### ISSUE TITLE
Change Password: after saving new password, user logout select not working unless refresh.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1000]
Change password, save, click username, nothing happens. Refresh page, now click username, gives select list.

**Comment by scolapasta** [comment]
@raprasad I know you made related fixes earlier - can we discuss?

**Comment by raprasad** [comment]
/cc @kcondon 
This appears to be working on mac firefox/safari/chrome.

**Comment by kcondon** [comment]
This issue as reported is resolved. The actual cause is clicking away from and then back to the landing tab of the selected user item: data related to me, notifications, account info.

So, if you click on the username, choose data related to me, you land on that tab. If you click another tab and then back to that one, the menus stop working. Clicking to another tab does not affect it. This happens with whichever tab you first select from the username menu: data related to me, notifications, account information.

Happens in Chrome and Firefox on Windows.

**Comment by raprasad** [comment]
@kcondon 
Able to reproduce the bug.  Checked in javascript which appears to fix the bug on mac browsers

**Comment by kcondon** [comment]
Works, closing
