### ISSUE TITLE
mvn -Pct clean package docker:run  error

### ISSUE THREAD

**Issue by zhaojc** [IQSS/dataverse#10011]
Failed to execute goal io.fabric8:docker-maven-plugin:0.43.0:build (default-build) on project dataverse: Execution default-build of goal io.fabric8:docker-maven-plugin:0.43.0:build failed: No <dockerHost> given, no DOCKER_HOST environment variable, no read/writable '/var/run/docker.sock' or '//./pipe/docker_engine' and no external provider like Docker machine configured ->

**Comment by pdurbin** [comment]
@zhaojc hi! I just wanted to mention that we talked about this issue yesterday: https://docs.google.com/document/d/1CT2HiulVF3DSto4GBOq6F6VcR724vyEdykY1o60I4xU/edit?usp=sharing

The recording is here if you're interested: https://harvard.zoom.us/rec/share/sXvYnt4ojCIePOafbYCnTp4Jvmuyd3dO6I2sRSP2U-jIkSPZV3q3DSrY2iN3kYLL.AythwksVvTKN3Lmk

I mentioned that @vera saw something similar here: https://dataverse.zulipchat.com/#narrow/stream/379673-dev/topic/Error.20when.20.20running.20.22mvn.20-Pct.20package.20docker.3Arun.22/near/393212857

If there's anything we should add to the documentation, please let us know!

**Comment by zhaojc** [comment]
@pdurbin Thank you for your reply. It is good now.
