### ISSUE TITLE
Support versions before a dataset is published

### ISSUE THREAD

**Issue by mercecrosas** [IQSS/dataverse#1002]
We want to be able to support multiple versions of a pre-published dataset.

Questions:
- what happens to the pre-published versions when you publish the dataset

**Comment by pdurbin** [comment]
@mercecrosas is this still something you're interested in?

**Comment by RightInTwo** [comment]
I would love to see this in regards to #5764

**Comment by pdurbin** [comment]
> b) tracking changes when passing on the data between different people in the curation process

There is some amount of tracking when a curator returns a dataset to an author. Via API a curator can include `reasonForReturn` as explained at http://guides.dataverse.org/en/4.15.1/api/native-api.html#return-a-dataset-to-author and note is saved in the `workflowcomment` database table: http://phoenix.dataverse.org/schemaspy/latest/tables/workflowcomment.html . This was implemented in #3943 and there's a lot of conversation about it at 'Help Wanted: stories related to "Submit for Review" and "Return to Author"' thread at https://groups.google.com/d/msg/dataverse-community/bGlCU2pbQpE/h3d9enX9AAAJ . There is demand for a GUI for the curator to be able to write this note, reflected in the following issue: Return to Author: When returning datasets that were submitted for review, I want to add a feedback note. #3702

**Comment by qqmyers** [comment]
FWIW: In QDR we've had some discussion on this - still thinking through the overall curation strategy, but if curators work in Dataverse to do things like replace files with archival versions, etc., having pre-publication versions would be a good way to track their efforts.

**Comment by RightInTwo** [comment]
And also, we will definitely have data that we cannot publish but still want to curate and archive. This would be a nice way to facilitate that.

**Comment by janetm** [comment]
hi All, I would like to re-engage with this issue.  I searched the community group for reference to dataset versioning PRE publication.  ADA uses a Dataverse installation dedicated for DEPOSITs only - so we do not want to publish data received as a SIP.  Data at the deposit stage has not been curated and should not be published.  Our use case closely matches QDR's functionality requirements described by qqmyers above:  "if curators work in Dataverse to do things like replace files with archival versions, etc., having pre-publication versions would be a good way to track their efforts.".

For ADA, it would be very useful to be able to 'set' the unpublished dataset as Version 1 for example, when the deposit is accepted as a SIP and is  moved to archival storage - without the requirement to 'publish'.  The main reason is to enable revised data files, or new waves/releases of a dataset to be deposited into the same DEPOSIT dataset to be recognised by Dataverse versioning for our automated workflow.

Does anyone else have a similar need for pre-publication versioning?

**Comment by pdurbin** [comment]
@janetm I don't know if this helps at all but from the software development perspective, I'm reminded of tags in Git. GitHub has conflated tags and releases a bit but with plain Git you can use tags to indicate the completion of some work, a milestone, or a significant event. I could make a tag called "ready-for-ui-review" or something. Git tags always have a date associated with them (as well as a commit, so you know its state exactly). Anyway, I can understand the need for this.

I guess my take is that maybe every edit within a draft is not so significant but at some point you might want to say, "Ok, I've fiddled with this dataset enough. I'd like the flag it now." Hmm, that makes me wonder. Have you played with the Curation Status Labels added in 5.7? I don't have a screenshot of the final product but here's one from pull request #7967 that gives the idea of how they look:

![126700233-639d56b0-214f-4172-8a29-92f2020bec45](https://user-images.githubusercontent.com/21006/145225632-074e6cfa-2719-436f-af94-ca8782b7dc7a.png)

You can read more about these curation labels at https://github.com/IQSS/dataverse/releases/tag/v5.7 and https://guides.dataverse.org/en/5.8/admin/dataverses-datasets.html?highlight=curation%20labels#configure-a-dataverse-collection-to-allow-use-of-a-given-curation-label-set

**Comment by qqmyers** [comment]
FWIW: The fact that those curation status labels can be read/set via API might help an external app keep track of pre-publication state. I.e. such an app could record the state of the metadata/files when the curation state changes to be able to show changes. (A nice addition would be to add an event trigger for such an app - currently changes to the curation state alerts curators/admins via notification/email but we don't yet have notification for apps beyond polling.)

In contrast, managing pre/no-publication versions within Dataverse could be more complex than it first appears. The basic idea of adding versions isn't so complex but I'm not sure if all the rules for versioning should apply, i.e. do prepublication versions include restriction and embargo settings that then become fixed (e.g. non-admins can't change the embargo for previously 'released' files which currently means files in non-draft versions). Should metadata exports be created? Do citations show any date? Is DataCite updated. What version numbers are allowed (0.1, 0.2, ...?), Do workflows run? Etc. I think these questions could probably be answered but making all of this functionality work with real versions in Dataverse makes this route a bigger dev task than it might seem.

**Comment by stevenmce** [comment]
Hi folks, it would be good to draw a distinction here between the process of curation and the preservation of versions. The tags would allow knowing where we are at - but the "tagged releases"/versions would allow preservation of the content at that point.

For ADA, we are interested as well in being able to distinguish SIPs, AIPs and DIPs - this is where the tagged versions would be of benefit.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
