### ISSUE TITLE
Support for s3 without tagging (e.g., s3 api on top of swift)

### ISSUE THREAD

**Issue by ErykKul** [IQSS/dataverse#10022]
**What steps does it take to reproduce the issue?**
When using an s3 implementation that does not support tagging, e.g., [s3 api](https://github.com/openstack/swift/tree/master/swift/common/middleware/s3api) of the [openstack swift](https://github.com/openstack/swift), you cannot use the upload-redirect feature. The uploads are prevented with "501: Not implemented" error.

**When does this issue occur?**
An error is thrown when uploading a file with upload-redirect feature turned on. This happens only on a Dataverse instance using an s3 implementation that does not support tagging. I have tested it with s3 on top of the openstack swift.

**Which page(s) does it occurs on?**
File upload

**What happens?**
 "501: Not implemented" error.

**To whom does it occur (all users, curators, superusers)?**
All users

**What did you expect to happen?**
I expect the upload to succeed.

**Which version of Dataverse are you using?**
Latest.

**Any related open or closed issues to this bug report?**
#9130
Since the solution to this problem is removing the tag header (I am working on a pull request for this issue that would add an option to disable tagging for uploads), a cleanup mechanism is needed to removed partially uploaded files, etc., since the `temp` tag would not be there anymore. That mechanism is already implemented in #9132 as a solution to the linked issue.

**Screenshots:**

![image](https://github.com/IQSS/dataverse/assets/101262459/ce794474-f16d-4f18-b496-e4cf8c7df407)

**Comment by pdurbin** [comment]
@ErykKul hmm, I wonder if we can join forces. I'm currently working on S3 tests here:

- https://github.com/IQSS/dataverse/issues/6783

@poikilotherm and I are talking about that issue at https://dataverse.zulipchat.com/#narrow/stream/375812-containers/topic/testing.20S3/near/396903562 and you're welcome to join!

Right now I'm testing with LocalStack, by the way.
