### ISSUE TITLE
Different contribution of mime type .wav

### ISSUE THREAD

**Issue by sbondka** [IQSS/dataverse#10032]
**What steps does it take to reproduce the issue?**
When I upload an audio file, Dataverse shows in the Type=audio/vnd.wave

* When does this issue occur? 
we have observed with the modification of the typemime on our servers, with the evolution of our JDK 

* Which page(s) does it occurs on?
![vnd_wave](https://github.com/IQSS/dataverse/assets/145585953/89119ec4-5163-467f-94a9-55099a7f0e8a)
 on the upload page for a [dataset]([url](![vnd_wave](https://github.com/IQSS/dataverse/assets/145585953/6e180588-cac1-4d07-92a6-1e2cf41bbfce)))

* What happens?

* To whom does it occur (all users, curators, superusers)?

* What did you expect to happen?
it must shows Type= Waveform Audio 

We propose two solutions to do:
Should we add the audio/vnd.wave type so that we will handle all the type of wav/vnd.wave/, or it's up to the dataverse side to force the audio/vnd.wave type.
Which solution you recommend?

**Which version of Dataverse are you using?** 5.14

**Any related open or closed issues to this bug report?**

**Screenshots:**

No matter the issue, screenshots are always welcome.

To add a screenshot, please use one of the following formats and/or methods described here:

* https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests
*

**Comment by sbondka** [comment]
@pdurbin 
Thank you for your prompt response.
In order to reproduce the issue and obtain the 'audio/vnd.wave' MIME type, we uploaded a file directly to S3 ([https://guides.dataverse.org/en/latest/developers/big-data-support.html#s3-direct-upload-and-download]) and we have redetected the type of a file following the documentation : [https://guides.dataverse.org/en/latest/api/native-api.html#redetect-file-type].
Upon testing, we received the following response:
{
  "status": "OK",
  "data": {
    "dryRun": true,
    "oldContentType": "audio/wav",
    "newContentType": "audio/vnd.wave"
  }
}
During our testing, we identified a missing MIME type return by Jhove(vnd.wave), and we believe it is necessary to update the 'MimeTypeDisplay.properties' file. Specifically, we propose adding the following configuration:
"audio/vnd.wave=Waveform audio".

Your attention to this matter is greatly appreciated, and we look forward to your guidance on the next steps to propose a pull request.
If you have any questions or require further information, please feel free to reach out.

Sabrine BONDKA.

**Comment by pdurbin** [comment]
@sbondka yes, sounds right.

Would you be able to provide a test file for us? Small, preferably. One whose content type is "audio/vnd.wave"?

**Comment by sbondka** [comment]
@pdurbin 
I wanted to provide an update regarding the MIME type detection process:

Any .wav file gets the audio/vnd.wave MIME type after redetection ( using Jhove ) (https://jhove.openpreservation.org/modules/wave/)
(https://guides.dataverse.org/en/latest/api/native-api.html#redetect-file-type))  (which is not consistent with the rest of Dataverse's properties).

**Comment by sbondka** [comment]
@pdurbin 

The file at (https://lasonotheque.org/detail-3019-sifflement-train-a-vapeur-7.html) initially had the MIME type audio/x-wav, but after redetection, it was transformed into audio/vnd.wave.

**Comment by pdurbin** [comment]
Thanks! I'm uploading a copy here for safe keeping: [TRNHorn_Sifflement train a vapeur 7 (ID 3019)_LS.wav.zip](https://github.com/IQSS/dataverse/files/13181547/TRNHorn_Sifflement.train.a.vapeur.7.ID.3019._LS.wav.zip)

**Comment by pdurbin** [comment]
Huh. I see what you mean. It's detected as "Waveform Audio" upon initial upload/save...

![Screenshot 2023-10-26 at 2 55 32 PM](https://github.com/IQSS/dataverse/assets/21006/6c37045d-3447-4667-95a9-290249043c7c)

... but the re-detect API wants to change the content type:

```
$ curl -s -H "X-Dataverse-key:$API_TOKEN" -X POST "$SERVER_URL/api/files/$ID/redetect?dryRun=true" | jq .
{
  "status": "OK",
  "data": {
    "dryRun": true,
    "oldContentType": "audio/x-wav",
    "newContentType": "audio/vnd.wave"
  }
}
```

I'm not sure what's going on, honestly. 🤔 

But yeah, like you said, a quick fix for how the file looks would be to add "audio/vnd.wave" to the property files.

I don't really like how the content type changes, though. Very strange. And mysterious.
