### ISSUE TITLE
Use try-with-resources to guarantee closing of JsonReader in .../api/DataSets.java

### ISSUE THREAD

**Issue by rtreacy** [IQSS/dataverse#10033]
**What steps does it take to reproduce the issue?** 
This issue is reported by running static analysis with SonarQube or SonarCloud

* When does this issue occur?
There are 7 occurrences of this code:
JsonObject json = Json.createReader(rdr).readObject(); 

in DataSets.java in the following methods -

public Response updateDraftVersion(...)
private Response processDatasetFieldDataDelete(...)
private Response processDatasetUpdate(...)
public Response createFileEmbargo(...)
public Response removeFileEmbargo(...)
public Response returnToAuthor(...)
public Response completeMPUpload(...)

* What happens?
This can prevent JsonReader objects from properly closing and being Garbage Collected and thus prevent referenced objects from being GCed as well.

**Comment by qqmyers** [comment]
As with earlier issues, replacing these with the appropriate JsonUtil method would be a good fix. https://github.com/IQSS/dataverse/blob/0af5caf98bccf6a296e5ded3475519fd201e1ea2/src/main/java/edu/harvard/iq/dataverse/util/json/JsonUtil.java#L62-L77

**Comment by bencomp** [comment]
Ah, this is the issue I didn't create for #9980. I think that PR fixes this.

**Comment by rtreacy** [comment]
Great, thanks for being proactive on this. We will be reviewing. #9980  soon
