### ISSUE TITLE
Fixing documentation to configure XLSX ingest

### ISSUE THREAD

**Issue by gwendoux** [IQSS/dataverse#10043]
* Which page(s) does it occurs on?
(https://guides.dataverse.org/en/latest/installation/config.html#tabularingestsizelimit)

* What happens?
When you want to configure XLSX extension ingestion by following the documentation, the command line returns good news, but XLSX is ingested with the default configuration.

* To whom does it occur (all users, curators, superusers)?
Admin

* What did you expect to happen?
The documentation give the extension in upper case and the command work with the extension in lower case

**Which version of Dataverse are you using?**
5.13

**Comment by bencomp** [comment]
I think you just opened #10049 to fix this issue, didn't you?

**Comment by gwendoux** [comment]
I did. I forgot to mentionned it‧ My bad

**Comment by bencomp** [comment]
No worries! If you add `closes #10043` to the text of the PR, it will create a special link that closes this issue when the pull request is merged.

**Comment by pdurbin** [comment]
@bencomp good catch. Thanks!

@gwendoux I added the "closes" magic to your PR. 😄
