### ISSUE TITLE
API: Duplicate dataverse aliases are allowed via api

### ISSUE THREAD

**Issue by esotiri** [IQSS/dataverse#1004]
Creating dataverse via api allows duplicate alias.  I created many dv with the same alias via api below. 

curl -H "Content-type:application/json" -X POST -d @eso_dv.json  http://$host/api/dvs/root?key=$token

**Comment by kcondon** [comment]
OK this works, prevents duplicate alias with error: 

{"status":"ERROR","message":"Creating Dataverse: Bad Request (A dataverse with alias kctest already exists)"}

Closing
