### ISSUE TITLE
Use try-with-resources to close JsonReader "report = Json.createReader(reader).readObject();" in method addUsageMetricsFromSushiReport(...) and to close JsonReader "report = Json.createReader(reader).readObject();" in method ddUsageMetricsFromSushiReportAll(...) and to close JsonReader "JsonObject report = Json.createReader(connection.getInputStream()).readObject();" in  method updateCitationsForDataset(...) in MakeDataCountApi.java

### ISSUE THREAD

**Issue by rtreacy** [IQSS/dataverse#10056]

**Comment by bencomp** [comment]
Oh, I missed a few of these in #9980! (#10054 is very similar)

Are you working on this already?

**Comment by qqmyers** [comment]
In general, issues still in the Dataverse_Global_Backlog board shouldn't be being worked on by anyone in the core team, so unless there's an assignment or chatter in the issue, I think you can consider it open.

**Comment by pdurbin** [comment]
Related:

- #9157

**Comment by rtreacy** [comment]
Every one of these you work on, let us know. We'll get them into ready for review and Jim can push them across the line

**Comment by bencomp** [comment]
I just marked #10062 ready for review 😃
