### ISSUE TITLE
Deployment 6.0 fails: java.lang.reflect.InaccessibleObjectException

### ISSUE THREAD

**Issue by lmaylein** [IQSS/dataverse#10068]
Hi,

I tried to update from 5.14 to 6.0 on our test server but the deployment of dataverse-6.0.war fails:

I followed the instructions at https://github.com/IQSS/dataverse/releases/tag/v6.0 step by step.

```
java -version
java version "17.0.8" 2023-07-18 LTS
Java(TM) SE Runtime Environment (build 17.0.8+9-LTS-211)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.8+9-LTS-211, mixed mode, sharing)
```
This results in

```
  Exception while loading the app
java.lang.reflect.InaccessibleObjectException: Unable to make private static java.lang.ClassLoader java.io.ObjectInputStream.latestUserDefinedLoader() accessible: module java.base does not "opens java.io" to unnamed module @7101112b
```

complete server.log:

[server.log](https://github.com/IQSS/dataverse/files/13205829/server.log)

**Comment by pdurbin** [comment]
@lmaylein did you run this command?

`sudo -u dataverse /usr/local/payara6/bin/asadmin create-jvm-options --add-opens=java.base/java.io=ALL-UNNAMED`

In the 6.0 release notes, as of this writing, it's step 15: Enable workaround for FISH-7722. The following workaround is for https://github.com/payara/Payara/issues/6337

**Comment by pdurbin** [comment]
@lmaylein hmm, Good idea. In the same step I just added that you should restart Payara:

```
1. Enable workaround for FISH-7722.

   The following workaround is for https://github.com/payara/Payara/issues/6337

   `sudo -u dataverse /usr/local/payara6/bin/asadmin create-jvm-options --add-opens=java.base/java.io=ALL-UNNAMED`

   Afterwards, you must restart Payara.

   `sudo -u dataverse /usr/local/payara6/bin/asadmin stop-domain`

   `sudo -u dataverse /usr/local/payara6/bin/asadmin start-domain`

```

**Comment by lmaylein** [comment]
Thanks! The deployment worked without any problem afterwards.
