### ISSUE TITLE
Automatically add "Bug:Type" issue label to new bug issues

### ISSUE THREAD

**Issue by ysuarez** [IQSS/dataverse#10065]
@pdurbin mentioned that it would be nice to have new "bug report" issues to automatically get the "Bug:Type" label assigned automatically. 

I will be adding a PR in a few moments that should allow this.

**Comment by pdurbin** [comment]
Works great! I put a screenshot here: https://github.com/IQSS/dataverse/pull/10066#issuecomment-1785218856

@DS-INRA if you want to create issues or PRs for the other two, please go ahead!
