### ISSUE TITLE
Feature Request/Idea: Dissociate and label issue templates for Features & Ideas

### ISSUE THREAD

**Issue by DS-INRA** [IQSS/dataverse#10069]
**Overview of the Feature Request**
Split the currently unique Feature request issue template in two :
- name: Feature request
  - about: Suggest a new feature for the Dataverse software!
  - label: Type: Feature (edit:) done via #10081
- name: Idea proposal
  - about: Propose a new idea for discussion to improve the Dataverse software!
  - label: Type: Suggestion

**What kind of user is the feature intended for?**
(Example users roles: API User, Curator, Depositor, Guest, Superuser, Sysadmin)
Developers

**Any open or closed issues related to this feature request?**
This label attribution has already been done for bugs (edit:) & Features here :
- https://github.com/IQSS/dataverse/issues/10065
- #10081

**Comment by pdurbin** [comment]
This is a good point. We have two related types (feature vs. suggestion) but only one template (feature request/idea). Probably these were set up by different people. 😄 

Sure, maybe a good next step would be to have a template for each.

**Comment by DS-INRA** [comment]
Label for the existing Feature template has been added in #10081 👍

**Comment by pdurbin** [comment]
Yes! Thanks to @ysuarez! ❤️ 

For now I think it's fine to have non-bugs come in as features. We can always flip some of them to suggestions manually.

That said, @DS-INRA if you feel strongly about splitting the non-bug template, please feel free to make a pull request. 😄

**Comment by DS-INRA** [comment]
I agree that it would work as is but still think it's better if we can go the extra mile with a distinction from the start so I added the extra template :smile: .
Out of topic for today, but the issue forms look very nice for future use when they will be out of beta :eyes: .
