### ISSUE TITLE
Feature Request/Idea: group/group member management ui

### ISSUE THREAD

**Issue by jump2cn** [IQSS/dataverse#10073]
**Overview of the Feature Request**
website manager can add/delete group/group members in the website UI

**What kind of user is the feature intended for?**
Superuser

**What inspired the request?**
website manager may not have any IT skills to add groups via API, 

**What existing behavior do you want changed?**
nothing

**Any brand new behavior do you want to add to Dataverse?**
a group/group member manage page to modify those things

**Any open or closed issues related to this feature request?**
nothing

**Comment by pdurbin** [comment]
@jump2cn hi! I'm confused. You should be able to CREATE groups via UI, at least:

![Screenshot 2023-10-31 at 2 00 12 PM](https://github.com/IQSS/dataverse/assets/21006/a43c2bb2-a5f6-423c-afdb-1c9b6a625053)

That said, there are some old old issues about deleting, etc:

- #2413

**Comment by jump2cn** [comment]
thank you @pdurbin , I'm not familiar enough with using Dataverse, that your point is what I want 😁

I will close this issue.

**Comment by pdurbin** [comment]
No worries! Please keep the questions coming!
