### ISSUE TITLE
Upgrade 5.14 -> 6.0 Reindexing with solr 9.3.0 works but frontend shows 0 dataverses and 0 datasets

### ISSUE THREAD

**Issue by lmaylein** [IQSS/dataverse#10078]
As the last step of the upgrade from 5.14 to 6.0, I did a re-indexing with SOLR 9.3.0. This also apparently worked and I can find the corresponding index docs via SOLR Admin interface. There are no differences between the new index docs and the corresponding index docs of the old SOLR 8.11.1 installation (or I don't see the differences).
Unfortunately, the interface still does not display dataverses and datasets after indexing is complete.

![indexing](https://github.com/IQSS/dataverse/assets/7468155/b89ffd16-248b-494c-abe6-f1a2df7061ba)

![indexing2](https://github.com/IQSS/dataverse/assets/7468155/a10286c7-b971-4fad-b486-7ac9a18a5879)

What could be the reason for this? Did I miss something in the instructions?

**Comment by landreev** [comment]
Sorry for asking stupid questions, but just to get it out of the way, you're positive that `http://localhost:8983` you are accessing directly and the solr server your Dataverse instance is trying to use is the same thing?

**Comment by pdurbin** [comment]
One more question for you... does the Search API work?

**Comment by lmaylein** [comment]
I am very sorry that I did not check the server.log first.
This is, was the server.log says:

```
[2023-10-31T21:45:02.878+0100] [Payara 6.2023.8] [INFO] [] [edu.harvard.iq.dataverse.search.SearchServiceBean] [tid: _ThreadID=103 
_ThreadName=http-thread-pool::jk-connector(2)] [timeMillis: 1698785102878] [levelValue: 800] [[
  Search Syntax Error: Error from server at http://localhost:8983/solr/collection1: Expected mime type in [application/octet-stream
, application/vnd.apache.solr.javabin] but got text/html. <h1>Bad Message 414</h1><pre>reason: URI Too Long</pre>]]

[2023-10-31T21:45:02.879+0100] [Payara 6.2023.8] [INFO] [] [edu.harvard.iq.datav
erse.search.SearchIncludeFragment] [tid: _ThreadID=103 _ThreadName=http-thread-pool::jk-connector(2)] [timeMillis: 1698785102879] [levelValue: 800] [[
  Search Syntax Error: Error from server at http://localhost:8983/solr/collection1: Expected mime type in [application/octet-stream, application/vnd.apache.solr.javabin] but got text/html. <h1>Bad Message 414</h1><pre>reason: URI Too Long</pre>]]

[2023-10-31T21:45:02.900+0100] [Payara 6.2023.8] [INFO] [] [edu.harvard.iq.dataverse.search.SearchServiceBean] [tid: _ThreadID=103 _ThreadName=http-thread-pool::jk-connector(2)] [timeMillis: 1698785102900] [levelValue: 800] [[
  Search Syntax Error: Error from server at http://localhost:8983/solr/collection1: Expected mime type in [application/octet-stream, application/vnd.apache.solr.javabin] but got text/html. <h1>Bad Message 414</h1><pre>reason: URI Too Long</pre>]]

[2023-10-31T21:45:02.901+0100] [Payara 6.2023.8] [INFO] [] [edu.harvard.iq.dataverse.search.SearchIncludeFragment] [tid: _ThreadID=103 _ThreadName=http-thread-pool::jk-connector(2)] [timeMillis: 1698785102901] [levelValue: 800] [[
  Search Syntax Error: Error from server at http://localhost:8983/solr/collection1: Expected mime type in [application/octet-stream, application/vnd.apache.solr.javabin] but got text/html. <h1>Bad Message 414</h1><pre>reason: URI Too Long</pre>]]

```

The reason is a copy and paste mistake when setting requestHeaderSize in jetty.xml:

`<Set name="requestHeaderSize"><Property name="solr.jetty.request.header.size" default="02400" /></Set>`

"02400" instead of "102400".

Sorry again. I should have noticed that myself.

**Comment by pdurbin** [comment]
No worries! Thanks for letting us know!
