### ISSUE TITLE
"Incomplete metadata" label on published datasets

### ISSUE THREAD

**Issue by haarli** [IQSS/dataverse#10116]
We recently set a metadata field to "required", which was "optional" before. Since v 5.14, this leads to the undesired effect that all formerly published datasets without this field show the "Incomplete metadata" label. The label is visible for every user on the published dataset page.

We were wondering if this behaviour is intended. In our opinion, it might be confusing for external users and should only be displayed for draft versions.

Example: 
https://edmond.mpg.de/dataset.xhtml?persistentId=doi:10.17617/3.UV4FBN

![grafik](https://github.com/IQSS/dataverse/assets/5524896/29e05f5f-df12-4b2b-a186-bee6fcd9809d)

**Comment by pdurbin** [comment]
Huh. Probably not! @ErykKul @DieuwertjeBloemen have you seen this?

**Comment by ErykKul** [comment]
This is not intended. I agree that it should be only visible in draft versions. I will make a pull request for this.

**Comment by haarli** [comment]
@ErykKul Thank you!

**Comment by poikilotherm** [comment]
May I ask to make this behavior configurable and/or visible to a logged in user with permissions on the dataset?

Usually, when a metadata schema changes a field from optional to required, as contributors/curators you might want to see this kind of Information, maybe also be able to make it a fragment to see all things that need attention at once.

**Comment by ErykKul** [comment]
Thanks, @poikilotherm 
As for the fragment, you can already do that in the "My Data" filters:
![image](https://github.com/IQSS/dataverse/assets/101262459/34b4d757-4525-4736-8d26-b69df1b37832)

**Comment by ErykKul** [comment]
I will make the rule that makes the label visible for all draft datasets and, if not draft, only when the permission is configured.

**Comment by lmaylein** [comment]
Okay. Apparently we have a problem with these old data sets with the metadata Geographic Bounding Box.

"Geographic Bounding Box has invalid coordinates. East must be greater than West and North must be greater than South. Missing values are NOT allowed."

You only see this when you try to save the metadata again.
But of course it's not so nice that the affected datasets are then silently no longer listed.

**Comment by DieuwertjeBloemen** [comment]
I believe the addition of validation on the geographic bounding box fields was added quite recently (I believe in 5.13) for some new functionality to do with geospatial information by @pdurbin. We had some errors from that at the time and had to manually correct the records too (@Kris-LIBIS might remember more of the technical details). I think even it remaining in a previous version of the dataset caused issues at the time for us somewhere.

**Comment by pdurbin** [comment]
> "Geographic Bounding Box has invalid coordinates. East must be greater than West and North must be greater than South. Missing values are NOT allowed."

This error and related validation was added in this pull request for 6.1:

- #10142

I hope this helps!

**Comment by lmaylein** [comment]
Thank you very much. Do you have any tips on how we can find the datasets affected?

**Comment by pdurbin** [comment]
@lmaylein I don't off the top of my head, sorry. Can you please create a new issue for this? It sounds like we should add something to the 6.1 upgrade instructions.

**Comment by mdmADA** [comment]
@pdurbin - note that the 'Incomplete metadata' tag is also calculated on the fly for dataset.xhtml and is displayed for the dataset if the metadata is deemed invalid (dataset.xhmtl code, line 146: rendered="{!valid}" ) and for all users.

For example, some datasets published on ADA's previous Dataverse version had metadata consisting of url's with leading spaces that passed the publication process with the previous Dataset version but is now being picked up as "not valid" so the "Incomplete metadata" tag is applied.

Also, if there is a mismatch between the policy/license and or Terms of Access (or missing Terms) when a dataset is restricted, then the "Incomplete metadata" tag is also applied. 

So the 'Incomplete metadata' is displayed for incomplete metadata, invalid metadata, or a mismatch between licence and Terms of Access.

**Comment by pdurbin** [comment]
@mdmADA thanks. I think (and hope) that @ErykKul fixed all this in Dataverse 6.3 with this pull request:

- #10172

If anything fell through the cracks, please open a new issue! 😅
