### ISSUE TITLE
ProvIT test failing due provenance metadata being disabled.

### ISSUE THREAD

**Issue by jp-tosca** [IQSS/dataverse#10112]
**What steps does it take to reproduce the issue?**
Execute the ProvIT test

* When does this issue occur?
When running the ProvIT test

* Which page(s) does it occurs on?
n/a

* What happens?
{
"status": "ERROR",
"message": "This functionality has been administratively disabled."
}

* To whom does it occur (all users, curators, superusers)?
All users

* What did you expect to happen?
The test should be completed successfully. 

**Which version of Dataverse are you using?**
6.0

**Any related open or closed issues to this bug report?**
No

**Screenshots:**

No matter the issue, screenshots are always welcome.

To add a screenshot, please use one of the following formats and/or methods described here:

* https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests
*

**Comment by pdurbin** [comment]
@jp-tosca I'm taking this off the board now that there's a PR:

- #10113
