### ISSUE TITLE
Premature validation of dataset metadata (single value drop down) prevents template selection

### ISSUE THREAD

**Issue by jo-pol** [IQSS/dataverse#10119]
### What steps does it take to reproduce the issue?

Preparations (while logged in on on https://demo.dataverse.org ):
- create a new dataverse, under metadatafields
  - deselect “Use metadata fields from Demo Dataverse“
  - select “Journal metadata“ and make “type of article required“
- Create a new template in the new dataverse with some value in the title of the citation metadatablock of the template

Scenario 1a
- in the new dataverse, under "_add data_" select "_new dataset_"
- don't fill in any fields
- save the dataset

Scenario 1b (follow up of 1a)
- fix the "type of article"
- save again

Scenario 2a
- in the new dataverse, under "_add data_" select "_new dataset_"
- don't fill in any fields
- select the template

Scenario 2b (follow up of 2a)
- fix the "type of article"
- select the tamplate

#### When does this issue occur?

See preparations above

#### Which page(s) does it occurs on?

See scenario's above

#### What happens?

Scenario 1a/2a: The page scrolls down with the screenshot just out of sight.

Scenario 1b: The page scrolls back to the top with a red error message "...required fields were missed..."

Scenario 2b: The page scrolls back to the top and the title form the template is filled in.

While debuging, I also noticed a lot of server side validation occurred when selecting "new dataset" under "add data". Though it does not cause error messages for the end user, it does not make sense to me. Similarly, I don't expect any validation when selecting a new template as all data is cleared and replaced anyway. 

#### To whom does it occur (all users, curators, superusers)?

Depositors

#### What did you expect to happen?

Scenario 1a: as scenario 1b including a red message "_Type of Article is required_", not just the button highlighted in red what is easily overlooked.

Scenario 2a: the title of the template is filled in for the new dataset  

### Which version of Dataverse are you using?

v. 6.0 build 1512-366fd41

### Any related open or closed issues to this bug report?

https://github.com/IQSS/dataverse/issues/2190 The premature validation causes scrolling to the missing required filed, but just too little.

### Screenshots:

![image](https://github.com/IQSS/dataverse/assets/10553630/43f2d05a-5c02-452d-b408-797affb5525f)

**Comment by jo-pol** [comment]
I tried a dirty hack on a DANS development environment and changed the `required` attribute to false in the deployed [metadataFragment.xhtml](https://github.com/DANS-KNAW/dataverse/blob/0b0f8bc0db89319137c986a36771266acfe894f6/src/main/webapp/metadataFragment.xhtml#L287-L288) and rebooted the server. To my surprise the red required mark still showed up and at first sight it caused the desired behavior in both scenarios. I'm afraid this might have undesired effects in other situations.

**Comment by qqmyers** [comment]
A clearer test case: as in scenario 1, have a required field in another metadatablock (e.g. type of article) and a template that should set a field(s) in the citation block (e.g. title). When you create a new dataset and select the template, the page updates but the template fields are not filled in (e.g. no title appears). The page also scrolls down to the missing required field in the other block and the page is left showing that the template is in use when it has not been applied.

**Comment by jo-pol** [comment]
A sharp observation that I overlooked: the page is left showing that the template is in use when it has not been applied.

Scenario one is our blocking problem. Scenario two helped me to realize there are two phases of validation. One phase controlled by `required` attributes in the XHTML, another phase controlled by the tsv's/db-table `datasetfieldtype`.

**Comment by jggautier** [comment]
Hi @jo-pol. I've been following this issue because I noticed part of what you've written and what your screenshot shows, that when someone tries to save a dataset where they haven't filled in a required "single value dropdown" field, the validation error is only that the dropdown button is highlighted in red, "which is easily overlooked" and doesn't match the error messages that Dataverse shows for other types of fields that have some sort of validation. It's an error that some users of Harvard Dataverse will see since the repository is adding a required "single value dropdown" field (https://github.com/IQSS/dataverse.harvard.edu/issues/232).

Will your PRs address this, too? Or should another GitHub issue be opened about making it easier for users to see when they need to choose an option from a "single value dropdown" field in order to save the dataset?

**Comment by jo-pol** [comment]
fixed by https://github.com/IQSS/dataverse/commit/caf2d91c234cd2a16930d1211c5e1b3b2b8e5a46 on the following branches
iqss/beta-deploy
iqss/develop
iqss/master

**Comment by qqmyers** [comment]
@jo-pol - thanks for verifying that this has been fixed. Closing.

**Comment by pdurbin** [comment]
I see. It was fixed in 6.2 by this commit: https://github.com/IQSS/dataverse/pull/10401/commits/caf2d91c234cd2a16930d1211c5e1b3b2b8e5a46

I guess I'll add the 6.2 milestone.
