### ISSUE TITLE
JDD Metrics: Label KO

### ISSUE THREAD

**Issue by sbondka** [IQSS/dataverse#10123]
In the display within the metric block under "download," there is a parenthesis that appears. Please refer to the attached screenshot for clarification. Thank you.
![Capture3](https://github.com/IQSS/dataverse/assets/145585953/f48bdce5-f8d3-409f-bbd7-374927774232)

**Comment by qqmyers** [comment]
What Dataverse version is this? I don't see the issue on demo.dataverse.org (where Make Data Counts is not enabled), nor do I see it at QDR (which is a fork but doesn't appear to have differences in this part of the dataset.xhtml file or the Bundle.properties where the formatted strings come from). It's possible that older versions had this issue and it has been fixed.
