### ISSUE TITLE
Support for exporting bibtex data citation

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#1013]
Previously in #881 I was unable to figure out a proper data citation export into bibtex. However, I now found an example from [DataCite](http://data.datacite.org/10.7910/DVN/24017) on how to export a Dataverse data citation to bibtex format.

```
@data{data,
  doi = {10.7910/DVN/24017},
  url = {http://dx.doi.org/10.7910/DVN/24017},
  author = {Beber, Bernd, Roessler, Philip, Scacco, Alexandra; },
  publisher = {Harvard Dataverse},
  title = {Replication data for: Intergroup Violence and Political Attitudes: Evidence from a Dividing Sudan},
  year = {2013}
}
```

**Comment by posixeleni** [comment]
DataCite is already exporting our data citations in bibtex format so we can model it off what they already do: http://data.datacite.org/10.7910/DVN/G4FFVL

```
@data{9828e9f5-196c-404a-89c2-5761df6f19cc,
  doi = {10.7910/DVN/G4FFVL},
  url = {http://dx.doi.org/10.7910/DVN/G4FFVL},
  author = {Sсhmerling, Dmitry S. (National Research University Higher School of Economics, Moscow, Russia.); },
  publisher = {Harvard Dataverse},
  title = {New model of understanding income distribution through graduation of normalized Gini Mean Difference},
  year = {2015}
}
```

**Comment by pdurbin** [comment]
@pameyer just mentioned this is something @sbgrid is interested in and @bmckinney said to go ahead and assign this issue to him.

**Comment by bmckinney** [comment]
@posixeleni and @pdurbin, how does something like this look?
In particular, is the bibtex key and multi-author formatting acceptable?
```
@data{P4Y0XE_2016,
  author = {Smith, Jane and Doe, John},
  publisher = {Root Dataverse},
  title = {Test data},
  year = {2016},
  doi = {10.5072/FK2/P4Y0XE},
  url = {http://dx.doi.org/10.5072/FK2/P4Y0XE}
}
```

**Comment by posixeleni** [comment]
@bmckinney This looks great! The only thing I would change is for multiple
authors I would follow what DataCite is doing (
http://data.datacite.org/10.3886/ICPSR01218) and separate each of them with
a semi-colon

```
@data{ea87f5a5-2a54-4616-86e4-45592b340d76,
  doi = {10.3886/ICPSR01218},
  url = {http://dx.doi.org/10.3886/ICPSR01218},
  author = {Beck, Nathaniel L.; King, Gary; Zeng, Langche; },
  publisher = {ICPSR - Interuniversity Consortium for Political and Social
Research},
  title = {Improving Quantitative Studies of International Conflict: A
Conjecture},
  year = {2000}
}
```

On Tue, Mar 15, 2016 at 12:42 PM, bmckinney <notifications@github.com>
wrote:

> @posixeleni
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_posixeleni&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=OiTcIL_jSSCUW82Gf-OSkgnZLbG2Yt87eT87BdLiP54&m=ZaEyqNZCGHBpd_05YWMVd-t6krLQ67uzM8EJq4ZanJE&s=MGMp7AjX2QQhRX1ytlpgbBxVJ61W4Ru-KzIHBNWqERE&e=>
> and @pdurbin
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_pdurbin&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=OiTcIL_jSSCUW82Gf-OSkgnZLbG2Yt87eT87BdLiP54&m=ZaEyqNZCGHBpd_05YWMVd-t6krLQ67uzM8EJq4ZanJE&s=3tvD5SRWNegrBvtF8Xb2zb0tuhTVI4pJa3cSuZD_mp0&e=>,
> how does something like this look?
> In particular, is the bibtex key and multi-author formatting acceptable?
>
> @data{P4Y0XE_2016,
>   author = {Smith, Jane and Doe, John},
>   publisher = {Root Dataverse},
>   title = {Test data},
>   year = {2016},
>   doi = {10.5072/FK2/P4Y0XE},
>   url = {http://dx.doi.org/10.5072/FK2/P4Y0XE}
> }
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/IQSS/dataverse/issues/1013#issuecomment-196915024
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_issues_1013-23issuecomment-2D196915024&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=OiTcIL_jSSCUW82Gf-OSkgnZLbG2Yt87eT87BdLiP54&m=ZaEyqNZCGHBpd_05YWMVd-t6krLQ67uzM8EJq4ZanJE&s=Y9ZYkdxZfLEK57mNSRemNJAeps5c8fOeD2vYV3yE7us&e=>
>



-- 

Eleni Castro
Research Coordinator, Data Curation and Outreach
IQSS, Harvard University
617-496-0703
http://www.iq.harvard.edu/people/eleni-castro
http://orcid.org/0000-0001-9767-8536


~Got Data? Check out the Dataverse Project. <http://dataverse.org/>~

**Comment by bmckinney** [comment]
Thanks, sounds good.

Keep in mind that "and" has long been the default bibtex separator for multiple authors: https://en.wikipedia.org/wiki/BibTeX#Author_formatting

Users of biblatex or biber might have issues with alternative separators.

**Comment by kcondon** [comment]
Tested, works, closing.

**Comment by mfenner** [comment]
We at DataCite have finally fixed several long-standing bugs with the bibtex output of our metadata. Author names should be separated by `and`. See for example

```
curl http://doi.org/10.3886/ICPSR01218 -H "Accept: application/x-bibtex" -L
```
@misc{https://doi.org/10.3886/ICPSR01218,
  doi = {10.3886/ICPSR01218},
  url = {https://doi.org/10.3886/ICPSR01218},
  author = {Beck, Nathaniel L. and King, Gary and Zeng, Langche},
  publisher = {ICPSR - Interuniversity Consortium for Political and Social Research},
  title = {Improving Quantitative Studies of International Conflict: A Conjecture},
  year = {2000}
}
```

We also now use the DOI as bibtex key (unconventional, but better than a random UUID that changes on every request), and we properly escape special characters for Latex.

**Comment by sbarbosadataverse** [comment]
Thanks, Martin! This is good to know!

On Wed, Aug 24, 2016 at 1:38 PM, Martin Fenner <notifications@github.com>
wrote:

> We at DataCite have finally fixed several long-standing bugs with the
> bibtex output of our metadata. Author names should be separated by and.
> See for example
>
> curl http://doi.org/10.3886/ICPSR01218 -H "Accept: application/x-bibtex" -L
>
> @misc
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_misc&d=CwMFaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=NIGjmFLkyMgCokX5wNxbgXaZKUeSYrp5FegnttpJcz8&s=YVz99FC3IELR9acZTx5aHhY8LrfHCHvj-63vtR8aMOI&e=>
> {https://doi.org/10.3886/ICPSR01218
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__doi.org_10.3886_ICPSR01218&d=CwMFaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=NIGjmFLkyMgCokX5wNxbgXaZKUeSYrp5FegnttpJcz8&s=d5TRvh9mBoDvmgFgU21vgJ_2Y3l-tyoEllIT4aVNNfM&e=>
> ,
> doi = {10.3886/ICPSR01218},
> url = {https://doi.org/10.3886/ICPSR01218
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__doi.org_10.3886_ICPSR01218&d=CwMFaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=NIGjmFLkyMgCokX5wNxbgXaZKUeSYrp5FegnttpJcz8&s=d5TRvh9mBoDvmgFgU21vgJ_2Y3l-tyoEllIT4aVNNfM&e=>
> },
> author = {Beck, Nathaniel L. and King, Gary and Zeng, Langche},
> publisher = {ICPSR - Interuniversity Consortium for Political and Social
> Research},
> title = {Improving Quantitative Studies of International Conflict: A
> Conjecture},
> year = {2000}
> }
>
>
> We also now use the DOI as bibtex key (unconventional, but better than a random UUID that changes on every request), and we properly escape special characters for Latex.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_issues_1013-23issuecomment-2D242148386&d=CwMFaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=NIGjmFLkyMgCokX5wNxbgXaZKUeSYrp5FegnttpJcz8&s=O20748BRysxk_W8XmXFCX3iuRGXbNsgL7mijy-R25E8&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AH79Kt5zChYNwcBbRQY7e2hhKa3xx2B4ks5qjIGzgaJpZM4C0APz&d=CwMFaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=NIGjmFLkyMgCokX5wNxbgXaZKUeSYrp5FegnttpJcz8&s=alhW5irrzal1L6mhf_KQAcB5OjV9MdA5o1Xi00aY5Fk&e=>
> .
>



-- 
Sonia Barbosa
Manager of Data Curation, The Dataverse Project
Manager of the Murray Research Archive, IQSS
Data Science
Harvard University

Dataverse 4.0 is now available for use!
http://dataverse.harvard.edu

All test dataverses should be created  in 4.0 Demo!
http://dataverse-demo.iq.harvard.edu/

Join our Dataverse Community!
https://groups.google.com/forum/#!forum/dataverse-community

**Comment by sbarbosadataverse** [comment]
@kcondon @djbrooke  do we need to reopen this ticket per the last comment?

**Comment by djbrooke** [comment]
Thanks all. I created a new ticket that we'll get into the next small release.
