### ISSUE TITLE
Can't generate sitemap due to issue validating xml against remote schema

### ISSUE THREAD

**Issue by bricas** [IQSS/dataverse#10143]
I am able to start the sitemap generation, but the logs show that the process has failed with the following error:

[2023-11-27T10:29:56.712-0400] [Payara 5.2022.3] [WARNING] [] [edu.harvard.iq.dataverse.sitemap.SiteMapUtil] [tid: _ThreadID=211 _ThreadName=__ejb-thread-pool7] [timeMillis: 1701095396712] [levelValue: 900] [[
  Unable to update sitemap! Exception caught while checking XML staged file (/var/opt/payara5/glassfish/domains/domain1/docroot/sitemap/sitemap.xml.staged ) against XML schema: schema_reference.4: Failed to read schema document 'https://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.]]

FWIW, I can download the schema locally (on the same host as our dataverse) and validate the xml without issue.

**Comment by pdurbin** [comment]
@bricas thanks for opening this issue. As I said at https://dataverse.zulipchat.com/#narrow/stream/378866-troubleshooting/topic/Sitemap.20generation.20error/near/404424858 I'm really not sure what's going on.

Maybe others will have some ideas.

Worst case, maybe we could add a setting to turn off validation?

**Comment by bricas** [comment]
I forgot to add my DV version: v. 5.14 build 1471-9f4ddbb (we're not quite ready to move to 6)

**Comment by donsizemore** [comment]
@bricas hello, have you tried https://github.com/IQSS/dataverse/issues/8950#issuecomment-1233286517 ?

**Comment by pdurbin** [comment]
@bricas do you think this information should be in the guides? (And are you interested in making a pull request?) Or should we just point people to that issue? (We can probably close that issue if we aren't going to add any docs.)

I don't have a sense of if people are using old JVMs or what. We don't see this problem on our test servers. 🤔

**Comment by qqmyers** [comment]
FWIW: The cacerts file that's involved is part of the payara domain, so if you've followed the update guidance to copy the old domain when updating, you could have the old one. Presumably this stops with 6.0 as the instructions don't involve reusing the old domain.

**Comment by pdurbin** [comment]
@qqmyers oh! That's great news!
