### ISSUE TITLE
replace Dockerfile in root with docker dir, mention Docker in main README

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#10157]
notes in https://docs.google.com/document/d/1V4T2JA8O36PZEDLvnioaR06o7j5B_68cSrS09bte51Q/edit?usp=sharing

More notes in https://docs.google.com/document/d/1WfUj3fn4RU3ZmdkgmNIbWu2uvD_zU9Y3h3MT5X6TzCI/edit?usp=sharing

**Comment by kuhlaid** [comment]
I'm in favor. Whether a `docker` directory resides at the root of the repository or some sub-folder such as `modules` (especially if we are adding other container platform configurations such as OpenShift later) does not matter so much for me. I would vote for any compose or Docker files but moved out of the root directory of the repository and into the docker directory so we do not pollute the root.

**Comment by poikilotherm** [comment]
I started a small experiment: https://github.com/IQSS/dataverse/compare/develop...poikilotherm:dataverse:10157-dockerdir

**Comment by pdurbin** [comment]
As of this PR we have a "docker" directory at the root level of the repo:

- #10273

I borrowed from Oliver's branch above when I comes to file paths such as `docker/compose/demo/compose.yml`.

I didn't grab the fancy stuff from that branch though, the includes and overrides.

Anyway, we're in a better spot for continuing this work.

If we'd like a very narrow scope, we could simply create a PR to

- remove the (dummy) Dockerfile in the root
- add docker/README.md to link to https://guides.dataverse.org/en/latest/container
