### ISSUE TITLE
add Visual Studio Code to guides

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#10156]
Historically we've talked about Netbeans in the guides but we started writing about IntelliJ here:

- #10102

Let's also add some docs for VS Code, especially any tips for fast redeployment.

**Comment by jp-tosca** [comment]
I would also like to add to the VS-Code guide the setup you need to debug on the containers:

```
{
    "type": "java",
    "name": "Debug (Attach) - Remote",
    "request": "attach",
    "hostName": "localhost",
    "port": 9009
}
```

**Comment by pdurbin** [comment]
I'm not using VS Code myself. Closing. Someone who does use it is welcome to open a fresh issue! 😄

**Comment by pdurbin** [comment]
I tried deploying to Docker but I get an error when connecting: a8432ae

@ErykKul have you had any luck with this?

We also have a thread going here: https://dataverse.zulipchat.com/#narrow/channel/375812-containers/topic/fast.20redeploy.20with.20VS.20Code.20.28.2310156.29/with/543285645

**Comment by pdurbin** [comment]
Instead of documenting a workflow with VS Code specifically, we now have a command line fast redeploy that is IDE-independent:

- #11961 

Thanks, @ErykKul!
