### ISSUE TITLE
getDatasetVersionArchivalStatus API give blank response when archival copy location is null

### ISSUE THREAD

**Issue by sekmiller** [IQSS/dataverse#10168]
**What steps does it take to reproduce the issue?**
Call the getDatasetVersionArchivalStatus api 

EX: curl -H "X-Dataverse-key:2b3b0a53-2740-450f-b7eb-a84551f667dc" -H "Accept:application/json" "http://localhost:8080/api/datasets/:persistentId/1.0/archivalStatus?persistentId=doi:10.5072/FK2/WJASHX"

If the getArchivalCopyLocation method returns null then the response is empty. The calling user just sees the prompt - with no error or any visible response

* When does this issue occur? See above

* Which page(s) does it occurs on? not a page - api

* What happens? response is completely empty/blank

* To whom does it occur (all users, curators, superusers)? api users with publish dataset perms

* What did you expect to happen? would like to get an error response telling me that the archival version is not available. 
      By the way changing the status of this line in Datasets.java: 

        return error(Status.NO_CONTENT, "This dataset version has not been archived");

       to 
        Status.NOT_FOUND seems to fix the error - or at least posts the error message back to the caller.

**Which version of Dataverse are you using?** 6.0/6.1

**Any related open or closed issues to this bug report?** Not that I'm aware of

**Screenshots:**

No matter the issue, screenshots are always welcome.

To add a screenshot, please use one of the following formats and/or methods described here:

* https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests
*

**Comment by pdurbin** [comment]
This NO CONTENT behavior is asserted in DatasetsIT:

        //Verify the status is empty
        Response nullStatus = UtilIT.getDatasetVersionArchivalStatus(datasetId, "1.0", apiToken);
        nullStatus.then().assertThat().statusCode(NO_CONTENT.getStatusCode());

        //Set it
        Response setStatus = UtilIT.setDatasetVersionArchivalStatus(datasetId, "1.0", apiToken, "pending",
                "almost there");
        setStatus.then().assertThat().statusCode(OK.getStatusCode());

        //Get it
        Response getStatus = UtilIT.getDatasetVersionArchivalStatus(datasetId, "1.0", apiToken);
        getStatus.then().assertThat().body("data.status", equalTo("pending")).body("data.message",
                equalTo("almost there"));

        //Delete it
        Response deleteStatus = UtilIT.deleteDatasetVersionArchivalStatus(datasetId, "1.0", apiToken);
        deleteStatus.then().assertThat().statusCode(OK.getStatusCode());

        //Make sure it's gone
        Response nullStatus2 = UtilIT.getDatasetVersionArchivalStatus(datasetId, "1.0", apiToken);
        nullStatus2.then().assertThat().statusCode(NO_CONTENT.getStatusCode());

I agree that it's weird that the user never sees the message "This dataset version has not been archived".

**Comment by qqmyers** [comment]
Looks like an ~autocomplete mistake - NO_CONTENT doesn't really make sense vs a 404. Good catch!
