### ISSUE TITLE
Add support for STRLs in Stata 13

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#1016]
My implementation of Stata 13 isn't handling STRLs - new storage mechanism for larger (and non-ASCII?) strings.
Needs to be added ASAP. 
Everything else in Stata 13 should be working, to the best of my knowledge.

**Comment by landreev** [comment]
STRLs should be working now. 
I haven't tested it with anything approaching 2GB strings that can, in theory, be packed into a STRL. 
I'm actually guessing it'll barf. (I make a Java String out of the contents of the object; and in some cases cache it in memory...). Should be working on reasonable strings though. 

A simple example can be found on dvn-build, in /usr/local/dvn-admin/data/auto_strls.dta
This is just the sample auto.dta file that comes with Stata 13; with one more variable added that is a STRL.

**Comment by kcondon** [comment]
OK, tested, works, closing
