### ISSUE TITLE
API Metrics : add user accounts number

### ISSUE THREAD

**Issue by DS-INRA** [IQSS/dataverse#10177]
**Overview of the Feature Request**
Add an API Metrics type for total number of user accounts?

**What kind of user is the feature intended for?**
(Example users roles: API User, Curator, Depositor, Guest, Superuser, Sysadmin)
In order to allow display of this metric as in this issue :
- https://github.com/gdcc/dv-metrics/issues/15

**Any brand new behavior do you want to add to Dataverse?**
Add the new metric to the API, as per other metrics :
- Total - an aggregate count over all-time:
  - Form: GET `https://$SERVER/api/info/metrics/accounts`
  - Return: A simple JSON object with a `count` whose value is the accounts' total count.
  Ex. `{"status":"OK","data":{"count":13}}`
- To-Month - a count of accounts in dataverse up to and including a specified month `$YYYY-DD` in YYYY-MM format (e.g. `2018-01`):
  - Form: GET `https://$SERVER/api/info/metrics/accounts/toMonth/$YYYY-DD`
  - Return: A simple JSON object with a `count` whose value is the accounts' total count.
  Ex. `{"status":"OK","data":{"count":13}}`
- Past Days - a count of accounts in a Dataverse installation for the past `$days` (e.g. `30`):
  - Form: GET `https://$SERVER/api/info/metrics/accounts/pastDays/$days`
  - Return: A simple JSON object with a `count` whose value is the accounts' total count.
  Ex. `{"status":"OK","data":{"count":3}}`
- Monthly - a time series of the metric with aggregate values per month with counts up to and including the given month:
  - Form: GET `https://$SERVER/api/info/metrics/accounts/monthly`
  - Return: A CSV with an array of counts per month.
  Ex.
    ```
    date,count
    "2022-12",19
    "2023-01",19
    "2023-02",19
    "2023-03",19
    "2023-04",19
    "2023-05",19
    "2023-06",19
    "2023-07",19
    "2023-08",19
    "2023-09",19
    "2023-10",19
    "2023-11",19
    "2023-12",19
    ```

**Any open or closed issues related to this feature request?**
- https://github.com/gdcc/dv-metrics/issues/15
- https://github.com/IQSS/dataverse-metrics/issues/100

**Comment by pdurbin** [comment]
@DS-INRA I've wanted this for a long time. Thanks for creating this issue!

I'm not sure if you've looked at the authenticateduser table lately: https://guides.dataverse.org/en/5.14/schemaspy/tables/authenticateduser.html

We might want to consider fields such as:

- lastlogintime
- lastapiusetime
- deactivated (I forget why we don't just use the time below 🤔 )
- deactivatedtime

Basically, what I'm getting at is that if we want to get fancier, we could say things like:

- Show me all the active users (either by login or API).
- Show me all the non-deactivate users (though I suspect deactivation is rare).

Also, does your team plan to work on this?

**Comment by DS-INRA** [comment]
It would be very helpful to have active users too indeed, I'm still thinking about what parameter would be best for this use case though, my guess is pastDays because the timeframe for "active" might vary between installations. 
On our side we would also be interested in the various account types number but I didn't mention it here to keep the issue focused on the first step.
As per a contribution on our side, we have not scheduled it yet but we'll likely be proposing a PR for this in 2024 in order to unlock the other issue on dv-metrics we planned to do, I'll add a comment when confirmed :)

**Comment by pdurbin** [comment]
> It would be very helpful to have active users too indeed

@DS-INRA are you still interested in counting active users somehow? Have you considered creating an issue for this?

**Comment by DS-INRA** [comment]
> @DS-INRA are you still interested in counting active users somehow? Have you considered creating an issue for this?

It would still be interesting but we would like to discuss with our collection administrators the need, we have a meeting on the metrics topic on July 5th, so there will be more news at that time :smiley:
