### ISSUE TITLE
Stop sending websocket (atmosphere) requests through the Apache proxy

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1017]
R ingest was working but after a recent build that included date changes, r ingest now ends in a yellow error page: XML Parsing Error: syntax error Location: https://dvn-build.hmdc.harvard.edu/dataset.xhtml?id=28&versionId=2 Line Number 1, Column 1:94|{"data":{"summary":"ingest done","detail":"ingest done","severity":"INFO 0","rendered":false}}<?xml version='1.0' encoding='UTF-8' ?>

**Comment by landreev** [comment]
Just to reiterate, this is not about R specifically; this appears to be the result of sending atmosphere pings through the apache proxy. Now that the apache proxy is back, I need to reinvestigate this, see if the problem still there and invest into configuring websocket proxy. beta 14.

**Comment by landreev** [comment]
Changed the subject of the ticket.

**Comment by landreev** [comment]
While there is more or less a consensus re: running websocket requests through apache proxy being a bad idea; the alternatives are really numerous: 
1) mod_proxy_wstunnel is only one of them;
2) mod_pywebsocket is another; 
3) haproxy... and more alternatvies still
4) simply running atmosphere on a different port, and bypassing the proxy altogether is yet another possibility - something I actually want to investigate.

**Comment by landreev** [comment]
The status of this issue: 
I have a solution that seems to be working. However, it appears that I don't have configuration logistics figured out yet. My current setup relies on hard-coding something in the web.xml. And there is some additional configuration that's required when doing everything over https; which we are going to require. 

All in all, I'm not ready to close this issue for b14. There will be very little code for this - mostly configuration; except for whatever I end up putting into web.xml... So I'll have to continue looking into this for 4.0 final...

**Comment by landreev** [comment]
The QA status:
dvn-build has been configured to bypass the proxy for PrimePush calls; 
Thanks to @pdurbin for his documentation on importing CRT certificates under Glassfish; that was needed to work out the https/wss setup; 
On dvn-build, you can continue deploying the app as usual. No special steps are needed to keep the extra PrimePush configuration active. 
On dataverse-demo, once we deploy b14, a one-time configuration step will be required. (will document)

(This added "production" configuration stays in place when the app is redeployed using autodeploy. If it is undeployed, then deployed again, the configuration gets overwritten in the domain.xml; and then it needs to be put back, with one asadmin command. The setup does not rely on anything added to the web.xml)

**Comment by landreev** [comment]
This is the asadmin command: (already done, on dataverse-demo)

asadmin set-web-context-param --name='primefaces.PUSH_SERVER_URL' --value='https://${dataverse.fqdn}:8181' dataverse-4.0

(will create an extra documentation entry for this)
