### ISSUE TITLE
Documentation for trusted remote storage setup has json quotes incorrect

### ISSUE THREAD

**Issue by jmjamison** [IQSS/dataverse#10175]
<https://guides.dataverse.org/en/latest/developers/big-data-support.html?highlight=trusted%20remote#trusted-remote-storage-with-the-remote-store-type>

The single an double quotes need to be reversed.

what it has:
export JSON_DATA="{'description':'My description.','directoryLabel':'data/subdir1','categories':['Data'], 'restrict':'false', 'storageIdentifier':'s3://demo-dataverse-bucket:176e28068b0-1c3f80357c42', 'fileName':'file1.txt', 'mimeType':'text/plain', 'checksum': {'@type': 'SHA-1', '@value': '123456'}}"

what it should be:
export JSON_DATA='{"description":"My description.","directoryLabel":"data/subdir1","categories":["Data"], "restrict":"false", "storageIdentifier":"trs://images/dataverse_project_logo.svg", "fileName":"dataverse_logo.svg", "mimeType":"image/svg+xml", "checksum": {"@type": "SHA-1", "@value": "123456"}}'

**Comment by pdurbin** [comment]
@jmjamison thanks for creating this issue following [the chat](https://dataverse.zulipchat.com/#narrow/stream/378866-troubleshooting/topic/trusted.20remote.20storage.20setup/near/407306937) we had about it today!
