### ISSUE TITLE
SWORD: Display of actual dcterms xml element for equivalent of required field not found

### ISSUE THREAD

**Issue by esotiri** [IQSS/dataverse#1019]
This is related to #921 
Display of actual dcterms xml element for equivalent of required field not found. Right now you can look the mapping at foreignmetadatamapping.

It says (for example) "Can't create/update dataset. http://purl.org/dc/terms/ equivalent of required field not found: authorName" but it would be nicer if it told you `dcterms:creator` so you don't have to look it up in a table in the API Guide.

**Comment by ekraffmiller** [comment]
Assigning this to Bob, since he is working on the new dcterms import code.

**Comment by posixeleni** [comment]
Bob: In case this is helpful I have a related ticket #1077 on mapping dcterms to dataverse elements via SWORD. So here is the table I have been working on with the mapping for import: https://docs.google.com/spreadsheets/d/1r5jDqw9qMeeHaZ2ga8PSXTtom58gsmd5If3Skr9ercw/edit?usp=sharing Please let me know if this helps and if anything needs clarification.

**Comment by pdurbin** [comment]
This seemed like a good idea back Oct 2014 but no one seems to really be asking for this. Closing.
