### ISSUE TITLE
Color Scheme/Layout/UI Components - General Application UI Design

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#102]
---

Author Name: **Mike Heppler** (@mheppler)
Original Redmine Issue: 3511, https://redmine.hmdc.harvard.edu/issues/3511
Original Date: 2014-02-24
Original Assignee: Mike Heppler

---

Clean up the general look and feel of the application, by applying a consistent layout, with a unique color scheme, as well as font face, font size, link color, etc.

Related issue: font size on the create version of dataset is different than the edit version.

**Comment by eaquigley** [comment]
passing to QA to close as this has been broken down into individual tickets

**Comment by kcondon** [comment]
Closing broken down ticket
