### ISSUE TITLE
Extend getVersionFiles API endpoint to include the total file count, which is required for pagination

### ISSUE THREAD

**Issue by GPortas** [IQSS/dataverse#10202]
**Overview of the Feature Request**

To paginate the results of getVersionFiles it is necessary to know the total file count and thus know the pagination limit. Currently a separate endpoint (getVersionFileCounts) is used to know the total file count. 

The goal is to add the total file count in the getVersionFiles response so we don't have to use an additional endpoint to know the total file count and avoid an additional API call.

The Solr search API implements pagination in this way, returning {"total_count", "items"} in the response payload, so this extension will make the API experience more consistent between search endpoints.

The getVersionFileCounts endpoint is necessary to know the different file counts for each filter option, so it is necessary in any case and should remain in the API.

**What kind of user is the feature intended for?**
API User

**What inspired the request?**
- https://github.com/IQSS/dataverse-client-javascript/pull/107#discussion_r1434858529

**What existing behavior do you want changed?**
- None

**Any brand new behavior do you want to add to Dataverse?**
- New field with total file count in getVersionFiles API endpoint response

**Any open or closed issues related to this feature request?**
- https://github.com/IQSS/dataverse-client-javascript/issues/109
- https://github.com/IQSS/dataverse-client-javascript/pull/107

**Comment by stevenwinship** [comment]
Since getting the total count takes time should we only get it when the offset is 0 (first call) or is it ok/desirable to get the total with each call?
