### ISSUE TITLE
Add DataCite badge to dataverse.org

### ISSUE THREAD

**Issue by jp-tosca** [IQSS/dataverse#10213]
**Overview of the Feature Request**

This is a continuation of [#210 ](https://github.com/IQSS/dataverse.harvard.edu/issues/210)the badge is ready for Harvard Dataverse but @siacus mentioned the badge should be on both sites(dataverse.org).

**Comment by cmbz** [comment]
2024/01/29
- Prioritized by @cmbz (as 6.2) and moved to Needs Sizing.

**Comment by jp-tosca** [comment]
The content was added to https://dataverse.org reviewed with Dwayne Liburd
