### ISSUE TITLE
Documentation Update: Update to information for "Set Citation Date Field Type for a Dataset"

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#10227]
We should add more information to [the section in the API guides](https://guides.dataverse.org/en/latest/api/native-api.html?highlight=unlock#set-citation-date-field-type-for-a-dataset) about the API endpoint that changes the year in Dataverse's suggested citations:

- **The file citation may change, too.** The API endpoint changes the year in the suggested file citation as well as the suggested dataset citation
- **The citation year used in each dataset and file version depends on the metadata of each version**. The API endpoint changes the year in the suggested citation of each version of the dataset and files as long as the dataset version has a year entered in the date metadata field being used. And for dataset versions that have nothing entered in the date metadata field being used, such as the Production Date, the Publication Date will continue to be used for that version's suggested dataset and file citations.

  For example, if the Production Date is used in the API call for a dataset that has three versions, V1 has nothing entered in its Production Date, V1.1's Production Date date has 2021, and V2's Production Date has 2022, then the suggested dataset and file citations for V1 will use the year of the system-generated Publication Date, the suggested dataset and file citations for V1.1 will use the year that the user entered for that version's Production Date (2021), and the suggested dataset and file citations for V2 will use the year that the user entered for that version's Production Date (2022).

**Comment by sbarbosadataverse** [comment]
@jggautier can't easily find Katie's contact so pinging you here if you have any additional information of want to edit what I wrote. Thanks

**Comment by kmika11** [comment]
Thanks @jggautier. Another way to think about the versioning is that the endpoint is _version agnostic_. Changing the default date metadata field for the citation date executes across all versions. Any version without an entry in the new date metadata field will revert to the default citation date field (publicationDate). 

You can see this tested on the Demo Dataverse here: [https://demo.dataverse.org/dataset.xhtml?persistentId=doi:10.70122/FK2/X5GFFN](https://demo.dataverse.org/dataset.xhtml?persistentId=doi:10.70122/FK2/X5GFFN)

**Comment by pdurbin** [comment]
@kmika11 @jggautier would either of you like to take a whack at editing that page in the guides? You should be able to use your browser, the quick fix explained at https://guides.dataverse.org/en/6.1/developers/documentation.html#quick-fix

**Comment by kmika11** [comment]
Thanks @pdurbin! I think I did it correctly; here's the pr: [https://github.com/IQSS/dataverse/pull/10237](https://github.com/IQSS/dataverse/pull/10237).

**Comment by pdurbin** [comment]
@kmika11 looks great! Thanks!
