### ISSUE TITLE
Linked Collections are not available in the Featured Dataverses List

### ISSUE THREAD

**Issue by sekmiller** [IQSS/dataverse#10229]
**What steps does it take to reproduce the issue?**
In a Dataverse collection link one or more collections.
Click the Edit then Featured Dataverses
I expect to see my linked collections as available to be featured but some are not.

* When does this issue occur?
See above

* Which page(s) does it occurs on?
 Dataverse Landing page - edit - Featured Dataverses

* What happens?
 Linked Dataverses are not available to be featured

* To whom does it occur (all users, curators, superusers)?
 Anyone with Edit Dataverse permissions

* What did you expect to happen?
 Linked Dataverse Collections should be available to be selected as Featured

**Which version of Dataverse are you using?**
6.1, Dev

**Any related open or closed issues to this bug report?**
None 

**Screenshots:**

No matter the issue, screenshots are always welcome.

To add a screenshot, please use one of the following formats and/or methods described here:

* https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests
*
<img width="599" alt="Screen Shot 2024-01-11 at 5 02 31 PM" src="https://github.com/IQSS/dataverse/assets/2364928/5d02a8e7-5a65-4c25-a5eb-0248bc71b96e">

**Comment by cmbz** [comment]
**2024/01/22**
- Preliminarily sized at a 3 (fix will be very small, QA will be the 3) and added to Sprint Ready

**Comment by jp-tosca** [comment]
Tests passed and the linked collections feature will work now 👍🏼
