### ISSUE TITLE
Spike: Investigate creating OpenAPI YAML from our code

### ISSUE THREAD

**Issue by cmbz** [IQSS/dataverse#10236]
## Overview

The `openapi` endpoint provided by Payara results in an internal server error in version 6.0, as detailed here: https://github.com/IQSS/dataverse/issues/9981

Payara has been contacted for a fix (see: https://github.com/IQSS/dataverse/issues/9981#issuecomment-1885056159).

This spike proposes that while we await the Payara fix, we investigate using the [OpenAPI Generator Tool](https://github.com/OpenAPITools/openapi-generator) to determine feasibility, as recommended here: https://github.com/IQSS/dataverse/issues/9981#issuecomment-1885056159

## Related
- https://github.com/IQSS/dataverse/issues/9981

**Comment by cmbz** [comment]
2024/01/17: Moved to sprint ready so work can start.

**Comment by pdurbin** [comment]
As I mentioned in standup, I'm going to change the title of this issue to make it more generic.

After poking at https://github.com/OpenAPITools/openapi-generator a bit and playing with the example at https://openapi-generator.tech/docs/plugins/ I'm not so sure that this is the right tool for generating the OpenAPI YAML we want. Instead, it seems like it produced client code from OpenAPI YAML.

I checked with @poikilotherm who [suggested](https://dataverse.zulipchat.com/#narrow/stream/379673-dev/topic/.2Fopenapi.20broken.20in.206.2E0/near/416457528) some additional libraries to try:

"I might have gotten that one wrong - the OpenAPI generator is about generating Java code from the spec, not the other way round

But: I did some digging, looking specifically for generating the OpenAPI YAML file... And here's what I found:

A) Use Swagger and Swagger Annotations. https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-maven-plugin/README.md and https://github.com/openapi-tools/swagger-maven-plugin (not sure what the difference is). There is also https://github.com/stoicflame/enunciate which supports Swagger output as well as generating client code in a variety of languages.

B) Use [MicroProfile OpenAPI annotations](https://download.eclipse.org/microprofile/microprofile-open-api-3.1.1/microprofile-openapi-spec-3.1.1.html) (these are the ones also useable with Payara /openapi endpoint) and use other plugins: https://geronimo.apache.org/microprofile/openapi.html or https://github.com/smallrye/smallrye-open-api/tree/main/tools/maven-plugin

I think the best shot is the SmallRye Maven Plugin, as it provides code scanning and keeps us compatible with the Payara OpenAPI implementation"

So next we should try some of the above.

**Comment by jp-tosca** [comment]
Testing [this plugin](https://github.com/smallrye/smallrye-open-api/tree/main/tools/maven-plugin) I was able to generate the following spec:

[openapi.json](https://github.com/IQSS/dataverse/files/14288504/openapi.json)

**Comment by pdurbin** [comment]
Here's, I grabbed the YAML from [the post](https://dataverse.zulipchat.com/#narrow/stream/379673-dev/topic/.2Fopenapi.20broken.20in.206.2E0/near/421530784) JP made and added .txt so GitHub will take it: [openapi.yaml.txt](https://github.com/IQSS/dataverse/files/14288543/openapi.yaml.txt)

This is great! I guess if we go with this approach we should figure out where to put these files. It reminds me of how we put SchemaSpy output here, for example: https://guides.dataverse.org/en/5.14/schemaspy . That said, SchemaSpy has been treated as a one-off, something @donsizemore kindly does manually. Maybe this output should go directly into `doc/sphinx-guides/source` somewhere and get committed as part of a PR? It could even be useful for code review to see how the API has been extended or changed. And of course, we'd like to the output from the guides so API users can easily find it.

**Comment by pdurbin** [comment]
On a related note, I just built a version of Payara (for the first time) using the PR that fixes /openapi and left some notes about how I built it and where I put it: https://github.com/IQSS/dataverse/issues/9981#issuecomment-1962056328
