### ISSUE TITLE
Dataset Template: Text/Instructions for Pages related to Dataset Template

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1024]
Text to either add or change for Edit Dataverse->Dataset Template feature.

Dataset Template landing page (page a user lands on after clicking Dataset Template from the Edit Dataverse dropdown)
- [x] Currently in the table it says "No records found". Please change to say, No existing templates
- [x] There need to be instructions above the table where dataset templates are listed. Instructions: Create, clone, edit, view, or delete dataset templates. Create a dataset template to prefill metadata fields with standard values, such as author affiliation, to help users create datasets in this dataverse. You can also add watermarks or help text to the metadata fields to guide users on what to add to in these metadata fields. (This should only appear if there are pre-existing dataset templates. Otherwise #1490 should be displaying)

Create/Edit Dataset Template Page:
- [x] Place this text above the dataset template form: Asterisks indicate metadata fields that users will be required to fill out while adding a dataset to this dataverse.

**Comment by sekmiller** [comment]
Mike, I put in the above text in the bundle can you style it on manage-templates.xhtml.  It only appears after you've added at least one template.....

**Comment by mheppler** [comment]
I recommend that the supplied text should be displayed in an info block, at the top of the page, as it is designed for, and not a new block of text above the table.

Attached is a mock up for everyone to review. Enjoy. @eaquigley @sekmiller @mcrosas 

![screen shot 2015-02-24 at 3 59 15 pm](https://cloud.githubusercontent.com/assets/687227/6359077/5b61c024-bc3e-11e4-9927-8dbfded23b10.png)

**Comment by mcrosas** [comment]
Fine with me


Mercè Crosas, Ph.D.
Director of Data Science, IQSS
Harvard University
http://datascience.iq.harvard.edu

**Comment by eaquigley** [comment]
+1

**Comment by sekmiller** [comment]
I can take care of this….


On Feb 24, 2015, at 4:05 PM, Merce Crosas <notifications@github.com<mailto:notifications@github.com>> wrote:

Fine with me


Mercè Crosas, Ph.D.
Director of Data Science, IQSS
Harvard University
http://datascience.iq.harvard.edu

**Comment by mheppler** [comment]
Assigning to @sekmiller to wire up info block text.

**Comment by sekmiller** [comment]
Fix Checked in ...

**Comment by kcondon** [comment]
@eaquigley I don't see the explanatory text when there are no templates, is that by design?
Also, do not see the inherit templates checkbox, will report as a bug.

**Comment by eaquigley** [comment]
@kcondon : @mheppler has added in the text for when there are no templates or guestbooks. this is documented in ticket #1490

**Comment by eaquigley** [comment]
All messaging is appearing. Closing ticket.
