### ISSUE TITLE
Feature Request/Idea: Set featured collections through Native API

### ISSUE THREAD

**Issue by Asbjoedt** [IQSS/dataverse#10242]
**Overview of the Feature Request**
Hello

We want to automate our installation through Ansible and create Dataverses using Native API, which works fine.
However, we cannot set featured collections using the Native API and hence cannot automate this configuration.

**What kind of user is the feature intended for?**

Sysadmin

**What inspired the request?**
Automation.

**What existing behavior do you want changed?**
Native API.

**Any brand new behavior do you want to add to Dataverse?**
Expand functionality of Native API to allow setting featured collections.

**Any open or closed issues related to this feature request?**
Couldn't find any.

**Comment by pdurbin** [comment]
@Asbjoedt good idea. For anyone who's unfamiliar with this GUI-only feature, it's described here: https://guides.dataverse.org/en/6.1/user/dataverse-management.html#featured-dataverse-collection

**Comment by DS-INRA** [comment]
Hi asbjoet, tanks for the issue !
We also have an environment deployed with Ansible, maybe it would be a good topic for a comunity call someday :)

**Comment by Asbjoedt** [comment]
Sure, we would be interested in that.

**Comment by DS-INRA** [comment]
Is this something your organisation is planning on adding to Dataverse by the way ?

**Comment by Asbjoedt** [comment]
Not at the moment. We need to finish going from test to production.

I am trying to raise awareness in our organisation about the value of contributing back to the community.

**Comment by pdurbin** [comment]
We'd definitely be interested in a pull request. We'll need this functionality for the new frontend some day, which operates over APIs: https://github.com/IQSS/dataverse-frontend
