### ISSUE TITLE
docs: correct typo in search API documentation

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#10249]
https://github.com/IQSS/dataverse/blob/develop/doc/sphinx-guides/source/api/search.rst?plain=1#L28 provides "Dataverse" as an available type, but 6.0 returns:

`{"status":"ERROR","message":"Invalid type 'Dataverse'. Must be one of [dataverse, dataset, file]"}`

A Don-special 1-byte PR to follow.

**Comment by jggautier** [comment]
@donsizemore, do you think this is related to the issue at https://github.com/IQSS/dataverse/issues/8971, too?

**Comment by donsizemore** [comment]
@jggautier heh. yup. I just didn't turn that up in a search, sorry.

**Comment by jggautier** [comment]
Oh no worries! I'm happy you're working on it! And glad to see another issue closed lol
