### ISSUE TITLE
Error when creating new dataverse/dataset after upgrade on 6.1

### ISSUE THREAD

**Issue by lmaylein** [IQSS/dataverse#10253]
We have upgraded from dataverse 5.14 to 6.1 (via 6.0).

Now we get error messages when creating new dataverses

`Error – jakarta.ejb.EJBException: jakarta.ejb.CreateException: Could not create stateless EJB If you believe this is an error, please contact [heiDATA Team](https://heidata.uni-heidelberg.de/dataverse.xhtml?ownerId=1#) for assistance.`

or datasets

`Error – The dataset could not be created. If you believe this is an error, please contact [heiDATA Team](https://heidata.uni-heidelberg.de/dataset.xhtml?persistentId=doi%3A10.11588%2Fdata%2FFSVRIN&version=DRAFT#) for assistance.`

server.log:

[server.log](https://github.com/IQSS/dataverse/files/14023835/server.log)

This message is interesting:
"Caused by: javax.naming.NameNotFoundException: notifyMailSession not found"

During upgrade from 5.14 to 6.0 I've submitted the following command (according the release notes):

`/usr/local/payara6/bin/asadmin create-javamail-resource --mailhost "relays.uni-heidelberg.de" --mailuser "dataversenotify" --fromaddress "heidata@listserv.uni-heidelberg.de" mail/notifyMailSesssion`

What could have gone wrong here?

**Comment by lmaylein** [comment]
Oh no. I found the typo. notifyMailSession instead of notifyMailSession. Sorry.

**Comment by pdurbin** [comment]
Phew! 😅
