### ISSUE TITLE
Create/Edit Dataset Page: Text to add in or remove

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1025]
On the create/edit dataset page there needs to be text above the form that states what the asterisks represent. Text:

- [x] Asterisks indicate required metadata fields.

- [x] Additionally, on the create page take out the text that says, "No records found."
- [x] On Dataset page within the files tab, where it says "No records found." change to say, "No files found."

**Comment by kcondon** [comment]
Looks good, messages are approximately correct. Closing.
