### ISSUE TITLE
css problem with dataverse logos in 6.1

### ISSUE THREAD

**Issue by lmaylein** [IQSS/dataverse#10265]
There seems to be a CSS problem with the display of dataset logos in 6.1. These are not scaled correctly.

Example:

https://heidata.uni-heidelberg.de/dataverse/arthistoricum

![dataverse_icons](https://github.com/IQSS/dataverse/assets/7468155/4be26cf4-527a-4bfb-98c4-0f7495035555)

Clearing the browser cache (to load a new CSS version if necessary) does not help.

**Comment by donsizemore** [comment]
related to #10220

**Comment by lmaylein** [comment]
> related to #10220

Thanks.
