### ISSUE TITLE
Dataverse General Information Page: Text to add in or change

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1026]
Metadata Elements section:
- [x] change text by the i icon to say: Choose metadata fields to use in dataset templates and when adding a dataset to this dataverse. 
- [x] update fields link, change to say: Select metadata fields as hidden, required, or optional.
- [x] Hide fields link, change to say: Close
- [x] System requirement, change to say: Required by Dataverse

Select Facets section:
- [x] change text by the i icon to say: Pick the metadata fields to use as facets for browsing datasets and dataverses in this dataverse.

**Comment by eaquigley** [comment]
Passing this ticket to QA to be closed. Most of the items in the list above have been done either by myself or have been done in other tickets.

**Comment by kcondon** [comment]
Closing
