### ISSUE TITLE
Dataverse Instalation error: JNDI lookup failed for the resource: Name: [VDCNet-ejbPU]

### ISSUE THREAD

**Issue by nmunatsibw** [IQSS/dataverse#10277]
**What steps does it take to reproduce the issue?**
I am currently running Rocky Linux 9 and payara 6 an am trying to set up anew installation of the dataverse software. I have successfully set up all the prerequisites for installation following the this [guide](https://guides.dataverse.org/en/4.9.4/installation/prerequisites.html).

* When does this issue occur?
 When i move on to the installation stem and i run the installer using the python command `python3 install.py` I then get the above mentionned error.  After confirming thet the pre requisits were installed properly i then run this command
 `sudo -u dataverse /usr/local/payara6/bin/asadmin deploy dataverse.war` to try to deploy dataverse

* To whom does it occur (all users, curators, superusers)?
@pdurbin

**Which version of Dataverse are you using?**
v6.1

**Any related open or closed issues to this bug report?**
I am not sure if this helps, but qhen i was reseaching the erro above i came across this bug, [#10036](https://github.com/IQSS/dataverse/issues/10036), but this bug is for an upgrade.

**Screenshots:**
No matter the issue, screenshots are always welcome.
* ![Screenshot 2024-01-29 at 11 24 03](https://github.com/IQSS/dataverse/assets/129177120/7ddaf167-7583-4ae2-9f89-831834e8ff38)

> `[nmunatsi@dataverse2 dvinstall]$ sudo -u dataverse /usr/local/payara6/bin/asadmin deploy dataverse.war 
remote failure: Error occurred during deployment: JNDI lookup failed for the resource: Name: [VDCNet-ejbPU], Lookup: [java:app/jdbc/dataverse], Type: [javax.sql.DataSource] -- Lookup failed for 'java:app/jdbc/dataverse' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factory.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl, java.naming.factory.url.pkgs=com.sun.enterprise.naming}. Please see server.log for more details.
Command deploy failed.`

**Comment by donsizemore** [comment]
I can consistently reproduce this on Debian 12 with Postgres 15.

**Comment by DaftPug** [comment]
We run in to the same problem, when trying to do a fresh reinstall, with Postgres 15 as well. Using the war file https://github.com/IQSS/dataverse/releases/download/v6.1/dataverse-6.1.war, instead of the one in dvinstall.zip works however.

**Comment by donsizemore** [comment]
@DaftPug you're right, they're not the same! thank you for noticing this.

**Comment by donsizemore** [comment]
@DaftPug according to my tests this morning, the opposite is true: a warfile built from the develop branch deploys successfully; the warfile from dvinstall.zip fails (and is smaller, and also timestamped March 2022)

**Comment by donsizemore** [comment]
@DaftPug @nmunatsibw earlier this afternoon, @landreev published an updated dvinstall.zip at https://github.com/IQSS/dataverse/releases/v6.1 — please try it now?

**Comment by Asbjoedt** [comment]
dvinstall works now. thanks for the fast reaction on this one @donsizemore

**Comment by nmunatsibw** [comment]
Thank you everyone for your help. I will go on and close this issue then.

**Comment by donsizemore** [comment]
Thanks to @landreev for the fix, and to @DaftPug for catching it (sorry, I mis-read your sentence above).
