### ISSUE TITLE
API tests failing on Rocky 9

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#10271]
A little bird told me API tests are failing on Rocky 9. We diagnose and fix them. I'll give this issue a 10 for now to investigate and fix what we can.

Meanwhile @donsizemore already has a Rocky 9 branch going as part of this issue:

- https://github.com/GlobalDataverseCommunityConsortium/dataverse-ansible/issues/243

Just this morning I [suggested](https://dataverse.zulipchat.com/#narrow/stream/378866-troubleshooting/topic/Install.20Dataverse/near/418104827) it to someone who was having trouble installing Dataverse.

There's also an existing issue about updating our guides for RHEL/Rocky 9:

- https://github.com/IQSS/dataverse/issues/8856

This new issue I'm creating now is focused on the API tests.

**Comment by donsizemore** [comment]
current failing test in develop on Rocky 9 (though failures are inconsistent):
`[ERROR]   ExternalToolsIT.testDatasetLevelTool1:211 1 expectation failed.", "JSON path data[0].displayName doesn't match.", "Expected: DatasetTool1", "  Actual: Whole Tale"`

**Comment by sekmiller** [comment]
I put in a fix for one of these tests on a branch revising the ExternalToolsIT. I can take care of this one and any others

**Comment by donsizemore** [comment]
@pdurbin reopening becuz https://github.com/IQSS/dataverse/issues/10312 ?

**Comment by pdurbin** [comment]
@donsizemore I was wondering about that other issue! Or we could rename this one to be about external tool tests? We probably don't need two open issues? Maybe just the remaining one about the banner? 🤔
