### ISSUE TITLE
Set patch branch to be 6.1.1 and release as an official version

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#10289]
This ticket is for tracking the changes to the branch from which the pathc is built to set is as 6.1.1 and then make the release on github (merge to master, etc). 

One additional step that will need to be done is to then merge from master to develop.

**Comment by scolapasta** [comment]
So, now that we'rew releasing 6.2 this seems less necessary. Closing.

**Comment by pdurbin** [comment]
I let the community know we are not releasing 6.1.1: https://groups.google.com/g/dataverse-community/c/nz2UddWgpeY/m/l3AJIxcVBAAJ
