### ISSUE TITLE
Feature Request/Idea: Add "Term URI" metadata in Keyword block

### ISSUE THREAD

**Issue by stevenferey** [IQSS/dataverse#10288]
**Overview of the Feature Request**
The proposal of the issue is to integrate a new metadata "Term URI" to the keyword block to facilitate the integration of controlled vocabulary services. 

Example with entrepot.recherche.data.gouv.fr:

![capture_keyword_block](https://github.com/IQSS/dataverse/assets/13960773/3215adb1-c191-431e-a042-1b74286aa4ee)

**What kind of user is the feature intended for?**
All depositors

**What inspired the request?**
This is related to issue #9276 and the [Google group discussion](https://groups.google.com/g/dataverse-community/c/4eTd3kfJeBU/m/gcgjM1ZXAAAJ)

**What existing behavior do you want changed?**
Adding a “Term URI” metadata to the “keyword” block

**Any open or closed issues related to this feature request?**
- Issue #9276
- PR #10145 
- [Google group discussion](https://groups.google.com/g/dataverse-community/c/4eTd3kfJeBU/m/gcgjM1ZXAAAJ)

**Comment by jonquet** [comment]
In practice, this 4 field-form should be changed by only one with autocompletion. 
This will make description of dataset record with standard vocabulary/ontology term (I would not use the word "keyword" in this case) much more efficient and easy. 

If term is from INRAE Thesaurus, then a lookup like the one illsutrated here should be enough: 
https://agroportal.lirmm.fr/ontologies/INRAETHES/?p=widgets
<img width="1053" alt="Capture d’écran 2024-03-28 à 12 18 18" src="https://github.com/IQSS/dataverse/assets/7379183/18d7a0f7-cb9b-4d55-939e-e71e6bc45f36">
