### ISSUE TITLE
Dataverse collection thumbnail in addition to Logo Image as banner

### ISSUE THREAD

**Issue by DS-INRA** [IQSS/dataverse#10291]
**Overview of the Feature Request**
Allow dataverse collection admins to add a distinct thumbnail image in conjunction to a Logo Image in rectangle format to display as a banner for their collection

**What kind of user is the feature intended for?**
(Example users roles: API User, Curator, Depositor, Guest, Superuser, Sysadmin)
Dataverse collection admins

**What inspired the request?**
Rectangle logos may result in very ugly featured collection thumbnails.

**Any brand new behavior do you want to add to Dataverse?**
Have two distinct images for the featured collection thumbnail :
![image](https://github.com/IQSS/dataverse/assets/46443753/f451b657-951a-4f46-9861-2e3703cc3969)

And the logo, that can be used as a banner :
![image](https://github.com/IQSS/dataverse/assets/46443753/de7c0910-24ad-45d0-9c62-cdc027882532)

Suggested implementation in the Theme and Widget page :
![image](https://github.com/IQSS/dataverse/assets/46443753/ab1b3373-4f73-4043-ad17-899b55048d44)

**Any open or closed issues related to this feature request?**
SPA version :
- https://github.com/IQSS/dataverse-frontend/issues/298
On the logo deposit part : 
- #3680

**Comment by sergejzr** [comment]
Good day!
We addressed this issue through the HTML code in description: https://bonndata.uni-bonn.de/dataverse/:root?q=

A more flexible and appealing landing page is of course desired nevertheless. I would also like at this point to mention my feature request that would allow for more general sub-collection branding: https://github.com/IQSS/dataverse/issues/10252

**Comment by pdurbin** [comment]
Good idea but I must admit that my first thought is that we should implement this in the [new React frontend](https://github.com/IQSS/dataverse-frontend) rather that JSF, which will someday go in the garbage. 🗑️
