### ISSUE TITLE
 Add Harvesting Source to search facets

### ISSUE THREAD

**Issue by DS-INRA** [IQSS/dataverse#10298]
**Overview of the Feature Request**
Following the addition of a source name for harvesting clients :
- #10217
This information should be useable as a search facet to filter results.

**What kind of user is the feature intended for?**
(Example users roles: API User, Curator, Depositor, Guest, Superuser, Sysadmin)
API User, Guests

**What inspired the request?**
 Needed for our harvested repositories.

**What existing behavior do you want changed?**
Modify the current search facet "Metadata Source" to include the list of Sources from harvesting clients.

**Any open or closed issues related to this feature request?**
- #10195 (macro issue for centralization)
- #10217

**Comment by pdurbin** [comment]
I remember suggesting this back when we added that facet.

@DS-INRA are you thinking this would be a system-wide setting? And we'd keep the default as-is but installations could opt-in to it? Some installations might like the current behavior.

**Comment by gwendoux** [comment]
It could be interesting to include a feature that displays the data sources in search facets.

@DS-INRA, what kind of source information are you considering for the harvesting client to display? Would it be the server URL, nickname, or Dataverse?

**Comment by jp-tosca** [comment]
Hi @DS-INRA  👋🏼, Quick question: What would you expect to see on the Metadata Source? As of now I have this where you see the name that was given to the **Harvesting Client**

As an example here are my Clients: 

![image](https://github.com/IQSS/dataverse/assets/142103991/6a7940f8-d406-4364-923d-3848a50b3f03)

 And here is how it looks:

![image](https://github.com/IQSS/dataverse/assets/142103991/668a0e6c-7aca-4ba9-82fb-b8a89e443c23)


A couple of things come to my mind:

- The Harvesting Client name can't have spaces so it may not look great for clients with more than 1 word.
- If we use the name of the original Dataverse we can encounter issues where the same name is used on different sources and would be grouped by the same name.
- Would it still make sense to include the root between all the other sources?

**Comment by DS-INRA** [comment]
Hi @landreev , unfortunately there are two additional limits to this approach even if it would have been great to avoid adding a new field :)
- when a Harvested repository matches 1:1 a target collection, the repository name does not necessarily matches the collection name
- a Dataverse Collection is usually in our case the target of  more than one harvesting clients/sets, coming from different repositories

**Comment by landreev** [comment]
@DS-INRA Sure. So, just to confirm, our plan then is to merge the linked PR #10464 as is, with the client nickname used for the facet (for now). Then, when the descriptive label is added, we'll switch to using that - ?

**Comment by DS-INRA** [comment]
I'm okay with this approach, as discussed with @jp-tosca  (thanks for the short summary :) )
