### ISSUE TITLE
Some tiff files don't generate thumbnails

### ISSUE THREAD

**Issue by juancorr** [IQSS/dataverse#10317]
**What steps does it take to reproduce the issue?**
Upload a tiff file in a dataset using the normal procedure . You can download examples from here: https://demo.dataverse.org/dataset.xhtml?persistentId=doi:10.70122/FK2/LNCJWK

* When does this issue occur?
This happens with some tiff files and not with others. 

* What happens?
Thumbnails are not generated sometimes uploading tiff files. The XXXXXXXXX-XXXXXXXX.thumbYY files are generated but with size 0. The alternative text is shown from the parent dataverse and not image is shown in the file preview. This problem is not dependent on the file size or the image file size limits in the database.

* To whom does it occur (all users, curators, superusers)?
All users.

**Which version of Dataverse are you using?**
v. 6.1 build iqss-prod-patch  (demo Dataverse) and v.5.10.1

**Any related open or closed issues to this bug report?**
None related

**Screenshots:**
Tiff files can't be uploaded, but here are two screenshots

![imagen](https://github.com/IQSS/dataverse/assets/325896/4256ec6c-b1d9-41ed-91b9-4999d8928981)

![imagen](https://github.com/IQSS/dataverse/assets/325896/4f915584-ef8a-4d63-9188-ec662bab3ffe)

**Comment by juancorr** [comment]
If had a problem generating tiff thumbnails with the native java library, a possible solution could be use the external Imagemagick convert tool as pdf thumbnails are generated. We had generated the tiff thumbnails in the filesystem running the convert tool from the command line here: https://edatos.consorciomadrono.es/dataset.xhtml?persistentId=doi:10.21950/KTALA8

**Comment by pdurbin** [comment]
@juancorr thanks! I'm uploading the test files here as a zip because we clear out the demo server from time to time: 
[Archive.zip](https://github.com/IQSS/dataverse/files/14241257/Archive.zip)

**Comment by pdurbin** [comment]
@juancorr you should expect some different behavior as of this PR (a default image):

- #10509

**Comment by pdurbin** [comment]
@juancorr sure, you're welcome to close this issue if you like. Generally speaking, please keep any eye on tiff support and feel free to open new issues in the future!

There's also this issue to watch:

- #10351

**Comment by juancorr** [comment]
Closing this issue because the solution it being developed with #10509 and #10351.

**Comment by juancorr** [comment]
Closing this issue because the solution it being developed with https://github.com/IQSS/dataverse/pull/10509 and https://github.com/IQSS/dataverse/issues/10351.
