### ISSUE TITLE
When granting file permissions (for a group), only one file permission is granted

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#10324]
**What steps does it take to reproduce the issue?**

Start with a datset with >1 restricted files (it can be a draft)
Then go to file permissions and grantt access to multiple files to a user. 
UI does not refect success, then reloading page shows only access to 1 file (and not all).

**Which version of Dataverse are you using?**

Confirmed in 6.1 (well ~6.1.1)

**Comment by cmbz** [comment]
2024/02/15
Added to sprint at request of @scolapasta. Tentatively sized at 3; please update size as needed.
