### ISSUE TITLE
Add latestVersionPublishingStatus field to dataset version payload

### ISSUE THREAD

**Issue by GPortas** [IQSS/dataverse#10330]
**Overview of the Feature Request**

This parameter is very necessary in many use cases. By including it in the payload of a specific Dataset version we avoid to make an extra call to the API.

**What kind of user is the feature intended for?**
API User

**What inspired the request?**
Frontend devs discussion

**What existing behavior do you want changed?**
None

**Any brand new behavior do you want to add to Dataverse?**
Add latestVersionPublishingStatus field to dataset version payload

**Any open or closed issues related to this feature request?**
- https://github.com/IQSS/dataverse/issues/10280

**Comment by jp-tosca** [comment]
@GPortas 👋 

What should a user see? the Published Status of the latest version o the published status of the version that they have access? I can get on a call with you so we can talk about this.

For example an unauthenticated user that calls this endpoint would get always RELEASED or DEACCESSIONED when calling for a specific version. If it is an authenticated user if they have access to the draft then they would get DRAFT if it exist . 

How do we want to handle deaccessioned for this? Do we want this to always include deaccessioned or respect the parameter of the request? or probably never look ad deaccessioned versions?

**Comment by GPortas** [comment]
@jp-tosca 👋

The user should see the status of the latest version, regardless of user permissions.

We should consider deaccessioned version always. If the status of the latest version is deaccessioned, we should specify it.

Thanks!
