### ISSUE TITLE
Update password encryption to use BCrypt

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#1034]
For password encryption, use something like BCrypt (SHA-256 or SHA-512). Need to change from current implentation of just SHA.
Can we use this (check license): http://www.mindrot.org/projects/jBCrypt/
Maven code: https://code.google.com/p/jbcrypt/wiki/GotMaven

**Comment by rtreacy** [comment]
Switching to jBCrypt should be pretty straightforward. The only caveat is that there is a newly released version 0.4 that is not yet in maven repository

**Comment by eaquigley** [comment]
Mockups for when there is only one account associated with an email address: https://iqssharvard.mybalsamiq.com/projects/36to40builtinaccounts/Dataverse%20Account%20II%20-%20Account%20Found

**Comment by michbarsinai** [comment]
What's left to do: Complete the change to `passwordreset.xhtml` to support both password reset and password upgrade.

**Comment by scolapasta** [comment]
@sekmiller if you could put the logic for the renders in this issue, @mheppler can add (since he'd have to go in and do cleanup after, anyway)

**Comment by sekmiller** [comment]
Added TOU section per mock-ups.  Mike, please take a look at styling and add link out to view agreement.

**Comment by mheppler** [comment]
Cleaned up passwordreset for 3.6 to 4.0 user workflow.

**Comment by kcondon** [comment]
Password encryption is in place. Onboarding/ migration process defined/ designed. There is a separate ticket opened for not showing the above migration form but is most likely due to a testing error and will need to be retested. Closing this ticket as basic functionality has been delivered.
