### ISSUE TITLE
Dataset Upload/Edit Files - Add "Advanced Options" popup

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#1035]
As specific/short-term goals: we have a couple of cases where, for specific file types, the Add Files page should [optionally] allow the user to enter extra ingest parameters, before they hit "save":

1) if the file type is recognized as "application/x-spss-por" (aka "SPSS-portable"), there should be an option for uploading the second text file, to accompany the ingest. (This is something custom made for Odum; but could be useful for other people). 

2) if the file type is recognized as "application/x-spss-sav", we want to also show a menu for [optionally] selecting a specific language encoding. [will add more details on this]

The question is how to implement this. The simplest thing to do would be just to add the 2 things above to the individual file rows, rendered depending on the file type... 
But it is looking like we may need more and more such extra options as we go along. (Merce recently brought up this extra interface for assigning extra "tags" to tabular data). 
So I'm wondering if, instead of simply piling extra things up in the file rows,  we should instead render a single "advanced options" button; that would in turn open a pop-up window with whatever extra 
options that may be available for this file type...

What do you think? At this point we should probably choose whatever is easiest to implement for 4.0, not necessarily prettiest or cleanest.

**Comment by landreev** [comment]
OK, so this is a top-level ticket with 4 individual sub-tasks: 
#960 - tabular data tags (done, closed)
#1145 - default thumbnail image (done, closed)
#831 - Odum-style "extended labels" SPSS/por ingest; (in QA) - in QA
#1343 "select language encoding" for SPSS/sav ("Fudan-style") - (done, closed)

**Comment by kcondon** [comment]
All child tickets are closed. There was one functional requirement not implemented due to dependency on another feature: zip upload creating file categories from sub dirs. I will open a new ticket for that.

Also, discussed with Mike, will open a review UI ticket for fit and finish if necessary.
