### ISSUE TITLE
Feature Request/Idea: Enforce agreement to updated terms of use

### ISSUE THREAD

**Issue by sergejzr** [IQSS/dataverse#10353]
**Overview of the Feature Request**
Dear Dataverse Developers,
when a user is registering to RSpace, the user needs to agree with the terms of use. Unavoidably, these terms are subject to change and get updated from time to time. As administrator, I would like to let the users agree to new terms in this case. Best would be an explicit flag that lets every user check and agree to new terms upon next login.

**Comment by pdurbin** [comment]
@sergejzr yes, good idea. Does the issue below cover your use case?

- #4978

**Comment by sergejzr** [comment]
Yes, thanks!

**Comment by pdurbin** [comment]
@sergejzr great, I hope you don't mind, but I'm going to close this as a duplicate. Please feel free to give the older issue a 👍 and a comment.
