### ISSUE TITLE
Ingest: Stata 13 test file fails to ingest with error: called to read 0 or negative bytes.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1038]
I created a small Stata 13 test file of 3 variables with numbers 1-10.
It fails to ingest and the red triangle reports it failed because it was called to read 0 or negative bytes.

The file was sent directly to Leonid and is called 3by10_stata13.dta

**Comment by landreev** [comment]
I didn't realize how old this ticket was - thought it was something newly discovered. 
Probably a duplicate. Kevin, please re-test and close.

**Comment by kcondon** [comment]
This works now! Closing.
