### ISSUE TITLE
Index after publish

### ISSUE THREAD

**Issue by ErykKul** [IQSS/dataverse#10381]
**What steps does it take to reproduce the issue?**
As @scolapasta described, If you go to Harvard Dataverse right now and look at the datasets on the front page, most of them do not show the filters (on the currently released versions). This is because (at least from past investigation), the index time is getting set to an earlier time than the publish time. (which is why running a manual reindex fixes it for a particular dataset).

* When does this issue occur?*
After publishing a new dataset.

* Which page(s) does it occurs on?*
All pages.

* What happens?*
The dataset has no index that is more recent than the publishing time.

* To whom does it occur (all users, curators, superusers)?*
All users.

* What did you expect to happen?*
Dataset is indexed.

**Which version of Dataverse are you using?**
5.14, 6.0, 6.1

**Any related open or closed issues to this bug report?**
#9199

**Comment by landreev** [comment]
@scolapasta Could you please remind me, as you were investigating this in our prod., did it really look like that indexing time stamp was somehow being set to a time prior to the publication time _within_ the latest publication of the datasets in question? (as opposed the dataset *not getting reindexed at all* after it was re-published; with the indexing timestamp still referring to when it was indexed after a previous publishing)
