### ISSUE TITLE
Geospatial metadata block > bounding box coordinates fields > tool tips are INCORRECT and mention use of commas

### ISSUE THREAD

**Issue by amberleahey** [IQSS/dataverse#10397]
Using 6.1 release
-->
**What steps does it take to reproduce the issue?**
enter geospatial metadata > bounding box coordinates for a dataset using the tool tips in Dataverse UI (hover over coordinate field boxes) 
![image1](https://github.com/IQSS/dataverse/assets/17624834/30165c15-e830-49cc-a15a-adffaf542071)

This tool tip in the UI mentions the use of commas instead of decimals points, this is incorrect formatting and will fail against the validation now added for geospatial bounding box validation for geospatial search

* When does this issue occur?
Enter this metadata according to the UI tool tip and it will fail
![image2](https://github.com/IQSS/dataverse/assets/17624834/149af2e9-d94c-42c7-9fca-98041ca26a38)
![image4](https://github.com/IQSS/dataverse/assets/17624834/add241fa-c3b8-457d-ac9c-348e1feabcba)
![image3](https://github.com/IQSS/dataverse/assets/17624834/ce0d8efb-e6b2-48e5-8e57-63824e7b175d)

* Which page(s) does it occurs on?

Geospatial metadata > bounding box coordinates
* What happens?
fails when using tool tip in UI for use of commas in coordinates (not best practice and will fail validation)

* To whom does it occur (all users, curators, superusers)?
all users

* What did you expect to happen?

Let's improve the tool tip to remove mention of commas and replace with decimals. The general UI tool tip for this field can specify only - and decimals . are appropriate to use

**Which version of Dataverse are you using?**
6.1 

**Any related open or closed issues to this bug report?**
yes lots for geospatial metadata, will link shortly

**Screenshots:**

No matter the issue, screenshots are always welcome.

To add a screenshot, please use one of the following formats and/or methods described here:

* https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests
*

**Comment by amberleahey** [comment]
Related to: https://github.com/IQSS/dataverse/issues/7455 ; https://github.com/IQSS/dataverse/issues/7947 ; https://github.com/IQSS/dataverse/issues/7108 ; https://github.com/IQSS/dataverse/issues/7091 ; https://github.com/IQSS/dataverse/issues/10397

**Comment by amberleahey** [comment]
Dataverse Guides need to be changed as well : https://docs.google.com/spreadsheets/d/13HP-jI_cwLDHBetn9UKTREPJ_F4iHdAvhjmlvmYdSSw/edit#gid=4 & https://github.com/IQSS/dataverse/blob/master/scripts/api/data/metadatablocks/geospatial.tsv 

We will be updating this in our user guides and best practices as well.

**Comment by sbarbosadataverse** [comment]
3/20/24 GitHub issue review meeting with Gustavo, Sonia, Julian:

Gustavo is sizing this as a "3" to address the tooltip changes mentioned "Let's improve the tool tip to remove mention of commas and replace with decimals. The general UI tool tip for this field can specify only - and decimals . are appropriate to use"

Julian will make this change: "Dataverse Guides need to be changed as well : https://docs.google.com/spreadsheets/d/13HP-jI_cwLDHBetn9UKTREPJ_F4iHdAvhjmlvmYdSSw/edit#gid=4 & https://github.com/IQSS/dataverse/blob/master/scripts/api/data/metadatablocks/geospatial.tsv"

**Comment by landreev** [comment]
Really weird that we managed to miss this, when we invested a good effort into fixing the actual validation for the values (I consulted on and reviewed the fixes, so I'm taking responsibility for it). We are going to try and add the fixed tooltips to 6.2 tomorrow (updating the block is already part of the 6.2 upgrade, so why not address this as well).

To address some questions from the planning meeting yesterday - yes, there are some places in the world where commas are used in coordinate values. I don't think we should worry about this in the context of fixing the tooltips in the block as we distribute it. Our normal approach is for all the labels in the core blocks to be in en_US locale. They can be localized through extra properties files if desired. It's slightly less complicated for these specific tooltips - they are not just labels, they need to match the validation rules that will be applied to the entered values. So, anyone translating this particular block would need to check and confirm how the validation works in their locale. 😄 But, once again, I don't think this should be a concern for the purposes of fixing the block .tsv as distributed.

**Comment by amberleahey** [comment]
amazing thanks! agree, we noted some use of commas in metadata in French in Quebec here in Canada, but largely this is for display and many technical GIS systems use decimals widely. All the best! thanks again for these fixes in 6.2 looking forward to using the new validation in the block!

**Comment by landreev** [comment]
(Just read my comment from the other day - I obviously meant "... it's slightly _more_ complicated", not "less" 🙂)
