### ISSUE TITLE
API Documentation of Explicit Groups

### ISSUE THREAD

**Issue by CB-HAL** [IQSS/dataverse#10411]
**What steps does it take to reproduce the issue?**
The section https://guides.dataverse.org/en/5.12.1/api/native-api.html?highlight=list%20explicit%20groups#explicit-groups of the API Guide is not fully correct. For the usage of explicit groups is an API key necessary, e.g.:
  `GET http://$server/api/dataverses/$id/groups`
-> {"status":"ERROR","message":"User :guest is not permitted to perform requested action."}
Correct with API key:
`curl -H X-Dataverse-key:xxx  http://$server/api/dataverses/$id/groups`

**Which version of Dataverse are you using?**
API Guide 5.12.1, latest v6.1 also.

**Comment by pdurbin** [comment]
Yes, I confirmed that 6.1 is no better. Thanks for reporting this.

@CB-HAL are you interested in making a pull request? The file to edit is https://github.com/IQSS/dataverse/blob/develop/doc/sphinx-guides/source/api/native-api.rst

**Comment by CB-HAL** [comment]
Thanks for the offer (I‘m honoured), but I’m a dedicated amateur (sociologist with a little IT knowledge) and far away to do professional development…

**Comment by pdurbin** [comment]
Ha! No worries! Thanks again for letting us know!

**Comment by pdurbin** [comment]
@CB-HAL good news! @zearaujo25 came along and created pull request #10427.

I just merged it. Can you please check out the preview version of the guides below to see if it helps?

https://dataverse-guide--10427.org.readthedocs.build/en/10427/api/native-api.html#explicit-groups
