### ISSUE TITLE
When solr down, we should say Dataverse is down

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#1042]
Currently just shows dataverse page with no results. It's too confusing.

We could add a backup way some day, but for now, let's just say dataverse is down, since we rely on Solr so much.

**Comment by mheppler** [comment]
I couldn't stand looking at it another minute.

![screen shot 2015-04-01 at 5 34 22 pm](https://cloud.githubusercontent.com/assets/687227/6953210/d82c83dc-d895-11e4-83c1-17a96c4dc4db.png)

**Comment by eaquigley** [comment]
Closing ticket due to @mheppler's update; messaging is fine.
