### ISSUE TITLE
Deleted dataset or incorrect URL path throws error that looks like a system error

### ISSUE THREAD

**Issue by DonRichards** [IQSS/dataverse#10434]
**What steps does it take to reproduce the issue?**
Delete a dataset and try to go to the original path. Example of URL (likely not related to he issue .../dataset.xhtml?persistentId=doi:10.7281/T1/HSYYZ0&version=1.0) 

* When does this issue occur?
Throws several errors on the page that adds confusion to the user.

* Which page(s) does it occurs on?
dataset page

* What happens?
Throws `Internal Server Error - An unexpected error was encountered, no more information is available.`

* To whom does it occur (all users, curators, superusers)?
Mostly system admins

* What did you expect to happen?
Redirect or a 404. 

**Which version of Dataverse are you using?**
v. 5.14 build 1471-9f4ddbb

**Any related open or closed issues to this bug report?**
I didn't see any

**Screenshots:**
![Screenshot from 2024-03-27 10-19-55](https://github.com/IQSS/dataverse/assets/2738244/52631351-c895-4cf1-9ada-14c0a3e38132)

**Comment by pdurbin** [comment]
@DonRichards thanks for the bug report. Just to be clear, since you wrote "1.0", I assuming are you doing a "destroy" of a published dataset (requires superuser) as opposed to deleting the only draft of a dataset that's never been published.

Either way, you shouldn't get a 500 error like that!

Can you share the server.log?

**Comment by DonRichards** [comment]
@pdurbin The only thing I see in the server.log file is this but it doesn't seem to come up ever time I try a different URL. This is for a random ID. 
```
[#|2024-04-15T09:19:24.667-0400|WARNING|Payara 5.2022.3|edu.harvard.iq.dataverse.DatasetPage|_ThreadID=102;_ThreadName=http-thread-pool::jk-connector(4);_TimeMillis=1713187164667;_LevelValue=900;|
  Failed to retrieve version|#]
```

We just updated our server and now we're getting a 404 error page (expected behavior for the most part). So we could probably close this.

**Comment by pdurbin** [comment]
Yes, a 404 is expected. I guess I'll close this. Please don't hesitate to reach our if you find similar weirdness!
