### ISSUE TITLE
Jenkins having trouble building guides

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#10457]
When releasing 6.2 we learned that Jenkins is having trouble building the guides. (We upgraded Sphinx in 6.2.)

We should fix it as it's our documented procedure: https://guides.dataverse.org/en/6.2/qa/test-automation.html#guides-dataverse-org

(Please feel free to edit this description with details! I'm not sure how to size this.)

**Comment by donsizemore** [comment]
this is fixed by pointing /etc/alternatives at /usr/bin/pip3.9

sphinx 7.2.6 requires python-3.9+ so it's strange this hasn't come up before.
