### ISSUE TITLE
Add DataLad to list of integrations

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#10468]
Over the weekend, during the [Distribits](https://distribits.live/) hackathon, @bpoldrack and I [tweaked](https://github.com/datalad/datalad-dataverse/pull/305) some documentation and confirmed that integration between Dataverse and DataLad is working fine. We were able to push push DataLad datasets into Dataverse and then use DataLad to clone them from Dataverse.

In the DataLad chat I asked if they're ready to list DataLad on our list of integrations at https://guides.dataverse.org/en/latest/admin/integrations.html and @mih said yes and sounds willing for the DataLad folks to make a pull request. The file to edit is https://github.com/IQSS/dataverse/blob/develop/doc/sphinx-guides/source/admin/integrations.rst and I'd say somewhere under "Getting Data In" is a good fit. Thanks in advance for the pull request! ❤️ 

---

By the way, Benjamin did demo this a while back, back during the [2022-07-12](https://docs.google.com/document/d/1UKMjIDIgLIGX1cV1_Mi4j6KnirCz827BZItPnI-K8I8/edit?usp=sharing) community call. We still haven't address this issue that's preventing them from uploading a directory that starts with a dot (e.g. `.datalad`) and we should:

- #8807

**Comment by jsheunis** [comment]
Thanks for the issue, I'll get cracking on this.
