### ISSUE TITLE
Captcha question in contact form doesn't appear on 403 error page

### ISSUE THREAD

**Issue by jeromeroucou** [IQSS/dataverse#10466]
**What steps does it take to reproduce the issue?**

* When does this issue occur?

When a authenticated user requests access to a resource (URL) for which he doesn't have rights (for example, a dataset in draft mode).

* Which page(s) does it occurs on?

On the 403 error page, or _"Not Authorized"_

* What happens?

A 403 error page is displayed, and telling to the user he or she doesn't have rights, with a link opening a contact form. In this case, the question _"Please fill this out to prove you are not a robot."_ only display ` + =`. And when the form is submitted, a `NullPointerException` is thrown, indicating that variable `op1` is null.

* To whom does it occur (all users, curators, superusers)?

All users who doesn't have the correct privilege on the asked resource.

* What did you expect to happen?

The contact form have to be complete with the captcha question

**Which version of Dataverse are you using?**

`5.14`, but there is present on `6.2` (`develop` branch)

**Any related open or closed issues to this bug report?**

I don't find any other issue on this theme.

**Screenshots:**

![403_error_contact_form](https://github.com/IQSS/dataverse/assets/13969969/863f9341-b13d-4639-8c3c-b698e1610b34)

**Comment by pdurbin** [comment]
Huh, this reminds me of this issue:

- #3036

Which we (partially?) fixed in this PR:

- #3573

**Comment by jeromeroucou** [comment]
Indeed, the problem seems to be linked to the linked issue. I doesn't know why but in case of 403 error page, `actionListener="#{sendFeedbackDialog.initUserInput}"` isn't called.

A quick fix can be to add a verification on `opX` parameters, for example :

```diff
public String getMessageTo() {
+    if (op1 == null or op2 == null) {
+        initUserInput(null);
+    }
    if (feedbackTarget == null) {
        return BrandingUtil.getSupportTeamName(systemAddress);
    } else if (feedbackTarget.isInstanceofDataverse()) {
        return ((Dataverse) feedbackTarget).getDisplayName() + " " + BundleUtil.getStringFromBundle("contact.contact");
    } else {
        return BundleUtil.getStringFromBundle("dataset") + " " + BundleUtil.getStringFromBundle("contact.contact");
    }
}
```
