### ISSUE TITLE
Tag version for the container base image

### ISSUE THREAD

**Issue by poikilotherm** [IQSS/dataverse#10478]
**Overview of the Feature Request**

People are sometimes struggling with the base image when building the application image. When there are changes pushed to the unstable tag, sometimes people still use a cached version and run into problems.

**What existing behavior do you want changed?**

We should tag the base image with some versioning scheme and make the application image use the tag by default. That way people will receive newer base image versions automatically.

**Any open or closed issues related to this feature request?**

More discussion here: https://dataverse.zulipchat.com/#narrow/stream/375812-containers/topic/change.20version.20scheme.20base.20image.3F

**Comment by cmbz** [comment]
2024/07/19 - 6.4 proposal request from @poikilotherm

**Comment by pdurbin** [comment]
At https://guides.dataverse.org/en/6.6/container/running/production.html we say to look to this issue (#10478) for updates but really people should follow this one:

- #10618
