### ISSUE TITLE
Extend the API to expose the dataset creation fields configured in the General Information page

### ISSUE THREAD

**Issue by GPortas** [IQSS/dataverse#10477]
**Overview of the Feature Request**

The metadata fields that are set as required in the General Information page of the collection cause them to be displayed when creating the datasets. So we need to extend the API in addition to the extension we have already implemented in https://github.com/IQSS/dataverse/pull/10418.

So the `displayOnCreate` flag is not the only condition to display a block and its fields in the create dataset form. We can test this by adding a metadata block in the General Information page and we will see how when creating a dataset that block appears with the fields marked as required.

**What kind of user is the feature intended for?**
API User

**What inspired the request?**

- SPA requirements

**What existing behavior do you want changed?**

- Exposed dataset creation fields for a particular collection

**Any brand new behavior do you want to add to Dataverse?**

- None

**Any open or closed issues related to this feature request?**

-https://github.com/IQSS/dataverse/pull/10418

**Comment by pdurbin** [comment]
Closed by this PR:

- #10498
