### ISSUE TITLE
Feature Request/Idea: Add psql to the configbaker image

### ISSUE THREAD

**Issue by vera** [IQSS/dataverse#10487]
**Overview of the Feature Request**

We would like `psql` to be added to the configbaker image, so `psql` commands can be used during initial setup of Dataverse.

**What inspired the request?**

We are using the configbaker image for a bootstrap pod in our Kubernetes setup. We would like to create our own custom `generateIdentifierFromStoredProcedure` function within Postgres as part of the bootstrapping. However, we can't connect to the Postgres and run the CREATE command from the bootstrap pod, since the image doesn't have `psql` available.

**Comment by pdurbin** [comment]
@vera sure, @poikilotherm and I have no objection. From the discussion in Zulip at https://dataverse.zulipchat.com/#narrow/stream/375812-containers/topic/add.20psql.20to.20configbaker/near/432869945 it sound like the package can be added to ARG APK_PACKAGES="curl bind-tools netcat-openbsd jq bash dumb-init wait4x ed" at https://github.com/IQSS/dataverse/blob/v6.2/modules/container-configbaker/Dockerfile#L24

Would you like to make a pull request?

**Comment by johannes-darms** [comment]
Done https://github.com/IQSS/dataverse/pull/10488 :)
