### ISSUE TITLE
Metadata: Should required fields from Other Metadata block stay after checking on Metadata Elements from Host Dataverse

### ISSUE THREAD

**Issue by esotiri** [IQSS/dataverse#1048]
This came up after https://github.com/IQSS/dataverse/issues/1047 

When Creating a new dataverse > uncheck Metadata Elements from Host Dataverse > check ie. Geospatial Metadata and mark some required fields > create dataverse. 
Go back and edit dataverse > general info > check on Metadata Elements from Host Dataverse > Should required fields from Other Metadata block stay after checking on Metadata Elements from Host Dataverse?

**Comment by sekmiller** [comment]
Now if a user tries to go back to inherit metadatablocks he will get a warning pop-up.  Going to custom does not trigger a warning.  User should be able to cancel the pop-up and revert to original state.
New build required for testing

**Comment by posixeleni** [comment]
Tested and works as expected. Closing.

![image](https://cloud.githubusercontent.com/assets/5013837/6756266/0c0b994a-ceff-11e4-8ca1-5f111dc4cc5f.png)
