### ISSUE TITLE
INSTALL ERROR

### ISSUE THREAD

**Issue by weii323** [IQSS/dataverse#10493]
**What steps does it take to reproduce the issue?**

* When does this issue occur?
After I completed both the prerequisites and the installation part, and followed the tutorial to the next step of accessing http://localhost.localdomain:8080, the page says Page Not Found - The page you are looking for was not found. 

* Which page(s) does it occurs on?

After I completed both the prerequisites and the installation part, and followed the tutorial to the next step of accessing http://localhost.localdomain:8080, the page says Page Not Found - The page you are looking for was not found. 
* What happens?

* To whom does it occur (all users, curators, superusers)?

* What did you expect to happen?

**Which version of Dataverse are you using?**

**Any related open or closed issues to this bug report?**

**Screenshots:**
![image](https://github.com/IQSS/dataverse/assets/72862275/274adad1-772c-481c-a4c2-0e13ee021a49)

No matter the issue, screenshots are always welcome.

To add a screenshot, please use one of the following formats and/or methods described here:

* https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests
*

**Comment by poikilotherm** [comment]
Hi @weii323!

Thank you for opening this issue. As this is about troubleshooting your installation, please join us on Zulip to dig deeper into this. You can find instructions to join in https://chat.dataverse.org. A preview of the troubleshooting channel is also available: https://dataverse.zulipchat.com/#narrow/stream/378866-troubleshooting

I am going ahead and close this issue. See you on Zulip!

**Comment by pdurbin** [comment]
@weii323 thanks for starting a topic on Zulip: https://dataverse.zulipchat.com/#narrow/stream/378866-troubleshooting/topic/Installation.20issues

If someone else has a similar problem, maybe they'll be able to find an answer there!
