### ISSUE TITLE
Add "Group + Roles" tab to account page 

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#105]
---

Author Name: **Xiangqing Yang** (@xyang02)
Original Redmine Issue: 3514, https://redmine.hmdc.harvard.edu/issues/3514
Original Date: 2014-02-03
Original Assignee: Xiangqing Yang

---

Add "Group + Roles" tab to the account page to display groups and roles of the user. User could choose to leave the group he/she belongs to and remove his/her role.

**Comment by kcondon** [comment]
Addressed some of the functionality with MyData by putting role next to the data.
