### ISSUE TITLE
Simplify thumbnail handling code and swap the image generation library

### ISSUE THREAD

**Issue by stevenwinship** [IQSS/dataverse#10515]
Two thing need to happen here:
1. Simplify the thumbnail generation code. There needs to be a more tight set of methods for getting and generating thumbnails. It seems as though the code was written over time with multiple ways of getting/creating thumbnails.
2. The current thumbnail creation code fails to generate images for some TIFF files, even though the file sizes are grater than 0 bytes the thumbnails, when resized, come back as 0 bytes. It was subjected to switch to ImageMagick.

**What kind of user is the feature intended for?**
intended for all users

**What inspired the request?**
Bugs in TIFF thumbnail generation

**What existing behavior do you want changed?**
More thumbnails being generated instead of generic images

**Any brand new behavior do you want to add to Dataverse?** No

**Any open or closed issues related to this feature request?**

- https://github.com/IQSS/dataverse/issues/10317
- https://github.com/IQSS/dataverse/pull/10509

**Comment by landreev** [comment]
@pdurbin did you mean to reference a different issue above? 
There is a recently opened #10351 that I just mentioned in #10509. 

But, we can definitely use this new issue to handle it and close all the duplicates in favor of it.

**Comment by cmbz** [comment]
Closing as not planned.
