### ISSUE TITLE
Implement a global setting and/or API for dataset types

### ISSUE THREAD

**Issue by cmbz** [IQSS/dataverse#10518]
## Overview
- See https://github.com/IQSS/dataverse-pm/issues/307 and [Proposal: Supporting Multiple Dataset Types in Dataverse](https://docs.google.com/document/d/16RvGXmaPQK9DGsEEbrrFEu8mjUrN93YY_yh7ZONyMDI/edit?usp=sharing) for details

## Scope of Work
- Implement a global setting and/or API
  - Allows admins to decide whether the new Software and Workflow types are allowed or not for their installation

## Depends on
- https://github.com/IQSS/dataverse/issues/10517

## Note
- The functionality of this issue and https://github.com/IQSS/dataverse/issues/10517 should be delivered in a single release to better support UX.

**Comment by pdurbin** [comment]
I just marked this pull request as closing this issue because it includes a feature flag for dataset types:

- #10694

**Comment by pdurbin** [comment]
I checked with @cmbz and she said to go ahead and remove it from the board (since there's already a PR that will close it).

**Comment by pdurbin** [comment]
Closing. We decided not to do this.
