### ISSUE TITLE
Create the datasetType class and add UI facet

### ISSUE THREAD

**Issue by cmbz** [IQSS/dataverse#10517]
## Overview
- See https://github.com/IQSS/dataverse-pm/issues/307 and [Proposal: Supporting Multiple Dataset Types in Dataverse](https://docs.google.com/document/d/16RvGXmaPQK9DGsEEbrrFEu8mjUrN93YY_yh7ZONyMDI/edit?usp=sharing) for details

## Scope of Work
- Enables users to tag their datasets as a specific datasetType
- Available only at dataset creation time
  - Implement access via API. Therefore, the create dataset API will have this option, but datasetType can only be set at create time
  - Implement access via UI
- Add UI facet to support `datasetType`
- Functionality is not activated by default
- Send an appropriate type to DataCite (maybe also other PID providers)

## Note
- The functionality of this issue and https://github.com/IQSS/dataverse/issues/10518 should be delivered in a single release to better support UX.

**Comment by pdurbin** [comment]
The pull request is ready for review:

- #10694

**Comment by johannes-darms** [comment]
Please allow users or at least curators to change the datatype after initial creation.

**Comment by poikilotherm** [comment]
Is there any literature on good practices regarding changing a resource type after initial publication?

IMHO it should be fine to allow the switch for an initial draft. Not so sure about an already published entity, hence the question about best practices.

@jggautier are you aware of anything?

**Comment by jggautier** [comment]
@poikilotherm I'm not aware of any literature on good practices regarding changing a resource type after initial publication.
