### ISSUE TITLE
404static.xhtml has an old date in the footer (2023 is hard-coded)

### ISSUE THREAD

**Issue by BenediktMeierUIT** [IQSS/dataverse#10527]
**What steps does it take to reproduce the issue?**
If you call up a flat page, an error page "404static.xhtml" appears. This still has an old date in the footer. Maybe you should adjust something there too?

**Screenshots:**
https://github.com/IQSS/dataverse/blob/develop/src/main/webapp/404static.xhtml

![Screenshot from 2024-04-24 10-19-09](https://github.com/IQSS/dataverse/assets/149382667/7aaee466-86ec-4552-9b8c-40b516918bcb)

**Comment by pdurbin** [comment]
@BenediktMeierUIT good idea. I've used something like this before:

```
let date = new Date();
document.getElementById("current-year").innerHTML = date.getFullYear() + " ";
```

Are you interested in making a pull request? 😄

**Comment by BenediktMeierUIT** [comment]
yes, I will do that.
