### ISSUE TITLE
The "--skip_db_setup"-option of install.py seems not to be recognized

### ISSUE THREAD

**Issue by faborg** [IQSS/dataverse#10534]
We'd like to install dataverse with 3 Servers running apache2/payara6 (being load-balanced).

The installation of the first Server with apache2/payara6 works fine with the command `python3 install.py -y`. The database is set up and Dataverse is deployed on the Server.

For the remaining two Servers with apache2/payara6 I tried the command `python3 install.py -y --skip_db_setup`. And here the problem occurs:

```bash
Waiting for domain1 to start ......
Successfully started the domain : domain1
domain  Location: /usr/local/payara6/glassfish/domains/domain1
Log File: /usr/local/payara6/glassfish/domains/domain1/logs/server.log
Admin Port: 4848
Command start-domain executed successfully.
/opt/dataverse-prepared/dataverse/scripts/installer
Payara setup complete
Mon Apr 29 11:20:41 UTC 2024

Installing additional configuration files (Jhove)... 
done.
Deploying the application (dataverse.war)

PER01003: Deployment encountered SQL Exceptions:
	PER01000: Got SQLException executing statement "CREATE TABLE EXTERNALTOOLTYPE (ID  SERIAL NOT NULL, TYPE VARCHAR(255) NOT NULL, EXTERNALTOOL_ID BIGINT NOT NULL, PRIMARY KEY (ID))": org.postgresql.util.PSQLException: ERROR: relation "externaltooltype" already exists
----
....
```

As you can see we get SQL-errors because the installer tries to create Tables in the database.

Is there a way to skip this db_setup-step on the remainig apache2/payara-Servers?

Thanks in advance!

**Comment by qqmyers** [comment]
I don't think this can be skipped, but it should be non-fatal. This is something seen when upgrading as well. Dataverse tries to create the table, and reports a failure because the table exists, but the end result is the table is there and ready for use. I think there has been some discussion about changing Dataverse to avoid this and there may be an issue for it.

**Comment by pdurbin** [comment]
@qqmyers yes, you might be thinking of this:

- #5871
