### ISSUE TITLE
Permissions: Edit role page needs vertical scrolling.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1054]
When editing a role, such as manager, the contents is more than a page long but there is not scroll bar.

**Comment by mheppler** [comment]
I think this was closed after a check in #5e4b2b66c9ef00aae27a574a0a329f12f6ae2127 and it wasn't sent to QA. Sorry.

**Comment by kcondon** [comment]
OK, can see entire page well with new layout. Closing.
