### ISSUE TITLE
Document how to use ZGC for Solr

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#10548]
@donsizemore @jp-tosca and I were talking about https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=120723174 during today's Containerization meeting.

It might be worth documenting how to configure Solr to use ZGC at a test to see if it improves performance.

Part of:

- #10469

**Comment by pdurbin** [comment]
I'm not particularly interested in this myself. Closing. Please feel free to open a fresh issue.

**Comment by cmbz** [comment]
2024/08/23: Reopening because issue was already sized and prioritized.
