### ISSUE TITLE
Bulk clear notifications

### ISSUE THREAD

**Issue by mankoff** [IQSS/dataverse#10556]
Is there an API call to clear all notifications? I do not have the time or thumb muscles to click my mouse 418 times.

**Comment by pdurbin** [comment]
I think you'll have to get them all with https://guides.dataverse.org/en/6.2/api/native-api.html#get-all-notifications-by-user

And then delete them one by one with https://guides.dataverse.org/en/6.2/api/native-api.html#delete-notification-by-user

I take it you'd like a single API for this? 😄

**Comment by pdurbin** [comment]
Related:

- #9221
- #2892

**Comment by mankoff** [comment]
Thanks. A for loop is close enough to `bulk` for me:

```bash
curl -H "X-Dataverse-key:$API_TOKEN" "$SERVER_URL/api/notifications/all" > ~/tmp/dv.json
for id in $(cat ~/tmp/dv.json | jq | grep "id\":" | tr -cd '[[:digit:]]\n'); do
  curl -H "X-Dataverse-key:$API_TOKEN" -X DELETE "$SERVER_URL/api/notifications/${id}"
done
```
