### ISSUE TITLE
Add "Submit for Review" Option for Datasets Uploaded by CAFE Admin

### ISSUE THREAD

**Issue by Saixel** [IQSS/dataverse#10577]
## Background
Currently, when a public user (i.e., no administrator privileges) submits a dataset to the CAFE repository, they can either "save as draft" or "submit for review." However, when a CAFE administrator uploads a dataset to the repository, the options are "save as draft" or "publish."

## Issue
We need to add a third option, "submit for review," for datasets uploaded by CAFE administrators. This will allow other administrators to review the dataset and metadata before it is published.

## Feature Request
- Implement a "submit for review" option for datasets uploaded by CAFE administrators.
- Ensure that this option allows datasets to be reviewed by other administrators before publication.

## Justification
This feature will ensure that datasets uploaded by administrators undergo the same review process as those uploaded by public users, maintaining data quality and consistency.

## Implementation Considerations
- Review the current workflow for dataset submission by administrators.
- Develop and test the necessary changes to include the "submit for review" option.
- Ensure that the review process for administrators is consistent with the process for public users.

## Additional Context
This request emerged from discussions during the data management meeting, highlighting the need for a review process for datasets uploaded by administrators to ensure metadata standards are met before publication.

**Comment by sbarbosadataverse** [comment]
@Saixel Hi Alexis, 
It would be best if CAFE turned all non essential admins into "contributors," and they can all submit their content for review.
The existing workflow allows all collection admins to publish content, a concrete action. Changing this workflow would break the collection-level admin permission workflow. Does everyone listed as an admin now in CAFE need to have that role? If not, they can be moved to contributors.

**Comment by Saixel** [comment]
Following the recommendation, we decided to convert non-essential admins to "contributors." This solution allows contributors to submit content for review without disrupting the current collection-level admin permission workflow. As this approach meets the intended objective, we are marking this as resolved.
