### ISSUE TITLE
Permissions: If attempt to access unpublished dv as registered user without perms, get log in page.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1057]
I attempted to paste the url for root dv into the browser when logged in as a user without perms:
https://dvn-build.hmdc.harvard.edu/dataverse.xhtml?id=287

It sent me to the log in page even though the navbar showed that I was still logged in.

**Comment by mheppler** [comment]
Duplicate issue of this was created and closed.

Dataverse/Dataset (Unpublished) - No Access/Permsission Landing Page #1704

Related to 404 issue.

404 Not Found - Browser Gets Forwarded to /404.xhtml #2367

**Comment by sekmiller** [comment]
To differentiate between a url that yields an object that is not found and one that is found, but the session user does not have permission to view, I have added a 403.xhtml page

**Comment by sekmiller** [comment]
Added redirect logic for Dataverse and Dataset pages

**Comment by kcondon** [comment]
OK, works for logged in user without sufficient perms, for user who is not logged in, they go to the log in page. Closing.
