### ISSUE TITLE
Emails sent to Dataset Owners from "Guestbook at Request Access" missing key information and are hard to read due to Q/As being in random order and no formatting between

### ISSUE THREAD

**Issue by mdmADA** [IQSS/dataverse#10581]
------------------------------------------------------------------------

**Description:**

Note that the email issues detailed below are costing ADA a lot of additional time and resources, so it is a critical issue for ADA's day-to-day operations.

**The email that is sent to dataset/owners has the following issues:**

**1. The subject line is the same for every request for the same dataset.** 

- If there are many requests, this makes it impossible to pick out unique requests per user when looking at the email inbox and/or a ticketing system where tickets are generated with the email subject. 
- The access/ticket manager has to open each email to see who requested it. [Dataverse sends the emails from ADA's email address so the emails/tickets all have the same "from" so that doesn't assist in unique identification].

Now, **in dv 6.2, the email subject is:
ADA Dataverse : Access has been requested for a restricted file in dataset "dataset title"**

If there are 100 emails for dataset x then there will be 100 emails with the same subject line with no uniquely identifying information.

ADA's previous Dataverse installation email subject sent to Dataset owner/contact:
**ADA Dataverse: “Firstname Lastname (@xxxxxx)" requested access to dataset “dataset title"**

If there are 100 emails from 100 different users requesting access, there are 100 unique email subject lines, so the access/ticket manager can see them at a glance without having to open each ticket/email.

**ADA is requesting the email subject be changed to (where xxxx is the root dataverse):
   xxxx Dataverse: “Firstname Lastname (@xxxxxx)" requested access to dataset "dataset title"** 

**2. The user details in the email should include:**

Name:
Email:
Institution:
Position:
authenticateduserid: numeric_database_id
useridentifier: @useridentifier

**3. The Questions from the user's guestbook response are not in the same order as the guestbook itself and are random order from email to emai.**

The Q/A pairs should be written to the email in the displayorder as specified for the guestbook.

**4. There is no spacing between the Q/A pairs so it is almost impossible to read** for long and more complex answers.

One or 2 blank lines between each Q/A pair is necessary for readability.

NOTE: 3 and 4 also occur for the email sent to the user who requested access. Not sure if a new bug report is required for that?

------------------------------------------------------------------------

**What steps does it take to reproduce the issue?**

1. Either you or someone else go to a dataset that has:
-  "guestbookAtRequestAccess" flag set to true
-  restricted files
-  assigned guestbook with custom questions
- the dataset owner/contact is set such that you will receive the request access email sent to the dataset owner/contact to alert them to the request

2. Click "Request Access"

3. Enter answers to the custom questions + Click "Request" or "Accept" in the popup

4. You will receive the email that was generated by the Access Request

------------------------------------------------------------------------

**When does this issue occur?**

When emails are generated for the dataset owner/contact in the "Guestbook at Request Access" functionality.
(The questions out of order also occurs in email sent to the requester).

------------------------------------------------------------------------

**Which page(s) does it occur on?**

Dataset.xhtml, file.xhtml, anywhere where there is a "guestbook at request access" email generated.

------------------------------------------------------------------------

**What happens?**
see description above

------------------------------------------------------------------------

**To whom does it occur (all users, curators, superusers)?**
Dataset owners/contacts and/or access/ticket managers who receive and mange the access requests with email and.or a ticketing system.

Questions out of order also occurs in the requester's email.

------------------------------------------------------------------------

**What did you expect to happen?**
See description at top.

------------------------------------------------------------------------

**Which version of Dataverse are you using?**
6.2

------------------------------------------------------------------------

**Any related open or closed issues to this bug report?**
No.

------------------------------------------------------------------------

Including @stevenmce for any further comments/information.

**Comment by stevenmce** [comment]
@pdurbin can you advise if this is something that can be worked on in the short term? This is a priority for ADA.

**Comment by pdurbin** [comment]
Let's ask @cmbz and @scolapasta

**Comment by mdmADA** [comment]
In re-reading this issue (that I created), please retain the guestbookresponse_id in the email (and add in the other id's requested).

**Comment by sekmiller** [comment]
We did not remove the guestbookresponse_id from the email.

**Comment by mdmADA** [comment]
Great - thank you!
