### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by mankoff** [IQSS/dataverse#10580]
Under https://guides.dataverse.org/en/latest/api/native-api.html#export-metadata-of-a-dataset-in-various-formats the line

```
curl "$SERVER_URL/api/datasets/export?exporter=$METADATA_FORMAT&persistentId=PERSISTENT_IDENTIFIER"
```

should have a `$` immediately before `PERSISTENT_IDENTIFIER`

**Comment by pdurbin** [comment]
@mankoff good catch. I made a PR:

- #10587
