### ISSUE TITLE
Dataverse on Debian and Ubuntu

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#1059]
The Dataverse team at Harvard has much more experience with RHEL/CentOS than Debian and Ubuntu but there is demand for supporting installation on these platforms, most recently at https://groups.google.com/d/msg/dataverse-community/3xqr8c_DFso/kT37maVD9E4J

This would be a great opportunity for contribution from members of the community who are familiar with Debian or Ubuntu.

Let's get it working in Vagrant first.

**Comment by pdurbin** [comment]
@lwo this is the issue I was telling you about and you're right that "Here be dragons!" if you run `export OPERATING_SYSTEM=debian` before you run `vagrant up`. Don't let that scare you, though! Please feel free to send us a pull request, even with the Puppet stuff we talked about at the [community meeting](http://projects.iq.harvard.edu/dataverse-community-meeting)! :)

For my part I run Ubuntu at home and my dev environment works fine. @abidart even documented Ubuntu from a dev perspective at http://guides.dataverse.org/en/4.0/developers/ubuntu.html

**Comment by lwo** [comment]
Sir @pdurbin: I'll begin forging a module once I get a go head.

**Comment by pdurbin** [comment]
Ubuntu and Debian are supported by the community in the form of these Puppet and Ansible repos by 

- https://github.com/IQSS/dataverse-puppet by @lwo
- https://github.com/IQSS/dataverse-ansible by @donsizemore

In my pull request at #2895 I give shout outs to these two projects. You can preview what I wrote here: http://guides.dataverse.org/en/2884-install-guide-reorg/installation/prep.html#advanced-installation

Both repos support Vagrant, which is great.

**Comment by kcondon** [comment]
This is a strategic decision that may consume more resources, particularly support. We would direct users of the puppet and ansible config solutions to their respective repositories for support and would only be able to offer best effort on supporting operational issues in those environments.

**Comment by pdurbin** [comment]
@oscardssmith this is the issue I was telling you about today if you'd like to try to get the Vagrant environment to work when you set the environment variable `OPERATING_SYSTEM` to `debian`: https://github.com/IQSS/dataverse/blob/v4.6.2/Vagrantfile#L23

I'm assigning it to you but if after you take a look you decide you aren't interested, you can just unassign yourself.

**Comment by pdurbin** [comment]
If anyone wants to work on this, please get in touch. For now, see the community efforts I mentioned at https://github.com/IQSS/dataverse/issues/1059#issuecomment-176512779 . Closing.

**Comment by pdurbin** [comment]
What's this! A DM from @4tikhonov with a link to a doc called **Running Dataverse repository on Kubernetes installed and deployed on Ubuntu 18.04 with local storage**".

Want. Sold. Reopening.

Links or it didn't happen, @4tikhonov 

@janetm once Dataverse Installation Personas are fully operational, we'll know who's running Ubuntu, Debian etc. https://github.com/IQSS/dataverse-installations/issues/16

![index](https://user-images.githubusercontent.com/21006/75836180-02637380-5d8f-11ea-9d71-dd2654026e50.jpg)

**Comment by poikilotherm** [comment]
Beware, the Glassfish container images sill use CentOS 7.

Payara Flavor is running on Debian.

**Comment by 4tikhonov** [comment]
@pdurbin, we're going to discuss it with @poikilotherm today as I need to clean up some things and the local storage definition requires own YAML specifications in the master branch.

My colleagues will try to install Dataverse on CentOS as well this week following the same guide.

**Comment by poikilotherm** [comment]
I'd vote to close this issue. We have been running Dataverse successfully on Ubuntu in containers for a long time now.

**Comment by pdurbin** [comment]
https://guides.dataverse.org/en/6.3/installation/prerequisites.html#linux does say, "A number of community members have installed the Dataverse Software in Debian/Ubuntu environments."

Besides, there's the (now merged) PR above on the Ansible side. And the Docker stuff, as you mention.

Sure, I'll close it. If anyone out there wants better Debian/Ubuntu support or more docs or whatever, please open an issue!
