### ISSUE TITLE
Download Metric Counter stuck

### ISSUE THREAD

**Issue by DominikWA** [IQSS/dataverse#10609]
We have the strange behavior that the shown download metric on the dataverse start page seems to be stuck: https://dataverse.iza.org . It stays at 539. But the API call give the correct higher count: https://dataverse.iza.org/api/info/metrics/downloads . The higher count seems to be correct since the database entries in the filedownload and guestbookresponse table have the same count. All entries have a time stamp, I have read in past issues and versions that this could be a potential problem. Additionally, the solr cache was recreated via API call.

Do you have any idea why the UI counter is not showing the correct number?

**Comment by qqmyers** [comment]
My guess is that https://groups.google.com/g/dataverse-community/c/CVj5nG3EIhA/m/uAhbXCcLAQAJ explains the issue.

**Comment by DominikWA** [comment]
This will most likely it. I hope that the upgrade from 5.13 to 6.2 with the docker version in the future will solve the problem for us.
