### ISSUE TITLE
Metadata Entries Cleared When Validation Error Shifts Focus to Host Dataverse Field (and editing it)

### ISSUE THREAD

**Issue by sergejzr** [IQSS/dataverse#10605]
**What steps does it take to reproduce the issue?**

1. Fill in some metadata fields on a dataset page.
2. Leave a required field empty.
3. Attempt to save, triggering the validation error due to the missing required field.
4. Note that the focus shifts to the "Host Dataverse" field.
5. Enter any text in the "Host Dataverse" field and then correct it by reselecting the original dataverse.
6. The mask is automatically cleared, which should not have been happened

* When does this issue occur?

This issue occurs when a required field is left empty and a validation error is triggered.

* Which page(s) does it occur on?

It occurs on any page where metadata for a dataset is entered.

* What happens?

When a required field is left empty, upon attempting to save, a validation error occurs. The focus moves to the "Host Dataverse" field, and any accidental typing in this field, followed by correction (reselecting the original dataverse), results in all previously entered metadata being cleared without warning.

* To whom does it occur (all users, curators, superusers)?

This issue occurs to all users entering metadata for a dataset.

* What did you expect to happen?

I expected the form to retain previously entered metadata when correcting the "Host Dataverse" field. Additionally, there should be a warning or confirmation prompt before clearing all fields when changing the "Host Dataverse".

**Which version of Dataverse are you using?**

This issue was encountered on Dataverse version 6.2 , tested with Firefox 126.0. and Chrome  125.0.6422.112

**Any related open or closed issues to this bug report?**

No related issues found.

**Screenshots:**

I recorded a video: https://www.youtube.com/watch?v=Eoot0C27vSU

**Proposed Improvement Suggestions:**

1. Implement a check to see if user input is already present before allowing the "Host Dataverse" field to clear all fields.
2. Display a confirmation prompt if user input is detected, asking the user if they are sure they want to change the dataverse and clear all fields.
3. Ensure that the focus, when a validation error occurs, should move to the first field with an error, not the "Host Dataverse".

Thank you for addressing this issue.

**Comment by pdurbin** [comment]
@sergejzr the good news is that for the new React-based front end, we are making the "collection field" read only until you try to edit it. Here's a screenshot:

![332856459-3534348f-fe92-4ce4-a337-204d2f26ee22](https://github.com/IQSS/dataverse/assets/21006/7626a028-c49d-48ab-96fb-84306ab4da6c)

The PR where this was added:

- https://github.com/IQSS/dataverse-frontend/pull/399

**Comment by sergejzr** [comment]
Thanks, @pdurbin this will solve the issue!

**Comment by sbarbosadataverse** [comment]
@scolapasta said to close as it will be fixed in new UI
