### ISSUE TITLE
Dataverse development in Windows

### ISSUE THREAD

**Issue by lubitchv** [IQSS/dataverse#10606]
In the developer's guide it recommended to use Docker container for those using windows https://guides.dataverse.org/en/latest/developers/windows.html#. Although it does not always work. At least I was not able to run Dataverse with Docker container on Windows. But it seems that Dataverse can be successfully run on Windows using WSL (Ubuntu).

**Comment by cmbz** [comment]
Recommendation
- Containerization Working Group should review
- @pdurbin @poikilotherm
