### ISSUE TITLE
Harvested dataset display is broken on develop branch

### ISSUE THREAD

**Issue by jeromeroucou** [IQSS/dataverse#10611]
**What steps does it take to reproduce the issue?**

With a Dataverse compiled with the latest version of the current development source code : 
* login as a super-user
* on dashboard page, add a new Harvesting Clients
* run the client
* after the client has finished, check that datasets have been harvested
* go to the dataverse page containing the harvested datasets
* the display of harvested datasets is like non-harvested (created on the repository)

**Which version of Dataverse are you using?**

I reproduce this bug after compiling the latest version of the code on `develop` branch.

**Any related open or closed issues to this bug report?**

I think this bug is related to the new feature #10298 : on [search-include-fragment.xhtml](https://github.com/IQSS/dataverse/blob/develop/src/main/webapp/search-include-fragment.xhtml#L506) at line 506, the display is conditioned by the [SolrSearchResult.isHarvested()](https://github.com/IQSS/dataverse/blob/develop/src/main/java/edu/harvard/iq/dataverse/search/SolrSearchResult.java#L140) method. The `harvested` attribute is set by [SearchServiceBean](https://github.com/IQSS/dataverse/blob/develop/src/main/java/edu/harvard/iq/dataverse/search/SearchServiceBean.java#L582) class at line 582.

With the new feature, `metadataSource` can now contain the repository source, [not only](https://github.com/IQSS/dataverse/blob/develop/src/main/java/edu/harvard/iq/dataverse/search/SearchServiceBean.java#L581) `Harvested` value.

**Screenshots:**

Actual
![harvested_datasets](https://github.com/IQSS/dataverse/assets/13969969/73373aa5-f677-4c89-9262-35fd9789b012)

Expected
![expected_harvested_datasets](https://github.com/IQSS/dataverse/assets/13969969/b19e2fca-1b03-4ef6-a065-c1b5d22a1f7e)

**Comment by landreev** [comment]
While we are fixing this - can we also make the new feature itself (showing the source of the Harvested metadata in the facet) configurable/optional? Just like with the new license facet, it appears that this may not be something we actually want in our own prod. here at Harvard. 
I'm personally ok with the new behavior being the default. But I'd like there to at least be a way to opt out of it. I.e., to be able to create a JVM option and keep the old behavior, of simply having one "Harvested" item in the "metadata source" facet.

**Comment by landreev** [comment]
(p.s. I'm happy to contribute or consult)

**Comment by landreev** [comment]
Made a draft PR.
