### ISSUE TITLE
Demo website: Add data explorer v2 to demo

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#10650]

**Comment by landreev** [comment]
OK, it is on demo. 
https://demo.dataverse.org/dataset.xhtml?persistentId=doi:10.70122/FK2/TKCIZ3
@sbarbosadataverse please take a look. 
Please note that I left the old version in place, for now: 
![Screen Shot 2024-08-22 at 12 44 05 PM](https://github.com/user-attachments/assets/b18cc3c0-7e36-400d-8fa5-ed29d3408772)
I'll remove it once we confirm v2 is functioning properly.

**Comment by landreev** [comment]
ok, closing.
