### ISSUE TITLE
Missing dataverse.db.parameters from long list of JVM options

### ISSUE THREAD

**Issue by poikilotherm** [IQSS/dataverse#10669]
Looks like we forgot to add it to the long list of options back when working on #7980.
It was in 8a1ee7e3af9a8d7e470c75249d421a4e292d532a, but it somehow got edited away #8915 :shrug: 
(It still is in the [DB section](https://guides.dataverse.org/en/latest/installation/config.html#basic-database-settings) of the guides)

**Comment by diptechexpo** [comment]
@poikilotherm I would like to fix this documentation issue. Can this be assigned to me?

**Comment by poikilotherm** [comment]
Yes of course, right away!

If you need some guidance what to do and what to write, we welcome you to join us at https://chat.dataverse.org 😊

**Comment by diptechexpo** [comment]
> Yes of course, right away!
> 
> If you need some guidance what to do and what to write, we welcome you to join us at https://chat.dataverse.org 😊

Thanks for your quick response and assigning me the issue. I am going through the contributor guideline and reach out in chat.dataverse.org if I need assistance.
