### ISSUE TITLE
Guestbook email field does not check email validity

### ISSUE THREAD

**Issue by DS-INRAE** [IQSS/dataverse#10661]
**What steps does it take to reproduce the issue?**
- Set a guestbook on a dataset
- Attempt downloading files from the dataset
- Enter a value in the email field of the guestbook which isn't a correct email
- Voilà !

**When does this issue occur?**
With any guestbook

**Which page(s) does it occurs on?**
Guestbook (therefore dataset page and preview tab of files page)

**What happens?**
Email are not checked

**To whom does it occur (all users, curators, superusers)?**
File downloaders/explorers

**What did you expect to happen?**
Verify that the email address inputed is actually an email address

**Which version of Dataverse are you using?**
v5.14 (also seen on Demo Dataverse running v6.2)

**Any related open or closed issues to this bug report?**
Functionally unrelated but on guestbook checks :
- https://github.com/IQSS/dataverse/issues/9492

**Screenshots:**

https://github.com/IQSS/dataverse/assets/46443753/894368a5-f3fc-436b-849d-aac0978643ef

**Comment by qqmyers** [comment]
related to #10625

**Comment by DS-INRA** [comment]
Related to the discussion on zulip on validators for guestbook, as that would impact the API part for these fields : https://dataverse.zulipchat.com/#narrow/stream/379673-dev/topic/metadata.20validators.20per.20field/near/449952746

**Comment by cmbz** [comment]
2024/08/19
- This could also impact frontend (we would want validation in UI as well as backend)
