### ISSUE TITLE
Temporary files in uploads directory not deleting automatically 

### ISSUE THREAD

**Issue by bikramj** [IQSS/dataverse#10667]
**What steps does it take to reproduce the issue?**

* When does this issue occur?
After upgrading to 6.2 version

* Which page(s) does it occurs on?
File uploads

* What happens?
Files in `uploads` directory are not getting cleared after successful uploads. We are using Openstack Swift S3. As workaround I  had to setup a cronjob to manually files from uploads directory

* To whom does it occur (all users, curators, superusers)?
all users

* What did you expect to happen?
After a successful upload, the temporary files from `uploads` should clear automatically 

**Which version of Dataverse are you using?**
6.2

**Any related open or closed issues to this bug report?**

**Screenshots:**
![image](https://github.com/IQSS/dataverse/assets/7265815/5ee1139f-6c7a-421a-b2fb-6153b6f31fed)

As you can see on our demo server, there are 69777 files after we upgraded to 6.2 on May 9

Related discussion: https://dataverse.zulipchat.com/#narrow/stream/378866-troubleshooting/topic/Uploads.20directory.20content.20not.20clearing.20after.206.2E2.20upgrade/near/441953212

**Comment by sbarbosadataverse** [comment]
@landreev any feedback here?

**Comment by landreev** [comment]
I wasn't aware of this as something introduced in 6.2 specifically. But I very strongly recommend to always have some automated cleanup of all the temporary directories when running Dataverse in production. If this is a new bug introduced in 6.2 we'll try to fix, but it is still safe to assume that *some* junk files will always accumulate in temp directories, just because some things always go wrong. 

This happens to be the reason we didn't notice this on our own production servers here at IQSS - we just clean that directory every 30 min., deleting everything older than 4 hours. This is our crontab entry: 

`15,45 * * * * /bin/find /uploads/web/ -mmin +119 -type f -name "upload*" -exec rm -f {} \; > /dev/null 2>&1`

Note that we also use `/uploads/web`, a temp directory outside the Payara domain where it ends up by default: 

```
grep 'dataverse\.files\.uploads' domain.xml
        <jvm-options>-Ddataverse.files.uploads=/uploads/web</jvm-options>
```

We have similar cleanup entries for all the other temporary directories.

**Comment by landreev** [comment]
What's interesting here is that this temp location is part of the PrimeFaces/Payara upload workflow. Their code will save the file there, but it is moved immediately after the upload completes to a location managed by Dataverse proper (where it may sit until the user clicks on "Save" in the UI). So it is a bit strange that files started to accumulate there, of all places. 
Did you by any chance upgrade Payara at the same time, when you upgraded Dataverse to 6.2? 
(I know we weren't recommending a Payara upgrade with that release, but asking just in case)

**Comment by bikramj** [comment]
Hi @landreev, Yes the Payara upgrade was part of 6.0 upgrade (5.13 -> 5.14 -> 6.0 -> 6.1 -> 6.2)
We have almost same `cronjob` to clear files from `uploads` dir, which was not needed before this upgrade. In total we have 4 corn jobs to clear all tmp directories.

**Comment by landreev** [comment]
I'm wondering if this has been happening since the upgrade to Payara 6, without anybody else noticing. 

Some extra weirdness: looking more closely at the files in the directory, only a few of them are actual uploaded files. Most are very small files that appear to only contain the names/states of individual jsf components: 
```
% ls -lat | head
total 130536
-rw-r--r--     1 landreev  wheel      1084 Aug 15 11:11 upload_3c282630_1915693841e__7ff7_00000010.tmp
drwxr-xr-x  1394 landreev  wheel     44608 Aug 15 11:11 .
-rw-r--r--     1 landreev  wheel        47 Aug 15 11:11 upload_3c282630_1915693841e__7ff7_00000009.tmp
-rw-r--r--     1 landreev  wheel        22 Aug 15 11:11 upload_3c282630_1915693841e__7ff7_00000008.tmp
-rw-r--r--     1 landreev  wheel        45 Aug 15 11:11 upload_3c282630_1915693841e__7ff7_00000007.tmp
-rw-r--r--     1 landreev  wheel         4 Aug 15 11:11 upload_3c282630_1915693841e__7ff7_00000006.tmp
-rw-r--r--     1 landreev  wheel        40 Aug 15 11:11 upload_3c282630_1915693841e__7ff7_00000005.tmp
-rw-r--r--     1 landreev  wheel         5 Aug 15 11:11 upload_3c282630_1915693841e__7ff7_00000003.tmp
-rw-r--r--     1 landreev  wheel        11 Aug 15 11:11 upload_3c282630_1915693841e__7ff7_00000000.tmp
% cat upload_3c282630_1915693841e__7ff7_00000009.tmp
datasetForm:filesTable datasetForm:filesButtons
% cat upload_3c282630_1915693841e__7ff7_00000008.tmp
datasetForm:fileUpload
% cat upload_3c282630_1915693841e__7ff7_00000007.tmp
datasetForm:fileUpload datasetForm:filesTable
% cat upload_3c282630_1915693841e__7ff7_00000006.tmp
true
% cat upload_3c282630_1915693841e__7ff7_00000005.tmp
-6774116795326397418:3131572445535781434
% cat upload_3c282630_1915693841e__7ff7_00000003.tmp
false                                                                                                              
```
etc. 
I have no idea what's up with these files; we obviously don't create them on purpose. 
Do we have some debug option turned on on the PrimeFaces level??
We should look into this. But, that said, this does look like something very specific to JSF and PrimeFaces; and therefore it will all go away once we switch to the SPA UI, so that would be an argument against spending too much time on this mystery.

**Comment by donsizemore** [comment]
In the interim, on RedHat-based systems `dataverse.files.directory/temp` may also be added to systemd-tmpfiles' configuration: https://www.baeldung.com/linux/systemd-tmpfiles-configure-temporary-files

**Comment by donsizemore** [comment]
A simpler solution for most installations, as proposed by @landreev would be to set `dataverse.files.uploads=/tmp` and not even have to configure tmpdir-cleaner:

```
[vagrant@localhost ~]$ ls -al /tmp
-rw-r--r--.  1 dataverse dataverse        11 Aug 28 18:48 upload_26e7dd4b_1919a4b9986__7ff5_00000000.tmp
-rw-r--r--.  1 dataverse dataverse         4 Aug 28 18:48 upload_26e7dd4b_1919a4b9986__7ff5_00000002.tmp
-rw-r--r--.  1 dataverse dataverse         4 Aug 28 18:48 upload_26e7dd4b_1919a4b9986__7ff5_00000003.tmp
-rw-r--r--.  1 dataverse dataverse         1 Aug 28 18:48 upload_26e7dd4b_1919a4b9986__7ff5_00000004.tmp
-rw-r--r--.  1 dataverse dataverse         4 Aug 28 18:48 upload_26e7dd4b_1919a4b9986__7ff5_00000005.tmp
-rw-r--r--.  1 dataverse dataverse        16 Aug 28 18:48 upload_26e7dd4b_1919a4b9986__7ff5_00000006.tmp
-rw-r--r--.  1 dataverse dataverse        13 Aug 28 18:48 upload_26e7dd4b_1919a4b9986__7ff5_00000007.tmp
-rw-r--r--.  1 dataverse dataverse        16 Aug 28 18:48 upload_26e7dd4b_1919a4b9986__7ff5_00000011.tmp
-rw-r--r--.  1 dataverse dataverse        13 Aug 28 18:48 upload_26e7dd4b_1919a4b9986__7ff5_00000012.tmp
-rw-r--r--.  1 dataverse dataverse        24 Aug 28 18:48 upload_26e7dd4b_1919a4b9986__7ff5_00000013.tmp
-rw-r--r--.  1 dataverse dataverse         4 Aug 28 18:48 upload_26e7dd4b_1919a4b9986__7ff5_00000014.tmp
-rw-r--r--.  1 dataverse dataverse         2 Aug 28 18:48 upload_26e7dd4b_1919a4b9986__7ff5_00000017.tmp
-rw-r--r--.  1 dataverse dataverse        16 Aug 28 18:48 upload_26e7dd4b_1919a4b9986__7ff5_00000028.tmp
-rw-r--r--.  1 dataverse dataverse        10 Aug 28 18:48 upload_26e7dd4b_1919a4b9986__7ff5_00000029.tmp
-rw-r--r--.  1 dataverse dataverse         5 Aug 28 18:48 upload_26e7dd4b_1919a4b9986__7ff5_00000030.tmp
-rw-r--r--.  1 dataverse dataverse         5 Aug 28 18:48 upload_26e7dd4b_1919a4b9986__7ff5_00000031.tmp
-rw-r--r--.  1 dataverse dataverse         4 Aug 28 18:48 upload_26e7dd4b_1919a4b9986__7ff5_00000034.tmp
-rw-r--r--.  1 dataverse dataverse         2 Aug 28 18:48 upload_26e7dd4b_1919a4b9986__7ff5_00000035.tmp
-rw-r--r--.  1 dataverse dataverse         1 Aug 28 18:48 upload_26e7dd4b_1919a4b9986__7ff5_00000037.tmp
-rw-r--r--.  1 dataverse dataverse        40 Aug 28 18:48 upload_26e7dd4b_1919a4b9986__7ff5_00000039.tmp
-rw-r--r--.  1 dataverse dataverse         4 Aug 28 18:48 upload_26e7dd4b_1919a4b9986__7ff5_00000040.tmp
-rw-r--r--.  1 dataverse dataverse        45 Aug 28 18:48 upload_26e7dd4b_1919a4b9986__7ff5_00000041.tmp
-rw-r--r--.  1 dataverse dataverse        22 Aug 28 18:48 upload_26e7dd4b_1919a4b9986__7ff5_00000042.tmp
-rw-r--r--.  1 dataverse dataverse        22 Aug 28 18:48 upload_26e7dd4b_1919a4b9986__7ff5_00000043.tmp
-rw-r--r--.  1 dataverse dataverse     99783 Aug 28 18:48 upload_26e7dd4b_1919a4b9986__7ff5_00000044.tmp
```

This will remove these files at 10 days' staleness by default.

**Comment by bikramj** [comment]
Thanks @donsizemore @landreev, unfortunately `/tmp` solution doesn't work for us because we have fairly small `root` disks. So far cleanup every hour is working well but it still gets issues sometimes when there is 250GB of data uploaded in an hour.

**Comment by donsizemore** [comment]
@landreev one data point which may be helpful: UNC Dataverse is running v5.13 and we're not (yet) seeing buildup in the uploads folder. However, dataverse-staging.rdmc.unc.edu ran v5.14 for a while, and I do see these .tmp files back on Payara 5 (potentially the problem was introduced in v5.14):
```
[ec2-user@ip-172-31-69-136 ~]$ ls -al /usr/local/payara5.2022.3/glassfish/domains/domain1/uploads/
-rw-r--r--.  1 payara payara    11 Jul 18 19:13 upload_661a8972_190c7419882__7ff7_00000000.tmp
-rw-r--r--.  1 payara payara     5 Jul 18 19:13 upload_661a8972_190c7419882__7ff7_00000003.tmp
-rw-r--r--.  1 payara payara    40 Jul 18 19:13 upload_661a8972_190c7419882__7ff7_00000005.tmp
-rw-r--r--.  1 payara payara     4 Jul 18 19:13 upload_661a8972_190c7419882__7ff7_00000006.tmp
-rw-r--r--.  1 payara payara    45 Jul 18 19:13 upload_661a8972_190c7419882__7ff7_00000007.tmp
-rw-r--r--.  1 payara payara    22 Jul 18 19:13 upload_661a8972_190c7419882__7ff7_00000008.tmp
-rw-r--r--.  1 payara payara    47 Jul 18 19:13 upload_661a8972_190c7419882__7ff7_00000009.tmp
-rw-r--r--.  1 payara payara 99783 Jul 18 19:13 upload_661a8972_190c7419882__7ff7_00000010.tmp
```

**Comment by landreev** [comment]
It really looks like adding an explicit `uFile.delete()` call to the upload handler method on the page (https://github.com/IQSS/dataverse/commit/79273b0c37985849231b6db0f7fdce20645ceeb4) fixes it for the actual uploaded files. 
The tiny files with jsf debugging messages (?) are still left there, but those are unlikely to cause any practical issues, just an annoyance. 
I'll see if I can push it into 6.4.
