### ISSUE TITLE
Shellspec jobs fail for CentOS 7

### ISSUE THREAD

**Issue by bencomp** [IQSS/dataverse#10681]
**What steps does it take to reproduce the issue?**

* When does this issue occur?
When recent commits are built, that trigger the Shellspec workflow, the CentOS 7 job fails.

* Which page(s) does it occurs on?
n/a

* What happens?
E.g., in <https://github.com/IQSS/dataverse/actions/runs/9864329507/job/27239023962>, the job fails because some dependencies are missing for the build system.

* To whom does it occur (all users, curators, superusers)?
Developers

* What did you expect to happen?
The job should pass.

**Which version of Dataverse are you using?**
These are recent builds. >= 6.3

**Any related open or closed issues to this bug report?**
In #9829 I found a different problem with the build system, but this is unrelated – except in the way that I feel CentOS 7 may have become unsupported.

**Screenshots:**
n/a, see the linked action run.

**Comment by donsizemore** [comment]
CentOS7 is now EOL and many mirrors have disabled or removed their content. If the shellspec job requires installing any software packaged for CentOS7 I would expect it to fail. Time to bump to Rocky9/Deb12/Ubuntu24.

**Comment by poikilotherm** [comment]
I removed CentOS 7 in ec6a252a3256afdd6d77261ab391a2aa3a140e7e as part of #9176, but am happy to take that out! Seeing that you started #10682 which is great!
