### ISSUE TITLE
404 Page Not Found - Not Catching URLs with File Names

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1069]
In attempting to find the 404 page locally, I tried to access it by entering a bad URL that I made up.

http://localhost:8080/blah.xhtml

This resulted in a default HTTP Status 500 - Internal Server Error, and not our custom 404.

But when I remove the file extension, it worked.

http://localhost:8080/blah

**Comment by eaquigley** [comment]
Tested this with blah.xhtml on dataverse.harvard.edu and am getting the 404 page not found. Passing to QA to try again and close.

**Comment by kcondon** [comment]
OK, get nice error page, closing
