### ISSUE TITLE
SWORD: More granular permission checks

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#1070]
In DVN 3.x we required "admin" privileges for any SWORD operation.

In Dataverse 4.0 we are working toward making good use of the new flexible permission system that has checks for permissions such as "AddDataset" and "Publish".

The SWORD "Service Document" looks for the "AddDataset" permission as of https://github.com/IQSS/dataverse/issues/784#issuecomment-60139604 but other operations still look for an equivalent of "admin".

**Comment by shlake** [comment]
UVa is seeing this problem with connection to COS/OSF. See my update and story in the Dataverse Users Community Google Group: https://github.com/IQSS/dataverse/issues/1070

**Comment by pdurbin** [comment]
@shlake thanks, yes we see your post at https://groups.google.com/d/msg/dataverse-community/G9TMVnhab5A/lUfuGwsmBgAJ . It's very cool to see UVa listed as the second production site at https://github.com/CenterForOpenScience/osf.io/pull/5344 !

A developer needs to look at all the places that call hasAccessToModifyDataverse from https://github.com/IQSS/dataverse/blob/v4.3/src/main/java/edu/harvard/iq/dataverse/api/datadeposit/SwordAuth.java

Integration tests here should be updated: https://github.com/IQSS/dataverse/blob/v4.3/src/test/java/edu/harvard/iq/dataverse/api/SwordIT.java

I **think** this is a "E2: Medium-One to two days" but perhaps I should hedge and say "E3: Large-Within a week" to use the terminology at https://groups.google.com/d/msg/dataverse-community/eq5aWkLbZ24/E7d7VqwoIwAJ . Basically, we should SWORD in line with what the GUI and native API allow.

**Comment by pdurbin** [comment]
I'm having a nice chat with at @CenterForOpenScience folks about this issue at https://github.com/CenterForOpenScience/osf.io/pull/5344

**Comment by pdurbin** [comment]
My hope is to turn my attention to this issue after I've gotten #1012 to the point where it can be demo'ed to stakeholders.

**Comment by pdurbin** [comment]
I just opened pull request #3137 as a fix for this issue. Passing to QA.

**Comment by kcondon** [comment]
Leaving in QA but removing my name until I receive pull request.

**Comment by kcondon** [comment]
Tested, works with admin, curator, contrib roles and explicit groups. Closing.
