### ISSUE TITLE
API endpoint method not supported for Signed URL

### ISSUE THREAD

**Issue by nana-boateng** [IQSS/dataverse#10704]
I am attempting to use a signed URL to make changes to a file. Prior to signed URLS, we used /api/v1/edit/{fileID} with an xml payload in a POST request to make changes, but the same route doesn't seem work for signed URLs. I get this error back:

`{
    "status": "ERROR",
    "code": 405,
    "message": "API endpoint does not support this method. Consult our API guide at http://guides.dataverse.org.",
    "requestUrl": "https://demo.borealisdata.ca/api/v1/edit/40226?until=2024-07-19T21:22:41.852&user=n.boateng&method=POST&token=9050a37554152c4b8ed46b734698ce51a39a200280f32b9cd92194588bcd03ef826cddf30366fc5a23e59699b0ced2d694941441684da0456373f7a74608d319",
    "requestMethod": "POST"
}`

Here is an example of the data object returned in the initial signed request: 
```{
    "queryParameters": {
        "fileId": 40226,
        "fileMetadataId": 39564,
        "datasetPid": "doi:10.80240/FK2/KLPDSV"
    },
    "signedUrls": [
        {
            "name": "retrieveDataFile",
            "httpMethod": "GET",
            "signedUrl": "https://demo.borealisdata.ca/api/v1/access/datafile/40226/metadata/ddi?until=2024-07-19T21:22:41.851&user=n.boateng&method=GET&token=random32423423token",
            "timeOut": 270
        },
        {
            "name": "uploadDataFile",
            "httpMethod": "POST",
            "signedUrl": "https://demo.borealisdata.ca/api/v1/edit/40226?until=2024-07-19T21:22:41.852&user=n.boateng&method=POST&token=random32423423token",
            "timeOut": 270
        }
    ]
}
```

And I am using the second signed URL to upload changes.

Here is my manifest file:

```
{
  "displayName": "DataExplorer",
  "description": "Odesi Data Explorer for viewing, configuring and editing variables",
  "toolName": "explorer",
  "scope": "file",
  "type": "configure",
  "contentType": "text/tab-separated-values",
  "toolUrl": "https://demo.borealisdata.ca/data-explorer-test/",
  "toolParameters": {
    "queryParameters": [
      {
        "fileId": "{fileId}"
      },
      {
        "fileMetadataId": "{fileMetadataId}"
      },
      {
        "datasetPid": "{datasetPid}"
      },
      {
        "dvLocale": "{localeCode}"
      }
    ]
  },
  "allowedApiCalls": [
    {
      "name": "retrieveDataFile",
      "httpMethod": "GET",
      "urlTemplate": "/api/v1/access/datafile/{fileId}/metadata/ddi",
      "timeOut": 270
    },
    {
      "name": "uploadDataFile",
      "httpMethod": "POST",
      "urlTemplate": "/api/v1/edit/{fileId}",
      "timeOut": 270
    }
  ]
}
```

**What steps does it take to reproduce the issue?**
Apologies for the verbosity, but because this is related to signed URLs, I couldn't figure out an easy link to send.

- Sign into demo.borealisdata.ca and navigate to https://demo.borealisdata.ca/dataset.xhtml?persistentId=doi:10.80240/FK2/KLPDSV&version=DRAFT
- Scroll down to the tab file, click the three dots and open the file in Data Explorer
- In the Data Explorer page, open Inspect Element and click the "Save To Borealis" button

* When does this issue occur?
When you attempt to use the signed URL to edit changes in a dataset.

* Which page(s) does it occurs on?
API call.

* What happens?
   I get a message: "API endpoint does not support this method. Consult our API guide at http://guides.dataverse.org."

* To whom does it occur (all users, curators, superusers)?
 Curators

* What did you expect to happen?
The upload to complete or maybe a new API endpoint

**Which version of Dataverse are you using?**

v6.2.8-SP

**Any related open or closed issues to this bug report?**

**Comment by pdurbin** [comment]
> "requestUrl": "https://demo.borealisdata.ca/api/v1/edit

Wow, /api/edit doesn't feel right (I would expect an additional word like "file" or "metadata" or "fileMetadata" to be in the path) but it's true. It was added in #5971 and the docs do say just "/api/edit": https://guides.dataverse.org/en/6.3/api/native-api.html#editing-variable-level-metadata

Anyway, thanks for the bug report @nana-boateng. I'm not sure why it isn't working. On a related note, this week during a pyDataverse meeting we talked about how we'd like to support signed URLs:

- https://github.com/gdcc/pyDataverse/issues/200

**Comment by nana-boateng** [comment]
Looks like the httpMethod is PUT and not POST, as written in this comment https://github.com/gdcc/pyDataverse/issues/200#issuecomment-2240267624 

Thanks for the quick reply and help @pdurbin!

**Comment by nana-boateng** [comment]
Nothing else, feel free to close it. :)

**Comment by pdurbin** [comment]
Ok, closing. FYI, as the person who opened an issue, you should also have the power to close it. 😄 

Thanks for flying Dataverse! ✈️
