### ISSUE TITLE
cannot build due to missing artifact org.primefaces.themes:all-themes:jar:1.0.10

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#10718]
Originally reported by @haarli [in Zulip](https://dataverse.zulipchat.com/#narrow/stream/379673-dev/topic/Build.20fails.20due.20to.20missing.20dependency.20org.2Eprimefaces.2Ethemes.3A/near/453680152), I'm also seeing problems building the Dataverse war file (`mvn package`) if I delete my Maven cache (`~/.m2`):

`[INFO] ------------------------------------------------------------------------`
`[INFO] BUILD FAILURE`
`[INFO] ------------------------------------------------------------------------`
`[INFO] Total time:  02:07 min`
`[INFO] Finished at: 2024-07-24T13:08:32Z`
`[INFO] ------------------------------------------------------------------------`
`[ERROR] Failed to execute goal on project dataverse: Could not resolve dependencies for project edu.harvard.iq:dataverse:war:6.3: The following artifacts could not be resolved: org.primefaces.themes:all-themes:jar:1.0.10 (absent): Could not find artifact org.primefaces.themes:all-themes:jar:1.0.10 in payara-nexus-artifacts (https://nexus.payara.fish/repository/payara-artifacts) -> [Help 1]`

I'm on the tip of the develop branch (d33e249a78).

**Comment by haarli** [comment]
The Primefaces people put the missing depencies on Maven Central Repository, so the Dataverse build is working again.
See https://github.com/orgs/primefaces/discussions/2382

Ticket can be closed

**Comment by pdurbin** [comment]
@haarli yes, thanks, I'll close this.

I also independently verified that we can build with those Primefaces artifacts in this (no-op) PR:

- #10724
