### ISSUE TITLE
Feature Request/Idea: Allow ORCID and ROR to be used together in author field

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#10711]
**Overview of the Feature Request**
Using External vocabulary scripts in the citation author field has several slight differences from other examples we've had before:
* While ORCID nominally can have affiliation info, it sounds like the freedom to select affiliation manually is desired, which means the ORCID script needs to manage the name and idType fields while adding the ORCID to the identifier field, and the ROR script has to handle the affiliation field
* Since the name field exists, it makes more sense for the ORCID script to put plain text values there rather than in the identifier field (as our one-field demos have done) - this means that the identifier field is not included in the display by Dataverse (since it has no value) and hence there's no field for the ORCID script to find
* the idType is an internal cvv field which uses a select element rather than an input
* The identifier field is the last of 4 fields, but we want the person name to appear before the affiliation
* When no ORICD exists for a person, we want to show the idType/identifier fields so others can be entered.
* ORCID and ROR have logos which can be included, but need to be styled

Much of this can be handled by changes to the scripts themselves (See [#22](https://github.com/gdcc/dataverse-external-vocab-support/pull/22)), but some aspects require Dataverse changes:
* Dataverse needs to show a child as a managed field if one is configured but only if the term-uri field has a value
* Managed internal CVV fields need to be marked with the data-cvoc-managedfield attribute
* Styling for drop-down lists needs to apply to ORCID/ROR inputs and display of ORCID/ROR images needs to be styled.

**What kind of user is the feature intended for?**
(Example users roles: API User, Curator, Depositor, Guest, Superuser, Sysadmin)

**What inspired the request?**
Work at QDR to deploy ORCID and ROR

**What existing behavior do you want changed?**

**Any brand new behavior do you want to add to Dataverse?**

**Any open or closed issues related to this feature request?**

**Comment by jggautier** [comment]
Just a heads up that as it's redesigning the Author field and other fields that describe people and organizations, the UX WG is working on many of these points you raised @qqmyers. I don't fully understand some of the points, but it looks like the desired outcomes of them are very similar.

**Comment by qqmyers** [comment]
~yes. This particular issue and #10712 are generic improvements to the external vocabulary mechanism to address cases where we might want two scripts managing different child fields (as with author/affiliation). It does not make changes to the author field or subfields. 

That said, [external vocab #22](https://github.com/gdcc/dataverse-external-vocab-support/pull/22) includes updated ROR and ORCID scripts that take advantage of the improvements to allow ORCID/ROR use in the author field as shown in one of the [new README.md](https://github.com/gdcc/dataverse-external-vocab-support/blob/aae79e4cc9db273fdae64d893570a1dfbb6b97ac/README.md) examples.  I think that's consistent with the UX discussion.

Somewhat independent of that, #10632 is also capable of detecting ORCIDs and RORs in the author field, and RORs in the grantNumberAgency field (regardless of whether they are typed in or the external vocab scripts are used) and sends the identifiers to DataCite.

All of that is nominally prioritized to get into v6.4, so hopefully it can become a new baseline context for what to prioritize next in pursuing PID support and further author/affiliation changes.

**Comment by jggautier** [comment]
Thanks @qqmyers! What you wrote in the README.md is really helpful for clarifying what the associated PR at https://github.com/IQSS/dataverse/pull/10712 will do. We'll check it out as we're working on the redesign of the Citation block's author field and other fields.
