### ISSUE TITLE
Upgrade from Ubuntu 22 to 24 breaks container images

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#10722]
As @poikilotherm mentioned in last week's container meeting ([recording](https://harvard.zoom.us/rec/share/6YV8RWVgXNtANjLIpnGnL9tKN4AeMWbBjy_A6zzJu0dUgM48pOtYN8WU_J0mRSIl.9-ja80A1IHfF8cUW)), the `eclipse-temurin:17-jre` image we build on has switched from Ubuntu 22 to 24. See https://github.com/adoptium/containers/commit/d762761bff59ad4ee3bacf89050e2081e5464c65 via https://github.com/adoptium/containers/issues/606#issuecomment-2244787657

Unfortunately, this broke a few things. For example, the `addgroup` command is missing. See https://github.com/IQSS/dataverse/actions/runs/10078623902/job/27869639991?pr=10721 and https://dataverse.zulipchat.com/#narrow/stream/375812-containers/topic/.5BINFO.5D.20DOCKER.3E.20ERROR.3A.20failed.20to.20solve/near/453771298

For now, I think we should revert to Ubuntu 22. Then we can worry about upgrading the Ubuntu 24 and rewriting scripts that use `addgroup` etc. at our leisure.

**Comment by poikilotherm** [comment]
There is a PR ready for merging that solves all of this: #10672

I'll go ahead and flag this as solving this issue.

**Comment by pdurbin** [comment]
@poikilotherm hmm, meanwhile, in this PR I'm reverting to Ubuntu 22 (and removing the JAVA_IMAGE env var, which I couldn't get to work):

- #10721

Can you please take a look? Thank you!
