### ISSUE TITLE
Search API: File dataset_name and dataset_citation refer to different versions

### ISSUE THREAD

**Issue by ekraffmiller** [IQSS/dataverse#10735]
**What steps does it take to reproduce the issue?**

1. Create a dataset with a file
2. Publish the dataset
3. Edit the title of the dataset
4. use the search API to get the file, for example, http://localhost:8000/api/v1/search?q=*&type=file&sort=date&order=desc&per_page=10&start=0&subtree=root
5. The title in the dataset_name field doesn't match the title in the dataset_citation (see screenshot)

* When does this issue occur?
When dataset metadata is edited, but not file metadata

* Which page(s) does it occurs on?
N/A

* What happens?

* To whom does it occur (all users, curators, superusers)?
All

* What did you expect to happen?
The dataset_citation field should be for the released version of the file, not the draft version

**Which version of Dataverse are you using?**
6.2

**Any related open or closed issues to this bug report?**

**Screenshots:**

<img width="1067" alt="Screenshot 2024-07-31 at 1 28 41 PM" src="https://github.com/user-attachments/assets/cc8e088e-490f-4c9c-bbda-fef5e919b45a">

**Comment by stevenwinship** [comment]
Just to be clear. Is this a true bug? Per the Search API Documentation these values are not guarantied to be the same:

![image](https://github.com/user-attachments/assets/3bf5abf8-0b96-4838-87f0-a16f92eddb78)

**Comment by qqmyers** [comment]
Looks like a bug that got copied to the documentation to me. We shouldn't be leaking draft info to someone who can't see the draft version.
