### ISSUE TITLE
is 6.3's schema.xml missing workflowCodeRepository?

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#10745]
My grad student helped/watched me upgrade a test server to v6.3 on Monday, and now Payara warns
`Search Syntax Error: Error from server at http://localhost:8983/solr/collection1: undefined field workflowCodeRepository`

Indeed, I don't see `workflowCodeRepository` in https://github.com/IQSS/dataverse/blob/develop/conf/solr/schema.xml though it is in the TSV: https://github.com/IQSS/dataverse/blob/ac32b00ee1f2431807a01ae997a4d5ddc9a96761/scripts/api/data/metadatablocks/computational_workflow.tsv#L5

I see it in schema.xml on demo.dataverse.org, but not in the schema.xml distributed in the v6.3 dvinstall.zip. A `diff` of schema.xml from the 6.3 dvinstall.zip and from the develop branch shows no output/difference.

**Comment by qqmyers** [comment]
@donsizemore - the computational workflow block is optional, so when upgrading, you have to follow the instructions for when you have custom blocks installed. That includes running the update script that will make sure all the fields from non-standard blocks are added to the schema. If that's not clear, maybe we need additional documentation?

**Comment by pdurbin** [comment]
@donsizemore good catch. I just updated https://github.com/IQSS/dataverse/releases/tag/v6.3 to break up step 7 into two steps and tried to make it clear that the computational block is optional. Please take a look.
