### ISSUE TITLE
Extend the dataset version payload to include the latest published version number

### ISSUE THREAD

**Issue by GPortas** [IQSS/dataverse#10761]
**Overview of the Feature Request**

Extend the dataset version payload to include the latest published version number.

**What kind of user is the feature intended for?**

API User

**What inspired the request?**

SPA needs

**What existing behavior do you want changed?**

Change the dataset version payload

**Any brand new behavior do you want to add to Dataverse?**

None

**Any open or closed issues related to this feature request?**

- https://github.com/IQSS/dataverse-frontend/issues/428

**Are you thinking about creating a pull request for this feature?**  

Yes

**Comment by qqmyers** [comment]
@GPortas - what is it you need here? Steven is adding the id of the latest published version in the PR, but if you want to know the major/minor version numbers, you'd still have to go get the JSON for that version (which is available already by asking for the [:latest-published version in the API.](https://guides.dataverse.org/en/latest/api/native-api.html#dataset-version-specifiers). 

Were you looking to get the version major/minor of the latest published version back in the json for the draft version to avoid a round trip? Or?

**Comment by GPortas** [comment]
> @GPortas - what is it you need here? Steven is adding the id of the latest published version in the PR, but if you want to know the major/minor version numbers, you'd still have to go get the JSON for that version (which is available already by asking for the [:latest-published version in the API.](https://guides.dataverse.org/en/latest/api/native-api.html#dataset-version-specifiers).
> 
> Were you looking to get the version major/minor of the latest published version back in the json for the draft version to avoid a round trip? Or?

@qqmyers The goal is to have the minor and major numbers available to display the version increments corresponding to each update in the publish popup (minor or major).

<img width="1067" alt="Screenshot 2024-08-19 at 09 56 20" src="https://github.com/user-attachments/assets/01363e81-d0d2-4f99-ae7e-9c1f63e713e7">

I agree, as you mention, that this information can already be obtained by making an extra call to the dataset version with :latest-published. 

I suggest adding a waiting tag to this issue/PR until we clarify with @ekraffmiller if there's any particular reason to include the shortcut instead of making the extra call. I remember creating this issue after a frontend standup conversation.

@ekraffmiller Not including the shortcut would imply making an extra call to the getDataset use case for :latest-published. The major and minor numbers are included in the dataset model in js-dv.

**Comment by stevenwinship** [comment]
@GPortas Does this satisfy the requirement?
"latestVersion": {
    "id": 3,
        "datasetId": 5,
        "datasetPersistentId": "doi:10.5072/FK2/J50XYQ",
        "storageIdentifier": "local://10.5072/FK2/J50XYQ",
        "versionState": "DRAFT",
        "latestVersionPublishingState": "DRAFT",
        "lastUpdateTime": "2024-08-16T20:33:02Z",
        "createTime": "2024-08-16T20:33:02Z",
        "publicationDate": "2024-08-16",
        "citationDate": "2024-08-16",
        "latestPublishedVersion": {
            "id": 2,
            "versionNumber": 1,
            "versionMinorNumber": 0
        },

**Comment by ekraffmiller** [comment]
@GPortas I agree that making a second call to get the :latest-published version of the dataset would provide this information.  I hadn't been thinking of that, because until now, all the dataset data needed for the Dataset Page is retrieved in one API call.  But I think it makes sense to make this second call to keep the API simpler.  
So, in that case we don't need to make this change.  
Thanks everyone for the feedback!

**Comment by GPortas** [comment]
Can we close the issue then? The associated PR would no longer be necessary. I apologize for the time spent on this. We will take these cases more into account before creating API extension issues. Thank you. @stevenwinship @qqmyers
