### ISSUE TITLE
Guides: "Add data" in "About" menu selection not resolving

### ISSUE THREAD

**Issue by DieuwertjeBloemen** [IQSS/dataverse#10770]
**What steps does it take to reproduce the issue?**
Go to the guides, and hover over 'about' and click "add data"
* When does this issue occur?
In the guides for all users when you hover over 'about' and click "add data"

* Which page(s) does it occurs on?
https://dataverse.org/add-data

* What happens?
There is no content

* To whom does it occur (all users, curators, superusers)?
all users

* What did you expect to happen?
For that page to not be there, or to lead to the relevant user guide anchor/page

**Which version of Dataverse are you using?**
6.3

**Any related open or closed issues to this bug report?**
/

**Are you thinking about creating a pull request for this issue?**
Help is always welcome, is this bug something you or your organization plan to fix?

**Comment by pdurbin** [comment]
@DieuwertjeBloemen good catch!

I vote we simply remove it. Here's how (look for the minus sign), if anyone would like to make a pull request:

```
% git diff
diff --git a/doc/sphinx-guides/source/_templates/navbar.html b/doc/sphinx-guides/source/_templates/navbar.html
index c7b81dcb93..d88306be8a 100644
--- a/doc/sphinx-guides/source/_templates/navbar.html
+++ b/doc/sphinx-guides/source/_templates/navbar.html
@@ -25,7 +25,6 @@
                     <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">About <span class="caret"></span></a>
                     <ul class="dropdown-menu">
                         <li><a target="_blank" href="https://dataverse.org/about">About the Project</a></li>
-                        <li><a target="_blank" href="https://dataverse.org/add-data">Add Data</a></li>
                         <li><a target="_blank" href="https://dataverse.org/blog">Blog</a></li>
                         <li><a target="_blank" href="https://dataverse.org/presentations">Presentations</a></li>
                         <li><a target="_blank" href="https://dataverse.org/publications">Publications</a></li>
```
