### ISSUE TITLE
Thumbnail setting inconsistent between loading from Datafile and Uploading from file

### ISSUE THREAD

**Issue by stevenwinship** [IQSS/dataverse#10821]
**What steps does it take to reproduce the issue?** 
1. Create a Dataset
2. Publish
3. Add datafile (image)
4. Collection page should show both dataset versions with the Datafile Image as thumbnail
5. Select Draft version 
6. Edit Dataset -> Thumbnail -> Remove image -> Save changes
7. Collection page should show both dataset versions with the Default Image as thumbnail
8. Select Draft Version
9. Edit Dataset -> Thumbnail -> Upload Image -> Save changes
10. Collection page still shows default image for both versions (should show new thumbnail for both version)
11. Select published version, Dataset page still shows default image (should show new thumbnail)
12. Select Draft version, Dataset page shows correct image

If the image is selected via the Select Thumbnail button instead of Upload button all images show correctly.

* When does this issue occur? Every time

* Which page(s) does it occurs on? Collection / Dataset

* What happens? Thumbnails not showing correctly

* To whom does it occur (all users, curators, superusers)? All

* What did you expect to happen? Should match functionality of selecting thumbnail image from Datafile. See above

**Which version of Dataverse are you using?** 6.3

**Any related open or closed issues to this bug report?**

**Screenshots:**
Thumbnails selected by Upload Image button from Draft version
![image](https://github.com/user-attachments/assets/fe79a4e8-c4c8-466f-b129-3496effbabb5)

![image](https://github.com/user-attachments/assets/a375ef81-b62a-4128-a17c-7a8cb74c0fdd)

![image](https://github.com/user-attachments/assets/3b154ed3-4cf1-434a-9c93-a226d0e7d89d)

Thumbnails selected by Select Thumbnail button from Draft version
![image](https://github.com/user-attachments/assets/1dbe076e-7935-4ed9-8a0a-7aa31f3ed2aa)

**Comment by landreev** [comment]
@stevenwinship 
Yeah, I can reproduce the behavior. It appears that removing a DataFile-based thumbnail and selecting the default icon is the key. If you skip this step: 
 `6. Edit Dataset -> Thumbnail -> Remove image -> Save changes`
and proceed to upload an image, then it works properly.
In other words, it looks like uploading the thumbnail image does not unset  `dataset.usegenericthumbnail`. To make matters worse, this combination of `dataset.usegenericthumbnail == true` and the presence of the uploaded logo image is interpreted differently by the dataset and dataverse pages, and/or for published and draft versions on the dataset page.

**Comment by landreev** [comment]
@stevenwinship 
I believe that the important thing is to test the behavior of the thumbnail image upload API. If it's similarly broken/inconsistent there, we should fix it, because that's what we'll be using in the long term. My guess is that it IS similarly broken in the API, because both places appear to be using the same UpdateDatasetThumbnailCommand. But we need to confirm. 
This may also be as simple as adding a missing 
```dataset.setUseGenericThumbnail(false);```
 line to the method ```DatasetServiceBean.setNonDatasetFileAsThumbnail()```.

**Comment by landreev** [comment]
@stevenwinship 
It really looks like that one missing line fixes it. See the draft PR tagged. 

I know I shouldn't be spending any time on this, but can't help myself.

**Comment by stevenwinship** [comment]
@landreev I approved the draft PR. I tested it as well and the issue goes away. Nice fix

**Comment by landreev** [comment]
I'll mention it during standup or on slack and explain how it materialized on the board bypassing the formal process. I have downgraded it to "size: 3" also.
