### ISSUE TITLE
Dataverse Theme: Intermittent issue uploading image 

### ISSUE THREAD

**Issue by esotiri** [IQSS/dataverse#1085]
There seem to be an intermittent issue when uploading an image.  Sometimes can't upload the image and other times works just fine.  

see https://github.com/IQSS/dataverse/issues/117

**Comment by esotiri** [comment]
I have updated the google doc, verifying the commands of the API guide: https://drive.google.com/drive/u/0/#folders/0B3_V6vFxEcx-RS1OMGg3YUpCVDQ/0By40CG63udC_T2pZTFBIeURtZGc/0By40CG63udC_cGo2ZGNFTFgtcms

**Comment by scolapasta** [comment]
Can QA try to reproduce? This is an older ticket and we don't seem to be able to.

**Comment by kcondon** [comment]
Uploaded several times, cancelled, removed, etc. All worked. Closing
