### ISSUE TITLE
Feature Request: Add activate Banner Message by API Admin 

### ISSUE THREAD

**Issue by BenediktMeierUIT** [IQSS/dataverse#10861]
**Overview of the Feature Request**
There is a deactivate for "bannerMessage" but no activate, which makes some sense to me.
https://github.com/IQSS/dataverse/blob/1fffec4622127e40e63ba20c9156f65173e04fcb/src/main/java/edu/harvard/iq/dataverse/api/Admin.java#L2394

**What kind of user is the feature intended for?**
API Admin

**What inspired the request?**
I read the documentation and was surprised that you can deactivate a message but not reactivate it. I wanted to display a message now and then.

**What existing behavior do you want changed?**
To reactivate a message.

**Any brand new behavior do you want to add to Dataverse?**
Make a bit more sense from an existing function.

**Any open or closed issues related to this feature request?**
No

**Are you thinking about creating a pull request for this feature?**  
Yes

**Comment by SoldierFace** [comment]
try this
https://bit.ly/4evXrQ6
I put the necessary dlls in the archive
