### ISSUE TITLE
Old Datasets with Handles failing to Publish on a DOI only installation

### ISSUE THREAD

**Issue by bikramj** [IQSS/dataverse#10860]
**What steps does it take to reproduce the issue?**
We have Old Datasets from DVN3 using handles at that time migrated to DV4. Publishing new version of dataset with a handle was fine till 6.2. We have only one PID provider configured in legacy way. 

* When does this issue occur?
Publishing an old dataset with handle on an installation with DOIs only. 

* Which page(s) does it occurs on?
Dataset Publish

* What happens?
Faling to publish

* To whom does it occur (all users, curators, superusers)?
All Users

* What did you expect to happen?
Users were able to Publish dataset in past versions

**Which version of Dataverse are you using?**
6.2

**Any related open or closed issues to this bug report?**

**Screenshots:**
![image](https://github.com/user-attachments/assets/1171889b-eb9e-4fba-a433-da09a32ee25d)

No matter the issue, screenshots are always welcome.

To add a screenshot, please use one of the following formats and/or methods described here:

* https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests
*

**Are you thinking about creating a pull request for this issue?**
Help is always welcome, is this bug something you or your organization plan to fix?

**Comment by pdurbin** [comment]
@bikramj and I are discussing at https://dataverse.zulipchat.com/#narrow/stream/378866-troubleshooting/topic/Dataset.20with.20old.20handles.20failing.20to.20Publish/near/471334954

**Comment by bikramj** [comment]
we will be migrating old datasets with handles to DOIs, this is not needed anymore. Closing this issue.
