### ISSUE TITLE
Dataset UI - Terms Tab - Restricted Files section is displayed even when there is no data present

### ISSUE THREAD

**Issue by ofahimIQSS** [IQSS/dataverse#10879]
**What steps does it take to reproduce the issue?**
Steps: 
1. Go to the dataverse site (https://dataverse-internal.iq.harvard.edu/)
2. Login using valid credentials | if you are not registered, please create an account
3. Create a New Dataset
5. Under Description, enter test
6. Subject: Pick any subject 
7. Save the data set. 
8. Navigate to the Terms Tab and look under "Restricted Files+Terms of Access"

* When does this issue occur? 
* Right after publishing a new Dataset

* Which page(s) does it occurs on?
Dataset page on Terms Tab - example of issue can be found here: https://dataverse-internal.iq.harvard.edu/dataset.xhtml?persistentId=doi%3A10.70122%2FFK2%2FEDABWF&version=DRAFT 

* What happens?
"Restricted Files+Terms of Access" is displayed even when there isn't any data present. 

* What did you expect to happen?
Spoke to Julian about this - Julian confirmed that when none of the fields are filled, we don't expect the section to appear at all.

**Which version of Dataverse are you using?**
Dataverse Prod and Internal 

**Any related open or closed issues to this bug report?**
N/A

**Screenshots:**
![image](https://github.com/user-attachments/assets/a8212485-6e92-4118-8f1e-b04b9b827ecb)

**Comment by ofahimIQSS** [comment]
Reproduced in production today 
![image](https://github.com/user-attachments/assets/3fabcff0-1234-42a9-bcb9-1f7a117912df)

Reproduced in Demo 6.4 Release Candidate
![image](https://github.com/user-attachments/assets/f20a61c1-aa95-4799-be23-682b6f1dc1a3)

**Comment by sekmiller** [comment]
I'm not seeing in on Demo which has the 6.4 release candidate, I think

**Comment by pdurbin** [comment]
I can reproduce it on demo (yes, it's running a 6.4 release candidate).

I created the dataset in the root collection but I doubt that matters.

Here's a screenshot:

![Screenshot 2024-09-27 at 4 25 57 PM](https://github.com/user-attachments/assets/df2dddaa-d598-4254-b7ae-236800896924)

The bug is in JSF, which we're throwing away 🗑️  in favor of [React](https://github.com/IQSS/dataverse-frontend) so I'm not sure if this is worth fixing. /me ducks

**Comment by sekmiller** [comment]
My working theory is that this is due to the "Request Access to Restricted Files" being true by default. The reason I wasn't seeing it in my prior datasets was because I was using a template on create where "Request Access...." was false.

**Comment by sekmiller** [comment]
Mentioned this in standup on Monday - the fix was simple enough that there's no need for further discussion. (My original thought was that it could be complex or require changing a default dataset setting. fortunately that is not the case)
