### ISSUE TITLE
Update the conditions to display image_url in Solr search results for file type

### ISSUE THREAD

**Issue by GPortas** [IQSS/dataverse#10875]
**Overview of the Feature Request**

We need to update the added conditions  in https://github.com/IQSS/dataverse/pull/10855 to determine whether to return image_url or not for a file type result. JSF displays images for a file type result even when it is not published, which does not happen with the newly added logic. We also need to review the other conditions (restricted, harvested...) and understand how it currently works in JSF to return or not return image_url for a file type result.

**What kind of user is the feature intended for?**
API User

**What inspired the request?**

- https://github.com/IQSS/dataverse/pull/10855

**What existing behavior do you want changed?**

image_url display condition for file search result included in https://github.com/IQSS/dataverse/pull/10855

**Any brand new behavior do you want to add to Dataverse?**

None

**Any open or closed issues related to this feature request?**

- https://github.com/IQSS/dataverse/pull/10855

**Are you thinking about creating a pull request for this feature?**  
Yes

**Comment by stevenwinship** [comment]
@GPortas 
Here are a list of the current conditions for returning the image_url:

1. thumbnail is available
2. datafile is not harvested
3. datafile is not restricted
4. datafile is not released
5. datafile is not embargoed
6. datafile retention is not expired

Please comment if the following should be added/removed:
1. return the image url even if it was not published
2. one check that was removed and should be added back is user "hasDownloadFilePermission"
3. size limitations. We used to scale the image down when returning the base64 image. Now we return the url so the caller is responsible for scaling the image. Should we not return the url if the image is too large?

**Comment by GPortas** [comment]
Hi @stevenwinship !

Answering your first list:

**3) datafile is not restricted**

If a datafile is restricted but you have the right permissions, the image is displayed in the search result card, so this condition is not sufficient on its own.

For example, I created a file from the admin user and restricted it. Logged in as the admin user, the file card appears like this:

<img width="858" alt="Screenshot 2024-09-27 at 16 14 55" src="https://github.com/user-attachments/assets/6a05a022-b637-43c6-a2be-5f55dd3448b0">

Therefore, if we do not return the image_url in restricted files in all cases, we would not be able to display this card.

When I log in as a new user (without permissions to access the file), the card appears like this, so I believe the image should not be returned in this case:

<img width="858" alt="Screenshot 2024-09-27 at 16 14 41" src="https://github.com/user-attachments/assets/5b83c31f-ae28-4b53-a7a5-f6a7baa4d7e8">

**4) datafile is not embargoed**

Currently in JSF, if a file is embargoed, all users, including the Guest user (unauthenticated), can view the thumbnail in the file card. Therefore, if we keep this condition, we would not be able to replicate the current behavior on the SPA. A separate issue is whether we want to change this behavior for embargoed files, but it would be a change in the SPA compared to JSF that we would need to discuss. Possibly @qqmyers, who I think has experience with the Embargo feature, can provide more information on this.

**2) and 6)**

Right now, I’m not clear whether the file would be visible in these cases or not, or under which conditions. So far, I haven't found a way to test these scenarios in my local environment. Perhaps someone on the team with more context on these features can clarify this point for us directly; otherwise, we need to replicate these scenarios or analyze the JSF code to confirm this point.

Answering your second list:

**1) return the image url even if it was not published**

Should be added. This is necessary to display the image when the file is part of a DRAFT version, as we can see below.

<img width="873" alt="draftcards" src="https://github.com/user-attachments/assets/6d70f031-cfbf-4323-821c-2c6b3fb6d1b7">

**2) one check that was removed and should be added back is user "hasDownloadFilePermission"**

It makes sense to include it, especially if this check was already there and was removed.

**3) size limitations. We used to scale the image down when returning the base64 image. Now we return the url so the caller is responsible for scaling the image. Should we not return the url if the image is too large?**

If I’m not mistaken, we are using the query parameter imageThumb in the image_url property for files, right? (`/api/access/datafile/{identifier}?imageThumb=true`) Then it should return a thumbnail and not the original image. Maybe I’m missing something.

**Comment by qqmyers** [comment]
re: 4) - I think files that are embargoed or have a retention period should follow the access rules for restricted when the embargo is active or the retention period has expired. Without digging, I'm not sure if showing the thumb when embargoed was just missed originally or changed with some later fix. In any case, I'd consider the current JSF behavior to be inconsistent with the design.

**Comment by stevenwinship** [comment]
@qqmyers @GPortas Do either of you know if there is a document where this is clearly stated? Perhaps within a table? If not, is there a document where I can add such a table so it is clearly defined?

**Comment by stevenwinship** [comment]
I added the conditions to the release note in the PR
