### ISSUE TITLE
Edit Dataverse Collection Native API endpoint

### ISSUE THREAD

**Issue by g-saracca** [IQSS/dataverse#10904]
**Overview of the Feature Request**

We need an **_Edit Dataverse Collection_** Native API endpoint.
For the Edit Collection page in the SPA, we need to create first a  use case in js-dataverse for editing a collection and for that we need an API endpoint for editing a collection.
We have already implement a use case in js-dataverse for creating a collection which uses this [Create Dataverse Collection Native API endpoint](https://guides.dataverse.org/en/latest/api/native-api.html#create-a-dataverse-collection)

**What kind of user is the feature intended for?**
API User

**What inspired the request?**
Q4 Roadmap

**What existing behavior do you want changed?**
None

**Any brand new behavior do you want to add to Dataverse?**
None

**Any open or closed issues related to this feature request?**
https://github.com/IQSS/dataverse-client-javascript/issues/200

**Comment by pdurbin** [comment]
FYI there is an endpoint for editing a collection description and a few other fields: https://guides.dataverse.org/en/6.4/api/native-api.html#change-collection-attributes

And there are various other APIs for changing this or that for collections, but it's all very ad hoc! 😅

**Comment by g-saracca** [comment]
Yes, that is exactly what @GPortas told me and he is going to take a more in-depth look at it.
It could be nice to have a single api endpoint to send the same but updated data as we do with the Create Collection/Dataverse endpoint but of course it is not up to me.
Thanks @pdurbin
