### ISSUE TITLE
SKOSMOS is named in Metadata Customization documentation page as SKOMOS (without the second S)

### ISSUE THREAD

**Issue by pkiraly** [IQSS/dataverse#10920]
**What steps does it take to reproduce the issue?**

* When does this issue occur?
When the site admin reads the Metadata Customization page of the user guide

* Which page(s) does it occurs on?
For the users at the Metadata Customization page of the user guide (https://guides.dataverse.org/en/latest/admin/metadatacustomization.html). There is a comment in source code and a ticket which also have this typo.

* What happens?
Instead of SKOSMOS it is written as SKOMOS (without the second S)

* To whom does it occur (all users, curators, superusers)?
Site admins and those who works on metadata customization.

* What did you expect to happen?
It is names as SKOSMOS.

**Which version of Dataverse are you using?**
It appears in versions from 5.7 to the current one.

**Any related open or closed issues to this bug report?**
No

**Screenshots:**
![image](https://github.com/user-attachments/assets/1aa6dc4e-752a-401a-bd2d-7fc9d2d9dde4)

No matter the issue, screenshots are always welcome.

To add a screenshot, please use one of the following formats and/or methods described here:

* https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests
*

**Are you thinking about creating a pull request for this issue?**
Help is always welcome, is this bug something you or your organization plan to fix?

Yes

**Comment by pkiraly** [comment]
@pdurbin Could you please place this PR to the project board?

**Comment by pdurbin** [comment]
@pkiraly sure, I put the PR in our new "ready for triage" column:

- #10921

Thanks!
