### ISSUE TITLE
Release 6.5: Prepare release branch

### ISSUE THREAD

**Issue by cmbz** [IQSS/dataverse#10954]
## Overview
- Release 6.5: Prepare release branch
  - [Prepare Release Branch](https://dataverse-guide--10932.org.readthedocs.build/en/10932/developers/making-releases.html#prepare-release-branch)
  - [Merge “develop” into “master”](https://dataverse-guide--10932.org.readthedocs.build/en/10932/developers/making-releases.html#merge-develop-into-master)
  - [Add Milestone to Pull Requests and Issues](https://dataverse-guide--10932.org.readthedocs.build/en/10932/developers/making-releases.html#add-milestone-to-pull-requests-and-issues)
  - [(Optional) Test Docker Images](https://dataverse-guide--10932.org.readthedocs.build/en/10932/developers/making-releases.html#optional-test-docker-images)
  - [Build the Guides for the Release](https://dataverse-guide--10932.org.readthedocs.build/en/10932/developers/making-releases.html#build-the-guides-for-the-release)
  - [Create a Draft Release on GitHub](https://dataverse-guide--10932.org.readthedocs.build/en/10932/developers/making-releases.html#create-a-draft-release-on-github)
  - [Run a Build to Create the War File](https://dataverse-guide--10932.org.readthedocs.build/en/10932/developers/making-releases.html#run-a-build-to-create-the-war-file)
  - [Build Installer (dvinstall.zip)](https://dataverse-guide--10932.org.readthedocs.build/en/10932/developers/making-releases.html#build-installer-dvinstall-zip)
  - [Make Artifacts Available for Download](https://dataverse-guide--10932.org.readthedocs.build/en/10932/developers/making-releases.html#make-artifacts-available-for-download)
  - [Publish the Release](https://dataverse-guide--10932.org.readthedocs.build/en/10932/developers/making-releases.html#publish-the-release)
  - [Update Guides Link](https://dataverse-guide--10932.org.readthedocs.build/en/10932/developers/making-releases.html#update-guides-link)
  - [Close Milestone on GitHub and Create a New One](https://dataverse-guide--10932.org.readthedocs.build/en/10932/developers/making-releases.html#close-milestone-on-github-and-create-a-new-one)
  - [Update the Container Base Image Version Property](https://dataverse-guide--10932.org.readthedocs.build/en/10932/developers/making-releases.html#update-the-container-base-image-version-property)

## Related
See completion order here:
- https://github.com/IQSS/dataverse-pm/issues/335

**Comment by pdurbin** [comment]
@cmbz just some feedback for you that in practice I'm not looking at the steps in the description above. I'm following https://preview.guides.gdcc.io/en/develop/developers/making-releases.html which is more real, if that makes sense. It's a checklist with very specific steps.

**Comment by cmbz** [comment]
@pdurbin I was pretty certain that we copied the list above from the https://preview.guides.gdcc.io/en/develop/developers/making-releases.html document, remember? Did it change?

**Comment by pdurbin** [comment]
It looks like we copied from https://dataverse-guide--10932.org.readthedocs.build/en/10932/developers/making-releases.html#prepare-release-branch for example.

I'm not sure if more changes were made before merging.

Also, we made another PR later:

- #11029

I'm just saying it's a moving target. I would prefer the description to say to go to https://preview.guides.gdcc.io/en/develop/container/dev-usage.html and do steps 7 through 23 or whatever. 😅

**Comment by cmbz** [comment]
Works for me! I'll make sure it does for 6.6.

**Comment by cmbz** [comment]
@pdurbin we should close the issue, yes?

**Comment by pdurbin** [comment]
Well, merging this issue will close it automatically:

- #11091

But up to you.

See also Leonid's comment at https://iqss.slack.com/archives/C03R1E7T4KA/p1733957819653069?thread_ts=1733948198.674539&cid=C03R1E7T4KA

**Comment by cmbz** [comment]
@pdurbin My bad! I completely missed the linked pull request.
