### ISSUE TITLE
Authentication 

### ISSUE THREAD

**Issue by esotiri** [IQSS/dataverse#1096]
Steps to reproduce:
At signup page leave empty some of required fields > click create account > displays warnings > click login 
URL bar displays: https://dvn-build.hmdc.harvard.edu/dataverseuser.xhtml?dataverseUserForm:accountInfoView:save=dataverseUserForm%3AaccountInfoView%3Asave&javax.faces.partial.render=%40all&javax.faces.partial.execute=%40all&javax.faces.source=dataverseUserForm%3AaccountInfoView%3Asave&dataverseUserForm=dataverseUserForm&dataverseUserForm:accountInfoView_activeIndex=0&dataverseUserForm:accountInfoView:inputPassword=sfd&javax.faces.partial.ajax=true&javax.faces.ViewState=2489439450101436637%3A-6366046617944000495

![screen shot 2014-11-05 at 12 33 16 pm](https://cloud.githubusercontent.com/assets/1107614/4943801/fac6cd8c-65f7-11e4-89ca-e8a442c3e566.png)

**Comment by scolapasta** [comment]
This was fixed a while ago.
