### ISSUE TITLE
API Tokens: Getting an API Token Through the UI

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1098]
We need a way for a user to generate an API Token/Key in the UI. 

Examples:
-GitHub:
![githubtoken](https://cloud.githubusercontent.com/assets/5922904/4954682/c2255bd2-668e-11e4-8a50-01d1300181a3.png)

-Redmine:
![redminetoken](https://cloud.githubusercontent.com/assets/5922904/4954714/0999b378-668f-11e4-8b38-7a57bde4acf5.png)

**Comment by raprasad** [comment]
Note:  

1.  Click "Generate API Token": token created
1.  Click "Generate API Token" a **second** time: 
   - Error appears ```API token could not be generated.```
   - Previous API token remains visible
    - Not sure it matters: I logged in via Shib when doing this

![api_token_-_root_dataverse](https://cloud.githubusercontent.com/assets/1036060/6515472/f7d31a00-c357-11e4-956e-6da72f125c8e.png)

**Comment by mheppler** [comment]
Also, this page needs a "Done" button, which will return the user back to the Account Information tab of the dataverseuser page.

**Comment by pdurbin** [comment]
Sadly, the behavior @raprasad describes is expected at this time. It's all I had time to develop months ago.

Also, please don't forget that there is a functional requirements doc we can all edit: https://docs.google.com/document/d/1PfQtblJxPv975U_cTOIA7OR71MT4CslP-s2n83eb1i8/edit?usp=sharing

**Comment by pdurbin** [comment]
@scolapasta should the priority be bumped up on this? Please see https://help.hmdc.harvard.edu/Ticket/Display.html?id=216470

**Comment by scolapasta** [comment]
Logic to regenerate was added in #2296.

**Comment by pdurbin** [comment]
Some future issue can help us address our dreams for API tokens: https://docs.google.com/document/d/1PfQtblJxPv975U_cTOIA7OR71MT4CslP-s2n83eb1i8/edit?usp=sharing
