### ISSUE TITLE
stop using v3 of download-artifact and upload-artifact

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#10993]
From https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

"Starting November 30, 2024, GitHub Actions customers will no longer be able to use v3 of [actions/upload-artifact](https://github.com/actions/upload-artifact) or [actions/download-artifact](https://github.com/actions/download-artifact). Customers should update workflows to begin using [v4 of the artifact actions](https://github.blog/2024-02-12-get-started-with-v4-of-github-actions-artifacts/) as soon as possible. While v4 of the artifact actions improves upload and download speeds by up to 98% and includes several new features, there are [key differences](https://github.com/actions/upload-artifact?tab=readme-ov-file#breaking-changes) from previous versions that may require updates to your workflows. Please see [the documentation](https://github.com/actions/upload-artifact/blob/main/docs/MIGRATION.md) in the project repositories for guidance on how to migrate your workflows."

We tried to upgrade in this PR but saw failures:

- #10822

We should try again, soon. And we should compare notes with the frontend:

- https://github.com/IQSS/dataverse-frontend/issues/537

**Comment by cmbz** [comment]
2024/10/31: Due to urgency of issue, confusing documentation, and unknown size, I'm moving this into this sprint immediately.

**Comment by qqmyers** [comment]
from Github: 
![image](https://github.com/user-attachments/assets/031aa6d3-6b54-4735-9082-052e9813c44d)
