### ISSUE TITLE
Quirk in overview display when using external controlled variables

### ISSUE THREAD

**Issue by bjosel** [IQSS/dataverse#11005]
**What steps does it take to reproduce the issue?**
Add some JS-script and configure ":CVocConf" in order to select entries from external vocabularies or id-providers

* When does this issue occur?
When looking at the metadata in the metadata tab 

* Which page(s) does it occurs on?
On the dataset overview page

* What happens?
Some entries that have been filled via selecting from external sources are shown repeatedly. 

* To whom does it occur (all users, curators, superusers)?
Happens to all users

* What did you expect to happen?
The entries should be displayed only once

**Which version of Dataverse are you using?**
6.4

**Screenshots:**
Author names and project title are shown repeatedly
![ohnePatch_alteOrcid_mitFooter](https://github.com/user-attachments/assets/4e343fe9-fc39-4659-b855-d9a23a32c105)

If we apply a small patch author names and project title are displayed correctly
![mitPatch_altesOrcid_mitFooter](https://github.com/user-attachments/assets/c99dee06-ff8e-4092-a92f-9727b317609b)

**Are you thinking about creating a pull request for this issue?**
Yes, we can create a PR. Our patch would be the following:

![Screenshot from 2024-11-07 15-58-42](https://github.com/user-attachments/assets/39354fa9-5563-4ef7-88b3-35043fba3b13)

This effectively changes the logic of the decision if data is rendered from NOT(ITEM1 AND  ITEM2) to NOT(ITEM1 OR ITEM2). All test so far didn't expose any side effects of the patch

**Comment by qqmyers** [comment]
Thanks for the report and possible fix. FWIW: I think our most recent testing has been done using [authorsOrcidAndRor.json](https://github.com/gdcc/dataverse-external-vocab-support/blob/main/examples/config/authorsOrcidAndRor.json), which works as can be seen for [doi:10.70122/FK2/NEQHTE](https://demo.dataverse.org/dataset.xhtml?persistentId=doi:10.70122/FK2/NEQHTE). Can you make sure your fix works for that case as well?

**Comment by bjosel** [comment]
Yes, we tested with the latest [authorsOrcidAndRor.json](https://github.com/gdcc/dataverse-external-vocab-support/blob/main/examples/config/authorsOrcidAndRor.json), too. It works with our patch, see the screenshot
![mitPatch_neuesOrcid_mitFooter](https://github.com/user-attachments/assets/b76683f4-edeb-410d-88e6-49dd2d1a7a3a)

**Comment by ffritze** [comment]
A pull-request has been created: https://github.com/IQSS/dataverse/pull/11034
