### ISSUE TITLE
Videos are sometimes too large for previewer

### ISSUE THREAD

**Issue by jo-pol** [IQSS/dataverse#11014]
* **What steps does it take to reproduce the issue?**

  * download sample_1280x720.mp4 from https://toolsfairy.com/video-test/sample-mp4-files# 
  * upload the file to a dataset
  * save the changed dataset

* When does this issue occur?

the dimensions of the video are larger than the dimensions of the iframe

* Which page(s) does it occurs on?

The file page, for example https://demo.dataverse.org/file.xhtml?persistentId=doi:10.70122/FK2/OHJOFX/FUH65T&version=1.0&toolType=PREVIEW

* What happens?

The play button is not in the center of the video (FireFox), you need to scroll to see the controls and the right/bottom side of the video.

* To whom does it occur (all users, curators, superusers)?

all users

* What did you expect to happen?

See the full video with controls in a slightly smaller resolution

**Which version of Dataverse are you using?**

v. 6.4 build v6.4+10926+10958+10865+10919

**Any related open or closed issues to this bug report?**

**Screenshots:**

![image](https://github.com/user-attachments/assets/35f23800-61e1-4c69-b57d-d5e4fe4e3a0b)

**Are you thinking about creating a pull request for this issue?**

Yes.

**Comment by qqmyers** [comment]
FWIW: The fix is available now in [the betatest folder of the previewers repo](https://github.com/gdcc/dataverse-previewers/tree/develop/previewers/betatest) and will become part of the next release (v1.5 presumably, date tbd).
