### ISSUE TITLE
Extend datasets' and files' property from search API endpoint

### ISSUE THREAD

**Issue by ChengShi-1** [IQSS/dataverse#11027]
**Overview of the Feature Request**
For the SPA, in order to display the lock icon, and tags/categories information for items in the collection page, we should add some extra properties to each file item from search api once `type=file`. 
- `restricted: boolean`
- `canDownloadFile: boolean` ( from file user permission)
- `categories: array of string` "categories" would be similar to what it is in metadata api, for example, `{"label":"blob","description":"","restricted":true,"categories":["Data","Documentation"],"id":6}`

For tabular files, there are some properties needed additionally.
- `tabularTags: array of string` for example,`{"tabularTags" : ["Event", "Genomics", "Geospatial"]}`
- `variables: number/int` shows how many variables we have for the tabular file
- `observations: number/int` shows how many observations for the tabular file
 
Also, for dataset search api `type=dataset`, because datasets' thumbnail should be displayed, an extra property is needed.
- `thumbnail: string`

**What kind of user is the feature intended for?**
(Example users roles: API User, Curator, Depositor, Guest, Superuser, Sysadmin)
API User

**What inspired the request?**
Q4 roadmap, Q4.2 

**What existing behavior do you want changed?**
None

**Any brand new behavior do you want to add to Dataverse?**
Add extra properties

**Any open or closed issues related to this feature request?**
https://github.com/IQSS/dataverse-client-javascript/issues/221
https://github.com/IQSS/dataverse-frontend/issues/547

**Comment by stevenwinship** [comment]
Bumping the size to 30 since this requires solar schema changes
