### ISSUE TITLE
In User Guide Appendix, most links to Google Sheets that show metadata block TSVs are broken

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#11028]
In [the User Guide's Appendix](https://guides.dataverse.org/en/6.4/user/appendix.html), most links to Google Sheets that show metadata block TSVs are broken.

The links behind all of the names of the metadata blocks listed in [the Supported Metadata section](https://guides.dataverse.org/en/6.4/user/appendix.html#supported-metadata) and behind "Computational Workflow Metadata" in [the Experimental Metadata section](https://guides.dataverse.org/en/6.4/user/appendix.html#experimental-metadata) lead to a Page Not Found page, which reads that the file's been deleted.

<kbd><img width="389" alt="Screenshot 2024-11-18 at 1 08 37 PM" src="https://github.com/user-attachments/assets/4f763f6d-339d-40c2-bd4a-a2cadf91e38a"></kbd>

I checked my Google Drive's trash folder in case I accidentally deleted it, but my folder's empty. I also asked the Dataverse core team if anyone knew how this happened but no one knew.

I think at the least the broken links should be removed, or someone should re-create the Google Sheet, which had tabs for each of the metadata blocks that ship with Dataverse, put that Google Sheet in [Dataverse's shared Google Drive](https://drive.google.com/drive/u/0/folders/0ABsTQ1OH63GGUk9PVA), and replace the broken links in the Appendix page with links to the tabs of the new Google Sheet.

**Comment by jggautier** [comment]
@cmbz, could this issue be considered for v6.5? I could make the changes to the User Guides. I'd give this a size of .5

Also, I wrote that I'd open a new GitHub issue about learning how people need to use the TSV files, so that we're sure that we're making them available in the best ways. But I'm not going to do this after all.

**Comment by jggautier** [comment]
Hey @DS-INRAE. I'm not aware of is using anything like that. I think it might be helpful to ask again next week when others are back from the holiday week.

**Comment by pdurbin** [comment]
@DS-INRAE brought it up here as well: https://dataverse.zulipchat.com/#narrow/channel/446770-docs/topic/Checking.20docs.20links/near/484871995
