### ISSUE TITLE
API: Create mechanism to shut off API access selectively and globally.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1103]
APIs may expose the service to sharp load spikes due to batch/ programmatic nature. Also, potential malicious use.

So, it would be good to have a way to turn off API access entirely or selectively, based on UI, or trusted user/hosts.

**Comment by kcondon** [comment]
@scolapasta This wasn't designed or implemented, right?

**Comment by kcondon** [comment]
Passing back as a feature request.

**Comment by djbrooke** [comment]
Closing as a duplicate of #1339, which has some good discussion.
