### ISSUE TITLE
Warning messages in the server log due to missing properties

### ISSUE THREAD

**Issue by JayanthyChengan** [IQSS/dataverse#11030]
Here are a few WARNING messages in the server.log due to missing properties in the BUNDLE file.

notification.typeDescription.GLOBUSUPLOADCOMPLETED
notification.typeDescription.GLOBUSUPLOADCOMPLETEDWITHERRORS
notification.typeDescription.GLOBUSDOWNLOADCOMPLETED
notification.typeDescription.GLOBUSDOWNLOADCOMPLETEDWITHERRORS
notification.typeDescription.GLOBUSUPLOADLOCALFAILURE
notification.typeDescription.GLOBUSUPLOADREMOTEFAILURE
notification.typeDescription.REQUESTEDFILEACCESS

`[2024-11-13T11:24:05.757-0500] [Payara 6.2024.10] [WARNING] [] [edu.harvard.iq.dataverse.util.BundleUtil] [tid: _ThreadID=132 _ThreadName=http-thread-pool::jk-connector(2)] [timeMillis: 1731515045757] [levelValue: 900] [[
  Could not find key "notification.typeDescription.REQUESTEDFILEACCESS" in bundle file: ]]

[2024-11-13T11:24:05.758-0500] [Payara 6.2024.10] [WARNING] [] [edu.harvard.iq.dataverse.util.BundleUtil] [tid: _ThreadID=132 _ThreadName=http-thread-pool::jk-connector(2)] [timeMillis: 1731515045758] [levelValue: 900] [[
  Could not find key "notification.typeDescription.GLOBUSUPLOADREMOTEFAILURE" in bundle file: ]]

[2024-11-13T11:24:05.758-0500] [Payara 6.2024.10] [WARNING] [] [edu.harvard.iq.dataverse.util.BundleUtil] [tid: _ThreadID=132 _ThreadName=http-thread-pool::jk-connector(2)] [timeMillis: 1731515045758] [levelValue: 900] [[
  Could not find key "notification.typeDescription.GLOBUSUPLOADLOCALFAILURE" in bundle file: ]]`

**Which version of Dataverse are you using?**
v6.4

**Comment by landreev** [comment]
Thank you for the report! As @qqmyers suggested, I have added these missing entries to the bundle in the PR #11040, that is scheduled to be included in 6.5.
