### ISSUE TITLE
Incorrect info re: anonymous URLs

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#11046]
**What steps does it take to reproduce the issue?**
https://github.com/IQSS/dataverse/blob/b8e47582d3308bf3886e1a2592f97bbb44bc9dcd/src/main/java/propertyFiles/Bundle.properties#L1737

implies restricted files are not accessible, which is not true AFIAK (it wasn't prior to #10961, I don't see changes there to download, and I can still download restricted files from an anonymized url after merging develop into QDR's fork). I suggest just deleting " if they're not restricted" but if the intent was to not allow download of restricted files with an anonymized URL - I suspect there are places that will not want that so we might need a feature flag.

Also - minor: https://github.com/IQSS/dataverse/blob/f95c1a0366d38119e6e235fccce1d91af936b84d/src/main/java/propertyFiles/Bundle.properties#L1742 and https://github.com/IQSS/dataverse/blob/f95c1a0366d38119e6e235fccce1d91af936b84d/src/main/java/propertyFiles/Bundle.properties#L1745 don't appear to be used anymore.

* When does this issue occur?

* Which page(s) does it occurs on?

* What happens?

* To whom does it occur (all users, curators, superusers)?

* What did you expect to happen?

**Which version of Dataverse are you using?**
develop

**Any related open or closed issues to this bug report?**

**Screenshots:**

No matter the issue, screenshots are always welcome.

To add a screenshot, please use one of the following formats and/or methods described here:

* https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests
*

**Are you thinking about creating a pull request for this issue?**
Help is always welcome, is this bug something you or your organization plan to fix?

Guessing this is size 0.5 if it is just the text change, maybe 10 if a change to downloads was intended.

**Comment by jggautier** [comment]
I agree, someone who gets the anonymous preview url will be able to download files, even if those files are restricted. We didn't mean to change this behavior and that text is wrong. I remember you bringing this up when I was working on this while ago, too, and I think it was just lost :(

Removing that part of the text sounds good, or editing it to start with "The datasets files are not changed and users of the Anonymous Preview URL will be able to access them. ..."

**Comment by qqmyers** [comment]
OK - cool - I'll make a quick PR.
