### ISSUE TITLE
Dataverse Theme: File Upload Dimensions Limit + Resize

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1106]
Currently, you can upload an image of any size, and the CSS resizes it to fit in the header. We need to imit file size allowable for upload + resize images to our preferred dimensions.

Current CSS dimensional limits for the logo in the header:

Rectangles: max-width:900px; max-height:120px;
Squares: max-width:100px; max-height:100px;

The max width of the header is 1140px, which is set in the Bootstrap theme, so that is a starting point for a limit. 1080p HD screens imply a resolution of 1920x1080 (http://en.wikipedia.org/wiki/1080p), 1920px is the largest we should need to go for any images. (http://alistapart.com/article/responsive-images-in-practice)

**Comment by scolapasta** [comment]
will review with @mheppler to better understand what the issue here is.

**Comment by mheppler** [comment]
Added file size limit for logo upload in the Theme + Wdiget popup. Added help text to bundle. Moved CSS to stylesheet.

File size limit on upload: 500 kb
Logo max-width limit on display: 940px
Logo max-height limit on display: 120px

**Comment by sbarbosadataverse** [comment]
screen shot attached confirming: 

Added file size limit for logo upload in the Theme + Wdiget popup. Added help text to bundle. Moved CSS to stylesheet.

File size limit on upload: 500 kb
Logo max-width limit on display: 940px
Logo max-height limit on display: 120px


https://www.dropbox.com/s/j1ss5wwvt518hqu/Screenshot%202015-03-18%2016.00.19.png?dl=0
