### ISSUE TITLE
Feature Request: Extend Search API to include counts for file, dataset, collection

### ISSUE THREAD

**Issue by ekraffmiller** [IQSS/dataverse#11065]
**Overview of the Feature Request**
For the SPA Collection Page, we need to show counts of the files, datasets, and collections (dataverses) in the results.  To support this,  we need to add a section to the API response, to contain the counts.
If preferred, we can make this behavior optional by adding a boolean `show_type_counts` parameter.
For example:
```
total_count_per_object_type: {
  collection: 3,
  dataset: 10,
  file: 75
}

```
**What kind of user is the feature intended for?**
(Example users roles: API User, Curator, Depositor, Guest, Superuser, Sysadmin)

**What inspired the request?**

**What existing behavior do you want changed?**

**Any brand new behavior do you want to add to Dataverse?**

**Any open or closed issues related to this feature request?**

**Are you thinking about creating a pull request for this feature?**  
Help is always welcome, is this feature something you or your organization plan to implement?

**Comment by stevenwinship** [comment]
@ekraffmiller Just to clarify, when you say " in the results", you are referring to the number of items returned for the page and not the total of all items found?
