### ISSUE TITLE
Metrics Box Shows Inconsistent Numbers When Refreshing

### ISSUE THREAD

**Issue by ofahimIQSS** [IQSS/dataverse#11078]
**Summary**
The Metrics box on the test server (beehive.dataverse.org) displays inconsistent numbers for the download count when refreshing the page multiple times.

**Steps to Reproduce**

1. Navigate to [beehive.dataverse.org](https://beehive.dataverse.org/).
2. Observe the Metrics box at the top of the page.
3. Refresh the page multiple times.
4. Note the fluctuating download count value.

**Expected Behavior**
The download count should consistently display 104 downloads.

**Actual Behavior**
The Metrics box alternates between 54 downloads and 104 downloads upon refreshing.

Environment
Server: Test Server (beehive.dataverse.org)
Browser: Chrome and Safari
Build: Develop branch v. 6.4 build 1672-82dad99

**Possible Impact**
Users may receive incorrect metrics data, leading to confusion or misinterpretation of download statistics.

Video Can be found below of the issue: 

https://github.com/user-attachments/assets/02bc9dce-810c-4bc9-a227-706a6556b562

**Comment by pdurbin** [comment]
Just to chime in, I was able to reproduce this on https://beehive.dataverse.org as well. Keep clicking and it cycles between showing 104 and 52 downloads.

I'm not sure if the bug is in JSF or somewhere in the backend. We should watch our for it when we add this to the frontend.

**Comment by ofahimIQSS** [comment]
I tested this again today and I am unable to reproduce the issue.
