### ISSUE TITLE
Disable URL Not Working After Accessing Preview URL

### ISSUE THREAD

**Issue by ofahimIQSS** [IQSS/dataverse#11076]
Issue Summary: The "Disable URL" feature for the Preview URL does not work when the same user accesses the generated Preview URL in a different browser tab.

Steps to Reproduce:

URL: https://beehive.dataverse.org/
Username: dataverseadmin

1. Log in to the Dataverse instance:
2. Create an Unpublished Dataset and save it.
3. Edit the dataset and navigate to Preview URL.
4. Click on Create General Preview URL.
5. Copy the generated Preview URL and paste/load it in a different browser tab.
6. Return to the Preview URL screen and click Disable URL.
7. Expected Behavior: The Preview URL should be disabled and become inaccessible immediately.

Actual Behavior: The "Disable URL" feature does not work after the Preview URL is accessed in another browser tab.

Impact: This issue allows continued access to the Preview URL even after it is supposed to be disabled, potentially leading to unintended exposure of dataset content.

Environment Details:

Build: Development branch, v. 6.4 build 1672-82dad99 

Server.log file can be found here: 
[server.log --- preview URL.txt](https://github.com/user-attachments/files/18066329/server.log.---.preview.URL.txt)

**Comment by sekmiller** [comment]
what is happening here is that the use of the Preview URL in another browser window is invalidating the login on the original page. On the original page the user is effectively logged out, but the page isn't refreshed. Clicking on anything that causes an error to be thrown to the log stating "this.workingVersion is null". There might be a way to handle this cleanly and notify the user, but I'm not sure it's worth it. You can see a similar effect if you have two browser windows open and log out in one of the and then go over to the one where you think you're still logged in on, but you've effectively been logged out there.

**Comment by pdurbin** [comment]
> On the original page the user is effectively logged out

Right, we were tracking that here:

- #6576

It was closed in the recent [sweep](https://groups.google.com/g/dataverse-community/c/lDVJq-1CHLY/m/Vl824d8fAQAJ) of old issues.

It would be nice to get this right when we add Preview URLs to the SPA.

**Comment by sekmiller** [comment]
@pdurbin as I noted above, a similar thing happens if I have two browser windows open and I log myself out of one of them - I am effectively logged out of both. Is there an issue for that also?

**Comment by pdurbin** [comment]
Hmm, not that I'm aware of. But if you log out of one tab I think it's the correct behavior to be logged out of the other tab. Of course, this is all JSF territory so we should see what happens in the React SPA.
