### ISSUE TITLE
Timeout for signed URLs do not exceed 5 minutes

### ISSUE THREAD

**Issue by nana-boateng** [IQSS/dataverse#11098]
**What steps does it take to reproduce the issue?**
    1. Clone the repo.
    2. Run the docker start command.
    3. Register an external tool with a timeout greater than 270.
    4. Create dataset within locally run dataverse instance.
    5. Access dataset with registered external tool.
    6. In the network response, the returned signed URL contains "until" which will always be 5 minutes from when you open the dataset.

* When does this issue occur?
When you register an external tool and/or
When dataverse creates a signed URL

* Which page(s) does it occurs on?
Dataset page and/or
External Tool

* What happens?
Unexpected timeout.

* To whom does it occur (all users, curators, superusers)?
All users

* What did you expect to happen?
The timeout should match (in seconds) the timeout specified in the manifest file used to register the external tool.

**Which version of Dataverse are you using?**
Version 6.4

**Any related open or closed issues to this bug report?**
No

**Are you thinking about creating a pull request for this issue?**
Help is always welcome, is this bug something you or your organization plan to fix?
No

**Comment by qqmyers** [comment]
In the current design, the initial signed URL that is returned is always limited to 5 minutes. However, if you make that call, you should get a list of all the signed URLs you configured with the appropriate timeouts. The limit on the initial returned URL was purposely kept short since it is exposed in the URL (in base64 encoded form) whereas the URLs you configure for later callbacks are not. And the assumption was that a remote tool could at least retrieve that initial URL quickly.

If there's a use case where an external tool cannot respond and retrieve the initial URL within 5 minutes, we could potentially make that longer/configurable as well.

**Comment by nana-boateng** [comment]
For the Data Explorer external tool, we have a cross-tabulation calculator that could take up to 15 minutes for larger (specifically census) datasets. So I'd ask if we can reconsider the limit

**Comment by qqmyers** [comment]
Is there a reason you can't read the initial URL and get the long-lived signed URLs to store until your calculation is done?

**Comment by qqmyers** [comment]
Just to make sure we're talking about the same things: At QDR (on a firewalled test machine), I have the video previewer set to have timeouts of 600 and 3600. The initial URL I get is like:
https://dv.dev-aws.qdr.org/api/v1/files/6575/metadata/11625/toolparams/5?until=2024-12-16T20:20:37.751&user=qqmyers&method=GET&token=a11955c06cb7968d81b90ebc20a26e9f49e1707995c491389344ad119b6fc004f6bc2686c535547355ce277442b5b6cae926d5ab0c0d6f664d10b334e7ee1d73

with a 5 minute timeout, but if I read that, I get JSON with the URLs with the long timeouts as configured. The video previewer has to get these URLs up front but can then use them over the next hours/days.

{
"status": "OK",
"data": {
"queryParameters": {
"fileid": 6575,
"siteUrl": "https://dv.dev-aws.qdr.org/",
"datasetid": 6572,
"datasetversion": ":draft"
},
"signedUrls": [
{
"name": "retrieveFileContents",
"httpMethod": "GET",
"signedUrl": "https://dv.dev-aws.qdr.org/api/v1/access/datafile/6575?gbrecs=true&until=2024-12-17T06:16:06.033&user=qqmyers&method=GET&token=f8d2b3d2c138f4d495f24a668869bf79091b9d160933731261e4b8916a9be7b555bc8544a0da04586d84bb0162a92713031a15176a3f625b29fe9f99af1f7bd0",
"timeOut": 600
},
{
"name": "downloadFile",
"httpMethod": "GET",
"signedUrl": "https://dv.dev-aws.qdr.org/api/v1/access/datafile/6575?gbrecs=false&until=2024-12-19T08:16:06.036&user=qqmyers&method=GET&token=36a66c233faac33840950a00b74009dc1ba8c1d86fee680eaf3aa94b4b401ae496e06fab83281940c5a5dc28e73a1aaafeac8eebfddb8ff33f314718ec2638aa",
"timeOut": 3600
},
{
"name": "getDatasetVersionMetadata",
"httpMethod": "GET",
"signedUrl": "https://dv.dev-aws.qdr.org/api/v1/datasets/6572/versions/:draft?until=2024-12-19T08:16:06.038&user=qqmyers&method=GET&token=6d58586ade3802d9e4cd2950731f617f628a63a1a9bcd08363aab9eaaff04067de93476e5aaf6e262a95a9e9473c480e9ba1c23a8c68f538ec8580429c9c6d40",
"timeOut": 3600
}
]
}
}

**Comment by nana-boateng** [comment]
Maybe I'm mistaken. 

```
{"status":"OK","data":{"id":2,"displayName":"Data Explorer","description":"Odesi Data Explorer for viewing, and configuring variables","types":["explore"],"scope":"file","toolUrl":"http://localhost:4200","toolParameters":"{\"queryParameters\":[{\"fileId\":\"{fileId}\"},{\"fileMetadataId\":\"{fileMetadataId}\"},{\"datasetPid\":\"{datasetPid}\"},{\"dvLocale\":\"{localeCode}\"}]}","contentType":"text/tab-separated-values","allowedApiCalls":"[{\"name\":\"retrieveDataFile\",\"httpMethod\":\"GET\",\"urlTemplate\":\"/api/v1/access/datafile/{fileId}\",\"timeOut\":300},{\"name\":\"retrieveDataFileDDI\",\"httpMethod\":\"GET\",\"urlTemplate\":\"/api/v1/access/datafile/{fileId}/metadata/ddi\",\"timeOut\":300}]"}}
```

On load we get the dataset with the 'retrieveDataFileDDI' signed URL, but we use 'retrieveDataFile' to check weights and change weights, as well as in the Cross Tabulation calculator. 

Unless I'm mistaken, the five minute limit means if the user only has 5 minutes to use the Cross Tab Calculator and/or only 5 minutes from when a weight has changed to change another weight value. I plan on fetching all the values for cross tabulation on load but that can take 4 minutes for our biggest dataset.

Here is an example of a problem dataset: https://borealisdata.ca/api/access/datafile/705083?format=subset&variables=v2892998,v2893118,v2893017

**Comment by qqmyers** [comment]
When you call the tool, base 64 decode the callback token in the tool url, and retrieve the initial `/api/v1/files/<id>/metadata/<mid>/toolparams/<toolid>*` , what JSON do you get?

**Comment by nana-boateng** [comment]
Yes, it does. Thank you!
