### ISSUE TITLE
Create Dataset: Required field validation is not happening on create for GSD block.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1128]
This was found by Elda.

If the GSD block is added to a dv and you create a dataset, no validation is made for required fields, only those in the Citation block. You cannot save the dataset and there is an error in the log.

Right now, only Citation and GSD have required fields.

**Comment by sekmiller** [comment]
Validation messages are showing up and dataset may be saved once all required fields are added.  Please re-test.

**Comment by kcondon** [comment]
All required fields in gsd block were intentionally made not required. Closing.
