### ISSUE TITLE
Linked Dataset - Link to an existing dataset

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#113]
---

Author Name: **Philip Durbin** (@pdurbin)
Original Redmine Issue: 3522, https://redmine.hmdc.harvard.edu/issues/3522
Original Date: 2014-02-03
Original Assignee: Michael Bar-Sinai

---

None

**Comment by mheppler** [comment]
Added an icon only button for the Linked Dataset workflow as a placeholder, in the same button group as the Email Contact button.

**Comment by sekmiller** [comment]
Linking to existing dataset has been implemented.  Minor UI clean up is in progress.

**Comment by kcondon** [comment]
Basic functionality works, ok for demo.
When tested against functional requirements, found these issues:
-Can't remove linked objects
-Can't see list of linked objects
-Contents of linked objects are not searchable and do not show up as cards in host dv, with the exception of files, so no sub ds or dvs.
-Can link a dataset and then link it's parent dv to same host dv.
-Can link unpublished dv and ds if you have permissions

**Comment by kcondon** [comment]
OK, basic functionality works and issues above were opened as separate tickets. Passing to Mike for UI cleanup unless there is already a UI ticket.

**Comment by mheppler** [comment]
Cleaned up layout and styled form elements for the Linked Dataset workflow on the datasete page.

**Comment by mheppler** [comment]
Found issues:
- [ ] Success message didn't display when I linked a dataset to a dataverse AND THEN immediately linked it a second dataverse of mine.
- [ ] Popup message for a dataset that is already linked to all of my dataverses, is the same message if I have zero dataverses.

**Comment by kcondon** [comment]
OK, still works, opened Mike's issues under new ticket: #1435 Closing.
