### ISSUE TITLE
Permissions: Can save new role with no permission selected, needs validation.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1134]
Can save new role with no permission selected, needs validation.
Actually, needs validation on page, period. There seems to be an alias length validation but it allows saving and only appears when you click on create role again, it remembers your previously unsaved role and presents the error. Other things like no name or alias not included.

**Comment by scolapasta** [comment]
Merged with #1135

**Comment by kcondon** [comment]
Closing due to consolidation
