### ISSUE TITLE
Permissions: Need to check for unique role id, can create roles with same name and alias, different perms.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1135]
Role validation needed:
Can save new role with no permission selected, needs validation.
Actually, needs validation on page, period. There seems to be an alias length validation but it allows saving and only appears when you click on create role again, it remembers your previously unsaved role and presents the error. Other things like no name or alias not included.

Need to check for unique role id, can create roles with same name and alias, different perms.

Related messaging:
- [ ] Add New Role pop up, inline errors: Please add in a role name. Please add in an identifier. Please add in a description. Please select at least one role permission.
- [ ] Add asterisks in the Assign Role pop up for Required Fields

**Comment by scolapasta** [comment]
For 4.0, we won't allow anyone to create roles, unless they are superusers. So we will defer this validation to post 4.0.

**Comment by scolapasta** [comment]
Also validate, that to not allow save new role with no permission selected per #1134.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
