### ISSUE TITLE
Documentation: Shibboleth 

### ISSUE THREAD

**Issue by esotiri** [IQSS/dataverse#1138]
Add Shibboleth to installers guide. https://github.com/IQSS/dataverse/blob/master/doc/Sphinx/source/Installers/dataverse-installer-main.rst

this is done.

**Comment by pdurbin** [comment]
I'm stealing this from @landreev because yesterday he, @scolapasta and I agreed I would document Shibboleth as an experimental feature since we had to remove it from https://dataverse.harvard.edu for reasons detailed in #2117.

I'll improving what's already at http://guides.dataverse.org/en/latest/installation and perhaps deleting https://github.com/IQSS/dataverse/blob/master/doc/shib/shib.md

**Comment by pdurbin** [comment]
@kcondon as we've discussed I've documented Shibboleth at http://guides.dataverse.org/en/latest/installation/shibboleth.html and you are welcome to test on https://shibtest.dataverse.org or any other host.

Heads up to @bencomp and @akio-sone that this new page on Shibboleth is now available. Feedback is welcome!

Passing to QA.

**Comment by bencomp** [comment]
IMO It looks great, it's very readible. Let me check that Arnoud agrees. I am unsure he would agree on changing SELinux settings, although if the official docs say it has to be done…

**Comment by eaquigley** [comment]
Documentation for Shibboleth is done. Closing this issue. If any issues arise relating to Shibboleth Documentation, a new issue should be created.

**Comment by pdurbin** [comment]
> unsure he would agree on changing SELinux settings

This week a user mentioned that disabling SELinux fixed the "Metadata Request Failed" and  "Discovery Request Failed" errors he was seeing while trying to set up Shibboleth. He encouraged me to go ahead and close the ticket he opened ( https://help.hmdc.harvard.edu/Ticket/Display.html?id=240694) but I thought I'd mention it here. This is what I wrote in that ticket:

At
http://guides.dataverse.org/en/4.5/installation/shibboleth.html#disable-selinux
we quote the official Shibboleth wiki about how it isn't possible to use
Shibboleth with SELinux:
https://wiki.shibboleth.net/confluence/display/SHIB2/NativeSPSELinux

I'd encourage you to read that wiki page to see if you or your IT
department has the same interpretation. That page suggests that they are
welcome to contributions for getting this Shibboleth working with
SELinux. I don't personally have this expertise but maybe you can find
someone who does.

It's a bummer. I wish it "just worked" but it doesn't. :(
