### ISSUE TITLE
Linked Dataverse - Link to an existing dataverse

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#114]
---

Author Name: **Philip Durbin** (@pdurbin)
Original Redmine Issue: 3523, https://redmine.hmdc.harvard.edu/issues/3523
Original Date: 2014-02-03
Original Assignee: Michael Bar-Sinai

---

None

**Comment by mheppler** [comment]
Added an icon only button for the Linked Dataverse workflow as a placeholder, in the same button group as the Email Contact button.

**Comment by sekmiller** [comment]
Link to dataverse is ready for testing - some minor ui Cleanup is needed

**Comment by kcondon** [comment]
Basic functionality works, ok for demo.
When tested against functional requirements, found these issues:
-Can't remove linked objects
-Can't see list of linked objects
-Contents of linked objects are not searchable and do not show up as cards in host dv, with the exception of files, so no sub ds or dvs.
-Can link a dataset and then link it's parent dv to same host dv.
-Can link unpublished dv and ds if you have permissions

**Comment by kcondon** [comment]
OK, basic functionality works and the above issues opened as separate tickets.

**Comment by mheppler** [comment]
Cleaned up layout and styled form elements for the Linked Dataverse workflow on the dataverse page.

**Comment by kcondon** [comment]
OK still works, closing
