### ISSUE TITLE
Dataverse URL: Pretty-fied URL Has Typo

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1142]
When I was working on the ticket #1111 to apply the "pretty" URL to the Featured Dataverse links, I noticed that the "pretty" URL that is being used on the dataverse cards, points to "/view-datataverse/{alias}". There is an extra "T-A" in there. Also, see here on dvn-build.

https://dvn-build.hmdc.harvard.edu/view-datataverse/umaTop

Since we're going to need to go ahead and correct this, I would like to take this opportunity to remove "view-" from the URL as well, since it shouldn't be needed, and "dataverse" is shorter, and sweeter.

**Comment by scolapasta** [comment]
I think this is all set, no?

**Comment by kcondon** [comment]
OK, typo and view is gone. Mike pointed out the dataverse url on the dataset card is not prettified so passing to Mike for cleanup.

**Comment by mheppler** [comment]
Found that I also have ticket #1111 that outlines other instances of where the Pretty Faces needs to be used. Sending this back to QA to close. Will keep the other ticket for further development.

**Comment by mheppler** [comment]
Fixed dataverse URLs on search-include that still referenced dataverse ID's, which don't work with the PrettyFaces URLs.

Found that this bug in the search-include (as well as the "View All Datasets and Dataverses >" link hidden under the "Preview Recently Published Datasets [+]" link) were easy fixes, so I checked those in quick.

Please forgive the dup comment above.

**Comment by kcondon** [comment]
Fixed, closing.
