### ISSUE TITLE
Dataset Card: Default File Icon Selection Logic

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1144]
Currently, the icon on the dataset card is the icon for the first file uploaded. However, to prevent the dataset cards from using the default icon all the time (like what is currently happening) @mcrosas recommended that we have default logic to look for first a shapefile image, then a FITS, then a tabular, then any image format, then PDF, if none in the dataset then there would be the dataset icon appearing in the dataset card.

**Comment by landreev** [comment]
Please retest this.

**Comment by kcondon** [comment]
OK, can now select/change which thumbnail is used after one is selected.
There is an issue where deleting the file that is the current thumbnail doesn't appear to save and throws an exception in the log. It does delete the file but it is not clear from save that it does so.

Also, the original requirements for file types thumbnail precedence needs to be implemented but I understand that is waiting for another ticket to create such icons.

**Comment by landreev** [comment]
@kcondon 
I believe the delete should be working now, without any exceptions; but the actual datafile delete seems to be broken at this point; I'll wait till it's fixed - just mentioned it to Gustavo. We'll look into it tomorrow.

I'll ping Liz and Mike about type-specific icons.

**Comment by landreev** [comment]
Delete is now working, when trying to delete files from an *already existing draft version*; 
Tested deleting a file that happened to be the designated thumbnail, saw no exceptions.
(still looking into the delete bug, where *all* files get deleted in a published version with no draft).

**Comment by kcondon** [comment]
OK delete of thumbnail when it is selected thumbnail works. There is some unexpected follow on behavior related to not caring which version a selected image lives in but that will be defined in ticket #1433
