### ISSUE TITLE
JSON for Create Dataset should not include Protocol and Authority

### ISSUE THREAD

**Issue by sekmiller** [IQSS/dataverse#1147]
We want to use the Protocol and Authority from the settings table.  Also, the user should not be providing identifier(?).  If we allow the user to provide an identifier we need to verify that it is unique in the database and that a dataset with that identifier has not yet been registered.

@michbarsinai is there anything else I need to worry about here?  Please comment and assign the ticket back to me.

**Comment by ekraffmiller** [comment]
This has been resolved by using the doiSeparator from the Settings table if it isn't found in the JSON

**Comment by esotiri** [comment]
Issue resolved, created dataset with sword and got http://dx.doi.org/10.5072/FK2/QAUPSO.
