### ISSUE TITLE
API: DOI shoulder and identifier not separated with "/"

### ISSUE THREAD

**Issue by esotiri** [IQSS/dataverse#1150]
When a dataset is created via api, doi is http://dx.doi.org/10.5072/FK25555 

![screen shot 2014-11-19 at 3 06 14 pm](https://cloud.githubusercontent.com/assets/1107614/5113479/0200bef4-6ffe-11e4-9c74-fee491298640.png)

and in database I can see missing slash
![screen shot 2014-11-19 at 3 06 54 pm](https://cloud.githubusercontent.com/assets/1107614/5113455/d2435082-6ffd-11e4-9b94-de51559d4295.png)

**Comment by pdurbin** [comment]
I'm just adding #1147 with a hash so this issue links to that one. Also, if we need Michael's input, let's mention him with @michbarsinai

**Comment by kcondon** [comment]
Also, now that we are using global id in the URL to locate datasets, this null issues makes it impossible to get to these datasets with nulls via the UI.

**Comment by pdurbin** [comment]
> this null issues makes it impossible to get to these datasets with nulls via the UI.

I just put in a workaround so that if the doi has the string "null" in it we at least can get to the dataset via its database id: 54cb051

Navigating by globalId rather than database id was introduced in #1238

**Comment by ekraffmiller** [comment]
Added code for reading doiSeparator from Settings if it isn't found in JSON data

**Comment by esotiri** [comment]
issue resolved
