### ISSUE TITLE
Notifications: Define what notifications are sent, their content, and the channel used.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1155]
The purpose of this ticket is to clarify and define which notifications are sent, their content and the channels used, ie. email, online.

A starting point might be the v3.4 notifications spreadsheet:
https://docs.google.com/spreadsheets/d/1IGnhtjxqBziQcWDu88AxU4udZyWfUk3E79rqAtfHSCc/edit#gid=1546983890

**Comment by eaquigley** [comment]
The only part left is to set up a CRON job for the API to email the notifications.

**Comment by scolapasta** [comment]
for 4.0  we decided to send e-mails when the notification is created and not as a cron job.

Passing to QA.

**Comment by sbarbosadataverse** [comment]
@kcondon 
the document referenced doesn't seem complete?? Can I test this yet?

**Comment by sbarbosadataverse** [comment]
following this document: https://docs.google.com/spreadsheets/d/1skbZbetn7h7tB3Iaiyc0UQZZdYTUT4ir-HEenZo7g4U/edit#gid=0

DATAVERSE:
USER CONTACTED DV ADMIN - YES
DATAVERSE CREATED - YES

DATASET:
Create a dataset - (BY ADMIN!) --- Yes
New Version (minor) published -- NO NOTIFICATION to email or on dataverse
New version (major) published - No Notification to email or dataverse
Publishing dataverse and dataset - NO notification received at hmdc or dataverse notifications
Password is updated/changes by user - NO NOTIFICATION at hmdc or dataverse notifications
dataverse notification when added  guestbook and published (minor version)- NO

ACCOUNT:
ACCOUNT CREATED - YES
PASSWORD RESET - NO
GUESTBOOK COMPLETED - NO

**Comment by scolapasta** [comment]
We'll review the notifications in 4.0.1

**Comment by eaquigley** [comment]
Also need notifications for:

- [ ] when a dataverse is published
- [ ] when a dataset is published

**Comment by eaquigley** [comment]
Closing ticket and will review all notifications to determine which ones need to be added in and when.
