### ISSUE TITLE
API: dataverse "contents" endpoint doesn't list all the DvObjects under it

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#1160]
As of this writing https://github.com/IQSS/dataverse/blob/master/scripts/api/readme.md says...

```
GET http://{{SERVER}}/api/dvs/{{id}}/contents

Lists all the DvObjects under dataverse `id`.
```

... but this doesn't work the way I expect. **All** DvObjects? When I try to get **all** DvObjects in my "birds" dataverse I don't see the dataverse "birds/sparrows/chestnutsparrows" nor the dataset "birds/finches/finchdataset1".

Here's is the attempt to list **all** DvObjects under the "birds" dataverse, which is right under the root dataverse. We don't see all the DvObjects under the birds dataverse. We appear only see direct children of the "birds" dataverse?

```
curl -s "http://localhost:8080/api/dvs/birds/contents?key=$FINCHKEY" | jq .
{
  "status": "OK",
  "data": [
    {
      "type": "dataverse",
      "id": 113,
      "title": "Finches"
    },
    {
      "type": "dataverse",
      "id": 114,
      "title": "Sparrows"
    },
    {
      "type": "dataverse",
      "id": 115,
      "title": "Wrens"
    }
  ]
}
```

Here is the dataverse at "birds/sparrows/chestnutsparrows"

```
curl -s "http://localhost:8080/api/dvs/sparrows/contents?key=$FINCHKEY" | jq .
{
  "status": "OK",
  "data": [
    {
      "type": "dataverse",
      "id": 116,
      "title": "Chestnut Sparrows"
    }
  ]
}
```

Here is the dataset at "birds/finches/finchdataset1":

```
curl -s "http://localhost:8080/api/dvs/finches/contents?key=$FINCHKEY" | jq .
{
  "status": "OK",
  "data": [
    {
      "id": 121,
      "identifier": "4dabc5",
      "persistentUrl": "http://dx.doi.org/10.5072/FK2null4dabc5",
      "protocol": "doi",
      "authority": "10.5072/FK2",
      "type": "dataset"
    }
  ]
}
```

As the dataverse "contents" API endpoint is currently documented, here's what I except to see from "api/dvs/birds/contents" (all of these are in draft):
- finches
  - finchdataset1
- sparrows
  - chestnutsparrows
- wrens

**Comment by eaquigley** [comment]
Related to #752

**Comment by pdurbin** [comment]
The "contents" API has never quite worked right (#2122) but it hasn't been a priority to fix it. That's fine. Closing.
