### ISSUE TITLE
Facets for unselected metadata blocks showing up as options on Dataverse Create

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#1162]
When I went in to create a Dataverse, I just kept the default citation block selected however when I scrolled down to see what facets were available for me to select I saw ALL facets available for all metadata blocks including the GSD. Is this expected behavior? Wouldn't you only want to show the users facets from the metadata blocks they had selected?

![image](https://cloud.githubusercontent.com/assets/5013837/5166294/cc4fae92-73bc-11e4-9e56-678d9ee8060b.png)

**Comment by scolapasta** [comment]
We show all facets as sub dataverses / linked datasets may use any block. But we added a dropdown to make it easier to see what facets belong to what block.

**Comment by posixeleni** [comment]
Works as expected. Closing.
