### ISSUE TITLE
Journal Custom Metadata Block

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#1166]
Creating a custom Journal Metadata Block to be able to browse datasets by journal volume, issue number and Article Type based on [JATS specification] (http://dtd.nlm.nih.gov/archiving/tag-library/n-v990.html). This will be particularly important for journal dataverses that used the collection functionality in 3.6 to achieve this.

**Comment by posixeleni** [comment]
@kcondon if you did not test this new block in #1353 then please do so. Should match what is in this tsv https://docs.google.com/spreadsheet/ccc?key=0AjeLxEN77UZodHFEWGpoa19ia3pldEFyVFR0aFVGa0E#gid=8

**Comment by kcondon** [comment]
Tested as part of #1305, closing
