### ISSUE TITLE
Dataset Templates: Add in Info, Error, Success Messages 

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1182]
Need to add in error and success messages for dataset templates. Related to #682

**Comment by kcondon** [comment]
All ok except for copy, which uses the edit message instead. Btw, for guestbook copy used the create  message instead of copy but I let that one go.

**Comment by scolapasta** [comment]
Shouldn't we just say created, even when it's a copy anyway? Thoughts, @equigley?

**Comment by eaquigley** [comment]
That's fine with me @scolapasta & @kcondon . Passing this to QA to close.

**Comment by kcondon** [comment]
Closing, edit/create/copy, it's all good.
