### ISSUE TITLE
Files: Add in Info, Error, Success Messages

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1184]
Need to add in error and success messages for all things files. Related to #682

**Comment by landreev** [comment]
@kcondon 
I've checked in the code for this; however, there's some new wonkiness on the dataset page, that prevents the restrict and delete files buttons from working properly, again; so that would prevent QA-ing this... Gustavo and I will try to look into this tomorrow.

**Comment by landreev** [comment]
Should be working now. 
Note that the 4 success messages above (assign thumbnail; assign tab file tag; restrict file(s); delete file(s);) appear after the action is performed, while still in the edit mode of the files tab. 
Once the user clicks save, the final, and more generic, "successfully updated" message will appear.

**Comment by eaquigley** [comment]
I took out the second part of the Restricted Files message since the terms of access & restrict access pop up is now a thing. Otherwise looks good. Closing ticket.
