### ISSUE TITLE
Install: do not hard code localhost:8080 in all scripts

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1185]
do not hard code localhost:8080 in all scripts

**Comment by pdurbin** [comment]
@kcondon I'd like to close this. I like the scripts the way they are.

**Comment by kcondon** [comment]
@pdurbin Please leave this alone. Thanks.

**Comment by kcondon** [comment]
OK discussed with Leonid. This ticket was opened pre 4.0 release and the approach we used in v3.x was different to what we do now. We have since settled on assuming all scripts should be run locally against port 8080. I think this ticket was in part a response to design decisions being made on the fly. Closing.
