### ISSUE TITLE
Theme + Widgets: Add Info, Success, Error Messages

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1186]
Need to add in error and success messages for Theme + Widgets. Related to #682

**Comment by ekraffmiller** [comment]
@eaquigley , I refreshed this page with out saving your new text, sorry!  Also, with the validation message being right next to the field, I thought maybe a shorter message would be better - right now it just says "Invalid URL"

**Comment by scolapasta** [comment]
Confirmed that "Invalid URL" works as the validation method. Passing to QA.

**Comment by eaquigley** [comment]
Success messages + error messages are now appearing. Invalid URL inline message showing as well. Closing ticket.
