### ISSUE TITLE
API: Create dataset should not typically specify Protocol, Authority, ID but rely on system values instead. 

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1191]
@scolapasta @sekmiller @michbarsinai @eaquigley @posixeleni 
Now that a more robust DOI support is provided, which assigns IDs, checks for uniqueness and registration, the create dataset endpoint/function should not specify protocol, authority, and id but instead use the system defined values and methods. Since there may be a need to specify such information in certain cases: harvesting already registered datasets, or in cases where some partners want to be able to specify: Odum, Heidelberg U., we may need to support both modes: most common, do not specify and use system values, less common, allow specifying the information.

**Comment by ekraffmiller** [comment]
Adding info about this ticket from an email exchange with @scolapasta and @mcrosas - 

On Fri, Jan 16, 2015 at 1:54 PM, Kraffmiller, Ellen <ekraffmiller@hmdc.harvard.edu> wrote:
Hi Merce,
I’m adding the logic for generating a global id when batch importing, and Gustavo & I wanted to check with you - if we are importing a DDI that already has an id, for example: <IDNo agency="handle">hdl:1902.1/00011</IDNo>, should we use this data or ignore it and create our own id?

Merce's Response:  Ideally, this would be a configurable option in the API (a parameter). By default, I would say to NOT register a DOI, if there is already a persistent identifier for that dataset. It would be best to validate  that the ID is a "persistent identifier" (DOI, handle, purl, ...), but perhaps it's difficult to do a proper validation. If we have the option to force to register a DOI, even if it already has an identifier, it could be very useful in some use cases.

**Comment by ekraffmiller** [comment]
After talking to Merce & Gustavo, we decided that we WILL register new import datasets.  (Migrate and Harvest datasets will not be registered).
If a new dataset supplies an identifier, we will attempt to register that, else we will generate one.
If a new dataset supplies a protocol, authority or DOI, we will validate that against application Settings, and use that for the registration (currently we only support one protocol, authority and DOI, but in the future we may support more.

**Comment by ekraffmiller** [comment]
@posixeleni , we have one more question for this ticket, that Gustavo wanted me to ask you - for the Import New Dataset use case, should we allow the create dataset command to succeed even if registration fails? (Currently that's how it works when creating a dataset within the app, or with the SWORD API.
Thanks,
Ellen

**Comment by posixeleni** [comment]
@ekraffmiller I'm thinking we should be consistent with the behavior used in the API and GUI. 

However, we should have a way to alert us that the registration (for DOI) failed. Will it automatically try to register a DOI later on?

**Comment by pdurbin** [comment]
For SWORD I plan to start setting registrationRequired to true in the CreateDatasetCommand. I had asked @sekmiller for this but haven't gotten around to changing/testing it.
