### ISSUE TITLE
Persistent ID: Provide support for test, do not register mode.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1193]
Merce mentioned this as a feature and it may help when doing bulk uploads: allow creating datasets without attempting to register IDs. 

I am not entirely sure what the complete details are:
Is it like v3.6: a default TEST value that can be replaced but not registered? Uniqueness will need to be checked.
If registration is enabled after the IDs are created, will the system automatically attempt to "fix" and register these IDs? Is there a case where the answer is yes, and where it is no?

**Comment by ekraffmiller** [comment]
Since we already have a test feature with the DOI "test" authority, and we have logic that prevents registration in during harvest, need to check with Merce if its ok to close this ticket

**Comment by kcondon** [comment]
Merce said this was ok, closing.
