### ISSUE TITLE
Support for ingest of ODS tabular file format

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#1195]
F1000 Research asked if we have any plans to support ingest of ODS file format (Open Document Spreadsheet format) so I am creating this ticket as a placeholder for us to review after 4.0.

**Comment by pdurbin** [comment]
I'd like to point out that this issue has been open since 2014 and hasn't attracted any comments. Maybe ODS isn't a very popular format.

**Comment by oscardssmith** [comment]
I'd leave it open, and let it sit. It's fine if it stays a low priority open issue.

**Comment by pdurbin** [comment]
@jggautier are you in touch with F1000 Research?
