### ISSUE TITLE
Dataverse General Information: Metadata Elements, Can Uncheck the open set of metadata elements and it stays open

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1198]
Open metadata elements->uncheck->remains open and the close option disappeared

![2014-12-02_14-27-22](https://cloud.githubusercontent.com/assets/5922904/5269272/4b3e1b44-7a2f-11e4-92a1-0e5622e39558.png)

**Comment by eaquigley** [comment]
@kcondon could you please retest this once @mheppler finishes his clean up on this page. #1429

**Comment by mheppler** [comment]
@kcondon, @eaquigley -- dataverse.xhtml clean up is done on the Metadata Fields section.

**Comment by eaquigley** [comment]
Tried this today. Done button still appears when one unchecks it. However, the box does not turn uneditable. Need to make sure the box cannot be edited.

**Comment by kcondon** [comment]
Additional clarification, unchecking refers to deselecting the metadatablock for that dataverse. Once deselected, the fields in that block should not be editable but still are.
.
