### ISSUE TITLE
Install: Add option to select two ravens server

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1201]
It is now possible to configure a remote two ravens server so this option should be added to the installer. See #1108  for details.

**Comment by landreev** [comment]
Another simple installer issue.

**Comment by landreev** [comment]
The installer now asks for the TwoRavens URL in the configuration dialogue. 
The user has an option to leave it set to the default value of "NOT INSTALLED". In which case the Dataverse settings option disabling TwoRavens is set. 
The installer provides a brief paragraph of text explaining what this setting is about. 
A documentation entry has been added to the installation guide, under "New in 4.3".

**Comment by kcondon** [comment]
This was added, default is false. Need to test true path/ url.

**Comment by kcondon** [comment]
Works setting path, two ravens is enabled. Closing.
