### ISSUE TITLE
Account Page: Broken Dropdown Menus

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1208]
If you navigate to any of the tabs, you can break the dropdown menus on the Edit Account button, as well as the user name link in the navbar.

The dropdown for the user name link will also break if you go to any of the Account Information, Password pages off the Edit Account button -- API Token is OK, presumably because it's a separate page.

Looking at the XHTML code, there looks to be a lot of update="@all" used on the links and buttons. These have been known to break javascript/jQuery functionality on the page.

**Comment by scolapasta** [comment]
@raprasad can you see if this fix you apply for these works here too?

**Comment by raprasad** [comment]
This appears to be working now.  (I didn't make any changes.)

**Comment by eaquigley** [comment]
Confirmed @raprasad's comment. Closing ticket.
