### ISSUE TITLE
Migrate Collections For Dataverses Using New Dataverse Functionality

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#121]
---

Author Name: **Eleni Castro** (@posixeleni)
Original Redmine Issue: 3530, https://redmine.hmdc.harvard.edu/issues/3530
Original Date: 2014-02-03

---

Since we are moving away from Collections for 4.0, users within a Dataverse should be able/have the option to group/organize Datasets into custom metadata blocks, which would display as a Facet when browsing.

While most Dataverses that use Collections and Subnetworks can easily be converted to Dataverses (see this: http://irri.org/tools-and-databases/irri-dataverse), we have identified a couple of Dataverses that use “Subjects” or “Journal Issues/Volumes” to form their Collections, which would not convert well into Dataverses. For example:
* MRA uses Topic Classifications as Collections 
* Journal Dataverses use Issues/Volumes as Collections: 
** RESTAT: http://thedata.harvard.edu/dvn/dv/restat
** AJPS: http://thedata.harvard.edu/dvn/dv/ajps
* AfricaRice: http://thedata.harvard.edu/dvn/dv/africarice
* IFPRI has some collections that could be made into Dataverses (ex. Social Accounting Matrix (SAM)) but others which resemble Topic Classifications (ex. Regional)
* ICRAF http://thedata.harvard.edu/dvn/dv/icraf

While these will involve some automated migration there will need to be a manual review of the abovementioned Dataverses to ensure that these Dataverse Collections migrated successfully to using custom metadata blocks.

For more information review meeting notes: https://docs.google.com/document/d/1SizZ0K8cj4CzyBBg7pkup_SHqD8IECOdqBg2V0pIKYY/edit?usp=sharing

**Comment by posixeleni** [comment]
migration has not started as of today so will need to move this to Beta 14

**Comment by posixeleni** [comment]
Closing this ticket since it has been replaced with: https://github.com/IQSS/dataverse/issues/1764
