### ISSUE TITLE
Search: Syntax Error, What to display to the end user

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1212]
Currently this is what appears when a user does a search that has no results: 

![colon](https://cloud.githubusercontent.com/assets/5922904/5306180/3dd4f340-7bd0-11e4-9015-d3ee1ed5287d.png)
![undefined-field](https://cloud.githubusercontent.com/assets/5922904/5306188/4caea992-7bd0-11e4-8cec-92520140c06d.png)

We need to change this to be more user friendly and not look like a deeply technical error has occurred that the user has no idea what to do with.

One suggestion: have a "view more details" after the "Sorry, there are no..."  for a user to open to learn more about what happened.

**Comment by pdurbin** [comment]
@mheppler said to pass this to him to take care of hiding the technical details and revealing them with a link. I did stub this out a bit (and fixed a 404 to the search guide) in this commit: 37325ba

**Comment by mheppler** [comment]
Added collapse functionality to technical details of search with no results on the dataverse page.

**Comment by pdurbin** [comment]
@kcondon you should see different errors/technical details if you search for ":" vs. searching for "foo:bar". See also the screenshots above.

**Comment by kcondon** [comment]
OK technical details are hidden behind link, closing
