### ISSUE TITLE
Create a Custom Metadata Block for ARCS Dataverse

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#1213]
Per #833 all custom metadata fields need to be properly migrated into 4.0. 

The [ARCS Dataverse](http://thedata.harvard.edu/dvn/dv/arcs) has custom metadata fields which I will transform into an ARCS metadata block.

Writing the tsv here: https://docs.google.com/spreadsheet/ccc?key=0AjeLxEN77UZodHFEWGpoa19ia3pldEFyVFR0aFVGa0E#gid=6

**Comment by posixeleni** [comment]
@kcondon if you did not test for this new block in #1353 please do so. This should match what is in the tsv file https://docs.google.com/spreadsheet/ccc?key=0AjeLxEN77UZodHFEWGpoa19ia3pldEFyVFR0aFVGa0E#gid=6

**Comment by kcondon** [comment]
Tested as part of #1305, closing
