### ISSUE TITLE
Configuration: Enforce https on glassfish

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1214]
For now, until we work out issues with fronting gfish by apache, we need to enforce https on gfish.

A quick google search shows a "port unification" method for v3.x:

http://brentingitup.com/?q=node/5

Another method is to ensure confidential for transport:
https://glassfish.java.net/docs/4.0/security-guide.pdf

http://stackoverflow.com/questions/5472707/user-data-constraint-is-not-working
First in web.xml do this -
"
\<user-data-constraint\>
    \<transport-guarantee\>CONFIDENTIAL\</transport-guarantee\>
"
Then in the admin console of your weblogic server "check" the SSL Listen port enabled.
This should then redirects your normal http calls to https in the url.

**Comment by scolapasta** [comment]
So, since we are doing apache, we're all set with this, yes? @kcondon can you please verify?

**Comment by kcondon** [comment]
Closing
