### ISSUE TITLE
Create a Custom Metadata Block for PS Replication Dataverse

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#1215]
Per #833  all custom metadata fields need to be properly migrated into 4.0.

The [PS Replication Dataverse](http://thedata.harvard.edu/dvn/dv/PSReplication) has custom metadata fields which I will transform into a PS Replication metadata block.

Writing the tsv here: https://docs.google.com/spreadsheet/ccc?key=0AjeLxEN77UZodHFEWGpoa19ia3pldEFyVFR0aFVGa0E#gid=7

**Comment by posixeleni** [comment]
@kcondon if you did not confirm this new block while testing for #1353 please confirm that this metadata block is displaying. Should show as is represented in this tsv https://docs.google.com/spreadsheet/ccc?key=0AjeLxEN77UZodHFEWGpoa19ia3pldEFyVFR0aFVGa0E#gid=7

Feel free to close if you have already tested this.

**Comment by kcondon** [comment]
Tested as part of #1305, closing
