### ISSUE TITLE
Dataverse - Edit General Information - Tab Order Includes Labels

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1218]
On some versions of Chrome, the tab order on the Dataverse - Edit General Information page includes the field labels.

Related #307, #1190.

I created this as a separate ticket, because it's a separate page than Sign Up and might require a dynamic solution, like Dataset.

**Comment by mheppler** [comment]
The tab index order is working on the Edit Dataverse General Information page. The Metadata Elements and Select Facets widgets are not something that we'll be able to tab through easily with the PrimeFaces widgets, and tabbing just skips over them and goes to the Save Changes button, so I'm closing this for now.

**Comment by kcondon** [comment]
OK looks good, closing
