### ISSUE TITLE
Add "subset download" functionality to the files tab 

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#1222]
This task was originally part of #1066. But since everything else in there was already completed, I moved it to QA; and I'm opening this one for the subset thing. 
@mheppler : 
Please create a popup with the variable selection GUI javascript from Vito. A new item 'subset' needs to be added to the tab file download menu; clicking on it should open this popup. 

Please pass it back to me for wiring. Or you may not even need to... as I understood from his demo, 
when the user clicks "download", his javascript cooks a complete download url that should be ready to go... But do pass it to me if there's any doubt as to whether it's doing the right thing.

**Comment by mheppler** [comment]
Added the TwoRavens code into a new Download Data Subset popup linked from the files Download dropdown button. [ref 75ff1573463f2ed877a10c8344da6c0030a5f022]

Passing to Leonid to make the hostname dynamic, rather than the hard coded 'localhost'. The 'Download' button is also displaying the URL in an alert. I am hoping Leonid will know what to do with that as well.

Let me know if you need anything from me, @landreev.

**Comment by mheppler** [comment]
Fixed the renders on the Download Data Subset popup so that file upload will work.

Fixed Download button in the Download Data Subset popup.

**Comment by mheppler** [comment]
Also, it didn't look like the download URL was getting just the selected variables into the file. It looked like what I was downloading was the entire file. (See attached.)

![screen shot 2015-01-12 at 10 30 44 am](https://cloud.githubusercontent.com/assets/687227/5705277/1b52b354-9a46-11e4-969b-f546418a9b85.png)

**Comment by landreev** [comment]
OK, just pushed in a fix for the issue above (it was simply "vars=" instead of "variables=" in the subset 
parameter in the javascript).

**Comment by landreev** [comment]
Will add a fix for the hostname shortly.

**Comment by landreev** [comment]
Should be ready to test now.

**Comment by kcondon** [comment]
OK, tested, works, closing
