### ISSUE TITLE
MetadataFragment.xhtml - more efficient renders for edit mode

### ISSUE THREAD

**Issue by sekmiller** [IQSS/dataverse#1223]
The file is used by Dataset page when editing/displaying a dataset, likewise for Template.  It's also used by ManageTemplates for a preview.  

The following ui:fragment render causes beans to be created for all three pages.  Should be able to do this more efficiently (use params maybe)

<ui:fragment rendered="${((empty DatasetPage.editMode) and (empty TemplatePage.editMode)) or ManageTemplatesPage.selectedTemplate != null}">

**Comment by sekmiller** [comment]
Leaving assigned to me. This may be done already. will review the code

**Comment by sekmiller** [comment]
This has been completed.  To verify please test that view and edit metadata works in both template and dataset contexts

**Comment by kcondon** [comment]
OK, template and dataset/blocks working. Closing.
