### ISSUE TITLE
EJBException in browser with dataset.xhtml?globalId=foo

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#1224]
In my browser I see `HTTP Status 500 - Internal Server Error` and `javax.ejb.EJBException: Error parsing identifier: foo. ':' not found in string` if I go to https://dvn-build.hmdc.harvard.edu/dataset.xhtml?globalId=foo

![glassfish_server_open_source_edition_4 1_-_error_report_-_2014-12-06_08 11 46](https://cloud.githubusercontent.com/assets/21006/5327521/3ace2756-7d20-11e4-9f8c-5289da4e1fe3.png)

**Comment by sekmiller** [comment]
giving a global id url that does not parse will put user in 404 page - Dataset not found.

**Comment by kcondon** [comment]
OK, gets a 404 for first case through UI, gets a 403, forbidden in second, sword case. Also, sword error is in html when maybe should not be? I believe there already an issue for such html/api errors.

Closing
