### ISSUE TITLE
Advanced search: Can't find dataverse with name of "a" when searching for dvName_en:a

### ISSUE THREAD

**Issue by esotiri** [IQSS/dataverse#1225]
On dvn-build, created a new dataverse > Advanced search does not return result when searching for dvName_en

**Comment by eaquigley** [comment]
Closing as this isn't a bug. A is a stopword so there should be no results for it.

**Comment by esotiri** [comment]
@eaquigley or @scolapasta, sorry I'm a bit confused.   We are allowing creating dataverse with name from the list of English dictionary stop words, but we are not displaying the results in the advanced search? 

It seems that it returns results for stop words >= 5 chr 
From the stop words list, I created a dataverse with name 'about' and I can find it the advance search dvName_en:about

**Comment by scolapasta** [comment]
I think that behavior is fine. My guess is "about" would also match the case if you created a dataverse with the name "Experiment about bunnies". So matching just about is fine.

We just don't want to match something like "a" or "the" that will be used in so many dataverses.

**Comment by scolapasta** [comment]
Also, as people use the sytem more and more, we can think about if we need to modify this behavior.

**Comment by esotiri** [comment]
ok, that makes sense. thanks
