### ISSUE TITLE
File Download: By guessing the file id, any file can be downloaded

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#1226]
https://dvn-build.hmdc.harvard.edu/dataset.xhtml?id=32 (for example) is an unpublished dataset and if you log in as "admin" and hover over the link to a file, you can see that the URL is https://dvn-build.hmdc.harvard.edu/api/access/datafile/34

If an attacker can guess the database id of the file, it can be downloaded without any authentication with `curl https://dvn-build.hmdc.harvard.edu/api/access/datafile/34` or via a browser.

Here's how the unpublished dataset and file looks from the GUI when logged in as admin:

![curl-any-file](https://cloud.githubusercontent.com/assets/21006/5343464/2e3aac8e-7ed4-11e4-8a83-0faa42a8e597.png)

![curl-any-file2](https://cloud.githubusercontent.com/assets/21006/5343467/32f59482-7ed4-11e4-805b-d553c53a6c8e.png)

**Comment by pdurbin** [comment]
Huh. This ticket was never closed or given a milestone. Moving to QA.

**Comment by kcondon** [comment]
closing due to above related issue being closed.
