### ISSUE TITLE
Account Page: Hide Group & Roles Tab

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1227]
@mheppler can you use ui remove to hide the group and roles tab on the account page. we will add this tab back in after 4.0 with the necessary functionality

**Comment by mheppler** [comment]
Groups & Roles has been hidden on the Account page tabs, the user name dropdown menu links, and the BuiltinUserPage backing bean where it referenced the tab order.

**Comment by esotiri** [comment]
resolving
