### ISSUE TITLE
Templates: Ability To Set Dataset Licensing and Terms of Use + Access for Multiple Datasets

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#1229]
Spoke about this with @scolapasta and @ekraffmiller that it would be nice if Dataverse Admins could set a default Licensing and Dataset Data Usage Agreements Terms at the Dataverse-level for all their Datasets instead of having to edit this each time they add a new Dataset.

@eaquigley recommended we look into adding this support in the Dataset Templates feature.

**Comment by posixeleni** [comment]
@eaquigley @scolapasta I am copying over Templates from 3.6 to 4.0 right now and am unable to copy over template text from Terms of Use metadata

![image](https://cloud.githubusercontent.com/assets/5013837/7573831/aae99312-f7f6-11e4-9416-8a6ab20ed000.png)

I am making a note of all the templates that i need to go back in and add this once its supported in 4.0

**Comment by posixeleni** [comment]
Another example for why we need to include in the Templates Terms of Use:

This Elections Data Dataverse uses CC-BY but they would have to set this every time they create a new dataset. https://dataverse.harvard.edu/dataverse/eda

![image](https://cloud.githubusercontent.com/assets/5013837/7820855/eb15da7c-03b8-11e5-8285-3c3c00084f7b.png)

**Comment by posixeleni** [comment]
This will be an issue for ALL the PSI Templates and the UCLA SSDA Templates since they have Terms inserted in their templates.

**Comment by posixeleni** [comment]
Any items in the following spreadsheet with a red box indicates that I was not able to 100% complete the template copying due to us not having the Terms of Use and Terms of Access in the templates for 4.0.: https://docs.google.com/spreadsheets/d/1Y_y5SbxbZZrCLQOIpTIar236BFjQ18V2hYdX6ZKAjFg/edit?usp=sharing

When this functionality is in place someone will need to go in and copy the terms of access and terms of use that these templates had in 3.6

**Comment by eaquigley** [comment]
@sekmiller a few things to change:

- [ ] on beta.dataverse.org, the Save and Add Terms button in the pop up isn't work BUT that shouldn't be an issue anymore (unless it still is, so sorry) because I'd like you to change it to be...
- [ ] Rather than have Create Dataset Template button on the bottom of the metadata page, make that be the Save and Add Terms button to bring a user to the Add Terms portion.
- [ ] at bottom of Add Terms page, change button to be Save Dataset Template and Cancel with a pop up warning the user they will be losing their changes

Make sense?

**Comment by sekmiller** [comment]
As discussed, we're not going to add a warning popup on "Cancel" because we don't warn on cancel in general.  Also, I think we should leave the save for the templates portion to be "Save Changes" for consistency with other edit (non-create) modes.

**Comment by sekmiller** [comment]
Completed as described above with the exception of warning popup for cancel.  Ready for testing after next build

**Comment by kcondon** [comment]
OK, works as described by Liz with caveats provided by Stephen. Closing.
