### ISSUE TITLE
Publish Dataverse: Unpublished state is not refreshed after publishing dataverse.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1232]
Using Chrome Version 39.0.2171.71 m

When I published a dataverse, there is not message to indicate anything happened and the dataverse still says unpublished, though refreshing the page shows it is published.

**Comment by mheppler** [comment]
The duplicate #1231  was closed.

**Comment by esotiri** [comment]
duplicate of #1231 closing
