### ISSUE TITLE
Facets: Show facets that are related to the checked metadata blocks only

### ISSUE THREAD

**Issue by esotiri** [IQSS/dataverse#1233]
Creating this per @eaquigley from https://github.com/IQSS/dataverse/issues/359: When unselecting a metadata block, the facets still show, facets only related to the checked metadata blocks should appear.

**Comment by eaquigley** [comment]
Due to children dataverses, we can't actually hide the facets HOWEVER we can do something to have headings for each section of facets (i.e. Citation: with facets listed below) to provide better organization and context. @scolapasta is looking into this.

**Comment by scolapasta** [comment]
Added a dropdown which shows each blocks (plus "All"), so you can filter just the ones you want.

Only issue is that when you remove one from the selected, it will return it to the source list. Added an ajax call to remove it if not that list, but it will "blink" there for a second. I'm not aware of any way to work around this other than to change from picklist.

**Comment by kcondon** [comment]
OK, pick list groups work, closing
