### ISSUE TITLE
When clicking a dataset the DOI (globalID) should appear in the URL

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#1238]
When I go to http://thedata.harvard.edu/dvn/ and click on the first study I see I am taken to a URL with a DOI in it: http://thedata.harvard.edu/dvn/faces/study/StudyPage.xhtml?globalId=doi:10.7910/DVN/27955

When I go to http://dataverse-demo.iq.harvard.edu and click on the first dataset I see I am taken to a URL with the dataset database ID in it: http://dataverse-demo.iq.harvard.edu/dataset.xhtml?id=72&versionId=27

From internal discussion it sounds like we want to preserve the behavior in production.

**Comment by pdurbin** [comment]
d98eb5e and 5f6c95f contain the changes I made. At first I thought this would just be the search cards but there are a number of places in the system where the database id for a dataset is exposed in the GUI. Here are places I changed:

- dataset card
- file card
- dataset versions tab
- notifications
- redirect URLs

Passing to QA.

**Comment by kcondon** [comment]
OK, tested all of the above cases, works, closing
