### ISSUE TITLE
Featured Dataverses link broken when no logo

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#1239]
Set a featured dataverse of a dataverse which has no logo, clicking on image does not go to dataverse.

**Comment by sekmiller** [comment]
I'm not able to get this to happen.  Please re-test and let me know a specific set of steps to recreate.

**Comment by kcondon** [comment]
Could not reproduce @scolapasta cannot feature any dv below immediate child, plus if try to feature dv from a dv, not root level, featured dv feature never appears. Comment?

**Comment by scolapasta** [comment]
Only featuring immediate children is not ideal, but we may have to live with for 4.0. But not being able to feature below root seems to me a bug.

**Comment by kcondon** [comment]
Opened separate ticket: #1434 Closing
