### ISSUE TITLE
Cleanup: initDatasetFields in DatasetVersion and DatasetVersionUI

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#1241]
We have two methods that do the same thing - the call in DatasetVersionUI should just call the DatasetVersion's/

**Comment by pdurbin** [comment]
@scolapasta do we still need this cleanup?

**Comment by mheppler** [comment]
@sekmiller commented on Mar 31, 2015 in issue #1816 (which has been closed as duplicate of this issue)...
>The Dataset page and the API retrieve dataset versions differently in some cases. Review how each is done and implement the best version across the application.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
