### ISSUE TITLE
Download: File citation format shows off the page if page not large enough.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1243]
The new file citation download has two formats listed in a sub select popup: endnote and ris. This works but displays off the page, to the right or below if the window is not sized correctly.

**Comment by scolapasta** [comment]
This is also true for the new "Permissions >" under Edit Dataverse.

**Comment by mheppler** [comment]
This issue was also reported in #2736 and was fixed in the commit 1686142c9a801e5b85a462157af20926cc0f30c0.

**Comment by kcondon** [comment]
Still works, closing.
