### ISSUE TITLE
Validation: Properly handle cases where required has been dynamically set for DatasetFields

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#1245]
We recently added logic for DatasetFields to be set as required at a dataverse level.

We need to make sure that:
- this is looked at when validation is called
- this is looked at when determining to use the NA value

**Comment by scolapasta** [comment]
This is done, but might best wait to be tested until #1416 (also require validation related) is done.

**Comment by sbarbosadataverse** [comment]
This is based on another ticket, #1416. Parent can set required fields, but child can change those fields as needed. Appears all set. Tested both: Child does inherit required fields from parent; child can change from required to other.

https://www.dropbox.com/s/lrp10qkyajuikj6/Screenshot%202015-03-18%2016.11.11.png?dl=0
