### ISSUE TITLE
Allow multiple contact e-mails for a dataverse

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#1251]
Right now you can only select one. You should be able to press a "+" button and add additional (we allowed multiple in 3.6, but as a comma separated list).

This will involve a db change, a UI change, and then logic to hable this when sending e-mails (and copying e-mails to new datasets).

**Comment by mheppler** [comment]
Cleaned up the layout of the Edit Dataverse General Information page with the new multiple email fields.

**Comment by esotiri** [comment]
It is working ok to add additional contact email to the dataverse.  However it lets me add same email multiple times. Do we want to check for uniqueness? and say something that email already exists.

**Comment by scolapasta** [comment]
We do not need to have uniqueness through the system for this. However, yes, putting the same e-mail here is a minor issue. Let's close this ticket and you can reopen a separate issue and assign to post 4.0.

**Comment by esotiri** [comment]
per @scolapasta opened https://github.com/IQSS/dataverse/issues/1306
