### ISSUE TITLE
Create Dataset: Validation error on soc sci block not shown since block collapses on save.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1253]
Entered a string rather than a number in Target Size, Actual size and when I saved, there was not obvious error. Turns out the error occurred in the doc sci block but that block was collapsed on save and so did not see the error.

**Comment by mheppler** [comment]
Cleaned up the error message block on the Dataset page.

In addition to this problem, this page doesn't have a general error message at the top of the page.

This ticket belongs in the 4.0 Messaging queue, to be addressed with the other remaining messaging issues. I am also opening a new, related issue (#1304) for these custom fields, that need input watermarks, letting a user know that a special format is required/allowed -- ie, integer, date, html, etc.

**Comment by mheppler** [comment]
Related #1304.

**Comment by eaquigley** [comment]
Passing to QA to close as it is a duplicate of #531

**Comment by kcondon** [comment]
OK, the general message,  Data input validation error. See below for details.  , works but when the block is collapsed, you still don't see where the problem is. Closing.
