### ISSUE TITLE
ICPSR data utilization-GUESTBOOK

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#126]
---

Author Name: **Gustavo Durand** (@scolapasta)
Original Redmine Issue: 3535, https://redmine.hmdc.harvard.edu/issues/3535
Original Date: 2014-02-06

---

from Mary at ICPSR:

Hi, Merce. Bryan has left ICPSR and Nathan Adams has taken over for him. He was asking about getting utilization data from the Dataverse guestbook. He suggested additional fields that we should capture. Here is what he says:

I think the missing link regarding utilization data is the mechanism for transferring the data from the DVN system to our utilization tracking system.  My sense is we would need to write some software to integrate the two systems and that this software would need access to the following information about each downloaded file (in addition to the user info you indicated earlier):

INSTIT_NO - the id of the member institution that the user belongs to
STUDY - the study number
DS - the dataset number
ORDER_DATE - date/time stamp of the download event
EMAIL - email address of the user
REMOTEHOST - ip address of the user
KBYTES - size of the file downloaded
SESSIONID - DVN session ID
FILECONTENT - content type (based on ICPSR controlled vocabulary) of the file
FILEDESCR - file description
FILEFORMAT - format (based on ICPSR controlled vocabulary) of the file
PATH - if multiple DVN instances are used, this field should be used to differentiate them
FILE_ID - the ICPSR id of the file

Let us know if you need additional information. Thanks.

Mary
--

**Comment by scolapasta** [comment]
This is from old 3.6 world where harvested downloads originated on the dataverse side. We now send you directly to the harvest source for the download.
