### ISSUE TITLE
Handle keyword and description metadata changes

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#1262]
Keyword and Description were made into compound fields and now don't show up "above the fold" (nor does description show up in the search card).

When fixing this, we need to consider the case of description when a 2nd (or nth) description matches the search  (the contextual highlighting bit).

**Comment by sekmiller** [comment]
Per conversation with Eleni, for simplicity's sake we will display only a list of keywords and the first description.  Users my click on the metadata tab for more details.

**Comment by sekmiller** [comment]
Fix is checked in and may be tested after next build

**Comment by sekmiller** [comment]
@pdurbin does this need your attention. See Gustavo's 12/15/14 note....

**Comment by posixeleni** [comment]
@sekmiller Should we be seeing this fix in build? I see the values for the Keyword field and the description but I dont see the field name "Keyword"

![image](https://cloud.githubusercontent.com/assets/5013837/6043929/f53b3d88-ac5d-11e4-8ddc-a71dea8b15dd.png)

**Comment by pdurbin** [comment]
> @pdurbin does this need your attention. See Gustavo's 12/15/14 note....

Yes, there is search stuff to fix. This shouldn't be in QA.

**Comment by kcondon** [comment]
Making separate ticket for Eleni's bug: #1427

**Comment by pdurbin** [comment]
> we need to consider the case of description when a 2nd (or nth) description matches the search (the contextual highlighting bit)

For this ticket I'm focusing on highlighting search results. Prior to 20c304f if you created a dataset with two authors with the same last name and then searched on that last name, you would only get a highlighted match for one of the authors. Now, you see both:

![wright](https://cloud.githubusercontent.com/assets/21006/6398190/f0d60000-bdb7-11e4-9491-aeb0f04b46f4.png)

The parameter "[hl.snippets](http://wiki.apache.org/solr/HighlightingParameters#hl.snippets)" what I increased from the default of 1 to 10:

> The maximum number of highlighted snippets to generate per field... The default value is "1".

I tested description as well, and it seems to work fine. I **think** 10 will be plenty but we can always increase it.

@scolapasta if this ticket is supposed to be about more than just highlighting, please let me know. Passing to QA.

p.s. Go [Flyers!](https://udayton.edu)

**Comment by scolapasta** [comment]
Highlighting has been reverted and is now issue #1589 

The index related changes, I think, then are just showing description on search code, which is also separate: #1522 

So this is really now just for the changes @sekmiller  made.

**Comment by posixeleni** [comment]
Keyword is now displaying as expected. Closing.

On the dataset summary page:
![image](https://cloud.githubusercontent.com/assets/5013837/6756803/bcde8388-cf02-11e4-9485-509a6f5e64e9.png)

On the search results when searching for a keyword:
![image](https://cloud.githubusercontent.com/assets/5013837/6756816/dc381d20-cf02-11e4-8384-27cd41009f34.png)
