### ISSUE TITLE
Versioning Terms of Use and Terms of Access for Datasets

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#1263]
Discussed yesterday evening with @sekmiller @mcrosas and @scolapasta that any changes to Dataset terms of use and Dataset terms of access should be version controlled just like the dataset metadata blocks. Users would be given the option to select a major or minor version release and would need to publish their draft version for the new terms to be publicly displayed.

Although previous versions of the terms would be available we should include a way (button) for users to toggle to the currently applied Terms since previous terms are only available for historical reasons and no longer apply to the files in the dataset.

cc/ @eaquigley @mheppler

**Comment by sekmiller** [comment]
Terms of Use are now saved at the version level. Need to get the latest check-in for the copying of TOU and ancillary data to new dataset versions

**Comment by kcondon** [comment]
OK, tou are versioned, closing
