### ISSUE TITLE
Deaccession: deaccessioner can not see metadata nor perform many actions

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#1267]
According to the [Deaccessioning design doc](https://docs.google.com/document/d/1lFcwjtdGIqqQLYYnwtTI2GZNzmzYlrnMk2omGcXO9oY/edit?usp=sharing), "Only the owner (others with permission) will have a link in the versions tab **so that they may see the metadata/files associated with the deaccessioned version**." (emphasis added)

Probably due to changes in permissions, it is not possible for anyone (even admin!) to see the metadata for the deaccessioned dataset. (There is no "Metadata" tab.) I'm sure an admin might be interested in looking into the details of why a dataset was deaccessioned, beyond the reason given on the version tab. They might want to look at the metadata or the files.

The dataset creator might want to create a new version of the dataset based on the deaccessioned version.

Screenshot:

![spruce_goose_-_spruce_dataverse_-_2014-12-17_09 07 34](https://cloud.githubusercontent.com/assets/21006/5472274/db4bee34-85cc-11e4-9164-46984398af65.png)

**Comment by Grimaldum** [comment]
You still can't see metadatas of the deaccessioned dataset as creator. 
Also, if you create a draft version of a dataset, then deaccession it, you will keep a draft version of the dataset, ready to publish later. But, if you deaccession a dataset, you can't make a draft version of it any more. Maybe allowing , to the creator, to create a draft version of a deaccessioned dataset would solve some "problems" with that issue ?

**Comment by mheppler** [comment]
In addition to not being able to see the Metadata, the Version tab reads, "No records found" when there are in fact other published/draft version.

<img width="980" alt="screen shot 2016-10-20 at 4 03 12 pm" src="https://cloud.githubusercontent.com/assets/687227/19575934/f4b61da2-96de-11e6-9e7b-efa038cabd37.png">

**Comment by mheppler** [comment]
Related to #1308.

**Comment by djbrooke** [comment]
@sekmiller what's the correct state of this one? Should this be in Development?

**Comment by sekmiller** [comment]
@djbrooke  Can probably go directly into QA. There's nothing notable about the code changes.

**Comment by mheppler** [comment]
When the Versions table is displayed, there is no version number displayed in the first column if you are an end user without access to view that version (see attached). Instead of an empty column cell, we should put a static text version number.

![screen shot 2016-10-25 at 4 35 08 pm](https://cloud.githubusercontent.com/assets/687227/19703286/47dc7652-9ad1-11e6-997f-89070654cfbf.png)

**Comment by djbrooke** [comment]
Had a brief discussion about this in standup 10/25. This is ready for code review, but the fix is on the file landing page branch. I'm going to move it to the bottom of the development column in Waffle for now.

**Comment by pdurbin** [comment]
@sekmiller was this fixed by b5b5f31?

**Comment by pdurbin** [comment]
@sekmiller and I just spoke about how b5b5f31 indeed should be a fix for this issue so he said this issue should go to QA. I associated it with pull request #3408.

**Comment by mheppler** [comment]
Based on feedback from @mcrosas, hid the "Share" button in deaccessioned view on dataset and file pgs.

**Comment by kcondon** [comment]
All good, closing.
