### ISSUE TITLE
Review/Update UNF documentation in Developers Guide

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#1268]
@landreev the UNF documentation has been moved to the Developers Guide in Sphinx: https://github.com/IQSS/dataverse/tree/master/doc/sphinx-guides/source/developers/unf

Please review & update it there and let me know if I can help with anything.

Thanks!

**Comment by landreev** [comment]
I've completed #959 - the finalized new UNF v6 technical writeup. 
Just need to rewrite the top-level paragraph in doc/sphinx-guides/source/developers/unf/index.rst . 
It still has some awful language in it. ("UNF version 5 is implemented and uses Java code")

**Comment by landreev** [comment]
OK, so I've rewritten the top-level blurb (doc/sphinx-guides/source/developers/unf/index.rst).
So the UNF documentation is complete. 
Of course, if anyone has any specific suggestions/improvements, we'll keep improving it.

**Comment by kcondon** [comment]
Looks good, closing
