### ISSUE TITLE
Dataverse Level: Info, Error, & Success Messages

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1269]
Success Messages:
- [x] You have successfully created your dataverse! To learn more about what you can do with your dataverse, check out the User Guide (insert this link: http://guides.dataverse.org/en/latest/user/dataverse-management.html)
- [x] You have successfully updated your dataverse!
- [x] You have successfully updated the theme for this dataverse!
- [x] The permissions for this dataverse have been updated. 
- [x] This dataverse has been published.
- [x] The dataverse was deleted. 
- [x] The featured dataverses for this dataverse have been updated.

Error Messages:
- [x] This dataverse was not able to be deleted. Please try again or contact support@dataverse.org.
- [x] The theme for this dataverse was not updated. Please try again or contact support@dataverse.org.
- [x] This dataverse was not able to be updated. Please try again or contact support@dataverse.org.
- [x] This dataverse was not able to be published. Please try again or contact support@dataverse.org.

**Comment by kcondon** [comment]
OK, tested success 2-6 and error 2, passing back for remainder. @eaquigley msg says dataverse is now public rather than dataverse has been published, ok? Also, perms msgs make sense but not so generic as listed above. ok?

**Comment by eaquigley** [comment]
@kcondon I would prefer that the message says the dataverse is published not public for consistent terminology sake across the application. For perms msgs, which ones are you talking about? I'm confused.

**Comment by kcondon** [comment]
@eaquigley The permissions for this dataverse have been updated.

**Comment by kcondon** [comment]
OK, looks good, closing.
