### ISSUE TITLE
Files: Advanced Options Pop Ups Need Informational Text

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1271]
For image file:
- [ ] Select if you would like this image to be used as the image that is displayed in the search results card for this dataset.

For Tabular Data Tags:
- [ ] Select one or more tags to describe the type of data file this file is.

**Comment by mheppler** [comment]
Additional info text is also needed for the following fields.

For spss-savEncoding:

[ ] {INFO TEXT NEEDED}

For variable labels text file:

[ ] {INFO TEXT NEEDED}

**Comment by mheppler** [comment]
Added info help text to the Advanced Options popup on the Upload + Edit Files page for the two options that I had. Need the help info text for the remaining two.

**Comment by landreev** [comment]
I have a separate ticket for #831 (Odum-style SPSS .por ingest).
The text currently there, in the "advanced options" menu for SPSS/por files says "Upload text file with variable labels". 
I wanted to review this ticket one more time before I move it into QA. I can give it to you first, if you want to try and think of a better way to phrase it. 
IMO, it doesn't even need to be super user-friendly. The only people who will be using this option - folks from ODUM - do know what it does. Maybe we should just add "(Optional!)" to it... to make sure everybody else understands it's not something they HAVE to supply.

**Comment by landreev** [comment]
I already replied to the question about the spss/sav advanced option, outside github; 
but adding it here, for reference: 

The 4th "advanced option" is for SPSS .sav files.
From #1035:

    2) if the file type is recognized as "application/x-spss-sav", we want to also show a menu for [optionally] selecting a     specific language encoding.

All it needs to say is "select text encoding", or "select language encoding". And a pull down select menu next to it.
I can think of  reasonable help text when I implement this; and I can give it to you for review.

**Comment by kcondon** [comment]
OK, verified the above works as described. Closing.
