### ISSUE TITLE
Guestbook: Info, Error, Success Messages

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1277]
Info:
- [x] You can set up a guestbook to assign to datasets to collect information on all users before they can download or subset files from the dataset. The guestbook is independent of Terms of Use. You can create custom questions or select to collect the user account information from the person downloading the files.

Success:
- [x] The guestbook has been copied.
- [x] The guestbook has been enabled.
- [x] The guestbook has been deleted.
- [x] The guestbook has been edited and saved.
- [x] The guestbook has been created.

Error Messages:
- [x] Please add in a name for the guestbook.
- [x] The guestbook cannot be created. Please try again or contact support@dataverse.org.
- [x] The guestbook cannot be enabled. Please try again or contact support@dataverse.org.
- [x] The guestbook cannot be copied. Please try again or contact support@dataverse.org.
- [x] The guestbook cannot be disabled. Please try again or contact support@dataverse.org.
- [x] At least one response needs to be added for the custom question you have added.

**Comment by eaquigley** [comment]
@mheppler could you please add in the info text

**Comment by mheppler** [comment]
Added info help text in the backing bean (needs to be wired up still).

**Comment by kcondon** [comment]
OK looks good. All message present, could not test many of the error ones.
Some wording differences but @eaquigley said they were OK. Closing
