### ISSUE TITLE
IP Groups: using PageKite, Numbers in IPv6 addresses should be in hexadecimal notation

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#1281]
I just started [PageKite](http://guides.dataverse.org/en/latest/developers/tools.html#pagekite) and now at http://pdurbin.pagekite.me I get a 500 error:

root cause

java.lang.IllegalArgumentException: Numbers in IPv6 addresses should be in hexadecimal notation.

root cause

java.lang.NumberFormatException: For input string: "65.112.10.81"

@eaquigley indicated I should open a ticket and give it to @michbarsinai 

![hex](https://cloud.githubusercontent.com/assets/21006/5493855/7ba3b7e6-86bc-11e4-82e6-93abb85f88e2.png)

**Comment by pdurbin** [comment]
I'm getting "Parsing remote address: ::ffff:65.112.10.85".

@michbarsinai can you please remove `@Ignore` from from the test I added in e6be40b and get it passing?

**Comment by pdurbin** [comment]
> ::ffff:65.112.10.85

This seems to be an "IPv6 'IPv4 mapped' address" according to http://docs.guava-libraries.googlecode.com/git-history/v18.0/javadoc/com/google/common/net/InetAddresses.html

Could we just use that Guava library to parse addresses for us? Instead of having our own? It's the most upvoted and accepted answer at http://stackoverflow.com/questions/2309049/is-there-an-easy-way-to-convert-string-to-inetaddress-in-java

**Comment by michbarsinai** [comment]
We can. I'll have to see how this will work with efficient SQL queries.

**Comment by michbarsinai** [comment]
Implemented support for IPv4 addresses mapped onto IPv6 addresses, such as 
::ffff:192.133.24.33.

Unit tests following: `edu.harvard.iq.dataverse.authorization.groups.impl.ipaddress.ip.IpAddressTest`

**Comment by pdurbin** [comment]
It works! \o/

**Comment by kcondon** [comment]
Phil tested and confirmed it is fixed, closing
