### ISSUE TITLE
Account Page -- Conditional Page Title

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1282]
The dataverseuser page should have conditional page titles for each of the different workflows associated with the page: "Account Sign Up", "Account Information", "Edit Account Information", "Change Account Password", "Forgot Account Password". This special render logic associated with the ui:param page title, needs to be done through the backing bean (as outlined here: http://stackoverflow.com/questions/20372421/setting-uiparam-conditionally).

**Comment by pdurbin** [comment]
> Do we really need all these different page titles?

Probably not. Vote to close.
