### ISSUE TITLE
Breadcrumbs should show context for dataverse sub pages

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#1284]
Now that we have sub pages for templates, themes, permissions,  the breadcrumb infrastructure needs to be improved to allow for this.

**Comment by scolapasta** [comment]
Infrastructure is there. Passing to @mheppler to add to all the pages.

**Comment by mheppler** [comment]
Pages that need ui:param showBreadcrumbs removed and f:viewAction initBreadcrumbs added:
- [ ] 404 - @rtreacy 
- [ ] apitoken - @pdurbin 
- [ ] datafilemap - @raprasad 
- [ ] dataset - @sekmiller 
- [ ] dataverse - @scolapasta 
- [ ] dataverse_template - @scolapasta 
- [ ] dataverseuser - @scolapasta 
- [ ] loginpage - @scolapasta 
- [ ] passwordreset - @pdurbin 
- [ ] shib - @pdurbin 
- [ ] template - @sekmiller 
- [ ] termsofuse - @sekmiller (not yet wired with the backend)

Additional pages that just need f:viewAction initBreadcrumbs added:
- [ ] manage-roles @michbarsinai (is this and old page or still part of the UI?)
- [ ] manage-templates @sekmiller 
- [ ] ThemeAndWidgets @ekraffmiller 

Pages already converted:
- [x] guestbook
- [x] manage-guestbooks
- [x] permissions-manage
- [x] permissions-manage-files

**Comment by scolapasta** [comment]
Breadcrumbs have been re added to dataverse and dataset page. There is still an issue with the create mode, but that is now tracked in a new issue, #1507, so I'm going to go ahead and pass this ticket back to @mheppler.

Let me know if you have specific question on any pages. (i also am modifying the previous comment with some notes and reordering as things I know are done)

**Comment by mheppler** [comment]
That should be everything. If there are any new pages that need breadcrumbs after this, they can be created in individual tickets.

**Comment by sbarbosadataverse** [comment]
Breadcrumb issues with dataset permissions:
permission
        dataset - crumbs only reads "permissions."
        files -resolves to crumbs "file permissions."

breadcrumbs with parent dataverse    
                                    general information (missing crumbs is any should exist)

**Comment by kcondon** [comment]
Additionally, I noticed:
-Some create pages do not say create in breadcrumb but others do:
create guestbook, create account do not 
create template, create dataset do
-API Token page has no breadcrumb, not sure if that is what was intended by the above list (remove from page).

**Comment by mheppler** [comment]
- [ ] Dataset Permissions
- [ ] Create Guestbook
- [ ] Create Account
- [ ] API Token (doesn't have "Account" in the breadcrumb, need more assistance to make that happen)

- General Information : this isn't it's own page, but it will be some day, and when it does, it can have it's own breadcrumb, until then, this is more difficult than what I can get done.

**Comment by posixeleni** [comment]
@kcondon would you be able to verify this for me?
