### ISSUE TITLE
Analysis: dvn-build not running models, http status 0 error, cross-origin error in firebug.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1286]
When running gamma model on build for fearonlaitin data with ccode as dep var, throws xmlhttprequest status is 0. local server limitation?  url too long?
indicating communication issue with rapache.

Checked config files and restarted apache, rserve and problem persists. Firebug reports this when running model, which in the past indicates trying to run http on https session.

urlcall out: https://dvn-build.harvard.edu/custom/zeligapp?solaJSON={"zdata":"fearonLaitinData.tab","zedges":[["country","ccode"],["ccode","cname"]],"ztime":[],"znom":[],"zcross":[],"zmodel":"gamma","zvars":["ccode","country","cname"],"zdv":["ccode"],"zdataurl":"https://dvn-build.hmdc.harvard.edu/api/access/datafile/28?key=043849b4-1a0f-48ff-b5cf-3b67891464a5","zsubset":[["",""],["",""],["",""]],"zsetx":[["",""],["",""],["",""]],"zmodelcount":0,"zplot":[],"callHistory":[]}
app_ddi.js (line 1393)
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://dvn-build.harvard.edu/custom/zeligapp?solaJSON={%22zdata%22:%22fearonLaitinData.tab%22,%22zedges%22:[[%22country%22,%22ccode%22],[%22ccode%22,%22cname%22]],%22ztime%22:[],%22znom%22:[],%22zcross%22:[],%22zmodel%22:%22gamma%22,%22zvars%22:[%22ccode%22,%22country%22,%22cname%22],%22zdv%22:[%22ccode%22],%22zdataurl%22:%22https://dvn-build.hmdc.harvard.edu/api/access/datafile/28?key=043849b4-1a0f-48ff-b5cf-3b67891464a5%22,%22zsubset%22:[[%22%22,%22%22],[%22%22,%22%22],[%22%22,%22%22]],%22zsetx%22:[[%22%22,%22%22],[%22%22,%22%22],[%22%22,%22%22]],%22zmodelcount%22:0,%22zplot%22:[],%22callHistory%22:[]}. This can be fixed by moving the resource to the same domain or enabling CORS.

**Comment by landreev** [comment]
I believe this is an orphan ticket; the hostname in the url above is missing "hmdc". 
I recall I pointed that out, and then it was working again. We just forgot to close this ticket.

**Comment by kcondon** [comment]
OK, can run models now. Closing
