### ISSUE TITLE
Ingest: clean up temp files from /tmp.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1287]
Ingest leaves a bunch of files with names like: columnBufferFile1042015997543016021bytes
They are not cleaned up and probably should be, otherwise it would become an ops issue.

**Comment by landreev** [comment]
easy.

**Comment by landreev** [comment]
All temp files should now be getting nuked, I believe. 
If you come across something that's still being left behind - let me know.

**Comment by kcondon** [comment]
@landreev Still seeing some left behind, passing back:
-rw-r--r--. 1 root   root     105000 Mar  4 09:27 tempTabfile.6450192626126296711.tab
-rw-rw-rw-. 1 rserve rserve   105291 Mar  4 09:27 dataverseTabData_.024285.tab
-rw-rw-rw-. 1 rserve rserve     5743 Mar  4 09:27 dataverseDataFrame_.024285.RData
-rw-r--r--. 1 root   root       5743 Mar  4 09:27 dataversePreprocess_024285.json
-rw-r--r--. 1 root   root     105000 Mar  4 10:59 tempTabfile.2540319461680981954.tab
-rw-r--r--. 1 root   root    2299204 Mar  4 11:36 tempTabfile.712009280122872738.tab
-rw-rw-rw-. 1 rserve rserve  2299204 Mar  4 11:37 dataverseTabData_.289007.tab
-rw-rw-rw-. 1 rserve rserve  2299204 Mar  4 11:42 dataverseTabData_.102960.tab
-rw-rw-rw-. 1 rserve rserve  2299713 Mar  4 11:43 dataverseTabData_.485189.tab
-rw-rw-rw-. 1 rserve rserve    54245 Mar  4 11:43 dataverseDataFrame_.485189.RData
-rw-r--r--. 1 root   root      54245 Mar  4 11:43 dataversePreprocess_485189.json
-rw-r--r--. 1 apache apache     1090 Mar  4 12:30 temp.tab
-rw-r--r--. 1 root   root    2299204 Mar  4 12:38 tempTabfile.5500510102758631202.tab
-rw-r--r--. 1 root   root    2299204 Mar  4 13:28 tempTabfile.850711319527494309.tab
-rw-rw-rw-. 1 rserve rserve  2299713 Mar  4 13:38 dataverseTabData_.043931.tab
-rw-rw-rw-. 1 rserve rserve    54245 Mar  4 13:38 dataverseDataFrame_.043931.RData
-rw-r--r--. 1 root   root      54245 Mar  4 13:38 dataversePreprocess_043931.json
-rw-rw-rw-. 1 rserve rserve  2299204 Mar  4 13:39 dataverseTabData_.121560.tab
-rw-rw-rw-. 1 rserve rserve  2299204 Mar  4 13:39 dataverseTabData_.032733.tab

**Comment by landreev** [comment]
Added code to delete all the R-related temp files.

**Comment by kcondon** [comment]
Still seeing some Rserve files in /tmp. Leonid asked to let it run for a few more days and then add the directory listing to this ticket. So, what I have for now is this:

-rw-rw-rw-. 1 rserve  rserve  2056195 Mar 16 17:04 dataverseTabData_.185870.tab
-rw-rw-rw-. 1 rserve  rserve  2055864 Mar 16 17:08 dataverseTabData_.819298.tab
-rw-rw-rw-. 1 rserve  rserve  2055864 Mar 16 17:09 dataverseTabData_.941511.tab
drwxr-xr-x. 2 root    root       4096 Mar 17 13:59 hsperfdata_root
drwxr-xr-x. 2 root    root       4096 Mar 17 13:59 fileinstall-3585197701240614016
-rw-r--r--. 1 root    root       1262 Mar 18 11:21 data6140141350892532601.csv
-rw-rw-rw-. 1 rserve  rserve     1127 Mar 18 11:23 dataverseTabData_.775754.tab
-rw-rw-rw-. 1 rserve  rserve   105291 Mar 18 12:02 dataverseTabData_.161029.tab
-rw-rw-rw-. 1 rserve  rserve    52355 Mar 18 13:10 dataverseTabData_.585737.tab
drwxr-xr-x. 2 rserve  rserve     4096 Mar 18 13:10 Rserv
-rw-r--r--. 1 root    root          0 Mar 18 13:38 data-5545168286184702994.tab
-

**Comment by kcondon** [comment]
Still happening. Some might be 2Ravens:

-rw-r--r--.  1 root    root        1262 Mar 18 11:21 data6140141350892532601.csv
-rw-rw-rw-.  1 rserve  rserve      1127 Mar 18 11:23 dataverseTabData_.775754.tab
-rw-rw-rw-.  1 rserve  rserve    105291 Mar 18 12:02 dataverseTabData_.161029.tab
-rw-rw-rw-.  1 rserve  rserve     52355 Mar 18 13:10 dataverseTabData_.585737.tab
-rw-r--r--.  1 root    root           0 Mar 18 13:38 data-5545168286184702994.tab
-rw-rw-rw-.  1 rserve  rserve    387837 Mar 18 16:42 dataverseTabData_.775005.tab
-rw-rw-rw-.  1 rserve  rserve    105000 Mar 18 19:58 dataverseTabData_.346567.tab
-rw-rw-rw-.  1 rserve  rserve    105000 Mar 18 19:58 dataverseTabData_.020517.tab
-rw-rw-rw-.  1 rserve  rserve    105000 Mar 18 20:00 dataverseTabData_.848801.tab
-rw-rw-rw-.  1 rserve  rserve      3646 Mar 18 20:02 Data.385289.RData
-rw-rw-rw-.  1 rserve  rserve      3566 Mar 18 20:02 dataverseDataFrame_.385289.RData
-rw-rw-rw-.  1 rserve  rserve      3646 Mar 18 20:06 Data.970028.RData
-rw-rw-rw-.  1 rserve  rserve      3566 Mar 18 20:06 dataverseDataFrame_.970028.RData
-rw-rw-rw-.  1 rserve  rserve      3646 Mar 18 20:13 Data.237508.RData
-rw-rw-rw-.  1 rserve  rserve      3566 Mar 18 20:13 dataverseDataFrame_.237508.RData
-rw-rw-rw-.  1 rserve  rserve    631189 Mar 19 14:54 Data.250450.RData
-rw-rw-rw-.  1 rserve  rserve    627917 Mar 19 14:54 dataverseDataFrame_.250450.RData
-rw-rw-rw-.  1 rserve  rserve   2299204 Mar 19 14:55 dataverseTabData_.198825.tab
-rw-rw-rw-.  1 rserve  rserve   2299204 Mar 19 14:56 dataverseTabData_.505829.tab
drwx------.  2 root    root        4096 Mar 19 18:03 RtmpfwtBtk
drwx------.  3 root    root        4096 Mar 19 19:03 Rtmpkhs7Ad
-rw-r--r--.  1 apache  apache      1837 Mar 19 19:06 libloc_171_9fbb5070ab307a43.rds
drwxr-xr-x.  2 apache  apache      4096 Mar 19 19:07 devtools6f452499fb4d
drwxr-xr-x.  2 apache  apache      4096 Mar 19 19:07 devtools6f44d1b40f3
drwxr-xr-x.  2 apache  apache      4096 Mar 19 19:07 devtools6f5a96552f3
drwxr-xr-x.  2 apache  apache      4096 Mar 19 19:07 devtools6f596b8f4f6
drwxr-xr-x.  2 apache  apache      4096 Mar 19 19:07 devtools6f587bbc28b8
drwxr-xr-x.  2 apache  apache      4096 Mar 19 19:07 devtools6f57775962ef
drwxr-xr-x.  2 apache  apache      4096 Mar 19 19:07 devtools6f92f680365
drwxr-xr-x.  2 apache  apache      4096 Mar 19 19:07 devtools6f946bc49689
drwxr-xr-x.  2 apache  apache      4096 Mar 19 19:07 devtools6f931652e001
-rw-r--r--.  1 root    root       24147 Mar 19 19:22 rep182056868264273228tmp
-rw-r--r--.  1 root    root       12600 Mar 19 19:22 rep3286603864332938070tmp
-rw-r--r--.  1 root    root        7159 Mar 19 19:22 rep6372189731697932767tmp
-rw-r--r--.  1 root    root        5931 Mar 19 19:22 rep2225431627292991552tmp
-rw-r--r--.  1 root    root       17699 Mar 19 19:22 rep1479460629562188092tmp
-rw-r--r--.  1 root    root        2422 Mar 19 19:22 rep769021786473070726tmp
-rw-r--r--.  1 root    root        1233 Mar 19 19:24 rep2371999897308332272tmp
-rw-r--r--.  1 root    root       28348 Mar 19 19:24 rep1811063261646650152tmp
-rw-r--r--.  1 root    root        2198 Mar 19 19:24 rep2795162115686140720tmp
-rw-r--r--.  1 root    root        2824 Mar 19 19:24 rep3174515415235184518tmp
-rw-r--r--.  1 root    root        5002 Mar 19 19:24 rep7996025070876752318tmp
-rw-r--r--.  1 root    root        2087 Mar 19 19:24 rep5945010830021776421tmp
-rw-r--r--.  1 root    root        2317 Mar 19 19:24 rep7201055904730876224tmp
-rw-rw-rw-.  1 rserve  rserve    234162 Mar 20 11:34 dataverseTabData_.365958.tab
-rw-rw-rw-.  1 rserve  rserve    105291 Mar 20 12:28 dataverseTabData_.394244.tab
-rw-r--r--.  1 apache  apache    105291 Mar 20 12:28 data_408a61cf-e03e-4b99-bad8-bd5307a105c1.tab
-rw-rw-rw-.  1 rserve  rserve      3646 Mar 20 12:29 Data.333258.RData
-rw-rw-rw-.  1 rserve  rserve      3566 Mar 20 12:29 dataverseDataFrame_.333258.RData
-rw-r--r--.  1 gdurand users  190718040 Mar 20 14:09 dvn-vm5.pdurbin.2015-03-20.sql
-rw-r--r--.  1 root    root      650165 Mar 20 14:29 master.zip
drwxr-xr-x.  8 root    root        4096 Mar 20 14:43 Zelig-master
-rw-r--r--.  1 apache  apache      2402 Mar 20 15:27 libloc_171_2b363be77582bd8f.rds
-rw-rw-rw-.  1 rserve  rserve   2299713 Mar 20 15:39 dataverseTabData_.838785.tab
-rw-r--r--.  1 apache  apache   2299713 Mar 20 15:39 data_82fb0ab3-4a21-4548-846c-9782c2269988.tab
drwx------.  2 rserve  rserve      4096 Mar 20 18:07 (null).97.97
-rw-rw-rw-.  1 rserve  rserve   2299204 Mar 20 18:11 dataverseTabData_.091227.tab
-rw-rw-rw-.  1 rserve  rserve   2299204 Mar 20 18:36 dataverseTabData_.387493.tab
-rw-rw-rw-.  1 rserve  rserve   2299204 Mar 20 18:37 dataverseTabData_.113188.tab
drwxr-xr-x. 15 rserve  rserve      4096 Mar 20 18:52 Rserv
-rw-rw-rw-.  1 rserve  rserve   2299204 Mar 20 18:52 dataverseTabData_.441177.tab
-rw-r--r--.  1 root    root       24149 Mar 20 19:32 rep6344801686511370334tmp
-rw-r--r--.  1 root    root       12600 Mar 20 19:32 rep2245079533725047641tmp
-rw-r--r--.  1 root    root        7167 Mar 20 19:32 rep5948091660377118652tmp
-rw-r--r--.  1 root    root        5931 Mar 20 19:32 rep4546445973564024207tmp
-rw-r--r--.  1 root    root       17699 Mar 20 19:32 rep7172574327490322975tmp
-rw-r--r--.  1 root    root        2422 Mar 20 19:32 rep7654587177370449932tmp
-rw-r--r--.  1 root    root        1233 Mar 20 19:33 rep6513631609375340808tmp
-rw-r--r--.  1 root    root       28429 Mar 20 19:33 rep7279515470467807180tmp
-rw-r--r--.  1 root    root        2198 Mar 20 19:33 rep5478633204920745296tmp
-rw-r--r--.  1 root    root        2824 Mar 20 19:33 rep1958443207941934481tmp
-rw-r--r--.  1 root    root        5002 Mar 20 19:33 rep4711924988127410321tmp
-rw-r--r--.  1 root    root        2087 Mar 20 19:33 rep5890980574070350132tmp
-rw-r--r--.  1 root    root        2317 Mar 20 19:33 rep2615574264938141424tmp
-rw-r--r--.  1 root    root       24149 Mar 20 19:44 rep3735985444150130489tmp
-rw-r--r--.  1 root    root       12600 Mar 20 19:44 rep6559960576982985155tmp
-rw-r--r--.  1 root    root        7167 Mar 20 19:44 rep2686613651219038220tmp
-rw-r--r--.  1 root    root        5931 Mar 20 19:44 rep170193260935881304tmp
-rw-r--r--.  1 root    root       17699 Mar 20 19:44 rep6802795461115170324tmp
-rw-r--r--.  1 root    root        2422 Mar 20 19:44 rep4713601810956623859tmp
-rw-r--r--.  1 root    root        1233 Mar 20 19:44 rep453564238268954308tmp
-rw-r--r--.  1 root    root       28429 Mar 20 19:44 rep1958026101949097517tmp
-rw-r--r--.  1 root    root        2198 Mar 20 19:44 rep432023269042049774tmp
-rw-r--r--.  1 root    root        2824 Mar 20 19:44 rep6230624781033927839tmp
-rw-r--r--.  1 root    root        5002 Mar 20 19:44 rep2263062850694508774tmp
-rw-r--r--.  1 root    root        2087 Mar 20 19:44 rep7798504766700148048tmp
-rw-r--r--.  1 root    root        2317 Mar 20 19:44 rep7910838820695841885tmp
drwxr-xr-x.  2 root    root        4096 Mar 20 19:55 hsperfdata_root
drwxr-xr-x.  2 root    root        4096 Mar 20 19:55 fileinstall--5741005145763973451
-rw-r--r--.  1 root    root       24149 Mar 20 19:57 rep8201622948285849116tmp
-rw-r--r--.  1 root    root       12600 Mar 20 19:57 rep2457132124418597478tmp
-rw-r--r--.  1 root    root        7167 Mar 20 19:57 rep8667526869041175659tmp
-rw-r--r--.  1 root    root        5931 Mar 20 19:57 rep5777461719455836005tmp
-rw-r--r--.  1 root    root       17699 Mar 20 19:57 rep7930646112603732568tmp
-rw-r--r--.  1 root    root        2422 Mar 20 19:57 rep8805421674510979560tmp
-rw-r--r--.  1 root    root        1233 Mar 20 19:57 rep2656593665124311647tmp
-rw-r--r--.  1 root    root       28429 Mar 20 19:57 rep5726016013314774090tmp
-rw-r--r--.  1 root    root        2198 Mar 20 19:57 rep7314415081203469512tmp
-rw-r--r--.  1 root    root        2824 Mar 20 19:57 rep250319582522728288tmp
-rw-r--r--.  1 root    root        5002 Mar 20 19:57 rep8207346857971323553tmp
-rw-r--r--.  1 root    root        2087 Mar 20 19:57 rep4839984145957950197tmp
-rw-r--r--.  1 root    root        2317 Mar 20 19:57 rep6283961104808636223tmp

**Comment by kcondon** [comment]
@scolapasta Not sure why you gave this back

**Comment by landreev** [comment]
@kcondon 
Gustavo and I spoke about this one. He meant to move it back into beta15, for me. But he may have assigned it to you in the process, by mistake. 
I'll grab it...

**Comment by landreev** [comment]
So, I spoke about this to Gustavo. 
I proposed that for these files, that are TwoRavens and Rserve-related, we stick with the DVN 3.* approach - keep the temp files and rely on the tempwatch to clear the directory. I feel that it could be useful for debugging purposes, particularly so for working out the integration between the dataverse and TwoRavens. So basically this is staying as is for 4.0.
