### ISSUE TITLE
password complexity message after successful login

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#1291]
Not sure what the user is supposed to do next.  See screenshot.

(1) Logged in successfully with password "admin" (local test version)
(2) Received warning message:
 ```Please enter a 6 character length password with at least one characters and one number```
(3) There is no action to be taken regarding the message. 
(fyi: made this a new ticket b/c **Log in was successful**)

related: #1032 
![account_-_root_dataverse](https://cloud.githubusercontent.com/assets/1036060/5525751/c017b0b8-89b8-11e4-86cd-b59937bb6208.png)

**Comment by eaquigley** [comment]
Decision made to just delete this message so there is no longer an error message saying, "Please enter a character length..."

**Comment by kcondon** [comment]
Message no longer appearing. Closing
