### ISSUE TITLE
Consistency: API token vs. key

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#1293]
In the API we use `key=1234` but we also use the term "token" in the UI and the backend.

I'm the one who suggested at https://github.com/IQSS/dataverse/issues/459#issuecomment-51400205 using the term "token" based on GitHub's "personal API tokens": https://github.com/blog/1509-personal-api-tokens

Sometimes I wonder if "key" is better. When we get around to implementing OAuth I'm sure we'll just use its terminology.

For now, at least, we should be consistent.

**Comment by pdurbin** [comment]
In the "2016-10-18 Meeting and demo about OAuth and ORCID login" meeting (notes at https://docs.google.com/document/d/1Lja6sqG0Ljg2Q6suoMJbYr3J01DTpw6HkgvRwdbEDXQ/edit?usp=sharing ) I asked @michbarsinai if we (he) had learned anything about OAuth that will help us someday use OAuth for API tokens instead of our existing strings. It sounds like not. Switching from our existing strings (UUIDs) to something else would be a different activity, fairly unrelated.

**Comment by michbarsinai** [comment]
Just to clarify, OAuth tokens are characterized by the way users obtain them and by how they behave. UUID is a way of generating (probably) unique strings without coordinating at the software level. Either unrelated or I don't understand the question.

For the record, ORCiD uses UUID strings as its OAuth tokens:

    "access_token":"89f0181c-168b-4d7d-831c-1fdda2d7bbbb"

(From https://members.orcid.org/api/tutorial-retrieve-orcid-id)

**Comment by pdurbin** [comment]
@michbarsinai it's likely that I'm misunderstanding what users want but check out a comment by @rliebz at http://irclog.iq.harvard.edu/dataverse/2015-04-20#i_18678 about OAuth tokens. Another example, perhaps more complete, comes from the "2015-06-10 Dataverse Authentication Breakout Session" notes at https://docs.google.com/document/d/17TI2RLqdntd5vnrygDrFgYNNmqb_eoTdSFita-L1Azk/edit?usp=sharing where Arturo Covarrubias ( @a-covar ), CTO of Nebula.io asked about OAuth tokens and came up to me afterwards as well. I wrote, "OAuth for Dataverse, with authorization for specific account use and revocable keys. Interest from http://nebulab.io "

**Comment by pdurbin** [comment]
Fixed in 66c30c7. Closing.
