### ISSUE TITLE
Copyright: Change from 2014 to 2015

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1295]
For future, look for a way to automate this.

**Comment by eaquigley** [comment]
@mheppler will manually change this to 2015 and later look for a way to automate it. QA after testing to make sure it says 2015, please pass this ticket back to @mheppler and change the Milestone to be Post 4.0.

**Comment by mheppler** [comment]
Copyright © 2015, The President & Fellows of Harvard College

**Comment by esotiri** [comment]
verified
