### ISSUE TITLE
Have API add NA for missing required fields for harvesting import

### ISSUE THREAD

**Issue by ekraffmiller** [IQSS/dataverse#1296]
There are metadata fields that are required by Dataverse, which won't necessarily be available in harvested datasets.  For these fields, we will assign the value "N/A" to the metadata field.

**Comment by pdurbin** [comment]
We do this alread in the addDatasetSubject method of https://github.com/IQSS/dataverse/blob/master/src/main/java/edu/harvard/iq/dataverse/api/datadeposit/SwordServiceBean.java

Please feel free to move that method to a more central place where various APIs can call into it.

**Comment by pdurbin** [comment]
> For these fields, we will assign the value "N/A" to the metadata field.

Right, and http://guides.dataverse.org/en/latest/api/sword.html reflects this, saying, '“Subject” is automatically populated with “N/A”' but I'm confused about how this works. Let's say I create a dataset with SWORD and later I go in to the GUI to change the title. I change the title and click "Save Changes" at the top of the page and I get a validation error (which I can't even see until I scroll down) that says "Subject is required." All I can think is, "If Subject is required, why was I allowed to create a dataset via SWORD?"

I guess this is a question for @scolapasta who changed the behavior from what @posixeleni and I talked about and implemented in #921 which was to populate Subject with "Other". Now "N/A" is used.

My design principle with SWORD is that SWORD should allow you to create a completely legitimate dataset. You shouldn't see an error if you want to change the title with the GUI.

**Comment by scolapasta** [comment]
Assigning to @ekraffmiller to resolve the issue which this was created for.

But to answer @pdurbin, when you create via Sword we allow you to create a dataset with fields that normally validate. But if you then go through UI, you are expected to add the additional info, because we can get it there.

**Comment by ekraffmiller** [comment]
Talked to Phil about this and we agreed that the code is fine as is - we don't currently have a need for a centralized method for assigning NA values.

**Comment by pdurbin** [comment]
I'm fine with not having a centralized method for assigning NA values but I still strongly believe that SWORD should be capable of creating a fully legitimate dataset, not one that yield validation errors when you try to change the title. I discussed this will @mcrosas and @eaquigley last week and I guess the plan generally is to put effort into #769.
