### ISSUE TITLE
Add additional Advance Search + Facetable fields for Social Science block

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#1298]
Due to having moved certain fields out of the Social Science block and into Citation or Geospatial blocks, @eaquigley identified that there is now only one advance search field in the social science block: "Universe". Additionally there are no facetable social science fields. This looks awkward to users.

In the social_science.tsv file I will add the following fields to have advancedSearchField and facetable booleans set to TRUE:

* unitOfAnalysis
* timeMethod
* responseRate

@scolapasta will help me make these changes in the db so that we won't need to do a schema.xml update / db drop.

Usability testing this block in Advance Search can help us get more feedback on what other fields we should make advance searchable.

**Comment by posixeleni** [comment]
@kcondon if you do a db drop in your local install you should be able to see these changes. Let me know if you have any questions.

**Comment by kcondon** [comment]
OK, fields appear in advanced search and in soc sci facets group. All functionality works. Closing.
