### ISSUE TITLE
Exporting Metadata Google Doc into Documentation (User Guide)

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#130]
---

Author Name: **Elizabeth Quigley** (@eaquigley)
Original Redmine Issue: 3539, https://redmine.hmdc.harvard.edu/issues/3539
Original Date: 2014-02-07
Original Assignee: Eleni Castro

---

The metadata tables currently found in Google Docs should be integrated into documentation so we have a record of it in case Google Docs is down or disappears.

https://docs.google.com/spreadsheet/ccc?key=0AjeLxEN77UZodHFEWGpoa19ia3pldEFyVFR0aFVGa0E&usp=sharing

It should be saved as a plain text format (csv or tsv) and committed into git *before* the branch is tagged as 4.0 per our release process http://thedata.harvard.edu/guides/dataverse-developer-main.html#release

**Comment by posixeleni** [comment]
Added links to .tsv versions of the files. Closing this ticket.
