### ISSUE TITLE
Add "Explore" option for FITS, .wtt and other astronomy image files to WorldWide Telescope

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#1300]
@mcrosas requested that I create this ticket so that we work on adding an "Explore" option for astronomy image and FITS files that opens the image or FITS file in [WorldWide Telescope](http://www.worldwidetelescope.org/).

The FITS files will be easy to identify given their file extension and header information.

Image files (e.g., png, etc) will need to be able to tagged as "astronomy image files" in the header. @posixeleni will talk to Gus about how we can easily identify these files.

**Comment by augustfly** [comment]
watching to jump in later...

**Comment by raprasad** [comment]
Moved this to 4.3.  After meeting with Gus, there is significant ingest work for the FITS->PNG with embedded metadata conversion.

**Comment by raprasad** [comment]
This will be part of modular ingest to accommodate the needed FITS transformations.

**Comment by aagoodman** [comment]
Asking Gus--is there a status update on this? Alyssa & Julie

**Comment by djbrooke** [comment]
@aagoodman, I'll tag @augustfly so that he gets a notification.

As far as the Dataverse side, this is not something that is currently on our roadmap.

**Comment by djbrooke** [comment]
I'm going to close this. Any explore tools can be added using the external tools feature: http://guides.dataverse.org/en/latest/installation/external-tools.html. If there's interest and resources available we'll be happy to assist!

**Comment by pdurbin** [comment]
Absolutely! I re-wrote the docs and added a "Building External Tools" page in the API Guide for Dataverse 4.17. I hope it helps! We are always happy to help external tool authors! We want all the tools. :smile:
