### ISSUE TITLE
Should we require dataverse creators to choose their own alias?

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#1303]
From Ben at DANS:

I noticed that I am required to provide a URL for new dataverses (I remember it used to be called an alias). The label suggests I need to provide a full URL, but the hover text makes clear it is still the 'short name that will be used in the URL'.

However, I don't like that it is required to choose an alias/URL/..., as it puts the responsibility of finding a good short _untaken_ label with every dataverse creator. Can it be made optional, please?

**Comment by bencomp** [comment]
If dataverse creators are required to choose an alias/identifier, it must not be allowed to consist of digits only, or it will break the API access: #1461.

**Comment by pdurbin** [comment]
#1461 was fixed a while ago. I copied the comment above about having to choose an alias into #2900 in an effort to consolidate issues. I'm closing this one.
