### ISSUE TITLE
Custom Metadata Inputs -- Value Format Watermarks Needed

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1304]
I noticed that in some custom metadata block fields need input watermarks, letting a user know that a special format is required/allowed -- ie, integer, html, etc.

It looks like "LastName, FirstName" is used, and "YYYY-MM-DD", but there are more that are needed and should be added.

For example, in the Social Science and Humanities Metadata block, the Target Sample Size input requires an integer, so that field should have a watermark that explains that.

**Comment by mheppler** [comment]
Related #1253.

**Comment by posixeleni** [comment]
I can enter these into the TSV metadata blocks.

**Comment by posixeleni** [comment]
Adding watermarks into the Social Science Metadata Block for integer.
Adding watermarks into the Astrophysics metadata block for integers and floats.

**Comment by kcondon** [comment]
OK, watermarks are there, closing
