### ISSUE TITLE
Metadata Updates for beta 11 push

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#1305]
With the beta 11 push I need to put in some metadata updates which will require:

1) Schema.xml update
2) DB Drop. Note: When we push the changes to demo we will have to recreate the dropped dataverses, and datasets using @ekraffmiller DDI XML import file.

For the schema.xml updated @pdurbin please review the changes and let me know if you have any questions/concerns:

**Citation Metadata Block**
* Minimal changes to watermark text (typo) for Distributor Logo URL and Producer Logo URL https://github.com/IQSS/dataverse/commit/bb07f2fea58dec22888f518f3bf7c92fd794660d

**Geospatial Metadata Block** NO CHANGES

**Social Science Block**
1. Added new: Notes compound field at the bottom. (makes notes DDI-Lite compliant)
2. Added watermarks for the integer value. See #1304 
3. Changed some Booleans for Facetable and Advance Searchable from FALSE to TRUE. See #1298 for more details.

**Life Sciences Block** (see #1115)
1. Added two **new** free-text fields: "Other Organism" and "Other Measurement Type"
2. Adding two **new** controlled vocabulary fields: "Technology Type" and "Technology Platform" 
3. Updated the controlled vocabularies for: Organism, and Measurement. These have been updated to include more high-level terms based on feedback from ISA-Tab and Caroline Shamu (Harvard Medical School).

**Astrophysics Block** 
1. Added watermarks for integer and float values. See #1304

**GSD Block** See #1137 
1. **New** field added: Accreditation, ~~Notes~~
2. Changed Display Name from "Program Brief" to "Program / Brief" and changed fieldtype to textbox.
3. Set Advance Searchable Boolean to TRUE: Student Name, Student's Program of Study, Course Name, Faculty Name, Semester / Year, Faculty Recommendation, Site Type, Program / Brief, Tags, Prize
4. Set Facetable Boolean to TRUE: Faculty Recommendation
5. Updated controlled vocabulary list for: Faculty Name and Course Name to make sure we migrate all the old cvv's properly.

**Journal Metadata Block**
For field disambiguation between the metadata blocks I changed/prefaced each field name in this block with the word "journal". See this ticket for more info: https://github.com/IQSS/dataverse/issues/1166#issuecomment-65246195 

**NEW Block: PS Replication Dataverse Block (PSRI)** See #1215 
This Dataverse had custom fields in 3.6. Added new block to file: setup-datasetfields.sh

**NEW Block: ARCS Dataverse Block*** See #1213 
This Dataverse had custom fields in 3.6. Added new block to file: setup-datasetfields.sh

**Comment by posixeleni** [comment]
@pdurbin to avoid messing up other peoples code I checked this into a new metadata-beta11 branch. please let me know if i can help with anything.

**Comment by pdurbin** [comment]
@posixeleni I just merged your commits as well as a commit containing a new Solr schema.xml (which everyone should update to) with master.

Passing to QA.

**Comment by kcondon** [comment]
@posixeleni @pdurbin  OK, mostly looks good with a few questions/ issues:
-Life Science block says field name Other Organism in ticket, similar to existing Organism field but in app says Other Organisms, OK?
-There is supposed to be a new notes field in the GSD block but it is missing.
-All required fields in GSD block now not required. This was not mentioned, intentional?
-Can search on "yes" but not "no" for the new blocks. This is not a major deal but weird. Maybe on the word filter list?

**Comment by posixeleni** [comment]
@kcondon here are some answers to your questions:
-Life Science block says field name Other Organism in ticket, similar to existing Organism field but in app says Other Organisms, OK?
[Eleni: Thanks for catching this. Will fix typo in field name in tsv and check this in for beta12 to make sure it is consistent.]
-There is supposed to be a new notes field in the GSD block but it is missing.
[Eleni: Please disregard. This notes field would be redundant since we already have Notes in Citation. Sorry for the confusion]
-All required fields in GSD block now not required. This was not mentioned, intentional?
[Eleni: Yes this was intentional since Janina would like to be able to easily change this setting in the UI rather than in the backend.]
-Can search on "yes" but not "no" for the new blocks. This is not a major deal but weird. Maybe on the word filter list?
[Eleni: Should we create a separate ticket for this one? Not sure how I can fix this issue if it is index related.]

**Comment by posixeleni** [comment]
@kcondon fixed the field displayName typo for Other Organism (removed the "s" at the end of Other Organism). This should solve this ticket. @pdurbin dont think this needs a schema.xml just a db drop.

**Comment by pdurbin** [comment]
> @pdurbin dont think this needs a schema.xml

@posixeleni yep, I agree, based on what I'm seeing at f3daf19c3df552c8ab2d8bbdcba04ace2f691826

**Comment by kcondon** [comment]
OK, fixed, closing.
