### ISSUE TITLE
Dataverse contact email uniqueness 

### ISSUE THREAD

**Issue by esotiri** [IQSS/dataverse#1306]
Opening this per @scolapasta comment on https://github.com/IQSS/dataverse/issues/1251

>It is working ok to add additional contact email to the dataverse. However it lets me add same email multiple times. Do we want to check for uniqueness? and say something that email already exists.

**Comment by mheppler** [comment]
Still possible as of 5.3

<img width="579" alt="Screen Shot 2021-02-11 at 11 03 24 AM" src="https://user-images.githubusercontent.com/687227/107662963-d3b97280-6c58-11eb-9771-42070a69a235.png">
