### ISSUE TITLE
API Dataset : Create dataset via native API not working anymore

### ISSUE THREAD

**Issue by esotiri** [IQSS/dataverse#1307]
Until yesterday noon time, I used to be able to do the following:
1.  Get json

``
curl -X GET http://$host/api/datasets/11?key=$token
``
2. create dataset via api using the json (format, remove the OK header part)

``
curl -H "Content-type:application/json" -X POST -d @dset2015.json https://$host/api/dvs/test2015/datasets/?key=$token
``
3. update metadata

``
curl -H "Content-type:application/json" -X PUT -d @dset2015.json https://$host/api/datasets/24/versions/:draft?key=$token
``

Now I can't create the dataset.

**Comment by ekraffmiller** [comment]
Changed to JSON test data to match the parsing code - "initialVersion" is changed to "datasetVersion"

**Comment by esotiri** [comment]
issue resolved.
