### ISSUE TITLE
Deaccessioned Dataset: Suppress License and Terms Tab

### ISSUE THREAD

**Issue by sekmiller** [IQSS/dataverse#1309]
When a dataset version is deaccessioned we hide the metadata and files tab.  We need to do the same for the License and terms tab

**Comment by sekmiller** [comment]
Fix for this has been checked in.  To test add a dataset, publish, then deaccession.  You should no longer see the license tab...

**Comment by kcondon** [comment]
Tab is not displayed for deaccessioned versions but remains for all others, closing.
