### ISSUE TITLE
Download button issues

### ISSUE THREAD

**Issue by esotiri** [IQSS/dataverse#1310]
1. Download button shows:
0 files in the dataset - should not show
1 files in the dataset - should not show
more than 1 files - this is ok

2. Download button does nothing (no download action)
when files are selected > download selected is grayed out
when files are not selected > all files from this dataset is not grayed out but no action

This behavior is consistent when dataset is published or not.

**Comment by scolapasta** [comment]
Assigning to @mheppler for rendering rules.

**Comment by mheppler** [comment]
This functionality is not yet done being done developed.

Leonid still owns this ticket -- Add download-multiple-files-as-one-zip-archive, similar to 3.6.* #338.

See my comment, "Added static download button..."

**Comment by landreev** [comment]
@eaquigley ,
@scolapasta ,
Do we really want to have the "download all the files in the dataset" option?

**Comment by eaquigley** [comment]
@landreev @scolapasta couldn't this also be accomplished by using the checkbox to select all files in the dataset and then click the download button? if so, i'm not sold on needing a separate "download all the files in the dataset" option?

**Comment by landreev** [comment]
@scolapasta @eaquigley  - yeah, that's how we've been doing it in 3.*; a one-click way to select all checkboxes, then download the selection.

**Comment by eaquigley** [comment]
@landreev cool, i'd keep it the same then for 4.0. thanks!

**Comment by esotiri** [comment]
Reviewing the issues listed above: 
1. Download button shows:
0 files in the dataset - fixed
1 files in the dataset - fixed
more than 1 files - ok

2. Download button action
when one file is selected > actions grayed out > it should enable 'download selected'
when more than one file is selected > download selected is ok in a zip
when files are not selected > actions grayed out - ok

**Comment by esotiri** [comment]
I have a question if this should be ok?

when one file is selected > actions grayed out > should it enable 'download selected'

**Comment by esotiri** [comment]
opened https://github.com/IQSS/dataverse/issues/1373, resolving this issue.

**Comment by landreev** [comment]
@esotiri 
I originally implemented it like this on purpose - the rationale being, it's just stupid to download just one file in a file bundle; but we eventually decided it was ok. So you should be seeing the download link enabled now, even if there's only 1 file selected.
