### ISSUE TITLE
Permissions: Dataverse Role Description Character Count

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1313]
In #507, @mheppler said, "Removed all character count code from the dataverse description workflow.

Found that there is also a 1000 character limit on the descriptions for roles. I removed all references to those, but then I was not able to create a new role when I had a description over 1000 characters. I replaced all the code, and could create a role using only 10 characters. Passing to @scolapasta to look into this further (whether he likes it or not)."

and @scolapasta responded with, OK, this is an easy change as it is just adding @Column(columnDefinition = "TEXT") to the db.

But question - while I think all text areas should be unlimited characters, should the dataverse role really be a textarea? We are displaying these descriptions on the page and what seems to be a limited area, and this type of description seems like it should be shorter. Should we mae this a regular text box and limit to 255?"

Yes, we should make this a regular text box.

**Comment by scolapasta** [comment]
OK, I made this a regular text input. I think it should be larger than the name and identifier fields, so I used size="100", but am passing to Mike so he can make it look better.

**Comment by scolapasta** [comment]
Also added validation to limit to 255 characters.

**Comment by mheppler** [comment]
Cleaned up sizing of the description text input field on the Add/Edit Role popup.

**Comment by kcondon** [comment]
OK, throws error at 255 but no message:
 Validation Error – Required fields were missed or there was a validation error. Please scroll down to see details. 

And there is nothing else

**Comment by scolapasta** [comment]
Yes, this is already there as part of the  messaging issue: #1187 

Can we close this since we have that? (if we need to add this as a needed message up top?)

**Comment by eaquigley** [comment]
@scolapasta & @kcondon close away!

**Comment by kcondon** [comment]
Closing, added comment to other ticket
