### ISSUE TITLE
Dataset Destroy: Index all needed for destroyed published dataset 

### ISSUE THREAD

**Issue by esotiri** [IQSS/dataverse#1316]
After running destroy command on a published dataset, the dataset cart is still visible, until running index all.

**Comment by pdurbin** [comment]
Previously the DestroyDatasetCommand wasn't deleting Solr IDs for:
    
- published datasets
- deaccessioned datasets
- published files

Now it is. Passing to QA. If it's helpful, my script for testing: https://github.com/IQSS/dataverse/blob/53f5e52dbf97a08d3099f8b8992f229bbf68023f/scripts/search/tests/destroy-dataset-spruce1

**Comment by michbarsinai** [comment]
This happened to me when the solr index was out-of-date. Maybe we should add a test for the dataverse being `null`, and then issue a -reindex message, while displaying an "index being updated" fragment in the UI.
