### ISSUE TITLE
Files: Edit File Categories Help Text

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1318]
Need help text for the Edit File Categories pop up:

Select existing categories or create new categories to describe your files. Creating a new category will add it as a category option for all files in this dataset. Each file can have more than one category.

**Comment by mheppler** [comment]
Added help text to the Edit Categories popup from the Upload + Edit Files page, via the bundle.

UI cleanup on this popup will be addressed in another ticket, that I've yet to create for myself.

**Comment by kcondon** [comment]
Help text added, closing
