### ISSUE TITLE
Notifications provide regular e-mail with some stats to users

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#132]
---

Author Name: **Gustavo Durand** (@scolapasta)
Original Redmine Issue: 3541, https://redmine.hmdc.harvard.edu/issues/3541
Original Date: 2014-02-07

---

Based on e-mail from Merce and Gary:

I believe this was already part of a ticket on notifications - at least we had discuss it in the notifications meetings.

Could you enter a ticket for 4.0 if there isn't one?  This should be relatively easy and it's gives a lot to researchers.

Thanks

Merce

---------- Forwarded message ----------
From: Gary King king@harvard.edu
Date: Fri, Feb 7, 2014 at 7:10 AM
Subject: Fwd: Your DASH Statistics Update

We should have this or something like it for dvn (tho with easy ways of changing the frequency of emails, and one email per data set user, not per dataset). It would draw people back on to dvn. We could also include little ads in the emails about what else we are doing or might be of interest to them.

---

Gary King

---

Redmine related issue(s): [2942](https://redmine.hmdc.harvard.edu/issues/2942)

---

**Comment by kcondon** [comment]
Treating the general issue of reports as a separate issue: #3099

**Comment by pdurbin** [comment]
@mercecrosas are you still interested in this feature?
