### ISSUE TITLE
Featured Dataverses: Boxes need to be same size

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1322]
From General UI Doc: https://docs.google.com/document/d/1VXac5Eqx1LDVWvMogf4EYVfxv-9gIavgAnL4x_esiTI/edit

@mcrosas comment: Boxes for each dataverse in carousel should have same size.

**Comment by mheppler** [comment]
Added jQuery matchHeight plugin to apply an even height to all the Featured Dataverses on the Dataverse page.

**Comment by eaquigley** [comment]
Tested this with multiple dataverses and they were all the same size. Closing ticket.
