### ISSUE TITLE
Citation: DOI should be a working link

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1323]
From General UI doc: https://docs.google.com/document/d/1VXac5Eqx1LDVWvMogf4EYVfxv-9gIavgAnL4x_esiTI/edit

**Comment by sekmiller** [comment]
DOI on DS card is now a working link. @mheppler, the css in the citation block is interfering
 with the display, can you take a look search-include-fragment around lines 624-625...

**Comment by mheppler** [comment]
Fixed DOI links in the citation block in file search/browse cards on the Dataverse page.

@sekmiller -- it wasn't a CSS issue. The h:outputText for the styled citation block was missing an escape="false" attribute, in order to render HTML in the value on the page as HTML and not text.

**Comment by eaquigley** [comment]
DOI appearing as a working link in the search/browse cards as well as on dataset pages. Closing ticket.
