### ISSUE TITLE
Data Citation: Download Data Citation Button move into Data Citation Block

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1324]
From General UI doc: https://docs.google.com/document/d/1VXac5Eqx1LDVWvMogf4EYVfxv-9gIavgAnL4x_esiTI/edit

**Comment by mheppler** [comment]
Moved Download Citation button into citation block and bumped it down in size.

**Comment by kcondon** [comment]
Button moved, smaller, works, closing.
