### ISSUE TITLE
Button Groups: Consistency Needed

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1325]
From General UI doc: https://docs.google.com/document/d/1VXac5Eqx1LDVWvMogf4EYVfxv-9gIavgAnL4x_esiTI/edit

- [x] Consistent spacing, margins, background colors to button groups on all pages and forms.
- [x] Some “action item” buttons in confirmation pop ups are green and some aren’t. Need consistency with this.
- [x] For "plus" and "minus" buttons, remove "Record" from the tooltip.

**Comment by mheppler** [comment]
Related to and can be tested in conjunction with #1570.

**Comment by mheppler** [comment]
Sending both the buttons and tooltips tickets to QA. I have spent most of this week going through the entire site, and cleaning up as much as I can find. If there are any additional tickets related to these two issues, they should have individual tickets.

**Comment by eaquigley** [comment]
Buttons, tooltip for Add & Delete look great. Did not find any green buttons. Closing ticket.
