### ISSUE TITLE
Contact Buttons: Change to only be the email icon

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1326]
From General UI doc: https://docs.google.com/document/d/1VXac5Eqx1LDVWvMogf4EYVfxv-9gIavgAnL4x_esiTI/edit

**Comment by mheppler** [comment]
Switched Email Contact buttons on datasets and dataverses to just an icon.

**Comment by kcondon** [comment]
Buttons are now icons, closing
