### ISSUE TITLE
Contact Forms: Add Captcha to Prevent Spam

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1327]
Due to the amount of spam coming in through the Feedback Contact Form on dataverse 4.0, we need to implement a captcha to prevent this from happening when 4.0 goes public.

**Comment by scolapasta** [comment]
discussed with @eaquigley and it would be ok to do something other than captcha, as long as we remove spam (i.e. solve a simple math problem)

**Comment by eaquigley** [comment]
Decided to use an alternate method instead of captcha. We decided to use @scolapasta 's suggestion to use a simple math question for this.

**Comment by ekraffmiller** [comment]
completed as part of ticket #1502

**Comment by kcondon** [comment]
OK, formula in place, varies, complains about wrong answers. Closing
