### ISSUE TITLE
Search API: improve documentation

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#1328]
@eaquigley you asked me to create a ticket for you to improve the Search API documentation by adding links, etc. This is that ticket. :)

I just did a build so http://guides.dataverse.org/en/latest/api/search.html is current.

**Comment by eaquigley** [comment]
@pdurbin the linking is in and I can verify it working once you kick off a build!

**Comment by eaquigley** [comment]
Linking worked. Passing to QA to verify that per_page, start, show_relevance, show_facets, and fq have links to the appropriate sections in the example part.

**Comment by kcondon** [comment]
Links are good, closing
