### ISSUE TITLE
Optimize Bootstrap + jQuery Libraries

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1330]
There seems to be an excessive amount of Bootstrap files in the project code, including over 30 copies of bootstrap.min.css, largely attributed to the documentation themes from Sphinx. (See attached.)

![screen shot 2015-01-13 at 10 43 57 am](https://cloud.githubusercontent.com/assets/687227/5723353/82cc7d0a-9b11-11e4-93f2-0281e2903088.png)

**Comment by pdurbin** [comment]
As @mheppler and @cchoirat and I discussed, a good first step would be to install the Sphinx bootstrap files on to the server we use to build the Dataverse docs (which isn't a server we have direct control over). Then we can remove the files from the repo.

**Comment by pdurbin** [comment]
> a good first step would be to install the Sphinx bootstrap files on to the server we use to build the Dataverse docs (which isn't a server we have direct control over)

I've started a (private) Google Doc about this and other concerns I have with our internal build tool (Jenkins) and process: https://docs.google.com/a/harvard.edu/document/d/1Rvkt5ZL7puGmq6Q1prdOgy9S3nNtc28tcb4HnztmbOY/edit?usp=sharing

**Comment by pdurbin** [comment]
As @scolapasta @eaquigley and I discussed, I went ahead and opened [a ticket](https://help.hmdc.harvard.edu/Ticket/Display.html?id=192221) about installing sphinx_bootstrap_theme 0.4.0 on the Jenkins server.

I noticed that we do seem to be modifying those files though I think we'll need to move those files to some other directory when we remove the module from our code.

@mheppler can you please look at https://github.com/IQSS/dataverse/tree/master/doc/sphinx_bootstrap_theme/bootstrap/static/images ? Should these images live someplace else? I'm passing this ticket to you.

@raprasad same question but for your Javascript at https://github.com/IQSS/dataverse/tree/master/doc/sphinx_bootstrap_theme/bootstrap/static/js

**Comment by pdurbin** [comment]
@mheppler as I mentioned in this morning's meeting, I think this ticket represents a non-essential cleanup task that could be deferred until after Dataverse 4.0 ships.

**Comment by raprasad** [comment]
Use grunt to concat and minify the non-primefaces js and css:

http://stackoverflow.com/questions/13713273/how-to-concatenate-and-minify-multiple-css-and-javascript-files-with-grunt-js-0

https://egghead.io/lessons/grunt-minifying-your-output-with-grunt-uglify

\cc @mheppler

**Comment by mheppler** [comment]
In the /doc/sphinx_bootstrap_theme directory there were unused directories for bootstrap-2.3.2, bootswatch-2.3.2, bootswatch-3.1.0. When I remade the the docs locally, there were now less Bootstrap files in the /doc/sphinx-guides/build directory. You can see in the screenshot below, the number of duplicate files went from nearly 30 files to 3 which is the number that should be expected.

![screen shot 2015-11-24 at 1 06 35 pm](https://cloud.githubusercontent.com/assets/687227/11376134/03553528-92ad-11e5-9057-fbf3fff295dc.png)

**Comment by pdurbin** [comment]
Here's the build from the commit (2598873) @mheppler made: https://build.hmdc.harvard.edu:8443/job/guides.dataverse.org-4.2.2/22/ . They can be verified at http://guides.dataverse.org/en/4.2.2

**Comment by kcondon** [comment]
Docs are working, closing.
