### ISSUE TITLE
Permissions: Can't download a file anonymously from published dataset where file permissions were not touched

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#1331]
As I mentioned to @eaquigley @kcondon and @landreev I just did the following on dvn-build:

- sign up
- create dataverse (in root)
- publish newly created dataverse
- create dataset (in newly created dataverse)
- upload file (no attempts were made to restrict the file)
- publish dataset
- log out
- try to download file

To my surprise, when I then browse to [that dataset](https://dvn-build.hmdc.harvard.edu/dataset.xhtml?id=2208&versionId=600) and try to download the file I get a Glassfish error that says "HTTP Status 401 - Unauthorized... This request requires HTTP authentication."

![glassfish_server_open_source_edition_4 1_-_error_report_-_2015-01-13_11 57 44](https://cloud.githubusercontent.com/assets/21006/5724828/56ecf7cc-9b1c-11e4-90b5-40ed1308cc9e.png)

In addition, when looking at the dataset anonymously (before downloading the file) I noticed that I don't see the preview image and it server.log it says "edu.harvard.iq.dataverse.api.Access... Unauthenticated access: No guest access to the datafile".

@eaquigley asked me to create this ticket. It seems to add up to a change in file permissions so I'm giving it to @scolapasta .

**Comment by scolapasta** [comment]
If a file is not restricted and and in a published dataset, permissions should not be checked.

@landreev can you take a look at the api?

**Comment by landreev** [comment]
@gdurand, 
per our conversation, I'm bouncing it back to you, for now; 
this is the perm service call that the access API is making: 

permissionService.on(df).has(Permission.DownloadFile)

(the user is not explicitly supplied here; on(DataFile) will extract the user from the session; and assume guest access if it's null). 

For API token auth, I get the user from the token, then call
permissionService.userOn(user, df).has(Permission.DownloadFile)

**Comment by raprasad** [comment]
/cc @scolapasta @landreev  (fyi: I have a demo on Thursday. thx)

This also applies to viewing file thumbnails:

The screenshots below are
1. authenticated user (ok thumbnails)
1. guest user (broken thumbnails)

  **Note:** The guest user has broken thumbnails for a published dataset

![bob_dylan_s_115th_dream_-_eat_boutique_dataverse](https://cloud.githubusercontent.com/assets/1036060/5782381/8f91fcee-9d88-11e4-81d0-635401faef97.png)


![bob_dylan_s_115th_dream_-_eat_boutique_dataverse](https://cloud.githubusercontent.com/assets/1036060/5782358/5d984e78-9d88-11e4-8e4d-a8f5d11d906c.png)

**Comment by landreev** [comment]
This should be working now. Please re-test. (may need a new build).

**Comment by kcondon** [comment]
OK, tested, works, closing.
