### ISSUE TITLE
Dataset: Cannot edit dataset metadata, buttons save, cancel not responsive.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1337]
Tested with Chrome, Firefox.
After creating a dataset, cannot edit metadata, the save, cancel buttons do nothing.

**Comment by eaquigley** [comment]
This is also happening with all the other tabs on the dataset page. Passing to @sekmiller to take a look at.

**Comment by sekmiller** [comment]
I changed the render on the Two Ravens popup 
<ui:include src="/subset/gui_subset.xhtml"/> at line 1932 on dataset.xhtml so that it doesn't occur when the page is in any kind of edit mode.

**Comment by kcondon** [comment]
This is working now, closing
