### ISSUE TITLE
Contact Us Form: Two Send Message buttons, one blank and gray

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1340]
I noticed there is now a Contact Us popup when you click on dataverse email icon. The form has two send message buttons, one is normal, the other is blank and gray.

**Comment by mheppler** [comment]
Fixed display of text within Cancel button on the Email Dataverse Contact.

Nice catch, Kevin.

**Comment by kcondon** [comment]
Buttons are better, closing
