### ISSUE TITLE
Add "select language encoding" for SPSS/sav files, as an "advanced option"

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#1343]
This is another child ticket of #1035. 
This option was never in the prod. version of DVN 3.*; was only available as a patch  made for Fudan .

**Comment by landreev** [comment]
It's implemented; just needs to be prettified a little. 
The expanding menu doesn't fit in the panel; will ask Mike for help.

**Comment by landreev** [comment]
Mike, please see if you can fix that issue I just showed you - where the expanding menus don't fit in the panel.

**Comment by landreev** [comment]
Once again, this option is for SPSS/sav files. 
And it should only appear on ingest; once the file is turned into tabular data, this option is no longer in the "advanced options". 
I'll send you a tiny SPSS/sav file by email.

**Comment by landreev** [comment]
BTW, functionally, it's working and ready to go into QA, once the menu is fixed.

**Comment by mheppler** [comment]
Fixed a layout issue with the Language Encoding dropdown submenu not displaying entirely.

**Comment by kcondon** [comment]
OK, tested and this works, closing.
