### ISSUE TITLE
Delete Files: Some weird behavior when deleting files: error, incomplete delete, immortal files.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1344]
While testing file upload, discovered some weird delete behavior:
1. In at least one case, deleting a file throws an error in the log, foreign key constraint, but then deletes file:
If a you delete an existing file at the same time you are adding a new one, this happens. Otherwise deleting individually works fine. Update: seems you need to add new, then delete, not vise versa.

Happens with both text and tabular files.

**Comment by landreev** [comment]
@scolapasta 
This is likely a UI issue, also related to the recent addition of the delete/restrict buttons and the corresponding logic; I may ask you to take a quick look, and see if you can easily diagnose this...
Otherwise - beta 14.

**Comment by eaquigley** [comment]
Passing to QA to test again.

**Comment by sbarbosadataverse** [comment]
Issue continues to exist. If I am in active window to upload files, and I select an existing file and delete it, confirm deletion, don't hit "SAVE," proceed to upload by drag and drop, then hit save, the page shows all files, including the deleted file.

1- image of the file deleted, new files added: https://www.dropbox.com/s/etnhsl5vao3m8ix/Screenshot%202015-03-18%2016.25.01.png?dl=0

2-SAVE selected, i see brief note at top telling me the deleted  file will be "deleted," but after save resolves, all files are still visible:

https://www.dropbox.com/s/bzoe6xjy4ltx7c9/Screenshot%202015-03-18%2016.25.35.png?dl=0

**Comment by sbarbosadataverse** [comment]
I did one final test, deleted the file, without uploading any additional files, and file still shows up after save:

https://www.dropbox.com/s/jztjlvxlnyfmgr2/Screenshot%202015-03-18%2016.29.10.png?dl=0

**Comment by kcondon** [comment]
I was able to reproduce this. It happens only when a file previously exists, you delete it and add a new one, in the same edit session. Either order: add/delete, delete/add it happens. The file that should be deleted it not and it becomes undeleteable or immortal.

**Comment by scolapasta** [comment]
Consolidated in #2044 (note the immortal file issue was resolved in 4.0 patch)

**Comment by kcondon** [comment]
OK, delete/add, add/delete seems fixed here but I reported another, related ticket:
https://github.com/IQSS/dataverse/issues/2227

Happens when add/delete is in the same session not a preexisting file.

Closing this one.
