### ISSUE TITLE
File Permissions: Granting File Access

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1345]
Notes on features and workflow from UI meeting with Merce, Gustavo, Liz, Mike:
- [x] Files Permissions page linked from Edit Dataset and Upload + Edit Files dropdown buttons, consistent panel layout with existing Dataverse and Dataset Permissions pages, displaying a Users/Groups panel and Files panel.
- [x] Users/Groups panel has a table displaying User Name, Files (number of files, link to popup), Action (Grant/Remove).
- [x] Files panel has a table displaying File Name (only restricted files), Access (number of users, link to popup), Assign (link to popup).
- [x] Access popup has list of users, with a checkbox, and a "Remove" button.
- [x] Assign popup has Users/Groups input (AutoComplete, Multiple, PrimeFaces component -- http://www.primefaces.org/showcase/ui/input/autoComplete.xhtml), and Files input.

![filepermissions_page_2](https://cloud.githubusercontent.com/assets/687227/5764689/141ddbe4-9cc2-11e4-85c6-69557b6e37c2.png)

**Comment by mheppler** [comment]
Related to #792 and .

**Comment by mheppler** [comment]
Added wireframe for File Permissions page, using Roles + Permissions page, and added some of the title, button text to the bundle.

**Comment by mheppler** [comment]
Added File Permissions link to Edit Dataset dropdown menu. b5b81d83c8aedee08d27225a9da795543091f978

**Comment by scolapasta** [comment]
For Users table, "grant" is specific to having a request, so will be implemented as part of #1348 .

**Comment by scolapasta** [comment]
@mheppler can you look at first checkbox and do any cleanup for beta 11, then pass to QA?

**Comment by mheppler** [comment]
The UI should be good. These are some additional items that might be best as additional tickets.

Manage File Permissions
- Requested Access table is separate from the Users/Groups table, rather than combined into one, and on top of that, is always displayed, even when empty, and without any label/title. Something needs to be done here.
- In the Files table, "0 Users/Groups" is a link to empty popup, where you can do nothing. That should just be plain text.

**Comment by kcondon** [comment]
Works, closing
