### ISSUE TITLE
Dataverse as a SWORD Client

### ISSUE THREAD

**Issue by spalan** [IQSS/dataverse#1346]
There are a number of use cases where it would be useful to be able to export data from Dataverse into another repository.  This might be a repository with the mission of aggregating data from a particular discipline or from a geographic area or it might be a repository with an archiving focus. We have a particular use case where we would like researchers to be able to export their data into a preservation management system based on Archivematica.  

Since SWORD has emerged as a standard way of importing into repositories, would it be possible to extend the server support in Dataverse to allow it to act also as a SWORD client so that studies could be exported from Dataverse?

**Comment by pdurbin** [comment]
The suggestion came from a [2015-01-14 meeting](https://docs.google.com/a/harvard.edu/document/d/1LwGSTTiaoCCSTKjT_uyGZEhNdN203BfY1xm_udfv9oI/edit?usp=sharing) with @spalan @scolapasta , Leanne Trimble, and myself. I feel like @mcrosas mentioned this once but maybe it was the same use case from the same people. It would be good to gauge community interest in this feature. It seems like @spalan has an idea for some middleware that could be developed in the shorter-term.

**Comment by pdurbin** [comment]
On a related note, I've seeing some [tweets](https://twitter.com/sparrowbarley/status/603572505899618306) about how [Jisc](http://www.jisc.ac.uk/) is conducting an interesting [survey](https://www.surveymonkey.com/s/PTHY5ND) going on right now that mentions "SWORD+" and a proposed API for getting data from repos to journal systems:

> "The proposed API will transfer data and metadata from the repository to a journal’s submission system, with an intermediary ‘helper app’ allowing authors to add their manuscript, references and other necessary information before submission. Article metadata will be sent back to the repository upon publication. These tools will be designed for maximum interoperability and made freely available. (Please see the schematic below for an outline of the workflow.)"

![helper-app](https://cloud.githubusercontent.com/assets/21006/8034709/3b4ba1c6-0db8-11e5-9c89-db1a2de42e0a.jpg)

**Comment by posixeleni** [comment]
:+1:

**Comment by bencomp** [comment]
DANS has a very similar use case for Dataverse to act as a SWORD client, namely to transfer datasets to a Trustworthy Digital Repository.

We have been working on detailing the use cases and requirements for this functionality; a pretty stable (though never finished) PDF report can be found [here](https://surfdrive.surf.nl/files/public.php?service=files&t=7f1a3ed92bdfaaa6092415b0c11e8084).

**Comment by pdurbin** [comment]
I just wanted to mention that while I was writing API tests as part of #2746 as described at https://groups.google.com/d/msg/dataverse-community/X8OrRWbPimA/LT0OU_s5DQAJ I could see where it would be helpful to try using https://github.com/swordapp/JavaClient2.0 in the API tests. It could be a good check against our implementation of SWORD to let the official SWORD Java client library provide "rel" URLs for the next action (deposit, edit, etc.). For the same reason (helping to ensure compliance with the SWORD spec), we used to use the official Python SWORD library at https://github.com/dvn/swordpoc/tree/master/dvn_client (which has since evolved into https://github.com/IQSS/dataverse-client-python which no longer uses the official Python SWORD library).

**Comment by pdurbin** [comment]
An interesting development in this area is that @richarda23 has started a repo at https://github.com/IQSS/dataverse-client-java which contains SWORD client code, which we could perhaps someday consider incorporating into Dataverse.

**Comment by pdurbin** [comment]
@spalan are you still interested in this?
