### ISSUE TITLE
Guestbook: Logging information is recorded to db but most is not displayed in GUI.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1350]
I created a custom guestbook and basically turned everything on. I was prompted to complete the guestbook on file download. When I checked the Guestbook response in the GUI, there were entries for each download but minimal info: filename and dataset. All the rest of the logging info is stored in the db with the exception of sesson_id.

**Comment by sekmiller** [comment]
A while back we updated the view collected data page to display most of the data collected.  We don't show session_id, but we do show dataset name, date of download, file name, download type, user name and affiliation and the responses to custom questions if available.

**Comment by sekmiller** [comment]
This may be a duplicate?

**Comment by eaquigley** [comment]
I went in and looked to see what is being tracked with guestbook downloads now. The image below shows the data being collected. @sbarbosadataverse, would you expect to see other data that is outside of the guestbook fields here?

![screen shot 2015-12-15 at 1 47 31 pm](https://cloud.githubusercontent.com/assets/5922904/11820408/68629efc-a332-11e5-8cec-c9955539049a.png)

**Comment by sbarbosadataverse** [comment]
@eaquigley @mheppler 
What Liz posted on Dec 15 looks fine. 
On another note, but same issue: IP addresses aren't useful as far as I can tell,  and I think those were also being logged at one point in the tracking info page WE maintained outside of a guestbook for users... Has that been removed? That may help speed up the process of generating our reports when asked.

**Comment by kcondon** [comment]
Db information appears to be complete. Opened a separate ticket about specific content formatting. Closing.
