### ISSUE TITLE
Documentation: Document settings API, remove related command examples from Install Guide.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1352]
This ticket is partly in response to a change in how the settings API works, see #1329 
Some settings API commands are used at Install time and are documented, with examples, in the Install Guide. These are now out of date based on the changes.

What might make sense is to document the settings API in the API guide using the new format, then update the Install Guide to just list the settings being set and their value, referencing the API guide for actual command format.

**Comment by pdurbin** [comment]
@raprasad fixed a lot of these in 906aefbf8363d4cba6d56f62d9b00304ee01d065 ... thanks!

**Comment by pdurbin** [comment]
I believe all the old `s/setting` examples have now been changed to `admin/setting` and reflect that data must be sent with `PUT -d $VALUE`.

> What might make sense is to document the settings API in the API guide using the new format, then update the Install Guide to just list the settings being set and their value, referencing the API guide for actual command format.

This is a good suggestion but my focus was on removing examples that don't work before we tag 4.0. Passing to QA.

**Comment by scolapasta** [comment]
Documentation for 4.0 is done, so closing this issue. If any specific issues arise relating, a new issue should be created.
