### ISSUE TITLE
Metadata: Adv Search and Results cards display description as Description Information Description

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1353]
While testing adv search, I noticed the Citation description field displays as Description Information Description when it should probably just say Description.

This also appears in the search results cards for Datasets.

**Comment by posixeleni** [comment]
@kcondon I will fix the field display name in the citation.tsv file so that it displays correctly.

**Comment by posixeleni** [comment]
@kcondon Changed the field displayNames to solve this display issue in Advance Search. @pdurbin I dont think this needs a schema.xml update for it to show. This should just need a db drop.

**Comment by pdurbin** [comment]
> @pdurbin I dont think this needs a schema.xml update for it to show

@posixeleni from looking at d6586ca067e2cd436113ae9d6183de24f302532f I agree with you.

**Comment by kcondon** [comment]
OK fixed, search works. Closing.
