### ISSUE TITLE
Dataverse General Information: URL to Identifier & Add in Link example

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1356]
For the URL metadata field on the General Information page, the label needs to change to say Identifier. Additionally, an example of the link needs to be put in, i.e.-dataverse.harvard.edu/ with the input box after the /. This way a user knows what the link will look like and gives context to what this field is.

**Comment by eaquigley** [comment]
@mheppler there is a low level version of this in but I wanted to check if you planned to do something else or if this could be passed to QA. If needs more, I would say move to Beta 15

**Comment by mheppler** [comment]
Added dynamic dataverseSiteUrl to the Identifier field form input help text of the Dataverse General Information create/edit workflows.

A separate ticket #1429 was created for cleaning up the UI of that entire form.

**Comment by kcondon** [comment]
Works, closing
