### ISSUE TITLE
Metadata Fields: Required Asterisks on Compound Fields

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1357]
Currently, the required asterisk for a compound field is only appearing on the sub field. It is really easy to overlook this, so I recommend we have a required asterisk on the field on the far left in addition to the one for the actually required field. This way you can tell when looking down the left hand side which ones have required components and which ones don't. 
![compundfields](https://cloud.githubusercontent.com/assets/5922904/5839547/160b9a46-a15d-11e4-8686-73264fc42526.png)

**Comment by mheppler** [comment]
I took a look into this. It looks like the asterisks already have render logic regarding child fields. (Line 158)
````
rendered="#{subdsf.datasetFieldType.required or subdsf.datasetFieldType.requiredDV }"
````
This was in there from a check in by @sekmiller from 10/29/2014, where he commented "put in required
asterisks for required child fields". I am passing this to him to look into.

**Comment by sekmiller** [comment]
Added asterisks to parent label when children are required.

**Comment by kcondon** [comment]
OK, parents of required children also have asterisks. Closing
