### ISSUE TITLE
Permissions: Editing dataverse access permissions causes page load to throw 500 error.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1358]
For any dataverse, if you edit access perms to allow any user to create a dataset/dv, reloading that permissions page results in 500 error.

This is most likely due to a change in the assigeneeidentifier for the internal group of all registered users.

**Comment by scolapasta** [comment]
@michbarsinai reverted the change he made to the AuthenticatedUsers identifier.

**Comment by kcondon** [comment]
Tested, this works now. Closing
