### ISSUE TITLE
Permissions: Confirmation Pop Ups for Removing an Assignment

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1359]
When an assigned role is removed or granting access to a file is revoked, there needs to be a pop up confirmation for the user to confirm what they are about to do.

Text for these:

- [x] Remove Assigned Role button is clicked: Are you sure you want to remove this role assignment? (Continue and Cancel buttons below)
- [x] Remove Access button is clicked: Are you sure you want to remove access to this file? Once access has been removed, the user or group will no longer be able to download this file. (Continue and Cancel buttons below)

**Comment by scolapasta** [comment]
These should now be wired up.

**Comment by kcondon** [comment]
OK, looks good, closing.
