### ISSUE TITLE
Properties Files - Remove All Text from App for Internationalization

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#136]
---

Author Name: **Mike Heppler** (@mheppler)
Original Redmine Issue: 3545, https://redmine.hmdc.harvard.edu/issues/3545
Original Date: 2014-02-11
Original Assignee: Mike Heppler

---

There shouldn't be any text, that is displayed in the browser, in the source code for the app. All of that, including help text, input labels, button labels, etc., will need to be moved to properties files. This will make the task of internationalizing the app much, much easier.

**Comment by scolapasta** [comment]
Closing as a duplicate #209.
