### ISSUE TITLE
Files tab: Thumbnail selection button is no longer appearing.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1362]
This worked yesterday but Liz pointed out the thumbnail selection button is now missing.

**Comment by landreev** [comment]
Seems to be working now. 
Please report if it heads its ugly rear again.

**Comment by kcondon** [comment]
OK, it headed it's ugly rear: if occurs if the dataset is published but works if it is unpublished.

**Comment by landreev** [comment]
@kcondon 
@scolapasta 
Can't immediately answer this; the null filemetadata id that we've just seen is a serious smoking gun too. 
It is most likely to blame for the delete bug (*all* files get deleted, when you attempt to delete a file in a release version) too. So we'll need to look into this separately.

**Comment by landreev** [comment]
@kcondon
@scolapasta 
... a serious smoking gun *though*.

**Comment by landreev** [comment]
OK, the button should now be showing, whether it's a draft version, or a published version with no draft.

**Comment by kcondon** [comment]
This is working now. Only thing, I noticed an unexpected behavior: selecting a thumbnail on a published dataset creates a new draft dataset. Seems like it shouldn't -this is not information that is part of the academic record.

**Comment by kcondon** [comment]
Opened a separate ticket for the other issue: #1433 Closing
