### ISSUE TITLE
Linked Dataverse: Do not allow linking of unpublished dataverses or datasets

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1363]
Currently I can link both unpublished datasets and dataverses if I have permissions, eg admin.
Gustavo felt this should be fixed for beta 11.

**Comment by sekmiller** [comment]
Fix checked in.

**Comment by eaquigley** [comment]
I don't understand why we aren't allowing this.


On Jan 21, 2015, at 7:38 PM, sekmiller <notifications@github.com<mailto:notifications@github.com>> wrote:


Fix checked in.

**Comment by sekmiller** [comment]
Gustavo requested that this be fixed at for the push.  Originally the logic did not allow you to link to unpublished dataverses. My recent checkin suppresses the link button on unpublished datasets and dataverses.  Either or both would be easy to back out if thats what you want.


On Jan 21, 2015, at 8:00 PM, Elizabeth Quigley <notifications@github.com<mailto:notifications@github.com>> wrote:

I don't understand why we aren't allowing this.


On Jan 21, 2015, at 7:38 PM, sekmiller <notifications@github.com<mailto:notifications@github.com><mailto:notifications@github.com>> wrote:


Fix checked in.

**Comment by kcondon** [comment]
________________________________

It is in the requirements doc where on 12/1 you said OK:
https://docs.google.com/document/d/1sHuXD7VGI8Gowfvc69Y7xIUoezVUH4J6hHnhW4nXd9k/edit

On Jan 21, 2015, at 8:00 PM, Elizabeth Quigley <notifications@github.com<mailto:notifications@github.com>> wrote:

I don't understand why we aren't allowing this.

**Comment by mcrosas** [comment]
I agree with @eaquigley - I know that this is similar to how it worked in 3.6 (for collections), but it was a big annoyance in many use cases. Can we change it so it is possible to link unpublished datasets/dataverses? Would it cause any problem?

**Comment by kcondon** [comment]
Not sure if this still holds weight but the discussion in the requirements doc went:
Sonia asked this: do we need to worry at all about users who don't want others linking their dataverses/datasets?
Liz asked: Did we have anything in 3.6 for a user to be able to block others from linking their dataverses/datasets?
Sonia: nope
Liz: Then I say we leave it as is. You can only link published dataverses and datasets is something we had decided on.

________________________________

**Comment by eaquigley** [comment]
Thanks @kcondon. I most likely said that to eliminate extra work. But now am rethinking it, especially in light of me needing to put together a sample Dataverse that won't be published yet needs linking. It would make sense to be able to link unpublished so once it's ready to publish it appears. Sorry for all the confusion and going back on what was in the Google doc.


On Jan 21, 2015, at 9:10 PM, kcondon <notifications@github.com<mailto:notifications@github.com>> wrote:


Not sure if this still holds weight but the discussion in the requirements doc went:
Sonia asked this: do we need to worry at all about users who don't want others linking their dataverses/datasets?
Liz asked: Did we have anything in 3.6 for a user to be able to block others from linking their dataverses/datasets?
Sonia: nope
Liz: Then I say we leave it as is. You can only link published dataverses and datasets is something we had decided on.

________________________________

**Comment by sekmiller** [comment]
Per discussion with @kcondon and Merce, I have removed all requirements that a linking dataverse or linked dataset or dataverse are published.  I haven't tested the full implications of permissions on the viewing of these unpublished items outside of their "natural habitats"

**Comment by kcondon** [comment]
Works, closing
