### ISSUE TITLE
Linked Dataverse: There is no way to view a list of linked objects: dv or ds.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1365]
A requirement for linked dv/ds was to see a list of linked objects. There is no way currently but Gustavo suggested perhaps a facet?

**Comment by eaquigley** [comment]
@sekmiller @mheppler needs logic put in for the search/browse cards to be

**Comment by eaquigley** [comment]
Icons are now in Dataverse 4.0 so linked icons are displaying on search/browse cards when they are linked in a dataverse.

**Comment by scolapasta** [comment]
Closing this as it is covered by #1840

**Comment by kcondon** [comment]
Link icons are in place. Closing.
