### ISSUE TITLE
Linked Dataverse: Can link a dataset and then link its parent dv.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1367]
Not sure if this is a bug but would cause issues when we show the contents of all linked objects.

I can first link a dataset and then link its parent dv so in effect the ds is linked twice.

**Comment by sekmiller** [comment]
@kcondon - if I have linked a dataset from the dataverse should I be able to link the dataverse?

**Comment by scolapasta** [comment]
Discussed with @eaquigley, and we think we should leave it like this for now.

**Comment by kcondon** [comment]
Closing
