### ISSUE TITLE
Dataset Permissions for Dataset issue with assigning roles

### ISSUE THREAD

**Issue by esotiri** [IQSS/dataverse#1369]
Scenario:
create a dataverse  > create a dataset > edit dataset permissions > dataset 
There are a couple of issues:
1. permissions dropdown is empty, and should not appear here.
2.  Users/Groups > assign role > Anyone with a Dataverse account > can be Editor
a. Login as another user > can see the dataset but has no actions available
(Same happens when assigning Manager or Admin role - no actions available)

**Comment by scolapasta** [comment]
Moved point 1 to #1377

**Comment by michbarsinai** [comment]
Issue 1 solved as of 6f14d45.

**Comment by michbarsinai** [comment]
First off - internal permission mechanism works (pew!)
```
dataverse| curl http://localhost:8080/api/test/permissions/13?key=$GABBI_KEY | jq .
{
  "status": "OK",
  "data": [
    "ViewUnpublishedDataset",
    "DownloadFile",
    "EditDataset",
    "DeleteDataverse"
  ]
}
```

**Comment by michbarsinai** [comment]
Over to Gustavo, as this seems to be a UI issue.

**Comment by kcondon** [comment]
OK, the first issue was one of the panels (access?) did not make sense for datasets, only dataverses. That is resolved.
The second is that assigning permissions to groups does not seem to grant them the permissions in reality. So, assigning editor to "Anyone with an account" does not really make them an editor.

**Comment by scolapasta** [comment]
Actually, when I tested this worked. I don't see the dataset on the search page (but this is indexing related, and I don't think groups are currently used for indexing).

But if I try the direct link to the dataset, I am able to view the dataset and also to edit it.

**Comment by kcondon** [comment]
Yes, this works as well, closing
