### ISSUE TITLE
Permissions: Can't see thumbnail on files tab if you are a registered user, non owner.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1371]
This issue was just resolved for an anonymous user but still exists if you are a registered user, non owner:

In a published dataset, unrestricted files, see broken thumbnail images on files tab for a registered user, non owner.

**Comment by landreev** [comment]
Seems to be working properly now. In the screen shot below I'm logged in as a non-owner...
Please re-test. 
![screen shot 2015-01-29 at 5 51 17 pm](https://cloud.githubusercontent.com/assets/737558/5967963/759048de-a7e0-11e4-941a-e9391be2cfc1.png)

**Comment by kcondon** [comment]
OK, works, closing
