### ISSUE TITLE
Download button - one file selected

### ISSUE THREAD

**Issue by esotiri** [IQSS/dataverse#1373]
per Gustavo, opening a new ticket in relation to https://github.com/IQSS/dataverse/issues/1310 last question. 

Download button action: 
when one file is selected > actions grayed out > it should enable 'download selected'

**Comment by landreev** [comment]
@esotiri 
I originally implemented it like this on purpose - the rationale being, it's just stupid to download just one file in a file bundle; but we eventually decided it was ok. So you should be seeing the download link enabled now, even if there's only 1 file selected.
