### ISSUE TITLE
API: Add User fails on adding duplicate but still adds record to builtinuser table, creating non-unique errors. 

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1374]
If I add the same user twice with the add user api, it fails with {"status":"ERROR","message":"Can't save user: Transaction aborted"} but actually still adds a row to the builtinuser table. This causes non-unique/500 errors later if a dataset is created with that user.

**Comment by pdurbin** [comment]
You can easily see the duplicate usernames with this:

curl http://localhost:8080/api/users?key=burrito
