### ISSUE TITLE
Author/User Identifiers: Suggested Additions

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1375]
In addition to ORCID and ISNI, there has been user feedback on including Digital Author Identification. I'd imagine there might be some other ones as well. This ticket is to review which identifiers to add.

**Comment by posixeleni** [comment]
@eaquigley whats the best documentation to look at for DAI? http://en.wikipedia.org/wiki/Digital_Author_Identification

**Comment by eaquigley** [comment]
@posixeleni I found this: https://wiki.surfnet.nl/display/standards/DAI but this would definitely be worth reaching out to the DANS partners to get more information for us to be able to implement it after 4.0 is done.

**Comment by pdurbin** [comment]
See also: authorIdentifierScheme : Add "ResearcherID" as one of the option #3169

**Comment by PaulBoon** [comment]
We  at DANS are planning to add the DAI, but we could also take ResearcherID and ScopusID if that is a useful addition.

**Comment by pdurbin** [comment]
@PaulBoon sounds good. Do you want me to assign this issue and #3169 to you and put them in the "Community Dev" column at https://github.com/orgs/IQSS/projects/2 ?

**Comment by mderuijter** [comment]
@pdurbin Could you please assign this issue to me? 

And regarding this issue, I found some validation coder here:
https://github.com/IQSS/dataverse/blob/41acae142051802fc8935a92716a219b8dc9c401/src/main/java/edu/harvard/iq/dataverse/DatasetAuthor.java#L92

I tried testing these validations for the various identifierScheme's but the validation doesn't seem to be active. 

Does this need to be turned on via a configuration option?

**Comment by pdurbin** [comment]
> I tried testing these validations for the various identifierScheme's but the validation doesn't seem to be active.

@mderuijter good question. It looks like the only place that the ORCID regex is excercised in the live code is during the export of Schema.org JSON-LD here:

https://github.com/IQSS/dataverse/blob/v4.17/src/main/java/edu/harvard/iq/dataverse/DatasetVersion.java#L1646

Basically, if you don't provide a valid ORCID ID, it won't be added to the Schema.org JSON-LD output.

It would be nice to use this validation much earlier, of course, such as when the user is entering their ORCID ID while creating their dataset. #5271 is related as is the comment at https://github.com/IQSS/dataverse/issues/4371#issuecomment-435443733

**Comment by mderuijter** [comment]
@pdurbin alright, thanks for clearing that up!

My colleagues here at DANS would also be interested in using this validation earlier on.

**Comment by pdurbin** [comment]
@mderuijter great! You are welcome to work on #5271 or you could create a new issue in your own words to describe the feature or bug fix you want. Sometimes we try to express issues as user stories... "As someone creating a dataset, I want assurance that my ORCID ID is in the right format." Something like that. 😄
