### ISSUE TITLE
Remove (was Implement) new EditDatasetAccess permisison

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#1383]

**Comment by michbarsinai** [comment]
See relevant email from Gustavo.

**Comment by michbarsinai** [comment]
Of course. That's not the issue. 

In the UI, we have these areas, metadata and licensing as separate areas. So we can check for permissions before even allowing someone to click edit (and the edit forms are separate.

But through the API, it's all just part of the datasetversion object (either as meteadata fields or as properties directly on the datasetversion). And right now there is one command for Create and one for update.

But in create, you should not be able to edit the access terms without that specific permission. And same with Update (maybe this needs to be two separate commands?)

Let me know if that makes sense? If not, we can setup a skype call at some point.

Gustavo

On Thu, Jan 22, 2015 at 2:15 PM, Bar-sinai, Michael <mbarsinai@iq.harvard.edu> wrote:
Not sure I got the concern.

Generally, if a user can perform an action in the UI, she could do it via the API as well, no?

-- Michael

**Comment by scolapasta** [comment]
In reviewing this, we realized it was simpler to just remove this extra permission and have one less role. Authors would still not be able to restrict a file until it was published - thay can restrict on a version draft, but a reviewer would need to confirm.
