### ISSUE TITLE
Consistency: default license when creating dataset

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#1385]
"Set Default License to CC0 on dataset create" is the commit message for 444f52b but this is only when creating datasets through the GUI.

Should this business rule be applied consistently throughout the app? Right now when you create a dataset via the native API or SWORD, no license is set ("null" in the database). I'm working on the SWORD side of things at #805 but it seems like the business rule should be applied centrally in the CreateDatasetCommand.

I'm giving this to @eaquigley for now since she has worked in this area of licensing.

**Comment by posixeleni** [comment]
@eaquigley @scolapasta I'm pretty sure this default license should be set universally across the whole application and not just at the GUI. However, the one question I have is: 

How do you make it evident to users in the API that by default the license would set to to CCO unless someone puts in custom Terms of Use? This would need to be set before allowing someone to be able to publish their dataset so we could have a curl command to set it to CCO or None. If None is selected then they MUST enter custom Terms of Use for the data.

Sound ok? Or am I missing something?

**Comment by eaquigley** [comment]
@posixeleni If the API user selects None, to match the GUI, they still wouldn't need to enter custom Terms of Use.

**Comment by posixeleni** [comment]
@eaquigley: Am I misunderstanding something here? I was under the assumption that if you dont select CC0 you would NEED to give Terms of Use? This would need to be figured out in the API calls to match the UI as best as possible.

**Comment by posixeleni** [comment]
After chatting with @eaquigley I understand better now.

So Users in the GUI as well as the API are NOT expected to enter Terms of Use if they do not select CC0. However, we should allow them the ability (optional) to enter Terms of Use via the API should they want to, right? Some may want to enter a different license that we dont have listed ATM (i.e. CC-BY or some custom license).

Not sure if you need anything else from me here, who should I assign this ticket to?

**Comment by eaquigley** [comment]
@posixeleni API users should definitely have the option to add in Terms of Use. @pdurbin should this ticket be going to you? or is this something for @sekmiller to do? i am confused.

**Comment by pdurbin** [comment]
@eaquigley I would say if @sekmiller would adjust the DatasetPage to use the centrally defined static variable "defaultLicense" I added in https://github.com/IQSS/dataverse/blob/6babd4a45586f408e72bbf54db3083372553958c/src/main/java/edu/harvard/iq/dataverse/DatasetVersion.java#L80 it would be a step in the right direction.

Last time I checked the Native API allows you to create a dataset without specifying a license. I'm not sure who would work on that. Maybe @ekraffmiller or @michbarsinai 

Overall the goal of this ticket is consistency in how business rules are enforced.

**Comment by posixeleni** [comment]
I spoke with Berkman and they think that if a user is going through an API to use Dataverse they will need to abide by the general Dataverse terms of use + a set of API-specific terms which they are currently drafting for us. They should have a strawman set of terms by the end of this week for us to review.

**Comment by posixeleni** [comment]
Closing please see #1781.
