### ISSUE TITLE
Dataverse Category: Values are Appearing in Facet as Plural

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1386]
I changed the dataverse category values to be singular (i.e.-researchers to researcher) however they are appearing in the facet as plural. @pdurbin could you please look into fixing this? The change was in a37465d95670dbe7f4094022cf17924c3dcd553d

**Comment by scolapasta** [comment]
Actually, should this be in the bundle? My point is, these values are data, they are stored in the index as the values.

Should they be internationalized? (Other data will clearly not be.

**Comment by scolapasta** [comment]
I went ahead and modified these to singular for indexing.

But passing to @eaquigley because of the bundle / internationalization question. I don't think the values on the dataverse page should be in the bundle, as this is data (like subject) and will be stored and indexed in English. (is this an issue? what about with other controlled vocabulary)

**Comment by eaquigley** [comment]
@scolapasta I agree that it shouldn't be in the bundle. I'll check and see if any other controlled vocabularies are in the bundle and need to be moved out of it.



On Feb 19, 2015, at 6:33 PM, Gustavo Durand <notifications@github.com<mailto:notifications@github.com>> wrote:


I went ahead and modified these to singular for indexing.

But passing to @eaquigley<https://github.com/eaquigley> because of the bundle / internationalization question. I don't think the values on the dataverse page should be in the bundle, as this is data (like subject) and will be stored and indexed in English. (is this an issue? what about with other controlled vocabulary)

**Comment by eaquigley** [comment]
@scolapasta I went through the UI and bundle and didn't find other controlled vocabularies listed in the bundle. Passing to QA so this ticket can be closed.

**Comment by eaquigley** [comment]
Appearing as singular. Closing ticket.
