### ISSUE TITLE
Files Tab: Perform design review of Advanced Options.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1389]
Basic functionality of Advanced Options appears complete and so is ready for design review.

**Comment by mheppler** [comment]
Cleaned up the UI for the Edit Categories workflow on files from the Upload + Edit Files view of the dataset page.

**Comment by mheppler** [comment]
Cleaned up the UI for the Advanced Options popup on the Upload + Edit Files view of the dataset page.

**Comment by mheppler** [comment]
Additional clean up for the UI for the Advanced Options popup on the Upload + Edit Files view of the dataset page.

That should be everything.

**Comment by kcondon** [comment]
OK, still works, closing.
