### ISSUE TITLE
Shibboleth: Intermittant 500 errors on login page, intermittent success using shib login.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1390]
We just reenabled/reregistered test shib login on dvn-build, first shib test since new weld component.

I am seeing serious intermittent errors, including 500 error when clicking on login, 500 error when choosing shibtest, 500 error when logging in to shib, shib login not succeeding, then some repeated homepage loads and the original shib login is there.

**Comment by esotiri** [comment]
I have seen it before. Try to re upload the metadata on testshib.

**Comment by kcondon** [comment]
This was a result of not restarting gfish. Once I did, the problem went away. For the record, I had restarted httpd and shibd.
