### ISSUE TITLE
Date/Time Stamp Format - Consistency Across App

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1391]
The date and time stamps used for created, uploaded, published, etc. need to be displayed consistently.

Here's a list of instances across the site, and their preferred formats:
- [ ] Dataset Guestbook, Manage - "Month, Day, Year"
- [ ] Dataset Templates, Manage - "Month, Day, Year"
- [ ] Dataset Versions, View - "Month, Day, Year HH:MM AM/PM Time Zone"
- [ ] Dataset Versions, Difference - "Month, Day, Year HH:MM AM/PM Time Zone"

Code example:

```
public String getCreateDate() {
        return new SimpleDateFormat("MMMM d, yyyy").format(createTime);
}
```

**Comment by mcrosas** [comment]
Go over this in a google doc and then add to our new Design Guide.

**Comment by pdurbin** [comment]
I'm not sure how relevant this is to the UI, but for the API we use a single method to always return the date and time in a consistent format (ISO-8601): https://github.com/IQSS/dataverse/blob/v4.5.1/src/main/java/edu/harvard/iq/dataverse/api/Util.java#L58

**Comment by mheppler** [comment]
See #5300 for how the date and time format of the time stamps on the Versions Details popup (labeled "Dataset Versions, Difference" above) on the Dataset pg, as well as the Notification table on the Account pg have been updated for the internationalization efforts across the site.

Any date and time format consistency issues should also look to . As well as _Permissions: Timestamp + user name in notifications/permissions pg for access requests #2855_ which is requesting a new time stamp to be added to the Requests table on the dataset/file Permissions pgs.

**Comment by oscardssmith** [comment]
Just saying, there is an actual spec for the right way https://en.wikipedia.org/wiki/ISO_8601 for dates, it's YYYY-MM-DD. It prevents any guessing games (at least until 10000 AD)
