### ISSUE TITLE
Published citation has V0 as a version, should be V1

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#1392]
When I run https://github.com/IQSS/dataverse/blob/master/scripts/deploy/apitest.dataverse.org/post as part of regular deployment to https://apitest.dataverse.org the citation of a published dataset has "V0" in it like this:

> Spruce, Sabrina, 2015, "Spruce Goose", http://dx.doi.org/10.5072/FK2/JXAOOW, API Test Dataverse, V0

V0? That doesn't seem right! Shouldn't it be V1 or higher? I'm not sure how this happens. It's not **just** what's indexed into Solr because the dataset page shows "V0" as well.

You can also see V0 in an example citation of a published dataset at http://guides.dataverse.org/en/latest/api/search.html so we should fix that doc too.

**Comment by ekraffmiller** [comment]
I tested the Datasets API publish method, and this is handling the version number as expected.  When I call api\datasets\{id}\actions\:publish?type=major&key={key},  on a dataset with a draft version, the result is a published dataset with version 1.0.  

In this ticket, the script "publish-dataset-spruce1" is calling the sword data deposit API, so it looks like the issue is how the publish command is being called from within the sword API.

**Comment by scolapasta** [comment]
@pdurbin, @ekraffmiller and I made a change for this that we think makes sense, but as it's Sword specific code, could you please review, and if OK, pass on to QA.

**Comment by pdurbin** [comment]
973d06cd672b139fea8df918b3b35906618607a3 looks like a good fix to me. Before moving it to QA I'll make sure it's fixed on apitest and also fix the example JSON output in the Search API docs.

**Comment by pdurbin** [comment]
@scolapasta isn't it a little weird that the PublishDatasetCommand allows the publishing of a dataset with a version of V0? I can't imagine there being any use case for this. Maybe we can fix that post 4.0.

**Comment by pdurbin** [comment]
It seems like a good fix. Using SWORD, I can't publish a dataset with "V0" any more. And when I edit just metadata publishing bumps it to V1.1. Adding a file bumps it to 2.0, as expected.

I left a todo in the code to think about why the PublishDatasetCommand allowed a "V0" version to be published. A post 4.0 activity. :)

Passing to QA.

**Comment by sbarbosadataverse** [comment]
Kevin--can I text this on build? It's API related it appears?
