### ISSUE TITLE
Files: Don't show download, if no access

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#1394]

**Comment by scolapasta** [comment]
If you could also wire the request access button(s) with opposite logic, once this is in place.

**Comment by landreev** [comment]
Gustavo, 

I've added extra permission logic to the download and request access buttons; 
it's based on 

permissionServiceBean.on(fileMetadata.dataFile).has('DownloadFile')

and Permission Service now handles granting download access to released unrestricted files. 

Please review.

**Comment by scolapasta** [comment]
Reviewed, looks good, passing to QA.

**Comment by kcondon** [comment]
Removing downloading works but explore button still appears. Passing back.

**Comment by landreev** [comment]
OK, added the permission check for the dataexplore (tworavens) button. 
Also added it for the worldmap links... I'm not 100% positive about these though - so if these are still not looking right, please give this to Raman.

**Comment by kcondon** [comment]
This works, closing
