### ISSUE TITLE
Dataset Citation 'Why Cite?' - 404 Page Not Found

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1395]
The "Why Cite?" link in the dataset citation block goes to a 404 Page Not Found error page.

Here is the old bad link: https://dataverse-demo.iq.harvard.edu/guides/Data_Citation/index.html

Here is the new good link: http://best-practices.dataverse.org/data-citation/

**Comment by mheppler** [comment]
Fixed bad URL for the Why Cite? link on the dataset citation block.

**Comment by kcondon** [comment]
Fixed, closing
