### ISSUE TITLE
Code Cleanup: general datasetfield and metadatablock

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#1398]
Some time after 4.0, I'd like to review this and see if there are things that can be cleaned up.

Some possibilities - can we use same methods to avoid N/A values for edit and display
(edit uses getValueForEdit, while display uses isEmptyForDisplay, which calls getValues())

look at getDisplayValue methods on DatasetField

see how mdb.isEmpty is used?

**Comment by pdurbin** [comment]
@scolapasta good ideas. Are you still interested having them implemented? Has your thinking changed at all?

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
