### ISSUE TITLE
Review what to do for N/A values in the citation

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#1399]
In particular for title and author, but it would be true for ANY of the fields that are gotten from the dynamic datasetfields

**Comment by posixeleni** [comment]
Will review this with Merce by the end of this week.

**Comment by posixeleni** [comment]
![image](https://cloud.githubusercontent.com/assets/5013837/6397961/636b17e2-bdb6-11e4-9b02-1b30bf0c7fd8.png)

**Comment by posixeleni** [comment]
Reviewed with @mcrosas @scolapasta @ekraffmiller : 

If no author in the dataset: 
Use Producer
ELSE do not show anything before date (hide N/A from the display)

Also, do not show N/A if there is no Title in the dataset. Show nothing.

Assigning to @scolapasta to assess dev effort required for this.

**Comment by sekmiller** [comment]
Fix is checked in and will be available for testing after the next build.

**Comment by sbarbosadataverse** [comment]
I tested in DVN-5, searched for "title:N/A"
returned no values

Can't test in build until datasets from 3.6 with this value in "author" field, or missing values in author field are migrated.
