### ISSUE TITLE
Shibboleth: Institution-wide Shibboleth groups

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#1401]
As explained in the [Shibboleth Functional Requirements Document for Dataverse 4.0](https://docs.google.com/a/harvard.edu/document/d/12Qru8Gjq4oDUiodI00oObHJog65S7QzFfFZuPU3n8aU/edit?usp=sharing), we plan to support Institution-wide Shibboleth groups.

In practice this means creating a groups with names like "All Harvard PIN/Shibboleth Users" or "All testshib.org Shibboleth Users" that pay attention to the "Shib-Identity-Provider" Shibboleth attribute to see if you authenticated via harvard.edu, testshib.org, etc.

You should be able to assign roles to these groups by clicking the "Assign Roles to Users/Groups" button.

**Comment by pdurbin** [comment]
As of https://github.com/IQSS/dataverse/commit/4a4310b0a08f1b23f4380692c832495234e4c716 you can log into dvn-build with the "TestShib IdP" and see that you are part of the "All testshib.org Shibboleth Users (&shib/1)" group with the debugging output I added to the screen when Shibboleth is enabled:

![testshib](https://cloud.githubusercontent.com/assets/21006/5987978/2ff09a20-a918-11e4-892c-30f5257e57a8.png)

These are the commands I used to enable Shibboleth and create the testshib group:

curl -X PUT -d yes $HOST/s/settings/:ShibEnabled

curl -s -X POST -H 'Content-type:application/json' --upload-file data/shibGroupTestShib.json "$HOST/api/groups/shib?key=$ADMIN_KEY"

**Comment by pdurbin** [comment]
Per @scolapasta I'm giving this to QA but please note that there is something going on with permissions first reported in #1380 such that Shibboleth users aren't seeing the "Add Data" button when they should. "No effect".

This ticket is more about the creation of Shibboleth groups, and assigning roles like this:

![shibrole](https://cloud.githubusercontent.com/assets/21006/6011599/bc7b8640-ab0b-11e4-90c3-454962543986.png)

Please note that we'd like to automate the addition of Shibboleth groups in #1403

**Comment by bencomp** [comment]
In the Dataverse.nl situation, all users come through the same IdP: SURFconext. We look at the value of the Organization attribute to determine the user's organisation. Can that attribute be used as well?

**Comment by bencomp** [comment]
Oh, and :+1: !

**Comment by pdurbin** [comment]
> We look at the value of the Organization attribute to determine the user's organisation. Can that attribute be used as well?

I have [a todo in the code](https://github.com/IQSS/dataverse/blob/4a4310b0a08f1b23f4380692c832495234e4c716/src/main/java/edu/harvard/iq/dataverse/authorization/users/AuthenticatedUser.java#L69) that at runtime I should store a hash of "potentially interesting" attributes. I guess this hash should be backed by a table that can be managed by users who have the superuser boolean set to "true".

**Comment by kcondon** [comment]
@pdurbin I think you meant to pass me #796. I tested that one and then passed along to Mike. Giving you back this one.

**Comment by pdurbin** [comment]
@kcondon no, a while back I purposely put this in QA per my comment back then: https://github.com/IQSS/dataverse/issues/1401#issuecomment-72563750

**Comment by mheppler** [comment]
@pdurbin, no GitHub Issues commenting on vacation.

**Comment by kcondon** [comment]
Shib groups can be created and assigned roles. Closing

**Comment by pdurbin** [comment]
> We look at the value of the Organization attribute to determine the user's organisation. Can that attribute be used as well?

@bencomp not as of this writing but I just opened #1515 about this
