### ISSUE TITLE
Automatically add a shib group when a user from a new institution first logs in

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#1403]
From https://github.com/IQSS/dataverse/issues/1403#issuecomment-712435403 below:

At Harvard, we are changing our curation workflow to require validation of users. We do plan on allowing users of some shib IDPs to automatically be part of this group, so automatically creating shib groups could be helpful for this.

**Comment by pdurbin** [comment]
This is a follow up to #1401. Here is where we document the manual process for adding an institution-wide group: http://guides.dataverse.org/en/4.5/installation/shibboleth.html#institution-wide-shibboleth-groups

**Comment by pdurbin** [comment]
@mbamouni wrote in at https://groups.google.com/d/msg/dataverse-community/6Q9cQn-fjZQ/zWqxFg-mAAAJ and seemed a bit confused about how to use Shibboleth groups. Making the creation of groups automatic would probably help.

**Comment by scolapasta** [comment]
At Harvard, we are changing our curation workflow to require validation of users. We do plan on allowing users of some shib IDPs to automatically be part of this group, so automatically creating shib groups could be helpful for this.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
