### ISSUE TITLE
For mapped datasets, expose WorldMap file export links: KML, geojson, geotiff, png, etc.

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#1404]
evaluate with DV team / file landing page..

**Comment by eaquigley** [comment]
@raprasad are you working on this? if not, what needs to be done by a dataverse developer?

**Comment by raprasad** [comment]
Not essential, moved to post 4.0

**Comment by djbrooke** [comment]
Closing some old Worldmap issues. Will re-evaluate when/if additional Worldmap work gets added to the roadmap.
