### ISSUE TITLE
DOI: Provide a way to update server urls for already registered DOIs.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1407]
We need a way to administratively update server urls for DOIs that have already been registered in cases where the service url changes. This was requested by a partner, Odum.

This functionality is inline with our existing handle utilities where a handle could be "fixed" but was not updated to include DOI.

**Comment by qqmyers** [comment]
There are ap/datasets/id/modifyRegistration and /api/datasets/modifyRegistrationAll calls that do this. Not sure they are in the guides. There are also /api/datasets/id/modifyRegistrationMetadata and the similar All calls that do this for published data that are in the guides at https://guides.dataverse.org/en/latest/admin/dataverses-datasets.html?highlight=modifyregistration#send-dataset-metadata-to-pid-provider.
