### ISSUE TITLE
File Tab: Add Request Access Button for non logged in users

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1409]
When a file is restricted and the option to request access to a file is enabled, a non logged in user sees nothing about this. When a user is logged in, they see a request access button. Could you please add in the request access button even when a user is not logged in that when clicked, opens a log in pop up. @scolapasta said this was something you could do but would need some rendering help possibly so please reach out to him.

**Comment by mheppler** [comment]
Related to #1345, moving to Beta 13.

**Comment by mheppler** [comment]
Added "Request Access" button to restricted files on the dataset page that's displayed for guests (no user is logged in) and linked to a Sign Up/Log In popup.

**Comment by kcondon** [comment]
Works Closing
