### ISSUE TITLE
Update Version Differences to account for items added since development

### ISSUE THREAD

**Issue by sekmiller** [IQSS/dataverse#1410]
There have been several additions to the dataset versions including file category, file restriction and terms of use and access.  We need to add these to the differences displayed.

**Comment by sekmiller** [comment]
Added Terms of Use; TOU Additional Information; Terms of Access ; TOA Add'tl Info.

Also added Datafile tags.

Could not add changes to guestbook status (add, remove, change) because guestbook is at the dataset level and thus not tracked by version.

**Comment by sekmiller** [comment]
Fixes will be available after next build

**Comment by kcondon** [comment]
Tested, toa and tou seem to work, data file tags are not appearing. Also, the title for the TOU/TOUA block in the verions tab could use some styling to appear like the other blocks: files/ metadata changes.

**Comment by sekmiller** [comment]
@kcondon 
Data file tags appear if they are changed from one version to another.  They are not displayed for a new file.  Should they be? And if they are displayed for a new file should all metadata for a new file be shown?Also, I labeled them as "Category" because that is what they are called internally.  Should I change it to "File Tags" "Tags" Something else?

**Comment by sekmiller** [comment]
Changed label to Tag(s) and added more metadata (including tags and "restricted") to new files

**Comment by kcondon** [comment]
Working, closing.
