### ISSUE TITLE
Guestbook: Various issues

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1411]
- [x] 1. Weird edit/update issues
There are some weird page update issues when creating/ editing a custom guestbook and it varies between FF and Chrome on my mac.
The fundamental issue is trying to create more than one custom question of different types or just creating one and switching between types. Behavior varies from changing all custom fields to the same type, not changing type back from second type and throwing validation error, etc. Not usable if using custom fields and needing to update. (type dropdown is broken)
[Kevin] Works
- [x] 2. Edit guestbook from view popup calls create rather than edit. The main edit works.
[Kevin] Works
- [x] 3. Include Guestbooks from Parent Dataverse checkbox does not stay checked and is always enabled and available for selection on edit licensing.
[Kevin] Works
- [x] 4. Canceling from copy makes a copy anyway *and enables it*.
[Kevin] works.
- [x] 5. View guestbook from the dataset licensing and terms tab shows formatting/ encoded characters.
[Kevin] Works
- [ ] 6. Can save a guestbook that has a name but nothing else.
[Kevin] Spoke with Stephen, intended behavior, results in account info optional.
- [x] 7. Can disable a selected guestbook (ok) but it still prompts user as if it were enabled.
[Kevin] Works
- [x] 8. Included parent guestbooks are not appearing in available guestbook list, see issue #3.
[Kevni] Works
- [x] 9. User account fields in guestbook behavior unclear: what happens is these fields will *always* appear on the guestbook but only the ones you check will become required. There is no indication of this on the create/edit page but if you select just one and save, it explains it on the view guestbook popup from the available guestbooks table.
[Kevin] Works, informational text supplied
- [ ] 10. The black bubble view mouseover on the available guestbook table appears through the transparent view popup.
- [x] 11. Usage count not working
[Kevin] Works
- [x] 12. Hide "View Collected Data" button if not enabled, or if not used by a dataset.
[Kevin] Works
- [x] 13. Not able to view collected data.
[Kevin] Works
- [ ] 14. Wire up commented out edit help info text.
- [x] 15. Validation runs on empty Guestbook Name when you click Add Custom Question.
[Kevin] Works
- [x] 16. Show empty Custom Question form by default, have Required selected by default, add "Select..." to Type dropdown to get around validation.
@eaquigley Does #16 makes sense? This is not how it is working and doesn't seem like it would improve things
- [x] 17. Remove "Add Custom Question" button and just use "+" and "-" buttons next to questions.
[Kevin] Works
- [x] 18.Filled out popup form, no file.
[Kevin] Works

From #1397:
- [ ] Display error message in the popup and not on the dataset page.
- [ ] Need inline "required field" error msg on validation for the input fields in that popup form.
- [x] Position isn't automatically filling in user account info.
[Kevin] Still not working

General
- [ ] Add in all the success/error messages from #1277.

**Comment by scolapasta** [comment]
Removed a couple of the checkboxes from the description:
- Automatic log out of session expiration should forward to log in page. (this is already covered by issue #52)

- I saw a random weird state with the success message stuck on the page, and followed me to other, non-Guestbook pages (this was seen on a developer machine and has not been reproduced. Mentioned to QA to keep an eye open for this)

**Comment by sekmiller** [comment]
Finished as much as possible for Beta 13.  Please verify checked items and continue others in a new ticket for Beta 14 and beyond.  Final check-in just after noon 2/18.  Please make a build before testing.

**Comment by kcondon** [comment]
Tested fixed items, updated status and opened a new ticket, part deux (#1477) for remainder.
Closing
