### ISSUE TITLE
Terms of Use: Allows select custom licensing but leaving terms of use blank.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1413]
Minor issue but you can select custom licensing but then put nothing for terms of use.

**Comment by eaquigley** [comment]
@kcondon Merce said she was fine with this. I chatted with her about it last week.

**Comment by kcondon** [comment]
OK but then when you try to use it, you cannot download anything because the checkbox does not appear.
________________________________

**Comment by eaquigley** [comment]
@kcondon the checkbox for the file doesn't appear? which checkbox?

**Comment by kcondon** [comment]
Sorry, I was speaking in context: the "I accept" checkbox on the TOU popup doesn't appear if you select custom license but leave TOU blank. Since the code thinks there is a TOU but does not display a "I accept" checkbox if it is blank, you cannot ever accept and download in this situation. I know it is an edge case but weird.

________________________________

**Comment by eaquigley** [comment]
@kcondon I'm not able to reproduce this issue. I tried with a guestbook, without a guestbook, logged in, not logged in, and I'm not seeing this. When I had selected no license and didn't fill out terms of use,  I was able to immediately download the file.

**Comment by eaquigley** [comment]
my bad @kcondon! @sekmiller showed me the issue. sorry!

**Comment by sekmiller** [comment]
Removed Checkbox for accept in all cases.  Now the accept button is sufficient for accepting TOU.

**Comment by kcondon** [comment]
OK, works, closing
