### ISSUE TITLE
Terms of Use: Does not prompt when choosing Explore.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1414]
Terms of use popup appears on download for a tabular file but not for explore, which allows downloading of subsets.

**Comment by scolapasta** [comment]
It also doesn't prompt when downloading alternate formats.

**Comment by sekmiller** [comment]
Fixed for alternate formats and explore (minor issue with two ravens not opening in new window after popup will be a separate issue)

new build required for testing

**Comment by posixeleni** [comment]
Tested and works as expected. Prompted for ToU for alternate formats and when selecting Explore.

Closing.
