### ISSUE TITLE
Terms of Use: remove checkbox and just use the accept button at the bottom as it is duplication.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1415]
When terms of access is enabled, the popup only shows an accept button at the bottom. When terms of use is enabled, it has an I accept checkbox as well as the accept button at the bottom. This is a duplication, though it won't work if you don't click the checkbox. 

It looks weird when you have both tou and toa enabled with the checkbox in the middle and the accept button at the bottom. So, please just remove the checkbox and make the accept button work for tou as well. Thanks!

**Comment by sekmiller** [comment]
Removed TOU check box - Validation now assumes that clicking the accept button is acceptance of TOU

**Comment by kcondon** [comment]
OK, checkbox removed and still works. Closing
