### ISSUE TITLE
Metadata blocks: if parent has field has required, child dv's should be forced to be required

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#1416]

**Comment by scolapasta** [comment]
Discussed with @mcrosas and @sekmiller and we decided that we will not do this. If a child inherits, it will have same requirements as parent, but if they turn off inheritance, they'll be able to turn off required (unless the dataset field type is system required).

**Comment by sbarbosadataverse** [comment]
tested during beta 14 review--and able to change options in child dataverse, when parent has "required" fields.
