### ISSUE TITLE
Create Dataverse: If don't specify a dv subject and save, inline validation error squished and checkboxes become red.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1421]
Create Dataverse: If don't specify a dv subject and save, inline validation error squished and checkboxes become red.

Also, mouseover says: ???dataverse.subjegt.title???  Maybe due to a typo in the name?

**Comment by sekmiller** [comment]
Mike, can you help out on the UI here?  Thanks!

**Comment by mheppler** [comment]
Cleaned up the validation error layout. Fixed typo that broke Subject tooltip description on Dataverse General Information create/edit workflow.

**Comment by kcondon** [comment]
OK, they're still evil (red) but looks good, closing.
