### ISSUE TITLE
Shibboleth: allow for configuration of attributes used for user identification

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#1422]
eppn (eduPersonPrincipalName) is a Shibboleth attribute supported by http://testshib.org and [Harvard's Shibboleth](http://iam.harvard.edu/resources/saml-shibboleth-attributes) to uniquely identify users, but other attributes are in common use and should be supported:
- **ePTID** (eduPersonTargetedID) is described by InCommon as ["a powerful alternative to the use of eduPersonPrincipalName"](https://www.incommon.org/federation/attributesummary.html) and is supported by [surfnet.nl](https://wiki.surfnet.nl/display/surfconextdev/Attributes+in+SURFconext)
- **NameID** seems popular outside of higher education in the US, used by [surfnet.nl](https://wiki.surfnet.nl/display/surfconextdev/Attributes+in+SURFconext) and [in industry](https://lists.iq.harvard.edu/pipermail/dvn-auth/2014-July/000016.html).

At minimum, someone installing Dataverse should be able to specify globally the order in which the attributes should be checked for all Identity Providers (IdPs). Perhaps the default order could be:
1. ePTID
2. eppn
3. NameID

Perhaps people installing Dataverse should also be able to override the default order on a per-IdP basis, if certain IdPs are known to prefer one attribute over others.

From what I understand, people running mod_shib ( https://shibboleth.net/products/service-provider.html ) have a lot of control over [attribute mapping](https://wiki.shibboleth.net/confluence/display/SHIB2/NativeSPAttributeExtractor) so no matter what we come up with for configuration options with Dataverse, people installing Dataverse **should** have a fair amount of control to re-map attributes (from NameID to ePTID or whatever) with their Shibboleth mod_shib/shibd Service Provider (SP) service.

See also discussion in the [Shibboleth Functional Requirements Document for Dataverse 4.0](https://docs.google.com/document/d/12Qru8Gjq4oDUiodI00oObHJog65S7QzFfFZuPU3n8aU/edit?usp=sharing).

**Comment by marlenaerdos** [comment]
Hi Phil,   I think you are misunderstanding the purpose of the these identity-oriented attributes when you talk about "ordering." Either that or I'm mis-understanding your business case :-).  Generally, identity and identifier attributes are used for account-finding and also authorization.  And other attributes (like roles and groups) also factor into authorization.  There's not really an "ordering" but rather a question of "purpose" for each attribute.  An IdP is generally only going to send you one of the attributes you list for a given user. Its purpose is "account-finding" if applicable, and/or  "identifier-based authorization."   --Marlena

**Comment by pdurbin** [comment]
> An IdP is generally only going to send you one of the attributes you list for a given user.

@marlenaerdos you would certainly know better than I would, but my read of https://wiki.surfnet.nl/display/surfconextdev/Attributes+in+SURFconext is that they send both NameID and ePTID: "The user's identity is transmitted in the form of the NameID element of the SAML statement... For convenience, this identifier is duplicated in the SAML attribute eduPersonTargetedID". This is a service used by @bencomp and http://dataverse.nl

**Comment by marlenaerdos** [comment]
Hi Phil,

I took a look at what Surfnet says it does.

If sure looks like Surfnet isn't following the definition or intent of
eduPersonTargeted Id.

The intent is a persistent, non-reassigned, opaque identifier for a
principal that is specific to each SP.

Here's the eduPerson spec bookmarked to the definition:

http://software.internet2.edu/eduperson/internet2-mace-dir-eduperson-201310
.html#eduPersonTargetedID


My opinion:  It's great to look at examples, but the spec should rule
unless there's a good reason to ignore it.


My best,
Marlena
617-872-9736 






-----Original Message-----
From: Philip Durbin <notifications@github.com>
Reply-To: IQSS/dataverse
<reply+0077d8cd710fc29cce6dd5bf0649bf18878d20f74d97d02a92cf0000000110eb7db1
92a169ce0360f32a@reply.github.com>
Date: Thursday, February 5, 2015 at 13:51 PM
To: IQSS/dataverse <dataverse@noreply.github.com>
Cc: Marlena Erdos <marlena_erdos@harvard.edu>
Subject: Re: [dataverse] Shibboleth: allow for configuration of attributes
used for user identification (#1422)

**Comment by scolapasta** [comment]
Optimistically setting this to beta 15, but if it has to wait until 4.01, we may need to defer it.

**Comment by pdurbin** [comment]
I'm under the impression that I'm the only one that wasn't very comfortable with the fact that "eppn" is hard-coded as the identifier for users. I guess there's no problem to solve until someone complains. Closing.
