### ISSUE TITLE
Permissions: Add private DS role, so ds can add to unreleased dv like in v3.6.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1426]
Currently there is no easy way to make someone a contributor to an unreleased dv if access perms require assignment. The current DS role only gives add dataset, when the also need view unpublished dataverse. 

This is something that worked in v3.6 and seems like a necessary, out of the box option, especially for groups working on stuff pre-publication. 

So, this ticket is requesting adding a new role or enhancing the existing DS role to include view unpublished dataverse.

**Comment by eaquigley** [comment]
Will add a "Member" role with view unpublished dataverse and view unpublished dataverse.

**Comment by scolapasta** [comment]
Added member role, but needs a better description (as do other roles).

@eaquigley can you take a look at the roles and update them. They are in the api/data directory and you should be able to just update via github. Let me know if you have any other questions.

(Side note, what did we end up deciding about "Manager"?)

**Comment by eaquigley** [comment]
@kcondon I've been updating the display names for the roles and will be adding in descriptions as well. Here is a doc with more information for you when you go to test: https://docs.google.com/document/d/11LuKLswjhGcSdzcFCXdeLgFFrtJ8OrTFfFlFuI3nRLk/edit?usp=sharing

**Comment by sbarbosadataverse** [comment]
Contributor
and
Member

can view unpublished dataverse


![jypvc2itan6b-uuh1h2jzhi4fjsipfku9gc-e8l3qs0](https://cloud.githubusercontent.com/assets/8322346/6906306/1933bc88-d6fc-11e4-8b1e-a72e6c6379f3.png)


![nx4uebsealfqjg3kiq8f7j6gdkgaphlkmb2xfjduklk](https://cloud.githubusercontent.com/assets/8322346/6906272/dd68f380-d6fb-11e4-988d-d77738cd5798.png)

**Comment by sbarbosadataverse** [comment]
Not able to finish testing until "permissions assignment" is working again.

**Comment by sbarbosadataverse** [comment]
Members role added with permissions to view unpublished dataverse/dataset
contributor can view unpublished dataset
