### ISSUE TITLE
View Dataset: Keyword label is missing from above the fold info.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1427]
Eleni reported that the keyword values are displayed but the label is not, see original comment in #1262:
@sekmiller Should we be seeing this fix in build? I see the values for the Keyword field and the description but I dont see the field name "Keyword"

![image](https://cloud.githubusercontent.com/assets/5013837/6043929/f53b3d88-ac5d-11e4-8ddc-a71dea8b15dd.png)

**Comment by sekmiller** [comment]
Added Keyword Display Title to bundle

**Comment by kcondon** [comment]
Label added, closing
