### ISSUE TITLE
Adv Search: Selecting subject field with & results in no results

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1428]
In adv search, choosing Medicine, Health & Life Sciences for subject under Citation results in an error:
Search Syntax Error: Cannot parse 'subject:"Medicine, Health': Lexical error at line 1, column 26.  Encountered: <EOF> after : "\"Medicine, Health"

**Comment by scolapasta** [comment]
Added urlencoding the query part of the URL

**Comment by kcondon** [comment]
Error fixed but now cannot find datasets with this subject. Passing back to fix adv search/index.

**Comment by scolapasta** [comment]
I tried on dvn-build. There is one study with this subject and when I did an advanced search, it was returned.

**Comment by kcondon** [comment]
OK, I see the issue. Both dv and ds have the same subject controlled vocab and I was accidentally searching on the dv controlled vocab.

________________________________

**Comment by scolapasta** [comment]
So is still an issue?

**Comment by pdurbin** [comment]
I changed the Solr field type in #1681 so I'd recommend testing that ticket and this one at the same time.

**Comment by posixeleni** [comment]
Once #1709 fix is reflected in dvn-build the & (ampersand) will no longer be in the subject

**Comment by posixeleni** [comment]
Based on @pdurbin fix in #1681 the search is now working:

Works when you search for Dataverses or Datasets in Advance Search that have Medicine, Health & Life Sciences:
![image](https://cloud.githubusercontent.com/assets/5013837/6757562/55aecab4-cf08-11e4-891b-c61b033cf751.png)

**Comment by posixeleni** [comment]
Closing.
