### ISSUE TITLE
Dataverse - Create/Edit General Information Top Section Clean Up

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1429]
With all the new additional features we've added to this form, without much attention to how it looks overall, it needs a little UI clean up.

**Comment by mheppler** [comment]
Cleaned up the top section of the Dataverse General Information create/edit form. Removed subject from the XHTML. Cleaned up the Metadata Fields section.

Related #1473, #1452

**Comment by eaquigley** [comment]
Looks much better. Closing ticket.
