### ISSUE TITLE
Search: New metadata block uses yes/no as controlled vocab. Yes search works, no returns "no" results.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1432]
Search: New metadata block uses yes/no as controlled vocab. Yes search works, no returns "no" results.

Probably no is a stop word. I believe changing stop words in Solr is easy, just a config file.

**Comment by pdurbin** [comment]
> Probably no is a stop word. I believe changing stop words in Solr is easy, just a config file

@kcondon you're absolutely right. Please try https://github.com/IQSS/dataverse/blob/master/conf/solr/4.6.0/stopwords_en.txt where I've removed "no" as a stop word. You'll need to stop Solr, replace the file, and, start Solr again, and re-index.

After this I was able to find "Is the original code available?: No" with a search for "no". From a Solr perspective, the field being matched was `"PSRI2":"No"`.

Passing to QA. Like schema.xml, customized stop words files should probably go in the installer. And we should document them.

**Comment by sbarbosadataverse** [comment]
Yes returns results
No does not return results
One study containing both custom values used in ARCS metadata template

![aqghmrxicmp38l4x1jym3jbszdwwzha66t0ag-l_lhs](https://cloud.githubusercontent.com/assets/8322346/6834994/27c498e0-d30e-11e4-9940-376062c4d7fe.png)

![tmwkxpybagtzyoyaqomkija3ucyabl-zjrpluzay2b0](https://cloud.githubusercontent.com/assets/8322346/6834998/2b41fc74-d30e-11e4-9098-65f0033a8f45.png)

**Comment by sbarbosadataverse** [comment]
Search: New metadata block uses yes/no as controlled vocab/ Yes and No search returns accurate results

![gklx_s7qfd_4ct12j9s7wobscoorrh8_xmdco3o22bk](https://cloud.githubusercontent.com/assets/8322346/6870556/40d417aa-d473-11e4-9aee-3418d18e8945.png)
