### ISSUE TITLE
Thumbnail: Changing default thumbnail generates a new dataset version.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1433]
Opening this ticket as the desired behavior needs to be discussed/ determined.

Currently, selecting a default thumbnail image applies to all dataset versions, regardless of which version the image actually resides in, whether only old versions or latest.

Also, selecting or changing the default thumbnail while on a published version will create a new draft version. This seems to me to be incorrect since this information is app presentation rather than a matter of academic/public record.

**Comment by eaquigley** [comment]
during the meeting on 2/6, we agreed that this was fine. passing to QA to close.

**Comment by kcondon** [comment]
Closing
