### ISSUE TITLE
Linked Datasets: Couple issues

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1435]
Found by Mike, copied from larger ticket: #113 

1. Success message didn't display when I linked a dataset to a dataverse AND THEN immediately linked it a second dataverse of mine.

2. Popup message for a dataset that is already linked to all of my dataverses, is the same message if I have zero dataverses.

**Comment by sekmiller** [comment]
Added a distinctive message when no data verses remain.

**Comment by sekmiller** [comment]
Don't know what to do about non-refreshing success message.  I think there is another ticket for success messages overstaying their welcome....

**Comment by mheppler** [comment]
@sekmiller -- re: overstaying/non-refreshing success message

I think I can find some possible javascript solutions for this, so if you have a ticket for it, shoot it my way, and I can investigate. I can't promise that it won't involve some backend assistance, but, at the least, I should be able to help identify a way to go about a solution.

**Comment by kcondon** [comment]
Works, closing
