### ISSUE TITLE
Publish Dataset: Sometimes publishing a dataset is very slow, 1min

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1436]
Sometimes publishing a dataset is very slow, 1min
This is intermittent and mostly is ok but sometimes seems broken. When it is, I have observed this query in the server log and only when it completes does publish complete.

[2015-02-05T18:58:11.442-0500] [glassfish 4.1] [INFO] [] [] [tid: _ThreadID=52 _ThreadName=Thread-8] [timeMillis: 1423180691442] [levelValue: 800] [[
  EJBQueryImpl(ReadObjectQuery(referenceClass=DatasetVersionUser sql="SELECT DATASETVERSIONID, USERIDENTIFIER, LASTUPDATEDATE, datasetversion_id FROM DatasetVersion_DataverseUser WHERE ((DATASETVERSIONID = ?) AND (USERIDENTIFIER = ?))"))]]

**Comment by eaquigley** [comment]
Hey @kcondon do we have data for production to see if publishing is still taking this long? I guess I'm asking if that query you list above is still showing up. If not, let's close this issue! :)

**Comment by kcondon** [comment]
@eaquigley no, haven't see it but maybe Sonia has? Looks like it may affect datasets that have lots of versions.

**Comment by eaquigley** [comment]
@kcondon I tried this on beta with a dataset that has many versions and it was always less than 3 seconds for publishing. I think this one can be closed.
