### ISSUE TITLE
Linked Datasets: Can't link to a dataset in the root dv.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1437]
Can't link to a dataset in the root dv.
I checked with Gustavo and he thought it was a bug though there is/ may be some logic about preventing linking to root dv and that might cause this unintended? consequence.

**Comment by sekmiller** [comment]
Fixed and checked in. Now the only dataverse you are not allowed to link to is the one that already owns it.

**Comment by kcondon** [comment]
Works, closing
