### ISSUE TITLE
Configure Harvard Dataverse Root for Release

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#1438]
During our 2/6 Dataverse review meeting Merce asked that we:

1. Create a dataset template at the root for Harvard Dataverse: Have Harvard Dataverse as the Distributor. Any Dataverse directly under Harvard needs to have the Harvard Dataverse template pre-selected.
2. List of which Featured Dataverses to show on the Harvard Dataverse root.
- [x]  3. Branding: @eaquigley will get harvard logo approval (HPAC branding guide).

**Comment by eaquigley** [comment]
Featured Dataverses:
- Harvard Smithsonian
- Data-PASS
- PSI
- Avahan
- Murray

**Comment by eaquigley** [comment]
Link to branding guidelines: http://guidelines.hwp.harvard.edu/color-palette (Need to log in via PIN)

**Comment by eaquigley** [comment]
Logo from HPAC for customization: 
![harvardshield_cmyk](https://cloud.githubusercontent.com/assets/5922904/6741053/07cf083e-ce5b-11e4-8b39-299d7ab10ae8.jpg)

@mcrosas are you still fine with the featured dataverses list above?

**Comment by mcrosas** [comment]
Yes @eaquigley , still fine with these featured Dataverses to start. It would be nice to have some from journals and some from biomedical data, but we can add them later.

BIG logo, by the way

**Comment by eaquigley** [comment]
Closing due to another ticket created for this post migration.
