### ISSUE TITLE
Solr: empty dataverses when content expected

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#1439]
In 1eb10af I documented a workaround for a problem I encountered locally wherein I was seeing what looked like empty dataverses when I expected to see content.

This is what I wrote in that commit (which now appears at http://guides.dataverse.org/en/latest/installation/installation-main.html#solr-configuration ):

> If ``WARN org.eclipse.jetty.http.HttpParser – HttpParser Full for /127.0.0.1:8983`` appears in the Solr log, adding ``<Set name="requestHeaderSize">8192</Set>`` (or a higher number of bytes) to Solr's jetty.xml in the section matching the XPath expression ``//Call[@name='addConnector']/Arg/New[@class='org.eclipse.jetty.server.bio.SocketConnector']`` may resolve the issue. See also https://support.lucidworks.com/hc/en-us/articles/201424796-Error-when-submitting-large-query-strings-

I could also add this is what you see in the Glassfish server.log: "Search Syntax Error: Expected content type application/octet-stream but got ."

As https://support.lucidworks.com/hc/en-us/articles/201424796-Error-when-submitting-large-query-strings- explains, the change to jetty.xml Solr config file is one fix. Another may be switching from GET to POST.

I'm not sure what a user should see when a system error like this happens. Showing the same message as you see for an empty dataverse doesn't seem right. This is sort of status page ( #131 ) or Solr down ( #1042 ) territory.

**Comment by pdurbin** [comment]
Since the related issue #2311 got assigned to the 4.2 milestone, I'm going to put this one in 4.2 as well and put it in QA. The question is if the explanation about the jetty.xml file at http://guides.dataverse.org/en/4.2/installation/installation-main.html#solr-configuration is good enough. I also added a note to the [Google doc](https://docs.google.com/document/d/1GLky44JbtCNhGuavLXGEP8WPNdjbyHNxalEGjR78MaA/edit?usp=sharing) linked from #2321.

**Comment by kcondon** [comment]
Probably fine. Not sure everyone would immediately be able to parse an xpath expression but at least the accompanying link gives a real life example. The value 8192 is too small for our production config once MyData was added so perhaps this value should be changed to something like Raman suggested in 2311? Anyway, seems ok, closing.
