### ISSUE TITLE
Bundle.properties -- Clean Up Various Messages

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1442]
Here is a general catch all outline of various issues with Bundle.properties that need to be fixed.

Labels using "Tooltip description"
- [x] dataverse.theme.inheritCustomization.title
- [x] dataverse.permissions.Q2.title
- [x] file.dataFilesTab.terms.list.termsOfUse.license.title
- [x] file.dataFilesTab.terms.list.termsOfUse.termsOfUse.title
- [x] file.dataFilesTab.terms.list.termsOfAccess.restrictedFiles.title
- [x] file.dataFilesTab.terms.list.termsOfAccess.termsOfsAccess.title
- [x] file.dataFilesTab.terms.list.termsOfAccess.requestAccess.title

Needs Tooltips
- [x] file.tabularDataTags.title
- [x] file.spss-savEncoding.title
- [x] file.fileTags.title

Change Tooltip:
- [x] Tool tip for email button on dataverse pages needs to change to say dataverse not dataset

Email vs E-mail
- [x] email=Email
- [x] dataverse.email=E-mail
- [x] dataverse.email.title=The e-mail address(es) of the contact(s) for the Dataverse.
- [x] dataverse.contact=Email Dataverse Contact

ALL CAPS
- [x] dataverse.theme.logo.format.selectTab.square=SQUARE
- [x] dataverse.theme.logo.format.selectTab.rectangle=RECTANGLE
- [x] dataverse.theme.logo.alignment.selectTab.left=LEFT
- [x] dataverse.theme.logo.alignment.selectTab.center=CENTER
- [x] dataverse.theme.logo.alignment.selectTab.right=RIGHT

"Dataverse" vs "dataverse"
- [x] header.search.title=Search all Dataverses...
- [x] dataverse.search.input.watermark=Search this dataverse...

Capitalize?
- [x] dataverse.permissions.roles.edit=Edit role
- [x] dataverse.permissions.roles.copy=Copy role
-  [x] authenticationProvidersAvailable.tip={0}There are no active authentication providers{1}If you are a system administrator, please enable one using the api.{2}If you are not a system administrator, please talk to one.

Uncapitalize?
- [x]  file.dataFilesTab.terms.list.guestbook.inUse=Custom Guestbook in use
- [x] file.dataFilesTab.terms.list.guestbook.noSelected=No Guestbook selected.
- [x] file.dataFilesTab.terms.description=These are all the License + Terms for your dataset.

"Dataverse" vs "dataverse"
- [x] dataverse.title=The project, department, university, or professor this Dataverse will contain data for.
- [x] dataverse.identifier.title=Short name used for the URL of this Dataverse.
- [x] dataverse.affiliation.title=The organization with which this Dataverse is affiliated.
-[x]  dataverse.link.dataverse.choose=Choose which of your dataverses you would like to link this dataverse to.
- [x] dataverse.link.dataset.choose=Choose which of your dataverses you would like to link this dataset to.
- ...and many more

"e.g." vs "i.e."
- [x] dataset.manageGuestbooks.noGuestbooks.why.reason1=Guestbooks allow you to collect data about who is downloading the files from your datasets. You can decide to collect account information (username, given name & last name, affiliation, etc.) as well as create custom questions (e.g., What do you plan to use this data for?).
- [x] file.dataFilesTab.terms.list.termsOfUse.addInfo.permissions.title=Determine if any special permissions are required to access a resource (e.g., if form is a needed and where to access the form).
- [x] advanced.search.files.fileType.tip=The extension for a file, e.g. CSV, zip, Stata, R, PDF, JPEG, etc.
- [x] file.dataFilesTab.terms.list.guestbook.noSelected.title=User information (i.e., name, email, institution, and position) will be collected when files are downloaded.
- [x] file.dataFilesTab.terms.list.guestbook.noAvailable.title=User information (i.e., name, email, institution, and position) will be collected when files are downloaded.

Double or Single Quotes?
- [x] dataverse.publish.tip=Are you sure you want to publish your dataverse? Once you do so it must remain 'Published'.
- [x] dataset.manageTemplates.tab.action.btn.delete.dialog.tip=Are you sure you want to delete this template? This action may not be 'Undone'.
-  [x] dataset.manageGuestbooks.tab.action.btn.delete.dialog.tip=Are you sure you want to delete this guestbook? This action may not be 'Undone'.
- [x]  file.dataFilesTab.terms.list.termsOfUse.license.txt=CC0 - "Public Domain Dedication"

Extra Period
- [x] file.dataFilesTab.terms.list.termsOfUse.addInfo.permissions.title=Determine if any special permissions are required to access a resource (e.g., if form is a needed and where to access the form). .

Typo
- [x] file.deleteDialog.tip=Are you sure you want to delete your dataset? You cannont undelete this dataset.

Placeholder Text
- [x] remove dataset.email.tip=Dataverse 4.0 Beta cannot email dataset contacts. Look for this feature in Dataverse 4.0!
- [x] file.spss-porExtraLabels=(optional!) Upload text file with extra variable labels

Escape Special Characters?
- [x] feedback.header=Send feedback to the Dataverse development team\!
- [x]  toPublish=Don't forget to publish it\!
- [x] toReview=Don't forget to publish it or send it back to the contributor\!
- [x] dataverse.permissions.Q2.answer=A contributor can be a(n)…

Dynamic Version Number?
- [x] welcome=Welcome to Dataverse 4.0 Beta\! Please take a look around, try everything out, and check out our

Conditional Text Example
- [x] file.dataFilesTab.terms.list.termsOfAccess.restrictedFiles.txt=There {0, choice, 0#are|1#is|2#are} {0} restricted {0, choice, 0#files|1#file|2#files} in this dataset.

Huh?
- [x] user.toEditDetail=You have logged in through your institution. To edit account detaThe e-mail address(es) of the contact(s) for the Dataverse.ils, please visit the account page for your institution.

Messages to change:
- [x] Browse/Search Facets: first help text change from in use to used to meet tense used in second part of help text
- [x] Edit Access pop up: What should be the default role for someone adding datasets to this dataverse? and A contributor can be a(n).... needs to be updated
- [x] Guestbook section in License + Terms page
- [x] May Not Publish change to Cannot Publish Dataverse or something more descriptive (in the cannot publish pop up)

**Comment by eaquigley** [comment]
All of these items have been done or checked to see if anything needed to be changed. Passing to QA.
