### ISSUE TITLE
Log In & Shibboleth: Onboarding Process

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1444]
Due to passwords needing to be changed and Shibboleth account conversions, we need a robust, interactive, and helpful onboarding process to let users know how their accounts need to be updated. 

Things to take into consideration:
1) In 3.6, a user could have multiple accounts using the same email address. This cannot happen in 4.0
2) In 3.6, a user account password did not have restrictions, in 4.0 a password must be 6 characters and include at least one letter and one number
3) In 4.0, we will need a way for a user to confirm their account via their email address and user name
4) In 4.0, once a user confirms their account (or at the same time, but not sure how that would work) a user will also need to change their password to be compatible with our new restrictions
5) In 3.6, built in users were the only type of user, in 4.0 we also have shibboleth users
6) Shibboleth users---user names? yes, no? the ongoing debate. If yes, how do we set those up? 
7) Add something to Sign Up page about Shibboleth (i.e.-want to use your institutional account? go here to do so)

Research/Design Inspirations:
http://www.useronboard.com/onboarding-teardowns/
http://www.quora.com/UI-UX-Design-Patterns/What-are-good-examples-of-registration-flows-that-require-a-lot-of-info-but-manage-to-make-it-a-painless-experience
http://www.lukew.com/ff/entry.asp?1906

**Comment by eaquigley** [comment]
Shibboleth Use Cases:
1. User DOES NOT have a Dataverse account, creates account through Shibboleth
2. User DOES have a Dataverse account, creates another account through Shibboleth
3. User DOES have a Dataverse account and converts it to a Shibboleth account

**Comment by mheppler** [comment]
Mockups for Shibboleth workflows.

https://iqssharvard.mybalsamiq.com/projects/loginwithshibboleth-version3-dataverse40/grid

**Comment by pdurbin** [comment]
@scolapasta and I noticed that Harvard Shibboleth will send "One or more of the following values: faculty, staff, student, affiliate, and member" per http://iam.harvard.edu/resources/saml-shibboleth-attributes and in [a meeting](https://docs.google.com/document/d/1zP80gaCx8a1UGD7GNxxjlKbYLBdbaxpQs1mapcrqON4/edit?usp=sharing) we decided we'd like to persist these to the "authenticatedusers" table in the database.

The question (for @mcrosas and @eaquigley especially) is, what about non-Shibboleth users? When they sign up for an account, should "Position" allow multiple values? Should there be a plus button so you can enter both "staff" and "student"? The backend question is if we should separate these values by a semicolon (ugly) or create a new table (better database design).

**Comment by eaquigley** [comment]
@pdurbin, what do we do with Position? Is it used anywhere in the metadata of dataverses, datasets, or files?

**Comment by pdurbin** [comment]
I have no idea what "position" is used for. As of this writing it's only stored for "builtin" users.

**Comment by scolapasta** [comment]
I don't think it's used for anything - but as of now it is stored, or at least storable, for all Authenticated Users.

**Comment by pdurbin** [comment]
I spoke with @mcrosas and @eaquigley about "position" the other week and I thought there was interest in using ORCID (and other identifiers) per #923.

What I'm trying to say is that I'm not sure we should persist "position" at all until we've thought it through. As I mentioned above, it would be a little ugly and hackish to separate more than one position with semicolons in the field database.

**Comment by eaquigley** [comment]
Mockups: https://iqssharvard.mybalsamiq.com/projects/36to40builtinaccounts/grid

These are based off of discussions with @mcrosas and @scolapasta as to what users will need to change account wise when first logging into Dataverse 4.0. 

Still missing:
- [ ] a user could have multiple accounts using the same email address, in 4.0, one account per email address in order for the forget password functionality to work. need to add this in to the mockups.

**Comment by mheppler** [comment]
Added static "Welcome to Dataverse" header and warning message to the Edit Password form on the Account page.

**Comment by scolapasta** [comment]
The plan is through migration to make sure there are no multiple e-mails. If that changes, we may need to repoen this.

**Comment by kcondon** [comment]
1. Shib convert account works fine. When old user tries logging in, says invalid user/pass. @eaquigley is this OK?
2. Migrated user change password does not work, opened separate ticket.
3. Shib and other account, create separate -is this even a situation? Isn't it just the shib log on with no builtin user with same email? In that case it works.

Closing

**Comment by xoroz** [comment]
Could anyone confirm that using shibboleth and ADFS the attribute position is stored in dv?

**Comment by djbrooke** [comment]
Hey @xoroz - I'm not sure, and this is a pretty old issue. Is this something that you can test? Also, if you're using Microsoft for identity management, note that we do have login using Microsoft (as of 4.18), and that may be a better option.
