### ISSUE TITLE
Users are unable to change their username

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#1445]
To help users distinguish between two people with the same name we should show the username next to the "display name". Examples from GitHub and Trello of a search for "John Smith" are below.

Ideally, users should be able to change their username at any point, as long as the username isn't taken.

Local/Builtin users should be allowed to pick their own username at sign up (perhaps auto-suggested by the name they entered). We **could** let Shibboleth users pick a username, or to expedite their signup experience we could simply generate one for them (which they could change later) based on their email address, for example. For more on onboarding, see #1444

For Builtin users, the username is used both to disambiguate them within the system and for login.

It would be relatively easy to simply expose the "useridentifier" field from the "authenticateduser" table but doing so is currently fraught with peril because as of this writing this string is used to look up users by the "roleassignment" table per #1151 . A username change would require updating this table.

![github](https://cloud.githubusercontent.com/assets/21006/6120913/a7b4852e-b0a9-11e4-905e-ebeeee5c3661.png)

![trello](https://cloud.githubusercontent.com/assets/21006/6120914/ace9fa92-b0a9-11e4-9fdd-c980b5fa8cca.png)

**Comment by eaquigley** [comment]
@pdurbin Looking over this, I'm inclined for us to go with a hybrid of what I'm seeing in these two examples. Since we collect Affiliation information for a user, we should display: username, first name last name, and affiliation. If there are multiple users with the same name, I'm not positive only having the username would help someone distinguish who two different people are thus the inclusion of the affiliation.

**Comment by pdurbin** [comment]
> Since we collect Affiliation information for a user

As of this writing we only collect affiliation (and position) for **builtin** users and store these values in the **builtinuser** table. This is a bug. At https://github.com/IQSS/dataverse/issues/923#issuecomment-73573356 I'm arguing that if we'd like to collect these values they should be stored in the **authenticatedusers** table. All users can make use of what's stored in the authenticatedusers table.

> I'm not positive only having the username would help someone distinguish who two different people are

Me neither. The value in a username is that its unique across the system. People can say, "No, no, no, I'm not **jsmith** in Dataverse! My username is **jasmith**. Please give **that** username access to the unpublished dataset and don't let that other username see it." While quite unlikely it's **possible** to have two people with the same name and same affiliation. This is not possible with username. They are always unique.

**Comment by eaquigley** [comment]
@pdurbin Is there a ticket to fix the authenticatedusers table?

**Comment by pdurbin** [comment]
> Is there a ticket to fix the authenticatedusers table?

@eaquigley not that I know of but #945 and #457 and #965 are related.

**Comment by pdurbin** [comment]
> It would be relatively easy to simply expose the "useridentifier" field from the "authenticateduser" table but doing so is currently fraught with peril

Uh oh. It looks like this is being done in #1584

**Comment by pdurbin** [comment]
To be clear, the "username" that is displayed for Shibboleth users (all users, really), is the `useridentifier` field from the `authenticateduser` table. An "@" sign is prepended, such that it looks like `@johndoe` this:

![screen shot 2016-10-05 at 11 26 26 am](https://cloud.githubusercontent.com/assets/21006/19119865/1f0735e2-8aef-11e6-892b-c50819c02aa7.png)

The problem is that this value cannot be changed. A sysadmin would have to issue SQL statements like the following (hat tip to @scolapasta ):

`update builtinuser set username='newusername' where username='oldusername';`

`update authenticateduser set useridentifier='newusername' where useridentifier='oldusername';`

`update authenticateduserlookup set persistentuserid='newusername' where persistentuserid='oldusername';`

`update roleassignment set assigneeidentifier='@newusername' where assigneeidentifier='@oldusername';`

(For extra credit, you could also update the "actionlogrecord" table.)

Instead of this we should add a column called `username` to the `authenticateduser` table and allow users to change their usernames in case of marriage or divorce, for example. Like GitHub (screenshot below), we can explain that changing your username may lead to unintended side effects ( https://help.github.com/articles/what-happens-when-i-change-my-username/ ).

![screen shot 2016-10-05 at 11 37 49 am](https://cloud.githubusercontent.com/assets/21006/19120224/2fec84b0-8af0-11e6-879b-601c20af0e91.png)

**Comment by pdurbin** [comment]
An example of a user wanting to change a username: https://help.hmdc.harvard.edu/Ticket/Display.html?id=247382

**Comment by pdurbin** [comment]
These days the `useridentifier` field from the `authenticateduser` is pretty well accepted as the username but it's still a bug that users can't change it. People get married and divorced. They should be able to change their username.

**Comment by pdurbin** [comment]
I guess no one thinks this is a significant problem so I'm closing this issue. If someone wants this, please open a fresh one.

**Comment by pdurbin** [comment]
Here's the fresh issue to track this problem of users being unable to change their username: #5515
