### ISSUE TITLE
Destroy dataset fails if dataset is linked to a Dataverse

### ISSUE THREAD

**Issue by ekraffmiller** [IQSS/dataverse#1446]
Need to update the Destroy Dataset command so that it removes any existing links before deleting the dataset

**Comment by scolapasta** [comment]
Destoy will now remove links.

**Comment by posixeleni** [comment]
I tested the ability to delete unpublished datasets that are linked to Dataverses, which works, but to close this particular I will need to reassign to @kcondon for him to try destroying a published dataset that is linked to a dataverse. Related to https://github.com/IQSS/dataverse/issues/506

I would do this myself but do not know how or if I can do this in the GUI or if this needs a certain command line script
