### ISSUE TITLE
Update Text & Messages Across Applications

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1447]
General Information Page:
- [x] Text for selecting Metadata Fields (Facets/Metadata Elements from Parent Dataverse)--uncheck to choose which metadata fields you want to use
- [x] Text for selecting Facets

Publish Messages:
- [x] Second part needs to change. 

Permissions: 
- [x] What type of contributor text change to "What should be the default role for someone adding datasets to this dataverse?"

Template:
- [x] Change text for when there are no templates created

Guestbook:
- [x] Change text for when there are no guestbooks created
- [x] Change "option buttons" text to "multiple choice" @sekmiller is taking care of this

Files:
- [x] No files found changed to No files added to this dataset.

Featured Dataverses when enabled:
- [x] Don't have "Featured Dataverses" label on the dataverse homepage when this is enabled.
-[x] Change display check box text to say, Display the dataverses selected below on the homepage for this dataverse.

Permissions:
- [x] Add information next to the Editor role signifying this is the role for contributor/review workflow

**Comment by mheppler** [comment]
This is related to #1442. These message belong in the Bundle.properties file.

**Comment by kcondon** [comment]
OK, all looks good except the last item didn't seem to be in place. Passing back to Liz since there needs to be additional decision making on it (manager role also relevant).

**Comment by eaquigley** [comment]
@kcondon I've added in the Submit datasets for review to the Editor role.

**Comment by kcondon** [comment]
OK, note is there, closing.
