### ISSUE TITLE
Export: Export study metadata upon release/ publication.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1448]
This was requested by a partner (U. Heidelberg):

we are highly interested in an automated export functionality (and
therefore availability via OAI) when a study is released.

**Comment by mheppler** [comment]
@sekmiller and I believe this was delivered as past of [4.5 - Metadata Export and Harvesting](https://github.com/IQSS/dataverse/milestone/50), so I am adding that label and passing to QA to close.

**Comment by kcondon** [comment]
Yes, seems to have been added. They may want something more or slightly different but the OAI/Export was delivered.
