### ISSUE TITLE
When only empty facets are selected in non-empty dataverse, "This Dataverse currently has no Dataverses, Datasets, or Files."

### ISSUE THREAD

**Issue by bencomp** [IQSS/dataverse#1449]
When I navigate to a dataverse without child dataverses and uncheck the boxes in front of Datasets and Files, I see a message suggesting that there is no content *at all* in that dataverse. I expect a message that the existing content is hidden, not non-existent.

For example, the [Shib dataverse](https://dataverse-demo.iq.harvard.edu/dataverse/shib?id=44&q=&types=dataverses&sort=release_or_create_date_dt&order=desc&page=1) in the demo instance:
![screen shot 2015-02-13 at 14 24 46](https://cloud.githubusercontent.com/assets/1303898/6187889/1ca3ad58-b38c-11e4-8247-524bce88ac64.png)

**Comment by eaquigley** [comment]
Great catch @bencomp. @scolapasta who should I send this to for fixing? The message needs to say, "This dataverse currently has no dataverses in it. You can add to it a dataverse by using the Add Data button on this page."

**Comment by scolapasta** [comment]
I think this is probably one for @pdurbin. Though can this be 4.0.x?

**Comment by pdurbin** [comment]
There are eight possible messaging scenarios depending on if you're logged in, if you can see the Add Data button, and if you're browsing or searching. @eaquigley and I went through all of them and the setup could be reproduced on apitest. In the list below the CAPS indicate comments you can see when you "view source". 

Not logged in:

- BROWSE GUEST ZERO COUNTS http://localhost:8080/dataverse/wrens This dataverse currently has no dataverses, datasets, or files. Please log in to see if you are able to add to it.
- BROWSE GUEST HIDDEN http://localhost:8080/dataverse/spruce?types=dataverses There are no dataverses within this dataverse. Please log in to see if you are able to add to it.
- SEARCH HIDDEN http://localhost:8080/dataverse.xhtml?q=bird&types=datasets%3Afiles There are no search results based on how you have narrowed your search. You can check out the search guide for tips.
- SEARCH ZERO COUNTS http://localhost:8080/?q=nosuchresult There are no dataverses, datasets, or files that match your search. Please try a new search by using other or broader terms. You can also check out the search guide for tips.

Logged in as "admin":

- BROWSE CAN_ADD ZERO COUNTS http://localhost:8080/dataverse/wrens This dataverse currently has no dataverses, datasets, or files. You can add to it by using the Add Data button on this page.
- BROWSE CAN_ADD HIDDEN http://localhost:8080/dataverse/spruce?types=dataverses There are no dataverses within this dataverse. You can add to it by using the Add Data button on this page.

Logged in as "sparrow":

- BROWSE NO_ADD_BUTTON ZERO COUNTS http://localhost:8080/dataverse/wrens This dataverse currently has no dataverses, datasets, or files. You can use the Email Dataverse Contact button above to ask about this dataverse or request access for this dataverse.
- BROWSE NO_ADD_BUTTON HIDDEN http://localhost:8080/dataverse/spruce?types=dataverses There are no dataverses within this dataverse.

Passing to QA.

**Comment by kcondon** [comment]
Looks good, closing

**Comment by pdurbin** [comment]
> Looks good except for case 3: search hidden.

Good catch @kcondon! In f4eef47 I fixed a boolean. Passing to QA.

**Comment by sbarbosadataverse** [comment]
Message active:
There are no dataverses within this dataverse. You can add to it by using the Add Data button on this page.
