### ISSUE TITLE
Switching from builtinuser table to authenticatedusertable for certain pages

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1450]
Currently the builtinuser table is being used to populate information on:
1. Account Information page
2. Create Dataverse/General Information Dataverse page
3. Create/Edit Dataset Metadata

however, since we have moved some components of the builtinuser table to the authenticateduser table, we need to change it so these pages are calling from the authenticateduser table.

**Comment by scolapasta** [comment]
#965 #945

**Comment by scolapasta** [comment]
I think this is all set for #2 and #3. #1 is a bit messy, so I suggest deferring display of account info for none built in (since they also cannot edit) to 4.0.x.

**Comment by eaquigley** [comment]
Passing to QA to confirm 2 & 3. Please send back to me after that so I can decide what to do with 1. thanks! @kcondon

**Comment by kcondon** [comment]
OK, 2,3 look good both with builtin and shib user. Passing back to Liz as requested.

**Comment by eaquigley** [comment]
We will the text from the Account Information edit dropdown appear in this tab instead of there.

**Comment by eaquigley** [comment]
@mheppler Currently when a user logs in via Shibb and goes to their account page, they see this:
![shibbaccount1](https://cloud.githubusercontent.com/assets/5922904/6355292/de0203ca-bc22-11e4-8ff7-98f53d66c1e8.jpg)

When they click on the Account Info dropdown, they see this:
![shibbaccount2](https://cloud.githubusercontent.com/assets/5922904/6355300/eb0827e8-bc22-11e4-8cf5-8aea40f5204c.jpg)
(bonus, this text is mentioned in the Bundle ticket #1442 )

We need to move the text from that dropdown (so only API Token is left) and have it displayed in the Account Information tab. However, that texts doesn't make sense so it should say: "You are logged in through your institution so Dataverse is not able to display your account information. If you need to update any of this information, please contact your institution."

**Comment by mheppler** [comment]
Added back user.toEditDetail message to bundle, and revised it to the suggested, updated text. Moved it from Account Information dropdown to the Account Information tab on the Account page.

**Comment by pdurbin** [comment]
> I suggest deferring display of account info for \[non\] built in (since they also cannot edit) to 4.0.x.

Is there a ticket for this? Shib users still see something like this:

![account_-_root_dataverse_-_2015-03-05_16 35 58](https://cloud.githubusercontent.com/assets/21006/6541700/508cb3c6-c4ad-11e4-87ce-02c164b99d7c.png)

**Comment by scolapasta** [comment]
This is what was decided for 4.0, rather than remove the tab (hence @equigley adding her comments).

One quick note: it's not that we can't display your account info (because we will in a future version, or at least the parts we get from shib, etc), so I think that line is a little misleading. Can we remove it?

**Comment by kcondon** [comment]
OK, message is there. @eaquigley wording is not exactly as you specified but seems close enough. Closing.
