### ISSUE TITLE
Search/Browse Results Cards - Improve Visual Separation

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1451]
Due to the lack of visual differences with the three types of results cards -- dataverses, datasets, files.

Suggestions were:

- Adding icons
- Adding color

**Comment by mheppler** [comment]
Related to #1178.

**Comment by mheppler** [comment]
Added result type icons to cards, as well as new border colors to visually separate result types. 81e1168d093723a1fb7925af77c6f1343f002d69

**Comment by kcondon** [comment]
OK, colors, icons in place, closing.
