### ISSUE TITLE
Dataverse Subject: Remove from General Information Page, Have it be populated by dataset subjects

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1452]
Per conversations with @mcrosas it makes more sense to have the subject of a dataverse be populated based off the subjects of the datasets contained within it. So we need to change the way it currently is in the application, including removing it as a selection from the General Information page for a dataverse.

**Comment by scolapasta** [comment]
Decision for 4.0 - we will remove subject as required and also remove from the UI and API.

When editing a datset, it will populate its ancestors subject, but if you remove a subject, that will not remove (eventually yes, but is extra work, since you have to then look at all datasets).

**Comment by mheppler** [comment]
Removed subject from the XHTML.

**Comment by scolapasta** [comment]
Removed subject from JsonParser.

Added logic to Publish command (better than when editing) to populate subject for its ancestors. (note that if the dv(s) subjects changed, it also reindexes the dv(s)).

There will still be issues when you remove subjects (though technically an old version is still that subject - but we are not keeping that for the dataset), when you deaccession, and when you destroy.

**Comment by eaquigley** [comment]
This is working the way it was described above. Closing ticket.
