### ISSUE TITLE
Metadata Blocks: Custom Blocks Need to Be Hidden

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1453]
We need to have a way for custom metadata blocks to only appear for the dataverses they are for. For example, the GSD block should only appear in the GSD dataverse general information page and its children. At the root (for Harvard) we should only see Citation, Social Sciences & Humanities, Astronomy & Astrophysics, Life Sciences, and Journal Metadata.

This is critical for migration and preexisting collections. cc: @mcrosas @posixeleni

**Comment by scolapasta** [comment]
This is not possible with the current design - metadatablocks were not designed to be specific to dataverses, but as global, standard blocks that are usable by anyone. 

We'll need to discuss what would need to change to handle something like this, how long it will take, and what consequences it may have (moving datasets, etc.)

**Comment by mcrosas** [comment]
@scolapast I thought of some ideas for doing this for now. We have to find
some solution for 4.0, which doesn't involve a big change.


Mercè Crosas, Ph.D.
Director of Data Science, IQSS
Harvard University
http://datascience.iq.harvard.edu

**Comment by sekmiller** [comment]
We will have to assign custom metadatablocks to data verses via an update query in the DB.  Let me know when you're ready to test and I'll walk you through it.  It will look something like this but the ids will be different:

update metadatablock set dataverse_id = 1 where id in (2, 3, 4, 6);
update metadatablock set dataverse_id = 48 where id = 5;
update metadatablock set dataverse_id = 30 where id = 7;
update metadatablock set dataverse_id = 27 where id = 8;
update metadatablock set dataverse_id = 25 where id = 9;

**Comment by kcondon** [comment]
OK, works, closing. Noticed a slight issue with no being able to save do not inherit from parent checkbox and select other blocks at once. Will open as a separate ticket. Closing.
