### ISSUE TITLE
Install: Set jvm -server option

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1455]
We need to make sure install sets the jvm -server option. -client is default and does not perform well.

**Comment by landreev** [comment]
Taking this for 4.3, another "low-hanging" installer issue.

**Comment by pdurbin** [comment]
For now, at least, I've **documented** this as part of #2521 in my pull request at #2895.

But yeah, it should go in the installer.

**Comment by landreev** [comment]
The installer now sets this, together with all the other JVM options. 
Since this is being done behind the scene, in the glassfish-setup shell script, with no interaction from the user, it didn't require any documentation updates.

**Comment by kcondon** [comment]
-server is not set and the prexisting jvm options continue to be set. Closing.
