### ISSUE TITLE
Clean up user code (review specific methods for shib and built in user on AuthenticatedUser)

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#1456]

**Comment by pdurbin** [comment]
@scolapasta what is this issue about?

**Comment by pdurbin** [comment]
"methods that were specific to shibboleth that ideally would exist in a general way or not at all"

**Comment by pdurbin** [comment]
As @mheppler suggested at https://github.com/IQSS/dataverse/issues/3486#issuecomment-268636806 I think we should close this issue in favor of #3486.

**Comment by mheppler** [comment]
Duplicate of **Improve consistency of various remote auth options (Shibboleth vs. OAuth) #3486**

**Comment by pdurbin** [comment]
@scolapasta do you agree that we should close this one?
