### ISSUE TITLE
Dataverse Search/Browse Card - File Permissions: Restricted File Icons

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1457]
Restricted files need to have the "restricted" and "restricted with access" icons added to the file search/browse cards on the dataverse page.

**Comment by landreev** [comment]
@mheppler
Mike,
I've added logic to the file card, for the "lock" and "unlocked lock" icons;
as of now, it's just showing text "(locked)" or "(unlocked)", depending on which one it is.
Could you please modify it to show your neat little icons instead?

**Comment by mheppler** [comment]
Added icons for restricted and restricted with access to file cards. Added default icons for dataverse and dataset to the preview for cards. Cleaned up markup and moved CSS to stylesheet.

**Comment by sbarbosadataverse** [comment]
Kevin---not sure what I'm testing here....

**Comment by kcondon** [comment]
@sbarbosadataverse Sonia, test to see when a file is restricted there is a lock icon for a user without permission and an unlocked icon for a user with permission. These should appear both on the files tab for a dataset and in the case of this ticket, on the file card in the browsing list.

**Comment by sbarbosadataverse** [comment]
Lock Icon - yes
Request Access - yes

![xo4j2ireu9yxinkyapfvatfl-dcewgwzeei5zskhd6o](https://cloud.githubusercontent.com/assets/8322346/6870033/bd344260-d46f-11e4-84f0-3e40011e386f.png)

Lock/Request Access does not show up when searching for a restricted file: F8.txt in this case:
![x8sd4cez7qbbpgfiguwfp9ptbfhesydgrtekgl0qs1y](https://cloud.githubusercontent.com/assets/8322346/6870137/5cc0b6ba-d470-11e4-8e8c-8857ace5c732.png)

Gave Eleni access to restricted file-asked her to search for the file after login, to see what lock icon she sees a "green" lock icon, and downloads without problem

Does not see "green" icon when searching for the file by name, from root dataverse

**Comment by sbarbosadataverse** [comment]
Restricted File Icon does not show up on search for restricted data files

**Comment by mheppler** [comment]
Fixed typo in render logic for restricted icons in a failed attempt to get them to display properly on file browse/search cards. c13bc257d3543e5c87df78907d14fe268810f3ce

Saw that @scolapasta was last in there with render logic improvements(?) on the icons in the name of performance enhancement. 40417938a9ee19842a6312b01edd3e67e660aaec

**Comment by scolapasta** [comment]
Rendering fixed.

**Comment by sbarbosadataverse** [comment]
Perfect~


![ahheqdv5yct9wfhx8cbd82zo0fu-qltq8oiwykohjry](https://cloud.githubusercontent.com/assets/8322346/6900617/c6c47e4a-d6d5-11e4-8c40-5576245e3b0a.png)
