### ISSUE TITLE
Dataverse Search/Browse Card - Linked Dataverse/Dataset/File: Linked Icon

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1459]
For any linked dataverse, dataset, file, that is displayed on the dataverse page, through the search-include, there needs to be a "linked" icon added to the search/browse card.

**Comment by eaquigley** [comment]
@scolapasta and @sekmiller need to talk to @pdurbin about this due to linked dv/ds not being something in the index currently.

**Comment by mheppler** [comment]
Added link icon to the far right of the search/browse cards for linked dataverses/datasets/files.

**Comment by posixeleni** [comment]
Works as expected. Link icon shows up in Dataset card of the linked Dataverse

![image](https://cloud.githubusercontent.com/assets/5013837/6736201/cd26d4b2-ce39-11e4-8d14-01ead3f10377.png)

Closing.
