### ISSUE TITLE
Notifications/Dataverse Account - Various Clean Up

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1460]
- [x] File permissions notifications should link to File Permissions page, and not the dataset page. (From #1348)
- [x] Dataverse links do not using Pretty Faces URLs.
- [x] Custom icons need to be added for dataverses, datasets, files.

**Comment by mheppler** [comment]
Fixed dataverse links in Notifications tab of Account page to point to Pretty Faces/alias URL. Replaced image type icons with custom icons.

Need to check on the permission page URL format before changing those here.

**Comment by mheppler** [comment]
Changed file permission notifications on the Account page to point to the file permissions page, rather than the dataset page.

**Comment by sbarbosadataverse** [comment]
@mheppler  can you explain this first feature? is this the notification link you get in your email? Or the notification you get on dataverse? not clear. thnx
File permissions notifications should link to File Permissions page, and not the dataset page. (From #1348)


Dataverse links do not using Pretty Faces URLs.- check
Custom icons need to be added for dataverses, datasets, files. - check

**Comment by mheppler** [comment]
@sbarbosadataverse -- These are specific to the notifications in the Notifications tab on the Dataverse Account page, in the app.
