### ISSUE TITLE
Dataverse alias can be a number (which breaks API access)

### ISSUE THREAD

**Issue by bencomp** [IQSS/dataverse#1461]
I created a dataverse on https://apitest.dataverse.org and assigned it the alias (identifier) `5`. The web view shows me my dataverse, but I assume that because the API interprets `X` in `https://[SERVER]/api/dvs/X` as either a database ID *or* an alias, it breaks.

    curl https://apitest.dataverse.org/api/dvs/5?key=<key>
    {"status":"ERROR","message":"Get Dataverse unauthorized."}

By changing the alias to `b5`, the corresponding request works as expected.

NB: the [Native API guide](http://guides.dataverse.org/en/latest/api/native-api.html) does not show the key parameter is required for `GET`.

**Comment by bencomp** [comment]
I see there is a general issue about validating dataverse attributes: #364. Maybe this issue should be merged (then I apologise for opening an extra issue).

**Comment by scolapasta** [comment]
No problem - personally I prefer target issues like this, because it's easier to review, estimate time, and pass through QA.

**Comment by scolapasta** [comment]
@rtreacy we just need to update the alias validation to not allow just a number.

**Comment by pdurbin** [comment]
I'm fine with whatever for 4.0 but @bencomp and I discussed this the other day and I was saying "maybe we could let people tell the app if there providing an alias or a database id... /api/dataverses/alias/5 vs /api/dataverses/id/5 ... could support both rather than requiring that aliases not be only numbers" at http://irclog.iq.harvard.edu/dataverse/2015-02-23#i_16492

**Comment by scolapasta** [comment]
We considered that approach as well, but I like the idea of not having an alias be a number. (and being able to use the same API interchangeably).

**Comment by pdurbin** [comment]
Please note the proposed fix by @akio-sone above as part of #1616

**Comment by kcondon** [comment]
OK, UI prevents this and API throws an error when trying to create with alias = #. Closing.
