### ISSUE TITLE
Restricted Image Files - Default File Icon

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1462]
For restricted image files (or any file that uses a thumbnail image preview), there shouldn't be a image displayed, but instead the default custom image icon.

On the dataset page, currently nothing is displayed, if you don't have access to a restricted file that uses a thumbnail preview. On the dataverse serach/browse card, the thumbnail preview is displayed.

![screen shot 2015-02-18 at 1 03 43 pm](https://cloud.githubusercontent.com/assets/687227/6253361/b9800104-b76e-11e4-8f00-cb6d18c6923b.png)

![screen shot 2015-02-18 at 1 04 43 pm](https://cloud.githubusercontent.com/assets/687227/6253366/bfd0ead2-b76e-11e4-9031-8237feeeee02.png)

**Comment by landreev** [comment]
@mheppler 
Mike, 
I've added logic to the file card, for the "lock" and "unlocked lock" icons; 
as of now, it's just showing text "(locked)" or "(unlocked)", depending on which one it is. 
Could you please modify it to show your neat little icons instead?

**Comment by landreev** [comment]
@mheppler 
Oh, I must have given you the wrong ticket. 
Meant to give you #1457 instead.

**Comment by landreev** [comment]
( @mheppler : fyi )
Should be working as specified now: 
If a user has no permission to download an image file, the thumbnail will not be shown either. 
But, instead of a broken image or nothing at all, the type-specific default icon will be shown.

**Comment by posixeleni** [comment]
Works as expected:

At the Dataset level:
![image](https://cloud.githubusercontent.com/assets/5013837/6736050/d833b93e-ce38-11e4-9f97-41a628372a09.png)

At the file level:
![image](https://cloud.githubusercontent.com/assets/5013837/6736033/c6076e04-ce38-11e4-815d-14687b9e2c7e.png)

Closing.
