### ISSUE TITLE
 Dataverse Search/Browse Card - Remove Default Icon

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1465]
Now that we have new vector custom icons, we need to remove the old image icon from the backing bean. It is currently being used when a dataverse doesn't have a logo or contains files that have a thumbnail image preview.

**Comment by landreev** [comment]
@mheppler 
Mike, 
Similarly to #1464: 
Added more image logic and modified the search fragment.
Now it only displays a thumbnail on a dataverse card if a non-default image is available.
otherwise it displays text "(no image available for dataverse)"
Please replace this with your fancy vector image.

**Comment by mheppler** [comment]
Added icons for restricted and restricted with access to file cards. Added default icons for dataverse and dataset to the preview for cards. Cleaned up markup and moved CSS to stylesheet.

**Comment by kcondon** [comment]
OK, icons are in place and look good. Closing.
