### ISSUE TITLE
File Upload: Restrict & Delete Buttons Appear before any files uploaded

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1466]
Currently, the restrict & delete buttons are appearing prior to any files being uploaded. This is odd. There is nothing you can do with these buttons so they shouldn't be appearing prior to a file being uploaded.

**Comment by scolapasta** [comment]
Added a fragment around the buttons and update it on add a file and delete (and only show buttons if list is not empty).

Can you make sure to test with dropbox? I don't have that set up in my environment and it has update="@all"; I think these buttons will work fine with that, but am also concerned that that update will cause other (unrelated) issues.

**Comment by kcondon** [comment]
OK works and with drop box too. Closing
