### ISSUE TITLE
Dataverse Permissions Page: Selected Role needs permissions listed

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1467]
On the Dataverse permissions page, we see this:
![access1](https://cloud.githubusercontent.com/assets/5922904/6254368/02f2f646-b776-11e4-95fb-9b9adf4c8206.jpg)

but where it says the role (Editor in this example) we also need to have the permissions for it as listed on the Edit Access pop up...
![access2](https://cloud.githubusercontent.com/assets/5922904/6254383/1a97cace-b776-11e4-8825-e2d581fab41f.jpg)

@mheppler please let me know if this isn't something you can do and i'll reassign it.

**Comment by mheppler** [comment]
Added contributor role descriptions to the Manage Permissions page. Fixed some minor layout issues. Fixed a bug in previous check in for the remove role confirmation popup.

**Comment by eaquigley** [comment]
Looks good. closing ticket.
