### ISSUE TITLE
Login: Username no longer appearing in upper right.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1468]
Login: Username no longer appearing in upper right.

**Comment by mheppler** [comment]
On dvn-build and locally, it seems that old accounts (before today) display the username in the navbar when logged in, and new accounts (created today) display nothing.

Passing to Gustavo, based on his recent db account changes.

**Comment by scolapasta** [comment]
Fixed.

**Comment by kcondon** [comment]
Works, closing
