### ISSUE TITLE
Dataset Version: Switch Default to be Minor

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1470]
When publishing a new dataset version, in the pop up, major version is selected as the default. If you could make it so minor is the default as well as switch the order so minor is next to the first radio button and major is next to the second radio button.

**Comment by sekmiller** [comment]
Fix is checked in. Please rebuild to test..

**Comment by kcondon** [comment]
Works, closing. Note: Adding a file still forces a major version change.
