### ISSUE TITLE
Dynamically Populate "Parent" Dataverse

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1471]
On the following pages, please change it so instead of the text always saying "parent dataverse" it would be populated with the name of the parent (or grandparent if necessary) dataverse, i.e.-Harvard Dataverse:

- [x] General Information -- Metadata Fields, Facets Selection
- [x] Theme tab for Theme + Widgets
- [x] Manage Guestbook page
- [x] Manage Templates page

**Comment by sekmiller** [comment]
@mheppler please take a look at the theme and customization fragment

**Comment by eaquigley** [comment]
@sekmiller and @mheppler I was playing around today and noticed that the dynamic population for Theme is happening in the tool tip and not in the text that appears next to it. It should be appearing there, not in the tool tip.

**Comment by mheppler** [comment]
Cleaned up the display of the dynamic parent dataverse name in the Inherit Customization field on the Theme + Widgets popup for a dataverse.

**Comment by eaquigley** [comment]
Looks good. Closing ticket.
