### ISSUE TITLE
Publish Dataset Pop Up Upon Saving Changes

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1472]
Need to throw a pop up in that allows a user to publish the new version of the dataset once they have hit the save changes button for metadata or files so they don't forget to publish it.

**Comment by pdurbin** [comment]
I can imagine users being annoyed by seeing a pop up every time they click save.

**Comment by sekmiller** [comment]
Could be, @pdurbin.  Maybe we can figure out a way to show a popup the first time you make a draft after a publish.  Even that could become annoying.

**Comment by pdurbin** [comment]
@sekmiller what's you're latest thinking on this feature request? Annoying?

**Comment by sekmiller** [comment]
My vote would be to close this with extreme prejudice. My thinking is that "publishing" is a well-known feature of dataverse, so informing a user that they must republish is unnecessary. (have we had a single user complaint of, "Hey! you didn't tell me I had to republish my version 2 draft?") However, I am open to be persuaded, if there is an argument to be made by the current UI/UX team.

**Comment by jggautier** [comment]
I've always wondered how many people don't know that they have to click publish after saving a new dataset version. How many unpublished, version 1+ datasets exist because the depositor didn't know to hit publish after saving the new version?

**Comment by scolapasta** [comment]
This should is a question for the UX team.

(I will add one more idea, a save and publish button (assuming you have permission), but will defer to @TaniaSchlatter)

**Comment by pdurbin** [comment]
Do we have any data indicating how widespread of a problem is it that researchers are forgetting to publish the latest version of their datasets? Are any real users asking for a solution to this problem? I'm with @sekmiller ... vote to close. If a real user comes along and describes the problem in their own words let's revisit this then. I don't see a lot of value in keeping this issue open.

**Comment by pdurbin** [comment]
> Maybe this isn't the best way to solve the problem, so this issue could be closed. It's a great point that a pop-up would be annoying for people who already know how it works. But I've seen people saving datasets and don't realize that there's another step.

@jggautier good point. Perhaps it's time for a fresh issue. Maybe instead of having a solution in the title, the problem ("I forgot to publish my dataset" or whatever) could be in the title.

**Comment by TaniaSchlatter** [comment]
Closing this issue because it has been captured in more recent issues (#7746, #7678), and verified with a review of status of unpublished datasets that have sat by @jggautier, as well as though user tests of proposed UI improvements.
