### ISSUE TITLE
Dataverse General Information: Uncheck "Metadata Elements from Parent" When another block is checked

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1473]
Currently when a user has "Metadata Elements from Parent Dataverse" selected, you cannot click on any of the checkboxes till Metadata Elements is unselected. @sekmiller could you please look into having a way for this to be overwritten when a user selects a metadata block? Thanks.

**Comment by mheppler** [comment]
Cleaned up the Metadata Fields section. f6c0aab452630c74adc82b46cfc1bf9b24f791aa

**Comment by sekmiller** [comment]
You want to make the mdbs clickable when the dv is in "inherit" mode? Is this requirement obviated by the ability to "view" the contents of an unselected block? @eaquigley?

**Comment by mheppler** [comment]
@sekmiller @eaquigley -- After reviewing what is currently on dvn-build, and seeing the new "View fields" changes made from Mar 25 cf4448beb9a3760287d6472828f29f1509224b39, I remember discussing this functionality.

What is being asked is, for a child dataverse, with "Use metadata fields from Root Dataverse" selected, allow the admin to click on the (now disabled, uncheckable) check boxes for the additional metadata blocks. Upon clicking these additional metadata checkboxes, the checkbox for "Use metadata fields from Root Dataverse" will be unselected.

This request originated from usability testing, where very few users understood that you needed to uncheck the first checkbox, before being allowed to select the disabled checkboxes for the additional metadata blocks.

If you have any questions about how to best implement this, I'm available to discuss it in further detail.
