### ISSUE TITLE
On Dataset Version Improve Checking for IsMinorUpdate

### ISSUE THREAD

**Issue by sekmiller** [IQSS/dataverse#1475]
If the number of files has remained the same verify that these are in fact the same files by comparing FileMetdatas of the files on the two versions

**Comment by sekmiller** [comment]
Fix has been checked in.  Must make a new build to test.  To verify, make sure that if the number of files remains the same, but the files themselves have been changed it will force a major release.  Deleting and re-adding the same file may also trigger a major release.  (Not sure if there's any way around that one - probably a minor use case issue.)

**Comment by kcondon** [comment]
OK, when file count remains the same, +1, -1, still detects major version  change. Closing.
