### ISSUE TITLE
Restricted Files: Request Access to Selected Files Button

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1476]
"Request Access to Selected Files" button, associated with checkboxes on dataset page.
- [ ] Confirmation popup with user name, email, to show it is being sent.
- [ ] Email sent with user name, email, requested files names, dataset title, dataverse name, date/time to admin/dataset contact

**Comment by scolapasta** [comment]
From @eaquigley:

The pop up goes with allowing the guestbook to be used with requesting access.
So as long as there is a ticket for that, this one can be closed

ticket for guestbook being used with request access is: #2552

**Comment by kcondon** [comment]
Closing as duplicate.
