### ISSUE TITLE
Guestbook: Various issues part deux

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1477]
These are remnants from part un:
- [ ] 10. The black bubble view mouseover on the available guestbook table appears through the transparent view popup.
- [x] 14. Wire up commented out edit help info text.

From #1397:
- [x] Display error message in the popup and not on the dataset page.
- [x] Need inline "required field" error msg on validation for the input fields in that popup form.
- [x] Position isn't automatically filling in user account info.
[Kevin] Still not working

General
- [x] Add in all the success/error messages from #1277.

**Comment by eaquigley** [comment]
I'm not seeing inline error messages appearing. Also, the required asterisk is displaying oddly for a longer custom guestbook question as seen in this image:
![guestbookasterisk](https://cloud.githubusercontent.com/assets/5922904/6582971/4a386d94-c737-11e4-982e-d5a6b97e76a4.jpg)

Passing back to @sekmiller

**Comment by scolapasta** [comment]
I'm going to send this back to QA as issue #1664 seems to have been opened for the validation messages. Opened new issue #1647 for the asterisks.

**Comment by posixeleni** [comment]
https://github.com/IQSS/dataverse/issues/1664 is a dependency to test this?

**Comment by posixeleni** [comment]
All reported issues have been resolved but found a new issue when testing where at the Dataverse-level if you click on the "View" the guestbook and then "x" out of it the black help text "View" bubble stays displayed / frozen even when I go to hover over the other Guestbook options

![image](https://cloud.githubusercontent.com/assets/5013837/6855878/5ba14a86-d3d2-11e4-9b53-17f5d7c14439.png)

Re-assigning to @sekmiller to resolve this issue.

**Comment by mheppler** [comment]
@posixeleni @sekmiller @kcondon -- the reported issue with tooltips "sticking" or however you want to describe it, is a site wide issue that will need a site wide solution. Please open a ticket specific to this issue and give it to me, for "In Review - 4.0.x". Thank you.

**Comment by posixeleni** [comment]
@kcondon @sekmiller Per @mheppler's comment above https://github.com/IQSS/dataverse/issues/1477#issuecomment-86697512, I created a new ticket for the tooltip sticking issue: https://github.com/IQSS/dataverse/issues/1781

This ticket is closed since Guestbook is specifically working as expected.
