### ISSUE TITLE
File Permissions: Grant File Access popup has skewed display in FF

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1478]
When granting file access, there is a view popup to see which file(s) are requested. In my FF, 35.0.1, the files table is pushed off screen to the right with the top text and buttons to the left. Works ok in Chrome.

**Comment by scolapasta** [comment]
@mheppler are you still doing general cleanup for this page?

**Comment by mheppler** [comment]
I thought I had gone through the general clean up of file permissions. If
this is still an issue, assign it to me and I can take a look.

**Comment by mheppler** [comment]
Cleaned up the Grant Access form in the popup from the File Permissions page.

**Comment by kcondon** [comment]
Looks good, closing
