### ISSUE TITLE
Groups: UI doesn't allow spaces in name but doesn

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1481]
I tried creating a group named Test Root Admin with friendly name Root Admin. This failed validation but it did not explain why. When I removed spaces, it worked.

**Comment by eaquigley** [comment]
- Change the name to be Identifier
- Change Friendly Name to be Group Name
- Text for Identifier about which characters can and cannot be used (tool tip)
- Add in inline error messages for this

**Comment by michbarsinai** [comment]
[x] Change the name to be Identifier
    [x] Change Friendly Name to be Group Name
    [x] Text for Identifier about which characters can and cannot be used (tool tip)
    [x] Add in inline error messages for this
    [x] Overall validation messages for this feature

**Comment by michbarsinai** [comment]
Over to QA. Once done, please send over to Mike for UI cleanup.

**Comment by mheppler** [comment]
Clean up is complete. Need a few minor pieces done on the backend before it's ready for QA.

- [ ] Remove the info text that is displayed in both blue blocks on the popup, as that is now in a grey help-block under the input. The popup doesn't need any blue info blocks.
- [ ] I have added an asterisk next to Users/Groups, as I would assume that is required, but validation doesn't check to make sure you have added anyone. Should it? If not, remove the asterisk from the label.

**Comment by michbarsinai** [comment]
Role assignees are not required, as groups can be empty. A good use case is when someone sets up a dataverse before all the user have joined.

**Comment by kcondon** [comment]
@michbarsinai OK, look good. Notice it fails on dupe id but doesn't explain. Also doesn't require unique name but that results in duplicate names in assignment lists. I believe Gustavo has this task for users too, of adding id along with name in pick list.
