### ISSUE TITLE
Pre-selected Facets at Dataverse Creation

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#1485]
Spoke with @mcrosas & @eaquigley that to assist users when creating a Dataverse, certain facets should be pre-selected.

Author
Subject
Keyword Term
Deposit Date
_________________

Type (Dataverse, Dataset, File)
Affiliation
Publication Status
Publication Date
Dataverse Category 
File Type

appear already by default. The ones above need to be added into to the installer script for 4.0.

**Comment by scolapasta** [comment]
Added api to update facets and added to setup-all script.

**Comment by sbarbosadataverse** [comment]
here is what's showing up as preselected facets:

Affiliation
 Publication Date
 Author Name
 Subject
Keyword Term
Deposit Date

Are these fields in a particular block? If so, which (doesn't appear in social science block)

Publication Status
Publication Date
Dataverse Category
File Type

**Comment by sbarbosadataverse** [comment]
Eleni, just a question on which metadata block contains the list of fields--I found "type" under astronomy?
