### ISSUE TITLE
File Download Button -- Random Font, Icon Issues

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1486]
- [ ] Download buttons (not of the dropdown variety) are displaying with a serifed font
- [ ] On Liz's Windows machine... Dropdown download buttons have a strange button styling to the "All File Formats + Information" link (see attached)

![dropdown-button](https://cloud.githubusercontent.com/assets/687227/6309468/c1d4496a-b91b-11e4-9234-0e05bbe4a783.jpg)

**Comment by mheppler** [comment]
Fixed some markup issues with commandLinks and Bootstrap icons, that were causing strange font and icon issues with the download buttons on the dataset page. Optimized the markup by removing unnecessary ui:fragment tags and moving the renders to their components.

**Comment by kcondon** [comment]
Looks good, weirdness has been banished. Closing.
