### ISSUE TITLE
Restrict Files: Works intermittently

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1487]
Sometimes restrict files works, sometimes not.

When it doesn't, the behavior varies:
Sometimes checkbox works, lock appears but save doesn't work.
Sometimes, checkbox works but no lock appears, save seems to save but does not restrict.

It is not yet clear when it doesn't work.

Note: On my machine it never works in either FF or Chrome.

**Comment by scolapasta** [comment]
When I started debugging this, you could never restrict files (null pointer). I have foxed that and it has worked for me on my test, but not sure if the intermittent problem is gone (though I'm not seeing it).

**Comment by mheppler** [comment]
Cleaned up the Download, Upload + Edit Files, Restrict, Delete buttons atop the files table on the dataset page in both the view and edit modes.

**Comment by kcondon** [comment]
Works now, closing
