### ISSUE TITLE
Bootstrap - Upgrade

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1488]
We currently use Bootstrap v3.1.1 and there is a new v3.3.2, that was released Jan 19.

**Comment by mheppler** [comment]
Upgraded Bootstrap to v.3.3.2 by replacing CSS, JS and font files. Changed the font file URL links in the CSS. Changed glyphicon for "Copy role" on the Permissions page to new Bootstrap glyphicon for "duplicate".

**Comment by kcondon** [comment]
Closing, will keep an eye out for weirdness.
