### ISSUE TITLE
Text for when there are no guestbooks or templates

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1490]
From #1447. 

Link to mockups: https://iqssharvard.mybalsamiq.com/projects/guestbookandtemplatesblankpages/grid
These need to appear whenever there are no dataset templates or guestbooks.

**Comment by eaquigley** [comment]
@mheppler I'm passing this to you as @mcrosas approved what is in the mockups. 

Links for the links needed based off the mockups:
-[ ] http://guides.dataverse.org/en/latest/user/dataverse-management.html#dataset-guestbooks
- [ ] http://guides.dataverse.org/en/latest/user/dataverse-management.html#dataset-templates

**Comment by mheppler** [comment]
Added new why/how text for empty Dataset Templates/Guestbooks manage pages. Cleaned up a few minor layout issues.

**Comment by kcondon** [comment]
In place, closing
