### ISSUE TITLE
Dataverse - Edit General Information - Select Facets, Dynamic Parent Dataverse Name

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1491]
In the Select Facets section of the Dataverse - Edit General Information page, there was a static "Facets from Parent Dataverse" label for the checkbox. I took the dynamic code from the Metadata Fields section, but this needs to be dynamic for the facets, and not use the code from the metadata section.

Here is the code that I used in the facets section:
````
<h:outputFormat value="#{bundle['dataverse.facetPickList.facetsFromHost.text']}">
     <f:param value="#{DataversePage.dataverse.metadataRootDataverseName}"/>
</h:outputFormat>
````

**Comment by kcondon** [comment]
OK, works. If parent also inherits, it lists the top level that it will inherit from. Not sure if that is meaningful but ok. Closing
