### ISSUE TITLE
Customization - Improvements

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1493]
Customization improvements, based on feedback from Dwayne's experiment to bring 3.6 customizations into 4.0.

- [x] Tagline only allows "alphanumeric" and that means, no commas or periods, and that's weird.
- [x] Change "Link URL" to "Website" label, with watermark for "Your personal site, http://".
- [x] Merge Tagline + Link Text to one option, that works with Link URL.

**Comment by scolapasta** [comment]
#1196

**Comment by pdurbin** [comment]
Please note that @akio-sone has proposed a fix at https://github.com/akio-sone/dataverse/commit/49257fa905b5262c14d9d4092c4410308820ebaa in #1616

**Comment by scolapasta** [comment]
@mheppler Can you take a look and see if removing the fields from the page requires any UI cleanup (also I think one of the texts got added to the page and not the bundle).

**Comment by scolapasta** [comment]
Tagline validation was removed, as to allow foreign characters. Though I did add a size check of 255, since that's what the db allows. (  @mheppler @eaquigley are we OK with this size?)

**Comment by mheppler** [comment]
@scolapasta -- this is the tagline... that goes in the dataverse header... I'd argue that 255 is a bit excessive...
![screen shot 2015-03-09 at 5 45 56 pm](https://cloud.githubusercontent.com/assets/687227/6565128/3052bbcc-c684-11e4-94ca-916dc5269e17.png)

**Comment by eaquigley** [comment]
I'm inclined to go with Twitter standards for this one and do 140 characters. Don't think we need to support more than that based off @mheppler's screenshot showing how it looks with 255 characters.


On Mar 9, 2015, at 5:46 PM, Michael Heppler <notifications@github.com<mailto:notifications@github.com>> wrote:


@scolapasta<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_scolapasta&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=Y9aY3P6kFFpmMLaYYO_id08dS3gL1xWMQuI2CZ74PoI&m=NgNubsO2h2RQcLT6-THCL_zGUy_CatNVd9BgoVFzGuM&s=YavEBTyAosMc5W4ctlOFlo3f7iWOcw3ZrtD0fCgQZpw&e=> -- this is the tagline... that goes in the dataverse header... I'd argue that 255 is a bit excessive...
[screen shot 2015-03-09 at 5 45 56 pm]<https://urldefense.proofpoint.com/v2/url?u=https-3A__cloud.githubusercontent.com_assets_687227_6565128_3052bbcc-2Dc684-2D11e4-2D94ca-2D916dc5269e17.png&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=Y9aY3P6kFFpmMLaYYO_id08dS3gL1xWMQuI2CZ74PoI&m=NgNubsO2h2RQcLT6-THCL_zGUy_CatNVd9BgoVFzGuM&s=oPE3HUTGzZPFA5bAVfWpjSiA4MVkXv4qHKHpeezeCPs&e=>

**Comment by mheppler** [comment]
Cleaned up some minor layout issues, added some help text, fixed validation error messages, changed tagline length from 255 to 140.

**Comment by eaquigley** [comment]
This all looks good. Creating a new ticket for updating the info/help text above the Website field. Also need to add info/help text about the tagline only being 140 characters.
