### ISSUE TITLE
Shibboleth: strings "givenName" and "sn" are persisted for all Shib users

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#1495]
f82ac47529873201f799acf0fd939acd22d799d1 introduced a bug (probably as part of #1450) where every Shibboleth user who tries to log in has the strings "givenName" and "sn" persisted:

![shib_-_2015-02-24_10 35 38](https://cloud.githubusercontent.com/assets/21006/6353243/298bacae-bc16-11e4-8c51-a120db5fcc16.png)

Instead, the actual first name and last name should be persisted.

**Comment by pdurbin** [comment]
979a59d0d6a66c3596097594622aa4fe5cebbcae should be a good fix. Please note that Shibboleth attributes "givenName" and "sn" have just been added to the list of required attributes:

- Shib-Identity-Provider
- eppn
- givenName
- sn
- mail

The question of which attributes should be required was raised at https://github.com/IQSS/dataverse/issues/796#issuecomment-75388752 . There's some thinking specifically around "eppn" at #1422

Passing to QA. After a successful login as the "myself" TestShib account, based on what I'm seeing at https://dvn-build.hmdc.harvard.edu/Shibboleth.sso/Session ...

givenName: Me Myself
sn: And I

... the name at the Shib confirmation screen (or later in the upper right when you log in again) should say "Me Myself And I".

**Comment by kcondon** [comment]
This appears to be working now for Harvard IdP closing.
