### ISSUE TITLE
Dataverse Permissions - "Who can add to this dataverse?" Value Disappears

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1496]
The selected value for "Who can add to this dataverse?" on the Dataverse Permissions page, disappears after editing the "What type of contributor should be the default for this dataverse?" value on the Edit Access popup.

Steps to reproduce:
- 1. Dataverse > Edit Permissions
- 2. Permissions > Edit Access
- 3. Change "What type of contributor should be the default for this dataverse?" > Save Changes
- 4. Permissions > "Who can add to this dataverse?" == BLANK
- 5. Refresh > "Who can add to this dataverse?" == Value returns

**Comment by kcondon** [comment]
Fixed, closing
