### ISSUE TITLE
Shibboleth: persist institution name as affiliation for users

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#1497]
As discussed especially with @mcrosas and @eaquigley and @mheppler we want to persist "Harvard University" (or whatever friendly string we can get per-institution by parsing https://dataverse.harvard.edu/Shibboleth.sso/DiscoFeed ) to the "affiliation" field in the authenticateduser table for Shibboleth users. Some initial work toward this was done in 193787ccbd3156cad0832065a75405fe29c02f82

If there's a better programmatic way of getting these values, that would be great but it's my understanding that Identity Providers (IdPs) do not commonly pass an attribute for this. Rather, you get something like "https://fed.huit.harvard.edu/idp/shibboleth" from the attribute "Shib-Identity-Provider" from which you could extract "harvard.edu" but we'd like a friendlier name ("Harvard University") rather that a domain name to display to users.

**Comment by eaquigley** [comment]
@pdurbin are we getting Harvard University through the JSON currently?

**Comment by pdurbin** [comment]
@eaquigley as I explained to @scolapasta as of 193787ccbd3156cad0832065a75405fe29c02f82 I'm parsing a static file on the filesystem: https://github.com/IQSS/dataverse/blob/master/src/main/webapp/resources/dev/sample-shib-identities.json . There's a test to make sure it's getting the expected values.

What hasn't been done yet is dynamically downloading the JSON from the server (not sure if this should be "localhost" or a domain in DNS).

**Comment by pdurbin** [comment]
After a build if you log in as "myself" using TestShib I expect the "affiliation" column of the authenticateduser table to be populated with "TestShib Test IdP" for that user. (This value comes from https://dvn-build.hmdc.harvard.edu/Shibboleth.sso/DiscoFeed .)

Like firstname, lastname, and email address, the "affiliation" value is updated on every log in, so one way to test is to change the value of affiliation to a junk value ("FIXME" or whatever) and make sure it gets updated properly at login.

Passing to QA.

**Comment by bencomp** [comment]
In our situation, the affiliation attribute carries a domain name value. For DANS (my affiliation) it is not "DANS" or "Data Archiving and Networked Services", but "dans.knaw.nl". [It works like this for all SURFconext users](https://wiki.surfnet.nl/display/surfconextdev/Attributes+in+SURFconext#AttributesinSURFconext-Homeorganisation).

Ideally my next suggestion should not be necessary, but a mapping of domain names to institution names could come in handy here. SURF does provide [a list of connected organisations](https://wiki.surfnet.nl/display/conextsupport/List+of+Connected+Identity+Providers), but not their domain names. I wouldn't want having to update a mapping file, even though there aren't that many affiliations in the DDN. Could a Linked Data source provide this mapping? I.e., could Dataverse use a L(O)D source to find an institution name for a domain name?

**Comment by kcondon** [comment]
Works as described, affiliation column is updated on log in. @pdurbin not sure about ben's comment.

**Comment by bencomp** [comment]
@kcondon I guess I didn't read @pdurbin's initial comment closely enough, because the problem he outlines is similar. I may get back to this when we have tested Shibboleth on our side.

**Comment by kcondon** [comment]
@bencomp OK, let us know if you need something to behave differently and we can open another ticket to consider it.
