### ISSUE TITLE
Migration - handle invalid dataset contact email

### ISSUE THREAD

**Issue by ekraffmiller** [IQSS/dataverse#1498]
For migration, some emails in production data are invalid (for example, they say "enter your email address".  For these cases, we are substituting NA for dataset contact email.

If email is NA, we need a way to handle the contact button on the dataset page.  Gustavo suggested using the dataverse contact email.

@eaquigley and @posixeleni , is that ok with you?

**Comment by posixeleni** [comment]
@ekraffmiller @eaquigley I think the easiest solution like Gustavo suggested would be for any email that is NA (when migrated from 3.6) to use the Dataverse-level Contact Email. People can always go in and change this in their metadata if they want to later on.

Question: From 3.6: Would there ever be no Dataverse-level contact email as well, though?

**Comment by ekraffmiller** [comment]
@posixeleni @eaquigley @scolapasta - I updated the contact form so that if no dataverse-level contact is available, it goes to the general support email.  (I'm assuming that this should happen only rarely).
