### ISSUE TITLE
Guestbook: Mouseover Issue in Table

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1499]
The black bubble view mouseover on the available guestbook table appears through the transparent view popup.

**Comment by scolapasta** [comment]
This is happening with other mouseovers too: #1868 
Keeping this issue as the parent of all this and closing the other as a duplicate.

**Comment by mheppler** [comment]
This ticket had a duplicate (#1781) that was fixed and sent to QA. Sending this to QA as well.

> I searched through the project for other buttons that have tooltips, and it appears that this issue doesn't effect those pages.

**Comment by kcondon** [comment]
@mheppler @scolapasta OK, this ticket has a circular reference: 1499->1868->1499, then to 1781 and so closed. 1868 is not addressed by this ticket so I will reopen that after retesting of course.

**Comment by kcondon** [comment]
Guestbook working, templates working, add/delete email working. Closing this but will open a fresh, new ticket if I see new places such as on edit dataset form, etc.
