### ISSUE TITLE
Featured Dataverses: Removing Label & Adding Option to Edit Dataverse Drop Down

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1501]
- [ ] Please remove the bold "Featured Dataverses" label that appears on the homepage for a dataverse that has featured dataverses enabled
![fd1](https://cloud.githubusercontent.com/assets/5922904/6360796/ed0f36ee-bc4a-11e4-8fe5-d05306a51e73.jpg)

-[ ] Currently, the Featured Dataverses link in the Edit Dataverse dropdown only appears when a user has at least one published dataverse. This needs to change so that the option always appears. If a user clicks on it when they don't have a published dataverse, we need a message to pop up that says "To use Featured Dataverses, there needs to be at least one published dataverse within this dataverse."

**Comment by mheppler** [comment]
Cleaned up the carousel and popup for the Featured Dataverses on the Dataverse page. Moved text to bundle, and inline CSS to stylesheet, for both Featured Dataverses and Linked Dataverses.

**Comment by eaquigley** [comment]
@mheppler please have featured dataverses appear at the bottom of the list under edit dataverse (above delete dataverse)

**Comment by mheppler** [comment]
Moved "Featured Dataverse" link to bottom of Edit Dataverse button dropdown.

**Comment by kcondon** [comment]
@eaquigley @mheppler Featured dv's doesn't appear when no published dv's. Passing back.

**Comment by sekmiller** [comment]
Now if there are no published DVs the user may click on Featured Dataverse Link and will get a warning Pop-up saying You must have a published dataverse in order to feature it.

Build rehired for testing

**Comment by eaquigley** [comment]
Featured Dataverses at bottom of list under Edit DV, Checkbox removed from FD pop up, and FD appears in dropdown list even when there are no published ones, when clicked on, help message appears. Closing ticket.
