### ISSUE TITLE
Dataset Contact Form: Wire this up

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1502]
For some reason the Dataset Contact Form was never wired up though the Dataverse Contact Form was. @ekraffmiller could you please do this since you are working on the invalid email migration stuff for datasets. @scolapasta said for me to assign this one to you, it already exists for on a dataverse page behind the email icon button.

**Comment by ekraffmiller** [comment]
@eaquigley , I noticed on the latest version of the contact page, the message subject is input text rather than a   drop down.  What default value do you want here (for dataset contact form and dataverse contact form)?

**Comment by eaquigley** [comment]
@ekraffmiller sorry for not alerting you about it being input now! i'd prefer no default subject actually so that a user doesn't accidentally skip over that field.

**Comment by ekraffmiller** [comment]
@eaquigley ok, no problem - should the general feedback subject be blank also?

**Comment by eaquigley** [comment]
@ekraffmiller for that one, can you have the build # populate it? i know that has been useful for support in the past.

**Comment by ekraffmiller** [comment]
ok, sounds good

**Comment by mheppler** [comment]
As pointed out in #1529, make sure to also remove the placeholder popup when wiring up this dataset contact form.

**Comment by ekraffmiller** [comment]
This is ready for styling fixes now, passing on to @mheppler

**Comment by mheppler** [comment]
Cleaned up the Feedback link in navbar, and Email Dataset/Dataverse Contact button on respective pages. Cleaned up contact form layout, styled send button, validation messages.

**Comment by kcondon** [comment]
Looks good, closing
