### ISSUE TITLE
Add API to list facets for a dataverse

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#1506]
In 4.0 we have an API to add them, but we should also be able to list.

(it would be good to verify that we also have an API to list which ones are facetable)

**Comment by michaelsuo** [comment]
@scolapasta what info should the API expose? Right now I have the id of the `DataverseFacet` and the display name of the `DatasetFieldType`.

**Comment by kcondon** [comment]
OK, api call seems to work and is documented in the API Guide: GET http://$SERVER/api/dataverses/$id/facets?key=$apiKey
