### ISSUE TITLE
Breadcrumbs - New Dataverse vs. "null Dataverse"

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1507]
When creating a new dataverse, the breadcrumbs are now displayed, and it reads "null Dataverse". The dataverse header link, and page title both read "New Dataverse". The breadcrumbs should also read "New Dataverse".

**Comment by scolapasta** [comment]
I'm not done with the breadcrumbs issue #1284 for this, so new this was an outstanding item. It's fine to keep it tracked separately, so then I can pass #1284 back to you.

**Comment by scolapasta** [comment]
Fixed for both Dataverse and Dataset (which just had blank)

**Comment by kcondon** [comment]
Breadcrumbs look just fine, closing.
