### ISSUE TITLE
Dataverse - Create/Edit General Information - Clean Up Redux

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1508]
- [x] Dataverse input is missing the "Dataverse" text to the left of the input
- [x] The tabindex is off for Affiliation and Identifier

**Comment by mheppler** [comment]
Cleaned up the edit/create Dataverse General Information page by fixing tabindex and adding "Dataverse" help text.

**Comment by kcondon** [comment]
Looks good, closing
