### ISSUE TITLE
Expose Controlled Vocabulary Terms in the API

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#1510]
With the Native API we should be able to expose controlled vocabulary terms.

For example: this would be helpful if someone wants to use our required Subject controlled vocabulary without having to manually add and update the terms.

See this IRC chat for more information on user needs: http://irclog.greptilian.com/rest/2015-02-07#i_95635

@pdurbin is also stubbing this out here: https://github.com/IQSS/dataverse/commit/9e6c218821ec5f465c4b97224c734f4cb4f64ffd

**Comment by pdurbin** [comment]
> @pdurbin is also stubbing this out here: 9e6c218

For now the output is this but it's hard-coded to only show subject. We could make it more general. Also, not to open a can of worms but I have no idea what the plan is for languages besides English. Anyway, here's the current output:

```
{
  "data": [
    "Arts and Humanities",
    "Astronomy and Astrophysics",
    "Business and Management",
    "Chemistry",
    "Earth and Environmental Sciences",
    "Engineering",
    "Medicine, Health & Life Sciences",
    "Computer and Information Science",
    "Law",
    "Mathematical Sciences",
    "Physics",
    "Social Sciences",
    "Other"
  ],
  "status": "OK"
}
```

**Comment by posixeleni** [comment]
thanks Phil. This will be helpful for OJS so I'm pinging @jwhitney @axfelix

**Comment by pdurbin** [comment]
That's fine but I'm purposely not documenting it until we decide what we want. "API design is building in future regret." ;)

**Comment by pdurbin** [comment]
@scolapasta this is behind an API endpoint I believe we plan to block: https://github.com/IQSS/dataverse/blob/master/src/main/java/edu/harvard/iq/dataverse/api/DatasetFieldServiceApi.java /cc @michbarsinai

**Comment by bencomp** [comment]
See also: #2357

**Comment by pdurbin** [comment]
This has been requested at https://github.com/IQSS/dataverse-client-java/issues/6

**Comment by pdurbin** [comment]
Related:

- Query Dataverse for mandatory metadata fields via API #6978

**Comment by pdurbin** [comment]
"Programmatically determine list of dataset subjects" has been requested at https://github.com/datalad/datalad-dataverse/issues/27 by @mih. 

As explained above, years ago we stubbed out an API for this at 9e6c218 but it remains hidden behind the "admin" API.

In practice, integrations still have to hard-code the list of subjects.
