### ISSUE TITLE
Permissions: Explicit groups who are assigned admin role cannot access or edit unpublished dv, ds.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1512]
I've directly assigned an explicit group to a unpublished dv and to an unpublished ds and they appear in the search cards, the group appears on the permissions page under role assignment, but I cannot go directly to the landing page, nor the permissions page as a user of the explicit group. Add data/edit buttons also do not appear.

I believe I have also seen this work (2 times fail, one time works) so I am not sure what the difference is.

**Comment by michbarsinai** [comment]
Cause: Group membership calculations did not effectively take DvObject containment hierarchy into account.

**Comment by posixeleni** [comment]
Works as expected. Closing.
