### ISSUE TITLE
Use Authenticated User instead of Built-In User for getting default identifying values 

### ISSUE THREAD

**Issue by sekmiller** [IQSS/dataverse#1514]
Built-in user was used for getting default identifying values such as name and email for guestbook and dataset version user.  Since not all contributors will be built-in users we must use Authenticated user in place of built-in user

**Comment by sekmiller** [comment]
Default dataset version author name and guestbook info is coming from authorized user.

Dataverse Contributor is still using built-in user lookup for getting version tab contributor names.  We may need to change the way contributors are stored.

**Comment by sekmiller** [comment]
Fixed and checked in.  will need a new build before testing.  To test verify that the contributor's names on the datasetversion tab are correct.

**Comment by kcondon** [comment]
OK, check both versions tab and guestbook autocomplete as shib user. Works, closing.
