### ISSUE TITLE
Change Password: Agree to TOU checkbox is there and is always required.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1518]
I noticed that the account/site TOU checkbox and TOU is on the change password page, it is always there and always required, no matter how many times you accept.

**Comment by bencomp** [comment]
I noticed it too, and don't think it makes sense to have it there. I guess @kcondon means it should not be - if so, I agree.

**Comment by scolapasta** [comment]
Dupe of #1565

**Comment by kcondon** [comment]
Gone for now until new migration workflow is implemented. Closing.
