### ISSUE TITLE
Search/Browse Card: Dataset Descriptions No Longer Displayed

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1522]
@pdurbin mentioned to me that description was no longer appearing and posed the question that since no one had noticed it, do we still care about having the dataset description display? I say yes, we do want it still to appear.  

Going deep into my archives of the progression of DV 4, I found this screen showing when they were displayed:
![2014-05-08_15-37-17](https://cloud.githubusercontent.com/assets/5922904/6402550/779ae966-bdd6-11e4-9609-5dd4c95112e3.jpg)\

**Comment by posixeleni** [comment]
+1 with @eaquigley I believe descriptions are extremely important when a user is browsing a list of results to see which ones are actually most relevant for them to click on.

**Comment by pdurbin** [comment]
I chatted with @mheppler about this the other day and he agrees with me and @scolapasta that when browsing we should only show the first description. And we'll make sure long descriptions are truncated with ellipsis (...) as before.

**Comment by pdurbin** [comment]
As I mentioned at https://github.com/IQSS/dataverse/issues/69#issuecomment-69761957 "description" is also missing from the Search API for datasets. It works fine for dataverses and files.

**Comment by pdurbin** [comment]
Ok, dataset descriptions are back in search cards in the UI...

![dsdescription](https://cloud.githubusercontent.com/assets/21006/6507360/a345ee50-c31f-11e4-80ad-181caf69bcc3.png)

... and newly available from the Search API:

$ curl -s "https://apitest.dataverse.org/api/search?q=goose" | jq .data.items[].description
"What the Spruce Goose was really made of."

Please note that in both cases we only show the **first** description.

Truncation and highlighting behavior should work as it did in the days of yore. Thanks for the archaeology @eaquigley!

Passing to QA.

**Comment by eaquigley** [comment]
Dataset descriptions are now appearing! Closing ticket.
