### ISSUE TITLE
Publish Dataset - Clean Up Layout

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1523]
"Publish" (Major release)
- [x] Message inline with buttons

"Publish" (Minor/Major release)
- [x] Version number select message in button section, cleanup spacing, styling

"Publish" (Parent not published, publish both)
- [x] Message in one line, capitalize button

"May Not Publish" (Administrator)
- [x] Capitalize header, add "Close" button

"May Not Publish" (Two parent dataverses not published)
- [x] Capitalize header, add "Close" button

**Comment by kcondon** [comment]
Looks good, closing
