### ISSUE TITLE
Metadata: N/A shouldn't appear in the section of fields below the citation, above the tabs

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1524]
Noticed today: N/A is appearing in the Subject metadata field that is displayed in the no mans land between the citation and the tabs. @scolapasta said that definitely shouldn't be happening since it doesn't display like that in the metadata tab.

**Comment by sekmiller** [comment]
Fixed and ready for testing after a new build

**Comment by posixeleni** [comment]
@kcondon to be able to test this in dvn-build we would need to run Ellen's DDI script to pre-populate studies from 3.6 in build. I am not seeing any of these old studies in dvn-build. Re-assigning to you.

**Comment by sbarbosadataverse** [comment]
NA not showing up between citation and tabs
