### ISSUE TITLE
Templates: Some template issues

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1525]
While testing template messaging, I came across several issues:
1. If a sub dataverse was created at a time when no root dataverse template existed, then when it does have one, no include templates from root dataverse checkbox is present.
2. It is possible to have one root template and not make it default but when there are two templates, one has to be default.
3. When there is only one root template and it is not default, the include from root checkbox is unchecked. When there are two or if the one is default, then the include checkbox is checked.

**Comment by kcondon** [comment]
Retested and was not able to reproduce issues 1,3.

**Comment by eaquigley** [comment]
@kcondon I agree. Definitely should be able to have multiple templates with none as default. I'm going to move this ticket to In Review-4.0.x

**Comment by sekmiller** [comment]
Regarding point 1:  The include templates from parents check box will only appear if the metadata blocks of the child dataverse are identical.

**Comment by sekmiller** [comment]
With respect to #2 - if a template is default the button says "Default" you can de-select it as default by clicking the button.  That's not obvious.  Looking for suggestions for the button label and suggest that we add another indicator that a given template is the default.

**Comment by sekmiller** [comment]
For Point 3 - not sure what you're describing.  On create the include from parents is checked regardless of the state of the parent's templates.

**Comment by sekmiller** [comment]
Discussed point 2 with Mike.  Assigning to him for now to follow-up on UX suggestions for de-selecting default template

**Comment by eaquigley** [comment]
In regards to point 2. I played around with this, looked at some toggle button research, and then had @mcrosas and @sbarbosadataverse do a guerilla usability test where I had two templates set up, one as default and one as not. I asked them to tell me which one was the default and how they could tell. Both of them were easily able to with the current Default and Make Default buttons. Additionally, we haven't received any support tickets from users saying this is an issue. Based off this, I recommend QA closes this ticket and if we receive support tickets from users about this being an issue, we will evaluate then. Passing to QA to close.
