### ISSUE TITLE
Linked Dataset: Select box is longer than popup when long names present. Linked dv ok.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1528]
Linked Dataset: Select box is longer than popup when long names present. Linked dv ok.
Using FF

**Comment by mheppler** [comment]
Changed PrimeFaces component to JSF h:selectOneMenu component in order to fix display of long dataverse names in dopdown for Link Dataset popup on dataset page.

**Comment by kcondon** [comment]
Looks good, closing
