### ISSUE TITLE
Contact Us: Text missing from contact us form on dataset. Shows ???dataset.email.tip???

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1529]
Contact Us: Text missing from contact us form on dataset. Shows ???dataset.email.tip???

Believed to be a casualty of bundling.

**Comment by mheppler** [comment]
That message was removed from the bundle 38180861d567b1dac54c1c010d6485eea1710e52 before the placeholder popup was removed, and the intended dataset contact form functionality was added, which is being developed in this ticket #1502.

Sending to QA to close.

**Comment by kcondon** [comment]
Closing since that other ticket describes implementing that feature.
