### ISSUE TITLE
Account/Data Related to Me - [Dataverse is empty] Message For New User

### ISSUE THREAD

**Issue by bencomp** [IQSS/dataverse#1531]
When I create an account and click through to "Data Related to Me", I get the message *This dataverse currently has no dataverses, datasets, or files. You can add to it by using the Add Data button on this page.* It is a minor issue, but it suggests I'm looking at a dataverse rather than a collection of objects that I have a part in.

![Screen shot showing "This dataverse currently has no dataverses, datasets, or files. You can add to it by using the Add Data button on this page."](https://cloud.githubusercontent.com/assets/1303898/6409942/41d33506-be6a-11e4-853f-8469740384c7.png)

**Comment by mheppler** [comment]
Good catch, @bencomp. I will take a look into this and will get a proper message in there, with the help of @eaquigley on a message that is more "your account" specific.

**Comment by eaquigley** [comment]
Message: 
- [ ] You have no dataverses, datasets, or files associated with your account. You can add a dataverse or dataset by clicking the Add Data button above or link dataverses and datasets by using the link button located on a dataverse or dataset page. Read more about adding data or linking data in the User Guide.

Please link to: http://guides.dataverse.org/en/latest/user/dataverse-management.html

**Comment by mheppler** [comment]
Since linking isn't possible without a dataverse first, the revised text will be:

You have no dataverses, datasets, or files associated with your account. You can add a dataverse or dataset by clicking the Add Data button above. Read more about adding data in the [User Guide].

**Comment by mheppler** [comment]
Also, I am expanding this ticket to include conditional render logic for the search box that currently "Search this dataverse...".

It has been suggested - by @eaquigley -  that "Search this data..." should be there in it's place.

**Comment by mheppler** [comment]
Created new non-dataverse specific messages for the search-include to display on the Dataverse Account page.

**Comment by kcondon** [comment]
Looks good, closing
