### ISSUE TITLE
Log important events to an audit log

### ISSUE THREAD

**Issue by bencomp** [IQSS/dataverse#1532]
As the back-office administrator of a nation-wide Dataverse (Network), with lots of different users, groups and roles in separate partner institutions, I would like to see who did what, when, and how (if applicable).

Not all events are equally important to log, but if something goes wrong (in some user's view), it should be possible to reconstruct the events leading up to the situation. Ideally I shouldn't have to search the Glassfish server log, but is this information available in a separate readable log.

I am thinking of events like (non-inclusive):

- new user registered (via website or API, via which authentication provider)
- new dataverse created
- new dataset (version)
- dataverse / dataset / datafile updated (including publication status)
- dataverse / dataset [/ datafile] deleted
- role changes
- permission changes
- role assignment changes
- admin setting changes

Some information is of course logged in the database, but extracting that for reconstruction may be hard and (at least in DVN 3.6) things like last released date of a dataverse only keeps the last event.

**Comment by scolapasta** [comment]
It's a nice idea - have previously discussed with @michbarsinai the idea of commands logging something. Will discuss more next week to see if it is something we can easily squeeze in now or if it makes more sense for 4.0.x.

**Comment by michbarsinai** [comment]
Super easy to do as long as the information we log is obtainable from the command interface (which may be the case). We just need to have the engine log each command it gets. There's a little caveat: User creation is not done via commands, as not DvObjects are involved. But - it's done on a single bean, so again, doable.

We do need a short spec-ing, just making sure we log the right things. Also, note that this log table will _not_ be able to hold foreign keys, as this would prevent objects from being deleted. It's structure should be text-y, as commands vary a lot. The alternative would be to have a few log tables and would make the queries more complex and the results less readable, unless we add a proper UI.

Items to log for each command (initial, probably partial list):
* User
* Action description (type, involved dv objects)
* timestamp
* attempt, result (success, fail+why)
* timing? (would later allow us to optimize the common actions)
* anything else?

Items for the log:
* Should we have an API for that? in 4.0?
* On/off by  default? Or always on?
* Rolling the log - as the log table just grows, we need a way to remove old records. We could:
    * Keep records for X days (configurable by the settings table)
    * Keep last X records (configurable by the settings table)
    * add an API for deletion, and have the sysadmin decide when to do that.

@bencomp Can we have example use cases? 

Adding @eaquigley  as some user requirements are involved

**Comment by mcrosas** [comment]
This is also important for our DataBridge project with UNC - worth thinking
about it and doing this soon @scolapasta

**Comment by bencomp** [comment]
Here are three hypothetical use cases. They may not apply to every installation, but I think they are general enough to say that they could.

## Use case: data librarian checks that data was deleted

Our users generally won't use Dataverse for long term storage, so following certain procedures, some dataverses or datasets will be removed or moved to another system. A researcher wants to see that the request to delete a dataset was handled correctly and have questions like these answered:

- Who deleted this data or unpublished it? When?
- Who gave this person permission to delete/unpublish it?
- Has the persistent identifier been updated correctly?

A data librarian (at the university-wide front office) can search/view the audit log to see that an assistent professor in the researcher's group deleted the dataset two days ago, and that this person was granted administrator rights for the dataverse by the research group secretary on June 3, 2015 at 15:00h CEST.

## Use case: researcher finds who replaced her data files

A researcher in a large project reads a review that uncovers flaws in the dataset used to produce results. She doesn't understand - during the project everything was fine.

In the audit log she finds a researcher from a partner institute created a new version of the dataset in which the data file was replaced by a slightly modified one that indeed has a different UNF and produces the incorrect result when input in the analysis method. She finds that during a batch update of permissions at the start of the project this other researcher was granted permissions to her dataset as well. (It turns out to be a mistake and the newer dataset version is deaccessioned, reverting the dataset to the original version.)

If a dataverse or dataset is shared, who added or updated metadata or data? Who updated roles and permissions for the dataverse and how, from where?

## Use case: data librarian finds spam in the root dataverse

One sunny day the data librarian looks at her dataverse installation and finds spam disguised as a dataverse in the root dataverse. From the audit log, it becomes clear what happened. Issue #976 was not resolved before the dataverse application went live and someone, probably using a stolen email account, accessed an existing user account, assigned it superuser rights and put a botnet to work to fill the root with spam using the API with a key that had been used before by the account. To cover up the breach, the API key was deleted and a new one generated. To top it up, the password of the admin user was changed by the new superuser.

**Comment by michbarsinai** [comment]
Decisions so far:

* Log records go to a log record table.
* No API/UI for 4.0
* No truncation/log rotation policy for 4.0. It will be added in a 4.0.x release; meanwhile, rotation and archiving can be done via sql commands.
* On by default, can be turned off using the `settings` mechanism

**Comment by michbarsinai** [comment]
Log record:
* Timestamp start
* Timestamp end
* type (command, user, etc)
* User
* Info
    * for commands: affectedDvObjects
    * for user creation: username
* result (OK, BadRequest, PermissionError, InternalError)

**Comment by michbarsinai** [comment]
To test, look in the actionlogrecord table.

**Comment by kcondon** [comment]
OK looks good. Closing.
