### ISSUE TITLE
geoconnect: return to dataverse link

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#1534]
Show modal message:  "Your map has been saved back to Dataverse."

[ Keep Map ]    [ Delete Map ]  [Return to GeoConnect]

**Comment by raprasad** [comment]
Functional (not designed) version is available. 
Potential test link on demo: https://dataverse-demo.iq.harvard.edu/dataset.xhtml?globalId=doi:10.5072/FK2/UADIWO&versionId=16

![style_map](https://cloud.githubusercontent.com/assets/1036060/6564488/51e1cb70-c67f-11e4-8bf9-638719de9e56.png)

/cc @mheppler @eaquigley

**Comment by eaquigley** [comment]
@raprasad i'm passing this back to you for post 4.0. i'd like to usability test this and see how users feel about the three buttons and if it makes sense.

**Comment by raprasad** [comment]
(unassigning for now until user testing is scheduled/mapping is stabilized)

**Comment by raprasad** [comment]
putting in overall usability issue
