### ISSUE TITLE
Account/Data Related to Me - [Return] on Search Input Broken

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1537]
When on the Dataverse Account/Data Related to Me page, and you type in a search term into the search input, and hit "Return" on the keyboard, it does not run the search.

**Comment by scolapasta** [comment]
Since we are getting rid of search on this page, this goes away.

**Comment by dliburd** [comment]
Even though this is going away, search was tested and successfully verified on dataverse internal.
