### ISSUE TITLE
Linked Dataset: Pop up button says done, should say cancel.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1538]
Linked Dataset: Pop up button says done, should say cancel.

In Linked Dataverse popup says cancel.

**Comment by mheppler** [comment]
Changed button to read "Cancel" on Link Dataset popup on the dataset page.

**Comment by kcondon** [comment]
OK, works, closing.
@mheppler What happened to the success message?  Opening new ticket
