### ISSUE TITLE
Delete Dataset: Deleting a draft does not call reindex so draft card remains.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1539]
Delete Dataset: Deleting a draft does not call reindex so draft card remains.

**Comment by scolapasta** [comment]
related to #1316

**Comment by pdurbin** [comment]
@kcondon I can't reproduce this. Not locally and I even ran a build on https://apitest.dataverse.org where a dataset is deleted as part of a post-deploy test. I don't see any cards. Can you please help me reproduce it? Passing back to you.

**Comment by kcondon** [comment]
Happens in UI, not API. Passing back.

**Comment by pdurbin** [comment]
I can reproduce the bug when I create a dataset in the root dataverse but not any child dataverse.

**Comment by pdurbin** [comment]
The deleteMultipleSolrIds method wasn't calling `commit`. Now it is. Passing to QA.

**Comment by kcondon** [comment]
Works, closing
