### ISSUE TITLE
Log in: Not specifying a password results in null ptr error in log file.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1542]
Seeing as this was reported for create account, reporting it for log in too.

**Comment by pdurbin** [comment]
Please note that @akio-sone has proposed a fix at https://github.com/akio-sone/dataverse/commit/71f1a980cdf3c6543f7a287490393ecc36c20bc6 as part of #1616

**Comment by kcondon** [comment]
Works, no error in log, closing
