### ISSUE TITLE
Add Distribution Date as a Metadata Field in Citation Block

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#1546]
After some discussion w/ @mcrosas @scolapasta @ekraffmiller we will be adding Distribution Date as an editable metadata field and will make sure all previous studies that used this field will have that date migrated over successfully. Adding this to the Citation metadata block tsv file.

We also discussed that for the migration and for Dataverse 4.0 and on: the Publication Year in the Data Citation for the Dataset will use the 1st Release/Publication Date in Dataverse, which is a system generated date. Not all datasets in 3.6 have a distribution or production date so this is the most reliable date to pull from for migration.

**Comment by posixeleni** [comment]
@pdurbin Setup a Metadata-Beta14 branch for these changes. So you can do schema.xml update. How would we merge these changes back into the master? Or would I just check these into the master if it works ok in the branch?

**Comment by pdurbin** [comment]
Merged! And I committed a new Solr schema.xml. Passing to QA.

**Comment by kcondon** [comment]
Field is editable, searchable. Validation is broken at the moment but opened as a separate ticket. Closing
