### ISSUE TITLE
Browse - Files - Logged Out

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1548]
I got a weird view of my local dataverse, when I was automatically logged out on a deploy.

![screen shot 2015-03-02 at 9 59 15 am](https://cloud.githubusercontent.com/assets/687227/6444497/e68bc140-c0cb-11e4-8566-f4b4dcb68cd9.png)

It's got a message about logging in, but then it also displays the facets, paginator, results counter, etc. -- just no files.

But, if I browse to the page normally, I get what the page SHOULD look like, when not logged in.

![screen shot 2015-03-02 at 10 06 06 am](https://cloud.githubusercontent.com/assets/687227/6444505/f22a4ac6-c0cb-11e4-99c0-46dbbd25a138.png)

Here is the URL.

http://localhost:8080/dataverse/mheppler?id=2&q=&types=files&sort=release_or_create_date_dt&order=desc&page=3

I was able to copy and paste it into a completely different browser, and got the same weird logged out view.

**Comment by pdurbin** [comment]
I saw it with my own eyes at http://mheppler.pagekite.me/dataverse/mheppler?id=2&q=&types=files&sort=release_or_create_date_dt&order=desc&page=3

Weird. Obviously, "21 to 12 of 12 results" makes no sense either.

**Comment by pdurbin** [comment]
@mheppler can you reproduce this in "develop"?

**Comment by mheppler** [comment]
No. That said, I didn't know how to reproduce this state then, I still don't know how to reproduce it now.

**Comment by pdurbin** [comment]
Ok. I doubt this issue has much value staying open then. I recommend we close it. Moving to QA.
