### ISSUE TITLE
Create a Custom Metadata Block for Murray Archive

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#1549]
After speaking with @sbarbosadataverse we decided the best way to preserve browsing of MRA collections is to make them into their own Metadata Block with a controlled vocabulary based on the 3.6 collection. Will check this in as a new custom metadata block.

For migration: @scolapasta could we easily map the collection names from 3.6 to this new metadata field based on matching controlled vocabularies?

**Comment by posixeleni** [comment]
@pdurbin @kcondon when I check this in (along with #1546) it will require a schema.xml update and a db drop for it to display and work in the GUI

**Comment by pdurbin** [comment]
> when I check this in (along with #1546) it will require a schema.xml update and a db drop

@posixeleni in that case, please consider making your changes in a branch.

**Comment by posixeleni** [comment]
@pdurbin Setup a Metadata-Beta14 branch for these changes. So you can do schema.xml update. How would we merge these changes back into the master? Or would I just check these into the master if it works ok in the branch?

**Comment by pdurbin** [comment]
@posixeleni as I mentioned I'm getting errors when I try to load up https://github.com/IQSS/dataverse/blob/4318f1a018bddb8cb978a9e0d5ced608e178f8f9/scripts/api/data/metadatablocks/citation.tsv

```
  StandardWrapperValve[edu.harvard.iq.dataverse.api.ApiConfiguration]: Servlet.service() for servlet edu.harvard.iq.dataverse.api.ApiConfiguration threw exception
java.lang.ArrayIndexOutOfBoundsException: 14
	at edu.harvard.iq.dataverse.api.DatasetFieldServiceApi.parseDatasetField(DatasetFieldServiceApi.java:276)
	at edu.harvard.iq.dataverse.api.DatasetFieldServiceApi.loadDatasetFields(DatasetFieldServiceApi.java:224)
```

@scolapasta said he could take a look so I'll give this to him.

**Comment by pdurbin** [comment]
p.s. This is not the master branch. This one: https://github.com/IQSS/dataverse/tree/metadata-beta14

**Comment by posixeleni** [comment]
@pdurbin issue should be resolved with citation.tsv file. It was missing a necessary value at the very end of the table. Checked a fix in so it should be working now.

Sorry!

**Comment by scolapasta** [comment]
@pdurbin if this is fixed, since other branch, feel free to just close.

**Comment by posixeleni** [comment]
@scolapasta but wouldnt we want to merge this branch or have me re-commit this citation.tsv to the master branch?

**Comment by pdurbin** [comment]
All set. @posixeleni pushed a fix to the branch and there I updated the Solr schema.xml and merged to master. Passing to QA.

**Comment by kcondon** [comment]
Murray block works, has one new field with controlled vocab that represents the current production collections. All are facetable, searchable.

**Comment by posixeleni** [comment]
Re-opening for @scolapasta to help us figure out how we can automate the mapping of the Murray Collections from 3.6 to this new facet.

**Comment by posixeleni** [comment]
We will also need to figure this out for Journals so we map their Collections to the new Journals metadata block

**Comment by sbarbosadataverse** [comment]
will open in data-curation
