### ISSUE TITLE
Shibboleth: make use of redirectPage logic for shib users

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#1551]
"Implement redirect logic for when a user logs in or signs up when they aren't on the homepage" was developed in #869 but only **builtin** users benefit from it. It would be nice if Shibboleth users got the same feature.

For Shibboleth, we'd need to pass the "redirectPage" parameter and value (i.e. redirectPage=%2Fdataverse.xhtml) to the Shib Identity Provider (IdP) and have the IdP return it to us.

**Comment by pdurbin** [comment]
I mentioned what I think will be the fix at http://irclog.perlgeek.de/shibboleth/2015-04-14

I'll have to figure out how to get the redirect value and pass it here: https://github.com/IQSS/dataverse/blob/293af79b5efa0ec159a30f3e66cc940de272d97d/src/main/webapp/resources/js/shib/idpselect_config.js#L17

**Comment by pdurbin** [comment]
@scolapasta I have this issue marked as "out of scope" right now for #2939 but I've mentioned to @mheppler that I'd take a look. Can I pick your brain about the code? I'm attaching a diff for the area of the code I'm messing with. The diff contains hard-coded values but when we do this for real we'd need to get the values from the backing bean and put them somehow in the Javascript. Anyway, here's the diff: 
[diff.txt](https://github.com/IQSS/dataverse/files/158962/diff.txt)

**Comment by pdurbin** [comment]
I think I got this working in 96adc39. I just deployed this to https://shibtest.dataverse.org if @mheppler @eaquigley or others would like to check it out. Please note that I have **not** yet addressed #2952 which is related (but should be straightforward).

**Comment by pdurbin** [comment]
As I mentioned in this morning's standup I was hoping that the fix at 96adc39 I pushed on Friday was a good one but I noticed that Shibboleth users are sometimes redirected properly, sometimes (especially when you completely clear your browser cache), they can't log in at all! Since this issue is a "nice to have" for phase 1 (#2939) I backed out of the fix in 2d5130c. @scolapasta said he'd like to take a look so I'll give this issue to him. I was [lamenting](http://irclog.iq.harvard.edu/dataverse/2016-03-07#i_32391) to @bmckinney that this issue is tricky to work on because (I think) you need a full Shibboleth environment set up. In practice, for me, this means redeploying to https://shibtest.dataverse.org after every little change. On the Shib mailing list long ago, I did ask about [running Shibboleth on my Mac](http://shibboleth.net/pipermail/users/2014-April/014907.html) but it seems tricky. Maybe someday Shibboleth could be part of our dev setup (#2443 is related) to make hacking on Shibboleth related code easier.

**Comment by bencomp** [comment]
It appears that in our adaptation of DVN 3.6 we notice that the page a user was on before logging in is available in the referrer header. The user interface does not need to change any links.

**Comment by bencomp** [comment]
And with regard to deploying after every change: you have Jenkins for that, right? :)
Have you tried Selenium for automating (parts of) user interaction tests?

**Comment by pdurbin** [comment]
This week in the "2016-10-18 Meeting and demo about OAuth and ORCID login" notes at https://docs.google.com/document/d/1Lja6sqG0Ljg2Q6suoMJbYr3J01DTpw6HkgvRwdbEDXQ/edit?usp=sharing I mentioned that ideally we'd also let ORCID users make use of the redirect logic that local users benefit from. In the code local users are called "builtin" users.

**Comment by donsizemore** [comment]
Odum received a request for this functionality; bumping on behalf of Carleton College.

**Comment by pdurbin** [comment]
@donsizemore thanks for the feedback. Perhaps this could be addressed at the same time as #3486.

**Comment by pdurbin** [comment]
We had what I thought was a nice solution in place in pull request #3539 but we backed out of it in 3f03f6f.

Last week @thegaryking mentioned he's interested in a fix.

A couple days ago @aivanov100 posted about an approach that works for their installation which is Shibboleth-only: https://groups.google.com/d/msg/dataverse-dev/SaVf172LQ4o/jb3AOqyvBAAJ . Here's the diff he included which is worth studying at least, even if it's not a drop-in solution: [shib_login_links.diff.txt](https://github.com/IQSS/dataverse/files/937657/shib_login_links.diff.txt)

**Comment by aivanov100** [comment]
@pdurbin my approach is specific to our implementation in that we do not want our users to use the IdPSelect dropdown to login.  We are not configuring a Federated IdP, we are just trying to trick our users into thinking that our Drupal site and our Dataverse site are two different parts of the same site.  For both Drupal and Dataverse, we've overwritten the Login links to point directly to our IdP login page.  The redirecPage parameter is set in the url query string, so the user is successfully brought back to the page they were on when they clicked Login.  However, our approach would not work if logins from multiple IdPs were supported and the IdPSelect dropdown was involved in the login process.

Best,
Alex

**Comment by pdurbin** [comment]
@aivanov100 ok, so your approach isn't generalizable. That's fine. Thanks.

**Comment by donsizemore** [comment]
Odum received another request for this functionality; bumping on behalf of East Carolina University.

**Comment by pdurbin** [comment]
@donsizemore thanks. Speaking of bumping, please note that as of last week we have introduced a new column in https://waffle.io/IQSS/dataverse called "Inbox" where this issue currently lives. Here are the definitions:

- Inbox: Any open issues automatically show up in this column.
- Backlog: Prioritized list of items for future sprints
- This Sprint: The items for the next sprint.
- etc

Here's how it looks:

![screen shot 2017-05-22 at 11 11 43 am](https://cloud.githubusercontent.com/assets/21006/26315693/f0bd4ba4-3edf-11e7-8895-0eb0eb87071d.png)

You are welcome to leave comments but I hope this helps explain the process. 😄

**Comment by kcondon** [comment]
Boston College also asked about it: RT 249556

**Comment by donsizemore** [comment]
Tested on dataverse-test.irss.unc.edu - works as advertised.

**Comment by pdurbin** [comment]
Pull request #3910 looks good! Thanks, @aivanov100 for making it and @donsizemore for testing it!

**Comment by pdurbin** [comment]
@kcondon noticed that pull request #3910 was behind develop so I just created pull request #3929 which is the same code (commits by @aivanov100 and @oscardssmith) but with the latest from develop merged in.
