### ISSUE TITLE
Document handling of "subject"

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#1553]
Looking into #1430 revealed that behavior with regard to `dcterms:subject` in SWORD has changed from 3.6 to 4.0. In 3.6 this field mapped to `keyword`. Now it maps to both `keyword` and `subject` with special processing if the value matches the controlled vocabulary. This should be documented.

**Comment by eaquigley** [comment]
Documentation for Shibboleth is done. Closing this issue. If any issues arise relating to Shibboleth Documentation, a new issue should be created.

**Comment by pdurbin** [comment]
@eaquigley this has nothing to do with Shibboleth. It has to do with the "native" API and SWORD. The code in question was written by @ekraffmiller or @rtreacy I believe.

**Comment by eaquigley** [comment]
had too many tickets open. whoops!

**Comment by posixeleni** [comment]
@pdurbin I had documented this new mappin behavior in the DC Terms - Dataverse DB Element Crosswalk in the SWORD API documentation see #1077  but for some reason this table is no longer showing in the guide. Who removed this?

**Comment by posixeleni** [comment]
@pdurbin - I fixed the display issue someone had improperly edited the table markdown causing it to not be recognized by Sphinx or GitHub https://github.com/IQSS/dataverse/blob/master/doc/sphinx-guides/source/api/sword.rst

The documentation for how we handle dcterms:subject is in the crosswalk table and can be sent to QA

**Comment by eaquigley** [comment]
@posixeleni thanks for making this change. closing ticket as this is now found in the crosswalk table.

**Comment by pdurbin** [comment]
Actually, more importantly (I believe), the example XML shows how you can use controlled vocabulary values in dcterms:subject now:

```
   <!-- Dataverse controlled vocabulary subject term -->
   <dcterms:subject>Chemistry</dcterms:subject>
   <!-- keywords -->
   <dcterms:subject>coffee</dcterms:subject>
```

**Comment by posixeleni** [comment]
@pdurbin both help :+1:
