### ISSUE TITLE
Dataverse Popup - Clean Up UI/Markup

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1559]
Style the messages and clean up button spacing on dataverse related popups.

- [x] Publish
- [x] Featured Dataverses
- [x] Linked Dataverse
- [x] Metadata Reset Modification

**Comment by mheppler** [comment]
Cleaned up popups layout, message formatting on dataverse page.

**Comment by kcondon** [comment]
Looks good, closing
