### ISSUE TITLE
Facets: Double rainbows! Two Less links: click one and then see another one.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1561]
Check out this dv, click less link under Murray facet, see another less link.
https://dvn-build.hmdc.harvard.edu/dataverse/m2

**Comment by eaquigley** [comment]
This should say More not Less to begin with so it seems that something has happened and the More link has disappeared and is now Less.

**Comment by mheppler** [comment]
Fixed duplicate (Double Rainbow!) "Less..." link text in browse/search facets.

**Comment by eaquigley** [comment]
No longer seeing too Less... links. Closing ticket.
