### ISSUE TITLE
Dataset: Date validation is no longer happening.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1562]
Dataset: Date validation is no longer happening for any date field.

**Comment by sekmiller** [comment]
Date validation is happening in general.  There is an issue with "year only" accepting alpha-numeric entries.  Will investigate

**Comment by sekmiller** [comment]
Date validation will now reject years that are non-numeric

**Comment by posixeleni** [comment]
validation works as expected. Closing.

![image](https://cloud.githubusercontent.com/assets/5013837/6714050/9f5c30a4-cd6c-11e4-8d33-cb646a9d9d4d.png)
