### ISSUE TITLE
Dataverse - Edit General Information - Metadata Fields/Select Facets Improvements

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1563]
- [x] Label for the section should be an item (noun) and capitalized, like "Browse/Search Facets", and not an action ("Select facets")
- [x] "Uncheck" action text needs to move from the checkbox label to the help text, "Uncheck to pick the metadata fields to use as facets for browsing datasets and dataverses in this dataverse."
- [x] Label for checkbox should just read, "Browse/Search Facets from \#{Parent} Dataverse"
- [x] Add spacing to Metadata Fields first checkbox, and the rest of the custom blocks, as well as second help text message.
- [x] Apply same double help text message to Browse/Search Facets.
- [x] Label for the checkbox is still displayed, when the checkbox isn't, on the Root Dataverse for both Metadata Fields and Browse/Search Facets, there should be nothing displayed, and render logic should also be added to the help-block.

**Comment by mheppler** [comment]
Cleaned up the UI, labels, and help text on Dataverse Edit General Information.

Passing to @eaquigley to revise help text as needed.

**Comment by eaquigley** [comment]
Passing to QA as I have updated the help text in the metadata fields and browse/search facets areas.

**Comment by eaquigley** [comment]
Everything looks good. Closing ticket.
