### ISSUE TITLE
Account Information: Terms of Use Appearing

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1565]
On Edit Account Information and Edit Password pages, the Terms of Use and Terms of Use Checkbox are now appearing.

**Comment by mheppler** [comment]
Changed the Terms of Use to only appear on "CREATE" workflow.

**Comment by kcondon** [comment]
OK, this is gone now but there is a requirement for migration that all users change their password and accept TOU. There is a workflow and conditional render logic for this on this page. It is covered under a separate ticket but there is some static text alluding to this process that I will ignore for now until the other ticket comes my way.

Closing.
