### ISSUE TITLE
Dataset Page UI Changes/Updates

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1568]
- [x] Make citation block background a bit lighter
- [x] Keyword tool tip broken when displayed above the tabs

**Comment by mheppler** [comment]
Changed background color of citation blocks on Dataset page and search-include to be a lighter blue. Moved CSS to stylesheet.

Passing to @sekmiller in order to look into the Keyword tool tip that isn't being delivered from the backend/tsv.

**Comment by sekmiller** [comment]
Fixed and checked in

**Comment by eaquigley** [comment]
Both items are fixed and look good. Closing ticket.
