### ISSUE TITLE
Tooltips: Change Pointer from Hand to Arrow

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1570]

**Comment by mheppler** [comment]
To fix this, I am changing the mark up from an a tag, to a span tag. This will solve the issue with the cursor acting like labels with tooltips are links to another page.

**Comment by mheppler** [comment]
- [x] dataset
- [x] themeAndWidgetFragment

**Comment by mheppler** [comment]
Related to and can be tested in conjunction with #1325.

**Comment by mheppler** [comment]
Sending both the buttons and tooltips tickets to QA. I have spent most of this week going through the entire site, and cleaning up as much as I can find. If there are any additional tickets related to these two issues, they should have individual tickets.

**Comment by eaquigley** [comment]
Tested and confirmed all of the ones listed above have a pointer not a hand appear when you hover over the tooltips. Closing ticket.
