### ISSUE TITLE
Help Text: Change from Blue to Gray

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1571]
In the Dataverse General Information edit form, the help text for Metadata Fields and "Select Facets" (soon to be "Browse/Search Facets") is blue, the same as the link on the site. Change this to the help text gray that is being used through out the rest of the site.

This blue help text is also found on:
- [x] API Token
- [x] Dataverse, General Information

**Comment by kcondon** [comment]
OK, blue is now gray, closing.
