### ISSUE TITLE
Advanced Search: Add Chevrons to Panels

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1572]
- [x] Also, panels are blinking before you close them. Not sure if you can fix this.

**Comment by mheppler** [comment]
Added chevrons to section panels, utilized javascript function to swap the icons when collapsed. Fixed blinking issue when collapsed. ca106432044691895382a3dc10f4d002777bf122

**Comment by mheppler** [comment]
When adding the chevrons and fixing the blinking, I changed code in the dv_rebind_bootstrap_ui.js, which swapped the UP and DOWN chevrons on panel collapse on the following pages:

- advanced
- dataset
- metadataFragment
- permissions-manage
- permissions-manage-files

**Comment by eaquigley** [comment]
Looks good. Tested all listed above. Closing ticket.
