### ISSUE TITLE
Search Keyword Highlight -- Mulitiple "Description Text" Highlight Hits

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1575]
On a search of "twice", the search card highlights gave me three returns of the Description Text field. (See attached.)

Here is the single description from the dataset.

````
Metadata Publish Twice Metadata Publish Twice Metadata Publish Twice Metadata Publish Twice Metadata Publish Twice Metadata Publish Twice Metadata Publish Twice Metadata Publish Twice Metadata Publish Twice Metadata Publish Twice 
```` 
![screen shot 2015-03-04 at 10 25 04 am](https://cloud.githubusercontent.com/assets/687227/6486415/bdd6fb82-c258-11e4-8bd6-b46a782d9fdd.png)

**Comment by pdurbin** [comment]
Weird, I'm seeing it from the Search API too:

```
$ curl -s "http://localhost:8080/api/search?q=twice&key=$ADMINKEY&show_relevance=true" | jq .data.items[].matches
[
  {
    "dsDescriptionValue": {
      "snippets": [
        "Metadata Publish <span class=\"search-term-match\">Twice</span> Metadata Publish <span class=\"search-term-match\">Twice</span> Metadata Publish <span class=\"search-term-match\">Twice</span> Metadata Publish <span class=\"search-term-match\">Twice</span>",
        " Metadata Publish <span class=\"search-term-match\">Twice</span> Metadata Publish <span class=\"search-term-match\">Twice</span> Metadata Publish <span class=\"search-term-match\">Twice</span> Metadata Publish <span class=\"search-term-match\">Twice</span> Metadata",
        " Publish <span class=\"search-term-match\">Twice</span> Metadata Publish <span class=\"search-term-match\">Twice</span> "
      ]
    }
  }
]
```

Maybe I introduced this in 20c304fa5be5c2b83089977e0e78d0db53fd0d17 for #1262

**Comment by pdurbin** [comment]
Confirmed. By changing setHighlightSnippets from 1 to 10 I introduced this bug. I was trying to improve highlighting as I described at https://github.com/IQSS/dataverse/issues/1262#issuecomment-76231675

@scolapasta please let me know how much time you want me to spend on this.

**Comment by pdurbin** [comment]
@scolapasta and I agreed to revert to the old behavior. The bug above should no longer be reproducible with this string as the description of a dataset: "Metadata Publish Twice Metadata Publish Twice Metadata Publish Twice Metadata Publish Twice Metadata Publish Twice Metadata Publish Twice Metadata Publish Twice Metadata Publish Twice Metadata Publish Twice Metadata Publish Twice"

Passing to QA.

**Comment by sbarbosadataverse** [comment]
I searched for "Twice" in dvn-5, and no multiples of description field returned in search results
