### ISSUE TITLE
Removing Metadata Blocks from Dataverse: How should this effect Templates in the DV?

### ISSUE THREAD

**Issue by sekmiller** [IQSS/dataverse#1576]
If a DV removes a metadata block but existing Datasets have data from the removed block that data will be viewable by all (with permissions) and at edit time all of the fields associated with that block will be available for edit.  What should be done for Templates?

**Comment by scolapasta** [comment]
checked with @posixeleni , same logic as datasets

**Comment by sekmiller** [comment]
Fixed and available for testing

**Comment by posixeleni** [comment]
Works as expected. Closing.
