### ISSUE TITLE
Linked files: Icons are appearing even if file isn't linked

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1578]
In the search/browse cards, the linked icon is appearing on all files. 

From @mheppler:
I just tested locally, that linked files ARE displaying properly. The bug is that the icon is displaying for ALL files.
Here is the logic that I used to display the linked icon on the file cards.

<span class="glyphicon glyphicon-link text-muted pull-right" jsf:rendered="#{!result.parent.get('isInTree')}"/>

**Comment by sekmiller** [comment]
Fixed and checked in. Build required.

**Comment by kcondon** [comment]
Works closing
