### ISSUE TITLE
App Version Number - Move Out of DataverseServiceBean

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1579]

**Comment by pdurbin** [comment]
@mheppler since you opened this issue are you particularly invested in it? Would you like to see it go through QA? I ask because @bencomp created a pull request (almost a month ago) for it at #2877. If you feel like it, you could get on that branch and see if everything looks ok to you.

**Comment by mheppler** [comment]
Pretty sure the lack of detail in that initial comment on this one reflects the amount I am invested. If I had to guess, this was a feature that I requested, it got thrown into the app during 4.0-haste, and @scolapasta said, "create a ticket to review this, so that we don't forget, and do something better with it."

**Comment by pdurbin** [comment]
@mheppler yeah, that's what I was thinking too. You probably volunteered to enter tickets during a meeting long ago or something. I've done the same.
