### ISSUE TITLE
Guestbook Error: Not Recognizing Required Fields Have Been Filled Out

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1580]
This is happening:

![filledoutform](https://cloud.githubusercontent.com/assets/5922904/6490808/fbd56662-c276-11e4-9925-8cbd4136b0b8.jpg)

![error](https://cloud.githubusercontent.com/assets/5922904/6490803/f744dda8-c276-11e4-9396-e062184b0112.jpg)

**Comment by posixeleni** [comment]
Getting an internal server error (500) when saving a newly created Guestbook in build

![image](https://cloud.githubusercontent.com/assets/5013837/6715371/79cebc28-cd74-11e4-815a-63ddfea1a040.png)

**Comment by posixeleni** [comment]
Now working as expected closing.
