### ISSUE TITLE
Groups: Issues with how we handle uniqueness: id, name.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1581]
In create group, duplicate ids are prevented with a general validation error but it doesn't indicate what went wrong. 

Also, names can be duplicates but when assigning permissions it is not possible to determine which is which. This is the same issue we have with users that may be addressed by adding another piece of info such as id or email. Same could be done here. @scolapasta would have the latest thinking on this.

**Comment by scolapasta** [comment]
For second part, solved in #1584 

@michbarsinai can you give a better validation error?

**Comment by michbarsinai** [comment]
Implemented, not pushing due to freeze.

**Comment by sbarbosadataverse** [comment]
"Group ID"- duplicate- validation error clearly indicates that the "group id already exists/is duplicate"
Can still create two identical "group names" when group "ID is" different
It is possible to distinguish which group ID the identical names belong to:

https://www.dropbox.com/s/irperm3spsqgwnq/Screenshot%202015-03-30%2016.37.43.png?dl=0
