### ISSUE TITLE
Move Community Norms and Sample Data Usage Agreement Out of User Guide

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#1583]
Discussed with @mcrosas & @eaquigley that Community Norms and Sample Data Usage Agreement should be moved to dataverse.org Best Practices > Harvard Dataverse Policies. 

Once these are moved we will need to update the link in License + Terms of Use that points to "Community Norms"

**Comment by posixeleni** [comment]
@mheppler here is the new URL for Community Norms: http://best-practices.dataverse.org/harvard-policies/community-norms.html

**Comment by mheppler** [comment]
Also from Merce, regarding the Community Norms text/link on the License + Terms tab, for end users, she'd like the text updated to:

Our {link}Community Norms{link} as well as good scientific practices expect that proper credit is given via citation. Please use the data citation above, generated by the Dataverse.

**Comment by mheppler** [comment]
Changed the help text for end users on the License/CCO field of the License + Terms tab. Changed the URL for the Community Norms link.

**Comment by kcondon** [comment]
Linked and text changed, closing
