### ISSUE TITLE
Manage Permissions: Add Identifier for Users/Groups

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#1584]

**Comment by scolapasta** [comment]
This needs to be added to all the autocompletes (assign role, create group, and grant (file) access).

The logic is:

                            <p:column>
                                <h:outputText value="#{roleAssignee.identifier}" />
                            </p:column>   

But I imagine at this point it probably makes sense to use something other than 3 columns (or at least add text to identify what each is?)

So passing to @mheppler .

**Comment by mheppler** [comment]
I'm going to wire up the autocomplete dropdown user info tables to look a little something like this.

![screen shot 2015-03-04 at 7 18 18 pm](https://cloud.githubusercontent.com/assets/687227/6496561/5cdd3f8a-c2a3-11e4-911c-bca87629d6b6.png)

**Comment by mheppler** [comment]
Added user identifier to the autocomplete dropdown user info tables on all role/permission related pages.

**Comment by mheppler** [comment]
Added render logic to user affiliation in the autocomplete dropdown user info tables on all role/permission related pages.

**Comment by kcondon** [comment]
@mheppler Need to add identifier to the assigned tables too: dv, ds, file, otherwise for whom am I granting/ removing access?

**Comment by mheppler** [comment]
It looks like identifier isn't easily added to those table views, so I will have to check in a static placeholder and pass it back to Gustavo. I am also going to add the affiliation, since that is also in the autocomplete user info table.

Here is a screenshot of what I'll be checking in.

![screen shot 2015-03-05 at 2 11 15 pm](https://cloud.githubusercontent.com/assets/687227/6512402/ba8cebf0-c341-11e4-9753-e3bbc1f4c2e3.png)

**Comment by mheppler** [comment]
Added affiliation and static placeholder for identifier to the assign tables on the Manage Permissions pages.

**Comment by scolapasta** [comment]
Should just be "roleAssignment.roleAssignee.identifier" (or whatever is being used for roleAssignment, i/e the value that you put in var="XXX"

**Comment by pdurbin** [comment]
The internal useridentifer is used for role assignments (see #1151) so I don't think it's a good idea to expose this as a sort of pretend username. In #1445 I'm arguing for real usernames in some future version of Dataverse.

**Comment by mheppler** [comment]
Couldn't get "roleAssignment.roleAssignee.identifier" or anything of the like to work. Checked in a static place holder of "@identifier" into the Users/Groups table on both permissions-manage pages. Let me know what else should be going there.

**Comment by eaquigley** [comment]
Update display of this to be Given Name, Family Name, Username, Affiliation. Work with @mheppler on how this should look while @scolapasta figures out the logic.

@scolapasta did i miss anything in this comment?

**Comment by scolapasta** [comment]
Logic added - passing to @mheppler

**Comment by mheppler** [comment]
Cleaned up the Manage Permissions and Edit Access form for the Permissions section, as well as the display of users/groups display name and identifier in the Users/Groups section.
