### ISSUE TITLE
multi-line SWORD collectionPolicy (API Terms of Use) squished into a single line

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#1585]
First reported at https://github.com/IQSS/dataverse/issues/551#issuecomment-77267924

I'm getting strange results from a multi-line input file. It gets squished onto a single line like this:

`<collectionPolicy xmlns="http://purl.org/net/sword/terms/">This is line 1 of API terms.This is line 2 of API terms.This is line 3 of API terms.</collectionPolicy>`

I'm not sure how to fix this. Here's the multi-line file and how I put it in the database and checked the SWORD service document:

    $ cat /tmp/api-tos.txt 
    This is line 1 of API terms.
    This is line 2 of API terms.
    This is line 3 of API terms.
    $ curl -X PUT -d@/tmp/api-tos.txt http://localhost:8080/api/s/settings/:ApiTermsOfUse
    {"status":"OK","data":{":ApiTermsOfUse":"This is line 1 of API terms.This is line 2 of API terms.This is line 3 of API terms."}}
    $ scripts/api/data-deposit/service-document | grep collectionPolicy | head -1

**Comment by scolapasta** [comment]
Unless there's a demonstrable impact to users, this is unlikely to be worked on.

**Comment by pdurbin** [comment]
In practice we recommend a single line (a URL) anyway: http://guides.dataverse.org/en/4.3/installation/config.html#apitermsofuse
