### ISSUE TITLE
Refactor Harvard-specific settings out of setup-all.sh

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#1587]
We'd like the Harvard-specific setup commands in their own script, commented out by default from setup-all.sh.

**Comment by scolapasta** [comment]
In fact, removed from setup-all completely. (if we have to go and uncomment, it's just as easy to run it separately).

**Comment by pdurbin** [comment]
Ok, there's a new script at `scripts/api/setup-optional-harvard.sh` that currently only does one thing: set up the link for the Privacy Policy in the footer of the page. The link is hidden by default per #1547 so you can run the new script to see it. Passing to QA.

**Comment by kcondon** [comment]
Done, works, closing
