### ISSUE TITLE
Icons: Open lock not appearing on file card for users who are admins/owners.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1590]
Icons: Open lock not appearing on file card for users who are admins/owners. They do appear on files tab.

**Comment by mheppler** [comment]
This is what I've got locally. I'll take a look at dvn-build and see if I can figure out what's crappening there.

![screen shot 2015-03-05 at 11 17 27 am](https://cloud.githubusercontent.com/assets/687227/6508840/4be09098-c329-11e4-808f-fe46285f134f.png)

**Comment by mheppler** [comment]
This looks good on dvn-build. Sending back to QA to clarify or close.

![screen shot 2015-03-05 at 11 52 08 am](https://cloud.githubusercontent.com/assets/687227/6509567/1ef22916-c32e-11e4-82e2-dea60c698421.png)

**Comment by kcondon** [comment]
Confirmed this is working. Closing.
