### ISSUE TITLE
Add ability to host R Shiny Apps?

### ISSUE THREAD

**Issue by leeper** [IQSS/dataverse#1593]
I've been thinking about how to maximize value of datasets stored in Dataverse. In the R world, an increasingly common way of letting novice users play around with datasets is via [Shiny](https://github.com/rstudio/shiny), which is basically a web page front-end for an R server instance. Since Dataverse is already interfacing with R to some extent, it would seem like an obvious feature to be able to deposit a Shiny app into a Dataverse repository, which could be available via the "Explore" button that current takes users to TwoRavens (or something similar).

A particularly helpful use-case for this would be with data that has extensive permissions thus preventing it from being fully public. If Dataverse can allow a user to do some basic data exploration on a dataset that cannot be shared fully publicly, it may aid data transparency by allowing other users to at least examine an author-defined subset of relationships within the data.

Maybe this is really a suggestion for TwoRavens, not Dataverse per se, but I thought I'd put it out there as a suggestion and see what you think.

**Comment by mcrosas** [comment]
We've been considering something along these lines with @tercer @cchoirat
and @vjdorazio - Yes, this would fit into TwoRavens, so I'll probably move
it to the TwoRavens repo, after discussing it with them.

**Comment by pdurbin** [comment]
http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3950337/#BX1 says that [Synapse](http://synapse.org) has wiki pages that support "runnable R instances in the form of shiny apps." There seems to be a Shiny server at https://shiny.synapse.org . I wonder if there's potential for integration.

**Comment by brucehoff** [comment]
Yes, Synapse supports Shiny integration.  Here is an example: https://www.synapse.org/#!Synapse:syn2467714/wiki/64261

**Comment by mcrosas** [comment]
@leeper  could you move this issue to the TwoRavens repo (https://github.com/IQSS/TwoRavens)? I'm not sure if the whole use can be moved as it is, it needs to be copied manually. do you know?

**Comment by leeper** [comment]
I think it has to be moved manually, so I can just open a new issue there
and reference back to this one.
