### ISSUE TITLE
Google Analytics is not optional (or configurable?)

### ISSUE THREAD

**Issue by bencomp** [IQSS/dataverse#1594]
At DANS we are considering moving away from using Google Analytics (GA) to using an in-house installation of [Piwik](http://piwik.org/). However, the script code for GA is hardcoded and always uses the Harvard credentials.

Configuration of analytics could be a setting that can be accessed from the superuser interface (#1574).

**Comment by mcrosas** [comment]
This makes a lot of sense @bencomp - sent to @scolapasta for review

**Comment by scolapasta** [comment]
This was handled for 4.0, no?

**Comment by pdurbin** [comment]
> the script code for GA is hardcoded and always uses the Harvard credentials

This was fixed in #2069

**Comment by kcondon** [comment]
OK, noop, closing.
