### ISSUE TITLE
Visualization of Astronomy data with WWT

### ISSUE THREAD

**Issue by mcrosas** [IQSS/dataverse#1596]
We want to be able to visualize astronomy images and FITS files in the World Wide Telescope. This could follow a similar approach to visualizing geospatial data in WorldMap, but it should be much simpler to integrate since there is already an API to open any FITS files, and some image files in WWT. To discuss more with Gus.

**Comment by posixeleni** [comment]
@mcrosas I had already created a ticket for this last year: https://github.com/IQSS/dataverse/issues/1300

want me to close that one as duplicate?

**Comment by mcrosas** [comment]
yes, please. ANd sorry. I looked for that ticket and couldn't find it.

**Comment by posixeleni** [comment]
Closing this since it is a duplicate. See #1300
