### ISSUE TITLE
For Collections Migration: Make Additional Fields Facetable & Advance Searchable

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#1597]
To help migrate collections from 3.6 into facets we will need to make more fields facetable and advance searchable.

In **Citation Block**: it would be useful to have:
- Series (seriesName) field: facetable and advance searchable boolean set to TRUE.
- Kind of Data: facetable (already is advance searchable) boolean set to TRUE

Ex 1. RESTAT Dataverse uses Series field to track Journal volume and issue so it would be a helpful facet for them to have.
Ex 1. Economics: The Open-Access, Open-Assessment E-Journal uses Kind of Data frequently for their datasets.

In the **Social Science Block**: 
- Frequency: facetable and advance searchable Boolean set to TRUE
(ex. Economics: The Open-Access, Open-Assessment E-Journal use this field a lot)

In the **Geospatial Block**:
- Geographic Unit: Facetable and Advance Searchable Boolean set to TRUE (ex. MCH Data Connect Dataverse uses this)
- City: Facetable and Advance Searchable Boolean set to TRUE (ex. GSD Dataverse uses this once we migrate custom fields)
- State / Province: Facetable and Advance Searchable  Boolean set to TRUE (ex. GSD Dataverse uses this once we migrate custom fields)

**Comment by posixeleni** [comment]
@pdurbin i had to put in this change in order for this to make it into beta 14 before I left on my trip for @sbarbosadataverse to be able to setup facets for these dataverses that use to have collections in 3.6. 

Since we are altering the booleans for Advance Search and Facetable (setting them to TRUE) for the fields mentioned in the description this will most likely require a schema.xml change and a db drop.

I have checked these into a separate branch metadata-facets-beta14. Thanks!

**Comment by pdurbin** [comment]
@posixeleni due to the nature of these changes a new Solr schema.xml is not required (no effect from changing fields to facetable, for example) so I went ahead and merged eb101e8 into master. Heads up to @scolapasta about this.

Passing to QA. Please not the recommended database drop above by @posixeleni

**Comment by posixeleni** [comment]
@ekraffmiller since I changed the booleans for some metadata fields will this impact anything you have been working on metadata-wise?

**Comment by ekraffmiller** [comment]
@posixeleni , no that should be fine - no changed required for metadata

**Comment by kcondon** [comment]
OK, all are facetable and advanced searchable, closing.
