### ISSUE TITLE
Default Values for Deleted Template Show up in Add Data - Investigate

### ISSUE THREAD

**Issue by sekmiller** [IQSS/dataverse#1600]
While in the process of testing the effect of removing metadata blocks on datasets and templates I clicked Add Data and got a Dataset with default values from a template that was not in the drop down list of templates available.  It may have been deleted.  Regardless, not being in the drop down and providing values is troubling enough.

Investigating.

**Comment by sekmiller** [comment]
It was default template at the time it was deleted.

**Comment by sekmiller** [comment]
Templates will be deleted and removed as default for all dvs that have it. Also, user will be warned if the template is in use as a default for any dv.

**Comment by kcondon** [comment]
OK, works -deleted default template no longer affects new datasets. Closing.
