### ISSUE TITLE
Handle cases when Account ToU is modified

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#1602]
Currently, we don't store if a user accepted terms, we just now it has happened if they've successfully created an account (or logged in via Shib or reset their old 3.6 password)

We should determine a way to track, so that if we change it, we can make them accept it again.

**Comment by bencomp** [comment]
This relates to keeping track of the terms of use that a user agreed to: #1650 

Maybe the solution to this issue could be overlapping with the solution to keeping track?

`if` user-agreed-terms `!=` most recent terms `then` ask to agree to most recent terms

**Comment by pdurbin** [comment]
I think this is a good idea but it's been over two years since it has been suggested. Is anyone out there who is running Dataverse following this issue and still interested in this?

**Comment by pdurbin** [comment]
Closing in favor of #1602

**Comment by bencomp** [comment]
@pdurbin you closed this issue in favor of itself?

**Comment by pdurbin** [comment]
Whoops! Closing in favor or #4978. Thanks, @bencomp !
