### ISSUE TITLE
Should we have a ManageTemplates permission?

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#1603]
So curators can manage templates and not edit the dataverse.

**Comment by pdurbin** [comment]
@scolapasta we've gotten by without a ManageTemplates for years. Vote to close.

**Comment by oscardssmith** [comment]
If so, this should get a wontfix label

**Comment by pdurbin** [comment]
@oscardssmith it's a good idea to add a "Status: Won't Fix" label but let's give @scolapasta time to reply. I assume this label would only be applied to closed issues.

**Comment by pdurbin** [comment]
@qqmyers managed to split out a permission in PR #8174 so if we still want this (do we?) we have a nice model to follow. (Thanks, Jim!)

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
