### ISSUE TITLE
Guestbook: Fix select box for custom question.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1605]
The multi option custom question answer list appears as a select box when a user attempts a download. Currently it is misaligned and a little shortened.

**Comment by mheppler** [comment]
Fixed display of select dropdown for custom questions in the Guestbook popup for downloading a file. Cleaned up layout of the rest of the guestbook workflow.

This workflow might need additional clean up and development. That can be discussed after 4.0.

**Comment by eaquigley** [comment]
Looks good. Closing ticket.
