### ISSUE TITLE
Roles Names for Contributions to Dataverse

### ISSUE THREAD

**Issue by mcrosas** [IQSS/dataverse#1606]
@eaquigley remember that we said yesterday that we wouldn't change anymore the role names? Guess what? we would like to change it to:

Contributor (instead of Editor)
Curator (same)

OK?

**Comment by eaquigley** [comment]
@mcrosas makes sense. i've gone ahead and changed it in the Roles JSON file @scolapasta but can't remember, do i need to change it in the bundle too?

**Comment by scolapasta** [comment]
The name is in the Json file for the actual role, but I'm sure there's text in the bundle that refers to it.

**Comment by kcondon** [comment]
@eaquigley @mcrosas @scolapasta 

Is there a list somewhere of what the roles and perms should be at this point?

**Comment by posixeleni** [comment]
Now seeing Contributor (instead of Editor) and Curator is still showing as it was before.

Works as expected. Closing.
