### ISSUE TITLE
Review Good Tables from OKFN

### ISSUE THREAD

**Issue by mercecrosas** [IQSS/dataverse#1609]
The new Good Tables API my be useful for better CSV and Excel file support in ingest (or at least it would be interesting to review what they do and how it compares to what Dataverse does).

---

The Good Tables web service is an API and UI for processing tabular data, being an HTTP wrapper around Good Tables, which was previously announced on OKFN Labs.
- http://goodtables.okfnlabs.org
- https://github.com/okfn/goodtables-web
- https://github.com/okfn/goodtables

The Good Tables web service is currently an alpha release; we invite the community to start using and contributing to it to help us move towards a v1.0 release.

In the current release, the Good Tables web service will validate CSV and Excel files (the first sheet therein) for well-formedness, and, if a JSON Table Schema is supplied, for conformity to the given schema.

API docs can be found here: http://goodtables.okfnlabs.org/api

The run end point accepts GET and POST requests. Here are some example GET requests, using spend publishing data from UK government departments:
- http://goodtables.okfnlabs.org/reports?schema=https%3A%2F%2Fraw.githubusercontent.com%2Fokfn%2Ftabular-validator%2Fmaster%2Fexamples%2Fhmt%2Fbis-modified.json&data=https%3A%2F%2Fwww.gov.uk%2Fgovernment%2Fuploads%2Fsystem%2Fuploads%2Fattachment_data%2Ffile%2F230002%2FMay-2013.csv&ignore_empty_rows=True&row_limit=20000&format=csv&report_limit=1000
- http://goodtables.okfnlabs.org/reports?schema=https%3A%2F%2Fraw.githubusercontent.com%2Fokfn%2Ftabular-validator%2Fmaster%2Fexamples%2Fhmt%2Fbis-modified.json&data=https%3A%2F%2Fwww.gov.uk%2Fgovernment%2Fuploads%2Fsystem%2Fuploads%2Fattachment_data%2Ffile%2F318341%2Fbis-monthly-spend-february-2014.csv&ignore_empty_rows=True&row_limit=20000&format=csv&report_limit=1000

Good Tables can be used for any tabular data, not just send data. We hope to prepare more examples for that as the library moves out of alpha stage.

**Comment by pdurbin** [comment]
@oscardssmith I'd be curious to hear any thoughts you have on this since you're working on #3767.

**Comment by oscardssmith** [comment]
This has the advantage that it can check for duplicate rows (which we could do quite easily if we wanted to, which I don't think we do). Other than that, I see no advantages. It is slower than our parser (likely due to internet, but still worth considering), is not free for API use, is not open source, is not customizable by us, and fails to parse more complicated CSV files. All in all, while pretty and a cool idea, I don't think that this is a good fit for Dataverse.
