### ISSUE TITLE
Old Files - REMOVE YOUR UNUSED FILES!

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1610]
Listed here are all the old, unused files that need to be removed from the project:

- [ ] /doc/gui/ingest/language_encoding/AddFilesPage.xhtml
- [x] /src/main/webapp/manage-roles.xhtml
- [x] /src/main/webapp/sample-account-page-with-search.xhtml
- [x] /src/main/webapp/sample-search-include-page.xhtml
- [x] /scripts/api/role-bigboss.json

**Comment by scolapasta** [comment]
The first one is actually in the docs area, which needs general cleanup, so I created a new issue: #1797

Moving this one to QA.
