### ISSUE TITLE
Stop using @pete and @uma in the datasetversion_dataverseuser table

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#1611]
This issue was first noted at https://github.com/IQSS/dataverse/issues/1151#issuecomment-72055219 but deserves its own ticket.

When you create a dataset, the string for your "useridentifier" is persisted in the datasetversion_dataverseuser table:

```
+ psql -c 'select * from datasetversion_dataverseuser;' dataverse_db
 datasetversionid | useridentifier |     lastupdatedate      | datasetversion_id 
------------------+----------------+-------------------------+-------------------
                2 | @finch         | 2015-03-06 10:21:27.637 |                 2
                1 | @spruce        | 2015-03-06 10:21:31.359 |                 1
(2 rows)
```

Persisting these useridentifier strings makes the job of ever changing the useridentifier (in case of divorce, etc.) more difficult. You have to update all the rows in the datasetversion_dataverseuser table.

Instead the primary key of from the authenticateduser table should be stored. Since it's a primary key it will never change.

(The ticket for some day having a real username that users can freely and easily change at will is #1445.)

**Comment by sekmiller** [comment]
The DatasetVersionUser table now has an id foreign key into the Authenticated User Table...

**Comment by kcondon** [comment]
Table now uses a foreign key for user id. Closing.
