### ISSUE TITLE
"Support" + Account Name Navbar Links - (Safari) Isn't Aligned w/ Other Links

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1614]
Both "Support" and the account name dropdown links in the navbar are displaying at a different height/level than the other navbar links.

![screen shot 2015-03-07 at 9 10 14 am](https://cloud.githubusercontent.com/assets/687227/6541610/c53b8e26-c4a9-11e4-98ae-9f60c2727b04.png)

**Comment by mheppler** [comment]
I believe this is a caching issue. I have looked into the CSS code, it looks kosher. I have emptied my cahce, and redeployed my localhost environment, and all the links are good.

Sorry.

![screen shot 2015-03-08 at 2 44 31 pm](https://cloud.githubusercontent.com/assets/687227/6547046/b0ede754-c5a1-11e4-8f75-509c46ea1bf9.png)

**Comment by eaquigley** [comment]
Looks good. I had this appear when I first visited dvn-build this morning, refreshed and it went away. Closing ticket.
