### ISSUE TITLE
Shapefiles: Clean Up UI + Other Improvements

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1618]
The UI for the displaying of shape files in the dataset files table needs some cleanup. Here is a run down of items that need addressing.

- [x] "Map Data" vs. "Re-Map Data", the button text changes, shouldn't be necessary
- [ ] "preview" link for popup is just floating at the bottom of the file table row, this feature should be worked into the thumbnail preview/icon popover.
- [x] If dataset is unpublished, have a fake “Map Data” button that pops ups a message about needing to publish the dataset before being able to map it with WorldMap.
- [ ] Is there a better term than “Map Data”?

**Comment by raprasad** [comment]
When to show Map-related buttons

|Show Button?|Draft / File Not Published|File Published / No Map|File Published / Map Exists|Draft / Map Exists / File Previously Published|Draft / No Map /File Previously Published|Draft / New File (Unpublished)|
|----------- |----------- |----------- |----------- |----------- |----------- |----------- |
|Explore|||Yes|Yes|||
|Reminder*|Yes|||||Yes|
|Map||Yes|Yes|Yes|Yes|

* Message that once published, user can map file

@mheppler

**Comment by mheppler** [comment]
Added popup with message to a "Map Data" button on shape files for a dataset, that is only displayed when the file is unpublished.

Sending to @eaquigley to review the header and message of the popup.

Re: other tasks. "Map Data" was determined to be good enough. The "Preview" link was moved to the thumbnail area, and styled. Hopefully in a future release, we can review changing the functionality of that thumbnail for shape files, to open the preview, rather than the larger image preview.

**Comment by eaquigley** [comment]
Looks good. Created separate ticket for changing the messaging with the delete pop up #1826 
Closing ticket.
