### ISSUE TITLE
Clean up theme validation to use bean validation

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#1619]

**Comment by bencomp** [comment]
It would be great to have more information in this issue.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
