### ISSUE TITLE
Facet: File Type - More Specific for "Shapefile as ZIP Archive"

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1621]
Currently, when a "Shapefile as ZIP Archive" is uploaded to a dataset, on the dataverse page, it has a facet File Type of "application".

https://dataverse-demo.iq.harvard.edu/?id=&q=&fq0=filetype_s%3A%22application%22&types=files&sort=release_or_create_date_dt&order=desc

![screen shot 2015-03-09 at 6 23 12 pm](https://cloud.githubusercontent.com/assets/687227/6565831/63e95b26-c689-11e4-93fc-6ee2bfb99ad1.png)

**Comment by landreev** [comment]
@mheppler , 
I checked in a "facet" definition for shape files. 
Please take a look (you may need to reindex). 
Shape files should now appear under a facet "shape". If you want to change this name, edit src/main/java/MimeTypeFacets.properties, this line: 

application/zipped-shapefile=shape

(I'll review the other facets we  have there, to make sure they match the icon classes...)

**Comment by landreev** [comment]
(I meant to say *checked in a "friendly" facet definition...*)

**Comment by mheppler** [comment]
Looks good.

**Comment by eaquigley** [comment]
Tested this and Shape is appearing as a file type for Shape Files. Closing ticket.
