### ISSUE TITLE
Review File permissions page UI

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#1622]
This is just for the details here - for example not showing the file request table if it has no rows.

**Comment by scolapasta** [comment]
@mheppler will fill in other details of things he changes as he reviews it.

**Comment by mheppler** [comment]
Added render logic to empty file access request table on Manage File Permissions page.

**Comment by kcondon** [comment]
@mheppler Grant button and popup probably should not appear when there are no files. Otherwise works fine, closing
