### ISSUE TITLE
Create Account: When access level at root requires direct permission, newly created account just sees login page.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1623]
If a dataverse installation is configured to not allow users to create anything at root by default, when a user creates an account they see the login page with no other information.

**Comment by scolapasta** [comment]
I believe this is actually happening because the root is unpublished, not because of the access settings.

So the user does not have access to the root page. In practice the root will be published and avaialable to all.

**Comment by kcondon** [comment]
Yep, new account with published root and restricted access still sees other studies. Closing
