### ISSUE TITLE
Improve the automcomplete on permissions

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#1624]
Steps TBD, but one thing:
don't autocomplete on every keystroke if user is still typing

**Comment by scolapasta** [comment]
added:
 minQueryLength="2" 
queryDelay="1000"
cache="true"

**Comment by scolapasta** [comment]
there is also a nice group by feature, but we need to upgrade to primefaces 5 first (I added a new issue for this: #1669

**Comment by sbarbosadataverse** [comment]
Note sure how to test the querydelay and cache
but the minquerylength check out!

added:
minQueryLength="2"
queryDelay="1000"
cache="true"

**Comment by posixeleni** [comment]
@kcondon does this still need to be tested? please let me know if we can close this ticket

Thanks!

**Comment by kcondon** [comment]
Yeah, it can be closed. Basically the responsiveness of the matching is configurable and affects the user experience. Initially I thought it was a little erratic. It seems better now.
