### ISSUE TITLE
Download All: Download all tabular data bundle .zip cannot be opened from build.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1627]
When downloading all from a tabular file on build,  the resulting zip file is not able to be opened.
Please note that at the time of this writing, download as R was throwing a 503 error.

This works on demo.

**Comment by landreev** [comment]
Please re-test.

**Comment by landreev** [comment]
P.S. It should be working, and the zip file should be readable, whether Rserve is running or not.

**Comment by kcondon** [comment]
Works, closing
