### ISSUE TITLE
Dataset Description: Doesn't wrap when there are no spaces

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1634]
When you create a dataset description with no spaces, it doesn't wrap. Looks like this:
![datasetdescription](https://cloud.githubusercontent.com/assets/5922904/6585625/7d41b49a-c749-11e4-8757-b5366f33fcf8.jpg)

**Comment by mcrosas** [comment]
is there much one can do with this? It looks like "unwrappable" text ...


On Tue, Mar 10, 2015 at 5:18 PM, Elizabeth Quigley <notifications@github.com

**Comment by pdurbin** [comment]
Maybe `word-break: break-all;` or something per https://css-tricks.com/snippets/css/prevent-long-urls-from-breaking-out-of-container/ ? I think @mheppler may have already applied a similar to fix to facets because some of them can get quite long.

**Comment by djbrooke** [comment]
Closing in favor of #6578
