### ISSUE TITLE
Guestbook/TOU: Popup has a broken layout.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1635]
This was working earlier today but now the guestbook/tou popup has a broken layout.
Check out smoketest14 ds on build.

I am using 3 custom q's, one with select box. Also, tou and toa.

**Comment by mheppler** [comment]
![screen shot 2015-03-10 at 8 40 34 pm](https://cloud.githubusercontent.com/assets/687227/6588279/bef07f22-c765-11e4-9de7-31737f2ec9e9.png)

**Comment by mheppler** [comment]
Changed all buttons that used jsf:rendered to p:commandLinks, in order to fixed a layout bug on the Guestbook Download File popup.

**Comment by kcondon** [comment]
Works, closing
