### ISSUE TITLE
Make all Entities use GenerationType.IDENTITY

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#1636]
While working on migration, I found the ExplicitGroup entity to be using GenerationType.AUTO. I then checked and found several that have auto.

We should be consistent and have all our entities use the same GenerationType, which we typically use IDENTITY.

**Comment by scolapasta** [comment]
Did this in Beta 14, so as to try and avoid a db drop for beta 15.

**Comment by kcondon** [comment]
Done, smoke tested. Closing
