### ISSUE TITLE
Sign Up Page: Have Link to Log In Page

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1637]
We need to have a link to the log in page on the sign up page. Something like: Want to create your account through your institutional account? Log In here.

We can workshop the text.

cc: @pdurbin @bencomp

**Comment by bencomp** [comment]
Thanks for picking this up. I see that the [user guide](http://guides.dataverse.org/en/latest/user/account.html#create-user-account) already has a *FIXME* in place:

> FIXME: Shibboleth needs to be documented.

**Comment by eaquigley** [comment]
@mheppler could you please add this in for me on the sign up page to the right of the fields? 

Want to create your account through your institution? Log In here.

With link to log in page behind the Log In here text.

**Comment by mheppler** [comment]
Added help text on Sign Up for creating account with Institutional Log In with link to login page.

Passing to @pdurbin -- needs render logic on Line 278 for Shib being enabled. 
````
<ui:fragment rendered="#{true}">
     <p class="help-block"><span class="glyphicon glyphicon-info-sign"/> <h:outputText value=" #{bundle['user.institutionLogIn.tip']}" escape="false"/></p>
</ui:fragment>
````

**Comment by mheppler** [comment]
Please pass to @eaquigley after for QA.

**Comment by pdurbin** [comment]
> needs render logic on Line 278 for Shib being enabled

Done in 56f1ec2

Passing to @eaquigley for QA.

**Comment by eaquigley** [comment]
Looks great and works! Closing ticket.
