### ISSUE TITLE
Guestbook: Preserve order of multiple choice answers, as created.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1641]
Similar to the ordering of custom questions, the current order of custom multiple choice answers is unordered, so potentially a different order each time.

We should preserve the order as created.

**Comment by sekmiller** [comment]
Fix for this has been checked in. you'll need to rebuild and run this update query:

alter table customquestionvalue add column displayorder bigint;

**Comment by kcondon** [comment]
Order is restored. Closing
