### ISSUE TITLE
Create Dataset: Alternate metadatablock with required fields not appearing on create, prevents save

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1642]
If enable an alternate metadata block, such as geo, make one field required, country, then create a dataset, you cannot save, gives validation error about required field. This is because required field is not being displayed as part of create dataset.

 FYI, this works if using a template and populate fields in that metadata block.

**Comment by sekmiller** [comment]
It actually doesn't have to do with templates.  The issue was caused by setting a child field as required.  That wasn't being picked up by the required mdb's on create

**Comment by sekmiller** [comment]
It actually doesn't have to do with templates.  The issue was caused by setting a child field as required.  That wasn't being picked up by the required mdb's on create

**Comment by sekmiller** [comment]
Fix checked in for this. new build needed

**Comment by kcondon** [comment]
Works, closing
