### ISSUE TITLE
Dataset Template - UI Cleanup

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1643]
Manage Templates
- [ ] ~~View template popup doesn't scroll~~ #1672

Create Dataset
- [x] Host Dataverse value should include "Dataverse"
- [x] "Asterisks indicate required fields" message should be below the Dataset Template field

Create Dataset - Select Template/"clear default values"
- [ ] ~~Instead of: "No template - clear default values" - have a "Clear/Reset" button~~ #1674

**Comment by mheppler** [comment]
Minor layout improvements to dataset for the Create Dataset (with Template) workflow.

Created new high-level ticket to investigate all popups scrollability. #1672 

Created new ticket to investigate how to improve the Dataset Template dropdown on the dataset page, and it's functionality regarding the "No template - clear default values" option. #1674

**Comment by sbarbosadataverse** [comment]
@mheppler "No template-Clear default values" clears all fields except for "author" and "contact." Is this what I'm expecting in build or should all fields be cleared?

**Comment by mheppler** [comment]
@sbarbosadataverse -- that dropdown option is up to debate and will hopefully be redesigned to be clearer in a later release #1674.

That said, if the template enters "author" and "contact", then it should be cleared. If those fields are automatically pre-filled with user information from the current user in session, then those won't get removed by selecting that option. I think.

**Comment by sbarbosadataverse** [comment]
If previous comments is the case, this is working as expected.
