### ISSUE TITLE
Guestbook/TOU: Not completing required fields does not display an error.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1644]
This used to work, with the error on the main page rather than the popup. Now it just exits silently.

**Comment by sekmiller** [comment]
https://code.google.com/p/primefaces/issues/detail?id=6654

**Comment by sekmiller** [comment]
Errors now posting to popup.

Know Issues: Format of Accept Button (now Command Link) @mheppler - please look at command links at the bottom of the guestbook popup - around line 2040+

Inline message not showing if Custom Question is Multiple Choice and user leaves on "Select..." Message posts at top of popup and download is prevented.

Guestbook Pop-up stays up behind Two Ravens popup when Data Subset is invoked

**Comment by sekmiller** [comment]
Will write separate ticket for code cleanup of onComplete hack

**Comment by kcondon** [comment]
Works closing.
