### ISSUE TITLE
Guestbook: Disabling an actively used guestbook causes undead guestbook.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1645]
1. Create a guestbook, enable, assign to a dataset, publish.
2. Upload file, creates draft.
3. Become annoyed at answering complicated guestbook so disable it.
4. It still works on published dataset, *and* the draft one, though it says no guestbook available on licensing tab so can't get rid of it.
5. Publish draft dataset and newly published dataset has undead guestbook though it has dropped the custom questions.

**Comment by sekmiller** [comment]
If a guestbook is disabled at the DV level, it will no longer be shown to the end user at download time, even if it is selected at the DS level.  Once it is re-enabled it will be shown at download without any additional action by the DS owner.

**Comment by kcondon** [comment]
Works, closing.
