### ISSUE TITLE
Edit Dataset: Choosing a different TOU updates page and clears guestbook selection.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1646]
1. Edit dataset licensing, select an available guestbook.
2. Choose TOU rather than cc0, notice page refreshes and guestbook selection is cleared.

**Comment by sekmiller** [comment]
This is fixed.  A new build is required before it may be tested.

**Comment by kcondon** [comment]
Guestbook selection is preserved, closing.
