### ISSUE TITLE
Required asterisk is displaying oddly for a longer custom guestbook question 

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#1647]
![4a386d94-c737-11e4-982e-d5a6b97e76a4](https://cloud.githubusercontent.com/assets/4268292/6609286/f63277fe-c825-11e4-85e1-dc51addcce5c.jpg)

**Comment by mheppler** [comment]
@scolapasta @kcondon -- this is an old bug. In testing for why the layout of the Guestbook Download File popup was severely broken, I removed CSS code that was most likely the cause of this particular layout bug. It should be tested and closed.

**Comment by sbarbosadataverse** [comment]
I attempted to create a guestbook like the sample above, with additional question, no values, when hit save:  Internal Server Error - An unexpected error was encountered, no more information is available.

**Comment by sbarbosadataverse** [comment]
Asterisk not showing up at all after making custom field required (before hitting save)--is it supposed to show up in this page or after hitting save?

https://www.dropbox.com/s/gpu54j2ost0i6ga/Screenshot%202015-03-20%2012.51.48.png?dl=0

**Comment by sbarbosadataverse** [comment]
Required asterisk is displaying properly 
![yk6bnu6ccg_fviya6h-6pi1jg3rbd_jhfyejgctd5wi](https://cloud.githubusercontent.com/assets/8322346/6757492/db20cb58-cf07-11e4-866d-a16301ffbbcd.png)
for a longer custom guestbook question
