### ISSUE TITLE
Account/Sign Up/Change Password: Move Help Text

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1649]
Move help text to be above the Password input field and not in between password and confirm password.

**Comment by mheppler** [comment]
Moved help text on Password field of dataverseuser to be above the field, rather than below.

**Comment by mheppler** [comment]
Passing to @eaquigley to review the help text.

Current: "Password requirements are 6 characters with at least one letter and one number."

Suggested: "Requires minimum six characters with at least one letter and one number."

**Comment by eaquigley** [comment]
Updated in commit: 1ab106fd4d3be24a4471159789153c4207e521e6

Passing to QA.

**Comment by sbarbosadataverse** [comment]
Text is not aligned to what is suggested in this ticket:

 mheppler commented 7 days ago

Passing to @eaquigley to review the help text.

Current: "Password requirements are 6 characters with at least one letter and one number."

Suggested: "Requires minimum six characters with at least one letter and one number."

Help text is in correct location above the password field; but "pop up" text field says "AND"
help text says "OR."

![7tpir-qw-31owj749uo9izio85chxp8nvqrfhcq0pba](https://cloud.githubusercontent.com/assets/8322346/6758980/bd000d9a-cf12-11e4-97c5-fee8392ebe4d.png)

**Comment by mheppler** [comment]
@eaquigley - from @kcondon - New, 4.0-onboarding page, update password message also needs reviewing, along with mention of special characters.

**Comment by eaquigley** [comment]
added mention of special characters in commit 2ab5a1e05423d4f47474f968d66973a7415bfc66
