### ISSUE TITLE
File Categories: Need to Add "Code" as the third default option

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1652]
Currently have Data and Documentation. Still need Code as a default one.

**Comment by landreev** [comment]
In addition to "Documentation" and "Data", "Code" will now be presented as the 3rd default category.

**Comment by sbarbosadataverse** [comment]
Code has been added


![2vgg_yikk72wri1jwjxpejtmxwyvxppp6o_p8ciruim](https://cloud.githubusercontent.com/assets/8322346/6966240/85e6fe96-d925-11e4-8fc1-92ac5cd8283c.png)
