### ISSUE TITLE
Create Dataset: When restrict file on create, validation error on required field not displayed and dataset not created.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1654]
Create Dataset: When restrict file on create, validation error on required field not displayed and dataset not created.

1. Used geo metablock, made country required.
2. Create dataset, did not select geo country do not yet save.
3. Made file restricted, entered access terms, clicked add dataset. Nothing happens, green message about file being made restricted after saving.

**Comment by scolapasta** [comment]
The continue button was missing the proper updates for the page.

**Comment by kcondon** [comment]
Works now, closing.
