### ISSUE TITLE
Dataset Lock/File Ingest - Edit + Publish Buttons Not Displayed

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1658]
When you are uploading subsettable files, and returned the dataset page, the "Ingest in progress..." message is displayed, and the "Upload + Edit Files" is disabled. Unfortunately, the "Publish" and "Edit" buttons for your dataset are not displayed.

We should probably be disabling those as well, or have better messaging as to what is going on with the dataset lock, while ingest is in progress. Also, we need to review the use of the large lock icon next to the buttons on the Metadata and License + Terms tab.

![screen shot 2015-03-12 at 1 52 31 pm](https://cloud.githubusercontent.com/assets/687227/6624372/32264350-c8bf-11e4-90b3-58143304ed93.png)
![screen shot 2015-03-13 at 11 53 51 am](https://cloud.githubusercontent.com/assets/687227/6641963/9e28867c-c977-11e4-83a9-3850d6fdbae1.png)

**Comment by mheppler** [comment]
To be reviewed and discussed in the UI Review Part II with Merce.

**Comment by mheppler** [comment]
Removed large lock image from Metadata and License + Terms tabs on the Dataset page.

**Comment by sekmiller** [comment]
Edit and publish buttons will now display as disabled when dataset is locked.  Formerly they were hidden.

**Comment by sbarbosadataverse** [comment]
Edit and P"edit and upload" are "locked."
I don't see "publish" anywhere on here
and there is not message letting me know that tabular file upload is in process???


![0_ts85_j6cp6ms2ems6dlpalvyxr94uvqpyre7_trhk](https://cloud.githubusercontent.com/assets/8322346/6966322/3494e764-d926-11e4-898c-5f340e22cec1.png)

**Comment by kcondon** [comment]
This works as described: ingest in progress message is present, specified buttons are disabled. Sonia has opened a separate ticket about ingest in progress messaging that covers any gap in messaging. Closing.
