### ISSUE TITLE
Notifications: No need for notification when a dataverse is updated

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1659]
Currently, when a user goes in and clicks Save Changes on the General Information page for a dataverse, a notification is created. We don't need that. Only need a notification for when the dataverse is created.

**Comment by bencomp** [comment]
Have you considered notifications for changes in the Terms? If someone agrees to specific terms for depositing and downloading and these are changed, a notification would be useful. Maybe only for users who did not make the change?

**Comment by pdurbin** [comment]
> Have you considered notifications for changes in the Terms?

@bencomp is that different than #1650 (which you already gave a :+1: )? :)

**Comment by bencomp** [comment]
@pdurbin yes. Account Terms of Use are about the use of the system (the Dataverse instance) whereas Terms for Deposit are dataverse-specific (e.g. "you will not deposit political science data in this archaeology dataverse"). If these terms change (e.g. become more stringent) and this change makes my previous deposit violate the terms, I would want to get a notification. Or do I? Maybe if I plan to deposit in the same dataverse again?

I'm doubting. In the spirit of #1650, I would like to record what terms for deposit were in place when I deposited. Going off this issue's topic: setting deposit terms of use for a Dataverse appears impossible in the current beta. It is in v3.6. Setting terms of use for downloading in a template is a request: #1229. v3.6 allows these on network and dataverse level (see also #551). I guess templates for these make more sense than stacking (potentially contradictory) terms from all ancestor dataverses plus the terms in a dataset to know what you can do with data.

**Comment by eaquigley** [comment]
@bencomp & @pdurbin this notification and ticket relate to whenever something is changed on this page:

![generalinfopage](https://cloud.githubusercontent.com/assets/5922904/6639810/10b9a784-c969-11e4-9b0e-d129aadd38fe.jpg)

This isn't where a terms of use would be changed for a dataverse.

**Comment by sekmiller** [comment]
Notification will only happen for DV creation.  Prior multiple notifications are not removed.  Need to test on a go-forward basis.

**Comment by sekmiller** [comment]
Also the bundle has an entry 
notification.generic.objectDeleted=The item pertaining to this notification has been deleted

@eaquigley please modify as you see fit

**Comment by eaquigley** [comment]
@sekmiller thanks for fixing the notification when save changes is clicked on the general information page. i've also updated the object deleted notification in the bundle in commit: 87588f9

Passing to QA

**Comment by posixeleni** [comment]
This is working as expected. I can close this ticket. 

As a related aside: I had a question: @eaquigley: do we want to have a notification when someone publishes their Dataverse? Or do we only get notifications when someone publishes a Dataset?
