### ISSUE TITLE
Notifications: Add in Role Assignment Notifications

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1660]
need a notification created whenever someone assigns a role or grants access to a user in a dataverse or dataset (unpublished or published).

**Comment by sekmiller** [comment]
@eaquigley  What should the notification say?
Something like:
You have been added as a [Name of Role] to the [Link to DV/DS] Dataverse/Dataset

**Comment by sbarbosadataverse** [comment]
Kevin received the notification twice-should have received once.
I did but I got 2 notifications=bug!


You have been granted the Contributor/Dataverse + Dataset Creator role for Test CSV Ingest, Cust data do not use.July 16, 2015 3:40 PM EDT
You have been granted the Contributor/Dataverse + Dataset Creator role for Test CSV Ingest, Cust data do not use.July 16, 2015 3:40 PM EDT

**Comment by michaelsuo** [comment]
@sbarbosadataverse I'm having trouble reproducing. Was it one email with two messages, or two separate messages

**Comment by sbarbosadataverse** [comment]
@kcondon  good point @michaelsuo 
Kevin was it one email with two messages or two separate messages?

**Comment by sbarbosadataverse** [comment]
Better! Looks good. Thanks

**Comment by kcondon** [comment]
It was the online notification. The account you sent it to did not have a valid email address.
________________________________

**Comment by michaelsuo** [comment]
@sbarbosadataverse Ah, I see the confusion. @sekmiller authored the online notifications, I authored the email notifications

**Comment by kcondon** [comment]
Points out that I should have tested both though. Thanks!

________________________________

**Comment by kcondon** [comment]
@sbarbosadataverse So, we need to check both online and email notifications.

**Comment by kcondon** [comment]
OK, Sonia and Dwayne confirmed it was working, closing:
I did get an email when you granted me access at 3:19PM. Also within dvn-build there was a notification when access was granted.
 
I received no notification when access was revoked.

Closing
