### ISSUE TITLE
Dataset Deaccession - Cleanup UI Popups, Reason, etc.

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1670]
- [x] Move all popup text to bundle.
- [x] Add "http://..." watermark help text to URL field.
- [x] Add "warning" icon and text styling to confirmation popups.
- [x] Clean up buttons spacing on all popups.
- [x] Make "Deaccession" label red (danger), for the other label colors: "Draft" blue (primary), "Unpublished" orange (warning).
- [x] Improve layout of Deaccession Reason on dataset page.
- [x] Change citation background to red, rather than blue.
- [x] Hide "Download Citation" and "Link Dataset" buttons

Once these are reviewed, and completed, we should then apply the same improvements to the browse/search card for a deaccessioned dataset.

Related to #1221

**Comment by eaquigley** [comment]
@mheppler the deaccessioned dataset citation isn't appearing red in the search/browse cards. passing ticket back to you for that.

**Comment by mheppler** [comment]
Applied red deaccession-styled background color to the citation block on dataset browse/search cards. Removed green/success button color from deaccession Yes button in confirmation popup.

**Comment by eaquigley** [comment]
Showing as red now. Closing ticket.
