### ISSUE TITLE
File upload fails

### ISSUE THREAD

**Issue by AlexEngy** [IQSS/dataverse#1671]
I've tried to upload a test file of size ~2 Gb. At it silently fails - the upload finishes and nothing happens. (Small files can be uploaded without any problem).

**Comment by scolapasta** [comment]
@kcondon could you test this with a large file and see reproduce this behavior?

**Comment by scolapasta** [comment]
Actually @AlexEngy is this on the new Dataverse 4.0? (in on of our test environments?) or on 3.6 in production? if the latter, files > 2gb are not supported.

**Comment by AlexEngy** [comment]
Ok, it's 3.6.2. But I still think that it shouldn't just silently fail :)

Is there a way to migrate to 4.0? (I'm a new comer and just created http://thedata.harvard.edu/dvn/dv/idea)

**Comment by scolapasta** [comment]
Agreed 100% it shouldn't fail silently. However, our dev efforts at this point are all on 4.0 (and this issue tracker is for 4.0 issues).

Our scheduled release for 4.0 to production is the end of the month, at which point all of the data will be migrated over. Until then you can test the dataverse demo site at:
http://dataverse-demo.iq.harvard.edu/

Note that occasionally drop data from here and refresh to continue testing the code prior to production release.

**Comment by scolapasta** [comment]
I'm going to close this issue as it is not for 4.0. But feel free to open any issues you find while working with 4.0 and we will review them.
