### ISSUE TITLE
Search/Browse: Dataverse Cards Are Appearing Quite Small

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1673]
Not sure when this happened:

![smalldvcard](https://cloud.githubusercontent.com/assets/5922904/6646557/795b5db8-c99c-11e4-912c-d1d534e09f08.jpg)

**Comment by mheppler** [comment]
The dataverse/dataset/file browse/search card preview thumbnails W x H uniformity that is being sought with this request will need to be applied to the dataset page files datatable as well.

**Comment by mheppler** [comment]
Cleaned up dataverse browse/search card by improving text, giving uniform sizing to logo images. Also improved file icon size and restricted icons positioning in files table on dataset page.

**Comment by eaquigley** [comment]
Looks good. Closing ticket.
