### ISSUE TITLE
Create Dataset - Select Template, "clear default values"

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1674]
When you create a new dataset, and there is a default dataset template, there are values prepopulated in the metadata fields. If you start filling out metadata fields, but then realize you need to change the dataset template, you lose the metadata you've entered. Same if you select "No template - clear default values".
- Is there a way to retain the info you've entered, and change/remove templates?
- Can we replace "No template - clear defalut values" with a "Clear" or "Reset" button?
- If can implement the "Reset" button, and there is no default template, can we use the more common "Select..." text in the dropdown?

**Comment by mheppler** [comment]
To be reviewed and discussed in the UI Review Part II with Merce.

**Comment by mheppler** [comment]
Removed large lock image from Metadata and License + Terms tabs on the Dataset page.

**Comment by mcrosas** [comment]
To review with @scolapasta because it involves a developer. Also need more information from @eaquigley from usability feedback, and review what can be done for 4.0.
