### ISSUE TITLE
DataTable w/ Select Checkboxes - Tone Down Selection Background Color

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1675]
The vibrant blue table row background color is a little obnoxious.

- [x] dataset (Upload + Edit Files page)
- [x] permission-manage-files (Assign Users/Groups, View/Remove Users/Groups popups)

**Comment by mheppler** [comment]
Changed the selected background color for datatable rows w/ select checkboxes to a more pleasant yellow.

**Comment by posixeleni** [comment]
Seeing color change in Upload + Edit files page:
![image](https://cloud.githubusercontent.com/assets/5013837/6926221/d322196c-d7b2-11e4-877f-65d2565fefbb.png)

Also in Permissions Grant File Access
![image](https://cloud.githubusercontent.com/assets/5013837/6926281/3387fb46-d7b3-11e4-8d37-076ddbd6da6f.png)

Works as expected. Closing this ticket.
