### ISSUE TITLE
Include Access Information Metadata in Harvested Datasets 

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#1678]
This was discussed in our 3/5/15 migration meeting that we need to have access information text included for harvested datasets.

Example: ICPSR Datasets (files) can only be accessed by users who are part of their member institutions.

**Comment by landreev** [comment]
@posixeleni , 
This is the same screenshot I posted on the list. 
See how all the search cards of harvested objects have this access information note: "This Dataset is harvested from our partners at Statistics Canada, Canada's central statistical office. Clicking the link will take you directly to the archival source of the data."
I haven't been very creative with these notes; for the Odum datasets and files I have "... is harvested from our partners at the Odum Institute at the UNC ... " etc. 
If you have any input/recommendations as to what these access information entries should be saying for various harvested archives - here's Merce's spreadsheet of the harvested dataverses we need to migrate: 

https://docs.google.com/spreadsheets/d/1xE55jFE--sEDvvS-vtXavBxc8VvKvKpGJXcjfkelcAw/edit#gid=0

![screen shot 2015-04-01 at 5 31 37 pm](https://cloud.githubusercontent.com/assets/737558/6958231/fac3f7ae-d8d6-11e4-9931-f846688464b0.png)

**Comment by mheppler** [comment]
@landreev @posixeleni @eaquigley -- I would like to review these message, and clean them up. I would like to bump those messages down a few pixels in font size. Maybe throw in an "info" icon too. Please pass me this ticket when you're done.

**Comment by scolapasta** [comment]
This text is stored in the db. so code wise is all set. Passing to @mheppler to clean up the UI. 

If the text should change, please let @landreev know and he can adjust the script where he sets it. (we can always set it directly in db, even post release)

**Comment by mheppler** [comment]
Fixed display of harvested dataset message on the browse/search cards. My only suggestion for @landreev to change in the text to make "Dataset" lowercase. @eaquigley might have other suggestions.

![screen shot 2015-04-02 at 5 38 00 pm](https://cloud.githubusercontent.com/assets/687227/6974266/5407fab2-d95f-11e4-8751-dd58d3e24081.png)
