### ISSUE TITLE
Advanced Search on dataverse subject

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#1681]
In #1452 the "subject" of a dataverse was changed to be populated by dataset subjects. That ticket went through QA but as I work on #1314 I'm questioning if one can still use Advanced Search to find dataverses based on the "subject" checkboxes. I'm having trouble with this in dev anyway. Passing this @scolapasta for review.

Please note that #1428 is still open and related but it has more to do with an ampersand (&) being in the subject.

**Comment by scolapasta** [comment]
I tested on dvn-build and it worked.

**Comment by pdurbin** [comment]
@scolapasta well, it's not working the way I expect.

'dvSubject_en:"Arts and Humanities"' is matching both "Arts and Humanities" and "Astronomy and Astrophysics":

![root_dataverse_-_2015-03-17_08 12 12](https://cloud.githubusercontent.com/assets/21006/6687068/a6e85856-cc7d-11e4-9333-329828106051.png)

But maybe that's because that dataverse has both? I guess we're relying entirely on Solr to display the subjects properly in the UI. Maybe when looking at "general information" for a dataverse we should show (read only) which subjects the dataverse contains.

From a search perspective, I think I need to change this from `text_en` to `string' (Solr types) for an exact match. Perhaps all checkboxes on Advanced Search should be backed by a Solr `string` type. Let me think some more about this.

**Comment by pdurbin** [comment]
In SearchFields.java if I rename "dvSubject_en" to a Solr field name that is non-dynamic and to an "index all" Solr does not complain that the field doesn't exist. It's as if dataverse.getDataverseSubjects() never returns anything.

**Comment by pdurbin** [comment]
@scolapasta explained that I had to publish a dataverse before dataverse.getDataverseSubjects() will return anything.

I change the Solr field type to string since it's better for faceting as part of 90f3e73

Passing to QA. I would recommend testing this ticket and #1428 at the same time.

**Comment by posixeleni** [comment]
Works as expected and also tested #1428 :

![image](https://cloud.githubusercontent.com/assets/5013837/6757610/ba1e85b6-cf08-11e4-84be-60932d77ffb3.png)

Closing.
