### ISSUE TITLE
Citation for subset download

### ISSUE THREAD

**Issue by mercecrosas** [IQSS/dataverse#1683]
When a user downloads a subset of a tabular file,  the citation for the subset should be included.

**Comment by eaquigley** [comment]
@vjdorazio can you let us know if the subset for a citation is happening with TwoRavens?

**Comment by vjdorazio** [comment]
The subset for a citation is not happening with TwoRavens. I'll open a ticket for that.

--Vito

________________________________

**Comment by mcrosas** [comment]
@vjdorazio and @landreev but, isn't it now part of the "Subset" of variables functionality? That is, when you download a subset of the tabular files, do you also get the citation for that subset?

**Comment by eaquigley** [comment]
I went to dataverse.harvard.edu to see if the citation for the subset is part of what a user receives when they download a subset and two things 1) TwoRavens isn't working on Chrome (nothing appears in the pop up when I click Explore or Subset in the download dropdown) 2) when I went to Firefox (which the variables did populate in the Subset pop up), when I selected several variables and clicked Download, what shows in the image below happened: 

![screen shot 2015-08-10 at 10 06 20 am](https://cloud.githubusercontent.com/assets/5922904/9173326/784034a0-3f47-11e5-9de9-cfe879a572ec.png)

So I am not able to test and see if the citation for a subset is happening.

cc: @mcrosas @kcondon @vjdorazio @landreev @tercer

**Comment by djbrooke** [comment]
I'll close this. We removed subsetting from the application (https://github.com/IQSS/dataverse/pull/6098).
