### ISSUE TITLE
File Icons Display Issue in Demo

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#1687]
@eaquigley and I found this while showing a demo of 4.0 to CfA yesterday on the demo site.

Liz uploaded a zip file and when it was done unpacking and ingesting the files, the icons appeared much smaller than they normally do next to each file: https://dataverse-demo.iq.harvard.edu/dataset.xhtml?globalId=doi:10.5072/FK2/BEEIDE

![image](https://cloud.githubusercontent.com/assets/5013837/6690365/98ad6b50-cc96-11e4-82ea-0e6ae3951682.png)

I tried uploading non-zip files as well and am seeing the same issue where the icons appear much smaller than expected. 

As far as timing, this issue popped up only after the HTML in the description was fixed yesterday.

@mheppler, @sekmiller  do you know what this issue is?

**Comment by mheppler** [comment]
This was a result of this week's decision to push dataset.xhtml to demo, and not pushing the structure.css along with it. Progress had been checked in 208611b0e2b39baa846dae2e64ad5d680407be98 on the dataset pg, related to ticket #1673. Without the CSS, the icons weren't sized properly. When the CSS gets moved to demo in the next build, this won't be an issue.

**Comment by posixeleni** [comment]
Confirmed that this is working correctly in build which has the latest code. Closing.
