### ISSUE TITLE
File Download: Download term of access popup now has a third button, validation.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1688]
The third button always allows downloading, regardless of accepting terms. This seems like a developer's debug code was checked in by mistake.

**Comment by sekmiller** [comment]
button already removed from build

**Comment by sbarbosadataverse** [comment]
Need a note in "Terms of use" that specifies "download" terms of use, just like we did with "Account" terms of use.

I don't see any other third button options. I don't see a "terms of use"  popup describing the field--not sure one is expected?


![sotjfdh_oz_c6laub0n81n6-zeeqrmbisjpqrwaucqk](https://cloud.githubusercontent.com/assets/8322346/6759537/196c284e-cf17-11e4-89dc-cebcc49f2bc0.png)

**Comment by sekmiller** [comment]
The remaining issue her is that Sonia asked that the Label "Terms of Use" and "Terms of Access" are updated to say "Download Terms...." @eaquigley is this worth doing at this point?

**Comment by eaquigley** [comment]
@sekmiller leave as is. based off feedback from Berkman, the Account Terms of Use are now labeled as General Terms of Use.

**Comment by sekmiller** [comment]
OK - There is still a known issue that there isn't an inline error message for a required "multiple choice" question, however the blanket error should show at the top of the pop-up

**Comment by posixeleni** [comment]
Third button is no longer present. Works as expected. Closing.
