### ISSUE TITLE
Dataset + File Metrics - Downloads, Views, Shares, Citations

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1689]
Add counting metrics like Downloads (Beta 15), Views (post 4.0), Shares (post 4.0?), Citations (post 4.0) to the top of the ~~dataverse~~ and dataset page.

Also need to add "Download + Analysis" count to individual files in the file table on the dataset page.

**Comment by eaquigley** [comment]
Download Counts are:
- [ ] File Level (how many times a file has been downloaded)
- [ ] Dataset Level (how many times all the files in the dataset have been downloaded)
- [ ] Dataverse Level (how many times all the files in all the datasets have been downloaded)

**Comment by mheppler** [comment]
Added placeholder Metrics block to the top of dataverse and dataset pages.

**Comment by mheppler** [comment]
Going to change how the Metrics are displayed, so that labels can be inside of each block, rather than in tooltips, by utilizing a horizontal accordion technique through Bootstrap.

![screen shot 2015-03-24 at 10 56 02 am](https://cloud.githubusercontent.com/assets/687227/6804541/a79f71e8-d214-11e4-961e-3cee0281ef8b.png)

Demo: http://jsfiddle.net/fauzi/q9GLR/20/show/light/
Ref: http://stackoverflow.com/questions/18993202/bootstrap-3-0-collapse-horizontally

**Comment by scolapasta** [comment]
added dataset download counts - need to discuss if we will have dataverse counts a) at all and b) for 4.0 with @mcrosas.

**Comment by mheppler** [comment]
Revamped Metrics block to work on hover. Removed Metrics block from dataverse page.

Taking this ticket back, assuming the discussion on dataverses has happened for 4.0, and that another ticket can be created for "In Review - 4.0.x" for that functionality. (And, done #1808.)

**Comment by mheppler** [comment]
Finalized styling and functionality of the metrics block, and hover feature.

Had to change it to a simpler hover/fade functionality, based on the tab Bootstrap and jQuery component.

**Comment by eaquigley** [comment]
Looks really good. tried downloading a few files and saw the download count go up (goes up upon refreshing the page)
