### ISSUE TITLE
License + Terms Tab - Improve Messaging, Fix Rendering

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1690]
- [x] CC0 + logo should be together, one line.
- [x] “Community Norms” text should always display.
- [x] When no restricted files, remove Request Access.
- [x] Terms of Use, Terms of Access is displayed when empty.
- [x] Guestbook better text than "No Guestbook selected." for end user... "There is no guestbook assigned to this dataset, you will not be prompted to provide any information on file download."
- [ ] ~~Guestbook better text than "No Guestbook selected." for admin (has guestbooks)... "There is no guestbook assigned to this dataset."~~ (Not doing this. There is so much render logic on this page, that an admin will see the same message above as the end users.)
- [x] Guestbook better text than "No Guestbook selected." for admin (no guestbooks)... "There are no guestbooks available in {dataverse.name} Dataverse to assign to this dataset."
- [x] Fix labels on Guestbook so there aren't two "Guestbook" labels.
- [x] Instead of "Guestbook may be applied to files to get information from users who download them.", have help text, "Select a guestbook to have a user provide additional information when downloading a file."
- [x] Instead of "No Available Custom Guestbooks", have help text, "There are no guestbooks enabled in {dataverse.name} Dataverse, to create a guestbook, return to {dataverse.name} Dataverse, click "Edit" button and select the "Dataset Guestbooks" option."
- [x] Remove "Available Custom Guestbooks"
- [x] Fix width of radio button column.
- [x] Change "View" button to "Preview Guestbook".
- [x] Remove grey "help-block" styling of text (CC0 - "Public Domain License", "There are 0 restricted files...", etc.), unless it actually is help text.

Following may need additional help text revisions:
- [x] Instead of "Custom Guestbook In Use: {Name}", have help text, "The following guestbook will prompt a user to provide additional information when downloading a file.", then a table-looking-block with the guestbook name and View button, right justified, to mimic the edit view.

**Comment by mheppler** [comment]
That should be everything. I tried to be as detailed as possible in what I did, with the check list above. Please review that new help text message I added, and the grey help-block styling of the messaging vs. the black plain-text styling of the values. Let me know if I missed anything or should improve anything.

**Comment by eaquigley** [comment]
All of this looks good. Closing ticket.
