### ISSUE TITLE
Dataverse + Dataset Description - Help Text

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1692]
- [x] Fields won’t have HTML validation, add help text "suggesting" what HTML can be used.

Related to #1320

**Comment by mheppler** [comment]
Found a sample of "safe, whitelisted" HTML tags that we can use as a starting point.

http://meta.stackexchange.com/questions/1777/what-html-tags-are-allowed-on-stack-exchange-sites

````
<a>              - hyperlink.
<b>              - bold, use as last resort <h1>-<h3>, <em>, and <strong> are 
                   preferred.
<blockquote>     - specifies a section that is quoted from another source.
<code>           - defines a piece of computer code.
<del>            - delete, used to indicate modifications.
<dd>             - describes the item in a <dl> description list.
<dl>             - description list.
<dt>             - title of an item in a <dl> description list.
<em>             - emphasized.
<h1>, <h2>, <h3> - headings.
<i>              - italic.
<img>            - specifies an image tag.
<kbd>            - represents user input (usually keyboard input).
<li>             - list item in an ordered list <ol> or an unordered list <ul>.
<ol>             - ordered list.
<p>              - paragraph.
<pre>            - pre-element displayed in a fixed width font and and 
                   unchanged line breaks.
<s>              - strikethrough.
<sup>            - superscript text appears 1/2 character above the baseline 
                   used for footnotes and other formatting.
<sub>            - subscript appears 1/2 character below the baseline.
<strong>         - defines important text.
<strike>         - strikethrough is deprecated, use <del> instead.
<ul>             - unordered list.
<br>             - line break.
<hr>             - defines a thematic change in the content, usually via a 
                   horizontal line.
````

**Comment by pdurbin** [comment]
@mheppler that's a good whitelist of HTML tags. You could also compare it to the list at https://github.com/github/markup as I mentioned at https://github.com/IQSS/dataverse/issues/1320#issuecomment-72076214 . Here it is:

h1 h2 h3 h4 h5 h6 h7 h8 br b i strong em a pre code img tt div ins del sup sub p ol ul table thead tbody tfoot blockquote dl dt dd kbd q samp var hr ruby rt rp li tr td th s strike summary details

Of course, GitHub let's people write in Markdown. So what they're limiting is which HTML tags you can use within your Markdown.

**Comment by mheppler** [comment]
Added help text message, popover and allowed HTML tags list to be displayed on dataverse and dataset pages.

I went with the original list I posted, because it seemed more like a "limit", where the markdown list that also suggested allowed a lot more, like div, table, etc. Since this is a "false message", I guess it doesn't matter what we list. Passing to QA to review.

**Comment by eaquigley** [comment]
Updated text. @mheppler could you please change the HTML Tags pop up that appears, to appear on hover like the tool tips do.

**Comment by mheppler** [comment]
This popover is now broken locally and on dvn-build. No message is being delivered to what is now an empty popover container.

![screen shot 2015-03-27 at 6 17 05 pm](https://cloud.githubusercontent.com/assets/687227/6878007/8705db98-d4ad-11e4-835b-b96444c2a446.png)

**Comment by mheppler** [comment]
Fixed broken popover on dataverse and dataset Description fields in edit view. Changed trigger to hover.

**Comment by eaquigley** [comment]
Woooo hover works like a dream! Closing ticket.
