### ISSUE TITLE
Dataset "Persistent Identifier" for Citation Metadata - Index, Add Citation Block and Advanced Search

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1694]
- [x] Need to index DOI/Global ID/”Persistent Identifier” for dataset.
- [x] Add DOI/Global ID/”Persistent Identifier” to Citation Metadata block on dataset page.
- [x] Also add Publication Date to Citation Metadata block.
- [ ] ~~Figure out how to display both on Edit Dataset form. (Discuss with Merce, UI Team)~~
- [x] Tooltips needed for ”Persistent Identifier” label.
- [x] Advanced Search pg, move those two inputs into Dataset: Citation Metadata block.

**Comment by pdurbin** [comment]
@posixeleni I'm passing this to you to review the label and tooltip @mcrosas and I came up with in 4383be4

Then, can you please pass this to @mheppler ?

I'm aware that you can't search on a full DOI such as "doi:10.5072/FK2/4QEJQV" because the colon is a problem and gives "Search Syntax Error: undefined field doi". I'm going to work on that in #1720

**Comment by posixeleni** [comment]
@pdurbin I assume you are referring to how this field would look in the UI in Advance Search.

Following how we labelled it in 3.6 we can:
- Label it: **Dataset Global ID**
- Tooltip: The unique global identifier for a Dataset, which can be a Handle or DOI in Dataverse.

Assigning this to @mheppler to add this language in the UI

**Comment by pdurbin** [comment]
@posixeleni yes, you can see it at https://dvn-build.hmdc.harvard.edu/dataverse/root/search

Hmm, I named the field in Solr "datasetPersistentIdentifier" so if we go with "Dataset Global ID" in the UI I should rename the Solr field to "datasetGlobalId". @mheppler if you would prefer that I change this now, please pass the ticket to me. Later is fine too. It will require a schema.xml change.

**Comment by mcrosas** [comment]
@posixeleni is this important olr necessary? "Persistent ID" is not more
commonly used elsewhere than "global"


Mercè Crosas, Ph.D.
Director of Data Science, IQSS
Harvard University
http://datascience.iq.harvard.edu

**Comment by posixeleni** [comment]
@pdurbin @mheppler : after speaking with @mcrosas we decided on the following:

Label it: Dataset Persistent ID
Tooltip: The unique persistent identifier for a Dataset, which can be a Handle or DOI in Dataverse.

**Comment by mheppler** [comment]
Cleaned up display of Publication Date and Dataset Persistent ID on Advance Search page. Added them to Dataset page.

Need @sekmiller to clean up the Publication Date that gets displayed on Dataset page. It is looking like "2015-03-18 15:19:19.886 ", currently. Need to confirm with @mcrosas if we want just the year, or the full date "YYYY-MM-DD".

**Comment by posixeleni** [comment]
@mcrosas @mheppler since in the Data Citation we just show the year wouldnt we want to just show the year YYYY for Publication Date?

**Comment by mcrosas** [comment]
In the metadata tab (dataset page) we can allow more detailed information
than in the "citation" itself (which is a condensed summary). So, I think
we should show there "YYYY-MM-DD"

**Comment by sekmiller** [comment]
Metadata display updated to show publication date as YYYY-MM-DD.  A new build is required before this can be tested...

**Comment by posixeleni** [comment]
@kcondon: would you by any chance be able to run a new build for me to test this?

Thanks!

**Comment by posixeleni** [comment]
Works as expected:

In the Dataset
![image](https://cloud.githubusercontent.com/assets/5013837/6753717/8db6e55a-ceee-11e4-9029-83ec2f984125.png)

In Advanced Search:
![image](https://cloud.githubusercontent.com/assets/5013837/6753696/4b55aab6-ceee-11e4-9933-d9845408f43b.png) 

Although @mcrosas @eaquigley is it ok that persistent ID and Publication Date are pushed to the very bottom of the Dataset Citation in both Advance Search and View Dataset Metadata? I imagine these might get missed.

**Comment by pdurbin** [comment]
Re-opening to follow up on something I said earlier in this ticket.

> I named the field in Solr "datasetPersistentIdentifier"

"datasetPersistentIdentifier:doi:10.5072/FK2/JB5HPN" is what appears in the basic search box you click "Find" on Advanced Search.

Do we want to change this to "datasetPersistentId:doi:10.5072/FK2/JB5HPN"? That way, the Solr field would match the GUI.

**Comment by posixeleni** [comment]
@pdurbin if thats easy to fix then by all means make it match how it displays in the UI. I didnt realize this would be an issue since the field names in solr and the UI are very similar and someone would be able to easily infer that they are the same thing.

**Comment by pdurbin** [comment]
@posixeleni it's an easy change for me so I'll do it as soon as the master branch is stable. It will require everyone to update their Solr schema.

**Comment by pdurbin** [comment]
Ok, I decided to go with "dsPersistentId" to be consistent with other Solr fields such as "dsPublicationDate". This will require a change to the Solr schema. Moving to QA.

(Along these lines of consistency, I wonder about the Solr field "dsDescriptionValue" vs. the Advanced Search label that says "Description Text". I'd be curious to heard what @posixeleni or @eaquigley or @mheppler think about this. If you want I could change the Solr field to be "dsDescriptionText").

**Comment by sbarbosadataverse** [comment]
all fields accounted for:

![uej2tb29vhxdpqjp6qa5w3mvcr7ixg9fcyof1uyxmhe](https://cloud.githubusercontent.com/assets/8322346/6984946/147cdd52-d9fc-11e4-9d74-58dd906839c5.png)
