### ISSUE TITLE
Dataset Contributor - Hide Return to Author Button

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1695]
- [x] After admin confirms “Return to Author” on the popup, hide the button on dataset pg.

(Specifically only occurs on Draft version-only datasets, until #1707 is fixed.)

**Comment by eaquigley** [comment]
Return to Author button is going away. Passing to @kcondon to determine if he wants to test as well.

**Comment by posixeleni** [comment]
Works as expected. Closing this ticket.
