### ISSUE TITLE
Dataset - Upload + Edit Files Help Text on File Support

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1697]
- [x] On Upload + Edit Files, add info text, with link to User Guide about file support (/guides/user/dataset-management.html#file-handling-and-uploading).

**Comment by mheppler** [comment]
Added help text to file upload widget in the Upload + Edit Files view on the dataset page.

The help text is a placeholder to determine what needs to be specified in this message with @mcrosas. Passing to @eaquigley to determine and edit the bundle property "file.selectToAdd.tip".

**Comment by eaquigley** [comment]
Updated text in the bundle in commit 067ca91. Passing to QA to verify.

**Comment by posixeleni** [comment]
This help text with link to guides is showing up on the File Upload and Handling page of a dataset. Closing.
