### ISSUE TITLE
Dataset - Save Changes/Continue (Delete Files) Scroll To See Messages

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1698]
- [x] Success msg for deleting files in the Upload + Edit Files view, displayed at top of page, and isn’t visible when the page stays on the files table.
- [x] Fix dataset Save Changes scrolling, so that it doesn't jump the page to the top, when you're still on the edit view, unless there is a validation error to display.

Related to #1865.

**Comment by mheppler** [comment]
Fixed the "scrollTo" functionality for displaying validation errors on dataset to only display on error, and delete file success, messages. Applied fix to dataverse and dataset template pages as well.

**Comment by mheppler** [comment]
Bug reported in Chrome #1881. Can't create dataset in Chrome. Page just refreshes. No message. No error logged.

**Comment by pdurbin** [comment]
#1881 opened by @posixeleni and confirmed by @sbarbosadataverse describes what I just observed about not being able to create or edit a dataset in Chrome but since this is the open ticket I'll comment here.

Nothing is logged to the Glassfish log but in the Chrome Javascript console I see this:

`Uncaught SyntaxError: Unexpected token ; dataset.xhtml?ownerId=3:548`

This was on build 1011 on dvn-build.

**Comment by mheppler** [comment]
@pdurbin -- Yup. Can't have an ";" in javascript function of the onerror attribute of the f:ajax tag, that I was using on the hidden Save Changes commandButton. In fact, you don't need the "()" either. Unfortunately, you remove those, and it no longers works in Firefox, or anywhere for that matter. Need to have @scolapasta review the use of the hidden Save Changes commandButton to determine if a Terms of Access popup is needed or not. Here is the offend code, as it looks currently in GitHub.
````
<!-- Create/Save Dataset Button Panel -->
<div class="button-block" jsf:rendered="#{!empty DatasetPage.editMode}">
     <p:commandButton tabindex="1000" id="save" value="#{DatasetPage.editMode == 'CREATE' ? bundle['file.addBtn'] : bundle.saveChanges}" onclick="checkNewlyRestricted();" />
     <p:commandButton tabindex="1000" id="cancel" value="#{bundle.cancel}" action="#{DatasetPage.cancel}" process="@this" update="@form" rendered="#{DatasetPage.editMode != 'CREATE'}" oncomplete="javascript:post_cancel_edit_files_or_metadata()">
          <f:setPropertyActionListener target="#{DatasetPage.selectedTabIndex}" value="#{DatasetPage.editMode == 'METADATA' ? 1 : DatasetPage.selectedTabIndex}"/>
     </p:commandButton>
     <p:button id="cancelCreate" value="#{bundle.cancel}" outcome="/dataverse.xhtml?alias=#{DatasetPage.dataset.owner.alias}" rendered="#{DatasetPage.editMode == 'CREATE'}" />
     <p:commandButton value="Direct" id="datasetSave"
          style="display:none"
          update=":datasetForm,:messagePanel"
          oncomplete="javascript:bind_bsui_components();"
          action="#{DatasetPage.save}">
                    <f:ajax onerror="window.scrollTo(0, 0);" />
     </p:commandButton>
</div>
<!-- END: Create/Save Dataset Button Panel -->
````

**Comment by raprasad** [comment]
error seen in firebug and chrome (but firebug keeps going):
```
SyntaxError: missing } after property list
...indow.scrollTo(0, 0);});PrimeFaces.ab({source:'datasetForm:datasetSave',update:
```
	
related: http://forum.primefaces.org/viewtopic.php?f=3&t=1872
http://stackoverflow.com/questions/26912246/syntaxerror-missing-using-primefaces-extensions-inputnumber-using-jquery

**Comment by mheppler** [comment]
This will need to be moved to another milestone, to review further. I have reopened #1881 and sent that to QA, to confirm that Chrome bug that this fix created is fixed.

The problem that remains with dataset is as follows:

- Create new dataset, fill out a bunch of metadata fields, click "Save Changes" at the bottom of the page.
- The browser viewport jumps up to the top of the page, where you see the spinner turning, and you're still in "EDIT" mode, with a blue block of help text.
- The spinner disappears, and you're still looking at the "EDIT" view of the page, wondering if something is broken.
- The page refreshes and you're on the dataset in "VIEW" mode, with a success message.

**Comment by eaquigley** [comment]
@mheppler I'm going through some older issues and came across this one. The workflow you describe in the last comment is no longer happening because
1) That blue box of text has been moved to the bottom of the create dataset page
2) The page grays out while the spinner is going

I'm thinking this issue can be closed since modifications were done in other tickets and this is not behaving the same way anymore. Agree or disagree?

**Comment by mheppler** [comment]
@eaquigley -- I concur. With the addition of the blockUI PrimeFaces component (#2566), the scrollTo functionality is far less jarring and prohibits the user from impatiently clicking around on form buttons.

@scolapasta @kcondon -- closing.
