### ISSUE TITLE
Guestbook - Manage Table, View Popup UI Cleanup

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1702]
- [x] Add styled container block for default text when no guestbooks exist.
- [x] Review Accept/Submit label for button on Download File popup, rendered whether it has a Guestbook or Terms of Use.
- [x] Cleanup spacing of action buttons in manage table.
- [x] Review layout cleanup of data collected popup. (Changed to new page layout  #1730)

**Comment by mheppler** [comment]
Cleaned up guestbook workflow, change guestbook-responses to a dataTable layout.

Passing to @sekmiller to look into displaying the custom questions in the dataTable, using p:columns, that doesn't seem to be working, potentially because of the additional back end work needed (ref: http://stackoverflow.com/questions/18867345/how-to-display-variable-number-of-columns-in-primefaces-datatable).

Pass to @eaquigley when done, unless you need more UI cleanup. She needs to review the "Accept" vs. "Submit" button issue and decide if that is something worth fixing, and what needs to display, and when.

**Comment by eaquigley** [comment]
@mheppler definitely think this button should say submit not accept but i can't find the button text in the bundle.

**Comment by sekmiller** [comment]
It’s called acceptTerms.  I can take care of it.


On Mar 30, 2015, at 1:04 PM, Elizabeth Quigley <notifications@github.com<mailto:notifications@github.com>> wrote:


@mheppler<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mheppler&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=uc0dhVjtnKfIQDl5-G4MT4YxctZgHjeEQ0TBWfoSJsE&s=QURnGNtu_MK1Ih9lJm2Jc1vrPGcKWSyh3g902lbNIOw&e=> definitely think this button should say submit not accept but i can't find the button text in the bundle.

**Comment by mheppler** [comment]
Looks like @sekmiller got to this -- thank you, sir. d6c4b821b192f6911db2b60548a3a5efc687828f

**Comment by eaquigley** [comment]
Button now says Accept. Looks good. Closing ticket.
