### ISSUE TITLE
Account Information API Token - Return to Account Pg?

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1706]
- [ ] The API Token page needs a "Done" button to return to Account Information page.

**Comment by pdurbin** [comment]
As of 0e08dca in pull request #3025 the API Token page has been changed from a separate page to tab so I think this issue no longer applies. I'm moving it to QA for 4.4, which is the release we hope to merge that pull request into.

**Comment by kcondon** [comment]
Page is now a tab, closing.
