### ISSUE TITLE
Dataset Version - Form Actions Return To Wrong Version

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1707]
There has been a few actions I've noticed that don't return the user back to the draft version of the dataset, where the action originated from, but to the most recently published version.

Here is a running list of actions:

- [x] Upload + Edit Files, Cancel
- [x] Edit Metadata, Cancel
- [x] Edit License + Terms, Cancel (these three workflows share the same button at bottom)
- [x] Submit for Review
- [x] Return to Author

These pages do seem to return you to the current draft version:

- Upload + Edit Files, Save
- Edit Metadata, Save
- Edit License + Terms, Save (these three workflows share the same button at bottom)
- Edit License + Terms

**Comment by mheppler** [comment]
@scolapasta @sekmiller @eaquigley  -- this is by no means a show stopper, but it's pretty annoying and would be confusing to users ("where are my edit/publish buttons?!).

**Comment by mheppler** [comment]
Related to #1733.

**Comment by sekmiller** [comment]
Fix has been checked in. New Build required for testing. 03-20 10AM

**Comment by mheppler** [comment]
@kcondon -- I have checked in a fix for #1733 and @eaquigley has that ticket to QA. Please discuss these two tickets together, as I have reviewed them with her. They should be QA'd together, to make sure that we have the correct landing pages, as expected by a user, for all workflows.

**Comment by eaquigley** [comment]
Tested this and it is working as explained above. Passing to @kcondon to see if he wants to take a look as well before this ticket is closed.

**Comment by posixeleni** [comment]
Returns to Draft for:
- Upload + Edit Files, Cancel
- Edit Metadata, Cancel
- Edit License + Terms, Cancel (these three workflows share the same button at bottom)

Still unable to test:
 Submit for Review
 Return to Author

**Comment by kcondon** [comment]
@posixeleni Return to Author is going away: https://github.com/IQSS/dataverse/issues/1695
What is the trouble with Submit for Review?

**Comment by posixeleni** [comment]
@kcondon I thought I was unable to because of this bug #1803

But after our discussion I will try just putting in the URL to "Add a Dataset" to see if it will let me test.

**Comment by posixeleni** [comment]
All workflows listed in this ticket are working as expected where they go back to right version (tested with Draft). Closing.
