### ISSUE TITLE
File Download: R data file is downloaded without extension when original file is downloaded.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1708]
I uploaded file t1.RData and downloaded original R file but was saved as only t1.

In v3.6.2, we did not allow files without the .RData extension to be ingested, though there was some question about whether this was the most commonly used extension.

**Comment by landreev** [comment]
Please retest (as of next build).

**Comment by posixeleni** [comment]
RData file now has the extension included when you download the original file. Works as expected. Closing.
