### ISSUE TITLE
Metadata Updates for Beta 15

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#1709]
Checking in minor metadata updates to fix validation errors found in migration and make sure that we get in any final tweaks before 4.0 is released. According to @pdurbin suggestion these are checked into a branch metadata-beta-15 to make sure the schema.xml can be properly updated and once this is moved to master it would also need a db drop in build.

**citation.tsv**
- Under controlled vocabulary added arxiv as an alternate spelling of the publicationType. @scolapasta  had showed me an error log where certain records were being thrown out due to case-sensitivity since we only accepted ones with "arXiv" as a publication type rather than also "arxiv"
![image](https://cloud.githubusercontent.com/assets/5013837/6710692/b384a89a-cd58-11e4-9849-5c04044fa832.png)
- In Subject controlled vocabulary changed "Medicine, Health **&** Life Sciences" to "Medicine, Health **and** Life Sciences" for consistency across this controlled vocabulary
- seriesInformation changed to fieldType textbox

**social_science.tsv** [updated w/ feedback from @eaquigley]
- Changed the following fieldTypes to textbox: collectionMode, dataCollectionSituation (Characteristics of the Data Collection), weighting, responseRate

**customGSD.tsv**
- Added to gsdCoordinator controlled vocabulary: Long, Judith Grant; Idenburg, Florian; 
- Added to gsdFacultyName controlled vocabulary: Etzler, Danielle

**journal.tsv**
- made volume and issue a compound field to be able to eventually (post 4.0) hierarchically browse by volume and issue together.
- added new publication date child to compound field

**Comment by posixeleni** [comment]
@eaquigley has some additional minor fixes for the metadata blocks that she will be sending me shortly.

**Comment by posixeleni** [comment]
Added in changes to metadata in metadata-beta-15 branch for @pdurbin  to do schema.xml 

A db drop will be needed as well to test in build.

**Comment by pdurbin** [comment]
These changes did not require an update to the Solr schema.xml. Passing to QA. Please note above that @posixeleni recommends a database drop.

**Comment by posixeleni** [comment]
@kcondon like @pdurbin mentions below this will need a db drop for the changes to display for QA.

**Comment by posixeleni** [comment]
WIll need to fix the journals.tsv file so that the new compound field shows properly.

**Comment by posixeleni** [comment]
@pdurbin please check if this new journals.tsv commit will need a schema.xml change. I added a new field Publication Date and created a compound field called Journal (which has Volume, Issue, Publication Date as children).

**Comment by pdurbin** [comment]
@posixeleni this is going to sound crazy but I can't find your commits in any branch, such as your latest one:

```
$ git branch -r --contains 25cf69beb2a341e5a11f9010079c962f5fef9b85
error: no such commit 25cf69beb2a341e5a11f9010079c962f5fef9b85
```

Can you find it under https://github.com/IQSS/dataverse/branches ?

**Comment by pdurbin** [comment]
Instead of seeing "branch:whatever" I'm seeing "tree:25cf69beb2" here:

https://github.com/IQSS/dataverse/blob/25cf69beb2a341e5a11f9010079c962f5fef9b85/scripts/api/data/metadatablocks/journals.tsv

I assume this the version we want ( @posixeleni can you please confirm?) though I'm not sure why it isn't in any branch.

**Comment by posixeleni** [comment]
@pdurbin Re-checked this into a new branch

**Comment by pdurbin** [comment]
I generated a new Solr schema and pushed it to master. Passing to QA.

**Comment by sbarbosadataverse** [comment]
NOT DONE:

customGSD.tsv
    Added to gsdCoordinator controlled vocabulary: Idenburg, Florian;

**Comment by posixeleni** [comment]
@kcondon we need a db drop for this controlled vocabulary field to show. I had checked this in earlier in the week.

**Comment by sbarbosadataverse** [comment]
all set!
