### ISSUE TITLE
Advanced Search: Populated Subject Field with Dataset Subjects

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1710]
Mentioned during a CfA demo that it would great if Astronomy and Astrophysics was already selected in the subject box on the advanced search page.

**Comment by pdurbin** [comment]
There are actually two subject boxes on the Advanced Search page (screenshot below), one for collections and one for datasets. I guess both would be checked?

But why? The search is already narrow to the CfA collection and all the content within it. If there's weird non-astronomy stuff found in the search maybe it should be moved to some other collection.

Does this issue have a champion?

<img width="1039" alt="Screen Shot 2022-10-05 at 9 12 18 PM" src="https://user-images.githubusercontent.com/21006/194192118-63ab4e86-31cf-4a30-a3fe-81f883a1b949.png">
