### ISSUE TITLE
Breadcrumbs: For Account Pages

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1711]
Need to add in breadcrumbs for the account page. 

Example: Harvard Dataverse > [insert user name] Account

**Comment by mcrosas** [comment]
To review with @scolapasta  if it can be done for 4.0

**Comment by mheppler** [comment]
Added breadcrumbs to the Account page. Cleaned up the spacing in the dataverse_header. Moved inline CSS to stylesheet.

**Comment by eaquigley** [comment]
Looks good. Closing ticket.
