### ISSUE TITLE
Dataset - Register Dataset Button

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1715]
- [x] It has been discussed that removing this button from the UI is OK.

**Comment by mheppler** [comment]
Register button removed. Merce was OK with the DOI being registered again on publish.

**Comment by posixeleni** [comment]
@mheppler any advice on how I can test if this is now working/looking as expected in build?

**Comment by mheppler** [comment]
Nope. @kcondon ? @sekmiller ? @scolapasta ? All I did was remove the button from the dataset page. Not sure how to best orchestrate a test scenario to display it is being handled properly on publish.

**Comment by posixeleni** [comment]
thanks @mheppler I was assuming we would need to orchestrate some way to make it so that a dataset did not register a DOI when it was first created to see if the button shows up. @sekmiller @kcondon @scolapasta please help!

**Comment by posixeleni** [comment]
Assigning to @kcondon to confirm that this is working as expected.

**Comment by mheppler** [comment]
The button made a mysterious and miraculous return back to the dataset.xhtml code. I have removed it again. Hopefully this allows it to be properly tested. Good luck.

**Comment by kcondon** [comment]
Register button is gone but so is publish button. It makes sense that it is gone when not able to register but it never returns so can never publish/register it.

**Comment by mheppler** [comment]
The Publish button still had some render logic in it, that was hiding it.
````
DatasetPage.dataset.globalIdCreateTime != null
````
Removed that from the button, should now display properly. When the dataset isn't registered, the publish confirmation popup will display a message, "This dataset is unregistered. We will attempt to register it before publishing."
