### ISSUE TITLE
API Terms of Use

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#1718]
Spoke with the Berkman team and the API will have its own set of Terms of Use that are distinct from (but also reference) the Account Terms of Use. Meeting with them on 3/23 to finalize this document with them. A draft is available here: https://www.dropbox.com/s/edrt6gcgk7ffnuc/API_TOS_Draft2.docx?dl=0

For background information about this ticket please see #551 & #1385.

Once we have the finalized API Terms text from Berkman I will add this to our dataverse.org Best Practices Harvard Policies guide and dev can then use this text with the API.

**Comment by pdurbin** [comment]
@posixeleni would it be possible for you to go ahead commit a file into git with some placeholder text? Then dev can go ahead and use this text and finish up the work on the dev end.

Then it would just be a matter of updating the placeholder text, once it's finalized.

**Comment by posixeleni** [comment]
@pdurbin Added placeholder .rst file in git of dataverse.org repo and once a new dataverse.org build runs the link to the docs should be: http://best-practices.dataverse.org/harvard-policies/harvard-api-tou.html

**Comment by pdurbin** [comment]
The ticket where I left a comment at https://github.com/IQSS/dataverse/issues/551#issuecomment-77267924 is now closed so I'll ask a clarifying question here. Which are we storing in the database...

1. A link to http://best-practices.dataverse.org/harvard-policies/harvard-api-tou.html
2. The content of https://github.com/IQSS/dataverse.org/blob/master/docs/best_practices/source/harvard-policies/harvard-api-tou.rst

?

**Comment by posixeleni** [comment]
For storing: @pdurbin: similar to how we handle the privacy policy this would be option 1 that you mention above so that we just store the link and only need to update the content in one place 

For displaying in the API:
We can get clarification from Berkman on our 3/23 meeting if its ok to just reference the terms (w/ a link) or display the entire API Terms document.

**Comment by mcrosas** [comment]
@posixeleni what's the status of this? can we close it?

**Comment by posixeleni** [comment]
@pdurbin can you please confirm that you are now using the API Terms of use that I have put on the dataverse.org site? http://best-practices.dataverse.org/harvard-policies/harvard-api-tou.html per your comment here https://github.com/IQSS/dataverse/issues/1718#issuecomment-83128636 i was unsure what the status was

**Comment by pdurbin** [comment]
@posixeleni it has not been configured in production. It says "There are no API Terms of Use for this Dataverse installation.":

```
murphy:dataverse pdurbin$ curl -s -u $PDURBINKEY: https://dataverse.harvard.edu/dvn/api/data-deposit/v1.1/swordv2/service-document | xmllint -format -
<?xml version="1.0"?>
<service xmlns="http://www.w3.org/2007/app" xmlns:atom="http://www.w3.org/2005/Atom">
  <workspace>
    <atom:title type="text">Harvard</atom:title>
    <collection href="https://dataverse.harvard.edu/dvn/api/data-deposit/v1.1/swordv2/collection/dataverse/pdurbin">
      <atom:title type="text">Philip Durbin</atom:title>
      <collectionPolicy xmlns="http://purl.org/net/sword/terms/">There are no API Terms of Use for this Dataverse installation.</collectionPolicy>
      <mediation xmlns="http://purl.org/net/sword/terms/">false</mediation>
      <acceptPackaging xmlns="http://purl.org/net/sword/terms/">http://purl.org/net/sword/package/SimpleZip</acceptPackaging>
    </collection>
  </workspace>
  <generator xmlns="http://www.w3.org/2005/Atom" uri="http://www.swordapp.org/" version="2.0"/>
  <version xmlns="http://purl.org/net/sword/terms/">2.0</version>
</service>
```

**Comment by posixeleni** [comment]
@pdurbin whats the roadblock for having this display in the API? Please let me know if there is anything you need from me.

**Comment by pdurbin** [comment]
@posixeleni no roadblock. This ticket just need to be assigned to someone who could do it. I just did:

`curl -X PUT -d 'http://best-practices.dataverse.org/harvard-policies/harvard-api-tou.html' http://localhost:8080/api/admin/settings/:ApiTermsOfUse`

Now it shows the way I think you want it to:

```
murphy:dataverse pdurbin$ curl -s -u $PDURBINKEY: https://dataverse.harvard.edu/dvn/api/data-deposit/v1.1/swordv2/service-document | xmllint -format -
<?xml version="1.0"?>
<service xmlns="http://www.w3.org/2007/app" xmlns:atom="http://www.w3.org/2005/Atom">
  <workspace>
    <atom:title type="text">Harvard</atom:title>
    <collection href="https://dataverse.harvard.edu/dvn/api/data-deposit/v1.1/swordv2/collection/dataverse/pdurbin">
      <atom:title type="text">Philip Durbin</atom:title>
      <collectionPolicy xmlns="http://purl.org/net/sword/terms/">http://best-practices.dataverse.org/harvard-policies/harvard-api-tou.html</collectionPolicy>
      <mediation xmlns="http://purl.org/net/sword/terms/">false</mediation>
      <acceptPackaging xmlns="http://purl.org/net/sword/terms/">http://purl.org/net/sword/package/SimpleZip</acceptPackaging>
    </collection>
  </workspace>
  <generator xmlns="http://www.w3.org/2005/Atom" uri="http://www.swordapp.org/" version="2.0"/>
  <version xmlns="http://purl.org/net/sword/terms/">2.0</version>
</service>
```

Right? Just the link?

**Comment by posixeleni** [comment]
looks good! thanks @pdurbin! I am closing this ticket now.

**Comment by pdurbin** [comment]
@posixeleni actually, I'll grab it and re-open it to put the curl command in our setup scripts.

**Comment by pdurbin** [comment]
> put the curl command in our setup scripts

Done in 147e803

Passing to QA.

**Comment by kcondon** [comment]
OK, sword api tou is in place, closing.
