### ISSUE TITLE
Search: undefined field doi, handle search terms with a colon

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#1720]
We expect people to search for DOI's such as "doi:10.5072/FK2/4QEJQV".

Because they have a colon in them Solr thinks we're trying to search a specific field, like "title:democracy".

Right now we get an error:

```
$ curl -s http://localhost:8080/api/search?q=doi:10.5072/FK2/4QEJQV | jq .
{
  "message": "Search Syntax Error: undefined field doi",
  "status": "ERROR"
}
```

Basically, this ticket is about deciding how to handle colons that appear in strings you search on.

**Comment by pdurbin** [comment]
#1694 is the ticket where we are trying to make DOIs searchable.

**Comment by pdurbin** [comment]
I played around a bit with `query = ClientUtils.escapeQueryChars(query);` from org.apache.solr.client.solrj.util.ClientUtils and while it make a basic search for "doi:10.5072/FK2/4QEJQV" work, it breaks all other advanced search, such as "title:foo".

**Comment by pdurbin** [comment]
As I showed @mcrosas as of 61da669 we're special-casing searches for DOI's and Handles. Should be good enough for 4.0 but feedback is welcome, as always. Passing to QA.

**Comment by sbarbosadataverse** [comment]
No error message associated with searching for a complete doi; returns exact dataset containing the doi
