### ISSUE TITLE
Code Cleanup: consider having continue button push hidden save button

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#1721]
See issue #1654 
In that case, continue was missing the update. If the update changes on the save it will need to change her too, so maybe it's better to have the continue push the hidden save button and changes only need to go to one place.

**Comment by pdurbin** [comment]
@scolapasta do you imagine that in backlog grooming you'll advocate for this issue to be added to a sprint anytime soon? If not, I say we close it.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
