### ISSUE TITLE
Theme + Widget - Validation Errors Break Label Tooltips

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1722]
The validation returned to the page has broken the tooltips for the form labels, which is a problem especially when the validation refers to formatting the values, and the tooltip has information that might be useful.

- [x] Theme + Widget

**Comment by mheppler** [comment]
Fixed broken tooltips after validation error on Theme + Widgets pg. Save Changes button was missing an `oncomplete="bind_bsui_components();"` attribute.

**Comment by kcondon** [comment]
OK, works, tool tips work after validation failure.
