### ISSUE TITLE
Searching for De-accessioned Datasets

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#1725]
Spoke with @mcrosas and I had missed an important use case where we would have end users wanting to search for known datasets in Dataverse that had become de-accessioned. So we need to review this functionality for 4.x to see how these would be made searchable.

**Comment by mheppler** [comment]
Believe this feature is already done, so I will close this issue, but added a reference to it in **Admin cannot view deaccessionned record in GUI list if draft of said record still exists #6733** to make sure it considered when addressing the discoverability of deaccessioned datasets going forward.

Here is a screenshot from a test server running a develop branch of 4.20, where a dataset title search returned the deaccession dataset.

<img width="1190" alt="Screen Shot 2020-07-15 at 5 14 46 PM" src="https://user-images.githubusercontent.com/687227/87597023-131de180-c6bf-11ea-9a23-3e86ee30825e.png">
