### ISSUE TITLE
Datasets Not Being Saved in build

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#1726]
As of today, @eaquigley, @sbarbosadataverse and myself have tried to create a Dataset in dvn-build and it looks like the Dataset is successfully saved as an unpublished draft but when I go to the Dataverse-level it is not listed and I am unable to search for it.  There are no errors listed on the page.

Since this bug has been replicated three times I am assuming that this is a bug.

Assinging to @scolapasta for help since this is a critical issue that we need to fix.

**Comment by pdurbin** [comment]
I'm pretty sure this is due to the schema.xml change I made in 4383be4 and commented about at https://github.com/IQSS/dataverse/issues/1694#issuecomment-83198938

Passing to QA.

**Comment by posixeleni** [comment]
Works as expected now. Closing this ticket.
