### ISSUE TITLE
Edit dataverse: view required metadata block fields should not allow changing for an inherited block

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#1727]
Parent dataverse and subdataverse that inherits a metadata block from a parent, I can click on "[+] View fields + set as hidden, required, or optional" for that block, it allows changing "required/optional" but doesn't actually save changes.

The expected behavior is:
view only if inherited.

**Comment by sekmiller** [comment]
You should only be able to edit the input level of fields if the DV is in non-inherit mode.  Also a view link has been added for when you are in inherit mode or the given mdb is not selected.

**Comment by sbarbosadataverse** [comment]
Inherited metadata block does not allow editing. Perfect~

![mgdvbymq75sn5op0d64vf9dxscg1e4qyfkodpioxsbg](https://cloud.githubusercontent.com/assets/8322346/6872736/71a00d7c-d481-11e4-9fda-2b50f72456cf.png)
