### ISSUE TITLE
Guestbook - View Data Collected

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1730]
- [x] New page, and not a popup
- [x] Table display
- (Future release) Download

**Comment by mcrosas** [comment]
To review with @scolapasta if it can be part of 4.0. Needs new page from developer, and then some @mheppler work

**Comment by sekmiller** [comment]
Mike, 
I created a new page guestbook-responses.xhtml  Please take a look and format the responses.  I talked to Gustavo about the breadcumbs.  We're not in a position to add something at the moment, but I created a ticket for "In Review"

**Comment by mheppler** [comment]
Passing to @sekmiller to look into displaying the custom questions in the dataTable, using p:columns, that doesn't seem to be working, potentially because of the additional back end work needed (ref: http://stackoverflow.com/questions/18867345/how-to-display-variable-number-of-columns-in-primefaces-datatable). Also, rather than formatting the date "3/27/2015", please change it to "March 27, 2015", as we use more consistently across the site.

**Comment by sekmiller** [comment]
This page still needs a little love, but we got a "good enough for now" from Liz.

**Comment by mcrosas** [comment]
:heart_eyes:

**Comment by sbarbosadataverse** [comment]
New page, and not a popup --- YES
    Table display --- YES
    (Future release) Download
