### ISSUE TITLE
Dataverse Navbar/Footer - Items For Production

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1731]
- [x] Change "Beta" label in navbar to "Upgrade In Progress"
- [x] Link label to popup with more information
- [x] **About** will link to http://dataverse.org
- [x] **Feedback** will change to **Contact** (navbar and contact form popup)
- [x] Footer: "Powered by Dataverse" logo will link to dataverse.org and **Privacy Policy** will show with a link to the page on dataverse.org (http://best-practices.dataverse.org/harvard-policies/harvard-privacy-policy.html)

**Comment by posixeleni** [comment]
@mheppler added some additional items that need to be modified in the navbar and footer when we launch. Thanks for the help!

**Comment by mheppler** [comment]
Update the navbar and footer to be production ready with new links, messaging.

Privacy Policy URL was already in the set up script, and will be ready for when it is run on production or any test environment.

@eaquigley -- Popup for the "Upgrade in progess..." label has placeholder message that can be edited in the bundle.

**Comment by eaquigley** [comment]
Updated text for this and added in a link to the Dataverse Roadmap. Passing to QA

**Comment by mheppler** [comment]
For the navbar status label and popup, updated text in bundle and add render logic.

@ekraffmiller has moved the "upgrade" specific message to a curl command that gets added to the database. The render logic I added checks to see if it is there.
````
curl -s -X PUT -d 'Dataverse is currently being upgraded. You can see the features, bug fixes, and other upgrades for this release in the <a href="http://roadmap.datascience.iq.harvard.edu/milestones/milestone-roadmap/dataverse/" title="Dataverse Roadmap" target="_blank">Dataverse Roadmap</a>.' http://localhost:8080/api/admin/settings/:StatusMessageText 

curl -s -X PUT -d 'Upgrade in progress...' http://localhost:8080/api/admin/settings/:StatusMessageHeader
````

**Comment by sbarbosadataverse** [comment]
Change "Beta" label in navbar to "Upgrade In Progress" --- done
Link label to popup with more information --- done

About will link to http://dataverse.org - done
Feedback will change to Contact (navbar and contact form popup) - done

Footer: "Powered by Dataverse" logo will link to dataverse.org - done

and Privacy Policy will show with a link to the page on dataverse.org (http://best-practices.dataverse.org/harvard-policies/harvard-privacy-policy.html) -- done
