### ISSUE TITLE
Dataverse - Edit General Information - Metadata Blocks, Browse/Search Facets Improvements

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1732]
- [x] Removed "two-step" help text, and have the two pieces of each form come back together
- [x] When metadata blocks are disabled, grey the text out

**Comment by mheppler** [comment]
Removed second help text block on Metadata Fields and Browse/Search Facets sections of Dataverse Edit General Information page. Cleaned up some minor UI issues, optimized markup by moving some rendered elements around.

@eaquigley -- With the single help text block, now these messages display for both Root and child dataverses. If two different messages are needed, additional render logic will be needed. Just add all the text here, and I can add it to the bundle, along with the render logic to the XHTML.

**Comment by eaquigley** [comment]
@mheppler here are the messages (I went back to a previous commit in the bundle prior to having the two separate i blocks and used the messages from there).

For Root Dataverse: 
- [ ] Choose the metadata fields to use in dataset templates and when adding a dataset to this dataverse.
- [ ] Choose the metadata fields to use as facets for browsing datasets and dataverses in this dataverse.

For dataverses under Root Dataverse:
- [ ] Choose the metadata fields to use in dataset templates and when adding a dataset to this dataverse.
- [ ] Use metadata fields from [insert dataverse name] Dataverse.
- [ ] Choose the metadata fields to use as facets for browsing datasets and dataverses in this dataverse.
- [ ] Use browse/search facets from [insert dataverse name] Dataverse.

**Comment by mheppler** [comment]
Improved help text messaging for Edit General Information on dataverse pg.

**Comment by eaquigley** [comment]
@mheppler After this was added in, the metadata fields section of the General Information page is broken. 

Unselect Use metadata fields from Root Dataverse->Cannot click on any of the metadata sets, still appear grayed out->Reselect Use metadata fields from Root Dataverse and the checkbox doesn't stay checked.

**Comment by mheppler** [comment]
@eaquigley -- Checked this locally and on dvn-build and was able to changed the metadata blocks from the Root Dataverse, to a custom list, set required fields, and save successfully.

**Comment by eaquigley** [comment]
Passing back to @mheppler as this is still happening on my Windows machine.

**Comment by mheppler** [comment]
Metadata Fields/General Information issue no longer seems to be an issue on dvn-build, or locally, in Chrome/Windows. Passing back to @eaquigley.

**Comment by eaquigley** [comment]
@sekmiller fixed this as well as added in logic so a user can always View the metadata fields but can only set them as hidden, required, or optional, if they disinherit from the root.

**Comment by sbarbosadataverse** [comment]
all set!
