### ISSUE TITLE
Performance: Homepage and Search/Browse Card Queries

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#1735]
The Search/Browse Cards generate a high number of queries. File Cards, in particular, appear to create in the neighborhood of 500 queries each.

A listing of queries for 18 dataverses, 3 datasets, 9 files is available on google drive: 
- https://drive.google.com/a/harvard.edu/folderview?id=0B4VvItDJwfehemRYN0ktVFJnRzA&usp=sharing
- The query list is related to the screenshot below

![root_dataverse](https://cloud.githubusercontent.com/assets/1036060/6756741/3e0adef8-cf02-11e4-9d35-25c0400c6438.png)

/cc @scolapasta

**Comment by scolapasta** [comment]
Moved info to #800, passing to QA as a duplicate
