### ISSUE TITLE
Manage Guestbook: No Edit Button for Inherited Guestbook

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#1736]
Initially testing ticket: Beta 14; 1647

I created a guestbook in root dataverse, and enabled.
created a new dataverse
created a new dataset
went to parent dataverse, selected "dataset guestbook," resolved to page displayed a guestbook I had created and enabled, but did not use, but no option to "edit" only "view"

![9mnlep9yiae44b1jj09krgkjbg9cp4mnt1oiz5grhco](https://cloud.githubusercontent.com/assets/8322346/6757051/721b680a-cf04-11e4-8627-fe2c162d18f5.png)

**Comment by sbarbosadataverse** [comment]
This is an inherited guestbook--working as it should--but--maybe a clearer indication of the source of the guestbook?

**Comment by eaquigley** [comment]
@mheppler Could we have text in the box with the view that renders to only show when its a guestbook that is inherited? my other thought would be a column for Dataverse Created In but that seems a bit much.

**Comment by mheppler** [comment]
Yes, I believe the best approach would be to add a small text message to the Action column of the Manage Guestbook pg, like we do for inherited roles on the Manage Permissions pg. (See attached.)

<img width="462" alt="screen shot 2015-12-15 at 4 00 10 pm" src="https://cloud.githubusercontent.com/assets/687227/11824027/66919bd8-a345-11e5-8e31-0ae8c91a425f.png">

Also, this same "no edit button" issue exists on the Manage Templates pg, and a new ticket should be opened specific to that pg.

**Comment by mheppler** [comment]
Added new message to manage tables to identify templates and guestbooks that were created in the root or parent dataverse.

![screen shot 2016-01-04 at 4 21 04 pm](https://cloud.githubusercontent.com/assets/687227/12100851/9004a66c-b2ff-11e5-97b8-1ebf59f9259f.png)

**Comment by kcondon** [comment]
Message is as described, closing.
