### ISSUE TITLE
required Guestbook field on download: No "field" required error message appears when required field left blank

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#1737]
Required field left blank
Click "Accept"

No immediate download but no error message indicated a required field was left blank:

![f7pbqupmoejefdwsphkwymx_nwhnodyed25vxkidgsa](https://cloud.githubusercontent.com/assets/8322346/6759684/4d62cf30-cf18-11e4-87dd-5deb242945f0.png)

![lzmi8ap8uxxa5ggmsjx9xve6tydgurjkpjwp4jeygci](https://cloud.githubusercontent.com/assets/8322346/6759685/4ecf317e-cf18-11e4-8f26-c77663138b1c.png)

**Comment by scolapasta** [comment]
There had been an issue with the validation message for required dropdown questions (error message at top, but not next to question). This has been resolved, so please let us know if you see anything else.

**Comment by sbarbosadataverse** [comment]
Validation error when required field left blank!

![alt1_vnk3nioxzsgesuowiubvzkf8t_fxyzia9lo-nm](https://cloud.githubusercontent.com/assets/8322346/6870480/b52e3bd6-d472-11e4-95d4-1c131772e3b7.png)
