### ISSUE TITLE
Edit Dataverse: When hiding metablocks, choosing local blocks does not save until first save do not inherit separately.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1739]
Edit Dataverse: When hiding metablocks, choosing local blocks does not save until first save do not inherit separately.

1. Assign sub blocks to a dv by updating the metadatablocks table and assigning dataverse_id.
2. Edit general info
3. Deselect inherit from parent and select a sub block.
4. Save. Notice nothing was saved.
5. Repeat with just deselecting inherit from parent, save. That works. Now rest will work.

**Comment by sekmiller** [comment]
Fix checked in for this.  New build required for testing

**Comment by posixeleni** [comment]
Works as expected. Closing.
