### ISSUE TITLE
Code Cleanup - On Complete for Guestbook Popup Accept Buttons

### ISSUE THREAD

**Issue by sekmiller** [IQSS/dataverse#1740]
We are using:

oncomplete="if (args === undefined) downloadPopup.hide();"

to close the guestbook popup windows.

**Comment by sekmiller** [comment]
Leaving Assigned to me. This may be fixed wrt to new prime faces version.

**Comment by sekmiller** [comment]
This was fixed as part of the PF upgrade. Can be closed.

**Comment by kcondon** [comment]
Yes, tested as part of 4.2.4, closing.
