### ISSUE TITLE
Onboarding: Migrated user message at login incorrect, not helpful: username password invalid.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1741]
For migrated users, first time log in should present a friendly message asking them to change their password along with the form that allows them to do so, according to this lovely mockup:
https://iqssharvard.mybalsamiq.com/projects/36to40builtinaccounts/Dataverse%20Account%20II%20-%20Account%20Found

It does not do this: only tells you that your username/password combo is incorrect.
I tested this by setting passwordencryptionversion to 0 for the admin account. 0 fails, 1 works.

**Comment by scolapasta** [comment]
This was my mistake. Just changing encryption stole is not enough, as then the encrypted value would be different (d'oh).


You'll also have to copy a known password's encrypted value.

**Comment by kcondon** [comment]
OK, works. Wording might need to change to add info about required password format but was noted in #1649 Closing
