### ISSUE TITLE
Log in: Help link on Shib login box throws 404.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1743]
Log in: Help link on Shib login box throws 404.

**Comment by eaquigley** [comment]
That link is displaying as guides/User/account.html when it should be displaying as: /guides/user/account.html apparently the capital U breaks it. Odd. Passing to @mheppler

**Comment by mheppler** [comment]
Changed "user" to lowercase in URL to fix 404 error.

I don't have Shib locally, so didn't test locally.

**Comment by posixeleni** [comment]
Help link is now working as expected. Closing ticket.
