### ISSUE TITLE
Templates: Review Feature Post 4.0 Release Based on Usability Testing Feedback

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1744]
There was a lot of feedback on the Templates feature and how it could be improved to better suit the needs of our users. Creating this ticket as a placeholder for us to remember to review this feature and determine our plan for making it better.

**Comment by pdurbin** [comment]
> There was a lot of feedback on the Templates feature and how it could be improved to better suit the needs of our users. Creating this ticket as a placeholder for us to remember to review this feature and determine our plan for making it better.

I'm closing this issue. If we can find the feedback and want to work on this, great. We can re-open it in the future or create a fresh one.
