### ISSUE TITLE
File Uploading: Add Google Drive & other options 

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1746]
Currently we have Dropbox as a way to upload files, users have suggested these other integrations:
- [ ] Google drive
- [ ] box.com

**Comment by posixeleni** [comment]
just received a user request for uploading astro data from Google Drive into Dataverse

**Comment by eaquigley** [comment]
Consilience will also need this so while it is in research by Consilience team, we can then use the information found out about Google Drive for Dataverse.

**Comment by umuchlish** [comment]
To facilitating File upload from multi-vendor, please add Hyperlink File upload and listed as Files. 

This is perhaps a solution for part of dataset that stored at other location due to technical burden, license or agreement. 

By design user able to input the URL from other vendor storage or third-party collaboration research output.

**Comment by scolapasta** [comment]
The issue with just adding a link is that Dataverse is meant to guarantee the availability of the files and a link to any external resource will not do that. 

The current approach that is being explored is the idea of having "Trusted Remote Storage Agents", which is being tracked in issue #4379

**Comment by jmjamison** [comment]
Being able to upload from Google drive would be helpful.  I've just upgraded UCLA's Dataverse to 5.0 and that seems to have eliminated the issue I was having uploading large (LiDAR) data.  Unfortunately the data I need to upload is currently stored on Google Drive.  I'll try the workarounds suggested but a direct upload would be nice.

**Comment by mheppler** [comment]
Looks like there is a [Google Picker](https://developers.google.com/drive/api/v3/picker) to "enable users to open or upload Google Drive files".

<img width="842" alt="Screen Shot 2020-09-01 at 1 35 55 PM" src="https://user-images.githubusercontent.com/687227/91886940-11e94980-ec58-11ea-95c6-de50303f2ed1.png">

For the [picker docs](https://developers.google.com/picker/docs):

>After obtaining the file ID from the picker when opening files, an application can then fetch the file metadata and download the file content as described in the reference documentation for files.get.

**Comment by pdurbin** [comment]
I guess it's the "and other options" in the title of this issue that drives me crazy. It's too broad.

@umuchlish if you want "Hyperlink File upload" (I don't know what this is), please feel free to create a fresh issue (and explain it a bit more and provide a link, please).

@jmjamison if you still want Google Drive support, please feel free to open a fresh issue for that.

We do have Globus support now, as of 5.12! 🎉 https://guides.dataverse.org/en/5.12/developers/big-data-support.html#globus-file-transfer

And remote storage (also with 5.12): https://guides.dataverse.org/en/5.12/developers/big-data-support.html#trusted-remote-storage-with-the-remote-store-type
