### ISSUE TITLE
Allow DvObjects to be persisted even if there are Solr errors (more try/catch)

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#1749]
#229 ("Create Dataset: Allow data set to be created even if not able to index. Manage index failures for later correction) handled the case of Solr being **down** but if the Solr schema is **out of date** DvObjects still can't be persisted. You'll get an error like this:

> org.apache.solr.client.solrj.impl.HttpSolrServer$RemoteSolrException: ERROR: [doc=dataset_10_draft] unknown field 'whateverTheNewFieldIs'

In a lot of methods we catch `SolrServerException` and `IOException`. I think if we add `HttpSolrServer.RemoteSolrException` to the list of exceptions we catch, we'll be able to persist objects to the database even if the Solr schema is out of date.

Of course this raises the question of keeping Solr in sync with the database. In #702 I started working on a "status" page/endpoint to know when Solr is out of date (missing documents and orphaned documents). That ticket still needs more work in that regard. Right know it's hard to know the status of Solr being in sync with the database.

The question for this ticket is if we should go ahead and let DvObjects be created if the Solr schema is out of date. @scolapasta we had talked about this with @ekraffmiller in the context of "more try/catch". I'll give this to you for now to think about.

**Comment by bencomp** [comment]
We just ran into the issue of the Solr schema being out of date. If there such a strong interdependence between the Dataverse version and Solr schema, I would suggest to make sure they are updated in a single "transaction". The documentation has to say 

> The Solr schema **MUST** be updated at the same time as the Dataverse application WAR.

**Comment by pdurbin** [comment]
@bencomp this is an excellent point. We could really use some help improving the Installation Guide in #913 if you or anyone is interested!

**Comment by pdurbin** [comment]
#2321 is the new issue for improving documentation.

**Comment by pdurbin** [comment]
I guess we're surviving with the way things are. Closing.
