### ISSUE TITLE
Multiline text squished into a single line when saved to "setting" table

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#1752]
How can we display multiple paragraphs in our Terms of Use? This used to work in #972

Now multiline input is squished into a single line when saved to the database:

```
murphy:dataverse pdurbin$ cat /tmp/app-tou.txt
This is paragraph 1.

This is paragraph 2.

This is paragraph 3.
murphy:dataverse pdurbin$ curl -s -X PUT -d@/tmp/app-tou.txt http://localhost:8080/api/s/settings/:ApplicationTermsOfUse | jq .
{
  "data": {
    ":ApplicationTermsOfUse": "This is paragraph 1.This is paragraph 2.This is paragraph 3."
  },
  "status": "OK"
}
$ psql -c "select * from setting where name = ':ApplicationTermsOfUse';" dataverse_db
          name          |                           content                            
------------------------+--------------------------------------------------------------
 :ApplicationTermsOfUse | This is paragraph 1.This is paragraph 2.This is paragraph 3.
(1 row)
```

![squished](https://cloud.githubusercontent.com/assets/21006/6788374/69587042-d16f-11e4-8a19-75b12bd1e35a.png)

This was first reported at https://github.com/IQSS/dataverse/issues/551#issuecomment-77267924

**Comment by pdurbin** [comment]
I'm not sure when this behavior changed. As a sanity check I reverted (locally) the commit I made in 44e4661 where I changed the PostgreSQL data type from "varchar" to "text", but that's not it. Passing to @scolapasta for review.

**Comment by pdurbin** [comment]
I wonder if this broke when the "actionlogrecord" table was added in #1532

At least, this is the error I get when I try to import a long document (which worked 28 days ago according to https://github.com/IQSS/dataverse/issues/972#issuecomment-75631924 ):

curl http://best-practices.dataverse.org/_sources/harvard-policies/harvard-terms-of-use.txt > /tmp/app-tou.txt 

curl -s -X PUT -d@/tmp/app-tou.txt http://localhost:8080/api/s/settings/:ApplicationTermsOfUse

Caused by: javax.persistence.PersistenceException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: ERROR: value too long for type character varying(1024)
Error Code: 0
Call: INSERT INTO ACTIONLOGRECORD (ID, ACTIONRESULT, ACTIONSUBTYPE, ACTIONTYPE, ENDTIME, INFO, STARTTIME, USERIDENTIFIER) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
        bind => [8 parameters bound]

**Comment by scolapasta** [comment]
We need to get real terms of use in here and see what it looks like. I'll work with @posixeleni to get those in.

**Comment by scolapasta** [comment]
Added real terms to dvn-build. Line breaks are there, but there isn't formatting.

(Other option would be to not have it be in a text area and store html markup in the setting)

Are we OK with how this looks for 4.0? (if so, we will work on adding this to setup-harvard and commit).

**Comment by posixeleni** [comment]
@scolapasta  Berkman had updated the General Terms of Use earlier this week, which is not reflected in the Sphinx guide at the moment, since we were waiting to hear from Cris & Gary if they wanted to modify anything. Gary responded already but Cris did not so I will follow-up with her to see if she has any reservations about the Terms or if we can use them as is.

cc/ @eaquigley

**Comment by scolapasta** [comment]
@mheppler is taking a look at this. Mike, if you need to change terms of use, it's in the Settings table as :AppicationTermsofUse. Just add what you need there. I'll be working on adding this to the setup-harvard script momentarily.

**Comment by mheppler** [comment]
@scolapasta @posixeleni -- please provide a file or text/HTML snippet of what isn't properly displaying, so I can test it locally. (Emailing a file is preferable. Posting it here in a comment could change the formatting.)

**Comment by posixeleni** [comment]
@mheppler would this be helpful? http://best-practices.dataverse.org/harvard-policies/harvard-terms-of-use.html

**Comment by mheppler** [comment]
Fixed display of HTML formatted teext on term-of-use.

Created new ticket #1863 for properly formatting the terms text with HTML for deployment.

**Comment by bencomp** [comment]
@pdurbin just guessing, but could the original issue (multi-line squish) be a PostgreSQL connection/database setting?

Or, wait, I may have seen this before. It may be a "LF vs CRLF over curl/HTTP" issue. In the curl command you use `-d`. I had to use `--data-binary` to preserve line breaks even for plain text.
