### ISSUE TITLE
Dataset Page Performance: Each Additional File

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#1754]
Similarly to #1735, dataset page performance steadily degrades as the number of files increase.

This chart gives a look at "rough"  query counts as additional files were added/published to a dataset.  
  -  Note: each file was either 1 or 2 bytes.  eg. 'f1.txt' containing '1', 'f2.txt' containing '2', etc.

To run query counts, use: https://github.com/IQSS/glassfish-query-counter

|Number of Published Files|Queries - as Admin|Queries - Not Logged In|Incremental - as Admin|Incremental - Not Logged In|
-------------|-------------|-------------|-------------|-------------|
|0|868|374|n/a|n/a|
|1|922|428|54|54|
|2|1107|661|185|233|
|3|1258|812|151|151|
|4|1409|963|151|151|
|5|1560|1114|151|151|
|6|1711|1265|151|151|
|7|1862|1416|151|151|
|8|2013|1567|151|151|
|9|2164|1718|151|151|
|10|2315|1869|151|151|
|15|2662|2216|347|347|
|20|3009|2563|347|347|
|30|3601|3155|592|592|
|50|4634|4188|1033|1033|

**Comment by raprasad** [comment]
Example with Queries for 5 published files and user not logged in.

|Query count|SQL Statement|
-------------|-------------
|290|"SELECT ID, DISPLAYORDER, value, DATASETFIELD_ID FROM DATASETFIELDVALUE WHERE (DATASETFIELD_ID = ?) ORDER BY DISPLAYORDER ASC"|
|156|"SELECT ID, ASSIGNEEIDENTIFIER, DEFINITIONPOINT_ID, ROLE_ID FROM ROLEASSIGNMENT WHERE ((ASSIGNEEIDENTIFIER = ?) AND (DEFINITIONPOINT_ID = ?))"|
|107|"SELECT t0.ID, t0.DESCRIPTION, t0.DISPLAYNAME, t0.GROUPALIAS, t0.GROUPALIASINOWNER, t0.OWNER_ID FROM EXPLICITGROUP t0, ExplicitGroup_CONTAINEDROLEASSIGNEES t1 WHERE (((t0.OWNER_ID = ?) AND (t1.CONTAINEDROLEASSIGNEES = ?)) AND (t1.ExplicitGroup_ID = t0.ID))"|
|77|"SELECT ID, ADVANCEDSEARCHFIELDTYPE, ALLOWCONTROLLEDVOCABULARY, ALLOWMULTIPLES, description, DISPLAYFORMAT, DISPLAYONCREATE, DISPLAYORDER, FACETABLE, FIELDTYPE, name, REQUIRED, title, WATERMARK, METADATABLOCK_ID, PARENTDATASETFIELDTYPE_ID FROM DATASETFIELDTYPE WHERE (PARENTDATASETFIELDTYPE_ID = ?) ORDER BY DISPLAYORDER ASC"|
|77|"SELECT ID, INCLUDE, REQUIRED, datasetfieldtype_id, dataverse_id FROM DATAVERSEFIELDTYPEINPUTLEVEL WHERE ((dataverse_id = ?) AND (datasetfieldtype_id = ?))"|
|75|"SELECT ID, DISPLAYORDER, PARENTDATASETFIELD_ID FROM DATASETFIELDCOMPOUNDVALUE WHERE (PARENTDATASETFIELD_ID = ?) ORDER BY DISPLAYORDER ASC"|
|75|"SELECT ID, DATASETFIELDTYPE_ID, DATASETVERSION_ID, PARENTDATASETFIELDCOMPOUNDVALUE_ID, TEMPLATE_ID FROM DATASETFIELD WHERE (PARENTDATASETFIELDCOMPOUNDVALUE_ID = ?) ORDER BY DATASETFIELDTYPE_ID ASC"|
|48|"SELECT ID, DISPLAYORDER, IDENTIFIER, STRVALUE, DATASETFIELDTYPE_ID FROM CONTROLLEDVOCABULARYVALUE WHERE (DATASETFIELDTYPE_ID = ?) ORDER BY DISPLAYORDER ASC"|
|35|"SELECT t1.ID, t1.DISPLAYORDER, t1.IDENTIFIER, t1.STRVALUE, t1.DATASETFIELDTYPE_ID FROM DATASETFIELD_CONTROLLEDVOCABULARYVALUE t0, CONTROLLEDVOCABULARYVALUE t1 WHERE ((t0.DatasetField_ID = ?) AND (t1.ID = t0.controlledVocabularyValues_ID))"|
|29|"SELECT DISTINCT t0.ID, t0.DTYPE, t0.DESCRIPTION, t0.DISPLAYNAME, t0.PERSISTEDGROUPALIAS FROM IPV6RANGE t1 LEFT OUTER JOIN PERSISTEDGLOBALGROUP t0 ON (t0.ID = t1.OWNER_ID) WHERE (((((t1.TOPA > ?) OR ((t1.TOPA = ?) AND (t1.TOPB > ?))) OR (((t1.TOPA = ?) AND (t1.TOPB = ?)) AND (t1.TOPC > ?))) OR ((((t1.TOPA = ?) AND (t1.TOPB = ?)) AND (t1.TOPC = ?)) AND (t1.TOPD >= ?))) AND ((((t1.BOTTOMA < ?) OR ((t1.BOTTOMA = ?) AND (t1.BOTTOMB < ?))) OR (((t1.BOTTOMA = ?) AND (t1.BOTTOMB = ?)) AND (t1.BOTTOMC < ?))) OR ((((t1.BOTTOMA = ?) AND (t1.BOTTOMB = ?)) AND (t1.BOTTOMC = ?)) AND (t1.BOTTOMD <= ?))))"|
|14|"SELECT NAME, CONTENT FROM SETTING WHERE (NAME = ?)"|
|12|"SELECT ID, AUTHENTICATIONPROVIDERID, PERSISTENTUSERID, AUTHENTICATEDUSER_ID FROM AUTHENTICATEDUSERLOOKUP WHERE (AUTHENTICATEDUSER_ID = ?)"|
|12|"SELECT ID, ADVANCEDSEARCHFIELDTYPE, ALLOWCONTROLLEDVOCABULARY, ALLOWMULTIPLES, description, DISPLAYFORMAT, DISPLAYONCREATE, DISPLAYORDER, FACETABLE, FIELDTYPE, name, REQUIRED, title, WATERMARK, METADATABLOCK_ID, PARENTDATASETFIELDTYPE_ID FROM DATASETFIELDTYPE WHERE (ID = ?)"|
|10|"SELECT t0.ID, t0.DTYPE, t0.CREATEDATE, t0.INDEXTIME, t0.MODIFICATIONTIME, t0.PERMISSIONINDEXTIME, t0.PERMISSIONMODIFICATIONTIME, t0.PUBLICATIONDATE, t0.CREATOR_ID, t0.OWNER_ID, t0.RELEASEUSER_ID, t1.ID, t1.AFFILIATION, t1.ALIAS, t1.DATAVERSETYPE, t1.description, t1.DISPLAYBYTYPE, t1.FACETROOT, t1.GUESTBOOKROOT, t1.METADATABLOCKROOT, t1.NAME, t1.PERMISSIONROOT, t1.TEMPLATEROOT, t1.THEMEROOT, t1.DEFAULTCONTRIBUTORROLE_ID, t1.DEFAULTTEMPLATE_ID FROM DVOBJECT t0, DATAVERSE t1 WHERE ((t0.ID = ?) AND ((t1.ID = t0.ID) AND (t0.DTYPE = ?)))"|
|10|"SELECT ID, BACKGROUNDCOLOR, LINKCOLOR, LINKURL, LOGO, LOGOALIGNMENT, LOGOBACKGROUNDCOLOR, LOGOFORMAT, TAGLINE, TEXTCOLOR, dataverse_id FROM DATAVERSETHEME WHERE (dataverse_id = ?)"|
|10|"SELECT ID, ARCHIVEDESCRIPTION, ARCHIVEURL, HARVESTSTYLE, HARVESTTYPE, HARVESTINGSET, HARVESTINGURL, dataverse_id FROM HARVESTINGDATAVERSECONFIG WHERE (dataverse_id = ?)"|
|7|"SELECT ID, AFFILIATION, EMAIL, FIRSTNAME, INDEXTIME, LASTNAME, MODIFICATIONTIME, NAME, POSITION, SUPERUSER, USERIDENTIFIER FROM AUTHENTICATEDUSER WHERE (USERIDENTIFIER = ?)"|
|7|"SELECT ID, LASTUPDATEDATE, authenticatedUser_id, datasetversion_id FROM DATASETVERSIONUSER WHERE (datasetversion_id = ?)"|
|7|"SELECT ID, DATASETFIELDTYPE_ID, DATASETVERSION_ID, PARENTDATASETFIELDCOMPOUNDVALUE_ID, TEMPLATE_ID FROM DATASETFIELD WHERE (DATASETVERSION_ID = ?)"|
|7|"SELECT ID, CATEGORY, DESCRIPTION, LABEL, RESTRICTED, VERSION, DATAFILE_ID, DATASETVERSION_ID FROM FILEMETADATA WHERE (DATASETVERSION_ID = ?) ORDER BY CATEGORY ASC"|
|6|"SELECT DISTINCT DTYPE FROM DVOBJECT WHERE (ID = ?)"|
|5|"SELECT ID, AFFILIATION, EMAIL, FIRSTNAME, INDEXTIME, LASTNAME, MODIFICATIONTIME, NAME, POSITION, SUPERUSER, USERIDENTIFIER FROM AUTHENTICATEDUSER WHERE (ID = ?)"|
|5|"SELECT ID, CASEQUANTITY, ORIGINALFILEFORMAT, ORIGINALFORMATVERSION, RECORDSPERCASE, UNF, VARQUANTITY, DATAFILE_ID FROM DATATABLE WHERE (DATAFILE_ID = ?)"|
|5|"SELECT t1.ID, t1.NAME, t1.DATASET_ID FROM FILEMETADATA_DATAFILECATEGORY t0, DATAFILECATEGORY t1 WHERE ((t0.fileMetadatas_ID = ?) AND (t1.ID = t0.fileCategories_ID))"|
|5|"SELECT ID, CONTROLCARD, LABELSFILE, TEXTENCODING, datafile_id FROM INGESTREQUEST WHERE (datafile_id = ?)"|
|5|"SELECT t0.ID, t0.DTYPE, t0.CREATEDATE, t0.INDEXTIME, t0.MODIFICATIONTIME, t0.PERMISSIONINDEXTIME, t0.PERMISSIONMODIFICATIONTIME, t0.PUBLICATIONDATE, t0.CREATOR_ID, t0.OWNER_ID, t0.RELEASEUSER_ID, t1.ID, t1.CONTENTTYPE, t1.FILESYSTEMNAME, t1.FILESIZE, t1.INGESTSTATUS, t1.MD5, t1.NAME, t1.RESTRICTED FROM DVOBJECT t0, DATAFILE t1 WHERE ((t0.ID = ?) AND ((t1.ID = t0.ID) AND (t0.DTYPE = ?)))"|
|5|"SELECT ID, ALIAS, DESCRIPTION, NAME, PERMISSIONBITS, OWNER_ID FROM DATAVERSEROLE WHERE (ID = ?)"|
|5|"SELECT t0.ID, t0.DTYPE, t0.CREATEDATE, t0.INDEXTIME, t0.MODIFICATIONTIME, t0.PERMISSIONINDEXTIME, t0.PERMISSIONMODIFICATIONTIME, t0.PUBLICATIONDATE, t0.CREATOR_ID, t0.OWNER_ID, t0.RELEASEUSER_ID, t1.ID, t1.AUTHORITY, t1.DOISEPARATOR, t1.FILEACCESSREQUEST, t1.GLOBALIDCREATETIME, t1.IDENTIFIER, t1.PROTOCOL, t1.guestbook_id, t1.thumbnailfile_id FROM DVOBJECT t0, DATASET t1 WHERE ((t1.thumbnailfile_id = ?) AND ((t1.ID = t0.ID) AND (t0.DTYPE = ?)))"|
|1|"SELECT ID, ADVANCEDSEARCHFIELDTYPE, ALLOWCONTROLLEDVOCABULARY, ALLOWMULTIPLES, description, DISPLAYFORMAT, DISPLAYONCREATE, DISPLAYORDER, FACETABLE, FIELDTYPE, name, REQUIRED, title, WATERMARK, METADATABLOCK_ID, PARENTDATASETFIELDTYPE_ID FROM DATASETFIELDTYPE WHERE (METADATABLOCK_ID = ?)"|
|1|"SELECT ID, INFO, STARTTIME, USER_ID, DATASET_ID FROM DATASETLOCK WHERE (DATASET_ID = ?)"|
|1|"SELECT ID, DISPLAYNAME, NAME, dataverse_id FROM METADATABLOCK WHERE (ID = ?)"|
|1|"SELECT t1.ID, t1.DISPLAYNAME, t1.NAME, t1.dataverse_id FROM DATAVERSE_METADATABLOCK t0, METADATABLOCK t1 WHERE ((t0.Dataverse_ID = ?) AND (t1.ID = t0.metadataBlocks_ID))"|
|1|"SELECT ID, EMBEDMAPLINK, LAYERLINK, LAYERNAME, MAPIMAGELINK, WORLDMAPUSERNAME, DATASET_ID, DATAFILE_ID FROM MAPLAYERMETADATA WHERE (DATASET_ID = ?)"|
|1|"SELECT ID, INCLUDE, REQUIRED, datasetfieldtype_id, dataverse_id FROM DATAVERSEFIELDTYPEINPUTLEVEL WHERE (dataverse_id = ?)"|
|1|"SELECT t0.ID, t0.DTYPE, t0.CREATEDATE, t0.INDEXTIME, t0.MODIFICATIONTIME, t0.PERMISSIONINDEXTIME, t0.PERMISSIONMODIFICATIONTIME, t0.PUBLICATIONDATE, t0.CREATOR_ID, t0.OWNER_ID, t0.RELEASEUSER_ID, t1.ID, t1.AUTHORITY, t1.DOISEPARATOR, t1.FILEACCESSREQUEST, t1.GLOBALIDCREATETIME, t1.IDENTIFIER, t1.PROTOCOL, t1.guestbook_id, t1.thumbnailfile_id FROM DVOBJECT t0, DATASET t1 WHERE ((t0.ID = ?) AND ((t1.ID = t0.ID) AND (t0.DTYPE = ?)))"|
|1|"SELECT ID, UNF, ARCHIVENOTE, ARCHIVETIME, AVAILABILITYSTATUS, CITATIONREQUIREMENTS, CONDITIONS, CONFIDENTIALITYDECLARATION, CONTACTFORACCESS, CREATETIME, DATAACCESSPLACE, DEACCESSIONLINK, DEPOSITORREQUIREMENTS, DISCLAIMER, FILEACCESSREQUEST, INREVIEW, LASTUPDATETIME, LICENSE, MINORVERSIONNUMBER, ORIGINALARCHIVE, RELEASETIME, RESTRICTIONS, SIZEOFCOLLECTION, SPECIALPERMISSIONS, STUDYCOMPLETION, TERMSOFACCESS, TERMSOFUSE, VERSION, VERSIONNOTE, VERSIONNUMBER, VERSIONSTATE, DATASET_ID FROM DATASETVERSION WHERE (DATASET_ID = ?) ORDER BY VERSIONNUMBER DESC, MINORVERSIONNUMBER DESC"|

**Comment by raprasad** [comment]
![dataverse_-_netbeans_ide_8_0_2](https://cloud.githubusercontent.com/assets/1036060/6832918/ccde2c9c-d2ff-11e4-8456-11b8ca39742a.png)

**Comment by raprasad** [comment]
Offending lines generating about 2,000 queries for 50 published files
```xml
     <p:commandLink rendered="#{!(empty fileMetadata.dataFile.id) and !(fileMetadata.dataFile.tabularData) and !(DatasetPage.downloadPopupRequired) and (permissionServiceBean.on(fileMetadata.dataFile).has('DownloadFile'))}"
                                                           type="button" styleClass="btn btn-default"
                                                           action="#{DatasetPage.startFileDownload(fileMetadata, '')}">
                                                <span class="glyphicon glyphicon-download-alt"/> #{bundle.download}
                                            </p:commandLink>
                                            <!-- guest book or terms of use, etc. enabled - open "download popup" first: -->
                                            <p:commandLink rendered="#{!(empty fileMetadata.dataFile.id) and !(fileMetadata.dataFile.tabularData) and DatasetPage.downloadPopupRequired and (permissionServiceBean.on(fileMetadata.dataFile).has('DownloadFile'))}"
                                                           type="button" styleClass="btn btn-default"
                                                           action="#{DatasetPage.initGuestbookResponse(fileMetadata)}"
                                                           update="@form" oncomplete="downloadPopup.show();handleResizeDialog('downloadPopup');">
                                                <span class="glyphicon glyphicon-download-alt"/> #{bundle.download}
                                            </p:commandLink>
```

**Comment by raprasad** [comment]
The links in th versions tab generate another 400 queries for the 50 published files

```xml
<p:commandLink rendered="#{(!empty(versionTab.defaultVersionDifference)) and DatasetPage.versionTabList.size() > (rowNum + 1)}"
actionListener="#{DatasetPage.updateVersionDifferences(versionTab, null)}"
oncomplete="detailsBlocks.show();post_differences();"
update=":datasetForm"
value="#{bundle['file.dataFilesTab.versions.viewDetails.btn']}"></p:commandLink>
```

**Comment by raprasad** [comment]
Only use the permissionService once for each of these commands.  

```xhtml
<!-- (40) -->                                                                                and permissionServiceBean.on(DatasetPage.dataset).canIssueCommand('UpdateDatasetCommand')
<!-- (81) -->                                      <ui:fragment rendered="#{!DatasetPage.dataset.released and DatasetPage.dataset.latestVersion.versionState=='DRAFT' and permissionServiceBean.on(DatasetPage.dataset).canIssueCommand('DeleteDatasetCommand')}">
<!-- (89) -->                                      <ui:fragment rendered="#{DatasetPage.dataset.released and DatasetPage.dataset.latestVersion.versionState=='DRAFT' and permissionServiceBean.on(DatasetPage.dataset).canIssueCommand('DeleteDatasetCommand')}">
<!-- (97) -->                                      <ui:fragment rendered="#{DatasetPage.dataset.released and !empty(DatasetPage.releasedVersionTabList) and permissionServiceBean.on(DatasetPage.dataset).canIssueCommand('DeleteDatasetCommand')}">
<!-- (111) -->                                                       and permissionServiceBean.on(DatasetPage.dataset).canIssueCommand('PublishDatasetCommand')
<!-- (113) -->                                                          and permissionServiceBean.on(DatasetPage.dataset).canIssueCommand('UpdateDatasetCommand')
<!-- (114) -->                                                          and !permissionServiceBean.on(DatasetPage.dataset).canIssueCommand('PublishDatasetCommand'))}">
<!-- (133) -->                                                              and permissionServiceBean.on(DatasetPage.dataset).canIssueCommand('PublishDatasetCommand')}">
<!-- (139) -->                                                              and permissionServiceBean.on(DatasetPage.dataset).canIssueCommand('PublishDatasetCommand')}">
<!-- (145) -->                                                             and permissionServiceBean.on(DatasetPage.dataset).canIssueCommand('PublishDatasetCommand')
<!-- (154) -->                                                              and permissionServiceBean.on(DatasetPage.dataset).canIssueCommand('PublishDatasetCommand')}">
<!-- (161) -->                                                              and permissionServiceBean.on(DatasetPage.dataset).canIssueCommand('PublishDatasetCommand')}"
<!-- (170) -->                                                              and permissionServiceBean.on(DatasetPage.dataset).canIssueCommand('PublishDatasetCommand')}">
<!-- (179) -->                                                          and permissionServiceBean.on(DatasetPage.dataset).canIssueCommand('UpdateDatasetCommand')
<!-- (180) -->                                                          and !permissionServiceBean.on(DatasetPage.dataset).canIssueCommand('PublishDatasetCommand')}">
<!-- (471) -->                                                               and (permissionServiceBean.on(DatasetPage.dataset).canIssueCommand('UpdateDatasetCommand') 
<!-- (500) -->                                              <p:commandLink rendered="#{dataverseSession.user.authenticated and permissionServiceBean.on(DatasetPage.dataset).canIssueCommand('UpdateDatasetCommand')}"
<!-- (877) -->                                                       and permissionServiceBean.on(DatasetPage.dataset).canIssueCommand('UpdateDatasetCommand')}">
<!-- (891) -->                                                       and permissionServiceBean.on(DatasetPage.dataset).canIssueCommand('UpdateDatasetCommand')}">
<!-- (1329) -->                                                                                       and ((!dataverseSession.user.authenticated or !permissionServiceBean.on(DatasetPage.dataset).canIssueCommand('UpdateDatasetCommand'))
<!-- (1330) -->                                                                                       or ((dataverseSession.user.authenticated and permissionServiceBean.on(DatasetPage.dataset).canIssueCommand('UpdateDatasetCommand') 
<!-- (1335) -->                                                                                and (dataverseSession.user.authenticated and permissionServiceBean.on(DatasetPage.dataset).canIssueCommand('UpdateDatasetCommand'))
<!-- (1457) -->                                          <ui:fragment rendered="#{versionTab.deaccessioned and  !(permissionServiceBean.on(DatasetPage.dataset).canIssueCommand('UpdateDatasetCommand'))}">
```

**Comment by raprasad** [comment]
FileDownload Perms, move to PermissionsWrapper and also use for dataverse page:

```xhtml
<!--  lines 652-653 -->
                                       <span class="glyphicon glyphicon-lock text-danger pull-right" jsf:rendered="#{result.entity.restricted and !permissionServiceBean.on(result.entity).has('DownloadFile')}"/>
                                        <span class="icon-unlock text-success pull-right" jsf:rendered="#{result.entity.restricted and permissionServiceBean.on(result.entity).has('DownloadFile')}"/>
```

**Comment by raprasad** [comment]
Trim down Dataset Difference computation.

This can significantly add # of queries (30%, 50% of queries, etc): 
- DatasetVersion.java: https://github.com/IQSS/dataverse/blob/master/src/main/java/edu/harvard/iq/dataverse/DatasetVersion.java#L485
- dataset-versions.xhtml: https://github.com/IQSS/dataverse/blob/master/src/main/webapp/dataset-versions.xhtml#L43

**Comment by raprasad** [comment]
Check the Poole dataset: http://dvn-vm6.hmdc.harvard.edu:8080/dataset.xhtml?globalId=hdl:1902.1/12061&versionId=12401

**Comment by raprasad** [comment]
Lots of queries here for a published page, 1 file, no versions:
- https://github.com/IQSS/dataverse/blob/master/src/main/java/edu/harvard/iq/dataverse/DatasetVersion.java#L1018
- Other (bigger) hit, as mentioned above is DatasetVersionDifference

**Comment by raprasad** [comment]
another place to improve.  This line runs 2 queries per file:
```
<div class="file-tags-block #{DatasetPage.editMode == 'FILE' or DatasetPage.editMode == 'CREATE' ? 'margin-top-half' : ''}" jsf:rendered="#{!(empty fileMetadata.categories) or !(empty fileMetadata.dataFile.tags) or (DatasetPage.editMode == 'FILE' or DatasetPage.editMode == 'CREATE')}">
```

**Comment by raprasad** [comment]
check: Error Rendering View[/dataset.xhtml]
javax.el.ELException: /dataset-versions.xhtml @118,80 value="#{versionTab.versionDate}": java.lang.NullPointerException

**Comment by scolapasta** [comment]
Several sub issues have been created for dataset performance, so we're moving this more general one to QA to be closed.

**Comment by raprasad** [comment]
Query Count Update
|Number of Published Files|Queries - as Admin|Queries - Not Logged In|Incremental - as Admin|Incremental - Not Logged In|
-------------|-------------|-------------|-------------|-------------|
|0|248|138|n/a|n/a|

**Comment by raprasad** [comment]
Summary of progress.  No longer going into the stratosphere but lots of room to improve.

#### Known factors remaining:
- [ ] Version tab  - now loaded after main page but generating approx 1/3 of queries.  
     - [ ] Don't preload. #1820
- [ ] 2 queries per file for category check #1868
- [ ] post 4.0: delve into the many/many queries to retrieve metadata values (should be a single query)
     - #1874?

#### Updated counts to compare to orig. ticket

|Number of Published Files|Queries - as Admin|Queries - Not Logged In|Incremental - as Admin|Incremental - Not Logged In|Without Versions Tab|
-------------|-------------|-------------|-------------|-------------|-------------|
|0|248|138|n/a|n/a||
|1|276|166|28|28||
|2|305|195|29|29||
|3|334|224|29|29||
|4|363|253|29|29||
|5|392|282|29|29||
|6|421|311|29|29||
|7|450|340|29|29||
|8|479|369|29|29||
|9|508|398|29|29||
|10|537|427|29|29||
|15|590|480|53|53||
|20|643|533|53|53||
|30|726|616|83|83||
|50|869|759|187|54|543/457|

**Comment by raprasad** [comment]
Keeping this open as an umbrella issue.  Can still make DatasetPage significantly faster.

**Comment by raprasad** [comment]
@scolapasta @kcondon
This can be handled in 4.2

**Comment by kcondon** [comment]
This was significantly improved during dataset performance improvements in v4.2.2 using direct queries. Closing
