### ISSUE TITLE
Widgets: Updates for Integrating with OpenScholar

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1755]
- [x] update search box widget to show that it is for Dataverse. Currently is a plain input box with a generic Find button. 
- [x] Add height parameters for the listing widget
- [x] Have an image display when the data is being loaded from Dataverse

**Comment by mheppler** [comment]
Improved the widget code to style and fix some issues on the search box and iframe code that was being rendered via our javascript.

Revised list of improvements:
- [x] "Search my dataverse..." placeholder text added to search box input.
- [x] Styled search box input and Find button to have more of a Dataverse look-and-feel.
- [x] Blue "loading" spinner displayed as iframe background, to display when loading content.
- [ ] ~~Height parameters~~ (this was already in there, waiting for feedback from OpenScholar)
- [x] Styled iframe border and padding to have more of a Dataverse look-and-feel.

**Comment by posixeleni** [comment]
Updates work as indicated. Closing.
