### ISSUE TITLE
Browse/Search - Number Format

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1761]
Mainly in the browse/search, but really everywhere on the site, we need to format our numbers.

- [x] "1 to 10 of 22350 results" --  should be a little easier on the eyes, "22,350"
- [x] All facet counts
- [x] Paginator page numbers

**Comment by scolapasta** [comment]
http://stackoverflow.com/questions/8740578/how-to-format-the-number-with-comma-when-user-lost-focus-in-hinputtext
```xhtml
<h:outputText value="#{results.number}" >
    <f:convertNumber pattern="###,###" />
</h:outputText>
```

**Comment by mheppler** [comment]
Formatted dynamic counts for search-include and dataset (Downloads). Optimized some bundle code to utilize outputFormat and choices.

**Comment by posixeleni** [comment]
@kcondon not sure how to test this in build where we have only a small handful of datasets and are nowhere near anything in the thousands to verify that we are now seeing commas in larger numbers. I looked in vm5 but this also now currently only has a small handful of datasets. Can you advise where I can test for this?

**Comment by kcondon** [comment]
Test on one of the migration boxes when the update the code. Gustavo would be able to advise.
________________________________

**Comment by posixeleni** [comment]
@scolapasta can you please let me know when one of the servers used to test migration has the latest code so I can test and close this ticket?

**Comment by posixeleni** [comment]
this is now working as expected in production
