### ISSUE TITLE
Shib/Log In -- FATAL - DISCO:UI

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1762]
The following error was seen on dvn-vm6, when trying to log in. It should probably be something a little less "disco".

http://dvn-vm6.hmdc.harvard.edu:8080/

![screen shot 2015-03-25 at 11 19 19 am](https://cloud.githubusercontent.com/assets/687227/6828772/de8cd2a0-d2e5-11e4-9b84-d860ee83db4a.png)

![disco](https://cloud.githubusercontent.com/assets/687227/6828779/e8c30eba-d2e5-11e4-90d7-9706fab35573.gif)

**Comment by pdurbin** [comment]
@scolapasta asked me to re-assign this to @mheppler 

I'm not exactly sure what the message should say... maybe "This Dataverse installation is configured for login via Shibboleth but there was an internal error. Please contact support."

Here's where that message comes from:

```
murphy:dataverse pdurbin$ git diff src/main/webapp/resources/js
diff --git a/src/main/webapp/resources/js/shib/idpselect.js b/src/main/webapp/resources/js/shib/idpselect.js
index b1ff425..28286f2 100644
--- a/src/main/webapp/resources/js/shib/idpselect.js
+++ b/src/main/webapp/resources/js/shib/idpselect.js
@@ -1321,7 +1321,7 @@ function IdPSelectUI() {
             idpData = JSON.parse(jsonData);
 
         }else{
-            fatal(getLocalizedMessage('fatal.loadFailed') + dataSource);
+            fatal(getLocalizedMessage('fatal.loadFailed') + dataSource); // here
             return false;
         }
         return true;
@@ -2212,7 +2212,7 @@ function IdPSelectUI() {
     */
 
     var fatal = function(message) {
-        alert('FATAL - DISCO UI:' + message);
+        alert('FATAL - DISCO UI:' + message); // here
         var txt = document.createTextNode(message); 
         idpSelectDiv.appendChild(txt);
     };
diff --git a/src/main/webapp/resources/js/shib/idpselect_config.js b/src/main/webapp/resources/js/shib/idpselect_config.js
index b83809b..a62adbd 100644
--- a/src/main/webapp/resources/js/shib/idpselect_config.js
+++ b/src/main/webapp/resources/js/shib/idpselect_config.js
@@ -42,7 +42,7 @@ function IdPSelectUIParms() {
             'fatal.wrongProtocol': 'Policy supplied to DS was not "urn:oasis:names:tc:SAML:profiles:SSO:idpdiscovery-protocol:single"',
             'fatal.wrongEntityId': 'entityId supplied by SP did not match configuration',
             'fatal.noData': 'Metadata download returned no data',
-            'fatal.loadFailed': 'Failed to download metadata from ',
+            'fatal.loadFailed': 'Failed to download metadata from ', // here
             'fatal.noparms': 'No parameters to discovery session and no defaultReturn parameter configured',
             'fatal.noReturnURL': "No URL return parameter provided",
             'fatal.badProtocol': "Return request must start with https:// or http://",
```

**Comment by mheppler** [comment]
Gave to @scolapasta to review in the "In Review - 4.0" milestone.

This isn't just swapping out the text displayed in the modal popup - but thank you, @pdurbin for digging that up.

As I said in my email, "(when there is a FATAL error from Shib) we need to have our built-in login displayed so the majority of our users can access the site, and not a modal popup that covers the entire screen with some "disco" developer-nerd "FATAL" message... Ideally, it fails silently on the UI, or displays a little text blurb in the Institution Log In block that is a little more subtle."

**Comment by mheppler** [comment]
In the spirit of the good work being done in the prioritization meetings, I have compromised the most of the UX problems initially reported in this issue, and just changed the text of the modal popup to "Internal Error".

Disco is dead.

![screen shot 2016-05-17 at 10 17 02 am](https://cloud.githubusercontent.com/assets/687227/15328283/534091f0-1c22-11e6-88bc-5f46dc0429a1.png)

**Comment by kcondon** [comment]
Updated as described, closing.
