### ISSUE TITLE
Custom Fields

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#1765]
Post 4.0 assessment of custom fields migration

**Comment by sbarbosadataverse** [comment]
GSD
ARCS
Political Science Replication Initiative
Digaii
CHIA

**Comment by posixeleni** [comment]
@ekraffmiller @scolapasta for me to properly QA this is it possible for you to let me know when these Dataverses with their Datasets have been migrated over? I know this is set for post-deployment of 4.0 but if you do migrate these to dvn-5 or some other place ahead of time please let me know so I can catch any issues ahead of time.

Thanks!

**Comment by posixeleni** [comment]
@sbarbosadataverse Would you please review these when you get the chance?

**Comment by sbarbosadataverse** [comment]
Can close for now. Update custom fields/values as requested by users.
