### ISSUE TITLE
Customization

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#1768]
Customizations
Released dataverses with customizations (n=379): (Dwayne-complete) 
 https://drive.google.com/open?id=1d_wUapwS1yhgPi4nQphwRK71MnYzGDBzkBeonBS9zgY&authuser=0
Unreleased dataverses with customizations (n=135): (Dwayne)
https://docs.google.com/spreadsheets/d/1bftyXi_CeFlylMSebSsnHcyHXnoT1VmVk7CZ5cdJHoM/edit#gid=0

Pre 4.0 - Dwayne will contact those created between 2013 and present (with data?) first
contact all post 2013 to see if still viable, delete or customize based on reponse (Kevin will query for mailing list of both groups)

**Comment by mcrosas** [comment]
Manual customizations to be done after migration (move issue to Dwayne after automation).

Most of them will be restored from saved customizations backup.

**Comment by mcrosas** [comment]
@dliburd On Monday, after all customizations have been copied, and migration + iindexing is complete, you can update any customizations that need manual changes. Check with @scolapasta  when this is ready

**Comment by dliburd** [comment]
Will do.

**Comment by dliburd** [comment]
I've completed the customization of released Dataverses that were embedded in 3.6.
