### ISSUE TITLE
Individual Dataverse Needs for 4.0

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#1772]
Townsend:
-restricted datasets moved as unpublished except for cases that they are removing from 3.6; 
-they have a selection to move as “unpublished.”

Contact individual Dataverses to let them know if we had to slightly transform their data for it to validate during migration. Gustavo will give me a list of Dataverses. (Eleni)
 
Center for International Forestry Research Dataverse 
 will remove from Harvard Dataverse (they are requiring help with migrating to their own installation: http://data.cifor.org/dvn/) - Kevin

*Ask them if they would like to be listed on dataverse.org--waiting on reply (Sonia)

**Comment by mcrosas** [comment]
Check after migration that dataset that were under unpublished dataverse are now unpublished.

**Comment by sbarbosadataverse** [comment]
Sanity check done! Looks awesome
