### ISSUE TITLE
Create Account: Sign up page validation not happening unless email field is completed.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1773]
Field validation for the sign up page is happening but not in all cases, leaving the impression in those cases it is not working properly at all.
1. Enter any combination of fields but do not fill in the email field and no validation occurs. 
2. Enter any combination of fields and do fill in the email field and validation occurs.

**Comment by sekmiller** [comment]
Fix is checked in

**Comment by posixeleni** [comment]
Validation occurs when email field is not filled in:
![image](https://cloud.githubusercontent.com/assets/5013837/6873206/24da142a-d485-11e4-930d-f7e2129f9e61.png)

Working as expected. Closing this ticket.
