### ISSUE TITLE
Google Analytics -- Track Social Shares/Interactions

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1774]
With the Sharrre social media sharing plugin added to dataverses and dataset in ticket #449, we should be tracking these shares/interactions in our Google Analytics.

Ref: http://sharrre.com/track-social.html
Ref: https://developers.google.com/analytics/devguides/collection/analyticsjs/social-interactions

**Comment by eaquigley** [comment]
Notes from discussing with @mheppler:
- [ ] sharre instructions above is outdated
- [ ] need to use code from google analytics link
- [ ] will put in the code for facebook and twitter so we can try it out and see if it works
- [ ] need to also add that code into the Tracking Code information on Google Analytics so it works

**Comment by mheppler** [comment]
OK. Updated Google Analytics code on dataverse_template, to track social interactions (send, tweet) with Facebook and Twitter. Updated the account UA number to track on dvn-build.
````
ga('create', 'UA-3745567-8', 'harvard.edu');
          ga('send', 'pageview', {
            'hitType': 'social',
            'socialNetwork': 'facebook',
            'socialAction': 'send',
            'socialTarget': '#{systemConfig.dataverseSiteUrl}',
            'page': '#{systemConfig.pageURLWithQueryString}'
          }, {
            'hitType': 'social',
            'socialNetwork': 'twitter',
            'socialAction': 'tweet',
            'socialTarget': '#{systemConfig.dataverseSiteUrl}',
            'page': '#{systemConfig.pageURLWithQueryString}'
          });
````

**Comment by mheppler** [comment]
Related to #1594. All of our analytics code in dataverse_template is related to harvard.edu, and this needs to be moved into a systemConfig setting that is configurable per installation.

**Comment by eaquigley** [comment]
So this is turning out to be a bigger situation. The Sharres aren't being counted properly in the UI but it is showing in Google Analytics so that is GREAT NEWS. I am closing this ticket and opening another one to review Sharres and look into other options.
