### ISSUE TITLE
Dataset, Upload + Edit Files, Advanced Options - Any Edit Removes Categories

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1775]
When adding a tabular data tag or setting an image to be the default thumbnail -- any action from the Advanced Options popup -- it will remove the pre-existing category assigned to that file.

**Comment by mheppler** [comment]
Additional Advanced Options bugs:

When you Save

**Comment by landreev** [comment]
I'm going to check in a fix for this, and 1776, shortly.

**Comment by landreev** [comment]
Please test, should be working properly now. 
Designating an image as the dataset thumbnail should not be erasing any existing file categories; 
same for the "tabular tags" (they are now in the same popup as the "tab. tags")
