### ISSUE TITLE
Breadcrumbs - Need a way to include a link for a Page that is not a dvObject

### ISSUE THREAD

**Issue by sekmiller** [IQSS/dataverse#1778]
The View Guestbook Responses page is kicked off from a button on the Manage Guestbooks Page.  The breadcrumbs on View GB Responses only have a link back to the dataverse that owns the Guestbook.  There's no easy way to get back to the Manage Guestbooks page.  We need a way to put in a link back to this page as a general solution for other instances where you may be in several layers of pages.

**Comment by mheppler** [comment]
Looks like this was fixed back in May '16 in #3122 which was released as part of 4.4.

![Screen Shot 2019-06-17 at 2 25 45 PM](https://user-images.githubusercontent.com/687227/59627273-d2464880-910b-11e9-93d7-c04b300bdf54.png)
