### ISSUE TITLE
Post migration: Move groups to appropriate dataverses

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#1779]
In 3.6 groups existed at the installation level, so they will all belong to the root post migration.

We need to review the groups and manually move them to the appropriate dataverse level (for example, PSI can go to PSI dataverse).

**Comment by scolapasta** [comment]
Worked with @sbarbosadataverse and this is all set, except for one (PSI Research and Metrics), which @sbarbosadataverse is investigating.

 Note, this was not a code change, but a production curation task.

**Comment by scolapasta** [comment]
Done - we deleted that last group (per Dana @ PSI).

**Comment by pdurbin** [comment]
It looks like this ticket should be in QA so I'm adding that label.

**Comment by kcondon** [comment]
Closing. Need to add to migration notes.
