### ISSUE TITLE
Notifications: Weird display of Xs

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1780]
Noticed on dvn-build that two Xs near the bottom were oddly displaying and weren't in line with their notifications.

![notificationsbug](https://cloud.githubusercontent.com/assets/5922904/6855930/c5b960d4-d3d2-11e4-944b-dbfb75d097aa.png)

**Comment by mheppler** [comment]
@eaquigley -- which browser are you in. This isn't appearing for me in any of my browsers on a Mac.

It looks like the "x" from the previous row is getting pushed down, which will be a simple CSS fix.

**Comment by eaquigley** [comment]
@mheppler I was using chrome.


On Mar 27, 2015, at 8:41 AM, Michael Heppler <notifications@github.com<mailto:notifications@github.com>> wrote:


@eaquigley<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_eaquigley&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=Y9aY3P6kFFpmMLaYYO_id08dS3gL1xWMQuI2CZ74PoI&m=Vb_U3DZLW6lt-5WtL_aw8tuzDWqODILU313yEML9dZY&s=YheNWKVYEXcYpKZ04_2MtIxiXOqqzgSqFtVUeA4QZak&e=> -- which browser are you in. This isn't appearing for me in any of my browsers on a Mac.

It looks like the "x" from the previous row is getting pushed down, which will be a simple CSS fix.

**Comment by mheppler** [comment]
Cleaned up markup and styling of notification items on Account page, to fix bug in Windows Chrome.

**Comment by eaquigley** [comment]
Looks good. Closing ticket.
