### ISSUE TITLE
Issue with Tooltips Sticking

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#1781]
When testing the Guestbook at the Dataverse-level if you click on the "View" the guestbook and then "x" out of it the black help text "View" tooltip stays displayed / frozen even when I go to hover over the other Guestbook options.

@mheppler commented in https://github.com/IQSS/dataverse/issues/1477#issuecomment-86697512 that this is a site wide issue that will need a site wide solution not just for guestbook.

**Comment by mheppler** [comment]
I found this ticket, and saw that it was a quick fix. A fix for this same issue on the Manage Groups page, was committed 40e63a3fe1ca53929315f89e68d2e43c54fbedc1 that allows this bug to be easily fixed on other pages. I searched through the project for other buttons that have tooltips, and it appears that this issue doesn't effect those pages.

**Comment by sekmiller** [comment]
Added the fix to the Manage Templates page.  Will check it in when general work on the page (pertaining to adding Terms of Use and Access to Templates.) has been completed.

**Comment by kcondon** [comment]
This ticket is intended to be for all sticking tooltips, not just templates. I did other places that had separate tickets that were consolidated into this: add/ delete email for dv contact, guestbook, templates. So, will close this as it is very open-ended but will open fresh, new, specific tickets if I see places where this occurs such as edit dataset, etc.
