### ISSUE TITLE
inherited metadata block: if you unselect to "inherit" a block, the metadata block should no longer be "checked"

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#1785]
I unselected the "inherit" option, but the check still remains next to "journal" metadata block.

![ga50ouzjhl0zteahpkztyuuetceu3-5zwfokj1llmog](https://cloud.githubusercontent.com/assets/8322346/6872759/911202b4-d481-11e4-9059-f0b9b57f6694.png)

**Comment by sekmiller** [comment]
The intent of the unchecking inherit is that you start out with the inherited blocks, but you may then change them.

**Comment by scolapasta** [comment]
Exactly, disinheriting "unlocks" you from the parent, but the base you start out as is that.

**Comment by sbarbosadataverse** [comment]
according to comments, this is working as designed.
