### ISSUE TITLE
inherited metadata block/missed required field combination : if you miss required field, you can't unselect "inherited" block until you correct and save "required" field

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#1786]
If you miss a "Required" field, and hit save, you get the missing field validation error.
If you correct the error, but don't save immediately" then move to metadata blocks and try to "unselect" inherited block, it doesn't let you do so

![hqbioqtirsmanv5ktr4b-ujy-a1geq51df9dbhnezbo](https://cloud.githubusercontent.com/assets/8322346/6872961/4c6a4f0c-d483-11e4-926a-059fab32df4d.png)

**Comment by sekmiller** [comment]
I see this happening.  I don't know the cause yet.

**Comment by sekmiller** [comment]
Fix is checked in. Build required for testing

**Comment by sbarbosadataverse** [comment]
works!
