### ISSUE TITLE
Install: Setup-optional-harvard has two errors

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1788]
{"status":"ERROR","message":"Problem with API token: Could not find user from API token."}
- Setting up the MIT Shibboleth institutional group
{"status":"ERROR","message":"Problem with API token: Could not find user from API token."}

**Comment by scolapasta** [comment]
@michbarsinai since you're moving the groups to admin, can you look at this? I asked @pdurbin and he said he added key requirements in the code, s they just need to be removed (and the the script updated with the new /admin path)

**Comment by kcondon** [comment]
Works, closing.
