### ISSUE TITLE
Includes - XMLNS Attributes in DIV Containers

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1790]
Rather than using DIV tags as containers for includes with the XMLNS attributes, use ui:composition tags instead, to avoid the XMLNS attributes ending up in the source code.

Ref: http://stackoverflow.com/questions/4792862/how-to-include-another-xhtml-in-xhtml-using-jsf-2-0-facelets

H/T: @raprasad

**Comment by mheppler** [comment]
- [x] dataverse_header
- [x] contactFormFragment
- [x] permissions-configure
- [x] guestbookResponseFragment
- [x] gui_subset
- [x] metadataFragment
- [x] search-include-fragment
- [x] termsofuse

**Comment by mheppler** [comment]
Improved code of includes to be wrapped in ui:composition tags, and not div tags.

**Comment by kcondon** [comment]
@posixeleni Just test the above areas to make sure they still work.

**Comment by posixeleni** [comment]
assigning to @kcondon since I will not be able to complete this QA
