### ISSUE TITLE
Dataverse Footer - Twitter, GitHub Logo Images + Page Load

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1792]
Remove the Twitter and GitHub logo images from the footer, and utilize the vector based social media icons from Socicon, that were added to the app for the share functionality.

**Comment by mheppler** [comment]
Swapped out Twitter and GitHub image logos from the footer for vector icons.

**Comment by posixeleni** [comment]
Confirmed that the logos have been swapped out in build. Closing this ticket.
