### ISSUE TITLE
Create Dataverse: No Edit or Publish buttons on a new dv created by new user.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1794]
First reported by Mike:

1. Create new user account.

2. Create dataverse on Root.

3. No "Edit" or "Publish" button on dataverse page, but there is a mocking "success" message.

4. Can create a dataset in that dataverse though, and get "Publish" and "Edit" buttons for that.

5. Go to publish the dataset and get warned that I can't because the parent dataverse isn't, but asked "Would you like to publish both right now?" So I click, "Yes, Publish Both".

6. I get a success message that the dataset was published, and the dataverse was too, because the "Unpublished" label is gone from the header.

7. Go back to the dataverse page, and still no "Edit" button.

**Comment by mheppler** [comment]
This is now happening locally, for all users, "Admin Dataverse" included, all dataverses, new and previously existing.

**Comment by scolapasta** [comment]
Should be fixed.

**Comment by kcondon** [comment]
Works, closing @mheppler
