### ISSUE TITLE
review logic for setting displayimage (for search cards) to see if it can be more efficient

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#1796]

**Comment by pdurbin** [comment]
@scolapasta @landreev was this re-addressed in #3852? Are we all set?

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
