### ISSUE TITLE
Clean up docs directory

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#1797]
Looking at the docs, we have several things in there that we probably don't need as "official" docs for release.

Let's review and clean this up.

Example:
the  /doc/gui/ingest/language_encoding/ directory.

**Comment by scolapasta** [comment]
Handing first to @landreev, but this may need to be reviewed by several developers.

**Comment by landreev** [comment]
I cleaned the doc files that were mine, that were no longer needed.

**Comment by mheppler** [comment]
There seem to be only a few remaining stragglers in the `docs` directory left to clean up.

- /doc/Architecture/
- /doc/mergeParty/
- /doc/shib/
- /doc/theTestableCommand/
- /doc/JAVADOC_GUIDE.md
- /doc/dv refactoring notes.md

@pdurbin, @michbarsinai -- I see your finger prints on a lot of these. Is there a more appropriate place for this information to be saved then the `doc` directory?

**Comment by pdurbin** [comment]
@mheppler yeah, all this stuff should probably go in the Dev Guide. A lot of it is good and current, even new.

**Comment by pdurbin** [comment]
@michbarsinai please take a look at a299f8a where I added a link to your `TheTestableCommand.md` file. At some point, this Markdown content should be converted to reStructuredText and added to the "Testing" section but I'm considering this out of scope for issue #3431 and pull request #3892 unless you care to take it on.

**Comment by michbarsinai** [comment]
I'll try to handle this during the next few days, but I don't want to block this issue form being solved. You can create a new issue about this and assign it to me if you want .

**Comment by pdurbin** [comment]
@michbarsinai yeah, let's treat it as a small chunk in a new issue to merge the testable command content into the dev guide. @ferrys wrote https://github.com/IQSS/dataverse/blob/277634356f398d3bd6d1ea0dae86c45c87bc3d2b/src/test/java/edu/harvard/iq/dataverse/engine/command/impl/RestrictFileCommandTest.java based on what I wrote but she said she found your content useful as well. She didn't know about it until I pointed it out.

**Comment by pdurbin** [comment]
@scolapasta can we close this? I agree that the work needs to be done but we're reminded every time we write docs and `cd` into the directory. Also, I don't think QA has a role in this.

**Comment by pdurbin** [comment]
I don't see any value in keeping this issue open. Closing. If anyone feels strongly, I could roll a fix or two into pull request #4502. Lemme know.
