### ISSUE TITLE
Download terms don't go away once you hit accept, nor when you cancel from two ravens

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#1799]
The dialogue box stays open--should disappear once you accept and go into two ravens. If you "x" out of two ravens, box still appears underneath two ravens dialogue box

![1rfdfsj5tb5bdon74_g7coiu650hy5hahmadpdkhjko](https://cloud.githubusercontent.com/assets/8322346/6900095/4424f184-d6d2-11e4-9a45-e876ce123d82.png)

**Comment by sbarbosadataverse** [comment]
Image stays open under Two Ravens

![lnmt4zg4u2rfvzaz9eowx2aifuadwjuuam_hq5jmjtu](https://cloud.githubusercontent.com/assets/8322346/6900122/6f4b01c8-d6d2-11e4-9261-eeafa82b0213.png)

**Comment by scolapasta** [comment]
Duplicate of #1742

**Comment by kcondon** [comment]
Dupe, closing
