### ISSUE TITLE
Restricted File Icons placement

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#1801]
The icon is far removed from the file name. Does it make sense to put it right next to the file names, preceding the file name?

![ahheqdv5yct9wfhx8cbd82zo0fu-qltq8oiwykohjry](https://cloud.githubusercontent.com/assets/8322346/6900676/228078ce-d6d6-11e4-86d0-a55834825aed.png)

**Comment by scolapasta** [comment]
Assigning to In Design so we can decide if we are happy with what we have or want to move it,

**Comment by eaquigley** [comment]
Plan is to move the lock icon to be inline with the name rather than over in the corner.

**Comment by mheppler** [comment]
![screen shot 2015-06-29 at 5 34 10 pm](https://cloud.githubusercontent.com/assets/687227/8419057/14afaa8e-1e85-11e5-9549-5d142489b5c4.png)

**Comment by mheppler** [comment]
Moved restricted lock icons to the upper left corner of the file browse/search card, inline with the file title.

**Comment by dliburd** [comment]
Icons are still in the lower right of the icons.

Tested on The Dataverse Project
v. 4.1 build 36

**Comment by mheppler** [comment]
@dliburd -- are you looking at the dataverse page (see attachment in comment above) or the dataset page? I only moved the icons on the dataverse page. The dataset page layout for files is being reviewed in an upcoming release.

**Comment by dliburd** [comment]
@mheppler Sorry about that. Good day, good sir.

Verified: Restricted file icons moved to the upper left corner of the file browse/search card, inline with the file title.
