### ISSUE TITLE
Meta Description Tag: Have Better Description of Dataverse 

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1802]
When a user shares a dataverse or dataset via facebook or google plus, we need to have a standard message appear that says what Dataverse is. @mheppler please add this: 

The Dataverse Project is an open­ source software application to share, cite and archive data. Dataverse provides a robust infrastructure for data stewards to host and archive data, while offering researchers an easy way to share and get credit for their data.

**Comment by mheppler** [comment]
Looking lots better!

![screen shot 2015-03-30 at 1 52 15 pm](https://cloud.githubusercontent.com/assets/687227/6903069/ca66f36a-d6e5-11e4-897b-01f45dcbf467.png)

**Comment by eaquigley** [comment]
@mheppler I'm seeing the right message for Twitter and Google Plus but for some reason, Facebook still isn't showing the correct one.
