### ISSUE TITLE
Permissions Issue: Unable to add a Dataset as an Authenticated User Contributor

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#1803]
In build I setup the "Eleni Is Testing" https://dvn-build.hmdc.harvard.edu/dataverse/el-test Dataverse permissions to allow anyone with a Dataverse Account to Add Datasets as a Contributor.

![image](https://cloud.githubusercontent.com/assets/5013837/6905828/bc41d044-d6f8-11e4-8f99-0e63f9f199e5.png)

However, when I login as an authenticated user (through shibboleth or regular login) I do not see the "Add Data" button. I only see this when I logged in as Super User.

![image](https://cloud.githubusercontent.com/assets/5013837/6905862/f288a11e-d6f8-11e4-821b-fc15f7e2a646.png)

**Comment by posixeleni** [comment]
To see if this issue can be repeated, I created another Dataverse https://dvn-build.hmdc.harvard.edu/dataverse/tj with a different user and put the same permissions in as before. When I log in as a different authenticated user I am unable to see the Add Data button in this dataverse as well.

**Comment by scolapasta** [comment]
Fixed - when rendered logic was moved to permissionsWrapper, the wrong command was being checked.

**Comment by posixeleni** [comment]
Now working as expected. Closing this ticket.
