### ISSUE TITLE
Can't remove user access to a restricted file in a dataverse

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#1805]
I assigned Eleni to a restricted file a few days ago--tried to delete her today in the "user group" and "files" section, it appears to work, but does not~

![sr3s8ioyhfkodzaupuowvpsli1cnkr32nahpam_rsyy](https://cloud.githubusercontent.com/assets/8322346/6906634/1eee65c2-d6fe-11e4-8fae-ef8bbc73fde9.png)

![revmfrvnsq-ilfxy1tcz8rzuc5n6hwh-sor6xpyyf4e](https://cloud.githubusercontent.com/assets/8322346/6906635/204a98a0-d6fe-11e4-9da4-9debced509e3.png)

![ey9cle_9fa-nnqb_7hqmkmvmgwsszbmjasjkneb0oqa](https://cloud.githubusercontent.com/assets/8322346/6906637/21f3a4b2-d6fe-11e4-8721-fc387bfc2bfe.png)

**Comment by scolapasta** [comment]
One of the type="button" issues (#1847). Fixed.

**Comment by sbarbosadataverse** [comment]
successfully removed a user with access to restricted file
