### ISSUE TITLE
Can't delete a unpublished dataverse that has linked to another dataverse or dataset

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#1812]
If you link a dataset or dataverse to an unpublished dataverse and then try to delete that unpublished dataverse, you will see "Error – This dataverse was not able to be deleted. Please contact support" in the screenshot below and the following stacktrace:

![root_dataverse_-_2015-03-31_11 26 17](https://cloud.githubusercontent.com/assets/21006/6922430/12b27d2a-d799-11e4-862b-0e60a5c9c57b.png)

Caused by: org.postgresql.util.PSQLException: ERROR: update or delete on table "dvobject" violates foreign key constraint "fk_dataverselinkingdataverse_linkingdataverse_id" on table "dataverselinkingdataverse"
  Detail: Key (id)=(278) is still referenced from table "dataverselinkingdataverse".

This was observed on dvn-build v. 4.0 Beta build 987.

Related: #1364

**Comment by pdurbin** [comment]
A related problem is that while the dataverse is not deleted the Solr document is, which means you can't easily find the dataverse again. In this case on dvn-build I went to https://dvn-build.hmdc.harvard.edu/api/admin/index/dataverses/278 to re-index the dataverse so it can be found. (I could have done an "index all" as well, of course.)

**Comment by scolapasta** [comment]
Since linked dataverses and datasets are superuser only for 4.0, we should be able to manage this behavior.

**Comment by scolapasta** [comment]
We need to make sure the cascades are set correctly.

**Comment by sekmiller** [comment]
Cascades are set for facets, linking dataverses, featured dataverses, and linked datasets.  Some more work required for subjects

**Comment by scolapasta** [comment]
Actually subject is all set, as it is not an entity but just a many to many relationship.

**Comment by kcondon** [comment]
Tested, works, closing
