### ISSUE TITLE
Saved Search: Automatically Create A Dataverse When Generating A Saved Search

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#1813]
Hi @eaquigley 

@pdurbin and I have been trying out how Saved Search (#90) will work in 4.0 and already found a usability issue that we would need to prioritize for development.

The issue is that someone would need to manually create a Dataverse ahead of time in which to place their Saved Search in. 

An easier workflow would be to allow the user be able to create the Dataverse at the SAME time as they create the Saved Search.

**Comment by eaquigley** [comment]
If we were to add this functionality in, we would also need to add it for linked dataverses/datasets since they are similar functionality and I would want the workflows to be similar.

**Comment by posixeleni** [comment]
@eaquigley so from the Linked/Saved Search workflow have the option to:

A. Link to a pre-existing Dataverse
B. Create a New Dataverse

**Comment by eaquigley** [comment]
Functional Requirements Document for Linked Search: https://docs.google.com/document/d/1dmxs4XIQkrn9QfP4Ih4wIbyARUyWFJflJk3y4W3nzXk/edit?usp=sharing

**Comment by eaquigley** [comment]
Moving back to In Review. We've discussed this and it is a nice to have feature that will take some more time to figure out how to make it work. Would probably be best to do this once we have the ability to move dataverses and datasets implemented.

**Comment by pdurbin** [comment]
In helping with the Harvesting feature (#813) I was reminded of this issue and how Harvesting is another area where it would be nice to have a workflow that supports a dataverse being created when you're setting up a harvesting client. Right now you have to stop what you're doing and go create a dataverse first:

![screen shot 2016-08-16 at 10 32 38 am](https://cloud.githubusercontent.com/assets/21006/17702707/fbf7402a-639c-11e6-8c45-f2288f19e388.png)
