### ISSUE TITLE
Crosswalk for Importing Datasets From NARA Into Dataverse

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#1814]
Working with NARA https://dataverse.harvard.edu/dataverse/nara to develop a crosswalk for us to be able to ingest metadata for their studies into Dataverse. They are a Data-PASS member.

This is the NARA export of batch datasets which contains 887 records (https://www.dropbox.com/s/ule0djqytersv8v/lgoodsell_150505103739_concat.tar.gz?dl=0) that we need to import into dataverse like we do for harvested datasets. They have their own custom XML so I worked with NARA to put together the proper mapping from their schema to our internal dataverse metadata https://docs.google.com/spreadsheets/d/1prBLBsmf4HmPiehFTq7oL8YciA0uzLTD4ZVXOSHGBgc/edit#gid=0

Some imp. information about these datasets:
- The files/data will live on the NARA repository but we will have a link back to NARA to access data (similar to other harvested datasets)
- It would need to be updated with an XML file once or twice a year. NARA would send us this file. This file would include ALL records not just new, updated or deleted. So we would just need to reload all their datasets each time.

**Comment by posixeleni** [comment]
Designing the Crosswalk here: https://docs.google.com/spreadsheets/d/1prBLBsmf4HmPiehFTq7oL8YciA0uzLTD4ZVXOSHGBgc/edit#gid=0

**Comment by posixeleni** [comment]
Completed crosswalk and sent to NARA to review

CC/ @mcrosas

**Comment by posixeleni** [comment]
Completed crosswalk w/ NARA but waiting for them so send us some sample data so we can test mapping once the code is implemented

**Comment by posixeleni** [comment]
@scolapasta this is the NARA export of batch datasets (https://www.dropbox.com/s/ule0djqytersv8v/lgoodsell_150505103739_concat.tar.gz?dl=0) that we need to import into dataverse like we do for harvested datasets. They have their own custom XML so I worked with NARA to put together the proper mapping from their schema to our internal dataverse metadata https://docs.google.com/spreadsheets/d/1prBLBsmf4HmPiehFTq7oL8YciA0uzLTD4ZVXOSHGBgc/edit#gid=0

@mcrosas can comment on the priority of this ticket

**Comment by mcrosas** [comment]
Medium priority for now, but soon will be High - since it's needed for DataPASS

**Comment by posixeleni** [comment]
@scolapasta @mcrosas my mapping work for this has been completed but we need help from development to make this custom harvested datasets available in Dataverse. Since this relates to DataPASS what would the priority for this be?

**Comment by mcrosas** [comment]
Eleni, could you add this in the export/harvesting BRD? Harvesting of NARA
data is a business requirement, so support of this the crosswalk should be
part of this. I forgot it in the BRD.


Mercè Crosas, Ph.D.
Chief Data Science and Technology Officer, IQSS
Harvard University
http://scholar.harvard.edu/mercecrosas

**Comment by posixeleni** [comment]
Will do. Thanks.

Eleni Castro
Research Coordinator, IQSS
Harvard University

**Comment by pdurbin** [comment]
This issue reminds me a lot of #3632 and #3083.
