### ISSUE TITLE
Astronomy Metadata: Add Support for Unified Astronomy Thesaurus

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#1815]
Requested by the CfA group to add the Unified Astronomy Thesaurus as a controlled vocabulary field in Dataverse's Astronomy Metadata block. http://astrothesaurus.org/

Can work with Katie Frey when we are ready to implement this. Can start with this flat file: https://drive.google.com/file/d/0BzeLxEN77UZoRGVnS2VQZDVNOUk/view?usp=sharing but will follow-up with Katie to make sure there havent been any updates/changes.

**Comment by bencomp** [comment]
Just to confirm: is this thesaurus *not* a subject thesaurus? If the function of the terms in this thesaurus in dataset metadata was to indicate subject terms, they would surely be used in the Subject field?

**Comment by posixeleni** [comment]
@bencomp its a subject thesaurus that is specific to "astronomical concepts and their inter-relationships" and contains thousands of terms.

For 4.0 the Subject field is currently being used only to classify at a very high-level what major discipline(s) the dataset covers and is not meant to be as granular as this thesaurus would allow. We may in the future decide to merge this discipline-specific thesaurus with the larger Subject field but for now we will plan to have it only in the Astronomy metadata since only Astronomers and Astrophysicists would choose this thesaurus.

**Comment by bencomp** [comment]
@posixeleni hmm, I see that I really meant *keyword field*, oops. Subject terms from this thesaurus, I my humble opinion, could be entered in the keyword field, with the URL of the thesaurus in the vocabulary URL subfield. (I was confusing *subject* with *keyword*, maybe because I thought of LCSH. LCSH is mentioned as a potential source of keywords for the keyword field, and the UAT appears to have a similar function within a particular field.)

**Comment by posixeleni** [comment]
@bencomp thanks for clarifying. We will have to review this after 4.0 to see if we can support options for indexing multiple controlled vocabularies in the Keyword field. At the moment it is a free-text field which allows for any term / vocabulary to be manually entered. Our system is not currently setup to allow users to choose from different vocabularies/ontologies/thesauri (like LCSH, MeSH, UAT, etc).

**Comment by mcrosas** [comment]
This will also be a critical feature for life sciences metadata - supporting multiple controlled vocabularies for one field.

**Comment by pdurbin** [comment]
Related to #434.

**Comment by pdurbin** [comment]
These days I'm hoping this can be implemented here: https://github.com/gdcc/dataverse-external-vocab-support
