### ISSUE TITLE
Dataverse - Edit General Information - Improve Layout of "Dataverse" and "{dataverseSiteUrl}"

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1817]
The light grey text for "Dataverse" and "{dataverseSiteUrl}" next to the inputs for Dataverse and Identifier respectively, need to improve in order to stand out a little more.

**Comment by mheppler** [comment]
Change the style from grey "muted" text, to a styled "input-group-addon" form component from Bootstrap. Adjusted the padding of the entire form around it, to give it some more room.

**Comment by eaquigley** [comment]
Looks great. Closing ticket.
