### ISSUE TITLE
Implement a way for tools to get a token for a user given username and password

### ISSUE THREAD

**Issue by astrofrog** [IQSS/dataverse#1818]
A third-party tool, for example glue (http://www.glueviz.org) could take a username and password then request the API token from a dataverse server - which would then allow the tool to access data on the dataverse.

Better though would be if the third-party tool doesn't have to deal with username and passwords but simply launches a browser to a specific location where the user has to log in to the dataverse, and the third-party tool then has a way to retrieve the token (edit: I think what OAuth does). However, this could be more complex.

For the first, one could have a JSON endpoint that takes (over https) the username and password and returns the API token.

**Comment by rliebz** [comment]
:+1:

**Comment by astrofrog** [comment]
Just out of curiosity, is there any chance this could be squeezed in to the 4.0 API, or will it have to wait for a future version?

**Comment by pdurbin** [comment]
@astrofrog I just flagged this ticket for review at least. I asked if anyone had security concerns at http://irclog.greptilian.com/rest/2015-03-31#i_106173

**Comment by scolapasta** [comment]
@michbarsinai is it possible to get this fixed by EOD tomorrow (Thursday)? Otherwise we can move this to 4.0.1.
