### ISSUE TITLE
Dataset Deaccession - Entering Reason + URL Gives NullPointerException

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1819]
If you select "Other..." and type a reason, and provide a URL, you can't deaccession a dataset, because it throws a 500/NullPointerExeption.

Just selecting a reason from the dropdown, and only that, succeeds.

**Comment by sekmiller** [comment]
The "select other" was the key to solving this.  Thanks Mike.  Fix is checked in.

**Comment by kcondon** [comment]
Works, closing.
