### ISSUE TITLE
Make breadcrumb trees dynamic

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#182]
---

Author Name: **Gustavo Durand** (@scolapasta)
Original Redmine Issue: 3594, https://redmine.hmdc.harvard.edu/issues/3594
Original Date: 2014-02-26
Original Assignee: Gustavo Durand

---

Right now the trees in the breadcrumbs  all load at once, but if we decide to keep this functionality, we should make the trees load dynamically, only getting the branches that need to be shown. This is critical for performance.

---

Related issue(s): #128
Redmine related issue(s): [3537](https://redmine.hmdc.harvard.edu/issues/3537)

---

**Comment by eaquigley** [comment]
If there are "many" dataverses under root, should the breadcrumb functionality change?

Please see attached screenshot with dozens of dataverses under root.
![7f5eaf80-0e7b-11e4-8baa-12a56250a3be](https://cloud.githubusercontent.com/assets/5922904/8530344/7fef5d12-23ee-11e5-975b-dcaa2694364c.png)

**Comment by kcondon** [comment]
This has some significant technical challenges that make it unlikely to be implemented.
