### ISSUE TITLE
API endpoint for dataverse metadata blocks crashes when gets ints in the array

### ISSUE THREAD

**Issue by michbarsinai** [IQSS/dataverse#1821]
Must escape them:

    curl -X POST -H"Content-type:application/json" -d "[\"1\",\"2\",\"5\"]" http://localhost:8080/api/dataverses/1/metadatablocks/?key=$KEY

Not stringing the ints fails over class cast exception, waiting for JsString rather than JsNumber.

**Comment by scolapasta** [comment]
@michbarsinai is it possible to get this fixed by EOD tomorrow (Thursday)? Otherwise we can move this to 4.0.1.

**Comment by michbarsinai** [comment]
Now, even this works (note that there's a duplicate block):

    curl -X POST -H"Content-type:application/json" -d "[1,2,\"geospatial\"]" http://localhost:8080/api/dataverses/1/metadatablocks/?key=$KEY
