### ISSUE TITLE
Dataset Page: Metadata Display.  Need More Efficient Method (solr, json, etc)

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#1822]
Reconstruct Metadata values for display is costly in terms of queries that shoot to the top of the profiler*
(\* 2nd after #1820)

Solr documents already contain metadata for display.  Use these instead.

Longer terms:  Save Metadata values as JSON (even if put into a Postgres field)

**Comment by pdurbin** [comment]
> Solr documents already contain metadata for display.

While this is true for the most part, the data you get out of Solr is flat key/value pairs. You lose all the hierarchy of compound fields.

**Comment by raprasad** [comment]
(updated based on @pdurbin  comments)

Short term strategy:
- [ ] create table **DatasetMetadataDisplay** (or something similar)

|dataset id|dataset version id|json metadata|timestamp|
|-----------|-----------|-----------|-----------|

- [ ] For each version of metadata fields,  look to the table above for info.
- [ ] If not found:
  - Construct display metadata the current way
  - Save the constructed metadata as JSON to the table above, including citation block hierarchy.
  - Look at field ordering.  Either put in JSON, or set field ordering dynamically...)
- [ ] If found:
  - Update the DatasetPage.java / dataset.xhtml to use JSON as citation block metadata source

**Comment by scolapasta** [comment]
No plan to do this for now. Can reopen, if/when we do.
