### ISSUE TITLE
Account Page: Error Message Redundancy 

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1824]
@mheppler can you please change the error message that appears when a user enters the incorrect username and/or password while logging in. Currently it says contact support@dataverse.org and please contact support. Can you please change it to read, "The username and/or password you entered is invalid. If you need assistance accessing your account, please contact support." (the contact support is supposed to open the contact pop up and it isn't fyi. am about to check other error messages to make sure this hasn't been broken completely)

![error messages](https://cloud.githubusercontent.com/assets/5922904/6943190/588037ae-d85a-11e4-9cd4-d29ad87b205b.png)

**Comment by mheppler** [comment]
Need to revise the suggested error, to fit into how we're currently building these error messages.
Part 1, from messages.xhtml:
````
<strong>Error</strong> – <h:outputText escape="false" value="#{flash['errorMsg']} "/>
````
+
Part 2, from ShibServiceBean.java:
````
logger.info("The username and/or password you entered is invalid. Contact support@dataverse.org if you need assistance accessing your account." + ex.getResponse().getMessage());
````
+
Part 3, from messages.xhtml:
````
Please <p:commandLink  value="contact support" onclick="feedbackForm.show()"/>.
````

**Comment by eaquigley** [comment]
Change second sentence to say, "Need assistance accessing your account?" Then please contact support.

**Comment by mheppler** [comment]
Fixed error message regarding username/password in both the bundle and ShibServiceBean.

This ticket helped identify that not all messaging from the backing beans are pulling from the bundle, and that message.xhtml will need to be reformatted when we try to complete internationalization, because of how error messages are put together, as outlined above.

**Comment by eaquigley** [comment]
Looks perfect! Closing ticket.
