### ISSUE TITLE
Getting a 404 when I log in or log out from dataset.xhtml

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#1825]
When I log in or log out from a published Dataset page (dataset.xhtml) it logs me out or logs me in successfully but I get an error message page instead of being taken back to the Dataset.

To recreate this here is the dataset I am logging in and out from: https://dvn-build.hmdc.harvard.edu/dataset.xhtml?persistentId=doi:10.5072/FK2/Z3F8OG&version=1.0

![image](https://cloud.githubusercontent.com/assets/5013837/6943261/d030d6e6-d85a-11e4-9188-52547e3c5860.png)

cc/ @kcondon

**Comment by kcondon** [comment]
It looks like any dataset does it, even draft.

**Comment by sekmiller** [comment]
I will take a look at this to see if it might be related to the change to the dataset url…



On Apr 1, 2015, at 10:48 AM, kcondon <notifications@github.com<mailto:notifications@github.com>> wrote:


It looks like any dataset does it, even draft.

**Comment by sekmiller** [comment]
Code is now fixed.  A new build is required for testing.

**Comment by posixeleni** [comment]
Issue resolved. Now working as expected. Closing
