### ISSUE TITLE
GeoConnect: Allow a user to only delete the latest version of the map

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1827]
Currently when a user uses the delete map functionality, it deletes all versions of the map. It would be better if we had options to delete only the most recent version of the map or delete all versions of the map.

**Comment by raprasad** [comment]
Confer with @eaquigley.  Currently, there is only one version of a layer.  e.g., When a layer is updated, the previous version no longer exists on Worldmap.  (Note: In a WorldMap terminology, a map is 1 or more layers.)

**Comment by raprasad** [comment]
There is only version of the map--e.g delete will remove the map
