### ISSUE TITLE
Listing Dataverses Widget is Displaying Unexpected Datasets and Dataverses 

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#1828]
I am seeing unexpected dataverse and dataset results when I use a the Listing Dataverses Widget for a specific Dataverse:

**Example: Testing Widgets Dataverse**

For this Dataverse I should only see the following 2 datasets listed:
![image](https://cloud.githubusercontent.com/assets/5013837/6943968/4367f9e2-d85f-11e4-9630-1b86a9d662a9.png)

But for this script:
```
<script src="https://dvn-build.hmdc.harvard.edu/resources/js/widgets.js?alias=test-dv&amp;dvUrl=https://dvn-build.hmdc.harvard.edu&amp;widget=iframe&amp;heightPx=500">
```

I am seeing other Dataverses and Datasets that dont belong with this Dataverse 

![image](https://cloud.githubusercontent.com/assets/5013837/6944621/a5e2ff10-d862-11e4-8349-efaea83acd1a.png)

**Comment by mheppler** [comment]
Added viewParam to iframe, to fix Dataverse Listing widget bug.

**Comment by posixeleni** [comment]
@kcondon can you please let me know if Mike's recent code update made is in build for me to test? https://github.com/IQSS/dataverse/commit/e5d3970f7f148271744b834ea55f1a10cf21c2e7

**Comment by posixeleni** [comment]
Listing Dataverses Widget is now working as expected. Closing.

![image](https://cloud.githubusercontent.com/assets/5013837/6952206/46848c06-d88e-11e4-9874-a048e7100347.png)
