### ISSUE TITLE
Implement SWORD 2.0 Profile 6.4. - Retrieving the content

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#183]
---

Author Name: **Philip Durbin** (@pdurbin)
Original Redmine Issue: 3595, https://redmine.hmdc.harvard.edu/issues/3595
Original Date: 2014-02-27
Original Assignee: Philip Durbin

---

http://swordapp.github.io/SWORDv2-Profile/SWORDProfile.html#protocoloperations_retrievingcontent says "the response to a request for the Media Resource should be considered a representation of the entire content of the object on the server, and it is not permissable to attempt to content negotiate for a particular part of the Media Resource."

Since we require Data Deposit API users to zip up their files before adding them to a study/dataset, it stand to reason that when they "retrieve content from the server" that it would also be a zip file.

Please note that we much consider terms of use discussions that have taken place in #3277, for example, which is about the Data Sharing API.

This feature was requested by the Open Science Framework (OSF) team at http://irclog.iq.harvard.edu/dvn/2014-02-27#i_6612

---

Related issue(s): #338
Redmine related issue(s): [3753](https://redmine.hmdc.harvard.edu/issues/3753)

---

**Comment by scolapasta** [comment]
@pdurbin Is this something we still need or have we handled it with the download API?

**Comment by pdurbin** [comment]
I'd say to be more fully SWORD-compliant we still need this. My understanding is that it would be a representation of a dataset as a zip file.

**Comment by kcondon** [comment]
@pdurbin Would you rephrase this ticket in terms of specific user-oriented behavior? It's hard to prioritize otherwise. It seems to relate to 1. SWORD compliance, 2. Downloading a Dataset as a zip file, 3. Downloading files as a zip file, 4. Also allowing downloading of individual files (see irclog), 5. Requiring an file/dataset owner to complete TOU before downloading their own file.

**Comment by pdurbin** [comment]
I'm closing this issue. If someone out there wants us to implement section 6.4 "Retrieving the content" from the SWORD spec, please get in touch!
