### ISSUE TITLE
Guides Footer - Broken Github Image, Favicon, Outdated Copyright

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#1830]
In all of our Sphinx guides the GitHub icon is broken at the footer.

![image](https://cloud.githubusercontent.com/assets/5013837/6948066/5429e014-d879-11e4-9ba7-44b4ff405822.png)

@mheppler do you know where / how this can be fixed?

**Comment by mheppler** [comment]
Also, the copyright is outdated.

**Comment by mheppler** [comment]
Fixed broken image URLs for footer and favicon in User Guides. Updated copyright year.

**Comment by eaquigley** [comment]
Can see fix here: http://guides.dataverse.org/en/4.0.1/user/

Closing ticket.
