### ISSUE TITLE
Create Dataset: Double validation errors appear when geo block/ country is required and not completed on save.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1831]
1. Enable geo block.
2. Make country field required.
3. Create dataset, do not complete country field, save.
4. Notice correct validation message but there are two of the same on top of each other.

**Comment by sekmiller** [comment]
Fixed and checked in. Another build, please.

**Comment by posixeleni** [comment]
Cant test this until this issue https://github.com/IQSS/dataverse/issues/1903 is resolved since I cannot currently make the Country field required

![image](https://cloud.githubusercontent.com/assets/5013837/7029390/55fb2694-dd2b-11e4-8982-ff6995c25b94.png)

**Comment by posixeleni** [comment]
Double validation error is no longer showing. Issue resolved. Closing this ticket

![image](https://cloud.githubusercontent.com/assets/5013837/7049173/8c475d02-dde5-11e4-8faf-bebd1c853b91.png)
