### ISSUE TITLE
Guestbook: Required field validation pink background spans whole popup behind textbox or default fields, eg. name.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1834]
Using FF 37.0, when I create guestbook that makes some or all default fields required, when I do not complete them, the validation error is correct but the pink message background spans the whole popup, behind the text boxes.

**Comment by mheppler** [comment]
Fixed display issue with input validation error blocks in the Dataset Download File (Guestbook) form popup.

**Comment by kcondon** [comment]
Looks good, closing
