### ISSUE TITLE
Indexing: potential problem indexing dataset that has a draft and deaccessioned version and files but no published version

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#1839]
@scolapasta and I were just talking about how we should look more at `datasetVersion.isDraft() && dataset.isReleased()` and how `dataset.getReleasedVersion().getFileMetadatas()` might be throwing an NPE.

**Comment by scolapasta** [comment]
Had to fix for index to run after exception.

**Comment by suenjedt** [comment]
When I am logged in as admin, I can search, find and access the draft version (old versions not shown in search results). 
When I am logged in with my guest account, I cannot find it.
