### ISSUE TITLE
Permissions - Can't assign "multiple" roles to a user/must save each role as it is assigned

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#1841]
I can only assign one role at a time, per user. Believe we should be able to select multiple roles at once?

**Comment by scolapasta** [comment]
Passing to @eaquigley to decide how we want this to work

**Comment by scolapasta** [comment]
Can we decide if this is something we want and then confirm the design (just change to checkboxes)?

**Comment by eaquigley** [comment]
@sbarbosadataverse what would the use case be for needing to assign multiple roles at once to one user? i.e.-Member + File Downloader?

**Comment by pdurbin** [comment]
@sbarbosadataverse are you still interested in this feature?

**Comment by sbarbosadataverse** [comment]
decided to close it after reviewing the need for multiple role assignment with Gustavo and Julian
