### ISSUE TITLE
Unable to Save Dataverse Theme

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#1846]
Tried to edit my Dataverse Theme and when I tried to save nothing happened.

**Comment by mheppler** [comment]
This is a duplicate to #1847. @kcondon

**Comment by mheppler** [comment]
Removed type="button" attribute from commandButton, that was breaking the button's functionality.

This should now be fixed.

**Comment by posixeleni** [comment]
Now working as expected. Thanks @mheppler 
![image](https://cloud.githubusercontent.com/assets/5013837/6969645/2c01449a-d93e-11e4-9356-a1bc264b0bc0.png)

Closing this ticket.
