### ISSUE TITLE
commandButton - type="button" Attribute Blocking update, action, oncomplete Functionality

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1847]
In the follow code, the type="button" is blocking functionality in the update, action, oncomplete attributes. Remove all type="button" from all commandButton's. Review the JSF and PrimeFaces requirements and HTML validation for this attribute, to identify a best practice going forward.
````
<p:commandButton type="button" value="#{bundle.continue}" onclick="confirmation.hide()"
     action="#{manageFilePermissionsPage.removeRoleAssignments()}"
     process="@this"
     update=":#{p:component('userGroups')} :#{p:component('restrictedFiles')} @([id$=Messages])"
     oncomplete="viewRemoveWidget.hide();"/>
````

**Comment by mheppler** [comment]
Found on:
- dataset-license-terms
- dataset-versions
- dataset
- datasetFieldForEditFragment
- dataverse
- explicitGroup-new-dialog
- manage-guestbooks (on Continue, breaks page)
- manage-templates (on Continue, breaks page)
- permissions-manage-files (on Continue, breaks page)
- permissions-manage
- themeAndWidgetFragment (on Save Changes, breaks page)

**Comment by kcondon** [comment]
OK, tested all of the above. Found a couple unrelated issues, reported separately. Otherwise ok. Closing.
