### ISSUE TITLE
File type (xlsx) is not recognized after upload

### ISSUE THREAD

**Issue by suenjedt** [IQSS/dataverse#1850]
- states "unknown file type"
- see, https://dvn-build.hmdc.harvard.edu/dataset.xhtml?persistentId=doi:10.5072/FK2/YBURNO&version=1.0

**Comment by scolapasta** [comment]
@suenjedt   Can you provide a sample file?

**Comment by suenjedt** [comment]
I just tried again with a different xlsx file and it works fine. The test yesterday was on @posixeleni  computer. Maybe she can double check with exactly the same file again...

**Comment by posixeleni** [comment]
@scolapasta here is the file we tried: https://www.dropbox.com/s/00yl2jsxzr3wen4/chinese-rice-paddy-values-5517.xlsx?dl=0

**Comment by suenjedt** [comment]
Thanks - The xlsx now appears as a tab file. 

https://dvn-build.hmdc.harvard.edu/dataset.xhtml?persistentId=doi%3A10.5072%2FFK2%2FQ8MZL9&version=DRAFT

**Comment by posixeleni** [comment]
Since the file is now being recognized I am going to close this ticket. Thanks @suenjedt and @scolapasta !
