### ISSUE TITLE
Missing box for "alternative" Terms of Use (when not selecting CC0)

### ISSUE THREAD

**Issue by suenjedt** [IQSS/dataverse#1851]
- if the user decides NOT to select CC0, there is (currently) no box allowing the user to enter their preferred license/ToU.

**Comment by posixeleni** [comment]
There use to be a Custom Terms of Use free-text box that allowed folks to enter in any custom ToU.

**Comment by suenjedt** [comment]
Works. 
However, when you confirm. You see the following:
![screen shot 2015-04-07 at 13 43 38](https://cloud.githubusercontent.com/assets/7300319/7029526/3d460730-dd2c-11e4-9859-6c8e663b1538.png)

I wonder, if it is confusing for an external/new user to see waiver, non-waiver, and selected alternative licence in one box here. Maybe one could remove the "waiver" information here and solely focus on the selected alternative license?

**Comment by mcrosas** [comment]
I agree this is confusing. @eaquigley could you review this with @suenjedt ? I t would make sense not to show the waiver information if terms of use are selected instead.

Also It would be clearer if the "community norms' text doesn't show as part of the waiver (it should be in a separate line)

**Comment by posixeleni** [comment]
we could still show this Waiver information when a user goes in to Edit but on View hide it right?

**Comment by suenjedt** [comment]
Good question. Initially I thought yes, but once it is published you should not be able to change the licence/waiver information for that version, anyway - non?

**Comment by posixeleni** [comment]
For that version yes but changing the license information should make you publish a new version. Is it not doing that now?

**Comment by suenjedt** [comment]
Yes - you are right. Just tested it. Works
