### ISSUE TITLE
Review indexing for deaccessioned datasets

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#1853]
A late change removed the indexing of files from deaccessioned datasets - this is likey what we want going forawrd, but we should review the idea (and the code).

**Comment by pdurbin** [comment]
> A late change removed the indexing of files from deaccessioned datasets

No. On July 9, 2014 in a design meeting it was decided, "You should never see a card for deaccessioned files. We only show cards for deaccessioned datasets." -- https://docs.google.com/document/d/1lFcwjtdGIqqQLYYnwtTI2GZNzmzYlrnMk2omGcXO9oY/edit?usp=sharing

@scolapasta are you reversing that design decision? It was implemented in #57. /cc @eaquigley @mheppler @posixeleni @sekmiller also commented on that design doc or attended the meeting.

**Comment by scolapasta** [comment]
This issue was created at a time when we were quickly debugging things - from the code it was not apparent that deaccessioned files were not being indexed, however they were. So this is a non issue.

**Comment by kcondon** [comment]
Non issue, closing.
