### ISSUE TITLE
Document SPSS Ingest Advanced Options in User Guide

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#1854]
>Since this is a quite advanced feature, could we have a link to the user guides in the place that this is >described? If that's not ready now, at least we want an issue to add the link to the guides later.
>
>Merce

**Comment by eaquigley** [comment]
@landreev I created a section for this here: https://github.com/IQSS/dataverse/blob/master/doc/sphinx-guides/source/user/dataset-management.rst and added some advanced options but not all. Could you please go in and add the remaining ones. Thank you.

**Comment by landreev** [comment]
This is now documented in the SPSS-specific section of the Tabular Data ingest section of the guide: 

guides/user/tabulardataingest/spss.html

**Comment by kcondon** [comment]
Doc is in place, closing
