### ISSUE TITLE
View Template: Peristent id field shows nullnullnull

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1858]
Created a new template, put something in title for no particular reason, saved. Viewed it and saw:
Dataset Persistent ID   null:nullnullnull

**Comment by sekmiller** [comment]
Fixed will be checked in shortly - pending other available  minor fixes

**Comment by sekmiller** [comment]
checked in

**Comment by kcondon** [comment]
Fixed, closing.
