### ISSUE TITLE
Duplicate / Wrong Text Found When Deaccessioning A Dataset

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#1859]
There is duplicate text on this page. The first text should say "Which version(s) do you want to deaccession?" rather than "What is the reason for deaccession?" which is already displayed in the valid section below. See screenshot.

![image](https://cloud.githubusercontent.com/assets/5013837/6971766/e66a0cbe-d94c-11e4-803d-d68e8a7e57f3.png)

cc/ @mheppler @sekmiller

**Comment by kcondon** [comment]
OK, duplicate text is gone, replaced by correct text. Closing.
