### ISSUE TITLE
Versions button won't display all versions after selecting to view a previous version

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#1860]
I went to a dataset
clicked on versions
selected version 1.0 of the three versions possible
took me to the version, then when I click/hover over versions again, I get a slim little empty box under it but no option to see other versions, including released version

![szmkyvs_wbs1eexqnopb4crmdpjtq15wki080osizho](https://cloud.githubusercontent.com/assets/8322346/6972648/331a780e-d953-11e4-8986-7855ce954e4d.png)

**Comment by posixeleni** [comment]
Test

**Comment by scolapasta** [comment]
Fixed.

**Comment by sbarbosadataverse** [comment]
Fixed!
