### ISSUE TITLE
User/Groups shown incorrectly when editing the permissions of a dataverse

### ISSUE THREAD

**Issue by suenjedt** [IQSS/dataverse#1864]
as shown on screenshot below. 

In addition, when selecting the group's role, it might be helpful to call the first field "group name" (same name convention used when defining the group earlier). 

![screen shot 2015-04-02 at 17 23 29](https://cloud.githubusercontent.com/assets/7300319/6974047/54b8e8b0-d95d-11e4-86a8-a950d903836f.png)

**Comment by mcrosas** [comment]
New layout to make this clearer:

Column 1: User/Group Name (affiliation)
Column 2: id

@mheppler if this is confusing, talk to me

**Comment by mheppler** [comment]
Applied suggested layout clean up to the User/Group Name (Affiliation) and ID to tables/dropdowns on permissions-manage, permissions-manage-files, explicitGroup-new-dialog and roles-assign.

These changes are in a new branch and need to be merged into master.

**Comment by suenjedt** [comment]
Indeed, clearer. 

Minor thing: The formatting in the table is not clean, but I understand it is for admins predominantly. 
![screen shot 2015-04-07 at 14 16 18](https://cloud.githubusercontent.com/assets/7300319/7030174/b70a74da-dd30-11e4-9d11-30f537a7e517.png)
