### ISSUE TITLE
Validation Errors - Scroll to Message Top of Page

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1865]
These following pages could use a "scroll to top" feature, similar to what is being used on dataset #1698.

- [x] Dataverse
- [x] Dataset Template

This is something that should probably be added to the "Save..." buttons of every page, but that is something for another release.

**Comment by mheppler** [comment]
Fixed the "scrollTo" functionality for displaying validation errors on dataset to only display on error, and delete file success, messages. Applied fix to dataverse and dataset template pages as well.

**Comment by kcondon** [comment]
Doesn't work for Chrome, scrolls but validation errors not appearing.
