### ISSUE TITLE
CC0 - waiver vs. license [nomenclature]

### ISSUE THREAD

**Issue by suenjedt** [IQSS/dataverse#1867]
Just a minor comment:
at CERN we also use CC0. We also used a similar phrasing to yours (including "licence") in our ToU and metadata. However, we got approached by Creative Commons directly as they preferred to change the wording to "waiver" instead of using the expression CC0 "license". 
Our revised ToU can be found here, http://opendata.cern.ch/terms-of-use

**Comment by scolapasta** [comment]
Assignig to beta 15 for @posixeleni to investigate - then we can decide if we want to make a change.

**Comment by posixeleni** [comment]
We should use the same language as the folks in Creative Commons which according to their website is:

CC0 - Public Domain Dedication
https://creativecommons.org/publicdomain/zero/1.0/

**Comment by mheppler** [comment]
That page doesn't refer to either a "Waiver" or a "License". But if you click on the "Legal Code" link, there, you have...
> 3. Public License Fallback. Should any part of the Waiver for any reason be judged legally invalid or ineffective under applicable law, then the Waiver shall be preserved to the maximum extent permitted taking into account Affirmer's express Statement of Purpose.

There is a reference to a "Waiver". I assume that means we should use "Waiver".

@posixeleni @scolapasta @mcrosas @suenjedt

**Comment by mheppler** [comment]
Talked to Merce. Showed her the Creative Commons link. She has OK'd changing "License" to "Waiver".

- [ ] Anywhere it reads "License + Term" for tab, link, etc, it should now be just "Terms".
- [ ] Anywhere the CCO - "Public Domain Dedication" is referenced as a "license", it should be "waiver".
- [ ] Tab label should be "Waiver", help text should be revised.
- [ ] User Guide help text should also be revised.

@posixeleni -- I am going to take this ticket to implement all this in the XHTML of the app today. Feel free to tackle the User Guides, if you can, while I have it.

**Comment by posixeleni** [comment]
@mheppler I will tackle the User Guides

**Comment by posixeleni** [comment]
@mheppler the documentation should be all set: also updated here: https://github.com/IQSS/dataverse/blob/master/doc/sphinx-guides/source/user/dataset-management.rst

**Comment by mheppler** [comment]
Swapped out all front-end references to "license" for "waiver" for tab, buttons, labels, help text, as related to CC0 being applied to the dataset.

These changes are all on a new branch, and need to be merged to master.

**Comment by suenjedt** [comment]
With the current wording, I would propose to remove some "waivers" in the text in the individual record's ToU box, so that it would read the following:

Datasets will default to a CC0 public domain dedication. CC0 facilitates reuse and extensibility of research data. Our Community Norms as well as good scientific practices expect that proper credit is given via citation. If you are unable to give datasets a CC0 waiver you may enter custom Terms of Use for datasets.
	Yes, apply CC0 - "Public Domain Dedication" 	
	No, do not apply CC0 - "Public Domain Dedication" 

Comment: I am not a native speaker obviously. Feel free to revise. 
Also, I understand that second line beneath the radio buttons showing the CC0 logo is to confirm the choice. I would find it clearer to see the logo in the radio button line. But thats just me and not crucial right now...

**Comment by eaquigley** [comment]
Great suggestions @suenjedt . I've taken the extra waivers out and think post 4.0, we can discuss the location of the icon.
