### ISSUE TITLE
Add/Delete emails upon new dataverse creation resulting in persistent mouseovers

### ISSUE THREAD

**Issue by suenjedt** [IQSS/dataverse#1868]
I tried several times - with this result (Firefox)

![screen shot 2015-04-03 at 11 07 42](https://cloud.githubusercontent.com/assets/7300319/6983982/0af6eb24-d9f2-11e4-9069-1babe6204700.png)

**Comment by scolapasta** [comment]
related to #1499, so closing this as aduplicate and putting details there.
