### ISSUE TITLE
Unable to search Thai characters 

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#1869]
Searching for a known dataset with Thai characters does not work, which we had resolved in #1274 for Japanese characters.

![image](https://cloud.githubusercontent.com/assets/5013837/6984415/9913349a-d9f6-11e4-8213-83ee3fd0a4bb.png)

Here is the study you can test this with in build:
https://dvn-build.hmdc.harvard.edu/dataset.xhtml?persistentId=doi%3A10.5072%2FFK2%2F2PBREP

**Comment by scolapasta** [comment]
seems related to #1862

**Comment by kcondon** [comment]
Was able to fix  this by adding     <parameter-encoding default-charset="UTF-8" /> to the glassfish-web.xml file. Leonid will check it in so it will be in place upon deployment. Closing.
