### ISSUE TITLE
Number Formatting: Commas for Numbers 999+

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#1870]
http://stackoverflow.com/questions/8740578/how-to-format-the-number-with-comma-when-user-lost-focus-in-hinputtext
```xhtml
<h:outputText value="#{results.number}" >
    <f:convertNumber pattern="###,###" />
</h:outputText>
```
![screen shot 2015-04-03 at 11 53 56 am](https://cloud.githubusercontent.com/assets/687227/6984564/26dd3df6-d9f8-11e4-854c-e94d5a5b2f21.png)

**Comment by scolapasta** [comment]
Duplicate - of #1761 - copying the above info to that issue.

**Comment by kcondon** [comment]
Closing as dupe.
