### ISSUE TITLE
while testing 1786, the metadata "checkbox" function stopped working

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#1871]
I can select the metadata block, but the check doesn't appear

![t0lbvuly5uubhii-jl-_8ebzhyjovulirxomhynx8pe](https://cloud.githubusercontent.com/assets/8322346/6984566/2b2da792-d9f8-11e4-9548-36142957295f.png)

**Comment by kcondon** [comment]
Could not reproduce. Sent Sonia an email to double check. Closing for now, will reopen if Sonia can reproduce. Closing.
