### ISSUE TITLE
Inherited guestbooks: Could not enable the guestbooks in a chain of dataverse/dataset children

### ISSUE THREAD

**Issue by suenjedt** [IQSS/dataverse#1873]
I tried to set up a chain of dataverses and datasets (4 levels). In the lower levels we could not enable the guestbooks. We could still look at them, so they were inherited, but we could not enable them. We double checked that they were enabled in the upper levels.

**Comment by mcrosas** [comment]
To be review with QA team

**Comment by kcondon** [comment]
Was able to reproduce: it only works for 2 levels of dataverses.

**Comment by sekmiller** [comment]
Fixed. needs a build for testing

**Comment by kcondon** [comment]
Works, closing.
