### ISSUE TITLE
Dataset Page Performance (sub issue #3) (if needed)

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#1874]
Part of #1754 

**ISSUE**:   Displaying metadata conducts circuitous queries to display each piece of information

**'FAST FIX'**: Stash the display data (for released versions) as JSON.  Run 1 query rather than hundreds.

**ADDITIONAL BENEFIT**: Use this data for Solr Indexing. e.g 1 query rather than hundreds

Short term strategy:
- [ ] create table **DatasetMetadataView** (or something similar)

|dataset id|dataset version id|JSON metadata|timestamp|
|-----------|-----------|-----------|-----------|
|21|79|{ metadata here }|2015-04-03 12:22:00|

- [ ] For each version of metadata fields,  look to the table above for info.
- [ ] If not found:
  - Construct "display metadata" the current way
  - Save the constructed metadata as JSON to the table above, including citation block hierarchy.
  - Look at field ordering.  Either put in JSON, or set field ordering dynamically...)
- [ ] If found:
  - Update the DatasetPage.java / dataset.xhtml to use JSON as citation block metadata source

**Comment by pdurbin** [comment]
I wonder if we take advantage of the JsonWalker code somehow.

**Comment by kcondon** [comment]
Closing, improvements made in v4.2.2.
