### ISSUE TITLE
reference 1694-Eleni asked about position of Publication Date and DOI-should move up in citation info?

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#1875]
DOI appears at bottom of the list, and does publication date. Perhaps can move under title as these are pretty important citation fields?

![uej2tb29vhxdpqjp6qa5w3mvcr7ixg9fcyof1uyxmhe](https://cloud.githubusercontent.com/assets/8322346/6984969/4085c1ac-d9fc-11e4-85b0-00722153536d.png)

**Comment by mheppler** [comment]
Those are static fields, as opposed to dynamic fields, we we can not place
them between fields. They need to be on the top or the bottom. We went with
bottom originally, and intended to review after.

Would you prefer them above Title?

**Comment by mcrosas** [comment]
Above the title:
DOI (first)
Publication Date (second)
Title

**Comment by mheppler** [comment]
Moved Persistent ID and Publication Date to the top of the Citation Metadata block on dataset page.

**Comment by kcondon** [comment]
Works as described, closing
