### ISSUE TITLE
Saved Search - "Link earch" is Disabled, Can Click Through Anyway

### ISSUE THREAD

**Issue by suenjedt** [IQSS/dataverse#1879]
![screen shot 2015-04-03 at 14 48 28](https://cloud.githubusercontent.com/assets/7300319/6987091/d5ceb7fe-da11-11e4-8774-9c0f94562c87.png)

**Comment by mheppler** [comment]
Fixed the disabled links for Link Dataverse and Link Search. Also applied similar fixes for the links in View Dataset Versions on dataset, and pagination links for "<</Previous" and "Next/>>" on search.

These commits are on a new branch and need to be merge to master.

**Comment by suenjedt** [comment]
Works
