### ISSUE TITLE
Unable to Add Dataset in Chrome (works in Firefox)

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#1881]
We dropped the db this afternoon and as soon as this happened I was unable to Add A Dataset. It would just refresh the page back to the form. Sonia tried this on her computer as well and had the same issue. Not seeing any server log errors.

However, when I tried in Firefox it saved the Dataset just fine.

cc/ @mheppler @kcondon

**Comment by mheppler** [comment]
Related to #1698 -- which was in QA. Send that back to me. Closing this issues as a dup.

**Comment by mheppler** [comment]
I reopened this ticket, because #1698 will not be completed for Beta 15 and is getting moved to another milestone. I have reverted back the old code, so that fixes this bug ticket, which I am sending to QA.

This check-in is in another branch and will need to be merged with master.

**Comment by posixeleni** [comment]
Able to Add Dataset in Chrome now. Works as expected.
