### ISSUE TITLE
Install: Setup-optional-harvard.sh is putting the support queue email as the system email. Don't!

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1882]
Setup-optional-harvard.sh is putting the support email as the system email and as a result it is creating an RT ticket everytime someone creates a dataverse or dataset. Stop the madness!!!!

OK, the actual cause was putting the support email in the super user account. Need to review with Gustavo/ Merce how it works to see which email goes where.

**Comment by scolapasta** [comment]
We're fine with support@dataverse.org as the system e-mail.
