### ISSUE TITLE
Indexing: N/A values should not be indexed

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#1883]
"I noticed that in #1246 that we don't want to display N/A values in UI, but as of this writing it's easy to create a dataset like this via SWORD by simply not including any dcterms:subject elements in the XML"

I first made that comment a month ago at https://github.com/IQSS/dataverse/issues/1430#issuecomment-76814420 but I'm opening this ticket (with a screenshot) to make sure we're ok with showing N/A in the Subject facet:

![subjectna](https://cloud.githubusercontent.com/assets/21006/6990063/99a305f2-da32-11e4-9209-6feba3ecbf32.png)

This happens all the time on https://apitest.dataverse.org right now where I'm not specifying a subject in the XML I use to create a dataset via SWORD.

**Comment by scolapasta** [comment]
We should not be indexing these N/A values.

**Comment by scolapasta** [comment]
Notice with production data we also see several N/As.

**Comment by pdurbin** [comment]
> We should not be indexing these N/A values.

@scolapasta please review a195b17 (pushed to a branch) and let me know if it's ok to merge in. The question I have is for the dataset level. In that commit the logic is to never index an "N/A" value for **any** dataset field that has a controlled vocabulary that includes "N/A" (not just the "subject" field).

**Comment by pdurbin** [comment]
I chatted with @scolapasta and it sounds like we want to avoid indexing "N/A" for as many fields as possible, including fields that don't have controlled vocabularies (which is most fields).

Since the logic I'll need to put in the code is spread on various lines, I just did a query on our migrated data to make sure I adjust indexing for as many fields as possible. The main ones to adjust will be for authors and descriptions:

```
[pdurbin@dvn-vm7 ~]$ curl -s 'http://localhost:8983/solr/collection1/select?rows=1000000&wt=json&indent=true&q="N/A"' | grep '"N/A"' | sort | uniq -c | sort -nr
   6563         "dsDescriptionValue":["N/A"],
   6062         "authorName_ss":["N/A"],
   6062         "authorName":["N/A"],
     12         "producerURL":["N/A"],
      6         "universe_ss":["N/A"],
      6         "universe":["N/A"],
      4         "relatedMaterial":["N/A"],
      4         "otherGeographicCoverage":["N/A"],
      3         "relatedDatasets":["N/A"],
      2         "gsdSiteType_ss":["N/A"],
      2         "gsdSiteType":["N/A"],
      2         "geographicUnit_ss":["N/A"],
      2         "geographicUnit":["N/A"],
      2         "dvDescription":"N/A",
      2         "description":"N/A",
      1         "title":"N/A",
      1         "publicationCitation":["N/A"],
      1         "nameSort":"N/A",
      1         "gsdProgramBrief_ss":["N/A"],
      1         "gsdProgramBrief":["N/A"],
```

**Comment by pdurbin** [comment]
@scolapasta please review the new-and-improved version at 269081b and let me know if I should merge it to master.

**Comment by pdurbin** [comment]
@scolapasta merged #1897 but we decided to change `break` to `continue` in 50a4b9a so that we don't stop indexing values on the first "N/A" in a list of controlled vocabulary values. Some of those values may not be "N/A".

Ready for QA.

**Comment by posixeleni** [comment]
@scolapasta @kcondon I cant test this in build since we need to see how migrated local studies got indexed. So can you please tell me when this fix is in the new production site (harvard.dataverse.edu) or vm6?

**Comment by posixeleni** [comment]
Searched for N/A in production and was unable to find it indexed. Also looked at facets to confirm this was the case. Closing this ticket.
