### ISSUE TITLE
Support newer versions of API

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#1885]
In 4.0, we added v1 to the URLs, but we'll need to modify code for when we want to support more versions.

**Comment by pdurbin** [comment]
#3326 is a case of a minor breaking change of our API that users noticed and seem to have mostly worked around.

We should review #3325 to see if it's ok or not that we're hard coding non-versioned URLs in various places.

The point of versioning an API, of course, is that you have different behavior or at least different syntax to trigger the same behavior and that both syntaxes and/or behavior can exist side by side for several months or years or whatever. We would need tests in place to make sure that the deprecated API version continues to work. Once the deprecated API version is disabled or deleted, those API tests could be deleted or modified to expect failure.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
