### ISSUE TITLE
Review the harvest note that is set for each harvest configuration

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#1887]
This shows up for each dataset and is currently configurable in the db.

**Comment by posixeleni** [comment]
This is what it currently looks like: 

>"This Dataset is harvested from our partners at the ICPSR at the University of Michigan. Clicking the link will take you directly to the archival source of the data."

![image](https://cloud.githubusercontent.com/assets/5013837/7006768/afb987c8-dc51-11e4-8d76-6049a08e99f4.png)

@scolapasta this generic text is good for the most harvested open data repositories but during our 3/13/15 migration meeting https://docs.google.com/document/d/1AqOQKGRBzjqacp4_x8BzAPJqyQaP4_5OOYaMCmygaZ0/edit?usp=sharing @mcrosas had discussed putting in more customized text for ICPSR harvested data to let users know that only ICPSR Members would have access to this data. So for ICPSR data can we change this to:

>"This Dataset is harvested from our partners at the ICPSR at the University of Michigan. If you or your institution are an ICPSR Member, clicking the link will take you directly to the archival source of the data."

**Comment by mheppler** [comment]
Please make "Dataset" lowercase. Review the format of these messages with @eaquigley.

**Comment by eaquigley** [comment]
dataset has been made lowercase and i am fine with the message
