### ISSUE TITLE
Add harvested icon to search cards

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#1889]
Now that we have harvested data, we need to change the icon for those. @mcrosas has ideas, and @landreev can point you to the rendered logic (I think it's just .harvested from the entity).

**Comment by mheppler** [comment]
Added new icons to the browse/search cards for files, dataset, dataverse. Also added titles to these icons, and the other icons for type, linked, restricted, restricted w/ access icons.

These changes are in a new branch, which needs to be merge to master.

**Comment by posixeleni** [comment]
@kcondon sorry for all the questions but according to Mike's last message in this ticket this was not yet merged with master. How can I test this? Unless you know that this was finally merged?

@mheppler can you please let me know what the harvested icon will look like so I know what to expect?

**Comment by mheppler** [comment]
@posixeleni @kcondon -- branch was merged this AM by @scolapasta 1378835f963306e594b243ae3daa0966c237fe4a

**Comment by posixeleni** [comment]
@scolapasta which of the servers have migrated harvested datasets with the latest code from Mike? I need to know so I can test if the icon is showing up.

Thanks!

**Comment by posixeleni** [comment]
tested this on vm5 and I am now seeing the harvested icon
![image](https://cloud.githubusercontent.com/assets/5013837/7048328/69bc7bc8-dde0-11e4-8e1c-9e62f79661ab.png)

Closing since this works as expected.
