### ISSUE TITLE
SWORD: prepare docs for 4.0 release

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#1891]
SWORD was worked on before many features such as DOI registration were added so http://guides.dataverse.org/en/latest/api/sword.html should be reviewed to make sure it still makes sense. Many "known issues" are gone and some of the features on the roadmaps have already been implemented.

**Comment by pdurbin** [comment]
In addition to the first pass of corrections I made in 67fd763 I reviewed the SWORD docs fairly thoroughly as part of #1077. I think they're good enough to tag as 4.0. Moving to QA.

**Comment by pdurbin** [comment]
Oh, ready except for #1553 which is a separate ticket.

**Comment by eaquigley** [comment]
#1553 has been closed so I am going to go ahead and close this. If any new issues may arise relating to this documentation, a new issue should be created.
