### ISSUE TITLE
Create Dataset: Created dataset, sent me to login page with successfully created message.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1892]
I created a dataset in root dv as regular user/ contributor with access perms set to allow anyone with account create dataset/dv as contributor. It redirected me to the login page with message that it was successfully created.
Additionally, I found that I no longer had access to that dataset when I clicked on it so it seems to be a permissions issue.
Does not happen with no files on create or not ingestable  files such as image. Happened with dta and csv at least.
Also does not happen if you add the files after create.

**Comment by scolapasta** [comment]
Still not sure why exactly this was happening, but fixed by switching the a call to save the file to re find the file by id (I think somewhere the method had pre merged data?)

**Comment by kcondon** [comment]
OK, works now, closing
