### ISSUE TITLE
dataset-versions.xhtml null pointer

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#1893]
Issue
```
Error Rendering View[/dataset.xhtml]
javax.el.ELException: /dataset-versions.xhtml @118,80 value="#{versionTab.versionDate}": java.lang.NullPointerException~~
```
#### Failed fix:
- Null check on ```versionDate```

```
<ui:fragment rendered="#{versionTab.versionDate != null}">
```

#### Correct Fix:
- ```versionDate``` is not an actual field, only a method that formats ```lastUpdateTime```
    - instead use: ```!empty(versionTab.lastUpdateTime)```
```
<ui:fragment rendered="#{ !empty(versionTab) and !empty(versionTab.lastUpdateTime) }">
                 <h:outputText id="versionDate" value="#{versionTab.versionDate}" />
             </ui:fragment>
```

**Comment by raprasad** [comment]
Moving to QA
@kcondon

**Comment by kcondon** [comment]
OK, went to versions tab with draft and other versions and do not see the server log error. Closing.
