### ISSUE TITLE
Revise Ref-Type in EndNote XML Export for Dataset Data Citation

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#1894]
When exporting the dataset data citation to EndNote XML I am seeing the ref-type is set to <ref-type name="Online Database">45</ref-type> 

Example:

```
<?xml version="1.0" encoding="UTF-8"?>
<xml>
  <records>
    <record>
      <ref-type name="Online Database">45</ref-type>
      <contributors>
        <authors>
          <author>Castro, Eleni</author>
          <author>Catstro, Fidel</author>
        </authors>
      </contributors>
      <titles>
        <title>Fictional Data</title>
      </titles>
      <section>2015-04-06</section>
      <dates>
        <year>2015</year>
      </dates>
      <publisher>Root Dataverse</publisher>
      <urls>
        <related-urls>
          <url>http://dx.doi.org/10.5072/FK2/DOY6MP</url>
        </related-urls>
      </urls>
      <electronic-resource-num>doi/10.5072/FK2/DOY6MP</electronic-resource-num>
    </record>
  </records>
</xml>
```

If possible, this should be set to:

```
<ref-type name="Dataset">59</ref-type>
```

I spoke with @kcondon who explained to me why it is showing up as <ref-type name="Online Database">45</ref-type>  but if possible after 4.0 it would be more ideal if we could change this to be <ref-type name="Dataset">59</ref-type> and is what ICPSR is using for their datasets
![image](https://cloud.githubusercontent.com/assets/5013837/7011575/4782670c-dc78-11e4-9f3f-adad6cf86ed2.png)

Updated 2017-06-05 by @pdurbin to make the XML above readable rather than being on a single line.

**Comment by jggautier** [comment]
Instead of using Online Database, I think we can use the "Dataset" reference type Endnote has now. I'm trying get the ref-type number for it.

**Comment by jggautier** [comment]
The ref-type was changed to 59 in https://github.com/IQSS/dataverse/issues/4816. 👍Closing this issue.
