### ISSUE TITLE
Deaccession Dataset: Contributor is incorrectly? allowed to deaccession but it doesn't work.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1895]
This may be a permission issue where a contributor should not be allowed to deaccession a dataset but is given the opportunity to try.

Works fine for admin.

**Comment by scolapasta** [comment]
Review all the sub buttons under edit (permissions, etc).

**Comment by sekmiller** [comment]
With respect to deaccession - the link was rendering if the user has delete dataset permission, but the command required publish dataset permission.

**Comment by sekmiller** [comment]
Fix checked in

**Comment by kcondon** [comment]
This works now, closing.
