### ISSUE TITLE
File Ingest: Ingesting a file puts dataset in incorrect UI state, added file not visible/ apparent until refresh.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1899]
1. Create a dataset, publish.
2. Ingest a data file, say fearonlaitin.dta to published dataset.
3. Upon saving, see grayed out edit, publish buttons, consistent with ingest in progress but notice file does not appear in UI and dataset is published version, not new draft. Refresh and everything appears correctly.

**Comment by raprasad** [comment]
Reproducible bug.  Needs more investigation of how the async. ingest process works with the DatasetPage.  The DRAFT version is being retrieved after file is saved.  However, it is not the version getting to the screen.

Talked @scolapasta and moving to review

**Comment by kcondon** [comment]
This area has been improved, if not corrected. Closing.
