### ISSUE TITLE
File upload: Adding files to a dataset adds the string "hello!" to the versions tab for that version.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1900]
1. Create a dataset, publish.
2. Add a file, publish.
3. Look at version tab, see the word, "hello!" after the add files comment.

**Comment by sekmiller** [comment]
Removed the static "hello!" text @raprasad It looks like you were using this for debugging

**Comment by kcondon** [comment]
Hello! was removed, closing.
