### ISSUE TITLE
Data Citation Export: API Integration w/ EndNote

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#1902]
Work with EndNote to allow for more seamless data citation export from Dataverse into EndNote using RESTful API. See email below from EndNote Developer:

> Hello Eleni,
> 
> Apologies for the delay in responding. We have a couple of improvements in progress that would make it easier for you to consume our API and documentation. For the API, we are validating a RESTful implementation that will make integration simpler with web applications (as opposed to our existing Thrift implementation). For the documentation, we are working on a developer portal to provide better management of developer credentials and access to developer information (as opposed to sending documents via email).
> 
> We’ve made great strides in both areas but I don’t have a definite timeline for either so we may want to proceed without waiting for these and we’ll be sure to keep you updated with progress on both fronts.
> 
> On the topic of developer credentials, access to the EndNote cloud API is governed by developer credentials that will be assigned to each developer. See below for a snippet from our license agreement (the current agreement is in the process of being updated to cover the cloud API – vs. the local API – so this is a preview of one section from the updated terms).
> 
> In order to access the Cloud API, you must register for a unique API key from Thomson Reuters. You will be issued one or more unique security keys, tokens, passwords and/or other credentials (collectively, "Keys"), for accessing the Cloud API and managing your account. You may only access the Cloud API with the Keys issued to you by Thomson Reuters. Access may not always be available. You may not (i) sell, transfer, sublicense or otherwise disclose your Keys to any other party, (ii) use your Keys with any other product or application other than that for which you initially applied for them, or (iii) circumvent or modify your Keys or other security mechanism employed by Thomson Reuters. You are fully responsible for maintaining the secrecy and security of your Keys, and for all activities that occur using your Keys, regardless of whether such activities are undertaken by you or a third party. You are also responsible for maintaining up-to-date and accurate information (including a current email address and other required contact information) for your account. Thomson Reuters may discontinue your access to the Cloud API if such contact information is not up-to-date and/or you do not respond to communications directed to such email address.
> 
> I wanted to ensure that you will be able to abide by these [and, once available, the rest of the] terms considering your software sharing model and publicly hosted source code.
> 
> Please let us know if you have any questions. Thanks.
> 
> Curtis Smith

**Comment by pdurbin** [comment]
Do we still need this now that we have EndNote import thanks to #1393 being shipped with Dataverse 4.7?

**Comment by jggautier** [comment]
Maybe we can close this and revisit if EndNote doesn't play as well with additional dataset meta tags (dataset version, repository, etc.) as we would like.

**Comment by pdurbin** [comment]
No one seems to be asking for this. Closing.
