### ISSUE TITLE
Metadata blocks: Geospatial and Journal metadata blocks are broken for compound fields, parents not identified correctly, leading to incorrect hidden designation.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1903]
Viewing the default display for the geospatial and journal metadata blocks at root when these are *not* selected shows the compound fields parent/child order is incorrect, ie. parents display below the children, and possibly as a result, the children are all marked as hidden when in fact they are not.

This also happens in a child dv when these blocks are chosen/ enabled. We do not have the ability to define how these fields behave due to the above issue.

**Comment by sekmiller** [comment]
Fixed - new build required for testing

**Comment by posixeleni** [comment]
Needed to test this before being able to test #1831 and this is now working as expected. Closing.
