### ISSUE TITLE
Metadata can't be updated-contact support

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#1905]
This came up when I used GSD custom fields, made fields required, and was attempting to add values, and hit save.

![ijjzvu-o0st5l9gai0venmkq6kktwtvx9byldjdsf2s](https://cloud.githubusercontent.com/assets/8322346/7029010/21d2b678-dd28-11e4-8c9f-18d5532ce1cc.png)

**Comment by scolapasta** [comment]
CVV Datasetfields were still being saved in db. This is now removed.

**Comment by scolapasta** [comment]
The other issue was that blank fields were getting created when going to view. Which mean that when you published a dataset, those blanks were getting saved to the db.

This should be all set now. @sekmiller knows how to consistently reproduce the issue, so can help test.

**Comment by scolapasta** [comment]
Please note, the previously created datasets that had this issue will continue to have this issue, as the bad data is already in the db.

**Comment by sbarbosadataverse** [comment]
@scolapasta 
user just reported. I tested on his dataset and was able to reproduce in production 4.0
