### ISSUE TITLE
 Root Dataverse > Account  moving between tabs is slow and disrupted

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#1906]
Stuck on blue rotating icon after a few clicks

![lnlfibazwsyteptqxq4mzx4n3gibykcdz8fokhwqugo](https://cloud.githubusercontent.com/assets/8322346/7029148/4bd0b8fc-dd29-11e4-9c4f-8cfebf471f30.png)

**Comment by scolapasta** [comment]
@kcondon will test some more to evaluate the scope of the issue.

**Comment by kcondon** [comment]
This happens for admin on build but not for admin on vm6. Works for other users on build.

**Comment by scolapasta** [comment]
I think this was the issue we discovered in resolved in #2004

**Comment by kcondon** [comment]
Same issue, closing.
