### ISSUE TITLE
404 + 500 Error Page -- Clean Up

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1908]
- [x] Move page title, button, input placeholder, message text to bundle.
- [x] Make placeholder text have lower case "dataverse...".

**Comment by mheppler** [comment]
Moved 404 and 500 error pages' page title, error message, button text, etc. to bundle.

**Comment by kcondon** [comment]
404 page looks good, not sure how to generate 500 error. Closing but will keep an eye out for it.
