### ISSUE TITLE
lock icon for restricted files has disappeared on main page

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#1911]
The file is restricted in the dataset-when you browse in the dataverse you should see a restricted icon showing up next to the file name

![kmwpqiiyovwbac7n2z1jeqmtj1fqjf2pfwapnuru3eu](https://cloud.githubusercontent.com/assets/8322346/7034573/9b72bbb4-dd4f-11e4-804a-1b34f7d653e8.png)\

![rk4mt8n9qcydqgi5cncaiujghnlngywv0d8ec31n6xc](https://cloud.githubusercontent.com/assets/8322346/7034628/d6bae840-dd4f-11e4-8b62-e66791f8d858.png)

**Comment by scolapasta** [comment]
This was fixed in beta 15.

**Comment by scolapasta** [comment]
This was fixed in beta 15.
