### ISSUE TITLE
Support for tsv file ingest for tabular data

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#1912]
We currently do not support special ingest for tabular files that are in a tab-delimited format (.tsv). Spoke w/ @mcrosas that this is something we should also support if we already can handle .csv format which similarly looks at the first row of the table to grab variable metadata.

**Comment by philippconzett** [comment]
As for tabular data, in addition to the original file format we recommend our users to provide a tabulator separated Unicode utf-8 .txt file. Those seem not be be ingested properly in Dataverse. Here are to examples that can be tested:

http://dx.doi.org/10.18710/SJ4OQE
http://dx.doi.org/10.18710/4MCRQL

Best, Philipp

**Comment by pdurbin** [comment]
@philippconzett thanks. To be clear you mean that "Spring_migration_arrival_dates_Acrocephalus_schoenobaenus.txt" (MD5: fcc151933f34034bfd1ea6b2ff3d3186), for example, is a tab separated values file from https://opendata.uit.no/dataset.xhtml?persistentId=doi:10.18710/4MCRQL that you would like to pass ingest. (At https://opendata.uit.no/dataset.xhtml?persistentId=doi:10.18710/SJ4OQE I don't actually see any tab separated .txt files.)

**Comment by philippconzett** [comment]
Sorry about that. I should have linked to a tab separated uft-8 .txt file that has not been properly ingested. Here is an example:
http://hdl.handle.net/10037.1/10296
See e.g. the file: Database fiskesammensetninger for publisert versjon Maal og Minne 2016_1.txt

**Comment by pdurbin** [comment]
@philippconzett ah, yes, I see what you mean. Thanks.

**Comment by pdurbin** [comment]
As I mentioned at http://irclog.iq.harvard.edu/dataverse/2016-11-14#i_44974 a workaround for me has been to convert my TSV file to a CSV file by using https://github.com/brendano/tsvutils . I cloned the repo and ran `cat /tmp/irclog.tsv | python tsv2csv > /tmp/irclog.csv`

**Comment by pdurbin** [comment]
@oscardssmith does the work you're doing in #3930 help us get support for ingest of TSV files?

**Comment by oscardssmith** [comment]
#3930 makes this a very easy change once we get around to it. It will not, however directly solve this issue.

**Comment by raprasad** [comment]
Also flagging this original issue, ran into it again today.

e.g. Ingest does not occur for .tsv files--even thought ingest files are converted to this format.

Thx.

**Comment by LibrarPotter** [comment]
From reading this thread, am I correct that direct ingest of .tsv files is still not possible?  

My actual goal (ingesting from STATA 14) will be addressed with completion of #2301, but in case this is delayed, I am looking to export to a file format that will import with Two Ravens support.

**Comment by pdurbin** [comment]
@LibrarPotter yes, that's right. Direct ingest of .tsv files is not supported. Now that pull request #3963 has been merged, it's my understanding that it shouldn't be too hard to add this feature but it hasn't been done yet. Your best bet is probably to save down from Stata 14 to Stata 13 for now. If that doesn't work, you could try converted your data into a .csv file. I hope this helps. If not, please feel free to post questions at https://groups.google.com/forum/#!forum/dataverse-community or email support@dataverse.org. You can also try the "Support" button on the installation of Dataverse you're using.

**Comment by pdurbin** [comment]
I'm closing this issue in favor of #4044.
