### ISSUE TITLE
Email: Create account email says welcome to Dataverse 4.0 Beta, should remove beta and maybe 4.0?

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1914]
@eaquigley 
Just created an account and got a nice welcome email. Saw it said welcome to Dataverse 4.0 Beta. Since we are close to releasing, we should remove beta and depending on how it gets 4.0, we may consider removing that. If automatically populated, then ok.

**Comment by eaquigley** [comment]
done in 0bd57136e077d8bc0d8a03a2c8d95cf3370a65f7

**Comment by scolapasta** [comment]
See line 267 of MailServiceBean - we need to move this text to the bundles, as well as the do not reply and dataverse network references (which should be removed / replaced with better text).

**Comment by sekmiller** [comment]
That method is not used for the notification email.  I left all of the original methods in the bean, but the notification emails come from a single method sendNotificationEmail which uses the Bundle.

**Comment by scolapasta** [comment]
@sekmiller we should remove all the old methods
