### ISSUE TITLE
Notification that a user has requested access to a restricted file is extremely limited/need more information

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#1915]
There are three restricted files in this study, doesn't tell me which study and who requested access

![nxhfrykzj70jvr3mkesdglrvzb3lt1qkoubvmrqerhc](https://cloud.githubusercontent.com/assets/8322346/7048777/fa9c9342-dde2-11e4-8bc3-7dcc97bb335d.png)

**Comment by scolapasta** [comment]
That is the messaging for this notification for 4.0/ Post 4.0 we will add more detail. It should however have a link to the file permissions page to get that.

@eaquigley can you take a look at if this is something that just needs to be added to the bundle? You can consult with @sekmiller

**Comment by eaquigley** [comment]
@sekmiller could you also please take out the Please do not reply to this email text and remove Network from the signature so it reads The Dataverse Project instead of The Dataverse Network Project

**Comment by sekmiller** [comment]
Removed the Please do not reply and "Network"

**Comment by sekmiller** [comment]
Added links to datasets and data verses to email notifications.

Also removed extraneous methods

**Comment by sekmiller** [comment]
One last functional update to create dataverse notification was checked in this morning.  new build required for testing.
