### ISSUE TITLE
Empty search on root does not give any results

### ISSUE THREAD

**Issue by suenjedt** [IQSS/dataverse#1919]
... and shows "Null".
I would expect this search to show the complete repository content. 

![screen shot 2015-04-08 at 13 24 42](https://cloud.githubusercontent.com/assets/7300319/7050947/b8a84bba-ddf2-11e4-956f-e5ed10dd833b.png)

**Comment by scolapasta** [comment]
Duplicate of #1338

**Comment by kcondon** [comment]
Closing as duplicate.

**Comment by suenjedt** [comment]
I did an empty search on https://dataverse.harvard.edu/. I get a "null" search instead of the expected complete repository content. 


![screen shot 2015-04-15 at 15 53 20](https://cloud.githubusercontent.com/assets/7300319/7167943/a93ea9a4-e387-11e4-8a3b-ac7adf86e2e8.png)

**Comment by mheppler** [comment]
This behavior is still reproducible in v. 4.2.3 on dvn-build.

**Comment by pdurbin** [comment]
@mheppler really? I can't reproduce it on dvn-build. It's running v. 4.2.3 build 55-6561f58 which includes my fa73991 fix as part of #1338 for 4.2.1.

**Comment by pdurbin** [comment]
Discussed with @mheppler. He was typing the word "null". Closing.
