### ISSUE TITLE
Save Dataset: Concurrent access or stale read results in cannot update metadata. Investigate better workflow.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1921]
Not sure how much work this should get but if I try to save a dataset that had been modified while I was editing or if I am viewing a draft version that became published while I was viewing it and then edit from that view, on saving I get cannot update metadata and essentially a concurrent access error in the log file.

Not sure whether this can be improved but submitting for review.

**Comment by pdurbin** [comment]
@kcondon are you still seeing this problem? Can we close this issue and open a fresh one if this bug crops up again?

**Comment by kcondon** [comment]
@pdurbin Please leave this alone, thanks.

**Comment by mheppler** [comment]
@kcondon, just leaving a comment to check if this have been resolved with _Parallel edits cause multiple draft versions #5550_ which was just merged into 4.15.

**Comment by kcondon** [comment]
@mheppler Still happens but even worse: locks dataset:

<img width="1241" alt="Screen Shot 2019-06-21 at 5 38 28 PM" src="https://user-images.githubusercontent.com/4983816/59952778-6b969700-944b-11e9-8962-f588432cc2b9.png">
