### ISSUE TITLE
Header Navbar "Community & Support" - New Links

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1925]
The link for "Community & Support" under the Support dropdown in the header navbar, needs to be split into two separate links.

From @mcrosas + @eaquigley:

> for the header option of community + support, the link it goes to needs to change
> so one option for community: http://community.dataverse.org/advisory-team.html
> and one option for support: http://dataverse.org/contact/

**Comment by mheppler** [comment]
Added new URLs in the navbar for Support dropdown options Comminuty and Support. Added navbar open-dropdown background styles to stylesheet.

**Comment by kcondon** [comment]
Looks good, closing.
