### ISSUE TITLE
Google Analytics + Sharre: Review other options

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1926]

**Comment by bencomp** [comment]
Sounds related to #1594 ?

**Comment by bencomp** [comment]
This issue is a follow-up from #1774.

**Comment by pdurbin** [comment]
As of Dataverse 4.5.1 we have Piwik support (#3018): http://guides.dataverse.org/en/4.7/installation/config.html#piwikanalyticsid

That's enough for me to close this issue.
