### ISSUE TITLE
Dataset Page, add DatasetVersion id as query string parameter

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#1927]
Add something similar to this method in the DatasetVersionServiceBean:

(Deferring from #1872)

```java
public RetrieveDatasetVersionResponse retrieveDatasetVersionById(Long datasetId, String version){
        msg("retrieveDatasetVersionById: " + datasetId + " " + version);
        if (datasetId==null){
            return null;
        }        
        
        String identifierClause = " AND ds.id = " + datasetId;

        DatasetVersion ds = retrieveDatasetVersionByIdentiferClause(identifierClause, version);
        
        if (ds != null){
            return new RetrieveDatasetVersionResponse(ds, version);
        }
        
        return null;
}
```

**Comment by raprasad** [comment]
To test:
#### By DatasetVersion Id
   - **versionId**
      - Format:  ```dataset.xhtml?versionId={ DatasetVersion.id }```
      - Example: ```dataset.xhtml?versionId=86```  
 
#### By Dataset id
   1. **id** 
      - Format: ```dataset.xhtml?id={ Dataset.id  }```
      - Example: ```dataset.xhtml?id=5```   
   1.  **id** and **DRAFT** 
      - Format: ```dataset.xhtml?id={ Dataset.id }&version={ DatasetVersion.versionState }``` (only for DRAFT)
      - Example: ```dataset.xhtml?id=5&version=DRAFT```   
   1. **id** and **versionNumber** 
      - Format: ```dataset.xhtml?id={ Dataset.idt }&version={ DatasetVersion.versionNumber }```
      - Example: ```dataset.xhtml?id=5&version=2```   *(version 2.0)*   
   1. **id** and **versionNumber** (dot) **minorVersionNumber**
      - Format: ```dataset.xhtml?id={ db id of Dataset }&version={ DatasetVersion.versionNumber(dot)DatasetVersion.minorVersionNumber  }```
      - Example: ```dataset.xhtml?id=5&version=2.1```   *(version 2.1)*   

\cc @kcondon @scolapasta

**Comment by kcondon** [comment]
This went out with last night's patch, for Gustavo's dev convenience. Closing.
