### ISSUE TITLE
Dataverse Browse/Search - Improve Layout

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#1930]
With the real production data migrated over to our test servers, the dataverse page is looking a little too dense. This can be improved with some simple CSS improvements -- mainly bumping down the font-size of most elements, in order to improve the visual hierarchy on the page.

- Facet Links
- Result card description, metadata, citation

![screen shot 2015-04-08 at 5 55 54 pm](https://cloud.githubusercontent.com/assets/687227/7056959/ce0a0dfa-de1e-11e4-974f-0681405b9638.png)

**Comment by kcondon** [comment]
OK, closing.
