### ISSUE TITLE
Guestbook: Guestbook data has blank dataset name if dataset is not published.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1931]
I created a guestbook for a dataset that was not yet published. I downloaded a file, completed the guestbook and checked the collected data. The dataset name was blank. After publishing new downloads have the dataset name.

**Comment by scolapasta** [comment]
discussed with @mcrosas and we'll review what the guestbook / draft behavior should be (should it show guestbook? should it count as download? etc)

**Comment by scolapasta** [comment]
Decided that no guestbook entry for drafts, so this issue goes away.

**Comment by kcondon** [comment]
Guestbook popup does not appear at all, ever for drafts anymore. Closing.
