### ISSUE TITLE
Generate API token through API using username/password

### ISSUE THREAD

**Issue by rliebz** [IQSS/dataverse#1935]
Currently, API tokens can be retrieved for users only if those users already have existing API tokens (https://github.com/IQSS/dataverse/issues/1818). This is only the case for users generated through the API and users who have manually generated an API token through the GUI.

By allowing generation of the API token through the API, it would be possible for services who are currently authenticating by username/password to seamlessly switch to API tokens without additional action from the Dataverse user.

**Comment by pdurbin** [comment]
"Our use case is that we have existing Dataverse users with accounts being authenticated from a stored username/password. I'd like to be able to migrate them over to the API token without them having to do anything" -- @rliebz at http://irclog.iq.harvard.edu/dataverse/2015-04-09#i_18037

**Comment by scolapasta** [comment]
Since we're planning on releasing tomorrow (Friday April 10), we don't have time to fit this in, but we will review for 4.0.1.

**Comment by scolapasta** [comment]
@pdurbin I'd like discuss this before we begin development on it.

**Comment by pdurbin** [comment]
@EvgenyKarataev are you interested in this feature? I noticed you mentioned it at https://github.com/ColFusion/ColfusionServer/issues/11

**Comment by pdurbin** [comment]
@EvgenyKarataev I'm closing this issue but please just say the word and we'll re-open it.
