### ISSUE TITLE
Dataverse Card: Review Information in Cards for Dataverses

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#1938]
![datqlr9jkkjm7hnyktjqkouzlm1_ozhd71opacgur94](https://cloud.githubusercontent.com/assets/8322346/7072473/bcfe955c-deba-11e4-92a6-04f1ae7ee4a4.png)

**Comment by eaquigley** [comment]
Reviewing this issue with @djbrooke and from what I can tell, the only thing that could be added to a dataverse card would be the Category.

**Comment by pdurbin** [comment]
I don't see a lot of value in leaving this issue open. If @sbarbosadataverse  @TaniaSchlatter @dlmurphy @jggautier or @mheppler feel strongly that the category of a dataverse should be added to the dataverse search card, let's re-open this issue and add it. It should be an easy task.
