### ISSUE TITLE
Unable to Login with Shibboleth > 500 Internal Server Error

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#1940]
I was able to login with Shibboleth in build yesterday but today when I select "Harvard University" and click on Continue I am taken to a 500 Error page.

@kcondon @pdurbin do you know what may be causing this? Was there a new build this afternoon?

**Comment by kcondon** [comment]
@posixeleni I was able to log in, can you try again?

**Comment by posixeleni** [comment]
Now working as expected! Closing
