### ISSUE TITLE
Groups: Can't create a group in build/get error to contact support

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#1941]
![lhhiwo8sifli2oq-4gptahld_jb4_iq71zlpn3h50di](https://cloud.githubusercontent.com/assets/8322346/7073516/f9bdf062-dec1-11e4-8653-3da9cb667f45.png)

**Comment by sbarbosadataverse** [comment]
Now it created the role, but does not list it anywhere. Just says "successfully created "sonia."

**Comment by scolapasta** [comment]
We'll need ti figure out why group creation sometimes fails.

**Comment by kcondon** [comment]
This is not currently an issue, closing.
