### ISSUE TITLE
Review DeleteDataFileCommand

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#1942]
Currently this command only works if you already have a draft, but an alternative is if called on a dataset with no draft, create the draft and delete the file from it.

**Comment by scolapasta** [comment]
Attempted to do this in 4.0, but there were issues with it, so that aspect was deferred to 4.0.x.

See issue #1784

**Comment by pdurbin** [comment]
I'm closing this because we'll naturally revisit this when we work on either #2464 or #3419 and I'm sure that now @bsilverstein95 and I have written a book at http://guides.dataverse.org/en/4.7/developers/testing.html there will be API tests! :smile:
