### ISSUE TITLE
Notifications: Account creation online notification mentions beta version

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1943]
Welcome to Dataverse 4.0 Beta build 1027! Please take a look around, try everything out, and check out our Google Group to leave feedback.April 9, 2015 2:16 PM EDT

**Comment by sekmiller** [comment]
Changed notification from taking the appVersion from the Dataverse Service Bean to "4.0".  For future releases we may want to revisit how this is filled rather than manually updating with each release.

**Comment by sekmiller** [comment]
New Build required to capture update of bundle file
