### ISSUE TITLE
Dataverse Card: Link to dataset throws 404 exception

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#1948]
On build, afghanistan dv has a kabul dataset. If I click on the kabul dataset from the additional information link on the dv card, it throws a 404 error. Here is the link:
https://dvn-build.hmdc.harvard.edu/dataset.xhtml?globalId=doi:10.5072/FK2/IZQIXV

**Comment by sekmiller** [comment]
Fixed and checked ion
