### ISSUE TITLE
Dataset Files: Unstyled/Unfriendly 403 forbidden page when trying to download restricted files

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#1950]
Action:

![150_files_-_root_dataverse](https://cloud.githubusercontent.com/assets/1036060/7075649/9dbf9a58-ded1-11e4-908f-28fbae349fd3.png)

Result:

![glassfish_server_open_source_edition_4_1_-_error_report](https://cloud.githubusercontent.com/assets/1036060/7075657/b26b9c5e-ded1-11e4-9930-e76d573b9775.png)

**Comment by pdurbin** [comment]
Duplicate of #1845

**Comment by mheppler** [comment]
Raman, please review if this issue you created is a duplicate of the more recent issue, #2722 Restricted File Download: "Download (selected files)" button above files table is not properly handling restricted files. If it isn't please comment to clarify your issue with more details. Thank you.

**Comment by raprasad** [comment]
thanks, @mheppler.  Closing as this is a duplicate of #2722
