### ISSUE TITLE
Edit Dataset: Allow select all for restrict/unrestrict files

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#1951]
@mheppler showed that there is a hidden table header that contains this functionality
![150_files_-_root_dataverse](https://cloud.githubusercontent.com/assets/1036060/7075878/52d1f6ba-ded3-11e4-9585-1283ce1ce10d.png)

**Comment by eaquigley** [comment]
If we enable this, I'd also like it to work for wanting to select all files to delete them.

**Comment by eaquigley** [comment]
Passing to QA as this was implemented in 4.2 (sorry @kcondon  that there was a ticket for it already)

**Comment by kcondon** [comment]
Works, closing
