### ISSUE TITLE
Metrics for Root Dataverse

### ISSUE THREAD

**Issue by mcrosas** [IQSS/dataverse#1952]
The root dataverse should have the Metrics icons to show downloads, shares, etc - this should show the total for all published datasets.

**Comment by raprasad** [comment]
Just checked in.  Same as dataset page except "downloads" metric is taken from all guestbooks.

@scolapasta

**Comment by raprasad** [comment]
/cc @kcondon 
![root_dataverse](https://cloud.githubusercontent.com/assets/1036060/7091180/05ccf7d6-df76-11e4-8163-89a3b6e2072b.png)

**Comment by mheppler** [comment]
Added "Coming soon..." for Shares metric, since it didn't seem to be working.

Sorry @kcondon -- instead of giving you a new ticket for this last, last second request, I am piggy-backing on a related ticket you have in QA currently.
