### ISSUE TITLE
Dataset Versions: cleanup backing bean, put not 'different version' message into a bundle

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#1953]
Move result text from [`RetrieveDatasetVersionResponse.getDifferentVersionMessage()`](https://github.com/IQSS/dataverse/blob/0b585c2b5984a5eb33e1f005a33f83dcece936b3/src/main/java/edu/harvard/iq/dataverse/DatasetVersionServiceBean.java#L75) into a bundle

<img width="990" alt="screen shot 2017-06-14 at 4 06 04 pm" src="https://user-images.githubusercontent.com/687227/27152309-7498d27a-511b-11e7-8b2a-1eac760c6282.png">

**Comment by pdurbin** [comment]
Still an issue. Here's the text as of 4.6.1: https://github.com/IQSS/dataverse/blob/v4.6.1/src/main/java/edu/harvard/iq/dataverse/DatasetVersionServiceBean.java#L106
