### ISSUE TITLE
Google analytics for Dataverse.harvard.edu

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1955]
Need to take out the GA code currently in and replace it with the GA code for Dataverse.harvard.edu

**Comment by eaquigley** [comment]
Code for dataverse.harvard.edu has been emailed to @raprasad 

Needs to be placed in a way that it shows up on all pages. We've done this for dvn-build and dataverse-demo already.

**Comment by raprasad** [comment]
Updated.
- Placed in a separate .xhtml file: google-analytics-snippet.xhtml
- This snippet is included by the dataverse_template.xhtml

commit: https://github.com/IQSS/dataverse/commit/3a84ca0d39eac275657344f917b62d850dd9f8b7

**Comment by raprasad** [comment]
reference: http://stackoverflow.com/questions/4245132/google-analytics-api-filter-by-uri
