### ISSUE TITLE
Select dataverse categories/subject/contact email metadata

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1956]
We need to go through and select categories for dataverses so the the facet doesn't read Uncategorized 2739.

**Comment by pdurbin** [comment]
@scolapasta and I were planning on **not** indexing "Uncategorized" so I'll use this ticket for that change if that's ok. That way we can change dataverses from "Uncategorized" at our leisure.

**Comment by eaquigley** [comment]
Cool with me as long as you pass this ticket back to me after you finish your part. I need this ticket for doing the selecting categories work.


On Apr 10, 2015, at 9:28 AM, Philip Durbin <notifications@github.com<mailto:notifications@github.com>> wrote:


@scolapasta<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_scolapasta&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=Y9aY3P6kFFpmMLaYYO_id08dS3gL1xWMQuI2CZ74PoI&m=IDo7ycCCZW6zYy6xr2TykutfASxVaxL80-FrWDK7RbM&s=cS1bSLEJR31_FzaWnm_uVSzTpmNdw2NamYAFhG2oig8&e=> and I were planning on not indexing "Uncategorized" so I'll use this ticket for that change if that's ok. That way we can change dataverses from "Uncategorized" at our leisure.

**Comment by pdurbin** [comment]
@scolapasta please review 8496b42

You can create a pull request from that commit at https://github.com/IQSS/dataverse/compare/1956-no-index-uncategorized and merge it yourself if you like.

**Comment by pdurbin** [comment]
@scolapasta and I discussed the commit and agreed to merge it into master, which I just did.

@kcondon I'm giving this ticket to you for a build. Then can you please give it to @eaquigley for selecting categories?

**Comment by kcondon** [comment]
@eaquigley passing to eq

**Comment by eaquigley** [comment]
@suenjedt this is the ticket for selecting categories for dataverses as you do post deployment curation tasks. selecting categories found under the Edit button for a dataverse->then General information

**Comment by sbarbosadataverse** [comment]
We need to meet with Sunje, Kevin, Gustavo, together with "subjects" and "contact emails"
to create scripts to get this done. Also review general facets logic that can be cleaned up with scripts

**Comment by sbarbosadataverse** [comment]
You will be writing the scripts so this doesn't need to be assigned to me.

**Comment by scolapasta** [comment]
After discussing with @sbarbosadataverse @kcondon @eaquigley we decided to modify the workflow to allow save on these pages and use N/A for the requred dataset fields. This was opened as issue #2448.

Separately @kcondon added researcher category to all former scholar dataverses.

**Comment by kcondon** [comment]
Work completed, closing.
