### ISSUE TITLE
Dataset Page License and Terms Tab - Allow html

### ISSUE THREAD

**Issue by sekmiller** [IQSS/dataverse#1958]
Some of the dataset terms in the migrated production data include HTML, and we need to be able to display it as HTML and not text.

![screen shot 2015-04-10 at 11 04 27 am](https://cloud.githubusercontent.com/assets/687227/7090544/be49c140-df71-11e4-9f57-adc40816973a.png)

**Comment by mheppler** [comment]
Fixed display of HTML in terms and additional information fields in the Terms tab on the dataset page.
