### ISSUE TITLE
Set up Featured Dataverse

### ISSUE THREAD

**Issue by mcrosas** [IQSS/dataverse#1960]
Include:
CFA
DataPASS
PSI
Avahan
Murray
IFPRI
WorldForestry
AJPS
MRI

**Comment by scolapasta** [comment]
Also, add facets to these dataverses.

**Comment by eaquigley** [comment]
Done. Discovered #1999 while doing this so each time the general info is changed, I have to go and redo the featured dataverses. Obviously not ideal but can be worked around for the launch. Will need to fix this in the patch for this week.
