### ISSUE TITLE
Delete test Dataverses

### ISSUE THREAD

**Issue by mcrosas** [IQSS/dataverse#1963]
Go over empty test dataverses and decide which ones to delete.

**Comment by sbarbosadataverse** [comment]
@mcrosas 
Can I go through and delete without double checking with you? It's mostly obvious which should be removed.

**Comment by mcrosas** [comment]
yes

On Wed, Apr 15, 2015 at 9:42 AM, sbarbosadataverse <notifications@github.com

**Comment by eaquigley** [comment]
Can we compare the test dvs deleted to the email addresses for user accounts that bounced when the email announcements were sent?

**Comment by mcrosas** [comment]
Good idea @eaquigley @sbarbosadataverse

**Comment by eaquigley** [comment]
In google drive, I have created a spreadsheet called User Emails + Test DVs Deleted in 4.0 @sbarbosadataverse in the second tab of that spreadsheet, please input the information regarding the test dvs you are deleting. (can't share the link here because of privacy of emails)

**Comment by sbarbosadataverse** [comment]
moved to dataverse -curation
