### ISSUE TITLE
Set Subjects for datasets

### ISSUE THREAD

**Issue by mercecrosas** [IQSS/dataverse#1964]
After release, assign subjects to datasets at the database level, for cases that we know easily.

**Comment by mcrosas** [comment]
Spreadsheet with all dataverses and try to map subjects for their datasets, when possible.

**Comment by posixeleni** [comment]
@kcondon  : Is it possible to get a database report with the names and links to all Dataverses that exist in 4.0 (list which ones are published and unpublished).

We will start categorizing just the published ones but want to have the unpublished ones on hand just in case.

**Comment by suenjedt** [comment]
FYI, as per the categories for the disciplines, we used the following in the past, https://www.hesa.ac.uk/jacs2 [established in the UK; the highest level is rather comprehensive already I find ]. OECD has one, http://www.oecd.org/science/inno/38235147.pdf [first level is very general].

**Comment by posixeleni** [comment]
@kcondon sent me a list of ALL dataverses https://docs.google.com/spreadsheets/d/1D0bt-8T98bZMLwH4g9uSkueVeQh-u8M7B7RBxQfcQXs/edit?usp=sharing so I will go through them and see if we can assign subjects to certain dataverses for all their datasets

Will need to work with @scolapasta afterwards to discuss how these would be implemented programatically. Understood that this would involve a minor version change.

**Comment by posixeleni** [comment]
Based on @suenjedt comment above I have created a spreadsheet with proposed changes to Subjects using the OECD taxonomy https://docs.google.com/spreadsheets/d/1PwxDyPv83BA6ueDimM2xavgNIUP2d2qQYsjIyVuy59E/edit?usp=sharing

**Comment by posixeleni** [comment]
Updating this ticket is dependent on #2083 being completed by development since we need update scripts to be able to change metadata now that 4.0 is released.

**Comment by sbarbosadataverse** [comment]
Provide a list of dataverses  and their subjects to Gustavo--run back end script

**Comment by jggautier** [comment]
Closing this ticket, which was about applying Dataverse's current 14 subject terms to as many existing Harvard Dataverse datasets as possible. That work has stopped in light of current work on increasing the number of subject terms (which started with a look at using OECD's vocabulary, mentioned in [a comment in this issue](https://github.com/IQSS/dataverse/issues/1964#issuecomment-99121605), and continues with discussions about using the [FAST vocabulary](http://experimental.worldcat.org/fast/) ([1](https://groups.google.com/d/msg/dataverse-community/TNRb7hoJd8Q/TcSoJknkAAAJ), [2](https://groups.google.com/d/msg/dataverse-community/uDl01J8qMbg/68G6om-BAQAJ))).
