### ISSUE TITLE
Set CC0 to all datasets with no terms of use 

### ISSUE THREAD

**Issue by mcrosas** [IQSS/dataverse#1965]
Datasets that used to have only Network Terms of Use should be set to CC0.

**Comment by mcrosas** [comment]
Terms of Use
Confidentiality Declaration 
Special Permissions 
Restrictions 
Citation Requirements 
Depositor Requirements 
Conditions 
Disclaimer

**Comment by scolapasta** [comment]
We will set the latest released versions and draft versions of each dataset with no terms of use (fields that @mcrosas added) to CC0.

**Comment by scolapasta** [comment]
The queries for reference:


-- update all versions to NONE
update dataseversion set license='NONE';

-- update all released with no terms of use to CCO
update datasetversion set license='CC0' 
where 1=1
and TermsofUse is null
and ConfidentialityDeclaration is null
and SpecialPermissions is null
and Restrictions is null
and CitationRequirements is null 
and DepositorRequirements is null 
and Conditions is null
and Disclaimer is null
and dataset_id || '_' || versionnumber in (
select dataset_id || '_' || max(versionnumber) from datasetversion dsv, dvobject ds
where dsv.dataset_id = ds.id
and dsv.versionstate != 'DRAFT'
and dsv.versionstate != 'DEACCESSIONED'
and ds.owner_id not in 
(select dataverse_id from harvestingdataverseconfig)
group by dataset_id
);


-- update all draft with no terms of use to CCO
update datasetversion set license='CC0' 
where 1=1
and TermsofUse is null
and ConfidentialityDeclaration is null
and SpecialPermissions is null
and Restrictions is null
and CitationRequirements is null 
and DepositorRequirements is null 
and Conditions is null
and Disclaimer is null
and versionstate = "DRAFT';

**Comment by mcrosas** [comment]
Tested. Looks good.
