### ISSUE TITLE
Review creation of DS identifiers

### ISSUE THREAD

**Issue by sekmiller** [IQSS/dataverse#1967]
Currently the identifier is a random 6-letter string. The database now enforces uniqueness.  It is conceivable that two users could generate the same identifier at the same time.  The first would save properly and the second would throw a database constraint error.  Also take a look at registration to make sure that doi registrations that fail due to unique constraint are handled properly.

**Comment by pdurbin** [comment]
@sekmiller now that #3654 (a request from @pameyer ) is done, can we close this issue?

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
