### ISSUE TITLE
Investigate if code supports migrating of a non 1.0 version

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#1968]
in order to migrate T3 dataset.

**Comment by pdurbin** [comment]
@scolapasta can we close this issue?

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
