### ISSUE TITLE
Get citations count

### ISSUE THREAD

**Issue by mercecrosas** [IQSS/dataverse#1970]
Need to get citations count from DataCite/CrossRef

**Comment by pdurbin** [comment]
@mercecrosas what should we do with the citations count from DataCite/CrossRef once we have them? Would they be displayed in the UI?

**Comment by jggautier** [comment]
When Dataverse implements metrics using Make Data Count's standard (https://github.com/IQSS/dataverse/issues/4821), the usage metrics will include citation counts. Since citation counts will be involved in that discussion, I'm going to close this issue.
