### ISSUE TITLE
Change Handles and DOIs urls

### ISSUE THREAD

**Issue by mcrosas** [IQSS/dataverse#1977]
This is to remember make the changes so all handles and DOIs resolve  to the new dataset urls in dataverse.harvard.edu , after migration.

**Comment by posixeleni** [comment]
Changed status to critical since this is now affecting how users access datasets since they are being pointed to 3.6.2 which does not allow them to do anything with the data.

CC/ @eaquigley

**Comment by sekmiller** [comment]
Coded an api to handle doi cases.
to call use:
$SERVER/api/datasets/11/modifyRegistration?key=a8c39fb7-1038-49bd-98c8-6eb918c255c3

where the dataset db id comes directly after "datasets/" and key= the user's api key

**Comment by sekmiller** [comment]
Reviewed the code with Leonid so he will know where to add the hdl updates.

**Comment by bmckinney** [comment]
Greetings, we are going to link a few DASH articles to their research data in an upcoming DASH release. They all use handles instead of DOIs so it would be great to have them pointing to the new URL when we announce/promote this new linking.

**Comment by posixeleni** [comment]
@bmckinney when do you expect this upcoming DASH release? The reason I ask is because we are planning to have these dataset handles and DOIs redirecting in the very near future.

**Comment by bmckinney** [comment]
Hi Eleni,

I hope to get a new release out on Weds. April 29th that would include
this. No real pressure though, we can simply hold off on any announcements
about this feature until you're ready.

Thanks!

--Bill

**Comment by posixeleni** [comment]
@bmckinney we just completed the DOI and Handle re-directs to go to Dataverse 4.0 so you can definitely include Dataverse in your announcement. Please let us know when you send this out so we can promote it too!

**Comment by bmckinney** [comment]
will do, thanks!

**Comment by mcrosas** [comment]
Left to do: CfA handles with different prefix

**Comment by sbarbosadataverse** [comment]
@landreev 
Hi Leonid, Just checking on the last bit of work left to do on this ticket:  Left to do: CfA handles with different prefix

Thanks

**Comment by eaquigley** [comment]
CfA ones were fixed and this was discussed in an RT ticket. Passing to QA to close this ticket.
