### ISSUE TITLE
Transfer subnetwork "ownership" appropriately

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#1978]
In 3.6 subnetworks were created and owned by network admins; but for 4.0 we should transfer PSI to the, ubiquity to them, etc.

Steps to do this would be:
- assign admin roles to the correct user
- change dataverse contact email

**Comment by mcrosas** [comment]
CfA
PSI
Ubiquity Press
GSD

**Comment by posixeleni** [comment]
Contacted folks from Dataverses indicated above and awaiting reply. GSD and PSI are all set.

**Comment by posixeleni** [comment]
CfA are all set. Awaiting reply from Ubiquity Press.

**Comment by posixeleni** [comment]
All set with Ubiquity Press as well. This is now resolved so I am closing this ticket.
