### ISSUE TITLE
Can't delete a draft if it has a download

### ISSUE THREAD

**Issue by mcrosas** [IQSS/dataverse#1979]
You cannot delete a draft that has a download.

This is the error from the log:
Caused by: org.postgresql.util.PSQLException: ERROR: update or delete on table "dvobject" violates foreign key constraint "fk_guestbookresponse_datafile_id" on table "guestbookresponse"
  Detail: Key (id)=(10) is still referenced from table "guestbookresponse".

we'll decide on Monday what's the best solution for this.

**Comment by sekmiller** [comment]
If a draft has a previous download you still won't be able to delete it.  We'll need to cleanup the DB for prior gb responses.  The fix that will be part of the next build prevents responses from being created on draft versions of a dataset - both before and after "original publication."

**Comment by kcondon** [comment]
Now you can delete a draft that has a download, downloads on draft are not recorded. Closing.
