### ISSUE TITLE
Dataset page: file info says 0 bytes--but the files have bytes

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#1984]
Example: https://dataverse.harvard.edu/dataset.xhtml?persistentId=hdl:1902.1/21919
![precinct-level_election_data_-_election_data_archive_dataverse](https://cloud.githubusercontent.com/assets/1036060/7116735/d3772ea2-e1c1-11e4-99d1-cf47f8948e45.png)

/cc @scolapasta @landreev

**Comment by kcondon** [comment]
OK, now showing bytes, closing
