### ISSUE TITLE
Download Files: Select All Checkbox

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1988]
Need a way for a user to select all files in the dataset to download.

**Comment by kcondon** [comment]
Also see #639

**Comment by eaquigley** [comment]
Talked to users at IASSIST and this is really crucial to them to have in as soon as possible

**Comment by eaquigley** [comment]
implemented in 4.2. there is a checkbox at the top outside of the files table. passing to QA to test.

**Comment by kcondon** [comment]
Yes, check box is there but throws exception. Opened a separate ticket, closing.
