### ISSUE TITLE
Files: Show number of files in a dataset

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1989]
Need to add how many files are in a dataset in the files tab.

**Comment by mheppler** [comment]
Reviewed mocked up screenshot with UI team and will be moving this into development.

![screen shot 2015-05-11 at 11 00 34 am](https://cloud.githubusercontent.com/assets/687227/7568209/722e4ca6-f7cf-11e4-826d-28345c735505.png)

**Comment by mheppler** [comment]
Added file count to the top of the Files tab on the Dataset page.

Made the "Files" vs. "File" dynamic in the bundle. Count also displays for the Upload + Edit Files workflow.

**Comment by raprasad** [comment]
related #2196

**Comment by eaquigley** [comment]
Number of files is now showing. Closing ticket.
