### ISSUE TITLE
Dataset: Show on Create Page CC0 default

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1990]
Add into the create dataset page a section showing CC0 will be selected.

**Comment by eaquigley** [comment]
Something else to think about as well:
-[ ] Add CC0 waiver image to dataset page outside of the tab so it is easier to see

**Comment by eaquigley** [comment]
If we do this when a user hits publish, as mocked up: https://iqssharvard.mybalsamiq.com/projects/termsofuse-dataverse40/1C%20Terms%20of%20Use%20and%20Licensing then that should fix the problem.

**Comment by posixeleni** [comment]
:+1:

**Comment by pdurbin** [comment]
> Add into the create dataset page a section showing CC0 will be selected.

I agree that we should make it clear to users which license or waiver has been selected by default. Check out this tweet at https://twitter.com/ruebot/status/938861697766477827 (emphasis mine):

> "While I'm very sympathetic to it, it really bugs me that OCUL's Dataverse still defaults a submission to Public Domain, and **it's not obvious that it does it unless you're really looking**."

**Comment by pdurbin** [comment]
In a design meeting today with @TaniaSchlatter @dlmurphy @djbrooke @scolapasta @mheppler @jggautier and myself we agreed to leave a comment on this issue to indicate that showing which license/waiver is used by default is under consideration for Dataverse 5. The doc we discussed was "CC0 visibility design doc" at https://docs.google.com/document/d/10lQeIbfqgFd8JOBXYznxv2AMHFXxhSlYxyEaOoe00G0/edit?usp=sharing

#1753 is related.

**Comment by MrK191** [comment]
> In a design meeting today with @TaniaSchlatter @dlmurphy @djbrooke @scolapasta @mheppler @jggautier and myself we agreed to leave a comment on this issue to indicate that showing which license/waiver is used by default is under consideration for Dataverse 5. The doc we discussed was "CC0 visibility design doc" at https://docs.google.com/document/d/10lQeIbfqgFd8JOBXYznxv2AMHFXxhSlYxyEaOoe00G0/edit?usp=sharing
> 
> #1753 is related.

Would it be possible to open the document?

**Comment by pdurbin** [comment]
> Would it be possible to open the document?

@MrK191 sorry, I don't have access to open the doc. I would if I could!

> If we do this when a user hits publish, as mocked up: [non-working link to mockup] then that should fix the problem.

We have this now. On publish, the license is shown. Here's a screenshot from 5.11.1:

<img width="1251" alt="Screen Shot 2022-10-04 at 8 24 41 PM" src="https://user-images.githubusercontent.com/21006/193954014-6c06b334-89c7-4438-bf87-95425cc88af8.png">

Is that enough to close this issue? I think so. Dear reader, what do YOU think?

**Comment by jggautier** [comment]
I just made the Google Doc publicly viewable again. It used to be public but it became restricted somehow.

I agree with @pdurbin. More recent versions of the Dataverse software have changes designed to make "it clearer to users which license or waiver has been selected by default".
