### ISSUE TITLE
Townsend Dataverse Restricted Datasets

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#1996]
They require assistance removing/moving their restricted datasets off 3.6 and into their own (tbd) space--
will remove any we moved to 4.0 as unpublished (if they were restricted datasets in 3.6)

**Comment by mcrosas** [comment]
@sbarbosadataverse  provide a list

**Comment by sbarbosadataverse** [comment]
Gustavo was cc'd in email to Townsend's RA to provide us with IDs for all "unpublished" datasets that need to be removed from dataverse. The task is to also provide them a dump of DDIs and datafiles for these datasets.

**Comment by sbarbosadataverse** [comment]
moved to dataverse-curation
