### ISSUE TITLE
Cannot Edit General Information without Deleting Selected Featured Dataverses

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#1999]
Noticed while setting up dataverse.harvard.edu that you cannot have both featured dataverses and facets. if you have one selected and do the other, it deletes the one already set up.

**Comment by eaquigley** [comment]
Further investigation shows that changing anything on the General Information page deletes the featured dataverses.

**Comment by scolapasta** [comment]
Cleaned up logic around the featured dataverses save. Please test all aspects of Dataverse Page. (sub pages (permission, theme, etc), not changed)

**Comment by kcondon** [comment]
OK, can edit general info and set and remove featured dvs. Closing.
