### ISSUE TITLE
html showing up in facets for affiliation

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2000]
https://dataverse.harvard.edu/dataverse/IFPRI

https://dataverse.harvard.edu/dataverse/IFPRI?q=&fq0=affiliation_ss%3A%22International+Food+Policy+Research+Institute%22&types=dataverses%3Adatasets&sort=dateSort&order=desc

**Comment by pdurbin** [comment]
We starting stripping HTML while indexing in #1332

@scolapasta and @posixeleni should authorAffiliation allow HTML? Check this out from https://dataverse.harvard.edu/dataset.xhtml?persistentId=hdl:1902.1/17988

![assessing_the_potential_of_farmer_field_schools_ ffs _to_fight_poverty_and_foster_innovation_in_east_africa_-_international_food_policy_research_institute_ ifpri _dataverse_-_2015-04-13_18 02 03](https://cloud.githubusercontent.com/assets/21006/7126470/73c73858-e207-11e4-8e79-92644c430199.png)

**Comment by posixeleni** [comment]
This was something we supported in 3.6 see study here: http://hdl.handle.net/1902.1/17988

So I think we should continue to allow it if possible. Otherwise we should strip the HTML from the display in the UI

**Comment by pdurbin** [comment]
@posixeleni the rule established in #1332 is that if the tsv says the "fieldType" is "textbox" that we strip HTML before indexing. Does that mean you'll be changing the "fieldType" for authorAffiliation from "text" to "textbox"?

**Comment by posixeleni** [comment]
@Pdurbin @gdurand not sure… depends how many people are actually putting HTML in their Author Affiliation field. Is there a way for us to find out which Dataverses are doing this? I don't think a text box would make sense UI-wise for something like Author Affiliation.

**Comment by pdurbin** [comment]
@posixeleni instead could your add a boolean to every field called "stripHtml" that could be set to true or false?

**Comment by posixeleni** [comment]
@scolapasta can we?

**Comment by posixeleni** [comment]
I did a bit more research and as far as standard metadata practice goes for Author Affiliation it does not ask users to enter a URL for Affiliation so this is additional information that they are adding into the metadata that is not suppose to be there and may cause interoperability issues when exporting to other systems. 

This may just be easier to strip the HTML from Author Affiliation.

**Comment by pdurbin** [comment]
@posixeleni I think the tsv file should somehow indicate when a field permits HTML so that we can display this in the UI like this:

![html-allowed](https://cloud.githubusercontent.com/assets/21006/7240530/a4eb5810-e77f-11e4-93d7-1078d0b5cd19.png)

**Comment by posixeleni** [comment]
@pdurbin yes I understand. I can put this into the tsv but @scolapasta will need to let me know when/if/how to implement this into the tsv.

Re-assigning to @scolapasta to decide

**Comment by scolapasta** [comment]
Moving to post curation for clean up of migrated datasets.

**Comment by sbarbosadataverse** [comment]
being tracked in dataverse-curation
