### ISSUE TITLE
Permissions: Not able to search by username

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2001]
Tried searching for a user to assign them a role in a dataverse but was not able to search by username. Even tried with @ and it didn't work. Was able to find them by using their first and last names.

**Comment by pdurbin** [comment]
Reported here as well: https://help.hmdc.harvard.edu/Ticket/Display.html?id=196347

**Comment by eaquigley** [comment]
tried this in demo and it appears to be working now. passing to @kcondon to test and close.

**Comment by kcondon** [comment]
Works, closing
