### ISSUE TITLE
Widget links leave dataverse

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#2002]
Since the paging (and sorting) are links, they do a get. And in this case the search include fragment assumed that the dataverse would be provided by the alias in the url. But in the iframe version it is not there. So the link loads what it thinks it should which is page X of the root dataverse (since it doesn't have an alias or id reference).

(maybe the iframe code should be prettyfaced to take alias.

So:

https://dataverse.harvard.edu/iframe.xhtml?q=&types=dataverses%3Adatasets&sort=nameSort&order=asc&page=2

would be

https://dataverse.harvard.edu/iframe/king?q=&types=dataverses%3Adatasets&sort=nameSort&order=asc&page=2

or something like that.

**Comment by scolapasta** [comment]
iframe now uses pretty faces - fix should work for open scholar once we push (no change needed on their side)

**Comment by kcondon** [comment]
They now don't leave, closing.
