### ISSUE TITLE
Installation Branding - Customize/configurable navbar logo + links, landing pg etc.

### ISSUE THREAD

**Issue by bencomp** [IQSS/dataverse#2003]
At [DANS](http://www.dans.knaw.nl) we would like to upgrade our service [DataverseNL](https://dataverse.nl) (formerly known as Dutch Dataverse Network) to use Dataverse 4. We fiddled with a few settings, but they did not result in promising layout changes.

Our options seem to be:
- customise the root dataverse: name and description, affiliation, featured dataverses etc. The result could be that the root dataverse is named "DataverseNL Dataverse", as the " Dataverse" suffix for names of dataverses is fixed.
- customise the application: HTML (templates or snippets) and CSS, perhaps the `Bundle.properties`. It appears that the value for the localisable string _Dataverse_ in Bundle.properties is used for both the application name in the top menu bar as well as most references to the word "Dataverse". For example, when we changed the Bundle.properties, the top menu bar shows "DataverseNL" (which is good), but the root dataverse became the "Root DataverseNL" (which is bad).

![screen shot 2015-04-14 at 14 39 45](https://cloud.githubusercontent.com/assets/1303898/7136761/35371dbc-e2b4-11e4-8e30-d4faaf78fadd.png)

We would like customising the application to be more a matter of configuration than programming. Allowing to change the "service" name (i.e. the application name) independently of the Dataverse concept seems a minimal requirement. This and other possible customisation configuration options should be documented.

(This appears unrelated to another issue called "Customization", #1768)

**Comment by pdurbin** [comment]
@mheppler @eaquigley @scolapasta @mcrosas what do you think of this?

"Dataverse" is currently appended in various places, making it difficult for @bencomp to brand his installation the way he'd like.

**Comment by mcrosas** [comment]
@bencomp this makes sense. So, to clarify, we would have a configurable label for the "Dataverse" displayed at the top menu bar which can be customized for each installation to distinguish "Harvard Dataverse" from "DataverseNL" or from any other name from another installation. And we would leave the "Dataverse" term used through the application (which applies to the Dataverse object, not the installation instance) as defined in the resource.properties ("Dataverse" ). Yes, if that's the case, I think this straightforward and will cause less confusion.

Adding to In Review short term milestone, to first review with UI team @eaquigley @mheppler

**Comment by bencomp** [comment]
@mcrosas yes, I don't want to change the name of the Dataverse concept of a container for data containers and sets, I would like to be allowed to change the application (instance) name.

**Comment by mcrosas** [comment]
This makes sense and seems pretty straightforward. I'm adding it to 4.0.1.

**Comment by lmaylein** [comment]
Regarding the initial request and the two options: Are there any plans to support html templates/snippets (as in Dataverse 3.x) or CSS (includes) on the level of instance or individual dataverses?

**Comment by djbrooke** [comment]
Thanks @scolapasta for getting more information about this!

**Comment by mheppler** [comment]
Custom hmpg example: [Open Research Data Platform](http://opendata.pku.edu.cn/) (Peking University).

<img width="1280" alt="screen shot 2016-09-20 at 3 18 59 pm" src="https://cloud.githubusercontent.com/assets/687227/18685428/f78ad816-7f45-11e6-88af-17bc348f4975.png">

**Comment by pdurbin** [comment]
Right now "About" in the nav bar is hard coded to http://dataverse.org but there's a discussion about making this configurable at https://groups.google.com/d/msg/dataverse-community/2WlHl8gD2q4/NSHELerTCAAJ

In addition, I think small changes to the footer should be considered, such as #3379.

**Comment by mheppler** [comment]
Also make sure that as part of any customization changes to the Harvard Dataverse, we apply the same layout changes to the static maintenance pg (#2588).

**Comment by mheppler** [comment]
From #3401 @donsizemore -- would like to be able to set UNC's logo (in header navbar) à la Scholars' Portal

**Comment by donsizemore** [comment]
per request of @pdurbin: I'd personally want the various "About," "Powered by" and "Hosted by" homepage links pulled together into an "About" drop-down in the nav-bar. whether that's a move or a duplication could be up to you all, but if I personally want to know something about a web site/service, that's where I'd look first. So, "About" could contain entries for the software itself, the dataverse instance, and the hosting/curating organization.

**Comment by pdurbin** [comment]
I'm glad I asked (at http://irclog.iq.harvard.edu/dataverse/2016-11-07#i_44685 ) because the answer was different than what I expected! 😄

**Comment by tdilauro** [comment]
I took a stab at cleaning up the clunky way I managed the parameters for the [JHU Data Archive](https://archive.data.jhu.edu) branding customizations. These are much more amenable to adoption by other DV4 instances.

There are two new branches for this on my Dataverse fork at 
- [initial changes atop v4.6, where I need them](https://github.com/tdilauro/dataverse/tree/2003-instance-branding-on-v4.6) and 
- [v4.6 changes rebased to the 'develop' branch](https://github.com/tdilauro/dataverse/tree/2003-instance-branding).

Some notes in the commit message.

**Comment by mheppler** [comment]
This issue has been broken down into three new issues, so that it can be easily tracked through development.
- *Navbar Customization - Logo, Name, Nav links for About and Guides #3637*
- *Footer Customization - Logo, Name, Nav links for About and Guides #3638*
- *Homepage Customization - Optional new landing page for installation #3639*

Thank you for your input @bencomp @lmaylein @donsizemore @tdilauro! Please check those new issues to make sure that we covering your requested features.

@tdilauro I will be following up with you regarding your branched code.

**Comment by tdilauro** [comment]
The approach I mentioned in a [previous comment on this issue](https://github.com/IQSS/dataverse/issues/2003#issuecomment-278955920) is probably applicable to all three of the newly spawned customization issues(#3637, #3638, #3639). Representative changes are in [this branch of my fork of dataverse](https://github.com/tdilauro/dataverse/tree/2003-instance-branding).

In addition, I just committed changes to a [rough ansible role](https://github.com/tdilauro/dataverse-ansible-role/releases/tag/v1.1) to accommodate changes in the above-mentioned branch. 

These changes are deployed in [our production instance[(archive.data.jhu.edu).
