### ISSUE TITLE
My Unpublished Data doesn't load

### ISSUE THREAD

**Issue by mcrosas** [IQSS/dataverse#2004]
Going to unpublished data takes forever, and it never loads. I tried that with my personal account. @cchoirat had the same problem.

**Comment by eaquigley** [comment]
I've noticed this before but it was a specific case where I had clicked on Notifications or Account Information then clicked on My Unpublished Data. Did you both go directly to My Unpublished Data and have this issue? @mcrosas @cchoirat

**Comment by cchoirat** [comment]
I did click on Account Information (to try to change the email associated
with the account).

On Tue, Apr 14, 2015 at 9:41 AM, Elizabeth Quigley <notifications@github.com

**Comment by mcrosas** [comment]
I tried both going directly and not going directly - it always had this
problem.

**Comment by scolapasta** [comment]
Reproduced with both @mcrosas @cchoirat , also locally. When going directly to My unpublished data works fine. However when first going to to Account Information or Notifications, then to My Unpublished Data, you get the spinner.

**Comment by raprasad** [comment]
To QA:
- log in
- click on username (upper right corner)
- select either "notifications" or "account information" (*not* "My Unpublished Data" )
   - should land on the selected tab
- go to "My Unpublished Data" tab

/cc @kcondon @scolapasta

**Comment by kcondon** [comment]
OK, works, closing
