### ISSUE TITLE
Create new account: General ToU show incorrectly

### ISSUE THREAD

**Issue by suenjedt** [IQSS/dataverse#2006]
- I think there are either typos or/and formatting issues
- I see many question marks. Don't think thats correct. 

![screen shot 2015-04-14 at 11 30 28](https://cloud.githubusercontent.com/assets/7300319/7140533/d67c2e26-e299-11e4-9da3-9d9e9202f746.png)

**Comment by mheppler** [comment]
I believe this is a duplicate, and we're already tracking this issue with a "Dataverse 4.0: Release Patch" ticket, Terms of Use - HTML Formatting #1863.

**Comment by scolapasta** [comment]
Passing to QA as a duplicate,

**Comment by kcondon** [comment]
Closing as duplicate.
