### ISSUE TITLE
Searching and browsing without loggin into DV, when you log-in (with Shibboleth) you are taken to root dataverse and lose your search

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2007]
If I'm in a dataverse and I decide to log in, I'm taken back to the root, and lose my search. In 3.6 we used to be taken back to the page we were on

**Comment by pdurbin** [comment]
@sbarbosadataverse yes, this is frustrating for Shibboleth users, I'm sure. We are tracking this problem at #1551 so if you feel like that ticket accurately captures the problem, please close this one. (It's somewhat technically worded.)

**Comment by sbarbosadataverse** [comment]
sounds good. I'll close this. thanks

**Comment by sbarbosadataverse** [comment]
already in ticket #1551
