### ISSUE TITLE
Harvested dataverses which have been linked to individual dataverses are not shown

### ISSUE THREAD

**Issue by suenjedt** [IQSS/dataverse#2008]
An example 
https://dataverse.harvard.edu/dataverse/PVM and http://thedata.harvard.edu/dvn/dv/PVM

![screen shot 2015-04-14 at 13 10 27](https://cloud.githubusercontent.com/assets/7300319/7142593/c82308a0-e2a7-11e4-8148-fb8b3f0536f2.png)
![screen shot 2015-04-14 at 13 10 15](https://cloud.githubusercontent.com/assets/7300319/7142594/c82eb8bc-e2a7-11e4-9ac1-803822682bbd.png)

**Comment by mcrosas** [comment]
Missing:

- Harvested linked datasets

**Comment by sbarbosadataverse** [comment]
As we find these issues, we can discuss in dataverse-curation repo
