### ISSUE TITLE
Permissions: Popups Not Scrollable

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2009]
Searching for a user, can't scroll to the remaining of the list.
Also, if you attempt to expand the dialogue box, then the box shift and can only see "save and cancel" and can't fix by making the box smaller/larger

**Comment by sbarbosadataverse** [comment]
![hzafxahkwonenm0toasemav6vusxdmapdz6t_jm1occ](https://cloud.githubusercontent.com/assets/8322346/7165760/a77ffa42-e377-11e4-8ec2-ecd0f2a37ef3.png)

![m5nxcvilcoeaztilata_xevngzjitidr8aptvmk9u8y](https://cloud.githubusercontent.com/assets/8322346/7165762/a92b0850-e377-11e4-8e5e-b28272828170.png)

**Comment by mheppler** [comment]
![screen shot 2015-04-15 at 2 03 12 pm](https://cloud.githubusercontent.com/assets/687227/7165836/171a48c6-e378-11e4-8226-f498ade8f086.png)

**Comment by mheppler** [comment]
![screen shot 2015-04-15 at 3 01 35 pm](https://cloud.githubusercontent.com/assets/687227/7167086/4f94444c-e380-11e4-8419-79a86ec8a839.png)

**Comment by mheppler** [comment]
Added some scrolling and height attributes on autoComplete and dataTable components to fix issues with long lists in the Permissions workflows. Also added utlitized some javascript, CSS to improve popup resizing.

**Comment by kcondon** [comment]
OK, shows about 5 rows and a scroll bar. Works, closing.
