### ISSUE TITLE
Zip file upload functionality: sometimes a file unpacks, sometimes it's uploaded as "zip"-which is it?

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2010]
![fo4vvwdqbeozqcvcdg9efi_v6pc4jtkb4t62klhcujk](https://cloud.githubusercontent.com/assets/8322346/7144518/1109c6ec-e2b4-11e4-96d2-9628721474a8.png)

**Comment by scolapasta** [comment]
Zip file behavior:
Unpacked automatically.
If it fails to unpack, for whatever reason, it'll upload as is.
If the number of files inside is more than a set limit (1,000), you get
an error message and the file uploads as is.

**Comment by scolapasta** [comment]
@sbarbosadataverse could you provide files that had this behavior so we can investigate why it's failing to unpack?

**Comment by sbarbosadataverse** [comment]
User notified. Eleni will add to documentation.

**Comment by scolapasta** [comment]
@sbarbosadataverse could you provide files that had this behavior so we can investigate why it's failing to unpack?

**Comment by kcondon** [comment]
Seems like a request for information rather than a bug, retested zip upload, works, closing.
