### ISSUE TITLE
Dataset Curation: Et Al. for Authors appearing in Facets

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2011]
Should look into this and see if we want to clean it up.

**Comment by sbarbosadataverse** [comment]
@scolapasta  
could this be fixed by facet not showing "et al?"

**Comment by pdurbin** [comment]
If https://github.com/IQSS/dataverse.harvard.edu/issues had existed in 2015 we would have created the issue there. It's so old, I'm just going to close it.
