### ISSUE TITLE
SWORD: retrieving the Service Document is not performant with ~3000 dataverses

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#2012]
This ticket is specifically to address the performance problem retrieving the SWORD Service Document from https://dataverse.harvard.edu as reported by @rliebz and @axfelix at http://irclog.iq.harvard.edu/dataverse/2015-04-14#i_18331

#784 is a related ticket in which we hope to solve the problem more completely.

**Comment by pdurbin** [comment]
@scolapasta and I think 70548db is good enough for a quick patch so I'm passing this to QA. Please note that the SWORD Service Document will only return dataverses for which your user account has a a direct role assignment. Role assignments for groups you may belong to will be ignored. We'll fix this in a future ticket such as #784 or #1070 or #1443

This is how I would recommend testing on a system with may dataverses (such as dvn-vm5):

curl -u $API_TOKEN: https://dataverse.harvard.edu/dvn/api/data-deposit/v1.1/swordv2/collection/dataverse/pdurbin

See also http://guides.dataverse.org/en/latest/api/sword.html#retrieve-sword-service-document

**Comment by kcondon** [comment]
OK this works but the curl command should be this:
curl -u $API_TOKEN: https://dataverse.harvard.edu/dvn/api/data-deposit/v1.1/swordv2/service-document
