### ISSUE TITLE
Edit Dataverse/Metadata: If make a field hidden first, then cannot make something required in that session.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2015]
If I make a field hidden first, say SocSci unit of analysis, then may a field like universe required, the radio button for required keeps snapping back to optional. If I exit and try again, making universe required first, then I can make the other hidden and save both.

**Comment by eaquigley** [comment]
I tested this and noticed that if I go back in and unhide Unit of Analysis then try to make any field required, it won't move over from Optional.
