### ISSUE TITLE
When click Download in a file, it downloads the other file in the dataset

### ISSUE THREAD

**Issue by mcrosas** [IQSS/dataverse#2016]
This can be seen in this dataset:

https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/8PY6Q6

**Comment by mcrosas** [comment]
This is related to #2014

**Comment by raprasad** [comment]
Also related #1992.
Every time you click a checkbox, the file tab is reloaded--and may be sorted differently

**Comment by raprasad** [comment]
This effects mapping and also seems impact two ravens.  
- When I click Dowload directly, I often receive a different file.  
- Similarly, the Map Data button is trying to access an incorrect file.  
- Reported problems with two ravens failing to load a file may be a variation on the same issue.
fyi: @scolapasta

**Comment by scolapasta** [comment]
Fixed.

**Comment by mcrosas** [comment]
:+1:

**Comment by kcondon** [comment]
Works, closing
