### ISSUE TITLE
The metadata could not be updated.  Please contact support. error message

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2018]
possibly related to #1905 , but with different cause.

went into study, filled in new required fields: contact email and subject
hit save and error message shows.

user receives (also tested by me and same error): meta data can't be updated

> Dear Dataverse Support,

>

> I'm unable to update any metadata for any existing studies in our 4.0 Dataverse https://dataverse.harvard.edu/dataverse/CIAT such as this one http://dx.doi.org/10.7910/DVN/28944.

>

> Best regards,

>

> Leroy Mwanzia  I  Data & Information Manager  I  International Center

> for Tropical Agriculture (CIAT)  I

> Email: l.mwanzia@cgiar.org<mailto:l.mwanzia@cgiar.org<mailto:l.mwanzia@cgiar.org%3cmailto:l.mwanzia@cgiar.org>>  I Tel:  +57 2

> 4450000 Ext: 3683 I Skype: leroy.mwanzia I A.A. 6713, Cali, Colombia

**Comment by scolapasta** [comment]
The issue here is that the dataset is part of a dataverse with a guestbook that has no name (which is actually all guestbooks, since they did not have names in 3.6).

Will run a script to set guestbook names to be the dataverse name. (and add script to migration)

**Comment by scolapasta** [comment]
Script run

**Comment by kcondon** [comment]
OK, not a code change, closing.
