### ISSUE TITLE
reset all open and wiki dataverses to have the right dataverse permissions

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2019]
Permissions for "open" dataverses in 3.6 should be:
Anyone with a Dataverse account can add datasets

**Comment by posixeleni** [comment]
And the default role for 3.6 Open Dataverses should be:

Contributor - Edit metadata, upload files, and edit files, edit Terms, Guestbook, Submit datasets for review

**Comment by mcrosas** [comment]
This will be done as a DB update.

**Comment by scolapasta** [comment]
Done. To open added :authenticated-users group as:
Dataset Creator

To wiki,  added :authenticated-users group as:
Dataset Creator and
Contributor (editor on backend)

Also wiped all other contributors from both these open and wiki.

**Comment by pdurbin** [comment]
Related: https://help.hmdc.harvard.edu/Ticket/Display.html?id=214858

**Comment by mcrosas** [comment]
Need to review wiki dataverses when bug is fixed. Open dataverses are all set.

**Comment by posixeleni** [comment]
Can only fix wiki dataverses once #2081 is resolved.

**Comment by posixeleni** [comment]
Assigning to @sbarbosadataverse since I will most likely be out when this will need to be worked on

**Comment by sbarbosadataverse** [comment]
moved to dataverse-curation repo
