### ISSUE TITLE
Better handling of dataset page with many files

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#2021]
There are likely several other issues like this or related, but to make sure we track, opening this:

We need to consider cases of loading many files and of sorting / filtering.

**Comment by scolapasta** [comment]
@mcrosas comments from #2014:

yes, we need for some datasets as soon as possible a way to sort or filter them by category - we could, for example, display the categories as "tags" at the top of the page (if the dataset has any tags), and when you click in a "tag", it filters the files for that category. This is needed son to bring functionality we had in 3.6 that a few dataverses are heavily relying on.

**Comment by eaquigley** [comment]
Suggestions of things needed:
- [ ] Count of files in the dataset at the top of the page
- [ ] Sort by option
- [ ] Listing of tags at top of page for filtering

**Comment by posixeleni** [comment]
A User also asked about this in RT https://help.hmdc.harvard.edu/Ticket/Display.html?id=196756 they were particularly interested in how they can sort/filter with tags.

**Comment by posixeleni** [comment]
@eaquigley do you happen to have an idea of when this will be implemented? I have a user asking if it will take more than a few months that they will rename their files for now but if its in a few weeks they  will wait till this feature is enabled?

Thanks!

**Comment by pdurbin** [comment]
@posixeleni @eaquigley @mheppler are there mockups and/or a Functional Requirements document? This sounds like a non-trivial task.

**Comment by pdurbin** [comment]
@chaudj has attached a screenshot of how files were groups in DVN 3.6: #2150

**Comment by eaquigley** [comment]
Functional Requirements Document for this feature: https://docs.google.com/document/d/1RkPycxX3nsCJJV9xbhc2mXvgwxJTkyDCsb_k2LGWrII/edit?usp=sharing

**Comment by eaquigley** [comment]
Request from community to be able to set a tag for all files in a dataset at one time. For example, if a user is uploading 25 files at once and wants them all to have the same tag without having to click edit tags for each file.

**Comment by CathyGarlick** [comment]
Hi All - is there an estimate of when this feature to be able to sort by tags will be implemented? If it's likely to be soon (within the next month) then I'll wait; if it's likely to be several months then I'll look into renaming the files so that they appear in the order we want when sorted alphabetically.

Many thanks

**Comment by mcrosas** [comment]
As of now, we are considering this for Milestone 4.0.3, which is planned for August 4.

We'll review this with @scolapasta and @eaquigley this week to confirm.

**Comment by sbarbosadataverse** [comment]
@eaquigley 
will this ticket cover sorting by tags? aka "sorting or organizing files by catogories in 3.6"

**Comment by eaquigley** [comment]
@sbarbosadataverse yes. more information can be found in this FRD (that has links to FRDs specific to this): 

https://docs.google.com/document/d/1v-6WuFyClnAAHqyMf1VsWtCdXDTTR-ikuG6Ou8RtDMM/edit?usp=sharing

**Comment by pdurbin** [comment]
Here are some examples of datasets with more than 25 files:

- 1,343 Files: https://dataverse.harvard.edu/dataset.xhtml?persistentId=hdl:1902.1/17045
- 244 Files: https://dataverse.harvard.edu/dataset.xhtml?persistentId=hdl:1902.1/NGQCIPIDUK
- 48 Files: https://dataverse.harvard.edu/dataset.xhtml?persistentId=hdl:1902.1/FYXLAWZRIA

See also #1877.

**Comment by mheppler** [comment]
Mockups for the new view of files on the dataset page show the "View Next..." button, as well as a link under it for "View all...". This will improve the loading of datasets with many (200+ files).

To improve the browsing of files search, filtering and tags (#2150) will be used. These features are also included in the mockups.

https://iqssharvard.mybalsamiq.com/projects/filesallthings-enduser-dataverse42andbeyond/Dataset%20-%20Files%20-%20Access

![screen shot 2015-09-08 at 2 31 13 pm](https://cloud.githubusercontent.com/assets/687227/9743838/62c7a454-5636-11e5-9494-ff567201a2ef.png)

**Comment by sbarbosadataverse** [comment]
added a related request that came in this morning:
'https://help.hmdc.harvard.edu/Ticket/Display.html?id=238458&results=c53170a1cdb9320f7c122c4b54b8608d

**Comment by mheppler** [comment]
A new issue, **Dataset - File UI Improvements #3404**, was created to track the UI improvements related to the files view on the dataset pg. Older feature requests and bug reports like this one will be closed in favor of that new issue.
