### ISSUE TITLE
Dataset Files: Selecting files in files tab is problematic can result in mistakes (delete, download, edit, etc).

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2023]
Minor but when I click the Explore button, the file is checked and highlighted.

**Comment by kcondon** [comment]
Investigation may be quick but if new component needed could take a lot longer.

**Comment by kcondon** [comment]
From #2244

User reported an issue when trying to click on multiple files:

    Let me follow that up with a quick UI bug report (or at least,
    unexpected behavior report). I was selecting files to delete for a
    version, and if I click exactly on the checkbox button, I am able to
    select multiple files. If I miss the checkbox button and hit any
    other part of the file "box" (which is large), that file will be
    selected, but all others will be unselected. This makes selection of
    multiple files difficult, and it surprised me because my files did not
    all appear in the same window, so I was unaware that other files were
    being unselected when I selected each one.

**Comment by mheppler** [comment]
A new issue, **Dataset - File UI Improvements #3404**, was created to track the UI improvements related to the files view on the dataset pg. Older feature requests and bug reports like this one will be closed in favor of that new issue.
