### ISSUE TITLE
Review performance when selecting a user to assign to roles

### ISSUE THREAD

**Issue by mcrosas** [IQSS/dataverse#2027]
Filtering a user to assign it to a role is slow in production (sue to the large number of users). Maybe there a few more things we can do to speed it up. Also we can review it showing 5 at a time is a suitable number (in some cases, you need to scroll among many names).

**Comment by kcondon** [comment]
User filtering is much faster with production data: 1-2 seconds. The limit results to 5 was not done, not sure how to easily do this if there are more than 5 and what you want is >5? Closing this ticket, will revisit shorter list.
