### ISSUE TITLE
SuperUser: grant ability to see and edit all user info and reset passwords (like we did in 3.6 as network admins)

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2029]

**Comment by pdurbin** [comment]
We don't store passwords for Shibboleth users, of course, so a superuser wouldn't be able to reset them. The user would need to contact their their "Identity Provider" ... the group that manages logins for their institution.

**Comment by mcrosas** [comment]
we can't do this for security reasons, but we'll think of the right solution to better support our users when they are having an issue with login or passwd reset.
