### ISSUE TITLE
Dataverse Pilot Integration with Annotopia for Metadata

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#203]
---

Author Name: **Eleni Castro** (@posixeleni)
Original Redmine Issue: 3617, https://redmine.hmdc.harvard.edu/issues/3617
Original Date: 2014-03-04

---

Need to consider this pilot feature for future release of Dataverse wrt integrating w/ Annotopia application, which atm would be particularly beneficial for biomedical metadata but can be applied to any other discipline:

Proposal from Tim Clark: (see attached file below for presentation with visuals)

1 - suppose we wanted to do a pilot project using Dataverse + Annotopia, with absolutely minimum disruption to your current work. 

2 - suppose we provided you with a web service connector to Annotopia, using some of the API calls we showed today

3 - could you build in an option to Dataverse to write your metadata (redundantly as discussed) using this connector, to Annotopia ?

4 - the general idea would be, flip a configuration switch in Dataverse, give it an endpoint for Annotopia, and it automagically shares the complete metadata set with us. 

We could then use this to do a number of very useful demonstrations without disturbing you further in this release. 

We'd basically be using this option to validate our approach. It could readily feed into the NIH BDDI proposal, too, as a pilot, but I'd like to see if there's a way to move it along quickly and simply in the current DV release without a lot of fuss, if you guys think it's at all possible. Of course I am not asking for a commitment, just a technical opinion.

**Comment by djbrooke** [comment]
Closing this. Will reopen if this comes up in the future.
