### ISSUE TITLE
Unable to Delete a File In the UI

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#2031]
User reported (see RT ticket: https://help.hmdc.harvard.edu/Ticket/Display.html?id=196503) this issue where they try to delete a file in draft but when they try to save the file does not disappear from the UI.

Did some troubleshooting with @scolapasta and uncovered that the file is deleted in the backend but still shows up in the UI.

To recreate here is the dataset: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi%3A10.7910%2FDVN%2FGJDUTV&version=DRAFT

And this is the file which is a duplicate filename: "02-Tables-Ineligibles_OD.do" [note: they want to delete the one that has NO description]

The Error in the log is:  
```
Error deleting physical file object while deleting DataFile 2668092 from the database.
```

**Comment by scolapasta** [comment]
@landreev checked in a fix

**Comment by kcondon** [comment]
OK, within the limit scope of the fix, this works:
1. add a file, save.
2. add another file, delete the first, can't save, throws server log error, click cancel.
3. in the past, the first attempted deleted file became immortal. now, if edit again and only delete not upload, delete works.
4. now upload to your heart's content.
