### ISSUE TITLE
Notification: URL in Request Access is Going to Wrong Permissions Page

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#2037]
If you look at the email below the URL is sending the user to the Dataset Permissions page but this needs to go to the File Permissions page for them to be able to grant or reject access to files that users have requested.

>---------- Forwarded message ----------
From: <support@dataverse.org>
Date: Thu, Apr 16, 2015 at 11:46 PM
Subject: Dataverse: You have requested access to restricted file
>
>Hello,
File access requested for dataset: "Online vs Official Price Indexes:
Measuring Argentina?s Inflation" - Journal of Monetary Economics. December
2012. Manage permissions at
https://dataverse.harvard.edu/permissions-manage.xhtml?id=2668076.
>
>Thank you,
The Dataverse Project

This was reported by a user in the following RT ticket: https://help.hmdc.harvard.edu/Ticket/Display.html?id=196545

**Comment by sbarbosadataverse** [comment]
@scolapasta 
Just an FYI that this has not been assigned to anyone--any idea when this will be fixed? I see this often because I'm admin on several dataverses.

**Comment by kcondon** [comment]
OK, now goes to files permissions page, closing.
