### ISSUE TITLE
Facets: Don't Hardcode Any Facets

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2039]
Now that we see real data in Dataverse, several of the hard coded facets no longer make sense to have as ones that a user cannot pick if they want them to appear or not. Affiliation is the primary example as well as Dataverse category since most dataverses still need to be given categories.

Things that need to be done:
- [ ] Allow a user to unselect any facet (besides the Dataverse, Dataset, Files and Publication Status ones) from appearing on their Dataverse page (including the Harvard Dataverse)
- [ ] Allow a user to reorder all facets so if they want Subject to appear before Dataverse Category, they can

**Comment by pdurbin** [comment]
@scolapasta this ticket probably means it time to make **all** Solr search field database-driven. Right now many fields are hard coded into https://github.com/IQSS/dataverse/blob/master/src/main/java/edu/harvard/iq/dataverse/search/SearchFields.java

**Comment by djbrooke** [comment]
Closing in favor of #6259
