### ISSUE TITLE
Make All Metadata Fields Facetable & Advance Searchable

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#2042]
We will need to look into if it makes sense to enable all metadata fields to be facetable and advance searchable.

**Comment by pdurbin** [comment]
I suspect there are many more metadata fields we could make facetable but I wouldn't say "all" since some fields such as "description" will probably never make sense to facet on.

**Comment by posixeleni** [comment]
@pdurbin you are correct -- we would not make textbox, URL or email fields facetable. But advance searchable yes.

**Comment by pdurbin** [comment]
Is anyone out there watching this issue and still wants this feature?

**Comment by pdurbin** [comment]
I guess not. Closing. Happy to re-open if anyone objects.
