### ISSUE TITLE
Delete File issues

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#2044]
We've seen many delete files issues, but from the exception, they are all fundamentally the same issue.

So I am creating this new issue for this. When fixed, please retest the specifc cases in the other three issues:
- when add/delete files in same request. #1344
- when upload a zip, then remove files #1661 
- uploading a file that has duplicate files (same md5) where automatic removal is done #1804 

The exception:
Caused by: org.postgresql.util.PSQLException: ERROR: null value in column "createdate" violates not-null constraint

**Comment by scolapasta** [comment]
Please retest these use cases.

**Comment by kcondon** [comment]
OK, all child tickets closed, closing.
