### ISSUE TITLE
Contact Us: When a lot of text is entered, popup refreshes and send button is displayed off screen with no scroll bars.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2045]
Contact Us: When a lot of text is entered, popup refreshes and send button is displayed off screen with no scroll bars.

Tested in both Chrome and FF.

An example of the text:

Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text. Testing a bunch of text.

**Comment by mheppler** [comment]
For reference, here is the javascript code that is currently being used to handle large popups.

http://stackoverflow.com/questions/13912397/primefaces-with-big-dialogs-how-to-do-this-correct?rq=1

````
/*
 * Dialog Height-Scrollable
 */
function handleResizeDialog(dialog) {
        var el = $('div[id$="' + dialog + '"]');
        var doc = $('body');
        var win = $(window);
        var elPos = '';
        var bodyHeight = '';
        var bodyWidth = '';
        // position:fixed is maybe cool, but it makes the dialog not scrollable on browser level, even if document is big enough
        if (el.height() > win.height()) {
            bodyHeight = el.height() + 'px';
            elPos = 'absolute';
        }
        if (el.width() > win.width()) {
            bodyWidth = el.width() + 'px';
            elPos = 'absolute';
        }
        el.css('position', elPos);
        doc.css('width', bodyWidth);
        doc.css('height', bodyHeight);
        var pos = el.offset();
        if (pos.top + el.height() > doc.height())
            pos.top = doc.height() - el.height();
        if (pos.left + el.width() > doc.width())
            pos.left = doc.width() - el.width();
        var offsetX = 0;
        var offsetY = 0;
        if (elPos != 'absolute') {
            offsetX = $(window).scrollLeft();
            offsetY = $(window).scrollTop();
        }
        // scroll fix for position fixed
        if (pos.left < offsetX)
            pos.left = offsetX;
        if (pos.top < offsetY)
            pos.top = offsetY;
        el.offset(pos);
}
````

**Comment by mheppler** [comment]
Added autoResize="false" attribute and value to all p:inputTextarea components within dialog popups. Added some more logic to javascript for resizing popups to improve how it handles scrolling popups larger than the window size. Also added logic to run the resize function anytime a popup is opened, and not just the popups that call the specific function.

The most important thing, for any dialog popups in the future, is to remember to include the autoResize="false" attribute. Not having that, along with the custom resize javascript function, was the main cause of the problem.

Other references for new javascript:
http://stackoverflow.com/questions/12936013/dialog-updates-in-primefaces
http://stackoverflow.com/questions/651563/get-the-last-element-of-a-splitted-string-array-in-javascript

**Comment by dliburd** [comment]
Verified: Send button remains visible when a lot of text is entered.
