### ISSUE TITLE
Share Dataverse/Dataset Via Email

### ISSUE THREAD

**Issue by suenjedt** [IQSS/dataverse#2047]
Within the training today, a user suggested to offer "sharing via email" as an addition to the existing social media options. 
![screen shot 2015-04-20 at 12 08 41](https://cloud.githubusercontent.com/assets/7300319/7234574/0aa20caa-e756-11e4-8dc5-1ced87a8bef3.png)

**Comment by pdurbin** [comment]
Is anyone out there interested in this?

**Comment by djbrooke** [comment]
I'm going to close this. The DOI is easy enough to copy and paste into an email, and if we added the ability to email from the form it would open another avenue for spam and possibly get emails from an installation blocked.
