### ISSUE TITLE
User suggestion: Featured dataset 

### ISSUE THREAD

**Issue by suenjedt** [IQSS/dataverse#2049]
A user suggested to include a functionality called "featured datasets", e.g. by most visited/shared/cited or most recently published. Many users might only create one Dataverse with many datasets inside and thus might appreciate such a functionality which highlights specific datasets.

**Comment by pdurbin** [comment]
@TaniaSchlatter and I talked about this the other week. Now that 4.7 is out installations can make a completely custom homepage (#3639) and feature datasets there. Closing.
