### ISSUE TITLE
Getting a 500 Error When Trying to Access Specific Datasets ($ in compound fields)

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#2050]
Reported in RT https://help.hmdc.harvard.edu/Ticket/Display.html?id=196556 on Friday 4/17/15:

Go to this Dataverse: https://dataverse.harvard.edu/dataverse/socialsciencercts

Try clicking on the title of the following Datasets and you will get an "Internal Server Error":
- Underinvestment in a Profitable Technology: the Case of Seasonal Migration in Bangladesh (doi:10.7910/DVN/28277)
- Does Price Matter in Charitable Giving? Evidence from a Large-Scale Natural Field Experiment (doi:10.7910/DVN/27853)
- Northern Uganda Social Action Fund - Youth Opportunities Program (doi:10.7910/DVN/27898)

@scolapasta looked into this quickly and discovered that all these datasets have a $ character in the description. According to @scolapasta any dataset with a $ in a compound field will exhibit this behavior so this needs to be fixed for all compound fields.

**Comment by scolapasta** [comment]
Fixed - use replace() instead of replaceAll() since we are not (yet) replacing regular expressions here.

**Comment by kcondon** [comment]
Created datasets with $ in description and keyword and they opened without error. Closing.
