### ISSUE TITLE
Edit Dataset: Adding files to a migrated dataset results in stack trace error to user when saving due to no subject.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2051]
This was reported by a user, see RT #196609.
"Dataset Save Failed  - edu.harvard.iq.dataverse.engine.command.exception.IllegalCommandException: Validation failed: Subject is required." 

Since this is likely to happen many times in the future, maybe we can catch this error with a friendlier validation style message?

**Comment by scolapasta** [comment]
This seems a duplicate of #1311 where we need to decide best way to handle this

**Comment by kcondon** [comment]
Right, this is just the subject now required on an existing dataset that didn't have one. Closing since the other ticket covers it.
