### ISSUE TITLE
Allow "." and some additional characters in usernames

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#2052]
From migration of old, we have usernames that have periods and should allow. Need to definew what characters we accept.

**Comment by scolapasta** [comment]
Added '-' as well as the '.' as a valid character.

Please verify that usernames that should be invalid are still invalid.

**Comment by kcondon** [comment]
@scolapasta Which should be invalid, 1char only, outside of a-Z, 1-n, not . - ?

**Comment by kcondon** [comment]
Ok, works, closing.
