### ISSUE TITLE
File Download: When downloading multiple files, put files into folders by file category.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2054]
This was requested by a user, see RT #196683:
 I noticed that when you download files separately, they aren't put into
different folders corresponding to their file "type" as was the case with
Dataverse previously. Is that something that will be updated as you guys
work on the new interface?

Speaking with Leonid, this needs some decision making since we now allow more than one category/tag per file so which to use?

**Comment by djbrooke** [comment]
Closing this, as we now download the hierarchy and so would need some toggle if we wanted to do some grouping by file types/tags.
