### ISSUE TITLE
Favorite A Dataset, Dataverse or Search Result (Star / Unstar)

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#2056]
Add the ability for a user to "Favorite" a Dataset, Dataverse or Search in Dataverse using something like the Star / Unstar button in GitHub, Twitter and other sites. Received this suggestion via twitter: https://twitter.com/crherlihy/status/590250638686216192

![image](https://cloud.githubusercontent.com/assets/5013837/7239891/3a661dda-e77b-11e4-8d1a-3394a3ad6aee.png)

**Comment by pdurbin** [comment]
I can imagine a user story that goes something like "As a fan of data about [whatever], I created my own dataverse and used the Link Dataset feature to gather together datasets I care about." The problem with this, of course, is that the "Link Dataset" feature is superuser only, as mentioned at http://guides.dataverse.org/en/4.6/api/native-api.html#saved-search

Judging from the thread on Twitter, what the user really wants is the ability to bookmark datasets, etc. though. I don't have a good sense of how much demand there is for this feature out there.

**Comment by pdurbin** [comment]
Does anyone want this feature?

**Comment by pdurbin** [comment]
My take is that this was requested once on Twitter over two years ago but not since. Closing. I'm happy to re-open this if people object!
