### ISSUE TITLE
Missing image in "Institution Log In"

### ISSUE THREAD

**Issue by cchoirat** [IQSS/dataverse#2057]
Works with Safari:
![login_safari](https://cloud.githubusercontent.com/assets/4173925/7241540/9615a572-e787-11e4-9e9f-9e5f90dd9261.png)

But not with Chrome:
![login_chrome](https://cloud.githubusercontent.com/assets/4173925/7241552/aea8027e-e787-11e4-918d-0c31108cbaac.png)

**Comment by pdurbin** [comment]
@cchoirat I believe this was just fixed in #2032 . Since it's Javascript you'll need to Shift-Reload to see the difference. Can you please try again?

**Comment by cchoirat** [comment]
No broken link anymore on Chrome (and no logo, same with Safari).

**Comment by kcondon** [comment]
Yes no broken image in Chrome, closing.
