### ISSUE TITLE
Displaying additional metadata for harvested dataverses

### ISSUE THREAD

**Issue by mcrosas** [IQSS/dataverse#2058]
The cards for Harvested datasets now do not display all the metadata that we get from harvested repositories. Since we don't have a dataset landing page for harvested datasets, at leas we should have a way to provide more information either in the card or in some other way.

To be reviewed with UI team @eaquigley @mheppler

**Comment by mheppler** [comment]
Current display (after the 4.5 release which featured harvesting) of additional metadata fields on the dataset cards for harvested content.

https://dataverse.harvard.edu/dataverse/harvard?q=survey+data&types=datasets&fq0=metadataSource%3A%22Harvested%22&sort=score&order=desc&page=1

![screen shot 2016-09-01 at 2 19 22 pm](https://cloud.githubusercontent.com/assets/687227/18179133/1d1df316-704f-11e6-92a8-09a9c206265c.png)

**Comment by djbrooke** [comment]
Closing this as we now provide more information on Harvested datasets.
