### ISSUE TITLE
Include dataset citation in native API

### ISSUE THREAD

**Issue by rliebz** [IQSS/dataverse#2059]
Right now, citation information for a dataset can be found using SWORD or the search API, but not the native API. SWORD has the disadvantage of only giving information for the latest version, and the search API only has access to published (and is a search, rather than a lookup).

Ideally, one of the native API routes would include the full citation in the JSON, such as: 
`GET http://$SERVER/api/datasets/$id/versions/$versionId/metadata?key=$apiKey`

**Comment by pdurbin** [comment]
@rliebz I'm going to guess that you're less interested in this now that you're no longer at COS. I'm closing it but we'll be happy to work on this if you or someone else comes along and opens a new issue. Thanks!
