### ISSUE TITLE
Notifications Page: Invalid Commas Being Inserted Into Dataset URL for "File access requested for dataset" 

### ISSUE THREAD

**Issue by SolomonMg** [IQSS/dataverse#2065]
I have a request for restricted data in my notifications <https://dataverse.harvard.edu/dataverseuser.xhtml?selectTab=notifications>, but when I click on the "News40 simulation data" hyperlink...
![screen shot 2015-04-21 at 11 49 55 am](https://cloud.githubusercontent.com/assets/833835/7260107/9e893378-e81c-11e4-800b-df91e17786d8.png)

I get this:
![screen shot 2015-04-21 at 11 50 10 am](https://cloud.githubusercontent.com/assets/833835/7260108/9e8a89ee-e81c-11e4-9ff0-48b4351774af.png)
URL is <https://dataverse.harvard.edu/permissions-manage-files.xhtml?id=2,668,791>

**Comment by posixeleni** [comment]
Hi @SolomonMg 

Thank you for reporting this issue. The url you included has commas in it that I have removed. Would you please try this URL instead? https://dataverse.harvard.edu/permissions-manage-files.xhtml?id=2668791

When I use the above URL I can now see the correct dataset file permissions page and it has one request to access files. 

Please let us know if you can see this.

Thanks
Eleni
-- 
Eleni Castro
Research Coordinator, Data Acquisition and Archiving, Data Science
IQSS, Harvard University
http://www.iq.harvard.edu/people/eleni-castro

**Comment by SolomonMg** [comment]
Yes, that solved the problem!

Solomon Messing
http://solomonmessing.wordpress.com/

**Comment by posixeleni** [comment]
We will investigate this issue further to see why commas are being inserted into the URL.

**Comment by scolapasta** [comment]
Assigned to investigate immediately; depending on resolution may need to be moved out of Patches.

**Comment by mheppler** [comment]
Fixed links from bundle for account notifications related to file access in a dataset.

The ID number value returned via the f:param, can be formatted in the bundle. (Ref: http://stackoverflow.com/questions/27965033/can-i-use-fconvertnumber-with-houtputformat?rq=1)

**Comment by kcondon** [comment]
OK, tested with dataset id 1001 and it works, closing.
