### ISSUE TITLE
Updating Terms of Access / Terms of Use Should strip harmful tags

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#2067]
Part of #1320.  Moved to separate ticket to smoke test for patch.

Updating Terms of Access/Terms of Use should strip harmful HTML tags .

-  ```<script>``` tags removed  
- Allowable tags closed/sanitized: ```<p>``` tag that has no corresonding ```</p>``` will be removed

**Comment by kcondon** [comment]
Tested, script tags are removed but <p> with no corresponding </p> actually gets a </p>. Passing back for Raman to look at but otherwise seems ok.

**Comment by scolapasta** [comment]
Checked with @raprasad it's fine that it closed the tag, but @sekmiller is altering the logic for this, so should be retested when he's done.

**Comment by sekmiller** [comment]
Ready for testing

**Comment by sekmiller** [comment]
New Build required.

**Comment by kcondon** [comment]
OK, works, the following rules were tested:
    // basic includes: a, b, blockquote, br, cite, code, dd, dl, dt, em, i, li, ol, p, pre, q, small, span, strike, strong, sub, sup, u, ul
    Whitelist wl = Whitelist.basic().addTags("img", "h1", "h2", "h3", "kbd", "hr", "s", "del");   

I just entered blank tags and watched if they survived as tags on a rendered page:
Basic:
<a></a><b></b><blockquote></blockquote><br></br><cite></cite><code></code><dd></dd><dl></dl><dt></dt><em></em><i></i><li></li><ol></ol><p></p><pre></pre><q></q><small></small><span></span><strike></strike><strong></strong><sub></sub><sup></sup><u></u><ul></ul>

Whitelist:
<img></img><h1>h1</h1><h2>h2</h2><h3>h3</h3><kbd></kbd><hr></hr><s></s><del></del>

Blacklist:
<script></script>


Closing
