### ISSUE TITLE
Original Zip file download failure;  appears to have a 15 minute timeout, causing failures for large files and slow links

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#2068]
User reported (RT https://help.hmdc.harvard.edu/Ticket/Update.html?id=209024) that when they try to download a single zip file (uploaded in 3.6 as a zip and not unpacked)  and they try to open it, the file itself has nothing inside. I noticed that the file invpat_final.zip they tried to download was over 1G zipped in this Dataverse https://dataverse.harvard.edu/dataset.xhtml?persistentId=hdl:1902.1/15705

**Comment by posixeleni** [comment]
Another user reported in RT https://help.hmdc.harvard.edu/Ticket/Display.html?id=196815 the same issue where if they go to this Dataset: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi%3A10.7910/DVN/28999&version=5.0  and try to download a large zip file "DARTE.gdb.zip" (originally uploaded as zip in 3.6.2) that is > 1G and they try to open it there is nothing in the file

**Comment by pdurbin** [comment]
Related (I think): #2013

**Comment by scolapasta** [comment]
From #2080: Reported by various users, especially on slow links but any download taking more than 15 minutes, the download halts, resulting in various user symptoms: zero length file (Mac/Mozilla) to partial download and corrupted zip file (windows, chrome)

**Comment by scolapasta** [comment]
Passing to QA.

**Comment by kcondon** [comment]
Tested, this appears to be resolved. Increased the download timeout but needed to add it to http-listener-2 since we use that now for direct file download via port 8181.

Closing.
