### ISSUE TITLE
Factor Google Analytics code out of google-analytics-snippet.xhtml and into the "setting" table

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#2069]
This should be a setting:

```
src/main/webapp/google-analytics-snippet.xhtml
16:          ga('create', 'UA-61753334-1', 'auto');
```

**Comment by pdurbin** [comment]
@raprasad I added GoogleAnalyticsCode to the enum for the `setting` table and updated the Harvard-specific setup script with our code: 816a88e

If you populate the setting the code will be printed at the bottom of the page in an HTML comment like this:

```
murphy:dataverse pdurbin$ curl -s -X PUT -d UA-61753334-1 http://localhost:8080/api/admin/settings/:GoogleAnalyticsCode | jq .
{
  "data": {
    ":GoogleAnalyticsCode": "UA-61753334-1"
  },
  "status": "OK"
}
murphy:dataverse pdurbin$ curl -s http://localhost:8080 | tail -3
	</script>
        <!--Google Analytics code: UA-61753334-1--></body>
```

@raprasad can you take it from here?

**Comment by kcondon** [comment]
OK, ran curl command saw db table updated with key, saw html page with key. Compared resulting code with current production code and it is identical. Closing.
