### ISSUE TITLE
Update native API to for Deaccessioned Datasets

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#2071]
native api query for this datast:

https://dataverse.harvard.edu/dataset.xhtml?id=2668654

Gives these results.  Did not include a "latestVersion"

``` json
{"status":"OK","data":
    {"id":2668654,
    "identifier":"YVRVCH",
    "persistentUrl":"http://dx.doi.org/10.7910/DVN/YVRVCH",
    "protocol":"doi",
    "authority":"10.7910/DVN"}
}
```

**Comment by pdurbin** [comment]
@raprasad can we close this?

**Comment by pdurbin** [comment]
Discussed with @raprasad and he said he'd take a look.

**Comment by pdurbin** [comment]
I talked to @raprasad today and he said he's fine with me closing most open issues in his name. No one else seems to have reported this issue. Closing.
