### ISSUE TITLE
Reset Password: update email address to be support@

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2072]
Currently email address for reset password emails sent to users is do-not-reply, this needs to be changed to be support@dataverse.org so it is the same as all other emails sent to users.

@pdurbin found where it is here: 
https://github.com/IQSS/dataverse/blob/master/src/main/java/edu/harvard/iq/dataverse/passwordreset/PasswordResetServiceBean.java

**Comment by pdurbin** [comment]
Or rather, whatever the installation has designated the support address to be.

**Comment by pdurbin** [comment]
@scolapasta e919cde seems like a good fix, which you can merge with pull request #2084

I tested it on apitest:

![1](https://cloud.githubusercontent.com/assets/21006/7306965/1878a4a0-e9d7-11e4-964f-e45da2b63df4.png)
![2](https://cloud.githubusercontent.com/assets/21006/7306969/1ce22502-e9d7-11e4-8ea0-b3217cd4ba28.png)

**Comment by kcondon** [comment]
OK, works, correct sender address, closing.

**Comment by pdurbin** [comment]
The sharp eyed @eaquigley noticed the duplicate thank yous in the screenshot: https://github.com/IQSS/dataverse/issues/2072#issuecomment-95712818

I removed them in 41e94a0 so I'm re-opening this ticket to go through QA again.

**Comment by kcondon** [comment]
Sender address is correct,  just the one thank you as well, closing
