### ISSUE TITLE
Enable Custom Metadata To Only Be Enabled & Show For Specific Dataverses

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#2077]
Work w/ @scolapasta to make sure that all custom metadata blocks are only appearing for the dataverses they were developed for (will also need to review if any other dataverses used these blocks (as custom fields in 3.6) in their templates).

- GSD
- PSRI
- Murray
- CHIA World-Historical
- ARCS
- MRA
- PSI

**Comment by posixeleni** [comment]
@scolapasta when can we work on this ticket together?

**Comment by posixeleni** [comment]
Assigning to @scolapasta but let me know if I can help with anything

**Comment by scolapasta** [comment]
Worked with @sbarbosadataverse and this is all set.

**Comment by kcondon** [comment]
OK, closing
