### ISSUE TITLE
Dataverse Card: Show children should show all next level children, both datasets and dataverses.

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#208]
---

Author Name: **Kevin Condon** (@kcondon)
Original Redmine Issue: 3622, https://redmine.hmdc.harvard.edu/issues/3622
Original Date: 2014-03-04
Original Assignee: Philip Durbin

---

Spoke with Mike and Phil

Mike's original mockup includes dataverses in his show children area. He confirmed he'd intended it to be only the next level below the current dv, both datasets and dv's.

So, this ticket is basically saying we need to add child dv's to the list displayed in show children.

Mockup from https://trello.com/c/jmry3BJR/28-browse-dataverses

!https://trello-attachments.s3.amazonaws.com/527d1605c7b30060420027b0/52e6fb3a575628c730670739/cf01183779472273f66b15a4321175a0/searchcardstype.png!

**Comment by pdurbin** [comment]
Removed for performance reasons:

remove preview of recently released datasets from dv card #1985 · IQSS/dataverse@35c4f3a - https://github.com/IQSS/dataverse/commit/35c4f3a53f60bbfb5fb6ad1f9fa9f074fb013a97

**Comment by eaquigley** [comment]
Discussed with @mcrosas to have this show on the card how many dataverses and datasets are in the dataverse. Will discuss with @mheppler to mock this up so it can be developed.

**Comment by eaquigley** [comment]
We no longer show children. Closing this ticket and created new ticket for final comment on April 29.
