### ISSUE TITLE
Review thumbnail generation

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#2082]
We found issues with the thumbnail generation when being done on demand (in particular for a dataset with a large # of files, and with PDFs)

- PDF thumbnail generation loads entire PDF into memory

**Comment by landreev** [comment]
@scolapasta 
@kcondon 
This really needs to be closed. 
Has not been an issue; through controlling the size limit of files for which on-the-fly generation of thumbnails is attempted; and generally optimized thumbnail generation. 

Kevin, I found this one going through the tickets not tied to specific milestones that Gustavo told me to un-assign myself from.  Please close this, if you feel comfortable doing so without re-testing/investigating this. 
If not, please simply un-assign yourself and throw it back into the pile.

**Comment by kcondon** [comment]
Yes, there are jvm options to limit the size of thumbnails:
dataverse.dataAccess.thumbnail.image.limit
dataverse.dataAccess.thumbnail.pdf.limit

The optimized part I don't know about. The main problematic use case was GSD and their prexisiting, very large, non-jpeg files. I think you did something to address the bad behavior of ImageMagick for non-jpeg performance.

I supposed something similar could occur with a large zip file of images: 1000 2MB images, etc.
