### ISSUE TITLE
Add Additional Controlled Vocabulary Terms to Life Sciences Metadata for TB Dataverse

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#2083]
Will need to modify the Life Sciences Metadata to add the following controlled vocabulary terms in the following fields, will check if there are any slight variants of these terms that are more standardly used:

**StudyDesignType**
- Cohort Study Design (ontology: http://bioportal.bioontology.org/ontologies/OCRE/?p=classes&conceptid=http%3A%2F%2Fpurl.org%2Fnet%2FOCRe%2Fstudy_design.owl%23OCRE100078)
- Randomized Controlled Trial (ontology: http://bioportal.bioontology.org/ontologies/EDDA?p=classes&conceptid=http%3A%2F%2Fedda.dbmi.pitt.edu%2Fontologies%2FStudyDesigns.owl%23randomized_controlled_design)
- Nested Case Control Design (ontology: http://bioportal.bioontology.org/ontologies/EDDA/?p=classes&conceptid=http%3A%2F%2Fedda.dbmi.pitt.edu%2Fontologies%2FStudyDesigns.owl%23nested_case_control_design&jump_to_nav=true)

**StudyFactorType**
- drug susceptibility test

**Organism** (note: make sure these are in NCBI Taxonomy)
- Mycobacterium tuberculosis
- Mycobacterium canetti
- Mycobacterium africanium (SEK - in the taxonomy it's africanum)

**Measurement** 
- targeted sequencing
- drug susceptibility test

**technology type**
- culture based drug susceptibility testing, single concentration
- culture based drug susceptibility testing, two concentrations
- culture based drug susceptibility testing, three or more concentrations (minimium inhibitory concentration measurement)

**technology platform**
- Indirect proportion method on LJ medium
- Indirect proportion method on Middlebrook Agar 7H9
- Indirect proportion method on Middlebrook Agar 7H10
- Indirect proportion method on Middlebrook Agar 7H11
- BD BACTEC MGIT 960
- BD BACTEC MGIT 320
- BD Radiometric BACTEC 460TB
- microplate Alamar Blue (resazurin) colorimetric method

**Comment by posixeleni** [comment]
We may need to postpone this to the next release since additional dev work will be needed to support metadata field changes now that 4.0 has been released:

from @scolapasta 
>Though Eleni, for yours we'll need to work on update scripts for any changes you make, since we won't be dropping the db anymore (or have a way to run a setup that only catches changes).

**Comment by sekmiller** [comment]
@posixeleni do we need to update the "display order" so that the entries are alphabetical?

**Comment by posixeleni** [comment]
@eaquigley @sekmiller I am re-assigning this to me since this metadata has yet to be added to the biomedical.tsv file. 

Also this wont be ready for 4.0.1 since I am waiting to hear from @scolapasta if there will be update scripts available after 4.0.1 so that I can actually push this change to the metadata.

**Comment by posixeleni** [comment]
@sekmiller the updated biomedical.tsv is now here https://www.dropbox.com/s/5l6970xoh5vsw3e/biomedical.tsv?dl=0 but I am holding off commiting it to GitHub until you have the update script ready

https://docs.google.com/spreadsheets/d/1GvP-Nxc6UUMrWLSPBPPcvm3oP3iecb_FsyKsyiObrFc/edit?usp=sharing

**Comment by sekmiller** [comment]
Coding of datasetfield input/update updated.

To test run the update-datasetfields.sh script

**Comment by kcondon** [comment]
OK, all values correct, closing.
