### ISSUE TITLE
Review MailServiceBean methods

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#2085]

**Comment by bencomp** [comment]
@scolapasta what for? And how? Are you talking about improving the documentation (#775)? :)

**Comment by pdurbin** [comment]
I have no idea what this ticket is about. I searched my email and I can't find a reference to it.

**Comment by pdurbin** [comment]
@scolapasta can we close this?

**Comment by scolapasta** [comment]
This issue was about doing code cleanup to these methods. It's tech debt in that it works, but is not the maintainable code.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
