### ISSUE TITLE
Account - Access Granted and Access Rejected Notifications Should Go to the Dataset Page

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#2087]
they are currently going to the manage permissions page. 

This should be checked both in the UI notifications as well as the e-mails.

**Comment by scolapasta** [comment]
Seems to be correct in the code for e-mails.

**Comment by mheppler** [comment]
Fixed links from bundle for account notifications related to file access in a dataset.

Users who requested access are now pointed to the dataset page.

**Comment by kcondon** [comment]
OK notifications work both forms, links are ok, closing.
