### ISSUE TITLE
4 released datasets with unregistered DOIs

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#2089]
There are 4 released Datasets where the DOI is unregistered:

https://dataverse.harvard.edu/dataset.xhtml?id=54628
https://dataverse.harvard.edu/dataset.xhtml?id=66267
https://dataverse.harvard.edu/dataset.xhtml?id=65392
https://dataverse.harvard.edu/dataset.xhtml?id=64907

/cc @scolapasta

**Comment by sekmiller** [comment]
Successfully registered all DOI by hand via the EZID Admin interface.
http://dx.doi.org/10.7910/DVN/28028
http://dx.doi.org/10.7910/DVN/27669
http://dx.doi.org/10.7910/DVN/28447
 http://dx.doi.org/10.7910/DVN/FZNFL

**Comment by scolapasta** [comment]
Verified the doi links go to 4.0 production.
