### ISSUE TITLE
Internationalization

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#209]
---

Author Name: **Mike Heppler** (@mheppler)
Original Redmine Issue: 3623, https://redmine.hmdc.harvard.edu/issues/3623
Original Date: 2014-03-04
Original Assignee: Gustavo Durand

---

All help text, form labels, etc. will need to be easily translated from one language to another.

Figure out how internationalization will be handled, so that new dynamic content, like domain metadata fields, can be added to the application and available in all languages.

---

Related issue(s): #190
Redmine related issue(s): [1115](https://redmine.hmdc.harvard.edu/issues/1115), [3602](https://redmine.hmdc.harvard.edu/issues/3602)

---

Parent to #4685
Parent to #4684
Parent to #4680
Parent to #4679
Parent to #4672
Parent to #4634

**Comment by juancorr** [comment]
Hi,

I think that there are some issues to solve to have a complete multi-language environment. You could decide the advisable to Dataverse :

- metadatablocks tsv files:
    + Include only labels but not titles or descriptions and use ResourceBundle files?.
    + Create a file version for language and select the correct file for the current i18n configuration (Ej : astrophysics.tsv – astrophysics_ES.tsv)?
    + Other options?

- Some text in javascript files:
    + javascript dv_rebind_bootstrap_ui.js: “Edit Dataverse – Edit your dataverse and click Save Changes. Asterisks indicate required fields.”
    + mydata.js: “result”, “results”

- Select help url files in configuration and choose the correct url in a ResourceBundle file?. Ej: 
helpBundle.properties: help.userGuide= http://guides.dataverse.org/en/4.2.3/user
helpBundle_es_ES.properties: help.userGuide= http://www.consorciomadrono.es/dataverse/en/4.2.3/user

- Word order in some phrases. Ej: “Floris Peters Dataverse” in Spanish is “Dataverse Floris Peters”. “Bicycle Collisions in Boston, MA (2009-2012) Dataverse” in Spanish is “Dataverse Bicycle Collisions in Boston, MA (2009-2012)”

- Update some java files (java server faces, tests, …)

- UI toggle for language selection

- Strings not translated in java and xhtml files.

**Comment by djbrooke** [comment]
Removing from 4.5. This will be prioritized for later release. Going to assign to @scolapasta for now as he will be having some conversations about this at the Community Meeting and may update this ticket with more information.

**Comment by pdurbin** [comment]
Anyone interested in internationalization of Dataverse should subscribe to the newly-revived dataverse-internationalization-wg mailing list at https://groups.google.com/forum/#!forum/dataverse-internationalization-wg

Lots of good stuff happening, especially the many pull requests by @JayanthyChengan !

**Comment by djbrooke** [comment]
I'm going to close this out because I18N is largely done and several installations provide multiple languages. There may be future work here, but we can continue to open specific issues.
