### ISSUE TITLE
Widgets: Add Link to Individual's Dataverse Page 

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2090]
Mentioned by @thegaryking about the widgets: if you click on any study in my dataverse you go, as planned, to the main dataverse page.  however, there is no indication that my dataverse is part of the iq dataverse, and no way to get to the iq dataverse or the full version of the 'gary king dataverse' if you don't know or don't want to click on one of the individual studies.  let's add an indication at the top and make it a link, which would solve both problems.

Suggestion: 
- [ ] let's add an indication at the top and make it a link, which would solve both problems.

**Comment by mheppler** [comment]
Requirements outline as copied from [FRD](https://docs.google.com/document/d/12Y3HyAbhm69MqiHPci8Caxk3l_8m1uh64xCjVvPdyUk/edit).

**Dataverse Template**
- [x] Add new include for the footer block
  - [x] Rendering not to display copyright, links, version number in widget
  - [x] Rendering to display “Data is stored at…” msg, link to installation
  - [x] “Log in” link in footer to access admin features on full Dataverse installation

**iframe Template**
- [x] Add new include for the footer block

**Dataverse Listing Widget**
- [x] Dataverse branding w/ “Data is stored at…” msg, link to installation

**Dataset Citation Widget**
- [x] Dataverse branding w/ “Data is stored at…” msg, link to installation

**Comment by kcondon** [comment]
OK all works, closing.
