### ISSUE TITLE
Citation: Make Citation Easier to Copy

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2091]
Instead of having to highlight the citation and copy, add ability to click and have it copied like in OpenScholar

**Comment by eaquigley** [comment]
Link to Code snippet from OpenScholar for us to use to have this work: https://github.com/openscholar/openscholar/blob/SCHOLAR-3.x/openscholar/modules/os_features/os_publications/os_publications.theme.inc#L217

What it will do is highlight all the text so a user doesn't have to highlight it all.

**Comment by mheppler** [comment]
Improved layout and help text of citation block on dataset page. Also added click-to-highlight javascript functionality.

Code is available for review and merging on the following branch: https://github.com/IQSS/dataverse/tree/2091-2092-citation

**Comment by pdurbin** [comment]
Merged into 4.0.1. Passing to QA.

**Comment by eaquigley** [comment]
Works as expected. Closing ticket.
