### ISSUE TITLE
Why Cite? Link: Update Text and Move Outside of Citation Box

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2092]
- [x] line should be outside the blue citation box
- [x] "If you use these data, please add this citation to your scholarly resources. Why Cite?" change to be Data Citation Standards as this link goes to the Best Practices-Data Citation Standards page on dataverse.org

**Comment by mcrosas** [comment]
@mheppler first propose a "photoshop" view and send to @thegaryking

**Comment by mheppler** [comment]
Improved layout and help text of citation block on dataset page. Also added click-to-highlight javascript functionality.

Code is available for review and merging on the following branch: https://github.com/IQSS/dataverse/tree/2091-2092-citation

**Comment by pdurbin** [comment]
Merged into 4.0.1. Passing to QA.

**Comment by eaquigley** [comment]
Works as expected. Closing ticket.
