### ISSUE TITLE
home page performance

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#2096]
The homepage is still quite expensive in terms of queries, load time, etc.
What can be made more efficient as well as cached?

### Scenario
* localhost, 20 dataverses, 58 datasets, 373 files

#### Queries counts

* Not logged in: 
   - plain vanilla homepage: **873**
   - clicking the "Files" facet: **5065**
* Logged In:
   - plain vanilla homepage: **1123**
   - clicking the "Files" facet: **5068**

Multiply these numbers by 100 hits on the homepage, 200 hits, 1000 hits ...

**Comment by kcondon** [comment]
Mike captured these test results, takes ~4seconds before something loads:
http://www.webpagetest.org/result/150629_RG_Z50/

**Comment by raprasad** [comment]
replaced by #2472
