### ISSUE TITLE
Server logs: We are generating 10x more server log info, 4/21=4 files 4/24=46 files.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2098]
We are generating 10x more server log info, 4/21=4 files 4/24=46 files.

One possible contributor are these entries. This was the first one and now there are ~3000+ per log.

 grep -c "Checking for thumbnail" server.log_2015-04-22T19-04-29

[2015-04-22T18:53:56.220-0400] [glassfish 4.1] [INFO] [] [edu.harvard.iq.dataverse.dataaccess.ImageThumbConverter] [tid: _ThreadID=54 _ThreadName=jk-connector(1)] [timeMillis: 1429743236220] [levelValue: 800] [[
  Checking for thumbnail, file type: application/pdf]]

**Comment by landreev** [comment]
The thumbnail message is mine; no, it has no business logging at the 
level "info". It was part of another "firefighting" patch, so I was 
checking it in in a hurry. Will trim down my logs first thing this week.

**Comment by kcondon** [comment]
Fixed, closing
