### ISSUE TITLE
Add creative commons license info for CC0

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#21]
---

Author Name: **Gustavo Durand** (@scolapasta)
Original Redmine Issue: 1828, https://redmine.hmdc.harvard.edu/issues/1828
Original Date: 2012-02-16

---

We need to evaluate with Merce what this entails; how it interacts with Terms of Use, etc.

**Comment by sekmiller** [comment]
Basic functionality completed

**Comment by kcondon** [comment]
This is effectively a dupe of the other TOU ticket, closing.
