### ISSUE TITLE
Widgets - Embedding of Dataverse Metrics

### ISSUE THREAD

**Issue by rbran100** [IQSS/dataverse#2101]
@dancabral would like to embed the dataverse metrics onto the IQSS website.

Is is possible to add this data as a embeddable widget so that it can be updated continuously?

Specifically these elements:
![screenshot 2015-04-27 11 39 29](https://cloud.githubusercontent.com/assets/651318/7351261/2838b0d0-ecd2-11e4-9468-6e034a2f87c5.png)
![screenshot 2015-04-27 11 39 34](https://cloud.githubusercontent.com/assets/651318/7351262/283a0340-ecd2-11e4-9b7e-fc593ad595ad.png)

If a JS embed is not practical, we could use a custom created iframe as long as the data is available at a URI.

**Comment by dancabral** [comment]
The goal is to keep this DV metrics block on the iq site dynamic. 
![screen shot 2015-04-29 at 4 14 17 pm](https://cloud.githubusercontent.com/assets/867075/7400471/2b5ec35c-ee8b-11e4-851d-4a032e8dd352.png)

**Comment by djbrooke** [comment]
@dancabral and @raprasad - please feel free to close this out if this need will be addressed by the Miniverse project. Thanks!

**Comment by pdurbin** [comment]
Right, these days the dataverse metrics on http://dataverse.org come dynamically from https://services.dataverse.harvard.edu/miniverse/map/dataverse-org?iframe=true

Here are some screenshots showing the URLs:

![screen shot 2016-10-23 at 10 43 40 am](https://cloud.githubusercontent.com/assets/21006/19627121/b91c85ac-990d-11e6-99a3-41f79d642eb2.png)

![screen shot 2016-10-23 at 10 44 04 am](https://cloud.githubusercontent.com/assets/21006/19627120/b91ae71a-990d-11e6-84e2-f8862f96abd3.png)

I'm with @djbrooke. This issue should be closed. It was done in the 4.5.1 timeframe so I'll give it that milestone. Vote to close.

If any Dataverse installation out there wants similar metrics of their own installation, the code that powers that "services" host is at https://github.com/IQSS/miniverse

**Comment by raprasad** [comment]
In production via minverse.  actual implementation is an open scholar "widget" that iframes the stats and map.
