### ISSUE TITLE
Creating a draft version of a published dataset via the native API removes existing files

### ISSUE THREAD

**Issue by rliebz** [IQSS/dataverse#2102]
This has only been tested on `apitest.dataverse.org`

Steps to Reproduce
--- 
1. Create a dataset
2. Upload some files
3. Publish the dataset
4. Before making any other changes:
  1. Get the current metadata from `http://$SERVER/api/datasets/$id/versions/:latest?key=$apiKey`
  2. Post the metadata (with or without changes) to `http://$SERVER/api/datasets/$id/versions/:draft?key=$apiKey`

Expected
---
The dataset will have a draft version with the metadata specified in the post and all files intact.

Actual
---
The draft version of the dataset does not include the files.

**Comment by pdurbin** [comment]
I just reproduced this bug in master:

- scripts/database/homebrew/delete-all 
- scripts/database/homebrew/rebuild-and-test
- upload a file to the "Darwin's Finches" dataset
- publish "Darwin's finches"
- change title to "Darwin's Galápagos Finches" using [scripts/search/tests/edit-dataset-finch1](https://github.com/IQSS/dataverse/blob/1f3a84ed39bba8f02f0f4a82a6528ead4b331615/scripts/search/tests/edit-dataset-finch1) ("native" API call)
- observe that **the file is gone from the draft** (but not gone from v1.0)

![darwin_s_galapagos_finches_-_finches_dataverse_-_2015-05-06_17 43 06](https://cloud.githubusercontent.com/assets/21006/7504733/7607c5ae-f41a-11e4-94db-82d68a6feecd.png)

**Comment by michbarsinai** [comment]
Supposed fix is pushed to a new branch for validation (https://github.com/IQSS/dataverse/tree/4.0.1-issue2102)

**Comment by michbarsinai** [comment]
Over to @scolapasta for validation

**Comment by pdurbin** [comment]
@scolapasta asked me to merge this in to 4.0.1.

@michbarsinai please advise if there's anything we should look out for.

**Comment by pdurbin** [comment]
@michbarsinai the fix didn't seem to work so I'm giving this ticket back to you and changing the milestone to "**candidate** for 4.0.1". If you could write a test next time along with the fix it would be awesome.

In 255f0cf (new branch) I cherry-picked fa411ed on tip of 4.0.1 and repeated the test at https://github.com/IQSS/dataverse/issues/2102#issuecomment-99625189 but the file is still deleted from the draft ("Files (Removed: 1)"):

![darwin_s_galapagos_finches_-_finches_dataverse_-_2015-05-21_12 56 19](https://cloud.githubusercontent.com/assets/21006/7754279/7ceb0b56-ffb9-11e4-833d-14a7537c5d96.png)

**Comment by michbarsinai** [comment]
Added file metadata copying to the CreateDatasetVersionCommand.
Over to QA - there's a new folder: /scripts/issues/2102, with some scripts file to get the testing started (compose the curl commands etc). There is also a son file to post.

**Comment by michbarsinai** [comment]
Also, QA: database state file is also in that folder, so you can generate the starting conditions of the database. It does not include the file itself - not sure if that matters.

**Comment by kcondon** [comment]
Closing based on Phil's testing.

**Comment by kcondon** [comment]
OK, tested using Michael's sample commands after manually creating a dataset with files. Files were preserved after making metadata changes to a published dataset.

Closing
