### ISSUE TITLE
Shibboleth: update shibboleth2.xml entityID to end with "sp" rather than "shibboleth"

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#2104]
Per https://spaces.internet2.edu/display/InCFederation/Entity+IDs it has been recommended to use to have our Shibboleth entityID be in this form...

```
entityID="https://sp_name.example.edu/sp"
```

... rather than this one:

```
entityID="https://sp_name.example.edu/shibboleth"
```

We should update the example at https://github.com/IQSS/dataverse/blob/master/conf/vagrant/etc/shibboleth/shibboleth2.xml

**Comment by pdurbin** [comment]
> We should update the example at https://github.com/IQSS/dataverse/blob/master/conf/vagrant/etc/shibboleth/shibboleth2.xml

More importantly, we've already updated the example at http://guides.dataverse.org/en/latest/installation/shibboleth.html to be `entityID="https://shibtest.dataverse.org/sp"`.

However, all of our servers still have the old style ending in "shibboleth" rather than "sp". For example, https://dataverse-demo.iq.harvard.edu/Shibboleth.sso/Metadata shows `entityID="https://dataverse-demo.iq.harvard.edu/shibboleth"`.

@scolapasta and @kcondon I'm thinking we could use this issue to work on making sure all of our servers use the new ending. Also, we should re-define which servers we want Shibboleth support on. Here's a potential list:

- https://dataverse.harvard.edu
- https://dataverse-demo.iq.harvard.edu
- dvn-build
- dataverse-internal?
- http://beta.dataverse.org ?
- https://apitest.dataverse.org ?
- cluster/staging?

In INC01226245 we're working on getting https://dataverse.harvard.edu registered with InCommon at https://incommon.org/federation/info/all-entity-categories.html#SPs but we could probably have a few testing or staging instances. In the past we've done "out of band" metadata exchanges for Harvard's Identity Provider (IdP) but since the Harvard IdP is part of InCommon we should probably treat it like all other IdPs in that federation.

**Comment by bencomp** [comment]
The [Entity IDs doc](https://spaces.internet2.edu/display/InCFederation/Entity+IDs) also has a warning that says 

> Do NOT change your entity ID!

So in any case it's important to choose wisely before registering and using an ID. Add to #2884?

**Comment by pdurbin** [comment]
https://dataverse-demo.iq.harvard.edu was renamed to https://demo.dataverse.org in #2651.

To me this issue is about registering the following two servers at https://incommon.org/federation/info/all-entities.html#SPs

- https://dataverse.harvard.edu (production)
- https://demo.dataverse.org (QA/testing/staging/demo)

As of this writing https://dataverse.harvard.edu is using a non-recommended entityID (doesn't end in "sp") and https://demo.dataverse.org isn't configured for Shibboleth at all (after the rename). To make progress on this I could at least reconfigure demo with a recommended entityID (I may want to change the docs from shibtest to demo) and get it working again with http://www.testshib.org .

Incidentally, I noticed that many QA/testing/staging/demo Service Providers are [registered with InCommon](https://incommon.org/federation/info/all-entities.html#SPs)...

![incommon_federation_info_entities_-_2016-02-04_09 55 26](https://cloud.githubusercontent.com/assets/21006/12818623/a1a35b50-cb25-11e5-8545-cb99da3c1f6f.png)
![incommon_federation_info_entities_-_2016-02-04_09 56 00](https://cloud.githubusercontent.com/assets/21006/12818625/a1a6b4b2-cb25-11e5-92ce-d189eb7a62a0.png)
![incommon_federation_info_entities_-_2016-02-04_09 56 38](https://cloud.githubusercontent.com/assets/21006/12818624/a1a677a4-cb25-11e5-992e-28895211be99.png)

... and I *think* one server should be enough but I'll check with @kcondon if he'd like more from the list at https://github.com/IQSS/dataverse/issues/2104#issuecomment-122875686 registered with InCommon.

**Comment by pdurbin** [comment]
I checked in with @kcondon and he said that ideally the following servers would be registered with InCommon:

- https://dataverse.harvard.edu (production) - public
- https://demo.dataverse.org (demo of latest release) - public
- https://beta.dataverse.org (demo of pre-release software) - public
- build server 1 (QA) - private
- build server 2 (QA) - private

I'm adding public vs. private above because I **think** that all servers would necessarily become public as part of the InCommon registration process. This means that they would need to be given stable hostnames and have real SSL certs, etc.

I don't think we should bother registering https://apitest.dataverse.org and in general I think there's agreement that this should some day be deprecated in favor of https://demo.dataverse.org

Likewise, it's probably not worth registering http://phoenix.dataverse.org . It's actively used but we don't need to clutter up the InCommon list and there seem to be enough other hosts to test on. Same with cluster/staging which is used for load testing.

I'm planning on using https://shibtest.dataverse.org for testing in the near term but I don't think it needs to be registered with InCommon either. We can use beta or some other server.

**Comment by pdurbin** [comment]
I just changed the entityID on https://demo.dataverse.org to the one we want to use (`entityID="https://demo.dataverse.org/sp"`). I changed it in two places:

```
[root@dataverse-demo ~]# cd /etc/shibboleth
[root@dataverse-demo shibboleth]# diff shibboleth2.xml.2016-02-04.oldhostname shibboleth2.xml
16c16
<     <ApplicationDefaults entityID="https://dataverse-demo.iq.harvard.edu/shibboleth"
---
>     <ApplicationDefaults entityID="https://demo.dataverse.org/sp"
31c31
<             <SSO discoveryProtocol="SAMLDS" discoveryURL="https://dataverse-demo.iq.harvard.edu/loginpage.xhtml">SAML2 SAML1</SSO>
---
>             <SSO discoveryProtocol="SAMLDS" discoveryURL="https://demo.dataverse.org/loginpage.xhtml">SAML2 SAML1</SSO>
[root@dataverse-demo shibboleth]# 
```

Running `service shibd restart` was enough to download the new metadata from https://demo.dataverse.org/Shibboleth.sso/Metadata but insufficient for login to work properly. I had to run `service httpd restart` as well. Now it works again for TestShib users (I re-uploaded the metadata per http://guides.dataverse.org/en/4.2.3/installation/shibboleth.html#testing ) but not for Harvard or MIT users. They'll see errors like below until we either join InCommon or ask for another out-of-band metadata exchange:

![harvardsp](https://cloud.githubusercontent.com/assets/21006/12826976/94b9ec8a-cb4b-11e5-9c31-19e773d3bdf5.png)
![mitsp](https://cloud.githubusercontent.com/assets/21006/12826975/94b7bffa-cb4b-11e5-8b22-0b2c816d09e4.png)

**Comment by pdurbin** [comment]
As of yesterday (INC01606454) https://dataverse.harvard.edu/Shibboleth.sso/Metadata and https://dataverse.harvard.edu/Shibboleth.sso/DiscoFeed are back in action. I chatted with @bencomp about this at http://irclog.iq.harvard.edu/dataverse/2016-02-25

We still need to (via INC01226245):

- [ ] register https://dataverse.harvard.edu with InCommon
- [ ] register https://demo.dataverse.org with InCommon
- [ ] register https://beta.dataverse.org with InCommon (can start work on #2937 prior to this)

Once these are registered with InCommon I'll consider this issue ready for QA.

**Comment by pdurbin** [comment]
A week ago the people working on INC01226245 replied and said they are actively trying to resolve it.

**Comment by pdurbin** [comment]
@kcondon and I discussed how #2937 is really a better issue to leave open for getting Harvard servers registered with InCommon in INC01226245 since it's about federated login so I'm passing this to QA to close. I changed the title of this issue to be about changing the entityID to end in "sp" rather than "shibboleth" which we have done on all of our servers and in the guides.
