### ISSUE TITLE
Re-ingest FITS files to extract metadata

### ISSUE THREAD

**Issue by mercecrosas** [IQSS/dataverse#2105]
Now that we've deployed Dataverse 4.0, we want to re-ingest all the FITS file that had been previously uploaded so we can take advantage of the new ingest and the extraction and indexing of VO metadata values from FITS files.

**Comment by sbarbosadataverse** [comment]
@scolapasta is this complete?

**Comment by landreev** [comment]
No, there may still be a few things to clean up there.

**Comment by pdurbin** [comment]
As far as I know, reingesting files is a manual process but perhaps this functionality should be added. Here's an example of manually reingesting a file: https://github.com/IQSS/dataverse/issues/2218#issuecomment-143636105

**Comment by mheppler** [comment]
Duplicate (?) of _FITS files: Investigate ingesting older FITS files that were added before FITS and md5 functionality. #2131_
