### ISSUE TITLE
Messaging For Request Access Depending on Version or State

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#2106]
From @scolapasta 

During today's demo, we noticed a peculiar issue around setting allow file requests, but I think we now understand the current behavior and we just need to decide how it should work. 

Background:

For datasets you can set "allow users to Request Access" as true or false. Similar to file restrictions there are two scopes for this value:
- the version: this can be different per version, i.e. in version one it can be set to false, then in version 2 it can be set to true; it is stored for each version and kept for historical reasons (e.g. a user can see what it had been set at during different version, just like terms of use)
- the dataset: this is what is actually used for all files, regardless of version. So when I view the files, regardless of which version I am looking at, the logic for showing the button is based on the published version.

Current behavior:

The terms tab shows the value for the dataset, regardless of what version you're looking at. So currently there is no way to see the historical values.

Showing the historical values, would be a relatively straightforward fix. But in discussing with Eleni, while the current display is confusing, this also could be. So I got version 1, see it says I can request, go to files, but cannot. 

Proposal:
We display the historical value when looking at a past version, however, we have some kind of indicator showing that this is no longer the actual value. For example, it could say "Files access can be requested" then some kind of warning icon that when hovered over, says "this has changed in the current value". If we like this general idea, I'd leave it to the UX team to decide the best way to represent this.

We should also consider doing something similar with the lock icons for files. If I got to v1 and see no lock, I will wonder why no download button.

Question: 
As this change is non trivial, if we go with it, it should be for 4.0.x (hopefully x=1). But should we make any simple quick change to the current behavior in a patch. Is it better to confuse the day owner now (not showing the current version value when looking at a draft) versus confusing the end user when looking at the past versions.

**Comment by eaquigley** [comment]
Instead of having a hover over that says, "this has been changed in a later published version", I think we should have it displayed in the UI as there is room in that section. My proposal would be to have text where it says Request Access that reads something along the lines of: "File request access has been changed in a later published version so files in this version can no longer be requested or downloaded." (This text would obviously need some editing and shortening.)

@posixeleni @scolapasta @mcrosas @mheppler

**Comment by scolapasta** [comment]
What about the opposite, were it wasn't allowed but no is (and the button will also be there)?
