### ISSUE TITLE
Dataverse Theme: Unable to Save an Uploaded Logo

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#2108]
Both @dliburd  and I tried to upload a logo in this Dataverse https://dataverse.harvard.edu/dataverse/ubiquity-press and in other ones using Chrome and Firefox and it will look like it completed uploading but the upload bar never goes away and does not allow you to select if the logo is rectangular or square since it just hangs up on the upload. When I save the theme it saves everything else but the image. The image size I am trying to upload is MUCH smaller than the 500KB limit (trying with a 3.6KB image) https://thedata.harvard.edu/images/up_opendata.png

![image](https://cloud.githubusercontent.com/assets/5013837/7379061/fbd6cbe6-edbf-11e4-88c9-886f99dcbd64.png)

@mheppler @scolapasta would you happen to know what may be causing this?

**Comment by dliburd** [comment]
I was able to upload successfully the UP logo file on dataverse-demo. Also, I able to recreate the upload fail in production with another image file.

**Comment by posixeleni** [comment]
This is now working for me in production. Not sure if this is an intermittent issue?

**Comment by scolapasta** [comment]
Could we retest this?

**Comment by posixeleni** [comment]
Tested and now working as expected. Closing.
