### ISSUE TITLE
Trimming white spaces issue - dataverse alias

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#211]
---

Author Name: **Elda Sotiri** (@esotiri)
Original Redmine Issue: 3625, https://redmine.hmdc.harvard.edu/issues/3625
Original Date: 2014-03-04
Original Assignee: Xiangqing Yang

---

Entering a space at the end of the alias generates the following. I would expect to trim the white space at the end of alias, if any,  and allow save action. 

Found an illegal character(s). Valid characters are a-Z, 0-9, '_', and '-'.Found an illegal character(s). Valid characters are a-Z, 0-9, '_', and '-'.

**Comment by pdurbin** [comment]
@eaquigley do you have a different expectation if someone tries to create a dataverse with a trailing space via API? Via API I'd expect to see an error message indicating which characters are valid, as reported above. However, as I believe @joshhartigan is suggesting, we **could** do the automatic trimming for both API and GUI.

**Comment by pdurbin** [comment]
@eaquigley oh, sorry, it was Elda who asserted an expectation above. I think @raprasad simply used your GitHub accounts to import this issue from Redmine.

**Comment by mheppler** [comment]
Found a JSF-related, suggested solution on [Stackoverflow](http://stackoverflow.com/questions/33233398/how-to-prevent-spaces-form-jsf-hinputtext).

**Comment by pdurbin** [comment]
In case it's of interest, I just wrote some tests of validation logic here: https://github.com/IQSS/dataverse/blob/ff7770b3cc24bcc88b868dcc1248c5d43ad39264/src/test/java/edu/harvard/iq/dataverse/authorization/providers/builtin/BuiltinUserTest.java (hasn't been merged yet, it's part of my pull request at #2919 ).

**Comment by pdurbin** [comment]
@joshhartigan are you still interested in working on this bug?

**Comment by pdurbin** [comment]
Come to think of it. I think the behavior described in the original report is what we want. We show an error when an invalid character is entered for a dataverse alias. Vote to close.
