### ISSUE TITLE
View Dataverse: HTML in description can cause page layout /float issues.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2114]
Specific use case: FF browser for the [1.2 Meter CO Survey Dataverse](https://dataverse.harvard.edu/dataverse/rtdc). Dataverse/Datasets/Files facets appear to right of description rather than below it.

![screen shot 2015-08-27 at 2 13 10 pm](https://cloud.githubusercontent.com/assets/687227/9529006/d0f4d412-4cc5-11e5-9987-619903fadabe.png)

**Comment by mheppler** [comment]
Just doing a quick look at the description and it's HTML, it appears that the align="left" attribute and property of the image is what is causing the layout issue.

There is already an open issue for HTML that we should support in our metadata fields #1320 (Priority: High, Milestone: In Review). This specific issue in this ticket can be resolved one of the following ways:

- A.) The layout of the dataverse page can be fixed to avoid layout issues like this in the future.

- B.) The HTML that is allowed in metadata fields can be restricted using a white-list, as is suggested in #1320.

- C.) The dataverse admin (or a Dataverse Support team member) can edit the HTML to fix this layout issue. (This would be easier on the user if there was a "preview" feature to the description field.)

What probably needs to happen is all three of these options, and a whole lot of testing on the kind of HTML being used in these kind of metadata fields in production.

**Comment by mheppler** [comment]
Added a "clearfix" element under the dataverse description containing element, to fix an align/float issue with HTML in the description.

Moving the above comment to issue #1320 to look into how the align attribute will be handled in the HTML validation on the description field.

**Comment by kcondon** [comment]
OK, the last change made FF behave the same as Chrome, closing.
