### ISSUE TITLE
Linked Dataverse + Datasets: Ability to Request to Link

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2118]
Feedback from a user for us to think about:

A user finds a dataverse that relates to a dataverse or dataset they have, this functionality would be for that user to request/contact that dataverse admin to say, "hey would you be interested in linking my (insert name of) dataverse or dataset?"

We have contact functionality so a user could always email the dataverse admin that way about this but I'd like to crowdsource for a bit and see if this is a feature other users would be interested in/have a need for.

**Comment by pdurbin** [comment]
@eaquigley would this show up as a notification? And an email as well? It sounds potentially spammy. I guess it's like a friend request, sort of. Someone would like to "connect" with you on Dataverse.

**Comment by pdurbin** [comment]
I still think is spammy. Closing.
