### ISSUE TITLE
File Upload: Investigate and potentially disable JSP file upload caching.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2125]
The generated/jsp directory caches files that have been uploaded but not yet saved. After saving it deletes them. However, there seems to be a lot of orphans in the cache that are not being removed.

This ticket is to investigate better ways of managing this behavior:
disable, make cache directory configurable

**Comment by bencomp** [comment]
We experience this too. Via a support ticket we (@ekoi and @kcondon) discussed using a symbolic link to at least prevent having lots of orphaned files in the application directory. This seems to work, but a configurable directory is better. In DVN 3.6.2 it wasn't clear to us that there would be a difference between the temporary directory (which is configurable using a JVM option) and the "arrivals area" in which uploaded but not yet saved files are cached. I guess the same holds for Dataverse 4?

**Comment by tomck** [comment]
@bencomp How did you get a symbolic link to work? For me, I can create the symbolic link to a temporary disk, but when the application starts it magically replaces it with a real directory on the present disk. Once glassfish is stopped the symbolic link returns.

**Comment by pdurbin** [comment]
@tomck you may or may not get a quick answer from @bencomp since he's no longer a service manager for DataverseNL: http://irclog.iq.harvard.edu/dataverse/2016-06-03#i_36010 . I'd suggest emailing support@dataverse.org with questions about these symlinks.

**Comment by pdurbin** [comment]
This issue is related to #2140 and #2848.

**Comment by pdurbin** [comment]
Related:

- #8983

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
