### ISSUE TITLE
'Explore' ('View map') button is visible even if TwoRavens (WorldMap) is not configured

### ISSUE THREAD

**Issue by bencomp** [IQSS/dataverse#2135]
As a provider of the Dataverse application to users, we would like to keep the service simple and lightweight and not install and support the TwoRavens application (at least from the beginning of using Dataverse 4; we may change this in the future).

In our test environment the *Explore* button is visible even if we don't install and configure Two Ravens, which seems to be an integration that is too tight. If I understand the source code correctly, the same happens for geographical data and World Map.

https://github.com/IQSS/dataverse/blob/master/src/main/webapp/dataset.xhtml#L722-L757

I would like Two Ravens and World Map to be optional service components. Dataverse and integration with TwoRavens/WorldMap should be configurable.

**Comment by posixeleni** [comment]
@bencomp this is something we have heard from other dataverse installations as well https://github.com/IQSS/dataverse/issues/901

**Comment by mcrosas** [comment]
@bencomp would this apply to ingesting tabular files to extract variable metadata + reformat? or just the explore button?

**Comment by bencomp** [comment]
@mcrosas just the button(s). I was told that setting up rApache, Zelig, TwoRavens wasn't easy... (Yes, we did install them in the test environment, but plan to not use them in production.)

We do want the functionality to extract variable metadata and download as other formats.

**Comment by raprasad** [comment]
1. Turn on/off the ability to use TwoRavens
       Explore buttons don't appear on the file listing page next to tabular info
2. Add Default Two Ravens Information to initial SQL script
3. Update instructions

Similar to #2957

**Comment by raprasad** [comment]
Need to add initial sql script, rewrite other two ravens button to use new method

**Comment by raprasad** [comment]
Helpful queries:
```sql
insert into setting (':TwoRavensTabularView', 'true');
update setting set content='false' where name = ':TwoRavensTabularView';
update setting set content='true' where name = ':TwoRavensTabularView';
```

**Comment by kcondon** [comment]
@raprasad OK, new 2 ravens setting works. I did not see this in the install doc though?

**Comment by kcondon** [comment]
OK looks good. Closing.
