### ISSUE TITLE
The metadata could not be updated.  Please contact support. for GSD dataverse

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2136]
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/SPQAZT&version=DRAFT

![gz3v6oxsugzadftqo3wxqxz0jyzom2olqz74fhuxpou](https://cloud.githubusercontent.com/assets/8322346/7519543/da0a2936-f4ae-11e4-9fa0-cae4e82d587b.png)

**Comment by pdurbin** [comment]
@sbarbosadataverse can you please tell us some more about this dataset? Was it migrated? Is it new? Anything unusual about it?

**Comment by sbarbosadataverse** [comment]
@pdurbin 
was created May 5th, first draft . no published version available.

**Comment by scolapasta** [comment]
This is working now.

**Comment by sbarbosadataverse** [comment]
Thank you!
