### ISSUE TITLE
Files Display: Image + PDF previews not displaying

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2137]
When 4.0 was first launched, thumbnails were being generated for all images and pdfs that existed in 3.6. Once critical errors started happening, this was turned off. This ticket is a reminder to go back and finish generating those thumbnails.

Additionally, broken images icons are appearing for some of the thumbnails that have been generated. Would be good to have the mouseover hover images generated at the same time as the thumbnail.

**Comment by eaquigley** [comment]
On dataverse.harvard.edu, this seems to be working again. Passing ticket to @kcondon to review and decide if it can be closed.

**Comment by kcondon** [comment]
Works, closing
