### ISSUE TITLE
Error Reporting: Automatically capture user errors and stack traces, send alerts and store them.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2138]
We already log many error conditions but it was discussed that when users encounter an error, the failure message is too generic to be of use to them. 

We should distinguish between user task based errors where they just entered something incorrectly versus a system error.

Task based errors should be handled with appropriate messaging and possible redesign.
System errors likely aren't recoverable by the user and I am not sure a specific message could be designed for it, hence fail whale type errors. 

However, it may be possible to reassure the user and capture enough technical information automatically to help identify and troubleshoot the issue.

So, generic message: a system error has occurred, technical details are being sent to the development team. If you would like to follow up, open a ticket here: support@dataverse.org and reference this number (system generated number).

On the dataverse side, we could capture the command, the user, the stack trace, time of day, browser, and which production server was accessed. Also, stamp it with the reference number. This could possibly automatically generate an RT ticket or just go in to a mailing list, be an online notification to the admin and view a summary event log rather than viewing the server log directly.

**Comment by pdurbin** [comment]
This seems highly related to #2130 and #2134 and I wonder if this is in scope for the dashboard being designed at https://trello.com/c/kDSgIVVS/8-administrative-dashboard-4-7 for #840.

**Comment by mheppler** [comment]
@pdurbin commented on Dec 21, 2016 on issue "Error Messages: Have a way to track error messages users encounter" #2130
>We could consider using something like https://rollbar.com or https://sentry.io for this. There's also Splunk (or open source equivalents), which I've mentioned at #3428 (comment) and #2879 (comment) . I couldn't agree more that it would great to determine pain points in the application so that we can fix them!

I agree with his comment that this issue is highly related, so I am closing that previous issue and keeping this one.

**Comment by pdurbin** [comment]
Yeah, I feel like Rollbar is the one I hear about from time to time. I'm fine with you closing #2130 @mheppler because I like it when open issues were created by people who still have a stake or interest in Dataverse. Someone we can follow up with and say, "Hey, we fixed that issue you opened. Are you excited?" 😄

**Comment by djbrooke** [comment]
I'm going to close this, because while it's possible for us to implement it's much more likely we would rely on external tooling such as Splunk or one of the other tools mentioned to report/alert on these errors.

**Comment by bencomp** [comment]
Even with external tooling you would need an SDK inside Dataverse to capture the error and send it to the external tool.

**Comment by pdurbin** [comment]
@bencomp which tools have you used for this? Also, come say hi at FOSDEM! You're in a group pic in my slides: https://fosdem.org/2020/schedule/event/dataverse/ 😄
