### ISSUE TITLE
File upload: Consider creating configurable file upload and ingest upload size limits.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2141]
As we gain more experience with our new platform, we may need to set practical limits on uploads and ingests. It should be configurable so we can adjust as we learn more. 

One suggestion was to present a popup or some message to a user if their upload exceeds a limit, do not upload of course, then give them the option of requesting permission.

For ingest same but maybe also allow a choice of upload without ingest in case of ingest size limit?

**Comment by bencomp** [comment]
Related: #938

**Comment by pdurbin** [comment]
I think we did this already (well, I'm not sure about the popup suggestion). See :MaxFileUploadSizeInBytes and :TabularIngestSizeLimit and :ZipUploadFilesLimit at http://guides.dataverse.org/en/4.6/installation/config.html

If more work is in scope for this issue, it should be defined.
