### ISSUE TITLE
Allow topic classification field to be multiple and hierarchical

### ISSUE THREAD

**Issue by mercecrosas** [IQSS/dataverse#2143]
The "topic classification" (or simply "classification") metadata field should allow not only multiple entries but also a hierarchy. This would solve a lot of problems recreating something like "collections" in Dataverses, and it wouldn't require creating new metadata blocks for each case (which are are harder to maintain than simply using existing metadata fields). The facets for these classification hierarchy would serve as "collections" for a Dataverse. For example, for a journal:

Classification 1: Journals by Year and Volume

- 2015
  - Volume 1 
  - Volume 2
  - Volume 3
- 2014
  - Volume 1 
  - ...

Another example, for courses:

Classification 1: 
- Introductory statistics
  - Fall
  - Spring
- Advanced statistics 
  - Fall
  - Spring

Similar examples could work for PSI dataverse.

This issue relates to: 

- #434

**Comment by posixeleni** [comment]
Also relates to this #377 since we most likely want multiples within a single compound metadata field.

**Comment by posixeleni** [comment]
For Journals I would recommend that we use the Journal Metadata (NISO JATS Schema) that I put together which stores the Journal Volume, Issue and Year as a compound field https://docs.google.com/spreadsheets/d/13HP-jI_cwLDHBetn9UKTREPJ_F4iHdAvhjmlvmYdSSw/edit#gid=8

So we could potentially, like topic classification show this information hierarchically.

**Comment by mcrosas** [comment]
:+1:

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
