### ISSUE TITLE
Create Account: Change Redirect to Take User back to the page they came from

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2145]
In the "open" dataverse in 4.0, and as reported by users, if a user first navigates to the a dataverse and they click on "sign-up" because they don't have an existing dataverse account, they are redirected off the restat dataverse after sign-up is complete

Needs to be fixed to be this workflow:

User is on a dataverse page (say, Gary King Dataverse)->clicks on Sign Up->Creates an Account->Brought back to page they were originally on (Gary King Dataverse)

**Comment by pdurbin** [comment]
I assume any fix for 4.2 is only for BuiltIn users since Shibboleth users are never redirected right now per #1551.

**Comment by scolapasta** [comment]
This uses the same redirect logic as the login page (added to the dataverse suer page for create, of course)

**Comment by kcondon** [comment]
This works, tested in FF, Chrome, Safari. Did not test Shib, this is not yet enabled in prod and not nfigured. Closing.
