### ISSUE TITLE
Add file upload limiter

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#2149]
Add to the settings, if no setting, then lo limit.

Make sure it is used my primefaces upload, the API, and the dropbox upload.

**Comment by pdurbin** [comment]
@raprasad please note that the API already uses `DataDepositApiMaxUploadInBytes` per #1043 so please update the code and docs to use instead whatever new common (shared between the GUI and API) `setting` table key you come up with.

Here's how you'd test afterwards: http://guides.dataverse.org/en/latest/api/sword.html#add-files-to-a-dataset-with-a-zip-file

**Comment by raprasad** [comment]
- [ ] rename ```DataDepositApiMaxUploadInBytes``` to ```DataDeposiMaxUploadInBytes```
- [ ] dropbox: use in DatasetPage.java ```handleDropBoxUpload```
- [ ] UI:  sizeLimit="500000" invalidSizeMessage="File exceeds our limits. Please contact support."

**Comment by raprasad** [comment]
If MaxFileUploadSizeInBytes is found in the settings table, use that number.  If not, default to unlimited upload size.

Moving to QA

**Comment by kcondon** [comment]
OK, works, closing. Need to set this is prod to 10GB.
