### ISSUE TITLE
Data - File Structure

### ISSUE THREAD

**Issue by chaudj** [IQSS/dataverse#2150]
In the previous versions of Dataverse, we have always had a file structure that groups similar data sets together. Any chance of having the same in 4.0. Something like this: 
![dataverse](https://cloud.githubusercontent.com/assets/3154601/7580825/5e88e052-f884-11e4-8402-50e3a47bbf31.PNG)

**Comment by mcrosas** [comment]
Thanks for submitting this issue, we've heard this from other users. We are thinking of a different solution for 4.0, providing at the top of the files table options to filter and sort by the categories/tags. Assigned to @eaquigley who can follow up on details.

**Comment by mcrosas** [comment]
As we finish the design, this will be a candidate for 4.0.2.

**Comment by eaquigley** [comment]
Functional Requirements Document for this feature: https://docs.google.com/document/d/1RkPycxX3nsCJJV9xbhc2mXvgwxJTkyDCsb_k2LGWrII/edit?usp=sharing

**Comment by mheppler** [comment]
Here are the mockups for the File Tag feature, with hierarchical levels, that will be utilized to group and filter files.

https://iqssharvard.mybalsamiq.com/projects/filesprovenancefacetsfilter-dataverse40/Dataset%20-%20Files%20-%20Tag%20Hierarchy

![screen shot 2015-09-08 at 2 00 08 pm](https://cloud.githubusercontent.com/assets/687227/9743053/37e749e6-5632-11e5-9fd1-f360b9378ed2.png)

**Comment by chaudj** [comment]
Hi Michael

Thanks, but I think it would make more sense to have all files  be grouped together like this 
![5e88e052-f884-11e4-8402-50e3a47bbf31](https://cloud.githubusercontent.com/assets/3154601/9756101/22771d62-56e0-11e5-905e-e15850a68604.PNG)

As opposed to this - which is similar to the mockup above,
![2](https://cloud.githubusercontent.com/assets/3154601/9756162/aa3e8140-56e0-11e5-9a39-e918d6d0a248.PNG)

The hierarchy system would look more prominent here.

Regards
Jacquie

**Comment by pdurbin** [comment]
Related:

- Files: Provide Way to Organize Files Hierarchically · Issue #2249
- Use Solr for file listing on dataset page · Issue #2455 
- File grouping in Dataverse 4 - Google Groups - https://groups.google.com/forum/#!msg/dataverse-community/PW6xCnhkjmQ/u7V6t82zAgAJ

**Comment by mheppler** [comment]
Related to #3247.

**Comment by mheppler** [comment]
@chaudj -- In issue #2249 we are discussing the intention to support directory structure being retained as part of the upload process, and displayed properly in the UI and retained for the end user upon download.

We are going to close this issue, but the two have been linked so your input here will not be lost. Please feel free to add any additional information in comments on that issue, which we will use to track this feature moving forward.
