### ISSUE TITLE
Upgrade from Java 7 to Java 8

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#2151]
According to [Oracle Java SE Support Roadmap](http://www.oracle.com/technetwork/java/javase/downloads/eol-135779.html) "after April 2015, Oracle will no longer post updates of Java SE 7 to its public download sites... Developers and end-users are encouraged to update to more recent Java SE versions that remain available for public download."

In short, we should upgrade to Java 8. Developers first, then test servers, then production.

**Comment by pdurbin** [comment]
@scolapasta we need a decision if on we are changing "[-target](http://docs.oracle.com/javase/8/docs/technotes/tools/windows/javac.html)" in the pom.xml from 1.7 to 1.8 or not. If so, Java 8 will become a hard requirement for people installing Dataverse. I'm fine with this.

**Comment by pdurbin** [comment]
In this morning's meeting we approved changing "source" and "target" to 1.8 which @sekmiller did in 8768e05 (in the 2731-techupdate) branch.

As expected, this has a ripple effect. The Travis build failed: https://travis-ci.org/IQSS/dataverse/builds/90152574

I can't build on my Mac ("Fatal error compiling: invalid target release: 1.8"):

```
murphy:dataverse pdurbin$ mvn package
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building dataverse 4.3
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.6:copy (default) @ dataverse ---
[INFO] 
[INFO] --- jacoco-maven-plugin:0.7.5.201505241946:prepare-agent (jacoco-initialize) @ dataverse ---
[INFO] argLine set to -javaagent:/Users/pdurbin/.m2/repository/org/jacoco/org.jacoco.agent/0.7.5.201505241946/org.jacoco.agent-0.7.5.201505241946-runtime.jar=destfile=/Users/pdurbin/NetBeansProjects/dataverse/target/jacoco.exec
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ dataverse ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 15 resources
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ dataverse ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 483 source files to /Users/pdurbin/NetBeansProjects/dataverse/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.443 s
[INFO] Finished at: 2015-11-09T13:55:08-05:00
[INFO] Final Memory: 18M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project dataverse: Fatal error compiling: invalid target release: 1.8 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
murphy:dataverse pdurbin$ 
```

At https://github.com/IQSS/dataverse/commit/8768e05fa3a0bff256d2a5fde902a8c1167ca1b7#commitcomment-14283949 I've been discussing a fix for Travis.

On my Mac, I can get "BUILD SUCCESS" but running `JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home mvn package` but I'll want to figure out a better long term fix once the 2731-techupdate branch gets merged into a release branch.

**Comment by pdurbin** [comment]
I just pushed a346a4a which seems like a good fix for Travis:

![builds_-_iqss_dataverse_-_travis_ci_-_2015-11-09_14 05 46](https://cloud.githubusercontent.com/assets/21006/11043513/0f84f4b4-86eb-11e5-8a95-72c28468d4cc.png)

This blog post was helpful: http://blog.travis-ci.com/2013-11-26-test-your-java-libraries-on-java-8/

**Comment by pdurbin** [comment]
I'm giving this to @sekmiller to comment on any Java 8 tips for @mheppler and others who want to help with the 2731-techupdate branch.

**Comment by pdurbin** [comment]
Stealing this back from @sekmiller . @mheppler and I are able to deploy to our Mac laptops with Java 8. Netbeans seems to do the right thing. On @mheppler 's machine we undeployed, stopped Glassfish, and then click "Run" in Netbeans.

I started tweaking the Vagrant scripts a bit locally to get Java 8 installed (nothing to push yet) and noticed that at least on CentOS 6 Java 7 still seems to be the default:

```
[vagrant@standalone ~]$ rpm -qa | grep openjdk
java-1.6.0-openjdk-1.6.0.36-1.13.8.1.el6_7.x86_64
java-1.8.0-openjdk-1.8.0.65-0.b17.el6_7.x86_64
java-1.7.0-openjdk-1.7.0.91-2.6.2.2.el6_7.x86_64
java-1.8.0-openjdk-devel-1.8.0.65-0.b17.el6_7.x86_64
java-1.8.0-openjdk-headless-1.8.0.65-0.b17.el6_7.x86_64
java-1.7.0-openjdk-devel-1.7.0.91-2.6.2.2.el6_7.x86_64
[vagrant@standalone ~]$ 
[vagrant@standalone ~]$ java -version
java version "1.7.0_91"
OpenJDK Runtime Environment (rhel-2.6.2.2.el6_7-x86_64 u91-b00)
OpenJDK 64-Bit Server VM (build 24.91-b01, mixed mode)
[vagrant@standalone ~]$ 
[vagrant@standalone ~]$ cat /etc/redhat-release 
CentOS release 6.5 (Final)
[vagrant@standalone ~]$ 
```

**Comment by pdurbin** [comment]
In 1abbd77 I put a quick hack into the Vagrant scripts to make Java 8 the default for `java` and `javac`. The app seems to compile, deploy, and run fine.

The hack assumes the Java 8 is the second line in this output:

```
[root@standalone ~]# alternatives --config java

There are 3 programs which provide 'java'.

  Selection    Command
-----------------------------------------------
   1           /usr/lib/jvm/jre-1.6.0-openjdk.x86_64/bin/java
 + 2           /usr/lib/jvm/jre-1.8.0-openjdk.x86_64/bin/java
*  3           /usr/lib/jvm/jre-1.7.0-openjdk.x86_64/bin/java

Enter to keep the current selection[+], or type selection number: 
[root@standalone ~]# 
```

For Vagrant, this might be fine. In our Installation Guide, perhaps we'll document how to run the command above and select the default version of Java interactively.

**Comment by pdurbin** [comment]
Here's how I just switched https://shibtest.dataverse.org from Java 7 to Java 8:

```
[root@dvn-vm3 ~]# java -version
java version "1.7.0_91"
OpenJDK Runtime Environment (rhel-2.6.2.2.el6_7-x86_64 u91-b00)
OpenJDK 64-Bit Server VM (build 24.91-b01, mixed mode)
[root@dvn-vm3 ~]# 
[root@dvn-vm3 ~]# rpm -qa | grep openjdk
java-1.7.0-openjdk-1.7.0.91-2.6.2.2.el6_7.x86_64
[root@dvn-vm3 ~]# yum -y install java-1.8.0-openjdk
(snip)
[root@dvn-vm3 ~]# rpm -qa | grep openjdk
java-1.8.0-openjdk-headless-1.8.0.65-0.b17.el6_7.x86_64
java-1.7.0-openjdk-1.7.0.91-2.6.2.2.el6_7.x86_64
java-1.8.0-openjdk-1.8.0.65-0.b17.el6_7.x86_64
[root@dvn-vm3 ~]# 
[root@dvn-vm3 ~]# alternatives --config java

There are 3 programs which provide 'java'.

  Selection    Command
-----------------------------------------------
*+ 1           /usr/lib/jvm/jre-1.7.0-openjdk.x86_64/bin/java
   2           /usr/lib/jvm/jre-1.5.0-gcj/bin/java
   3           /usr/lib/jvm/jre-1.8.0-openjdk.x86_64/bin/java

Enter to keep the current selection[+], or type selection number: 3
[root@dvn-vm3 ~]# 
[root@dvn-vm3 ~]# java -version
openjdk version "1.8.0_65"
OpenJDK Runtime Environment (build 1.8.0_65-b17)
OpenJDK 64-Bit Server VM (build 25.65-b01, mixed mode)
[root@dvn-vm3 ~]# 
```

Then I restarted Glassfish and made sure I saw Java 8 ("java-1.8.0-openjdk") in server.log:

```
[2015-11-17T14:36:03.417-0500] [] [INFO] [NCLS-GFLAUNCHER-00005] [javax.enterprise.launcher] [tid: _ThreadID=1 _ThreadName=main] [timeMillis: 1447788963417] [levelValue: 800] [[
  JVM invocation command line:
/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.65-0.b17.el6_7.x86_64/jre/bin/java
```

http://guides.dataverse.org/en/4.2.1/installation/prerequisites.html says it's fine to use OpenJDK but I believe that in practice we run Oracle JDK in production.

@kcondon I'm passing this to you for feedback and assigning this to the 4.2.2 milestone to see what you need from me to help you get the [I2731-techupdate](https://github.com/IQSS/dataverse/tree/2731-techupdate) branch deployed somewhere.

**Comment by kcondon** [comment]
I will do some regression testing initially to help plan when this might be deployed.

**Comment by pdurbin** [comment]
I pulled this out of QA to document in the Dev and Installation Guides that Java 8 will be required.

**Comment by pdurbin** [comment]
> On my Mac, I can get "BUILD SUCCESS" by running JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home mvn package but I'll want to figure out a better long term fix once the 2731-techupdate branch gets merged into a release branch.

Since this merge is done, this matters to me more now. :)

My fix was to update my ~/.bashrc file to contain this:

```
export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_25.jdk/Contents/Home
```

Now running `mvn package` works fine from my Mac. Probably not many developers do this though. In practice Netbeans should take care of all this for us.

What else? The job at https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-deploy/17/console failed with "remote failure: Error occurred during deployment: Exception while deploying the app [dataverse] : Class edu.harvard.iq.dataverse.api.datadeposit.SwordAuth has unsupported major or minor version numbers, which are greater than those found in the Java Runtime Environment version 1.7.0_91. Please see server.log for more details." As of 4.2.3 an error like this is expected when you try to deploy Dataverse to a Glassfish server that has been started with Java 7 rather than Java 8. To fix this I ran `alternatives --set java /usr/lib/jvm/jre-1.8.0-openjdk.x86_64/bin/java` as mentioned at https://github.com/IQSS/dataverse/issues/2151#issuecomment-157503081 to set the default version of Java. From what I hear this is configurable within Glassfish as well, but I don't see any problem with simply no longer calling Java 7 by default. It's EOL.

> I pulled this out of QA to document in the Dev and Installation Guides that Java 8 will be required.

I fixed this at 808f81b

I'm moving this issue to QA. @kcondon the change is reflected at http://guides.dataverse.org/en/4.2.3/installation/prerequisites.html#java (it now says "yum install java-1.8.0-openjdk-devel") but I'm happy to write more docs if you think it would be helpful.

**Comment by kcondon** [comment]
Closing

**Comment by kcondon** [comment]
@pdurbin Thanks, can we document alternatives too?

**Comment by pdurbin** [comment]
Sure! Done in 148b7f5 and now available at http://guides.dataverse.org/en/4.2.3/installation/prerequisites.html#java

**Comment by landreev** [comment]
Please disregard this if there is a separate documentation issue for this (but I couldn't find one); 
As of now, the JDK change is only half-reflected in the 4.2.3 documentation: 

The dev. guide still says that JDK 1.7 is required; 

The "prerequisites" section of the installation guide does say that 1.8 is needed. However, in the Mac paragraph it still says that "MacOS X comes with the JDK (but make sure you keep it updated)." - which isn't really true (?) - it still comes with 1.7. So it should probably give a link to the Oracle distribution of 1.8 instead.

**Comment by pdurbin** [comment]
@landreev good catch. As we discussed the dev guide seems fine, but I rewrote the Java section in the  Installation Guide in 454e5b4 (we'd like to rewrite the whole guide per https://docs.google.com/document/d/1GLky44JbtCNhGuavLXGEP8WPNdjbyHNxalEGjR78MaA/edit?usp=sharing ).

@kcondon this is ready for QA.

**Comment by kcondon** [comment]
Looks good, closing.
