### ISSUE TITLE
dropbox upload button gives an error 

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#2152]
Only tested with my personal dv account:

Error message:
```json
{"error": "Origin does not match any app domain"}
```

Url of pop-up box: 
```
https://www.dropbox.com/chooser?origin=https%3A%2F%2Fdataverse.harvard.edu&app_key=1itrou6ddxx0bsd&link_type=direct&trigger=js&multiselect=true&extensions=&folderselect=false&iframe=false&version=2
```

![mozilla_firefox_and_new_haven_crime_data__2007_-_new_haven_independent_dataverse](https://cloud.githubusercontent.com/assets/1036060/7589480/eb5b6110-f890-11e4-8a7f-0ab4d952f86f.png)

**Comment by raprasad** [comment]
thanks for looking at this @landreev

**Comment by landreev** [comment]
Is working now.

**Comment by kcondon** [comment]
Works, closing.
