### ISSUE TITLE
Update Guide references in code

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#2153]
So we want all guides to go to dataverse.org. (but configurable for an installation if they want to modify them for themselves).

So we'll want a setting for the general root: http://guides.dataverse.org/
and then the code would use this and add the rest of the URL (i.e.user/index.html while also getting the version dynamically)

**Comment by pdurbin** [comment]
In 6bc409f I just pushed the ability to change the base URL for guides from http://guides.dataverse.org and documented it here: http://guides.dataverse.org/en/latest/installation/installation-main.html#guidesbaseurl

**Comment by pdurbin** [comment]
Passing to QA.

**Comment by kcondon** [comment]
Works, default is fine and setting updates guides url. Closing.
