### ISSUE TITLE
Navigation + Bundle: Guides Links for Navbar, Bundle, etc.

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2154]
About
Guides with dropdown for User Guide, API Guide, Installation Guide, Developers Guide (talk to @pdurbin  about this please)
Support (pop up form)
Sign Up
Log In

**Comment by mcrosas** [comment]
Related to: https://github.com/IQSS/dataverse/issues/2153

**Comment by pdurbin** [comment]
The main thing to know about linking to the Developers' Guide is that (unlike the other guides) we always want to link to the **latest version**: http://guides.dataverse.org/en/latest/developers

For the other guides, we want to link to **the version that is currently installed** (that the user is actively using) such as http://guides.dataverse.org/en/4.0/user (or 4.0.1 or 4.3, etc.).

**Comment by mheppler** [comment]
Revamped navbar with new links for each of the guides, including dynamic version number in the URL where needed.

In addition to pointing the Developers Guide link to "latest", I am also pointing the Installation Guide to "latest" as well.

Also found a number of instances across the application, where links to the guides have absolute paths to the "latest" version, and should be dynamic (in the app) or relative (in the guides), so that any version numbers needed in the path can be utilized and maintained.

Here is a list of places where guides links needed to be updated:
- [ ] /doc/sphinx-guides/source/user/dataset-management.rst

**Comment by posixeleni** [comment]
I can look at the dataset page you mention below to make sure they all have relative links on there.

**Comment by mheppler** [comment]
Changed links in guides to be relative, instead of absolute, to allow for dynamic versions and roots.

**Comment by mheppler** [comment]
Passing to @sekmiller to look into the MailServiceBean.java and DataversePage.java uses of the bundle, and how to make the messages delivered from the bundle contain the dynamic version number `#{dataverseServiceBean.applicationVersion}` and root `#{systemConfig.guidesBaseUrl}`.

**Comment by pdurbin** [comment]
I explained e81a7aa to @scolapasta before committing and there's still more to do but it's a good start. Next steps:

- [ ]  convert `notification.email.createDataverse` and `notification.email.createDataset` to use new BundleUtil methods (`dataverse.create.success` was converted in that commit)
- [ ] add variations of getGuidesBaseUrl that include the version (and perhaps make choice of language configurable
- [ ] reconcile/merge older DataverseServiceBean.getApplicationVersion() method with new SystemConfig.getVersion() method

**Comment by pdurbin** [comment]
Done. Passing to QA. Code clean up deferred.

**Comment by kcondon** [comment]
@mheppler @pdurbin @scolapasta Do we want to point to the latest installation guide? I think we want the latest *released* installation guide, no?

**Comment by pdurbin** [comment]
The idea of this ticket is that it should point to whatever version is at https://github.com/IQSS/dataverse/blob/master/src/main/java/VersionNumber.properties (4.0 as of this writing). So http://guides.dataverse.org/en/4.0/user or whatever.

**Comment by kcondon** [comment]
OK, links reference 4.0 except dev and install, which reference latest. Closing
