### ISSUE TITLE
Featured Dataverses: Review this functionality

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2155]
Reconsider Featured Dataverses so they could also be used to show the hierarchy of the dataverse.

cc @mcrosas

**Comment by sbarbosadataverse** [comment]
@eaquigley  Hi Liz, just wondering where we are with this feature? It seems to be coming up as I create collections etc....

**Comment by mcrosas** [comment]
Also, from @sbarbosadataverse and PSI consider how to we display a large number of featured dataverses - perhaps use a solution different than a carroussel.

**Comment by CCMumma** [comment]
From TAMU, institutional user of the Texas Data Repository: "Although the organization of a dataverse with datasets and sub-dataverses may be hierarchical, we lack a way to create a view that represents this beyond the possibility of displaying “featured dataverses” near the top of a page. By this I mean that a given dataverse will show all sub-dataverses and datasets contained within as a list. I’ve had researchers ask why there isn’t a way to reflect the organization they try to impose through collections."

**Comment by sbarbosadataverse** [comment]
Hi Courtney, Can you just provide an example, graphic perhaps, of what is
being requested?

Thanks

On Wed, Nov 8, 2017 at 3:12 PM, Courtney Mumma <notifications@github.com>
wrote:

> From TAMU, institutional user of the Texas Data Repository: "Although the
> organization of a dataverse with datasets and sub-dataverses may be
> hierarchical, we lack a way to create a view that represents this beyond
> the possibility of displaying “featured dataverses” near the top of a page.
> By this I mean that a given dataverse will show all sub-dataverses and
> datasets contained within as a list. I’ve had researchers ask why there
> isn’t a way to reflect the organization they try to impose through
> collections."
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_issues_2155-23issuecomment-2D342944600&d=DwMFaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=myzodusX2afpkQA6AZah9r7cK22FmNgwukJ9QC6r2Fc&s=CWPYrpnFytG-H1XZJVdm62L0Jfga2TS51MQmRKh2N8w&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AH79Kpan7YmttF6GpD7y8jagnhBmMQ8Wks5s0gskgaJpZM4EYPNH&d=DwMFaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=myzodusX2afpkQA6AZah9r7cK22FmNgwukJ9QC6r2Fc&s=kIvqqhsSZ4Ae5KjwA27Y3saUpbQT3Kh0nDEzHKUp9hc&e=>
> .
>



-- 
Sonia Barbosa
Manager of Data Curation, The Dataverse Project
Manager of the Murray Research Archive, IQSS
Data Science
Harvard University

all Harvard Dataverse Repository inquiries should be sent to:
support@dataverse.org

Dataverse 4.0 is now available for use!
http://dataverse.harvard.edu

All test dataverses should be created  in 4.0 Demo!
http://dataverse-demo.iq.harvard.edu/

Join our Dataverse Community!
https://groups.google.com/forum/#!forum/dataverse-community

**Comment by jggautier** [comment]
Reviving this general issue to record here (before I forget) that a Dataverse collection's "Featured" carousel can contain only its direct children collections (so not its grandchildren collections or great-grandchildren, etc.) and this might also be reconsidered.

For example, being able to display on Bob Dataverse collection's "Featured" carousel any collection within Bob Dataverse collection, even if it's a grand child or great grand child, is something the Harvard Dataverse Repository staff wonder would be beneficial. The staff are re-organizing sub-collections with a particular large collection on the Harvard Dataverse Repository and the re-organizing will mean that some sub-collections that were in the parent collection's "Featured" carousel will be removed from the carousel because they'll no longer be direct children of the parent collection.

**Comment by pdurbin** [comment]
> Although the organization of a dataverse with datasets and sub-dataverses may be hierarchical, we lack a way to create a view that represents this

@CCMumma there's some code at https://github.com/IQSS/miniverse/tree/master/dv_apps/metrics/templates/metrics/viz-tree and a comment at https://github.com/IQSS/dataverse/issues/5603#issuecomment-470993028 that explains where this viz of collections (but not datasets) below came from. Not sure if this helps. Please feel to create a fresh issue. I hear you. People want to see the tree, they want to know how collections are organized.

![54040476-79bdf180-4193-11e9-9769-fc4a143512ae](https://user-images.githubusercontent.com/21006/194193948-cd8f1013-4eef-40d6-bca2-6cc1be4389c9.png)

**Comment by DS-INRA** [comment]
Chould this get the label "UX & UI: Design" so the discussion of this feature doesn't get forgotten when porting on the SPA ? :grinning:

**Comment by DS-INRA** [comment]
Another suggestion to take into account in the rework, being able to sort the featured collections:
- https://github.com/IQSS/dataverse/issues/10703

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
