### ISSUE TITLE
Search: characters in (dataset names) return zero results

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2156]
Example:
 4.0 search doesn't like the "%" in this search:

População Estrangeira na Europa e no Mundo Nôvo (%) - 1870 - 2001

When I remove the "%", it has no problem searching....

**Comment by mheppler** [comment]
@sbarbosadataverse I am closing this issue, and consolidating it with other related issues in an old issue that I have retitled as _**Search: Accented characters, ampersands, negative numbers and other special characters #820**_.

If you have any further information about this bug or other "special character" related search issues, please add your comment there.
