### ISSUE TITLE
Delete files: in File---> edit, can't see track record of when a file was uploaded to determine which version to delete

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2157]
In a case where a user has uploaded new versions of files and they want to go back and delete

![ix45msfwcjny0hnj1wqilnjsxfqndmwree9dy8enocw](https://cloud.githubusercontent.com/assets/8322346/7596478/efb38c30-f8bb-11e4-826c-ec1971db5901.png)

**Comment by mheppler** [comment]
With the development of the new File Replace (#2290), the way files are deleted and replaced is changing, and the proposed UI mockup includes dates with previous versions.

Also, in [4.2](https://github.com/IQSS/dataverse/releases/tag/v4.2) upload and edit workflows were broken out into separate workflows, which should also clarify confusion.

Sending back to @sbarbosadataverse to review and close this issue, if she believes that it is no longer an issue or this feature is included and being properly tracked in the File Replace project.

**Comment by djbrooke** [comment]
Going to close this in favor of #2290. Please reopen if this is not covered by the mockup.
