### ISSUE TITLE
Versioning: "destroy version" option for superusers

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2159]
Gustavo asked me to create this ticket based on recent user interaction.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
