### ISSUE TITLE
Harvested Data: When going to a harvested dataset, should open in a new tab

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2161]
When a user goes to a harvested dataset, the link is opening in the same window, this should open in a new tab so their search on Dataverse hasn't been lost.

**Comment by scolapasta** [comment]
Wouldn't it be the same case, though, for local datasets? (Another related idea is a message informing the user they are leaving the dataverse site)

**Comment by mheppler** [comment]
@landreev added a message to the harvested result cards with his commit 6dbad79d01ccae99c26293dc8cb97d6dce3fed86.
![screen shot 2016-01-27 at 4 15 59 pm](https://cloud.githubusercontent.com/assets/687227/12628463/47378598-c511-11e5-9aa0-199d89cb6637.png)

**Comment by mheppler** [comment]
@djbrooke @landreev @kcondon This is a feature that was delivered in 4.5.
