### ISSUE TITLE
Dataverse Metadata Fields: Have Link to Metadata Appendix 

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2162]
In the General Information of a dataverse, within the Metadata Fields area, have a link to the Metadata Appendix section so users can easily learn which schemas are being used for each domain.

Link should open the Metadata Appendix in a new tab.

**Comment by bencomp** [comment]
May I suggest to rename the metadata blocks/schemas to something that explains their domain? I do support links to more information about each schema and field, but it would make the software more generic if using e.g. "School curriculum metadata" instead of "Graduate School of Design metadata".

**Comment by posixeleni** [comment]
@bencomp: apologies for the confusion we have some metadata blocks (such as the Graduate School of Design) that were created to support custom use cases we use to support in 3.6 (custom fields) and these should not be showing up for other installations or for the root level Dataverse. We have a ticket here to hide those custom non-standard metadata blocks and only show them for the specific Dataverses they were designed for (within the Harvard Dataverse) https://github.com/IQSS/dataverse/issues/2077

**Comment by pdurbin** [comment]
Hmm, I like the idea of linking to the appendix where metadata blocks are described BUT what about custom metadata blocks? They won't be described in the appendix. And we don't currently have a way to know (from the database) if a metadata block is shipped with Dataverse (and therefore listed in the appendix) or not.
