### ISSUE TITLE
Previous/Next navigation links in dev guide

### ISSUE THREAD

**Issue by terriko** [IQSS/dataverse#2163]
It would be great if there were previous/next links in the dev guide to make things easier for folk who want to read through from start to finish (or finish to start, I guess?)

**Comment by pdurbin** [comment]
@terriko and I have been [talking](http://irclogs.jackgrigg.com/irc.freenode.net/openhatch/2015-05-12) [about](http://irclogs.jackgrigg.com/irc.freenode.net/openhatch/2015-05-12) the dev guide which I've been working on in #912 and I prompted her to create this issue. I imagine this would be helpful to have in all guides but I'm not sure.

I haven't even looked but I assume Sphinx supports it. /cc @cchoirat

**Comment by pdurbin** [comment]
As part of #2895 I **manually** entered links at the bottom of Installation Guide pages like "Now that you have all the prerequisites in place, you can proceed to the Installation section." I didn't research if there's a better way. At some point I'll ask @cchoirat if she can suggest something.

**Comment by pdurbin** [comment]
I spoke with @cchoirat last week and she indicated that by default Sphinx has "previous" and "next" links but they were taken out for some reason. Here's what the Sphinx docs themselves look like:

![first_steps_with_sphinx_ _sphinx_1 3 7 _documentation_-_2016-02-29_09 56 02](https://cloud.githubusercontent.com/assets/21006/13398074/ba3211bc-deca-11e5-94d4-c2d4103764e5.png)

She suggested looking at "relations.html – two links to the previous and next documents" at http://www.sphinx-doc.org/en/stable/config.html

It should be controlled in https://github.com/IQSS/dataverse/blob/develop/doc/sphinx-guides/source/conf.py somewhere.

**Comment by pdurbin** [comment]
Implemented in 06bd186.

**Comment by pdurbin** [comment]
> She suggested looking at "relations.html – two links to the previous and next documents" at http://www.sphinx-doc.org/en/stable/config.html

If I add "relations.html" to the sidebar like this...

```
$ git diff source/conf.py
diff --git a/doc/sphinx-guides/source/conf.py b/doc/sphinx-guides/source/conf.py
index be167e4..7268338 100755
--- a/doc/sphinx-guides/source/conf.py
+++ b/doc/sphinx-guides/source/conf.py
@@ -240,7 +240,7 @@ html_last_updated_fmt = '%b %d, %Y'
 # Custom sidebar templates, maps document names to template names.
 #html_sidebars = {}
 #html_sidebars = {'sidebar': ['localtoc.html', 'sourcelink.html', 'searchbox.html']}
-html_sidebars = {'**': ['searchbox.html', 'sidebartoc.html']}
+html_sidebars = {'**': ['searchbox.html', 'sidebartoc.html', 'relations.html']}
```

... links to the previous and next pages appear in the sidebar, but they don't look so great:

![Screen Shot 2019-08-12 at 10 14 21 AM](https://user-images.githubusercontent.com/21006/62871726-05f7b600-bcea-11e9-8b1b-2b2192a216e1.png)

It would be nice to come up with a automated solution for "next" and "previous" links in the guides. The way I implemented this in the Dev Guide requires maintenance every time we add a page or reorganize pages.

**Comment by pdurbin** [comment]
I'm fixing this across all pages in the guides with this PR:

- #10942
