### ISSUE TITLE
Server error when accessing notifications

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2168]
Internal Server Error - An unexpected error was encountered, no more information is available.

I have a movie file of the steps to reproduce,  but can't attach that to github-not supported.

**Comment by sbarbosadataverse** [comment]
![error](https://cloud.githubusercontent.com/assets/8322346/7638207/2a1087a8-fa41-11e4-9ebd-2ec6bddaafbd.gif)

**Comment by scolapasta** [comment]
Reviewed with @eaquigley and could not reproduce.

**Comment by kcondon** [comment]
Many of these notifications issues were resolved. Not able to reproduce, closing.
