### ISSUE TITLE
Dataverse - "Save Search" Feature

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#2175]
Use Case 1:  A user has done a search and wants to be able to return to that search.

Rather than adding the results of a search to one's dataverse (see, ["Link Search"](https://docs.google.com/document/d/1dmxs4XIQkrn9QfP4Ih4wIbyARUyWFJflJk3y4W3nzXk/edit)), this feature would allow a user to run a search (on a term, or facets, or multiple Advanced Search terms), then save those search parameters to a location where they can easily return, and rerun the search, to find those results and any new/updated results, at a later time.

**Comment by pdurbin** [comment]
This feature suggestion reminds me of a nice "saved search" feature Twitter has: https://support.twitter.com/articles/96646-saving-searches

**Comment by scolapasta** [comment]
Because the URLs are bookmarkable now, it is possible to do this by simply making a bookmark in your browser. Of course we could consider replicating similar beahvior on the dataverse side.

**Comment by pdurbin** [comment]
Related: #2056

**Comment by mheppler** [comment]
Dusting this oldie but goodie off to close it, as there has been no additional requests for such a feature. A new issue can be opened if and when there is.
