### ISSUE TITLE
Set Required, Hidden & Optional Metadata Fields At the Template Level 

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#2177]
While setting up templates in 4.0 I discovered that some Dataverses (migrated from 3.6) have multiple templates, and in 3.6 the required, hidden and optional fields were set at the template level not the Dataverse-level.

However, in 4.0 you can only setup ONE set of required, hidden and optional metadata fields per Dataverse even if they have multiple templates. This makes it impossible for me to completely copy over the template settings certain Dataverses had in 3.6 (especially with PSI where they have 3-4 different templates for each of their 70+ Dataverses).

This feature request is to allow for setting which fields are required, hidden and optional at the template-level.

**Comment by bencomp** [comment]
Perhaps to not confuse people who have just been getting used to the new way of setting required, hidden and optional metadata fields, the current settings for a dataverse could be moved to a template that every dataverse has - the *Default template*?

**Comment by mheppler** [comment]
Related to #2164

**Comment by mheppler** [comment]
@chaudj commented on May 14, 2015 in #2164

> Tried creating different data set templates but it wont give any option to add and remove any meta- data fields.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
