### ISSUE TITLE
Update migration script to remove "null" string from notes

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#2179]
Related: #2075

**Comment by raprasad** [comment]
In ImportServiceBean.java, update processNotes

**Comment by raprasad** [comment]
moved to QA

**Comment by kcondon** [comment]
@raprasad I looked at this same dataset on v4.0.1 and null is still there.

**Comment by kcondon** [comment]
Discussed with Raman and Gustavo. This was for the script itself, not for existing data. This was verified by Raman, closing.
