### ISSUE TITLE
Worldmap - some type of check if service is 504, etc

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#2183]
WorldMap service is frequently down or times out:
- [ ] Provide functional test that can be called by nagios
  e.g. url on WorldMap that shows server availability
- [ ] Use functional test (or similar) to provide user-friendly message

(@scolapasta for evaluation of priority)
/cc @kcondon

**Comment by kcondon** [comment]
Also add server logging when it fails as a record.

**Comment by mheppler** [comment]
Closing as duplicate in favor of **Geoconnect: provide heartbeat link to allow service monitoring of geoconnect and worldmap #2251**.
