### ISSUE TITLE
Add Documentation About OpenScholar Dataverse Widgets

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#2184]
In the Dataverse section of the User Guides there is a placeholder for OpenScholar but this needs to be fleshed out more.

https://dataverse.harvard.edu/guides/user/dataverse-management.html?highlight=openscholar

Passing to @eaquigley to review how this should be written.

**Comment by eaquigley** [comment]
I wrote this before leaving on vacation so it should be there. @posixeleni please let me know if you don't see it.

On May 20, 2015, at 10:04 AM, Eleni Castro <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #2184<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_issues_2184&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=Y9aY3P6kFFpmMLaYYO_id08dS3gL1xWMQuI2CZ74PoI&m=tHPLQ8Nn1-PyxnNOdH9lsln74Wg26MtsifV-2RC2_k0&s=NJM7EocaEYKf10YwRQgIXYfz0lPbW_8AuZ78Y8B18rY&e=> to @eaquigley<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_eaquigley&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=Y9aY3P6kFFpmMLaYYO_id08dS3gL1xWMQuI2CZ74PoI&m=tHPLQ8Nn1-PyxnNOdH9lsln74Wg26MtsifV-2RC2_k0&s=xVIHCl7JrEZfWxrQBtS4MblFP1oKkN-nnXYzVHF0MdA&e=>.

**Comment by posixeleni** [comment]
@eaquigley if I go to: http://guides.dataverse.org/en/latest/user/dataverse-management.html#theme-widgets I can see that this documentation has been updated however it has not been updated in the guides that point from Harvard Dataverse: https://dataverse.harvard.edu/guides/user/dataverse-management.html#theme-widgets

@kcondon @pdurbin would either of you be able to comment on when it will be updated on this page? https://dataverse.harvard.edu/guides/user/dataverse-management.html

**Comment by eaquigley** [comment]
@posixeleni I am moving this ticket to 4.0.1 because that is when the change to how the guides are built will be done. Also, moving to this QA so that it can be tested.

**Comment by posixeleni** [comment]
:+1:
