### ISSUE TITLE
Expand Index & Search Within Files

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#2185]
A user came to me today during Dataverse Office Hours with a use case we don't currently support:

They have tabular files which we index the variables for but they also want users to be able to search for all the values in the file (not just variables).

From the user:

> The link below will demonstrate the functionality we want to replicate.
> http://140.247.119.225/mcz/

**Comment by pdurbin** [comment]
@posixeleni would the user be able to supply us with a sample tabular file we could test with? A file that can be made public (no restrictions) would be ideal.

**Comment by posixeleni** [comment]
@pdurbin yes I am going to get them to send us one

**Comment by wfarnum** [comment]
@posixeleni I will posted it to dataverse. Search for Pheidole for the data set of names.

**Comment by posixeleni** [comment]
Thanks @wfarnum !

@pdurbin you can access the data here: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/HMAFSD&version=DRAFT

**Comment by wfarnum** [comment]
@pdurbin would be possible to meet and discuss this project in person in the coming week?

**Comment by pdurbin** [comment]
@wfarnum do you mean at the Dataverse Community Meeting ( http://projects.iq.harvard.edu/dataverse-community-meeting )? I'll definitely be around!

That dataset at doi:10.7910/DVN/HMAFSD isn't published so I can't see it without giving myself special permission. Is there a public file I could look at?

**Comment by wfarnum** [comment]
Just got back from being sick for a week. Pheidole set is now published. We to be able to search the contents of the file. Thanks for your help.

**Comment by pdurbin** [comment]
@wfarnum sorry to hear you were sick! I just looked at http://dx.doi.org/10.7910/DVN/HMAFSD and it is indeed published. It sounds like you're all set so I guess we could close this issue (I'll let @posixeleni or @scolapasta or someone else decide) but I'd like to note that there is no special indexing of the contents of the "Dataverse Pheidole Data.tab" file in question. By this I mean that the system did not ingest the file as tabular (TSV support is coming in #2263) so the variables were not indexed. Searching on the file name or description will match. At a high level I **do** feel like we could do more to match the **content** of files but it's a largish project and I don't know if we want to keep this ticket open for that or someday create a new ticket or functional requirements document.

**Comment by pdurbin** [comment]
I'm not sure what this issue is about anymore. @wfarnum said thanks so we could close it as resolved. If someone out there thinks the contents of PDFs and whatnot should be searchable, we could create a new issue. Vote to close.

**Comment by djbrooke** [comment]
👍  to close.

**Comment by pdurbin** [comment]
> If someone out there thinks the contents of PDFs and whatnot should be searchable, we could create a new issue.

The contents of PDFs and other files are searchable these days thanks to pull request #5147 by @qqmyers for #5030. Docs here: http://guides.dataverse.org/en/4.11/installation/config.html#solrfulltextindexing

**Comment by pdurbin** [comment]
In my review of pull request #6080 I suggested that this issue could be closed ... oh! I see above that @djbrooke already gave closing a thumbs up. Closing!

**Comment by djbrooke** [comment]
@pdurbin Sorry, was only a few months in at that point and didn't think y'all would trust me to click the close button myself. :)

**Comment by pdurbin** [comment]
We trust you, we trust you. 😄
