### ISSUE TITLE
Install: Running make to generate install zip does not find schema.xml

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2188]
When running make to generate the installer .zip file, it complained that it could not located dvninstall/schema.xml. 

I was able to add this file manually to the right location and run it but wanted to report this issue for future fix.

**Comment by landreev** [comment]
The Makefile is fixed. Schema.xml should now be a part of the distribution. 
(Will look at #2234 too)

**Comment by kcondon** [comment]
Schema.xml is part of the distribution. Installation guide should be updated but this maybe an intermediate step to having the installer configure and start Solr?
