### ISSUE TITLE
File Upload: When uploading a new file, the most recent upload should show up at the top of the list, not the bottom

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2189]
Gary sent the following to support today:

after I dragged the file, it looked like nothing happened and in fact
the screen didn't change at all so far as I could tell.  i tried dragging
it again and it said that i had already uploaded it.  so then i looked down
and saw it at the bottom of the long list of files (off the bottom of the
screen).  the user shouldn't have to discover this; it should be
highlighted and moved to the front and center of things, so then the user
can add a description etc. let's fix this.

**Comment by eaquigley** [comment]
Passing to QA as we have updated the upload + edit files functionality to separate them and all files in a dataset don't show in the upload page.

**Comment by kcondon** [comment]
@eaquigley @scolapasta 
OK, most likely the new design will make issue go away but for the record, files are still added to the bottom of the add/edit files page if you are adding them one or two at a time. I'm closing unless people think otherwise.
