### ISSUE TITLE
File upload: Tar file upload does not automatically unpack like zip as in v3.6.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2195]
Not sure whether this was intentionally dropped or missed in the dev process but tar file currently do not automatically unpack as they did in v3.6

**Comment by pdurbin** [comment]
Unfortunately, the 4.0 User Guide is inaccurate. It says:

> "Compressed files in tar and zip format are unpacked automatically." -- http://guides.dataverse.org/en/4.0/user/dataset-management.html#compressed-files-tar-zip

**Comment by posixeleni** [comment]
can someone confirm that tar is expected to be supported in 4.0? If so @pdurbin the mention of tar should remain in the documentation and the bug should be fixed

**Comment by kcondon** [comment]
I honestly don't know whether the omission was intentional or not. I tested it and it is not working. This may have been a case of testing by ticket -there was a ticket for zip files and it was tested. No ticket for tar files, not tested, and was missed in the gap analysis of the feature list.

________________________________

**Comment by posixeleni** [comment]
In our guides, I clarified that we do not currently support tar and referenced this ticket. @kcondon when you QA this before you close this ticket would you please also make sure that someone has added in the documentation that tar is supported? Thanks!

**Comment by bencomp** [comment]
Possibly related: #1612

**Comment by mheppler** [comment]
In a Google Doc for [ingest requirements](https://docs.google.com/document/d/1pGCiH5oPfQD2V5wzGoz62M4pDElGHU50NKBioG2IT9c/edit), dated Nov '14 for the last edit, I found a requirement of "Automatically unpacks - mandatory (Delivered)" under the ZIP Files section. Whether or not that requirement was changed for one reason or another was not documented in that FRD however.

In a comment from @landreev on ticket #1175 dated Dec '14, he states:
> If there's more files in the zip archive than the limit, it is ingested as a single zip file, and the warning message ("too man files; the limit is ... blah ... upload a zip archive with fewer files if you want them ingested as individual datafiles...") is shown to the user.

Then there are the tickets #2055 and #2017 which debate "to zip or not to zip", the latter of which is still open, which probably makes this ticket a duplicate.

**Comment by kcondon** [comment]
This is not a duplicate because it involves unpacking files of .tar format rather than unpacking files of .zip format.
In v3.6.x we did both and the assumption is we still wanted that but it was overlooked.

________________________________

**Comment by pdurbin** [comment]
Here's how the tar upload feature was documented in DVN 3.6:

> "An alternative to selecting files individually is to first create an archive of files in .zip or .tar format and then select the appropriate “multiple files” Data Type when uploading your archive. The zip file or tarball will be unpacked so that the individual files will be added to the page." http://guides.dataverse.org/en/3.6.2/dataverse-user-main.html

**Comment by dfear0** [comment]
We need the option to KEEP .zip and .tar from unpacking automatically, which was there in the 3.x's.  Often users should download single files that keep all the components together in a folder, which .zip does. Our only workaround is to create dummy files, add files directly to the server, and rename them to bypass the interface.

**Comment by pdurbin** [comment]
@dfear0 this issue having to do with the "double zip" workaround is highly related to what you want, I believe: #3439.

**Comment by pdurbin** [comment]
Does anyone out there care if Dataverse supports upload of tarballs or not? We seem to be getting by fine right now with zip file upload. And I say this as a [Unix hacker](http://www.ru.j-npcs.org/usoft/WWW/LJ/Articles/unixtenets.html) who loves me some tarballs.

**Comment by dfear0** [comment]
HI Philip,
Johns Hopkins-based Data Conservancy<http://dataconservancy.github.io/dc-packaging-spec/> and the JHU Data Archive <http://archive.data.jhu.edu/> are working with a packaging tool that generates .tar files. We currently upload .zip files, but, not having technical reasons immediately at hand, it may be good to keep .tar upload options on the table if that flexibility will come into play in the integration of COS’s OSF platform and Dataverse, and some of the APIs that the Data Conservancy is developing with them that might ultimately flow into Dataverse, should that work out. That’s my top-of-head speculation at least, and I can point you to the people on our team who can better address that issue.


David Fearon, Ph.D.
Data Management Consultant
JHU Data Management Services
Johns Hopkins University
http://dms.data.jhu.edu/
(410) 516-0713

**Comment by oscardssmith** [comment]
why would we be closing this? Is it fixed?

**Comment by pdurbin** [comment]
@dfear0 thanks for your feedback! I removed my "vote to close" label. 😄 

I also added some new labels I'm experimenting with called [Help Wanted: Code](https://github.com/IQSS/dataverse/labels/Help%20Wanted%3A%20Code) and [Mentor: pdurbin](https://github.com/IQSS/dataverse/labels/Mentor%3A%20pdurbin). For more background on these, please see what I wrote at https://groups.google.com/d/msg/dataverse-dev/Pkces_MBqR8/4819N2tmBQAJ

@oscardssmith since there's a workaround of uploading using a zip file rather that a tarball, I changed this from "Type: Bug" to "Type: Suggestion". I think of this issue as implement a suggestion rather than fixing a bug. If you'd like to work on this one, please clear with with @djbrooke and I'm happy to mentor you. This one adds value to @dfear0 and probably others.

Oh, by the way, there's a "3.6 & 4.0 Feature Comparison" spreadsheet here if anyone is interested: https://docs.google.com/spreadsheets/d/1ftHM6E4b9Dft_AvA6KTzeklJyLguItz2_0hNAFL8-VM/edit?usp=sharing

**Comment by mankoff** [comment]
I'm adding a vote to keep tar (and tar.gz?) files as an upload option *with unpacking*. The reason being that it is easier to generate tar files and rewrite filenames internally than zip files. For example:

```
tar -zvcf upload.tar.gz --transform 's/foo/bar/' ./files/*
```

Let's me rename files from `foo` to `bar` in the uploaded data set without renaming on my computer. I find this useful. I have folders of model output with complicated names, but want to upload them to different datasets with the same name. tar supports this behavior.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
