### ISSUE TITLE
dataset page, appropriate pluralization for file count

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#2196]
![dropbox_test_-_root_dataverse](https://cloud.githubusercontent.com/assets/1036060/7778808/ffe05212-009c-11e5-93a1-550c00d95705.png)

**Comment by mheppler** [comment]
This is a bug related to 4.0.1 issues #1989.

**Comment by sekmiller** [comment]
Suggestion - That File number is not rendered if there are no files, since we already have the "There are no files in this dataset." displayed. Then we just have to distinguish between 1 and more than one.

**Comment by scolapasta** [comment]
Should be easy to do with the choice logic in the bundle.

**Comment by mheppler** [comment]
@raprasad fixed this in his commit 29195cfff2085f9b024d2cd4a6883772c2c815ab which is in 4.0.1.

Moving this ticket to 4.0.1 and sending it to QA.

**Comment by kcondon** [comment]
Works, closing.
