### ISSUE TITLE
File Downloads: Downloading a specific file results in internal server error.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2197]
See RT #216402. 

Is this part of the review files batch job?

**Comment by landreev** [comment]
The original RT ticket appears to have been resolved back in May. (by simply re-uploading the file). 
Hard or impossible to to tell what was wrong with the original file... but most likely, the upload went wrong during some instance of system instability. Of which we had a few during the first weeks of 4.0. 
Close this one?

**Comment by kcondon** [comment]
Closing
