### ISSUE TITLE
Licensing & Terms of Use: Add CC0 and Custom Terms of Use to Dataset

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#22]
---

Author Name: **Kevin Condon** (@kcondon)
Original Redmine Issue: 2963, https://redmine.hmdc.harvard.edu/issues/2963
Original Date: 2013-05-17

---

This was requested by Merce and Eleni, see RT #158870:

Yes, good point, it would be CC0 and CC-BY, which are the most standard
options offered in other data repositories.

From the technical side, we should plan this for v3.6 and decide where in
the study cataloging these licenses would appear and how the data depositor
would choose a license.

From the legal, policy side, I'll talk to some people in the Berkman
center/Law School to check if choosing one of these licenses is consistent
with the current DVN terms of use.

Merce

**Comment by sekmiller** [comment]
Basic functionality completed

**Comment by eaquigley** [comment]
@sekmiller We need to have a dataset be given the CC0 license as a default. Currently, when a user publishes a dataset without selecting anything, the tab looks like this:
![licenseeterms](https://cloud.githubusercontent.com/assets/5922904/5620601/783a3024-94fb-11e4-8b5d-dca49ee69249.png)

**Comment by eaquigley** [comment]
@kcondon here are the CC-0 and Terms of Use requirements from conversations with the Berkman Center:
- [ ] CC-0 can be used with restricted files
- [ ] CC-0 cannot be used with Terms of Use
- [ ] If a user has inputted Terms of Use, then the CC-0 license should be negated (if already selected)
- [ ] CC-0 only relates to the way the data is used after downloading not access to download

Let me know if you need other requirements.

**Comment by kcondon** [comment]
Not able to save anything/ additional info, CC0, selecting no to CC0 does not open TOU edit box. Passing back.

**Comment by sekmiller** [comment]
Editing should be working now....

**Comment by kcondon** [comment]
OK, did basic functional testing of forms and all works but for TOU additional info, citation requirements throws 500 error. Will open separate ticket.

Passing to Mike for UI review/ cleanup.

**Comment by kcondon** [comment]
Oh, the more comprehensive, consolidated requirements doc is here:
https://docs.google.com/document/d/1Rg0JTLTeF4seiDdoMDaiWR15WZcH5D7xOtvqTuA0mlI/edit

**Comment by pdurbin** [comment]
See also some comments at https://github.com/IQSS/dataverse/issues/805#issuecomment-70290922

**Comment by mheppler** [comment]
Manage
- [ ] Hide "View Collected Data" button if not enabled, or if not used by a dataset.
- [ ] Usage count not working.
- [ ] Not able to view collected data.

Create/Edit
- [ ] Wire up commented out edit help info text.
- [ ] Validation runs on empty Guestbook Name when you click Add Custom Question.
- [ ] Show empty Custom Question form by default, have Required selected by default, add "Select..." to Type dropdown to get around validation.
- [ ] Remove "Add Custom Question" button and just use "+" and "-" buttons next to questions.
- [ ] Sorry, I broke your Type dropdown.
- [ ] I guess I also broke the "Add/Remove" buttons too. Sorry.

View Guestbook
- [ ] Added new Edit button to the View popup, it isn't wired properly, brings you to empty edit form.

View Collected Data
- [ ] Can't get it to display.

Download
- [ ] Filled out popup form, no file.

General
- [ ] Add in all the success/error messages from #1277.
- [ ] Automatic log out of session expiration should forward to log in page.
- [ ] I saw a random weird state with the success message stuck on the page, and followed me to other, non-Guestbook pages.

**Comment by eaquigley** [comment]
Closing this ticket and moving all of @mheppler comments to #1411
