### ISSUE TITLE
Guides - Add machine name/host to hidden url or utility pg

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2200]
When troubleshooting in a multi web server environment, it is helpful to know which server the client is talking to without resorting to the time tested practice of viewing live server logs.

In the previous version, we displayed the machine name on the settings page. Something like that would be really useful.

**Comment by pdurbin** [comment]
@raprasad asked about this once and I pointed him to a commit I made in a branch: c32cd3e

**Comment by pdurbin** [comment]
@bencomp mentioned the DVN 3.6 system-wide settings page here: #1574

**Comment by pdurbin** [comment]
I added a list of possible places to show the hostname in the description of this issue and asked the dev team to add to the list.

**Comment by mcrosas** [comment]
I moved this issue to In Review, so we consider it for a release, and decide whether it needs first some design.

**Comment by pdurbin** [comment]
Related: #2805

**Comment by mheppler** [comment]
This may have been completed with the development related to #2805.

![screen shot 2016-09-19 at 1 57 03 pm](https://cloud.githubusercontent.com/assets/687227/18643097/91ce3fb0-7e71-11e6-8ce6-deaa108cebf1.png)

**Comment by kcondon** [comment]
Not resolved. See original request, the idea is to find out which machine a user is on at any time, not just when an error happens.

**Comment by pdurbin** [comment]
I propose that we make the scope of this issue quite small. We can simply document in the Admin Guide a tip to drop a file called `host.txt` into the proper directory of each Glassfish server (when there are multiple) so that when you visit a URL like https://dataverse.harvard.edu/host.txt you can see the content of the `host.txt` file, which can display as much or as little information about the Glassfish server as you like but at the very least something to identify it uniquely such as a hostname or an IP address.

**Comment by kcondon** [comment]
OK, so document what we're already doing then. Did you change the title of the ticket to be guides? Mike asked about closing this ticket earlier today and I was ok with it since our installation has a solution but documenting what we've done as a tip is a good idea.

**Comment by scolapasta** [comment]
While I think that the host.txt solution is a clever workaround, it does require these (easy) extra setup steps. What would still be a better, more robust solution is to fix the info/server api, which was meant to serve this solution, BUT only returns the user facing name (e..g. dataverse.harvard.edu).

**Comment by pdurbin** [comment]
https://dataverse.harvard.edu/api/info/server for example returns this:

```
{
  "status": "OK",
  "data": {
    "message": "dataverse.harvard.edu"
  }
}
```

What would it return instead?

**Comment by scolapasta** [comment]
The actual server (which as tried to say, was the purpose of adding this in the first place, but it's a bug that it just shows dataverse.harvard.edu.

So something like:

```
{
  "status": "OK",
  "data": {
    "message": "server-1.harvard.edu"
  }
}
```

**Comment by pdurbin** [comment]
Oh! I didn't realize it's a bug. Sure, I'd be happy for this issue to include fixing it. It's a somewhat useless endpoint right now because it just spits back at you the hostname you're accessing. All this said, @landreev was saying this morning at standup, however, AWS doesn't do any stickiness for the API because cookies aren't used, so we should still document the `host.txt` setup (easy!) as part of this issue. That way, if you're using an HTTP client that uses cookies, such a browser, you can tell what server you're on from the browser by looking at the `host.txt` file in your browser.

**Comment by scolapasta** [comment]
Good point on the new load balancing style... that actually (at least for anyone using a setup like Harvard dataverse) make the end point useless - even if it gave a specific server, you have no guarantee that this is what you'd hit on any other call.

**Comment by pameyer** [comment]
What about adding a HTTP header to the response? Aka - `X-Dataverse-Application-Server: server-1.harvard.edu` ?  Should work for clients with and without browsers.

**Comment by pdurbin** [comment]
@pameyer for which requests? All HTTP requests? I'm not criticizing; I'm just trying to understand.

Personally, as I mentioned earlier, I'm in favor of at least documenting the `host.txt` solution. It's practical and reliable and has been used by Harvard Dataverse in production for a while. It works and solves the issue.

Let's make a pull request for that. We can increase the scope later if we really feel like it.

**Comment by scolapasta** [comment]
I'm ok with documenting the workaround as long as we make it's obvious that we prefer a better solution and it will eventually be deprecated. 

My issue with the workaround is that's it's not reliable; without checking we won't know if an installation actually implemented, or implemented it correctly. With a code way,  we can know for sure, depending on which version they are running.

**Comment by pdurbin** [comment]
Meh, I think there are only two or three installations of Dataverse that even use multiple Glassfish servers. And it shouldn't really matter to us (IQSS) if this or that installation uses the `hosts.txt` trick. It's really up to them and their support departments and end users. By reliable I meant that it works every time.

**Comment by djbrooke** [comment]
- For this issue, we'll provide documentation changes of the existing hosts.txt
- We won't handle the broken server API endpoint at this time
