### ISSUE TITLE
Update CONTRIBUTING.md to explain feature request process and what a Functional Requirements Document is

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#2203]
We plan to update https://github.com/IQSS/dataverse/blob/master/CONTRIBUTING.md to explain (among other things) what a Functional Requirements Document (FRD) is and we may attach the following image (or similar) in the CONTRIBUTING.md doc:

![feature-request](https://cloud.githubusercontent.com/assets/21006/7837273/1741347a-0454-11e5-9d74-6f582dee3a1d.png)

**Comment by bencomp** [comment]
Sounds great! :+1:

**Comment by pdurbin** [comment]
If we're going to tweak CONTRIBUTING.md a bit we might consider taking some inspiration from https://github.com/contribute-md/contribute-md-template/blob/master/contribute.md from http://contribute.md

Hat tip to @prologic for mentioning this at https://github.com/circuits/circuits/issues/14#issuecomment-107016175

**Comment by prologic** [comment]
Haha no worries :) It seems like a *useful* place to start! Funny thing s we've always had this piee of [documentation](http://circuits.readthedocs.org/en/latest/dev/contributing.html); just not int he form of a ``CONTRIBUTING.md`` :)

**Comment by eaquigley** [comment]
updated in 4.0.2 branch: https://github.com/IQSS/dataverse/blob/4.0.2/CONTRIBUTING.md Passing to QA.

**Comment by bencomp** [comment]
Looks good to me.

**Comment by dliburd** [comment]
Verified: infographic does appear in https://github.com/IQSS/dataverse/blob/4.0.2/CONTRIBUTING.md.
