### ISSUE TITLE
Requesting Access to (multiple) restricted files: allow to request access to all files simultaneously

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2205]
Now, results in multiple emails to dataverse admin,one for each file request.

**Comment by eaquigley** [comment]
Things to add into Dataverse:

[ ] Add a way to have users request access to multiple files at one time
[ ] Only send one email to a dataverse admin for a single user requesting access to multiple files

**Comment by mheppler** [comment]
Related to/duplicate of #1476 #639 #1988 #1951 and probably a few more that involve files and checkboxes and "select all" on the dataset.

**Comment by eaquigley** [comment]
Implemented by @sekmiller in 4.2. Passing to QA.

**Comment by kcondon** [comment]
OK, works, one email. Closing.
