### ISSUE TITLE
Remove all No Records Found Displaying in the UI

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2208]
We need to remove anywhere in the UI that "No Records Found" is displayed.

**Comment by mheppler** [comment]
- [ ] search-include-fragment (empty dataverse)

**Comment by mheppler** [comment]
Added "> 0" render to resultsTable on search-include-fragment, to keep "No records founds" from displaying in empty dataverses/search results.

**Comment by kcondon** [comment]
OK, spoke with Mike, it was only for the search fragment and the no results message was replaced by a custom message:
There are no dataverses, datasets, or files that match your search. Please try a new search by using other or broader terms. You can also check out the search guide for tips.

Closing
