### ISSUE TITLE
Sign Up Page: Add text about having a dataverse account

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2209]
Add text to the sign up page that tells a user the benefits of having a dataverse account.

**Comment by eaquigley** [comment]
Above the user name field, add in the following,
"Why have a Dataverse account? To create your own dataverse and customize it, add datasets, and request access to restricted files, if available."

@mcrosas does that sound good or should there be more in that little blurb?

**Comment by mcrosas** [comment]
looks good, perhaps a small change:

"Why have a Dataverse account? To create your own dataverse and customize it, add datasets, or request access to restricted files."

**Comment by eaquigley** [comment]
Looks good to me @mcrosas  Passing to 4.0.3 for this to be implemented.

**Comment by mheppler** [comment]
Added info help message to backing bean for the Dataverse account Sign Up page.

**Comment by mheppler** [comment]
![screen shot 2015-07-20 at 11 40 50 am](https://cloud.githubusercontent.com/assets/687227/8779978/384ee478-2ed4-11e5-8c4c-400ee005a045.png)

**Comment by kcondon** [comment]
Text is present, closing.
