### ISSUE TITLE
Create Documentation for Superusers in User Guide

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#2211]
@pdurbin indicated that the documentation from Super Users needs to be updated for 4.0 and this ticket is a placeholder for us to update this page:

https://github.com/IQSS/dataverse/edit/4.0.1/doc/sphinx-guides/source/user/super-user.rst

In 3.6 Super Users were able to do many things in the UI so @scolapasta there are some features we  need your help figuring out what we can currently support in 4.0 for super users in the UI and what will be coming down the road
- Harvesting
- Bulk Upload
- Web Analytics?

**Comment by pdurbin** [comment]
I just wanted to note that @mcrosas and I seem to prefer "superuser" (no dash) over "super-user". I assume this extends to "Superuser" over "Super User."

**Comment by posixeleni** [comment]
@pdurbin please feel free to make these changes in the file

**Comment by bencomp** [comment]
So this is not necessarily related to the [Administration documentation](https://github.com/IQSS/dataverse/blob/4.0.1/doc/sphinx-guides/source/installation/administration.rst)? My role in 3.6 is both information manager ("administrator") and superuser, so to me Superuser Action and Administration are related.

**Comment by pdurbin** [comment]
As I (mentioned yesterday](http://irclog.iq.harvard.edu/dataverse/2015-05-28#i_20253) products such as RHEL have separate guides for installation and administration:

- [Installation Guide](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/index.html)
- [System Administrator's Guide](https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/index.html)

As @bencomp mentioned, often in practice the same individual would be reading these guides. These are people who have the ability to make themselves a superuser and make raw edits to the databases as necessary.

45f13cc is where I started a new "Administration" page under the Installation Guide but I'm really not sure how best to organize this. In some ways a separate guide makes sense to me. I'd love to hear thoughts from @eaquigley @posixeleni @sbarbosadataverse and @kcondon on where best to put this information about the care and feeding of a Dataverse installation.

**Comment by posixeleni** [comment]
@pdurbin @bencomp to clarify this Super User documentation is meant for Administrators of an entire Dataverse installation for **post-installation** and would be for features a Super User (Aka Super Admin) would be able to do in the **Dataverse GUI** (which we use to have features for in the 3.6 User Guides).

**Comment by pdurbin** [comment]
@posixeleni where should we document SQL scripts that people like @bencomp or @kcondon will need to run until a GUI can be built? I mean for things like deleting an API token: http://guides.dataverse.org/en/next/installation/administration.html#deleting-an-api-token

**Comment by posixeleni** [comment]
@pdurbin If it's post-installation this can't be in the Installation guide, right? Nor in the API Guide? So would have to be in this section of the User guide, I suppose, with a caveat that this needs to be done outside of the GUI for now.

**Comment by pdurbin** [comment]
I just wanted to mention that as part of my pull request at #2895 I mention superuser accounts at http://guides.dataverse.org/en/2884-install-guide-reorg/installation/config.html#root-dataverse-configuration but assuming that gets merged in the next steps could be:

- rename user/super-user.rst to user/superuser.rst (take out the space)
- write more at user/superuser.rst
- link to user/superuser.rst the "config" page above

**Comment by kcondon** [comment]
@posixeleni @pdurbin Mention in Installation guide noted but I think Eleni's essential request remains open: add info to User Guide on what a Super User is and what things they can do and how to promote/revoke such permission.

**Comment by pdurbin** [comment]
Yes, agreed. User Guide territory.

**Comment by posixeleni** [comment]
Who would have the most knowledge on our team as to what a super user can
do in the UI and with scripts?

**Comment by mheppler** [comment]
In 4.5 we the [Admin Guide](http://guides.dataverse.org/en/4.5/admin/index.html) to the Dataverse Guides.

**Comment by mheppler** [comment]
Placeholder super-user pg removed from the guides. ffa76b46d606b1a79ddc4e215c57c5c4924f2e16

**Comment by pdurbin** [comment]
@mheppler again, I'm not a fan of the dash: https://github.com/IQSS/dataverse/issues/2211#issuecomment-106351496 . That's why I removed the page ( ffa76b4 ). Plus, it was basically empty. These day we have a new "Admin Guide" too at http://guides.dataverse.org/en/4.5/admin which is probably a better place for it than the User Guide.

**Comment by mheppler** [comment]
There are additional issues that track the original requirements outlined in this issue.

- Harvesting #3262 (Closed)
- Bulk Upload #2204
- Web Analytics? #3112

**Comment by pdurbin** [comment]
For web analytics, Pwiki support just got merged into 4.5.1 via pull request #3374. And we've had Google Analytics support since 4.0 of course.

**Comment by pdurbin** [comment]
Since as @mheppler points out at https://github.com/IQSS/dataverse/issues/2211#issuecomment-250554588 that there are other issues tracking future possibilities, I'm closing this issue.

**Comment by kcondon** [comment]
@pdurbin, the tickets Mike points out do not address Eleni's initial request: document what the Super User can actually do, the scope of their powers:

[Eleni]
 to clarify this Super User documentation is meant for Administrators of an entire Dataverse repository for post-installation and would be for features a Super User (Aka Super Admin) would be able to do in the Dataverse GUI (which we use to have features for in the 3.6 User Guides).
[Eleni]
Who would have the most knowledge on our team as to what a super user can
do in the UI and with scripts?

**Comment by kcondon** [comment]
@pdurbin @dlmurphy So we can link this ticket to that pull request then since #3614 is not specifically about the above issue.

**Comment by pdurbin** [comment]
@kcondon sure I just added the magic "connect to" syntax over at pull request #3877.

**Comment by dlmurphy** [comment]
Just spoke with @scolapasta about changing the name of the "Admin Guide" to "Superuser Guide", as that guide is really more about what Superusers can accomplish rather than "admins", and the use of the term "admin" was confusing people. 

In order to solve that problem and address the ideas raised in this issue, I'd like to do the following:

- [ ] Rename "Admin Guide" to "Superuser Guide"

- [ ] Rewrite the intro on the Admin Guide's index to explain what a superuser is.

- [ ] Find a place in the User Guide to briefly explain what a Superuser is, what they can do, and how to become one.

P.S. It's worth noting that confusion over the terms "admin" and "superuser" can also be addressed by adding them to a hypothetical future glossary page, proposed in #4274 .

**Comment by pdurbin** [comment]
@dlmurphy I am so so happy to read this comment. Thank you!!

**Comment by pdurbin** [comment]
There's plenty of content for superusers in the guides. Closing.
