### ISSUE TITLE
Dataset Page: Contact Metadata Field link to Contact Form

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2213]
Currently the contact email metadata form displays, "Use email button above to contact". We should figure out how to have this dynamic field work as a link to open the contact form found behind the email button at the top of the dataset page.

**Comment by mheppler** [comment]
This is related to a few existing tickets.
- Dataset Metadata - Improve display of compound fields in metadata tab #1625
- Dataset Metadata - Contact "[Email in Contact button above]" #1923
