### ISSUE TITLE
Files: Quick Viewers for Common File Extensions

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2214]
We already have a preview for image files but we should investigate adding more quick viewers for common file extensions such as:
- [ ] PDF
- [ ] data
- [ ] documents
- [ ] gif

By default, maybe these could show the first 100 lines of the file.

Suggestion from @thegaryking

**Comment by raprasad** [comment]
For data, grab first 10 to 50 lines for:
 - [ ] .csv
 - [ ] .tab
 - [ ] .xls
 - [ ] .xlsx

**Comment by mheppler** [comment]
- Feedback: People want to understand contents of the file beyond what we’re showing. Want to know more about what’s in it before downloading it. What is the quality of the file? E.G. percentage of missing variables in a tab file.

[Recommended by the UX Team](https://docs.google.com/document/d/1mNNRqRqIW92LXock332sIA-uXh-2agOpoyLLLKwXUA0/edit) based upon user feedback in usability testing of 4.6.

**Comment by raprasad** [comment]
re: @mheppler comment.  Are there specific stats?

- rp reference: getting missing data via pandas
   - http://stackoverflow.com/questions/22257527/how-do-i-get-a-summary-count-of-missing-nan-data-by-column-in-pandas
   - fyi: metrics app can calculate this, save it to the db, and send it over via API

**Comment by pdurbin** [comment]
The "Visualize + Analyze Contents of Files" idea from #1203 is related.

**Comment by djbrooke** [comment]
Hi @MINGEIN - this is not being worked on right now. To see what we're working on right now, check out https://waffle.io/iqss/dataverse and check out what's in the Next Sprint, Development, Code Review, and QA columns. These are the various stages our work process and anything in one of those columns is being worked on by the development team (or, in the case of Next Sprint, will soon be worked on).

If you're working with tabular data, one thing that will be of interest is that the last release (https://github.com/IQSS/dataverse/releases/tag/v4.8.6) provides the ability to integrate with Data Explorer, which we'll soon add to the Harvard Dataverse installation. If you're using Harvard Dataverse, this is an additional exploration tool that will soon be available for tabular data. If you're using a different installation, the administrators could choose to install it as an option.

**Comment by pdurbin** [comment]
This issue of having a "preview" for files like PDFs, etc. came up a lot at last week's Dataverse community meeting. There's a even older issue at #1203 that's quite similar.

Mahsa from http://irclog.iq.harvard.edu/dataverse/2018-06-11 just pointed me to an interesting line from https://docs.seek4science.org/tech/install.html which says, "SEEK uses the soffice service provided by LibreOffice to convert various document formats to PDF and Text - to allow them to be viewed in a web browser, and to make them indexable to the search." The point is that we may not need to reinvent the wheel when it comes to building this feature.

**Comment by TaniaSchlatter** [comment]
There is a use case for astronomy researchers being able to deposit and preview HTML files and images, "view in browser" functionality. Researchers want to host interactive figures on Dataverse as well as with the journal the figures are published in:

"need to host an html webpage for the figure itself, but would also need URLs for the individual png files which go into the interactive figure (of which there are ~ thousand). Add the pngs to the Dataverse regardless (so they are preserved, along with all the tables) but would love to have a stable place (with a doi) to host the figures as a data product in themselves."

**Comment by djbrooke** [comment]
Will close this issue. We are adding common file types preview support in #6210. We (or the community) will add additional previews as individual external tools or preview modes for existing external tools.
