### ISSUE TITLE
Dataset Description Truncation: Expand (wasted whitespace)

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2215]
Now that we have real data in dataverse, we can see that 200 characters is too small for truncated descriptions on the browse cards. We should play around with the abbreviate method from Omnifaces to see what looks best so there isn't a lot of white space left over in the line of the card.

Here is where you can see some wasted whitespace:

![harvard_dataverse_-_2015-05-28_14 40 37](https://cloud.githubusercontent.com/assets/21006/7868109/c6d6918e-0547-11e5-8938-cc203e3383ba.png)

**Comment by eaquigley** [comment]
I'd like us to try out 300-350 characters and see how it looks with descriptions and if that fills out the white space we see a lot of. 

Passing to @pdurbin to take a look at.

**Comment by pdurbin** [comment]
After discussing this with @mheppler (who talked to @eaquigley ) we've decided to try 280 characters which I changed in 8e6f8cf

The thinking is that most users may be seeing a width of 1170px or so. Passing to QA.

**Comment by dliburd** [comment]
Verified: Dataset descriptions truncated at 280 characters.

**Comment by pdurbin** [comment]
@dliburd as we discussed, can you please verify the amount of wasted whitespace and attach a screenshot if necessary? Thanks.

**Comment by pdurbin** [comment]
@dliburd @eaquigley @mheppler I think it would be best to copy and paste the original idea from @thegaryking which was this:

"on cards that list datasets, we have a snippet of text summarizing the description.  but the cutoff to the text we'll show before "..." means that the 2nd half of the second line of every card is whitespace.  why don't we make the cutoff such that we use the rest of that line."

As @mheppler and I have discussed, I **think** we need way to **dynamically** determine how much space we can use to avoid wasted whitespace but I'm not sure technically how to accomplish this. We'd have to look into it more.

**Comment by dliburd** [comment]
@pdurbin @mheppler @eaquigley 

I don’t know how you would make the truncation dynamic but I did a random sampling of character count per a line when the Dataverse is viewed at 940px wide. I’ve gotten between 115 and 125 characters per a line. I estimate that 120 characters per a line might be enough. Maybe we should try 350 characters for three lines of descriptions and the added ellipses.

**Comment by pdurbin** [comment]
@dliburd sure changing to 350 characters is easy and I just did so in dcece97

We also could make it configurable rather than hard coding it, if that's of interest.

Passing to QA. dvn-build is on v. 4.1 build 40 right now so you'll need a newer build than that to see the change.

**Comment by dliburd** [comment]
![untitled-1](https://cloud.githubusercontent.com/assets/11178866/8731040/aff0f6ac-2bc2-11e5-8b61-50d4b11f7fe0.jpg)
Here is the screen shot of what I'm getting. The Dataverse is being viewed at 940px wide.

**Comment by pdurbin** [comment]
@dliburd thanks. I see what you mean. And you're testing with the 280 characters version since dvn-build is still at v. 4.1 build 40. I'm giving this to @mheppler because I'm just changing the character count to what he and you are telling me anyway.

**Comment by pdurbin** [comment]
@scolapasta I'm giving this ticket to you to decide what to do with it.

**Comment by scolapasta** [comment]
discussed with @eaquigley, let's just switch it back to 280.

**Comment by pdurbin** [comment]
@scolapasta ok, back to 280 in 4d50349 . I don't like how the screenshot looks in https://github.com/IQSS/dataverse/issues/2215#issuecomment-122036214 (lots of wasted whitespace) but perhaps @dliburd is using a screensize that isn't representative. Passing to QA.

**Comment by dliburd** [comment]
Verified: 280 character truncation works as design when viewed at 1170px wide.
