### ISSUE TITLE
File Ingest: File type identification relies on browser identification, sometimes misidentifies type and fails ingest.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2217]
We have found an issue with file type identification that causes tabular ingest, namely stata files, to fail.

This was found in on my machine with FF only but also found in a user report: 
https://help.hmdc.harvard.edu/Ticket/Display.html?id=215169

Turns out files with extension .dta were being misidentified by some browsers as stata13 and dataverse was trusting this id to process the files. In both cases, the type was wrong: 1 was stata12, 1 was a tab file. Resulted in ingest failure.

**Comment by landreev** [comment]
This issue doesn't have a milestone; but I believe I have a (simple) fix, so I'm moving it into QA. 
The code fix has been checked into the 4.0.1 branch.

**Comment by mcrosas** [comment]
Added milestone 4.0.1

**Comment by landreev** [comment]
Also, just to document it here: the RT issue 215169 appears to be unrelated. Their files are real Stata 13 files. I'm looking into that separately.

**Comment by kcondon** [comment]
Was able to ingest both Stata12 and Stata13 files without error. Closing.
