### ISSUE TITLE
Write-Up A Preservation Policy For Harvard Dataverse

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#2220]
In 3.6 we use to document how the Harvard Dataverse handled preservation in different places: 
- http://projects.iq.harvard.edu/thedata_new2/book/data-backup-preservation-terms
- http://projects.iq.harvard.edu/thedata_new2/book/faq-using-harvard-dataverse-network

However for 4.0 we should make this information more formally available in a Preservation Policy document that would be hosted on Dataverse.org under **Best Practices > Harvard Policies**. This will be helpful for when we want to apply for the Data Seal of Approval http://datasealofapproval.org/en/ to become a trusted data repository

Example of high-level preservation policy page: https://purr.purdue.edu/legal/digitalpreservation and more detailed: https://purr.purdue.edu/legal/preservation-support-policy

Before publishing this policy will have @mcrosas, developers (file-handling) and curation team review for accuracy. I also think it would be a good idea to have it reviewed by Berkman in case there may be any legal implications for such a policy.

**Comment by pdurbin** [comment]
Right, http://libguides.mit.edu/ssds/hmdc/dvn_deposit for example, currently links to http://thedata.org/data-backup-preservation-terms which doesn't exist anymore.

(There are a number of other links on that page that that we should redirect to their new homes as well.)

**Comment by bencomp** [comment]
Please know that DSA (or any other standard for TDRs) applies to an organization, not just a system. If we host a Dataverse installation, we won't instantly get the DSA because IQSS has a certified installation. What I'm trying to say is that your documentation should make clear that your policies apply only to the IQSS Dataverse service, not the system in itself.

**Comment by posixeleni** [comment]
@bencomp yes as you mentioned this will be very clear that it **only applies to the Harvard installation**  (this will not be in the general Dataverse release documentation) since it will be only in our Harvard policies documentation. But other installations are free to use this as a model or an example of how preservation can be done.

**Comment by posixeleni** [comment]
draft is here for internal review first: https://docs.google.com/document/d/19BWWX2Mo5TYTPilMq3QgtkLUueezmEKfG5zUzJRgHt4/edit?usp=sharing

**Comment by posixeleni** [comment]
@eaquigley if this document is approved by @mcrosas would you please put this on dataverse.org under Harvard Policies? Re-assigning to you since I will be out.

**Comment by eaquigley** [comment]
done in a commit in the dataverse.org repo (https://github.com/IQSS/dataverse.org/commit/f300c7b08bb8299f51e9b085ada03567fcd7298c) and can be found here https://github.com/IQSS/dataverse.org/blob/master/docs/best_practices/source/harvard-policies/harvard-preservation-policy.rst 

Passing to QA

**Comment by sbarbosadataverse** [comment]
@eaquigley  it's not under http://best-practices.dataverse.org/harvard-policies/
yet....?

**Comment by eaquigley** [comment]
I think a build needs to be done dataverse.org (hi @pdurbin)

**Comment by pdurbin** [comment]
Oh noes! So stormy!
![dashboard_ jenkins _-_2015-07-16_16 45 08](https://cloud.githubusercontent.com/assets/21006/8734747/112b63b4-2bda-11e5-8e09-66bca652f9b9.png)

**Comment by pdurbin** [comment]
Ok, build fixed. Now there's http://best-practices.dataverse.org/harvard-policies/harvard-preservation-policy.html and hopefully whatever else you might need to look at.

**Comment by eaquigley** [comment]
@sbarbosadataverse please test again.

**Comment by sbarbosadataverse** [comment]
looks good
