### ISSUE TITLE
Harvested Files - Several with 0 bytes 

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#2221]
Potential error.  May be with source data

![harvard_dataverse](https://cloud.githubusercontent.com/assets/1036060/7885218/a18fd58a-05f0-11e5-96bb-9d256342223a.png)

**Comment by scolapasta** [comment]
Also md5.

Since these are harvested, we don't have this info, so we probably should hide this on the card.

**Comment by mheppler** [comment]
Noticed on [production](https://dataverse.harvard.edu/?q=&fq0=fileTypeGroupFacet%3A%22unknown%22&sort=dateSort&order=desc&page=8293&types=files) that a blank MD5 is also showing up for files that are local.

<img width="708" alt="screen shot 2016-02-05 at 6 13 14 pm" src="https://cloud.githubusercontent.com/assets/687227/12861840/3674c30e-cc34-11e5-83f9-ff3180667ce1.png">

**Comment by mheppler** [comment]
Added render logic to hide empty metadata fields for harvested files in the dataverse result cards.

**Comment by mheppler** [comment]
@kcondon - This was not tested locally, as I was not able to set up my local environment with harvested files.

**Comment by mheppler** [comment]
Deleted old branch, created ["2221-new-harvested-file-cards"](https://github.com/IQSS/dataverse/tree/2221-new-harvested-file-cards) branch and recommitted change to search-include-fragment due to 4.3 development code somehow getting mixed in.

**Comment by landreev** [comment]
OK, pushed my fix (for the broken dataset links in harvested *file* cards). 
Git made me do a merge in the process... I seriously hope I didn't mess up this branch in the process. 
@mheppler 
@kcondon 
Odum files are still showing as "unpublished". This is NOT a code error. It is something we fixed in the database - but we need to reindex all Odum datasets for it to take effect.

**Comment by mheppler** [comment]
Just did a double-check on the latest version of search-include-fragment in this branch, and it looks like my code is still in there.
