### ISSUE TITLE
Build process: Change war file name to be only dataverse.war rather than dataverse-4.0.1.war

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2223]
Build process: Change war file name to be only dataverse.war rather than dataverse.4.0.1.war

**Comment by landreev** [comment]
I'm confused. I'm pretty sure we agreed to keep the version number in the war file name. 
I thought this was the ticket related to how the installer was looking for the war file, and where the version number was specified, and all that... And I spent most of the day today working on it. OK, that was #2165. 
OK, let's just close this one. I don't think anybody really wants to rename the war file at this point. It actually makes things cleaner; can potentially prevent from deploying a wrong version of the war file, etc.

**Comment by landreev** [comment]
(that said, if this ticket was about renaming the war file "dataverse.war" in the installer zip bundle - that was done, a while ago)

**Comment by kcondon** [comment]
Closing.
