### ISSUE TITLE
Delete File: Success message for deleting file before save needs spaces between file names.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2224]
Success message for deleting file, before save needs spaces between file names:
 Success! – Files images.jpgmuench2002.fitsharris_s1635_spss.tab will be permanently deleted from this version of this dataset once you click on the Save Changes button.

**Comment by mheppler** [comment]
Added commas and quotation marks to the success message for delete/restrict actions on Edit Dataset Files pg.

**Comment by scolapasta** [comment]
Actually it turns out there's an even earlier issue, #2206 which mentions the space, but is also more general about the display. So I suggest we close this issue as a duplicate of that one.
