### ISSUE TITLE
Files Permissions Page: Add User Email Address to Table

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2228]
Requested by users so they are able to contact the users who request access to restricted files.

Fix would be to insert an email address column in the table on the files permission table.

![filerequestissuefix](https://cloud.githubusercontent.com/assets/5922904/7922365/b1079efe-0879-11e5-8cb1-5dbf67488b85.png)

**Comment by posixeleni** [comment]
:+1:

**Comment by mheppler** [comment]
Should the user email display also be expanded to the dataverse/dataset permissions? @mcrosas @scolapasta @eaquigley @posixeleni -- thoughts?

![screen shot 2015-06-02 at 11 42 08 am](https://cloud.githubusercontent.com/assets/687227/7940024/436d28ca-091c-11e5-8193-bf4c08bead9d.png)

**Comment by mheppler** [comment]
Added email field to the permissions-manage-files Users/Groups tables for requests and access.

**Comment by mcrosas** [comment]
I think @sbarbosadataverse and other dataverse admins would find this very useful. We discussed the privacy concerns, but perhaps once you've added a member  (contributor, admin or other) in your dataverse/dataset, it is reasonable to show the email address.

**Comment by mheppler** [comment]
Original task outlined in the ticket is completed. Passing to @scolapasta to determine if anything else needs to be done with the dataverse/dataset permissions page.

**Comment by pdurbin** [comment]
A 500 error is thrown when the role assignee is a group: https://github.com/IQSS/dataverse/commit/21d612b50350768e5fd973c4eea93c8205682b21#commitcomment-11483661

**Comment by mheppler** [comment]
Added "!empty" render logic to the email values on the permissions-manage-files Users/Groups tables for requests and access. 423556fb3501a8f80e7c1dab8c54c7f7d6e7c629

**Comment by mheppler** [comment]
Removed email values on the permissions-manage-files Users/Groups access table.

This should fix the 500 error associated with groups that have file access, that @pdurbin reported. Passing to QA.

**Comment by kcondon** [comment]
This works fine for individual users. Have not yet tested with groups, need some pointers from @pdurbin since am not able to assign explicit groups file perms in UI.

**Comment by pdurbin** [comment]
Try with an IP Group:

scripts/search/tests/ipgroup-add

**Comment by kcondon** [comment]
This works now, closing.
