### ISSUE TITLE
Identify unzipped shapefile for Worldmap use

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#2230]
Can we take the pieces of shapefile and allow mapping?

See: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/28674

**Comment by raprasad** [comment]
for the future...

**Comment by djbrooke** [comment]
Closing this, as I'm not sure what it's about and we have tabular mapping for file-level content and dataset explore for any explorations working across multiple files.
