### ISSUE TITLE
Guides: Solr config should come from installer rather than GitHub

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#2234]
http://guides.dataverse.org/en/4.0/installation/prerequisites.html#solr says to get the Solr schema.xml based from https://github.com/IQSS/dataverse/raw/master/conf/solr/4.6.0/schema.xml but really it should come from https://github.com/IQSS/dataverse/releases/download/4.0/dvinstall.zip

Related: https://help.hmdc.harvard.edu/Ticket/Display.html?id=216678 #2188 #1167

**Comment by landreev** [comment]
@pdurbin - the schema file is now part of the zip bundle. 
But how do you want to handle the installation? - 
a) modify the doc above, to say "copy schema.xml from the installer directory..." 
or
b) modify the installer, to ask the user where Solr is installed, and copy it there automatically? (if it's running on a different host, it would still have to tell them - "ok, copy this schema.xml into the Solr directory on your Solr host..."

**Comment by pdurbin** [comment]
@landreev hmm, maybe it **would** be good if the installer at least mentioned Solr. So yeah, perhaps it could prompt for a hostname at least.

**Comment by pdurbin** [comment]
> a) modify the doc above, to say "copy schema.xml from the installer directory..."

This is the approach I went with in my pull request at #2895

The change can be previewed at http://guides.dataverse.org/en/2884-install-guide-reorg/installation/prerequisites.html#installing-solr

Passing to QA.

**Comment by kcondon** [comment]
Looks good, closing.
