### ISSUE TITLE
Dataset Metadata: Have Contributor Appear as an Above the tabs Field

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2235]
Brought up during IASSIST. Move Contributor to also be one of the fields that is exposed in the box with description and subject. This way it is easy to see who all has been part of the creation of the dataset.

We should also look at Credit Taxonomy (http://credit.casrai.org) for this controlled vocabulary. Credit to @thevandalen for the link!

**Comment by posixeleni** [comment]
We use the DataCite controlled vocabulary for Contributors so we can compare with Casrai's list to see what is missing.

**Comment by pdurbin** [comment]
This reminds me of the composable dataset page @pameyer wants. I don't believe there's an issue for it yet though.

**Comment by jggautier** [comment]
> We should also look at Credit Taxonomy (http://credit.casrai.org) for this controlled vocabulary. Credit to @thevandalen for the link!

The DataCite team is considering using this vocabulary in the DataCite schema. It's in their roadmap and their collecting information from people who are interested. See https://portal.productboard.com/71qotggkmbccdwzokuudjcsb/c/59-contributor-roles-aligned-with-credit-list

If there's still interest in the Dataverse community to incorporate this CRediT vocabulary, I think a separate issue should be open for it. It's a bit complicated since Dataverse repositories have been using the DataCite schema's existing Contributor vocabulary for so long, and that discussion might bury the suggestion to expose the Contributor metadata in the metadata summary panel (above the tabs).

**Comment by stevenmce** [comment]
Hi Julian,

A big +1 for this from ADA. This would also fit in well with plans for using controlled vocabularies in DV that we've been discussing in the CV working group.

It should be possible to align the DataCite and CRediT vocabularies. This should be on their agendas as well.
The International Committee of Medical Journal Editors recommend the use of CRediT (read - those who publish in Elsevier, Science, British Medical Journal, ...). Lining up these two agendas is VERY high value returns and low hanging fruit.

**Comment by pdurbin** [comment]
> This reminds me of the composable dataset page @pameyer wants.

Just to follow up on this, we ended up creating the :CustomDatasetSummaryFields config option so that installations can put whatever fields they want above the tabs. Docs at https://guides.dataverse.org/en/5.3/installation/config.html#customdatasetsummaryfields

**Comment by poikilotherm** [comment]
Just today I learned about https://casrai.org/credit via [Nine Best Practices for Research Software Registries and Repositories](https://ui.adsabs.harvard.edu/abs/2020arXiv201213117B)

Maybe this is in scope for @hermes-hmc? Tagging @atrisovic, too.

**Comment by stevenmce** [comment]
Per comments at #8213, note the new home of CRediT at https://credit.niso.org/ (CASRAI has ceased operations)

**Comment by atrisovic** [comment]
+1
I think it is in scope! Also, it would probably be good to introduce an authorship policy at Dataverse.

**Comment by pdurbin** [comment]
> we ended up creating the :CustomDatasetSummaryFields config option so that installations can put whatever fields they want above the tabs. Docs at https://guides.dataverse.org/en/5.3/installation/config.html#customdatasetsummaryfields

Again, people can use the setting above to put whatever fields they want above the tabs.

Vote to close.

(And thanks @poikilotherm for creating #8213 as a dedicated issue about CRediT.)

**Comment by pdurbin** [comment]
Please :CustomDatasetSummaryFields. It's even supported in the new React UI.
