### ISSUE TITLE
OSF + Dataverse: OSF now mints DOIs for Registries 

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2236]
OSF is now minting DOIs for registries, do we have that DOI being pushed into the Related Materials metadata field when an OSF publishes data from OSF to Dataverse? we should look into this.

**Comment by posixeleni** [comment]
With OJS' integration the article DOI is put into the Related Publications field under ID Number but the Related Materials field is just a free-text field .

![image](https://cloud.githubusercontent.com/assets/5013837/7974228/32cdf7da-0a2d-11e5-9ffa-9299a44115f1.png)

**Comment by eaquigley** [comment]
After discussing with @posixeleni, we have come up with a solution and I created this as a ticket in OSF's repo. https://github.com/CenterForOpenScience/osf.io/issues/3255

Closing ticket.

**Comment by pdurbin** [comment]
Just a heads up that https://github.com/CenterForOpenScience/osf.io/issues/3255 was just closed. I don't believe anything was implemented but who knows.
