### ISSUE TITLE
Documentation: Installer's manual has incorrect info on Weld and should probably be made more obvious given the seriousness of the issue.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2237]
The installer's guide references v2.2.4 of WELD but to fix the issue I believe we need v2.2.10 as well as the lazy load setting.

http://guides.dataverse.org/en/latest/installation/prerequisites.html?highlight=weld

**Comment by bencomp** [comment]
I think @pdurbin just stumbled across this too when we were looking at docs.

**Comment by kcondon** [comment]
The steps to update weld in the installation guide are on the prequisites page:
http://guides.dataverse.org/en/latest/installation/prerequisites.html

I've repeated the contents but updated the links and changed one step, I delete the original weld file rather than rename it since the system doesn't care about the file name, just looks for the libraries.

This is what it should say:

Required Glassfish Versiion 4.1 is with weld v.2.2.10.SP1 module.

Download Glassfish:
$ wget http://dlc-cdn.sun.com/glassfish/4.1/release/glassfish-4.1.zip
$ rsync -auv glassfish4 /usr/local
$ cd /usr/local/glassfish4/glassfish/modules
$ rm -rf weld-osgi-bundle.jar

Download weld v.2.2.4 and copy in the modules folder:
$ wget http://central.maven.org/maven2/org/jboss/weld/weld-osgi-bundle/2.2.10.SP1/weld-osgi-bundle-2.2.10.SP1-glassfish4.jar 
$ cp weld-osgi-bundle-2.2.10.SP1-glassfish4.jar /usr/local/glassfish4/glassfish/modules/
$ service glassfish start

Verify Weld version:
$./asadmin osgi lb | grep 'Weld OSGi Bundle'

**Comment by pdurbin** [comment]
I didn't realize SP1 was out so we should probably update Vagrant to use that version instead of this one:

murphy:dataverse pdurbin$ grep weld downloads/download.sh
curl -L -O http://search.maven.org/remotecontent?filepath=org/jboss/weld/weld-osgi-bundle/2.2.10.Final/weld-osgi-bundle-2.2.10.Final-glassfish4.jar

**Comment by landreev** [comment]
Fixed the weld patch instruction, pushed into 4.0.2. (will update the prod. version doc on guides.dataverse.org on Monday).

**Comment by landreev** [comment]
OK, @pdurbin  has created a guides branch for v.4.0.1  (for making retroactive changes to the docs while 4.0.1 is in production) and set up a jenkins project. 
I've made a few more mods to the "prerequisites" page (also fixed the PostgresQL configuration section, that was missing instructions on granting access to the Dataverse app). 
The changes are now showing in the default guide in production.

**Comment by landreev** [comment]
(I committed all these changes into 4.0.2; then merged back into guides4.0.1 branch. so they are now showing in both prod. and dev. versions of the guide)

**Comment by kcondon** [comment]
OK new version info in place, closing.
