### ISSUE TITLE
E-mails in the API to list explicit group members

### ISSUE THREAD

**Issue by 4tikhonov** [IQSS/dataverse#2238]
Is it possible to add emails in the API to list group members?

At the moment this functionality allows to see containedRoleAssignees.
http://guides.dataverse.org/en/4.0/api/native-api.html#explicit-groups
"List explicit groups under dataverse $id:
GET http://$server/api/dataverses/$id/groups"

At the moment:
{"status":"OK","data":[{"identifier":"&explicit/34-di","groupAliasInOwner":"rurep","owner":34,"displayName":"distat","containedRoleAssignees":["@user1","@user2"]},{"identifier":"&explicit/34-di","groupAliasInOwner":"Ri","owner":34,"displayName":"di","containedRoleAssignees":["@user1","@user2"]}]}

Expected result should something like that:
{"status":"OK","data":[{"identifier":"&explicit/34-di","groupAliasInOwner":"rurep","owner":34,"displayName":"distat","containedRoleAssignees":["@user1","@user2"]},{"identifier":"&explicit/34-di","groupAliasInOwner":"Ri","owner":34,"displayName":"di","containedRoleAssignees":["@user1","@user2"], "e-mails":["email1@hotmail.com", "email2@hotmail.com"]}]}

Thanks in advance!

**Comment by pdurbin** [comment]
This conversation started in chat: http://irclog.iq.harvard.edu/dataverse/2015-06-04#i_20411

**Comment by djbrooke** [comment]
If we discuss this in the hackathon, we should discuss the permissions of this API before starting work.

**Comment by pdurbin** [comment]
@4tikhonov are you still interested in this?

**Comment by pdurbin** [comment]
@4tikhonov is this still something you want?
