### ISSUE TITLE
dataverse-client-python SSL error on connection

### ISSUE THREAD

**Issue by garthg** [IQSS/dataverse#2239]
Hi @pdurbin ,

I seem to have encountered a problem in the Python Dataverse client. I'd really like to be able to use the client, because it's got a lot of helpful functionality, so I'm reporting the error here.

I'm receiving a fatal SSL error when I create a new Dataverse connection object. My invocation looks like this:
```
dataverse_conn = dataverse.Connection('dataverse.harvard.edu', my_api_key)
```
Here is the traceback:
```
Traceback (most recent call last):
  File "update.py", line 49, in <module>
    dataverse_conn = dataverse.Connection('dataverse.harvard.edu', api_key)
  File "/opt/src/src/dataverse/dataverse/connection.py", line 23, in __init__
    self.get_service_document()
  File "/opt/src/src/dataverse/dataverse/connection.py", line 33, in get_service_document
    resp = requests.get(self.sd_uri, auth=self.auth)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 68, in get
    return request('get', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 1] _ssl.c:510: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
```
This same code ran without a problem two days ago, so it seem that something has changed. If I'm invoking this incorrectly, please let me know!

Thanks,

Garth

**Comment by pdurbin** [comment]
> so I'm reporting the error here

Hi @garthg! Are you reporting the error here rather than https://github.com/IQSS/dataverse-client-python/issues because you suspect there's a problem with the SSL cert at https://dataverse.harvard.edu ? I **think** that cert is fine but could you also try https://apitest.dataverse.org ? All the tests seem to be passing at https://travis-ci.org/IQSS/dataverse-client-python

**Comment by garthg** [comment]
Hi @pdurbin ,

I just tested against apitest.dataverse.org and succeeded in connecting, so it's definitely something wrong either with my setup or with the production server at dataverse.harvard.edu. I don't have any certificate problems in the web browser, though, so if it's the same cert then it must be something else about the connection. In that case, probably this bug would be more appropriate inside dataverse-client-python, so sorry about that.

Does my invocation look correct?

Also, in case it matters, I just reinstalled the client using the following command and the issue still persists:
```
pip install -e git+https://github.com/IQSS/dataverse-client-python.git#egg=dataverse
```

Any ideas?

**Comment by pdurbin** [comment]
Hmm, maybe there **is** a problem with that cert in production:

```
$ curl https://dataverse.harvard.edu/
curl: (60) Peer certificate cannot be authenticated with known CA certificates
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

I'll notify the authorities! :)

**Comment by pdurbin** [comment]
@astrofrog are you seeing these errors too?

**Comment by garthg** [comment]
Thanks for checking it out @pdurbin !

**Comment by astrofrog** [comment]
I see the same error with ``curl``

**Comment by lyndsysimon** [comment]
We're having the same issue on the OSF. It seems to be coming from the fact that a new SSL cert was issued for the domain `dataverse.harvard.edu`. The cert works for me on my Macbook Air in Chrome, Firefox, and Safari - but it doesn't validate for others in the COS office.

Here's a screenshot of the cert details:

![screen shot 2015-06-05 at 1 28 28 pm](https://cloud.githubusercontent.com/assets/131414/8012058/42ced950-0b8c-11e5-85c5-75831ac68e1e.png)

![screen shot 2015-06-05 at 2 09 03 pm](https://cloud.githubusercontent.com/assets/131414/8012083/71065bb8-0b8c-11e5-966e-215a8561b57b.png)

I've downloaded the PEM and attempted to validate it on the OSF application server - it doesn't validate.

From this point forward, my knowledge is a bit more sparse. It *seems* to me that the root CA for your issuer is not part of our server deployment. There are no cert files installed with "Internet2", "InCommon", or "USERTrust" in the names, so I think that's the issue. That said, it could also be that there are intermediate certs that are available on my OSX workstation but not on the OSF application server, breaking the verification chain.

I think I can fix this by finding the correct CA cert and installing it on the server for now - but that raises a number of trust issues. More importantly for Dataverse, I suspect that most users won't have the ability to add a trusted root CA to their environment. In light of that, I recommend that a new cert from a more universally accepted CA be purchased for the `dataverse.harvard.edu` domain and deployed.

**Comment by keflavich** [comment]
Is there a temporary workaround I can try?  I'm also experiencing this issue.

**Comment by garthg** [comment]
Thanks @lyndsysimon for clarifying!

It sounds like the eventual solution is to get a new cert, which makes sense. In the meantime, I just wanted to cast a vote for deploying the temporary fix you suggested (finding the correct CA cert and installing it), because I think all some or all API users are blocked at the moment.

Please let me know if you take any steps here, or make any additional discoveries about the problem. Thank you for your help!

Garth

**Comment by garthg** [comment]
Hi @lyndsysimon and @pdurbin ,

I hope you both had a good weekend. Unfortunately, I'm pretty much blocked by this at the moment, so I wanted to check and see if either of you had any updates on it, either for a fix or for a temporary workaround. Anything new here?

Thanks for your help!

Garth

**Comment by lyndsysimon** [comment]
I've not had time today to investigate further, but I found a resource on Friday that seemed to indicate that the problem could be solved by bundling additional intermediate certificates.

http://www.acns.colostate.edu/files/UnderstandingInCommonSSLCertificateChains.pdf

**Comment by garthg** [comment]
Hi @lyndsysimon , thanks for the update. That pdf does seem to suggest that the currently-breaking certificate could be made to work by somehow causing the Dataverse server to link it with an already-trusted certificate, but I'm not so familiar with how that works. Please let me know if you figure anything else out with this stuff!

**Comment by garthg** [comment]
Hey,

My test for this just started passing. Did a fix or workaround just get implemented? If so, thank you very much!

Garth

**Comment by pdurbin** [comment]
@garthg I just heard that the cert was worked on, so if you're saying it's fixed, that's great! For my part, I repeated by `curl` test and I'm no longer seeing any cert errors.

**Comment by garthg** [comment]
Hi @pdurbin , yep it looks like it's working! Thanks to all those who helped resolve this so quickly!
