### ISSUE TITLE
Review Groups UI: determine missing workflow steps based off user feedback

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#2240]
Working with a user issue today where they created a group but the group doesnt display anywhere in the UI after its been created (until you go to Assign a Role) which made them think that the group was never actually created (regardless of a success message).

Can we have a place in the UI:
1. where it lists all the groups a user has created even before they assign roles to them? Otherwise it looks like these groups dont exist.
1.1 where they can edit who is in the group
1.2 where they can rename a group
1.3 where they can delete a group they have created 

Related: #92

**Comment by eaquigley** [comment]
Reviewed this ticket today. In the Groups option under Edit Dataverse, there is a table that is now created when a Group has been created. However, there is a message saying you need to refresh the page to see the new group and no matter how many times I try adding a member to the group, the member column never changes from No Members.

**Comment by mheppler** [comment]
The cleanup of the Manage Dataverse Groups pgs was completed in [4.1](https://github.com/IQSS/dataverse/releases/tag/v4.1). I suggest this issue can be closed, with the 4.1 milestone added for reference. If there are any problems contained in this issue that have no been resolved, we can address with additional user testing in a future release.

![screen shot 2016-10-27 at 5 29 58 pm](https://cloud.githubusercontent.com/assets/687227/19786376/a58e8790-9c6b-11e6-81cf-523939d78442.png)

**Comment by kcondon** [comment]
Mike, feel free to close if this is a Design decision.
