### ISSUE TITLE
Let users from the same group directly inform each other about changes in the shared dataset

### ISSUE THREAD

**Issue by 4tikhonov** [IQSS/dataverse#2242]
We want to create collaborative platform where all our researchers will be combined in the specific groups to share efforts and work on the same dataset. Every person from the group should be able to contact other researcher to inform about latest updates in datasets. 

Probably the basic "Email Dataset Contact" function can be extended with functionality like that if  person that sharing the same dataset will click on this button and will contact other user from the group. 

E-mail with notes should be delivered only to selected users but person should get direct link to download and explore dataset shared by the group. I'll attach screenshots if it's not clear as I've implemented this feature but I'm wondering if other people would like to have this functionality in the core of Dataverse.

**Comment by posixeleni** [comment]
@eaquigley @mheppler @scolapasta would this be something we could do via our notifications feature but specifically for Groups?

**Comment by 4tikhonov** [comment]
Just note that it's really critical for us to have possibility to select people from the list as we have quite a lot of people in our institution collecting data on different countries from the same dataset, for example.

**Comment by 4tikhonov** [comment]
At the moment it works like that:
![collabs](https://cloud.githubusercontent.com/assets/704075/8009894/131c93ee-0bac-11e5-8e56-ebfb1411f90d.png)

**Comment by pdurbin** [comment]
@4tikhonov are you still interested in this?

**Comment by pdurbin** [comment]
@mheppler @dlmurphy do you think this sounds a bit too much like adding chat to Dataverse? I just left a somewhat related comment about this at https://github.com/IQSS/dataverse/issues/3943#issuecomment-312147274

Here it is again:

> The curator isn't supposed to ask question like, "Is there a third author?" because the author can't reply. We are not building chat within Dataverse. If the curator needs to chat with the author, use a chat application for goodness sake. Or email. The author is receiving instructions or requirements or advice from the curator, not questions.

**Comment by pdurbin** [comment]
@4tikhonov is this still something you're interested in?
