### ISSUE TITLE
API endpoint as new object type in Dataverse

### ISSUE THREAD

**Issue by 4tikhonov** [IQSS/dataverse#2245]
Problem statement
During community meeting it was big discussion how to describe, store and process Big Data (petabytes of data) in Dataverse.

Suggestion
Dataverse data model should be extended with new object called "API" that will keep the information about all API endpoints and will allow to add technical specification how to use specific APIs. 

Solution

Prototype
I used our our project API endpoint to create file containing link to API and uploaded user guide how to query it with some examples. It will create metadata level and will allow people find our datasets provided by API in Dataverse but API service API will be provided by other system (Hadoop, Spark, MongoDB, etc).
http://dv.sandbox.socialhistoryservices.org/dataset.xhtml?persistentId=hdl%3A10622%2FDXZAZM&version=DRAFT

The concept
We can let different Big Data systems communicate to each other. The only problem is harmonization but it should be done on research side.

Is it difficult to implement feature like that?

**Comment by 4tikhonov** [comment]
Phil, I'm attaching the drawing I've showed you yesterday (sorry for low quality of the image). 
I'll explain the vision and idea behind today.
![img_0406](https://cloud.githubusercontent.com/assets/704075/8084223/38c778ac-0f8a-11e5-9dc7-99df10e690ba.JPG)

**Comment by pdurbin** [comment]
@4tikhonov as we discussed, **perhaps** we could think about defining a different kind of dataset, perhaps similar to a "harvested" dataset. It sounds like you're going to do some more thinking and prototyping. Also, perhaps the functionality you're looking for could be built into a separate "microservice" that runs alongside Dataverse, rather than being part of the Dataverse code itself.

**Comment by 4tikhonov** [comment]
Well, I've just intended Breakout Session for Metadata curation and have beautiful idea to extend Metadata section with extra field called API. What is the best way to create new metadata fields in Dataverse?

**Comment by pdurbin** [comment]
@4tikhonov would all the recent work on support for Swift and rsync help? What is your latest thinking on this?

**Comment by 4tikhonov** [comment]
Sure, I think we're moving fast in this direction now and able to create any metadata fields. And a lot of new opportunities are coming with Docker.

**Comment by 4tikhonov** [comment]
Sure, please close it.

**Comment by pdurbin** [comment]
@4tikhonov thanks! Now we're at 799. 😄
