### ISSUE TITLE
Guides: Add Functional Requirements Documents to Guides

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2246]
Brought up during Dataverse Community Meeting. Would be great to add FRDs after development is completed to the guides so they aren't behind google drive and are easy to access as while as read.

**Comment by bencomp** [comment]
To get a better grasp of what is being developed and with what constraints use cases are being implemented, I would like an overview of all existing FRDs. (The few links in the description of the *In Design* [milestone](https://github.com/IQSS/dataverse/milestones) aren't enough.)
A **link from [CONTRIBUTING.md](https://github.com/IQSS/dataverse/blob/master/CONTRIBUTING.md) and/or the Developers' Guide to a dynamic view of all FRDs** would be the best. If all FRDs are in a specific Google Drive folder, this folder would have to be publicly viewable (which doesn't necessarily mean that the documents inside that folder are viewable, I think). This then allows people to understand the design of the application (and start contributing).

When developers read the FRDs and implement the actual requirements in code, they should write documentation with the code and tests demonstrating that the code behaves as designed. (At least one unit test for each requirement = awesome.) Only then can others verify that Dataverse works as designed. 

Writing documentation in code has been a long-standing request of mine: #775 - writing tests is good practice.

**Comment by eaquigley** [comment]
@bencomp ( @mcrosas as well), my thoughts on structure of FRDs in Google Drive is this: 
FRD Folder->In Design Folder (all FRDs for In Design milestone are here)
FRD Folder->Individual Release Folder (all FRDs for that release are here)

So in the contributing.md there would be a link to the overall FRD folder and anyone can view them by release or in design so they are organized that way so they match up to Github and code releases

**Comment by mcrosas** [comment]
:+1:

**Comment by eaquigley** [comment]
@bencomp I've added a few FRDs to the 4.2 folder in the FRD folder and updated the contributing.md to have a link to it. I'll continue to add FRDs there.

**Comment by bencomp** [comment]
@eaquigley great. Where can I find this folder?

**Comment by eaquigley** [comment]
Updated this in commit 266120c8b278be3f9800299fa753e84e870d6ada

**Comment by kcondon** [comment]
Links are added to Contributing.md as discussed. Closing.
