### ISSUE TITLE
Software field in metadata displaying version instead

### ISSUE THREAD

**Issue by nmedeiro** [IQSS/dataverse#2248]
In the conversion to 4.0, the software field, which in our case always encoded "Stata" appears with the version instead (12).  The resulting display reads

12, Version: 12

**Comment by mheppler** [comment]
It appears that this issue has been fixed. If that is not the case and this issue should be reopened, then please let us know.

[NBA Contracts and Recency Bias: An Investigation into Irrationality in Performance Pay Markets](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/Z1A1KE)

<img width="408" alt="screen shot 2016-10-10 at 3 24 17 pm" src="https://cloud.githubusercontent.com/assets/687227/19248377/a3aa222a-8efd-11e6-9855-f25824e143fb.png">
