### ISSUE TITLE
Error when trying to explore tabular data

### ISSUE THREAD

**Issue by umeditor** [IQSS/dataverse#2250]
Clicking "Explore" gives me this error message:

![error](https://cloud.githubusercontent.com/assets/206762/8109852/07604ad0-1027-11e5-905a-c0e81f87d03e.png)

> The page at https://dataverse.harvard.edu says:
? There was an error making hte request. xmlhttprequest status is 0.

I'm running Google Chrome Version 41.0.2272.101 (64-bit) on Mac OS X 10.9.5.

To recreate:
1. Goto https://dataverse.harvard.edu/dataset.xhtml?persistentId=hdl:1902.1/CGKYQXYSXG
2. Click "Explore" for mazedata1.tab

**Comment by landreev** [comment]
Hi, 
Please try again. 
TwoRavens, the data explore application, was upgraded last night. It turned out that it introduced some issues, that affected some datasets. We have just put in place some fixes.
Please let us know if it is working for you now.

**Comment by umeditor** [comment]
Looks good.
