### ISSUE TITLE
Geoconnect: provide heartbeat link to allow service monitoring of geoconnect and worldmap

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2251]
We have been seeing availability issues with the Geoconnect/ Worldmap function and would like an automated way to monitor and measure the availability of both services. 

---

### Notes:
  - This is a dataverse codebase change

**Comment by djbrooke** [comment]
Going to remove from 4.6.3 as this has been open for 2 years. Will reopen if there are issues that dictate the need for additional monitoring.

**Comment by pdurbin** [comment]
Duplicate of #2183.

**Comment by mheppler** [comment]
With recent efforts related to system stability, I found this issue, and the now closed duplicate "Worldmap - some type of check if service is 504, etc #2183" issue.

Similar service availability features where mentioned for persistent ID providers like DataCite and EZID, which is related to #2225.

**Comment by djbrooke** [comment]
Closing some old Worldmap issues. Will re-evaluate when/if additional Worldmap work gets added to the roadmap. There is another issue (searching skills are failing me now, will link when I find it) about providing a dashboard for monitoring services used by the community, we may put this under there.
