### ISSUE TITLE
Notifications: Deleting notifications does not update UI until page refresh/reload.

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2252]
Seen in demo and production on macbook. Click on the X to delete the notification and it does nothing. Notification does not disappear.

**Comment by eaquigley** [comment]
At demo.dataverse.org with build  v. 4.2.2 build 54-9883aaa, the notifications are only deleted after refreshing the page.

**Comment by jggautier** [comment]
This seems to be working now, at least on macOS Sierra (10.12.4 (16E195)) and on:
Chrome: Version 57.0.2987.133 (64-bit)
Firefox: 52.0.2 (64-bit)
Safari: Version 10.1 (12603.1.30.0.34)
<br>

![deleting_notifications](https://cloud.githubusercontent.com/assets/18374574/24839045/ba157dd6-1d21-11e7-8b0a-7a4f66449a5c.gif)

**Comment by pdurbin** [comment]
@jggautier fantastic! Very convincing animation that this bug has been fixed! Who knows when it was fixed but it doesn't matter. :smile:  Thanks! Closing this issue.
