### ISSUE TITLE
Group identifier needs tool tip to explain why it's important

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#2254]

**Comment by scolapasta** [comment]
Mentioned by @bencomp during a demo.

**Comment by bencomp** [comment]
And @eaquigley was there too.

As a user, when I create a group in the Permissions view, I have to enter both an identifier and a name for the group. As well as some confusion about the requirement for a group identifier itself, I found it not obvious to first give the identifier and secondly the group name. If you first create a group name, perhaps the group identifier could be suggested based on the name. (Is group ID case sensitive, by the way?)

**Comment by mheppler** [comment]
@eaquigley - Does this work for a tooltip?

Group Identifier - "Short name used for the ID of this group."

**Comment by eaquigley** [comment]
+1

**Comment by bencomp** [comment]
I guess that could work, yes.

**Comment by kcondon** [comment]
Works for me too! Closing.
