### ISSUE TITLE
Templates: link for editing general info does not work

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#2256]
It used editMode in the URL., but editModes are not currently guaranteed to work from the URL.

**Comment by pdurbin** [comment]
@scolapasta do you happen to know if this still doesn't work?

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
