### ISSUE TITLE
Cannot deselect guestbook for a dataverse

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#2257]

**Comment by scolapasta** [comment]
Noticed by @bencomp during a demo.

**Comment by bencomp** [comment]
It appears that a guestbook is selected via a radio button instead of a checkbox. If there is just one guestbook, and it is selected, you cannot deselect it after saving.

**Comment by mheppler** [comment]
There is a "Clear Selection" button on the page (see attached), but the render logic for it is `rendered="#{!empty DatasetPage.dataset.guestbook}"` which only seems to render the button after you save, or preview (which triggers the blue spinner). I tried applying an AJAX behavior event of `rowSelectRadio` in the dataTable, but I was not able to get it to work.

![screen shot 2016-02-16 at 3 18 29 pm](https://cloud.githubusercontent.com/assets/687227/13089942/1d9c8624-d4c1-11e5-9c1f-d096e93a6d54.png)

**Comment by bencomp** [comment]
How about an default row "no guestbook" with its own radio? 
In any case I don't think you want to trigger a server call before you save (like what happened in #2633 before requesting the actual download). Client-side JavaScript could do the same.
