### ISSUE TITLE
Move guestbook up the user story

### ISSUE THREAD

**Issue by tokeefe** [IQSS/dataverse#2260]
The ability to capture additional information about users is important to decide who should be granted access to a restricted file, or files. I propose that the Guestbook should be presented when the user requests access to restricted files, not when the user attempts to download these files.

**Comment by tokeefe** [comment]
Sorry this is a duplicate of #2043

**Comment by eaquigley** [comment]
Passing this ticket to QA to close since it is a duplicate of #2043.

**Comment by kcondon** [comment]
Closing as duplicate
