### ISSUE TITLE
Documentation: update user guides with list of all files supported for ingest

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#2265]
A list of all file formats and accepted versions.

**Comment by landreev** [comment]
The documentation section on tabular data ingest has been expanded and improved. 
(the "tabular data" section of the dataset management guide has been rewritten; a new "tabular data ingest" section has been added).

**Comment by sbarbosadataverse** [comment]
@landreev  can I have the text I should be checking? I see text there now but I have nothing to compare it to at this point.

**Comment by sbarbosadataverse** [comment]
@landreev  and don't see anything called: tabular data ingest. There is a regular: http://guides.dataverse.org/en/latest/user/dataset-management.html?highlight=dataset and "tabular"

**Comment by landreev** [comment]
@sbarbosadataverse 
The "latest" in your URL: 
http://guides.dataverse.org/en/latest/user/dataset-management.html?highlight=dataset
- I think that's pointing to the current production documentation. So it's not really "latest"; or, it is, as in "latest, available to the users". 
You need to go specifically to the version 4.1 to see the documentation for the version we are currently working on: 

http://guides.dataverse.org/en/4.1/user/tabulardataingest/supportedformats.html

**Comment by sbarbosadataverse** [comment]
looks good
