### ISSUE TITLE
Allow users to select additional metadata for tabular metadata

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#2266]
preselect default model to be used with TwoRavens
set variable type or attributes

**Comment by pdurbin** [comment]
@scolapasta what's the user story for this one? @vjdorazio @tercer do you happen to know?

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
