### ISSUE TITLE
Add an ability to link data files by certain variables

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#2267]
In this way the user would be able to use tools like TwoRavens across multiple data files.

**Comment by scolapasta** [comment]
This is related to the Provenance functionality for linking data files.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
