### ISSUE TITLE
Add threshold size for ingest file

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#2268]
We have seen issues with large files failing ingest and know they may cause issues. So we should determine the right logic for this threshold and a) not ingest it, b) provide good feedback to user, explaining what happened.

**Comment by scolapasta** [comment]
Please review how we return this feedback to the end user (could be a notification).

**Comment by landreev** [comment]
I have added the threshold; it can be set as a blanket size for all ingestable formats (not recommended?), or for individual formats. 
(we will need to review separately what these limits should be set to, and for what formats. it may not be needed for all supported formats; it is definitely needed for R, as it is still very inefficient - but I'm still not sure what this limit should be).

**Comment by kcondon** [comment]
@scolapasta @landreev How is this set and is there any feedback given to the user if they hit the limit?

**Comment by landreev** [comment]
The size limit is an application setting. It can be set for a specific supported format, like this:

curl -X PUT -d LIMIT http://localhost:8080/api/admin/settings/:TabularIngestSizeLimit:FORMAT

where LIMIT is the size limit in bytes; and FORMAT is a format identification tag, as reported by the plugin. 
The tags for the currently supported format are as follows (case sensitive!):

dta
por
sav
Rdata
CSV
xlsx

So, for example, to set the limit for R files to 1000 bytes, the API call will be

curl -X PUT -d 1000 http://localhost:8080/api/admin/settings/:TabularIngestSizeLimit:Rdata

I didn't have time to add a user notification. So as of now the app will just quietly skip attempting to ingest those files that are above the size limit. (they will of course still be ingested as "plain", non-tabular files).

**Comment by landreev** [comment]
P.S. Also, it is possible to set a "blanket" size limit, that will apply to all tabular format - that would be simply 

curl -X PUT -d LIMIT http://localhost:8080/api/admin/settings/:TabularIngestSizeLimit

(i.e., with no FORMAT tag). 
This doesn't have much of a practical value; because different formats have very different "problem" thresholds. But it could be used to flat-out disable tabular data ingests on a system - by enabling it and setting the value to zero.

**Comment by kcondon** [comment]
OK, tested turning ingest off completely, limit=0, the below and above thresholds for all and each formats.
Closing.
