### ISSUE TITLE
Determine how best to present which "apps" to show for which files

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#2269]
We need to decide if we will configure this at the dataverse, dataset, or data file level (or multiple).

**Comment by bencomp** [comment]
This sounds like a UI related task? Do I hear Appiverse? :)

**Comment by mcrosas** [comment]
:+1:

**Comment by pdurbin** [comment]
Anyone interested in this issue may want to participate in this Tuesday's community call because Scholars Portal will be giving a demo of their new "DDI Explorer" app. For details on how to call in, please see https://groups.google.com/d/msg/dataverse-community/Zpib-uCIG1g/Rg9tJGieBAAJ

**Comment by scolapasta** [comment]
Closing in favor of #3657
