### ISSUE TITLE
Minor update of tworavens/r documentation

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#2270]
Update the doc and the installer scripts, incorporate what we've learned in the most recent tworavens upgrade: 
lists of dependencies with specific versions; 
disable directory listing on the dataexplore directory; 
more? ...

**Comment by landreev** [comment]
The TwoRavens doc should be up-to-date and accurate at this point. (Vito has actually added most of it).

**Comment by kcondon** [comment]
Versions and directory disable were added. Closing.
