### ISSUE TITLE
Delete File: File tags prevent files from being deleted. Remove tag and delete works.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2273]
Delete File: File tags prevent files from being deleted. Remove tag and delete works.

**Comment by scolapasta** [comment]
Please try this again.

**Comment by kcondon** [comment]
OK this works for this specific scenario:
within the same draft, add and delete 2 files that have the same tags.
I was not able to reproduce the problem on a non patch server otherwise.
Closing.
