### ISSUE TITLE
Robots txt: Enable Google

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2274]
Need to enable Google in the robots.txt file so datasets can be discovered in Google Scholar: https://dataverse.harvard.edu/robots.txt

**Comment by eaquigley** [comment]
Passing to QA. @kcondon let me know this was changed.

**Comment by pdurbin** [comment]
I noticed https://github.com/IQSS/dataverse/blob/4.0.2/src/main/webapp/robots.txt was not changed so I think what's happening is that we want robots.txt to block Google for all the **test** instances of Dataverse. That is, Google is blocked by default. For a **production** instance I assume there's some procedure for letting Google crawl a Dataverse instance. Probably this should be documented somewhere.

**Comment by kcondon** [comment]
I did not realize this file was checked in. Seems like a hassle. I directly changed the robots.txt file in production to resolve the request but if I'm reading you right, this will be overwritten during the next deployment.

________________________________

**Comment by dliburd** [comment]
Verified. Also datasets added within the last 30 days were discoverable via google.
