### ISSUE TITLE
File Ingest: CSV ingest does not seem to be working.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2275]
Tested with the original test file provided by Leonid from redmine, https://redmine.hmdc.harvard.edu/issues/3750

collier-1740.csv

Also created a very simple csv file:

One,Two,Three
1,2,3
1,2,3
1,2,3

**Comment by landreev** [comment]
Please re-test (fixes committed today). 
CSV type recognition should be working again (it appears it got broken in 4.0.1); 
There are specific issues with CSV ingest - such as handling of commas embedded in string values; that is being addressed in its own ticket.

**Comment by landreev** [comment]
If it tests ok, I would suggest to patch it in prod. tomorrow.

**Comment by sbarbosadataverse** [comment]
both of my csv files displayed ingest errors. One ingested as "0" bytes and one displayed the red ingest error icon

![screen shot 2015-07-15 at 4 57 41 pm](https://cloud.githubusercontent.com/assets/8322346/8709650/d46fb894-2b11-11e5-893a-b67c790d7652.png)

**Comment by landreev** [comment]
@sbarbosadataverse : 
It appears that ALL files were ingesting with "0 bytes" in the info label, for the last months or so. 
You were just the first to notice. Had nothing to do with the file being CSV. 
This is now fixed.

**Comment by landreev** [comment]
@sbarbosadataverse : 
As for the file that failed with an error message: I need more to work with - for example, what the error message was. And I would usually need the file that failed. 
OK, I found the file on dvn-build. The error message is pretty clear - "invalid variable names in the first line". Yes, a CSV file must have the variable names in the first line, in order to ingest as a tabular file.

**Comment by landreev** [comment]
@sbarbosadataverse I'll make sure this is explained in the ingest guide.

**Comment by landreev** [comment]
@sbarbosadataverse 
The error message shown for this condition now explicitly says: 
"First line of a CSV file must contain a comma-separated list of the names of the variables."
Also, made sure this requirement is in the documentation (in the user guide -> tabular data ingest -> tab; under "Formatting Requirements").

**Comment by sbarbosadataverse** [comment]
@landreev  thank you! I'll check the files again!
