### ISSUE TITLE
Manage Templates Page: Square Around Text is Missing

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2276]
When a user has no templates and the help text is showing, there is no box around it like there is for an empty Guestbook page. This needs to change so there is a box around it.

![guestbookbox](https://cloud.githubusercontent.com/assets/5922904/8208605/7e78efb0-14d6-11e5-8496-d807a58cd95a.png)
![templatenobox](https://cloud.githubusercontent.com/assets/5922904/8208613/8336deea-14d6-11e5-8b2d-ce139c768271.png)

**Comment by mheppler** [comment]
Added Bootstrap border styling and containing div element to the "no templates" view.

**Comment by dliburd** [comment]
Verified: The box appears in Manage Templates Page.
