### ISSUE TITLE
EZID Service Bean: Modify Logging To include Warnings when processes fail 

### ISSUE THREAD

**Issue by sekmiller** [IQSS/dataverse#2277]
When connections to EZID server or create/modify identifier fail, we are only putting INFO into the log not WARNING. We should make them warnings

**Comment by bencomp** [comment]
Agreed :)

**Comment by bencomp** [comment]
(This is one of the guidelines for a nicer code style in #775.)

**Comment by bencomp** [comment]
Actually, I am thinking that when logging into the EZID service fails, this should be logged as `SEVERE`. What happens if login fails? Will DOIs not be registered? What if the login failure is caused by bad configuration?

**Comment by bencomp** [comment]
Even though I said SEVERE may be better, I gave `WARNING` a shot in https://github.com/bencomp/dataverse/commit/0119f161f95d6536ad040de2b51631df86533640. Since some log calls include `Throwable`s, I changed the call to use the `Throwable`-accepting variant.

**Comment by pdurbin** [comment]
I spoke with @sekmiller about this and he said this issue has become a lower priority for us (post 4.1 for sure) because EZID is doing more now to insulate us from DataCite failures. Or something! He said he's check out the commit by @bencomp at some point. Thanks @bencomp !
