### ISSUE TITLE
Users with multiple roles for the same DvObject

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#2282]
In the "thedata" postgres db, there are 25 users with either 2 or 3 roles for the same DvObject.

The concept of ```One User / One Role / One DvObject``` is not enforced at the database level and there appear to be instances of the concept breaking down in actual data.

Results from the 1st query below may be found in this [google doc](https://docs.google.com/a/harvard.edu/document/d/1dysi9jEPLWtIj9S_Qca8eTklIHwzgGYWMOjSlGnCTVg/edit?usp=sharing)

### 1 - Query to check for count roles for a given user and dvobject
```sql
select r.assigneeidentifier, r.definitionpoint_id, d.dtype, count(r.role_id) as cnt 
from roleassignment r,
dvobject d
where r.definitionpoint_id = d.id
group by r.assigneeidentifier, r.definitionpoint_id, d.dtype
order by cnt desc;
```
#### 2 - Query to look at roles for a specific user and dataverse id
```sql
select r.*, dr.name, d.*
from roleassignment r,
dataverse d,
dataverserole dr
where r.definitionpoint_id = d.id
ANd r.role_id = dr.id
AND r.definitionpoint_id= -- dvobject id, e.g. 123 --
AND r.assigneeidentifier= --username e.g. '@username'--;
```
#### 3 - Query to look at roles for a specific user and dataset id
```sql

select r.*, dr.name, d.*
from roleassignment r,
dataset d,
dataverserole dr
where r.definitionpoint_id = d.id
ANd r.role_id = dr.id
AND r.definitionpoint_id= -- dvobject id, e.g. 123 --
AND r.assigneeidentifier= --username e.g. '@username'--;
```

**Comment by pdurbin** [comment]
@raprasad are you thinking the enforcement should be done with a database constraint? I see you assigned this to @scolapasta so I'm assuming someone already has some ideas of how to fix this.

**Comment by raprasad** [comment]
Gave to @scolapasta for review.  If there's logic in the code that allows this, that should be fixed too.  Not sure if this is new or migrated data

**Comment by pdurbin** [comment]
Wait. I'm confused. It's a **feature** to be able to have more than one role for a DvObject as long as they are different roles, right?

**Comment by scolapasta** [comment]
Yes, there is no one user / one role / one dvObject rule. As @pdurbin, it is a feature to have 2 roles (think Member, and Dataset Creator, for someone who should be able to add datasets to an unpublished dataverse). So I think this can be closed.

**Comment by raprasad** [comment]
FYI: I think I made the ticket in the initial planning for 'mydata' -- it should have been closed.  Eg During that process, @scolapasta explained the underlying rationale.

On Jan 14, 2016, at 6:18 PM, Gustavo Durand <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, there is no one user / one role / one dvObject rule. As @pdurbin<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_pdurbin&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=EkFi6BF7pof1mvmoyqcphtSeruEfuDmHCUNhyy4Y_XM&m=tMk0uwzYVT7NOrdUXeyPb1pP_x-M4xKx0FOs2xblyiE&s=xpPaj9bwoA9KIzbnefa1Q3I5mFyYVlkNCIWW00ZBckk&e=>, it is a feature to have 2 roles (think Member, and Dataset Creator, for someone who should be able to add datasets to an unpublished dataverse). So I think this can be closed.

-

**Comment by kcondon** [comment]
Closing
