### ISSUE TITLE
Request Access for Files: Admin View Usability Issues

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2285]
Few usability issues that need to be fixed for the Admin view of a dataset page when there are restricted files.

1) If an admin has restricted files and enabled the request access button, the message they are seeing in the Terms tab for the request access button field is, "Users may not request access to files." This is very confusing. Though it may be true that a user cannot request access to the files because the draft hasn't been published, this is not clear to the admin. The Admin wants to see what will be displayed to the data downloader who comes to their dataset page. I suggest we change this to say Users may request access to files. 

2) We provide a lot of ways for an admin of a dataset page to see what the data downloader will see when they are on a dataset page. For example, the lock or no lock for files, the download button, the metadata for the files, the metadata they have filled out for the dataset. However, it is confusing that they don't see the Request Access button appearing as well. We should add it in so they know what a data downloader will be seeing when on the dataset page. This could be a fake button where if the admin clicks on it, they receive a pop up with text saying something about it or a grayed out button. My one concern with the grayed out button is they might think it still hasn't been enabled.

**Comment by mcrosas** [comment]
:+1: 

@eaquigley  shouldn't we remove the "Status: Design" and use the "Milestone: In Design" instead?

**Comment by mheppler** [comment]
A new issue, **Dataset - File UI Improvements #3404**, was created to track the UI improvements related to the files view on the dataset pg. Older feature requests and bug reports like this one will be closed in favor of that new issue.
