### ISSUE TITLE
Documentation: Add info on configuring Google Analytics to installer's guide.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2287]
Currently there is no explicit info on how to config Google Analytics in the guides. Basically add the key to the settings table.

**Comment by pdurbin** [comment]
In my pull request at #2895 I document this as http://guides.dataverse.org/en/2884-install-guide-reorg/installation/config.html#googleanalyticscode

Passing to QA.

**Comment by kcondon** [comment]
Doc'd closing.
