### ISSUE TITLE
Installer: Update installer script to change the final message to indicate correct port.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2288]
The currently installer ends with this message:

You should now have a running DVN instance at
  http://localhost[:YOURPORT]

Since we were not asked for a port number during installation and the default glassifish port is 8080, the message should probably indicate the correct URL:
http://<your host name>:8080

Also, it may be worthwhile to update the installation guide to put this same information there as in something like:
You can confirm the installation succeeded by loading the homepage at:
http://<your host name>:8080

**Comment by pdurbin** [comment]
In bb695f3 I changed YOURPORT to 8080. I'm not sure where to note this in the installation guide but I added a note about this to #2321.

**Comment by kcondon** [comment]
OK, retested installer and it works and message was updated as described. Closing.
