### ISSUE TITLE
Installer: If enter an incorrect path to glassfish, then a correct one after check fails, get perl security error and exits.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2292]
Proceeding with the Glassfish setup.

Checking your Glassfish installation...
Invalid Glassfish directory /usr/local/installer_test/glassfish4!
Enter the root directory of your Glassfish installation:
(Or ctrl-C to exit the installer): /usr/local/installer_test/glassfish4
OK!

Setting the heap limit for Glassfish to 1536MB. 
You may need to adjust this setting to better suit 
your system.

Insecure dependency in system while running with -T switch at ./install line 858, <> line 14.

**Comment by bencomp** [comment]
Sounds like a Perl thing, doesn't it, @pdurbin?

**Comment by kcondon** [comment]
This is now working as of 4.3
