### ISSUE TITLE
Regeneration of API Tokens

### ISSUE THREAD

**Issue by CamMerrill** [IQSS/dataverse#2296]
Noticed by Gustavo in tutorial - no simple way for user to revoke/destroy and create new API token.

**Comment by CamMerrill** [comment]
Finished/pushed to 4.0.2

**Comment by pdurbin** [comment]
The commit by @CamMerrill: 8bbae61

#1098 should be reviewed as well. It links to an [FRD about API Tokens](https://docs.google.com/document/d/1PfQtblJxPv975U_cTOIA7OR71MT4CslP-s2n83eb1i8/edit?usp=sharing).

Also, we should update what was written in 45f13cc

**Comment by kcondon** [comment]
OK, I am able to regenerate a new token but the button text is showing an error.

**Comment by CamMerrill** [comment]
Missing regenerate button, 
fixed in commit: https://github.com/IQSS/dataverse/commit/74d2d70233e68e612ace2d104ada14e931ae218e
pushed to 4.0.2

**Comment by dliburd** [comment]
Verified: "Regenerate Token" button displays properly.
