### ISSUE TITLE
Add publication counts next to checkboxes (mydata branch)

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#2306]
part of #2302 
Get counts for publication statuses (see screen shot)
  - @pdurbin  probably has some insight on this 
  - Here’s the method for adding the dvobject counts into the JSON
	-https://github.com/IQSS/dataverse/blob/ca65b0efdd747f1b4e28574fc52f5d27755f1500/src/main/java/edu/harvard/iq/dataverse/mydata/DataRetriever.java#L292

![root_dataverse](https://cloud.githubusercontent.com/assets/1036060/8483105/4d23e1f8-20bc-11e5-9af5-eb041e7f3294.png)

**Comment by pdurbin** [comment]
On the Solr side it's an array:

    "publicationStatus":["Unpublished", "Draft"],

Like many fields you can facet on it.

**Comment by pdurbin** [comment]
Here is where the count is set for a facet:

`FacetLabel facetLabel = new FacetLabel(facetFieldCount.getName(), facetFieldCount.getCount());`

https://github.com/IQSS/dataverse/blob/v4.0.1/src/main/java/edu/harvard/iq/dataverse/SearchServiceBean.java#L571
