### ISSUE TITLE
test with full data (mydata) 

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#2308]
part of #2302
#### Test postgres query responsiveness on local machines with full database.
Even though data isn't indexed, the bottleneck will be with postgres.
- Some notes on getting production data—Gustavo or Kevin could probably change this to work.
	It’s a .txt file that doesn’t open immediately in a browser
	https://drive.google.com/a/harvard.edu/file/d/0B4VvItDJwfehYnh1Nlo2RGMzcUk/view?usp=sharing
- See how performant the page is locally. B/c things aren’t indexed, you may get 0 cards results.
	- However, the postgres queries will run, so even “no results” will give an idea of the speed

**Comment by kcondon** [comment]
Tested with production data and super admin account. Performs reasonably well. Closing.
