### ISSUE TITLE
update jetty header http size (mydata branch)

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#2311]
part of #2302 

----

- To accommodate larger solr queries, update the jetty header size on production (first dvn-build) to allow larger http header sizes.
- See Phil's note: http://guides.dataverse.org/en/latest/installation/installation-main.html#solr-configuration, specifically the link to: https://support.lucidworks.com/hc/en-us/articles/201424796-Error-when-submitting-large-query-strings

**Comment by scolapasta** [comment]
@pdurbin should we check in a jetty.xml file into our repository for this? @kcondon

**Comment by pdurbin** [comment]
Related: #1928

**Comment by pdurbin** [comment]
@kcondon @raprasad what header size did you decide on?

**Comment by pdurbin** [comment]
Today @scolapasta @raprasad and I discovered that an internal server had the value set to one million. This is quite a bit higher than the "8192" value documented at http://guides.dataverse.org/en/4.1/installation/installation-main.html#solr-configuration

**Comment by pdurbin** [comment]
@raprasad can you please add some documentation on what the value should be?

**Comment by raprasad** [comment]
I think it's "102400"

This should be sanity checked--e.g., a significantly lower number may work fine.

e.g. test actual query for dataverseAdmin and go up as needed
```xml
            <Set name="requestHeaderSize">61440</Set>
```

**Comment by pdurbin** [comment]
This was never documented. I'm stealing this from @raprasad and folding it into #2884.

**Comment by pdurbin** [comment]
In my pull request at #2895 I increased the value of requestHeaderSize from "8192" to "102400". That change can be previewed here: http://guides.dataverse.org/en/2884-install-guide-reorg/installation/config.html#jetty-xml

I don't actually have access to this host in production so I can't verify that this is the value we use but I think it is.

Passing to QA.

**Comment by kcondon** [comment]
Doc'd closing.

**Comment by pdurbin** [comment]
Shoot. @kcondon I need to reopen this issue. @sekmiller just ran into #1439 and in helping him troubleshoot his seemingly empty installation and "Search Syntax Error: Expected content type application/octet-stream but got ." in the Glassfish server.log, I'm realizing that during my rewrite I failed to mention that you have to **add** the line in question. For now I'll reopen this. Please send it to me when you're ready for me to push a fix to the branch we're using for pull request #2895.

**Comment by pdurbin** [comment]
@kcondon I noticed you sent this issue back to me yesterday and that the milestone is still 4.3. #2895 has already been merged so please advise if you want a new pull request for just this issue (already listed at #2944 by the way) or if you just want me to fix it quick in "develop" or something.

**Comment by kcondon** [comment]
@pdurbin 
I think you said the developer should just tell me where to test it, right? What is the process in this case?

**Comment by pdurbin** [comment]
I brought this up to @scolapasta today during the standup so pass this to him for a decision.

@scolapasta again, please note that this issue is linked from the longer todo list at #2944.

**Comment by pdurbin** [comment]
@scolapasta I just chatted with @kcondon about this and reviewed what's already at http://guides.dataverse.org/en/4.2.4/installation/config.html#jetty-xml

Because that page already links to https://support.lucidworks.com/hc/en-us/articles/201424796-Error-when-submitting-large-query-strings which explains that you have to **add** something, I think most people installing Dataverse will figure it out. I recommend moving this out of the 4.3 milestone and dealing with it in #2944 where it's already referenced.

**Comment by pdurbin** [comment]
@kcondon heads up that I added a fix to @landreev 's pull request at #3017. You can see what I wrote at 49217a0. I'm moving this to QA for 4.3.

**Comment by kcondon** [comment]
Looks good, closing.
