### ISSUE TITLE
UX question: publication statues (mydata) branch

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#2312]
part of #2302 

---

Is this desired behavior:
- q: We're asking for asking for everything with "unpublished".  Why do some cards have "draft" -- I didn't check tahat
- a: "unpublished" cards correctly pulled from solr.  We display *all* of that card's statuses--including "draft"
![role_permission_relationships_-_root_dataverse](https://cloud.githubusercontent.com/assets/1036060/8485255/5d71d412-20ca-11e5-84d8-01595915954d.png)

**Comment by mheppler** [comment]
Yes. I think this is the desired behavior. I also am not sure how we can currently display anything different, unless we change the Publication Status checkboxes to have more accurate facets like "Draft/Published" and "Draft/Unpublished", that would allow for the filtering in the use case you've pointed out.

**Comment by raprasad** [comment]
Got it
