### ISSUE TITLE
"In Review" status needed in solr (MyData)

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#2315]
This will be a publication status facet for mydata

**Comment by pdurbin** [comment]
As was mentioned at #2366 the original mockups at https://iqssharvard.mybalsamiq.com/projects/accountdatalisting-dataverse/Account%20-%20Type%20Filter showed an "In Review" facet:
![account_-_type_filter_mybalsamiq_-_2015-09-09_14 13 49](https://cloud.githubusercontent.com/assets/21006/9770261/2b94c1ac-56fd-11e5-98a7-876d4851575f.png)

@eaquigley is the idea that the "In Review" facet would be visible on the homepage as well as MyData? If we show it on the homepage, I assume it's like the "Draft" facet in that you only see it if you're logged in. Is that right?

For my reference, here's a handy link to the [MyData FRD](https://docs.google.com/document/d/1xv_IKS1hWYUzX3GZOjHqGQ3BUBI7QH_2FekP90cexNA/edit?usp=sharing).

**Comment by eaquigley** [comment]
@pdurbin yes, it should be available both on the dataverse page and the my data page when a user is logged in

**Comment by pdurbin** [comment]
I pushed an experiment to a branch at 643d251 but I still need to make the MyData code flexible enough to handle a Publication Status facet that has a space in it such as "In Review".

**Comment by pdurbin** [comment]
@raprasad if you could pick up where we left off at https://github.com/IQSS/dataverse/commits/2315-in-review-pub-status-facet I'd appreciate it!

**Comment by raprasad** [comment]
@pdurbin turn over for code review; merging

**Comment by pdurbin** [comment]
42fc96e really hit the spot. Thanks, @raprasad ! Merged into 4.2. Passing to QA.

Here's how the new "In Review" facet/label looks (green per @mheppler) on the homepage and mydata page, respectively:

## Homepage

![root_dataverse_-_2015-09-10_13 54 41](https://cloud.githubusercontent.com/assets/21006/9796360/cc651f20-57c3-11e5-8100-dce1f4d51a71.png)

## MyData

![account_-_root_dataverse_-_2015-09-10_13 55 31](https://cloud.githubusercontent.com/assets/21006/9796369/d1fb6746-57c3-11e5-8fba-893027c7ba36.png)

@mheppler as always, please feel free to grab this out of QA if you want to make things more eyebally. I was thinking it might be nice to define the color in a common css file for both card types.

**Comment by pdurbin** [comment]
@mheppler as we discussed, I added "In Review" as a Boostrap label to the dataset page as well in 101e626. It's green like the others:

![finch_dataset_in_issue_2315_dataverse_-_issue2315_dataverse_-_2015-09-10_15 46 26](https://cloud.githubusercontent.com/assets/21006/9799132/578c4dbc-57d3-11e5-8fda-14d55cdda78e.png)

I'm passing this ticket to you, per your request, to look things over. If (like me) you were unclear on how to even get a dataset into "In Review", here's a handy link that helped me: http://guides.dataverse.org/en/4.1/user/dataset-management.html?highlight=submit%20for%20review#submit-for-review . Oh, that reminds me, "In Review" was developed in #832 and the FRD is here: [Contributor/Reviewer Workflow Requirements Document (FRD)](https://docs.google.com/document/d/1O5HhLgypYF9OSjCaujaEh-Vh9jieCF-3A0MlHnb7iQ8/edit?usp=sharing).

**Comment by pdurbin** [comment]
Bloops! In d656d7f I fixed the double "In Review" typo I made in the last commit. Here's a better screenshot:

![fix](https://cloud.githubusercontent.com/assets/21006/9799354/a6b4adb6-57d4-11e5-8fea-0377ba20f80c.png)

**Now** it's ready for @mheppler.

**Comment by mheppler** [comment]
Thank you for including the screenshots, @pdurbin. Everything looks kosher, and as was mocked up. Sending to QA.

**Comment by kcondon** [comment]
OK, in review facet works for both homepage and my data. Closing.
