### ISSUE TITLE
Dataverse Card: Show Count of Datasets + Dataverses within a Dataverse

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2319]
Carrying this over from #208. Discussed with @mcrosas to have this show on the card how many dataverses and datasets are in the dataverse. Will discuss with @mheppler to mock this up so it can be developed.

**Comment by pdurbin** [comment]
This is the drawing Mike gave me back in 2014 (see especially "view more" for the list of children):

![searchcardstype](https://user-images.githubusercontent.com/21006/194197638-e25765b8-1305-4ca0-a1c8-5209b2c1bd05.png)

We tried to get this working but as chronicled in #208 we had to rip it out for performance reasons.

Fast forward 8 years. Is anyone still interested in this?
