### ISSUE TITLE
Installation Guide: Updates from tickets sent to RT 

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2321]
Since releasing the code for 4.0, there have been several RT tickets that have come in with questions about installing. The installation guide should be updated to have the answers to these questions.

**Comment by pdurbin** [comment]
For RT, we've been using [a spreadsheet](https://docs.google.com/spreadsheets/d/1EWDwsj6eptQ7nEr-loLvdU7I6Tm2ljAplfNSVWR42i0/edit?usp=sharing) to list tickets in which people are installing Dataverse 4.

Naturally, https://groups.google.com/forum/#!forum/dataverse-community would be a good place to look for feedback as well.

Probably the Installation Guide needs a full reorg. @bencomp started working on a [Google Doc about a better hierarchy](https://docs.google.com/document/d/1GLky44JbtCNhGuavLXGEP8WPNdjbyHNxalEGjR78MaA/edit?usp=sharing) after chatting at http://irclog.iq.harvard.edu/dataverse/2015-07-07 but the more feedback the better, probably.

**Comment by kcondon** [comment]
@eaquigley @pdurbin I have been opening tickets with the installation guide as I find issues, either from helping users or from my recent testing of the installer related to other tickets. I usually discuss with Leonid first to better understand what it should be in case of failure.

**Comment by pdurbin** [comment]
There is a suggestion at #2288 to document which port Dataverse is running on (8080 by default).

**Comment by pdurbin** [comment]
I believe that all the feedback from RT has been entered as individual issues by @kcondon (thanks!) and I listed as many as I could find (with help from @mheppler .... hmm, that should be `@mHELPler` ha!) in my pull request at #2895

In short, I think we're covered, so I'm moving this issue to QA. Also, writing docs all day makes you slaphappy. I don't recommend it.

**Comment by kcondon** [comment]
Yep, closing.
