### ISSUE TITLE
html in 4.0: target attribute should be allowed for <a> tags

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2324]
Gustavo asked to have this

**Comment by raprasad** [comment]
See MarkupChecker.sanitizeBasicHTML

**Comment by raprasad** [comment]
fyi: no time to do this before end of week

**Comment by pdurbin** [comment]
All set. Passing to QA.

**Comment by dliburd** [comment]
Verified. Target attribute allowed in <a> tag
