### ISSUE TITLE
mydata bug: getting 1 result but no cards

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#2328]
part of #2302 

--- 

Solr is saying 1 result -- is card getting lost while formatting?
![role_permission_relationships_-_root_dataverse](https://cloud.githubusercontent.com/assets/1036060/8561743/ddca3146-24f7-11e5-8028-216070b595c5.png)

**Comment by pdurbin** [comment]
@raprasad @sekmiller does this problem ever happen with non-mydata search?

**Comment by raprasad** [comment]
Fixed.  Was pagination issue.
