### ISSUE TITLE
My Data: New user creates first dataverse, not datasets, does not appear yet in my data until dataset added.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2329]
My Data: New user creates first dataverse, not datasets, does not appear yet in my data until dataset added.

1. create user
2. create dataverse
3. go to my data, see no dv
4. add dataset
5. go to my data, see dv and dataset
6. add another dv, see that in my data
7. delete dataset, see neither dv in my data.

**Comment by sekmiller** [comment]
Fix checked in

**Comment by kcondon** [comment]
Dataverse doesn't appear at all now, even after adding dataset.

**Comment by sekmiller** [comment]
Fixed and checked in

**Comment by kcondon** [comment]
Fixed, closing.
