### ISSUE TITLE
My Data: Show Count for DVObject Types Even When Not Checked

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2332]
Requested during user testing of my data.

---

part of #2302

**Comment by raprasad** [comment]
@eaquigley 
Would it make a difference if these counts were retrieved a single time--when the user goes to the mydata page?  
e.g. If the person went to another part of dataverse and returned, the totals would be recalculated.

**Comment by raprasad** [comment]
Replaced by #2381
