### ISSUE TITLE
My Data: Spinner Continues after moving to different tab

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2335]
Discovered during usability testing:

When a user clicks on a checkbox in the my data then goes to a different tab, the spinner continues to run. This shouldn't happen.

**Comment by raprasad** [comment]
Recheck with latest code.  I'm not sure if this is still happening--the spinner also activates when switching tabs.

**Comment by kcondon** [comment]
I was not able to reproduce this, closing.
