### ISSUE TITLE
Error message after editing dataset name 

### ISSUE THREAD

**Issue by aawinburn** [IQSS/dataverse#2337]
If I edit the name of a dataset that's already uploaded, I get an error message (picture below) when I try to open the dataset in TwoRavens. The file was uploaded as .rdata.  

![error](https://cloud.githubusercontent.com/assets/9394843/8618931/a9fd5c04-26e0-11e5-9cc7-59cf28037443.png)

**Comment by pdurbin** [comment]
This issue was previously reported (and fixed) in #2250.

**Comment by eaquigley** [comment]
Passing to @kcondon to close since it was fixed in another ticket.

**Comment by kcondon** [comment]
Retested, works, closing.
