### ISSUE TITLE
My Data: When creating a new dataset in root dv, does not appear in my data.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2338]
When creating a new dataset in root dv, does not appear in my data.
1. create a new account
2. add dataset to root dv
3. check my data, nothin'
4. publish, check my data, nothin'
5. add file, check my data, no dataset but see file.

**Comment by raprasad** [comment]
first things to check:
-  Are the entityIds and parents being picked up in the postgres permission queries?
-  Are they included in the solr filter queries?
     - This line prints the filter queries: ```msgt("myDataFinder.getSolrFilterQueries(): " + myDataFinder.getSolrFilterQueries().toString());```
- If the solr query is correct, are the objects found?

**Comment by sekmiller** [comment]
Fixed and checked in

**Comment by kcondon** [comment]
OK works, closing
