### ISSUE TITLE
My Data: Unpublished draft of a published dataset does not show up as unpublished tag or filter.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2339]
Unpublished draft of a published dataset does not show up as unpublished tag or filter.

1. Create a dataset, publish
2. Create a draft of that dataset
3. Go to my data, see no unpublished tag on draft, click unpublished, see 0 count.

**Comment by sekmiller** [comment]
The "unpublished" label is only applied when there is no published version of the dataset.  If a draft was always "unpublished" then why have both labels.  This is working as designed.

**Comment by kcondon** [comment]
OK, this labeling behavior is consistent with how datasets use labels. Closing.
