### ISSUE TITLE
Notifications: Request access notification appears as object was deleted message.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2340]
When I request access to a restricted file in v2 of a published study, was public in v1, made restricted in v2, notification is sent to the creator but it says this:

The dataverse, dataset, or file for this notification has been deleted.July 10, 2015 4:21 PM EDT

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
