### ISSUE TITLE
My Data: When granted access to restricted file, the file does not appear in My Data as file downloader.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2341]
When granted access to restricted file, the file does not appear in My Data as file downloader.

1. Create restricted file
2. Request access by another user
3. Grant access
4. View My Data, notice no files are present.

**Comment by sekmiller** [comment]
This is fixed.  The roles displayed on the files needs some work.  Roles listed need work in general.

**Comment by kcondon** [comment]
This is working now but saw an issue with the grant notification: The dataverse, dataset, or file for this notification has been deleted.July 16, 2015 1:58 PM EDT 

Closing
