### ISSUE TITLE
My Data: When granted a role to dataset by another user, dataset does not appear in my data.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2342]
When granted a role to dataset by another user, dataset does not appear in my data.

1. User creates dataset
2. User grants another user contributor (or admin) role in that dataset
3. Check my data, dataset does not appear.

**Comment by sekmiller** [comment]
Could not recreate this.

**Comment by sekmiller** [comment]
Worked in Child of Root as well

**Comment by kcondon** [comment]
Does not work on dvn-build. Passing back.

**Comment by sekmiller** [comment]
Please re-try after the next build

**Comment by kcondon** [comment]
This is working now, probably an issue with build's schema.xml that was fixed yesterday. Closing.
