### ISSUE TITLE
My Data: User who has contrib role at parent dv gets admin role for dataset and child dv in listing.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2345]
User who has contrib role at parent dv gets admin role for dataset and child dv in listing.
1. Create a dataverse
2. Create a dataset
3. Create a child dataverse
4. Grant contributor role on the parent dv to another user.
5. Check my data on the other user and that user sees both the dataset and child dv and has admin role on both.

**Comment by sekmiller** [comment]
Fixed to display only those roles that apply to a given dvObject

**Comment by kcondon** [comment]
OK this is working. Saw another issue related to contributor but will open as a separate ticket/ question for Liz/Gustavo. Closing.
