### ISSUE TITLE
My Data: When assigning admin role to parent dv to user, they should not see sub dv due to "is root" setting.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2346]
When assigning admin role to parent dv to user, they should not see sub dv due to is root perm.
1. Create a parent dv
2. Create a child dv
3. Grant admin role to another user at parent dv
4. Go to my data as grantee user, see you are admin to child dv.
5. Click child dv, you are prompted to log in  (no real perms)
6. Check actual perms at child dv and see no admin role for grantee (as designed, refer to "is root" and search/ index discussions).

**Comment by sekmiller** [comment]
This is fixed and checked in

**Comment by kcondon** [comment]
Works, closing.
