### ISSUE TITLE
Rename 4.0.2 to 4.1 

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#2348]
We've decided to rename 4.0.2 to 4.1. We're drawing some inspiration from http://semver.org where MINOR from MAJOR.MINOR.PATCH means "add functionality" (such as MyData in #2302).

**Comment by mcrosas** [comment]
:+1:

**Comment by pdurbin** [comment]
For expediency we decided to continue to push to the 4.0.2 branch but I changed the pom.xml file and various Sphinx files in b098f78 and reconfigured Jenkins so that docs are being built in http://guides.dataverse.org/en/4.1/

@kcondon I'm passing this issue to QA. Please let me know if you need any assistance reconfiguring the job that deploys the war file to dvn-build (or any other job).

**Comment by kcondon** [comment]
Ok, works, closing.
