### ISSUE TITLE
Dataverse Alias shows in the URL

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#235]
---

Author Name: **Elizabeth Quigley** (@eaquigley)
Original Redmine Issue: 3649, https://redmine.hmdc.harvard.edu/issues/3649
Original Date: 2014-03-06
Original Assignee: Gustavo Durand

---

Currently, the alias a user enters in for a dataverse doesn't appear in the URL so this ticket is a reminder that it needs to happen.

https://trello.com/c/ZUbdgjRc/20-urls has a link to Pretty URLs for JavaServer Faces and Java Application Servers | OCPsoft - http://ocpsoft.org/prettyfaces/

**Comment by pdurbin** [comment]
Related: #2900
