### ISSUE TITLE
Add DownloadFile permisison to Member role

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#2350]

**Comment by scolapasta** [comment]
Done. (I also ran this in production, as it was needed to support a customer)

**Comment by kcondon** [comment]
@scolapasta Can you provide more details on how I set this up and test? Thx

**Comment by scolapasta** [comment]
On a new db, just verify that Member has DownloadFile permission. For an existing db, I added the update to the script (which I already ran in production, but wrote in a way that it doesn't cause any issue to run multiple times).

**Comment by kcondon** [comment]
Tested script, works, now need to test new db.

**Comment by kcondon** [comment]
OK, verified on new installation, closing.
