### ISSUE TITLE
User Guide still references 4.0.2

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#2351]
The following docs reference version 4.0.2 but it has been renamed to 4.1 in #2348:

- http://guides.dataverse.org/en/4.1/user/dataverse-management.html
- http://guides.dataverse.org/en/4.1/user/find-use-data.html

My preference would be to avoid mentioning specify versions anyway. Perhaps a link to a GitHub issue would be better:

```
$ cd source/user
(dataverse_docs)murphy:user pdurbin$ grep 4.0.2 -B2 *.rst
dataverse-management.rst-Linked Dataverses + Linked Datasets
dataverse-management.rst-======================================================
dataverse-management.rst:Coming soon in 4.0.2!
--
find-use-data.rst-Saved Search
find-use-data.rst---------------------
find-use-data.rst:Coming soon in 4.0.2!
```

@eaquigley I'm happy to let you decide on the wording so I'll give this to you.

**Comment by eaquigley** [comment]
done. passing to qa.

**Comment by kcondon** [comment]
References removed. Closing.
