### ISSUE TITLE
When create new account and viewing under MY Account: Notification should say "Welcome to DV and a link to the user guide."

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2352]
Currently wrong message displayed (via Liz data science lunch talk demo)

**Comment by eaquigley** [comment]
@sekmiller please change this notification to be:

Welcome to Harvard Dataverse! Need help? Check out the user guide (insert link to user guide) or post in the Dataverse Community Google Group (insert link to Google Group).

**Comment by sekmiller** [comment]
This should be quick and low-risk.  I'll have something shortly.

**Comment by sekmiller** [comment]
@eaquigley I think we need to take "Harvard" out of the notification so it's generic for other installations.

**Comment by eaquigley** [comment]
can we make it dynamic?

**Comment by sekmiller** [comment]
Display Name of the Root Dataverse? Let me see.

**Comment by eaquigley** [comment]
Yup! Thanks!

**Comment by sekmiller** [comment]
All set.  Kevin will make a build so that this can be verified.

**Comment by eaquigley** [comment]
tested on dvn-build. works beautifully! closing ticket.
