### ISSUE TITLE
Permissions: have "Users/Groups" be expanded by default

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#2354]
When editing permissions the most useful/unique information is under "Users/Groups" (it shows the roles assigned) but it's collapsed by default. In my opinion it should be expanded by default:

![dv2](https://cloud.githubusercontent.com/assets/21006/8680712/1ff98da8-2a31-11e5-8278-67ce42480cb1.png)

I've been chatting with @scolapasta and @eaquigley about this.

**Comment by bencomp** [comment]
Related to #2255

**Comment by mheppler** [comment]
Improved messaging on the dataverse and file Permissions pages. Worked with @eaquigley on an improved placement and wording of the help text, mainly by moving the brief section descriptions to the panel header, so the settings contained in each are more obvious upon first viewing the page.

With these changes in place, I am assigning this to @eaquigley to review if further changes are needed to the UI of the Permissions pages.

**Comment by pdurbin** [comment]
I just merged this into the 4.3 branch per my comment at https://github.com/IQSS/dataverse/issues/2852#issuecomment-170628537

I'm giving this the 4.3 milestone. Heads up @eaquigley since this issue is in your name.

**Comment by scolapasta** [comment]
The "develop" branch was created from 4.3 so this fix is already in develop.

**Comment by kcondon** [comment]
OK, I see the added help text:  All the users and groups that have access to your dataverse. for the Users/Groups section. 

Since this was about opening the section should this be decided on by @eaquigley as Mike indicated?

**Comment by eaquigley** [comment]
its a great idea to have it open by default but really only works when there aren't many users with roles. once you get over 10-15, that page is going to turn really long and the role descriptions at the bottom won't be seen. so if there could be logic that its open by default if there are less than 10 or 15 great. removing from 4.2.4 as there needs to be some more investigation into this.

**Comment by pdurbin** [comment]
I'll bow out of this fight and let the UI/UX folks decide what to do, if anything. Closing.
