### ISSUE TITLE
List of subjects in Advanced Search is in no order

### ISSUE THREAD

**Issue by mcrosas** [IQSS/dataverse#2355]
We should list the subjects in Advanced alphabetically

**Comment by kcondon** [comment]
This has been fixed.

**Comment by posixeleni** [comment]
@kcondon sent pull request to resolve this issue.

On Tue, Apr 5, 2016 at 12:34 PM, kcondon <notifications@github.com> wrote:

> Reopened #2355
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_issues_2355&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=OiTcIL_jSSCUW82Gf-OSkgnZLbG2Yt87eT87BdLiP54&m=vgYRDdW4YhF_pp99uxa1jGhP9wk46Ae3U5KPyKViipU&s=_Ye4Lm990pybnSa87x0Bu54-CTkou56cWLaIMZOLArA&e=>
> .
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_issues_2355-23event-2D615463574&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=OiTcIL_jSSCUW82Gf-OSkgnZLbG2Yt87eT87BdLiP54&m=vgYRDdW4YhF_pp99uxa1jGhP9wk46Ae3U5KPyKViipU&s=Xz-D8LwIOR6i2E5ncBMED1xO7zVEawUFYk40k8cx3HM&e=>
>



-- 

Eleni Castro
Research Coordinator, Data Curation and Outreach
IQSS, Harvard University
617-496-0703
http://www.iq.harvard.edu/people/eleni-castro
http://orcid.org/0000-0001-9767-8536


~Got Data? Check out the Dataverse Project. <http://dataverse.org/>~

**Comment by posixeleni** [comment]
QA should test that subjects are alphabetical in:
- [ ] Advance Search
- [ ] Create Dataset
- [ ] Edit Dataset

**Comment by kcondon** [comment]
@posixeleni This does not seem to be alphabetized.

**Comment by kcondon** [comment]
OK, works, just needed to run the setup scripts. Closing.
