### ISSUE TITLE
Installer for TwoRavens

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#2359]
I have a dev ticket for this in the TwoRavens queue: 
https://github.com/IQSS/TwoRavens/issues/44

- this ticket is for tracking and QAing the issue on our side, so that it's done in time for our 4.1 release.

**Comment by landreev** [comment]
OK, committed the fixed script. Updated the ticket in the TwoRavens github queue. 
Still need to make a couple of changes to the installer guide in our (dataverse) documentation. 
Will move this into QA once that's done.

**Comment by landreev** [comment]
Both installer scripts should now be working: 
The shell script installs the required R packages; 
And the script supplied with TwoRavens that configures the app and rApache. 
The instructions in the installation guide should be accurate too now.

**Comment by kcondon** [comment]
Installer is working also docs updated. Closing.
