### ISSUE TITLE
My Data: Contributor role assigned at dv should display both dv and child datasets as contributor role.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2360]
Update:
Discussed with @eaquigley and the intuitive approach seems better:
If someone is assigned the Contributor role at the dv level, display the dv and the child datasets, all showing contributor role. The dv is shown to indicate the scope and if there are a bunch of datasets they can follow the link directly to the dv and see all. The datasets are shown so they can directly access them to edit. If @scolapasta or @sekmiller think this is incorrect, please weigh in.

--------------------------------------------------------------------------------------------------------------------------
There is some confusion for me around the Contributor role since it is not the same as the one in v3.6. As a result, it is a little tricky making sure My Data accurately reflects what this means.

My understanding of the Contributor role is it allows editing on an existing dataset. It can be assigned either at the dataset or dataverse level. At the dataset level, it is a direct assignment and that dataset should appear in My Data, I think. When it is assigned at at Dataverse, it means that this user can edit any dataset that currently exists in the dataverse but not create one.

The tricky part is they do not have access to an unpublished dataverse. Also, if assigned at the dataverse level, it is an indirect permission on any current and future datasets, not really on the dataverse itself -they do not see an add or edit button in the dv in othr words.

So, Gustavo suggested we do not show this role at all on the My Data page. @eaquigley @scolapasta @sekmiller what do you guys think?

Currently it shows the dataverse to which you've granted Contributor access though it does not display the role and it is not really accurate since you can't do anything directly on the dv.

**Comment by sekmiller** [comment]
Fixed and checked in

**Comment by kcondon** [comment]
OK works, closing.
