### ISSUE TITLE
Notifications: File access request has  object deleted message.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2361]
When a user requests access to a restricted file, the admin receives a notification that says the object to which the message pertains has been deleted:

The dataverse, dataset, or file for this notification has been deleted.July 16, 2015 1:58 PM EDT

**Comment by sekmiller** [comment]
Fix for this has been checked in

**Comment by dliburd** [comment]
Verified: User request notification now displays properly.
