### ISSUE TITLE
My Data: File should appear if users have role with DownloadFile permission

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2362]
Currently in My Data, only files where someone has directly assigned the File Downloader role on that particular file appears, as is the case with the request/ grant restricted file access workflow.

@eaquigley Thinks that any role with DownloadFile applied at either the dataverse or dataset level should cause files affected by those permissions to appear in My Data:

Admin, Curator,Contributor, File Downloader, Member

**Comment by sekmiller** [comment]
Fix checked in

**Comment by kcondon** [comment]
OK, works, closing
