### ISSUE TITLE
My Data: Provide ability to add data per FRD

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2364]
The FRD for My Data specifies a use case for adding data, presumably with the same add data button.

**Comment by sekmiller** [comment]
@eaquigley - If user does not have permission to add to Root DV should this button appear?  And if so, but the user has add permission to several DV's how will the determination be made of where the data will be added?

**Comment by eaquigley** [comment]
@sekmiller i say leave the add data button out for now. we have no way to communicate well to the users where they are about to deposit (at the root) and there is no way for them to select a dataverse they have permissions to for this. this can be postponed till we have that worked out.

**Comment by kcondon** [comment]
We've decided not to implement this. Closing.
