### ISSUE TITLE
My Data: Does not display an entirely deaccessioned dataset.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2365]
When a dataset has all versions deaccessioned, it does not appear in My Data. I'm thinking it should unless @eaquigley or @scolapasta thinks otherwise?

If only a version is deaccessioned, the non deaccesioned versions are still listed as expected.

**Comment by sekmiller** [comment]
Selecting a dataset with a status of deaccessioned is not currently supported by the MyData queries.  (Only 'draft' 'unpublished' and 'published' are allowed.) When I removed the restriction, the deaccessioned DS shows up in the MyData listing, but the special formatting we use in the regular search include fragment is missing.

**Comment by sekmiller** [comment]
Assigning to Raman as he is working on it...

**Comment by raprasad** [comment]
There is now a deaccessioned checkbox

**Comment by kcondon** [comment]
OK, fully deaccessioned datasets now appear using the deaccesioned facet, closing.
