### ISSUE TITLE
My Data: In Review status specified by mockup is not displayed.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2366]
Not sure whether this was a definite requirement but the In Review status appears in a mockup but does not appear in My Data nor in the UI in general, other than a grayed out button saying submitted for review.

**Comment by scolapasta** [comment]
To support this, changes need to made in indexing - this is issue #2315 and once there, should show as a facet.

Sending this one back as a duplicate.

**Comment by kcondon** [comment]
OK, closing as a duplicate.
