### ISSUE TITLE
Guestbook: Allow Authors to create guestbooks for linked datasets that may belong to a journal dataverse.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2371]
See RT 219152 for details. 

The Dataset was created by the author and submitted to a journal dataverse. The author then linked the dataset  back to their personal dataverse but wants to post a guestbook and review download data for the dataset.

Merce suggested we track this feature since it has relevance for the upcoming Datatags functionality:

"consider a workflow for authors to set up or request a "guestbook" that needs to be approved by journals (or more generally by the dataset owner) or something like that. I think this will be even more relevant with DataTags support, so it's worth tracking it."

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
