### ISSUE TITLE
My Data: Make all facet links behave like dataverse/dataset links where clicking selects and clears others.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2372]
Liz confirmed she would like the behavior of all the facet links to act the same as the dataverse/dataset/files facets where checkbox adds the facet, clicking the link selects that facet exclusively.

Actual conversation:

Should I submit a ticket to request My Data role filters act like datavese/ dataset links as in they select rather than deselect?

Yeah go ahead. I think it's important to do it for super users or people with multiple roles

Ah... should all filter links act that way for consistency? I'm guessing yes.

Yeah. I've gone back and forth on it because we need both the checkbox and the filtering options. The data represented with these facets is different in that you don't want to eliminate any options by default like you would on the homepage, you want to be able to have the option to limit and to add to the results. I think for consistency sake it does make sense though to have them all behave like the DV object type facet however it gets weird when there is only one role, Admin, as I saw during testing was common.

@sekmiller Spoke with Mike, it's a go.

**Comment by sekmiller** [comment]
Sorry.  forgot about this one.  Can you take a look @raprasad?

**Comment by kcondon** [comment]
OK, works great! Closing.
