### ISSUE TITLE
Notifications: Admin not receiving email notification when a user request data access.

### ISSUE THREAD

**Issue by dliburd** [IQSS/dataverse#2373]
The Dataverse is not sending email notifications to dataverse admin when a user request access to a restricted data file. A notification does appear within Dataverse site but no email is sent to admin.  However admin does receive an email when a dataverse is created so we do know that emails are sent in other situations. Requester also does receive an email notification if access request is rejected.

**Comment by kcondon** [comment]
Request access/ granted/reject email and notifications are being sent. Closing.
