### ISSUE TITLE
Dataverse Theme Logo: Need info message with guidelines on acceptable file types

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2374]
currently,  accepted file type info only appears after submitting an unaccepted image type---should appear as part of the existing description on maximum display, etc...should show up before an incorrect image type is uploaded

**Comment by eaquigley** [comment]
Added to user guide here: https://github.com/IQSS/dataverse/blob/4.0.2/doc/sphinx-guides/source/user/dataverse-management.rst on file types and sizes.

**Comment by mheppler** [comment]
Updated info text on the Theme + Widgets page for the Logo Image upload. Fixed typos in the User Guide for Dataverse Management page.

**Comment by kcondon** [comment]
Info is in place in both the UI and doc. Closing.
