### ISSUE TITLE
Notifications: Page reformats and does not refresh when delete notification when many are on page.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2375]
When there are a lot of online notifications, >20? Deleting them does not work smoothly: the page reformats so the "X" appears below the message and the page does not refresh so show the notification was removed, though refreshing the page shows it has. This is confusing when you have a lot of notifications and you just want to remove them.

**Comment by sekmiller** [comment]
Fix checked in

**Comment by kcondon** [comment]
Works better but still has the no refresh behavior with lots of messages, especially those at the top of the list.

**Comment by kcondon** [comment]
Issue unique to this ticket was fixed, now a dupe of #2252
