### ISSUE TITLE
Prod. Google Analytics ID also on dvn-build

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#2376]
The dvn-build machine is using the same google analytics id as production:

- The google analytics are not accurate and include pages not yet in production.
- The analytics may be showing **better than actual** average page speed b/c there's little data in dvn-build system.

**Fix:** remove the google analytics id from the dvn-build settings table.

**Comment by kcondon** [comment]
OK, key was removed and the setup-optional-harvard script had the key commented out. Closing.
