### ISSUE TITLE
MyData: Change "filter" language to "search"

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#2379]
button: "filter" -> "Search"
input box: "Search my data"

**Comment by kcondon** [comment]
I think Liz said button-> "Find", like on the homepage.

**Comment by kcondon** [comment]
Find button does not seem to be working.

**Comment by raprasad** [comment]
I just checked in the fix for the button.

**Comment by kcondon** [comment]
Fix doesn't work for FF v39, works for Chrome.

**Comment by kcondon** [comment]
I had deleted cache, no go but then did shift+reload and worked, D'oh! Closing.
