### ISSUE TITLE
mydata: search button, check all boxes

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#2380]
When using the search box, select all check boxes before submitting the ajax form.
All checkboxes selected when user:

- presses 'enter' key in search box
- clicks 'search' button

**Comment by raprasad** [comment]
There's a bug in Chrome where it tries to submit another form on the page--e.g. functionality works for a second and then fails

**Comment by kcondon** [comment]
Ok, search selects all checkboxes. Did not see the Chrome issue but saw an issue with FF and reported in another ticket. Closing.
