### ISSUE TITLE
mydata: dvobject and publication status counts

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#2381]
If:
  1. box isn't checked AND
  1. count is unavailable or "0"

Then:
   - show nothing "", instead of "(0)"
<img width="1252" alt="account_-_cool_dataverse" src="https://cloud.githubusercontent.com/assets/1036060/8808527/1cb31512-2fb1-11e5-8bde-252185d51378.png">

**Comment by kcondon** [comment]
Works as described, closing.
