### ISSUE TITLE
Migrated dataset contains handle and no doi: some datasets migrated with unregistered handles and no doi

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2383]
Libbie contacted us about one dataset in particular that she could not publish. She received both "unregistered handle and publishing dataset" message when she selected to "publish" but neither  the "registration"  or "publishing" function worked. 

Stephen noticed the dataset contained a handle and no doi. We followed up with Libbie who confirmed the dataset was created on our interface and prior to 4.0 migration.

dataset example:  https://dataverse.harvard.edu/dataset.xhtml?persistentId=hdl:1902.1/M474V1&version=DRAFT

**Comment by sbarbosadataverse** [comment]
@sekmiller 
Libbie sent me a list of all datasets in their dataverse that have handles and not dois

http://hdl.handle.net/1902.1/M099V1

http://hdl.handle.net/1902.1/M098V1

http://hdl.handle.net/1902.1/M097V1

http://hdl.handle.net/1902.1/M089V1

http://hdl.handle.net/1902.1/M086V1

http://hdl.handle.net/1902.1/M084V1

http://hdl.handle.net/1902.1/M081V1

http://hdl.handle.net/1902.1/M080V1

http://hdl.handle.net/1902.1/M967V1

http://hdl.handle.net/1902.1/M921V1

http://hdl.handle.net/1902.1/M920V1
http://hdl.handle.net/1902.1/M919V1

http://hdl.handle.net/1902.1/M918V1

http://hdl.handle.net/1902.1/M917V1

http://hdl.handle.net/1902.1/M916V1

http://hdl.handle.net/1902.1/M915V1

http://hdl.handle.net/1902.1/M911V1
http://hdl.handle.net/1902.1/M910V1
http://hdl.handle.net/1902.1/M908V1
http://hdl.handle.net/1902.1/M902V1
http://hdl.handle.net/1902.1/M895V1

**Comment by sekmiller** [comment]
Are these all unpublished?


On Jul 23, 2015, at 7:01 AM, sbarbosadataverse <notifications@github.com<mailto:notifications@github.com>> wrote:


@sekmiller<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sekmiller&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=JLoYUzC47p12YrOEH7S_pT7r0HQJRKoxeOnoIrLhXxk&s=k2wl0FOQ3yW2AMqjdue8BgAusI57nDOZ5z1c46af1T0&e=>
Libbie sent me a list of all datasets in their dataverse that have handles and not dois

http://hdl.handle.net/1902.1/M099V1<https://urldefense.proofpoint.com/v2/url?u=http-3A__hdl.handle.net_1902.1_M099V1&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=JLoYUzC47p12YrOEH7S_pT7r0HQJRKoxeOnoIrLhXxk&s=y2etFEi31jCAlZNqLdyNmBcUV0adG8FIX3xu_BCvH0M&e=>

http://hdl.handle.net/1902.1/M098V1<https://urldefense.proofpoint.com/v2/url?u=http-3A__hdl.handle.net_1902.1_M098V1&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=JLoYUzC47p12YrOEH7S_pT7r0HQJRKoxeOnoIrLhXxk&s=u5cmEbmOT3IdN8wFX9zIP_qfTsTNTKzNA3G32tUS7R8&e=>

http://hdl.handle.net/1902.1/M097V1<https://urldefense.proofpoint.com/v2/url?u=http-3A__hdl.handle.net_1902.1_M097V1&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=JLoYUzC47p12YrOEH7S_pT7r0HQJRKoxeOnoIrLhXxk&s=rApJaVpI4LHZ5eWIAhv8nf_Ao0HqaGINYvZjLxa4H10&e=>

http://hdl.handle.net/1902.1/M089V1<https://urldefense.proofpoint.com/v2/url?u=http-3A__hdl.handle.net_1902.1_M089V1&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=JLoYUzC47p12YrOEH7S_pT7r0HQJRKoxeOnoIrLhXxk&s=5URD6cIft96J0KO1eebjEQ0TUsEJiTMgoDSPwIWCAWw&e=>

http://hdl.handle.net/1902.1/M086V1<https://urldefense.proofpoint.com/v2/url?u=http-3A__hdl.handle.net_1902.1_M086V1&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=JLoYUzC47p12YrOEH7S_pT7r0HQJRKoxeOnoIrLhXxk&s=Y7_nMrAU56HKzPFn8QXzEwPb9bfnOPDDyDl61v9WAy0&e=>

http://hdl.handle.net/1902.1/M084V1<https://urldefense.proofpoint.com/v2/url?u=http-3A__hdl.handle.net_1902.1_M084V1&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=JLoYUzC47p12YrOEH7S_pT7r0HQJRKoxeOnoIrLhXxk&s=hEyPo8KnSHGRM1EAfHQEd5fqib6LUq9pkvUBPzpLxGo&e=>

http://hdl.handle.net/1902.1/M081V1<https://urldefense.proofpoint.com/v2/url?u=http-3A__hdl.handle.net_1902.1_M081V1&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=JLoYUzC47p12YrOEH7S_pT7r0HQJRKoxeOnoIrLhXxk&s=fLhMrSvZujo3YI5-l5ipIDOFCMlLvmh9NDShNb3dUuc&e=>

http://hdl.handle.net/1902.1/M080V1<https://urldefense.proofpoint.com/v2/url?u=http-3A__hdl.handle.net_1902.1_M080V1&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=JLoYUzC47p12YrOEH7S_pT7r0HQJRKoxeOnoIrLhXxk&s=8OVuNoWo3FvIExkER3-k3VxL-flTJ5VBJLnl2Mqi_Fs&e=>

http://hdl.handle.net/1902.1/M967V1<https://urldefense.proofpoint.com/v2/url?u=http-3A__hdl.handle.net_1902.1_M967V1&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=JLoYUzC47p12YrOEH7S_pT7r0HQJRKoxeOnoIrLhXxk&s=Mjxn_-aQmjI3_rf-6tsP9zp0WuzdXi5cRaR59VgT9CA&e=>

http://hdl.handle.net/1902.1/M921V1<https://urldefense.proofpoint.com/v2/url?u=http-3A__hdl.handle.net_1902.1_M921V1&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=JLoYUzC47p12YrOEH7S_pT7r0HQJRKoxeOnoIrLhXxk&s=KBn8a7CztXd2y9juC6O77UA3JNKTOY4-_lOoqbszdTk&e=>

http://hdl.handle.net/1902.1/M920V1<https://urldefense.proofpoint.com/v2/url?u=http-3A__hdl.handle.net_1902.1_M920V1&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=JLoYUzC47p12YrOEH7S_pT7r0HQJRKoxeOnoIrLhXxk&s=D-x-S_FXC5zycnxBi0JzLOA9GYBXubjET7YRscE7OwI&e=>
http://hdl.handle.net/1902.1/M919V1<https://urldefense.proofpoint.com/v2/url?u=http-3A__hdl.handle.net_1902.1_M919V1&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=JLoYUzC47p12YrOEH7S_pT7r0HQJRKoxeOnoIrLhXxk&s=XmY4ndiY8OJo1sNJfSFHfjZ8ZMuNdJLo9XrMCeYP6oc&e=>

http://hdl.handle.net/1902.1/M918V1<https://urldefense.proofpoint.com/v2/url?u=http-3A__hdl.handle.net_1902.1_M918V1&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=JLoYUzC47p12YrOEH7S_pT7r0HQJRKoxeOnoIrLhXxk&s=9sTVnNuKuZTQC4auFwng21zsqjhhmrPAIYTfMy7C9Uk&e=>

http://hdl.handle.net/1902.1/M917V1<https://urldefense.proofpoint.com/v2/url?u=http-3A__hdl.handle.net_1902.1_M917V1&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=JLoYUzC47p12YrOEH7S_pT7r0HQJRKoxeOnoIrLhXxk&s=XGxTAUM7RmmdXBB3Q3dSZLIB9tIrk5mAwCBvOZbzMgE&e=>

http://hdl.handle.net/1902.1/M916V1<https://urldefense.proofpoint.com/v2/url?u=http-3A__hdl.handle.net_1902.1_M916V1&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=JLoYUzC47p12YrOEH7S_pT7r0HQJRKoxeOnoIrLhXxk&s=yq9653WmMsgcuYLwXheF_r6KNgnjrK52JUXnWSX6AdQ&e=>

http://hdl.handle.net/1902.1/M915V1<https://urldefense.proofpoint.com/v2/url?u=http-3A__hdl.handle.net_1902.1_M915V1&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=JLoYUzC47p12YrOEH7S_pT7r0HQJRKoxeOnoIrLhXxk&s=uiD4y0mgz95WoF2o0ZmnMHQfNZYLDp1rDHZB3eW_yIA&e=>

http://hdl.handle.net/1902.1/M911V1<https://urldefense.proofpoint.com/v2/url?u=http-3A__hdl.handle.net_1902.1_M911V1&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=JLoYUzC47p12YrOEH7S_pT7r0HQJRKoxeOnoIrLhXxk&s=kXqOp70p_2mTx-dS5n8Jhenw-KQTvu_gNt9JjFEuJr0&e=>
http://hdl.handle.net/1902.1/M910V1<https://urldefense.proofpoint.com/v2/url?u=http-3A__hdl.handle.net_1902.1_M910V1&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=JLoYUzC47p12YrOEH7S_pT7r0HQJRKoxeOnoIrLhXxk&s=t7JbQ0BcmRllEaVL7GqJy0lG3n2VRuiPQRIqwKpY4A4&e=>
http://hdl.handle.net/1902.1/M908V1<https://urldefense.proofpoint.com/v2/url?u=http-3A__hdl.handle.net_1902.1_M908V1&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=JLoYUzC47p12YrOEH7S_pT7r0HQJRKoxeOnoIrLhXxk&s=S9j8ZtyjNexbX4JgYqSee9uOGE1-YuMs9l6y-9MLW3Q&e=>
http://hdl.handle.net/1902.1/M902V1<https://urldefense.proofpoint.com/v2/url?u=http-3A__hdl.handle.net_1902.1_M902V1&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=JLoYUzC47p12YrOEH7S_pT7r0HQJRKoxeOnoIrLhXxk&s=R07aQlBpLRVD8xhnTgnOQfkYqxbeBrDV5xqfAyLV8yY&e=>
http://hdl.handle.net/1902.1/M895V1<https://urldefense.proofpoint.com/v2/url?u=http-3A__hdl.handle.net_1902.1_M895V1&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=JLoYUzC47p12YrOEH7S_pT7r0HQJRKoxeOnoIrLhXxk&s=7TcpNEXDy4IwpUeVhx75YJx87WDv4At_7pmV6vQ5oJw&e=>

**Comment by sbarbosadataverse** [comment]
appears so--they are unpublished.

On Thu, Jul 23, 2015 at 10:05 AM, Stephen Kraffmiller <
notifications@github.com> wrote:

> Are these all unpublished?
>
>
> On Jul 23, 2015, at 7:01 AM, sbarbosadataverse <notifications@github.com
> <mailto:notifications@github.com>> wrote:
>
>
> @sekmiller<
> https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sekmiller&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=JLoYUzC47p12YrOEH7S_pT7r0HQJRKoxeOnoIrLhXxk&s=k2wl0FOQ3yW2AMqjdue8BgAusI57nDOZ5z1c46af1T0&e=
> >
> Libbie sent me a list of all datasets in their dataverse that have handles
> and not dois
>
> http://hdl.handle.net/1902.1/M099V1<
> https://urldefense.proofpoint.com/v2/url?u=http-3A__hdl.handle.net_1902.1_M099V1&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=JLoYUzC47p12YrOEH7S_pT7r0HQJRKoxeOnoIrLhXxk&s=y2etFEi31jCAlZNqLdyNmBcUV0adG8FIX3xu_BCvH0M&e=
> >
>
> http://hdl.handle.net/1902.1/M098V1<
> https://urldefense.proofpoint.com/v2/url?u=http-3A__hdl.handle.net_1902.1_M098V1&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=JLoYUzC47p12YrOEH7S_pT7r0HQJRKoxeOnoIrLhXxk&s=u5cmEbmOT3IdN8wFX9zIP_qfTsTNTKzNA3G32tUS7R8&e=
> >
>
> http://hdl.handle.net/1902.1/M097V1<
> https://urldefense.proofpoint.com/v2/url?u=http-3A__hdl.handle.net_1902.1_M097V1&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=JLoYUzC47p12YrOEH7S_pT7r0HQJRKoxeOnoIrLhXxk&s=rApJaVpI4LHZ5eWIAhv8nf_Ao0HqaGINYvZjLxa4H10&e=
> >
>
> http://hdl.handle.net/1902.1/M089V1<
> https://urldefense.proofpoint.com/v2/url?u=http-3A__hdl.handle.net_1902.1_M089V1&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=JLoYUzC47p12YrOEH7S_pT7r0HQJRKoxeOnoIrLhXxk&s=5URD6cIft96J0KO1eebjEQ0TUsEJiTMgoDSPwIWCAWw&e=
> >
>
> http://hdl.handle.net/1902.1/M086V1<
> https://urldefense.proofpoint.com/v2/url?u=http-3A__hdl.handle.net_1902.1_M086V1&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=JLoYUzC47p12YrOEH7S_pT7r0HQJRKoxeOnoIrLhXxk&s=Y7_nMrAU56HKzPFn8QXzEwPb9bfnOPDDyDl61v9WAy0&e=
> >
>
> http://hdl.handle.net/1902.1/M084V1<
> https://urldefense.proofpoint.com/v2/url?u=http-3A__hdl.handle.net_1902.1_M084V1&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=JLoYUzC47p12YrOEH7S_pT7r0HQJRKoxeOnoIrLhXxk&s=hEyPo8KnSHGRM1EAfHQEd5fqib6LUq9pkvUBPzpLxGo&e=
> >
>
> http://hdl.handle.net/1902.1/M081V1<
> https://urldefense.proofpoint.com/v2/url?u=http-3A__hdl.handle.net_1902.1_M081V1&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=JLoYUzC47p12YrOEH7S_pT7r0HQJRKoxeOnoIrLhXxk&s=fLhMrSvZujo3YI5-l5ipIDOFCMlLvmh9NDShNb3dUuc&e=
> >
>
> http://hdl.handle.net/1902.1/M080V1<
> https://urldefense.proofpoint.com/v2/url?u=http-3A__hdl.handle.net_1902.1_M080V1&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=JLoYUzC47p12YrOEH7S_pT7r0HQJRKoxeOnoIrLhXxk&s=8OVuNoWo3FvIExkER3-k3VxL-flTJ5VBJLnl2Mqi_Fs&e=
> >
>
> http://hdl.handle.net/1902.1/M967V1<
> https://urldefense.proofpoint.com/v2/url?u=http-3A__hdl.handle.net_1902.1_M967V1&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=JLoYUzC47p12YrOEH7S_pT7r0HQJRKoxeOnoIrLhXxk&s=Mjxn_-aQmjI3_rf-6tsP9zp0WuzdXi5cRaR59VgT9CA&e=
> >
>
> http://hdl.handle.net/1902.1/M921V1<
> https://urldefense.proofpoint.com/v2/url?u=http-3A__hdl.handle.net_1902.1_M921V1&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=JLoYUzC47p12YrOEH7S_pT7r0HQJRKoxeOnoIrLhXxk&s=KBn8a7CztXd2y9juC6O77UA3JNKTOY4-_lOoqbszdTk&e=
> >
>
> http://hdl.handle.net/1902.1/M920V1<
> https://urldefense.proofpoint.com/v2/url?u=http-3A__hdl.handle.net_1902.1_M920V1&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=JLoYUzC47p12YrOEH7S_pT7r0HQJRKoxeOnoIrLhXxk&s=D-x-S_FXC5zycnxBi0JzLOA9GYBXubjET7YRscE7OwI&e=
> >
> http://hdl.handle.net/1902.1/M919V1<
> https://urldefense.proofpoint.com/v2/url?u=http-3A__hdl.handle.net_1902.1_M919V1&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=JLoYUzC47p12YrOEH7S_pT7r0HQJRKoxeOnoIrLhXxk&s=XmY4ndiY8OJo1sNJfSFHfjZ8ZMuNdJLo9XrMCeYP6oc&e=
> >
>
> http://hdl.handle.net/1902.1/M918V1<
> https://urldefense.proofpoint.com/v2/url?u=http-3A__hdl.handle.net_1902.1_M918V1&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=JLoYUzC47p12YrOEH7S_pT7r0HQJRKoxeOnoIrLhXxk&s=9sTVnNuKuZTQC4auFwng21zsqjhhmrPAIYTfMy7C9Uk&e=
> >
>
> http://hdl.handle.net/1902.1/M917V1<
> https://urldefense.proofpoint.com/v2/url?u=http-3A__hdl.handle.net_1902.1_M917V1&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=JLoYUzC47p12YrOEH7S_pT7r0HQJRKoxeOnoIrLhXxk&s=XGxTAUM7RmmdXBB3Q3dSZLIB9tIrk5mAwCBvOZbzMgE&e=
> >
>
> http://hdl.handle.net/1902.1/M916V1<
> https://urldefense.proofpoint.com/v2/url?u=http-3A__hdl.handle.net_1902.1_M916V1&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=JLoYUzC47p12YrOEH7S_pT7r0HQJRKoxeOnoIrLhXxk&s=yq9653WmMsgcuYLwXheF_r6KNgnjrK52JUXnWSX6AdQ&e=
> >
>
> http://hdl.handle.net/1902.1/M915V1<
> https://urldefense.proofpoint.com/v2/url?u=http-3A__hdl.handle.net_1902.1_M915V1&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=JLoYUzC47p12YrOEH7S_pT7r0HQJRKoxeOnoIrLhXxk&s=uiD4y0mgz95WoF2o0ZmnMHQfNZYLDp1rDHZB3eW_yIA&e=
> >
>
> http://hdl.handle.net/1902.1/M911V1<
> https://urldefense.proofpoint.com/v2/url?u=http-3A__hdl.handle.net_1902.1_M911V1&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=JLoYUzC47p12YrOEH7S_pT7r0HQJRKoxeOnoIrLhXxk&s=kXqOp70p_2mTx-dS5n8Jhenw-KQTvu_gNt9JjFEuJr0&e=
> >
> http://hdl.handle.net/1902.1/M910V1<
> https://urldefense.proofpoint.com/v2/url?u=http-3A__hdl.handle.net_1902.1_M910V1&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=JLoYUzC47p12YrOEH7S_pT7r0HQJRKoxeOnoIrLhXxk&s=t7JbQ0BcmRllEaVL7GqJy0lG3n2VRuiPQRIqwKpY4A4&e=
> >
> http://hdl.handle.net/1902.1/M908V1<
> https://urldefense.proofpoint.com/v2/url?u=http-3A__hdl.handle.net_1902.1_M908V1&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=JLoYUzC47p12YrOEH7S_pT7r0HQJRKoxeOnoIrLhXxk&s=S9j8ZtyjNexbX4JgYqSee9uOGE1-YuMs9l6y-9MLW3Q&e=
> >
> http://hdl.handle.net/1902.1/M902V1<
> https://urldefense.proofpoint.com/v2/url?u=http-3A__hdl.handle.net_1902.1_M902V1&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=JLoYUzC47p12YrOEH7S_pT7r0HQJRKoxeOnoIrLhXxk&s=R07aQlBpLRVD8xhnTgnOQfkYqxbeBrDV5xqfAyLV8yY&e=
> >
> http://hdl.handle.net/1902.1/M895V1<
> https://urldefense.proofpoint.com/v2/url?u=http-3A__hdl.handle.net_1902.1_M895V1&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=JLoYUzC47p12YrOEH7S_pT7r0HQJRKoxeOnoIrLhXxk&s=7TcpNEXDy4IwpUeVhx75YJx87WDv4At_7pmV6vQ5oJw&e=
> >
>
> —
> Reply to this email directly or view it on GitHub<
> https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_issues_2383-23issuecomment-2D124058376&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=d7bbsLIcERTG2Qe_gE_iKH1z80JxaTHhJpRXaS4mxwM&m=JLoYUzC47p12YrOEH7S_pT7r0HQJRKoxeOnoIrLhXxk&s=Y1nmWV0IyAvCBQHbBouA8NQmzN_pvr5vu8nQo0t6DDc&e=
> >.
>
> —
> Reply to this email directly or view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_issues_2383-23issuecomment-2D124118546&d=BQMFaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=i8i-IkM9lNUL4xQymIvNYtGzsN14xKJFPtj4itRF4tQ&s=mtG2w6y_RoWpD5b31EUIhdMXeQU4Owl3uQv4pstmzlc&e=>
> .
>



-- 
Sonia Barbosa
Manager of Data Curation, IQSS Dataverse Network
Manager of the Murray Research Archive, IQSS
Data Science
Harvard University

Dataverse 4.0 is now available for use!
http://dataverse.harvard.edu
<https://fasmail.harvard.edu/OWA/redir.aspx?C=2jB6Ls9Fe0mjxN6gZ3Yb568isoGyjtII21j8MZOjF0BwTp8i9Fumfff0X7hVFLqgHryS8DmrBHs.&URL=http%3a%2f%2fdataverse.harvard.edu>

All test dataverses should be created  in 4.0 Demo!
http://dataverse-demo.iq.harvard.edu/
<https://fasmail.harvard.edu/OWA/redir.aspx?C=2jB6Ls9Fe0mjxN6gZ3Yb568isoGyjtII21j8MZOjF0BwTp8i9Fumfff0X7hVFLqgHryS8DmrBHs.&URL=http%3a%2f%2fdataverse-demo.iq.harvard.edu%2f>

Join our Dataverse Community!
https://groups.google.com/forum/#!forum/dataverse-community
<https://fasmail.harvard.edu/OWA/redir.aspx?C=2jB6Ls9Fe0mjxN6gZ3Yb568isoGyjtII21j8MZOjF0BwTp8i9Fumfff0X7hVFLqgHryS8DmrBHs.&URL=https%3a%2f%2fgroups.google.com%2fforum%2f%23%21forum%2fdataverse-community>

**Comment by sekmiller** [comment]
The issue is caused by the globalIdCreateTime on the dataset being null.  The command tries to fill in the time but since the dataset doesn't have a doi protocol it fails.  The code should be updated to handle this.

As a bandaid we can manually update the global id create time which should allow them to publish.

Here are two diagnostic queries and an update query to accomplish this:

Select * from dataset where authority = '1902.1'
and protocol = 'hdl' 
and identifier = 'M474V1'; 

select createtime from datasetversion where dataset_id = 
(Select id from dataset where authority = '1902.1'
and protocol = 'hdl' 
and identifier = 'M474V1');

update dataset set globalidcreatetime = (select createtime from datasetversion where dataset_id = 
(Select id from dataset where authority = '1902.1'
and protocol = 'hdl' 
and identifier = 'M474V1'))
where authority = '1902.1'
and protocol = 'hdl' 
and identifier = 'M474V1';

Run the diagnostic queries to make sure we're getting the correct dataset then run the update.

**Comment by sekmiller** [comment]
For the remaining datasets we can check with the admin to see if they are planning to publish and run a bulk update if necessary.

**Comment by sekmiller** [comment]
@sbarbosadataverse - we ran a data update for the one dataset at the top of the ticket.  UCLA should now be able publish that dataset.  Next week we can decide what to do about the rest of the datasets on the list.  The keys here will be to see which are unpublished and to make sure that their handle urls resolve to dataverse 4 before we run a bulk update.

**Comment by sbarbosadataverse** [comment]
@sekmiller 
libbie pinged me about this today.
any idea when we can do this? I don't see a milestone?

**Comment by sekmiller** [comment]
Disregard that commit notice above.  I was discussing this issue while I was in the process of making a commit on another issue, and the wires in my brain got crossed.

**Comment by sekmiller** [comment]
@sbarbosadataverse - sorry about dropping the ball on this.  I can work with Kevin to write a bulk update query for the rest of the datasets in question. It will be done outside of the context of a release.

**Comment by pdurbin** [comment]
@sekmiller even though it sounds like you won't be changing code, you might want to change the milestone to 4.2.2 if you're going to be working on this in the near future. It helps @kcondon find issues once they're in QA.

**Comment by sekmiller** [comment]
Couldn't attach the sql files directly to the issue as .sql files are not supported by git.  Emailed them to Kevin.  

@kcondon let me know if you have any questions or run into any problems

**Comment by pdurbin** [comment]
@sekmiller if you add ".txt" to the end (i.e. script.sql.txt) you should be able to attach it to a github issue.

**Comment by kcondon** [comment]
Have run the two scripts before/after updating createtime and they are all updated. @sbarbosadataverse Please let Libbey know and confirm it's working.

**Comment by sbarbosadataverse** [comment]
Noting that Libbie and her team may want DOIs for these datasets.
