### ISSUE TITLE
Groups UI: After creating a group, manage groups page should automatically refresh.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2386]
When you create your first group there is a green message block that says success, refresh page to see the group. This should probably be done automatically. The same happens when you create any subsequent group.

**Comment by michaelsuo** [comment]
@scolapasta having some trouble with this. In [explicitGroup-new-dialog.xhtml](https://github.com/IQSS/dataverse/blob/4.0.2/src/main/webapp/explicitGroup-new-dialog.xhtml), we have the following save button.
```xhtml
<div class="button-block">
    <p:commandLink type="button" styleClass="btn btn-default" 
                   value="#{bundle['dataverse.permissions.explicitGroupEditDialog.createGroup']}"
                   update="explicitGroupNewDialogContent @([id$=Messages])"
                   actionListener="#{manageGroupsPage.createExplicitGroup}"
                   oncomplete="if (args &amp;&amp; !args.validationFailed) explicitGroupForm.hide();">
        <f:param name="DO_GROUP_VALIDATION" value="true"/>
    </p:commandLink>
    <button type="button" class="btn btn-default" onclick="explicitGroupForm.hide()" value="#{bundle.cancel}">#{bundle.cancel}</button>
</div>
```
We want 
```xhtml
update="explicitGroupNewDialogContent @([id$=Messages])"
``` 
to also update the `allGroups` dataTable in [manage-groups.xhtml](https://github.com/IQSS/dataverse/blob/4.0.2/src/main/webapp/manage-groups.xhtml), but when I change the line to
```xhtml
update="explicitGroupNewDialogContent allGroups @([id$=Messages])"
```
It causes an infinite loop (?). An analogous thing is done with permissions-manage.xhtml and the roles assign dialog, so I'm not sure why this specifically is breaking.

**Comment by kcondon** [comment]
Still not working, passing to Gustavo.

**Comment by scolapasta** [comment]
Fixed - the issue seemed to be the "@([id$=Messages]" which I replaced with the messagePanel from the header. This worked, but then I also had to modify backing bean to add the new group to the list of explicit groups.

**Comment by kcondon** [comment]
Works, closing
