### ISSUE TITLE
Groups UI: Clicking Cancel on create groups pop up throws validation error.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2387]
Clicking Cancel on create groups pop up throws validation error, it should just exit quietly and not throw an error.

Try it from the manage groups page.

**Comment by michaelsuo** [comment]
@kcondon I'm not seeing this behavior?

**Comment by kcondon** [comment]
@michaelsuo This does not seem to be happening now, I'll close it. Thanks!
