### ISSUE TITLE
Groups UI: Not able to Edit an existing group

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2392]
There is currently no way to edit an existing group: there is a view button instead. View should be replaced by edit.

**Comment by michaelsuo** [comment]
Edit groups functionality not in 4.1, targeting for next release

**Comment by kcondon** [comment]
Michael, this ticket should remain open whether or not it is due in v4.1 or later. I opened it and assigned to v4.1 because this feature was being worked on now and wanted Gustavo and others to reprioritize as necessary.

**Comment by michaelsuo** [comment]
Rudimentary edit functionality should be done.

**Comment by kcondon** [comment]
@michaelsuo Works! Thanks for getting this one in at the last minute! Closing.
