### ISSUE TITLE
Groups UI: Manage groups table missing some columns, some need to be combined.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2393]
Currently, the columns displayed on the Manage groups page table are:
Group Name, Number of Users, Number of Groups, Action

According to the mockup:
https://iqssharvard.mybalsamiq.com/projects/groupsui/Dataverse%20-%20Groups%20-%20Stand%20Alone

The columns should be:
Group Name, ID, Created In, Membership, Action

Where Membership is actually the combination of what's currently Number of Users and Number of Groups.

Additionally, the Membership value should be a link that goes to the add/edit users popup but  that will be opened as a separate ticket.

**Comment by kcondon** [comment]
@michaelsuo Michael, when you finish these tickets, do not close them, instead mark them as qa and remove the dev label. That way I can retest and close. Thanks!

**Comment by michaelsuo** [comment]
@kcondon oh sorry! didn't realize

**Comment by kcondon** [comment]
No problem, thanks for all the hard work!

**Comment by kcondon** [comment]
This is mostly working but is missing the Created In column.

**Comment by michaelsuo** [comment]
I think we decided to not display groups that belong to sub-Dataverses,
which makes the Created In column unnecessary?

**Comment by kcondon** [comment]
Yes, do not show sub dv groups in parent dv's manage group page but do show parent groups in sub dv's manage groups page since that is how group availability for assignment works. So yes, we should still have Created In following the above rules.

**Comment by mheppler** [comment]
Cleaned up layout of Edit popup for Manage Groups page.

The clean up of that popup doesn't entirely fit into the scope of this ticket, but I tagged it on, so as to save from an additional ticket.

**Comment by kcondon** [comment]
@michaelsuo The created in column still does not exist so I am reopening this ticket. In general, do not directly close tickets but send them to QA, thanks!

**Comment by michaelsuo** [comment]
@kcondon oh I think issues are auto-closed when commits that mention them
are merged to master. I'll stop doing that!

**Comment by mheppler** [comment]
The cleanup of the Manage Dataverse Groups pgs was completed in [4.1](https://github.com/IQSS/dataverse/releases/tag/v4.1). I suggest this issue can be closed, with the 4.1 milestone added for reference. If there are any problems contained in this issue that have no been resolved, we can address with additional user testing in a future release.

![screen shot 2016-10-27 at 5 29 58 pm](https://cloud.githubusercontent.com/assets/687227/19786376/a58e8790-9c6b-11e6-81cf-523939d78442.png)

**Comment by kcondon** [comment]
Mike, feel free to close if this is a Design decision.
