### ISSUE TITLE
Groups UI: Create Group and Add Users need to be two separate workflows according mockup and FRD.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2394]
Create/Edit Group and Add/Edit Users need to be two separate popups/ workflows.

According to the FRD:
https://docs.google.com/document/d/1P4HOUuJEoPfU06-4R9xP0nRFapNyZUg5xnjYNVRvFik/edit#
Add second pop up in create workflow for selecting users and groups for a group

And mockups:
https://iqssharvard.mybalsamiq.com/projects/groupsui/Dataverse%20-%20Groups%20-%20Create%20Group

https://iqssharvard.mybalsamiq.com/projects/groupsui/Dataverse%20-%20Groups%20-%20Create%20Group%20Add%20Users

**Comment by michaelsuo** [comment]
Related to adding functionality for editing groups; in for next release

**Comment by mheppler** [comment]
The cleanup of the Manage Dataverse Groups pgs was completed in [4.1](https://github.com/IQSS/dataverse/releases/tag/v4.1). I suggest this issue can be closed, with the 4.1 milestone added for reference. If there are any problems contained in this issue that have no been resolved, we can address with additional user testing in a future release.

![screen shot 2016-10-27 at 5 29 58 pm](https://cloud.githubusercontent.com/assets/687227/19786376/a58e8790-9c6b-11e6-81cf-523939d78442.png)

**Comment by pdurbin** [comment]
I'm with @mheppler. Vote to close. If he doesn't feel like the mockups from over a year ago need to be adhered to, neither do I. Let's start with a fresh look and new workflows if necessary.

**Comment by kcondon** [comment]
I didn't know we were all voting. I spoke with Gustavo on his way out and for bugs that were reported against features that were under development, they are bugs because either: 1. something is broken or 2. it was not built as specified, often by Design, aka Liz/Mike. 

So, unless Danny feels otherwise such as needing some UX review in some cases, like the create groups buttons on every permissions page, I am not voting on whether Mike as a designer feels it is no longer needed since it is his job to make that determination and I'm all for letting people do their jobs. In this particular case I thought it was needlessly complex but dutifully reported it anyway.

**Comment by kcondon** [comment]
Mike, feel free to close if this is a Design decision.
