### ISSUE TITLE
Groups UI: View mouse over message remains even after popup appears.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2396]
This may be a non issue if view mode is replaced by Edit but when you mouse over the view button, see the view tool tip, then click the view button, the tool tip remains active and seen through the popup.

**Comment by michaelsuo** [comment]
@scolapasta iirc this is a persistent issue with Primefaces?

**Comment by mheppler** [comment]
@michaelsuo @scolapasta @kcondon -- this issue with PrimeFaces popups and Bootstrap tooltips can be found across the entire app. Give me this ticket, and I can try to resolve it for 4.2.

**Comment by mheppler** [comment]
Fixed bug with tooltips continuing to display when a popup is opened.

I looked into this, and it was a simple fix, by adding a line of jQuery to the dv_rebind_bootstrap_ui.js to hide tooltips when that file is run via oncomplete calls in commandLinks for opening the popup dialog component.

**Comment by kcondon** [comment]
Works, closing.
