### ISSUE TITLE
My Data: Deaccession facet should only show dataset if no published version like search does.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2398]
The deaccession facet on My Data works but it shows deaccessioned versions in cases where there is still at least one published version. It should only show deaccessioned datasets if there are no published version if we are keeping the behavior consistent with search.

**Comment by pdurbin** [comment]
It's possible that this is a case where we are relying the deletion of the corresponding "permission" document to hide the primary document from regular search/browse. That is, the fix may be to make sure the primary document is also deleted. This is just a theory however.

**Comment by kcondon** [comment]
Works, closing.
