### ISSUE TITLE
Installation Guide: Update Postgres section; provide path to Postgres config files, get rid of ident sameuser, remind to restart postgres.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2399]
There are a few things that could make the Postgres prerequisite section easier to use:

1. In the Installer's Guide under the PostgreSQL section, we ask users to modify the pg_hba.conf file but don't say where it can be found: 
/var/lib/pgsql/9.3/data on RHEL/CentOS.

2. Remove local all all ident sameuser from the Configure access to PostgresQL for the installer script section and use only the trust option since we had trouble getting sameuser to work.

3. Make a note that postgres needs to be restarted after modifying the file:
service postgres restart.

**Comment by landreev** [comment]
Looks like it should just be
local all all                ident

-  if one wants to use ident. "sameuser" is kind of redundant there... but older versions of postgres were apparently willing to tolerate it there. But 9.3 thinks "ident sameuser" is an error. 

But yes, it may be easier to just say "set it to trust for the installer to run". 
Although it may be better still to finally eliminate the whole idea of su-ing to user postgres and running psql under its uid... I'll figure out what's the best I can put in there today; but I'll fix it one way or another.

**Comment by landreev** [comment]
Wait, why are we supplying redhat-specific instructions only? Didn't we have MacOS instructions too, in the 4.0 documentation?? (maybe they are buried in the dev. guide...)

**Comment by landreev** [comment]
OK, I rewrote the guide:  
added instructions for MacOS; 
specified the likely locations of the config file; 
made it more clear which files need to be modified for each config entry; 
replaced "ident sameuser" with "peer" (that's what "ident" does anyway, when specified on the local socket connection). 
further advised to change the setting to "trust" if the installer is still having problems; 
added the restart requirement; 
made things generally more clear. alas, at the expense of making the section longer.

**Comment by landreev** [comment]
And no, I'm not ready to get rid of the su-ing to user postgres, and the requirement to run the installer as root. Maybe in 4.2?

**Comment by kcondon** [comment]
OK doc updated, closing.
