### ISSUE TITLE
DOI: Add support for direct DataCite doi registration

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#24]
---

Author Name: **Kevin Condon** (@kcondon)
Original Redmine Issue: 3397, https://redmine.hmdc.harvard.edu/issues/3397
Original Date: 2013-12-03
Original Assignee: Gustavo Durand

---

See RT #171127

We already have a DataCite account and use DOIs for our articles,
published
via the OJS system (http://pkp.sfu.ca/ojs/).
Is there any possibility to register DOIs within DataVerse directly with
DataCite? Or would we really have to pay for
an extra mediator service (EZID)?

**Comment by eaquigley** [comment]
Pasing to @scolapasta because I am not sure why this was given to me and am not sure of what needs to happen.

**Comment by pdurbin** [comment]
> Handle support will need to be in place

"Here in UBC, we would strongly support continue issuing handles for datasets (and not just DOIs) in Dataverse 4. We will be relying on handles to assign/resolve DOIs in our new discovery level for UBC Library - open collections. Our thinking is to use handles to resolve DOIs to. So handles will continue to be essential for us to use. As we have to work with DataCite API in Canada for now, we cannot use EZID, hence handles are a must for us to have. " -- @eugene-barsky at https://groups.google.com/d/msg/dataverse-community/xVb9a6dY8FQ/qS995aZyHQAJ

**Comment by eugene-barsky** [comment]
Thanks, Philip!

E

**Comment by mfenner** [comment]
I don't know if that helps, but Dspace has been in a similar situation, supporting DataCite DOI registration initially only via EZID, and later adding support for registration with the DataCite MDS directly: https://wiki.duraspace.org/display/~pbecker/DOI+support+using+DataCite.

DataCite has three members in the US: CDL (EZID), Purdue and OSTI, so the issue here is not strictly US vs. non US.

**Comment by sekmiller** [comment]
Assigning to QA - Pull request has been made

**Comment by kcondon** [comment]
Tested, works with some issues opened in separate ticket.

Test checklist:
Documentation
	-Are the steps to enable clear?
Configuration
	-Do the configuration steps work?
Create Dataset
	-Does an appropriate DOI/persistent Url get created and appear in the Draft Citation?
	-Since DataCite does not reserve DOIs, does the identifier appear in the DOIDataCiteRegisterCache table?
Publish Dataset
	-Is the DOI created at DataCite?
	-Is the persistent URL resolvable?
	-Is the dataset metadata included?
	-Is there an updated DOI version with updated metadata for each published version of a dataset?
Deaccession Dataset
	-When there is at least one published version available, persistent URL will resolve to that.
	-When all versions are deaccessioned, persistent URL will resolve to deaccessioned tombstone page and isActive flag at DataCite set to false.
	-What happens when all versions are deaccessioned except one draft version?
Delete Dataset
	-No special handling, other than removing draft dataset. DOI identifier remains in DOIDataCiteRegisterCache table. If a published version exists, persistent URL will resolve to that, if no published version, just remove it. Will review with Gustavo.
Destroy Dataset
	-No special handling, other than removing all versions of dataset. We do not update record at DataCite nor remove identifier form DOIDataCiteRegisterCache table. Will review with Gustavo.
Supported Metadata
	-identifier
		identifierType (DOI)
	-creators
		creator
			creatorName
			nameIdentifier
			affiliation
	-titles
		title
	-publisher (automatic: dataverse name)
	-publicationYear (automatic: current year/ year published)
	-resourceType (Dataset)
	-descriptions (only first description listed)
		description
			descriptionType (Abstract)
	-contributors
		contributor
			contributorType (ContactPerson)
			contributorType (Producer)
			contributorName
			affiliation
Validation
	-Bad credentials
	-Unique identifier
	-Failure to register
	-DOI format (shoulder)
Error handling
	-Messages (indicate possible DataCite or temporary issue, try again later)
	-Behavior (if duplicate detected, will keep trying with different id)
Logging
	-Verify there are no debugging statements left in place.
Out of Scope
	-Multiple DOI providers
Questions
	-Interactions between namespaces/shoulders
	-Interactions between DOI providers

**Comment by kcondon** [comment]
This has been delivered with separate tickets opened for individual issues. Closing.
