### ISSUE TITLE
Installer: Update make README.txt to change versions, file list, path to war file.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2400]
The README.txt is a little outdated and could use updating.
1. It still references dataverse 4.0.
2. The file list now includes schema.xml and possibly others.
3. There is a line that says, the script itself knows to look for these files in 2 places (for example, ../../target/dataverse-4.0.war and ./dataverse-4.0.war)

but the ./dataverse-4.0.war file option doesn't work when using make, only the ../../target/dataverse-4.0.war

When the installer script (install) can be run either by a developer (inside the source tree), or by an end-user installer, from 
a zip file distribution. 

In the former case, other files that the installer needs can be found in other parts of the source tree. 
for example, the war file (once built) can be found in ../../target/dataverse-4.0.war

When building a distribution archive file however, all the files that the installer needs are piled up in 
the same directory and zipped up; this way it can be run outside the full source tree. 
So the script itself knows to look for these files in 2 places (for example, ../../target/dataverse-4.0.war and ./dataverse-4.0.war)
And a Makefile is provided that copies all the needed files here and makes the final zip file.

**Comment by landreev** [comment]
Yes, that README was written a year ago, in July '14 - and not touched since. 
I have rewritten it; hopefully removing the ambiguities (made it more clear whether I'm talking about the installer script itself, or the Makefile that builds the bundle, etc.). 
please review.

**Comment by kcondon** [comment]
Updated, closing.
