### ISSUE TITLE
Installation Guide: Tell users to start solr before running the installer, until installer includes Solr.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2401]
Until the installer incorporates starting Solr, it would be good to tell users to start Solr before running the installer, either in the Solr prerequisite page or on the running the installer section.

**Comment by pdurbin** [comment]
As I mentioned in [a thread on the Google Group](https://groups.google.com/forum/#!msg/dataverse-community/PFMkHkelj_Q/3o5cgPiOxkcJ) yesterday @bencomp and others are planning a reorg of the Installation Guide as part of #2321 in a Google doc: https://docs.google.com/document/d/1GLky44JbtCNhGuavLXGEP8WPNdjbyHNxalEGjR78MaA/edit?usp=sharing

The proposed reorg has Solr first under "Configuration".

**Comment by kcondon** [comment]
@pdurbin OK but I need to enter issues as I find them while using the installation guide. If you find there are duplicates feel free to link back to the more general ticket but I think it is useful to call these out.

**Comment by kcondon** [comment]
The current Solr section does not mention starting Solr as a requirement for running the installer.

**Comment by pdurbin** [comment]
In my pull request at #2895 I addressed this issue. The new wording can be previewed at http://guides.dataverse.org/en/2884-install-guide-reorg/installation/prerequisites.html#solr-init-script

**Comment by kcondon** [comment]
OK, part of prereq, required before running installer. Closing.
