### ISSUE TITLE
Installation Guide: Fix various typos.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2402]
The Installation Guide has numerous minor typos throughout the guide. This is a placeholder ticket to review and correct these.

**Comment by pdurbin** [comment]
So many typos fixed in my pull request at #2895. If I introduced any I apologize and this issue should be kicked back to me. The rewritten Installation Guide can be previewed at http://guides.dataverse.org/en/2884-install-guide-reorg/installation

Passing to QA.

**Comment by kcondon** [comment]
Looks good, closing.
