### ISSUE TITLE
Installation Guide: Add information that jq is required to run the installer.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2405]
I ran into the error that jq was not installed when I was setting up beta. It was not listed in the prerequisites.

yum install jq was enough to satisfy the prereq though I think you need the website for a mac that doesn't have the dev tools installed?

**Comment by pdurbin** [comment]
In my pull request at #2895 I addressed this issue. It can be previewed at http://guides.dataverse.org/en/2884-install-guide-reorg/installation/prerequisites.html#jq

Passing to QA.

**Comment by kcondon** [comment]
Doc'd closing.
