### ISSUE TITLE
Dataverse/Dataset Metadata - Description + Notes Truncated + "Show More" Link

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#241]
---

Author Name: **Mike Heppler** (@mheppler)
Original Redmine Issue: 3655, https://redmine.hmdc.harvard.edu/issues/3655
Original Date: 2014-03-06
Original Assignee: Mike Heppler

---

Long descriptions can push the search and child items down too far. We could truncate it, and use a "Show More" link to display the rest.

---

Related issue(s): #454
Redmine related issue(s): [3869](https://redmine.hmdc.harvard.edu/issues/3869)

---

**Comment by mheppler** [comment]
Related to #1320.

**Comment by scolapasta** [comment]
Going to merge this into #1249

**Comment by sbarbosadataverse** [comment]
No "showmore" option available with truncated "Description" field text. Just "..."



![tk6pvvghbnowwbn4_ds-3ebjt8m-v7nyhr-fjvmc2tm](https://cloud.githubusercontent.com/assets/8322346/6759976/ec06f7cc-cf1a-11e4-969a-59934b7b2d83.png)

**Comment by kcondon** [comment]
@eaquigley @mheppler 
Sonia tested this and text is truncated ok but she notes there is an elipsis ... rather than a view more link as mentioned at the top this ticket. I am fine with this but wanted to check with you guys. I'm closing but feel free to reopen if this is not desired behavior.
