### ISSUE TITLE
MyData - streamline retrieval of role labels

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#2411]
Currently 70 to 200+ queries.  Can be done in 2 queries--or max. 30--up to 3 per card

- [RoleTagRetriever.java](https://github.com/IQSS/dataverse/blob/4.2/src/main/java/edu/harvard/iq/dataverse/mydata/RoleTagRetriever.java) class reduces queries to 2 or 3 total

**Comment by raprasad** [comment]
@kcondon, Now 'all' roles should show, even if assigned at a higher level.

**Comment by raprasad** [comment]
@scolapasta - I moved this to "4.2" since the code is already checked in.

**Comment by kcondon** [comment]
OK, regression tested role tags and seems to be working, closing.
