### ISSUE TITLE
Groups UI: Delete user, then cancel or X the popup appears to delete user anyway but it is a refresh issue.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2413]
The cancel and X buttons in the edit groups popup appear to save deleted users but it is only a refresh issue since shift reload makes the user appear again. This does not seem to affect saving new users.

**Comment by mheppler** [comment]
Tried to resolve this while working on the popups and buttons in #5717 but it was a little more complicated than I had anticipated. It is also highly related to another know "refresh" bug with the groups in issue #2930. Hopefully we can resolve these two together and consolidate the two issues into one "groups refresh bugs".
