### ISSUE TITLE
File Ingest Limiter: Document file size limiter in the administration? section of the guides.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2415]
The new file size limiter is a useful feature but should be documented too, probably in the administration section of the guides?

**Comment by pdurbin** [comment]
I learned a lot about how this feature even works by documenting it in my pull request at #2895.

The change can be previewed at http://guides.dataverse.org/en/2884-install-guide-reorg/installation/config.html#tabularingestsizelimit

Passing to QA.

**Comment by kcondon** [comment]
Yep, doc'd closing.
