### ISSUE TITLE
Hovering mouse over Download button does not reveal the URL of the file and the URL does not contain the file name

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#2416]
If you go to https://zenodo.org/record/18898#.VbZZpZNVhBd and hover your mouse over the "Download" button you will see the URL https://zenodo.org/record/18898/files/MHC_PosSel_dataset.zip which is a direct link to the file. You can email this link to someone and it will work.

![screen shot 2015-07-27 at 12 18 18 pm](https://cloud.githubusercontent.com/assets/21006/8911449/a6fb50e2-345a-11e5-9bc8-166f9f8eccf0.png)

If you go to https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/DAGL4S and hover your mouse over the "Download" button the URL you see is https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/DAGL4S# which is **not** a link you can send to someone to download the file in question. You have to click the link (which does a POST) and then the file is downloaded. Furthermore in the URL to download this file, the file name is a number rather than "R_code_for_replication.R".

![screen shot 2015-07-27 at 12 17 10 pm](https://cloud.githubusercontent.com/assets/21006/8911468/b5116888-345a-11e5-8926-6b33bf6f0c06.png)

At https://groups.google.com/d/msg/dataverse-community/Uz-_PoyxvY0/qCVxmTdlEDoJ this problem was expressed in this way:

> So Adam...
> 
> You are happy using the SWORD api to get a list of file #'s and file names and then working that out off line to provide direct links to your files? I'm writing up some author instructions right now for using 3rd party repositories in AAS articles and this is utterly baffling to explain this compared to Zenodo, which uses restful real file names to resolve to files. 
> 
> To be clear, if one is building an application around a Dataverse dataset, then the SWORD API seems like an awesome solution. But if all you (the dataset author) want to do is reuse the direct link to a file in another place this(*) is a huge, huge barrier. 
> 
> But maybe I need another astronomer's perspective here on what is and isn't useful about file level links. 
> 
>  - Gus
> 
> (*): calling a file named trees.png "https://apitest.dataverse.org/api/access/datafile/12" instead of something human readable.

**Comment by keflavich** [comment]
:+1: this is what I want!

**Comment by augustfly** [comment]
yah. me too. and if I think of any permutations i'll comment promptly.

**Comment by pdurbin** [comment]
Related: #2700

**Comment by binarybottle** [comment]
What is the status of file-level persistent URLs?

**Comment by pdurbin** [comment]
https://help.hmdc.harvard.edu/Ticket/Display.html?id=236541 has details about another request for this feature. I've invited that person to comment here as well.

**Comment by djbrooke** [comment]
Going to merge this and #2700 into a new issue.
