### ISSUE TITLE
Add API endpoint for Dataverse.org metrics

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#2417]
- Add simple API including:
  - # of public datasets
  - # of public dataverses
  - # of registered users
  - # downloads
- May be expanded later
- How dynamic should this be?
     - Suggestion:
       -  table:  "dv_public_stats"
       -  column: id, timestamp, JSON (or Text) 
- API:
    - Uses database if called within last x hours,
    - If not, dynamically finds stats

**Comment by bencomp** [comment]
What would the necessary permissions for access to these endpoints be? Anyone (with a key) for the simple metrics and superuser for diagnostic endpoints (that may include all datasets and dataverses)?

Isn't the number of public dataverses and datasets queriable from Solr?

**Comment by pdurbin** [comment]
> Isn't the number of public dataverses and datasets queriable from Solr?

Yes. In fact, the Search API queried by SHARE for https://osf.io/share/?q=*&optional=source%3Aharvarddataverse&sort=Date and https://osf.io/api/v1/share/search/?q=source:harvarddataverse

With the exception of API endpoints that are blocked to localhost for admin purposes, all APIs currently require an API token but #1838 may change this.

**Comment by raprasad** [comment]
@bencomp, they need stats (these to start) for the dataverse.org site; creating graphs, etc.  

 - Point of a separate API endpoint is the stats they'd like to display will probably change out of the current solr scope in coming months.  That said, they should be available via anyone's API key

**Comment by raprasad** [comment]
done in https://github.com/iqss/miniverse
