### ISSUE TITLE
Link Dataset - List of dataverses getting stuck, can't select

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2427]
Even tho I'm selecting "Schneer,' the list is stuck on "smith."
Tried several times same results.

And when I type in the entire name of the dataverse, the list will "skip" instead of staying on the name selected

![screen shot 2015-08-03 at 12 20 06 pm](https://cloud.githubusercontent.com/assets/8322346/9041910/f85422ba-39d8-11e5-823a-3c4e10baacd1.png)

**Comment by djbrooke** [comment]
We did some optimizations to this code the last time we worked on linking because of issues like this. I'd expect this to work now. Closing.
