### ISSUE TITLE
Processing bar not showing progress: post the last 4.1 release, noticed blue progress bar showing no progress during file upload

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2428]
![screen shot 2015-08-01 at 9 36 41 am](https://cloud.githubusercontent.com/assets/8322346/9042113/896d900a-39da-11e5-87a3-a5b2a9116e10.png)

**Comment by eaquigley** [comment]
Passing to QA to test out. I tried this on demo.dataverse.org and the progress bar worked for the pdf I uploaded.

**Comment by sbarbosadataverse** [comment]
@kcondon  where is the best place for me to test today?

**Comment by kcondon** [comment]
demo.dataverse.org
________________________________

**Comment by sbarbosadataverse** [comment]
works fine. progress bar processed quickly!

On Tue, Jan 5, 2016 at 5:28 PM, kcondon <notifications@github.com> wrote:

>
> demo.dataverse.org
> ________________________________
> From: sbarbosadataverse [notifications@github.com]
> Sent: Tuesday, January 05, 2016 5:27 PM
> To: IQSS/dataverse
> Cc: Condon, Kevin M
> Subject: Re: [dataverse] Processing bar not showing progress: post the
> last 4.1 release, noticed blue progress bar showing no progress during file
> upload (#2428)
>
>
> @kcondon<
> https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_kcondon&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=TUpjWt9sVfaAC8ETCY_cDPtqJKl7s242PLg6-Wx6UpM&m=RZv0JXCfpRRdf6Md8mv6h5jIt-CNOtI1oxMyXBgWTFg&s=d54-90S0dHn1MNoAfcXRJR4ODkH5D8b41EiENgKlffs&e=>
> where is the best place for me to test today?
>
> —
> Reply to this email directly or view it on GitHub<
> https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_issues_2428-23issuecomment-2D169154282&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=TUpjWt9sVfaAC8ETCY_cDPtqJKl7s242PLg6-Wx6UpM&m=RZv0JXCfpRRdf6Md8mv6h5jIt-CNOtI1oxMyXBgWTFg&s=mCCMXoh7Puq735AU0gckeKlvc7ZkI93Dle0wgHJM7UE&e=
> >.
>
> —
> Reply to this email directly or view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_issues_2428-23issuecomment-2D169154648&d=CwMFaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=1FH9XHiCAsLobHV2R6QQ9ikWMTlZD-LHnLVYHVIEN20&s=lnBOT_jMmxjcm4buXtNb_ONk6wXXBwgDNRVjaCQ434s&e=>
> .
>



-- 
Sonia Barbosa
Manager of Data Curation, IQSS Dataverse Network
Manager of the Murray Research Archive, IQSS
Data Science
Harvard University

Dataverse 4.0 is now available for use!
http://dataverse.harvard.edu

All test dataverses should be created  in 4.0 Demo!
http://dataverse-demo.iq.harvard.edu/

Join our Dataverse Community!
https://groups.google.com/forum/#!forum/dataverse-community

**Comment by kcondon** [comment]
I tested on demo using the file in the screen shot and did not see a problem. We sometimes see issues with the progress bar due to client/ server communication so wonder whether this feature is brittle in some way. Depending on production observations going forward, we may want to rethink such a feature for reliability.
