### ISSUE TITLE
My Data - Superuser "Results by username" expanded to allow First, Last Names

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2430]
As it's not always easy to find a username especially if someone is not creating a username based on their email, it's much easier to search for users by their first and last names.

**Comment by djbrooke** [comment]
Closing this in favor of #3614 and #3612.

**Comment by pdurbin** [comment]
@djbrooke I think you forgot to actually click "Close" so I'm helping you out. 😄
