### ISSUE TITLE
Versions Tab: Enable request access value does not appear in version differences.

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2432]
If you change the terms between versions, this isn't listed in the versions table or in the pop up. It should be.

**Comment by bencomp** [comment]
There is more like this: #2258

**Comment by kcondon** [comment]
This works for all terms of use and terms of access fields except for the Enable access request status. So, changing this ticket to be about enable request access value.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
