### ISSUE TITLE
md5 error: remove error that shows up when creating a new draft

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2433]
![screen shot 2015-08-04 at 1 01 22 pm](https://cloud.githubusercontent.com/assets/8322346/9066952/76ce6f04-3aa8-11e5-853c-da8e6fcbc806.png)

**Comment by eaquigley** [comment]
@sbarbosadataverse what is the workflow for when this happens? is it when editing pre-existing files or is it you've uploaded new files?

**Comment by kcondon** [comment]
Have not seen in a while, some work has been done to this area. Will reopen with steps to reproduce if we see it again.
