### ISSUE TITLE
Edit Dataset Metadata: After save, page should display with Metadata tab open

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2435]
When I edit metadata page and hit "save" I am directed back to "file" tab page and have to go and select "metadata" tab to see my changes before publishing. I should direct back to metadata tab or whatever tab I was editing to begin with.

**Comment by pdurbin** [comment]
@sbarbosadataverse we always show the Files tab first by design. I could maybe see @pameyer wanting the behavior you're describing.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
