### ISSUE TITLE
Permissions: Cannot assign explicit groups permissions at the file level.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2440]
Cannot assign explicit groups permissions at the file level, works at dv and ds level.

Groups do not show up in list of available assignees.

**Comment by pdurbin** [comment]
"It should just be to look at the dataset permissions logic for adding explicit groups to the dropdown and add that same logic to files." -- @scolapasta

**Comment by pdurbin** [comment]
The fix is in 25c1f4a .

**Comment by kcondon** [comment]
This doesn't work: I can assign the permission to a group at the file level but file remains locked to a user who is a member of that group.

**Comment by kcondon** [comment]
OK, assigning perms works but the file download doesn't. I'm opening a new ticket for that. closing.
