### ISSUE TITLE
Can't use X-Dataverse-key from Search API

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#2442]
In #2123 we started allowing the use of an API token as a header but it isn't working in the Search API:

$ curl -H "X-Dataverse-key:$API_TOKEN" http://localhost:8080/api/search
{"status":"ERROR","message":"Please provide a key query parameter (?key=XXX) or via the HTTP header X-Dataverse-key"}

**Comment by pdurbin** [comment]
Fixed in a76fad2 in a branch. @michbarsinai I made a method private so it couldn't be called from the Search API endpoint. I'll wait until you're done with your big change in 4.2 before merging this in.

**Comment by pdurbin** [comment]
Ok 50c308e is a better fix. Cleaner because I removed the "key" parameter from the Search endpoint (though I tested it still works). Passing to QA.

**Comment by kcondon** [comment]
OK, works, closing.
