### ISSUE TITLE
Dataset Files Explore - Add CartoDB and plotly

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#2444]
Minimal coding effort is needed to add "Explore" links for cartodb and plotly.

The attached screenshot is from data.gov (a CKAN installation)

The links indicated in the screenshot are:
- https://plot.ly/external/?url=http://www.gsa.gov/dg/NSN_DATA.xls
- http://oneclick.cartodb.com/?file=http://www.gsa.gov/dg/NSN_DATA.xls&provider=data.gov

---

![national_stock_number_extract_-_data_gov](https://cloud.githubusercontent.com/assets/1036060/9199704/ec3c63fe-4011-11e5-922f-4e8897f85eb3.png)

**Comment by mcrosas** [comment]
@scolapasta and @eaquigley we should do this for 4.2, given that it's so straightforward.

**Comment by pdurbin** [comment]
Is anyone still interested in this? If not, vote to close.

**Comment by mercecrosas** [comment]
Please open again. We would like to consider doing this, in particular for plotly (possibly not for CartoDB).

**Comment by pdurbin** [comment]
@mercecrosas sure. Re-opened. Now that we have the framework for external tools ( http://guides.dataverse.org/en/4.9.1/installation/external-tools.html ) perhaps someone from the community could work on adding this feature.

**Comment by pdurbin** [comment]
Again, now that we support external tools, CartoDB, Plotly, et. al. are welcome to create external tools. We can open fresh issues when they want to add their tools to the list in the guides.

Vote to close.

**Comment by pdurbin** [comment]
Tools can be requested here: https://github.com/gdcc/dataverse-previewers
