### ISSUE TITLE
Add `isSecureConnection` field `DataverseRequest`

### ISSUE THREAD

**Issue by michbarsinai** [IQSS/dataverse#2446]
note the interplay with #1368. Need to support connections that are externally secure, but forwarded in the clear, e.g. by a reverse proxy.

_Part of the DataTags support._

**Comment by pdurbin** [comment]
I'm grabbing this issue to discuss with @mcrosas and @kcondon to see if it's related at all to the [Support for Sensitive Data BRD](https://docs.google.com/document/d/1iSO6u2pRadyMbWJ-x4hXFeLEJGNuRC2ij-euWzipwzw/edit?usp=sharing). It may turn out to be a requirement we can defer until a later effort such as DataTags integration.

**Comment by pdurbin** [comment]
@michbarsinai and I discussed this issue briefly yesterday and I have a better idea of what it's about. In practice *all* traffic between end users and the server at https://dataverse.harvard.edu is encrypted over HTTPS but especially as we introduce other ways of getting data in and out (such as rsync in #3145) we need to make sure that these mechanisms are at least as secure at HTTPS. That's my take on it anyway. @michbarsinai said this is something we won't be working on this week or this month. Requirements will be made available to developers as part of the project to integrate DataTags with Dataverse. This issue doesn't seem to be actionable at this time so I'm going to unassign myself.

**Comment by pdurbin** [comment]
Closing in favor of #871.

**Comment by pdurbin** [comment]
I'm reopening this issue to remind us about this subtask. The most recent chatter about DataTags was at https://groups.google.com/d/msg/dataverse-community/1BtCe29Dhp0/lHoW-zNuFAAJ as @mheppler mentioned at https://github.com/IQSS/dataverse/issues/871#issuecomment-270675743

This is a big project so #871 will need to be broken down into smaller chunks at some point.

**Comment by pdurbin** [comment]
@michbarsinai since all of this is deferred until Dataverse 5.0 can we close this issue? We'll break the project into small chunks once we get closer to starting it.

**Comment by michbarsinai** [comment]
As you wish - but can't we just tag it as "5.0" if it is going to be re-opened anyway?

**Comment by pdurbin** [comment]
Sure, tagged and closed. Thanks!
