### ISSUE TITLE
Permissions: ability to give admin/curator permissions from Parent dataverse to child dataverse, at parent level

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2447]
Currently have to go into each subdataverse and assign an admin in the parent, permissions in the child. While we don't want parent level permissions inherited at child level, there should be a feature that allows parent admins to be easily added to child dataverses.

**Comment by rlzijdeman** [comment]
Hi! Is there any outcome on the review yet? We've rolled out Dataverse and are now in the processing of moving all our datasets into it. We use 3 people who all should have all rights in the subdataverses. It's kind of a hassle to do this manually.

**Comment by pdurbin** [comment]
@rlzijdeman for now, if you're looking for a way to automate things, you could use the API to assign roles. Here's an example: https://github.com/IQSS/dataverse/blob/v4.2.2/scripts/issues/2036/grant-role-then-revoke

See also http://guides.dataverse.org/en/4.2.2/api/native-api.html#dataverses

**Comment by eaquigley** [comment]
@rlzijdeman if your institution is running their own Dataverse installation, please do let us know if you'd like it to be added to the repositories map at dataverse.org by emailing support@dataverse.org

**Comment by rlzijdeman** [comment]
@pdurbin @eaquigley Thank you very much for these lighting fast and adequate responses!

**Comment by pdurbin** [comment]
As a workaround, :InheritParentRoleAssignments, added in 4.10 by @qqmyers in PR #5096 should help.

@sbarbosadataverse and @rlzijdeman have you had a chance to play with this feature? Please see https://guides.dataverse.org/en/5.11.1/installation/config.html#inheritparentroleassignments

**Comment by DS-INRA** [comment]
Are there still cases that the :InheritParentRoleAssignments didnt't solve ? We had the same issue and the inheritance solved it :)

**Comment by cmbz** [comment]
2024/08/26: Closing, was addressed by https://github.com/IQSS/dataverse/pull/5096
