### ISSUE TITLE
Edit Dataset: When create draft from files or terms tab, fill in any required field that fails validation with N/A

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2448]
A short term solution for the validation errors preventing saving from files or terms tab is to put N/A in those failing metadata fields and allow save to proceed. N/A is a special value that is not printable in view mode and meant to facilitate content from non Dataverse sources via harvesting. We are using it to alleviate this immediate usability issue but long term will have a better solution. Editing the metadata will still validate required fields in the normal fashion, including failing on N/A values.

Longer term we will allow saving on drafts if required from files and terms but present a warning as to required fields and not allow publishing. See #2451

**Comment by scolapasta** [comment]
This is all set.

**Comment by kcondon** [comment]
Ok, works except for creating draft for files, opened a new issue.
