### ISSUE TITLE
Metadata Validation: Script to populate required values as N/A

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2449]
Short term solution for datasets that existed prior to 4.0 and are missing newly required metadata fields.

-write script that will populate subject and contact email fields as n/a if they are empty so a user does not lose work when they go to save edits to files or terms in a new draft and do not have these metadata fields filled out.

**Comment by scolapasta** [comment]
We won't be doing this via script, but the issue for code is already entered at #2448.

**Comment by eaquigley** [comment]
@scolapasta can this ticket be closed then?
