### ISSUE TITLE
IP Groups: How do we show someone is part of an IP group?

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2458]
In v3 we had text next to the log in link displaying if you were accessing the site as part of an IP group. How should we show this in 4.0?

**Comment by pdurbin** [comment]
#105 is for 'Add "Group + Roles" tab to account page' so I imagine we'd show your membership in an IP Group on that tab on the account page (once it exists).

**Comment by pdurbin** [comment]
"When an IP group member is detected, how is this signaled in the UI?" is asked in #3106.

**Comment by pdurbin** [comment]
Closing in favor of #3106.
