### ISSUE TITLE
Native API: publish dataset allows version less than v1.0 to be published (i.e. v0.1)

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#2461]
If you do `curl -X GET -H "X-Dataverse-key:$API_TOKEN" http://localhost:8080/api/datasets/2675227/actions/:publish?type=minor` (which should probably be a POST per #2431) on a new unpublished dataset, you are permitted to publish version 0.1 but I think our business rules dictate that the initial version of a dataset should be 1.0. Docs are here: http://guides.dataverse.org/en/4.2/api/native-api.html#datasets

This bug was discovered as of 35c42ad in the 4.2 branch.

**Comment by michbarsinai** [comment]
Sounds like a missing check in `PublishDatasetCommand`. Faced with such request, the command should throw an `IllegalCommandException`, which the API will automatically translate to `403 FORBIDDEN` (equivalent human message: "Can't do this").

So, not part of #3358, but rather a bug on it own.

**Comment by pdurbin** [comment]
We just noticed this bug being exercised during an integration demo.

**Comment by pdurbin** [comment]
Fixed in pull request #3550. Passing to Code Review at https://waffle.io/IQSS/dataverse

**Comment by kcondon** [comment]
OK, now prevents an initial version being published with minor both GET and POST:
{"status":"ERROR","message":"Cannot publish as minor version. Re-try as major release."}
