### ISSUE TITLE
Migration: Complete scripts and documentation, then verify migration steps for use by others.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2462]
We currently have migration scripts and steps on how to run just the scripts but there were some off script customizations done during our own migration that need to be included and the instructions are only for running the scripts, not how to do a complete migration. Since we have had a half dozen requests for information on how to upgrade and at least one import error, we need to meet as a group, finalize the information and verify with one more test migration.

High level steps I had been providing until we determined there were potential issues:

We are finalizing our instructions to include some lessons learned but upgrading from v3.6.2 to v4.0 involves three major steps:
1. Create a new environment using Glassfish v4.1, Postgres 9.3, Java 1.7, according to the Installation Guide:
   http://guides.dataverse.org/en/4.0.2/installation/index.html [Open URL]
2. Migrate the database and files from v3.6.2 instance to v4.0.x
   -move files and point to their location, update jvm option in the Glassfish domain.xml file
   -run database migration scripts according to https://github.com/IQSS/dataverse/blob/master/scripts/migration/migration_instructions.txt [Open URL](https://github.com/IQSS/dataverse/tree/master/scripts/migration) [Open URL]
3. Reindex all metadata
   Depending on how much data you have, this can take some time. A complete reindex of our Dataverse takes between 1 and 2 days but we have 30,000 datasets.
   To index all:
   -first clear the lastindextime from the dvobject table:
   update dvobject set lastindextime=null;
   -next run index all by entering the following into a browser:
   http://<yourhost>/api/admin/index

We recommend trying this all on a test machine first to understand how to execute all the steps. You should also record and verify the main object counts: dataverses, datasets (studies), files, and users. Last, confirm you can create new objects, update existing/ migrated objects, and review a sample of your migrated dataverses, datasets and files.

We have used these scripts and process in our own production environment so everything works but there is always some variations in data so a review is recommended.

**Comment by djbrooke** [comment]
Removing from 4.5, will be prioritized for a later release.

**Comment by djbrooke** [comment]
I'm going to close this as a large majority of installations have made the jump from Dataverse 3 to 4 (hooray!). We can provide help with individual installations on a case by case basis as they come up.
