### ISSUE TITLE
File Error Triangle: Only Show for Dataset Owners

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2463]
Currently the triangle error for a file is appearing for both data downloaders and dataset owners. Spoke with @mcrosas and we both agree that it only needs to appear for the dataset owner (admin, curator, contributor) not when a user is viewing the page to download. 

@mheppler can you evaluate if this is something you can do on your end or if there is a need for a back end developer to help with this.

**Comment by mheppler** [comment]
@eaquigley with our plan to redesign the files page, it will provide ample opportunity for me or a backend developer to fix this.

It looks like there is render logic on the page that I can use, to add to the display of the ingest warning icon.

````
permissionsWrapper.canIssueUpdateDatasetCommand(DatasetPage.dataset)
````

I can go over this with one of the developers (@scolapasta ?) , to make sure I've got the right code and can check this fix in, and make sure it is there and ready when the redesign development begins.

**Comment by eaquigley** [comment]
@mheppler that would be great. @scolapasta can you review the render logic above and confirm if it is the right code @mheppler needs to alter?

**Comment by mheppler** [comment]
Passing to @landreev to look into the above render logic, and apply necessary fixes to the dataset files view page.

**Comment by landreev** [comment]
The "red triangle" thing will not be shown to the general public from now on; and only to those who can ingest/edit files in the dataset. 
Unless you already have a failed tab ingest in the db, you may want to wait for the #2516, as tab data ingest may still be broken (need to double-check on that before I move that into QA).

**Comment by kcondon** [comment]
Works, triangle appears for admin curator, contrib but not for downloader or guest. Closing
