### ISSUE TITLE
Index "File Tag" and "Access" (Public vs. Restricted) facets

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#2466]
Even if facets only show on the dataverse page and not the dataset page, we'd like to start indexing tags (formerly categories) at the file level so we can facet on them.

We *could* also index other fields at the file level, such as:

- More detailed file type ("RData" instead of just "tabular")
- If the file is restricted or not. See also #2325
- ...

**Comment by pdurbin** [comment]
As I was discussing with @mheppler this data about file types is already indexed in Solr:

```
        "fileTypeDisplay":"Adobe PDF",
        "fileContentType":"application/pdf",
        "fileType":["Adobe PDF",
          "document"],
        "fileTypeGroupFacet":"document",
```

Currently we only show "document" for PDFs because we use the fileTypeGroupFacet which shows up as "File Type" in the GUI:

![harvard_dataverse_-_2015-08-18_12 04 10](https://cloud.githubusercontent.com/assets/21006/9335285/253ff5dc-45a1-11e5-9881-2d1100c95403.png)

It would probably be nice to be able to facet on stuff like "Adobe PDF" (fileTypeDisplay) in the GUI. We'd need to give it a label like "Specific File Type" or something.

I'm less sure that we should add a facet for "application/pdf" (fileContentType). I guess I'd call this "File Content-Type" or "File MIME Type".

**Comment by pdurbin** [comment]
With around 8000 datasets from production data indexed locally and here's how the new "File Tags" facet is looking:

![harvard_dataverse_-_2015-08-18_12 14 54](https://cloud.githubusercontent.com/assets/21006/9335582/d8bf4710-45a2-11e5-97db-b56f9620213f.png)

**Comment by pdurbin** [comment]
> If the file is restricted or not. See also #2325

After discussing this with @landreev I'm going to defer this task for 4.2. It turns out to be more complicated that I expected per my comment at https://github.com/IQSS/dataverse/issues/2325#issuecomment-132299339

**Comment by pdurbin** [comment]
@eaquigley as we discussed I'm giving this ticket to you to review. I've put v. 4.2 build 23-0178b43 on dataverse-internal.iq for you see the change.

This is what **has changed**:

- I added a "File Tags" facet and here's where you can see how it looks with ~8000 datasets indexed from production: https://github.com/IQSS/dataverse/issues/2466#issuecomment-132263943

This is what I **haven't changed** but what I've commented on in this ticket:

- I did not add a "Access" facet (Public vs. Restricted) because per this comment I've been told by @landreev that it's not as simply as I hoped: https://github.com/IQSS/dataverse/issues/2466#issuecomment-132299641
- I did not add a second version of "File Type" that would show us PDF rather than "document" because I'm not sure if we want it or what we'd call it. The data is in Solr already (and has been since 4.0) so it would be easy to make a change in this area if we'd like to. Please see https://github.com/IQSS/dataverse/issues/2466#issuecomment-132262089

The only other thing I can think to facet on at the file-level is size but until we figure out the UI for ranges (I like the design for date ranges at https://github.com/IQSS/dataverse/issues/70#issuecomment-97474713 ) and have time to dedicate to it, I don't think it's worth spending time on right now. Definitely not for 4.2.

**Comment by eaquigley** [comment]
@pdurbin one note, can you change File Tags to be File Tag. All other facets are singular. 

Regarding the Access facet, if you have time this week, could you look into this and determine how risky it is to do this and the technical difficulty?

**Comment by pdurbin** [comment]
> @pdurbin one note, can you change File Tags to be File Tag. All other facets are singular.

Sure. Done in e934b01 . I'd still like to update the underlying Solr field like I did at #1314 . I didn't do this yet because it will require a schema change.

> Regarding the Access facet, if you have time this week, could you look into this and determine how risky it is to do this and the technical difficulty?

I just spoke with @scolapasta about this and he thinks a simple boolean check should work but I should check the **File** object rather than the FileMetadata object. I can look into this more tomorrow.

**Comment by pdurbin** [comment]
@scolapasta I just pushed 8e83223 which seems to do what you want. It adds an "Access" facet at the file level with Public vs. Restricted. http://hdl.handle.net/1902.1/RSCNY is an example of a dataset that has a mix of public and restricted files:

![harvard_dataverse_-_2015-08-21_11 40 54](https://cloud.githubusercontent.com/assets/21006/9412381/66c4c23a-47f9-11e5-8aa3-44024f0d16d9.png)


I'm passing this ticket to you for review.

Please note that I think we should change `fileTags_ss` and `fileRestricted_s` I added in [SearchFields.java](https://github.com/IQSS/dataverse/blob/4.2/src/main/java/edu/harvard/iq/dataverse/search/SearchFields.java) from dynamic to non-dynamic Solr fields, similar to the clean up I did in #1314 before Dataverse 4.0 shipped. This will break indexing though (see #1749) unless a change to the Solr schema is made at the same time.

**Comment by pdurbin** [comment]
I just tried v. 4.2 build 39-e866445 on https://beta.dataverse.org and I'm pretty sure there's a bug with the Access facet. For a new, unpublished dataset, all files seem to show as Public until you publish. Then the ones you marked as restricted show as restricted. We might need to dig into the timing of when the boolean on `datafile.isRestricted()` returns true.

**Comment by pdurbin** [comment]
I brought this up at group meeting and @scolapasta and @raprasad seem to know what may be causing the public/restricted bug I reported at https://github.com/IQSS/dataverse/issues/2466#issuecomment-137480171 . @raprasad is going to give me a brain dump and I'll see if I can get the fix in for 4.2.

Also, everyone seems fine with me wanting to finalize the fields Solr fields as we did in #1314 so I'll write something up for the Dataverse 4.2 release notes (which I stubbed out at https://docs.google.com/document/d/1q3vKhVjkqyo9D_Cn4lImHROGOaJJOU9G1qxhpknLtxo/edit?usp=sharing ) and send an email around internally about the change. Hmm, we should probably have a public "dev" list for stuff like this.

**Comment by raprasad** [comment]
Both the ```filemetadata``` and ```datafile``` tables have the boolean attribute ```restricted```
From @scolapasta, the usage should be:

- file is **published** -> use ```datafile.restricted```
- file is **unpublished/draft** -> use ```filemetadata.restricted```

**Comment by pdurbin** [comment]
I made the change in 839a97e and it seems to work. Now you can see the change to the Access facet (Public vs. Restricted) even before you publish the dataset. Thanks, @raprasad! /cc @eaquigley since you asked if we can get this is 4.2 (yes, it's in).

**Comment by eaquigley** [comment]
👍👏



On Sep 8, 2015, at 2:05 PM, Philip Durbin <notifications@github.com<mailto:notifications@github.com>> wrote:


I made the change in 839a97e<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_commit_839a97e5e787b49443a7e0ce2dae612eb4a53ca9&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=Y9aY3P6kFFpmMLaYYO_id08dS3gL1xWMQuI2CZ74PoI&m=Uk6aw1Enuz1zvotiv_zue3QWHS-q1bVGrUF13_hZkvQ&s=vvBQPCSksrJWtQ-yJyFWS_QTCI5pof2kvlwvlya9C8U&e=> and it seems to work. Now you can see the change to the Access facet (Public vs. Restricted) even before you publish the dataset. Thanks, @raprasad<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_raprasad&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=Y9aY3P6kFFpmMLaYYO_id08dS3gL1xWMQuI2CZ74PoI&m=Uk6aw1Enuz1zvotiv_zue3QWHS-q1bVGrUF13_hZkvQ&s=AouIJ4-Uj6594VwOL_0OeAzdnpVcvmvfuCcj4JEn0q0&e=>! /cc @eaquigley<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_eaquigley&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=Y9aY3P6kFFpmMLaYYO_id08dS3gL1xWMQuI2CZ74PoI&m=Uk6aw1Enuz1zvotiv_zue3QWHS-q1bVGrUF13_hZkvQ&s=vI2wQbrhsQVXnI0XKRY4_H-Rtu1uUVy7HF5hoSuacaE&e=> since you asked if we can get this is 4.2 (yes, it's in).

**Comment by pdurbin** [comment]
@scolapasta and @eaquigley while I'm in here indexing file tags (are we still worried about confusion between file tags and DataTags?) I was thinking it would be nice to make file tags searchable from Advanced Search. In this case, I'd actually index two versions of the file tags into Solr:

- a string to facet on (exact match)
- a "text_en" that's nicely searchable, like the other fields on the advanced search page

We could also defer this until we work on #2455 but I figure we might as well make file tags nicely searchable if we're going to start indexing them anyway.

The reason I bring this up now is that we could roll all the changes into a single Solr schema.xml change for 4.2.

**Comment by pdurbin** [comment]
Ok, everyone should update to the Solr schema in the 4.2 branch: https://github.com/IQSS/dataverse/blob/4.2/conf/solr/4.6.0/schema.xml

Otherwise, you'll see errors like this:

- undefined field: "fileTag"
- undefined field: "fileTags"
- undefined field: "fileAccess"

The fileTags (plural) version is for the nicely searchable version I mentioned at https://github.com/IQSS/dataverse/issues/2466#issuecomment-138686567 . For now it's API-only, but again, please let me know if you'd like me to add this to the Advanced Search Page. I realized we *might* want highlighting too. It probably deserves its own ticket.

```
$ curl -s "http://localhost:8080/api/search?key=$FINCHKEY&q=fileTags:custom&show_relevance=true" | jq .data.items[].matches
[
  {
    "fileTags": {
      "snippets": [
        "This is my <span class=\"search-term-match\">custom</span> file tag"
      ]
    }
  }
]
```

Moving to QA.

**Comment by pdurbin** [comment]
@kcondon if you would take a look at #2325 at the same time, I'd appreciate it. I just left a comment: https://github.com/IQSS/dataverse/issues/2325#issuecomment-139541031 . Thanks.

**Comment by kcondon** [comment]
@pdurbin
OK, so to summarize, I am testing the following (nice to have a short list):
1. Access group of facets: public/ restricted
2. File Tag group of facets: file tags, not data tags are indexed.

**Comment by kcondon** [comment]
OK, both types of facets are present and work. Closing.
