### ISSUE TITLE
File Upload: Improve message when user tries to upload duplicate file.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2467]
See RT 225830
User attempted to upload a duplicate file with a different name to an existing set of files and became very frustrated because the app only said the file already exists but gave no other information.

I believe we used to provide more information. Maybe we can at least provide the duplicate file name and reason: 

A file with the same content ,<file name>, already exists identified by MD5: <MD5 value>.

**Comment by pdurbin** [comment]
@raprasad @landreev @sekmiller @scolapasta has the behavior changed in the 2290-file-replace branch? Is the GUI and the API consistent? I'm moving this to the dev column in Waffle so we can at least talk about it. It's highly related to #2290.

**Comment by mheppler** [comment]
In a meeting to review help messaging in the new Replace File workflow, we identified other file upload/edit/delete messaging that is inaccurate. I will make sure to include this issue, in our review.

**Comment by djbrooke** [comment]
Moving out of development. In #2290 we'll ensure messaging is appropriate for file replace. This will be reviewed/handled separately.

**Comment by pdurbin** [comment]
See also #3571.

**Comment by landreev** [comment]
@djbrooke @pdurbin 
I'm not sure why this issue resurfaces, or how it's related to the file replace task. 
It was opened a long time ago, because of users' complaints about error messages related to duplicate file uploads. This has been addressed since, and resolved, in 4.6. I believe it should be closed for good. 

So yeas, I agree, if there are any error messages specific to file replace, it should be addressed in 2290.

**Comment by pdurbin** [comment]
@landreev I agree. I'm parking this issue in Development so it can be associated with the pull request for #2290 once it exists.

**Comment by kcondon** [comment]
This now displays all duplicates such as when uploading a batch using zip and indicates which files in the zip are duplicates, skipping those that are dupes but uploading those that do not. Closing
