### ISSUE TITLE
Widgets: Add Branding to Data Listing Widget

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2469]
The data listing widget currently doesn't have The Dataverse Project logo on them or anything saying the widget is being populated from the Harvard Dataverse repository. We need to add branding to this widget.

**Comment by mheppler** [comment]
Made a quick mockup of some branding for the widget on Gary King's site.

![screen-shot-2015-11-03-at-12 52 14-pm](https://cloud.githubusercontent.com/assets/687227/10916580/11a75356-822a-11e5-948f-9cf559917870.jpg)

**Comment by mheppler** [comment]
Currently have a working prototype, that adds a block of code, below the iframe, which contains a "Data stored in the [Root Dataverse]" message, and link, as well as the "Powered by" message, Dataverse Project logo and dataverse.org link.

There are some questions about this approach, which changes the widget code, and how to best approach it for personal sites that are already using the widget code. Those will need to be answered before this code can be committed.

![screen shot 2015-11-05 at 4 52 38 pm](https://cloud.githubusercontent.com/assets/687227/10982941/03a5036a-83de-11e5-915e-9fc2d22f418d.png)

**Comment by mheppler** [comment]
Requirements outline as copied from [FRD](https://docs.google.com/document/d/12Y3HyAbhm69MqiHPci8Caxk3l_8m1uh64xCjVvPdyUk/edit).

**Dataverse Template**
- [x] Add new include for the footer block
  - [x] Rendering not to display copyright, links, version number in widget
  - [x] Rendering to display “Data is stored at…” msg, link to installation
  - [x] “Log in” link in footer to access admin features on full Dataverse installation

**iframe Template**
- [x] Add new include for the footer block

**Dataverse Listing Widget**
- [x] Dataverse branding w/ “Data is stored at…” msg, link to installation

**Dataset “Full” Widget**
- [x] Dataverse branding w/ “Data is stored at…” msg, link to installation

**Dataset Citation Widget**
- [x] Dataverse branding w/ “Data is stored at…” msg, link to installation

**Comment by kcondon** [comment]
OK, footer in place with link, message and logo. Closing.
