### ISSUE TITLE
Download Data: Review and potentially limit which user data is recorded when download.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2473]
A partner from Canada, currently running v3.6 (see RT 226031), has privacy concerns about collecting users' names and affiliation when downloading public files and making that information available to dataverse admins. 

They would like it to be at least limited to downloading restricted files and presented with a guestbook questionnaire that was clearly requesting that information. They would like any other record of download activity be anonymized or possibly aggregated.

There is some question whether Canada has specific privacy rules that differ from U.S. So should installations be able to turn off this feature completely?

Spoke with Merce and we should review this feature with the Berkman Center and depending on what they say, consider not collecting identifying user information unless they are presented with a guestbook questionnaire.

The partner's concerns centered around:
1. Tracking user activity/ collecting user identifiable information.
2. Making consent to tracking explicit.
3. Who can see such tracking information: dataverse or network admins.
4. Whether some level of deidentified stats can be gathered instead.

**Comment by djbrooke** [comment]
Unassigning myself for now, but could perhaps be rolled into 5.0 and the Sensitive Data project.
