### ISSUE TITLE
Homepage Cleanup #1 - Efficient retrieval of Card Attributes

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#2474]
part of #2472 

---

### Current process

1. Primary card attributes retrieved from Solr
1. Secondary card attributes from Postgres
1. During step (2) above, nearly all of the attributes in step (1) are re-retrieved.
  - When only specific “secondary” attributes are needed, full DvObjects are re-retrieved from the database and re-instantiated as full objects.  This degrades performance.

### Impact
Hundreds to thousands of extra queries are run to render the 10 cards.  The performance hit is a combination of both:
  -  The extra database query I/O and 
  -  Extra memory used to instantiate all of the extra/redundant objects.

### Suggested fixes

1. When possible, use Solr attributes instead of querying (or requerying) database.
1. Move several new attributes to the Solr documents.
1. Make efficient queries to retrieve other needed information.  
  - For example, tags for all the file cards may be retrieved in a single query--whether 1 card or 10 cards.
1. Make the attributes available as JSON in the SolrSearchResult.java and SolrSearchResponse.java

### Next Steps:  
Use the google spreadsheet below to decide which attributes:
-  Should be moved to Solr (fix 2 above) or
-  Have more efficient retrieval strategies (fix 3 above)	https://docs.google.com/a/harvard.edu/spreadsheets/d/1L8_4LU-8SG3Ubycfei5n2ufh1u-Lpszo4rghJMD2BFI/edit?usp=sharing

**Comment by kcondon** [comment]
Significant homepage performance changes were made, closing this for now. Can reopen if performance is deemed unacceptable in the future.
