### ISSUE TITLE
Homepage Cleanup #2 - Efficient Retrieval of File Images and Icons

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#2475]
part of #2472 

---
### Current Process

The retrieval of images and/or icons for cards eats up unnecessary processing time through these steps:

1. The system (again) retrieves the DvObject.  (Note: This is after the DvObject info has been (a) retrieved through Solr and (b) queries/re-instantiated through the database.  e.g. This is at least the 3rd time the DvObject info. has been retrieved.
1. A check is made of the file system to see if a thumbnail exists.
1. For files, if no thumbnail exists, a check is made for a file-type specific icon.  
1. If no thumbnail or specific icon exists, a default icon is used. 

### Impact
**_The page slows down through at least dozens of extra queries per image_**. The DvObjects are re-instantiated again.  Permissions and file system checks are made again.  The image URL given in the API often returns an empty string.  

#### Strategy 1 - Making images out of icons

In general, the Image URL in the API shouldn’t return an empty string.  It would be nice to have the appropriate icons available as images.  The link to the image thumbnail, whether an actual thumbnail or an icon thumbnail should be available in the database.

The steps might look like this:

1. API call made for image thumbnail
1. A database field contains the path to the actual thumbnail or a more general icon thumbnail.  (This seems quite rudimentary) **OR** database contains flag indicating whether image exists
1. There is no unnecessary checking of the file system or returning of empty strings in the Image URL

#### Strategy 2 - Checking for images and icons

This keeps the option of either showing a thumbnail image or an actual icon.

1. A database field indicates whether an actual thumbnail image exists and/or path to the thumbnail
1. For file type icons, the methods (as noted in the google spreadsheet) to determine the appropriate icon don’t need a DV File object--only the file type string.  https://docs.google.com/a/harvard.edu/spreadsheets/d/1L8_4LU-8SG3Ubycfei5n2ufh1u-Lpszo4rghJMD2BFI/edit?usp=sharing
1. There is no unnecessary checking of the file system or returning of empty strings in the Image URL

#### Possible discussion points

1. Keeping images in a separate location from the files themselves--especially for published files.  In this way, a direct url to the image may be used
1. Integrating optimatization for slower networks.  via @eaquigley: https://code.facebook.com/posts/991252547593574/the-technology-behind-preview-photos/

#### Next Steps
Pick a strategy from above and make the fixes.

**Comment by pdurbin** [comment]
Work is being done related to this in 4.2.2 in #2776 

I'm going to move this issue to the 4.2.2 milestone for a decision on if the two issues should go through QA at the same time.

**Comment by pdurbin** [comment]
@landreev can you please comment on if you'd like to keep this issue open, separate from #2776 ? If so, let's move it out of the 4.2.2 milestone.

**Comment by landreev** [comment]
I think this needs to be closed; as I did optimize the living crap out of the search card thumbnails, in 4.2.2.

**Comment by kcondon** [comment]
Significant homepage performance changes were made, closing this for now. Can reopen if performance is deemed unacceptable in the future.
