### ISSUE TITLE
Homepage #3 - For Searching and Filtering, Return JSON instead of rendered HTML

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#2476]
part of #2472 

---

#### _Front End_ 
For each search or facet click:
  - Currently: 90k to 130k of rendered HTML is returned. 
  - If switched:  8k to 22k of JSON would be returned*		
These numbers are based on experience with the MyData page which returns JSON--including information for cards, checkbox facets, and building pagination.

#### _Server Side_
As mentioned in #2474, hundreds to thousands of unnecessary queries are made and many redundant objects instantiated.  

### Impact

The page is below basic performance standards...e.g., average 7.x second load time with 43% of homepage loads over 7 seconds.

### Suggested fixes:

Use the basic MyData workflow for page rendering.

- All card and facet information would be included in a JSON document--most of this information would be from Solr.  (Takes advantage of the fixes in Improvement #1)
- The “SearchIncudeFragment” would transition to an API call to return JSON.  Javascript would be used to render the facets and cards
- Reuse the card templates across the homepage and MyData.
- As well as reuse, the templating would arguably be easier to create/read.
  - Homepage XHTML pager: https://gist.github.com/raprasad/3d6c6bc3b7deee51304b
  - Visual equivalent with Javascript:
https://gist.github.com/raprasad/8c325cc664aecd4b5699
(currently “turned off” on mydata page)

**Comment by kcondon** [comment]
Significant homepage performance changes were made, closing this for now. Can reopen if performance is deemed unacceptable in the future.
