### ISSUE TITLE
User Guide: Update User Guide to Reflect Feature Changes

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2480]
Need to add changes based on feedback from others as well as add in any new features.

**Comment by eaquigley** [comment]
Adding in:
-Terms of Use + Access to templates
-Uploading + Editing Files changes

**Comment by eaquigley** [comment]
Added these into the user guide. Passing to QA (@posixeleni) to check out and then close ticket.

Updated: dataset and file management, dataverse management, and finding and using data.

**Comment by kcondon** [comment]
@posixeleni I'm working on closing out the remaining v4.2 issues this week. This one is assigned to you, do you mind taking a look? I can also check if needed.

**Comment by pdurbin** [comment]
@posixeleni let's coordinate on setting up a git branch for you to use to push changes to docs for v4.2.

**Comment by eaquigley** [comment]
@pdurbin @posixeleni any changes can wait till next release. this was just for eleni to review what i added in for 4.2. i like having a sanity check.

**Comment by pdurbin** [comment]
@eaquigley ok, great. @posixeleni is welcome to edit the 4.3 guides at will in the 4.3 branch. Changes will show up at http://guides.dataverse.org/en/4.3

**Comment by posixeleni** [comment]
Docs for Terms of Use + adding Terms is very clear and answered all my questions.

Uploading + Editing Files changes looks good too.

However, @eaquigley  I noticed that under Edit Dataset it only talks about how to Edit Files but nothing about the entire Dataset's Metadata, Terms, Permissions. Maybe we need a seperate section just to describe how to Edit a Dataset in General and one about Edit Files in A Dataset http://guides.dataverse.org/en/4.2/user/dataset-management.html#edit-dataset

**Comment by kcondon** [comment]
@posixeleni @eaquigley 
It seems like the what's been added is ok but maybe additional info could be added.
So should this ticket be closed and a new one opened to address that last comment or should this ticket be moved to 4.3 to do additional work?

**Comment by eaquigley** [comment]
This one closed, new one created. I like having a ticket per release for updating the user guide.

**Comment by kcondon** [comment]
Closing, opened a new v4.3 ticket for the last comment: #2616
