### ISSUE TITLE
API Tokens: Add Done Button To Page

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2481]
There is no done button on the API Token page. Need to add this to the page so a user can easily exit.

**Comment by eaquigley** [comment]
Related to #1098

**Comment by pdurbin** [comment]
As of 0e08dca in pull request #3025 the API Token page has been changed from a separate page to tab so I think this issue no longer applies. I'm moving it to QA for 4.4, which is the release we hope to merge that pull request into.

**Comment by kcondon** [comment]
Page now a tab, closing.
