### ISSUE TITLE
User stats: No method to count new users

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#2485]
For these tables, add created/modified timestamp columns:
- authenticateduser
- builtinuser

**Time estimate:** 2-4 hours
**Special notes:** Need to run "add column" postgres command

**Comment by bencomp** [comment]
User account creation is logged in the table that stores `ActionLogRecord`s. See #1532.

**Comment by pdurbin** [comment]
Scratch work SQL scripts based on http://crossingtheruby.com/2013/12/15/time-series-with-postgresql.html - https://docs.google.com/a/harvard.edu/document/d/1_uJVRDeZCI46-ZEDfbQ5vUZ2wZUfSpL3errlDpCp-9E/edit?usp=sharing

**Comment by pdurbin** [comment]
Duplicate of #3246, I think.

**Comment by raprasad** [comment]
yes.  same ticket added each year:)

**Comment by pdurbin** [comment]
It's a tradition! 😄
