### ISSUE TITLE
My Data: Perms acquired via Explicit groups do not show role tags.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2487]
This is a regression: it was working in v4.1.

Assign a user to an explicit group, assign that explicit group admin perms to a dataverse that has datasets, go to my data for that user, see the objects in the list but with no roles.

**Comment by raprasad** [comment]
@kcondon, I just checked in a fix for this.

**Comment by kcondon** [comment]
@raprasad Mostly working, when display files, role from ds is removed, hide files, reappears.

**Comment by kcondon** [comment]
@raprasad The dropped ds roles in the presence of files is still happening, both for groups and individuals.

**Comment by raprasad** [comment]
Found a definite bug which is now fixed. Was able to reproduce bug and fix locally

**Comment by kcondon** [comment]
OK, works now. Closing.
