### ISSUE TITLE
MyData superuser bug

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#2488]
For superuser's MyData shows an input box that allows the entry of arbitrary usernames.

- **Incorrect**: Currently, the username defaults to DataverseAdmin.  
- **Correct**: It should default to the username of the logged in superuser.
![account_-_root_dataverse](https://cloud.githubusercontent.com/assets/1036060/9608889/9e02cae6-509e-11e5-90ee-0dabebc7d4fd.png)

**Comment by kcondon** [comment]
Works as described. Closing.
