### ISSUE TITLE
My Data: File Downloader role not appearing in child objects when assign at parent dv.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2489]
Create dv, ds, file. Assign file downloader at dv. In My data should show file downloader role at dv, ds, file. Instead, only shows it at dv.

**Comment by raprasad** [comment]
![banners_and_alerts_and_role_permission_relationships_-_harvard_dataverse](https://cloud.githubusercontent.com/assets/1036060/9615481/500e990a-50c6-11e5-9cfa-dac4c02147a7.png)

**Comment by kcondon** [comment]
Ok works, closing
