### ISSUE TITLE
File Upload: Uploading a relatively large number of larger files results in inability to save, need to start over.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2491]
See rt ticket 226580. User uploaded 60 files of around 750MB each overnight. In the morning, upload page showed all files present but they could not save and would prefer not to repeat the task.

The upload process is somewhat prone to inexplicable failures resulting in hung upload progress bars and also in this type of uploaded but not saved situations that effectively require users to start over. 

Best advice for now is to upload in smaller batches but can we make this more robust?

**Comment by bencomp** [comment]
We had a situation in DVN 3 in production where uploaded files were stored within the application environment (see also #2125) and it filled up the partition. Glassfish got into problems and some sessions may have been killed causing the UI to hang.

**Comment by kcondon** [comment]
Consolidating to #2482, closing.
