### ISSUE TITLE
404 when clicking link to API Guide from API token page

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#2494]
https://dataverse-demo.iq.harvard.edu/account/apitoken links to https://dataverse-demo.iq.harvard.edu/guides/API/index.html but it's a 404. As of this writing it should link to http://guides.dataverse.org/en/4.1/api

**Comment by pdurbin** [comment]
I just discovered a related problem. If you go to https://beta.dataverse.org/dataverse/root?q=foo:bar and click "search guide" you are taken to https://beta.dataverse.org/guides/user/find-use-data.html which is a 404.

We moved away from hosting the guides on the server itself in #2153 and related issues.

**Comment by pdurbin** [comment]
While I was fixing the two bad links to pages under "/guides" on the server itself, I found a third similar problem and fixed it too. Here are examples to where you can still see the 404s as of v. 4.2 build 39-e866445 (all fixed as of c576131)

- https://beta.dataverse.org/account/apitoken (apitoken.message)
- https://beta.dataverse.org/dataverse/root?q=foo:bar (dataverse.results.empty.zero)
- https://beta.dataverse.org/dataverse/root?q=saml&types=dataverses (dataverse.results.empty.hidden)

Moving to QA.

**Comment by kcondon** [comment]
OK, all cases are now resolving: links embedded in info messages on pages: apitoken, search where no results found, search where only files found, then files deselected.

Closing.
