### ISSUE TITLE
SWORD: not authorized when dataset is in root dataverse

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#2495]
First reported at [SWORD access failed - not authorized - Google Groups](https://groups.google.com/forum/#!msg/dataverse-community/G9TMVnhab5A/InZ9Zxg8CQAJ) and confirmed on https://dataverse-demo.iq.harvard.edu running v. 4.1 build 71, users are unable to operate on datasets created in the root dataverse via SWORD.

Examples of trying to to retrieve the Atom Entry and SWORD Statement are below.

The reason this doesn't work is that as noted at http://guides.dataverse.org/en/4.1/api/sword.html#known-issues SWORD does not yet take advantage of the granular Dataverse 4.0 permission system. Rather it still always checks for "admin" rights on the parent dataverse just like how it did in DVN 3.6. The ticket to track the required work to fix this is #1070. Technically, it's not "admin" that is checked but `permissionService.requestOn(dataverseRequest, dataverse).has(Permission.EditDataverse)` which was deemed to be more or less equivalent to admin.

Users are *not* expected to have this permission on the root dataverse, of course. Until #1070 is fixed we might want to clarify the known issue about the problems with datasets in the root dataverse.

#1443 is related.

```
murphy:dataverse pdurbin$ curl -s -u $API_TOKEN: https://dataverse-demo.iq.harvard.edu/dvn/api/data-deposit/v1.1/swordv2/edit/study/doi:10.5072/FK2/P2IPDE | xmllint -format -
<?xml version="1.0" encoding="ISO-8859-1"?>
<sword:error xmlns:sword="http://purl.org/net/sword/terms/" href="http://purl.org/net/sword/error/ErrorBadRequest">
  <atom:title xmlns:atom="http://www.w3.org/2005/Atom">ERROR</atom:title>
  <atom:updated xmlns:atom="http://www.w3.org/2005/Atom">2015-09-03T10:28:50Z</atom:updated>
  <atom:generator xmlns:atom="http://www.w3.org/2005/Atom" uri="http://www.swordapp.org/" version="2.0"/>
  <sword:treatment>Processing failed</sword:treatment>
  <atom:summary xmlns:atom="http://www.w3.org/2005/Atom">User Fiona Finch is not authorized to retrieve entry for doi:10.5072/FK2/P2IPDE</atom:summary>
</sword:error>
murphy:dataverse pdurbin$ 
murphy:dataverse pdurbin$ curl -s -u $API_TOKEN: https://dataverse-demo.iq.harvard.edu/dvn/api/data-deposit/v1.1/swordv2/statement/study/doi:10.5072/FK2/P2IPDE | xmllint -format -
<?xml version="1.0" encoding="ISO-8859-1"?>
<sword:error xmlns:sword="http://purl.org/net/sword/terms/" href="http://purl.org/net/sword/error/ErrorBadRequest">
  <atom:title xmlns:atom="http://www.w3.org/2005/Atom">ERROR</atom:title>
  <atom:updated xmlns:atom="http://www.w3.org/2005/Atom">2015-09-03T10:31:25Z</atom:updated>
  <atom:generator xmlns:atom="http://www.w3.org/2005/Atom" uri="http://www.swordapp.org/" version="2.0"/>
  <sword:treatment>Processing failed</sword:treatment>
  <atom:summary xmlns:atom="http://www.w3.org/2005/Atom">user Fiona Finch is not authorized to view dataset with global ID doi:10.5072/FK2/P2IPDE</atom:summary>
</sword:error>
murphy:dataverse pdurbin$
```

**Comment by pdurbin** [comment]
This issue is so highly related to #1070 (which I'm working on now) that I just assigned myself to it so I remember to at least leave a comment after I make a pull request. I'm trying to make use of the existing ListDataverseContentCommand even thought it's been problematic per #2122 and #3058.

**Comment by pdurbin** [comment]
I just opened pull request #3137 as a fix for this issue. Passing to QA.

**Comment by kcondon** [comment]
Leaving in QA but removing my name until I receive pull request.

**Comment by kcondon** [comment]
Tested and works in root dv. Closing.
