### ISSUE TITLE
Migration: NullPointerException when importing a DDI file

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#2496]
Reproducible with `curl "http://localhost:8080/api/batch/migrate?path=/tmp/ddi2/pdurbin&dv=pdurbin&key=$API_TOKEN`

... at edu.harvard.iq.dataverse.engine.command.impl.CreateDatasetCommand.execute(CreateDatasetCommand.java:182)
...
Caused by: java.lang.NullPointerException
	at edu.harvard.iq.dataverse.search.IndexServiceBean.indexDataset(IndexServiceBean.java:294)

I'm on commit 7319fb1 . @scolapasta asked me to take a look. As he found, the NPE is at `                List<String> allFilesForDataset = findFilesOfParentDataset(dataset.getId());`

**Comment by pdurbin** [comment]
I put in a fix at 5e5dcf5 but I'll hold on to this ticket to see if we need a better one. This one catches the NPE and prints "could not run search of files to delete: NullPointerException".

**Comment by pdurbin** [comment]
I spoke with @kcondon this morning and since we agree that Solr will be down during a migration scenario, the quick fix I put it should be fine. Passing to QA.

**Comment by kcondon** [comment]
OK, error is suppressed, will reopen if we continue to have issues.
