### ISSUE TITLE
Dataverse - Remove Pagination from Above Results Listing

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#2498]
When a browser window is small enough, and there are many results being displayed on the dataverse page, the pagination at the top of the results can break to a second line, as can the results count.

To fix this, we should remove the pagination from the top of the page, and leave only the pagination at the bottom. The top pagination block is redundant, and doesn't fit with the workflow where a user navigates to the next page of results, only after they have reviewed all the results on the page, which they'd need to scroll to the bottom to do -- which is where the pagination component will be waiting for them.

![screen shot 2015-09-08 at 3 07 49 pm](https://cloud.githubusercontent.com/assets/687227/9744705/6b2cdce0-563b-11e5-93eb-377103e804ba.png)

**Comment by mheppler** [comment]
Also, the type facets in the side column are breaking to a second line in that screenshot. Those also should be displayed in a cleaner manner, on a single line, in small browser windows. (Related to #811.)

**Comment by mheppler** [comment]
Improved responsiveness of search-include-fragment, introduced a toggle button for the facets side column for small viewport, removed pagination from top of results listing.

![screen shot 2015-09-09 at 3 44 07 pm](https://cloud.githubusercontent.com/assets/687227/9772360/b2f9693e-5709-11e5-9564-1c88d56ab7dc.png)
![screen shot 2015-09-09 at 3 44 26 pm](https://cloud.githubusercontent.com/assets/687227/9772362/b56da090-5709-11e5-9d37-678f565e7a42.png)

**Comment by kcondon** [comment]
Looks good, closing
