### ISSUE TITLE
Permissions

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#25]
---

Author Name: **Gustavo Durand** (@scolapasta)
Original Redmine Issue: 3432, https://redmine.hmdc.harvard.edu/issues/3432
Original Date: 2014-02-03
Original Assignee: Michael Bar-Sinai

---

With 4.0 being a rewrite of the code base, this ticket represents one of the core functional components to be done. Individual items that can be tested separately or need to be passed to another developer or designer should be added as new tickets under this one.

* Management of permissions by setting up roles and users and groups
* Creation of individual commands
* All actions using the new command design pattern to check if user has permissions (or in a group that does)
* Individual developers should be adding the use of the commands to the proper rendered fields in the UI and to the backing bean or API calls.

---

Related issue(s): #57
Redmine related issue(s): [3464](https://redmine.hmdc.harvard.edu/issues/3464)

---

---

Child issue(s): #87, #88, #91, #92, #343, #345, #602, #650, #651
Redmine child issue(s): [3496](https://redmine.hmdc.harvard.edu/issues/3496), [3497](https://redmine.hmdc.harvard.edu/issues/3497), [3500](https://redmine.hmdc.harvard.edu/issues/3500), [3501](https://redmine.hmdc.harvard.edu/issues/3501), [3758](https://redmine.hmdc.harvard.edu/issues/3758), [3760](https://redmine.hmdc.harvard.edu/issues/3760), [4033](https://redmine.hmdc.harvard.edu/issues/4033), [4100](https://redmine.hmdc.harvard.edu/issues/4100), [4101](https://redmine.hmdc.harvard.edu/issues/4101)

---

**Comment by scolapasta** [comment]
This is the high level permissions tickets - what's left has been broken out into individual issues. Passing to QA.

**Comment by kcondon** [comment]
OK, basic permissions were delivered with the exception of groups and file level permissions. There are separate tickets for groups and I know file perms are being worked on but @scolapasta is there a ticket for file permissions?

Closing this.
