### ISSUE TITLE
Dataset - Floating Issue for Citation Block + Metadata Fields

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#2500]
When a browser window is small enough, it causes floating issues for the Download Citation button and the values for metadata fields, where those elements will break to the next line.

Bootstrap's grid system provides a way to fix this, with it's responsive layout options. This is something that was either overlooked or developed incorrectly and can easily be fixed.

![screen shot 2015-09-09 at 1 42 54 pm](https://cloud.githubusercontent.com/assets/687227/9769631/4a3e7cbe-56f9-11e5-9998-25ae62e37347.png)

**Comment by mheppler** [comment]
Cleaned up the dataset page and site page template to be more responsive.

The citation block now has more room in smaller browser windows, as do the metadata fields, with some minor tweeking of our CSS and the use of Bootstrap's grid layout. In small mobile devices, the metadata values will float under their labels, so they have more room for the data.

The font of the footer has been bumped down, and styled grey, so it less heavy. Similar CSS tweaking was done to improve floating issues.

**Comment by mheppler** [comment]
Related to UI Layout: Make sure page layouts work in all screen resolutions, via bootstrap. #811

**Comment by kcondon** [comment]
Looks good, closing.
