### ISSUE TITLE
File Landing - UI Cleanup

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#2504]
- [ ] "Download" button (missing from UI currently)
- [ ] "Explore" button (missing from UI currently)
- [ ] "Request Access" button (missing from UI currently)
- [x] Preview image/icon (too small)
- [x] Citation block (style)
- [x] Draft/In Review/Unpublished labels (new feature, need to be added next to file title)
- [x] Tags (placement, label?)
- [x] Metadata block (style labels, values)
- [x] Restricted icon missing
- [x] MD5, UNF, Variables, Observations
- [ ] Edit dropdown needs to have same options as on dataset page

**Comment by mheppler** [comment]
In the 4.2.1 release, there were UI changes to the dataset pg [ref #2650], and as a result the remaining cleanup issues above have been completed. I'll leave them unchecked however, so QA can review.

<img width="1186" alt="screen shot 2015-10-22 at 11 08 49 am" src="https://cloud.githubusercontent.com/assets/687227/10669156/5b482110-78ad-11e5-8c10-b6aae8f35323.png">

**Comment by kcondon** [comment]
OK, seems fine, closing.
