### ISSUE TITLE
Dataset Page File Tab: Add Facets

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2508]
Based off this mockup: https://iqssharvard.mybalsamiq.com/projects/filesprovenancefacetsfilter-dataverse40/grid need to add facets to file tab.

**Comment by mheppler** [comment]
A new issue, **Dataset - File UI Improvements #3404**, was created to track the UI improvements related to the files view on the dataset pg. Older feature requests and bug reports like this one will be closed in favor of that new issue.
