### ISSUE TITLE
Dataset Page File Tab: Add View All + View More

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2509]
Based on mockups: https://iqssharvard.mybalsamiq.com/projects/filesprovenancefacetsfilter-dataverse40/grid

Instead of pagination have view all and view more options for going through files.

**Comment by eaquigley** [comment]
Infinite scroll was added in during a previous release and there is a ticket for View All button (#2705). Passing this ticket to QA to close as a duplicate.

**Comment by kcondon** [comment]
Closing
