### ISSUE TITLE
Files: Link to File Should Go to File Landing Page

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2510]
Workflow:

Dataverse page->select files in type facet->click on file name in card->brought to correct file landing page

Currently a user is being brought to the dataset page. Needs to be updated to go to file landing page.

**Comment by sekmiller** [comment]
Fix requires a new build. otherwise ready for testing.

**Comment by kcondon** [comment]
OK, now brought to the file landing page. Closing.
