### ISSUE TITLE
Files: Various issues related to editing files

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2511]
1. Cannot save file edits if dataset is published, does nothing, throws server log error, null dataset id.
2. Deleting a file does not remove it from the list before saving so can edit it, then it won't delete.
3. Restrict button needs to be on edit files (metadata) page.
4. Tag button (bulk update) needs to be on the edit files (metadata) page, above file list according to mockups.

**Comment by landreev** [comment]
Kevin, 
Please re-test 1., 2., and 3. 
As for the 4. - bulk update of file tags - it's a new feature that Steve has just added to the dataset page. 
It should be easy to copy it to this editFiles page now - but I haven't had time to do so for 4.2. I'm going to ask on Monday to reschedule it to 4.3.

**Comment by kcondon** [comment]
OK, retested 1, 2, 3. 1 (save on published) and 3 (restrict) work but 2 (delete) still has an issue.

-Clicking cancel on delete, then clicking delete again, removes the wrong file from the list:
Select 2 files, 1,2. Edit metadata. Choose file 2, click delete. Click cancel, then delete, save. The wrong file (1) gets removed.

**Comment by landreev** [comment]
Committed the fixes for the following issues brought up during the meeting: 
1. removed the stray file type from the file display;
2. removed the "no files in this dataset" message;
3. added a redirect back to the file landing page, if the edit request came from that page;
4. added breadcrumbs to the page.

**Comment by landreev** [comment]
(still looking into the "cancel on delete" issue)

**Comment by kcondon** [comment]
OK, the new 1-4 are completed, delete cancel is still  open.

**Comment by landreev** [comment]
Kevin, 
Please re-test the delete issue. Should be working properly now. 
(I may be wrong, but I don't think cancel was a factor there; I believe it was just an existing DRAFT version vs. published version w/ no DRAFT - with the wrong file getting removed from the list in the latter case...)

**Comment by kcondon** [comment]
OK, delete cancel now works. The only thing left from the original list is bulk edit of tags which is scheduled for 4.3. Passing back and marking as 4.3.

**Comment by landreev** [comment]
OK, I may open a separate ticket for the bulk edit of tags, that we agreed to implement in 4.3.
So that we could close this one (there's already a lot in this ticket...)

**Comment by eaquigley** [comment]
Created #2842 for the edit tags button missing. Passing this ticket to QA for @kcondon to close.

**Comment by kcondon** [comment]
Closing
