### ISSUE TITLE
Hide File Landing Page from 4.2 - show in Beta for now

### ISSUE THREAD

**Issue by sekmiller** [IQSS/dataverse#2515]
While we complete the functionality of the File Landing Page we want to keep it out of the 4.2 release but display it in Beta.

I added renders to the links in the search include fragment and the filesFragment.

In order to get the links to the File Landing Page to display run the following insert query in the Beta Database:

INSERT INTO setting(
            name, content)
    VALUES (':ShowFileLandingPage', 1);

**Comment by kcondon** [comment]
Works great, closing.
