### ISSUE TITLE
Delete files: Put spaces between file names in success message before save.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2517]
When deleting files on edit metadata page, the files to be deleted are listed in the success message but have no space between names so is hard to read.

**Comment by eaquigley** [comment]
@kcondon I'm passing this back to you to take a look at again since we have changed how these tabs are designed. i am guessing when it says edit metadata page you are referring to when editing metadata of a dataset and uploading files were on the same page.

**Comment by kcondon** [comment]
This still happens: select some files, edit, then select some files on edit view, delete, see success message with file names without spaces in message (worse when you delete many):

 Success! – Files onea.txtShortFile.txt will be permanently deleted from this version of this dataset once you click on the Save Changes button.

**Comment by scolapasta** [comment]
Duplicate of #2224

**Comment by kcondon** [comment]
Closing.
