### ISSUE TITLE
File Ingest: Support user defined missing values in addition to system missing values in SPSS (and other formats?)

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2518]
A user pointed out that the SPSS ingest does not support user defined missing values so it throws off the summary stats. They would like this to be supported, see RT ticket 226587:

This is pretty common with social survey data, because you need to be able
to specify that data can be "missing" for different reasons - e.g. the
respondent didn't know the answer vs. the respondent refused to answer the
question. So you give the different types of missing values different
codes.

Hope this helps! And let us know if we can assist in any way in fixing this
bug - we've worked a lot with this kind of data.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
