### ISSUE TITLE
Edit Files:  Restricting/restricted files on Edit metadata page does not display lock icon.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2520]
In v4.1, on the edit files page, as soon as you restricted a file, a lock icon appeared before save and they appear when you edit files that are restricted.

In v4.2, no lock icon appears ever on the edit files page, when restricting or when editing a restricted file.

Also, a slight bug in v4.1, the lock should be open green one on edit page since you have access but it showed up as red.

**Comment by landreev** [comment]
Please re-test. 
I saw the "red lock instead of green" condition you mention at least once. From what you are saying it sounds like this is something we've inherited from 4.1, correct? Also, it went away after I reloaded the draft version.

**Comment by kcondon** [comment]
Locks still do not appear on the edit files page. They do appear on the dataset listing page.

**Comment by landreev** [comment]
Should be there now.

**Comment by kcondon** [comment]
Still not appearing

**Comment by kcondon** [comment]
Works, closing
