### ISSUE TITLE
Installation: use -server rather than -client JVM option for Glassfish

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#2521]
By default Glassfish has `<jvm-options>-client</jvm-options>` in domain.xml but in the DVN 3.x days we recommended changing this from `-client` to `-server`: http://guides.dataverse.org/en/3.6.2/dataverse-installer-main.html

I imagine that [glassfish-setup.sh](https://github.com/IQSS/dataverse/blob/master/scripts/installer/glassfish-setup.sh) is the best place to make this change so that it's picked up in all environments (installations, developer laptops, Vagrant). We should probably also document this in the Installation Guide (#2321).

I don't know much about the reason for the change but it's what we run in production and http://blog.c2b2.co.uk/2013/07/glassfish-4-performance-tuning.html has good things to say about it:

> The standard JVM defaults are not suitable for a production system. One of the simplest changes that can be made is to use the -server flag, rather than the default -client. Although the Server and Client VMs are similar, the Server VM has been specially tuned to maximise peak operating speed. It is intended for executing long-running server applications, which need the fastest possible operating speed more than a fast start-up time or smaller runtime memory footprint.

**Comment by pdurbin** [comment]
In my pull request at #2895 I addressed this issue. The change can be previewed at http://guides.dataverse.org/en/2884-install-guide-reorg/installation/prerequisites.html#glassfish

Passing to QA.

**Comment by kcondon** [comment]
Documented, closing.
