### ISSUE TITLE
Templates: no error message when name is not filled out

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2522]
When creating a template, if a user clicks the save and add terms button and has not added a name for the template, the page stays at the bottom by the buttons. There is no validation message appearing on the page.

**Comment by sekmiller** [comment]
This is fixed and checked in (thanks for catching it) a new build is needed for testing.  Kevin is making one momentarily

**Comment by eaquigley** [comment]
working perfectly! thanks! closing ticket
