### ISSUE TITLE
Edit + Upload Files - UI Cleanup

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#2523]
- [x] Page title and breadcrumbs "Edit/Upload Files"
- [x] Return info help text block to Upload workflow
- [x] Return "Files" tab
- [x] Upload and edit specific empty message for dataTable

**Comment by mheppler** [comment]
Found a comment in the EditDatafilesPage.java that seems to imply that the info help block for the edit and upload file workflows wasn't wired up completely.

````
/* TODO: is it needed? */
````

Got confirmation that it is needed on the upload workflow, not the edit, since the upload widget is no longer displayed for that workflow. I have edited the bundle message and the backing beans to remove the reference to the edit workflow. 

Passing to @landreev to wire up for the upload workflow.

**Comment by landreev** [comment]
@mheppler, could you please stop by and show me what needs to be done? 
I'm seeing the "is it needed?" comment in the Edit Files page bean - but I don't think it has anything to do with the help messages...

**Comment by landreev** [comment]
OK, done. 
That edit() method was no longer in use; so I removed it, and added the following to the end of the page init() method: 

        if (mode == FileEditMode.UPLOAD) {
            JH.addMessage(FacesMessage.SEVERITY_INFO, JH.localize("dataset.message.uploadFiles"));
        }

**Comment by mheppler** [comment]
Looks good. Thanks!

**Comment by kcondon** [comment]
OK looks good, closing
