### ISSUE TITLE
Dataset In Review Notifications - Admin not notified if dataset is "resubmitted"

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2526]
Currently, admins don't get another notification of a previously submitted dataset being edited and resubmitted for review.

The bigger issue that has been discovered with "In Review" which is the "In Review" is just a flag and does not actually change the state of the dataset (such as changing it from Draft to In Review it is still a Draft just with an extra label on it).

**Comment by pdurbin** [comment]
> The bigger issue that has been discovered with "In Review" which is the "In Review" is just a flag and does not actually change the state of the dataset (such as changing it from Draft to In Review it is still a Draft just with an extra label on it).

Right. See https://github.com/IQSS/dataverse/issues/2554#issuecomment-141967451 for an example of how the boolean seems to work but it isn't always cleared, it seems.

**Comment by pdurbin** [comment]
Related: #3943.

**Comment by pdurbin** [comment]
@pameyer is this something you want?

**Comment by pameyer** [comment]
@pdurbin : [user submits for review] -> [user remembers something and makes changes] -> [dataset gets kicked out of "in review" state] -> [user submits for review again]; I'd think the second "submit for review" should act the same way as the first one in terms of notifications.

You could make the case for a notification to the curator(s) when a dataset leaves the "in review" state; but the failure mode there is cleaner in the absence of a notification.

**Comment by pdurbin** [comment]
@pameyer ok, I just confirmed via API tests in 886538e that the author gets a notification both times but I'll re-test the GUI after @sekmiller refactors the logic into commands.

**Comment by pdurbin** [comment]
I believe this bug is fixed in pull request #3992 so I added the "connect to" Waffle syntax to it.

**Comment by pdurbin** [comment]
@pameyer I see you moved this to the backlog and I assume that means that you don't think pull request #3992 fixed it!

**Comment by pameyer** [comment]
@pdurbin moving it back meant that I wanted to check if it was fixed or not

**Comment by pdurbin** [comment]
Oh! Great! Please keep us posted!

**Comment by djbrooke** [comment]
@pameyer - is this one fixed?

**Comment by pameyer** [comment]
@djbrooke - not sure yet. Will need to do an update of our fork prior to testing.

**Comment by pameyer** [comment]
Finally checked 915c9fa1ff2208e3b0f9ab585ec37bb110651566 (file DOI branch); it's fixed there.
