### ISSUE TITLE
Updated Controlled Vocabulary for Life Sciences and Citation Metadata Not Showing in Production

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#2527]
Need a developer to look at this:

Issue was reported by user who had requested we add certain controlled vocabulary values to the Life Sciences block, which we had added to Dataverse in June (see #2083) but I no longer see these new values which are in the https://github.com/IQSS/dataverse/blob/4.2/scripts/api/data/metadatablocks/biomedical.tsv

Example: 

Check DesignType field: There you should find: "Cohort Study" but it is not in the list.

@sekmiller @kcondon

**Comment by posixeleni** [comment]
Based on the same commit https://github.com/IQSS/dataverse/commit/752212d6c99d7035d4d72e43d36b6bb9672cb9ca "Agricultural Sciences" had been added in the citation.tsv under the Subject controlled vocabulary but this is also not showing in production.

**Comment by posixeleni** [comment]
Working with @kcondon and @scolapasta to resolve this issue and have both the 
citation.tsv and biomedical.tsv files updated in production.

**Comment by kcondon** [comment]
In production confirmed by Eleni. Closing
