### ISSUE TITLE
Dataset page: Batch restrict does not display terms of access popup as in previous workflow.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2528]
Batch restrict does not display terms of access popup as in previous workflow.

This was mentioned by Merce in the context of the file landing page but it was noted that it also is missing from the dataset batch restrict workflow. Gustavo asked for this ticket. This happens on both dataset file listing and edit files pages.

**Comment by sekmiller** [comment]
Popup will be shown to the admin every time a file is newly restricted, as was the case in 4.1

A new build required for testing

**Comment by kcondon** [comment]
This working on the dataset page but does not appear on the edit files page.

**Comment by sekmiller** [comment]
Here's the ticket you were asking about yesterday

**Comment by landreev** [comment]
This ticket should be in QA... (I didn't have to do anything for it - Steve fixed it)

**Comment by kcondon** [comment]
OK, pops up when needed. Closing.
