### ISSUE TITLE
Indexing: "index all" should not clear Solr index or timestamps, add separate "clear" API endpoint for this

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#2529]
@scolapasta and I decided we want a separate API endpoint for clearing all data from Solr and all indexing timestamps from the database: http://localhost:8080/api/admin/index/clear

@kcondon and agree that in production it's very rare that we'd want an "index all" to do all this clearing of Solr data and database timestamps (otherwise the homepage would look relatively empty as indexing slowly completes per #50) so we'll change the behavior to prevent this clearing of data and timestamps. Instead, installations should use the new "clear" API endpoint if they want a fresh index.

**Comment by pdurbin** [comment]
@scolapasta let's defer the idea of allowing installations have "index all" also do a "clear" (powered by a boolean). I think having the separate API endpoints is enough for 4.2 (the code is complex enough already) and I left a todo in the code: https://github.com/IQSS/dataverse/commit/1f929ba25f0ba7c4da627e8d8bdd323911280145#diff-50498e2946cf2df8ba43e444c463b998R82

@kcondon here's how I've been testing the new "clear" method:

```
murphy:dataverse pdurbin$ curl -i http://localhost:8080/api/admin/index/clear | jq .
 {
  "status": "OK",
  "data": {
    "numRowsClearedByClearAllIndexTimes": 12,
    "message": "Solr index and database index timestamps cleared."
  }
}

As before, "index all" is http://localhost:8080/api/admin/index but now it doesn't clear Solr data or database timestamps. I know we discussed documenting reindexing in the Installation Guide but I'm going to looks at some more code-related issues first. Moving to QA.

**Comment by kcondon** [comment]
Index all does not clear index times, does not delete existing index but updates in place. Clear api works, closing.
