### ISSUE TITLE
Indexing: add field for which version of Dataverse did the indexing (dataverseVersionIndexedBy_s)

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#2530]
@scolapasta and I have been talking about how it would be useful (especially after an upgrade) to be able to query Solr and know which version of Dataverse was used to index a particular DvObject.

**Comment by pdurbin** [comment]
In 22713ec I added a field called `dataverseVersionIndexedBy_s`. This is a dynamic field (`*_s`) because it isn't user-facing. Since it's dynamic, we don't need a new Solr schema.xml

Here's how you might use this new field:

## Show DvObjects indexed by Dataverse 4.2 (fq=dataverseVersionIndexedBy_s:4.2)

`curl -s 'http://localhost:8983/solr/collection1/select?rows=1000000&wt=json&indent=true&q=entityId:*&fq=dataverseVersionIndexedBy_s:4.2' | jq '.response.docs[] | {id,dataverseVersionIndexedBy_s}'`

```
{
  "id": "dataverse_31",
  "dataverseVersionIndexedBy_s": "4.2"
}
{
  "id": "dataverse_27",
  "dataverseVersionIndexedBy_s": "4.2"
}
{
  "id": "dataverse_25",
  "dataverseVersionIndexedBy_s": "4.2"
}
{
  "id": "dataverse_29",
  "dataverseVersionIndexedBy_s": "4.2"
}
{
  "id": "dataset_33_draft",
  "dataverseVersionIndexedBy_s": "4.2"
}
```

## Show DvObjects **not** indexed by Dataverse 4.2 (fq=-dataverseVersionIndexedBy_s:4.2)

`curl -s 'http://localhost:8983/solr/collection1/select?rows=1000000&wt=json&indent=true&q=entityId:*&fq=-dataverseVersionIndexedBy_s:4.2' | jq '.response.docs[] | {id,dataverseVersionIndexedBy_s}'`

```
{
  "id": "dataset_32_draft",
  "dataverseVersionIndexedBy_s": null
}
{
  "id": "datafile_34_draft",
  "dataverseVersionIndexedBy_s": null
}
{
  "id": "dataverse_28",
  "dataverseVersionIndexedBy_s": null
}
{
  "id": "dataverse_26",
  "dataverseVersionIndexedBy_s": null
}
{
  "id": "dataverse_30",
  "dataverseVersionIndexedBy_s": null
}
{
  "id": "dataverse_24",
  "dataverseVersionIndexedBy_s": null
}
```

Passing to QA.

**Comment by kcondon** [comment]
Works as described, just remember to remove the -s from the above statement or you will see no output.

Closing.
