### ISSUE TITLE
saved search: currently does not automatically update to include "new" additions to the search query - need a script that calls into the API on a periodic basis.

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2531]
The deliverable for this issue could be a script that calls into the API on a periodic basis. The API endpoint does exist already and is mentioned at https://github.com/IQSS/dataverse/issues/90#issuecomment-85987398 and https://github.com/IQSS/dataverse/issues/1852#issuecomment-89027304 but I'll document the situation better in the Installation Guide.

User reference ticket: https://help.hmdc.harvard.edu/Ticket/Display.html?id=227022

**Comment by pdurbin** [comment]
@sbarbosadataverse and I have been chatting about this and I've been taking notes while executing a saved search that's defined at the "Soils" dataverse ( https://dataverse.harvard.edu/dataverse/soils ): https://docs.google.com/a/harvard.edu/document/d/1UdDpAFmcdc2BrILCJ8Vpwz1Vmh3pVNugo5tvyZ7D1Gs/edit?usp=sharing

We decided for now we'll execute the saved searches at midnight unless there are any objections internally.

**Comment by kcondon** [comment]
@pdurbin @scolapasta Would a glassfish timer job be better, require less external config?

**Comment by pdurbin** [comment]
@kcondon yes that would be better and is what we have in mind some day. I just created an issue for this: #2543.

**Comment by kcondon** [comment]
Actually I was just talking about the simple case. We can still call it via api, just as a timer job within the app. I would think we should think about doing from the get go.
________________________________

**Comment by pdurbin** [comment]
@kcondon right, the proposed deliverable for 4.2 is documentation or maybe a script. For now I'm using a Google Doc for notes: https://docs.google.com/a/harvard.edu/document/d/1UdDpAFmcdc2BrILCJ8Vpwz1Vmh3pVNugo5tvyZ7D1Gs/edit?usp=sharing

**Comment by pdurbin** [comment]
I documented the fact that Saved Search is experimental (including warnings about the fact that you can't delete links per #1364 which I think is reason enough to stay away from the Saved Search, Linked Dataverses, and Linked Datasets features) an explained that API endpoints must be called for Saved Search and Linked Dataverses to have fresh data based on new content.

I'm moving this to QA to review what I wrote at http://guides.dataverse.org/en/4.2/api/native-api.html#saved-search

On that page I link back to this issue which has a detailed example of setting up a cron job for Saved Search in a Google Doc: https://docs.google.com/a/harvard.edu/document/d/1UdDpAFmcdc2BrILCJ8Vpwz1Vmh3pVNugo5tvyZ7D1Gs/edit?usp=sharing . (The executive summary is to put something like this in cron: `10 0 * * * curl -s -X PUT http://localhost:8080/api/admin/savedsearches/makelinks/219?debug=true | jq . > /tmp/savedsearch219.json` .)

**Comment by kcondon** [comment]
OK, that's fine if we'e not at the point of making a complete feature. I'm not sure who scoped the ticket, it wasn't Sonia though she created it apparently. I will make sure it works according to the ticket's scope.

**Comment by kcondon** [comment]
Looks good, closing.
