### ISSUE TITLE
Ingest: When ingest of tabular data file completes, top level edit button is reenabled but batch edit is not and checkboxes and download buttons not working.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2532]
Tested with Chrome.

Upload tabular files such that edit is temporarily disabled while ingesting, use my test_files.zip file for example.

When ingest completes, the top level edit button is reenabled but the batch edit button and download (selected) us grayed out. I know in part this is due to requiring a checkbox to be checked. I did the top checkbox, nothing. Individual file checkboxes are not working. Download individual files buttons not working, Upload files button is. Seems like the page is partially broken. Notice spinner periodically keeps running/ exiting/ running.

Reloading the page works (had to go to homepage, return since refresh was hanging).

**Comment by sekmiller** [comment]
Not seeing this one either.  I will send you the file I have that "takes a long time to ingest"

**Comment by kcondon** [comment]
OK, this is working better now. Closing.
