### ISSUE TITLE
Harvest / Import da | ra metadata schema

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#2533]
Work with GESIS to harvest their datasets which use the da | ra metadata schema via OAI-PMH into Dataverse.  Waiting for them to send me their OAI URL so I can work on mapping a crosswalk.

**Comment by posixeleni** [comment]
@mcrosas mentioned to GESIS that we would start work on this in the November timeframe but we do not have a milestone setup for that yet.

**Comment by sbarbosadataverse** [comment]
@mcrosas @posixeleni 
should this go into the curation github que?

**Comment by mcrosas** [comment]
yes


Mercè Crosas, Ph.D.
Director of Data Science, IQSS
Harvard University
http://scholar.harvard.edu/mercecrosas

**Comment by sbarbosadataverse** [comment]
@posixeleni  please create in our curation que and you can reference this ticket number. Gustavo can be assigned from that que is needed.
