### ISSUE TITLE
Dataset card: Image icon show broken image when there are image files available.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2534]
When I uploaded a zip file containing several images in addition to other files, see a broken image icon on the dataset card and this server.log error. Seems to work in the simple case, uploading a single image.

 [2015-09-17T12:49:30.103-0400] [glassfish 4.1] [INFO] [] [edu.harvard.iq.dataverse.dataaccess.ImageThumbConverter] [tid: _ThreadID=50 _ThreadName=jk-connector(2)] [timeMillis: 1442508570103] [levelValue: 800] [[
  attempting to read the image file /usr/local/glassfish4/glassfish/domains/domain1/files/10.5072/FK2/YGNUBS/14fdbfacba2-34233ae23dde with ImageIO.read()]]

**Comment by landreev** [comment]
Can't reproduce, working for me. 
Are you sure the files were actually available?  - i.e.,  were they actually uploaded and saved? 
(the file from the error message does exist)
Was it just the dataset card? - did you see the thumbnails on the dataset page? Does it happen for all images, or just specific image types? 

In the light of the fact that I was able to upload a zip with a bunch of jpegs and everything worked fine - this must be an issue specifically with your image and/or your zip and/or your specific image type... 

As such - should we defer it to 4.3? 
I will need that specific zip file to try to reproduce the error.

**Comment by kcondon** [comment]
OK, there are two issues here:
1. tif file is being selected by default and it requires specific library support put in by installer. Leonid will check and (re)open the original ticket.
2. The selected thumbnail is not saving where I chose a known working image. I will open this as a separate ticket.

Closing this one
