### ISSUE TITLE
Edit Files: Select all checkbox is missing

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2537]
Edit Files: Select all checkbox and batch edit tags button missing

https://iqssharvard.mybalsamiq.com/projects/filesprovenancefacetsfilter-dataverse40/Dataset%20-%20Edit%20Files

**Comment by landreev** [comment]
@kcondon 
Didn't we agree that there would not be an edit tags button on the editfiles page in 4.2? 
(and you already have it in another ticket, that you marked 4.3... ?)

**Comment by kcondon** [comment]
You are right Leonid. It just becomes hard to remember what we're deferring when you're tracking down a number of issues.

________________________________

**Comment by scolapasta** [comment]
Checked for select All checkbox, still not there. There is however, a workaround which is to do this from the view page (where you can select all).

**Comment by landreev** [comment]
Select button should no longer be missing.

**Comment by kcondon** [comment]
Select all checkbox is now on edit files page and working. Closing
