### ISSUE TITLE
Select All: On dataset page, selecting all changes the file sort order, returns after op complete, causes confusion to a discerning eye.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2538]
It would be useful to be able to choose most of a larger list without having to check each item. One way would be to select all, then deselect a few items. 

When you try that with select all, it deselects the ones you choose but when saving, it acts like select all (because select all button is still selected probably).

When you repeat the above but before saving try to deselect select all, it unchecks all items so that doesn't help.

Maybe what it should do is as soon as you deselect something from a select all list, the select all checkbox is also deselected but the other checkboxes remain in their state.

**Comment by sekmiller** [comment]
Have tried everything haven't been able to recreate

**Comment by sekmiller** [comment]
Assigning back to see if @kcondon recreate issue.

**Comment by kcondon** [comment]
OK, the actual bug is that when you select all the sort order of files changes. It is more apparent when you have lots of files, see test zip ingest. The actual update logic works.

**Comment by sekmiller** [comment]
We're now using sorted file metadatas on the fileFragment. this should fix the issue.

**Comment by kcondon** [comment]
This is working now, closing.
