### ISSUE TITLE
Dataset Pg/Edit (Dataset): Empty Files (Upload + Edit) Pg

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2539]
I was testing batch restricting. I added three files, select all, go to edit, select "restrict."
deselect two files, go under "Edit" and select "unrestrict"

Save options disappear at this point.

I refresh the page and the changes are succefully there, but I no longer can use the new "Edit" button near the files display. 

I try to use the top tool bar for "edit-->file upload and edit" and get thrown to a page that only displays an option for "Save changes or Cancel."

I select save changes and still continue to have the problems as described above: no option to edit, etc...

**Comment by sbarbosadataverse** [comment]
No option to save and "edit" next to files list not functional

<img width="1495" alt="screen shot 2015-09-17 at 2 33 54 pm" src="https://cloud.githubusercontent.com/assets/8322346/9942469/2821c176-5d49-11e5-8fc5-f2aa5719bea4.png">

**Comment by sbarbosadataverse** [comment]
<img width="1361" alt="screen shot 2015-09-17 at 2 39 21 pm" src="https://cloud.githubusercontent.com/assets/8322346/9942600/faef9362-5d49-11e5-8a5a-a10422d2ca26.png">

**Comment by sbarbosadataverse** [comment]
Exiting the dataset and going back in, does not solve the issue

**Comment by mheppler** [comment]
Reviewed the issue with @sbarbosadataverse to clear up the workflow, and specific issues found. I will break out each issue, with a bulleted checkbox, to outline the workflow and bug, and then after, include a suggested fix, discussed with @eaquigley.

- [ ] "Edit" (dataset) button at the top of the page has a single "File (Upload + Edit)" option that brings you to the dataset page, in edit mode, with nothing displayed but "Save Changes" and "Cancel" button

Suggestion: Change that single file option in the "Edit" (dataset) button to be "File (Upload)", which points to editdatafiles, in upload mode. Users should use the checkboxes in the files table to select which ones they want to edit, to get to that workflow.

- [ ] When you restrict or unrestrict selected files, the page's behavior is different upon successful completing the action, with the files remaining selected in the unrestrict workflow

Suggestion: Have the selected view of the files refreshed to being unselected for the unrestrict workflow, as it does for the restrict workflow.

In the original comment for this issue, there maybe some other UI improvements we can make, to make the new tag/restrict/delete workflows within the dataset pg more obvious, but we are going to do some more user testing and interviews before we make any suggestions for changes.

**Comment by mheppler** [comment]
The second task in my previous comment has been stricken due to another ticket (#2540) outlining that issue specifically. I will change the title of this issue to be specific to the "Edit" (dataset) button workflow.

**Comment by landreev** [comment]
@mheppler 
OK, so the way I'm reading this ticket in its final version - the only remaining issue is that we still have a 
single "upload and edit files" button at the top of the page; and I should just replace this with "upload files". And to edit existing files, they will need to use the checkboxes and "Edit Files -> metadata" further down. Correct?

**Comment by mheppler** [comment]
Correct. The other issue was moved to another ticket, that Stephen has.

**Comment by landreev** [comment]
@mheppler 
OK, could you please take a look at the page, and make sure it's ok?
I committed the fix for the page, and the backing bean, that redirects to the editfiles in Upload mode, when this button is clicked. 
But, thinking about it, it could be simpler to just use a static link in xhtml for this, without calling the bean at all - ?

**Comment by mheppler** [comment]
@landreev -- after pulling the latest changes, I still saw the empty edit page when clicking the "Files (Upload + Edit)" option in the "Edit" (dataset) button.

I went ahead and changed the Edit (dataset) button dropdown menu's dynamic p:commandLink item "Files (Upload)" to be a static h:outputLink. The same code used by the "Upload Files" button on the filesFragment. That worked.

**Comment by landreev** [comment]
@mheppler 
Sorry - it looks like I didn't commit the change I made last night!
Thanks for fixing it.

**Comment by kcondon** [comment]
OK, this is working now: top edit button for files only shows upload. Closing.
