### ISSUE TITLE
Dataset/Edit (Selected) Files: Unrestrict Success Behavior Not Consistent With Restrict

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2540]
When batch unrestrict files from the dataset page, it does not display the success message positioned at the top and deselect all checked boxes as restrict does, leading to some confusion as to what happened. Instead, it posts the success message but does not position the page all the way to the top so you can see the success message. Also it does not clear the checkboxes, leading to confusion, despair.

**Comment by posixeleni** [comment]
note: i'm seeing the same issue with the checkboxes not being cleared after I edit Tags

**Comment by mheppler** [comment]
- [ ] When you restrict or unrestrict selected files, the page's behavior is different upon successful completing the action, with the files remaining selected in the unrestrict workflow

Suggestion: Have the selected view of the files refreshed to being unselected for the unrestrict workflow, as it does for the restrict workflow.

(Originally commented in ticket #2539)

**Comment by sekmiller** [comment]
Despair, well we certainly don't want despairing users.

**Comment by sekmiller** [comment]
Fixed the redirects for edit tags and restrict/unrestrict the file check boxes revert to unchecked and the user is redirected to the draft version.  New build required for testing.

**Comment by kcondon** [comment]
This is working now, the sky is clearing...
