### ISSUE TITLE
Upload Files: Cancel Returns to Published Dataset Version, Not Draft Version

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2541]
On "files" tab of a dataset page, I select "upload files"
Next page I select "cancel"
Page displayed is "published" version and not the expected DRAFT that was being edited.

**Comment by landreev** [comment]
OK, I made Cancel return to the Draft version (if there is a draft version!).

**Comment by kcondon** [comment]
This is working: edit metadata, cancel, returns to draft. Closing
