### ISSUE TITLE
Saved Search: make links using a timer (and/or publish triggers) rather than curl and cron

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#2543]
In #2531 we are working on documenting how to set up curl and cron to kick over periodic linking of dataverses and datasets based on saved searches but longer term we'd like this to be part of the app itself.

We should think about how often the equivalent of the "makelinks" API endpoint(s) should be called and if we'll let non-superusers choose how often.

As @sbarbosadataverse pointed out, it would also be nice if the linking were triggered but "publish" actions of any dataset in a dataverse.

**Comment by pdurbin** [comment]
Meh, I like cron. And EJB timers seem to be problematic: http://guides.dataverse.org/en/4.7/admin/troubleshooting.html#deployment-fails-ejb-timer-service-not-available . Closing.

**Comment by kcondon** [comment]
@pdurbin, is the cron job/ need for the cron job documented in the guides?
I personally do not like having yet one more thing to configure but that's me.

**Comment by kcondon** [comment]
@pdurbin Seems kind of buried and easy to overlook. Anyway, no skin off my nose. I'm not sure even we run a cron job.

**Comment by pdurbin** [comment]
Maybe instead of "documented" I should have said "mentioned in passing." 😄
