### ISSUE TITLE
Batch Update: some events do not generate a new dataset version: unrestrict, edit tags.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2544]
Some events do not generate a new dataset version: unrestrict, edit tags.

**Comment by sekmiller** [comment]
It was always creating a new draft version but the page wasn't refreshing so it wasn;t obvious.  The redirects have been fixed pursuant to another ticket.  This will be available for testing once a new build is made.

**Comment by kcondon** [comment]
OK, verified these events were creating new versions and now redirected to them. Closing.
