### ISSUE TITLE
Create Dataset: Restricting files on create does not display restrict success message at top of form.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2547]
When restricting files on creating dataset, the success message is not displayed at the top of the form as in v4.1, making it less clear that something happened. As a side note, the lock icon doesn't appear prior to save either but does in v4.1. The lock icon issue is opened in another ticket.

**Comment by landreev** [comment]
Where should the success message appear? (on the dataset page, when the user is redirected there, after a successful save - ?)

**Comment by landreev** [comment]
This is actually working as of now. The mesage "the file(s) ... will be restricted after you click ... save" does appear at the top of the page; the same way it does appear on the Edit Files page. 
In all fairness, whether it appears or not, it's somewhat useless in most cases (when the user is uploading files, they are too far down on the page to see it; unless they collapsed the metadata block). 

Anyway, please re-test. And close, hopefully.

**Comment by kcondon** [comment]
OK, works, closing
