### ISSUE TITLE
Request Access: According to mockups, there should be a request access popup.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2552]
@mheppler @sekmiller @eaquigley 
According to mockups there should be a request access popup.
https://iqssharvard.mybalsamiq.com/projects/filesallthings-enduser-dataverse42andbeyond/Dataset%20-%20Files%20-%20Restricted%20Selected

https://iqssharvard.mybalsamiq.com/projects/filesallthings-enduser-dataverse42andbeyond/Dataset%20-%20Files%20-%20Guestbook

and finally a message:
https://iqssharvard.mybalsamiq.com/projects/filesallthings-enduser-dataverse42andbeyond/Dataset%20-%20Files%20-%20Request%20Access

Although this mockup shows a combined guestbook TOU and is for multi select request access. The mockup for individual request access shows no popup:
https://iqssharvard.mybalsamiq.com/projects/filesallthings-enduser-dataverse42andbeyond/Dataset%20-%20Files%20-%20Restricted

**Comment by eaquigley** [comment]
Related to #1476

**Comment by mheppler** [comment]
A new issue, Dataset - File UI Improvements #3404, was created to track the UI improvements related to the files view on the dataset pg. Older feature requests and bug reports like this one will be closed in favor of that new issue.
