### ISSUE TITLE
Publish Dataset: Publishing In Review dataset does not remove In Review tag.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2554]
Publish Dataset: Publishing In Review dataset does not remove In Review tag.
This is the first time published from initial draft.

**Comment by pdurbin** [comment]
By "tag" I assume what is meant is the Bootstrap label that appears on various cards and on the dataset page itself, per the screenshots at #2315 (which is the issue I probably used for these commits).

**Comment by kcondon** [comment]
Generally a tag is any small amount of text set off by a contrasting or colored surrounding background shape denoting a category or classification commonly used in many websites such as github, dataverse, etc. In particular, for Dataverse, In Review is a dataset worflow state along with Draft, Unpublished and a tag indicating this state with a green background appears next to the title of the dataset both on the dataset card and the dataset page itself.

**Comment by pdurbin** [comment]
I can easily reproduce this issue. When you publish a dataset that is "In Review" the boolean in the database doesn't change:

```
dataverse_db=# select id,dataset_id,versionstate,inreview from datasetversion;
 id | dataset_id | versionstate | inreview 
----+------------+--------------+----------
  4 |         14 | RELEASED     | t
(1 row)
```

This was also expressed in #2526 as "The bigger issue that has been discovered with "In Review" which is the "In Review" is just a flag and does not actually change the state of the dataset (such as changing it from Draft to In Review it is still a Draft just with an extra label on it)."

The code for the "In Review" facet and label simply checks if datasetVersion.isInReview() but it seems like the `inreview` boolean isn't cleared when the dataset is published. I assume it should be but it would be good to review #832 where "In Review" was originally implemented as well as the [FRD for In Review](https://docs.google.com/document/d/1O5HhLgypYF9OSjCaujaEh-Vh9jieCF-3A0MlHnb7iQ8/edit?usp=sharing).

**Comment by pdurbin** [comment]
I spoke with @sekmiller and he indicated I should give this issue to him and that he'd take a look.

**Comment by sekmiller** [comment]
I updated the Publish Command to reset the inReview flag to false.  The reason we didn't see this previously was because the submit button is rendered based on "inDraft" status and does not render for "published" versions.

New build required for testing.  This does not fix the data for previously published "inReview" versions.  I can write an update query to do so.

**Comment by kcondon** [comment]
@scolapasta @sekmiller @pdurbin 
Ok, in review tag disappears now from dataset page, card, and my data. Passing to Gustavo for comments on updating existing data in prod and more defensive coding.

**Comment by pdurbin** [comment]
@scolapasta can you please code review 3ce423f to make sure it's what you want before we merge it in?

**Comment by pdurbin** [comment]
@kcondon I merged defensive coding idea. @sekmiller said it would be easy to update existing data so you might want to ask him to update https://github.com/IQSS/dataverse/blob/4.2/scripts/database/upgrades/upgrade_v4.1_to_v4.2.sql but I'm passing this to QA.

**Comment by kcondon** [comment]
Passing to Stephen to update the update script to correct existing data. Belt and suspenders.

**Comment by sekmiller** [comment]
Here is the script(I just put the update part into the upgrade script):
--- To look for bad data
select * from datasetversion where inreview = true
and versionstate = 'RELEASED';
--- update the bad data
UPDATE datasetversion SET inreview = false where inreview = true
and versionstate = 'RELEASED';
--- You can re-run the select to add a CUMMERBUND to the belt and suspenders

**Comment by kcondon** [comment]
OK, both Phil's suspender and Stephen's Cummerbund are working. Closing.
