### ISSUE TITLE
Edit Dataset: Select Template Dropdown Too Short in Chrome

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2560]
When using Chrome the select template list box is to short: it does not completely display the default selection: "No template - clear default values" This works on FF.

**Comment by mheppler** [comment]
Styled the dropdown menu to be a little larger, as well as revised select item text on the Dataset Template dropdown menu for the "no template" option on the create dataset pg, and moved "clear default values" text into a help-block.

**Comment by kcondon** [comment]
Works, closing
