### ISSUE TITLE
Dataset page: While tabular file is first ingesting, the upload button is not greyed out and is too close to the next button.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2561]
When uploading a tabular file, the resulting dataset page shows an upload button with a crossed circle and grayed out edit button but the upload button is not grayed out and it is right next to the edit button, needs spacing.

**Comment by landreev** [comment]
@kcondon 
@mheppler 

Kevin, I confirmed that the upload button IS actually disabled, when the dataset is locked and you are seeing it displayed with that crossed circle. Whether the button can be completely greyed out, like the "Edit Files" dropdown button next to it - we'll have to ask Mike. 

Mike, I'm passing this ticket to you, for the above, and for the other cosmetic issue Kevin mentioned - 
that the 2 buttons are too close when the dataset is locked.

**Comment by mheppler** [comment]
Styled the disabled "Upload Files" button so it looks more disabled, and so it's properly spaced from the other buttons on the page.

**Comment by kcondon** [comment]
@mheppler This is basically fixed, thanks but the upload button crammed next to the edit button during this op is still happening. Do you want to take a look or good enough? I'll close but you can let me know.
