### ISSUE TITLE
Edit Files: When restricting a file, add terms of access popup is not appearing.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2562]
This was working, seems to have broken. When restricting files on edit files page, add/edit terms of access popup is not appearing.

**Comment by landreev** [comment]
@kcondon 
Kevin, 
The popup should now be appearing consistently, on both the EditFiles page, on existing and brand-new draft versions, plus on the dataset page in Create mode. 
Please note that in create mode the workflow is the same as on the edit/upload files page: when restricting files, you get an intermediate success message on the top of the page; and the terms of use popup when you click save.

**Comment by kcondon** [comment]
OK popups appear where they should. Not saving from edit flles though. Will open a new ticket. Closing.
