### ISSUE TITLE
Edit Files: Tabular data tags can be selected but are not saved.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2563]
You can add tabular data tags on the edit files page but they're not saved.

**Comment by landreev** [comment]
Steve has volunteered to take this ticket from me... thank you Steve!

**Comment by sekmiller** [comment]
Sorry.  This one is in the save of selected files metadata.  Leonid is closer to the subject than I am so I am passing it back.

**Comment by landreev** [comment]
Kevin, please re-test. 
After the next build. 
After the next build that actually builds and deploy successfully.

**Comment by kcondon** [comment]
This works, tested on build that actually deployed. Closing.
