### ISSUE TITLE
Batch Edit Tags: Should show tabular tags if any file selected is tabular but with some updated text.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2564]
Batch editing file tags popup should show the tabular data tags option if any file selected is tabular but only apply the selected tag to tabular files. It should not show the popup if not tabular files are selected.

There should also be some updated text to the popup indicating the tabular tags apply only to files of type R, Stata, SPSS, etc. Liz will add the text.

**Comment by sekmiller** [comment]
Waiting for updated text. Functionality is completed.

**Comment by eaquigley** [comment]
Text updated in commit 093a25d9810491cad6a77a4ae0ffe693aeed8659

**Comment by kcondon** [comment]
OK, works: tabular tags always appear as an option if at least one tabular data file selected, only updates tabular files with tabular tags, mouse over text has format tip. Closing.
