### ISSUE TITLE
edit files page should give the user a 403 if they don't have Edit permission!

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#2567]
@scolapasta and I discussed this earlier, but didn't open a ticket for this. 
The edit page should send an unauthorized user directly to 403.xhtml, just like the dataset page. 
As of now, it protects the files table with the .authorized render rules; but the page (and the save button) is still rendered even if they are not authorized.

**Comment by landreev** [comment]
Should be working as requested:
If an unauthorized user comes to the edit files page (with otherwise legit url parameters - dataset id, etc.), they will be sent to the 403 page, if logged in; or to the login page, if not.

**Comment by kcondon** [comment]
Works as described. Closing.
