### ISSUE TITLE
Multi Select Request Access: Grant list box has unordered file list, unlike file view on dataset page.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2572]
Grant list box has unordered file list, unlike file view on dataset page.

Makes it more difficult to compare to dataset if the ordering is different. Same with file order on view granted file list, unordered.

**Comment by mheppler** [comment]
The table order is determined by the attribute `rowKey="#{roleAssignment.id}"`.

**Comment by mheppler** [comment]
Fixed sort order of the file table on the Grant FIle Access and File Access popups on the File Permissions pg. Also added icons to action buttons to better distinguish Grant from Reject.

This code was pushed to the ["2572-permissions-ux"](https://github.com/IQSS/dataverse/tree/2572-permissions-ux) branch.

**Comment by mheppler** [comment]
Sorry, taking this back. Don't seem to have this solved on all three dataTables on the File Permissions pg. The dataTable (Line 236) in the "Grant Access to Users/Groups" popup is still looking random by `rowKey="#{file.id}"` and not sorted by `sortBy="#{file.displayName}"`.

**Comment by mheppler** [comment]
The "Grant File Access" popup seems to be the only place that the `sortBy` attribute is working for. (See attached.)

Here is a list of file and users/groups tables in the various permissions workflows that need to have the sort order fixed.

*Dataverse/Dataset Permissions*
- [ ] Users/Groups role assigned table (broken)

*File Permissions*
- [ ] Users/Groups access requests table (working?)
- [x] Users/Groups file access requested popup (working!)
- [ ] Users/Groups access granted table (working?)
- [x] Users/Groups file access granted popup (working!)
- [ ] Users/Groups grant access popup (broken)
- [ ] Files restricted table (broken)
- [ ] Files users/groups access assigned popup (working?)
- [ ] Files grant access popup (broken)

![screen shot 2016-02-09 at 11 45 07 am](https://cloud.githubusercontent.com/assets/687227/12923300/31ee7054-cf23-11e5-98fd-90f021aa2e0a.png)

**Comment by djbrooke** [comment]
@mheppler @sekmiller I'm going to move this to not started, but I saw there were a few commits that referenced it.

**Comment by djbrooke** [comment]
The fix for #2657 is in this branch.

**Comment by mheppler** [comment]
Updated my comment above to make the checklist items clearer as to which dataTable was broken and in which popup from which page.
