### ISSUE TITLE
Validation Error: Cannot create draft when uploading files if there is a missing required field.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2573]
The missing required field logic was changed to allow file uploads and terms updating and it generally works except in the case of creating a draft by uploading files. That fails on save with a validation error as before. You can change terms to create the draft, then continue to upload files for example.

**Comment by landreev** [comment]
@scolapasta 
Gustavo, could you tell me what needs to be done here? Kevin is telling me there is already some code that you wrote that I could use... but I don't know anything about it. 
Is this really a 4.2 issue?

**Comment by landreev** [comment]
Please test.

**Comment by landreev** [comment]
P.S. The validation of the version should be "lenient" now; being chill about missing required fields, etc. - just like on the dataset page. But if there are bad characters in the file names - or any similar errors in the file metadatas, that the user can actually fix, they should still be getting the validation messages on the page.

**Comment by kcondon** [comment]
Works, closing
