### ISSUE TITLE
Code style: lack of Java generics causes 100s of type safety warnings

### ISSUE THREAD

**Issue by bencomp** [IQSS/dataverse#2574]
Following up on #775. The [style guide](http://guides.dataverse.org/en/latest/developers/coding-style.html) says to use Java 7 and the generics provided by the language.

This should result in 100s fewer compiler warnings about unchecked conversions and unchecked method invocations and cleaner code, e.g. because casts are no longer needed.

**Comment by bencomp** [comment]
In the IRC channel @pdurbin and I discussed the possibility of allowing project settings related to NetBeans hints in the repository. Having hints for Javac compiler warnings could help enormously in getting the message of this issue across. I created #2644 for this.

**Comment by pdurbin** [comment]
I implemented this in 6535d9d and am closing this issue in favor of #3418.

**Comment by bencomp** [comment]
I believe this issue was about the existence of "ugly" code, not about the dev guide. Yes, the coding style guidelines should include a guideline on the use of generics, but to solve my original issue I would have liked to see cleaning up. @oscardssmith seems to have noticed the same in #3902, so I won't ask to reopen this issue.
