### ISSUE TITLE
Code style/Ops: use Logger.log instead of System.out.print[ln]

### ISSUE THREAD

**Issue by bencomp** [IQSS/dataverse#2575]
Following up on #775.

`java.util.logging.Logger` provides a consistent way of sending log messages to the centralised log, including a level indicating the importance of the message. `System.out.print` and `System.out.println` messages do end up in the log, but without a source and all at `Level.INFO`.

It helps tremendously to operate a Dataverse installation if log messages are informative. That, to us, means that every message has at least a source and the right importance level. Currently there are nearly 200 uses of `System.out` in the codebase, although a lot are commented out and some are even "hidden" inside something like:

``` java
private void msg(String s){
    System.out.println(s);
}
```

The [style guide](http://guides.dataverse.org/en/latest/developers/coding-style.html) has more tips for logging, like using the warning (or severe) level when an exception is caught.

**Comment by pdurbin** [comment]
I implemented this in 6535d9d and am closing this issue in favor of #3418.

**Comment by bencomp** [comment]
Nice work on the style guide, @pdurbin!

Note that `println` is still used – and not only in tests or command-line interfaces.
