### ISSUE TITLE
Code style: licensing boilerplate is incomplete or incorrect or conflicting

### ISSUE THREAD

**Issue by bencomp** [IQSS/dataverse#2576]
Follow up from #775.

Whereas DVN 3.6 has a licence (license) header applied consistently across all Java files, Dataverse 4 has not.

Currently, there are files that:
- have no boilerplate at all
- have a NetBeans default template
- have DVN 3.0 license information
- were copied (verbatim?) from a Sun JDK, including Sun copyright + GPL2 license information _and_ Harvard copyright with Apache license information

Why the files from the Sun JDK (e.g. [ServiceRegistry.java](https://github.com/IQSS/dataverse/blob/v4.1/src/main/java/edu/harvard/iq/dataverse/ingest/plugin/spi/ServiceRegistry.java) and [PartiallyOrderedSet.java](https://github.com/IQSS/dataverse/blob/v4.1/src/main/java/edu/harvard/iq/dataverse/ingest/plugin/spi/PartiallyOrderedSet.java)) were copied instead of referenced as a dependency is unclear to me, but the licenses may not be compatible. The other files tell me that the code is not ready for release yet, let alone reuse.

(Edit: include examples of copied files.)

**Comment by pdurbin** [comment]
Isn't a single license file at https://github.com/IQSS/dataverse/blob/master/LICENSE.md enough? Do we really need to have a copy of the license in each 500 (and growing .java files)?

**Comment by bencomp** [comment]
The documentation for the European Union Public Licence advises to put a small header in each source file. I'm not sure what Apache says about this.

**Comment by mcrosas** [comment]
Apache also recommends a short header.

@bencomp I did notice that there is inconsistency about the bolierplate or header in the  Java files across Dataverse code (some of them carry what we had for 3.x).

I'm reviewing these issues with legal (cyberspace) experts - I've contacted them already and waiting for feedback.

**Comment by bencomp** [comment]
Thanks, @mcrosas!

**Comment by pdurbin** [comment]
Closing until we get the feedback.
