### ISSUE TITLE
Native API : contents json result , got title for dataverses but no title for datasets ?

### ISSUE THREAD

**Issue by rmo-cdsp** [IQSS/dataverse#2577]
Hello !

I used the command "GET http://HOST/api/dataverses/:root/contents" from the Native API in order to retrieve the root contents (Dataverses + Datasets). Here is the (shorter) Json result file: 

```
{
  u'status': u'OK',
  u'data': [
    {
      u'protocol': u'doi',
      u'authority': u'10.5072/FK2',
      u'persistentUrl': u'http://dx.doi.org/10.5072/FK2/81ZOVB',
      u'identifier': u'81ZOVB',
      u'type': u'dataset',
      u'id': 22
    },
    {
      u'type': u'dataverse',
      u'id': 10,
      u'title': u'Antislavery Petitions Massachusetts'
    }
  ]
}
```

As you can see, the dataverse got his title, but not the dataset. Is it intended to have the title for one and not the other ? Wouldn't it be "fair" to have the title field for both ? I let you judge if it is relevant or not :)

**Comment by pdurbin** [comment]
@rmo-cdsp are you still interested in this? I'm flagging issues as low-hanging-fruit for interns and a hackathon at the community meeting.

**Comment by pdurbin** [comment]
@rmo-cdsp I haven't heard back so I'm closing this. Please let us know if you're still interested!

**Comment by rmo-cdsp** [comment]
It's not an important feature to me, but a detail that should be, imho, standardized :)

**Comment by pdurbin** [comment]
@rmo-cdsp ok. If you want me to re-open this issue, please let me know. Thanks!
