### ISSUE TITLE
Edit Files: Select all wipes out any new, unsaved file descriptions

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2582]
If I upload a bunch of files and edit the descriptions, then choose select all it wipes out the newly entered and unsaved file descriptions. 

This does not happen with saved file descriptions. It does not happen with individual check boxes.

**Comment by landreev** [comment]
I don't know how to fix this. I just copied the "select all" from the dataset page; and used the exact same mechanism.  It triggers a method on the inside that goes through all the metadatas on the list and adds them to the "selected" list... but it apparently doesn't sync the contents of the bean's list of filemetadatas with the changes already made on the page, first - so they are lost. 
Gustavo, do you have any advice?

**Comment by landreev** [comment]
P.S. is this just a matter of using process="..."?

**Comment by landreev** [comment]
OK, I've committed the process="filesTable"... but Gustavo thinks it's stupid.

**Comment by mheppler** [comment]
Review the process fix Leonid applied with Gustavo and Leonid, and we all agree this is good enough for 4.2, and that we will look into further improving the "Select All" functionality in 4.3 for the far outlying usecase that causes the validation error.

**Comment by kcondon** [comment]
This was tested and works. Closing.
