### ISSUE TITLE
Page printing: Messy printing of dataset

### ISSUE THREAD

**Issue by rmo-cdsp** [IQSS/dataverse#2584]
Printing a dataset through the brower print function sometimes produce messy results. An example : 
![dataverse_bad_printing](https://cloud.githubusercontent.com/assets/14806890/10073322/486d5af6-62c8-11e5-889f-36bb88347c4d.png)

As you can see, some text parts are on each others. Any "dataverse" printing function is planned ? Would be better than the browser one, I guess :)

**Comment by pdurbin** [comment]
As I [mentioned in chat](http://irclog.iq.harvard.edu/dataverse/2015-09-24) I can easily reproduce this from both Mac and Ubuntu using Firefox. [The dataset](https://beta.dataverse.org/dataset.xhtml?persistentId=doi:10.5072/FK2/BWSZDW) seems to print ok on Chrome and Safari on Mac.

**Comment by eaquigley** [comment]
@romainM would you mind expanding on when and why you would need to print a dataset (or any page) in dataverse so we have more information on this use case when working on this. Thanks!

On Sep 24, 2015, at 8:28 AM, RomainM <notifications@github.com<mailto:notifications@github.com>> wrote:


Printing a dataset through the brower print function sometimes produce messy results. An example :
[dataverse_bad_printing]<https://urldefense.proofpoint.com/v2/url?u=https-3A__cloud.githubusercontent.com_assets_14806890_10073322_486d5af6-2D62c8-2D11e5-2D889f-2D36bb88347c4d.png&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=Y9aY3P6kFFpmMLaYYO_id08dS3gL1xWMQuI2CZ74PoI&m=jcjSjoWdzaSeHxh4SppfhSNX3QgmAflLEGUTogHys9Y&s=l5dTSa3zdt87Y2ZYIoVWUmvFduHyVn_cLryVLD4zc3w&e=>

As you can see, some text parts are on each others. Any "dataverse" printing function is planned ? Would be better than the browser one, I guess :)

**Comment by mheppler** [comment]
@eaquigley -- This looks to be a conflict issue with the PrimeFaces and Bootstrap components not messing well together. I was able to resolve the print-layout issue I was seeing locally by removing PrimeFaces layout components from the citation summary metadata block, leaving just the Bootstrap gird layout component. This fix will easily tie into the responsive layout improvements we have planned for 4.3, so I went ahead and took this ticket, and assigned to myself for the next release.
![screen shot 2015-09-24 at 11 00 43 am](https://cloud.githubusercontent.com/assets/687227/10076909/d04c4dc8-62ab-11e5-92c1-992f163ec2d0.png)

**Comment by Grimaldum** [comment]
@eaquigley : for the when, I would say when I see the dataset itself, or when I see a dataset's list from a dataverse. For the why, I don't really know. Maybe to show it during a meeting, etc. Sometimes, people prefer to have papers, it happens :)

**Comment by mheppler** [comment]
A new issue, **Dataset - File UI Improvements #3404**, was created to track the UI improvements related to the files view on the dataset pg. Older feature requests and bug reports like this one will be closed in favor of that new issue.

**Comment by pdurbin** [comment]
#739 is related.
