### ISSUE TITLE
Dataset: Select > Edit Files > Delete, large number of files, page does not refresh

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2591]
I selected all files, then went under edit-delete, it processed for over 4 minutes before it stopped "processing."
Page did not refresh to show files removed.
I refreshed the page and files were removed successfully

**Comment by scolapasta** [comment]
checked with @sbarbosadataverse - this happened in a dataset, deleting around 1700 files

**Comment by mheppler** [comment]
A new issue, **Dataset - File UI Improvements #3404**, was created to track the UI improvements related to the files view on the dataset pg. Older feature requests and bug reports like this one will be closed in favor of that new issue.
