### ISSUE TITLE
Guides: Add information on deleting datasets, dataverses and destroy command

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2593]
A partner was asking about how to delete things and it was not in the User Guide, see RT 227504.

This was my answer and could be documented both in the user guide and api guide:

You can delete draft versions of datasets through the UI and empty dataverse through the UI by navigating to the dataset or dataverse, choosing edit, and then delete dataset or dataverse.

You cannot delete a published or deaccessioned dataset through the UI. A user who has been granted super user status can delete a published dataset using the native API:
http://guides.dataverse.org/en/4.2/api/native-api.html#datasets<br> [Open URL] curl -X DELETE http://$SERVER/api/datasets/$id/destroy?key=$apiKey

Please note: the command normally is used for removing draft datasets but when a super user you can add the destroy keyword and that removes the published version.

**Comment by eaquigley** [comment]
I'll take this ticket to add the delete information into the user guide. Someone else will need to do the API guide

**Comment by pdurbin** [comment]
How to destroy datasets is already documented in the API Guide. We should probably also document it in the Superuser section of the User Guide as part of #2211.

**Comment by pdurbin** [comment]
> How to destroy datasets is already documented in the API Guide.

I just looked at http://guides.dataverse.org/en/4.8/api and couldn't find it. Here's what I sent on the mailing list...

> You can destroy datasets like this but the API token must belong to a superuser:
> 
> `curl -H 'X-Dataverse-key: 2395bbb2-5ac6-40b1-b15d-0308bc0053d2' -X DELETE https://demo.dataverse.org/api/datasets/:persistentId/destroy?persistentId=doi:10.5072/FK2/3NQEGS`

... and it seems like it helped: https://groups.google.com/d/msg/dataverse-community/84beQsFuC9w/mcF-Q6-wBwAJ

For the record, if you're going to post your API token like this should you immediately generate a new one like I did! 😄

**Comment by kcondon** [comment]
@donsizemore 
This does not seem to be entirely accurate. You cannot destroy a published dataverse that has children (datasets or dataverses) nor is there a dataverse destroy argument, only a dataset destroy argument. What you can do is delete an empty dataverse, whether published or not via UI or standard delete dataverse api. The fact that it needs to first be emptied is what users stumble over since delete as an option in the ui only appears when it is empty. This ticket was opened in part after having answered the question many times. Also, the delete published dataset using the destroy argument was never documented but we also sometimes need to provide that info. So, ideally this ticket addresses both.

**Comment by donsizemore** [comment]
@kcondon 10-4, will fix.

**Comment by pdurbin** [comment]
I noticed @donsizemore pushed 7b2ef2b so I moved this to QA.

**Comment by kcondon** [comment]
@pdurbin Still needs info on deleting dataverse in ui

**Comment by pdurbin** [comment]
@donsizemore so sorry to send this back to you. Please see above about the UI and I'm also wondering if you could convert the commands to copy and pasteable full curl commands.
