### ISSUE TITLE
Configuration to turn on/off geoconnect

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#2597]
In practical terms:

  - [x] 1. Turn on/off the ability to create/edit maps 
    - Map Data buttons don't appear on the file listing page
  - [x] 2. Turn on/off the ability to view existing maps
     - Explore Map and Map previews don't appear on the file listing page
  - [ ] 3. Add Default Geoconnect "Map It" Information to initial SQL script

## 1. Turn on/off the ability to create/edit maps 

This is a new value (or values) for the settings table with a boolean flag.
  - **Variable Name:** ```GeoconnectCreateEditMaps``
  - **Values:**: true/false

#### How the setting is used/Code updates

For the Dataset page, use the setting in these functions:
  1.  ```canUserSeeMapDataButton```
  2. ```canSeeMapButtonReminderToPublish```

If the setting is not found or not true, return a false.

  - This will disable the following buttons via the rendered attribute, **_without_** needing to change the following in In the **filesFragment.xhtml**:

```
<!-- WorldMap Map Data -->
<h:outputLink pt:role="button" rendered="#{DatasetPage.canUserSeeMapDataButton(fileMetadata)}"
              type="button" styleClass="btn btn-default" value="#{fileMetadata.dataFile.getMapItURL(dataverseSession.user.id)}" role="button">
    <span class="glyphicon glyphicon-map-marker" /> #{bundle['file.mapData']}
</h:outputLink>
<!-- Unpublished Map Data -->
<ui:fragment rendered="#{DatasetPage.canSeeMapButtonReminderToPublish(fileMetadata)}">
    <button type="button" class="btn btn-default" onclick="PF('mapData_popup').show()">
        <span class="glyphicon glyphicon-map-marker" /> #{bundle['file.mapData']}
    </button>
</ui:fragment>
```

## 2. Turn on/off the ability to view existing maps

This is a new value (or values) for the settings table with a boolean flag.
  - **Variable Name:** ```GeoconnectViewMaps``
  - **Values:**: true/false

#### How the setting is used/Code updates

For the Dataset page, use the setting in these functions:
  1.  ```canUserSeeExploreWorldMapButton```
  2. ```hasMapLayerMetadata```

 - This should the several sections of the **filesFragment.xhtml** page via the rendered attribute, **_without_** needing to change the following in In the **filesFragment.xhtml**:

## 3. Add Default Geoconnect "Map It" Information to initial SQL script

To populate the table ```worldmapauth_tokentype```:
  - Add an initial SQL script to add a row to ```worldmapauth_tokentype```.
  - For future changes to the Geoconnect url or other attributes:
     - Change the  ```worldmapauth_tokentype``` row where the ```name``` is **GEOCONNECT**.  
     - Note: In TokenApplicationType.java: 
  ```java
public static final String DEFAULT_GEOCONNECT_APPLICATION_NAME = "GEOCONNECT";
```

Default data for  ```worldmapauth_tokentype``` 
```json
{ 
   "name" : "GEOCONNECT",
   "mapitlink" : "http://geoconnect.datascience.iq.harvard.edu/shapefile/map-it",
   "contactEmail" : "support@dataverse.org",
   "hostName" : "geoconnect.datascience.iq.harvard.edu",
   "ipaddress" : "140.247.115.127",
   "timelimitminutes" : 30,
   "timelimitminutes" : 1800,
   "md5" : "38c0a931b2d582a5c43fc79405b30c22",
   "created" : "2015-06-08 11:19:46.909",
   "modified" : "2015-06-08 11:19:46.909"
 }
  ````

#### How the setting is used/Code updates

  - **class**: TokenApplicationTypeServiceBean
  - **method**: getGeoConnectApplication

---

**Comment by bencomp** [comment]
Relates to #2135

**Comment by sekmiller** [comment]
@raprasad, @landreev 
Is there an ingest aspect to this? In other words, does some processing happen during ingest that we need to turn on/off?

**Comment by pdurbin** [comment]
As decided in this morning's meeting I created a new [2597-geoconnect-toggle-off](https://github.com/IQSS/dataverse/commits/2597-geoconnect-toggle-off) branch for @sekmiller to push to for this issue, branched from the v4.2.2 tag. I bumped the version number to 4.2.2.1 to distinguish it from v4.2.2 which is already tagged. We **might** end up just cherry-picking the fix into 4.2.3 (I guess I'll change the milestone to 4.2.3 for now). Time will tell.

**Comment by sekmiller** [comment]
@raprasad 
mapit link and md5 are non-nullable fields so an insert statement for worldmapauth_tokentype needs to have values for these.

**Comment by sekmiller** [comment]
Checked into my local branch.

**Comment by pdurbin** [comment]
@sekmiller and I merged the branch into 4.2.3. Please note the two new geoconnect settings in 46d3feb2c75d4dcbfb37339c7d323a0c59c91ea1 (GeoconnectCreateEditMaps and GeoconnectViewMaps).

Set ``GeoconnectCreateEditMaps`` to true to allow the user to create GeoConnect Maps. This boolean effects whether the user sees the map button on the dataset page and if the ingest will create a shape file.

`curl -X PUT -d true http://localhost:8080/api/admin/settings/:GeoconnectCreateEditMaps`

Set ``GeoconnectViewMaps`` to true to allow a user to view existing maps. This boolean effects whether a user will see the "Explore" button.

`curl -X PUT -d true http://localhost:8080/api/admin/settings/:GeoconnectViewMaps`

We added these settings to the "setup optional harvard" script: e25e900

**Comment by kcondon** [comment]
Tested the map it button and that worked, had some trouble getting WorldMap to process the shape file so still need to test the explore button.

**Comment by kcondon** [comment]
OK, tested both settings and the work, also confirmed they are in script.Closing
