### ISSUE TITLE
SWORD: Can not list all datasets in a dataverse with over 4000 datasets

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#2599]
http://guides.dataverse.org/en/4.0/api/sword.html#known-issues already says "Inefficiency in constructing the list of datasets" and links to #784 but I'm opening this issue to be more focused on the "List datasets in a dataverse" SWORD endpoint ( http://guides.dataverse.org/en/4.2/api/sword.html#list-datasets-in-a-dataverse ) which seems to be slow enough not to return for a dataverse such as https://dataverse.harvard.edu/dataverse/antislaverypetitionsma that has almost 4000 datasets. @garthg originally reported this in [a support ticket](https://help.hmdc.harvard.edu/Ticket/Display.html?id=227665) and I was able to reproduce the problem on a test server (dvn-vm5):

`curl -u $API_TOKEN: https://$HOSTNAME/dvn/api/data-deposit/v1/swordv2/collection/dataverse/antislaverypetitionsma`

```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>503 Service Temporarily Unavailable</title>
</head><body>
<h1>Service Temporarily Unavailable</h1>
<p>The server is temporarily unable to service your
request due to maintenance downtime or capacity
problems. Please try again later.</p>
<hr>
<address>Apache/2.2.15 (CentOS) Server at dvn-vm5 Port 443</address>
</body></html>
```

**Comment by garthg** [comment]
I just wanted to confirm that the URL tested above does appear to be what causes a problem for the dataverse-client-python wrapper. A GET request to the production URL fails with 503 Service Temporarily Unavailable even without authentication. 

The failing URL:
https://dataverse.harvard.edu/dvn/api/data-deposit/v1.1/swordv2/collection/dataverse/antislaverypetitionsma

**Comment by pdurbin** [comment]
On my laptop I loaded up some production data from a few months ago. The curl command above listing the datasets of the "antislaverypetitionsma" dataverse did return but it took 2m35.849s. From `jconsole` it's easy to see how much heap memory is being consumed and that garbage collection occurred twice during the operation:

![screen shot 2015-10-05 at 9 46 51 am](https://cloud.githubusercontent.com/assets/21006/10282005/537c2edc-6b46-11e5-854c-cfcf1d6b1d50.png)

**Comment by pdurbin** [comment]
By commenting out the line below that gets the dataset title from the latest version I'm able to reduce the time it takes to execute the curl command above from 2m35.849s to 0m1.951s

```
$ git diff
diff --git a/src/main/java/edu/harvard/iq/dataverse/api/datadeposit/CollectionListManagerImpl.java b/src/main/java/edu/harvard/iq/dataverse/api/datadeposit/CollectionListManagerImpl.java
index 2a7d7e6..3fa4ae9 100644
--- a/src/main/java/edu/harvard/iq/dataverse/api/datadeposit/CollectionListManagerImpl.java
+++ b/src/main/java/edu/harvard/iq/dataverse/api/datadeposit/CollectionListManagerImpl.java
@@ -79,7 +79,7 @@ public class CollectionListManagerImpl implements CollectionListManager {
                         String editMediaUri = baseUrl + "/edit-media/study/" + dataset.getGlobalId();
                         Entry entry = feed.addEntry();
                         entry.setId(editUri);
-                        entry.setTitle(dataset.getLatestVersion().getTitle());
+//                        entry.setTitle(dataset.getLatestVersion().getTitle());
                         entry.setBaseUri(new IRI(editUri));
                         entry.addLink(editMediaUri, "edit-media");
                         feed.addEntry(entry);
murphy:dataverse pdurbin$ 
```

In the DVN 3.x version of this method the line looked like this:

    entry.setTitle(study.getLatestVersion().getMetadata().getTitle());

I'm not sure why the method is so much slower in Dataverse 4.

**Comment by pdurbin** [comment]
In 5a78dee I added a native query to return the title of the latest version of a dataset and switched the "List datasets in a dataverse" SWORD operation to use it. At https://github.com/IQSS/dataverse/issues/2599#issuecomment-145544786 I mentioned that listing around 4000 datasets with this operation was taking 2m35.849s but the new version I just added is only taking 0m3.526s. Over 44 times faster is a huge improvement so I went ahead and put this in the 4.3 branch, but I'm passing this issue to @scolapasta for code review ( @sekmiller or anyone you are welcome to take a look as well). Along the way I was testing the output of the curl command above operating on the antislaverypetitionsma dataverse to make sure the output is the same before and after.

**Comment by pdurbin** [comment]
I don't mean to steal @bencomp 's thunder but he [pointed out](http://irclog.iq.harvard.edu/dataverse/2015-10-06#i_25410) that the old slow method **could** be extra slow due to missing database indices. I didn't explore this.

Also, I wanted to note that when profiling the old, slow method...

    dataset.getLatestVersion().getTitle()

... I found that the vast majority of the time was spent in the `getLatestVersion()` rather than `getTitle()`. I tried making a faster version of `getLatestVersion()` using JPQL but failed, which is why I ended up writing a native query.

**Comment by sekmiller** [comment]
@pdurbin I took a look at the query you wrote.  Three things: 
1) should we make this part of the dataset service bean instead of SWORD?
2) do we need to have special handling for DRAFT versions
3) I rewrote the query with joins.  I find it to be more readable and more efficient.

**Comment by pdurbin** [comment]
@sekmiller I wasn't sure where to put the query and fine with moving it to a different bean. If you'd like to add your version written with joins to another bean I'm happy to switch call it from the SWORD code and delete the one I wrote from the SWORD code. I'll do the same before and after tests of antislaverypetitionsma to make sure I get the same output. I'll give this issue to you. Please give it back to me after you've pushed your version.

What sort of special handling of DRAFT versions did you have in mind? Again, the original code was calling `dataset.getLatestVersion().getTitle()`.

**Comment by landreev** [comment]
If this is a significant improvement,  that we know affects real life operations - should we consider patching it in production? (by *some* means; it could be quick-and-dirty, by just dropping the new class file in place; or merging it back into 4.2 and making another build, etc.)

**Comment by bencomp** [comment]
@landreev or releasing and deploying 4.2.1? :) (continuous delivery :D)

**Comment by landreev** [comment]
@bencomp I probably would not bother releasing 4.2.1 if it's just this one fix. But if there are other things we want to put into production asap, yes, I would seriously support doing that.

**Comment by pdurbin** [comment]
My preference would be releasing 4.2.1 rather than dropping class files into place. Or we could wait for 4.3. The fix is already in the 4.3 branch, though @sekmiller might improve it per https://github.com/IQSS/dataverse/issues/2599#issuecomment-145879848 .

**Comment by pdurbin** [comment]
> 3) I rewrote the query with joins. I find it to be more readable and more efficient.

The fastest time I observed for the ~4000 datasets operation using the method @sekmiller added in 90465bf was 0m5.802s rather than 0m3.526s for the one I added in 5a78dee so I don't believe his version is any more efficient but it does seem to be more readable and it's centralized on the DatasetServiceBean so I reverted the commit where I added my version and switched SWORD to @sekmiller 's version.

Both versions are way faster than the original version that was taking 2m35.849s.

Again, here's the curl command I've been using (antislaverypetitionsma is the one with ~4000 datasets):

`curl -u $API_TOKEN: https://$HOSTNAME/dvn/api/data-deposit/v1/swordv2/collection/dataverse/antislaverypetitionsma`

Passing to QA.

**Comment by garthg** [comment]
Thank you @pdurbin and team for working to resolve this! It looks like it will make a big difference for my use cases. Any idea when I should expect it to be deployed?

**Comment by pdurbin** [comment]
@garthg please keep an eye on https://github.com/IQSS/dataverse/milestones to see if a 4.2.1 milestone appears and if this issues gets assigned to it. Yesterday the dev team discussed the possibility of a 4.2.1 release that would include the fix for this issue and other performance-related issues. For now the fix is in the 4.3 branch. Sorry I don't have exact dates to share.

**Comment by garthg** [comment]
@pdurbin Okay, thanks!

**Comment by kcondon** [comment]
I was able to run the curl command and fetch results for the dv in question. Closing.

**Comment by pdurbin** [comment]
@garthg no, https://dataverse.harvard.edu is still running 4.2 as of this writing (you can tell by what's in the lower right). I'll try to remember to ping you after we push to Harvard's production installation.

> For now the fix is in the 4.3 branch.

Just to clarify, the new 4.2.1 branch was created from the 4.3 branch today so it also includes the patch.

**Comment by garthg** [comment]
@pdurbin I see, thanks. I'll continue to keep an eye on the milestone dates!

**Comment by pdurbin** [comment]
@garthg we pushed v. 4.2.1 build 32-3164663 to https://dataverse.harvard.edu yesterday. It includes a fix for this issue which was a blocker for you testing #2441. If you can comment both here and there I'd appreciate it!

**Comment by garthg** [comment]
Hey @pdurbin , my test case for this issue passed successfully! I'll now retry my update for all studies in my dataverse, and let you know how that goes.

I really appreciate all the work you and the team put towards this issue. Thank you!

(cross-posted to #2441 as requested)
