### ISSUE TITLE
Clean-up Code / Package Structure / File Names

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#26]
---

Author Name: **Gustavo Durand** (@scolapasta)
Original Redmine Issue: 3433, https://redmine.hmdc.harvard.edu/issues/3433
Original Date: 2014-01-27

---

Code cleanup task:

When we started with 4.0 we did not worry about what package a class belonged to, but we really should have. This task is to go in and review each current class and put in in the right package, so that the code is organized better.

We should also review file names, because some of those files will be showing up in the URL, and we should have have a consistent naming convention, and whatnot.

Also, property files for internalization of field labels, help text, etc.

Added by Phil 2014-01-28: Can we add a way to format the code programmatically using a "house style" or the default NetBeans 7.4 style? Right now we have a mix of tabs and spaces...

**Comment by michbarsinai** [comment]
Remove usage of `com.google.common.base.Objects#equal`, replace with `java.util.Objects#equals`.

see https://google.github.io/guava/releases/19.0/api/docs/com/google/common/base/Objects.html#equal(java.lang.Object,%20java.lang.Object)

**Comment by pdurbin** [comment]
> Can we add a way to format the code programmatically using a "house style" or the default NetBeans 7.4 style? Right now we have a mix of tabs and spaces...

The comment above is covered by #3418.

https://docs.google.com/spreadsheet/ccc?key=0ApuNKse3YShudFpaWlNsd2JiY243bm1Hc2RVd2EyN0E&usp=drive_web#gid=0 is still a good starting point (now out of date) for desires to have xhtml files with more consistent naming.

@michbarsinai 's comment is duly noted. I really don't think we need an open issue to remind us to work on code quality. Closing.
