### ISSUE TITLE
File access request link takes admin to the wrong dataset

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2602]
This request came in earlier to support que:
When I click the link, it takes me to a dataset in the Murray Archive, not the dataset in the email below. I was also able to see the username in the Murray dataset. It should have taken me to the dataset listed in the email below.

We did have server issues for quite a while today. The link eventually goes to an "error" page.

Elizabeth gets the same results when she clicks on the link @eaquigley 

Hello,
File access requested for dataset: National Public Services Survey, 2005-2011. Manage permissions at https://dataverse.harvard.edu/permissions-manage-files.xhtml?id=65402.

Thank you,
The Dataverse Project

**Comment by sbarbosadataverse** [comment]
This is where the request ended up
https://dataverse.harvard.edu/dataset.xhtml?persistentId=hdl:1902.1/01066

**Comment by sekmiller** [comment]
When I go to the MADICS Study of Adolescent Development in Multiple Contexts, 1991-1998 and click Edit/ Permissions/Files I don't see a pending request.  Did you deny the request? 

(For the record, the link to this datasets manage permissions page is permissions-manage-files.xhtml?id=48154)

**Comment by eaquigley** [comment]
Moving out of 4.2 as all development for 4.2 has been completed. @sekmiller we should also investigate if this happened because of server issues.

**Comment by pdurbin** [comment]
I'm planning on checking with @sekmiller if this issue and #2624 are indeed the same issue.

**Comment by pdurbin** [comment]
@sbarbosadataverse and I discussed this issue on Friday and as she wrote at https://github.com/IQSS/dataverse/issues/2624#issuecomment-154540707 this issue and #2624 are not the same issue.

#2624 was about seeing an error message

This issue is about the link going to the wrong dataset.

That said, I haven't been able to reproduce either problem with test data on my laptop. I added many screenshots to #2624.

I'm going to pass this issue to @scolapasta for any ideas on reproducing this issue.

**Comment by scolapasta** [comment]
I clicked on the link above and get the correct page. Not sure of other ideas of what to do to reproduce.

Let's see if @sbarbosadataverse has any. Otherwise, I think we pass to QA for one last sanity check.

**Comment by sbarbosadataverse** [comment]
@scolapasta 
should I test in demo or internal? I didn't think it would be easy to reproduce at all.

**Comment by pdurbin** [comment]
@sbarbosadataverse internal has the latest code from the 4.2.2 branch so I'd recommend testing there.

**Comment by sbarbosadataverse** [comment]
Tested in internal. Successful.
