### ISSUE TITLE
Feature request: Make some dataset fields autocomplete ?

### ISSUE THREAD

**Issue by rmo-cdsp** [IQSS/dataverse#2603]
I was wondering if some fields (like authors or keywords) could have an autocomplete functionality in the edition view? I think it would be a good addition in order to uniform the names, and not have "multiple" names for the same person (name error, inversion between last and first name, etc). A global (meaning all authors from the root) autocomplete could be considered for the author fields, but maybe not for keywords and only consider the actual dataverse ? I would say yes for keywords, I don't personally see any problem, but who knows ...

**Comment by pdurbin** [comment]
@Grimaldum thanks for creating this issue. Since I participated in the chat at http://irclog.iq.harvard.edu/dataverse/2015-09-29 I'd be happy to clarify anything that's unclear.

Generally, we should think more about disambiguation of author names using ORCID IDs or similar.

Astronomers probably don't want to see keywords suggested from social science datasets (looking at you @augustfly) so any autocomplete on keywords should probably be restricted to subdataverses.

**Comment by augustfly** [comment]
I would definitely state that autocompletion should be filtered on some sort of relevant contextual information. Pure autocomplete would be a nightmare across domains.

**Comment by pdurbin** [comment]
@rmo-cdsp are you still interested in this?

**Comment by rmo-cdsp** [comment]
Yes indeed, some users on our dataverse asked us if this feature already existed. I think they would be very happy to have such a thing available :)

**Comment by RightInTwo** [comment]
It would be very nice to have this feature for TSV-based vocabularies, but also in combination with "Referencing API data in the metadata" (#4772).

**Comment by poikilotherm** [comment]
We also are very interested in this for using it with a custom metadata block. See some chatting about this on [IRC today](http://irclog.iq.harvard.edu/dataverse/2019-05-10#i_93080).

**Comment by djbrooke** [comment]
Hi @rmo-cdsp and all, I'm going to close this as it's very similar to #6000. I'll be doing some consolidation of issues in this space and I'll link up the consolidated issue here so we can discuss further if needed.

**Comment by djbrooke** [comment]
#6030 created!
