### ISSUE TITLE
Add Backend Support for Changing Citation Date

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#2606]
In order to support #2297 we will be building in backend support in the database to point to allow users the flexibility to use a different date in the citation other than the default dataset publication date.

We will also apply this update to the following two Dataverses:

1) Use Distribution Date in the citation for IFPRI Dataverse https://dataverse.harvard.edu/dataverse/IFPRI ( @sbarbosadataverse will confirm if this is for their entire Dataverse or for only a subset)

2) Use Distribution Date in the citation for Murray

**Comment by sbarbosadataverse** [comment]
@scolapasta @posixeleni 
FYI that IFPRI requested an update on this today and I have sent them this issue number

**Comment by scolapasta** [comment]
A backend has been added for this - as well as an API call:

curl -X PUT localhost:8080/api/datasets/XXX/citationdate/distributionDate?key=YYY

this will allow users with Publish Dataset permission to set.

**Comment by posixeleni** [comment]
Once 4.3 is released what is our plan for fixing the citation dates for all of IFPRI's datasets? @sbarbosadataverse @scolapasta

**Comment by pdurbin** [comment]
@posixeleni I can see some docs at the top of https://github.com/IQSS/dataverse/pull/3000/files if that helps. @scolapasta would know for sure.

**Comment by posixeleni** [comment]
Sorry should have clarified if there will be a way to do a batch change for all of IFPRI's data citation dates.

**Comment by pdurbin** [comment]
Well, given that the (proposed, not merged yet) solution is an API endpoint, this means a script could be written for a batch change.

**Comment by scolapasta** [comment]
Yes, @pdurbin is correct, all we would need is to get the list of the datasets that need to use this, then run the API for each. Could be written as a script.

**Comment by kcondon** [comment]
Tested both put, delete, distributionDate and publicationDate, draft and published (does not create a new draft), with publish and without publish permission. Works, closing.

**Comment by kcondon** [comment]
Wait! Reopening for the IFPRI/ MRA production update and assigning to Gustavo
