### ISSUE TITLE
Dataset Metadata - Export as Native JSON Metadata

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#2608]
Exporting dataset metadata as Native JSON Metadata is a subtask of the main export issue (#907) which lists a variety of formats. @mcrosas mentioned it during [a meeting yesterday](https://docs.google.com/document/d/1XZHpTyYUwyPN3FIfJhaSFg5_h-9C415mlE42Fuao38w/edit?usp=sharing) so I'm creating this issue to track it. As I said then, it **should** be pretty easy to add to the UI since you can already export datasets as JSON via the API ( http://guides.dataverse.org/en/4.2/api/native-api.html#datasets ) so I'll add this to the 4.3 milestone for now. However, since there is a UI component to this I think @mheppler and @eaquigley should opine on where to put the link or button before passing this issue to a developer.

**Comment by pdurbin** [comment]
@mheppler said to give this ticket to him. For reference, in DVN 3.x we had a link at the bottom of the dataset page that read "Download the cataloging information..." . This was for DDI, which is being worked on in #2579.

![dataset_mgr-2014-04_v0_-_recession_trends_dataverse_-_dvn_archive_dataverse_network_-_2015-09-30_11 51 56](https://cloud.githubusercontent.com/assets/21006/10198416/e860b300-6769-11e5-8c52-f1077c2d5322.png)

**Comment by pdurbin** [comment]
I just pushed code for the backend to provide a link to the dataset as JSON in 6fae1a9 but because export isn't ready (#2579 is for DDI, for example) the link is only rendered if a feature flag is set to true ([see curl command](https://github.com/IQSS/dataverse/commit/6fae1a951a9bc5d648ea250b2f5b54670b9d71b6#diff-9651fb33052176dfc2ddb6a934a6d308R507)).

Mostly I made this commit so that @mheppler and @eaquigley can think more about where they'd like the export button to be positioned.

On the backend we need to think more about when people should be able to download a JSON representation of a dataset. Technically, the URL is under "/api" so I was surprised to discover that an API token is currently not necessary to download the JSON of a published dataset given how in #1838 we say we require API tokens. What should the rules be?

**Comment by michbarsinai** [comment]
I think this basically comes down to per-user rate limitation (as opposed to IP or overall rate). As far as I know, the logic of "no key means Guest" is pretty sound, and plays well with the existing permission model. The only thing we cannot do with it is rate limit, as all no-token calls are the same.

So, until we hit that problems, we're fine. When we do hit this problem, we can turn down no-token calls from, e.g., the APIWebFilter, by configuration (as @bencomp suggested here: https://github.com/IQSS/dataverse/issues/1838#issuecomment-106793204)

**Comment by eaquigley** [comment]
@mheppler did a mock up for what this should look like already so i'm not sure why we would need to have another discussion on where the button/link should go? 

![screen shot 2015-09-30 at 12 04 54 pm](https://cloud.githubusercontent.com/assets/5922904/10915936/ff11e9b6-8226-11e5-9811-459b4d7bc60b.png)

additionally, what is the best practice/standard for if this should require an API key or not? I'd imagine if it is a completely public dataset (so published), then why would an API key be required to download the metadata? @pdurbin

**Comment by pdurbin** [comment]
@eaquigley as I mentioned at https://github.com/IQSS/dataverse/issues/2608#issuecomment-144456556 in DVN 3.6 the "Download the cataloging information" link was at the **bottom** of the page. This morning @posixeleni and I were discussing how this makes sense since it's a power user feature to download the metadata as XML or JSON or whatever. If you and @mheppler want the opposite in Dataverse 4 it's fine with me. No need for further discussion.

With regard to API tokens, we opened #1838 ("Consider options for opening APIs without tokens") when it was decided that all APIs would require API tokens. However, in practice, clearly not all APIs require them! Is this a bug or a feature? I mentioned it here because some back end code will need to be modified if we decide to lock down the native API to disallow download of the dataset as JSON if no API token is provided.

**Comment by posixeleni** [comment]
If the metadata is public then I dont think we need an API token.

**Comment by pdurbin** [comment]
> If the metadata is public then I dont think we need an API token.

If some APIs are not going to require an API token, we should probably update http://guides.dataverse.org/en/latest/api which currently says, "In 4.0, we require to get a token, by simply registering for a Dataverse account, before using our APIs." I think @mcrosas put that in so we should have her weigh in on the wording and #1838 generally.

**Comment by mheppler** [comment]
Sending to @sekmiller per this morning's status meeting discussion.

**Comment by eaquigley** [comment]
Based on today's meeting, @sekmiller will do the following:

- [ ] Download Metadata button renamed Export Metadata
- [ ] Dropdown menu within the button for JSON, DDI, and Dublin Core options 
- [ ] Metadata opens in new tab

After these three things have been done, a review with @mcrosas and @posixeleni will happen.

**Comment by sekmiller** [comment]
Complete except for Leonid's adding of variable data.  It's not in the requirements for 4.5, but do we need to add the ability to "turn-off" the download of variable data for DDI?

**Comment by djbrooke** [comment]
@sekmiller - thanks! Can you please tag a person that can answer the question above?

**Comment by djbrooke** [comment]
@kcondon gave me some good info about how to test this. Going to give it a shot.

**Comment by djbrooke** [comment]
Thanks @kcondon for setting up dataset with every possible field filled in! All fields are present in the export.

I believe that the variable data question is being tracked here: #1067 

Marking this as closed.
