### ISSUE TITLE
  Migration: Complete clean up tasks listed in migration issues doc. [Gustavo]

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2613]
test_migration doc contains a list of issues that have been assigned individually. Review and complete ones assigned to you:
https://docs.google.com/document/d/1rHyHKerYNaq1eztGLalUCd0Mnm61M86oFMWEHeX8Zp8/edit

Folder: https://drive.google.com/drive/folders/0B5QwpIhRRT8_Y1Y5MmZxUTFuMXM

**Comment by kcondon** [comment]
Review priority at GIRT as part of Migration project.

**Comment by djbrooke** [comment]
Closing this. If we have issues come up because of things we didn't handle correctly during the migration, we'll handle them one by one. :)
