### ISSUE TITLE
Widgets - Dataverse Slowness Effects Personal Sites

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#2618]
For sites using dataverse listing and search widgets (OpenScholar sites, dataverse.org, etc.), the slowness of our site can negatively effect the loading of the personal sites. This was noticed recently on the dataverse.org, where the search widget was found to delay the page layout displaying properly for up to a minute.

Potential solutions could be to add the [defer](http://www.w3schools.com/tags/att_script_defer.asp) attribute to the script code we provide.

**Comment by kcondon** [comment]
This is part of the widgets project spreadsheet.

**Comment by mheppler** [comment]
The defer attribute in the script code that we provide to sites does not work, in fact, it breaks the widget and fails to the Dataverse site. Will look into other options.

**Comment by scolapasta** [comment]
As these issues seemed to have been related to general server slowness, which we have improved, we're going to close this issue. We can always reopen, if we begin to see issues again.
