### ISSUE TITLE
Ingest of tabular data: RoundRoutines:decimal separator no in right place

### ISSUE THREAD

**Issue by lmaylein** [IQSS/dataverse#2620]
If glassfish server is started with a (language) environment which defines a comma as decimal separator (e.g. LANG=de_DE.UTF-8) the ingest of tabular data fails.

```
[2015-10-01T10:45:04.712+0200] [glassfish 4.1] [SEVERE] []
[org.dataverse.unf.RoundRoutines] [tid: _ThreadID=62 _ThreadName=p:
thread-pool-1; w: 5] [timeMillis: 1443689104712] [levelValue: 1000] [[
   RoundRoutines:decimal separator no in right place]]

[2015-10-01T10:45:04.728+0200] [glassfish 4.1] [INFO] []
[edu.harvard.iq.dataverse.ingest.IngestServiceBean] [tid:
_ThreadID=62 _ThreadName=p: thread-pool-1; w: 5] [timeMillis:
1443689104728] [levelValue: 800] [[
   Ingest failure: Failed to save tabular data (datatable,
datavariables, etc.) in the database. Clearing the datafile object.]]

[2015-10-01T10:45:04.789+0200] [glassfish 4.1] [INFO] []
[edu.harvard.iq.dataverse.ingest.IngestServiceBean] [tid:
_ThreadID=62 _ThreadName=p: thread-pool-1; w: 5] [timeMillis:
1443689104789] [levelValue: 800] [[
   Unknown excepton saving ingested file; Sent push notification to
the page.]]

[2015-10-01T10:45:04.814+0200] [glassfish 4.1] [INFO] []
[edu.harvard.iq.dataverse.ingest.IngestMessageBean] [tid:
_ThreadID=62 _ThreadName=p: thread-pool-1; w: 5] [timeMillis:
1443689104814] [levelValue: 800] [[
   Error occurred during ingest job!]]
```

**Comment by pdurbin** [comment]
We just saw another case of this issue at https://groups.google.com/d/msg/dataverse-community/g5pHge-rtdE/UHUF3uBIAQAJ . @mbamouni wrote, "After set "LANG=us_US.UTF-8", I see the "Explore" button when uploading the 50by1000.dta file."

**Comment by pdurbin** [comment]
@lmaylein would an appropriate fix be to document this in the Installation Guide? I'm hoping so.

**Comment by pdurbin** [comment]
I added a note to the Installation Guide in 902daea and am moving this to Code Review at https://waffle.io/IQSS/dataverse

**Comment by lmaylein** [comment]
@pdurbin: Yes, this is an appropriate fix.

**Comment by pdurbin** [comment]
@lmaylein thanks! You can read what I wrote at 902daea (part of pull request #3877) which has a milestone of 4.7.1. Feedback is welcome and I'm happy to copy and paste anything you write if you'd like to express it differently.

**Comment by pdurbin** [comment]
As I mentioned at standup on Friday, this issue is already listed among a few other documentation-only changes on pull request #3877 so like the others, I'm closing this.
