### ISSUE TITLE
Dataset: Automatically select discipline-specific metadata depending on Subject selection

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#2625]
Allow for discipline specific metadata to be automatically selected for a dataset when a user picks certain Subjects that apply to their data:

Example if they pick "Astronomy and Astrophysics" as a Subject then the "Astronomy & Astrophysics" metadata would automatically be selected for this particular dataset.

This would be particularly useful at the root Dataverse level since you cannot pick a metadata block per dataset there.

**Comment by mheppler** [comment]
Related to #2356
