### ISSUE TITLE
Users/Groups section of permissions page:  the "users/groups" section of permission should expand on access

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2627]
The user/groups section doesn't expand on access to permission page and is causes confusion when users access the page and try to figure out where to add users.

**Comment by bencomp** [comment]
This could be a duplicate of #2255 (in which I agree with @sbarbosadataverse) and is very likely a duplicate of #2354 (in which I mentioned the relation with #2255 to @pdurbin).

**Comment by eaquigley** [comment]
Duplicate of #2354. Passing to @kcondon to close.

**Comment by kcondon** [comment]
Duplicate, closing.
