### ISSUE TITLE
Harvested Archives Dataverse: Users should not be able to add dataverses here--should this be read only?

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2630]
https://dataverse.harvard.edu/dataverse/harvested

There are several unpublished dataverses here, added by "normal" users so it appears. Should this be read only

**Comment by mcrosas** [comment]
Yes, registered users should not be able to add Dataverses under this
dataverse.



On Thu, Oct 8, 2015 at 12:47 PM, sbarbosadataverse <notifications@github.com

**Comment by sbarbosadataverse** [comment]
Kevin things this was due to the Federated dataverse feature from 3.6. I'm going to delete these straddlers now--they are empty and unpublished, and we should verify that no one can actually add dataverses under this space.

Thanks

**Comment by pdurbin** [comment]
@sbarbosadataverse so it's a matter of configuring permissions for https://dataverse.harvard.edu/dataverse/harvested right? To prevent more dataverses from being added?

I'm asking because I **think** we want to support the ability to have a mix of harvested and "native" dataverses in a given dataverse put this is not yet clear in the [DRAFT - Harvesting Functional Requirements Document (FRD)](https://docs.google.com/document/d/1XZHpTyYUwyPN3FIfJhaSFg5_h-9C415mlE42Fuao38w/edit?usp=sharing) as an actual use case and requirement.

**Comment by sbarbosadataverse** [comment]
Good question, Phil. thinks it needs a discussion?

On Thu, Oct 8, 2015 at 4:06 PM, Philip Durbin <notifications@github.com>
wrote:

> @sbarbosadataverse
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sbarbosadataverse&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=hlSebBRDm8oOz729h-QxgXgBJIIRapM51Cv5dc6yWWE&s=Ohl1laFcAwXjaVzZwwB7E0vXE6Yb2EGP3u_V2Cu9qms&e=>
> so it's a matter of configuring permissions for
> https://dataverse.harvard.edu/dataverse/harvested right? To prevent more
> dataverses from being added?
>
> I'm asking because I *think* we want to support the ability to have a mix
> of harvested and "native" dataverses in a given dataverse put this is not
> yet clear in the DRAFT - Harvesting Functional Requirements Document (FRD)
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__docs.google.com_document_d_1XZHpTyYUwyPN3FIfJhaSFg5-5Fh-2D9C415mlE42Fuao38w_edit-3Fusp-3Dsharing&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=hlSebBRDm8oOz729h-QxgXgBJIIRapM51Cv5dc6yWWE&s=JPjySEac3semMbaduOU62V2YvsY56Dh6XNi_VZ1jVBs&e=>
> as an actual use case and requirement.
>
> —
> Reply to this email directly or view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_issues_2630-23issuecomment-2D146671281&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=hlSebBRDm8oOz729h-QxgXgBJIIRapM51Cv5dc6yWWE&s=7SCLOj8hUhZW7WWCG1ru2KQ2wovvjFr-kLtmXCRh14c&e=>
> .
>



-- 
Sonia Barbosa
Manager of Data Curation, IQSS Dataverse Network
Manager of the Murray Research Archive, IQSS
Data Science
Harvard University

Dataverse 4.0 is now available for use!
http://dataverse.harvard.edu

All test dataverses should be created  in 4.0 Demo!
http://dataverse-demo.iq.harvard.edu/

Join our Dataverse Community!
https://groups.google.com/forum/#!forum/dataverse-community

**Comment by pdurbin** [comment]
@sbarbosadataverse yes, but let table it until the next meeting about the [DRAFT - Harvesting Functional Requirements Document (FRD)](https://docs.google.com/document/d/1XZHpTyYUwyPN3FIfJhaSFg5_h-9C415mlE42Fuao38w/edit?usp=sharing) whenever that is.

**Comment by mheppler** [comment]
@djbrooke @sbarbosadataverse  Now that 4.5 has been released, featuring the Harvesting functionality, we should review this again.

**Comment by scolapasta** [comment]
@sbarbosadataverse Can this be closed? Permissions are correctly set so no one can add a dataverse here except admin and you. So there is no code issue. There may be a curation issue for current unpublished dataverses that should not be there, but can that be put in the github curation project?

**Comment by pdurbin** [comment]
I agree that this isn't a code issue. It seems to be a configuration issue for https://dataverse.harvard.edu . If there's work to be done it should probably be tracked elsewhere.

**Comment by scolapasta** [comment]
Confirmed with @sbarbosadataverse that we can close.
