### ISSUE TITLE
Versioning "view difference" shows nothing when selected

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2635]
when select two versions to compare, there is no info being displayed:
study example: https://dataverse.harvard.edu/dataset.xhtml?persistentId=hdl:1902.1/00431

version 7 and 6 selected. Individual version "view info" also gives no information. This dataset was updated in feb 2015, before 4.0

<img width="488" alt="screen shot 2015-09-17 at 2 39 18 pm" src="https://cloud.githubusercontent.com/assets/8322346/10458796/9a721af4-719a-11e5-8ca8-6e2524def99d.png">

**Comment by sbarbosadataverse** [comment]
<img width="866" alt="screen shot 2015-09-17 at 2 19 17 pm" src="https://cloud.githubusercontent.com/assets/8322346/10458833/d103f4c0-719a-11e5-9de7-a0dbc521254e.png">

**Comment by bencomp** [comment]
Changes in terms not showing is a known issue: #2432 
(Keyword changes not showing up is known too: #2258)
