### ISSUE TITLE
"Dataset can't be created-contact support "bug"

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2637]
User reported this stale error message. Tried to create a dataset and can't save
![capture](https://cloud.githubusercontent.com/assets/8322346/10459066/d8e36ada-719b-11e5-9dcd-05d41bdf76ee.PNG)

**Comment by kcondon** [comment]
@sbarbosadataverse @scolapasta 
The bug is that you cannot create a dataset using a template and upload files at the same time. Creating a dataset with a template without files works and creating a dataset with files without a template works.

The workaround for now is to create the dataset using the template, then add files.

**Comment by sekmiller** [comment]
@kcondon  - There may be more to it than that.  I wasn't able to recreate this in the simplest case.  Do you have to change templates during the create process? Have a template with data in other metadata blocks? I will continue to try to recreate.

**Comment by sekmiller** [comment]
It happens when you go from no template to a template.

**Comment by sbarbosadataverse** [comment]
Thanks, Kevin. That's the one I didn't test--with adding files.

On Tue, Dec 8, 2015 at 6:20 PM, kcondon <notifications@github.com> wrote:

> @sbarbosadataverse
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sbarbosadataverse&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=CSb074B9N9_qa0lTyAB441eAXJPnlEeqYgRMghs0ffs&s=zbTgm0axove44mcjXd2Fqjrw1MuCkiqNpUCMvx0bccg&e=>
> @scolapasta
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_scolapasta&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=CSb074B9N9_qa0lTyAB441eAXJPnlEeqYgRMghs0ffs&s=-yH_7fZq3QCvJSjn4gTX940WZ8ja9Mx9v2lJLMAZdfQ&e=>
> The bug is that you cannot create a dataset using a template and upload
> files at the same time. Creating a dataset with a template without files
> works and creating a dataset with files without a template works.
>
> The workaround for now is to create the dataset using the template, then
> add files.
>
> —
> Reply to this email directly or view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_issues_2637-23issuecomment-2D163053757&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=CSb074B9N9_qa0lTyAB441eAXJPnlEeqYgRMghs0ffs&s=Gxv7vtvGdWXcYFeVlZZECeT6OTOI4AVKg-1oMlLKvJI&e=>
> .
>



-- 
Sonia Barbosa
Manager of Data Curation, IQSS Dataverse Network
Manager of the Murray Research Archive, IQSS
Data Science
Harvard University

Dataverse 4.0 is now available for use!
http://dataverse.harvard.edu

All test dataverses should be created  in 4.0 Demo!
http://dataverse-demo.iq.harvard.edu/

Join our Dataverse Community!
https://groups.google.com/forum/#!forum/dataverse-community

**Comment by sekmiller** [comment]
Fix checked into 4.2.2

**Comment by kcondon** [comment]
Fixed, closing.
