### ISSUE TITLE
Dataset File Request Access - Notification success message missing

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2639]
No message shows up after requesting accessing to "restricted"data to inform the user that their request was "successful."

**Comment by scolapasta** [comment]
On page, there is feedback, as designed, in the button text changing and being grayed out. Also, a notification is created (and e-mail sent).

@sbarbosadataverse assigning back as can't reproduce, and you can add more detail if this is mistaken.
