### ISSUE TITLE
Shorten and clean up bookmarkable search URLs (and refactor duplicate code)

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#264]
---

Author Name: **Philip Durbin** (@pdurbin)
Original Redmine Issue: 3678, https://redmine.hmdc.harvard.edu/issues/3678
Original Date: 2014-03-10
Original Assignee: Philip Durbin

---

As part of cleaning up the bookmarkable URL feature in pages that are powered by search (i.e. the Home/Dataverse page), we should remove duplicate code. The thinking that we'll factor it into a separate template or templates. An example of the duplicate code:

```
<c:forEach items="#{SearchIncludeFragment.filterQueries}" var="clickedFilterQuery" varStatus="status">
  <f:param name="fq#{status.index}" value='#{clickedFilterQuery}'/>
</c:forEach>

```

**Comment by scolapasta** [comment]
Optimistically setting this to beta 15, but if it has to wait until 4.01, we may need to defer it.

**Comment by pdurbin** [comment]
As of 90f3e73 the sorting part of the URL is shorter:

- sort=nameSort
- sort=dateSort

Holding on to this ticket to keep making the URLs shorter though.

**Comment by kcondon** [comment]
Some work has been done to shorten urls. @pdurbin would you mind being specific about what's left? Gustavo sees  this ticket primarily as a code refactoring ticket. Thanks.

**Comment by pdurbin** [comment]
@kcondon really I considered this to be a pre-4.0 issue. Now that Dataverse 4 is in production, we'd be breaking URLs that are bookmarked if we shorted them. I vote we close this issue and open another if we are interested in further shortening, which may break backwards compatibility. Passing to QA for consideration.

**Comment by kcondon** [comment]
Closing since the initial shortening was done.
