### ISSUE TITLE
Installation Guide: Provide sample glassfish start up script

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2640]
User asked about this, was in the v3.6 guide.

**Comment by pdurbin** [comment]
In my pull request at #2895 I addressed this issue. It can be previewed at http://guides.dataverse.org/en/2884-install-guide-reorg/installation/prerequisites.html#glassfish-init-script

Passing to QA.

**Comment by kcondon** [comment]
Init script provided, closing.
