### ISSUE TITLE
Support Link: Destination email address is hard coded, should be configurable.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2642]
See RT 228323

From Development:

For the Support link in the dataverse header the recipient email is hard-coded in SendFeedbackDialog backing bean

    private String defaultRecipientEmail = "support@thedata.org”;

this should probably get it from the settings table as

settingsService.getValueForKey(Key.SystemEmail);

**Comment by pdurbin** [comment]
This was originally reported by @shlake (thanks!) on the mailing list:

Changing the Support Link to Send Email to a local address - Google Groups - https://groups.google.com/forum/#!msg/dataverse-community/0OFRhXWW_i0/Je4JGmMJCwAJ

**Comment by sekmiller** [comment]
Fix has been checked in.  Build needed for testing.

**Comment by kcondon** [comment]
@sekmiller What was the fix? How configure it?

**Comment by kcondon** [comment]
OK, works. Tied to the system email value. Closing.
