### ISSUE TITLE
Performance: Use a CDN for css, javascript, and static images

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#2647]
Approximately, 75% of glassfish requests are for static assets including css, js, icons, etc.
- Put these on a separate CDN using the Glassfish CDN option `cdn.host=`:
  - https://docs.oracle.com/cd/E19575-01/820-7054/girpj/index.html
- primefaces reference:
  - http://stackoverflow.com/questions/15817578/is-primefaces-able-to-get-jquery-from-another-domain

fyi: Talk to OpenScholar team about their use of AWS as a CDN

**Comment by mheppler** [comment]
Closing duplicates of this issue and moving comments here.

@pameyer commented on Oct 6, 2017 in issue #4181
> Possibly related: #2647 , #1330
>
> 7 CSS files in dataverse_template.xhtml, 8 JS files; mix of minified and un-minified. These could potentially be combined (during the build process, not in source) to reduce the number of requests browsers need to make to render the page, which should help with UI performance. The slow step is still likely to be time for glassfish to generate the (x)html.

@mheppler commented on Nov 23, 2015 in issue #2754
> Our app serves the user 10 separate CSS files, and 13  separate JS files. Optimizing and efficiently serving these files by  combining and compressing these files will help improve client side  performance. One common resource that is frequently suggested is the WebUtilities Java library.

**Comment by pameyer** [comment]
@mheppler For this issue, I'd tend to interpret "use CDN" as "not glassfish" vs "use AWS".  Does this match your thinking (aka - support but not require external CDN)?

**Comment by mheppler** [comment]
That is true. But we could consolidate all of these suggestions into an issue to optimize the use of CSS and JS one way or another.

**Comment by pdurbin** [comment]
We tried to use a CDN for Bootstrap but due to controversy we removed it (before QA): https://github.com/IQSS/dataverse/issues/4219#issuecomment-403601277

Sadly, @raprasad is no longer here to advocate for CDNs so I'm closing this issue. A new champion for use of CDNs is very welcome to create a new issue.

**Comment by scolapasta** [comment]
We removed it with the idea of exploring community thoughts on it (e-mail forthcoming).

**Comment by mheppler** [comment]
I reopened _UI Performance - investigate improvements to static file handling #4181_ with the hopes that a solution can be found, without specifically suggestion one option or another.

@scolapasta I suggest that any outreach you undertake points to that issue, or we open another new issue, to track the community feedback you generate.

**Comment by pdurbin** [comment]
Not a bad idea but I'm closing this because [the JSF UI is going away](https://groups.google.com/g/dataverse-community/c/2hfhWIHQddE). We can revisit in the new React repo someday, perhaps: https://github.com/IQSS/dataverse-frontend
