### ISSUE TITLE
MyData: the "File Downloader" role alone should not be enough for cards of unpublished files to be displayed

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#2649]
From https://github.com/IQSS/dataverse/issues/2645#issuecomment-148713191

> When someone has the "File Downloader" role on a file, MyData currently [displays file cards with links to datasets that can not be viewed](https://cloud.githubusercontent.com/assets/8322346/10517621/84351358-732b-11e5-9717-b66b008b4c65.png) ("Not Authorized"). These files are unpublished.

![84351358-732b-11e5-9717-b66b008b4c65](https://cloud.githubusercontent.com/assets/21006/10551042/786418ec-7418-11e5-894c-321284a0d102.png)

@scolapasta and I discussed this and decided that these cards showing unpublished files should not appear in MyData based on the "File Downloader" role alone. This related to #2648 in that users with the "File Downloader" role alone shouldn't be able to download these files when the dataset has not yet been published.

I was thinking that perhaps the code in MyData that the generates the list of IDs could be modified to exclude these cards but @scolapasta suggested that MyData could be modified to start using the same "Solr permission documents" (a Solr JOIN) that the home pages uses. I'll consult with @raprasad and @sekmiller about this.

**Comment by sbarbosadataverse** [comment]
Yes, that's what I thought we agreed to yesterday? That MYdata should not
show the cards?
But in what case, along with "file downloader" would the card be expected
to show?

On Fri, Oct 16, 2015 at 3:19 PM, Philip Durbin <notifications@github.com>
wrote:

> From #2645 (comment)
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_issues_2645-23issuecomment-2D148713191&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=pCwzi0dSY1x2gAdKSAvPtwUzoedC9H1FaEXuo8bo9-c&s=R31fodnIzv_Jxf6w0gDp-wZyjLZv5yYtegvFAzauv2M&e=>
>
> When someone has the "File Downloader" role on a file, MyData currently displays
> file cards with links to datasets that can not be viewed
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__cloud.githubusercontent.com_assets_8322346_10517621_84351358-2D732b-2D11e5-2D9717-2Db66b008b4c65.png&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=pCwzi0dSY1x2gAdKSAvPtwUzoedC9H1FaEXuo8bo9-c&s=L-Q0KYwWbMsHYa4NPUz8chzHButOzvy1wJWys_fFqt8&e=>
> ("Not Authorized"). These files are unpublished.
>
> [image: 84351358-732b-11e5-9717-b66b008b4c65]
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__cloud.githubusercontent.com_assets_21006_10551042_786418ec-2D7418-2D11e5-2D894c-2D321284a0d102.png&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=pCwzi0dSY1x2gAdKSAvPtwUzoedC9H1FaEXuo8bo9-c&s=ubDnEFYUKVd_nrafBecyiixxyY-7kQP0PCeKggKfT6Y&e=>
>
> @scolapasta
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_scolapasta&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=pCwzi0dSY1x2gAdKSAvPtwUzoedC9H1FaEXuo8bo9-c&s=yaGHg8GrpCDQnJvHnsFLMZlHgaOOUu4k6KX-3xxgnCg&e=>
> and I discussed this and decided that these cards showing unpublished files
> should not appear in MyData based on the "File Downloader" role alone. This
> related to #2648
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_issues_2648&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=pCwzi0dSY1x2gAdKSAvPtwUzoedC9H1FaEXuo8bo9-c&s=VbW3i6AiszIwzj2mTGu1dYfdoC2cuzP4-xRllmaTtP8&e=>
> in that users with the "File Downloader" role alone shouldn't be able to
> download these files when the dataset has not yet been published.
>
> I was thinking that perhaps the code in MyData that the generates the list
> of IDs could be modified to exclude these cards but @scolapasta
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_scolapasta&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=pCwzi0dSY1x2gAdKSAvPtwUzoedC9H1FaEXuo8bo9-c&s=yaGHg8GrpCDQnJvHnsFLMZlHgaOOUu4k6KX-3xxgnCg&e=>
> suggested that MyData could be modified to start using the same "Solr
> permission documents" (a Solr JOIN) that the home pages uses. I'll consult
> with @raprasad
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_raprasad&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=pCwzi0dSY1x2gAdKSAvPtwUzoedC9H1FaEXuo8bo9-c&s=VlqJto7sVIX6-UVMvc-LlR4WfxY8o4fm5q5CQ8USwFY&e=>
> and @sekmiller
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sekmiller&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=pCwzi0dSY1x2gAdKSAvPtwUzoedC9H1FaEXuo8bo9-c&s=FjutHAaEB7HJ9sT-6phdYrl74zop3lIc4KW-S9kMM5U&e=>
> about this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_issues_2649&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=pCwzi0dSY1x2gAdKSAvPtwUzoedC9H1FaEXuo8bo9-c&s=ruyMxphnTNKr5XxM51fAZEVNGMRN1cHPzwhXsNq5428&e=>
> .
>



-- 
Sonia Barbosa
Manager of Data Curation, IQSS Dataverse Network
Manager of the Murray Research Archive, IQSS
Data Science
Harvard University

Dataverse 4.0 is now available for use!
http://dataverse.harvard.edu

All test dataverses should be created  in 4.0 Demo!
http://dataverse-demo.iq.harvard.edu/

Join our Dataverse Community!
https://groups.google.com/forum/#!forum/dataverse-community

**Comment by pdurbin** [comment]
> @scolapasta suggested that MyData could be modified to start using the same "Solr permission documents" (a Solr JOIN) that the home pages uses

This turned out to be a great idea and is what I went with in 0f53436. My first approach was to alter the MyData code that generates lists of database IDs so that the card doesn't show up and I started a [Google Doc about this](https://docs.google.com/document/d/1hiGhIP6fhlmtaSVCJBYMw7WELu6HHgQGP2IbKdp_hJ0/edit?usp=sharing) but this proved pretty tricky and complicated. By using the same Solr permission doc approach, the same "discoverability rules" (#57) are applied to MyData as the home page.

Passing to QA. Please note that the "File Downloader" role can be assigned at the file, dataset, or dataverse level. In no case should an unpublished dataset card appear in MyData with this permission alone anymore. (This was the problem reported in https://help.hmdc.harvard.edu/Ticket/Display.html?id=228447 .) The cards **should** continue to appear if you have higher roles, such as Member, which allows you to view unpublished datasets.

An operational note is that we can back out of this change if we need to with a setting I added. By default you get the new behavior of MyData using the Solr permission documents. If you want compare with the old behavior from 4.2, the ":MyDataDoesNotUseSolrPermissionDocs" setting can be set to true.

@sbarbosadataverse I'm not sure what you mean but let's touch base on this. We're planning on testing soon on dvn-vm5 if you'd like to help.

**Comment by kcondon** [comment]
OK, filedownloader only role will not cause file to appear in My Data if dataset or dataverse is restricted. If member role is assigned, it is. 

Closing this issue. There are related issues that will be tested separately (notification, messaging).
