### ISSUE TITLE
Hosting: Change dataverse-demo to be demo.dataverse.org

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2651]
Gary ran into a cert issue on demo but most likely due to using the hmdc rather than iq url. Still, it revived the request to change the hostname for this box and corresponding cert. See RT 228519

Looking at the warning from Chrome from the iq URL, it says the cert is valid but that it uses a weak security configuration, SHA-1 so communication may not be private. 

@pdurbin FYI

Phil

By the time you mess with all the certs it's probably half a day's work.

Kevin

I personally can't do it, I don't know how. I've asked Phil if he would and he agreed but said it would take 4 hours of work.

Can we meet next week sometime to talk about environments generally as Raman suggested?

6/24/15

I also like to change dataverse-demo.iq.harvard.edu to demo.dataverse.org  

can we go ahead with this change?

Merce

**Comment by eaquigley** [comment]
Can we also make sure that when this is done dataverse-demo.iq.harvard.edu redirects to demo.dataverse.org. That link is out there a lot.

**Comment by pdurbin** [comment]
@eaquigley yes. No problem. We'll redirect the old site similar to how we redirect thedata.org: https://github.com/IQSS/dataverse.org/blob/master/deploy/files/etc/httpd/conf.d/1thedata.org.redirect.conf

**Comment by eaquigley** [comment]
@pdurbin cool. i figured it would but wanted to make sure it was written down

**Comment by pdurbin** [comment]
Yep. I put this in the 4.2.1 milestone so I don't forget about it but in practice this is not a code thing at all. Once 4.2.1 is frozen I'll work on it.

**Comment by pdurbin** [comment]
On second thought, I'm pulling this out of the 4.2.1 milestone because (again), it's not a code thing (for this repo anyway) and I don't want to clutter that milestone. I won't forget about this task. It's high on my list: https://trello.com/c/vQWdO7ao/221-rename-demo-site-to-demo-dataverse-org

**Comment by pdurbin** [comment]
Note to self: Shibboleth login will stop working on the demo site after we switch hostnames until we re-exchange metadata with Harvard and MIT. In #2104 it was recommended to have our EntityID end with "sp" rather than "shibboleth" so it would be a good time to make this switch on the demo site.

**Comment by pdurbin** [comment]
> Looking at the warning from Chrome from the iq URL, it says the cert is valid but that it uses a weak security configuration, SHA-1 so communication may not be private.

Yeah, it looks like this (angry red X):

![screen shot 2015-10-22 at 3 38 53 pm](https://cloud.githubusercontent.com/assets/21006/10676265/127a0568-78d3-11e5-87a9-a5fd14aba711.png)

I'm starting to list the steps at https://trello.com/c/vQWdO7ao/221-rename-demo-site-to-demo-dataverse-org (including shib stuff) before I start executing them.

**Comment by pdurbin** [comment]
@kcondon as we discussed, I'm passing this to you to so some QA on the new hostname: https://demo.dataverse.org

The cert definitely looks good:

![screen shot 2015-10-23 at 4 32 57 pm](https://cloud.githubusercontent.com/assets/21006/10704297/eab5bf0a-79a3-11e5-8854-60322ae2a268.png)

I think most things are working fine. I tested TwoRavens and Zelig, for example (and also opened a related issue at https://github.com/IQSS/TwoRavens/issues/47 ):

![screen shot 2015-10-23 at 4 03 40 pm](https://cloud.githubusercontent.com/assets/21006/10704313/0a2decb8-79a4-11e5-9d6d-a076bc15ba4e.png)

(Don't mind the Chrome debugging toolbar above.) :)

Unfortunately, redirects of HTTPS (not plain HTTP) might be harder than I realized ( http://serverfault.com/questions/83658/apache-ssl-new-domain-redirect ) so one stays on https://dataverse-demo.iq.harvard.edu right now, which is not what I want. I'll ping @landreev for ideas when he's back. Maybe @whorka has some thoughts. Sorry, @eaquigley ! This might be phase 1.5 to work on this. :/ Redirects of plain HTTP should be working fine such as http://dataverse-demo.iq.harvard.edu .

Phase 2 will be to get Shibboleth back on the demo site, which requires coordination with third parties. So @kcondon please pass this issue back to me after you're done.

**Comment by kcondon** [comment]
OK looks good, closing.

**Comment by pdurbin** [comment]
@kcondon as I mentioned, there were some references to the old demo hostname in the git repo and I just fixed these in d083580. Since we reviewed this together, I'm not going to re-open this issue.
