### ISSUE TITLE
Assign Role Pop Up: Carry Role Descriptions Over

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2658]
In the Assign Roles pop up, the description for a role from the roles table on the dataverse or dataset permissions page, needs to be carried over. Currently only the role name and the permissions it has appears in the right hand side of that pop up.

**Comment by mheppler** [comment]
Added role description to the Assign Role popup on the Dataverse/Dataset Permissions pg.

**Comment by kcondon** [comment]
OK, text in place. Closing.
