### ISSUE TITLE
File Permissions: Change Name to Reflect it is only for restricted files

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2659]
File Permissions Page should be changed to be Restricted Files Permissions. This page is only for granting access to restricted files; has nothing to do with non restricted files.

**Comment by mheppler** [comment]
Here is an outline of all the places where text title, headers, labels, etc. have been changed, as well a few other minor text/icon edits and additions.

*Dataverse/Dataset Permissions Pg > Assign Role Popup*
- Change “User/Group” input label to “Users/Groups”

*Dataset Pg*
- Change “File Permissions” references (edit link) to "Restricted File Permissions"

*Restricted File Permissions Pg*
- Change “File Permissions” references (page header, page title, section header) to "Restricted File Permissions"

*Restricted File Permissions Pg > Grant File Access Popup*
- Change “File” table header to “File Name” on Restricted Files dataTable
- Add check/ban icons to Grant/Reject action buttons

*Restricted File Permissions Pg > File Access Popup*
- Change “File” table header to “File Name” on Restricted Files dataTable
- Add ”x” icon to Remove action button
- Add Users/Groups “(Affiliation)” to dataTable

**Comment by mheppler** [comment]
This feature was delivered as part of the pull request [#3346](https://github.com/IQSS/dataverse/pull/3346) and merged into develop.

**Comment by kcondon** [comment]
Looks good, was already merged. Closing.
