### ISSUE TITLE
System Email: Default value for system email seems to be support@thedata.org, an out of date email domain.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2663]
From RT 228627, a user was having trouble getting reset password email due to not configuring system email. The instructions are not in the guide but that is a separate ticket.

This issue is about what they're seeing as a default: support@thedata.org. This email domain is ours but is now outdated, should be support@dataverse.org as in the setup-optional-harvard.sh script:

curl -X PUT -d "Dataverse Support <support@dataverse.org>" http://localhost:8080/api/admin/settings/:SystemEmail

**Comment by pdurbin** [comment]
I think this issue is really about documenting how to configure the system email so I'm going to try to wrap it into #2884.

**Comment by pdurbin** [comment]
In my pull request at #2895 I documented how to set the system email. The change can be previewed at http://guides.dataverse.org/en/2884-install-guide-reorg/installation/config.html#systememail

Passing to QA.

**Comment by kcondon** [comment]
Documented, closing.
