### ISSUE TITLE
Improve error message when metadata block added but Solr schema is not

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#2665]
It would be nice to have a more informative error message than this if you load a new metadata block tsv file and forget to update the Solr schema.xml that has the new fields in it:

![screen shot 2015-10-21 at 4 25 55 pm](https://cloud.githubusercontent.com/assets/21006/10649174/8a7a34fc-7810-11e5-80c8-70f754d6e53c.png)

 Dataset Save Failed  - edu.harvard.iq.dataverse.engine.command.exception.CommandException: Command [DatasetCreate dataset:null] failed: null
The dataset could not be created.  Please contact support.

Some of the error also appears in the log:

[2015-10-21T16:23:27.680-0400] [glassfish 4.1] [SEVERE] [] [edu.harvard.iq.dataverse.DatasetPage] [tid: _ThreadID=130 _ThreadName=http-listener-1(5)] [timeMillis: 1445459007680] [levelValue: 1000] [[
  Command [DatasetCreate dataset:null] failed: null]]

For now the clue that Solr doesn't know about a new field is in its own log:

2932024941 [qtp918598659-2314] ERROR org.apache.solr.core.SolrCore  – org.apache.solr.common.SolrException: ERROR: [doc=dataset_13_draft] unknown field 'hbgdkiStudyName'
    at org.apache.solr.update.DocumentBuilder.toDocument(DocumentBuilder.java:174)
    at org.apache.solr.update.AddUpdateCommand.getLuceneDocument(AddUpdateCommand.java:77)
    at org.apache.solr.update.DirectUpdateHandler2.addDoc(DirectUpdateHandler2.java:215)

**Comment by pdurbin** [comment]
Here's a case of a user running into this user: https://groups.google.com/d/msg/dataverse-community/KZkD0PvDv8E/KDmwvFMPAgAJ

As I wrote there, the user in this case is probably a sysadmin who is standing up Dataverse for the first time and kicking the tires to see if it even works.

Our number 1 goal at http://dataverse.org/goals-roadmap-and-releases is "increase adoption (users, dataverses, datasets, installations, journals)" and resolving this issue might help lead to more sysadmins getting Dataverse stood up for the first time and showing it to their end users.

**Comment by shivadcedtu** [comment]
[server.txt](https://github.com/IQSS/dataverse/files/556596/server.txt)

sir, I have updated the schema.xml file but still cant add dataverse into it.
Please help me as I am stuck with this issue.

**Comment by pdurbin** [comment]
@shivadcedtu you must have seen my message at https://groups.google.com/d/msg/dataverse-community/KZkD0PvDv8E/KDmwvFMPAgAJ

When you look at the output of http://localhost:8983/solr/schema/fields (replace "localhost" with the name of your server, as necessary), do you see "dv" stuff like "dvAffiliation", "dvCategory", "dvDescription", etc? Here's a screenshot:

![screen shot 2016-10-28 at 8 57 24 am](https://cloud.githubusercontent.com/assets/21006/19807127/a4706a14-9cec-11e6-91d8-16b2c726e3f6.png)

If you see all that "dv" stuff, your installation of Solr has the Dataverse-specific "schema.xml" file in place, the one I mentioned in that thread and that we explain at http://guides.dataverse.org/en/4.5.1/installation/prerequisites.html#solr . If you **don't** see all that "dv" stuff, please stop Solr and try again to put the "schema.xml" file in place. I hope the instructions are clear enough but I am very open to suggestions for improvement.

This is a URL we ask developers to check at http://guides.dataverse.org/en/4.5.1/developers/dev-environment.html#installing-and-running-solr

**Comment by shivadcedtu** [comment]
hey ,thank you very much.
I could resolve the issue.

**Comment by pdurbin** [comment]
@shivadcedtu fantastic! Thanks for letting us know! If there's something we should add to the Installation Guide, please let us know.

**Comment by pdurbin** [comment]
I guess people are surviving without any special messaging. We always indicate in our release notes when you need to update your Solr schema. Closing.
