### ISSUE TITLE
Guestbooks: View collected data for large dv, ds, downloads takes a really long time.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2670]
Clicking view collected data for a large dv takes a long time to open. Have not yet looked at load impact on system.

For example: https://dataverse.harvard.edu/guestbook-responses.xhtml?dataverseId=2690441&guestbookId=9

It took 47 seconds to display initially and 74 seconds total to complete loading.

**Comment by scolapasta** [comment]
Per issue #2946, if it's large enough, this causes a timeout:
"guestbook "view collected info" feature is timing out due to volume of information -
IFPRI is an example. There are over 11000 entries and user can't access their own stats. Currently IFPRI has 57 datasets using the guestbook."

**Comment by kcondon** [comment]
This is much better, took 10 seconds to view ifpri 10000 records. Closing.
