### ISSUE TITLE
A dataverse can not be published if the File Downloader role has been assigned at the dataverse level

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#2671]
Something about "Caused by: java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key notification.access.granted.fileDownloader.additionalDataverse"

I can only assume this is a regression in 4.2.1 but I don't really know.

**Comment by pdurbin** [comment]
I demo'ed this to @sekmiller and he said to assign it to him.

**Comment by pdurbin** [comment]
I'm not sure why I'm seeing this on my machine but @sekmiller isn't seeing it on his or why I can't reproduce the bug on v. 4.2.1 build 8-a0bc225 at dataverse-internal.

I guess I'll hold on to this issue for now.  This is the line in question as of fa73991:

src/main/java/edu/harvard/iq/dataverse/MailServiceBean.java
333:                        pattern = ResourceBundle.getBundle("Bundle").getString("notification.access.granted.fileDownloader.additionalDataverse");

**Comment by pdurbin** [comment]
As of 44b67ac I can't reproduce this on my laptop any more. Quite possibly this was just me and if so I apologize for the noise. I'm now able to give the user "finch" the "File Downloader" role at the dataverse level and publish it:

![screen shot 2015-10-23 at 10 00 43 am](https://cloud.githubusercontent.com/assets/21006/10694627/344af41e-796d-11e5-9a21-2bc572929763.png)

Passing to QA for a sanity check.

**Comment by kcondon** [comment]
Works on internal. Closing.
