### ISSUE TITLE
Can't publish a dataset that contains a file

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#2672]
I've tried publishing a dataset containing a file from my laptop running fa73991 and from dataverse-internal (i.e. doi:10.5072/FK2/EO4IB7 ) and in both cases it failed to publish and I saw OptimisticLockException in server.log. Same behavior on @sekmiller 's laptop. @landreev thinks some fixes he's working on might help so I'll give this to him.

"Exception Description: The object [edu.harvard.iq.dvn.core.study.FileMetadata[id=1]] cannot be merged because it has changed or been deleted since it was last read."

**Comment by pdurbin** [comment]
Interestingly, I'm able to publish the database on my laptop via SWORD with scripts/search/tests/publish-dataset-spruce1 . So I guess it is probably something in the dataset page, which is being worked on in #2650.

**Comment by kcondon** [comment]
@pdurbin @landreev , I am seeing the same issue on dataverse internal

**Comment by landreev** [comment]
yeah - that's today's build. working on this now.

**Comment by landreev** [comment]
Please retest this as well.

**Comment by kcondon** [comment]
This is now working, closing.
