### ISSUE TITLE
HandlenetServiceBean must not catch Throwables

### ISSUE THREAD

**Issue by bencomp** [IQSS/dataverse#2674]
SonarQube found some issues that must be addressed immediately, among which are four violations of the rule "`Throwable` and `Error` should not be caught", all found in `HandlenetServiceBean`.

Rationale:

> `Throwable` is the superclass of all errors and exceptions in Java.
>  `Error` is the superclass of all errors, which are not meant to be caught by applications.
>  Catching either `Throwable` or `Error` will also catch `OutOfMemoryError` and `InternalError`, from which an application should not attempt to recover.
>  Only `Exception` and its subclasses should be caught.

**Comment by pdurbin** [comment]
Closing to consolidate into #3950.

**Comment by bencomp** [comment]
Triggered by #9846, I notice that Sonarcloud does not mark this still existing issue as problematic.
