### ISSUE TITLE
Implementation of Object.finalize() must call super.finalize()

### ISSUE THREAD

**Issue by bencomp** [IQSS/dataverse#2675]
SonarQube found a few issues that must be solved immediately. One is the violation of the rule "`super.finalize()` should be called at the end of `Object.finalize()` implementations" in `ServiceRegistry`.

Rationale:

> Overriding the `Object.finalize()` method must be done with caution to dispose some system resources.
>  Calling the `super.finalize()` at the end of this method implementation is highly recommended in case parent implementations must also dispose some system resources.

I found it strange that this class and related classes are even in the codebase, seeing that they have been copied from an old JDK and are still in the JDK in a form _with generics_ as `javax.imageio.spi.ServiceRegistry`. It creates some copyright issues too, as I mentioned in #2576.

**Comment by pdurbin** [comment]
Closing to consolidate into #3950.
