### ISSUE TITLE
Upload Files: Upload status bar includes unpacking of zip file, it should probably only include upload of zip file itself.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2678]
This is kind of a UX issue but also a technical one. the upload status bar for a 1000 file zip file does not increment until it unpacks all 1000 files. This takes much longer than uploading the actual zip file, which is tiny. This is a problem because it gives incorrect information and may result in the user aborting the operation, getting confused, etc.

**Comment by kcondon** [comment]
Related to slow upload of large zip files, see #2482

**Comment by kcondon** [comment]
Retested, now do not see the progress bar, only a spinner that spins for 24 seconds with 1000 file zip. Behavior and intrusiveness may vary depending on # and size of files in zip. Basic question of whether to include unzipping as part of "upload" progress. Can't add files to list until unzipped but can it be improved, possibly by updating as unpack or in batches?

**Comment by djbrooke** [comment]
- Need to view the behavior
- See how other sites handle this
- Decide whether or not to include in 4.6 or as a large file reorganization effort

**Comment by mheppler** [comment]
Related to #3116.

**Comment by djbrooke** [comment]
Talked with @landreev about earlier this afternoon. This issue will still persist after #3116 is implemented, but the wait time will not be as long. This may be reprioritized based on how much of an improvement has been realized.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
