### ISSUE TITLE
File Tab: Search does not work when there is one page or less of files.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2679]
When I upload just a few files and search on filename, it does not seem to update the page at all but when there is more than one page of files, it does search and return only matching files.

I understand part of the reason for search is to facilitate browsing multiple pages of files but I think it should always work to be consistent and potentially if searching by card were working, that alone would be useful. 

Btw, the current page size seems to be 100+ files.

**Comment by sekmiller** [comment]
The search was being suppressed when the dataset was not in edit mode(read only)

**Comment by kcondon** [comment]
This is still happening. Create a dataset, load file1, publish. Upload file2 to create a draft. From version 1, search for file2 and it appears.

**Comment by landreev** [comment]
I want to grab this issue.

**Comment by landreev** [comment]
Ready to QA (after a new build).

**Comment by kcondon** [comment]
Works, closing
