### ISSUE TITLE
Files Tab: Search only works on names. Should it do more?

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2683]
@eaquigley @mheppler @scolapasta 
File search and facets outside of the files tab allows:
Adv Search:
Name
Description
File Type
Variable Name
Variable Label
Facets:
File Type
File Tag
Access

Not sure what should be searchable on the files tab and whether some will be implemented now, some later? Tags in particular would be nice to be searchable or filterable on the files tab, description too.

**Comment by kcondon** [comment]
For the record, it does search on partial names, regardless of case, including just .extension.

**Comment by kcondon** [comment]
Discussed in meeting, add search for description for now, avoid more complex searches requiring joins.

**Comment by sekmiller** [comment]
Added Description to search.  New build required to test...

**Comment by kcondon** [comment]
OK, works closing.
