### ISSUE TITLE
Files Tab: Search box will show files from the latest version of a dataset, not the one being viewed.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2684]
Search box will show files from the latest version of a dataset, not the one being viewed.

**Comment by sekmiller** [comment]
It's actually only from the latest version of the dataset as currently coded.

**Comment by sekmiller** [comment]
This is probably because search had been set as a non-ReadOnly function so only the latest version needed to be considered. @landreev since we need to open up searching to all versions is it OK to return the search parameter to working version id?

**Comment by sekmiller** [comment]
Duplicate of #2679

**Comment by landreev** [comment]
@kconodon : since this is a duplicate (of 2679), should I close one of these? Or keep both open?

**Comment by landreev** [comment]
Search should now be working properly. Both in draft and published versions.

**Comment by kcondon** [comment]
This is working now, closing
