### ISSUE TITLE
Files Tab: Tabular file category tags disappear from published dataset versions, present in drafts.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2687]
As soon as we publish a dataset, the tabular file categories disappear, are not rendered. They are still there -if you try to add new ones you can see they are already selected and if you create a new draft they reappear.

**Comment by sekmiller** [comment]
This has been fixed.

**Comment by kcondon** [comment]
Works, closing.

**Comment by landreev** [comment]
@sekmiller: just fyi, I have removed the refreshTableTags() method - because the tags are now being properly set from the db.
