### ISSUE TITLE
dataverse.org: change the link to the demo site to use the new name: demo.dataverse.org

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2688]
Not sure who should get this or of this is the right queue but the link to the demo site on dataverse.org should change to demo.dataverse.org

**Comment by eaquigley** [comment]
Per feedback from Gary, I needed to update something with that link anyways. I've updated it to be demo.dataverse.org, have removed the button from the homepage of dataverse.org and added it as a link to the Add Data and the Features page. Passing back to @kcondon for QA (does that make sense as it isn't part of the repo?)

**Comment by kcondon** [comment]
Looks good,thanks! Closing.
