### ISSUE TITLE
Files Tab: Resizing page to be more narrow causes download buttons to move off page/ disappear.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2689]
The files tab is not responsive to resizing: the explore and download buttons seem to get chopped and move off screen and disappear when browser sized smaller, more narrow. 

Works for res down to 1024x768, 800x600 is chopped. 800x600 or lower is about 3.5% of traffic per google analytics.

It does happen on my 1366x768, single window PC when I resize browsers to be smaller to fit in order to have multiple apps on my desktop so that may be a common use case.

Happens in both Chrome and FF on Windows 10.
Chrome Version 46.0.2490.71 m
FF 40.0.3

**Comment by mheppler** [comment]
Improved responsiveness of the files table on the dataset pg.

Buttons no longer get cut, but they do look funky, stacked in smaller browsers. This will have to be a temporary fix, until we have a chance to prioritize UX for mobile and tablet users, and make necessary design improvements across the board.

**Comment by kcondon** [comment]
Much better,  thanks. Closing.
