### ISSUE TITLE
Files Tab: Sometimes Infinite Scroller does not work or stops working

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2695]
@sbarbosadataverse and @posixeleni both saw issues with the scroller when testing on beta.dataverse.org

They were using FF and Chrome and either did not see the scroll bar at all or it fetched 200 file or so and then stopped scrolling. Eleni noticed a difference being logged in and logged out.

I was able to use the scroller using both FF and Chrome on Windows 10 and Mac but tried retesting this and noticed in Chrome it sometimes doesn't scroll if the vertical height is not tall enough and sometimes the scroller goes deaf when going through many files.

**Comment by posixeleni** [comment]
To see if you can duplicate this error: On Google Chrome for Mac (Version 46.0.2490.71 (64-bit)) 

Went to beta.dataverse.org as a Guest ( not logged in and logged in) and tried to scroll to see all the files in the 1000 Files dataset. Not able to infinite scroll.

**Comment by kcondon** [comment]
After discussing with Mike and double checking with Sonia and Eleni, it looks like the FF issue was due to needing to select or highlight the table to enable the files table scrollbar. This is potentially a UX issue since not everyone would be aware to do that.

For Chrome, the scroll bar is not working at all and Mike thinks he has a quick fix so I am passing this to him at his request.

**Comment by pdurbin** [comment]
It sounds like this is a well known issue but I thought I'd chime in that for me on Chrome if I can get the blue spinning wheel to show up by resizing the window a few times I'm able to see beyond the initial 25 files in my dataset.

**Comment by mheppler** [comment]
Fixed scrolling issue found in Chrome by applying a margin to the bottom of the files table.

**Comment by pdurbin** [comment]
Much better. Thanks, @mheppler !

**Comment by kcondon** [comment]
Works, closing. There is an issue with whitespace at the bottom of the page but that was opened as a separate ticket.
