### ISSUE TITLE
Dataset Files Scroller: Both internal and external scroller scrolls as you reach the bottom + page grows with whitespace.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2696]
In Chrome, the infinite scroller is now working but as you keep scrolling, the length of the page grows, padded with whitespace and so the outside scroll bar begins scrolling as you scroll the internal files table one. So, it's kind of confusing.

**Comment by mheppler** [comment]
Related to #2731.

Changing the scrolling table to a new [PrimeFaces 5 DataScroller component](http://www.primefaces.org/showcase/ui/data/datascroller/loader.xhtml) will resolve this issue.

**Comment by kcondon** [comment]
The page growing with whitespace is no longer happening. Closing.
