### ISSUE TITLE
Permissions: Removing a role assigned at Root, such as curator, is not immediately reflected in browse results due to slow indexing.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2697]
Sonia attempted to remove a curator role assignment from root, it did not remove it and service became unresponsive shortly afterwards. Not sure it was related to service issue. There is another ticket about permission performance but this is a very specific use case that should be considered for changing how the transaction is managed, eg. remove role first in one transaction, do reindex in another transaction.

**Comment by pdurbin** [comment]
Right, at https://github.com/IQSS/dataverse/issues/2036#issuecomment-147706851 we re-confirmed that it only takes a few milliseconds to remove the role assignment from the database. The expensive part is the reindexing.

**Comment by kcondon** [comment]
Retest with production db

**Comment by pdurbin** [comment]
My earlier comment at https://github.com/IQSS/dataverse/issues/2697#issuecomment-151539046 is no longer accurate in the sense that the user removing the role no longer experiences the expense of reindexing (watching the spinner spin) since it was made asynchronous in #2036.

**Comment by kcondon** [comment]
So does that mean this is no longer an issue then?


________________________________

**Comment by pdurbin** [comment]
I depends on how you interpret what this issue is about, I guess. Indexing is not immediate, it's just asynchronous now. If desired, we could turn this issue into the new #50 about indexing being too slow. But that issue was recently closed as fast enough.

**Comment by kcondon** [comment]
Spoke with Phil. Before asynch indexing, Sonia would just see a spinner after removing and would seem to never return. Now returns but user would continue to see cards they no longer have access to until index is complete. This last asynch mode is how we interpreted the issue.

As for this being indexing being too slow and how it related to #50, that was about the sys admin use case of doing an overnight index all not completing in a reasonable time. That is good enough, happens in a few hours but not the same use case as this: curation of permissions.

It's clear there is not a likely short term solution to slower index times or even an ultimate solution so we need to decide if this is ok to live with.

**Comment by kcondon** [comment]
Asynch change made this much better but given the current perms/ index architecture the amount of improvement would not significantly change this so we should live with it for now and revisit if it becomes a problem for users. Closing.
