### ISSUE TITLE
Dataset Files - DataTable LiveScroll w/ Duplicate Files

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#2699]
In a [local dataset pg](http://mheppler.pagekite.me/dataset.xhtml?persistentId=doi:10.5072/FK2/HOV2LR), I have files 026.txt - 050.txt duplicated multiple times, due to the table reloading the same 25 files it loaded previously.

To replicate it, load the dataset pg, scroll the page half way down, then hover over the files table, to scroll the files and trigger a liveScroll refresh for additional files. While the blue spinner is on the page, quickly start scrolling the table further. I was able to replicate it multiple times with this approach.

This was in Firefox (v 41.0.2). Dataset is published. I wasn't logged in.

(Pay no attention to the icons being cut off in this screenshot. That layout issue was resolved in another ticket.)

![screen shot 2015-10-27 at 12 56 15 pm](https://cloud.githubusercontent.com/assets/687227/10765656/293234d0-7caa-11e5-9c86-53141b743025.png)

**Comment by landreev** [comment]
Hmm. This sounds like PF's scroll is just buggy (allowing to activate scrolling while it's already scrolling...)
Unless of course this is something we are doing wrong. Will investigate.

**Comment by sekmiller** [comment]
For what it's worth, I was able to get it to happen, but when I selected the same file twice and clicked "download all" I only got it once.

**Comment by landreev** [comment]
I'm at a loss as to what to do with this one... Doesn't seem like anything we are doing (i.e., this is the behavior of the PF component). There could still be a way to disable extra scrolling while another scrolling is in progress... I just don't know how to do that .
@sekmiller - any chance you have time to take this one for investigation?

**Comment by pdurbin** [comment]
I spoke with @sekmiller this morning and he said he's able to replicate the bug. I just tried locally (I'm on commit a593b40 ) and couldn't. I walked over to @mheppler and we couldn't replicate it on his machine either.

**Comment by kcondon** [comment]
@mheppler @pdurbin @sekmiller @landreev 

I can reproduce the bug. It creates duplicate blocks of files, not two of the same next to each other.

**Comment by kcondon** [comment]
@mheppler @pdurbin @sekmiller @landreev 

I did more testing and confirmed edit, delete, restrict, download only affect the file chosen, even if both copies are chosen.

**Comment by landreev** [comment]
Putting the ticket into 4.3. Also, removing my name. (It ended up in my queue kinda randomly - I asked for it thinking it could be something I was doing with the filemetadatas; but it quickly became apparent this had to do with the idiosyncrasies of the PrimeFaces'  scroller). 
Let's decide who'll be working on this for 4.3.

**Comment by mheppler** [comment]
A new issue, **Dataset - File UI Improvements #3404**, was created to track the UI improvements related to the files view on the dataset pg. Older feature requests and bug reports like this one will be closed in favor of that new issue.
