### ISSUE TITLE
Dataset Files Table: Table Tries to Load More Files, When There Are No More

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2701]
[Kevin]
My original report was that if there were exactly 25 files, the scroll bar appears and you can scroll back and forth, the spinner runs and seems like it is doing work. Not sure this is very important but wanted to mention it. So for instance there could be logic that if there are exactly 25 files, it does not do the cut off thing, that was my only point.

[Mike]
If a dataset has enough files to go past the "92%" scrollHeight of the files datatable -- the file count setting for the scroller cut-off is 25 files -- it partially displays the last file, shows a scrollbar (in Chrome) and always displays the spinner when you scroll to the bottom of the table because it's trying to load more files, even if there aren't any more files to load.

See [Twenty-Five (25, XXV)](https://dataverse-internal.iq.harvard.edu/dataset.xhtml?persistentId=doi%3A10.5072%2FFK2%2F9QZKGO) or [Test Wrong File Bug](https://dataverse-internal.iq.harvard.edu/dataset.xhtml?persistentId=doi:10.5072/FK2/0WPI4W) on dataverse-internal.

**Comment by mheppler** [comment]
Related to #2731.

Changing the scrolling table to a new [PrimeFaces 5 DataScroller component](http://www.primefaces.org/showcase/ui/data/datascroller/loader.xhtml) will resolve this issue.

**Comment by mheppler** [comment]
A new issue, **Dataset - File UI Improvements #3404**, was created to track the UI improvements related to the files view on the dataset pg. Older feature requests and bug reports like this one will be closed in favor of that new issue.
