### ISSUE TITLE
Search: Text after and including Ampersand (&) is removed from Search Query

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#2702]
I did a search for a known item: "Economics & Politics" which is a journal title (see dataset: https://dataverse.harvard.edu/dataset.xhtml?persistentId=hdl:1902.1/21940). Instead of returning results that match this query the query dropped the ampersand and any text after that so was just searching for "Economics"

**Comment by mheppler** [comment]
I am closing this issue, and consolidating it with other related issues in an old issue that I have retitled as _**Search: Accented characters, ampersands, negative numbers and other special characters #820**_.

Any further information about this bug or other "special character" related search issues, please add your comment there.
