### ISSUE TITLE
DatasetPage: can't create Guestbook entry when downloading a file, in readonly mode.

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#2703]
Verified that this is a new, untracked issue. 
This is happening when the DatasetPage is in the new, optimized "read-only" mode. I.e., when looking at a non-draft version, or a draft version with no permission to edit.
When you try to download a file, you get the file just fine; but a guestbook entry is not created. (and there are errors in the logs indicating that). 
This is relatively serious, but I know what needs to be done to fix it.

**Comment by kcondon** [comment]
I tested this on the test server and did not see the problem. It was most likely some corruption in the dev db. Closing.
