### ISSUE TITLE
Guides: Throws 404 error in test when accessing guides.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2704]
@pdurbin 
All guides links throw 404 errors for 4.2.1 at the moment.

**Comment by pdurbin** [comment]
Confirmed. This is a regression. It worked in 4.2.

**Comment by pdurbin** [comment]
I just pushed ca871c5 which is the minimal change to fix the bug. The regression was introduced as part of the #2656 which also lead to duplicate `getGuidesBaseUrl` methods. There's a todo in the code to address this duplication some day.

@kcondon when testing please do confirm that you're still able to configure the guides URL (a feature implemented in #2153) like this:

`curl -X PUT -d http://dataverse.example.edu http://localhost:8080/api/admin/settings/:GuidesBaseUrl`

This feature is documented at http://guides.dataverse.org/en/4.2/installation/installation-main.html#guidesbaseurl

Passing to QA.

**Comment by kcondon** [comment]
Works, closing.
