### ISSUE TITLE
Add "View All" button for files on the dataset page

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#2705]
Now that we're adding scrolling, we'd like to have a "View All" button rather than forcing people to scroll and scroll until they can see all the files.

**Comment by sekmiller** [comment]
Added a prelim version that gets all.  Mike will look at styling and/or adding a customizable number of records.

**Comment by sekmiller** [comment]
@mheppler added a Show All link to the footer facet of the files table.

**Comment by kcondon** [comment]
@mheppler @pdurbin @sekmiller 
Scroll bar no longer working. This needs to be restored or show all removed if we're releasing Thursday

**Comment by pdurbin** [comment]
@sekmiller said he'd take a look.

**Comment by sekmiller** [comment]
https://github.com/primefaces/primefaces/issues/685

reported issue to PrimeFaces

**Comment by sekmiller** [comment]
We decided for the purposes of 4.2.1 to forgo this one

**Comment by kcondon** [comment]
OK, works, closing.

**Comment by pdurbin** [comment]
@kcondon and I agreed that since we want this feature in 4.3 we should set the milestone to 4.3 and reopen it, so I'll do that now. Basically, it was deferred for the 4.2.1 release. @sekmiller since you'll be working in this area I'll give this issue to you.

**Comment by mheppler** [comment]
A new issue, **Dataset - File UI Improvements #3404**, was created to track the UI improvements related to the files view on the dataset pg. Older feature requests and bug reports like this one will be closed in favor of that new issue.
