### ISSUE TITLE
HttpSolrServer in the class of SearchServiceBean  doesn't shutdown.

### ISSUE THREAD

**Issue by pengchengluo** [IQSS/dataverse#2706]
In the class of edu.harvard.iq.dataverse.search.SearchServiceBean, every search request create a HttpSolrServer object. However, HttpSolrServer has a method named shutdown() which releases some resources. So the code must invoke the shutdown method.

Besides, when construct the HttpSolrServer object, it will create a HttpClient. This process is expensive and there is no need to create a new HttpSolrServer for every search request.

**Comment by pdurbin** [comment]
@pengchengluo thanks for pointing this out! @bencomp and I chatted about this at http://irclog.iq.harvard.edu/dataverse/2015-10-29 (good catch, as he said) and I was wondering if you've measured how expensive the process is. Also, I would be more than happy to review a pull request if you are inclined to try addressing this issue!

**Comment by pengchengluo** [comment]
Hi @pdurbin , I have done a simple test using the following code to measure the cost.
+++++++++++++++++
        long pre = System.currentTimeMillis();
        for(int i = 0;i<5000;i++){
            SolrServer solrServer = new HttpSolrServer("http://localhost:8389/solr");
            solrServer.shutdown();
        }
        System.out.println((double)(System.currentTimeMillis()-pre)/5000);
+++++++++++++++++
On my desktop computer which has a i5-3470 CUP (3.20GHz), the output is 0.206. So create a new SolrServer for each request is too expensive.

Yes, I'm very glad to contribute the dataverse. ^_^

**Comment by pdurbin** [comment]
I just merged #2713 (a pull request from @pengchengluo ) to address this issue. Thanks @pengchengluo ! Sending to QA.

To test this, I ran my usual scripts/database/homebrew/rebuild-and-test script to make sure I got the output I expect.

**Comment by kcondon** [comment]
OK, search still works: basic, advanced, facets, index all.
