### ISSUE TITLE
Dataset Files - Cleanup UI for Download, Edit, Restrict, etc. Actions With No Files Selected

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#2708]
The following actions from the dataset page have a warning popup that was missing punctuation in the message. I also added styling for a warning message, and a warning icon, plus a "Close" button.

- [x] Download
- [x] Request Access
- [x] Delete
- [x] Edit Metadata

<img width="990" alt="screen shot 2015-10-29 at 10 56 03 am" src="https://cloud.githubusercontent.com/assets/687227/10822043/b0cbca50-7e2b-11e5-8495-78f0e00e957b.png">

**Comment by mheppler** [comment]
Added "Close" button, warning icon and styling, plus punctuation.

<img width="990" alt="screen shot 2015-10-29 at 10 57 34 am" src="https://cloud.githubusercontent.com/assets/687227/10822093/f1fbab8a-7e2b-11e5-8293-607ab38b6bbc.png">

**Comment by kcondon** [comment]
Works, closing.
