### ISSUE TITLE
Request Access: Edge case where request access button does not appear using custom role for unpublished, restricted file.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2711]
See test case 3 at: #2648 

Request Access: Button does not appear for file, does not become disable when pressed for unpublished, restricted file where user has special view unpublished dataset only perm.

Using an unpublished dataset with two files, one restricted, one unrestricted
Verify view unpublished dataset grants downloading unrestricted file but not restricted unpublished file, until file downloader perm is also granted. using the above test dataset and files, create a special role at the datateverse level that has only view unpublished dataset. Grant to user. Verify they can view dataset and all file access buttons appear: request access for restricted file (make sure allow request access is enabled), and download for the unrestricted file. Make sure you can download unrestricted file. Verify you can download unrestricted file and get 403 with restricted file via API.

**Comment by eaquigley** [comment]
Discussed with @kcondon and am sending this back to him to retest and see if it is still happening.

**Comment by kcondon** [comment]
Retested above test case and found it mostly works with the exception of the request access button not appearing for custom role without file download perm.

Works:
Custom role having only view unpublished dataset permission but without the file download permission (like member without file download).
 Can see unpublished dataset, can download unrestricted file, downloading all does not download restricted file, says restricted/ not allowed in manifest, downloading restricted file only with download selected button throws 403 error, not allowed.

Does not work:
request access button does not appear even though allow request access is enabled.
