### ISSUE TITLE
Update Custom Metadata for HBGDki 

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#2714]
From the User sent to me by @sbarbosadataverse :
If possible, can the controlled terminology (i.e., the drop-down list) for the “Study Registry” field be modified to include these entries (and to drop the “DOI” number entry)?    If so, then please also modify the text that appears over the two fields when the user hovers.   From “Study ID Type: ICTRP or DOI” to “Which study registry was used?“.   From “Study ID Number:   ICTRP number or DOI number”  to “ID number for the study per the registry“.
 
Also, I noticed that these fields are asterisked.   I thought it was not possible to make custom fields required?   Please make these two fields optional.  [Eleni: Will make these optional in the db and they can make any of them required in the UI]
 
·         International Clinical Trials Registry Platform (ICTRP)

·         Australian New Zealand Clinical Trials Registry (ANZCTR)

·         Brazilian Clinical Trials Registry (ReBec)

·         Chinese Clinical Trial Registry (ChiCTR)

·         Clinical Research Information Service (CRiS), Republic of Korea

·         Clinical Trials Registry - India (CTRI)

·         Cuban Public Registry of Clinical Trials (RPCEC)

·         EU Clinical Trials Register (EU-CTR)

·         German Clinical Trials Register (DRKS)

·         Iranian Registry of Clinical Trials (IRCT)

·         ISRCTN

·         Japan Primary Registries Network (JPRN)

·         Pan African Clinical Trial Registry (PACTR)

·         Sri Lanka Clinical Trials Registry (SLCTR) 

·         Thai Clinical Trials Registry (TCTR) 

·         The Netherlands National Trial Register (NTR) 

·         US Clinical Trials Registry (clinicaltrials.gov)

**Comment by posixeleni** [comment]
Will need to work with either @kcondon or @scolapasta to update this in the db and have @pdurbin do a schema.xml update

**Comment by pdurbin** [comment]
I just took a quick glance at 0241b24 and I don't **think** a new Solr schema is required because what I could tell no fields were added.

**Comment by posixeleni** [comment]
@pdurbin the only things that changed are that I added new controlled
vocabulary values, changed the descriptions of the Study Registry fields
and made all fields not required.

On Wed, Nov 4, 2015 at 3:22 PM, Philip Durbin <notifications@github.com>
wrote:

> I just took a quick glance at 0241b24
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_commit_0241b2481e1d3cc20d5cea8702a84eced1afd035&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=OiTcIL_jSSCUW82Gf-OSkgnZLbG2Yt87eT87BdLiP54&m=gh43cG6rSyzI4UQo1YRwu4hzLefIwj6bmk_tnvqWngA&s=2MxOm7JzzL30KgUx4ti-LNQWBROmX9ePag7ZMMjHFtc&e=>
> and I don't *think* a new Solr schema is required because what I could
> tell no fields were added.
>
> —
> Reply to this email directly or view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_issues_2714-23issuecomment-2D153851691&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=OiTcIL_jSSCUW82Gf-OSkgnZLbG2Yt87eT87BdLiP54&m=gh43cG6rSyzI4UQo1YRwu4hzLefIwj6bmk_tnvqWngA&s=65IyxSblr8jVldklaWqft2zRH2EqCX-TsIu4n_f6HV0&e=>
> .
>



-- 

Eleni Castro
Research Coordinator, Data Curation and Outreach
IQSS, Harvard University
617-496-0703
http://www.iq.harvard.edu/people/eleni-castro
http://orcid.org/0000-0001-9767-8536


~Got Data? Check out the Dataverse Project. <http://dataverse.org/>~

**Comment by pdurbin** [comment]
@posixeleni right. As a sanity check and for due diligence I just did my normal check-if-a-new-solr-schema-is-required routine. No Solr schema.xml change is necessary, as we suspected.

**Comment by posixeleni** [comment]
@sbarbosadataverse I assigned this to @kcondon who will work with @scolapasta to get this into production.
