### ISSUE TITLE
Support MARC-XML for Export and Harvest

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#2721]
Use case from Harvard libraries and Harvard Business School to make MARC-XML metadata available for export or harvest at the dataset-level. This would be to make datasets in Dataverse searchable/discoverable in the Hollis Catalog and in OCLC Worldcat.

Need to consider this when planning out which metadata schemas we will support for an upcoming implementation phase of the Harvest feature since we have an active use case from the Harvard community. FRD: https://docs.google.com/document/d/1XZHpTyYUwyPN3FIfJhaSFg5_h-9C415mlE42Fuao38w/edit?usp=sharing

**Comment by borsna** [comment]
If you have DDI 3.1/3.2 in as an export you could use the XSLT:s in the project DDI-XSLT to produce MARC-XML:
https://github.com/MetadataTransform/ddi-xslt/tree/master/ddi-marcxml

**Comment by posixeleni** [comment]
@borsna thanks for your help. Unfortunately we do not have DDI 3.1 or 3.2 at the moment. We are still using Codebook but we may be able to reuse some of the XSLT so we may be forking the ddi-marcxml repo.

**Comment by mcrosas** [comment]
Yes, that's a good approach, which we've used in the past.

But in general, for export and harvesting from various metadata standard, we need to export to the native JSON (which contains ALL metadata fields), and then map that JSON to all XML standards we want to support. The reason to do this is not to leave out or convert wrongly some fields, which can happen when you convert from one metadata standard to another to another ...

**Comment by posixeleni** [comment]
Scholars Portal has mapped DDI to MARC and have shared with us their documentation
[marc.zip](https://github.com/IQSS/dataverse/files/279869/marc.zip)
: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/dataverse-community/iwYEwAJRmtQ/2KIaADLNAAAJ

**Comment by poikilotherm** [comment]
These days the exporter would be doable using a plugin. https://github.com/gdcc/dataverse-exporters

I am interested in an XML-RDF exporter as well, supporting exposing custom metadata, too.

**Comment by cmbz** [comment]
2024/08/26: Closing because there are alternate ways to address this functionality. @poikilotherm please reopen or create a new issue if you feel this is a must-have feature.

**Comment by cmbz** [comment]
2024/08/26: Additional note, there is a plan underway to investigate this functionality: https://github.com/IQSS/dataverse-pm/issues/309
