### ISSUE TITLE
Linking dataset to dataverse: success message is not displaying, dataset not successfully linked to dataverse

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2723]
Eleni was able to replicate that linking dataset to dataverse is not working.

**Comment by pdurbin** [comment]
The "Link Search" feature started throwing red CommandException errors as of 4.2 ( #2718 ) and I'm wondering if this issue is related. @sbarbosadataverse and @posixeleni you are saying you aren't seeing a success message but I'd be curious to know if you're seeing a red error message like in that other issue.

**Comment by posixeleni** [comment]
Neither @sbarbosadataverse or I are seeing a red error message, instead it
appears as if no action was taken.

On Wed, Nov 4, 2015 at 3:15 PM, Philip Durbin <notifications@github.com>
wrote:

> The "Link Search" feature started throwing red CommandException errors as
> of 4.2 ( #2718
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_issues_2718&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=OiTcIL_jSSCUW82Gf-OSkgnZLbG2Yt87eT87BdLiP54&m=ohvgXYlvkNP_uDqPP1DmwQoQmVzPlrY9Gh0PoWL64l8&s=2AuYOs1PCOu9OszTkAJ2jrw9nzKPa12fd80ZHFSJRyo&e=>
> ) and I'm wondering if this issue is related. @sbarbosadataverse
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sbarbosadataverse&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=OiTcIL_jSSCUW82Gf-OSkgnZLbG2Yt87eT87BdLiP54&m=ohvgXYlvkNP_uDqPP1DmwQoQmVzPlrY9Gh0PoWL64l8&s=VADcwRKaES9q-Br8JdqzEl-MmT4Wzp-_rURh7bMAWTI&e=>
> and @posixeleni
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_posixeleni&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=OiTcIL_jSSCUW82Gf-OSkgnZLbG2Yt87eT87BdLiP54&m=ohvgXYlvkNP_uDqPP1DmwQoQmVzPlrY9Gh0PoWL64l8&s=tjtiJQTDAShUbNDCQ6y_CO205atk24jUGja_NFB8KM4&e=>
> you are saying you aren't seeing a success message but I'd be curious to
> know if you're seeing a red error message like in that other issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_issues_2723-23issuecomment-2D153849983&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=OiTcIL_jSSCUW82Gf-OSkgnZLbG2Yt87eT87BdLiP54&m=ohvgXYlvkNP_uDqPP1DmwQoQmVzPlrY9Gh0PoWL64l8&s=NRevxCt_50Z8W5EpJVXOHHM2t-zyWNlkfKdYmoaer5Q&e=>
> .
>



-- 

Eleni Castro
Research Coordinator, Data Curation and Outreach
IQSS, Harvard University
617-496-0703
http://www.iq.harvard.edu/people/eleni-castro
http://orcid.org/0000-0001-9767-8536


~Got Data? Check out the Dataverse Project. <http://dataverse.org/>~

**Comment by pdurbin** [comment]
Ok. These may be separate bugs then. Thanks @posixeleni.

We need a stacktrace for this one. @scolapasta any ideas from the stacktrace on the other issue?

**Comment by sekmiller** [comment]
I have a stacktrace.  It's pointing me to indexPermissionsOnSelfAndChildren.  Let me see what I can come up with.

**Comment by landreev** [comment]
@sekmiller : I'm looking into this now. My strategy for the page has been to get out of the readonly mode and get a new Draft version explicitly whenever  any write operation needed to be performed. 
The whole linking thing just slipped off my radar - I didn't even realize it could be done from the dataset page.

**Comment by landreev** [comment]
@sekmiller - just to make sure, we are NOT actually modifying the dataset object at all for this linking operation, are we? Just reindexing it?

**Comment by sekmiller** [comment]
That's correct, just a re-index of the dataset.

**Comment by landreev** [comment]
I took this ticket, and put it into 4.2.2 - I think it's a good candidate for inclusion into the patch (?).

**Comment by landreev** [comment]
@sekmiller : 
I believe I have fixed it, with just this:
if (readOnly) {
   // Pass a "real", non-readonly dataset the the LinkDatasetCommand: 
   dataset = datasetService.find(dataset.getId());
}
LinkDatasetCommand cmd = new LinkDatasetCommand(... , dataset);
...

So, again, the idea is that these "readonly" versions of objects should never be used for anything other than the display on the page.

A much cleaner way of doing this would/will of course be using some kind of a dataFileUI or readonlyDataFile object, or wrapper object; that can *only* be used for display. (kind of going back to what we were doing in v.3). 
That way we'll never try to EJB-merge it, or index it, etc., by mistake. I just didn't have time to do it cleanly for 4.2.1.

**Comment by landreev** [comment]
Should be working properly now.

**Comment by kcondon** [comment]
OK, am now able to link datasets and dataverses. Closing.
