### ISSUE TITLE
Code style: meaningful strings should be constants, but aren't

### ISSUE THREAD

**Issue by bencomp** [IQSS/dataverse#2724]
As @pdurbin notes in [#2720 (comment)](https://github.com/IQSS/dataverse/issues/2720#issuecomment-153850880), the file extension ".tab" is hardcoded in many places (and therefore changing it is non-trivial).
There are many more important strings in the Dataverse code that suffer from this. For example, URI paths and query parameters, special metadata block names ("citation") with property names ("title") and many more.

Special strings should be defined as public constants and they should be used throughout the code.

**Comment by pdurbin** [comment]
I implemented this in 6535d9d and am closing this issue in favor of #3418.
