### ISSUE TITLE
DatasetPage - retest search in the files tab

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#2725]
OK, I'm opening a QA ticket just for this. It's a minor issue, but we'll likely want it in that 4.2.2 patch: 
Please retest that you can still search on files in Draft versions. 
It should still be doing the same thing; but in one pass instead of some multiple lookups happening in the service bean. That was

https://github.com/IQSS/dataverse/commit/a690fa4872ff61da7c67ce007952979feb004a49

**Comment by kcondon** [comment]
This works but due to the limitations of the current db implementation, until we use Solr, the (sub)string is literal.
