### ISSUE TITLE
Rdata download: downloading data in Rdata format throws 503 error

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2726]
exmaple dataset.
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/26448

<img width="1901" alt="screen shot 2015-11-05 at 12 55 49 pm" src="https://cloud.githubusercontent.com/assets/8322346/10977056/cf6b7924-83bc-11e5-8e8d-8ffc42ad49b6.png">

if this is a duplicate ticket, feel free to delete. I did search for Rdata related issues and didn't find a duplicate to this.

**Comment by sbarbosadataverse** [comment]
Just tried this again today to verify it is still happening--verified. Still a bug.

**Comment by eaquigley** [comment]
This could potentially be more than just an Rdata issue; this could be happening for any large file that is downloading and times out.

@scolapasta @kcondon

**Comment by sbarbosadataverse** [comment]
This was reported again today, by a user of this data: Tennessee's STAR project.
attached error:
<img width="1752" alt="screen shot 2016-02-23 at 10 36 40 am" src="https://cloud.githubusercontent.com/assets/8322346/13256965/e3c6902a-da1a-11e5-84fd-bd89013509c9.png">

**Comment by landreev** [comment]
@sbarbosadataverse 
I'm working on this issue now, for 4.3.

**Comment by landreev** [comment]
Fixes have been checked in, into the branch 2726-download-as-rdata. 
The file from the user report, above, should now be downloading in R. And it should be working more reliably and faster for other files too. 
Going to make a pull request shortly as well.

**Comment by kcondon** [comment]
@landreev Was the problem and fix specifically for transforming to R format taking a long time or something else too? Should I test some other large tabular file as well?

**Comment by kcondon** [comment]
OK, looks good. Was able to download test file mentioned as Rdata with no issues. Closing.
