### ISSUE TITLE
Metadata: Support radio buttons for Yes / No responses

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#2727]
To make Metadata Fields with Yes or No responses more user-friendly @eaquigley suggested we put in support for radio buttons.

This is how they currently look in the UI:

![image](https://cloud.githubusercontent.com/assets/5013837/10980635/2c50f3a8-83d1-11e5-8ae1-85d1599278fd.png)

**Comment by pdurbin** [comment]
Related:

- #7961

**Comment by pdurbin** [comment]
Closing in favor of this one:

- #7961
