### ISSUE TITLE
Upgrade to PrimeFaces 5

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#2730]
Dataverse 4 is using PrimeFaces 4.0 but we are planning to upgrade: https://github.com/primefaces/primefaces/wiki/Migration-Guide

**Comment by mheppler** [comment]
Cleaned up minor layout issue with the col widths of the files table on the dataset pg.

In the [PrimeFaces 5.1 release notes](http://blog.primefaces.org/?p=3302), there is a reference to "improved scrollable datatable implementation". I believe it was those improvements/changes, that caused the CSS/UI issues I found.

**Comment by mheppler** [comment]
Outline of code changes required for upgrading to 5.3.
- [x] Moved disabledSelection logic from column to table (assignedRoles/permissions-manage-files.xhtml) 8768e05fa3a0bff256d2a5fde902a8c1167ca1b7
- [x] Changed widgetVar reference format in popups () 8768e05fa3a0bff256d2a5fde902a8c1167ca1b7
- [x] CSS
- [ ] sortBy

**Comment by sekmiller** [comment]
Passing to Leonid for updating push context

**Comment by landreev** [comment]
Just moved #2758 into QA. That appears to be the last sub-issue here, so moving this ticket into QA as well.

**Comment by kcondon** [comment]
Ingest is working now, closing.
