### ISSUE TITLE
Technology Upgrade (PF 5.3, JDK 1.8)

### ISSUE THREAD

**Issue by sekmiller** [IQSS/dataverse#2731]
We are considering the following technology upgrades, to be regression tested together:

- [x] Upgrade from Primefaces 4 to 5.3 #2730
- [x] Upgrade from Java 7 to Java 8 #2151

- Upgrade Glassfish to 4.1.1 #2628 (deferred)

**Comment by sekmiller** [comment]
per http://forum.primefaces.org/viewtopic.php?f=3&t=38042 

I moved this:

disabledSelection="#{!roleAssignment.definitionPoint.instanceofDataFile}"

from the column of the view remove dialog / data table assignedRoles to the table definition.

This is in the permissions-manage-files.xhtml file.  Special care needs to be taken when testing manage permissions roles for files.

**Comment by pdurbin** [comment]
The 4.2.3 branch (as of 808f81b anyway) contains the Java 8 upgrade (#2151) and the Primefaces 5.x upgrade (#2730).

It's looking like the Glassfish 4.1.1 upgrade (#2628) isn't going to make it into 4.2.3 due to the blockers in that issue.

**Comment by scolapasta** [comment]
Moving to QA (but removing glassfish from title, as that is not for 4.2.3 and tracked separately in #2628)

**Comment by kcondon** [comment]
This was tested and individual tickets opened. Closing
