### ISSUE TITLE
Files tab: For download, original file format (UNKNOWN) for a newly ingest Stata file.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2735]
When I download 50by1000.dta in original file format, it says format UNKNOWN in the select list.

**Comment by landreev** [comment]
May not be limited to newly ingested...
I should be able to fix this in 4.2.2. 
But, going forward, I suggest we only add more issues to 4.2.2 if they are critical to performance/otherwise urgent. 
cc-ing @scolapasta

**Comment by landreev** [comment]
Please re-test, as of next build.

**Comment by sbarbosadataverse** [comment]
@landreev  This was also a problem I submitted in another ticket for .por files in Murray datasets

**Comment by landreev** [comment]
Yes, it was the same problem. I'll mark that ticket as a duplicate.

**Comment by kcondon** [comment]
OK works now for both newly ingested and existing files. Closing.

**Comment by sbarbosadataverse** [comment]
@landreev ok. but the file in my case is an excel file, not a stata file. or an spss file. just an FYI

**Comment by landreev** [comment]
@sbarbosadataverse - correct, it was showing as "unknown" for all formats.
