### ISSUE TITLE
What's the difference between two ways of creating roles?

### ISSUE THREAD

**Issue by leeper** [IQSS/dataverse#2737]
In the [Native API docs](http://guides.dataverse.org/en/4.1/api/native-api.html), there appear to be two ways to create roles.

One, listed under Dataverses is:

> Creates a new role under dataverse id. Needs a json file with the role description:
> `POST http://$SERVER/api/dataverses/$id/roles?key=$apiKey`

The other under Roles is:

> Creates a new role in dataverse object whose Id is dataverseIdtf (that’s an id/alias):
> `POST http://$SERVER/api/roles?dvo=$dataverseIdtf&key=$apiKey`

What's the difference?

**Comment by pdurbin** [comment]
Hmm. I can dive into the code as some point but for now let me ping @michbarsinai

**Comment by michbarsinai** [comment]
At the moment there's no difference. The `roles` endpoint might be used later for roles that have no dataverse associated with them, but at the moment we don't support this.

**Comment by leeper** [comment]
Perfect. Thanks, @michbarsinai!
