### ISSUE TITLE
504 gateway Time-out error When Clicking on Map Data

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#2741]
User reported this issue when clicking on their shape files to Map Data button it spins for a minute or two and then displays a 504 gateway Time-out error instead of taking you to WorldMap.

![image](https://cloud.githubusercontent.com/assets/5013837/11189718/7fbe529c-8c5f-11e5-8e38-4281fe94bce8.png)

**Comment by raprasad** [comment]
fyi: under active scrutiny.  Working with CGA to mitigate.  Related to multiple factors/active development.

**Comment by raprasad** [comment]
Fixed with longer time-outs on the CGA side (5 minutes) + user messaging on the Geoconnect side
