### ISSUE TITLE
Minor UI Performance Optimization Fixes

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#2742]
Running list of minor UI optimization improvements made across the site to improve page loading performance. (Notes for QA are in parenthesis.)

- [x] **Use the ".min" version of the Bootstrap CSS** (this change would effect the button icons we commonly use across the site, so if something is wrong with that file, that's one of the places you'll see a problem)
- [x] **Use "defer" attribute for script files** (the Sharrre plugin for socially sharing pages in our app is powered by one of these script files, so if you are not prompted with Facebook and Twitter popups from the Share popup, then this change might have caused a problem)
- [x] **Use plain HTML or generic JSF components if a PrimeFaces component is not needed** (this change was implemented on the results table, as well as the layout container for the search input and button on the search-include-fragment used by the dataverse pg)

And, this isn't performance related, but a minor layout tweek from an overlooked render logic perspective.

- [x] Hide search input, button and Advanced Search link, as well as the Add Data button when Solr is down (since there was already some layout tweeks happening on the page, I threw this in as well)

**Comment by kcondon** [comment]
OK, checked the above list and all seems to be working. Closing.
