### ISSUE TITLE
Permissions: Removing role "Success" notification incorrectly displays in "Assign Role" dialogue

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2745]
When removing a role, the blue spinner and success message shows up on the screen. You then navigate to the "Assign role" dailogue box, and while in the midst of adding a new role for a user, you see another "success" message show up in the "assign role" dialogue box, repeating the first success message of "user role removed" and this of course interrupts the process of adding the new user.

won't attach screen shot for security purposes. I have a copy on my desktop

**Comment by eaquigley** [comment]
@sbarbosadataverse I tried recreating this today and I couldn't get it to happen on demo.dataverse.org. can i pass this to @kcondon to try and if it isn't happening, close? i'm wondering if this was one of those things that happened when the servers were acting up.

**Comment by sbarbosadataverse** [comment]
Depends when the server was acting up. This wasn't that far back. I've
noticed lingering dialogue boxes as recent as this week.

On Wed, Dec 16, 2015 at 10:32 AM, Elizabeth Quigley <
notifications@github.com> wrote:

> @sbarbosadataverse
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sbarbosadataverse&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=wP7w3PhCpX3pNbO2ZAtDJ84BiS4FEjOM8dj8DnYp3BU&s=zY_UYndVI4LLBP-8c_6aQibOssNhRkg3ROLBfWVARts&e=>
> I tried recreating this today and I couldn't get it to happen on
> demo.dataverse.org. can i pass this to @kcondon
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_kcondon&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=wP7w3PhCpX3pNbO2ZAtDJ84BiS4FEjOM8dj8DnYp3BU&s=ElVFvPe5eCMIVGxktXqBpgqjuWZqdP_gcwSeiGngj7s&e=>
> to try and if it isn't happening, close? i'm wondering if this was one of
> those things that happened when the servers were acting up.
>
> —
> Reply to this email directly or view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_issues_2745-23issuecomment-2D165144344&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=wP7w3PhCpX3pNbO2ZAtDJ84BiS4FEjOM8dj8DnYp3BU&s=ZVJdEHdb1X7M4IHhSDJssZ_cShX_ucH1KxFrGjf83xY&e=>
> .
>



-- 
Sonia Barbosa
Manager of Data Curation, IQSS Dataverse Network
Manager of the Murray Research Archive, IQSS
Data Science
Harvard University

Dataverse 4.0 is now available for use!
http://dataverse.harvard.edu

All test dataverses should be created  in 4.0 Demo!
http://dataverse-demo.iq.harvard.edu/

Join our Dataverse Community!
https://groups.google.com/forum/#!forum/dataverse-community

**Comment by pdurbin** [comment]
I suspect the blue spinner is seen only briefly as of 4.2.3 since I made the expensive part of changing roles asynchronous as part of #2036.

I'd suggest we re-test this issue. I guess I'll assign it to @sbarbosadataverse but @kcondon or @scolapasta or @eaquigley or @mheppler can let me know if the process should be different. Not sure if I should set a milestone or not.

**Comment by mheppler** [comment]
No need for a milestone. Save that label for development on features and bug fixes that are going to be merged into "develop". With this issue, we're still in the triage phase of trying to determine if this is still a bug and if it can be closed or needs to be fixed still.

I have tested this locally on a post-4.2.3 branch off develop and couldn't reproduce after a few tries. I believe our permissions-related performance improvements have resolved this. Unless this is a success/validation issue with the popup messages getting signals crossed page messages, which can still be fixed.

**Comment by sbarbosadataverse** [comment]
since this happened in production, no need to assign it to me to test. If it happens again, I will create a new ticket.
