### ISSUE TITLE
Guides - Missing Navbar Links in Header

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#2750]
As originally noted by @eaquigley at https://trello.com/c/aKUM82XA/11-navigation-consistent-for-guides-dataverse-org-best-practices-dataverse-org-and-dataverse-org ever since we switched from the [Django version](https://github.com/IQSS/dataverse.org) of http://dataverse.org to OpenScholar in late September the header at http://guides.dataverse.org has been missing.

Firebug indicates that's the page is failing to fetch URLs like http://dataverse.org/nav-only-json/?callback=jsonp1447942170901 which used to exist in the Django site:

![screen shot 2015-10-28 at 10 39 35 am](https://cloud.githubusercontent.com/assets/21006/11272736/14052fae-8e9d-11e5-9017-dfb9e4a32a49.png)

@raprasad and @mheppler originally set this up so I'm going to give it to one of them for investigation for now.

I should note that http://best-practices.dataverse.org and http://community.dataverse.org suffer from the same issue for the same reason. That code is in a different repo however: https://github.com/IQSS/dataverse.org/tree/master/docs

**Comment by pdurbin** [comment]
Actually, it sounds like we're moving to readthedocs ( https://trello.com/b/NPAE4dNU/user-guides-dataverse ) so this will probably become a non-issue.

**Comment by mheppler** [comment]
The guides should have the same navbar links that are found on the (Dataverse Project)[http://dataverse.org/] site.

![screen shot 2015-11-30 at 3 34 22 pm](https://cloud.githubusercontent.com/assets/687227/11483715/002fe85a-9778-11e5-90f3-96787503f5bd.png)

**Comment by mheppler** [comment]
Replaced dynamic guide navbar solution for the guides with a static version to fix missing links.

![screen shot 2015-11-30 at 5 00 03 pm](https://cloud.githubusercontent.com/assets/687227/11486939/25141dd2-978a-11e5-99c5-e965155cafe8.png)

**Comment by kcondon** [comment]
OK, tested, works, closing.
