### ISSUE TITLE
"Original file format Unknown": when attempting to download tabular file that was originally spss portable file 

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2751]
<img width="1305" alt="screen shot 2015-11-19 at 3 50 10 pm" src="https://cloud.githubusercontent.com/assets/8322346/11283997/723f6106-8ed5-11e5-88e6-6d4ddee0847e.png">

If you select "unknown format" for download,, you get this error

<img width="1738" alt="screen shot 2015-11-19 at 3 55 40 pm" src="https://cloud.githubusercontent.com/assets/8322346/11284115/18bfde52-8ed6-11e5-9623-b9b7b5ea53ab.png">

**Comment by kcondon** [comment]
@sbarbosadataverse This is fixed in v4.2.2, to be deployed today and fixed in another ticket, #2735 , as part of the v4.2.2 release. Closing.
