### ISSUE TITLE
Guestbook: Entering more text in any textbox field, custom or not, fails to write to db but still downloads file.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2752]
Tested against v4.22 on internal.

Using a guestbook with default fields enabled (name, etc) and one custom question of text type, user can put more than 255 characters in any text field and it will complete the transaction and download the file but fail to write to the db, both guestbookresponse table and customquestionresponse tables.

**Comment by sekmiller** [comment]
After discussion with Liz, the approach we are going to take is to change the datafield type for custom question responses to "TEXT" to allow for longer responses.  For the remaining fields (Name, Position, etc.) the user will be warned if they enter more than 255 characters and be allowed to modify and re-try.

**Comment by sekmiller** [comment]
Fix for this has been pushed to the 4.2.2 branch. Another build required before testing may occur.

**Comment by kcondon** [comment]
Must add this to db update script:
ALTER TABLE customquestionresponse
    ALTER COLUMN response TYPE text;

**Comment by kcondon** [comment]
Looks good, closing.
