### ISSUE TITLE
Dataverse: Uncheck "use metadata from root dataverse" does not save, can't re-edit block fields after create dv.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2757]
When first creating a dataverse, if you uncheck "use metadata from root dataverse" make some field access changes in the citation block, save, when you edit dataverse again, the use metadata from root is still checked and now cannot uncheck nor edit field access levels.

**Comment by mheppler** [comment]
Related to #2775

**Comment by kcondon** [comment]
The checkbox works but the view states cannot be saved. Passing back to fix the view states.

**Comment by sekmiller** [comment]
Editing and updating dataset field input levels is fixed.  New build required for testing.

**Comment by kcondon** [comment]
Works, closing
