### ISSUE TITLE
Permissions: Watermark for adding users is cut off when editing an existing group definition or adding permissions

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2759]
Edit an existing group. Watermark says, "Edit User/Group Nan" on build but no watermark exists for internal (4.2.2).

**Comment by kcondon** [comment]
This also happens on the permissions page, assign user to a role select box.

**Comment by mheppler** [comment]
This was fixed with the commit 246e64389f353bce36b860b67acb83e759dbbcdc for work done on the permissions pg in #2765.

**Comment by kcondon** [comment]
Still happens even after shift reload.

**Comment by mheppler** [comment]
My original check in only resized one part of the autocomplete component, so I have fixed the CSS to adjust the width for all pieces needed to resolve this issue.

**Comment by kcondon** [comment]
OK, works now. Closing.
