### ISSUE TITLE
Dataset Terms: Cannot preview or save a guestbook from terms tab.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2760]
Create a guestbook, edit terms on a dataset, click preview, nothing happens, click save, see whiteout screen and not saved. Works in v4.2.2. Using FF.

**Comment by sekmiller** [comment]
Fixed and checked in - new build required prior to testing.

**Comment by kcondon** [comment]
Now now guestbooks appear on dataset terms tab.

**Comment by sekmiller** [comment]
Went over the functionality w/Kevin.  Appears to be working as expected.

**Comment by kcondon** [comment]
Works, closing
