### ISSUE TITLE
Permissions: Cancel button does nothing.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2761]
Cancel button on assign roles popup does nothing. Works in 4.2.2
Also cancel on create role does nothing.

**Comment by mheppler** [comment]
- [ ] Dataverse Permissions > Assign Role > Cancel

**Comment by mheppler** [comment]
Fixed broken cancel buttons on Permissions pg that were missing the new PrimeFaces 5 hide onclick formatting.

**Comment by mheppler** [comment]
Related #2762 #2763 #2764

**Comment by kcondon** [comment]
Works now, closing.
