### ISSUE TITLE
Permissions: Save button on create role works but popup stays in place, page updated in background.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2762]
When creating a role the popup stays in place with success message and new role on page behind whitened background.

**Comment by mheppler** [comment]
This was fixed with 6b98f34e93f9cd934b9c38855bf1e771ac64810f for work done on permissions page for #2761 #2764.

**Comment by mheppler** [comment]
Related #2761 #2763 #2764

**Comment by kcondon** [comment]
Works, closing
