### ISSUE TITLE
Permissions: Edit and copy role icons do nothing.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2763]
Edit and copy icons next to role names do nothing, they worked in v4.2.2. Need a new role for edit to appear.

**Comment by mheppler** [comment]
Tested this locally in both Firefox (42.0) and Chrome (46.0) and could not replicate it. Sending it back to QA. This may have been fixed due to changes made in commits for #2764 or #2761.

**Comment by mheppler** [comment]
Related #2761 #2762 #2764

**Comment by kcondon** [comment]
No longer happening. Closing.
