### ISSUE TITLE
Permissions: Save assigned role works but leaves popup in place until page refresh.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2764]
Save assigned role does not clear popup and return user to permissions page. Needs refresh of page to work.

**Comment by mheppler** [comment]
Fixed broken save button on Permissions pg that was missing the new PrimeFaces 5 hide onclick formatting.

**Comment by mheppler** [comment]
Related #2761 #2762 #2763

**Comment by kcondon** [comment]
Works, closing
