### ISSUE TITLE
Permissions: Watermark for assigning user to file permissions says, "???dataverse.permiss

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2765]
Incorrect watermark for files permissions select user. It shows an error and is truncated.

**Comment by mheppler** [comment]
Fixed broken placeholder text for File Permissions page.

Message text was broken due to a typo in the xhtml for the bundle message. Overwrote PrimeFaces CSS to resolve truncating of placeholder text within the input.

**Comment by kcondon** [comment]
Works, closing.
