### ISSUE TITLE
Concatenate and Minify CSS/JS

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#2766]
(fyi: this is a clear performance issue)

Use grunt to concat and minify the _non-primefaces_ js and css:

http://stackoverflow.com/questions/13713273/how-to-concatenate-and-minify-multiple-css-and-javascript-files-with-grunt-js-0

https://egghead.io/lessons/grunt-minifying-your-output-with-grunt-uglify

\cc @mheppler

**Comment by pdurbin** [comment]
Not a bad idea but no one is championing this issue. Closing.
