### ISSUE TITLE
Saved Search: If creator of link loses published dv permission, update link api call fails.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2770]
See issue #2718 . 

The saved search logic requires currently requires a super user to create the link and gets updated for new content by running the saved search makelinks command as that user, requiring no key. 

This works fine except for when that user no longer has publish dv perms as would be the case if ownership is transferred to local users or that person leaves the organization. In those cases, running the makelinks command fails and saved search results may grow stale until the creator field of the saved search in question is updated to be another user with publish dv perm.

**Comment by pdurbin** [comment]
Right. The workaround in this scenario is to update the "creatorId" in the saved search ("1" in the example below) to the id of an authenticated user who does have the "PublishDataverse" permission on the definition point (the "trees" dataverse, in the example below):

```
{
  "status": "OK",
  "data": {
    "saved searches": [
      {
        "query": "darwin",
        "filterQueries": [
          "dvObjectType:(dataverses OR datasets OR files)",
          "subtreePaths:\"/2/3\""
        ],
        "id": 1,
        "definitionPointId": 7,
        "definitionPointAlias": "trees",
        "creatorId": 1
      }
    ]
  }
}
```

See also #2543 where we'd like to move away from cron altogether and have an EJB timer control when the "make links" logic is executed periodically.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
