### ISSUE TITLE
Deaccession: Deaccession option missing from tech update branch.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2772]
This is probably expected since tech branch was created before deaccessioning was fixed but this is a placeholder to verify this gets fixed in tech branch.

**Comment by pdurbin** [comment]
Just capturing the commit this was tested on: b5a3ca2

It does sound like the fix for #2732 (a2fad92) hasn't been merged into the 2731-techupdate branch yet.

@landreev plans to merge the latest there from the 4.2.2 branch when he's done.

**Comment by sekmiller** [comment]
Getting the jump on the merge.  Hopefully this will save Leonid one small step.

**Comment by kcondon** [comment]
OK works, closing
