### ISSUE TITLE
Download File: Accept Terms of Access button on popup results in file download but popup remains in screen.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2773]
The accept in the TOA popup works in that the file download completes but the popup remains onscreen as if nothing happened.

**Comment by mheppler** [comment]
@sekmiller -- looked into this, and didn't see any obvious problem regarding the new PrimeFaces 5 formatting of hide/show commands for popups.

**Comment by sekmiller** [comment]
Issue was with the scrollTo in error handling.

**Comment by sekmiller** [comment]
Code for the fix has been checked in...

**Comment by kcondon** [comment]
This is still happening. Did the code get checked in?

**Comment by sekmiller** [comment]
Sorry - it was a mistake on my part to send this to QA.  I confused it with an edit dataverse ticket. not sure why.  is it Friday yet.

**Comment by sekmiller** [comment]
This time it really is fixed sorry about yesterday's mixup.

**Comment by kcondon** [comment]
Works, closing

**Comment by kcondon** [comment]
Works, closing
