### ISSUE TITLE
Dataverse Page/Search Include Fragment: optimize handling of thumbnails.

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#2776]
The code that retrieves and displays thumbnails in  the search fragment is inefficient. 
A couple hundred queries (or more) could be easily saved on an average page load, by using better strategies and custom queries.

(fyi:  There is some overlap with #2475)

**Comment by landreev** [comment]
OK, let's refresh the database that vm5 is using.
We'll need to 
a) run the db update script;
b) I'll need to copy the files for 10 or so pages worth of datasets, in order to be able to QA thumbnails properly.

**Comment by kcondon** [comment]
OK, thumbnails are still working and page is much faster. Will perform some benchmarks.

**Comment by kcondon** [comment]
Tested with thumbnails in root dv homepage, see benchmarks in #2777 . Closing
