### ISSUE TITLE
Optimize Dataverse page, to issue fewer queries and load faster.

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#2777]
Dataverse page still issues 1,200+ queries to load the default home page in production.
Custom/native queries can be used to speed things up. (Raman already worked out some solutions for the mydata page).
Also, an important subtask of this is #2776 - optimizing handling of thumbnails. This alone generates a surprising number of database requests; hence it has a dedicated ticket of its own.

fyi: Card attribute list can be found under "Next Steps": https://github.com/IQSS/dataverse/issues/2474

**Comment by raprasad** [comment]
fyi:  There is overlap with #2475

**Comment by landreev** [comment]
I can see 2 areas of QA process for this issue:

1. regression - compare the functionality to the 4.2.1;
2. performance. verify savings in the # of queries against 4.2.1? stress test, compare to 4.2.1?

for best results the same db should be used.
I also have a preserved version of a 4.2.2 war file, built before my dataverse page fixes were added.

**Comment by landreev** [comment]
(a new build is needed; i've already made a commit today)

**Comment by landreev** [comment]
OK, there are following known limitations/things that may be messed up:
- no "linked" icon;
- extra info for tabular files may not be shown;
- harvested cards - not sure if displayed correctly.
- mydata (and potentially any other components using SearchServiceBean) are not available...

But it is fast!! lol

I have solutions for these things; will wire them on Friday. Really had to leave today.
Anything else you find - please add.

**Comment by kcondon** [comment]
Also missing from the harvest card a note at the bottom that reads:
 This dataset is harvested from our partners at the ICPSR at the University of Michigan. Clicking the link will take you directly to the archival source of the data.

**Comment by kcondon** [comment]
For tabular data, for comparison on what is missing, for the same file:

production:
Tabular Data - 228.3 KB - 1559 Variables, 77 Observations - UNF: UNF:5:OJzZAAxyY+KzHZUBuzGj1A==

4.2.2:
Tab-Delimited - 228.3 KB - MD5:

**Comment by mheppler** [comment]
I am going to take the list of to-do items from both Leonid's comment and Kevin's comment, and combined them here. Please add additional items here, for one easy to read checklist, rather than a running dialog of new comments.

-  [ ] no "linked" icon
-  [ ] extra info for tabular files may not be shown;
-  [ ] harvested cards - not sure if displayed correctly.
-  [ ] mydata (and potentially any other components using SearchServiceBean) are not available...
-  [ ] "This dataset is harvested from our partners at the ICPSR at the University of Michigan. Clicking the link will take you directly to the archival source of the data."

**Comment by kcondon** [comment]
Benchmark summary:
Both 4.2.1 and 4.2.2 had the same max load: 240 concurrent users but the response time at the maximum and the growth in response time under load varied considerably: 4.2.1 sharply increased, 4.2.2 stayed relatively flat.
Query count summary:
4.2.2 query counts were a factor of 10 less than 4.2.1:
4.2.2 was roughly 280 for the homepage, 250 for the files facet and 4.2.1 was 3500 for the homepage, 7200 for the files facet.

**Comment by kcondon** [comment]
Benchmark
4.2.1
Users Resp (ms) / Resp (ms) File Facet Total requests RPS Fail Max Mem CPU
5         1689            3187                          99                   0.4    0    6.5GB       4.7%
100     2811            8228                          518                 6       0    7.2GB       50%
200   16665          56335                          518                 5.5    0    10GB        60%
240   22538          73538                          625                 5       0    10GB        64%

4.2.2
Users Resp (ms) / Resp (ms) File Facet Total requests RPS Fail Max Mem CPU
5         728              906                            100                 0.5
100     572              604                            500                 7.5
200     651              688                           1000                13
240     

Query Count
4.2.1
User Status       /          File Facet
Not logged in    3586    7695
dvAdmin           3306     6196

4.2.2
User Status       /          File Facet
Not logged in    283      246
dvAdmin           326      283

**Comment by mheppler** [comment]
:dizzy_face:

**Comment by landreev** [comment]
Tabular data files: cards should now have proper display of UNF, var counts, etc.

**Comment by kcondon** [comment]
my data and tabular data file cards now ok.

**Comment by landreev** [comment]
Cards for harvested dataverses and datasets should be properly formatted now.

**Comment by landreev** [comment]
Cards for harvested files should also be properly formatted now.

**Comment by landreev** [comment]
Linked objects - should now be displayed properly.

**Comment by landreev** [comment]
File categories - should now be displayed in the file card.

**Comment by landreev** [comment]
Per @mheppler 's list of TODO items:

To the best of my knowledge, all the issue have been resolved.
With the single exception being the tabular data tags. I can easily retrieve them (at the cost of one extra db query per page); however, I feel we should just start indexing these things - same way we are already indexing file categories. This way they'll be available from SOLR, with no need to retrieve them from the db on page load... 
I'll bring this up at the meeting in the AM - whether it's ok to add extra indexable fields at this point.
And I will fix it, one way or another, after the meeting.

**Comment by pdurbin** [comment]
> tabular data tags. I can easily retrieve them (at the cost of one extra db query per page); however, I feel we should just start indexing these things - same way we are already indexing file categories.

A few things.

- It's confusing to me that we use the term "tags" so much (I think this deserves its own issue):
  - File categories (already indexed) show up under as the "File Tag" facet in the GUI (the Solr field is "fileTag").
  - The proposal above is to index "Tabular Data Tags". Their not currently being indexed was noted by @kcondon at https://github.com/IQSS/dataverse/issues/2466#issuecomment-144124060
  - At some point we need to integrate with "DataTags" ("Share Sensitive Data with Confidence" per http://datatags.org ) in #871 
- As far as I know, all this tagging is a GUI-only operation. It's not possible to do via API. This makes it more challenging to test.

Here's how the current "File Tag" facet ("categories" in the code looks in production as of v. 4.2.1):

![harvard_dataverse_-_2015-12-07_09 10 14](https://cloud.githubusercontent.com/assets/21006/11628868/96d742c2-9cc2-11e5-8dfe-2dac2dd830a5.png)

Here's how you can edit "File Tags" vs "Tabular File Tags":

![spruce_goose_-_spruce_dataverse_-_2015-12-07_09 23 22](https://cloud.githubusercontent.com/assets/21006/11629130/48e20b7c-9cc4-11e5-85c9-6177acc8243f.png)

Here's the DataTags homepage/branding:

![datatags_-_2015-12-07_09 29 11](https://cloud.githubusercontent.com/assets/21006/11629256/0f2cb7c8-9cc5-11e5-957e-4b41ffade680.png)

I don't have any objection to indexing Tabular Data Tags in principle but I want us to think about the use of the word "tags". It feels overloaded to me already, and we haven't integrated DataTags yet (#871). /cc @mcrosas @eaquigley

**Comment by kcondon** [comment]
@landreev  Citation is missing from harvested datasets:
Production:
ICPSR, 2014, "Toward a Healthy America: Selected Research Data from the Health and Medical Care Archive at ICPSR", http://hdl.handle.net/1902.29/CD-11511
4.2.2:
blank but with a thin blue line which would be the background color of the citation.

**Comment by landreev** [comment]
Just an  info update:
We realized today the 4.2.1 query-counting test, above, was done with a pre-production build of 4.2.1.
But I re-ran the tests today, with the final, production 4.2.1 build - and the numbers are virtually the same. (they don't have to be exactly the same, because some datasets have been reindexed since last week - so the data objects loaded on the home page are not the same).
This makes sense, because the dataverse page wasn't touched much in 4.2.1; but some changes were made to it (the number of the Setting table lookups must have been reduced); so we weren't sure.

So yeah, 10:1 reduction or better, in query numbers...

**Comment by pdurbin** [comment]
> All that's left for this ticket is tabular data tags, opened as a separate ticket.

That issue is #2802
