### ISSUE TITLE
Dataverse - Fake (Not Logged In) "Add Data" Sign Up/Log In Popup Buttons Broken

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#2779]
When accessing the dataverse pg, while not logged in, a placeholder "Add Data" button is displayed on the page, that brings up a Sign Up/Log In popup. This popup is not being displayed when the Add Data button is clicked.

**Comment by mheppler** [comment]
Fixed broken Add Data Sign Up/Log In popup and cancel button.

**Comment by kcondon** [comment]
Works now, closing.
