### ISSUE TITLE
PublishDatasetCommand: same error appears three times, should be unique

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#2780]
The error "This dataset may not be published because it has not been registered. Please contact thedata.org for assistance" appears three times in the PublishDatasetCommand (as of 4a3e7b2) making it difficult for me to diagnose the problem reported by @Grimaldum at http://irclog.iq.harvard.edu/dataverse/2015-11-30#i_27476

The messages should vary slightly so we can tell which "else" the code has fallen into. These messages are user-facing so more detailed logging could be added as well.

**Comment by posixeleni** [comment]
This also should not say "contact thedata.org for assistance" since this is a site we no longer use but rather something more like "Harvard Dataverse Support"

**Comment by pdurbin** [comment]
Well, not "Harvard Dataverse Support" because other institutions besides Harvard run Dataverse. But yes, I agree that we should no longer reference that legacy thedata.org URL.

**Comment by posixeleni** [comment]
"Dataverse Support"

**Comment by sekmiller** [comment]
Suggested changes to the error messages have been made and checked into 4.2.3 branch.

**Comment by pdurbin** [comment]
As of f339074 the messages now vary slightly (thanks @sekmiller !) so I'm sending this to QA at https://waffle.io/IQSS/dataverse . That commit was part of 4.2.3 so I'll add that milestone to this issue.

**Comment by sekmiller** [comment]
The one comment I would make is that we need to be careful of how the generalization of DOI service providers and the introduction of Handle support is integrated here.

**Comment by kcondon** [comment]
Closing based on feedback from person who initially reported the issue.
