### ISSUE TITLE
Permissions: Edit Dataset, Permissions, Dataset/File select displays off screen if browser small.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2785]
The child select box for Edit Dataset->Permissions->Dataset or File, always displays to the right in v4.2.3, even when the browser width is small, resulting in those options displaying partly off screen and scroll bars appearing. This does not happen in v4.2.2, the dataset/file select box appears to the left instead.

**Comment by mheppler** [comment]
The right-side dropdown/flyout submenus is something that was fixed in 4.2.2, as originally reported in #2736. That same fix was also applied to the Edit Dataset button. The code from 4.2.2 has yet to be merged with 4.2.3. Once it is, this will no longer be an issue.

**Comment by pdurbin** [comment]
Merged! c3fc5e8

**Comment by mheppler** [comment]
With 4.2.2 and the techupdate branch having been successfully merged into a new 4.2.3 branch, I can now confirm that the menu fix is there and working as advertised.

**Comment by kcondon** [comment]
Looks good, closing
