### ISSUE TITLE
Have popup Calendar as option on Metadata Date Fields

### ISSUE THREAD

**Issue by shlake** [IQSS/dataverse#2786]
For any date field (advance search or metadata creation), allow the user to either type in a date OR have a calendar pop up to allow date choosing.

**Comment by posixeleni** [comment]
:+1:

**Comment by pdurbin** [comment]
Excellent suggestion, @shlake

**Comment by pdurbin** [comment]
@qqmyers and I discussed this yesterday. Now that we have a popup calendar for embargo (screenshot below), why not add them for additional fields?

![Screen Shot 2022-08-11 at 10 08 37 AM](https://user-images.githubusercontent.com/21006/184152918-fdf0ed24-17c1-49e6-b2e4-f6a10f9704b7.png)

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
