### ISSUE TITLE
Edit Dataset: Restricting a file on edit files tab results in TOA popup behind the white background.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2787]
The behavior varies, depending on whether you restrict the file on creating the dataset or just editing the file metadata. It works if you restrict from the view dataset mode.

1. On create dataset:
create a dataset, upload a file, restrict that file, save.
The TOA popup is completely behind the whiteout background and you cannot interact with the popup.

2. On edit file metadata:
On save, the TOA popup is half behind the whiteout background with the buttons visible and working and a > next to the cancel button.

**Comment by mheppler** [comment]
Fixed CSS for dialogs displaying behind blockUI component on both Dataset and Edit Dataset Files pgs.

In addition to the reported bug, I also found that clicking the Cancel button on these pages would leave the blockUI component displayed over the page content area. To resolve this, I have added 'PF('blockDatasetForm').hide();' to the onclick attributes for every dialog Cancel button as well as any other buttons in a dialog that uses the onclick attribute.

**Comment by kcondon** [comment]
@mheppler Thanks. So, in addition to testing the issue I should also retest every button then?

**Comment by mheppler** [comment]
I have checked most of them, but not all of them. Here are the dialog widgets that I added code to. (Double asterisk indicates that it is more than just the Cancel/Close button that new code was added to.)

dataset
- deleteConfirmation
- deleteVersionConfirmation
- deleteFileConfirmation
- deleteSelectedFileConfirmation
- deaccessionBlock
- deaccessionAllConfirmation
- compareTwo
- detailsBlocks
- selectFilesForDownload
- selectFilesForRequestAccess
- selectFilesForDelete
- selectFilesForEditMetadata
- fileTagsPopup
- accessSignUpLogIn_popup
- downloadPopup
- mapData_popup
- linkDatasetForm
- accessPopup
- inreview **
- publishConfirm **
- publishParent **
- releaseDraft **
- mayNotRelease
- maynotPublishParent
- sendBackToContributor

editFiles
- editFileAccessPopup
- fileAdvancedOptions
- fileSetThumbnail
- editFileTagsPopup

**Comment by kcondon** [comment]
Works in FF and Chrome. Will test the additional mods as part of merge regression testing. Closing.
