### ISSUE TITLE
Restrict Button to have more "Actionable" Label

### ISSUE THREAD

**Issue by shlake** [IQSS/dataverse#2789]
Suggestion to label the "Restrict" button "Set Restriction" (OK, maybe that's too long). But the comments I've been getting is that the word on the button "Restrict" seems to be the action that will be performed when clicked. My users missed the small down arrow on the side of the button where once clicked THEN they pick Restrict or Unrestrict. Testing here, our users couldn't remember how to unrestrict.

![screen shot 2015-12-01 at 3 08 13 pm](https://cloud.githubusercontent.com/assets/3809325/11512891/6a3e1458-983e-11e5-9e7e-5f72909d4085.png)

**Comment by mheppler** [comment]
@shlake + @sbarbosadataverse -- I have discussed changing the button text with @eaquigley and after reviewing what we use for button text in the Permissions workflow, we've come up with the following proposed solution (see attached) of using "Edit Access". Please let us know if you believe this solution is suitable.

![screen shot 2016-02-09 at 4 27 12 pm](https://cloud.githubusercontent.com/assets/687227/12931101/09603722-cf4a-11e5-9621-512d99982afe.png)

**Comment by shlake** [comment]
This looks good. Thanks.

**Comment by sbarbosadataverse** [comment]
sorry so late. This looks good!

On Thu, Feb 11, 2016 at 12:21 PM, Sherry Lake <notifications@github.com>
wrote:

> This looks good. Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_issues_2789-23issuecomment-2D182965368&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=AkYP6q22cKzpgPopywDf90bn4duJu3qX5lDf0yN4oxI&s=-TywJC-s59gP6egNwLYytblseuqUQ_MxZt-KsELljy0&e=>
> .
>



-- 
Sonia Barbosa
Manager of Data Curation, IQSS Dataverse Network
Manager of the Murray Research Archive, IQSS
Data Science
Harvard University

Dataverse 4.0 is now available for use!
http://dataverse.harvard.edu

All test dataverses should be created  in 4.0 Demo!
http://dataverse-demo.iq.harvard.edu/

Join our Dataverse Community!
https://groups.google.com/forum/#!forum/dataverse-community

**Comment by kcondon** [comment]
Restrict/unrestrict works, new button text in place, closing.
