### ISSUE TITLE
Themes: Image uploaded to Dataverse is not displayed on dv page or card.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2792]
Uploading an image to a dataverse using themes does not result in the image in the dataverse homepage banner and does not appear in featured dv's or dataverse cards.

**Comment by mheppler** [comment]
- Dataverse Header: Broken image URL, image alt text in it's place
- Feature Dataverse Carousel: Broken image URL, image alt text in it's place
- Dataverse Result Card: Default icon-dataverse symbol in it's place

**Comment by landreev** [comment]
I'm looking into it.

**Comment by landreev** [comment]
#2791 is unrelated.

**Comment by landreev** [comment]
OK, fixed the part where logos were not appearing in the carousel, and in the page headers.

**Comment by landreev** [comment]
#2791 is related after all - in that we still have real-time generation of *new* thumbnails disabled (on vm4 and vm5 both)! Existing ones should be showing.
so that's not a bug - just a configuration setting.

**Comment by kcondon** [comment]
Works now, closing.
