### ISSUE TITLE
Groups: select list for users appears behind whiteout background in Chrome, works in FF.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2793]
From any dataverse, edit->groups->create group
type something in user/group edit box so options appear, notice the list is dispalyed behind whiteout background.

Happens in Chrome, not FF.

**Comment by mheppler** [comment]
Fixed layering issue with autcomplete component dropdown list on the Create Group popup from the Manage Groups pg.

**Comment by kcondon** [comment]
Works, will test other mods with post merge regression testing. Closing.
