### ISSUE TITLE
Dataverse Result Cards - CSS Fixes

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#2796]
As part of the 4.2.2 merge into 4.2.3, it seems that some minor CSS changes from #2742 didn't make into the new branch. Attached is a screenshot of how it should look.

- File cards border is dark grey
- Font size on all cards is 100% and not 90%

![screen shot 2015-12-04 at 3 05 25 pm](https://cloud.githubusercontent.com/assets/687227/11600109/8c4ea75e-9a98-11e5-9e0d-2a9e7610bdd6.png)

**Comment by mheppler** [comment]
Fixed lost CSS changes to dataverse pg result cards. 756a222ba08cdd15b8557fd9d86c539eda63d1f2

**Comment by kcondon** [comment]
@mheppler Tags do not appear in v4.2.3 on the file card so can't verify this. I'll open a new ticket for this.

**Comment by kcondon** [comment]
OK, cards look as described, closing.
