### ISSUE TITLE
Dataset - Edit Files "Please select..." Message Missing

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#2797]
When you click the "Edit Files" button on the dataset pg, you are provided a dropdown with the options to Delete, Metadata, Restrict, Unrestrict, Tags. If you have no files selected, and choose Delete and Metadata, you get a message "Please select a file or files..." If you choose Restrict, Unrestrict, Tags, there is no such message -- for Unrestrict it even displays a success message.

There needs to be a "Please select a file or files..." popup and message for these workflows.

- Dataset pg Files tab > Edit Files button > Restirct
- Dataset pg Files tab > Edit Files button > Unrestirct
- Dataset pg Files tab > Edit Files button > Tags

**Comment by sekmiller** [comment]
Restrict and unrestrict messaging fixed.

**Comment by sekmiller** [comment]
Added a message for selected "Tags" with no selected files

**Comment by sekmiller** [comment]
@kcondon one more small issue to be tested.  Will need a build.

**Comment by kcondon** [comment]
@mheppler @sekmiller OK all have messages. Tags says select files to be edited. Hope that ok closing
