### ISSUE TITLE
File Tags: Tabular tags are not save on an already existing draft

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2798]
On an already existing draft version of a dataset, either unpublished or of a published dataset, saving tabular data file tags does not work. Normal file tags do.

Also, the file tags are truncated if there are a lot on the view dataset and edit files views but does not seem to be on the file card.  Opened this one as #2804

These bugs exist in v4.2.1.

**Comment by sekmiller** [comment]
@kcondon  Is this on bulk update, individual file update or both?

**Comment by kcondon** [comment]
@sekmiller It happens on the edit file metadata view, aka individual files.

**Comment by mheppler** [comment]
Related to #2391.

**Comment by mheppler** [comment]
I am assigning this issue to @sekmiller, as discussed with @scolapasta and @eaquigley. This bug will be looked into as part of the development of #2391. The scope of the File Tags UX projected is outlined in it's [FRD](https://docs.google.com/document/d/1ihQ9GiK2qVYH_tKOJSCUdNxPdOw1Ut_AXDEIiGRjQss/edit).

**Comment by mheppler** [comment]
Currently I can replicate this bug on the Edit File pg, in a local build of the "develop" branch.

User Workflow: Draft version of a published dataset, with tabular data files. Select tabular file, click "Edit Files" button, select "Metadata" from dropdown to go to Edit File pg. Click "Edit Tags" button next to tabular file. Select new tabular data tag from the dropdown. Click "Save Changes" button on the Edit Tags popup. Click "Save Changes" on the Edit Files pg. See "Success!..." msg on dataset pg, scroll down to find tabular data file missing the new tag.

**Comment by landreev** [comment]
Pushed in a fix, into the 2391-file-edit-tags branch branch. 
Moving to QA. 
(note that it doesn't have a milestone assigned).

**Comment by kcondon** [comment]
OK, seems to work though thought I saw it fail at least once (intermittent). Since I cannot work, will close and reopen if I see it again. Closing.
