### ISSUE TITLE
My Data: Card icons are incorrectly sized and positioned, regression introduced in 4.2.2.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2799]
The object type card icons that are larger and positioned to the left of the citation are now tiny and centered in the card above the citation. Should be fixed for v4.2.2.

**Comment by mheppler** [comment]
Fixed CSS issues with icon alignment and text size on MyData and dataverse pg.

**Comment by kcondon** [comment]
Fixed, closing.
