### ISSUE TITLE
Make sure citations are shown for harvested datasets, just as in 4.2.1.

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#2800]
Harvested datasets still have no indexed citations. So up until 4.2.2 we relied on some code that was "cooking" harvested citations in real time. 

So for 4.2.2 we are going to move that code into SearchServiceBean and reindex all the harvested datasets. This way we can stop treating these harvested citations as a special case on the dataverse page.

I'm opening a separate (4.3 or 4.4) issue for a longer-term solution - this is something we've been meaning to address since 4.0.

**Comment by landreev** [comment]
@kcondon 
I committed a change that makes harvested datasets show citations.
But we still need to reindex all the harvested datasets, to make sure the citations are well-formatted. 
(Most importantly, we don't want to show the handle global ids that we used to assign to nesstar studies)

**Comment by landreev** [comment]
OK, nevermind on the "need to reindex" part. All the harvested datasets in production already have properly-formatted citations indexed in solr.
So, in terms of QA, please double-check that the citations shown in search cards on vm5 are identical to what we get in production.

**Comment by kcondon** [comment]
OK, looks good. Closing.
