### ISSUE TITLE
Harvested Files: Card show 0 bytes, blank MD5

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2801]
Example:
data/various-formats - 0 bytes - MD5: 

Could maybe hide this or perhaps a note indicating file is hosted remotely.

**Comment by scolapasta** [comment]
This appears to be a duplicate of #2221. If not, could you clarify the issue in more detail. Thanks.

**Comment by kcondon** [comment]
Yes, it is a duplicate, now that it was identified as harvested. Closing.
