### ISSUE TITLE
DDI.XML file retrieved in multi-file bundle download contains 0 bytes

### ISSUE THREAD

**Issue by evelynPM** [IQSS/dataverse#2803]
A bundle retrieved through the Data Access API from https://apitest.dataverse.org/dataset.xhtml?persistentId=doi:10.5072/FK2/D3B38B included an empty DDI.XML file.

**Comment by pdurbin** [comment]
@evelynPM can you please provide an example in curl or Python for how to reproduce this?

Note to self that apitest is currently running v. 4.2.1 build 32-3164663.

**Comment by landreev** [comment]
Was the bundle generated for the file ERS_weather_data_hourly_2015-x.tab?

**Comment by evelynPM** [comment]
Yes, that bundle contained the 0 byte DDI.XML file.

**Comment by pdurbin** [comment]
@evelynPM I'm about to repurpose the "apitest" server per #3345 but I wanted to try to preserve the file that you uploaded that failed ingest. Unfortunately, that was so long ago it looks like there's nothing at https://apitest.dataverse.org/dataset.xhtml?persistentId=doi:10.5072/FK2/D3B38B anymore (404 per the screenshot below). I probably dropped the database and blew away the files, which is my habit when I would this server. If possible, can you please attach the problematic file to this GitHub issue? If you don't have the file handy, please don't worry about it. We probably have other similar files to test with. Thanks!

![screen shot 2016-10-25 at 1 07 06 pm](https://cloud.githubusercontent.com/assets/21006/19696188/232d3f2a-9ab4-11e6-83f5-fadb655fcf94.png)

**Comment by pdurbin** [comment]
@evelynPM is this still a problem for you?
