### ISSUE TITLE
Files Tab: File tags are cropped well short of width of table and shorter than file card.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2804]
This issue predates 4.2.2 but reporting it after retesting this area:
If you enable all default tags, both file category and tabular data tags for a tabular data file, all appear on the file card but are cropped at geo in geospatial on the files tab view.

**Comment by mheppler** [comment]
Fixed display issue with File Tags in the dataset files table and dataverse results cards.

**Comment by kcondon** [comment]
Works, tags wrap now, closing.
