### ISSUE TITLE
Add Date/Time and Sever for unexpected error messages

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#2805]
When people get unexpected error messages, we have a message for them to contact support. It would be useful for us to have the day/time and server on this, so that if they take a screenshot, we know exactly where in the logs to look.

**Comment by pdurbin** [comment]
Related: #2200

**Comment by kcondon** [comment]
No way to reproduce but will make sure rest of app works ok. Closing.

**Comment by pdurbin** [comment]
As I was mentioning to @scolapasta the commit at c32cd3e contains code that should show which server you are on (such as kirk vs. picard for us). #2200 is related.
