### ISSUE TITLE
Files Tab: Tabular data tags are not sorted.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2808]
Tabular data tags appear in random order: for a dataset with several tabular files, batch add tabular data tags, select all, and notice they are in different order per file. This was fixed in the file cards.

**Comment by mheppler** [comment]
Related to #2391.

**Comment by mheppler** [comment]
I am assigning this issue to @sekmiller, as discussed with @scolapasta and @eaquigley. This bug will be looked into as part of the development of #2391. The scope of the File Tags UX projected is outlined in it's [FRD](https://docs.google.com/document/d/1ihQ9GiK2qVYH_tKOJSCUdNxPdOw1Ut_AXDEIiGRjQss/edit).

**Comment by kcondon** [comment]
will retest

**Comment by kcondon** [comment]
Still happens.

**Comment by mheppler** [comment]
A new issue, **Dataset - File UI Improvements #3404**, was created to track the UI improvements related to the files view on the dataset pg. Older feature requests and bug reports like this one will be closed in favor of that new issue.
