### ISSUE TITLE
Rewrite Rules: Retest and correct URL rewrite rules

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2810]
The rewrite rules were moved from glassfish to apache and at least one rule, redirecting datasets from thedata.harvard.edu to dataverse.harvard.edu is not working: rather than resolving and redirecting handles to the appropriate datasets, they send users to the dataverse.harvard.edu home page.

**Comment by kcondon** [comment]
An example: http://hdl.handle.net/1902.1/11193
Current record: http://dvn.iq.harvard.edu/dvn/study?globalId=hdl:1902.1/11193
Resolves incorrectly to: https://dataverse.harvard.edu/?globalId=hdl:1902.1/11193
Should resolve to: https://dataverse.harvard.edu/dataset.xhtml?persistentId=hdl:1902.1/11193

Please note there is another ticket, #2809 that is the fundamental fix for these issues: update the older URLs in these handle and doi records.

**Comment by landreev** [comment]
OK, there was a problem with this rule: 

We (I) were using 

RewriteRule     ^.*globalId=(.*)        https://dataverse.harvard.edu/dataset.xhtml?persistentId=$1

- but, apparently, RewriteRule only matches on the URL (not on the URL parameters). 
So, to match the globalId parameter, the following rule needs to be used instead: 

RewriteCond     %{QUERY_STRING} globalId=(.*)
RewriteRule     ^/(.*)          https://dataverse.harvard.edu/dataset.xhtml?persistentId=%1

Updated on all 3 production systems. Restarted apache. 

This was the only rule where we were trying to pattern-match on a URL parameter. So I'm not immediately seeing any other rules that should not be working as they should be. Please update this/open another ticket if you find any others.

**Comment by landreev** [comment]
That said, it's not clear why some of our registered handles still have the old hostname registered. 
I'll need to go through them one more time and see if any need to be re-registered still. 
So I'm keeping that other ticket (#2809) in my queue .

**Comment by kcondon** [comment]
Tested, works, closing
