### ISSUE TITLE
Custom ordering of Featured Dataverses broken: should be able to order featured children 

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2813]
Custom ordering of  "featured child dataverses"  not working. Noticed this as I was using this feature today,

**Comment by landreev** [comment]
Correct, the dataverses in that carousel are not being sorted by DisplayOrder. A simple bug in the new query.

I have checked in a fix. We can decide tomorrow if we are patching the production for this, and if so - when.

@sbarbosadataverse  - could you please take a look at dvn-vm5.hmdc.harvard.edu, and confirm if that's the correct order?
My latest patch is already applied there.

**Comment by pdurbin** [comment]
It looks like the fix (422a310) is in the 4.2.2 branch so I'll set the milestone to the same.

**Comment by kcondon** [comment]
Fixed, closing.
