### ISSUE TITLE
Error Handling: Throws 500 error rather than 404 for missing or non existent dataset.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2816]
The system should throw a 404 error when a requested dataset does not exist but currently throws a 500 error. This was a regression and needs to be corrected.

**Comment by landreev** [comment]
4.2.2?

**Comment by landreev** [comment]
OK, I have a code fix for that. 
I still feel this is something we could/should delay till 4.2.3. (this is definitely something that was introduced back in 4.2.1)

**Comment by landreev** [comment]
(I'm not checking in my fix, until we decide we patching this bug in 4.2.2; discuss at the AM meeting?)

**Comment by landreev** [comment]
Fix checked in, into 4.2.2.

**Comment by kcondon** [comment]
Works, closing
