### ISSUE TITLE
Mention Vagrant in the Installation Guide

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#2817]
In January 2013 a user was having trouble running `vagrant up` on 32bit Windows: https://groups.google.com/d/msg/dataverse-community/wRxRSGE8VpQ/jO2liOkcnLsJ

Today I have been helping someone with similar trouble.

We should see what we can do with the Vagrant config to make `vagrant up` work on more platforms.

I *think* the solution could be to detect 32 bit and use a different Vagrant base box such as https://atlas.hashicorp.com/puppetlabs/boxes/centos-6.6-32-nocm but we'd need to first detect that the host operating system (Windows in this case) is running 32 bit.

Currently using a 32bit base box fails because we assume 64bit jq. Without jq you get errors like this: {"status":"ERROR","message":"Bad api key 'null'"}

**Comment by pdurbin** [comment]
Actually, for the problem in question it may be that installing a version of VirtualBox that allows for the creation of 64 bit Linux may help. Here's how it should look:

![screen shot 2015-12-10 at 1 44 18 pm](https://cloud.githubusercontent.com/assets/21006/11724800/44eacf68-9f44-11e5-841e-4a4b09c9e1ef.png)

**Comment by pameyer** [comment]
I haven't tested enough to know if it's specific to the default puppet-vagrant-boxes.puppetlabs.com-centos-65-x64-virtualbox-puppet.box; but `vagrant up` also appears to need VirtualBox 5 (VirtualBox 4.3.34 is supported by vagrant, but has networking issues for standalone.vm.box).  I'm not sure if this is something that could be checked for in vagrant or not (or how reproducible it is, for that matter).

**Comment by pdurbin** [comment]
Ok, I'm cheating a bit by removing "32bit" from the title of this issue. It's far easier for me to assume that people using Vagrant are able to boot a 64 bit Linux VM in VirtualBox.

The person I was helping yesterday actually had a 64 bit version of Windows and she found a solution at http://www.fixedbyvonnie.com/2014/11/virtualbox-showing-32-bit-guest-versions-64-bit-host-os/ which helped her diagnose the root problem: "intel virtualization technology was disabled in my computer's BIOS."

I think what I'll do from here is write up more about Vagrant in our Guides and mention troubleshooting steps like this.

@scolapasta directed this individual to me since she wanted to kick the tires on a fresh Dataverse installation using Vagrant so I assume we should add something about Vagrant to the Installation Guide. It looks like someone (probably me) already put it in the reorg proposal at https://docs.google.com/document/d/1GLky44JbtCNhGuavLXGEP8WPNdjbyHNxalEGjR78MaA/edit?usp=sharing

**Comment by pdurbin** [comment]
I'm making this issue about documentation since I'm working on the Installation Guide as part of #2884

I've already mentioned Vagrant there in a commit in a branch. I still need to decide how much I want to promote Vagrant since it can be a little flaky. See the comment by @bricas at http://irclog.iq.harvard.edu/dataverse/2016-01-26#i_30160

**Comment by pdurbin** [comment]
In my pull request at #2895 I mentioned Vagrant in the Installation Guide. The change can be previewed at http://guides.dataverse.org/en/2884-install-guide-reorg/installation/prep.html#vagrant-for-testing-only

Passing to QA.

**Comment by kcondon** [comment]
Mentioned, closing.
