### ISSUE TITLE
Initial Home (Results) Page

### ISSUE THREAD

**Issue by shlake** [IQSS/dataverse#2819]
Suggestion by a few of our users. 

The "home" dataverse pages has the text "__1 to 10 of XXX Results__". Comment was "I haven't done a search yet, why am I getting results?"

A suggestion, based on top screens from DV 3.6:
There the text has "__Recently Released__". That is totally understandable (maybe "Recently Published" in V 4.2?). This is what the initial screen is showing published datasets/dataverses sorted by newest.

Then use the results text when a change in facet or a search is performed.

**Comment by djbrooke** [comment]
@jggautier is leading efforts to redesign the landing page and this is good feedback!

@shlake - as @jggautier moves forward in the process and needs some folks for user testing may he reach out to you?

If it's OK, I'll close out this issue.

**Comment by shlake** [comment]
Would love to test. Just let me know when and how. @djbrooke @jggautier

**Comment by jggautier** [comment]
Sherry and I are in touch to discuss this and other elements of the 4.x homepage.

**Comment by djbrooke** [comment]
Thanks both. I'm going to close this. This is one of the things we'll be user testing as part of the new homepage, so we'll have data about what's best to display here.

**Comment by pdurbin** [comment]
In addition to user testing, it looks like there are plans to conduct a survey about the new homepage: https://github.com/IQSS/dataverse-ui-ux/issues/1
