### ISSUE TITLE
Better Differentiation between Dataset boxes and Dataverse boxes

### ISSUE THREAD

**Issue by shlake** [IQSS/dataverse#2820]
Suggestion by a few of our users.

To make the borders (red/blue) around dataverse/datassets thicker. Comment was the red and blue boxes did not make them distinct enough.

**Comment by pdurbin** [comment]
@shlake thanks for the feedback! You could try applying your own custom CSS once you upgrade to 4.7. For now the docs about `:StyleCustomizationFile` can be found at https://github.com/IQSS/dataverse/blob/a7242a92eb5173977fff6eadc984ce22ec55f3ba/doc/sphinx-guides/source/installation/config.rst#custom-css-stylesheet

Please let us know if that works for you. Thanks!

**Comment by shlake** [comment]
@pdurbin Thanks for the "hint" way back in 2017. I finally got a chance to try it with my custom-stylesheet.css file. And it works (seen at this time on our test server).
This can be closed.

**Comment by shlake** [comment]
@pdurbin Thanks for the "hint" way back in 2017. I finally got a chance to try it with my custom-stylesheet.css file. And it works (seen at this time on our test server).
This can be closed.

**Comment by pdurbin** [comment]
@shlake you're welcome. And thanks for open sourcing your custom css file. I see you pushed the change already:

https://github.com/shlake/LibraDataHomepage/commit/a7aced581a9478768f42c9db0e31722064f6b7ec

:smile:
