### ISSUE TITLE
Advanced Search "File Type" needs better label

### ISSUE THREAD

**Issue by shlake** [IQSS/dataverse#2821]
Suggestion that this field be renamed to "File Extension" as this is what is being searched (and is what the tool tip says). 

There is also an inconsistency with the FileType facet. In the screenshot below, the search was for fileType "tab", but the File Type facet says "**tabulardata**:

![screen shot 2015-12-11 at 4 49 33 pm](https://cloud.githubusercontent.com/assets/3809325/11756375/75b958d8-a027-11e5-943d-0eaf02a2cf8d.png)

**Comment by pdurbin** [comment]
@shlake yes, I completely agree. Thanks for the feedback!

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
