### ISSUE TITLE
API: Cleaner messaging when attempting to delete a user that has "history"

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#2825]
Related to #2824 about deleting users, it's impossible to delete a user if that user had published the root dataverse:

org.postgresql.util.PSQLException: ERROR: update or delete on table "authenticateduser" violates foreign key constraint "fk_dvobject_releaseuser_id" on table "dvobject"
  Detail: Key (id)=(8) is still referenced from table "dvobject".

I'm not sure what the right fix for this should be. Would we change the "releaseuser" for the root dataverse to some other existing user?

**Comment by pdurbin** [comment]
One is unable to delete a user with a published dataset either: https://github.com/IQSS/dataverse/issues/2824#issuecomment-169399614

**Comment by scolapasta** [comment]
This is the desired behavior, as we want to track ho did what.

However, we should make the API call cleaner, I think, by checking for these things first and providing a friendlier message.

**Comment by bencomp** [comment]
In DVN 3.6 we don't delete users, we deactivate their accounts when necessary. It doesn't seem to be possible though: #2419

**Comment by pdurbin** [comment]
> In DVN 3.6 we don't delete users, we deactivate their accounts when necessary. It doesn't seem to be possible though: #2419

Yep. We haven't forgotten about that issue ( @scolapasta and I discussed it last week at https://github.com/IQSS/dataverse/issues/2824#issuecomment-169426416 and below) but thanks for linking it here, @bencomp

**Comment by pdurbin** [comment]
This issue may be a duplicate of #1929.

**Comment by kcondon** [comment]
Combined with #1929
