### ISSUE TITLE
Manage Templates: No Edit Button for Inherited Templates

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#2827]
When a dataset template is inherited by a dataverse from it's parent, no "Edit" button is displayed on the Manage Templates pg. To resolve this usability issue, it was suggested that a message like the one used for inherited permissions could be added to the "Action" column of the manage table.

This issue was also pointed out on the Manage Guestbooks pg #1736. More information about that issue, and the original discussion about resolving it can be found in that issue.

**Comment by mheppler** [comment]
Added new message to manage tables to identify templates and guestbooks that were created in the root or parent dataverse.

![screen shot 2016-01-04 at 4 20 52 pm](https://cloud.githubusercontent.com/assets/687227/12100842/8a6dd4c6-b2ff-11e5-9788-d271d35fe14c.png)

**Comment by kcondon** [comment]
Message appears as described, closing.
