### ISSUE TITLE
Browse/Search Facets: Custom Metadata Schemas Showing as options for Facets

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2830]
In #2077, custom metadata schemas were fixed to only show in the dataverses they belonged to. However, in the browse/search facets section the facets available for the custom metadata schemas are still showing up. We should have the facets match the same behavior as the metadata schemas section so only the citation, geospatial, social sciences, astronomy + astrophysics, life sciences, and journals facets appear for all dataverses (unless they are one that has the custom metadata)

**Comment by pdurbin** [comment]
Yep, this is still apparently a bug. If I go to https://dataverse.harvard.edu/dataverse/open-source-at-harvard I can see search facets from custom metadata blocks specific to Harvard like GSD:

<img width="948" alt="Screen Shot 2022-10-05 at 10 29 46 PM" src="https://user-images.githubusercontent.com/21006/194200919-5812d837-8713-4c1c-bf78-22af25246a44.png">
