### ISSUE TITLE
Installation Customization - Configurable Navbar Link for User Guides

### ISSUE THREAD

**Issue by shlake** [IQSS/dataverse#2831]
Propose that the "Guides" link at the top of the page NOT be a drop down but go to one [configurable] link (set as GuidesURL, so we can select THE URL - one - we want, and not need a "base" URL - currently the configuration setting is GuidesBaseURL).

**Comment by mheppler** [comment]
Discussion related to this issue can be found on #2832 which was closed in favor of this issue.

@pdurbin commented that a working example of this can be found at the [Peking University Open Research Data Platform](http://opendata.pku.edu.cn/) (running Dataverse 4.0) developed in part by @pengchengluo.

This feature relates to the installation branding/customization features being tracked in #2003.

**Comment by jggautier** [comment]
@mheppler, Derek and Julian spoke with @shlake about this issue in larger discussion about homepage customizations. Notes are [https://docs.google.com/document/d/17-_y4A-oBlmp4whIy7g9ISOiFDfJlNktuV8SFYagknk/edit](here: https://docs.google.com/document/d/17-_y4A-oBlmp4whIy7g9ISOiFDfJlNktuV8SFYagknk/edit)

**Comment by pdurbin** [comment]
@shlake heads up that related issue #3637 was created recently.
