### ISSUE TITLE
Publish Data: Configurable popup message

### ISSUE THREAD

**Issue by shlake** [IQSS/dataverse#2833]
When publishing a dataset, we would like the current pop-up

![screen shot 2015-12-16 at 11 50 48 am](https://cloud.githubusercontent.com/assets/3809325/11881308/f578e7fe-a4d3-11e5-8dca-7771a00275fd.png)

to have additional information (configurable??), such as  "Deposit License" text.

Suggestion is to include (on the "Are you sure" Publish Data pop-up) brief text (confirmation of complying with our deposit terms) when a dataset is published. This text should be configurable.

**Comment by ecr2c** [comment]
Hi Philip and Michael. I work with Sherry on UVA's Dataverse implementation. We found out this week that we cannot go forward with our local instance of Dataverse unless the change above is in place before we go live, per license agreement requirements as clarified by UVA's Director of Information Policy (our legal dude). We were really hoping for a February 8 soft launch. Could you give us an update on where this request is in the queue and if a resolution is possible before Feb 8?

**Comment by mcrosas** [comment]
The terms that the user needs to agree when creates an account  define also "deposit" terms. At Harvard Dataverse, these general terms are:
http://dataverse.org/best-practices/harvard-dataverse-general-terms-use

You can customize the terms for your installation. Would that be sufficient?

**Comment by ecr2c** [comment]
Hi there, we have three separate license and terms of use agreement pieces that need to be in our instance. We have good home for the first two:

1. Terms of Use (for general use of the software and content of our Dataverse instance). It is passive consent, users can view the terms from a link (the tag line) in the heading of each Dataverse that goes to:
http://libra.virginia.edu/terms

2. Libra Data Deposit License. It is similar to the Harvard General Terms, and the way Dataverse is configured, the only opportunity for depositors to view and agreed to this licenses is upon initial creation of a UVA Dataverse Account. This is what we will be using as the text for “General Terms” set by the variable ApplicationTermsOfUse:
http://www.library.virginia.edu/libra/datasets/dataset-license/

What we need is:

3. Acknowledgement/Confirmation of complying with our deposit license each time a dataset is published to be included with the "Are you sure" Publish Data pop-up, similar to this:
[UVa-confirmation.pdf](https://github.com/IQSS/dataverse/files/110484/UVa-confirmation.pdf)

This kind of pop up will remind users that the deposit is subject to those license terms and would help ensure people think twice about those issues before uploading a dataset that could contain sensitive info, etc. We are wary of having people agree to something once and then have free rein to deposit without being reminded of our expectations.

**Comment by mcrosas** [comment]
Thanks for the useful explanation. Does this mean that every time that same users publishes a new dataset or a version of an existing dataset you want that user to agree to the Confirmation of complying? Just trying to clarify if this should always appear at a time of "publishing".

Would this apply to all deposits for all dataverses in your installation? Otherwise, does this need to be configure at the dataverse level or at the installation level?

Also, note that this will also mean that the API to deposit datasets should not allow to publish the dataset unless this agreement is acknowledged somehow through the API.

**Comment by ecr2c** [comment]
Yes, exactly right! For every dataset a depositor publishes, the confirmation of complying should always appear as the popup box, for all dataverses in our instance.

Can you tell me more about the API issue? We are expecting all deposits to be via the Dataverse interface, does that still mean there are concerns with possible deposits from outside the Dataverse UI, even though we haven’t specifically enabled that?


On Jan 29, 2016, at 6:30 PM, Merce Crosas <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for the useful explanation. Does this mean that every time that same users publishes a new dataset or a version of an existing dataset you want that user to agree to the Confirmation of complying? Just trying to clarify if this should always appear at a time of "publishing".

Would this apply to all deposits for all dataverses in your installation? Otherwise, does this need to be configure at the dataverse level or at the installation level?

Also, note that this will also mean that the API to deposit datasets should not allow to publish the dataset unless this agreement is acknowledged somehow through the API.

**Comment by pdurbin** [comment]
All APIs are open an enabled by default. I'm clarifying this in a pull request at #2895.

**Comment by ecr2c** [comment]
Do we as Dataverse administrators have the ability to turn off specific APIs that are on by default? If so, for example, we could turn off the publish API.

On Jan 30, 2016, at 10:43 AM, Philip Durbin <notifications@github.com<mailto:notifications@github.com>> wrote:


All APIs are open an enabled by default. I'm clarifying this in a pull request at #2895<https://github.com/IQSS/dataverse/pull/2895>.

**Comment by pdurbin** [comment]
@ecr2c there are two ways to publish datasets via API:

- http://guides.dataverse.org/en/4.2.3/api/sword.html#publish-a-dataset
- http://guides.dataverse.org/en/4.2.3/api/native-api.html#datasets (search for "publish")

I've never actually tried blocking SWORD, but I believe it's blockable in the same way that "native" API endpoints are blocked. Again, the pull request at #2895 is where how to block APIs is starting to be documented. That pull request hasn't been merged yet (it's being reviewed) but as of this writing, you can preview what I wrote here:

- https://github.com/IQSS/dataverse/blob/bdbe60702c813020a7988923cca1a270cfaa9e5f/doc/sphinx-guides/source/installation/config.rst#securing-your-installation
- https://github.com/IQSS/dataverse/blob/bdbe60702c813020a7988923cca1a270cfaa9e5f/doc/sphinx-guides/source/installation/config.rst#blockedapipolicy

I hope this helps! You might also want to read the "Harvard Dataverse API Terms of Use" at http://dataverse.org/best-practices/harvard-api-tou . See also https://github.com/IQSS/dataverse/blob/bdbe60702c813020a7988923cca1a270cfaa9e5f/doc/sphinx-guides/source/installation/config.rst#apitermsofuse

**Comment by eaquigley** [comment]
@ecr2c Hi! Would this pop up text need to be displayed each time a user were to publish a new version of a dataset or only the first time they publish the dataset?

**Comment by ecr2c** [comment]
We could go either way. if a researcher publishes a new version, they don’t need to see the acknowledgment a 2nd time. They would have seen it on first publish.

But if it is easier to have it programmed to display every time, that is ok too.

Thanks!

On Feb 1, 2016, at 2:43 PM, Elizabeth Quigley <notifications@github.com<mailto:notifications@github.com>> wrote:


@ecr2c<https://github.com/ecr2c> Hi! Would this pop up text need to be displayed each time a user were to publish a new version of a dataset or only the first time they publish the dataset?

**Comment by eaquigley** [comment]
To sum this up, the requirements for this are:

- [ ] ability to add custom text into the Publish pop up
- [ ] have this pop up configurable for the installation so for every dataset published, this pop up happens
- [ ] okay with the custom text being displayed each time the pop up is displayed during publishing (so v1, v1.1, v2, etc)
- [ ] custom text also needs to be displayed for an API user publishing a dataset

@shlake and @ecr2c am i missing any requirement for this to work for your use case?

**Comment by shlake** [comment]
Hi @eaquigley The four requirements you list are exactly what will work for us. Any time frame as to when this would be in place?

Thanks.

**Comment by ecr2c** [comment]
Thanks @eaquigley . Requirements look good, as @shlake says. We definitely need this change in place before we can soft launch in mid-March, it is the very last piece of our pre-launch puzzle!

**Comment by sekmiller** [comment]
@eaquigley, @ecr2c, @shlake - This is going to be set at the dataverse level, so that any dataset within a given dataverse will have the same custom message and display logic.  Question: Should sub-dataverses use the same message/logic or should they be able to set their own message?

**Comment by shlake** [comment]
@sekmiller @eaquigley For UVa we need it set (be able to set it) for all dataverses (top level and sub dataverses), but I don't see why a sub-dataverse shouldn't be able to set their own message (or be able to unset a parent or inhertited message)?

**Comment by sekmiller** [comment]
Thanks for your input, everyone.  As stated in my email and agreed to by the responders, we will make the publishing popup message configurable at the installation level. This will ensure that all data deposited to a given installation will be subject to the same standard sign-off.

**Comment by kcondon** [comment]
@sekmiller Can you document how to customize the text?

**Comment by shlake** [comment]
Here is the text we want to include:

> By clicking Continue you affirm that you have met all licenses, policy and other data agreements:
> You have the legal right and authorization to make this data publicly available online worldwide through Libra.
> You have removed any confidential or sensitive information, including all information that personally identifies any individual or that contains any information that should not be made public under state or federal law, or UVA policy.
> You have fulfilled any right of review, confidentiality, or other obligations imposed under any sponsored research agreement.
> You have made a reasonable effort to ensure that the data contained in your submission is accurate.
> You have appropriately acknowledged other researchers whose work contributed to the data.

Which would look similar to the following when added to the popup box:
![publish](https://cloud.githubusercontent.com/assets/3809325/13294947/625e187a-daf4-11e5-81df-ed8a3134d918.png)

**Comment by sekmiller** [comment]
Here are the curl commands to get update the settings table:

  curl -X PUT -d true http://localhost:8080/api/admin/settings/:DatasetPublishPopupCustomTextOnAllVersions

curl -X PUT -d "Deposit License Requirements" http://localhost:8080/api/admin/settings/:DatasetPublishPopupCustomText

**Comment by eaquigley** [comment]
@shlake the deposit terms will be customizable for each installation so it will be part of the set up script for the installation. @sekmiller have you added how to do this to the installation guide?

**Comment by sekmiller** [comment]
It is in the installation guide in the branch for this feature.

**Comment by eaquigley** [comment]
@sekmiller :100:

**Comment by kcondon** [comment]
OK, I used the following command to test the above:

curl -X PUT -d "By clicking Continue you affirm that you have met all licenses, policy and other data agreements:
<ul>
  <li>You have the legal right and authorization to make this data publicly available online worlwide through Libra.</li>
  <li>You have removed any confidential or sensitive informatio, including all information that personally identifies any individual or that contains any information that should not be made public under state or federal law, or UVA policy.</li>
  <li>You have fulfilled any right of review, confidentiality, or other obligations imposed under any sponsored research agreement.</li>
  <li>You have made a reasonable effort to ensure that the data contained in your submission is accurate.</li>
  <li>You have appropriately acknowledged other researchers whose work contributed to the data.</li>
</ul>" http://localhost:8080/api/admin/settings/:DatasetPublishPopupCustomText

**Comment by kcondon** [comment]
OK, 2 issues:
1. for my browsers, chrome, ff, safari, I see a scroll bar on the popups, custom text or no.
2. for versions greater than 2, html is not rendered.

Passing to Stephen to check out, may make its way to Mike.

**Comment by sekmiller** [comment]
Fixed issue 2 above with the noted check-in.  Passing to Mike for issue 1.

**Comment by kcondon** [comment]
Verified issue 2 is fixed.

**Comment by mheppler** [comment]
Fixed scroll bar issue with Publish Dataset popups on dataset pg.

Sending pull-request and issue back to @kcondon for testing.

**Comment by kcondon** [comment]
OK, all issues resolved. Closing.
