### ISSUE TITLE
Groups: "usernames" are not accepted when trying to add users to "groups."

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2834]
You can only add users by "first and last name." Since everything else with permissions has been updated to use either or or, this should also be applied to this feature.

**Comment by pdurbin** [comment]
Hmm, I see what you mean @sbarbosadataverse . I just created the following user:

- username: foo
- given/first name: bar
- family/last name: baz

When I type the username ("foo"), the user can't be found:

![screen shot 2016-01-15 at 1 28 18 pm](https://cloud.githubusercontent.com/assets/21006/12361468/4beed66a-bb8c-11e5-9fc3-441ff4a8813c.png)


Typing the first or last name works fine:

![screen shot 2016-01-15 at 1 28 36 pm](https://cloud.githubusercontent.com/assets/21006/12361463/44383498-bb8c-11e5-8405-312c62d56799.png)

![screen shot 2016-01-15 at 1 28 45 pm](https://cloud.githubusercontent.com/assets/21006/12361458/3e9ae936-bb8c-11e5-822b-0114667adc84.png)

**Comment by pdurbin** [comment]
#2001 seems to be related but I'm not sure who worked on it. The commits were not tagged with that issue number, apparently.

**Comment by pdurbin** [comment]
To be clear, you can just type the username ("foo") and find it from the permissions page from a dataverse for example (<http://localhost:8080/permissions-manage.xhtml?id=1>):

![screen shot 2016-01-20 at 4 10 00 pm](https://cloud.githubusercontent.com/assets/21006/12463238/62115ba4-bf90-11e5-9cf2-8b8ec1a9ed64.png)

**Comment by pdurbin** [comment]
I'm assigning this issue to myself because I plan to mentor a new developer on fixing it. Also, we should test this with thousands of users in the system because with the fix in place I suspect it might suffer from #2853. (I create users with these scripts if it's helpful: https://github.com/IQSS/dataverse/blob/develop/scripts/search/populate-users and https://github.com/IQSS/dataverse/blob/develop/scripts/search/create-users .)

**Comment by pdurbin** [comment]
@scolapasta I helped get @majorseitan up and running with a Dataverse dev environment and he has already submitted two possible fixes:

- #2885 seems to be the smallest possible change
- #2887 seems to be a fancier changes

I haven't pulled either fix locally and thought I'd check with you before doing so. I'll assign this issue and both pull requests to you to decide how you'd like to proceed with them.

**Comment by scolapasta** [comment]
Since we can now assign @majorseitan to issues, reassigning to him. I have the pull requests and will review.

**Comment by kcondon** [comment]
Works, closing
