### ISSUE TITLE
adding files while creating new dataset results in error; solution is to create dataset without adding files 

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2837]
This has been reported several times in the past two weeks:

I am trying to create a new dataset as part of [any] Dataverse. However, it's giving me the following error: 

"edu.harvard.iq.dataverse.engine.command.exception.IllegalCommandException: Dataset with identifier 'TMSXYD', protocol 'doi' and authority '10.7910/DVN' already exists"

I was able to successfully create a dataset if I skipped adding files. User also tried this and was successful.

**Comment by sbarbosadataverse** [comment]
Went into same dataverse as user, no template was attached to this dataverse, created a dataset and added file, save successfully.

Can't recreate this same error : edu.harvard.iq.dataverse.engine.command.exception.IllegalCommandException: Dataset with identifier 'TMSXYD', protocol 'doi' and authority '10.7910/DVN' already exists"

**Comment by sekmiller** [comment]
After discussing with Gustavo and Kevin, we've decided to close this for now.  We will re-open if there are further reports of  the issue.
