### ISSUE TITLE
File Permissions: Grant Access success msg only lists file name for one of multiple

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2840]
When role is give to multiple files, either use generic success message or display all files user was given access to. Otherwise, it appears only one of multiple files selected was successfully assigned.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
