### ISSUE TITLE
Permissions - Pages w/o Log In Accessible Via URL

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#2841]
These admin-permission-like pages can be viewed, without being logged in, by going directly to the URL of the page.

- [x] Theme + Widgets: <http://localhost:8080/ThemeAndWidgets.xhtml?id=1>
- [x] Manage Dataverse Groups: <http://localhost:8080/manage-groups.xhtml?dataverseId=1>
- [x] Manage Dataset Templates: <http://localhost:8080/manage-templates.xhtml?dataverseId=1>
- [x] Create Dataset Template: <http://localhost:8080/template.xhtml?ownerId=1>
- [x] Manage Dataset Guestbooks: <http://localhost:8080/manage-guestbooks.xhtml?dataverseId=1>
- [x] Create Dataset Guestbook: <http://localhost:8080/guestbook.xhtml?ownerId=1&editMode=CREATE>
- [x] API Token: <http://localhost:8080/account/apitoken> - fixed in 0e08dca
- [x] Superuser: <http://localhost:8080/superuser.xhtml>
- [x] Dataset Widgets: <http://localhost:8080/dataset-widgets.xhtml?datasetId=3304>

Related to #2838 where the Sign Up page can be accessed with the URL, even if the installation settings do not allow account creation.

**Comment by kcondon** [comment]
@mheppler Thanks!

**Comment by pdurbin** [comment]
I feel like this issue might have "merge conflict" written all over so as a first step I think it makes the most sense to be clear about which xhtml files are in play so I'll modify the list by @mheppler to include them.

**Comment by majorseitan** [comment]
There seems to be a few options. 
1. viewAction,prerender view listener
2. rendered attribute
3. container managed security
4. filter
What would be the preferred approach?

**Comment by kcondon** [comment]
This is assigned to Widgets project, in part. When fixing, please update ticket with scope of fix so we know whether more work remains.

**Comment by pdurbin** [comment]
As of 0e08dca there is no longer a separate API Token page per #3086.

**Comment by sekmiller** [comment]
Fixes as outlined above complete in widgets branch.

**Comment by kcondon** [comment]
OK, all of the above URLs are now protected from unauthorized viewing. Closing.
