### ISSUE TITLE
Dataverse: Edit General Info, cannot disable selected blocks by Use metadata fields from parent.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2846]
Related #1473

If in a sub dv you choose specific metadata blocks, then later decide to use parent blocks again, simply checking use parent and saving doesn't work, though it acts like it does: clears check boxes and saves but revisiting settings shows old values still there.

The way to deselect is to first deselect each selected block, save, then select use parent, save. Not obvious.

**Comment by qqmyers** [comment]
FWIW: This appears to be fixed in 5.14+ - at least I can't reproduce it at QDR.
