### ISSUE TITLE
File Tags Popup: The list of available tags is appearing behind the popup and grayed out background.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2847]
Tested with both FF and Chrome
Edit file metadata, add tags, select from list of tags, tag list appears behind tag popup and grayed out background.

**Comment by mheppler** [comment]
Fixed CSS layering issue with dropdown menus and the blue spinner displaying behind popups.

**Comment by kcondon** [comment]
Works, closing.
