### ISSUE TITLE
Dataset Image File Preview: Preview window buggy, must move off image completelty

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2852]
preview of next image in an "image" dataset: preview doesn't work unless move off image completelty and return cursor to image list

https://demo.dataverse.org/dataset.xhtml?persistentId=doi:10.5072/FK2/C09I1Z&version=DRAFT

here is an example. If I hover to "preview" one image and move directly "down" to the next image with my cursor, the preview doesn't expand for viewing. Must move curses off the "file" space completely in order to get a next image preview. This is Chrome and Firefox

**Comment by mheppler** [comment]
This also happend on dvn-build in 4.2.3.

https://dvn-build.hmdc.harvard.edu/dataset.xhtml?persistentId=doi%3A10.5072%2FFK2%2FRNEAUE

**Comment by mheppler** [comment]
Fixed hover issue on the Preview popover for image files on the dataset pg.

Committed changes to a new branch titled "2016-01-ux-branch". This is branch is not associated with a milestone, which is why none is selected for this ticket.

**Comment by pdurbin** [comment]
I just merged the latest from the 4.2.3 branch into the 4.3 branch and then the 4.3 branch into 2016-01-ux-branch and then 2016-01-ux-branch back into the 4.3 branch. Along the way the version in the pom and guides was changed to 4.2.3. @scolapasta do we need a branch to fix this? My inclination is to just fix these in the 4.3 branch.

**Comment by pdurbin** [comment]
@scolapasta @kcondon I went ahead and fixed the versions in the 4.3 branch, updating them from 4.2.3 in 2875820

**Comment by pdurbin** [comment]
The "develop" branch was created from 4.3 so this fix is already in develop.

**Comment by kcondon** [comment]
Good catch guys! Works now: hover over first thumbnail, see preview, move directly over next in list, see preview. Closing!
