### ISSUE TITLE
Permissions: Looking up username on large dataverse for role assignment takes 6-8s.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2853]
PSI/Madagascar is a large nested dv with lots of role assignments. When adding a new user to assign a role to, it takes 6-8s to look up the username. This slows down an admin who may need to add several users.

**Comment by pdurbin** [comment]
@michbarsinai and @scolapasta discussed this recently when Michael was in town. Maybe @landreev too? I'm not sure if any diagnostics were done.

**Comment by bencomp** [comment]
Related: #2027

**Comment by mheppler** [comment]
I would suggest that #2027 is more than related, it's a duplicate.

**Comment by kcondon** [comment]
Closing as dupe.
