### ISSUE TITLE
Guides - Outdated Reference to TwoRavens

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#2866]
In the User Guide > Data Exploration Guide > TwoRavens: Tabular Data Exploration, there are references to TwoRavens old name "Sola Fide", which should be corrected ASAP.

**Comment by pdurbin** [comment]
I just merged the fix into the 4.2.3 branch (will set the milestone to this) in 6fe7c3a and ran a guides build. Passing to QA to check out http://guides.dataverse.org/en/4.2.3/user/data-exploration/tworavens.html

**Comment by kcondon** [comment]
Closing.
