### ISSUE TITLE
Odd tabular file behavior: duplicate tab files displayed on files page after ingest

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2873]
This is the second time in two days that I've uploaded tabular data and while scrolling on the files tab have noticed two identical tabular files in the list. If I completely leave the files page it eventually resolves itself, but not immediate: In this example TIF.TAB shows up at the top of the screenshot and at the very bottom-which should be impossible?

<img width="1232" alt="screen shot 2016-01-14 at 1 08 58 pm" src="https://cloud.githubusercontent.com/assets/8322346/12333120/5f7ab284-bac0-11e5-958d-5412e11c5a32.png">

**Comment by scolapasta** [comment]
This appears to be a duplicate of #2699. If not, could you clarify the issue in more detail. Thanks.
