### ISSUE TITLE
Dataverse creation: Indentifier field width too small

### ISSUE THREAD

**Issue by ajirnyi** [IQSS/dataverse#2874]
When the base URL is long enough (e.g. 49 symbols in our test case), the Identifier entry field is too short except for very wide browser windows, and it is not possible to see the text entered there (see example below). The issue is most noticeable in Firefox (box is too small up to screen width of 1183 pixels, after which it instantly expands), but is present in all browsers.

![dvidentifier](https://cloud.githubusercontent.com/assets/1527045/12335359/7aded088-bac4-11e5-8292-9b96fa7db6e9.PNG)

**Comment by pdurbin** [comment]
Yeah, in Chrome I tried "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ" as an alias and I can't quite see the first "z":

![screen shot 2016-01-14 at 2 53 48 pm](https://cloud.githubusercontent.com/assets/21006/12335735/a6e5fe4a-bace-11e5-8ce0-f8e82e9ba263.png)

**Comment by pdurbin** [comment]
@ajirnyi hi! Are you still interested in a fix for this issue?

**Comment by mheppler** [comment]
I am going to close this issue, as this UI bug is being looked into as part of the Create/Edit Dataverse form cleanup in issue _ Add "Add Data" to navbar, plus Host Dataverse input to create dataverse/dataset forms #5615_.
