### ISSUE TITLE
Number of total Datasets not displaying correctly when narrowing search to Dataverse Category: Journal

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#2878]
I need to collect metrics of # of total datasets for journal dataverses but when I narrowed my results down to just _Dataverse Category: Journal_ the number of total datasets displays as "0" which is not possible since there are 75 journal Dataverses listed with published datasets in them. For example this Dataverse is listed and has 24 published datasets: https://dataverse.harvard.edu/dataverse/regionalstatistics

![image](https://cloud.githubusercontent.com/assets/5013837/12421896/431e46a2-be92-11e5-9c57-c45211411a4a.png)

**Comment by pdurbin** [comment]
@posixeleni the behavior you're describing has to do with the fact that "Dataverse Category" applies only to dataverses. It's something you can facet on for dataverses. This is unlike "Subject" which applies to both dataverses and datasets:

![advanced_search_-_harvard_dataverse_-_2016-01-20_09 04 36](https://cloud.githubusercontent.com/assets/21006/12451032/0a651084-bf55-11e5-86c4-dae03eb56d2a.png)

The way that "Subject" is applied at the dataset level is that it's one of the fields (it's even required). @scolapasta worked on code in #1452 to have "Subject" get applied to the dataset's parent (a dataverse), writing,

> "When editing a datset, it will populate its ancestors subject, but if you remove a subject, that will not remove (eventually yes, but is extra work, since you have to then look at all datasets)."

(It sounds like a potential bug, by the way, if subjects are removed. Anyway.)

So, @posixeleni do you want a field at the **dataset** level for "Dataverse Category"?

We might want to ping @eaquigley and @mheppler for their thoughts on this as well. @eaquigley did drop by the other day to ask about "Dataverse Category" and I explained how it works, how it only applies to dataverses.

To solve your immediate problem of getting the total number of datasets for journal dataverses. I would probably write a script to facet by "Dataverse Category: Journal" (like you're doing) and iterate over those 66 dataverses to get counts of all the datasets within them. I agree it would be much friendlier to be able to do this from the GUI somehow!

**Comment by posixeleni** [comment]
Thanks for your reply @pdurbin and for explaining the logic, I need a short term solution script to collect these metrics to make sure we are meeting our FY2016 IQSS and Sloan goals for journals. Would you be able to assist me with this script or can someone else help?

For the long term I think @eaquigley and @mheppler will need to comment on how user friendly this display of zero datasets is. From my end-user standpoint I would assume that regardless of my selecting a facet that was *Dataverse only* I would still see the contents reflected accurately for the # of datasets held within these Dataverses. Otherwise I assume there is nothing in these Dataverses and stop my search there.

**Comment by pdurbin** [comment]
@posixeleni for now can you use the GUI to select each of the 66 journal dataverses one by one and then looking at the count of datasets in the top left. For example, you could click "Land Cover Map at APTBNC Dataverse" and see that there is one dataset:

![harvard_dataverse_-_2016-01-20_09 57 14](https://cloud.githubusercontent.com/assets/21006/12452445/7fe80152-bf5c-11e5-800b-c8e902bc4d2c.png)

![land_cover_map_at_aptbnc_dataverse_-_2016-01-20_09 55 24](https://cloud.githubusercontent.com/assets/21006/12452450/84152ac0-bf5c-11e5-8452-990daa4870a3.png)

**Comment by posixeleni** [comment]
@pdurbin i forgot to mention that I was already doing that, but this is time consuming and is not sustainable for the long term as the # of dataverses increases.

**Comment by pdurbin** [comment]
@posixeleni gotcha. Well, it sounds like you have a very real world use case (user story) that @eaquigley and @mheppler should review. Let's give this to @eaquigley for now to think about.

I'm afraid I can make any firm commitments about writing a script, @posixeleni . If you want I can sit with you and get you started if you'd like to write a script. I believe you were interested in Python at one point and maybe you'd be able to use https://github.com/IQSS/dataverse-client-python . There's also the Metabase idea at https://github.com/IQSS/dataverse/issues/2729#issuecomment-161840783

**Comment by eaquigley** [comment]
Spoke to @posixeleni and we were under the impression there was going to be a tag put on datasets for the dataverse category they belong to (so the reverse of what is currently happening with Subject(s) on datasets populating the Dataverse subject).

The requirement would be, "If I'm faceting on Dataverse Category, I should be able to get results for all the Dataverses, Datasets, and Files within that category."
