### ISSUE TITLE
Email Dataset Contact - Email needs more information when authors replyto a user

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2882]
I've been using the email icon to contact authors and when they reply I get no indication which dataset/dataverse they are replying from. Would be more helpful to have this info attached to the email dialogue box in some way.

**Comment by mheppler** [comment]
@sbarbosadataverse this issue you opened looks to be similar to **Email Dataset Contact: No context info given in the email correspondance received #1916**.

Please clarify any differences between these issue in a new comment #1916, and then close issue as a duplicate.

**Comment by mheppler** [comment]
Closing this issue as a duplicate of #1916 which is currently in development. Will also copy over the comment above from @sbarbosadataverse from Jan 21, 2016.
