### ISSUE TITLE
Account Sign Up: Can Enter The Same Email Address More Than Once (different cases)

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#2888]
@pdurbin and I just spoke about this related issue #2879 (case sensitive password reset) and so I tried to create a second account with the same email address but with different cases.

example foo@Harvard.edu and foo@harvard.edu

**Comment by pdurbin** [comment]
#2170 about confirming email addresses is also related.

**Comment by eaquigley** [comment]
@pdurbin will fixing this also fix the issue described in #2879? 

@scolapasta can you check to make sure people aren't creating multiple accounts with the same email address just different cases?

**Comment by pdurbin** [comment]
@eaquigley it depends on how we fix it. I **think** I'd like to simply force all email addresses to be persisted to the database in their lowercase version. I don't know if users will object to this. Will they say, "Hey! I entered my email address as fOo@bAr.cOm and that's the way I likes it!"? They probably won't care if we change it to foo@bar.com but I don't know.

@raprasad said it should be a simple SQL query to check for multiple accounts with the same address.

**Comment by majorseitan** [comment]
I went with the simple query fix.  I added the create index scripts to the pull request just in case they were needed.

**Comment by pdurbin** [comment]
To be clear, the pull request @majorseitan is talking about is #2894. Thanks!

**Comment by majorseitan** [comment]
This is addressed in pull request #2894

**Comment by majorseitan** [comment]
Tested providing an email with a different case
The following query was run
  SELECT ID, AFFILIATION, EMAIL, FIRSTNAME, LASTNAME, MODIFICATIONTIME, POSITION, SUPERUSER, USERIDENTIFIER FROM AUTHENTICATEDUSER WHERE (LOWER(EMAIL) = LOWER(?))
        bind => [1 parameter bound]]]
resulting in the error
This email address is already taken

The normal work flow works and I was able to register by providing an email that was no already in the database.

**Comment by pdurbin** [comment]
@majorseitan I just noticed that you closed your old pull request at #2894. Is the new pull request at #2986 now your proposed fix for this issue? If so, can you please include #2888 under "Related Issues" at pull request #2986? Thanks!

**Comment by majorseitan** [comment]
Corrected  #2986 to point to this issue.

**Comment by kcondon** [comment]
This is working, does not allow duplicate email of different case to be created, Closing.
