### ISSUE TITLE
Allow to set "Default Displays" on Parent Dataverse

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2889]
Dataverse admin would like the ability to set default on what users see displayed when they navigate to a dataverse:

see parents first
see subdataverses first
see datasets first, etc...

Apparently the list of "all" dataverses, subdataverses and datasets and files" can be quite overwhelming and confusing and this is has been reported before.

**Comment by pdurbin** [comment]
@sbarbosadataverse are you saying that a user would log in at set this preference for their **account**? Or are you talking about a setting that the admin of a dataverse would set at the dataverse level? I'd get @eaquigley and @mheppler involved for sure. We want a consistent user experience.

**Comment by sbarbosadataverse** [comment]
The admin of a dataverse would set this at the dataverse level. Thanks

On Tue, Jan 26, 2016 at 11:33 AM, Philip Durbin <notifications@github.com>
wrote:

> @sbarbosadataverse
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sbarbosadataverse&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=3UHoky4MotO-georOMyQm9sEluhbyg1i4wqSaDbKSVA&s=EDzlRCWHpuwj97r7Zbf1ioogpx2ebuC8BNCqQvN0p9k&e=>
> are you saying that a user would log in at set this preference for their
> *account*? Or are you talking about a setting that the admin of a
> dataverse would set at the dataverse level? I'd get @eaquigley
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_eaquigley&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=3UHoky4MotO-georOMyQm9sEluhbyg1i4wqSaDbKSVA&s=gQxH3_Zm-TqtBiknAG2xPY83Cci0sakl2brsWAu3Hyw&e=>
> and @mheppler
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mheppler&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=3UHoky4MotO-georOMyQm9sEluhbyg1i4wqSaDbKSVA&s=xGsM7Gzq_4v4JgggFQBG3qE2lreP7pNGG_69GdY8NY0&e=>
> involved for sure. We want a consistent user experience.
>
> —
> Reply to this email directly or view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_issues_2889-23issuecomment-2D175104010&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=3UHoky4MotO-georOMyQm9sEluhbyg1i4wqSaDbKSVA&s=cwHRwuvQrUMhc9e2YUckgnMNJMIO3tYCuuM4Q2gsRTg&e=>
> .
>



-- 
Sonia Barbosa
Manager of Data Curation, IQSS Dataverse Network
Manager of the Murray Research Archive, IQSS
Data Science
Harvard University

Dataverse 4.0 is now available for use!
http://dataverse.harvard.edu

All test dataverses should be created  in 4.0 Demo!
http://dataverse-demo.iq.harvard.edu/

Join our Dataverse Community!
https://groups.google.com/forum/#!forum/dataverse-community

**Comment by pdurbin** [comment]
But wouldn't that lead to an inconsistent (possibly jarring) browsing experience for users as they navigate around the site?

**Comment by sbarbosadataverse** [comment]
@pdurbin 
What it leads to should be brought to @Elizabeth and @mheppler  as I'm putting in the request from a user.

**Comment by pdurbin** [comment]
@sbarbosadataverse do you know which RT ticket this was from? I'd be curious to know the the user still wants this. Also, this reminds me a lot of #2715.

**Comment by donsizemore** [comment]
Odum has long wanted the ability to display only collections at the "root dataverse" level.

**Comment by cmbz** [comment]
2024/08/26: @sbarbosadataverse will ask the Community (and @jggautier will potentially ask UX working group for their feedback) if this is a must-have or nice-to-have feature for the UI and API.

**Comment by sbarbosadataverse** [comment]
No interest was communicated from the community
