### ISSUE TITLE
File Permissions: Can't scroll list of approved users

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2896]
Tim from Brain Genomics dataset noticed he can't see all "approved" users. You can't scroll the approved user list and likely the users "waiting for approval" dialogue box as well.

I am assuming this is the issue and not a bigger issue with the permissions/username page

@mheppler  assigning to you but give to anyone else if I'm wrong here.

**Comment by mheppler** [comment]
The title of this issue has been edited to be clearer after review it further with @sbarbosadataverse and @scolapasta. The `userGroupsAccess` table on the `permissions-manage-files` page does not have a scrolling feature. As many users that are in the database are the number of users that get displayed in that table, in full view on that page.

There are already other bug and user suggestion issues that will be looked into to improve this feature, such as #2641 (Permissions: Grant access errors for large # of files) and #2716 (File Permissions: Grant File Access popup should display number of restricted files).

Sonia, I am passing this issue back to you to confirm this, and to close the ticket.

**Comment by sbarbosadataverse** [comment]
@scolapasta  Can I close this? It's related to the larger bug #2722  and #2716

**Comment by sbarbosadataverse** [comment]
related to the larger bug #2722 and #2716
