### ISSUE TITLE
Investigate possibility of using Altmetrics for reporting and sharing dataset metrics

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#2899]
@eaquigley and I spoke with [Altmetrics](https://www.altmetric.com/) about using their repository badges to track metrics for datasets in Dataverse.

They pointed us to this small piece of code which would need to be embedded into each dataset page and would just the section to be populated

```
<div data-badge-popover="right" data-badge-type="medium-donut" 
data-doi="10.5072/FK2/PTU9PK" data-hide-no-mentions="true" 
data-hide-less-than="1" class="altmetric-embed"></div>
```

A very helpful description as to what altmetrics offer is included here: https://scholarworks.iu.edu/dspace/handle/2022/17147

**Comment by jggautier** [comment]
A list of sources Altmetrics uses is here: https://help.altmetric.com/support/solutions/articles/6000136884-when-did-altmetric-start-tracking-attention-to-each-attention-source-

It uses Scopus to account for citations in academic literature.

[Altmetrics needs a way to identify persistent IDs](https://help.altmetric.com/support/solutions/articles/6000086842-getting-started-with-altmetric-on-your-journal-or-institutional-repository) (DOI, hdl, etc.) in each dataset's landing page, and suggests using meta tags in landing page html  (#1393, #2445).

**Comment by jggautier** [comment]
Obi from UiT [mentioned](https://groups.google.com/d/msg/dataverse-community/dsCrZAWJIAs/sHg_W0DlAQAJ) on the Dataverse User's Community that they'd like to track altmetrics for [UiT Open Research Data Dataverse](https://opendata.uit.no/)'s datasets, but meta tags with dataset persistent IDs (DOI, hdl, etc.) need to be added to dataset landing pages first (#1393).

**Comment by jggautier** [comment]
In the 4.7 release, metatags with dataset persistent IDs (DOI, hdl, etc.) will be added to dataset landing pages (#1393).

FYI, how we support dataset citation tracking (Altmetrics, Counter, etc.) even more is still an open discussion.

**Comment by pdurbin** [comment]
@jggautier thanks for the update. Can you please write a little more about what the definition of done is for this issue? Thanks.

**Comment by jggautier** [comment]
Hey @pdurbin. Sorry for the very late reply. I would think this issue would be closed once we decided if and how we would support adding Altmetrics citation counts to dataset pages (or use another service like PlumX).

**Comment by pdurbin** [comment]
@jggautier ok, when a card has been created in https://trello.com/b/ySoeAeCc/ui-ux please link to it here. Thanks.

**Comment by djbrooke** [comment]
I'm going to close this. We don't plan to implement this in the near term, and we just merged metrics changes as part of Make Data Count support in #5253.
