### ISSUE TITLE
Account Page

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#29]
---

Author Name: **Gustavo Durand** (@scolapasta)
Original Redmine Issue: 3436, https://redmine.hmdc.harvard.edu/issues/3436
Original Date: 2014-01-31
Original Assignee: Xiangqing Yang

---

With 4.0 being a rewrite of the code base, this ticket represents one of the core functional components to be done. Individual items that can be tested separately or need to be passed to another developer or designer should be added as new tickets under this one.

* Account Info
* Group + Roles
* Preferences
* Data Related to Me tab, including dataverses, datasets
* Search w/ Facets
* "Add Data" button to create dataverse, add dataset, link dataverse/dataset
* Notifications
* History

---

Related issue(s): #379
Redmine related issue(s): [3794](https://redmine.hmdc.harvard.edu/issues/3794)

---

---

Child issue(s): #60, #61, #62, #96, #98, #100, #104, #105, #106, #107
Redmine child issue(s): [3467](https://redmine.hmdc.harvard.edu/issues/3467), [3468](https://redmine.hmdc.harvard.edu/issues/3468), [3469](https://redmine.hmdc.harvard.edu/issues/3469), [3505](https://redmine.hmdc.harvard.edu/issues/3505), [3507](https://redmine.hmdc.harvard.edu/issues/3507), [3509](https://redmine.hmdc.harvard.edu/issues/3509), [3513](https://redmine.hmdc.harvard.edu/issues/3513), [3514](https://redmine.hmdc.harvard.edu/issues/3514), [3515](https://redmine.hmdc.harvard.edu/issues/3515), [3516](https://redmine.hmdc.harvard.edu/issues/3516)

---

**Comment by mheppler** [comment]
Moved Account Information out of the Edit Account dropdown on the Account page, and give it it's own tab. Added Account Information into the dropdown off the user's name in the navbar.

**Comment by esotiri** [comment]
Verified @mheppler changes.
