### ISSUE TITLE
info request path in alias

### ISSUE THREAD

**Issue by rlzijdeman** [IQSS/dataverse#2900]
Hi, this relates to #1303. Users of our (IISH) instance of dataverse would like for the alias reflect the hierarchical structure of their (sub)dataverses. Obviously  '/' cannot be entered in the alias path and the result is that now the 'main' dataverse clutters with all kinds of aliases. In the future people might therefore 'miss out' on why a certain alias cannot be picked (they tend to think in terms of their own instance of dataverse).

So my question is, like in #1303, can this please be made optional, or so that, people are indeed allowed for the alias to reflect the path structure?

Best,

Richard

**Comment by pdurbin** [comment]
Dataverse aliases and paths have been discussed at #235. At this point I think it would be a fair amount of effort to refactor the code. Someone would need to dive into the code and play around to be more certain. Anyway, please see that issue for discussion on this topic.

**Comment by pdurbin** [comment]
@rlzijdeman are you still interested in this?

**Comment by rlzijdeman** [comment]
Hi, yes, are users still tend to think in terms of 'folder structures'. I think this is a more general tendency, but to be honest: In more than a year's time this request hasn't attracted any +1's :)

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
