### ISSUE TITLE
Do not load Google Analytics Javascript unless :GoogleAnalyticsCode is configured

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#2901]
In #1594 and #2069 we stopped hard-coding the Google Analytics code for the Harvard Dataverse in the HTML (see ab6fe38 ) but didn't address the fact that the **Javascript** for Google Analytics ( http://www.google-analytics.com/analytics.js ) is still being loaded.

If the `:GoogleAnalyticsCode` setting is absent the Google Analytics Javascript should not be loaded.

This issue was brought to our attention by @lmaylein at https://groups.google.com/d/msg/dataverse-community/7QsS-7FvK7g/EpmusIvDEAAJ

**Comment by majorseitan** [comment]
Addressed in pull request #2903

**Comment by kcondon** [comment]
Works, closing.
