### ISSUE TITLE
FITS File Upload: not being ingested properly/ possibly due to misidentification of file type

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2904]
Reported by a user, see RT 232095
User was uploading a fits file but was not seeing the extracted metadata in the file description. 

I tested here, was able to get it to work with a different file, had use try same file. They still could not get it to work. I downloaded their version of my file and it failed ingest for me too. After, all fits ingests failed for me. I was using Firefox v44.0. I tried Chrome and Safari and they still worked.

Not sure whether there is some misidentified file type that is cached in my  Firefox browser. Tried clearing cache, etc. but no luck.

For testing, I'm using this file from production:
dataset: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/28977
file: R_TRAP_J_Avg2_T.fits

When it is correctly ingested, the type appears as FITS, when incorrectly ingested it appears as type image/fits

**Comment by matthew-a-dunlap** [comment]
Tested uploading R_TRAP_J_Avg2_T.fits on firefox 54.0.1, and file uploads as FITS, not image/fits . Maybe Firefox cleaned up this issue with later versions?

**Comment by djbrooke** [comment]
I pinged Nick L from TDL to take a look at this to determine if it's resolved or not.

**Comment by mheppler** [comment]
As referenced above, @jggautier is still seeing this issue in demo (v 4.14) and I was able to replicate it locally in develop (v 4.15).

![Screen Shot 2019-06-18 at 11 19 19 AM](https://user-images.githubusercontent.com/687227/59696915-ef862000-91ba-11e9-88f7-e73a418a6b29.png)

**Comment by djbrooke** [comment]
Will close for tracking in #5919
