### ISSUE TITLE
URLs for harvested datasets are not rendered properly. 

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#2907]
A side effect of the dataverse page optimizations in 4.2.2. And my penny-pinching with entity objects, trying not to instantiate anything except for what was strictly necessary. 
As the end result, a URL pointing to a local dataset.xhtml is rendered, instead of a link to the remote location. 
I'm marking it 4.3, but would be in favor of producing a production patch for this.

**Comment by landreev** [comment]
I have a simple fix checked in, into the branch 2686-2907-bugfixpatch-424. 
It's simple, or simplified in that, rather than fixing the card-rendering code in the SearchResultsFragment, to render the correct remote url, it was much easier to modify DatasetPage, to redirect to the original harvested URL (instead of issuing 404). 
So the user still goes to the local dataset.xhtml, but gets redirected from there. It should be invisible to the user and the end result will be correct.

**Comment by landreev** [comment]
Once again, the branch name is 2686-2907-bugfixpatch-424
You'll need some harvested datasets in order to test that it's working now... 
On a copy of prod. db perhaps?

**Comment by kcondon** [comment]
This works for Odum and now Roper, now that the destination service was updated, but fails with 404 for ICPSR. Most likely an issue with the actual destination URL being outdated now, will check.

**Comment by landreev** [comment]
It is a local "404", so it is a lookup problem on our end. 
Most likely because our DOI code expects to have another "/" in the authority, maybe? - Their authority has no "shoulder" - it's just "10.3886".
Looking into it.

**Comment by landreev** [comment]
Pushed a fix into the branch.

**Comment by kcondon** [comment]
OK, works now. Closing.
