### ISSUE TITLE
Validation Message: Inform user they can't log in with an email address as a username

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2908]
We need to add a validation message to the log in and sign up pages to inform users they cannot use an email address as their user name. Tickets are being sent to RT in regards to this and it takes a while for support and the user to figure out what is going in. Would be nice to have email address as a log in option but that will take longer (#2115) and we need to add something in now that will help users who are attempting to log in via email address until email login can be supported.

**Comment by pdurbin** [comment]
I've been assigned #2115 so I'm grabbing this one as well.

**Comment by pdurbin** [comment]
Giving this to @scolapasta to review my commit in a new branch. Details at https://github.com/IQSS/dataverse/issues/2115#issuecomment-180409507

**Comment by pdurbin** [comment]
I misunderstood the requirement: https://github.com/IQSS/dataverse/issues/2115#issuecomment-180447388

I'm stealing this back.

**Comment by pdurbin** [comment]
I just made a new pull request at #2922 with some questions for @scolapasta so I'll assign this issue to him.

**Comment by scolapasta** [comment]
in fact, since we're fixing #2115 we can just close this one.
