### ISSUE TITLE
Rename Controlled Vocabulary Values to Controlled Vocabulary

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#291]
---

Author Name: **Steve Kraffmiller** (@sekmiller)
Original Redmine Issue: 3705, https://redmine.hmdc.harvard.edu/issues/3705
Original Date: 2014-03-13
Original Assignee: Gustavo Durand

---

Since there isn't an umbrella table rename for simplicity

**Comment by scolapasta** [comment]
We can leave the table as CVV, especially since it is joined to DatasetField, so actually makes sense to keep it with that name.
