### ISSUE TITLE
Add more detail to ActionLogRecord

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#2912]
The ActionLogRecord table records (among other things) every command that is called. However, the detail of the info for the commands is very sparse. Recently, we've been trying to debug a support issue and it became obvious that a mechanism for a command to provide more detail would be useful.

In this issue, we track the design and development of that infrastructure. Adding details for individual commands should be tracked separately.

(but we'll probably start with a few, for example, for RevokeRoleCommand - add detail on the user whose role was revoked.

**Comment by mheppler** [comment]
Related to **Add a mechanism to trim and/or archive ActionLogRecord entries #5916**.

**Comment by mdmADA** [comment]
ADA would also like more detail in the info field in the actionlogrecord specifically for: 

AssignRoleCommand - add the dataset doi to the info field when it's an assign FileDownloader permissions command: 
[user details] has been given DataverseRole{id=2, alias=fileDownloader} on [file details] in dataset [doi text or link].

RevokeRoleCommand - make it similar to the info for the AssignRoleCommand when it's a revoke fileDownloader role - the user it was revoked from, the name of the file, the doi of the dataset. Currently the info field only lists the dataset name but nothing else.

This is requested for the AssignRoleCommand as some datasets have the same file name.
This is requested for the RevokeRoleCommand so it can be known which file in which dataset was revoked.

**Comment by mdmADA** [comment]
Is it possible to add something like 
`@Override 
public String describe() {
        return toBeRevoked.getAssigneeIdentifier() + " has had the role: " + toBeRevoked.getRole() + " REVOKED on " + toBeRevoked.getDefinitionPoint().accept(DvObject.NameIdPrinter);
    }`

to the RevokeRoleCommand. I know it's a hard-coded string but it is similar to the describe() method in the AssignRoleCommand class. Many of ADA's users want to know who has had filedownload role revoked.

**Comment by pdurbin** [comment]
@mdmADA sound pretty non-controversial since it was part of the original description from 5 (!) years ago: "add detail on the user whose role was revoked"

I'd say please feel free to make a pull request!

**Comment by mdmADA** [comment]
@pdurbin - I issued a pull request for the RevokeRoleCommand. 

I assume there should be similar actionlogrecord detail for the RevokeAllRolesCommand.

Am wondering what could be recorded within the RevokeAllRolesCommand that would provide useful (specific) information regarding each role revoked for that specific user or how that could be achieved within the code. 

If the RevokeRoleCommand was called for each role in the RevokeAllRolesCommand then each specific role revoked would be logged. I'm not sure how to achieve this within the revokeAll(ra) method or even if it's achievable at all. 

A bare minimum would be to record that all roles for the specific user were revoked.

**Comment by pdurbin** [comment]
@mdmADA thanks for pull request #8211 and for setting it up to close this old issue. I moved it to QA.

For RevokeAllRolesCommand do you mind creating a new issue? From a quick look it seems like that command revokes all roles from the user and then removes the user from all explicit groups. I suppose all of this would be of interest to you in the log (but I'm not sure).

I see what you mean about `revokeAll(RoleAssignee assignee)` returning void so there's nothing to log. Maybe we can call a method to list assignments first? Or change `revokeAll` to return the information you want? We can figure out the details in a new issue and/or pull request.
