### ISSUE TITLE
Bug in TokenApplicationTypeServiceBean.getGeoConnectApplication

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#2914]
Bug where the hard-coded default geoconnect attributes are always used and overwrite the database entry.

The hard-coded attributes should not be used when there is info in the database.

https://github.com/IQSS/dataverse/blob/develop/src/main/java/edu/harvard/iq/dataverse/worldmapauth/TokenApplicationTypeServiceBean.java#L33

Note: To reproduce:

1. Click "Map Data" next to a shapefile
1. Look at then mapitlink attribute in the table 'worldmapauth_tokentype'
1. Change the mapitlink attribute to something else (anythng else)
1. Again, click "Map Data" next to a shapefile
1. Bug: The mapitlink attribute in the table 'worldmapauth_tokentype' has been set back to the default

**Comment by raprasad** [comment]
Fixed/tested locally.

**Comment by kcondon** [comment]
Works as described, closing.
