### ISSUE TITLE
Guestbook: Custom question dropdown displays behind popup

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#2918]
The dropdown menu for selecting a multiple-choice answer for custom questions in the Guestbook popup form, displays behind the popup, so that you can not view the options.

**Comment by mheppler** [comment]
This issue has been seen in the app before, and since I'm fixing it yet again, I've decided to be more prudent in my attempts to fix. I have gone identified all popups that have a component with a dropdown menu of some sort, so that I may test each to determine if this bug exists anywhere else.

- [ ] roles-edit.xhtml, rolesPermissionsDialog, h:selectManyCheckbox
- [ ] roles-assign.xhtml, userGroupDialog, p:autoComplete
- [ ] permissions-manage-files.xhtml, assignDialog, p:autoComplete
- [ ] manage-groups.xhtml, viewGroup, p:autoComplete
- [ ] explicitGroup-new-dialog.xhtml, explicitGroupNewDialog, p:autoComplete
- [ ] editFilesFragment.xhtml, editFileTagsPopup, p:selectCheckboxMenu (x2)
- [ ] editFilesFragment.xhtml, fileAdvancedOptions, p:tieredMenu
- [ ] dataverse.xhtml, linkDataverseForm, h:selectOneMenu
- [ ] dataverse.xhtml, linkDataverseForm, p:autoComplete
- [ ] dataset.xhtml, linkDatasetForm, h:selectOneMenu
- [ ] dataset.xhtml, downloadPopup, p:selectOneMenu
- [ ] dataset.xhtml, fileTagsPopup, p:selectCheckboxMenu (x2)
- [ ] dataset.xhtml, deaccessionBlock, h:selectOneMenu

**Comment by mheppler** [comment]
Fixed dropdown menu for custom question that displayed behind popup in the File Download > Guestbook workflow.

After applying the new fix, I was not able to find the bug in any of the menus above. This solution should cover the use of any more PrimeFaces components that use a dropdown menu. (For the record, I do not believe this is an issue for generic JSF components.)

This code commit was made to the ["feb-16-ux-fixes"](https://github.com/IQSS/dataverse/tree/feb-16-ux-fixes) branch and can be tested there.

**Comment by kcondon** [comment]
Popup in question is fixed, checked others mentioned and they are also working. Closing.
