### ISSUE TITLE
Info Message: Inform user which version they are editing

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2921]
we need to add an info message informing a user they are editing a draft of the most recent version if they access the edit options from a version that isn't the most recently published version.

example: on version 1 of a dataset with 3 published versions, select several files, click Edit Tags, need to inform the user they are editing the file tags in v3 NOT v1.

**Comment by sbarbosadataverse** [comment]
@TaniaSchlatter  making sure that what we are addressing is:
1-letting a user know they have created a "draft," when they select "Edit" and that "DRAFT" needs to be published once editing is done, or deleted if they don't want it anymore. The message should be clear to users at the top of the DRAFT page that "they have created a DRAFT to edit and this DRAFT needs to be published to replace the existing dataset."

**Comment by sbarbosadataverse** [comment]
how do you handle making sure the correct version when a  "user has multiple versions," is being edited? Looking at the versioning tab, for users who still don't understand versioning, all we provide is the "publishing" date on those now "Archived" versions. The latest published version should be clear that it's the version users are accessing and the version that should be edited when needed?  Users can click on any old version and edit it, and lose changes in the most recent version they made. It needs to be clear to the user which version they are editing (the most recent version versus version 3 of 5 (see my attachment)

"DRAFTs" under the versions tab should be clear it needs to be "published" and the image here from an existing dataset, doesn't tell you that.


<img width="1755" alt="Screen Shot 2021-07-15 at 3 29 24 PM" src="https://user-images.githubusercontent.com/8322346/125847021-1aa23bd6-a3a5-430a-a7a2-a9401188471a.png">

**Comment by sbarbosadataverse** [comment]
Another related versioning cleanup: is when I click on an older version (same example as above) nothing on this page indicates to me that I am not on the most recent published version of my dataset (I am actually on version 3 which I can mistakenly start to edit if I wanted to

<img width="1827" alt="Screen Shot 2021-07-15 at 3 37 33 PM" src="https://user-images.githubusercontent.com/8322346/125847413-05f5338b-1784-4e0f-9b87-f70b255c3dcb.png">

**Comment by scolapasta** [comment]
> Users can click on any old version and edit it, and lose changes in the most recent version they made. It needs to be clear to the user which version they are editing (the most recent version versus version 3 of 5 (see my attachment)

To be clear, a user can never edit any published version (the caveat being the superuser functionality that allows it), and a new draft is created always from the most recently published.

**Comment by TaniaSchlatter** [comment]
@scolapasta, this issue is for preventing the case of a user selecting a version that is not the most recent (v3.0 of 6.4, let's say), editing it, and creating version 7.0 or 6.5 (depending on what they choose) on publish, erasing changes made after 3.0. 

Based on this popup:
<img width="994" alt="Screen Shot 2021-07-15 at 4 54 35 PM" src="https://user-images.githubusercontent.com/15386424/125856308-a52fb340-5794-412f-bf3e-feafaf632893.png">
it looks like more recent changes only get rewritten if the "update current" option is selected? 

Which version is edited if the user selects the major release or minor release options? The one they selected (3.0) or the most recent (6.4)?

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
