### ISSUE TITLE
File Page: Add Back to Top Option at Bottom of Page

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2923]
would be helpful to have something like this: https://codyhouse.co/demo/back-to-top/index.html on the files page so if a user has scrolled down the page to see a ton of files, they can easily navigate back to the top. 

this would be something to do during the Files Tab Redux (which includes adding a view all option for the files tab)

**Comment by mheppler** [comment]
A new issue, **Dataset - File UI Improvements #3404**, was created to track the UI improvements related to the files view on the dataset pg. Older feature requests and bug reports like this one will be closed in favor of that new issue.
