### ISSUE TITLE
Files Edit Tags: Missing "Remove" and Add Multiple Custom File Tags

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#2925]
There were some UX issues outline in #2391 regarding the SelectCheckboxMenu component used for the File Tags and Tabular Data Tags. Additional issues came to light with the Custom File Tag field as that solution was being developed.

- You can not remove a Custom File Tag.
- You can only add one Custom File Tag at a time.

**Comment by mheppler** [comment]
Added static "Apply" button to the Custom File Tag input on the Edit File Tags popup on the dataset pg.

This code was pushed to the ["2391-file-edit-tags"](https://github.com/IQSS/dataverse/commits/2391-file-edit-tags) branch.

**Comment by mheppler** [comment]
@eaquigley -- We need to investigate potential UI solutions with @sbarbosadataverse and other stakeholders for "managing" file tags in general for a dataset, as opposed to editing the individual file tags applied to individual file.

**Comment by sekmiller** [comment]
Per discussion with @eaquigley and @mheppler I added remove unused tag functionality.  I added a check box that if checked will remove any custom tags that are not assigned to any files in a dataset.
![screen shot 2016-02-23 at 4 41 25 pm](https://cloud.githubusercontent.com/assets/2364928/13267676/89f85268-da4c-11e5-8019-45bb1bd7b59f.png)

**Comment by mheppler** [comment]
Cleaned up the UI of the Delete Tags checkbox on the Edit Tags popup, as well as the UI in general for the Edit Tags popup linked from the Edit Files pg.

![screen shot 2016-03-01 at 12 20 43 pm](https://cloud.githubusercontent.com/assets/687227/13435394/14c2a410-dfa8-11e5-9a73-c3b608343c60.png)

**Comment by mheppler** [comment]
The wiring up of the Delete Tags checkbox on the Edit Files pg version of the popup has been postponed, and documented in a new ticket, #2991.

**Comment by kcondon** [comment]
Add multiple custom tags works, remove unused works though it is missing from edit files view popup. Will open a separate ticket for that. Closing.

**Comment by TaniaSchlatter** [comment]
Ideally the "Delete Tags" feature only shows up when there are custom file tags that are not being used.
