### ISSUE TITLE
Delete Role: There is no way in the UI to delete a user created role.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2927]
Deleting a role can be problematic: need to first remove all assignments, etc, cannot delete built in roles, need to be superuser, etc. However, all were true when I tested creating a custom role and saw no way to delete.

**Comment by pdurbin** [comment]
As mentioned in this thread, there is an [API for deleting roles](https://guides.dataverse.org/en/5.12.1/api/native-api.html#delete-role), but it doesn't seem to work: https://groups.google.com/g/dataverse-community/c/5bZqCRFP8BU/m/1JRc-p5RAwAJ

**Comment by DS-INRA** [comment]
Maybe this should be tagged as an improvement for SPA when it is mature enough to address this part of the UI :)

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
