### ISSUE TITLE
Support Registering Multiple Prefixes for DataCite DOIs In an Installation

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#2943]
[Alan Darnell from Scholars Portal informed us on our User Community](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/dataverse-community/7-5NsSA6iGg/7kG4RR_VEQAJ) that there is an additional use case we need to consider for fully supporting DataCite DOI registration for their installation.

> In particular, I am interested in whether it will be possible to associate different DataCite accounts (and prefixes) with different Dataverses.  We have a number of libraries using a shared Dataverse instance -- each library has its own account with DataCite and so its own prefix.  Ideally, we would like to associate accounts and prefixes with IP Groups so that datasets created under a specific IP group can be registered with an institution specific prefix.  

We are already working on Phase 1 of implementing DatCite DOI support (#24 ) which will only allow for the registration of a single prefix at the system level to begin with. But we will be looking at supporting the Scholars Portal use case as well in the future (more from Alan):

> We could start out with a single installation prefix, but there should be an option to suppress automatic generation of a DOI to allow an institution that uses DataCite to mint its own DOIs with its own institution prefix to add these manually.  Otherwise, we would end up with 2 DOIs pointing to the same resource, which would not be terrible, but could be confusing.  
> 
> Ultimately, it would be good to have a prefix "override" at the Dataverse level -- a place to enter institutional DataCite credentials -- that would override the default server level credentials and prefix.  The reasons for this include stats tracking.  If you look at this Datacite site, you can see how stats on registrations and resolutions are captured: https://stats.test.datacite.org

**Comment by pdurbin** [comment]
Related: #3623.

**Comment by pdurbin** [comment]
Closing in favor of #3623.
