### ISSUE TITLE
Bug: spaces allowed in email and useridentifier in authenticateduser table

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#2945]
I'm on f37fdbd working on authenticateduser-related code creating users from https://randomuser.me and just noticed that spaces are allowed in email and useridentifier in the authenticateduser table despite Bean Validation. I can only assume this is a bug

```
$ psql -c 'select firstname,lastname,email,useridentifier from authenticateduser where id=52;' dataverse_db
 firstname | lastname |           email            | useridentifier 
-----------+----------+----------------------------+----------------
 Elisah    | Da mota  | elisah.da mota@example.com | elisah.da mota
(1 row)
```

We should also doublecheck email and username on the builtinuser table but I suspect username is fine.

**Comment by kcondon** [comment]
retest with leading and trailing spaces, we should check this anyway.

**Comment by kcondon** [comment]
Closing this as duplicate of #3044
