### ISSUE TITLE
sorting file by downloads:  feature request by user from HKS

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#2947]
interested in letting users know which datasets have been downloaded
how many times, and letting users sort the datasets by downloads. Would it
be possible to have this data on the front page and have it an option under
the "sort" pull-down menu

**Comment by pdurbin** [comment]
This reminds me of #2729. There are nice screenshots at https://github.com/IQSS/dataverse/issues/2729#issuecomment-154773635

**Comment by eaquigley** [comment]
Something to think about when adding this sorting option:
- [ ] Downloads equals: explicit dataset downloads; e.g.-one file in the dataset downloaded 1000 times
- [ ] Downloads equals the sum of all the files downloaded; e.g.-each file in the dataset downloaded 5 times each
- [ ] Downloads of Metadata for the dataset  

Per discussion with @djbrooke

**Comment by mheppler** [comment]
A new issue, **Dataset - File UI Improvements #3404**, was created to track the UI improvements related to the files view on the dataset pg. Older feature requests and bug reports like this one will be closed in favor of that new issue.
