### ISSUE TITLE
Shibboleth: successful conversion from builtin/local account message should appear on account page rather than the home page.

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#2952]
In  #796 we developed "Account/Shibboleth: Converting from local to non-local" but in a design review yesterday we decided that we'd rather have the success message be on the account page rather than the home page. I don't **think** there are any other requirements in this area but @eaquigley can clarify.

**Comment by pdurbin** [comment]
Done in e911234. Redirects to account page:

![screen shot 2016-03-07 at 1 55 50 pm](https://cloud.githubusercontent.com/assets/21006/13579680/c3d2a644-e46c-11e5-8cf8-1694e843381d.png)

**Comment by eaquigley** [comment]
Just tried this out and it works like a dream. Thanks @pdurbin!!

**Comment by pdurbin** [comment]
Passing to QA. @eaquigley seems happy, above, which is always good. :)

The fix is in pull request #3025.

**Comment by kcondon** [comment]
Works, closing.
