### ISSUE TITLE
Update File Ingest Documentation To Explain Duplicate File Handling

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#2956]
Current User Guide needs to be updated to clearly explain how we find and treat duplicate files (checksum verification instead of filename matches)

**Comment by eaquigley** [comment]
If the only time the error message in the screenshot below appears is when a file is uploaded has a checksum that is the same as a file already in the dataset, then perhaps we should change the error message to be more explicit so users don't have to go to the user guide to find out what is going on.

![screen shot 2016-02-16 at 4 37 15 pm](https://cloud.githubusercontent.com/assets/5922904/13092145/77266dd0-d4cc-11e5-9f97-dd7b3136a06c.png)

**Comment by posixeleni** [comment]
+1

Eleni Castro
Research Coordinator, IQSS
Harvard University

**Comment by bencomp** [comment]
This relates strongly to #2955, but had no link yet. Please solve that issue (how should apparent duplication be handled) first :)

**Comment by pdurbin** [comment]
Related: As a researcher, I need to publish a dataset that contains files with the same content, which are handled differently #4813

**Comment by mheppler** [comment]
Closing this issue as we are currently looking into changing how the MD5/checksum validation as part of issue _File Upload - allow files with same MD5 in a dataset #4813_. Any changes to this feature will be thoroughly documented as requested in this issue.
