### ISSUE TITLE
Dataverse UI for mapping Tabular files

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#2957]
- Dataverse users with correct (edit) permissions will be able to “tag” a tabular file as containing geospatial data.

The following points apply to _published_ geospatial files.

- [x] Dataverse users with edit permissions will be able to visualize geospatial files via the Map Data button.
   - [x] For the geoconnect link, retrieve the .tab version of the file.  Similar shapefile-specific functionality already exists. 
- [x] Dataverse users with view permissions will be able to view maps from geospatial files by using the Explore button (see #2961)
- [x] Dataverse users with view permissions will be able to link to the WorldMap page where the visualized geospatial file resides. (see #2961)

---

See wireframes: https://iqssharvard.mybalsamiq.com/projects/geoconnectmapdata20/grid

**Comment by kcondon** [comment]
OK, works, closing
