### ISSUE TITLE
File Permissions - Grant Access popup needs existing user access status

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#2958]
Grant Access popup doesn't display status of a user's access to restricted files in the list after they have been selected in the User/Group autoComplete input.

Originally requested by @sbarbosadataverse in #2641.

**Comment by scolapasta** [comment]
The challenge with this is that you can add multiple users with different file access, so if this something we want to do, we'll need to decide how to display this first. (and then see technically how to make it work, but first design!)
