### ISSUE TITLE
General Terms of Use: Remove Mention of Guest Terms of Use

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2959]
Noticed by TDL folks that in the General Terms of Use there is a mention of the Guest Terms of Use. In 4.x, those don't exist because of the use of the CC0 and ability to input Custom Data Usage Agreement that a user (guest or otherwise) would need to accept before a download can begin. 

We need to remove Guest Terms of Use and make sure it is clear that CC0 or a Data Usage Agreement is replacing the Guest Terms of Use.

**Comment by eaquigley** [comment]
This only needed to be updated in dataverse.org, not part of the code. My bad! 

Changed text to say, "Downloaders must be registered Users of the Site or guests that agree to the CC0 waiver or the Custom Data Usage Agreement for a dataset in order to take advantage of the Site’s Services, including downloading any materials or datasets."

Passing to QA to close.

**Comment by posixeleni** [comment]
Looks good!
