### ISSUE TITLE
Explore button dropdown 

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#2961]
Related #2957 
Prerequisite: #2135 (two ravens settings on/off)

----

#### Possible Explore Button States
1.  Tabular Files
  - No Explore button
      - When the installation DOESN'T have TwoRavens configured and there's no map
  - 1 Explore button: Two Ravens only 
      - When the installation has TwoRavens configured and there's no map
  - 1 Explore button: WorldMap only
      - When the installation doesn't have TwoRavens configured and there's a Map
  - 2 Explore buttons: Two Ravens and View WorldMap

1.  Shapefiles
   - No Explore button
   - 1 Explore button (View WorldMap)

#### Code
  - **Dataverse Branch**: 2957-tab-mapping
  - **File:** filesFragment.xhtml
  - **Render triggers for explore options:** 
```
#{DatasetPage.canUserSeeExploreWorldMapButton(fileMetadata)}
#{DatasetPage.canSeeTwoRavensExploreButton(fileMetadata)}
```

**Comment by mheppler** [comment]
Styled "Explore" button dropdown for TwoRavens and WorldMap on the Dataset pg. Also styled some other related components, like the "Preview" link and the "Preview Map" popup.

Passing back to @raprasad to complete his work, including the missing "Map Data" button on the Dataset pg for tabular files that already have a map.

**Comment by raprasad** [comment]
## Testing

Make sure these settings are available and true.  (They may be toggled during testing)

```sql
INSERT INTO setting VALUES (':TwoRavensTabularView', true);
INSERT INTO setting VALUES (':GeoconnectViewMaps', true);
INSERT INTO setting VALUES (':GeoconnectCreateEditMaps', true);
```

### When Geoconnect or WorldMap is not available
To see WorldMap inserts as shown in the screenshot below:
  1. Log in as a superuser
  1. Add this setting:
```sql
INSERT INTO setting VALUES (':GeoconnectDebug', true);
```

![new_dataset_for_tags_-_root_dataverse](https://cloud.githubusercontent.com/assets/1036060/13297230/47841508-daff-11e5-9fc7-be544b6f1f41.png)

**Comment by kcondon** [comment]
@raprasad I'm seeing the map it button not disappearing for an already published dataset with a shapefile for which I have run the insert statement. Seems like a bug?

**Comment by shivadcedtu** [comment]
I have installed the two Ravens but the explore function is not coming...please help me


OK, please confirm what you've entered:

Directory where TwoRavens is installed: /var/www/html/dataexplore
Apache config directory: /etc/httpd
Apache Web Root directory: /var/www/html
Internet address of the rApache host: localhost.localdomain
rApache port number: 80
http or https?: http
URL address of the Dataverdse application, to access files and metadata: http://localhost.localdomain:8080

Is this correct? [y/n] y
Configuring script rooksource.R...
Configuring script rookdata.R...
Configuring script rookzelig.R...
Configuring script rooksubset.R...
Configuring script rooktransform.R...
Configuring script rookselector.R...
Configuring script rookutils.R...


Configuring rApache to serve TwoRavens Rook applications...

Restarting Apache...
Stopping httpd:                                            [  OK  ]
Starting httpd:                                            [  OK  ]

Creating application directories on the filesystem...
OK!


Great. You should now have a working TwoRavens installation!

**Comment by pdurbin** [comment]
@shivadcedtu for the Explore button to work, you have to upload a tabular file that passes successfully passes through "ingest". Please see http://guides.dataverse.org/en/4.5.1/user/tabulardataingest/ . In addition, there is a setting to control if the Explore button appears: http://guides.dataverse.org/en/4.5.1/installation/config.html#tworavenstabularview . If you continue to have trouble, a better place to discuss this is probably https://groups.google.com/forum/#!forum/dataverse-community or http://chat.dataverse.org rather than an old, closed issue. 😄

**Comment by pdurbin** [comment]
@shivadcedtu this pull request @donsizemore just made should help: #3453
