### ISSUE TITLE
Widgets: Handle and DOI links in the citation leave the user within the frame

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2965]
When on someone's personal website that has a Dataverse widget and you click on the handle or doi in the citation within the search card, it isn't bringing you back to Dataverse. A user instead is staying on the person's website and the dataset is being opened within the widget frame. This is not happening when a user clicks on the name of a dataset link in the search card. 

According to @mheppler, "The dataset citation and it's DOI link (value="#{result.citation}") are something that get delivered from the backend, so any fix related to that link needs to happen on the backend." So there's that tip for fixing this.

**Comment by pdurbin** [comment]
Right. The citation comes from Solr. To get the values into Solr the indexing code calls DatasetVersion.getCitation.

**Comment by mheppler** [comment]
Added target="_top" attribute to citation block persistentURL HTML link created in the DatasetVersion.java backing bean. This will force that URL to be loaded in the top most window, outside of any and all iframe it may be displayed in. It will behave this way both from the citation block in the result cards on the dataverse pg, as well as the citation block in the dataset pg.

This fix has been committed to the [2965-dataset-card-links](https://github.com/IQSS/dataverse/tree/2965-dataset-card-links) branch.

**Comment by mheppler** [comment]
| Page/Requirements  | Issue# | Commit# |
| ------------- | ------------- | ------------- |
| **Dataverse Listing Widget, Personal Site**  |
| Add `target="_top"` attribute to persistentURL link in citation block on dataset result cards  | #2965  | 5977e0e0e8e0105f395d5ba9c2075b4e2684d72a  |

**Comment by kcondon** [comment]
This works as Mike describes: in the same window, dataset is displayed outside of widget frame. However, clicking on the dataset title opens in a new tab whereas clicking on the citation doi link opens in the same window without the widget frame. @eaquigley @mheppler @scolapasta is this what we want?

**Comment by kcondon** [comment]
Can be tested on dataverse-internal.iq.harvard.edu/test.html

**Comment by eaquigley** [comment]
Tested by myself and @sbarbosadataverse. Comments are in the pull request. Closing this ticket.
