### ISSUE TITLE
Multiple related publications do not appear

### ISSUE THREAD

**Issue by acjaz88** [IQSS/dataverse#2967]
I added multiple entries of this field to a dataset (https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi%3A10.7910%2FDVN%2FFIS9LH&version=DRAFT), but only the first entry appears in the view.

**Comment by pdurbin** [comment]
@acjaz88 I'm sorry to hear about your trouble. Please email support@dataverse.org and paste the URL of the ticket that's generated as a comment here. Thanks.

**Comment by acjaz88** [comment]
@pdurbin Thanks for the quick reply. The ticket URL is https://help.hmdc.harvard.edu/Ticket/Display.html?id=232964

**Comment by sekmiller** [comment]
This is working as designed. Only the first Related Publication is shown with the "key" or "above the fold" metadata.  The rest are can be seen if you click on the Metadata tab 
![screen shot 2016-02-24 at 10 00 45 am](https://cloud.githubusercontent.com/assets/2364928/13289421/0088fd24-dade-11e5-907a-c1a785a2b8f4.png)

**Comment by sbarbosadataverse** [comment]
Yes, working as expected

On Wed, Feb 24, 2016 at 10:04 AM, Stephen Kraffmiller <
notifications@github.com> wrote:

> This is working as designed. Only the first Related Publication is shown
> with the "key" or "above the fold" metadata. The rest are can be seen if
> you click on the Metadata tab
> [image: screen shot 2016-02-24 at 10 00 45 am]
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__cloud.githubusercontent.com_assets_2364928_13289421_0088fd24-2Ddade-2D11e5-2D907a-2Dc1a785a2b8f4.png&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=CLOhvvPxVEw1w_b96lCobRxeuQb3DGhpMqJFpdcwDs4&s=OC7dIvqBc7w02mwU7hrekSWxR009HIQoxtLIXPlCr7s&e=>
>
> —
> Reply to this email directly or view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_issues_2967-23issuecomment-2D188293905&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=CLOhvvPxVEw1w_b96lCobRxeuQb3DGhpMqJFpdcwDs4&s=tM5CeXsNwJLjSXBPYdBBXBlITtlcf7-jh2HAkU4kDAo&e=>
> .
>



-- 
Sonia Barbosa
Manager of Data Curation, IQSS Dataverse Network
Manager of the Murray Research Archive, IQSS
Data Science
Harvard University

Dataverse 4.0 is now available for use!
http://dataverse.harvard.edu

All test dataverses should be created  in 4.0 Demo!
http://dataverse-demo.iq.harvard.edu/

Join our Dataverse Community!
https://groups.google.com/forum/#!forum/dataverse-community
