### ISSUE TITLE
Icons in Share Pop-Up Not Displaying in Firefox v44

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#2970]
@shlake reported an issue to me that she found in the most recent version of Dataverse where if you are on Firefox V44 on Mac – 10.10 the social media site icons in the Share pop-up are not displaying but instead are just three color bars. They point to the right sites but the icon is missing.

![image](https://cloud.githubusercontent.com/assets/5013837/13302783/0572199c-db4c-11e5-9418-6015909e34c6.png)

**Comment by mheppler** [comment]
@posixeleni + @shlake -- do you have any more details about where this was seen? I checked our current production Harvard Dataverse (running 4.2.4), as well as another test environment (running the latest and soon to be greatest post-4.2.4 code), and was not able to replicate this issue.

**Comment by posixeleni** [comment]
I saw this on @shlake computer when you click on the Share button at root
and also at dataset level. Was not able to reproduce on my laptop on
Firefox 44 (i have mac 10.11) but was able to verify with Sherry that this
only happened when she was on firefox.

**Comment by mheppler** [comment]
Thank you for the additional details, @posixeleni. I will try to investigate further and replicate it somehow, somewhere.

@shlake -- could you please confirm that you are still seeing on either installation? Also, if you do see still, please attempt this simple method of refreshing your browser's cache of the site. Hold the "shift" key on your keyboard, while clicking the "refresh" button on your Firefox browser window. This will clear your browser's cache of various image, stylesheet and javascript files. Hopefully it will fix any weirdness locally for you that could be causing these icons to go missing on only one of three computers.

**Comment by shlake** [comment]
@mheppler after messing w/ a few things, I fixed it by **disabling AdBlock-Plus** on the dataverse sites (Harvard's and UVa's). Running Firefox 44.02   w/ AdBlock Plus 2.7.2.

Now I see the social media site icons.

**Comment by mheppler** [comment]
@shlake -- thank you for the additional details! There's something there with browser plugins to look into.

**Comment by kcondon** [comment]
Closing since this was an add-block issue.
