### ISSUE TITLE
WorldMap thumbnail generation

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#2972]
Currently thumbnail generation is only attempted when information is returned via the Dataverse API.

e.g., Dataverse attempts to contact WorldMap via a PNG generation link.

Update the code to check for the thumbnail on each view--if it doesn't exist try the PNG generation link again.

**Comment by djbrooke** [comment]
Closing some old Worldmap issues. Will re-evaluate when/if additional Worldmap work gets added to the roadmap.
