### ISSUE TITLE
Login page for "only remote authentication" mode

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#2974]
As I dig into #2838 I'm realizing the that "only remote authentication" authentication option in the [Remote Authentication Business Requirements Document](https://docs.google.com/document/d/1vcAmo2nkFYavAr7OwwXzxM0IFQbkRZYZrrX43q-wqGE/edit?usp=sharing) (BRD) is not especially well defined. As of 2016-02-26, this is what it says under "phase 1" (#2939):

> An installation should be able to configure to use: 1) only local authentication, 2) only remote authentication (support both Federated Login mode - all approved institutions from InCommon - and Specific Identity Provider(s)), 3) both 1 and 2

The "remote only" mode is not something we plan to use at https://dataverse.harvard.edu but I understand that folks like @donsizemore @ecr2c @shlake @ajirnyi @bencomp and others might want to run in this mode. The question #2838 got me thinking about (after talking with @mheppler) is this...
- When installations like the Odum, DANS, the University of Virginia, and others who have expressed interest in "only remote authentication" mode put their installation in that mode, will they expect to still see the login screen for **local** users that appears on the left?

Here's a screenshot:

![log_in_-_root_dataverse_-_2016-02-26_09 42 43](https://cloud.githubusercontent.com/assets/21006/13355229/5499d4e8-dc6d-11e5-8993-7e12f2801500.png)

I'm guessing they're going to say, "Hey! I put this thing in 'only remote authentication' mode. How come it's still providing a place for local users to enter their username and password?"

And I answer, "Well, what if your identity provider is down? Maybe you'd like to be able to log in with the 'dataverseAdmin' local account. Besides, changing this was out of scope for phase 1 (#2939) ." :)

Food for thought, at least. Please note that there is a lot of chatter about "remote only" mode in #2838 about what this mode means. I recommend reading the comments. I'm going to try to make **this** issue mostly about the login screen for now. We could put a bullet under phase 2 in the BRD saying something like "Evaluate the need to hide the login prompt for local users when in 'only remote authentication' mode." That said, another issue raised in #2838 is this...
- Should "remote only" mode automatically prevent local users from being created via API? (Currently there's a separate control for this. This will probably be decided as part of #2838.)

And there are probably other things to consider as well for "remote only" mode. As always, comments are welcome.

**Comment by pdurbin** [comment]
Assigning to @eaquigley because @mcrosas wants her to check with Odum, DANS, etc.

In #2939 I'm declaring this issue out of scope for "phase 1" but we still want feedback from the community, of course!

**Comment by eaquigley** [comment]
@pdurbin, @mheppler, and I talked a bit about this today and had a request for @scolapasta to brainstorm what the technical implications are for not having local accounts; how will this impact the database and all actions associated with roles?

**Comment by bencomp** [comment]
@eaquigley Dataverse will still know about every user, because remotely authenticated users will have to create an account that is linked to the identity provided by the remote authentication provider. You can assign roles to these users or add them to groups just like local accounts.

**Comment by pdurbin** [comment]
I just re-read the line "To disable account creation by users, sys admins may turn off the LocalAuthenticationProvider module" at https://github.com/IQSS/dataverse/blob/v4.3.1/doc/Architecture/auth.md#notes-about-the-design and it seems relevant for this issue. (I assume it's true but I've never tested it.) #2838 about `:AllowSignup` is related, of course.

**Comment by djbrooke** [comment]
@eaquigley and I met to discuss this so that I could become familiar with the current state. The potential value and impact of this increases as more folks enable Shib. Will revisit for a future release.

**Comment by pdurbin** [comment]
Last week @pameyer indicated that SBGrid may be interested in disabling local login once ORCID login is working (#3338).

**Comment by djbrooke** [comment]
This is out of scope for #3338 (and the 4.6 release) and will live on as a separate issue.

**Comment by pdurbin** [comment]
At the [2016-12-07 Helmsley Quarterly Meeting](https://docs.google.com/document/d/1ViZF_7ocIpBf0uROz9x5oUE1WFCB_wnGNmegrzLVJYk/edit?usp=sharing) @scolapasta pointed out that this issue is a probably easy or completely done based on the current work in the 3338-oauth-login and after playing around with the http://localhost:8080/api/admin/authenticationProviders endpoint in 546ae73 I agree. It's done. I think! I just need to document this a bit so I'm pulling this into the Development column at https://waffle.io/IQSS/dataverse

**Comment by pdurbin** [comment]
@scolapasta et al. while working on docs in 13d1d90 I thought of a reason why the code isn't done. I just wrote this:

> "Remote only" mode should be considered experiemental until https://github.com/IQSS/dataverse/issues/2974 is resolved. For now, "remote only" means:
> 
> - Shibboleth or OAuth has been enabled.
> - ``:AllowSignUp`` is set to "false" per the :doc:`config` section to prevent users from creating local accounts via the web interface. Please note that local accounts can also be created via API, and the way to prevent this is to block the ``builtin-users`` endpoint or scramble (or remove) the ``BuiltinUsers.KEY`` database setting per the :doc:`config` section. 
> - The "builtin" authentication provider has been disabled. Note that disabling the builting auth provider means that the API endpoint for converting an account from a remote auth provider will not work.  This is the main reason why https://github.com/IQSS/dataverse/issues/2974 is still open.

A fix could be to add some render logic such that we don't show the "If you already have a Demo Dataverse account, you will need to convert your account." text if there is no builtin provider to switch to. As of 81945b5 it looks like this:

![screen shot 2016-12-19 at 1 41 26 pm](https://cloud.githubusercontent.com/assets/21006/21324709/e8874b96-c5f0-11e6-9cab-1a415cd22298.png)

**Comment by pdurbin** [comment]
In 98e6ec4 (3338-oauth-login branch which is pull request #3539) I made enough changes to satisfy @pameyer 's "remote only" use case, I believe. In short, I believe "remote only" an be supported **if you only have a single remote auth provider** such as ORCID. The moment you introduce a second remote auth option your users will probably be disappointed that they can't switch between them due to how the builtin provider must be enabled to convert a user from ORCID to builtin so that the user can convert herself from ORCID to Google (or whatever). I put this in QA but I expect that the real solution for "remote only" for us to implement #3487 to sidestep the need to convert one remote account to another.

See the "Auth Modes: Local vs. Remote vs. Both" section for what I added in the commit above: http://guides.dataverse.org/en/3338-oauth-login/installation/config.html#auth-modes-local-vs-remote-vs-both

The main code change I added is to **not** show the suggestion to convert your account if you have deleted the builtin auth provider.

**Comment by kcondon** [comment]
Tested remote only mode, works, closing.

**Comment by xoroz** [comment]
Hello all,
sorry to bring this back up but is it posibile to leave only Remote Auth enabled?
I have tried but did not work

Ref. 
https://github.com/IQSS/dataverse/issues/2974 
http://guides.dataverse.org/en/latest/installation/oauth2.html?highlight=authenticationproviderrow 


shib.json
{ 
"id":"builtin", 
"factoryAlias":"BuiltinAuthenticationProvider", 
"title":"Dataverse Local", 
"subtitle":"Datavers' Internal Authentication provider", 
"factoryData":"", 
"enabled":false
}, 
{ 
"id":"shib", 
"factoryAlias":"shib", 
"enabled":true 
} 
curl -X POST -H 'Content-type: application/json' --upload-file shib.json http://localhost:8080/api/admin/authenticationProviders

**Comment by xoroz** [comment]
tried this way 

curl  http://localhost:8080/api/admin/authenticationProviders/builtin/enabled
curl -H "Content-type: application/json"  -X POST -d"false" http://localhost:8080/api/admin/authenticationProviders/builtin/:enabled

curl  http://localhost:8080/api/admin/authenticationProviders/builtin/enabled
curl -X PUT -d shib http://localhost:8080/api/admin/settings/:DefaultAuthProvider

almost worked.. but became very slow.. maybe its something else

**Comment by pdurbin** [comment]
@xoroz hi! I'm sorry your having trouble. It sounds like the documentation should be improved. Can you please open a new issue about this?
