### ISSUE TITLE
User Guide: Add section about remote authentication (experimental)

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#2975]
Need to add a section about remote authentication into the user guide

**Comment by pdurbin** [comment]
@eaquigley In 21bd0e8 I improved the Shibboleth section of the Installation Guide and the change can be previewed at http://guides.dataverse.org/en/2939-shib/installation/shibboleth.html . Please read through the top part as I tried to keep it high level (local vs. remote, etc.).

Please make your commit(s) to the [2939-shib](https://github.com/IQSS/dataverse/tree/2939-shib) branch. Thanks!

**Comment by pdurbin** [comment]
@eaquigley please note that there is some new feedback from @bencomp in #2953 that relates to the User Guide.

**Comment by pdurbin** [comment]
@eaquigley I just deployed b6c638d (a fix for #3011) to https://shibtest.dataverse.org so if you want to grab screenshots you can. It looks like this:

![log_in_-_root_dataverse_-_2016-03-15_16 02 23](https://cloud.githubusercontent.com/assets/21006/13792281/7fb8e0a2-eac7-11e5-86d6-0728534147b3.png)

Or do you need the Harvard Identity Provider (IdP) rather than the TestShib IdP? Are you blocked on getting the screenshots you need?

**Comment by pdurbin** [comment]
@eaquigley I just made a pull request at #3025 and in the RFI checklist I indicated that me checking "All code checkins completed" is blocked on this issue. Should we simply remove the references to the screenshots? As of 15e15d1 http://guides.dataverse.org/en/2939-shib/user/account.html looks like this with broken links to images:

![account_creation_ _management_ _dataverse org_-_2016-03-16_16 27 15](https://cloud.githubusercontent.com/assets/21006/13827641/19213736-eb94-11e5-8867-c4434f4a210d.png)

**Comment by eaquigley** [comment]
@pdurbin I went onto beta today to take the screenshots and it doesn't seem to be the most recent shibb code (text wasn't correct). what machine is running it so i can complete this section of the guide?

**Comment by pdurbin** [comment]
The shibtest server per https://github.com/IQSS/dataverse/issues/2975#issuecomment-196999243

**Comment by eaquigley** [comment]
@pdurbin excellent! thanks. i'll need your help with getting the screenshot for converting a local account to a shibb account.

also, i'm noticing issues on shibtest.dataverse.org where i keep getting thrown to this:

![screen shot 2016-03-16 at 5 30 55 pm](https://cloud.githubusercontent.com/assets/5922904/13829342/e0a0254e-eb9c-11e5-9705-7b1a67e144c0.png)

**Comment by pdurbin** [comment]
Oh. Sorry. If you publish the root dataverse that error should go away.

**Comment by pdurbin** [comment]
@eaquigley as we discussed I'm quite happy with the screenshots you added (thanks!) and removed the note about this being a blocker for pull request #3025 but I understand if you want to do some more reformatting. Please just pass this issue to me when you're done and I'll make sure it makes its way to QA. Thanks!!

**Comment by pdurbin** [comment]
@eaquigley heads up the the login page just changed slightly. I added the "Learn More" link to the User Guide you asked for. You can see a screenshot at https://github.com/IQSS/dataverse/issues/2951#issuecomment-199414962

**Comment by kcondon** [comment]
OK, user guide section in place, reviewed. Closing. @eaquigley I've reviewed this and looks good so closing. Phil mentioned a slight change to log in text in case you wanted to update your screen shot. Seems ok to me.
