### ISSUE TITLE
API should return proper HTTP codes

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#298]
---

Author Name: **Michael Bar-Sinai** (@michbarsinai)
Original Redmine Issue: 3712, https://redmine.hmdc.harvard.edu/issues/3712
Original Date: 2014-03-14
Original Assignee: Gustavo Durand

---

API endpoints:

## NOT converted yet

* Access
* Browse (what's that?)
* Config
* DatasetFieldServiceApi
* index
* mail
* meta
* Search
* SearchFields

## Converted

* Dataverses
* Users
* roles
* permissions
* Metadatablocks
* Datasets

## Deleted

* Files

---

Redmine related issue(s): [3385](https://redmine.hmdc.harvard.edu/issues/3385)

---

**Comment by michbarsinai** [comment]
To be converted:
* Access - DONE
* Browse (what's that?)
* Config
* DatasetFieldServiceApi
* index
* mail
* meta
* Search
* SearchFields

**Comment by michbarsinai** [comment]
Current state: Meta is the only one left.

**Comment by pdurbin** [comment]
@michbarsinai sorry but as I mentioned in 7cde601 I'm not ready to change from String to Response in api/Config.java

**Comment by michbarsinai** [comment]
Current state:
apiConfig has to stay as is for now.
meta will probably be merged to Access. At any event, can't change until TowRavens are updated as well.

Assign to @scolapasta - this can be closed, I think.
