### ISSUE TITLE
DataCite DOI: when dataset fails to publish due to DataCite inaccessible, dataset card seems to show published.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2983]
Edge case, should only happen when DataCite is unavailable when dataset is published. In this case, the dataset page shows an error happened and retains the draft and unpublished tags but the dataset card seems to have updated the tags so does not appear to be unpublished. The card also appears in listing to an anonymous user as if public but permissions still as draft (prompts log in). So, seems like it is being indexed anyway even though publish failed.

**Comment by sekmiller** [comment]
Moved the re-index to after the DOI update so that if the DOI update fails the re-index will not be done.

**Comment by sekmiller** [comment]
Fix checked into branch

**Comment by kcondon** [comment]
OK, works, not indexed on failure, indexed on success. Closing.
