### ISSUE TITLE
DataCite DOI: Some DOI create/registration failures dump 404 html page to logs.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2988]
I've tested a few failure cases and found the server log is logging the 404 html page:

1. Bad DataCite service URL
2. Duplicate identifier on create in cache table.
3. Duplicate identifier on publish at DataCite.

It ends up dumping pages and pages of text to the log file, not very usefule.

**Comment by sekmiller** [comment]
Have not been able to recreate this one.  Please add specific steps that will cause it.

**Comment by kcondon** [comment]
There is an error reported and we can live with it. Closing.
