### ISSUE TITLE
DataCite DOI: When encountering a duplicate, does not select a new value, just fails.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2989]
This may be a requirements issue rather than a bug but the FRD says, "(Part of the DOI reservation process is to make sure that identifiers are not duplicated.  If a duplicate is discovered, another identifier will be submitted. This will continue until a unique identifier is minted.) "

What actually happens is it just fails and never allows for trying another identifier. Gives an error:
 Error – This dataset may not be published because the DOI update failed. Please contact Dataverse Support for assistance. Please contact support.

**Comment by sekmiller** [comment]
Fix checked into branch

**Comment by kcondon** [comment]
Now it just pretends to succeed but doesn't -indexes and published locally but does not register/update DataCite record.

**Comment by sekmiller** [comment]
Fix has been checked in. As we discussed the publish will retry with a new identifier when one already exists on the DataCite site.

**Comment by kcondon** [comment]
Works, closing.
