### ISSUE TITLE
DataCite DOI: Error message does not indicate cause as being DOI outage.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2990]
This may be a problem with how the requirements were specified rather than a bug but the FRD says, " If during this process there are repeated API failures, most likely caused by the DataCite API being unresponsive, the dataset will not be published and the user will be notified that the publish command failed due to DOI outage."

The actual error does not indicate an outage nor that it may be temporary and to try again:
"Error – This dataset may not be published because the DOI update failed. Please contact Dataverse Support for assistance. Please contact support. "

**Comment by sekmiller** [comment]
Here is the message I added (based on what I paraphrased from Kevin's suggestion:

This dataset may not be published because the DataCite Service is inaccessible. Please try again. If the issue persists, please contact Dataverse Support for assistance.

**Comment by sekmiller** [comment]
Fix checked into branch

**Comment by kcondon** [comment]
This is what it actually says, maybe one too many contact supports:
 Error – This dataset may not be published because the DataCite Service is inaccessible. Please try again. If the issue persists, please contact Dataverse Support for assistance. Please contact support.

**Comment by mheppler** [comment]
@kcondon + @sekmiller -- please let me and @eaquigley review this message text. If we are going to include the "please contact Dataverse Support for assistance", then I can wire that up to open the Contact Dataverse Support popup. Assign this ticket to me and I will get it done this afternoon.

**Comment by kcondon** [comment]
Sure, I had already sent the initial message to Liz but did not hear back.



________________________________

**Comment by kcondon** [comment]
For the record, the popup was already coded into the original message. Stephen changed the text but had double contact, one without the popup.



________________________________

**Comment by mheppler** [comment]
Cleaned up error msg on Dataset pg related to persistentURL services down while publishing.

- Moved error msgs from `PublishDatasetCommand.java`, to the `Bundle.properties`.
- Added link to DataCite Status Page.
- Fixed broken popup links for Dataverse Support in `messages.xhtml`.

**Comment by kcondon** [comment]
Passing to Stephen at his request.

**Comment by mheppler** [comment]
Thank you, @sekmiller!!

**Comment by sekmiller** [comment]
This is good to test now

**Comment by kcondon** [comment]
Works, closing

**Comment by kevinworthington** [comment]
We repeatedly experience this message and traced the cause to the description field having html. The fix we've found is to update the DOIDataCiteRegisterService.java file line 49 with:

`metadataTemplate.setDescription(dataset.getLatestVersion().getDescription().replaceAll("<[^>]*>", ""));`

**Comment by pdurbin** [comment]
@kevinworthington thanks for providing a possible solution.
