### ISSUE TITLE
DataCite DOI: Investigate how to handle dataset Destroy.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#2994]
@posixeleni @sekmiller 
Although destroy is a rarely used option it does happen. How should this be handled via DataCite? We currently do nothing special -the record remains active.

Eleni will check with DataCite to see if they have a recommended approach, Stephen will investigate the DataCite API to see whether there is something he can used to remove the record.

**Comment by sekmiller** [comment]
There's no way to delete an identifier via the API.  I did add a method to delete the record from the api cache if a draft is deleted before publish.

**Comment by sekmiller** [comment]
Added Code to delete row from cache in the case of delete prior to publish.  Handling of destroy published dataset may be deferred as we have not heard from DataCite on the approach we should take. As noted above - there is no way to delete a published identifier - it can be set to "inactive"

**Comment by sekmiller** [comment]
Still no response from Martin at DataCite.

**Comment by kcondon** [comment]
Closing since there is no real impact to user and will reopen if deemed important.
