### ISSUE TITLE
BARI tabular: SLD files for Joins are Points instead of Polygons

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3003]
codebase: WorldMap legacy

---
#### Scenario
Create a view by joining:
   - an existing polygon layer (example Boston zip codes) and 
   - a tabular file (e.g. with a Boston zip column)

#### Bug

Resulting map layer displays points instead of polygons even though underlying database view has correct MULTIPOLYGON in the *the_geom* column

#### Underlying issue

The SLD for the join layer is incorrect. In this scenario:

The default SLD type is:
```xml
<sld:PointSymbolizer>
```

Instead of:
```xml
<sld:PolygonSymbolizer>
```

Fix: Copy the SLD from the original layer and update the ```<sld:Name>``` appropriately

**Comment by raprasad** [comment]
This is not necessarily ideal--especially if the original layer has styling

**Comment by kcondon** [comment]
@raprasad can you update this ticket when you get a chance?
