### ISSUE TITLE
Files Tags: Cancel does not prevent tags from being added when adding tags and files on dataset create, edit..

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3004]
Have tested with FF.
1. create dataset and before save
2. add files
3. add tags, click cancel
4. notice tags still are added.

**Comment by kcondon** [comment]
There is also an issue on editing a draft only version, seems to cancel but on save adds tag:
1. create dataset, add files, save.
2. edit metadata, all files.
3. add tags for a file, click cancel, no tag appears on edit page.
4. save and see tag was added.

**Comment by mheppler** [comment]
This isn't a simple "Cancel" button that merely has a `hide()` function to close the popup. There is some backend logic from the `actionListener="#{EditDatafilesPage.clearFileMetadataSelectedForTagsPopup()}"` attribute.

I'm passing to @sekmiller to look into this further.

**Comment by sekmiller** [comment]
Fix Checked into Branch/Pull Request

**Comment by kcondon** [comment]
Tested both scenarios with FF, Chrome, and MSEdge. Works, closing
