### ISSUE TITLE
bari tabular: Classify rules for SLD do not include PolygonSymbolizer

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3006]
Classification isn't working for files created via tabular join.

The classify rules include correct filters, but not colors/styles to apply to those filters.

Example urls:

### no PolygonSymbolizer*

  - url: ```http://localhost:8080/geoserver/rest/sldservice/geonode:j_happiness_zip_codes/classify.xml?reverse=&attribute=happiness&ramp=Custom&endColor=%23f16913&intervals=3&startColor=%23fff5eb&method=quantile```
  - Rules snippet:

```xml
<sld:Rule>
    <sld:Title> &gt; 65.0 AND &lt;= 75.0</sld:Title>
    <ogc:Filter>
        <ogc:And>
            <ogc:PropertyIsGreaterThan>
                <ogc:PropertyName>happiness</ogc:PropertyName>
                <ogc:Literal>65.0</ogc:Literal>
            </ogc:PropertyIsGreaterThan>
            <ogc:PropertyIsLessThanOrEqualTo>
                <ogc:PropertyName>happiness</ogc:PropertyName>
                <ogc:Literal>75.0</ogc:Literal>
            </ogc:PropertyIsLessThanOrEqualTo>
        </ogc:And>
    </ogc:Filter>
</sld:Rule>
```

### PolygonSymbolizer appears

  - url: ```http://localhost:8080/geoserver/rest/sldservice/geonode:social_dis_hb1/classify.xml?reverse=&attribute=SocDis_203&ramp=Custom&endColor=%23f16913&intervals=3&startColor=%23fff5eb&method=quantile```
  - Rules snippet:  *Note inclusion of ```PolygonSymbolizer``` within the ```Rule``` tag

```xml
<sld:Rule>
    <sld:Title> &gt; 1.6152 AND &lt;= 5.9643</sld:Title>
    <ogc:Filter>
        <ogc:And>
            <ogc:PropertyIsGreaterThan>
                <ogc:PropertyName>Violence_3</ogc:PropertyName>
                <ogc:Literal>1.6152</ogc:Literal>
            </ogc:PropertyIsGreaterThan>
            <ogc:PropertyIsLessThanOrEqualTo>
                <ogc:PropertyName>Violence_3</ogc:PropertyName>
                <ogc:Literal>5.9643</ogc:Literal>
            </ogc:PropertyIsLessThanOrEqualTo>
        </ogc:And>
    </ogc:Filter>
    <sld:PolygonSymbolizer>
        <sld:Fill>
            <sld:CssParameter name="fill">#670000</sld:CssParameter>
        </sld:Fill>
        <sld:Stroke/>
    </sld:PolygonSymbolizer>
</sld:Rule>
```

Check with CGA.  Is layer missing some type of info?  Tried making join a table instead of a view, etc.
Do attribute types matter?  e.g. "int" vs "xsd:int"

**Comment by capooti** [comment]
do you have an online sample?

**Comment by mbertrand** [comment]
It might have something to do with the layer's geometry type or default style.  I just looked for geonode:social_dis_hb1 and geonode:j_happiness_zip_codes from the examples above but couldn't find them in geoserver.

**Comment by raprasad** [comment]
@capooti @mbertrand, getting the online sample going now.  

Yes, @mbertrand, both issues are there:

(1) SLD default type was incorrect.  I temporarily "fixed" ** that by making a copy of the SLD from the "target layer".  Note, this may have not have been the underlying problem.  

(2) Also, the "geometry type" is incorrects
Just noted the following, see screen shot:

The "table_join" code is here:  https://github.com/cga-harvard/cga-worldmap/blob/legacy-rp-update/geonode/contrib/datatables/utils.py#L268

![mozilla_firefox_and_mozilla_firefox_and_dataverse_rt_ _exchange__0_messages_](https://cloud.githubusercontent.com/assets/1036060/13709134/5580ed92-e780-11e5-908c-766de40b08de.png)

---

** Re: SLD copying. Was a temp fix that works as long as the target SLD has doesn't have attributes rules.

**Comment by raprasad** [comment]
Online samples are here:

### Shapefile Layer

  - Mass Census:  http://23.21.172.243/data/geonode:boston_census_tract_o2w
  - layer attributes: http://23.21.172.243/geoserver/rest/sldservice/geonode:boston_census_tract_o2w/attributes.xml
  - classify service (SLD generation)
  http://23.21.172.243/geoserver/rest/sldservice/geonode:boston_census_tract_o2w/classify.xml?reverse=&attribute=SHAPE_AREA&ramp=Custom&endColor=%23f16913&intervals=3&startColor=%23fff5eb&method=quantile

### Join Layer (at first creation)
  - http://23.21.172.243/data/geonode:j_cbg_annua_boston_ce
  - layer attributes:  http://23.21.172.243/geoserver/rest/sldservice/geonode:j_cbg_annua_boston_ce/attributes.xml
  - classify service (SLD generation): http://23.21.172.243/geoserver/rest/sldservice/geonode:j_cbg_annua_boston_ce/classify.xml?reverse=&attribute=trash_long&ramp=Custom&endColor=%23f16913&intervals=5&startColor=%23fff5eb&method=jenks

**Comment by capooti** [comment]
I am getting an authentication required popup when opening the layer
attributes and classify service links.
Could you provide details?

On Fri, Mar 11, 2016 at 2:42 PM, Raman Prasad <notifications@github.com>
wrote:

> Online samples are here:
> Shapefile Layer
>
>    - Mass Census:
>    http://23.21.172.243/data/geonode:boston_census_tract_o2w
>    - layer attributes:
>    http://23.21.172.243/geoserver/rest/sldservice/geonode:boston_census_tract_o2w/attributes.xml
>    - classify service (SLD generation)
>    http://23.21.172.243/geoserver/rest/sldservice/geonode:boston_census_tract_o2w/classify.xml?reverse=&attribute=SHAPE_AREA&ramp=Custom&endColor=%23f16913&intervals=3&startColor=%23fff5eb&method=quantile
>
> Join Layer (at first creation)
>
>    - http://23.21.172.243/data/geonode:j_cbg_annua_boston_ce
>    - layer attributes:
>    http://23.21.172.243/geoserver/rest/sldservice/geonode:j_cbg_annua_boston_ce/attributes.xml
>    - classify service (SLD generation):
>    http://23.21.172.243/geoserver/rest/sldservice/geonode:j_cbg_annua_boston_ce/classify.xml?reverse=&attribute=trash_long&ramp=Custom&endColor=%23f16913&intervals=5&startColor=%23fff5eb&method=jenks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IQSS/dataverse/issues/3006#issuecomment-195517141>.
>



-- 
Paolo Corti
Geospatial software developer
web: http://www.paolocorti.net
twitter: @capooti
skype: capooti

**Comment by raprasad** [comment]
re: @capooti, appears to be due to older postgis (1.5) running

**Comment by raprasad** [comment]
Also related to postgis update.
