### ISSUE TITLE
File Tags: Remove unused custom tags checkbox missing from edit file metadata/ edit tags popup view.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3007]
Remove unused tags was implemented in #2925 and works but presently is only available in batch view. This ticket is to implement it in the edit file metadata, edit tags popup.

**Comment by kcondon** [comment]
This issue is included in #2991 but we may want to treat them separately?

**Comment by eaquigley** [comment]
Closing as this is a duplicate of #2991.
