### ISSUE TITLE
File Tags: Tabular file tags not appearing in popup before save, tabular tags not updated in popup in edit file metadata view.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3008]
1. Add tabular file, ingest it, draft version of dataset (not sure it matters as long as file ingested).
2. Select tabular file, edit->metadata
3. Click edit tags for tabular file, select one or all tabular tags, notice none appear in popup.
4. Save and usually tags are saved.
5. Edit, add or deselect tabular tags and notice the displayed tags are not updated in the popup but on save they were apparently updated.

This works in the batch popup btw.

**Comment by sekmiller** [comment]
Fixed in the 2391 File Tags Edit Branch

**Comment by sekmiller** [comment]
Checked into Branch/Pull Request

**Comment by kcondon** [comment]
Tested with FF, Chrome, MSEdge, works, closing.
