### ISSUE TITLE
API: add endpoint for listing users

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#3009]
[In chat yesterday](http://irclog.iq.harvard.edu/dataverse/2016-03-08#i_32462) we discussed adding an API for listing users. Technically, I already stubbed something out in 7ea6a01 but in a standup meeting this morning I advocated to make it more real, especially so I can explain how to list users before attempting to convert one from being a Shibboleth user to being a local/builtin user (#2915). I'm playing around with what the JSON would look like and I'm thinking of something along these lines:

    {
      "id": 1,
      "identifier": "@dataverseAdmin",
      "displayName": "Dataverse Admin",
      "firstName": "Dataverse",
      "lastName": "Admin",
      "email": "dataverse@mailinator.com",
      "superuser": true,
      "affiliation": "Dataverse.org",
      "position": "Admin",
      "persistentUserId": "dataverseAdmin",
      "authenticationProviderId": "builtin"
    },
    {
      "id": 9,
      "identifier": "@aiden.cook",
      "displayName": "Aiden Cook",
      "firstName": "Aiden",
      "lastName": "Cook",
      "email": "aiden.cook@example.com",
      "superuser": false,
      "persistentUserId": "https://idp.example.com/idp/shibboleth|5e97f768",
      "authenticationProviderId": "shib"
    }

**Comment by pameyer** [comment]
@pdurbin - is the "@" coming from the export, or something that's part of the identifiers in your test set?

aka - "@dataverseAdmin" vs "dataverseAdmin"?

**Comment by pdurbin** [comment]
@pameyer it's sort of a long story. See #1151 #1445 #1705 and probably other issues. The answer to your specific question is that `authenticatedUser.getIdentifier()` adds the `@` sign. The `@` sign isn't in the `authenticateduser` table.

Otherwise, I hope the data returned looks ok and useful. I did go ahead and push 0b212f8 which is the code I was playing with to dump the JSON above.

**Comment by pdurbin** [comment]
Passing to QA. The new API endpoint is documented as `curl -H "X-Dataverse-key: $API_TOKEN" http://localhost:8080/api/admin/authenticatedUsers` at http://guides.dataverse.org/en/2939-shib/installation/shibboleth.html#converting-shibboleth-users-to-local and shows JSON as described in the first comment/description above. This feature is in pull request #3025.

**Comment by kcondon** [comment]
OK, works, closing.
