### ISSUE TITLE
File Tags: Batch update should be incremental, not specify all tags as a set.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3010]
This issue already exists but in testing related tags issues it was identified as being incorrect and not useful. 

An example:
3 files, each has their own tag: file1, file2, file3.
Curator wants to add one common tag to all three files while preserving their own unique tags.
Curator batch edits the three files, adds tag "common" and saves.
Now, all three files have the union of all file tags: each has tags, file1,file2,file3,common.

Expected and desired behavior is to incrementally update file tags: 
after adding the "common" tag above, files should have the following tags:
1. file1, common
2. file2, common
3. file3, common

Reviewed with Gustavo and @eaquigley . Liz felt this was really important to fix for v4.3.

**Comment by kcondon** [comment]
@eaquigley @scolapasta 

Update:
Discussed more broadly the tags batch update feature with Gustavo and it seems the batch delete/remove tags and batch add tags have different requirements and so make this more complicated, needing some design/ ux input.

For adding:
A curator may want to add a single new tag to an arbitrary list of files that may have other unique tags. So, for batch it seems like we would want to just add the single tag and *not* make all selected files have the union of existing tags.

For deleting:
A curator may want to remove a particular tag from an arbitrary set of files that may also have unique tags. In order to remove the tag they need the ability to deselect an existing tag and unless we want to insist a curator choose exactly those files  that have the tag in common, we need to show the union of all tags across selected files and allow someone to remove a particular tag. This is sort of how the feature works right now but for both adding and removing/deleting.

So, if we make adding incremental only by only showing tags selected during this popup's session, we also need a way to display existing tags for removal.

**Comment by kcondon** [comment]
Potential use cases that may impact design and need evaluation:
1. Making tags the same for a list of files:
1.1 Assigning the same tags to a list of files with no assigned tags (make all tags the same)
1.2 Making a list of files all have the same tags when they have been previously assigned different tags.
2. Incrementally changing (add or remove) tags:
2.1 Assigning the same tag(s) to a list of files that already have tags assigned that should remain unique to those files.
2.2 Removing the same tag(s) from a list of files that also have unique tags, preserving the unique tags.

**Comment by djbrooke** [comment]
@eaquigley and I met to discuss this so that I could become familiar with the current state. This will be prioritized for a future release, but back to the unassigned pool for now!

**Comment by TaniaSchlatter** [comment]
Discussed in the design meeting Aug. 17: need discussion around batch editing and how displayed to the user – what is selected, what the user is applying to what files. Need to define expected rules
