### ISSUE TITLE
Shibboleth: Update any mentions of Institution to be Institutional

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#3011]
In this commit: https://github.com/IQSS/dataverse/commit/8e7d93a492a94d76059eb59cf7af9aff00426e04 I added the institutional log in section to the user guide.

From here on out, we should refer to this feature as Institutional Log In. Anywhere in the app that says Institution instead of Institutional when referring to this feature needs to be updated.

**Comment by pdurbin** [comment]
@eaquigley I think I got them all in b6c638d.

**Comment by pdurbin** [comment]
Passing to QA. You can even see screenshots at http://guides.dataverse.org/en/2939-shib/user/account.html

Instead of "Institutional Log In" we now say "Institution Log In" which is gooder English. ;)

The fix is in pull request #3025.

**Comment by kcondon** [comment]
Looks good, closing
