### ISSUE TITLE
DataCite DOI: Reference data script fails on new installation

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3012]
You are now connected to database "dvndb" as user "postgres".
dvndb=# \i /tmp/dataverse/dataverse-24-add-DataCite-DOI-Support/scripts/database/reference_data.sql 
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
INSERT 0 1
psql:/tmp/dataverse/dataverse-24-add-DataCite-DOI-Support/scripts/database/reference_data.sql:30: ERROR:  syntax error at or near "CREATE"
LINE 2: CREATE UNIQUE INDEX index_authenticateduser_lower_email ON a...
        ^
CREATE INDEX
CREATE INDEX
INSERT 0 1

**Comment by sekmiller** [comment]
Checked in the fix to DataCite Branch....

**Comment by kcondon** [comment]
Thanks Stephen, for the record, this was not a problem with DataCite branch, just a minor typo in the refdata script that got into develop branch.

**Comment by kcondon** [comment]
Works, closing.
