### ISSUE TITLE
User Guide contains Harvard-specific information such as 2 GB file upload limit

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#3015]
There's Harvard-specific information in the User Guide. As @shlake pointed out via [the mailing list](https://groups.google.com/d/msg/dataverse-community/DDIGmmRe8oE/xMLMjOuxBgAJ) http://guides.dataverse.org/en/4.2.4/user/dataset-management.html#file-handling-uploading says "All file formats are supported, up to 2GB per file for the Harvard Dataverse. Please contact support@dataverse.org if you need to upload a file that is larger than 2GB. You can also add descriptions and categorize each of them by adding tags."

That 2 GB limit comes from http://guides.dataverse.org/en/4.2.4/installation/config.html#maxfileuploadsizeinbytes and is specific to an installation of Dataverse. In the User Guide we shouldn't be encouraging users of other installations to contact support@dataverse.org (which goes to https://help.hmdc.harvard.edu ) for a limit that may not even apply to them.

@mcrosas asked me to go create this issue and I mentioned that we **could** expose the `:MaxFileUploadSizeInBytes` value in the GUI (or API) somehow so researchers who are "shopping" for a place to upload data could know what the limits are before they even bother to create an account. Maybe there could be a page at https://demo.dataverse.org/about or https://demo.dataverse.org/limits ? I dunno. Something to think about but out of scope for this issue, which should be about fixing the docs.

**Comment by sbarbosadataverse** [comment]
Hi:
Can we change it to say they should contact us to discuss how to separate
their dataset into manageable components?
 I agree we are not going to help upload larger files, but we can discuss
the best option for using we what offer.

On Fri, Mar 11, 2016 at 11:51 AM, Philip Durbin <notifications@github.com>
wrote:

> There's Harvard-specific information in the User Guide. As @shlake
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_shlake&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=sIAoPIcXEQRgfqyULqZfUh_qw11-NlpIc1217_eGwIE&s=TjOB2fi0JhsAQJqEkevYhNzVhkBcvD3iOjav-T-vBKA&e=>
> pointed out via the mailing list
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__groups.google.com_d_msg_dataverse-2Dcommunity_DDIGmmRe8oE_xMLMjOuxBgAJ&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=sIAoPIcXEQRgfqyULqZfUh_qw11-NlpIc1217_eGwIE&s=ibpXY4TB5QNH1hes0joir98keiZZDFpYEMLtdrrLneo&e=>
> http://guides.dataverse.org/en/4.2.4/user/dataset-management.html#file-handling-uploading
> <https://urldefense.proofpoint.com/v2/url?u=http-3A__guides.dataverse.org_en_4.2.4_user_dataset-2Dmanagement.html-23file-2Dhandling-2Duploading&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=sIAoPIcXEQRgfqyULqZfUh_qw11-NlpIc1217_eGwIE&s=qJVW_SmJYZbg2tgz9CRDytnH8b69ipJXnbdhdGXAWM8&e=>
> says "All file formats are supported, up to 2GB per file for the Harvard
> Dataverse. Please contact support@dataverse.org if you need to upload a
> file that is larger than 2GB. You can also add descriptions and categorize
> each of them by adding tags."
>
> That 2 GB limit comes from
> http://guides.dataverse.org/en/4.2.4/installation/config.html#maxfileuploadsizeinbytes
> <https://urldefense.proofpoint.com/v2/url?u=http-3A__guides.dataverse.org_en_4.2.4_installation_config.html-23maxfileuploadsizeinbytes&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=sIAoPIcXEQRgfqyULqZfUh_qw11-NlpIc1217_eGwIE&s=ULQqr7-fPmtT3XXsgkKw-mOXJkjqUfDOs2Bfr6E6tUY&e=>
> and is specific to an installation of Dataverse. In the User Guide we
> shouldn't be encouraging users of other installations to contact
> support@dataverse.org (which goes to https://help.hmdc.harvard.edu ) for
> a limit that may not even apply to them.
>
> @mcrosas
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mcrosas&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=sIAoPIcXEQRgfqyULqZfUh_qw11-NlpIc1217_eGwIE&s=MY17jdgXVGFxNOH4XI-ORTgSe782e8E_4_ehx8BQAKw&e=>
> asked me to go create this issue and I mentioned that we *could* expose
> the :MaxFileUploadSizeInBytes value in the GUI (or API) somehow so
> researchers who are "shopping" for a place to upload data could know what
> the limits are before they even bother to create an account. Maybe there
> could be a page at https://demo.dataverse.org/about
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__demo.dataverse.org_about&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=sIAoPIcXEQRgfqyULqZfUh_qw11-NlpIc1217_eGwIE&s=OZvFo9o5k9xFYj7zflVdpZt1bt4pef5pat-tkt8y7e4&e=>
> or https://demo.dataverse.org/limits
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__demo.dataverse.org_limits&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=sIAoPIcXEQRgfqyULqZfUh_qw11-NlpIc1217_eGwIE&s=UH6_GBVF2-CG5fUp37RTn0AO9TQbfroMTziOc8RqJ5g&e=>
> ? I dunno. Something to think about but out of scope for this issue, which
> should be about fixing the docs.
>
> —
> Reply to this email directly or view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_issues_3015&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=sIAoPIcXEQRgfqyULqZfUh_qw11-NlpIc1217_eGwIE&s=eENs4GxPXS69EOe4UZEijI4dNOx6FU6ANvv3M6TALVA&e=>
> .
>



-- 
Sonia Barbosa
Manager of Data Curation, IQSS Dataverse Network
Manager of the Murray Research Archive, IQSS
Data Science
Harvard University

Dataverse 4.0 is now available for use!
http://dataverse.harvard.edu

All test dataverses should be created  in 4.0 Demo!
http://dataverse-demo.iq.harvard.edu/

Join our Dataverse Community!
https://groups.google.com/forum/#!forum/dataverse-community

**Comment by eaquigley** [comment]
The :MaxFileUploadSizeInBytes is already being displayed in the UI, as one can see here:

![screen shot 2016-03-11 at 12 08 43 pm](https://cloud.githubusercontent.com/assets/5922904/13709449/1565a8fe-e782-11e5-8b21-4d1bf252d8ce.png)

I would recommending changing the User Guide to say something like, "File upload limit size varies based on Dataverse installation. It is viewable in the text above where files are uploaded. If you have further questions, contact support for that installation by clicking on the Support link in the header."

I can take this ticket to do this.

@pdurbin @sbarbosadataverse @mcrosas

**Comment by shlake** [comment]
I have taken out the Harvard-specific links in our UVa Dataverse Guides; pointing to our support team, not Harvard's.

Here is our UVa Dataverse User Guide: http://uvalib.github.io/dataverse-docs/

I update them via sphinx and then move them to github. Do a redirect on the "User Guides" URL.

But I see that the UI display from @eaquigley previous comment has a link to the User Guide, which breaks for us because I have done (lots) of redirecting.

What other places in the UI are there links to the User Guide (specific sections in the user guide)?

Looks like we need to re-think how we are doing our User Guides.

**Comment by pdurbin** [comment]
@shlake [on the mailing list](https://groups.google.com/d/msg/dataverse-community/pH_XT1NBQyk/UkYfgumvAgAJ) I mentioned that the API token page and links to the **API** Guide. I'm not sure of where all the links to the User Guide are. You might find at least a partial list here: https://github.com/IQSS/dataverse/blob/v4.2.4/src/test/java/edu/harvard/iq/dataverse/util/BundleUtilTest.java

**Comment by pdurbin** [comment]
@eaquigley heads up that @landreev and I are making doc changes as part of #3017 so you may want to check with @kcondon to see if he'd like to you to make small changes in that branch. We're hoping to merge that pull request into develop soonish. Otherwise, you'll need to make a new branch, I guess.

**Comment by eaquigley** [comment]
@shlake I went in and updated the user guide so it no longer says to email support@dataverse.org. In the Tabular Data Files section of the Dataset Management User Guide, there are mentions to file size. Wanted to check with @shlake if thats okay to stay in there.

**Comment by shlake** [comment]
@eaquigley thanks. I'll keep an eye on the changes. I have already taken the existing guides and made UVa customizations (email addresses, file size plus others). So what ever you have in the guides that are Harvard specific, I can change, re-run sphinx and update our UVa guides. You can find them here (still doing a few tweaks): http://uvalib.github.io/dataverse-docs/

**Comment by kcondon** [comment]
OK, looks good, closing.
