### ISSUE TITLE
This is a Mother Issue for all the installer-related fixes and improvements addressed in 4.3

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#3016]
The "child issues" addressed are: 

#2980 
#1455 
#1201 
#1167 
#1097 

On top of these, the following has been addressed: 

Removed the annoying long "sleep" statements; the installer should be taking a couple of minutes less time to run now. 

It now takes care of the  Jhove configuration file and schema location. 

Improved the messaging and diagnostics. 

Some large chunks of unnecessary output is now being hidden from the user (for example - the multiple screenfulls of output from the metadata block ingests). 

Worked with Phil to address some security issues, I believe we have finally closed some particularly bad security holes that we used to leave open out of the box. 

Updated accordingly and somewhat improved the installation guide.

(there are probably more small things I can't remember right now). 

Most importantly, rewrote the installer so that it doesn't require running it as root. 
Overall, it doesn't necessarily make the install process easier for the user. It's a bit of a "you get some, you lose some". The prerequisites section on Postgres got simplified a little bit; since it's no longer necessary to separately configure access on the local sockets connections... But then there is a bit of extra work - since now the user needs to supply the Postgres admin password, or set the access level to "trust" on localhost, in order to allow the installer to create the database and user...

It has however simplified the script internally and made it more robust. There are now fewer opportunities for things to go wrong. Switching between root and regular user there was occasionally causing permission errors and security warnings. 

QAing the installer is notoriously difficult. I'm almost positive some user with some unusual setup will be able to break it. I'm willing to even maybe give my direct email in the release notes, telling people to contact me if they are running into problems with the installer. 

But even if they have to send a support request through normal channels, installer script fixes are usually pretty easy. Unlike bugs in the app, we don't have to tell them to wait till the next release - usually I can just change a couple of lines in the script and give it back to them, here, try this again.

**Comment by kcondon** [comment]
OK, sleep was addressed
Jhove was addressed
messaging has changed
output was reduced
installation guide was updated

need to verify:
security changes
running as user other than root

**Comment by kcondon** [comment]
api endpoints automatically blocked

**Comment by kcondon** [comment]
confirmed can run installer as user that is not root. Closing.

**Comment by landreev** [comment]
Just adding this to the issue, for posterity. 
These are some, mostly minor, improvements added based on the feedback during testing and QA: 

Issues addressed:

1. Rewrote the parts of the Prerequisites -> Postgres section talking about configuring localhost;
 (made it clear it is being done before the installer run; and just made it more clear overall)

2. Switched the installer to use 127.0.0.1 as the default for postgres address;

3. Removed the "leave blank" from the help text comment, since it can't be left blank;

4. Made the configuration dialogue look better for entries with long help text (extra newlines);

5. Made the installer recognize Postgres versions up to 9.5 as legit;

6. Glassfish dir validation moved to be performed in real time, right when the user enters it;
 (the re-entered value should be saved properly now)

7. Improved the explanation of the siteURL JVM option in the doc; (it was actually kinda explained, in the
explanation for the *previous* option - the fqdn; but I added some extra text.

8. Changed the "Internet Address" in the config dialogue, to FQDN, and/or numeric, if FQDN not available.

9. Moved SMTP (mail) server validation to be immediately performed as entered
(i.e., instead of sending the user back to start over)

10. Fixed the issue causing the warning about the scope of the "exit_status" variable.

Didn't do anything about:

1. Whatever is causing the "syntax deprecated" warning from the glassfish setup script. Whatever it is, it's not fatal;

2. No check for the Java version;

3. No validation for the rserve configuration entered.

(these could be addressed in another release)
