### ISSUE TITLE
Documentation: Missing Link to Appendix in User Guide

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#3023]
Under "Metadata Elements for datasets in this dataverse" user reported missing URL for "appendix (insert link here)"

Link to appendix is: http://guides.dataverse.org/en/4.2.4/user/appendix.html

**Comment by mheppler** [comment]
Also add link to Account Creation & Management pg on the [Dataverse Management](http://guides.dataverse.org/en/4.5.1/user/dataverse-management.html) pg to replace the "(see Create Account)" text.

**Comment by mheppler** [comment]
Also fix layout width issue due screenshots images in the Permissions and Assign Roles sections.

![screen shot 2016-10-06 at 3 55 26 pm](https://cloud.githubusercontent.com/assets/687227/19168369/e0bfe7e4-8bdd-11e6-9596-46ed6dfbaba8.png)

**Comment by mheppler** [comment]
Added missing links to Appendix and Account Creation & Management pgs, plus fixed screenshot image widths on Dataverse Management pg in User Guides.

**Comment by kcondon** [comment]
Appendix link in Dataverse Management section of User Guide fixed.
See Create Account link fixed.
Screenshot sizing fixed.

Closing.
