### ISSUE TITLE
geoconnect: move to stable production server (heroku)

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3024]
original title: _geoconnect: python 2.7 need for pandas on old centos version_

---

Since this ticket was written, Heroku became available _and_ the HMDC application servers*  are being sunsetted (*geoconnect is currrently located).

- [x] move to Heroku

**Comment by raprasad** [comment]
```
cd /usr/lib64/httpd/modules/
cp /webapps/code/geoconnect/deploy/files/usr/mod_wsgi.so.python2.7 .
```

**Comment by raprasad** [comment]
(This will inevitably be overwritten with an upgrade--need to move to a different server)

**Comment by kcondon** [comment]
@raprasad Would you please update this ticket when you get a chance -what is needed to test and close this?

**Comment by raprasad** [comment]
It's still open.  Will try to prioritize it this week with Len and Gustavo.  e.g., there's  a short term fix and a longer term fix.

**Comment by kcondon** [comment]
@raprasad I'm taking this out of QA since it shows up in my queue, thanks.

**Comment by raprasad** [comment]
- [ ] S3 backend - factor out to use either local file paths or S3 backend (url)
  - [x] basic file load
    - [x] set backend to either local file system or S3
       - Currently no need to do both.  Will there ever be a need for Geoconnect?  Probably not.
  - [x] tabular join processing
  - [ ] tabular lat/lng processing
  - [ ] shapefile processing
     - Can't use "directories" on S3
  - [ ] Update "stale" data remover to make sure temp S3 file are removed

**Comment by raprasad** [comment]
- tabular join processing and lat/lng processing are basically switching pd.read_csv to use the AWS url instead of the path.

**Comment by raprasad** [comment]
- [ ] Need to force iframe url to 'https', comes across as http

**Comment by raprasad** [comment]
- [ ] Update "stale" data remover to make sure temp S3 file are removed

**Comment by raprasad** [comment]
- [ ] update tests that use local dirs

**Comment by raprasad** [comment]
![Uploading Map_Data_File.png…]()

**Comment by raprasad** [comment]
last check-in example script to remove data from s3 bucket

**Comment by raprasad** [comment]
- [ ] "install from scratch" for heroku
- [ ] logs

**Comment by raprasad** [comment]
- [ ] logging
  - have serious errors emailed to ADMINS

**Comment by raprasad** [comment]
- [ ] update stale data remover to clear JoinTargetInformation. (e.g. the layers retrieved from WorldMap and saved in the db)

**Comment by raprasad** [comment]
- [ ] remove datatables cdn--copy file locally
- [ ] add page listing join targets

**Comment by raprasad** [comment]
- [ ] bug: static assets not showing when DEBUG is off

**Comment by raprasad** [comment]
Bug appears to be fixed.  Added something to stackoverflow about it.

**Comment by raprasad** [comment]
- [ ] bug found: url to map legend image  using http:// instead of https://

---

![manage_map](https://cloud.githubusercontent.com/assets/1036060/23068211/c4e30a20-f4f0-11e6-82c2-b115d59b8632.png)

**Comment by raprasad** [comment]
legend url fixed in last commit.

---

![manage_map](https://cloud.githubusercontent.com/assets/1036060/23069151/5a017580-f4f4-11e6-9663-45b4af3d3b55.png)

**Comment by raprasad** [comment]
Logging is now working.

Once this passes Code Review/QA; next step would be re-assigning the ```http://geoconnect.datascience.iq.harvard.edu/``` url

**Comment by raprasad** [comment]
Code review task is to run through this set-up: https://github.com/IQSS/geoconnect/blob/3024-heroku/heroku_setup.md

**Comment by landreev** [comment]
@raprasad @kcondon 
OK, I was able to follow Raman's instruction. I have made a few edits to it. They are minor, but may save a couple of minutes of figuring things out. 
I don't have direct edit permission on the geoconnect github repo. So I made a pull request with my changes: https://github.com/IQSS/geoconnect/pull/122
Raman please take a look and see if they make sense. 

I used the "geoconnect-test" app name that's used as an example throughout the instruction. I have deleted the app once I was done testing. I'm assuming we'll want a different name for the actual stable prod. deployment.

**Comment by landreev** [comment]
@kcondon 
Kevin, if you run into any problems following the instruction, please let me know.

**Comment by raprasad** [comment]
Move checklist
  - [ ] Choose move day
  - [ ] Copy production data, specifically the "Registered Dataverse" models
  - [ ] Coordinate domain name assignment with Evan
    - e.g. point "geoconnect.datascience.iq.harvard.edu" to final Heroku app
  - [ ] Test it once the domain is moved
  - [ ] Decommission HMDC server (after 1 week)

**Comment by landreev** [comment]
@kcondon 
couple of extra notes on following the steps in the instruction: 

Under "Dashboard set-up": 
1. Install the Heroku CLI... - the Heroku site offers 2 ways of installing the app. I used homebrew. If you don't have/like homebrew, they also have an installer - but I haven't tried it myself. 
With homebrew, the installation worked without a problem. BUT, to actually use heroku, I had to modify my PATH, like this: PATH=/usr/local/bin:$PATH; export PATH
- otherwise heroku was getting the wrong version of ruby and couldn't run. 
Your mileage may vary...

2. Under "Configure additional settings" -&gt; SECRET_KEY - there are 2 methods for creating  that "large random string". I used the "code snippet" method: follow the url, download the source, save it as  django-secret-keygen.py  and run it as "python  django-secret-keygen.py". It doesn't work out of the box however; you need to edit it and move the line "from __future__ ..." to the top of the file, above the "import" lines (that's described in the first comment on that github page)

**Comment by raprasad** [comment]
- Coordinating DNS move with @pdurbin

**Comment by raprasad** [comment]
@kcondon : your updates have been incorporated into the heroku install doc.  For the secret key, put an updated code snippet right into the doc

**Comment by pdurbin** [comment]
@raprasad please let me know the DNS name of the new server that's on Heroku. Based on https://gist.github.com/raprasad/810b9ecaea6f02acbb9d0183362440a0 it looks like the DNS entry to change is http://geoconnect.datascience.iq.harvard.edu . I'm a bit surprised that HTTPS is not being used: `curl: (7) Failed to connect to geoconnect.datascience.iq.harvard.edu port 443: Connection refused`

**Comment by raprasad** [comment]
Steps for adding a certificate to heroku
  - https://devcenter.heroku.com/articles/ssl-endpoint#dns-and-domain-configuration

**Comment by pdurbin** [comment]
@raprasad for step 1, "Purchase an SSL certificate from your SSL provider", you might find this helpful: https://github.com/IQSS/dataverse/blob/v4.6/scripts/deploy/phoenix.dataverse.org/cert.md

**Comment by pdurbin** [comment]
@raprasad I created certs based on the CSR you sent. You'll probably need both the cert and the intermediate cert, which you can download from here:

 - as X509 Certificate only, Base64 encoded: https://cert-manager.com/customer/InCommon/ssl?action=download&sslId=705171&format=x509CO
- as X509 Intermediates/root only, Base64 encoded: https://cert-manager.com/customer/InCommon/ssl?action=download&sslId=705171&format=x509IO

I don't know how to use an intermediate cert with Heroku but here's what I do for Apache:

https://github.com/IQSS/dataverse/blob/v4.6/doc/shib/shib.md#re-configure-apache-to-use-the-new-cert

**Comment by pdurbin** [comment]
I just updated the CNAME. Here's the before and after:

## Before

```
$ dig +noall +answer geoconnect.datascience.iq.harvard.edu
geoconnect.datascience.iq.harvard.edu. 10800 IN	CNAME dvnweb-vm7.hmdc.harvard.edu.
dvnweb-vm7.hmdc.harvard.edu. 300 IN	A	140.247.115.127
```

## After

```
$ dig +noall +answer geoconnect.datascience.iq.harvard.edu
geoconnect.datascience.iq.harvard.edu. 10800 IN	CNAME geoconnect-prod.herokuapp.com.
geoconnect-prod.herokuapp.com. 300 IN	CNAME	us-east-1-a.route.herokuapp.com.
us-east-1-a.route.herokuapp.com. 8 IN	A	23.23.114.129
```

**Comment by pdurbin** [comment]
## After, take 2

```
$ dig +noall +answer geoconnect.datascience.iq.harvard.edu
geoconnect.datascience.iq.harvard.edu. 10800 IN	CNAME geoconnect.datascience.iq.harvard.edu.herokudns.com.
geoconnect.datascience.iq.harvard.edu.herokudns.com. 60	IN A 23.23.128.123
geoconnect.datascience.iq.harvard.edu.herokudns.com. 60	IN A 107.21.206.81
geoconnect.datascience.iq.harvard.edu.herokudns.com. 60	IN A 184.72.248.171
geoconnect.datascience.iq.harvard.edu.herokudns.com. 60	IN A 23.21.77.86
geoconnect.datascience.iq.harvard.edu.herokudns.com. 60	IN A 23.23.117.228
geoconnect.datascience.iq.harvard.edu.herokudns.com. 60	IN A 54.243.85.55
geoconnect.datascience.iq.harvard.edu.herokudns.com. 60	IN A 50.19.93.247
geoconnect.datascience.iq.harvard.edu.herokudns.com. 60	IN A 75.101.145.225
```

**Comment by pdurbin** [comment]
## After, take 3

```
$ dig +noall +answer geoconnect.datascience.iq.harvard.edu
geoconnect.datascience.iq.harvard.edu. 10800 IN	CNAME tokushima-96974.herokussl.com.
tokushima-96974.herokussl.com. 1913 IN	CNAME	elb096291-436501406.us-east-1.elb.amazonaws.com.
elb096291-436501406.us-east-1.elb.amazonaws.com. 60 IN A 107.21.97.159
elb096291-436501406.us-east-1.elb.amazonaws.com. 60 IN A 23.21.201.5
elb096291-436501406.us-east-1.elb.amazonaws.com. 60 IN A 54.235.173.194
```

**Comment by kcondon** [comment]
Am able to save and map shape files, tabular data using lat/long and Boston admin data. Basic service seems functional. Closing.

**Comment by raprasad** [comment]
SSL documentation notes added here: https://github.com/IQSS/geoconnect/blob/master/heroku_setup.md#adding-ssl-to-heroku
