### ISSUE TITLE
Draft Version URL Problem in "My Data"

### ISSUE THREAD

**Issue by shlake** [IQSS/dataverse#3038]
The draft version of a previously published dataset has an incorrect URL (or better said, it does not have the "Draft" version of the URL) when displayed in "My Data".

From this search, when "shlake" is logged on, I see:
https://dataverse-demo.iq.harvard.edu/dataverse/harvard?q=&fq0=authorName_ss%3A%22Lake%2C+Sherry%22&types=dataverses%3Adatasets&sort=dateSort&order=desc

![screen shot 2016-03-28 at 10 17 42 am](https://cloud.githubusercontent.com/assets/3809325/14088154/e5f05d80-f4fb-11e5-88b2-e720650705a4.png)

Link to the 1st one above (Draft) in this list goes to (which is what I expected):

https://dataverse-demo.iq.harvard.edu/dataset.xhtml?persistentId=doi:10.5072/FK2/NSLLSQ&version=DRAFT

BUT if I go to “My Data” (image below) the link for both versions (Draft & published) go to the same (URL) which is not the Draft URL.

https://dataverse-demo.iq.harvard.edu/dataset.xhtml?persistentId=doi:10.5072/FK2/NSLLSQ

![screen shot 2016-03-28 at 12 13 41 pm](https://cloud.githubusercontent.com/assets/3809325/14088168/f78173fe-f4fb-11e5-9c34-3d67b8daa478.png)

**Comment by shlake** [comment]
Still a problem in 4.8.4

**Comment by pdurbin** [comment]
@shlake thanks for staying on top of this and adding a version number.

**Comment by shlake** [comment]
And still a problem in 4.11 - as seen on demo.dataverse.org.

As seen in "MyData":
Both links to the dataset go to the "published" version. I expected the one with "Draft" label to go to the Draft version.

![Screen Shot 2019-03-27 at 9 45 32 AM](https://user-images.githubusercontent.com/3809325/55081044-86888380-5075-11e9-92cd-6938b80aaea9.png)

As seen on the "home" page:
The dataset with "Draft" label goes to the draft version and the other goes to the published version (as expected):
![Screen Shot 2019-03-27 at 9 50 58 AM](https://user-images.githubusercontent.com/3809325/55081262-e67f2a00-5075-11e9-85e2-ec529de2aa77.png)

**Comment by pdurbin** [comment]
@shlake thanks for the update. We discussed this issue (briefly) as a group yesterday.

**Comment by djbrooke** [comment]
Hey @shlake - we need to re-evaluate My Data as a whole instead of trying to fix individual issues as they come up. Since it's different than the usual view, we can expect more and more work to keep it in sync. This is not sustainable. I'll create an issue and edit this comment to add a link.

@scolapasta - we should set this up as a tech hours discussion in the next few weeks. Let me know if there are UI considerations.

**Comment by mheppler** [comment]
@shlake, with only a few short business days til the 6th annual Dataverse Community Meeting (June 17-19), it is my great honor to present you with THIS pull request #6969 and this awesome image of a trophy that only exists digitally, as a special recognition/achievement award of some sort for your many years of contributions like this issue, to our lil open source project.

![dataversecup2020](https://user-images.githubusercontent.com/687227/84032902-0989b700-a966-11ea-9598-ae8a754c7583.png)

Which reminds me, I should take this opportunity to remind everyone to registration for #Dataverse2020 is open using the [Registration Form](https://www.google.com/url?q=https%3A%2F%2Fharvard.az1.qualtrics.com%2Fjfe%2Fform%2FSV_3gzr27UzDaW0rAx&sa=D&sntz=1&usg=AFQjCNH5LkQVmYUuTQvIgMg3lXAijHRZCw). Please register before June 12th!

**Comment by shlake** [comment]
Thanks, @mheppler
