### ISSUE TITLE
My Data: Permissions granted by Shib groups do not appear on My Data

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3041]
Individual shib user permissions appear on My Data but those granted by shib group membership do not appear. 

1. Assign admin permission to published dv to all testshib group.
2. Log in as myself shib user, go to my data, see no data.
3. Assign admin permission to myself to that dv, refresh my data for myself and see dv.

Explicit group perms do appear and even assigning a shib user to an explicit group works.

**Comment by pdurbin** [comment]
To work on this issue, I would recommend (from branch that #3025 is based on) :

## Create group

curl http://localhost:8080/api/admin/groups/shib -X POST -H 'Content-type:application/json' --upload-file doc/sphinx-guides/build/html/_static/installation/files/etc/shibboleth/shibGroupTestShib.json

## Assign role

In the GUI, like normal

## Log in with a "testshib" user

curl http://localhost:8080/api/admin/settings/:DebugShibAccountType -X PUT -d TESTSHIB1

Visit <http://localhost:8080/shib.xhtml> in a browser.

**Comment by sekmiller** [comment]
Update checked into shib branch

**Comment by sekmiller** [comment]
Fix is available in shib branch

**Comment by kcondon** [comment]
This is working. Saw a separate issue relating to not showing / indexing child objects when assigned to a group. Will open in a new ticket. This issue existed in 4.3.
