### ISSUE TITLE
Data Visualization: Allow data depositors to create and host an interactive visualization based on the data.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3043]
This was requested by a partner in RT 234109:

Background: A colleague of mine ... is interested in not only hosting a dataset for a University-related project, but they would also like to create and host an interactive visualization based on the data. Specifically, they would like to use D3js as the basis for their data visualization.

Question: When a user creates an account to host a dataset through Harvard Dataverse, does it include a space—either a page or a site—where the user can provide a "front door" or landing page that contextualizes the data? If so, can external javascript be referenced in that space to facilitate hosting a D3js-enabled visualization?

**Comment by pdurbin** [comment]
Anyone interested in this issue may want to participate in this Tuesday's community call because Scholars Portal will be giving a demo of their new "DDI Explorer" app. For details on how to call in, please see https://groups.google.com/d/msg/dataverse-community/Zpib-uCIG1g/Rg9tJGieBAAJ

**Comment by djbrooke** [comment]
I'll close this for now. We can build specific explore (and soon preview) tools for specific file types. These can include visualizations.

**Comment by pdurbin** [comment]
In many cases, a custom site is built outside of Dataverse to tell the story of the data with a custom visualization. My favorite example is from @garthg and can be found at http://www.yourhumblepetitioners.com/mapview/antislaveryma (screenshot below) via http://www.yourhumblepetitioners.com

I've been playing the video a lot the past could weeks as we've talked about visualizations. Here's a screenshot:

![Screen Shot 2019-10-02 at 5 24 59 PM](https://user-images.githubusercontent.com/21006/66083269-edfa2100-e539-11e9-8ae4-2a07cc76d97c.png)

**Comment by garthg** [comment]
Thanks for the shoutout, @pdurbin !
