### ISSUE TITLE
Account Information: whitespace as part of fields, particularly email address is saved to db, should be trimmed.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3044]
As part of shib testing, needed to check account conversion based on preexisting email address. Found it was not matching due to a copy/ paste leading whitespace issue in email. Phil suggested this was a bug in the account creation/ account info process: should trim whitespace from email before saving to db.

Not sure whether this should be applied to other using info fields but email is used as an identifier so seems reasonable.

**Comment by pdurbin** [comment]
I'm proposing a fix in pull request #3121 so I'm moving this to QA.

**Comment by kcondon** [comment]
This was fixed in pull request, closing.
