### ISSUE TITLE
Add "Laboratory" and "Research Project" To Dataverse Categories

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#3046]
Requested from the Helmsley project we need to add two new Dataverse Categories:

"Laboratory"
"Research Project"

cc / @pameyer @bmckinney

**Comment by pdurbin** [comment]
This issue is on the list of priorities at https://docs.google.com/a/hkl.hms.harvard.edu/spreadsheets/d/10t4oD25Zk5-EPxeuebSQne04tWbs5ZoZiGPZQOoKn2I/edit?usp=sharing

**Comment by bmckinney** [comment]
See pull request https://github.com/IQSS/dataverse/pull/3070

**Comment by kcondon** [comment]
Works, closing.
