### ISSUE TITLE
Citation Metadata: Add Affiliation and Identifier for Contributors

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#3048]
Discovered an oversight in the citation metadata where the contributors field is missing "Contributor Affiliation" and "Contributor Identifier" (ORCID). This will also need to be added for other fields which have individuals listed (ex. Depositor).

**Comment by ChrisBaers** [comment]
At DANS we would love to see an ORCID also for contributor. Would it be an idea to have a more generic flied for 'person' with different roles (eg DataCite roles) like: Contributor, Data collector, Project Leader etc? Of course combined with an ORCID.

**Comment by jggautier** [comment]
Hi @ChrisBaers. There are conversations in the DataCite metadata forums that I think are very relevant to this issue, but without having this conversation complicated by what's being discussed there, I'd like to better understand you're idea about a more generic 'person' field.

As of Dataverse v5.9, the Contributor field lists 17 types of contributors: 1) Data Collector, 2) Data Curator, 3) Data Manager, 4) Editor, 5) Funder, 6) Hosting Institution, 7) Project Leader, 8) Project Manager, 9) Project Member, 10) Related Person, 11) Researcher, 12) Research Group, 13) Rights Holder, 14) Sponsor, 15) Supervisor, 16) Work Package Leader and 17) Other.

Are you suggesting that the Contributor field could be retitled "Person" and that that field would have the same 17 types plus a new type called "Contributor"?

**Comment by ChrisBaers** [comment]
HI Julian,

 

No, what you describe it pretty much what I meant. These roles (in combination with an ORCID) would be very helpful.

 

 

All the best,

Chris Baars

 

Senior Information Systems Officer

+31 6 233 80 622

***@***.***

werkdagen: | MA | DI | DO | VRIJ |

 

DANS: nationaal expertisecentrum en repository voor onderzoeksdata

***@***.***

dans.knaw.nl

 

DANS is een instituut van de Koninklijke Nederlandse Akademie van Wetenschappen (KNAW) en de Nederlandse Organisatie voor Wetenschappelijk Onderzoek (NWO).

 

From: Julian Gautier ***@***.***>
Reply to: IQSS/dataverse ***@***.***>
Date: Thursday, 3 February 2022 at 19:40
To: IQSS/dataverse ***@***.***>
Cc: Chris Baars ***@***.***>, Mention ***@***.***>
Subject: Re: [IQSS/dataverse] Citation Metadata: Add Affiliation and Identifier for Contributors (#3048)

 

Hi @ChrisBaers. There are conversations in the DataCite metadata forums that I think are very relevant to this issue, but without having this conversation complicated by what's being discussed there, I'd like to better understand you're idea about a more generic 'person' field.

As of Dataverse v5.9, the Contributor field lists 17 types of contributors: 1) Data Collector, 2) Data Curator, 3) Data Manager, 4) Editor, 5) Funder, 6) Hosting Institution, 7) Project Leader, 8) Project Manager, 9) Project Member, 10) Related Person, 11) Researcher, 12) Research Group, 13) Rights Holder, 14) Sponsor, 15) Supervisor, 16) Work Package Leader and 17) Other.

Are you suggesting that the Contributor field could be retitled "Person" and that that field would have the same 17 types plus a new type called "Contributor"?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by pdurbin** [comment]
Related:

- #8904

**Comment by pdurbin** [comment]
Closing in favor of this one:

- #8904
