### ISSUE TITLE
Demo dataverse: add link in "account creation" notification that directs "testing" to demo site

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#3049]

**Comment by eaquigley** [comment]
Assigning to myself to write the update for this notification.

**Comment by eaquigley** [comment]
The bundle needs to be updated in line 130 for more text to be added. I'm not sure how the welcome email is updated as that is not in the bundle. Additionally, I don't want to actually add the text to the bundle as it will need a link and I don't want to mess it up and accidentally destroy the links already in it.

This is what it should say:

Welcome to {name of installation} Dataverse! Get started by adding or finding data. Have questions? Check out the Dataverse User Guide. Want to try out Dataverse? Check out our Demo Site {insert link to demo.dataverse.org}.

@sbarbosadataverse does that text update work for you?

**Comment by sbarbosadataverse** [comment]
@eaquigley can't be more direct that "all testing of dataverse features should take place in demo?"

**Comment by eaquigley** [comment]
@sbarbosadataverse how about this:

Welcome to {name of installation} Dataverse! Get started by adding or finding data. Have questions? Check out the Dataverse User Guide. Want to test out Dataverse features? Use our Demo Site {insert link to demo.dataverse.org}.

**Comment by sbarbosadataverse** [comment]
Better! Thanks

On Thu, May 5, 2016 at 3:47 PM, Elizabeth Quigley <notifications@github.com>
wrote:

> @sbarbosadataverse
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sbarbosadataverse&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=Sf85vkqVq84-QjeHFjuRFZr_UqMWc6cY3NQfQWbIndo&s=q0edamT6Cy8ONHFwB025vWs_lTkyUvy2LiU7tWqhgXg&e=>
> how about this:
>
> Welcome to {name of installation} Dataverse! Get started by adding or
> finding data. Have questions? Check out the Dataverse User Guide. Want to
> test out Dataverse features? Use our Demo Site {insert link to
> demo.dataverse.org}.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_issues_3049-23issuecomment-2D217257227&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=Sf85vkqVq84-QjeHFjuRFZr_UqMWc6cY3NQfQWbIndo&s=K4dGrQG26E0L1Xh2qAXmFyEPgGq5nQTcBrI-0tghx7g&e=>
>



-- 
Sonia Barbosa
Manager of Data Curation, IQSS Dataverse Network
Manager of the Murray Research Archive, IQSS
Data Science
Harvard University

Dataverse 4.0 is now available for use!
http://dataverse.harvard.edu

All test dataverses should be created  in 4.0 Demo!
http://dataverse-demo.iq.harvard.edu/

Join our Dataverse Community!
https://groups.google.com/forum/#!forum/dataverse-community

**Comment by eaquigley** [comment]
@scolapasta can you please assign this to the developer who will do this? It also needs to be added to the create account email. It's scheduled for 4.4.

**Comment by sekmiller** [comment]
@eaquigley
The New Account Welcome Email is in the bundle (around line 238 -depending on which branch you are in) It just has a link to the User guide.

notification.email.welcome=

Welcome to Dataverse! Get started by adding or finding data. Have questions? Check out the User Guide at {0}/{1}/user/ or contact Dataverse Support for assistance.

Would you care to suggest a modification?

Thanks

**Comment by eaquigley** [comment]
@sekmiller 

Can you add "Want to test out Dataverse features? Use our Demo Site {insert link to demo.dataverse.org}." as the last sentence.

thanks!

**Comment by sekmiller** [comment]
@eaquigley @sbarbosadataverse 
Do we want other installations to be able to set their demo environment or are we OK with all of them using our Demo Dataverse?

**Comment by eaquigley** [comment]
@sekmiller I'm fine with it not be configurable! 

@sbarbosadataverse

**Comment by sekmiller** [comment]
Fix checked into the branch created for this ticket.

**Comment by kcondon** [comment]
@eaquigley @sekmiller 
Email and notification messages are different, neither has support info (should it?) and email shows actual links and one is not clickable.

email:
Hello,
Welcome to Dataverse! Get started by adding or finding data. Have questions? Check out the User Guide at http://guides.dataverse.org/en/4.3.1/user/ or contact Dataverse Support for assistance. Want to test out Dataverse features? Use our Demo Site at https://demo.dataverse.org.

Thank you,
The Dataverse Project

notification:
Welcome to Root Dataverse! Get started by adding or finding data. Have questions? Check out the User Guide. Want to test out Dataverse features? Use our Demo Site.May 25, 2016 5:23 PM EDT

**Comment by eaquigley** [comment]
@kcondon i'm confused, in the notification are there no links behind the User Guide and Demo Site text? Also, if I am remembering correctly, the emails are difficult to customize or something like that for other installations so we weren't having support@dataverse.org in them. @sekmiller @scolapasta please clarify if I have this wrong.

**Comment by kcondon** [comment]
@eaquigley OK, when I copied and pasted into github it did some funny things with links. I'll forward you my email, the demo link is not clickable in email. Both are clickable links in notification, just that the email had a mention of support and notification does not.

**Comment by sekmiller** [comment]
Take a period off the end of the Bundle text to make the link work properly

**Comment by sekmiller** [comment]
Fix pushed to the branch.

**Comment by kcondon** [comment]
Works, closing.
