### ISSUE TITLE
File Permissions: role not assigned contact support BUG; user is actually assigned

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#3050]
Go to file permissions; type in user name, select name, select all files, hit "grant"
error message below, but user is successfully assigned. Haven't seen this bug in a while.

<img width="1744" alt="screen shot 2016-03-31 at 3 15 23 pm" src="https://cloud.githubusercontent.com/assets/8322346/14188058/19b35ca8-f754-11e5-839f-b792f6cf0620.png">

**Comment by kcondon** [comment]
Duplicate of #2641
