### ISSUE TITLE
Index: dataset and file object cards are not shown when role assigned to explicit groups, works with shib groups

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3055]
Affects explicit groups, works with shib groups:
1. assign admin role to published dv that has an unpublished ds with 2 files.
2. see dv card on homepage view and on my data but do not see ds or files.
3. if assign admin role to indvidual user, shib or builtin, see dv, ds, and files.

Update:
Also assigning role to a group directly to an unpublished dataset does not show the dataset card at all.
Granting access to restricted file also does not work with an explicit group, works in my data.

This issue exists in v4.3.
@pdurbin Any chance you can take a quick look to see whether it is a simple fix or something requiring more thought?

**Comment by pdurbin** [comment]
Potential fix but need to make this `roleAssigneeService.getUserGroups` method by @sekmiller public and see what @michbarsinai thinks:

        logger.info("BEGIN finding explicit groups for " + user.getIdentifier());
        List<String> explicitGroups = roleAssigneeService.getUserGroups(user.getIdentifier().substring(1));
        for (String string : explicitGroups) {
            logger.info("found explicit group: " + string);
            sb.append(" OR ");
            sb.append(IndexServiceBean.getGroupPrefix() + string);
            groupsFromProviders = sb.toString();
        }
        logger.info("END finding explicit groups for " + user.getIdentifier());

All this would go after calling `Set<Group> groups = groupService.groupsFor(au, groupsForDvObjectParamCurrentDataverse);` in SearchServiceBean: https://github.com/IQSS/dataverse/blob/v4.3/src/main/java/edu/harvard/iq/dataverse/search/SearchServiceBean.java#L851

@michbarsinai I'm wondering if we can have a `groupService.groupsFor(au)` method where we get back all the user's groups, without having to pass in a dataverse like the method above.

**Comment by sekmiller** [comment]
@pdurbin  If you pass (au, null) you get all groups assigned to the authenticated user.  I used the method that way for shib/ip groups.

**Comment by michbarsinai** [comment]
We could, but note that ExplicitGroups are defined in a context of a Dataverse. So you would not get ALL the groups.

**Comment by sekmiller** [comment]
But it would work for shib/ip groups since they are not in the context of a dv?

**Comment by michbarsinai** [comment]
Shib should be there. IP groups won't, since they are determined by the IP address of the DataverseQuery.

**Comment by pdurbin** [comment]
@michbarsinai @sekmiller @scolapasta I implemented a fix in pull request #3062. Code review is very welcome!

I'm passing this issue to QA.

**Comment by kcondon** [comment]
This works now, closing.

**Comment by pdurbin** [comment]
Pull request #3062 now has merge conflicts. Reopening this issue and giving to @scolapasta for prioritization.

**Comment by pdurbin** [comment]
I resolved the merge conflicts in pull request #3062 and updated the branch to include the fix I made in pull request #3124 which resolves the user id mismatch mystery. Passing to QA.

**Comment by pdurbin** [comment]
To be clear, the fix is in pull request #3062 which is the 3055-get-more-groups branch.
