### ISSUE TITLE
Documentation: Add info on passing log in credentials to configured SMTP server.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3061]
A user installed Dataverse and wanted to use a third party email service that supports SMTP but requires log in credentials. We currently do not support this, this ticket is a request to implement it.
See RT 234442 for more information. The third party service is mailgun.org.

Update: This may be natively supported through additional properties in the Java mail client config. We'll confirm and close if that is the case.

It looks like this can be configured though admin console/ domain.xml:
http://www.hildeberto.com/2010/02/sending-e-mails-with-javamail-on-glassfish-v3.html

**Comment by pdurbin** [comment]
Someone popped into chat today and said at http://irclog.iq.harvard.edu/dataverse/2016-04-19#i_34377 that after initial trouble using Mailgun's SMTP server they got it all working by following http://osama-zienadden.blogspot.com/2012/01/how-to-send-e-mail-using-glassfish.html

There was much rejoicing!

**Comment by djbrooke** [comment]
So.... can we close it? Thanks!

@pdurbin @kcondon

**Comment by pdurbin** [comment]
https://help.hmdc.harvard.edu/Ticket/Display.html?id=234442 has been marked "resolved" so I vote we close it.

**Comment by djbrooke** [comment]
Closed it!

**Comment by kcondon** [comment]
Add info on how to do this to the installation guide.

**Comment by pdurbin** [comment]
I just added this issue to the long list at #2944.

**Comment by pdurbin** [comment]
Today someone asked about this at http://irclog.iq.harvard.edu/dataverse/2016-11-29#i_45534

**Comment by pdurbin** [comment]
@bsilverstein95 as we discussed, please take a look at http://osama-zienadden.blogspot.com/2012/01/how-to-send-e-mail-using-glassfish.html including adding these properties:

![mali28](https://cloud.githubusercontent.com/assets/21006/26652663/a799a134-461e-11e7-8e12-e380a46c4385.png)

**Comment by pdurbin** [comment]
@ferrys said she's take a look as well.

**Comment by pdurbin** [comment]
At https://javabot.evanchooly.com/logs/%23glassfish/2017-06-07 I asked about adding to the `asadmin` command we use.

Currently we use this: https://github.com/IQSS/dataverse/blob/v4.6.2/scripts/installer/glassfish-setup.sh#L245

`./asadmin $ASADMIN_OPTS create-javamail-resource --mailhost "$SMTP_SERVER" --mailuser "dataversenotify" --fromaddress "do-not-reply@${HOST_ADDRESS}" mail/notifyMailSession`

Let's try this:

`./asadmin $ASADMIN_OPTS create-javamail-resource --mailhost "$SMTP_SERVER" --mailuser "dataversenotify" --fromaddress "do-not-reply@${HOST_ADDRESS}" --property=mail.smtp.auth=true:mail.smtp.port=25:mail.smtp.password=$SMTP_PASSWORD mail/notifyMailSession`

Another gist, if that doesn't work: https://gist.github.com/MiloCasagrande/2509214

**Comment by pdurbin** [comment]
As part of this, we should change `MAIL_SERVER` from `mail.hmdc.harvard.edu` to something less Harvard-specific such as `smtp.gmail.com` or whatever we can get to work. Places to change as of the v4.7 tag:

- https://github.com/IQSS/dataverse/blob/v4.7/doc/sphinx-guides/source/_static/util/default.config#L4
- https://github.com/IQSS/dataverse/blob/v4.7/scripts/installer/install#L75

( @michbarsinai can we delete your `asadmin-setup.sh` script at https://github.com/IQSS/dataverse/blob/v4.7/scripts/setup/asadmin-setup.sh ? It hasn't been updated in over three years.)

**Comment by michbarsinai** [comment]
Dunno. Do we have an alternative automated way of setting up Glassfish?

**Comment by pdurbin** [comment]
@michbarsinai yes. Please see the comment that was added to the top of your script three years ago:

```
# STOP!
# DO NOT ADD MORE ASADMIN COMMANDS TO THIS SCRIPT!
# IF YOU NEED TO ADD MORE GLASSFISH CONFIG SETTINGS, ADD THEM 
# TO THE ../installer/glassfish-setup.sh SCRIPT. 
```

😄

**Comment by michbarsinai** [comment]
Should have been deleted 3 years ago, then :-))

**Comment by bsilverstein95** [comment]
Just an update on this, I did manage to narrow down the necessary settings and fields for configuring Gmail SMTP on Dataverse reliably on @ferrys and my own machine(s). Google doesn't give a ton of information on the service but it's still free and still works! 

Planning to document the setup process asap. 📝

**Comment by pdurbin** [comment]
@bsilverstein95 cool. At standup you said that you might not want to touch the installation script. That's fine. If so, please open a new issue to capture what I wrote about `mail.hmdc.harvard.edu` at https://github.com/IQSS/dataverse/issues/3061#issuecomment-311071288

**Comment by pdurbin** [comment]
@bsilverstein95 great work! I made a small tweak at b737d63 but I'm moving this to QA.
