### ISSUE TITLE
Tabular mapping: cron job to remove stale data

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3063]
Separated from #3033 
---

Add functions to delete "stale data".  Run via daily cron job.  Needs scl enable python27, etc, etc

**Comment by raprasad** [comment]
Basic code in last check-in.  See StaleDataRemover

**Comment by djbrooke** [comment]
@raprasad - I'm going to move this to the backlog, but if it should be in some other state feel free to move it! Thanks!

**Comment by raprasad** [comment]
replaced with #3054
