### ISSUE TITLE
Guestbook: Downloaded guestbook data has a couple issues: time=date and commas at end of each line, should not be.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3064]
Guestbook: Downloaded guestbook data has commas at end of each line, should not be.

Also, there is a column in the download data, time, but it shows only date.

Also, custom question column would probably be better listed as question1, answer1, question2, answer 2, etc.

**Comment by sekmiller** [comment]
Fix checked in...

**Comment by kcondon** [comment]
OK, the comma at the end of line is fixed for the download all but not for the download individual guestbook. Also, the other potential issues: time and custom question column name were not addressed.

**Comment by sekmiller** [comment]
Fixed for individual guestbook

**Comment by kcondon** [comment]
Fixed, closing.
