### ISSUE TITLE
Search Card: Lock icon for restricted file remains locked even though granted access.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3065]
When a file card for a restricted file appears in search results, the red lock "locked" icon remains even after access is granted. Works on file tab.

**Comment by mheppler** [comment]
@kcondon was not able to replicate locally in latest and greatest develop branch, or on demo (v. 4.14 build 1326-57a392d).

1. admin granted permission to a restricted file to a user, logged out
2. logged in as said user, filtered search results to see all files, saw green lock icon

![Screen Shot 2019-06-18 at 10 28 32 AM](https://user-images.githubusercontent.com/687227/59692974-17be5080-91b4-11e9-96ef-ed26de1f9b62.png)

**Comment by kcondon** [comment]
works now
