### ISSUE TITLE
Edit Dataset: Tab order for fields/ objects needs to remove labels from tab order and only have data input objects.

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#307]
---

Author Name: **Kevin Condon** (@kcondon)
Original Redmine Issue: 3722, https://redmine.hmdc.harvard.edu/issues/3722
Original Date: 2014-03-14
Original Assignee: Mike Heppler

---

When entering lots of data, such as I am doing to help Liz with the Usability test, it would be nice if tabbing jumped between fields, next field/control, etc so it makes data entry easier. Instead, it includes the field labels in the tab order and that is less useful.

**Comment by scolapasta** [comment]
Per Mikes suggestion, I added the block's index (+1) as a tabIndex to each of the input fields (except the multiple checkboxes like subject, tab index does not appear to be supported by primefaces component, only standard component), the +/- buttons, and the special replication for button.

I added a tabindex of 1000 to the bottom save and cancel.

**Comment by eaquigley** [comment]
WOOHOOOOO this is working perfectly. Closing ticket.
