### ISSUE TITLE
Install: Add CC0 text as custom text to default publish popup.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3075]
To help address a usability issue where folks did not realize the default licensing of published datasets is CC0, Liz asked to add the following text:

"This dataset is being published with the CC0-“Public Domain Dedication” waiver. Learn more about the CC0 waiver here.

To publish with custom Terms of Use, click the Cancel button and go to the Terms tab for this dataset."

This was added directly to our production db:
curl -X PUT -d "This dataset is being published with the CC0-“Public Domain Dedication” waiver. Learn more about the CC0 waiver <a href="http://creativecommons.org/choose/zero/">here</a>.
<br></br>
To publish with custom Terms of Use, click the Cancel button and go to the Terms tab for this dataset.
" http://localhost:8080/api/admin/settings/:DatasetPublishPopupCustomText

Confirmed with Liz this should also be added to our install scripts.

**Comment by sekmiller** [comment]
This seems like a bit of a blunt instrument. There's no coding to determine if the license is CC0 when displaying this message. And adding code to test for this would be problematic since the PublishPopupCustomText could be anything.

**Comment by eaquigley** [comment]
spoke to @sekmiller and we will have the message say,

"By default, datasets in the {insert installation name} Dataverse are published with the CC0 Waiver <insert link to waiver site behind CC0 Waiver>. To publish with custom Terms of Use, click the Cancel button and go to the Terms tab for this dataset."

**Comment by sekmiller** [comment]
Fixed, that is the setup-optional-publish-terms.sh script has been updated to reflect the new disclaimer.
In order to fix production, we need to modify the setting table.  Let me know if you have any questions about the update query required for this.

Fix applied in this branch:
https://github.com/IQSS/dataverse/tree/3049-accout-notification

**Comment by kcondon** [comment]
Works but needs a little attention on line spacing. 3 br's is too many. 2 works.

**Comment by sekmiller** [comment]
Fix is checked into the branch

**Comment by kcondon** [comment]
OK, looks good, closing.
