### ISSUE TITLE
JaCoCo configuration in pom.xml contains typos

### ISSUE THREAD

**Issue by bencomp** [IQSS/dataverse#3076]
The configuration of the [JaCoCo Maven plugin](http://eclemma.org/jacoco/trunk/doc/maven.html) allows options for `dataFile` and `destFile`, but currently has:

```
<plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>0.7.5.201505241946</version>
                <configuration>
                    <destfile>${basedir}/target/coverage-reports/jacoco-unit.exec</destfile>
                    <datafile>${basedir}/target/coverage-reports/jacoco-unit.exec</datafile>
                </configuration>
```

(lower-case `f` in both options).

This causes Maven to ignore the options and use `${basedir}/target/jacoco.exec` instead.

**Comment by pdurbin** [comment]
Bloops! Thanks for pointing this out.

@bencomp do you think fixing this could help use generate code coverage reports for integration tests? It's one of the goals I listed at https://github.com/IQSS/dataverse/issues/2746 and I opened a related issue at https://github.com/pkainulainen/maven-examples/issues/3

Right now https://coveralls.io/github/IQSS/dataverse only shows **unit** tests, not integration tests.

**Comment by bencomp** [comment]
If I read [jacoco:prepare-agent-integration](http://eclemma.org/jacoco/trunk/doc/prepare-agent-integration-mojo.html) correctly, using the right options allows you to use separate files for unit tests and integration tests.

I don't think the problem of JaCoCo not understanding the REST Assured way of doing integration tests is solved this way. Perhaps [Arquillian](http://arquillian.org/) could help, although I have no experience whatsoever with it.

**Comment by bencomp** [comment]
There is an extension to connect to JaCoCo: https://github.com/arquillian/arquillian-extension-jacoco

**Comment by pdurbin** [comment]
@bmckinney has been looking into Arquillian a bit. See https://github.com/bmckinney/bio-dataverse/commit/2f243b1db1ca704a42cd0a5de329083763b7c37a

**Comment by bmckinney** [comment]
I've had good initial success with Arquillian. A couple of caveats: running glassfish 4.x in embedded mode is not possible. Remote and managed mode seem to work fine though.

**Comment by pdurbin** [comment]
I agree this is a bug but so far it's been harmless. Closing.
