### ISSUE TITLE
JsonObjectBuilder incorrect validation in add function

### ISSUE THREAD

**Issue by Alyanorno** [IQSS/dataverse#3078]
The JsonObjectBuilder add method has a bug where if another name in the same scope is added it will overwrite that one with the new one without casting an exception or displaying any error of any kind. The problem is with no check before adding the value to the valueMap which makes it so that the old value overwrites the old one.

Relevant parts are in JsonObjectBuilderImpl method JsonObjectBuilder third line change from:
valueMap.put(name, new JsonStringImpl(value));
to:
if(valueMap.contains(name)) {
    throw new SomeInvalidNameException("Two values cannot have the same name in the same scope");
}
valueMap.put(name, new JsonStringImpl(value));

**Comment by michbarsinai** [comment]
`JsonObjectBuilderImpl` is a class from `org.glassfish.json` class. So not sure we can do much about it...

**Comment by Alyanorno** [comment]
Ah sorry, added the issue right at the end of the work day. My fault! (will delete this and added it in a more suitable place)
