### ISSUE TITLE
Unable to Publish 1st Version of Dataset Using Handle ID

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#3079]
A user with an older unpublished dataset http://hdl.handle.net/1902.1/17082 (using Handle as global id) updated their dataset metadata and when they hit Publish an error message appeared:
 Error – This dataset may not be published because its DOI provider is not supported. Please contact Dataverse Support for assistance. Please contact Dataverse Support for assistance.

**Comment by sekmiller** [comment]
We can actually leave the identifier alone and just use the existing one in EZID.

For a reference query:

select * from dataset where identifier  = '17082';

should return the dataset in question.

This update should do the trick:


UPDATE dataset
   SET  authority='10.7910/DVN', doiseparator='/', 
        protocol='doi'
 WHERE identifier  = '17082';

**Comment by sekmiller** [comment]
Wait - we don't have to register with EZID - we can just update the timestamp on the globalidcreatetime

That's what we did for UCLA a while ago.

update dataset 
set globalidcreatetime = localtimestamp
where  identifier = '17082';

Also for the one that came in last night:

update dataset 
set globalidcreatetime = localtimestamp
where  identifier = '19121';

**Comment by kcondon** [comment]
Using this update to set time=create time:

update dataset ds
set globalidcreatetime=dvo.createdate
from dvobject dvo
where ds.id=dvo.id and (ds.protocol='hdl' and ds.identifier in ('17082','19121'));

**Comment by kcondon** [comment]
@posixeleni @sekmiller OK, this is done for both datasets. I will open a more general ticket to address these issues as a whole.
