### ISSUE TITLE
Shibboleth UI Improvements: Messaging, Formatting, Etc

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#3085]
From today's review with @mcrosas and me:

**Log In Page:**
- Using type in option, the dropdown appears but looks odd, especially on Chrome and Safari (this needs to be fixed):
![screen shot 2016-04-22 at 11 45 25 am](https://cloud.githubusercontent.com/assets/5922904/14750176/6eb93ab2-0891-11e6-8bbc-0284d48cee30.png)

- Add title to local user log in section (rendered only when shib is turned on) that says “Log In with Dataverse Account” - started in 936a5fb

**Create Account Workflow**
- When a user creates an account with shibboleth they should be directed to their account information page (like what happens when converting an account) - done in a32c290

**Convert Account Workflow:**
- Remove the text that says, “Welcome (name)” and replace with "Would you like to convert your Dataverse account to always use your institutional log in?" - done in e195cbb
- Add one more sentence (at the end) in the info block that says “After converting, you will only need to use your institutional log in.” - done in e195cbb

Assigning to @pdurbin to do a first run through of what he can fix before passing to @mheppler to work on any remaining items.

**Comment by pdurbin** [comment]
> Add title to local user log in section (rendered only when shib is turned on) that says “Log In with Dataverse Account”

@eaquigley I added an `h2` tag in 936a5fb and below is how it looks (obviously, it needs cleanup, maybe a grey box for both?) but I think the text should read "Log In with Local Account" to be in line with what is recommended from https://discovery.refeds.org/demo/good/step-two/ which I had researched as part of https://github.com/IQSS/dataverse/issues/794#issuecomment-52221569

![screen shot 2016-04-25 at 2 03 09 pm](https://cloud.githubusercontent.com/assets/21006/14793709/96162458-0aee-11e6-87be-1668c518c89d.png)


![screen shot 2016-04-25 at 1 59 55 pm](https://cloud.githubusercontent.com/assets/21006/14793710/961efbc8-0aee-11e6-915e-e01ff89d7af7.png)

**Comment by eaquigley** [comment]
@pdurbin I actually think to make it flow the same as Institutional Log In it should be Dataverse Account Log In. @mcrosas what do you think?

**Comment by pdurbin** [comment]
I chatted with @kcondon about this. I'm going to pass this issue to @mheppler think about how he'd like the login boxes to look (both grey?) and to see if he has any idea how to fix the dropdown.

**Comment by mcrosas** [comment]
Yes, I like "Dataverse Account Log in"


On Mon, Apr 25, 2016 at 4:12 PM, Elizabeth Quigley <notifications@github.com

**Comment by pdurbin** [comment]
@eaquigley @mcrosas in c979314 I changed it to "Dataverse Account Log In"...

![screen shot 2016-04-26 at 9 02 02 am](https://cloud.githubusercontent.com/assets/21006/14818915/9b52d6d8-0b8d-11e6-9785-67c56d99186a.png)


... but please note that at https://github.com/IQSS/dataverse/issues/3085#issuecomment-214465234 above I'm not talking about the order of the words. I think having the word "local" helps clarify the non-Shibboleth option. In my view, even if you log in via Shibboleth you still have a Dataverse account. The guides at http://guides.dataverse.org/en/2939-shib/user/account.html even say "How to create a new Dataverse account using Institutional Log In." So Shibboleth users have Dataverse accounts.

I don't feel super strongly about all this but enough to write what I've written in this issue I guess. Just some food for thought. Again, I'm influenced mostly by https://discovery.refeds.org/demo/good/step-two/

Interestingly, Trello says to log in via email or username and StackOverflow says to log in via email. Neither uses the word "local":

![screen shot 2016-04-26 at 8 58 43 am](https://cloud.githubusercontent.com/assets/21006/14818865/4882ab18-0b8d-11e6-9892-54ed52b25361.png)

---

![screen shot 2016-04-26 at 8 59 04 am](https://cloud.githubusercontent.com/assets/21006/14818866/4887802a-0b8d-11e6-88c4-65965cbfdbc6.png)

**Comment by mcrosas** [comment]
This looks good, Phil. "local" is not a term that users would understand
(to internal or develop-like).

**Comment by eaquigley** [comment]
@pdurbin, I agree with @mcrosas about local being too internal. The example you mention, to me, is highlighting the importance of having two distinct different areas for logging in via built in or authenticated user, not the language used for the sections.





On Tue, Apr 26, 2016 at 6:19 AM -0700, "Merce Crosas" <notifications@github.com<mailto:notifications@github.com>> wrote:

This looks good, Phil. "local" is not a term that users would understand
(to internal or develop-like).


On Tue, Apr 26, 2016 at 9:02 AM, Philip Durbin <notifications@github.com>
wrote:

> @eaquigley
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_eaquigley&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=n9HCCtgqDPssu5vpqjbO3q4h2g6vMeTOp0Ez7NsdVFM&m=KbUJM7x_-leb8bOXbDFRF0yw2OHM_SAIb2Mki7uoy10&s=3DyONiIvWpAJUnnnwhAn9kHspJ_5_CYMXV7PfgAYOX0&e=>
> @mcrosas
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mcrosas&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=n9HCCtgqDPssu5vpqjbO3q4h2g6vMeTOp0Ez7NsdVFM&m=KbUJM7x_-leb8bOXbDFRF0yw2OHM_SAIb2Mki7uoy10&s=lp4KR3RKI9GRSWUeR4_z-wpzzz2_pnhG2bh0IqIMj9Q&e=>
> in c979314
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_commit_c979314447529014744393848de3dde9554ffa4b&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=n9HCCtgqDPssu5vpqjbO3q4h2g6vMeTOp0Ez7NsdVFM&m=KbUJM7x_-leb8bOXbDFRF0yw2OHM_SAIb2Mki7uoy10&s=97Bs8Hu4N6wRm0Kt6Sl3R6X6SvI3_H3TDsdSVRufM2s&e=>
> I changed it to "Dataverse Account Log In"...
>
> [image: screen shot 2016-04-26 at 9 02 02 am]
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__cloud.githubusercontent.com_assets_21006_14818915_9b52d6d8-2D0b8d-2D11e6-2D9785-2D67c56d99186a.png&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=n9HCCtgqDPssu5vpqjbO3q4h2g6vMeTOp0Ez7NsdVFM&m=KbUJM7x_-leb8bOXbDFRF0yw2OHM_SAIb2Mki7uoy10&s=nptFv2diNE_6IuYufgHBfJ3KN_1OU2Vjz8vMl_qbYcI&e=>
>
> ... but please note that at #3085 (comment)
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_issues_3085-23issuecomment-2D214465234&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=n9HCCtgqDPssu5vpqjbO3q4h2g6vMeTOp0Ez7NsdVFM&m=KbUJM7x_-leb8bOXbDFRF0yw2OHM_SAIb2Mki7uoy10&s=wF2Mnijs3F2ZKZfFbk8KGlpYpQ7oDfQjeclVANU5sjI&e=>
> above I'm not talking about the order of the words. I think having the word
> "local" helps clarify the non-Shibboleth option. In my view, even if you
> log in via Shibboleth you still have a Dataverse account. The guides at
> http://guides.dataverse.org/en/2939-shib/user/account.html
> <https://urldefense.proofpoint.com/v2/url?u=http-3A__guides.dataverse.org_en_2939-2Dshib_user_account.html&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=n9HCCtgqDPssu5vpqjbO3q4h2g6vMeTOp0Ez7NsdVFM&m=KbUJM7x_-leb8bOXbDFRF0yw2OHM_SAIb2Mki7uoy10&s=NCQlHS9kZQfgKrgu94qqlh7v00XcRXvfYcBFqufmch4&e=>
> even say "How to create a new Dataverse account using Institutional Log
> In." So Shibboleth users have Dataverse accounts.
>
> I don't feel super strongly about all this but enough to write what I've
> written in this issue I guess. Just some food for thought. Again, I'm
> influenced mostly by https://discovery.refeds.org/demo/good/step-two/
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__discovery.refeds.org_demo_good_step-2Dtwo_&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=n9HCCtgqDPssu5vpqjbO3q4h2g6vMeTOp0Ez7NsdVFM&m=KbUJM7x_-leb8bOXbDFRF0yw2OHM_SAIb2Mki7uoy10&s=fsCkt-I0YnG0v2dms_lar4HfKsWNeeZCD4UQIhgTHOQ&e=>
>
> Interestingly, Trello says to log in via email or username and
> StackOverflow says to log in via email. Neither uses the word "local":
>
> [image: screen shot 2016-04-26 at 8 58 43 am]
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__cloud.githubusercontent.com_assets_21006_14818865_4882ab18-2D0b8d-2D11e6-2D9892-2D54ed52b25361.png&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=n9HCCtgqDPssu5vpqjbO3q4h2g6vMeTOp0Ez7NsdVFM&m=KbUJM7x_-leb8bOXbDFRF0yw2OHM_SAIb2Mki7uoy10&s=sJ7jh3ELTSbsT7qPHz4_PQKtpufvED3r0BlZ9jQ35MQ&e=>
> ------------------------------
>
> [image: screen shot 2016-04-26 at 8 59 04 am]
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__cloud.githubusercontent.com_assets_21006_14818866_4887802a-2D0b8d-2D11e6-2D88c4-2D65965cbfdbc6.png&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=n9HCCtgqDPssu5vpqjbO3q4h2g6vMeTOp0Ez7NsdVFM&m=KbUJM7x_-leb8bOXbDFRF0yw2OHM_SAIb2Mki7uoy10&s=MWPBbmhz9s8ivprPPyOBxD-VTqIaxcUiFE85r30DxRg&e=>
>
> -
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_issues_3085-23issuecomment-2D214733774&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=n9HCCtgqDPssu5vpqjbO3q4h2g6vMeTOp0Ez7NsdVFM&m=KbUJM7x_-leb8bOXbDFRF0yw2OHM_SAIb2Mki7uoy10&s=QC2jmU5WGIf3oTQBMwoRFld1rdqzoSj7ddXGrXe-T0E&e=>
>

-

**Comment by pdurbin** [comment]
Since both @mcrosas and @eaquigley are happy with the text above the local login (again, I don't care **that** much :smile: ) and because I just created a new separate issue for the ugly dropdown (#3091), I'm moving this issue into QA. Things to test:

Create Account Workflow

- When a user creates an account with shibboleth they should be directed to their account information page (like what happens when converting an account) - done in a32c290

Convert Account Workflow

- Remove the text that says, “Welcome (name)” and replace with "Would you like to convert your Dataverse account to always use your institutional log in?" - done in e195cbb
- Add one more sentence (at the end) in the info block that says “After converting, you will only need to use your institutional log in.” - done in e195cbb

The changes are in pull request #3025.

**Comment by kcondon** [comment]
@eaquigley Just a question: we're asking whether they want to convert their account but we're not really giving them any other option so why ask? It's more like we're saying: Logging in with your institutional account will automatically convert your existing account to always use this log in, Proceed?
