### ISSUE TITLE
API Token: Add as a tab in the my data/notifications/account info page

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#3086]
From today's Shibboleth UI review meeting with @mcrosas and me:

- Put API Token into a tab so account info drop down isn’t there anymore - done in 0e08dca
- Text needs to be updated as well (@eaquigley will add updated text here)
- Edit Account button should no longer render for users logged in through institutional log in once API token has been moved into a tab - done in 0e08dca

Once this is done, both of these issues can be closed (although they seem like duplicates): #1706 #2481 

Also will solve the issue of there being no breadcrumbs on the current API token page.

**Comment by pdurbin** [comment]
@eaquigley I fixed all the items above in 0e08dca with the exception of the updated text. Please let me know when this is available.

This fix also removes the API Token page from the list at #2841 since it's no longer a page. Now it's a tab on the account info page.

**Comment by pdurbin** [comment]
@eaquigley I was telling @kcondon that this issue is ready for QA with the exception of the updated text. Can you please either update https://github.com/IQSS/dataverse/tree/2939-shib or pass this issue back to me with the text? Thanks.

**Comment by pdurbin** [comment]
@kcondon I'm passing this issue to QA so can test the change of having an API Token tab on the account page. No longer is the a separate page just for API Tokens which means that both #1706  and #2481 no longer apply so I put them into QA as well. #2841 no longer applies to API Tokens so I left a note there as well.

The excellent summary by @eaquigley at the top of the issue should be used for testing. Please note that she may have some updated text to include in the future.

**Comment by eaquigley** [comment]
@pdurbin, is the text for this page in the bundle? If so, I'll just update it in the bundle for this branch so no one needs to assist





On Tue, Apr 26, 2016 at 7:41 AM -0700, "Philip Durbin" <notifications@github.com<mailto:notifications@github.com>> wrote:


@kcondon<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_kcondon&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=Y9aY3P6kFFpmMLaYYO_id08dS3gL1xWMQuI2CZ74PoI&m=mvDTTdS0nBbZxuZcwBSGUAujWQUx964_WAROLB2x42Y&s=tOMn6eg7ljsq2trZWIH696tJjlPToqbKnbg--dIl6ig&e=> I'm passing this issue to QA so can test the change of having an API Token tab on the account page. No longer is the a separate page just for API Tokens which means that both #1706<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_issues_1706&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=Y9aY3P6kFFpmMLaYYO_id08dS3gL1xWMQuI2CZ74PoI&m=mvDTTdS0nBbZxuZcwBSGUAujWQUx964_WAROLB2x42Y&s=2BrjWiQC8yIoYrkxEZYTkyaOftWB-JLXpR2epaL0S-o&e=> and #2481<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_issues_2481&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=Y9aY3P6kFFpmMLaYYO_id08dS3gL1xWMQuI2CZ74PoI&m=mvDTTdS0nBbZxuZcwBSGUAujWQUx964_WAROLB2x42Y&s=Z_jsGWJtofU1NyF3PTSDRPhwB9-9MCdvn6fZxZuFNnA&e=> no longer apply so I put them into QA as well. #2841<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_issues_2841&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=Y9aY3P6kFFpmMLaYYO_id08dS3gL1xWMQuI2CZ74PoI&m=mvDTTdS0nBbZxuZcwBSGUAujWQUx964_WAROLB2x42Y&s=LLaujaqOolURYLzGT_fPDd2CX1XjzvJ73zlydX5xZ04&e=> no longer applies to API Tokens so I left a note there as well.

The excellent summary by @eaquigley<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_eaquigley&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=Y9aY3P6kFFpmMLaYYO_id08dS3gL1xWMQuI2CZ74PoI&m=mvDTTdS0nBbZxuZcwBSGUAujWQUx964_WAROLB2x42Y&s=QOiTIDm46ZE-DXQUVx6nsSJpHBbdqpv2YoZ__URAVig&e=> at the top of the issue should be used for testing. Please note that she may have some updated text to include in the future.

-

**Comment by pdurbin** [comment]
@eaquigley yep. Here is the branch and what I assume is the line that you'd like to change: https://github.com/IQSS/dataverse/blob/2939-shib/src/main/java/Bundle.properties#L214

**Comment by kcondon** [comment]
OK, token now a tab, edit button gone, passing to Liz to add text.

**Comment by eaquigley** [comment]
Passing back to @pdurbin to do two things:
- [ ] add API Token as an option under the options when a user clicks on their name in the header
- [ ] in the API token tab, the text that shows before a token is generated isn't in the bundle and should say, "API Token for (insert name) has not been created." (currently says not found)

The other text was updated in the bundle. I changed it from Generate and Regenerate to be Create and Recreate for consistency with the Private URL terminology of using Create

**Comment by pdurbin** [comment]
Ok, I made these changes in pull request #3025:

- 3b5503e API Token: add to header
- 962997e API Token: put "not found" message in bundle and update
- 5dba82d consistent capitalization of "API Token"

Someday @eaquigley and I would like to add a disable/delete button but for now users can reach out to their sysadmins for this: http://guides.dataverse.org/en/4.3/installation/administration.html#deleting-an-api-token

Passing to QA.

**Comment by kcondon** [comment]
Looks good to me. @eaquigley it's on dataverse-internal if you want to take a look. Closing for now but feel free to open if does not meet spec.
