### ISSUE TITLE
prototype json schema endpoints for file metadata (sloan project)

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3088]
- Basic example of storing:
  - JSON metadata schemas
  - JSON metadata with reference to proper schema
- Note: Initial version of this will be using Postgres
- BRD is here: https://docs.google.com/document/d/1NW0l8ceUTnTsrk92XAqqSVO48o7Xnu4H65Vn0Zv8q1E/edit

**Comment by pdurbin** [comment]
I don't believe we are working on this anymore. Closing.
