### ISSUE TITLE
typo: biomedical and customGSD blockv have duplicate enum values

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3094]
Note: very low priority, spotted while working on schema validation
1.  For `studyAssayMeasurementType`, the value `transcription profiling` appears twice
   - https://github.com/IQSS/dataverse/blob/develop/scripts/api/data/metadatablocks/biomedical.tsv#L68
2. For `gsdFacultyName`, the value `Menges, Achim` appears twice
   - https://github.com/IQSS/dataverse/blob/develop/scripts/api/data/metadatablocks/customGSD.tsv#L138

(Very low priority, spotted while working on JSON schema validation.  Didn't immediately correct tsv b/c may need to be corrected in the database)

**Comment by pdurbin** [comment]
Related: tsv metadata block import: add preview mode #2551

**Comment by pdurbin** [comment]
> transcription profiling appears twice

It actually appears four times, some in parenthesis but they all have unique displayName's so I don't think it's a bug: https://github.com/IQSS/dataverse/blob/v4.9.1/scripts/api/data/metadatablocks/biomedical.tsv

It's true that Menges appears twice. Probably a bug. GSD is super Harvard-specific. I guess no one has noticed: https://github.com/IQSS/dataverse/blob/v4.9.1/scripts/api/data/metadatablocks/customGSD.tsv

**Comment by scolapasta** [comment]
Re: the same value appearing with different display values - it should ideally be one value, and we should have a better way to have more "display values" link to the same value. This has been discussed in the context of subjects. (if the display value is not really a s"synonym" it should have a different value)

**Comment by pdurbin** [comment]
> customGSD.tsv

The GSD block is Harvard-specific. We've started moving this to https://github.com/IQSS/dataverse.harvard.edu

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.

**Comment by sbarbosadataverse** [comment]
@cmbz Given that the biomedical block is part of this problem, should we reopen to address in the spa? We'd need to research how much use the block is getting. Was something done recently to suppress errors during the reindexing of datasets? @scolapasta
