### ISSUE TITLE
Reports: Generate reports for large organizations

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3099]
Several of our larger institutional users regularly request quarterly and annual reports on usage and download activity. This is separate from periodic download activity to authors in #132

**Comment by bencomp** [comment]
This would be very useful for us as well. I use SQL and some custom scripts via ssh to generate stats for our partner institutions, but it's still too manual.

**Comment by pdurbin** [comment]
I still sort of wonder if Metabase could be used as a user-friendly front end for generating reports. I first floated the idea at https://github.com/IQSS/dataverse/issues/2729#issuecomment-161840783 .

**Comment by bencomp** [comment]
You need the right tools for the job. Metabase is still interesting and might be a very good solution. It depends on the audience of the reports - what do they want and how do they want the information?

**Comment by djbrooke** [comment]
I'm going to close this one. We have several tools available these days: http://guides.dataverse.org/en/latest/admin/reporting-tools-and-queries.html

**Comment by kcondon** [comment]
@djbrooke While we do have these tools, I'm sure Julian would like it if he did not need to run these reports manually on a quarterly basis for some customers. The use case remains but I'm fine with whatever folks decide since I'm no longer generating them.

**Comment by jggautier** [comment]
There are two types of reports customers ask for regularly, though not necessarily quarterly: download counts for dataset files that are in several dataverses and a spreadsheet of what's entered in metadata fields in datasets of several dataverses. 

The tools at http://guides.dataverse.org/en/latest/admin/reporting-tools-and-queries.html wouldn't help depositors get access to this information without help from installation admins, although I suppose features could be added that enable that.

The download counts are still accessible only from the postgres database, but that should change with more support for Make Data Count, whose metrics are accessible with APIs.

For what's entered in metadata fields, I've created and shared with customers python scripts using Dataverse's APIs and Google's Colaboratory (https://colab.research.google.com). So people just need to enter some info (like the name of their dataverse), press a button and save CSV files to their computer.

I guess I'm saying that eventually I don't think I'll have to run these two reports manually, either. But not every Dataverse installation allows unrestricted access to their APIs or someone who can write scripts for customers.

Maybe new GitHub issues can be opened that ask for more specific functionally, like letting admins get a report of MDC download counts of datasets in their dataverses, or getting spreadsheets of what's entered in metadata fields.
