### ISSUE TITLE
Add data to dataverse

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#31]
---

Author Name: **Gustavo Durand** (@scolapasta)
Original Redmine Issue: 3438, https://redmine.hmdc.harvard.edu/issues/3438
Original Date: 2014-02-03
Original Assignee: Michael Bar-Sinai

---

With 4.0 being a rewrite of the code base, this ticket represents one of the core functional components to be done. Individual items that can be tested separately or need to be passed to another developer or designer should be added as new tickets under this one.

---

Child issue(s): #103, #112, #113, #114
Redmine child issue(s): [3512](https://redmine.hmdc.harvard.edu/issues/3512), [3521](https://redmine.hmdc.harvard.edu/issues/3521), [3522](https://redmine.hmdc.harvard.edu/issues/3522), [3523](https://redmine.hmdc.harvard.edu/issues/3523)

---

**Comment by scolapasta** [comment]
This is the high level ticket. Since linked datasets and dataverses are in (with specific individual issues being opened, and saved search has it's onn issue (#90), I think we can just close this?

**Comment by kcondon** [comment]
Closing for housekeeping.
