### ISSUE TITLE
WorldMap Join Targets: For edits, limit admin to selected layer/attributes

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3100]
This is related to the Django admin for the JoinTarget model.
- Add a JoinTarget from the Layer Admin
  - works, ok
- Directly adding a new JoinTarget
  - [x] Don't show any dropdown choices for Layer and LayerAttribute fields
  - [x] Add a message to the admin template - highlight in red
- Edit existing JoinTarget entry
  - [x] Limit Layer and LayerAttribute fields
  - [x] Add a message to the admin template - highlight in blue

---

!Note: This is Django **1.4.13**
- [x] move to test server
- [ ] move to prod server

**Comment by raprasad** [comment]
In pull request: https://github.com/cga-harvard/cga-worldmap/pull/115

**Comment by djbrooke** [comment]
@raprasad - I'm going to move this to the backlog, but if it should be in some other state feel free to move it! Thanks!

**Comment by raprasad** [comment]
Closing.  Already in production.
