### ISSUE TITLE
Footer: Update the text and links in footer

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#3101]
Current footer:

![screen shot 2016-05-02 at 1 45 17 pm](https://cloud.githubusercontent.com/assets/5922904/14965760/17fd3586-107d-11e6-9250-86875cdf2760.png)

Updates to be made:
- [x] Remove Data Science and link to Data Science website
- [x] Change it to be, "Developed at the Institute for Quantitative Social Science" with link to iq.harvard.edu behind Institute for Quantitative Social Science

**Comment by mheppler** [comment]
Updated the dataverse_template footer text and links for IQSS.

![screen shot 2016-05-02 at 4 28 44 pm](https://cloud.githubusercontent.com/assets/687227/14966990/00f47ae2-1083-11e6-8626-da11f69019d5.png)

**Comment by kcondon** [comment]
Looks good, closing.
