### ISSUE TITLE
Editing text files

### ISSUE THREAD

**Issue by binarybottle** [IQSS/dataverse#3104]
My use case for editing text files is straightforward:

I would like to be able to make small fixes in place to save time, especially when fixes need to be made across a number of files. This would also enable collaboration between remote parties with editing privileges and access to the Dataverse. A side effect is that the Dataverse would become the definitive/master repository and workspace.

It would be great to support markdown or to view/edit csv files as well!

**Comment by pdurbin** [comment]
Hmm, right now files are immutable so I guess clicking "edit" on a text file would create a new one. The question is if the old file is deleted automatically or not.

**Comment by binarybottle** [comment]
Couldn't files be versioned, as with git?

**Comment by pdurbin** [comment]
Well, to version a file in Dataverse you'd publish your dataset as 1.0 and then create a draft (the published version is unchanged), delete the file, upload a new version with the same file name, and publish it as 2.0. As the guides explain, you can always go back to the previously published version of a file: http://guides.dataverse.org/en/4.3/user/dataset-management.html#dataset-versioning . In short, versioning happens at the dataset level.

**Comment by pdurbin** [comment]
@binarybottle file versioning (the ability to replace a file) is currently being worked on in #2290. Being able to edit the file in the GUI is out of scope but we are adding API enpoints for the "file replace" operations. Perhaps a third party service could make use of those new API endpoints to allow you do download the file, make a quite edit in a GUI, and reupload to Dataverse, replacing the file. We can dream anyway. 😄

**Comment by pdurbin** [comment]
@binarybottle are you still interested in this feature?

**Comment by binarybottle** [comment]
I continue to recommend Dataverse to people, and point them to the comparison chart we worked on (https://docs.google.com/spreadsheets/d/1RJ7EZx2EuDiMeDHVy5sXbPVv2wY8NX8S_ncRPqgv-RA/edit).  I am sure such a feature would be of interest to people other than myself, but I don't know how they would prioritize their desired features.  Thank you for asking!

**Comment by pdurbin** [comment]
@binarybottle thanks, that's an interesting comparison of Synapse,	 Harvard Dataverse, Open Science Framework, RDoCdb -- NDA, and NITRC-IR. You might also find the comparisons at https://groups.google.com/d/msg/dataverse-community/xHCX9mWWqbo/aA_12pqgAQAJ interesting. Thanks also for recommending Dataverse.

With regard to editing files in a browser from the Dataverse UI, I'm thinking we should walk before we should run. #1203 is about **viewing** files so we should probably work on that first. I appreciate the fast response, though!

**Comment by pdurbin** [comment]
These days, now that we have the concept of "external tools", this could perhaps be an external tool of type "configure" (which allows editing). See "types" at https://guides.dataverse.org/en/5.11.1/api/external-tools.html#terminology

**Comment by pdurbin** [comment]
@binarybottle are you still interested in this? Thanks.

**Comment by binarybottle** [comment]
It will not affect my present use of Dataverse, but I still feel it would be helpful to others.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
