### ISSUE TITLE
IP Groups: Better integrate feature into the app and UI.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3106]
We are working on getting basic IP Group perms working in #1380 but there are some UI/Design issues that should be addressed to better integrate IP Groups as a feature into the UI.

-When an IP group member is detected, how is this signaled in the UI?
-IP Groups are read only so what happens when a role with both read and write perms is assigned such as admin? Should it allow it but only provide read only perms or disallow with error?
-Can only create and delete through UI and cannot delete if assigned a role.

**Comment by michbarsinai** [comment]
re: write access: I don't see why not. IP Groups can allow administrators, who control the IP assignments on a network, to assign roles an a way that appears as "zero configuration" to the users. Valid (I think) use cases include:
* all computers in lab X have the curator on the tutorial dataverse
* all computers in the sysadmin offices are administrators
* "trust" another computer in the same datacenter (for API calls etc.)

**Comment by djbrooke** [comment]
From #3233
_________

It is not obvious to less technical admins which ip or shib groups exist to assign roles to. While there are API commands that list each type, someone who exclusively uses the UI would not have access to this.

Also, maybe expand the User Guide to discuss the use of groups and their types in more detail.

There is some useful information on explicit groups on the groups page when there are no groups listed.

It may be useful to add shib and ip groups to the groups page as well or as Phil mentioned, perhaps to the Dashboard. Not sure how they will be used.

**Comment by pdurbin** [comment]
> When an IP group member is detected, how is this signaled in the UI?

This feature is also covered by #2458.
