### ISSUE TITLE
Install Guide: Explain how to configure Google Analytics

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3112]
User asked how to enable Google Analytics at their installation, see RT 235716

**Comment by pdurbin** [comment]
Huh. Yeah, http://guides.dataverse.org/en/4.5/installation/config.html#googleanalyticscode doesn't explain it very well. I just added this to the list at #2944.

**Comment by pdurbin** [comment]
@donsizemore and I discussed this at http://irclog.iq.harvard.edu/dataverse/2016-09-30#i_42392 and I encouraged him to create a pull request, which he did at #3393.
