### ISSUE TITLE
Postgres upgrade needed

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3125]
For the July community meeting, at least one demo Dataverse installation needs an upgrade to postgres 9.4+.   
- [ ] Postgres update.  release notes: http://www.postgresql.org/docs/9.4/static/release.html
- [ ] Update dev guide
- [ ] Announce to mailing list

This is to take advantage of the binary JSON field for use in file level metadata schemas.

**Comment by pdurbin** [comment]
On a lot of our hosts, we run CentOS 6 and use the version of posgres that comes with the operating system, which seems to be postgres 8.4 for CentOS 6. (I'm seeing postgresql-8.4.20-5.el6_7.x86_64 on http://phoenix.dataverse.org running CentOS 6.7.) Interestingly, we say version 9.x is required at http://guides.dataverse.org/en/4.3.1/installation/prerequisites.html#postgresql even though 8.4 seems to work fine as far as I know.

It appears that upgrading to CentOS 7 won't provide a new enough version of postgres out of the box (packaged with the operating system). Judging from http://mirror.centos.org/centos/7.2.1511/os/x86_64/Packages/ the version of postgres that comes with CentOS 7.2 is 9.2 (postgresql-server-9.2.13-1.el7_1.x86_64.rpm).

Anyway, there are, of course, other ways to install postgres besides simply running `yum install postgresql-server` and getting the version that ships with the operating system, as we document in the Installation Guide.

**Comment by donsizemore** [comment]
I would argue that, given RHEL/CentOS's promise of 10 years of software/security support and other distros' 5 years of LTS support, we'd want to retain compatibility with those particular versions if possible. If necessary features obsolete these versions, strike this from the record.

**Comment by pdurbin** [comment]
@donsizemore are you planning to run RHEL/CentOS 6 or 7 in production for Dataverse 4? Were you hoping to use the version of postgres that ships with the distribution?

To be a little more clear, the **Installation Guide** at http://guides.dataverse.org/en/4.3.1/installation/prerequisites.html#postgresql is a little inconsistent in that it says, "The version that ships with RHEL 6 and above is fine" (followed by `yum install postgresql-server`) which will give you postgres 8.4 and yet it also says, "Version 9.x is required. Previous versions have not been tested."

The **Developer Guide** at http://guides.dataverse.org/en/4.3.1/developers/dev-environment.html#postgresql says, "PostgreSQL 9.x is required."

Part of the pull request for this issue should be updating both the Installation Guide and the Dev Guide on the required version of PostgreSQL.

I spoke with @raprasad about this yesterday and really what we're trying to head off migration task in the future. If we're pretty sure we want to use the binary version of the JSON field that's only available in 9.4 and up we can avoid a future database migration script from the non-binary to the binary version if we require 9.4. I'm a little out of my depth here but that's my understanding of the situation.

Obviously, this ties us even more strongly to PostgreSQL but we haven't heard lately from any group that they want to run MySQL or other databases instead. I'm not sure how database independent https://github.com/IQSS/dataverse/blob/v4.3.1/scripts/database/reference_data.sql is anyway. It looks like @landreev removed some postgres-specific stuff in b4bf254.

**Comment by donsizemore** [comment]
@pdurbin Dataverse 4 will definitely run RHEL/CentOS7, and the packaged Postgres 9.2 would make it super straightforward for your sysadmins. If you need 9.4+, let's shoot for 9.5. Trying to avoid a production machine winding up on a deprecated/EOL-ed version of Postgres down the road.

**Comment by pdurbin** [comment]
@raprasad you were talking about last year's Dataverse Community Meeting originally and this year's meeting is next week. Is this still needed?
