### ISSUE TITLE
Geotweet Visualization/API Endpoint

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3128]
On 5/17, we decided to create/host the geotweet visualization as a small Django app that includes the following:
-  [ ] A Django view (url endpoint) showing the GeoTweet heatmap and search controls.  It will have the following characteristics
  - [ ] Interacts with the GeoTweet API
  - [ ] Uses an [open layers javascript client](http://openlayers.org/) to create a heatmap
  - [ ] May be iframed by a Dataverse landing page
- [ ] Provide a Django api endpoint that:
  - [ ] Returns JSON with the following information for display on the dataset landing page
    - # tweets
    - start/end times (to the minute or second) of the current 1 billion tweets (or all the tweets in the solr system)
    - This API endpoint will be used by the Dataverse application
- [ ] Hosting
  - Utilize Heroku, in conjunction with HMDC's enterprise agreement

**Comment by pdurbin** [comment]
I don't believe we are working on this anymore. Closing.
