### ISSUE TITLE
Dataverse URL - Page Not Found (404 Error) w/ Trailing Forward Slash

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#3130]
Came across this minor navigation issue recently. When there is a trailing forward slash at the end of a dataverse URL, you get a 404/Page Not Found error.

Good: `https://dataverse.harvard.edu/dataverse/mra`

Bad: `https://dataverse.harvard.edu/dataverse/mra/`

Other sites that I've tested this one, forwards you from one to the other. I found a [related post](http://www.ocpsoft.org/support/topic/automatically-adding-trailing-slashes-to-urls-that-need-slash/) on the Pretty Faces support forum with a potential solution.

**Comment by pdurbin** [comment]
Related #4196

**Comment by landreev** [comment]
This is an honest 1, for once. 
This is solved by adding this extra pretty-faces mapping: 
```
   <url-mapping id="dataverseslash">
        <pattern value="/dataverse/#{alias}/" />
        <view-id value="/dataverse.xhtml" />
    </url-mapping>
```
(this is in `src/main/webapp/WEB-INF/pretty-config.xml`)

**Comment by pdurbin** [comment]
@landreev cool, should we fix #4196 with prettyfaces too? That one's about a trailing parenthesis, a ")".

**Comment by landreev** [comment]
I don't think we should *encourage* people to use invalid urls. A trailing back slash kind of makes sense on the end of a url; a single mismatched parenthesis? - not really. 
I feel like a better error message would be a correct solution for #4196.

**Comment by mheppler** [comment]
Added mapping for dataverse url with trailing slash.

This now allows for the user to navigate to both `/dataverse/alias` and `/dataverse/alias/` URL's, and both return a `200 OK` status code.

There was some concern about duplicate content, but that was alleviated by @landreev who claimed his work in `robots.txt` will block this URL format.

Here is what the Google Webmaster Central Blog said on Wednesday, April 21, 2010 in the _To slash or not to slash_ post.

>If both slash and non-trailing-slash versions contain the same content and each returns 200, you can:
>
>   - Consider changing this behavior (more info below) to reduce duplicate content and improve crawl efficiency.
>   - Leave it as-is. Many sites have duplicate content. Our indexing process often handles this case for webmasters and users. While it’s not totally optimal behavior, it’s perfectly legitimate and a-okay. :)
>   - Rest assured that for your root URL specifically, http://example.com is equivalent to http://example.com/ and can’t be redirected even if you’re Chuck Norris.

**Comment by landreev** [comment]
Correct - I don't think duplicate indexed content is a problem in our case. Google bot will only index "/dataverse/foo" and "/dataverse/foo/" separately, if it has some way to discover both urls. I don't think it should be possible to ever get to "/dataverse/foo/" by crawling the site. Plus, our current approach is to specifically discourage the bots from crawling the site (i.e., from following the search and facets links); and instead make it go straight to the pages we advertise via the sitemap. The sitemap never uses the "/dataverse/name/" notation - only "/dataverse/name". 
(It was still nice to fix this issue, for the benefit of the human users)

**Comment by landreev** [comment]
(the only times I saw google bot try to access "/dataverse/name/" was when I specifically sent it there, via their search console)
