### ISSUE TITLE
Widgets: Advanced options, cancel button does not appear to cancel

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3132]
Tested on Windows using Chrome, Version 50.0.2661.102 m

Using advanced options to set a forwarding URL, cancel appears to save the value entered when you return to the form.

**Comment by sekmiller** [comment]
Fix checked in to the widgets branch.

**Comment by kcondon** [comment]
Fix works, passing back for review.

**Comment by sekmiller** [comment]
@mheppler 
I used this from PrimeFaces:

http://www.primefaces.org/showcase/ui/misc/resetInput.xhtml

In particular I adapted this code to the cancel button on the Advanced Options Popup:
            <h:commandButton value="Reset p:ajax" style="margin-right:20px;" >
                <p:ajax update="panel" resetValues="true" />
            </h:commandButton>

Any Comments? Objections?

**Comment by mheppler** [comment]
It looks like instead of updating the inputText and the messages components via the ajax tag, if you update the dialog with `themeWidgetsForm:advancedOptions` it returns the watermark to the input on cancel.

**Comment by sekmiller** [comment]
Awesome! Thanks, Mike. I will make that change.

**Comment by sekmiller** [comment]
Fixed the watermark per Mike's suggestion. Checked into Widgets Branch.

**Comment by kcondon** [comment]
Works, closing
