### ISSUE TITLE
Permissions: approved users go "missing" from permissions page

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#3133]
Brain Genomics Dataset specific at the moment.
Gustavo has looked into this and I am unable to determine why approved users go missing from the permissions page.
Tim reported today again, that the issue is still happening.

**Comment by djbrooke** [comment]
We should add the DB triggers as part of the 4.6 release.

**Comment by djbrooke** [comment]
Talked with @scolapasta and he helped me understand that this is not a code change and as such would not go out with the 4.5.1 release.  Removing the 4.5.1 label.

**Comment by djbrooke** [comment]
Hey @sbarbosadataverse - we've added some triggers to the DB to provide us with some additional information whenever this occurs. I'll contact Tim to ask him to let us know whenever this happens so that we can look in the logs, but please let me know if you see it as well - thanks!

**Comment by scolapasta** [comment]
connect to #3498
