### ISSUE TITLE
User Guide: Add section about Private URL

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#3138]
This morning @posixeleni and I chatted about how the User Guide should be updated to explain the Private URL feature once it lands in "develop". She'll be doing the writing so I'm assigning this issue to her.

As of this writing pull request #3111 has not yet been merged so the most logical place to update the User Guide is in the branch on which the pull request is based: https://github.com/IQSS/dataverse/tree/1012-private-url . I've already updated the API Guide in that branch/pull request.

I'm giving this issue a milestone of 4.5 since I think that's where the Private URL feature will land.

**Comment by pdurbin** [comment]
There may be some text edits coming in #3174.

**Comment by pdurbin** [comment]
@eaquigley I'm passing this issue to you to work on "12. Update User Guide to be consistent with labeling in the UI: https://github.com/IQSS/dataverse/blob/1012-private-url/doc/sphinx-guides/source/user/dataset-management.rst " from #3174.

**Comment by eaquigley** [comment]
@kcondon i've finished updating the user guide for Private URL. passing to you for QA.

**Comment by kcondon** [comment]
Looks good, closing.
