### ISSUE TITLE
Decide on a datastructure/mechanism to capture dataset mode

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3139]
The Biomedical (Helmsley) and Interactive/Streaming Datasets (Sloan)* will have distinct dataset page views.  The functionality for these views is diverse/complex enough that it cannot be easily "tacked" onto the existing code.  e.g. A dataset should inherently know it's mode or type.  What is the data structure/strategy to capture this?

**Comment by pdurbin** [comment]
Right, @raprasad explained the other day that in this experiment to relationship to the dataset id is expressed in his InteractiveDataset object: https://github.com/IQSS/dataverse/blob/3102-geotweets/src/main/java/edu/harvard/iq/dataverse/interactivedataset/InteractiveDataset.java

    @OneToOne
    @JoinColumn(name="dataset_id")
    @Expose
    private Dataset dataset;

It sounds like instead there should probably be a column called "mode" or whatever on the "dataset" table: http://phoenix.dataverse.org/schemaspy/latest/tables/dataset.html

**Comment by raprasad** [comment]
Closing after talking to @scolapasta.  This will be a method on the Dataset object with presentation functionality integrated into the dataset page.

**Comment by pdurbin** [comment]
@raprasad can you please ping me and @bmckinney when a branch has been pushed that has this new method?

**Comment by raprasad** [comment]
@pdurbin: will do
