### ISSUE TITLE
Use something that's not native sequence incerementing for file's fileSystemName

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#314]
---

Author Name: **Michael Bar-Sinai** (@michbarsinai)
Original Redmine Issue: 3729, https://redmine.hmdc.harvard.edu/issues/3729
Original Date: 2014-03-17
Original Assignee: Leonid Andreev

---

To allow easier setup and database independence.
Optional solutions are JDBC generated keys, JPA's @GeneratedValues, java.util.UUID etc.

**Comment by pdurbin** [comment]
A link from @michbarsinai via @landreev from long ago that might prove useful: http://stackoverflow.com/questions/1915166/how-to-get-the-insert-id-in-jdbc/1915197#1915197
