### ISSUE TITLE
Widgets: Add forwarding url help text, target url needs widget code

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3143]
It might help to add a little more info on the forwarding url popup to indicate the page the url points to needs to host or have the dvlisting widget code to work.

Current text:
Forward persistent URL's in your dataset citation to your personal website.

Maybe something add something like:
Forward dataset persistent URLs to your personal website. Your page must contain the dataverse listing widget.

**Comment by mheppler** [comment]
I have created a new issue to track the widgets documentation (#3147), which I name a new branch off of. Development for this issue will be done on that branch.

**Comment by mheppler** [comment]
Revised the help text in the Advanced Options popup of the dataverse widgets. Added documentation to the Dataverse Management and Dataset Management pages of the User Guide.

**Comment by scolapasta** [comment]
This has now been removed from the code.

**Comment by kcondon** [comment]
True, closing.
