### ISSUE TITLE
Widgets - Documentation

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#3147]
The User Guides need to be updated with the new widgets features.

Created a [Google doc](https://docs.google.com/document/d/1lb_7igH9mseJDcOcXdepgXGspmZfMTSoZutgolx643k/edit#) for collaboration on updating the text.

**Comment by mheppler** [comment]
@eaquigley -- I have checked in my initial take on the widgets documentation. I am passing this along to you in hopes that you can help review and improve it.

**Comment by eaquigley** [comment]
Widgets section of the user guide is complete. Passing this issue to QA. Not sure if branch is ready for pull request though due to some development work that still needs to be done with the citation.

**Comment by kcondon** [comment]
Looks good, closing.

**Comment by kcondon** [comment]
Spoke too soon. This is no longer true and needs to be removed from the docs:

http://guides.dataverse.org/en/3147-widgets-docs/user/dataset-management.html#widgets

Note: You can forward the persistent URL (DOI or Handle) of your dataset to your personal website. For more information on the widgets available for a dataverse, please visit the Widgets section of the Dataverse Management page.

**Comment by eaquigley** [comment]
@kcondon good catch! deleted that section.

**Comment by kcondon** [comment]
Section removed, closing.
