### ISSUE TITLE
Create Dataset: Cannot add files if focus is left on compound field

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#315]
---

Author Name: **Kevin Condon** (@kcondon)
Original Redmine Issue: 3730, https://redmine.hmdc.harvard.edu/issues/3730
Original Date: 2014-03-18
Original Assignee: Mike Heppler

---

Tested on 3/18 using FF on build and alpha

If focus is left on a field such as author, keyword, contact email, and user scrolls to bottom and clicks add files, browser scrolls back to focused field and does nothing else. If the focus is put on a non compound field (without +), such as description, it works as expected.

Steps to reproduce:
1. Choose add dataset
2. Enter title, author, click on contact email field, leave focus there
3. At bottom of page, click add files, notice it does nothing
4. Click into description field, notice add files button works
5. Click keyword field, notice add files does not work again.

It seems to require clicking on author or adding text to author and then navigating to another compound field to get it in this state. Otherwise if you just enter author and leave it there, add files button works.

**Comment by scolapasta** [comment]
rediscussed with @kcondon - although this does happen, it:
a) affects only one browser
b) happens with a very specific use case (autofill)
c) has an easy workaround

so we won't invest time to fix. Closing.
