### ISSUE TITLE
Sensitive Data: IP Groups should not allow access to level 2 data or above

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#3151]
Level 2 data is defined at http://policy.security.harvard.edu/level-2 (not public).

**Comment by scolapasta** [comment]
Can this be combined with #3152 to just be "User must be authenticated" in order to download Level 2? (that seems to be the underlying issue with users who are just identified by IP address, but not logged in, or private URLs)

**Comment by djbrooke** [comment]
Notes from 7/7 meeting:

- We need more information about datatags before implementing this completely, but we can make an assumption that a datatag will be referenced by this code when making the determination about whether or not the user can access the data. We can move forward with the backend while the datatags project is still being defined.
- Messages will need to display about why these users cannot access the information. The text of these messages and the workflow will be defined during the datatags project.
- The comment from @scolapasta above was also discussed

**Comment by pdurbin** [comment]
Per @djbrooke the Sensitive Data project is being deferred until Dataverse 5.0 so I'm unassigning myself since I like having https://github.com/IQSS/dataverse/issues/assigned/pdurbin reflect what I'm actually working on. I'll also add the 5.0 milestone.

**Comment by pdurbin** [comment]
Sensitive data work isn't happening until Dataverse 5.0. We'll revisit this then. Closing.
