### ISSUE TITLE
User Guide Updates

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#3154]
In the documentation, we should note "BibTex" as a Download Citation option on the "Finding and Using Data" page in two places:

[https://github.com/IQSS/dataverse/blob/2935cdedcd2f907d9b44356410d5139cfaf19062/doc/sphinx-guides/source/user/find-use-data.rst#download-citation] 

and 

[https://github.com/IQSS/dataverse/blob/2935cdedcd2f907d9b44356410d5139cfaf19062/doc/sphinx-guides/source/user/find-use-data.rst#download-files]

**Comment by mheppler** [comment]
@djbrooke -- Liz and I are going to meet to discuss documentation changes in the User Guide related to the Widgets project. I am going to take this issue, and make sure we include it in our [3147-widgets-docs](https://github.com/IQSS/dataverse/tree/3147-widgets-docs) branch.

**Comment by djbrooke** [comment]
@mheppler  - I was hoping to make this small change to familiarize myself with the process end-to-end. Let me know if there's another preferred way for me to get acquainted. Thanks!

**Comment by mheppler** [comment]
My apologies! Have at it.

**Comment by djbrooke** [comment]
Awesome, thanks! PR incoming.

**Comment by eaquigley** [comment]
@djbrooke let me know if you need the link to the Sphinx formatting cheat sheet document!





On Thu, Jun 2, 2016 at 6:39 AM -0700, "Michael Heppler" <notifications@github.com<mailto:notifications@github.com>> wrote:


My apologies! Have at it.

-

**Comment by djbrooke** [comment]
@eaquigley please send it on when you have a chance. Thanks.

PR is out - let me know what I missed!

https://github.com/IQSS/dataverse/pull/3155

**Comment by mheppler** [comment]
@djbrooke -- While you're in there, adding the BibTex info, please also update the text under the Download Citation section to reflect the UI changes we'll be making in the Widgets project. The button text has been changed to "Cite Data" (see attached).

<img width="974" alt="screen shot 2016-06-02 at 9 48 37 am" src="https://cloud.githubusercontent.com/assets/687227/15747195/94b14c24-28a7-11e6-97b8-87873e80bcbc.png">

**Comment by djbrooke** [comment]
OK - I've updated the PR with that change.

**Comment by kcondon** [comment]
This was merged and will be available in v4.5.
