### ISSUE TITLE
Dataset Citation: Add Padding to Blue Data Citation Box

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#3157]
There needs to be padding added around the updated dataset citation box. Its too crowded and difficult to read as is.

![screen shot 2016-06-02 at 2 16 49 pm](https://cloud.githubusercontent.com/assets/5922904/15755866/a951a5e6-28cc-11e6-950d-1fab7885b314.png)

**Comment by kcondon** [comment]
Looks good, wraps with more space/ padding before the end of the citation block, closing.
