### ISSUE TITLE
Guides - Oversized Screenshots Break Layout

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#3158]
When a large screenshot is added to the guides, the large width breaks the page layout and you get some weird scrolling/layering issues. (See attached.)

To resolve this, you should be able to add the `img-responsive` class from the Bootstrap theme to the images in Sphinx via the [options](http://www.sphinx-doc.org/en/stable/rest.html), that will properly size the image to the width of it's container element.

**Comment by mheppler** [comment]
Fixed screenshot image size issue that broke the layout by adding img-responsive style class.

**Comment by kcondon** [comment]
Seems ok, closing.
