### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by lmaylein** [IQSS/dataverse#3160]
http://guides.dataverse.org/en/4.3/installation/r-rapache-tworavens.html :

Broken link in Chapter "1. Set Up R":
https://github.com/IQSS/dataverse/conf/R/

**Comment by mheppler** [comment]
It appears this was fixed in the commit a1456b15d5c41dd72c5679e4d8c2995ae0fbb696 and was released as part of [4.5.1](https://github.com/IQSS/dataverse/releases/tag/v4.5.1).

**Comment by kcondon** [comment]
Fixed, closing.
