### ISSUE TITLE
authorIdentifierScheme : Add "ResearcherID" as one of the option

### ISSUE THREAD

**Issue by Venki18** [IQSS/dataverse#3169]
Please help to add "ResearcherID" as one of the options to the authorIdentifierScheme as one of the controlled vocabulary.

**Comment by pdurbin** [comment]
Related: #3944

**Comment by pdurbin** [comment]
@Venki18 are you still interested in this? Is there a website that describes what "ResearcherID" is? Is it based on a standard?

**Comment by pdurbin** [comment]
Related #1375.

**Comment by Venki18** [comment]
Dear Phil

We are still interested in ResearcherID. You can find more information from the following website

http://www.researcherid.com/Home.action?returnCode=ROUTER.Success&Init=Yes&SrcApp=CR&SID=T2JUmfMmCWUdwFFc7pf <http://www.researcherid.com/Home.action?returnCode=ROUTER.Success&Init=Yes&SrcApp=CR&SID=T2JUmfMmCWUdwFFc7pf>

Thanks and Regards
Venki

**Comment by pdurbin** [comment]
@Venki18 ok, thanks. I should be a relatively easy pull request. Is there someone at your organization who could make one? I recently wrote these instructions: http://guides.dataverse.org/en/4.7/developers/version-control.html#how-to-make-a-pull-request

Here's where ORCID is defined: https://github.com/IQSS/dataverse/blob/v4.7/scripts/api/data/metadatablocks/citation.tsv#L131 . A line for ResearcherID would need to be added.

**Comment by pdurbin** [comment]
@Venki18 if you'd like to make a pull request, please see pull request #5161 as an example. It was for #5151 to add two identifiers for authors.

**Comment by Venki18** [comment]
@pdurbin thank you. Will do it during the next upgrade of Dataverse.

**Comment by pdurbin** [comment]
@Venki18 great. If you need any help making the pull request, please just let us know.

**Comment by djbrooke** [comment]
Hey @Venki18, I'll be back in Singapore next month. If you'd like, we can set aside 30 minutes or so to take you or a member of your team through the Pull Request process with this as an example. Let me know if you'd be interested.

**Comment by Venki18** [comment]
Hi Danny 

Welcome to SG. Sure that would be great. Thank you.

**Comment by djbrooke** [comment]
Thanks @mderuijter @pdurbin and @kcondon for working on this and getting it merged. 

@Venki18 and I weren't able to catch up during my time in SG, so this is appreciated! :)
