### ISSUE TITLE
Widgets - Usability Revisions

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#3170]
Suggested revisions to the Widgets feature based on [usability testing feedback](https://docs.google.com/document/d/1bhdzpLG_0qUZcaAnKvYgxow-3jSqnYmzWGuB-YcaIKg/edit) collected by @eaquigley.

- [x] Display the Feature Dataverses carousel on the dataverse pg
- [x] Display Versions tab on dataset pg, but hide content, instead displaying text about finding "more information" and being able to "edit the dataset on the full version", plus provide a link.

**Comment by mheppler** [comment]
Added the Featured Dataverses carousel to the widgets view of the dataverse pg. Added Versions tab to the widgets view of the dataset pg with conditional msg and link to view/edit full version on dataverse.

Passing to @eaquigley to review/approve/improve msg text.

![screen shot 2016-06-14 at 4 11 28 pm](https://cloud.githubusercontent.com/assets/687227/16058069/b1003bf4-324a-11e6-85d5-7a0746afb70b.png)

**Comment by eaquigley** [comment]
@mheppler 

Update:

To view more information about the versions of this dataset or edit it if this is your dataset, please visit the full version of this dataset at the Root Dataverse.

**Comment by mheppler** [comment]
Revised help/info text in Versions tab on dataset pg conditionally displayed in widgets view.

(Thank you, @eaquigley.)

**Comment by kcondon** [comment]
OK, versions tab with text and link in place.
Featured dv's in place but links need updating, in separate ticket. Closing.
