### ISSUE TITLE
Widgets: Finishing touches, adjust URL in citation, do not resolve DOI to remote site.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3171]
From recent review meeting with stakeholders:

1. DOI's will always be directly redirected to dataverse.
2. We will still allow users to "register their widget". If they do, the website they input will be used as part of the citation (see 3).
3. We will modify the citation to:
  - A. show the DOI (or other persistent ID) as "doi:xxxx/yyyy", i.e. the text will not display the URL. However for the online version, it will still be linked to the persistent URL.
  - B. add [Website:short.url/xyz] to the citation, if the widget has been registered.
4. In the near future, consider adding URL to the citation metadata, which can be harvested and indexed by other systems.

![screen shot 2016-06-15 at 11 38 27 am](https://cloud.githubusercontent.com/assets/687227/16086507/bc9897ba-32ed-11e6-98a9-6499ba20fe9b.png)

**Comment by mheppler** [comment]
Updated screenshot based off refining the requirements.

![screen shot 2016-06-17 at 3 41 39 pm](https://cloud.githubusercontent.com/assets/687227/16206814/24cc4008-36f8-11e6-8a44-de99e75ed68c.png)

Also, this issue is related to issues #2297 and #2146 which are based on user requested features to add metadata fields to the dataset citations.

**Comment by mheppler** [comment]
Removed the Advanced Options feature from Dataverse Listing Widget section of the Dataverse Theme + Widgets pg.

**Comment by kcondon** [comment]
OK, 1-3 are done, adv options removed. 3b. needs some modification to meet Gary's expectation.

**Comment by kcondon** [comment]
Closing this ticket since it was essentially delivered. The one word change can be tracked separately. Closing.
