### ISSUE TITLE
Private URL -- UI Improvements

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#3174]
UI improvements to the Private URL (#1012) project.

![screen shot 2016-06-16 at 2 24 24 pm](https://cloud.githubusercontent.com/assets/687227/16159809/c1e54668-3492-11e6-878c-b26d9b8c1ac8.png)
- [x] 1. Expand title header to be "Unpublished Dataset Private URL". The popup header has the space to give a little more information about the feature, even if the dataset's Edit dropdown button only says "Private URL".
- [x] 2. Remove the extra padding at the bottom the panel.
- [x] 3. In the help text, link to further details about this feature in User Guide.
<img width="609" alt="screen shot 2016-06-16 at 2 58 26 pm" src="https://cloud.githubusercontent.com/assets/687227/16159819/cec653a4-3492-11e6-9e77-3447ff2f4582.png">
- [x] 4. Display Private URL as only text instead of a link. Add javascript to highlight the text URL when you click it.
![screen shot 2016-06-16 at 2 35 10 pm](https://cloud.githubusercontent.com/assets/687227/16159820/d6e07a56-3492-11e6-8e9f-c7ffe7631b95.png)
- [x] 5. Move the success message for creating the Private URL into the popup, where the action is happen, and it's easier for the user to see. (No URL in success msg needed, make more human friendly.)
- [ ] 5B. Dynamically render the newly added static "Success!" message in the popup via the back end.
- [x] 6. Instead of success message block displayed on dataset pg behind the popups, display the info block text for admins/authors (see Item 10).
- [x] 7. Instead of stacking the confirm popup on top of the original popup, only display one popup at a time. The "Disable..." button closes original popup, opens the the confirm popup. The "Cancel" button reopens the original popup.
- [x] 8. On the confirm popup, the action button text is the same in both popups. We should add to the warning message something along the lines of "Are you sure...?" and the action button text can be "Yes, Disable Private URL..."
- [x] 8B. Format the disable success msg: "Success! – You have successfully disabled the Private URL for this unpublished dataset."
- [x] 9. Fix the spacing between the buttons.
<img width="1170" alt="screen shot 2016-06-16 at 3 00 27 pm" src="https://cloud.githubusercontent.com/assets/687227/16159830/e45915da-3492-11e6-9457-2dc0621466dd.png">
- [x] 10. The info block text for admins/authors needs to be formatted: "Unpublished Dataset Private URL - Privately share this dataset before it is published: {URL}" ~~Maybe we can provide a link to open the Private URL popup.~~
<img width="974" alt="screen shot 2016-06-16 at 2 54 57 pm" src="https://cloud.githubusercontent.com/assets/687227/16159831/e9553bf4-3492-11e6-9ab3-36130aa6122d.png">
- [x] 11. The info block text for end users/reviewers needs to be formatted: "Unpublished Dataset Private URL - This unpublished dataset is being privately shared. You will not be able to access it when logged into your Dataverse account.  "
- [x] 12. Update User Guide to be consistent with labeling in the UI: https://github.com/IQSS/dataverse/blob/1012-private-url/doc/sphinx-guides/source/user/dataset-management.rst

**Comment by pdurbin** [comment]
Today @djbrooke @mheppler and I met to discuss the Private URL feature and the state of the branch, open issues, and pull request.

Mike will be working on some of the changes he suggested above so I'll pass this issue to him. The work should be done in the 1012-private-url branch, which pull request #3111 is based on. After switching to the branch, you must run the SQL update at 
https://github.com/IQSS/dataverse/blob/95570c78c030588a56b29f366dba5c3cad2d8e78/scripts/database/upgrades/upgrade_v4.4_to_v4.5.sql to add a column to the "roleassignment" table. (A Private URL is a specialized "Member" role assignment with a token.) Details about what I've implemented can be found in my design doc at https://github.com/IQSS/dataverse/blob/1012-private-url/doc/Architecture/privateurl.md

Items 5 and 7 should be discussed with @eaquigley

Item 10 might be challenging to implement based on my reading of http://stackoverflow.com/questions/3356546/embedding-a-link-or-other-html-in-a-jsf-message

From my perspective, the other items a mix of fantastic ideas (thanks!) and stuff that I don't have strong opinion about. I would suggest asking the stakeholders named in the BRD at https://docs.google.com/document/d/1FT47QkZKcmjSgRnePaJO2g1nzcotLyN3Yb2ORvBr6cs/edit?usp=sharing if there is any doubt on if something should change.

**Comment by pdurbin** [comment]
Border gone in 27a8e48

6 was done in a8963d3

5b is half working. Please see the FIXME at 2c80313

@mheppler can you please take a look?

**Comment by pdurbin** [comment]
@mheppler I got the "Close" button to properly set privateUrlWasJustCreated to false in f515e4b but please not that I changed the FIXME to reflect the fact that there's a related known issue I just discovered in this area.

The bug is that if you click the "X" in the upper right corner rather than the "Close" button (or the "Disable Private URL" button) the green "Success" message doesn't go away. Basically, I don't know how to make it so that `setPrivateUrlJustCreatedToFalse` gets called when you click the "X". Honestly, I can live with this bug but if you can figure it out, awesome. I'll leave this issue assigned to you so you can check this out and other changes I've described in person and in comments above.

Here's a handy screenshot of the "X" in the upper right of the Bootstrap "modal" I'm talking about:

![screen shot 2016-06-24 at 10 53 09 am](https://cloud.githubusercontent.com/assets/21006/16341254/351bec42-39fa-11e6-9575-9e5e7b98c99a.png)

Oh, and I copied item 12 about the docs to #3138 and gave it to @eaquigley since that issue is about docs. That way you can each have an issue. 😄

**Comment by pdurbin** [comment]
@mheppler it looks like the section title and anchor changed at a54d5e8 so this key in the Bundle should change (I would think):

`dataset.privateurl.tip=Use a Private URL to allow those without Dataverse accounts to access your unpublished dataset. For more information about the Private URL feature, please refer to the <a href="{0}/{1}/user/dataset-management.html#private-url-for-draft-dataset-review" title="Private URL For Draft Dataset Review - Dataverse User Guide" target="_blank">User Guide</a>.`

The new anchor seems to be dataset-management.html#private-url-for-reviewing-an-unpublished-dataset

**Comment by mheppler** [comment]
Fixed User Guide link in Private URL dialog. Fixed "X" close dialog navigation issue on confirm dialog.

Passing back to @pdurbin to fine tune the backing bean and how the "Success!" msg is displayed and removed.

**Comment by pdurbin** [comment]
@mheppler I checked with @scolapasta and he knew immediately how to fix the delay we were seeing. I needed to switch it from "onclick" to "oncomplete", which did the trick. I rolled it into what I hope is the final commit for this branch and pull request: 50ae521

Moving to QA.

**Comment by kcondon** [comment]
Looks good, closing.
