### ISSUE TITLE
Metadata Fields > Edit Dataverse General Information: "Done" btn is broken on new dataverse form only, when viewing metadata fields

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3175]
Steps to reproduce:
1. Create a dataverse, do not yet save.
2. On any of the metadatablocks, under Metadata Fields, click View Fields.
3. Click Done and notice the block remains expanded, cannot close, and now cannot view any other blocks.

Refreshing the page does restore functionality.

This was reported by a user, see RT 235672

**Comment by mheppler** [comment]
Stumbled across this issue when reviewing the PR for #3924.

**Comment by djbrooke** [comment]
- If we fill out the required fields (category, identifier), clicking "Done" closes this as expected.
