### ISSUE TITLE
Widgets: Featured Dataverse Links should follow same render logic as other dv links (child opens in widget).

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3177]
Featured dataverse links currently open at Dataverse in a new tab. Most featured dataverses are children of the hosting parent dv so should open in the widget according to the general render logic.

There are cases such as linked dataverses, where this would not be the case, right?

**Comment by mheppler** [comment]
Applied widgetWrapper URL logic to the links in the Featured Dataverses carousel.

**Comment by kcondon** [comment]
Works, closing.
