### ISSUE TITLE
Version: Update Dataverse version to be 4.4 in preparation for v4.4. release.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3178]
The last dev task by current convention is to update the version of Dataverse that shows up in the footer in the app and also determines where it looks for the docs.

We are fast approaching  the last dev check in (one last known one addressing the citation link) and we can complete this.

**Comment by pdurbin** [comment]
How to do this is documented at http://guides.dataverse.org/en/4.3.1/developers/making-releases.html#bump-version-numbers

**Comment by pdurbin** [comment]
This was done in #3188. Closing.
