### ISSUE TITLE
Documentation: Resolve build warnings for HTML version of doc

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3181]
There are a dozen or so warnings in the build output when making the html version of the docs. They do not seem to cause any problem with rendering/viewing the content but it would be a good idea to understand and resolve them to make build output cleaner and prevent potential future issues by using the doc tool better. Note: These warnings are separate from the PDF build issue (#3134) and occur without PDF enabled.

See Jenkins console output for: guides.dataverse.org-rfi

reading sources... [100%] user/tabulardataingest/supportedformats
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/api/dataaccess.rst:63: WARNING: Title underline too short.

Parameters:
~~~~~~~~~~
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/api/dataaccess.rst:67: WARNING: Title underline too short.

"All Formats" bundled access for Tabular Files.
----------------------------------------------
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/api/dataaccess.rst:67: WARNING: Title underline too short.

"All Formats" bundled access for Tabular Files.
----------------------------------------------
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/api/dataaccess.rst:81: WARNING: Title underline too short.

Parameters:
~~~~~~~~~~
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/api/index.rst:18: WARNING: toctree contains reference to nonexisting document u'api/ :maxdepth: 2'
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/api/native-api.rst:92: WARNING: Inline literal start-string without end-string.
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/api/native-api.rst:167: WARNING: Title underline too short.

Builtin Users
~~~~~
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/api/native-api.rst:167: WARNING: Title underline too short.

Builtin Users
~~~~~
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/developers/index.rst:11: WARNING: toctree contains reference to nonexisting document u'developers/ :maxdepth: 2'
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/developers/unf/index.rst:3: WARNING: Title overline too short.

====================================
Universal Numerical Fingerprint (UNF)
====================================
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/developers/unf/index.rst:9: WARNING: toctree contains reference to nonexisting document u'developers/unf/ :maxdepth: 2'
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/developers/unf/unf-v5.rst:14: ERROR: Document may not end with a transition.
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/installation/config.rst:107: WARNING: Inline literal start-string without end-string.
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/installation/config.rst:107: WARNING: Inline literal start-string without end-string.
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/installation/config.rst:194: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/installation/config.rst:204: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/installation/config.rst:209: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/installation/config.rst:271: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/installation/config.rst:278: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/installation/config.rst:285: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/installation/config.rst:292: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/installation/config.rst:395: WARNING: Title underline too short.

:TwoRavensTabularView
+++++++++++++++++++
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/installation/config.rst:395: WARNING: Title underline too short.

:TwoRavensTabularView
+++++++++++++++++++
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/installation/index.rst:11: WARNING: toctree contains reference to nonexisting document u'installation/ :titlesonly:'
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/installation/index.rst:11: WARNING: toctree contains reference to nonexisting document u'installation/ :maxdepth: 2'
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/installation/prerequisites.rst:101: WARNING: Title underline too short.

Configuring Database Access for the Dataverse Application (and the Dataverse Installer)
=====================================================================================
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/installation/prerequisites.rst:101: WARNING: Title underline too short.

Configuring Database Access for the Dataverse Application (and the Dataverse Installer)
=====================================================================================
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/installation/r-rapache-tworavens.rst:194: WARNING: Title underline too short.

I. Configure the TwoRavens web (Javascript) application.
-------------------------------------------------------
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/user/data-exploration/index.rst:11: WARNING: toctree contains reference to nonexisting document u'user/data-exploration/ :titlesonly:'
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/user/data-exploration/index.rst:11: WARNING: toctree contains reference to nonexisting document u'user/data-exploration/ :maxdepth: 2'
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/user/dataset-management.rst:2: WARNING: Duplicate explicit target name: "worldmap".
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/user/dataset-management.rst:2: WARNING: Duplicate explicit target name: "worldmap".
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/user/dataset-management.rst:288: WARNING: nonlocal image URI found: http://static.projects.iq.harvard.edu/files/styles/os_files_xxlarge/public/datascience/files/data_publishing_version_workflow.png?itok=8Z0PM-QC
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/user/dataset-management.rst:314: WARNING: nonlocal image URI found: http://static.projects.iq.harvard.edu/files/styles/os_files_xxlarge/public/datascience/files/data_publishing_version_workflow.png?itok=8Z0PM-QC
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/user/dataverse-management.rst:62: WARNING: Duplicate explicit target name: "widgets".
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/user/index.rst:11: WARNING: toctree contains reference to nonexisting document u'user/ :maxdepth: 2'
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/user/tabulardataingest/index.rst:11: WARNING: toctree contains reference to nonexisting document u'user/tabulardataingest/ :titlesonly:'
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/user/tabulardataingest/index.rst:11: WARNING: toctree contains reference to nonexisting document u'user/tabulardataingest/ :maxdepth: 2'
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/user/tabulardataingest/index.rst:11: WARNING: toctree contains reference to nonexisting document u'user/tabulardataingest/stata'
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/user/tabulardataingest/rdata.rst:147: WARNING: Block quote ends without a blank line; unexpected unindent.
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/user/tabulardataingest/rdata.rst:193: WARNING: Line block ends without a blank line.
looking for now-outdated files... none found
pickling environment... done
checking consistency... /var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/developers/ubuntu.rst:: WARNING: document isn't included in any toctree
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/developers/windows.rst:: WARNING: document isn't included in any toctree
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/installation/installer-script.rst:: WARNING: document isn't included in any toctree
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/user/super-user.rst:: WARNING: document isn't included in any toctree

writing output... [100%] user/tabulardataingest/supportedformats
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/installation/config.rst:91: WARNING: undefined label: doi.baseurlstring (if the link has no caption the label must precede a section header)
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/installation/config.rst:91: WARNING: undefined label: doi.username (if the link has no caption the label must precede a section header)
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/installation/config.rst:91: WARNING: undefined label: doi.password (if the link has no caption the label must precede a section header)
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/installation/config.rst:93: WARNING: undefined label: :doiprovider (if the link has no caption the label must precede a section header)
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/installation/config.rst:93: WARNING: undefined label: :protocol (if the link has no caption the label must precede a section header)
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/installation/config.rst:93: WARNING: undefined label: :authority (if the link has no caption the label must precede a section header)
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/installation/config.rst:93: WARNING: undefined label: :doiseparator (if the link has no caption the label must precede a section header)
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/user/dataverse-management.rst:39: WARNING: undefined label: theme-widgets (if the link has no caption the label must precede a section header)

reading sources... [100%] user/tabulardataingest/index
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/api/index.rst:18: WARNING: toctree contains reference to nonexisting document u'api/ :maxdepth: 2'
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/developers/index.rst:11: WARNING: toctree contains reference to nonexisting document u'developers/ :maxdepth: 2'
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/developers/unf/index.rst:3: WARNING: Title overline too short.

====================================
Universal Numerical Fingerprint (UNF)
====================================
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/developers/unf/index.rst:9: WARNING: toctree contains reference to nonexisting document u'developers/unf/ :maxdepth: 2'
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/installation/index.rst:11: WARNING: toctree contains reference to nonexisting document u'installation/ :titlesonly:'
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/installation/index.rst:11: WARNING: toctree contains reference to nonexisting document u'installation/ :maxdepth: 2'
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/user/data-exploration/index.rst:11: WARNING: toctree contains reference to nonexisting document u'user/data-exploration/ :titlesonly:'
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/user/data-exploration/index.rst:11: WARNING: toctree contains reference to nonexisting document u'user/data-exploration/ :maxdepth: 2'
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/user/index.rst:11: WARNING: toctree contains reference to nonexisting document u'user/ :maxdepth: 2'
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/user/tabulardataingest/index.rst:11: WARNING: toctree contains reference to nonexisting document u'user/tabulardataingest/ :titlesonly:'
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/user/tabulardataingest/index.rst:11: WARNING: toctree contains reference to nonexisting document u'user/tabulardataingest/ :maxdepth: 2'
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/user/tabulardataingest/index.rst:11: WARNING: toctree contains reference to nonexisting document u'user/tabulardataingest/stata'
looking for now-outdated files... none found
pickling environment... done
checking consistency... /var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/developers/ubuntu.rst:: WARNING: document isn't included in any toctree
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/developers/windows.rst:: WARNING: document isn't included in any toctree
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/installation/installer-script.rst:: WARNING: document isn't included in any toctree
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/user/super-user.rst:: WARNING: document isn't included in any toctree

writing output... [100%] user/tabulardataingest/supportedformats
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/installation/config.rst:91: WARNING: undefined label: doi.baseurlstring (if the link has no caption the label must precede a section header)
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/installation/config.rst:91: WARNING: undefined label: doi.username (if the link has no caption the label must precede a section header)
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/installation/config.rst:91: WARNING: undefined label: doi.password (if the link has no caption the label must precede a section header)
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/installation/config.rst:93: WARNING: undefined label: :doiprovider (if the link has no caption the label must precede a section header)
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/installation/config.rst:93: WARNING: undefined label: :protocol (if the link has no caption the label must precede a section header)
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/installation/config.rst:93: WARNING: undefined label: :authority (if the link has no caption the label must precede a section header)
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/installation/config.rst:93: WARNING: undefined label: :doiseparator (if the link has no caption the label must precede a section header)
/var/lib/jenkins/workspace/guides.dataverse.org-rfi/doc/sphinx-guides/source/user/dataverse-management.rst:39: WARNING: undefined label: theme-widgets (if the link has no caption the label must precede a section header)

writing content.opf file...
WARNING: unknown mimetype for _static/jquery.js, ignoring
WARNING: unknown mimetype for _static/underscore.js, ignoring
WARNING: unknown mimetype for _static/doctools.js, ignoring
WARNING: unknown mimetype for _static/websupport.js, ignoring
WARNING: unknown mimetype for _static/navbar_from_dataverse_org.js, ignoring
WARNING: unknown mimetype for _static/navbarscroll.js, ignoring
WARNING: unknown mimetype for _static/searchtools.js, ignoring
WARNING: unknown mimetype for _static/installation/files/issues/2180/grizzly-patch/glassfish-grizzly-extra-all.jar, ignoring
WARNING: unknown mimetype for _static/installation/files/issues/2180/grizzly-patch/readme.md, ignoring
WARNING: unknown mimetype for _static/installation/files/etc/init.d/solr, ignoring
WARNING: unknown mimetype for _static/installation/files/etc/init.d/glassfish, ignoring
WARNING: unknown mimetype for _static/installation/files/etc/httpd/conf.d/dataverse.example.edu.conf, ignoring
WARNING: unknown mimetype for _static/installation/files/etc/httpd/conf.d/ssl.conf, ignoring
WARNING: unknown mimetype for _static/installation/files/etc/shibboleth/shibboleth2.xml, ignoring
WARNING: unknown mimetype for _static/installation/files/etc/shibboleth/attribute-map.xml, ignoring
WARNING: unknown mimetype for _static/installation/files/etc/shibboleth/dataverse-idp-metadata.xml, ignoring
WARNING: unknown mimetype for _static/installation/files/etc/shibboleth/shibGroupTestShib.json, ignoring

**Comment by mheppler** [comment]
Fixed the following warnings:

- [x] WARNING: Title underline too short.
- [x] WARNING: Inline literal start-string without end-string.
- [x] WARNING: undefined label: label-name (if the link has no caption the label must precede a section header).

**Comment by pdurbin** [comment]
@mheppler while you're in there can you please delete all the junk that got committed into https://github.com/IQSS/dataverse/tree/develop/doc/Sphinx ? Thanks.

**Comment by mheppler** [comment]
No more warnings.

![screen shot 2016-09-29 at 12 08 59 pm](https://cloud.githubusercontent.com/assets/687227/18962446/e0961b0c-863e-11e6-83db-88d22d231155.png)

**Comment by mheppler** [comment]
Removed duplicate img files, as well as the unnecessary directories they were contained in, as @pdurbin requested above.

**Comment by pdurbin** [comment]
Awesome! Quick! Make all the warnings fatal! Maybe this will help: https://github.com/krb5/krb5/commit/c54a33b520afb8d1e7c6c37db15189185f220ada

**Comment by kcondon** [comment]
@mheppler @pdurbin  OK, most of the warnings are gone but on  my build, there are still 18:

writing content.opf file...
WARNING: unknown mimetype for _static/jquery.js, ignoring
WARNING: unknown mimetype for _static/underscore.js, ignoring
WARNING: unknown mimetype for _static/doctools.js, ignoring
WARNING: unknown mimetype for _static/websupport.js, ignoring
WARNING: unknown mimetype for _static/navbar_from_dataverse_org.js, ignoring
WARNING: unknown mimetype for _static/navbarscroll.js, ignoring
WARNING: unknown mimetype for _static/searchtools.js, ignoring
WARNING: unknown mimetype for _static/installation/files/issues/2180/grizzly-patch/glassfish-grizzly-extra-all.jar, ignoring
WARNING: unknown mimetype for _static/installation/files/issues/2180/grizzly-patch/readme.md, ignoring
WARNING: unknown mimetype for _static/installation/files/etc/init.d/solr, ignoring
WARNING: unknown mimetype for _static/installation/files/etc/init.d/glassfish, ignoring
WARNING: unknown mimetype for _static/installation/files/etc/httpd/conf.d/dataverse.example.edu.conf, ignoring
WARNING: unknown mimetype for _static/installation/files/etc/httpd/conf.d/ssl.conf, ignoring
WARNING: unknown mimetype for _static/installation/files/etc/shibboleth/shibboleth2.xml, ignoring
WARNING: unknown mimetype for _static/installation/files/etc/shibboleth/attribute-map.xml, ignoring
WARNING: unknown mimetype for _static/installation/files/etc/shibboleth/dataverse-idp-metadata.xml, ignoring
WARNING: unknown mimetype for _static/installation/files/etc/shibboleth/shibGroupTestShib.json, ignoring
WARNING: unknown mimetype for _static/installation/files/home/rpmbuild/rpmbuild/RPMS/x86_64/rapache-1.2.7-rpm0.x86_64.rpm, ignoring
writing toc.ncx file...
writing Dataverse.epub file...
build succeeded, 18 warnings.

**Comment by mheppler** [comment]
Fixed mistakenly omitted toctree format change on User Guide index.

**Comment by mheppler** [comment]
Moved the warnings related to the epub version of the docs into a new issue #3391. There is also the older issue (#3134) related to the warnings specific to building the pdf version.
