### ISSUE TITLE
Dataverse theme logos directory name repeated many, many times in code

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3182]
Centralize the logo directory name and path in settings. "logos" directory name appears over 10 times in code. 
-  Filed under: technical debt.

<img width="697" alt="dataverse_-_netbeans_ide_8_0_2" src="https://cloud.githubusercontent.com/assets/1036060/16286865/f6abc58e-3893-11e6-8074-769ab8076f03.png">

**Comment by pdurbin** [comment]
https://github.com/IQSS/dataverse-aws/issues/10 might be related but I'm not sure.

**Comment by pdurbin** [comment]
We're living with the code as it is. If someone wants to work on this, please open a new issue. Closing.
