### ISSUE TITLE
File type not recognized on dropbox upload by ingest

### ISSUE THREAD

**Issue by tomck** [IQSS/dataverse#3183]
Scenario: .tar.xz files to compress fastq as much as possible (statistically better than .cram even) stored in Dropbox. (Transfer and saving takes forever, but that's not the issue.)

Filetype determines fine when using browser upload, but "unknown" when using dropbox upload.
![screenshot 2016-06-24 10 07 55](https://cloud.githubusercontent.com/assets/324521/16341702/1bbedff8-39f4-11e6-88e8-ee9c5d55f336.png)

Have not tried SWORD upload yet.  Environment: CentOS 7 on Microsoft Azure.

Related? #376

**Comment by pdurbin** [comment]
@tomck based on your comment at https://github.com/IQSS/dataverse/issues/3194#issuecomment-310656642 I assume you are no longer personally interested in this issue either so I'm closing it. Thanks.
