### ISSUE TITLE
catch builtinuser e-mail field mismatch when Shibboleth is enabled

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#3184]
This is possibly a tack-on to #2937 or possibly a suggestion, or possibly just noise.

During installation I set the dataverseAdmin account to my university address, with the intention that it be temporary until I found out where our archivists wanted such messages to go. Once I enabled Shib, a local login to the dataverseAdmin account found my e-mail address and dutifully offered to convert dataverseAdmin to a Shib account. I updated the address in the authenticateduser table but missed it in the builtinuser table. Until I found the mismatch in the database, dataverseAdmin login attempts would echo address mismatch SEVEREs to server.log but only present the login screen back to the end user, as if no login had been attempted.

We might want to add a note about this to the Shib docs, or maybe catch that error to send it back to the end-user in the browser, or since this is ultimately a Layer 8 Problem, close this issue and pardon my noise.

In any case, I hope you all have a great weekend!

**Comment by pdurbin** [comment]
> I updated the address in the authenticateduser table but missed it in the builtinuser table

Hmm. I hope most users don't hack on database tables directly. Much better would be to change an email address via the GUI. I guess an API endpoint could be added some day.

Anyway, @donsizemore I'm glad you were able to recover. It sounds like the errors in server.log were helpful as-is. Thanks for the feedback. It's not noise. 😄 

This vaguely related to #2170 which @bsilverstein95 is starting to look at.
