### ISSUE TITLE
My Data: Provide information on dataverses, datasets, and files that user actually created or edited, etc. "working set".

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3185]
My Data currently shows dataverses, datasets and files that a user has permission to and the role they have in them.

However, for curators and other admin they likely see a large set of objects they have permission to but have not personally acted upon. So this ticket is about filtering on those objects they have actually created, edited, approved, etc with some timeframe for reference.

The current use case is Sonia, who is a super user, wanted to know which dataverses, datasets, and files she created since July 1, 2015.

**Comment by pdurbin** [comment]
Closing in favor of this issue:

- #5880
