### ISSUE TITLE
Permissions: update "roles" description for "Admins" to specify this role allows you to approve requests to restricted data

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#3189]
I noticed that none of the roles, including "Admin" specifically says who can "approve" access to restricted data. I think this should be included somewhere in the "roles" description.
If this is a quick update, can we do it sooner rather than later?

**Comment by pdurbin** [comment]
For anyone wanting to work on this issue, I think the file to change is

`scripts/api/data/role-admin.json`

However, it might be one of the other "role-*" files in that directory.

**Comment by pdurbin** [comment]
These days this string is here (now that roles are internationalized):

`src/main/java/propertyFiles/BuiltInRoles.properties`

I would suggest a change like this:

```
$ git diff src/main/java/propertyFiles/BuiltInRoles.properties
diff --git a/src/main/java/propertyFiles/BuiltInRoles.properties b/src/main/java/propertyFiles/BuiltInRoles.properties
index 3c4b802000..2687843ee9 100644
--- a/src/main/java/propertyFiles/BuiltInRoles.properties
+++ b/src/main/java/propertyFiles/BuiltInRoles.properties
@@ -1,5 +1,5 @@
 role.admin.name=Admin
-role.admin.description=A person who has all permissions for dataverses, datasets, and files.
+role.admin.description=A person who has all permissions for dataverses, datasets, and files, including approving requests for restricted data.
 role.editor.name=Contributor
```
