### ISSUE TITLE
Add Dataset Title to the Dataset Version table

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3191]
If not using Solr, retrieving the DatasetVersion title from the metadata citation block can take several queries.  Would be nice to have this element exposed at the DatasetVersion level.  Or, alternatively, expose it through a cached version of a document (JSON) containing all metadata.

Current steps to retrieve the DatasetVersion title:
1.  Get the DatasetFieldType for the citation title
   - name = 'title", metadatablock.name = "citation"
2.   Get the DatasetField
   - dataset_version.id = your datasetset version, DatasetFieldType from step 1 (above)
3.  Get the DatasetFieldValue
   - dataset_field.id = DatasetField from step 2

As Queries:
(This could be done in fewer queries, more joins, etc.)
#### Step 1: Join across two tables, select from single table

``` sql
SELECT • FROM "datasetfieldtype" INNER JOIN "metadatablock" ON ( "datasetfieldtype"."metadatablock_id" = "metadatablock"."id" ) WHERE ("metadatablock"."name" = 'citation' AND "datasetfieldtype"."required" = true AND "datasetfieldtype"."name" = 'title')
```
#### Step 2: Join across two tables, select from single table

``` sql
SELECT • FROM "datasetfield" INNER JOIN "datasetfieldtype" ON ( "datasetfield"."datasetfieldtype_id" = "datasetfieldtype"."id" ) WHERE ("datasetfield"."datasetfieldtype_id" = 1 AND "datasetfield"."datasetversion_id" = 26) ORDER BY "datasetfield"."id" ASC LIMIT 1
```
#### Step 3: Single table query

``` sql
SELECT ••• FROM "datasetfieldvalue" WHERE "datasetfieldvalue"."datasetfield_id" = 342 ORDER BY "datasetfieldvalue"."id" ASC LIMIT 1
```

---

Related: #761, #2110

**Comment by raprasad** [comment]
pain point: Would help with Metrics and other tasks!

**Comment by pdurbin** [comment]
We've been surviving with the code as it is and this issue doesn't have a champion. Closing.
