### ISSUE TITLE
Dropbox-like file picker for integrating Dataverse into other platforms

### ISSUE THREAD

**Issue by tomck** [IQSS/dataverse#3194]
Presently, one may upload files to Dataverse using a simple Dropbox file picker. However, as Dataverse is now being referred to as "[a dropbox for structural biologists](https://hms.harvard.edu/news/dropbox-structural-biologists)", it could be quite handy for other platforms to integrate Dataverse through a similar file picker, so that data could be further processed without requiring the user to re-download and then re-upload the data elsewhere.

**Comment by pdurbin** [comment]
@tomck are you still interested in this?

**Comment by tomck** [comment]
I left the company doing the project and afaik they're not doing it
anymore, so me personally, no.

**Comment by pdurbin** [comment]
@tomck now worries. Thanks. I'll close this issue then. Maybe in the future someone will open a similar one. Thanks for the suggestion. Good luck in your new position in the future!
