### ISSUE TITLE
Index: Harvested datasets without a distribution date (?) fail indexing

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3197]
Reported by Leonid, present in at least v4.3.1.

**Comment by scolapasta** [comment]
This was due to a change I made, but it should already be fixed in @landreev's branch.

**Comment by landreev** [comment]
So, since this is fixed in the export-harvest branch, I'm assuming it's in QA as part of the general export and harvest QA.

**Comment by kcondon** [comment]
Tested and discussed with Leonid:
The current fix works for Odum harvested datasets but others, eg. ICPSR still fail for unknown reasons. We have a temporary workaround of not indexing these datasets for v4.5 deployment but the issue still needs to be resolved long term.

**Comment by djbrooke** [comment]
Thanks @kcondon. Is this the same as #3278?

**Comment by kcondon** [comment]
Not necessarily. This was the initial issue. It was fixed, then I continued to see index failures for harvested content of unknown origin.

________________________________

**Comment by djbrooke** [comment]
Closing this in favor of #3278.
