### ISSUE TITLE
Add MyData presentation to the docs

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3198]
[MyData-Cards.pdf](https://github.com/IQSS/dataverse/files/349902/MyData-Cards.pdf)

**Comment by pdurbin** [comment]
My comment from https://github.com/IQSS/dataverse/pull/3199#issuecomment-278704381

> Let's simply add a link to https://docs.google.com/a/harvard.edu/presentation/d/1aHjOMy8FIbMVyJEZu_m4ab4ftutgQiC8y6HM47Am2z0/edit?usp=sharing somewhere under https://github.com/IQSS/dataverse/tree/develop/doc/sphinx-guides/source/developers

This would be better than a PDF we can't edit.

**Comment by pdurbin** [comment]
Down with PDFs we can't edit. Closing.
