### ISSUE TITLE
Upgrade Dataverse Guides for 4.0

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#32]
---

Author Name: **Eleni Castro** (@posixeleni)
Original Redmine Issue: 3439, https://redmine.hmdc.harvard.edu/issues/3439
Original Date: 2014-01-31
Original Assignee: Eleni Castro

---

With 4.0 being a major release, a re-write of the entire Dataverse Guides is in order.

This will involve:
* Rewrite of the User, Developer, Installer and API Guides. Eleni has uploaded all (4) on dataverse_temp: https://github.com/IQSS/dataverse_temp/tree/master/doc/Sphinx
* Review w/ Gustavo about moving to a separate repo or finding a way to always point:
** Installer Guide: to the MOST recent STABLE released version
** Developer Guide: to the Latest DEV branch version 
-* Need to a temporary place to host HTML of 4.0 Guides and Link from the UI for February Testing *(Deadline: 02/13)*.-

**Comment by posixeleni** [comment]
This is a duplicate ticket which is already being tracked by individual tickets.
