### ISSUE TITLE
Private URL: When a contributor deletes a draft of a published dataset with privateURL defined, role is not cleared.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3201]
When a contributor deletes a draft of a published dataset that has a privateURL defined, the role assignment that identifies a privateURL is not removed but the dataset draft is. This can be observed by seeing the privateURL blue banner still displaying when visiting the dataset as an admin.

This does not happen in v4.4 but happens in the private url branch.

See related ticket: #3200

**Comment by pdurbin** [comment]
I added some tests to exercise this bug ( https://github.com/IQSS/dataverse/issues/3200#issuecomment-231377876 ) but I'd like to keep the conversation in #3200.

**Comment by pdurbin** [comment]
@scolapasta please see https://github.com/IQSS/dataverse/issues/3200#issuecomment-232458080

**Comment by pdurbin** [comment]
@scolapasta and @michbarsinai blessed the fix at 24df280 so I merged it into pull request #3111. Passing to QA.

**Comment by kcondon** [comment]
Works, closing.
