### ISSUE TITLE
Widgets: Dataverse listing widget, clicking page 2 opens on dataverse site, not within widget.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3202]
Child objects are supposed to open within a widget on the remote site but clicking on page 2 or next button in a long dataverse listing opens back on Dataverse site.

**Comment by scolapasta** [comment]
@bradleycaccivio the links on the search-include-pager should work the same as the links in the sort section of the search-include fragment.

**Comment by kcondon** [comment]
Works, closing.
