### ISSUE TITLE
Add Variable List View with Frequencies

### ISSUE THREAD

**Issue by tlchristian** [IQSS/dataverse#3205]
With TwoRavens replacing the 3.x analysis capability, we've lost the variable list view that allows users to view individual variables along with their labeled value frequencies in one nice table.  

I thought I remembered hearing an intern working on this, but I'm not sure if there are any plans to add this classic function.  Any updates on this?  I know that many of our users will miss the variable list view when we upgrade to 4.x.

**Comment by djbrooke** [comment]
@tlchristian - the work that you reference is here:

https://github.com/IQSS/data-viz

I don't have any updates at this time. I'll get you something soon.

**Comment by scolapasta** [comment]
We've also discussed adding this list as part of the new File Landing page.

**Comment by pdurbin** [comment]
@tlchristian how similar is your request to #3604?

**Comment by pdurbin** [comment]
@tlchristian any thoughts on this issue since we just had a community meeting? There was a nice demo of "Data Explorer" and new features coming to TwoRavens.

**Comment by stevenmce** [comment]
@pdurbin @amberleahey @jggautier this feeds into the recent DDI-Dataverse discussions on extending the set of DDI metadata fields supported in Dataverse. Also relevant here:
- #962 on editing metadata - having an interface to edit variable metadata would be excellent. 
- @amberleahey and Kevin worthington's data explorer systems which leverage this metadata (per the DCM2017 presentations - https://osf.io/w5zsh/).

**Comment by pdurbin** [comment]
According to @donsizemore at http://irclog.iq.harvard.edu/dataverse/2018-10-04#i_74773 thu-mai sez "yes, data explorer does give us what i wanted". Hooray! So everyone who wants this should install Data Explorer, linked from http://guides.dataverse.org/en/4.9.4/installation/external-tools.html
