### ISSUE TITLE
Documentation: Consider adding Two Ravens site and guide to our own Two Ravens user guide section.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3206]
We received a comment that it was not immediately clear how to use Two Ravens so we may consider linking to the Two Ravens site and user guide pdf as well as possibly an instructional video. Sent email to the Two Ravens team.

**Comment by pdurbin** [comment]
As of 4.6.1 this doc abruptly ends with a colon as if the author had to run.

http://guides.dataverse.org/en/4.6.1/user/data-exploration/tworavens.html

![screen shot 2017-03-29 at 4 09 16 pm](https://cloud.githubusercontent.com/assets/21006/24474308/2bad630e-149a-11e7-81d2-5d55f2c78513.png)

**Comment by landreev** [comment]
Yeah, we spoke about this as we worked on the new installation guide. 
Fixing this old user guide was totally out of scope for #2212; but yes, we'll do exactly what this ticket was opened for - I'll add the links to the TwoRaven's own user guide, on their project site, to the top of the page.

**Comment by landreev** [comment]
OK, I added this to the top of the Dataverse tworavens user guide: 

Please note: This document is a bit old and may need an update. The TwoRavens
project has a more recently published user guide on their site: http://2ra.vn/papers/tworavens-guide.pdf. 

this is done as part of #2212. 
Should be safe to close this issue (?).

**Comment by pdurbin** [comment]
Wow, http://2ra.vn/papers/tworavens-guide.pdf is really nice. Good find. I went ahead and put this issue in QA in https://waffle.io/IQSS/dataverse after looking at ac1b3ad which looks good.
