### ISSUE TITLE
Preserve query parameter when redirecting from login page.

### ISSUE THREAD

**Issue by felliott** [IQSS/dataverse#3207]
When an OSF user is connecting their Dataverse account, we give them a link to `/dataverseuser.xhtml?selectTab=apiTokenTab` that they can click on to go directly to their api token. If they haven't logged in yet, they are sent to a login screen. The redirect function of the login page strips the query parameter from the original url, so after a successful login they are sent to `/dataverseuser.xhtml`, but not the token tab. It's a minor thing, but would it be possible to preserve the query parameter or provide some way to send them straight to the token tab after login? Thank you!

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
