### ISSUE TITLE
rApache RPM for RHEL/CentOS 7

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#3208]
In #975 an rApache RPM was created for RHEL/CentOS 6 (hosted by HMDC and linked from http://guides.dataverse.org/en/4.4/installation/r-rapache-tworavens.html ) but a number of users are upgrading to RHEL/CentOS 7 ( https://groups.google.com/d/msg/dataverse-community/KIwy7bYgo0Q/X0AamCDzBQAJ ) and would appreciate an RPM so they can run TwoRavens.

**Comment by pdurbin** [comment]
In 4daf136 I pushed an rApache RPM for CentOS 7 (and the files used to build it) to a branch. The RPM is only 29 KB so the idea is that it will be downloadable from the guides just like our custom Grizzly patch.

Anyway, if someone out there with CentOS 7 would like to try the RPM, you can download it from https://github.com/IQSS/dataverse/blob/4daf136b59a5dc7bfbf0f5395194057544128484/doc/sphinx-guides/source/_static/installation/files/home/rpmbuild/rpmbuild/RPMS/x86_64/rapache-1.2.7-rpm0.x86_64.rpm?raw=true

Then you can install it with `rpm -Uvh rapache-1.2.7-rpm0.x86_64.rpm`. I don't know anything about rApache but I'm able to install the RPM at least. 😄

**Comment by pdurbin** [comment]
I made 4daf136 into pull request #3210. Basically, I'm adding an experimental rApache RPM for CentOS 7 that described in and downloadable from the "R, rApache and TwoRavens" section of the Installation Guide. I can confirm that the RPM can be installed on CentOS 7. I've reached out to the Dataverse community at https://groups.google.com/d/msg/dataverse-community/KIwy7bYgo0Q/EkdtbW5eAwAJ for help in testing this new RPM.

Please not this RPM was build using rApache 1.2.7 (for CentOS 6 we use rApache 1.2.6). I would have built an RPM for 1.2.8 ( @landreev and I agreed that using the latest version, which might have bug fixes, would be prudent) but the RPM spec file is still for 1.2.7. So that's what I built. I opened a issue at https://github.com/jeffreyhorner/rapache/issues/42 for updating the RPM spec file to 1.2.8.

Passing to QA. You'll need a CentOS 7 environment to test with.

**Comment by kcondon** [comment]
This is currently unsupported but was tested by Don from Odum.

**Comment by donsizemore** [comment]
Successfully tested by Don from Odum! (and thanks @landreev for finding the versioning issue with preprocess.R)

**Comment by kcondon** [comment]
Yes, tested successfully and found to work, thanks! Closing.

**Comment by Venki18** [comment]
Hi Phil, Thanks a lot for your kind help. We are able to install Rapache from the RPM that you have posted here.

**Comment by pdurbin** [comment]
@Venki18 fantastic! If either you or @donsizemore can confirm that rApache is working (not just installed, which I did myself), please let us know! In pull request #3210 I'm calling this RPM "experimental" in the guides and provide a link to download it. Come to think of it, above @donsizemore has already said "Successfully tested by Don from Odum!" That sounds like it's working. Either way, we'd probably continue to call the RPM experimental until https://dataverse.harvard.edu has switched to CentOS 7.

**Comment by pdurbin** [comment]
@donsizemore said "the rapache/centos7 rpm worked well at odum" at http://irclog.iq.harvard.edu/dataverse/2016-07-21 so I think pull request #3210 is in good shape.

**Comment by Venki18** [comment]
Hi Phil

The rapache rpm worked well for us too. Thank you very much for your help. 

Have few other things to report to so thought would drop an email on that but time didn’t permit it. Sorry for not having informed you earlier.

Regards
Venki
