### ISSUE TITLE
Remove or rename "/api/test" endpoint

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#3209]
Yesterday @michbarsinai and I discussed https://github.com/IQSS/dataverse/blob/v4.4/src/main/java/edu/harvard/iq/dataverse/api/TestApi.java and how we strongly require that people installing Dataverse block the "/api/test" endpoint.

http://guides.dataverse.org/en/4.4/installation/config.html#blocking-api-endpoints says, "There is a “test” API endpoint used for development and troubleshooting that has some potentially dangerous methods."

@michbarsinai says he doesn't have any automated testing that depends on these methods. Tests at https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-apitest-develop/ won't fail if they are removed or moved. I **think** this could be as simple as putting it under the "admin" namespace with...

```
-@Path("test")
+@Path("admin/test")
```

... and then removing the warning in the docs mentioned above.

**Comment by pdurbin** [comment]
@michbarsinai do you have a preference for changing the `@Path` as described above or should we simply blow away `src/main/java/edu/harvard/iq/dataverse/api/TestApi.java` since it isn't be used by any automated testing. I'd prefer to simply blow it away (and remove the warnings in the guides).

**Comment by michbarsinai** [comment]
It's very useful for testing commands. If there's a way of not packaging it into production, that's great. But having a way of bypassing the UI is very important.

**Comment by pdurbin** [comment]
@michbarsinai ok, so let's put it under "/api/admin" like I'm proposing above by changing the path. And updating the guides to tell sysadmins not to worry about blocking "/api/test" in production.

**Comment by kcondon** [comment]
Verified endpoint was moved by calling permissions. Watch this space for further developments.

**Comment by pdurbin** [comment]
@scolapasta asked me to move the two useful methods under "admin" which I did at 95774dd

**Comment by kcondon** [comment]
Confirmed, closing
