### ISSUE TITLE
Support multi-core Solr instances

### ISSUE THREAD

**Issue by bricas** [IQSS/dataverse#3212]
Currently, Dataverse assumes the URL you're entering for Solr is a single-core instance (as evidenced by the code adding /solr to the config url)

https://github.com/IQSS/dataverse/blob/v4.4/src/main/java/edu/harvard/iq/dataverse/search/SearchServiceBean.java#L91

If the config option was changed to be the full endpoint URL to Solr, (so localhost:8983/solr instead of just localhost:8983) then Dataverse could support multi-core instances which have URLs that look like localhost:8983/solr/corename/

Although this config change will break existing installs, if there was an upgrade detection process, then you could easy just add /solr to the end of the existing config value and everything would be functional once again.

**Comment by pdurbin** [comment]
Related: #4762
