### ISSUE TITLE
Documentation enhancement for Apache config for mod_shib on Ubuntu

### ISSUE THREAD

**Issue by bricas** [IQSS/dataverse#3213]
I'm installing Dataverse on Ubuntu 14.04 with Apache 2.4 / mod_shib & mod_proxy_ajp.

After some trial and error, I was able to find a working combination:

```
<VirtualHost *:443>
  # yadda yadda ...

  <Location />
    Require all granted
  </Location>

  # don't pass paths used by rApache and TwoRavens to Glassfish
  ProxyPassMatch ^/RApacheInfo$ !
  ProxyPassMatch ^/custom !
  ProxyPassMatch ^/dataexplore !
  # don't pass paths used by Shibboleth to Glassfish
  ProxyPassMatch ^/Shibboleth.sso !
  ProxyPassMatch ^/shibboleth-ds !

  # Glassfish
  ProxyPass / ajp://localhost:8009/

  <Location /shib.xhtml>
    AuthType shibboleth
    ShibRequestSetting requireSession 1
    require valid-user
  </Location>
</VirtualHost>
```

Most importantly is the presence of the `Require` line early on:

```
  <Location />
    Require all granted
  </Location>
```

I had it after the `<Location /shib.xhtml>` section, and was getting authenticated, but no ENV variables were being sent to Dataverse. Moving it higher up was the fix.

**Comment by pdurbin** [comment]
@lwo you might be interested in this since you have "Shibboleth" at https://github.com/IQSS/dataverse-puppet#to-do :smile:

**Comment by pdurbin** [comment]
It would be nice to add the contribution by @bricas above to the Installation Guide even though Ubuntu isn't supported per #1059.

**Comment by pdurbin** [comment]
@bricas do you feel like making a pull request for this?

**Comment by bricas** [comment]
Sure! I'll try and whip up a doc patch ASAP.

**Comment by pdurbin** [comment]
Pull request #4871 looks good and fixes 404s in doc/shib/shib.md because we deleted the old "auth" branch. Moving to QA.
