### ISSUE TITLE
Enable/Disable Exploration options per dataset and/or dataverse

### ISSUE THREAD

**Issue by mercecrosas** [IQSS/dataverse#3216]
Add a switch to enable and disable TwoRavens and other exploration tools at the dataset and dataverse level. Dataverse admins and dataset owners should be able to do this.

This is requested by the Center for Health Decision Science (CHDS) at the School of Public Health, and was requested in the past by other groups.

**Comment by zward** [comment]
We're having trouble getting TwoRavens to work with our files, and our users are getting confused since they end up there quite often when trying to look at the data.  An option to disable TwoRavens on a dataset would be great while we work out any issues that may be happening at ingest.

**Comment by pdurbin** [comment]
TwoRaven is long gone. The current tools are here: https://guides.dataverse.org/en/6.0/admin/external-tools.html

Closing.
