### ISSUE TITLE
File Replace

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3220]
To support Provenance, we need to add versioning/replace functionality for DataFile objects.

Basics:

  - User may replace an existing dataset file with a new one:
     - via UI
     - via API
  - File versions are tied to dataset versions

Technical notes:

Internal storage:
 - DataFile will have two extra fields:
     - Root DataFile id
     - Previous DataFile id

| DataFile id | Root DataFile ID | Previous DataFile ID |
|-------------|------------------|----------------------|
| 1           | 1                | null                 |
| 5           | 1                | 1                    |
| 7           | 1                | 5                    |
| 35          | 1                | 7                    |

Documentation/notes:  https://drive.google.com/drive/u/0/folders/0B4VvItDJwfehQjQ0bkp1dl9vdWc

**Comment by djbrooke** [comment]
[Mockups](https://iqssharvard.mybalsamiq.com/projects/filesprovenancefacetsfilter-dataverse40/File%20-%20Versions)

**Comment by djbrooke** [comment]
Moving to ready since mockups are available.

**Comment by mheppler** [comment]
Duplicate of: Files: Ability to Replace a File Instead of Deleting #2290.

**Comment by djbrooke** [comment]
Closing in favor of #2290
