### ISSUE TITLE
Widget - Footer Height Cuts Off Dataverse Project Logo

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#3223]
As reported by the OpenScholar team, the height of the footer should be looked into in order to fix a layout issue where the Dataverse Project logo is cut off when the width of the widget is very narrow.

![screen shot 2016-07-26 at 3 10 17 pm](https://cloud.githubusercontent.com/assets/687227/17182093/63cb627e-53f0-11e6-9f89-7f1921666d15.png)

**Comment by mheppler** [comment]
Fixed minor layout issue with the Dataverse Project logo in the footer in widget view.

![screen shot 2016-07-27 at 1 34 18 pm](https://cloud.githubusercontent.com/assets/687227/17191225/e7f2a21c-5416-11e6-84b4-939e850c6023.png)

**Comment by kcondon** [comment]
OK, looks good. Tested with html table at 400 width, saw issue, saw it disappear with new code for all widgets using footer.
