### ISSUE TITLE
Integrate Data Viz

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#3232]
There's some interest from the community in integrating the contents of the Data Viz repo with Dataverse:

https://github.com/IQSS/data-viz

**Comment by pameyer** [comment]
@djbrooke - is this interest in augmenting two-ravens specifically, or integrating other visualization tools (along the lines of what rpartridge has been working on)?

**Comment by pdurbin** [comment]
Here's a screenshot from an experiment at https://dv.sbgrid.org/dataset.xhtml?persistentId=doi:10.15785/SBGRID/190 that shows what @rpartridge has been working on. Note the new "Visualization" tab:

![screen shot 2016-08-02 at 10 39 47 am](https://cloud.githubusercontent.com/assets/21006/17332677/91435f5c-589d-11e6-87b7-f508378853f1.png)

**Comment by djbrooke** [comment]
Oops! Closing this in favor of #3205, which I did not see and is more specific. Feel free to move the convo to there if it is still relevant.

**Comment by djbrooke** [comment]
(and tagging @tlchristian)
