### ISSUE TITLE
Groups: Allow shib/ ip groups to be discovered in the UI.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3233]
It is not obvious to less technical admins which ip or shib groups exist to assign roles to. While there are API commands that list each type, someone who exclusively uses the UI would not have access to this. 

Also, maybe expand the User Guide to discuss the use of groups and their types in more detail.

There is some useful information on explicit groups on the groups page when there are no groups listed.

It may be useful to add shib and ip groups to the groups page as well or as Phil mentioned, perhaps to the Dashboard. Not sure how they will be used.

**Comment by djbrooke** [comment]
Closing in favor of #3106, will leave this note there.
