### ISSUE TITLE
API:  Provide an API-firendly 404 on nonexistent endpoints

### ISSUE THREAD

**Issue by michbarsinai** [IQSS/dataverse#3235]
currently, there's an HTML 404 page there. Should be JSON.

**Comment by mheppler** [comment]
:thumbsup: :star:

**Comment by pdurbin** [comment]
Related: #1312

**Comment by michbarsinai** [comment]
NOTE TO QA: For this change to work, you need to undeploy the app, do a clean build, and then deploy again. Hot deployment might skip the provider-detection step of loading the API part, and so the exception handlers that create the custom messages are not being used.

To test:
1. access a non-existent endpoint (should yield a 404 JSON message)
2. access an existing endpoint with an unsupported method (e.g. `curl -X HEADER -H"Accept: application/json" http://localhost:8080/api/datdasets/23`). (should yield a 405 JSON message)

**Comment by kcondon** [comment]
Works as described. Closing.
