### ISSUE TITLE
Caching data file locally on harvesting from a Dataverse OAI server

### ISSUE THREAD

**Issue by anuj-rt** [IQSS/dataverse#3236]
A new feature is added to the existing export-harvest code to cache data files on the local storage.
This caching extends the existing harvesting functionality.

**Comment by pdurbin** [comment]
From what I understand, the code is in pull request #3239 but the `4.5-export-harvest-swift` branch is currently 731 commits the `develop` branch.

**Comment by pdurbin** [comment]
Closing until we decide to pick this up again.
