### ISSUE TITLE
Manual Provenance Integration for Files

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#3238]
File and dataset level, we'll need a few things in order to populate the [Provenance system](https://www.usenix.org/conference/tapp12/workshop-program/presentation/macko) with relevant information from Dataverse so that provenance graphs can be displayed (#3245). 

At the file level we need to:
- Allow a User to upload a provenance file and/or allow a user to add text explaining the transformation
- Call “prov.setversiontransformation” when free text is added in a draft state
- Call “prov.(TBD)versiontransformation” when a file is added in a draft state
- Call ? to import Provenance when a file is published

**Comment by djbrooke** [comment]
We'll get a demo and code walkthrough from @jacksonokuhn next Friday and learn more about what we should expect.

**Comment by djbrooke** [comment]
Mockups are set, but we need information from the Provenance team about what will be displayed under the tab and what error conditions to expect.

**Comment by sekmiller** [comment]
On the provenance tab we allow the user to upload a provenance file.  We have to add a process for ingesting these files. It's my understanding that they will be saved to the provenance file directory. Phil suggested that this might need to be configurable.

**Comment by pdurbin** [comment]
Yeah, I was suggested that for now the files could be put in `10.5072/FK2/ZPWUDQ/provenance` or whatever. I'm sure people like @pameyer and @bmckinney will be very glad to hear that the eventual plan is to put the provenance files on a separate file system because they definitely don't want these files intermixed with data they're trying to do computation on! But yes, a sane default for the location and a configuration option would be welcome, I can only imagine.

**Comment by mheppler** [comment]
The mockups are being finalized, and can be reviewed in [Balsamiq](https://iqssharvard.mybalsamiq.com/projects/filesprovenancefacetsfilter-dataverse40/Dataset%20-%20Edit%20Provenance).

![screen shot 2016-11-14 at 2 25 49 pm](https://cloud.githubusercontent.com/assets/687227/20279352/47695d66-aa76-11e6-8451-b67a7ac4d1f6.png)

**Comment by mheppler** [comment]
Test JSON file from Matthew

https://github.com/MKLau/json_example

Test JSON files from Thomas

https://www.w3.org/Submission/prov-json/

Test JSON files from @jacksonokuhn 

https://github.com/tfjmp/provR/tree/master/tests

**Comment by djbrooke** [comment]
Replaced by #4343
