### ISSUE TITLE
Document how to migrate passwords from DVN 3.x to Dataverse 4

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#3240]
https://github.com/IQSS/dataverse/blob/v4.4/scripts/migration/migration_instructions.txt#L111 says the following:

```
12. (when ready for users to log in) add user passwords

[how?]
```

Users are confused by this, most recently at http://irclog.iq.harvard.edu/dataverse/2016-08-05#i_39166

**Comment by pdurbin** [comment]
Back in early August, @donsizemore made a pull request at #3242 to fix this issue so I'm moving it to code review at https://waffle.io/IQSS/dataverse

**Comment by pdurbin** [comment]
Oh, I believe that @scolapasta is in the best position to code review pull request #3242 so I'll make him the assignee. He originally sent the fix in an email called "Odum Upgrade process" on August 5th. @donsizemore replied with "Gustavo, you are wonderful!" which is, of course, true. 😄

**Comment by donsizemore** [comment]
that was @scolapasta 's SQL query which worked perfectly for Odum's migration. i submitted the pull request to fill in the [how?] section in the docs.
