### ISSUE TITLE
support directory structure visualization of transfered data files

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#3247]
Data files transferred through the [Data Capture Module](https://github.com/IQSS/dataverse/issues/3145), data sets with data files that have directory structure available should display that structure. 

Related to https://github.com/IQSS/dataverse/issues/2249, but distinct in that this doesn't require supporting re-organization of uploaded files (and possibly should support disabling such an option in the UI).

**Comment by mheppler** [comment]
Closing this issue in favor of #2249. Your comments, @pameyer, will be copied over, to make sure we deliver a feature that supports your use case.
