### ISSUE TITLE
Support multiple dataset (or datafile) level download URLs

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#3248]
For data sets where the data files are available at multiple locations (which are known to the dataverse installation - will need a related issue for that), the dataset landing page should display all of the URLs.

It might be helpful to try and recommend a particular distribution URL (aka - recommend a download URL close to the location of the user).

**Comment by pdurbin** [comment]
Related: #3249

**Comment by djbrooke** [comment]
Closing in favor of #3998.

**Comment by pdurbin** [comment]
@pameyer has this been delivered?

**Comment by pameyer** [comment]
for package files / rsal downloads, this was done a while back.
