### ISSUE TITLE
support display of non-http download URLs on dataset landing page

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#3249]
For some types of data files (e.g. large data files, or data files that have been "deposited by reference") the landing page should display one (or [more](https://github.com/IQSS/dataverse/issues/3248) non-http download URLs.

**Comment by pdurbin** [comment]
I just left a comment relating to this issue at https://github.com/IQSS/dataverse/issues/3403#issuecomment-257148631 . I believe that initially the plan is to show rsync links similar to what is currently shown at https://data.sbgrid.org/dataset/1/

![sbdg_1_-_2016-10-30_08 16 21](https://cloud.githubusercontent.com/assets/21006/19836615/4b67809c-9e7c-11e6-9f35-6cee776ec552.png)

**Comment by pdurbin** [comment]
Today @pameyer @TaniaSchlatter @scolapasta and I discussed the mockups in https://docs.google.com/document/d/1nzkuv9BW4A2xEbmGTQNqrwrcxRpGvwEgm9xHoPDW4uc/edit?usp=sharing

**Comment by djbrooke** [comment]
Closing in favor of #3998.
