### ISSUE TITLE
File Level Metadata - Tabular Metadata

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#3252]
Tabular files have additional metadata that is created during the ingest process. Some of this metadata should be shown, along with a preview, on the File Level Landing Page (#2465).

**Comment by djbrooke** [comment]
Need to check with @landreev - the metadata is generated from a tabular file and outputted in a standard format

**Comment by djbrooke** [comment]
@scolapasta  and I met with DSS yesterday. They were very helpful in providing information about ways we could improve the display of tabular metadata on the File Landing Page (#2465). We walked away with three pieces of feedback:

- It would be helpful to provide the Variable Metadata in a human-readable format. It is currently downloaded as DDI XML and is decidedly not human-readable. :)
- Information about missing data on a per-variable basis will allow users to easily see if specific variables within the file have the information they are looking for. @scolapasta mentioned that in 3.x we had the concept of "Invalid" and "Valid" data that could be investigate for use here.
- A "representation" or "overview" of the files contents (DSS encouraged me not to use the term "preview") similar to the attached image.

![img_7532](https://cloud.githubusercontent.com/assets/7773392/19734249/d716b44c-9b74-11e6-9298-eefde926949d.JPG)
- Variables on left side instead of across the top (to prevent the endless horizontal scroll
- A label or other descriptor next to each variable
- A the first ~5 values for each variable

I thanked the DSS folks and told them that this will provide a good basis for generating more feedback from the community.

**Comment by mcrosas** [comment]
Consider also embedding the DDI Explorer (renamed Data Explorer) developed by ScholarsPortal in the file page for a tabular file. This would give a good preview/summary of the data without having to download the data values.

**Comment by raprasad** [comment]
(tangentially metadata related)

basic tabular preview example using file id ```2966861```:

 - basic/basic table: https://services.dataverse.harvard.edu/miniverse/datafile/table-preview-html/2966861
 - json:   https://services.dataverse.harvard.edu/miniverse/datafile/table-preview-json/2966861
 
Add any id of a _published_ file to the urls above

---

![mozilla_firefox_and_behavioral_data](https://cloud.githubusercontent.com/assets/1036060/22268639/44195324-e256-11e6-9c4f-42bb63232197.png)

**Comment by pdurbin** [comment]
The comments above were all made before external tools were shipped in PR #4298.

These days, we very likely say that this should be an external tool, a preview tool. So I'd suggest anyone who is interested in this should create an issue at https://github.com/gdcc/dataverse-previewers

Meanwhile, it's probably safe to close this issue.

**Comment by pdurbin** [comment]
Related:

- #6455
- #7930
- #8240

**Comment by sbarbosadataverse** [comment]
Closed per Phil's followup above

**Comment by qqmyers** [comment]
FWIW: There is a tabular previewer these days. I don't think it uses the extracted file-level metadata though (it just shows a tabular view of the file contents), so that could be an improvement.
