### ISSUE TITLE
Sign Up Url - Session ID

### ISSUE THREAD

**Issue by Venki18** [IQSS/dataverse#3254]
This is part of a series of issues raised by NTU libraries as discussed with @pdurbin

Refer to other issue - #3253 

The jsession ID that is generated when the user clicks on "Sign Up" url. The appscan report says that the session ID generated before the user log in can be modified or altered by an middle man. So the session ID must be generated after the sign up is completed. This was flagged as Medium vulnerability.

When testing the url with and without the jsessionid the effect is the same. Is this session ID in anyway required for the sign up. Can this be disabled?

/dataverseuser.xhtml?editMode=CREATE&redirectPage=%2Fdataverseuser.xhtml

/dataverseuser.xhtml;jsessionid=2aaf45f07480a9153e53bffbd921?editMode=CREATE&redirectPage=%2Fdataverse.xhtml

**Comment by pdurbin** [comment]
For now I'll just include something I wrote internally:

"Note that the default tracking-mode in GlassFish v3 is COOKIE and URL."

https://blogs.oracle.com/swchan/entry/change_session_id_on_authentication

Looks like we could make it just COOKIE like this (in web.xml):

    <session-config>
        <tracking-mode>COOKIE</tracking-mode>
    </session-config>

I'm asking about it: https://javabot.evanchooly.com/logs/%23glassfish/2014-10-31

**Comment by pdurbin** [comment]
@Venki18 are you still interested in a fix for this issue? My understanding is that you don't like it when `jsessionid` appears in the URL.
