### ISSUE TITLE
Metrics / demo.dataverse.org: Make the postgres db (dvndb) accessible from the public IP

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3257]
Required for https://github.com/IQSS/dataverse/issues/3229

---

For testing the Heroku metrics application, make the postgres "dvdb" database accessible via demo.dataverse.org's public IP

- Once this is done, Evan can update the firewall rules so Heroku can access it

**Comment by pdurbin** [comment]
@raprasad is this done? I'm moving this to Code Review in https://waffle.io/IQSS/dataverse

**Comment by raprasad** [comment]
Done.
