### ISSUE TITLE
Internationalization: search and indexing

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#326]
---

Author Name: **Philip Durbin** (@pdurbin)
Original Redmine Issue: 3741, https://redmine.hmdc.harvard.edu/issues/3741
Original Date: 2014-03-18
Original Assignee: Philip Durbin

---

Gustavo and I agreed today that we should think about how to internationalize search and indexing.

For example, the dataset field "title" is defined in one of the metadata tsv files. Titles for datasets are indexed under "title". Advanced search helps you populate "title:yourSearchTerm". But what would all of this look like in a different language. In a Spanish installation, would we index titles under the field "título"?

For now I'll assign this to Gustavo to think about when we'd like to put effort into this.

---

Related issue(s): #209
Redmine related issue(s): [3623](https://redmine.hmdc.harvard.edu/issues/3623)

---

**Comment by pdurbin** [comment]
Closing in favor of #209.
