### ISSUE TITLE
Export: Add a paragraph in admin section about how export behaves generally.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3261]
While the visible aspects of Export are an export metadata button and two api calls (export dataset, export all), it would be good for administrators to understand how export functions generally: when does it run, where does it put stuff, any logging, what happens on failure, what formats are exported, how it might interact with import?, what currently makes use of export (harvest server).

**Comment by djbrooke** [comment]
I'll do this as part of my text edits.

**Comment by landreev** [comment]
Kevin, Danny, 
In addition to Steve's entry on the API "datasets/export" command, in the User Guide, there is also a small section on export in the Admin guide. Please review, and see if it's sufficient, and/or if you can think of more info to add to it?

**Comment by djbrooke** [comment]
Link to the documentation below. I think this is OK for now. Closing this. 

https://github.com/IQSS/dataverse/blob/4.5-export-harvest/doc/sphinx-guides/source/admin/metadataexport.rst
