### ISSUE TITLE
Harvest: Exception error banner support email does not include math challenge numbers so won't work.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3265]
This problem has appeared before: the numbers do not appear in the math challenge required to send a support email in the case of an exception so no email can be sent.

The use case was to enter more than 30 chars as the client nickname, see exception when save.

**Comment by landreev** [comment]
Just to make sure I understand - this is not immediately related to harvesting and export; you are just that this has stopped working during the development of this release, correct?

**Comment by landreev** [comment]
I meant "you are just REPORTING that this has stopped working..."

**Comment by scolapasta** [comment]
This is not related to this release specifically. It is the math challenge
for the general exception. The other math challenge issue is still open for
this user case.

**Comment by djbrooke** [comment]
#3036 is the other Math Challenge issue.
