### ISSUE TITLE
Harvest: Server archive type could use better explanation; clicking on datasets harvested with incorrect type results in 404 error.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3266]
The last step in creating a harvest client is choosing a server archive type.  If you choose the wrong type, the redirect to the original source is broken and throws a 404. It is my understanding that "...we cook the redirect urls based on it, among other things."

The current help text says, 

Select the archive type that best describes this remote server in order to properly apply formatting rules and styles to the harvested metadata.

but it is unclear what the implication of that is or what to do or check if it is the wrong one.

**Comment by landreev** [comment]
Word, the original inline help text I wrote said something like "It is very important to properly select the remote archive type, or else ..." - then it was toned down by somebody else. 

I have just added this sentence to the current Bundle.properties: 

<b>Note</b> that improperly selecting the type of the remote archive can result in incomplete entries in the search results, and a <b>failure to redirect the user to the archival source</b> of the data.

I also describe this in a bit of greater detail in the Harvesting Client section of the guide. (under "New in Dataverse 4"). I explain why it is important to properly select this setting; and what's going to happen if you don't. And also, that it is very easy to correct, if it wasn't properly selected: that you don't need to reharvest; simply changing the setting is enough. 

Please review!

**Comment by kcondon** [comment]
OK, looks good except found some typo/formatting issues on the last sentence:
'''as failure to do so can result in information missing from the pthe search results, and, a <b>failure to redirect the user to the archival source</b> of the data!'''

**Comment by djbrooke** [comment]
Nice work @landreev and @kcondon - I made some small formatting changes directly on the branch:

https://github.com/IQSS/dataverse/commit/170e0849df2a44ec65d59dc0c631b856cd18ec80 https://github.com/IQSS/dataverse/commit/9fa91fcbb574f65e5de829a19de464d55fb62f1a

Closing...
