### ISSUE TITLE
Harvest: Deleting a client can be problematic, needs more feedback.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3267]
Harvest client delete button is always available. This can cause some problems since the harvest status is not automatically updated and the client may still be finishing up even after the harvest stats are posted. The result is nothing happens in the UI. Nada. Exceptions in logs though. Does work if you wait 5-10 mins more.

Another related issue is when deleting large but not running clients. When you click delete there is no feedback so you click a couple more times, etc. In the logs, each click results in a delete request. Once the first finally succeeds, the rest throw (harmless) errors. The user does not know the delete is in progress though.

**Comment by landreev** [comment]
OK, I've made the following improvements: 
When you start a harvest now, you should see the status of the client change to "inporgress". The run, edit and delete buttons will become disabled while the harvest is in progress. 
So this will prevent a user from trying to delete a running harvest. 

While the delete is in progress, yes, it looks like it was possible to click the delete buttons again, even though there was the spinner running. (I believe we saw something similar on other pages too). The buttons should be blocked now while a client is being deleted.

**Comment by kcondon** [comment]
Works great! Closing.
