### ISSUE TITLE
Harvest: Remove the metadata.tmp files left in /tmp directory

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3269]
This is a known task to be taken before releasing this feature. Right now, harvesting ends up leaving lots of metadata.tmp files in the /tmp directory. This becomes a cleanup/ maintenance issue unless our app cleans up after itself.

**Comment by landreev** [comment]
Checked in code to delete all these temp files after the import is complete. 
Please re-test.

**Comment by kcondon** [comment]
OK, seems to be working. Closing
