### ISSUE TITLE
Harvest: harvest client does not check for unique identifiers.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3274]
I am able to harvest an existing dataset from one web server pointing to the same db to the other web server pointing to the same db. This shows the client does not detect duplicate id's. 

While this particular use case is likely only a test case, it may be possible to harvest the same id's from different, non dataverse OAI servers.

**Comment by landreev** [comment]
Hmm. Could you please verify what happened there? 
I DO check for duplicate IDs, and I have verified and tested it. 
It has come up previously in a slightly different context: when during the usability session they attempted to harvest some datasets that had already been harvested, *in another dataverse*. 
When this condition is detected, the dataset is skipped, and an error entry is added to the harvest log. (and the dataset is added to the "failed" count). So... are you positive it wasn't skipped in your test? 

I guess it would be successfully imported if you were attempting to harvest it into the same dataverse... This would be a seriously "only a test case" though. :)
Please retest?

**Comment by kcondon** [comment]
Retested. Duplicate id is checked unless you are harvesting from/to same dataverse in same dv. In which case, existing dataset is updated with "This dataset is harvested from our partners..." message. 

It is true this is really just a test scenario but sometimes these reveal loopholes in underlying logic so worth at least bringing to attention of dev.

**Comment by landreev** [comment]
The bottom lines, it was an artificial test case; but it exposes real issues that can be of practical value to others. 

Good to know that the check for a global id already in the database was working. 

I have added another check to the logic for what to do if a dataset with this global id IS already in the database. So this is how it's handled now: 

If I already have this global id in the database: 

- if this existing dataset is LOCAL (non-harvested) - the harvested one is skipped (not imported); 
- if it's harvested, but exists in a different dataverse - it's skipped also. 

Only if it's both harvested and in the dataverse we are currently harvesting into, that I delete the existing dataset and replace it with the one I just harvested. 

So you should not be able to do this "self-harvesting" trick anymore, even if it's in the same dataverse...

**Comment by kcondon** [comment]
OK, works, closing.
