### ISSUE TITLE
Harvest: Harvesting all IQSS local datasets results in almost 19k success, nearly 800 failures.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3277]
The set advertises 19726 exported datasets.
The client successfully harvested 18933, with 792 failures.
18933+792=19725, or one less than were exported in the set.

So two issues:
1. 792 failures
2. The client harvest count does not agree with the total set size from the server.

**Comment by djbrooke** [comment]
We should investigate the 792 failures as a high priority issue for the 4.5 release.

**Comment by landreev** [comment]
![screen shot 2016-08-17 at 8 26 01 pm](https://cloud.githubusercontent.com/assets/737558/17757956/4c13c7e6-64b9-11e6-9d5f-c3872d747f66.png)

**Comment by landreev** [comment]
How's that for a success ratio? Good enough?

**Comment by djbrooke** [comment]
👏 👏 

Nice!

**Comment by kcondon** [comment]
This is working now, all 19726 exported datasets were harvested. Closing.

**Comment by landreev** [comment]
What are you saying Kevin? You had to re-run that harvest... as in, my word was not good enough?
This is really hurting my feelings... This lack of trust... I stayed up late, photoshopping that "zero failed" status message...

**Comment by kcondon** [comment]
Trust but verify my friend.

________________________________
