### ISSUE TITLE
Harvest: Disabling Harvest Server does not disable service, only disables UI.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3280]
Disabling the OAI Harvest server hides all existing sets and shows status disabled on the dashboard but the OAI server is still accessible by external clients.

**Comment by landreev** [comment]
Fix, please retest.

**Comment by kcondon** [comment]
OK, you now cannot harvest and it says FAILED for status. In server log it says, Error querying service. Returned HTTP Status Code: 503

Might be friendlier to say, Service unavailable or Error querying service but I suppose we don't have much room for that. Will leave it up for follow up UX.
