### ISSUE TITLE
Export: No easy way for admin to determine how many and which datatsets have failed export.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3281]
Datasets are exported on publish but can fail, in which case an error is posted to the screen but the dataset is still published. How can an admin discover this and investigate?

It would be good to have something in the dashboard to help with that or at least an export error log?

Presumably the export timer job will come along, see the export did not succeed (is export time left blank in case of failure?) and try again but does that report that info either?

**Comment by djbrooke** [comment]
@sekmiller - Can you take a look at this to determine if the logging is robust enough to give some information to the administrators so that they can troubleshoot.

**Comment by pdurbin** [comment]
Related: #3276

**Comment by sekmiller** [comment]
There's one line printed for each successfully exported dataset and summary counts added to the dedicated export log...

**Comment by kcondon** [comment]
Works, closing.
