### ISSUE TITLE
Export: Logging for export all contains no individual entries, only start and finish

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3286]
The newly added logging for export all does not contain details on what was exported, only a start and end entry. The entries for individual exported datasets are still being written to the server.log file. Maybe this is because export all is just a wrapper around individual export dataset calls and those still write to server.log?

**Comment by sekmiller** [comment]
For the dedicated export logs of ExportAll and ReExportAll, Added one line per dataset exported successfully; plus summary statistics (counts) at the end.

**Comment by sekmiller** [comment]
Fix checked into the Harvest branch

**Comment by kcondon** [comment]
Works, closing
