### ISSUE TITLE
Install script fails if postgres master password and user password differ

### ISSUE THREAD

**Issue by telnoratti** [IQSS/dataverse#3291]
To reproduce this issue, begin an install of dataverse using dvinstall/install and override the admin password to be "secret1" and the user password to be "secret2". The postgresql instance will also need to be configured with the correct admin password. The install fails saying:

    Configuring Postgres Database:

    Creating Postgres user (role) for the DVN:
    Could not create the DVN Postgres user role!
    (SQL: CREATE ROLE "dvnapp" PASSWORD 'md5e2b7be727f1bd43570cec707ac5f5b76' NOSUPERUSER CREATEDB CREATEROLE INHERIT LOGIN)

I got it to work making a couple minor changes. On line 811 of install I replaced

    my $psql_commandline = $psql_exec . "/psql -h " . $CONFIG_DEFAULTS{'POSTGRES_SERVER'} . " -U postgres -d postgres -f /tmp/pgcmd.$$.tmp >/dev/null 2>&1";

with

    my $psql_commandline = $psql_admin_exec . "/psql -h " . $CONFIG_DEFAULTS{'POSTGRES_SERVER'} . " -U postgres -d postgres -f /tmp/pgcmd.$$.tmp >/dev/null 2>&1";

There was a second related issue on lines 831-836 which caused database creation to fail.

    Proceeding.
    Creating Postgres database:
    Could not create Postgres database for the Dataverse app!
    (command: PGPASSWORD=root1234; export PGPASSWORD; /bin/createdb -h dataverse-dev.c1ovjmk8lyqm.us-east-1.rds.amazonaws.com -U postgres dvndb --owner=dvnapp)
    (psql exit code: 256)
    (STDOUT and STDERR: createdb: database creation failed: ERROR:  must be member of role "dvnapp"
    )

I fixed this by changing those lines from

    my $psql_command =
        $psql_admin_exec
        . "/createdb -h " . $CONFIG_DEFAULTS{'POSTGRES_SERVER'} . " -U postgres "
        . $CONFIG_DEFAULTS{'POSTGRES_DATABASE'}
        . " --owner="
        . $CONFIG_DEFAULTS{'POSTGRES_USER'};

to

    my $psql_command =
        $psql_exec
        . "/createdb -h " . $CONFIG_DEFAULTS{'POSTGRES_SERVER'} . " -U dvnapp "
        . $CONFIG_DEFAULTS{'POSTGRES_DATABASE'}
        . " --owner="
        . $CONFIG_DEFAULTS{'POSTGRES_USER'};

After that the rest of the install went smoothly after these changes.

**Comment by djbrooke** [comment]
@landreev - you mentioned in standup you'd take a look at this one - thanks!

**Comment by djbrooke** [comment]
@pdurbin - assigning this one your way. You said that you were going to follow up with @telnoratti about a small change to the PR.

**Comment by pdurbin** [comment]
Yeah, I gave some feedback to @telnoratti at #3292 and http://irclog.iq.harvard.edu/dataverse/2016-09-23#i_41978 but really I was passing along feedback from @landreev . As long as @landreev is happy with the final result, I think we're good.

**Comment by pdurbin** [comment]
@landreev and @telnoratti are discussing the details in pull request #3292 so I'm unassigning myself.

**Comment by kcondon** [comment]
Tested, works, merged. Closing.
