### ISSUE TITLE
Link to "Metadata Crosswalk" doc from appendix of User Guide

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#3294]
From https://help.hmdc.harvard.edu/Ticket/Display.html?id=239869

"It would be nice if you exposed the native JSON mapping somewhere online almost like a standard namespace for all to see and reference, this makes things easier for our preservation activities and METS creation. That would also cover the non-DDI and extra disciplinary elements that either fit into an existing standard or are local elements (either way this could be more transparent)."

This mapping exists as a Google Doc called "Dataverse 4.0 Metadata Crosswalk: DDI, DataCite, DC, DCTerms, VO, ISA-Tab" and technically it's readable if you know the link but I'm not sure if we're publicizing it yet. I opening this issue because I think we should link to this Google doc along site the other Google docs we link to in the appendix of the User Guide: http://guides.dataverse.org/en/4.4/user/appendix.html

This existing issue is highly related: Connect metadata field names and blocks to (de facto) standard ontologies #2357

**Comment by pdurbin** [comment]
Update it looks like we already link to the doc from here: https://github.com/IQSS/dataverse/issues/907#issuecomment-92869060

**Comment by pdurbin** [comment]
This was just requested in #3492.

**Comment by pdurbin** [comment]
I fixed this in pull request #3549. Moving to QA at https://waffle.io/IQSS/dataverse

**Comment by pdurbin** [comment]
Whoops, moving to Code Review, rather.

**Comment by pdurbin** [comment]
Whoops! Please ignore what I said about pull request #3549 which I have closed. The fix is now in pull request #3539 (the 3338-oauth-login branch). Here's the "diff": b61897b

**Comment by pdurbin** [comment]
Oh, and you can preview the fix at http://guides.dataverse.org/en/3338-oauth-login/user/appendix.html

**Comment by jggautier** [comment]
This looks good to me. Moving to QA.

**Comment by pdurbin** [comment]
@jggautier thanks for looking! I wouldn't call it done until pull request #3539 is merged but I went ahead and put the same milestone on this issue.

**Comment by djbrooke** [comment]
@pdurbin - oops, moving to done was my suggestion - didn't catch that this was on a larger PR.  I think it's fine in Done for now. As we discussed yesterday, I think it's great to fix these small things as they come up instead of putting them in github and going through the effort of tracking them, but let's discuss in the new year how to handle small, easily verifiable changes without having a bunch of issues in this limbo state (done, reviewed, QA'ed, and waiting for a merge).
