### ISSUE TITLE
2 Issues: 1. Manage Server: Gray out buttons when exporting or deleting sets; 2. Manage Clients: Reloading the page during a large delete is an issue.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3296]
We gray out buttons when deleting a client and provide a spinner if it takes a while but when deleting a really large client, such as when harvesting all of IQSS, there is not much feedback as to progress or how long it may take. Additionally, if you refresh the page or move away and come back, the grayed out status and spinner disappears and it is not clear how or when it may finish. Also, not much info in server log on status so can't see how far along it is.

Update: it appears that refreshing the page halts the delete in progress.

**Comment by kcondon** [comment]
Incorrectly submitted.

**Comment by landreev** [comment]
How about I add this to the text in the confirmation popup - "This may take a while, depending on the amount of harvested content. Do not reload the page while the delete is in progress".

**Comment by landreev** [comment]
OK, so just to clarify... We appear to be talking about 2 different things here... 

My suggestion above was for the issues you described related to deleting a *Client* with lots of harvested content. Yes, I feel we could get away with somewhat of a Band-aid solution of adding a warning to the delete confirmation. (actually, I no longer think refreshing the page killed that delete; it looks like it legitimately took about 40 min. the second time around; but regardless, this is a potential usability issue). I'll go ahead and add that warning now. 

But the subject of the ticket still talks about *Sets*. And I feel that this is something I need to address in the release as well... As in, yes, I should be graying out those buttons while the set is being updated/deleted... For the sake of consistency between the 2 pages, if nothing else. Even though deleting a set, even a large one, is never going to take as long as deleting that harvested prod. dataverse. (a linear set of simple objects vs. a complex tree of objects in the database). 

I believe I can address this fairly easily tomorrow.

**Comment by djbrooke** [comment]
@mheppler will review and update the text of the error message. 

@landreev will address the code change referred to in the third paragraph of the previous comment

**Comment by mheppler** [comment]
Revised and styled confirmation msg in the Delete Harvesting Client popup on the manage pg.

![screen shot 2016-08-19 at 1 32 16 pm](https://cloud.githubusercontent.com/assets/687227/17818441/92c5b0ce-6611-11e6-8e73-be30610874d6.png)

**Comment by djbrooke** [comment]
@landreev will update the message about not navigating from the page. He will also update the sets and client page so that the greying out happens.

**Comment by landreev** [comment]
Checked in an update for part 1, sets page. 
Please test and review. 
This update needs a database update: 

ALTER TABLE OAISET ADD COLUMN DELETED BOOLEAN;
ALTER TABLE OAISET ADD COLUMN UPDATEINPROGRESS BOOLEAN;

(note that this update does NOT need to go into the db upgrade script - because this database object is new in 4.5)

Deleting a *large* existing set, such as the all-prod set on vm5, should be an interesting test. 
(I do NOT expect it to take anywhere near 40 min. though!)

**Comment by landreev** [comment]
@mheppler 
Mike, please take a quick look at my changes to the harvesting sets page - see if anything can/needs to be made prettier. (the text lines should go into the bundle probably?)

**Comment by landreev** [comment]
@kcondon 
Just checked in more code for the Sets page (for run set reexport)

**Comment by mheppler** [comment]
@landreev -- I am not sure we want to say "Success! – Selected harvesting set is being deleted." The set is either successfully deleted or the intended action wasn't a success.

**Comment by landreev** [comment]
@mheppler 
"Success" in this context meant "successfully started a background delete job". As opposed to not being able to initiate the action - that would be the failure (also a possibility). 

But yes, let's just drop the word "success" - and let it just say "set is being deleted".

**Comment by kcondon** [comment]
Here's to Success!

**Comment by landreev** [comment]
another db update: 

ALTER TABLE HARVESTINGCLIENT ADD COLUMN DELETED BOOLEAN;

Just checked in the code, for the client.
The whole thing about doing the delete in the background, asynchronously - it looks like it's not super important for the sets at all - because even the large ones appear not to take any time at all to be deleted; but yes, it will make the whole process much less confusing potentially for large volumes of harvested data.

**Comment by kcondon** [comment]
OK, this looks good, thanks!

**Comment by landreev** [comment]
@mheppler 
@kcondon
There is no word "success" in my message. It just looks like JsfHelper.addFlashMessage() method defaults to JsfHelper.addSuccessMessage() - which always adds "Success" to the label. 
But if you want, feel free to change it to jsfHelper.addInfoMessage(); on either or both of the clients and server pages.

**Comment by landreev** [comment]
(ok, I did change the "delete in progress" messages to "info" )
