### ISSUE TITLE
Harvest: Harvest all from IQSS in JSON format had 68 failures out of 19726

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3298]
SUCCESS; 19658 harvested, 0 deleted, 68 failed.

**Comment by djbrooke** [comment]
Pulling out of 4.5. Per @landreev, this is occurring because of controlled vocabulary. I need to investigate whether or not there is an existing ticket for this.

**Comment by djbrooke** [comment]
Some background: https://github.com/IQSS/dataverse/issues/1247

**Comment by pdurbin** [comment]
@djbrooke good find. Interesting to see "This will eventually be used by harvest" at https://github.com/IQSS/dataverse/issues/1247#issuecomment-67544353

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
