### ISSUE TITLE
Version: Update build version from 4.4 to 4.5 as last step before release.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3301]
Convention has it that the last step before release is to update the version to be the release version. So, that would be changing 4.4 to 4.5.

**Comment by djbrooke** [comment]
We should update the version number in Sphinx as well.

**Comment by pdurbin** [comment]
To know which three files to change, please see http://guides.dataverse.org/en/4.4/developers/making-releases.html#bump-version-numbers

**Comment by kcondon** [comment]
Done, closing
