### ISSUE TITLE
Harvest: File type is not harvested, shows as unknown.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3305]
DDI harvest, JSON  harvest works.

**Comment by landreev** [comment]
Should be fixed, please re-test. 
But no, it was neither exported, nor imported, in DDIs. 
(Interestingly, it looks like we NEVER exported and/or harveset mime types, for non-tabular files, throughout the DVN3 life span).

**Comment by kcondon** [comment]
This is working. Closing.
