### ISSUE TITLE
Harvest: Investigate OAI-PMH protocol test for registration as a data provider.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3307]
The OAI-PMH website has information on registering as a data provider, including running a protocol test. We had done this for our first version of harvesting and would be good to do this for validation, improved interoperability, and increased data discovery (being on the list of data providers).

http://www.openarchives.org/pmh/register_data_provider
http://www.openarchives.org/pmh/register_data_provider#Protocol_Conformance_Testing

We currently pass the basic functionality test but have some issues on the in-depth test needed to register as a provider.

**Comment by rmo-cdsp** [comment]
Any informations/help needed about my pull request, or anything else about OAI-PMH (as much as I can help about it) ?

**Comment by landreev** [comment]
@rmo-cdsp 
I left a comment in #3368. 
Thank you for reporting this and submitting a fix. We will incorporate in the next release.

**Comment by djbrooke** [comment]
Outdated registration: http://www.openarchives.org/Register/BrowseSites?viewRecord=http://dvn.iq.harvard.edu/dvn/OAIHandler

**Comment by pdurbin** [comment]
This issue was just mentioned at https://groups.google.com/d/msg/dataverse-community/OlOsF5tJrrE/_FFRocaPAAAJ

**Comment by kcondon** [comment]
Passed on test env with small test data, failed on one test with full prod data:

Checking for correct use of resumptionToken (if used)

Request: GET http://dvn-vm5.hmdc.harvard.edu:8080/oai?verb=ListRecords&metadataPrefix=oai_dc

[FAIL] A cursor value was supplied with the resumptionToken but it did not have the correct value zero for the first response. The value was '1'.

**Comment by landreev** [comment]
Pushed a fix into the branch.

**Comment by kcondon** [comment]
OK, merged. Tests pass, submitted production url for registration though their process for https is currently manual on their end. Closing ticket!

**Comment by pdurbin** [comment]
This came up in https://groups.google.com/d/msg/dataverse-community/_gLUaA47aOY/RVGfwOhqAgAJ . I accidentally, reconfirmed that this issue is fixed in 4.6, perhaps. 😄
