### ISSUE TITLE
Separate Authors in Bibtex Citation with "and" instead of semi-colon

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#3311]
From https://github.com/IQSS/dataverse/issues/1013#issuecomment-242148386:

```
We at DataCite have finally fixed several long-standing bugs with the bibtex output of our metadata. Author names should be separated by and (datacite/content-resolver#10). See for example

curl http://doi.org/10.3886/ICPSR01218 -H "Accept: application/x-bibtex" -L
@misc{https://doi.org/10.3886/ICPSR01218,
doi = {10.3886/ICPSR01218},
url = {https://doi.org/10.3886/ICPSR01218},
author = {Beck, Nathaniel L. and King, Gary and Zeng, Langche},
publisher = {ICPSR - Interuniversity Consortium for Political and Social Research},
title = {Improving Quantitative Studies of International Conflict: A Conjecture},
year = {2000}"
```

**Comment by pameyer** [comment]
Author separator changed:
https://github.com/pameyer/dataverse/commit/22bdb66fcaded09b0e99beea159fb2aa7510cf6e

**Comment by scolapasta** [comment]
@pameyer Clearly a straightforward change - can you make a pull request and I'll send it on down the line?

**Comment by pameyer** [comment]
@scolapasta - I'll give it a shot (https://github.com/IQSS/dataverse/pull/3329)

**Comment by djbrooke** [comment]
@pameyer your code looks fantastic! I verified this on dvn-build with two and three author citations. I also checked it on one author citations as a regression.

Moving to Done.

**Comment by pameyer** [comment]
@djbrooke - I changed maybe four characters (aka - most of the credit for fantastic code goes to someone else).
