### ISSUE TITLE
Metrics: Allow downloading of undefined guestbook download stats at dataset and dv level

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3313]
Folks interested in download stats appear to want all downloads stats across all of their holdings (dv level) in a consolidated fashion, rather than or in addition to at a dataset level (this should be verified). Additionally, many or most do not define a guestbook (again verify) but they do want to know download activity.

So, this ticket is a feature request to enable downloading of non or undefined guestbook download stats in the same manner as guestbook stats (per dataset but definitely per dataverse).

A bonus would be to get all download stats for a hierarchy of dataverses since a few have dozens of sub dataverses and compiling individual files even at the dv level would be time consuming.

**Comment by pdurbin** [comment]
We already have download counts at the collection level.

For example: https://dataverse.harvard.edu/api/info/metrics/downloads?parentAlias=open-source-at-harvard

See https://guides.dataverse.org/en/5.11.1/api/metrics.html
