### ISSUE TITLE
Harvesting: Manage Sets, sets  defined with dataverse scope become less valid when subdv's are added.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3315]
The scope of parentId is the specified dataverse, no subdataverses included. So, in the case where a set was defined for a single dv which was later subdivided into sub dv's the set as defined shrinks to nothing since all datasets are moved to the sub dv's. This seems to invalidate the intent of creating the set initially: including all datasets underneath the hierarchy for which the parent is root. There is no way to detect this at the manage sets level.

So, it might be good to have a way to define all contents under a parent root such as the old ownerDvNetworkId term representing a subnetwork or root of a hierarchy of dataverses.

**Comment by pdurbin** [comment]
Related conversation with @rmo-cdsp - http://irclog.iq.harvard.edu/dataverse/2017-03-03#i_49631

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
