### ISSUE TITLE
Harvesting: Manage Sets page goes deaf after a while, making create set popup not save, does nothing until refresh page.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3316]
Not sure the exact sequence that causes this but when creating multiple sets where the manage page sits idle for a while in between, maybe 10 mins or so, page seems to go deaf so that the create set popup cannot save.

Refreshing the manage sets page makes it work again.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
