### ISSUE TITLE
Is that possible to add an another example for downloading file with curl?

### ISSUE THREAD

**Issue by wddabc** [IQSS/dataverse#3319]
http://guides.dataverse.org/en/latest/api/sword.html gives a fairly comprehensive usage of the curl command. I'm wondering if there could be another example for accessing a file given filename, doi using curl?

**Comment by pdurbin** [comment]
@wddabc well, you can't download files with Dataverse's implementation of SWORD and we don't plan to work on #183 any time soon. Instead, please use the Data Access API to download files: http://guides.dataverse.org/en/4.5/api/dataaccess.html

You're right that we should document somewhere how to download a file based on a DOI but it's a two step process. First you get a list of file IDs via the "Datasets" endpoint of the "native" API: http://guides.dataverse.org/en/4.5/api/native-api.html#datasets . Then you use the Data Access API to operate on the file IDs.

I've been thinking that maybe the API Guide should have a FAQ page or something!

**Comment by pdurbin** [comment]
@wddabc are you still interested in having us add an example?

**Comment by pdurbin** [comment]
> You're right that we should document somewhere how to download a file based on a DOI but it's a two step process. First you get a list of file IDs via the "Datasets" endpoint of the "native" API: http://guides.dataverse.org/en/4.5/api/native-api.html#datasets . Then you use the Data Access API to operate on the file IDs.

@wddabc I just made pull request #6107 and explained in a new "getting started" page the two step process above. Here's how it looks:

<img width="704" alt="Screen Shot 2019-08-21 at 6 51 28 AM" src="https://user-images.githubusercontent.com/21006/63426189-3d4c1e00-c3e0-11e9-94d8-6aba8f6cad68.png">

Does this help? Are you still interested in this issue?

**Comment by wddabc** [comment]
Hi Philip,
Thanks for working on this! Sorry that I didn't get an up-to-date response somehow! I found a way in 2016 which uses linux command line instead of API. But the new doc is indeed helpful!

**Comment by pdurbin** [comment]
@wddabc great! I'll go ahead close this issue, then. Thanks!
