### ISSUE TITLE
Remove the 'name' attribute from the DataFile table

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3320]
It's confusing and is currently NULL for the 440k+ files

This query returns 0 rows:
- `select name from datafile where name IS NOT NULL;`

**Comment by pdurbin** [comment]
This issue doesn't have a champion. Closing.

**Comment by oscardssmith** [comment]
why are we closing this? It seems both easy and useful

**Comment by pdurbin** [comment]
@oscardssmith please feel free to make a pull request if you'd like.
