### ISSUE TITLE
Harvest: Does not report all available formats in ListMetadataFormats

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3321]
Reported by a user on community group: ListMetadataFormats was only reporting dataverse_json in production though I was able to harvest oai_ddi using a dataverse 4 client.

On build, it only reports oai_ddi. Is this a list length issue? How is the client learning which formats work and so display in ui then?

**Comment by jggautier** [comment]
@kcondon. https://dataverse.harvard.edu/oai?verb=ListMetadataFormats now lists all five metadata formats available from Harvard Dataverse.

So is this issues resolved, at least for Dataverse version 4.20?

**Comment by kcondon** [comment]
@jggautier yes, it appears to be
