### ISSUE TITLE
Harvest: Do not list a set as available in ListSets until it has been successfully exported at least once.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3322]
The IQSS set in production is hung up on export but it appears in the list of available sets. When I harvest from it I get 0 datasets. It would be better not to list it until it has been successfully exported.

**Comment by mreekie** [comment]
Review with Leonid
- good candidate
- Get this estimated and prioritized

**Comment by cmbz** [comment]
2023/12/19: Prioritized during meeting on 2023/12/18. Added to Needs Sizing.

**Comment by landreev** [comment]
An ancient issue, but should still be relevant. 
Seems like a straightforward 10.
