### ISSUE TITLE
v3.6 Metadata field Funding Agency(fundAg) not migrating to v4

### ISSUE THREAD

**Issue by bikramj** [IQSS/dataverse#3323]
We are migrating data from v3.6 to 4.x and metadata field fundAg is not importing into v4. I see a [TODO:  here ](https://github.com/IQSS/dataverse/blob/develop/src/main/java/edu/harvard/iq/dataverse/api/imports/ImportDDIServiceBean.java#L1195)
Is there any plan to implement that?

**Comment by mheppler** [comment]
@scolapasta -- can you take a look at this TODO discovered in ImportDDIServiceBean.java.

**Comment by pdurbin** [comment]
I pointed out the TODO to @scolapasta during an SBGrid meeting last week since @bmckinney mentioned the need to store funding agency (as well as how there would ideally be a list of funding agencies to choose from in the GUI).

**Comment by pdurbin** [comment]
We might do well to take a look at https://github.com/ualbertalib/dataverse/commit/77a6767d756d78cfbe70447a8a46a3f1a73c302c by @pcharoen who was addressing a similar issue at https://github.com/ualbertalib/dataverse/issues/45 .

**Comment by pdurbin** [comment]
I just left this comment at https://groups.google.com/d/msg/dataverse-migration-wg/RLvINbxMfkQ/VIYveInRAQAJ but I'll repeat it here:

There are two ways to indicate funders in the Schema.org JSON-LD representation of datasets now that pull request #5169 has been merged (but not yet released): under "Contributor" ("Funder") and "Grant Information" ("Grant Agency").

**Comment by djbrooke** [comment]
@bikramj and all - I'm going to close this out as almost all installations have migrated from 3.x and we don't plan to address migration issues since the benefit would be small.

**Comment by pdurbin** [comment]
My guess is that from @bikramj 's perspective, he's trying to help @eugene-barsky get http://dvn.library.ubc.ca upgraded from DVN 3 and onto Scholars Portal. He opened #4996 about this. This is the last DVN 3 installation on the map.

**Comment by eugene-barsky** [comment]
Yes, Abacus Dataverse (3.6) is in plans to upgrade to 4.18 as we manage our
40,000 licensed data files on that platform. To be done by the end of the
year. It will not go to Scholars Portal. We have our research data there,
while licensed data on Abacus Dataverse based in UBC.

Does it help?

Eugene

**Comment by djbrooke** [comment]
@eugene-barsky, is this issue blocking the migration? If not, what else can we do to help with the migration?

**Comment by bikramj** [comment]
Hi @pdurbin @djbrooke from our side we don't need this anymore since we have completed all the migrations we were supposed to do. Thank you for confirming.

**Comment by djbrooke** [comment]
Thanks @bikramj. I'll wait to hear from @eugene-barsky before closing it out.

**Comment by eugene-barsky** [comment]
Thank you, Danny, no, not this issue blocking the migration. Feel free to
close this ticket.

I am reaching out to my team here - Paul Lesack and Jeremy Buhler to be in
touch with you to see whether we need any special help with our Dataverse
3.6 migration.

Eugene

**Comment by djbrooke** [comment]
Got it, thanks @eugene-barsky. support@dataverse.org or opening specific issues here is fine!
