### ISSUE TITLE
"/api/access/datafile" hardcoded 16 times in 7  files java/xhtml files

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3325]
related: #3324 

---

Makes it hard to version the API, etc.  Note: 16x is only counting .java and .xhtml files.    
- Screenshot shows 33 instances across all files--many of the full 33 not relevant

![netbeans_ide_8_0_2](https://cloud.githubusercontent.com/assets/1036060/18131133/b6d42246-6f5f-11e6-875a-41c7d2d823ff.png)

**Comment by pdurbin** [comment]
This is a blocker for this issue:  Support newer versions of API #1885

**Comment by pdurbin** [comment]
@raprasad I just pushed eb40c73 after discussion with @scolapasta. At some point let's get on the same page with regard to what a pull request would look like to resolve this issue. We could also consider consolidating this into #1885. Also, #3324 is mentioned in the description as related but I'm not sure how.

**Comment by pdurbin** [comment]
There is no will to address this anytime soon. Closing.
