### ISSUE TITLE
Guestbook: Restrict file download counts to current session

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3332]
-  **Action**:
  - Users can keep clicking `Download` on the same file.  
  -  Each click gets recorded as a separate download.  
  -  **Problem**: 
    - Inaccurate/skewed file download counts
  - **Fix**: 
    - Restrict file download _counts_ by session.

---

Related bugs: #3324, #3331

**Comment by pdurbin** [comment]
Closing in favor of #3331
