### ISSUE TITLE
UI Cleanup - Action Button + Metrics Block Layout

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#3341]
The layout of the top section of the dataverse, dataset and soon to be file pgs (e.g. Metrics block, Edit button, Publish/Submit for Review button, Email/Link/Share button group, mysterious disappearing View Dataset Versions button) could be improved.

This issue was raised upon further review of the mockups for the file pg (#2465) which require the additions of Explore, and Request Access/Download buttons to the action buttons section, resulting in a crowded string of elements across the top of the page.

![screen shot 2016-09-09 at 4 06 08 pm](https://cloud.githubusercontent.com/assets/687227/18401371/378e2572-76a8-11e6-8ae6-e2e59ce88b49.png)

Related issues:
- Dataset Publish/Submit for Review - Optimize Button/Popup Code #1664 
- View Dataset Versions Button does not appear on Page Load #2782
- Dataset - File UI Improvements #3404 
- Improve visibility of buttons for data owners #3815

**Comment by djbrooke** [comment]
Before moving to ready, we should get an estimate on this and do some user testing.

**Comment by mheppler** [comment]
Brief discussion today in the status meeting about the potential need for cleaning up and optimizing the permission render logic of all the buttons on the dataset and file pgs. The potential for adding new Explore/Visualization features for datasets and files (DDI Explorer, #2216) will also add to the new for improving this area of these pgs.

**Comment by mheppler** [comment]
- The placement and visual design of the metrics button is confusing. What does it refer to – file or dataset? It looks clickable but is not.

[Recommended by the UX Team](https://docs.google.com/document/d/1mNNRqRqIW92LXock332sIA-uXh-2agOpoyLLLKwXUA0/edit) based upon user feedback in usability testing of 4.6.

**Comment by mheppler** [comment]
Adding these recommendations on the share/email buttons to this issue.

- “Share dataset” button - supposed to say “share file”?
- “Share dataset” button doesn’t include sharing via email, and participants stated that they would share via email.
- Email button - emails the dataset owner, however, participants thought it was an email sharing button. Feature to email the dataset owner should be changed from a button to a link elsewhere on the page.

[Recommended by the UX Team](https://docs.google.com/document/d/1mNNRqRqIW92LXock332sIA-uXh-2agOpoyLLLKwXUA0/edit) based upon user feedback in usability testing of 4.6.

**Comment by mheppler** [comment]
New styles applied to the Metrics block in #3538, to lessen it's visual impact.

<img width="990" alt="screen shot 2017-01-06 at 12 42 55 pm" src="https://cloud.githubusercontent.com/assets/687227/21825671/a7dd09fa-d752-11e6-8084-76809633a4fd.png">

**Comment by mheppler** [comment]
Related issue: View Dataset Versions button #2782

**Comment by TaniaSchlatter** [comment]
![compute_dataset_round3](https://cloud.githubusercontent.com/assets/15386424/24929552/5beafe48-1ed4-11e7-9d86-cd7738022311.jpg)

Email/contact and Share buttons design proposed to be changed as part of adding Compute features – https://github.com/IQSS/dataverse/issues/3747

**Comment by pameyer** [comment]
For what it's worth, when I first saw the "Share" button I assumed it was to invite other users to become co-authors on a dataset (instead of its apparent function of interacting with social media).

**Comment by mheppler** [comment]
When reviewing links that use icons, and no text, make sure to consider accessibility improvements, as suggested in _homepage: 508 / accessiblity follow-up #3748_.

>Links without text can't be used by screen readers

```
<a href="/dataset.xhtml?persistentId=doi:10.7910/DVN/RO8ITP"><span class="icon-dataset text-info"></span></a>
```

**Comment by mheppler** [comment]
Closing. This issue is being resolved by **Layout and styling of action buttons on the dataset and file page #6684**.
