### ISSUE TITLE
Update forked SWORD library to prevent Maven from reaching out to dataone.org

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#3342]
As of this morning Travis is having trouble building the Dataverse war file and it has something to do with how the forked SWORD library at https://github.com/IQSS/swordv2-java-server-library we reference in pom.xml is incorrectly reaching out to dataone.org rather than the finding the jar on the filesystem at `local_lib/org/swordapp/sword2-server/1.1-SNAPSHOT`.

This issue is affecting developers as well. Unlike Travis, which times out, Netbeans eventually uses a cached file (or something?) but @sekmiller reports a build time of 9 minutes 22 seconds this morning. 

https://travis-ci.org/IQSS/dataverse/builds/159308260 shows `[WARNING] Could not transfer metadata org.swordapp:sword2-server:1.1-SNAPSHOT/maven-metadata.xml from/to dataone.org (http://dev-testing.dataone.org/maven): Connect to dev-testing.dataone.org:80 [dev-testing.dataone.org/129.24.0.17] failed: Connection timed out`

https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-build-develop/43/console shows `[WARNING] Failure to transfer org.swordapp:sword2-server:1.1-SNAPSHOT/maven-metadata.xml from http://dev-testing.dataone.org/maven was cached in the local repository, resolution will not be reattempted until the update interval of dataone.org has elapsed or updates are forced. Original error: Could not transfer metadata org.swordapp:sword2-server:1.1-SNAPSHOT/maven-metadata.xml from/to dataone.org (http://dev-testing.dataone.org/maven): Connection to http://dev-testing.dataone.org refused`

I think the solution will be to hack on https://github.com/IQSS/swordv2-java-server-library to give it a unique version number and then update the war file in the `local_lib/org/swordapp/sword2-server/1.1-SNAPSHOT` and the pom.xml in this repo to avoid reaching out to dataone.org. That is to say, that I think we need to re-do the commit at 2c1cfd5 where I originally added our fork of the SWORD library.

**Comment by pdurbin** [comment]
I'm starting to wonder if I'm mischaracterizing the issue, which may be simply that http://dev-testing.dataone.org/maven is down. Locally, for now I'm commenting out this section of the Dataverse pom.xml and I'm able to build quickly again:

```
    <repository>
        <id>dataone.org</id>
        <url>http://dev-testing.dataone.org/maven</url>
        <releases>
            <enabled>true</enabled>
        </releases>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </repository>
```

I mean, I think our forked SWORD library might still benefit from having "IQSS" or something in the version but maybe this whole issue goes away if http://dev-testing.dataone.org/maven comes back up?

**Comment by mbjones** [comment]
@pdurbin That is an older URL -- our maven repository has moved to http://maven.dataone.org.  We will put in a redirect from the old hostname so that it will resolve, but please update your build to use the stable maven repository.  Thanks.

**Comment by pdurbin** [comment]
@mbjones thanks! The actual fix is a one line change so I created a new issue (#3343) and pull request (#3344) to update our pom.xml file to use the correct dataone maven repo.

Maybe I was wrong about our SWORD library fork. Maybe we're not doing it wrong. I'm going to close this issue for now but anyone is welcome to comment or re-open it if we should update it.
