### ISSUE TITLE
API default license should be CCO (and corresponding logic)

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#3357]
In 4.5, we set the default license via API as "None". We want it to be CC0 (consistent with Sword API and UI). 

However, we also need to add logic / validation, so that:
- if they enter any terms, the default, in fact, would be none
- if they enter terms and actively set CC0 then it fails with a validation error

**Comment by pameyer** [comment]
Why should actively setting CC0 fail with a validation error?

**Comment by mheppler** [comment]
You can not apply a CC0 waiver to a dataset if you are applying Terms of Use. In the UI, the textarea input is not displayed until you deselect the CC0 waiver. The validation for the API should follow suit.

http://guides.dataverse.org/en/4.8.5/user/dataset-management.html?highlight=cc0#custom-terms-of-use-for-datasets

>Custom Terms of Use for Datasets
>
>If you are unable to use a CC0 waiver for your datasets you are able to set your own custom terms of use. To do so, select “No, do not apply CC0 - “Public Domain Dedication” and a Terms of Use textbox will show up allowing you to enter your own custom terms of use for your dataset. To add more information about the Terms of Use, we have provided fields like Special Permissions, Restrictions, Citation Requirements, etc.

**Comment by pdurbin** [comment]
This issue was created in a different age, when licenses were fixed. @shlake just created the modern equivalent of this issue where we should consider the flexibility we now have around licenses:

- #9364

Closing.
