### ISSUE TITLE
Map - Format logos for 4 new installations

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3359]
- fyi: Once this is done and installations linked, new map can be added to dataverse.org

---

For the new map of DV installations, logos are needed for these places:

- [x] Maine dataverse
- [x] Scholar's portal
- [x] 	ICRISAT - http://dataverse.icrisat.org/	 
- [x] DV in france

- @raprasad to coordinate with @mheppler

**Comment by mheppler** [comment]
Name | Project Site | Installation
--- | --- | ---
Scholar's Portal | scholarsportal.info | dataverse.scholarsportal.info/dvn/
ICRISAT | icrisat.org | ?
Maine? | ? | ?
France? | ? | ?

**Comment by mheppler** [comment]
Installations have been added with the above information, and logos were uploaded.
