### ISSUE TITLE
Fix import issue introduced in 4.5 - only one version per dataset is imported!

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#3362]
This was reported by Odum - the migration process was working for them in 4.4; when upgraded to 4.5 however, they noticed that only 1 version per dataset was migrated; even if there were multiple versions. 

Note that this is important to fix as soon as we can (maybe even in 4.5.1!); as this bug makes it impossible to migrate datasets with multiple versions in 4.5!

Things tested and ruled out: 

Some changes to the parsers were made to accommodate harvesting in 4.5; so I was afraid some of those changes were responsible for some of the Odum versions failures to import... But no, all of the DDIs still successfully parse. It just appears that every time you run /migrate on a DDI representing a version, if the dataset with this global id already exists, *all the existing versions get wiped* before this new version is added... thus only the last imported version is present. (So if you migrate the DDIs in different order, you'll end up with different versions migrated...)

Further, the code for the import of harvested datasets is well separated from the migration import... and the latter hasn't really been changed much in 4.5. 

Akio found something in the 4.5 code diffs that looked suspicious... but it appears to have been a false alarm. (will add more info for posterity...)

To make matters more confusing still, I am now seeing some lines in the version code that are looking totally wrong... wrong as in, they really look like they should result in just that - making it impossible to import a version without overwriting any existing versions... HOWEVER, the lines in question are NOT at all new! They haven't been added in 4.5, but rather have been around since very early 4*... So the question appears to be not why it's not working now - but why it has ever worked before?? 

So, I'm still looking into it, will report more soon. 
I keep thinking it must be something very simple, and thus a very simple fix... But I haven't found it yet.

**Comment by landreev** [comment]
OK, I'm 99% positive I know what it is - it's a change made by Michael to the CreateDatasetVersionCommand... It's just that he committed that change back in December '15, and 4.4 was released in May '16 - so I assumed it was in 4.4 as well. But it wasn't... meaning, it must have been committed into some side branch that didn't get merged into the main develop until 4.5... Hence that's when it broke. 

I still need to verify/confirm this... so, there's still a chance this is just another false alarm.

**Comment by pdurbin** [comment]
@landreev if you're talking about 35f1f8c this was part of the "2746-testable-commands" branch that was merged into develop as part of pull request #3002 which was merged after 4.4 was released. So you're right. I didn't make it into a release until 4.5.

**Comment by landreev** [comment]
I have checked in a fix, in the branch 3362-migration-issue-dropped-versions.

**Comment by pdurbin** [comment]
I just reviewed the code per https://github.com/IQSS/dataverse/pull/3366#issuecomment-248358732 and it looks good so I moved this issue to QA in https://waffle.io/IQSS/dataverse

**Comment by pdurbin** [comment]
@donsizemore mentioned he's doing some testing of the fix in pull request #3366: http://irclog.iq.harvard.edu/dataverse/2016-09-23#i_41952

**Comment by kcondon** [comment]
Don confirmed it's working, closing.
