### ISSUE TITLE
Mimetypes - Keep DRY*

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3363]
(\* Don't Repeat Yourself.)

---

Centralize mimetypes strings, including mimetype "groups" used for faceting.  Ideally have this in a database or database+JSON file.

### Mimetype strings are repeated all over the place.  
- Single source them in the code or db.
- Use the official IANA list when possible: http://www.iana.org/assignments/media-types/media-types.xhtml
  - Auto-ingest this list or find library that does

Examples:
- The mimetype for Excel (.xlsx) is repeated 8 times in the codebase
  - The Excel (.xlsx) mimetype: `"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"`
  - Repeated 8 times:
    ![dataverse_-_netbeans_ide_8_0_2](https://cloud.githubusercontent.com/assets/1036060/18635168/128146e0-7e52-11e6-9bd8-8ba88a4a944f.png)
  -  The mimetype for tab-delimited files is repeated many times in the codebase
- The tab-delimited files mimetype: `text/tab-separated-values`
- Repeated 10 times:
  ![netbeans_ide_8_0_2](https://cloud.githubusercontent.com/assets/1036060/18635344/aea355fe-7e52-11e6-8c48-92d3429f2d6f.png)

etc, etc...

**Comment by raprasad** [comment]
@pdurbin made a not of this in the latest guide: http://guides.dataverse.org/en/4.7/developers/coding-style.html#avoid-hard-coding-strings

**Comment by pdurbin** [comment]
Yep, I think the note is enough. Someone can open a fresh issue if they want to work on MIME type specifically and champion that cause.
