### ISSUE TITLE
DataCite DOI update on Dataset Deaccession

### ISSUE THREAD

**Issue by sekmiller** [IQSS/dataverse#3364]
Review process of identifier updates when a Dataset is completely deaccessioned with DataCite as the DOI provider.

**Comment by pdurbin** [comment]
For some more context on this issue: https://groups.google.com/d/msg/dataverse-community/GodzLLfeowc/PCpWRYOoBQAJ

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
