### ISSUE TITLE
Dataset Metadata - display productionDate, not publicationDate

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#3369]
Phil suggested Akio add a global setting to the DatasetVersion getCitationDate method to allow this. 

Odum can use the native API to fix existing datasets, but newly-created datasets will revert to publicationDate. We'd much prefer productionDate, particularly for older data.

**Comment by pdurbin** [comment]
Here's an approach I suggested to @akio-sone via email:

Maybe you could add a setting for which field to use, globally (per installation of Dataverse):

https://github.com/IQSS/dataverse/blob/v4.5/src/main/java/edu/harvard/iq/dataverse/DatasetVersion.java#L750

Settings go in the "Key" enum in SettingsServiceBean:

https://github.com/IQSS/dataverse/blob/v4.5/src/main/java/edu/harvard/iq/dataverse/settings/SettingsServiceBean.java#L35

The Key enum is referenced from SystemConfig:

https://github.com/IQSS/dataverse/blob/v4.5/src/main/java/edu/harvard/iq/dataverse/util/SystemConfig.java

**Comment by pdurbin** [comment]
This issue related to Add Backend Support for Changing Citation Date #2606 and pull request #3000.

**Comment by jggautier** [comment]
Hi @donsizemore, you wrote that for the date displayed in the dataset citation, "[w]e'd much prefer productionDate, particularly for older data". Could you share how that date is used on UNC Dataverse?

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
