### ISSUE TITLE
IP Groups: List roles assigned to group endpoint stopped working.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3370]
The list roles endpoint is relatively new but had been working.
Now, when run it, get a 404:
curl "http://localhost:8080/api/admin/assignments/assignee/\&ip/ipGroup3"
which throws a uri encoding error, so tried
curl "http://localhost:8080/api/admin/assignments/assignee/%26ip/ipGroup3" 
which throws a 404

Michael said he'd take a look.

**Comment by djbrooke** [comment]
@kcondon can you please retest this one in case anything has changed?

@michbarsinai also interested to hear your thoughts!

Thanks!

**Comment by kcondon** [comment]
@djbrooke  I'm waiting for Michael to tell me he fixed it.

**Comment by kcondon** [comment]
curl -X GET http://localhost:8080/api/admin/assignments/assignees/\&ip/ipGroup3
don't forget the s in assignees!
