### ISSUE TITLE
category of a dataverse cannot be set via API

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#3371]
In #3046 we introduced "Laboratory" as a dataverse category but it's impossible to set categories via API. This is an important feature for anyone migrating to Dataverse from another system, such as https://data.sbgrid.org which wants to set all dataverse categories to "Laboratory" during their migration.

**Comment by pdurbin** [comment]
I just created pull request #3373, tweaking the work by @bmckinney with a couple commits of my own. I moved this straight into QA at https://waffle.io/IQSS/dataverse because I don't feel like code review is necessary (Bill and I are happy with the code) and the change is small. The code is in the "sbgrid-json-migration" branch and here's how to test it:

- If you put `"dataverseType": "LABORATORY"` into the JSON you use to create a Dataverse via API, it should set the category to "Laboratory". Here's an example JSON file https://github.com/IQSS/dataverse/blob/2af246fcb87ffd62ad3e2c637abf873a2027bf49/src/test/resources/json/complete-dataverse.json
- If you leave the "dataverseType" field out of the JSON, the old behavior is preserved and the Dataverse gets "Uncategorized" at a category.

I didn't document the possible values (maybe I should) but here they are (from the DataverseType enum in Dataverse.java):

`RESEARCHERS, RESEARCH_PROJECTS, JOURNALS, ORGANIZATIONS_INSTITUTIONS, TEACHING_COURSES, UNCATEGORIZED, LABORATORY, RESEARCH_GROUP`

**Comment by pdurbin** [comment]
> I moved this straight into QA at https://waffle.io/IQSS/dataverse

I moved this issue straight to QA but the pull request itself I put in Code Review: #3373

**Comment by pdurbin** [comment]
@bmckinney can you please code review 203966f? For now I want the API to be more strict so I changed `equalsIgnoreCase` to `equals`. If you're fine with this and you feel like this branch is ready for QA, please comment below. Thanks!

**Comment by bmckinney** [comment]
Thumbs, up. Thanks!

**Comment by pdurbin** [comment]
@bmckinney great! I moved it to QA in https://waffle.io/IQSS/dataverse

@kcondon instructions on how to test are at https://github.com/IQSS/dataverse/issues/3371#issuecomment-248734852

**Comment by kcondon** [comment]
Please add json example to docs, thanks.

**Comment by pdurbin** [comment]
@kcondon as we discussed I added a JSON example in 510b907 and while I was in there I improved the error reporting for when you don't send the right JSON to create a dataverse. I'm aware that a 500 error is still being thrown but at least you get a sense of which bean validation rules are not being obeyed. Passing back to you.

**Comment by kcondon** [comment]
Looks good, closing.
