### ISSUE TITLE
file replace error bundle + future test list

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3387]
part of #2290  (test list in process)

- [x] add to error bundles for #2290
- [ ] add tests, not necessarily for #2290

---

- [ ] 1) Load null dataset
- [ ] 2) Load dataset by null id
- [ ] 3) Load dataset by non-existent id
- [ ] 4) Load good dataset
- [ ] 5) Load good dataset by id
- [ ] 6) User w/o Edit Dataset Perms
- [ ] 7) User w/ Edit Dataset Perms
- [ ] 8) Load new good file, name, content type
- [ ] 9) Load null file input stream
- [ ] 10) Load null file name
- [ ] 11) Load null content type
- [ ] 12) Load good file to replace by id
- [ ] 13) Load file to replace by null id
- [ ] 14) Load file to replace by non-existent id
- [ ] 15) Load file to replace by id from other dataset
- [ ] 16) Load unpublished file to replace by id
- [ ] 17) Load deleted file to replace by id (file from previous version)

---

|#|Test                                    |Success|Fail   |Replace Only Test|Expected Message|
---|---|:---:|:---:|:---:|:---:|:---:
|1|Load null dataset                       |--     |Y      |--             |Dataset cannot be null|
|2|Load dataset by null id                 |--     |Y      |--             |Dataset id cannot be null|
|3|Load dataset by non-existent id         |--     |Y      |--             |No dataset found|
|4|Load good dataset                       |Y      |--     |--             |--|
|5|Load good dataset by id                 |Y      |--     |--             |--|
|6|User w/o Edit Dataset Perms             |--     |Y      |--             |No dataset found|
|7|User w/ Edit Dataset Perms              |Y      |--     |--             |--|
|8|Load new good file, name, content type  |Y      |--     |--             |--|
|9|Load null file input stream             |--     |Y      |--             |File input stream cannot be null|
|10|Load null file name                     |--     |Y      |--             |File name cannot be null|
|11|Load null content type                  |--     |Y      |--             |File content type cannot be null|
|12|Load good file to replace by id         |Y      |--     |Y              |--|
|13|Load file to replace by null id         |--     |Y      |Y              |File id cannot be null|
|14|Load file to replace by non-existent id |--     |Y      |Y              |File id cannot be null|
|15|Load file to replace by id from other dataset |--     |Y      |Y        |File does not belong to this dataset|
|16|Load unpublished file to replace by id  |--     |Y      |Y              |File must be published before can be replaced|
|17|Load deleted file to replace by id (file from previous version)|--     |Y      |Y        |File must be in most recently published Dataset|

**Comment by pdurbin** [comment]
I added the "4.6 - File Replace" milestone. It seems to be under active development to I dragged it to that column at https://waffle.io/IQSS/dataverse

**Comment by djbrooke** [comment]
Let's track the creation of these tests as part of the larger issue (#2290) instead of creating additional sub issues that need to be tracked and completed before the larger issue can be moved to done.  Closing this.
