### ISSUE TITLE
Guides - Building epub version results in warnings

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#3391]
As noted by @kcondon in #3181 there are warnings when building the docs, which are a results of the epub version being created. This also relates to the warnings when building the pdf version, which are outline in #3134.

```
writing content.opf file...
WARNING: unknown mimetype for _static/jquery.js, ignoring
WARNING: unknown mimetype for _static/underscore.js, ignoring
WARNING: unknown mimetype for _static/doctools.js, ignoring
WARNING: unknown mimetype for _static/websupport.js, ignoring
WARNING: unknown mimetype for _static/navbar_from_dataverse_org.js, ignoring
WARNING: unknown mimetype for _static/navbarscroll.js, ignoring
WARNING: unknown mimetype for _static/searchtools.js, ignoring
WARNING: unknown mimetype for _static/installation/files/issues/2180/grizzly-patch/glassfish-grizzly-extra-all.jar, ignoring
WARNING: unknown mimetype for _static/installation/files/issues/2180/grizzly-patch/readme.md, ignoring
WARNING: unknown mimetype for _static/installation/files/etc/init.d/solr, ignoring
WARNING: unknown mimetype for _static/installation/files/etc/init.d/glassfish, ignoring
WARNING: unknown mimetype for _static/installation/files/etc/httpd/conf.d/dataverse.example.edu.conf, ignoring
WARNING: unknown mimetype for _static/installation/files/etc/httpd/conf.d/ssl.conf, ignoring
WARNING: unknown mimetype for _static/installation/files/etc/shibboleth/shibboleth2.xml, ignoring
WARNING: unknown mimetype for _static/installation/files/etc/shibboleth/attribute-map.xml, ignoring
WARNING: unknown mimetype for _static/installation/files/etc/shibboleth/dataverse-idp-metadata.xml, ignoring
WARNING: unknown mimetype for _static/installation/files/etc/shibboleth/shibGroupTestShib.json, ignoring
WARNING: unknown mimetype for _static/installation/files/home/rpmbuild/rpmbuild/RPMS/x86_64/rapache-1.2.7-rpm0.x86_64.rpm, ignoring
writing toc.ncx file...
writing Dataverse.epub file...
build succeeded, 18 warnings.
```

**Comment by mheppler** [comment]
Found this [old report of these same warnings](https://code.djangoproject.com/ticket/16422), which makes it seems there is no solution to be expected.

**Comment by pdurbin** [comment]
For what it's worth, I found the line where this warning comes from in Sphinx: https://github.com/sphinx-doc/sphinx/blob/1.5/sphinx/builders/epub.py#L587

I'm not sure what the fix would be though. https://github.com/sphinx-doc/sphinx#contributing says, "1. Check for open issues or open a fresh issue to start a discussion around a feature idea or a bug." and I couldn't find an open issue so I guess we could open one at https://github.com/sphinx-doc/sphinx/issues

**Comment by pdurbin** [comment]
I went ahead and created https://github.com/sphinx-doc/sphinx/issues/3214

**Comment by pdurbin** [comment]
@mheppler good news! The Sphinx project implemented a fix for the issue I opened at https://github.com/sphinx-doc/sphinx/issues/3214 and it looks like it has been given a milestone of Sphinx 1.5.1. Once they've released it, you or I should test it to make sure the bug is fixed and that out docs still look good (we're still using quite an old version, Sphinx 1.1.3, at http://guides.dataverse.org ). If we're happy with our local builds, we can recommend that an upgrade be made on the Jenkins server that builds the docs. I'm going to give this issue to you so you see it. I'm not sure which column it should go in at https://waffle.io/IQSS/dataverse so I'll assign this to @djbrooke as well.

**Comment by djbrooke** [comment]
Hi - who can I work with to move this to Done? It looks like Sphinx 1.5.1 has been released, so now I want to upgrade Jenkins to use this new version.

**Comment by pdurbin** [comment]
@djbrooke the Jenkins server is maintained by @hmdc and we don't have "root" on that box. We've been provided this job to execute jobs as the "jenkins" user, which may or may not help: https://build.hmdc.harvard.edu:8443/job/Command_Line/ . There's also a very low traffic list at https://lists.iq.harvard.edu/mailman/listinfo/builders

https://build.hmdc.harvard.edu:8443/job/guides.dataverse.org-3338-oauth-login/ is the job I'm using to build docs for the 3338-oauth-login branch. Here's what it does:

`VERSION=3338-oauth-login`
`TARBALL=guides$VERSION.tar.gz`
`(cd $WORKSPACE/doc/sphinx-guides; make clean; scl enable python27 "make html";  scl enable python27 "make latexpdf"; cp build/latex/Dataverse.pdf build/html; scl enable python27 "make epub"; cp build/epub/Dataverse.epub build/html; cd build/html; tar cvzf /tmp/$TARBALL .; scp /tmp/$TARBALL plaid@docs.dataverse.org:/tmp)`
`ssh -l plaid docs.dataverse.org "(mkdir -p /var/www/docs.dataverse.org/en/$VERSION && cd /var/www/docs.dataverse.org/en/$VERSION && tar xvzf /tmp/$TARBALL)"`

Commands like `make html` and `make latexpdf` and `make epub` are what call Sphinx. They call `sphinx-build` (currently version 1.1.3) as defined at https://github.com/IQSS/dataverse/blob/develop/doc/sphinx-guides/Makefile


```

**Comment by djbrooke** [comment]
Thanks for the background @pdurbin! I'll get in touch with the right folks and get this moved to done.

**Comment by djbrooke** [comment]
I contacted @hmdc about this. I will let you know when I have more info.

**Comment by djbrooke** [comment]
@hmdc is available to help with this after the break. Moving this back to ready for now, will be moved back to "development" when it's being worked on again.

**Comment by pdurbin** [comment]
Fixing this requires a code change so I just made pull request #3542. The change itself is quite small: 56db0a8

I upgraded my laptop from Sphinx v1.4.5 to  to v1.5.1 using `pip install sphinx==1.5.1`. No more warnings:

```
(dataverse) murphy:sphinx-guides pdurbin$ tail -2 source/conf.py 
# Suppress "WARNING: unknown mimetype for ..." https://github.com/IQSS/dataverse/issues/3391
suppress_warnings = ['epub.unknown_project_files']
(dataverse) murphy:sphinx-guides pdurbin$ 
(dataverse) murphy:sphinx-guides pdurbin$ 
(dataverse) murphy:sphinx-guides pdurbin$ make clean && make epub
rm -rf build/*
sphinx-build -b epub -d build/doctrees   source build/epub
Running Sphinx v1.5.1
making output directory...
loading pickled environment... not yet created
loading intersphinx inventory from http://docs.python.org/objects.inv...
intersphinx inventory has moved: http://docs.python.org/objects.inv -> https://docs.python.org/2/objects.inv
building [mo]: targets for 0 po files that are out of date
building [epub]: targets for 55 source files that are out of date
updating environment: 55 added, 0 changed, 0 removed
reading sources... [100%] user/tabulardataingest/supportedformats                                                                      
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] user/tabulardataingest/supportedformats                                                                       
generating indices... genindex
writing additional pages...
copying images... [100%] user/./img/Dataverse-Diagram.png                                                                              
copying static files... done
copying extra files... done
writing mimetype file...
writing META-INF/container.xml file...
writing content.opf file...
writing nav.xhtml file...
writing toc.ncx file...
writing Dataverse.epub file...
build succeeded.

Build finished. The epub file is in build/epub.
(dataverse) murphy:sphinx-guides pdurbin$ 
```

I'll put this in Code Review at https://waffle.io/IQSS/dataverse

**Comment by scolapasta** [comment]
Reviewed - code was trivial change, but needs the Sphinx to be updated before it can be tested.

**Comment by kcondon** [comment]
epub warnings are gone. closing.

**Comment by pdurbin** [comment]
I'm working on getting Sphinx upgraded in https://help.hmdc.harvard.edu/Ticket/Display.html?id=244853 . Currently http://guides.dataverse.org says "Created using Sphinx 1.1.3" and we need to use 1.5.1

**Comment by pdurbin** [comment]
Our exisiting Jenkins job looks something like this:

`(cd $WORKSPACE/doc/sphinx-guides; make clean; scl enable python27 "make html";  scl enable python27 "make latexpdf"; cp build/latex/Dataverse.pdf build/html; scl enable python27 "make epub"; cp build/epub/Dataverse.epub build/html; cd build/html; tar cvzf /tmp/$TARBALL .; scp /tmp/$TARBALL plaid@docs.dataverse.org:/tmp)`

I've tried setting the `SPHINXBUILD` environment variable like this but it doesn't seem to work:

`(cd $WORKSPACE/doc/sphinx-guides; make clean; scl enable python27 "SPHINXBUILD=/nfs/tools/lib/python/2.7/current/bin/sphinx-build make html"; ...`

**Comment by pdurbin** [comment]
Per https://help.hmdc.harvard.edu/Ticket/Display.html?id=244853#txn-4941004 I'm going to meet with the folks who run the Jenkins server tomorrow afternoon.

**Comment by pdurbin** [comment]
I just found an answer at http://stackoverflow.com/questions/4122040/how-to-make-sphinx-look-for-modules-in-virtualenv-while-building-html/4249730#4249730 that did the trick for me. Here's what allowed me to build the guides with Sphinx 1.5.1 or higher (actually 1.5.2):

`VERSION=3338-oauth-login`

`TARBALL=guides$VERSION.tar.gz`

`(cd $WORKSPACE/doc/sphinx-guides; make clean; scl enable python27 "make html SPHINXBUILD=/nfs/tools/lib/python/2.7/current/bin/sphinx-build";  scl enable python27 "make latexpdf SPHINXBUILD=/nfs/tools/lib/python/2.7/current/bin/sphinx-build"; cp build/latex/Dataverse.pdf build/html; scl enable python27 "make epub SPHINXBUILD=/nfs/tools/lib/python/2.7/current/bin/sphinx-build"; cp build/epub/Dataverse.epub build/html; cd build/html; tar cvzf /tmp/$TARBALL .; scp /tmp/$TARBALL plaid@docs.dataverse.org:/tmp)`

`ssh -l plaid docs.dataverse.org "(mkdir -p /var/www/docs.dataverse.org/en/$VERSION && cd /var/www/docs.dataverse.org/en/$VERSION && tar xvzf /tmp/$TARBALL)"`

For the command above in action, see https://build.hmdc.harvard.edu:8443/job/guides.dataverse.org-3338-oauth-login/

Output at http://guides.dataverse.org/en/3338-oauth-login/user/index.html (note "Sphinx 1.5.2" in the screenshot below:

![screen shot 2017-01-25 at 1 55 42 pm](https://cloud.githubusercontent.com/assets/21006/22304588/0bad638a-e306-11e6-97d7-99033706a923.png)

Moving to QA to apply to a branch that hasn't already been merged.

**Comment by pdurbin** [comment]
Oh, and here's how you can tell that upgrading Sphinx fixed the issue that this is all about.

Before we upgraded Sphinx you'd see lots of "WARNING: unknown mimetype for" such as here: https://build.hmdc.harvard.edu:8443/job/guides.dataverse.org-3338-oauth-login/27/consoleFull

After the upgrade, they're gone, such as here: https://build.hmdc.harvard.edu:8443/job/guides.dataverse.org-3338-oauth-login/32/consoleFull

**Comment by kcondon** [comment]
Added/replaced this command line in the guides-dataverse.org-rfi project and epub warnings disappeared:

(cd $WORKSPACE/doc/sphinx-guides; make clean; scl enable python27 "make html SPHINXBUILD=/nfs/tools/lib/python/2.7/current/bin/sphinx-build"; scl enable python27 "make latexpdf SPHINXBUILD=/nfs/tools/lib/python/2.7/current/bin/sphinx-build"; cp build/latex/Dataverse.pdf build/html; scl enable python27 "make epub SPHINXBUILD=/nfs/tools/lib/python/2.7/current/bin/sphinx-build"; cp build/epub/Dataverse.epub build/html; cd build/html; tar cvzf /tmp/$TARBALL .; scp /tmp/$TARBALL plaid@docs.dataverse.org:/tmp)

Closing
