### ISSUE TITLE
API Key:  If expired, add message to "API token" tab

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3398]
I logged in using an older Dataverse account in order to grab the API key.

When tried to use API key, it was expired--but the UI never mentioned it.

**Comment by pdurbin** [comment]
@raprasad does the API say that the token is expired?

**Comment by raprasad** [comment]
When I used it: yes

**Comment by pdurbin** [comment]
In a year and a half no one else has reported this. It'll come up again naturally if someone reports it. The workaround is simply to regenerate a new API token for yourself with the click of a button. Closing.
