### ISSUE TITLE
allow customizable "sticky header" logo

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#3401]
Thu-Mai would like to be able to set UNC's logo à la #2003 (specifically, Scholars' Portal) - would it take much effort to make her happy? It would be so wonderful not to have to shoe-horn in minor tweaks like this. Sorry if this issue is a dupe (and please close it if #2003 has the wheels in motion).

p.s. we're ironing out some final Shibboleth issues, and have a test box upgraded to 4.5.1!

**Comment by mheppler** [comment]
Don, Thu-Mai, I am going to close this as a duplicate issue to #2003. I have copied over your feature request for the configurable navbar logo into a comment on that original issue. As you suggested, that ticket has some motion to it already, covering features to customize the navbar logo, about pg link, user guide link, as well as add a custom landing pg.

Those features are currently scheduled to be included in an upcoming release. We'll be announcing an updated roadmap soon, outlining major releases and the new features to be expected.

**Comment by mheppler** [comment]
Also updated the title of #2003 to include more detail: Installation Branding - Customize/configurable navbar logo + links, landing pg etc.
