### ISSUE TITLE
Data Locality Module (DLM) support (an alternative to LOCKSS?)

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#3403]
Overall issue for supporting Data Locality Module (DLM) within Dataverse.  Why would a user want to install/configure a DLM? - replicating datasets to remote storage sites (preservation, facilitating remote access, facilitating local access at the remote sites, data close to compute resources).

Similar to [DCM](https://github.com/IQSS/dataverse/issues/3145) this will be another separate component coupled to Dataverse application communicating with HTTP API calls and sharing a filesystem.   This will most likely need more changes on the Dataverse end, since Dataverse's "model of the world" will need to be expanded ("remote sites" and "storage locations for datasets"), and there will be more administrator and user level interactions.

We should be getting this more specified next week.

**Comment by pdurbin** [comment]
On Friday @joehand presented Dat ( http://dat-data.com ) to me, @djbrooke @scolapasta @landreev @sekmiller @kcondon and @bsilverstein95 . Joe knows all about LOCKSS and explained the vision for using Dat to replicate data to various data centers. I showed Joe https://data.sbgrid.org/dataset/1/ (the system we are migrating to Dataverse) and how there are rsync URLs to sites in the US, Sweden, Uruguay, and China:

![sbdg_1_-_2016-10-30_08 16 21](https://cloud.githubusercontent.com/assets/21006/19836517/2a552510-9e79-11e6-8e30-2ad11294e332.png)

Joe's reaction was that you **could** replace all those rsync links with a single Dat link and have the data in multiple data centers. While this is interesting, it's not quite what we have in mind. The technology we plan to use to replicate data from one site to others is Globus/GridFTP. (I still own @pameyer feedback on his DLM write up at https://docs.google.com/document/d/1VCblZjSnC71MuX78GBKDuPk0HyweswNkJxbzinMq2Kw/edit?ts=57f5026a ). The next logical step in my mind is to open source the DLM code so developers like Joe can see how it works. 

Note that #3249 is the issue tracking what the end users sees on a dataset page in terms how how to download the files (such as rsync). There's a big difference between pushing data around between data centers and the download mechanisms available to end users for ultimately downloading the data from their data center of choice (probably the one geographically closest to them). Anyway, great presentation by Joe. Dat is a very interesting and promising new technology.

**Comment by eugene-barsky** [comment]
Maybe this would of interest to @axfelix over at Compute Canada

**Comment by axfelix** [comment]
Yup, we've done some work with Globus, would be nice if Dataverse somehow implemented the Globus APIs in a way that facilitated easy transfer of data from a Dataverse instance to a Globus Endpoint.

**Comment by eugene-barsky** [comment]
Similar to work Dataverse did with Open Science Framework...

E.

**Comment by pameyer** [comment]
@axfelix - Globus is the first protocol we're working on.  This is more 'move dataset from a Globus Endpoint in the same installation as Dataverse to another Endpoint' than 'Dataverse with no endpoint into Globus'.

I'm not fully up to speed on the Open Science Framework, but I imagine @pdurbin could bring me up to speed if necessary.

**Comment by pdurbin** [comment]
Related: #4396

**Comment by pdurbin** [comment]
@pameyer I think visuals help so I'm attaching slide 7 from the [slides](https://schd.ws/hosted_files/dataversecommunitymeeting20/83/Slides%20-%20Biomedical%20Dataverse%20Structural%20Biology%20and%20Beyond-Meyer.pdf) you used during the [Biomedical Dataverse: Structural Biology and Beyond](https://dataversecommunitymeeting20.sched.com/event/F7Vn/biomedical-dataverse-structural-biology-and-beyond?iframe=no&w=100%&sidebar=yes&bg=no) talk over the summer during the [2018 Dataverse Community Meeting](https://projects.iq.harvard.edu/dcm2018/agenda):

<img width="1153" alt="screen shot 2018-10-24 at 12 20 02 pm" src="https://user-images.githubusercontent.com/21006/47445702-94b13b80-d787-11e8-8892-ac71d3f0c5e4.png">

**Comment by pdurbin** [comment]
Related:

- #8985
