### ISSUE TITLE
Dataset - File UI Improvements

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#3404]
There have been many suggested features and reported bugs with relation to the display of files on the dataset pg. These [mockups](https://iqssharvard.mybalsamiq.com/projects/filesprovenancefacetsfilter-dataverse40/Dataset%20-%20Files) have been created for many new features, including facets and sorting to improve browsing.

The scope of this issue will cover all the new UI improvements needed for the dataset pg. Rather than tracking nearly a dozen other issues, they'll be closed in favor of this one.

**Mockup**

![dataset-files](https://cloud.githubusercontent.com/assets/687227/19237328/521c5f0a-8eca-11e6-86f5-376da9464b25.jpg)

**Consolidated Issues**
~~- Better handling of dataset page with many files #2021~~
~~- Dataset Files: Selecting files in files tab is problematic can result in mistakes (delete, download, edit, etc). #2023~~
~~- Request Access for Files: Admin View Usability Issues #2285~~
~~- Use Solr for file listing on dataset page #2455~~
~~- Dataset Page: File Tab Sort Button #2506~~
~~- Dataset Page File Tab: Add Facets #2508~~
~~- Page printing: Messy printing of dataset #2584~~
~~- Dataset: Select > Edit Files > Delete, large number of files, page does not refresh #2591~~
~~- Files Tab: File count does not indicate how many files are currently displayed from total. #2681~~
~~- Dataset Files - DataTable LiveScroll w/ Duplicate Files #2699~~
~~- Dataset Files Table: Table Tries to Load More Files, When There Are No More #2701~~
~~- Add "View All" button for files on the dataset page #2705~~
~~- Files Tab: Tabular data tags are not sorted. #2808~~
~~- data files scrolling: users report Chrome not allowing to scroll past 25-50 files #2835~~
~~- File Page: Add Back to Top Option at Bottom of Page #2923~~
~~- sorting file by downloads: feature request by user from HKS #2947~~
- Request Access: According to mockups, there should be a request access popup. #2552
- Dataset Page: Download button for tabular file has dropdown but is cut off if near the bottom of the list of files #3835
- Dataset Page: Should lazy load thumbnails to better support slower storage media and improve page responsiveness. #4091
- Dataset Page HTML cleanup (W3 validator errors) #3750

These are related issues, which will remain open in order to track development of other projects which will impact this project.

**Related Issues**
- Dataset: File Hierarchy + Directory Structure #2249
- Initial ADA check: Primeface hidden checkboxes fail compatibility #2634
- Download Permissions: Remove business logic from Application fragments. #2698
- Edit File Metadata: Select All Files in Tab, Can't Edit Them All after clicking Edit Metadata #2859 
- UI Cleanup - Action Button + Metrics Block Layout #3341 
- Download button present for files in previous dataset versions when newest version is restricted #3576
- Performance degradation investigation #3631
- File Download: Changing the list of selected files for a multipage file list results in bad download all behavior. #3711
- Improve visibility of buttons for data owners #3815
- UI to enable file tags to be searched #4122 
- File Tags - Improve UI/UX and misc. bugs #6074
- Dataset page: Page fails to load when it cannot understand an image file to generate thumbnail #4473
- Long (e.g. SHA-512) fixity checksums are too long for display #5210 
- I'd like to be able to select and copy just the DOI from the citation block #4994

**Comment by amberleahey** [comment]
Hi there, just wondering will file organization on the dataset landing pages be supported in a future release? We have had a few members interested in this for a while now as currently the pages get cluttered and disorganized quite easily when many files are uploaded. Some even contain hundreds of files and when this happens it is not easily accessible for people to get at or understand any structure. Thanks for considering this for a future release, btw really like the mockup!

**Comment by pdurbin** [comment]
@amberleahey do you have any sketches of how you'd like the file organization to look? Or maybe you can point us to a webapp that does this well.

**Comment by amberleahey** [comment]
the mock-up you have looks pretty nice for organization, but perhaps you could also add folder hierarchy or some structure to this? In some cases, we've had requests for this at the file level to support types of files, hierarchy of files, etc. It's difficult currently for files with more than 10 files, so anything will help! Thanks again maybe we will look into developing some mock-ups to support this development work.

**Comment by TaniaSchlatter** [comment]
@amberleahey Thanks for adding your comments. I agree that it makes sense to work the requests for file organization/hierarchy into these other file UI improvements that have been mocked up. We don't have a plan to address these in the next sprint, but continued requests for these refinements should help them get prioritized.

**Comment by TaniaSchlatter** [comment]
Note that the UI changes related to the citation block shown on this mock up are obsolete.

**Comment by mheppler** [comment]
Issue **View Dataset Versions Button does not appear on Page Load #2782** was moved through development by simply removing the button. If a new dataset layout requires additional version navigation in the UI, beyond the Versions tab, we should reference the discussion in that issue, in regards to concerns with page performance.

**Comment by dconner3** [comment]
Hello. We are using the "Request Access" button on a restricted file, but the emails we receive does not tell us who the requester was. 

It seems like this ticket (as well as two preceding tickets (https://github.com/IQSS/dataverse/issues/1476, https://github.com/IQSS/dataverse/issues/2552) were going to try an address this issue. Is there any update?

More on our use case: 
Without being able to follow up with individual requesters, all we get out of using the button is that there is interest in the restricted file. We plan on making it public eventually, but for now it needs to be embargoed. We want to give access to individual requestors, but the "Request Access" button does not give us the information we need to do that.

**Comment by pdurbin** [comment]
@dconner3 I agree with what @mheppler is saying but if the email doesn't show the email address of the person who clicked "Request Access", please open a new issue about this with a screenshot, if possible. I wanted to point out that even if the email doesn't say who clicked "Request Access" which, again, would be a bug), the email should link you to the dataset and from the web interface you should be able to see the email address of the person who requested the file. For example, "pdurbin3@mailinator.com" would be the person who clicked "Request Access" in the screenshots below, which I can see by clicking "Edit" then "Permissions" then "File" like this:

<img width="1373" alt="screen shot 2018-10-11 at 8 50 18 pm" src="https://user-images.githubusercontent.com/21006/46841796-0c4e9600-cd98-11e8-8235-51065b8933f5.png">

<img width="1373" alt="screen shot 2018-10-11 at 8 50 38 pm" src="https://user-images.githubusercontent.com/21006/46841794-0c4e9600-cd98-11e8-829d-816ea7b9e6cd.png">

<img width="1269" alt="screen shot 2018-10-11 at 9 00 35 pm" src="https://user-images.githubusercontent.com/21006/46841938-bcbc9a00-cd98-11e8-95a2-76f4b7ce9da5.png">


For some reason, I didn't receive the email from the server I tested on which is why I'm hoping you can create a new issue with a screenshot. I hope the workaround of looking in the web interface for the email address of the person who clicked "Request Access" helps. The idea is that you could email them on the side and ask more questions about why they want access.

**Comment by mheppler** [comment]
Thanks for jumping in @pdurbin with some more detail. Since I seemed to overlook the email portion of this use case, I did some more digging in our issues and found this open issue.

- Permissions: Timestamp + user name in notifications/permissions pg for access requests #2855

@dconner3 if that issue covers the problem you are seeing, I would suggesting commenting there in order to track it's progress going forward. We recently added more context to contact emails (#1916), but it appears we did not add those same improvements to request access emails.

**Comment by pdurbin** [comment]
> For some reason, I didn't receive the email

Huh, I finally got the email about six hours ago. Screenshot below. Sure enough, there's no way to tell who requested the file, just like @dconner3 said. That's not great.

<img width="592" alt="screen shot 2018-10-13 at 9 02 11 am" src="https://user-images.githubusercontent.com/21006/46905813-f390ce00-cec6-11e8-9725-b2c537ae6472.png">

@dconner3 do you feel like creating an issue for this? The fix should be relatively straightforward.

**Comment by dconner3** [comment]
Sorry for falling off this thread. Thank you for the additional information @pdurbin on how to see who the requester is through the web interface. @pdurbin, it looks like you added a screenshot to #2855. You don't need me to open an additional issue do you?

**Comment by djbrooke** [comment]
Before we bring this to development, we need to 

- [ ] Review Dataset Button options for scalability
- [ ] Review File list in File Table for scalability
- [ ] Determine Usability Testing strategy, scope, and plan
- [ ] Complete Usability Testing
- [ ] Implement Usability feedback
- [ ] Implement front end code (before sprint or in sprint)

**Comment by pdurbin** [comment]
This is a good issue to follow for updates:

- Dataset Page Redesign #6605
