### ISSUE TITLE
When users convert their account from the "Username/Email and Password" to the "Institutional Log In" option, they receive a confirmation email with no link

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#3407]
Per https://help.hmdc.harvard.edu/Ticket/Display.html?id=242106 somehow this message was sent by https://dataverse.harvard.edu running v. 4.5.1 build 49-7e5e8c9 which doesn't contain a "confirm email" link to click. Confirm email is new as of 4.5.1 (#2170) and I'm not sure how to reproduce this bug. It may have something to do with Shibboleth but I'm not sure. Shibboleth users should not be asked to confirm their email since we trust the email address being asserted by their institution. We should figure out if we can reproduce this.

```
From: support@dataverse.org
Sent: Thursday, October 06, 2016 2:09 PM
To: REDACTED
Subject: Dataverse: Verify your email address

Hello, REDACTED.

Please contact us if you did not intend this change or if you need assistance.

Thank you,
The Dataverse Project
```

**Comment by djbrooke** [comment]
@bsilverstein95 - welcome back. I'm going to assign this one to you.

**Comment by pdurbin** [comment]
This bug is easy to reproduce. All you have to do is convert your builtin account to a Shibboleth account, which I did yesterday on https://dataverse.harvard.edu running v. 4.6.1 build 69-1ed82ae. This is the email I got:

```
From: <support@dataverse.org>
Date: Tue, Apr 4, 2017 at 11:50 AM
Subject: Dataverse: Verify your email address
To: philip_durbin@harvard.edu

Hello, Philip.

Please contact us if you did not intend this change or if you need assistance.

Thank you,
The Dataverse Project
```

Obviously, the email above is not useful, but as @TaniaSchlatter points out in #3704 it's easy to forget which of the five options you used to create your account so maybe some sort of email should be sent when you convert your account from builtin to Shib or OAuth.

**Comment by kcondon** [comment]
This is still an issue and now with the removal of the Dataverse string from notifications to make it more brandable it says, {0}: Verify your email address rather than Dataverse: Verify your email address

**Comment by pdurbin** [comment]
@bsilverstein95 a screenshot for you:

![screen shot 2017-06-20 at 2 58 07 pm](https://user-images.githubusercontent.com/21006/27350660-f239633c-55c8-11e7-926e-263eea03f23d.png)

**Comment by pdurbin** [comment]
I think we'll work on this issue naturally when we work on #3300 so I'm closing it.
