### ISSUE TITLE
Remove instantiation of `ShibAuthenticationProvider` in `AuthenticationServiceBean#startup`?

### ISSUE THREAD

**Issue by michbarsinai** [IQSS/dataverse#3410]
The `startup()` method of `AuthenticationServiceBean` contains an instantiation of `ShibAuthenticationProvider`. Seems not to have any effect?

https://github.com/IQSS/dataverse/blob/develop/src/main/java/edu/harvard/iq/dataverse/authorization/AuthenticationServiceBean.java#L98

**Comment by pdurbin** [comment]
As I look into #3445 I'm wondering if in the ORCiD-integration branch we need to change the way we enable Shibboleth. I'm on 28120f6 and locally I added more logging to AuthenticationServiceBean...

    public AuthenticationProvider lookupProvider( AuthenticatedUser user )  {
        logger.info(user + " has provider id: " + user.getAuthenticatedUserLookup().getAuthenticationProviderId());
        for (Map.Entry<String, AuthenticationProvider> entry : authenticationProviders.entrySet()) {
            String key = entry.getKey();
            AuthenticationProvider value = entry.getValue();
            logger.info(key + ":" + value);
        }
        logger.info("done iterating");
        return authenticationProviders.get(user.getAuthenticatedUserLookup().getAuthenticationProviderId());
    }

... and I don't see a "shib" provider:

  [AuthenticatedUser identifier:@9d79b13c] has provider id: shib]]

[2016-11-02T09:29:49.828-0400] [glassfish 4.1] [INFO] [] [edu.harvard.iq.dataverse.authorization.AuthenticationServiceBean] [tid: _ThreadID=32 _ThreadName=http-listener-1(3)] [timeMillis: 1478093389828] [levelValue: 800] [[
  builtin:edu.harvard.iq.dataverse.authorization.providers.builtin.BuiltinAuthenticationProvider@398561c]]

[2016-11-02T09:29:49.828-0400] [glassfish 4.1] [INFO] [] [edu.harvard.iq.dataverse.authorization.AuthenticationServiceBean] [tid: _ThreadID=32 _ThreadName=http-listener-1(3)] [timeMillis: 1478093389828] [levelValue: 800] [[
  echo-dignified:edu.harvard.iq.dataverse.authorization.providers.echo.EchoAuthenticationProvider@12c56dae]]

[2016-11-02T09:29:49.828-0400] [glassfish 4.1] [INFO] [] [edu.harvard.iq.dataverse.authorization.AuthenticationServiceBean] [tid: _ThreadID=32 _ThreadName=http-listener-1(3)] [timeMillis: 1478093389828] [levelValue: 800] [[
  echo-simple:edu.harvard.iq.dataverse.authorization.providers.echo.EchoAuthenticationProvider@2cedd8dd]]

[2016-11-02T09:29:49.828-0400] [glassfish 4.1] [INFO] [] [edu.harvard.iq.dataverse.authorization.AuthenticationServiceBean] [tid: _ThreadID=32 _ThreadName=http-listener-1(3)] [timeMillis: 1478093389828] [levelValue: 800] [[
  orcid-sandbox:edu.harvard.iq.dataverse.authorization.providers.oauth2.impl.OrcidOAuth2AP@93a97228]]

...

```
Info:   [AuthenticatedUser identifier:@9d79b13c] has provider id: shib
Info:   builtin:edu.harvard.iq.dataverse.authorization.providers.builtin.BuiltinAuthenticationProvider@398561c
Info:   echo-dignified:edu.harvard.iq.dataverse.authorization.providers.echo.EchoAuthenticationProvider@12c56dae
Info:   echo-simple:edu.harvard.iq.dataverse.authorization.providers.echo.EchoAuthenticationProvider@2cedd8dd
Info:   orcid-sandbox:edu.harvard.iq.dataverse.authorization.providers.oauth2.impl.OrcidOAuth2AP@93a97228
Info:   done iterating
Info:   Could not find auth provider for user: [AuthenticatedUser identifier:@9d79b13c
```

That last "Could not find auth provider" I added as well, to DataverseUserPage:

    AuthenticationProvider getUserAuthProvider() {
        if ( userAuthProvider == null  ) {
            userAuthProvider = authenticationService.lookupProvider(currentUser);
        }
        if (userAuthProvider == null) {
            String error = "Could not find auth provider for user: " + currentUser;
            logger.info(error);
        }
        return userAuthProvider;
    }

Anyway, I'm growing a bit concerned about the regressions in ORCiD-integration. As #3445 explains, you get a 500 error when you create a local account or a Shibboleth account.

**Comment by pdurbin** [comment]
@michbarsinai I addressed this issue in 6952dbd and would love for you to take a look. I put this in Code Review at https://waffle.io/IQSS/dataverse and am assigning this to you. Thanks!

**Comment by michbarsinai** [comment]
The code looks good. Unless we want to tackle the full change at this point (that is, adding a ShibProviderFactory and using an AuthenticationProviderRow to enable shib). I'm fine with leaving it as-is or doing the full refactor.

**Comment by djbrooke** [comment]
@pdurbin - based on the discussion in standup this morning, I'll close this one out. I'll leave a note in #3338 that we'll test it there.

**Comment by pdurbin** [comment]
The other day in 546ae73 I improved the code to bring Shib in line with other auth providers. I think @michbarsinai would approve. 😄
