### ISSUE TITLE
Provenance Export

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#3416]
The [Provenance System](https://www.usenix.org/conference/tapp12/workshop-program/presentation/macko) will provide an export of a "Provenance Bundle." This is a JSON file and we should provide some way through the UI to export this file.

**Comment by mheppler** [comment]
The mockups are being finalized, and can be reviewed in [Balsamiq](https://iqssharvard.mybalsamiq.com/projects/filesprovenancefacetsfilter-dataverse40/File%20-%20Provenance%20-%20Details).

![screen shot 2016-11-14 at 2 41 10 pm](https://cloud.githubusercontent.com/assets/687227/20279923/75fe5bb6-aa78-11e6-860a-e04390fc45c1.png)

**Comment by djbrooke** [comment]
Replaced by #4346
