### ISSUE TITLE
Shibboleth: Improve help text/provide options if your institution isn't listed

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#3420]
If you go to Sign Up ( https://dataverse.harvard.edu/dataverseuser.xhtml?editMode=CREATE&redirectPage=%2Fdataverse.xhtml ) you'll see at the top "Want to create your account through your institution? Log In here." You click and see long list (over 200 institutions) and "Select your institution and click "Continue" to log in via your institution's authentication system... Use Dataverse with your institutional log in instead of creating an account. Learn More." When you click "Learn More" it says "Institutional log in allows you to use your log in information for your university (e.g. HarvardKey at Harvard) to log into your Dataverse account. By using your institutional log in, you won’t have to remember your password for Dataverse or manage another account."

This is a dead end. We should add something like "if your institution is not on the list, contact your IT department to see if your institution is part of the Research & Scholarship (R&S) category of the InCommon federation".

The way the fix was described by @nmedeiro at https://groups.google.com/d/msg/dataverse-community/txP-gHrpXGA/zV3ztgNaAAAJ was this:

"We've been using Harvard's hosted Dataverse for few years, and our users had to create separate accounts to log in.  Once Shibboleth was enabled on Dataverse, I worked with Phil and Haverford's identity staff to have us added to the Research & Scholarship category of InCommon. Now our users can take advantage of single sign-on with their college credentials, which is much more convenient for them."

(For more details on what Research & Scholarship is, see http://guides.dataverse.org/en/4.5.1/installation/shibboleth.html#identity-federation and for an even deeper dive, see #2937.)

For a real-world example of the confusion, see https://help.hmdc.harvard.edu/Ticket/Display.html?id=242595#txn-4859135 . The work around, of course, is to create a local account.

Reducing the friction to creating an account will help with our number one goal of "increase adoption (users, dataverses, datasets, installations, journals)" at http://dataverse.org/goals-roadmap-and-releases and this doc change is very low hanging fruit.

**Comment by pdurbin** [comment]
There's also the opposite problem (and maybe should be in yet another issue). We got a report in https://help.hmdc.harvard.edu/Ticket/Display.html?id=241588 that UC Davis shows up in the list (because they're part of R&S) get the user got "given name was null" when attempting to log in. This should never happen because all Identity Providers (IdPs) that are part of R&S are supposed to release the "Research & Scholarship Attribute Bundle" per https://spaces.internet2.edu/display/InCFederation/Research+and+Scholarship+Attribute+Bundle

**Comment by mheppler** [comment]
Having dipped into the Institutional Log In section of the User Guide with the ORCID/OAuth branch, Phil and I reviewed this issue and propose adding this paragraph to the *Account Creation + Management > Remote Authentication > Institutional Log In > Create a Dataverse account using Institutional Log In* section of the User Guide.

> If you do not find your institution listed,  you will need to request that it is added to the Research & Scholarship category of InCommon. Contact support for assistance on how to get this process started with the identity provider support team at your institution.

**Comment by pdurbin** [comment]
@mheppler and I discussed adding this to the 3338-oauth-login branch before we make a pull request.

**Comment by pdurbin** [comment]
The suggestion by @mheppler looks great and in 67bc192 I added it to the 3338-oauth-login branch, which is where the change should be QA'ed. I'm moving this issue to QA in https://waffle.io/IQSS/dataverse

**Comment by kcondon** [comment]
Paragraph added. Closing.
