### ISSUE TITLE
API: Allow changing label, description and tags of an existing file

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3422]
Complementary feature to adding a file via API
- related: #1612 #2497
## 

Description of API:
- [ ] Modifying label, description, categories or tags for **1 or more SELECTED files** in a dataset
  - API endpoint receives list of file ids (database ids)
- [ ] Modifying label, description, categories or tags for **ALL files** in a dataset
  - API endpoint receives dataset id or persistent identifier
- [ ] Distinguish between:
  - ADDing to existing tag 
  - REPLACING existing tags with the new list

Note: Currently there is no way to add tabular tags via API.

## Starting point

Scratch code to get started

- Logic for Files.java API: https://gist.github.com/raprasad/c962ce00217a169238f5461138326135
- Add this to the ```datasetutility``` package: https://gist.github.com/raprasad/e714c99ec1731d41442cffd27e875397

---

**Comment by pdurbin** [comment]
Not a bad idea but this issue doesn't have a champion anymore. Closing.
