### ISSUE TITLE
SMTP setup failure during Dataverse install

### ISSUE THREAD

**Issue by bsilverstein95** [IQSS/dataverse#3424]
Opening this issue per the advice of @pdurbin as I cannot currently install Dataverse due to the step which prompts for an SMTP server. As I'm not on Harvard's network while installing, [mail.hmdc.harvard.edu] - the default SMTP value - fails to connect after a few seconds. When I entered 'localhost' instead, the installer instantly returned a failure.

![installer failure](https://cloud.githubusercontent.com/assets/16244907/19657825/aa42b740-99f3-11e6-9114-9d511ba009ae.jpg)

**Comment by pdurbin** [comment]
@bsilverstein95 as a work around for now you could set `$mail_server_status` to `1` at https://github.com/IQSS/dataverse/blob/v4.5.1/scripts/installer/install#L1398

Longer term we should probably add a flag to the installer that developers can use (#3163 basically) which should:

- bypass the SMTP server check (this issue)
- pass `--insecure` run `setup-all.sh` #3163 

#2443 is definitely related.

**Comment by pdurbin** [comment]
@bsilverstein95 if you're truly blocked on this you **could** consider trying one of the altenative ways of getting a Dataverse dev environment set up. Please see http://bl.ocks.org/pdurbin/raw/7847a0642f8bd6601a07c3619b4a35f6/#2 (screenshot below):

![screen shot 2016-10-26 at 2 04 01 pm](https://cloud.githubusercontent.com/assets/21006/19738382/3247294a-9b85-11e6-9ae2-e106544bfff1.png)

These days I actually use a mix of @bmckinney 's fantastic https://github.com/bmckinney/dataverse-osx-playbook and my "homebrew" scripts that I described at https://github.com/IQSS/dataverse/issues/2443#issuecomment-130005115 . All of this is not for the faint of heart! There be dragons! I'd recommend the `$mail_server_status` workaround I mentioned earlier. You could also try running a mailserver on localhost if you want.

**Comment by bsilverstein95** [comment]
Closing this because the clearest solution is to just set up developer Dataverse installation on Harvard University's network and, if necessary, employ a quick-fix/hack to keep SMTP disconnection from breaking the app (while working remote) courtesy of @raprasad : 

https://dataverseteam.slack.com/files/raprasad/F2V3UVCVD/by_passing_email.java

Placing that snippet into MailServiceBean.java should keep the app from crashing due to mail server disconnection. Another suggested alternative that might work well is a VPN to Harvard's network in the case of actually wanting to utilize mail.hmdc.harvard.edu.
