### ISSUE TITLE
Add /info/version API endpoint

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#3426]
We recently removed a simple test endpoint /test/echo which was only accessible by an admin. We want to replace it with /info/version which will serve the same purpose, as well as give more info as to the version of Dataverse that is running.

**Comment by morris-jason** [comment]
I will get started on this.

**Comment by michbarsinai** [comment]
@kcondon @pdurbin is there a place in the code the version/build number are available?

**Comment by pdurbin** [comment]
@michbarsinai yes, just pass "true" to `public String getVersion(boolean withBuildNumber)` at https://github.com/IQSS/dataverse/blob/v4.5.1/src/main/java/edu/harvard/iq/dataverse/util/SystemConfig.java#L80

(A related factoid is that in Jenkins we create `src/main/java/BuildNumber.properties` on the fly to include the SHA1 of the git commit.)

**Comment by michbarsinai** [comment]
Implementation:
Testing notes:
* I've added the guides URL, seems useful
* To get a value in the build number, the build has to be done via Jenkins (see @pdurbin's note above).

````json 
dataverse$ http localhost:8080/api/info/version
HTTP/1.1 200 OK
Content-Length: 110
Content-Type: application/json
Date: Thu, 17 Nov 2016 08:13:40 GMT
Server: GlassFish Server Open Source Edition  4.1
X-Powered-By: Servlet/3.1 JSP/2.3 (GlassFish Server Open Source Edition  4.1  Java/Oracle Corporation/1.8)

{
    "data": {
        "build": null,
        "guides": "http://guides.dataverse.org/en",
        "version": "4.5.1"
    },
    "status": "OK"
}
````

**Comment by michbarsinai** [comment]
Guides fixed, no longer containing the error Gustavo found.

**Comment by pdurbin** [comment]
I added some REST Assured tests in 2fd543a.
