### ISSUE TITLE
File Tabular Tags - Tags applied in DRAFT version displayed in published version

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#3429]
I saw this locally, and was able to confirm this in demo (4.5.1). When file tabular tags are applied in a DRAFT version of a dataset, they are also displayed in published version. This should not be the case, and is not how the category tags function. In the screenshot below, we see the "Survey" tabular tag displayed for V1 of the dataset, but that was only added in the DRAFT version of the dataset and not yet published.

![screen shot 2016-10-25 at 4 00 03 pm](https://cloud.githubusercontent.com/assets/687227/19702433/a5c14d78-9acd-11e6-899e-6bb5245eb812.png)

Related to #3430.

**Comment by mheppler** [comment]
Discussed this with @sekmiller @scolapasta @landreev and it may be functioning as designed. Will hold off on closing until we can confirm that we don't need to change anything in association with other file and version related projects.

**Comment by mheppler** [comment]
Originally reported in _Version Differences Detail - Tabular tags applied in DRAFT version not recorded in Version Details #3430_, @scolapasta suggested it was a similar issue, and I believe one is a symptom of the other, so I will close the other issue and move the info from that issue here:

> I saw this locally, and was able to confirm this in demo (4.5.1). When file tabular tags are applied in a DRAFT version of a dataset, they are not recorded in the Version Differences Detail. This should not be the case, and is not how the category tags function. In the screenshot below, we see the custom category tag "Sample" is recorded, but it is missing the "Survey" tabular tag.
> 
> ![screen shot 2016-10-25 at 4 14 45 pm](https://cloud.githubusercontent.com/assets/687227/19702571/2d59ed94-9ace-11e6-8f0c-0a0984eed430.png)

**Comment by TaniaSchlatter** [comment]
Discussed in the design meeting August 17: tech design discussion is needed for tabular tags and how they are applied to dataset versions, also discussion needed on improving how the system handles.
