### ISSUE TITLE
Version Differences Detail - Tabular tags applied in DRAFT version not recorded in Version Details

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#3430]
I saw this locally, and was able to confirm this in demo (4.5.1). When file tabular tags are applied in a DRAFT version of a dataset, they are not recorded in the Version Differences Detail. This should not be the case, and is not how the category tags function. In the screenshot below, we see the custom category tag "Sample" is recorded, but it is missing the "Survey" tabular tag.

![screen shot 2016-10-25 at 4 14 45 pm](https://cloud.githubusercontent.com/assets/687227/19702571/2d59ed94-9ace-11e6-8f0c-0a0984eed430.png)

Related to #3429.

**Comment by scolapasta** [comment]
Similar to #3429, Tabular tags are not part of versions.

**Comment by mheppler** [comment]
Closing in favor of _File Tabular Tags - Tags applied in DRAFT version displayed in published version #3429_.
