### ISSUE TITLE
WorldMap: Dataset citations longer than 255 chars cause an error

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3432]
## Problem
- The code limits the Dataset citation to 255 characters—the error is happening when the citation is longer
## First impression
- Full Fix:
  1. Change the “geoconnect” code to accept a longer citation (nearly unlimited)
  2. Change the “geoconnect" database column type to accept a longer citation 
     1. Change the WorldMap code (shared)  to accept a longer citation 
     2. Change the WorldMap database column type to accept a longer citation 
- Partial fix:
  - Do 1. and 2. which doesn’t touch the WorldMap
  - Pros: user should see be able to run map and see expected results
  - Cons: Citation stored in WorldMap will be truncated

![image001](https://cloud.githubusercontent.com/assets/1036060/19737630/285cc910-9b82-11e6-97b3-ab4bbab20d8d.png)

**Comment by raprasad** [comment]
File to change: https://github.com/IQSS/shared-dataverse-information/blob/master/shared_dataverse_information/dataverse_info/models.py

Change ```dataset_citation```:
 
  - Original: ``` dataset_citation = models.CharField(max_length=255)```
  - Updated: ``` dataset_citation = models.TextField()```

Steps after change is made and checked in:

- Update this library in pypi to version 0.5.6:
  - https://pypi.python.org/pypi/shared_dataverse_information/0.5.5

## Geoconnect
  - Update the requirements file in geoconnect:
    - https://github.com/IQSS/geoconnect/blob/master/requirements/base.txt#L1
  - Update the geoconnect migrations and save in github
  - Run the migrations:
    - On geoconnect dev (heroku)
    - On geoconnect prod (heroku)

## WorldMap
  - Update the requirements file in the worldmap legacy branch:
    - https://github.com/cga-harvard/cga-worldmap/blob/legacy/shared/requirements.txt#L69
  - Open a pull request and have WM team update:
     - shared_dataverse_information library
     - update the database column

Note 1: WorldMap should be updated before geoconnect on dev/prod

Note 2: Checked the 3 codebases* that dataset_citation size doesn't appear on any validation forms, etc.  e.g., the model size (currently 255) is used for any validation. * (shared_dataverse_information, geoconnect, worldmap)

**Comment by pdurbin** [comment]
We discussed this issue at standup this morning and I floated the idea of doing the "partial fix" described above of truncating the citation on the WorldMap side. It sounds like we don't want this so it would be a waste of effort. I guess I'll leave this issue assigned to me for now because I'd like to see if I can add a failing test.

Speaking of tests, I also added tests as part of #3489 but they are not automatically executed so they could start failing at any time. Since we're already using https://travis-ci.org/IQSS for Dataverse and Zelig, we should probably attempt to figure out how to add a Django app to Travis and run the tests automatically. I did a quick search for this but it seems somewhat involved: https://docs.travis-ci.com/user/languages/python/

**Comment by pdurbin** [comment]
I'm blocked on this issue because I can't get WorldMap installed so I'm unassigning myself. The error I'm seeing is at the `paver build` step: https://github.com/IQSS/worldmap-legacy-dev/commit/fc8136865a5989a412fd1ab9fcdcd8f6af561cf7#commitcomment-21735918

**Comment by raprasad** [comment]
- [x] shared dataverse information repository update
- [ ] geoconnect repository update
   - [  ] geoconnect dev db update (updated requirements)
   - [  ] geoconnect prod db update (updated requirements)
- [ ] worldmap repository update
   - [  ] worldmap prod db update (updated requirements)

**Comment by raprasad** [comment]
Code updated on 2/4 repositories. and 2/4 servers

**Comment by raprasad** [comment]
Last commit is a 1-liner for the dataverse codebase

**Comment by raprasad** [comment]
pull requested add to worldmap codebase: https://github.com/cga-harvard/cga-worldmap/pull/228

**Comment by raprasad** [comment]
Note: Will coordinate with Paolo re: the Worldmap update and then it can be moved to QA

**Comment by raprasad** [comment]
Testing
- Create a dataset where the citation is over 255 characters
- Add a mappable file (e.g. shapefile)
- Check if the citation is carried to the final map.  Currently, WorldMap returns a non-descript error b/c of a 255 char limit on the citation size

**Comment by raprasad** [comment]
Status:
 - can code review:
   - Dataverse code
   - Geoconnect code
 QA
  - Pull request in for WorldMap change.  Will coordinate when that is in--then the ticket can go to QA

**Comment by pdurbin** [comment]
It looks like https://github.com/IQSS/geoconnect/pull/129 was already merged. https://github.com/cga-harvard/cga-worldmap/pull/228 hasn't but looks fine. https://github.com/IQSS/dataverse/pull/3772 is small and looks good. I'm moving this to QA at https://waffle.io/IQSS/dataverse

**Comment by raprasad** [comment]
@kcondon will you let know when WorldMap code has been deployed for testing

**Comment by raprasad** [comment]
How to test (from comment above):

-  Create a dataset where the citation is over 255 characters
-  Add a mappable file (e.g. shapefile)
-  Check if the citation is carried to the final map. Currently, WorldMap returns a non-descript error b/c of a 255 char limit on the citation size
