### ISSUE TITLE
Add dataverse-client-java to Client Libraries page in API Guide, mention SDK, explain support

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#3434]
As of Dataverse 4.5.1 there are client libraries for Python and R mentioned at http://guides.dataverse.org/en/4.5.1/api/client-libraries.html but there's a new kid on the block who deserves mention as well!  @richarda23 has created https://github.com/IQSS/dataverse-client-java and we should add it to the page.

While I'm on that "Client Libraries" page, I plan to make some additional changes as well:

- What I call a "client library" Danny calls an "SDK" and I'm sure he isn't alone, so I plan to put the word "SDK" in there.
- Explain how to get support for these libraries.
- Sadly, "Robert Liebowitz from the Center for Open Science heads its development" is no longer true of dataverse-client-python so I need to find some better phrasing. I've asked @felliott for advice here but I'll come up with something.

**Comment by pdurbin** [comment]
I made pull request #3435 and moved this issue to Code Review at https://waffle.io/IQSS/dataverse

I'd be happy for anyone from the Dataverse team to take a look as well as @richarda23 (who we added) @leeper @rliebz (modified) and @felliott

Incidentally, I did try out dataverse-client-java this morning from my Ubuntu laptop from home. Works great. 😄 I'd like to start making use of it in automated testing (#2746) in REST Assured tests.

**Comment by pdurbin** [comment]
@donsizemore sounds excited: http://irclog.iq.harvard.edu/dataverse/2016-10-27#i_43832 😄

**Comment by djbrooke** [comment]
Hey @pdurbin - looks good! Thanks for making these changes. 

@richarda23 @leeper @rliebz @felliott - I'll plan to merge this documentation change before the weekend and any needed changes can be in a follow-on PR.

**Comment by pdurbin** [comment]
I made a small change at 71b2c33 based on feedback at https://github.com/IQSS/dataverse/pull/3435/commits/540de0a64f1f1fa164c88f367e36dc52a6f806d2#r85438102 to link to the https version of COS websites.

**Comment by pdurbin** [comment]
@richarda23 I'm already referencing this pull request at http://irclog.iq.harvard.edu/dataverse/2016-10-28#i_43884 . Can you please jump in http://chat.dataverse.org and see if you can answer questions about 96 well plates? I'm out of my depth! 😄

**Comment by djbrooke** [comment]
Thanks - I didn't catch the redirect. I'm going to close this out, but we can revisit it in another issue if there are further changes.
