### ISSUE TITLE
Email Verification: 2 issues; refresh un-verifies, verify email button should always be available.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3438]
Users are starting to use this feature and one reported an issue where they had confirmed their email but the account page said not verified and they did not know what to do, see RT 242896

I found a couple things that may impact this:
1. If I'm on the account info page where there is a verify email button, I press it and then after clicking the confirmation button I refresh that page, it asks to resubmit the form and then it "unverifies" me and sends another email.
1. It seems the verify email button does not appear until after the initial confirmation email timeout, default 24hrs. In cases where there is an issue, like this, it may be useful to always display the button.

**Comment by pdurbin** [comment]
I  just noticed this bug at https://github.com/IQSS/dataverse/issues/3405#issuecomment-256977123

**Comment by bsilverstein95** [comment]
Assigning this issue to myself, will work to recreate both of these and go from there. May need to consult the team regarding best practice with changing the Verify Email button's behavior (keeping it visible after confirmation vs having it disappear).

**Comment by mheppler** [comment]
Proposed solution:
- Always show "Verify Email" button on Account pg
- User clicks button, backend logic...
  - checks for and clears expired tokens
  - checks for active tokens
  - if none, send email with new token
  - if active token found, triggers confirmation popup telling them to check their email

**Comment by chewsw** [comment]
May I check if there are any updates on the missing email verification button? I've encountered cases where the email verification button do not appear even after the 24 hours deadline has passed.

**Comment by pdurbin** [comment]
@chewsw hi, no one is working on this bug. If someone out there in the community would like to work on it, I'm happy to point out where in the code to start looking.

**Comment by TaniaSchlatter** [comment]
Notes from discussion.

Situations of use:

- people don't click the link in the welcome email, or the link in the email expires. 
- @donsizemore wants to see/track unvalidated accounts?

Conventional, general account creation flow is that users don't have an account until/unless an account is verified via email. This convention prevents security issues and reduces fake/dead accounts. Users should not be able to do anything without a verified account.

**Comment by TaniaSchlatter** [comment]
@poikilotherm I edited the notes above after further discussion with @pdurbin. Are you thumbs up for having the request account verification email, or for questioning the purpose of unverified accounts?

**Comment by TaniaSchlatter** [comment]
Adding a screenshot of the current state:

<img width="1456" alt="Screen Shot 2020-09-03 at 3 01 54 PM" src="https://user-images.githubusercontent.com/15386424/92161189-4139bb00-edfe-11ea-9ad9-62897acbf0d9.png">

**Comment by poikilotherm** [comment]
Questioning unverified accounts. Every service out there these days will force you to validate your email address. Some just show a banner, some are more restrictive. IMHO a banner is a must to remember people, now that mail groups are a reality. IMHO this could be extended to limit people to read-only access, as a valid email address is vital for people trying to contact a depositor.

Adding a column with the verification status to the admin user dashboard would be another huge benefit, as an admin has very limited possibilities to catch on the status without using the API right now.

**Comment by pdurbin** [comment]
@djbrooke @TaniaSchlatter and I just had a meeting and one of the questions that came up is what the user sees after clicking an expired link. The answer is an error saying "We were unable to verify your email address." Here's the error in context:

<img width="1131" alt="Screen Shot 2020-09-08 at 1 00 40 PM" src="https://user-images.githubusercontent.com/21006/92506678-cd1f5e80-f1d3-11ea-8dd6-3d9156f2621c.png">

This is a good error, of course. We want expired links to actually be expired.

As I said in the meeting, overall I feel like the confirm email feature is in pretty good shape. Clicking the link or a new account works. Clicking links for an existing unconfirmed account works.

I think the biggest problem is that if you have a link in the database and never got the email or the link expired, that expired link can hang around for a while. When you have a link already (and may not even know it) the UI won't give you the opportunity to request a new one. There's no button to click. So, now that we're getting better at timers, I would suggest putting the "delete expired links" method on a timer that runs every day or every hour.

**Comment by mheppler** [comment]
Adding responsive layout UI cleanup note from other issues, as it is more appropriate to fix in this effort.

- email verify icon overlaps email address #4484
- Handle long strings in the UI #6578
- Truncate methods: checksums, long summary metadata fields #6685

Anything learned in the truncating/toggle efforts of #6685 should be added here if necessary. Should investigate what the system allows for email address character limits. Wrapping long emails within the container using CSS ``word-break`` might be more appropriate than truncating with ellipses or a toggle.

**Comment by djbrooke** [comment]
I'd like to take another pass at this as part of a sprint. I was just getting back to things on Sept 8th when we discussed above (thanks @TaniaSchlatter and @pdurbin) and I asked for it to be moved back to Needs Discussion, but reviewing this again I think we can talk through the remaining issues after picking this up. My goal with this issue is to fix the verification system so that users can reliably put their accounts into a "verified" status, not make any changes to the privileges of verified/non-verified users. That can come next.

**Comment by sekmiller** [comment]
UI change for review. Part of the solution to this bug was to always display the "Verify Email" button while the user's email is unverified. If the user clicks the button while there is an active token this popup is rendered:

<img width="591" alt="Screen Shot 2021-01-14 at 11 11 03 AM" src="https://user-images.githubusercontent.com/2364928/104637286-991ce400-5672-11eb-8442-ed920daa9213.png">

**Comment by sekmiller** [comment]
For reference. this is the existing success message when the user clicks "Verify Email" when there is no active token:

<img width="757" alt="Screen Shot 2021-01-14 at 10 26 04 AM" src="https://user-images.githubusercontent.com/2364928/104637444-ccf80980-5672-11eb-9ad9-410ea3a093b9.png">

**Comment by mheppler** [comment]
Added responsive layout clean up to the fix the overlapping of the email address and verified status label, as reported in #4484. If the containing width is too small, the button and/or status label will wrap to another line. (See screenshot.)

<img width="300" alt="Screen Shot 2021-01-19 at 3 24 35 PM" src="https://user-images.githubusercontent.com/687227/105096385-f8b13000-5a74-11eb-95c1-799937cfe90c.png">
