### ISSUE TITLE
No functionality should be GUI-only. Make all functionality reachable via the API

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#3440]
As explained in our "Dataverse API Strategy (High-Level)" doc at https://docs.google.com/document/d/1gxiKGtHjZJmyLaO6j2rPTBwTNxFZazmVb9I-BlF0iMk/edit?usp=sharing there should be no functionality in Dataverse that is GUI-only. All functionality should be reachable via the API.

Please use this description to keep a running list of GUI-only functionality:

- ~#3873 Restricting files~ (added in #3967)
- ~#4645 get info about access restrictions on file level~
- #778 Deaccessioning datasets
- Setting Terms of Use
- Set "Enable Access Request" for Terms of Use: https://groups.google.com/d/msg/dataverse-community/oKdesT9rFGc/qM6wrsnnBAAJ
- Set guestbook_id for a dataset: https://groups.google.com/d/msg/dataverse-community/oKdesT9rFGc/qM6wrsnnBAAJ
- Filling out a guestbook. See also https://groups.google.com/d/msg/dataverse-dev/G9FNGP_bT0w/dgE2Fk4iBQAJ
- Downloading a guestbook
- ~#3144 Submit for Review workflow via API~ (added in #3992)
- Setting a dataverse logo
- Seeing why a file failed ingest
- Notifications (partially added in #3992)
- ~#4095 Creating OAI-PMH sets~ (added in #4096)
- ~Adding descriptions and tags to files~ - added in 4.6.1 as part of #1612: http://guides.dataverse.org/en/4.6.1/api/native-api.html#files
- editing properties of an existing dataverse
- get/set methods for dataset metadata
- setting logo image / url / "tagline" for dataverse during creation
- templates

**Comment by djbrooke** [comment]
Thanks @pdurbin - this will be useful for tracking items that we should make API-accessible. Once it comes time to work on these, we'll break into smaller chunks.

**Comment by pameyer** [comment]
A few to add to the list (potentially more to follow):
 - editing properties of an existing dataverse
 - setting facets for a dataverse
 - get/set methods for dataset metadata
 - setting logo image / url / "tagline" for dataverse during creation

**Comment by pdurbin** [comment]
I'm closing this issue because I don't think it'll ever be done. Dataverse 4 is way better than DVN 3 about having APIs for all functionality but it will take constant vigilance to make sure we don't introduce any GUI only features. Anyone reading is encouraged to open "small chunk" issues for particular functionality they'd like via API.
