### ISSUE TITLE
Geoconnect: Upgrade from Django 1.6 (insecure version)

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3442]
Make changes necessary to upgrade to Django 1.10 (python 2.7)

**Comment by raprasad** [comment]
(starting the process by trying clean install)

**Comment by raprasad** [comment]
1st step, big rename:  https://github.com/IQSS/geoconnect/commit/9fda022bb3e6d5f22f6441f73fddd08c73540c27

**Comment by raprasad** [comment]
django 1.7 tweaks
- [ ] update shared dv info to version .5
- [ ] get tests working--testrunner is updated
- [ ] update debug toolbar

**Comment by raprasad** [comment]
- [ ] make initial table migrations
- [ ] verify that 'initial_data.json' still works for classification, mapping types, etc
  - [ ] re-document initial data loading

**Comment by raprasad** [comment]
last checkin: 

- Updates to shared-dataverse-information dependency
- For HttpRepsonse, changed ```mimetype=``` to ```content_type=```
- Upgraded django-debug-toolbar version from 1.0.1 to 1.6
- Removed old django.conf.urls.patterns--used lists of urls
- Changed ```render_to_response``` to ```render```, remove imports of ```RequestContext```
- Use ```TEMPLATES``` setting from django conf files
- Templates, use ```static``` tag

**Comment by raprasad** [comment]
last commit:
- Remove old models from worldmap_connect: WorldMapImportAttempt, WorldMapImportFail, WorldMapLayerInfo
- Switch ```datetime.now()``` to ```timezone.now()```
    - using ```from django.utils import timezone```

**Comment by raprasad** [comment]
Pull Request is in Geoconnect:
https://github.com/IQSS/geoconnect/pull/118

**Comment by raprasad** [comment]
- *NOTE*: QA Dependent on configuration/installation of Dev Server which has a target date of 2/9.  As discussed with @kcondon

**Comment by kcondon** [comment]
Basic regression test works for both shape and tabular files.
