### ISSUE TITLE
lighten stroke for maps

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3444]
from the 5/24/2016 meeting

- Use a lighter stoke and color (1px, gray) to outline map boundaries.  Currently, the thicker, dark boundaries can obscure boundaries/content.
- Next Steps: Modify the classification API to default to a lighter stroke.

**Comment by raprasad** [comment]
consult with paolo to change default stroke

**Comment by djbrooke** [comment]
We talked about this in the sprint planning meeting yesterday. This change is on the Worldmap side, and it's unclear if we'll take this on. @raprasad is going to check in with Paolo and we'll fill in more details if it comes back our way.

**Comment by raprasad** [comment]
simplified code change to make: https://gist.github.com/raprasad/20c63dd2c0ebb8f2f889aabd97fce613

**Comment by raprasad** [comment]
connectsto:  https://github.com/cga-harvard/cga-worldmap/pull/215

**Comment by raprasad** [comment]
Reviewed the updated polygon border color with @mheppler 
Thanks @pdurbin for code review

**Comment by kcondon** [comment]
Map appears, the dude abides.

**Comment by raprasad** [comment]
note: paolo will be able to put this into production on 4/10
