### ISSUE TITLE
Stop distributing TestShib IdP file with old cert, better guidance on how to configure specific Shibboleth identity providers

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#3446]
At https://help.hmdc.harvard.edu/Ticket/Display.html?id=242358#txn-4856837 we got a report of trouble testing one's Shibboleth configuration with the TestShib Identity Provider (IdP) as suggested at http://guides.dataverse.org/en/4.5.1/installation/shibboleth.html#exchange-metadata-with-your-identity-provider

Since I ran into this trouble myself yesterday on https://shibtest.dataverse.org I think I now know why.

This is what I was seeing in my browser after attempting to log in with myself/myself:

---

opensaml::FatalProfileException

The system encountered an error at Tue Nov 1 11:41:35 2016

To report this problem, please contact the site administrator at root@localhost.

Please include the following message in any email:

opensaml::FatalProfileException at (https://shibtest.dataverse.org/Shibboleth.sso/SAML2/POST)

Message was signed, but signature could not be verified.

---

See also https://wiki.shibboleth.net/confluence/display/SHIB2/NativeSPTroubleshootingCommonErrors#NativeSPTroubleshootingCommonErrors-Messagewassigned,butsignaturecouldnotbeverified

(I didn't see anything helpful in https://idp.testshib.org/cgi-bin/idplog.cgi?lines=150&logname=idp-process.log but it's a good place to look when you see errors in the browser.)

The fix was to **not** use the sample dataverse-idp-metadata.xml file downloadable from http://guides.dataverse.org/en/4.5.1/installation/shibboleth.html#exchange-metadata-with-your-identity-provider but rather to use https://www.testshib.org/metadata/testshib-providers.xml from http://www.testshib.org/configure.html . Apparently certs were re-issued and the sample file we distribute with Dataverse contains the old cert.

While we're in this part of the guides, I think that we should get away from having a single "dataverse-idp-metadata.xml" file. Rather. We should distribute a file called "testshib.xml" or something (and change the shibboleth2.xml file to reference it instead). Then we can encourage users to add their own "harvard.xml" or "emory.xml" or whatever files along side these (and comment out the "testshib.xml" one before going into production. I realize this is quite in the weeds but @kcondon and @donsizemore know what I'm talking about.

**Comment by Venki18** [comment]
@pdurbin Thanks a lot for checking testshib at your end and making it work. Yeah I too prefer if you guys allows us to download xml files and reference it in shibboleth2.xml file instead of downloading and replacing dataverse-idp-metadata.xml file.

**Comment by pdurbin** [comment]
@knikolla and company at @CCI-MOC ran into this bug in our documentation today. It would be nice to fix it. It's a confusing error and gives the impression that the Shibboleth feature for Dataverse doesn't "just work".

**Comment by pdurbin** [comment]
I don't think many people are affected by this issue and if they are we haven't heard from them. Closing! 😄

**Comment by pdurbin** [comment]
The TestShib IdP is no longer available. See https://github.com/IQSS/dataverse/issues/5369#issuecomment-445906804
