### ISSUE TITLE
create a zip file on the fly using the new "directorylabel" field added in pull request #3412

### ISSUE THREAD

**Issue by bjonnh** [IQSS/dataverse#3448]
This will depend on whether or not #3412 will be implemented.

That would allow the user to download the hierarchy in a zip file.

I also wonder if this would be possible using rsync.

This was called "Download as zip while preserving directory structure" in 3.6

**Comment by pdurbin** [comment]
Pull request #3412 was merged so this could, in theory, be implemented, but on upload of a zip we'd need to persist the directory structure. We don't do this right now.

This is feature we had in DVN 3.x. See "Download as zip while preserving directory structure" at "3.6 & 4.0 Feature Comparison" at https://docs.google.com/spreadsheets/d/1ftHM6E4b9Dft_AvA6KTzeklJyLguItz2_0hNAFL8-VM/edit?usp=sharing

**Comment by pdurbin** [comment]
@bjonnh does #5498 capture what you want?

**Comment by bjonnh** [comment]
Yes!

**Comment by pdurbin** [comment]
@bjonnh great! #5498 is now in our next sprint so are you ok with closing this issue as a duplicate?
