### ISSUE TITLE
Time Limit for User Access of Dataverse or Dataset

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#345]
---

Author Name: **Elizabeth Quigley** (@eaquigley)
Original Redmine Issue: 3760, https://redmine.hmdc.harvard.edu/issues/3760
Original Date: 2014-03-25
Original Assignee: Michael Bar-Sinai

---

Ability to grant a user only a certain amount of time, i.e.-one week, two weeks, for accessing a restricted Dataverse or dataset.

**Comment by kcondon** [comment]
Unless we have a specific request comes in, we're closing this.
