### ISSUE TITLE
Deaccession: Cannot delete a draft if deaccession all published versions, edit button not rendered.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3451]
Reported by a user via Sonia:

If deaccession all (published) versions of a dataset when there is a draft, the draft can no longer be deleted through the UI since the edit button is no longer rendered. User can access the draft version and can publish, then deaccession that version. It happens even outside of any review workflow.

This appears to be an issue with rendering the edit button only since you can delete the draft version through the API.

**Comment by sekmiller** [comment]
OK. I am seeing this bug in my current branch. Let me see if there is an obvious fix.

**Comment by sekmiller** [comment]
Fixed in the Provenance Branch

**Comment by pdurbin** [comment]
Is this a duplicate of #1267 and #1308?

**Comment by pdurbin** [comment]
Provenance is 4.6 so I guess I'll add that milestone so we can find this issue again.

**Comment by kcondon** [comment]
No, definitely not a duplicate. A very specific behavior that otherwise would be overlooked (again)

________________________________

**Comment by djbrooke** [comment]
Talked over this in standup today. I'll check in with @sekmiller on Monday.

**Comment by pdurbin** [comment]
@sekmiller and I just spoke about how b5b5f31 is a fix for this issue so he said this issue should go to QA. I associated it with pull request #3408.

**Comment by sekmiller** [comment]
Actually per Kevin's request made a separate branch while we're dealing with ingest (etc.) issues.

**Comment by kcondon** [comment]
Tested, works, closing.
