### ISSUE TITLE
TwoRavensTabularView setting missing from r-rapache-tworavens

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#3452]
Creating an issue to gen a pull request to add it to the instructions for anyone installing TwoRavens not using Dataverse's install.pl

**Comment by pdurbin** [comment]
@donsizemore thanks for opening this. It should help with questions like this one from @shivadcedtu - https://github.com/IQSS/dataverse/issues/2961#issuecomment-258414466

Thanks also for the pull request at #3453 ! I'm moving this to Code Review at https://waffle.io/IQSS/dataverse
