### ISSUE TITLE
Provenance for Ingested Files

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#3455]
When we ingest a file, we're doing a transformation. We should store draft provenance on Dataverse.

On publish, we should be able to send this draft provenance data to the Provenance System.

**Comment by mheppler** [comment]
The mockups are being finalized, and can be reviewed in [Balsamiq](https://iqssharvard.mybalsamiq.com/projects/filesprovenancefacetsfilter-dataverse40/File%20-%20Provenance%20-%20Details).

![screen shot 2016-11-14 at 2 41 10 pm](https://cloud.githubusercontent.com/assets/687227/20279923/75fe5bb6-aa78-11e6-860a-e04390fc45c1.png)

**Comment by djbrooke** [comment]
Replaced by #4344.
