### ISSUE TITLE
Provenance Integration for Datasets

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#3456]
At the dataset level, we'll need a few things in order to populate the Provenance system with relevant information from Dataverse so that provenance graphs can be displayed (#3245). 

At the dataset level we need to:

- Allow a User to upload a provenance file explaining the transormation OR
- Allow a User to add text explaining the transformation
- Validate the JSON using the Provenance System Validation API
- Call “prov.setversiontransformation” when free text is added
- Call “prov.(TBD)versiontransformation” when a file is added

**Comment by mheppler** [comment]
The mockups are being finalized, and can be reviewed in [Balsamiq](https://iqssharvard.mybalsamiq.com/projects/filesprovenancefacetsfilter-dataverse40/Dataset%20-%20Edit%20Provenance).

![screen shot 2016-11-14 at 2 25 49 pm](https://cloud.githubusercontent.com/assets/687227/20279352/47695d66-aa76-11e6-8451-b67a7ac4d1f6.png)

**Comment by djbrooke** [comment]
Hey @jacksonokuhn - can you update this issue with any relevant thoughts based on the discussion during the Prov meeting this morning?

**Comment by mheppler** [comment]
Test JSON files from @jacksonokuhn 

https://github.com/tfjmp/provR/tree/master/tests

**Comment by djbrooke** [comment]
Closing, as dataset Provenance will not be included in the initial integration
