### ISSUE TITLE
Publish Dataset: Cannot publish dataset through if fqdn is not defined.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3461]
We document this in the troubleshooting guide but seems like it should work without being defined, ie default to local host name as in the past.
http://guides.dataverse.org/en/4.5.1/installation/installation-main.html#dataset-cannot-be-published

**Comment by pdurbin** [comment]
For more context, please see https://groups.google.com/d/msg/dataverse-community/sgF0EKqpvwc/PcAsxFPDBQAJ
