### ISSUE TITLE
Document extra timer configuration in a multiple node installation

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#3467]
We've discovered that our default configuration results in an access conflict to the timer table in the database, in a multi-server installation. 
The fix is simple - only the dedicated timer node needs the datasource attribute in the timer section, pointing to the main database: 
<ejb-timer-service timer-datasource="jdbc/VDCNetDS">
On the non-master, consecutive nodes, the default 
<ejb-timer-service>
should be left in place. 
This needs to be documented, in the same section where we explain how to set/unset the configuration flag that designates the timer server node.

**Comment by djbrooke** [comment]
@landreev - thanks for creating this issue. Is this something you're working on right now?

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
