### ISSUE TITLE
FileRecordJobIT should be executable remotely from a Jenkins server to a test server

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#3468]
This is a follow up to https://github.com/IQSS/dataverse/commit/74f58c409b333dafc32c58aa185df6498c01f5e5#commitcomment-19812600

We need to be able execute REST Assured tests over the wire from the Jenkins server to a test server. As of this writing it is impossible to add `FileRecordJobIT` to the list of tests that we execute from build.hmdc.harvard.edu against http://phoenix.dataverse.org

That is to say, this is known to fail: `mvn test -Dtest=FileRecordJobIT -Ddataverse.test.baseurl='http://phoenix.dataverse.org'`

Here's how https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-apitest-develop/configure looks as of this writing:

![screen shot 2016-11-14 at 10 39 10 am](https://cloud.githubusercontent.com/assets/21006/20270950/130f477a-aa57-11e6-9cf7-5b1581cb2737.png)

**Comment by bmckinney** [comment]
The new requirement for this scenario: the ability to generate and move test files on remote test servers to the Dataverse data directory. These fundamental goal of all of these tests is to exercise file system import with actual test files.

**Comment by pdurbin** [comment]
@bmckinney what if we add an "admin" API endpoint that generates some test data in `/tmp`? We'd call this `generateTestData` API endpoint from the `@BeforeClass` method. I'm just spit-balling, of course. I just don't want to rely on developers to remember to run FileRecordJobIT on their laptops. I want the Jenkins server to run it against the phoenix server every time we kick off a build from the "develop" branch.

**Comment by bmckinney** [comment]
@pdurbin great idea, give it a shot

**Comment by pdurbin** [comment]
Meh, I can live without this. For the future, http://guides.dataverse.org/en/4.7/developers/testing.html#the-phoenix-server explains how tests run across the wire.
