### ISSUE TITLE
View Downloads: View downloads page does not properly exclude access.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3470]
Although the manage downloads page is limited by permissions, the actual view downloads page does not properly exclude access. See RT 243555 for an example.

**Comment by mheppler** [comment]
This appears to have been fixed in 4.8 as part of #3609. See [comment in that issue](https://github.com/IQSS/dataverse/issues/3609#issuecomment-322257731) from @landreev.
> checked in the fix for unauthorized users

**Comment by mheppler** [comment]
Example of [Guestbook Responses pg on dataverse-internal (4.8.5)](https://dataverse-internal.iq.harvard.edu/guestbook-responses.xhtml?dataverseId=1857&guestbookId=12) which now requires log in.
