### ISSUE TITLE
Download filename encoding problem

### ISSUE THREAD

**Issue by wingfranky** [IQSS/dataverse#3473]
Hi, I am programmer of project which based on Dataverse source code in Asia's institution. There is a bug in download filename. The filename is not same as the displayed one on the web page because of encoding problem. There is inconsistency between database encoding and the output file name encoding. The PostgreSQL database is UTF-8 encoded, but the filename corrupted in download.

We are using Dataverse 4.2.2, but we could find this bug also happen in the current Harvard University's Dataverse (need to pull down to download file with Chinese filename). Thus we believe that the bug is not yet fixed in the latest version of dataverse:
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/GDYFAG 
<img width="638" alt="capture" src="https://cloud.githubusercontent.com/assets/5762362/20378628/46f44edc-acd2-11e6-8fd1-7c685d94297c.PNG">

I have solved this problem by replacing these lines in one single file:

In /src/main/java/edu/harvard/iq/dataverse/api/DownloadInstanceWriter.java line 194:

`import java.net.URLEncoder;`

`//httpHeaders.add("Content-disposition", "attachment; filename=\"" + fileName + "\"");                   
                    //httpHeaders.add("Content-Type", mimeType + "; name=\"" + fileName + "\"");`
                   
 `String encodedFileName = URLEncoder.encode(fileName, "UTF-8");                    
                    httpHeaders.add("Content-disposition", "attachment; filename*=UTF-8''" + encodedFileName );         
                    httpHeaders.add("Content-Type", mimeType + ";charset=UTF-8");`

<img width="171" alt="capture3" src="https://cloud.githubusercontent.com/assets/5762362/20378811/631fb9c4-acd3-11e6-97ad-dc34dcbf4873.PNG">

<img width="572" alt="capture2" src="https://cloud.githubusercontent.com/assets/5762362/20378776/35832532-acd3-11e6-8dba-364f41f08e4b.PNG">

Hope this could help to make Dataverse better.

**Comment by pdurbin** [comment]
@wingfranky thanks for the detailed bug report! @landreev and I reproduced the bug quite easily and he'd like to take a closer look and asked me to assign this issue to him.

**Comment by pdurbin** [comment]
@wingfranky can you still reproduce this? I just tried at https://dataverse.harvard.edu/file.xhtml?persistentId=doi:10.7910/DVN/GDYFAG/MBJOWJ&version=1.1 (screenshot below) and I don't see an encoding problem.

<img width="987" alt="Screen Shot 2022-10-08 at 4 51 52 PM" src="https://user-images.githubusercontent.com/21006/194727459-00f85286-5329-4fdc-bee4-90fddd3d7464.png">
