### ISSUE TITLE
Dataverse API: Update bounding box

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3476]
Send a lat/lng bounding box information from WorldMap to GeoConnect and back to Dataverse, updating the new GIS metadata block.

---

### Notes:
  - This is a dataverse codebase change
  - Originally issue: iqss/geoconnect#32

**Comment by pdurbin** [comment]
@raprasad is this still something you want? I'm confused why the normal "update metadata" APIs can't be used to update the bounding box.

**Comment by raprasad** [comment]
@pdurbin Please close. I believe Geoconnect dev. stopped 5+ years ago)
