### ISSUE TITLE
Save/Display mapping errors in Dataverse metadata

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3479]
Mapping tabular data may be partially successful.
  - e.g. Not all rows get mapped

These error messages need to be:
  - Saved in Dataverse
  - Displayed to the user
     - Depending on the error, _consider_ allowing user to download data
       - e.g. rows that didn't map, ids of rows that didn't map, etc.Tabular mapping 

---

### Notes

- Mainly _Dataverse codebase_ change
- Originally part of geoconnect ticket IQSS/geoconnect#90

**Comment by raprasad** [comment]
Note: If unmatched "id" list is returned from WM:
- Look up those rows in the original tabular file
- Present/Save those rows to user

**Comment by djbrooke** [comment]
Closing Worldmap/Geoconnect issues as it's no longer supported after the recent Harvard Worldmap migration
