### ISSUE TITLE
Minor/Misc. WorldMap tweaks

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3481]
_To be done after Thanksgiving, when WorldMap code accessible_

- Details for each item listed as a separate comment

---

- [x] 1. Error message typo
- [x] 2. Lat/Lng error message, clearer language
- [x] 3. For unmatched rows, "pluralize" error message
- [x] 4. Join Target Django Admin, add search on 'name':
- [x] 5. TableJoin admin needs to be limited--similar to JoinTarget
   - If not it attempts to put many, may layers in one dropdown and the layer attributes in another dropdown--e.g. page takes too long to render or fails.
   - This dropdown info should not be "editable"

**Comment by raprasad** [comment]
- [ ] Error message typo
![mozilla_firefox](https://cloud.githubusercontent.com/assets/1036060/20403363/aebe598a-acce-11e6-9a09-4375c199e792.png)

**Comment by raprasad** [comment]
- Lat/Lng error message, clearer language

![geoconnect__map_data](https://cloud.githubusercontent.com/assets/1036060/20435875/c5f49152-ad7b-11e6-8bf4-7977e67bf983.png)

**Comment by raprasad** [comment]
Join Target Django Admin, add search on 'name':

![mozilla_firefox](https://cloud.githubusercontent.com/assets/1036060/20538430/35b4705c-b0bf-11e6-9969-c334033b347a.png)

**Comment by raprasad** [comment]
5. TableJoin admin needs to be limited--similar to JoinTarget

![mozilla_firefox](https://cloud.githubusercontent.com/assets/1036060/20818497/f5d6ab1e-b7fb-11e6-879c-94ec7a0a784c.png)

**Comment by raprasad** [comment]
- requires local WorldMap install

**Comment by pdurbin** [comment]
I'm looking around the WorldMap code for the places to fix:

## 1. typo

- https://github.com/cga-harvard/cga-worldmap/blob/855ce0e0d0d8ef059907168ce16a9c8cfd75e86c/geonode/contrib/datatables/column_checker.py#L176
- https://github.com/cga-harvard/cga-worldmap/blob/855ce0e0d0d8ef059907168ce16a9c8cfd75e86c/geonode/contrib/datatables/column_checker.py#L252

**Comment by pdurbin** [comment]
@raprasad for item 3 I went ahead and pushed a commit to a new branch in Geoconnect ( https://github.com/IQSS/geoconnect/commit/9de10d699c5892387a3c13f04f6930635064e7e7 ) but for the other items I made guesses above of where in the WorldMap code the changes need to happen. I guess I'm blocked on installing WorldMap for the other four items.

**Comment by pdurbin** [comment]
@raprasad and I just discussed this issue. For 4 of 5 items, we're blocked on getting WorldMap installed and plan to work on the Vagrant environment at https://github.com/IQSS/worldmap-legacy-dev

We agreed to go ahead and make a pull request for the one item that's in the Geoconnect code base, the "pluralize" thing: https://github.com/IQSS/geoconnect/pull/128

**Comment by pdurbin** [comment]
I'm blocked on this issue because I can't get WorldMap installed so I'm unassigning myself. The error I'm seeing is at the `paver build` step: https://github.com/IQSS/worldmap-legacy-dev/commit/fc8136865a5989a412fd1ab9fcdcd8f6af561cf7#commitcomment-21735918

**Comment by raprasad** [comment]
This ticket has code changes in 2 repositories:
- geoconnect
- worldmap

For the WorldMap changes, the PR is here:  https://github.com/cga-harvard/cga-worldmap/pull/229

**Comment by pdurbin** [comment]
The geoconnect pull request is here: https://github.com/IQSS/geoconnect/pull/128 . I made that pull request so I'll recuse myself from code review.

I looked at https://github.com/cga-harvard/cga-worldmap/pull/229 and it more or less makes sense to me.

I'll touch base with @raprasad before moving this to QA.

**Comment by raprasad** [comment]
Pluralize fix looks good for geoconnect

**Comment by raprasad** [comment]
@kcondon : please ping me when ready to test.

**Comment by kcondon** [comment]
4 out of 5 work, first error message saying of type a character, a numeric still typo. Will be fixed outside of this ticket.

**Comment by raprasad** [comment]
Geoconnect update has been moved live
