### ISSUE TITLE
Tabular: Need simple convert numeric to string

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3485]
Scenario:  

- tabular file column is numeric
- join target column is string *without* leading zeros
- add a new column to tabular, where numeric converted to string

Note: This logic is similar to "zero-padding" where numeric columns are converted to char with zero padding

pseudo:
```python
If target_column.attribute.type.endswith(':string') and selected_column.is_numeric():
    selected_column.convert_to_string()
```

example data:
```json
 {
      "layer": "geonode:census_tracts_2010_boston_6f6", 
      "name": "Census Tracts, Boston (GEOID10: State+County+Tract)", 
      "geocode_type_slug": "us-census-tract", 
      "geocode_type": "US Census Tract", 
      "attribute": {
        "attribute": "CT_ID_10", 
        "type": "xsd:string"
      }, 
      "abstract": "As of the 2010 census, Boston, MA contains 7,288 city blocks, defined as any piece of land bounded by streets or water on all sides, and not divided by any streets or water. These are nested in 558 block groups, ......(etc, etc)", 
      "title": "Census Tracts 2010, Boston (BARI)", 
      "expected_format": {
        "expected_zero_padded_length": -1, 
        "is_zero_padded": false, 
        "description": "Concatenation of state, county and tract for 2010 Census Tracts.  Reference: https://www.census.gov/geo/maps-data/data/tract_rel_layout.html", 
        "name": "2010 Census GEOID10 (State+County+Tract)"
      }, 
      "year": 2010, 
      "id": 28
    },

**Comment by raprasad** [comment]
- [x] working with census tract.
- [ ] block groups test 
- [ ] block test

**Comment by raprasad** [comment]
ready to test

**Comment by pdurbin** [comment]
@raprasad can you please provide a link to the code you'd like me to look at? Is it https://github.com/IQSS/geoconnect/commit/9f5d2e9aea44896e327a95c8723808df2a02aa8a ?

**Comment by raprasad** [comment]
to do post @pdurbin code review:
- [ ] add to tabular doc re: types of join cases and formatting
- [ ] add test for this feature using target info JSON

**Comment by raprasad** [comment]
doc added giving formatting cases.  This ticket is case 1 on the table: https://github.com/IQSS/geoconnect/wiki/Geoconnect-Column-Formatting

**Comment by raprasad** [comment]
@djbrooke - The documentation and test for this ticket are now done.

**Comment by raprasad** [comment]
See: https://github.com/IQSS/geoconnect/pull/116

**Comment by raprasad** [comment]
Closing. Thanks @pdurbin  for code review and "mini" QA. 
Full QA will happen with #3531

**Comment by pdurbin** [comment]
@raprasad sure. I was glad to see the newly added tests execute. It would be nice to see Geoconnect tests execute on every commit via Travis or similar, like we have with Dataverse. Thanks for adding a todo for this at #3024.
