### ISSUE TITLE
Improve consistency of various remote auth options (Shibboleth vs. OAuth)

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#3486]
When the [Shibboleth Functional Requirements Document for Dataverse 4.0](https://docs.google.com/document/d/12Qru8Gjq4oDUiodI00oObHJog65S7QzFfFZuPU3n8aU/edit?usp=sharing) document was written and the Shibboleth code was polished enough to be considered non-experimental in #2939 we had a certain idea of how we expected remote auth to work. Now that we've gotten our hands dirty with OAuth login by way of ORCID, Google, and GitHub in #3338 we'd like to revisit some of the decisions we made about Shibboleth and bring more consistency to the various remote auth options.

TODO:

- Finish listing inconsistencies below.
- List Shibboleth design decisions we'd like to revisit. See "phase 2" of the [Remote Authentication BRD](https://docs.google.com/document/d/1vcAmo2nkFYavAr7OwwXzxM0IFQbkRZYZrrX43q-wqGE/edit?usp=sharing) and [2015-04-30 Dataverse User Accounts and Auth Meeting](https://docs.google.com/document/d/157sw9gaFGwrb0EtCGGlLMxSg0cooHfKEvIsjcebPcA8/edit?usp=sharing)
- Link to additional material from "background" section of [2016-10-25 ORCID/OAuth2 -- UI/UX Meeting](https://docs.google.com/document/d/1nq1WO2fgnnjTX7gR78mxvEI12pVWy4G4Rx1NYorTNNo/edit?usp=sharing)
- Do refactoring explained in "Refactor xhtml for Login/Auth/Account" spreadsheet at https://docs.google.com/spreadsheets/d/1AM8IC6P43KURNNgAlYX5BvO4qOVze-vYMYFqaDmtHTI/edit?usp=sharing 

Inconsistencies:

- No cancel button on Github/Google/Oauth create account/add info page, there is on Shib and local log in.

**Comment by mheppler** [comment]
@scolapasta, @pdurbin Found an old vague issue, **Clean up user code (review specific methods for shib and built in user on AuthenticatedUser) #1456**, that maybe we can close and use this new issue to track instead.

**Comment by mheppler** [comment]
Closed **Clean up user code (review specific methods for shib and built in user on AuthenticatedUser) #1456** in favor of this issue, that will allow us to consolidate and optimize consistency for user account code.

**Comment by pdurbin** [comment]
I don't see a ton of value in having this issue open until we decide to start working on it. Closing.
