### ISSUE TITLE
Permit multiple login options to the same Dataverse account

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#3487]
The original design doc at https://github.com/IQSS/dataverse/blob/4.0/doc/Architecture/auth.md was for "allow multiple logins to map to the same internal system user" but at the "merge party" in late September 2014 we decided to do away with this concept in fe8e41a. We'd like to at least explore the possibility of reintroducing the idea of permitting multiple login options to the same Dataverse account. The idea is that you could log in with HarvardKey (Shibboleth) or ORCID or a local account and still be "you" in Dataverse.

**Comment by pdurbin** [comment]
I think we want this, but when? Closing until we decide to prioritize it.

**Comment by pdurbin** [comment]
I'm re-opening this because as I mentioned at https://github.com/IQSS/dataverse/issues/6701#issuecomment-591986929 the dream is alive!

Yesterday, I saw this when testing OpenID Connect (OIDC), a next generation repository technology contributed by @poikilotherm in pull request #6433 for Dataverse 4.19: https://ngr.coar-repositories.org/technology/openid-connect/

<img width="977" alt="75450242-6ffd4300-593c-11ea-9020-a6076e65a690" src="https://user-images.githubusercontent.com/21006/75538531-bb6c2b80-59e6-11ea-87c6-572c90f1b66d.png">

That is to say, in theory, I should be able to log into https://data-beta.fz-juelich.de with any of HarvardKey, ORCID, and GitHub and still be "me" in Dataverse.

This is incredibly exciting! If it works, it has the potential to solve many headaches:

- 4.6.1 Account creation confirmation email #3704 
- Convert User: Cannot convert user from remote to local if preserving email address #3834 
- Having some trouble when a user tries logging in using both Shib AND OAuth...I think... #4769
- ...

But does it work? Someone should test it. 😄

**Comment by poikilotherm** [comment]
I tested this with our installation of [Unity IDM](https://unity-idm.eu), maintained by @apw1388

First let's associate my ORCID account with my company account in the IDM:

![add-account-1](https://user-images.githubusercontent.com/5468333/75544717-d8bfea80-5a24-11ea-9e72-f0d16e8b9a06.png)
![add-account-2](https://user-images.githubusercontent.com/5468333/75544280-ed4fb300-5a23-11ea-8ceb-328ea52aafb5.png)
![add-account-3](https://user-images.githubusercontent.com/5468333/75544281-ed4fb300-5a23-11ea-8229-e34459f55a8b.png)
![add-account-4](https://user-images.githubusercontent.com/5468333/75544282-ede84980-5a23-11ea-9db0-4ccecb750aa6.png)
![add-account-5](https://user-images.githubusercontent.com/5468333/75544285-ede84980-5a23-11ea-920b-5b9b37a12565.png)
![add-account-6](https://user-images.githubusercontent.com/5468333/75544288-ede84980-5a23-11ea-8c18-ab8d5f46e625.png)
![add-account-7](https://user-images.githubusercontent.com/5468333/75544289-ee80e000-5a23-11ea-9bb0-c1e98a1eff8b.png)

Then login to Jülich DATA BETA with ORCID and still have the same user account:

![multiway-login-1](https://user-images.githubusercontent.com/5468333/75544600-9eeee400-5a24-11ea-908e-388b2db1ca50.png)
![multiway-login-2](https://user-images.githubusercontent.com/5468333/75544604-9f877a80-5a24-11ea-9a8f-d28c4ba53155.png)
![multiway-login-3](https://user-images.githubusercontent.com/5468333/75544606-9f877a80-5a24-11ea-9443-8d70d8bd7d7a.png)
![multiway-login-4](https://user-images.githubusercontent.com/5468333/75544607-a0201100-5a24-11ea-8844-74cd58ab3589.png)
![multiway-login-5](https://user-images.githubusercontent.com/5468333/75544608-a0201100-5a24-11ea-9d6e-a8cb86726161.png)

**Comment by poikilotherm** [comment]
I'd vote to close this, as this is probably way easier to solve on the OIDC provider level.

**Comment by pdurbin** [comment]
I'm a little nervous that our docs are not at all clear on how to achieve this, though.

Maybe a line or two near a future version of https://guides.dataverse.org/en/6.3/installation/config.html#auth-modes-local-vs-remote-vs-both would help?

**Comment by pdurbin** [comment]
In the future, with the React SPA ( https://github.com/IQSS/dataverse-frontend ) we plan to solve this by having OIDC in the mix.

See the auth doc at https://groups.google.com/g/dataverse-community/c/2hfhWIHQddE/m/hATuWGGSAAAJ for details.

Closing.
