### ISSUE TITLE
File Landing Page: Add Edit Tags to the edit list button.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3488]
This was in the original mockups but missed in the functional outline in the ticket.
Add edit tags to the edit list button on the file landing page, similar to how the edit files list button on the dataset page has it.

**Comment by sekmiller** [comment]
Technical debt issue: editFilesTagsPopup currently resides both in dataset.xhtml (for multiple files update) and EditFilesFragment for single file updates. To do this right, we should make a separate fragment which can be included in both of those places plus the file page. Or possibly some other more clever arrangement.

**Comment by TaniaSchlatter** [comment]
Visual example:
<img width="1257" alt="Screen Shot 2019-05-01 at 11 59 31 AM" src="https://user-images.githubusercontent.com/15386424/57026811-b0027500-6c08-11e9-98ae-dfcf0d6eeea7.png">

**Comment by djbrooke** [comment]
- adding an edit tags popup to the file page (much like popups for restriction)
- existing functionality, easier way to get to it

**Comment by scolapasta** [comment]
closing until we determine design from #7376
