### ISSUE TITLE
Files tab: When tabular file upload results in "ingest in progress" message, explore button does not appear when complete until manual refresh.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3491]
This issue is a regression resulting from the file landing page merge.

When a tabular file is ingested, an explore button to access Two Ravens appears when completed. Sometimes it takes a while to complete, during which a message indicating "ingest in progress", after which the page automatically refreshes and the explore button appears.

Now, since adding the file landing page and reorganizing the button logic, the page is not automatically refreshed when the "ingest in progress" completes, requiring a manual refresh to see the explore button.

**Comment by mheppler** [comment]
The "manual refresh" problem is also associated with the "Upload Completed with Errors" hover popover, linked to the warning icon in the files table on the dataset pg.

![screen shot 2018-04-02 at 2 46 06 pm](https://user-images.githubusercontent.com/687227/38210257-de597792-3684-11e8-820e-0d8fab2defa6.png)

**Comment by kcondon** [comment]
Now works
