### ISSUE TITLE
Update mapping between Dataverse metadata and DataCite 4.0 metadata

### ISSUE THREAD

**Issue by edzale** [IQSS/dataverse#3492]
Hi All. Is there anywhere a documentation of the mappings between Dataverse and DataCite metadata elements? Specially the following metadata elements that are required by DataCite: Publisher, PublicationYear, resourceTypeGeneral , and descriptionType which is mandatory when we give a description.
Thank you in advance for your help.

**Comment by pdurbin** [comment]
@edzale I believe the "Dataverse 4.0 Metadata Crosswalk: DDI, DataCite, DC, DCTerms, VO, ISA-Tab" doc is what you're looking for: https://docs.google.com/spreadsheets/d/10Luzti7svVTVKTA-px27oq3RxCUM-QbiTkm8iMd5C54/edit?usp=sharing

In #3294 we plan to link to this doc from the appendix of the User Guide.

**Comment by edzale** [comment]
@pdurbin Thank you very much for the link. Indeed, this what I was looking for.

**Comment by bmckinney** [comment]
I don't believe that the crosswalk is comprehensive with regard to DataCite. I'm currently working on DataCite 4.0 support (via a new edu.harvard.iq.dataverse.export.Exporter) and may have more specific mapping information when I'm done.

**Comment by edzale** [comment]
@bmckinney Ok, thank you. I'm looking forward to your work.
In the spreadsheet pointed by @pdurbin, DataCite is missing in the Citation metadata tab. But I noticed that you've made some changes comapred to this spreadsheet https://docs.google.com/spreadsheets/d/13HP-jI_cwLDHBetn9UKTREPJ_F4iHdAvhjmlvmYdSSw/edit#gid=0 which is the one I had before. So, the citation metadata in the spreadsheet pointed by @pdurbin seems more aligned with DataCite if I'm not mistaken. Could you please just confirm me that the metadata in the the spreadsheet pointed by @pdurbin  are the one implemented in Dataverse 4.5.1? Thank you very much.

**Comment by bmckinney** [comment]
@edzale Sorry, I'm just as new to this as you are at the moment (started working on DataCite XML export 2 days ago). The bottom line is that the mapping is bare-bones right now. See the current template here: https://github.com/IQSS/dataverse/blob/develop/src/main/resources/edu/harvard/iq/dataverse/datacite_metadata_template.xml (just 7 mappings)

I'll keep you updated on this work and would welcome your feedback. What exactly is your current interest or need?

**Comment by jggautier** [comment]
Hi @edzale. In spreadsheet @pdurbin pointed to (https://docs.google.com/spreadsheets/d/10Luzti7svVTVKTA-px27oq3RxCUM-QbiTkm8iMd5C54/edit#gid=0), the Citations tab had its two columns with DataCite 3.1 mapping hidden. I've unhid them. They're columns G and H. Hope that's helpful.

**Comment by edzale** [comment]
Thank you @jggautier, it does help.

**Comment by pdurbin** [comment]
#2917 is related.
