### ISSUE TITLE
Worldmap: Add Boston Parcels Target Layer

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3493]
This is a left-over layer from #3477, where the world map upload wasn't working with the parcels file although it opens with QGIS.  Tried .zip as well as uploading separate files.

- [ ] Parcels 2015, Boston
    11/29 - hanging or error on upload

---

 - Data: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/LIPBJB
  - Docs: [Documentation for the 2015 Geographical Infrastructure](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/C5IULB)

**Comment by raprasad** [comment]
- e.g. Ask Ben toward end of week

**Comment by djbrooke** [comment]
@raprasad - I'm going to close this one based on the discussion in the backlog grooming today.
