### ISSUE TITLE
tabular mapping: Add map thumbnail on Dataset page

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3495]
If a tabular DataFile has an associated "MapLayerMetadata" object:
  1. Retrieve a thumbnail from WorldMap.
      - Already happens for shapefiles
      - Code is here: 
          - File/Method: ```MapLayerMetadataServiceBean.java``` ```retrieveMapImageForIcon```
  2. Display the thumbnail on the:
      1. Dataset page within the file listing
      1. File Page
      1. Dataverse search result card

  3. Under the thumbnail, display a "Preview link" which pops up a modal window showing the map

## Current

![darwin_s_finches_-_7801f23d_dataverse](https://cloud.githubusercontent.com/assets/1036060/20723363/35536f36-b638-11e6-857e-977ae2f8ce2c.png)

## Expected

![mapping_trial__test__-_harvard_dataverse](https://cloud.githubusercontent.com/assets/1036060/20723389/50c0a446-b638-11e6-9244-c03cbd360e26.png)

**Comment by djbrooke** [comment]
We discussed this in the sprint planning meeting yesterday, and the title and description of the issue was changed around a few times to capture the correct tasks here. These changes are in the Dataverse codebase.

**Comment by raprasad** [comment]
Events:

(1) Geoconnect adds WorldMap metadata via:
   - See File/Method: WorldMapRelatedData.java  /  ```updateWorldMapLayerData```
   - End of ```updateWorldMapLayerData```
    
       ```java
        // ------------------------------------------
        // Retrieve a PNG representation from WorldMap
        // ------------------------------------------
        try {
                logger.info("retrieveMapImageForIcon");
                this.mapLayerMetadataService.retrieveMapImageForIcon(savedMapLayerMetadata);
        } catch (IOException ex) {
                logger.severe("Failed to retrieve image from WorldMap server");
                Logger.getLogger(WorldMapRelatedData.class.getName()).log(Level.SEVERE, null, ex);
        }  
        
        return ok("map layer object saved!");
       ```
(2) At the end of the method above, Dataverse attempts to retrieve a PNG representation from WorldMap:

  -  See File/Method: MapLayerMetadataServiceBean.java ```retrieveMapImageForIcon```

**Comment by raprasad** [comment]
Timing issues occur where Geonode WMS server not always serving PNG right away.  e.g. 1-2 second delay.
- add "delay" into Geoconnect using @scolapasta's suggestion of checking for PNG (from Geoconnect) before sending info to DV.
- without a queuing mechanism, will be a separate scripted command
  - e.g. try twice: wait 2 sec, is PNG available. yes? send info to dv

**Comment by raprasad** [comment]
Timing fix is working on geoconnect branch: [3496-png-readiness](https://github.com/IQSS/geoconnect/tree/3496-png-readiness)
  - Updated local geoconnect to this branch should help for testing

**Comment by pdurbin** [comment]
@raprasad as we've been discussing, I just deleted 3496-png-readiness and the new branch is 3496-png.

**Comment by landreev** [comment]
working on the "large preview image"; will push in a fix shortly.

**Comment by raprasad** [comment]
Note: The geoconnect part of this code has been pushed to the heroku dev instance.
e.g. dvn-build points to this server

[server_relationships.pdf](https://github.com/IQSS/dataverse/files/894343/server_relationships.pdf)

**Comment by pdurbin** [comment]
PNG version so we can see it inline:

![server_relationships](https://cloud.githubusercontent.com/assets/21006/24676164/e0b7dfcc-194f-11e7-8ae5-9a7b792f05d7.png)

**Comment by landreev** [comment]
I have committed the fix for the preview. 
All it was, since the file is also a tabular file, the access API was adding the variable list header to the output - which of course was screwing up the image.

**Comment by landreev** [comment]
I have a more general comment: 
I'm seeing that in methods like DataFileServiceBean.thumbnailSupported(), the mime type for tabular files has just been added to the list: 

```
return (contentType != null && 
                (contentType.startsWith("image/") || 
                contentType.equalsIgnoreCase("application/pdf") ||
                contentType.equalsIgnoreCase("text/tab-separated-values") ||
                contentType.equalsIgnoreCase(MIME_TYPE_GEO_SHAPE)));
```

I don't really like this... we shouldn't be attempting this on *any* tabular file. So it should probably be a check if the file is tabular, AND if it has that "geospatial" tag.

**Comment by landreev** [comment]
(if what I just said, about the type check, makes sense to everybody - I can just go ahead and add that extra logic...)

**Comment by sekmiller** [comment]
Makes sense to me. Thanks.

**Comment by landreev** [comment]
OK, just pushed my change. 
It was trivial, since @raprasad already provided a convenience method for checking on the geospatial tag. 

@sekmiller @raprasad could you please give it a quick look, to make sure what I did hasn't broken anything else; it shouldn't have, but just in case. 

Otherwise should be ready to go into code review and qa.

**Comment by raprasad** [comment]
- possible issue, after the map is deleted, file page is attempting
to retrieve thumbnail. (dataset page reverts to default icon)

![election_precincts3_tab_-_root_dataverse](https://cloud.githubusercontent.com/assets/1036060/24715067/4ae0a1e2-19f8-11e7-8ac5-b81fa64b6ed1.png)

**Comment by sekmiller** [comment]
OK. I'll check it out.

**Comment by raprasad** [comment]
found geoconnect error which may have been added as part of this ticket
![map_data_file](https://cloud.githubusercontent.com/assets/1036060/24715357/0eaa817e-19f9-11e7-9389-0c7b151ff9c7.png)
:

**Comment by landreev** [comment]
@raprasad @sekmiller 

The part about the page still trying to access the "large preview", after the map layer is deleted:
I believe the solution is to setPreviewImageAvailable(false) on the datafile. (it appears that you are already deleting all the generated map images/thumbnails when this layer delete happens... otherwise the large thumbnail would still be showing up on the files page... So this boolean needs to be set there as well). 

Does this make sense?

**Comment by landreev** [comment]
@raprasad @sekmiller 
pushed in a fix for the null pointer

**Comment by pdurbin** [comment]
@sekmiller @landreev @raprasad just explained their changes in pull request #3756 to me and @mheppler . Looks good. moving to QA at https://waffle.io/IQSS/dataverse
