### ISSUE TITLE
TabularFileInfo model column_names attribute error

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3496]
This attribute is not being saved as JSON, instead it's a python list

Note: column_names attribute use is inconsistent in models between different file types, leading to error:
  - [x] shapefile (custom-made field)
    - [x] creation
  - [x] tabular file (```jsonfield.JSONField```)
     - [x] column names
     - [x] join layer
     - [x] lat/lng layer
 - [x] styling
     - [x] post styling.  search for ```#   Looks good, update the WorldMapLayerInfo's attribute info```
- [x] add test

**Comment by raprasad** [comment]
This has been hampered by #3502 -- e.g. basic functions not working on WM

**Comment by raprasad** [comment]
ready for next step in process....

**Comment by landreev** [comment]
Just to confirm, there's no pull request for this issue; neither in IQSS/dataverse, nor in IQSS/geoconnect. So I was assuming what needed to be reviewed was this commit: https://github.com/IQSS/geoconnect/commit/7bb91cf2f3b0898129268f97f793879bdcda3105

- that looks straightforward enough. I'm pushing this into QA, but if there was anything else I was supposed to look at, please let me know.

**Comment by raprasad** [comment]
Closing.  Thanks @sekmiller for code review and "mini" QA.  Full QA will happen with #3531
