### ISSUE TITLE
Visualizing FITS files the Files Landing Page and World Wide Telescope

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3499]
Relevant info from email summarizing 8/2015 meeting with @scolapasta and Gus.  All estimates would need to be redone, etc.

### (1) Converting FITS to PNG/JPG with embedded metadata

- **Time**: Unknown (1-3+ weeks?), needs to be spec’d out with Leonid and included in ingest.  

- **Scope**: Experiment with various FITS->PNG/JPG conversion libraries as well as metadata libraries.  Main work is adding it to the ingest process

- **Note**: This part also provides preview images for the dataset and file pages

## (2) Sending PNG representation to the WWT (World Wide Telescope) website

- **Time:** 1-2 days

- **Scope**: Send a url to a PNG/JPEG representation of a FITS to WWT 

## Key Points about Converting FITS to PNG/JPG:

Gus spent considerable time explaining the conversion of FITS->PNG/JPG, 

  - From Gus: __There is no one-size-fits-all conversion library and it will take some experimentation: **not all libraries will convert all FITS files**__
    - e.g. One tool may work fine with FITS files from the Hubble telescope, but give poor conversions for images from other sources. 
  - He gave us a starting list of potential libraries to use.
     - The libraries Gus pointed out for our test list are in a variety of languages including python, perl, java, command line tools, etc.
     - Our ingest process will likely need to shell out / glue together non Java libraries, how to handle 2D vs. 3D images, and other issues not mentioned here.

Gus pointed out that one benefit about the FITS conversion to PNG/JPG with embedded AVM metadata is that those files will be usable by other systems, not just WWT.

**Comment by pdurbin** [comment]
I don't believe we are working on this. Closing.
