### ISSUE TITLE
Multi Selects for Fields

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#350]
---

Author Name: **Elizabeth Quigley** (@eaquigley)
Original Redmine Issue: 3765, https://redmine.hmdc.harvard.edu/issues/3765
Original Date: 2014-03-25
Original Assignee: Gustavo Durand

---

Try using Multiple Select under Selected and Disabled Support for all multi select fields, which would also allow for auto-populate / auto-complete for any matching terms within the list: http://harvesthq.github.io/chosen/#selected-and-disabled-support

Metadata fields that should use this component:
-Subjects
-Type (Astro Metadata block)
-Language
-Country (Geospatial Metadata block)
All Biomedical terms will be multi-select:
-Design Type
-Factor Type
-Measurement Type
-Organism
-*Cell Type (coming soon... waiting to decide on hierarchical dropdown terms list and/or "type ahead" field for a large list like this one.)

**Comment by scolapasta** [comment]
Let's re review this when we get near the end.

**Comment by eaquigley** [comment]
Bringing this ticket back up. @scolapasta could we use the component used for searching through usernames for role assignments for this?

**Comment by scolapasta** [comment]
@eaquigley can we close this one?

**Comment by eaquigley** [comment]
@scolapasta no, this was never done for multi select fields. I can see this being needed even more with biomedical data. @posixeleni

**Comment by djbrooke** [comment]
@eaquigley gave me an overview of the importance of this, especially in those metadata schemas that have many options. Removing myself for now, will be added in a future release.

**Comment by djbrooke** [comment]
Closing in favor of #6030 to evaluate as part of a larger effort.
