### ISSUE TITLE
Update tooltip for "Unit of Analysis" in Social Science and Humanities Metadata block

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#3500]
The tooltip for Unit of Analysis in the Social Science and Humanities Metadata block points users to an outdated URL.

![screen shot 2016-12-01 at 5 20 07 pm](https://cloud.githubusercontent.com/assets/18374574/20816275/82314aea-b7ef-11e6-9885-6dddbd2080b7.png)

It should be http://www.ddialliance.org/controlled-vocabularies. Looks like that involves editing the socialscience.tsv file.

**Comment by jggautier** [comment]
Linking related issue: #3501

**Comment by djbrooke** [comment]
Hey @jggautier - good finds. Do you want to work together tomorrow to get these fixed up? Your first PR(s)!! 👍

**Comment by jggautier** [comment]
Thanks. Tomorrow sounds good!

**Comment by pdurbin** [comment]
@mheppler and Tania and I discussed this bug this morning. One thought was to remove the URL entirely. At some point a tool tip stops being a tool tip and becomes a wall of text. 😄

**Comment by djbrooke** [comment]
Thanks @pdurbin - I've corrected the tool tip for now, but if we want to re-evaluate as a larger effort around help text/options we should capture it as another ticket.

**Comment by djbrooke** [comment]
The URL has been updated, so closing this issue. Mentioned to @jggautier that the tool tip width does not allow full display of the URL, but that should be handled in a separate issue.

**Comment by pdurbin** [comment]
@djbrooke @jggautier did you include a SQL upgrade script?

**Comment by pdurbin** [comment]
@djbrooke I spoked with @kcondon about this after standup and he will be adding the step @scolapasta mentioned to the release notes.

**Comment by kcondon** [comment]
Yes  I mentioned to Phil I was adding it.
