### ISSUE TITLE
On the "create dataset" page, prepopulate author identifiers such as ORCID, ISNI, and LCNA

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#3507]
When you click "Add Dataset" you get a form to create a dataset your **name** and affiliation (if available) are prepopulate as the first Author but the "Identifier Scheme" is not. After we store ORCID iDs per user in #923 (and perhaps author's ISNI or LCNA identifiers), we should similarly prepopulate this field. Right now users have to type it in manually:

![screen shot 2016-12-05 at 3 49 37 pm](https://cloud.githubusercontent.com/assets/21006/20901916/ca40ea6e-bb02-11e6-8bcf-07c01be36111.png)

**Comment by mheppler** [comment]
Duplicate of #923.

**Comment by pameyer** [comment]
@mheppler - #923 is a superset of this issue (that one covers obtaining identifiers by whatever means; this assumes that they're present already).

**Comment by pdurbin** [comment]
For ORCID IDs specifically, we recently added #3944 to the current sprint.

**Comment by pdurbin** [comment]
We can work on the others in new issues in future sprints. Closing.
