### ISSUE TITLE
Metrics update for 4.6 launch

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3508]
The Metrics app will need updating to reflect the Dataverse schema changes in 4.6.

Specifically, the checksum changes for the DataFile object need to be reflected in the metrics app as well as other changes in the file:

```dataverse/scripts/database/upgrades/upgrade_v4.5.1_to_v4.6.sql```

Note: So far, checksum changes will break some of the Metrics models but other column additions will simply be ignored.

**Comment by raprasad** [comment]
checksum update is here:
https://github.com/IQSS/miniverse/commit/3ae9b1be9d7ff0d923c127cf592a83cb5ea649be

**Comment by raprasad** [comment]
ready for code review

**Comment by djbrooke** [comment]
Moving to code review column

**Comment by raprasad** [comment]
Updated test fixtures: https://github.com/IQSS/miniverse/commit/8a6efcb83bd49e39ea34fd7fca193f580aaaa275
