### ISSUE TITLE
Sensitive Data: Request to supported selected sensitive dataset metadata.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3510]
See RT 244340. A partner wondered whether a group of researchers working with sensitive metadata could create datasets with sensitive metadata, having to do with locations, publish the datasets but "hide" or control access to the sensitive parts.

Currently, our proposed sensitive data support assumes public, non-sensitive metadata.

**Comment by pdurbin** [comment]
This sounds similar to #902.
