### ISSUE TITLE
update "return_to_dataverse_url" to use File landing page

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3511]
**Summary**:  Geoconnect's "Return to Dataverse" button should go to dataset page or file page depending on the source.

### Workflow
  -  User clicks "Map Data" and goes to Geoconnect
  -  Within Geoconnect, the User will click either the "Cancel" button or "Return to Dataverse" button
  - Currently both options return the user to the Dataset landing page containing the file being mapped
  - With the advent of the file page, the "Return to Dataverse" link should go back to where the user came from--either the file page or dataset page.

### Work
  - Send additional "dataverse_session_url" attribute to Geoconnect containing appropriate page to bring user
  - Methods to look at for sending this info
    - ```mapDataFileTokenOnlyOption```
    - ```getWorldMapDatafileInfo```

## Item 2: Decision
  - WorldMap contains  a Dataverse source url which is currently the Dataset page
  - Should this change to the File page?
  - What to change.  Update this line in WorldMapRelatedData.java:
```java
jsonData.add("return_to_dataverse_url", dset_version.getReturnToDatasetURL(serverName, dset));
```
      
- [x] Return to Dataverse link 
  - If map exists, always re-send metadata to Dataverse

---

### Link stored for WorldMap users

When mapping files, WorldMap stores a link back to the **Dataset** of that file.

With the new file page, the link can now go directly to the file page--by updating this line in ```WorldMapRelatedData.java```:

```java
jsonData.add("return_to_dataverse_url", dset_version.getReturnToDatasetURL(serverName, dset));
```
### Link stored for Dataverse session

1.3.2017 - With the addition of the file page, a user may now map "from" a Dataset page or File page -- the source page must be passed to Geoconnect for a "clean return" back to dataverse

**Comment by djbrooke** [comment]
We discussed this in the sprint planning meeting yesterday, and the title and description of the issue was changed around a few times to capture the correct tasks here. These changes are in the Dataverse codebase.

**Comment by sekmiller** [comment]
Geoconnect return to dataverse will now send the user back to the file landing page. (Additional coding would have been needed to refer the user back to the referring page (either dataset page or file landing page.) I put a comment alongside the method for retrieving the file page url (DatasetVersion: getReturnToFilePageURL (String serverName, Dataset dset, DataFile dataFile)  to describe the additional work required.)

**Comment by pdurbin** [comment]
I did some code review of pull request #3720 (looks good) and I'm moving this issue to QA in https://waffle.io/IQSS/dataverse

**Comment by kcondon** [comment]
Saw some errors pressing the explore button when testing return link. Raman describes it this way:
(2) There seems to be a *new bug on the dataset page*  where *both explore buttons*  go to the same map:
https://dataverse-internal.iq.harvard.edu/dataset.xhtml?persistentId=doi:10.5072/FK2/JLVYA3&version=2.0
(2a) For the files in the dataset above, the *explore buttons work correctly from the "File" pages--but not the dataset page*
