### ISSUE TITLE
No Option to download all file formats.

### ISSUE THREAD

**Issue by shlake** [IQSS/dataverse#3513]
According to the user guide and the image displayed, a tabular file can be downloaded in "All formats". The image in the user guide shows this option, and is described in the text, but I do not see that option in production.

![screen shot 2016-12-07 at 4 32 51 pm](https://cloud.githubusercontent.com/assets/3809325/20987555/220c6d42-bc9b-11e6-8701-89d8f66ff9d0.png)

I am looking at a tabular file on Harvard 4.5.1. Is this downloading all formats only for certain tabular files?
From this dataset: http://dx.doi.org/10.7910/DVN/29604

![screen shot 2016-12-07 at 4 35 50 pm](https://cloud.githubusercontent.com/assets/3809325/20987658/85f6dcf2-bc9b-11e6-874d-15a240305805.png)

**Comment by sbarbosadataverse** [comment]
Hi Sherry:
This is exactly what you should be seeing. The supported download formats
are what is included in that list. Maybe we need to update the text in the
guide for accuracy.


On Wed, Dec 7, 2016 at 4:39 PM, Sherry Lake <notifications@github.com>
wrote:

> According to the user guide and the image displayed, a tabular file can be
> downloaded in "All formats". The image in the user guide shows this option,
> and is described in the text, but I do not see that option in production.
>
> [image: screen shot 2016-12-07 at 4 32 51 pm]
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__cloud.githubusercontent.com_assets_3809325_20987555_220c6d42-2Dbc9b-2D11e6-2D8701-2D89d8f66ff9d0.png&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=zWswK3IbRikMSjoHC1EIfgF-7ACqz-xSvSVB-0MHul4&s=3O62Fat5OhMc7MQO3NNyP9-gnbPIvGSvmXF9Qg9oFWQ&e=>
>
> I am looking at a tabular file on Harvard 4.5.1. Is this downloading all
> formats only for certain tabular files?
> From this dataset: http://dx.doi.org/10.7910/DVN/29604
> <https://urldefense.proofpoint.com/v2/url?u=http-3A__dx.doi.org_10.7910_DVN_29604&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=zWswK3IbRikMSjoHC1EIfgF-7ACqz-xSvSVB-0MHul4&s=wki_1gxxl9HK-EcOgvAoVEJa-tPC2V9WWkMxed-AUh4&e=>
>
> [image: screen shot 2016-12-07 at 4 35 50 pm]
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__cloud.githubusercontent.com_assets_3809325_20987658_85f6dcf2-2Dbc9b-2D11e6-2D874d-2D15a240305805.png&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=zWswK3IbRikMSjoHC1EIfgF-7ACqz-xSvSVB-0MHul4&s=Ow_Zy1L-24Fi6fyiKjiXfZdGVwtNe8xnlpxw7ZGVXeM&e=>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_issues_3513&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=zWswK3IbRikMSjoHC1EIfgF-7ACqz-xSvSVB-0MHul4&s=W-0OVsX3oa13TCXpy5vnftFBAqcyEBSKiPNyJXVFMXQ&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AH79Kntd4h51OQO97IfLKgXTYHShvbCzks5rFyd3gaJpZM4LHJKj&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=zWswK3IbRikMSjoHC1EIfgF-7ACqz-xSvSVB-0MHul4&s=oSNanLAa0NWpi2hNgz0fE_q2WboGQiHOImBKMh91GGI&e=>
> .
>



-- 
Sonia Barbosa
Manager of Data Curation, The Dataverse Project
Manager of the Murray Research Archive, IQSS
Data Science
Harvard University

all Harvard Dataverse Repository inquiries should be sent to:
support@dataverse.org

Dataverse 4.0 is now available for use!
http://dataverse.harvard.edu

All test dataverses should be created  in 4.0 Demo!
http://dataverse-demo.iq.harvard.edu/

Join our Dataverse Community!
https://groups.google.com/forum/#!forum/dataverse-community

**Comment by sbarbosadataverse** [comment]
The second is the correct image---what is available. Anyone else can chime
in....

On Wed, Dec 7, 2016 at 4:48 PM, Barbosa, Sonia <sbarbosa@g.harvard.edu>
wrote:

> Hi Sherry:
> This is exactly what you should be seeing. The supported download formats
> are what is included in that list. Maybe we need to update the text in the
> guide for accuracy.
>
>
> On Wed, Dec 7, 2016 at 4:39 PM, Sherry Lake <notifications@github.com>
> wrote:
>
>> According to the user guide and the image displayed, a tabular file can
>> be downloaded in "All formats". The image in the user guide shows this
>> option, and is described in the text, but I do not see that option in
>> production.
>>
>> [image: screen shot 2016-12-07 at 4 32 51 pm]
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__cloud.githubusercontent.com_assets_3809325_20987555_220c6d42-2Dbc9b-2D11e6-2D8701-2D89d8f66ff9d0.png&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=zWswK3IbRikMSjoHC1EIfgF-7ACqz-xSvSVB-0MHul4&s=3O62Fat5OhMc7MQO3NNyP9-gnbPIvGSvmXF9Qg9oFWQ&e=>
>>
>> I am looking at a tabular file on Harvard 4.5.1. Is this downloading all
>> formats only for certain tabular files?
>> From this dataset: http://dx.doi.org/10.7910/DVN/29604
>> <https://urldefense.proofpoint.com/v2/url?u=http-3A__dx.doi.org_10.7910_DVN_29604&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=zWswK3IbRikMSjoHC1EIfgF-7ACqz-xSvSVB-0MHul4&s=wki_1gxxl9HK-EcOgvAoVEJa-tPC2V9WWkMxed-AUh4&e=>
>>
>> [image: screen shot 2016-12-07 at 4 35 50 pm]
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__cloud.githubusercontent.com_assets_3809325_20987658_85f6dcf2-2Dbc9b-2D11e6-2D874d-2D15a240305805.png&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=zWswK3IbRikMSjoHC1EIfgF-7ACqz-xSvSVB-0MHul4&s=Ow_Zy1L-24Fi6fyiKjiXfZdGVwtNe8xnlpxw7ZGVXeM&e=>
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_issues_3513&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=zWswK3IbRikMSjoHC1EIfgF-7ACqz-xSvSVB-0MHul4&s=W-0OVsX3oa13TCXpy5vnftFBAqcyEBSKiPNyJXVFMXQ&e=>,
>> or mute the thread
>> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AH79Kntd4h51OQO97IfLKgXTYHShvbCzks5rFyd3gaJpZM4LHJKj&d=CwMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=8R6PzVqt1PEocauQgZMGXsGz29-nb19M7eqlo1d8EVs&m=zWswK3IbRikMSjoHC1EIfgF-7ACqz-xSvSVB-0MHul4&s=oSNanLAa0NWpi2hNgz0fE_q2WboGQiHOImBKMh91GGI&e=>
>> .
>>
>
>
>
> --
> Sonia Barbosa
> Manager of Data Curation, The Dataverse Project
> Manager of the Murray Research Archive, IQSS
> Data Science
> Harvard University
>
> all Harvard Dataverse Repository inquiries should be sent to:
> support@dataverse.org
>
> Dataverse 4.0 is now available for use!
> http://dataverse.harvard.edu
>
> All test dataverses should be created  in 4.0 Demo!
> http://dataverse-demo.iq.harvard.edu/
>
> Join our Dataverse Community!
> https://groups.google.com/forum/#!forum/dataverse-community
>



-- 
Sonia Barbosa
Manager of Data Curation, The Dataverse Project
Manager of the Murray Research Archive, IQSS
Data Science
Harvard University

all Harvard Dataverse Repository inquiries should be sent to:
support@dataverse.org

Dataverse 4.0 is now available for use!
http://dataverse.harvard.edu

All test dataverses should be created  in 4.0 Demo!
http://dataverse-demo.iq.harvard.edu/

Join our Dataverse Community!
https://groups.google.com/forum/#!forum/dataverse-community

**Comment by shlake** [comment]
But the guide describes an option (and shows it on the image) to download "All File Formats + Information", all the above as a zip bundle. This is the option that is not seen in 4.5.1. So yes, if the 2nd image is correct then the guide image and text needs to be updated.

**Comment by jggautier** [comment]
Sorry. Didn't mean to close.

**Comment by mheppler** [comment]
Sherry, thank you for creating this issue. I doing some investigating for more details, but I can tell at this moment is that the "All File Formats + Information" download feature was disabled as part of our performance and stability fixes. I'll update here with more information as I find it.

**Comment by scolapasta** [comment]
It was - it was specifically causing trouble because of the "chunking encoding bug" in Glassfish (Which has since been resolved with a patch to Glassfish) 

We would need to retest and confirm that it's no longer causing trouble, if/when we re-enable these bundle downloads.

**Comment by pdurbin** [comment]
It sounds like we can go two different directions with this issue:

1. Update the Guides to reflect the removal of the feature to download "All of the above, as a zipped bundle."
2. Re-enable this feature in the GUI after some performance testing.

For more background the reason this feature was taken out, please see http://guides.dataverse.org/en/4.5.1/installation/shibboleth.html#apply-grizzly-1787-patch and #2180.

**Comment by pdurbin** [comment]
I just wanted to mention that we revisited "download all" for the dataset level in #4000 which was included in Dataverse 4.9.3.

Here's how the example above at http://dx.doi.org/10.7910/DVN/29604 looks now:

## dataset level

<img width="219" alt="screen shot 2018-10-03 at 11 08 27 pm" src="https://user-images.githubusercontent.com/21006/46450820-4fd64e00-c761-11e8-9d47-106f69cd1711.png">

## file level

<img width="321" alt="screen shot 2018-10-03 at 11 09 31 pm" src="https://user-images.githubusercontent.com/21006/46450854-71cfd080-c761-11e8-9033-72c510fe95a0.png">

**Comment by shlake** [comment]
I think this can be closed, as the  User guide http://guides.dataverse.org/en/latest/user/find-use-data.html#download-files, no longer has an image of the download options (which was incorrect).

**Comment by pdurbin** [comment]
@shlake I hate to say it, but the image is still in the User Guide: http://guides.dataverse.org/en/4.15/user/dataset-management.html#tabular-data-files

That said, please don't let me stop you from closing this issue if you want. That's one of the powers the person who opens an issue has. :smile:

**Comment by shlake** [comment]
@pdurbin Thanks for double checking.
Obviously, I didn't look on that page ;-)
I'll keep it open, and add it to my project board under "bug" (as in user guide bug).

**Comment by mheppler** [comment]
@shlake there was a new issue titled _Optimize Zipping #6505_ which was recently opened. I am going to move some of the details of your use case to that issue to be considered as part of the scope when that work is prioritized.

**Comment by pdurbin** [comment]
> @shlake I hate to say it, but the image is still in the User Guide: http://guides.dataverse.org/en/4.15/user/dataset-management.html#tabular-data-files

I'm not sure when the image was removed but it's gone now: https://guides.dataverse.org/en/5.11.1/user/dataset-management.html#tabular-data-files

@shlake do you want to go ahead and close this? 😄

**Comment by shlake** [comment]
@pdurbin Maybe the title needs to change - or at least an update in the description. The image is gone, but the text https://guides.dataverse.org/en/5.11.1/user/dataset-management.html#tabular-data-files

still has this as the last bullet:
**All of the above, as a zipped bundle.**

That bullet still needs to be removed 

FYI: I signed up for the HacktoberFest and was going to work on Dataverse Documentation things - assume that is OK?

**Comment by pdurbin** [comment]
@shlake absolutely! I just added the hacktoberfest label. I missed that bullet. Looking forward to your PR! Thanks!
