### ISSUE TITLE
Bump Version from 4.5.1 to 4.6

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#3522]
Follow the steps here:

http://guides.dataverse.org/en/4.5.1/developers/making-releases.html#bump-version-numbers

**Comment by pdurbin** [comment]
Additionally, @kcondon and I want to make sure we merge all the SQL scripts into one file called upgrade_v4.5.1_to_v4.6.sql.

**Comment by pdurbin** [comment]
I just created pull request #3523 to bump the version from 4.5.1 to 4.6 and consolidate SQL upgrade scripts into upgrade_v4.5.1_to_v4.6.sql. Passing to code review at https://waffle.io/IQSS/dataverse
