### ISSUE TITLE
Notifications - User Account Converted

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#3525]
When a user converts their local/builtin Dataverse account to be authenticated through Your Institution (Shibboleth) or ORCID/GitHub/Google (OAuth), you should receive emails and system account notifications (just like those sent when you create an account), that provide the user more information, user guide links, etc.

This was originally suggested as part of development for #3338 based on recommendations from the design team after user testing, but was determined to be out of scope and has moved to this new issue.

**Comment by pdurbin** [comment]
Related:

- #3704
