### ISSUE TITLE
Dataverse metrics bar at sub-dataverse level

### ISSUE THREAD

**Issue by philippconzett** [IQSS/dataverse#3527]
I was wondering if there is a way to get metrics on sub-dataverse level? The metrics bar is displayed in the main dataverse, and for each dataset, and as of 4.6 even on the datafile level. However, it does not show up in the different sub-dataverses, or did I miss something? Would it be possible to include metrics for sub-dataverses?

Best,
Philipp, UiT The Arctic University of Norway

**Comment by pdurbin** [comment]
@philippconzett thanks for opening this issue. As I mentioned at https://groups.google.com/d/msg/dataverse-community/3w9q7Vs1I94/WLM5GiYEDQAJ this is related to a request at https://help.hmdc.harvard.edu/Ticket/Display.html?id=239408 that is referenced in #3312.

I've since noticed that #1971 is related as well. Also there's a lot of discussion about metrics in general at #2729 but I like how this issue you just created is more focused. Please note that it's conceivable that the functionality you want could be added to https://github.com/IQSS/miniverse which powers http://dataverse.org/metrics

**Comment by raprasad** [comment]
@philippconzett @pdurbin:

 For future reference, "download counts" are available via API at a sub-dataverse level.  However, currently this endpoint is only open to superusers.

API endpoint, including parameter descriptions: [monthly file download counts](https://services.dataverse.harvard.edu/static/swagger-ui/index.html#!/metrics_-_files/get_files_downloads_count_monthly)

- Relevant API parameters:
  - ```selected_dvs```: specify single dataverse or list of dataverses
    - default: only show download counts directly within the selected dataverse(s)
    - related option ```include_child_dvs```: include download counts of selected dataverses _*and their child dataverses*_
  
**Note**:  If demand exists, the selection of "sub-dataverses" may be extended to other statistics

**Comment by pdurbin** [comment]
@philippconzett you might be interested in the discussion at #3923.

**Comment by mheppler** [comment]
Related to, duplicate of issue **Dataverse - Views, Downloads, Citations, Shares #1808** and **Track views for Dataverses and Datasets #1969**.

**Comment by pdurbin** [comment]
@philippconzett hi! Have you played with `parentAlias` in the Metric API?

"Specifies which Dataverse sub-collection the metric should be collected for" -- https://guides.dataverse.org/en/5.12/api/metrics.html#parentalias

In addition, there are some reporting tools that might help: https://guides.dataverse.org/en/5.12/admin/reporting-tools-and-queries.html

**Comment by philippconzett** [comment]
Thanks for this heads-up, @pdurbin! Is the parentAlias a global setting, so if you set it to subdataverse1, the metrics for subdataverse1 will also be displayed on the root dataverse and all other possible subdataverses?

**Comment by pdurbin** [comment]
@philippconzett `parentAlias` is not a global setting. It's a parameter you pass to the Metrics API to narrow the metrics returned.

To be honest, I'm not sure I understand your question. Here's the example from the docs I linked above:

---

Example: curl https://demo.dataverse.org/api/info/metrics/datasets/?parentAlias=abc would return the number of datasets in the Dataverse collection with alias 'abc' and in sub-collections within it.

---

Does that help?

Should we have a Zoom call or talk it out in chat? 😄

**Comment by philippconzett** [comment]
Sorry for my late reply, @pdurbin. I mixed up API and GUI in my previous reply - sorry. My original request was about the metrics bar in the GUI, which I still think would be good to have also at sub-dataverse level.

To use the Harvard Dataverse as an example: I would like the metrics bar that is currently displayed on top of the front page of the root collection (highlighted with red):

![image](https://user-images.githubusercontent.com/21955790/212004679-759dcb97-76ae-4d9a-8ae6-5d26ca1ff4a2.png)


to be available also at sub-dataverse level, e.g., here:

![image](https://user-images.githubusercontent.com/21955790/212004876-bdee71be-2af4-4e2d-9886-a6099068fabb.png)

Thanks!

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.

**Comment by philippconzett** [comment]
Hi all, I still think this feature request is relevant as more granular usage metrics is something that can contribute to motivate data sharing and a feature some of our depositors have been requesting.

Thank you for reconsidering whether this issues should be closed! For some reason, I'm not able to reopen the issue.

**Comment by pdurbin** [comment]
D'oh! I thought the creators of issue could re-open them. 🤔 

Ah, I'm seeing "you can re-open your own issues if you closed them yourself" at https://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github/21333938#21333938

I'll re-open this for you, @philippconzett. Thanks for letting us know!

**Comment by philippconzett** [comment]
I might have misunderstood some part of the old issues review process. As for me, this issue (#3527) can wait until the new SPA version of Dataverse is released.

**Comment by pdurbin** [comment]
@philippconzett ok, in that case, would you be willing to create an issue in https://github.com/IQSS/dataverse-frontend , mention it here, and close this issue?

**Comment by philippconzett** [comment]
@pdurbin Sure! Here it is: https://github.com/IQSS/dataverse-frontend/issues/474.
