### ISSUE TITLE
Allow to customize dataverse names and change "dataverse" to "repository"

### ISSUE THREAD

**Issue by mcrosas** [IQSS/dataverse#3529]
This issue has two parts:

- small "d" dataverse should not be used in the Dataverse application anymore (due to trademark issues, in addition of being confusing and not desirable by a number of community users). It should be changed to "repository". This means that in the facets it should say "xxx repositories" instead of "xxx dataverses", and under Add Data, it should say "Add dataset" + "Add repository". This should apply to other instances of "dataverse" through out the application.

- When a new repository is created (whether is the root repository/Dataverse installation or a sub-repository formerly called sub-dataverse) the user/admin can enter any name for the repository. For example, the root repository in the Harvard installation will still be called "Harvard Dataverse". However, the help text should encourage to provide a repository name that identifies well that repository and doesn't necessarily add "Dataverse" as part of the name. For example, the "Murray Research Archive" doesn't need Dataverse at the end, or "Merce Crosas Datasets" or "Merce Crosas Lab Data".

**Comment by djbrooke** [comment]
Closing in favor of individual issues #3611 and #3610.
