### ISSUE TITLE
Tabular Mapping: UI review/Mock-ups/Dev

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3531]
- [x] @mheppler and Tania UI review
- [x] mock-ups + review
- [x] dev (@raprasad -- let me know if you need wireframes for anything... MH)
    - [ ] Return to Dataverse link - see #3511
- [x] dev review (iterative during dev and final)

**Comment by mheppler** [comment]
After reviewing the [UI Clean Up](https://docs.google.com/document/d/1OQT5v_iY4zVuq76OqqX15fXije6BTpGtSm7pBfIIli0/edit#heading=h.qn2z0yfqzb9k) issues with Tania and Raman, we collaborated to create some mockups. 

*Map Data File*

![mapdata-geoconnect-mockup-1a](https://cloud.githubusercontent.com/assets/687227/21199733/c42d3abc-c212-11e6-921e-13f9a2c7a833.jpg)

![mapdata-geoconnect-mockup-1b](https://cloud.githubusercontent.com/assets/687227/21199743/ce1202ce-c212-11e6-817f-5ba9a692d8a2.jpg)

![mapdata-geoconnect-mockup-1c](https://cloud.githubusercontent.com/assets/687227/21199748/d1aabd22-c212-11e6-972a-d7c01a605c59.jpg)

![mapdata-geoconnect-mockup-1d](https://cloud.githubusercontent.com/assets/687227/21199757/d5f3722a-c212-11e6-958e-9dccc2393f6c.jpg)

*Style Map*

![mapdata-geoconnect-mockup-1e](https://cloud.githubusercontent.com/assets/687227/21199760/d9ffe4e8-c212-11e6-8952-42fcafa06529.jpg)

![mapdata-geoconnect-mockup-1f](https://cloud.githubusercontent.com/assets/687227/21199763/ddeff1ba-c212-11e6-9882-a070ea83d8fd.jpg)

![mapdata-geoconnect-mockup-1g](https://cloud.githubusercontent.com/assets/687227/21199767/e1e5ac06-c212-11e6-94ec-6d200fd906ce.jpg)

**Comment by raprasad** [comment]
- [ ] additional backend work: split out the worldmap layer form into two separate forms

**Comment by raprasad** [comment]
Logic checklist.  (for detaching form "pieces")

- [ ] Action: Select Latitude/Longitude from ```Type```
  - Show Lat/Lng form
  - Hide Single Column Join form (if showing)
  - Hide row2: WorldMap layer choices (if showing)
  - Show submit for Lat/Lng form
  - Hide submit for  ```Single Column Join Form```
- [ ] Action: Select non-Lat/Lng choice from ```Type```
  - Show Single Column Join form
  - Hide Lat/Lng form (if showing)
  - Show submit for  ```Single Column Join Form```
  - Hide submit for Lat/Lng form
  - Row2: Show/Hide WorldMap layer choices depending on if ``Single Column Join Form``` has chosen value.
  - Hide submit for Lat/Lng form
- [ ] Action: Select column from ```Single Column Join Form```
  - Show row2: WorldMap layer choices
- [ ] Action: Select "Select..." from ```Single Column Join Form```
  - Hide row2: WorldMap layer choices
- [ ] Action: Select "Select..." from ```Type```
  - Hide  ```Single Column Join Form```
  - Hide row2: WorldMap layer choices
  - Hide Lat/Lng form 
  - Hide submit for Lat/Lng form 
  - Hide submit for  ```Single Column Join Form```
  - Hide row2: WorldMap layer choices

  - Hide row2: WorldMap layer choices

**Comment by raprasad** [comment]
commit for "download from worldmap" button: https://github.com/IQSS/geoconnect/commit/124a7670e4ad3d0b1f68abeaaaa8092c33b438e5

![style_map](https://cloud.githubusercontent.com/assets/1036060/21901167/a1bdee0e-d8c4-11e6-829c-4da51966fedd.png)

**Comment by raprasad** [comment]
last check in.  reformatted/moved ajax messages to top: 

![style_map](https://cloud.githubusercontent.com/assets/1036060/22117290/6ff5ae02-de41-11e6-82da-2589e8a399e6.png)

**Comment by raprasad** [comment]
last commit:  
  - for post-delete page, change "return to dataverse" button text from "cancel" to "return to dataverse"
  - fix button size/color on post-delete page

![would_you_like_to_re-map_this_file_](https://cloud.githubusercontent.com/assets/1036060/22119802/f7eaf264-de4a-11e6-86da-b543551fc617.png)

**Comment by raprasad** [comment]
screen shot re: last check in.  note preview table needs some help

![style_map](https://cloud.githubusercontent.com/assets/1036060/22124954/de4b6e0a-de5f-11e6-9493-809f25517d41.png)

**Comment by raprasad** [comment]
last check in: 
![map_data_file](https://cloud.githubusercontent.com/assets/1036060/22128361/266625be-de6e-11e6-97fa-1f4ac6d0f126.png)

**Comment by raprasad** [comment]
- Almost there.  Working on display/download of rows that failed to join.  In some cases need to re-create a formatted column from the original file
- Alternative is a WorldMap change to re-send the failed row info in full but had run into issues of sending too many rows 100s, etc.

**Comment by raprasad** [comment]
- [ ] rationalize top buttons
- [ ] error and success messaging formatted
- [ ] preview tables (pre-mapping and modal failed rows)
   - verify formatting with tables too wide/too narrow

**Comment by raprasad** [comment]
- [ ] RP - make sure that commented out <form..> tag in delete button html is not needed

**Comment by raprasad** [comment]
- [ ] RP - Fix disjointed abstract code

**Comment by raprasad** [comment]
- [ ] change title to "Manage" via ajax

**Comment by raprasad** [comment]
- *NOTE*: QA Dependent on configuration/installation of Dev Server which has a target date of 2/9.  As discussed with @kcondon

**Comment by raprasad** [comment]
Pull request is here: https://github.com/IQSS/geoconnect/pull/119

**Comment by raprasad** [comment]
- last commit related to code review.  (add some tests to make sure those changes working correctly)

**Comment by raprasad** [comment]
- [x] test for dv metadata update (no server, etc)
  _- in last commit_
- [ ] test for dv metadata delete

**Comment by raprasad** [comment]
(accidental close)

**Comment by raprasad** [comment]
- NOTE: QA may be done on Heroku test server

**Comment by kcondon** [comment]
Very minor potential issue: 
when world map layer not specified, error message refers to it as chosen_layer:

Errors found with the following field(s):
- chosen_layer: This field is required.

Field help text:
 Select the WorldMap layer to map your geospatial data onto.

**Comment by kcondon** [comment]
Some general feedback: 

I could easily work through generating a map but wasn't sure what I'd done afterwards. I was a little confused conceptually: I think of starting from what I want to map (my data) and where I want to map it on to (an appropriate layer). Additionally, attributes select box on resulting map confused me as to what they represented because I'd seen them earlier in the preview/layer step. Here, the data has already been geo located (mapped) based on the earlier step of mapping a data column onto a layer so that now the remaining columns or attributes can be displayed on the map. However, the original location column(s) still appear in the attributes list.

**Comment by kcondon** [comment]
Error message when there is a mismatch between data type, column, and layer is not super clear:
Sorry! Error Creating Join: No records matched. Make sure that you chose the correct column and that the chosen layer is in the same geographic area.

I chose Boston, Administrative Geography, the wrong column, and any of the available layers.

Maybe something like this is clearer?
Sorry, could not create a map using the selected data. Make sure the selected column contains geolocation data and its type is compatible with the WorldMap layer selected, eg. zip code.

**Comment by kcondon** [comment]
Other than the issues identified, this is done.

**Comment by kcondon** [comment]
@mheppler @TaniaSchlatter @raprasad 

Last UX feedback from me:
-Style map might be renamed to focus more on data and displaying attributes and info rather than on visual style: Display Attributes? Populate Map? View Attributes? Select Attributes to Display?
-Potentially display selected column and layer selected to draw map when editing map and possibly viewing map. That way we better understand what data is underlying base map and can then re-edit if data and choose another if data supports that. Also better connects geolocation data with map and distinguishes it from displaying attributes.
