### ISSUE TITLE
Mapping bug introduced in 4.6

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3536]
Once a file is mapped the user no longer sees a "Map Data" button--therefore the map cannot be further edited or deleted.

Usual sequence for user with edit file permissions:
  1.  Before mapping, user sees:
      - 1.  "Map Data" button (map creation)
  1. After successful mapping, user sees:
     -  1. "Map Data" button (edit/delete map)
     -  2. "Explore" button (view map)
  - **Bug**: After mapping, user no longer sees (2a) "Map Data" button

This was likely introduced when code was factored out of the dataset page for sharing between the dataset and file pages.  (Seeing this on local build using develop and in production).

---

### "The Fix"

In  ```WorldMapPermissionHelper.java``` remove lines 465-467

```java
        if (this.hasMapLayerMetadata(fm)){
            return false;
        }
```

---

![screen_shot_2016-12-16_at_9_53_42_am](https://cloud.githubusercontent.com/assets/1036060/21266810/aab3934c-c375-11e6-8c52-8e1bc5d9dc19.png)

**Comment by raprasad** [comment]
- bug somewhere between ```file-download-button-fragment.xhtml``` and ```WorldMapPermissionHelper.java```

**Comment by pdurbin** [comment]
> "The Fix"
> 
> In WorldMapPermissionHelper.java remove lines 465-467
> 
>         if (this.hasMapLayerMetadata(fm)){
>             return false;
>         }

I removed these lines in pull request #3548. Passing to Code Review in https://waffle.io/IQSS/dataverse

**Comment by kcondon** [comment]
Map it button appears after initial map. Closing.
