### ISSUE TITLE
Data file citation not downloading correctly

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#3537]
On file pages, when I download an Endnote XML, RIS or BibTex file, I don't get files with the appropriate extensions (.xml, .ris or .bib). I seem to get citation files with the extension of the data files.

For example, when I try to download the Endnote XML for the .pdf file in the screenshot below, I get a citation file with a .pdf extension. (That file is here: https://dataverse.harvard.edu/file.xhtml?fileId=2908858&version=5.0). I get an error message when trying to open the file by double clicking on it. It does open through textEdit.

![screen shot 2016-12-16 at 10 01 25 am](https://cloud.githubusercontent.com/assets/18374574/21267068/ad978c34-c376-11e6-953e-b2a2969a70c7.png)

**Comment by djbrooke** [comment]
Good catch, @jggautier. Looks like it's working as expected on the dataset pages. This is now in "Ready" in Waffle.

**Comment by pdurbin** [comment]
I created pull request #3546 to fix this and am sending it to Code Review at https://waffle.io/IQSS/dataverse

**Comment by kcondon** [comment]
The fix does not appear to be present -all citation formats on files page download as .txt when building from branch 3546: 3537-file-citation-download. Passing back to Dev/Phil
