### ISSUE TITLE
Allow metrics bar to be hyperlinked, revisit design

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#3538]
Admins should be able to set a URL that users can navigate to when they click the metrics bar. 

![screen shot 2016-12-20 at 2 05 48 pm](https://cloud.githubusercontent.com/assets/7773392/21364126/7e240c26-c6bd-11e6-9463-73480bc8aa3d.png)

For example, we'll set the dataverse.harvard.edu metrics bar to link to dataverse.org/metrics currently, and other installations should be able to set this to their respective metrics pages.

**Comment by djbrooke** [comment]
Had a quick discussion with @TaniaSchlatter and @mheppler re: the appearance of the block - feel free to change the colors/design of the block around, but let's keep this defined to the block for now and not add additional functionality.

**Comment by mheppler** [comment]
Related to #3341.

**Comment by mheppler** [comment]
Added static link to Metrics block on dataverse pg. Restyled the Metrics blocks, removed all old, commented-out "coming soon" references.

Need to add configurable back-end support and front-end render logic. Using static `rendered="#{true}"` currently. The layout of the Metrics block also needs some additional attention, but for now, I've simplified the markup and removed old code, at least.

**Comment by djbrooke** [comment]
We discussed this in the planning meeting on 1/4. The following items remain:

- [ ] Add render logic for the root Dataverse
- [ ] Allow URL to be added to settings table
- [ ] Documentation

If the URL is not added in the settings file, the metrics will not be hyper linked. We acknowledge that we'd like to do some further work on this, but we'll keep it as it is for now and work on a larger overhaul in #3341.

**Comment by pdurbin** [comment]
I checked the three boxes above because I believe I implemented them all in 499e6be. Passing to Code Review in https://waffle.io/IQSS/dataverse

**Comment by pdurbin** [comment]
@mheppler I'm passing this to you so you can make any last changes before we make a pull request.

Out of the box, there should be no link. To add one, you can run this:

curl -X PUT -d http://metrics.dataverse.example.edu http://localhost:8080/api/admin/settings/:MetricsUrl

To remove the link, you can run this:

curl -X DELETE http://localhost:8080/api/admin/settings/:MetricsUrl

**Comment by TaniaSchlatter** [comment]
@mheppler I'd like to see what this looks like if possible before you are done with it. Thanks!

**Comment by pdurbin** [comment]
@TaniaSchlatter here's how it looks as of 499e6be:

<img width="415" alt="screen shot 2017-01-06 at 9 37 36 am" src="https://cloud.githubusercontent.com/assets/21006/21720915/d472192c-d3f3-11e6-93a4-e896c5f5380b.png">

**Comment by mheppler** [comment]
Got approval from @TaniaSchlatter on the cleaned up UI.

<img width="990" alt="screen shot 2017-01-06 at 12 42 55 pm" src="https://cloud.githubusercontent.com/assets/687227/21825671/a7dd09fa-d752-11e6-8084-76809633a4fd.png">

**Comment by kcondon** [comment]
OK works, closing.

**Comment by kcondon** [comment]
@pdurbin, I had already closed this ;)

**Comment by pdurbin** [comment]
@kcondon sorry! I was responding to https://github.com/IQSS/dataverse/pull/3568#issuecomment-272571027 . Thanks for merging it!
