### ISSUE TITLE
Not easy to preview changes to User Guide and API Guide in development

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#3540]
I'm pushing code to https://shibtest.dataverse.org as I work on #3338 but when you click links that go to the guides, you are taken to the final 4.6 version of the guides rather than the version that I'm working on. This means that you'll see stuff like "Log in or sign up with your ORCID account — learn more" but when you click "learn more" to end up on a page that doesn't talk about ORCID at all because there was no ORCID feature in 4.6.

![screen shot 2016-12-21 at 1 19 48 pm](https://cloud.githubusercontent.com/assets/21006/21400904/33ca8f92-c780-11e6-9ba2-28bd53f31899.png)

My proposed fix for this is to have an optional setting called `:GuidesVersion` where I can override "4.6" or whatever and have it go to an arbitrary "version" such as a branch name like "3338-oauth-login". That way, from the user interface, you can click "learn more" and actually read about ORCID, for example, at http://guides.dataverse.org/en/3338-oauth-login/user/account.html

This is somewhat related to #2831 and #2832 but different enough that I'm making a dedicated issue and pull request after talking this over with @djbrooke and @TaniaSchlatter .

**Comment by pdurbin** [comment]
I implemented a fix in pull request #3541 and am passing this to Code Review at https://waffle.io/IQSS/dataverse

**Comment by kcondon** [comment]
OK, URL for User Guide and API guide now read the :GuidesVersion entry, after gfish restart. Note that other guides still point to existing docs since they use the "latest" pointer. Closing.
