### ISSUE TITLE
User Guide says "Dataverse will email your unread notifications once a day"

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#3543]
As of 4.6 the User Guide says "Dataverse will email your unread notifications once a day." but I believe this was fixed in #1848. This line from the docs should be deleted, I believe. Here's a handy to link to the page I'm talking about: http://guides.dataverse.org/en/4.6/user/account.html

**Comment by pdurbin** [comment]
I removed the line in pull request #3539. Moving to QA.

**Comment by kcondon** [comment]
Was deleted.
