### ISSUE TITLE
Deaccession: deaccession button in some cases is not being rendered, possibly due to slow query timeout.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3544]
This was reported by a user (see RT 244439) and was reproduced but since we'd manually deaccessioned the dataset in question, the failure case is gone. Repeating this with other datasets in production did not immediately show the issue. Seems data related:

1. Choose to deaccession a dataset that had only one version
2. Deaccession popup appears right away, including cancel button
3. An in progress spinner appears and spins for a while, then disappears.
4. The deaccession button is never rendered.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
