### ISSUE TITLE
email Dataverse Contact / authenticated users

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#3545]
For authenticated users, it would be helpful if the username was included in the email sent to the dataverse contact.
Same behavior observed for "support" menu item.

**Comment by pdurbin** [comment]
@pameyer are you talking about the "Welcome to Dataverse!" email that is sent to the person who just created an account? Here is the text: https://github.com/IQSS/dataverse/blob/v4.6/src/main/java/Bundle.properties#L440

I'm not sure what you mean by "dataverse contact". A user does not necessarily become a contact for a dataverse. The user could just have a ready only role such as "Member", for example.

**Comment by pameyer** [comment]
@pdurbin - there are buttons in the GUI for "contact support" / ~"message to dataverse contact". These both send emails; but neither of those emails includes the source username

**Comment by pdurbin** [comment]
Ah you're talking about:

        if (isLoggedIn() && userMessage!=null) {
            mailService.sendMail(loggedInUserEmail(), email, getMessageSubject(), userMessage);

... over at https://github.com/IQSS/dataverse/blob/v4.6/src/main/java/edu/harvard/iq/dataverse/SendFeedbackDialog.java#L212

@mheppler is actually working on code related to this over in d800944 for #3036. Maybe there's a chance to coordinate in that branch.

**Comment by pdurbin** [comment]
As @mheppler points out, this is related to the "who wrote" aspect of #1916.

**Comment by pdurbin** [comment]
#2882 is related.

**Comment by mheppler** [comment]
@pameyer this issue you opened looks to be similar to **Email Dataset/Dataverse Contact: No context info given in the email correspondance received #1916**.

Please clarify any differences between these issues (e.g. "username") in a new comment #1916, and then close issue as a duplicate. Thank you.

**Comment by pameyer** [comment]
closing in favor of #1916; will re-open if necessary
