### ISSUE TITLE
Native API: publish dataset endpoint doesn't support :persistentId

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#3547]
Docs (http://guides.dataverse.org/en/latest/api/native-api.html) suggest that calls to 
`http://$SERVER/api/datasets/:persistentId/actions/:publish?type=minor&persistentId=doi:$DOI`would work the same way as calls to "http://$SERVER/api/datasets/$id/actions/:publish?type=$type".  Instead, it returns 400/{"status":"ERROR","message":"Bad dataset id. Please provide a number."}

And another vote for fixing #3483 and #2431 (either by updating the docs, or updating the API).

**Comment by pdurbin** [comment]
@pameyer good catch. It looks like was not fixed in #1837 as I expected. I'm pulling this into Development at https://waffle.io/IQSS/dataverse and plan to look at #2431 and #3483 while I'm in there.

**Comment by pdurbin** [comment]
I'm going to look at #2461 as well.

**Comment by pdurbin** [comment]
Fixed in pull request #3550. Passing to Code Review at https://waffle.io/IQSS/dataverse

**Comment by kcondon** [comment]
OK, works but in curl you need to put quotes around the URL for this particular call. Closing.
