### ISSUE TITLE
`Utils.isNumeric` returns `true` for empty string

### ISSUE THREAD

**Issue by michbarsinai** [IQSS/dataverse#3551]
Should be `false`.

It's a quick fix, but since this method is used a lot, fixing this would require some app-wide testing. So opening a new bug.

**Comment by pdurbin** [comment]
@michbarsinai please see my comments at #3903. Again, first we set expectations in the dev guide. Then we point to the expectation. Then we fix the code. Or just walk down the hall and have a conversation with the person if you can! :smile:

**Comment by pdurbin** [comment]
Closing to consolidate into #3950.

**Comment by oscardssmith** [comment]
In my mind, the better question is why does this function exist? It seems like a worse version of org.apache.commons.lang.StringUtils, and is only used by AbstractApiBean, which has the following method ` protected boolean isNumeric( String str ) { 
        return Util.isNumeric(str); 
    }`. This function is minimally tested, and only used in 5 places other than tests. I'm making a pull request now to remove the function and replace it's usages with the apache version.

**Comment by sekmiller** [comment]
Ready for QA.
