### ISSUE TITLE
Deploy error on Glassfish

### ISSUE THREAD

**Issue by anne27** [IQSS/dataverse#3554]
I am facing a problem in deploying the WAR file onto the glassfish server. Attached is the error message that follows from the asadmin shell: deploy [PATH NAME].

remote failure: Error occurred during deployment: Exception while loading the app : EJB Container initialization error. Please see server.log for more details.

I am not using Vagrant or any VM software as of now.

[CommandLIneMessage.txt](https://github.com/IQSS/dataverse/files/685313/CommandLIneMessage.txt)

**Comment by pdurbin** [comment]
@anne27 hi! Thanks for trying Dataverse! What version of Dataverse are you trying to install? Would you be willing to try Vagrant to see if you get the same results? At this point you might need to go through these step: http://guides.dataverse.org/en/4.6/installation/installation-main.html#fresh-reinstall . Please feel free to pop in http://chat.dataverse.org with questions.

**Comment by djbrooke** [comment]
Hi @anne27 and @pdurbin - I'm going to close out this issue since it appears that this support question is being covered as a support ticket.
