### ISSUE TITLE
Typo: Shapefile "repackaging" is skipping ".cpg" files

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3556]
Dataverse should handle shapefiles as described here:  
  - https://github.com/IQSS/geoconnect/wiki/How-Dataverse-Handles-Shapefiles

However, there's a bug where ".cpg" files aren't being re-packaged.

## Fix

File: ShapefileHandler.java

- Current line with Bug.  Should be ```cpg```, not ```.cpg```
```java
    public final static List<String> SHAPEFILE_ALL_EXTENSIONS = Arrays.asList("shp", "shx", "dbf", "prj", "sbn", "sbx", "fbn", "fbx", "ain", "aih", "ixs", "mxs", "atx", ".cpg", SHP_XML_EXTENSION);  
```

- Fixed line: 
```java
    public final static List<String> SHAPEFILE_ALL_EXTENSIONS = Arrays.asList("shp", "shx", "dbf", "prj", "sbn", "sbx", "fbn", "fbx", "ain", "aih", "ixs", "mxs", "atx", "cpg", SHP_XML_EXTENSION);  
```

**Comment by pdurbin** [comment]
Pull request #3557 has more than a one character fix, but makes sense and has a test in ShapefileHandlerTest.java, which makes me happy. Travis is happy too (build and tests pass): https://travis-ci.org/IQSS/dataverse/builds/189214989

I'm moving this to QA in https://waffle.io/IQSS/dataverse

**Comment by raprasad** [comment]
>more than a one character fix

... well, one character without the tests:)

**Comment by djbrooke** [comment]
One could say this was a good test of (a) character.

**Comment by kcondon** [comment]
Tested against all 15 supported file extensions as well as one not supported for comparison. Works, closing.
