### ISSUE TITLE
File Replace: Bug when deleting a replacement upload

### ISSUE THREAD

**Issue by dlmurphy** [IQSS/dataverse#3564]
While writing documentation for File Replace I noticed something I think is a bug.  

On the Replace File page, after uploading a replacement file I decided to delete the replacement using the Delete button. The warning box says that I'll need to click the Save Changes button on the following page in order to delete the file:

![delete file box](https://cloud.githubusercontent.com/assets/22962740/21781857/4016e558-d67f-11e6-9489-565cb433c10a.PNG)

However, when I click Continue, on the following page I get a success message telling me that the replacement file has been deleted _before_ I've hit the Save Changes button. Additionally, I am unable to upload a new replacement because the "Select Files to Add" button is grayed out.

![file replace bug](https://cloud.githubusercontent.com/assets/22962740/21781772/e7c2b954-d67e-11e6-9575-3d804259eace.PNG)

When I then click Save Changes, I get the following error message:

![file replace bug 3](https://cloud.githubusercontent.com/assets/22962740/21811666/81e74e10-d71e-11e6-82d3-9efab426ff67.PNG)

After this message, _then_ I'm allowed to add a new file.

**Comment by mheppler** [comment]
@dlmurphy -- since this feature is still in development and hasn't hit QA yet, you don't have to open a new issue for a bug like this. Please close this issue and add your comments (and screenshots -- thanks!) to the original development issue **Files: Ability to Replace a File Instead of Deleting #2290**.

**Comment by dlmurphy** [comment]
On Mike's advice, added this to original issue, #2290.
