### ISSUE TITLE
Browsing directly to a specified page number within a result set

### ISSUE THREAD

**Issue by andrewSC** [IQSS/dataverse#3565]
If you're browsing a Dataverse and wish to navigate to a specific page you must either manipulate the `page=` query string parameter or skip ahead/backward two pages at a time via pagination. Ideally there would be a third option which would allow the user to enter a page number (either as an input field within the pagination div, or otherwise) and browse directly to that page.

**Comment by pdurbin** [comment]
@andrewSC nice talking with you about this at http://irclog.iq.harvard.edu/dataverse/2017-01-10#i_47015

It sounds like you're look for "Go to [page]"  like in the screenshot below from http://ux.stackexchange.com/questions/7999/pagination-let-the-user-choose-how-many-items-are-shown-per-page

![m742v](https://cloud.githubusercontent.com/assets/21006/21821353/3f96fa74-d741-11e6-8f8f-6cfffafd17f8.jpg)

**Comment by andrewSC** [comment]
Likewise and correct!

**Comment by pdurbin** [comment]
@andrewSC are you still interested in this?

**Comment by andrewSC** [comment]
Sure am! Sorry for not getting back to you sooner on this.

**Comment by pdurbin** [comment]
@andrewSC no worries. Heads up that pagination is being added to the file listing page in #4656 but I don't believe there is a "go to page" feature planned.

**Comment by andrewSC** [comment]
Gotcha gotcha

**Comment by pdurbin** [comment]
> pagination is being added to the file listing page in #4656

This is how it looks:

<img width="1197" alt="Screen Shot 2022-10-10 at 7 45 05 AM" src="https://user-images.githubusercontent.com/21006/194859119-336b00f4-7534-4600-8ee1-db60914d8106.png">

@andrewSC however, you were talking about the home/collection/search results page originally which still doesn't have "go to page" or the ability to specify "search results per page":

<img width="524" alt="Screen Shot 2022-10-10 at 7 47 05 AM" src="https://user-images.githubusercontent.com/21006/194859540-cf7f0897-e684-424c-92ac-e09c097f12fa.png">

Are you still interested in this issue? Thanks.

**Comment by andrewSC** [comment]
Hey @pdurbin I can't say I am--I've since moved on to a different org.

**Comment by pdurbin** [comment]
@andrewSC I hope you're enjoying your new gig! I'll go ahead and close this out.

Future person reading this, please feel free to open a fresh issue!
