### ISSUE TITLE
Version Differences Details - Empty details added to dataset Versions table

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#3567]
In the **[Oral History of the Tenured Women in the Faculty of Arts and Sciences at Harvard University, 1981](https://dataverse.harvard.edu/dataset.xhtml?persistentId=hdl:1902.1/00709)** dataset in the Murray Research Archive Dataverse, I found that for some dataset version details, there is missing information.

![screen shot 2017-01-10 at 3 19 46 pm](https://cloud.githubusercontent.com/assets/687227/21823351/a797818c-d748-11e6-9f59-65a368099118.png)

In version 7.1 details are empty for **"MRA Metadata: ();"** and in version 4.0 **"Additional Citation Metadata: ();"** is empty.

**Comment by sekmiller** [comment]
This is fixed in the File Versions Difference Summary branch

**Comment by sekmiller** [comment]
@djbrooke I fixed this as a side effect of working on File Differences. Not sure what to do with it in our current process.

**Comment by pdurbin** [comment]
@sekmiller it sounds like you're saying you fixed this as part of pull request #3651 so I'm going to give this a milestone of 4.6.1 since that pull request was merged as part of that milestone.

**Comment by djbrooke** [comment]
Hi @kcondon - can you please take a look at this on the 4.6.1 release branch and verify if this was fixed as a side effect of the versions summary ticket? Feel free to close if so.

**Comment by kcondon** [comment]
Examples cited are fixed, closing.
