### ISSUE TITLE
Rsync File Import: Alternate manifest filename defined in job spec xml is used but also uploaded, not ignored as default file is.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3569]
This is being reported separately from #3353 because it is not considered a blocking issue.

If use a different filename for files.sha, also imports that file -it appears in file list though not in any manifest list.
For reference: /usr/local/glassfish4/glassfish/domains/domain1/applications/dataverse-4.5.1/WEB-INF/classes/META-INF/batch-jobs/FileSystemImportJob.xml

Bill's comments:
It should be treated like any other data file if: 1) it isn't set as the manifest filename in either the job xml or as a system property or it isn't in the job xml ignore list
(Kevin) It is set in the job spec file as the manifest filename but gets imported anyway.

Other more general comments from Bill on manifest file:
The manifest file is a property of the checksum step, not the file import step. This is desired behavior for experimental data.
Errors are reported whenever there are more files imported than manifest entries and visa versa.

**Comment by pdurbin** [comment]
@pameyer is this something you care about?

**Comment by pdurbin** [comment]
Related:

- #8985
