### ISSUE TITLE
Download Count: Download of variable metadata increments count but subset does not. Should be reversed.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3572]
While testing the new metrics bar, found the above issue in download count logic. Affects subsettable files only.

**Comment by kcondon** [comment]
Note, subset count is not incremented if no terms of use popup appears. It does increment count if tou pop is accepted.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
