### ISSUE TITLE
Download button present for files in previous dataset versions when newest version is restricted

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#3576]
When viewing a previous version of a dataset published with files that have no download restrictions, but whose newest version has restricted files, no restricted icons (red locks) are shown and there are download buttons. So it appears that those previous versions of currently restricted files are downloadable. But clicking on the download button gives an error that the user isn't authorized to view this page.

- Are previous versions of currently restricted files supposed to be downloadable? Is there a use case that someone would want others to have access to previous versions of files when their current versions are restricted?
- If previous versions of currently restricted files should not be downloaded, should their download buttons (and Explore-like buttons) be removed (or replaced with a request access button when the current file can only be accessed by request?)

**Comment by pdurbin** [comment]
We should probably retest this when #3776 hits QA.

**Comment by mheppler** [comment]
@pdurbin Can replicate this on production (4.8.4) still.

This issue #4154 from @sbarbosadataverse is a duplicate, as @jggautier noted in a comment. I am closing that issue and moving her comment to this issue.

From @sbarbosadataverse in the issue, Archived versions of restricted data should not allow "download" and "explore" options before showing 500 error bug #4154

> I created a new version of a dataset and restricted previously open data files. New version was published. I went back to the archived version and expected to see the data files now restricted, but no lock, red or green, was available (in super user mode or logged out mode).
> 
> The download option showed me all available tabular data options and only when I clicked on any of the download options did it show an error. Two ravens was also still available for me to click on and when I did, it redirected to two ravens but no error message and no variables.
> 
> The workflow should be that previously open data files (or any files), in archived versions, should not show explore, or download option, and should have the green or red lock to indicate file is restricted.

**Comment by scolapasta** [comment]
@jggautier yes in previous versions download button should be removed, but we should also note that it had been unrestricted. i.e. just removing the button doesn't give complete info.

**Comment by jggautier** [comment]
Moved info from this issue to #6057. Closing this issue.
