### ISSUE TITLE
Widgets - File Page

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#3578]
Navigating to a file page while in the context of a widget removes you from that widget and takes you a full-screen version of the dataverse.

Follow these steps:

- Go to http://gking.harvard.edu/data
- Click into a dataset (note that you remain in the widget iframe)
- Click into one of the files for the dataset (you leave the widget iframe and are directed to the dataverse)

Instead, the navigation to a file page should stay within the iframe, similar to how the dataverse to dataset navigation works.

**Comment by mheppler** [comment]
Scope Outline:
- navigate from dataset pg to file pg in widget
- navigate from dataverse pg to file pg for in widget AND full version (#3555)
- hide metrics block, edit button, edit metadata button, map data button on file pg in widget
- hide map data button on dataset pg in widget
- returned export metadata button back to dataset pg in widget

**Comment by oscardssmith** [comment]
Unassigned myself, as I don't really know how xhtml works well enough to tell if these changes are reasonable.

**Comment by pdurbin** [comment]
I took a look at pull request #3922 as of ed2c5ef and the changes seem reasonable to me. Here's the comment I left in my review:

> These changes make sense to me. Approved. I didn't actually run the code myself. Now that the Dev Guide includes information on getting set up to hack on the code for remote accounts (Shibboleth and OAuth) as well as Geoconnect, it might be nice to someday add a little information on how to hack on widgets code.

With permission by @mheppler I just merged the latest from "develop" into the pull request. Moving to QA in https://waffle.io/IQSS/dataverse

**Comment by pdurbin** [comment]
I just did a quick test as of a461340 and it looks ok, like this:

![screen shot 2017-06-22 at 4 20 44 pm](https://user-images.githubusercontent.com/21006/27454143-ebfdb366-5766-11e7-8d01-59700b9c189c.png)

Here's my "website":

```
murphy:deleteme pdurbin$ cat index.html 
BEGIN
<script src="https://dev1.dataverse.org/resources/js/widgets.js?alias=spruce&amp;dvUrl=https://dev1.dataverse.org&amp;widgetScope=spruce&amp;widget=iframe&amp;heightPx=500"></script>
END
murphy:deleteme pdurbin$ 
```
