### ISSUE TITLE
Guestbook: Cannot download a particular guestbook using Chrome, throws duplicate header error

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3581]
See RT 245614
Downloading the guestbook from CCAFS - Climate Change, Agriculture and Food Security fails when using Chrome with the error:
ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_DISPOSITION

It works with Firefox. Looking up the error online indicates Chrome sometimes throws this error when it has trouble understanding the filename due to something like a comma, etc. Workarounds include double quoting the filename in code or removing things like commas.

Strangely, Chrome can download other guestbook files and when they are saved, add a .csv file extension. When downloading using FF, no extension is added.

A working Chrome guestbook download is: 
https://dataverse.harvard.edu/dataverse/popcouncil

**Comment by mheppler** [comment]
@kcondon could you confirm that this issue is a duplicate of _Cannot download guestbook in Chrome if Dataverse has a "," in the name #4512_ and if so, close this. Thank you.

**Comment by kcondon** [comment]
@mheppler, I would say the other is a duplicate of this since this was opened 3 months earlier, references the same exact user with RT ticket info. I would suggest closing the other one.

**Comment by mheppler** [comment]
Comment on #4512 from @scolapasta 

>Discovered by CCAFS:
>https://dataverse.harvard.edu/dataverse/CCAFSbaseline
>
>If a Dataverse has a "," in the name, the user gets an error when downloading guestbook responses via Chrome.
>
>ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_DISPOSITION
>
>This looks to be easily solved by adding quotes around the filename when setting the Content-Disposition header (see https://stackoverflow.com/questions/13578428/duplicate-headers-received-from-server)
>
>At the same time we should consider:
>
>  -  by adding these quotes, we likely don't need to replace spaces with "_".
>  - would it be better to use the guestbook name as the name instead of dataverse name and id >(@jggautier ?)

**Comment by jggautier** [comment]
Hmm, revising my comment. If a dataverse has multiple guestbooks, the Manage Dataverse Guestbooks page doesn't let you download individual guestbooks. You can only download them all into one CSV file (which has a "guestbook name" column). So dataverse admins wouldn't need to "collect and sort many guestbook CSVs from the same dataverse." It's more likely that dataverse admins would be collecting one guestbook CSV each from several dataverses. On Harvard Dataverse, maybe IFPRI does this. Maybe this is something "multi-institutional" Dataverse repositories do. We should consider what will happen then.

In cases where there are multiple guestbooks, what would the downloaded guestbook response file name be? "{Name of the first guestbook} Guestbook responses"? And what should the file name be if the dataverse doesn't have a custom guestbook? The default guestbook is named "Default", so "Default Guestbook responses"?

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
