### ISSUE TITLE
Dataset Thumbnails: Shape file thumbnails should have a modal map preview opened by a preview link, it is missing.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3586]
Shape files have a thumbnail generated by the map it process and it is special since more than just a mouse over it has a preview link that is a modal popup rather than disappearing when moving off the image. It was opened via a preview link but that is missing, possibly when we optimized this view for performance.

**Comment by djbrooke** [comment]
Closing as a duplicate of #3601.
