### ISSUE TITLE
Re-styling tabular map: pre-populate style form

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3587]
- [ ] WorldMap: API endpoint for core_data, include style attribute, algorithm, bins, color
- [ ] Geoconnect: If non-default style exists, pre-populate form

---

![style_map](https://cloud.githubusercontent.com/assets/1036060/22224062/4729f4ea-e18b-11e6-97d3-166dfb52f50c.png)

**Comment by djbrooke** [comment]
Closing this, as the migration of worldmap.harvard.edu to new infrastructure is resulting in Geoconnect and Worldmap being able to no longer communicate. We can investigate new Geospatial explore/analysis solutions in the future and will reopen specific issues as needed.
