### ISSUE TITLE
MD5 - Empty labels shown on File Result Cards, Dataset Version Details

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#3590]
When reviewing the Version Differences Details popup for existing files on production, I found a [dataset which contains two files that do no have MD5's](https://dataverse.harvard.edu/dataset.xhtml?persistentId=hdl:1902.1/00700). In the popup, the "MD5" label is displayed, but there is no MD5 listed.

![screen shot 2017-01-24 at 2 08 05 pm](https://cloud.githubusercontent.com/assets/687227/22262352/940dd16a-e23e-11e6-9ac5-f7cba7d22896.png)

**Comment by mheppler** [comment]
It appears these same files showing empty MD5 labels in the details popup are also displaying empty MD5 labels on [their results cards on the dataverse pg](https://dataverse.harvard.edu/dataverse/mra?q=&fq0=fileTag%3A%224.+Detailed+Usage+Terms%22&types=files&sort=dateSort&order=desc).

This issue is also seen in [older ZIP files on production](https://dataverse.harvard.edu/dataverse/harvard?q=&fq0=fileTypeGroupFacet%3A%22zip%22&types=files&sort=dateSort&order=desc&page=290).

**Comment by djbrooke** [comment]
@mheppler is this a duplicate of #4131? Or is the issue here that the MD5s exist but are not displaying?

**Comment by mheppler** [comment]
@djbrooke more like #4131 is a duplicate of this older issue! I didn't do much digging into the symptoms though. I moved one of my screenshots from here over to Sonia's issue which has more info about the bug. Closing.
