### ISSUE TITLE
View File Versions / Difference Summary

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#3592]
breaking out #3241 into smaller stories

This issue is to track the addition of a version tab on the file page with Difference Summaries.

**Comment by djbrooke** [comment]
We identified a few tasks in Sprint Planning today:

- A rough mockup will be provided in order for development to begin
- We need to discuss how to determine who/when for editing
- We'll need to code to generate the summary of changes
- Investigate whether or not an API endpoint for this makes sense
- Load testing since this is a potentially resource intensive calculation

There may also be value in having a discussion covering the technical implementation of this issue and #3593. @scolapasta suggested this.

**Comment by mheppler** [comment]
Initial mockup of the file level version summaries to give development a starting point. We can review and revise the layout as development is able to demo a functional table and we get a chance to look at it in more detail with production data.

<img width="938" alt="screen shot 2017-01-27 at 8 43 19 am" src="https://cloud.githubusercontent.com/assets/687227/22406083/d7068bcc-e619-11e6-87fc-1cd8d28bab6e.png">

**Comment by mheppler** [comment]
Discussed design issues with the mockup above after questions were raised. Created a new, more detailed view of the summary for one version as a clear example.

<img width="946" alt="screen shot 2017-01-30 at 4 16 29 pm" src="https://cloud.githubusercontent.com/assets/687227/22480609/fd52b222-e7bf-11e6-81ab-23f1e1aabf55.png">

**Comment by mheppler** [comment]
Found a copy of a production data file ([link](http://dvn-vm5.hmdc.harvard.edu:8080/file.xhtml?fileId=2667945&version=5.0)) that is part of a dataset with versions that have been deaccessioned. I am adding a screenshot of the versions table to illustrate the missing version numbers, as well as summary notes and reason for deaccession.

![screen shot 2017-02-17 at 1 03 06 pm](https://cloud.githubusercontent.com/assets/687227/23077183/769ffdd4-f511-11e6-896d-24d11fad9752.png)

**Comment by sekmiller** [comment]
Fixed the Deaccession handling. See Version 2.1 is deaccessioned. Link will only be available for users with read access to unpublished versions, and difference summary replaced with Deaccession notes.

![screen shot 2017-02-17 at 1 50 28 pm](https://cloud.githubusercontent.com/assets/2364928/23078787/21415714-f518-11e6-96c2-c7985a62c9b8.png)

**Comment by mheppler** [comment]
TO-DO
- [ ] Style (bold, italic, muted, etc.) summary notes in table
- [ ] _(Usability testing recommendations TBD)_
- [ ] Updates to User Guide > Dataset + File Management

**Comment by djbrooke** [comment]
test comment

**Comment by mheppler** [comment]
Usability testing [recommendations](https://docs.google.com/document/d/193QZ9iHO1TXm8ywqoDKAg5WzEjlskuM4A1we9c2Xypw/edit) from UX team:

- [ ] Add table headers
- [ ] Highlight in bold the and remove link for the version currently viewed
- [ ] Add version number to top section of pg

**Comment by sekmiller** [comment]
@mheppler - checked in a fix for the second one and the third one for the file page.  Where should it go on the dataset page?

**Comment by dlmurphy** [comment]
Just spoke with @scolapasta about the way we display file changes in the table. There's potentially too much bolding going on, and not enough emphasis on file content changes (file replace, deletion, etc). When @TaniaSchlatter is in the office on Tuesday I'd like to come to a consensus about how to best solve this issue.

**Comment by kcondon** [comment]
-When logged in w/ edit perms, if on deaccessioned version, shows DEACCESSIONED in dataset id column and truncated.
-Versions never appear if entire dataset is deaccessioned: loading versions message remains if user views history and does not have edit perms.

**Comment by sekmiller** [comment]
If the entire dataset is deaccessioned then a user without edit perms should be restricted from files page, as they are not allowed to see the files tab.

**Comment by sekmiller** [comment]
Issues noted by Kevin above fixed and checked in.

**Comment by kcondon** [comment]
OK, looks good.
