### ISSUE TITLE
Review Dataset Difference Detail inconsistencies

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#3598]
In adding File Replace #2290 , we are left with some inconsistencies. 

In particular File Add and File remove show the ID and md5 in the left most column, whereas replace shows it in the 2nd and 3rd columns (for each of the respective files). However we also have to consider the case of File Metadata Changed, since the ID and md5 are also in the left hand column, and are used to identify the file.

![img_20170126_135604](https://cloud.githubusercontent.com/assets/4268292/22345765/72c64ba8-e3cf-11e6-82a4-4b0c6ecba18d.jpg)

Another inconsistency is that if you do a file replace, you see it as one row if comparing the version where the file was replaced, but as two rows (an add and delete) if comparing a later version with an earlier. For example, File was replaced in V3. If compare V3 to V2 you see the one replacement row. Comparing V4 to V1, you see two rows.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
