### ISSUE TITLE
Bug: Worldmap Preview Modal "disappeared" in 4.6

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3601]
On the Dataset listing page, mapped shapefiles previously had this functionality:
  - "preview" link below the map logo
  - Modal box that showed an embedded map -- no need to go to Geoconnect or WorldMap

---

Code previously connected to the "preview" link is commented out--and no longer functional:

```xhtml
<!-- WorldMap Preview -->
            <ui:remove>
            <ui:fragment rendered="#{DatasetPage.worldMapPermissionHelper.canUserSeeExploreWorldMapButton(fileMetadata)}">
                <div class="modal fade" id="map-modal-#{fileMetadata.id}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&#215;</span></button>
                                <h4 class="modal-title" id="myModalLabel"><span style="color:#c75b1d;">Preview Map:</span> #{fileMetadata.label}</h4>
                            </div>
                            <div class="modal-body">
                                <iframe id="id_iframe_map" height="300" width="100%" src="#{ DatasetPage.getMapLayerMetadata(fileMetadata.dataFile).getEmbedMapLink() }"></iframe>
                            </div>
                            <div class="modal-footer clearfix">
                                <a href="#{ DatasetPage.getMapLayerMetadata(fileMetadata.dataFile).getLayerLink() }" target="_blank"><img src="https://worldmap.harvard.edu/static/theme/img/WorldMap-Logo_26px.png" alt="WorldMap" class="pull-left" style="margin-top:5px;" /></a>
                                <a href="#{ DatasetPage.getMapLayerMetadata(fileMetadata.dataFile).getLayerLink() }" class="btn btn-default" target="_blank"><span class="glyphicon glyphicon-equalizer"/> #{bundle['file.metaData.viewOnWorldMap']}</a>
                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                    </div>
                </div>
                <a data-target="#map-modal-#{fileMetadata.id}" data-toggle="modal" class="small bg-info text-center" style="margin-top:5px;display:block;">
                    <span class="glyphicon glyphicon-map-marker"/> Preview
                </a>
            </ui:fragment>
            </ui:remove>
```

**Comment by pdurbin** [comment]
@raprasad you mentioned today that a developer may not need a full geoconnect and worldmap setup to work on this issue. Can you please elaborate on this or point to some docs? Here's where I document how to hack on Shibboleth, for example: http://guides.dataverse.org/en/4.6/developers/dev-environment.html#shibboleth

**Comment by raprasad** [comment]
It looked like this:

![mapping_tabular_files_-_google_slides](https://cloud.githubusercontent.com/assets/1036060/22983712/fcf4c74a-f370-11e6-887c-5e1dc36367e3.png)

**Comment by mheppler** [comment]
Related to #3495.

**Comment by mheppler** [comment]
Working to clean up the layout of the Preview button displayed along side the Explore, Map Data and Download buttons on the dataset pg and file pg. It is very difficult try and improve this layout and not address related issues #3341 or #3404.

![screen shot 2017-03-23 at 3 27 54 pm](https://cloud.githubusercontent.com/assets/687227/24266511/60c7bb50-0fdd-11e7-83ee-7114ceb9124c.png)

![screen shot 2017-03-23 at 3 28 08 pm](https://cloud.githubusercontent.com/assets/687227/24266515/635c5010-0fdd-11e7-9bd8-0c9fb5ab192a.png)

**Comment by mheppler** [comment]
Preview button + popup is back on the dataset pg and has been added to the file pg.

![screen shot 2017-03-23 at 4 03 58 pm](https://cloud.githubusercontent.com/assets/687227/24267971/6a73f6f0-0fe2-11e7-9eef-d0e3a6dfe40f.png)

**Comment by raprasad** [comment]
- @pdurbin : let's chat.  e.g. you can test the functionality by creating a map through your local geoconnect.

**Comment by sekmiller** [comment]
Great! Thanks!

**Comment by kcondon** [comment]
preview link is now a button and this causes spacing issues when logged in as admin and can see all buttons, particularly when a tabular datafile.

**Comment by mheppler** [comment]
With some minor CSS tweaks, I was able to find a few more pixels to improve the button spacing for larger browser windows. There is still an issue for medium and smaller sized windows. That will have to wait until we address #3341 which would require more of a redesigned solution.

![screen shot 2017-03-30 at 6 06 06 pm](https://cloud.githubusercontent.com/assets/687227/24528214/96c0f6a4-1573-11e7-8fe7-34a5ad68419e.png)
