### ISSUE TITLE
Should shapefiles automatically receive a "geospatial" tag?

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3602]
Ingest recognizes zipped shapefiles, should they also receive automatic tags?

**Comment by pdurbin** [comment]
Yes, probably. Does anyone else have any opinions on this?

**Comment by pdurbin** [comment]
Apparently, no one feels strongly about this. If someone out there does feel strongly, please open a new issue. Thanks. :smile: Closing.
