### ISSUE TITLE
File Replace: Allow shape files to be replace by other shape files.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3603]
Currently file replace does not allow replacing with zip files that contain multiple files in order to avoid the 1 to many mapping issue. A side effect is  that one cannot replace shape (zip) files with other shape files. This ticket is a placeholder to look at how that might be done, such as adding an exception based on mime-type, etc.

**Comment by mheppler** [comment]
This was also discovered while trying to replace a "double ZIP" file when working on mockups for code deposit (#5372). The page failed silently, and in the Glassfish logs, I found "Severe:   You cannot replace a file with the exact same file."
