### ISSUE TITLE
Introduce "repository" label to Dataverse application

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#3610]
Small "d" dataverse should not be used in the Dataverse application anymore (due to trademark issues, in addition of being confusing and not desirable by a number of community users). It should be changed to "repository". This means that in the facets it should say "xxx repositories" instead of "xxx dataverses", and under Add Data, it should say "Add dataset" + "Add repository". This should apply to other instances of "dataverse" through out the application.

**Comment by adam3smith** [comment]
@djbrooke trying to follow along why this was closed. Is "Dataverse" in the facets going to change in 4.7? Will it be customizable (at the installation level? At the dataverse level)?

**Comment by pdurbin** [comment]
@adam3smith I'm trying to remember the conversation but I think that for now we're sticking with small d dataverses for thing that holds datasets. I'd love to hear some ideas of what we could call it! 😄

**Comment by jggautier** [comment]
Yes, like @pdurbin mentioned and @mercecrosas verified, we'll continue referring to them as dataverses in the application. For example, clicking "+ Add Data" will still show "New Dataverse", and they'll be "dataverses" in the facets. I'd like to defer to @djbrooke about the timetable for this change.
