### ISSUE TITLE
Display User Info

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#3615]
As a Superuser I want to view more information about a user so that I can determine the best way to contact them.

This was an available feature in 3.x that we need to bring back in 4.x. This is reached via the Users list (#3614). Some of the info in the screenshot below may no longer be valid in 4.x.

![view user info](https://cloud.githubusercontent.com/assets/7773392/22494419/4f9114a8-e805-11e6-8d7a-3344199510cf.png)

**Comment by djbrooke** [comment]
- Consider something else instead of a whole new page

**Comment by TaniaSchlatter** [comment]
So if you (superuser) wants to view more info about a particular user, they need to find the user. What are superusers most likely to have to identify (find) users?

**Comment by sekmiller** [comment]
They might have a name, user name, maybe email address. Or possibly filter the list on affiliation.

**Comment by TaniaSchlatter** [comment]
If we treat the filter just as it is on the dataset page, we are all set. I don't think we need "watermark" text. Just a "find" button.
![dashboard_find_users](https://cloud.githubusercontent.com/assets/15386424/26729899/32e27eb4-477d-11e7-987d-7a765d65ee3b.png)

**Comment by djbrooke** [comment]
Closing this in favor of #3614. We'll make the changes on that PR.

**Comment by pdurbin** [comment]
http://guides.dataverse.org/en/4.7.1/admin/user-administration.html#manage-users-table says, "clicking on a username takes you to the account page that contains detailed information on that account" which we didn't end up doing.
