### ISSUE TITLE
Possible to default to non-CC0 license for new datasets?

### ISSUE THREAD

**Issue by tdilauro** [IQSS/dataverse#3618]
My organization currently does not wish to use CC0 waiver by default. Is it possible to default to non-CC0 license for new datasets?

**Comment by pdurbin** [comment]
Nope. It's hard coded at https://github.com/IQSS/dataverse/blob/v4.6/src/main/java/edu/harvard/iq/dataverse/TermsOfUseAndAccess.java#L282

Related: #1753.

**Comment by tdilauro** [comment]
Happy to move this to #1753.

**Comment by pdurbin** [comment]
@tdilauro thanks for leaving a comment in #1753. I'll close this issue.
