### ISSUE TITLE
Request: ability to use remote and dynamic lists in properties such as author, contributor, producer, contributor

### ISSUE THREAD

**Issue by edzale** [IQSS/dataverse#3622]
I would like to use external data (for example data I get by querying my LDAP directory) to suggest authors and contributors names while leaving the possibility to the user to enter a name which is not from my list of suggestions. Same for producers and distributors. This is important to reduce typos and the time dedicated to the documentation of the datasets.
I must indicate that this request is related to a self-installed institutional instance of Dataverse.

**Comment by pdurbin** [comment]
@edzale it would be easier to implement autocomplete for authors that already have Dataverse accounts in your installation since they're right there in the database (in the `authenticateduser` table). Would that be of interest as a start? Or are you really only interested in LDAP for now?

**Comment by edzale** [comment]
Hi @pdurbin 
Thank you for your answer. Your proposal sounds good. Is that something doable without forking the Dataverse project initial code? Do you know if some folks have implement this kind of autocomplete function before?

**Comment by pdurbin** [comment]
@edzale hi! Well, if you fork the code, we'd love to to get a pull request. 😄 

There's some autocomplete code when assigning permissions. It looks like this:

    public List<RoleAssignee> completeRoleAssignee( String query ) {
        return roleAssigneeService.filterRoleAssignees(query, dvObject, roleAssignSelectedRoleAssignees);                  
    }

That's from https://github.com/IQSS/dataverse/blob/v4.6/src/main/java/edu/harvard/iq/dataverse/ManagePermissionsPage.java#L348 and called from https://github.com/IQSS/dataverse/blob/v4.6/src/main/webapp/roles-assign.xhtml#L28

The idea is that the `query` above is the thing you're typing and that's suggesting people.

I hope this helps!

**Comment by pdurbin** [comment]
Related: #4282

**Comment by RightInTwo** [comment]
Both options could be possible with the solution proposed in #4772.
A) Referencing dataverse users: Call the dataverse API
B) Referencing LDAP users: Call a custom API (that would have to be created and maintained outside dataverse) that queries the LDAP

**Comment by djbrooke** [comment]
Closing in favor of #6030 to evaluate as part of a larger effort.
