### ISSUE TITLE
Support flexible option for DOI and Handle registration, in same installation

### ISSUE THREAD

**Issue by amberleahey** [IQSS/dataverse#3623]
At Scholars Portal (and possibly other library hosted installations) we'd like to have the choice to assign a handle to a dataset that we don't have "authority" over, or, when there are multiple copies of that data across various access repositories (e.g. licensed data for example). This would be in accordance with DOI best practice for data copies.  

Support for both handle and doi as a PID in the same installation would be great. Possibly the user can choose which PID to assign upon deposit. 
Related, but different than https://github.com/IQSS/dataverse/issues/2943

**Comment by pdurbin** [comment]
@amberleahey thanks for opening this issue. It's a nice follow up to what you had written at https://groups.google.com/d/msg/dataverse-community/E_nxXqH68NE/BwkHbR_IGQAJ

**Comment by pdurbin** [comment]
At https://projects.iq.harvard.edu/dcm2017 someone mentioned they really want this but I can't remember who. Probably @amberleahey :smile:

**Comment by pdurbin** [comment]
"This PR takes significant steps toward making PID Providers plugable and allowing multiple DOI accounts to manage different authority/shoulder combinations."

- #8674

**Comment by cmbz** [comment]
**2023/08/29**
- Added to Global Dataverse Backlog NIH Deliverables column and added relevant label as this issue has been identified as relevant to Aim 2, task 2.2.3: Support multiple DataCite providers

**Comment by cmbz** [comment]
2023/09/25: Follow up with @qqmyers to determine whether he has already addressed this issue.

**Comment by cmbz** [comment]
2023/10/23: Sized at approx. 80 (as per slack conversation: 5 October 2023)

**Comment by pdurbin** [comment]
Related:

- https://github.com/IQSS/dataverse-pm/issues/132
