### ISSUE TITLE
correct docs for `api/dataverses/$id/metadatablocks` API endpoint

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#3624]
Current docs have "The query body is a JSON array with a list of metadatablocks identifiers (either id or name)."; but `curl -d $json_list` fails with:
{"status":"ERROR","message":"Invalid token=EOF at (line no=1, column no=0, offset=-1). Expected tokens are: [CURLYOPEN, SQUAREOPEN]"}

`--upload-file $json_list_in_file` works as expected; but it's a field of the POST body (not the entire thing).

**Comment by pdurbin** [comment]
The native API docs could use a lot of work. That's what #2174 is about.

**Comment by pameyer** [comment]
I've been adding functionality to #3440 as I've been running across things.  Should I treat #2174 the same way for docs?

**Comment by pdurbin** [comment]
@pameyer let's both read or re-read http://blog.atom.io/2016/04/19/managing-the-deluge-of-atom-issues.html and chat sometime about the Dataverse GitHub issue tracker. I think there good ideas in there. Sometimes it makes sense to have a issue with a punchlist that is added to. The native API page is probably one of these. Here's my punchlist for the Installation Guide: #2944. We should also set expectations for the entire community in the CONTRIBUTING.md file per #2594, especially with regard to creating issues. You should keep doing what you're doing unless we update that doc, I'd say. 😄

**Comment by pdurbin** [comment]
We talked about this issue after standup today and decided to include a fix in pull request #6107 and add a "closes" to that pull request to close that issue after it goes through QA.

@pameyer is right. Using `--file-upload` works fine. I also like that now all the "out of the box" metadata blocks are enumerated. Here's a screenshot of this part of the API Guide looks now (in that pull request):

![Screen Shot 2019-08-21 at 12 25 50 PM](https://user-images.githubusercontent.com/21006/63450082-3983c000-c40f-11e9-8e2a-8b4b34f952a5.png)
