### ISSUE TITLE
Cannot publish dataset with existing DOI imported into Dataverse as DDI

### ISSUE THREAD

**Issue by didaRo** [IQSS/dataverse#3632]
Hello,

I am using Native API Dataverse (version 4.5.1) to add a new Dataset with json file 
**curl -X POST -H "Content-type:application/json" -d @data/dataset-create-new.json 'http://$SERVER/api/dataverses/$id/datasets/?key=$apiKey'**
In the dataset-create-new.json file, i have the following informations for my identifier
  **"authority": "10.5075",
  "identifier": "PP2RMH",
  "protocol": "doi",**
 
the API create a new identifier and ignore the sent identifier in json file. How can I use Native API to create a new dataset with an existing identifier?

Thanks !!!!

**Comment by pdurbin** [comment]
@didaRo hi! This sounds highly related to #3083. In the end, we decided not to merge #3377 but it's good to know that there's more demand out there than just the use case from @pameyer 

@didaRo are you trying to migrate your data from some other solution? Would you like to share any more details about your scenario?

**Comment by didaRo** [comment]
Hi @pdurbin 
I'm in the team of @Esther Dzale ( https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/dataverse-community/EVCuBELhEWs/5_oFB_5CAAAJ)
Just to summarize : there are no solution for this case ? 
Regards
Fairouz

**Comment by pdurbin** [comment]
@didaRo the way to import datasets that already have DOIs into Dataverse is to use XML rather than JSON. Specifically, the datasets need to be in DDI format.

Recently I was looking at #3583 and playing around with some code at https://github.com/pdurbin/dataverse/commit/ca6ecb49bb4fb1695e4a87ba54d768e22b2728c1 where you can see an example DDI file called "version1.xml" that I'm using in an integration test in BatchImportIT.java where I call "migrate". I can explain more if you'd like to go down the route of putting your datasets in DDI format. It should work. You can also read more about importing DDI files at https://github.com/IQSS/dataverse/blob/develop/scripts/migration/migration_instructions.txt#L31

**Comment by didaRo** [comment]
@pdurbin Hi, 
It's work, I added a new Dataset with an existing identifier :dancing_women: 

But I have another problem, when I try to publish dataset :
Case one : 
if i try to publish my dataset after to create it 
curl POST 'http://$SERVER/api/datasets/$id/actions/:publish?type=major&key=apiKey'
I have this error
{"status":"ERROR","message":"Latest version of dataset T1J10121 is already released. Only draft versions can be released."

Case two:
I modify dataset and try to publish draft version I have this error : version number 
org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: ERREUR: la valeur d'une clé dupliquée rompt la contrainte unique « unq_datasetversion_0 »
  Détail : La clé « (**dataset_id, versionnumber, minorversionnumber**)=(592, 1, 0) » existe déjà
Error Code: 0
Call: UPDATE DATASETVERSION SET LASTUPDATETIME = ?, MINORVERSIONNUMBER = ?, RELEASETIME = ?, VERSIONNUMBER = ?, VERSIONSTATE = ?, VERSION = ? WHERE ((ID = ?) AND (VERSION = ?))

Thanks 
Fairouz

**Comment by pdurbin** [comment]
@didaRo when you added your dataset with an existing identifier was the dataset in DDI format? If so, we can change the issue title to be about documenting how to accomplish what you're trying to do.

**Comment by didaRo** [comment]
@pdurbin yes DDI format file.
I have error when I try to publish this dataset (web platform or with API Dataverse)

**Comment by pdurbin** [comment]
@didaRo ok, I changed the title to "Cannot publish dataset with existing DOI imported into Dataverse as DDI". Thanks. I'm actually not sure if this is currently supported or not. You might need to import the dataset as published or something. Can you please provide the curl command you used to import the dataset as DDI?

**Comment by didaRo** [comment]
@pdurbin 
I use this command
**curl -H "X-Dataverse-key: $apiKey" "http://$SERVER/api/batch/migrate/?dv=dataverseName&path=/path/to/version1.xml&createDv=true"**

**Comment by didaRo** [comment]
the  **version1.xml** file
`<?xml version='1.0' encoding='UTF-8'?><codeBook xmlns="http://www.icpsr.umich.edu/DDI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.icpsr.umich.edu/DDI http://www.icpsr.umich.edu/DDI/Version2-0.xsd" version="2.0" source="DVN_3_0">
    <docDscr>
        <citation>
            <titlStmt>
                <titl>Black Professional Women, 1969 </titl>
		
		<IDNo agency="DOI">doi:10.5072/T1J10121</IDNo>
            </titlStmt>
            <distStmt>
                <distrbtr>IQSS Test Dataverse Network</distrbtr>
                <distDate date="2014-02-12">2014-02-12</distDate>
            </distStmt>
            <verStmt source="DVN">
                <version date="2014-02-13" type="RELEASED">3</version>
                <verResp>Dwayne</verResp>
            </verStmt>
            <verStmt source="DVN">
                <version date="2013-09-20" type="ARCHIVED">2</version>
                <verResp>Dwayne</verResp>
                <notes type="DVN:ARCHIVE_NOTE" subject="Archive Note">Replaced by version 3</notes>
                <notes type="DVN:ARCHIVE_DATE" subject="Archive Date">2014-02-13</notes>
            </verStmt>
            <verStmt source="DVN">
                <version date="2010-04-22" type="ARCHIVED">1</version>
                <verResp>sonia, IQSSdvnAdmin</verResp>
                <notes type="DVN:VERSION_NOTE" subject="Version Note">Initial version</notes>
                <notes type="DVN:ARCHIVE_NOTE" subject="Archive Note">Replaced by version 2</notes>
                <notes type="DVN:ARCHIVE_DATE" subject="Archive Date">2013-09-20</notes>
            </verStmt>
            <biblCit format="DVN">Cynthia Fuchs Epstein, 1983, "Black Professional Women, 1969 ", http://hdl.handle.net/1902.1/00012 Murray Research Archive [Distributor] V1 [Version]</biblCit>
	    
	    <holdings URI="http://dvn-4.hmdc.harvard.edu/dvn/study?globalId=doi:10.5072/T1J10121"/>
        </citation>
    </docDscr>
    <stdyDscr>
        <citation>
            <titlStmt>
                <titl>Black Professional Women, 1969 </titl>
		
		<IDNo agency="DOI">doi:10.5072/T1J10121</IDNo>
		
		<IDNo>T1J10120</IDNo>
            </titlStmt>
            <rspStmt>
                <AuthEnty>Cynthia Fuchs Epstein</AuthEnty>
            </rspStmt>
            <prodStmt>
                <producer>Cynthia Fuchs Epstein<ExtLink URI="http://www.asanet.org/page.ww?section=Presidents&amp;name=Cynthia+Fuchs+Epstein"/></producer>
            </prodStmt>
            <distStmt>
                <distrbtr>Murray Research Archive<ExtLink URI="http://www.murray.harvard.edu"/>
                    <ExtLink URI="http://murray.harvard.edu/files/murray/banner146x48.png" role="image"/>
                </distrbtr>
                <contact email="mra_support@help.hmdc.harvard.edu"></contact>
                <depDate date="1983">1983</depDate>
                <distDate date="1983">1983</distDate>
            </distStmt>
            <verStmt source="DVN">
                <version date="2010-04-22" type="ARCHIVED">1</version>
            </verStmt>
        </citation>
        <stdyInfo>
            <subject>
                <keyword>Achievement</keyword>
                <keyword>African American</keyword>
                <keyword>Women</keyword>
                <keyword>Professional</keyword>
                <topcClas>mra murraydiversity</topcClas>
                <topcClas vocab="Sampsize" vocabURI="http://www.murray.harvard.edu/vocabulary">50 or fewer</topcClas>
                <topcClas vocab="Gender" vocabURI="http://www.murray.harvard.edu/vocabulary">female</topcClas>
                <topcClas vocab="Age" vocabURI="http://www.murray.harvard.edu/vocabulary">mixed</topcClas>
                <topcClas vocab="Race" vocabURI="http://www.murray.harvard.edu/vocabulary">African American</topcClas>
                <topcClas vocab="SES" vocabURI="http://www.murray.harvard.edu/vocabulary">middle</topcClas>
                <topcClas vocab="Generations" vocabURI="http://www.murray.harvard.edu/vocabulary">1</topcClas>
                <topcClas vocab="Follow-up permitted" vocabURI="http://www.murray.harvard.edu/vocabulary">yes</topcClas>
                <topcClas vocab="Education" vocabURI="http://authorities.loc.gov/">Women and education</topcClas>
                <topcClas vocabURI="http://authorities.loc.gov/">Work</topcClas>
                <topcClas vocab="Family. Marriage. Women." vocabURI="http://authorities.loc.gov/">Women</topcClas>
            </subject>
            <abstract>The purpose of this study was to explore the special conditions which enable African American professional women to create a self-image and achievement value system, the problems attendant to traditional female roles, and the reinforcing components of the work situation. The study was also conducted in order to test the findings of a similar study the researcher did with White women lawyers, also archived at the Murray Center (see Related Studies below).&lt;br /></abstract>
            <abstract>&lt;br />  In 1969, the researcher interviewed 35 African American women in the following professions: law, medicine, dentistry, university teaching, journalism, business, and social service administration. Nursing, social work, and teaching at other than the university level were excluded.&lt;br /></abstract>
            <abstract>&lt;br />  A structured, open-ended interview was employed. The questions included nature of work, clients, disadvantages of being a woman, disadvantages of being African American, relationships at work, professional associations, community organizations, education, demographics, family life, income, and dual-career conflict.&lt;br /></abstract>
            <abstract>&lt;br />  The Murray Archive holds additional analogue materials for this study: original record paper data for 35 women, including interviews and other descriptive materials. The Murray Archive also holds audiotaped interviews. If you would like to access these materials, please apply to use the data.</abstract>
            <sumDscr>
                <timePrd event="start" date="1969">1969</timePrd>
                <collDate event="start" date="1969">1969</collDate>
                <nation>United States</nation>
            </sumDscr>
        </stdyInfo>
        <dataAccs>
            <setAvail>
                <origArch>Henry A. Murray Research Archive, Institute for Quantitative Social Sciences, Harvard University</origArch>
                <avlStatus>Available</avlStatus>
            </setAvail>
            <useStmt>
                <specPerm>Submission of the following &lt;a href= "http://www.murray.harvard.edu/application"  target="_blank">Application For The Use Of Data&lt;/a> is required to access the data from this study.</specPerm>
                <restrctn>I will use these data solely for the purposes stated in my application to use data, detailed in a written research proposal. I will honor all agreements and conditions made between the Contributor of the Data and the study participants, and between the Contributor of the Data and the Henry A. Murray Research Archive, Harvard University, as specified in the Memorandum of Agreement.</restrctn>
                <contact>&lt;a href="mailto:mra@help.hmdc.harvard.edu">Manager of Operations&lt;/a>, the Henry A. Murray Research Archive, Institute for Quantitative Social Sciences, 1737 Cambridge St, Cambridge, MA 02138, USA.</contact>
                <citReq>I will include a bibliographic citation acknowledging the use of these data in any publication or presentation in which these data are used. Such citations will appear in footnotes or in the reference section of any such manuscript. I understand the guideline in "How to Cite This Dataset" described in the Summary of this study.</citReq>
                <deposReq>Murray Research Archive will list my publication and manuscripts on the Archive website when I submit a bibliographic citation or title of the manuscript, and indicate the Henry A. Murray Research Archive data used. Doing this will also help Henry A. Murray Research Archive to provide funding agencies with essential information about use of archival resources, to fulfill requirements of some memoranda of agreement, and to promote the broader exchange of information about research activities.</deposReq>
                <conditions>The data are available without additional conditions other than those stated in the "Restrictions" Terms of Use above.</conditions>
            </useStmt>
            <notes level="dv" type="DVN:TOU" subject="Terms Of Use">&lt;div style="padding-left: 30px;">
&lt;ul style="list-style-type: decimal;" >&lt;li>
                The Murray Archive (the Distributor) has granted me a revocable license to use this dataset solely for the purposes of conducting research, and the Distributor may terminate this license at any time and for any reason.
&lt;/li>
&lt;li>
                I will use the dataset solely for statistical analysis and reporting of aggregated information, and not for investigation of specific individuals or organizations, except when identification is authorized in writing by the Distributor.  
&lt;/li>
&lt;li>I will produce no links among the Distributor’s datasets or among the Distributor’s data and other datasets that could identify individuals or organizations.
&lt;/li>
&lt;li>I represent that neither I, nor anyone I know, has any prior knowledge of the possible identities of any study participants in any dataset that I am being licensed to use.  
&lt;/li>
&lt;li>
                I will not knowingly divulge any information that could be used to identify individual participants in the study, nor will I attempt to identify or contact any study participant, and I agree to use any precautions necessary to prevent such identification.
&lt;/li>
&lt;li>
                I will make no use of the identity of any person or establishment discovered inadvertently.  If I suspect that I might recognize or know a study participant, I will immediately inform the Distributor, and I will not use or retain a copy of data regarding that study participant.  If these measures to resolve an identity disclosure are not sufficient, the Distributor may terminate my use of the dataset.
&lt;/li>
&lt;li>
                I will not reproduce the dataset except as is necessary for my scholarly purposes.  I will destroy the dataset upon the completion of my scholarly work with it.
&lt;/li>
&lt;li>
                I will not share data from the dataset (in any form or by any means) with any third party, including other members of my research team, as I understand that all users of data must obtain the data directly from the Distributor.
&lt;/li>
&lt;li>
                I will make appropriate acknowledgement of the contributor of the dataset as well as the Distributor in any manuscript or presentation (published or unpublished) using the citation standard documented here: &lt;a  href="http://thedata.org/citation"> http://thedata.org/citation&lt;/a>
&lt;/li>
&lt;li>
                THE DISTRIBUTOR MAKES NO WARRANTIES, EXPRESS OR IMPLIED, BY OPERATION OF LAW OR OTHERWISE, REGARDING OR RELATING TO THE DATASET.  
&lt;/li>
&lt;/ul>
&lt;/div></notes>
            <notes level="dvn" type="DVN:TOU" subject="Terms Of Use">&lt;b>IQSS Dataverse Network Terms and Conditions&lt;/b>

&lt;p>By downloading these Materials, I agree to the following:&lt;/p>

&lt;ol>
&lt;li>I will not use the Materials to
&lt;ol type="a">
&lt;li>obtain information that could directly or indirectly identify subjects.&lt;/li>
&lt;li>produce links among the Distributor's datasets or among the Distributor's data and other datasets that could identify individuals or organizations.&lt;/li>
&lt;li>obtain information about, or further contact with, subjects known to me except where the use and/or release of such identifying information has no potential for constituting an unwarranted invasion of privacy and/or breach of confidentiality.&lt;/li>
&lt;/ol>
&lt;/li>
&lt;li>I agree not to download any Materials where prohibited by applicable law.&lt;/li>
&lt;li>I agree not to use the Materials in any way prohibited by applicable law.&lt;/li>
&lt;li>I agree that any books, articles, conference papers, theses, dissertations, reports, or other publications that I create which employ data reference the bibliographic citation accompanying this data. These citations include the data authors, data identifier, and other information accord with the Recommended Standard (&lt;strong>http://thedata.org/citation/standard&lt;/strong>) for social science data.&lt;/li>
&lt;li>THE DISTRIBUTOR MAKES NO WARRANTIES, EXPRESS OR IMPLIED, BY OPERATION OF LAW OR OTHERWISE, REGARDING OR RELATING TO THE DATASET&lt;/li>
&lt;/ol>
            </notes>
        </dataAccs>
        <othrStdyMat>
            <relStdyINRA>Cynthia Fuchs Epstein, 1983, "Women in Law, 1965-1980", hdl:1902.1/00168 Murray Research Archive [Distributor]. &lt;a href="http://dvn.iq.harvard.edu/dvn/dv/mra/faces/study/StudyPage.jsp?studyId=441" target= "_new">study available here&lt;/a>
            </relStdyINRA>
        </othrStdyMat>
    </stdyDscr>
    <otherMat level="study" URI="http://dvn-4.hmdc.harvard.edu/dvn/dv/mra/FileDownload/00012Epstein-Professional-Measures.pdf?fileId=8336">
        <labl>00012Epstein-Professional-Measures.pdf</labl>
        <txt>Collection of blank measures used in the study</txt>
        <notes type="vdc:category">1. Documentation</notes>
    </otherMat>
    <otherMat level="study" URI="http://dvn-4.hmdc.harvard.edu/dvn/dv/mra/FileDownload/00012Epstein-Professional-StudyDescription.pdf?fileId=8345">
        <labl>00012Epstein-Professional-StudyDescription.pdf</labl>
        <txt>Overview: abstract, research methodology, publications, and other info.</txt>
        <notes type="vdc:category">1. Documentation</notes>
    </otherMat>
    <otherMat level="study" URI="http://dvn-4.hmdc.harvard.edu/dvn/dv/mra/FileDownload/00012Epstein-Professional-MeasuresForm.pdf?fileId=8356">
        <labl>00012Epstein-Professional-MeasuresForm.pdf</labl>
        <txt>Usage guidelines relating to measures created by study investigators</txt>
        <notes type="vdc:category">2. Supplemental Documentation</notes>
    </otherMat>
    <otherMat level="study" URI="http://dvn-4.hmdc.harvard.edu/dvn/dv/mra/FileDownload/00012Epstein-Professional-BoxCoverSheets.pdf?fileId=8351">
        <labl>00012Epstein-Professional-BoxCoverSheets.pdf</labl>
        <txt>Describes contents of each box of a paper data set</txt>
        <notes type="vdc:category">2. Supplemental Documentation</notes>
    </otherMat>
    <otherMat level="study" URI="http://dvn-4.hmdc.harvard.edu/dvn/dv/mra/FileDownload/00012Epstein-Professional-MemoOfAgreement.pdf?fileId=8352">
        <labl>00012Epstein-Professional-MemoOfAgreement.pdf</labl>
        <txt>Legal agreement between data depositor and the Murray Archive</txt>
        <notes type="vdc:category">3. Detailed Usage Terms</notes>
    </otherMat>
    <otherMat level="study" URI="http://dvn-4.hmdc.harvard.edu/dvn/dv/mra/FileDownload/RM2562+Epstein?fileId=8359">
        <labl>RM2562 Epstein</labl>
        <txt>Box cover sheet for DVD's of .wavs from audio originals</txt>
        <notes type="vdc:category">5.Other Resources</notes>
        <notes type="LOCKSS:CRAWLING" level="file" subject="LOCKSS Permission">restricted</notes>
    </otherMat>
</codeBook>
`

**Comment by pdurbin** [comment]
@didaRo thanks! Can you please email support@dataverse.org and mention this issue? I'll get you in touch with people who will know more about if this is already supported or not. I'm hoping it only needs to be documented (no code change) but I don't really know. Thanks!

**Comment by didaRo** [comment]
OK 
thanks :)

**Comment by pdurbin** [comment]
@didaRo thanks for creating https://help.hmdc.harvard.edu/Ticket/Display.html?id=246794 . I assigned it to someone who can help. One thing is bothering me... You said the error is "Latest version of dataset T1J10121 is already released." In this context, "released" means "published". So it sounds like perhaps the dataset is already published? I'm confused about what state the dataset is in. (Doing a GET of the dataset to get a dump of it as JSON may help. This is documented at http://guides.dataverse.org/en/4.6/api/native-api.html#datasets .) Also, given how the DOI looks (doi:10.5072/T1J10121) it reminds me even more of #3583.

**Comment by didaRo** [comment]
@pdurbin.
In my case the dataset is not published, i checked the identifier in DataCite platform, it's doesn't exist :(
the command of migrate dataset maybe create the dataset in publish state.
I was also update the dataset created with existing identifier, and try to publish it I have an other error
I**nternal Exception: org.postgresql.util.PSQLException: ERREUR**: la valeur d'une clé dupliquée rompt la contrainte unique « unq_datasetversion_0 »
Détail : La clé « (dataset_id, versionnumber, minorversionnumber)=(592, 1, 0) » existe déjà
**Error Code: 0
Call: UPDATE DATASETVERSION SET LASTUPDATETIME = ?, MINORVERSIONNUMBER = ?, RELEASETIME = ?, VERSIONNUMBER = ?, VERSIONSTATE = ?, VERSION = ? WHERE ((ID = ?) AND (VERSION = ?))**

**Comment by pdurbin** [comment]
Ok, again, it might be interesting to see the JSON output of a GET of the dataset like this:

`curl -H "X-Dataverse-key: $API_TOKEN" http://localhost:8080/api/datasets/:persistentId?persistentId=doi:10.5072/T1J10121`

**Comment by didaRo** [comment]
@pdurbin Hi,
I have this JSON output, 
{"status":"OK","data":{"id":XXX,"identifier":"T1J10121","persistentUrl":"http://dx.doi.org/10.5072/T1J10121","protocol":"doi","authority":"10.5072","publisher":"Inra Dataverse","latestVersion":{"id":ZZZ,"versionNumber":1,"versionMinorNumber":0,"versionState":"RELEASED","distributionDate":"1983","productionDate":"Production Date","lastUpdateTime":"2017-02-17T13:23:57Z","releaseTime":"2010-04-22T00:00:00Z","createTime":"2017-02-17T13:23:57Z","license":"NONE","termsOfUse":"<div style=\"padding-left: 30px;\"> <ul style=\"list-style-type: decimal;\" > .....
Complete result  in attachment
[dataverse get dataset persistentID.zip](https://github.com/IQSS/dataverse/files/786847/dataverse.get.dataset.persistentID.zip)

Thanks

**Comment by didaRo** [comment]
Error in constraint unique « **unq_datasetversion_0** »
**the key  « (dataset_id, versionnumber, minorversionnumber)=(XXX, 1, 0) » already exist**

**Comment by didaRo** [comment]
Hello @pdurbin 

Finally I just specify DRAFT version in the DDI file :)
<verStmt source="DVN">
                <version date="2017-02-20" type="DRAFT">1</version>
</verStmt>

It's work :+1: 
Thanks for all 
Fairouz

**Comment by pdurbin** [comment]
@didaRo good job figuring it out! I guess we'll leave this issue open until we document the solution. Maybe it could go somewhere under http://guides.dataverse.org/en/latest/admin

**Comment by didaRo** [comment]
Hii @pdurbin,
I have another question, for the DDI file metadata
I have a DataCite metadata and I hope to converter the xml file to DDI format in order to migrate the dataset.
you use an API to do this in Dataverse ? 

Thanks a lot 
Fairouz

**Comment by pdurbin** [comment]
@didaRo hi, I see you posted about this at https://groups.google.com/d/msg/dataverse-migration-wg/I82Cpqf0rN0/ui_MFGvaAAAJ as well. We do not have a converter from DataCite to DDI.

There is some unmerged code to export from DataCite but I'm not sure that will help you. That code is at https://github.com/sbgrid/sbgrid-dataverse/blob/098b56b531f0c3e5cad689ef39eb54d321071587/mod-sbgrid/src/main/java/edu/harvard/iq/dataverse/export/DataciteExporter.java and was mentioned at https://github.com/IQSS/dataverse/issues/2917#issuecomment-270693674

A tool to convert from DataCite XML to DDI XML could probably be written as a standalone tool outside of Dataverse. For all I know such a tool already exists. You might want to ask on the DDI mailing list: http://lists.icpsr.umich.edu/mailman/listinfo/ddi-users . If you find one there or elsewhere, please let us know!

**Comment by pdurbin** [comment]
In a thread at https://groups.google.com/d/msg/dataverse-community/0WF2IA-43XI/gw8syLZZAwAJ Michel Bamouni just wrote, "To import an existing doi into my dataverse, I use sql queries. So I need to publish dataset using an sql command." At https://groups.google.com/d/msg/dataverse-community/0WF2IA-43XI/JJNhz8P0AAAJ I replied explaining that you can't publish just by switching one field in the database. The root problem, however, seems similar to this issue... a desire to import an existing DOI into Dataverse.

@didaRo what is your latest thinking on this issue, please?

**Comment by pdurbin** [comment]
Also: "We need this to import existing datasets with DOIs into Dataverse. For that, the two options are to either import via OAI-PMH or to create the dataset with a "test" DOI and then change it to the "real" one via SQL." -- @adam3smith at https://groups.google.com/d/msg/dataverse-community/qmFQK5_sZoA/dNotwpkQAgAJ

**Comment by pdurbin** [comment]
Also: "One of the SBGrid migration requirements is to move the existing datasets, along with their DOIs, into Dataverse. Currently, it appears that this can only be done using the DDI XML import." -- issue #3083 . @pameyer what do you think of these comments I'm making today? Similar requirements, right?

**Comment by pdurbin** [comment]
@didaRo are you still interesting in this issue? If so, pull request #4606 for issue #3083 was just merged and you could try an import using JSON.

**Comment by pdurbin** [comment]
Related: #5104
