### ISSUE TITLE
Style Guide - document the application of Bootstrap styles

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#3635]
Create a Style Guide to be added along with the other guides, to be utilized by designers/developers internally and in the community.

**Comment by TaniaSchlatter** [comment]
Here's a useful overview of the benefits of creating a guide, and tips on how to do it:
https://alistapart.com/article/creating-style-guides

Here's a list of tools for generating a guide. Not sure this will work for us:https://github.com/davidhund/styleguide-generators

**Comment by TaniaSchlatter** [comment]
See a breakdown of work on the Trello card: https://trello.com/c/DXs9VNl9/18-style-guide

In progress now: 
• Review and document the application of Bootstrap styles @michaelheppler
• Review examples of system feedback and guidance and classify them @taniaschlatter

**Comment by djbrooke** [comment]
- The audience for this is both internal and external
- TBD of the location of this guide (Sphinx likely)

**Comment by mheppler** [comment]
Development is happening in: https://github.com/IQSS/dataverse/tree/3635-style-guide

**Comment by djbrooke** [comment]
We talked about this in the Sprint Planning meeting yesterday. For "Done" for this issue, we'll plan to have the "Foundations" section drafted for the development team and @mercecrosas to take a look. We'll create another issue for the "Patterns" section. 

@TaniaSchlatter provided a good link to the definitions of these sections in the [comment above](https://github.com/IQSS/dataverse/issues/3635#issuecomment-282305448)

**Comment by pdurbin** [comment]
@TaniaSchlatter you can see the latest version at http://guides.dataverse.org/en/3635-style-guide/style/foundations.html

**Comment by pdurbin** [comment]
I fixed a typo in 0c4d1b3 but otherwise it looks great. I say merge it.

**Comment by mheppler** [comment]
Compiled feedback notes...
- Is mentioning Less necessary?
- Use more app specific icons in examples?

**Comment by scolapasta** [comment]
The lock question / suggestion was not just about the icon used on the button for restrict, but what shows up on top of the thumbnail (the little locked / unlocked image) after you've restricted a file. I'm perfectly fine if it's not included, but just wanted to be clear to what it is I was referring.
