### ISSUE TITLE
Customization Header/Footer/Homepage - Optional new landing page for installation

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#3639]
Based on feedback from the community (#2003), we will provide configurable settings to allow for an installation to enable a custom landing page as the homepage, as well as custom header and footer for their Dataverse application.

This issue, along with the custom configuration features outlined in #3637 and #3638 will provide a flexible solution for installations to brand their Dataverse application as they may choose with content, images, messaging, etc.

**Comment by pdurbin** [comment]
Possibly related: #2049.

**Comment by sekmiller** [comment]
To add a record to the settings table so that the app can find a custom file outside the war file(Also have to update SettingsServiceBean):
INSERT INTO setting(
            name, content)
    VALUES (':HomePageCustomizationFile', '/Applications/Custom/testCustom.xhtml');

**Comment by raprasad** [comment]
- Adding this from #3637: 

- Logo: display a logo in the navbar in place of orange Dataverse logo
   - This will be another external file
   - A setting will specify whether or not to look for the logo externally

**Comment by pdurbin** [comment]
@mheppler as I mentioned I got all of @sekmiller 's code working and made a documentation-only change at 29ed4d9 and included stubs for the following files. It would be fantastic if you could fill them out with real content:

- custom-footer.html
- custom-header.html
- custom-homepage.html
- custom-stylesheet.css

Thanks!

**Comment by pdurbin** [comment]
I set up a Jenkins job to build the docs hourly: http://guides.dataverse.org/en/3639-homepage-customization/

**Comment by kcondon** [comment]
-Search in the navbar does not work in this branch.

**Comment by pdurbin** [comment]
I just spoke with @sekmiller about the todo list above and will be making a few small documentation tweaks.

**Comment by pdurbin** [comment]
@sekmiller I implemented the documentation improvements we talked about in c05ae5e and you and @dlmurphy and others are welcome to take a look. I also merged the latest from develop into the pull request (#3639).
