### ISSUE TITLE
GeoConnect: Classification failing for lat/long maps

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3640]
Using the test data file, starbucks locations 2, I mapped using lat/long but could not then map an attribute, addresses or name_city without an error:

Sorry! The classification failed.

(Failed to remove whitespace from XML)

**Comment by raprasad** [comment]
worldmap codebase. @raprasad to consult with Paolo/Ben

**Comment by raprasad** [comment]
It is possible to classify lat/lng.  Example layer for wm admin to test: http://worldmap.harvard.edu/data/geonode:felix_centroid_g26

**Comment by raprasad** [comment]
(Checklist)

## Determine/communicate/store whether layer geom consists of points, polygons, mixed(?)

Note: Currently classify via UI in WorldMap **does not** make this distinction and has a **silent failure** when trying to style a point layer with a non-numeric attribute

- [ ] What is best way to determine if layer the layer consists of points or polygons (or mixed?)?
  - **polygon layers** - _any attribute_ may be used for styling
  - **point layers** - _only numeric attributes_ my be used for styling.  (source may be tabular or shapefile)
- [ ] Worldmap: send "layer type" or "style restrictions" back with other new layer info via existing API endpoints
- [ ] Geoconnect: receive/store layer type within WorldmapLayerInfo object 

## Limit user classification options for a "point layer"

- [ ] Geoconnect: Do not allow the user to choose a non-numeric attribute for styling
  - What is the best way to visually represent this?  
     - e.g. Do not list non-numeric attributes in the dropdown?  Italicize or in another way mark non-numeric attributes?

## SLD process: pinpoint numeric attribute failure for "point layer"

Note: Use the centroid file and compare the native UI method vs what is happening for the DV API.  e.g. The initial WMS SLD classify.xml call appears to be the same, but processing afterward differs 

Currently this process is failing.  Examine steps below to see why a "new" SLD for a numeric attribute fails.  Chain (may be updated)

### WorldMap

Compare input/output of these steps when done for DV versus the WorldMap UI

1.  Receives classify params from Geoconnect
2. Creates SLD in XML format by making call to geoserver classify service
3. (this could be it) Processes resulting XML to update several XML attribute names, etc
4. Associates new SLD with layer via WMS as well as appropriate geonode updates

**Comment by raprasad** [comment]
For (1) above: 

```sql
select type from geometry_columns where f_table_name = 'layer_name';
```

**Comment by raprasad** [comment]
Last check in has basics working for mapping Point layers.  Need clean-up, etc.
  - Note: It is unexpectedly working for string as well as numeric values

**Comment by raprasad** [comment]
- better error handling in for worldmap classification (on worldmap)
- reviewing error handling on geoconnect--especially for shapefiles

**Comment by raprasad** [comment]
- [ ] lat/lng link fix for map itself and legend

**Comment by raprasad** [comment]
Last check in fixings link for map.  gist notes/scratch work here: https://gist.github.com/raprasad/312623429945e08f980c90e14dc8dcb3

**Comment by raprasad** [comment]
geoconnect pull request: https://github.com/IQSS/geoconnect/pull/133
worldmap pull request: https://github.com/cga-harvard/cga-worldmap/pull/231

**Comment by raprasad** [comment]
(coordinating worldmap pull request via slack)

**Comment by pdurbin** [comment]
@raprasad and I just did code review of https://github.com/IQSS/geoconnect/pull/133 and https://github.com/cga-harvard/cga-worldmap/pull/231 and the changes are long but good. Raman demo'd classifying lat/longs and it works! It turns out that you can also classify strings and one improvement that's a little squirreled away is improved error messages when classifying a string with many unique values so a test case should be provided to @kcondon if we want him to see the improved error message. We also talked about how a microseconds value is now added to the URL which should help with errors involving a map not being found when deleting and remapping. The extra value in the URL helps prevent the browser from caching stale data.

**Comment by raprasad** [comment]
This is ready to test.

**Comment by raprasad** [comment]
New PR to avoid case where styling creates over 100 categories.  It's very easy to end up with 1,000s of categories and break the map.
https://github.com/cga-harvard/cga-worldmap/pull/235

Will coordinate with WM and Kevin

**Comment by raprasad** [comment]
Updated WorldMap PR above has been merged
