### ISSUE TITLE
GeoConnect: Columns used to create map layer are still present in (map) attributes list

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3641]
This seems like a bug: if I choose lat/long or a column like zip code for a mapped tabular file, the resulting map provides a list of attributes that can be displayed on the resulting map layer. However, they list all columns of the original data file, including the ones used to create the layer, which I think probably does not make sense.

**Comment by raprasad** [comment]
check with Ben to confirm

**Comment by raprasad** [comment]
Closing.  Checked with Ben and there are common cases where a user will want to classify on the column used to create the map.
