### ISSUE TITLE
Converter DataCite metadata (Dataset) to DDI format

### ISSUE THREAD

**Issue by didaRo** [IQSS/dataverse#3646]
Hello

I use this command to import the dataset as DDI
curl -H "X-Dataverse-key: $apiKey" "http://$SERVER/api/batch/migrate/?dv=dataverseName&path=/path/to/version1.xml&createDv=true"

I have a DataCite metadata and I hope to converter the xml file to DDI format in order to migrate a dataset.
you use an API to do this in Dataverse ?

Thanks!
Fairouz

**Comment by pdurbin** [comment]
@didaRo are you still interested in this? If so, is this a duplicate of #3632?

**Comment by pdurbin** [comment]
@didaRo hi? Still interested? Please let us know. Thanks.
