### ISSUE TITLE
Enrich dataverse shibboleth documentation

### ISSUE THREAD

**Issue by mbamouni** [IQSS/dataverse#3649]
Hello,

In dataverse shibboleth instructions, can you please indicate that "Session showAttributeValues" must be set to "true" to view attribute in /Shibboleth.sso/Session?

This related to my post : https://groups.google.com/forum/#!topic/dataverse-community/7QoOIiqNp8E

Best regards

**Comment by pdurbin** [comment]
@mbamouni thanks for opening this issue. It sounds like you're suggesting we add a little bit of text at http://guides.dataverse.org/en/4.6/installation/shibboleth.html#shibboleth2-xml just before the code block begins that contains `showAttributeValues` in it.

**Comment by pdurbin** [comment]
Fixed in c4f34df.
