### ISSUE TITLE
'Cite Data File' labelling

### ISSUE THREAD

**Issue by amberleahey** [IQSS/dataverse#3650]
As reported by a user of our installation: "Regarding the CITE DATA FILE function, this button is how to export the citation. I parse the phrase CITE DATA FILE as meaning getting the actual citation. It seems the button could be labelled as traditional databases do it: export citation or similar words."

**Comment by jggautier** [comment]
Thanks Amber! Would you say the user was unfamiliar with Dataverse? And was this feedback part of a usability study?

This was tested _a little_ when we were testing the new file landing page, but many of our participants were familiar with Dataverse.

**Comment by amberleahey** [comment]
Library user, not unfamiliar but new to using that feature.

**Comment by pdurbin** [comment]
It looks like there are some proposed changes to the button in c0c852f as part of pull request #4802 by @qqmyers for #4777.

**Comment by pdurbin** [comment]
I just wanted to mention that pull request #4802 was replaced by pull request #4971 and was merged in Dataverse 4.9.3. It looks like the button label is the same as before, though. It still says "Cite Data File" rather than "Export Citation" or whatever.

**Comment by pdurbin** [comment]
@amberleahey hi! Are you still interested in this? "Export Citation" has my vote but I don't feel strongly about it. 😄 

Just so we have a visual, here's how it looks these days (5.11.1):

<img width="1181" alt="Screen Shot 2022-10-13 at 9 56 43 PM" src="https://user-images.githubusercontent.com/21006/195744368-360a4070-d41b-48a9-bef0-fe7974a20b64.png">

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.

**Comment by pdurbin** [comment]
Related:

- https://github.com/IQSS/dataverse-frontend/issues/185
