### ISSUE TITLE
Make dataset DOI publication optional

### ISSUE THREAD

**Issue by andrewSC** [IQSS/dataverse#3652]
When creating a dataset, a DOI is automatically created and assigned. Furthermore, when publishing a dataset the DOI is also published. Ideally there is some way to configure Dataverse, or there is an option at publish, that allows you to decide whether or not you actually want to publish the DOI with the dataset. Rather than automatically publishing the DOI when you publish the dataset.

IRC discussion: http://irclog.iq.harvard.edu/dataverse/2017-02-27

**Comment by djbrooke** [comment]
Hey @andrewSC - I know this is something that's been discussed a bit in IRC - thanks for the log link for context! As I mentioned, accomplishing this for now will require some "creative breakage" of the application. :)

From a Dataverse Project standpoint, this isn't something that we'd want to make optional since our focus with the project is on publishing and sharing data, and the DOIs are a critical part of that.

**Comment by pdurbin** [comment]
Related:

delete DOI link from the citation block #6423

**Comment by pdurbin** [comment]
The ability to run Dataverse without real DOIs (or real Handles, any real PIDs) keeps coming up (most recently during day 1 of #dataverse2022 yesterday) so I'm reopening this issue.

Here's a related thread:

- https://groups.google.com/g/dataverse-community/c/nduj0om4qOg/m/_BdMHOi7AQAJ

Also, a real life example of a biotech that runs Dataverse behind a firewall and uses fake DOIs:

- https://osf.io/j6hmz/

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.

**Comment by pdurbin** [comment]
These days installations can choose Permalinks instead of DOIs. See https://guides.dataverse.org/en/6.3/installation/config.html#persistent-identifiers-and-publishing-datasets
