### ISSUE TITLE
Error migrating DVs with aliases longer than 60 characters

### ISSUE THREAD

**Issue by tdilauro** [IQSS/dataverse#3655]
More than anything, this is probably a documentation request, so those migrating from DVN 3.6.3 to DV 4.x aren't lost if they run into this problem. I ran into this while migrating our instance.

If incoming DV alias is longer than 60 characters (see #1252), it must be fixed before running step 2 (run migrate_dataverses.sql script](https://github.com/IQSS/dataverse/blob/develop/scripts/migration/migration_instructions.txt#L25) of the Migration Instructions. I received the following error when I encountered the problem. 
```
{
  "status": "ERROR",
  "message": "javax.ejb.EJBTransactionRolledbackException javax.ejb.TransactionRolledbackLocalException Exception thrown from bean javax.persistence.PersistenceException javax.validation.ConstraintViolationException: Bean Validation constraint(s) violated while executing Automatic Bean Validation on callback event:preUpdate. Please refer to embedded ConstraintViolations for details. javax.validation.ConstraintViolationException Bean Validation constraint(s) violated while executing Automatic Bean Validation on callback event:preUpdate. Please refer to embedded ConstraintViolations for details. (invalid value: <<<IIEAD_Project_Focus_Group_Interviews_in_Japan_and_South_Korea>>> for alias at [Dataverse id:5 name:Immigrant Incorporation in East Asian Democracies (IIEAD) Project: Focus Group Interviews in Japan and South Korea] - Alias must be at most 60 characters.)"
}
```
 
I resolved it by inserting a check before that step in the process:
```
select id, alias, name from _dvn3_vdc where char_length(alias) > 60;
```
For any DVs that met the condition, I did the following before proceeding:
```
# update the incoming dataverse
dv4db=# update _dvn3_vdc set alias = '{shorter-alias}' where id = {offending-id};
# renamed the corresponding DV folder from the DDI export step (step -5)
$ mv ddi/{offending-alias} ddi/{shorter-alias}
```
I would suspect that this could also be resolved by checking and fixing any offending alias in the DVN 3.6.3 database before starting the migration process.

**Comment by pdurbin** [comment]
@tdilauro this is a fantastic write up of the problem and solution but at this point I believe all (definitely most) DVN 3.x installations have been migrated to Dataverse 4 so I'm closing this issue. We will certainty point anyone to this issue if they run in this problem. Thanks!
