### ISSUE TITLE
geoconnect style - prefill attributes for an already styled map

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3660]
- WorldMap: return current classification selections (if they exist)
- Use the selection to prefill the classification form

**Comment by djbrooke** [comment]
In the Sprint Planning meeting 4/5, we mentioned that we'd need to work with Paolo from the Worldmap team on this. He'll be back on Monday.

**Comment by djbrooke** [comment]
Closing this, as the migration of worldmap.harvard.edu to new infrastructure is resulting in Geoconnect and Worldmap being able to no longer communicate. We can investigate new Geospatial explore/analysis solutions in the future and will reopen specific issues as needed.
