### ISSUE TITLE
Guestbook Response Download: In some cases does not report previously reported and still existing download records.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3662]
Reported by a user in production, see RT 247077

In the case reported by the user, entries from one day in January of this year had been included in the guestbook response download but no longer are. I've confirmed they are still in the db and using the same guestbook id.

I do not immediately know what might cause this but wanted to report it for further investigation. One thought might be to reproduce in a test environment, enable db debug output and reproduce the issue. We then compare that query which misses the entry with the one we run manually to see what's different.

**Comment by kcondon** [comment]
The user wrote back noticing further issues. After looking at their data and doing more testing it was  found that the cause is deleting files. When a file is deleted the guestbook download record is not viewable through the UI or downloadable. Note that downloading older versions of the deleted file does not add to the UI guestbook log but downloading presently available files from older dataset versions does add to the guestbook log. In all cases the downloads are still recorded in the db, guestbookresponse table.

**Comment by pdurbin** [comment]
The pull request is #3795.

**Comment by pdurbin** [comment]
I just looked at #3795 and I'm happy to see formerly duplicated code consolidated. I trust that @sekmiller has implemented the logic properly so I'm passing this to QA at https://waffle.io/IQSS/dataverse
