### ISSUE TITLE
Locate/Fix 500 Error on the Homepage: java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3665]
This is happening on the home page within the `DataverseServiceBean.java` code and giving 500 errors.  See New Relic screen shots below.

---

![traced_error_for_java_lang_arrayindexoutofboundsexception_-_my_application_-_new_relic](https://cloud.githubusercontent.com/assets/1036060/23614070/bc35bdf2-024f-11e7-8696-3835f31b2502.png)

---

![errors_-_my_application_-_new_relic](https://cloud.githubusercontent.com/assets/1036060/23614004/85eb1e0e-024f-11e7-9e2d-e0bfdfa3aed4.png)

**Comment by pdurbin** [comment]
This bug report is for https://dataverse.harvard.edu running v. 4.6 build 62-c913662. I'd be curious to know which line is throwing the IndexOutOfBoundsException in the DataverseServiceBean. The stack trace would be helpful, I mean.

**Comment by raprasad** [comment]
re; @pameyer : this may be related to changes in robots.txt

**Comment by pdurbin** [comment]
I just left a related comment at https://github.com/IQSS/dataverse/issues/2605#issuecomment-285103264

**Comment by djbrooke** [comment]
Notes from Sprint Planning meeting:

- We need to successfully split the string - this is not happening right now 
- Refactor into unit-testable class
- This is on a read path, not a write path

**Comment by raprasad** [comment]
(copying from other ticket #2605)

### Test url
  - http://localhost:8080/?q=&fq0=authorName_ss%25253A%252522U.S.+Department+of+Commerce%25252C+Bureau+of+the+Census%25252C+Geography+Division%252522&types=dataverses%25253Adatasets&sort=dateSort&order=desc

### where to start fixing

 - File: **SearchIncludeFragment.java**
 - Check for null string
 - Check length of array before attempting to access values

```
    public List<String> getFriendlyNamesFromFilterQuery(String filterQuery) {
        String[] parts = filterQuery.split(":");
        String key = parts[0];
        String value = parts[1];
```

**Comment by raprasad** [comment]
moved to code review

**Comment by raprasad** [comment]
help text should be reviewed

**Comment by raprasad** [comment]
branch/code changes: https://github.com/IQSS/dataverse/compare/3665-facet-error?expand=1

**Comment by raprasad** [comment]
test urls:

 - example url from prod (also above in ticket)
    - http://localhost:8080/?q=&fq0=authorName_ss%25253A%252522U.S.+Department+of+Commerce%25252C+Bureau+of+the+Census%25252C+Geography+Division%252522&types=dataverses%25253Adatasets&sort=dateSort&order=desc
  - From ticket #2605:
     - http://localhost:8080/dataverse/harvard?fq0=authorName_ss:%22Bar,+Foo

**Comment by raprasad** [comment]
Moved back to code review.  Attempt to catch error further upstream.
This also fixes #2605

**Comment by mheppler** [comment]
Added javascript function to clear search query string from URL with click of link from error msg on dataverse pg. The previous error msg only contained a link back to the root dataverse. The new link calls the JS function to reload the page minus all query parameters and works for any dataverse, not just the root.

![screen shot 2017-03-13 at 11 48 33 am](https://cloud.githubusercontent.com/assets/687227/23862505/8dfe5144-07e3-11e7-8f70-e2d49593a39a.png)

**Comment by raprasad** [comment]
pull request is here: https://github.com/IQSS/dataverse/pull/3691

**Comment by pdurbin** [comment]
@raprasad I just noticed that code coverage is decreasing on pull request #3691 but https://github.com/IQSS/dataverse/issues/3665#issuecomment-285150709 says, "Refactor into unit-testable class." Can you please add some unit tests? Thanks.
