### ISSUE TITLE
Missing File Investigation

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#3668]
There are a small number of local files in Dataverse where the metadata exists but the files do not exist. These files were uploaded during a time of system instability. In the application, this is noticed when a researcher goes to download a file and the file is not there.

We need to find what files are missing so that we can contact the creators of those files. This item will be complete when we provide a list to Sonia of:

- A count of the missing files
- The files that are in this missing state
- Any information about the uploaders that we can find, to make it easier to contact them

**Comment by raprasad** [comment]
One place to start, several of these files do not exist when attempting to download: 

https://services.dataverse.harvard.edu/miniverse/qc/filesize-zero-local-list

**Comment by djbrooke** [comment]
Planning Meeting Notes:

- The fix for this should be reproducible
- Leonid has a script that looks for all files, needs to adjust to provide the information about the files' (non-location) on the file system. Check should include MD5 as well.
- Consider feeding the script to the page in the previous comment in order to create a reusable dashboard for Sonia and other installation administrators
- Consider revisiting dataset integrity endpoint
- Consider using command line tool MD5sum here if it's helpful

**Comment by landreev** [comment]
Status update: 
I did run my script in production; 
the script is checked in in the branch 3668-missing-files-investigation. 
The output is saved as a tab-delimited file (that can be used to make a spreadsheet), with the tab-delimited fields as follows: 

FILESYSTEMPATH      CREATE DATE    DATASET, GLOBALID    DATAVERSE NAME    CONTACT EMAIL(S)

sorted by database id (which = by the date when it was created); 
I can send you the file and/or point you where it is saved on the prod. server (contact me off github). 
  
I'd like to review this list with a larger group, before we pass it to Sonia.
It appears that the bulk of it are indeed the "migration victims", back from the dvn3-to-dataverse4 upgrade.  
But there are some very recent cases too (a few files from a few days ago!) Which is a bit unexpected. So let's have a brief meeting tomorrow.

**Comment by landreev** [comment]
Also, fixed the few missing sizes of existing files, while I was at it.

**Comment by landreev** [comment]
I put the spreadsheet into Dataverse / Curation folder on GD; 
Passing it to Sonia; 
Did the meeting earlier today count as a "review"? Or does this need to be reviewed any further?

Opening a new issue to investigate the more recent/mysterious cases, unrelated to the upgrade instability.

**Comment by djbrooke** [comment]
Hey @landreev - this can be moved to done. I'll make sure Sonia gets the file list! Thanks.

**Comment by djbrooke** [comment]
Hey @landreev - I provided the list to Sonia. As we discussed in standup, feel free to get the script(s) merged and then move this one to done.
