### ISSUE TITLE
Dataverse Theme + Widgets - Broken TIF, TIFF upload for Logo Image

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#3671]
When developing the dataset thumbnail feature (#3559) it was determined that the TIF and TIFF upload is broken. Not sure if and when it worked, but upload a ~400 KB version with both extension formats did not work on Dataverse Beta.

![screen shot 2017-03-06 at 5 59 55 pm](https://cloud.githubusercontent.com/assets/687227/23634135/bd948e34-0296-11e7-9085-485f171da98e.png)

**Comment by pameyer** [comment]
I'm not familiar enough with the image handling code to know if it always does conversions, but I've run across browser issues with TIFF thumbnails (I can track down details from last time if it's helpful).

**Comment by mheppler** [comment]
@pameyer I did not do much testing on this. Only reporting an issue that I found. From what I could find, it appears that any valid TIF image file will fail to be uploaded.

**Comment by pdurbin** [comment]
I just wanted to note that as of this writing and testing, https://beta.dataverse.org is running v. 4.6 build 327-ce3d87c.

**Comment by pdurbin** [comment]
It looks like the message has changed slightly to "The image could not be uploaded. Please try again with a JPG, TIF, or PNG file."

If TIF files aren't working and no one is complaining (presumably, they're using JPGs and PNGs ok) we could simply remove "TIF" from the message (so we are no longer suggesting that they are supported).

**Comment by landreev** [comment]
@stevenwinship Just noticed that the error message was still saying `Please try again with a JPG, TIF, or PNG`. Just made a commit dropping it: 
https://github.com/IQSS/dataverse/pull/10820/commits/19489b0246db6161a99fd0d9708a98f45993dfbe
