### ISSUE TITLE
released file has "ingest in progress" indicator showing

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3676]
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/Z9MMD6&version=5.0
<img width="1017" alt="passed_resolves__resolves_1783__c_62__sc1_series_228__petition_of_william_brown_-_antislavery_petitions_massachusetts_dataverse" src="https://cloud.githubusercontent.com/assets/1036060/23703025/df5d9e80-03cb-11e7-8038-f6175f6c91e2.png">

**Comment by pdurbin** [comment]
Related to https://help.hmdc.harvard.edu/Ticket/Display.html?id=246242

**Comment by pdurbin** [comment]
I just checked https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/Z9MMD6&version=5.0 again and, sure enough, it still says "Ingest in progress" but this sounds very much like an issue that should be addressed by the support team behind Harvard Dataverse, which can be reached by clicking "Support" in the header of https://dataverse.harvard.edu and filling out the form. Dataset author @garthg or other interested parties are very welcome to mention this issue (which I'm now closing) when contacting Harvard Datavese Support.
