### ISSUE TITLE
use enum for possible fieldTypes

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#368]
---

Author Name: **Philip Durbin** (@pdurbin)
Original Redmine Issue: 3783, https://redmine.hmdc.harvard.edu/issues/3783
Original Date: 2014-03-26
Original Assignee: Steve Kraffmiller

---

This ticket is a placeholder for this thread:

```
From: Philip Durbin <philip_durbin@harvard.edu>
Date: Thu, Mar 20, 2014 at 8:33 AM
Subject: textBox or textbox? source of truth for possible fieldTypes?
To: Dataverse Team

```

textbox, text, date, email, and url and the current types defined at https://docs.google.com/spreadsheet/ccc?key=0AjeLxEN77UZodHFEWGpoa19ia3pldEFyVFR0aFVGa0E&usp=sharing

We're thinking we should make an enum (or something) the source of truth for this list of fieldTypes and refactor the code accordingly. Solr needs to know the types up front to avoid runtime exceptions while indexing.

Also, maybe we should call it textarea rather than text or textbox since that's what it is in HTML.

**Comment by scolapasta** [comment]
This is all set.

Test is to make sure there are no issues when loading a new setup and when editing and validating a dataset. Also, that dates and e-mails gets indexed the way we want them to.

**Comment by posixeleni** [comment]
@scolapasta also added "none" as a valid fieldType for parents of compound fields. I am checking in changes to the metadata block tsv files to reflect this modification now.

**Comment by scolapasta** [comment]
Confirming change was made and smoke tests pass.
