### ISSUE TITLE
Dataverse Theme - File upload for Logo Image does not have a file size limit if a logo already exists

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#3680]
When working on making the dataset thumbnail #3559 consistent with the dataverse theme functionality, I discovered that there is render on the page that shows you one of two file upload widgets. There is an inconsistency between the validation on these two fileUpload widgets. One has the `sizeLimit` attribute and one doesn't. That means if a dataverse theme already has a file uploaded as the logo, and you try to upload a new logo, that file does not have any file size validation applied to it. I was able to upload a 1.3 MB image, when the stated limited is 500 KB.

**Comment by jggautier** [comment]
Ran into this issue when fixing a logo display for a Dataverse collection in Harvard Dataverse Repository (https://dataverse.harvard.edu/dataverse/digistruct). The admins managed to upload a 2.2MB size PNG. This caused the image to be broken on the search page:

<img width="562" alt="Screen Shot 2021-05-13 at 11 22 50 AM" src="https://user-images.githubusercontent.com/18374574/118147473-9c846a00-b3dd-11eb-9ce9-36c5a56f004c.png">

I resized the image and re-uploaded it, but the image was still broken on the search page (even after several hard page refreshes, clearing my browser cache, and trying Chrome, Firefox and Safari (on MacOS)). I had to rename the resized image and re-upload - now the image displayed on the search results page:

<img width="312" alt="Screen Shot 2021-05-13 at 11 26 51 AM" src="https://user-images.githubusercontent.com/18374574/118147995-22081a00-b3de-11eb-8307-6385b6827c09.png">
