### ISSUE TITLE
Permissions-File giving me 500 internal server error message

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#3686]
I am trying to access the permissions-files page for : https://dataverse.harvard.edu/dataset.xhtml?persistentId=hdl:1902.1/00097-8

and keep getting this bug.

**Comment by pdurbin** [comment]
Access to Splunk would help. See also https://github.com/IQSS/dataverse/issues/3428#issuecomment-256929834 . Also, I suspect this issue might be specific to data in the Harvard Dataverse rather than a problem with the code. Without a stack trace isn't hard to know what's going on.

**Comment by mryder2** [comment]
@mheppler this appears to still be a problem

![image](https://user-images.githubusercontent.com/29635214/61492080-9b6b8880-a97e-11e9-86c5-b421e590c7ed.png)

**Comment by mheppler** [comment]
@mryder2 thank you for the update. Now that I have Splunk access, I will try to replicate and dig up a stack trace from the logs to report here.

**Comment by scolapasta** [comment]
I have narrowed down this issue to the fact this the user EHSConsortiumRestrictedData has access to files. If you remove that user from access (I tried this on a copy of the db), the page should load.

Still investigating what is bad about this user (it is a bean validation error).

**Comment by scolapasta** [comment]
@djbrooke I would suggest moving this to the Harvard specific repo (wasn't sure how to do that), unless we find a specific bug.

**Comment by scolapasta** [comment]
Found the issue with that user - the e-mail address has an extra "." character in it, so failed validation. Once you fix, that the page loads (albeit a slowly, because there are a lot of things going on in that page.

I'll go ahead and fix in the prod db.

**Comment by scolapasta** [comment]
@mryder2 Done, please try again, and then you can close this issue. (I'm leaving it to you, in case you see any other issue that I do not).

**Comment by scolapasta** [comment]
Hmm, actually now we get a "dataverse.harvard.edu took too long to respond." error. On vm-5 (production clone) it did take a while but eventually loaded.

It does load if you go directly to one of the servers.
