### ISSUE TITLE
UX Outreach - Configurable for users to opt-in to usability sessions

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#3694]
In a meeting with the UX team, we discussed ways to prompt users of the Harvard Dataverse to opt-in to usability sessions during their session.

One potential option discussed could be related to the issue allowing for custom content to be added to the footer (#3638).

**12/13/2017 edit from Derek:**

**User story: As a Guest or Dataverse user, I can see a feedback button in the UI that allows me to easily sign up to participate in Dataverse usability research in order to share my thoughts with the Dataverse Team.**

Discussed this with other members of the design team and with Danny, and here's what we want to implement for this issue (adapted from my comment further down in this issue):

 A small "Feedback" tab located in the corner of the screen that, when clicked on, expands to display a link to participate in usability research. This technique has been used for Consilience research in the past. Here are a couple screenshots of it in action on Consilience:

<img width="1139" alt="screen shot 2014-10-22 at 4 03 57 pm" src="https://user-images.githubusercontent.com/22962740/33950208-d6b8cac4-dff9-11e7-8cce-df9c8d414c51.png">
Here we see the red Feedback button at the bottom of the page.

<img width="1139" alt="screen shot 2014-10-22 at 4 04 11 pm" src="https://user-images.githubusercontent.com/22962740/33950243-eec99760-dff9-11e7-8a43-1bbac27f819e.png">
When a user clicks on the Feedback button, it expands to show a short message and a button that links out to a Qualtrics survey, which opens in a new tab.

A Feedback button like this in Dataverse can be set to link directly to a Qualtrics survey, or it can link to a Google Form where users can sign up to participate in remote usability testing sessions. The text and button inside the Feedback tab should be configurable by members of the design team. It should be possible to turn the feedback button on or off in the UI, to allow us the option to turn the button off when we're not running any studies. 

This Feedback button should appear in the bottom corner of the _screen_ rather than the _page_, so it doesn't get lost in the footer. If we're concerned about this being too annoying or intrusive, then we could include a little "x" on the button that users can click to dismiss it.

This Feedback button would be an extremely efficient way to recruit participants who are far more representative of our user base than we're currently able to. It would save a ton of time on recruitment, and it would get us a much higher number of recruits.

**Comment by pdurbin** [comment]
Heads up that I just added "Please email us at support@dataverse.org if you are interested in participating in usability testing" to CONTRIBUTING.md in pull request #3730.

**Comment by dlmurphy** [comment]
In our 11/29 team retrospective, we voted to prioritize improving the design team's ability to recruit participants for usability studies. 

We frequently need to recruit Dataverse users for surveys and usability testing, but we don't currently have a reliable way to reach end users who aren't stakeholders in the project. Going by the personas we've defined [in this document](https://docs.google.com/document/d/1DeFRHFj41aF0K7ETOmuUtjNh3uc4q0VdsVphSP7WAqs/edit?usp=sharing), we are currently able to reach Super-Admins, Admins, and (to a lesser extent) Curators. We typically recruit these users through Google Group posts and through direct contact via email.

We currently do not have a reliable way to reach our other 3 personas (which make up the wide majority of our users): Guests, Registered Users/Researchers, and Contributors. I've thought of a few different solutions, and I'm going to list them here, with #3 being, in my opinion, the best one.

## **1. Targeted email blasts**
Whenever we have a Dataverse UX study we need to recruit for, send a recruitment email to a subset of Dataverse users. If technically feasible, perhaps we could target these emails to, for example, users whose accounts have uploaded at least three datasets. This solution has the benefit of being easy to implement, but there may be some concerns about sending unsolicited recruitment emails to users.

## **2. Account option to opt in to recruitment emails**
Dataverse user accounts could have an option they could toggle to opt in to receive usability recruitment emails. When we need to recruit for a study, we could use a mailing list of all accounts with this option turned on. This option could be displayed during account creation, and on the account page. Compared to #1, this would give us fewer potential recruits, but it would also reduce the number of emails we send to people who aren't interested.

![option2](https://user-images.githubusercontent.com/22962740/33730617-89bf6df4-db4e-11e7-9fe8-a0b41aa38b85.PNG)

^This is what it might look like on the account creation page and account page.

## **3. Feedback button in Dataverse:**
A small "Feedback" tab located in the corner of the screen that, when clicked on, expands to display a link to participate in usability research. This technique has been used for Consilience research in the past. Here are a couple screenshots of it in action on Consilience:
<img width="1139" alt="screen shot 2014-10-22 at 4 03 57 pm" src="https://user-images.githubusercontent.com/22962740/33730659-b12aa8ea-db4e-11e7-8711-8522f110748c.png">
Here we see the red Feedback button at the bottom of the page.

<img width="1139" alt="screen shot 2014-10-22 at 4 04 11 pm" src="https://user-images.githubusercontent.com/22962740/33730688-c468d0e4-db4e-11e7-81a7-cccbcdb4cc2d.png">
When a user clicks on the Feedback button, it expands to show a short message and a button that links out to a Qualtrics survey, which opens in a new tab.

If we used a Feedback button like this in Dataverse, then we could have it link directly to a Qualtrics survey, or it could link to a Google Form where users can sign up to participate in remote usability testing sessions. The feedback button could be turned off normally, and only turned on when we have a study running that we need participants for.

This would be an extremely efficient way to collect recruits who are far more representative of our user base than we're currently able to.  It would save a ton of time on recruitment, and it would get us a much higher number of recruits. I'd recommend going with this option.

**Comment by pdurbin** [comment]
One idea I have is to print business cards we could hand out when we're chatting with researchers that invite them to participate in a usability test and explain how to get in touch. I got this idea from seeing how Data Science Services has a stack of cards to hand out during their office hours. @izahn and @goshevs were kind enough to give me a few cards and said it was fine to post a picture here:

![dss-cards](https://user-images.githubusercontent.com/21006/33889518-53293bfc-df1e-11e7-84fe-84f01d8edf56.jpg)

**Comment by mheppler** [comment]
Rooted around in the [Consilience code on GitHub](https://github.com/IQSS/consilience/blob/f6b67ee0f803f8201e1dee8434b67cbccdec75d6/src/consilience/src/main/webapp/template.xhtml) and found the old Feedback button from that screenshot.

```
<div id="surveyTab">
        <button type="button" class="btn btn-danger" data-toggle="collapse" data-target="#surveyTabBody">
                    <span class="glyphicon glyphicon-comment"></span>&#160; Survey
        </button>
        <div id="surveyTabBody" class="collapse">
            <div class="panel panel-default">
                <div class="panel-body text-center">
                          <p class="text-left">
                              Please fill out this quick survey, to help us improve Consilience!
                          </p>
                          <a class="btn btn-danger" href="https://harvard.az1.qualtrics.com/SE/?SID=SV_d7h4smaGG4dYNr7" role="button" target="_blank">
                              Start Now
                          </a>
                </div>
            </div>
        </div>
</div>
```

**Comment by dlmurphy** [comment]
Here's my preferred text for this feedback button:

**Header:** Feedback

**Body text:** Interested in helping us improve Dataverse's design? Volunteer to participate in our online user research using our sign up form!

**Button text:** Sign Up

**Button link:** https://goo.gl/forms/p7uu3GfiWYSlJrsi1

**Comment by mheppler** [comment]
Related to #3872, [README](https://docs.google.com/document/d/1tHwp9mmMeVRI2X_MY70Jp8rZqdkYDWWUcqywlwEUigU/edit#heading=h.32p51im12ty7) created to outline required customization options setup.

**Comment by mheppler** [comment]
Revised text as seen in screenshot below. Sending new resources files to @kcondon and will update link in README doc.
