### ISSUE TITLE
Index: Index according to data type to facilitate range facets and queries.

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#370]
---

Author Name: **Kevin Condon** (@kcondon)
Original Redmine Issue: 3785, https://redmine.hmdc.harvard.edu/issues/3785
Original Date: 2014-03-27
Original Assignee: Philip Durbin

---

This ticket is a placeholder for indexing fields that contain something other than strings, eg. dates and floats, to support range queries for either facets or searches, depending on what is finally decided.

Example date: production date
Example float: Coverage Central Wavelength(m)

---

Related issue(s): #70, #485
Redmine related issue(s): [3478](https://redmine.hmdc.harvard.edu/issues/3478), [3900](https://redmine.hmdc.harvard.edu/issues/3900)

---

**Comment by kcondon** [comment]
Closing as a duplicate and merging with #70.

**Comment by pdurbin** [comment]
Please see this new PR:

- https://github.com/IQSS/dataverse/pull/10887
