### ISSUE TITLE
Depositors/browsers can see which schemas map to Dataverse metadata fields

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#3701]
People adding, editing and viewing metadata will be able to see, in the UI, which fields in certain schemas map to Dataverse metadata fields they're adding, editing or viewing.

We'll need some way to show to users which fields in the citation, geospatial, life sciences and terms metadata blocks are mapped to schemas, including DDI, DataCite, Dublin Core, ISA-Tab, VO Resource and Schema.org.

This is related to #2162.

**Comment by pdurbin** [comment]
See also the related thread at https://groups.google.com/d/msg/dataverse-community/qsY8swD9Hh0/TgVLuELIAAAJ that says, "We should be able to map all the Nesstar DDI elements into [Dataverse]".

**Comment by jggautier** [comment]
Thanks @pdurbin. Glad to hear Janet found the mapping spreadsheet helpful. I imagine she and others working on migration and evaluation would also find it helpful to see where in the UI the Dataverse metadata fields are, helping them understand how researchers and curators might interpret a particular Dataverse field, and if it's being mapped to the appropriate fields in DDI and other standards.

That's hard to tell from the spreadsheet.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
