### ISSUE TITLE
4.6.1 Account creation confirmation email

### ISSUE THREAD

**Issue by TaniaSchlatter** [IQSS/dataverse#3704]
Now that there are multiple ways to create an account and log in, how does a user remember which option they used to create an account? 

I suggest the account creation confirmation email state which option was used to create an account, so the user has some reference. 

The email I got when I created an account is attached for reference.

<img width="718" alt="screen shot 2017-03-17 at 9 14 51 am" src="https://cloud.githubusercontent.com/assets/15386424/24044661/9c0a0eb0-0af2-11e7-88b0-1ce8d93256b9.png">

**Comment by pdurbin** [comment]
There's also the case of migrating from a Username/Email account to a Shibboleth ("institutional") or OAuth (ORCID, Google, GitHub) account. Perhaps an email should be sent in this case as well, as I suggested at https://github.com/IQSS/dataverse/issues/3407#issuecomment-292049702

Another thought is to have a form where people can enter their email address or username and be told immediately which authentication is in use for that email address or username. Maybe that's bad security though. I'm thinking back to the password reset feature I worked on in #416.

Anyway, to keep this issue small, I agree with Tania's suggestion to have the account creation message include which authentication provider was selected. We don't want people accidentally creating multiple accounts for themselves. Longer term we should work on allowing users to sign in with more than one authentication option, which is what #3487 is about.

**Comment by pdurbin** [comment]
> There's also the case of migrating from a Username/Email account to a Shibboleth ("institutional") or OAuth (ORCID, Google, GitHub) account. Perhaps an email should be sent in this case as well

Oh, there's already an issue for this: #3525.
