### ISSUE TITLE
Geoconnect: Filter select box content based on compatibility with other select box choices.

### ISSUE THREAD

**Issue by harvard-dataverse** [IQSS/dataverse#3707]
Tested with election precinct data. Chose Boston admin data, neighborhoods column from file, neighborhoods from layer template and then saved, failed with diff types error: neighborhoods from file is character string, neighborhoods from layer template is numeric. Based on selection name they seem like they'd be the same but cannot tell until save. So would be helpful to limit choices based on what was chosen previously.

**Comment by djbrooke** [comment]
Closing Worldmap/Geoconnect issues as it's no longer supported after the recent Harvard Worldmap migration
