### ISSUE TITLE
Geoconnect: When edit existing map by pressing map it, previous layer attribs are displayed but not listed in select boxes.

### ISSUE THREAD

**Issue by harvard-dataverse** [IQSS/dataverse#3708]
After creating an initial map using tabular data and selecting attributes (animals from election precinct data), editing it again using map it shows the chosen color scheme, download metadata shows the attribute mapping but the select boxes are not populated with the current choice. Viewing on Worldmap does show the selections under legend so the data is preserved and accessible, just not shown.

**Comment by pdurbin** [comment]
The description in this issue is more clear than what's in #3660 but I believe it's a duplicate.

**Comment by djbrooke** [comment]
Closing this, as the migration of worldmap.harvard.edu to new infrastructure is resulting in Geoconnect and Worldmap being able to no longer communicate. We can investigate new Geospatial explore/analysis solutions in the future and will reopen specific issues as needed.
