### ISSUE TITLE
File Download: When a file is missing from the file system and user choses download all, zip file is corrupted.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3712]
See RT 24178 for details.

If a file is missing from the file system and user chooses download all, the zip file is created but it cannot be opened, appears to be corrupted.

**Comment by donsizemore** [comment]
not sure if this belongs here or in a separate issue, but on the Harvard Dataverse we can reproduce this issue in a large dataset (with no files missing as best we know). this particular dataset is unpublished, but i can provide the draft DOI privately.

all files in total should be around 1.5GB, download all in original format sends me a 242MB zipfile (at around 3Mb/s from AWS to UNC where I'm on gigabit) and the zipfile is unreadable:

```
|dls@irss-dls:~/Desktop/corrupt| file dataverse_files.zip 
dataverse_files.zip: Zip archive data, at least v2.0 to extract

|dls@irss-dls:~/Desktop/corrupt| unzip -l dataverse_files.zip 
Archive:  dataverse_files.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of dataverse_files.zip or
        dataverse_files.zip.zip, and cannot find dataverse_files.zip.ZIP, period.
```

**Comment by donsizemore** [comment]
n/m, i had forgotten about :ZipDownloadLimit though i'm now curious what harvard's limit is.

**Comment by pdurbin** [comment]
@donsizemore the best way to find out is to email support@dataverse.harvard.edu but as I was suggesting at http://irclog.iq.harvard.edu/dataverse/2018-11-15#i_78881 perhaps there should be an API that exposes these limits without having to ask.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
