### ISSUE TITLE
Update Migrate scripts for checksumvalue

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#3717]
In recent versions we changed the md5 column of DataFile to checksumvalue, and added checksumtype, + rootdatafile_id.

We need to update the migration scripts to reflect that.

**Comment by scolapasta** [comment]
We should also make the fix for datafilecategories (the dataset_id column is actually storing the datafile_id).

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
