### ISSUE TITLE
Add API Endpoint to Get Latest Version of a File and Add  Latest Version of a File

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3718]
## Need for "Get Latest Version"

A Dataverse user needs to regularly retrieve the latest version of a File for processing.  This file may have been replaced many times. e.g. the DataFile Id is changing

The user needs a "persistent" id to retrieve the latest version

  - Related projects: BARI, BOP, and others that need regular retrieval of a specific DataFile.  e.g. growing corpus of Boston building permits, etc.

### Note on "Add Latest Version"
  - This is the same API endpoint as "File Replace" **except** that the "Root" DataFile ID may be used.  In this case, the file replace will happen on the "latest version" associated with the  "Root" DataFile ID

### Example "Get Latest Version" Endpoint:

  -  Endpoint:   ```api/v1/file/{{ Root DataFile ID }}/latestVersion```
    - Given the ```{{ Root/Original DataFile ID }}``` always retrieve the latest version of the file

Given the data below, the endpoint would be:

  - ```api/v1/file/1/latestVersion```

| DataFile id | Root/Original DataFile ID | Previous DataFile ID |
| --- | --- | --- |
| 1 | 1 | null |
| 5 | 1 | 1 |
| 7 | 1 | 5 |
| 35 | 1 | 7 |

**Comment by pdurbin** [comment]
Development on #4530 seems to be going fine without this. Closing.
