### ISSUE TITLE
Missing files investigation, the sequel

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#3722]
This is a followup to #3668. 
While finalizing the report on the broken file records left over from the D4 upgrade, more recent instances of database entries with no corresponding files were discovered. 

We need to investigate if there is any recognizable pattern, if it's reproducible, etc.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.

**Comment by jggautier** [comment]
Just noting that these missing files are files published in the Harvard Dataverse repository, and that in the Harvard Dataverse GitHub, the following GitHub issues are related:
- https://github.com/IQSS/dataverse.harvard.edu/issues/219
- https://github.com/IQSS/dataverse.harvard.edu/issues/220
- https://github.com/IQSS/dataverse.harvard.edu/issues/37
