### ISSUE TITLE
Some files not showing up in file permission list

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#3726]
In the Manage file permission list, some files are not showing up. This seems to be related to the fact that the same file (same name and md5) was removed and re-added.

Example dataset (if you have manage permissions permissions):
https://dataverse.harvard.edu/permissions-manage-files.xhtml?id=48000

**Comment by mheppler** [comment]
Talked to @sekmiller and @scolapasta about this missing file issue and Gustavo suggested that it was fixed in PR #6402 for issue **_Files with same name break permissions page #6401_**.

>Based on what I'm seeing in my branch, I would say that 6401 and 3726 were fixed by PR 6402. My branch is just extending that fix by filtering out deleted files(by default) and allowing you to see them via a check box on the page.

Sending this to QA to test and close.
