### ISSUE TITLE
Project Metadata from todogroup.org

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#3736]
I'm listening to https://changelog.com/podcast/245 with @willnorris and just mentioned to @mercecrosas that Google recently launched a new site at https://opensource.google.com that includes a directory of their thousands of open source projects.

It caught my attention that one challenge Google has is building this directory is that there is "no consistent, agreed upon method of expressing project metadata in a vendor-neutral way" and Project Metadata has been created to address this problem: https://github.com/todogroup/project-metadata

In the podcast (around 35:00 or so) Will mentioned these language-specific examples that are familiar to us:

- `DESCRIPTION` for R: https://github.com/IQSS/Zelig/blob/master/DESCRIPTION
- `composer.json` for PHP: https://github.com/openscholar/openscholar/blob/SCHOLAR-3.x/openscholar/composer.json
- `package.json` for JavaScript: https://github.com/twbs/bootstrap/blob/v4-dev/package.json

(See also a description of what became Project Metadata at https://groups.google.com/d/msg/todogroup/dyeb7Ye36zs/HSB0ZeqzAgAJ ) 

There's some potential crossover here with the software metadata block @tdilauro recently made available at https://github.com/tdilauro/dataverse-ansible-role/blob/master/roles/dataverse/files/dv-mdblocks/jhuSoftware.tsv as well as https://github.com/CodeMeta/codemeta (pinging @mbjones @acabunoc @arfon and @kaythaney ).

Again, one use case is to power a directory such as the one at https://opensource.google.com/projects but I'm sure there are many others. Here's how the directory looks:

![screen shot 2017-03-30 at 9 21 39 am](https://cloud.githubusercontent.com/assets/21006/24506837/c7be6fd0-152c-11e7-8f6c-485fff59b79c.png)

See also https://github.com/todogroup/project-metadata/blob/master/prior-art.md for some more thinking on this.

Update: From the IQSS perspective, what if there were a common file you could drop into each project's repo that described some metadata about the project no matter if it's in Java (Dataverse), PHP (OpenScholar), R (Zelig), or JavaScript (TwoRavens), etc. including items like:

- project website
- license
- URL of bug tracker
- ...

**Comment by arfon** [comment]
> Update: From the IQSS perspective, what if there were a common file you could drop into each project's repo that described some metadata about the project no matter if it's in Java (Dataverse), PHP (OpenScholar), R (Zelig), or JavaScript (TwoRavens), etc. including items like:

👋 @pdurbin, thanks for the ping. All these ideas resonate for me. I'm no-longer GitHub staff so don't have any particular insights into GitHub's current thinking on this but am bringing in @bkeepers and @mlinksva who may have some thoughts.

Also, in terms of prior art, https://github.com/ewilderj/doap is relevant. w

**Comment by willnorris** [comment]
Thanks.  I just added a Schemas section to https://github.com/todogroup/project-metadata/blob/master/prior-art.md to capture these.

**Comment by pdurbin** [comment]
@arfon @willnorris thanks.

I opened this issue to raise awareness and connect people. Mission accomplished as far as I'm concerned so I'm closing this issue. Everyone should please feel free to continue discussing, of course!

**Comment by pdurbin** [comment]
Yesterday I attended at talk at LibrePlanet about software preservation by @moranegg from @SoftwareHeritage and Katherine Thornton from @Wikidata and I was glad to see they mentioned CodeMeta and other standards:

![sw-schemes](https://user-images.githubusercontent.com/21006/37904965-5a5b6324-30cb-11e8-94dd-059d7b780bc9.png)

They are metadata enthusiasts!

![metadata-enthusiasts](https://user-images.githubusercontent.com/21006/37904994-701d8b4c-30cb-11e8-9c09-37675cc3d675.png)

I told them that once the video of their talk is available, I'd try to spread the word in the Dataverse community. For now, here's a link to their slides: https://commons.wikimedia.org/wiki/File:Pathways-discovery-free.pdf
