### ISSUE TITLE
OAI server: metadataPrefix unknown: Internal server error

### ISSUE THREAD

**Issue by lmaylein** [IQSS/dataverse#3741]
The oai server shows an internal server error when the metadataPrefix parameter contains an unknown value.

**Comment by pdurbin** [comment]
@lmaylein I see what you mean. If I go to the equivalent of https://dataverse.example.edu/oai?verb=ListRecords&metadataPrefix=JUNK on a server running v. 4.6.1 build 69-1ed82ae I'm easily able to reproduce the problem:

![500_internal_server_error_-_harvard_dataverse_-_2017-04-03_07 27 33](https://cloud.githubusercontent.com/assets/21006/24607317/1948fb44-183f-11e7-9689-bb20deb606e0.png)

**Comment by sekmiller** [comment]
This is fixed via https://github.com/IQSS/dataverse/issues/3797
