### ISSUE TITLE
running createsequence.sql against PostgreSQL 8.4 results in ERROR:  language "plpgsql" does not exist

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#3744]
I'm getting the following error on http://phoenix.dataverse.org when I run the new createsequence.sql script:

`psql:doc/sphinx-guides/source/_static/util/createsequence.sql:33: ERROR:  language "plpgsql" does not exist`

To see this error in context: https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-deploy-develop/92/console

I didn't get this error on my Mac laptop running PostgreSQL 9.3.

I'm seeing "A little more research indicates early 8.x releases didn't have plpgsql" at https://bugzilla.mozilla.org/show_bug.cgi?id=1044457#c1 and the phoenix server is running Postgres 8.4 (the RPM is postgresql-server-8.4.20-6.el6.x86_64).

Next steps:

- @pameyer what version of PostgreSQL are you running?
- We may need to remove "The version that ships with RHEL 6 and above is fine" from http://guides.dataverse.org/en/4.6.1/installation/prerequisites.html#postgresql because that version (PostgreSQL 8.4) is apparently not fine for the new `createsequence.sql` script developed for #3654. Not only that, on RHEL/CentOS 6, all the instructions such as `yum install postgresql-server` will need to be replaced since they result in having PostgreSQL 8.4 installed.
- If PostgreSQL 8.4 isn't good enough anymore, we should update the Vagrant scripts to use a version that's new enough and then roll these changes out to the phoenix server.

**Comment by pameyer** [comment]
I'll check.  I'm reasonably sure that this language is supported in postgres 8, but it may not be enabled by default (or may require an additional package in CentOS 6).

**Comment by pdurbin** [comment]
@pameyer thanks! For now I assigned this issue to you and put it in Development at https://waffle.io/IQSS/dataverse . You're only on the hook for the investigation you mentioned. We want to make sure the feature works on your installation. Please keep us posted. 😄

**Comment by pdurbin** [comment]
@pameyer started https://github.com/IQSS/dataverse/compare/3744-seq_pg84 (thanks!) and @landreev and I are hacking on it. I'm done but more to come.

**Comment by pdurbin** [comment]
The pull request is #3751.

**Comment by pdurbin** [comment]
I merged and the error about `plpgsql` not existing is gone on a server running PostgreSQL 8.4 and the `testSequentialNumberAsIdentifierGenerationStyle` test passes: https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-apitest-develop/92/
