### ISSUE TITLE
homepage: 508 / accessiblity follow-up

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3748]
(follow-up for #2634)

---

### Diagnostics

- **Tool used:** https://tenon.io/

- **Results in attached file**: [dataverse-508.xlsx](https://github.com/IQSS/dataverse/files/886199/dataverse-508.xlsx)

### Main issues:

- Links without text can't be used by screen readers (15 instances).  Examples:

      <a href="/dataverse/harvard;jsessionid=504b5a24ba3168c60748ca7618e7?q=amp;types=datasets&amp;sort=dateSort&amp;order=desc&amp;page=1" class="facetTypeChBox facetLink facetSelected">

      <a href="/dataset.xhtml?persistentId=doi:10.7910/DVN/RO8ITP"><span class="icon-dataset text-info"></span>
      </a>
      

  - Fix: "Add text within this link or use `aria-label` to give the link an accessible name."
- Links with improper href construction. (8 instances) Example:

       <a id="j_idt62:j_idt63" href="#" class="ui-commandlink ui-widget" onclick="PrimeFaces.ab({s:&quot;j_idt62:j_idt63&quot;,u:&quot;contactDialog&quot;,onco:function(xhr,status,args){PF('contactForm').show();}});return false;">

**Comment by pdurbin** [comment]
Closing in favor of #2634 which is quite similar.
