### ISSUE TITLE
Dataset Page HTML cleanup (W3 validator errors)

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3750]
### Dataset page diagnostics 4/4/2017

- Validator link: 
  - https://validator.w3.org/nu/?doc=https%3A%2F%2Fdataverse.harvard.edu%2Fdataset.xhtml%3FpersistentId%3Ddoi%3A10.7910%2FDVN1%2F22691

### Results
  - **Errors**: 87
  - **Warnings**: 65

See link above for details.  Many issues are repeated many times.
  - e.g. Of the 65 warnings, 24 are a repeated element id

**Comment by pdurbin** [comment]
This is a good catch but doesn't seem to be a priority. Closing. If someone feels strongly about this, please open a fresh issue. Thanks.

**Comment by mheppler** [comment]
I'll be your huckleberry.

Added a reference to this issue in _Dataset - File UI Improvements #3404_ to make sure it is addressed as part of the UI redesign efforts which are currently underway.
