### ISSUE TITLE
Sign up: Does not validate usernames and partially creates account if invalid

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3752]
See RT 247382, 249657, 250515 for details.

User tried creating an account with username  "First Last" type of format. There was no text on the page indicating that is not allowed and in fact no text message when you try to create a user with that field blank.

The result of trying to create with a space in the username is that it says the account already exists but goes ahead and adds a record to the authenticateduser table but not one to the builtinuser table so you can't actually log in with it.

in 250515, user partially created an account using their email address as username. Like above, form did not report error or succeed when first saved, then when pressed again said it already exists  with just the authenticateduser table completed, not builtinuser.

**Comment by pdurbin** [comment]
Woof. I wonder why this isn't in a single database transaction.

**Comment by pdurbin** [comment]
@ferrys thanks for picking this up. I just left what I hope is a helpful comment about Bean Validation at https://github.com/IQSS/dataverse/commit/5f05023f0b9b0742a74e533fb8f93612dc049dae#commitcomment-22714409

**Comment by jri-sp** [comment]
Hi,

We've been facing this issue today, the user have created an account and all was OK for him but he can't reconnect after because the account wasn't in `builtinuser` table.

In waiting for this to be fixed, with @pdurbin help, I've deleted accounts with the API using this function: [deleteAuthenticatedUserById](https://github.com/IQSS/dataverse/blob/v4.6.2/src/main/java/edu/harvard/iq/dataverse/api/Admin.java#L681)

The command:
`curl -X DELETE  http://localhost:8080/api/admin/authenticatedUsers/id/190`

To find the user id (190 in my case), we could also use API:
`curl  http://localhost:8080/api/admin/authenticatedUsers/username%20with%20spaces`

There are some tables in dataverse Database which can give some infos about your user: `builtinuser`, `authenticateduserlookup`, and `authenticateduser`

Hope this helps!

**Comment by pdurbin** [comment]
@jri-sp thanks for the detailed comment! If anyone is interested in the full conversation, please see http://irclog.iq.harvard.edu/dataverse/2017-06-26 . http://phoenix.dataverse.org/schemaspy/latest/tables/authenticateduserlookup.html is a good resource and we touched on #3614 and #1445.

I'd like to caution anyone reading this that deleting accounts is not currently supported until #1929 is resolved and that you should especially check the `roleassignment` table before attempting to delete an account.

**Comment by djbrooke** [comment]
Moving this to code review as there is an PR. We need a developer to take a look and either push it to QA or identify what needs to be done to get this into code review.

**Comment by pdurbin** [comment]
@ferrys I hope you found my comment at https://github.com/IQSS/dataverse/commit/5f05023f0b9b0742a74e533fb8f93612dc049dae#commitcomment-22714409 helpful. I'm copying it here so @raprasad and @bsilverstein95 can see what I wrote while they're doing code review:

---

[W]e use Bean Validation ( http://beanvalidation.org ) to centralize the validation rules for database fields.

The way you express Bean Validation is as an annotation on the field of an entity. They look like `@ValidateEmail` or `@NotNull` in the example below from `AuthenticatedUser.java`:

```
@ValidateEmail(message = "Please enter a valid email address.")
@NotNull
@Column(nullable = false, unique=true)
private String email;
```

Here's that fix in more context: https://github.com/IQSS/dataverse/commit/ffd1d6ee7b6bf8d518dba4ac239008671e7ab240#commitcomment-22714340

By the way, @scolapasta and @sekmiller gave a very nice talk about our use of Bean Validation at JavaOne a few years back:

- blog post: https://blogs.oracle.com/theaquarium/java-ee-7bean-validation-adoption-at-harvard-university
- slides: https://dataverse.org/presentations/bean-validation-practical-examples-real-world-java-ee-7-application
- video: https://www.youtube.com/watch?v=xg9A3q-fRyo

I hope this helps!
