### ISSUE TITLE
Harvesting client doesn't work in 4.6.1

### ISSUE THREAD

**Issue by 4tikhonov** [IQSS/dataverse#3753]
We're testing harvesting functionality but it seems something wrong goes there.
It shows success but failed import: 
SUCCESS; 0 harvested, 0 deleted, 231 failed.
<img width="1157" alt="screen shot 2017-04-05 at 14 33 43" src="https://cloud.githubusercontent.com/assets/704075/24705611/fe23de9a-1a0c-11e7-8571-d92b29e5682a.png">

I've tried with all OAI-PMH public endpoints from this list it didn't work either:
https://docs.google.com/spreadsheets/d/12cxymvXCqP_kCsLKXQD32go79HBWZ1vU_tdG4kvP5S8/edit#gid=0

**Comment by pdurbin** [comment]
@4tikhonov can you please show us the config of your harvest clients by posting the JSON output from this curl command?

`curl -s -H "X-Dataverse-key: $API_TOKEN" http://localhost:8080/api/harvest/clients`

You're welcome to pretty-print the JSON output like I did at https://groups.google.com/d/msg/dataverse-community/_gLUaA47aOY/uSBY-VImAgAJ so that it looked like this:

```
(dataverse) murphy:dataverse pdurbin$ curl -s -H "X-Dataverse-key: $API_TOKEN" http://localhost:8080/api/harvest/clients | jq .
{
  "status": "OK",
  "data": {
    "harvestingClients": [
      {
        "nickName": "uva",
        "dataverseAlias": "uva",
        "type": "oai",
        "harvestUrl": "https://dataverse.lib.virginia.edu/oai",
        "archiveUrl": "https://dataverse.lib.virginia.edu",
        "archiveDescription": "This Dataset is harvested from our partners. Clicking the link will take you directly to the archival source of the data.",
        "metadataFormat": "oai_dc",
        "set": "UVA-Libra-Data",
        "schedule": "none",
        "status": "inActive",
        "lastHarvest": "Thu Feb 02 15:24:07 EST 2017",
        "lastResult": "SUCCESS",
        "lastSuccessful": "Thu Feb 02 15:24:07 EST 2017",
        "lastNonEmpty": "Thu Feb 02 15:24:07 EST 2017",
        "lastDatasetsHarvested": "9",
        "lastDatasetsDeleted": "0",
        "lastDatasetsFailed": "0"
      }
    ]
  }
}
```

**Comment by 4tikhonov** [comment]
Here we go:

`{"status":"OK","data":{"harvestingClients":[{"nickName":"test","dataverseAlias":"tarki","type":"oai","harvestUrl":"http://dataverse.nl/oai","archiveUrl":"http://dataverse.nl","archiveDescription":"This Dataset is harvested from our partners. Clicking the link will take you directly to the archival source of the data.","metadataFormat":"oai_dc","set":"tilburg_oai","schedule":"none","status":"inActive","lastHarvest":"Wed Apr 05 14:09:31 CEST 2017","lastResult":"SUCCESS","lastSuccessful":"Wed Apr 05 14:09:31 CEST 2017","lastNonEmpty":"N/A","lastDatasetsHarvested":"N/A","lastDatasetsDeleted":"N/A","lastDatasetsFailed":"N/A"},{"nickName":"test4","dataverseAlias":"tarki","type":"oai","harvestUrl":"http://dataverse.scholarsportal.info/oai","archiveUrl":"http://dataverse.scholarsportal.info","archiveDescription":"This Dataset is harvested from our partners. Clicking the link will take you directly to the archival source of the data.","metadataFormat":"oai_dc","set":"Carleton-University-Set","schedule":"none","status":"inActive","lastHarvest":"Wed Apr 05 14:18:33 CEST 2017","lastResult":"SUCCESS","lastSuccessful":"Wed Apr 05 14:18:33 CEST 2017","lastNonEmpty":"N/A","lastDatasetsHarvested":"N/A","lastDatasetsDeleted":"N/A","lastDatasetsFailed":"N/A"},{"nickName":"UU","dataverseAlias":"dans","type":"oai","harvestUrl":"https://dspace.library.uu.nl/oai/request","archiveUrl":"https://dspace.library.uu.nl","archiveDescription":"This Dataset is harvested from our partners. Clicking the link will take you directly to the archival source of the data.","metadataFormat":"oai_dc","set":"com_1874_1","schedule":"none","status":"inActive","lastHarvest":"Tue Mar 28 10:07:04 CEST 2017","lastResult":"SUCCESS","lastSuccessful":"Tue Mar 28 10:07:04 CEST 2017","lastNonEmpty":"N/A","lastDatasetsHarvested":"N/A","lastDatasetsDeleted":"N/A","lastDatasetsFailed":"N/A"},{"nickName":"uvt","dataverseAlias":"tilburg","type":"oai","harvestUrl":"https://pure.uvt.nl/ws/oai","archiveUrl":"https://pure.uvt.nl","archiveDescription":"This Dataset is harvested from our partners. Clicking the link will take you directly to the archival source of the data.","metadataFormat":"nl_didl","set":"publications:all","schedule":"none","status":"inActive","lastHarvest":"Tue Mar 28 10:07:23 CEST 2017","lastResult":"FAILED","lastSuccessful":"N/A","lastNonEmpty":"N/A","lastDatasetsHarvested":"N/A","lastDatasetsDeleted":"N/A","lastDatasetsFailed":"N/A"}]}}`

**Comment by 4tikhonov** [comment]
Hi Phil, any news on this issue?

**Comment by pdurbin** [comment]
@4tikhonov no news. I believe harvesting works fine for us. Anything in server.log that gives a clue?

**Comment by mimatador** [comment]
Hi,
have made the same experience of failure in Dataverse 4.6.2 when using Dataverse as OAI client. In the test I used the dashboard to configure connections to 3 arbitrary selected public OAI Servers from list given in  http://re.cs.uct.ac.za/, but all imports failed with the same Java Exception found in the Glassfish server log :
javax.ejb.EJBException: Failed to find a global identifier in the OAI_DC XML record.
    at edu.harvard.iq.dataverse.api.imports.ImportGenericServiceBean.processOAIDCxml(ImportGenericServiceBean.java:229)

Any help would be very much appreciated.


Thanks in advance,
José

**Comment by pdurbin** [comment]
@mimatador hmm, line 229 is `throw new EJBException("Failed to find a global identifier in the OAI_DC XML record.");` - https://github.com/IQSS/dataverse/blob/v4.6.2/src/main/java/edu/harvard/iq/dataverse/api/imports/ImportGenericServiceBean.java#L229

Are you able to try harvesting using DDI rather than Dublin Core?

**Comment by djbrooke** [comment]
Hi @4tikhonov and @mimatador - is this still an issue? I'm closing this for now, but please comment and reopen if it's still an issue. Thanks!
