### ISSUE TITLE
File preview on the file page only

### ISSUE THREAD

**Issue by TaniaSchlatter** [IQSS/dataverse#3758]
Per discussion in the design meeting 3/30/17, users should preview a file on the file page, in the image window. Thumbnails should link to the file page. 

Recommend that manipulating or exploring a mapped file should happen in the native application (World Map), and not in iframes or other intermediary windows.

Desired behavior by file type (per meeting with Mercè 4/11/17):
- Static files: .pdf & images load a larger image on the file page when clicked. 
- Tabular data/data that can be processed: show variable info and summary stats, Explore button.
- Geospatial data: show preview image on the file page and Map Data button.

**Comment by TaniaSchlatter** [comment]
Mockups are in progress for testing. 

Preview types we know of now:

- image (multiple sub types)
- .pdf
- video
- sound
- HTML
- Hypothesis annotations
- tabular
- shape
- Fits
- text
- .zip
- SBGrid molecular structures

Plan to provide previews of some types, and expand the idea of the external tools framework to generate previews that will be displayed on the file page.

**Comment by TaniaSchlatter** [comment]
Related issues: 
#5746 
#5459 
#5456 ...

**Comment by djbrooke** [comment]
- We should investigate contributing to the preview repos developed by QDR and having them provide a preview that can be displayed on the file page (@scolapasta is following up with @qqmyers )
- On the file page we need to add the infrastructure to display the preview provided by an external tool
- How should we handle guestbook/access restrictions (you can see the whole PDF through preview, so this could be a way to circumvent the usual flow)? Consider showing the on-page preview for files that aren't restricted.

**Comment by scolapasta** [comment]
Discussed with @qqmyers should be straightforward to add a preview mode (by sending additional parameter, possible something like "embedded=true". 

So next step is for us to build up the infrastructure on the Dataverse side (as we can test even without preview being supported by the external tool and confirm we are able to display correctly the external site).

Basically, we need the ability to configure an external tool to be used as the previewer for that file type (should we add a table that has a column for file type and a foreign key to the external tool?*) and then embed that external tool in an iframe on the page. We can also decide on all the logic for when to show preview vs something else (e.g. file has to be public, questions on ToU / guestbook). 

* one question to be figure out is should any external tool be configurable here or should we define a subset of tills that are "previewers", i.e. support the embed tag. Additionally, will there be some tools that are only previewers?

**Comment by qqmyers** [comment]
@scolapasta - wr.t. "configure an external tool to be used as the previewer for that file type " - the tool table has already been extended to have a mimetype, providing a minimal solution. It might be nice to allow a previewer to be registered for multiple mime-types, e.g. the same image and video previewer works for multiple image/video mimetypes and that currently requires registering the same tool multiple times, which might get you back to a mimetype to tool table.

It's an interesting question regarding previewers versus external tools - my guess is that just categorizing by whether a tool supports embedding is enough and that it would be good to avoid trying to make previewers a, for example, read-only subset of tools. Right now, tools can get an apiKey which means that analysis tools can write and an embedded tool could potentially be more than a previewer (e.g. an image previewer that lets you tag faces/record metadata about the image.) Limiting to one previewer per file, or allowing only read-only tools to embed seem like artificial limits (versus allowing site admins to decide which previewers to enable and making tool developers responsible for making a usable GUI if they want to work in embedded mode.).

**Comment by djbrooke** [comment]
Let's wait until the file page is redesigned before approaching this. 

What we need before this is ready for development:

- [ ] The file page redesign to be implemented (#3404)
- [ ] Internal review of the functionality and planned UI
- [ ] Usability review by IQSS team and/or community members

**Comment by mheppler** [comment]
In the dev branch `3758-file-pg-preview`, added `TODO` comments to file.xhtml listing remaining tasks, as outlined in [my comment](https://github.com/IQSS/dataverse/issues/6048#issuecomment-520051095) on the spike issue (#6048). Happy to help define and complete these tasks before, during or after development.

>- configuration setting and render logic for external preview tools
>- maintain WorldMap hard coded feature
>- responsive sizing for iframe
>- noframes option, appropriate role and title attributes [[_ref_](https://webaim.org/techniques/frames/), [_ref_](https://fae.disability.illinois.edu/rulesets/FRAME_2/)]
>- mixed content (HTTPS vs HTTP)
>- lazy loading and/or defering scripts

<img width="1166" alt="Screen Shot 2019-08-09 at 4 03 49 PM" src="https://user-images.githubusercontent.com/687227/62806458-e0d42f00-bac0-11e9-9876-8cf8888f39cb.png">

**Comment by djbrooke** [comment]
For the sprint starting 8/14, we should plan to build on the branch available from the recent spike (#6048) and we should enable a file preview from an external previewer to appear in the desired size under the file metadata tab on the file page. We will also need to take into account the view for those file types where previewers do not exist.

This intermediate step is part of the continued effort to deliver the Dataset and File Redesign (#3404) in stages, that is, it will allow users to take advantage of expanded preview options while at the same time building infrastructure that the file page redesign will use.

While not necessary for completing this, I think it would be nice to pick at least one of the previewers on https://github.com/QualitativeDataRepository/dataverse-previewers (heads up @qqmyers) and make changes so that we can display it on the File Page in the preferred way.

**Comment by djbrooke** [comment]
@sekmiller I know that you temporarily jumped to #6229 (THANK YOU!) but when you're back on this one let me know and I'll be happy to work on the docs while you work on the code in (https://github.com/IQSS/dataverse/tree/3758-file-pg-preview)

**Comment by djbrooke** [comment]
Notes to self re: docs:

- [ ] How to add preview tools
- [ ] Preview tools in finding/using data
- [ ] Preview tools in dataset management (?)
- [ ] Discussion of mixed content
- [ ] tbd

**Comment by djbrooke** [comment]
@sekmiller I'll unassign myself for now, but let me know when it's further along and you want me to take another pass at the docs.

**Comment by sekmiller** [comment]
I'm at a point where I've done as much as I can do with the formatting. @mheppler can you take a look at file.xhtml around lines 435-460 where I've added an inner tab view for external tools that have preview modes? The formatting there needs some improvement. Thanks!

**Comment by TaniaSchlatter** [comment]
This mockup shows planned controls for accessing more than one preview in the future:
<img width="978" alt="Screen Shot 2019-10-16 at 1 43 51 PM" src="https://user-images.githubusercontent.com/15386424/66944734-c5832400-f01b-11e9-9bd4-8785e20cffca.png">

**Comment by pdurbin** [comment]
Yesterday in design standup I gave a demo of the 3758-file-pg-preview branch as of 8dbe327 using PDFs as an example such as http://ec2-34-230-54-112.compute-1.amazonaws.com:8080/file.xhtml?fileId=51&datasetVersionId=5

I pointed out that right now I have to manually update set `haspreviewmode` to true like this `update externaltool set haspreviewmode = true where id = 25;`

This means that a next step for that branch is to support hasPreviewMode in the external tool manifest file (JSON format) and document it on a future version of http://guides.dataverse.org/en/4.17/api/external-tools.html#terminology

I think we should also consider changing the new `haspreviewmode` column to `@Column(nullable = false)` and account for this in the SQL upgrade script in that branch. Basically, any existing tools in the database would automatically be updated by the SQL upgrade script to be "false" for hasPreviewMode since it's a new feature.

**Comment by pdurbin** [comment]
> support hasPreviewMode in the external tool manifest file (JSON format)

I tried this today as of 7118939 and it worked great! Thanks, @sekmiller ! You made working on #6210 easier. There's a new screenshot of how a tabular file looks in the Preview window as of that commit in a new pull request I just made at https://github.com/QualitativeDataRepository/dataverse-previewers/pull/27

**Comment by djbrooke** [comment]
Thanks @sekmiller for taking us through this. Feedback from Design Meeting:

- Change the magnifying glass preview button to another button (there was one that was used previously for Worldmap that may be used here)
- Discussion about whether or not to move the explore button to the bottom of the page, next to the preview. We could consider launch/open something else, but this potentially introduces another concept for users. We decided to add an "Open" button here below the folks.
- We should verify that the preview tools respect terms/restrictions.
- How are the tools ordered? Alpha for now is OK. 

Removing @mheppler from this issue as it's the @sekmiller show for now!

**Comment by djbrooke** [comment]
@sekmiller @TaniaSchlatter yes, we should use the same logic that we use for displaying that download URL. I think the message should be the same for this case and for those file types that do not have previews. "Preview unavailable for this file" is fine with me.

**Comment by mheppler** [comment]
I suggest we hide the tab all together. We don't have an "...unavailable" msg for Download URL or any other feature we hide because of permissions.

If we wanted to spend another half day thinking+developing this, we could consider a workflow that adds a Preview btn to the top of the page, that displays the terms/guestbook when it is clicked, and launches the Preview tool in a new window. This is how the explore tools work.

The fact that a dataset has terms/guestbook is not an uncommon trait. In fact, I'd guess that is becoming more the norm. If these preview tools provide any value, we should make them available to as many people as possible, for as many tools as possible.

With DataTags (#871) in the pipeline, I am sure we will review terms/guestbook in much detail, and review features to improve the over all user experience for working with data files that have terms/guestbook (#1420, #4391, #4978).

**Comment by sekmiller** [comment]
I'm with @mheppler on this one. Displaying a "not available" message will be confusing/annoying to users. Adding a button to take you through the terms/guestbook popup would be a bit more work but probably worth it in the long run.

**Comment by djbrooke** [comment]
@mheppler @sekmiller thanks for the discussion. I don't feel strongly about hiding the tab vs. showing the tab and having a message, but I do think having the message about why a preview is not available is less confusing than just having the preview tab for some files and not others. A message provides us the opportunity to say a few words about why it's not available using a tool tip/popover or words in the message itself. 

That being said, having someone click onto a preview tab (I assume in this case the metadata tab would be the default) with high hopes of seeing a preview and then just getting the message wouldn't be great either. 

We can discuss briefly after standup. I can see the merits and drawbacks of either approach. 

Tagging @TaniaSchlatter to give her a heads up on the discussion.

**Comment by djbrooke** [comment]
Thanks @scolapasta @TaniaSchlatter @mheppler @pdurbin for discussing after standup. At @TaniaSchlatter's suggestion, we said that I'd inventory the cases and then we'd get back together. The cases where a file preview may not be available are:

- Restricted Files
- Datasets that have guestbooks enabled
- Datasets that have terms that need to be agreed to
- Files that are of a type that don't currently have a previewer associated

Note that a file may meet one or more of these criteria. At this time, I don't want to build any workflows for accepting terms, filling out guestbooks, or requesting access to restricted files in the context of a preview. This is a question of scope for now and I understand that we want to do this eventually. 

With this information, I hope we'll make a more informed decision about what to display in this no-preview case.

**Comment by TaniaSchlatter** [comment]
I broke out two types of restricted files in the list above. I'm ready to discuss.

**Comment by djbrooke** [comment]
Thanks @TaniaSchlatter @sekmiller @mheppler for the discussion about this.  We will show no preview tab for the file conditions listed above. On to Code Review!!!

**Comment by pdurbin** [comment]
If anyone is interested in "before" and "after" screenshots, you can find some at https://github.com/IQSS/dataverse-ansible/issues/129

**Comment by pdurbin** [comment]
Here are screenshots of the final implementation:

## screenshot 1

<img width="1208" alt="Screen Shot 2019-11-18 at 11 30 17 AM" src="https://user-images.githubusercontent.com/21006/69070825-dba74a00-09f6-11ea-8ae0-c071f0d61be2.png">

## screenshot 2
<img width="1293" alt="Screen Shot 2019-11-18 at 11 29 54 AM" src="https://user-images.githubusercontent.com/21006/69070826-dc3fe080-09f6-11ea-8f35-224d67a1b312.png">
