### ISSUE TITLE
Map Data button: "Data Not Published" popup doesn't appear on file page (inconsistent with dataset page) and gives no feedback

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#3760]
While investigating #3489 @raprasad and I noticed that the "Map Data" button on the file page does not show the popup for when the dataset isn't published. It should show the same popup, below, that the dataset page shows:

![screen shot 2017-04-10 at 12 43 18 pm](https://cloud.githubusercontent.com/assets/21006/24872385/4bd26db4-1deb-11e7-9832-a35484a0071c.png)

This is as of commit 308f169.

**Comment by pdurbin** [comment]
Here's a screenshot from the demo server. When the dataset hasn't yet been published, clicking "Map Data" does nothing and gives no feedback:

![screen shot 2017-04-11 at 9 09 24 am](https://cloud.githubusercontent.com/assets/21006/24910748/c0276916-1e96-11e7-987d-181015180681.png)

If I knew how to record an animation like @jggautier did at https://github.com/IQSS/dataverse/issues/2252#issuecomment-292797075 I would. 😄

**Comment by TaniaSchlatter** [comment]
Yeah, we need a little lunchtime tech talk from Julian about how to do
that! ;)

- Tania

**Comment by pdurbin** [comment]
We even have a place to document how to use tools like this: http://guides.dataverse.org/en/4.6.1/developers/tools.html 😄

**Comment by pdurbin** [comment]
I made pull request #3779 and dragged this issue to Code Review at https://waffle.io/IQSS/dataverse
