### ISSUE TITLE
Eliminate the "partial/incomplete" ingest error condition.

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#3768]
The ingest process is designed to revert the datafile back to its pre-ingested, original state. There appears to be a failure  scenario where it fails in such a way that the file appears as non-tabular data, but the actual physical file is already replaced by the tab-delimited version. The original is properly preserved, so it's easy to recover manually. But it's super annoying and needs to be fixed. 

Preliminary research suggests that this is caused by an exception in the very last step of the process - the final database save of the extra metadata (datatable, datavariables, etc.)

**Comment by raprasad** [comment]
connects to #3819

**Comment by raprasad** [comment]
passback to check ingest issues: 
![screen shot 2017-05-05 at 12 00 22 pm](https://cloud.githubusercontent.com/assets/1036060/25753716/9f54978e-318a-11e7-9efc-cd8be35238f1.png)

**Comment by landreev** [comment]
There was a problem introduced, between Steve's and my changes, and syncing the code up to the develop branch (that now contains swift and extended DataFileIO). 
Should be working properly now.
