### ISSUE TITLE
Metadata: allow multiples of the same child within a single compound/parent

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#377]
---

Author Name: **Eleni Castro** (@posixeleni)
Original Redmine Issue: 3792, https://redmine.hmdc.harvard.edu/issues/3792
Original Date: 2014-03-28
Original Assignee: Eleni Castro

---

Could be used for compound metadata fields that require multiples of a certain child (e.g., author allow for more than (1) affiliation).

**Comment by posixeleni** [comment]
This is a feature that we now have a business case for: F1000 Research has authors with multiple affiliations (sometimes up to 6) and they will be sending us some examples shortly.

**Comment by posixeleni** [comment]
Example from F1000Research:

>most of the articles have multiple affiliations. Here is an example of a figshare entry with multiple affiliations: http://f1000research.com/articles/4-109/v1.   If there was an autofill option for previously entered affiliations, that would go a long way to making the process quicker.

**Comment by pdurbin** [comment]
Another request for letting authors have multiple affiliations (and a nice reply by @jggautier): https://groups.google.com/g/dataverse-community/c/qgaXlVuI1xU/m/bTI9o-1DBAAJ

**Comment by pdurbin** [comment]
Another request for letting authors have multiple affiliations (and other things), this time by @philippconzett: https://groups.google.com/g/dataverse-community/c/EkxFrQ8j63M/m/xcYgGpyEBgAJ

**Comment by DS-INRA** [comment]
A duplicate issue has been created :
- https://github.com/IQSS/dataverse/issues/10674

However it is much more documented with screenshots. Should we close this one in favor of this new one and re add the links in comment ?

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
