### ISSUE TITLE
Trying to download file from dataset causes 500 error

### ISSUE THREAD

**Issue by gboeing** [IQSS/dataverse#3774]
I'm getting internal server 500 errors through the web interface.

See screenshot below. I click the circled download button, a spinner spins for 60 seconds, disappears, and my console displays the 500 error. I was successfully able to download another file on this page, but not the circled one. I tried multiple browsers and computers.

![](https://i.imgur.com/djL9Rjv.png)

**Comment by pdurbin** [comment]
For more context, please see #3773 and https://help.hmdc.harvard.edu/Ticket/Display.html?id=248690

**Comment by scolapasta** [comment]
@gboeing I just tried this and it worked for me. We did recently change an Apache timeout, so that may have been the cause of the 500 for you. Would you mind retrying and see if you can now download the file?

**Comment by scolapasta** [comment]
A link to the dataset in question: https://dataverse.harvard.edu/dataset.xhtml?https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/CUWWYJ
