### ISSUE TITLE
Trying to edit dataset metadata causes 500 error

### ISSUE THREAD

**Issue by gboeing** [IQSS/dataverse#3775]
I'm getting internal server 500 errors through the web interface. Here I open my dataset, click the "edit" button, then click the "metadata" link (see red arrow in screenshot below). A spinner spins for 60 seconds, disappears, and my console displays the 500 error.

![](https://i.imgur.com/P5DSFtH.png)

See also #3774

**Comment by pdurbin** [comment]
For more context, please see #3773 and https://help.hmdc.harvard.edu/Ticket/Display.html?id=248690

**Comment by scolapasta** [comment]
@gboeing I just tried this and it worked for me. We did recently change an Apache timeout, so that may have been the cause of the 500 for you. Would you mind retrying and see if you can now edit the metadata?

**Comment by scolapasta** [comment]
A link to the dataset in question: https://dataverse.harvard.edu/dataset.xhtml?https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/CUWWYJ
