### ISSUE TITLE
Data Access API doesn't like curl/wget when datasets are unpublished

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#3778]
I wrote a script to call the /api/datasets endpoint for a given version of a dataset ID, parse out the fileID and original filename, then fire off original format download requests via /api/access/datafile (appending "?format=original" and the API token if provided).

Fine, unless the dataset is in draft. I feed the dataset endpoint above a version as ":draft" and get the JSON I expect back. I tell the script to print out the URL it's calling per file, and can copy-paste the URL from the script into Firefox or Chrome and get the original-format file as expected, even when not signed into Dataverse in the browser(s).

When I call via Python or the command line (using curl or wget) I get a 403 Forbidden. I've tested this against 4.6.1 build 69-1ed82ae. A sample URL:
https://dataverse-test.irss.unc.edu/api/access/datafile/7491308?format=original&key=<s3kr3tk3y>

server.log says
[2017-04-19T14:48:58.042-0400] [glassfish 4.1] [WARNING] [] [] [tid: _ThreadID=47 _ThreadName=jk-connector(1)] [timeMillis: 1492627738042] [levelValue: 900] [[
  Response has already been committed, and further write operations are not permitted. This may result in an IllegalStateException being triggered by the underlying application. To avoid this situation, consider adding a Rule `.when(Direction.isInbound().and(Response.isCommitted())).perform(Lifecycle.abort())`, or figure out where the response is being incorrectly committed and correct the bug in the offending code.]]
which may or may not be related.

Why I want this: Thu-Mai wants to be able to create an original format archive of user-uploaded content before the dataset is published, say as a journal editor might want before publication. If you promise not to laugh, the script is at https://github.com/donsizemore/odum/blob/master/dataverse/download_dataset_original_format.py but I've recreated the problem at the command line outside of Python. Everything works in $browser (haven't tried lynx).

Thank you for any advice!

**Comment by donsizemore** [comment]
quotes. slinking away sheepishly.

**Comment by pdurbin** [comment]
Heh. Don't forget to contribute that script, @donsizemore ! 😄
