### ISSUE TITLE
Installation icons on Dataverse metrics map slider aren't resizing

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#3780]
Just noticed that the installation icons on the Dataverse world map (toward the bottom of http://dataverse.org/) aren't being resized for the slider. Just the top left is visible in the frames.

Since the frame is 50x50, we could resize the logos to 50x50 pixels (maybe 46x46 because of the border) before being uploaded to miniverse. But when the frame sizes increase on mouseover, the images won't resize with them.

![worldmap_icons_mis-sized](https://cloud.githubusercontent.com/assets/18374574/25252330/8c94c5e8-25ea-11e7-8978-ef9400735678.gif)

**Comment by jggautier** [comment]
I resized all the icons for now. They just don't resize when the frame does on mouseover.

![screen shot 2017-05-09 at 1 15 37 pm](https://cloud.githubusercontent.com/assets/18374574/25863389/bd060876-34b9-11e7-9bd6-e1a53a6b1112.png)

**Comment by pdurbin** [comment]
@jggautier are you saying you fixed it? Should we close this issue?

Also, the code is over at https://github.com/IQSS/miniverse rather than this repo if anyone is looking for it.

**Comment by jggautier** [comment]
I was thinking done would be restoring how it used to work: The images should resize to fit their frames, including when they get a little bigger when you mouseover them.

**Comment by jggautier** [comment]
Closing this in favor of the older issue in the miniverse github repo: https://github.com/IQSS/miniverse/issues/4
