### ISSUE TITLE
Installer failure with postgresql 9.6

### ISSUE THREAD

**Issue by pjwest** [IQSS/dataverse#3786]
The install script fails when using postgresql 9.6
The solution is to add
,  "9_6", "postgresql-9.1-902.jdbc4.jar"
after line 164 of scripts/installer/install
(solution provided by pdurbin on irc)

**Comment by pdurbin** [comment]
@pjwest thanks for making pull request #3787!

I see you wrote "adding a 9_6 entry worked great for me" at http://irclog.iq.harvard.edu/dataverse/2017-04-24#i_51827 so I'm moving this issue to Code Review at https://waffle.io/IQSS/dataverse
