### ISSUE TITLE
Add datacite metadata in schema.org/JSON-LD format to dataset page via DataCite service

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#3793]
While we'll probably want to cook our own schema.org/JSON-LD support, (in that way, handles and other persistent identifier services would also be supported), a simplified way to get something in sooner would be to use DataCite service. From Martin at DataCite:

> one of the recommendations for repositories in our DCIP repositories preprint is for landing pages to include citation metadata in schema.org/JSON-LD format. I have now (almost) completed two steps that will make this much easier for DataCite members:
> we will soon relaunch DataCite content negotiation with much better support for schema.org. The service is now in beta, and an example with a Dataverse DOI would be https://data.test.datacite.org/application/vnd.schemaorg.ld+json/10.7910/DVN/DA1WTL
> I have written a little javascript that fetches the schema.org metadata and embeds them in a page via a <script> tag: https://github.com/crosscite/doi-metadata-search/blob/master/public/javascripts/schemaorg.js. We do this now at DataCite Search, but every data center could do exactly the same on a landing page. The script gets the DOI from the page via a "DC.identifier" meta tag, another one of our recommendations in the preprint.
> I think the above is a nice story to tell in our webinar in May, and in the data citation course in San DIego in August. And maybe Dataverse is interested in implementing this. An example of richer metadata, including a link to the associated article (relation_type isSupplementTo), would be https://data.test.datacite.org/application/vnd.schemaorg.ld+json/10.5517/CCDC.CSD.CC1NSQCJ.

**Comment by jggautier** [comment]
Related to #2243, being a quicker, less inclusive solution to adding schema.org metadata to most dataset landing pages, #2243

**Comment by jggautier** [comment]
> The script gets the DOI from the page via a "DC.identifier" meta tag

@scolapasta Now that dataset pages will have these meta tags in 4.7, could we use DataCite's service as a first step toward getting metadata in schema.org/JSON-LD format in dataset pages?

**Comment by pdurbin** [comment]
> The service is now in beta, and an example with a Dataverse DOI would be https://data.test.datacite.org/application/vnd.schemaorg.ld+json/10.7910/DVN/DA1WTL

@mfenner the URL above now returns "500 Internal Server Error". Is there a working example somewhere? Thanks!

**Comment by pdurbin** [comment]
@jggautier found https://data.datacite.org/application/vnd.schemaorg.ld+json/10.7910/dvn/icfngt as an example from https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/ICFNGT . Thanks!!

@jggautier also explained that the idea may be to download the JSON above from DataCite and simply present it for download from Dataverse. I'll play around with it.

**Comment by jggautier** [comment]
Thanks Phil! (How did you know to remove the "test" from that URL?)

The idea is to take the JSON from DataCite and plug it into the header of dataset html, like the metatags with the Dublin Core metadata.

**Comment by pdurbin** [comment]
> The idea is to take the JSON from DataCite and plug it into the header of dataset html

Ok, so I **shouldn't** make the "schema.org/JSON-LD" metadata available via the Export button like this which seems to be what #3700 is about:

![screen shot 2017-10-31 at 10 55 52 am](https://user-images.githubusercontent.com/21006/32230723-34957e40-be2a-11e7-9c1e-20665dffba80.png)

What tools or services will consume the JSON in the header of the dataset HTML?

Also, how is this issue different than #2243?

**Comment by pdurbin** [comment]
> What tools or services will consume the JSON in the header of the dataset HTML?

I think I found a good example:

https://search.google.com/structured-data/testing-tool#url=https%3A%2F%2Fsearch.datacite.org%2Fworks%2F10.7910%2Fdvn%2Ficfngt

![screen shot 2017-10-31 at 11 11 00 am](https://user-images.githubusercontent.com/21006/32231545-45d5019c-be2c-11e7-9d72-e33018f4e150.png)

In short, I think I could try to use this as a model: https://search.datacite.org/works/10.7910/dvn/icfngt

**Comment by csarven** [comment]
http://rdf.greggkellogg.net/distiller can probably check for JSON-LD in HTML. See also http://osds.openlinksw.com/

**Comment by borsna** [comment]
> What tools or services will consume the JSON in the header of the dataset HTML?
@pdurbin crawlers like google, bing, yahoo etc will look for it in the header. not sure if having it as an export target is necessary.

Its not different to have it inline (suggested in #2243) or declared as json-ld in the header.

The dateset json-ld example looks like a good example 👍

**Comment by pdurbin** [comment]
@csarven thanks! https://addons.mozilla.org/en-US/firefox/addon/openlink-structured-data-sniff/ seems nice:

![screen shot 2017-10-31 at 12 00 20 pm](https://user-images.githubusercontent.com/21006/32234427-1f12bb06-be33-11e7-8dc5-b5269367f626.png)

**Comment by pdurbin** [comment]
@jggautier I have metadata questions for you. Please see 1b62596 and the screenshot below:

![screen shot 2017-10-31 at 2 57 57 pm](https://user-images.githubusercontent.com/21006/32243558-f85c5b02-be4b-11e7-89bb-d8b27ab2ad19.png)

**Comment by jggautier** [comment]
Thanks for stopping by Phil! From our brief discussion, it sounds like you're not using the DataCite service, which @scolapasta suggested only as an intermediate step, but creating code so that the application can transform the metadata itself, what we wanted in the end. Should we move this discussion to #2243 and close this issue?

**Comment by pdurbin** [comment]
At standup we decided we're doing #2243 rather than this issue. Closing.
