### ISSUE TITLE
Ingest: When ingest completes, page refresh briefly shows broken css/ plaintext.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3794]
Uploading a tabular file, then saving works fine but when ingest completes it refreshes the page and for a short moment shows a broken page, like no css is present. Happens in Chrome, Version 57.0.2987.110 (64-bit) does not happen in FF.

This issue has been around for a while.

**Comment by mheppler** [comment]
Related to **Files tab: When tabular file upload results in "ingest in progress" message, explore button does not appear when complete until manual refresh. #3491**.

**Comment by mheppler** [comment]
Did not see the "broken CSS" issue in my localhost `develop` branch, build d317d23d1bc31ca2d8cc3a0f2c32ab6ad2431112, in Chrome `Version 64.0.3282.186`.

However, I did see that page requires a manual refresh, as reported in #3491.

Also, I agree with the recommended UX improvements suggested in #1798 and #2709. Going to consolidate those issues and comment as appropriate.

**Comment by kcondon** [comment]
Seems ok now.
