### ISSUE TITLE
Documentation: "table of contents" consistency

### ISSUE THREAD

**Issue by dlmurphy** [IQSS/dataverse#3796]
There are currently three different formatting choices we use for dealing with lengthy pages throughout all of our guides. These differing solutions are inconsistently applied, and create confusion when navigating the guides. Here are the three formatting options we've used:

**Option A.** No table of contents. This can be problematic for longer pages. Without any navigational aid, a user can get lost in all of the headings and subheadings.
![optiona](https://cloud.githubusercontent.com/assets/22962740/25445899/af8de4ac-2a7d-11e7-8d5d-8885194091b1.PNG)

**Option B.** A landing page of **only** the table of contents, with subpages displayed in the left navigation bar.
![optionb](https://cloud.githubusercontent.com/assets/22962740/25445986/fd2654e2-2a7d-11e7-8fa1-203d75622516.PNG)

**Option C.** A table of contents box displayed at the top of the page, with the page's full content beneath it.
![optionc](https://cloud.githubusercontent.com/assets/22962740/25446009/13d97f20-2a7e-11e7-9627-5595ebf15f03.PNG)

I believe that we need to choose one format and use it consistently throughout the guides so users don't have to figure out three different ways of navigating them. I believe that option C is the best of the three, but I would like to include this question in a future usability test to get users' input.

**Comment by jggautier** [comment]
Another difference between B and C is that each section in b, the Tabular File Ingest Page, has it's own page, which might be a ideal.

**Comment by dlmurphy** [comment]
On reflection, I believe option C to be the clear best choice for our docs for two reasons:
- Breaking up doc pages into further, granular subpages reduces the user's ability to use ctrl + F to find search terms of interest.
- Providing a table of contents at the top of the page allows for quick orientation on the page and navigation. All headers should be clickable to take users back to the table of contents, allowing for easy navigation

This approach is supported by [this article](http://idratherbewriting.com/2014/01/12/single-page-docs-versus-click-insanity/) on technical writing and its attendant presentation. I'd be comfortable going forward with these changes without having to specifically UX test them.

**Comment by pdurbin** [comment]
I just made pull request #3854 and moved this issue to Code Review at https://waffle.io/IQSS/dataverse

I also set up a Jenkins job that polls the branch behind that pull request every hour and puts an HTML version at http://guides.dataverse.org/en/3796-guides-table-of-contents/

**Comment by pdurbin** [comment]
@dlmurphy and I discussed pull request #3854 as of da2cda4 and he plans to think about and potentially work on moving the content of small pages such as http://guides.dataverse.org/en/3796-guides-table-of-contents/user/tabulardataingest/stata.html into their parent page. Sometimes it's nice to be able to glance at a URL to see where I am but for me `user/tabulardataingest/stata.html` and `user/tabulardataingest.html#stata` are relatively equivalent.

We also discussed how http://guides.dataverse.org/en/3796-guides-table-of-contents/api/native-api.html is quite long and how it would be nice to break up the Native API page into separate pages, similar to how the Search API has room to breathe on its own page. This is out of scope for now and we're already tracking this issue at #2174.

There's sort of question of if long pages are the enemy or not. http://guides.dataverse.org/en/3796-guides-table-of-contents/user/dataset-management.html is long but we're ok with that for now.

**Comment by dlmurphy** [comment]
Re: long pages as enemy, my feeling is that the ideal page is long enough to explore all relevant aspects of one discrete issue. If that means that a page is somewhat long, then that's OK; users can always use in-browser search or the table of contents/page headings to find the particular aspect of that issue that's most relevant to them. In rare cases where a page like this is unreasonably long, I think it's alright to break it up into two pages if there's an intuitive and sensible way to split it conceptually. In my opinion, there's no hard-line rule on this; it's something that needs to be evaluated on a case-by-case basis.

**Comment by dlmurphy** [comment]
(I'm currently working on altering the layout of the Tabular Data File Ingest user guide page to get it to conform with the "Option C" format I laid out in the original post)

**Comment by dlmurphy** [comment]
-Added a label to all within-page tables of contents - **On this Page:**
-Moved within-page tables of contents so they're positioned below the page's introductory text but above the first subheading, much like a Wikipedia page.
-Bolded the "Contents" label on all index pages.
-Made assorted other tiny changes/fixes to get all pages' tables of contents formatted and positioned consistently.

**Comment by pdurbin** [comment]
@dlmurphy "On this page" doesn't make much sense for a PDF or an ePub. Please check out the screenshot below from http://guides.dataverse.org/en/3796-guides-table-of-contents/Dataverse.pdf

![screen shot 2017-05-26 at 9 07 40 am](https://cloud.githubusercontent.com/assets/21006/26495793/f7e559a6-41f2-11e7-827f-44043fff32a9.png)

Note that we don't advertise the fact that we create PDF and ePub versions of the guides, but we'd like to some day, which is why #2148 is still open. I like your idea of adding a word or phrase to explain what the box is. Maybe we could the word "Contents" like Wikipedia does:

![screen shot 2017-05-26 at 9 12 22 am](https://cloud.githubusercontent.com/assets/21006/26495900/752974ba-41f3-11e7-93dd-ea4414df9801.png)

**Comment by pdurbin** [comment]
@dlmurphy I figured out how to define a variable in 2739c72 and changed it everywhere with `ack -l 'On this page:' | xargs perl -i -p -e 's/On this page:/|toctitle|/'`. Please let me know what you think.

Here's where `|toctitle` is defined once in the code: https://github.com/IQSS/dataverse/blob/2739c72663d4562c192e7bed9f167ee41c70170a/doc/sphinx-guides/source/conf.py#L431

Sphinx calls these "substitutions" and here are there docs on it:

> "If you want to use some substitutions for all documents, put them into rst_prolog" -- http://www.sphinx-doc.org/en/stable/rest.html#substitutions

**Comment by pdurbin** [comment]
Oh, and to be clear, I changed "On this page:" to contents to be more PDF-friendly. However, if @dlmurphy or others want a different word or phrase, you are welcome to change it in `conf.py`. Mostly I just wanted it to be defined in a single place so we can easily change it when we start promoting the PDF and ePub versions of the guides.

**Comment by dlmurphy** [comment]
That's a great point about the epub and pdf versions. I'm fine with using "Contents:" as the label.
