### ISSUE TITLE
install script should support non-interactive configuration of options

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#3799]
The existing installation script doesn't support non-interactive configuration of installation options (mail server, postgresql configuration, default contact email address, etc).  This causes friction with automated provisioning tools (or requires them to duplicate logic in the installation script).

Options:
 - installation script as a TODO for providing default values in a text file (possibly with hard-coded defaults if that files is missing); this could be implemented
 - command line arguments for these options could be implemented
 - values from environmental variables could be used, with default values being used if they aren't set

Potentially related to #3390

**Comment by pameyer** [comment]
Bringing previous work on this in sync (mix of option 1 and 2): https://github.com/IQSS/dataverse/tree/3799-noninteractive_installer)

**Comment by pdurbin** [comment]
@pameyer thanks for the pull request at #3803! I took a quick look and here's what I would suggest:

- Invoke the new functionality from Vagrant. Here's the line that you'd change: https://github.com/IQSS/dataverse/blob/v4.6.1/scripts/vagrant/install-dataverse.sh#L13 . This will build confidence in the fix before we move this issue to QA.
- Move the content of `scripts/installer/README-noninteractive.md` to the "develop" branch equivalent of https://github.com/IQSS/dataverse/blob/v4.6.1/doc/sphinx-guides/source/installation/installation-main.rst#running-the-dataverse-installer . This will make the improvements much more visible to the community.

Thanks!!

**Comment by pdurbin** [comment]
I fixed the backticks in 03c0dd0 to be rst style instead of markdown style. This is in pull request #3803

@pameyer you're using `-f` ... are you piggypacking off `--force`? Here's `GetOptions`:

    "f|force" => \$force,

**Comment by pameyer** [comment]
@pdurbin - thanks for the correction.  And it is using the same `--force` / `-f` that was already there.

**Comment by pdurbin** [comment]
@pameyer ok. Thanks. Moving to QA at https://waffle.io/IQSS/dataverse . The pull request is #3803.

**Comment by pdurbin** [comment]
Oh, wait. Not moving to QA yet because I think @landreev wants to take a look. I'm happy with the changes. @kcondon I didn't actually test `vagrant up` but that would be a good thing to test since it exercises the changes in the pull request.

**Comment by pdurbin** [comment]
@landreev and I just talked about this and we're both happy with the pull request (#3803) so I'm moving this to QA. Again, I'd recommend testing `vagrant up`.

**Comment by kcondon** [comment]
Works but does not seem to set HOST_DNS_ADDRESS and does prompt user to hit enter during process:

Command start-domain executed successfully.
Enter admin user name [Enter to accept default]>

**Comment by pameyer** [comment]
Prompting the user does not occur when redirecting stdout and stderr to a file - looks like there are odd interactions between `-y` and perl system / stty.  Will update docs.

**Comment by kcondon** [comment]
OK, all works now.

**Comment by pameyer** [comment]
Re-checked vagrant after the latest changes; no problems.
