### ISSUE TITLE
API for creating datasets fails: Error parsing the POSTed json into a dataverse: Field alias is mandatory

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#3805]
Test scripts creating a native dataset (POST to `/api/dataverses/$dataverse_aliase/datasets`) fail with error message:
{"status":"ERROR","message":"Error parsing the POSTed json into a dataverse: Field alias is mandatory"}

Creation of dataset through UI works; querying dataset API endpoint to check JSON (`api/datasets/:persistentId/?persistentId=doi:$persistentId`) does not show an `alias` field in the JSON returned.  `scripts/api/data/dataset-*json` also don't show an `alias` field.

Observed in df674631f777530e8a47a25633080d653f186736; haven't fully excluded the possibility that this is user error (yet).

**Comment by pdurbin** [comment]
@pameyer sounds like a bug in our API Guide. Confusion over whatever we wrote there. A dataverse has an alias but not dataset does not. Here's an example of creating a dataset from https://github.com/IQSS/dataverse/blob/v4.6.1/scripts/search/tests/create-all-and-test#L10

`curl -X POST -H "Content-type:application/json" -d @scripts/search/tests/data/dataset-finch1.json "http://localhost:8080/api/dataverses/finches/datasets/?key=$FINCHKEY"`

Does that help? In the example above the alias of the dataverse is "finches".

**Comment by pameyer** [comment]
@pdurbin - I don't think this is an API guide issue, because I was able to use the same scripts/JSON files to create datasets with a previous commit (I believe 4.6).  I still have some troubleshooting to do to narrow down which change caused things to stop working (aka - possible bug vs problem on my end).

**Comment by pameyer** [comment]
Additional investigation showed that this was user error (and that @pdurbin was on the right track).  

For future reference, the reported error message occurs with valid JSON - but when the dataverse alias (under which the dataset will be created) is missing from the endpoint URL (in this case, due to typo-ing an environmental variable).

**Comment by pdurbin** [comment]
@pameyer I'd still say that the API Guide could be improved and that that the error message could be more clear.
