### ISSUE TITLE
Installation Guide: The "drop database" section of the "Fresh Reinstall" section is unclear

### ISSUE THREAD

**Issue by ghost** [IQSS/dataverse#3807]
Hi,

I am currently doing the installation on CENTOS 6.8, using postgresql 9.3. See below. I am getting a warning that the database exists, however, there is no such database created. Any database I use, I am getting the same error. 

-----------------------------------

Found Postgres psql command, version 9.3.16.

(We'll be Using psql version 9.3)
Checking if we can talk to Postgres as the admin user...
Yes, we can!

Configuring Postgres Database:
WARNING! Database dvndb already exists!

Please note that you can only use this installer to create a blank,
new and shiny Dataverse database. I.e., you cannot install on top of an
existing one. Please enter a different name for the DVN database.

Press any key to continue, or ctrl-C to exit the installer...

**Comment by pdurbin** [comment]
@lbigramUWI Hi! Can you please open a ticket by emailing support@dataverse.org ?

Does the stuff under http://guides.dataverse.org/en/4.6.1/installation/installation-main.html#fresh-reinstall help, especially "Drop database"?

**Comment by lbigramUWI** [comment]
I tried that, I am using PGAdmin to view the postgres server, there is no database with the same database name I am using for the installation.

**Comment by lbigramUWI** [comment]
The same error happens if I use a remote postgres server address

**Comment by pdurbin** [comment]
@lbigramUWI ok. Hmm. Can you please email support@dataverse.org about this? Thanks!

**Comment by lbigramUWI** [comment]
Okay Thanks, I will.

**Comment by lbigramUWI** [comment]
Hi,

My college helped me solve the problem as follows:

1. Edited the install file and manually entered the server and database name 
2. Created the database and user role on pgAdmin
3. Used ./install --force

This caused the script to override the existing database.

**Comment by pdurbin** [comment]
@lbigramUWI huh. Interesting. I don't see ``--force`` mentioned anywhere at http://guides.dataverse.org/en/4.6.1/installation/installation-main.html so thanks for opening this issue!

**Comment by lbigramUWI** [comment]
Configuring Postgres Database:
WARNING! Database dvndb already exists but --force given... continuing.
User (role) dvnapp already exists;

**Comment by lbigramUWI** [comment]
Apparently, it exists

**Comment by lbigramUWI** [comment]
Oh, Yes it does. there is a $force variable

**Comment by pdurbin** [comment]
Yeah, I think I added it. I don't believe it was ever documented in the Installation Guide, though.

**Comment by lbigramUWI** [comment]
Yep, it wasn't.
