### ISSUE TITLE
more robust directory hierarchy for batch-import loggers

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#3810]
batch import jobs fail if the `$GLASSFISH_HOME/glassfish4/glassfish/domains/domain1/logs/batch-jobs` directory does not exist.  

 - update `batch/util/LoggingUtil.java:getJobLogger()` to check and recursively create if needed
 - check `batch/util/LoggingUtil.java:saveJsonLog()` to see if order of operations is an issue, and if so rewrite.

**Comment by pdurbin** [comment]
@pameyer I'm not in love with the style of curly braces you're using in pull request #3811. Ideally, you'd run the code you added through the standard Netbeans formatter to be in line with the rest of the code. See also http://guides.dataverse.org/en/4.6.1/developers/coding-style.html and #3418 and thanks for the pull request! 😄

**Comment by pdurbin** [comment]
I'm being too picky about curly braces. If the code is good, let's merge it. I don't see any indication of any code review that was done but perhaps it happened when I was on vacation.
