### ISSUE TITLE
Branding - Dataverse®

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#3814]
Add a registered trademark symbol properly applied to the Dataverse® branding (logos, etc.). More detailed information is forthcoming.

Updated information: 

> Add the following somewhere in the terms or bottom of page where the Dataverse® appears: "Dataverse is a trademark of President and Fellows of Harvard College and is registered in the United States."

Confirmed that the locations requiring the registered trademark are:
- Dataverse® Project logo (app footer + [Style Guide](https://github.com/IQSS/dataverse/tree/develop/doc/sphinx-guides/source/style/img) + [dataverse.org](http://dataverse.org/)/[Community Meeting](https://projects.iq.harvard.edu/dcm2017) project sites + [Twitter](https://twitter.com/dataverseorg) + [Geoconnect](https://github.com/IQSS/geoconnect/tree/master/static/images))
- GitHub [README.md](https://github.com/IQSS/dataverse)
- ~New installation level terms of use~ (to be delivered in later phase)

**Comment by mheppler** [comment]
![screen shot 2017-05-05 at 12 31 42 pm](https://cloud.githubusercontent.com/assets/687227/25755626/b333ee6a-3191-11e7-947a-9a3e4de6dd35.png)

**Comment by mheppler** [comment]
Updated registered Dataverse Project logo in Geoconnect. https://github.com/IQSS/geoconnect/commit/e704cee226911984f10dccd383882752a9390b0b

**Comment by mheppler** [comment]
Pointed the Style Guide at the Dataverse Project footer image on the production server.

**Comment by pdurbin** [comment]
Just a heads up to look out for a merge conflict in README.md if pull request #3822 is merged before pull request #3822. I just left a comment about this at https://github.com/IQSS/dataverse/issues/3728#issuecomment-301566281 .
