### ISSUE TITLE
API: dataverses endpoint

### ISSUE THREAD

**Issue by lbigramUWI** [IQSS/dataverse#3817]
Hi,

I am trying to this endpoint: POST http://$SERVER/api/dataverses/$id?key=$apiKey
to create a dataverse for a user which is $id, however, it is returning NULL and the dataverse is not being created.

**Comment by pameyer** [comment]
Hi @lbigramUWI ,

For `/api/dataverses/$id` ; `$id` should be the alias of the dataverse you're trying to create the new dataverse under; not the identifier of the user.  There's a second step for adding the user to the dataverse: `/api/dataverses/$dataverse_alias/assignments`.

**Comment by lbigramUWI** [comment]
Okay, thank you. It is working now.

**Comment by pameyer** [comment]
Great - glad it's working for you.
