### ISSUE TITLE
Publish: Cannot publish specific dataset, apparently due to failure of json export

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3820]
See RT 249185 for details, log files, debugging info.

The upshot: an unpublished draft only dataset in production cannot be published and appears to be failing during json export due to concurrent modification error.

Direct export and publish api calls fail too but metadata api calls that fetch dataset and files metadata in json format work.

**Comment by pdurbin** [comment]
This was under 4.6.1.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
