### ISSUE TITLE
Upgrade miniverse from django 1.9 to 1.10

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3823]
- 1.9 is now considered an insecure version
- List of changes:
  - https://docs.djangoproject.com/en/1.11/releases/1.10/#backwards-incompatible-1-10
  - should be minimal updates--unless used against postgres 9.1 or earlier

**Comment by pameyer** [comment]
1.10 went EOL in Dec 2017.  1.11 is a current django LTS; should be good until Apr 2020 (https://www.djangoproject.com/download/)

**Comment by pdurbin** [comment]
Are we still maintaining miniverse? Vote to close.
