### ISSUE TITLE
Admin Guide: explain Glassfish profiling under troubleshooting section

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#3824]
It might be helpful to add some information to the developer guide about how to configure the dataverse/dev recommended version of glassfish to enable application profiling.

**Comment by pdurbin** [comment]
I'm pretty sure this "just works" when you click "Profile Project" in NetBeans. It looks like this:

![screen shot 2017-05-15 at 2 30 03 pm](https://cloud.githubusercontent.com/assets/21006/26072848/0c5b4b78-397b-11e7-980e-d4f38a433413.png)

@pameyer you seem to be asking how to enable profiling from the command line on a server or whatever.

**Comment by pameyer** [comment]
adding more detail after brief discussion w\ @pdurbin : this was an attempt to run a JMX connection through ssh bastion host; solution is likely using conflicting `localhost` names going through tunnels.  will update if/when I get it working (or close as out-of-scope for this repo).

**Comment by pdurbin** [comment]
@pameyer I think this would be a valuable addition to the new "Troubleshooting" section at http://guides.dataverse.org/en/4.6.1/admin/troubleshooting.html so I hope you get it working! Thanks!

**Comment by pdurbin** [comment]
Over in pull request #3877 @dlmurphy and I agreed to move some of the content about Glassfish to the newish Admin guide under the "Troubleshooting" section.

**Comment by pdurbin** [comment]
@pameyer if there's something reasonable you can add to pull request #3877 before it gets merged, please go ahead.
