### ISSUE TITLE
Add static IP to Geoconnect

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3825]
- requirement for at least one Dataverse installation
- Heroku recycles its dynos (and IP addresses) frequently

**Comment by raprasad** [comment]
One approach, reroute any requests through the quotaguard service

```python
proxies = {
"http": os.environ['QUOTAGUARDSTATIC_URL'],
"https": os.environ['QUOTAGUARDSTATIC_URL']
}

requests.get("callback-rul", proxies=proxies)
````

references:
  - http://docs.python-requests.org/en/master/user/advanced/#proxies
  - https://devcenter.heroku.com/articles/quotaguardstatic#using-with-python-django

**Comment by djbrooke** [comment]
This is needed because the installation is not publicly accessible and is being used as an intranet. We don't have plans to focus our resources on the needs of non-public installations at this time. Closing this.
