### ISSUE TITLE
worldmap connection not configurable

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#3831]
WorldMap preview in dataset.xhtml has link to image at worldmap for non-geospatial file.  Should be configurable and/or disable-able (aka - avoid unnecessary outgoing traffic from installations, and unnecessary load on worldmap server).

**Comment by pdurbin** [comment]
I was able to replicate this on develop as of 51f2ba6 and just created pull request #3837.

What @pameyer was noticing was that you see `                    <a target="_blank"><img src="https://worldmap.harvard.edu/static/theme/img/WorldMap-Logo_26px.png" alt="WorldMap" class="pull-left" style="margin-top:5px;" /></a>` for example when you "view source". He was basically asking, "Why is Dataverse calling out to WorldMap if I haven't configured Geoconnect for my installation of Dataverse?"

I showed @sekmiller quick and he seemed to agree that adding a render wouldn't hurt. I'm basically duplicating the logic lower down in the xhtml.

I'm moving this issue to Code Review at https://waffle.io/IQSS/dataverse

**Comment by pdurbin** [comment]
Once upon a time this modal had render logic on it (back at https://github.com/IQSS/dataverse/blob/0d213adf32b4eb9e70acd0f1b2d7f0cf1ec66290/src/main/webapp/filesFragment.xhtml#L224 ) but it seems to have been removed during some refactoring for #3601 in pull request #3716.

**Comment by raprasad** [comment]
Tested locally.  Looks ok

**Comment by pdurbin** [comment]
@pameyer I just tested this on the phoenix server as of 5f88872 and I thought you said we should expect to see network traffic to Worldmap (downloading an image) even with Datataverse isn't configured to use Geoconnect. Maybe I'm testing wrong and need more coffee. Here's what Firefox shows me:

![screen shot 2017-05-18 at 9 37 32 am](https://cloud.githubusercontent.com/assets/21006/26204809/e29f2086-3bad-11e7-8237-0de207d92ad8.png)

**Comment by pameyer** [comment]
@pdurbin - that's what I was seeing (CSV file instead of PNG; not sure if that would've made a difference).

**Comment by pdurbin** [comment]
@pameyer can you please re-test on http://phoenix.dataverse.org ? I'd like to know if I should push hard for pull request #3837 to be included in 4.6.2 or not. Thanks!
