### ISSUE TITLE
Update documentation to indicate other DOI providers can be configured for doi.baseurlstring

### ISSUE THREAD

**Issue by mdmADA** [IQSS/dataverse#3832]
To reflect that "https://ezid.cdlib.org" and "https://mds.datacite.org" are no longer the only valid values for doi-baseurlstring, update the documentation at:

http://guides.dataverse.org/en/4.6.1/installation/config.html#doi-baseurlstring

The Australian Data Archive (ADA) successfully uses the Australian National Data Service (ANDS) API (a proxy for DataCite) to mint their DOI's through Dataverse.

ANDS supplied the doi-baseurlstring, doi-username and doi-password and Authority parameter values for ADA.

As ADA did for ANDS DOI minting, any DOI provider (and their corresponding DOI configuration parameters) other than DataCite and EZId must be tested with dataverse to establish if the other provider details will work or not.

**Comment by dlmurphy** [comment]
@mdmADA, thanks for bringing this to our attention. I've written a new draft of this documentation that takes this new information into account. I hope it's alright that I borrowed a little from your helpful explanation! Here's what I've got, let me know if this solves the issue:

> As of this writing, "https://ezid.cdlib.org" (EZID) and "https://mds.datacite.org" (DataCite) are the main valid values. 
> 
> While the above two options are recommended, it is also possible on an experimental basis to use a DataCite Client API as a proxy to DataCite. In this case, requests made to the Client API are captured and passed on to DataCite for processing. The application will interact with the Client API exactly as if it were interacting directly with the DataCite API, with the only difference being the change to the base endpoint URL. 
> 
> For example: The Australian Data Archive (ADA) successfully uses the Australian National Data Service (ANDS) API (a proxy for DataCite) to mint their DOIs through Dataverse. ANDS supplied the doi-baseurlstring ("https://researchdata.ands.org.au/api/doi/datacite"), doi-username and doi-password, and Authority parameter values for ADA. As ADA did for ANDS DOI minting, any DOI provider (and their corresponding DOI configuration parameters) other than DataCite and EZID must be tested with Dataverse to establish whether or not it will function properly.

**Comment by mdmADA** [comment]
Hi - I think that looks good but I am not sure about the 'experimental' part. ADA will be using the ANDS API in production so it won't be an experimental at that point...

Thanks!

**Comment by pdurbin** [comment]
@mdmADA that's good feedback. We could easily remove "experimental" after you've gone into production. We labeled the Shibboleth feature as experimental until Harvard Dataverse was using it. Swift/S3 support (#2909) is currently called "experimental" as well.

I could go either way on this. I'm fine with removing "experimental" and I'm fine with keeping it. Mostly, I'm just trying to say that we label some new features as experimental sometimes before they are used in production by somebody. 😄

**Comment by pdurbin** [comment]
@dlmurphy instead of "doi-username and doi-password" it should say "doi.username and doi.password" with dots instead of dashes. Sorry for not catching this earlier when you pinged me in Slack.

Since you're out at a conference, I'd say anyone who feels comfortable making this change should feel free to pick it up. The branch is https://github.com/IQSS/dataverse/tree/3832-docfix-doi-baseurlstring

**Comment by pdurbin** [comment]
I rewrote the text a bit in 9c17874 and ended up removing the part that had the dashes in it. The branch was behind develop so I brought it up to date and made pull request #3843, which I put in QA at https://waffle.io/IQSS/dataverse
