### ISSUE TITLE
Convert User: Cannot convert user from remote to local if preserving email address

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3834]
Found while moving a user from Shib to OAuth,  see RT 248518

If we use shibtolocal or remotetolocal endpoints, if we set the destination email to be the same as the source it fails with an error like:

{"status":"ERROR","message":"User id 1234 could not be converted from Shibboleth to BuiltIn. Details from Exception: java.lang.Exception: User id 1234 (@joeuser) cannot be converted from remote to BuiltIn because the email address joeuser@my.edu is already in use by user id 1234 (@joeuser). "}

**Comment by pdurbin** [comment]
The workaround is to set the email to some unique (possibly random) value temporarily and then to update in in the database to the value you want. Annoyingly, the email address is stored twice for builtin users, in these tables:

- authenticateduser
- builtinuser

**Comment by pdurbin** [comment]
This is coming up in https://help.hmdc.harvard.edu/Ticket/Display.html?id=252460

**Comment by pdurbin** [comment]
Here are steps to follow: http://guides.dataverse.org/en/4.7.1/installation/shibboleth.html#converting-shibboleth-users-to-local

**Comment by pdurbin** [comment]
Here's more of a workaround (for sysadmins running curl):

- When converting the account to builtin, provide an email address that you control and that doesn't already exist in the database.
- Reset the password for that email address.
- Change the email address to the one the user wants.
- Email the user and tell them to use the password reset feature.

We should really just fix this bug. When I wrote this code, I was thinking, "The user is leaving Harvard and they won't have access to their Harvard email account anymore. The user will give us a Gmail account instead."

**Comment by kaitlinnewson** [comment]
It would be great if we didn't have to give the user a new email address in the process of converting. The option to provide it is great, but we are running a multi-institution install and have had recent cases where there is a Shibboleth issue (e.g. an issue with the user at the IdP level) and the user wants to convert back to local, but keep using the same email address.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.

**Comment by pdurbin** [comment]
@orazionelson is having this problem. See https://groups.google.com/g/dataverse-community/c/8AlIL5YhG04/m/JKM0Fth8AQAJ

This is the workaround (for sysadmins running following https://guides.dataverse.org/en/6.7.1/installation/oauth2.html#converting-oauth-users-to-local or https://guides.dataverse.org/en/6.7.1/installation/shibboleth.html#converting-shibboleth-users-to-local ):

- When converting the account to builtin, provide an email address that you control and that doesn't already exist in the database.
- Reset the password for that email address.
- Change the email address to the one the user wants.
- Email the user and tell them to use the password reset feature.

I'm going to re-open this issue. I know auth is changing with the SPA ( https://github.com/IQSS/dataverse-frontend ) but it would be nice to fix this.
