### ISSUE TITLE
Dataset: Adding file tag on unpublished draft from dataset page fails silently.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3840]
Steps to reproduce:
1. create dataset.
2. upload file
3. click checkbox next to file, choose edit, tags
4. select tag, save
5. notice no tag is saved, works from file landing page or edit file metadata, also works once published.

**Comment by pdurbin** [comment]
@kcondon on which commit was this tested and is it a regression in the develop branch? Should this be fixed before we tag 4.6.2?

**Comment by kcondon** [comment]
@pdurbin We sit next to each other so if you have questions we can just chat. Also, any discussion of adding to a release is typically done in stand up and/or at Danny's discretion, right?

**Comment by kcondon** [comment]
The last confirmed time it worked was in commit 51f2ba68a648cc461b27527c47a3510c17fb78d5, currently on build.

**Comment by pdurbin** [comment]
@kcondon ok, so already merged with the develop branch. Thanks!

**Comment by djbrooke** [comment]
Thanks for the discussion about this post-standup. Let's get it fixed in 4.6.2.

**Comment by sekmiller** [comment]
Made several attempts to recreate. Works given the steps enumerated in the ticket.
Tried other permutations, but couldn't get it to fail as described.
Brought back to Kevin. He too, was unable to make error happen.
