### ISSUE TITLE
Locate/Fix 500 Error on the Homepage: java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3846]
Similar to #3665 

---

New Relic is showing over 30,000 errors in the last 7 days.  The errors should be:
 - Identified
 - Corrected/caught
   - not be causing 500s
- For the last week, this has been over 10% of requests so having an overall impact on performance

---

![errors_-_my_application_-_new_relic](https://cloud.githubusercontent.com/assets/1036060/26310228/109a9d3a-3ece-11e7-8b4b-40c5b82b2c76.png)

**Comment by raprasad** [comment]
- Fix steps:
  - Check logs
  - Recreate local urls which produce error.  (e.g. bot created querystrings)
  - Mitigate in code

**Comment by pdurbin** [comment]
@raprasad how is this not a duplicate of #3665 which you fixed in pull request #3691 for the upcoming version, 4.6.2? It's expected that we'll continue to see this error in production, which is running 4.6.1 and doesn't have your fix in place yet.

**Comment by raprasad** [comment]
bummer.  thought this had made it to 4.6.1.  see now that it missed it by a day.  although good in that the issue may already be fixed....

**Comment by pdurbin** [comment]
Yeah, let's hope it's fixed. I think is it. 😄
