### ISSUE TITLE
Dataverse Guides incompatible with Sphinx 1.6.1

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#3848]
Back in #3391 we switched to Sphinx 1.5.1 by switching the build server to the "current" version of Sphinx on NFS (`scl enable python27 "make html SPHINXBUILD=/nfs/tools/lib/python/2.7/current/bin/sphinx-build"`) but that version is now 1.6.1 and doesn't seem to work with our docs.

On my laptop I switched to Sphinx 1.6.1 and I'm getting the error `TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'` that we're seeing on the build server. This is as of 2e919bb on the "develop" branch. Coming up with a solution is a blocker for releasing Dataverse 4.6.2 so I'm adding that milestone.

Here's the output from my laptop using Sphinx 1.6.1:

```
(sphinx161) murphy:sphinx-guides pdurbin$ make clean
rm -rf build/*
(sphinx161) murphy:sphinx-guides pdurbin$ make html
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v1.6.1
making output directory...
loading pickled environment... not yet created
loading intersphinx inventory from http://docs.python.org/objects.inv...
intersphinx inventory has moved: http://docs.python.org/objects.inv -> https://docs.python.org/2/objects.inv
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 63 source files that are out of date
updating environment: 63 added, 0 changed, 0 removed
reading sources... [100%] user/tabulardataingest/supportedformats                                                                   
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [  1%] admin/geoconnect-worldmap                                                                                  
Exception occurred:
  File "/Users/pdurbin/NetBeansProjects/dataverse/doc/sphinx_bootstrap_theme/bootstrap/layout.html", line 40, in top-level template code
    {% set css_files = css_files + theme_css_files + bootswatch_css_custom %}
TypeError: unsupported operand type(s) for +: 'NoneType' and 'list'
The full traceback has been saved in /var/folders/c2/qts2_6zn7cl5h8g8x7r7xcbr0000gn/T/sphinx-err-sHNlww.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Error 1
(sphinx161) murphy:sphinx-guides pdurbin$ 
```

**Comment by pdurbin** [comment]
The bottom of http://guides.dataverse.org/en/4.6.1/ says "Created using Sphinx 1.5.3" so I suppose that was the last known good Sphinx version. I don't love the idea of `/nfs/tools/lib/python/2.7/current/bin/sphinx-build` always shifting under our feet so I'll ask if it's possible to freeze the version or something.

**Comment by pdurbin** [comment]
These are the recent versions of Sphinx available via pip: 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.6b1, 1.6b2, 1.6b3, 1.6.1. It's interesting that version 1.6 isn't available. On my laptop I installed the latest from the 1.5.x series, which is 1.5.6, and it worked fine.

**Comment by pdurbin** [comment]
I'm asking about a Sphinx downgrade at https://help.hmdc.harvard.edu/Ticket/Display.html?id=244853

**Comment by dlmurphy** [comment]
For the record, I've been using sphinx 1.5.5, and it has been fully compatible with Dataverse's guides.

**Comment by pdurbin** [comment]
@kcondon I'm passing this to QA because I believe you plan to switch back to Sphinx 1.1.3 so we can get the docs built, at least. If so we should expect #3391 to resurface. I'll let you know when I hear back at https://help.hmdc.harvard.edu/Ticket/Display.html?id=244853 about getting us on the 1.5.x version of Sphinx.

**Comment by kcondon** [comment]
Reverted to working, older build logic. Likely a bug in Sphinx. Closing.

**Comment by pdurbin** [comment]
I heard back on https://help.hmdc.harvard.edu/Ticket/Display.html?id=244853 and the HMDC Ops team has locked us to 1.5.6 as I requested. Here's the message I just wrote back to them:

> Looks great. At the bottom of http://guides.dataverse.org/en/Handles_doc_fix/ you'll see "Created using Sphinx 1.5.6". Thanks, Brad!
> 
> Here's what I've got in my build script:
> 
> (cd $WORKSPACE/doc/sphinx-guides; make clean; scl enable python27 "make html SPHINXBUILD=/nfs/tools/lib/python/2.7/current/bin/sphinx-build"; scl enable python27 "make latexpdf SPHINXBUILD=/nfs/tools/lib/python/2.7/current/bin/sphinx-build"; cp build/latex/Dataverse.pdf build/html; scl enable python27 "make epub SPHINXBUILD=/nfs/tools/lib/python/2.7/current/bin/sphinx-build"; cp build/epub/Dataverse.epub build/html; cd build/html; tar cvzf /tmp/$TARBALL .; scp /tmp/$TARBALL plaid@docs.dataverse.org:/tmp)

@djbrooke it would be nice to build the 4.6.2 docs with this version of Sphinx rather than Sphinx 1.1.3. Alternatively, we could re-open #3391 to track the work @mheppler and I did for that issue.
