### ISSUE TITLE
Documentation: Document zip file size download limit

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3857]
A partner was trying to increase the zip file size download limit and did not know how. Turns out it is not documented but we do so in production:

An easy way to set this is to run this command from a web server terminal window:
curl -X PUT -d 1000000000 http://localhost:8080/api/admin/settings/:ZipDownloadLimit

See RT 249731 for details.

**Comment by pdurbin** [comment]
Noted in #2944 but good to have a dedicated issue.

**Comment by pdurbin** [comment]
Added in fce05c8.
