### ISSUE TITLE
Dataverse Page - 4.6.2 Regression #2 - Files Facet

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3858]
### Scenario: 

- Local dataverse system running develop as of 5/24/2017
- Root dataverse page.  System has:
  - 1 Dataverse (root)
  - 4 Datasets (these are heavily versioned)
  - 13 files   
- Go to Dataverse page
- Click on Files facet 

### Query count in 4.6.1: ```124```

This is indirectly related to #3852--which involves datasets--not files.

**Comment by pdurbin** [comment]
@raprasad @landreev @sekmiller @kcondon and I met about this issue this afternoon and @sekmiller said he'd take a look.

**Comment by raprasad** [comment]
Note: From May 1st to May 30th, the files facet was used in **approx 6.22% of all pageviews**. 
  - This is across all pages, not only the dataverse page
  - source: Google analytics with url searches on: (```types=file``` or ```:file```) and excluding ```.xhtml```

**Comment by raprasad** [comment]
### Troubleshooting notes

Original test case on branch ```3852-query-600```:

- no changes: **1,763 queries**
  - (slight improvement may be due @landreev improvements on this branch)

## searchServiceBean.java

(a) 1st line removed for api card images: down to **1,617 queries**
  - ```//solrSearchResult.setImageUrl(baseUrl + "/api/access/dvCardImage/" + entityid);```

### (b) 2nd line remove for api card images: down to **_125_ queries**
  - ```//solrSearchResult.setImageUrl(baseUrl + "/api/access/fileCardImage/" + entityid);```

Note: The call to this API endpoint has become much more expensive: ```/api/access/fileCardImage/{ entityID }```

**Comment by raprasad** [comment]
Note: @sekmiller's above commit for #3852 also fixed the issue in this ticket

**Comment by raprasad** [comment]
connects to #3864
