### ISSUE TITLE
When uploading files, have an option to restrict files before clicking save

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#386]
---

Author Name: **Elda Sotiri** (@esotiri)
Original Redmine Issue: 3801, https://redmine.hmdc.harvard.edu/issues/3801
Original Date: 2014-04-02
Original Assignee: Gustavo Durand

---

Sonia suggested this feature. It would be very handy especially for zip files.

**Comment by scolapasta** [comment]
This is a duplicate of #792 (this one is older, but designs were added to #792, so leaving that one as the open issue)

**Comment by kcondon** [comment]
Closing as duplicate.
