### ISSUE TITLE
4.6.2 upgrade instruction typo

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#3884]
Good evening,

A quick search didn't turn up the "releases" github page source, and it's late, and it's a 2-character fix, but I believe step 5 of the 4.6.2 upgrade instructions should read "@./citation.tsv"

Forgive me if this should be reported through some other mechanism.

D

**Comment by pdurbin** [comment]
@donsizemore I think you're right. Right now it says:

`curl http://localhost:8080/api/admin/datasetfield/load -X POST --data-binary
/citation.tsv -H "Content-type: text/tab-separated-values"`

Your proposed fix should work. Or this:

`curl http://localhost:8080/api/admin/datasetfield/load -X POST --data-binary
@citation.tsv -H "Content-type: text/tab-separated-values"`

**Comment by pdurbin** [comment]
@kcondon and I fixed the Markdown in the release notes. Thanks for reporting this @donsizemore !
