### ISSUE TITLE
MyData: clicking files facet hangs/gives error (added in 4.6.2)

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3886]
Clicking on the "mydata" files facet link (not the checkbox) results in a javascript TypeError.

Note: 
   - This is a 4.6.2 error. 
      - I just tested the same data with the 4.6.1 release code and it works.
  - _Likely_, but not guaranteed, it's related to updates in the solr search.  The js parts have not changed.
  - fyi: if fix is data related, automated tests should be added to rest assured--all data available via API

![account_-_root1_dataverse](https://user-images.githubusercontent.com/1036060/26899087-090eda42-4b9c-11e7-8caf-bda2d835e63f.png)

**Comment by raprasad** [comment]
## Error location

File: SolrSearchResult.java, line 478: 
  - ```.add("image_url", getImageUrl())```

## Error reason

- With the 4.6.2 changes ```getImageUrl()``` returns null for File object.  
- For mydata, within the the template (```cards_minimum.html```), an attempt is made to make a replace on the null ```image_url``` string.  This results in an error

## Fix 

- **primary**: Update the ```getImageUrl())``` method in SolrSearchResult.java
- **secondary**: Add a RestAssured Test to make sure that the correct attributes for Dataverses, Datasets, and Files show up in the API
- **secondary** (optional): Fix the template to check for a null before attempting the replace (it looks like test data anyway)

**Comment by oscardssmith** [comment]
What should `getImageURL()` return for a File object?

**Comment by oscardssmith** [comment]
@raprasad any ideas?

**Comment by oscardssmith** [comment]
I can not reproduce this at the demo dataverse (`https://demo.dataverse.org/`). Is there something more specific needed to reproduce?

**Comment by raprasad** [comment]
@oscardssmith : you'll need to have at least 1 file uploaded to produce the error

**Comment by raprasad** [comment]
- quick fix put in to avoid error and show default file icon
- underlying issue moved to new ticket to be prioritized out of backlog: #3932

**Comment by mheppler** [comment]
Also included in this branch is the fix for "File cards in (MY DATA) should link to new File page" as outlined in #3555. Thank you, @raprasad.
