### ISSUE TITLE
MyData: Newly created objects not appearing under MyData but existing objects do.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3887]
Newly created objects (dataverses, datasets) are not appearing under a user's MyData page but existing objects do. This happens in v4.6.2 but only in test environments, not production.

More needs to be done to isolate this but it is worth noting for further investigation.

**Comment by djbrooke** [comment]
Closing in favor of #5343. Will retitle #5343 to reflect test-environment-only issue AFAWK.
