### ISSUE TITLE
I must wait in a long time when I create dataset..

### ISSUE THREAD

**Issue by sincold** [IQSS/dataverse#3888]
The version of Dataverse is v. 4.5.1 build 49-7e5e8c9.
![image](https://user-images.githubusercontent.com/13017958/26969948-1ba1f3fc-4d3a-11e7-9b85-456f888694da.png)

When i click the button of Create dataset , I have to  wait in a long time.  finally,I can get the right page .    

![image](https://user-images.githubusercontent.com/13017958/26969958-2882e2e8-4d3a-11e7-9239-423fbaba37b2.png)

but after I open the page of create dataset in a long time , I click the button of save  ,i have to wait a long time again.

my english is not  very well, but i see  you understand what  i wanna say...   what is wrong with my Dataverse??

**Comment by pdurbin** [comment]
@sincold thank you for reporting this issue and for including the version of Dataverse you are running. I added the "Performance" label.

I have a few questions for you.

How long in seconds (or milliseconds) does it take to create a dataset? (Am I understanding the screenshot correctly that it's taking 4.3 minutes?!?)

How long in seconds (or milliseconds) do you think it should take to create a dataset? (This will help us decide how fast is fast enough.)

Have you tried upgrading to the newest version of Dataverse, which is 4.6.2 as of this writing?

Thanks for using Dataverse!

**Comment by sincold** [comment]
It takes 4.3 minutes to open the page of  Create Dataset, and takes almost same time to save dataset  after opening the page of Create Dataset . However, other pages work very will，such as Create dataverse page.

I have a copy of the slow Dataverse, All the code is same,but data may be different.It only takes few seconds.  So  I guess that it may be solr with wrong ，or postgresql ??

I don't upgrade yet. Because that I have changed some bundle and .xhtml to Chinese.Upgrade may be hard.I will do it ,if upgrade can solve my problem.. 

Thanks for your rely！

**Comment by pdurbin** [comment]
@sincold I'm not sure if upgrading will solve your problem or not. You seem to be saying that you have two installations of Dataverse, a fast one and a slow one. What is the difference between them? You're saying the code is the same but the data is different?

@sincold can you please email support@dataverse.org about this problem? Thanks.

**Comment by djbrooke** [comment]
I'm going to close this one out. 

@sincold - as @pdurbin mentions, please get in touch with us at support@dataverse.org about this!
