### ISSUE TITLE
Cannot remove/delete failed ingest datafile

### ISSUE THREAD

**Issue by mdmADA** [IQSS/dataverse#3893]
A file that failed ingest shows in the UI with the indication that it failed the ingest process.

Trying to delete this "non-ingested" file in order to remove it from the dataset, to try again, fails. 

The (non-existent) datafile remains visible in the dataset's Files tab with no way to remove it.

**Comment by pdurbin** [comment]
@mdmADA files in Dataverse are immutable so the are forever associated with a dataset version. The only exception to this is that you can delete files from a draft of a dataset. Am I right to assume that the dataset has already been published? When you try to delete the file, do you get an error message in the UI? If so, what is it? Is there a stacktrace or anything interesting in server.log? What version of Dataverse are you running?

**Comment by mdmADA** [comment]
Hi Phil - Apologies as I meant to reply earlier.

DV version 4.6.1.

A colleague discovered this issue.

Scenario:
Unpublished dataset
Attempt to ingest data file into the dataset.
Ingest fails. No UI message of any sort.
The file name is in the UI with the glyphicon that indicates the ingest failed.
Try to delete the file. Nothing happens. No UI message of any sort. So that file name will always sit in the UI with no way to get rid of it.

Too many tests were going on at the time to be able to isolate the stack trace to that single file. I will ask my colleague to run through it again tomorrow in order to isolate the issue in the server.log file and see what we get.

Thanks.

**Comment by pdurbin** [comment]
@mdmADA thanks! Please keep me posted!

**Comment by pdurbin** [comment]
@mdmADA hi, have you tried the new "Uningest a File" API endpoint at http://guides.dataverse.org/en/4.9.1/api/native-api.html#uningest-a-file that was developed in pull request #4631 for #3766?

**Comment by djbrooke** [comment]
Hi @mdmADA, I'm going to close out this issue since we weren't able to reproduce it. If you have more information and this is still a priority for you and the ADA team, feel free to leave a comment here and we'll reopen this.

**Comment by mdmADA** [comment]
Hi @djbrooke - thanks for letting us know. It doesn't seem to be a problem for ADA anymore or we have learned to work around such issues. Thanks!
