### ISSUE TITLE
Installation: first "dataverseAdmin" user and root dataverse can't be created

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#3894]
As of 02e5545 on the `develop` branch, the first "dataverseAdmin" user can't be created which means that the root dataverse can't be created. This affects new installations of Dataverse.

**Comment by bsilverstein95** [comment]
After a reinstall and redeploy with a brand new database, I checked the `authenticateduser` table in postgres and I do have a dataverseAdmin user-- but when I try and run the app it can't seem to find any root dataverse.

The user exists in my database, but the root dataverse does not. Is there a way to manually create it without going through the application? I get nothing but 500 errors when I try localhost:8080.

**Comment by pdurbin** [comment]
I just created pull request #3895 and am moving this to code review at https://waffle.io/IQSS/dataverse

**Comment by pdurbin** [comment]
@michbarsinai took a look and said the fix looked ok.
