### ISSUE TITLE
API tests failing due to dropping "Dataverse" from dataverse names

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#3897]
After merging pull request #3880 having to do with branding, one of the REST Assured tests started failing:

```
Expected: 403 Not Authorized - Root Dataverse
  Actual: 403 Not Authorized - Root
```

**Comment by pdurbin** [comment]
I just created pull request #3898 and moved this to code review at https://waffle.io/IQSS/dataverse

**Comment by kcondon** [comment]
Leonid ran tests, confirmed they're working

**Comment by pdurbin** [comment]
Now that the pull request has been merged, all tests on https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-apitest-develop/ are passing again:

![screen shot 2017-06-20 at 4 39 01 pm](https://user-images.githubusercontent.com/21006/27354837-fd77f746-55d6-11e7-8260-51b1b24f3deb.png)
