### ISSUE TITLE
Cleanup: Convert all JPA queries to use `@NamedQuery`

### ISSUE THREAD

**Issue by michbarsinai** [IQSS/dataverse#3903]

**Comment by pdurbin** [comment]
@michbarsinai thanks for opening this ticket. Please help me with #3950 first and then we'll document what you're talking about either under a newer version of http://guides.dataverse.org/en/4.7/developers/coding-style.html or under a new page called "Code Quality" which would include a section on type safety.

The idea is that we don't just change the code. We start by setting expectations with other developers in the dev guide. Then we have something to point at when we say they should use type safe database queries. Please ping me at http://chat.dataverse.org if I'm not being clear enough. Thanks!

**Comment by pdurbin** [comment]
@michbarsinai oh, here are two recent examples of "set expectation" issues I've worked on:

- Set expectations for coding style and code review in dev guide #3418
-  Set testing expectations in Developer Guide and document tools (Jacoco, Coveralls, REST Assured) #3431

**Comment by pdurbin** [comment]
Closing to consolidate into #3950.
