### ISSUE TITLE
improved war deployment docs

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#3907]
question from DVCM - after install in dev env; necessary to rerun after code changes?

`asadmin undeploy dataverse` ; `asasmin deploy /path/to/dataverse.war`

**Comment by pdurbin** [comment]
@pameyer well, the default when using Netbeans is that it automatically re-deploys the war file every time you touch the Java code or the bundle. I let Netbeans do its thing. We could mention this explicitly in the dev guide, I guess.

**Comment by pameyer** [comment]
@pdurbin from the community meeting, it seemed like not everyone was using Netbeans (aka - folks with separate linux VMs).

**Comment by pdurbin** [comment]
@pameyer ok, maybe I can have @ferrys suggest something because she deploys code to a VM in the cloud rather than Glassfish running on her laptop.

**Comment by pdurbin** [comment]
@pameyer please let me know if fa95e12 helps. I'm happy to iterate on what I wrote there until we can close this issue. Thanks!

**Comment by pdurbin** [comment]
@pameyer gave me some better text which I added in dccd9b0
