### ISSUE TITLE
Allow customization of Shibboleth redirects per institution

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#3911]
Odum has received requests for customization of the Shibboleth target attribute, hopefully per institution, on behalf of Carleton College, Emory University, and UNC-CH/Odum itself. The idea might be to parse the entityID from a given Shib user's login data, 1) prefer an existing redirectPage, 2) search for a stored URL or Dataverse alias in say a lookup table, or 3) fail/default to the root Dataverse. I had been bumping this in #1551 but its scope is narrower.

**Comment by pdurbin** [comment]
@donsizemore thanks for discussing this with me and @aivanov100 yesterday. Assuming pull request #3910 for issue #1551 gets merged, I'm hoping we can build on it. It may make sense to add a column to the `shibgroup` table ( http://phoenix.dataverse.org/schemaspy/latest/tables/shibgroup.html ) to associate it with a dataverse, where the alias is stored.

**Comment by pdurbin** [comment]
Back in https://groups.google.com/g/dataverse-community/c/HtbqpVIa-SU/m/xo3zIVSPAQAJ @amberleahey talked about the idea of "sending people to institutional dataverse in hosted Dataverse network".

I believe you can now see this action in the video below where after logging in with University of Ottawa, Chantal says, "I'm going to navigate to my institutional space, the University of Ottawa."

I like @donsizemore's ideas above about being redirected to a specific page based on a click vs. your institution (or wherever) when you log in from the home page.

https://youtu.be/IdymBp0CTd4?t=1515

![Screen Shot 2021-11-05 at 1 54 34 PM](https://user-images.githubusercontent.com/21006/140556414-4c5d5b0d-52e1-4911-bf4c-fa3d9e4668bb.png)

**Comment by amberleahey** [comment]
@pdurbin yes that is correct, and in fact, after login in our installation, users are automatically directed to their institutional Dataverse collection for deposit. Some institutions even setup default roles and permissions for their affiliated researchers, using the institutional groups that are stored and configured in our DV. We use a customized institutional affiliations group workflow (based on DV Groups) at the point of signup/login that supports this. I believe TDL also has something like this. In the case of the video above, normally you wouldn't need to navigate to your institutional DV space using the carousel, but sometimes it is required if you've run a search or logged in and navigated away for example. Anything to improve this navigation to institutional spaces would be of interest as well!

**Comment by pdurbin** [comment]
> after login in our installation, users are automatically directed to their institutional Dataverse collection for deposit

@amberleahey that's cool but I'm assuming this only works because you forked the code? If so, have you considered a pull request? 😄

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
