### ISSUE TITLE
Is a delete file endpoint available?

### ISSUE THREAD

**Issue by leeper** [IQSS/dataverse#3913]
The native API currently allows file update (and now file replace) operations but it doesn't appear to allow file delete. This means that because replace only works on *published* files, it is not possible to update the file contents of a draft dataset without going through the GUI to manually delete the staged file or to delete the entire draft (all files and metadata) through the API. It would be great to be able to delete both unpublished/draft files and to delete files generally from a version (in the way that is currently possible through the GUI).

**Comment by pdurbin** [comment]
@leeper well, as I mentioned in person today, you could use SWORD to delete a file but you're right that there's no "native" API to delete a file. See also #3419 and for all I know #2464 is still a bug. #2222 is also related.

**Comment by pdurbin** [comment]
@leeper thanks for your feedback. I copied your comment into #3419 where the work would be done and am closing this issue.

**Comment by pdurbin** [comment]
On second thought, I like the way this issue is worded and how it's from a real user rather than me so I'm re-opening it in favor of #3419, which I just closed as a duplicate.

**Comment by qqmyers** [comment]
FWIW: #7149 is about adding the ability to replace files in draft versions, so it addresses the original use case above. (working on a PR)

**Comment by janvanmansum** [comment]
I am interested in the last use case "deleting files from a (draft) version similar to the UI". Would it make sense to have a new API endpoint similar to "replace" but which deletes the file from the current draft (and creates a draft if the last version is a published version)?

I imagine calling that endpoint would look like this for persistent IDs. 

```
export API_TOKEN=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
export SERVER_URL=https://demo.dataverse.org
export PERSISTENT_ID=doi:10.5072/FK2/AAA000

curl -H "X-Dataverse-key:$API_TOKEN" -X POST  "$SERVER_URL/api/files/:persistentId/delete?persistentId=$PERSISTENT_ID"
```

And for database IDs:
```
export API_TOKEN=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
export SERVER_URL=https://demo.dataverse.org
export ID=5

curl -H "X-Dataverse-key:$API_TOKEN" -X POST  "$SERVER_URL/api/files/$ID/delete"
```

**Comment by pdurbin** [comment]
@janvanmansum yes, that makes perfect sense. Thanks for leaving a comment here. As I mentioned in the [thread][] on the mailing list, the current work around is to use the SWORD API: http://guides.dataverse.org/en/5.1.1/api/sword.html#delete-a-file-by-database-id

[thread]: https://groups.google.com/g/dataverse-community/c/uR_GVWW7Rco/m/r6UVXVK3AwAJ

**Comment by joenio** [comment]
I'm doing this comment here just to let you know that there is +1 user wanting this feature of deleting files using the Native API.

**Comment by cmbz** [comment]
Yet another user who would also like this capability in the Native API.

**Comment by pallinger** [comment]
I also concur. It would be a useful feature to be able to delete files using the native API.

**Comment by foobarbecue** [comment]
I need to programmatically delete a lot of files now so this would be really helpful! I guess it's time to learn to use SWORD.

**Comment by pdurbin** [comment]
Thanks all. I just added it to the community backlog column in the new global backlog board: https://github.com/orgs/IQSS/projects/34/views/1

However, it's currently at the bottom of that column because I'm prioritizing pull requests. (If the work is already done, we should get those improvements in, right?)

Speaking of pull requests, is anyone out there interested in making one for this issue? If so, please get in touch! 😄
