### ISSUE TITLE
id -> identifier in DV -> DCM API

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#3915]
current DV -> DCM API is using dataset id (aka - database primary key) instead of dataset identifier (filesystem directory / unique value below persistent identifier prefix).

**Comment by pdurbin** [comment]
@pameyer thanks for opening this issue. I was confused about what value you wanted me to pass from Dataverse to the DCM. I assumed you wanted a unique, immutable value for the dataset so I'm passing you the dataset id of the dataset. What you really want is the directory name for the dataset, such as `RJI87V` from `/usr/local/glassfish4/glassfish/domains/domain1/files/10.5072/FK2/RJI87V`. This should be an easy change to make. `RequestRsyncScriptCommand.java` is the place to start looking at the code:

**Comment by pameyer** [comment]
Matches working with https://github.com/sbgrid/data-capture-module/commit/eea3ad96c49a5e017d87833a6ec32da61428df91

**Comment by pameyer** [comment]
Increased debug information output produced by mock DCM for easier QA. QA revealed discrepancies between behavior of scripts for testing DCM and what Dataverse was sending, as well as insufficiently specified DCM API docs. Not detected during initial dev because mock DCM is more strict about inputs than functional DCM.

Debating if it makes more sense to switch the DV end of this to match the DCM test scripts, or update the mock DCM and API docs to reflect what DV is sending.

**Comment by pameyer** [comment]
Insufficiently specified docs do exist; but source of problem was mock DCM attempting to return a more meaningful HTTP status code (202 instead of 200).

https://github.com/sbgrid/data-capture-module/commit/6b28f4067fbaff8a77c8b544343c56bff3c8badc is ready for meaningful QA with f87d90870ffdf4a2fd75145422335bd0d71cec37 (aka - no changes on the dataverse end).

**Comment by pdurbin** [comment]
@pameyer I think it's fine that you put this issue back in QA but while you're thinking about it, I wanted to point out that there's a test called `testCreateDatasetWithDcmDependency` in DatasetsIT that you **could** enable and ensure still passes. I mean you would enable it locally and then revert the change when you're done. You wouldn't change the code at all. This is the test I used to make sure the integration with DCM is/was working properly. Here a handy link to the test: https://github.com/IQSS/dataverse/blob/f87d90870ffdf4a2fd75145422335bd0d71cec37/src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java#L859

**Comment by pameyer** [comment]
@pdurbin thanks for pointing that one out - with my current success rate at running DatasetsIT, it didn't even occur to me to look there.

**Comment by pdurbin** [comment]
@pameyer from Netbeans you can right-click a method and "run focused test method" to run just that one test/method. See https://blogs.oracle.com/geertjan/run-focused-test-method .
