### ISSUE TITLE
User Guide - Hackathon Proofread

### ISSUE THREAD

**Issue by dlmurphy** [IQSS/dataverse#3916]
During the Hackathon, @acme146 did a full proofread of our User Guide. I plan on reviewing her changes and then incorporating them.

See below for changes:
https://github.com/IQSS/dataverse/compare/doc_proofread

**Comment by oscardssmith** [comment]
All changes reasonable.

**Comment by dlmurphy** [comment]
Made a few small changes to these edits. It's looking good. Many thanks to @acme146 for a helpful proofread! She caught several typos and grammatical errors.
