### ISSUE TITLE
API Guide improvements from the 2017 Dataverse Community Meeting

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#3918]
During the 2017 Community Meeting we had some improvements made to the API Guide in pull request #3912.

I'm planning on grabbing those commits by @leeper and making a new branch that I can tweak a bit before making a pull requst.

By the way, the User Guide got some proofreading love in #3916 last week too.

**Comment by pdurbin** [comment]
I made pull request #3920 and moved it to Code Review at https://waffle.io/IQSS/dataverse

**Comment by dlmurphy** [comment]
Currently reviewing Phil's changes to the docs.

Also, a related issue from the hackathon that could be rolled into this branch if someone's interested: #3318. I'd take it on myself, but it's beyond my technical expertise.
