### ISSUE TITLE
My Data page: Add Data button on My Data page

### ISSUE THREAD

**Issue by CCMumma** [IQSS/dataverse#3923]
This is a request from the University of Houston, Institutional users of the Texas Data Repository. They described the issue as follows:

Upon sign-in, the default landing location is the “My Data” page. We would like to allow the user to deposit data immediately upon signing in. However, the “upload data” button is not available here -- a user would need to select a dataverse first and then would see the option to select upload data. Would it be possible to Add data button to the “My Data” page?

**Comment by pdurbin** [comment]
@CCMumma thanks for the suggestion. It reminds me of #3911 by @donsizemore about having users land on the sub-dataverse for their institution, where the "Add Data" button would work. I guess I'm just encouraging us to think about where people should land when they log in and if it should be configurable.

**Comment by CCMumma** [comment]
@pdurbin -- related, because the TDR Dataverses are being managed in a way IQSS didn't envision, with multiple universities with their own policies controlling a top level Institutional Dataverse within the greater TDR, our liaisons wonder why we can't send people directly to their own institutional dataverse when they sign in. So, a user story might also be: "send people from a group to a specific dataverse on login" I've consider that DataverseNL might also be interested in this functionality since their setup is quite like ours.

**Comment by pdurbin** [comment]
@CCMumma yeah. I'm also reminded of "Once affiliated, upon login, users are directed to the identified institutional dataverse, where they will see their own dataverse and datasets, and others from their institution" by @amberleahey in the "Shibboleth integration + deposit workflows" thread she started at https://groups.google.com/d/msg/dataverse-community/HtbqpVIa-SU/xo3zIVSPAQAJ

There are a number of cases where Dataverse is installed to support multiple institutions. If you look at the 2017-05-23 Dataverse Community Call notes I took at https://groups.google.com/d/msg/dataverse-community/RkUqwFjSLv4/Y3nouV6HBgAJ you'll see that Boston College hosts at https://dataverse.harvard.edu/dataverse/bc and giving feedback about how the welcome email doesn't mention Boston College, looks like it comes from Harvard. They want Boston College users to be reassured they're in the right place even though the data is being hosted by Harvard.

**Comment by stevenmce** [comment]
Hi all

We would envision this usage as well in the near future, and I'm guessing there are others too.

Cheers
Steve
Australian Data Archive

Sent from my iPhone

On 21 Jun 2017, at 1:14 am, Philip Durbin <notifications@github.com<mailto:notifications@github.com>> wrote:


@CCMumma<https://github.com/ccmumma> yeah. I'm also reminded of "Once affiliated, upon login, users are directed to the identified institutional dataverse, where they will see their own dataverse and datasets, and others from their institution" by @amberleahey<https://github.com/amberleahey> in the "Shibboleth integration + deposit workflows" thread she started at https://groups.google.com/d/msg/dataverse-community/HtbqpVIa-SU/xo3zIVSPAQAJ

There are a number of cases where Dataverse is installed to support multiple institutions. If you look at the 2017-05-23 Dataverse Community Call notes I took at https://groups.google.com/d/msg/dataverse-community/RkUqwFjSLv4/Y3nouV6HBgAJ you'll see that Boston College hosts at https://dataverse.harvard.edu/dataverse/bc and giving feedback about how the welcome email doesn't mention Boston College, looks like it comes from Harvard. They want Boston College users to be reassured they're in the right place even though the data is being hosted by Harvard.

**Comment by pdurbin** [comment]
Related in the sense that it's an installation of Dataverse that hosts for many institutions:  Dataverse metrics bar at sub-dataverse level #3527

**Comment by pdurbin** [comment]
@CCMumma @stevenmce @amberleahey please take a look at #5615 and consider commenting there on if you like the idea of having an "Add Data" button in the header.

The reason this issue is on my mind is that on today's community call @jmjamison asked about directing people to a specific dataverse after logging in with Shibboleth. As I think about this some more, however, I think Jamie probably wants to route people based on their department. Unlike TDL which has multiple institutions...

![Screen Shot 2019-05-07 at 2 53 35 PM](https://user-images.githubusercontent.com/21006/57325397-eabc4f80-70d7-11e9-8b17-2b87c535933c.png)

... UCLA only has one institution (Identity Provider or IdP from the Shibboleth/SAML perspective):

![Screen Shot 2019-05-07 at 2 54 33 PM](https://user-images.githubusercontent.com/21006/57325449-0aec0e80-70d8-11e9-9a32-4cc1c90c7c24.png)

That said, the desire seems to be similar to what Amber originally wrote about, a desire for users to be directed to a certain dataverse on login. On a related note, when we were discussing #5615 the other day in sprint planning or backlog grooming (I forget which), I asked what I means to have a dataverse. Maybe every user should be able to specify what their "home" dataverse is. And maybe users could be directed to their home dataverse on login. And if users don't have a home dataverse, they could be nudged to create one. 😄

**Comment by amberleahey** [comment]
Hi folks! We have a workflow in place now that reuses Dataverse "affiliation" table to store school names and DV alias for directing users to their appropriate institutional Dataverse for deposit after login (non-Shibb login). 
In investigating Shibb login we found that Dataverse's Groups feature is used to store permissions for Shibb users, and so we'd like to mimic this for non-Shibb schools to direct and permit deposit in institutional Dataverses. If a school assigns permissions to deposit to the group, users affiliated with that school would be authorized to deposit. We haven't had time to dig into how our affiliations custom code could be integrated back into the core - here is the properties file we store locally https://github.com/scholarsportal/dataverse/blob/115c7861c9aaf1014a0d4e7cbca034e45e4e8808/src/main/java/affiliation.properties which is maintained currently by @suniluoft

**Comment by pdurbin** [comment]
@amberleahey interesting. And here's where the Java code was originally modified to make the redirect to a specific dataverse alias happen: https://github.com/scholarsportal/dataverse/commit/0864a85cd25ba925d09a952368a12ebba08ce7ab#diff-1d39072c93fbad15280a92af8019aeac . Thanks!

**Comment by suniluoft** [comment]
1. scholarsportal@0864a85#diff-1d39072c93fbad15280a92af8019aeac was inherited from Kevin Worthington who is no longer with ScholarsPortal.  Digging into the git history a while ago, it looked like Kevin had inherited most of the code from Harvard Dataverse (6 years ago approx).  I'm not able to find the initial git commits from back then.

2. Affiliation branch deployed on Scholars Portal production
https://github.com/scholarsportal/dataverse/commits/dataverse-affiliation-refactoring

3. The major decision we held back on was to replace affiliations in the database (AUTHENTICATED USER, DATAVERSE tables etc) with foreign keys to a new AFFILIATION table. That would mean deviating from the dataverse core code, handle merging of related customisation across releases etc.  Wasn't sure how much more work is involved.

4. Currently affiliations are stored in bundles.  We are trying to decide between keeping the affiliations in bundles or moving them into a new AFFILIATION table.  Probably scale the database table horizontally to support new locales?

**Comment by mheppler** [comment]
@CCMumma @stevenmce @amberleahey @suniluoft, et al...

I am going to close this issue, as we are adding an Add Data link to the navbar of the app and an Add Data btn to the My Data tab of the Account pg.

![Screen Shot 2019-10-22 at 4 07 27 PM](https://user-images.githubusercontent.com/687227/67327546-1b593f80-f4e6-11e9-84f9-3a602104984e.png)

This issue has a lot of back and forth on it, and I hope that if there is an issue or feature request that was added to this issue, and not resolved by issue #5615, then I suggest you open a new issue.
