### ISSUE TITLE
Metadata fields - View fields; Eliminate page jump when toggling show/hide

### ISSUE THREAD

**Issue by CCMumma** [IQSS/dataverse#3924]
v. 4.6.1, Texas Data Repository, Texas A&M University Institutional dataverse reported:

"Safari Version 10.1: When creating a new dataverse, in General Information > Metadata Fields "Choose the metadata fields to use in dataset templates and when adding a dataset to this dataverse." > View fields + set as hidden, required, or optional
If I choose to show/hide particular metadata fields, the page scrolls to the top each time. This is annoying when hiding a number of fields and needing to scroll down each time."

**Comment by qqmyers** [comment]
verified this is still an issue as of ~4.9.3 and is not browser specific... (planning to investigate at some point)
