### ISSUE TITLE
alternative URL Metadata is not displayed as Hyperlinked

### ISSUE THREAD

**Issue by edzale** [IQSS/dataverse#3926]
The metadata field "alternative URL" is not displayed as hyperlinked even when in the citation.tsv file, the field is set as "url", and set as <a href="#VALUE">#VALUE</a> 
We don't have a public interface at the moment but you can see an example here: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/HBXUOT

**Comment by scolapasta** [comment]
This is a duplicate of #3337.
