### ISSUE TITLE
Change robots.txt to allow search engine indexing by non Google

### ISSUE THREAD

**Issue by oscardssmith** [IQSS/dataverse#3928]
Currently our robots.txt file is the following
`User-agent: Googlebot
Allow: /$
Allow: /dataverse.xhtml
Allow: /dataset.xhtml
Disallow: /
Crawl-delay: 20
User-agent: *
Disallow: /`The good part of this is it allows Google to index, the bad news is that no other search engine can. We should probably change it to
`User-agent: Googlebot
Allow: /$
User-agent: DuckDuckBot
Allow: /$
User-agent: Baiduspider
Allow: /$
User-agent: BingBot
Allow: /$
Allow: /dataverse.xhtml
Allow: /dataset.xhtml
Disallow: /
Crawl-delay: 20
User-agent: *
Disallow: /`

**Comment by pdurbin** [comment]
The content of `src/main/webapp/robots.txt` matters less than `doc/sphinx-guides/source/_static/util/robots.txt` which is the version that has no mention of Google and is the one @pameyer added in pull request #3804 with documentation on how to put it into place as you go live.

**Comment by mheppler** [comment]
As part of #5639, @landreev removed (14e36fd22971d6961a0ed05ad550710dba501ec4) all the installation specific settings from `src/main/webapp/robots.txt` and added a comment with a reference to the _Letting Search Engines Crawl Your Installation_ section of the Installation Guide. This was merged as part of the 4.12 release.
