### ISSUE TITLE
mydata: file cards should show correct images or icons -- not just the default file icon

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3932]
(was originally #3886)

---

## For files, getImageUrl() now returns null

File: SolrSearchResult.java, line 478: 
  - ```.add("image_url", getImageUrl())```

## Error reason

- With the 4.6.2 changes ```getImageUrl()``` returns null for File object.  

## Fix 

- **primary**: Update the ```getImageUrl())``` method in SolrSearchResult.java
- **secondary**: Add a RestAssured Test to make sure that the correct attributes for Dataverses, Datasets, and Files show up in the API

**Comment by pdurbin** [comment]
Related: #3714

**Comment by pdurbin** [comment]
Closing in favor of #3714
