### ISSUE TITLE
Missing Dataverse brand from email verify subject

### ISSUE THREAD

**Issue by bsilverstein95** [IQSS/dataverse#3941]
With the rollout of root dataverse branding and modifications to `Bundle.properties` to include dataverse names in outgoing mail, my old friend ConfirmEmail once again needs some patching.

Opening this issue to separate it from #3407 which @pdurbin noted this week ties into a separate bug in the workflow of converting a builtin user account to shibboleth-based. I've already made headway with adjusting `ConfirmEmailServiceBean.java` to appropriately add the root dataverse name, e.g. "_LibraScholar: Verify your email address_" rather than "_{0}: Verify your email address_"

The fix for this (in lieu of fixing #3407 as well) should be slated for 4.7's release.

**Comment by bsilverstein95** [comment]
For reference, note the {0} in this email's subject line. (Ignore the other issue wherein it's also missing a message body as per #3407 )

![brokenemail](https://user-images.githubusercontent.com/16244907/27393240-bfd2059e-5676-11e7-8505-fbdb35171df3.jpg)

**Comment by pdurbin** [comment]
@bsilverstein95 and I just made pull request #3945 and moved it to Code Review at https://waffle.io/IQSS/dataverse

**Comment by kcondon** [comment]
Works, thanks!
