### ISSUE TITLE
On dataset create page, autofill ORCID ID (if available) to "Identifier Scheme" field (authorIdentifierScheme)

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#3944]
Highly related to #3507, but narrower scope.

On create dataset page, users logged in w\ ORCID should have their ORCID autofilled in same places as name and affiliation.

**Comment by djbrooke** [comment]
- Consider reusable logic so that we don't need to code this again when the next ORCID-esque ID provider comes around

**Comment by pdurbin** [comment]
I just made pull request #3966 and am moving this issue to Code Review at https://waffle.io/IQSS/dataverse

**Comment by pdurbin** [comment]
I spoke with @pameyer and @sekmiller about this issue this morning. Here's the "before" screenshot:

![screen shot 2017-06-28 at 12 14 44 pm](https://user-images.githubusercontent.com/21006/27648236-e48cfe9a-5bfb-11e7-8e5f-06e8c4d8ae0e.png)
 

@sekmiller is going to try to figure out how to make "ORCID" selected under "Identifier Scheme" for ORCID users.

@pameyer says he'll probably blow away the ISNI and LCNA values from his database to prevent his users from being confused by schemes they've never heard of. Meanwhile, over in #3169 @Venki18 wants to add "ResearcherID" to the controlled vocabulary. Both of these changes are out of scope but are potential nuggets that @dlmurphy and others might be interested in.

**Comment by pdurbin** [comment]
> make "ORCID" selected under "Identifier Scheme" for ORCID users

@sekmiller fixed this in 8a75be7 and I merged the latest from develop in 2c822f0. Ready for QA.

**Comment by pdurbin** [comment]
When testing, keep in mind this feature only works for ORCID users it is only for them that we persist ORCID IDs.
