### ISSUE TITLE
slightly more semantic metadata elements / dataset fields

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#3946]
It can be useful to have metadata items where the values are identifiers, either globally or unique to a given repository, and have these elements displayed as links - without requiring the user to enter the http(s) URL as free text (and displaying a non-clickable URL).

A few specific examples: PDB, EMDB, PMID (although most articles with a PMID also have a DOI), DOIs for related datasets.

Initial thinking: create a new DatasetFieldType ("FMT"?) where displayFormat accepts things link `<a href="http://www.rcsb.org/pdb/explore/explore.do?structureId=#VALUE>PDB (RCSB) #VALUE</a>` or `<a href="http://emdb-empiar.org/emd-#VALUE">EMDB (PDBe) #VALUE</a>`.

In earlier experiments, I wasn't able to accomplish this with the current system; although it's pretty close.

It may (or may not) make sense to consider switching the existing related dataset, related publication, and/or others to this approach.

**Comment by sekmiller** [comment]
@pameyer How many of these are there likely to be?
Also, what can we do to make sure that the href urls are up to date?
And are there tool tips and/or watermarks for them?

**Comment by sekmiller** [comment]
@pameyer When you say related Dataset and related publication are you expecting a separate field into which the user may enter a persistent id? (That we could then turn into a link by adding formatting.) Or something else?

**Comment by pameyer** [comment]
@sekmiller - correct.  This is different from the current behavior (free text and/or requiring users to type the full URL) of those two.  Changing things in the current block is out of scope for this issue though (and would be something for future discussion - as far as I know no decisions have been made to change those).

**Comment by sekmiller** [comment]
@pameyer After discussing with Gustavo and trying some things out, it doesn't seem like we need a new FieldType. We can put the display format in conjunction with an existing type (probably just TEXT)  for these new DatasetFieldTypes - and as long as the users put in a valid value the links will work.
With respect to PDB, EMDB, PMID are these going to go into their own metadata block or should they be added to an existing one?

**Comment by pameyer** [comment]
I may be wrong, but when I tested this I believe that having a valid link would only work if the user typed the full URL - which means more work for users, and higher complexity in having anything automated trying to use these identifiers.

Should I re-test this, or have you already done that?

**Comment by sekmiller** [comment]
With the code as it is in prod now it won't work for primitive (non-compound) fields, but the changes are minor and I have it working for primitive fields locally for me now. I just checked it into the 3946 branch, if you want to retrieve it and try it.

**Comment by pameyer** [comment]
re-capping the outside github conversation between @sekmiller and me, this is working for TEXTBOX currently (but not TEXT - potentially/probably due to escaping).

**Comment by sekmiller** [comment]
@pameyer I checked in a fix for the issue Raman found so if you want to take a look you can get the latest from the branch.
Also, as I mentioned this morning I did add a field to the DatasetFieldType table that takes in a regExp for validation purposes. It is called validationFormat.  There's no interface for updating this so if you want to play around with it you can run a sql update of something like this:

update datasetfieldtype 
set displayformat = '<a target="_blank" href="http://www.rcsb.org/pdb/explore/explore.do?structureId=#VALUE">PDB (RCSB) #VALUE</a>',
fieldType= 'TEXT',
validationformat='^[a-zA-Z ]{5,5}$'
where id = 73;

Let me know if you have any questions or run into any issues.

**Comment by sekmiller** [comment]
Wait - it converted my query `update datasetfieldtype 
set displayformat = '<a target="_blank" href="http://www.rcsb.org/pdb/explore/explore.do?structureId=#VALUE">PDB (RCSB) #VALUE</a>',
fieldType= 'TEXT',
validationformat='^[a-zA-Z ]{5,5}$'
where id = 73;`

**Comment by pameyer** [comment]
@sekmiller - looks good to me (`update datasetfieldtype set validationformat='^[A-Za-z0-9]{4,4}$' where id=157;` for un-versioned PDB entries).

**Comment by kcondon** [comment]
OK, based on my conversations with Stephen and Gustavo, this is what it does:
Allows a system-wide setting that puts a pre-populated  HTML anchor tag into a specific dataset field where part of the link and title portions of the anchor tag are variable and will be entered by the end user. The resulting completed anchor tag will then be rendered as a real HTML link, displaying the link as the text of the title.

The setting is the displayformat field of the datasetfieldtype table. This is where the partial anchor tag with variable is entered. Currently this is done using SQL by the sysadmin but ultimately would be done using the usual tsv metadatablock update mechanism.

An arbitrary example that sets an anchor tag in the Related Datasets field would be:
update datasetfieldtype 
set displayformat = '<a target="_blank" href="http://www.rcsb.org/pdb/explore/explore.do?structureId=#VALUE">PDB (RCSB) #VALUE</a>',
fieldType= 'TEXT'
where id = 73;
