### ISSUE TITLE
Unread notifications: Remove old notifications?

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#3949]
About 30% of the systems 50,000+ notifications are over half a year old.

   - 9,000+ notifications are over 365 days old
   - 15,000+ notifications are over 180 days old

Should we remove old notifications (say 1 year+ old)?  A rule could be added taking into account the last time the user logged in.

 Another alternative is to remove notifications that point to non-existent objects--objects that have been deleted/removed.

---

Scroll to bottom for current stats: https://services.dataverse.harvard.edu/miniverse/qc/dashboard

**Comment by pdurbin** [comment]
#2892 is related.

@raprasad I can only assume you're talking about the installation of Dataverse at https://dataverse.harvard.edu but this issue almost certainly affects other installations as well. 

Perhaps we could start by supplying a script that deletes old notifications. We would need to document its use in the Admin Guide. There's a "Troubleshooting" section but this feels more like "Care and Feeding". 😄

**Comment by mheppler** [comment]
This has been a bothersome issue, reported by @stevenmce from ADA in the Dataverse Community Meeting, as part of the request access workflow for his installation.

**Comment by pdurbin** [comment]
Closing in favor of #2892.
