### ISSUE TITLE
Navbar: User Guide link does not reflect updated version.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3951]
The guides link in the navbar was changed in v4.7 to restructure what was offered -show only User Guide as an entry point to entire guide structure to allow for preferences of other installations.

In doing so, it seems it has lost the ability to update the doc path to the correct version. We've bumped the version to 4.7 but still references 4.6.2

**Comment by pdurbin** [comment]
I deployed 3947-update-version as of 91b6526 on https://dev1.dataverse.org and I can't reproduce the problem. Here's a screenshot (note the arrow):

![screen shot 2017-06-22 at 3 22 53 pm](https://user-images.githubusercontent.com/21006/27452307-2010e03a-5760-11e7-8918-a1783b6a0578.png)

**Comment by mheppler** [comment]
That is also what I saw when building the latest `3947-update-version` code @pdurbin @kcondon.

**Comment by kcondon** [comment]
false alarm. We added a new setting to allow installations to use their own version scheme by means of an override:
:GuidesVersion
Set :GuidesVersion to override the version number in the URL of guides. For example, rather than http://guides.dataverse.org/en/4.6/user/account.html the version is overriden to http://guides.dataverse.org/en/1234-new-feature/user/account.html in the example below:

curl -X PUT -d 1234-new-feature http://localhost:8080/api/admin/settings/:GuidesVersion
