### ISSUE TITLE
opaque element IDs/names on create dataset page

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#3958]
Input elements on the create dataset page (and probably edit metadata page, but I haven't checked there) typically have HTML IDs/names along the lines of `datasetForm:j_idt371:0:j_idt374:0:j_idt381:0:j_idt383:0:inputText`.  This complicates testing, and may have implications for accessibility.

Haven't investigated yet - possible that this is required by primefaces.

**Comment by pameyer** [comment]
Also observed on the page for creating dataset templates.

**Comment by pdurbin** [comment]
See also https://github.com/IQSS/dataverse-helper-scripts/blob/e72145f1d611ec1fd9bd64cdd313494f6c013fda/system-thoughts/issues-with-primefaces.md#example-2-primefaces-input-boxes-for-metadata
