### ISSUE TITLE
increased flexibility in test API key

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#3959]
The API key used for integration tests is currently hard-coded.  In some cases, it may be desirable to run integration tests in an environment as similar to production as possible (and where the hard-coded key isn't configured).  Initial thinking was to check an environmental variable, and if not set fall back to the hard-coded value.  Discussed briefly with @pdurbin , he suggested that passing these values through a command line argument (similar to how the test application server is currently specified) would be preferable.

**Comment by pdurbin** [comment]
@pameyer would the fix be similar to the one in pull request #5201?
