### ISSUE TITLE
Navigation: Unexpected back button session issues.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3965]
Need to revisit caching and button logic for back button operation.

**Comment by pdurbin** [comment]
Huh, I though we fixed that in #2841.

**Comment by kcondon** [comment]
Nope, as I said, This page is not directly accessible if I'm not logged in though, which is what #2841 was about. I rather keep the chatter on tickets down to just new info though.

**Comment by raprasad** [comment]
references:
  - https://stackoverflow.com/questions/10305718/avoid-back-button-on-jsf-web-application
  - http://javaannals.blogspot.com/2013/09/avoid-browser-back-button-after-user.html

**Comment by oscardssmith** [comment]
After about a day of research, I believe that the correct solution is to split DataverseUserPage into two pages, one that deals with the creation of new users (SignUpPage), and the current one. This will fix the problem, and allow us to simplify the logic of a very complex page.

**Comment by pameyer** [comment]
headers not blocked by apache; fix works for me w\ firefox and apache in front of glassfish.

**Comment by djbrooke** [comment]
Hey @oscardssmith - I saw that @pameyer had some feedback about this one. We should get this one across the line before picking up the complex password stuff.

**Comment by matthew-a-dunlap** [comment]
FWIW I have not had time yet to review this, as I am doing 4053.

**Comment by oscardssmith** [comment]
@djbrooke  I've left it to @landreev  who said he'd look at it, as I don't have Safari, so testing any fix will require pushing, and getting someone else to test.
