### ISSUE TITLE
Add term to Titulo controlled vocabulary in custom Digaai metadata block

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#3972]
Folks from Digaai have asked us to add to their custom metadata block the term "O Novo Mundo" to the "Titulo" controlled vocabulary. This request is also in RT: https://help.hmdc.harvard.edu/Ticket/Display.html?id=250446&results=d48486a8cbf29e472a94f25d6240468c

**Comment by pdurbin** [comment]
Here: https://github.com/IQSS/dataverse/blob/v4.7/scripts/api/data/metadatablocks/customDigaai.tsv#L9

**Comment by pdurbin** [comment]
Looks good. Moved to QA.
