### ISSUE TITLE
file permissions: remove access feature is not working

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#3978]
Tried to remove access for files for one user, no success message. Tried to refresh to check if feature works, and user still visible on file access page.

**Comment by mheppler** [comment]
@sbarbosadataverse this an oldie, but a goodie. It appears to be working for me locally in the 4.12 `develop` branch (see attached). Please confirm if this is still a problem for you, and if so, close the issue or provide more details.

![Screen Shot 2019-04-16 at 2 38 44 PM](https://user-images.githubusercontent.com/687227/56235459-80266f80-6055-11e9-8829-2179b423fdaa.png)

**Comment by mryder2** [comment]
Michelle tested this issue in Demo Dataverse.  This feature appears to be working.

**Comment by mryder2** [comment]
Hi Mike, I was not able to to duplicate this issue in the Demo Dataverse. Sonia said to leave the 'closing' of this issue to you. 

Cheers,
Michelle

**Comment by mheppler** [comment]
@mryder2 with pleasure. Thank you for your efforts to replicate.

@pdurbin clicking the close issue button is less effort than applying a vote to close label.
