### ISSUE TITLE
A bug in SPSS SAV/POR file reader: missing value-label tables for non-key variables

### ISSUE THREAD

**Issue by akio-sone** [IQSS/dataverse#3987]
The following line in SAVFileReader#assignValueLabels (line 1708) and PORFileReader#assignValueLabels (line 1663) methods fails to wrap varName with valueVariableMappingTable.get(): 

            Map<String, String> valueLabelPairs = valueLabelTable.get(varName);

Consequently, a given value-label table is saved for the key (1st occurrence) variable only, non-key variables were left out. 
Because this bug has existed since these class files were initially committed in 2014, all 4.X versions are affected.

The above bug yields the following DDI fragment where variable Q2_1 is the key varible and Q2_2 and Q2_3 are non-key variables:

~~~ xml
<var ID="v1495" name="Q2_1" intrvl="discrete">
<location fileid="f217329"/>
<labl level="variable">The Federal Reserve System is oversteppi</labl>
<sumStat type="stdev">0.41914870953901723</sumStat>
<sumStat type="invd">1.0</sumStat>
<sumStat type="max">3.0</sumStat>
<sumStat type="min">1.0</sumStat>
<sumStat type="medn">2.0</sumStat>
<sumStat type="mode">.</sumStat>
<sumStat type="vald">724.0</sumStat>
<sumStat type="mean">1.8825966850828728</sumStat>
<catgry>
<catValu>2</catValu>
<labl level="category">Disagree</labl>
</catgry>
<catgry>
<catValu>1</catValu>
<labl level="category">Agree</labl>
</catgry>
<catgry>
<catValu>3</catValu>
<labl level="category">Not Sure</labl>
</catgry>
<varFormat type="numeric"/>
<notes subject="Universal Numeric Fingerprint" level="variable" type="Dataverse:UNF">UNF:6:4z1SnncAvn6u9uR5JesI4Q==</notes>
</var>
<var ID="v1561" name="Q2_2" intrvl="discrete">
<location fileid="f217329"/>
<labl level="variable">If our correspondents were to establish</labl>
<sumStat type="mean">1.4365411436541144</sumStat>
<sumStat type="mode">.</sumStat>
<sumStat type="vald">717.0</sumStat>
<sumStat type="medn">1.0</sumStat>
<sumStat type="invd">8.0</sumStat>
<sumStat type="stdev">0.5841990912890344</sumStat>
<sumStat type="max">3.0</sumStat>
<sumStat type="min">1.0</sumStat>
<varFormat type="numeric"/>
<notes subject="Universal Numeric Fingerprint" level="variable" type="Dataverse:UNF">UNF:6:xFdCiHHU9vq4XGuOk4DqRw==</notes>
</var>
<var ID="v1623" name="Q2_3" intrvl="discrete">
<location fileid="f217329"/>
<labl level="variable">Many correspondents still rely on entert</labl>
<sumStat type="max">3.0</sumStat>
<sumStat type="min">1.0</sumStat>
<sumStat type="mean">1.7168508287292819</sumStat>
<sumStat type="medn">2.0</sumStat>
<sumStat type="vald">724.0</sumStat>
<sumStat type="invd">1.0</sumStat>
<sumStat type="stdev">0.5002826585405282</sumStat>
<sumStat type="mode">.</sumStat>
<varFormat type="numeric"/>
<notes subject="Universal Numeric Fingerprint" level="variable" type="Dataverse:UNF">UNF:6:XMNSX1eepwwrM8m2JGVcxw==</notes>
</var>
~~~

Please note: it seems SPSS does not always (consistently) find/eliminate duplicated value-label sets for variables in a data set; frequently the same value-label set is assigned to multiple variables separately without elimination.  Such the case is immune from the above bug.

**Comment by jonc1438** [comment]
This is related to the closed ticket #3982 from yesterday.

**Comment by akio-sone** [comment]
The above pull request (#4019) has been submitted; Please note, due to my NetBeans settings, besides the relevant one-line change, unused import statements had been removed from the two modified class files.

**Comment by landreev** [comment]
This is in QA now. 
@kcondon I left some test files, .sav and .por in /usr/local/dvn-admin/3987_test_spss/ on dvn-build.hmdc.harvard.edu. 

The fixes in this PR are super straightforward, literally 1 line fix in both the SPSS/SAV and SPSS/POR ingest plugins. I ran tests on production SPSS files and confirmed that the fixed plugins produce value categories that were not present before. 

Going forward, I'm opening 2 new issues: 

1) To add tests for the SPSS plugins, similarly to the unit tests already added for the CSV ingest; that would detect it if any code modifications result in changes in the ingest results. 

2) To investigate/develop a fix for the existing data variables affected by the bug. 
To clarify what it is that is missing: 
The bug did not affect the integrity of the data as far as the UNF is concerned (it did not affect how the actual data values were stored). 
But some variables are missing value categories. I.e., some factors (categorical value vectors) became simple vectors. 
As a simple example, we may now have a numerical vector of 0s and 1s. Where in the original SPSS file it was a vector of 0s and 1s, *that were supposed to represent the categories "MALE" and "FEMALE", respectively*). It should be relatively easy, to go through the existing tabular files produced from POR and SAV files in 4.0, identify such missing categories, and add them to the existing variable metadata. Once again, the UNFs of the affected variables and files would stay the same, the tabular files would stay the same - but we'll be able to add a bit of extra info to the variable metadata. 

I feel like this fixer code would be fairly easy to produce. But I would need to confirm that. Also, I cannot immediately tell how many files we have in production that are actually affected by this.
