### ISSUE TITLE
1 dataset and its 21 files in Metadata Source called "Harvard"

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#3988]
In Harvard Dataverse, 1 dataset and its 21 files are in a third Metadata Source called "Harvard". First time I've seen this metadata source. The dataset is in a dataverse in Harvard Dataverse. Its one dataset was created October 4, 2016 and updated (files were removed and added) June 29, 2017. 

<img width="965" alt="screen shot 2017-07-08 at 8 34 35 pm" src="https://user-images.githubusercontent.com/18374574/27990217-6333572a-641d-11e7-95b1-bb0dd187e66f.png">

**Comment by scolapasta** [comment]
I reindexed that dataset and it should be fixed.

(I think this may have happened when we upgrading and dropped "Dataverse" as always being appended to name, but then added it manually back via script)
