### ISSUE TITLE
Parameters issue in display on production

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#3993]
Keyword parameter issues in facets:

clicked on keywords in attached dataset and keywords is long, and got the error. I can split this up, but not sure if this is a bug or if there are limitations in keyword field characters?
<img width="1866" alt="screen shot 2017-07-11 at 3 34 11 pm" src="https://user-images.githubusercontent.com/8322346/28086927-af61a524-664e-11e7-8e16-ceddbd601ccd.png">

**Comment by mheppler** [comment]
@sbarbosadataverse I am closing this issue, and consolidating it with other related issues in an old issue that I have retitled as _**Search: Accented characters, ampersands, negative numbers and other special characters #820**_.

If you have any further information about this bug or other "special character" related search issues, please add your comment there.
