### ISSUE TITLE
Broken unit test in AuthenticatedUserTest

### ISSUE THREAD

**Issue by bsilverstein95** [IQSS/dataverse#3994]
Some folks are getting build failures due to `AuthenticatedUserTest.java` in develop based on some very simple unit tests I wrote a while back on getters and setters from `AuthenticatedUser.java`. Not sure how the broken version of `testGetName()` ended up in develop (probably a regression from another branch being merged, who knows).

Planning to push a fix for this ASAP.

**Comment by pdurbin** [comment]
Pull request #3995 looks good so I moved this issue to QA. This is blocking me from running automated tests per http://guides.dataverse.org/en/4.7/developers/testing.html#the-phoenix-server because the first step of building the war file fails as seen at https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-build-develop/125/console as of 0252178:

![screen shot 2017-07-11 at 4 10 25 pm](https://user-images.githubusercontent.com/21006/28088374-774f682e-6653-11e7-9269-3f4c06e5255e.png)

**Comment by sekmiller** [comment]
By the way, this test is not failing for me locally. Is there something wrong with the way the MocksFactory is setup for some?

    public static AuthenticatedUser testUser = MocksFactory.makeAuthenticatedUser("Homer", "Simpson");

**Comment by bsilverstein95** [comment]
@sekmiller Worth noting that it passed for me locally as well. The reason I set the expResult as Homer Simpson is because that's the default for MocksFactory -- yet for whatever reason the test fails on remote servers (?) it seems, judging by @kcondon and @pdurbin 's experience.

I think an archaic version of the test ended up getting merged into develop from some other branch, as I remember fixing this same test before when the original issue was in QA (can't recall off the top of my head which issue it was a part of). Regardless, given that the test file was already incomplete and the [remotely] failing test is just for a getter method, it seems safe to remove for now.

**Comment by sekmiller** [comment]
I poked at it a little, I think the answer is to move the creation of the mockUser into the Setup method (When I made my user "Joe Cool" I had to update the expected values for the individual tests, but if you leave it as "Homer Simpson" that's probably the only change you would need to make):

    public static AuthenticatedUser testUser;
    public static Timestamp expResult; 
    public static Timestamp loginTime = Timestamp.valueOf("2000-01-01 00:00:00.0");
    public static final String IDENTIFIER_PREFIX = "@";
    
    
    @Before
    public void setUp() {
        testUser = MocksFactory.makeAuthenticatedUser("Joe", "Cool");
        expResult = testUser.getCreatedTime();
    }

**Comment by pdurbin** [comment]
@sekmiller and I just talked about this and I agree that it sends the wrong message to interns such as @bsilverstein95 that the fix should be to delete tests. I only recently discovered the `MocksFactory.makeAuthenticatedUser` method written by @michbarsinai and it's super useful but I feel like maybe it put objects in some sort of global namespace or something? He would know better than I would what a good fix would be.

I'll also note that it's very strange that I've only seen this problem on Linux, on my Ubuntu laptop at home and on the CentOS "phoenix" server.

**Comment by bsilverstein95** [comment]
@pdurbin @sekmiller  I agree that deleting tests isn't the way forward, though that particular test file is comprised of getter & setter tests and I only started writing them to help turn some code coverage report lines green. Given that it was breaking the phoenix server and was effectively a blocker, the quickest fix that I could offer was to cut it from the file.

Though, thinking about it, if you wanted to leave the test in and have it pass reliably (until we figure out why Linux doesn't like MocksFactory authenticated users) I could also just rewrite it to be 1 = 1 via making the expected / actual result the same `getName()` method. This isn't ideal either, cause it's not much of a test -- but at least it's less of a step backwards than removing it.

**Comment by michbarsinai** [comment]
I'm not aware of any global namespace there. The only global data is a "next id" atomic integer being incremented, to avoid duplicate user ids.

**Comment by bsilverstein95** [comment]
Just committed a couple changes to the test file including the use of @sekmiller 's setUp() fix (and bring another previously broken test back into play - woo!) 

I'm not really able to test this because it already worked locally, but if someone can try the fix on a Linux machine or the phoenix server it would be helpful! Better to have one more test than one less.
