### ISSUE TITLE
Version: Update version from v4.7 to v4.7.1

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#3996]
See notes from previous update ticket

**Comment by pdurbin** [comment]
The issue for the last version bump: #3947.

The main gotcha that we don't note at http://guides.dataverse.org/en/4.7/developers/making-releases.html#bump-version-numbers is that we like to have the underlines line up in Sphinx like this: 91b65261 . If someone wants to add this note to that page, that's fine. Or we could link to a better example that shows the underline length changing.

**Comment by matthew-a-dunlap** [comment]
Assigning this to myself to get a first taste of our git process.

**Comment by pdurbin** [comment]
Pull request #4007 looks good. Moving to QA.

**Comment by matthew-a-dunlap** [comment]
Note: A minor text change was included in this, the help text for password creation better reflects the actual password policy
