### ISSUE TITLE
Show Access Conditions/Restrictions for Files

### ISSUE THREAD

**Issue by adam3smith** [IQSS/dataverse#3997]
This is to some extent a duplicate of https://github.com/IQSS/dataverse/issues/2872 but @pdurbin encouraged me to open a new ticket, so here goes.

**User Story 1**: As a potential data user/downloader, I want to be able to tell the access conditions for any given file as quickly as possible, ideally without even having to log in to dataverse.

**User Story 2**: As a repository, I want all of our files restricted, but most of them available to all registered users. I want potential users, who are not logged in, to be able to see that they only need to create an account to access a given file.

**Current situation**: I can see that a file is restricted, but there is no way for me to tell what the access restrictions are. Even on clicking "Request Access" I don't get a pop-up informing me what I'll actually have to do to get access, but it just sends the access request.

**Proposal**: My preferred solution would be to have the terms of access shown as part of the file metadata:
![image](https://user-images.githubusercontent.com/128986/28135526-859f60de-6714-11e7-87d7-c1245f0dee88.png)

If that's not an option, then showing them on clicking Request Access (as per #2872) would do for us, but is a second best.

**Comment by mheppler** [comment]
Reviewed this issue and the closed issue with @TaniaSchlatter. The popup to display the Terms of Access is straight forward and ready for development. We are already displaying the Terms of Access properly when the Guestbook is enable. (See screenshot.)

<img width="990" alt="screen shot 2017-07-19 at 3 36 11 pm" src="https://user-images.githubusercontent.com/687227/28385992-24657e50-6c98-11e7-8d59-0b0c6e0c31d5.png">

For the user stories submitted by @adam3smith, we will continue to review those, to make sure we're delivering the requested features. The "Terms" tab of the dataset page has a "Terms of Access" panel which displays all the requested information to users (without requiring log in).

**Comment by pdurbin** [comment]
Seeing "Guest" in the screenshot above (thanks, @mheppler ) reminds me that there is an open issue at #3628 to reconsider whether we should continue to pre-populate "Name" with "Guest" or not. If we're fine with the existing behavior, we could simply close #3628.

**Comment by djbrooke** [comment]
Hey @adam3smith - we're going to push through #2872 since it's small and the designs are already set. We'll revisit these changes in terms (heh) of upcoming changes to request workflows in 5.0.

**Comment by pdurbin** [comment]
Related:  File Page needs a Term Tab #4391

**Comment by adam3smith** [comment]
Closing this in favor of #4391. Since the improved request access dialog already implements part of this, displaying relevant terms in the file landing page -- whether that's in the metadata or in a separate tab is all that's left to do here.
