### ISSUE TITLE
"HTML tags" popover for description metadata field is broken

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#4013]
The popover for the "HTML tags" link in the information text of the Description fields (on dataverse and dataset create and edit pages) is empty. Looks like this happened and was fixed before: https://github.com/IQSS/dataverse/issues/1692#issuecomment-87106238

I'm seeing this on latest versions of Firefox (54.0.1 (64-bit)) and Chrome (59.0.3071.115 (Official Build) (64-bit)) for OS X.

![screen shot 2017-07-17 at 10 54 25 am](https://user-images.githubusercontent.com/18374574/28274878-418bb24c-6ae0-11e7-8a13-1e0ca7d9a4d2.png)

**Comment by oscardssmith** [comment]
To me that suggests that we should have an integration test to prevent this from happening again.

**Comment by mheppler** [comment]
@jacobmakar thanks for reviewing this with me. Maybe this commit 970dce387e8c98790792db0326141b5f8aa0e014 isn't the culprit that I thought it was. I'll look in more detail on Monday.

**Comment by jacobmakar** [comment]
I fixed it by moving the html examples out of the bundle and into the popover function.

**Comment by kcondon** [comment]
@jacobmakar The popup on the dataset page is not working and the page exhibits some strange behavior as in stops listening to events when: 1. an error occurs such as save on missing required fields or 2. cancel button does not work.

**Comment by mheppler** [comment]
@kcondon @jacobmakar This is my fault. Sorry. I have committed a fix. Moved popupHTML function to our rebind js, changed to pass popup title as variable on document-ready.

**Comment by jggautier** [comment]
I'm seeing this again, where the popover for the "HTML tags" information text is empty on the dataset and dataverse create pages.

On Harvard Dataverse, v. 4.7.1 build 94-62f8987
and latest versions of 
MacOS 10.12.6 (16G29) 
Chrome Version 61.0.3163.100 (Official Build) (64-bit)
Firefox 56.0 (64-bit)
Safari Version 11.0 (12604.1.38.1.7)

**Comment by pdurbin** [comment]
@jggautier I'm confused why you re-opened this issue. It was fixed in 4.8 but you're reporting an observation about 4.7.1.

**Comment by jggautier** [comment]
My mistake. Closing.
