### ISSUE TITLE
Permission bugs: the selected role of "curator" is not reflected under the user role defined in level 2 of permissions page

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#4027]
<img width="2409" alt="screen shot 2017-07-26 at 1 25 59 pm" src="https://user-images.githubusercontent.com/8322346/28644631-4e4306a8-7228-11e7-8328-c24152577129.png">

**Comment by sbarbosadataverse** [comment]
The "contributor" role once selected at level 1 of setting dataverse permissions gets reflected by the "Dataset creator" role being added to the 1 user/group field. When this is changed to "curator" the role doesn't get updated or added to the user/group field.

**Comment by scolapasta** [comment]
Discussed with @sbarbosadataverse and the page worked as it should, but is confusing. Since we have another issue about documenting permissions will add a reference there.

Actually reference was already added by @pdurbin .
