### ISSUE TITLE
Miniverse db update to be in sync with #3919

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#4028]
Pull request #4020 changes the db model in the following ways:

  - DataFile: removes `filesystemname`
  - DvObject: adds `storageidentifier`
     - model defn: `storageidentifier = models.CharField(max_length=255)`

When this changes goes live, it will break multiple parts of miniverse.  The fix is to go through and remove/rework places where `filesystemname` is used.

**Comment by bsilverstein95** [comment]
There is now an active pull request for this issue which can be found here:

https://github.com/IQSS/miniverse/pull/60

**Comment by kcondon** [comment]
After merging this branch, I followed the update/deployment instructions from Raman's op doc (Miniverse/Metrics LTS setup) It's a bit difficult to determine whether the changes have taken place but I did not see any overt errors and the storage identifier column has replaced file system name in UI and that id/link works.

**Comment by kcondon** [comment]
Raman agreed to troubleshoot with a dv developer during an upcoming meeting.
