### ISSUE TITLE
Multiple values being entered into metadata fields that expect only one value (e.g. authors and keywords)

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#4035]
This has been brought up in other channels but I haven't seen it reported in a github issue.

Some dataset depositors entering terms into the keyword metadata field enter a string of keywords separated by semi-colons or commas. I suspect that most of the time those keywords are copied from the associated articles' keywords and pasted into the dataset keyword field. Depositors doing this don't realize that if they want to enter multiple terms, they should click the + sign for another set of keyword fields (and of course they might be expecting that the metadata field will parse the string, since they've seen other applications do it).

![screen_shot_2017-08-01_at_1_42_00_pm](https://user-images.githubusercontent.com/18374574/28838843-9f97ecd0-76bf-11e7-9d65-9f2f5a9fe743.png)

This is a problem because the fields don't split the strings by the common semi-colon or comma characters in order to treat each keyword as a separate term; it turns the whole string into one term, which hurts discoverability:

![screen_shot_2017-08-01_at_12_25_07_pm](https://user-images.githubusercontent.com/18374574/28841605-c6d723d4-76c8-11e7-808b-c5b2140e3b58.png)

To get a sense of how often this is done in Harvard Dataverse and how much of an issue it is, we could query Harvard Dataverse for all of the keywords of non-harvested datasets, then see how many contain semi-colons and/or commas.

I think we could also do the same query for harvested datasets in Harvard Dataverse, which might help indicate the size of the problem with the way keyword metadata is being harvested.

Both harvested and non-harvested datasets have keywords like this. Last November, Leonid sent me the results of a query that included harvested and non-harvested datasets with keywords metadata. Of the appr. 20,000 unique datasets in those results, about 2500 (12 percent) have keywords containing one or more semicolons. (I'm not including keywords that have only commas, because it's more likely that a greater portion of those are really just one-term keywords that happen to contain a comma (e.g. "Firm Objectives, Organization, and Behavior" from [JEL codes](https://www.aeaweb.org/econlit/jelCodes.php?view=jel) or lots of terms from LCSH).

**Comment by pdurbin** [comment]
@jggautier made this point elsewhere but we see a similar problem in #377 where authors wants to enter multiple affiliations. https://dataverse.csuc.cat/dataset.xhtml?persistentId=doi:10.34810/data31&version=2.0 is an example and here are screenshots from the metadata tab and the facet:

![Screen Shot 2021-12-01 at 10 14 34 AM](https://user-images.githubusercontent.com/21006/144260765-b1ad9682-8077-4392-b3b6-a7e458dbb5a0.png)

![Screen Shot 2021-12-01 at 10 15 35 AM](https://user-images.githubusercontent.com/21006/144260909-75eeca61-96dd-4d1e-a48c-25a3f5c4830d.png)

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
