### ISSUE TITLE
unexpected facet / displayformat (/solr indexing?) behavior

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#4036]
facets display displayformat values for (some?) URLs.  Expected behavior would be showing the value.

![screen shot 2017-08-01 at 5 48 10 pm](https://user-images.githubusercontent.com/10261853/28848619-a94f41c0-76e1-11e7-87ef-69ca1d67f094.png)

Haven't yet excluded the possibility that this is due to user error.

**Comment by pameyer** [comment]
DatasetField.getValuesWithoutNaValues was sending getDisplayValue(), instead of getValue().

**Comment by pameyer** [comment]
For reference, this appears to have been introduced for #3946 but was something I didn't catch then (in other words, this should only effect "slightly more semantic" DatasetFieldTypes).

**Comment by kcondon** [comment]
To test this I needed a field that was also a facet. I chose seriesName and used this sql:
```
update datasetfieldtype
set displayformat ='<a target="_blank" href="http://www.rcsb.org/pdb/explore/explore.do?structureId=#VALUE">PDB (RC+SB) #VALUE</a>',
fieldType= 'TEXT',
validationformat='^[a-zA-Z ]{5,5}$'
where id = 67;
```
