### ISSUE TITLE
Metadata blocks: When introducing a certain number of metadata fields via API the dataverse pages stop displaying sub-dataverses.

### ISSUE THREAD

**Issue by fbgesis** [IQSS/dataverse#4037]
In 4.6.2 release.

When adding a custom metadata block via API sub-dataverses are no longer shown.

To reproduce:
* Use clean installation
* Login as dataverseAdmin
* Create a new dataverse under the root dataverse
* Check if it is there by displaying the root dataverse page
* Register TSV metadata block
* Reload page
-> The sub-dataverse disappears

The sub-dataverse can still be accessed by its URL.

These workarounds helped (with the obvious drawbacks):
* Remove some dataset fields from the TSV file.
* Re-install dataverse without some of the default metadata bocks.

[metadatablock.txt](https://github.com/IQSS/dataverse/files/1193800/metadatablock.txt)

**Comment by pdurbin** [comment]
@fbgesis hi! Does the Google doc linked from #3168 help at all?

**Comment by fbgesis** [comment]
Hi. I am aware of that doc and as far as I see the TSV complies with it. Thanks for the link anyway.

I was writing the file step by step and tested it in between, always with a clean installation. The problem first occurred with the last 5 metadata fields. I checked them over and over and replaced them with simple dummy fields to no avail. 
The fact that it helps to remove some fields at another place lets me think that this whole issue is not caused by a syntax mistake in these 5 lines.

**Comment by pdurbin** [comment]
@fbgesis did you add the ``requestHeaderSize`` line to Solr's ``jetty.xml`` file? Please see http://guides.dataverse.org/en/4.6.2/installation/config.html#jetty-xml

**Comment by fbgesis** [comment]
Hi. That solved it.
