### ISSUE TITLE
PDF File type not recognized when uploading using python and Native API.

### ISSUE THREAD

**Issue by markrlondon** [IQSS/dataverse#4039]
PDF files don't get recognized as PDFs, but instead as text, when uploading using the following python code and Native API.   I did test it with an excel file, and that got recognized, and got converted to a .tab file (to my surprise!).   So the python code appears to be working properly.   It's basically the sample code from the Native API guide.   I've attached a PDF file, but I tried multiple PDF files, from different sources, and none of them worked.   

```
dataverse_server = 'https://demo.dataverse.org' # no trailing slash
api_key = ''
persistentId = '' # doi or hdl of the dataset

url_persistent_id = '%s/api/datasets/:persistentId/add?persistentId=%s&key=%s' %
 (dataverse_server, persistentId, api_key)

f = open('./test.pdf', 'r').read()
file_content = ''
for line in f:
        file_content += line
files = {'file': ('test.pdf', file_content)}
print 'making request: %s' % url_persistent_id
r = requests.post(url_persistent_id, files=files)

# -------------------
# Print the response
# -------------------
print '-' * 40
print r.text
print r.status_code
```

[test.pdf](https://github.com/IQSS/dataverse/files/1195646/test.pdf)

Updated: Small formatting fixes made by @pdurbin who has been discussing this at https://groups.google.com/d/msg/dataverse-community/rraewHpy6M0/AVDEak6uBQAJ

**Comment by pdurbin** [comment]
@markrlondon when I upload that PDF ("Subscriber Claim Form") using [REST Assured](http://rest-assured.io) in 1e1b3ae it works fine. Here's a screenshot:

![screen shot 2017-08-03 at 12 16 46 pm](https://user-images.githubusercontent.com/21006/28931998-07ea13d0-7846-11e7-9a26-fd34a1bd4100.png)

I suspect that you shouldn't iterate over each line with `for line in f` and that you should use `file_content = open('./test.pdf', 'r').read()` instead.

**Comment by markrlondon** [comment]
I will ask on stackoverflow and see how there could be a difference between the CURL command and the requests..post command.  I thought that one should emulate the other, but obviously not.

**Comment by markrlondon** [comment]
I compared the output of the CURL command with the output of my python script, using http://httpbin.org/post as the test url, and I found the difference between the 2 methods.

The CURL command base64 encodes the file.   In order to emulate this in the script, I found the following code on stackoverflow.   It works perfectly for all files types.

import base64
with open('./test.pdf', 'rb') as fd:
        b64data = base64.b64encode(fd.read())

files = {'file': ('test.pdf', b64data, 'application/octet-stream\r\nContent-Transfer-Encoding: base64')}

**Comment by pdurbin** [comment]
@markrlondon wow! Good find! Would you like to make a pull request to improve https://github.com/IQSS/dataverse/blob/develop/doc/sphinx-guides/source/api/native-api.rst ? We document the process at http://guides.dataverse.org/en/4.7.1/developers/version-control.html#how-to-make-a-pull-request

**Comment by markrlondon** [comment]
Philip - I just tested uploading all my files using a single zip file, in my python code, and the upload speed was magnitudes faster than uploading each file individually via base64 encoding.  The speed was very slow uploading individual files, and my files are not large at all.   So I don't recommend the method that I've posted here, even though it solved my original complaint. - Mark
