### ISSUE TITLE
Can't edit draft datasets on demo.dataverse.org, using the web interface.  Native API works.

### ISSUE THREAD

**Issue by markrlondon** [IQSS/dataverse#4045]
I've just created several datasets today, that I can't edit using the web interface.  All the boxes are greyed out.   For example, see this link (screenshot attached):

https://demo.dataverse.org/dataset.xhtml?persistentId=doi:10.5072/FK2/JSH8ND&version=DRAFT

But I could delete it, using a Native API command (using curl).  Thanks. - Mark 

![untitled](https://user-images.githubusercontent.com/15250804/28984932-458e1838-792e-11e7-9c8b-a6afb2721a3f.jpg)

**Comment by markrlondon** [comment]
The "disabled" class is being added to the buttons.   I was able to get rid of the class using the Chrome development tools, and that enabled the Edit button, and I was edit the dataset!   Obviously not the correct solution.   But it definitely opened my eyes regarding my own web pages, where I disable buttons in the same manner.  People can enable them!

**Comment by pdurbin** [comment]
@markrlondon how easy is it to reproduce the creating of these datasets via API that can't be edited via the GUI? This is a very strange bug. Also, in case this bug isn't examined anytime soon, I'd like to note that the demo site is running 4.7.1 right now.

**Comment by markrlondon** [comment]
Unfortunately the problem seems to have been transient, as I can't reproduce the problem.  All I know is that I created a handful of datasets at the same time, and they all had the same problem.  But the problem disappeared later that day.  I deleted most of them, but I have left the above dataset alone, in case you  tell from it, why I don't have permission to do anything with it.   I'll let you know if the problem occurs again.  I've been creating a lot of test datasets since then, without a problem..   Go figure!

**Comment by pdurbin** [comment]
@markrlondon ok, please keep us posted on if you can easily reproduce this in the future or not. Thanks!

**Comment by pdurbin** [comment]
@markrlondon any more thoughts on this issue? Should we close it? Do you think you can reproduce the bug and give us the steps to do so? Thanks!

**Comment by djbrooke** [comment]
I'm going to close this one for now. If we (or @markrlondon) can reproduce it, we should reopen. 

When this was brought up during backlog grooming today, @mheppler pointed out the potential issue of only having a "disabled" class on the frontend between the user being able to do something and not able to do something. If it's not some completely crazy scenario here, we may need something with more teeth.

**Comment by mdmADA** [comment]
And I totally agree with needing something "with more teeth" between the user and being able to do something...

**Comment by pdurbin** [comment]
@mdmADA I don't want to lose track of your comments on a close issue so I'm reopening it, assigning it to you, and moving it to the "Community Dev" column at https://waffle.io/IQSS/dataverse so we remember to touch base with you about what a good fix might be. Thanks.

**Comment by pdurbin** [comment]
I guess the only thing I'll add is that an OptimisticLockException is never a good thing. Any more leads on a fix, @mdmADA ? Or steps to reproduce the bug, especially on the "develop" branch?

**Comment by mdmADA** [comment]
Hi @pdurbin. An OptimisticLockException is definitely not a good thing. 

I have a number of things on the go at the moment but will add 'attempt to reproduce bug #4045" to my TO-DO list.  

As for a possible fix, I haven't have had time to think about that either. My instinct tells me the failed data file ingest caused the OptimisticLockException issue somewhere down the line and adding in a pause between each file upload gave the system time to recover from that Exception (if that's possible and/or makes sense). I am not sure how one would go about adding in a pause when something has "gummed up" the system and it needs time to recover... will add that to my TO-DO list too.

**Comment by pdurbin** [comment]
@mdmADA hi! This issue is still assigned to you but please let us know if we should throw it back in the inbox instead. No pressure either way! Thanks.

**Comment by mdmADA** [comment]
Yeah, as much as I would like to look at this,  I won't have time so you should probably throw it back into the inbox. 📥

**Comment by pdurbin** [comment]
@mdmADA thanks. Done. I'm not sure if we'll still call it the inbox once we migrate off Waffle (#5651) but I unassigned you at least. Thanks for the feedback on this issue.
