### ISSUE TITLE
server error with ORCID sandbox login

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#4054]
Seen on develop-5832e4f; configured to connect to ORCID sandbox.

Configure as documented, but substituting `https://sandbox.orcid.org/v1.2/{ORCID}/orcid-profile` for `https://api.orcid.org/v1.2/{ORCID}/orcid-profile` in `orcid.json` (and filling in appropriate clientId, clientSecret values.  Callback UR1 registered with ORCID sandbox as `$sitename/oauth2/callback.xhtml` following installation docs.

Dataverse home page -> Log In -> ORCID -> Log In With ORCID -> ORCID sandbox login, login with valid sandbox user, redirected back to dataverse; error banner 500 internal server error.

First exception trace from server.log:

[2017-08-09T11:52:38.230-0400] [glassfish 4.1] [SEVERE] [] [edu.harvard.iq.datav
erse.authorization.providers.oauth2.impl.OrcidOAuth2AP] [tid: _ThreadID=51 _Thre
adName=jk-connector(4)] [timeMillis: 1502293958230] [levelValue: 1000] [[
  XML error parsing response body from ORCiD: Open quote is expected for attribu
te "href" associated with an  element type  "a".
org.xml.sax.SAXParseException; lineNumber: 45; columnNumber: 2541; Open quote is
 expected for attribute "href" associated with an  element type  "a".

Harvard Dataverse (production ORCID registry, real ORCID account) does not show the same 500 error upon redirect to Dataverse.

**Comment by pameyer** [comment]
@kcondon was kind enough to check this on an internal site also configured with the ORCID sandbox; problem does not occur there (build 555-a1792ad).  Reset dev VM, re-installed (only code change is outputting dumping the response that values XML validation).  Still fails, result returned from ORCID is html, not xml.  Possible misconfiguration of sandbox endpoint? Possible other misconfiguration?

**Comment by pameyer** [comment]
Thanks to @pdurbin and @kcondon , confirmed misconfiguration (specifically using incorrect URL for sandbox API endpoint).

Documentation doesn't currently cover sandbox configuration (it would be used on a dev site, not production).  I'll make a small documentation update about sandbox configuration in case in comes up in the future.

**Comment by bsilverstein** [comment]
New documentation seems straightforward and accurate. If it's up to par for @dlmurphy then seems safe for QA / merge.
