### ISSUE TITLE
User Account Control: Button for access removal

### ISSUE THREAD

**Issue by matthew-a-dunlap** [IQSS/dataverse#4055]
To comply with Harvard Security requirements, Dataverse needs the ability to easily limit the access a user has. Current functionality allows the removal of groups and dataset permissions that a user has, but this requires searching for those access as opposed to the ability to deal with them all in one place. 

As a first step towards improving this, we are looking to add a button that allows all accesses for a user to be removed at once, putting the user back into "new user" state. 

See https://github.com/IQSS/dataverse/issues/2419 for previous discussion on this space.

**Comment by mheppler** [comment]
UI IMPACT

*Manage Users*
- [ ] swap "Authentication" and "Roles" columns in order
- [ ] add "Remove All" button under the roles listed (if no roles listed, don't display button)
- [ ] "Remove All Roles" confirmation popup... "_Are you sure..._?"

![screen shot 2017-08-16 at 11 49 33 am](https://user-images.githubusercontent.com/687227/29376460-9e67bd72-8286-11e7-8a61-14ad6cf87be3.png)

**Comment by mheppler** [comment]
New `4055-remove-user-roles` branch started with a commit of a placeholder button on the Manage Users pg.

**Comment by mheppler** [comment]
Looking good. Putting in Code Review. @scolapasta has looked it over already, but has suggested that anyone is free to take a peek.

![screen shot 2017-09-15 at 4 42 15 pm](https://user-images.githubusercontent.com/687227/30502842-f3e4c724-9a35-11e7-9a93-275a14e468d3.png)

**Comment by landreev** [comment]
I may have more questions about the back end for this ticket;
I'm going to drag it back into dev.; and I may need to talk to Gustavo some more about it.

**Comment by mheppler** [comment]
*BACKEND CHANGE LOG*

- [ ] Reindex roles... ??

**Comment by kcondon** [comment]
Tested, works, can be merged but has merge conflicts that need to be resolved first.
