### ISSUE TITLE
Fix the ConcurrentModificationException in ExportService

### ISSUE THREAD

**Issue by mdmADA** [IQSS/dataverse#4056]
DV 4.6.1

Dataverse Objects involved:

Dataverse: unpublished
Dataset 1: large, unpublished
Dataset 2: larger, unpublished
<br>

Workflow described:

1. Tried to publish the Dataverse and its two subsets simultaneously (ie. all 3 were unpublished - hit Publish on one of the datasets).

This failed in that the Dataverse and the 2 datasets all remained unpublished. No errors were found in the server.log file and there was nothing to indicate failure, or anything, in the UI.

2. Try a different approach:

a) Publish Dataverse first -> succeeds

b) Within this newly-published Dataverse, publish Dataset 1. -> succeeds

c) Try to publish Dataset 2:

UI Spinner just keeps spinning but there was an Exception thrown in the server-side code that is not caught by the UI => The user doesn't know if the publishing is just taking a long time or if it failed.

From the stack trace in server.log (see below), the issue seems to be that the Exporter e = exporters.next(); in the ExportService class is causing problems. The ConcurrentModificationException indicates that a collection (exporters?) is being accessed concurrently by the same, or another, thread. (https://docs.oracle.com/javase/7/docs/api/java/util/ConcurrentModificationException.html) (I figure these things out as I help my colleagues figure out why their datasets won't publish...)

My assumption is that, because this second dataset is quite large, that the attempt to publish in Step 1 above was still running and then hitting Publish the second time caused a second 'Publish' process to try and modify the exporters collection at the same time as the first. ConcurrentModificationException thrown.

3. Wait awhile. Try to publish Dataset 2 again. This time publish succeeds.

<br>
**Server.log with stack trace portions** from failed Step 2c) above with the ConcurrentModificationException:

#{DatasetPage.releaseDataset}: javax.ejb.EJBException
javax.faces.FacesException: #{DatasetPage.releaseDataset}: javax.ejb.EJBException
        at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:118)
        at javax.faces.component.UICommand.broadcast(UICommand.java:315)
        at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:790)
        at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:1282)

<lots of other messages relating to third-party software>

Then farther down in the stack trace:

Caused by: java.util.ConcurrentModificationException
        at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:719)
        at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:752)
        at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:750)
        at java.util.ServiceLoader$1.next(ServiceLoader.java:479)
        at edu.harvard.iq.dataverse.export.ExportService.exportAllFormats(ExportService.java:135)
        at edu.harvard.iq.dataverse.engine.command.impl.PublishDatasetCommand.execute(PublishDatasetCommand.java:208)
        at edu.harvard.iq.dataverse.engine.command.impl.PublishDatasetCommand.execute(PublishDatasetCommand.java:49)
        at edu.harvard.iq.dataverse.EjbDataverseEngine.submit(EjbDataverseEngine.java:201)
        at sun.reflect.GeneratedMethodAccessor1717.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        
        
This will be difficult, if not impossible, to reproduce but the end issue is that when a server side exception occurs during publish, it needs to be caught by the UI so the user knows that something went wrong.... otherwise the user sits there wondering what is happening, if anything.

I am also curious if this ConcurrentModificationException can be prevented when publishing a large dataset fails and then a second attempt causes this error.

**Comment by pdurbin** [comment]
This sounds a lot like the support ticket that we discussed at our tech meeting on Tuesday: https://help.hmdc.harvard.edu/Ticket/Display.html?id=251733

**Comment by landreev** [comment]
Yes, this appears to be the issue we discussed 2 days ago (we also have a good idea for a fix). 
Since there was no dedicated GitHub issue for tracking the fix, we'll use this one.

**Comment by landreev** [comment]
More relevant info: we believe the concurrent modification exception is the result of the line of code in ExportService.getInstance() that reloads the list of exporter plugins every time it's called. If this happens while another ExportService instance is doing an exportAll, the exception will be thrown as it attempts to iterate to the next export plugin on the list. (see the line "...LinkedHashIterator.nextNode(LinkedHashMap.java:719" in the exception stacktrace, above). 

In real life, this happens when a user attempts to publish a dataset where the metadata takes a long time to export (for example, when there is a significant amount of tabular data). Then the job is still in progress by the time the page attempts to refresh the list of available export formats - hence he exception, and a (quiet!) failure to publish. 

Annoying issue, but a fix seems to be easy: Per the discussion on Tue., it  appears that the dynamic reload is not really necessary, and/or adding any value.

**Comment by djbrooke** [comment]
Thanks @mdmADA @pdurbin @landreev. I mentioned on Friday that we should pull this into Development.

**Comment by landreev** [comment]
I'm taking the liberty of pushing this into QA directly. Because we reviewed the solution collectively last Tuesday - so that should count as code review (?). If anybody has any objections, please speak up.

**Comment by pdurbin** [comment]
@landreev that's fine. For what it's worth, I took a look anyway and yes, it's what we all talked about, so thanks for moving it right into QA.
