### ISSUE TITLE
Storage Driver: Refactor and document saveInputStream with filesize

### ISSUE THREAD

**Issue by ferrys** [IQSS/dataverse#4064]
During the creation of the S3 storage driver (#3921), we encountered an issue where the S3 SDK PutObjectRequest method requires the size of an Input Stream to be specified. The current solution is to convert the input stream to a byte array and then determine the size, which is not very efficient. This affects both saveInputStream and saveInputStreamAsAux.

@landreev suggested implementing another version of both methods which each take the size of the file/input stream as the extra argument. This would require the developer to set the file size before they called either method. I went ahead and created the basic abstract functions in StorageIO and implemented them in the storage drivers, but more thought needs to be put into the implementation/developer documentation of these methods.

Since theses methods are not being used heavily in the current Dataverse implementation, this was out of scope for the S3 storage driver, but it is still relevant for the future.

**Comment by landreev** [comment]
Awesome. (I'll add a couple of words here, as to other potential ways to avoid having to buffer that entire stream...)

**Comment by pdurbin** [comment]
Here's my take:

- 46d1fb835b0bee151c9842c4461aa075455aa25f has @matthew-a-dunlap using a temp file instead
- 15bf9dc7d752dd0156de06b3bfdbb23f0684582e has @landreev adding a nice explanation

I think we can close this. I hope so.
