### ISSUE TITLE
External Storage: For external storage, Swift/S3, should consider providing health check and fail more gracefully.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#4067]
While testing Swift on an underpowered test instance that was subject to outage, it became clear that the behavior of the app when the storage was unavailable was confusing and problematic. Specifically, we attempt to provide/retrieve thumbnails for all the cards so navigating the app when storage is down just times out. This happens anywhere where there are thumbnails: homepage, dv page, ds, file pages.

Maybe we can make it detect the underlying system is not available and then just serve up the default image or else timeout quickly on image fetch -display the default icon immediately then replace with actual.

Maybe have a periodic health check like we do with web servers and load balancers -a global static variable with a time stamp. Check is some quick app to app level ping to see if it is responding and update the state.  maybe try every x minutes or last successful request too.

Just a thought to stimulate thinking on the matter. We likely will have more such requirements as we add additional loosely coupled external components.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
