### ISSUE TITLE
Upload New Files - Tags not Applied

### ISSUE THREAD

**Issue by shlake** [IQSS/dataverse#4068]
Using Harvard's V4.7.1 on Chrome:

From the dataset page, I click "+Upload Files", after dragging/selecting a file I click the "Edit Tags" button.
I select a tag from the "File Tags" list, it shows up by "Selected Tags". I click "Save Changes" and the tag does not show up on my file. It doesn't even show up after I click "Save Changes" and go back to the dataset page. The file does not have a tag.

BUT if I do this after the file is uploaded and go to the Files page and click "Add+Edit Metadata", then click the "Edit Tags" button, do the same clicks as described above, this time the tag is displayed.

**Comment by djbrooke** [comment]
Confirmed on demo.dataverse.org. We'll get this fixed. 

Thanks @shlake!
