### ISSUE TITLE
Navigation: unexpected Save Button Issues

### ISSUE THREAD

**Issue by oscardssmith** [IQSS/dataverse#4070]
This will contain a fix to an issue with the save button

**Comment by bsilverstein** [comment]
This was discussed today as a larger group in terms of scope / plans and Oscar was quick to create a working fix. I looked high and low for similar bugs though many buttons across the UI don't have a similar trigger to the one from this issue. Tested @oscardssmith 's new fix on both Chrome and Safari. Any unwelcome changes made do not save. Page redirects as intended. 

Gonna move this to QA as it's a clean fix!
