### ISSUE TITLE
Swift File Restriction: Implement Swift ACLs

### ISSUE THREAD

**Issue by ferrys** [IQSS/dataverse#4071]
As a user of a computing environment, I want to be able to compute on an entire dataset at one time. I also want to be able to access datasets without going through Dataverse (if I have the proper permissions).

In order to allow for better access to data through a computing environment, we need a solution which takes advantage of the fact that InCommon will allow MOC OpenStack and Dataverse users to hold the same credentials. So, we will implement the concept of an _access control list_.

We break users up into three specific cases:	

1. A user has the `FileDownloader` role on a **dataset** level.
This user is given access to the entire container via the corresponding access control list.

2. A user has the `FileDownloader` role on **all** of the files in a dataset.
This user is given access via temporary URLs.

3. A user has the `FileDownloader` role on **some** of the files in a dataset.
This user is given access via temporary URLs.

**Note**: Case 2 is an edge case that we will not be able to support very well. Even if a user has access to all the files in a dataset, they must have the `FileDownloader` role on a dataset to be given permissions through an access control list. This is because a contributor could add another restricted file to the dataset and potentially give a user access to a file in Swift that they don’t have access to in Dataverse.

UI/UX Changes:

- Currently, we do not support a user request for access to an entire dataset (but, a curator can give them access through the dataset permissions page), but this would be necessary for this change. 
- Additionally, we do not support checking specific files for compute, which would be useful if a user only had access to some of the files in a dataset.

**Comment by pdurbin** [comment]
@ferrys hi! What is the status of this issue? Thanks.

**Comment by ferrys** [comment]
@pdurbin current status is limbo. New issues regarding secure computing are taking priority and we are working on Incommon. Also there may be issues with Ceph's version of Swift and ACL compatibility, so we're also looking into that.
