### ISSUE TITLE
Dataset titles composed of other metadata

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#4072]
Researchers depositing data in SBGrid Data Bank don't enter dataset titles. The titles are composed of values from several metadata fields. This standardizes the dataset titles, reduces human error and speeds up the deposit workflow. @pameyer [mentioned](https://github.com/IQSS/dataverse/issues/3679#issuecomment-299322534) this in a related issue (#3679), but we agreed to create a separate issue for Dataverse being able to create dataset titles using values from other metadata fields.

This might be useful for replication data, where the dataset title often follows the naming convention: "Replication data for:" plus the title of the article (which isn't a standard Dataverse metadata field right now). As @djbrooke pointed out, it might also be very helpful for naming datasets created from streaming data.

**Comment by mheppler** [comment]
Related to:
- _**Dataset Metadata - allow one subfield to reference the value of another #1625**_ 
- _**Dataset Metadata: "Replication Data for:" title prefix vs required field validation #4412**_
- _**Create Dataset: Add "replication data for" to title, make "related publication" metadata field required #3679**_
- _**Change how UI shows compound fields #6589**_
