### ISSUE TITLE
custom navbar logo causes logo to switch right/left with status message banner

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#4076]
<img width="286" alt="screen shot 2017-08-14 at 2 16 03 pm" src="https://user-images.githubusercontent.com/10261853/29285491-ae604aae-80fc-11e7-9ede-fea1170af8b9.png">
<img width="301" alt="screen shot 2017-08-14 at 2 15 57 pm" src="https://user-images.githubusercontent.com/10261853/29285492-ae61791a-80fc-11e7-88f3-9dcc677d5c1d.png">

**Comment by pameyer** [comment]
The branch the fix for this is in has some other branding related changes (which are up for discussion about merging).  So far:
- don't display the block for custom CSS if there's no custom CSS in the settings table
- move the custom CSS block to the page header (since having it in the body was making html validation less happy).

**Comment by mheppler** [comment]
All good stuff, @pameyer.

I have cleaned up a few minor things, like changing your `c:if test` to a `ui:fragment rendered`. Also included minor improvements to the documentation.
