### ISSUE TITLE
Special characters (ampersand, greater than, less than, nbsp) in dataset title displayed as HTML entity name codes

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#4077]
Ampersand, greater than and less than symbols in dataset titles are replaced with their escaped versions in different parts of the Dataverse UI: 

- Dataset landing page - breadcrumb, dataset citation and Title field in Metadata tab.
<kbd>![screen shot 2017-08-14 at 2 59 32 pm](https://user-images.githubusercontent.com/18374574/29287083-3b4448e4-8102-11e7-89a0-0e8b6b946795.png)</kbd>

- Dataset cards on My Data page - title and citation
<kbd>![screen shot 2017-08-14 at 3 02 53 pm](https://user-images.githubusercontent.com/18374574/29287873-be8b6d20-8104-11e7-865d-6c57bce4c151.png)</kbd>

- Dataset cards on regular results page - citation (but in the titles the characters are unescaped)
<kbd><img width="870" alt="screen shot 2017-10-25 at 12 25 07 am" src="https://user-images.githubusercontent.com/18374574/31980568-6b2a003e-b91b-11e7-8a1a-a6fe62edf713.png"><kbd>

**Comment by jggautier** [comment]
Also checked dataverse names and they seem to be displaying fine in the UI. The file name field has validation preventing files from being saved with these characters in their titles, so there's no problem there, either.

**Comment by mheppler** [comment]
Related to #4123 and #5020.

**Comment by donsizemore** [comment]
We're hitting this with a funder title as well (or does that go in a separate issue?).

**Comment by mbasket** [comment]
> We're hitting this with a funder title as well (or does that go in a separate issue?).

Same. Funder style guide requires &.

**Comment by djbrooke** [comment]
Thanks @donsizemore and @mbasket. This seems like a small fix (famous last words... :)) so we'll bring this into the next sprint.

**Comment by sekmiller** [comment]
Applying this method https://jsoup.org/apidocs/org/jsoup/parser/Parser.html#unescapeEntities-java.lang.String-boolean- to strings that have been stripped of tags in order to return escaped characters such as &, <, >, etc.

**Comment by djbrooke** [comment]
@donsizemore @mbasket - can you provide the specific cases that you're running into? We'll be able to build some test cases around those. Thanks!

**Comment by mbasket** [comment]
> @donsizemore @mbasket - can you provide the specific cases that you're running into? We'll be able to build some test cases around those. Thanks!

Bill & Melinda Gates Foundation
in the funder field

**Comment by donsizemore** [comment]
@djbrooke what @mbasket said =)

**Comment by djbrooke** [comment]
Perfect, thanks!

**Comment by mheppler** [comment]
It's pretty much all the fields.

https://dvn-build.hmdc.harvard.edu/dataset.xhtml?persistentId=doi%3A10.70122%2FFK2%2F3BBWPS&version=DRAFT

<img width="605" alt="Screen Shot 2019-08-09 at 3 37 36 PM" src="https://user-images.githubusercontent.com/687227/62804558-a916b880-babb-11e9-9d34-5a0db236b7a1.png">
<img width="596" alt="Screen Shot 2019-08-09 at 3 37 44 PM" src="https://user-images.githubusercontent.com/687227/62804571-ab791280-babb-11e9-9228-effb3887753a.png">

**Comment by mheppler** [comment]
Anything learned in this issue should be noted in _Publishing fails when dataset contains HTML entities such as &nbsp; #3328_ as well as _Use unescaped versions of ampersand, greater than and less than symbols in RIS files #4123_. Those issues are symptoms of the same problem.
