### ISSUE TITLE
User Guide contains information specific to one of the installations of Dataverse

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#4081]
Spotted at https://groups.google.com/d/msg/dataverse-dev/9xMaCrr1eek/fKHebo0DDAAJ at http://guides.dataverse.org/en/4.7.1/user/dataverse-management.html#linked-dataverses-linked-datasets it says,

> "If you need to have a dataverse or dataset linked in the Harvard Dataverse installation, please contact support@dataverse.org."

This line should be rewritten to apply to any installation of Dataverse. Perhaps we could link to this section of the API guide about Saved Search, Linked Dataverses, and Linked Datasets: http://guides.dataverse.org/en/4.7.1/api/native-api.html#saved-search

**Comment by mheppler** [comment]
With the blessing of @djbrooke I am closing this issue, and tracking it in #3348 as part of that deliverable. While looking at this issue in that branch, I found that two other instances of the support email in the docs. So, I will remove ALL instances of it in that one branch.

Here is the revised test that was committed as part of 0441dd35885dbcffc96f7a1d549cd4cc1278feb3.

> If you need to have a dataverse or dataset linked to your dataverse, please contact the support team for the Dataverse installation you are using.
