### ISSUE TITLE
On "My data" page, clicking dataverse links in dataverse and dataset cards shows users results from root dataverse

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#4083]
When logged in Harvard Dataverse or demo, as a regular or super user, go to "My data" page and click on a dataverse link of a dataverse or dataset card. Within the search results box, the page should show all dataverses, datasets and files my account has role in, but it shows everything in root Harvard Dataverse, as though I'm on the root dataverse.

<p>1. Click dataverse link in a dataverse card or dataset card:

<p><kbd><img width="733" alt="screen shot 2017-08-16 at 8 48 00 pm" src="https://user-images.githubusercontent.com/18374574/29391418-414483f2-82c5-11e7-96d1-0036505c5b62.png"></kbd>

<p>2. Page shows everything in root Harvard Dataverse instead of everything within that dataverse:

<kbd><img width="752" alt="screen shot 2017-08-16 at 8 48 31 pm" src="https://user-images.githubusercontent.com/18374574/29391448-64455426-82c5-11e7-8268-5b6d76fcbd4c.png"></kbd>

**Comment by scolapasta** [comment]
This is becuase those cards use urls with the ids instead of the alias (and is a known bug that has not yet been fixed).

For example:
https://dataverse.harvard.edu/dataverse.xhtml?id=645
vs
https://dataverse.harvard.edu/dataverse/cces

See #3600

**Comment by jggautier** [comment]
Doh! Okay, closing this one.
