### ISSUE TITLE
GlassFish 4.1 + NetBeans 8.2 = integration broken

### ISSUE THREAD

**Issue by matthew-a-dunlap** [IQSS/dataverse#4088]
It seems that in some cases NetBeans 8.2 is unable to talk to GlassFish 4.1 (which is required for dataverse). Interaction with GlassFish via the NetBeans Services tab is mostly broken. When NetBeans attempts to start GlassFish 4.1, the service is started but after that point NetBeans is unable to communicate with it and eventually gives up (with an error message somewhat incorrectly stating the startup "failed").

This lack of integration greatly slows down development for affected developers, as developers are unable to take advantage of auto-deployment and the ability for NetBeans to hot-update UI components.

There is a distinct lack of error messages in the GlassFish logs as well as the IDE logs.

NetBeans 8.2 is able to talk to GlassFish 4.1.1 & 4.1.2. NetBeans 8.0.2 (and maybe 8.1) are able to talk to GlassFish 4.1.

**Comment by matthew-a-dunlap** [comment]
My current recommendation for now is to add documentation to the Developer Guide noting this known issue and to tell developers to try an older NetBeans version if the latest one is causing issues.

This should also be reported to the NetBeans developer team. I am waiting on solving my other NetBeans issue before reporting this one.

**Comment by matthew-a-dunlap** [comment]
NetBeans bug filed: https://netbeans.org/bugzilla/show_bug.cgi?id=271338

**Comment by wadechandler** [comment]
Why would one not want to upgrade those GF versions? It seems a really good system practice in such cases of minor .x releases to keep current. If that is the only issue, then I would suggest that is kind of minor, but it could be related to client libraries used in NB in that case; fixes or other things etc.

**Comment by matthew-a-dunlap** [comment]
Hi @wadechandler thanks for the replies on this! 

We've had library compatibility issues between later versions of GlassFish and other libraries we use. More details can be found here: https://github.com/IQSS/dataverse/issues/2628 I'm new to our group so I can't speak about the choice in more detail, maybe someone else can chime in. 

That being said, its probably best to focus on the other issue we are having first, as that one is happening regardless of the GlassFish / NetBeans versions we've tried.

**Comment by pdurbin** [comment]
@matthew-a-dunlap I see you added the "dev guide" label to this issue and I'm wondering what, if anything, you'd like me to add to pull request #4502.

**Comment by pdurbin** [comment]
@matthew-a-dunlap and I talked about this issue today because I'm still hacking on pull request #4502 and asked what I should do with this issue if I get Netbeans 8.2 and Glassfish 4.1 talking to each other on freshly installed Mac running High Sierra. It worked (based on what I was seeing I made a few tweaks to the dev guide in 72e6b46) so I'm voting that we close this issue unless someone wants to try to reproduce the problem.

**Comment by pdurbin** [comment]
@matthew-a-dunlap heads up that Netbeans 9 is out: "Apache NetBeans 9.0, released on the 29th of July, 2018" https://netbeans.apache.org/download/index.html

**Comment by matthew-a-dunlap** [comment]
Since reporting this bug I've upgraded my machine to High Sierra and started using NetBeans 9.0, and the issue no longer manifests. Whether those are the cause or something else is not certain, but I am closing this.

**Comment by pdurbin** [comment]
Sadly, I'm now suffering from this problem after upgrading to Mac OS X Mojave (10.14). @matthew-a-dunlap has already gotten an earful about this (sorry) but @wadechandler and anyone else who's interested can read about my woes at #5431 😢

**Comment by pdurbin** [comment]
The fix for me was to configure Netbeans for "no proxy" as I explained in 0a5993e in pull request #5438
