### ISSUE TITLE
DatasetIT Failing 

### ISSUE THREAD

**Issue by rbhatta99** [IQSS/dataverse#4094]
The testCreatePublishDestroyDataset was failing due to new behavior. When publishing a dataset with EZID, it is required for th contributor to have an email id, but it is not required to have a name. But, Publishing with datacite require the name of the contributor as well.
As EZID service is shutting down in the future, all EZID installations have to be moved to DataCite eventually, and we will need to make the contributor name as a required field. 
The Integration Test testing this behavior is not changed, and will need to reflect this behavior.
This also relates to issue #3839 .

**Comment by pameyer** [comment]
`creator` is required; but the email requirement isn't from EZID / DataCite spec.

**Comment by sekmiller** [comment]
Tests now passing. Is there a ticket for migrating to DataCite?

**Comment by pdurbin** [comment]
@sekmiller nope, but there should be. We did discuss http://www.cdlib.org/cdlinfo/2017/08/04/ezid-doi-service-is-evolving/ during the 2017-08-15 Dataverse Community Call: https://groups.google.com/d/msg/dataverse-community/RnlJl_y9e1U/nVXKNbd6BQAJ
