### ISSUE TITLE
Swift: When a tabular file is added to swift, any tabular download select button will not work until page refresh by user.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#4102]
This is very specific and has an easy workaround.

When a tabular file is ingested, it show ingest in progress with a download button but not the download select list. When the page updates on ingest complete, the download button changes to a select list. If you do not manually refresh the page, this button does nothing. Refresh and the download list appears and works as expected. Note this does not happen with S3 or local files but happens for all ingested files (s3, local, swift) if any of the files is swift tabular.

**Comment by ferrys** [comment]
I started looking into this a little bit and it seems to be related to `dataset.xhtml`, where there is a comment "For whatever unknown PrimeFaces reason the page needs to be refreshed twice, for all the pull down menus to update properly...".

On both File and S3 storage, you can see the page get refreshed twice, but for some reason it fails with Swift and only gets refreshed once. Going to try to keep looking into this but if anyone has any thoughts...

**Comment by matthew-a-dunlap** [comment]
@ferrys maybe @scolapasta has some input, I know him and Steve were working on something similar with primefaces, I think it was related to hibernate not being up to date.
