### ISSUE TITLE
Notifications: In some cases, users receive more than one notification for a single event, eg. request access.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#4120]
This works as designed but it is a minor UX and technical design issue.
When a user has multiple roles on a dataset, ie. admin and curator, they receive two notifications from a user when they request access to a file. 

This happens when the access permissions to a dataverse grant a user curator rather contributor perms when creating a dataset or dataverse in that dataverse. This is our root config in production, btw.

The "works as designed" part is because curator and admins get the request access notification and if the admin of the dataverse creates a dataset in their own dataverse where curator is granted to a user (them) who creates a dataset, they have both admin and curator roles on that dataset, both of which receive the request.

So: admin maybe should not also get other, lesser roles, admin/curator should only get one notification regardless of how many incidental roles they accrued.

**Comment by mheppler** [comment]
This has been a bothersome issue, reported by @stevenmce from ADA in the Dataverse Community Meeting, as part of the request access workflow for his installation.

**Comment by pdurbin** [comment]
Related:

- #2891
- #8530

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
