### ISSUE TITLE
UI to enable file tags to be searched

### ISSUE THREAD

**Issue by janetm** [IQSS/dataverse#4122]
Hi Team
I would like to suggest a UI to enable file tags to be searched within Datasets as it would definitely enhance the UX.  At the moment fileTags can only be searched within Dataverses which is a bit distant.

https://groups.google.com/forum/?utm_source=digest&utm_medium=email#!topic/dataverse-community/x7zxRADP0q8 
Philip Durbin posted:   If someone would like to create a GitHub issue to build a UI, that would be great. I imagine we would simply add it to the bottom of the Advanced Search page under the "Files" section: https://dataverse.harvard.edu/dataverse/harvard/search

Thanks
Janet

**Comment by shlake** [comment]
Not sure about the API, but searching for data tags only seems to work on search boxes for searching "Dataverses" (using @pdurbin 's hint **fileTags:_code_**) . BUT If you are in a "Dataset" and enter in  the "search this dataset" box the fileTags syntax does not work.
Being able to search within a dataset for fileTags (so all files tagged with same tag could be easily selected) is a needed use case.

**Comment by pdurbin** [comment]
> If you are in a "Dataset" and enter in the "search this dataset" box the fileTags syntax does not work

Yes, this because "Search this dataset" on the dataset page (screenshot below) does a SQL search rather than a Solr search. We've talked about switching the dataset page to use Solr in #2455 but it's a lot of work.

![screen shot 2017-09-05 at 1 20 01 pm](https://user-images.githubusercontent.com/21006/30073795-2f9eb244-923d-11e7-982b-703f9e197456.png)

**Comment by janetm** [comment]
Yes I noticed this too - although when you are looking a files in a dataset you can see the list, but it may be useful to group them if there are a lot of files, like some of the datasets we have.
Janet



On 6 Sep 2017, at 3:15 am, Sherry Lake <notifications@github.com<mailto:notifications@github.com>> wrote:


Not sure about the API, but searching for data tags only seems to work on search boxes for searching "Dataverses" (using @pdurbin<https://github.com/pdurbin> 's hint fileTags:code) . BUT If you are in a "Dataset" and enter in the "search this dataset" box the fileTags syntax does not work.
Being able to search within a dataset for fileTags (so all files tagged with same tag could be easily selected) is a needed use case.

**Comment by mheppler** [comment]
In #5584 there were file facets added to the dataset pg, above the files table, which allows the filter of the table, by file metadata, including "File Tag". While that issue title included the suggestion of _"search using Solr on Dataset Page"_ it appears that it did not add the ability to use the "Search this dataset..." input to filter the table by file tags.

<img width="1149" alt="Screen Shot 2019-06-13 at 3 15 24 PM" src="https://user-images.githubusercontent.com/687227/59460894-2096d700-8dee-11e9-850a-c285558a0db4.png">

<img width="1150" alt="Screen Shot 2019-06-13 at 3 15 40 PM" src="https://user-images.githubusercontent.com/687227/59460902-2391c780-8dee-11e9-9e4f-1403beb132de.png">

**Comment by pdurbin** [comment]
@mheppler good point. I just played around with this at https://dev2.dataverse.org/dataset.xhtml?persistentId=doi:10.5072/FK2/NYNHAM and one thing that surprised me a bit was that even after I added some tags, I didn't see the "File Tag" filter at the top of my dataset. It looked like this:

![Dataverse_IRC_Metrics_-_The_Dataverse_Project_-_2019-06-13_16 01 13](https://user-images.githubusercontent.com/21006/59463811-cea57f80-8df4-11e9-93ba-c1ce380475fc.png)

Then it occurred to me that the "File Tag" filter may not appear until after I click Publish:

![Screen Shot 2019-06-13 at 4 01 45 PM](https://user-images.githubusercontent.com/21006/59463845-e7ae3080-8df4-11e9-8885-a76c4062e36e.png)

This worked fine. As soon as the new version was published, I could see the "File Tag" filter:

![Screen Shot 2019-06-13 at 4 02 03 PM](https://user-images.githubusercontent.com/21006/59463844-e7ae3080-8df4-11e9-80ed-8790ba2d7294.png)

This behavior was a little surprising to me but I'm glad it works. 😄 

@janetm maybe when you're in town next week we can get a sense from you on what more you had in mind for this issue given the changes that are coming above in the next version of Dataverse (the current version is 4.14).

**Comment by TaniaSchlatter** [comment]
This feature has been partially implemented. We need complete addressing this issue by adding the ability search for file tags.

**Comment by scolapasta** [comment]
@landreev since adding the filters, does the search box (for latest published and draft) not use Solr?

**Comment by djbrooke** [comment]
Closing in favor of #7082
