### ISSUE TITLE
Upgrade from 4.6 to 4.6.1

### ISSUE THREAD

**Issue by lbigramUWI** [IQSS/dataverse#4126]
Hi, Currently attempting to upgrade version 4.6 to 4.6.1 but stuck here:

/usr/local/glassfish4/bin/asadmin deploy dataverse-4.6.1.war

remote failure: Error during authorization
java.lang.RuntimeException: java.lang.RuntimeException: java.io.IOException: invalid zip file: file:/DVN/Dataverse4.6.1/dataverse-4.6.1.war
Command deploy failed.

**Comment by pdurbin** [comment]
I looked at https://github.com/IQSS/dataverse/releases/tag/v4.6.1 but I didn't immediately notice anything wrong with the release notes.

@lbigramUWI what do you think about that "invalid zip file" error? Maybe a bad download? Want to try downloading dataverse-4.6.1.war again?

**Comment by lbigramUWI** [comment]
I tried that a couple of times. but still no luck.

**Comment by pdurbin** [comment]
@lbigramUWI hmm. Can you please email support@dataverse.org about this?

**Comment by lbigramUWI** [comment]
okay thanks. will do

**Comment by pdurbin** [comment]
@lbigramUWI great. I wouldn't want to close this issue until you get an email back with a ticket number so once you have it, please us know. Also, please attach your server.log file when you email support. Thanks!

**Comment by lbigramUWI** [comment]
Hi, Resolved the issue. Needed to download the file directly using wget. The server didnt have internet temporarily and I used ftp. But ftp was somehow not copying the whole file.

**Comment by pdurbin** [comment]
Weird. Thanks for letting us know!
