### ISSUE TITLE
MD5s missing from data files

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#4131]
Ran across this during a demo

example below

https://dataverse.harvard.edu/dataset.xhtml?persistentId=hdl:1902.1/12612&version=1.0

is it the timeline of when the data were deposited, in 2009? There are likely more missing MD5s...

**Comment by pdurbin** [comment]
This sounds like something we should add to the "admin" API in the area of dataset integrity checks. We already document how a superuser can use the admin API to recalculate UNF values: http://guides.dataverse.org/en/4.7.1/api/native-api.html#dataset-integrity

**Comment by pameyer** [comment]
One idea for this would be to put a shell script for this into the guides (instead of building it into the application). That would keep the CPU load off the application server.

**Comment by mheppler** [comment]
I reported a similar MD5 display issue earlier this year in #3590.

**Comment by landreev** [comment]
The files in the dataset that Sonia reported above (1902.1/12612) are all old files, created before we started recording checksums. 
I was positive somehow we had generated MD5s for such files retroactively, but I guess not (?)
Will fix shortly. (will verify if there are any recent cases of files that are missing checksums)

**Comment by mheppler** [comment]
In addition to generating the missing checksums, we should fix the display logic bug that assumes there is a checksum and displays an empty "MD5:" label on the page if there isn't.

**Comment by pdurbin** [comment]
@landreev you might be thinking of UNFs. We added a nice "dataset integrity" API endpoint back when we fixed those: http://guides.dataverse.org/en/4.8.3/api/native-api.html#dataset-integrity

**Comment by landreev** [comment]
@pdurbin no, I was definitely thinking of MD5s.

**Comment by landreev** [comment]
@mheppler - I can add a quick "if not empty" check to the search card logic, yes. (we seem to be doing that on the dataset page). 
Or, actually, should it rather say "MD5: MISSING" in all caps - to draw attention to the problem, if it happens again for whatever reason?

**Comment by landreev** [comment]
(after some discussion - we are sticking with the way it's being handled on the dataset page: show the checksum if present; don't show anything if not)

**Comment by landreev** [comment]
Recalculated and added the missing MD5s. 
They should now be appearing on the dataset pages, such as in the dataset mentioned above: 
![screen shot 2017-12-06 at 11 12 02 am](https://user-images.githubusercontent.com/737558/33671759-84a79446-da76-11e7-8172-d3e0caa8fda2.png)
The corresponding datasets still need to be reindexed, for the MD5s to start appearing in the search cards (on the dataverse pages that is).

**Comment by kcondon** [comment]
md5s are now appearing for older dataset files and the md5 label is being hidden if there is not md5 value.
