### ISSUE TITLE
Allow to export metadata of unpublished datasets

### ISSUE THREAD

**Issue by rmo-cdsp** [IQSS/dataverse#4132]
Hello !

I was wondering why we cannot export metadatas of unpublished datasets, while we can with published datasets ? For a matter of quality control, this functionnality would be useful.

**Comment by pdurbin** [comment]
@rmo-cdsp good question. Which format do you want? Dublin Core? DDI? JSON? If you want JSON, a workaround would be to download metadata from the "native" API while passing in an API token of a user who has access to the unpublished dataset.

**Comment by rmo-cdsp** [comment]
@pdurbin It would be on "regular" user side, so using the native api may not be that good. And they are also more into DC and DDI than JSON. To me, the mechanism already available for published datasets would be the best.

**Comment by pdurbin** [comment]
> concerned about how their metadata is being mapped to different standards

Makes sense. Reminds me a lot of this issue: Connect metadata field names and blocks to (de facto) standard ontologies #2357



> they want to be able to check the exported data with their own

@rmo-cdsp how are your researchers doing this check? What tools are they using?

> Why not publish, and then check and adjust?

My impression over the years is that researchers and curators like to get the dataset just right the first time they publish their 1.0 version. Attitudes on this differ, I'm sure. Consider how Nick Lauland from TDL who said, "**I'd like to be able to fix this typo as if it never occurred**, but I'm guessing that opens a whole ball of wax as far as preserving all changes, etc." (emphasis mine) over at https://groups.google.com/d/msg/dataverse-community/HYMHkrQ0dUI/1qreu8kABAAJ

**Comment by BPeuch** [comment]
I second this request. It is something we wished we had during our own testing phase at the State Archives of Belgium.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.

**Comment by pdurbin** [comment]
Related:

- #11305 
- #4372

**Comment by pdurbin** [comment]
@rmo-cdsp and anyone watching this, please see this new PR, which should help:

- #11398
