### ISSUE TITLE
Create a "temporary user role" for user rights testing

### ISSUE THREAD

**Issue by rmo-cdsp** [IQSS/dataverse#4133]
Hello !

I was wondering if a "temporary user role" would be a good idea for user rights testing. This would allow a user managing a dataverse to test the rights he made for each groups, by giving itself a role he actually made with the rights management. Because, for now, all I can see to test rights is to have an account with those rights. Which imply a second account, with another email, etc etc.

I don't know if I'm clear here, don't mind asking me if needed.

**Comment by rmo-cdsp** [comment]
Woaw, sorry for the delay ! Thanks for the answer (and the update). In my case, I would say it is to test the rights the person applied to a dataverse, to be sure that no mistakes were made during the edition.

**Comment by pdurbin** [comment]
@rmo-cdsp is there other software that has something like this?

**Comment by rmo-cdsp** [comment]
@pdurbin The first thing that comes to my mind in the option "see page as" that facebook has. This allow you to look at your profile page as a friend or a guest, for example, and have an idea of what is available to who. 

Just in case, the main idea of this issue comes from a user of our dataverse, I'll try to ask this person to chat here directly, in case it might helps ;)

**Comment by pdurbin** [comment]
@rmo-cdsp hi! Just checking in. Are you or the user you mentioned still interested in this feature?

As a workaround, do you simply have a second account for testing?

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
