### ISSUE TITLE
Move testing calls out of Admin API

### ISSUE THREAD

**Issue by matthew-a-dunlap** [IQSS/dataverse#4137]
The API calls used solely for integration testing have been placed inside the Admin api file. They are not really "admin" functions. These should live on their own, or at least be organized as part of their own sub-path (e.g. /admin/test/).

This work is interconnected with #1886 , in so far as moving calls out of the Admin file may encourage us to switch from a blacklist to a whitelist for default api openness.

**Comment by pdurbin** [comment]
I'm fine with `/admin/test`. We could do that now.

**Comment by pdurbin** [comment]
@matthew-a-dunlap are you still interested in this?
