### ISSUE TITLE
"you have been assigned a role" notification send when a dataset is published

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#4141]
Originally noticed in #3998, but appears unrelated to code changes there.

Depositor with dsContributor creates dataset (with no restricted files), (optionally) submits for review, Curator publishes dataset.  Depositor receives notification that the dataset has been publish, and notification that they have been assigned a role (which isn't necessary to notify them about in this case).

**Comment by matthew-a-dunlap** [comment]
Here are some extra notes to help with QA:
Dataset publish notification goes to users with these permissions:
* Permission.ViewUnpublishedDataset
* Permission.DownloadFile

You should see these notifications in this order when creating a dataset, including when assign a dataset for review:
* Dataset created
* Dataset published
* Role added

Rsync timing should continue to work as intended (notification going out after things are done). Normal notifications should work in the same way.
