### ISSUE TITLE
Message in confirmation popup for submit for review is confusing and unclear

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#4144]
When submitting a file for review, the dialog message is not clear. This message can state what will happen and consequences. Publish message could likewise be improved. Use of term "continue" when executing a command can be misleading.

**Comment by TaniaSchlatter** [comment]
<img width="1007" alt="submit_for_review" src="https://user-images.githubusercontent.com/15386424/30614149-75e535ae-9d58-11e7-904b-28be4c9e9703.png">

**Comment by TaniaSchlatter** [comment]
Sample of an alternative message:

"One this dataset is submitted for review, you will no longer (be able to... describe the outcomes for the user if they complete the submission). 

Are you sure you want to continue?"

(submit)  (cancel)

**Comment by dlmurphy** [comment]
Closing this issue in favor of its more charismatic twin #4188
