### ISSUE TITLE
Handle Support

### ISSUE THREAD

**Issue by lbigramUWI** [IQSS/dataverse#4147]
Hi,

We are adding Handle.Net service to Dataverse. Just clarifying what :Authority Means. Does this refer to the Handle Prefix?

**:Authority
Use the authority assigned to you by your DoiProvider or HandleProvider.

curl -X PUT -d 10.xxxx http://localhost:8080/api/admin/settings/:Authority**

**Comment by lbigramUWI** [comment]
Dataverse is generating this but it seems to be an invalid handle URL. 
hdl:20.500.12122/WWD9VO

**Comment by lbigramUWI** [comment]
Okay, resolved this issue. The path to the private key was incorrect.

**Comment by pdurbin** [comment]
@lbigramUWI I'm glad you were able to figure it out. If you're interested in making a pull request to improve the docs, please get in touch!

**Comment by lbigramUWI** [comment]
Hello Philip,

I don’t mind helping to improve the docs. What’s the procedure?

LB

**Comment by pdurbin** [comment]
@lbigramUWI I'm glad you're interested! Here's my write up of how to make a pull request: http://guides.dataverse.org/en/4.7.1/developers/version-control.html#how-to-make-a-pull-request
