### ISSUE TITLE
Add file-level permissions settings to File Page

### ISSUE THREAD

**Issue by dlmurphy** [IQSS/dataverse#4148]
I've encountered a usability issue while writing docs for dataset permissions that we should fix.

The **file-level** permissions page can only be accessed through the **dataset** page, like so:
![filepermissions1](https://user-images.githubusercontent.com/22962740/30706680-2789b4b4-9ec7-11e7-926e-4ce73971bebf.PNG)

--
The File link pictured above brings you to this page:
![filepermissions2](https://user-images.githubusercontent.com/22962740/30706718-45db6c14-9ec7-11e7-9038-e83e412b67bb.PNG)

On this page, you can click "Grant Access to Users/Groups" to see this modal:
![filepermissions3](https://user-images.githubusercontent.com/22962740/30706760-73402f3c-9ec7-11e7-8269-af4b5f10d4d7.PNG)

Here you can grant specific users access to specific restricted files. As far as I can tell, this is the **only place** you can do this. 

I expected to be able to do this via the file page for each specific file, but I can't find any option to do that:
![filepermissions4](https://user-images.githubusercontent.com/22962740/30707000-1ba5b552-9ec8-11e7-947a-5f93249e4c61.PNG)

I recommend we include a menu option on the file page where I've drawn that arrow, called "Permissions", that takes the user to a page where they can grant specific users access to this file.

Now that we have file pages, it's completely unintuitive to force users to go to the **dataset** level to grant access to a specific **file**.

**Comment by dlmurphy** [comment]
In the issue where I first raised this concern, @scolapasta noted:

> It is true, and technically we could use some aspect of the current ManagePermissionsPage as it could be used for a file. It may not be ideal, but would be the easiest.

**Comment by pdurbin** [comment]
I'm working on a fix for #4268 and I'm also annoyed that I can grant access to a file to somebody from the file page.

**Comment by pdurbin** [comment]
I changed "move" to "add" in the title because people often don't like it when you move their cheese. 🧀
