### ISSUE TITLE
Dataset - Show all terms of use in Terms tab

### ISSUE THREAD

**Issue by TaniaSchlatter** [IQSS/dataverse#4149]
When a user has added terms of use, those terms are displayed in a closed accordion on the terms tab of a dataset page. Per meeting with @sbarbosadataverse people are not seeing the populated terms fields. It is important that all terms be visible – no "Additional Information" text, plus symbol (+) or open/close necessary. 

This applies to terms of access as well.

<img width="1016" alt="screen shot 2017-09-21 at 2 36 25 pm" src="https://user-images.githubusercontent.com/15386424/30712605-92efb18c-9eda-11e7-8380-5612652f4c93.png">
<img width="1011" alt="screen shot 2017-09-21 at 2 36 31 pm" src="https://user-images.githubusercontent.com/15386424/30712604-92ebee30-9eda-11e7-90bf-620117a5360d.png">

**Comment by mheppler** [comment]
Removed collapsible Additional Information panels in Terms tab for dataset pg (view and create).

![screen shot 2017-10-26 at 3 57 50 pm](https://user-images.githubusercontent.com/687227/32074305-e9aff728-ba66-11e7-8a96-ec51a4badce9.png)

![screen shot 2017-10-26 at 3 58 26 pm](https://user-images.githubusercontent.com/687227/32074312-ee24e64c-ba66-11e7-9563-c868c9e89923.png)

**Comment by mheppler** [comment]
Removed references in Dataset Management > User Guide to Additional Information panels in Terms tab for dataset pg (view and create).
