### ISSUE TITLE
Adding a note to the upgrading page

### ISSUE THREAD

**Issue by Thalia-Uranga** [IQSS/dataverse#4151]
Hello all,
My name is Thalia, and i have a problem with dataverse, well the server where it is installed dropped, now I wanted to run glassfish, but now it does not show me the main page of dataverse but the glassfish server, and in the dataverse guide I can not find information to solve this problem. That is why I request to attach information to the upgrading guide.

Thank you for the support.
Regards
Thalia Ur. Mtz

**Comment by pdurbin** [comment]
@Thalia25 thanks for creating this issue! For others reading this, there is some more context at http://irclog.iq.harvard.edu/dataverse/2017-09-25#i_57687

**Comment by pdurbin** [comment]
http://guides.dataverse.org/en/4.8/installation/upgrading.html basically says to go read the release notes. It could also include some commonly used commands such as `asadmin list-applications` to know if Dataverse is deployed or not as well as `asadmin deploy`. The release notes still win on specifics for a release, of course.
