### ISSUE TITLE
Archived versions of restricted data should not allow "download" and "explore" options before showing 500 error bug

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#4154]
I created a new version of a dataset and restricted previously open data files. 
New version was published.
I went back to the archived version and expected to see the data files now restricted, but no lock, red or green, was available (in super user mode or logged out mode). 

The download option showed me all available tabular data options and only when I clicked on any of the download options did it show an error. Two ravens was also still available for me to click on and when I did, it redirected to two ravens but no error message and no variables.

The workflow should be that previously open data files (or any files), in archived versions, should not show explore, or download option, and should have the green or red lock to indicate file is restricted.

**Comment by jggautier** [comment]
I think this is the same as #3576.

**Comment by mheppler** [comment]
Closing this issue in favor of #3576, moved original comment from @sbarbosadataverse there.
