### ISSUE TITLE
Upgrade Solr

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#4158]
We should upgrade Solr to at least a non-EOL version (<6.4). 

It's important to be on a version where we can get support/patches if needed.

**Comment by pdurbin** [comment]
As we work on this issue we should also consider the list of security concerns in https://help.hmdc.harvard.edu/Ticket/Display.html?id=253987

- Is it possible to secure the Solr admin console at http://localhost:8983/solr ? I'm not sure what this means exactly. Perhaps requiring a password?
- How difficult would it be to encrypt traffic between Solr and Dataverse such as with HTTPS?
- Should `enableRemoteStreaming` be enabled or not?

**Comment by kcondon** [comment]
kcondon [4:16 PM] 
https://lucene.apache.org/solr/guide/6_6/upgrading-solr.html


[4:16] 
Users upgrading from older versions are strongly encouraged to consult CHANGES.txt for the details of all changes since the version they are upgrading from.


[4:17] 
Index Format Changes
Solr 6 has no support for reading Lucene/Solr 4.x and earlier indexes. Be sure to run the Lucene IndexUpgrader included with Solr 5.5 if you might still have old 4x formatted segments in your index. Alternatively: fully optimize your index with Solr 5.5 to make sure it consists only of one up-to-date index segment.

**Comment by matthew-a-dunlap** [comment]
I have done work on the code side to make it compile with 6.4.2 / 7.1.0 (both work if switched in the pom). Next step is to get the new server up and running. It looks like with Solr 6+ the default is Solr uses a managed schema instead of a user-editable xml file, tho it seems like you can get it to use the schema.xml with a little effort https://stackoverflow.com/questions/37324603/

**Comment by matthew-a-dunlap** [comment]
Note: The branch above is using 7.1.0, I see that as the best path forward as 6/7 seem similar in terms of dev work

**Comment by matthew-a-dunlap** [comment]
When we upgrade solr, will we be upgrading our existing indexes (as noted by Kevin in https://github.com/IQSS/dataverse/issues/4158#issuecomment-337716287)? Or will we just reindex from scratch?

If we are looking to upgrade our indexes, what is expected related to that in this story? @scolapasta

**Comment by scolapasta** [comment]
I'd say either option is acceptable, whichever works best. (my guess is full reindex will be easier)

**Comment by matthew-a-dunlap** [comment]
My feeling as well! Thanks for the quick feedback

**Comment by matthew-a-dunlap** [comment]
Note: The core configuration work is done, but there are still other config changes needed along with updating of a few scripts.

**Comment by matthew-a-dunlap** [comment]
Looking over the solr init scripts we provide, I do not see any value in maintaining them with 7.2.1 as solr now encapsulates the launching of its jar itself. The commands are along the lines of: "bin/solr start" and "bin/solr stop". The java heap and logging can be set via arguments, e.g. "bin/solr start -m 1g". If there is no objection I will remove these scripts.

**Comment by pdurbin** [comment]
@matthew-a-dunlap no, we still need init scripts. If you reboot a server, how else will Solr start?

**Comment by matthew-a-dunlap** [comment]
@pdurbin isn't the "solr" script just called with a stop/start/restart argument? Can't an admin just call bin/solr in its folder directly? I updated the solr.service script as that seemed needed for automation. Forgive my lack of dev-ops knowledge!

**Comment by matthew-a-dunlap** [comment]
Note, I am specifically talking about this script:
`****
#!/bin/sh

# Starts, stops, and restarts Apache Solr.
#
# chkconfig: 35 92 08
# description: Starts and stops Apache Solr

SOLR_DIR="/usr/local/solr-7.2.1"
SOLR_COMMAND="bin/solr"
SOLR_ARGS=
#JAVA_OPTIONS="-Xmx1024m -DSTOP.PORT=8079 -DSTOP.KEY=mustard -jar start.jar --module=http"
LOG_FILE="/var/log/solr.log"
#JAVA="/usr/bin/java"

case $1 in
    start)
        echo "Starting Solr"
        cd $SOLR_DIR
        $SOLR_
        #$JAVA $JAVA_OPTIONS 2> $LOG_FILE &
        ;;
    stop)
        echo "Stopping Solr"
        cd $SOLR_DIR
        $JAVA $JAVA_OPTIONS --stop
        ;;
    restart)
        $0 stop
        sleep 1
        $0 start
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}" >&2
        exit 1
        ;;
esac
`

**Comment by pameyer** [comment]
With the change from CentOS 6 to Cent OS 7; using a unit file (`solr.service`) for systemd instead of an init script seems reasonable; although init scripts still work on Cent OS 7.

**Comment by matthew-a-dunlap** [comment]
I see now that having a script file to place in init.d is important, I will update the init scripts.

**Comment by matthew-a-dunlap** [comment]
Notes:
* This branch is not compatible with solr 4.6.0 (basic queries work, but dataset creation and larger queries fail). Solr 7.2.1 does not work at all with Dataverse before this branch. They will have to be upgraded in tandem.
* IT Tests pass
* "Normal" Dataverse and vagrant have been tested, but docker/minishift has not been tested. The init, service and other scripts not used in dev environments are also untested.

Question: 
* There are a number of scripts that I updated from solr 4.6.0 to 7.2.1, but I am unsure if they should even be in the project anymore. If you see scripts that are no longer used, feel free to remove them or leave a note and I will do so.

Future work: 
* The approach taken here was to use our old unmanaged schema definitions. This has some maintenance cost as custom metadata changes (there is an api endpoint to generate the custom metadata but it is not ideal. We could look to use managed schema to alleviate this.

**Comment by pameyer** [comment]
checked docker-aio; will need some work (fails to build image). I'm open to treating that as in-scope or out-of-scope for this issue; but let me know if it's out of scope.

**Comment by pdurbin** [comment]
In 693c50a I merged "develop" into the branch and resolved merge conflicts from pull request #4502 for issue #4419. I dropped my database and got set up again and things are looking good from a first glance. I can browse and search data in Solr from Dataverse.

@pameyer please let me know how  I can help with the problem you're seeing with docker-aio. I'm going to keep poking around this branch.

**Comment by pameyer** [comment]
@pdurbin I was seeing `docker build` failures; I'm guessing it was something to do with changed solr config files.  I'll see if I can dig into it more this afternoon.

**Comment by pameyer** [comment]
`solr-7.2.1/server/solr/collection1/conf/` doesn't exist (for `solrconfig.xml` and `schema.xml`) looks to be the problem.  `solr-7.2.1/server/solr/configsets/_default/conf/` or someplace else?

**Comment by pdurbin** [comment]
> docker/minishift has not been tested

I'm getting an error when I cd to `conf/docker` and run `build.sh`:

`/bin/sh: line 0: cd: /usr/local/solr-7.2.1/server/solr/collection1/conf/: No such file or directory`

**Comment by pdurbin** [comment]
In several commits I cleaned up the Java code after talking to @matthew-a-dunlap about it.

Now I'm in the Docker all in one and when running `docker build -t dv0 -f c7.dockerfile .` I'm seeing this:

```
cp: cannot create regular file '/opt/solr-7.2.1/server/solr/collection1/conf/schema.xml': No such file or directory
cp: cannot create regular file '/opt/solr-7.2.1/server/solr/collection1/conf/solrconfig.xml': No such file or directory
```

@pameyer and I were talking about where to install Solr and I'm leaning toward putting it in `/usr/local/solr`. @donsizemore mentioned a symlink but I think we're going to stick with hard-coded paths to specific versions of Solr, like we've done in the past.

**Comment by pdurbin** [comment]
Running `make clean` in `scripts/installer` is throwing warnings:

```
$ cd scripts/installer
$ make clean
Makefile:79: warning: overriding commands for target `dvinstall/schema.xml'
Makefile:74: warning: ignoring old commands for target `dvinstall/schema.xml'
/bin/rm -rf dvinstall dvinstall.zip
```

**Comment by pdurbin** [comment]
Ok, Docker all in one is fixed a of 27dc0a8 (BUILD SUCCESS from conf/docker-aio/run-test-suite.sh) and I fixed the Makefile and put solrconfig.xml in dvinstall.zip in b94795f

Next up is minishift/openshift, where Solr is still broken. Note, however, that Solr is already broken in the develop branch, as I reported at https://github.com/IQSS/dataverse/issues/4040#issuecomment-373189306

**Comment by pdurbin** [comment]
I hope I fixed the minishift/openshift stuff in 97740ce but it's super slow pushing and then downloading our 851 MB dataverse-glassfish to and from Docker Hub to test. As I mentioned at https://github.com/IQSS/dataverse/issues/4040#issuecomment-373189306 Solr is a bit broken there anyway.

I also made some tweaks to the docs. I just dragged this issue to QA. @matthew-a-dunlap will be leaving a "how to test" comment.

**Comment by matthew-a-dunlap** [comment]
Testing notes:
* See previous notes on the work https://github.com/IQSS/dataverse/issues/4158#issuecomment-373824425 . Also Phils subsequent notes on Docker.
* The setup notes for solr should be "tested" in and of themselves. Phil has walked through them and made edits but if anything seems off we should update it.
* Code wise, the most important thing to test is a variety of search queries. We ported over the old schema but its possible things were missed. This was tested a bit but I do not have a good understanding of the depth and breadth of what queries are used.
* Secondly, functionality that create data which is put into solr should be tested. I know OAI Harvesting & Indexing were touched with the code changes alongside search in Dataverse.

**Comment by matthew-a-dunlap** [comment]
Looks good after merging develop with the index memory leak fix. All you @kcondon .

**Comment by kcondon** [comment]
Issues found:
-Under Installing Solr in Installations guide, prereq's change \ to /:
http://guides.dataverse.org/en/4158-update-solr/installation/prerequisites.html
cp -r configsets\_default .
cp: cannot stat `configsets_default': No such file or directory

**Comment by pdurbin** [comment]
@kcondon after we talked I made many tweaks to the docs in 41a7ea9

Please take a look. Thanks.

**Comment by pdurbin** [comment]
> As we work on this issue we should also consider the list of security concerns in https://help.hmdc.harvard.edu/Ticket/Display.html?id=253987
> 
> -    Is it possible to secure the Solr admin console at http://localhost:8983/solr ? I'm not sure what this means exactly. Perhaps requiring a password?
> -    How difficult would it be to encrypt traffic between Solr and Dataverse such as with HTTPS?
> -    Should enableRemoteStreaming be enabled or not?

I took a quick look at these questions. I think they're all out of scope in the sense that we probably won't address any of them when using Solr in production at Harvard Dataverse. Firewalling off Solr is enough for us. That said, it looks like the Solr project has documentation on each of the topics above:

- http://lucene.apache.org/solr/guide/7_2/authentication-and-authorization-plugins.html
- http://lucene.apache.org/solr/guide/7_2/enabling-ssl.html
- http://lucene.apache.org/solr/guide/7_2/content-streams.html#remote-streaming

People who are interested in these topics should read the documentation above.

**Comment by pdurbin** [comment]
At standup I mentioned that a basic search of the identifier was working from Solr directly but not from Dataverse. The difference is that my curl command against Solr was using the default `/select` request handler but Dataverse has been using the `/spell` request handler. In d3b721e I switched Dataverse back to the default `/select` request handler and included a long commit message explain that I was planning with the "spelling suggestions" ("did you mean?") feature of Solr early in the Dataverse 4.0 rewrite and inadvertently left `/spell` in the code. Now basic search works fine on an identifier (i.e. JNIUOA).

**Comment by pdurbin** [comment]
I just gave a brain dump to @kcondon about recent fixes, including how in a7fd43a I made it so that "Dataset Persistent ID" shows up instead of "Match":

![screen shot 2018-03-27 at 10 43 05 am](https://user-images.githubusercontent.com/21006/37983468-9326c3fa-31c1-11e8-9cfa-c2232b97172e.png)

**Comment by pdurbin** [comment]
I checked in with @kcondon this morning and he mentioned that highlighting of search fields is not working as consistently as on the develop branch. I tested this as of a088d5e on the Solr branch and he's right. The good news is that the object can still be found with a search so it sounds like we might merge the pull request without a fix (we'd open a new issue and fix it later) but I'm assigning myself to this issue to at least poke around a bit and characterize the bug better. Perhaps I'll write some automated tests that exercise the bug.

**Comment by pdurbin** [comment]
I'm on the same commit (a088d5e) and this highlighting bug is really strange. It seems to be based on the data entered.

For example, when filling in "otherIdAgency" if I use the value "agency1", the highlighting works. Notice "otherIdAgency" under "highlighting" at the bottom of this JSON output:

`curl 'http://localhost:8983/solr/collection1/select?rows=1000000&wt=json&indent=true&hl=true&hl.fl=*&q=agency1'`

```
{
  "responseHeader":{
    "status":0,
    "QTime":1,
    "params":{
      "q":"agency1",
      "hl":"true",
      "indent":"true",
      "hl.fl":"*",
      "rows":"1000000",
      "wt":"json"}},
  "response":{"numFound":1,"start":0,"docs":[
      {
        "id":"dataset_124_draft",
        "entityId":124,
        "dataverseVersionIndexedBy_s":"4.8.5",
        "identifier":"doi:10.5072/FK2/M8KVFJ",
        "dsPersistentId":"doi:10.5072/FK2/M8KVFJ",
        "persistentUrl":"https://doi.org/10.5072/FK2/M8KVFJ",
        "dvObjectType":"datasets",
        "publicationStatus":["Unpublished",
          "Draft"],
        "dateSort":"2018-03-28T20:29:59.697Z",
        "dateFriendly":"Mar 28, 2018",
        "isHarvested":false,
        "metadataSource":"Root",
        "datasetVersionId":51,
        "citation":"Admin, Dataverse, 2018, \"429\", https://doi.org/10.5072/FK2/M8KVFJ, Root, DRAFT VERSION",
        "citationHtml":"Admin, Dataverse, 2018, \"429\", <a href=\"https://doi.org/10.5072/FK2/M8KVFJ\" target=\"_blank\">https://doi.org/10.5072/FK2/M8KVFJ</a>, Root, DRAFT VERSION",
        "nameSort":"429",
        "title":"429",
        "otherIdAgency":["agency1"],
        "authorName":["Admin, Dataverse"],
        "authorName_ss":["Admin, Dataverse"],
        "affiliation_ss":["Dataverse.org"],
        "authorAffiliation":["Dataverse.org"],
        "authorAffiliation_ss":["Dataverse.org"],
        "datasetContactName":["Admin, Dataverse"],
        "datasetContactAffiliation":["Dataverse.org"],
        "dsDescriptionValue":["test"],
        "subject":["Agricultural Sciences"],
        "subject_ss":["Agricultural Sciences"],
        "depositor":"Admin, Dataverse",
        "dateOfDeposit":"2018",
        "dateOfDeposit_s":"2018",
        "parentId":"1",
        "parentName":"Root",
        "_version_":1596215048611561472}]
  },
  "highlighting":{
    "dataset_124_draft":{
      "otherIdAgency":["<em>agency1</em>"]}}}
```

But if I fill in "otherIdAgency" with the value "agency", no highlight appears:

`curl 'http://localhost:8983/solr/collection1/select?rows=1000000&wt=json&indent=true&hl=true&hl.fl=*&q=agency'`

```
{
  "responseHeader":{
    "status":0,
    "QTime":1,
    "params":{
      "q":"agency",
      "hl":"true",
      "indent":"true",
      "hl.fl":"*",
      "rows":"1000000",
      "wt":"json"}},
  "response":{"numFound":1,"start":0,"docs":[
      {
        "id":"dataset_90",
        "entityId":90,
        "dataverseVersionIndexedBy_s":"4.8.5",
        "identifier":"doi:10.5072/FK2/LM1ZLY",
        "dsPersistentId":"doi:10.5072/FK2/LM1ZLY",
        "persistentUrl":"https://doi.org/10.5072/FK2/LM1ZLY",
        "dvObjectType":"datasets",
        "dateSort":"2018-03-27T16:38:18.189Z",
        "dateFriendly":"Mar 27, 2018",
        "publicationStatus":["Published"],
        "publicationDate":"2018",
        "dsPublicationDate":"2018",
        "isHarvested":false,
        "metadataSource":"Root",
        "datasetVersionId":35,
        "citation":"Finch, Fiona, 2018, \"test search\", https://doi.org/10.5072/FK2/LM1ZLY, Root, V1",
        "citationHtml":"Finch, Fiona, 2018, \"test search\", <a href=\"https://doi.org/10.5072/FK2/LM1ZLY\" target=\"_blank\">https://doi.org/10.5072/FK2/LM1ZLY</a>, Root, V1",
        "nameSort":"test search",
        "title":"test search",
        "subject":["Medicine, Health and Life Sciences"],
        "subject_ss":["Medicine, Health and Life Sciences"],
        "subtitle":"subtitle",
        "otherIdAgency":["agency"],
        "authorName":["Finch, Fiona"],
        "authorName_ss":["Finch, Fiona"],
        "affiliation_ss":["Birds Inc."],
        "authorAffiliation":["Birds Inc."],
        "authorAffiliation_ss":["Birds Inc."],
        "datasetContactName":["Finch, Fiona"],
        "dsDescriptionValue":["Darwin's finches (also known as the Galápagos finches) are a group of about fifteen species of passerine birds."],
        "subtreePaths":["/89"],
        "parentId":"89",
        "parentName":"dvf9916eda",
        "_version_":1596214687686459392}]
  },
  "highlighting":{
    "dataset_90":{}}}
```

**Comment by pdurbin** [comment]
After standup this morning @djbrooke @scolapasta @kcondon and I talked about the highlighting issues we're seeing. I just did some initial investigation to give me confidence that highlighting seems to work just fine in Solr 7.2.1 when you use their example config and data. I just opened #4557 to post these results and so that we have a issue to estimate in the future. We decided that the highlighting issues are not a show stopper for merging pull request #4520.

**Comment by matthew-a-dunlap** [comment]
fwiw I plan to take another look at our solr config tomorrow to see if something related to the highlighting shows itself, but I'd be surprised if I find anything.

**Comment by matthew-a-dunlap** [comment]
I tried diffing the solr configs, but due to the porting of our customization between the two versions of the stock config this approach did not reveal any info with our minor bugs

**Comment by pdurbin** [comment]
I just merged the latest from develop into the pull request: 5f67e56
