### ISSUE TITLE
Code in WorldMap related to dataverse needs to be updated

### ISSUE THREAD

**Issue by capooti** [IQSS/dataverse#4164]
We are in the process to release a new version of WorldMap in the next few weeks, based on latest GeoNode version.

We already migrated the datatables application, which is now part of GeoNode, but we noticed there is some more applications which was developed by @raprasad to interact with it. We believe a migration is needed for these applications too.

How it is in actual worldmap: https://github.com/cga-harvard/cga-worldmap/tree/legacy/geonode/contrib

<img width="1119" alt="screenshot 2017-09-26 16 40 37" src="https://user-images.githubusercontent.com/148380/30883205-70c8ffac-a2d9-11e7-9030-74bea952380c.png">

So the applications which would need to be ported are:

* dataverse_connect
* dataverse_layer_metadata
* dataverse_permission_links
* dataverse_styles

**Comment by raprasad** [comment]
@capooti @djbrooke 
- Those applications would need to be ported as well as a second look at **datatables**
- Was **datatables** migrated from the legacy WorldMap of a few months ago into geonode? 
  - **Yes**:  If so, it may be ok. 
  - **No**:  If datatables already existed in geonode last year, then WorldMap datatables and geocode datatables are probably much different
- The **datatables** in the link you sent is slightly intertwined with dataverse; specifically it contains:
   - datatables/urls_dataverse.py
   - datatables/views_dataverse.py

reference: https://github.com/cga-harvard/cga-worldmap/tree/legacy/geonode/contrib/datatables

**Comment by capooti** [comment]
An update on this after talking with @raprasad  yesterday.

The migrated version of the datatables application was migrated from GeoNode and not from WorldMap (we were not aware that it was changed by @raprasad), so answer to first question is "No". But we will do the migration of the application modified by @raprasad in the next few days.

There are still the other 4 applications (dataverse_connect, dataverse_layer_metadata, dataverse_permission_links, dataverse_styles) which need to be migrated though.

**Comment by pdurbin** [comment]
@capooti is this still something you need? If so, when? Thanks!

**Comment by capooti** [comment]
Hi @pdurbin sorry for late answer, I was in vacation.
I'd say you can close this and we can re-open when needed, as I am not sure when new WorldMap version is going to be launched! /cc @blewis
