### ISSUE TITLE
Workflows should not be a standalone guide, reorder list of guides

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#4167]
I was just looking at http://guides.dataverse.org/en/4.8/ and was surprised to see that "Workflows" has been elevated to the level of a guide. Now there are seven guides:

- User Guide
- Installation Guide
- API Guide
- Developer Guide
- Style Guide
- Admin Guide
- Workflows

It seems a bit excessive for Workflows to be its own guide. I can image that it would fall neatly under a page in the Admin Guide, for example, for merged with http://guides.dataverse.org/en/4.8/developers/big-data-support.html since it seems like is mostly related to the new rsync feature in 4.8. It's a single page and not all that long as you can tell from the scroll bar:

<img width="1168" alt="screen shot 2017-09-26 at 11 15 42 pm" src="https://user-images.githubusercontent.com/21006/30894324-2a958202-a311-11e7-8d4e-c6a75fa71426.png">

Sorry I missed this during code review. Oh, and while we're in there, let's reorder the guides into a more logic order based on number of people who will be looking at them (users, sysadmins, and developers) and keep related guides together, like this:

- User Guide
- API Guide
- Installation Guide
- Admin Guide
- Developer Guide
- Style Guide

**Comment by scolapasta** [comment]
If we reorder, I'd suggest putting Admin Guide as the 2nd guide in the list.

**Comment by pdurbin** [comment]
@scolapasta for me it's a numbers game. I think there are more ends users than API users. I think there are more API users than people who install Dataverse. It would be interesting to have the real numbers on this.

**Comment by scolapasta** [comment]
Sure, but there are more admins than installers. My logic was based on the fact that much of the Admin guide is about doing through the UI and that feels like it belongs before API. It's kind of an user guide part 2.

**Comment by pdurbin** [comment]
The Admin guide is for superusers. I'm saying that I think there are more API users than superusers. We could compare the number of API tokens vs. the number of people with the superuser boolean.

**Comment by scolapasta** [comment]
Sorry, wasn't completely clear in my last comment: I think it should definitely go before installer.

Whether it or API comes first, I vote for Admin, but I'm I see arguments for both. (I don't know if I agree that # of users should be the sole reasoning, however).

**Comment by pdurbin** [comment]
I made pull request #4273 and moved this issue to code review at https://waffle.io/IQSS/dataverse

**Comment by dlmurphy** [comment]
I agree with @scolapasta that the Admin Guide should come second on the list behind the User Guide, since the Admin Guide is the only other guide that focuses on getting things done using the UI. I think the right approach with this listing is to take the likely number of users of the guide into account, but also balance it with the need to organize the guides in a way that makes conceptual sense. 

This is the order I'd prefer: 
User Guide (end users using the UI)
Admin Guide (superusers using the UI)
API Guide (end users using the back end)
Installation Guide (stakeholders using the back end)
Developer Guide (developers developing the back end)
Style Guide (developers developing the UI)

I think that this is an intuitive way of organizing the guides that still generally gives preference to the guides that see the most users.

**Comment by dlmurphy** [comment]
The new positioning of the Workflow section looks good. Moving to QA.

**Comment by pdurbin** [comment]
> Admin Guide (superusers using the UI)

I'm just glad that there is understanding that the Admin Guide is for superusers (a vanishingly small number of users in a typical installation) not what Dataverse calls an Admin. This confusion has been noted in spreadsheet linked in the new issue about creating a glossary (#4274) for terms used in Dataverse.

> Installation Guide (stakeholders using the back end)

This is confusing to me. I would say "sysadmins installing server-side software" or something. I'm not sure why sysadmins alone are called stakeholders above.

**Comment by dlmurphy** [comment]
Fair, "sysadmins installing the server-side software" is a more precise way to describe that guide.
