### ISSUE TITLE
Admin guide - document useful database queries

### ISSUE THREAD

**Issue by dlmurphy** [IQSS/dataverse#4169]
As part of a metrics gathering project, @jggautier and I are writing SQL queries to help us learn about the usage statistics of different Dataverse features. @pdurbin suggested that we add some of the most useful of these queries to the Admin Guide. This way we can share this work with the community, helping admins of various Dataverse installations to more easily query their own databases.

Let's determine which page of the Admin Guide this should appear on (or create a new page for it) and then list all of the helpful queries we've come up with.

While we're writing queries, we're listing them in [this Google doc](https://docs.google.com/document/d/1-Y_iUduSxdDNeK1yiGUxe7t-Md7Fy965jp4o4m1XEoE/edit?usp=sharing), which anyone is welcome to contribute to, including members of the wider Dataverse community.

**Comment by pdurbin** [comment]
@jggautier did a great job of introducing the great work he and @dlmurphy have been doing on the 2017-10-10 Dataverse Community Call. Here are the notes I posted at: https://groups.google.com/d/msg/dataverse-community/HKuQUrmdmE8/r7WJXLbsAwAJ

  * (Julian) Derek and I have been figuring out a process to determine the usage of various features within Dataverse. We now have access to a copy of the Harvard Dataverse database and have been writing SQL queries, shared in https://github.com/IQSS/dataverse/issues/4169
      * (Kevin W.) How does this relate to miniverse? We may be interested in running it some day. Downloads by dataverse would be interesting.
         * (Julian) Perhaps this could lead to improvements in miniverse.
      * (Amber) We're interested in an institutional view of usage (where each institution is its own dataverse within an installation).
      * (Courtney) We also have a need for an institutional view. We have set up miniverse.
      * (Phil) It might be easier to maintain the code within Dataverse itself.
      * (Kevin W.) We'd rather have the metrics built into Dataverse especially if miniverse isn't well maintained.
      * (Pete) Are we talking about two types of usages? Software vs users.
         * (Danny) We want product development to be informed by metrics.
      * (Sherry) There's also Altmetrics and similar that can take into consideration citations and views outside of Dataverse. The "coming soon" text is gone.
      * (Courtney) We don't have the greatest usage statistics coming out of the system, which is what we're asked for the most.
      * (Pete) One more vote of agreement for having metrics built into Dataverse.
