### ISSUE TITLE
URL formatting: escape text in URLs

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#4175]
Reported by user, see RT: 
https://help.hmdc.harvard.edu/Ticket/Display.html?id=253865
https://help.hmdc.harvard.edu/Ticket/Display.html?id=253907
and
https://help.hmdc.harvard.edu/Ticket/Display.html?id=235101

**Comment by pdurbin** [comment]
https://help.hmdc.harvard.edu/Ticket/Display.html?id=253232

**Comment by matthew-a-dunlap** [comment]
Fixed in 4.8. See ticket for more info
