### ISSUE TITLE
document monitoring of EJB timers

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#4180]
Possibly related to #3672 , #3467 , #2595 ; if the EJB timers are one of the things that can fail in production it would be helpful to update `doc//sphinx-guides/source/admin/monitoring.rst` with information about how to know when the timer(s) are failing.

Potentially useful info https://docs.oracle.com/cd/E18930_01/html/821-2418/beahw.html (but for glassfish 3.1).

**Comment by pdurbin** [comment]
I just took a look at pull request #4182 by @pameyer and it looks great. I'll move it to QA.
