### ISSUE TITLE
UI Performance - investigate improvements to static file handling

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#4181]
Possibly related: #2647 , #1330

7 CSS files in `dataverse_template.xhtml`,  8 JS files; mix of minified and un-minified.  These could potentially be combined (during the build process, not in source) to reduce the number of requests browsers need to make to render the page, which should help with UI performance.  The slow step is still likely to be time for glassfish to generate the (x)html.

**Comment by mheppler** [comment]
@pameyer closing this issue in favor of **Peformance: Use a CDN for css, javascript, and static images #2647** and moved your comment there.

**Comment by mheppler** [comment]
Reopening this to see if community developer @pameyer is still interested in investigating these improvements to the UI. With UI redesign efforts under way, there is ample opportunity to improve our product, specifically related to UI perfomance.

**Comment by pameyer** [comment]
@mheppler - I'm still interested.

**Comment by pdurbin** [comment]
Not a bad idea but I'm closing this because [the JSF UI is going away](https://groups.google.com/g/dataverse-community/c/2hfhWIHQddE). We can revisit in the new React repo someday, perhaps: https://github.com/IQSS/dataverse-frontend
