### ISSUE TITLE
Unable to verify email address

### ISSUE THREAD

**Issue by orbitinc** [IQSS/dataverse#4183]
The Dataverse code (as of 4.8 and apparently well before) does put a period right at the end of the verify email link.

**Comment by pdurbin** [comment]
@orbitinc thanks for opening this issue.

@dlmurphy make commit 3cfb39e in pull request #4177 which is already in QA so I'm moving this issue to QA at https://waffle.io/IQSS/dataverse and will use the magic Waffle syntax to associate the pull request with this issue.
