### ISSUE TITLE
API tests are failing

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#4189]
API tests are failing as of 4.8 and 4.8.1:

- edu.harvard.iq.dataverse.api.DatasetsIT.testCreateDatasetWithDcmDependency
- edu.harvard.iq.dataverse.api.DatasetsIT.testDcmChecksumValidationMessages
- edu.harvard.iq.dataverse.api.InReviewWorkflowIT.testCuratorSendsCommentsToAuthor

Here's a screenshot:

<img width="1393" alt="screen shot 2017-10-11 at 11 16 40 pm" src="https://user-images.githubusercontent.com/21006/31477497-4806c9de-aeda-11e7-9716-855fdc92aa4b.png">

That's from https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-apitest-develop/142/testReport/

**Comment by pdurbin** [comment]
> InReviewWorkflowIT.testCuratorSendsCommentsToAuthor

Fixed in d3125d5. As discussed with @sekmiller there was a FIXME I was also able to remove.

**Comment by pdurbin** [comment]
I changed my mind and created a new branch called `4189-fix-api-tests` and created pull request #4199 for just the fixes for the API tests. Moving to code review.

**Comment by pdurbin** [comment]
https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-apitest-develop/143/ is passing! Hooray!

**Comment by pdurbin** [comment]
DatasetsIT.testPrivateUrl started failing at https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-apitest-develop/edu.harvard.iq$dataverse/145/testReport/junit/edu.harvard.iq.dataverse.api/DatasetsIT/testPrivateUrl/ as of 6b53fa13742c85a4cf0a2f7ae31fea5e48494526 and I'm hoping 3c8adc2 fixes it.

**Comment by kcondon** [comment]
I almost merged this, luckily I noticed it was the bigger pull request.

**Comment by pdurbin** [comment]
Good news. Now the pull request #4216 has been merged, all API tests are passing again:

<img width="1362" alt="screen shot 2017-11-03 at 7 34 36 pm" src="https://user-images.githubusercontent.com/21006/32399653-2b8fd646-c0ce-11e7-85a2-c0c6dc9ebc02.png">

That is to say, build 146 is blue rather than yellow: https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-apitest-develop/
