### ISSUE TITLE
Error message for wrong/missing dataverse is not clear

### ISSUE THREAD

**Issue by bjonnh** [IQSS/dataverse#4196]
Going to an url with a wrong dataverse name (note the parenthesis at the end):
https://dataverse.harvard.edu/dataverse/cenaptnmr)

gives the following error message:
 Validation Error – Required fields were missed or there was a validation error. Please scroll down to see details.

I think we should at least have something saying:
"This dataverse doesn't exist. Check your spelling and if you expect it to be here, contact the owner as they may have not published it yet."

And even better something like:
"This dataverse doesn't exist, did you mean <cenaptnmr>. Check your spelling and if you expect it to be here, contact the owner as they may have not published it yet." Where <cenaptnmr> is the link to the closest dataverse name accessible.

**Comment by pdurbin** [comment]
Yeah, that's weird. @bjonnh thanks for opening this issue. Affects Dataverse 4.8.1. Here's a screenshot:

![screen shot 2017-10-13 at 10 32 02 am](https://user-images.githubusercontent.com/21006/31551249-f1e981c6-b001-11e7-9a46-40ca89413117.png)

Here's a clickable link that turns `%29` into `)` to reproduce the bug:

https://dataverse.harvard.edu/dataverse/cenaptnmr%29

**Comment by pdurbin** [comment]
It's returning a 200 when it should return a 404:

```
$ curl -s -i 'http://localhost:8080/dataverse/trees%29' | head -2
HTTP/1.1 200 OK
Server: GlassFish Server Open Source Edition  4.1 
```

**Comment by djbrooke** [comment]
Let's return the correct error code here instead of trying to add dynamic text or other solutions.

**Comment by mheppler** [comment]
Highly related/duplicates:
- Dataverse URL - Page Not Found (404 Error) w/ Trailing Forward Slash #3130
- Dataverse URL - Validation Error for Bad URL with "." #2559

**Comment by mheppler** [comment]
Tried to reproduce this issue (originally discovered in 4.8.1) on demo (5.3) and could not. I am seeing the proper 404 Page Not Found error msg. Same with a URL that contains a misplaced `.` character at the end, as reported in #2559.

I have dug through GitHub, and consulted @landreev but could not find any evidence on what changes and in what release, this issue may have been resolved in. Closing as not reproducible.

<img width="1110" alt="Screen Shot 2021-02-17 at 1 52 33 PM" src="https://user-images.githubusercontent.com/687227/108253741-20ed8680-7128-11eb-9a03-27e7bea92117.png">
