### ISSUE TITLE
Add Dataverse - Root's theme logo mistakenly displayed when creating dataverse

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#4198]
When creating a new dataverse under the root, the logo image belonging to the root's theme is mistakenly displayed. For an example, I took a screenshot of a new dataverse that I was creating under the Harvard Dataverse, which displays the Harvard logo in the header. There should no logo displayed for a new dataverse, which is the default view.

![screen shot 2017-10-11 at 4 40 51 pm](https://user-images.githubusercontent.com/687227/31465938-75078450-aea3-11e7-8c04-47526f9bd459.png)

**Comment by matthew-a-dunlap** [comment]
The fix for this was to tell the system that the new dataverse was its own root before creation takes place. Thanks to @mheppler & @scolapasta for most of the lifting and letting me connect the dots.

**Comment by pdurbin** [comment]
bcbc5cc looks good so when @matthew-a-dunlap makes a pull request from the `4189-new-dataverse-theme` branch I'll be happy to go ahead and approve it and move this issue from Code Review to QA at https://waffle.io/IQSS/dataverse
