### ISSUE TITLE
Test Automation: Investigate, specify, prototype a build-time, UI-based smoke test.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#4200]
Create a UI-based automated smoke test that can be run with each build. It should:
1. create a new user
2. create a dataverse
3. create a dataset
4. upload file(s)
5. publish dataset/dataverse
6. download file(s)

Ideally, tool should be in popular use and free. We would like to make these tests available to partners to run.

**Comment by djbrooke** [comment]
We discussed this in backlog grooming 11/15 and the estimates ranged from 3-13. We'll try again in a future session.

**Comment by pdurbin** [comment]
We're using Cypress for the new UI: https://github.com/IQSS/dataverse-frontend
