### ISSUE TITLE
Test Automation: Investigate, specify, prototype a performance test suite that can be run at build time.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#4201]
Produce a performance test suite that can run at build time.
Initially, it should measure the performance of the most frequently accessed pages: dataset, dataverse.

There are some open questions about what constitutes an effective performance test suite: whether it needs to be deterministic of production performance, requiring the same servers and data or whether it can be used as a relative measure of performance using a range of real and/or synthetic data, such as larger lists of parent/child objects, eg. dataverse with datasets, datasets with files.

**Comment by pdurbin** [comment]
I'd recommend watching the video created https://github.com/BU-NU-CLOUD-SP18/Dataverse-Scaling#our-project-video that was created by BU students Ashwin Pillai, James Michael Clifford, Ryan Morano, and Patrick Dillon in April 2018.

They're using JMeter and here are some screenshots from around 17:38:

![screen shot 2018-04-30 at 1 42 42 pm](https://user-images.githubusercontent.com/21006/39441952-9c7a4a18-4c7d-11e8-806f-7137605366e0.png)
![screen shot 2018-04-30 at 1 44 33 pm](https://user-images.githubusercontent.com/21006/39441953-9c86434a-4c7d-11e8-8df6-171dbbba3956.png)
![screen shot 2018-04-30 at 1 44 48 pm](https://user-images.githubusercontent.com/21006/39441954-9c9225d4-4c7d-11e8-8840-c3ba1c02d8cf.png)
![screen shot 2018-04-30 at 1 45 04 pm](https://user-images.githubusercontent.com/21006/39441955-9c9d616a-4c7d-11e8-9008-a4828433fbdb.png)
![screen shot 2018-04-30 at 1 45 25 pm](https://user-images.githubusercontent.com/21006/39441957-9cb90e9c-4c7d-11e8-8722-bf47278d8ece.png)

**Comment by rockash** [comment]
The above tests have been run on a Minishift deployment of the containerized Dataverse application used for our class group project [Dataverse Scaling](https://github.com/BU-NU-CLOUD-SP18/Dataverse-Scaling.). I have documented steps for creation of my simple Jmeter test to test the Dataverse deployment. I have also added two Jmeter ".jmx" files. 

"**Dataverse Load testing template.jmx**" is a file which can be used with the steps for test creation on Jmeter to make a customized test plan as needed. 

"**MOC Project Dataverse Scaling_Load testing.jmx**" can be used to test the deployment with minor changes in the test plan adding or reducing users/threads. 

Please access these files using the drive link below - 
[Dataverse Load Testing using Jmeter](https://drive.google.com/drive/folders/1T7KwTxBDtSeCaibxzuen5h993V30JxCp?usp=sharing)

**Comment by pdurbin** [comment]
@rockash thanks! I gave you a 🎉 back when you uploaded your Jmeter jmx files and doc but thanks again. Much appreciated. 😄 I'm attaching the files to this issue for extra safe keeping: [Dataverse Load testing using Jmeter-20190708T162312Z-001.zip](https://github.com/IQSS/dataverse/files/3369309/Dataverse.Load.testing.using.Jmeter-20190708T162312Z-001.zip)

Speaking of Jmeter, as I mentioned at standup this morning, a couple of weeks ago @4tikhonov said he plans to use Jmeter in his development efforts for SSHOC.

Someone recorded his talk! You can hear him talking about Jmeter at https://youtu.be/vAPpKuDQUDY?t=341

Here's the Jmeter slide from https://osf.io/cqsrj/

![jmeter](https://user-images.githubusercontent.com/21006/60826318-90914680-a17b-11e9-9a57-f9a0f01cc4f4.png)

**Comment by pdurbin** [comment]
During sprint planning today we talked about a lot of stuff including:

- We should determine where these numbers go so that we can view historical trends

I don't know which tools we should use but from a quick look Jenkins has a "performance" plugin ( https://plugins.jenkins.io/performance ) that shows historical trends for throughput, response time, etc. Here's a screenshot from https://stackoverflow.com/questions/53411347/jenkins-display-multiple-jmeter-report-jtl-in-single-graph

![IX1RI](https://user-images.githubusercontent.com/21006/63893041-221c7800-c9b7-11e9-9d58-4497c212e07f.png)

I'm not trying to specify any particular tool at this point but this is what I mean when I say that we should gather the metrics over time into a database or whatever, hopefully in an automated fashion. Ideas for tools are welcome!

**Comment by pdurbin** [comment]
We want this but when? Let's open a fresh issue closer to when we plan to work on it.

**Comment by pdurbin** [comment]
Related:

- #12365
