### ISSUE TITLE
Test Automation: Investigate, specify, prototype a UI-based configuration test suite.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#4202]
Create a regression test suite that verifies the correct function of our various storage drivers and their UI rules: local file system, S3, Swift, and Rsync

**Comment by pdurbin** [comment]
Related: #5846

**Comment by poikilotherm** [comment]
BTW: I just discovered that BrowserStack offers their Selenium Grid for free to OSS products. Maybe this would offload things like running the grid, which is a huge thing?

https://www.browserstack.com/open-source
