### ISSUE TITLE
Notifications: investigate Dataverse email handling issues by Yahoo and Gmail 

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#4206]
Note: this happens only on demo. on test boxes like internal, it is delivered fast and to the inbox

It appears Dataverse email notifications are not received well and consistently by email providers like Yahoo and Gmail but works better with test site Mailinator.

Email may not appear, appears slowly, shows up as spam. It is not yet clear if there is a pattern but it may be related to the html links and domains of such links in the mail body or perhaps a difference between sender and reply to addresses.

Yahoo appears to convert links to plain text so that indicates some additional processing based on html and it puts all email in spam. Email was slow to appear

**Comment by donsizemore** [comment]
Kevin,

I'm just going through this with UNC Dataverse and UNC's hosted Office 365 mailsystem. E-mail verification messages from our Dataverse show up properly in my personal Gmail, but the Office365 spam checker strips the sentence containing the verification token.

Beyond having UNC whitelist us in three ways (spam, connection, spoofing), one recommendation I overlooked was to make the :SystemEmail setting match the address specified in domain.xml.

**Comment by kcondon** [comment]
Cool, so do you think it is a domain mismatch issue between system email domain and the mail server domain in domain.xml?

**Comment by kcondon** [comment]
@donsizemore You are the hero for the day! That seemed to fix the problem. Thanks!
