### ISSUE TITLE
Test Automation: Write a UI-based test script to create a new user.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#4207]
Use something like Selenium to produce a test script to create a user.

**Comment by pdurbin** [comment]
I just spotted a couple slides about Selenium testing from @4tikhonov at https://twitter.com/4tykhonov/status/1116229640232873984

![dataversesshocdevelopment-190411063200-10](https://user-images.githubusercontent.com/21006/55956012-f29be780-5c30-11e9-9ada-52f48523c419.png)

![dataversesshocdevelopment-190411063200-11](https://user-images.githubusercontent.com/21006/55956020-f4fe4180-5c30-11e9-9a8f-bd494912e42d.png)

**Comment by pdurbin** [comment]
If we'd like to strike while the iron is hot @rschlaefli is offering to help us with browser-based test automation in #5846

**Comment by poikilotherm** [comment]
You should get in touch with @4thikonov... We had a video conference the other day and they are eager getting Selenium in place like @pdurbin described above. This could be very useful for testing for a successfull deployment, too.

**Comment by pdurbin** [comment]
We're using Cypress for the new UI: https://github.com/IQSS/dataverse-frontend
