### ISSUE TITLE
User experience for curators editing datasets that are in review

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#4209]
As of b2cf086 in pull request #4208 for #4139 curators see a double message of green and yellow when editing metadata for a dataset that's in review:

- Green: Success! – The metadata for this dataset has been updated.
- Yellow: Dataset Locked This dataset has been submitted for review.

I find this confusing. Here's a screenshot:

![yellow-plus-green](https://user-images.githubusercontent.com/21006/31631252-2f95482a-b287-11e7-9f51-bbe7a46f6944.png)

I'm opening this issue at @mheppler 's request so that development for #4139 is not held up.

**Comment by dlmurphy** [comment]
Having two messages at the top of the page might feel like clutter, but in this (very specific) scenario I think it actually makes sense. However, I do think that lock message isn't ideal, and the UX of this scenario can be improved a great deal with new messaging.

I suggest changing
Yellow: **Dataset Locked** This dataset has been submitted for review.

to

Yellow: **Submitted for Review** This dataset is currently under review prior to publication.

This way, the message is not about the lock on the dataset, but instead makes it clear the true status of the dataset. I don't think it's necessary to explicitly say that the dataset is locked; saying that it's "under review" is enough of an explanation for why the Contributor (AKA submitter) can't edit it. And removing the text about the lock makes it less confusing for those users who _do_ have edit permission.

**Comment by djbrooke** [comment]
If we have suggestions, let's implement!

**Comment by dlmurphy** [comment]
Hold my beer.

**Comment by pdurbin** [comment]
I don't think we need two issues. I'm closing this one because I just implemented the change above and left a comment and screenshot at https://github.com/IQSS/dataverse/issues/4139#issuecomment-337217930
