### ISSUE TITLE
Responsiveness: 'Create Dataverse' page is not responsive and breaks on smaller screen sizes

### ISSUE THREAD

**Issue by kaitlinnewson** [IQSS/dataverse#4212]
Hi Harvard team!

We received a report from one of our users about display issues on the 'Create a new dataverse' page. I've tested this in both the Scholars Portal instance and the Harvard instance, have tested in Chrome (v 61.0.3163.100) and Firefox (v 56.0), and am using OSX 10.11.6.

The issue seems to happen at a screen width of 990px or less, and causes text overlap and the inability to see text entered into the identifier field. I've attached a couple of screenshots for reference.

![screen shot 2017-10-17 at 2 44 24 pm](https://user-images.githubusercontent.com/6903515/31683055-cd414a02-b349-11e7-932b-7b43fe44c9f5.png)

![screen shot 2017-10-17 at 2 44 39 pm](https://user-images.githubusercontent.com/6903515/31683059-d032768c-b349-11e7-9e51-5588fe62d33a.png)

Let me know if you need any more information!

**Comment by pdurbin** [comment]
@kaitlinnewson thanks for bringing this issue to our attention.

At http://guides.dataverse.org/en/4.8/installation/prep.html#software-requirements the only guidance right now is "Clients are expected to be running a relatively modern browser." In days past, applications would recommend a certain resolution. What is a comfortable width for you for a browser window? You mentioned 990px so I'm guessing you hover around a thousand pixels wide. I guess I'm just trying to figure out what we should shoot for.

Our Style Guide talks about "auto, 750px, 970px or 1170px": http://guides.dataverse.org/en/4.8/style/foundations.html . I'm not sure what we usually test with. In development, if my browser isn't wide enough, I just make it wider. 😄

**Comment by mheppler** [comment]
Related to #2874.

**Comment by kaitlinnewson** [comment]
@pdurbin I use a 1920x1080 resolution, but of course other users may resize their windows in a variety of ways, e.g. if they want to have two windows side by side. Ideally you'd want the screen to look good at any size of course - maybe by making some of the items/labels stack.

**Comment by mheppler** [comment]
I am going to close this issue, as this UI bug is being looked into as part of the Create/Edit Dataverse form cleanup in issue _Add "Add Data" to navbar, plus Host Dataverse input to create dataverse/dataset forms #5615_.

@kaitlinnewson I will move your comment to that issue, where you can track it's progress going forward.
