### ISSUE TITLE
Dataverse Navigation: alias parameter displayed in url

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#4214]
https://dataverse.harvard.edu/dataverse.xhtml?alias=Storytime

when you click on the dataverse name, getting ".xhtml?alias="
instead of  just "https://dataverse.harvard.edu/dataverse/storytime"

**Comment by mheppler** [comment]
Have confirmed locally on the `develop` branch that clicking the following dataverse links are funky, sending you to the dataverse page but with a URL that is incorrectly showing the `alias` parameter.
- dataverse header
- breadcrumbs
- featured dataverse

The following dataverse links seem to work just fine.
- dataverse card
- dataverse card, parent link
- dataset card, parent link

**Comment by sekmiller** [comment]
Datavers Page urls fixed
[x] - Dataverse Header
[x] - Breadcrumbs
[x] - Featured Dataverse
[x] - redirects after failed login
[x] - redirect after cancelled Create Dataset
[x] - redirect after Delete Dataverse
[x] - redirect after Delete Dataset
[x] - My Data page

**Comment by sekmiller** [comment]
- [x] Dataverse Header

**Comment by mheppler** [comment]
Related to (a result of?) #4030.

**Comment by mheppler** [comment]
Fixed a few last query string parameters that @scolapasta [pointed out](https://github.com/IQSS/dataverse/pull/4226#pullrequestreview-72289349).

**Comment by kcondon** [comment]
OK, almost all are working, just following up on a minor MyData issue.
