### ISSUE TITLE
UI - Bootstrap 3.3.7 Upgrade

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#4219]
Upgrade our Bootstrap library from v3.3.2 to v4.0. Read more here: https://getbootstrap.com/docs/4.0/migration/

As of this posting, it is still in beta, but that [beta release](https://blog.getbootstrap.com/2017/08/10/bootstrap-4-beta/) was two years in the making, with "6 major alpha releases", and has been out for two months now.

They do warn that they've dropped older browser support. "Need support for IE8/IE9, Safari 8-, iOS 8-, etc? Keep using Bootstrap 3." So we should take that into consideration before upgrading.

**Comment by mheppler** [comment]
There was some discussion with @pameyer and @matthew-a-dunlap in Slack about the PrimeFaces upgrade, specifically the jQuery libraries included since those need to be updated because of security concerns. It was determined that as long as we upgrade to Bootstrap 4 and PrimeFaces 6.2, we'll be good.

>PrimeFaces 6.2 is out now, and if we upgrade to Bootstrap 4, we would need no lower than 6.2 due to the jQuery versions.

It appears that [PrimeFaces 6.2 uses jQuery 3.2.1](https://github.com/primefaces/primefaces/issues/3062) which is the version that [Bootstrap 4 recommends](https://getbootstrap.com/docs/4.0/getting-started/introduction/).

**Comment by mheppler** [comment]
This appears to be the migration guide to follow for 3.x to 4.x.

https://v4-alpha.getbootstrap.com/migration/

**Comment by mheppler** [comment]
It appears that I overlooked the fact that there was a 3.3.7 release, which would provide a lot of the improvements we were aiming for in upgrading (read: jQuery 3 support).

http://blog.getbootstrap.com/2016/07/25/bootstrap-3-3-7-released/

I have retitled this issue to upgrade to that release, as the 4.0 upgrade would require far more effort than we intended for this issue. If and when we redesign the UI as a whole, it would be worth considering an upgrade to Bootstrap 4.0. But for our proposes now with this current UI, 3.3.7 is sufficient and will get done much sooner.

**Comment by mheppler** [comment]
Initial commit for upgrading Bootstrap versions in the app and guides. Also cleaned up or upgraded a few other random issues.

DATAVERSE
- Removed local version of Bootstrap 3.3.2 and updated `dataverse_template.xhtml` to point to CDN copies of v. 3.3.7
- Removed local version of matchHeight 0.7.2 jQuery plugin and updated `dataverse_template.xhtml` to point to CDN copies of v. 0.7.2
- Removed local version of bootstrap-hover-dropdown.min.js that was not being used in the app because of `ui:remove` component in `dataverse_header.xhtml` added comment there in HTML to explain changes and link to newer version if needed

GUIDES
- Added local version of `jquery-3.1.0.min.js`to guides static resources and link to it in `layout.html` from the guides Sphinx Bootstrap theme
- Removed local version of `jquery-1.11.0.min.js` from guides static resources
- Upgraded version of Sphinx Bootstrap theme 0.4 to 0.6.1
- Fixed jQuery code formatting in `navbarscroll.js` to remove console warning after jQuery 3.1.0 upgrade
- Removed extra `<meta charset='utf-8'>` tag in `layout.html` from the guides Sphinx Bootstrap theme
- Removed `xnavbar_from_dataverse_org.js` from guides static resources, which was no longer being used

Still on the to-do list is updating this `4219-bootstrap-upgrade` branch with the latest and greatest version of PrimeFaces #4220, which is currently in QA. Still have a few other minor details to comb over.

One other random note, in the guides, there is a warning in the console about the Google Analytics code, which I do not see in the current 4.9.1 released version. I am assuming this is a dev environment issue only.
>Not allowed to load local resource: file://www.google-analytics.com/analytics.js

**Comment by pdurbin** [comment]
Pull request #4806 looks good. I'm excited about the use of CDNs for better performance.

**Comment by scolapasta** [comment]
Since CDNs are not required for the upgrade to bootstrap, we're going to remove that from this issue / PR. That'll give us time to gather some feedback from the community on their needs / desires / concerns regarding CDNs.
