### ISSUE TITLE
Geoconnect - Allow map preview before saving

### ISSUE THREAD

**Issue by dlmurphy** [IQSS/dataverse#4221]
Current Dataverse version: 4.8.1
Based on my own usage of Geoconnect and on comments from two BARI researchers during a demo,  saving a map in Geoconnect doesn't work as expected/desired.

Currently, pressing the "Apply Changes" button saves the map. The instant that button is pressed, the map is publicly visible on Dataverse and Worldmap.
![geoconnect](https://user-images.githubusercontent.com/22962740/31793010-f7be23ce-b4eb-11e7-84ab-42f4c85070e5.PNG)

This is problematic for three reasons:
**A.** Users expect that "Apply Changes" will show them the changes they've made, _without_ making them public. The button doesn't work as expected.

**B.** Creating a map is an exploratory process -- you don't know what the map is going to look like until you see it. Currently the only way to see the map you've created is to press "Apply Changes", releasing it to the public at the exact moment that you've first seen it. This means that you can't experiment or vet the map before you release it.

**C.** Users get an account notification and email every time they press "Apply Changes". Because the mapmaking process is exploratory, by the time users are satisfied with their map they will have racked up far too many notifications. When I was first testing out the feature (and unaware of this issue), I had 25 notifications and emails when I was done.

These problems can be solved with one simple solution: Change the "Apply Changes" button so it still causes the new map to display, but no longer saves/releases it. Add a "Save Map" button that saves/releases it instead.

A rough mockup:
![geoconnect2](https://user-images.githubusercontent.com/22962740/31793454-36989024-b4ed-11e7-80da-74141e1a95e4.PNG)

**Comment by dlmurphy** [comment]
@mheppler pointed out that the problem is even worse - the map is saved and published the instant you first get to Geoconnect. This means that the default, featureless and useless map is published and viewable by anyone the instant you start working on mapping your file. My recommendation remains the same.

**Comment by mheppler** [comment]
For the record, I didn't say "even worse". My sentiment was more that it isn't that bad.

I said (paraphrasing), "(once upon a time) there was a message posted to the user earlier in the workflow that says, 'your data is going to be posted to WorldMap', with a "Continue" button or something, so the user knows their (already published, public) data is going to be copied from one site to the other."

**Comment by dlmurphy** [comment]
Apologies for putting words in your mouth! I meant that the info you gave me made the problem seem worse from my point of view, but I definitely wasn't clear enough about that in my comment.

**Comment by pdurbin** [comment]
> the default, featureless and useless map is published and viewable by anyone the instant you start working on mapping your file

Woof. 😞

**Comment by djbrooke** [comment]
Closing this, as the migration of worldmap.harvard.edu to new infrastructure is resulting in Geoconnect and Worldmap being able to no longer communicate. We can investigate new Geospatial explore/analysis solutions in the future and will reopen specific issues as needed.
