### ISSUE TITLE
Indexing: Create API endpoint(s) that allows an admin to detect/delete stale solr record

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#4225]
Although probably rare, see #4205, there may be orphaned solr records that need to be removed outside of Dataverse, directly from the Solr API. It would be more convenient if an admin could use the familiar Dataverse API to pass the identifier of a stale dataset record to be removed.

**Comment by djbrooke** [comment]
See #4205 for some very detailed discussion.
