### ISSUE TITLE
"our Demo Site" doesn't make sense for non-Harvard installation

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#4227]
This "our Demo Site" message linking to https://demo.dataverse.org makes sense for users of https://dataverse.harvard.edu but not for users of other installations of Dataverse because Harvard runs that demo site. Here's the welcome message from UNC Dataverse:

![screen shot 2017-10-23 at 4 04 42 pm](https://user-images.githubusercontent.com/21006/31910585-f2a23074-b80b-11e7-8aba-5c7ad56b7267.png)

The screenshot above is from 4.7.1 but the same message is in 4.8.1:

`notification.welcome=Welcome to {0}! Get started by adding or finding data. Have questions? Check out the {1}. Want to test out Dataverse features? Use our {2}. Also, check for your welcome email to verify your address.` https://github.com/IQSS/dataverse/blob/v4.8.1/src/main/java/Bundle.properties#L150

**Comment by dlmurphy** [comment]
Would it be sufficient to change the phrase "Use our Demo Site" to "Use the Dataverse Demo Site", or do we need to make this message customizable to installations can link to their own demo sites?

**Comment by pdurbin** [comment]
In this context of creating an account on a production installation of Dataverse, I don't think we need to tell users to try a demo site to test features. They should just use the features of the installation they just created an account on.

**Comment by pdurbin** [comment]
@jggautier and I decided to call this "flagship bias" (after attending a [fantastic talk](https://www.eventbrite.com/e/technically-wrong-sexist-apps-biased-algorithms-other-threats-of-toxic-tech-tickets-38787140381) about bias yesterday) and I create a [Flagship Bias](https://docs.google.com/document/d/1-LtDv_Yaf_3EPuMWcg5ZxH7M2ACrmCzPzgmbwbt8gMQ/edit?usp=sharing) doc with other examples.

**Comment by TaniaSchlatter** [comment]
The text "Get started by adding or finding data" isn't very useful without providing links. This text should be configurable, and include only default text that doesn't include flagship bias. Something like, "Welcome to [Dataverse Name]. Look for an email message with instructions on how to verify your address."

**Comment by pdurbin** [comment]
I agree with @TaniaSchlatter that the text should be configurable. If memory serves, this is something @shlake was interested in.

**Comment by shlake** [comment]
I am interested in configurable text in other email notifications that go out when dataverse/dataset are created.

It's been awhile (several versions back 4.2??) when I 1st created my account, so if this welcome message is new since then, then I would not have seen it.

I am amazed that @pdurbin remembers these things, ;-)

**Comment by pdurbin** [comment]
I've lost steam on caring about this issue. If someone wants to create a fresh issue with their ideas of how the welcome message should look, please go ahead. Closing! 😄
