### ISSUE TITLE
Non-breaking space in title is displayed as &nbsp; in citation

### ISSUE THREAD

**Issue by bjonnh** [IQSS/dataverse#4228]
https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/E5TGKA

I mistakenly typed a non-breaking space in the title of that dataset, and it shows with an &nbsp; in the Dataset citation.

Is that intended behavior?

**Comment by pdurbin** [comment]
@bjonnh nope! Thanks for the bug report. This was observed on 4.8.1.

**Comment by jggautier** [comment]
Just noting that I think this is related to this issue, Ampersand, greater than and less than symbols in dataset titles are replaced with their escaped versions in different parts of UI #4077.

**Comment by pdurbin** [comment]
Yes! Thanks @jggautier I was having trouble finding it.

**Comment by mheppler** [comment]
Also related? #4235 

Do we need to review how whitespaces or nonbreaking spaces are handled in our metadata fields?

**Comment by pdurbin** [comment]
I believe https://github.com/IQSS/dataverse/issues/3328#issuecomment-341717698 is related but I don't know which metadata field has the `&nbsp;` in it.

**Comment by djbrooke** [comment]
Closed in favor of #4077.
