### ISSUE TITLE
Infrastructure to support Privacy Preserving Metadata

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#4231]
In particular the ability to store multiple (two) sets of summary statistics and to be able to define them a "private" or "public" (or possibly a datatag color)

**Comment by djbrooke** [comment]
Had some discussion in the sprint planning meeting 10/25:

- Is this the time to approach a metadata block for files? Would need to discuss this approach.
- We need to discuss what exactly PSI will produce and expect to send back to Dataverse.

**Comment by raprasad** [comment]
**Note**: In thinking about design, consider next phase of the project where individual users may have their own, unshared summary stats.  In that scenario, there are 2+ sets of summary statistics:

1. Original/private summary stats
1. Noisy stats with green tag (according to google doc)
1. Additional noisy stats for users that have been granted a privacy budget
    - These are less noisy than (2)
    - Not supposed to be shared between users

**Comment by pdurbin** [comment]
Anyone working on this issue will want to read the "PSI Integration Tech Design" doc at https://docs.google.com/document/d/1XoS7kMwvZ-Ml1uIoWDClB3nj4lg06dMz9Ou6X9krVHo/edit?usp=sharing

Please note that #4232 is highly related.

**Comment by landreev** [comment]
Please note that the PR referenced above is a combined branch with the code for this and also #4232 and #4307 issues.

**Comment by kcondon** [comment]
Works as part of uploading prep file/ works as described.

**Comment by djbrooke** [comment]
Closing this issue for now. We'll pick this back up when we have DataTags support. 

The branch and issues will remain:

https://github.com/IQSS/dataverse/tree/4231-psi-metadata-infrastracture
https://github.com/IQSS/dataverse/issues/4231
https://github.com/IQSS/dataverse/issues/4232
https://github.com/IQSS/dataverse/issues/4307
