### ISSUE TITLE
As a Researcher, I want to view differentially private metadata so that I can learn enough to determine whether or not it’s worth my time to go through the IRB process for the raw data.

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#4234]
Logged in users can use Two Ravens to explore differentially private versions of the metadata for sensitive files.

**Comment by mheppler** [comment]
**NOTE:** Backend prerequisite, issue #4230 and frontend prerequisite, issue #4233

Here is an outline the proposed UI changes.

**UI IMPACT**

*Dataset pg*
- Explore File popup, displays terms of use, access, et al, plus any canned terms we might get from PSI
- Privacy-Preserving Data Preview popup, after data owner with access to sensitive data clicks Explore button for file with privacy preview, provide warning msg that they need to determine if they want to explore the privacy preview or the original sensitive data
- Privacy-Preserving Data Preview popup, info msg explaining PSI tool, links to TwoRavens with Continue button

*File pg*
- Explore File popup, displays terms of use, access, et al, plus any canned terms we might get from PSI
- Privacy-Preserving Data Preview popup, after data owner with access to sensitive data clicks Explore button for file with privacy preview, provide warning msg that they need to determine if they want to explore the privacy preview or the original sensitive data
- Privacy-Preserving Data Preview popup, info msg explaining PSI tool, links to TwoRavens with Continue button

![psi-explore-terms](https://user-images.githubusercontent.com/687227/32343970-9f48fd9a-bfdb-11e7-8240-4cf42b145855.png)

![psi-privacy-select](https://user-images.githubusercontent.com/687227/32343971-9f52e404-bfdb-11e7-87bb-cd670f4ec58b.png)

![psi-explore-info](https://user-images.githubusercontent.com/687227/32343982-a5cc0f54-bfdb-11e7-9db0-7c39f5370944.png)

**Comment by dlmurphy** [comment]
For reference when we get to this issue:

In #4233, I [recommended the following text change](https://github.com/IQSS/dataverse/issues/4233#issuecomment-345373466) for the "Privacy-Preserving Data Preview" modal seen in the last screenshot of Mike's previous comment:

> **Privacy-Preserving Data Preview**
> Use the PSI Budgeter tool to create safe, privacy-preserving summary statistics for this data file. The tool protects data using the [differential privacy](https://privacytools.seas.harvard.edu/publications/differential-privacy-primer-non-technical-audience-preliminary-version) framework. It allows you to introduce just enough noise into your summary statistics to ensure privacy while still allowing a useful (if blurry) window into the contents of your data. Dataverse users will be able to explore a preview of your data without any danger of exposing private information.

At the time we weren't able to implement this change because by that point we'd removed the psi.json file from the Dataverse source code. When the time comes, I'd like this text change implemented.

**Comment by TaniaSchlatter** [comment]
Thanks for these edits on the text, @dlmurphy. The language needs to be free of any implied promises. Can you take another round taking out words that imply any sort of guarantee?

**Comment by pdurbin** [comment]
@dlmurphy also, are hyperlinks supported? @matthew-a-dunlap wouldn't know better than I would.

**Comment by dlmurphy** [comment]
Good call, @TaniaSchlatter. I've edited the message to be less of a guarantee of success. 

@pdurbin, I'm not sure whether we can include a hyperlink in this modal. If so, I think it's nice to have, but if not then I'd be comfortable taking the link out (it's not essential).

> **Privacy-Preserving Data Preview**
> Use the PSI Budgeter tool to create privacy-preserving summary statistics for this data file. The tool helps you protect data using the [differential privacy](https://privacytools.seas.harvard.edu/publications/differential-privacy-primer-non-technical-audience-preliminary-version) framework. It can be used to introduce noise into your summary statistics to help ensure privacy while still allowing a useful (if blurry) window into the contents of your data. Dataverse users will be able to explore a preview of your data that is calibrated to minimize the risk of exposing private information.

**Comment by matthew-a-dunlap** [comment]
@dlmurphy @pdurbin I'm pretty sure the hyperlink will work as long as we provide the correct mark-up. I'll take a try at it myself in my local env at some point soon.

**Comment by matthew-a-dunlap** [comment]
@dlmurphy Confirmed 
![screen shot 2017-11-28 at 5 33 35 pm](https://user-images.githubusercontent.com/8901015/33347869-55144928-d462-11e7-86fc-335c37e3f409.png)
Here is the description section of the psi.json (github won't let me upload .json)
`"description": "Use the PSI Budgeter tool to create privacy-preserving summary statistics for this data file. The tool helps you protect data using the <a href=\"https://privacytools.seas.harvard.edu/publications/differential-privacy-primer-non-technical-audience-preliminary-version\">differential privacy</a> framework. It can be used to introduce noise into your summary statistics to help ensure privacy while still allowing a useful (if blurry) window into the contents of your data. Dataverse users will be able to explore a preview of your data that is calibrated to minimize the risk of exposing private information.",
`

**Comment by dlmurphy** [comment]
@matthew-a-dunlap Looking great, thanks!

**Comment by dlmurphy** [comment]
Just discussed with @mheppler and we realized there are a few pretty compelling reasons not to include that "differential privacy" link to the _Differential Privacy Primer_ paper in this message modal. Best option for us here is to take out that link, and instead link to our PSI page in the user guide (which will include a link to that paper).

So the message should actually be:

> **Privacy-Preserving Data Preview**
> Use the PSI Budgeter tool to create privacy-preserving summary statistics for this data file. The tool helps you protect data using the differential privacy framework. It can be used to introduce noise into your summary statistics to help ensure privacy while still allowing a useful (if blurry) window into the contents of your data. Dataverse users will be able to explore a preview of your data that is calibrated to minimize the risk of exposing private information. For more information, see our [Privacy Management user guide](http://guides.dataverse.org/en/latest/user/privacy-management.html#PSI). 

This can definitely wait until this issue is prioritized, just leaving it here for the future.

**Comment by djbrooke** [comment]
Closing in favor of #7400
