### ISSUE TITLE
support@dataverse.harvard.edu

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#4238]
Over at https://help.hmdc.harvard.edu/Ticket/Display.html?id=248343 I've been working on setting up a new support email address for Harvard Dataverse that will help us distinguish between Dataverse the project and Harvard Dataverse the service.

I'm opening this issue to make a pull request to change `scripts/api/setup-optional-harvard.sh`. This script is used by developers to express which configuration options are recommended for Harvard Dataverse. Right now it has the old "support@dataverse.org" address:

`curl -X PUT -d "Harvard Dataverse Support <support@dataverse.org>" http://localhost:8080/api/admin/settings/:SystemEmail`

Moving forward, we'll be better able to distinguish between the project/product and Harvard's installation of the product. That is to say:

- support@dataverse.org will be used for Dataverse the project: https://dataverse.org
- support@dataverse.harvard.edu will be used for Harvard Dataverse: https://dataverse.harvard.edu

The definition of done for this issue is running the updated curl command in production.

Afterwards, and effort should be made to update dataverse.org pages that reference the old address. For example, the section on https://dataverse.org/institutions in the screenshot below should be updated to "support@dataverse.harvard.edu":

![screen shot 2017-10-26 at 11 54 29 am](https://user-images.githubusercontent.com/21006/32063186-8e411092-ba44-11e7-9366-914fcf33df4e.png)

**Comment by pdurbin** [comment]
I made pull request #4239 and am moving this issue to Code Review at https://waffle.io/IQSS/dataverse

**Comment by sekmiller** [comment]
Looks good. Moving to QA.

**Comment by kcondon** [comment]
Adding to my deployment plan for 4.8.2

**Comment by pdurbin** [comment]
I just resolved INC02042470 but I wanted to note that the change hasn't yet been deployed to Harvard Dataverse. The new support@dataverse.harvard.edu works fine but @djbrooke and I have been talking about how we don't plan to roll out the change until more work is done for the Harvard Dataverse "about" page and/or the home page ( https://trello.com/c/x10i7aaB/2-harvard-dataverse-hmpg-47 ).

I would like to note that https://dataverse.org/institutions has been updated to use the new address. Thanks, @jggautier !

**Comment by jggautier** [comment]
> Afterwards, an effort should be made to update dataverse.org pages that reference the old address.

More about changing to support@dataverse.harvard.edu is being tracked in [this github issue](https://github.com/IQSS/dataverse-curation/issues/208) in the dataverse-curation github.

**Comment by jggautier** [comment]
> I just resolved INC02042470 but I wanted to note that the change hasn't yet been deployed to Harvard Dataverse. The new support@dataverse.harvard.edu works fine but @djbrooke and I have been talking about how we don't plan to roll out the change until more work is done for the Harvard Dataverse "about" page and/or the home page ( https://trello.com/c/x10i7aaB/2-harvard-dataverse-hmpg-47 ).

@pdurbin, will the change that you wrote hasn't been deployed change the ":SystemEmail" in the "Settings" table in the database to support@dataverse.harvard.edu? 

In other words, is that change dependent on more progress on Harvard Dataverse's "about" and/or home page? Can we change the email in the General Terms of Use (the text stored as :ApplicationTermsOfUse also in the "Settings" table in the database)?

**Comment by pdurbin** [comment]
@jggautier there no technical reason to wait to reconfigure Harvard Dataverse to send support requests to support@dataverse.harvard.edu since that email address has worked fine for over a year. There's no reason to wait to use support@dataverse.harvard.edu wherever appropriate, such as in General Terms of Use.

All that said, I would love, love, love, to have us reconfigure the "About" link at the top of Harvard Dataverse. The easiest thing to do would be to delete the `:NavbarAboutUrl` setting so that the "About" link is gone from the navbar. (See also the "Flagship Bias" doc at https://docs.google.com/document/d/1-LtDv_Yaf_3EPuMWcg5ZxH7M2ACrmCzPzgmbwbt8gMQ/edit?usp=sharing .) Longer term, we should set up an "about" page and reconfigured `:NavbarAboutUrl` to point to it. There's a Google doc on this but I don't want to link to it here without your permission.

**Comment by pdurbin** [comment]
I just published a new version of my dataset on Harvard Dataverse and it's still configured for the old support@dataverse.org address rather than the new support@dataverse.harvard.edu address. Here's the email I got:

From: Harvard Dataverse Support <support@dataverse.org>
Date: Mon, Feb 25, 2019 at 10:03 PM
Subject: Harvard Dataverse: Your dataset has been published
To: <philip_durbin@harvard.edu>

Hello,
Open Source at Harvard (view at https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/TJCLKP) was published in Open Source at Harvard (view at https://dataverse.harvard.edu/dataverse/open-source-at-harvard).

You may contact us for support at support@dataverse.org.

Thank you,
Harvard Dataverse Support
