### ISSUE TITLE
Reword Error Message - Tabular Data Ingest Failed

### ISSUE THREAD

**Issue by CCMumma** [IQSS/dataverse#4250]
Regarding: Dataverse v 4.7.1 - TDR

Texas A&M University has brought a small issue with an error message to our attention. 

A researcher uploaded a CSV file with data. The CSV file wasn't formatted as valid tabular data, so Dataverse couldn't interpret it in the way it tries to interpret tabular data saved as a CSV.

The warning message from TDR Dataverse (screenshot attached) says "Tabular Data Ingest Failed" for the following dataset: https://dataverse.tdl.org/dataset.xhtml?persistentId=doi:10.18738/T8/AF3COF

The warning seems visible to the submitter and the admin, not the users who aren't logged in. TDL staff has confirmed that the file has actually been uploaded and is available to download.

Can this message may be reworded to be more transparent? It seems almost to imply to a submitter that the file upload has failed.

![20171019-tabular_data_failed-screenshot](https://user-images.githubusercontent.com/12702471/32241620-a9240cfe-be3e-11e7-8db2-47e3ca13d2da.png)

Thank you,
Courtney Mumma, TDL, Texas Data Repository

**Comment by pdurbin** [comment]
@CCMumma hi! One of the big improvements in Dataverse 4.8 was improved CSV parsing (pull request #3963 for issues #3767 and #2626). Do you think you could re-test on 4.8 and let us know if the messaging is any better?

**Comment by CCMumma** [comment]
Will do - though we won't upgrade until December, so I'll follow up then. 
C

**Comment by oscardssmith** [comment]
This data will not ingest on new Dataverse versions. That said, I believe the messaging has changed.

**Comment by pdurbin** [comment]
Courtney, can you please try your file on https://demo.dataverse.org and post a screenshot of the new messaging we added in 4.8 and let us know what you think?

**Comment by pdurbin** [comment]
@CCMumma thanks! I added a label for UX attention. What do you think it should say instead?

**Comment by CCMumma** [comment]
Maybe just include the text "Upload Complete. Tabular Data Ingest Failed." in the header. The 'reason' text doesn't really need to change. I'm open to other suggestions, though.

**Comment by pdurbin** [comment]
> Maybe just include the text "Upload Complete. Tabular Data Ingest Failed." in the header.

I implemented this change in pull request #4276 and moved this issue to code review at https://waffle.io/IQSS/dataverse

**Comment by dlmurphy** [comment]
I think this text is an improvement, but I think the real root cause of this confusion is that users who encounter this error don't know what "tabular ingest failed" means, and don't know what the implications of that failure are. I think that a more thorough approach would be to include a link to the user guide page on tabular ingest, but given that the error message is dynamic, that's a much more complex prospect that might represent scope creep here. Thoughts?

**Comment by djbrooke** [comment]
ping @CCMumma

**Comment by dlmurphy** [comment]
Alternatively even better, we could add a bit at the start of every ingest failure message that goes something like: 

**Tabular Data Ingest Failed**
File can be downloaded, but cannot be explored.

**Comment by TaniaSchlatter** [comment]
I reviewed the original issue, and the simple solution is what we want.

**Comment by djbrooke** [comment]
Thanks @TaniaSchlatter - I unassigned folks from this.

**Comment by dlmurphy** [comment]
Spoke with Mike and Tania, sounds like we want:

**Upload Completed with Errors** 
Tabular Data Ingest failed. _(regular dynamic messaging about why it failed goes here)_

@mheppler says he's on board to implement this.

**Comment by mheppler** [comment]
New and improved ingest error popover message text.

![screen shot 2017-11-15 at 12 47 40 pm 2](https://user-images.githubusercontent.com/687227/32851810-0bb1831c-ca04-11e7-9efa-76d7c69f47da.png)

**Comment by jggautier** [comment]
Leaving feedback from someone who saw the re-worded error message when uploading data on Harvard Dataverse (from this RT ticket (https://help.hmdc.harvard.edu/Ticket/Display.html?id=258372)):

> I am trying to upload two datasets for replication, but I keep getting the error "Upload completed with errors. Tabular data ingest failed. DataReader.readBytes called to read zero or negative number of bytes." The two datasets are in Stata v13 format, and I get this error for both of them. 
> 
> After uploading, I downloaded all of my files and I seem to be able to replicate the results without any issues. Is there any reason I should be concerned about this error message?

@sbarbosadataverse let the depositor know that the file is still available for download:
> Some file versions are not compatible with the online analysis tool, but your normal download in original format should work just fine.

We haven't heard anything else, yet (and haven't had the chance to test the change after it was implemented). @CCMumma let us know during today's Community Call ([see meeting notes](https://docs.google.com/document/d/1nLNYMHB4xqUge3shMLEWfni0v5VOXb9brtLWcSujvDM/edit)) that she hasn't heard negative feedback, either.
