### ISSUE TITLE
Request access for restricted files not working from the file page

### ISSUE THREAD

**Issue by TaniaSchlatter** [IQSS/dataverse#4251]
When requesting access to a restricted file from the file page, the request does not appear to go through. 

File requested: https://dataverse.harvard.edu/file.xhtml?fileId=2902723&datasetVersionId=88609

<img width="1216" alt="screen shot 2017-10-31 at 4 34 04 pm" src="https://user-images.githubusercontent.com/15386424/32247649-61aa1222-be59-11e7-8106-7634e3433ba4.png">

**Comment by scolapasta** [comment]
This is not just a "no indication on the UI" happens, but more simply, the access request never goes through to the system.

**Comment by sekmiller** [comment]
The FileDownloadHelper was not exposed to the request access popup via the FilePage so the method never fired.

**Comment by pdurbin** [comment]
The fix makes sense. When I got to https://github.com/IQSS/dataverse/blob/v4.8.2/src/main/webapp/file.xhtml#L535 in NetBeans and try to  navigate to `#{FilePage.fileDownloadHelper}` it doesn't go anywhere. I thought that NetBeans highlighted cases like this of non-existent methods in yellow as warnings but I guess not in this case. Moving to QA.
