### ISSUE TITLE
Update dataset citation image in best practices documentation

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#4253]
An image on [the data citation page](http://best-practices.dataverse.org/data-citation/index.html) of the best practices documentation needs to be updated so that the parts of the dataset citation are in the right order. The order in the image is:

Author(s), Year, Dataset Title, **Data Repository or Archive, Version, Global Persistent Identifier**

<kbd>![32087405-8acbdcca-baa9-11e7-956d-8ce380d32574](https://user-images.githubusercontent.com/18374574/32303232-bbc4185e-bf3d-11e7-84dc-592d4d9ed291.png)</kbd>

We should replace it with this image, which has the current order:

Author(s), Year, Dataset Title, **Global Persistent Identifier, Data Repository or Archive, Version**

<kbd>![generic-citation-2](https://user-images.githubusercontent.com/18374574/32303291-fdd3dd6a-bf3d-11e7-8ca9-67a83972c6db.png)</kbd>

**Comment by pdurbin** [comment]
The image is in a different repo: https://github.com/IQSS/dataverse.org/blob/master/dataverse_org/static/images/generic-citation.png

**Comment by jggautier** [comment]
Thanks!

Moved this to https://github.com/IQSS/dataverse.org/issues/61. Closing this issue.
