### ISSUE TITLE
Move describe method from EjbDataverseEngine to Command interface

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#4262]
Our current design has an actionlog that tracks (among other things) every command called. One of the fields in details which is populated from the describe method in the EjbDataverseEngine. While this is useful, this describe method is composed generically for all commands.

Going forward, we would like to move the describe method to the Command interface so that we can maintain the generic approach for most commands, but also override in any specific Command.

A specific example is AssignRoleCommand. When you assign a role the describe command (generically) puts in the affected object id and name, however when assigning a rpole to a file, it puts in the dataset name, since the permission check for assigning a role for a file is checked at the dataset (i.e. it is the "affected object). Allowing override of the description would allow this command to specify the file, instead of the dataset.

For this issue, we'd like to provide the infrastructure to support this (the moving of describe) and the specific example of overriding in one class (so let's go with AssignRole as this will be immediately useful).

**Comment by pdurbin** [comment]
In 023cb8f and 7cfc8ba I addressed the issues @scolapasta raised in code review.

**Comment by pdurbin** [comment]
To do list based on latest feedback from @scolapasta 

- [ ] add the role to the message

**Comment by pdurbin** [comment]
@michbarsinai I saw your note about https://github.com/IQSS/dataverse/pull/4275#discussion_r150984056 but I don't think we should hold up this issue for refactoring. I think we should go ahead and move forward if we're otherwise happy with the pull request.

**Comment by pdurbin** [comment]
Oh, now that I have the code in front of me I see that I was mis-remembering. I thought I'd have to rename a getter that would have a large ripple effect in the code. It was a simple change: 633a19d
