### ISSUE TITLE
Upgrade 4.6.2 => 4.8.2: Internal Server Error. Missing column dataset.usegenericthumbnail

### ISSUE THREAD

**Issue by lmaylein** [IQSS/dataverse#4266]
> Local Exception Stack: 
> Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.5.2.v20140319-9ad6abd): org.eclipse.persistence.exceptions.DatabaseException
> Internal Exception: org.postgresql.util.PSQLException: ERROR: column t2.usegenericthumbnail does not exist
>   Position: 56
> Error Code: 0
> Call: SELECT t0.VERSIONSTATE, t1.ALIAS, t2.THUMBNAILFILE_ID, t2.USEGENERICTHUMBNAIL, t3.STORAGEIDENTIFIER FROM DATASETVERSION t0, DATAVERSE t1, DATASET t2, DVOBJECT t3 WHERE t0.ID = 268 AND t1.ID = 1470 AND t2.ID = 1471 AND t2.ID = t3.ID
> Query: DataReadQuery(sql="SELECT t0.VERSIONSTATE, t1.ALIAS, t2.THUMBNAILFILE_ID, t2.USEGENERICTHUMBNAIL, t3.STORAGEIDENTIFIER FROM DATASETVERSION t0, DATAVERSE t1, DATASET t2, DVOBJECT t3 WHERE t0.ID = 268 AND t1.ID = 1470 AND t2.ID = 1471 AND t2.ID = t3.ID")

There is no upgrade-xxx.sql between version 4.6.2 and 4.8.2 to add this column.

**Comment by lmaylein** [comment]
Ok.
upgrade_v4.6.1_to_v4.6.2.sql does the job.
Obviously  I should have used this script when upgrading directly from 3.x to 4.6.2.

**Comment by pdurbin** [comment]
@lmaylein I'm glad you figured it out and congrats on the upgrade. I believe yours in the first installation to have upgraded to 4.8.2.
