### ISSUE TITLE
Ambiguities with the Dataverse Installation Guide

### ISSUE THREAD

**Issue by gupta-yash** [IQSS/dataverse#4270]
Hey there, Dataverse community!
So, I'm working on developing Azure Blob storage driver for Dataverse ( #4247  ), and during our journey we got stuck in some trouble with the development environment due to the ambiguity caused by the Dataverse Installation Guide. I was suggested to create a new issue for this, so here it goes:

Actually I'm doing my development work over Netbeans IDE on a Linux machine. I was adding & configuring GlassFish server into my Netbeans environment for debugging our code. But over there I got stuck with something.
When I went to configure GlassFish in there, they ask to select a 'domain' to deploy your .war file. Now the default domain that the base GlassFish installation proceeds with is termed as `domain1`, and this is where my Dataverse installation is still running (the initial one which I installed for test purposes before the dev work).
But when I selected this domain during the setup process in Netbeans, it denied to accept it prompting that this isn't a valid domain to work with! Don't know why.
Anyways, I just moved on & created a new domain thinking that it wouldn't be an 'issue', but as I proceeded for the 'Build and Run' process for my updated dataverse application, it didn't went on as expected. I got about 50-60 exceptions which were related to some Dataverse JDBC classes and the procedure failed midway. So, I just undeployed that instance from my 'new' domain and went back to Fresh Reinstallation to set it up 'again' on my previous domain1 domain (again because, obviously, the same application can't run simultaneously on 2 domains of GlassFish & thus was undeployed from domain1).
I followed the Fresh Reinstall from the following link: 
http://guides.dataverse.org/en/latest/installation/installation-main.html

And guess what, the later attempt of deploying Dataverse messed up with the component-level installation of my Dataverse environment & now I can't even make it work back to where I was.

About those exceptions related to JDBC classes, I'm sorry but I didn't saved the stacktrace as I didn't thought that it could cause any major problem in the first place. Talking about the messing-up that happened with my environment, I mentioned 'component-level' because when I ran the installer, I got something that I never got before:

```
Executing curl -X PUT -d yash.gupta@appliedis.com http://localhost:8080/api/admin/settings/:SystemEmail
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><title>GlassFish Server Open Source Edition  4.1  - Error report</title><style type="text/css"><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 403 - Forbidden</h1><hr/><p><b>type</b> Status report</p><p><b>message</b>Forbidden</p><p><b>description</b>Access to the specified resource has been forbidden.</p><hr/><h3>GlassFish Server Open Source Edition  4.1 </h3></body></html>OK.

Executing curl -X PUT -d false http://localhost:8080/api/admin/settings/:TwoRavensTabularView
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><title>GlassFish Server Open Source Edition  4.1  - Error report</title><style type="text/css"><!--H1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} H2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} H3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} BODY {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} B {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} P {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;}A {color : black;}HR {color : #525D76;}--></style> </head><body><h1>HTTP Status 403 - Forbidden</h1><hr/><p><b>type</b> Status report</p><p><b>message</b>Forbidden</p><p><b>description</b>Access to the specified resource has been forbidden.</p><hr/><h3>GlassFish Server Open Source Edition  4.1 </h3></body></html>OK.
```
So this thing came up at the final stage of installation process and finished the installation. It displayed that: "You should now have a running Dataverse instance at localhost:8080"
But at localhost:8080, all I found is the homepage of GlassFish server running, and no UI for Dataverse.

Help, please?
Thanks in advance!

**Comment by matthew-a-dunlap** [comment]
First question: Were you able to make it through the installer process and get glassfish running? Even if it then broke as you tried to do development?

Also, have you been using the installer as discussed in this section of the guide? Just want to understand where you are and which setup you are using. http://guides.dataverse.org/en/latest/installation/installation-main.html#id1

Part of the installer process makes some modifications to the glassfish domain, so switching domains without rerunning the installer will not work and will cause many errors. But, once you've done a successful install you should be able to just click build and run on netbeans.

I've run into other issues with getting netbeans to cooperate with Glassfish 4.1, in my case the solution was to downgrade to netbeans 8.1, so if you are running into weird netbeans issues maybe try that? You can always build the war via netbeans and move it over to glassfish via command line, not the best but may help isolate your issue. In general glassfish issues can be a bit of a black hole so confirm that you are using all the correct versions of the tools and libraries. Thanks!

**Comment by pdurbin** [comment]
> Anyways, I just moved on & created a new domain thinking that it wouldn't be an 'issue'

@gupta-yash I think this is the problem. If you can't deploy the war file to "domain1" I would recommend stopping Glassfish, uninstalling it (`rm -rf` or simply `mv` aside) and reinstalling it (unzipping the Glassfish zip file). Then you will need to re-run the Dataverse installer to have it configure this fresh installation of Glassfish.
