### ISSUE TITLE
As a Dataverse admin, I want Dataverse to record how often people download versus explore data to learn more about how people use different tools to engage with data

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#4272]
Since the file page was added (around Dec. 13 2016), Dataverse stopped updating the database (the guestbookresponse table's downloadtype column) with "Explore" when people click "Explore" on ingested tabular files and mapped shape files. It's calling Explore "Download". This was an unintentional change.

Dataverse should update the guestbookresponse table with "Explore" when people click on Explore. The extra detail is helpful for collecting metrics about how often people use different tools to engage with data.

@sekmiller said today he's already fixed this.

**Comment by djbrooke** [comment]
@jggautier - when you say @sekmiller has already fixed this, do you mean that it's fixed or that he fixed it once it broke again? :)

**Comment by sekmiller** [comment]
There was some work done recently to split the contents of the guestbook responses to get a better handle on the types of usages. I wasn't involved in the coding or testing but it looks like the information is contained in the DownloadType and FileFormat fields of the FileDownload table which has a one-to-one relationship with the guestbookResponse table. I just dropped my database a couple of days ago so i don't have anything in those tables locally to look at.

**Comment by pdurbin** [comment]
@djbrooke @sekmiller here are some counts from the dev2 server:

```
dvndb=# select count(downloadtype),downloadtype from filedownload group by downloadtype order by count desc;
 count |      downloadtype       
-------+-------------------------
    93 | Download
    31 | girder.local Whole Tale
    11 | Stage Whole Tale
     8 | MyBinder
     3 | Whole Tale
     2 | Production Whole Tale
     1 | Custom Keys
(7 rows)
```

**Comment by jggautier** [comment]
> @jggautier - when you say @sekmiller has already fixed this, do you mean that it's fixed or that he fixed it once it broke again? :)

I meant that it was fixed (so that Dataverse would begin differentiating in the guestbook when someone clicked download versus explore) and I didn't mean to suggest that there was a fix but it was broken again. From what I can tell - I've seen different "downloadtypes" in Harvard Dataverse guestbooks as recently as today - it's still working as intended. :)

I can't remember why I didn't close this issue, or why I didn't ask if it could be closed. But do you think we should verify that there's no way to recover the lost information when Dataverse was not differentiating between "Download" and "Explore"?

**Comment by sekmiller** [comment]
There isn't a way to backfill those "Downloads" that should have been designated as "Explore" or something else.

**Comment by pdurbin** [comment]
In `scripts/database/upgrades/upgrade_v4.8.6_to_v4.9.sql` we changed all the "Explore" in the database to "TwoRavens" like this:

```
-- Previously, the only explore tool was TwoRavens. We now persist the name of the tool.
UPDATE guestbookresponse SET downloadtype = 'TwoRavens' WHERE downloadtype = 'Explore';
```

**Comment by pdurbin** [comment]
The change above from "Explore" to the name of the tool is discussed in #3657 and the specific commit above is c236079

@TaniaSchlatter @mheppler we could surfaces these as metrics, of course...

- 7 Downloads
- 3 Launches of Data Explorer
- 1 Launch of TwoRavens
- 1 Launch of WholeTale
