### ISSUE TITLE
installer zip file does not contain postgres drivers referenced in the installer

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#4278]
`dvinstall.zip` has `postgresql-8.4-703.jdbc4.jar  postgresql-9.0-802.jdbc4.jar  postgresql-9.1-902.jdbc4.jar` ; uses several more versions.

**Comment by pdurbin** [comment]
Looks good. Here's a listing of the before and after:

```
murphy:~ pdurbin$ ls -1 /tmp/before/dvinstall/pgdriver
postgresql-8.4-703.jdbc4.jar
postgresql-9.0-802.jdbc4.jar
postgresql-9.1-902.jdbc4.jar
murphy:~ pdurbin$ ls -1 /tmp/after/dvinstall/pgdriver
postgresql-42.1.4.jar
postgresql-8.4-703.jdbc4.jar
postgresql-9.0-802.jdbc4.jar
postgresql-9.1-902.jdbc4.jar
postgresql-9.2-1004.jdbc4.jar
postgresql-9.3-1104.jdbc4.jar
postgresql-9.4.1212.jar
murphy:~ pdurbin$ 
```

I was confused by `postgresql-42.1.4.jar` but it's for PostgreSQL 9.5 and 9.6 according to https://github.com/IQSS/dataverse/blob/v4.8.2/scripts/installer/install#L164

Moving to QA.
