### ISSUE TITLE
Logging guidelines in the coding style document should be updated

### ISSUE THREAD

**Issue by michbarsinai** [IQSS/dataverse#4284]
Current type of logging is wasteful: the JVM concatenates the string, passes it to the logger, only to have the logger ignore it. Passing the message format and the argument array is much more efficient (It's an auto-fix in NetBeans, BTW).

current: `logger.fine("object " + o + " does not match " + m + ".");`
efficient: `logger.log(Level.FINE, "object  {0} does not match {m}", new Object[]{o,m});`

**Comment by pdurbin** [comment]
Thanks for opening this issue, @michbarsinai

Isn't readability worth something? My eyes are bleeding a bit over `new Object[]{o,m})` and without tooling, would we even go on a quest to make these uglifications?

Has anyone measured performance to see if this will make much of a difference? This seems like classic premature optimization.

Dataverse is a slow app. I really doubt that changing the thousands of cases of these lines will make any difference. If we care about performance, let's measure and have some tooling tell us where Dataverse is slow. (Usually, it's database queries.) I'm fine with what's written at http://guides.dataverse.org/en/4.8.2/developers/coding-style.html#logging about using `logger.fine`. I probably wrote it. 😄 It looks nice and I haven't seen any data to indicate that it's especially slow.

What do others think? Do you like the ugly? Is it worth it? For more context, please see https://github.com/IQSS/dataverse/pull/4280#discussion_r150973811

**Comment by michbarsinai** [comment]
Some points:
1. I disagree that's this is a premature optimization: we're not making some wrong assumptions that allow us to overly simplify an algorithm. There are no consequences except readability,  performance, and memory consumption. We construct strings at runtime, mostly for developer readability. They are hardly ever used in production.
2. Constructing a string is not cheap. It makes the JVM allocate a contiguous memory block the size of the string. So it's not just the construction (O(n)), it's the GC overhead (+fragmentations etc).
3. The constructed strings are arbitrarily long here (e.g. for objects that have large toString results, such as sets), this can, at times, become a real memory issue. proliferation of such logging messages, in conjunction with other memory-intensive actions, may cause sporadic out-of-memory errors, which will be hard to replicate.

So the suggested change is less readable, true, but is safer and more performant. The current logging style is problematic enough to warrant its own NetBeans validation and auto-fix, so clearly I'm not the only one thinking we should change the way we log.
<img width="491" alt="screen shot 2017-11-15 at 21 06 19" src="https://user-images.githubusercontent.com/1938468/32855027-35ebe4c0-ca49-11e7-98bb-f01d12970b15.png">
<img width="504" alt="auto-fix" src="https://user-images.githubusercontent.com/1938468/32855030-36eadd7c-ca49-11e7-9255-9628ebbcc225.png">

**Comment by michbarsinai** [comment]
(P.S.: we can also decide to not decide :-)

**Comment by scolapasta** [comment]
Agreed with @michbarsinai on this. while it does unfortunately affect some readability, I think it's still relatively straightforward to understand and it makes sense as a best practice. (why ever concatenate these strings for log messages which will never be used.

**Comment by pdurbin** [comment]
@michbarsinai @scolapasta would either one of you gentlemen like to make a pull request against what's currently written at https://guides.dataverse.org/en/5.11.1/developers/coding-style.html ?

**Comment by bencomp** [comment]
Sonarlint/Sonarcloud also complains about this, fyi.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
