### ISSUE TITLE
Metadata templates preview for some templates doesn't show all pre-filled metadata fields

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#4286]
In some dataverses (but not all), when dataverse owners preview metadata templates, the preview doesn't show all of the fields filled out in the template.

I navigate to [PSI dataverse](https://dataverse.harvard.edu/dataverse/PSI), then Edit > metadata template, select "view". I don't actually see all the template details (that you see when you select "Add dataset " and use the mentioned template). All it displays are the Terms of Use pane:

<img width="1455" alt="screen shot 2017-11-15 at 3 41 14 pm" src="https://user-images.githubusercontent.com/8322346/32859287-05c61a36-ca1c-11e7-9edf-c8e5e37a5261.png">

Dataverses of metadata templates whose previews **don't** show all pre-filled fields:
https://dataverse.harvard.edu/dataverse/PSI
https://dataverse.harvard.edu/dataverse/SIIL

Dataverses of metadata templates whose previews **do** show all pre-filled fields:
https://dataverse.harvard.edu/dataverse/dataverse-ux-research-dataverse
https://demo.dataverse.org/dataverse/juliangautier

**Comment by mheppler** [comment]
I was able to replicate this issue on [dvn-build](https://dvn-build.hmdc.harvard.edu/manage-templates.xhtml?dataverseId=1583). There was metadata in the template for the citation block, as well as a handful of other custom blocks, yet only the terms were displayed in the preview, same as Sonia's screenshot above.

**Comment by mheppler** [comment]
Narrowed this bug down to render logic/params on two specific lines breaking the Dataset Template Preview popup in dataset-license-terms.xhtml.

```
Severe:   Error Rendering View[/manage-templates.xhtml]
javax.el.ELException: /dataset-license-terms.xhtml @244,93 value="#{DatasetPage.restrictedFileCount}": java.lang.NullPointerException
	at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:114)
        ...

Severe:   Error Rendering View[/manage-templates.xhtml]
javax.el.ELException: /dataset-license-terms.xhtml @265,139 rendered="#{!settingsWrapper.publicInstall and (DatasetPage.restrictedFileCount > 0)}": java.lang.NullPointerException
	at com.sun.faces.facelets.el.TagValueExpression.getValue(TagValueExpression.java:114)
       ...

Severe:   java.lang.NullPointerException
	at edu.harvard.iq.dataverse.DatasetPage.getRestrictedFileCount(DatasetPage.java:3104)
```

There is also some questionable render logic `rendered="#{DatasetPage.dataset.fileAccessRequest}"` that should also be reviewed since this popup is displayed on the manage-templates pg as well as the dataset pg.

Removing the `restrictedFileCount` logic from the pg, displays everything properly.

![Screen Shot 2019-08-13 at 2 17 18 PM](https://user-images.githubusercontent.com/687227/62966454-13d63580-bdd5-11e9-8297-f6f9f1080135.png)

**Comment by pdurbin** [comment]
@sekmiller and I just discussed pull review #6303 and it makes sense. I moved it to QA.
