### ISSUE TITLE
Upgrade the production geoconnect with the latest code

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#4299]
This was discovered during the work on #4093: 
It appears that the code added to Geoconnect to make it possible for the Dataverse to request that any data files associated with a specific layer be deleted from Worldmap, was never deployed in production. 
This code is called when a previously public file with an associated map layer is restricted; and when a file with a map layer gets deleted from Dataverse. So as of now it's working on dvn-build.hmdc.harvard.edu, and NOT working on dvn-vm4.hmdc.harvard.edu ("dataverse-internal"). A quick inspection shows that dvn-build is using the dev instance of geoconnect (geoconnect-dev.herokuapp.com), and dvn-internal - the prod. version (geoconnect.datascience.iq.harvard.edu).

I'll find the ticket associated with the Geoconnect changes above. We should locate the instructions for updating and managing the Heroku instance; as well as whatever other information we may need to manage Worldmap-related issues going forward.

**Comment by djbrooke** [comment]
Closing this, as the migration of worldmap.harvard.edu to new infrastructure is resulting in Geoconnect and Worldmap being able to no longer communicate. We can investigate new Geospatial explore/analysis solutions in the future and will reopen specific issues as needed.
