### ISSUE TITLE
Searching using top right search bar gives validation error

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#4304]
On Harvard Dataverse (4.8.3), searching using the top right search bar gives a validation error. In the search URL, there's an ampersand before the query. Changing it to a question mark gives the search results. The search box in the body of the page works.

![screen shot 2017-11-27 at 10 06 55 am](https://user-images.githubusercontent.com/18374574/33273323-f00a63e4-d35a-11e7-9a20-ede146df59e0.png)

**Comment by pdurbin** [comment]
Good catch, @jggautier . I just created pull request #4305

It looks like this bug was introduced in 5c3c1f1 which shipped as part of 4.8.2 when we worked on #4214.

**Comment by mheppler** [comment]
Reviewed. Pull request approved. Passing to QA.
