### ISSUE TITLE
URL's for Older Version of Files Not Correct

### ISSUE THREAD

**Issue by shlake** [IQSS/dataverse#4308]
In Version 1.0 of this dataset:
https://dataverse.lib.virginia.edu/dataset.xhtml?persistentId=doi:10.18130/V3/KEVCF8&version=1.0

 the link to this file (which is only in Version 1; it was removed in Version 2), links incorrectly here:
https://dataverse.lib.virginia.edu/file.xhtml?fileId=1167&version=RELEASED&version=.0

The correct file link, I think should be: https://dataverse.lib.virginia.edu/file.xhtml?fileId=1167&version=1.0

But all the files in Version 1 have both "version=RELEASED" and "version=.0" 

connects to #2438

**Comment by pdurbin** [comment]
@sekmiller indicated that ee521cf fixes this bug so I'll put it in QA along with the other issues associated with pull request #4350

**Comment by kcondon** [comment]
should probably go through scope review next time since this was extra work not covered by the other ticket.

**Comment by djbrooke** [comment]
If it's fixed let's go ahead and push it through, we can discuss in retrospective

**Comment by pdurbin** [comment]
It was something I noticed while helping with #2438.

At https://github.com/IQSS/dataverse/issues/2438#issuecomment-351085188 I had written this:

> One observation I'll make is that as of d75e866 when I click a file in a search card I land on a URL with persistentId in the URL (i.e. http://localhost:8080/file.xhtml?persistentId=doi:10.5072/FK2/TSA7BQ ) but when I click the same file on the dataset page I see fileId in the URL instead ( i.e. http://localhost:8080/file.xhtml?fileId=237&version=DRAFT&version=. ). Do we want these to be consistent? I assume so. (Also note version=. which is very strange, perhaps related to the strange version=.0 reported at #4308.) I'm logged in as dataverseAdmin if that matters.

**Comment by kcondon** [comment]
OK, urls for file card and dataset tab are now using doi without encoding.
Will need to test api to see whether ids and dois both work.
