### ISSUE TITLE
Create a checklist for AWS S3 Migration

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#4309]
Use previous moving checklist(s). Some potential ways of breaking down the work across several sprints:

- Install Software
- Test Software
- Copy Files
- Determine Dates
- Provide Community Documentation

**Comment by djbrooke** [comment]
This issue will be completed when we have a list and have created Github items that we can take on during the next few sprints.

**Comment by djbrooke** [comment]
We met today around the checklist:

https://docs.google.com/document/d/1r3rX4sHCSFLbzX7lIuo36J7trmsNoDyWbWXDPhnA7_s/edit

The suggested breakdown of items was:

1. Validate delivered AWS architecture, including running basic Dataverse installation
2. Setup and test a full production Dataverse installation 
3. Plan and test migration and cutover 
4. Cut production over to AWS

I'll create these issues and link them here.

**Comment by djbrooke** [comment]
Moving this item to code review, because someone should review the issues created and make sure there's enough information for estimation and discussion. Thank you!

**Comment by djbrooke** [comment]
(moved this back because I got distracted by some maintenance issues before I put the desired amount of info in the created issues :))

**Comment by djbrooke** [comment]
@kcondon created the issues and added the appropriate amount of detail. Moving to code review.

**Comment by pdurbin** [comment]
I'm glad the checklist is public because I mentioned it here: https://groups.google.com/d/msg/dataverse-community/tnkqIt4RADc/rWk2cYT6BAAJ

**Comment by matthew-a-dunlap** [comment]
I have reviewed the list and added a comment. I feel like we all did a fair bit of review during our meeting Tuesday, so I think this can be moved from review.
