### ISSUE TITLE
As a researcher, I want to have the option of creating an API token when accessing an external tool 

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#4310]
We've recently been working on adding external tools in a modular fashion. In some cases (for example Modular Configure, though it may need to be more broad), a user's API token is required to use the tool. However the user may not have yet generated their token.

One option is to have the user opt in to the creation of the token with some text explaining that an API token is required (and possibly some explanation of what the token represents) and the ability to generate it on the spot.

A second option is to generate the token automatically for the user if they do not have one. We are leaning towards the "opt in" option.

**Comment by scolapasta** [comment]
Closing in favor of the newer #5671.

**Comment by TaniaSchlatter** [comment]
Reopening to see if work done for #5671 for "Configure" can be applied to address this for "Explore"

**Comment by pdurbin** [comment]
Re-closing, this time in favor of this issue:

- #9898
