### ISSUE TITLE
Multiple File Download Not working via API

### ISSUE THREAD

**Issue by shlake** [IQSS/dataverse#4311]
Per the instructions in the API Guide
http://guides.dataverse.org/en/4.8.3/api/dataaccess.html#multiple-file-bundle-download

I should be able to download multiple files with one URL. But this doesn't work, I get a 404 Not Found error. Here's the URL I tried:
https://dataverse.harvard.edu/api/access/datafile/2678613,2678615

Each file downloads fine one at a time:
https://dataverse.harvard.edu/api/access/datafile/2678613
https://dataverse.harvard.edu/api/access/datafile/2678615

I found an old issue #338, that talks about the multi download, but it's closed.

I get the same "error" response on V 4.7.1, which is what LibraData is running.

**Comment by scolapasta** [comment]
The API for multiple file bundle has an 's': 
/api/access/datafiles/$id1,$id2,...$idN

This works:
https://dataverse.harvard.edu/api/access/datafiles/2678613,2678615

**Comment by shlake** [comment]
Thanks for pointing that out. Obviously, I missed that "s". Hey, so when have engineers worried about grammar in their URLs ;-)
