### ISSUE TITLE
Move to AWS: Plan and test migration and cutover to AWS

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#4322]
Migration as used here refers to moving production data, config, and files to the AWS environment in such a way to minimize downtime and not lose any changes/ keep it in sync.
Cutover refers to the actual steps and timeline to switch between old production to being hosted on AWS. We need to minimize downtime where possible and understand how long task take and who does them. Also plan for problems -contact lists, rollback.

**Comment by landreev** [comment]
Finalizing the "Day X" (cutover date) task list.
Will link the document here shortly.

**Comment by landreev** [comment]
https://docs.google.com/document/d/1tZLhoK25kUFe_Frd92BuuJBW6F0pg2NTiwBbGKsenik/edit
