### ISSUE TITLE
Index: Fix "bean validation error" at end of index to occur inline at point of failure and to indicate bad value.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#4328]
During testing of more robust index all, we've encountered a bean validation using our existing test db, which indicates bad data according to current validation rules. The index completes and the exception occurs at the end after it posts completed but there is no indication what failed and why. 

It would be helpful if the validation error occurred while iterating through the datasets/dataverses so we know which thing is the problem and also post the bad value so we know what to correct.

Phil tells me this had been working at one point but has since broken.

As a potential admin feature, separate from this issue, would be to create a data validation util that an admin could run that would also report on such problems.

Steps to reproduce:
1. take a working index all, no errors at the end, ie. clean data, such as a new db with at least one dataset.
2. remove the at sign from the contact email directly from the db.
3. run index all again and see the bean validation error.

Bean validation errors can occur in two ways:
1. new restrictions were added to the data so older, non conforming data fails.
2. a db admin made a direct change to the db that violates the validation such as removing the at sign.

**Comment by pdurbin** [comment]
Here's the code I was showing @kcondon that once worked but apparently (as of 4.8.3 and who know how much earlier) no longer prints "invalid value" following by the details of where exactly in the database the violation is occurring as well as the value that is invalid (such as an email address without an "@" sign, as described above):

https://github.com/IQSS/dataverse/blob/v4.8.3/src/main/java/edu/harvard/iq/dataverse/api/Index.java#L182

```
if (cause instanceof ConstraintViolationException) {
    ConstraintViolationException constraintViolationException = (ConstraintViolationException) cause;
    for (ConstraintViolation<?> violation : constraintViolationException.getConstraintViolations()) {
        sb.append("(invalid value: <<<").append(violation.getInvalidValue()).append(">>> for ").append(violation.getPropertyPath()).append(" at ").append(violation.getLeafBean()).append(" - ").append(violation.getMessage()).append(")");
    }
}
```
