### ISSUE TITLE
investigate incremental improvement for incorporating integration tests in development

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#4332]
Related #4329 (and probably earlier versions); failed integration tests are not easily visible in GitHub/waffle (aka - they require someone remembering to check https://build.hmdc.harvard.edu:8443/ and notice the failure).

It should be possible to configure jenkins to notify GitHub when integrations tests fail (https://plugins.jenkins.io/pipeline-githubnotify-step ? others?).  While the ideal state would be having these failure notifications integrated with the other "checks" automatically performed on pull requests (travis and coveralls); "done" for this issue would be having a comment showing up in the PR if an integration test fails (or a comment on the PR that integration tests have run, with success/failure).

**Comment by pdurbin** [comment]
> configure jenkins to notify GitHub when integrations tests fail

We've had this working for years at this point thanks to @donsizemore 

Closing.

There's more to do around automated testing, of course, but we should create new issues for those efforts.
