### ISSUE TITLE
Storage allocation quota per user

### ISSUE THREAD

**Issue by oodu** [IQSS/dataverse#4339]
There is no quota limit currently enforced in Dataverse for a user account. DataverseNO is interested in any implementation in Dataverse to support sending “warning message” to a user or Dataverse admin about a user in total has exceeded a certain amount of GB  so that we are aware of the storage needs and can approve further storage should the user need it.

**Comment by djbrooke** [comment]
Thanks @oodu for opening this! This feature provides particular value for those installations that are open to all researchers, such as Harvard Dataverse.

**Comment by pdurbin** [comment]
Yes, thanks for opening this issue @oodu . As I said over at https://groups.google.com/d/msg/dataverse-community/knmn5BerUFE/zK7EgLE9BQAJ "I assume individual quotas would be easier to implement than group quotas. Quotas could also be imagined at the dataverse level, I suppose, but this would complicate reorganizing dataverses, which sometimes happens." It sounds like you're interested in user-level quotas. If I'm a contributor to a dataset, do files other people uploaded count toward my quota?

Also, please note that there's a related issue at #938.

**Comment by pdurbin** [comment]
@CCMumma is asking for the same thing (storage quotas) in #3939

**Comment by pdurbin** [comment]
Related issues (some mentioned above already):

- #938
- #3939
- #4339
- #7829
- #8549

Quotas also came up on this past week's community call with comments especially from @CCMumma and @DieuwertjeBloemen: https://docs.google.com/document/d/15yUGslKMUr4QCxGFuEsRyd2FdRoPWv3OzxZcVe5yEbs/edit?usp=sharing

**Comment by pdurbin** [comment]
Just merged:

- #10144

**Comment by cmbz** [comment]
2024/09/09: Closing because quotas are available at the collection level. Please open another issue if that functionality doesn't fully address your need for user account-specific quotas.
