### ISSUE TITLE
As a researcher, I want the file ingest process to automatically update the provenance for my file so that other researchers can see that a transformation has taken place.

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#4344]
The mockups supporting this user story are available here:

https://drive.google.com/file/d/1AO_L0utJwjHEBxpj5b2xNiVkOjOG545D/view

This story covers the automatic generation of the prov json when a file ingest takes place, since this is a transformation. This will be sent to the provenance system at publish.

**Comment by jacksonokuhn** [comment]
So talking to Matt and Leonid about this issue, it seems like we can't/shouldn't modify the provenance file when it's uploaded. Instead, I'm thinking the right thing to do is to store some metadata indicating that the data was converted on ingest, specifying the original and modified formats, and maybe the process used to covert it. Then on datasetPublish() we can push that additional information to CPL.

**Comment by djbrooke** [comment]
Will close for now, will reopen if we decide to take on a similar approach with further provenance work.
