### ISSUE TITLE
As a researcher, I want to preview the provenance JSON that I’ve uploaded so that I can verify that it’s correct.

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#4345]
The mockups supporting this user story are available here:

https://drive.google.com/file/d/1vMWm78rBdSelfuSzBtbIRqf9iAqbaxji/view

This story covers the preview of a researcher's own provenance file.

**Comment by jacksonokuhn** [comment]
https://github.com/CamFlow/cytoscape.js-prov

**Comment by mheppler** [comment]
Updated the mockups link in the first comment from @djbrooke to point to the mockups that include the Provenance tab on the file page, as opposed to the file upload workflow, which is covered in issue #4343.

Included in that 4343 issue is a comment of mine that outlines ["what we are building"](https://github.com/IQSS/dataverse/issues/4343#issuecomment-350782107). Here is an outline for this preview issue.

**What we are building**

Provenance (Edit) Popup
- Preview button opens new window with provenance graph generated from the contents of the provenance file that was uploaded

File Pg
- New Provenance tab, in between Metadata and Versions
- Add Provenance button that links to Provenance popup
- Provenance option in Edit button dropdown menu that links to Provenance popup
- "Why Use Provenance?" info text if provenance does not exist
- Info text if provenance exists
- Description label and provenance free-form text value displayed if it exists
- Graph if provenance info exists from JSON file upload and/or system transformations
- Export Provenance button if provenance exists

**Comment by djbrooke** [comment]
Will close for now, will reopen if we decide to take on a similar approach with further provenance work.
