### ISSUE TITLE
As a Dataverse Installation Administrator, I want files in destroyed datasets to have their corresponding provenance files cleaned up on the provenance system.

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#4349]
One way to envision this is as a new API endpoint to delete a provenance file on the provenance system, and then having the destroy process call that API to make sure everything is kept tidy.

Since there is not a UI for this, there are no mockups.

**Comment by djbrooke** [comment]
@jacksonokuhn interested in your thoughts here.

**Comment by jacksonokuhn** [comment]
I mean we could either make this automatic or add a toggle to the destroy datasets page that says "remove provenance," both make sense i think. In terms of the API endpoints, I think I already implemented one for this.

**Comment by djbrooke** [comment]
- We should delete the provenance when it's wrong or it should never have happened, so we want to do a delete in this case

**Comment by scolapasta** [comment]
@matthew-a-dunlap  DataFiles can't be deleted (unless they're draft, which means nothing has yet been sent to prov system).  Currently the only way of deleting a published file is by destroying the dataset.

**Comment by matthew-a-dunlap** [comment]
@scolapasta makes sense! So in the case that we delete a file between versions of the dataset we hold onto the prov.json in the old versions which still links to CPL.

A bit of a tangent: Does CPL keeps a different version of the prov info per version of a DataFile? I ask because as of now a user can go and change their DataFile prov info in between DataSet versions. I can see a number of ways this plays out and possibilities for mismatches between Dataverse's copy of the prov info and CPL's version of the prov info.

Some of this may become more clear tomorrow in discussions with Jackson.

**Comment by matthew-a-dunlap** [comment]
I have begun stubbing out the rest calls for talking to CPL. We have run into some issues with SWIG finding the correct methods to call when a rest request is sent. We have begun debugging and will continue to do so.

**Comment by matthew-a-dunlap** [comment]
There is an open question about whether this call and other calls should be done asynchronously. I'm writing out the low level api commands now but before we get deep into using them there should be some discussion.

**Comment by matthew-a-dunlap** [comment]
Got CPL working in vagrant but am running into issues with the rest api. Have still stubbed out a few commands.

Tomorrow I plan to have a better understanding of what to do with the json we are taking in. This includes asking @jacksonokuhn & @pdurbin more details about the data we are dealing with to decide what objects we may want to be creating and passing around instead.

**Comment by pdurbin** [comment]
I added a few fixes and FIXMEs in a3f9957 and 6086f22 as well as various tests to exercise the prov system. The next API endpoint to work on is probably the one where we send JSON at a bundle id.

**Comment by djbrooke** [comment]
Will close for now, will reopen if we decide to take on a similar approach with further provenance work.
