### ISSUE TITLE
Clean up comments in displayed html

### ISSUE THREAD

**Issue by matthew-a-dunlap** [IQSS/dataverse#4351]
Dataverse has a large number of HTML developer comments that are unsightly when looking at the source code. Furthermore, commented out render logic in our XHTML can lead to unforseen data being inserted into our webpages. Instead of using the ui:remove tag on each comment (which is inevitably forgotten), we can instead use this chunk in the web.xml to remove all comments.

`<context-param>
    <param-name>javax.faces.FACELETS_SKIP_COMMENTS</param-name>
    <param-value>true</param-value>
</context-param>`

This can still be easily turned off by developers working on their local machines but will ensure that our production machines look good and are safer!

**Comment by pdurbin** [comment]
6f1ef61 makes sense to me. I think you should go ahead and make a pull request, @matthew-a-dunlap
