### ISSUE TITLE
Widgets do not work with Wordpress

### ISSUE THREAD

**Issue by tlchristian** [IQSS/dataverse#4357]
Because the dataverse widget code uses script tags and javascript, it is incompatible with Wordpress.  Please make plans to provide code that enables embedding of the dataverse widgets in platforms other than OpenScholar.  There is interest on UNC's campus to use the widget, but our users cannot because UNC uses Wordpress for campus websites.

**Comment by tlchristian** [comment]
Hm.  Not sure.  I'll talk to our web support folks here at UNC and get more information on the limitations.  They mentioned security issues with js and would have to make alterations to the campus's Wordpress.  Still, even if js ends up being no problem, we still will need to be able to embed without script tags.  Thanks!

**Comment by mheppler** [comment]
@tlchristian @pdurbin -- our embed widget feature was based off of a similar JS-based approach that Twitter uses for their tweets. Does Wordpress provide a special plugin for embedding tweets or does their JS embed code work?

**Comment by tlchristian** [comment]
@pdurbin @mheppler This is what our website tech support said:  
WordPress does not allow JavaScript in their pages or posts by default. We generally do not allow JavaScript at all because users can add malicious data without even knowing it, so it’s a security measure.
Sorry, but I don't have the WordPress expertise to tell you if it has a special plugin, but I do know that it uses iFrames.

**Comment by pdurbin** [comment]
@tlchristian obviously the solution is to switch from Wordpress to OpenScholar: https://twitter.com/kinggary/status/950822394754510849 😄 

You might want to ask on https://groups.google.com/forum/#!forum/dataverse-community if anyone has gotten the Dataverse widget to work on Wordpress. I don't have much experience with Wordpress either. I took a quick look at https://wordpress.org/about/security/ but I don't see anything about Wordpress not allowing Javascript by default but I believe you.

**Comment by tlchristian** [comment]
@phildurbin  I actually figured it out for Wordpress.  You use the iframe shortcode with this syntax:
[iframe src="DATAVERSEURL + ?widget=dataverse@DATAVERSEALIAS"]  Add iframe attributes if you want.  That is all you have to do.  That's really all.

**Comment by pdurbin** [comment]
@tlchristian great! Do you think this is non-obvious enough to mention in the Dataverse guides? Or somewhere? I guess people might just google and find this issue.

**Comment by tlchristian** [comment]
Well, I happened across the solution by chance, so I think it would be nice to add this to guides somewhere.

**Comment by pdurbin** [comment]
Ok, I guess that would mean future versions of these pages:

- http://guides.dataverse.org/en/4.8.4/user/dataset-management.html#widgets
- http://guides.dataverse.org/en/4.8.4/user/dataverse-management.html#widgets

Want to make a pull request, @tlchristian ? 😄

**Comment by mheppler** [comment]
Adding a new section to those pages would definitely help. Not sure that I know enough about Wordpress to write and test the documentation but I'll give it a shot.

>Adding Widgets to a Wordpress Website
>1. Download and set up the iframe plugin: https://wordpress.org/plugins/iframe/
>2. Either build a new page or navigate to the page you would like to use to show the Dataverse widgets
>3. Use the iframe shortcode syntax [iframe src="DATAVERSEURL + ?widget=dataverse@DATAVERSEALIAS"]
>4. Suggested iframe attributes to also include are:
>    - style="border:0; background:url(https://dataverse.harvard.edu/resources/images/ajax-loading.gif) no-repeat 50% 50%;"
>    - width="100%"
>    - height="800"

Does that look good @tlchristian?

**Comment by scolapasta** [comment]
@mheppler I get that this may be the best (only?) way to get into Wordpress, but should we be at all concerned that this is skipping past our widget model? i.e. we provide javascript, so that if/when we ever want to change the underlying iframe structure we can and it will automagically happen. In this scenario, the wordpress use of widgets would be "stuck in time".

At the very least, if we include this in official docs, we should flag it as a workaround and explain why it's not ideal.

**Comment by mheppler** [comment]
Yes, good catch @scolapasta. This work-around would result in a broken widget in the researcher's Wordpress website if and when the widget code ever gets revamped.

**Comment by tlchristian** [comment]
I just happened across that iframe syntax on Gary King's website when, on the dataset page, I copied the breadcrumb URL to the dataverse page:  https://dataverse.harvard.edu/dataverse/king?widget=dataverse@king.  Not sure how that gets generated, but if that URL remains the same even if the underlying iframe structure changes, would it still work?

**Comment by mheppler** [comment]
@tlchristian as @scolapasta pointed out, that URL is generated by our widget.js file, which your workaround circumvents. It is a legitimate workaround for the time being, but we could make changes to our URL structure for dataverses, or to our query strings, which we would apply to our widget.js, but it would not be applied to your Wordpress workaround, resulting in a broken iframe.

Changes of this magnitude are very unlikely in the near term, but not something we can rule out entirely, and isn't something that we can easy notify Wordpress users of, because we have no way of easily knowing who is using this workaround.

**Comment by tlchristian** [comment]
Hopefully, future developments to the widget will keep in mind a wider audience beyond OpenScholar users.

**Comment by pdurbin** [comment]
@tlchristian now you're making me wonder if we (royal we!) should develop a WordPress AddOn for Dataverse. 😄 It might be good advertising, a least. 😄

**Comment by scolapasta** [comment]
@tlchristian The widget was not specifically designed for OpenScholar, but for general websites, with OpenScholar being just one example. Wordpress, unfortunately is an exception since it is restrictive, but as @pdurbin points out maybe we need an exceptional solution for that case.

**Comment by pdurbin** [comment]
For the record, the other week I tried to get a widget working on a Wordpress site and failed miserably. I'm not in control of the installation ( http://blogs.harvard.edu/pdurbin ) so I can't make system-level changes to try to get it to work.

@tlchristian how do you feel about putting "Wordpress" in the title of this issue? That's mostly what it's about, right?

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
