### ISSUE TITLE
Database schema: Make all column types and sizes the same or supportive of v3.6 sizes and types, eg. text, text etc.

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#436]
---

Author Name: **Kevin Condon** (@kcondon)
Original Redmine Issue: 3851, https://redmine.hmdc.harvard.edu/issues/3851
Original Date: 2014-04-14
Original Assignee: Steve Kraffmiller

---

To facilitate data migration, it would be good to make all the column data types and sizes the same as in v3.6 unless there is a specific decision not to.

**Comment by scolapasta** [comment]
@michbarsinai I think we are likely all set on this, but would you mind doing a review of this, as you did with the not null?

Dynamic metadata for datasets should be all set, so it's just checking other name and description type fields against what we allowed  3.6.

**Comment by michbarsinai** [comment]
Where's the 3.6 code? I didn't find it on GiHub.

**Comment by scolapasta** [comment]
I am passing this to QA as we have been to able to do a complete migration (albeit with some issues) and did not have any db issues.
