### ISSUE TITLE
Added Postgres port variable to install script of DataVerse v4.8.x

### ISSUE THREAD

**Issue by ffritze** [IQSS/dataverse#4365]
I have recently tried to install the DataVerse version "v4.8.3". I used to set a custom port for the Postgres database connection. I discovered that the "install" script does not correctly set the custom port for the psql command when creating a new database. I corrected this issue in the attached perl file.

[install.txt](https://github.com/IQSS/dataverse/files/1538143/install.txt)

**Comment by pdurbin** [comment]
@ffritze thanks! I just did a `diff` as of ef7dce7 so we can see what the change you made was:

`712,713c712,713`
`<     $psql_admin_exec = "PGPASSWORD=" . $CONFIG_DEFAULTS{'POSTGRES_ADMIN_PASSWORD'} . "; PGPORT=". $CONFIG_DEFAULTS{'POSTGRES_PORT'} ."; export PGPASSWORD; export PGPORT;" . $psql_exec; `
`<     $psql_exec = "PGPASSWORD=" . $CONFIG_DEFAULTS{'POSTGRES_PASSWORD'} . "; PGPORT=". $CONFIG_DEFAULTS{'POSTGRES_PORT'} ."; export PGPASSWORD; export PGPORT;" . $psql_exec; `
`---`
`>     $psql_admin_exec = "PGPASSWORD=" . $CONFIG_DEFAULTS{'POSTGRES_ADMIN_PASSWORD'} . "; export PGPASSWORD; " . $psql_exec; `
`>     $psql_exec = "PGPASSWORD=" . $CONFIG_DEFAULTS{'POSTGRES_PASSWORD'} . "; export PGPASSWORD; " . $psql_exec; `

**Comment by djbrooke** [comment]
Hey @ffritze - if you'd like for us to review a potential code change for integration into the develop branch and for release to the community, please feel free to create a pull request with the changes. Let me know if you need help setting up the PR. Thanks!

**Comment by pdurbin** [comment]
@ffritze hi! There's a fairly massive refactoring of that Perl script going on in pull request #4805 and lost of details in #4764 if you'd like to check it out. Are you still interested in getting your change above incorporated in?

**Comment by ffritze** [comment]
@pdurbin hi. At the moment I don't have the time to look at the pull requests you have mentioned. But I have to say that I have forgotten to do a pull request for my small changes of the install script. Yesterday I tried to installl a new instance of DV but found the install script still buggy. So I inserted my changes which I mentioned on the 7 Dec 2017 and it worked. So I would suggest that I wait for a new version of the Perl script and see if the POSTGRES_PORT is used and set correctly. If not I can still make a pull request with my fix.

**Comment by pdurbin** [comment]
@ffritze that's fine. At this point, yes, it would be best for you to wait until #4805 have been merged before you make your own pull request with your fix for the port. Thanks for your patience. Do you mind changing the title of this issue to something about the postgres port? Thanks!

**Comment by pdurbin** [comment]
@ffritze back in 2019 we (well, @landreev ) re-wrote the installer in Python. The POSTGRES_PORT variable should work. Would you like to give it a try? Or should we close this issue? Please see https://guides.dataverse.org/en/5.11.1/installation/installation-main.html#running-the-dataverse-software-installer
