### ISSUE TITLE
Configure or turn off "Support" link?

### ISSUE THREAD

**Issue by laulandn** [IQSS/dataverse#4368]
Hi guys!  We're looking to either turn off or change where the Support item in the header goes.  I apologize if I missed an option for this someplace. We're a consortium, and our goal is avoiding global support...instead people would contact local liaisons at their institutions.  (Part of this is because each member institution may have different policies, etc).  We're still working out how best to do this, but one way would be to have the Support link go to a page with links for each institution.  If not that, hiding the link wouldn't hurt. One way I've tried is via CSS, but we figured this might be something others would be interesting in.

Thanks!

Nick Lauland
Texas Digital Libraries
texasdatarepository.org aka dataverse.tdl.org

**Comment by pdurbin** [comment]
@laulandn sure, maybe you can disable the "Support" link with a custom style sheet: http://guides.dataverse.org/en/4.8.4/installation/config.html#custom-stylesheet

If there's a lot of demand for this, I can imagine a future database setting to hide that "Support" link. There's already a way to hide the "Sign Up" link (`:AllowSignUp`) and the "About" link only shows up if it's configured (`:NavbarAboutUrl`).

**Comment by laulandn** [comment]
That's good enough for us!  Thanks!
