### ISSUE TITLE
Metadata blocks should be unique

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#437]
---

Author Name: **Elda Sotiri** (@esotiri)
Original Redmine Issue: 3852, https://redmine.hmdc.harvard.edu/issues/3852
Original Date: 2014-04-14
Original Assignee: Gustavo Durand

---

Its currently possible through the api to insert the same metadata block twice. 
It seems like the api should enforce uniqueness.  
An easy way to duplicate this is to run the ./datasetfields.sh twice

**Comment by scolapasta** [comment]
@kcondon I believe this is no longer true, Kevin could you retest?

**Comment by kcondon** [comment]
OK, ran script twice and it did not create duplicates. Closing
