### ISSUE TITLE
As a researcher, I want the metadata export to be available only if it matches the dataset version that's available for download so that I don't get a mismatch

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#4372]
When I'm on the landing pages of old dataset versions, the metadata files I'm able to export (DDI or  DC in xml, or native JSON or Schema.org in json) contain metadata not of the dataset version I'm looking at, but of the latest dataset version. There's no indication in the UI that that export file will contain metadata for the latest version and not the version I'm on.

When users view landing pages of older dataset versions, the UI should avoid giving researchers the impression that they're downloading the metadata they're able to see on that page's metadata tab.

**Comment by djbrooke** [comment]
Thanks @jggautier - I tooled with the user story format for a bit, but these "as a user I want to be prevented from doing something" ones are tough :) We can connect about it next week!

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.

**Comment by pdurbin** [comment]
Related:

- #11305
- #4132

**Comment by pdurbin** [comment]
We don't plan to fix this in the old JSF UI. I created this issue to fix it in the new React UI:

- https://github.com/IQSS/dataverse-frontend/issues/1008
