### ISSUE TITLE
As a researcher, I want my uploaded provenance file to be validated so that I know it's in an expected format

### ISSUE THREAD

**Issue by matthew-a-dunlap** [IQSS/dataverse#4378]
After a researcher enters or uploads their provenance information, we should ensure that the provenance json matches the formatting we expect. We will need to do some sort of validation to ensure our users are uploading and sharing usable provenance metadata.

There is an open question as to whether there will be a schema file for us to use to validate. If there is, we will need to take that schema in and use it for validation. If not, we will likely do some more manual hardcoded validation based upon objects we expect.

Relates to https://github.com/IQSS/dataverse/issues/4343

**Comment by pdurbin** [comment]
There is a schema file. It's at https://www.w3.org/Submission/prov-json/schema

It's mentioned at https://www.w3.org/Submission/prov-json/#validation

Here's what it says:

> A schema for PROV-JSON is provided, which defines all the valid PROV-JSON constructs described in this document. The schema was written using the schema language specified in [JSON-SCHEMA] (Version 4). It can be used for the purpose of validating PROV-JSON documents. A number of libraries for JSON schema validation are available at json-schema.org/implementations.html.

My understanding is that we should look for a suitable Java library at http://json-schema.org/implementations.html and see if we can get it to validate the JSON Schema above or some other schema.

I think it'll be nice to be able to validated JSON Schemas. We've even been asked by the community to provide some sort of schema for "native" JSON we use in Dataverse but I can't find the thread at the moment.

**Comment by matthew-a-dunlap** [comment]
We should maybe prioritize this issue @djbrooke . Right now we do some validation but not something that actually looks to the full json schema. 

The longer we leave our code out without it the more likely we'll have invalid prov files in our system that could break things later on. If we do it soon enough we may be able to decrease the complexity of checking validity at different points. It should be a quick, self-contained change.

Hearing about Prov interest during the community meeting reminded me that this was broken off from the first release of work.

**Comment by djbrooke** [comment]
@matthew-a-dunlap let's bring it to the backlog grooming for estimation. I'm more inclined to wait until we see use of this feature before working on it, but if it comes back small I could be be convinced. Thanks for tagging this!

**Comment by kcondon** [comment]
@matthew-a-dunlap I've just tried using the elisabeth.json file we used as a prov file during initial testing and that comes back as invalid. Is this a problem and is there a valid one to use?

**Comment by matthew-a-dunlap** [comment]
@kcondon Turns out a few of the prov files we used before are actually invalid based upon the schema. Here is a valid sample (I had to zip it to upload): 

[provout.json.zip](https://github.com/IQSS/dataverse/files/2196004/provout.json.zip)

**Comment by matthew-a-dunlap** [comment]
Note that I updated the branch since Friday. Caught an exception when the json is invalid. Also merged in develop.

**Comment by matthew-a-dunlap** [comment]
Lastly: The unit tests for the json validation are pretty slow, we may want to comment out the annotation that has them run on build as it's a fair bit of slowdown.

**Comment by matthew-a-dunlap** [comment]
@jacksonokuhn After implementing [schema](https://www.w3.org/Submission/2013/SUBM-prov-json-20130424/schema) validation for the prov json, I have been unable to find almost any example in the wild that passes the validation. We are curious what your (and maybe Matt's) take on it is. My assumption in in the end is that we need to be strict about the schema because that's what gives it value, but maybe there are strong norms outside the schema we have to take into account?

fwiw, I doublechecked my schema validation code with [this web tool](https://www.liquid-technologies.com/online-json-schema-validator) to make sure there wasn't something wrong with my implementation. The [w3c examples](https://github.com/CamFlow/cytoscape.js-prov/tree/master/json) Matt's repo pass but that's it.

**Comment by jacksonokuhn** [comment]
Where are you drawing examples from? I’m curious which tools in particular are responsible for the JSON that isn’t working.

**Comment by matthew-a-dunlap** [comment]
@jacksonokuhn To be honest it was a pretty chaotic round of google searches. I pulled a fair number off https://www.hl7.org/ . If there are specific systems we know to be generating valid prov I'd like to know as well!

**Comment by matthew-a-dunlap** [comment]
@jacksonokuhn I think the main thing our group is looking to understand is whether we should be strict with enforcing the schema, and if not how should we be more lax

**Comment by jacksonokuhn** [comment]
my general feeling is that we should err on the side of relaxedness, but if
all the example stuff I've given you so passes, that's a good sign

**Comment by jacksonokuhn** [comment]
I should honestly just take a look at the validation code though

**Comment by matthew-a-dunlap** [comment]
@jacksonokuhn The code really just checks the schema against the json, nothing more. We felt that we should apply some strictness on intake of the provenance, otherwise we may end up with a lot of data that has no use.

**Comment by jacksonokuhn** [comment]
that's fair. it might be fair to relax the schema though. I'll think about
the right way to do that

**Comment by jacksonokuhn** [comment]
Actually looking at this more, I think the schema is fine as is. I actually
think the stuff that's failing is supposed to fail. It might be useful to
be able to store PROV-JSON invalid provenance as a simple text file or
something though.

**Comment by matthew-a-dunlap** [comment]
@jacksonokuhn Thanks for looking into this! I agree that would be nice to have as well, as often folks won't really be able to easily fix their broken provenance data...

**Comment by matthew-a-dunlap** [comment]
Note: The prov junit tests are commented out in this branch, as they are slow. When we take on #4896 they should be uncommented and added to a full test suite
