### ISSUE TITLE
File Storage - Trusted Storage Services (TSS)

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#4379]
Dataverse will need to support external storage services for cases where the data cannot be moved to the dataverse storage. In these cases, we will define a concept of Trusted Storage Services (TSS) which guarantee resiliency while providing the appropriate metadata to Dataverse.

We'll need to add and expand existing APIs in order to accept this metadata, and also to have a list of supported TSS.

We'll likely have to break this issue out into several smaller chunks to support this overall functionality.

**Comment by scolapasta** [comment]
Some of this functionality is related to the work we've done with DCM (Data Capture Module), as well as what we're considering for DLM (Data Locality Module).

**Comment by djbrooke** [comment]
Closing in favor of #5213.
