### ISSUE TITLE
Move some Installation Guide content to Admin Guide

### ISSUE THREAD

**Issue by dlmurphy** [IQSS/dataverse#4382]
@scolapasta recently pointed out that some subsections of the Installation Guide might make more sense in the Admin Guide.

Installation guide sections that should probably be moved to admin guide:
-Converting Accounts
-Converting Local Users to OAuth
-Converting OAuth Users to Local

Sections that should probably appear in both (with slight modifications):
-Branding Your Installation
-Enforce Strong Passwords for user accounts

Let's take a more thorough look at the Installation and Admin Guides, make sure that content is placed where it belongs, and move/edit it in response.

**Comment by pdurbin** [comment]
Good idea. I'm not sure how extensive of a reorg you're planning but the last time we got a ton of great feedback from the community. See the post at https://groups.google.com/d/msg/dataverse-community/qujUFJDYXG0/0BhECCp0HQAJ and the Google doc at https://docs.google.com/document/d/1GLky44JbtCNhGuavLXGEP8WPNdjbyHNxalEGjR78MaA/edit?usp=sharing . Of the top of my head @donsizemore and @pameyer might have good opinions on what to put where.

At that time the thinking was that four guides (User, Installation, API, and Dev) was enough but I'm glad that theses days we're comfortable with having an Admin Guide.

In particular, the "config" part of the Installation Guide is getting quite long.

It would be fairly easy to pull in a number of other Installation and Admin Guide issues (especially suggestions from the community) into this effort.

**Comment by pdurbin** [comment]
Heads up that I'm messing with the Installation Guide over in #4384.

**Comment by pdurbin** [comment]
I don't see a ton of value in leaving this issue open. Yes, we could reorg the guides. It's probably better to create a Google doc to capture a more specific plan and then create a new issue when we're ready to execute it.
