### ISSUE TITLE
As a Dataverse Installation Administrator, I want to add an alternative OAuth provider as a plugin, so that I don't have to fork the core code

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#4383]
The code for adding a new Oauth provider is currently modular, but those modules currently have to reside within the core code. We should modify the code so that this can be added as a plugin (or configurable json file), per comment from @michbarsinai on #4334:

"Creating a completely general OAuth2 client would be nice, but OAuth2 is very permissive, so there's a lot of variance between providers. Even ScribeJava ended up writing multiple clients, one-per-service. It may be possible to generalize a bit, though, in the same manner we did with the REST-based workflow step.
Another option is to open the OAuth2 providers as a plug-in area. This way, the Dataporten OAuth2 client will be developed as a plug-in, and so there won't be a need to maintain a fork."

**Comment by knikolla** [comment]
This can be handled via middleware. For example, for SAML authentication you're using Shibboleth, and depending on it for providing you with the user's `eppn` via environment variables which you use to identity the user.

This approach can be extended to use something else (like https://github.com/zmartzone/mod_auth_openidc) for providing you with the user's identity via an environment variable and letting it handle all the auth stuff.

**Comment by poikilotherm** [comment]
This was created as a successor to #4334. Since 2017/2018, the world moved on and now OpenID Connect is an emerging standard. As OpenID Connect support offers adding authentication providers by configuration, not by pull request, maybe this issue should be closed in favor of #5974 or even already merged basic support #6432?

**Comment by pdurbin** [comment]
@poikilotherm maybe. Or maybe someone should create a fresh issue with a title like this:

"As a Dataverse installation administrator, I want to add an alternative OAuth provider through configuration so I don't have to fork the core code"

The pull request for this issue would be an update to the docs to explain how to do this.

@knikolla nice to see you in this issue. In theory, Dataverse is compatible with Keycloak now that pull request #6433 has been merged, if that's of interest to you. 😄

**Comment by djbrooke** [comment]
Closing in favor of OIDC, which was added in 4.19 by @poikilotherm
