### ISSUE TITLE
promote EL7 as the recommended platform 

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#4384]
Per @pdurbin and @landreev in commit 10b302b172c5bcfb8c6bec416f0a4eae3a2c4054 on #4157 

> in our repo there are a number of places where we reference el6: Vagrant files, Docker files, the Installation Guide, and probably other stuff I'm not thinking about. A future pull request would switch all of it from el6 to el7." — @pdurbin 

> We are going to 7 on the new production servers, on AWS. Whether upgrading is worth the trouble on our local test servers... yeah, probably. It was a bit of a pain to figure out how to install these packages on CentOS 6, so that Kevin could test it... because everything is so old there. We should promote 7 as the recommended platform. — @landreev

**Comment by pdurbin** [comment]
@donsizemore and I just talked about his pull request (#4385) at http://irclog.iq.harvard.edu/dataverse/2017-12-20#i_61662 and in summary I think he's done (thanks!) but I'd like to take a swing at tweaking the guides to emphasize RHEL7/CentOS7 (el7 for short) over RHEL6/CentOS6 (el6). I also may take a quick look at upgrading the Minishift images from el6 to el7.

**Comment by pdurbin** [comment]
> I also may take a quick look at upgrading the Minishift images from el6 to el7.

@pameyer pointed out to me that these images are already using el7. Great!

That means at this point this issue should be a review of the Installation Guide.

**Comment by pdurbin** [comment]
I made my main update to the guides in 98ad217 and am moving this issue to code review so @landreev @dlmurphy and anyone else who may be interested can take a look.

@donsizemore is going to take a look into getting `vagrant destroy` working again (as discussed at http://irclog.iq.harvard.edu/dataverse/2017-12-21#i_61766 ) but I'm ok with the pull request being merged as-is.

**Comment by pdurbin** [comment]
@donsizemore we discussed this issue in standup this morning and @landreev is happy with the changes that have been made to the docs (especially with regard to the version of R for TwoRavens) so we moved it to QA. I'm not too worried about the `vagrant destroy` thing since I documented a workaround in the Vagrantfile. If you're really itching to work on pull request #4385 some more please get in touch before pushing any commits. Thanks!
