### ISSUE TITLE
Some Question about IP Group

### ISSUE THREAD

**Issue by pengchengluo** [IQSS/dataverse#4386]
Hi,
recently I install the dataverse 4.84 and test the function of IP Group. I add an IpGroup through the dataverse API and then file downloader role is assigned to IP group on a dataset.  See following picture

![image](https://user-images.githubusercontent.com/7343585/34033173-1f9d16d0-e1b4-11e7-8ad8-bd9a4495ddb7.png)

However, I find that user whoes ip address is in the range of the IP group still can't download the restricted files. See following picture
![image](https://user-images.githubusercontent.com/7343585/34033418-1fe54a12-e1b5-11e7-9f91-b2ba1a41ef1f.png)

Besides, I am wondering what the eea46552f88003ca1677904607cc27b2030376ac commit mean? Why the following code was commented

![image](https://user-images.githubusercontent.com/7343585/34033546-9ee99412-e1b5-11e7-9e1c-ef1d18c06f0e.png)

**Comment by pdurbin** [comment]
@pengchengluo hi! Over in 9fa3f1a (unmerged, part of pull request #4367) I reverted that commit and I'm trying to get IP Groups working again for issue #4268 which is currently in the "Development" column at https://waffle.io/IQSS/dataverse . You are very welcome to look at what we're talking about in that issue and pull request and help diagnose the problem and help get IP Groups working again. Thanks!

**Comment by pengchengluo** [comment]
Thanks! I test the code of 4268-ip-groups-broken branch and find it works correctly now.

**Comment by pdurbin** [comment]
@pengchengluo great! Thanks for testing that branch (it's at commit 98672ad right now). I just moved this ticket to the "Code Review" column at https://waffle.io/IQSS/dataverse to match #4268. Would you be willing to close this issue? (The creator of a GitHub issue has permission to close it.) You could follow #4268 instead.

**Comment by djbrooke** [comment]
Hi @pengchengluo - 

The latest release has this fix:

https://github.com/IQSS/dataverse/releases/tag/v4.8.5

**Comment by pengchengluo** [comment]
@djbrooke Thanks！
