### ISSUE TITLE
Preservation: Improve file fixity and data integrity practices

### ISSUE THREAD

**Issue by dlmurphy** [IQSS/dataverse#4388]
During a meeting today with @djbrooke, @scolapasta, @sbarbosadataverse, and @jggautier, the subject of file fixity in Dataverse came up. We resolved to look into how we might improve our preservation practices in this area. 

I've chosen to use the National Digital Stewardship Alliance as my main source of archival best practices, as their consortium includes major players in digital preservation such as Harvard Library, the Library of Congress, NARA, and the Metropolitan New York Library Council. For more detail on some recommended practices, I've also referred to the Digital Preservation Coalition's [Digital Preservation Handbook](http://www.dpconline.org/handbook/technical-solutions-and-tools/fixity-and-checksums), which follows from the NDSA's recommendations.

The NDSA identifies "file fixity and data integrity" as one of the five functional areas that are at the heart of digital preservation systems. In [this paper](http://www.digitalpreservation.gov/documents/NDSA_Levels_Archiving_2013.pdf?loclr=blogsig) they offer a practical blueprint for how institutions can improve their product's ability to guarantee file fixity and data integrity. Their model is presented as a set of five levels of practice, with each successive level incorporating and building on the previous.

Here is their chart showing their levels of file fixity and data integrity:
![fixity0](https://user-images.githubusercontent.com/22962740/34060374-5eba2f0e-e1b1-11e7-9e8d-c983ad32bdae.PNG)
![fixity](https://user-images.githubusercontent.com/22962740/34060337-36e31c2a-e1b1-11e7-916c-a338f2c7b7b5.PNG)

Currently we are between Level 1 and 2 of this model. When a user uploads a file, we create fixity info by creating and storing an MD5 hash that we and our users can later use to perform a checksum verifying the integrity of the file. 

For this GitHub issue, I recommend we take what practical actions we can to bring our practices to level 3 or 4 of this model. There are two main actions we can take that will bring us closer to this goal: 

**1. Virus-check all uploads.**
Just as an archive of papers checks for insects and mold when accessioning a document, we should make sure we check for malware that could interfere with the contents of the data and potentially spread to other data in our repository. If possible, we should automatically scan all uploaded files for malware (or at least, scan any file types that have the potential to carry malware).

**2. Perform regularly scheduled checksum comparisons on all files.** 
Our use of MD5 for checksums fits recommended best practices, but we should perform regularly scheduled checks against the MD5 to more fully comply. This will ensure that files stored in Dataverse have not been altered by any means or subjected to random error via bit-rot or transfers between servers, etc. Because Dataverse maintains multiple copies of each file in multiple storage locations, if an automatic checksum comparison returns an error, then we can replace that copy of the file with a clean copy that does pass the checksum, taken from one of the file's alternate storage locations. For systems like ours, it's recommended that we schedule checksum comparisons every 6 months.

**Comment by pameyer** [comment]
@dlmurphy I'm surprised that multiple-checksum schemes isn't in the recommendations (or any discussion about pre-image vs collision attacks on MD5/SHA1).

"Create fixity info on ingest if not provided" doesn't show up in level 2+ ; do you see that as being a problem?

**Comment by dlmurphy** [comment]
@pameyer thanks for weighing in on this. I'm not too surprised that they left out the cybersecurity details, as archivists are rarely experts in that domain. You're right that these attacks are a possibility, but they seem like an unlikely one to me. 

In the chart I embedded, the levels' requirements are cumulative, so level 2+ actually do include "create fixity info on ingest if not provided", they just didn't want to list it every time.
