### ISSUE TITLE
Permissions - Improve Descriptions of Roles

### ISSUE THREAD

**Issue by dlmurphy** [IQSS/dataverse#4389]
When you assign roles to users on both the dataverse and dataset level, the summaries of those roles are inaccurate and confusing. I'd like to review and rewrite these descriptions. The descriptions are actually populated from the database, so we'll need to change their database values (found in the Description column of the Dataverserole table). We'll then need to write database update scripts for us and for other installations, as well as update existing scripts meant for new installations setting up their databases.

Here are some examples of uninformative/inaccurate descriptions:
![roles1](https://user-images.githubusercontent.com/22962740/34131012-f5317592-e417-11e7-9a58-02dcad827610.PNG)
(Obviously, this role allows you to edit more than just the license and terms, it allows you to edit all metadata.)

![roles2](https://user-images.githubusercontent.com/22962740/34131107-4ab763d2-e418-11e7-9894-bcc367c492cb.PNG)
(Similar problem here)

Role descriptions need to be edited not just for accuracy, but additionally to make sure they emphasize the main point of each role and important distinctions between roles. This will help alleviate user confusion we've observed (for example, dataverse owners assigning the Contributor role when they meant to give users the permissions of the Dataset Creator role).

**Comment by mheppler** [comment]
In the issue "Roles Description: Update File Downloader Description #3022" it was suggested:
> In the UI for roles, we need to add to the description for File Downloader that this is only for published dataverses and datasets.

Closed that issue in favor of this as it is more recent, and includes improving all the descriptions. This should be addressed as part of the DataTags integration #871.

**Comment by jggautier** [comment]
Another example of a role description that could be clarified is the Member role:

<img width="605" alt="screen shot 2018-11-29 at 11 09 17 am" src="https://user-images.githubusercontent.com/18374574/49235110-4d8e1a00-f3c7-11e8-8677-d3b5f59bdae0.png">

The description doesn't mention that people with the "Member" role can also download files. You might infer this from the listed permission "DownloadFile", but someone thought that that only applied to files when the dataset was unpublished. Once the dataset was published, they didn't expect the person with the Member role to be able to download the files (which were restricted files).

**Comment by mheppler** [comment]
Related to _For some roles, objects are not populated in alert message #5352_.

**Comment by AACGSR** [comment]
Hi there. Not sure whether this belongs here or needs an own issue. But we found that the right "DownloadFile" allows people to download restricted files. For not restricted files, even roles without "DownloadFile" can download files. (@RightInTwo created a role "observer" for our dataverse, which has the rights " ViewUnpublishedDataverse" and  "ViewUnpublishedDataset" only). This is on Dataverse version 4.11 fyi

**Comment by pdurbin** [comment]
@AACGSR yeah instead of...

**File Downloader** - A person who can download a published file. 

... maybe it should be called...

**Restricted File Downloader** - A person who can download a restricted published file. 

Here's a screenshot from 4.18.1 for context:

![Screen Shot 2020-01-24 at 2 20 42 PM](https://user-images.githubusercontent.com/21006/73097311-e083f080-3eb4-11ea-8a84-5357b373daa3.png)

**Comment by RightInTwo** [comment]
> ... maybe it should be called...
> 
> **Restricted File Downloader** - A person who can download a restricted published file.

That sound like you would like to rename the role - wouldn't it make sense to also rename the permission itself to "DownloadRestrictedFile"?
