### ISSUE TITLE
Persistent Identifiers for Dataverse

### ISSUE THREAD

**Issue by pengchengluo** [IQSS/dataverse#4390]
Hi, now dataverse system has the function to assign doi for dataset and datafile (in developing). I am wondering whether the dataverse can be assigned a doi ? Due to our data contributors have proposed this issues many times. They think that users maybe not just use one dataset but maybe all datasets under one dataverse.

**Comment by pdurbin** [comment]
@pengchengluo hi. This reminds me of the "File Download: Allow user to download all files from a dataverse at once" issue at #639

As you mentioned, we're working on DOIs for files at the moment (community discussion at https://groups.google.com/d/msg/dataverse-community/Jv8i31Wg_Fw/zDytm_VJBAAJ ). I'd like to note that in pull request #4350 all the database columns related to persistent identifiers are being moved from the `dataset` table to the `dvobject` table. The `dvobject` table contains three types and one of them is dataverses.

**Comment by pengchengluo** [comment]
That's wonderful!

**Comment by pdurbin** [comment]
@pengchengluo I'm glad you're happy, but to be clear, when that pull request gets merged, dataverses will not have persistent identifiers. I was merely trying to describe how that database schema is changing.
