### ISSUE TITLE
Front Glassfish with Apache and Using SSL

### ISSUE THREAD

**Issue by ghost** [IQSS/dataverse#4392]
Hi,
Recently added SSL using letsencrypt to our dataverse installation at UWI. We are front glassfish with apache and this created a problem. The https not be redirected into glassfish. 

In the VirutalHost _default_:443 settings you will need to add the JKMount rules such as JKMount /* worker1 to it. 

Restart apache and it should work. Anyone needs help with this particular setup and always ask me.

**Comment by pdurbin** [comment]
@lbigramUWI thanks for opening this issue. I'm a little confused. You're explaining a problem you faced and also offering a solution, right? Would you like to help us document this in the Installation Guide? Am I misunderstanding you? Thanks.

**Comment by donsizemore** [comment]
@pdurbin the inverse ProxyPassMatch and AJP ProxyPass directives are a bit buried (only on the Shibboleth page). They might be linked to or duplicated at http://guides.dataverse.org/en/latest/installation/config.html#id28 or better yet included as an optional-but-likely prerequisite on the prerequisites page?

**Comment by pdurbin** [comment]
@donsizemore oh, I absolutely agree. I could imagine this issue (or some other issue) being about how we should elevate the "how to front Glassfish with Apache" discussion out of the Shibboleth section and into the main config section. I spend a lot of time over at http://guides.dataverse.org/en/4.8.4/installation/config.html#network-ports trying to convince everyone that fronting Glassfish with Apache is a good idea but then I say, "If you are convinced you’d like to try fronting Glassfish with Apache, the Shibboleth section should be good resource for you." Instead, we should put the instructions right there.

**Comment by pameyer** [comment]
I don't remember having to use JKMount for https with apache in front of glassfish - is it possible this is related to letsencrypt?

**Comment by lbigramUWI** [comment]
@pdurbin It was a problem we were having but then found a solution.

@pameyer I am not sure if it specifically letsencrypt issue or a bit of information I am missing for using SSL when front glassfish with apache. But using the description I gave worked for me.

**Comment by pdurbin** [comment]
@lbigramUWI great, sorry for the extremely slow reply. Are you interested in making a pull request to add your tip to the Installation Guide? Or maybe you could write up an email to https://groups.google.com/forum/#!forum/dataverse-community about your fix? I'm trying to figure out when this issue can be closed. Thanks!

**Comment by djbrooke** [comment]
Hi @lbigramUWI, I'm going to close this out for now since there is a solution for the specific issue.

**Comment by pdurbin** [comment]
If anyone is interested in this topic, thanks to @donsizemore https://github.com/IQSS/dataverse-ansible recently gained support for setting up Apache with SSL in front of Glassfish. You can just drop your cert and keypair in the config and spin up a new installation. The config looks like this:

```
apache:
  ssl:
    enabled: true
    cert: 
    interm: 
    key: 
    pem:
      cert: 
      key: 
      interm: 
```

I just used it today. Works great.
