### ISSUE TITLE
support multiple storage locations

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#4396]
In the spirit of breaking things into smaller chunks; first step towards DLM integration would be to extend Dataverse to know about data files that are stored in multiple "storage locations"

related: https://github.com/IQSS/dataverse/issues/3403

**Comment by pameyer** [comment]
What does a user story for this look like?

As a member of the research community, I recognize that the files comprising datasets can and should exist in different storage locations, which may be accessible by different protocols internally (by the repository) and externally (by users).  I would like this information to be present in Dataverse, so that researchers can access (and compute on) the datafiles using the storage location and access protocol most efficient for their needs; and so that repository administrators and make use of external components to orchestrate this.

**Comment by matthew-a-dunlap** [comment]
Questions I have about this:
- What level of granularity do we see needed for saving to storage locations? Do we see users being able to choose different storage locations for different files upon saving? Or datasets will have a storage location attached to themselves to decide where the files will go?
- Currently, each dvobject has a storage identifier. If we move forward with storage locations, it seems we will likely end up with a table for the different locations. Those locations will likely include the storage type. If this is true, do we think we may end up removing storage identifier and instead roll that info into locations?

I realize these questions point to work that is not going to be done in this story, but I'm trying to understand the architecture needed.

**Comment by matthew-a-dunlap** [comment]
If we decide to remove storage identifier (at some point, maybe not this story) and do this through a more verbose storage location table, this is what I see as needed:
- a new row in dvobject for the storage location
- a new table for storing the storage locations. Including a url, type of location, name, etc.
- maybe a system variable to set the default storage location? Maybe this should be per dataverse? I need to learn more about use cases.
- Code to add the storage location to files as they are added to the system
- Code to retroactively add storage locations to existing files based upon their storage identifier (I'm a bit unsure about this).

**Comment by pameyer** [comment]
@matthew-a-dunlap Good questions; this does need to be clarified a little.

- For level of granularity; repository/installation level for storage sites; and dataset-level for what dvobjects are stored at which sites.
- Current thinking is that all data file depositions will go to an internal/primary storage site, so this won't be something a user has to select.

I may not be following all of the storage identifier points - my thinking is that the abstract data structure would be a sparse matrix with sites in one dimension and datasets in the other.  This would need another table for storing information about the sites themselves (storage type, transfer protocols, name, etc).

I'll check some of the earlier DLM docs / specs to see if there's anything helpful.

**Comment by matthew-a-dunlap** [comment]
I'm taking myself off this story as I think these prov fixes will take me today and tomorrow (hopefully not more). I'll pick this up after that if it is still open!

**Comment by matthew-a-dunlap** [comment]
We discussed this story a bit during our regular technical discussion meeting.
* We need two tables. One that contains all possible storage locations for the installation and one that joins locations to individual dv objects
* We need to keep track of the primary identifier. 
  *This definitely means that we need to know the location Dataverse will go to when being asked to generally serve a file. This is probably per datafile
   *We also need to know the storage location to save to when Dataverse saves a file through normal means. We did not discuss whether this is would be at a Dataset or Dataverse level.
* Open question of what to do with the current storage identifier. Do we keep it in place as primary, change it or get rid of it?

**Comment by pdurbin** [comment]
After our tech hours @pameyer and I sat and made a spreadsheet that has real world storage locations around the world for his installation of Dataverse: https://docs.google.com/spreadsheets/d/1YMquntQDD6Afbr_ua2G0YNmWa78mjPoxuTQazw5cOZY/edit?usp=sharing . We used most of the same names for columns as appear in 74ee4a0.

**Comment by pameyer** [comment]
real world, although the hostnames weren't checked for accuracy - some of those are placeholders (which shouldn't make a difference here).

**Comment by pdurbin** [comment]
Just a heads up that @pameyer and I have been talking and we're going to stop having "country" as a separate field. The country is relatively unimportant and not worth persisting in the database at this time. Concretely this means removing "country" (and the comma) from `file-data-access-fragment.xhtml` like this:

```
         <ui:repeat value="#{repositoryStorageAbstractionLayerPage.getRsyncSites(datasetVersion)}" var="site">
             <div class="col-sm-12">
                 <code><h:outputText value="#{site.rsyncDownloadcommand}"/></code>
-                <h:outputText class="text-muted" value=" (#{site.name}, #{site.country})"/>
+                <h:outputText class="text-muted" value=" (#{site.name})"/>
             </div>
         </ui:repeat>
```

I'll also remove the backend references to "country" in getRsyncSites and related code.

**Comment by djbrooke** [comment]
_John Lennon approves_

**Comment by pdurbin** [comment]
I made the change above in 5244f02 but I need more clarification on where we're going to continue. @pameyer and I Slacked a bit about it and I'm seeing a potential parallel with the "auth providers" table, how the installer sets you up with the builtin auth provider but you can enable other auth providers and even delete the builtin one if you don't want it. In a similar way, it sounds like the installer needs to populate a table having to do with storage sites or whatever such that a vanilla install knows where to put files and where files will be available from.

**Comment by scolapasta** [comment]
Looked over the code and discussed some with @pameyer. What is there now looks to serve as code restructuring that moves the storage locations to a new table and APIs to interact with that new table. 

The next steps will be to actually have more granular usage of the storage locations (for individual files) and APIs for the something like the DLM to call and tell Dataverse thatit has copied the files.

Discussing with @djbrooke we're fine with moving this along as is to be merged, and having the next "small batch" be the above as a new issue*.

(*) note, I would also be ok with continuing on in this issue for the next step

Moving to code review for any additional feedback from @pameyer .

**Comment by pdurbin** [comment]
@pameyer one column that appears in the spreadsheet above ( https://docs.google.com/spreadsheets/d/1YMquntQDD6Afbr_ua2G0YNmWa78mjPoxuTQazw5cOZY/edit?usp=sharing ) that isn't in the code is `primaryWriteLocation`, but I added a todo about how you'd like the rsync sites to be ordered, ideally "order by primary first, then whatever":

https://github.com/IQSS/dataverse/blob/5244f0243b37904bc996f573410dea871e752101/src/main/java/edu/harvard/iq/dataverse/repositorystorageabstractionlayer/RepositoryStorageAbstractionLayerServiceBean.java#L32-L33

As the code above indicates, they're ordered by id currently so you can just add your primary storage location/site first for now.

**Comment by scolapasta** [comment]
Can we just do order by o.primaryLocation desc? 
(this will order by null, true, false, but we won't have nulls, so really just true, then false)

**Comment by pdurbin** [comment]
@pameyer I attempted to implement all the changes we talked about (plus some clean up) in 47dde01. Please take a look at pull request #4585 and if you feel like it's ready for QA, I'd say you can go ahead and move it over. If there's anything else you need, please kick it back to me.

**Comment by pdurbin** [comment]
@pameyer I just made various improvements and fixes we talked about this morning. Can you please take another look? Thanks!

**Comment by pameyer** [comment]
@pdurbin Looks good to me (and as a bonus, less XHTML on errors).  Thanks!

**Comment by pdurbin** [comment]
@pameyer sure, I just merged the latest from "develop" in the pull request in e776b85. Thanks for moving this to QA.

@kcondon in terms of how to test, the changes to the guides are a good starting point. Please note that the `:ReplicationSites` database setting has gone away (it was added in #3998 and there are screenshots in that issue of rsync instructions). We are now using a proper database table called `storagesite` to store these entries and populating that table with our usual pattern of sending JSON to an API endpoint with curl. We've implemented some rules especially around the `primaryLocation` boolean, that there can only be one primary location. The storage sites are ordered by id in the UI. I'm happy to write more in the guides if you want me to.

**Comment by kcondon** [comment]
Was not able to complete testing due to: https://github.com/IQSS/dataverse/issues/4605
