### ISSUE TITLE
When setting harvesting schedule to weekly, settings don't persist

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#4398]
Scheduling weekly harvesting is working, but the scheduled settings don't persist when I set harvesting to weekly (they do persist when set to daily). I'm seeing this on Harvard Dataverse and Demo Dataverse, both on 4.8.4.

To reproduce: I set a harvesting client to harvest weekly, and save those settings, and when I edit that client again - to check or change the harvesting schedule - the scheduling settings seem to be reset ("none" is selected instead of the weekly schedule I chose before). This makes it seem as though I didn't schedule anything the first time, that weekly scheduling won't work, and makes it difficult to manage harvesting, especially as the number of harvesting clients increases.

Labeled this as a bug since the scheduling settings for weekly harvesting should at least persist like they do when for daily harvesting settings.

Going a little further, maybe the harvesting table can indicate someplace the schedule for each client, so installation admins don't have to go through all of the edit steps to check what the schedule is for each client.

**Comment by kcondon** [comment]
OK, settings persist in UI but found the weekly harvest is not kicking off while the daily does.
Stephen mentioned that the day of week was being store with the wrong array index, off by one and was fixed so this may have affected logic elsewhere.
