### ISSUE TITLE
API: As a dataverse administrator I want to destroy all datasets in a dataverse and delete the dataverse using an API call.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#4409]
As part of our ongoing curation efforts, we sometimes need to remove dataverses and their datasets that do not comply with repository policies, eg. they do not contain actual data. Having an api endpoint that does this would empower the curation staff and reduce burden on system admins.

**Comment by djbrooke** [comment]
From Backlog Grooming 1/31:

- Do we want to give this ability or is it too powerful? :) Consider some pretty heavy messaging and/or don't let folks run it on the root dataverse.
- We should handle cleaning up linking as part of this
- There could be multiple API endpoints for this

**Comment by donsizemore** [comment]
I'm actively using this endpoint so you may likely close this issue, but I do notice that the destroy dataset endpoint leaves behind the directory on the filesystem, and all export_* files:

```
[dls@4.20_test FK2]$ ls -al 3XJBN9/
-rw-r--r--  1 glassfish glassfish  1891 Apr 24 13:37 export_Datacite.cached
-rw-r--r--  1 glassfish glassfish  8935 Apr 24 13:37 export_dataverse_json.cached
-rw-r--r--  1 glassfish glassfish  2151 Apr 24 13:37 export_dcterms.cached
-rw-r--r--  1 glassfish glassfish 11662 Apr 24 13:37 export_ddi.cached
-rw-r--r--  1 glassfish glassfish 19071 Apr 24 13:37 export_html.cached
-rw-r--r--  1 glassfish glassfish  3062 Apr 24 13:37 export_oai_datacite.cached
-rw-r--r--  1 glassfish glassfish  1075 Apr 24 13:37 export_oai_dc.cached
-rw-r--r--  1 glassfish glassfish  4610 Apr 24 13:37 export_oai_ddi.cached
-rw-r--r--  1 glassfish glassfish  7842 Apr 24 13:37 export_OAI_ORE.cached
-rw-r--r--  1 glassfish glassfish  3145 Apr 24 13:37 export_schema.org.cached
```

**Comment by jggautier** [comment]
Yeah, it uses the Search API and "get contents" endpoints to find the PIDs of all datasets within a collection, then uses the destroy dataset endpoint on each dataset.

**Comment by pdurbin** [comment]
For now let's use Julian's thing.
