### ISSUE TITLE
Dataset Metadata: "Replication Data for:" title prefix vs required field validation

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#4412]
When adding a new dataset, you can click the Add "Replication Data for" to Title button under the dataset title field in the Citation Metadata block, which prepends the title field with the text "Replication Data for: ", which thus fulfills the required field validation, so a data depositer is not prompted to add a dataset title.

![screen shot 2018-01-11 at 3 45 29 pm](https://user-images.githubusercontent.com/687227/34846694-fd551580-f6e6-11e7-9c8d-7fa953e83819.png)

This was noticed on [production (4.8.4)](https://dataverse.harvard.edu/dataverse/harvard?q=replication+data+for&fq0=metadataSource%3A%22Harvard+Dataverse%22&types=datasets&sort=score&order=desc) and confirmed on [dvn-build (4.8.4)](https://dvn-build.hmdc.harvard.edu/dataset.xhtml?persistentId=doi%3A10.5072%2FFK2%2FFYNZ8V&version=DRAFT).

@sbarbosadataverse considered this a bug, so I created a new issue it for it. There was a discussion about this feature, as it related to these existing GitHub issues:

- Feature: add "Data related to" to the options under the "title" field #3678
- Feature: for anything tagged as "replication data for" make "related publication field" required #3679
- Dataset titles composed of other metadata #4072

We should try to determine which feature improvements we want to prioritize, as well as any and all UX improvements, and consolidate as many of these issues together before design + development pick them up.

**Comment by mheppler** [comment]
Found another instance in Harvard Dataverse.

![Screen Shot 2020-03-02 at 4 52 03 PM](https://user-images.githubusercontent.com/687227/75721394-4b8bc880-5ca6-11ea-9d74-a526657aeb53.png)

**Comment by jggautier** [comment]
The admin of a collection in the Harvard repository recently asked if this button could be removed when people deposit datasets in that collection (and in the collections within in), since he has no plans to ask depositors to include "Replication Data for:" in their dataset titles.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
