### ISSUE TITLE
 URL bug in dataset file list

### ISSUE THREAD

**Issue by pengchengluo** [IQSS/dataverse#4415]
Hi, I found the file url don't work since the url version parameter is given incorrectly.

For example, I have a dataset which has four version. I open the version 3 ( i.e. https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/27695&version=3.0 ) and I want to open the “Three Kingdom 11.txt” file ( i.e. https://dataverse.harvard.edu/file.xhtml?fileId=3102072&version=RELEASED&version=.0 ) which have been delete in version 4.  However, I will get the "404-Page Not Found" error page. 

I think this error is due to the wrong setting of version parameter, i.e. version=RELEASED&version=.0 .
It seems work correctly if I change the line 223 and line 224 in filesFragment.xhtml into following:

<f:param name="version" value="#{fileMetadata.datasetVersion.versionState}"  disable="#{(fileMetadata.datasetVersion.released or fileMetadata.datasetVersion.deaccessioned)}" />
<f:param name="version" disable="#{not (fileMetadata.datasetVersion.released or fileMetadata.datasetVersion.deaccessioned)}" value="#{fileMetadata.datasetVersion.versionNumber}.#{fileMetadata.datasetVersion.minorVersionNumber}" />

**Comment by pdurbin** [comment]
@pengchengluo interesting. Thanks for the bug report. This reminds me a lot of #4308 which we think is fixed in ee521cf as part of pull request #4350. I can definitely reproduce the 404 using that "Three Kingdom 11.txt" example you mentioned.

**Comment by pengchengluo** [comment]
@pdurbin Thanks. I test it and it is fixed by pull request #4350.

**Comment by pdurbin** [comment]
@pengchengluo thanks for testing!
