### ISSUE TITLE
Command Engine: Move indexing and other actions into "onSuccess" method

### ISSUE THREAD

**Issue by ferrys** [IQSS/dataverse#4425]
As a developer, when calling a command such as CreateDatasetCommand, I want to be able to do things like index the dataset **after** the dataset as been successfully created and the EJB transaction has completed, so that I will never have a scenario where my dataset was indexed but it does not exist in the database. 

@scolapasta and I started a little bit of work related to this issue but determined it needed a bigger discussion surrounding its implementation. The current work on branch `4425-on-success` is not what we think the correct solution will be, but just initial work.

**Comment by scolapasta** [comment]
Two challenges we'll need to solve:
• how to handle nested commands and calling nested onSuccess calls 
• if operations in onSuccess fail, how to automate them trying again and/or inform installation admins so it can rerun manually
