### ISSUE TITLE
As a researcher, I want the producer/distributor logo images I add to my dataset to always show

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#4428]
Dataset depositors who want to display distributor or producer logos on their dataset pages can include URLs of those images in the Producer Logo URL field and the Distributor Logo URL field.

<kbd>![screen shot 2018-01-22 at 1 59 36 pm](https://user-images.githubusercontent.com/18374574/35238949-12befe74-ff7d-11e7-8eb7-012c77e6a401.png)</kbd>

<kbd>![screen shot 2018-01-22 at 1 59 46 pm](https://user-images.githubusercontent.com/18374574/35238963-1c68a448-ff7d-11e7-8cd0-79528629a6d6.png)</kbd>

Dataverse displays the image in the dataset page's metadata tab:

![screen shot 2018-01-22 at 2 13 52 pm](https://user-images.githubusercontent.com/18374574/35240451-8022d59a-ff81-11e7-835b-321bf2b48fa8.png)

But storing logo URLs can be problematic when the URL breaks:
- The URL isn't displayed and needs to be updated.

- Logo URLs that are http instead of https also trigger browser security warnings (https://github.com/IQSS/dataverse/issues/2293).

**Local datasets on Harvard Dataverse**
The Harvard Dataverse installation uses this the most. It has about 5900 non-harvested datasets with one or more logo URLs, and about 8300 logo URLs. Of the 3388 URLs I was able to check, about 43 percent are broken or redirect to something other than an image. Of the 8300 URLs, 523 are unique, and about half are broken or redirect. 

@sbarbosadataverse @dliburd, and @myrder2 are working on updating broken URLs now for some dataverses, e.g. Murray.

**Harvested datasets on Harvard Dataverse**
There are about 9552 unique harvested datasets in Harvested Dataverse with logo URLs. They're all using one or more of **the same four logo URLs**. Most (about 9000) are from the [ICPSR Harvested Dataverse](https://dataverse.harvard.edu/dataverse/icpsr).

**Other installations**
It doesn't look like many of the other known Dataverse installations have published datasets with logo URLs. On Scholars Portal's installation, 105 of its roughly 900 published datasets have logo URLs. For UNC, it's 24 of 24,700+ published datasets.

One recommendation is to let depositors upload an image file instead. The logo URL fields would be replaced with an upload option, and the image would be stored on the Dataverse installation's servers.

**Comment by pdurbin** [comment]
Related: #2293

**Comment by mheppler** [comment]
Copying a comment from #2293 here now that I have closed that.

>The problem is that the `distributorLogoURL` points at a plain HTTP URL rather than HTTPS: http://murray.harvard.edu/files/murray/banner146x48.png
>
![record_of_american_democracy _all_geographic_boundary_files_-_murray_research_archive_dataverse_-_2015-06-29_13 32 17](https://cloud.githubusercontent.com/assets/21006/8414078/78f83816-1e63-11e5-9441-1c060225c40e.png)
>
>At the very least, in the guides we could encourage the use of HTTPS URLs for `distributorLogoURL`.

_Originally posted by @pdurbin in https://github.com/IQSS/dataverse/issues/2293#issuecomment-116770009_

**Comment by jggautier** [comment]
The issue described at https://github.com/IQSS/dataverse/issues/10544 is relevant here since it describes a solution that prevents broken URLs from breaking images displayed on dataset pages.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
