### ISSUE TITLE
Revise Explore Tools documentation to reflect modularity

### ISSUE THREAD

**Issue by dlmurphy** [IQSS/dataverse#4429]
With #3657 we've moved toward treating external explore tools as modular. This new way of looking at external tools in Dataverse requires we rethink the way we talk about them in our documentation. Let's review all mentions of TwoRavens, GeoConnect/Worldmap, and other explore tools throughout all guides to make sure that it's clear that these tools are considered modular, and that any number of other modular explore tools may be present in any given Dataverse installation.

**Comment by dlmurphy** [comment]
Note that Geoconnect is not considered modular in the same way as TwoRavens. At this point, Geoconnect is still a core feature of Dataverse that we maintain. Docs should reflect this.

**Comment by pdurbin** [comment]
I just reviewed the entire API Guide as part of pull request #6107 and there's nothing to fix there for this issue so I removed the GitHub Issue label for that guide.

**Comment by mheppler** [comment]
Going to close this issue, as the review of the guides suggested will be completed as part of issue #6919 for preview tools, and anything not resolved there, can be added to issue #5597 for Geoconnect/WorldMap.
