### ISSUE TITLE
As a user with an institutional account, I want to transition to another account when I relocate. 

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#4430]
A user works for institution A and creates an institutional Dataverse account while there. They later move to institution B and want to keep their account and what privileges are still relevant. 

Currently this requires a Support ticket and the intervention of a super user to first convert to a local account with the new email address, then the user logs in a converts their account following the workflow prompts in the UI.

See http://guides.dataverse.org/en/4.8.4/installation/shibboleth.html#converting-accounts
for the process.

There are 3 issues to consider:
1. Provide a simple push button transfer workflow to both the end user and to a super user.
2. Provide messaging to explain not to log in using their new institutional account but instead transfer the existing one since that creates a second account.
3. Provide a way to merge accounts in the case that a second account had been created and roles were assigned, content added.

Currently if the new institutional account already exists, their account needs to first be deleted, after all roles are removed, then the original account needs to be converted to local, then the user logs in and converts it to the new shib account.

**Comment by pdurbin** [comment]
Nice discussion on this issue during sprint planning yesterday. One thing I meant to say is that Shibboleth ("institutional account) users will see (for example) "Leaving your institution? Please contact Harvard Dataverse Support for assistance." It looks like this:

![screen shot 2018-10-04 at 12 53 51 pm](https://user-images.githubusercontent.com/21006/46490003-d1b38f00-c7d4-11e8-8f1a-2a2d7e9fee66.png)

While this is better than nothing and at least sets expectations that they're sort of locked in to their current login method, perhaps we could replace this with a "Convert to Username/Email Account" button and workflow.

#3704 is related in the sense that it's easy to get confused about which account type you have.

**Comment by kcondon** [comment]
@pdurbin 
I know the incremental approach above would require little code and is a good first step.

To help with the next step, I was thinking more about direct conversion I am not sure where the complexity lies -there are 2 tables, the account types are exactly the same, barring the default info, which is always overwritten when logging in via shib, I think the email and eppn are the only unique bits and those could be adjusted prior to logging in (eppn would be blank because we don't know it yet) and  perms indexing would need to happen for group membership changes. Plus, we already have the concept of moving from one account (builtin) to a new shib account so the idea of adjusting an account to be a shib account is already there, except the starting point would be another shib account. So, before executing the log in to the new account, switch email, clear eppn, and treat it as an already approved builtin conversion?

Anyway, would love to hear at a high level the potential steps and how it could work.

**Comment by djbrooke** [comment]
I'm going to close this with the desired solution being to create an account at the new institution, and then, using the new merge functionality (#5514), to merge that old account into the new.

**Comment by pdurbin** [comment]
@djbrooke I still like my "Convert to Username/Email Account" button idea above because it's self-service. No need to email support. But with 881 open issues I certainly appreciate a little housekeeping here in the issue tracker. 😄
