### ISSUE TITLE
On restricted files permission page, granting or rejecting access doesn't remove requester from "Request" list

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#4435]
The account information of people who request access to restricted files is listed in the "Request" table on the Restricted Files Permissions page (Dataset page > Edit > Permissions > File). Anyone with appropriate permissions can click Accept or Reject for each person's request.

<kbd>![restricted files permission bug 1](https://user-images.githubusercontent.com/18374574/35396059-ef539eba-01b9-11e8-9fe4-09b94340d4d3.png)</kbd>

@sbarbosadataverse reported that on Harvard Dataverse, 4.8.4, when clicking Grant or Reject, the person's account information remains on the Request table. I reproduced this with a dataset on Demo Dataverse:

<kbd>![restricted files permission bug 2](https://user-images.githubusercontent.com/18374574/35396922-0dc98e2a-01bc-11e8-9ee3-1f89febeeb2a.png)</kbd>

When testing in Demo Dataverse, refreshing the page seems to correct the problem: The person whose request I grant or reject is removed from the Request table. Refreshing the page works when I tested this with [my dataset in Harvard Dataverse](https://doi.org/10.7910/DVN/2ZQQJI), too.

Clicking Grant or Reject and seeing that the requester's info remains in the "Request" table gives the impression that the action didn't work, especially when the table listing users who've been granted access is long and searching through the list is difficult.

**Comment by sbarbosadataverse** [comment]
@TaniaSchlatter can we add this to things to fix more immediately ?

**Comment by TaniaSchlatter** [comment]
From @jggautier's description, it sounds like we need to confirm that refreshing the page addresses the problem, and edit the code to forcing a page refresh on Grant and Reject. I think this is ready for review to bring into a sprint or spike.

**Comment by jggautier** [comment]
I just tested this on Demo Dataverse, which is running Daverse v6.2, and when I granted and rejected access to restricted files, the request was immediately removed from the table that lists the requests. I didn't need to refresh the page. I tested this on the latest versions of Chrome, Firefox and Safari.

I'm going to close this GitHub issue.
