### ISSUE TITLE
Spike: Files DataTable, Selection, Paginator vs Scroll

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#4437]
Build datatable prototypes to explore UX and technical limitations of selection, paginator, scroll, and counter features of the dataset pg and we display all the files.

This is related to issue Dataset - File UI Improvements #3404. Answers we discover in this spike will be used to inform design decisions in a new dataset pg layout or one-off improvements that could be shipped before 5.0.

**Comment by mheppler** [comment]
If there is anything we learn about performance of this files table, we should add it to this issue, Performance degradation investigation #3631.

**Comment by matthew-a-dunlap** [comment]
I'm placing some DataTable related issues here as this is the current push forward:
- On dataset after each checkbox you have to wait 3 seconds to select another. If you do not, boxes will be unselected.
   - Gutsavo notes "we really should try to find a solution that doesn't necessitate going to the server when you check the box"
- On editDataFile checkboxes are unchecking correctly in some cases. I noticed this selecting and unselecting boxes for two files.

**Comment by mheppler** [comment]
Closing with approval from @scolapasta @TaniaSchlatter and @djbrooke.

Opened new issue **Dataset Files DataTable - Paginator, Selection, Download, Counter #4656**.
