### ISSUE TITLE
Dataverse API retreive informations of dataverse with alias

### ISSUE THREAD

**Issue by didaRo** [IQSS/dataverse#4440]
Hi
when I use API of **_Dataverse 4.5.1_** to GET informations of my dataverse,
`GET http://$SERVER/api/dataverse/$alias`
the dataverse I have "**theme**" not null

I have this error : 
**java.lang.ClassCastException: edu.harvard.iq.dataverse.DataverseTheme cannot be cast to edu.harvard.iq.dataverse.DataverseFacet**

But when I try this command, It works
`GET http://$SERVER/api/dataverse/$alias/metadatablocks`

Regards 
Fairouz

**Comment by pameyer** [comment]
@didaRo - do you see the same behavior when using `dataverses` (instead of `dataverse`)?

**Comment by didaRo** [comment]
sorry 
the correct command are : 
not work with a dataverse $alias with theme `GET http://$SERVER/api/dataverses/$alias`
work with the same dataverse $alias `GET http://$SERVER/api/dataverses/$alias/metadatablocks`

regards

**Comment by pameyer** [comment]
@didaRo I can't reproduce this with more recent versions (4.8.4 or 4.8.5).  Someone else may have a better suggestion for you, but it looks like upgrading should fix this problem.

**Comment by pdurbin** [comment]
@didaRo have you upgraded to a more recent version (4.9 is out) to see if the problem goes away?

**Comment by pdurbin** [comment]
@didaRo hi, just checking in again. Is this still an issue for you? Thanks.
