### ISSUE TITLE
Dataset Page: Edit metdata dialog fails to load if control characters exist in dataset description

### ISSUE THREAD

**Issue by andrewSC** [IQSS/dataverse#4442]
Hi folks,

As we were discussing in the [IRC chat](http://irclog.iq.harvard.edu/dataverse/2018-01-29#i_62627), I came across an interesting dataset where the user wasn't able to edit the metadata. When they clicked the `Add + Edit Metadata` they would get the following error in their web console.
![](https://cl.ly/1E0e36371R1u/Screen%20Shot%202018-01-29%20at%2012.20.29%20PM.png)

Digging a bit further I found that there were some ASCII control characters within the Description, stored in the DB. Here's some text with the control characters I found in my problematic description, embedded:
```
Call me Ishmael.  Some years ago--never mind how long precisely --having little or no money in my
purse, and nothing particular to interest me on shore, I thought I would sail about a little and see the
watery part of the world. It/is a way I have of driving off the spleen, and regulating the cir\x10u\x18la\x10tion. 
Whenever I find myself growing grim about the mouth; whenever it is a damp, drizzly November in my
soul; whenever I find myself involuntarily pausing before coffin warehouses, and bringing up the rear of
every funeral I meet; and \X0Cespecially whenever my hypos get such an upper hand of me, that it
requires a strong moral principle to prevent me from deliberately stepping into the street, and
methodically knocking people's hats off--then, I account it high time to get to sea as soon as I can.
```

This dataset was most likely created on a much older version of Dataverse (I'm thinking 4.2.x or 4.3.x). 
The version I experienced this on was DV 4.8.5

If there's any other information I can provide, definitely let me know :)

**Comment by pdurbin** [comment]
@andrewSC thanks for reporting this issue. Did you figure out a solution? Did you end up removing those control characters?

**Comment by andrewSC** [comment]
I just ended up manually removing the control characters. Haven't had any issues since!!

**Comment by pdurbin** [comment]
@andrewSC great. Do you think it's possible to replicate this bug on newly created datasets? Since you're personally all set, do you think we should consider closing this issue? With 823 open issues I try to keep an eye on what's open and still relevant.

**Comment by mheppler** [comment]
@pdurbin @andrewSC stumbled across this issue, while working with special characters in the metadata. I was able to use the description text provided about, create a dataset, publish, and edit, without a problem or any console errors.

OK with closing this issue if y'all are. @djbrooke 👀

![Screen Shot 2019-08-12 at 2 02 22 PM](https://user-images.githubusercontent.com/687227/62886912-1f105f00-bd0a-11e9-8aba-285d42fe5760.png)

**Comment by pdurbin** [comment]
See also:

- dataset.xhtml and user input of special characters #8018
