### ISSUE TITLE
Update com.github.scribejava version

### ISSUE THREAD

**Issue by xibriz** [IQSS/dataverse#4449]
I'm proposing to upgrade the com.github.scribejava version in pom.xml (line ~422) to the latest version `5.2.0-java7again` so that the latest OAuth API's are available.

**Comment by pdurbin** [comment]
@xibriz hi. It looks like right now we are running ScribeJava 3.1.0: https://github.com/IQSS/dataverse/blob/v4.8.5/pom.xml#L416

You are welcome to go ahead and make a pull request. I looked at https://github.com/scribejava/scribejava but I can't tell what changed from 3.x to 4.x or 4.x to 5.x. Have the APIs changed much? Is that why the major version has been bumped a couple times?

**Comment by xibriz** [comment]
I don't really know since he (scribejava owner) has stopped publishing changelogs. But I guess new API's are a big part of the new versions.

When I changed the version in my fork I see that Netbeans automaticly added a old version of the scibejava-core (3.1.0). Don't know why this happend, but I guess Netbeans knows best since I'm not a Java Developer :)

Anyway, I tested it with Dataporten off course and nothing seems to be broke.

https://github.com/IQSS/dataverse/compare/develop...uit-no:4334-dataporten-provider

**Comment by pdurbin** [comment]
@xibriz it was nice meeting you at the Dataverse Community Meeting last month! We spoke to @djbrooke about this a bit. I understand that you've already done all the work to get Norway's national auth service incorporated into the Java library we use in Dataverse. It's great to hear that nothing broke when you tested it.

**Comment by xibriz** [comment]
It was nice meeting you too @pdurbin :) Yes I have made the changes in my fork over at https://github.com/uit-no/dataverse/tree/4334-dataporten-provider

We are not running this fork in production, but I have been keeping it up to date when new versions of Dataverse has been released and it seems to be working just fine.

I will be starting the testing of Dataverse on Kubernetes hosted by Uninet when I get back to work after summer vacation. Maybe we will just run the fork then to make sure it runs without problems :)

**Comment by pdurbin** [comment]
@xibriz interesting. Thanks. You might be interested the "Docker for production" issue at #4665 because Kubernetes is being used.

**Comment by poikilotherm** [comment]
This has been done with the merge of #5997 for #5991.
