### ISSUE TITLE
Delinking of linked datasets

### ISSUE THREAD

**Issue by gohsunee** [IQSS/dataverse#4454]
Is the Dataverse team currently working towards allowing delinking of linked datasets? If yes, roughly when will we be able to see it? If no, what are the considerations?

**Comment by djbrooke** [comment]
Hi @gohsunee - this isn't something on our radar now, but the ability to unlink datasets would be included if we decided to make linking a non-super user feature in the future. I'm going to close this one as a duplicate of #1364

**Comment by TaniaSchlatter** [comment]
Reopening this issue, as the ability to unlink is related to #5615 and #5874.

**Comment by pdurbin** [comment]
@gohsunee the ability to unlink or delink datasets was added in this PR in 4.9:

- #4543

Here's the current documentation: https://guides.dataverse.org/en/5.12/admin/dataverses-datasets.html#unlink-a-dataset

Are you all set? If so, please feel free to close this issue. Thanks!

**Comment by gohsunee** [comment]
Thanks for the follow-up. I'll close this issue. I'll defer to the new team who is managing our university dataverse.
