### ISSUE TITLE
Allow data depositors to create metadata record derivatives from existing metadata records

### ISSUE THREAD

**Issue by gohsunee** [IQSS/dataverse#4456]
Similar to the idea of being able to 'clone' metadata records, any chance of making it easier for data depositors to create metadata record derivatives from existing metadata records?

**Comment by pdurbin** [comment]
I think this is an interesting idea, and it reminds me of how I asked, "Do we have the concept of *remixing* a dataset? Can you *fork* a dataset?" over at https://groups.google.com/d/msg/dataverse-community/0WF2IA-43XI/JJNhz8P0AAAJ

**Comment by jggautier** [comment]
Would the derivative metadata record would also reference the first record?

Right now, a depositor could do this by creating and using a metadata template and then filling in the Related Dataset field with the original record information, like its persistent ID. Would this work? What wouldn't work about it?

**Comment by pdurbin** [comment]
@gohsunee our standard answer is to set up a dataset template: https://guides.dataverse.org/en/5.12/user/dataverse-management.html#dataset-templates

Would that work for you? Have you tried using dataset templates? Are you still interested in your original idea?

**Comment by gohsunee** [comment]
Thanks for the follow-up. I'll close this issue. I'll defer to the new team who is managing our university dataverse.
