### ISSUE TITLE
Provide metadata templates for chemistry and physics

### ISSUE THREAD

**Issue by gohsunee** [IQSS/dataverse#4457]
The physicists and chemists of our community have found that they couldn't quite optimise the use of metadata. Hence, I'd like to request the Dataverse team to consider including metadata templates for chemistry and physics where possible later in future iterations. Here's an example for reference: some are using Cambridge Crystallographic Data Centre (CCDC).

**Comment by djbrooke** [comment]
@jggautier I'd like to get your thoughts on this because it's a metadata question and @pameyer I'd like to get your thoughts because I see the word "Crystallographic" and you're our local crystallographer. Thanks both!

**Comment by pameyer** [comment]
@gohsunee It looks like you were trying to link to something - do you have a URL?  And are you thinking Core CIF?

**Comment by pdurbin** [comment]
@gohsunee hi, I'm just wondering if you saw the question by @pameyer above.

**Comment by gohsunee** [comment]
Thanks @pdurbin for the alert and @pameyer for your question. We recently experimented with customised metadata template (see https://doi.org/10.21979/N9/VTVWFJ metadata - 'Daoist metadata'). We could apply the same approach to provide CCDC metadata fields such as 'Identifier' eg. CCDC number, CSD number, CSD refcode, ICSD number and 'Compound name' eg. 'sulfadiazine' ).

**Comment by pdurbin** [comment]
@gohsunee yes! I remember seeing your "Daoist" custom metadata block. It's great that you've figured out how to create them. I think the question @pameyer was asking is if there is a URL to the metadata standard you're talking about? I just took a quick look at https://www.ccdc.cam.ac.uk and happened to see a tweet at https://twitter.com/ccdc_cambridge/status/1008699962094424069 to find my way to https://www.iucr.org/resources/cif/dictionaries/cif_core . Is that "Core CIF dictionary" the metadata standard you want to use? Or some other one? Thanks!

**Comment by gohsunee** [comment]
Thanks @pdurbin and @pameyer! yes, it's indeed the core cif at https://www.iucr.org/resources/cif/dictionaries/cif_core ! Any chances of it being included as one of the ready-to-use Dataverse templates?

**Comment by pdurbin** [comment]
@gohsunee are you interested in making a pull request? Someone has to create the tsv file like the ones at https://github.com/IQSS/dataverse/tree/v4.9.1/scripts/api/data/metadatablocks

**Comment by pdurbin** [comment]
@gohsunee are you still interested in this? It sounds you had a good start on metadata blocks for both chemistry and physics.

**Comment by gohsunee** [comment]
Thanks for the follow-up. I'll close this issue. I'll defer to the new team who is managing our university dataverse.
