### ISSUE TITLE
Page Template - Improve page markup to display content with system connection issues

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#4458]
When the system is slowed or frozen, the dataverse pg will display popup contents in the page layout, due to not being properly hidden by CSS.

Investigate markup improvement to get the popups out of the way of the page content, so that when these system issues arise, the page breaks properly.

<img width="1622" alt="screen_shot_2018-02-05_at_1 21 56_pm" src="https://user-images.githubusercontent.com/687227/35822506-82fffe60-0a7a-11e8-981f-e455526e59dd.png">

**Comment by pameyer** [comment]
@mheppler - I think #2647 might also help with this (assuming the missing CSS properties are coming from external CSS).
