### ISSUE TITLE
Bulk data download original file format

### ISSUE THREAD

**Issue by nprasai** [IQSS/dataverse#4464]
Currently users have to go to individual data files in order to download data in the original file format or even to other different format available. But this would be tedious process to do when a data study contains more than 100 data files. As of now the bulk download will only download data in tabular format.

**Comment by pdurbin** [comment]
@nprasai thanks for the feedback. #4000 is related. At a lower level I think what you're saying is that the "Multiple File (“bundle”) download" API described at http://guides.dataverse.org/en/4.8.5/api/dataaccess.html#multiple-file-bundle-download only includes tab delimited version of the original file. Under "Basic File Access" which is documented at http://guides.dataverse.org/en/4.8.5/api/dataaccess.html#basic-file-access you can pass `format=original` as a query parameter, but this only downloads one file a a time so you'd have to hit the API 100 times for your 100 files. Anyway, it might be a workaround for you to use the API directly like this.

**Comment by nprasai** [comment]
That api option is useful for admin. However, I receive email query about bulk download in original file format form our dataset users. Is it possible to have an option for bulk download in original file format somewhere at the top.

Best, Nilam

**Comment by pdurbin** [comment]
We discussed #4000 this week and now I'm more convinced that this is the same issue. @nprasai can you please take a look and close this issue if you agree it's the same? Thanks!
