### ISSUE TITLE
Swift storage: Support for Keystone v3 authentication

### ISSUE THREAD

**Issue by ferrys** [IQSS/dataverse#4466]
Currently, the Dataverse supports two options for authentication in a Swift enabled dataverse: Basic and Keystone v2.0. Since Keystone v2.0 is/will be [deprecated](https://docs.openstack.org/keystone/pike/contributor/http-api.html), we should enable support of [Keystone v3](https://developer.openstack.org/api-ref/identity/v3/). 

This feature is supported in [JOSS version 0.10.0](http://joss.javaswift.org/release-notes.html).

**Comment by pdurbin** [comment]
In standup this morning I mentioned that I already approved pull request #4550 but I didn't drag it to QA in case anyone else wanted to take a look. Everyone seemed fine with it being in QA so we moved it.

Thank you @ferrys for going ahead and fixing up logging in 9859bf8 . The code is looking even better.
