### ISSUE TITLE
Dataset Terms - Empty Terms of Use

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#4471]
Noticed on [production](https://dataverse.harvard.edu/dataset.xhtml?persistentId=hdl:1902.1/ZXUXB) and reproducible on [dataverse-internal](https://dataverse-internal.iq.harvard.edu/dataset.xhtml?persistentId=doi%3A10.5072%2FFK2%2FR4O151&version=DRAFT).

When you edit the terms for a dataset, and select "No, do not apply CC0" for the Waiver field under Terms of Use, then enter no text into the newly displayed "Terms of Use" field textarea, and click Save Changes. This will result in the Terms of Use label displayed in the Terms tab, but it is empty.

![screen shot 2018-02-22 at 3 45 36 pm](https://user-images.githubusercontent.com/687227/36563231-79bedac2-17e7-11e8-88b5-3c6ec39512a2.png)

**Comment by pdurbin** [comment]
Should be fixed now.
