### ISSUE TITLE
Dataset page: Page fails to load when it cannot understand an image file to generate thumbnail

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#4473]
See RT 256006 for details but the dataset page failed to load when it tried to generate a thumbnail for a particular .tiff file but could not understand the format.

**Comment by landreev** [comment]
Yep, happens in the ImageIO.read(...) line in ImageThumbConverter.java:
```
try {
            logger.fine("attempting to read the image file with ImageIO.read(InputStream), " + storageIO.getDataFile().getStorageIdentifier());
            fullSizeImage = ImageIO.read(inputStream);
        } catch (IOException ioex) {
            logger.warning("Caught exception attempting to read the image file with ImageIO.read(InputStream)");
            return false;
        }
```
I'm catching IOException there - but it looks like that weirdly-formatted TIFF is resulting in an IllegalArgumentException... 
So yeah, annoying - but an easy fix.

**Comment by pdurbin** [comment]
@landreev thanks for posting the code. Sounds like a "1" to me. (The "size" in https://waffle.io/IQSS/dataverse for anyone who has no idea what I'm talking about.)

**Comment by landreev** [comment]
this was de-facto prioritized, since it was causing problems with some datasets in production. a PR is coming (it is about 1 yes).

**Comment by sekmiller** [comment]
Ready for QA
