### ISSUE TITLE
Design API endpoints for metrics

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#4478]
We want to add API endpoint/s for the kinds of metrics we're currently getting in Miniverse).

Step 0 is to design what the structure of these endpoint/s are. As an example, is it just one API endpoint that gets all metrics, or individual endpoints for each (or both). 

This just requires a meeting to discuss and decide, then we can make individual issues for each endpoint we decide upon.

**Comment by djbrooke** [comment]
Meeting notes:

https://docs.google.com/document/d/1BlFUaZvCUkfqjx6Ahz66odTysRPyAAx7rfcY0X5Ny_w/edit

I'll create some issues as discussed and link from/to here.

**Comment by djbrooke** [comment]
Created #4527
