### ISSUE TITLE
Speed up data transfer of the backup-to-secondary-storage script

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#4479]
We implemented the script in Python; and used paramiko, Python ssh/sftp client to transfer file. 
We never noticed it while testing it on our local subnets, but the Python sftp implementation appears to be very slow. We noticed this when we ran the script between the old production and the RC vm, with the network speed being very slow initially. 

It's still adequate for incremental backups; but not for the initial, full backup, of the amount of data we have here. 

One may argue that when you want to back up massive amounts of data, you should not be doing it over a slow network link. Still, there are straightforward ways to increase the performance of the script. Scrapping using the Python ssh client, and instead running scp as an external command would speed it up about 5X.

And then there is an option of using something more efficient for the original full dump - rather than relying on the script do back it up one file at a time.

**Comment by djbrooke** [comment]
@landreev - is this still something that's needed, or did we pursue a hardware/configuration solution?

**Comment by landreev** [comment]
Yes, I sped it up 5-7X, by using the approach above - switching to calling scp, instead of relying on the python sftp client. 
I'm using this hacked version of the backup script for the full backup of the existing, pre-migration data (that's almost done).

The code would need to be cleaned up a little before it can be checked in.  And at this point I'm not sure I want to check it in... The script works just fine as is for regular incremental runs. And for the full backup it only became a problem because the network connection was found to be freakishly slow between that old server and the RC VM at Holyoke... 
Normally it would not a be a real-life use case - meaning (normal) people serving terabytes of data are not likely to try and backup it all up over a modem-like link...

**Comment by djbrooke** [comment]
I'll close this for now, we can reopen if we decide to work on it further or check in the existing code.
