### ISSUE TITLE
As a sysadmin, I'd like to know how much usage (hits, etc.) my Dataverse installation is getting

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#4481]
This morning at an extra long standup @scolapasta @landreev @kcondon @mheppler and I were talking about the recent move to AWS and S3 undertaken by Harvard Dataverse and how we're interested in analyzing server logs to see how much usage (hits, bandwidth, etc.) this installation is getting day by day and hour by hour. As I understand it, we're trying to make sure we understand what baseline usage is so that when usage spikes we are aware that it's a spike. Spikes might be correlated with system instability, for example.

@landreev seemed to favor parsing the Glassfish access logs and I was thinking that it might be easier to find a tool that already parses Apache access logs. Ideally we would probably have a view per Glassfish server as well as an aggregate view of all Glassfish servers together. A view per server would probably be easier as a first iteration.

One problem with attempting to parse Apache access logs is that they do not contain the real IP address of the host that is making the HTTP request. Instead you see an internal IP address starting with `10.137`. The Glassfish access logs, on the other hand, show the real IP at the end of the line. (@landreev mentioned something about an `X-Forwarded-For` header but I didn't quite catch it. Sorry.)

I'd like to share an example of a tool that parse Apache access logs called `awstats`. We used in at IQSS back in 2006 or so and here are some instructions I sent around in 2015 for setting it up:

- `yum install awstats`
-  Tweak /etc/awstats/awstats.standalone.conf and /etc/awstats/awstats.localhost.localdomain.conf changing `LogFile` to `/var/log/httpd/ssl_access_log` and `LogFormat` to `4`.
- `/usr/share/awstats/tools/awstats_updateall.pl`
- Look at http://localhost:8888/awstats/awstats.pl?config=localhost.localdomain

What you see is the screenshot below. Is something like this what we want? Would this be helpful? Do we want something else?

![statistics_for_localhost localdomain_ 2015-11 _-_main_-_2015-11-12_15 45 29](https://user-images.githubusercontent.com/21006/36874435-dfb5f8d2-1d79-11e8-9ad1-0a34f81947d5.png)

**Comment by pameyer** [comment]
I suspect @landreev was referring to changing the apache log config to report `X-Forwarded-For`, which can (I *think*) be accommodated for but a corresponding change to the awstats config.

**Comment by pdurbin** [comment]
At https://javabot.evanchooly.com/logs/%23glassfish/2018-03-01 (#glassfish on freenode) I've been chatting with @phillipross and he rightly said, "awstats is old school... i believe these days people use ELK for that kind of stuff." I agree and I discovered that @bencomp wrote a nice little gist for ELK (that's Elasticsearch, Logstash, and Kibana for the uninitiated) at https://gist.github.com/bencomp/9b99cee2720d6233c8a1 for Glassfish's "access.log" format. Here's a copy/paste:

`GLASSFISHACCESS "%{IPORHOST:clientip}" "%{USER:auth}" "%{HTTPDATE:timestamp}" "(?:%{WORD:verb} %{SESSIONREQUEST:request}(?: HTTP/%{NUMBER:httpversion})?|%{DATA:rawrequest})" %{NUMBER:response} (?:%{NUMBER:bytes}|-)`

(The gist also includes a pattern for Glassfish's server.log, by the way.)

If we decide we'd like to give ELK a try, I should get in touch with @4tikhonov and @PaulBoon to see if DANS is still using it.

Oh, and thanks @pameyer because who knows if in the end we use awstats instead of ELK. Or something else. We're flexible. What do other Dataverse installations use?

**Comment by pdurbin** [comment]
This morning at standup @scolapasta @matthew-a-dunlap @jggautier and I decided I should purse awstats first ("as we used to say.... awstats was a task, but ELK is a project" as @phillipross said in #glassfish yesterday) and I just pushed a56a3ef to explain what I'm up to.

I copied `/var/log/httpd` from production from dvn-cloud-app-1 and attempted to process the files in a Vagrant VM on my laptop using `/usr/share/awstats/tools/awstats_updateall.pl now` as mentioned in the commit above. Unfortunately, I'm getting this error (after increasing the `NbOfLinesForCorruptedLog` value to 5000):

```
[root@standalone dataverse]# /usr/share/awstats/tools/awstats_updateall.pl now
Running '"/usr/share/awstats/wwwroot/cgi-bin/awstats.pl" -update -config=localhost.localdomain -configdir="/etc/awstats"' to update config localhost.localdomain
Create/Update database for config "/etc/awstats/awstats.localhost.localdomain.conf" by AWStats version 7.7 (build 20180105)
From data in log file "/var/log/httpd/ssl_access_log"...
Phase 1 : First bypass old records, searching new record...
Searching new records from beginning of log file...
Phase 2 : Now process new records (Flush history on disk after 20000 hosts)...
Flush history file on disk (unique url reach flush limit of 5000)
Jumped lines in file: 0
Parsed lines in file: 990958
 Found 0 dropped records,
 Found 0 comments,
 Found 0 blank records,
 Found 667803 corrupted records,
 Found 0 old records,
 Found 323155 new qualified records.

Running '"/usr/share/awstats/wwwroot/cgi-bin/awstats.pl" -update -config=standalone -configdir="/etc/awstats"' to update config standalone
Create/Update database for config "/etc/awstats/awstats.standalone.conf" by AWStats version 7.7 (build 20180105)
From data in log file "/var/log/httpd/ssl_access_log"...
Phase 1 : First bypass old records, searching new record...
Searching new records from beginning of log file...
Phase 2 : Now process new records (Flush history on disk after 20000 hosts)...
Flush history file on disk (unique url reach flush limit of 5000)
Jumped lines in file: 0
Parsed lines in file: 990958
 Found 0 dropped records,
 Found 0 comments,
 Found 0 blank records,
 Found 667803 corrupted records,
 Found 0 old records,
 Found 323155 new qualified records.

[root@standalone dataverse]#
```

Obviously, it's weird to see so many "corrupted" records. Next I'll work on making the awstats web interfaces available to people on the team.

**Comment by PaulBoon** [comment]
FYI at DANS we use PIWIK (now at https://matomo.org) for usage statistics.

**Comment by pdurbin** [comment]
I just opened https://dev1.dataverse.org/awstats/awstats.pl?config=localhost.localdomain to IP addresses for @sekmiller @matthew-a-dunlap and others so we can talk about awstats at standup.

**Comment by pdurbin** [comment]
Today I spent a little time trying to get awstats to work with Glassfish access logs. I didn't get very far, mostly because awstats doesn't seem to like how so many fields are quoted. (`%time1` for example is quoted and `LogFormat="%host time1=\"%time1\" methodurl=\"%methodurl\" %code %bytesd %otherquot %otherquot %otherquot %otherquot"` isn't working.)

In our production logs we are using `%client.name% %datetime% %request% %status% %response.length% %header.user-agent% %header.referer% %cookie.JSESSIONID% %header.x-forwarded-for%` as the value you get from `asadmin get server.http-service.access-log.format` but we've added four extra fields on the end vs. the default.

I also spend a little time at http://irclog.iq.harvard.edu/dataverse/2018-03-05 and https://irclog.perlgeek.de/crimsonfu/2018-03-05 asking what tools people use for log analysis. Wanting to make sense of logs is a common desire, so we should pick a tool. I'd say our options are:

- Splunk: proprietary but I believe it's paid for already at Harvard?
- ELK (Elasticsearch, Logstash, and Kibana) or the more modern equivalent: open source (still?) but complicated? https://www.elastic.co/elk-stack
- ELK but replace logstash with fluentd: open source but I've never heard of it: http://fluentd.org
- awstats: open source but a bit crufty and old. I'm currently struggling with it.
- TICK stack (Telegraph InfluxDB Chronograph and Kapacitor): open source but I've never heard of it. https://www.influxdata.com/time-series-platform/
- Sumologic: proprietary https://www.sumologic.com
- Write our own tool: seem tedious

I guess the next step is to keep hacking away on our logs using one or more of the tools above.

We also need to decided if we're targeting Apache access logs or Glassfish access logs or both. To get meaningful data out of Apache logs, we'll need to modify our config. We could pursue "insert LogFormat line before the "TransferLog logs/ssl_access_log" line in ssl.conf".

**Comment by pdurbin** [comment]
> Today I spent a little time trying to get awstats to work with Glassfish access logs. I didn't get very far, mostly because awstats doesn't seem to like how so many fields are quoted.

I just asked about this at https://stackoverflow.com/questions/49134154/what-logformat-definition-does-awstats-require-to-parse-glassfish-http-access-logs and https://sourceforge.net/p/awstats/discussion/43428/thread/9b1befda/

There was even more discussion about log analysis last night and https://irclog.perlgeek.de/crimsonfu/2018-03-06 and I thought this was an especially useful comment:

> "if you were going to instrument the DV application and/or JVM to emit metrics about database use, feature use, do event timing, track memory usage/etc/etc/etc from the application, then thinking about how that data would get streamed into elasticsearch/graphite/influxdb/etc so it could be graphed/trended would be very helpful for DV admins"

**Comment by pdurbin** [comment]
I just made pull request #4485 which I believe provides incremental value by cleaning up the page about monitoring in the Admin Guide and explains how to use AWStats with Apache logs that are not behind an Amazon load balancer. I also did some other general cleanup on that page. I'm moving this to Code Review at https://waffle.io/IQSS/dataverse

**Comment by pdurbin** [comment]
Since I'm reworked the monitoring page anyway and because @pameyer and I talked this morning about how useful Munin is, I went ahead and documented how to set it up a88532e

I've used Munin for years and below is a screenshot of "Apache access" from http://munin.greptilian.com/greptilian.com/server2.greptilian.com/apache_accesses.html

![screen shot 2018-03-06 at 2 32 07 pm](https://user-images.githubusercontent.com/21006/37053845-449e6eda-214b-11e8-9faf-bfa0fe817cd0.png)

**Comment by pdurbin** [comment]
As of this writing there are 32 installation of Dataverse on the map at https://dataverse.org so I'm soliciting feedback on my pull request (#4485) from all the sysadmin out there at https://groups.google.com/d/msg/dataverse-community/3PfkotTZFgs/CqD1CIVzAwAJ

**Comment by pdurbin** [comment]
Some more thoughts on monitoring, courtesy of @mikecroft from @Payara (thanks!) in my own words:

- The Microprofile Metrics API is a way for applications to expose telemetry data: https://github.com/eclipse/microprofile-metrics
- Jolokia ("remote JMX with JSON over HTTP") might be worth looking into: https://jolokia.org
- The "Monitoring Java EE Appservers with Prometheus and Grafana" video by @AdamBien is worth watching: http://www.adam-bien.com/roller/abien/entry/monitoring_java_ee_appservers_with

**Comment by mikecroft** [comment]
Here's a simple example of using MicroProfile Metrics:
https://github.com/payara/Payara-Examples/tree/master/microprofile/metrics

There are lots of annotations available to add your own instrumentation to the application as well as just monitoring the server itself. If you want more MBeans to be monitored, then you can supply a metrics.xml file to map MBean names to Prometheus-format metrics:
https://docs.payara.fish/documentation/microprofile/metrics.html

**Comment by pdurbin** [comment]
@mikecroft thanks! I was looking at a metrics folder in the wrong repo. Much appreciated, and now I see the [sample-prometheus.yml](https://github.com/payara/Payara-Examples/blob/master/microprofile/metrics/sample-prometheus.yml) file you mentioned.
