### ISSUE TITLE
Error in building docker-aio if locale is it_IT

### ISSUE THREAD

**Issue by domingoscisci** [IQSS/dataverse#4482]
As I explained in my [message](https://groups.google.com/d/topic/dataverse-community/haxkesa5Jic/discussion) in DV users community ML, I'm unable to build the docker image following the guide available at https://github.com/IQSS/dataverse/tree/develop/conf/docker-aio.
I got an error running 1prep.sh script, regarding the test suite "edu.harvard.iq.dataverse.ingest.tabulardata.impl.plugins.csv.CSVFileReaderTest", test "testVariableUNFs". Here's the error:

```
> -------------------------------------------------------------------------------
> Test set: edu.harvard.iq.dataverse.ingest.tabulardata.impl.plugins.csv.CSVFileReaderTest
> -------------------------------------------------------------------------------
> Tests run: 5, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.387 sec <<< FAILURE! - in edu.harvard.iq.dataverse.ingest.tabulardata.impl.plugins.csv.CSVFileReaderTest
> testVariableUNFs(edu.harvard.iq.dataverse.ingest.tabulardata.impl.plugins.csv.CSVFileReaderTest)  Time elapsed: 0.138 sec  <<< ERROR!
> java.lang.ArrayIndexOutOfBoundsException: 1
> 	at org.dataverse.unf.RoundRoutines.calcMantissa(RoundRoutines.java:399)
> 	at org.dataverse.unf.RoundRoutines.Genround(RoundRoutines.java:322)
> 	at org.dataverse.unf.UnfNumber.UNF5(UnfNumber.java:272)
> 	at org.dataverse.unf.UnfNumber.RUNF5(UnfNumber.java:215)
> 	at org.dataverse.unf.UnfDigest.unfV(UnfDigest.java:376)
> 	at org.dataverse.unf.UnfDigest.unf(UnfDigest.java:236)
> 	at org.dataverse.unf.UNFUtil.calculateUNF(UNFUtil.java:426)
> 	at edu.harvard.iq.dataverse.ingest.tabulardata.impl.plugins.csv.CSVFileReaderTest.testVariableUNFs(CSVFileReaderTest.java:350)
```

As already stated in the ML, changing the locale resolves the problem.

Here there are the steps to reproduce the error (test environment: Xubuntu 16.04 LTS VM with locale set to "it_IT.UTF-8" with appropriate apps (git, openjdk-8-jdk-headless, maven, docker.io) installed)
- clone the develop branch of dataverse
- run 0prep_deps.sh script: OK
- run 1prep.sh: **FAIL**
- reconfigure locale to en_GB.UTF-8
- run 0prep_deps.sh script: OK
- run 1prep.sh: OK

Feel free to ask me further information, if you need.
Thank you,
Domingo

**Comment by pameyer** [comment]
@domingoscisci thanks for the information.  I'm able to reproduce this failure (on CentOS); should be a straightforward fix.

For anyone curious about the UNF issue, it's reproducible with `export LANG=it_IT:UTF-8; mvn test`
