### ISSUE TITLE
email verify icon overlaps email address

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#4484]
As a user, I'd like icons to not overlap with text resulting in unreadable text.

![screen shot 2018-03-06 at 12 06 36 pm_bar](https://user-images.githubusercontent.com/10261853/37047009-c70af65e-2137-11e8-8b0e-b50913b7a375.png)

Black bar from blocking out email address; but green "email verified" and red "email unverified" icons overlap with mail addresses.

Seen in a 4.8.1 fork with custom footer, custom header, custom CSS.  Feel free to close if this isn't reproducible in non-customized mainline.

**Comment by djbrooke** [comment]
@pameyer I'm going to close this as we haven't seen this. If it's still happening and you want us to work on it, stop by the next time you're at IQSS and we can take a look together.

**Comment by pameyer** [comment]
@djbrooke Free free to leave it closed, but in my hands it's reproducible on develop bfe23273a 

![ss4484_20200124a](https://user-images.githubusercontent.com/10261853/73099867-5d659900-3eba-11ea-86a0-2ecdd8086652.png)

**Comment by djbrooke** [comment]
Ah, long emails. Got it.

**Comment by djbrooke** [comment]
Closing in favor of #6578

**Comment by mheppler** [comment]
As I commented in **Email Verification: 2 issues; refresh un-verifies, verify email button should always be available. #3438**...

> Added responsive layout clean up to the fix the overlapping of the email address and verified status label, as reported in #4484. If the containing width is too small, the button and/or status label will wrap to another line. (See screenshot.)
> 
> <img alt="Screen Shot 2021-01-19 at 3 24 35 PM" width="300" src="https://user-images.githubusercontent.com/687227/105096385-f8b13000-5a74-11eb-95c1-799937cfe90c.png">
