### ISSUE TITLE
Social Media per dataset & dataverse (tweet, share in FB, Google+)

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#449]
---

Author Name: **Gustavo Durand** (@scolapasta)
Original Redmine Issue: 3864, https://redmine.hmdc.harvard.edu/issues/3864
Original Date: 2014-04-17
Original Assignee: Mike Heppler

---

For Twitter, we want it to be the Share a Link one: https://about.twitter.com/resources/buttons#tweet We can choose to disable the count portion so it would only have the tweet button. 

For Facebook, we want it to be the Facebook Like Button: https://developers.facebook.com/docs/plugins/like-button We can choose what we want the button to look like, i.e.-have the number of Facebook Likes disabled. This posts to a user's Facebook timeline for others to see; Facebook has a share button that can be added in with the Like button but that can only be used for sending the link as a message to someone on Facebook. Weird. 
 
For Google +, we want to use their Share button: https://developers.google.com/+/web/share/ By choosing None under the Annotation dropdown, we can omit the count of how many times it has been shared.

I used this blog post to find out the best way to do all this: http://blog.hubspot.com/blog/tabid/6307/bid/29544/The-Ultimate-Cheat-Sheet-for-Creating-Social-Media-Buttons.aspx

**Comment by mheppler** [comment]
- [ ] Review and identify plugins, see how we can get a count of shares.
- [ ] Add "Share" button to the Contact/Link button group at the top of dataverse and dataset pages.

Related to ticket #1689

**Comment by mheppler** [comment]
Found a plugin and some font icons to use for this feature.
- Sharrre: http://sharrre.com/
- Socicon: http://www.socicon.com/

Working to get our Google Analytics wired up for the share count.

**Comment by mheppler** [comment]
Related: Google Analytics -- Track Social Shares/Interactions #1774

**Comment by mheppler** [comment]
Passing to @eaquigley to review the messaging of the share popup, as well as the text that gets added to a tweet. Right now, that just reads, "View this (dataverse/dataset)."

**Comment by mheppler** [comment]
I am taking this back. Still need your input on the text, but I am seeing all sorts of weirdness in the console log, that I want to look into, to make sure I've got this wired properly.

![screen shot 2015-03-27 at 6 15 51 pm](https://cloud.githubusercontent.com/assets/687227/6877987/54d9e272-d4ad-11e4-8d6d-b40be818caeb.png)

**Comment by mheppler** [comment]
Added empty urlCurl option for sharrre plugin to remove Google Plus error in console.

Without the sharrre.php file in our site, we won't be able to get the count from Google Plus. But the share button will still work.

Passing back for messaging review.

**Comment by eaquigley** [comment]
Looks most excellent! Closing ticket.
