### ISSUE TITLE
as a depositor, I'd like default terms to apply by default

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#4495]
The guides mention that CC0 is the default for new datasets: "http://guides.dataverse.org/en/latest/user/dataset-management.html#id25".  This default is not applied to datasets created using the native API (aka - datasets created without `license` or `termsOfUse` keys in JSON payload do not show CC0 by default).

Quick fix would be to clarify the docs - but the idea of "default to CC0" seems reasonable, and could be worth the effort the implement.

And credit to @jggautier for finding a bug that started me down the path to noticing this.

**Comment by pameyer** [comment]
thanks to @pdurbin for pointing me to a possibly related issue https://github.com/IQSS/dataverse/issues/1385 .

Regarding the discussion in that issue of "how to tell an API user that the default is CC0?" - my impression is that this should be at the account level, rather than the dataset level (but this might be an area for discussion).

**Comment by pameyer** [comment]
Documentation wording fix in #4539.

May make sense to leave this issue open for the "make this behavior the default" portion.

**Comment by mheppler** [comment]
Related to #3357

**Comment by pameyer** [comment]
@mheppler thanks, that looks like the appropriate issue for changing the behavior.
