### ISSUE TITLE
Fix/Clean up handling of 403 and 404 exit codes in data access API

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#4498]
1. "Not Authorized" and "Not Found" conditions are handled in the API as 
throw new WebApplicationException(Response.Status.FORBIDDEN)
and
...(Response.Status.NOT_FOUND) respectively. 
This must be some legacy way of throwing these exceptions. (a lot of this code was grandfathered from the older DVN implementation written for a very early version of Jersey). As of know, it's causing these messages in the server.log:
```
Response has already been committed, and further write operations are not permitted. This may result in an IllegalStateException being triggered by the underlying application. To avoid this situation, consider adding a Rule `.when(Direction.isInbound().and(Response.isCommitted())).perform(Lifecycle.abort())`, or figure out where the response is being incorrectly committed and correct the bug in the offending code.]]
```
This is, at best, noise in the logs. But, at worst, this may be resulting in hung connections between Glassfish and Apache mod_jk. 
The fix, apparently, is just to replace these with javax.ws.rs.ForbiddenException() and NotFoundException() respectively. 

2. We have an API-level exception handler for 404/Not Found: api/errorhandlers/NotFoundExceptionHandler.java; but not for 403 for whatever reason. This means, that when an API call results in a "Not Found", the client gets a 404 and a neat text message. But a 403 gets caught by the web application level handler, and returns the 403.xhtml page, intended for human users. (this is not specific to data access, but to the entire /api hierarchy). 
The fix is to provide a similar 20 line ForbiddenExceptionHandler.class. 

PR is coming. Again, this was de-facto prioritized since it was something we ran into during the migration and service stability investigation.

**Comment by landreev** [comment]
(I want to add that the data access API is a prime candidate for refactoring. Much of that code is unnecessary cumbersome because, as I said, it was originally implemented for a very early Jersey REST library. It also needs a good test matrix for various access/authorization scenarios. I will open a separate ticket)

**Comment by kcondon** [comment]
OK, confirmed by using file access api without proper perms. In old build threw uncaught error, in new build, error caught. Note that trying to fetch dataverse metadata without perms (unpublished) did not throw uncaught error in old build.
