### ISSUE TITLE
Feedback from SpinachCon 2018

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#4505]
Dataverse is participating in [SpinachCon 2018][] as an opportunity to get feedback on the experience for new contributors and I'm planning to make improvements to the Dataverse Developer Guide based on that feedback.

SpinachCon is [described][] as "a hackfest for user experience and new contributor feedback. The idea is that sometimes free software 'has a little spinach in it's teeth' and it needs its friends to let it know in a friendly way." It's associated with LibrePlanet, the Free Software Foundation's annual conference, where I gave a [lightning talk] about Dataverse last year.

Dataverse also [participated][] in [SpinachCon 2016][], and in the [photo] below, you can see a participant on each side of the table because Liz was running a usability test and I was gathering feedback on our contribution process.

![spinachcon2016](https://user-images.githubusercontent.com/21006/37373046-5365c904-26eb-11e8-8fa6-1f0aaf7f5d33.jpg)

This year Dataverse is not doing any usability testing. Instead, we'll focus on learning how to improve the new contributor experience. Toward that end, I have been working on #4419 to make the "setting up a development environment" page of the Dev Guide much shorter and focused. In case my pull request (#4502) doesn't get merged before the event, I set up hourly builds so participants can see the new and improved version at http://guides.dataverse.org/en/4419-new-developer/developers/dev-environment.html

Another difference from last time is that SpinachCon will be taking place in our building. The other projects that are participating are Debian and GNOME. Details of the event can be found on organizer Deb Nicholson's blog post at http://www.eximiousproductions.com/2018/03/09/spinachcon-2018/ but here are the basics:

- Date and time: Friday March 23rd, 12:30 - 5pm
- Location: CGIS Knafel, home of IQSS ([1737 Cambridge St.][], Cambridge, MA) room K354

My plan is to start a new branch just before the event and make commits throughout the day as I gather feedback. Then I'll make a pull request.

All are welcome to attend!

[SpinachCon 2018]: http://www.eximiousproductions.com/2018/03/09/spinachcon-2018/
[described]: https://www.libreplanet.org/2018/social/
[lightning talk]: https://www.youtube.com/watch?v=-GUr-cd_OWQ
[participated]: https://groups.google.com/d/msg/dataverse-community/G6cyCAv1hbY/iTI7_lCZBwAJ
[SpinachCon 2016]: https://opensource.com/life/16/4/spinachcon
[photo]:  https://twitter.com/philipdurbin/status/710986867437670401
[1737 Cambridge St.]: https://www.iq.harvard.edu/contact-us

**Comment by pdurbin** [comment]
SpinachCon was great. Here's the picture I tweeted at https://twitter.com/philipdurbin/status/977510501390389248

![spinachcon2018](https://user-images.githubusercontent.com/21006/37920487-f618861a-30f4-11e8-8f33-0db0d5acc338.jpg)

After standup I gave a brain dump to @djbrooke @kcondon @jggautier and @landreev 

The next step is to write up my notes in this issue.

**Comment by pdurbin** [comment]
My first SpinachCon was in 2016 and @jywarren was there. At around 12:50 in his talk on Sunday called [Sharing strategies for welcoming newcomers into FLOSS projects](https://media.libreplanet.org/u/libreplanet/m/sharing-strategies-for-welcoming-newcomers-into-floss-projects-first-timers-only-list-moderation-and-more/) he said, "SpinachCon was awesome. SpinachCon was the beginning of our journey." He talks about how you become humbled because you find out how difficult it is to install your software, but it's a positive experience because you're helping people and recognizing how hard it is to take the first step.

During that 2016 event @joeyh went through the process of installing a Dataverse dev environment (notes at https://github.com/IQSS/dataverse/issues/2863#issuecomment-199322114 ) and I was hoping that others would do this during SpinachCon on Friday. I feel like it's asking a lot to have someone load up their personal computer with all kinds of software to hack on your project so I'm not shocked that no one took me up on this. At the event Neil McGovern from GNOME has USB sticks to allow people to boot up into the version of GNOME he wanted people to test, an ephemeral environment. Maybe we could try something like this in the future but I don't know how well it would work on Mac hardware. Regardless, I still got valuable feedback from three people, which I'll describe below.

Feeback from @rul:

- Seeing "Admin login" on the Dataverse project page is somewhat confusing and may not be the best security practice. At first he thought that the project page may have been the Dataverse softare itself. Also, only a few people will be updating the project page we could consider hiding the link to the login page.
- When hovering on the project page menu bar, it might be nice to highlight the item you're on.
- Seeing over 800 open GitHub issues indicates a "huge backlog" but seeing over 3000 closed issues shows that the project is "really active".
- When asked to find a running installation of Dataverse from the project page, he couldn't find anything under the menus. He was looking for "use cases" or any other term that would help him find them.
- When looking at an installation of Dataverse, his first question was "are these papers?" The citation format is similar.
- He wasn't in love with some of the custom CSS he saw on a Dataverse installation he landed on from the map, but when he switched to Harvard Dataverse, the one he assumed would have a more "ideal configuration", he was happy with the site looked.
- He got errors when trying to download a file from the first dataset he landed on ( https://dataverse.harvard.edu/file.xhtml?fileId=3136098&version=RELEASED&version=.0 ). He was using Chromium 65.0.3325.146 on Debian unstable (Sid). He copied the "Download URL" and it worked fine from curl.
- He observed that even when download of a file does not complete successfully, the download count is incremented. This was originally reported at #3114. He suggested throttling downloads after a certain count, such as five downloads.

Feedback from Aaron:

- On the Dataverse project site, he liked the metrics but wanted to be able to click "Research Projects (33.1%)" to drill down and see some projects.
- When looking at Dataverse Community Meeting pages, he was wondering if there was a summary of each meeting. What was decided? What was the result of the meeting?
- He noticed we are using Google Groups for our mailing list and asked about privacy and forcing our users to give their information to Google. He likes it when projects run mailing lists on their own domains.

Feedback from @npettiaux:

- In the Dataverse CONTRIBUTING.md file, he really liked seeing "you don't need permission to participate" (credit to @HedgeMage in 426cf45 for that idea).
- If possible, he suggested making translations of CONTRIBUTING.md into other languages, such as French.

Even though I was hoping to get more people to attempt to set up a dev environment, in preparation for SpinachCon 2018 I did this myself on freshly installed Mac and Windows laptops following updated instructions I wrote for #4419. So I think at least for Mac we have better instructions than we've had for a while. It was also interesting to me to be a participant in the GNOME usability study. Finally, the feedback above is quite valuable. Once again, I'd like to thank everyone who participated!

**Comment by djbrooke** [comment]
Thanks for the feedback here! 

> On the Dataverse project site, he liked the metrics but wanted to be able to click "Research Projects (33.1%)" to drill down and see some projects.

We should take this into account when we redesign the metrics "aggregator" following the new APIs that we're adding in #4527. 

> When looking at Dataverse Community Meeting pages, he was wondering if there was a summary of each meeting. What was decided? What was the result of the meeting?

This is good feedback, as we're in the process of planning for DCM2018 (https://projects.iq.harvard.edu/dcm2018). We post the presentations and photos on the respective year's sites, but perhaps we could do a better job of linking back to the meeting outcomes (instead of just the general DCM sites)

**Comment by npettiaux** [comment]
Sorry to reopen the thread. What about proposing a docker installation (I must admit that i have not yet checked if it existed or not) at least for testing locally

**Comment by pdurbin** [comment]
@npettiaux hi! Please see this issue: Get Dataverse running on OpenShift (Docker and Kubernetes) #4040
