### ISSUE TITLE
Feature Request: Improve messaging when user selects too much data for download or download times out

### ISSUE THREAD

**Issue by meghangoodchild** [IQSS/dataverse#4507]
We are finding that users do not realize when they attempt to download too many files at one time (i.e., more than 10 GB). As a result, we are receiving tickets from users who are unsure why their download failed or times out. We would like more “heads-up” messaging, so that they are informed about these limitations before they attempt the download, as well as an error message if their download times out or fails for some other reason.

**Comment by pdurbin** [comment]
@meghangoodchild thanks for the bug report. It reminds me of #2060 but it sounds like you're talking about cases where the zip file fails to download. Can you please tell us which version of Dataverse you are using? You can find this at the bottom right of the page. Thanks!

**Comment by meghangoodchild** [comment]
@pdurbin we're from Scholars Portal Dataverse, currently running v. 4.7.1 and planning to update this spring.

**Comment by pdurbin** [comment]
Related: #4576
