### ISSUE TITLE
curl issue with native API

### ISSUE THREAD

**Issue by kaitlinnewson** [IQSS/dataverse#4510]
Hi Dataverse team,

I wanted to let you know about an issue we ran into using the Native API today. It appears to be an issue with certain versions of curl, in this case curl version 7.56.1. It seems to be related to this issue: https://github.com/curl/curl/issues/2022. The person running the commands was using Windows & Git bash. Our Dataverse instance is version 4.7.1.

Running the data upload command resulted in the following error: 
`Warning: garbage at end of field specification: ,"categories":["Data"]}` 

We eventually figured out that to get around this, you have to replace the second F flag (before the JSON) with --form-string instead, resulting in a command like this:

`curl -H "X-Dataverse-key:$API_TOKEN" -X POST -F 'file=@data.tsv' --from-string 'jsonData={"description":"My description.","categories":["Data"]}' "https://example.dataverse.edu/api/datasets/:persistentId/add?persistentId=$PERSISTENT_ID"`

I thought you might like to know in case anyone else runs into this. It may be useful to have in the docs somewhere too.

**Comment by pdurbin** [comment]
Huh. Interesting. Thanks for the bug report and the fix, @kaitlinnewson !

**Comment by pdurbin** [comment]
I'm thinking we should simply add a note at the bottom of https://guides.dataverse.org/en/latest/api/getting-started.html#curl-examples-and-environment-variables

Something like:

"With curl version 7.56.1 and below, for commands with ` -F 'jsonData=...` you might need to use  `--from-string 'jsonData=...` instead: https://github.com/curl/curl/issues/2022 "

For how to edit that page in the API Guide: https://guides.dataverse.org/en/latest/developers/documentation.html#quick-fix
