### ISSUE TITLE
HTTP Errors during file upload not caught

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#4511]
It looks like the code in editFilesFragment.xhtml (v 4.8.5) does not catch HTTP errors and thus these failures leave the GUI showing a full progress bar for the file with no further updates. I suspect that this is what was being seen in issue #4439 . In our case, we had a server with nginx configured with a small upload size limit and I was receiving 413 (Request Entity Too Large) errors (rather than some timeout error you might expect for GB+ files). It's straight-forward to add a javascript onerror handler to the p:fileUpload element to provide some user feedback that there's been a failure. I'd be happy to submit one if I can get some guidance on what error action would make sense for dataverse (just a note to the right of the entry stating that "the upload of this file has failed (<error code>) and it will not be saved to your dataset.", or?).

**Comment by pdurbin** [comment]
@qqmyers more feedback to the user about what's going on sounds great. I would say that for now you can put whatever message you want in a pull request and we can iterate on it. Thanks!

**Comment by pdurbin** [comment]
@qqmyers thanks for creating pull request #4522! I just dragged it to code review at https://waffle.io/IQSS/dataverse

**Comment by qqmyers** [comment]
Turned out it wasn't 'straight-forward' to get the status and other info across Chrome, Firefox, and Edge, but I was able to get them from the call stack. After that, I just wrote a simple message to the right of any entry that failed showing the error code (popup for the status text).

Doing this is different than how the error is reported when a file already exists in the dataset - where, as soon as there's one error, a message is posted, and the file list is deleted. A second error of this type replaces the first error message even though the second file no longer show in the list. 

It should be possible to work more like the file already exists error and put a red message below, but it seems like it would be less useful to work exactly like it and only show one message at a time and remove the file list. (If I upload 10 files (or more) and a few fail, I'd want to see the list of failures somewhere. And I'd probably want the same if there were several files that already existed in the dataset...). For this reason, and not wanting to go to far in trying to figure out how to make the client-side detection of HTTP errors tie into the server-side reporting coming back through JSF, I decided to leave it as is for now. Something simple like using CSS to make the HTTP errors have the same styling as the file already exists error message might be worthwhile though...

**Comment by pdurbin** [comment]
@qqmyers thanks for the write up. This morning I helped @sekmiller switch to your fork and branch and he's taking a look.

**Comment by matthew-a-dunlap** [comment]
Thanks for sending this our way @qqmyers . I had to minorly change the code to get it running as the function being called was not the correct name.

Here is a sample screenshot demoing the functionality. To do this I hacked the handleFileUpload method to add an error to the HttpServletResponse:

![screen shot 2018-03-21 at 1 06 42 pm](https://user-images.githubusercontent.com/8901015/37725170-bc6da854-2d08-11e8-8b56-fabfda37e224.png)

I noticed that if a user keeps uploading files the javascript will begin to concat repeats of the error message. I have yet to dig into it in more depth.

**Comment by matthew-a-dunlap** [comment]
@qqmyers Totally. Our team is going to discuss design around displaying these errors and get back to you about a good path to move forward on this. Thanks again!

**Comment by matthew-a-dunlap** [comment]
p.s. Its possible my fake errors in handleFileUpload are being added multiple times causing repeat errors.

**Comment by matthew-a-dunlap** [comment]
@qqmyers Our dev team discussed this and was hoping to find a solution that works with our normal JSF / PrimeFaces flow. I investigated solutions to this issue and was surprised at the number of steps it seemed to take to inside JSF / PrimeFaces. I tried asking last week on the PrimeFaces forum for guidance on this issue: https://forum.primefaces.org/viewtopic.php?f=3&t=55039&sid=c76fb7669bd36e2acc611e59b8a5c174 , some details of my investigation are in there. They have yet to reply but I am going to give it another day or two before finding another path.

Also FWIW, the issue with the double error labels seems to happen because the javascript matches on name, yet the user can upload multiple files of the same name. The concatenation of the error text then happens multiple times.

**Comment by pdurbin** [comment]
I don't know if this helps or not but I recently learned that PrimeFaces is on Gitter: https://gitter.im/primefaces/primefaces

**Comment by qqmyers** [comment]
@matthew-a-dunlap - thanks for the update. I agree it would be nice if Primefaces could handle it so hopefully they can provide some guidance. If javascript ends up being the best option, or if a javascript trigger just needs to send more than a filename to make it clear to JSF which entry had the error, I'd be happy to see what other info is available.

**Comment by pdurbin** [comment]
@matthew-a-dunlap if you could provide me with a brain dump of the latest on this issue, I'd appreciate it. At standup this morning I said I'd try to help.

**Comment by matthew-a-dunlap** [comment]
My apologies for our slow reply on this @qqmyers . We are interested in bringing in this javascript fix after a few outstanding points are fixed/investigated:

- Are there more verbose errors reported to onError? Something more than "error 403"
- Is there a way to fix the matching issue (e.g. something else to match on beside filename)? If not, we should only display one error and it should be more generic.
- Can you take a stab at trying to style this? See Bootstrap `text-danger` classes to be consistent with messaging outlined in our Style Guide.

**Comment by qqmyers** [comment]
Matthew,
I'm out this week, but I can look at these things next week. There is a text version of the error message that's more useful. It's actually shower now if you hover over the error code. I'm guessing there must be some way to distinguish files, but we'll see.
 Thanks,
Jim

On Apr 2, 2018 1:00 PM, matthew-a-dunlap <notifications@github.com> wrote:

My apologies for our slow reply on this @qqmyers<https://github.com/qqmyers> . We are interested in bringing in this javascript fix after a few outstanding points are fixed/investigated:

  *   Are there more verbose errors reported to onError? Something more than "error 403"
  *   Is there a way to fix the matching issue (e.g. something else to match on beside filename)? If not, we should only display one error and it should be more generic.
  *   Can you take a stab at trying to style this? See Bootstrap text-danger classes to be consistent with messaging outlined in our Style Guide.

**Comment by pdurbin** [comment]
@qqmyers thanks for working on this and nice talking to you on the community call the other day. I haven't loaded up your code myself but I like that you're trying to improve the user experience when uploading files. Error handling is super important. I hope your users aren't seeing too many of these errors!

I'm updating the "dev efforts from the community" spreadsheet linked from https://groups.google.com/d/msg/dataverse-community/X2diSWYll0w/ikp1TGcfBgAJ and I just added this issue and your pull request to it so we don't forget to follow up. There's no rush. I'm going to pull this out of the "Development" column at https://waffle.io/IQSS/dataverse so we don't have to see it every morning at standup but please just ping us when you want us to take another look at the code.

One more thing that's on my mind is that we're pretty far behind on our version of PrimeFaces and I hope that whatever you come up with will continue to work once we upgrade. Just something to think about. Thanks!

**Comment by matthew-a-dunlap** [comment]
This looks really great @qqmyers .The only thing I see needed is to merge development into your branch, and then our QA can take a look. 

Below is a screenshot in case folks are interested in the messaging.

![screen shot 2018-04-23 at 3 44 34 pm](https://user-images.githubusercontent.com/8901015/39149777-427c90c6-470e-11e8-947e-b3256a12626c.png)

**Comment by pdurbin** [comment]
@qqmyers hi! We just discussed this issue and pull request in sprint planning this afternoon. When you have a moment, please merge the latest from the "develop" branch into your pull request so we can advance this to QA in our kanban board. Thanks!

**Comment by qqmyers** [comment]
OK - merged again...

**Comment by djbrooke** [comment]
Thanks @qqmyers - moved over to QA.
