### ISSUE TITLE
Cannot download guestbook in Chrome if Dataverse has a "," in the name

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#4512]
Discovered by CCAFS:
https://dataverse.harvard.edu/dataverse/CCAFSbaseline

If a Dataverse has a "," in the name, the user gets an error when downloading guestbook responses via Chrome.

ERR_RESPONSE_HEADERS_MULTIPLE_CONTENT_DISPOSITION

This looks to be easily solved by adding quotes around the filename when setting the Content-Disposition header (see https://stackoverflow.com/questions/13578428/duplicate-headers-received-from-server)

At the same time we should consider:
- by adding these quotes, we likely don't need to replace spaces with "_".
- would it be better to use the guestbook name as the name instead of dataverse name and id (@jggautier ?)

**Comment by jggautier** [comment]
> would it be better to use the guestbook name as the name instead of dataverse name and id (@jggautier ?)

Or the name of the guest book plus the name of its dataverse?

**Comment by mheppler** [comment]
Retracted closing issue as a duplicate of #4671.

**Comment by mheppler** [comment]
Apparently I already tried to close this issue as a duplicate. So this time, lets leave this one open, and close _Guestbook: Cannot download a particular guestbook using Chrome, throws duplicate header error #3581_ as the duplicate.
