### ISSUE TITLE
SwordIT failing on develop

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#4516]
`testCreateDataverseCreateDatasetUploadFileDownloadFileEditTitle(edu.harvard.iq.dataverse.api.SwordIT): Cannot get property 'head' on null object`

`Tests run: 66, Failures: 0, Errors: 1, Skipped: 0`

https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-apitest-develop/lastBuild/edu.harvard.iq$dataverse/testReport/edu.harvard.iq.dataverse.api/SwordIT/testCreateDataverseCreateDatasetUploadFileDownloadFileEditTitle/

**Comment by pdurbin** [comment]
`	at edu.harvard.iq.dataverse.api.SwordIT.testCreateDataverseCreateDatasetUploadFileDownloadFileEditTitle(SwordIT.java:262)`

as of 50db13a133a61ad2a1bb21b4ba5a896d59e2fa50

**Comment by pdurbin** [comment]
Here's the code at https://github.com/IQSS/dataverse/blob/50db13a133a61ad2a1bb21b4ba5a896d59e2fa50/src/test/java/edu/harvard/iq/dataverse/api/SwordIT.java#L262

        Response attemptToDownloadUnpublishedFileWithoutApiToken = UtilIT.downloadFile(fileId);
        attemptToDownloadUnpublishedFileWithoutApiToken.then().assertThat()
                .body("html.head.title", equalTo("403 Not Authorized - Root"))
                .statusCode(FORBIDDEN.getStatusCode());

It would be nice to know if this is still "FORBIDDEN" or not.

@matthew-a-dunlap has suggested that the status code checks should go before the body checks. He's probably right. I always put the status code last because I know I want it there and I can easily add and replace body checks above it without touching the final line.

**Comment by pdurbin** [comment]
I just made pull request #4521 to have the text expect JSON output rather than HTML (this behavior changed after pull request #4509 was merged) and moved this issue to code review at https://waffle.io/IQSS/dataverse

**Comment by pdurbin** [comment]
@matthew-a-dunlap and I discussed this issue and he's going to make sure the tests are fixed on machine other than my laptop.

**Comment by matthew-a-dunlap** [comment]
I have run the built and run the IT tests on phoenix, was easy-peasy and succeeded!

**Comment by pdurbin** [comment]
@matthew-a-dunlap thanks! https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-apitest-develop/ is looking much better (tests no longer failing):

![screen shot 2018-03-20 at 2 42 14 pm](https://user-images.githubusercontent.com/21006/37675942-f4ec5d40-2c4c-11e8-89b7-aa9dfef9c613.png)

If you or anyone else has any feedback for what I wrote at http://guides.dataverse.org/en/develop/developers/testing.html#the-phoenix-server please let me know (or make a pull request to fix any confusing wording).
