### ISSUE TITLE
Dataverse release artifacts

### ISSUE THREAD

**Issue by ajs6f** [IQSS/dataverse#4523]
This ticket is a request for information, not for action.

Looking at the released artifacts, it seems that Dataverse is distributed as a WAR. If it is in fact using only the JEE APIs available from a servlet container, what is the need for Glassfish at all? Shouldn't Dataverse be usable with any servlet container? If it is not, if it is using JEE APIs normally only available from a full application container, why is it distributed as a WAR and with a requirement for Glassfish instead of as an EAR that could be used with any application container?

**Comment by pdurbin** [comment]
@ajs6f you're right. Dataverse is distributed as a WAR. I've heard of EAR and I remember seeing references to it from the DVN 3 days (DVN 3 was the predecessor to Dataverse 4). I've been under the impression that as of Java EE 6 you can put more stuff in a WAR file and that you sort of don't need EAR files anymore, that a WAR file is simpler, basically. "The ability to package local enterprise beans in a WAR file" is listed as a [feature][]. You're making it sound like switching from a WAR to an EAR would help remove Dataverse's dependence on Glassfish, allowing other app servers to be used such as Wildfly or Liberty (I don't believe TomEE supports Java EE 7 full profile). It sounds nice.

While the WAR file is the main artifact for a Dataverse [release], we distribute an installer as well, called "dvinstall.zip". The installer is meant for new installations and contains the WAR file and a variety of installation scripts and configuration files. Existing installations don't need the installer to upgrade to the next Dataverse version. They need the war file and any SQL upgrade scripts or other updates (such as Solr schema changes).

I wouldn't say that we love our current approach of having a Perl script that does all the setup we need (more than just deploying the war file) but it gets the job done. We're all ears if you have suggestions for how to improve the artifacts we release and make the whole installation process better.

[feature]: https://docs.oracle.com/javaee/6/tutorial/doc/bnacj.html
[release]: https://github.com/IQSS/dataverse/releases

**Comment by ajs6f** [comment]
Not to speak of-- I have not heard any requests from the group evaluating Dataverse. 

Looking at this issue with fresh eyes, it occurs to me that the simplest solution would be to release a WAR (which you are now doing) with an accompanying README explaining what database connections (or other JEE resources) are needed under what names to run it. Then people like me could take the WAR, set up the right connections, and go forward. Of course, that might imply changes to initialization or other parts of the codebase.

**Comment by pdurbin** [comment]
@ajs6f I see. I think you have more confidence than I do in getting Dataverse running on any application server other than Glassfish (or Payara, see #4172, which is an actively patched version of Glassfish). I'm curious which other application servers you would try.

No requests from the group evaluating Dataverse sounds good, I guess! Hopefully they are still kicking the tires. We'd love to hear their feedback. 😄

**Comment by djbrooke** [comment]
I'm going to close this. We have a Python installer now (#6484) and we're investigating moving off Glassfish 4.1 (#4248) to support one or more new application servers. We can re-evaluate the release artifact process in the future once these changes have been made.
