### ISSUE TITLE
Guestbook : Required fields not filled but on validation, no warnings and file is downloaded

### ISSUE THREAD

**Issue by rmo-cdsp** [IQSS/dataverse#4526]
Hello !

As the title says, I tried the Guestbook feature with a file I added to a dataset. This guestbook looks like this:

![screenshot from 2018-03-20 10-49-34](https://user-images.githubusercontent.com/14806890/37650173-6ea5a574-2c34-11e8-957b-f8cfb63ba44d.png)

As you can see, there are a lot of required fields. But it seems that required fields are not that much "required", because I can download the file of my dataset without filling the fields. The dataverse version used is 4.8.4 .
If you have a dataverse testing environnement available (I don't have any link left), I would be happy to reproduce it.

**Comment by pdurbin** [comment]
@rmo-cdsp hi, thanks for the bug report. I believe this was fixed in 4.8.5 in pull request #4404. There's some discussion in #4393 and in the release notes at https://github.com/IQSS/dataverse/releases/tag/v4.8.5

**Comment by djbrooke** [comment]
Thanks @pdurbin. I'm closing this as a duplicate, @rmo-cdsp feel free to reopen if you feel this in incorrect.

**Comment by djbrooke** [comment]
(realized I forgot to close this :) )
