### ISSUE TITLE
as a person building `dvinstall.zip`, I'd like dependency resolution in `make` to work

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#4528]
#3974 was too focused on a particular solution to this problem, rather than the higher level problem - when building `dvinstall.zip` the makefile rules do not recognize when the war file to be included is newer than the produced zip file, and therefore typing `make` does not rebuild the zip file when it should.

From discussions with @pdurbin, the solution proposed in #3975 has undesirable side effects - so isn't a good path forward.

**Comment by pdurbin** [comment]
@pameyer thanks for opening this issue. As you've discovered and implemented at https://github.com/IQSS/dataverse/blob/v4.8.5/conf/docker-aio/1prep.sh#L19 the workaround is to run `make clean` before running `make`. This will ensure that a fresh `dvinstall.zip` file is created with the latest war file that has been built.

Hopefully we will move in the direction of writing automated tests that operate on the `dvinstall.zip` file to install Dataverse. It's certainly on topic for the list at http://guides.dataverse.org/en/4.8.5/developers/testing.html#installation-testing if it's worth adding something there but this issue itself is probably enough of a reminder.

**Comment by pameyer** [comment]
@poikilotherm If maven solves the problem of broken dependency resolution, then it solves the problem :)

**Comment by pdurbin** [comment]
@poikilotherm it's more than you and @pameyer both seem to dislike Make so I thought you two should put your heads together. 😄 

/me runs
