### ISSUE TITLE
as a repository operator, I'd like to be sure that analytics reports are accurate

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#4533]
current `google-analytics-snippet.xhtml` has:

`          ga('send', 'pageview', {
            'hitType': 'social',
            'socialNetwork': 'facebook',
            'socialAction': 'send',
            'socialTarget': '#{systemConfig.dataverseSiteUrl}',
            'page': '#{systemConfig.pageURLWithQueryString}'
          }, {
            'hitType': 'social',
            'socialNetwork': 'twitter',
            'socialAction': 'tweet',
            'socialTarget': '#{systemConfig.dataverseSiteUrl}',
            'page': '#{systemConfig.pageURLWithQueryString}'
          });
`
It looks to me like this will over-report social network interactions on page load (instead of tracking the "share" button aka #1774), based on docs at https://developers.google.com/analytics/devguides/collection/analyticsjs/social-interactions and https://developers.google.com/analytics/devguides/collection/analyticsjs/command-queue-reference#send

**Comment by kcondon** [comment]
not seeing content on homepage but works fine on same box with /develop. might be a missing/ bad merge issue with solr 7

**Comment by pameyer** [comment]
From @kcondon's finding of 
``
edu.harvard.iq.dataverse.search.SearchServiceBean] [tid: _Thr
eadID=50 _ThreadName=jk-connector(1)] [timeMillis: 1523290275207] [levelValue: 800] [[
 Search Syntax Error: Expected content type application/octet-stream but got text/html;charset=iso-8859-1. <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404</h2>
<p>Problem accessing /solr/spell. Reason:
<pre>    Not Found</pre></p>
</body>
</html>
]]
``
the `/solr/spell` endpoint suggests to me that it was merge issues with solr 7.

**Comment by pdurbin** [comment]
@pameyer if it helps, we switch away from `/spell` to the default (`/select`) in d3b721e

**Comment by pameyer** [comment]
@pdurbin - it does help; I thought I remembered that `/spell` to `/select` was part of the upgrade.

Checked commit log; appears that this PR was updated for the version bump but not the solr upgrade.  Planning to merge develop again, recheck, and pass back to QA.

**Comment by pameyer** [comment]
re-merged; re-ran ITs in docker-aio; verified that homepage is non-empty after setupIT.bash
