### ISSUE TITLE
OAI_dc compatibility

### ISSUE THREAD

**Issue by LLongva** [IQSS/dataverse#4537]
We would like to have our Dataverse harvested by e.g. BASE (https://www.base-search.net/) and other harvesters. From BASE we get the response that our OAI is not oai_dc compatible. It does not return the metadata correctly:
"... returns fields as dc:license, dc:dateSubmitted, dc:modified, dc:issued which looks more as qualfied dc."

The problem seems to be that OAI returns elements from the dcterms namespace, but presents them as dc elements (http://dublincore.org/documents/dcmi-terms):
...
<dc:isReferencedBy> ... </dc:isReferencedBy>
<dc:dateSubmitted> ... </dc:dateSubmitted>
<dc:license>CC0</dc:license>
...

Is this something that may be solved in Dataverse? So that e.g.
<dc:isReferencedBy> is shown as <dc:relation>
<dc:dateSubmitted> is shown as <dc:date>
<dc:license> is shown as <dc:rights>,
in accordance with unqualified dublin core.

I see that OAI-PMH issues are discussed previously in this User Community, but I do not see where this issue stands. Is this perhaps something that the OpenAIRE compliancy will address?

Yours
Leif Longva
UiT, Norway and 
DataverseNO

**Comment by jggautier** [comment]
It looks like BASE supports two metadata formats as of this writing: oai_dc and base_dc (http://oai.base-search.net/#metadata-formats). So I think OpenAIRE compliancy might resolve this issue if BASE added oai_datacite. I hope all of this helps!

**Comment by JingMa87** [comment]
@jggautier Is there anything that I can do to help solve this issue? It seems to me that you already provided the answer (re-exporting the records).

**Comment by jggautier** [comment]
Thanks for following up about this @JingMa87. Looks like the issue's resolved.

@LLongva, it looks like DataverseNO's oai_dc exports are using elements from the DC Elements namespace (instead of DC Qualified), e.g. https://dataverse.no/oai?verb=GetRecord&metadataPrefix=oai_dc&identifier=doi:10.18710/HK395Z, and DataverseNO datasets have been harvested by BASE. Is it okay to close this GitHub issue?

**Comment by djbrooke** [comment]
I'll go ahead and close this. @LLongva please tell us if you feel this should be reopened. Thanks @jggautier and @JingMa87 !
