### ISSUE TITLE
Share - Track Dataverse, Dataset, File sharing in Google Analytics

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#4538]
While reviewing changes to the Google Analytics code in issue #4533, I learned that as @pameyer pointed out, we were not tracking social interactions properly. The code should have been formatted something like this.

```
            $(document).ready(function () {
               $('#sharrre-block a.sharrre-facebook').on('click', function(e) {
                   e.preventDefault();
                   ga('send', 'social', 'Facebook', 'like', '#{systemConfig.pageURLWithQueryString}');
               });
               $('#sharrre-block a.sharrre-google').on('click', function(e) {
                   e.preventDefault();
                   ga('send', 'social', 'Google', '+1', '#{systemConfig.pageURLWithQueryString}');
               });
               $('#sharrre-block a.sharrre-twitter').on('click', function(e) {
                   e.preventDefault();
                   ga('send', 'social', 'Twitter', 'tweet', '#{systemConfig.pageURLWithQueryString}');
               });
           });
```

In addition to not sending social interactions to Google Analytics properly, it appears that the Sharrre plugin we are using to provide social sharing functionality is outdated. It's Google Analytics code is old, which is most likely also prohibiting us from proper tracking social interactions using our "Share" button, as we had intend in the original issue #1774.

**Comment by mheppler** [comment]
Also closely related to _Custom Analytics - More than just pageviews #4660_.

**Comment by mheppler** [comment]
As part of #4660, the analytics code was removed from being hardcoded in `dataverse_template.xhtml` to being a configuration setting (Installation Guide > Configuration > Web Analytics Code).

The analytics code needed to track social media shares will need to be added using that new config setting. Documentation should be added to the Admin Guide or the Installation Guide outlining how to track these share events for dataverses, datasets and files.

**Comment by pdurbin** [comment]
I'm not sure if we still need this. The solution in the following PR seems to be working:

- #5628
