### ISSUE TITLE
Exploring the Tabular data through TwoRavens - Demo website does not load the data into TwoRavens

### ISSUE THREAD

**Issue by MINGEIN** [IQSS/dataverse#4540]
Hi, I am trying to demo some tabular data exploration through your demo website and it does not seem to be able to load my tablular data into TwoRavens tool when I click on the "explore".   
I tried it with different tables and the issue remains the same.
I know that that tool is not maintained any more but it would be nice to get a view of what one could be possibly do with it.
Thanks.

**Comment by djbrooke** [comment]
Hi @MINGEIN - The TwoRavens tool is supported, just by a different group. You should log this issue in their issue tracker and someone from the TwoRavens team should be able to help:

https://github.com/IQSS/TwoRavens/issues

In the meantime, I'll close this issue.
