### ISSUE TITLE
Replace links to best-practices.dataverse.org with links to dataverse.org

### ISSUE THREAD

**Issue by dlmurphy** [IQSS/dataverse#4544]
best-practices.dataverse.org currently hosts content that is also duplicated on dataverse.org. In order to reduce confusion and the need to keep two identical pages identically updated, we've decided to deprecate the best-practices.dataverse.org content and only maintain the dataverse.org content. I've already fixed things up on the dataverse.org end [here](https://github.com/IQSS/dataverse.org/issues/62), but this issue is to fix things up in the Dataverse application itself.

Each page on best-practices.dataverse.org has an equivalent page on dataverse.org. For example:
http://best-practices.dataverse.org/harvard-policies/community-norms.html 
is equivalent to
https://dataverse.org/best-practices/dataverse-community-norms

For this issue, let's replace all links to best-practices.dataverse.org in Dataverse with links to their equivalent pages on dataverse.org

**Comment by mheppler** [comment]
Files containing old links that need to be updated:

- /doc/sphinx-guides/source/_static/installation/files/etc/maintenance/maintenance.xhtml
- /doc/sphinx-guides/source/installation/config.rst
- /doc/sphinx-guides/source/user/dataset-management.rst
- /scripts/api/setup-optional-harvard.sh
- /src/main/java/Bundle.properties

**Comment by mheppler** [comment]
All links have been updated, with the exception of the sample maintenance pg provided in the Installation Guide. That file does not require that link in the first place, so I removed it as well as other Harvard specific footer info and links.

**Comment by sekmiller** [comment]
Looks good. Moving to QA.

**Comment by kcondon** [comment]
not seeing content on homepage but works fine on same box with /develop. might be a missing/ bad merge issue with solr 7
