### ISSUE TITLE
Customization – update Harvard Dataverse logo and tagline

### ISSUE THREAD

**Issue by TaniaSchlatter** [IQSS/dataverse#4546]
Part of this issue is making the logo change as in #3872. The other part is changing the tag line text to link users to https://dataverse.harvard.edu and https://dataverse.org/

See mockup below and [linked here]

(https://drive.google.com/drive/folders/0B5iL_lNzaDuccUk4dGNia1BveG8).
<img width="1251" alt="demo_dataverse_revised2" src="https://user-images.githubusercontent.com/15386424/37982785-873acc64-31bf-11e8-8bcc-03d13ca612c8.png">

**Comment by mheppler** [comment]
Including comment from @TaniaSchlatter on issue #3872

> Reopening issue to change the Harvard Dataverse logo to the small shield version on the Harvard installation and Harvard Demo. This change is being made to deemphasize the Harvard Shield, so that the Dataverse name has a bit more prominence. 

> Replace the logo with the file "Harvard-Dataverse_SmallShield” 

<img width="940" alt="h_dv_small_logos_compare" src="https://user-images.githubusercontent.com/15386424/37978689-98fcc2dc-31b4-11e8-8186-2614ef3e503a.png">

**Comment by mheppler** [comment]
To specify if all the edits are not clear...

Production (see mockup from @TaniaSchlatter in my comment above)
- update Harvard Dataverse logo in customization with smaller shield version of logo

Demo (see mockup from @TaniaSchlatter in her first comment above)
- update customization and branding on demo to closer resemble production, including updated custom navbar logo, removing root theme header
- remove tagline from theme header and instead use root dataverse description for header, text and links

Will coordinate with @kcondon to get all files, text and links needed for both environments.

**Comment by mheppler** [comment]
@kcondon -- moving this issue to QA, and providing links to ZIP files containing all the necessary image, HTML and CSS files. Here is an outline of the changes required to each environment.

**DEMO**

_Resources_

https://drive.google.com/open?id=1WKqi9VCcRl_JxkFn7IiABMeCDS_AxVwt

_Custom Navbar Logo_

`/resourcesDemo-2018-03-28/harvard-dataverse-logoSMshield.png`

_Custom CSS_

`/resourcesDemo-2018-03-28/harvard-dataverse-stylesheet.css`

_Dataverse Description_

```
<span><span><span><h3>This Dataverse is for demo purposes only.</h3></span></span></span>

To archive and publish to the Harvard repository, visit <a href="https://dataverse.harvard.edu" title="Harvard Dataverse" target="_blank">dataverse.harvard.edu</a>. To learn about and publish to other repositories, visit The Dataverse Project at <a href="https://dataverse.org" title="The Dataverse Project" target="_blank">dataverse.org</a>.
```

_Custom Footer_

`/resourcesProd-2018-03-28/harvard-dataverse-footer.html`

**PRODUCTION**

_Resources_

https://drive.google.com/open?id=1dWDiPEmFfnDJw-U5xzTtpMu3ucvWAynS

_Custom Navbar Logo_

`/resourcesProd-2018-03-28/harvard-dataverse-logoSMshield.png`

Please let me know if you have any questions.

**Comment by TaniaSchlatter** [comment]
Demo Dataverse is supposed to have the general Dataverse logo:
![image](https://user-images.githubusercontent.com/15386424/38269407-690c297e-374e-11e8-80b9-5583d63021d8.png)

**Comment by pdurbin** [comment]
The alias of the root dataverse on the demo server is "harvard" (you can tell by clicking "Advanced Search" and seeing "harvard" in the URL you land on: https://demo.dataverse.org/dataverse/harvard/search ). Perhaps this alias should be reverted back to the default, which is "root". Or something other than "harvard".

**Comment by scolapasta** [comment]
How about "demo"? :)

**Comment by scolapasta** [comment]
I went ahead and changed the alias of the root to "demo". Moving to QA as it looks like the header was changed.
