### ISSUE TITLE
Harvesting: Harvesting clients never complete harvesting of updates of at least 2 smaller sites.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#4548]
This is happening in the new Harvard AWS production architecture.

Harvesting of TDR and Madrono do not complete and appear to hang or pause and never complete according to both the in progress status in the UI and the harvest logs. Harvesting of both these sites works relatively quickly (about 5 minutes or less) on the test environment. Is this a network connectivity issue of some type related to the new architecture?

Update: both clients process 10, and 11 identifiers before halting in 27 and 19 seconds, respectively.
Update 2: though these hanged jobs were run manually, successful initial harvests for tdr on 02-05 and 02-06 were scheduled *and* logged on both web instances. (Note: this is from pre migration testing and logs were cloned)
Update 3: the harvest from date in 03-26 log is 02-14 but there is no 02-14 harvest log on either instance. (Note: this is because 02-14 harvest occurred pre migration and log was not copied over).
Update4: 
The last successful harvest of tdr, according to existing log files on cloud1 &2, was on 02-06-18 and resulted in 0 datasets. Directly requesting list identifiers from that date results in 100 identifier changes (new/delete) and 2 subsequent harvests since 02-06 resulted in getting, 10 (9 new, 1 delete), and 10 (9 new and 1 delete) from 03-26 and 03-27. (Note: the from date may actually be 02-14 because it appears as the from date in the 03-26 log. It does not appear on the AWS servers because harvest occurred pre migration and harvest log was not copied over. The list identifiers command from 02-14 still shows 100 identifiers)
Update 5: the madrono list identifiers also shows 100 identifiers available from last harvest of 02-11-18
https://edatos.consorciomadrono.es/oai?verb=ListIdentifiers&from=2018-02-11&metadataPrefix=oai_ddi&set=openaire_data

Here is the tdr list identifiers list:
https://dataverse.tdl.org/oai?verb=ListIdentifiers&from=2018-02-06&metadataPrefix=oai_ddi&set=TDR
<OAI-PMH xmlns="http://www.openarchives.org/OAI/2.0/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/ http://www.openarchives.org/OAI/2.0/OAI-PMH.xsd">
<responseDate>2018-03-28T16:20:27Z</responseDate>
<request verb="ListIdentifiers" metadataPrefix="oai_ddi" from="2018-02-06" set="TDR">https://dataverse.tdl.org/oai</request>
<ListIdentifiers>
<header>
<identifier>doi:10.18738/T8/0H1MWK</identifier>
<datestamp>2018-03-08T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/0SL6NE</identifier>
<datestamp>2018-03-18T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/0VXSGP</identifier>
<datestamp>2018-03-18T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/1HXBCV</identifier>
<datestamp>2018-03-08T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/1NPB8F</identifier>
<datestamp>2018-03-18T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/33NF9Y</identifier>
<datestamp>2018-03-08T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/3TTOWS</identifier>
<datestamp>2018-02-14T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/4813VQ</identifier>
<datestamp>2018-03-18T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/4Z1GAK</identifier>
<datestamp>2018-02-14T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/5NTI0C</identifier>
<datestamp>2018-02-14T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/5O59LD</identifier>
<datestamp>2018-03-08T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header status="deleted">
<identifier>doi:10.18738/T8/6CO7XD</identifier>
<datestamp>2018-03-07T08:00:01Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/7BTM0D</identifier>
<datestamp>2018-03-13T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/7CUCM8</identifier>
<datestamp>2018-03-18T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/7YRHOS</identifier>
<datestamp>2018-02-14T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/8KJA6T</identifier>
<datestamp>2018-02-14T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/8RUKOV</identifier>
<datestamp>2018-03-08T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/9CC4KZ</identifier>
<datestamp>2018-03-18T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/9EBL3A</identifier>
<datestamp>2018-03-10T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/9ON0VB</identifier>
<datestamp>2018-03-18T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/9UXITA</identifier>
<datestamp>2018-02-23T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/9VYDE0</identifier>
<datestamp>2018-03-08T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/9XV8WN</identifier>
<datestamp>2018-03-18T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/A6DIXF</identifier>
<datestamp>2018-02-14T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/A8DMKB</identifier>
<datestamp>2018-02-14T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/ACWIR0</identifier>
<datestamp>2018-03-08T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/AMBBEZ</identifier>
<datestamp>2018-02-13T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/ASJ3RA</identifier>
<datestamp>2018-03-18T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/ASU4TG</identifier>
<datestamp>2018-03-18T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/BBC71O</identifier>
<datestamp>2018-02-14T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/BGPA1O</identifier>
<datestamp>2018-03-18T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/BS0G9T</identifier>
<datestamp>2018-02-14T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/BXB2BI</identifier>
<datestamp>2018-02-14T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/C4EQ3W</identifier>
<datestamp>2018-02-14T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/CKRKJJ</identifier>
<datestamp>2018-02-14T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/CRBUOB</identifier>
<datestamp>2018-03-09T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/CRIWDF</identifier>
<datestamp>2018-02-14T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/CRLHCI</identifier>
<datestamp>2018-03-18T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/CXFO4Y</identifier>
<datestamp>2018-03-08T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/EA4GZC</identifier>
<datestamp>2018-02-14T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/ELAIH3</identifier>
<datestamp>2018-02-28T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/F1IDM3</identifier>
<datestamp>2018-03-18T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/FCZMRZ</identifier>
<datestamp>2018-03-18T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/FKTPIP</identifier>
<datestamp>2018-03-18T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/GGE2PG</identifier>
<datestamp>2018-03-18T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/GVL6ZD</identifier>
<datestamp>2018-03-18T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/H2RTCA</identifier>
<datestamp>2018-03-08T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/H77VLX</identifier>
<datestamp>2018-02-14T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/HJYOT5</identifier>
<datestamp>2018-02-14T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/HKHQGP</identifier>
<datestamp>2018-02-14T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/IAPEY0</identifier>
<datestamp>2018-02-13T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/IQT2DF</identifier>
<datestamp>2018-03-18T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/K2JAWP</identifier>
<datestamp>2018-02-14T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/K6YBV4</identifier>
<datestamp>2018-03-28T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/KGXMXS</identifier>
<datestamp>2018-02-13T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/L1RG0K</identifier>
<datestamp>2018-03-08T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/LHK7DY</identifier>
<datestamp>2018-03-08T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/LWKNHE</identifier>
<datestamp>2018-03-18T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/LXRZZ2</identifier>
<datestamp>2018-03-08T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/MBRE4N</identifier>
<datestamp>2018-02-14T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/N6XE5X</identifier>
<datestamp>2018-02-14T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/NBFBQT</identifier>
<datestamp>2018-03-08T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/NJJAYV</identifier>
<datestamp>2018-02-14T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/NNLYVC</identifier>
<datestamp>2018-02-23T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/O3HV9R</identifier>
<datestamp>2018-03-18T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/OJX6UE</identifier>
<datestamp>2018-03-08T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/OXVTA5</identifier>
<datestamp>2018-02-14T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/P66RQH</identifier>
<datestamp>2018-02-14T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/PJYL8P</identifier>
<datestamp>2018-03-08T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/PLT37J</identifier>
<datestamp>2018-02-14T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/PQ8UMS</identifier>
<datestamp>2018-03-08T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/QKPPM1</identifier>
<datestamp>2018-02-14T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/R6RODU</identifier>
<datestamp>2018-02-14T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/RLTN4P</identifier>
<datestamp>2018-03-14T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/RREJJF</identifier>
<datestamp>2018-03-18T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/RVDCIW</identifier>
<datestamp>2018-02-14T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/SHYF4J</identifier>
<datestamp>2018-03-08T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/SU8RF3</identifier>
<datestamp>2018-03-08T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/SVMBKS</identifier>
<datestamp>2018-03-18T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/ULLYCX</identifier>
<datestamp>2018-03-08T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/V0W5JE</identifier>
<datestamp>2018-03-18T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/V6B9VA</identifier>
<datestamp>2018-02-09T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/VCUJQR</identifier>
<datestamp>2018-03-18T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/VNO1Q6</identifier>
<datestamp>2018-03-18T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/VXATC2</identifier>
<datestamp>2018-02-14T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/WE2CRT</identifier>
<datestamp>2018-03-18T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/WVJ33R</identifier>
<datestamp>2018-02-14T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/XALAED</identifier>
<datestamp>2018-02-14T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/Y95FWM</identifier>
<datestamp>2018-03-02T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header status="deleted">
<identifier>doi:10.18738/T8/Y9LQQC</identifier>
<datestamp>2018-02-23T08:00:01Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/YGGQ10</identifier>
<datestamp>2018-02-14T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/YIRZN9</identifier>
<datestamp>2018-03-18T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/YSSPV0</identifier>
<datestamp>2018-02-26T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/YUIGHP</identifier>
<datestamp>2018-02-14T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/YXFPMD</identifier>
<datestamp>2018-03-08T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/Z4WIUV</identifier>
<datestamp>2018-03-18T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/ZF8QQZ</identifier>
<datestamp>2018-02-14T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/ZHBD9I</identifier>
<datestamp>2018-03-18T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/ZKKW1L</identifier>
<datestamp>2018-03-08T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
<header>
<identifier>doi:10.18738/T8/ZQZNQG</identifier>
<datestamp>2018-03-18T08:00:02Z</datestamp>
<setSpec>TDR</setSpec>
</header>
</ListIdentifiers>
</OAI-PMH>

**Comment by matthew-a-dunlap** [comment]
@kcondon Did you see any log entries that may indicate why the harvest is failing?

**Comment by kcondon** [comment]
@matthew-a-dunlap Everything I know is in the ticket.

**Comment by juancorr** [comment]
Hi @matthew-a-dunlap <https://github.com/matthew-a-dunlap> and @kcondon
<https://github.com/kcondon>,

  In Madrono (e-cienciaDatos) there was a problem with deleted
(deaccessioned) records. The oai requests obtained a null pointer
exception. We had done some changes to complain OpenAIRE requirements and
we do not know if we have create the bug, or the bug is part of original
Dataverse Code. A month ago we have repaired the bug.

  Tomorrow we will install the development Dataverse branch with the new
OpenAIRE dataverse code to check it and we will check if we obtain the null
pointer exception without our code changes.


Juan Corrales

2018-05-14 20:02 GMT+02:00 Kevin Condon <notifications@github.com>:

**Comment by pdurbin** [comment]
@juancorr sounds good since you're looking at pull request #4664 anyway. Thanks!

**Comment by juancorr** [comment]
I have checked the ListRecords request with v4.8.6. and develop branchs and I obtain the same exception.

**Comment by juancorr** [comment]
[XrecordDeleted.patch.txt](https://github.com/IQSS/dataverse/files/2016558/XrecordDeleted.patch.txt)

Here is a patch for the edu/harvard/iq/dataverse/harvest/server/xoai/Xrecord.java file that can repair the bug

**Comment by pdurbin** [comment]
@juancorr great! Do you mind making that patch into a pull request?

**Comment by juancorr** [comment]
@pdurbin , I have created my first pull request to Dataverse . If its correct, Monday I will create the other for the #4664

**Comment by pdurbin** [comment]
@juancorr great! Thanks for making pull request #4691! I'll drag it to Code Review at https://waffle.io/IQSS/dataverse

**Comment by pdurbin** [comment]
At standup I offered to review the pull request and left a comment at https://github.com/IQSS/dataverse/pull/4691#pullrequestreview-121489922 but I'd like @landreev to take a look. Others too, if they feel like it. While I was in there I noticed that we're still using a deprecated method related to #4683 so I'm wondering if we should address that issue now as well. Here's a screenshot of the deprecated method:

![screen shot 2018-05-18 at 12 15 46 pm](https://user-images.githubusercontent.com/21006/40246839-48f16a06-5a98-11e8-967a-5844b86f12a2.png)

**Comment by pdurbin** [comment]
@landreev and I took a look at the pull request and I added some javadoc in 36837f6 to clarify why the fix works, that header.getStatus() is only non-null when it's indicating "deleted". We agreed to go ahead and move this to QA.

**Comment by djbrooke** [comment]
Great! Thanks @juancorr for the PR!

**Comment by kcondon** [comment]
I have tried reproducing the problem before and after the patch but was unable to do so, consistent with my initial testing. I am not sure why but harvest works in the patch so I will merge it. Thanks for the help.

**Comment by juancorr** [comment]
Hi @kcondon , you can reproduce the exception with the next steps. You can start with a Dataverse installation with a Harvester server with less than one hundred dataverses in a set and at least two datasets.
1. Go to the ListRecords URL in your server. Ex: https://edatos.consorciomadrono.es/oai?verb=ListRecords&metadataPrefix=oai_dc&set=openaire_data
2. Select a dataset from the oai response and deaccession it.
3. Execute the "Run Export" action from the "Manage Harvesting Server" page
4. Go to the ListRecords URL again.

Last ListRecords page ends with a not closed <metadata> label and not with </metadata></record></ListRecords></OAI-PMH> 
You will have the javax.servlet.ServletException in the server.log traces too

**Comment by kcondon** [comment]
Thanks @juancorr, I was able to reproduce the bug and saw that it was fixed using your instructions.
