### ISSUE TITLE
Document the complete set of functionality tests for EditDataFiles page 

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#4549]
We've been talking about creating sets of tests for the more complex pages that any developer who ever has to touch the page will have to run, to ensure they are not breaking any existing functionality. 
We decided to start with the EditFiles page. This will serve as an experiment and a proof of feasibility/practicality of the concept. 

This should probably include the scenarios where other pages use functional pieces of this page. For example, the use of editfilesfragment.xhtml by the dataset page, in the Create New dataset mode.

**Comment by pdurbin** [comment]
@landreev can we close this? JSF is on the way out.

**Comment by landreev** [comment]
@pdurbin Sure, let's close it. Otherwise it'll just sit there, being a sad reminder of this failure and guilting us silently.
