### ISSUE TITLE
All APIs should use permissions

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#455]
---

Author Name: **Michael Bar-Sinai** (@michbarsinai)
Original Redmine Issue: 3870, https://redmine.hmdc.harvard.edu/issues/3870
Original Date: 2014-04-22
Original Assignee: Michael Bar-Sinai

---

And, preferably, Commands

**Comment by michbarsinai** [comment]
Closing, as agreed with @scolapasta.
Now that #976 is done, APIs either use permissions or can be blocked.
