### ISSUE TITLE
Upgrade from Solr 4.6.0

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#456]
---

Author Name: **Philip Durbin** (@pdurbin)
Original Redmine Issue: 3871, https://redmine.hmdc.harvard.edu/issues/3871
Original Date: 2014-04-22
Original Assignee: Philip Durbin

---

Right now we are running Solr 4.6.0 but "4.6.1 is strongly recommended, there were a lot of fixes in it and it should be 100% drop-in compatible." -- http://colabti.org/irclogger/irclogger_log/lucene-dev?date=2014-03-17#l139

4.8.0 seems to be a pretty big release with a lot of changes:

Solr - User - [ANNOUNCE] Apache Solr 4.8.0 released - http://lucene.472066.n3.nabble.com/ANNOUNCE-Apache-Solr-4-8-0-released-td4133531.html

4.7.0 seems less major with fewer changes:

Solr - User - [ANNOUNCE] Apache Solr 4.7.0 released. - http://lucene.472066.n3.nabble.com/ANNOUNCE-Apache-Solr-4-7-0-released-td4119816.html

**Comment by pdurbin** [comment]
I just thought I'd mention that when looking into #1332 I did briefly run Solr 4.10.4 (the latest in the 4.x branch) on my laptop and it seemed to work fine with our custom schema.xml.

**Comment by pdurbin** [comment]
I hope that any upgrade to Solr (Solr 5 is out) will also include work toward #2322 about load balancing, fault tolerance, and high availability.

**Comment by pdurbin** [comment]
At this point Sol 6 is out (6.4.0 as of this writing). I don't think we need an issue open to remind us that Solr has regular major releases so I'm closing it.

**Comment by pdurbin** [comment]
#4158 is now the "upgrade Solr" issue.
