### ISSUE TITLE
as a repository operator with users from multiple institutions, I'd like the dataverse affiliation facet to be configurable

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#4560]
In https://github.com/IQSS/dataverse/issues/2040, the "Affiliation" (hybrid of author affiliation and Dataverse affiliation).  This is (almost) easy to re-enable for installations that would like to do so - but it requires code changes and deploying a fork.

From some discussion, it sounds like it might be worth considering a way to handle this particular facet rather than the larger complexity of https://github.com/IQSS/dataverse/issues/2039.

--- 
The "almost" part is uncommenting `solrQuery.addFacetField(SearchFields.AFFILIATION);` in `/SearchServiceBean.java` works as expected, but `dvAffiliation` or `SearchFields.DATAVERSE_AFFILIATION` splits multi-word affiliations into separate facets, and truncates those words.

**Comment by pameyer** [comment]
Continuing investigation - `dvAffiliation` is in solr accurately (not truncated, not split).

**Comment by pdurbin** [comment]
> splits multi-word affiliations into separate facets, and truncates those words

As I mentioned after standup I think you get this behavior from a `text_en` type, for example, but not from a "string" type like this one:

    <field name="dvCategory" type="string" stored="true" indexed="true" multiValued="false"/>

**Comment by pdurbin** [comment]
@pameyer I sure hope I haven't lead you wrong. 😟

**Comment by pameyer** [comment]
Summary for those interested in enabling this behaviour prior to it becoming configurable:

- uncomment `solrFieldsToHightlightOnMap.put(SearchFields.DATAVERSE_AFFILIATION, "Affiliation");` in SearchServiceBean.java
- change `public static final String DATAVERSE_AFFILIATION = "dvAffiliation";` to `"dvAffiliation_ss"` in SearchFields.java
- remove both lines containing `dvAffiliation` from `schema.xml`
- redeploy/reindex as needed
