### ISSUE TITLE
Dataset create failure still resulted in a phantom index

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#4561]
A user attempted to create a dataset, but it did not work (see details below). However, it was still indexed as a "phantom" dataset.

In Harvard production, as a superuser:
https://dataverse.harvard.edu/dataverse/harvard?q=QN2HPG

here is the report:
Yes, the first time I tried to generate this I got a permanent spinning wheel from the site & it never saved/created (I had the tab open for >1h, so this definitely wasn’t a case of me not waiting long enough). Sorry for not reporting, but I was in a rush. This could be purely co-incidental, but I had just used the merge account feature (which is awesome, btw.), so might be related. I believe I was using the latest Firefox on Windows (though I doubt that was a factor), and there were no files attached at the time I was trying to save.

I also received two identical “dataset… was published” e-mails, FWIW. That’s in addition to the original “was created” one.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
