### ISSUE TITLE
Invalid SWORD tutorial link in documentation

### ISSUE THREAD

**Issue by pkiraly** [IQSS/dataverse#4563]
In the http://guides.dataverse.org/en/4.8.5/api/sword.html page there is a sentence:

"For a quick introduction to SWORD, the two minute video at http://cottagelabs.com/news/intro-to-sword-2 is recommended."

At the http://cottagelabs.com/news/intro-to-sword-2 the video is not available, it informs us: "In December 2015 we updated our website and removed a lot of old content. If there is something you are looking for, please contact us and we will put a copy up for you." The website doesn't have a search option, but neither Google, nor DuckDuckGo find any result of SWORD video on the current site. It needs more investigation or contacting with Cottage Lab to get a valid link of the video.

**Comment by pdurbin** [comment]
Ah, bummer. I like that video. Pinging @richard-jones to see if he knows the new URL. Thanks for the bug report, @pkiraly !

**Comment by pkiraly** [comment]
@pdurbin 
I wrote to the Cottage Labs, and Richard Jones answered, that the URL of the video was http://www.youtube.com/watch?v=bJaRl4O4DbA. but seems YouTube deleted it. He tries to figure it out if there is a copy somewhere.

**Comment by pdurbin** [comment]
@pkiraly thanks! Any news?

**Comment by pdurbin** [comment]
@pkiraly should we just delete that sentence with the broken link? Do you want to make a pull request for this?

**Comment by pkiraly** [comment]
@pdurbin yes, why not?

**Comment by pdurbin** [comment]
@pkiraly great! Thanks! While you're in there you could also take a look at #3588 but it would involve some testing.

**Comment by pkiraly** [comment]
@pdurbin I've created the pull request. I also checked #3588, but it won't be a quick task, first I should learn a number of things about how the API is implemented, are there tests etc.
