### ISSUE TITLE
Confusing/misleading error message when file delete fails

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#4564]
When a user tries to delete a draft datafile, and it fails because the associated physical file can't be deleted (for whatever reason), what they see is a succes-styled message that says: 
"Success! The file cannot be deleted."
(adds insult to injury, does it not?)

per support ticket rt #260355

**Comment by pdurbin** [comment]
Related: #4573

**Comment by mheppler** [comment]
Fixed the one line in the `DatasetPage.java` that called `addSuccessMessage` while delivering an error msg from the bundle (`dataset.message.bulkFileDeleteFailure=The selected files could not be deleted.`).

```
if (bulkFileDeleteInProgress) {
                JsfHelper.addSuccessMessage(JH.localize("dataset.message.bulkFileDeleteFailure"));
}
```

Discussed with @landreev about reviewing and testing further since this does not seem to an issue one can replicate in a local file system. He will confirm as part of the code review.

**Comment by landreev** [comment]
Yes, we just confirmed that it's only an issue with S3 - if it's a draft-only file missing from local filesystem, you can delete the datafile without a problem.

**Comment by ferrys** [comment]
@landreev would this affect Swift as well?

**Comment by landreev** [comment]
OK, tested @mheppler 's PR, looks good (see the screenshot). 

![screen shot 2018-04-26 at 3 06 44 pm](https://user-images.githubusercontent.com/737558/39326586-7f68ca48-4963-11e8-8d6e-7da05a6493c4.png)

**Comment by landreev** [comment]
Moved into QA. 
To summarize, for testing: 
- The file must be unpublished, i.e. draft-only. (with published files, we only delete them from versions, w/out trying to delete the physical file). 
- This is NOT an issue with local files (in that our app CAN delete a datafile with a physical local file missing). 
- So this needs to be tested w/ S3. 
- So the scenario is, configure S3, create dataset, upload a file; then remove the file from S3 directly. Try to delete the datafile from the dataset page, by selecting the checkbox, then Edit Files-&gt;Delete. The "before" behavior: message "Success! File(s) cannot be deleted!" The "after" behavior: properly formatted error message - " file(s) cannot be deleted..."
