### ISSUE TITLE
When your account is a builtin account, changing user info only changed the "authenticateduser" table

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#4565]
Steps:
1. Create a built in account
2. Change first name, last name, e-mail
3. Changes are made to "authenticateduser" but not "builtinuser"

In particular, the builtinuser e-mail is what is used for "forgot password" functionality.

**Comment by scolapasta** [comment]
Once thing to consider; when we first created this we treated the builtin (and all authentication providers) like we do with shib in that they are the source of truth for these details.

However, since then we have introduced oauth and user can (and sometimes have to) enter e-mail address via dataverse. All that is needed is some kind of unique token. We may want to consider this here and no longer store anything in builtinuser except for username and password.

**Comment by pdurbin** [comment]
Yes! I would love to remove the following fields from the ``builtinuser`` table:

- affiliation 
- email 
- firstname 
- lastname 
- position 

As @scolapasta indicated, we need to keep these fields:

- username
- encryptedpassword 
- passwordencryptionversion

**Comment by kcondon** [comment]
yup, just discovered this the hard way by changing email.
Btw, THIS IS WHY PASSWORD RESET EMAIL IS NOT SENT/RECEIVED.
I manually set them to be the same in the db and password resent email was then sent correctly. So, it appears that many UI features use the address in authenticateduser table (dashboard, account info, log in detect/ sign up detect) but password reset appears to use the builtinuser table email. So, it you changed it and *then* forgot your password you are SOL.

**Comment by djbrooke** [comment]
Hi @thaorell - is everything moving OK here? Feel free to drop into Slack or post a comment here if you have questions, we're happy to help!

**Comment by thaorell** [comment]
@djbrooke It is going ok. I'm still learning about the code. I have dropped some columns (email and affiliation) and changed the code a bit, they are still giving errors and I am currently working on fixing them

**Comment by djbrooke** [comment]
@thaorell - are you still working on this, or have you moved onto other items? Thanks!

**Comment by djbrooke** [comment]
assigning to @scolapasta  to talk about this at next estimation session

**Comment by pdurbin** [comment]
I just took a look at pull request #4993 and left this comment: "This seems like a good start but shouldn't the fields also be dropped from the BuiltinUser entity? Otherwise they will be present for new deployments."

**Comment by matthew-a-dunlap** [comment]
Since we have decided to remove most of data from builtinuser, what is our expecation of how the api endpoint to create those users should work? 

Can we retire it? Do we need to create a new json format for the info? Do we take the json the same as before but behind-the-scenes process that json manually to populate authenticateduser (right now we rely on serialization to turn the json into a builtinuser).

http://guides.dataverse.org/en/4.9.2/api/native-api.html?create-a-builtin-user

**Comment by kcondon** [comment]
Issues found so far:
1. When logged in as super user (dataverseAdmin) the dashboard link in navbar is missing.
