### ISSUE TITLE
Handle Service

### ISSUE THREAD

**Issue by lbigramUWI** [IQSS/dataverse#4569]
The UWI currently has a dataverse installation at: https://dataverse.sta.uwi.edu 

We added handle service to it, however, when the handle url is clicked while on campus, it resolves to the internal IP address. 
When it is clicked off campus, the site can’t be reached and displays the internal ip addres (192.168....) 

Am I missing some setting somewhere or one that has to be changed to point to the external ip address or server name?

**Comment by pameyer** [comment]
Is it possible that the handle system has the landing page for the identifier configured to be the internal IP (aka - `curl -I http://hdl.handle.net/${handle_identifier}` show the internal IP?

**Comment by lbigramUWI** [comment]
Are you talking about the settings in the config.dct? 

I contacted handle.net and they have verified that all the settings are correct on their end. They seem to think it is a setting in the application.

**Comment by pameyer** [comment]
I'm still trying to understand the problem.  It sounds to me like the landing page for the identifier is set to an internal IP address (which that curl command should be able to confirm or not).  If that's the case, I'd suspect that there's a dataverse setting for communicating with the handle system that's sending the internal address instead of the external address.  But if the landing page for the identifier is set to the correct (publicly facing / external) URL, then trying to track that down wouldn't be likely to fix the problem.

**Comment by lbigramUWI** [comment]
This is the URL it tries to resolve to when I click on a handle identifier in dataverse:

https://192.168.224.83/loginpage.xhtml?redirectPage=%2Fdataset.xhtml%3FpersistentId%3Dhdl%3A20.500.12122%2FNTS0L5

**Comment by lbigramUWI** [comment]
It also tries to resolve to this once logged in. 

http://192.168.224.83/citation?persistentId=hdl:20.500.12122/NTS0L5

**Comment by lbigramUWI** [comment]
Results for: 

curl -I http://hdl.handle.net/${handle_identifier}

HTTP/1.1 200 OK
Server: Apache-Coyote/1.1
Content-Type: text/html;charset=utf-8
Content-Length: 2580
Date: Fri, 06 Apr 2018 13:45:51 GMT

**Comment by pameyer** [comment]
It sounds like either `dataverse.fqdn` or `dataverse.siteUrl` is set incorrectly in `glassfish4/glassfish/domains/domain1/conf/domain.xml`  (http://guides.dataverse.org/en/latest/installation/config.html#dataverse-fqdn).

I'm vaguely surprised that there's no `Location` header in the curl response - thank you for checking.

**Comment by lbigramUWI** [comment]
Okay, I checked the domain.xml, dataverse.siteUrl was missing so I added that but it is still using the internal IP address.

**Comment by lbigramUWI** [comment]
This is what I have: 

<jvm-options>-Ddataverse.fqdn=dataverse.sta.uwi.edu</jvm-options>
<jvm-options>-Ddataverse.siteUrl=https://${dataverse.fqdn}:443</jvm-options>

**Comment by lbigramUWI** [comment]
-Ddataverse.siteUrl=http://${dataverse.fqdn}:80
tried that too but still no luck still resolves to internal

**Comment by pameyer** [comment]
Does it still go to the internal IP address after an update to the dataset is published (or a new dataset is created)?

BTW - if you're using the standard https / http protocols, I'd recommend leaving off the port numbers (they *shouldn't* be necessary).

**Comment by lbigramUWI** [comment]
I just created a new dataset and the handle resolves to the correct thing: https://dataverse.sta.uwi.edu/dataset.xhtml?persistentId=hdl:20.500.12122/XLRSMA 

However, for already existing handles it still goes back to the internal ip address even after updating the dataset.

**Comment by pdurbin** [comment]
I'm not sure if this helps, but that new dataset you created is redirecting (HTTP code 303) to port 80 and HTTP rather than HTTPS:

```
$ curl -i http://hdl.handle.net/20.500.12122/XLRSMA
HTTP/1.1 303 See Other
Server: Apache-Coyote/1.1
Location: http://dataverse.sta.uwi.edu:80/citation?persistentId=hdl:20.500.12122/XLRSMA
```

Since your HTTP certificate seems to be valid, you should probably use the HTTPS version of your site with no port, like this:

-Ddataverse.siteUrl=https://dataverse.sta.uwi.edu

@solhm or @4tikhonov might know how to fix some of these problems since they wrote a lot of the code in pull request #3826.

**Comment by lbigramUWI** [comment]
Thanks @pdurbin  that siteUrl setting works great. Its just to get the previously generated set of handles to do the same thing.

**Comment by pdurbin** [comment]
@lbigramUWI yeah, and that's the part I have no idea about. I've never set up a Handle server myself. :/

**Comment by sekmiller** [comment]
We have an API end point that is specifically for updating the targetURL of the identifier whether it is a DOI or handle

GET http://$SERVER/api/datasets/modifyRegistrationAll?key=$apiKey

The $apiKey you use must have super user status.

**Comment by lbigramUWI** [comment]
@sekmiller I will try this out. Thank you!

**Comment by lbigramUWI** [comment]
Okay, this worked. Thanks to all!

**Comment by djbrooke** [comment]
Great to hear! Thanks @sekmiller @pameyer and @pdurbin for the assistance!
