### ISSUE TITLE
API: pre-populate "Depositor" and "Deposit Date"

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#457]
---

Author Name: **Steve Kraffmiller** (@sekmiller)
Original Redmine Issue: 3872, https://redmine.hmdc.harvard.edu/issues/3872
Original Date: 2014-04-22
Original Assignee: Eleni Castro

---

We are pre-populating Deposit Date and Depositor on the DatasetPage.  There is an issue with how to handle datasets created via the API.  How will we know/handle the possibility that the depositor "Blanks out" the field.

Assigning to Eleni for now to think about use cases.

**Comment by pdurbin** [comment]
@scolapasta said he'd like to think about and look at this ticket.

**Comment by eaquigley** [comment]
This ticket is contingent on #965 being done. Moving it to Beta 15 for the time being.

**Comment by pdurbin** [comment]
> For Depositor: Either put in the admin name for the account, or have a static text that says something along the lines of "API Depositor"

We're going with the former. Datasets are created by users which I think is what @posixeleni meant by "admin name for the account". Basically, we're making SWORD work like the UI where if you're logged in as Sabrina Spruce the "depositor" will be with the last name first like "Spruce, Sabrina".

Passing to QA.
