### ISSUE TITLE
As an admin of another repository system migrating dataset versions to Dataverse, I would like to include existing dataset version numbers so that my version numbers are persistent across repositories

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#4570]
Dataset version numbers are generated by Dataverse and cannot be edited or imported. This is a problem for admins of other repositories who are migrating different versions of datasets into Dataverse and want to maintain the version number that's already in their metadata. The only way for researchers to identify a particular version of a dataset is from the version number, so when the version number changes during a migration, the researcher will have a harder time finding a particular version.

Janet [brought this up in a Google Groups post](https://groups.google.com/d/msg/dataverse-community/qsY8swD9Hh0/zhyxTO81CQAJ), and it's an unresolved comment in the [Dataverse 4.0+ Metadata Crosswalk](https://docs.google.com/spreadsheets/d/10Luzti7svVTVKTA-px27oq3RxCUM-QbiTkm8iMd5C54/edit#gid=0).

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
