### ISSUE TITLE
Use Explore Button when only one Explorer Installed

### ISSUE THREAD

**Issue by kevinworthington** [IQSS/dataverse#4572]
With release v4.8.6 the "Explore" button has changed to a dropdown even if only one External Tool is setup. Would it be possible to replace the dropdown functionality with a simple button when only one External tool has been added?

**Comment by pdurbin** [comment]
The code is so much simpler now I supposed we could consider it. Are you volunteering, @kevinworthington ? 😄 Thanks for creating the first non-Harvard external tool!

**Comment by kevinworthington** [comment]
Hi @pdurbin,
You're most welcome for the tool and yes I'm volunteer to address this issue.

Kevin

**Comment by pdurbin** [comment]
@kevinworthington cool. Assigned! I'm happy to review a pull request. I'll go add this to the "dev efforts from the community" spreadsheet: https://groups.google.com/d/msg/dataverse-community/X2diSWYll0w/ikp1TGcfBgAJ . Thanks!! 💯 👍

**Comment by djbrooke** [comment]
Thanks @kevinworthington for the future PR and @pdurbin for organizing! 💯

**Comment by pdurbin** [comment]
@kevinworthington good timing on pull request #4574 since we have standup right now. I just pulled it into Code Review at https://waffle.io/IQSS/dataverse

**Comment by djbrooke** [comment]
Reviewed with @scolapasta, looks good, moving to QA

**Comment by kevinworthington** [comment]
That's great news. Thanks for the update.
