### ISSUE TITLE
Upgrade to Solr 7.3.0

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#4579]
Solr 7.3.0 was released recently. Since we've not yet cut the release (4.9) that includes our last Solr upgrade (#4158), let's upgrade to the newest version.

**Comment by matthew-a-dunlap** [comment]
Update was confirmed working normally as well as in vagrant and docker-aio.

**Comment by kcondon** [comment]
Solr start message warns about dramatically increasing file descriptors and processes. This did not happen in 7.2.1. This may require a tweak to solr init script:

solr-7.3.0]$ bin/solr start
*** [WARN] *** Your open file limit is currently 1024.  
 It should be set to 65000 to avoid operational disruption. 
 If you no longer wish to see this warning, set SOLR_ULIMIT_CHECKS to false in your profile or solr.in.sh
*** [WARN] ***  Your Max Processes Limit is currently 1024. 
 It should be set to 65000 to avoid operational disruption. 
 If you no longer wish to see this warning, set SOLR_ULIMIT_CHECKS to false in your profile or solr.in.sh
Warning: Available entropy is low. As a result, use of the UUIDField, SSL, or any other features that require
RNG might not work properly. To check for the amount of available entropy, use 'cat /proc/sys/kernel/random/entropy_avail'.

Waiting up to 180 seconds to see Solr running on port 8983 [\]  
Started Solr server on port 8983 (pid=3731). Happy searching!

**Comment by pdurbin** [comment]
@kcondon as we discussed at standup I just merged the latest from develop (including the merged Solr 7.3.0 upgrade) into my metrics branch and deployed it (4527-metrics-api-900973b) to the server we talked about.

**Comment by kcondon** [comment]
index all took 14 hours for prod copy:
4472 dataverses and 81744 datasets indexed. index all took 50754458 milliseconds. Solr index was not cleared before indexing.

Solr index *was* cleared before indexing, despite message.
