### ISSUE TITLE
odd formatting in install guide contents

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#4581]
Big red text jumped out at me when I was looking for something else.

Feel free to close if this is the intended behaviour / display format.

![screenshot from 2018-04-12 15-38-06](https://user-images.githubusercontent.com/10261853/38700294-929c68f0-3e68-11e8-8ba6-61b15f17c365.png)

**Comment by pdurbin** [comment]
Here's the offending line if we'd like to change it from

    ``dataexplore``

to

    "dataexplore"

https://github.com/IQSS/dataverse/blob/v4.8.6/doc/sphinx-guides/source/installation/r-rapache-tworavens.rst#b-rename-the-resulting-directory-dataexplore

**Comment by djbrooke** [comment]
@pdurbin @dlmurphy @pameyer Feel free to just make this small formatting change and move this one along
