### ISSUE TITLE
Changing Sign Up URL should change it in all places where it appears

### ISSUE THREAD

**Issue by Venki18** [IQSS/dataverse#4583]
The sign up url for new sign up can be changed by using the  curl command curl -X PUT -d '/dataverseuser.xhtml?editMode=CREATE' http://localhost:8080/api/admin/settings/:SignUpUrl.
But it only changes the SignUpUrl in the homepage under the menu. The expected behavior is the signup url must be changed at three places, sign up menu, add dataset/dataverse pop up and Request access pop up. 
We are using dataverse 4.8.4 and the problem appears for everyone who is trying to sign up for an account. 

Also please help to update the guide for the following under configuration page
:SignUpUrl
The relative path URL to which users will be sent after signup. The default setting is below.

The word "after signup" is not correct, in fact it is the sign up url.

**Comment by djbrooke** [comment]
Hey @venki18 - thanks for reporting this. We're looking forward to seeing you for the community meeting. We discussed this in sprint planning meeting and I had a quick question before we start on it. 

Just to confirm, are you requesting that updating the URL in the popup when "Add Data" button is clicked and also in the popup when the "Request Access" button is clicked (screenshots attached)?

![Screen Shot 2018-04-25 at 4.30.14 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/577f13fa611c6a0e007ab513/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276456f66b7191a37cf1112b4f5e5b5ecc3c4a4356bcbbd671f3e57862804e0ee8856f5c75903d47afed8a4bec04ec208b4b8de7bddb1ed2f42f67b6d5db1063474f4dcbed5727a19e41c95df44fe7455da6173e63e2712431.png)
![Screen Shot 2018-04-25 at 8.32.59 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/577f13fa611c6a0e007ab513/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5710b77276456f66b7191a370f111294f5a565edd3c4a4356bcbbd671f3e57862804e0ee8856f5c75903d47afed8a4bec04ec208b4b8de7bddb1ed2f42f67b6d5db1063474f4dcbed5727a19e41c95df44fe7455da6173e63e3762431.png)

Can you also provide some information about your workflow for user sign up (and share URLs if appropriate)? Thanks!

**Comment by Venki18** [comment]
Hey @djbrooke I think if the option to change the sign up url is available then it should change the url in all three places like it does when we turn off the sign up url. 

Currently only our institutional members can login through Shibboleth and that is the only way to login. We would like to allow other institutional members who are working with our researchers to request for access to Dataverse. They would use the sign up form (in our case it’s a survey form) to request for access and my colleagues will use the actual Dataverse sign up form to create the account. This would help the Dataverse admins (without access to the servers or API) to create accounts easily and also have control over who can login through local account. Since the workflow is already there once we use the form to create the account the email is triggered automatically and the new user will receive the email to start using it. So without turning off the sign up url I am trying to use this option to redirect them to request for access and hence add the workflow to the system instead of having it off the system.

**Comment by djbrooke** [comment]
Thanks Venki, that's clear!

**Comment by mheppler** [comment]
Added logic for `:SignUpUrl` setting in sign up popups for Add Data btn on dataverse pg, and Request Access btn on dataset and file pgs. Followed the same logic found in the navbar for the Sign Up link.
