### ISSUE TITLE
as a developer, I'd like integration tests to run in a more production like environment

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#4587]
`docker-aio` (and I believe IQSS jenkins) run integration tests directly against glassfish.  The recommendations for production installations is to have apache proxying requests to glassfish; and some problems (my memory is vague on the details here) don't occur with direct connections to glassfish.

**Comment by pdurbin** [comment]
@pameyer had a nice long chat about pull request #4588 this morning. He's going to add a couple comments and then it should be ready to merge.
