### ISSUE TITLE
New DataFile is saved in the database, even when the physical file fails to save!

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#4590]
This appears to be the most important of the new file-related issues identified in production! The other 3 (#4578, #4573, #4564) result in questionable user experience (bad error messages); or leave a mess when a user tries to delete a file they no longer need. This one has direct implications for data integrity - making it look like a file has been added to the dataset, even though it failed to be saved physically!

The simplest way to reproduce the condition is to force the S3AccessIO savePath() method (called from IngestServiceBean) to throw an IOException. Just insert this into the method: 
```
    if (true) {
            logger.info("throwing a monkey wrench into the things!");
            throw new IOException("throwing a monkey wrench into the things!");
        }
```
Upload a file. Save it. It will be saved in the database - but not on S3. The datafile will appear on the dataset page, but attempting to download it will result in error. 

Should be a simple-ish fix in IngestServiceBean. A successful save there sets the boolean savedSuccess to TRUE. It's just that we appear to never check it later on (!) - and proceed to persist the datafile in the database anyway. 

NOTE: S3 is used in the example above, because that's what we are using in prod. But the issue does not appear to be S3 specific in any way. If the FileAccessIO.savePath() method fails to save the file and throws an IOException, it will be (mis)handled the same way, and result in the same condition!
But it's probably because of the fact that writing on S3 is more likely to fail (by virtue of having to do it over the network), that we've started seeing this as of late.

Also note that this is not the same issue as #4578 (handling of S3 exception). Once again, we are throwing a generic IOException - that the method is supposed to throw, when things go wrong. #4578 is about S3-specific exceptions that are not properly intercepted, thus resulting in the StorageIO methods bombing with RunTime exceptions, instead of throwing IOExceptions.

**Comment by landreev** [comment]
The comment below is buried in the TL;DR initial description. Adding it here on its own, for clarity: 
Should be a simple-ish fix in IngestServiceBean. A successful save there sets the boolean savedSuccess to TRUE. It's just that we appear to never check it later on (!) - and proceed to persist the datafile in the database anyway.

**Comment by pameyer** [comment]
@landreev did you notice if the checksum for the (database) file matches what the physical file should have had?

**Comment by landreev** [comment]
@pameyer a very good question
Yes, the md5 is correct. And that's because we are doing it wrong. We calculate it before we attempt to save the file permanently, and then save it in the database. 
OK, we calculate it before we do anything else with the file for a reason - to determine that the file is not in the dataset already. But a clean/accurate way of handling it would be to re-read the file once it's saved, recalculate the md5, compare to the previously calculated - and only then save.

**Comment by landreev** [comment]
@sekmiller @kcondon 
Stephen, Kevin has just merged my #4578 (handling of S3 exceptions). Please sync up your working branch with develop, since it's related to this issue in some way. 

For example, if you modify the authentication key in your ~/.aws/credentials file, as to make it invalid, and try to upload a file, before these fixes in #4578, it would result in a messy exception strack trace in the server log; and some unpredictable behavior further down. 
Now it will result in a clean IOException, which you can then intercept and abort adding the file to the dataset. 

Please let me know if you have any questions...

**Comment by landreev** [comment]
Nobody appears to be working on this one, so I'm taking it. 
This may be the most pressing/urgent thing in flight right now; and I'm fairly positive I can move it to ready fairly quickly.

**Comment by landreev** [comment]
OK, so this needs to be synced up with devlop before it can be QAed; and I may pull it back into develop to resolve any merge conflicts, if it looks like it's a project... 
But I'll wait for the test suite problem in ids-for-files to be resolved first.

**Comment by landreev** [comment]
(I dragged it back to dev. since I'm working on syncing it up to develop - since develop was fixed yesterday; it'll hopefully be a quick thing and it'll be back in QA later today)

**Comment by landreev** [comment]
I just committed the changes I made last week, syncing the branch with develop. It is all working now with everything added in the global-ids-for-files branch and ready for QA.

**Comment by kcondon** [comment]
Works great with the exception of adding prov file to failing file, results in log file and grayed out UI.

**Comment by landreev** [comment]
I've dragged this back into the dev. column temporarily, to address the less-than-graceful failure condition when a provenance metadata file is added to the mix.

**Comment by landreev** [comment]
Added provenance-related checks. Synced up w/ develop. 
Back in QA.
