### ISSUE TITLE
Saving a draft dataset results in two resolving requests for the 'new' identifier and the first time it is using 'null' as identifier string

### ISSUE THREAD

**Issue by PaulBoon** [IQSS/dataverse#4602]
We are using handle and because of handle related problem I had a close look at the handle logs. 
This is what happens in the handle access log when I push the ‘Save Draft’ button for a dataset on a test machine.
 
192.168.33.36 HTTP:HDL(2.10) "2018-04-18 19:34:53.140Z" 1 100 244ms  12345/null
192.168.33.36 HTTP:HDL(2.10) "2018-04-18 19:34:53.255Z" 1 100 91ms  12345/W6NCHD
192.168.33.36 HTTP:HDL(2.10) "2018-04-18 19:34:53.392Z" 400 1 24ms  /
192.168.33.36 HTTP:HDL(2.10) "2018-04-18 19:34:53.412Z" 100 402 1ms adm=300:12345/ADMIN 12345/W6NCHD
192.168.33.36 HTTP:HDL(2.10) "2018-04-18 19:34:53.474Z" 200 1 32ms adm=300:12345/ADMIN /
 
The second line is a resolving request for the handle that is about to be registered (to test uniqueness I guess), but he first line looks like a programming flaw.

I inspected the code (4.8.6) and discovered that this is happening in CreateDatasetCommand.execute

First it is calling generateDatasetIdentifier which leads to a call to IdServiceBean.alreadyExists with a 'null' as identifier. 
Then it does a more explicit check by calling isIdentifierUniqueInDatabase which also leads to IdServiceBean.alreadyExists but then with a correct identifier string. 

Maybe DatasetServiceBean.isIdentifierUniqueInDatabase should only do the database check as its name suggests?

**Comment by PaulBoon** [comment]
Ok, maybe alreadyExists should take an identifier instead of a dataset, because the dataset.identifier can be null. Then we have to change the implementation.

**Comment by pdurbin** [comment]
@PaulBoon hi! I feel like this might be a good thing for you to coordinate with @fbgesis and @scolapasta on. Over at #4106 they are working on making the persistent ID code modular and maybe this improvement could be rolled into that effort.

Also, we are actively working on code related to persistent identifiers in pull request #4350 so you might want to check the code in that branch to see if there have been changes in the parts of the code you're referencing.

Thanks for bringing this issue to our attention!

**Comment by pdurbin** [comment]
Possibly related to #5427 according to some discussion at http://irclog.iq.harvard.edu/dataverse/2019-01-03#i_83876

**Comment by pdurbin** [comment]
@PaulBoon https://dataverse.nl switched to DOIs, right? Are you still interested in this? Thanks!

**Comment by PaulBoon** [comment]
@pdurbin, Yes, its OK to close. It is not critical anyway, otherwise there would be complaints from others about this.

**Comment by pdurbin** [comment]
@PaulBoon yeah, I agree. Thanks! Closing!
