### ISSUE TITLE
Rsync: File upload not completing due to lock error when adding package.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#4605]
While testing the multiple storage PR https://github.com/IQSS/dataverse/pull/4585 , discovered that the rsync file upload process has stopped working. It gets hung up trying to add the package to the dataset with a lock error. File is processed into a package directory so that part worked. Batch error log:
INFO: Job ID = 67
INFO: Job Name = FileSystemImportJob
INFO: Job Status = STARTED
INFO: Dataset Identifier (datasetId=40): ZX5GAA
INFO: User Identifier (userId=dataverseAdmin): @dataverseAdmin
INFO: Import mode =  MERGE
INFO: Checksum type = SHA1 (FileSystemImportJob.xml property)
INFO: Checksum manifest = files.sha (FileSystemImportJob.xml property)
INFO: Reading checksum manifest: /usr/local/glassfish4/glassfish/domains/domain1/files/10.5072/FK2/ZX5GAA/ZX5GAA/files.sha
INFO: Checksums found = 1
INFO: Size parameter supplied: 72
INFO: Reading dataset directory: /usr/local/glassfish4/glassfish/domains/domain1/files/10.5072/FK2/ZX5GAA/ZX5GAA (excluding: *.DS_Store,* .sha, *.cached)
INFO: Files found = 1
INFO: Successfully created a file of type package
SEVERE: CommandException updating DatasetVersion from batch job: Dataset cannot be edited due to dataset lock.
INFO: Files read  = 1
SEVERE: Job Failed. See Log for more information.

**Comment by pdurbin** [comment]
If it helps, b2cf086 is where I added that "Dataset cannot be edited due to dataset lock" error in 4.8.2. @pameyer I believe you're running 4.8.1.

**Comment by pameyer** [comment]
@pdurbin Thanks between 4.8.2 and 4.8.1 releases is a good starting point.  We're running a hybrid that's got some 4.8.3 features in it as well.

**Comment by pameyer** [comment]
Remembered that this was working sufficiently in Jan to find file PID / package file issues https://github.com/IQSS/dataverse/issues/2438#issuecomment-362015165.

Needs more investigation.

**Comment by pameyer** [comment]
Reproducible in fresh branch off develop from 747b83c32378eab49fea2690a349a43447820db6 .  Didn't mention which commit I was checking in file PID branch, but 16c4ece8f8eeadec41190ea06b327bf3d09b9031 looks to be a reasonable starting place.

Stock DV install, stock DCM install; docker-aio extended w\ docker-compose for DCM system testing (still a rough edge or two to file off there).

**Comment by pameyer** [comment]
Attempting to narrow down source of error: create via API, download script via UI results in the uncleared lock on DCM success API call (aka - this path shows the bug).  create via UI, download script via API does not result in uncleared lock on DCM success API call (aka - this path does not show the bug).

Suggests that the difference is in `DatasetPage.downloadRsyncScript()` called as the `rsyncDL` actionListener.

**Comment by pameyer** [comment]
Potential for https://github.com/IQSS/dataverse/issues/4614 to be useful for addressing this.

**Comment by pameyer** [comment]
I think another developer should take a look first - the duplication messages look like something that will only effect administrative users, so I don't think fixing them is high priority.
