### ISSUE TITLE
As an installation admin, I need dataverse creators to categorize their dataverses correctly so that I can measure how people are using certain types of dataverses

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#4607]
We expect dataverse creators to use the "Journals" category if the dataverses will be managed by or for journals.

<img width="551" alt="screen shot 2018-04-22 at 6 16 31 pm" src="https://user-images.githubusercontent.com/18374574/39100485-5ea6ac42-4659-11e8-9596-fa798e1cca4e.png">

But on Harvard Dataverse, more than half of the dataverses created with the "Journals" category were not created or managed by journals. For most, the "Research Project" or "Researcher" category was more appropriate, and those dataverses' datasets were associated with articles that the creators had or planned to publish in journals.

Harvard Dataverse admins use the number of "Journal" dataverses to measure journal adoption of the repository, and miscategorized dataverses makes it difficult to measure.

Before I edited these 50+ dataverses, I emailed the creators to let them know I would be changing the categories and to ask why they chose the Journal category. Most who answered said they chose that category because they had to share the data associated with their journal articles, so the category seemed appropriate.

Some other questions to consider:
- What do Dataverse visitors expect to find when clicking on the "Journals" facet? (Google Analytics says people on Harvard Dataverse click it very rarely.)
<img width="294" alt="screen shot 2018-04-22 at 6 23 53 pm" src="https://user-images.githubusercontent.com/18374574/39100623-5a2744b4-465a-11e8-8607-ba0dc1fcd81b.png">

- Are the number of dataverses with other categories, such as "Researcher", "Organization or Institution", - used? How are they used? For example, do we plan to use the number of "Researcher" dataverses to measure how often researchers create their own dataverses? And how accurate are those numbers now?

**Comment by TaniaSchlatter** [comment]
One small chunk is to take on the Journal use case as a starting point for addressing more categories. I can see creating a basic poll or questionnaire to get input on possible alternative, more granular categories, like Journal-published or Journal-manged, for example.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
