### ISSUE TITLE
Info Message Block - Fix format/style issue (see: trailing hyphen)

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#4608]
On multiple pages that use the blue info message block at the top of the page, incorrectly pass the message text from the bundle via the backing bean to the message block in the XHTML. You can tell by the trailing hyphen at the end of the text, and the bold styling applied to the entire message text.

_Upload File pg_
![screen shot 2018-04-23 at 3 19 25 pm](https://user-images.githubusercontent.com/687227/39149269-8b822210-470c-11e8-9937-8fe5b351fee7.png)

_Edit Dataset pg_
![screen shot 2018-04-23 at 3 40 29 pm](https://user-images.githubusercontent.com/687227/39149314-ae2f07a6-470c-11e8-8bf3-654c2451d469.png)

_Edit Terms pg_
![screen shot 2018-04-23 at 3 40 58 pm](https://user-images.githubusercontent.com/687227/39149348-c1ba107c-470c-11e8-9d38-86b9a31526ec.png)

_Manage Dataset Templates pg_
![screen shot 2018-04-23 at 3 48 55 pm](https://user-images.githubusercontent.com/687227/39149641-dbddf7c4-470d-11e8-83fc-4f79714b8c21.png)

_Create Account pg_
![screen shot 2018-04-23 at 3 51 20 pm](https://user-images.githubusercontent.com/687227/39149756-31429828-470e-11e8-9d61-a3332d8ed3cd.png)

Some other pages with other minor formatting issues (two hyphens)...

_Manage Harvesting Clients pg_
![screen shot 2018-04-23 at 3 53 49 pm](https://user-images.githubusercontent.com/687227/39149870-89d102c2-470e-11e8-9692-2373428d71e4.png)

_Manage Harvesting Server pg_
![screen shot 2018-04-23 at 3 54 21 pm](https://user-images.githubusercontent.com/687227/39149904-9c5799b0-470e-11e8-9668-3544a3ffc9c5.png)

_Submit for Review workflow, Dataset pg_
<img width="1165" alt="screen shot 2018-11-28 at 5 49 38 pm" src="https://user-images.githubusercontent.com/687227/49187608-14f23000-f336-11e8-88f8-e477a849c258.png">

Backwards label and message formatting issue...

_Publish/Register file persistent identifiers workflow, Dataset pg_
<img width="1183" alt="screen shot 2018-11-28 at 5 05 03 pm" src="https://user-images.githubusercontent.com/687227/49185443-f6893600-f32f-11e8-8513-2a6fb65cc75b.png">

Success or validation error messages don't appear to be a problem...

![screen shot 2018-04-23 at 3 22 35 pm](https://user-images.githubusercontent.com/687227/39149249-7e7e1af6-470c-11e8-9d2d-5807cc52cbcc.png)

![screen shot 2018-04-23 at 3 24 01 pm](https://user-images.githubusercontent.com/687227/39149259-836dd722-470c-11e8-8d73-f26941765c99.png)

Example of pages that do have the blue info message block formatted properly include...

_Manage Dataset Guestbooks pg_
![screen shot 2018-04-23 at 3 45 59 pm](https://user-images.githubusercontent.com/687227/39149553-7266a76e-470d-11e8-81b4-ff0ba50795c4.png)

```
        if(totalResponses.intValue() > 0){
            displayDownloadAll = true;
            FacesContext.getCurrentInstance().addMessage(null, 
                    new FacesMessage(FacesMessage.SEVERITY_INFO, 
                            JH.localize("dataset.manageGuestbooks.tip.title"), 
                            JH.localize("dataset.manageGuestbooks.tip.downloadascsv")));

        }
```

_Edit Dataverse pg_
![screen shot 2018-04-23 at 3 50 07 pm](https://user-images.githubusercontent.com/687227/39149707-05aa40e4-470e-11e8-8df7-021f9ad2dd7e.png)

_Password Reset pg_
![screen shot 2018-04-23 at 3 52 20 pm](https://user-images.githubusercontent.com/687227/39149802-54ec3cb6-470e-11e8-9db5-47c2fd5c6506.png)

There are other instances found in backing beans while searching through the project, that I could not get to display in the UI, but should still be reviewed. For example the following message in `DatasetPage.java` has `SEVERITY_INFO`, but the message text is not in the bundle, and it reads like it should be more of a warning or an error, rather than info text.

```
FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO, "DataverseNotReleased", "Only authenticated users can release a dataverse.");
```

While there is an existing issue #3865 for a holistic review of message text and visual styles that has been open for nearly a year, I propose that this issue is different in that it suggests we at least use the existing message framework properly, which require only minor improvements to the bundle text and/or backing bean.

**Comment by markrlondon** [comment]
I agree with mheppler.   A recent Dataverse user here asked me what the message "Register/update file persistent identifiers workflow in progress – Publish workflow in progress" meant.   It's confusing and the user (and myself) didn't at first realize that it's simply a status warning.   We thought that it was an error message.

**Comment by mheppler** [comment]
Fixed format and hyphen issues related to dataset warning msgs for Submitted for Review and Publish in Progress workflows as part of #4403.

![screen shot 2018-12-03 at 5 13 53 pm](https://user-images.githubusercontent.com/687227/49404903-d508bf80-f71e-11e8-80e9-3c5bc5c4e92e.png)

![screen shot 2018-12-03 at 5 14 54 pm](https://user-images.githubusercontent.com/687227/49404983-231dc300-f71f-11e8-9e22-86f6e9bbd0fb.png)

**Comment by mheppler** [comment]
Fixed the formatting of these alert info msg...

- [x] Upload Files
- [x] Edit Dataset
- [x] Edit Terms
- [x] Manage Dataset Templates (...also revised text)
- [x] Create Account pg
- [x] Manage Harvesting Clients
- [x] Manage Harvesting Server
- [x] Submit for Review workflow, Dataset pg
- [x] Publish/Register file persistent identifiers workflow, Dataset pg

![screen shot 2018-12-20 at 2 41 38 pm](https://user-images.githubusercontent.com/687227/50307665-114e5680-0467-11e9-8082-0259925c8797.png)

![screen shot 2018-12-20 at 2 33 28 pm](https://user-images.githubusercontent.com/687227/50307671-157a7400-0467-11e9-8598-14ae4d707336.png)

![screen shot 2018-12-20 at 2 33 06 pm](https://user-images.githubusercontent.com/687227/50307680-19a69180-0467-11e9-80f7-bb678c497a7b.png)

**Comment by kcondon** [comment]
@mheppler I will test the trailing hyphen mentioned as the purpose for this ticket but it looks like you changed the actual messages on a bunch of alerts as well.
