### ISSUE TITLE
Create dataset/dataverse links: Extend to API

### ISSUE THREAD

**Issue by ferrys** [IQSS/dataverse#4619]
As a dataverse superuser, I would like to be able to create a link between a dataset/dataverse and another dataverse via the Native API so that I do not have to use the UI.

**Comment by kcondon** [comment]
I tested this and it works. Awaiting verdict for test api issues.

**Comment by djbrooke** [comment]
Thanks @landreev for taking a look at the failing tests as discussed in standup. 

@ferrys if instead, you'd prefer to take this on in the next few days, let us know and we'll pick up something else.

**Comment by landreev** [comment]
I'm looking at the API issue, yes.

**Comment by landreev** [comment]
Fixed the test, moving back into QA.
