### ISSUE TITLE
API Guide: Document how to set facets for a dataverse

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#4628]
Over in #3440 I noticed that @pameyer listed "setting facets for a dataverse" as something that's not possible via API. I was confused about this myself and had explained the GUI way to set facets at http://guides.dataverse.org/en/4.8.5/developers/dev-environment.html#rebuilding-your-dev-environment but it's actually been possible for a long time. In c13bf08 some Javadoc was added to explain how to set facets via API, which is great, but it should be added to the API Guide.

**Comment by pameyer** [comment]
@pdurbin good catch; I had it as an issue, figured out the undocumented API, and didn't update the issue.
