### ISSUE TITLE
Piwik - Counting downloads

### ISSUE THREAD

**Issue by Venki18** [IQSS/dataverse#4630]
Piwik integration with Dataverse allows tracking of usage but the download links are not tracked by Piwik by default. As the download button for Dataverse is set up as HTML button type and not as hyperlink the downloads are not counted. In order to have the downloads counted, we need to include the following code in the javascript file. 

// now all clicks on links with the css class "download" will be counted as downloads

// you can also pass an array of strings
_paq.push(['setDownloadClasses', "download"]);

_paq.push(['trackPageView']);

The button for download should include the class **piwik_download** as shown below

```
<button type="button" class="btn btn-default dropdown-toggle piwik_download" data-toggle="dropdown" aria-expanded="false">
            <span class="glyphicon glyphicon-download-alt"></span> Download <span class="caret"></span>
        </button>
```

Please refer to the following Piwik guide for more information on this

https://developer.matomo.org/guides/tracking-javascript-guide#recording-a-click-as-a-download

**Comment by djbrooke** [comment]
Thanks for the report @Venki18. Piwik support was added by an external contributor and we may need to get up to speed on this, but it looks easy.

**Comment by djbrooke** [comment]
Hi @venki18 - we discussed this in sprint planning today and we'll want to pursue a more scalable solution instead of one that's specific to Piwik. I'm going to close this, but @mheppler is going to create another scalable issue and will link here.

**Comment by mheppler** [comment]
The improvements to tracking analytics have been outlined in _Custom Analytics - More than just pageviews #4660_. These changes will allow sysadmin's to customize their analytics tracking code as they wish, as system configuration settings, similar to how branding works. We have also added a new event style class naming convention to end user action buttons, to allow for more tracking analytics than just pageviews.
