### ISSUE TITLE
Publish Dataset - custom pop up text

### ISSUE THREAD

**Issue by Venki18** [IQSS/dataverse#4652]
The custom pop up text UI doesnt show the complete text when the text is more than 1024 characters. Please refer to the screenshot below
<img width="907" alt="image" src="https://user-images.githubusercontent.com/19611506/39750259-5b715e2e-52e7-11e8-930b-9e82fca41be8.png">

It would be good if the UI can be set to resize according to the length of the text so that people dont miss the text that is hidden from view.

**Comment by djbrooke** [comment]
Thanks, we'll take a look @Venki18.

@sbarbosadataverse Did we work on this related to a report that you made recently? I thought I remembered this, but I can't find anything about it.

**Comment by pdurbin** [comment]
I created pull request #5269 which should also be a fix for #2669.
