### ISSUE TITLE
as a researcher, I'd like XML exports to have a recommended XML header

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#4657]
https://groups.google.com/forum/#!topic/dataverse-community/cJBHnxCaHWU

Short version: no ` <?xml version="1.0" encoding="UTF-8"?>` on some XML exports, even though content-type of response is set to XML.

**Comment by djbrooke** [comment]
We discussed this in Sprint Planning today, the team will review and provide feedback this sprint. Moving to Code Review column.

**Comment by kcondon** [comment]
- [ ] Harvesting ddi format fails with unexpected character:
[2018-05-11T17:07:36.393-0400] [glassfish 4.1] [SEVERE] [] [] [tid: _ThreadID=200 _ThreadName=Thread-9] [timeMillis: 15260728
56393] [levelValue: 1000] [[
  edu.harvard.iq.dataverse.api.imports.ImportException: Failed to process DDI XML record: class com.ctc.wstx.exc.WstxUnexpect
edCharException (Unexpected character ' ' (code 32); expected "?>" end marker
 at [row,col {unknown-source}]: [1,38])
        at edu.harvard.iq.dataverse.api.imports.ImportServiceBean.doImportHarvestedDataset(ImportServiceBean.java:236)

**Comment by landreev** [comment]
(I don't think I should be the owner of this one)
@pameyer OK, I thought about it - let's try and address it by only providing this header in the XML formats we are offering to the users ("ddi", "dcterms"); but NOT in the formats that are used for harvesting only ("oai_ddi", "oai_dc"). 
For ex., for the DDI, the xmlw.writeStartDocument() line should not be in the d2ddi() method.

**Comment by pameyer** [comment]
Updated w\ develop, HarvestingServerIT fails (in addition to SwordIT failure expected given current stage of develop).

**Comment by pameyer** [comment]
Checked before merge w\ develop (c9d8f5c1cba040d82b78ecff28c97f10c3195904); HarvestingServerIT passes successfully.  Possibly file-PIDs changed harvesting behavior, possibly something else.  Recheck this test individual on develop (although  ``conf/docker-aio/run-test-suite.sh`` was not reporting failures earlier); cccaf77029eb5e8a8c1030f1b642872e2b6824fc passes HarvestingServerIT individually.

switch back to 97dcb8165ff2cc910e8742cc6fc119f4924a0f4f (this branch, after merge) - HarvestingServerIT passes individually prior to setting JVM option for dataverse.siteUrl (which is needed for the private url test).  After setting dataverse.siteUrl, HarvestingServerIT fails individually (but not reproducibly - 2nd, 3rd calls on container succeed).

Needs more investigation - HarvestingServerIT should either pass or fail deterministically, which is currently not the case.

**Comment by pameyer** [comment]
This morning HarvestingServerIT is passing reproducibility, and was unable to get it to fail. Suggests I typo'd something in my test environment yesterday; moving back to QA.
