### ISSUE TITLE
remove direct ejb calls from rendered attribute in searchIncludeFragment.xhtml 

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#4663]
in searchIncludeFragment.xhtml:

<ui:fragment rendered="#{!dataverseSession.user.authenticated and (permissionServiceBean.userOn(AuthenticatedUsers:get(),SearchIncludeFragment.dataverse).canIssueCommand('CreateDataverseCommand')
                                         or permissionServiceBean.userOn(AuthenticatedUsers:get(),SearchIncludeFragment.dataverse).canIssueCommand('CreateNewDatasetCommand'))}">

Calling ejbs directly in xhtml can be expensive so we should remove these calls to permissionsWrapper where we can call ejb and cache for the view.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
