### ISSUE TITLE
Chrome audit tools flagging JQuery & Bootstrap versions as vulnerable

### ISSUE THREAD

**Issue by kaitlinnewson** [IQSS/dataverse#4667]
Hi Dataverse team,

After running the Chrome audit tools for 'best practices', the versions of Bootstrap and JQuery/JQuery UI are flagged as having security vulnerabilities in Dataverse 4.8.6 (tested in both Scholars Portal instance and Harvard instance). Here's an example of the audit result:

![screen shot 2018-05-14 at 2 12 51 pm](https://user-images.githubusercontent.com/6903515/40015625-f896c11e-5781-11e8-9816-8046f73324ad.png)

Maybe it's not a big deal, but I thought it should be flagged in case you're not already aware of it.

**Comment by mheppler** [comment]
Thank you for opening this issue, @kaitlinnewson. We have opened issues to upgrade our UI components, PrimeFaces #4220 and Bootstrap #4219. (While those are separate issues, we would most likely tackle them together in one release.)

Looking through the documentation for the latest versions, PrimeFaces 6.2 uses jQuery v3.2.1 and jQuery UI v1.12.1, while Bootstrap 4.0 also uses jQuery v3.2.1.

We have also been looking at the audit tool in recent development, but if you have any other interesting findings, please feel free to share them!

**Comment by kaitlinnewson** [comment]
Thanks for the quick response Michael! I'll be sure to let you know if I find anything else.
