### ISSUE TITLE
Internationalization : Move English strings from xhtml to bundle.properties, Phase 2

### ISSUE THREAD

**Issue by JayanthyChengan** [IQSS/dataverse#4672]
Creating new issue to handle more English strings noticed by Michael from Xhtml files and commented in the previous issue : https://github.com/IQSS/dataverse/issues/4634 

/src/main/webapp/dataset-versions.xhtml [Line 27, 42] -- javascript, display:none
/src/main/webapp/dataset.xhtml [Line 471] -- display:none
/src/main/webapp/dataverse_header.xhtml [Line 20] -- toggle nav
/src/main/webapp/dataverse_template.xhtml [Line 56] -- default body
/src/main/webapp/dataverseuser.xhtml [Line 533] -- Password/New Password label attribute

/src/main/webapp/editdatafiles.xhtml [Line 70] -- KB
/src/main/webapp/file-versions.xhtml [Line 27, 41] -- javascript, display:none

/src/main/webapp/harvestclients.xhtml [Line 78] -- Filter
/src/main/webapp/harvestsets.xhtml [Line 104] -- Filter

/src/main/webapp/loginpage.xhtml [Line 162, 197] -- shib:no javascript, ORCID
/src/main/webapp/permissions-manage-files.xhtml [Line 53, 99] -- requests, users/groups
/src/main/webapp/roles-edit.xhtml [Line 74] -- cancel

/src/main/webapp/superuser.xhtml [Line 23, 26] -- index all, check status

- As Gustavo mentioned in the PR: https://github.com/IQSS/dataverse/pull/4643, Encoding won't be moved to bundle.properties

/src/main/webapp/editFilesFragment.xhtml [Lines 402-542] -- Select Language Encoding...

- Also planning to handle javascript in separate issue.
/src/main/webapp/resources/js/mydata.js [Line 318-322] -- View Next... Results...

**Comment by pameyer** [comment]
Some of these look to me like HTML elements or CSS properties (`javascript`,`display:none`); suggesting that it might not be desirable to internationalize them.

**Comment by mheppler** [comment]
@pameyer the outline above is copied from my comment on a previous PR and includes my (_very_ vague) notes about what needs to be addressed. For example, the "javascript" note points out this snippet of javascript from the `file-versions.xhtml` file that includes the text "Loading versions...".

```
    <script type="text/javascript">
        /* Version tab: Retrieve data after page load */
        $(document).ready(function () {
            preload_message = "(Loading versions...)";
            $('#fileForm\\:tabView\\:versionsTable_data tr.ui-datatable-empty-message td').text(preload_message);
            
        });
    </script>
```

**Comment by mheppler** [comment]
@JayanthyChengan if you need any additional information to clarify my vague notes, please let me know!

**Comment by mheppler** [comment]
Provided some feedback to @JayanthyChengan in a comment on the PR #4678.

Also wanted to point out that a few of the javascript text examples outlined above, were moved into a new issue *Internationalization : remove English static strings from javascript files #4679*, and another issue was also created for examples in the java manage beans, *Internationalization : remove English static strings from Java files to bundle.properties #4680*.

**Comment by djbrooke** [comment]
Thanks @mheppler!

@JayanthyChengan I saw you made a few commits on the PR - is this ready for another round of review?

**Comment by djbrooke** [comment]
Hey @JayanthyChengan - we're starting to test this. Before we get too far, it would be helpful to know if you have any test cases (or any thoughts on how to test this in general). Thanks!

**Comment by kcondon** [comment]
@JayanthyChengan I noticed one issue on login page. When you reference the bundle string you left off the bundle syntax:
```
<h:outputText value="#{auth.providers.orcid.helpmessage1}"

<h:outputText value="#{auth.providers.orcid.helpmessage2}"
```

**Comment by djbrooke** [comment]
@JayanthyChengan I'm moving this one back to development, let us know when it's all set for us to take another look!

**Comment by JayanthyChengan** [comment]
@kcondon : thanks, corrected it.  It's ready for testing.

**Comment by djbrooke** [comment]
@scolapasta and I discussed this. For this PR, code review (and the feedback acted on by @JayanthyChengan) is the big chunk of verification that we want to do. For QA, I suggest timeboxing at 15-20 minutes for a quick check of basic functionality before merging.
