### ISSUE TITLE
Spike: Establish a component software version support policy and express it clearly in guides

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#4681]
With recent changes in both internal and external support for components of the dataverse architecture, it seems like a good idea to think more broadly about how we support past, current, and future versions of components of the dataverse architecture and communicate it to our community and users, especially in the guides.

Recent changes:
1. Change of hosting of Harvard Dataverse to AWS and attendant version upgrade requirements to conform to security norms.
2. Change of support for Postgres by Amazon RDS
3. Change in emphasis from supporting CentOS 6 to CentOS 7 and default packages available for those platforms.
4. Aging of existing production and dev versions, making them less relevant or more difficult for new installations to support given general patch practices.

Specific component changes:
1. Upgrade Solr from 4.6 to 7.x (7.3?)
2. Upgrade Postgres to v9.4+ due to Amazon RDS support change (10 recommended)
3. Upgrade to glassfish 5 (proposed)
4. Upgrade to Java 9 (proposed)

Changes to supported versions due to component changes:
1. Identify Harvard's specific version use (de facto supported)
2. Identify partner installation version use (provisionally supported)
2. Identify most common in use versions as likely in demand and conforming to security policy and their lifespans. (potentially supported)
3. Identify no longer supported versions by vendor, either by patch or support policy with timeframes and cycle times for general planning and communication. (no longer supported or at best effort support with likely no dev work for fixes available, case by case basis).

**Comment by pdurbin** [comment]
See https://guides.dataverse.org/en/6.0/developers/dependencies.html
