### ISSUE TITLE
Internationalization : redesign the architecture to handle metadatablocks 

### ISSUE THREAD

**Issue by JayanthyChengan** [IQSS/dataverse#4684]
Have to figure out, how internationalization will be handled for the files under scripts/api/data/metadatablocks, so that new dynamic content, like domain metadata fields, can be added to the application and available in all languages.

**Comment by pameyer** [comment]
@JayanthyChengan It may make sense to have internationalization handled separately, but I'd be curious to have your input on how it might fit into something like https://github.com/IQSS/dataverse/issues/4451.

**Comment by 4tikhonov** [comment]
I've managed to get all metadata fields translated in French
<img width="1156" alt="screen shot 2018-09-27 at 9 29 36 pm" src="https://user-images.githubusercontent.com/704075/46171272-56b41b00-c2a0-11e8-8089-04afb4183175.png">

I can share my solution if the same functionality isn't coming with new release.

**Comment by JayanthyChengan** [comment]
Hi @4tikhonov :  Thanks.  
I was able to get the output and I committed the code to 
https://github.com/scholarsportal/dataverse/tree/4684-metadatablock-internationalization

Will do PR soon after committing french metadata files.

**Comment by 4tikhonov** [comment]
Hi @JayanthyChengan, thanks, I see, it's good idea to have a separate folder for translated properties. I'm looking forward to see it in the master branch, we'll use it for DataverseEU as well.

**Comment by 4tikhonov** [comment]
> Hi @4tikhonov : Thanks.
> I was able to get the output and I committed the code to
> https://github.com/scholarsportal/dataverse/tree/4684-metadatablock-internationalization
> 
> Will do PR soon after committing french metadata files.
@JayanthyChengan, we've introduced in DataverseEU ISO codes for all languages we're supporting, can you please also test it with current release? 
 https://github.com/IQSS/dataverse-docker/tree/master/dataversedock/dataverse-property-files 
fr-CA here is coming from Scholarsportal, other translations were done by our community.

Also we modified 
https://github.com/IQSS/dataverse-docker/blob/master/dataversedock/lang.templates/metadataFragment.xhtml to get translated all properties for metadata fields. I don't know if it will be incorporated in the master branch soon so just in the case.

**Comment by scolapasta** [comment]
@JayanthyChengan thoughts on removing columns from db? It's not ideal to have duplicate info. (alternatively, the code could expect to use the db if the primary language and  only use the bundle otherwis; but that seems like possible overkill in logic)

**Comment by 4tikhonov** [comment]
@scolapasta, the ideal solution for DataverseEU is to use controlled vocabularies as properties delivered as microservice with language parameter. We're connecting Dataverse to ELLST multilingual thesaurus now (13 languages, distributed as RDF) to get similar functionality.

**Comment by pameyer** [comment]
Took a look after some discussion of how the documentation was for installations using custom metadata blocks.  Neither PR (#5111 or #5290) has any documentation - I haven't tested to see if that's because custom blocks without a corresponding bundle file will work they way they previously did (non-localized), or if things will assume there's a bundle for each block and fail when it's not present.

**Comment by JayanthyChengan** [comment]
@pameyer you are right, I missed to handle custom metadata blocks here.  

Noticed that it's throwing **java.util.MissingResourceException** in server.log for custom metadata block and in the interface:
**Internal Server Error - An unexpected error was encountered, no more information is available.**

I will add property files for existing custom metadata blocks.

**Comment by scolapasta** [comment]
@JayanthyChengan Adding files for those is good, but should we make the code have a backup plan for these cases?

**Comment by JayanthyChengan** [comment]
@scolapasta     
definitely, I am using a java code to create these property files, I will clean up/add proper comments in the code and add it.  under which folder does this code should go?

**Comment by JayanthyChengan** [comment]
@pameyer  added property files for custom metadatablocks in this commit https://github.com/IQSS/dataverse/pull/5290/commits/fe6ec387dd7609374a56a503986e10fa4dd86621

**Comment by JayanthyChengan** [comment]
@pameyer , I guess we need to specify in the documentation that the resource bundle property files are required for metadata blocks.  I can share the script which I use to generate them.

@scolapasta - could you please clarify here, do I need to handle in the program for missing property file(metadatablocks) and fetch the value from table.

**Comment by djbrooke** [comment]
@pameyer and @scolapasta - I moved this back to code review and assigned it to you two.

**Comment by scolapasta** [comment]
@jayanthy I think we want to fail in the "nicest" possible way. that is, let's imagine an istallation with a custom black that doesn't fully read the release notes so they don't do anything. What should happen?

I'd say not throw an ugly error, but at least use the KEYS from the table on the page. I do think eventually we don't want everything (like description, watermark, etc), in the table because that means we are doubling up, but at least to display something on the page that would allow a user to keep working?

I'm open to others opinions too. I.e. how much work should we do to handle cases where the installation owner doesn't configure things correctly? If we document correctly, throwing a useful error could also be enough.

**Comment by scolapasta** [comment]
@JayanthyChengan Similar to the alert PRs, could you consolidate a final version into one PR and close any remaining ones?(if one of these is already the consolidated version, just let us know). 

I could use some more detail on this java program to create the property files? (I'm not sure if I missed the detail on this). I think it should probably live in the project that eventually houses all the bundles files, once we transition it over to the GDCC.

**Comment by JayanthyChengan** [comment]
PR https://github.com/IQSS/dataverse/pull/5290 is the latest one with all changes.

**Comment by pdurbin** [comment]
@JayanthyChengan thanks for all work on this! Shouldn't your pull request include a change to the rst file for http://guides.dataverse.org/en/4.9.4/admin/metadatacustomization.html to explain to creators of custom metadata blocks that they must create not only a TSV file but also a bundle file? Once your pull request is merged, I mean.

**Comment by JayanthyChengan** [comment]
@pdurbin @scolapasta  , updated doc/sphinx-guides/source/admin/metadatacustomization.rst in the PR #5290 , please review it.

**Comment by pdurbin** [comment]
@JayanthyChengan I didn't `make html` but the info you added to about to metadatacustomization.rst looks great! I made a small tweak in a561055 to remove some references to this issue. I put this issue back in code review. Thanks!

**Comment by JayanthyChengan** [comment]
@kcondon please let me know, if I can answer any of your questions.  Thanks

**Comment by kcondon** [comment]
@JayanthyChengan Thanks, I have been occupied with other issues but hope to get to this shortly.

**Comment by kcondon** [comment]
@JayanthyChengan This looks good and hope to merge shortly but ran into a slight doc issue with unicode char when building pdf format. I'm checking with the team to see whether this is something we need to worry about. 

For what it's worth, here is the doc build error for pdf. html works fine:

! Package inputenc Error: Unicode char ṭ (U+1E6D)
(inputenc)                not set up for use with LaTeX.

See the inputenc package documentation for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.3758 ...age.marathi\_(marathi)=Marathi (Marāṭ
                                                  hī)
? 
! Emergency stop.
 ...                                              
                                                  
l.3758 ...age.marathi\_(marathi)=Marathi (Marāṭ

**Comment by JayanthyChengan** [comment]
@kcondon  replaced with unicode character in this commit
https://github.com/IQSS/dataverse/pull/5290/commits/86e5b7cf04eb1426f7930eb6399283a86f72bf59

does this help in pdf generation error?

**Comment by kcondon** [comment]
@JayanthyChengan Yes, that did it. Thanks! Merged.
