### ISSUE TITLE
Internationalization : UI toggle for language selection

### ISSUE THREAD

**Issue by JayanthyChengan** [IQSS/dataverse#4685]
Have to figure out where to place the toggle button in the main page?

**Comment by djbrooke** [comment]
Thanks @JayanthyChengan for this (and for all the internationalization PRs!). We discussed this briefly in standup today, and since this is getting into UI/UX land, I'll tag @TaniaSchlatter. 

Can you let us know what you're thinking?

**Comment by JayanthyChengan** [comment]
@djbrooke :  Thanks for involving Tania for UI design.  
  - Would like to figure out from Harvard team where to place the toggle button on the main page ?
 - Incorporate code changes to fetch language from the user selection and choose corresponding bundle properties

**Comment by JayanthyChengan** [comment]
@djbrooke  @scolapasta :  To get the dropdown list of languages dynamically, planning to have a database table for languages and pull the values from it.  So, we can use CURL commands to add new languages and fetch corresponding bundle.properties in the application.   Let me know, if there is any other better approach to tackle this.

To establish the locale into the web application, I will follow https://docs.oracle.com/javaee/6/tutorial/doc/bnaxw.html

Please confirm with your thoughts.  Thanks

**Comment by amberleahey** [comment]
Just to follow up, we are starting to develop the UI toggle to support testing the new internationalization code and eventual use of DV in different languages. The mock-ups and database design considerations are helpful. 

After some discussion at SP, we are considering placing the button  far right, after 'Login'. Any objections? I've provided some additional examples. 

Without opening too much of a debate around languages and flags, is this required for the toggle? 
![languagetoggle2](https://user-images.githubusercontent.com/17624834/41730758-91b5c2ec-754a-11e8-975b-e4d35f1c2813.png)
![languagetoggle3](https://user-images.githubusercontent.com/17624834/41730759-91c3303a-754a-11e8-80c2-0c4a72996d45.png)
![languagetoggle4](https://user-images.githubusercontent.com/17624834/41730760-91ce385e-754a-11e8-95ed-3bb9b1e4bc81.png)

**Comment by amberleahey** [comment]
same additional input from google https://support.google.com/webmasters/answer/182192?hl=en

**Comment by djbrooke** [comment]
@amberleahey @JayanthyChengan we missed this in the all the OR2018 and DCM excitement. We'll have the design team take a quick look and provide some feedback.

**Comment by TaniaSchlatter** [comment]
Hi @amberleahey, the rationale for the suggested language toggle was concern about length and shifting placement of items in the navigation bar. Placing the toggle to the right of the other items would cause placement to shift with the varying length of user names. I liked that the suggested toggle was short, clear, and consistent in length. What are the SP team's concerns?

Thanks for posting the google link. It has good a good summary of things to keep in mind. We will need to discuss with @mheppler and @scolapasta.

**Comment by mheppler** [comment]
@amberleahey @JayanthyChengan After reviewing the UI options with @TaniaSchlatter and discussing in a little more detail with a our visiting German developer, I have some recommendations -- and a mockup!

<img width="967" alt="screen shot 2018-06-21 at 4 04 36 pm" src="https://user-images.githubusercontent.com/687227/41742780-07b44b5e-756d-11e8-92f5-0f0782f755bf.png">

- Navbar link should contain the language name (e.g. "English") as opposed to "Language", as well as an icon of some sort, in order to ease the discovery of where to go to change the language (the "A"/font icon I used from Bootstrap is not the best, we could use another icon, the "language" icon used in one of the screenshots above is from FontAwesome, which we can get from PrimeFaces)
- Username navbar dropdown link should remain in the far right, with the language dropdown just to it's left
- Selected language should be highlighted in the dropdown, I've also included a checkmark icon in order to aid visual recognition outside of words
- Language options in the dropdown should be language names listed in their language, as one of the screenshot examples above shows

We're happy to discuss further and researching other options. Let us know if you have any feedback.

**Comment by amberleahey** [comment]
Makes sense, we were a bit worried about disruption in the nav bar, but this looks good! Thanks for the tips and mock-up.

**Comment by pdurbin** [comment]
> To get the dropdown list of languages dynamically, planning to have a database table for languages and pull the values from it.

@JayanthyChengan I don't see any objections above and this is fine with me.

**Comment by JayanthyChengan** [comment]
@pdurbin 
- Instead of Database table, languages were populated from json file src/main/webapp/resources/lang/languages.json in src/main/java/edu/harvard/iq/dataverse/DataverseLocaleBean.java

@mheppler 
- I submitted pull request, please review.  I was not successful when I tried to implement "fontAwesome" and "Checkmark" icon,  Can I get help from your team to implement them ?

**Comment by mheppler** [comment]
Cleaned up the alignment of the language selectOneMenu form input in the navbar, but need to look into responsive width issues. Will have a commit ready when I can get that resolved.

<img width="776" alt="screen shot 2018-06-28 at 4 48 23 pm" src="https://user-images.githubusercontent.com/687227/42061364-df6cbcae-7af7-11e8-8e44-6d5d1a0d0850.png">

**Comment by JayanthyChengan** [comment]
Thanks @mheppler

**Comment by mheppler** [comment]
With the help of @scolapasta (java) and @pdurbin (git), I was able to get the language dropdown for the navbar converted over from a selectOneMenu form component, to a list of links, in the Bootstrap styling we had originally mocked up.

<img width="965" alt="screen shot 2018-07-13 at 12 49 21 pm" src="https://user-images.githubusercontent.com/687227/42704196-f70225d8-869c-11e8-879b-72b9b90c9acf.png">

I created a new branch, and PR, and linked it to this issue. Will move it to Code Review now, so that @scolapasta can revisit some of the backing bean logic he helped "get working". I will also need to revisit some of the inline CSS I quickly added in order to get looking a lil more Bootstrappy.

**Comment by mheppler** [comment]
NOTE: This branch will most likely need to be updated with `develop`, as well as have some documentation added, before it is ready for QA. I can take care of those next week while, either as part of the revisions from the review, or before the review gets started. Just wanted to get this code into GitHub while it was still warm and fresh! 🍰 😎

**Comment by mheppler** [comment]
Also, created a new issue, _Status Message - Improve UI #4842_, to give the new navbar language dropdown a lil more real estate to work with.

**Comment by pdurbin** [comment]
@oscardssmith this issue is in code review but there are two open pull requests associated with it at https://waffle.io/IQSS/dataverse . Can you please close the pull request that we are not supposed to look at? Thanks.

**Comment by pdurbin** [comment]
@oscardssmith thanks. I took a quick look at pull request #4841. Please document the new database setting.

**Comment by oscardssmith** [comment]
will do.

**Comment by pdurbin** [comment]
@oscardssmith thanks for documenting the new setting in 2b67476

Chinese isn't in the example but it seems to work too... sort of... the header is translated at least:

`curl http://localhost:8080/api/admin/settings/:Languages -X PUT -d '[{  "locale":"en", "title":"English"},  {  "locale":"fr", "title":"Français"}, {  "locale":"zh_CN", "title":"Chinese"}]`

<img width="1497" alt="screen shot 2018-07-27 at 11 23 24 am" src="https://user-images.githubusercontent.com/21006/43329885-a81a8b24-918f-11e8-98bb-e620d3c67446.png">

**Comment by benjamin-martinez** [comment]
@JayanthyChengan The toggle button now works and switching between languages is possible. It also works when you change your browser's language settings to a different language. However there is a slight bug that we are having issues dealing with. If one were to change their entire OS to a language other than English, the toggle button does nothing except for changing the text of the button.

**Comment by JayanthyChengan** [comment]
@benjamin-martinez  and all:  Thanks for working on this and getting it ready for testing.  I will update the findings from our testing.  Thanks.

**Comment by 4tikhonov** [comment]
@JayanthyChengan, we're very interested to try this new switch languages functionality in DataverseEU project. At the moment we have Bundle.properties for French, German, Slovenian, Swedish, Ukrainian and Spanish languages, how can we connect to web interface to see all available languages there?

**Comment by pdurbin** [comment]
@4tikhonov you should check out the new `:Languages` database setting at https://github.com/IQSS/dataverse/blob/79c6dc3cd8dd1c88e00b441c37f95e26454085af/doc/sphinx-guides/source/installation/config.rst#languages and keep an eye on pull request #5023 for how we want to try keeping the bundle files outside the main app in the future.

**Comment by amberleahey** [comment]
I'll post something about this upcoming DV release and community objectives around collecting additional languages and the maintenance of them. Thanks @4tikhonov  for those additional language files they will be great for testing. We don't have a public DV instance w/this code accessible at the moment, but we will work on that with the Harvard team.

**Comment by pdurbin** [comment]
@4tikhonov here's a screenshot of how it looks on https://dev1.dataverse.org

![screen shot 2018-09-10 at 9 53 28 am](https://user-images.githubusercontent.com/21006/45301684-70531580-b4df-11e8-88a5-4eefa2e63415.png)

@amberleahey I'm looking forward to your write up! Thanks!

**Comment by pdurbin** [comment]
@4tikhonov no, I don't think so. If this is something you want or need, please open an issue for it.

**Comment by 4tikhonov** [comment]
This is what we're implementing with running different containers for all languages. But if there is possibility to get it as a part of core functionality it would be great.

**Comment by 4tikhonov** [comment]
Great, I have another question then about metadata schema: is it also already translated to French if you'll switch to it?

**Comment by amberleahey** [comment]
Update from the community call today, many people require having Dataverse in a specific language locale e.g. EN-CA, FR-FR, etc., and to be able to differentiate this in the UI toggle. Can we revisit the design of the UI toggle to incorporate these country/locales codes? Someone mentioned using ISO country and language codes or some combination of plain language and code might be best. see: https://docs.oracle.com/cd/E13214_01/wli/docs92/xref/xqisocodes.html as example of codes to combine...

**Comment by pdurbin** [comment]
@amberleahey we're always open to revisiting anything but can you please create a new GitHub issue for the language toggle? This closed issue represents the work that was done in pull request #4841 for the next version of Dataverse (the current version is 4.9.2). Thanks!

**Comment by pdurbin** [comment]
Let's continue the conversation at #5046 (thanks for creating that issue, @amberleahey !).
