### ISSUE TITLE
Scheduled harvests aren't running

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#4686]
On Harvard Dataverse 4.8.6, scheduled harvesting jobs aren't running when scheduled. Harvesting works only when pressing the "Run Harvesting" button.

**Comment by djbrooke** [comment]
@matthew-a-dunlap thanks for picking this up. #3672, #3669, and #3985 represent some previous work in this area.

**Comment by matthew-a-dunlap** [comment]
Talking more with @jggautier it looks like this predates 4.8.6. Will investigate more after my appointment today.

**Comment by matthew-a-dunlap** [comment]
I'm also assuming that #4548 has fixed at least some of this issue. @kcondon @pdurbin, have we tried running harvesting post #4548 for the clients stuck in production (as in, running the same harvests on a different box)?

**Comment by kcondon** [comment]
@matthew-a-dunlap The #4548 failure was a data failure, the scheduling one is a timer issue I believe. You can try out scheduling locally and ask Julian about specific harvesting jobs that are not running or what the pattern looks like.

**Comment by matthew-a-dunlap** [comment]
I have tried out scheduling locally on develop and 4.8.6 and harvesting seems to run as expected. Maybe there is a server timer configuration issue? Or some other variable in play that I do not have replicated on my local? @jggautier @kcondon

**Comment by landreev** [comment]
Yes, it appears to be turned off in production right now. (can't remember honestly when we turned it off or why...)
I'm turning it back on (yes, this is the JVM timer option that needs to be present on the designating primary server).

**Comment by matthew-a-dunlap** [comment]
@landreev Great! Thanks much for looking.

**Comment by landreev** [comment]
OK, turned it on. 
```
/opt/dvn/app/glassfish4/glassfish/bin/asadmin create-jvm-options "-Ddataverse.timerServer=true"
```
Will keep an eye on the actual harvests, once they start running.

**Comment by matthew-a-dunlap** [comment]
@jggautier Good to know! Yea its hard to know what's happening without a "next scheduled harvest" column.

**Comment by matthew-a-dunlap** [comment]
Scheduled Harvests are now running in production. There are still failures IN those harvests, but they may be failing due to issues fixed in our dev branch.
