### ISSUE TITLE
Documentation: Need to correct api endpoint for tabular column-wise subsetting.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#4687]
In the Data Access section of the API Guide: http://guides.dataverse.org/en/4.8.6/api/dataaccess.html
the syntax for the endpoint for column-wise subsetting is incorrect.

It currently says, 
http://localhost:8080/api/meta/datafile/6?vars=123,127

when it should say,
http://localhost:8080/api/access/datafile/6?variables=123,127

So, in the endpoint path meta should be changed to access and vars should be changed to variables. Otherwise the endpoint works.

Also, need to remove/change example for Data Variable Metadata Access, shows:
http://localhost:8080/api/meta/datafile/6
should be:
http://localhost:8080/api/access/datafile/6/metadata/ddi

Note the meta version still works but is deprecated. Might make mention of that or not.

**Comment by pdurbin** [comment]
I addressed feedback from @sekmiller in abbdf07 and added the API tests I mentioned at standup in e2bf07e. Off to QA.
