### ISSUE TITLE
(Tech Debt) Dataset needs to have a GlobalId rather than three strings

### ISSUE THREAD

**Issue by michbarsinai** [IQSS/dataverse#4688]
This can be done easily without changing the database by making GlobalId `@Embedable` (https://docs.oracle.com/javaee/7/api/javax/persistence/Embeddable.html)

**Comment by qqmyers** [comment]
Changes from the DOI for files and #3583 work have moved the authority, identifier, and protocol fields to DvObject and made GlobalId the only place that incoming global IDs are parsed into components. I'm guessing this issue now applies to DvObject embedding a GlobalId instead?

**Comment by michbarsinai** [comment]
Indeed. And should this be four strings now (including the value formerly known as "doi separator")?

**Comment by scolapasta** [comment]
Just the three - the shoulder is just used as a something to prepend to the unique part of the identifier, but there's no need to store separately.
