### ISSUE TITLE
GET `api/datasets/:persistentId/?persistentId` error

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#4692]
On 42014cb7f2c4c16c5825b16eaba7fb66c38b0cd5 in docker-aio (confirmed version in container with call to `api/info/version`.  `./conf/docker-aio/run-test-suite.sh` reports `Tests run: 72, Failures: 0, Errors: 0, Skipped: 0`.

Manual call to GET `api/datasets/:persistentId/?persistentId=doi:$pid` return `{"status":"ERROR","message":"Command edu.harvard.iq.dataverse.engine.command.impl.GetLatestAccessibleDatasetVersionCommand@3320cf09 failed: null"}` instead of expected JSON representation of published dataset (in this case, finches created by setupIT).

**Comment by pameyer** [comment]
Using an internal / database ID: `api/datasets/11` returns `{"status":"ERROR","message":"User :guest is not permitted to perform requested action."}`

**Comment by djbrooke** [comment]
Thanks @pameyer - we discussed this regression in standup this morning and @sekmiller and @scolapasta are going to take a look.

**Comment by sekmiller** [comment]
for testing be sure to try a get of a dataset with a draft version that the caller cannot view.
