### ISSUE TITLE
Leading and trailing whitespace in email (account creation) still being written to the authenticatedusers table

### ISSUE THREAD

**Issue by mdmADA** [IQSS/dataverse#4698]
DV 4.6.1

Leading and trailing whitespace in Account creation email field is still being written to the database's authenticateduser table. It's an issue because it is an identifier.

Name(s) fields, Institution, Position whitespace is also written to the authenticatedusers table although not as big an issue since none are used as identifiers.

First logged in Issue #3044.

**Comment by pdurbin** [comment]
@mdmADA thanks for reporting this issue. Have you tested it on more recent versions of Dataverse? As of this writing the latest version is 4.9.1.

**Comment by pdurbin** [comment]
@mdmADA hi! Did you and your sysadmin ever get around to testing this? Thanks!

**Comment by mdmADA** [comment]
Hi @pdurbin - I just tested it on dv 5.10.1 and it no longer allows whitespace in the email address - leading, trailing or within.

So it's been fixed. I will close it.
