### ISSUE TITLE
Enable outgoing connections over HTTP/HTTPS proxy

### ISSUE THREAD

**Issue by blavoie** [IQSS/dataverse#4707]
By default dataverse is not able to connect to the internet over a proxy like Squid.

Under normal circumstances, using relevant system properties on the command line should make use of proxy effortlessly. 

Parameters reference documentation: https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html

After investigation and [discussion](https://groups.google.com/d/topic/dataverse-community/re0--5aCzPg/discussion) it appears that:

**First**
EZID: by default doesn't support connections over HTTP proxy, a [pull request](https://github.com/NCEAS/ezid/pull/11) for this part was sent to use system properties when present. It uses HttpClient and by default this library isn't using considering system properties until we explicitly call the [useSystemProperties()](http://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/impl/client/HttpClientBuilder.html#useSystemProperties()) on the [HttpClientBuilder](http://hc.apache.org/httpcomponents-client-ga/httpclient/apidocs/org/apache/http/impl/client/HttpClientBuilder.html).

**Second**
Dataverse is experiencing the same kind of problem when configuring harvesting to external Dataverse instances. To make HTTP calls Dataverse is using [Unirest](http://unirest.io/java), that also uses HttpClient behind the scenes. 

It is possible to quickly make Unirest to use an HttpProxy by two ways:

- Passing a custom HttpClient that is built with useSystemProperties().
- Invoke Unirest.setProxy before invoking the current methods.

Don't know what is the best way of doing things in this case.

By doing a quick search I found that Unirest keyword is present in 8 files, not such a big deal to fix at first.

Thanks
Bruno Lavoie

**Comment by pdurbin** [comment]
@blavoie thanks for opening this issue, for making the pull request at https://github.com/NCEAS/ezid/pull/11 , and for all the chatter on the dataverse-community mailing list!

If you are willing to make a pull request to address the Unirest issue, my initial thought is that the useSystemProperties approach is probably better but honestly, whichever one is easier for you to implement is probably fine. Thanks!

**Comment by pdurbin** [comment]
@blavoie hi! Any updates? Is this still an issue for you?

**Comment by pdurbin** [comment]
> Dataverse is experiencing the same kind of problem when configuring harvesting to external Dataverse instances. To make HTTP calls Dataverse is using [Unirest](http://unirest.io/java), that also uses HttpClient behind the scenes.

While it's true that Dataverse is using Unirest for the Data Capture Module (in DataCaptureModuleServiceBean.java for example), I don't believe it's used it harvesting (OAI-PMH).

So I'm removing the "Feature: Harvesting" label from this issue.

@blavoie by the way, are you still interested in this?

**Comment by blavoie** [comment]
@pdurbin 
not interested, can be closed.
thanks
