### ISSUE TITLE
DCM Swift

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#4710]
similar to issue #4703, so cutting and pasting key points from there:

The DCM (data capture module, for big data upload) currently integrate with Datavese assumes POSIX storage (and ssh+rsync data transfer); however using object stores (AWS S3, OpenStack Swift, etc) is becoming more common.

Lowest-way complexity way of implementing this would be a second (third, if S3 done first) DCM implementation (or configuration option for current DCM), changing only how data files are transferred from the temporary upload location to the dataverse-accessable storage (aka - internal copy from temporary POSIX to DV swift dataset buckets) and keeping existing ssh+rsync and client-side checksums.

**Comment by djbrooke** [comment]
Will close for now. @amberleahey @carlosmcgregor and some other folks at SP have discussed adding large data transfer capability for Swift, but I'm guessing this won't use DCM. We can reopen this if there is a DCM-specific use case for installations running a Swift storage driver.

**Comment by pdurbin** [comment]
> @amberleahey @carlosmcgregor and some other folks at SP have discussed adding large data transfer capability for Swift

Yes, I do see a couple mentions of Swift at https://spotdocs.scholarsportal.info/display/DAT/2019/07/09/CANARIE+project+update%3A+Dataverse+for+the+Canadian+Research+Community
