### ISSUE TITLE
datasetVersion vs. latestVersion in JSON metadata response

### ISSUE THREAD

**Issue by ross-spencer** [IQSS/dataverse#4715]
Thank you for contributing an issue to the Dataverse Project! If this is a bug report, please let us know when the issue occurs, which page it occurs on, to whom it occurs, and which version of Dataverse you're using. If this is a feature request, please let us know what you'd like to see and give us some context - what kind of user is the feature intended for, and what inspired the request? No matter the issue, screenshots are always welcome.

I am using the web interface and the API to explore this dataset here: https://demodv.scholarsportal.info/dataset.xhtml?persistentId=doi:10.5072/FK2/6PPJ6Y

You'll see from the diff on this gist, that the differences between the two outputs are minimal. https://gist.github.com/ross-spencer/ffd54e2fc1893b44e44fcf7147d5e417/revisions#diff-12eb2b59d603b983287eb105cf667843 

My question is: are they by design?

* `datasetVersion` appears in the web interface JSON, but it changes to `latestVersion` in the api download
* `citation` appears in the version downloaded from the web interface

I'm interested to find out. We'll be developing against the API result, so we'll rely on that output for now.

**Comment by ross-spencer** [comment]
No worries. Thanks @pdurbin! We'll be sure to check out and add to #4283 as well!

**Comment by pdurbin** [comment]
@ross-spencer has your question been answered? If so, please feel free to close this issue. Or is there anything else you need for this issue?

**Comment by ross-spencer** [comment]
@pdurbin I believe they have and thank you! (Sorry I didn't see your response before). If there's no plan to fix this, maybe we can add some form of `wontfix` label? Otherwise, all is good and I'll close this now.

**Comment by pdurbin** [comment]
@ross-spencer sure. Good idea. I just created an applied a "wontfix" label, using the naming and color conventions at https://github.com/IQSS/redmine2github/tree/master/scripts/label_updates#label-namecolor-table 

Thanks for helping keep our issue tracker tidy!
