### ISSUE TITLE
CSV Byte order mark is translated literally into DDI metadata and Preview

### ISSUE THREAD

**Issue by ross-spencer** [IQSS/dataverse#4716]
If you look at this dataset here: https://demodv.scholarsportal.info/dataset.xhtml?persistentId=doi:10.5072/FK2/6PPJ6Y

And look at the DDI metadata, you'll see that the byte order mark has been translated into the XML. 

https://demodv.scholarsportal.info/api/datasets/export?exporter=ddi&persistentId=doi%3A10.5072/FK2/6PPJ6Y

![image](https://user-images.githubusercontent.com/1880412/40548237-6cb793b0-6034-11e8-9ffd-31b8ef941bb6.png)

It is also possible to see it when we explore the data in the viewer:

![image](https://user-images.githubusercontent.com/1880412/40548314-ac7e624e-6034-11e8-8ffa-e1af75c007aa.png)

Given access to the raw data anyway, I wonder if there is a way that this type of data can authentically be stripped before being made available in the metadata file?

**Comment by pdurbin** [comment]
Is that why "Don't know" looks so weird at https://twitter.com/scholarsportal/status/999378432139161600 ? Here's a screenshot:

![screen shot 2018-05-25 at 10 10 12 am](https://user-images.githubusercontent.com/21006/40548766-a5ea9f6e-6003-11e8-992d-69800a52ea7d.png)

**Comment by ross-spencer** [comment]
Interesting! I have seen that in other formats. Sometimes when using a windows code-page for encoding instead of UTF-8 or somesuch. I notice there isn't an XML encoding scheme set in the DDI either... maybe something similar going on in that other rendering?

**Comment by pdurbin** [comment]
@kevinworthington any thoughts on this?

**Comment by kevinworthington** [comment]
I think the issue resides in spacial characters being present when the data is ingested. The "’" and "“”" characters are particularly problematic as well as others like french characters. Sadly once the characters have been replaced (e.g �) it doesn't look like they can be fixed without going back to the source text and treating it as utf-8. 
Another option to fix existing datases would be to use a [curation tool](https://github.com/scholarsportal/Dataverse-Data-Curation-Tool) (shameless plug) to fix these characters. It's still in it's early stages and I've yet to add variable category editing, but this could definitely be added.

**Comment by pdurbin** [comment]
@ross-spencer is this bug easy to reproduce? Can you please provide the steps?

**Comment by pdurbin** [comment]
@ross-spencer I just uploaded and published your Drinks.csv file to https://demo.dataverse.org/file.xhtml?persistentId=doi:10.70122/FK2/7FPPWD/6SJOHD&version=1.0 and exported it as DDI: https://demo.dataverse.org/api/datasets/export?exporter=ddi&persistentId=doi%3A10.70122/FK2/7FPPWD

<img width="964" alt="Screen Shot 2022-10-09 at 9 17 12 AM" src="https://user-images.githubusercontent.com/21006/194759074-eacf33ce-85e1-4de5-ac08-00aecdfe688f.png">

It seems to look fine. I'm not sure which pull request might have fixed this in the last 4+ (!) years. 😄  Perhaps you could uningest and reingest your file? What do you think?

**Comment by ross-spencer** [comment]
@pdurbin apologies for missing your first call to recreate.

The CSV is here: https://github.com/artefactual/archivematica-sampledata/blob/b01539902198a9e4a15f76add7b6b129eecf6b7b/SampleTransfers/Dataverse/AStudyOfMyAfternoonDrinks/Drinks.csv

I can see it is also available via the original Dataverse upload: 

![image](https://user-images.githubusercontent.com/1880412/194827763-204f56f9-c7be-4c17-9b3d-3ea96accb6b5.png)

Importantly the bytes `EF BB BF` need to exist at the beginning of the file:

![image](https://user-images.githubusercontent.com/1880412/194827871-13ff8e47-850d-43fc-94d2-94db0636cc95.png)

It sounds like you've recreated the steps as I did, and have found the issue no-longer there. 

I haven't access to Dataverse currently. I was working at the time on an integration for the Archivematica system. I am happy that this seems to no-longer be an issue, so we can close this. If there are any future similar issues folks can still link here if necessary.
