### ISSUE TITLE
Installation Guide - Dropbox file upload configuration

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#4724]
The instructions for [how to set up Dropbox for file upload](http://guides.dataverse.org/en/4.8.6/installation/config.html#dataverse-dropbox-key) is severely lacking in our Installation Guide. It took me far too long to find these [required steps in the Dropbox documentation](https://www.dropbox.com/developers/chooser). We should link to that page from our guides to make it easier to set up.

**Comment by pdurbin** [comment]
It would be nice to list Dropbox as a feature at https://dataverse.org/software-features as well. And while we're in there we could add these:

- Schema.org support
- Dropbox integration
- OAuth login (ORCID, GitHub, Google)
- Widgets
- OAI-PMH
- Support for Zotero. Endnote, and Altmetrics
- Integration with OJS, OSF, and RSpace

I'd like to document all the known integrations, probably in the Admin Guide, over at #4283

**Comment by pdurbin** [comment]
@mheppler heads up that I mentioned Dropbox in the new page on integrations in the Admin Guide: 6ea5ed4

**Comment by pdurbin** [comment]
Pull request #4756 looks good so I moved it to QA. In 580cdfd I attempted to switch the remaining instances of `asadmin` to `./asadmin` so that the command actually works. (`asadmin` is not in one's $PATH.)
