### ISSUE TITLE
Version: Update version from 4.8.6 to 4.9 

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#4734]
Update version from 4.8.6 to 4.9.

In an earlier pull request we've modified the doc files where versions are referenced so the steps and instructions for versioning a release also need to change.

**Comment by pdurbin** [comment]
@kcondon you're probably referring to pull request #4613

I'll defer to @mheppler who updated the instructions.

**Comment by mheppler** [comment]
New branch [`4734-update-v-4.8.6-to-4.9`](https://github.com/IQSS/dataverse/commits/4734-update-v-4.8.6-to-4.9) with all the necessary commits.

**Comment by pdurbin** [comment]
The links to previous versions of the guides that appear on the new versions page seem to work fine. I deployed the branch to http://guides.dataverse.org/en/4734-update-v-4.8.6-to-4.9/versions.html
