### ISSUE TITLE
Demo: Address stability issues due to disk space by periodically cleaning and consider increasing space.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#4741]
Our demo instance is on AWS and has been running relatively maintenance free since 2015. However, it has a relatively small HD (50GB) and with time and more aggressive security scans filling log files it needs some active management to keep it running well.

Proposals:
1. set up cleaner jobs for /tmp, /temp, /logs to clear files older than a day? or 2 hours, 2 hours, and a day respectively.
2. set up cleaner job to wipe data files older than X where X might be a year, a month, etc, plus an accompanying script to destroy related datasets from the Dataverse app.
3. increase the HD space, though this will cost more, being on Amazon
4. create sample data scripts to repopulate demo with representative datasets useful for illustration that could be restored after purging. for the initial launch of demo, these were metadata-only datasets of selected production datasets.
5. potentially open up console access to more of the team so we can be more responsive to issues as they arise.

**Comment by landreev** [comment]
I have replicated the temp cleaner crontabs we have in production (domain1/files/temp had *a lot* of old files in it, having it cleaned will help a lot!); 
Adjusted the tmpwatch time limits to match what we are using in production;
Also automated your script for deleting older datasets, to be run by a cronjob every month (on the 1st of every month).
