### ISSUE TITLE
deaccessioning: users should be able to "Edit" deaccessioning note and forwarding URL if needed

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#4743]
We've had cases where users forget to add the new DOI to the "deaccessioning reason" box and or they realize they didn't include enough information in a previous note and they are requesting to edit such fields post deaccessioning of a dataset

putting this under "permissions" because there is no label for features: deaccession

**Comment by groceryheist** [comment]
Would be great if I can do this. I was just exploring dataverse functionality and hit publish and then deaccession only to realize it was not reversible.

**Comment by jggautier** [comment]
Until this issue is prioritized, could we explore how to let depositors know that the deaccession reason will not be editable and that deaccessioning is not reversible?

**Comment by pdurbin** [comment]
@jggautier not a bad idea. It looks like you added #5056 about this.

**Comment by djbrooke** [comment]
Updated title, will close #3464 as a duplicate

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
