### ISSUE TITLE
Provided solr.service file using bad Type

### ISSUE THREAD

**Issue by blavoie** [IQSS/dataverse#4749]
Yesterday, I was installing the latest Dataverse (4.9) with the Solr requirement (7.3).

I used the provided solr.service file as suggested in the docs:
http://guides.dataverse.org/en/4.9/installation/prerequisites.html#solr-init-script

But the service is starting and dying immediately when starting with systemctl but running successfully when staring manually using the same ExecStart into the defined WorkingDirectory.

I stumbled along Solr and Systemd logs and found nothing different between standalone and systemd launching.

While Solr and Glassfish are Java products I was wondering why it works for my Glassfish service and not for Solr. Then I compared the two provided service files and the difference is that Type property is **simple** for Solr and **forking** for Glassfish.

I changed Solr service file to use forking type rather than the simple one and it worked.

Reading carefully man page for systemd.service (man systemd.service) for Type option:

> If set to simple (the default if neither Type= nor BusName=, but ExecStart= are specified), it is expected that the process configured with ExecStart= is the main process of the service. In this mode, if the process           
> offers functionality to other processes on the system, its communication channels should be installed before the daemon is started up (e.g. sockets set up by systemd, via socket activation), as systemd will immediately        
> proceed starting follow-up units.
> 
> If set to forking, it is expected that the process configured with ExecStart= will call fork() as part of its start-up. The parent process is expected to exit when start-up is complete and all communication channels are       
> set up. The child continues to run as the main daemon process. This is the behavior of traditional UNIX daemons. If this setting is used, it is recommended to also use the PIDFile= option, so that systemd can identify the     
> main process of the daemon. systemd will proceed with starting follow-up units as soon as the parent process exits.

So, because we start Solr with a provided script (bin/solr start), it is not the final process that is Java. Because of that, forking is more appropriate and systemd service is working properly.

Also, maybe for production setup, using official deployment scripts from Solr project (their install_solr_service.sh script) is the best way to deploy and evolve through upgrades.
Reference: https://lucene.apache.org/solr/guide/7_3/taking-solr-to-production.html#service-installation-script

If it helps, I tested with latest and updated CentOS (7.5.1804)

**Comment by blavoie** [comment]
Also, the service file is missing ExecStop, this could be fixed at the same time:
`ExecStop=/PATH/TO/solr/bin/solr stop`

**Comment by pdurbin** [comment]
@blavoie thanks for the bug report! There's now an open pull request at #4752 by @donsizemore (thanks!) if you'd like to take a look.

**Comment by mbamouni** [comment]
Hi,
Setting Type=forking working also well for me. 
In some environnment, we need to set SOLR_JAVA_HOME value in solr.in.sh file.

Best regards,

Michel

**Comment by pdurbin** [comment]
@mbamouni I'm glad the fix about forking in pull request #4752 is working for you. If you think we should do something about SOLR_JAVA_HOME such as document it or update the script please open a new issue. Thanks!
