### ISSUE TITLE
API call using file PersistentId fails

### ISSUE THREAD

**Issue by matthew-a-dunlap** [IQSS/dataverse#4767]
While I was digging into #4761 (persistentId changes caused dcm to break) I was testing how we use persistentIds in the system. I was trying different API calls and ran into a bug.

File PIDs for accessing a datafile give an API endpoint error ( advertised in http://guides.dataverse.org/en/4.9/api/dataaccess.html#basic-file-access ): 
* BROKEN: curl -X GET "localhost:8080/api/access/datafile/:persistentId/?persistentId=doi:10.5072/FK2/ACOBON"
    * {"status":"ERROR","code":404,"message":"'/api/v1/access/datafile/:persistentId/' endpoint does not exist on this server. Please check your code for typos, or consult our API guide at http://guides.dataverse.org."}
* WORKS: curl -X GET "localhost:8080/api/access/datafile/8" works

FWIW, for datasets, both formats work:
* WORKS: curl -X GET "localhost:8080/api/datasets/33"
* WORKS: curl -X GET "localhost:8080/api/datasets/:persistentId/?persistentId=doi:10.5072/FK2/72447L"

**Comment by matthew-a-dunlap** [comment]
It looks like this issue was actually my environment being in a bad place! The curl works fine on https://dvn-vm4.hmdc.harvard.edu/file.xhtml?persistentId=doi:10.5072/FK2/1JXBTR/VWFPDA.

Example: curl -k -X GET "https://dvn-vm4.hmdc.harvard.edu/api/access/datafile/:persistentId/?persistentId=doi:10.5072/FK2/1JXBTR/VWFPDA"

Sorry for the alarm!

**Comment by pdante-ubc** [comment]
I'm getting basically the same issue, except it's failing even earlier in the path:  {"status":"ERROR","code":404,"message":"'/api/v1/access/datafile/' endpoint does not exist on this server. Please check your code for typos, or consult our API guide at http://guides.dataverse.org."}.

@matthew-a-dunlap, how was your environment in a "bad place"?

**Comment by pdante-ubc** [comment]
My call is to localhost:8080/api/access/datafile/:persistentId?persistentId=doi:10.5072/FK2/JSE79W/330XWG

**Comment by pdurbin** [comment]
@pdante-ubc what version of Dataverse are you running? Can you please start a thread at https://groups.google.com/forum/#!forum/dataverse-community or pop in http://chat.dataverse.org or email support@dataverse.org ? Thanks!
