### ISSUE TITLE
missing Bundle entries

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#4770]
dataverse/src/main/java/edu/harvard/iq/dataverse/api/AbstractApiBean.java references on lines 424 and 430 Bundle strings 'find.dataset.error.dataset.not.found.id' and 'find.dataset.error.dataset.not.found.bad.id' which were in prior versions of Bundle.properties but appear to be missing from the current one.

**Comment by pdurbin** [comment]
I noticed that pull request #4808 uses the term "data projects" rather than "datasets". @qqmyers can you please fix this up?

**Comment by pdurbin** [comment]
Looks good as of 61fd452. Thanks, @qqmyers . I moved this to QA at https://waffle.io/IQSS/dataverse

@qqmyers if you can write anything here about how to test, how to make those strings appear in the GUI, it would be helpful.

**Comment by qqmyers** [comment]
@pdurbin - I had just noticed this in trying to update and merge with QDR's Bundle changes, so I haven't seen where they show up. Looking through a little code, it looks like these messages get sent out in response to API calls when the id does not match an id in the database, or is not a number - /datasets/{id}/links looks like one option.

**Comment by qqmyers** [comment]
/api/datasets/bob/links?key=<APIKey of superuser>

gives 

{
"status": "ERROR",
"message": "Bad data project ID number: bob."
}
