### ISSUE TITLE
Files Card: Clicking the file name on a harvested file card results in an error.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#4771]
Clicking on the file name of a harvested file card results in a general handled error in UI. Server log shows stack trace starting with files page init method. This exists in v4.9.

**Comment by mheppler** [comment]
This sounds highly related to _Navigation - Harvested file landing page? #4288_.

**Comment by kcondon** [comment]
It is except now it throws an error. So you can close the other ticket ;)

**Comment by landreev** [comment]
We should probably close this issue, and use #4288 for fixing it instead. For continuity, etc. I'll add a comment there.

**Comment by mheppler** [comment]
@landreev fixed this and issue #4288, which is where he put an outline of his fix. I linked his pull request to this issue. Closing this issue to track progress in the older issue.
