### ISSUE TITLE
Referencing API data in the metadata

### ISSUE THREAD

**Issue by RightInTwo** [IQSS/dataverse#4772]
This is a proposal for a generalized system to reference data from external API sources in the metadata, which could be the (or part of the) solution to #4282 and #3622 and [probably more]. The preferred way to select the value would be an autocomplete function as described in #2603.

In some cases it might be nice to be able to select multiple values, as requested in #350.

Dataverse would need to save information about the used identifier (scheme|identifier of the value) and the metadata provenance (name|url|datetime of the API call) next to the display value. 

- Requirements
  - Saving the identifier together with the display value (no problem for Author, because "Identifier Scheme" and "Identifier" already exist). Does DDI allow IDs for all fields?
  - Display values should be updateable (while keeping the identifier of the reference), but only on new versions of the dataset (so the metadata stays immutable) and with confirmation of the user
  - A second lookup to gain details about the list from the first lookup is required if the ORCID search API shall be used, as described in #4236
  - If the TSV configures a field to use an external source and the source is not configured within dataverse, it should warn or break (based on configuration) (on create/update)
  - Both TSV and API config would need to be available when creating or updating the metadata

- UI representation
  - Button "Find [person | vocabulary term | object]" next to each field that has an API source configured
  - There should be a possibility to have greyed out fields that are configured (in this installation) to only be filled through the API source
  - Admin panel to manage custom API sources and browse default ones
  - Provide default API sources to be shipped with Dataverse (more examples at the bottom)
    - ORCID
    - LOC, DNB, other national libraries
    - Widespread vocabulary sources

IMPORTANT: The display value would be set when editing the metadata and published together with the provenance information (where the metadata came from) . Once published, all metadata becomes immutable and can only be changed on a new version.

The information that needs to be stored to describe the API source - feel free to add/reconfigure as you wish:

    "name" : "orcid-search-person",

    "version" : "2.1",

    "description" : "ORCID search person, v{VERSION}",
    
    "main_api" : "https://pub.orcid.org/v{VERSION}/search/?q={QUERY}",

    "id_source" : "result.orcid-identifier.path",  

    "id_target" : "AuthorIdentifier",  

    "secondary_fields" :
    
    {

        {

            "api" : "https://pub.orcid.org/v{VERSION}/{ID}", 

            "source" : "result. ...",

            "target" : "AuthorName",

            "string" : "person.name.given-names + ' ' + person.name.family-name",  

        },

        {

            "target" : "authorIdentifierScheme",

            "string" : "50", 

        }

    },

    "identifiers" :

    {

        "0000-1234-1234-5555" :

        {

            "string_representation" : "Jane Doe",

            "datetime" : "2018-06-22 16:20:25"
        
        },

        "0000-1234-1234-9999" : 

        {

            "string_representation" : "John Doeson",

            "datetime" : "2018-06-22 16:49:15"

        }

    }

...and lots of stuff more :)

**Todo**
Step 1:
a) Think about how data sources would be described within dataverse and referenced in the TSV.
b) Build a JavaScript (custom_footer?) to be put on top of the UI without changing the core.

Step 2: ?

Step 3: Profit!

- Example sources
  - Fields referencing persons (Author, Contact, Depositor, Contributor, Distributor, Producer, ...)
    -> Composite fields would need to be filled independently (to make historic references possible)
    - Dataverse native API
    - External sources: ORCID, LDAP through an API, Library of Congress Authorities, German National Library's norm data (DNB -> GND)
  - Fields referencing external vocabularies (Subject, Keyword, Topic Classification, Language, Production Place, Kind of Data, Software, Data Sources, ...)
    - DDI and other sources
  - Fields referencing other digital objects through a PID (Other ID, Related Publication, Related Datasets, ...)
    - Dataverse native API
    - External sources: DataCite index, other indexes and repositories

**Comment by pdurbin** [comment]
@RightInTwo I don't if you've seen https://twitter.com/4tykhonov/status/1068610709817384960 by @4tikhonov by it reminds me of what you want:

<img width="578" alt="screen shot 2018-11-30 at 8 48 28 pm" src="https://user-images.githubusercontent.com/21006/49322848-6a1e7500-f4e1-11e8-93d4-45d78756ef9e.png">

**Comment by 4tikhonov** [comment]
Yes, that's exactly what Jonas wants indeed. We'll meet with him next week in Berlin to discuss this stuff and future cooperation in SSHOC DataverseEU project.

**Comment by RightInTwo** [comment]
@pdurbin thanks Phil for pointing it out!
@4tikhonov i'm looking forward to meeting you again and finding out what the OpenSKOS solution can do

**Comment by djbrooke** [comment]
Hey @4tikhonov - we have another collaborator asking for this functionality and I'm going to point him to this issue. Any updates?

**Comment by RightInTwo** [comment]
@djbrooke @4tikhonov I'm still very much interested as well!

**Comment by doigl** [comment]
@RightInTwo @pdurbin @4tikhonov We are also very interested in this feature. We have a new metadata block for engineering data with variable and parameter fields (with name and value attributes). It would be wonderful to support (external and) controlled vocabularies for the name attributes with autocompletion. Ideally different vocabularies for one metadata field configurable by dataverse

**Comment by djbrooke** [comment]
Closing in favor of #6030 to evaluate as part of a larger effort.
