### ISSUE TITLE
Integration Test docs don't specify how to run integration tests

### ISSUE THREAD

**Issue by oscardssmith** [IQSS/dataverse#4773]
This is a really simple thing, but it should be added.

**Comment by pdurbin** [comment]
@oscardssmith good catch. The file to edit is doc/sphinx-guides/source/developers/testing.rst

**Comment by pdurbin** [comment]
As I've been reporting at http://irclog.iq.harvard.edu/dataverse/2018-07-02 the API test suite doesn't "just work" on a fresh clone of the git repo. I'm seeing the following errors:

- cp: directory ../../conf/docker-aio/dv/install does not exist
- cp: cannot stat 'pgdriver/postgresql-8.4-703.jdbc4.jar': No such file or directory

**Comment by pdurbin** [comment]
I just created pull request #4801 and will drag this issue to code review at https://waffle.io/IQSS/dataverse
