### ISSUE TITLE
Dataverse - V.4.9 - Authentication /Session Issue

### ISSUE THREAD

**Issue by Mahsanas** [IQSS/dataverse#4781]
There are a few issues with system authentication , but it seems it is associated more with the session handlings or timeouts than the authentication itself:
1- Sometimes the system can not sign me in despite I am typing in the correct credentials.
2- I have just signed in and I click a link, I am redirected to login page to sign in. 
3- I am already signed in, The My data page shows the "required Authentication".

Regards, 

Mahsa

**Comment by pdurbin** [comment]
@Mahsanas can you please provide the output of the following command?

`/usr/local/glassfish4/bin/asadmin osgi lb | grep 'Weld OSGi Bundle'
`

**Comment by pdurbin** [comment]
Thanks, that appears to be the right version of Weld: http://guides.dataverse.org/en/4.9/installation/prerequisites.html#glassfish

I'm not sure what's going on but the bug report reminds me of the old session troubles in #647 which led to us switching to version 2.2.10.SP1 of Weld.

I saw some of these behaviors recently on one of my test boxes (dev1, I think) and switching to the version of Weld above fixed it. Very strange.

**Comment by pdurbin** [comment]
@Mahsanas hi! Nice talking to you last week! I'm sorry we didn't get a chance to look at the Shibboleth issue you were telling me about. Is it this issue or #5237 or something totally different? 😄

**Comment by Mahsanas** [comment]
@pdurbin <https://github.com/pdurbin> Hi! Nice meeting with you as well and
thanks for digging up the issue. It is the same issue however I got help
from another Dataverse developer at the meeting who moved us one step
closer to the solution. Now, instead of the shibsp config error, we see the
an empty Account page once our Dataverse site is loaded. Another developer
suggested we should compare our config files with theirs to find the source
of the problem which I will do. Thanks for following up on this.

**Comment by pdurbin** [comment]
@Mahsanas ok, when you say "empty account page" does it look like this?

![Screen Shot 2019-06-26 at 4 39 13 PM](https://user-images.githubusercontent.com/21006/60213225-0cf96080-9831-11e9-9b6e-ea0c9ea216f1.png)

That's from https://help.hmdc.harvard.edu/Ticket/Display.html?id=277872 via http://irclog.iq.harvard.edu/dataverse/2019-06-25#i_98537

**Comment by Mahsanas** [comment]
@pdurbin <https://github.com/pdurbin>, yes! that is exactly what we see! Is
it coming from a different issue? Thanks..

**Comment by pdurbin** [comment]
@Mahsanas well, we're still troubleshooting so I'm not sure. Speaking of other issues, I just closed #5237 since we're talking here. I hope you don't mind. 😄 

Please keep us posted on the comparison of the config files you mentioned.

**Comment by Mahsanas** [comment]
@pdurbin <https://github.com/pdurbin>, that is fine though it would have
been better if you had closed this one and we continued on the other as
that is more relevant.
 I just want to calrify that our Shibboleth integration and auhentication
is in place and working fine since last fall.
We only have a configuration issue which causes (now) the "empty Account"
page to show when our Dataverse site is first loaded.
I will make a note here once we do the comaprisons.

**Comment by pdurbin** [comment]
@Mahsanas I just reopened #5237 since you said it's more relevant. Let's continue the conversation there. I'm closing this one. Thanks!
