### ISSUE TITLE
Update Chinese bundle properties file: Bundle_zh_CN.properties

### ISSUE THREAD

**Issue by pengchengluo** [IQSS/dataverse#4784]
The English bundle properties file has about 1800 key-value pairs. However, the Chinese bundle properties file updated two years ago and only has about 500 key-value pairs.  When viewing the web pages from Chinese web browser, there are only a few Chinese Characters. So, we want to translate all the key-value pairs and update some error translation, such as 
dataverse.permissions.roles.description.title=Describe the role (1000 characters max) has been erroneously translate into "描述中的作用（1000个字符）" which can't been understood by Chinese. We have translated 1000 key-value pairs based on dataverse 4.9 and plan to complete it in the following few days. We hope our updated Bundle_zh_CN.properties file could be added into dataverse code repository.

Besides, we also hope to continually update the Bundle_zh_CN.properties file in future releases of dataverse.

![image](https://user-images.githubusercontent.com/7343585/41883430-2ac78c16-7921-11e8-9a29-b4f4ef5c6375.png)

**Comment by oscardssmith** [comment]
While you are doing this, it probably makes sense to reduce duplicate bundle entries if you see them. A script I ran last summer found that ~20% are duplicates.

**Comment by djbrooke** [comment]
Tagging @scolapasta for his thoughts as he's coordinating internationalization efforts with other groups (see the list of child issues in #209)

**Comment by scolapasta** [comment]
@pengchengluo that's great! We'll review when it's ready.

Be aware we are planning on updating / streamlining the bundles as part of both internationalization and the Dataverse 5.0 release, i.e. the 1800 will hopefully be reduced in scope. 

(Generally, we're always in favor of "bringing back the forks", so let is know how we can help with that)

**Comment by pengchengluo** [comment]
@oscardssmith，I extract the keys from Bundle.properties and use Excel to find the following 14 duplicate keys:
advanced.search.datasets.persistentId.tip
advanced.search.files.persistentId.tip
authenticationProvider.name.builtin
authenticationProvider.name.github
authenticationProvider.name.google
authenticationProvider.name.null
authenticationProvider.name.orcid
authenticationProvider.name.orcid-sandbox
authenticationProvider.name.shib
citationFrame.banner.countdownMessage.seconds
ingest.csv.invalidHeader
ingest.csv.lineMismatch
ingest.csv.nullStream
ingest.csv.recordMismatch
For advanced.search.datasets.persistentId.tip and advanced.search.files.persistentId.tip, their values are different. I also extract the keys from Bundle_zh_CN.properties and find no duplicate keys.

**Comment by pengchengluo** [comment]
@scolapasta that's wonderful! We also hope to continually update the Bundle_zh_CN.properties file. 

Besides, could you explain the "bringing back the forks" for me since I can't understand it exactly and there seems little information about it on the Internet. Thank you~

**Comment by pdurbin** [comment]
@pengchengluo you might remember that at lunch during the Dataverse Community Meeting I showed you a spreadsheet were we keep track of forks that we know about:

<img width="457" alt="screen shot 2018-06-26 at 9 38 41 pm" src="https://user-images.githubusercontent.com/21006/41948187-8298a26e-7989-11e8-9a9c-efb4827a504b.png">

**Comment by pengchengluo** [comment]
@pdurbin Oh, yes, I see.

**Comment by pdurbin** [comment]
@pengchengluo thanks for pull request #4798. It only contains changes to Bundle_zh_CN.properties so I'm sure it's save to merge. It's interesting to see that "Dataverse" has been translated!

dataverse=\u6570\u636e\u7a7a\u95f4

数据空间 = data space

<img width="894" alt="screen shot 2018-07-02 at 9 02 05 am" src="https://user-images.githubusercontent.com/21006/42165626-a2ce57d0-7dd6-11e8-8d4f-382520ac3274.png">

**Comment by pengchengluo** [comment]
@pdurbin as far as I know, the dataverse comes from "data + universe“, so we use the '数据空间' to represent it whenever the dataverse references the dvObject. If dataverse references the software or platform, I try to remain as it is, i.e. dataverse.

**Comment by pdurbin** [comment]
@pengchengluo interesting! It drive some of the people on the team crazy when I say this, but we sometimes refer to the DvObject dataverse as "small d dataverse" which is different than Dataverse, the software/platform. 😄 Maybe we need a better name for the DvObject. @sbarbosadataverse calls it a "personal space" during her training. This reflects how it can be customized, branded, etc.
