### ISSUE TITLE
NPE in DatasetVersion.getPublicationDateAsString prevents dataset page from rendering

### ISSUE THREAD

**Issue by PaulBoon** [IQSS/dataverse#4788]
One of our datasets is not being displayed because of a null pointer exception. 
Running our fork of v4.8.6 (https://github.com/DANS-KNAW/dataverse/releases/tag/v4.8.6-DANS-1).

The dataset.xhtml webpage displays: "Internal Server Error - An unexpected error was encountered, no more information is available."
The logs show: 
```
Error Rendering View[/dataset.xhtml]
javax.el.ELException: /dataset.xhtml: java.lang.NullPointerException
...
	at edu.harvard.iq.dataverse.DatasetVersion.getPublicationDateAsString(DatasetVersion.java:1210)
...

```
Looking at https://github.com/IQSS/dataverse/blob/874a944476ed1647d48f69e6c0bd597716644d35/src/main/java/edu/harvard/iq/dataverse/DatasetVersion.java#L1210

This indeed does something with Date time formatting. 
When looking in the database the dataset's publicationdate is '2017-01-18 00:00:00', but this is the case for other datasets as well and those are rendered fine.

**Comment by pameyer** [comment]
@PaulBoon is it possible that the dataset in question is attempting to use one of the DatasetFields / metadata elements as the publication date?

**Comment by pdurbin** [comment]
@PaulBoon especially if the dataset is published, can you please let us know its Handle so we can poke around a bit? It looks like I was the last one to touch that code in ad71c6a but I thought I was simply moving logic from GUI-only code to a place deeper in the system so it can be using from API code as well.

**Comment by PaulBoon** [comment]
It's with a handle; https://dataverse.nl/dataset.xhtml?persistentId=hdl:10411/20850
That will give you the 500 @pdurbin.

**Comment by PaulBoon** [comment]
I had a look at the dataset.xhtml, looks like it is in https://github.com/IQSS/dataverse/blob/874a944476ed1647d48f69e6c0bd597716644d35/src/main/webapp/dataset.xhtml#L27

Maybe I can try to get some metadata via the API and hope it doesn't fail and returns something @pameyer

**Comment by PaulBoon** [comment]
Got some metadata, but all files are restricted so I don't show all details here. 

```
{
  "status": "OK",
  "data": {
    "id": 1506,
    "identifier": "20850",
    "persistentUrl": "https://hdl.handle.net/10411/20850",
    "protocol": "hdl",
    "authority": "10411",
    "publisher": "DataverseNL",
    "publicationDate": "2017-01-18",
    "latestVersion": {
      "id": 690,
      "versionNumber": 1,
      "versionMinorNumber": 0,
      "versionState": "RELEASED",
      "productionDate": "Production Date",
      "lastUpdateTime": "2017-02-14T10:15:16Z",
      "createTime": "2016-12-15T13:03:30Z",
      "license": "NONE",
      "metadataBlocks": {
        "citation": {
...
            {
              "typeName": "dateOfDeposit",
              "multiple": false,
              "typeClass": "primitive",
              "value": "2016-12-01"
            },
            {
              "typeName": "timePeriodCovered",
              "multiple": true,
              "typeClass": "compound",
              "value": [
                {
                  "timePeriodCoveredStart": {
                    "typeName": "timePeriodCoveredStart",
                    "multiple": false,
                    "typeClass": "primitive",
                    "value": "1996"
                  },
                  "timePeriodCoveredEnd": {
                    "typeName": "timePeriodCoveredEnd",
                    "multiple": false,
                    "typeClass": "primitive",
                    "value": "2016"
                  }
                }
              ]
            },
            {
              "typeName": "dateOfCollection",
              "multiple": true,
              "typeClass": "compound",
              "value": [
                {
                  "dateOfCollectionStart": {
                    "typeName": "dateOfCollectionStart",
                    "multiple": false,
                    "typeClass": "primitive",
                    "value": "1996"
                  },
                  "dateOfCollectionEnd": {
                    "typeName": "dateOfCollectionEnd",
                    "multiple": false,
                    "typeClass": "primitive",
                    "value": "2016"
                  }
                }
              ]
            }
          ]
        },
...
```

**Comment by pdurbin** [comment]
@PaulBoon thanks, that's what I was going to check too. As you said, it looks like we don't see a 500 error when we serialize the dataset as JSON using the API. Is this a bug you feel like working on? Do you feel like trying to make a pull request?

**Comment by PaulBoon** [comment]
I was kind of hoping that the eyeballing by you would reveal a problem spot in the GUI code, but there is nothing indicating a solution yet. Also it's not something I can reproduce on a test system, which makes it hard to investigate further. 

Because the database looked OK, I suspected the Solr index and tried to do a reindex; this is what happened: 

```
$ curl http://localhost:8080/api/admin/index/dataset?persistentId=hdl:10411/20850;tail -F /usr/local/glassfish4/glassfish/domains/domain1/logs/server.log
{"status":"OK","data":{"message":"Reindexed dataset hdl:10411/20850","id":1506,"persistentId":"hdl:10411/20850","versions":[{"semanticVersion":"1.0","id":690}]}}
[2018-06-27T11:33:52.218+0200] [glassfish 4.1] [INFO] [] [edu.harvard.iq.dataverse.search.IndexServiceBean] [tid: _ThreadID=27 _ThreadName=http-listener-1(2)] [timeMillis: 1530092032218] [levelValue: 800] [[
  unable to convert End: 2016  into YYYY format and couldn't index it (dateOfCollectionEnd)]]

[2018-06-27T11:33:52.225+0200] [glassfish 4.1] [INFO] [] [edu.harvard.iq.dataverse.search.IndexServiceBean] [tid: _ThreadID=27 _ThreadName=http-listener-1(2)] [timeMillis: 1530092032225] [levelValue: 800] [[
  unable to convert Start: 1996  into YYYY format and couldn't index it (timePeriodCoveredStart)]]

[2018-06-27T11:33:52.226+0200] [glassfish 4.1] [INFO] [] [edu.harvard.iq.dataverse.search.IndexServiceBean] [tid: _ThreadID=27 _ThreadName=http-listener-1(2)] [timeMillis: 1530092032226] [levelValue: 800] [[
  unable to convert End: 2016  into YYYY format and couldn't index it (timePeriodCoveredEnd)]]

``` 

Maybe it's related?

**Comment by pdurbin** [comment]
@PaulBoon it's a good thought but loading the dataset page (or file page) doesn't hit Solr. We're tracking that "unable to convert" bug over at #4558.

I wanted to ask you how easy you think it would be able to reproduce. Sounds like it might be tricky. Something unexpected in the data. Is this a new dataset? Was it migrated from DVN 3? Anything interesting or unique about its history?

**Comment by pdurbin** [comment]
http://phoenix.dataverse.org/schemaspy/latest/relationships.html might be helpful for you:

![screen shot 2018-06-28 at 3 13 28 pm](https://user-images.githubusercontent.com/21006/42055691-db525a46-7ae5-11e8-84e8-35c04ef147d6.png)

@scolapasta or @kcondon  any ideas? This dataset was migrated.

**Comment by pdurbin** [comment]
@PaulBoon I'm wondering if this should be a support ticket instead of a GitHub issue since it's specific to your data, one of your migrated datasets. If you like that idea you could try emailing support@dataverse.org

**Comment by PaulBoon** [comment]
Sorry, I missed the empty releasetime in the datasetversion table, so it is indeed a migration issue.

**Comment by pdurbin** [comment]
@PaulBoon no problem and thanks for closing this issue.
