### ISSUE TITLE
Request Access + Add Data - Log In link broken

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#4790]
Found this locally, but replicated on [demo](https://demo.dataverse.org/dataset.xhtml?persistentId=doi:10.5072/FK2/UFPC27). Click either of the Request Access buttons on the dataset pg without being logged in, and you are prompted with a popup with links to Sign Up or Log In. When you click the Log In link, you land on a Page Not Found (404) page with an ugly looking message block on it.

This is also the case for the Request Access popup > Log In link on the file pg. Also discovered that the Log In link on the Add Data popup from the dataverse pg is broken in the same fashion.

![screen shot 2018-06-27 at 4 10 33 pm](https://user-images.githubusercontent.com/687227/41997001-ae72989a-7a24-11e8-99f1-57a54ca92051.png)

**Comment by mheppler** [comment]
Looking into recent changes made to `search-include-fragment.xhtml` this appears to be a bug that was introduced when the PR for issue #4583 was merge.

Here is the current popup msg on that page...

```
<h:outputFormat styleClass="text-danger" value="#{dataverseHeaderFragment.signupAllowed ? bundle['dataverse.results.dialog.addDataGuest.msg.signup'] : bundle['dataverse.results.dialog.addDataGuest.msg']}" escape="false">
                <f:param value="#{dataverseHeaderFragment.getSignupUrl(navigationWrapper.redirectPage)}"/>
            </h:outputFormat>
```

It appears the new `getSignupUrl()` logic is being applied to both the Sign Up and Log In links, when it should only be applied to Sign Up. We most likely will need to simply revert the Log In link to use the original `f:param`...

```
<f:param value="#{navigationWrapper.redirectPage}"/>
```

**Comment by mheppler** [comment]
Added back `<f:param value="#{navigationWrapper.redirectPage}"/>` that was needed for log in link. The original change for #4583 should have only been applied to the Sign Up links, but it was mistakenly applied to the Log In links as well.

Applies to:
- "Add Data" button on datavese pg
- "Request Access" buttons on dataset pg (table header and table row)
- "Request Access" button on file pg

**Comment by sekmiller** [comment]
Looks good. Moved to QA.
