### ISSUE TITLE
Make "download as original" disappear from download options, when there is no saved original. 

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#4796]
This is the small issue that Sonia asked us to patch in production 2 weeks ago, since it was kind of important-ish:
We were showing "download original" for every tabular file; even when there is no saved original. 
This affects only a few tabular files - the oldest ones we grandfathered in from the VDC (!). But some of them also happen to be super important datasets and files. 
(this may have been made worse somewhat recently, when we rearranged the order of download options in the pulldown, making "original" the top option - so the users are now more likely to click it...)
So anyway, the fix is super simple - I'm creating a PR...

**Comment by pdurbin** [comment]
I'm troubled that the original files are missing but I guess there's nothing that can be done about that. Pull request #4797 seems fine. Thanks for creating it, @landreev even while on vacation!

**Comment by kcondon** [comment]
OK, so I have removed the original file from an ingested tabular file and still see download original in list. Should I? It seems like I shouldn't.

**Comment by kcondon** [comment]
Turns out the trigger is not a missing file but originalfileformat='' in the datatable table, as per the code. Works.
