### ISSUE TITLE
File upload: If exceed maximum number of files, says it was exceeded but continues to upload some files.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#4818]
Depending on your perspective, this may be considered robust behavior:

If I upload more than the 1000 file limit, it complains that the maximum amount was exceeded (good) but then continues to upload what files it can (good?). The potential problem is how do you determine easily which files were successfully uploaded and which not?

This is definitely an edge issue but not for someone who has lots of files and is unaware of the working limit.

I am not sure if there is a good solution: in this case I was not uploading a zip file to be extracted but rather was dragging and dropping from a directory.

I'm guessing the issue is that we don't know the # files until they are already transferred. Since the uploaded files are displayed, sorted by filename, that would allow someone to sort their upload list and compare that way.  So maybe a non issue.

**Comment by pdurbin** [comment]
As I just mentioned at https://github.com/IQSS/dataverse/issues/7227#issuecomment-993698489 as of 5.9 on my laptop anyway, you can't even read the warning message anymore. It just flashes by.

Also, as that issue indicates, this setting is undocumented.

I completely agree with "The potential problem is how do you determine easily which files were successfully uploaded and which not?"

Overall, not a great user experience.
