### ISSUE TITLE
DEPENDENT identifiers for files do not use :Shoulder

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#4823]
We ran across this on a test server (using 10.5072/FK2) trying to generate datafile DOIs for copies of production datasets with DOIs starting with 10.5064/F6 : the dependent option for datafile ids creates DOIs of the form 10.5072/F6ABCDEF/GHIJKL  - using the defined protocol and authority, but grabbing the shoulder as part of the parent identifier. In our case, attempts to create file DOIs then fail since they are not using the shoulder allowed for testing. 

While the solution for testing may be 'don't do that', I think this will be a future issue for anyone who changes shoulders, or gets a new shoulder when changing authority, particularly if they loose the ability to mint identifiers in the old shoulder. (Although it only affects files in datasets that are assigned an identifier prior to a :Shoulder change that occurs before the files are also registered. However, this would be the case when files are added in the future to create a new dataset version as well, so it isn't just for a limited time period.)

As a work-around, I've added a test in our code to see if the dataset shoulder matches the :Shoulder key and, if not, to strip the dataset DOI to 6 chars (which removes the shoulder in all cases for us and should for anyone who's been using the normal dataverse generators) and then add the new shoulder. If this is an issue for others, I can submit that code, but there may be other designs that are better for the long term:

- always prepend the :Shoulder
- prepend the :Shoulder to the whole dataset identifier (including the old shoulder) if it doesn't match
- store the shoulder separately so that it can be removed safely without knowing the length of the non-shoulder part, etc.
- store a list of previous shoulders that should be stripped
- remove the DEPENDENT option because it embeds semantics in the identifier :-)

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
