### ISSUE TITLE
File DOI registration with EZID does not make DOIs public

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#4828]
Using the ezid test server, I was able to create file DOIs with the registerDataFileAll api call but the resulting DOIs are 'reserved' rather than 'public'. I was able to track this to the logic in RegisterDvObjectCommand which only does setIdentifierRegistered(true); after the call to publicizeIdentifier. For the DOIEZIdServiceBean, publicize tries to re-createIdentifier() if isIdentifierRegistered() is not true, which fails (identifier already exists). While EZID is on its way out, the problem would affect any registerWhenPublished() == false id provider.

I have a fix that I will post, but it may be a few days. In the meantime, I think going to 4.9.1 with EZID and running registerDataFileAll will leave identifiers in 'reserved' and throw error messages about duplicate ids in the log.

**Comment by pdurbin** [comment]
@qqmyers thanks for making pull request #4830. I just moved this issue to code review at https://waffle.io/IQSS/dataverse

**Comment by pdurbin** [comment]
@qqmyers I'm sorry to do this but can you either fix up pull request #4830 or make a new one that doesn't have the whitespace changes? It's difficult to see what you changed.

**Comment by pdurbin** [comment]
@qqmyers I just remembered that by adding `?w=1` to the URL like https://github.com/IQSS/dataverse/pull/4830/files?w=1 I can see the "diff" without the whitespace changes:

![screen shot 2018-07-20 at 1 53 55 pm](https://user-images.githubusercontent.com/21006/43017562-9156613a-8c24-11e8-9d42-08b8962ee297.png)

However, now there's a merge conflict with `src/main/java/edu/harvard/iq/dataverse/engine/command/impl/RegisterDvObjectCommand.java`

**Comment by pdurbin** [comment]
@qqmyers I see you resolved the merge conflict. Thanks! I assume you're ready for code review, but if not, please let us know!

**Comment by qqmyers** [comment]
+1 - ready to go.

**Comment by pdurbin** [comment]
@qqmyers cool. I hope you don't mind but in 8712c94 I reverted the whitespace changes to make it easier to code review the pull request.

**Comment by qqmyers** [comment]
That's great. I try not to change whitespace but was rushed with that commit.

**Comment by pdurbin** [comment]
@qqmyers I see you moved those methods within the null check. Thanks. @sekmiller and I just talked about this issue and he'll take a look at your pull request.

**Comment by kcondon** [comment]
@qqmyers  I've tested this and found that though it does not register unpublished files, it still registers published files as reserved rather than public

**Comment by qqmyers** [comment]
@kcondon  - Hmm - we just ran ezid publication of files on qdr and I verified that they were public. Our deployed code is more like the initial commits here, so perhaps something in the shuffle of code inside if statements broke it. I'm on travel, but will look again as I can to see if I can spot an issue.

**Comment by qqmyers** [comment]
FWIW - the code at https://github.com/QualitativeDataRepository/dataverse/blob/v4.9.1-qdr-4777/src/main/java/edu/harvard/iq/dataverse/engine/command/impl/RegisterDvObjectCommand.java works for QDR. Other than moving the updates inside the test to see if an identifier exists, and merging with the change to use the GlobalIdServiceBean class, I don't see any difference that would cause it not to work with ezid...

**Comment by kcondon** [comment]
@qqmyers I think the branch you just mentioned is different from the one in the PR, no?
QualitativeDataRepository:4828-DOI_registration_with_EZID_does_not_make_DOIs_public

**Comment by qqmyers** [comment]
@kcondon Yes. The URL in my comment is to QDR's current deployment. My point was that it works and I don't see anything different enough from the PR to cause what you're seeing. Unless you can see something, it would have to be something in the recent merge or some config issue, etc. The only guess I have would be that this change won't update existing reserved dois to public, so if some had been created before this patch, you'd still see them. 
When I get back from travel, I can try updating the qdr branch to use exactly the same code as the PR and see if that reproduces the issue.

**Comment by kcondon** [comment]
OK, thanks. I've retested it and see the same "reserved" behavior.
I'm attaching a copy of my test db for you. It was created using 4.8.6, 4 datasets, 2 published, 2 unpublished, upgraded to 4.9.1, before running register endpoint. I'll also attach a copy after running it.
[testdb.zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5798d98d18ccf10e00ce215e/125516c66e82c728ace21e0d46fc9189378681ebc3abaf51ab57f5973d047d317c51a77923d4e578b9117e590b0c4bfa41585b4cadf8d879b4aa2e32db025fb28c341521842f1bbeb98b15be04b923884d85b2ba8b4cc4e92f68.zip)
[testdbpostapi.zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5798d98d18ccf10e00ce215e/125516c66e82c728ace21e0d46fc9189378681b980faab42b454b2d86b56357c2301a03f32dfa17dea4629525e094efa420d5710affcdf2ba6b234218b0d59ffcd7f1d2598694ef1e1c84afd13b0328a488fb7b9894fc3ea3d23e78a89473d0c48.zip)

**Comment by qqmyers** [comment]
@kcondon - Thanks. What are you seeing in the log? For the original problem, there were warnings from EZID about the DOI already existing (because publicize calls create if the id isn't registered and create then fails.). With Fine logging, publicize adds a message but by default you should be seeing the warnings from within the create call.

**Comment by qqmyers** [comment]
@kcondon - OK - a good clue in the log:  it looks like the protocol from the dvObject coming in is null and due to that, the new code in GlobalIdServiceBean is returning null instead of a bean - you've got the SEVERE log message about that. Any exception from that would get caught and ignored in the command class. Not sure I understand how you get reserved ids at all yet, but something to dig into now...

**Comment by qqmyers** [comment]
@kcondon - When you said 'reserved' - did you just mean that the doi is in the DB or that you could see the DOI in EZID as 'reserved'?. Hopefully the former - I can see how the DOI would get generated before the null bean would cause an error and will add a fix in the PR, but if EZID is actually getting contacted, something else is going on. FWIW - this PR fixes the issue where EZID is contacted but the DOI is never transitioned from their 'reserved' to 'public' state.

**Comment by kcondon** [comment]
@qqmyers I could see the doi in EZID as reserved

**Comment by qqmyers** [comment]
@kcondon - Hmm - I don't understand that unless some other part of the code sees the generated Id and calls EZID . Can you try the modification I just committed to the PR? It should allow the command to succeed and create IDs and make them public at EZID, and get rid of the SEVERE message in the logs. If it works, I can look a bit more and see if I can find if there is somewhere else EZID could be getting called to create but not publish/make public the DOI.

**Comment by kcondon** [comment]
@qqmyers your branch fails to build -refresh from /develop since we've fixed a failing test today

**Comment by qqmyers** [comment]
@kcondon - its merged...

**Comment by kcondon** [comment]
@qqmyers Your last fixes have resolved the issue. I'll merge this now.

**Comment by qqmyers** [comment]
Yeah! So ftr the second commit handles a change between IdServiceBean and GlobalIdServiceBean where the latter no longer handles a null protocol parameter (by finding the currently configured one in the context) in the getBean() method. I did a quick search back through other places that call getBean() and I think all of the others handle situations where the protocol will always be defined. It's only for file during publication that their protocols will be null.
