### ISSUE TITLE
Harvest: OAI client should follow http->https redirect since oai server validation allows http.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#4831]
Configuring an oai client allows http to be used in oai server url, as long as the server is valid. However, the actual harvest fails when it receives a 302 to move to https.

**Comment by stevenferey** [comment]
Hello,

I tried to harvest an OAI server compatible with the HTTP protocol, e.g.: `http://cds.unistra.fr/registry/?verb=ListIdentifiers&metadataPrefix=oai_dc`

Tested with the devleop branch, it is not possible to fill in an OAI server with the HTTP protocol :

![Capture d’écran du 2024-09-26 18-13-43](https://github.com/user-attachments/assets/6a0074d3-9b29-4eb5-9388-a05ff7455acf)

It is however possible to declare a harvesting client with the API and fill in an OAI server with the HTTP protocol.
In this case, an error is raised during harvesting : 

```
Caused By Exception.................... java.nio.channels.UnresolvedAddressException null
StackTrace: 
java.base/sun.nio.ch.Net.checkAddress(Unknown Source)
java.base/sun.nio.ch.Net.checkAddress(Unknown Source)
java.base/sun.nio.ch.SocketChannelImpl.checkRemote(Unknown Source)
```

**Comment by pdurbin** [comment]
@stevenferey interesting. Are you considering creating a pull request to fix this? 😄

**Comment by stevenferey** [comment]
This is not planned by the team at the moment !

Do you want a new issue to be created to allow OAI server harvesting with HTTP protocol?

**Comment by pdurbin** [comment]
Sure, if you're interested in this, I think a fresh issue would be nice.

**Comment by pdurbin** [comment]
@stevenferey thanks for creating this new issue:

- #10913
