### ISSUE TITLE
Feature: use ePIC PIDs in addition to DOI and EZID

### ISSUE THREAD

**Issue by poikilotherm** [IQSS/dataverse#4833]
We would like to have EPIC PIDs supported within Dataverse. See also http://www.pidconsortium.eu

I heard about a possible future installation of Dataverse at Göttingen university. The GWDG is the current hoster of EPIC services, so maybe they already try to integrate this?

There are good chances we at Forschungszentrum Jülich can provide man power for this feature, too.

Any interest in this overseas? ;-)

**Comment by djbrooke** [comment]
Hi @poikilotherm, good to hear from you! More PID provides are always welcome! 

You should connect with @fbgesis and @4tikhonov as they've been working on and discussing a plugin provider in #4106. They'll be meeting in Germany soon and it may be an opportunity to combine resources.

**Comment by poikilotherm** [comment]
Closing this in favor of #4106 and #5093.
