### ISSUE TITLE
DatasetPage limit calls to GetPrivateUrlCommand

### ISSUE THREAD

**Issue by sekmiller** [IQSS/dataverse#4834]
Currently the init method of the DatasetPage calls the getPrivateUrlCommand for every page load regardless of whether the user has permission to run the command. Permission errors are logged to the Action Log Record table causing some unnecessary noise. If we limit the calls to only those users who have ManageDataset permission we can reduce the noise.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
