### ISSUE TITLE
Writing to Action Log Record table fails when the dvObject name is "long"

### ISSUE THREAD

**Issue by sekmiller** [IQSS/dataverse#4835]
On Dataset Page load, when the getPrivateUrlCommand fails due to a permission error a record is written to the Action Log Record table.  The Info column of the table is 1024 characters and we try to write something along the lines of:
:[15054 Firefox]  (Can't execute command edu.harvard.iq.dataverse.engine.command.impl.GetPrivateUrlCommand@415a97d8, because request [DataverseRequest user:[GuestUser :guest]@0:0:0:0:0:0:0:1] is missing permissions [ManageDatasetPermissions] on Object Fire (...)

If the Dataset name is too long the character limit of the field is exceeded and a Database exception is thrown so that the Dataset Page won't load.

There may be other cases which could cause this error, so a more general fix might be needed. At least the size of the String for the info column should be tested and altered if it's too large.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
