### ISSUE TITLE
Guestbook - Broken Datatset/File Pg UI

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#4838]
A [support issue](https://help.hmdc.harvard.edu/Ticket/Display.html?id=264255) came in for a dataset on production that -- among other things -- had a broken Guestbook form at the bottom of the dataset pg (also discovered to be broken on the file pg as well).

Was able to replicate it on [dvn-build](https://dvn-build.hmdc.harvard.edu/dataset.xhtml?persistentId=doi%3A10.5072%2FFK2%2FZYIAPY). Here is what is needed to replicate it:
- any user will see this bug (as opposed to previously suspected super user only)
- dataset has one or more ingested tabular data file
- dataset has guestbook with one or more custom, multiple choice question
- dataverse installation setup with Explore btn displayed**

(**See latest comment from me on 8/17 below...)

<img width="1215" alt="screen shot 2018-07-13 at 11 25 29 am" src="https://user-images.githubusercontent.com/687227/42699705-86a94cce-868f-11e8-813e-6a5bf20b7f54.png">

Also replicated this locally on the `develop` branch. Unfortunately the Glassfish server logs are clean when loading a dataset with a broken guestbook popup in the UI. There was an error in console of the browser element inspector however.

```
[Error] TypeError: undefined is not an object (evaluating 'd.left')
	(anonymous function) (primefaces.js.xhtml:23:10214)
	dispatch (jquery.js.xhtml:25:41043)
	handle (jquery.js.xhtml:25:37187)
```

**Comment by djbrooke** [comment]
Thanks @mheppler for the detailed investigation. @sekmiller is going to take a closer look (timebox 30 minutes or an hour) and bring it back to the team for estimation.

**Comment by pdurbin** [comment]
For the record, line 136 is `<f:selectItems value="#{customQuestionResponse.responseSelectItems}" />`: https://github.com/IQSS/dataverse/blob/v4.9.1/src/main/webapp/file-download-popup-fragment.xhtml#L136

**Comment by mheppler** [comment]
Anything we learn about optimizing the popups should be added to for further code refactoring _Dataset Publish/Submit for Review - Optimize Button/Popup Code #1664_.

**Comment by mheppler** [comment]
While trying to replication this bug on my new installation of Dataverse, I did not see a broken guestbook popup as I had previously on my localhost, with the criteria outlined in my original comment above. It wasn't until I had set up TwoRaven and the Explore btn displayed for the guestbook popup to appear broken on my dataset pg. This is a great lead and hope to have this diagnosed quickly.

<img width="970" alt="screen shot 2018-08-17 at 1 08 00 pm" src="https://user-images.githubusercontent.com/687227/44279236-9f4ad400-a21e-11e8-9249-938bc6410334.png">

**Comment by mheppler** [comment]
Moved button render logic to ui:fragment to fix dataset pg layout bug related to guestbook popup. For some reason the `jsf:rendered` passthrough logic on the Explore buttons in file-download-button-fragment.xhtml was breaking the layout. Putting that render logic into a `ui:fragment` tag resolved the issue.

This same method of using jsf passthroughs to apply render logic to HTML button tags is used in two other places in the app that I suggest get reviewed.

Harvesting Clients - add client workflow, cancel button

```
<button type="button" jsf:rendered="#{harvestingClientsPage.initialSettingsValidated}" class="btn btn-default" onclick="PF('newHarvestingClientForm').hide()" value="#{bundle.cancel}">#{bundle.cancel}</button>
```

Harvesting Sets - add set workflow, cancel button

```
<button type="button" jsf:rendered="#{harvestingSetsPage.setQueryValidated}" class="btn btn-default" onclick="PF('newOAISetForm').hide()" value="#{bundle.cancel}">#{bundle.cancel}</button>
```

There are also a handful of other HTML buttons (e.g. dataverse-user, manage-guestbooks, superuser) in the app that use `jsf:action` passthroughs. Based on the number of those found, I suspect they are also functioning properly.

**Comment by mheppler** [comment]
Also, was able to replicate the broken dropdown menu in the paginator, as well as borken tabs that were reported in #4967. Did not check the publish workflow however.

**Comment by kcondon** [comment]
I can reproduce the publish issue on /develop: it shows popup but when click continue to publish, does nothing.

**Comment by mheppler** [comment]
Fixed similar render logic on Submit for Review button on the dataset pg. This one was harder to replicate, but it appears that if you have a dataset with 11 or more files to display the paginator and a Submit for Review button, the popup does not work.

My comment above about this render logic issue only being found in the harvesting pgs apparently was incorrect, due to an error in how I was searching for this render logic. Another search shows that we use the `jsf:rendered` passthrough 340 times in 42 files. I am continuing to go through and see how many of those are buttons, and of those, how many are broken.

**Comment by qqmyers** [comment]
FWIW - I found the Submit for Review error independently and fixed it by changing the <button> to be a <p:commandLink> to be the same as the other 'button's in that area (and changing jsf:rendered to rendered as they have as well.) As far as I can tell, there's no reason for this button to be different than the others...
