### ISSUE TITLE
Import API: Specifying the PID in json does not work.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#4839]
Part of the original design for import/migration API was to allow specifying the PID in json rather than on the command line. Since it was not working, the text referencing it was removed from the doc, to be fixed and added back later. This ticket covers that work.

**Comment by djbrooke** [comment]
@michbarsinai - I'm assigning this one to you. I wanted to get the PR for #3083 merged in, and this was the remaining issue. Thanks for investigating!

**Comment by kcondon** [comment]
Tested and import with pid on command line as well as in json work but noticed a few issues:
1. pid in json does not check/ensure the pid already exists as it does on command line.
2. example json in doc does not work for pid in json and shows shoulder in authority when should be prefix on identifier. maybe just use current dataset-package-files.json that does work as example and also provide a link to it.
3. dataset-package-files.json also has shoulder in authority when it now is moved as prefix to identifier.

Otherwise, works great!

**Comment by pdurbin** [comment]
Last week I mentioned to @michbarsinai that he should be aware of the regex that was added to https://github.com/IQSS/dataverse/blob/v4.9.2/src/main/java/Bundle.properties#L2036 for #4811.

As of this writing, here's the regex:

    pid.allowedCharacters=^[A-Za-z0-9._/:\\-]*

**Comment by RightInTwo** [comment]
Is there currently a workaround for this?

**Comment by pdurbin** [comment]
@RightInTwo nope. Your DOIs don't conform to the regex above? Can you please provide us with an example? Or are you having some other sort of problem? What error are you getting?

**Comment by RightInTwo** [comment]
@pdurbin Hi Phil, I deleted my comment as I had a wrong understanding of the purpose of the import function (see my hijacking of #5104) . You may delete your answer as well :) Thank you!

**Comment by pdurbin** [comment]
@RightInTwo ok, I'll delete my answer and yours and this one. 😄

**Comment by pdurbin** [comment]
Use the new migration API instead: https://guides.dataverse.org/en/6.0/developers/dataset-migration-api.html
