### ISSUE TITLE
API tests failing on phoenix server after 3083-support-migration-with-dois branch was merged

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#4840]
Pull request #4606 (3083-support-migration-with-dois branch) was just merged and now the following tests in the API test suite are failing:

- DatasetsIT.testCreatePublishDestroyDataset
- DatasetsIT.testExport
- DatasetsIT.testExcludeEmail
- DatasetsIT.testPrivateUrl
- SwordIT.testCreateDatasetPublishDestroy
- SwordIT.testDeleteFiles

<img width="1552" alt="screen shot 2018-07-13 at 12 36 15 pm" src="https://user-images.githubusercontent.com/21006/42703251-0827f7fa-869a-11e8-99d2-5ce51a76b112.png">

We should investigate and correct these failures before making the next release (currently planned to be 4.9.2).

**Comment by pdurbin** [comment]
Interesting. On the same commit ( 06b5e92 ), I cannot reproduce any of these failures in docker-aio. The test suite passes. The investigation should focus on why we are seeing failures above on the phoenix server.

**Comment by pameyer** [comment]
changes to `scripts/database/drop-all.sh` suggested possible cleanup issues; repeating runs of `run-test-suite.sh` with same container in docker-aio suggested this was less likely (aka - continued to pass).

**Comment by pdurbin** [comment]
@pameyer thanks. I don't think it's that drop script because phoenix doesn't use it.

What's actually failing is `DestroyDatasetCommand` and locally (not commited) I'm playing around with disabling the cleanup of datasets that were created by tests. Not a great solution, but having the test suite pass is more important to me that the cleanup.

One difference between phoenix and docker-aio is that the former is using DataCite and the latter uses EZID. Right before DestroyDatasetCommand runs, I see this in server.log: `A system exception occurred during an invocation on EJB DOIDataCiteRegisterService, method: public java.lang.String edu.harvard.iq.dataverse.DOIDataCiteRegisterService.registerIdentifier(java.lang.String,java.util.Map,edu.harvard.iq.dataverse.DvObject) throws java.io.IOException`

Is anyone reading this using DataCite? @sekmiller @kcondon others? Does destroying datasets work for you?

**Comment by sekmiller** [comment]
I'm running DataCite locally and I'm seeing failing tests in DatasetsIT on Destroy Dataset.
DataCite recently changed the way they mint (or not mint) DOIs in their test environment (10.5072/FK2) IT may have something to do with it. I'll take a closer look.  

By the way I was fine until I got the latest from DEV with 3083.

**Comment by pdurbin** [comment]
@sekmiller yes, I'm quite sure that merging pull request #4606 lead to the regression. I just opened #4843 specifically about no longer being able to destroy datasets when using DataCite rather than EZID as your DOI provider.

**Comment by pdurbin** [comment]
I just made a pull request for #4843 which I think will resolve this issue as well. I guess I'll just sit on the other issue has been merged.

**Comment by pdurbin** [comment]
As I mentioned at standup today, this issue is still blocked by the pull request for #4843.

**Comment by pdurbin** [comment]
Now that pull request #4845 has been merged (the one for #4843), the API test suite is passing again on the phoenix server so I'm closing this issue. Here's a screenshot from https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-apitest-develop/ (blue means passing):

![screen shot 2018-07-17 at 2 43 09 pm](https://user-images.githubusercontent.com/21006/42838898-f6a8955a-89cf-11e8-97bf-da07e522e7c7.png)
