### ISSUE TITLE
Update French property files

### ISSUE THREAD

**Issue by JayanthyChengan** [IQSS/dataverse#4856]
Our ScholarsPortal team would like to add french property files into Dataverse code repository.  And in future, any new terms added to English property files will be translated to French and keep in Sync with Dataverse codebase.  Thanks

**Comment by pdurbin** [comment]
@JayanthyChengan thanks for making pull request #4857. It's just translation files, no risk to the app, so I'm moving it to QA.

**Comment by mheppler** [comment]
Quick Draw Durbin gave this an approval before I could a single comment into my review. Trying to look at this in a little more depth than a superficial 5 min glance. Moving out of QA and adding comments to the PR in the "Files changed" view.

**Comment by pdurbin** [comment]
@JayanthyChengan @mhvezina not a big deal but two additional bundle keys were recently added in pull request #4808 if you'd like to go ahead and add them as well. To be clear, I'm fine with merging your pull request as-is but I thought I'd mention this. The translations are always going to lag behind the "develop" branch a bit because that the branch we merge pull requests into.

**Comment by pdurbin** [comment]
@JayanthyChengan yesterday at standup @scolapasta mentioned that you're looking at ways of translating Java apps without bundle property files that are in the main Maven project. Is that right? Any findings so far? I'm curious about how other Java apps like Jenkins handle translations but I haven't looked.

**Comment by JayanthyChengan** [comment]
To @pdurbin @scolapasta :
Created new branch : https://github.com/scholarsportal/dataverse/tree/dataverse-externalProperty and tried the below steps

Step 1: 
Created a JVM options 
/usr/local/glassfish4/glassfish/bin/asadmin create-jvm-options "-Ddataverse.lang.directory=/tmp/lang"

Step 2:
And saved language.json and bundle.properties, bundle_fr.properties in /tmp/lang

- Used language.json file in DataverseLocaleBean  to load language list for UI 

 
Step 3:
Modified BundleUtil.java to access property files from dataverse.lang.directory and create resourceBundle
 
Step 4:
Face-config.xml

<resource-bundle>
    <base-name>edu.harvard.iq.dataverse.util.LocalBundle</base-name>
    <var>bundle</var>
</resource-bundle>  

Stp 5: 
Created LocalBundle.java , to load values from resourceBundles for JSF Internationlization

**Comment by pdurbin** [comment]
@JayanthyChengan thanks for linking to your branch! Interesting! @landreev you might want to check this out.

**Comment by pdurbin** [comment]
What's the status of this issue?

**Comment by JayanthyChengan** [comment]
@pdurbin:
 Merged the latest code from develop branch to https://github.com/scholarsportal/dataverse/tree/4856_FrenchPropertyFiles

Bundle_fr.properties is up-to-date with english property until Sept 25th
MimeTypeDisplay.properties is up-to-date
MimeTypeFacets.properties has to be verified for capitalization
Thanks to @mhvezina for translation

The PR which I created last time (https://github.com/IQSS/dataverse/pull/4857) was closed,  
Can I submit new PR to merge latest translation to develop branch.

But not sure how are we planning to maintain the bundle language files, also including metadata property files and etc.

**Comment by JayanthyChengan** [comment]
@pdurbin: created new PR https://github.com/IQSS/dataverse/pull/5121 for this issue.  Thanks
