### ISSUE TITLE
JHove documentation

### ISSUE THREAD

**Issue by CCMumma** [IQSS/dataverse#4861]
As I mentioned on the Community call today, a librarian at UT Austin is working on the Core Trust Seal documentation gathering for the TDR Dataverse and noticed that JHove documentation is lacking in the current user-facing docs. 

Thanks,
Courtney C. Mumma
Deputy Director, Texas Digital Library

**Comment by pdurbin** [comment]
I just created pull request #4899 and moved this issue to code review at https://waffle.io/IQSS/dataverse

@CCMumma you are very welcome to take a look (or have your librarian at UT Austin take a look) at the change at https://github.com/IQSS/dataverse/pull/4899/files and give feedback! As of this writing, here's a screenshot of how the change looks and to give you more context, it would appear on a future version of the page at http://guides.dataverse.org/en/4.9.1/installation/installation-main.html#running-the-dataverse-installer

![screen shot 2018-07-26 at 2 39 40 pm](https://user-images.githubusercontent.com/21006/43281524-e8cad22c-90e1-11e8-9a3b-4a6500ee4e26.png)

**Comment by dlmurphy** [comment]
I've looked over @pdurbin's additions to the guide and they look good to me.
