### ISSUE TITLE
"text/tab-separated-values" changed to "text/tsv" and "Tab-Delimited" changed to "text/tsv", forceReplace=true required after 4044-tsv-ingest2 branch was merged

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#4866]
Pull request #4854 was recently merged and now the FilesIT.test_006_ReplaceFileGood test failing API test is failing:

![screen shot 2018-07-18 at 2 00 50 pm](https://user-images.githubusercontent.com/21006/42899162-287f3d9a-8a93-11e8-8b8f-17638826c9b9.png)

If you use "file replace" on a tsv file, you get the warning "The original file (Tab-Delimited) and replacement file (text/tsv) are different file types." Here's a screenshot:

![screen shot 2018-07-18 at 3 34 53 pm](https://user-images.githubusercontent.com/21006/42905010-c91b30a4-8aa4-11e8-8b4a-299c2d405378.png)

**Comment by pdurbin** [comment]
I just made pull request #4867 and moved it to code review. The behavior of the code changed in pull request #4854. "text/tab-separated-values" changed to "text/tsv" and "Tab-Delimited" changed to "text/tsv" and I updated the assertions in the API test suite. forceReplace=true wasn't required in one of the tests but now it is.

**Comment by pdurbin** [comment]
> suggests that we don't have a "pretty" display name for the "text/tsv" type in the properties bundle; so the real fix should probably be to provide one (It should probably be the same "Tab-Delimited" for both "text/tsv" and "text/tab-separated-values").

@oscardssmith fixed this is c87ea92 and I'll move it to QA if the tests still pass.

**Comment by pdurbin** [comment]
The tests pass on my laptop as of c87ea92 so I'm moving this to QA. I stopped by and talked to @landreev about the change and he's cool with it. @kcondon please note that this latest commit changes the GUI slightly:

![screen shot 2018-07-20 at 11 01 32 am](https://user-images.githubusercontent.com/21006/43009698-5bd6d4c6-8c0c-11e8-9c76-fc79b7d6caff.png)

**Comment by oscardssmith** [comment]
It actually just reverts an un-noticed change that my previous tsv pr created.
