### ISSUE TITLE
Config docs should mention the API and not DB tables

### ISSUE THREAD

**Issue by bricas** [IQSS/dataverse#4870]
As per the IRC chat, the documention for ["Auth Modes: Local vs. Remote vs. Both"](http://guides.dataverse.org/en/latest/installation/config.html#auth-modes-local-vs-remote-vs-both) talks about a database table "authenticationproviderrow" -- the documentation should point people to the API rather than directly to the database.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
