### ISSUE TITLE
404 errors for bootstrap.min.css.map

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#4875]
Looks like the minified CSS from the boostrap upgrade has references to the sourcemap, which is triggering 404 errors (possibly because the sourcemap is `bootstrap.min.css.map` instead a prime-face-ized `bootstrap.min.css.xhtml?version=4.9.1`)

**Comment by pdurbin** [comment]
I can easily reproduce the problem as of 42e6f7d on the phoenix server. Here's a screenshot:

![screen shot 2018-07-23 at 9 46 59 am](https://user-images.githubusercontent.com/21006/43080303-7568a5f6-8e5d-11e8-86ab-cdcec3ae8b9d.png)

@pameyer I'm looking at pull request #4876 and I see that you've commented out `sourceMappingURL` like this:

![screen shot 2018-07-23 at 9 49 20 am](https://user-images.githubusercontent.com/21006/43080429-ba528146-8e5d-11e8-882f-b5f6ef500f6b.png)

If this fixes the 404, great, but I guess I don't completely understand what we did in pull request #4806 to introduce the problem in the first place.

**Comment by pameyer** [comment]
My suspicion is that the older bootstrap version had the sourcemap commented out in the minified CSS, and the newer one didn't (or there's a different in the minification procedure used internally between the two bootstrap versions).

**Comment by pdurbin** [comment]
@pameyer ok, I just search through the git history trying to figure out if we purposefully commented out `sourceMappingURL` in the past. If so, I couldn't find a commit message about it. I went ahead and approved #4876 but before dragging it to QA, I'll let others weigh in. It bothers me a little that we can't use Bootstrap out of the box, that we have to edit these files. It makes me wonder if we would have 404s if we got Bootstrap from a CDN. I'm aware that we backed off of using a CDN in c11c96a as part of our recent Bootstrap upgrade in pull request #4806 (discussion in #4219).

**Comment by pdurbin** [comment]
@pameyer interesting. Are you saying that your pull request actually gets us closer to vanilla Bootstrap?

**Comment by pdurbin** [comment]
@pameyer ok, I went to https://stackoverflow.com/questions/21773376/bootstrap-trying-to-load-map-file-how-to-disable-it-do-i-need-to-do-it and I think I better understand what you're up to in your pull request. I was mistaken when I said you were commenting out something. You're deleting something that's commented out. It's a weird fix but I'm fine with it. Moving to QA.
