### ISSUE TITLE
Provide "bare minimum" R installation instructions; add "haven" package.

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#4878]
We need to provide an easy-ish process (and instructions) for installing basic R functionality (R itself, plus Rserve and a couple other 3rd party libraries) needed to ingest R and export R files. 

As of now, we instruct the users to install the R components by using the installer script maintained as part of the TwoRavens distribution. It installs the above plus all the dependencies that TwoRavens needs (there are many more of those, and they are more finicky to install). So it would help a lot to separate these parts. And provide a simplified installation instruction, in the same section where we provide glassfish, postgresql etc. instructions. 

This is also an opportunity to add the new package "haven" -  that is now required to generate RData files.

**Comment by djbrooke** [comment]
@landreev is this a necessary part of #4676, just called out as a separate issue?

**Comment by oscardssmith** [comment]
No. It just makes #4676 more convenient.

**Comment by djbrooke** [comment]
Got it, thanks.

**Comment by landreev** [comment]
This will address one thing - an R package - that's needed for #4676 to work, among other things. 
But it addresses other issues, that are important/somewhat urgent. As of now, the only way for a Dataverse to get Data Explorer to work, as documented, is to fully install TwoRavens... and that kinda invalidates the biggest selling point of Data Explorer - that it was supposed to be a simpler alternative to TwoRavens. Plus the doc needs to be updated since the version of R it specifies as required is no longer available from EPEL. 

The good part is that all of the above has been figured out as part of me working with Don on #4753; so I have enough to make a PR. We could just use that issue to address it all. But Don's branch is outside the Dataverse own github source tree; so I felt it would be easier to address it in a separate issue.

**Comment by donsizemore** [comment]
@landreev I'm happy to dump my branch or give you write access to the OdumInstitute repo (whichever will make this easiest for you, as I'm most grateful to have a roadmap!)

**Comment by landreev** [comment]
@donsizemore @kcondon I figured the easiest, and cleanest, housekeeping-wise, is keep your branch attached to #4753, and merge it as is, ASAP. Then I'll sync up this branch with develop, clean up, and move it into CR and QA as well; also asap.

**Comment by pdurbin** [comment]
Pull request #4891 looks good to me so I moved this to QA. @landreev I did add some comments in my review to think about for the future.

**Comment by landreev** [comment]
@donsizemore 
Sounds like you had a chance to look at the new instructions in this branch; but if not, here's my own copy. 
The "basic" install, in the prerequisites section: 
http://140.247.116.170:8080/guides/installation/prerequisites.html
The TwoRavens install section: 
http://140.247.116.170:8080/guides/installation/r-rapache-tworavens.html

**Comment by landreev** [comment]
Thanks @pdurbin. Will take a look at the comments (And @donsizemore if you have any feedback for the docs, it's not too late)

**Comment by donsizemore** [comment]
I tried to comment this morning but GitHub kept eating them, so I abandoned. If you want I'll stand up one more CentOS 7 test box and walk through the R installation as stupid-ole-me, then point a test Dataverse instance at it?

At a glance, the instructions look great.

**Comment by landreev** [comment]
@donsizemore I'll leave it to Kevin, whether to take you up on the offer of trying to replicate the whole thing from scratch, since he's doing the QA for this. 
I thought/talked to some folks about the docs yesterday, and I was able to think of a couple of clarifying sentences to add there; I'll do that now.

**Comment by kcondon** [comment]
Basic R install works fine, including RData ingest, export, Data Explorer.
Advanced R install, aka Two Ravens is ongoing.

**Comment by landreev** [comment]
I have rebuilt the rpm fort R3.5 + RedHat/CentOS6. 
Appears to be working (as in, installs) on both vm4 and dvn-build.

**Comment by kcondon** [comment]
-update two ravens R install syntax, was missing end of line between 2 statements
-update two ravens R installation erase to include core packages
-update two ravens repo version of preprocess.R to include fixed end of line chars fixed in this branch to avoid version mismatch.

**Comment by landreev** [comment]
I've made the documentation updates as described above; 
except for the "start rserve" - the install script will start it, so they don't need to do it manually. 

Also, updated the preprocess.R in the tworavens distribution. 

But I'm out of ideas as to why tworavens isn't working on vm4. I'm not sure what to do with this issue; since it was supposed to be about the "simple r install" - and we are now back to messing with the advanced (tworavens) install... This is kind of out of scope - especially since the setup appears to be working on RH7 fairly well, and that's the OS we want to support. But then we probably want to be able to get it to run on our own test boxes here? Everything about tworavens is an infinite time sink - so not sure what to do, really.

**Comment by landreev** [comment]
@kcondon
For the release/upgrade notes:
If your Dataverse is configured to use R, you need to install one extra R library (haven); Dataverse is now using it to export tabular datafiles as RData. Install the package with the following R command (for example):
```
install.packages("haven", repos="https://cloud.r-project.org/", lib="/usr/lib64/R/library" )
```

**Comment by landreev** [comment]
@kcondon 
(maybe mention the new-and-improved RData export in the release features too?)

**Comment by landreev** [comment]
@kcondon 
OK, it appears that the vm4 troubles were due to the httpd setup on that instance. Changing the dataverse.conf and ssl.conf files to match the setup on dvn-build (minus the host-specific certs, plus the server name directive - to reflect the name dataverse-internal.iq, which is a DNS alias for dvn-vm4.hmdc) appears to have fixed it (mysteriously??)

Please review the doc changes/take a look at the installs on dvn-build and dataverse-internal.
