### ISSUE TITLE
Allow boolean operators when searching Dataverse guides

### ISSUE THREAD

**Issue by dlmurphy** [IQSS/dataverse#4884]
Looking through recent search logs for our guides, I noticed a lot of attempts at using quotations to search for exact phrases. Unfortunately, the search tool for our guides is very basic and does not allow this kind (or any other kind) of boolean operator.

One user searched for "terms of use" in quotations. This is what happens when you attempt this query in our current search:

![termsofuse](https://user-images.githubusercontent.com/22962740/43105328-79350ef0-8ea2-11e8-81be-b054930d4d2a.PNG)

As you can see, this currently returns a useless list of all pages that use the words "use", "user", "used", etc. However, there are plenty of relevant sections about Terms of Use on our guides that are being drowned out. When I search "terms of use" using quotes on my local copy of the guides using SublimeText, I get these useful results:

![termsofuse2](https://user-images.githubusercontent.com/22962740/43105408-c40d4e10-8ea2-11e8-8ead-b97bbd4f3b25.PNG)

**In order to help users find what they're looking for in the guides, I propose we rework the Guides Search feature to allow standard boolean search operators, including:** 

- quotes
- AND
- OR
- NOT
- parentheses

**Comment by oscardssmith** [comment]
it would be easier to just do the quotes and not parts, as the other 3 require equation parsing (and are needed less often)

**Comment by mheppler** [comment]
Here is the Sphinx project site to _search_ for more info on features and config options.

https://sphinx.readthedocs.io/en/latest/index.html

**Comment by dlmurphy** [comment]
Here's an issue on Sphinx's repo where someone is asking for exact phrase searching with quotation marks:
https://github.com/sphinx-doc/sphinx/issues/3301

It appears that Sphinx does not currently support this because of they way it handles indexing. I'll leave a comment in that issue, and I also plan on asking about this and boolean operators in [https://groups.google.com/forum/#!forum/sphinx-users](their google group.)

**Comment by dlmurphy** [comment]
Created a thread in their google group to ask about this: https://groups.google.com/forum/#!topic/sphinx-users/kLX5b9vMWck

**Comment by pdurbin** [comment]
@dlmurphy what if you download the PDF from http://guides.dataverse.org/en/latest/Dataverse.pdf and do the search from whatever PDF reader you like? Here's how a search for "terms of use" looks on Mac for me:

![screen shot 2018-10-19 at 7 26 47 am](https://user-images.githubusercontent.com/21006/47215742-87074a80-d370-11e8-85c1-cbab129d633f.png)

Related: #2148

**Comment by pdurbin** [comment]
@dlmurphy as I mentioned you might want to ask in #sphinx at https://writethedocs.slack.com

**Comment by dlmurphy** [comment]
Good point that the PDF is more searchable. We can't expect our users to find the PDF, download it, and search it whenever they need to find something in the guides. But it is good that there's a publicly accessible workaround like this.

Good idea about Write the Docs, I'm going to look into them and see if they can give us some advice.

**Comment by pdurbin** [comment]
I don't think we're going to get this out of Sphinx.

It might take moving to Docusaurus: 🦖 

- #8905

Vote to close.

**Comment by pdurbin** [comment]
@kuhlaid not a bad idea. Please feel free to create an issue for this. I'm glad you think PDF search is sufficient! Closing.
