### ISSUE TITLE
Problem with thumbnail of geo file

### ISSUE THREAD

**Issue by Thanh-Thanh** [IQSS/dataverse#4904]
Hi all,

I use dataverse 4.8.6 with a local geoconnect.
I managed to make it work in general. I have now all the related button (Preview, Explore).
But the thumbnail of the file is not viewed as it must be, cf. following photo. 
Someone has an idea how to make it works please ?

Thx in advanced,
Thanh Thanh

![worldmap_icon_problem](https://user-images.githubusercontent.com/39987392/43313120-731c95de-918f-11e8-9f87-a3291e034385.PNG)

**Comment by djbrooke** [comment]
Hi @Thanh-Thanh - it's great to hear that Dataverse is working for you! Just to confirm, are other thumbnails working? If it is just thumbnails for geospatial files, I think that you may be running into something related to issue #2972.

**Comment by Thanh-Thanh** [comment]
Hi @djbrooke , I have thumbnails for image file (don't know if there are other types of thumbnails?!).
I've read the #2972 issue, they are related I think. 
However, I digged into the log and having this :

[2018-07-30T18:06:33.604+0200] [glassfish 4.1] [WARNING] [] [edu.harvard.iq.dataverse.MapLayerMetadataServiceBean] [tid: _ThreadID=48 _ThreadName=jk-connector(1)] [timeMillis: 1532966793604] [levelValue: 900] [[
  Error when retrieving map icon image. Exception: Connection reset]]

The generation link existe, however I can not get the image due to the connection reset. This is another problem?

**Comment by djbrooke** [comment]
HI @Thanh-Thanh, I closed the related issue (#2972) and I'm planning on closing this one as well. If it's still an issue for you and you have the time to make a PR for this, we can work with you. Note that we've made some thumbnail changes since 4.8.6, so it may be worthwhile to upgrade or test on demo.dataverse.org to see if this is still an issue.
