### ISSUE TITLE
Expand/rewrite CC0 documentation in User Guide

### ISSUE THREAD

**Issue by dlmurphy** [IQSS/dataverse#4909]
@sbarbosadataverse and @jggautier pointed out in a recent email thread that they've seen cases of user confusion around the CC0 Public Domain Dedication we use as a default for datasets in Dataverse. To help address this confusion, I'd like to rewrite [the user guide section on CC0](http://guides.dataverse.org/en/4.9.1/user/dataset-management.html#cc0-waiver-dataset-terms-of-use), which is currently a little too basic and general.

Checklist for expanded CC0 documentation:

- [x] Add a brief introduction to what Creative Commons licenses are.

- [x] Add a complete description of what CC0 is and what the implications of its use are.

- [x] Explain in more detail the benefits of applying CC0 to a dataset, including implications for long term preservation.

- [x] Explain why CC0 is compatible with file restriction.

**Comment by pdurbin** [comment]
At standup I mentioned that I wrote a paragraph in e79cba0 this morning. @dlmurphy is going to read it over and I told him that he is welcome to keep hacking on what I wrote or create a new branch and pull request.

**Comment by dlmurphy** [comment]
While rewriting this section of the guides, I've found [Dryad's blog post on CC0](https://blog.datadryad.org/2011/10/05/why-does-dryad-use-cc0/) to be an excellent explanation of why CC0 is the best default license for a data repository, if anyone is interested in learning more about the subject.
