### ISSUE TITLE
test Shibboleth 3.0.2

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#4922]
Pull request forthcoming. [https://dataverse-test.irss.unc.edu](https://dataverse-test.irss.unc.edu) is now running shibboleth-3.0.2 and seems fine to my light testing.

If you all would like to log in with your Harvard keys or other federated InCommon accounts, we can accept my pull request to remove the 2.6.1 lock-in from Dataverse's Shibboleth documentation?

Why this moved up from back burner 47b: Shibboleth 3.0.2 fixes a denial of service vulnerability.

**Comment by donsizemore** [comment]
Er. I thought we had locked in Shibboleth at 2.6? Oh, well. The test box above is running 3.0.2 if you want to try it out.

**Comment by pdurbin** [comment]
I can log in with HarvardKey at https://dataverse-test.irss.unc.edu
