### ISSUE TITLE
An extra '/' at the beginning of the ID in one record blocks whole dataverse

### ISSUE THREAD

**Issue by pkiraly** [IQSS/dataverse#4923]
We have a strange Dataverse issue.
A Java exception is blocking the rendering of the Dataverse front
page. The error is recorded in the server.log as:

```
2018-08-06T16:32:06.773+0200] [glassfish 4.1] [WARNING] [] [javax.enterprise.web] [tid: _ThreadID=56 _ThreadName=jk-connector(5)] [timeMillis: 1533565926773] [levelValue: 900] [[
  StandardWrapperValve[HomepageServlet]: Servlet.service() for servlet HomepageServlet threw exception
java.lang.IllegalArgumentException: Failed to parse identifier: doi:/10.25625/VUHOIJ
  at edu.harvard.iq.dataverse.GlobalId.<init>(GlobalId.java:38)
  at edu.harvard.iq.dataverse.DatasetVersionServiceBean.populateDatasetSearchCard(DatasetVersionServiceBean.java:851)
  at sun.reflect.GeneratedMethodAccessor322.invoke(Unknown Source)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.glassfish.ejb.security.application.EJBSecurityManager.runMethod(EJBSecurityManager.java:1081)
  at org.glassfish.ejb.security.application.EJBSecurityManager.invoke(EJBSecurityManager.java:1153)
  at com.sun.ejb.containers.BaseContainer.invokeBeanMethod(BaseContainer.java:4786)
  at com.sun.ejb.EjbInvocation.invokeBeanMethod(EjbInvocation.java:656)
```

I found that the problem is caused by a Solr record:

```
{
        "id":"dataset_5707_draft",
        "entityId":5707,
        "dataverseVersionIndexedBy_s":"4.9.1",
        "identifier":"doi:/10.25625/VUHOIJ",
        "dsPersistentId":"doi:/10.25625/VUHOIJ",
        "persistentUrl":"https://doi.org//10.25625/VUHOIJ",
        "dvObjectType":"datasets",
        "publicationStatus":["Unpublished",
          "Draft"],
        "dateSort":"2018-08-06T10:54:29.896Z",
        "dateFriendly":"Aug 6, 2018",
        "isHarvested":false,
        "metadataSource":"eRA",
        "datasetVersionId":127,
        "citation":"Harald Kusch, 2018, \"Test Export\", https://doi.org//10.25625/VUHOIJ, eRA, DRAFT VERSION",
        "citationHtml":"Harald Kusch, 2018, \"Test Export\", <a href=\"https://doi.org//10.25625/VUHOIJ\" target=\"_blank\">https://doi.org//10.25625/VUHOIJ</a>, eRA, DRAFT VERSION",
        "nameSort":"Test Export",
        "title":"Test Export",
        "language":["English"],
        "language_ss":["English"],
        "subject":["Medicine, Health and Life Sciences"],
        "subject_ss":["Medicine, Health and Life Sciences"],
        "dsDescriptionValue":["Test Export"],
        "authorName":["Harald Kusch"],
        "authorName_ss":["Harald Kusch"],
        "datasetContactName":["Harald Kusch"],
        "subtreePaths":["/3"],
        "parentId":"3",
        "parentName":"electroniclabnotebook",
        "_version_":1608064864314458112}]
}
```

I identified several place in Postgres which might cause this result in Solr.

In `doidataciteregistercache` table:

* doi: `doi:/10.25625/VUHOIJ`
* url: `https://data.gro.uni-goettingen.de/citation?persistentId=doi:/10.25625/VUHOIJ`
* xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<resource xsi:schemaLocation="http://datacite.org/schema/kernel-3 http://schema.datacite.org/meta/kernel-3/metadata.xsd"
  xmlns="http://datacite.org/schema/kernel-3"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <identifier identifierType="DOI">/10.25625/VUHOIJ</identifier>
  <creators>
    <creator>
      <creatorName>Harald Kusch</creatorName>
    </creator>
  </creators>
  <titles>
    <title>Test Export</title>
  </titles>
  <publisher>eRA</publisher>
  <publicationYear>2018</publicationYear>
  <resourceType resourceTypeGeneral="Dataset"/>
  <descriptions>
    <description descriptionType="Abstract">Test Export</description>
  </descriptions>
  <contributors>
    <contributor contributorType="ContactPerson">
      <contributorName>Harald Kusch</contributorName>
    </contributor>
  </contributors>
</resource>
```

In the dvobject table:

* storageidentifier: `file:///10.25625/VUHOIJ`
* identifier: `10.25625/VUHOIJ`

As you can see there are several extra '/' as part of the DOI identifier. At this point it is not clear what made that extra character, it is Dataverse or the client which use the Dataverse API?

The important thing I would like to solve is the original problem, i.e. the blocking DOI parsing issue.
So I cleared the database, and removed these extra '/'-s from everywhere, removed the Solr index, and reindexed the whole database again. The problem still existed: the DOI in Solr is what I showed you.

I continue investigation, and check how the dsPersistentId is created in Solr. In `DvObject` class (in edu.harvard.iq.dataverse package) I found this method:

```
    public GlobalId getGlobalId() {
        // FIXME should return NULL when the fields are null. Currenntly, 
        //       a lot of code depends call this method, so this fix can't be 
        //       a part of the current PR.
        return new GlobalId(getProtocol(), getAuthority(), getIdentifier());
    }
```

I also found that in the same class there is a named query:

```
    @NamedQuery(name = "DvObject.findByGlobalId",
            query = "SELECT o FROM DvObject o WHERE o.identifier=:identifier and o.authority=:authority and o.protocol=:protocol and o.dtype=:dtype"),
```
so `authority` also comes from the `dvobject` table. I checked it, and found that for this record its content is an empty string.

I modified the database manually, so

| identifier | authority |
| --- | --- |
| 10.25625/VUHOIJ | |

became

| identifier | authority |
| --- | --- |
| VUHOIJ | 10.25625 |

After clearing the index, and reindexing it again the original issue were solved, and now our front page is working again. There are some points however where Dataverse code base could be improved:

1) catch the DOI parsing exception, and instead of blocking the whole page the error should be reported to the admin with some more information, and the search result list should skip the particular record but should contain the rest.

2) Since the DOI is coming from Dataverse, it should check it after creation whether they are parsable. 

3) When Dataverse stores the new identifiers is should add a proper check against the content of dvobject's table columns (identifier, authority) whether they are syntactically correct or not.

4) The database stores the DOI in doidataciteregistercache.doi table, so it doesn't seem logical to not use that in indexing, and recreating it again from parts.

5) Tt would be also nice if these tables would have documentation

In the next days we will try to reproduce the issue, and figure it out if it was dependent or independent from the client application (this records and two others were imported from RSpace lab notebook). I will add a comment about the result as we have something to report.

Best,
Péter

**Comment by pdurbin** [comment]
@pkiraly great investigation and fix! Yes, "authority" should not be null and it's very strange that the "authority" value was in the "identifier" column. You've moved it to the right place.

> this records and two others were imported from RSpace lab notebook

Interesting. Does the bug only happen when you create a dataset using RSpace? Or does it happen when you create a dataset with the Dataverse GUI as well?

**Comment by pkiraly** [comment]
@pdurbin I tried it now, and yes, when I create a new dataset within the Dataverse UI I end up with a URL having this trailing slash:
https://data.gro.uni-goettingen.de/dataset.xhtml?persistentId=doi%3A%2F10.25625%2FY3WP5V&version=DRAFT (encoded here as %2F)
After submitting the form I am redirected to the above URL, but it gives a 404 HTTP error. The server log contains:

[2018-08-07T14:52:56.458+0200] [glassfish 4.1] [FINE] [] [edu.harvard.iq.dataverse.DatasetPage] [tid: _ThreadID=52 _ThreadName=jk-connector(1)] [timeMillis: 1533646376458] [levelValue: 500] [CLASSNAME: edu.harvard.iq.dataverse.DatasetPage] [METHODNAME: init] [[
  initializing DatasetPage with persistent ID doi:/10.25625/Y3WP5V]]

[2018-08-07T14:52:56.458+0200] [glassfish 4.1] [INFO] [] [edu.harvard.iq.dataverse.DvObjectServiceBean] [tid: _ThreadID=52 _ThreadName=jk-connector(1)] [timeMillis: 1533646376458] [levelValue: 800] [[
  Invalid identifier: doi:/10.25625/Y3WP5V]]

[2018-08-07T14:52:56.458+0200] [glassfish 4.1] [WARNING] [] [edu.harvard.iq.dataverse.DatasetPage] [tid: _ThreadID=52 _ThreadName=jk-connector(1)] [timeMillis: 1533646376458] [levelValue: 900] [[
  No such dataset: doi:/10.25625/Y3WP5V]]

and when I try to reach the landing page, I got the same parsing exception:

```
[2018-08-07T14:55:14.145+0200] [glassfish 4.1] [WARNING] [] [javax.enterprise.web] [tid: _ThreadID=52 _ThreadName=jk-connector(1)] [timeMillis: 1533646514145] [levelValue: 900] [[
  StandardWrapperValve[HomepageServlet]: Servlet.service() for servlet HomepageServlet threw exception
java.lang.IllegalArgumentException: Failed to parse identifier: doi:/10.25625/Y3WP5V
	at edu.harvard.iq.dataverse.GlobalId.<init>(GlobalId.java:38)
	at edu.harvard.iq.dataverse.DatasetVersionServiceBean.populateDatasetSearchCard(DatasetVersionServiceBean.java:851)
	at sun.reflect.GeneratedMethodAccessor322.invoke(Unknown Source)
```

**Comment by pdurbin** [comment]
@pkiraly when you run

curl http://localhost:8080/api/admin/settings/:Authority

Does the value start with a slash ("/")? It shouldn't.  Here's how it looks on a server I use for testing:

    {"status":"OK","data":{"message":"10.5072"}}

You can get a dump of all database settings with this:

    curl http://localhost:8080/api/admin/settings | jq .

I believe you can get a dump of all Dataverse-related JVM options with this:

    /usr/local/glassfish4/glassfish/bin/asadmin list-jvm-options | egrep 'dataverse|doi'

That's what we document at http://guides.dataverse.org/en/4.9.1/installation/config.html#jvm-options at least. 😄

**Comment by pkiraly** [comment]
@pdurbin It is strange that now I don't have the Authority settings however I have a note that once I set it. Maybe I did something wrongly, or would it be anyhow possible, that one of the update removed it?

curl http://localhost:8080/api/admin/settings/:Authority
```
{"status":"ERROR","message":"Setting :Authority not found"}
```

curl http://localhost:8080/api/admin/settings | jq .
```
{
  "status": "OK",
  "data": {
    ":Shoulder": "10.25625/",
    ":DoiSeparator": "/",
    ":TwoRavensUrl": "...",
    ":SystemEmail": "...",
    ":OAIServerEnabled": "true",
    ":ProvCollectionEnabled": "true",
    ":AllowSignUp": "yes",
    ":SearchApiRequiresToken": "true",
    ":DoiProvider": "DataCite",
    ":FooterCustomizationFile": "...",
    ":BlockedApiPolicy": "localhost-only",
    ":StyleCustomizationFile": "...",
    ":Protocol": "doi",
    ":BlockedApiEndpoints": "...",
    ":SignUpUrl": "/dataverseuser.xhtml?editMode=CREATE",
    ":HeaderCustomizationFile": "...",
    ":TwoRavensTabularView": "true"
  }
}
```

asadmin list-jvm-options | egrep 'dataverse|doi'
```
-Ddataverse.rserve.host=....
-Ddataverse.rserve.port=....
-Ddataverse.rserve.user=....
-Ddataverse.rserve.password=....
-Ddataverse.fqdn=....
-Ddataverse.auth.password-reset-timeout-in-minutes=60
-Ddataverse.timerServer=true
-Ddataverse.files.directory=....
-Ddoi.username=....
-Ddoi.password=....
-Ddoi.baseurlstring=https://mds.datacite.org
-Ddataverse.siteUrl=https://data.gro.uni-goettingen.de
```

As a next step I'll reset the authority and try creating dataset again.

**Comment by pkiraly** [comment]
@pdurbin 
I reset the :Authority value, and the record creation process went smoothly, however I found strange values in the DOI and in the database as well.

The URL is https://doi.org/10.25625/10.25625/RWTRVQ (the DOI prefix is duplicated)

The database values (removed some columns):

```
SELECT * FROM dvobject WHERE dtype = 'Dataset' ...;
...
-[ RECORD 55 ]-------------+--------------------------------
dtype                      | Dataset
...
storageidentifier          | file://10.25625/10.25625/RWTRVQ  <-- should it be file://10.25625/RWTRVQ?
authority                  | 10.25625
identifierregistered       | f
identifier                 | 10.25625/RWTRVQ  <-- should it be RWTRVQ?
protocol                   | doi
```

same in the other table:
```
select * from doidataciteregistercache WHERE id = 74;
-[ RECORD 1 ]----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
...
doi    | doi:10.25625/10.25625/RWTRVQ
status | reserved
url    | https://data.gro.uni-goettingen.de/citation?persistentId=doi:10.25625/10.25625/RWTRVQ
xml    | <?xml version="1.0" encoding="UTF-8"?>
       |     ...
       |     <identifier identifierType="DOI">10.25625/10.25625/RWTRVQ</identifier>
       |     ...
```

**Comment by pdurbin** [comment]
@pkiraly thanks, seeing these settings helps a lot. I'm assuming you ran `upgrade_v4.8.6_to_v4.9.0.sql` as documented in the release notes at https://github.com/IQSS/dataverse/releases/tag/v4.9 which say, "While your existing persistent identifiers stay the same (as the name suggests!), the update script will modify the database entries (it has to do with how the "authority" and "shoulder" suffix are stored)." I wonder if there's a bug in that script or something. Not sure.

Anyway, you should use "10.25625" as the value for ":Authority". (It looks like you just did made this change.)

It seems like you aren't using a shoulder so you should delete ":Shoulder". (On my test server I use "FK2/" to indicate that that the datasets are for testing. The easiest way is like this:

    curl -X DELETE http://localhost:8080/api/admin/settings/:Shoulder

**Comment by pkiraly** [comment]
@pdurbin Many thanks! It helps, and solved all the issues. 

Indeed, I run the conversion script you mentioned.

I am pretty sure that I did not set Shoulder (I have notes about the steps of setting the site, and Shoulder is not mentioned), so it might be an issue in the conversion script.

Best,
Péter

**Comment by pdurbin** [comment]
@pkiraly great news. Thanks for the update. How do you feel about closing this issue and opening as many "small chunk" issues as you want for any work that you feel should be done?

**Comment by pkiraly** [comment]
@pdurbin I am fine with it. However I could create the small issues suggested earlier in the thread not earlier than Friday.

**Comment by pdurbin** [comment]
@pkiraly great, no rush. I just assigned this issue to you to work on closing it and opening smaller issues as needed. Thanks!

**Comment by pdurbin** [comment]
Related: #5057

**Comment by pdurbin** [comment]
@pkiraly Happy New Year! What's the status of this issue, please? Thanks! :smile:

**Comment by pdurbin** [comment]
@pkiraly hi! Are you still interested in this?
