### ISSUE TITLE
Allow ability to choose whether file PIDs are created/minted

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#4929]
As feedback from the community, we've heard that some group do not want to create / mint file PIDs. So this issue is to add a setting to allow this code to be optional. 

Tasks:
- [ ] add setting to settings table
- [ ] use setting in publish commands to decide whether to create / mint file PIDs
- [ ] add display logic to show different file page citation/s depending on whether there is a file PID*

(*) this 3rd task should already be handled by the fact that file PIDs don't exist for draft files, but we should review this with the UI/UX team

**Comment by lmaylein** [comment]
What is the corresponding configuration option in 4.9.3. Could not find anything in the documentation except :DataFilePIDFormat

**Comment by pdurbin** [comment]
@lmaylein good job finding it. :smile: 

The "latest" symlink hasn't been updated yet but the 4.9.3 docs have been built: http://guides.dataverse.org/en/4.9.3/installation/config.html#filepidsenabled
