### ISSUE TITLE
Spike: Dataverse Linking - as a dataverse owner, I want to link a related dataverse to my dataverse to help relevant researchers find it.

### ISSUE THREAD

**Issue by dlmurphy** [IQSS/dataverse#4936]
This is the sister issue of #4410. While that one is about _dataset_ linking, this one is about _dataverse_ linking.

Currently, only Super Users have the ability to link other users' dataverses to their dataverses. This functionality used to be available to all users before Dataverse 4.0. Let's restore this functionality so all users are able to link others' dataverses to their dataverses.

**Design requirements:**

- The main impact of this issue is to open up dataverse linking to all logged in users, not just super users.

- Users who create or are otherwise in control of a dataverse will be able to link to any dataverse.

- Specifically, to create a link, a user's account must have an assigned role that includes the "Add Dataverse" permission on the dataverse that is DOING the linking.

- A user creating a new link will not need any permissions on the dataverse BEING linked.

- Any user can link to any published dataverse.

- For now, there will not be a way to remove links in the UI, but there is a currently existing way to do it via API.

- The success message when you have successfully created a new link should happen in the same place as now, but it should read:

- Success! - [linked dataverse] has been successfully linked to [linking dataverse]. If you need to remove this link in the future, please contact Support at [support email].

- This feature will use the existing linking UI, with one exception: On the "Link Dataverse" modal, we will replace the "Your Dataverses" drop-down list with a type-ahead box.

For future reference, this is our document where the design team deliberated on this feature. Keep in mind that it is not 100% up to date, especially regarding permissions: https://docs.google.com/document/d/14J8uBV4kNPHDfbiumNNKb01tdEksPpnfbRklrY1KhAc/edit

**Comment by cmbz** [comment]
**2023/09/18**
- Requires additional discussion to determine how best to support which subset of functionality associated with linking. Greater functionality will require rearchitecture
- Currently, there do not appear to be many tickets from users requesting this form of linking, and super users can perform the operation upon request from users
- Conversation will be deferred until after 6.1

**Comment by cmbz** [comment]
**2024/01/22**
- Currently functionality is limited to superuser because it can trigger significant indexing. 
- If this functionality is required in the future, please open another issue (that will require substantive investigation and development effort).
  - Note: a future functionality might involve allowing only trusted users to perform this action.
Closing now.
