### ISSUE TITLE
PermissionServiceBean Cleanup 

### ISSUE THREAD

**Issue by michbarsinai** [IQSS/dataverse#4944]
`PermissionServiceBean` has many deprecated methods, especially those that calculate permissions without taking IP groups into account (a.k.a "static permissions").
This issue will:

- [x] Remove the static permission code
- [x] Update code that uses static permissions to use the dynamic permission code
- [x] Update the developer guide, so it's easier for developers to understand how to query permissions in Dataverse
- [x] Perform general cleanup on the bean itself, and the related RoleAssignee area

⚠️ This issue was spun off from #2122.

**Comment by djbrooke** [comment]
@michbarsinai - I moved this back to Community Dev for now. When you have time, please respond to @oscardssmith's feedback and move it back to code review.

**Comment by michbarsinai** [comment]
@djbrooke done

**Comment by pameyer** [comment]
Took a quick look at 406fb41a81c2ac42fb2cb4613235a9b367a3647b after hearing @kcondon and @landreev discussing deployment issues (of course, they were talking about 2122-querying-root-dataverse-contents).  No issues building or deploying to docker-aio; but integration tests failed (`[ERROR] Tests run: 67, Failures: 24, Errors: 17, Skipped: 0`).

**Comment by djbrooke** [comment]
Hi @michbarsinai - I moved this back to Community Dev for now, as there are still a few items to work on. If you have the time to work on this, great! If not, let me know and we can get together some resources on this side.

**Comment by pdurbin** [comment]
@michbarsinai are you still interested in this?

**Comment by michbarsinai** [comment]
Not in any effective way, I'm afraid. Plus my knowledge is probably outdated on this by now. Happy to consult anyone implementing this, though.

**Comment by pdurbin** [comment]
@michbarsinai no worries, we'll cook up a fresh issue whenever you want one. Closing! And yes let's consult about something! We miss you! ❤️

**Comment by michbarsinai** [comment]
I Miss you too, good people!❤️
