### ISSUE TITLE
File permissions,  permissions-manage-files.xhtml missing error from link in requestor email

### ISSUE THREAD

**Issue by jmjamison** [IQSS/dataverse#4947]
I have a test site at: <http://ec2-54-219-54-246.us-west-1.compute.amazonaws.com:8080/>, running version 4.9.2. I'm working on restricted file settings.   

As a non-administrative  user I request access, email generated to the administrator account includes the link to the Restricted File Permissions page. Following the email link I get a 404 file (permissions-manage-files.xhtml not found) but in the admin account I can navigate to the permissions page from my notifications.

I've tried to replicate this on the demo site, which is 4.9.1.  I don't get the same result. User account requests access but the administrator account hasn't received anything yet.

**Comment by pameyer** [comment]
@jmjamison This sounds like the email is not including the port number of glassfish (`:8080`) in the link; similar to https://github.com/IQSS/dataverse/issues/4517.  If you add the port number to the link manual, does it work for you?

It also looks like there may be an issue with your apache configs.  http on port 80 is correctly redirecting to https on port 443, but the requests don't seem to be continuing to glassfish.

**Comment by jmjamison** [comment]
What seems to have fixed the problem for now is that I need to add the JVM dataverse.siteUrl option.   I'll add that to my install notes.
<jvm-options>-Ddataverse.fqdn=dataverse.example.edu</jvm-options>
<jvm-options>-Ddataverse.siteUrl=http://${dataverse.fqdn}:8080</jvm-options>

I will go through the apache configs.  My inexperience with networking is usually what trips me up.
