### ISSUE TITLE
File Downloads don't track checkbox state

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#4952]
In at least 4.9.1 and 4.9.2, when downloading files from a dataset that has a terms popup, with a guestbook, after an initial selection of one or all files, for a which the download works correctly, any further adjustment of the checkboxes may provide the wrong download, including a single file when multiple files are selected and a zip should be returned. (See http://phoenix.dataverse.org/dataset.xhtml?persistentId=doi:10.5072/FK2/EZHTAB for example). 

(For downloads without terms - the top/group download button always returns a zip,  even with only one file selected (results in download of a zip containing the file rather than the file itself) which may or may not be the desired result.)

I've been able to track this to logic in the FileDownloadServiceBean where it appears guestbookResponse.getDatafile() is set, but not being kept up to date while guestbookResponse.getSelectedFileIds() is up to date but, since the logic in writeGuestbookAndStartDownload tries to send a single file if getDatafile() is not null first (which is true) the subsequent attempt to redirect and download based on the fileIDString fails (response already committed). 

Since the fileIdString appears to be correct if set, even for a single file, I've written a work-around that checks it and uses it if available in preference to any value for the datafile. I also made the top/group download button switch to sending the file itself, rather than a zip of that single file, as well but that could be reversed if the intent is to always send a zip for the top/group download button.

I have not yet been able to follow the logic regarding how the datafile is set/updated/set to null and discover why it isn't correct when FileDownloadServiceBean.writeGuestbookAndStartDownload is called, but it seems like fixing at that level, rather than my work-around, would be better. I'll submit a PR, but hopefully someone else can find the root cause.

**Comment by kcondon** [comment]
@qqmyers I've tested this and it still seems to be broken:
with db and toa defined, logged in, I download first 3 files, works, download next 3 files, it downloads a single file , file # 3 from the first download, unzipped. This was the same behavior as /develop.

I'll test again to be sure but that is what I'm currently seeing.

**Comment by qqmyers** [comment]
@kcondon - Sorry - I missed cherry-picking one modification. Hopefully should work for all cases now.

**Comment by kcondon** [comment]
@qqmyers Thanks, that did the trick!
