### ISSUE TITLE
Don't write api keys in responses.

### ISSUE THREAD

**Issue by birdbrained** [IQSS/dataverse#4954]
Dataverse returns api keys in the body of the response. Many things log these errors. If the client makes the mistake of using the wrong api key, they may not realize it (an actual real api key) has now been logged. Please remove the api key from the response.

In most cases simply knowing the key was wrong is enough information about the error to know what went wrong.

https://github.com/IQSS/dataverse/blob/06b5e923c65bffcf557a208ae9701ea8161d0395/src/main/java/edu/harvard/iq/dataverse/api/AbstractApiBean.java#L709

https://github.com/IQSS/dataverse/blob/06b5e923c65bffcf557a208ae9701ea8161d0395/src/main/java/edu/harvard/iq/dataverse/api/Index.java#L563

https://github.com/IQSS/dataverse/blob/06b5e923c65bffcf557a208ae9701ea8161d0395/src/main/java/edu/harvard/iq/dataverse/api/Index.java#L600

**Comment by pdurbin** [comment]
@birdbrained thanks for this bug report. I agree with you but I think the title might be a bit off. From your perspective you may be logging the response but your objection is that the response contains the API key, right? Do you mind if I tweak the title a bit?

**Comment by birdbrained** [comment]
Nope that's probably better.
