### ISSUE TITLE
code coverage instrumentation for integration tests

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#4960]
unit tests are currently instrumented to measure code coverage, integration tests are not.

**Comment by oscardssmith** [comment]
Any chance we can get coveralls to use this?

**Comment by pameyer** [comment]
Not sure.  I *think* that coveralls uses the result from travis, and I don't think that we've got travis setup to run integration tests.

**Comment by pameyer** [comment]
@oscardssmith coveralls the GitHub integration (not without a way to run integration tests from something that integrates with GitHub), or coveralls the `org.eluder.coveralls` maven plugin (possibly)?

**Comment by pdurbin** [comment]
@pameyer I see you made pull request #5016 (thanks!) but this issue is still in the "inbox" according to https://waffle.io/IQSS/dataverse and I'm wondering if you're ready for code review.

**Comment by pameyer** [comment]
@pdurbin It's ready for review, but also didn't seem worth interrupting the flow of what's already going on - and doesn't seem like it's likely to generate merge conflicts.

**Comment by pdurbin** [comment]
@pameyer ok, thanks, I went ahead and dragged it over to code review. I'm curious if the percentage is higher or lower than than the 16% we show currently for unit tests on our README:

<img width="234" alt="screen shot 2018-09-06 at 6 33 02 pm" src="https://user-images.githubusercontent.com/21006/45188670-5aa1cf80-b203-11e8-9f82-80ef2423244f.png">

**Comment by pdurbin** [comment]
I'm moving this to QA because the directions are clear enough but I didn't try them myself. Note that there's a tip that this technique could be used in production to figure out how much code is actually exercised after a week or a month or whatever of usage. Pretty neat!
