### ISSUE TITLE
A code detail.

### ISSUE THREAD

**Issue by roydd3518** [IQSS/dataverse#4961]
**code-path :** ../main/java/edu/harvard/iq/dataverse/search/SearchIncludeFragment.java
**version :** 4.8.6
**line-num :** 211
`String qParam = "";`
`if (query != null) {`
`  qParam = "&q=" + query;`
`}`
`return widgetWrapper.wrapURL(dataverseRedirectPage + "?faces-redirect=true&q=" + qParam + optionalDataverseScope);`

You can remove the strings "&q=".

**Comment by pdurbin** [comment]
@roydd3518 huh. Yeah, it looks like I introduced this oddness in fa73991 as a fix for #1338 but from a little testing right now I can't make a double `&q=` appear in a URL. That is to say, I don't think any harm is being caused but I agree that it would be good to clean this up. Are you interested in making a pull request?

**Comment by roydd3518** [comment]
No, thanks.I just saw this and I hope dataverse is better.
