### ISSUE TITLE
Document JavaMail config for AWS SES email 

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#4969]
See RT 26574:

This is the configuration that worked for me finally.

/opt/glassfish4/glassfish/bin/asadmin create-javamail-resource --mailhost email-smtp.us-east-1.amazonaws.com --mailuser awstest --fromaddress <***> --transprotocol aws --transprotocolclass com.amazonaws.services.simpleemail.AWSJavaMailTransport --property mail.smtp.auth=true:mail.smtp.user=< aws_access_key >:mail.smtp.password=< aws_secret_key >:mail.transport.protocol=smtp:mail.smtp.port=587:mail.smtp.starttls.enable=true mail/notifyMailSession

The configured dataverse support email should be verified in aws ses.

**Comment by qqmyers** [comment]
FWIW: QDR's setup somewhat differently on AWS (showing the excerpt from domain.xml rather than the asadmin call to create it, <* *> surround values I've removed):

```
 <mail-resource host="email-smtp.us-east-1.amazonaws.com" from="<*x@y*>" user="<*name*>" jndi-name="mail/notifyMailSession">
      <property name="mail.smtps.user" value="<*name*>"></property>
      <property name="mail.smtp.socketFactory.fallback" value="false"></property>
      <property name="mail.smtp.socketFactory.class" value="javax.net.ssl.SSLSocketFactory"></property>
      <property name="mail.transport.protocol" value="smtps"></property>
      <property name="mail.smtps.ssl.enable" value="true"></property>
      <property name="mail.smtp.starttls.enable" value="true"></property>
      <property name="mail.smtps.password" value="<*password*>"></property>
      <property name="mail.smtp.port" value="465"></property>
      <property name="mail.smtp.socketFactory.port" value="465"></property>
      <property name="mail.smtps.auth" value="true"></property>
    </mail-resource>
```

**Comment by pdurbin** [comment]
Pull request #5039 looks fine to me. Off to QA.
