### ISSUE TITLE
Handlenet timeout, when looking up or registering handles. Library upgrade needed?

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#4972]
Noticed that publishing a dataset with a handle takes some minutes in production. (Note that this is after the patch for skipping file registration has been applied; so there is just one dataset-level handle, that needs to be looked up and possibly re-registered during the publication process). 
It appears that there are timeouts when Dataverse tries to communicate to the central handlenet service: 
```
[edu.harvard.iq.dataverse.HandlenetServiceBean] 
  Caught exception trying to process lookup request
HandleException (CANNOT_CONNECT_TO_SERVER) 132.151.1.179: java.io.InterruptedIOException: Connection timed out.
        at net.handle.hdllib.HandleResolver.sendHttpRequest(HandleResolver.java:1959)
        ...
        at edu.harvard.iq.dataverse.HandlenetServiceBean.isHandleRegistered(HandlenetServiceBean.java:197)
        ... etc.
```
(the dataset eventually gets published). 

My best guess is that this is because Dataverse is built with an ancient version of the handlenet library (the ip addresses of the central servers are somewhere in that jar). 
```
        <dependency>
            <groupId>net.handle</groupId>
            <artifactId>handle</artifactId>
            <version>2006-06-16-generated</version>
        </dependency>
```
(that's 2006 in the date, yes)

So we may need to upgrade it. 

(error handling inside the handlenet service bean may be problematic too; for example, it looks like it can't differentiate between the lookup connection timing out, and the handle not being registered...)

**Comment by Mahsanas** [comment]
Our Dataverse was working fine with Handles but since about a week ago we are seeing a similar pattern.  It takes a very long time for datasets to get published /deleted and we see handle exceptions. We have not upgraded or updated data verse or handle server. So this might be due to some other factor than older Handle.net libraries. I will post here if I get to the root of it.

**Comment by pdurbin** [comment]
@Mahsanas thanks, have you seen https://groups.google.com/d/msg/dataverse-community/zq3mCxDlsec/z7TREkBjAgAJ by @oodu ?

**Comment by PaulBoon** [comment]
At DANS we upgrade to 8.1.1 for the client lib and the server and this is working fine for more than a year now. 
I think that you can use the 8.1.1 lib with older (we had 7.3) versions of the service, but we might want to check this at Handel.net. 
I could do a PR with the 8.1.1 lib, that would also make our fork closer to IQSS, which is what I prefer.

**Comment by pdurbin** [comment]
@PaulBoon yes, a pull request would be appreciated! We are always interested in doing what we can to reduce the need for forking. Let's not worry too much about additional issues at this point. Thanks!

**Comment by PaulBoon** [comment]
The PR is here https://github.com/IQSS/dataverse/pull/5595. 
Response from Handle.net about compatibility of the server and client: The client and server will ensure that they speak a compatible version of the Handle wire protocol.

Upgrade to newer version (9.x) will need to be investigated later on (new PR will then follow).
