### ISSUE TITLE
Curators unable to edit metadata for datasets in review

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#4982]
Seen on bec8015f2fc9ca3331d585a9dc8ebf15c3508bf1 (develop) and 2f91725 (DCM S3); dataverseAdmin user reviewing a dataset does not have a UI option for editing metadata (did not test API for editing metadata).

From https://github.com/IQSS/dataverse/issues/4139, it sounds like this is a bug.

**Comment by pdurbin** [comment]
@pameyer thanks for the bug report! Do we know if 4.9.2 is affected? https://demo.dataverse.org is running it if you want to check. Do we know if 4.9.1 is unaffected?

**Comment by pameyer** [comment]
`api/datasets/:persistentId/editMetadata/?persistentId` appears to be working as expected on bec8015f2fc9ca3331d585a9dc8ebf15c3508bf1 for datasets that are in review; suggesting this is more related to UI than dataset locks.

@pdurbin I haven't tested either 4.9.2, 4.9.1 or demo.dataverse.org; so I don't know.

**Comment by pameyer** [comment]
From discussion with @kcondon , this was resolved by 
https://github.com/IQSS/dataverse/pull/4975.
