### ISSUE TITLE
HTML showing up in facets of many facetable metadata fields

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#4985]
@sbarbosadataverse noticed this is occurring on Harvard Dataverse. It's also occurring on Demo Dataverse. Both Dataverses are running 4.9.2. (I can't tell if it's occurring on other installations or other Dataverse versions.)

The dataset create and edit pages allow users to enter HTML into several metadata fields (I've tested just the Citation metadata fields) and save and publish those datasets. The metadata values are displayed in the metadata facets with their HTML. For an example, see this test dataverse: https://demo.dataverse.org/dataverse/html_facets

<kbd><img width="400" src="https://user-images.githubusercontent.com/18374574/45178711-7053cc80-b1e4-11e8-8e63-b3615c6efef0.png"></kdb>

This looks related to the github issue https://github.com/IQSS/dataverse/issues/2000. It was closed, and I'm not sure what the outcome was. In the issue @pdurbin wrote that:

> the rule established in #1332 is that if the tsv says the "fieldType" is "textbox" that we strip HTML before indexing. Does that mean you'll be changing the "fieldType" for authorAffiliation from "text" to "textbox"?

The fieldType for all fields in Dataverse 4.9.2's [citation metadata block tsv](https://github.com/IQSS/dataverse/blob/master/scripts/api/data/metadatablocks/citation.tsv) for which facetable is set to TRUE (so they can appear in the facets) are either "text", including author affiliation, or "date". None are "textbox." (All fields in that tsv that do have "textbox" have facetable set to FALSE (they can't be displayed in the facets).)

But we can't change the fieldType of all facetable fields that are currently "text" to "textbox" because all of those fields should all be one line fields - they shouldn't be textboxes.

In #2000 @pdurbin [asked](https://github.com/IQSS/dataverse/issues/2000#issuecomment-94563582) if we could "add a boolean to every field called "stripHtml" that could be set to true or false?"

Is that possible? Are there other ways to prevent html from even being saved in one-line metadata fields? If not, are there other ways to preventing that html from being displayed in the facets?

**Comment by scolapasta** [comment]
This is a curation issue. Technically these values are not html since we don't render them and we don't really want to be in the business of changing what a user inputs. (even for html fields, we never strip the disallowed html, we scrub it on display). 

What really needs to happen is the fields need to be edited to remove the extraneous text. (this text may exist because we may have allowed html in these fields prior to v4, I can't remember)

**Comment by jggautier** [comment]
Ah, thanks. So we don't want to prevent html from even being saved in metadata fields because we shouldn't change what a user inputs.

But when you write that it's a curation issue, does that mean that Dataverse shouldn't prevent the html from being displayed in the facets (Dataverse shouldn't scrub the fields so that html isn't displayed in the facets)?

**Comment by pdurbin** [comment]
There's a boolean called "facetable" that could perhaps be used some day to decide whether or not strip out HTML from a field as it's indexed into Solr: http://guides.dataverse.org/en/4.10.1/admin/metadatacustomization.html#datasetfield-field-properties

We already strip HTML for "textbox" fields: https://github.com/IQSS/dataverse/blob/v4.10.1/src/main/java/edu/harvard/iq/dataverse/search/IndexServiceBean.java#L824
