### ISSUE TITLE
As someone reviewing code I don't want to be distracted by alternative styles for placing curly braces

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#4992]
All of the developers at IQSS use Netbeans to edit Dataverse code and at http://guides.dataverse.org/en/4.9.2/developers/coding-style.html#format-code-you-changed-with-netbeans we kindly ask contributors to format the code they changed (not all the code in the file they touched) with Netbeans. That way, people doing code review are not distracted by differences of style and can focus on how the behavior of the code is changing.

In the spirit of small chunks, I'd like to update the dev guide to specifically address placement of curly braces. I don't know how to express this in Checkstyle (or even what it's called), but here are the settings Netbeans uses for braces:

![screen shot 2018-08-22 at 11 58 13 am](https://user-images.githubusercontent.com/21006/44475602-73a36180-a603-11e8-9d14-ac5c05564291.png)

**Comment by pameyer** [comment]
@pdurbin Probably, but I'll find out for sure.

**Comment by pdurbin** [comment]
@pameyer thanks for pull request #4995! I added a bit more and moved it to QA.
