### ISSUE TITLE
As a Dataverse user, I'd like to be able to select and copy just the DOI from the citation block

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#4994]
Attempting to copy just the DOI (presumably other PIDs as well) from the citation block results in the entire citation block being highlighted and selected for copy to clipboard.  This appears to be due to a `onclick` handler for the `citation-select` div (which suggests it's intentional).

**Comment by pdurbin** [comment]
@pameyer I brought up this issue to @mheppler yesterday and he demonstrated how he was easily able to right-click the DOI link and copy it with "copy link location". Is this still an issue? At some point we switched the citation from showing a DOI to showing a DOI in its link form but I don't remember when and can't find the pull request.

**Comment by pameyer** [comment]
@pdurbin "copy link location" will get the http url for the DOI, which isn't accepted by the various dataverse APIs.

**Comment by pdurbin** [comment]
@pameyer is copying from "Dataset Persistent ID" under the "Metadata" tab an acceptable workaround? It's not the citation but it *is* the citation metadata block. 😄  Here's a screenshot. It's just the DOI, not the DOI as a URL.

![screen shot 2019-03-06 at 12 44 53 pm](https://user-images.githubusercontent.com/21006/53901797-c5df2980-400d-11e9-94e8-ede075015bce.png)

**Comment by pameyer** [comment]
@pdurbin It's the workaround I've been using.

But the usability of "to copy this text in front of you; click another tab and scroll down" (and be experience enough with the app to know you can do this), combined with breaking the normal behavior of a browser; seems to me like it's worth fixing.

The more significant (and unknown) piece of information is how many users ran into this, didn't report it and/or couldn't figure it out.

**Comment by mheppler** [comment]
This "click citation content to select" functionality was something that was specifically requested during our last 4.0 redesign efforts. I suppose we could test a "click to select..." btn, to allow this specific request to highlight and copy specific parts of the citation.
