### ISSUE TITLE
Solr: Index all performance is too slow with full production data.

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#50]
---

Author Name: **Kevin Condon** (@kcondon)
Original Redmine Issue: 3457, https://redmine.hmdc.harvard.edu/issues/3457
Original Date: 2014-01-29
Original Assignee: Philip Durbin

---

Preliminary testing shows index all is taking too long with full production data.

Indexing 1861 dataverses: 41 minutes 

Indexing 1900 datasets: 2 hours, 15 minutes. There are 52,000+ datasets.

The above numbers were achieved on dvn-3 with full production data of public dv's and studies. Various glassfish heaps of 512MB and 10GB showed the same performance.

---
We see"java -server -jar start.jar" at https://cwiki.apache.org/confluence/display/solr/Distributed+Search+with+Index+Sharding

-server? What does that mean?

`man java` says this...

       -server             Selects the Java  HotSpot  Server  VM.   For  more  information  see
                           Server-Class             Machine             Detection            at
                           http://java.sun.com/j2se/1.5.0/docs/guide/vm/server-class.html

... and if you follow that link you see this:

"Starting with J2SE 5.0, when an application starts up, the launcher can attempt to detect whether the application is running on a "server-class" machine and, if so, use the Java HotSpot Server Virtual Machine (server VM) instead of the Java HotSpot Client Virtual Machine (client VM). The aim is to improve performance even if no one configures the VM to reflect the application it's running. In general, the server VM starts up more slowly than the client VM, but over time runs more quickly."

Maybe this can help performance?

---

Related issue(s): #623
Redmine related issue(s): [3430](https://redmine.hmdc.harvard.edu/issues/3430), [4062](https://redmine.hmdc.harvard.edu/issues/4062)

---

**Comment by pdurbin** [comment]
This morning I did an "index all" on dvn-vm6 of the following in 309631 milliseconds (5.16 minutes)

- Dataverses (9)
- Datasets (120)
- Files (698)

I put some notes at https://docs.google.com/a/harvard.edu/document/d/19_A_Kw3eO_UdeO2RCiqD7we-TDUWaU6snVddnPAxBnQ/edit?usp=sharing . And there are other notes from different days if you browse around from there.

In general, I'm happy to test with more and different data on different machines as it is made available to me.

I'm not sure if we have a specific millisecond goal for this ticket. Obviously, faster is better.

**Comment by pdurbin** [comment]
As @scolapasta and I have been discussing, we want "index all" to skip the normal Solr doc cleanup that happens with indexing. (An example of Solr doc cleanup is when you publish a dataset and the Solr doc representing the draft is deleted.)

As of b774d76 "index all" now skips the normal Solr doc cleanup. You can tell the difference by indexing a dataset individually vs indexing the same dataset as part of "index all". Notice how the output of the "index all" version is much shorter (and hopefully faster!):

### Indexing a dataset individually (runs all Solr doc cleanup operations)

[2015-03-20T09:36:08.907-0400] [glassfish 4.1] [INFO] [] [edu.harvard.iq.dataverse.IndexServiceBean] [tid: _ThreadID=29 _ThreadName=http-listener-1(5)] [timeMillis: 1426858568907] [levelValue: 800] [[
  Desired state for existence of cards: {DRAFT=true, DEACCESSIONED=false, RELEASED=false}
No published version, nothing will be indexed as dataset_32
The latest version is a working copy (latestVersionState: DRAFT) and indexing was attempted for dataset_32_draft (limited discoverability). Result: indexed dataset 32 as dataset_32_draft. filesIndexed: [datafile_34_draft]
Draft exists, no need for deaccessioned version. Deletion attempted for dataset_32_deaccessioned (and files). Result: Attempted to delete dataset_32_deaccessioned from Solr index. updateReponse was: {responseHeader={status=0,QTime=1}}IndexResponse{message=no known problem deleting the following documents from Solr:[datafile_34_deaccessioned]}
No published version. Attempting to delete traces of published version from index. Result: Attempted to delete dataset_32 from Solr index. updateReponse was: {responseHeader={status=0,QTime=0}}IndexResponse{message=no known problem deleting the following documents from Solr:[datafile_34]}

debug:
version found with database id 5
- title: Spruce Goose
- semanticVersion-VersionState: DRAFT-DRAFT
- files: 1 [34:trees.png]
numPublishedVersions: 0
result of attempt to premptively deleted published files before reindexing: IndexResponse{message=no known problem deleting the following documents from Solr:[datafile_34]}
]]

### Indexing the same dataset as part of "index all" (Solr doc cleanup operations skipped)

[2015-03-20T09:38:44.614-0400] [glassfish 4.1] [INFO] [] [edu.harvard.iq.dataverse.IndexServiceBean] [tid: _ThreadID=127 _ThreadName=__ejb-thread-pool1] [timeMillis: 1426858724614] [levelValue: 800] [[
  Desired state for existence of cards: {DRAFT=true, DEACCESSIONED=false, RELEASED=false}
No published version, nothing will be indexed as dataset_32
The latest version is a working copy (latestVersionState: DRAFT) and indexing was attempted for dataset_32_draft (limited discoverability). Result: indexed dataset 32 as dataset_32_draft. filesIndexed: [datafile_34_draft]

debug:
version found with database id 5
- title: Spruce Goose
- semanticVersion-VersionState: DRAFT-DRAFT
- files: 1 [34:trees.png]
numPublishedVersions: 0
]]

**Comment by pdurbin** [comment]
Per @scolapasta I'm assigning this to @raprasad who is starting to look at this issue. See also #1757 which I opened today and #702 which is related.

**Comment by scolapasta** [comment]
For 4.0, we've developed some mitigating strategies (multithreaded indexing). Moving post 4.0 for improving performance.

**Comment by eaquigley** [comment]
Index performance improvements have been made and this is currently reasonable. Closing this ticket per @kcondon

**Comment by pdurbin** [comment]
@eaquigley @kcondon if you say so. I think it's something like 11 hours to do a full re-index of https://dataverse.harvard.edu as of Dataverse 4.3. We can always open a new issue if we'd like to attempt to make improvements in this area. Also, please note that I reference this issue at http://guides.dataverse.org/en/4.3/installation/administration.html#full-reindex ("Please note that this operation may take hours depending on the amount of data in your system") so we might want to remove that reference from the guides.

**Comment by pdurbin** [comment]
Related: Investigate and fix a memory leak in IndexAll #4463

**Comment by pdurbin** [comment]
Related:

- #9558
