### ISSUE TITLE
Tags Attack!  Tag Uniqueness is not enforced, resulting in multiples in select list and assigned in db.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#5002]
Reported by our internal data curation team:

On Friday, I was meeting with Danny when he noticed that there continues to be duplicate tags listed when applying tags to files on Dataverse. He thought this bug was fixed in the latest release to the issue persists. I was working on a MRA study (https://hdl.handle.net/1902.1/00640) when he noticed the duplicates.

It turns out it is not uncommon to copy and paste an existing tag into the create custom tag edit field rather than selecting the already created tag of the same name from the tag list box. Since we do not enforce tag uniqueness for a dataset, this results in multiple tags of the same name both in the db and in the tag select list, causing confusion.

This ticket is about enforcing unique tags for a dataset and also cleaning up existing records that may have used these multiple tags.

A power user (Dawyne) requested to have a future solution detect a duplicate if entered and rather than fail, just use the existing tag.

**Comment by mheppler** [comment]
Highly related to _Edit File Tags: Duplicate Custom Tags #2991_.

**Comment by mheppler** [comment]
Moving comment from #2991 here and closing that as a duplicate.

> Attempted to replicate the "minor" bugs reported above, but they seemed to have been resolved. Could be fix by a commit from @sekmiller on Mar 18, 2016 [6f02f7e](https://github.com/IQSS/dataverse/commit/6f02f7e4d890a78dd9d82c2c2c17fb5af9cf809f) that was part of the PR for said #2391 linked in the comment above.
> 
> One new bug for the Edit Tags popup that I discovered in demo (v. 4.14 build 1326-57a392d), on both the dataset and edit files pgs, is that when you create a custom file tag for one file, and then add it to a second in the same edit file metadata workflow, it results in two custom tags being generated and displayed in the dropdown going forward.
> 
> ![Screen Shot 2019-06-18 at 11 00 44 AM](https://user-images.githubusercontent.com/687227/59695639-8ac9c600-91b8-11e9-813e-35298565b4d5.png)
> 
> Also, to simplify this issue, I have removed the "consolidate two popups" suggestion from the title, as that is a far more involved code refactoring.
> 
> Highly related to _Tags Attack! Tag Uniqueness is not enforced, resulting in multiples in select list and assigned in db. #5002_. Maybe related to _Save on Upload error: Upload 3 files at once with descriptions and custom tags results in exception. #4918_

**Comment by djbrooke** [comment]
- Instead of creating a second tag when a custom tag already exists, just assign the existing tag
- What do with existing duplicate tags? Add a Flyway migration script to consolidate what's there 
- Define validation rules (consider case sensitivity, tabular tags)
