### ISSUE TITLE
import API failures

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#5004]
Somewhere between ~ efa7631a4727d4ab9099c78ec55aa09c7950b7d3 and 2f9172526dd5aedd8da572757ec52808dc25ae68 ; the behavior of the `/api/dataverses/${dataverse_alias}/datasets/:import` changed, at least in the case where the `release=yes` parameter was specified.  

Previous behavior was to import the dataset and make it publicly available without communicating with the PID provider, and specify that importing file PIDs was not supported.  New behavior is to fail to import the dataset, reporting an error message due to problems contacting the PID provider.  Debugging suggests this is due trying and failing to register a file PID during import.

**Comment by pameyer** [comment]
Additional investigation suggests that this is due to the `isPidPrePublished` option to `PublishDatasetCommand` not being propagated to the `FinalizeDatasetPublicationCommand`.

**Comment by pameyer** [comment]
Short summary of discussion from code review:
- Conditional in the wrong spot; may miss desired functionality in finalize publish command
- logic for PID protocol consistency should be extended to protocol + authority 
- potential for #4929 to make the changed behavior obsolete 
- philosophical discussion of small simple operations vs larger operations that try to anticipate user intent
- figure of PID's protocol, authority, shoulder, identifier and other various parts would be nice to include in guides at some point

**Comment by matthew-a-dunlap** [comment]
FWIW I don't think #4929 will impact this. It only disables file PIDs on an install level and will not help with any more granular cases.

**Comment by pameyer** [comment]
229c382e9bdac33ae49678dde04af2d9ad8a3899 should address code review suggestions, passes integration tests, and appears to match the original behavior of the API.  Will do some more checking, but this should be ready for QA / 2nd round of code review tomorrow.
