### ISSUE TITLE
`grabbing.png` cursor image missing

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#5006]
`owl.carousel.css` has a reference to `grabbing.png`; but references to this url trigger a 404 error.

Easiest fix might be to remove the reference if this isn't used; if it is used it should probably be added to the resources / resource manager somewhere.

**Comment by mheppler** [comment]
There appears to be a new version of [Owl Carousel](https://github.com/OwlCarousel2/OwlCarousel2). I am not sure the original project is being maintained, as their site appears to be down.

Going forward it'd probably be worth updating these resource files with the latest and greatest, which appears to be version 2.3.4 released this past Apr.

**Comment by djbrooke** [comment]
@mheppler hoot hoot, does it make sense to have this issue reflect an update/switchout of Owl Carousel instead of this one off? Feel free to retitle if so.

**Comment by mheppler** [comment]
Yeah. I think it makes the most sense to keep these plugins up to date. We have a similar update issue for the Sharrre plugin #4538.

**Comment by pameyer** [comment]
When I was looking into this, https://github.com/cdnjs/cdnjs seemed like a good resource for tracking down resources from vanished projects.
