### ISSUE TITLE
Uploading data file through API and with json params = {} overwrites UNF/file description in UI

### ISSUE THREAD

**Issue by mdmADA** [IQSS/dataverse#5010]
v4.6.1

Scenario:

-> using python requests.post(), programmatically upload data file through API call "$SERVER/api/datasets/$id/add"

```
params = {}
files = {
	'jsonData': (None, json.dumps(params), 'application/json'),
	'file': (file_label, open(local_datafile, 'rb'), content_type)
}
```

call the API with requests.post() and pass headers, files

====> the UNF of the file does not appear in the Dataverse file description in the UI
(I have not had a chance to check the database to verify if the UNF has been calculated)

-> having a "description" value in the params is ok - UNF shows in file description in the UI

-> so the user should make sure the jsonData params is not empty - if it, is don't send it to the API, only send the file:

if params is not None and len(params) > 0:   #perhaps further conditions need testing?

	files = {
		'jsonData': (None, json.dumps(params), 'application/json'),
		'file': (file_label, open(local_datafile, 'rb'), content_type)
	}

else:

	files = {
		'file': (file_label, open(local_datafile, 'rb'), content_type)
	}

url = "$SERVER/api/datasets/$id/add"	 #correct url of course!!
d_headers = { 'X-Dataverse-key': api_key }
api_resp = requests.post(url, headers=d_headers, files=files)
	
-> the Dataverse API code should check the params as well - don't overwrite the UNF in the file description if the params is empty (if that is what is actually happening)

**Comment by pdurbin** [comment]
@mdmADA thanks for the bug report. I made some minor formatting changes in the description above (fenced code blocks and such).

**Comment by pdurbin** [comment]
Heads up that there are some changes to this part of the code coming in pull request #5715

**Comment by scolapasta** [comment]
This will be handled when we work on #5716, which is more general about what should and shouldn't be editable (or by whom) through the API.
