### ISSUE TITLE
Make Dataverse an OAuth provider

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#5012]
As we continue to add external tools, some of those tools will require a user to create an account / log in to their site (e.g. CodeOcean). To make this process easier for the user, Dataverse should become an Oauth provider so users can more seamlessly be logged into those sites.

**Comment by djbrooke** [comment]
@scolapasta are there UI/UX design considerations here?

**Comment by scolapasta** [comment]
Discussed with team and since other tools would need to support Oauth as a client in these cases, it seemed just as useful for them to just support Google or Github (or even Shibboleth) and not have to provide infrastructure on the Dataverse side to be yet another provider.
