### ISSUE TITLE
As a curator, I want the email notification I get when someone submits a dataset for review to include the name and email of the submitter so that reviewing datasets is more convenient

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#5013]
As a curator, I want the email notification I get when someone submits a dataset for review to include the name and email of the submitter so that I can:
- Use the extra information to remind me what the dataset is or what I need to do with it
- Click on the email address link to email the submitter (instead of getting the email someplace else, e.g. copying it from the dataset metadata, using the contact form on the dataset page, looking for the email in my address book)

This is what the email looks like now for a fictional dataverse named ABC Dataverse in an installation called Data Dataverse:

> **Subject line:**
ABC Dataverse: Your dataset has been submitted for review
> 
> Hello, 
> "Dataset title" (view at https://data.dataverse.org/dataset.xhtml?persistentId=doi:10.5072/123/ABCDE&version=DRAFT&faces-redirect=true) was submitted for review to be published in ABC Dataverse (view at https://data.dataverse.org/dataverse/ABC). Don't forget to publish it or send it back to the contributor!
> 
> You may contact us for support at datadataverse@email.com.
> 
> Thank you,
> Data Dataverse Support

This issue recommends adding the depositor's name and email to the existing email notification text. To reference what other email notifications look like, here's the [inventory of email notifications](https://docs.google.com/spreadsheets/d/1Bw8MdN2Cv_IZp31hzZgtdyremvA2DobsC1O9x3PguJY).

@sbarbosadataverse suggested this and other changes in https://github.com/IQSS/dataverse/issues/2128 (which has been closed and split into other Github issues)

This change is similar to #3702 (which is still planned) in that its purpose is to improve how reviewers and submitters communicate.

**Comment by sekmiller** [comment]
The name and email address of the contributor who presses the "Submit for Review" button is added to the email and notifications received by those having Publish Dataset permission on the dataset.

Email excerpt:

Don't forget to publish it or send it back to the contributor (Joe Contributor at joe_con@domain.org)!
