### ISSUE TITLE
Solr: Disable Solr Cell/ Tika from solr config

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#5018]
Requested by a user, recommended by Solr not to run in a prod env, see RT: 266424
Simple solution is to comment out the relevant handler and lib sections of solrconfig.xml

You can experiment with disabling it by editing the solrconfig.xml file and commenting out the following sections:
https://lucene.apache.org/solr/guide/7_0/uploading-data-with-solr-cell-using-apache-tika.html 

```
  <requestHandler name="/update/extract"
                  startup="lazy"
                  class="solr.extraction.ExtractingRequestHandler" >
    <lst name="defaults">
      <str name="lowernames">true</str>
      <str name="fmap.meta">ignored_</str>
      <str name="fmap.content">_text_</str>
    </lst>
  </requestHandler>
```
and
```
  <lib dir="${solr.install.dir:../../../..}/contrib/extraction/lib" regex=".*\.jar" />
  <lib dir="${solr.install.dir:../../../..}/dist/" regex="solr-cell-\d.*\.jar" />
```

**Comment by qqmyers** [comment]
@djbrooke - I think this is orthogonal to #5030. I've included the tika lib in Dataverse and it is used there to extract text that is then sent to solr to index. I think you can also send whole docs to solr and have tika run there, which is what I think is not recommended for production.

**Comment by djbrooke** [comment]
Great, thanks @qqmyers. I was just keying on the mention of Tika without the background knowledge. 👍

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
