### ISSUE TITLE
Ability to enter a partial search term without * and get results.

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#502]
---

Author Name: **Elizabeth Quigley** (@eaquigley)
Original Redmine Issue: 3917, https://redmine.hmdc.harvard.edu/issues/3917
Original Date: 2014-05-02
Original Assignee: Philip Durbin

---

It is desired that when you search for "dog" you find "doghouse" without needing to type "dog*".

---

Redmine related issue(s): [2967](https://redmine.hmdc.harvard.edu/issues/2967)

---

**Comment by eaquigley** [comment]
Need to look into google analytics and see how users are searching in Dataverse to make this a data driven decision instead of us trying to decide what is best.

**Comment by kcondon** [comment]
Closing, have made improvements already and following user needs/suggestions.
