### ISSUE TITLE
`:FilePIDsEnabled` setting ignored for DCM created package files

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#5021]
On 020a47bc90260b1d27751f52a517f73ff6a6faae with docker-dcm; `curl -X PUT -d 'false' "http://localhost:8080/api/admin/settings/:FilePIDsEnabled"` ; create dataset via API, upload dataset w\ transfer script from DCM; `docker exec -it dcmsrv /opt/dcm/scn/post_upload.bash`.

`dvobject` table shows identifier (and identifierregistered=t) for the resulting data file; file page citation shows PID.

**Comment by kcondon** [comment]
@pameyer to simplify this test case, I could simply disable file PID, create a dataset with a file and check the dvobject table for the datafile, looking for an identifier and file page citation containing a PID? Failing that I could try using the api to create the dataset?
