### ISSUE TITLE
The account conversion fails if the builtin authentication is disabled

### ISSUE THREAD

**Issue by pkiraly** [IQSS/dataverse#5026]
When a site disables the builtin authentication, and the user logs in into Dataverse via Shibboleth using the same email, what s/he used previously in the builtin login, Dataverse asks the user if s/he want to convert the account from builtin based to Shibboleth based. The user doesn't have any other option than accept this question otherwise Dataverse does not accept the user as authenticated. The process starts, but end with failure and a not informative error message: 

"Internal Server Error - An unexpected error was ancountered, no more information is available" 

The Glassfish log contains the following error message:

```
[glassfish 4.1] [WARNING] [] [javax.enterprise.resource.webcontainer.jsf.lifecycle] [tid: _ThreadID=54 _ThreadName=jk-connector(3)] [timeMillis: 1535979567156] [levelValue: 900] [[
  #{Shib.confirmAndConvertAccount()}: javax.ejb.EJBException
javax.faces.FacesException: #{Shib.confirmAndConvertAccount()}:
javax.ejb.EJBException
at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:118)
at javax.faces.component.UICommand.broadcast(UICommand.java:315)
...
Caused by: java.lang.IllegalArgumentException: No authentication
provider listed under id builtin
at edu.harvard.iq.dataverse.authorization.AuthenticationServiceBean.getCreateAuthenticatedUser(AuthenticationServiceBean.java:342)
at edu.harvard.iq.dataverse.authorization.AuthenticationServiceBean.canLogInAsBuiltinUser(AuthenticationServiceBean.java:799)
```

The relevant code checks the list of authentication providers via the query named "AuthenticationProviderRow.findAllEnabled" which checkes only the enabled authentication methods:

`SELECT r FROM AuthenticationProviderRow r WHERE r.enabled=true`

When our service started we enabled only the builtin type, then when we set up the Shibbolet authentication we disabled it. So right now we have some users, which were created via the builtin methods. but haven't yet converted into the shibboleth account. For them the conversion throws this error message, and is not sucessfull.

Is it possible to set this flag (AuthenticationProviderRow's table enabled column to 't') without adding the builtin method to the login form?

Now the authenticationProviders list looks like:
```
curl -s http://localhost:8080/api/admin/authenticationProviders | jq .
{
  "status": "OK",
  "data": [
    {
      "id": "shib",
      "factoryAlias": "shib",
      "enabled": true
    },
    {
      "id": "builtin",
      "factoryAlias": "BuiltinAuthenticationProvider",
      "title": "Dataverse Local",
      "subtitle": "Dataverse Internal Authentication provider",
      "factoryData": "",
      "enabled": false
    }
  ]
}
```
I guess if I delete the builtin from here, I will delete the row from the table. And if I simply enable it, it will shown up in the login form.

As I see it, there are two errors with the current approach:

1. in the process of authentication the system recognize that the email address belong to an existing user, even if the builtin authentication is not enable, while on a later point the authentication's presence is a requirement. This is inconsistency. The process should either fail at the beginning or should be successful till the end (this would be my natural choice).

2. The conversion and enabling/disabling the authentication form should be independent. To set up Shibboleth took a long time in our institution, and meantime we enables builtin login. Then when we fixed the issues with Shibbolet, we wanted to stop the possibility of builtin login, but we don't want to loose our existing users, we would like to convert them to Shibboleth users.

Dataverse version: 4.9..2

**Comment by pdurbin** [comment]
@pkiraly hi! Is this still a problem for you? It seems like it doesn't come up very often. Thanks.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
