### ISSUE TITLE
Double entry for variable "application/x-stata-14" for Mime Type display; "application/x-stata-15" variable seems to be missing (?)

### ISSUE THREAD

**Issue by mhvezina** [IQSS/dataverse#5031]
Spotted while doing translation work.

There is a double entry for variable "application/x-stata-14" within MimeTypeDisplay.properties.

Quick guess is that 2nd entry should be "application/x-stata-15" (since this mime type is also referred to in MimeTypeFacets.properties).

https://github.com/IQSS/dataverse/commit/cb26fea371eb234ce34c363b5914ec8e19ba99e7#r30430369

**Comment by pdurbin** [comment]
Yes, as I was saying at cb26fea I believe this is a copy/paste error I made.

Thanks for reporting this, @mhvezina !

The fix is a one character change for anyone who's interested in making a pull request.

**Comment by pdurbin** [comment]
Pull request #5038 looks good. Thanks, @JayanthyChengan !

Moving to QA.

**Comment by kcondon** [comment]
@pdurbin @JayanthyChengan On this branch, a stata 15 file appears as a stata 14 binary in the download as pull down. In /develop it appears as stata 15.

**Comment by JayanthyChengan** [comment]
Thanks

**Comment by pdurbin** [comment]
Yeah, in my testing a Stata 15 file was a minimum of 21 MB so in the code I simply put in one liner and instructions to create a Stata 15 file is we need it: https://github.com/IQSS/dataverse/blob/v4.9.2/src/test/java/edu/harvard/iq/dataverse/ingest/tabulardata/impl/plugins/dta/NewDTAFileReaderTest.java#L127


    // TODO: Is there a way to exersise this code with a smaller file? 33k.dta is 21MB.
    @Ignore
    @Test
    public void test33k() throws IOException {
        instance = new NewDTAFileReader(null, 119);
        // for i in `echo {0..33000}`; do echo -n "var$i,"; done > 33k.csv
        // Then open Stata 15, run `set maxvar 40000` and import.
    }
