### ISSUE TITLE
Internationalization: To keep the ValidationMessages.Properties outside the main app and access from file system

### ISSUE THREAD

**Issue by JayanthyChengan** [IQSS/dataverse#5040]
Note:
bundle.properties outside the main app is handled in the issue : https://github.com/IQSS/dataverse/issues/4892

Creating new issue, since **ValidationMessages.properties** works differently compared to bundle.properties, which requires some code changes and update in Hibernate version.

For example: 
   In DatasetVersion.java,  the below two lines takes the ValidationMessages.properties, located in the default package as required by the Bean Validation specification 
(refer to ValidationMessages.properties at : https://docs.oracle.com/javaee/6/tutorial/doc/gkafh.html#gkada)

ValidatorFactory factory = Validation.buildDefaultValidatorFactory();
Validator validator = factory.getValidator();

So, to access the ValidationMessages.properties from the file location, have to incorporate the method PlatformResourceBundleLocator("VMessages"  , urlClassLoader ); with two arguments, which is available only from version 5.2 (http://docs.jboss.org/hibernate/validator/5.2/api/org/hibernate/validator/resourceloading/PlatformResourceBundleLocator.html#PlatformResourceBundleLocator-java.lang.String-java.lang.ClassLoader-boolean-)

The code snippet is here:

       String filesRootDirectory = System.getProperty("dataverse.lang.directory");
      
        File file = new File(filesRootDirectory);
        URL[] urls = null;
        try {
            urls = new URL[]{file.toURI().toURL()};
        }
        catch (Exception e)
        {}

        ClassLoader urlClassLoader = new URLClassLoader(urls);

        PlatformResourceBundleLocator resourceBundleLocator;
        resourceBundleLocator = new PlatformResourceBundleLocator("VMessages"  , urlClassLoader );

       Validator validator = Validation.byProvider(HibernateValidator.class)
        .configure()
       .messageInterpolator(new ResourceBundleMessageInterpolator(resourceBundleLocator ))
        .buildValidatorFactory()
        .getValidator();

Would like advice on this?  In the meantime, I am also looking at any other workaround solution on this.  Thanks

**Comment by pdurbin** [comment]
@JayanthyChengan you did this already, right? (Thanks! 🎉 ) This PR:

- #4815

**Comment by JayanthyChengan** [comment]
Yes @pdurbin , I am closing with issue.
