### ISSUE TITLE
File icons for specific file types if there isn't a thumbnail preview

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#505]
---

Author Name: **Elizabeth Quigley** (@eaquigley)
Original Redmine Issue: 3920, https://redmine.hmdc.harvard.edu/issues/3920
Original Date: 2014-05-05
Original Assignee: Leonid Andreev

---

None

**Comment by landreev** [comment]
@eaquigley 
@mheppler 
@scolapasta : 
I've had this ticket for a while; I'm assuming it's for showing this type-specific file icons on both the dataset page and search cards; 
shouldn't be difficult; but it depends on having the actual file-specific icons around. 
Is it still part of 4.0?
Is there a dedicated ticket for creating these icons? Who's making them, Dwayne? (or Mike?)

**Comment by landreev** [comment]
@eaquigley 
@mheppler 
@scolapasta 
Hey, could somebody please reply (to the questions from the previous comment), and let me know what the deal is.

**Comment by eaquigley** [comment]
@mheppler could you please respond to @landreev about this since you have been coordinating icons.

**Comment by mheppler** [comment]
@landreev 
The custom icons ticket is #1178 and I will be working on it for Beta 13. The backend render logic should be worked on hand-and-hand with this, so we're on the same page. Coordinate a meeting with me when you are ready.

**Comment by landreev** [comment]
@scolapasta 
Spoke to Mike; I can work on this even before all the icons are ready; and get my part done for beta13.
This is not a rocket science ticket. But it is a bit tedious. I have a lot to get done for b13 by now; will try to get done as much as possible.

**Comment by landreev** [comment]
I passed the render and identification methods to Mike. 
Basically this ticket is for the backend mechanisms needed for Mike to wire the icons in the UI. Which he's handling in #1178. 
I'll pass this ticket to QA once Mike's ticket is done.

**Comment by landreev** [comment]
OK, Mike has moved #1178 into QA. 
One more time, this ticket is the backend mechanics for the ticket above. 
So the two should be QAed together.

**Comment by kcondon** [comment]
OK, icons appearing, closing
