### ISSUE TITLE
WorldMap - Explore button for geo file disappeared

### ISSUE THREAD

**Issue by Thanh-Thanh** [IQSS/dataverse#5052]
Hi all,
We used dataverse 4.8.6 with a local geoconnect. 
We have had the Explore button for geo file before, as we have set :GeoconnectViewMaps to true.
However, after migrating to 4.9.1, the "Explore" button does not show up. The :GeoconnectViewMaps is always true.

I have seen the same thing on the demo website of dataverse, ex: https://demo.dataverse.org/dataset.xhtml?persistentId=doi:10.5072/FK2/LCAQ4F
My geo file here does not have the "Explore" button as before.
![geo_file_explore_button_problem](https://user-images.githubusercontent.com/39987392/45490752-406a7300-b768-11e8-8b2e-01946b0c787a.PNG)

This is a bug or the "Explore" button for geo file is deleted in 4.9.1 ?

Thanks in advance,

Thanh Thanh

**Comment by mheppler** [comment]
This is also an issue with the [Harvard Dataverse](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/PJ3JK2) (v. 4.9.2 build 940-4ad7bf5).

![screen shot 2018-09-13 at 11 08 19 am](https://user-images.githubusercontent.com/687227/45497284-66cae700-b745-11e8-9bd8-febffde8720b.png)

**Comment by mheppler** [comment]
Additionally, on the [Harvard Dataverse](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/YFLY1F) the Explore btn is being displayed for Data Explorer, but does not have the dropdown list of options which includes WorldMap.

![screen shot 2018-09-13 at 11 31 22 am](https://user-images.githubusercontent.com/687227/45498916-35541a80-b749-11e8-9a69-4220695f2e66.png)

**Comment by sekmiller** [comment]
Explore Button would not appear if the file was a WorldMap file and there were no other explore tools.
Also, it wouldn't; appear a button with a dropdown option if there was exactly one explore tool plus World Map
