### ISSUE TITLE
Internationalization : MimeTypeDisplay and MimeTypeFacets property files

### ISSUE THREAD

**Issue by JayanthyChengan** [IQSS/dataverse#5055]
Would like to add french property file for MimeTypeDisplay and MimeTypeFacets , and to modify
 FileUtil.java to get corresponding language specific property value.

https://github.com/IQSS/dataverse/blob/develop/src/main/java/edu/harvard/iq/dataverse/util/FileUtil.java#L209
and
https://github.com/IQSS/dataverse/blob/develop/src/main/java/edu/harvard/iq/dataverse/util/FileUtil.java#L227
     _ResourceBundle.getBundle("MimeTypeDisplay").getString(fileType);_
     _ResourceBundle.getBundle("MimeTypeFacets").getString(fileType);_
has to be changed to fetch corresponding locale value.

**Comment by kcondon** [comment]
OK, this works but saw Mike's comments in pull request. Not sure of order/timing, will discuss with group at standup.

**Comment by djbrooke** [comment]
We're waiting for @JayanthyChengan and SP to review @mheppler suggestions re: capitalization and the changes made in #5067.

**Comment by JayanthyChengan** [comment]
@djbrooke : I reviewed and commented at https://github.com/IQSS/dataverse/pull/5073

**Comment by pdurbin** [comment]
@JayanthyChengan thanks. There's a new developer who's having trouble will the latest code in "develop". @juancorr and I have been trying to help. If you have time, please take a look at http://irclog.iq.harvard.edu/dataverse/2018-09-25

**Comment by pdurbin** [comment]
@JayanthyChengan heads up that the pull request for #5067 was merged today. That's pull request #5073 where some capitalization happened.

**Comment by JayanthyChengan** [comment]
@pdurbin:  Thanks.  I merged the latest develop branch.  The code is ready for review.

Also requested @mhvezina for capitalization correction in french MimeTypeFacets.properties

**Comment by JayanthyChengan** [comment]
@pdurbin:  updated MimeTypeFacets_fr.properties after fixing capitalization
