### ISSUE TITLE
As a researcher, I need to know more about deaccessioning before I deaccession my dataset so I can make sure my data is easy to find

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#5056]
When depositors need to remove a dataset, they can deaccession it or contact the installation's support team to ask how to remove it. If they choose to deaccession it, the UI doesn't let depositors know that the action is irreversible:

<kbd><img width="500" alt="screen shot 2018-09-13 at 6 04 29 pm" src="https://user-images.githubusercontent.com/18374574/45518430-7d8e2f80-b77f-11e8-9d19-4406db73d26a.png"></kbd>

<kbd><img width="500" alt="screen shot 2018-09-13 at 5 45 29 pm" src="https://user-images.githubusercontent.com/18374574/45517659-e88a3700-b77c-11e8-89f8-6416765e4905.png"></kbd>

So occasionally depositors deaccession datasets thinking they can return the dataset to a draft state if they decide not to deaccession. This is especially a problem when the ID of the deaccessioned dataset (e.g. DOI) has already been published someplace else (like a journal article). Someone following the ID from that article lands on the deaccessioned page ("tombstone" page) and can't get the data (and the depositor isn't able to update the deaccession reason to point others who find the deaccessioned dataset to another dataset where they can get the files (https://github.com/IQSS/dataverse/issues/4743).)

**Comment by jggautier** [comment]
The "Deaccession Dataset" popup could include a link to the explanation of deaccessioning in the User Guides or a sentence saying that the action is irreversible.

**Comment by gohsunee** [comment]
I concur that we need to inform the depositor via the UI:
 - that the deaccessioning is irreversible;
 - the reason entered for deaccessioning will become visible to public;
 - that there'll be a 'tombstone' page; and
 - the purpose of the 'tombstone' page.

**Comment by cmbz** [comment]
**2024/01/22:**
- Prioritizing as per the meeting. Preliminary size: 3

**Recommendation:**
- Create warning text (e.g., @sbarbosadataverse  or @jggautier)
- Determine it a link to the deaccessioning guide can be added, too as part of the text
- Change the dialog message to reflect the new text
- Confirm the text does not cause the dialog box to overflow

**Comment by sbarbosadataverse** [comment]
@jggautier your feedback on my proposed text when you have time:

This action is not reversible and will require creating a new major version of your dataset if the need to revive it occurs.

**Comment by jggautier** [comment]
Thanks @sbarbosadataverse.

How would we determine if a link to [the deaccession section of the User Guide](https://guides.dataverse.org/en/6.1/user/dataset-management.html?highlight=deaccession#dataset-deaccession) can be added as part of the text? Is this something a developer can look into to? I ask because I think that will affect what info we add to the text and what info we expect users to learn from that section in the User Guides.

Here's what the popup and the current text (in gold) looks like in v6.1:
<img width="657" alt="Screenshot 2024-01-23 at 11 25 35 AM" src="https://github.com/IQSS/dataverse/assets/18374574/5f28e585-b748-47ec-bc65-82b1086f169d">

**Comment by shlake** [comment]
It is also confusing if you deaccession the most recent version (and do not check all the versions), then the earlier versions are what one sees if you go to the dataset page.

The initial popup should say (link the confirmation popup):
**_The selected version(s) will no longer be viewable by the public._**

Not "Once your deaccession this dataset it will no longer be viewable by the public." Because if only one version is checked, the others are still viewable - maybe this is a different issue?

**Comment by shlake** [comment]
I consider deaccessioning as reversible, as Sonia says, the version will have changed (if that makes a difference?).

**Comment by jp-tosca** [comment]
Hi @shlake 👋🏼 

We made a proposed change to the message [here](https://github.com/IQSS/dataverse/pull/10315) which warns the user about the operation being not reversible and points the user to the documentation.

![image](https://github.com/IQSS/dataverse/assets/142103991/b042bb99-80d9-49ab-ab88-1a8548bdd466)
