### ISSUE TITLE
Are dataset and file metadata records already sent to EZID/DataCite being updated?

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#5060]
Are metadata records already sent to EZID/DataCite being updated as Dataverse adds metadata in the DataCite schema?

I'm assuming (so it's possible I'm wrong :) that in some cases it's not being updated because:
- The dataset and file metadata made available over OAI-PMH from EZID (like [the metadata for this file](https://ezid.cdlib.org/oai?verb=GetRecord&metadataPrefix=datacite&identifier=doi:10.7910/DVN/ZSCLQA/PQ7MFZ)) and DataCite (like [the metadata for this dataset](https://oai.datacite.org/oai?verb=GetRecord&metadataPrefix=oai_datacite&identifier=oai:oai.datacite.org:2032547)) don't have recent changes (e.g. the file metadata doesn't list the file's dataset as a relatedIdentifier, and the dataset has "Text" as the resource type when it should be "Dataset").
- The DataCite XML you can download for each "Work" (dataset or file) on DataCite Search doesn't include the additional metadata (e.g. the DataCite XML you can download [on this page](https://search.datacite.org/works/10.7910/dvn/rtb67k/emk9hp) for a file on Harvard Dataverse doesn't include its dataset as a relatedIdentifier (#4782)).

However, [this OAI-PMH record from EZID](https://ezid.cdlib.org/oai?verb=GetRecord&metadataPrefix=datacite&identifier=doi:10.7910/DVN/ZSCLQA) includes all of the authors added to [this dataset's second version](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/ZSCLQA&version=2.0) ([the first version](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/ZSCLQA&version=1.0) had just one author), so it looks like some information from the DataCite schema's required fields, like the creator field, are getting updated, and some, like the resourceType, are not. (Will this affect Dataverse's ability to update the resourceType displayed in DataCite Fabrica (#5086)?)

Could the issue be on DataCite's and EZID's ends (maybe with the way they're updating metadata they make available over OAI-PMH)? Or with how DataCite produces the DataCite XML we can download for each [work on DataCite Search](https://search.datacite.org/works/10.7910/dvn/rtb67k/emk9hp)?

It's important that the existing metadata records that EZID and DataCite have (and make available over OAI-PMH) are updated as Dataverse continues to improve the amount of metadata it sends to these data hubs, which redistribute this metadata and rely on some of it, like the relatedIdentifier metadata, to help generate citation metrics (for the Make Data Count work, #4821, which will be less effective if the metadata that DataCite has for old datasets doesn't include related identifier metadata).

**Comment by kcondon** [comment]
- [x] related identifier now works for EZID. 
- [ ] update metadata endpoint throws 404: curl -H "X-Dataverse-key: $API_TOKEN" -X POST http://$SERVER/api/admin/$dataset-id/modifyRegistrationMetadata

**Comment by landreev** [comment]
@sekmiller and everybody: 
Martin Fenner @mfenner (DataCite Technical Director) has pointed this out after the migration from EZID: 

```
something I see a lot in your DataCite metadata is multiple authors in one <creatorName>, e.g. (for DOI 10.7910/dvn/l2ltsc registered yesterday)
<creator>
<creatorName>M. Takayasu, L. Chiesa, J.V. Minervini</creatorName>
</creator>
It should instead be
<creator>
<creatorName>Takayasu, M.</creatorName>
</creator>
<creator>
<creatorName>Chiesa, L.</creatorName>
</creator>
<creator>
<creatorName>Minervini, J.V.</creatorName>
</creator>
Mutliple authors in one <creatorName> not only is not what the schema documentation says, but also makes many things hard or impossible, e.g. adding an ORCD or generating a properly formatted citation in any of the available citation styles.
```
This does seem like a real issue. Since this (#5060) is related to DOI metadata, and it's already in dev., should we take a look  at this problem as well, while we're at it? 
Otherwise, let me know and I'll open a new issue.

**Comment by landreev** [comment]
A quick investigation: I checked a couple of brand-new DOIs that have been minted  w/ DataCite since the upgrade yesterday - and they appear to have separate creatorName entries; for example:
```
<identifier identifierType="DOI">10.7910/DVN/YLUPSB</identifier>  
  <creators> 
    <creator> 
      <creatorName>Dossou-Yovo, Elliott</creatorName>  
      <nameIdentifier schemeURI="https://orcid.org/" nameIdentifierScheme="ORCID">0000-0002-3565-8879</nameIdentifier>  
      <affiliation>(Africa Rice Center)</affiliation> 
    </creator>  
    <creator> 
      <creatorName>Baggie, Idriss</creatorName>  
      <affiliation>(Sierra Leone Agricultural Research Institute)</affiliation> 
    </creator>  
    <creator> 
      <creatorName>Djagba, Justin Fagnombo</creatorName>  
      <affiliation>(Africa Rice Center)</affiliation> 
    </creator>  
    <creator> 
      <creatorName>Swart, Sander</creatorName>  
      <affiliation>(Africa Rice Center)</affiliation> 
    </creator> 
  </creators>  
```
So my first guess was that this was only a problem with the DOIs migrated from EZID; but then the example Martin provided, above, is ALSO brand-new; minted yesterday. 
So this means, I'm guessing, that those 3 authors are actually stored as the single author name in our database (??)
And that would mean this is a problem with our metadata, not with our DOI implementation... OK, either way, this needs to be investigated, whether in the context of this github issue or not.

**Comment by sekmiller** [comment]
There was a typo in the doc the curl command for the api is:
curl -H "X-Dataverse-key: $API_TOKEN" -X POST http://$SERVER/api/datasets/$dataset-id/modifyRegistrationMetadata

**Comment by jggautier** [comment]
Regarding @landreev [comment](https://github.com/IQSS/dataverse/issues/5060#issuecomment-431444168): "So this means, I'm guessing, that those 3 authors are actually stored as the single author name in our database (??)", I'm not sure why I never looked into this until now, but Leonid's hunch was right. Many of the datasets in the collection at https://dataverse.harvard.edu/dataverse/MIT-PSFC have multiple authors added in one field. This problem's been documented at https://github.com/IQSS/dataverse/issues/4035, though I suppose the name of the issue should be broadened.
