### ISSUE TITLE
inconsistent IT failures on develop (dd4ba227c50507989ed011de7b1ef69432a6a96c)

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#5069]
https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-apitest-develop/lastBuild/ shows 2 failures (edu.harvard.iq.dataverse.api.FileMetadataIT.testJsonParserWithDirectoryLabels x2) on dd4ba227c50507989ed011de7b1ef69432a6a96c ; docker-aio shows 0 failures 1 error (`HarvestingServerIT.testOaiFunctionality:153 » XmlPath Failed to parse the XML`) on same commit.

**Comment by pameyer** [comment]
A little more investigation - when I logged in as dataverseAdmin and checked the dashboard, harvesting wasn't enabled.  After enabling it, the ITs pass.  So the docker-aio failure may be due to misconfiguration (slight possibility that it's something that's not configurable without a UI login).

`curl -X PUT -d 'true' "http://localhost:8080/api/admin/settings/:OAIServerEnabled"` ; `Tests run: 75, Failures: 0, Errors: 0, Skipped: 0` for dd4ba22 in docker-aio.

Not sure if this is a configuration option that also needs to be changed in jenkins/phoenix or not.  Still not seeing the edu.harvard.iq.dataverse.api.FileMetadataIT.testJsonParserWithDirectoryLabels problems.

**Comment by pameyer** [comment]
Since I never actually assigned myself to this when I was looking into it, I can't un-assign myself.

But PR #5070 should be good to go.

**Comment by pdurbin** [comment]
@pameyer your fix for the harvesting stuff looks good to me but are we using this issue to represent the FileMetadataIT.testJsonParserWithDirectoryLabels failure as well? If so, I assume there's more work to do.

**Comment by pameyer** [comment]
@pdurbin If FileMetadataIT.testJsonParserWithDirectoryLabels is still failing on develop, that makes sense to me - but I don't see those failures when I run them.

**Comment by pdurbin** [comment]
Ok, now that I've added HarvestingServerIT to the list of tests on the phoenix server and run the test suite https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-apitest-develop/240/ indicates that HarvestingServerIT.testOaiFunctionality is failing, as expected. It sounds like this is good to go so I'll move it to QA.
