### ISSUE TITLE
validation: number of characters count is not in dataset description

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#507]
---

Author Name: **Elda Sotiri** (@esotiri)
Original Redmine Issue: 3922, https://redmine.hmdc.harvard.edu/issues/3922
Original Date: 2014-05-05
Original Assignee: Steve Kraffmiller

---

 Validation Error Description may not be more than 1000 characters.

**Comment by eaquigley** [comment]
@scolapasta Shouldn't we treat this text field the same way we do for Dataverse Alias and Username which was have a standard of 60 (I think) characters?

**Comment by eaquigley** [comment]
Passing this ticket to QA to close and am moving the last few comments to a new ticket as they deal specifically with Dataverse Role description limit NOT dataset description as this ticket was originally about.

**Comment by kcondon** [comment]
Was able to enter >10k chars without an issue. Closing
