### ISSUE TITLE
Refactoring of S3AccessIO driver

### ISSUE THREAD

**Issue by poikilotherm** [IQSS/dataverse#5072]
Hi @landreev 

while digging into the driver to get things running for #4690 and #5068 it seems you wrote most of the storage driver for AWS S3. (At least you opened #3921 :wink: )

In #5059 I started work to implement unit and integration testing for the driver. Are you interested to join?

**Comment by pdurbin** [comment]
@poikilotherm I see you're already working away on this over at https://github.com/poikilotherm/dataverse/commit/52510451d3f9b58bdead72311150fc5b9c63c05f adding unit tests. Great! Thanks!

**Comment by poikilotherm** [comment]
Yes I am - but it is quite an amount of work... And many details of the implementation are unknown to me.

Example: in [getMainFileKey()](https://github.com/IQSS/dataverse/blob/d0cb4021a9396e6ac47aef97910abe028fa49510/src/main/java/edu/harvard/iq/dataverse/dataaccess/S3AccessIO.java#L646) it is not obvious to me, why this method is not written sideeffect free. I hoped that @landreev could help me out with a lots of details about the driver... :wink:

**Comment by poikilotherm** [comment]
Maybe @ferrys, @matthew-a-dunlap, @bsilverstein, @oscardssmith and other can look into this, too?

**Comment by oscardssmith** [comment]
Most of the changes I made were making `StorageIO` parametric on the type of `DVObject` stored. My sense in general is that this area was rather underdesigned, and the reason for most of these types of questions is because "It worked and we want to move on". What is the side effect by the way?

**Comment by poikilotherm** [comment]
> What is the side effect by the way?

Both the instance vars `key` and `bucketName` get set inside, although `key` is set again with the return value of the function. This could be by design or unintended - hard to predict without comments and not being involved before... :wink:

**Comment by poikilotherm** [comment]
Mentioning #5165

**Comment by poikilotherm** [comment]
Mentioning #5996 here...

**Comment by pdurbin** [comment]
We now have some tests for S3AccessIO:

- #10044

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
