### ISSUE TITLE
Code styling seems inconsistent?

### ISSUE THREAD

**Issue by poikilotherm** [IQSS/dataverse#5075]
Dear all,

currently being active working on patches and stuff, I wondered about the style conventions you guys use and how I should write my code to be in line with your code of conduct. Example: indentation. I just found http://guides.dataverse.org/en/latest/developers/coding-style.html, which is not very precise/elaborated on that.

I would really enjoy something more sophisticated (like how you would like to see braces been set, etc)...

Also, there seem to be issues with different settings from different developers. An example from my IDEA IDE, showing the Maven `pom.xml`:
![grafik](https://user-images.githubusercontent.com/5468333/45889997-29f49500-bdc2-11e8-9941-e36d67b7282e.png)
But I also saw indentation hell in some Java code files...

Maybe some tooling could help with this? E.g. [CheckStyle](http://checkstyle.sourceforge.net/), which can be configured as needed, starting with indentation and maybe add more stuff down the road? This is also available as simple to use Maven plugin...

**Comment by pameyer** [comment]
It looks like it hasn't hit a release yet, but `doc/sphinx-guides/source/developers/coding-style.rst` may have some more information.  I've done a little with `astyle` (although I didn't come up with a satisfactory solution to the "just reformat the code you changed, not the whole file" recommendation).

But regarding the question - the code styling seems inconsistent because it is inconsistent.

**Comment by pdurbin** [comment]
Thanks, @pameyer , yes I was going to point out that your pull request #4995 helped explain about our preferred curly brace placement. It's been merged already and can be seen here for now: http://guides.dataverse.org/en/4990-ec2-ansible-scripting/developers/coding-style.html#braces-placement

**Comment by pdurbin** [comment]
@poikilotherm thanks for pull request #5094! I'll move it to code review at "Community Dev" at https://waffle.io/IQSS/dataverse but like you said in the pull request we probably won't want to merge it exactly as is so there's a good chance we'll send it back to you with questions or create our own config based on what you've demonstrated in the pull request.

**Comment by poikilotherm** [comment]
IMHO you should cover as many aspects as possible... The sooner you get a consistent styling and the sooner you get people to document the code they are writting the better. But that's just my 2 cents. :wink:

**Comment by pdurbin** [comment]
@poikilotherm I think what we need is more of a baby step at this point so I just closed your pull request #5094 in favor of pull request #5106 which is smaller in scope and doesn't fail the build. Code review from all is welcome!
