### ISSUE TITLE
Branding - AWS Cloud Name

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#5087]
Old habits die hard. Noticed we have a "dvn" in our AWS URL in instead of "dataverse" when I was downloading a file from production (see screenshot below). Also, we shouldn't have to name our dog "Dog".

Rather than "dvn-cloud" as the bucket name* which displays in these URL's (*reference @matthew-a-dunlap), I'd suggest we stick to our branding recommendations and just call it "dataverse" so that we end up a clearer, more recognizable URL like "dataverse.s3.amazonaws.com".

![screen shot 2018-09-24 at 12 10 36 pm](https://user-images.githubusercontent.com/687227/45965527-b25b7b80-bff6-11e8-8353-0cb5cc64f192.png)

**Comment by pdurbin** [comment]
Makes sense. Does "DVN" mean anything these days other than the name of version 3 (and lower) of the software we now call "Dataverse?" I don't think so.

**Comment by pdurbin** [comment]
The problem with "dataverse.s3.amazonaws.com" is that there are 34 installations of Dataverse so maybe something like "harvard-dataverse.s3.amazonaws.com" would be more appropriate for Harvard Dataverse.
