### ISSUE TITLE
closing more potential resource leaks

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#5098]
In looking through potential resource leaks for TDL, I came up with a few that were not in earlier PRs. I'll make a small PR for them...

**Comment by pameyer** [comment]
bac9dfcbff25c3bc546ffffd5ada1c1c96e6c477 ; ran through API dataset creation / upload (to exercise FileRecordJobListener.java), no leaks judging by the usual `lsof` approach; no problems with functionality..  Same approach on develop c43b4864b; DCM success API calls seem to intermittently leave open a read descriptor for the manifest.
