### ISSUE TITLE
Linked datasets disappear when using move dataverse API

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#5102]
When I use the _move Dataverse_ API to move a dataverse that has a linked dataset into another dataverse, the linked dataset no longer appears in the moved dataverse. I thought this was expected, but it's not. The linked dataset should still appear in the dataverse that was moved.

@scolapasta saw that if you force the dataset to be reindexed (e.g. by publishing a new version of the dataset) the dataset link reappears in the moved dataverse. I can also use the dataset linking API to add the link to the moved dataverse (my terminal shows no errors when doing this or when trying to create a dataset link in a dataverse that already has one).

I saw this on Demo Dataverse, running 4.9.2

**Comment by pdurbin** [comment]
Pull request #5139 looks good (adds reindexing of datasets, as we expected we needed). Moved to QA.
