### ISSUE TITLE
API tests failing as of 201fa1a

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#5107]
As of 201fa1a API tests started failing on phoenix:

![screen shot 2018-09-27 at 12 47 51 pm](https://user-images.githubusercontent.com/21006/46162032-24310080-c255-11e8-8439-0df347a0b33d.png)

See https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-apitest-develop/245/testReport/

**Comment by pameyer** [comment]
6af5c1f7fbc9162bbf47d5837fc6b8d264fab52f ; docker-aio ; Tests run: 76, Failures: 20, Errors: 17, Skipped: 0

**Comment by sekmiller** [comment]
The testMigrateToDOI requires a set-up that can connect to a handle server.  I can set it to ignore that test for now. Not sure why the others would be failing. They are passing for me locally. I will investigate further.

**Comment by sekmiller** [comment]
On a fresh build from dev, all of my tests are passing so for further investigation I need something from the logs for one or more failing tests.

**Comment by pameyer** [comment]
ddc41f58c1cc21449eb5d1f9a69a13be7915ca8d also failing for me; suggesting that this may not be related to that branch.

**Comment by pdurbin** [comment]
@pameyer can you please post which tests are failing for you?

**Comment by pameyer** [comment]
on ddc41f58c
`
[ERROR] Failures: 
[ERROR]   DatasetsIT.testDeleteDatasetWhileFileIngesting:1018 Expected status code <201> doesn't match actual status code <500>.

[ERROR]   FileMetadataIT.testJsonParserWithDirectoryLabels Multiple Failures (2 failures)
        Expected status code <201> doesn't match actual status code <500>.

        Expected status code <200> doesn't match actual status code <404>.

[ERROR]   FilesIT.testAccessFacet:1025->createDatasetGetId:86 Expected status code <201> doesn't match actual status code <500>.

[ERROR]   FilesIT.testAddFileBadJson:235->createDatasetGetId:86 Expected status code <201> doesn't match actual status code <500>.

[ERROR]   FilesIT.testAddTinyFile:873->createDatasetGetId:86 Expected status code <201> doesn't match actual status code <500>.

[ERROR]   FilesIT.testForceReplace:577->createDatasetGetId:86 Expected status code <201> doesn't match actual status code <500>.

[ERROR]   FilesIT.testReplaceFileBadJson:816->createDatasetGetId:86 Expected status code <201> doesn't match actual status code <500>.

[ERROR]   FilesIT.testRestrictAddedFile:982->createDatasetGetId:86 Expected status code <201> doesn't match actual status code <500>.

[ERROR]   FilesIT.testRestrictFile:915->createDatasetGetId:86 Expected status code <201> doesn't match actual status code <500>.

[ERROR]   FilesIT.test_001_AddFileGood:103->createDatasetGetId:86 Expected status code <201> doesn't match actual status code <500>.

[ERROR]   FilesIT.test_005_AddFileBadPermissions:266->createDatasetGetId:86 Expected status code <201> doesn't match actual status code <500>.

[ERROR]   FilesIT.test_006_ReplaceFileGood:299->createDatasetGetId:86 Expected status code <201> doesn't match actual status code <500>.

[ERROR]   FilesIT.test_006_ReplaceFileGoodTabular:458->createDatasetGetId:86 Expected status code <201> doesn't match actual status code <500>.

[ERROR]   FilesIT.test_007_ReplaceFileUnpublishedAndBadIds:645->createDatasetGetId:86 Expected status code <201> doesn't match actual status code <500>.

[ERROR]   FilesIT.test_008_ReplaceFileAlreadyDeleted:732->createDatasetGetId:86 Expected status code <201> doesn't match actual status code <500>.

[ERROR]   InReviewWorkflowIT.testCuratorSendsCommentsToAuthor:72 Expected status code <201> doesn't match actual status code <500>.

[ERROR]   SearchIT.testSearchPermisions:74 Expected status code <201> doesn't match actual status code <500>.

[ERROR]   SwordIT.testCreateAndDeleteDatasetInRoot:370 Expected status code <201> doesn't match actual status code <400>.

[ERROR]   SwordIT.testCreateDatasetPublishDestroy:508 Expected status code <201> doesn't match actual status code <400>.

[ERROR]   SwordIT.testCreateDataverseCreateDatasetUploadFileDownloadFileEditTitle:176 expected:<201> but was:<400>
[ERROR] Errors: 
[ERROR]   AdminIT.testMigrateHDLToDOI:535 » IllegalArgument Cannot get property 'id' on ...
[ERROR]   DatasetsIT.testAddUpdateDatasetViaNativeAPI:144 » IllegalArgument Cannot get p...
[ERROR]   DatasetsIT.testCreateDataset:107 » IllegalArgument Cannot get property 'id' on...
[ERROR]   DatasetsIT.testCreateDeleteDatasetLink:1425 » IllegalArgument Cannot get prope...
[ERROR]   DatasetsIT.testCreatePublishDestroyDataset:265 » IllegalArgument Cannot get pr...
[ERROR]   DatasetsIT.testDatasetLocksApi:1485 » IllegalArgument Cannot get property 'id'...
[ERROR]   DatasetsIT.testExcludeEmail:524 » IllegalArgument Cannot get property 'id' on ...
[ERROR]   DatasetsIT.testExport:404 » IllegalArgument Cannot get property 'id' on null o...
[ERROR]   DatasetsIT.testFileChecksum:941 » IllegalArgument Cannot get property 'id' on ...
[ERROR]   DatasetsIT.testPrivateUrl:679 » IllegalArgument Cannot get property 'id' on nu...
[ERROR]   DatasetsIT.testSequentialNumberAsIdentifierGenerationStyle:629 » IllegalArgument
[ERROR]   FilesIT.testUningestFileViaApi:1132 » IllegalArgument Cannot get property 'id'...
[ERROR]   HarvestingServerIT.testOaiFunctionality:121 » IllegalArgument Cannot get prope...
[ERROR]   SearchIT.testDatasetThumbnail:236 » IllegalArgument Cannot get property 'id' o...
[ERROR]   SearchIT.testIdentifier:607 » IllegalArgument Cannot get property 'id' on null...
[ERROR]   SearchIT.testSearchCitation:178 » IllegalArgument Cannot get property 'id' on ...
[ERROR]   SwordIT.testDeleteFiles:646 » ClassCast com.jayway.restassured.internal.path.x...
[INFO] 
[ERROR] Tests run: 76, Failures: 20, Errors: 17, Skipped: 0
`

After updating certs:
`
[ERROR] Failures: 
[ERROR]   DatasetsIT.testAddUpdateDatasetViaNativeAPI:197 expected:<200> but was:<500>
[ERROR]   DatasetsIT.testCreateDeleteDatasetLink:1437 Expected status code <200> doesn't match actual status code <500>.

[ERROR]   DatasetsIT.testCreatePublishDestroyDataset:287 expected:<200> but was:<500>
[ERROR]   DatasetsIT.testExcludeEmail:546 expected:<200> but was:<500>
[ERROR]   DatasetsIT.testExport:422 expected:<200> but was:<500>
[ERROR]   DatasetsIT.testPrivateUrl:846 expected:<200> but was:<400>
[ERROR]   FilesIT.testForceReplace:609 Expected status code <200> doesn't match actual status code <500>.

[ERROR]   FilesIT.testReplaceFileBadJson:848 Expected status code <200> doesn't match actual status code <500>.

[ERROR]   FilesIT.test_006_ReplaceFileGood:338 Expected status code <200> doesn't match actual status code <500>.

[ERROR]   FilesIT.test_006_ReplaceFileGoodTabular:521 Expected status code <200> doesn't match actual status code <500>.

[ERROR]   FilesIT.test_007_ReplaceFileUnpublishedAndBadIds:698 Expected status code <200> doesn't match actual status code <500>.

[ERROR]   FilesIT.test_008_ReplaceFileAlreadyDeleted:771 Expected status code <200> doesn't match actual status code <500>.

[ERROR]   HarvestingServerIT.testOaiFunctionality:128 expected:<200> but was:<500>
[ERROR]   InReviewWorkflowIT.testCuratorSendsCommentsToAuthor:404 Expected status code <200> doesn't match actual status code <500>.

[ERROR]   SearchIT.testDatasetThumbnail:353 Expected status code <200> doesn't match actual status code <500>.

[ERROR]   SearchIT.testIdentifier:625 JSON path data.total_count doesn't match.
Expected: <0>
  Actual: 1

[ERROR]   SearchIT.testSearchPermisions:131 Expected status code <200> doesn't match actual status code <500>.

[ERROR]   SwordIT.testCreateDatasetPublishDestroy:558 Expected status code <200> doesn't match actual status code <400>.

[ERROR]   SwordIT.testDeleteFiles:692 Expected status code <200> doesn't match actual status code <400>.

[INFO] 
[ERROR] Tests run: 75, Failures: 19, Errors: 0, Skipped: 0
`
These errors appear to be "auth to DataCite" :< will switch back to EZID test credentials.

**Comment by pdurbin** [comment]
@pameyer thanks. The phoenix server uses DataCite, not EZID.

**Comment by pameyer** [comment]
@pdurbin unless something's changed, there aren't generic test credentials available for DataCite.

**Comment by pdurbin** [comment]
@pameyer that's right. Please see "we would not be happy with a standard test account and no password as EZID is doing" at https://github.com/IQSS/dataverse/issues/5024#issuecomment-423610278

**Comment by pdurbin** [comment]
For what it's worth http://status.datacite.org says "major outage" for MDS:

![screen shot 2018-09-27 at 2 30 33 pm](https://user-images.githubusercontent.com/21006/46166871-3d8c7980-c262-11e8-9806-824dacde4ac3.png)

**Comment by pameyer** [comment]
Well, I'll wait with interest for DataCite's suggestions on how to make use of their service from automated provisioning / automated testing.

**Comment by pdurbin** [comment]
@pameyer in the same comment, did you catch "we have an API to create client accounts"?

**Comment by pdurbin** [comment]
After merging pull request #5108 all the tests on the phoenix server are now passing:

![screen shot 2018-09-27 at 2 46 10 pm](https://user-images.githubusercontent.com/21006/46167588-36ff0180-c264-11e8-9558-81679b56ff74.png)
