### ISSUE TITLE
Exclude deaccessioned dataset from being harvested

### ISSUE THREAD

**Issue by philippconzett** [IQSS/dataverse#5112]
We'd like deaccessioned datasets to be excluded from being harvested. I have tried to create an OAI set by setting the Solr field publicationStatus:Deaccessioned in the OAI set query; cf. [this thread](https://groups.google.com/forum/?hl=no#!topic/dataverse-community/hy_GlMdEBwU) in the Dataverse Google Group. Please have a look into this and enable deaccessioned datasets from harvesting. Thanks!

**Comment by jggautier** [comment]
Just noting that this problem might have been fixed since this GitHub issue was written. UVA Dataverse, running v5.9, harvests records from Harvard Dataverse Repository, and @shlake reported today that a recent harvesting run removed datasets that had been deaccessioned since the last time that UVA Dataverse harvested from Harvard Dataverse Repository.

**Comment by pdurbin** [comment]
> Just noting that this problem might have been fixed since this GitHub issue was written.

Nice.

@philippconzett are you able to re-test?

**Comment by philippconzett** [comment]
Sorry for my late reply, @pdurbin. We are currently migrating DataverseNO to the cloud, and during that process we won't be upgrading from the current version we use in production. Once, we've migrated, we'll be able to test. Maybe someone else in the community could test this already now? Thanks!

**Comment by mreekie** [comment]
sizing:
- This one may already be fixed.
- This is going to be tested.
- Sized at a 3. seems ver small to run the test.
- Will be closed if the tests are good without further processing

**Comment by sekmiller** [comment]
The OAIRecordServiceBean filters out those datasets that are fully deaccessioned as of 9/2018.  apparently this has been fixed for a long time. closing.
