### ISSUE TITLE
Open the MoveDataset  to non-superusers. 

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#5115]
This is per request from BARI project. 
They have a dataverse with a complex hierarchy inside. They want to be able to move datasets between dataverses on their own. 

The API/Commands are currently superuser only. 

Should not be hard to implement. Main issue appears to be figuring out the permissions. It can't be as simple as checking that the user owns/can modify the dataverses involved, unfortunately. (we may not want to allow moving drafts, for example; there are also some potential indexing issues with moving a dataverse more complicated).

**Comment by mheppler** [comment]
This functionality was part of the original 4.0 designs, and the front-end code is still in `dataverse.xhtml`.

```
<div class="col-xs-6 form-group" jsf:rendered="#{DataversePage.ownerId != null}">
    <label class="col-sm-3 control-label" for="hostDataverse">
        <span data-toggle="tooltip" data-placement="auto right" class="tooltiplabel text-info" data-original-title="#{bundle['dataverse.host.title']}">
            #{bundle.hostDataverse}
        </span>
    </label>
    <div class="col-sm-9 form-col-container">
        <p class="form-control-static">#{DataversePage.dataverse.getOwner().name}</p>
        <h:inputHidden value="#{DataversePage.ownerId}" id="hostDataverse" />
        <ui:remove><!-- removed for beta -->
        <p:selectOneMenu id="hostDataverse" tabindex="2" value="#{DataversePage.ownerId}" filter="true" filterMatchMode="startsWith" effect="none">
                <f:selectItems value="#{dataverseServiceBean.findAll()}" var="dv" itemLabel="#{dv.name}" itemValue="#{dv.id}"
                        itemDisabled="#{dv eq DataversePage.dataverse or dv.owners.contains(DataversePage.dataverse)}" />
        </p:selectOneMenu>
        </ui:remove>
    </div>
</div>
```

**Comment by scolapasta** [comment]
We'll want to focus on Datasets only first (moving Datasets introduces mass indexing, similar to linked dataverses).

For permissions, we'll need to decide if we want separate permissions for moving a published dataset versus a draft dataset. If we do, we'd have to use dynamic perms; if not, then we'd use the strictness of published for both states. 

Here's what I suggest:

For Drafts:
AddDataset on target Dataverse
EditDataset on dataset
- this is the equivalent of being able to delete the draft and then add a new draft to the target

For published:
(optional) AddDataset on target Dataverse
(optional) EditDataset on dataset
PublishDataset on target Dataverse
PublishDataset on dataset
- this is the equivalent of deaccessioning the dataset then publishing to the target, except that with deaccessioning, the original dataset would still live at the source dataset; also note the optional permissions -in practice, if you have the other permissions, you would have these, but those are not necessarily guaranteed in the permission system, so adding these would feel "safer"

**Comment by oscardssmith** [comment]
Correct me if I'm wrong,  but can't dataset permissions be inherited from the dataverse they are in? To me this seems like it could create a lot of weird issues where for example, you could move a dataset to a location where you could no longer edit it. Is this a problem? I'm not sure it is, but it feels weird.

**Comment by landreev** [comment]
@scolapasta The PR looks good; but it is implemented per your specifications above, and that includes:

"We'll want to focus on Datasets only first (moving Dataverses introduces mass indexing, similar to linked dataverses)."

I'm not sure if this is going to fully satisfy BARI. Looking at their emails (I tried to add you to the cc: there, but they may have left you off some followup messages), they seem to be asking to be able to move dataverses too. 

"It will be a rather substantial migration of data sets and sub-dataverses. I don't believe there is any need to move data files." (per Dan O'Brien)

I'll run it by Nolan et al. If this is indeed super important for them, I'm wondering if we should push the current implementation into a release and/or onto production asap, and then work on adding dataverses - or if we should address it as part of this request.
They do sound like they would prefer to have this feature asap, since they want somebody specific to work on the reshuffling, and this person is going to be leaving the project soon.

**Comment by landreev** [comment]
What about Oscar's question above, about permissions? Does anyone have any comments/ideas? 

As currently implemented, the sole permission we appear to require is to be able to publish the destination dataverse; which is kind of weird, if you think about it - does it really mean that I can steal *anyone's* dataset, and move it into my own dataverse? We should probably check for something on the dataset too - like the edit permission. Am I missing something?

**Comment by pdurbin** [comment]
@landreev good catch. I just pushed d85a7f6 to prevent dataset theft. 😄

**Comment by scolapasta** [comment]
Moving this back to dev for 2 reasons:
1. The permissions used are not what is enumerated above*. If there's reason to do it differently, then please comment here the reasoning. 

(*) if we're not doing dynamic permissions based on draft/versus published, the suggested permission for the Dataset was Publish Dataset

2. There is a way to do annotated permissions on multiple objects. See MoveDataverseCommand. Note that MoveDataverse is currently more strict in that it is only for superusers, which is checked in the execute method, but the annotations should still serve as an example.

**Comment by pdurbin** [comment]
@scolapasta it was extremely helpful that you mentioned using MoveDataverseCommand as a model. I just pushed 47fb045 and I'm moving this back to code review.

**Comment by pdurbin** [comment]
Whoops, after I pushed I realized that a unit test was failing. I'm not sure the case I was testing before is still possible with the new way so I added an `@Ignore` in 7a91717.

**Comment by kcondon** [comment]
- [ ] The required  permissions are not the same as specified by @scolapasta 
Instead they appear to need curator or admin role on both dataset to move and dataverse to move to.

**Comment by pdurbin** [comment]
@kcondon is there any user story you can think of that is a problem with the permissions you tested? For example in an earlier version @landreev pointed out above that a dataset could be "stolen" but I fixed this.

**Comment by pdurbin** [comment]
@kcondon I'm asking because I added a test for the "dataset theft" scenario to make sure it couldn't happen.

**Comment by kcondon** [comment]
@pdurbin We should talk tomorrow at or after standup.
