### ISSUE TITLE
as a developer, I'd like to be able to run integration tests without manual configuration

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#5123]
On ec377d2a4e27424db8815c55ce544deee48fc5e0; docker-aio setupIT does not result in a configuration capable of passing integration tests, due to the removal of EZID test credentials.

Would not be surprised if manual configuration was also required for the recent EC2 scripts (pending update to dataverse-ansible).

**Comment by pdurbin** [comment]
> Would not be surprised if manual configuration was also required for the recent EC2 scripts (pending update to dataverse-ansible).

Yep, now that dataverse-ansible has been upgraded to 4.9.3 I can't even create a dataset. I just opened this issue: https://github.com/IQSS/dataverse-ansible/issues/29
