### ISSUE TITLE
builtinuser login broken when using email address

### ISSUE THREAD

**Issue by matthew-a-dunlap** [IQSS/dataverse#5129]
There is an issue with builtinusers on the login page using their email address. Usernames work fine. Password reset works but if you log out after reset logs you in and try to log in with email again, its still can't find you.

This is due to the removal of information from builinuser. A check needs to be added back to the login flow to check for email as that was lost in transition.

**Comment by pameyer** [comment]
Agree on the PR.  https://github.com/pameyer/dataverse/tree/exp-selenium0 might be something else to revisit / consider for the future.

**Comment by matthew-a-dunlap** [comment]
For future clarity: there was api endpoint code created for exercising email logins via API, in part for testing purposes. That code could only be enabled through a temporary developer code change and was removed as part of #4565 . This code included a test that wasn't exercised but if it had been enabled it would have caught this issue.

To see at https://github.com/IQSS/dataverse/pull/4993/files , look for the retrievingApiTokenViaEmailEnabled boolean and the code it disables.

We should think about how we can better test as part of #4812 #4137 #5068
