### ISSUE TITLE
Analytics/Google Webmaster Tools

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#513]
---

Author Name: **Raman Prasad** (@raprasad)
Original Redmine Issue: 3928, https://redmine.hmdc.harvard.edu/issues/3928
Original Date: 2014-05-05

---

Following up on Phil's email, if not already in, the main site may be registered with:

- Google Webmaster Tools
  https://www.google.com/webmasters/tools/‎

This sign-up includes a web page that allows you to test that your robots.txt file is working properly to block google's indexing. It also provides a way to link back to google analytics

**Comment by eaquigley** [comment]
I registered dataverse-demo today. Passing ticket to QA to be able to close. (@kcondon not sure how you will check this, you will just need to trust that I did this)

**Comment by posixeleni** [comment]
we'll know if the stats are coming into Google Analytics within 24 hours right?

**Comment by eaquigley** [comment]
@posixeleni yup! it is showing now though because we already had google analytics set up. you need to go to the webmaster link above and log in to see it. will check in google analytics and see if it shows there.

**Comment by kcondon** [comment]
Closing
