### ISSUE TITLE
Feature Request: Add more ways to sort from collections page and allow setting default sort method

### ISSUE THREAD

**Issue by mdmADA** [IQSS/dataverse#5131]
At ADA, we are creating brand new datasets on our Dataverse installation as required. But then we are also adding our legacy datasets at the same time. So sorting by "newest" (the current default) isn't ideal since the legacy datasets will appear first.

We would like to see more ways to sort:
- sort by dataset collection date
- sort by most popular (most downloads)
- maybe a few others

And the ability to set the default sort method.

If possible, making it easy(ier) to add new ways to sort would be ideal.

M.

**Comment by pdurbin** [comment]
@mdmADA thanks for opening this issue. Please see some related discussion at #3066

Here's where the sort logic lives: https://github.com/IQSS/dataverse/blob/v4.9.3/src/main/java/edu/harvard/iq/dataverse/search/SearchIncludeFragment.java#L237

**Comment by mdmADA** [comment]
Thanks, Phil.

If I have time at some point, and the issue hasn't been addressed yet, I may look at the code myself and see what can be done and how much effort it would take.

M.

**Comment by pdurbin** [comment]
I told believe anyone is working on this issue. Our current efforts are toward #5053 which is about making a new custom homepage for Harvard Dataverse. More eyes on the code are always welcome! 😄

**Comment by tlchristian** [comment]
Any updates on this?  I have clients still asking for the capability to define the default sort order for their dataverse based on the needs and preferences of their user community.

**Comment by djbrooke** [comment]
Hey @tlchristian, no updates from the IQSS side and we don't currently have plans to work on this in the near future. There may be some community updates, so thanks for checking in!

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
