### ISSUE TITLE
Database upgrade via deployment?

### ISSUE THREAD

**Issue by lmaylein** [IQSS/dataverse#5140]
Is it possible that some of the database updates are done via deployment of the application and not via database-upgrade script?

We want to upgrade from 4.8.6 to 4.9.4. Do we really have to deploy every single version between?
If not, dataverse misses for example the relation alternativepersistentidentifier even if we run the database-upgrade scripts for all versions between 4.8.6 and 4.9.4.

**Comment by pdurbin** [comment]
@lmaylein it's a good idea but I'm not sure how technically feasible it is. Can you please take a look at #4980 and leave a comment there with your thoughts?

**Comment by donsizemore** [comment]
@lmaylein If this were Wordpress (or likely Drupal, my memory is hazy) then yes, the SQL upgrade scripts would handle this. However, Dataverse has so far allowed the Glassfish warfile deployment process to create any tables or additional columns, and relied on the SQL upgrade scripts to alter or remove existing columns.

While in theory you could switch between several point releases which require no modification to the database, it is safest (and yes, more time-consuming) to step through each release. As Phil mentions there is in effort at #4980 to allow direct database upgrades.

**Comment by poikilotherm** [comment]
Hey guys, do I get the right impression that you are suffering from migration hell?

Any chance you might consider using tooling like [Flyway](https://flywaydb.org/) or [Liquibase](https://www.liquibase.org/) to make life easier?

**Comment by pdurbin** [comment]
> Dataverse has so far allowed the Glassfish warfile deployment process to create any tables or additional columns

Slight correction. When we add a column to an existing table we have to add a line like `ALTER TABLE externaltool ADD COLUMN type` or whatever to our SQL update scripts.

Since #4980 is in the current sprint (see https://waffle.io/IQSS/dataverse ), it would be best to take the conversation there.

**Comment by lmaylein** [comment]
Ok. Thanks.
