### ISSUE TITLE
Released and unchanged datasets appear as new drafts when upgrading from 4.8.6 to 4.9.4

### ISSUE THREAD

**Issue by lmaylein** [IQSS/dataverse#5142]
When upgrading form 4.8.6 to 4.9.4 the number of the datasets in our instance is increased.
There are additional draft versions for already publicated (and unchanged) datasets.

**Comment by pdurbin** [comment]
@lmaylein that doesn't sound good. Are you basing this on what you're seeing in the database or Solr?

**Comment by lmaylein** [comment]
First: It was only a testmigration :-)
Here are some Screenshots:

4.8.6:

![dataset_count_4 8 6](https://user-images.githubusercontent.com/7468155/46532171-1fe19480-c8a0-11e8-9484-c11b4f8cccdf.png)

4.9.4:

![dataset_count_4 9 4](https://user-images.githubusercontent.com/7468155/46532199-2c65ed00-c8a0-11e8-9366-733c2d275b38.png)

**Comment by lmaylein** [comment]
Some of the additinal draft versions.
The description "dummy" was entered, when the datasets were created (several weeks ago).

![draft_datasets](https://user-images.githubusercontent.com/7468155/46532360-b746e780-c8a0-11e8-891e-10f939145d94.png)

**Comment by pdurbin** [comment]
> It was only a testmigration

Phew. I'm already recovering nicely from my heart attack.

Could it be that the draft datasets have been around for a long time but never indexed? Perhaps you ran an "index all" as part of your migration process? I long time ago I wrote some code to "diff" what's in Solr vs the database but it's buggy and we haven't documented it. You can find references to it in #4205.

**Comment by lmaylein** [comment]
I've reindexed our 4.8.6 (productive) dataverse now. The number number of dataset is the same as before. The nine additional draft versions don't appear in 4.8.6.

If I copy the dataset links generated by 4.9.4 to our official/productive domain
(e.g. https://heidata.uni-heidelberg.de/dataset.xhtml?persistentId=doi:10.11588/data/VGWRB7&version=DRAFT) I get:

> Info – The "DRAFT" version was not found. This is version "1.0". 

I'll check your diff script.

**Comment by lmaylein** [comment]
Ok. After fixing the problem described in #5141 ...

The URL
`https://<new_ip_for_dataverse_4.9.4>/dataset.xhtml?persistentId=doi:10.11588/data/9UXUB0&version=DRAFT`

shows the same result, when clicking on the "ghost draft":

> Info – The "DRAFT" version was not found. This is version "1.0".

**Comment by lmaylein** [comment]
Additional information:

Affected are the last nine datasets which have been release (in 4.8.6).

**Comment by lmaylein** [comment]
Can I further support the debugging of this problem?
Do you need any select results from the database?

In the solr result cited, both datasets (draft and release) have the same datasetVersionID. Maybe a problem with a join while indexing?

Which, however, speaks aginst it are the old metadata (description "Dummy") which are displayed in the search result for the drafts and which certainly reflects a state before the first release.

**Comment by pdurbin** [comment]
@lmaylein hi, all the detail here is much appreciated but can you please email support@dataverse.org to open a support ticket? If you've done this already, you can just mention the ticket number here. Thanks!

**Comment by lmaylein** [comment]
Mea culpa!

If I deploy every version between 4.8.6 and 4.9.4 
sequentially, it looks good.

**Comment by pdurbin** [comment]
@lmaylein no problem. While upgrades are on your mind, you might want to leave a comment on #4980 which is related.
