### ISSUE TITLE
expand logging for draft edits

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#5145]
Short version - change log for draft datasets could use some additional information.

Longer version - `UpdateDatasetVersionCommand` (and possibly `CreateDatasetVersionCommand`) provide information about which dataset version was changed, and who changed it - but there doesn't appear to be accessible information about what was changed.  Not sure if it makes more sense to add this to the action log record `info` field, or add a new logger / log file.

**Comment by pdurbin** [comment]
Related: #1002

**Comment by pameyer** [comment]
@pdurbin Thanks - that is closely related (aka #1002 would eliminate the need for this).

**Comment by pameyer** [comment]
It looks like special characters in metadata fields get mangled in the logs (eg - `Galápagos` is logged as `Gal?pagos`).  

Any ideas if this is a config issue or a code issue?

**Comment by pameyer** [comment]
Thanks to @sekmiller for pointing out that special characters didn't get mangled on his system, so that is a config issue.

**Comment by pameyer** [comment]
In my hands, 2e1d6073f1003a55689d6d9436d50b9568368622 is still losing newline characters in the edit log.

**Comment by djbrooke** [comment]
Moving back to team dev based on @pameyer's most recent comment.

**Comment by sekmiller** [comment]
@pameyer, can you attach a copy of the log file that your machine is producing?
 thanks!

**Comment by sekmiller** [comment]
I was able to get the log to use the raw version of the metadata.

**Comment by pameyer** [comment]
@sekmiller Thanks!

**Comment by pameyer** [comment]
For future reference (aka - it didn't make it into the issue from when we initially talked it over): this code enables logging, and there isn't currently a setting to disable the creation of edit logs.  This is something that might get revisited in the future however.
