### ISSUE TITLE
Enable facet UI for Time Period Covered

### ISSUE THREAD

**Issue by philippconzett** [IQSS/dataverse#5150]
This issue may be related to #70.

Dataverse offers faceting for several date fields. However, faceting does not work for
Time Period Covered: timePeriodCoveredStart + timePeriodCoveredEnd (Citation Metadata)

It would be nice to make this field facetable just like this field in the Astronomy Metadata:
coverage.Temporal: coverage.Temporal.StartTime + coverage.Temporal.StopTime

Thanks!
Philipp

**Comment by pdurbin** [comment]
@philippconzett hi, I just wanted to confirm that you aren't being affected by the bug in #4906 which was fixed in Dataverse 4.9.3.

**Comment by philippconzett** [comment]
@pdurbin hi, I we have just upgraded to 4.9.4, and I have tested this again, but there is no facet _Time Period Covered_ popping up.

**Comment by pdurbin** [comment]
Thanks. I just took a quick look at scripts/api/data/metadatablocks/citation.tsv and "facetable" is already set to "true" so I'm not quite sure what's going on. Here's a screenshot:

![screen shot 2018-10-09 at 9 32 47 am](https://user-images.githubusercontent.com/21006/46672820-68ea5f00-cba6-11e8-9a04-f3dece3cc11c.png)

This would need some more investigation.

**Comment by philippconzett** [comment]
@pdurbin, hmm, I'm not sure, maybe enabling faceting of the field in row 62 helps?

**Comment by pdurbin** [comment]
@philippconzett I'm not sure if it would help or not. You are welcome to try it. 😄

**Comment by philippconzett** [comment]
@pdurbin I'll ask our system admin. In the meantime, could you please send me a screenshot of the configuration of the three fields for coverage.Temporal?

**Comment by pdurbin** [comment]
@philippconzett sure, here you go:

![screen shot 2018-10-09 at 10 14 19 am](https://user-images.githubusercontent.com/21006/46675303-1e6be100-cbac-11e8-8bf6-02e87e3eb2a8.png)

You can find these TSV files at https://github.com/IQSS/dataverse/tree/v4.9.4/scripts/api/data/metadatablocks and we recently documented how they work (#3168): http://guides.dataverse.org/en/4.9.4/admin/metadatacustomization.html

**Comment by philippconzett** [comment]
@pdurbin  Thanks! I just tested this again, but this time in our production repo, and it works:
![image](https://user-images.githubusercontent.com/21955790/46676542-095d7500-cbe1-11e8-9d66-e601769b007c.png)

I just see here the chronological sort issue popping up again. I commented this in #4977

**Comment by pdurbin** [comment]
@philippconzett great! So it's working? Do you want to close this issue?

**Comment by philippconzett** [comment]
Yes, please. Thanks!
