### ISSUE TITLE
Other  author identifier schemes

### ISSUE THREAD

**Issue by lmaylein** [IQSS/dataverse#5151]
Is it possible to add further identifier schemes for authors?
For example:
 * VIAF (http://viaf.org/) or
 * GND (http://www.dnb.de/EN/Standardisierung/GND/gnd.html, mainly interesting for Germans, but widely used here (for example the German Wikipedia also uses the GND))

**Comment by lmaylein** [comment]
If I get it right, I could change citation.tsv and load this file via API in our local dataverse installation.
Or would it be better to add these two identifier schemes to the offical distribution and make a pull request?

**Comment by pdurbin** [comment]
@lmaylein a pull request would be better, I believe.

I wonder if @Venki18 is still interested in #3169.
