### ISSUE TITLE
Archivematica Integration 

### ISSUE THREAD

**Issue by amberleahey** [IQSS/dataverse#5152]
Placeholder for community dev tracking

Dataverse-Archivematica integration project information: https://wiki.archivematica.org/Dataverse 

Basic functionality: Users can configure local Archivematica instance to connect to any Dataverse instance and make Data Access API calls to select and retrieve Dataverse files (data + metadata) for preservation processing + METS metadata + PREMIS metadata + AIP package creation for long-term preservation. Archivematica can be confirgured to store Dataverse AIPs somewhere (local or shared) for reuse later. 

Related open Dataverse issues for this project: [#5081 ](https://github.com/IQSS/dataverse/issues/5081) most recent issue posted, [#2734](https://github.com/IQSS/dataverse/issues/2734) , [#2720 ](https://github.com/IQSS/dataverse/issues/2720), [#2609](https://github.com/IQSS/dataverse/issues/2609) can be closed since Archivematica now does this for pres community?, [#1346](https://github.com/IQSS/dataverse/issues/1346) not sure if this is still needed since Data Access API provides bundles, also not aware of need for SWORD for export anymore?

Generally, the integration work has been independent from DV development (aside from above) since it is meant to be more so a development of Archivematica tool to support research data preservation and the DV repository type. 

More information about the public release of Archivematica to be announced in late October 2018.

**Comment by pdurbin** [comment]
@amberleahey thanks for creating this issue and for linking to the various open issues! I moved this over to "Community Dev" and assigned it to you.

When you're ready to start promoting this integration, how do you feel about making a pull request to add Archivematica to this list of integrations in the Admin Guide? http://guides.dataverse.org/en/4.9.4/admin/integrations.html is the current list and comes from https://github.com/IQSS/dataverse/blob/v4.9.4/doc/sphinx-guides/source/admin/integrations.rst

**Comment by amberleahey** [comment]
will do! :)

**Comment by meghangoodchild** [comment]
Hello @pdurbin! I'm helping Amber to add details about the integration to the Admin Guide. Could you add me so that I can make the PR?

**Comment by pdurbin** [comment]
@meghangoodchild sure! I just invited you to join https://github.com/orgs/IQSS/teams/dataverse-readonly/members but either way you can make a pull request. The easiest starting point is probably to navigate to https://github.com/IQSS/dataverse/blob/develop/doc/sphinx-guides/source/admin/integrations.rst and then click the "pencil" icon to edit the page right in your browser. Maybe a new "Getting Data Out" section would be appropriate? Whatever you feel is best. 😄 

Over at https://groups.google.com/d/msg/dataverse-community/liT6DmUK8hI/uQQqz48QBQAJ I mentioned a link I found at https://www.archivematica.org/en/docs/archivematica-1.8/user-manual/transfer/dataverse/ which seemed like a good write up to link to.

**Comment by pdurbin** [comment]
Pull request #5411 looks good to me (doc change only) and I moved this issue to QA at https://waffle.io/IQSS/dataverse
