### ISSUE TITLE
Docs: Review API and Options functionality not listed in main api or config sections to see whether should be added to reference-style list.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#5155]
There are several places in the guides where api endpoints and jvm options are listed in topics but not in the configuration section or the api guides:

S3 jvm options
Shibboleth
Admin
Big Data
Other?

This ticket is to review what is there to see if this is intentional and whether it makes sense to consolidate into a reference section in addition to where the currently live.

**Comment by pdurbin** [comment]
@kcondon in pull request #6107 I tried to address this in a new "Lists of Dataverse APIs" section that looks like this:

<img width="822" alt="Screen Shot 2019-08-20 at 5 46 55 PM" src="https://user-images.githubusercontent.com/21006/63387078-86658900-c372-11e9-8868-a73df6153dd0.png">

Does this help?

I also added a new FAQ page and the question "Where is the Comprehensive List of All API Functionality?" that references #5794 and the fact that if we upgrade to Payara (#4172) we can get a complete list of API commands in Swagger/OpenAPI format. Here's how that question and answer look:

<img width="745" alt="Screen Shot 2019-08-20 at 5 49 57 PM" src="https://user-images.githubusercontent.com/21006/63387240-f247f180-c372-11e9-9a07-607b6d890242.png">

I also mentioned the Payara thing in my API talk the other day. Here are my notes from that talk: https://github.com/IQSS/dataverse/issues/6086#issuecomment-521431188

**Comment by kcondon** [comment]
@pdurbin Seems reasonable. Minor quibble, I might adjust the SWORD description from saying a standards based approach to saying using the SWORD standard. One seems broader and more weighty when actually the native api is more flexible, more maintained, and currently more useful.

**Comment by poikilotherm** [comment]
Today I had to lookup some stuff in the API docs and it bothered me that it's sometime complicated to parse the information, find out that an endpoint is missing from the docs and it would be nice to have more examples.

Looking at #5794 and this issue, maybe one day we can do something like one of these:
- Go for nicer inline examples via https://github.com/collective/sphinxcontrib-httpexample
    ![grafik](https://user-images.githubusercontent.com/5468333/153601085-16e841c2-965e-4660-9ff0-306d535a88b4.png)

- Go for fancy! 
    1. Document API endpoints within the code using [Swagger Core](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Getting-started) and create an extensive OpenAPI definition at buildtime
    2. Use https://slatedocs.github.io/slate/#introduction to create VERY nice API docs. Not sure, but I guess Zenodo is using it, too... https://developers.zenodo.org

**Comment by poikilotherm** [comment]
Today I learned about https://github.com/SAP/swagger-plugin-for-sphinx to include Swagger HTML pages within your Sphinx build.
