### ISSUE TITLE
can't publish using the EC2 script

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#5162]
DataCite requires credentials to publish test DOIs. The dataverse-ansible role now sets the DataCite baseurl, username and password in domain.xml, and it would be nice for developers to be able to set this in ec2-create-instance.sh alongside the desired branch and repo.

These variables might be specified in a conf file such as `~/.dataverse/dataverserc` or `~/.dataverse/ec2.env` so that ec2-create-instance.sh can simply test for their existence and pass them along to the ansible-playbook as extra-vars. I'd rather not expect them from .bashrc or .bash_profile for the sake of organizational sharing.

I volunteered to do this, and will coordinate with @pdurbin.

**Comment by pdurbin** [comment]
@donsizemore thanks for creating this issue! As I mentioned at https://github.com/IQSS/dataverse-ansible/issues/29#issuecomment-428579810 I tested a new version of ec2-create-instance.sh and was able to publish but the task now is to avoid doing hacks I added such as hard coding passwords into the script like this:

DATAVERSE_DOI_USERNAME='REDACTED'

Instead, as you've described well, we need to store passwords somewhere outside of the script itself. I like your "env" file idea.

**Comment by pdurbin** [comment]
@donsizemore thanks for working on this and pointing out https://github.com/IQSS/dataverse/compare/develop...OdumInstitute:5162_cant_publish_using_EC2_script in IRC! Looks like a great start. If you want, go ahead and make a pull request and I can mess with docs or whatever. Thanks! Thanks also for all the work on the dataverse-ansible side.
