### ISSUE TITLE
resource leaks in S3AccessIO calls

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#5165]
If I'm following things correctly, a call to something like isAuxObjectCached() (e.g. from ImageThumbConverter.isThumbnailCached()) is calling open() (no parameters, defaults to read mode), which for the S3AccessIO class goes ahead and opens an InputStream for reading. Since this call and others like it never access the InputStream, it looks to me like that stream is left open. A quick scan shows several methods that start with open() in the S3AccessIO class. I didn't see a similar problem in the File class and haven't checked Swift. 
A fix may be as simple as not opening the stream until the getInputStream() call is made...

**Comment by qqmyers** [comment]
@kcondon - I didn't look for the getReadChannel() method after overriding the getChannel() method. That one is also now overridden to make sure the channel is created.

**Comment by kcondon** [comment]
@qqmyers Yep, that did it, thanks!
