### ISSUE TITLE
Glassfish systemd file doesn't work as-is (glassfish.service)

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#5168]
@otheus is reporting a problem with the Glassfish systemd file we provide at http://guides.dataverse.org/en/4.9.4/installation/prerequisites.html#launching-glassfish-on-system-boot and has made a pull request at #5167 (thanks!)

Here is the bug report from the pull request:

> systemctl does not accept the file as-is. There is one major error, and second, the LANG setting should be enforce, per documentation.
> 
> Note: systemctl does only allows # comments that are on their own line.

I'm moving this issue to "Code Review" at https://waffle.io/IQSS/dataverse

**Comment by donsizemore** [comment]
looks good to me. i added the comment after the fact at the suggestion of more complete documentation.

**Comment by pdurbin** [comment]
Looks fine to me too but I've barely used systemd. I wanted to point out that just now @otheus opened #5175 which is related.
