### ISSUE TITLE
installer: fails to restart glassfish if it was previously started by systemd

### ISSUE THREAD

**Issue by otheus** [IQSS/dataverse#5175]
When running the `dvinstall/install` script on a system which is configured to use systemd to manage the glassfish service, the script will stop glassfish, but be unable to restart it.

```
Updates done. Restarting...
```

Eventually, that command will TIMEOUT, and abort the installation process.

## Work-arounds

1.  In another terminal window, I restarted the glassfish process with `systemctl start glassfish`
2.  Prior to running setup, I used `systemctl stop glassfish` so that asadmin handled stopping/starting completely. After setup, it was important to `asadmin stop-domain` and start with systemctl.

**Comment by pdurbin** [comment]
@otheus thanks for opening this issue and for all the chatter at http://irclog.iq.harvard.edu/dataverse/2018-10-12

I just wanted to point out that problem above is as of 4.9.4 with the installer coming from the dvinstall.zip for that release.

Related: #5176 #5177

**Comment by pdurbin** [comment]
I just noticed "start glassfish with asadmin so subsequent Ansible-initiated restarts succeed on RedHat/CentOS" at https://github.com/IQSS/dataverse-ansible/blob/064a8fa47b5f5283446191ab7bb1dbdbbbeef774/tasks/dataverse-glassfish.yml#L72 but I'm not sure if it's related or not. Sorry for the noise if it's unrelated! 😄

**Comment by pdurbin** [comment]
@otheus hi, is this still a problem for you? Are you still interested in a fix?
