### ISSUE TITLE
installer: still trying to populate the new db. with reference data, even in --skip_db_setup mode

### ISSUE THREAD

**Issue by otheus** [IQSS/dataverse#5176]
If `dvinstall/install` script fails before completion, re-running the script will stop and abort when trying to re-create the postgresql database.

To work-around this problem, one can stop glassfish, drop the database, and re-run from scratch, *or* one can use `--skip_db_setup`. This latter method will fail:

```
EXECUTING PSQL COMMAND: /psql -h 127.0.0.1 -p 5432 -U dvnapp -d dvndb -f reference_data.sql
exec "/psql": No such file or directory at ./install line 1545.
```

This is due to the fact that the `--skip_db_setup` option prevents the `$psql_exec_path` variable from being ever set. But a subsequent step relies on this variable.

**Comment by pdurbin** [comment]
@otheus thanks for opening this issue and for all the chatter at http://irclog.iq.harvard.edu/dataverse/2018-10-12

I just wanted to point out that problem above is as of 4.9.4 with the installer coming from the dvinstall.zip for that release.

Related: #5175 #5177

**Comment by landreev** [comment]
Hi, 
Sorry, this fell through the cracks - we had conferences and other distractions... 
Trying to read your original report - I'm a little confused by the following: 

> ... *or* one can use `--skip_db_setup`. This latter method will fail:
```
EXECUTING PSQL COMMAND: /psql -h 127.0.0.1 -p 5432 -U dvnapp -d dvndb -f reference_data.sql
exec "/psql": No such file or directory at ./install line 1545.
```
This is due to the fact that the `--skip_db_setup` option prevents the `$psql_exec_path` variable from being ever set. 

Why is the line 1545 (in the setup_postgres() method) being executed at all, if the installer was run with --skip_db_setup? I mean, the whole point is to skip it... what am I missing?

**Comment by landreev** [comment]
OK, I see what's going on; I was looking at the installer code in the dev. branch; and you must have been using the version from the latest release. 

Yes, we are still trying to populate the new db. with reference data, even in --skip_db_setup mode.  And that's where it's failing. We'll fix it. Thanks for the report.

**Comment by pdurbin** [comment]
I just retitled this issue.

In the time since this issue was last commented on, @landreev rewrote the installer from Perl in Python mostly in this PR:

- #6484

I assume the bug is still in the Perl version but I haven't looked at either version to confirm this.

**Comment by otheus** [comment]
I have no interest in following up here. TBMI, we are no longer using this project.

**Comment by pdurbin** [comment]
@otheus thanks for following up. I really appreciate it! Have a nice weekend!
