### ISSUE TITLE
Restricting a file on Dataset Create fails

### ISSUE THREAD

**Issue by sekmiller** [IQSS/dataverse#5190]
Looks like it is related to Dual Mode where I put in an extra test for dataset locks. That test throws an exception when the dataset hasn't been saved. (The dataset is new.)

**Comment by pdurbin** [comment]
Related: #3896 #4110

**Comment by pdurbin** [comment]
@sekmiller does pull request #5208 fix #3896 or #4110 as well?

**Comment by sekmiller** [comment]
It does fix 3896. I didn't test 4110. Will take a look.
