### ISSUE TITLE
Docs: Example IP Group json file does not work as is, works if ipv6 portion is removed.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#5196]
Not sure whether this is a doc bug or functional bug but the sample ipgroups json file in docs doesn't work unless you remove the ipv6 portion.

http://guides.dataverse.org/en/4.9.4/admin/ip-groups.html#creating-an-ip-group

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
