### ISSUE TITLE
Docs: Sample create dataverse json file fails with parsing error.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#5198]
The sample json file provided in api guide fails with {"status":"ERROR","message":"Error parsing Json: Invalid token=EOF at (line no=1, column no=0, offset=-1). Expected tokens are: [CURLYOPEN, SQUAREOPEN]"}

http://guides.dataverse.org/en/4.9.4/api/native-api.html#create-a-dataverse

**Comment by pdurbin** [comment]
Related: #3533

**Comment by pdurbin** [comment]
Related: #5865
