### ISSUE TITLE
User Session Expiration - Automatic Log Out

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#52]
---

Author Name: **Elda Sotiri** (@esotiri)
Original Redmine Issue: 3459, https://redmine.hmdc.harvard.edu/issues/3459
Original Date: 2014-01-29
Original Assignee: Mike Heppler

---

Tested on build DVN_4_0-108

Home page > click Login > click on the user name to go to dataverseuser page> click log out > leaves user account information displayed and "add data" and "edit account" commands available.

**Comment by kcondon** [comment]
This is not likely to be an issue with longer session timeouts. Closing unless a use case is found.
