### ISSUE TITLE
Dataset : deposit date and the displayed date of a dataset

### ISSUE THREAD

**Issue by rmo-cdsp** [IQSS/dataverse#5206]
Hello,

I have a question about dataset "date". Here is a screen shot of a dataset I created:

![1539782870-screenshot-from-2018-10-17-15-23-43](https://user-images.githubusercontent.com/687227/47091833-a7f66100-d1f3-11e8-8ce3-4c16d9358049.png)

You can see a date, Oct 17, 2018 . To me, it's the deposit date. I want to change it, so I edit the field "Deposit Date" of the dataset:

![1539783197-screenshot-from-2018-10-17-15-32-36](https://user-images.githubusercontent.com/687227/47091839-adec4200-d1f3-11e8-8ea0-99f719b1aaba.png)

But the date of the first picture doesn't change. So, if this date isn't the deposit date of the dataset, what is it ? Or is it related to the fact that it is a draft dataset, and that the deposit date is not updated ?

**Comment by mheppler** [comment]
I dropped the screenshots right into the comment above. Will review in more detail and come back with some feedback. Sounds like this is related to _Updated Dates: Search Results Cards + Versioning #2607_.

**Comment by pdurbin** [comment]
@rmo-cdsp hi! Did my explanation (from a while ago!) help? Are you all set? Are you still interested in some kind of change or fix or docs?
