### ISSUE TITLE
Long (e.g. SHA-512) fixity checksums are too long for display

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#5210]
File checksums are shown in multiple places and long ones (sha-512 and sha-256 in some places) will either be cut-off or run past the edge of their container. They also clutter the dataset file table. I'll submit a PR that adds wrapping where needed and replaces the main file table display checksums with small buttons showing the algorithm name in a small button that will copy the checksum value to the clipboard (with a tooltip that shows the value as well).

**Comment by qqmyers** [comment]
In most places, this PR just wraps the long checksum, e.g. 
![image](https://user-images.githubusercontent.com/6731983/47116432-aea2c980-d22f-11e8-8341-c4c2416a477b.png)

On the main dataset display, it uses the copy clipboard javascript that was already in Dataverse to make a simple button:

![image](https://user-images.githubusercontent.com/6731983/47116561-f9244600-d22f-11e8-998e-999d175a2606.png)

The pop-up tooltip still shows the checksum value and clicking the button copies the value to the clipboard.

Other displays that are updated by the style changes include the file page, the edit files tables, the version difference display, and the replace file display.

**Comment by mheppler** [comment]
Whoa. That's certainly an unruly text string that taxes the limits of our file table UI. I'm going to take a look here at the UI component used and consider some options. With the proximity to the file tag UI label components (e.g. "Documentation" in the second screenshot), I am concerned that it is so visually similar to it's neighbor.

**Comment by qqmyers** [comment]
Since no one is going to look at that and say 'Yeah, looks right' it might be something that could always be hidden by some sort of copy button...

**Comment by oscardssmith** [comment]
This talk is probably worth looking into. It's from defcon and is about making it easier for users to do visual checks of hash functions by displaying them as sentences or other easier to memorize chunks. https://youtu.be/xneBjc8z0DE?t=2469

**Comment by mheppler** [comment]
Just to update on the progress: got this branch built locally, and plan to iterate on some UI tweaks, as well as demo this week for some team members to get their feedback.

**Comment by djbrooke** [comment]
Hey @qqmyers - this is definitely an issue, but instead of taking this PR through our regular process and making this small change, this is something that we'd like to consider as part of the larger file and redesign effort in #3404. I'm going to close out the PR with a note that we won't merge this to the develop branch right now.

**Comment by djbrooke** [comment]
Closing out this unique issue as we'll be addressing this as part of the dataset redesign in #3404.

**Comment by pdurbin** [comment]
@qqmyers I just wanted to let you know that I gave your solution a shout out yesterday at https://groups.google.com/d/msg/dataverse-community/btZ3XSryJdM/ofDUbkzcDQAJ 😄 

I had forgotten about this issue or I would have linked to it. 😄
