### ISSUE TITLE
Open Content License for Guides

### ISSUE THREAD

**Issue by Duhem123** [IQSS/dataverse#5216]
Re-use of material on [http://guides.dataverse.org/en/latest/](http://guides.dataverse.org/en/latest/) could be facilitated by publishing it under an open content license, e.g. CC 0 or CC BY. 
Thanks for considering and best regards, Jochen

**Comment by pdurbin** [comment]
@Duhem123 which license do you recommend? Can you give an example or two of other open source projects that use an open content license for their documentation? Thanks!

**Comment by Duhem123** [comment]
Dear @pdurbin, I would go for Creative Commons. With respect to uncomplicated re-use, I think CC 0 would be optimal. CC BY is of course also an option. For example, the documentations of [DSPACE](https://wiki.lyrasis.org/display/DSDOC7x) and [InvenioRDM](https://inveniordm.docs.cern.ch/install/) are also available under CC BY.

**Comment by pdurbin** [comment]
@Duhem123 we're fans of CC0 (it's been the default license in Dataverse since 4.0) so that makes sense to me. Thanks!

**Comment by pdurbin** [comment]
@Duhem123 are you interested in making a pull request to show where you think the license should go? I'm guessing the footer?

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.

**Comment by DS-INRA** [comment]
@pdurbin I haven't followed the work of the group but maybe this is still relevant for the documentation group :)

**Comment by pdurbin** [comment]
Yes, thanks. I started a thread here about it: https://dataverse.zulipchat.com/#narrow/stream/446770-docs/topic/open.20content.20license.20for.20guides/near/463808377
