### ISSUE TITLE
Support arbitrary filetypes in index

### ISSUE THREAD

**Issue by matthew-a-dunlap** [IQSS/dataverse#5218]
If Dataverse hits a filetype that is not in its known list (MimeTypeFacets), it throws an exception on indexing. This causes the filetype to not be indexed (the file itself still indexed).

There was already code in place to catch this exception when there was no match, but that exception was being caught by a _different_ piece of code before it could be used to add a filetype.

I noticed this updating the index #5053. Note that in the fix I made sure that the exception is still being caught by the lower level code for all cases other than filetype indexing.

**Comment by matthew-a-dunlap** [comment]
Here is how my image results changed (268 files).

Previous:
![screen shot 2018-10-19 at 3 38 01 pm](https://user-images.githubusercontent.com/8901015/47240059-23ebd700-d3b5-11e8-8bdb-85630f5a7d70.png)

After fix:
![screen shot 2018-10-19 at 3 42 04 pm](https://user-images.githubusercontent.com/8901015/47240176-8fce3f80-d3b5-11e8-8789-af6fd2c0dde4.png)

**Comment by pdurbin** [comment]
I just left a review on pull request #5219 with some discussion points.
