### ISSUE TITLE
Slow and duplicate DataCite registration 

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#5220]
I was just looking through the DataCite code (hoping to borrow it for another project) and noticed a) that the code creates/closes an httpClient for each call, which repeats all of the ssl setup, etc., and b) that, at least for a 'normal' dataset, the publicizeExternalIdentifier() call is made twice. 
For a) it looks like it is a reasonable practice to just have a singleton httpClient for DataCite calls. For b) I'm not sure how/when the two calls were introduced. One is now inside an
```
if (!datasetExternallyReleased) 
```
while the second is inside

```
        if ( theDataset.getLatestVersion().getVersionState() != RELEASED ) {
            // some imported datasets may already be released.
            if (!datasetExternallyReleased){
```
My guess is that the former should removed, but I wonder if the datasetExternallyReleased flag was needed here because the first copy above was there. (In the externally released case, is the latest version RELEASED?).

I'll submit a PR...

**Comment by pameyer** [comment]
@qqmyers Have you tested the import API with this branch?  It might be possible that some of this is related to importing a dataset with an existing PID.

**Comment by qqmyers** [comment]
@pameyer - I haven't. Both copies appear to have been there for a while and the check if(!datasetExternallyReleased) was applied to both copies, presumably as part of supporting the import with existing PIDs...

**Comment by matthew-a-dunlap** [comment]
For testing this branch we should ensure our test cases for publishing with datacite still work. It looks like `publicizeExternalIdentifier` was being called twice accidentally (one has been removed in this branch), but its possible that removal has opened up some case. To me it looks like the removed call was publishing released datasets when it shouldn't.

**Comment by qqmyers** [comment]
@matthew-a-dunlap  - I'm not sure there is/was a case where the publish command was getting triggered on released datasets, unless it was the externally released case. So a) hopefully it was just publishing twice on drafts, and b) a question: was the datasetExternallyReleased flag needed because the first call was publishing them even though they were 'released' / should datasetExternallyReleased==true datasets also be released when they hit this code and therefore the second and now only call will skip them and would do so without the extra flag? (hopefully that makes sense). I don't know enough about the import code to know if that's the case...
