### ISSUE TITLE
Login page is not displayed in selected language

### ISSUE THREAD

**Issue by tcoupin** [IQSS/dataverse#5225]
On this screenshot, you can see that the selected language is english. All is in english, except username and password labels.
![image](https://user-images.githubusercontent.com/7457386/47350613-87784c00-d6b6-11e8-9bc3-ef752e27adc3.png)

**Comment by pdurbin** [comment]
@tcoupin hi! Thanks for the bug report. Are you on 2bac293 which is the latest commit and includes your fix for #5090?

**Comment by tcoupin** [comment]
@pdurbin yes

**Comment by pdurbin** [comment]
@tcoupin thanks. Likewise, you can get mostly French with English for "username" and "password" like this:

<img width="1206" alt="screen shot 2018-10-23 at 10 01 24 am" src="https://user-images.githubusercontent.com/21006/47365965-ae308580-d6aa-11e8-9eae-68dae9815f6a.png">

This is the curl command I used:

`curl http://localhost:8080/api/admin/settings/:Languages -X PUT -d '[{  "locale":"en", "title":"English"},  {  "locale":"fr", "title":"Français"}]'`

Are you interested in making a pull request?

**Comment by tcoupin** [comment]
@pdurbin  I use the same curl command.

I don't have any fix for now. If I found one, I will make a pull request.
