### ISSUE TITLE
Session Initiation Issues with Shibboleth

### ISSUE THREAD

**Issue by Mahsanas** [IQSS/dataverse#5237]
Hi,

We see a "Shibsp Configuration Exception" error the first time we go to our dataverse website.
This is the process that leads to the error: 
1- The user opens a browser tab and goes to our Dataverse instance ex: "http://ourdataverse.com"
2- If the user is not logged in already and no active session exists in the browser for the dataverse, then, the user is redirected to this address (https://ourdataverse.com/shib.xhtml?redirectPage=/) and this error pops up:  

shibsp::ConfigurationException
The system encountered an error at Thu Oct 25 15:41:30 2018
To report this problem, please contact the site administrator at root@localhost.
Please include the following message in any email:
shibsp::ConfigurationException at (https://ourdataverse.com/shib.xhtml)
None of the configured SessionInitiators handled the request.

3- if the user tries the link (http:/ourdataverse.com) again, the error does not show and the site loads. 
I think this is because a Shib session is not automatically instantiated (which should not unless you login) but is expected. I think if we figure out what causes the redirection to happen, we find the source of the problem.

I would like to emphasize that, this is prior to user login step. It is basically the first step a user takes to visit our data verse instance.

I did some tracing and it seems the issue is raised from the ssl.conf tags for Shibboleth.
<Location /shib.xhtml>
  AuthType shibboleth
  ShibRequestSetting requireSession 1
  require valid-user
</Location>

It seems the tags require a shibboleth session though non exists. So maybe (?) I would need to know how I can configure sp to initialize a session if non exists.

Thanks

**Comment by pdurbin** [comment]
@Mahsanas I'm seeing both "http" and "https" above. What if you redirect all http traffic to https? Please see http://guides.dataverse.org/en/4.9.4/installation/shibboleth.html#enforce-https

**Comment by Mahsanas** [comment]
@pdurbin The https redirect is in place. Once the user goes to http://ourdataverse.com, it is redirected to https automatically. The reason you see http:// is that I assumed the user uses http to go to our data verse web app.

**Comment by pdurbin** [comment]
@Mahsanas ok, thanks. The https redirect is in place at https://demo.dataverse.org also. Can you reproduce the problem there?

**Comment by Mahsanas** [comment]
So to add to my error report, this is the message I see when I try the Shibboleth.sso/Session link on our data verse:
"A valid session was not found."

I tampered with the Shibboleth2.xml and tried to add a session initiator tag but it did not help. 

@pdurbin, how can I reproduce it on the demo site when the issue is on our instance?

**Comment by pdurbin** [comment]
@Mahsanas you probably can't but thanks for trying. Can you please email support@dataverse.org to open a support ticket?

**Comment by Mahsanas** [comment]
@pdurbin Sure. I would like to add that the session initiation error happens only the first time the dataverse site is loaded. A reload of the website, fixes the issue.

**Comment by pdurbin** [comment]
Closing in favor of #4781

**Comment by pdurbin** [comment]
@Mahsanas years later, I have to ask... did you ever get Shibboleth working? Are you using something else like OAuth or OIDC?
