### ISSUE TITLE
Facet error "Author name" with an apostrophe in the name

### ISSUE THREAD

**Issue by stevenferey** [IQSS/dataverse#5243]
Hi,

In your demo website (https://demo.dataverse.org/), I created this dataset:
https://demo.dataverse.org/dataset.xhtml?persistentId=doi:10.5072/FK2/V1HXNK

The name of the author includes an apostrophe: "L'Hostis"
Because of this, no occurrence of the author is found in the facet "Author Name"

![capture_v4 9 4_error_facet_authorname](https://user-images.githubusercontent.com/13960773/47660241-eba77e00-db96-11e8-91d7-b64013ec9988.png)

Dataverse version : V4.9.4 and previous

Thanks,
--
Steven F.

**Comment by pdurbin** [comment]
@stevenferey thanks for this bug report. On a related note, names like "O'Neill" in the example below are also broken, showing "ONeill, Kelly ({0})" instead (no apostrophe and no number), but you have to click "More" several times to see it:

![screen shot 2018-10-29 at 12 08 34 pm](https://user-images.githubusercontent.com/21006/47663512-98700400-db73-11e8-9223-06e4ef0d45d0.png)

**Comment by stevenferey** [comment]
Thank you for this return Philip,

this bugfix is already included for a future version of dataverse?
Do you know this version?

Thank you very much,
--
Steven F.

**Comment by pdurbin** [comment]
@stevenferey no. The bug hasn't been fixed. This issue is still in the "inbox" at https://waffle.io/IQSS/dataverse

**Comment by tcoupin** [comment]
Same with subject :
![Capture d’écran du 2019-09-18 20-51-42](https://user-images.githubusercontent.com/7457386/65178408-ef671c00-da58-11e9-96e2-0e99e6ed352a.png)

**Comment by tcoupin** [comment]
As you see, I make a PR.

**Comment by djbrooke** [comment]
Thanks @tcoupin, we'll review it
