### ISSUE TITLE
How do I have a custom persistentId when creating a new dataset?

### ISSUE THREAD

**Issue by flaviofrancisco** [IQSS/dataverse#5258]
We would like to have the following information for the field: Dataset Persistent ID: 
doi:10.5072/nioz/7b.b.g since this DOI is already created on DataCite.

This is the request: (v. 4.9.4)
https://{our server}/api/v1/dataverses/doi/datasets/?key={our key}
This is the json used:
{
  "authority": "10.5072/NIOZ",
  "identifier": "nioz/7b.b.g",
  "protocol": "doi",
  "datasetVersion": {
    "metadataBlocks": {
      "citation": {
        "displayName": "Citation Metadata",
        "fields": [
          {
            "typeName": "title",
            "multiple": false,
            "typeClass": "primitive",
            "value": "Dataset One"
          },
          {
            "typeName": "alternativeURL",
            "multiple": false,
            "typeClass": "primitive",
            "value": "https://doi.org/10.5072/nioz/7b.b.g"
          },
          {
            "typeName": "author",
            "multiple": true,
            "typeClass": "compound",
            "value": [
              {
                "authorName": {
                  "typeName": "authorName",
                  "multiple": false,
                  "typeClass": "primitive",
                  "value": "Smith, Robert"
                },
                "authorAffiliation": {
                  "typeName": "authorAffiliation",
                  "multiple": false,
                  "typeClass": "primitive",
                  "value": "The Smiths"
                }
              },
              {
                "authorName": {
                  "typeName": "authorName",
                  "multiple": false,
                  "typeClass": "primitive",
                  "value": "Kew, Susie"
                },
                "authorAffiliation": {
                  "typeName": "authorAffiliation",
                  "multiple": false,
                  "typeClass": "primitive",
                  "value": "Creedence Clearwater Revival"
                }
              }
            ]
          },
          {
            "typeName": "datasetContact",
            "multiple": true,
            "typeClass": "compound",
            "value": [
              {
                "datasetContactName": {
                  "typeName": "datasetContactName",
                  "multiple": false,
                  "typeClass": "primitive",
                  "value": "Dataverse, Admin"
                },
                "datasetContactAffiliation": {
                  "typeName": "datasetContactAffiliation",
                  "multiple": false,
                  "typeClass": "primitive",
                  "value": "Sample Datasets, inc."
                },
                "datasetContactEmail": {
                  "typeName": "datasetContactEmail",
                  "multiple": false,
                  "typeClass": "primitive",
                  "value": "sammi@sample.com"
                }
              }
            ]
          },
          {
            "typeName": "dsDescription",
            "multiple": true,
            "typeClass": "compound",
            "value": [
              {
                "dsDescriptionValue": {
                  "typeName": "dsDescriptionValue",
                  "multiple": false,
                  "typeClass": "primitive",
                  "value": "This is a short text blurb describing the dataset. It is very informative and somewhat self-describing."
                },
                "dsDescriptionDate": {
                  "typeName": "dsDescriptionDate",
                  "multiple": false,
                  "typeClass": "primitive",
                  "value": "2015-01-14"
                }
              }
            ]
          },
          {
            "typeName": "subject",
            "multiple": true,
            "typeClass": "controlledVocabulary",
            "value": [
              "Chemistry"
            ]
          },
          {
            "typeName": "depositor",
            "multiple": false,
            "typeClass": "primitive",
            "value": "Admin Dataverse"
          },
          {
            "typeName": "dateOfDeposit",
            "multiple": false,
            "typeClass": "primitive",
            "value": "2015-01-14"
          }
        ]
      }
    }
  }
}

Kind regards;
Flavio Francisco.

**Comment by flaviofrancisco** [comment]
I was just about to write that I was able to do it with the import.
Worked!
Thanks @pdurbin !

**Comment by pdurbin** [comment]
@flaviofrancisco hi! Do you mind sharing the curl command you used? And the JSON file?

**Comment by kcondon** [comment]
Thanks!

**Comment by pdurbin** [comment]
@flaviofrancisco thank you!!
