### ISSUE TITLE
Regression: Conversion between Username/Email and "remote" accounts (Institution, ORCID, Google, and GitHub) no longer works

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#5260]
https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-apitest-develop/286/testReport/ indicates that conversion from "remote" to "builtin" accounts no longer works:

![screen shot 2018-11-01 at 10 28 31 am](https://user-images.githubusercontent.com/21006/47857802-f5142e80-ddc0-11e8-8e17-814733f18418.png)

This was first observed as of b632e40 which is just a merge of a doc change so I suspect the previous merge of pull request #5244 caused the regression.

**Comment by pdurbin** [comment]
As of dac897c0c (latest in develop branch, not release) here are the specific failures the API test suite is showing (all with the error "User doesn't know password"):

- migrateBuiltinToShib https://github.com/IQSS/dataverse/blob/dac897c0cd4852eb9e8befec6ba0b813f21f411b/src/test/java/edu/harvard/iq/dataverse/api/AdminIT.java#L300
- migrateBuiltinToOAuth https://github.com/IQSS/dataverse/blob/dac897c0cd4852eb9e8befec6ba0b813f21f411b/src/test/java/edu/harvard/iq/dataverse/api/AdminIT.java#L392
- migrateBuiltinToShib https://github.com/IQSS/dataverse/blob/dac897c0cd4852eb9e8befec6ba0b813f21f411b/src/test/java/edu/harvard/iq/dataverse/api/UsersIT.java#L79

My fix for these is pull request #5306.

**Comment by pameyer** [comment]
ade04c4c3209d420a36228d5c3db6e156b2285e6 successfully runs `run-test-suite.sh` in docker-aio (although setupIT broken recently-ish, and now requires a manual glassfish start).  Will defer on reviewing code changes.

**Comment by pdurbin** [comment]
Hooray! Now that pull request #5306 has been merged API tests are passing on phoenix again!

https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-apitest-develop/

![screen shot 2018-11-16 at 12 32 09 pm](https://user-images.githubusercontent.com/21006/48637419-a8714b80-e99b-11e8-985e-f2fe950cebe7.png)
