### ISSUE TITLE
Blocking localhost API access doesn't work when reverse-proxying

### ISSUE THREAD

**Issue by barryrowlingson** [IQSS/dataverse#5261]
I'm installing dataverse on our systems.

The setup is a front-end running nginx and glassfish.

nginx accepts http and redirects to https, and then nginx does https reverse-proxy to glassfish on port 8181

hence everything from the outside world appears to glassfish as being from localhost, and this lets the API leak through. So for example from my desktop I can go to:

    https://mydataverse.org/api/admin/settings

and see the admin settings, which I shouldn't be able to do because I've disabled the admin api except from localhost.

 To prove that, if I go to the API via port 8080 (avoiding nginx's rewriting) then dataverse sees the connection as coming from my desktop, and I get:

    { status:"error", message:"Endpoint available from localhost only. Please contact the dataverse administrator"}

Possible fix is to catch all /api URLs in nginx.conf, but am open to better ideas.

**Comment by pdurbin** [comment]
@barryrowlingson hi! Does nginx do AJP? That's what we recommend for Apache. Please see http://guides.dataverse.org/en/4.9.4/installation/shibboleth.html#ajp via http://guides.dataverse.org/en/4.9.4/installation/config.html#network-ports

**Comment by pameyer** [comment]
@barryrowlingson Are you setting the host header in your nginx proxy config?

**Comment by barryrowlingson** [comment]
nginx docs use proxy_pass:    https://www.nginx.com/resources/wiki/start/topics/examples/javaservers/

There's an nginx ajp module from a third party but no updates for three years: https://github.com/yaoweibin/nginx_ajp_module

**Comment by pdurbin** [comment]
I'm trying to think of the people who use nginx:

- @4tikhonov at #4665
- @qqmyers at #4511
- @lwo at #2826

**Comment by barryrowlingson** [comment]
relevant chunk of my nginx conf is here.

[nginx.txt](https://github.com/IQSS/dataverse/files/2539325/nginx.txt)

**Comment by pdurbin** [comment]
@barryrowlingson we're starting to talk about your troubles in IRC: http://irclog.iq.harvard.edu/dataverse/2018-11-01#i_77507

The easiest way to join in is http://chat.dataverse.org

**Comment by barryrowlingson** [comment]
(I know I said I was going home but I had to try the suggestions from IRC)

adding:  proxy_set_header Host $host to the location block that forwards to glassfish didn't work - I suspect glassfish is checking the host via IP address and not https headers?

```
        location / {
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass https://glassfish/;
       }
```

So for now I've added a total block on /api/admin from within the https server block:
```
location ^~ /api/admin { deny all; }
```

which now throws a 403 error on that endpoint URL, everything else working fine.

**Comment by qqmyers** [comment]
Looking in the source - the localhost check is 
return Arrays.equals( new short[]{127,0,0,1} , bytes);
or 
return Arrays.equals(words, new int[]{0,0,0,0,0,0,0,1} );
for IPV6...

**Comment by pameyer** [comment]
Good catch @barryrowlingson and @qqmyers - sorry to lead things down the wrong path (even if just a little ways).

**Comment by poikilotherm** [comment]
I accidentially came across this issue.
Using NGINX in our Dataverse installation on K8s and working around this by using the API "unblock-key" parameter.
Is this still of interest?

**Comment by djbrooke** [comment]
Thanks @poikilotherm. I'll close this. If people feel it should be reopened, please comment.
