### ISSUE TITLE
API Blocking requires two keys

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#5262]
It looks like blocking the API requires two keys: :BlockedApiPolicy and :BlockedApiEndpoints, yet it is possible to set one without the other (experimentally verified :-) ) which then leaves the apis, including admin and builtin-user, open.  Not a big priority but it would be nice to put a warning in the log (from edu.harvard.iq.dataverse.api.ApiBlockingFilter ) and/or api response.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
