### ISSUE TITLE
Extend DataCitation tests

### ISSUE THREAD

**Issue by pkiraly** [IQSS/dataverse#5265]
There is an initial version of a DataCitationTest class, but it tests only one public method. It should be extended to cover other functionalities of the base class `DataCitation`.

**Comment by pdurbin** [comment]
@pkiraly thanks for opening this issue! I'm always in favor of increasing our code coverage. Is this something you'd like to work on? As I mentioned at https://github.com/IQSS/dataverse/issues/5246#issuecomment-435017719 I would suggest using a mock to exercise dataset fields.

**Comment by pkiraly** [comment]
@pdurbin 
I have created a `createATestDatasetVersion()` method withing the test which creates a mock DatasetVersion object. This could be moved to its own class, since maybe other tests would like to use such a mock DatasetVersion.
What do you think? Did you create such mock classes within the test directory?

**Comment by pdurbin** [comment]
@pkiraly pull request #5266 looks good and code coverage is up! I'm fine with that method. Thanks! Of to QA.

**Comment by pkiraly** [comment]
@pdurbin I have added a new pull request, which extends the previous one in terms of coverage of functionalities. However it is still not the end. I'd like to add even more test, because it still doesn't cover everything. How should we proceed with it? Is it OK to keep this issue for that or I should create a new issue for every further improvements?
