### ISSUE TITLE
as a developer, I'd like the possible return values of API calls to be documented

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#5270]
As of fa38c5c794fe19b4ed28a0eeb8208ce7df612639; it looks like the only API call with documented return values is `$SERVER/api/datasets/$id/actions/:publish` (and that only documents success values).

Ideally, which HTTP status codes (and why) would be accessible without reading the source.

**Comment by pdurbin** [comment]
@pameyer I just wanted to let you know that "Why Aren’t the Return Values (HTTP Status Codes) Documented?" is one of the questions I added to the new "Frequently Asked Questions" section of the API Guide in pull request #6107.

For now, here's what it says:

"They should be. Please follow https://github.com/IQSS/dataverse/issues/5270 and please consider making a pull request to help. The :doc:`/developers/documentation` section of the Developer Guide should help you get started. :ref:`create-dataverse-api` has an example you can follow or you can come up with a better way."
