### ISSUE TITLE
Move logic for identifier type validation / url generation from code to db

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#5271]
In #4371, we added logic to validate author identifiers based on type and also to generate URLs. This is in the Java code, however, so now we can't just add a new type by just modifying the db, we need to add the corresponding code, as well. We agreed to accept this a technical debt in order to move #4371 along.

This issue is to track the moving of this from the code to the db. That is we want to define the URL schemes and validation in the database, and then have the code generically handle this.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
