### ISSUE TITLE
can't delete user if entry in passwordresetdata

### ISSUE THREAD

**Issue by barryrowlingson** [IQSS/dataverse#5281]
Trying to delete a test username via:

`curl -X DELETE -v  http://localhost:8080/api/admin/authenticatedUsers/testuser`

and get a 500 internal server error returned. In the logs:

```
org.postgresql.util.PSQLException: ERROR: update or delete on table "builtinuser" violates foreign key constraint "fk_passwordresetdata_builtinuser_id" on table "passwordresetdata"
  Detail: Key (id)=(3) is still referenced from table "passwordresetdata".
```

which I guess is because there's a pending password reset still valid. I can't see any reason to keep the password reset info around if deleting a user, so the delete should cascade to that table.

Workaround is to delete the corresponding row from the passwordresetdata table via psql, and then the `curl` works.

**Comment by pdurbin** [comment]
@barryrowlingson yes, that's the right workaround for now. Related: #4475 #1929

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
