### ISSUE TITLE
AccessIT Failing on Develop

### ISSUE THREAD

**Issue by sekmiller** [IQSS/dataverse#5287]
When adding integration tests for the request file access API I discovered that the AccessIT tests are failing in develop. Not sure at the moment which merge is causing the failure.

**Comment by pdurbin** [comment]
Something is broken enough that I can't even get the phoenix test suite to execute. I'm getting the following failure:

```
+ FILE_ID_OF_A_PUBLISHED_FILE=12
++ curl --insecure --write-out '%{http_code}' --silent --output /dev/null https://phoenix.dataverse.org/api/access/datafile/12
+ STATUS_CODE_FROM_DOWNLOADING_PUBLISHED_FILE=404
+ echo 404
404
+ [[ 404 != 200 ]]
+ exit 1
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

See https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-deploy-develop/304/console

When stage 2 (deployment) doesn't finish like this, stage 3 (API tests) can't run. See http://guides.dataverse.org/en/4.9.4/developers/testing.html#how-the-phoenix-tests-work

**Comment by pdurbin** [comment]
The phoenix server.log is saying this:

`Caused by: org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://localhost:8983/solr/collection1: ERROR: [doc=dataverse_3] unknown field 'dvAlias'`

I should have emailed dataverse-dev after pull request #5267 was merged. In the future, we're going to run an experiment where developers can put instructions in their pull requests: #5284.

**Comment by pdurbin** [comment]
I forgot that I put https://github.com/IQSS/dataverse/blob/96800f0f25e09d6b816bfb000fa68752b7184eed/doc/release-notes/5011-search-by-dataverse-alias.md in my merged pull request. 😄

**Comment by pdurbin** [comment]
I emailed the dev community to let them know about the Solr schema change: https://groups.google.com/d/msg/dataverse-dev/WwPRY23FyAA/VYeiHx0PBQAJ

I re-ran the tests on phoenix and as of https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-apitest-develop/290/ we are down the known failures with account conversion in #5260

@sekmiller and I are still messing with his dev environment so I won't close this quite yet.

**Comment by sekmiller** [comment]
All set here
