### ISSUE TITLE
Error trying to add a file to a draft dataset that has already a version published using SWORD API

### ISSUE THREAD

**Issue by flaviofrancisco** [IQSS/dataverse#5298]
On our dev server we have a doi that has a version 1 published. When I try to add a new file to the next draft version using the following url:
http://dataverse-dev.nioz.nl:8080/dvn/api/data-deposit/v1.1/swordv2/edit-media/study/doi:10.5072/nioz/7b.b.1
Headers:
x-dataverse-key: our key
Content-Type: application/x-zip-compressed
Content-Disposition: filename="doi-test-i.b.txt"
Packaging: http://purl.org/net/sword/package/SimpleZip
Authorization : super user credentials of our dataverse dev server
I have the error: 403 Forbidden

But if I use the Native API: http://dataverse-dev:8080/api/datasets/:persistentId/add?persistentId=doi:10.5072/nioz/7b.b.1
Headers:
Content-Type: multipart/form-data
x-dataverse-key:  our key
Basic Authorization
Body:
multipart/form-data: file="doi-test-i.b.txt"

We are able to insert the file into the draft version.

Am I missing something or doing something wrong with the SWORD API to add files into that dataset?

Thanks in advance;
Flavio.

**Comment by pdurbin** [comment]
@flaviofrancisco the API Guide isn't very clear about this but the "x-dataverse-key" header you're using doesn't work with SWORD. For SWORD, you have to use basic auth. Please see...

> "Dataverse 4 supports API tokens and requires them to be used for APIs instead of a username and password. In the curl examples below, you will see curl -u $API_TOKEN: showing that you should send your API token as the username and nothing as the password. For example, curl -u 54b143b5-d001-4254-afc0-a1c0f6a5b5a7:.

... at http://guides.dataverse.org/en/4.9.4/api/sword.html

**Comment by flaviofrancisco** [comment]
Hi @pdurbin,

I am using Advanced REST client to test and even if I remove the x-dataverse-key it gives me the 403 error.

If I this API against a dataset that was never published it works.

![image](https://user-images.githubusercontent.com/12722538/48261706-38554980-e420-11e8-80b6-ccae734def26.png)

**Comment by flaviofrancisco** [comment]
@pdurbin;

I just figure out what is happening. The json that we are sending has no description. Since this is a mandatory field there is no possible to upload the file.

Thanks;
Flavio.
