### ISSUE TITLE
Convert user: Unable to convert oauth users to builtin users in cases where oauth username characters are not valid for builtin.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#5314]
Oauth user accounts only check not null for username whereas builtin usernames have more stringent requirements. A case in point is several users make their oauth usernames their email addresses whereas the '@' character is not allowed in the builtin username.

Out of nearly 900 oauth user accounts in prod, 21 have this issue, found using this query:
select authenticationproviderid, authenticateduser_id from authenticateduserlookup where authenticateduser_id in (select id from authenticateduser where useridentifier like '%@%');

The temporary workaround is to change the username to something acceptable, then convert.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
