### ISSUE TITLE
Do not require email server for development environments

### ISSUE THREAD

**Issue by matthew-a-dunlap** [IQSS/dataverse#5328]
To install Dataverse, an email server is required to complete the installer. Dataverse will run without it (with some log errors) but the installer will not pass.

In the past I've hacked our installer to not ask for the email with good results, tho there may be some slowdown.

It would be good to make this optional for easier use of AWS environments, etc.

**Comment by pameyer** [comment]
For future reference, something like http://nilhcem.com/FakeSMTP/ might be another approach to this.

**Comment by mheppler** [comment]
This came up today in a live demo. So embarrassing.

**Comment by pdurbin** [comment]
Please see also:

- issue #7236: When setting up a dev environment, I don't want to be blocked by not having a mail server  
- pull request #7242: improve docs on setting up a new dev environment

**Comment by pdurbin** [comment]
@matthew-a-dunlap as of PR #7242 the dev guide now gives explicit instructions on how to avoid needing to install a mail server to set up a dev environment:

---

The installer will try to connect to the SMTP server you tell it to use. If you don’t have a mail server handy you can run `nc -l 25` in another terminal and choose “localhost” (the default) to get past this check.

---

That's from https://guides.dataverse.org/en/5.11.1/developers/dev-environment.html#run-the-dataverse-software-installer-script

Are you ok with closing this?

**Comment by pdurbin** [comment]
@matthew-a-dunlap I'm closing this. Using Docker you now get an SMTP server called Mail Dev when you spin up containers. It looks like this:

<img width="938" alt="222300276-ef55e310-dc08-4ded-b2fe-a4773a8be478" src="https://github.com/IQSS/dataverse/assets/21006/c5858fff-68c6-4b90-b13e-d5ed9ce8e7d9">

We switched the main "dev setup" docs over to Docker in this PR:

- #9761

Please give them a try! I'd love to hear what you think. Some related discussion: https://dataverse.zulipchat.com/#narrow/stream/379673-dev/topic/devs.2C.20please.20switch.20to.20Payara.206
