### ISSUE TITLE
Search highlighting: Highlighting should only show matches on what was searched for and should show all matches for multivalued fields, not just first hit.

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#533]
---

Author Name: **Kevin Condon** (@kcondon)
Original Redmine Issue: 3948, https://redmine.hmdc.harvard.edu/issues/3948
Original Date: 2014-05-07
Original Assignee: Philip Durbin

---

Tested on 5/7

This is relatively minor but may help user by providing more accurate feedback on their search results.

In a test dv, I created 3 cell fields and put cell1, cell2, cell3, one in each field.
When searching either in basic or adv search, if I entered cell1 cell2 cell3, highlight only shows match on cell1
Same thing happens for other multi valued fields, such as subject, organism, etc.

**Comment by pdurbin** [comment]
This feels related to #1589 and might even be the same issue.

**Comment by eaquigley** [comment]
Closing as a duplicate of #1589.
