### ISSUE TITLE
Admin Guide needs a page that lists community created reporting tools

### ISSUE THREAD

**Issue by jmjamison** [IQSS/dataverse#5331]
Admin Guide needs a page that lists reporting tools created by the community.  There were 3 mentioned in the Nov-11-2018 community.   

I'm working on a page for this in my dataverse fork and will create an issue.

**Comment by pdurbin** [comment]
@jmjamison thanks for creating pull request #5333! I just dragged this issue to code review at https://waffle.io/IQSS/dataverse

**Comment by pdurbin** [comment]
@jmjamison I just moved your pull request to QA. Wow, I asked for help just today on the community call and you already responded. Thanks!

A few things:

- In 001f246 I added the new Reporting Tools page to the side bar.
- Your branch is called "develop" which is fine but ideally it would have been called something like "5331-reporting-tools". It'll merge just the same but if you want to read more on this topic of branch naming, please see http://guides.dataverse.org/en/4.9.4/developers/version-control.html#create-a-new-branch-off-the-develop-branch . I can further explain in IRC sometime if you want. No pressure. 😄 
- I thought about adding these tools to the list at http://guides.dataverse.org/en/4.9.4/developers/intro.html#related-projects but it's not at all necessary. Just a thought.
- I'm not sure what to say about miniverse. It was created at IQSS but we aren't maintaining it. I think @4tikhonov might have a fork we could link to. We could always add it later to this page.
- @kcondon is on vacation this week so please don't expect your pull request to get tested and merged until next week at the soonest.

Thanks again!

**Comment by pdurbin** [comment]
Over at https://groups.google.com/d/msg/dataverse-community/FO0smRaA4I4/7Y-Z3hA0BQAJ Slamet asked us to list Matrix on that "related projects" list so I did in b52877d
