### ISSUE TITLE
Internationalization - Creative Commons logo

### ISSUE THREAD

**Issue by kaitlinnewson** [IQSS/dataverse#5332]
Hi Dataverse team,

I've been working with @JayanthyChengan on the internationalization project, and we've run into an issue we'd love your input on. The Creative Commons CC0 logo appears throughout dataverse in a dataset's 'terms on use' section when CC0 is selected. The CC logos don't have translations for the most part, so we can either remove the image completely, or allow translators to create their own images and provide a link to it. Before we do any work on this, do you have additional thoughts or suggestions on the ideal approach?

Thanks!

**Comment by mheppler** [comment]
Hey, @kaitlinnewson and @JayanthyChengan. That lil CC0 PNG image file recently popped up in my source tree, and I had kinda forgotten about it.

Looking quickly on the creativecommons.org site, I did not see anything that was provided by them, so I too wonder if there is a custom solution that fits into our internationalization story. Possibly a dynamically generated SVG that pulls texts from the bundles...?

Also note, there are discussions in #1753 to offer more licensing flavors than just CC0.

**Comment by kaitlinnewson** [comment]
If I'm understanding [the CC policies](https://creativecommons.org/policies) correctly, I don't think we can modify the logo without express permission:

> Modification of CC Licenses: To prevent confusion and maintain consistency, you are not allowed to use CREATIVE COMMONS, CC, the CC Logo, or any other Creative Commons trademarks with modified versions of any of our legal tools or Commons deeds, including modifications that do not modify the legal code directly but that further restrict or condition the rights granted by the particular legal tool. These modifications are often contained in a website’s terms of use, and where they are present you may not suggest that you are offering works under a Creative Commons legal tool. For the avoidance of doubt, you may not use any CC trademarks with unofficial language translations of CC licenses. See this page for more information.
