### ISSUE TITLE
Code formatting issues

### ISSUE THREAD

**Issue by pkiraly** [IQSS/dataverse#5336]
I just found that Dataverse already have a checkstyle.xml. Most of the rules are commented out, but even the remaining produce 200+ reported violation of the ruleset.

The command to check errors:
```
mvn clean checkstyle:checkstyle
```

This generates the HTML page 'target/site/checkstyle.html'.

It is clear if you open any Java code, that the number of commiters working with different coding style, so the result is not uniformed. Clearer code does not improve the software, but helps lowering the burden of maintenance and making the code more readable. My past experiences with code clearing efforts suggest, that this is an ongoing process: you have to run checks again and again, and clearing code constantly.

Code cleaning on the other hand is an ideal task if you, as a novice in the community just would like to test the water and try to understand the structure of the code. It doesn't require of deep knowledge of the code, and still, you can contribute with some useful thing.

I see three subtasks here:

* run check, and submit pull requests for the clearer code
* extend the checks one by one, increasing the number of checkstyle ruleset
* improving the documentation about the coding style in Dataverse manual (http://guides.dataverse.org/en/4.9.4/developers/coding-style.html)

**Comment by pkiraly** [comment]
Meantime I've started working with the current checkstyle settings, and fixed all the problems. It covers about 200 Java source files.

**Comment by pdurbin** [comment]
@pkiraly um. I'm not sure I want all of that change at once. It's very disruptive to our git history. Can we please talk about this more?

**Comment by pdurbin** [comment]
@pkiraly oh. You already made pull request #5337. I'll drag it to code review at https://waffle.io/IQSS/dataverse and we'll talk about it at standup.

**Comment by pkiraly** [comment]
@pdurbin I am open to discuss it. If this approach doesn't fit for your workflow, we can do differently. The thing is that approx. 200 files have either tabs in it instead of spaces (most of them has sporadic tabs, and only a couple of files has only tabs) for indentation. The other type of issue the checkstyle check is the usage of new lines before right curly braces, such as

```
public someMethod()
{
    ...
}
```

**Comment by pdurbin** [comment]
@pkiraly thanks. Please be advised that standup was cancelled today due to light attendance and the next two days are a holiday (Thanksgiving). Thank you for helping us make the code more consistent. I'm curious about your thoughts on keeping it consistent over time.

**Comment by poikilotherm** [comment]
As the one who opened #5075 in the first place, I can only second you on using more checks and fixing the code base. I had this stuff added to Travis too, but this was removed. It has not been introduced into the regular build cycle, too.

I hear the arguments of @pdurbin and others and understand their fear about not being able to use `git blame` easily. It's a real bummer: I really can't think of a way how to avoid that in Git.

**Comment by pdurbin** [comment]
@pkiraly @poikilotherm The thing about continuous integration and Travis in particular is that as a team we don't look at https://travis-ci.org/IQSS/dataverse very often. A git hook preventing developers from pushing code would be effective but I don't think we want that.

@oscardssmith sorry by "git blame" I'm talking more about logical changes than people.

**Comment by pkiraly** [comment]
@pdurbin I agree that code style check should not be a show stopper. If the community don't use Travis output very often, then we don't have to integrate it that way. If there is some tool, which behaves like coverall.io - test coverage report triggered automatically by Travis displayed in a separate site, which is linked from the Github's repo main page, then it would be worth to intergate such a hook into Travis. I am not aware such a tool. For me simple command line check and create report locally works well. 

@oscardssmith Making patches per contributors would be a good idea, but I don't really know how to implement it. We should separate the output of checkstyle by the ID of the last commiter of each source file. Sounds a little bit tricky, but not impossible nevertheless.

**Comment by djbrooke** [comment]
Hi @pkiraly - I got a chance to catch up with @scolapasta and we think that the concerns about the disruptions to the git history outweigh the benefit of this change. I'm going to close this PR and issue, but if there's some other change that provides a check at submission time (or some other solution that's not as disruptive and is more incremental), we should talk through it before a PR.

**Comment by pkiraly** [comment]
Dear @djbrooke,

the main purpose of this issue was to start discussion, it was a side topic whether the actual PR is OK or not. I accept your argument that solving these issues in one single step is too much of a burden elsewhere. But I don't see that there would be an agreement how to clean the code formatting in general. I mentioned some other measurements, such as improving the code style guide of the manual, and also: increasing the code formatting rules in checkstyle.xml. Maybe you missed those points or maybe you don't want to handle this issue at all, it is not clear from your comment.

Best,
Péter

**Comment by djbrooke** [comment]
Got it, sorry for closing this larger issue prematurely. We're very open to smaller batches that get the project's code cleaner! :) When there's some smaller part that you'd like to implement please create another issue and we can discuss there!

**Comment by pdurbin** [comment]
@pkiraly please check out this PR by @poikilotherm (and the issue it closes, that I opened about code formatting):

- https://github.com/gdcc/xoai/pull/36

Is this what you want for Dataverse?

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
