### ISSUE TITLE
MyData: Published status not updated on MyData page after publishing on test environments

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#5343]
1. create dataverse, dataset or both
2. publish both
3. notice both are still listed as unpublished on MyData page.

**Comment by pdurbin** [comment]
I'm on bc2661a77 on develop and I can't reproduce this (screenshot below). So I guess I'll move this to QA?

![screen shot 2019-02-13 at 4 15 08 pm](https://user-images.githubusercontent.com/21006/52744409-a3c42f80-2faa-11e9-8b47-a174e7346916.png)

**Comment by djbrooke** [comment]
I tried this on demo.dataverse.org as well and I was unable to reproduce this.

**Comment by kcondon** [comment]
OK, updated instructions:
as a non superuser, do the following:
1. create a dataset in root dv, got to mydata page, do not see dataset.
2. create a dataverse in root dv, go to mydata page, do not see dataverse.

if you create a dataverse in root and a dataset in that sub dataverse, the dataset acts normally on Mydata page.
