### ISSUE TITLE
Display when assigning a role

### ISSUE THREAD

**Issue by kaitlinnewson** [IQSS/dataverse#5350]
Hi Dataverse team,

We noticed this in the context of our internationalization work, but it also applies to any custom role created by a user.

When the name of the role is a longer string, the display is not correct and breaks onto a separate line below the checkbox (see attached screenshot). This was tested in 4.9.4 in Firefox.

![screen shot 2018-11-28 at 10 37 34 am](https://user-images.githubusercontent.com/6903515/49163032-29183c00-f2fa-11e8-8a4d-fa45bc4240c2.png)

**Comment by djbrooke** [comment]
Closing in favor of #6578
