### ISSUE TITLE
More places to find out how to report security issues

### ISSUE THREAD

**Issue by dheles** [IQSS/dataverse#5357]
When I inquired about how to report security issues to the Dataverse project, I was directed to the Contributing document in the GitHub repo:
 
https://github.com/IQSS/dataverse/blob/develop/CONTRIBUTING.md

Other good places for this information might be the Contact page of dataverse.org:

https://dataverse.org/contact

or on the front page of the guides, perhaps under Other Resources / Support:

http://guides.dataverse.org/en/latest/

**Comment by pdurbin** [comment]
@dheles thanks again for recommending that we update https://dataverse.org/contact to talk about how to report security issues. Here's how it looks now:

![screen shot 2018-12-19 at 2 45 30 pm](https://user-images.githubusercontent.com/21006/50243955-9ae52200-039c-11e9-9f1a-c4a25b8b1f41.png)

Do you feel like making a pull request to update that "Other Resources / Support" text?
