### ISSUE TITLE
Shibboleth: Cannot get shib login working with Test Shib, following the instructions in the guide.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#5369]
Was not able to get Shibboleth log in working on a test system by following the instructions in the guide.
This had worked previously but now returns the error:
Error Message: SAML 2 SSO profile is not configured for relying party https://dataverse-internal.iq.harvard.edu/sp

Note the instructions includes a test shib metadata file that has an out of date cert. My installation bypassed this by getting the latest metadata directly from Test Shib.

Here is more information that may help troubleshooting:

o we're running shib v2.5.5 (/usr/sbin/shibd -v
and the saml 2.0 came from the testshib providers.xml metadata file:
https://www.testshib.org/metadata/testshib-providers.xml
EntitiesDescriptor xmlns="urn:oasis:names:tc:SAML:2.0:metadata" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:mdalg="urn:oasis:names:tc:SAML:metadata:algsupport"
and the concise debug output from test shib:
16:21:05.226 - DEBUG [edu.internet2.middleware.shibboleth.idp.util.HttpServletHelper:339] - LoginContext key cookie was not present in request
16:21:05.227 - DEBUG [edu.internet2.middleware.shibboleth.idp.profile.saml2.SSOProfileHandler:188] - Incoming request does not contain a login context, processing as first leg of request
16:21:05.227 - DEBUG [edu.internet2.middleware.shibboleth.idp.profile.saml2.SSOProfileHandler:366] - Decoding message with decoder binding 'urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect'
16:21:05.230 - DEBUG [edu.internet2.middleware.shibboleth.common.relyingparty.provider.SAMLMDRelyingPartyConfigurationManager:128] - Looking up relying party configuration for https://dataverse-internal.iq.harvard.edu/sp
16:21:05.230 - DEBUG [edu.internet2.middleware.shibboleth.common.relyingparty.provider.SAMLMDRelyingPartyConfigurationManager:134] - No custom relying party configuration found for https://dataverse-internal.iq.harvard.edu/sp, looking up configuration based on metadata groups.
16:21:05.231 - DEBUG [edu.internet2.middleware.shibboleth.common.relyingparty.provider.SAMLMDRelyingPartyConfigurationManager:157] - No custom or group-based relying party configuration found for https://dataverse-internal.iq.harvard.edu/sp. Using default relying party configuration.
16:21:05.232 - WARN [org.opensaml.saml2.binding.security.SAML2AuthnRequestsSignedRule:81] - SPSSODescriptor role metadata for entityID 'https://dataverse-internal.iq.harvard.edu/sp' could not be resolved
16:21:05.232 - DEBUG [edu.internet2.middleware.shibboleth.idp.profile.saml2.SSOProfileHandler:387] - Decoded request from relying party 'https://dataverse-internal.iq.harvard.edu/sp'
16:21:05.233 - WARN [edu.internet2.middleware.shibboleth.idp.profile.AbstractSAMLProfileHandler:305] - No metadata for relying party https://dataverse-internal.iq.harvard.edu/sp, treating party as anonymous
16:21:05.234 - WARN [edu.internet2.middleware.shibboleth.idp.profile.saml2.SSOProfileHandler:222] - SAML 2 SSO profile is not configured for relying party https://dataverse-internal.iq.harvard.edu/sp
I was not able to get the ff saml tracer to do anything
was able to get saml tracer working for Chrome and trace looks ok, no obvious errors
<samlp:AuthnRequest
   AssertionConsumerServiceURL="https://dataverse-internal.iq.harvard.edu/Shibboleth.sso/SAML2/POST"
   Destination="https://idp.testshib.org/idp/profile/SAML2/Redirect/SSO"
   ID="_b5f6b021dc14fa7b558d3572362f6e82" IssueInstant="2018-12-04T21:32:12Z"
   ProtocolBinding="urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST" Version="2.0"
   xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol">
   <saml:Issuer xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">https://dataverse-internal.iq.harvard.edu/sp</saml:Issuer><samlp:NameIDPolicy AllowCreate="1"/></samlp:AuthnRequest>

I had reregistered the sp metadata but it made no difference

**Comment by pdurbin** [comment]
Today I learned that at http://www.testshib.org that the TestShib testing service we've been using is gone. Here's a screenshot:

![screen shot 2018-12-10 at 12 34 03 pm](https://user-images.githubusercontent.com/21006/49750599-5f01dc80-fc79-11e8-9808-ae6b93f1aefa.png)

This is unfortunate since we recommend using TestShib in our Installation Guide to validate that you've configured Shibboleth properly for use with Dataverse. Here's a screenshot from http://guides.dataverse.org/en/4.9.4/installation/shibboleth.html#exchange-metadata-with-your-identity-provider ...

![screen shot 2018-12-10 at 12 44 25 pm](https://user-images.githubusercontent.com/21006/49750598-5f01dc80-fc79-11e8-8820-ebac07c4d9b4.png)

... but there are many config files that should be removed such as `doc/sphinx-guides/source/_static/installation/files/etc/shibboleth/dataverse-idp-metadata.xml` which was causing trouble for us in #3446 anyway.

**Comment by pdurbin** [comment]
Oh, the other thing I mentioned to @djbrooke but that I should remind everyone of is that HarvardKey should "just work" for the following three hostnames that are part of the InCommon XML feed:

- https://dataverse.harvard.edu - https://incommon.org/federation/info/entity.html?entityID=https%3A%2F%2Fdataverse.harvard.edu%2Fsp&technical=true
- https://demo.dataverse.org - https://incommon.org/federation/info/entity.html?entityID=https%3A%2F%2Fdemo.dataverse.org%2Fsp&technical=true
- https://beta.dataverse.org - https://incommon.org/federation/info/entity.html?entityID=https%3A%2F%2Fbeta.dataverse.org%2Fsp&technical=true 

By "just work" I mean that you don't need to make a side deal to exchange metadata.

**Comment by djbrooke** [comment]
Note to self - check with Mahbub about the options of testing Shib at Harvard.

**Comment by djbrooke** [comment]
The folks at Harvard mentioned another service that may be helpful here:

https://samltest.id/

**Comment by pdurbin** [comment]
Also reported at #5666

**Comment by djbrooke** [comment]
Closing in favor of #6018.
