### ISSUE TITLE
Production Date: Date range instead of single date?

### ISSUE THREAD

**Issue by lmaylein** [IQSS/dataverse#5370]
Is it possible to allow date ranges for the production date in future releases?

Or is there better way to record that the production of the data has lasted several months/years ... ?

**Comment by pdurbin** [comment]
@lmaylein it's fine to ask here and people like @jggautier or @sbarbosadataverse might have some ideas for you, but I think it would for you to post to https://groups.google.com/forum/#!forum/dataverse-community as well (and include a link to this GitHub issue) to see what the community does for cases like this. Maybe there's a way to express date ranges in DDI or something. I'm not sure.

**Comment by lmaylein** [comment]
https://groups.google.com/forum/#!topic/dataverse-community/lZ9ntAy3QQs

**Comment by pdurbin** [comment]
@lmaylein thanks for kicking off that thread.

So so we have a visual, currently (as of 5.11.1) the watermark shows YYYY-MM-DD like this:

<img width="588" alt="Screen Shot 2022-09-30 at 5 29 25 PM" src="https://user-images.githubusercontent.com/21006/193358821-f9f86e45-db52-4135-8a17-47a7fb1491ca.png">

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
