### ISSUE TITLE
Deposit from GitHub 

### ISSUE THREAD

**Issue by TaniaSchlatter** [IQSS/dataverse#5372]
This issue is phase 1 of three phases to [allow depositers to add code to Dataverse (#2739)](https://github.com/IQSS/dataverse/issues/2739).  

- This issue was [discussed in the community call on December 4, 2018](https://docs.google.com/document/d/1EXKqARyxdPWW7yg3TPi9-QvXME44mwcyXkogxRGoFXk/edit)
- [Feature Design Doc](https://docs.google.com/document/d/1Wa8OJBftzJs_v9QDeccRanx6S0MNoiuPjqnRaL20cNk/edit)

**Planned functionality and next steps:**

**Upload:**
Provide URL input with import functionality. Create a .zip of what is available from the URL. Users must paste the URL of the repo’s landing page (easily found in their browser’s address bar). If they paste the [default landing page](https://github.com/IQSS/dataverse), they get the default branch up to the latest commit. If desired, they can use the URL for a specific [branch](https://github.com/IQSS/dataverse/tree/2036-fewer-dvobject-lookups), [release](https://github.com/IQSS/dataverse/tree/v4.9.3), or [commit](https://github.com/IQSS/dataverse/tree/ec377d2a4e27424db8815c55ce544deee48fc5e0). 

System uses "repoName-branchName" or repoName-releaseNameNumber as ZIP name. User can edit the name.

Users could add more than one file to the dataset. If this happens, the concept of archiving a GitHub repository as a dataset would be broken. 
- Messaging/tool tip stating if they want to maintain their repository as a dataset, they should not add any other files.
- If a user adds one or more files to the dataset, having a DOI that refers only to the GitHub repository would rely on file-level DOIs, and not all installations have file-level DOIs enabled.

**Metadata:**
User can add metadata to the Description field (as now – no change). 
The repo URL is saved in the database and displayed on the page. 

**Edit:**
Edit the ZIP just like any other file deposited into a dataset. For a user to update the ZIP, go to replace pg just like any other file, same upload method widgets available on upload pg will be available on replace pg.
- For consideration: could the upload widget on the replace pg retain the GitHub repo URL?

**Replace:**
_See Edit._ Allow users to replace the ZIP just like any other file deposited into a dataset. 
For a published 2.0 version, the new zip to be a replaced version of the zip in the 1.0 version. Users can see that files were replaced vs deleted and added on the versions tab.

**To do:**

- [ ] Mock up (digital) the UI and relevant messages (on-page help, tool tips, success/error message text) for release 1:
    - Create dataset page
    - File replace page
- [ ] Review and refine
- [ ] Create test plan, recruit participants, conduct testing
- [ ] Revise if/as needed
- [ ] Finalize mockups and UI behavior for development

**Comment by pdurbin** [comment]
I promised @ethomson and @neovintage from GitHub that I would link up the notes from the fantastic meeting we had with them today. Here they are: https://groups.google.com/d/msg/dataverse-community/uEJRcNoghjY/RVnXkuxoBgAJ

**Comment by pdurbin** [comment]
@atrisovic created an awesome GitHub integration using GitHub Actions.

- docs: https://guides.dataverse.org/en/5.11.1/admin/integrations.html#github
- action: https://github.com/marketplace/actions/dataverse-uploader-action
- code: https://github.com/IQSS/dataverse-uploader
- video: https://www.youtube.com/watch?v=3ek7F_Dxcjk&t=6286s
- slides: https://osf.io/e4xu6
- PR to add to docs: #8416

I think we should close this issue. We can create a fresh one for the next level of GitHub integration.
