### ISSUE TITLE
Community Call on Docker, Kubernetes and more: collecting interested people

### ISSUE THREAD

**Issue by poikilotherm** [IQSS/dataverse#5373]
Dear Dataverse users, sysadmins, devs, devops and anybody else,

from the [community call on 12/4/2018](https://docs.google.com/document/d/1EXKqARyxdPWW7yg3TPi9-QvXME44mwcyXkogxRGoFXk) I got the impression that a follow up meeting on this topic might be a good idea.

**If you are interested in using Dataverse on Docker and/or Kubernetes in production systems or during development, let's get in touch and talk. Community power!** :muscle: 

Please leave your feedback below and feel free to @mention more people you think that might be interested. On 12/12/2018 I will try to come up with a timeslot poll for all interested parties. And yes: timezones timezones timezones!

Please spread the word! :smile:

**Comment by poikilotherm** [comment]
Mentioning people I know that might be interested:
@bronger @pdurbin @pameyer @MrK191 @4tikhonov @qqmyers

**Comment by poikilotherm** [comment]
Hey @mercecrosas, @djbrooke and @sbarbosadataverse, may I ask you to [retweet my post](https://twitter.com/poi_ki_lo_therm/status/1070446102434979842) to reach more people out there? Thanks! :smile_cat:

**Comment by mercecrosas** [comment]
Good idea! Done.

On Fri, Dec 7, 2018 at 2:37 AM Oliver Bertuch <notifications@github.com>
wrote:

> Hey @mercecrosas
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_mercecrosas&d=DwMFaQ&c=WO-RGvefibhHBZq3fL85hQ&r=n9HCCtgqDPssu5vpqjbO3q4h2g6vMeTOp0Ez7NsdVFM&m=MZI9f10DItGo_QZKahsYAsRnXqQ6F2uY5DjLErMRYrs&s=FS4h4CawhsMO3qH_dkYVgDyCR7rzZVssgjU3sAvryQ0&e=>,
> @djbrooke
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_djbrooke&d=DwMFaQ&c=WO-RGvefibhHBZq3fL85hQ&r=n9HCCtgqDPssu5vpqjbO3q4h2g6vMeTOp0Ez7NsdVFM&m=MZI9f10DItGo_QZKahsYAsRnXqQ6F2uY5DjLErMRYrs&s=thN7yUpvcBD-HtpBxbJrgg6ouLt4T_TNseQsHzPef-s&e=>
> and @sbarbosadataverse
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_sbarbosadataverse&d=DwMFaQ&c=WO-RGvefibhHBZq3fL85hQ&r=n9HCCtgqDPssu5vpqjbO3q4h2g6vMeTOp0Ez7NsdVFM&m=MZI9f10DItGo_QZKahsYAsRnXqQ6F2uY5DjLErMRYrs&s=bIckpBq0p-RVvVb-ADozPDiL98tm5vImNzqJ2DI8Cug&e=>,
> may I ask you to retweet my post
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__twitter.com_poi-5Fki-5Flo-5Ftherm_status_1070446102434979842&d=DwMFaQ&c=WO-RGvefibhHBZq3fL85hQ&r=n9HCCtgqDPssu5vpqjbO3q4h2g6vMeTOp0Ez7NsdVFM&m=MZI9f10DItGo_QZKahsYAsRnXqQ6F2uY5DjLErMRYrs&s=dcX6EMFrh3OpCvlcSanuyVASuUO7xrYdtaYUZmqlOR4&e=>
> to reach more people out there? Thanks! 😸
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_IQSS_dataverse_issues_5373-23issuecomment-2D445148599&d=DwMFaQ&c=WO-RGvefibhHBZq3fL85hQ&r=n9HCCtgqDPssu5vpqjbO3q4h2g6vMeTOp0Ez7NsdVFM&m=MZI9f10DItGo_QZKahsYAsRnXqQ6F2uY5DjLErMRYrs&s=qdJY7L-P8c7MXyeR5_boSD9gr_gWBehHh5dAHk5pJiA&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AApQyAYHSbAj2FxrfxT2JUbI9dA-5FRXJ3ks5u2hq-2DgaJpZM4ZFW7K&d=DwMFaQ&c=WO-RGvefibhHBZq3fL85hQ&r=n9HCCtgqDPssu5vpqjbO3q4h2g6vMeTOp0Ez7NsdVFM&m=MZI9f10DItGo_QZKahsYAsRnXqQ6F2uY5DjLErMRYrs&s=45NUOdp-uLZSpMOvrMZ0lGcGEQQaHYtgPxyjzyf-yds&e=>
> .
>


-- 
Mercè Crosas, Ph.D., Chief Data Science and Technology Officer, IQSS, Harvard
University
mcrosas@g.harvard.edu | @mercecrosas <https://twitter.com/mercecrosas> |
scholar.harvard.edu/mercecrosas

**Comment by 4tikhonov** [comment]
We're deploying multilingual DataverseEU instance on Google Cloud (demo server) and ready to share our experience with deployment on Kubernetes:
https://github.com/IQSS/dataverse-docker/tree/master/kubernetes

**Comment by skasberger** [comment]
I am interested too.

**Comment by poikilotherm** [comment]
Dear community,

thank you for your interest on the topic of running Dataverse in Docker and/or Kubernetes.

To have some kind of agenda to talk about in a call, I ask everybody to add comments and/or suggestions to https://docs.google.com/document/d/13h4zra_ugYH5IKMkj5tya1NwaFdC2FfWXBmGUxxAdn8, including your nick/name.
If something you are keen to talk about is already present, just put your nick/name next to the other/s, so we can see what is important to you.

I am eager to setup a poll for a timeslot for a call, but there is a chance that we could use next weeks community call and stay a little longer (if it takes place because of holidays). Please share your preferences if this doesn't fit.

Cheers!
Oliver

**Comment by pdurbin** [comment]
> there is a chance that we could use next weeks community call

This morning @djbrooke and I spoke about next week's community call on December 18th and we do plan to have it. (For anyone reading this who is unfamiliar with our community calls, please see https://dataverse.org/community-calls .) We like your idea of having those interested in discussing this issue to stay a little longer on the call.

@poikilotherm please keep us posted on if you'll be sending a poll or using a community call. We appreciate all the organizational legwork you've done already!

**Comment by thaorell** [comment]
Hi all, I would love to attend but I have a final exam on the 18th and I would not be able to attend 
@pdurbin

**Comment by vsoch** [comment]
I don't have the bandwidth to add another project right now, sorry @poikilotherm !

**Comment by poikilotherm** [comment]
> @poikilotherm please keep us posted on if you'll be sending a poll or using a community call. We appreciate all the organizational legwork you've done already!

Then let's just reuse the regular community call for now. Depending on the echo from it maybe a separate call can be setup for next year... :wink:

**Comment by poikilotherm** [comment]
Happy New Year everyone :smile: 

The discussion from the call is logged here: https://docs.google.com/document/d/13h4zra_ugYH5IKMkj5tya1NwaFdC2FfWXBmGUxxAdn8/edit

To paraphraze: people around in the call primarily seemed interested in production usage of Dataverse on Docker and Kubernetes. Just [yesterday pmauduit was asking on IRC](http://irclog.iq.harvard.edu/dataverse/2019-01-02#i_83592) about using it for dev purposes, too.

Any feedback you are willing to provide here or in other places is very much appreciated. I would love to hear from you :smile:

**Comment by poikilotherm** [comment]
Cleaning up old issues. Since this was initially writen, things are moving in [IQSS/dataverse-kubernetes](https://github.com/IQSS/dataverse-kubernetes).

Please follow up there if you are interested. Closing this.
