### ISSUE TITLE
Persisted id (doi) for files are using test prefixes instead of production one.

### ISSUE THREAD

**Issue by flaviofrancisco** [IQSS/dataverse#5375]
We have a published doi on the following link: 
http://dataverse.nioz.nl:8080/dataset.xhtml?persistentId=doi:10.25850/nioz/7b.b.f

But the files related to that doi has a test prefix (10.5072)
http://dataverse.nioz.nl:8080/file.xhtml?persistentId=doi:10.5072/nioz/7b.b.f/F0FIDK&version=4.0

It should be 10.25850, should it not be?

We upload files using the following url: 
http://dataverse.nioz.nl:8080/dvn/api/data-deposit/v1.1/swordv2/edit-media/study/doi:10.25850/nioz/7b.b.f

I also tried to do directly throughout the web interface and I ended up with the same result.

Is there any setting that we are missing in our environment in order to have the correct code on the production DOIs files?

Thanks;
Flavio Francisco.

**Comment by pdurbin** [comment]
@flaviofrancisco hi! I guess the first question I have is if you want DOIs for files or not. They're optional as of Dataverse 4.9.3 (and I see you're running 4.9.4): http://guides.dataverse.org/en/4.9.4/installation/config.html#filepidsenabled

@sekmiller and I just looked at your settings (please block this) and you have "10.5072" configured for ":Authority" so if you create a new dataset right now, it will get "10.5072". You should change ":Authority" to "10.25850". We're confused how you got the mix you did. Maybe you created a few datasets while configured with "10.25850" and then someone switched it back to "10.5072" when you weren't looking and then when you published the dataset, the files got "10.5072". Unlike datasets, files only have database IDs until publish is clicked, at which point files get DOIs.

I hope this helps!

**Comment by flaviofrancisco** [comment]
Thanks @pdurbin! I just blocked the admin api.

Regards;
Flavio.
