### ISSUE TITLE
Can't delete partially created zombie dataset

### ISSUE THREAD

**Issue by mdmADA** [IQSS/dataverse#5376]
DV 4.6.1

I was using the API to create a dataset in a sub-dataverse of our production Dataverse installation.

The postgres database was configured for less than half the db connections than Dataverse was configured for. As a result, when I tried to create the dataset, Dataverse couldn't get a connection and somewhere down the line crashed.  (We fixed the connection issue btw by setting the number of postgres connections to 2X the number of outgoing Dataverse connections and handing it more RAM).

After rebooting dataverse, I am now left with a partially created zombie dataset that shows as Draft in the main page UI. If I click on the dataset, dataverse crashes. It seemingly has a DOI according to the UI view. However, when I tried the API to delete it using this doi, the API returned an error stating a dataset with that DOI does not exist.

When I went to the sub-dataverse that contained this 'dataset', the dataset was listed as belonging to it. So I deleted the sub-dataverse - which did work - hoping it would get rid of this dataset but the dataset is still showing in the main page UI view.  I recreated the sub-dataverse but the dataset does not appear within it (which I expected).

So, I am not sure how to get rid of this now and I can't leave it as somebody might inadvertently click on it and crash Dataverse. I assume I'll have to delete from the database itself (never fun). 

Can I get a list of the tables that I would have to check/delete from, and the order, to get rid of this zombie dataset? It's just the dataset and metadata, no data files.

Or is there something else I can try?

**RESOLUTION:** Running a "reindex all" as suggested by @scolapasta (see issue trail below) removed the zombie dataset from the UI. There may be remnants of the dataset left in the database but they will be left as is as long as they don't cause any further problems.
Thanks!

**Comment by pdurbin** [comment]
@mdmADA yikes! Just clicking the zombie datasets crashes the entire web app for everybody? Very strange. My first thought is that you should try to delete the dataset via API. This is documented here: http://guides.dataverse.org/en/4.9.4/api/native-api.html#delete-dataset

You could also use the "destroy" form which isn't documented but you can find an example in #2593.

Either way is safer than hacking on the database but you can find some information about related tables at http://phoenix.dataverse.org/schemaspy/latest/tables/datasetversion.html (the dataset is a dvobject). Please see also http://guides.dataverse.org/en/4.9.4/developers/tips.html#database-schema-exploration

**Comment by scolapasta** [comment]
@mdmADA From the symptoms above, it sounds to me as if the dataset was *not* created. That would explain why the API says it cannot find it and why you could delete the owning dataverse.

The fact that it is still showing means that it is still in the index. I'm actually not sure if we have any way to clean up an "orphan" from the index, but you could run an index all (clean).

**Comment by mdmADA** [comment]
Thanks for the feedback/advice.

@pdurbin - I probably misspoke when I said it crashed dataverse - when I clicked on it, Dataverse stopped responding but it might have been due to the original underlying db connection issue that caused its zombie status in the first place. But I am unwilling to click on it again to see what happens... I did try the API to delete it but the API returned an error message saying the dataset doesn't exist.

@scolapasta - Our sysadmin will reindex all at some point in the next few days and we will see if that gets rid of it from the UI anyway.

Thanks!

**Comment by mdmADA** [comment]
Just an update - our sysadmin ran a "reindex all" and it seems to have done the trick - the zombie dataset is no longer showing in the dataverse UI as far as I can tell. So something to keep in mind if this happens to anybody else.

Thank you for assisting, @pdurbin and @scolapasta...

**Comment by pdurbin** [comment]
@mdmADA cool. Do you want to close this issue? Or is there something you have in mind you want to add to the code or docs?

**Comment by mdmADA** [comment]
I am not sure where in the docs to add a line about reindexing to get rid of a zombie dataset. And is it necessary to add it seeing as how this seems to be the first instance of such a thing happening?

It might be enough to close it with an obvious resolution statement wrt how to 'fix' the zombie dataset by reindexing.

**Comment by pdurbin** [comment]
@mdmADA sounds fine. You can always open a fresh issue in the future if something like this comes up again, especially if the error is easily reproducible. Thanks!
