### ISSUE TITLE
Migration Script - metadata bug (softwareName)

### ISSUE THREAD

**Issue by johnhuck** [IQSS/dataverse#5381]
When we migrated from 3.6 to 4.0, we discovered two metadata mapping errors in the scripts, which were captured in the following two issues:

- https://github.com/ualbertalib/dataverse/issues/45
- https://github.com/ualbertalib/dataverse/issues/50

I believe the first issue has already been [flagged](https://github.com/IQSS/dataverse/issues/3323). The second issue pertains to the element softwareName, which was not coming over. Hope this helps! Sorry for the delay in sharing.

**Comment by pdurbin** [comment]
@johnhuck no worries on the delay. Thanks for letting us know!

**Comment by djbrooke** [comment]
@johnhuck - thanks for the report here. I'm going to close this out as almost all installations have migrated from 3.x and we don't plan to address migration issues since the benefit would be small.
