### ISSUE TITLE
Internationalization - Duplicate "html", "head" tags, broken 403, 404, 500 pgs after #5299 was merged

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#5400]
After pull request #5299 was merged DatasetsIT.testPrivateUrl started failing.

Here's a screenshot:

<img width="1421" alt="screen shot 2018-12-13 at 6 34 38 pm" src="https://user-images.githubusercontent.com/21006/49974107-cfbd2900-ff05-11e8-84be-d0cdd1b99518.png">

https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-apitest-develop/306/edu.harvard.iq$dataverse/testReport/edu.harvard.iq.dataverse.api/DatasetsIT/testPrivateUrl/

**Comment by pdurbin** [comment]
It's failing at https://github.com/IQSS/dataverse/blob/ce30a4f523ae82bf4f5e70e1f2a6c8464684dd62/src/test/java/edu/harvard/iq/dataverse/api/DatasetsIT.java#L772

with

`Caused by: java.lang.IllegalArgumentException: Unsupported assignee identifier 'doesNotExist'
	at edu.harvard.iq.dataverse.RoleAssigneeServiceBean.getRoleAssignee(RoleAssigneeServiceBean.java:91)`

at https://github.com/IQSS/dataverse/blob/ce30a4f523ae82bf4f5e70e1f2a6c8464684dd62/src/main/java/edu/harvard/iq/dataverse/RoleAssigneeServiceBean.java#L91

**Comment by pdurbin** [comment]
These lines are failing...

        String title = getDatasetAsUserWhoClicksPrivateUrl.getBody().htmlPath().getString("html.head.title");
        assertEquals("Darwin's Finches - " + dataverseAlias, title);

... because we have two "html" tags on our dataset page:

![screen shot 2018-12-14 at 1 29 34 pm](https://user-images.githubusercontent.com/21006/50020583-650efa80-ffa4-11e8-9b9b-c557ba8da9cb.png)

This is obviously not great. @djbrooke and @kcondon I'd like to flag this as a show stopper for releasing 4.10.

**Comment by pameyer** [comment]
@pdurbin I don't think this is due to having two html tags - the first one you've flagged is the doctype.

I think the problem is that the opening `<html>` tag is before the `<head>` tag; so the DOM doesn't have a valid `<title>`.

For what it's worth, I'd also vote to flag this as a show-stopper.

And point out that https://github.com/IQSS/dataverse/issues/4855 is relevant to these types of things.

**Comment by djbrooke** [comment]
Yes, we should get this cleared up before releasing 4.10.

**Comment by pdurbin** [comment]
Some more screenshots that might help us diagnose:

![screen shot 2018-12-14 at 1 41 20 pm](https://user-images.githubusercontent.com/21006/50021045-d00d0100-ffa5-11e8-8283-69e9a2bffaff.png)
![screen shot 2018-12-14 at 1 40 54 pm](https://user-images.githubusercontent.com/21006/50021046-d00d0100-ffa5-11e8-89bf-65b2efcca78c.png)

![showing_results_for_phoenix dataverse org_dataset xhtml_persistentid doi_10 5072_fk2_zvoxq9_-_nu_html_checker_-_2018-12-14_13 39 28](https://user-images.githubusercontent.com/21006/50021049-d7340f00-ffa5-11e8-8e89-e57adc9d254f.png)

**Comment by pameyer** [comment]
Further investgation shows that the  structure for the dataset page (as of 88c2494009990c9b4f7403d526fe09a39e3813e5) is roughtly `<head>$stuff</head>` `<body></body>` `<html><head>$stuff</head><body>$stuff</body></html>`

So it appears that some JSF magic is adding both an additional `<head>` , and empty `<body>` outside of the `<html>` element.

**Comment by kcondon** [comment]
weird, it seemed to work when I tested it in that branch. I actually cannot build /develop right now:
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /var/lib/jenkins/workspace/Dataverse_rfi/src/main/java/edu/harvard/iq/dataverse/FileDownloadHelper.java:[307,58] cannot find symbol
  symbol:   method localize(java.lang.String)
  location: variable JH of type edu.harvard.iq.dataverse.util.JsfHelper

**Comment by pdurbin** [comment]
I just made pull request #5405 to get DatasetsIT.testPrivateUrl passing again but I suspect that by undoing some of the work in pull request #5299 that #5202 will need to be re-opened. The "fix" is to remove `<f:view locale="#{dataverseLocaleBean.localeCode}">` from the XHTML files that the API test suite cares about (mostly it's checking JSON and XML output, not HTML). @JayanthyChengan @mheppler and @scolapasta will have a better idea of what a better fix might be. Please note that I did not remove `f:view` everywhere. The pull request is mostly just to illustrate how the extra html start tags are being introduced. If we need to remove `f:view`, we should do so on all pages. `f:view` was added all over the place in pull request #5299.

@kcondon yes, please see #5403 about how the code doesn't compile on develop. Pull request #5404 is a fix to get the code compiling again.

**Comment by pameyer** [comment]
#5405 also gets the dataset page back to the usual amount of html validation errors for the dataset page.

dataverse page appears to have a similar problem with multiple `<head>` elements.

I'd assume that seriously invalid / non-parsable html being generated will cause problems with the various discoverability stuff (json-ld, meta tags, etc) features, so it may be worth a little more investigation.

**Comment by pdurbin** [comment]
@pameyer yes, I'm sorry but I was confused earlier when I said the multiple `<head>` elements are only on the dataset page. It's all pages. I spoke with @scolapasta and @kcondon about it.

**Comment by pdurbin** [comment]
Just a heads up that stage 2 of phoenix tests are failing as well because of the invalid HTML:

```
-:7: parser error : Extra content at the end of the document
</script></head><body></body><html xmlns="http://www.w3.org/1999/xhtml" lang="en
```

Here's a screenshot from https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-deploy-develop/335/console

![screen shot 2018-12-18 at 10 31 00 am](https://user-images.githubusercontent.com/21006/50164140-e66dd200-02af-11e9-8a5e-a850a1158de8.png)

**Comment by mheppler** [comment]
Expanded this issue to include the broken 403, 404 and 500 pgs reported in #5408.

![screen shot 2018-12-18 at 10 21 24 am](https://user-images.githubusercontent.com/2364928/50163644-e4574380-02ae-11e9-9023-5bf066a6a1f2.png)

Just checked those on the `4403-guest-publish-msgs` branch, compared to `develop` and the properly formatted error msg alerts have returned to the UI.

![screen shot 2018-12-18 at 12 09 45 pm](https://user-images.githubusercontent.com/687227/50170396-d3fa9500-02bd-11e9-85ed-466f9e07b78f.png)

**Comment by mheppler** [comment]
In an attempt to blame ALL strange things in `develop` on the `f:view` tags... I give you the strange border/box-shadow that seems to appear around the tabs on various pages...

![screen shot 2018-12-18 at 2 10 10 pm](https://user-images.githubusercontent.com/687227/50176967-cd284e00-02ce-11e9-8245-eef0c9aad221.png)

These have disappeared in this new branch... [Twilight Zone theme music...]

To be fair, I have noticed these in the internationalization branches, but could not pinpoint the cause. In attempt to finally put an end to them now that they appeared in `develop`, I took to this branch to sneak a quick fix in, only to discover they were no longer there!
