### ISSUE TITLE
With latest from Dev, my local Dataset page is broken

### ISSUE THREAD

**Issue by sekmiller** [IQSS/dataverse#5408]
![screen shot 2018-12-18 at 10 21 24 am](https://user-images.githubusercontent.com/2364928/50163644-e4574380-02ae-11e9-9023-5bf066a6a1f2.png)

Seems to be related to adding the localeCode via the dataverseLocaleBean

**Comment by mheppler** [comment]
@sekmiller, et al, I have been seeing this error fairly regularly on my localhost, but still intermittently. Mostly on the internationalization branches. No idea why.

@JayanthyChengan have you seen this on your dev environment at all?

I believe this too is also a symptom of the problems reported in #5400 with the new `f:view` tags. Something to keep track of now that we've backed those changes out.

**Comment by sekmiller** [comment]
So, running the sql update for adding original file size to the datafile table "fixed" my dataset page. I've never seen an out of date data table error manifest itself this way.

**Comment by mheppler** [comment]
I have confirmed that the changes in PR #5407 fix all the broken 403, 404 and 500 error pgs that were reported above.

**Comment by pdurbin** [comment]
For the record, as I mentioned at standup, I saw this problem on my laptop too until I ran the SQL script update in pull request #5390.
