### ISSUE TITLE
Make a Custom 500 Error page

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#541]
---

Author Name: **Raman Prasad** (@raprasad)
Original Redmine Issue: 3957, https://redmine.hmdc.harvard.edu/issues/3957
Original Date: 2014-05-08

---

Create a dataverse branded 500 error page -- or at least not the default glassfish 500 Error page.

**Comment by scolapasta** [comment]
@mheppler can you create the page, then assign to Bob to wire up via web.xml?

**Comment by mheppler** [comment]
Created new 500 error page, to be wired up into the app.

**Comment by rtreacy** [comment]
500.xhtml has been wire up in web.xml

**Comment by eaquigley** [comment]
500 page is wired up and appears. Need to talk to @mheppler about the message appearing on this page. Will close ticket once that is resolved.

**Comment by kcondon** [comment]
OK, I've seen this error in the app but there is one 500 error not captured: the dreaded weld 500 error. I think that issue can be handled separately and this ticket can be closed. Closing.
