### ISSUE TITLE
Advanced Search: make File Type a dropdown driven by uploaded data

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#543]
---

Author Name: **Philip Durbin** (@pdurbin)
Original Redmine Issue: 3959, https://redmine.hmdc.harvard.edu/issues/3959
Original Date: 2014-05-08
Original Assignee: Philip Durbin

---

In #3745 we added File Type as a field you can search on but we didn't get around to making it a dropdown driven by the data that has been uploaded in the system. That is to say, you'd see the file types that were uploaded, such as PDFs, RData, etc. in the dropdown but you wouldn't see file types that hadn't been uploaded.

---

Related issue(s): #330
Redmine related issue(s): [3745](https://redmine.hmdc.harvard.edu/issues/3745)

---

**Comment by pdurbin** [comment]
> Author Name: **Philip Durbin** (@pdurbin)

This was my idea and I still like it but we have other priorities. Closing.

If anyone reading this wants this, please feel free to create a fresh issue!
