### ISSUE TITLE
Reconsider how we delete draft files from Solr

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#544]
---

Author Name: **Philip Durbin** (@pdurbin)
Original Redmine Issue: 3960, https://redmine.hmdc.harvard.edu/issues/3960
Original Date: 2014-05-08
Original Assignee: Philip Durbin

---

In #3795 we started deleting Solr docs for files based on a query like this:

```
q=parentid:16&fq=id%3A*_draft

```

See https://github.com/IQSS/dataverse/blob/ebc5163856830b3a3f6ad95fdd0093daeaf93e25/src/main/java/edu/harvard/iq/dataverse/IndexServiceBean.java#L972

Instead, perhaps we should figure out this list from the database, from the datasetVersion.

---

Related issue(s): #380
Redmine related issue(s): [3795](https://redmine.hmdc.harvard.edu/issues/3795)

---

**Comment by pdurbin** [comment]
I have a fix for this ready to merge into master at https://github.com/IQSS/dataverse/issues/1734#issuecomment-84993693 once master can compile. I'll change the milestone to the current one.

**Comment by pdurbin** [comment]
I just merged 43911e4 into master. As of that commit we no longer use a Solr query to identify which draft versions of files should be deleted from Solr. (We now use database calls instead.) I would say as long as #1734 is fixed it's safe to close this ticket. Passing to QA.

**Comment by kcondon** [comment]
#1734 fixed, closing.
