### ISSUE TITLE
Include Counter Processor in Dataverse installation procedure for Make Data Count support

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#5440]
@matthew-a-dunlap @sekmiller and I have been discussing that our working plan is to require the installation of Counter Processor ( https://github.com/CDLUC3/counter-processor ) in order for Dataverse to support Make Data Count.

Here's a preliminary diagram that shows where Counter Processor fits in our architecture:

![mdc-arch](https://user-images.githubusercontent.com/21006/50841935-c02dd600-1333-11e9-87ed-2ecbe742b6e6.png)

Source for the diagram above: https://github.com/IQSS/dataverse/blob/b60a679723c0905de3a9e0dbeebad04c2f81f9cd/doc/sphinx-guides/source/admin/img/make-data-count.uml

I chatted with @donsizemore this morning at http://irclog.iq.harvard.edu/dataverse/2019-01-08#i_84180 and he's planning on helping add Counter Processor into Ansible scripts: https://github.com/IQSS/dataverse-ansible/issues/33

**Comment by pdurbin** [comment]
Now that I think of it, #5385 is almost the same as this issue. Or maybe it's stage 2 of that issue.

**Comment by pdurbin** [comment]
I just showed @landreev that pages I've made so far:

- http://guides.dataverse.org/en/4821-make-data-count/admin/make-data-count.html
- http://guides.dataverse.org/en/4821-make-data-count/developers/make-data-count.html

We decided that we'll treat Counter Processor like Solr in the sense that we will simply document on the Prerequisites of the Installation Guide the steps that must be taken to install Counter Processor.

@donsizemore please note that in the dev guide I talk about how we are using the Ansible code you wrote in https://github.com/IQSS/dataverse-ansible/issues/33 for development purposes. Thank you!

**Comment by pdurbin** [comment]
I wouldn't mind some feedback on what I wrote at 0b185f0 so I'm moving this to code review.

**Comment by landreev** [comment]
This looks good. 
As discussed/agreed, I'm closing this issue (there's no PR yet). But yes, I agree that this should be sufficient to document it like this.
