### ISSUE TITLE
as a system administrator, I'd like glassfish to not throw exceptions from (from dataverseuser.xhtml) during normal operations

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#5446]
One example of the general principle: `curl -I -X GET "${DATAVERSE_HOST}/dataverseuser.xhtml?editMode=foo"` shouldn't result in a http 500 error / `IllegalStateException`.

There are a variety of other cases that appear to result in additional `IllegalStateException`s (and `EJBException`s), but more information needs to be developed on those.

**Comment by pameyer** [comment]
Another example: `curl -X GET -I "${DATAVERSE_HOST}/dataverseuser.xhtml?javax.faces.ViewState=-1006817140300558635:-185982852916731803" triggers `ViewExpiredException` , leading to another `IllegalStateException` (same parameter results in same exceptions on other pages).

**Comment by foobarbecue** [comment]
FWIW, I don't get a 500 error, I get a 200 with partially rendered page.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
