### ISSUE TITLE
Homepage Count Updates

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#5447]
- [x] Search input watermark dataset count (27400) is off by 53,827 compared to "Datasets (81,227)" facet (Expect to be a count of all dataverses and datasets that will be searched – including Harvested)
- [x] Browse by subject # expected to be dataverses+datasets including harvested
- [x] Allow queries for all datasets (harvested + native), as well as datasets harvested and files harvested. This really means implementing an ability to specify harvested or both for all (file/dataset) metrics.

**Comment by matthew-a-dunlap** [comment]
As per discussion with @TaniaSchlatter , our metrics need to provide values for harvested / non-harvested . 
<img width="920" alt="50990068-168b4800-14df-11e9-9bd6-d5c68be91f88" src="https://user-images.githubusercontent.com/8901015/50990895-518e7b00-14e1-11e9-8b0e-a5d4d33c00ef.png">

**Comment by matthew-a-dunlap** [comment]
Code Todo:
[ ] Add admin command to clear caches (needed with metric renaming happening)
[ ] Add query param to all metrics to specify local/remote/all (default is local for backwards compatibility)

**Comment by djbrooke** [comment]
Closing in favor of #5445. Will do some group design QA and stakeholder verification in that issue.
