### ISSUE TITLE
Some datasets showing up as links after manually changing "root" dataverse - remove hard coded value of 1

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#5454]
Reported by Sherry Lake from UVA:

After changing which dataverse was the "root" (by giving the original root a parent, and removing the parent from another dataverse), some datasets are improperly showing up as linked.

From the Google group:
https://groups.google.com/forum/?hl=en#!topic/dataverse-community/x042DsIk3-I

**Comment by scolapasta** [comment]
I looked in the code a bit and there is a line where the root dataverse is hard coded to id of 1.
In SearchIncludeFragment.java, line 1236 (additional lines provided for context):

  // determine which of the objects are linked:
        
        if (!this.isRootDv()) {
            // (nothing is "linked" if it's the root DV!)
            Set<Long> dvObjectParentIds = new HashSet<>();
            for (SolrSearchResult result : searchResultsList) {
                if (dataverse.getId().equals(result.getParentIdAsLong())) {
                    // definitely NOT linked:
                    result.setIsInTree(true);
                *} else if (result.getParentIdAsLong() == 1L) {*
                    // the object's parent is the root Dv; and the current 
                    // Dv is NOT root... definitely linked:
                    result.setIsInTree(false);
                } else {
                    dvObjectParentIds.add(result.getParentIdAsLong());
                }
            }
            ...

**Comment by scolapasta** [comment]
Please note: 
This may not be the exact cause of Sherry's issue (since the dataset's parent in question is not the former root), but this bug could still be indirectly causing the problem. 

It would still be good to fix this and see the resultant effect it has on Sherry's test setup.

**Comment by scolapasta** [comment]
One last note and why I'm not convinced this will definitely fix Sherry's issue:
In her case the dataset that is incorrect has a parent id of 281. So even though the root is no longer id of 1 (it is id of 23313), this if statement would still return false.

(similarly there is a dataset that has a parent id of 13, in the same structure and that was does not show up as linked.)

In fact if it *had* been 1, then the previous statement would have caught it (since these results are being shown from the grandparent, which is the former root and does have id of 1) and so isInTree would be set to true)

**Comment by shlake** [comment]
@scolapasta, I see that this is closed, but wanted to add a little more info in case there may be another reason for the "link" icon displaying.

Here's the solr info for a dataset that shows a link - am wondering what the "subtreePaths" field means and why do they all start with "/1"? But this may not be a problem for the link icon display, as the datasets that don't show a link also have "subtreePaths" starting with "1".

{ 
        "id":"dataset_233276",
        "entityId":233276,
        "dataverseVersionIndexedBy_s":"4.9.3",
        "identifier":"doi:10.5072/FK2/HTWQIH",
        "dsPersistentId":"doi:10.5072/FK2/HTWQIH",
        "persistentUrl":"https://doi.org/10.5072/FK2/HTWQIH",
        "dvObjectType":"datasets",
        "dateSort":"2017-09-26T12:47:09.719Z",
        "dateFriendly":"Sep 26, 2017",
        "publicationStatus":["Published"],
        "publicationDate":"2017",
        "dsPublicationDate":"2017",
        "isHarvested":false,
        "metadataSource":"University of Virginia Dataverse",
        "datasetVersionId":22733, 
        "citation":"Lake, Sherry, 2017, \"Chemistry test on Tuesday\", https://doi.org/10.5072/FK2/HTWQIH, University of Virginia Dataverse, V1, UNF:6:zB8EFDq5PgotjJzjUjp3Yw== [fileUNF]",
        "citationHtml":"Lake, Sherry, 2017, \"Chemistry test on Tuesday\", <a href=\"https://doi.org/10.5072/FK2/HTWQIH\" target=\"_blank\">https://doi.org/10.5072/FK2/HTWQIH</a>, University of Virginia Dataverse, V1, UNF:6:zB8EFDq5PgotjJzjUjp3Yw== [fileUNF]",
        "dateOfDeposit":"2017",
        "dateOfDeposit_s":"2017",
        "nameSort":"Chemistry test on Tuesday",
        "title":"Chemistry test on Tuesday",
        "depositor":"Lake, Sherry",
        "subject":["Chemistry"],
        "subject_ss":["Chemistry"],
        "productionDate":"2011",
        "productionDate_s":"2011",
        "authorName":["Lake, Sherry"],
        "authorName_ss":["Lake, Sherry"],
        "affiliation_ss":["University of Virginia"],
        "authorAffiliation":["University of Virginia"],
        "authorAffiliation_ss":["University of Virginia"],
        "datasetContactName":["Lake, Sherry"],
        "dsDescriptionValue":["never can have enough tests"],
        "subtreePaths":["/1",
          "/1/281"],
        "parentId":"281",
        "parentName":"Department of Chemistry",
        "_version_":1623014453397159936}

**Comment by pdurbin** [comment]
@shlake hi! "subtreePaths" is a Solr field we use to enumerate all the places where a dataverse, dataset, or file should exist within the tree structure of a dataverse installation. In the example above...

    "subtreePaths": [
        "/1",
        "/1/281"
    ]

... the dataset is with the "281" dataverse as well as the parent of "281", which is "1". If this were a Unix file system, it might look something like this:

    /libradata/chemistry/dataset1.txt

The wrinkle with regard to linking is that as you link this dataset to more and more dataverses, you will see the list under "subtreePaths" grow. For example, if you link it to two more dataverses, the new list could look something like this (if you linked the dataset to "42", a dataverse directly under the root dataverse, and "66", a dataverse two levels deep):

    "subtreePaths": [
        "/1",
        "/1/281",
        "/42",
        "/17",
        "/17/66",
    ]

The idea is that if you navigate to any of the dataverses that correspond to numbers above, the dataset will be within that part of the tree. If these were Unix symlinks, you could find the same file in multiple locations, perhaps like this:

    /libradata/chemistry/dataset1.txt
    /biology/dataset1.txt
    /awesome/biochem/dataset1.txt

One more time, with numbers:

    /1/281/dataset1.txt
    /42/dataset1.txt
    /17/66/dataset1.txt

I sure hope this is helping. 😄
