### ISSUE TITLE
Authentication between Dataverse and Whole Tale

### ISSUE THREAD

**Issue by craig-willis** [IQSS/dataverse#5455]
This issue is intended primarily for discussion about improving the user experience between Dataverse and Whole Tale via the [external tools integration](https://github.com/IQSS/dataverse/issues/5097).

## Problem: 
As noted in https://github.com/IQSS/dataverse/issues/5097#issuecomment-453191563, when using the Whole Tale external tool integration user experience will be better if they are already logged in to Whole Tale.  Whole Tale currently supports Oauth2 via Globus Auth which supports InCommon (via [CILogon](https://www.cilogon.org/news/globus-auth)], Google, and ORCID.  Dataverse supports Shibboleth and Oauth2 (ORCID, Github, and Google) in addition to basic username/password authentication.

The experience for a particular Dataverse installation will depend on the local authentication configuration. If the installation uses username/password, then the user will necessarily need to login to WT using alternative credentials. It might be possible to support a more seamless experience via either ORCID or Globus Auth (Oauth2).  (Note that ORCID is also required by DataONE for WT integration).  

Note that this issue is related to but different from https://github.com/whole-tale/whole-tale/issues/53, which discusses how a WT user can authenticate into Dataverse once we've implemented publishing capability.  At this time, the publish feature would leverage Dataverse API tokens (i.e., the WT user would need to configure the Dataverse API token to publish).

**Comment by pdurbin** [comment]
Yesterday I mentioned this issue to @blewis because he and I have talked on and off for years about how to improve auth between Dataverse and WorldMap: http://guides.dataverse.org/en/4.11/admin/integrations.html#worldmap

**Comment by pdurbin** [comment]
@djbrooke just clicked "Explore" from Dataverse and landed on Whole Tale (thank you @donsizemore for https://github.com/IQSS/dataverse-ansible/issues/59 !!!), went through the Whole Tale sign up process with HarvardKey (Shibboleth/InCommon) and the file id (7, if memory serves, I don't have screenshots) came through ok on the Whole Tale side.

@craig-willis I guess what I'm trying to say is that the experience was relatively seamless. Way less rocky than I expected. I'm glad you have high standards but maybe you can try it out and let me know what you think? The Whole Tale button is currently enabled at http://ec2-3-81-98-96.compute-1.amazonaws.com:8080

If you're not available right now right now and that ec2 instance is gone, please just ping me and I'm happy to spin up a new one. Or you can if you want to try out new fancy dancy "spin up Dataverse" scripts at http://guides.dataverse.org/en/4.12/developers/deployment.html

You'll need the latest "main.yml" to enable the Whole Tale button and this is how you run the script: 

`ec2-create-instance.sh  -g main.yml`

**Comment by pdurbin** [comment]
@craig-willis now that we're in new decade, what are your thoughts on this issue? 😄 

For a hopefully smoother and more secure alternative to tools like Whole Tale having to tell users to manually retrieve API Tokens from Dataverse, we have this new (unmerged) PR:

- #9001

**Comment by craig-willis** [comment]
Sorry for not replying to your original comment sooner. Time passes...

For public datasets, I agree that the current user experience is acceptable, even if they needs to login to WT with different credentials.

I don't recall why, but apparently we are not (yet) using the `apiToken` parameter for private datasets.  We do currently support setting an API key in WT to import private datasets:

![image](https://user-images.githubusercontent.com/4334350/194890892-0cb81cb8-0b0e-48d6-a325-a9b4dc91ed20.png)

It's good to know that at some point the `apiToken` parameter may be replaced by the signed-url approach.

I think this issue can be closed.

**Comment by pdurbin** [comment]
@craig-willis sounds good. Thanks. I'll go ahead and close this out. Over the summer I flew into O'Hare and as we touched down I was looking for the Big 10 building were we had that great workshop. Let's do it again sometime. 😄
