### ISSUE TITLE
External tools can't see the dataset context

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#5457]
Currently, the external tools interface only sends a reference for the relevant file and a tool can't easily discover which dataset and datasetversion the file is included in, and therefore, if I understand correctly, cannot retrieve the file metadata (name, tags, description) since these are associated with a give filemetadata entry that is specific the dataset version.

For QDR, we wanted to display the dataset name (with a link), and file creation date in the annotation viewing tool, so I extended the external tool interface to allow tools to request the dataset and datasetversion ids from Dataverse for inclusion in the called URL, mirroring the way the fileid, apikey, and siteurl can be requested.

I'll submit a PR so this can be merged in if there's broader interest.

**Comment by pdurbin** [comment]
@qqmyers added documentation in 60f9b10. Thanks!
