### ISSUE TITLE
Support for retrieving and displaying Hypothesis annotations

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#5459]
This is a placeholder issue for discussion: QDR has been using http://hypthes.is to allow researchers to annotate specific parts of published research papers. Those annotations are nominally part of the research record along with the data. With the data stored in Dataverse, QDR wanted a way to retrieve, store, and display these annotations as part of the dataset. @adam3smith can provide more detail on Hypothesis and what QDR has done with it. To support the integration with Dataverse, I've developed code mirroring the dropbox integration to allow a file containing annotations (in json), about a specific source document, and created within a specific group, to be uploaded into Dataverse, and to then use the external tools mechanism, extended as in #5456 and #5457, to create a previewer consisting of a static html page with associated javascript (which could be hosted externally, but which we just add as a resource in the Dataverse webapp).

These capabilities may not be of broad enough interest to include in Dataverse, but if there's interest, I can submit the code and develop documentation. (As with dropbox, the annotation retrieval code only shows if you configure with a hypothesis key, and the tool only appears if you register it as with other tools.). I'm hoping that what QDR has now will be out on the production server in the next few days, which may make it easier to understand what it all looks like...

**Comment by pdurbin** [comment]
@qqmyers I just spoke with @kcondon about #5457 (merged) and #5456 (in QA) and I do think it would be nice to have Hypothesis described as an external tool on a future version of the list at http://guides.dataverse.org/en/4.10.1/installation/external-tools.html#inventory-of-external-tools

The tricky part is that we want the external tool authors to maintain the documentation and I'm not sure if Hypothesis would be open to this or not. Here's an example of how @whole-tale recently updated the list to include their external tool: pull request #5417 . If you know anyone at Hypothesis I'd be happy to chat with them at http://chat.dataverse.org or here or elsewhere about this.

**Comment by qqmyers** [comment]
@pdurbin - This is definitely a tricky one. As of now, the ability to retrieve Hypothesis files is more tightly coupled - like the dropbox integration, while the display 'external tool' is so simple it's just an html template with a javascript. 

The former could potentially be pulled out some if the dropbox-style input became extensible (did the github integration do anything there?). That might at least allow the source to be managed separately (perhaps by Hypothesis) with users just having to drop a jar file in to use it with Dataverse. 

The latter - the display tool - is almost too small to think about hosting externally, but it could be something we could try to push to hypothesis' git repo. (They have similar tools such as a javascript bookmarklet that creates a sidebar on other websites...).

In any case, I'll talk with @adam3smith and see about approaching Hypothesis/thinking about where put the source, etc....

**Comment by adam3smith** [comment]
@judell is in charge of integration at Hypothesis, so would be the first contact for this. I agree that ownership is quite tricky here.

**Comment by qqmyers** [comment]
An update - we spoke with Hypothesis and they're interested in advertising on their equivalent of of the external tools page but are focusing their efforts and repositories on general tools. So the path for the viewer side seems to be having QDR, or the DV consortium or IQSS host a separate repository for the html/css/js. The uploader can't be separated that way unless/until there's a clearer interface for retrieving files form external sources (has/will the github integration generalize what was done for dropbox?). And given that, I think unless there's string interest at this point, I think we just monitor the upload integration side and leave this until then. (Could potentially make a page to retrieve annotations and by entering a DOI and your DV apikey, to push it to DV via the API... that's not quite as slick for the user, but it would be a lighter weight approach unless/until there's a upload integration mechanism.)

**Comment by pdurbin** [comment]
@qqmyers thanks for this update. I saw some emails flying around about an IQSS + QDR Coordination meeting so maybe you can bring this up then? Or during a community call? I'd like to understand more about the clearer interface for retrieving files from external sources. Sounds like a nice feature. 😄

**Comment by djbrooke** [comment]
@adam3smith @qqmyers do the previewers do the trick here, or should we keep this open to track further discussion/work?

**Comment by qqmyers** [comment]
The previewer solves the display side. QDR has implemented an uploaded mechanism modeled on the dropbox input pane to retrieve Hypothesis annotations in the first place, and then store them as a file. This hasn't been integrated with the develop branch. However, given that Hypothesis is not used widely across the community (probably only QDR at present), it might be better to close this issue and just keep the idea of Hypothesis annotations (as richly structured metadata) in mind as metadata changes are contemplated.

**Comment by adam3smith** [comment]
> However, given that Hypothesis is not used widely across the community (probably only QDR at present), it might be better to close this issue and just keep the idea of Hypothesis annotations (as richly structured metadata) in mind as metadata changes are contemplated.

Yes, 100% agree

**Comment by djbrooke** [comment]
Thanks @adam3smith and @qqmyers, I'll close this out.
