### ISSUE TITLE
As a depositor, I want to know why the API to create datasets using DDI xml failed

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#5467]
When I use the API to import a dataset with a DDI xml file (see [section in API guide](http://guides.dataverse.org/en/latest/api/native-api.html#import-a-dataset-into-a-dataverse-with-a-ddi-file)) and the file isn't an xml file or (more likely to happen) if the xml isn't well-formed I get a message that doesn't tell me why the import failed.

The error looks like the html of the 500 server error page.
![screen shot 2019-01-14 at 4 31 05 pm](https://user-images.githubusercontent.com/18374574/51142491-22964300-181a-11e9-9508-dc5985a9119a.png)

**Comment by BPeuch** [comment]
@youssefOuahalou ran into the same problem when I asked him to try out the "Import a Dataset" feature with a DDI file. It worked fine with JSON files, but with DDI it always ends with this rather uninformative 500 error.

One might also wonder if the fact that @jggautier used a .pdf file (as shown on the screenshot) might have had an impact on the procedure, but @youssefOuahalou experienced the same problem with a strictly .xml file.

**Comment by mheppler** [comment]
Related DDI XML improvements in the PR **3648 Change "DVN" to default value "producer" and only write the firs… #7094**.
