### ISSUE TITLE
dial back ec2-create-instance.sh options

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#5468]
per http://irclog.iq.harvard.edu/dataverse/2019-01-15 passing each additional group_var to dataverse-ansible as an extra-var or from an env file gets unwieldly, and phil and i agreed to switch to an optional, external group_vars file for anyone who doesn't want the role defaults.

pull request forthcoming.

**Comment by pdurbin** [comment]
@donsizemore pull request #5470 works perfectly and is helping me move forward with Make Data Count. Merged! Thanks!!
