### ISSUE TITLE
risky legacy methods in MailServiceBean

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#5472]
PR #5134, which added a requestor param to the sendNotification and getMessageTextBasedOnNotification methods left versions of these calls with fewer parameters. These methods are not currently used, but would cause a null pointer exception if used for REQUESTFILEACCESS or SUBMITTEDDS messages. 

The methods are at (https://github.com/IQSS/dataverse/blob/develop/src/main/java/edu/harvard/iq/dataverse/MailServiceBean.java#L212) and created a 3 param version (https://github.com/IQSS/dataverse/blob/develop/src/main/java/edu/harvard/iq/dataverse/MailServiceBean.java#L217
(https://github.com/IQSS/dataverse/blob/develop/src/main/java/edu/harvard/iq/dataverse/MailServiceBean.java#L320) and created a 3 param version (https://github.com/IQSS/dataverse/blob/develop/src/main/java/edu/harvard/iq/dataverse/MailServiceBean.java#L326

I was unable to find any use of them in the app or tests.

**Comment by mheppler** [comment]
Related to **Revisit notifications #1336**.

**Comment by poikilotherm** [comment]
Related to "mail configuration in app" #7424
Some refactoring already done in https://github.com/poikilotherm/dataverse/tree/7424-maildefinition

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
