### ISSUE TITLE
Dataverse Facets - Duplicate French Values Listed (Category, File Type)

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#5473]
In my demo yesterday I noticed one category facet in "french" for one dataverse. When I navigate to that dataverse, that category is not an option in French, as expected and not included anywhere else in the metadata for that dataverse and its dataset. See screen shots. 

<img width="533" alt="screen shot 2019-01-17 at 1 44 59 pm" src="https://user-images.githubusercontent.com/8322346/51341793-287d6580-1a60-11e9-81be-320e72aebffb.png">
<img width="1334" alt="screen shot 2019-01-17 at 1 45 09 pm" src="https://user-images.githubusercontent.com/8322346/51341794-287d6580-1a60-11e9-8aec-ff063d333fc4.png">

**Comment by mheppler** [comment]
There are now three facets in production in French.

```
Chercheur (1)
Groupe de recherche (1)
Projet de recherche (1)
```

With three different dataverses.

https://dataverse.harvard.edu/dataverse/amsre_footprint

**Comment by scolapasta** [comment]
I cleaned up the ones in production by reindexing via admin API. They seemed to have been created in later January / early February. Is it possible we had multiple languages enabled briefly? 

In other words, I didn't do anything about what is likely the underlying cause. but fixing individual one is easy.

**Comment by mheppler** [comment]
Was able to replicate the duplicate translated category values in my localhost.

![Screen Shot 2019-04-02 at 1 18 19 PM](https://user-images.githubusercontent.com/687227/55422632-10d75880-554a-11e9-9aa0-959c99051e17.png)

1. Toggle language to French
2. Create dataverse
3. Publish dataverse
4. Toggle language to English, find French category value listed as duplicate facet

**Comment by mheppler** [comment]
Copied comment from related/duplicate issue that I open and closed.

_Search - French Controlled Vocabulary Facets #5752_

> Found more French facets in [production](https://dataverse.harvard.edu/dataverse/harvard?q=&fq0=fileTypeGroupFacet%3A%22Texte%22&types=files&sort=dateSort&order=desc).
> 
> <img alt="Screen Shot 2019-04-10 at 3 33 42 PM" width="1184" src="https://user-images.githubusercontent.com/687227/55907948-267dfb00-5ba6-11e9-9dcc-3488e5e563f2.png">

**Comment by JayanthyChengan** [comment]
@scolapasta - please review PR https://github.com/IQSS/dataverse/pull/6051
