### ISSUE TITLE
Create/Edit Dataset - Loss of form data when adding a multiple field

### ISSUE THREAD

**Issue by fcadili** [IQSS/dataverse#5477]
While compiling a dataset if you add a multiple field via the plus button all the entered data are deleted.
A simple use case is:

open dataset form selecting New Dataset to insert a new data;
insert title, for instance "Test";
select plus button near Keyword field to add a new one;
now a new form with two keywords fields is shown but the "Test" value of title field is cleared.
The same problem affects all multiple fields.
There is a workaround to avoid data loss: just saving the data with save dataset button before pushing the plus button.

This problem was detected in dataverse version 4.10.1.

**Comment by djbrooke** [comment]
Thanks for the report @fcadili, just confirmed this behavior on demo as well.

**Comment by mheppler** [comment]
This may have changed in 4.10 as part of _Cannot add multiple field to a dataset #5212_ with a commit ec11eeb2138cd12677da843aa93f1a7a51986247 from @sekmiller to the `metadataFragment.xhtml`.

**Comment by mheppler** [comment]
👍

**Comment by mheppler** [comment]
@djbrooke vote for 4.11 release.
