### ISSUE TITLE
Separate metadata entries to be easily distinguishable from one another

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#5481]
I  came across related publication metadata in [this dataset](https://doi.org/10.7910/DVN/DKURGR) with html paragraph breaks in the "Citation" text boxes.

The depositor added the `<p> </p>` html tags, like these...

<kbd>![screen shot 2019-01-18 at 11 25 09 am](https://user-images.githubusercontent.com/18374574/51567222-ad9fba80-1e64-11e9-82dc-7547688de0bc.png)</kbd>

... to make the metadata displayed more readable by creating space between each related publication :

<kbd>![screen shot 2019-01-22 at 4 44 17 pm](https://user-images.githubusercontent.com/18374574/51567915-69151e80-1e66-11e9-80d0-b48aab7ac185.png)</kbd>

Otherwise there are only line breaks, and all three entries look like one block of text, making it hard to tell how many related publications there are and distinguish between the elements in the compound fields.

I see this most often the related publication field, I think because it's the most used among the fields that have large text boxes (so it's more likely that depositors will enter multiple lines of text), where multiple entries are allowed (like multiple related publications), and each entry isn't separated with a paragraph break (like the Description field is).

But [here's another dataset](https://hdl.handle.net/1902.1/19237) with `<p> </p>` in the "related dataset" and "related material" fields used to create space between each entry.

Semicolons are used to separate multiple entries in the "related material" and "related dataset" fields, and in the "unit of analysis" and "universe" fields in the Social Science metadata block.

When the UI separates multiple entries of these metadata fields (and any other fields that use large text boxes), would it be possible to use paragraph breaks instead of line breaks or semicolons?

**Comment by pameyer** [comment]
Another approach might be to wrap each in a `div` or `span` element; that would allow modification of the spacing and possibly a border or different background color for the values.
