### ISSUE TITLE
Error editing dataverse permissions with Postgres 9.3

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#5482]
As of v4.10.1, QDR has been seeing internal server errors when trying to go to the Edit/Permissions page for Dataverses. I tracked this down to the query at https://github.com/IQSS/dataverse/blob/develop/src/main/java/edu/harvard/iq/dataverse/DataverseRoleServiceBean.java#L245 which was updated with #4883. On our instance, the RoleAssignment objects returned from this call have getDefinitionPoint()==null which causes an NPE at line 248. When I tried using the RoleAssignment.listByAssigneeIdentifier_DefinitionPointId query instead, it worked and the RoleAssignment returned has the correct definition point, so from that, and from inspecting the DB, I don't see any problem with our DB contents. 
I'm not able to reproduce this on demo.dataverse.org. Given that, and the fact that the problem is directly with a db query, I suspect that the problem is an incompatibility with our Postgres version (still at 9.3, planning to upgrade) but I don't know this for sure. I did verify that the updated 4.2.2 driver noted in the 4.9.1 release notes does not seem to help.
We'll see if this is resolved after we upgrade. If so, it means v4.10.1 is not compatible with Postgres 9.3 (and perhaps 9.4, 9.5) and the install prerequisites should be updated. If that's not it, there may be some other aspect of our configuration that is an issue. If this affects anyone else, I'd be interested to hear about it.

**Comment by pameyer** [comment]
@qqmyers On a system with postgres 9.3.25 that I just finished upgrading to data verse 4.10.1 , I don't see any internal server errors on the Edit/Permissions (for dataverses) page.  So there may be another factor in play than the postgres version.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
