### ISSUE TITLE
Custom citation (with a different distributor)

### ISSUE THREAD

**Issue by RightInTwo** [IQSS/dataverse#5486]
As a curator, I want to be able to control the text displayed in the citation box wherever it comes up. This could be for the following reasons:

- A dataset is only archived ("unpublished" state) within the institutional repository (our dataverse instance) and thus is not public and cannot be cited. The citation box could be hidden or display "Unpublished archival material of [the institute's name]" as the distributor.
- A dataset is only a reference to an object published somewhere else and the citation must refer to the original source and its required citation style

A nice extension of this would be to have an option to grab a citation directly from https://crosscite.org/.

All the best
Jonas

**Comment by pdurbin** [comment]
My first thought on this is that datasets in Dataverse are meant to be cited. So my brain blows up a little when I read "cannot be cited". 😄 I guess you could create the dataset in Dataverse but then never publish it? That would be weird.

**Comment by RightInTwo** [comment]
Well, the idea of not having a citation at all goes back to our idea of using our dataverse to archive data as well as for published data. For published datasets we want to use the citation provided by the original publisher...

**Comment by RightInTwo** [comment]
Sorry I have to bring this up again.... I managed to use :importddi to get the metadata in for an existing DOI, but the citation is not imported but re-generated.

**Comment by RightInTwo** [comment]
possible duplicate of/overlap with #2297

**Comment by pdurbin** [comment]
> possible duplicate of/overlap with #2297

Yeah. I agree. @RightInTwo are you still interested in this issue. I'm thinking perhaps we should close it as a duplicate of the one you found above.

**Comment by RightInTwo** [comment]
@pdurbin Hi Phil! Same like the other issue: I will just close it, as nobody else has shown interest yet or is covered by the overlapping issue/duplicate...
