### ISSUE TITLE
Notifications - Link published/submit for review dataset to existing/new dataverse

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#5493]
The following feature was requested by @thegaryking in Slack on Jan 28.

>I’d like to add a step to the workflow of journals accepting replication data files and publishing them on dv.  After the editor sends congrats, we’ve published it on dv, I’d like dv itself to automatically ask each author of the file whether (a) they would like the dataset added to their dv if they have one and/or (b) whether they would like a new dv to add to their personal website or project website.  then we can create it automatically for them.  this ought to greatly help the spread of the number of dv’s out there

Right now, dataset authors are sent a notification in the app, as well as an email.

_Published dataset notification, account pg_

![screen shot 2019-01-29 at 9 50 31 am](https://user-images.githubusercontent.com/687227/51916564-92283880-23ab-11e9-9433-132541234b07.png)

_Published dataset notification, contact email_

![screen shot 2019-01-29 at 9 50 58 am](https://user-images.githubusercontent.com/687227/51916616-b1bf6100-23ab-11e9-9155-bf5b5279dd2b.png)

An additional place we could notify the dataset author of these additional actions is on the dataset pg itself, using the alert msg block. There currently is no msg posted when an author visits the recently published dataset for the first time. (The screenshot below is an example of the submitted for review alert msg posted before the dataset was published.)

_Submitted for review warning alert msg, dataset pg_

![screen shot 2019-01-29 at 9 56 12 am](https://user-images.githubusercontent.com/687227/51916890-44600000-23ac-11e9-915e-68543e5f9071.png)

The dataset linking functionality is currently limited to a popup opened from the "Link" btn on the dataset pg. Because of this UI component, we would not be able to provide a text link that lands on the dataset pg with the popup open.

_Link dataset popup, dataset pg_

![screen shot 2019-01-29 at 4 44 49 pm](https://user-images.githubusercontent.com/687227/51943322-31b6ec80-23e7-11e9-98ae-00a7e169049b.png)

**Comment by TaniaSchlatter** [comment]
Reviewed inviting authors to add a published dataset to their dataverse in the email messages the system sends to authors with @thegaryking. 

Gary expects this functionality to be open to all – not permission-based as now with the linking feature. "Adding" a dataset would link it. Gary wants to use the term "add" and not "link" in the UI. Clicking on the "added" dataset in the author's dataverse resolves back to the parent dataverse. 

3 states:

<img width="820" alt="screen shot 2019-02-26 at 4 13 20 pm" src="https://user-images.githubusercontent.com/15386424/53446789-c52d0e80-39e1-11e9-8bb4-4e33f9cf2861.png">

On clicking the link in the email, the system:

1. Pulls dataset category, and description from the user’s account via API to link the dataset to the user’s dataverse.
2. User sees their dataverse with the new dataset added and visible. 
3. Adds a message at the top of the page, stating that the dataset has been added.

<img width="822" alt="screen shot 2019-02-26 at 4 13 27 pm" src="https://user-images.githubusercontent.com/15386424/53446788-c52d0e80-39e1-11e9-931d-ad37ed3cf774.png">
If the author has more than one dataverse, on clicking the link, the system:

1. Records dataverses selected, pulls dataset category, and description from the user’s account via API to link the dataset to the user’s dataverse.
2. User sees their dataverse with the new dataset added and visible. 
3. Adds a message at the top of the page, stating that the dataset has been added. Message could also prompt that they can import their dataverse to their web page (is it a Scholar’s Portal only feature?)


<img width="810" alt="screen shot 2019-02-26 at 4 13 32 pm" src="https://user-images.githubusercontent.com/15386424/53446787-c4947800-39e1-11e9-9937-c3ba47a8243b.png">
If the author does not have a dataverse, on clicking the link, the system:
1. Pulls the user’s information from their account to create a dataverse, and pulls dataset category, and description from the user’s account via API to link the published dataset to the user’s new dataverse.
2. Loads the user’s new dataverse, with the dataset added and visible.  
3. Adds a message at the top of the dataverse page, stating the status of the new dataverse, added dataset, prompting the user to customize the dataverse, and import their dataverse to their web page (is it a scholar’s only feature?

Implications:
How would this work for, or impact other installations? Does the accepted author user have permission to create a Dataverse at the root level?

**Comment by scolapasta** [comment]
After further discussion, these two links:
• Click here to add this dataset to your dataverse
• Click here to create a dataverse and link this dataset to it

will send you to a page on the dataverse app. In the first case, it should send you to the dataset page with the link popup opened (*); in the second it will send you to the create dataverse page with a new parameter (linkid=XXXX) so it can link after creating. (this functionality is being added in #5851)

**Comment by djbrooke** [comment]
Thanks @scolapasta. So this issue would just be adding those email links after the plumbing is set up?

**Comment by TaniaSchlatter** [comment]
The emails should include text about some of the benefits of publishing research (published in a Journal) to your own dataverse.

**Comment by djbrooke** [comment]
Closed in favor of #5874. Will create another issue for fast-create and the prompting mentioned in the above comment.
