### ISSUE TITLE
Point Harvard Miniverse to upgraded (9.6) Postgres instance

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#5497]
The Miniverse installation running dataverse.org/metrics and the map at dataverse.org no longer works, as it was using a DB which has been taken down. 

The map will likely have its own DB.

**Comment by craig-willis** [comment]
Whole Tale currently relies on https://services.dataverse.harvard.edu/miniverse/map/installations-json to get a list of available Dataverse instances to search when users register data by DOI or URL.  We're making a change to fall back to a static list.  We could cache the last retrieved version in the event of future failures -- or maybe it would make sense for Harvard to serve a static version if others depend on this data?

**Comment by landreev** [comment]
Minverse is back to life. 
I have updated Raman's original configuration/maintenance document: "Miniverse/Metrics LTS setup (production)" https://docs.google.com/document/d/1gaML30O0dt2b7VQQ_Si61uF3wMpdmMZk-I7k1yOEkRo/edit

**Comment by djbrooke** [comment]
@craig-willis, as @landreev mentions the application and map are back. Note that the map is missing a few installations, which I'll work with @jggautier to add back in.

**Comment by djbrooke** [comment]
Moving to QA. There does seem to be a big jump in files in October. I don't want to spend too much time digging into this as we'll soon be retiring Miniverse in favor of visualizations powered by the metrics aggregator.
