### ISSUE TITLE
Dataset files table selection counter needs refinement

### ISSUE THREAD

**Issue by TaniaSchlatter** [IQSS/dataverse#5499]
1. File selection counter does not need to show unless there are enough files to paginate the display.
2. File selection counter prompts the user to select all files, even if all files are selected. If all files are selected, the select all prompt should not display. 
<img width="1176" alt="screen shot 2019-01-30 at 3 05 43 pm" src="https://user-images.githubusercontent.com/15386424/52009506-23c5a200-24a1-11e9-8af6-e0a44bdb18b4.png">

**Comment by mheppler** [comment]
1. Added `#{DatasetPage.workingVersion.fileMetadatas.size() gt 1 and (DatasetPage.selectedFiles.size() gt 0)}` render logic to entire dynamic selected files block

![screen shot 2019-02-20 at 2 58 10 pm](https://user-images.githubusercontent.com/687227/53120495-f5773780-351f-11e9-95c8-169b2758bbd9.png)

2. Changed `le` to `lt` to adjust render logic of "Select all {X} files in this dataset" link in dynamic selected files block

![screen shot 2019-02-20 at 2 57 27 pm](https://user-images.githubusercontent.com/687227/53120444-dc6e8680-351f-11e9-9e5b-a2acfaef8323.png)

**Comment by scolapasta** [comment]
@TaniaSchlatter @mheppler  Did a quick review - was the idea to not show if only 1 file or only 1 page of files? I had read it as one page of files, but code change looks like 1 file.

**Comment by TaniaSchlatter** [comment]
Idea was to not show if 1-10 items. The select all option is only needed if there is more than one page.

**Comment by mheppler** [comment]
Fixed.
