### ISSUE TITLE
Show Download URL For Publicly Downloadable Files without PIDs

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#5502]
Download URLs used to be available on a file's Metadata tab if the file met the "ispubliclyDownloadable" criteria (NOT being restricted, NOT having terms of use associated, or NOT being part of a dataverse with a guestbook). In the recent past, it also became required that a File PID be present for the link to display:
 
https://github.com/IQSS/dataverse/commit/77cd617#diff-f11067d071f5a9a337df6ba5056fe96bR365

We should change this so that in cases where a File PID does not exist, a download URL with the File ID is shown, similar to the attached image from NTU's Dataverse running 4.8.6. 
<img width="745" alt="screen shot 2019-01-31 at 2 39 26 pm" src="https://user-images.githubusercontent.com/7773392/52080632-4077dd80-2566-11e9-97b7-5fee60214f10.png">

**Comment by pdurbin** [comment]
In the screenshot below, the line in question as of 960e96f23 in the "develop" branch is 430 about `FilePage.file.identifier != null`:

![screen shot 2019-01-31 at 2 57 23 pm](https://user-images.githubusercontent.com/21006/52081628-b0876300-2568-11e9-975e-7664061e073a.png)

https://github.com/IQSS/dataverse/blob/960e96f235dcff0d4fd7986b7f7444cd4c2d2569/src/main/webapp/file.xhtml#L430
