### ISSUE TITLE
Update modifyRegistration API calls to only update when necessary

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#5505]
The /modifyRegistrationPIDMetadataAll and {id}/modifyRegistrationMetadata api call implementations (which actually update the metadata and targetURL) currently do not check to see whether updates are needed before sending change requests to the provider. This makes their use as a way to correct errors in the metadata and/or targetUrl problematic as they would also try to update PIDs that don't need any change. (See, for example, #5144 and #4760). 
The DataCite DOI provider is one that provides an API to retrieve the current targetURL and metadata, making it possible to check before updating. It would be helpful if the Abstract classes for providers differentiated between first time registration and updates and for the DataCite DOI provider to perform checks when updating. (PR to follow).

**Comment by djbrooke** [comment]
Hi @qqmyers - just making sure you saw the note from @sekmiller in the PR here:

https://github.com/IQSS/dataverse/pull/5506

**Comment by qqmyers** [comment]
@djbrooke - thanks - just being slow / finding new issues :-)

**Comment by pdurbin** [comment]
@qqmyers heads up that pull request #5506 now has merge conflicts. Thanks, as always, for the pull requests!

**Comment by qqmyers** [comment]
@cmbz - I think this can be removed from the board as the #5506 PR is already in ready for review
