### ISSUE TITLE
OAI-ORE exports list "A Dataverse instance" as the installation name

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#5508]
The OAI-ORE metadata exports for datasets in Dataverse repositories should list the name of the repository in `dcterms:creator`. In the OAI-ORE exports of datasets in QDR repository, like [this one](https://data.qdr.syr.edu/api/datasets/export?exporter=OAI_ORE&persistentId=doi%3A10.5064/F6QN64NH), dcterms:creator is "Qualitative Data Repository":

```
{
  "dcterms:modified": "2019-02-01",
  "dcterms:creator": "Qualitative Data Repository",
  "@type": "ore:ResourceMap",
  "@id": "https://data.qdr.syr.edu/api/datasets/export?exporter=OAI_ORE&persistentId=doi:10.5064/F6QN64NH",
```

But in the OAI-ORE exports of datasets on Harvard Dataverse, like [this one](https://dataverse.harvard.edu/api/datasets/export?exporter=OAI_ORE&persistentId=doi%3A10.7910/DVN/2ERRXC), dcterms:creator is "A Dataverse Instance":

```
{
  "dcterms:modified": "2019-02-01",
  "dcterms:creator": "A Dataverse Instance",
  "@type": "ore:ResourceMap",
  "@id": "https://dataverse.harvard.edu/api/datasets/export?exporter=OAI_ORE&persistentId=doi:10.7910/DVN/2ERRXC",
```

Definition of done for this issue would be the value of `dcterms:creator` in OAI-ORE exports being the name of the repository.

**Comment by qqmyers** [comment]
@jggautier - that string comes from 
institution.name=A Dataverse Instance
at https://github.com/IQSS/dataverse/blob/develop/src/main/java/Bundle.properties#L152
We could choose a better default and/or make it clear that this should be updated upon install - any preferences?

**Comment by pdurbin** [comment]
@qqmyers I would suggest getInstallationBrandName from here:

https://github.com/IQSS/dataverse/blob/v4.10.1/src/main/java/edu/harvard/iq/dataverse/branding/BrandingUtil.java#L9

But I defer to @jggautier 😄

**Comment by qqmyers** [comment]
@pdurbin - at QDR, that's "QDR Main Collection"  whereas we have
institution.name=Qualitative Data Repository . I didn't survey lots of instances, but I suspect that the root dataverse name is not always the type of formal/complete organization name that should go in the metadata (and archival copy if you use that). One option would be to default to 
institution.name=
in Bundle.properties and use getInstallationBrandingName() if it isn't set...

**Comment by pdurbin** [comment]
@qqmyers I hear you but in the Installation Guide we do say "The name of your root dataverse is the brand of your installation of Dataverse and appears in various places such as notifications and support links, as outlined in the :SystemEmail section below." http://guides.dataverse.org/en/4.10.1/installation/config.html#branding-your-installation . If you feel like this is a bug or needs further thought, please open a separate issue.

**Comment by mheppler** [comment]
@qqmyers @pdurbin, configurable text should not be in the bundle. If a setting is not required, default text can go in the bundle. It sounds like "A Dataverse Instance" isn't suitable as a default though.

**Comment by pdurbin** [comment]
> configurable text should not be in the bundle

@mheppler check out "Data Projects" and "Search this collection":

<img width="316" alt="screen shot 2019-02-02 at 9 36 36 am" src="https://user-images.githubusercontent.com/21006/52165379-2953ff80-26ce-11e9-8b04-f67f07afc5cd.png">

@qqmyers is good at giving people what they want. 😄 

I agree that these ideally wouldn't be bundle edits. They should be configuration options.

**Comment by qqmyers** [comment]
@jggautier - Would this be an :InstitutionName setting? Another possibility would be to use the Affiliation field for a Dataverse (which could be different for sub-dataverses), but that is displayed by default which may not be desirable. I could make it a setting for now and open an issue for making it Dataverse-specific and either using Affiliation or other new dataverse field to support that.

**Comment by jggautier** [comment]
Those are interesting solutions. Hadn't thought of the dataverse affiliation field. We'll have to think more about how this might work.

We'd like to understand how QDR is using these different pieces of information, if we could pick your brain :) @scolapasta and I were browsing QDR's repo and noticed that the dataset citations have both the root dataverse name and "Qualitative Data Repository," and we're wondering where the "Qualitative Data Repository" string comes from? E.g. is it hard coded in the code used to create citations, or maybe coming from the dataset Distributor field?

And does QDR use the root dataverse or "Qualitative Data Repository" in its email notifications?

**Comment by qqmyers** [comment]
@jggautier  - in general, QDR has custom code when it hasn't been clear how to make something generic. With the root dataverse named 'QDR Main Collection', I think we started with some hardcoding but have mostly switched now to having institution.name and institution.acronym (for where that was too long) as two bundle entries that we use in mail messages, various places in the display, and the OREMap, with custom code to retrieve those rather than the brandingname/root dataverse where needed. Citation is still hardcoded, just because it was done before we had institution.name, but the fact that there's an extra field in the citation is custom code. (Distributor could work, but that value is usually name, email, URL for QDR to go in the metadata and would be too long for the citation.)

As noted earlier, making these settings would probably be better. Since QDR changes many of the Bundle entries - changing 'dataverse' to 'collection' almost universally for example, but also pointing to QDR specific guidance on adding metadata, etc., I sometimes haven't worried too much about adding additional value strings to Bundle, but I agree it is cleaner to avoid that.

**Comment by jggautier** [comment]
Since I opened this issue, have changes been made to the software that would affect what's in the dcterms:creator element of Dataverse installations' OAI-ORE exports? Or make it possible or easier for installations to use something other than the name of the Root Dataverse collection? (Sometimes changes discussed and tracked in other GitHub issues affect )

To learn more about [what @qqmyers wrote earlier](https://github.com/IQSS/dataverse/issues/5508#issuecomment-459867886), would it be helpful to ask Dataverse installations:
- What's in the dcterms:creator element of their OAI-ORE exports and why (especially if it isn't the name of the "Root" collection)?
- Are they satisfied with what's in that element?
- Is it clear from the documentation (e.g. the Installation Guide?) how to change what's put in that element?

Also I think it might be helpful to document how this system-generated information is added to various exports. A while back I added to the crosswalk [a tab only for system-generated metadata](https://docs.google.com/spreadsheets/d/10Luzti7svVTVKTA-px27oq3RxCUM-QbiTkm8iMd5C54/edit#gid=1901625433), and there's a row for "Dataset Publisher", but:
- There's no indication about where this information comes from (e.g. "institution.name" or "getInstallationBrandName")
- I didn't add a column for the OAI-ORE export since I haven't really thought of it as an export with its own fields (the way that the DDI Codebook and Datacite exports have their own fields)

**Comment by qqmyers** [comment]
relates to #8760

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
