### ISSUE TITLE
API: Support Dataverse Deposit Terms of Use for Backwards Compatability w/ Data Deposit API (SWORD v2)

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#551]
---

Author Name: **Eleni Castro** (@posixeleni)
Original Redmine Issue: 3967, https://redmine.hmdc.harvard.edu/issues/3967
Original Date: 2014-05-12

---

As Phil is working on backwards compatibility for the Data Deposit API in 4.0 and he discovered that there is nothing so far in 4.0 discussing Dataverse Deposit Terms of Use. Attached related ticket for the Dataset level terms of use/licensing.

In order to accomplish backwards compatibility: dataverse.getDepositTermsOfUse() will need to be supported in some way. For more information: https://docs.google.com/a/harvard.edu/document/d/1YC_ACDEoJ7JIX94n6gXyobA3kFYehDq-_Tf4tTpVv0k/edit?usp=sharing

---

Related issue(s): #342
Redmine related issue(s): [3385](https://redmine.hmdc.harvard.edu/issues/3385), [3757](https://redmine.hmdc.harvard.edu/issues/3757)

---

**Comment by pdurbin** [comment]
@scolapasta informed me that (unlike DVN 3.x) Dataverse 4.0 does not have Deposit Terms of Use. We'll have some form of API Terms of Use, it seems.

**Comment by pdurbin** [comment]
This morning I talked on the phone for about an hour with Shuangjun Wang and Christopher Bavitz from Berkman about APIs and Terms of Use. Here are my notes: https://docs.google.com/a/harvard.edu/document/d/1497sGM827nYFAD5QVgWs9OAN2V5eom7xHGSmqea85CA/edit?usp=sharing

They're drafting something for us. It was a very nice chat.

@scolapasta it would probably be a good idea to expose the API Terms of Use via the "native" API. I just poked around in GitHub's API docs and I don't see where they expose it. It's not in their "meta" API for example: https://developer.github.com/v3/meta/

**Comment by pdurbin** [comment]
I went ahead and added key for `ApiTermsOfUse` in the settings table in 483931e8fd982cc832f05f340c4088264953788d per @scolapasta 's request and documented it but I'm getting strange results from a multi-line input file. It gets squished onto a single line like this:

`<collectionPolicy xmlns="http://purl.org/net/sword/terms/">This is line 1 of API terms.This is line 2 of API terms.This is line 3 of API terms.</collectionPolicy>`

I'm not sure how to fix this. Here's the multi-line file and how I put it in the database and checked the SWORD service document:

    $ cat /tmp/api-tos.txt 
    This is line 1 of API terms.
    This is line 2 of API terms.
    This is line 3 of API terms.
    $ curl -X PUT -d@/tmp/api-tos.txt http://localhost:8080/api/s/settings/:ApiTermsOfUse
    {"status":"OK","data":{":ApiTermsOfUse":"This is line 1 of API terms.This is line 2 of API terms.This is line 3 of API terms."}}
    $ scripts/api/data-deposit/service-document | grep collectionPolicy | head -1

I'm not sure what's going on or how to fix this.

**Comment by pdurbin** [comment]
> I'm getting strange results from a multi-line input file. It gets squished onto a single line like this

@scolapasta and I agreed to make fixing this bug a post 4.0 activity so I created an issue: #1585

@posixeleni I'm going to give this ticket to you to collect the final API Terms of Use from Berkman, make sure it's in plain text (or HTML? ... plain text would probably be better since it's consumed by the API) and commit the file into git.

**Comment by posixeleni** [comment]
Waiting for Berkman to draft up the API Terms. Met with Phil this week to discuss API functionality.

**Comment by posixeleni** [comment]
Closing please see #1718
