### ISSUE TITLE
Database changes for Data Curation Tool

### ISSUE THREAD

**Issue by lubitchv** [IQSS/dataverse#5513]
This issue is related to  #4174, #4448, #3604.
For curating Variable metadata in DCT (external tool) there is a need for database changes. This is a first step for #4448. New variablemetadata table for mutable variable metadata is needed to be introduces. Also new tables for Variable Groups will be needed.

**Comment by pameyer** [comment]
on lubitchv/5513-database-variablemetadata 73dc5e7dceb30bd853800d0e72f36695545279f7 in docker-aio:

```
[ERROR] Failures: 
[ERROR]   InReviewWorkflowIT.testCuratorSendsCommentsToAuthor:256 Expected status code <204> doesn't match actual status code <400>.

[INFO] 
[ERROR] Tests run: 82, Failures: 1, Errors: 0, Skipped: 1
```

**Comment by lubitchv** [comment]
Hi everyone.

I cannot reproduce the error in InReviewWorkflowIt test. The error occurs only when Root is not publish and permissions are not setup for "Anyone with a Dataverse account can add sub dataverses". Then the error also happens for current develop branch not only for the new branch. If root is published and Permissions set up properly I do not see that error. So I suspect that permissions were not setup properly for the tests to run.

**Comment by pdurbin** [comment]
@lubitchv ok, thanks for trying to reproduce the reported error. It sounds like someone on the Dataverse team should take a look so I dragged this back to code review at https://waffle.io/IQSS/dataverse

**Comment by pameyer** [comment]
@lubitchv Thanks for taking a look.  When I checked, I saw the the error on this branch; but not on develop.  It's very plausible to me that my test setup glitched 2x the same way when I tried this branch.

**Comment by lubitchv** [comment]
@landreev I introduced the required changes, i.e I returned weighted column back into DataVariable.

**Comment by djbrooke** [comment]
@lubitchv - is this ready for another code review?

**Comment by lubitchv** [comment]
@djbrooke Yes, it is.

**Comment by djbrooke** [comment]
Thanks, we'll take a look!

**Comment by kcondon** [comment]
@lubitchv We've released v4.11 so the db update script name has changed. Please update your script to contain just your changes since it is the first for this release and name it 
upgrade_v4.11_to_v4.12.sql

Thanks!

**Comment by lubitchv** [comment]
@kcondon I moved my database changes to upgrade_v4.11_to_v4.12.sql as you requested.

**Comment by kcondon** [comment]
@lubitchv Thanks for the update. When I upload a file of any type using this branch it does not appear in the uploaded list and saving does not persist it to the dataset. I see no server log errors.

**Comment by kcondon** [comment]
@lubitchv Please disregard my previous comment about uploading files. There had been a UI change and needed some files reloaded to work.
