### ISSUE TITLE
More specificity about the meaning of "dataset" on delete

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#5517]
"Dataset" can mean different things in different repositories. On delete, we should add some brief additional text to clarify what is about to be deleted. See: 

https://twitter.com/KSchultz3580/status/1092851050971709440

<img width="626" alt="screen shot 2019-02-05 at 7 37 34 pm" src="https://user-images.githubusercontent.com/7773392/52358428-f2e7ee80-2a05-11e9-9620-36602b47a448.png">

**Comment by mheppler** [comment]
"Delete Draft Version" confirmation msg'n should also be considered here.

![screen shot 2019-02-06 at 12 08 26 pm](https://user-images.githubusercontent.com/687227/52359481-f8463880-2a07-11e9-91dd-f421ff3d03ed.png)

**Comment by mheppler** [comment]
And while we're piling on... "Delete Dataverse" confirmation msg'n follows the same format of vagueness.

![screen shot 2019-02-06 at 12 10 01 pm](https://user-images.githubusercontent.com/687227/52359618-40fdf180-2a08-11e9-94cd-f8af746d7c63.png)

**Comment by pdurbin** [comment]
From the tweet above, it's probably worth considering the rest of the feedback about multiple buttons. Here's a screenshot:

![screen shot 2019-02-12 at 11 03 58 am](https://user-images.githubusercontent.com/21006/52649307-1acbcc00-2eb6-11e9-9209-fc466a558ec3.png)

- "PSA: the term dataset can either refer to a single data file or to a collection of data files and associated code. So when Dataverse asks if you really want to delete the selected dataset, make sure you know which meaning it is using."
- "PS. In retrospect what messed me up is that when you select a file, there are two edit buttons, one which will let you delete the file, the other (higher up) that will delete the entire dataset. I didn’t see the former until it was too late."

That said, this was estimated as a "1" last week when I wasn't here so I don't know what the plan is.

**Comment by djbrooke** [comment]
The plan is to make the text change(s) only. 

@dlmurphy you said you would include some suggested text here?

**Comment by pdurbin** [comment]
I just created pull request #5536 with some tweaks to the wording. Here are some screenshots:

![screen shot 2019-02-13 at 3 27 45 pm](https://user-images.githubusercontent.com/21006/52741929-9146f780-2fa4-11e9-98fa-2fa27ecb0bb3.png)

![screen shot 2019-02-13 at 3 28 01 pm](https://user-images.githubusercontent.com/21006/52741927-9146f780-2fa4-11e9-91a0-615c6b796b14.png)

I'm reminded that we never did create a glossary (#4274) of terms and "dataset" should definitely be in there since as the tweet points out, to many people it can mean a single file.

**Comment by dlmurphy** [comment]
The Delete Dataset message looks great to me. 

For the Delete Draft Version message, I suggest just adding the words "most recently" to make it a little more clear:

"Files will be reverted to the most recently published version."

I'd also like to tackle the "Delete Dataverse" message that Mike pointed out. Let's rephrase to:

"Are you sure you want to delete this Dataverse and all of its datasets and files? You cannot undelete this dataverse."

I'll make these changes to the bundle and pass this on to QA.

**Comment by scolapasta** [comment]
@dlmurphy I don't think you can delete a dataverse if it has contents.

**Comment by dlmurphy** [comment]
Whoops, good call! I'll check on this and make sure.

**Comment by dlmurphy** [comment]
Yup, @scolapasta is right. Dataverses can only be deleted if they're not yet published and they contain no draft datasets. I'll leave the existing Delete Dataverse message as is.
