### ISSUE TITLE
Files per page - make configurable

### ISSUE THREAD

**Issue by Thanh-Thanh** [IQSS/dataverse#5519]
Hi all,

Actually, the number of files per page is hard coded in the filesFragment.xhtml

We can make it configurable ?

Thanks in advanced,

Thanh Thanh

**Comment by mheppler** [comment]
@Thanh-Thanh, out of curiosity, what number of files displayed on the page are you aiming for? As you noted, the current setting for the files dataTable on the dataset pg is `rows="10"`.

**Comment by Thanh-Thanh** [comment]
@mheppler I modified it to 20. So I think it would be great if we can configure this value... :)

**Comment by pdurbin** [comment]
Do you want to make a pull request, Thanh-Thanh? :)

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
