### ISSUE TITLE
deleting large #files from a dataset should "resolve" to success message

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#5522]
When you select large number of files for deletion <400 with the datasets I am working on, and select "delete," the page does not refresh until unless done manually, to reflect files have been successfully removed.

**Comment by mheppler** [comment]
This issue appears to be a duplicate of _Deleting files: selecting 50 files to delete from a large dataset should result in a success message #5567_ which @djbrooke was going to look into back in Feb.

@sbarbosadataverse can you please close this issue as a duplicate or provide any additional details necessary if it is not.
