### ISSUE TITLE
Spike - investigate impact of upgrading to Bootstrap 4.x

### ISSUE THREAD

**Issue by TaniaSchlatter** [IQSS/dataverse#5527]
Bootstrap is currently on release 4.2.1. As we look at UI changes to the dataset and file page, it makes sense to [consider migrating](https://getbootstrap.com/docs/4.0/migration/), and get a sense of impact.

**Comment by djbrooke** [comment]
Closing out this spike for now, as the answer is "extremely high" - 

https://github.com/IQSS/dataverse/issues/4219#issuecomment-400463760

@TaniaSchlatter and @scolapasta - you and I should work together to determine the appropriate time and method to introduce such a large change to the application.
