### ISSUE TITLE
DiscoFeed error

### ISSUE THREAD

**Issue by jmjamison** [IQSS/dataverse#5528]
When a dataset owner gets a request for access to a restricted file, follows the link (email includes this) and gets this eroror:  Internal Error - Failed to download metadata from /Shibboleth.DiscoFeed

But, I am able to log in , look at messages and allow access if necessary.

I'm still running v.4.9.2 build 940 on our test system. 

In the shibboleth2.xml file the reference to DiscoFeed is:   
   <Handler type="DiscoveryFeed" Location="/DiscoFeed"/>.  

I've noticed that the link in the email:  (http://test.dataverse.ucla.edu:8080/permissions-manage-files.xhtml?id=4932.)   includes :8080.   If I take that part out the link works. 

I've tried looking through the related issues but they refer to an earlier verison of dataverse.

**Comment by pdurbin** [comment]
@jmjamison hi, I would suggest looking at your `dataverse.siteUrl` JVM option: http://guides.dataverse.org/en/4.9.2/installation/config.html#dataverse-siteurl

You should probably take ":8080" out of it, like in this example:

`<jvm-options>-Ddataverse.siteUrl=http://phoenix.dataverse.org</jvm-options>`

The default location of the domain.xml is /usr/local/glassfish4/glassfish/domains/domain1/config/domain.xml

**Comment by jmjamison** [comment]
I did try that.  It I take out the 8080 from  
<jvm-options>-Ddataverse.siteUrl=http://${dataverse.fqdn}:8080</jvm-options>

I can't login,   just get a blank page.     I'll try removing the entire line.

**Comment by jmjamison** [comment]
I completely took out the jvm-option siteUrl and that fixed the problem.   Thank you!
