### ISSUE TITLE
Export: Failing export on publish still registers doi, leading to doi collision and change when republish.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#5539]
When export was failing on publish, as in the case with funder with no name, it actually registers the doi for the dataset, so that when you fix the export issue and try to publish again, it detects an existing doi of the same value, then generates a new one for the dataset. This causes file storage location to be incorrect and 404 download results.

So, there are a couple issues: 
1. likely should not register doi if fails to publish on export
2. if doi legitimately changes ob publish due to an actual doi collision file location, based on dataset PID, should be adjusted in some manner so files remain accessible.

**Comment by qqmyers** [comment]
FYI - this is the issue in #5469 as well - in that case it was a combination of the change at DataCite and a DV bug that falsely reported the DOI already existed, but the problem from there is the same.

**Comment by djbrooke** [comment]
We discussed in backlog grooming 4/3 and decided to think about this one a bit.

**Comment by djbrooke** [comment]
@scolapasta do you expect that #4425 will resolve this?

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
