### ISSUE TITLE
DDI xml parser for Data Curation Tool

### ISSUE THREAD

**Issue by lubitchv** [IQSS/dataverse#5540]
Data Curation Tool sends DDI xml file to dataverse from Data Curation Tool. Therefore dataverse will need to be able to parse that file and save the data into VariableMetadata and VarGroup structures (from #5513).
This issue is related to  #4174, #4448, #3604. This is a second step in #4448

**Comment by djbrooke** [comment]
Hey @lubitchv - are you working on this right now? If so, I'll move it community dev.

**Comment by lubitchv** [comment]
@djbrooke  Yes, thanks.

**Comment by landreev** [comment]
@kcondon - this is ready to merge. I can't think of anything to qa/test for this PR. This is some code to support the Data Curation tool in the future - but it's not being used in any way by the application in its present form.
