### ISSUE TITLE
drag and drop of  files should not "hang" on file upload progress bar

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#5544]
Tried uploading 30 image files to a dataset and several times the upload status bar just hangs and forces me to restart the upload. It never resolves

<img width="1985" alt="screen shot 2019-02-14 at 3 29 48 pm" src="https://user-images.githubusercontent.com/8322346/52815814-a6d42400-306d-11e9-9eeb-9691474c88ca.png">

**Comment by pdurbin** [comment]
This reminds me a bit of #4511 and the "more feedback about errors" feature @qqmyers added in pull request #4522

**Comment by qqmyers** [comment]
Could be ... what version is running? The code to check errors was in that original PR, but it was broken with provenance additions and only works again after #5466.

**Comment by pdurbin** [comment]
@qqmyers good point. I'm sure @sbarbosadataverse is using Harvard Dataverse which would be Dataverse 4.10.1 and that fix in pull request #5466 will ship in the next release.

**Comment by jggautier** [comment]
I just uploaded 30 image files averaging about 1MB each and haven't seen a stall, yet. Maybe this  issue's been improved since last February?

**Comment by pdurbin** [comment]
@jggautier since you also just opened #6481 (thanks), I assume your observation was on Dataverse 4.18.1

**Comment by jggautier** [comment]
@pdurbin is sure was!

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
