### ISSUE TITLE
GET dataverse data returns blank values for dataverseContact in Native API

### ISSUE THREAD

**Issue by tmrozewski** [IQSS/dataverse#5549]
I'm experiencing a minor problem using the Native API on the Scholars Portal Demo DV (v. 4.10.1.3-SP).

When I use the Native API to GET the data about a dataverse, the dataverseContact field comes back with an empty value even though I know there to be contacts listed when viewed in a web browser. All other fields seem to return the proper values in the output. Here's my code: 
`curl -X GET https://demodv.scholarsportal.info/api/dataverses/laurentian`

Similarly, when I use POST to create a new dataverse with the [JSON example](https://dataverse.scholarsportal.info/guides/en/4.8.6/_downloads/dataverse-complete.json) provided in the documentation, the response shows that the dataverseContact field has a blank value; however, when I verify in my browser, I notice that the contact info I uploaded _is_ displayed properly. Here's code:
`curl -i -X POST --upload-file foo/bar.json -H "X-Dataverse-key: $API_KEY" https://demodv.scholarsportal.info/api/dataverses/laurentian`

Probably a minor issue but I thought I'd flag it anyway.

**Comment by pameyer** [comment]
@tmrozewski Could you check if it's possible that the installation you're using has `:ExcludeEmailFromExport` set to `true`?

**Comment by tmrozewski** [comment]
I'll forward that question to our DV admins and get back to you.
*________________*
*Tomasz Mrozewski*

Data, GIS and Government Documents librarian & Engineering liaison
librarian /
Bibliothécaire pour les données, les services géospatials et les documents
gouvernementaux & bibliothécaire spécialisé pour la génie
Laurentian University Library and Archives / Bibliothèque et archives,
Université Laurentienne
935 Ramsey Lake Road
Sudbury, ON P3E 2C6
tmrozewski@laurentian.ca
(705) 675-1151 x3325

**Comment by pameyer** [comment]
@tmrozewski I took a quick look, and it appears that this shows up for the dataverses API regardless of the value of that setting.  Good find - thanks for reporting it.

**Comment by tmrozewski** [comment]
No sweat!

**Comment by pdurbin** [comment]
@tmrozewski is this bug blocking anything you're working on? Do you have a use case? Or are you just letting us know? Whatever is fine. 😄 Thanks for letting us know!

**Comment by tmrozewski** [comment]
Just letting you know! When I ran the code and looked at the response, I
saw the Contact field was blank so I started trying to troubleshoot what
went wrong. Thought that correcting the response might save future users
some time but I realize it's not a high priority.
*________________*
*Tomasz Mrozewski*

Data, GIS and Government Documents librarian & Engineering liaison
librarian /
Bibliothécaire pour les données, les services géospatials et les documents
gouvernementaux & bibliothécaire spécialisé pour la génie
Laurentian University Library and Archives / Bibliothèque et archives,
Université Laurentienne
935 Ramsey Lake Road
Sudbury, ON P3E 2C6
tmrozewski@laurentian.ca
(705) 675-1151 x3325

**Comment by pdurbin** [comment]
@tmrozewski it certainly would but with 885 open issues it's good to know you're not blocked on the one. Thanks!

**Comment by pdurbin** [comment]
@tmrozewski I just looked at https://demo.borealisdata.ca/api/dataverses/laurentian and I don't see any contacts.

My guess is that the server has been upgraded to a version that includes this fix to hide the contact (and its email, for privacy purposes):

- Issue #5583
- PR #5655

Any objection to closing this issue? Thanks.
