### ISSUE TITLE
Parallel edits cause multiple draft versions

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#5550]
In working with datasets with 100+ files, we've seen an issue that is probably related to #2132 and #2545 : 
if a user(s) working on the same dataset try a save for an edit to a file or the dataset before a prior save has finished, you end up with multiple draft versions, each with some of the changes. (It's a little confusing because you can only see the latest draft version in the web interface). The prior changes to grey out/remove the add/edit metadata, publish, etc. buttons helps but doesn't address the case where multiple windows were open or when multiple users/browser are in play. 

To handle the underlying cause, we've gone ahead to implement an editInProgress lock that will a) warn users that the dataset can't be edited temporarily, and b) stop any attempts from other pages/browsers that would otherwise corrupt the database. (This is somewhat analogous to the Dcm lock...).

Also - FWIW: in trying to recover from an instance of this with 4 draft versions, I was able to delete a datasetversion manually (essentially recursing to delete entries in every table that referenced the version or entities associated with the version) and by using the delete draft button in the gui. I don't know when #5542 was introduced, but I think that the same issue that stopped you from deleting one draft version when starting from a published version view would have affected deleting in the multiple draft case. My guess is that, if anyone has this problem in a prior version, deleting form the draft page and/or updating to get the #5542 fix would allow removal of the extra drafts without having to touch the DB.

**Comment by scolapasta** [comment]
@qqmyers I'm a little surprised by this because I thought we had added a constraint to make sure that multiple drafts couldn't be created - in the issue you referenced #2132. Is that not the case?

Doing the locking here may be cleaner and still worthwhile, but first would like to understand a little about why this issue is occurring and previous attempted fix not working.

**Comment by qqmyers** [comment]
@scolapasta - the fix in #2132 is at the GUI/view-level. If your action in one tab starts a long-running edit, if you try to get back to an edit form, your buttons will disabled. However, if you have multiple tabs/people/browsers involved in editing, you can still get to and use edit forms. This could potentially be addressed with user education (except for the case of two people editing one dataset), but it's painful enough to clean up that I thought adding a lock to avoid concurrent edits would be better.

**Comment by scolapasta** [comment]
@qqmyers #2132 specifically references adding the following constraint to the db:

CREATE UNIQUE INDEX one_draft_version_per_dataset ON datasetversion
(dataset_id) WHERE versionstate='DRAFT';

Is that not working to block multiple drafts?

**Comment by qqmyers** [comment]
@scolapasta  - A quick check on our dev db shows that we didn't have this constraint in place. Scanning the releases I see it in the 4.2.1 to 4.2.2 upgrade script with a note "--It may not be applied until all of the datasets with
--multiple drafts have been resolved" I think QDR started after that though, so I'm not sure why we wouldn't have it ( - I don't think we had a pre 4.2.2 db with multiple drafts).

In any case, you're right that this should eliminate the need for a lock. I'll take a look and see if any of the messaging I added is still useful.

**Comment by qqmyers** [comment]
FWIW: looks like we never ran reference_data.sql - I don't see any of the other db changes/entries from that file in our db...

**Comment by qqmyers** [comment]
@scolapasta - After some internal discussion, I think QDR is going to keep this lock since it provides users with a useful warning when long edits are in progress (that disappears when the lock is released), versus just failing due to the db constraint from #2132 (which we now have in place).  (FWIW: I don't see a way to provide a warning with just the db constraint in place.)
I think the primary use case is with curators wanting to make multiple changes to datasets with many files, which may be rare enough to not be worth merging this code into DV. If not, you can close this and we'll just maintain it in our fork.

**Comment by pdurbin** [comment]
@qqmyers good point over at https://github.com/IQSS/dataverse/issues/5535#issuecomment-470600910 that the locks you added might help with the "partial failure" with deleting files under investigation.

**Comment by scolapasta** [comment]
@qqmyers we'll be reviewing this next week at our weekly tech hours and hope to make a decison then.

**Comment by landreev** [comment]
Hello, 
We've been trying to gauge how much this would help us; the fact that the dataset needs to already be locked by the time the second user comes to the page is of course a limiting factor. 
But we've been wondering if there's something simple that can be added to improve it. For example, if we have a situation where the second user (same user in another tab) has started another edit *before* the dataset was locked - rather than letting the command fail, should we just try and check for a lock before we execute the command? Then, if we detect a lock we can put up some informative message, and put the page in the locked mode... Same end result really - they can't make that change; but a bit better/friendlier user experience (?). (The lock change would need to be made in a way that doesn't try to refresh the entire dataset from the db)

Also, since the removal of this lock happens inside the command, does that mean that if the command fails for whatever reason and the transaction gets reversed, that they are stuck with a locked dataset?

**Comment by poikilotherm** [comment]
Any chances you might think of adding Operational Transformation realtime collaboration instead of locks? There are existing JavaScript libs for this, like ShareDB and others.

**Comment by qqmyers** [comment]
@landreev - I'm not sure I understand what's 'limiting' - is it just that the severity level for the warning is higher than you'd like? (If so perhaps dropping that to 'info' from 'warning' is a fix?). Overall, I think one can always do a find() against the database to discover a lock, so adding a step in the page workflow to check for a lock just prior to submission could be done, but that's basically what happens with the save button in the PR - a find() checks the db and refuses to go forward if one exists. Being able to keep the entered changes, e.g. to submit them again could add value, but I'm not sure its worth the effort and it is nominally independent of a lock - if another edit has already succeeded, the save will fail due to the db conflict rather than a lock and you'd presumably want to handle that case as well.

W.r.t. remaining locked upon failure - I think one of my two changes is safe against that - the lock is removed in a finally() clause. I'll look again at the other one - I think it should be possible to do a similar thing there.

**Comment by qqmyers** [comment]
@poikilotherm - I don't think operational transform helps too much here (at least in terms of handling text changes to the same item). The issue is primarily due to the current code treating an entire dataset version (with all of the files/file metadatas) as one object to persist in a db transaction. That makes things slow with large numbers of files and makes changes to different files be seen as conflicting. So far I think the primary use case is more that one person will make changes to one file and another person will change another (e.g. their titles). These don't really conflict (except that both update the dataset version modified date) but because the code tries to update the dataset version as a whole, the second edit fails. (The 'lock' I'm proposing doesn't really affect all of this - it just flags when there's an active transaction in progress so that a second one that would conflict can be avoided/stopped early).
I think a good way to improve this would be to make the transactions finer grained - just update the specific file affected and then update the datasetversion's modified date regardless of whether it has been previously modified (latest date always wins). I'm not sure this is easy given the PrimeFaces and persistence layers in the code, but it should be possible.

**Comment by qqmyers** [comment]
@landreev  - I've added try/finally logic everywhere the lock is created so failures shouldn't leave locks in place. I also updated the DatasetPage.save() method to make the same pre-check against the database copy of the dataset to avoid calling the command if there's a lock. That gives the 'nicer' message (versus the command failing) as shown in the image below.

![image](https://user-images.githubusercontent.com/6731983/56057150-23147c00-5d2c-11e9-980a-f7c25f5005ff.png)

Do these address all the open topics?

**Comment by pdurbin** [comment]
@qqmyers we have backlog grooming in 20 minutes and I'm looking at open pull requests. Are you ready for more code review? From your last comment, it sounds like it.

**Comment by qqmyers** [comment]
@pdurbin - yes. The code should be working, the bigger question is whether it addresses the issues. FWIW, I'm currently looking at timeout errors on edits of large datasets (which leave the edit page grayed out forever) and working to catch the error and use the edit lock to indicate when the edit completes (analogous to what happens with the lock from this PR where you can see the dataset is locked until the edit is done). A different issue/discussion, but it would be good to nail down the edit lock issue/PR itself...

**Comment by djbrooke** [comment]
@scolapasta @landreev  - can you determine if we want this code, and if so, give it a code review? If we don't want it we should close out this issue and PR with some reasons. Sorry if I'm missing something in the convo up the thread. Thanks!

**Comment by scolapasta** [comment]
@qqmyers So, we met again about this and will move it forward and merge. Can you a) merge with the latest from develop and b) add the new lock type to the API for removing locks? @landreev will also be adding some more comments about auto removing locks (on server startup), but we'll keep that out of scope.

**Comment by pdurbin** [comment]
> b) add the new lock type to the API for removing locks?

Since I had it up already, this is what we're talking about: http://guides.dataverse.org/en/4.14/api/native-api.html#dataset-locks ... "Currently implemented lock types are..."

**Comment by qqmyers** [comment]
@scolapasta - Thanks. I merged with develop. @pdurbin - thanks for pointing to the doc to update.
