### ISSUE TITLE
DataCite alreadyExists() doesn't check correctly for no PID case 

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#5554]
Correcting a bug I think I introduced in #5427: a DvObject with no PID currently has a non-null GlobalIdentifier with an empty value. The alreadyExists class just checks for null.

**Comment by pdurbin** [comment]
As @qqmyers says, his pull request #5555 adds an additional check for empty string. Seems fine. I moved it to QA.

I strikes me as somewhat odd that the method is called "alreadyExists" (returns true or false) but when no identifier exists, it doesn't log "doesn't exist". Instead it logs "No identifier sent." Sent where? I assume the code was refactored at some point. Not a big deal but I thought I'd mention it. This isn't anything Jim added in his pull request.

**Comment by qqmyers** [comment]
I'm guessing that this was/is a sanity check - e.g. it doesn't make sense to call alreadyExists() if there's no PID being sent (to this method)... It must be that some upstream code does though, otherwise there wouldn't have been an issue when DataCite changed its return value for a check on an empty string...

**Comment by kcondon** [comment]
@qqmyers As a practical matter, how would one test this?

**Comment by qqmyers** [comment]
@kcondon - I'm not sure. I guess the scenarios (publishing a first version?) that were causing the DataCite failures in Dec/Jan would still exercise this and, if you repeated those, you should see the "No identifier sent." message in the log now. Since DataCite reverted, this PR doesn't change the final outcome, but if they ever make the same mistake, this will stop Dataverse from calling them and potentially getting the answer that yes, the empty DOI exists...
