### ISSUE TITLE
If you download a citation the filename always begins with "DOI_" also if the PID is a Handle instead of a DOI.

### ISSUE THREAD

**Issue by PaulBoon** [IQSS/dataverse#5563]
When you download a citation from the dataset page you get a file with a name that starts with DOI_, which is confusing if you have Handles instead of DOIs. 
Proposed solution is to have this filename depending on the type of PID being used. 

The function getFileNameDOI in FileDownloadServiceBean.java (edu/harvard/iq/dataverse/FileDownloadServiceBean.java:386) adds the hardcoded "DOI:" prefix. 
We better do something like the following: 
`return id.getProtocol() + ":" + id.getAuthority() + "_" + id.getIdentifier();`

Also the name of this function should better be getFileNameFromPid.

**Comment by djbrooke** [comment]
@paulboon this makes sense to me, but I'll have a developer confirm.  Are you interested in making a pull request for this change?

**Comment by PaulBoon** [comment]
Yes I planned to do a PR soon. 

It looks like 
`return id.getProtocol().toUpperCase() + "_" + id.getAuthority() + "_" + id.getIdentifier();`
would do it.

But if we drop the uppercasing of the protocol part we could also simply do
`return id.toString();`

Also note that this filename string is placed in the response header, but as soon as the browser creates the file the name has no colon or slashes in it.

**Comment by PaulBoon** [comment]
See Pull request: https://github.com/IQSS/dataverse/pull/5568
With the `id.asString()` solution.
