### ISSUE TITLE
As dataverse user I would like to import a doi from https://doi.test.datacite.org using the native api.

### ISSUE THREAD

**Issue by flaviofrancisco** [IQSS/dataverse#5570]
We are using the following test environment/ url: https://doi.test.datacite.org (suffix: 10.33591/ shoulder: nioz). 
The doi is successfully created on datacite as you can see on the picutre bellow.
![image](https://user-images.githubusercontent.com/12722538/53250997-e927e180-36bb-11e9-9749-e2c95bcb6d80.png)
The problem start when we use the native api to import the json file into dataverse and we get the following error: Provided PID does not exist. Status code for GET 'https://doi.org/10.33591/nioz/7b.b.j' is 404."

url: http://dataverse-dev.nioz.nl:8080/api/v1/dataverses/doi/datasets/:import?pid=doi:10.33591/nioz/7b.b.j

with the following dataverse json:
{
  "authority": "10.33591/nioz",
  "identifier": "doi:10.33591/nioz/7b.b.j",
  "persistentUrl": "https://handle.test.datacite.org/10.33591/nioz/7b.b.j",
  "protocol": "doi",
  "datasetVersion": {
    "metadataBlocks": {
      "citation": {
        "displayName": "test 22/02/19-08:52",
        "fields": [
          {
            "typeName": "depositor",
            "multiple": false,
            "typeClass": "primitive",
            "value": "Maarten Franken"
          },
          {
            "typeName": "dateOfDeposit",
            "multiple": false,
            "typeClass": "primitive",
            "value": "2019-02-22"
          },
          {
            "typeName": "productionDate",
            "multiple": false,
            "typeClass": "primitive",
            "value": "2019-02-22"
          },
          {
            "typeName": "title",
            "multiple": false,
            "typeClass": "primitive",
            "value": "test 22/02/19-08:52"
          },
          {
            "typeName": "subject",
            "typeClass": "controlledVocabulary",
            "multiple": true,
            "value": [
              "Earth and Environmental Sciences"
            ]
          },
          {
            "typeName": "otherId",
            "typeClass": "compound",
            "multiple": true,
            "value": [
              {
                "otherIdValue": {
                  "typeName": "otherIdValue",
                  "multiple": false,
                  "typeClass": "primitive",
                  "value": "DAS:ffc2a009-fee7-4276-ac5b-7e647931ec10"
                }
              },
              {
                "otherIdValue": {
                  "typeName": "otherIdValue",
                  "multiple": false,
                  "typeClass": "primitive",
                  "value": "DOI:10.33591/nioz/7b.b.j"
                }
              },
              {
                "otherIdValue": {
                  "typeName": "otherIdValue",
                  "multiple": false,
                  "typeClass": "primitive",
                  "value": "update"
                }
              }
            ]
          },
          {
            "typeClass": "compound",
            "typeName": "author",
            "multiple": true,
            "value": [
              {
                "authorName": {
                  "typeName": "authorName",
                  "multiple": false,
                  "typeClass": "primitive",
                  "value": "test, test"
                },
                "authorAffiliation": {
                  "typeName": "authorAffiliation",
                  "multiple": false,
                  "typeClass": "primitive",
                  "value": ""
                }
              }
            ]
          },
          {
            "typeClass": "compound",
            "typeName": "datasetContact",
            "multiple": true,
            "value": [
              {
                "datasetContactName": {
                  "typeName": "datasetContactName",
                  "multiple": false,
                  "typeClass": "primitive",
                  "value": "Research Data Management"
                },
                "datasetContactAffiliation": {
                  "typeName": "datasetContactAffiliation",
                  "multiple": false,
                  "typeClass": "primitive",
                  "value": "NIOZ Royal Netherlands Institute for Sea Research"
                },
                "datasetContactEmail": {
                  "typeName": "datasetContactEmail",
                  "multiple": false,
                  "typeClass": "primitive",
                  "value": "rdm@nioz.nl"
                }
              },
              {
                "datasetContactName": {
                  "typeName": "datasetContactName",
                  "multiple": false,
                  "typeClass": "primitive",
                  "value": "Maarten Franken"
                },
                "datasetContactAffiliation": {
                  "typeName": "datasetContactAffiliation",
                  "multiple": false,
                  "typeClass": "primitive",
                  "value": "NIOZ Royal Netherlands Institute for Sea Research"
                },
                "datasetContactEmail": {
                  "typeName": "datasetContactEmail",
                  "multiple": false,
                  "typeClass": "primitive",
                  "value": "maartenfranken@live.nl"
                }
              }
            ]
          },
          {
            "typeClass": "compound",
            "typeName": "dsDescription",
            "multiple": true,
            "value": [
              {
                "dsDescriptionDate": {
                  "typeName": "dsDescriptionDate",
                  "multiple": false,
                  "typeClass": "primitive",
                  "value": "2019-02-22"
                },
                "dsDescriptionValue": {
                  "typeName": "dsDescriptionValue",
                  "multiple": false,
                  "typeClass": "primitive",
                  "value": "test"
                }
              }
            ]
          },
          {
            "typeClass": "compound",
            "typeName": "keyword",
            "multiple": true,
            "value": [
              {
                "keywordValue": {
                  "typeName": "keywordValue",
                  "multiple": false,
                  "typeClass": "primitive",
                  "value": "testing"
                }
              }
            ]
          },
          {
            "typeClass": "compound",
            "typeName": "dateOfCollection",
            "multiple": true,
            "value": [
              {
                "dateOfCollectionStart": {
                  "typeName": "dateOfCollectionStart",
                  "multiple": false,
                  "typeClass": "primitive",
                  "value": "2019-02-28"
                },
                "dateOfCollectionEnd": {
                  "typeName": "dateOfCollectionEnd",
                  "multiple": false,
                  "typeClass": "primitive",
                  "value": "2019-02-28"
                }
              }
            ]
          },
          {
            "typeClass": "compound",
            "typeName": "contributor",
            "multiple": true,
            "value": [
              {
                "contributorType": {
                  "typeName": "contributorType",
                  "typeClass": "controlledVocabulary",
                  "multiple": false,
                  "value": "Hosting Institution"
                },
                "contributorName": {
                  "typeName": "contributorName",
                  "multiple": false,
                  "typeClass": "primitive",
                  "value": "NIOZ Royal Netherlands Institute for Sea Research in cooperation with Utrecht University"
                }
              }
            ]
          },
          {
            "typeClass": "compound",
            "typeName": "producer",
            "multiple": true,
            "value": [
              {
                "producerName": {
                  "typeName": "producerName",
                  "multiple": false,
                  "typeClass": "primitive",
                  "value": "test, test"
                },
                "producerAffiliation": {
                  "typeName": "producerAffiliation",
                  "multiple": false,
                  "typeClass": "primitive",
                  "value": ""
                }
              }
            ]
          },
          {
            "typeClass": "compound",
            "typeName": "distributor",
            "multiple": true,
            "value": [
              {
                "producerName": {
                  "typeName": "distributorName",
                  "multiple": false,
                  "typeClass": "primitive",
                  "value": "Research Data Management"
                },
                "producerAffiliation": {
                  "typeName": "distributorAffiliation",
                  "multiple": false,
                  "typeClass": "primitive",
                  "value": "NIOZ Royal Netherlands Institute for Sea Research"
                }
              }
            ]
          },
          {
            "typeName": "distributionDate",
            "multiple": false,
            "typeClass": "primitive",
            "value": "2019-02-22"
          }
        ]
      }
    },
    "license": "CC0 1.0",
    "termsOfUse": ""
  }
}

Are we missing a setting on our dataverse dev environment? 

I was able to create a dataset manually on our dev dataverse (GUI) but not with the api please see the picture below:

![image](https://user-images.githubusercontent.com/12722538/53251438-eed1f700-36bc-11e9-963b-1162d23cef19.png)

Thanks in advace;
Flavio.

**Comment by pameyer** [comment]
You should be able to use the create API to re-create these datasets in a new installation.  

The import API is intended to bring in datasets that already exist; and it uses the ability to resolve the DOI (/PID) as a check to make sure that the dataset does exist.  So if I'm correctly understanding what you're trying to do, that approach won't work.

**Comment by flaviofrancisco** [comment]
> You should be able to use the create API to re-create these datasets in a new installation.
> 
> The import API is intended to bring in datasets that already exist; and it uses the ability to resolve the DOI (/PID) as a check to make sure that the dataset does exist. So if I'm correctly understanding what you're trying to do, that approach won't work.

Correct.

**Comment by pameyer** [comment]
Could you clarify what the use case is for preserving a test DOI?

**Comment by flaviofrancisco** [comment]
We would like to have a test environment because we have an internal application where users can create its own dois and that application interacts with DataCite and Dataverse through API.

**Comment by flaviofrancisco** [comment]
Using our internal application (Data Archive System) the user can create their DOIs.
1. On our test environment when a user creates a DOIs a new code is generated by our application: 10.33591/nioz/7b.b.j
2. The application sends the metadata through API to https://doi.test.datacite.org
3. Once the application receives the response from doi.test.datacite.org that is Ok then we change the status from draft to registered.
4. Once the DOI has its status changed to registered then the application tries to import it to Dataverese using the Native Api method: import: http://dataverse-dev.nioz.nl:8080/api/v1/dataverses/doi/datasets/:import?pid=doi:10.33591/nioz/7b.b.j
5. Once the DOI is on our dataverse dev environment then that doi is published on DataCite, but now we are stuck on the step 4 (it is working on production with: https://doi.datacite.org/.

**Comment by flaviofrancisco** [comment]
It was working with the suffix: 10.5072 and when we were using: https://mds.datacite.org/.
Now we changed to 10.33591 and https://mds.test.datacite.org

Here are our dataverse settings on dev:
{
"status": "OK",
"data": {
":Shoulder": "nioz/",
":Authority": "10.33591",
":SystemEmail": "flavio.francisco@nioz.nl",
":AllowSignUp": "yes",
":UploadMethods": "native/http",
"BuiltinUsers.KEY": "<our key>",
":DoiProvider": "DataCite",
":BlockedApiPolicy": "localhost-only",
":Protocol": "doi",
":BlockedApiKey": "<our other key>",
":BlockedApiEndpoints": "",
":SignUpUrl": "/dataverseuser.xhtml?editMode=CREATE"
}
}

**Comment by djbrooke** [comment]
Hey @flaviofrancisco! A quick read through seems to indicate that you’d like Test DOIs from DataCite to be resolvable? I’m going to tag in @mfenner to get his thoughts about this, but I think this would be an issue (or proposed new functionality) on DataCite’s side

**Comment by flaviofrancisco** [comment]
> Hey @flaviofrancisco! A quick read through seems to indicate that you’d like Test DOIs from DataCite to be resolvable? I’m going to tag in @mfenner to get his thoughts about this, but I think this would be an issue (or proposed new functionality) on DataCite’s side

We read it on DataCite documentations: https://support.datacite.org/docs/create-a-client-in-fabrica-test 

> Your prefixes in test are different from your prefixes in production
The production system and the test system are separate, as are your accounts in both systems. This means that your prefix list in the test system will be different from your prefix list in the production system, so you won't be able to create DOIs in the test system using your normal prefix of choice. **Since the DOIs you create in the test system aren't real and don't resolve,** having different prefixes doesn't matter.

Since they are not resovable I will close this issue.
Thanks @djbrooke  and @pameyer.
