### ISSUE TITLE
Harvard Dataverse custom homepage: "Datasets from journal dataverses" links don't work from mobile or narrow screens

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#5571]
As I mentioned at standup, for the custom home page at https://dataverse.harvard.edu users on mobile phones can't click anything under "Datasets from journal dataverses" including the datasets and the "ALL RECENT JOURNAL ACTIVITY" link. Other dataset links work fine from mobile such as under "Datasets from other dataverses" and from a desktop browser, all links seem to work. I was able to replicate the bug on desktop Firefox by making the width narrow as in the screenshot below:

![screen shot 2019-02-25 at 11 24 09 am](https://user-images.githubusercontent.com/21006/53352256-72bff500-38f0-11e9-9a5b-27f52932e019.png)

Tested on Android and iPhone. @poikilotherm said "Seems like the div is eating too much space" at http://irclog.iq.harvard.edu/dataverse/2019-02-25#i_87142 but I'm not sure what's going on.

**Comment by mheppler** [comment]
Updated the Harvard Dataverse customization files required for production, which can be found in Google Drive at `Dataverse > Harvard Dataverse > Harvard Dataverse Customization > resourcesProd-2019-03-04.zip`.

**Comment by pdurbin** [comment]
The fix in pull request #5599 looks pretty straightforward, changing "col-md" to "col-xs" like this:

![screen shot 2019-03-05 at 12 37 03 pm](https://user-images.githubusercontent.com/21006/53825081-73393b00-3f43-11e9-851e-0d3a386b7ba7.png)
