### ISSUE TITLE
Automatically add custom tags on upload

### ISSUE THREAD

**Issue by TaniaSchlatter** [IQSS/dataverse#5576]
We are working on file table improvements, including the ability to sort by and filter on tags – file tags, DataTags, and custom tags (#3404). 

We are also working on the ability to deposit data from GitHub (#5372), and maintain file hierarchy metadata (#5498, #5572).

Question for the community: when uploading, would it be desirable to add a custom tag – "GitHub" in the upload from GitHub scenario? Similarly, would it be desirable to add a custom tag with the name of the .zip file to files added from a .zip file?

**Comment by mheppler** [comment]
This issue has many related technical dependencies outline in **File Tags - Improve UI/UX and misc. bugs #6074**.

**Comment by pdurbin** [comment]
> Question for the community...

I'm afraid we haven't heard from the community on this one.

Vote to cloe.
