### ISSUE TITLE
email address of dataverse creator visible in API

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#5583]
Noticed some unintuitive behavior when looking at https://github.com/IQSS/dataverse/issues/5549 ; `curl -X GET $host//api/dataverses/$dv_alias` also returns information on the user who created the dataverse; and the `:ExcludeEmailFromExport` setting doesn't have any effect there.

This isn't a bug in `:ExcludeEmailFromExport` (scope for #3443 was datasets), and it's debatable if it's  desirable behavior or not.

**Comment by djbrooke** [comment]
We should consider renaming the config and and applying this to Dataverse email contacts as well.

**Comment by matthew-a-dunlap** [comment]
I feel that the current name is still good if we are just expanding this to the `GET $host//api/dataverses/` endpoint. Even if its not under "export" its functionally one.

**Comment by scolapasta** [comment]
Agreed. I think I was the one suggesting at sprint planning to rename, but your assessment that's it's functionally one is correct.
