### ISSUE TITLE
Add support for the independent handle service setup

### ISSUE THREAD

**Issue by PaulBoon** [IQSS/dataverse#5587]
When registering a handle for a dataset the bean will use a special 'admin' handle to communicate with the service and that is now: '`"0.NA/" + handlePrefix`'
This, however, does not work when the handle service is configured to run as 'Independent' service (No communication with the Global Handle Registry). In that case this 'admin' handle must be '`handlePrefix + "/ADMIN"`'. 

In order to also support the independent handle service we could add a new setting: 
‘`:HandleIsIndependentService`’ = true or false (default)
Or maybe a new JVM option?

Then use the new setting to construct this 'admin' or 'auth' handle in:  
 src/main/java/edu/harvard/iq/dataverse/HandlenetServiceBean.java

**Comment by pdurbin** [comment]
I dragged this to code review at https://waffle.io/IQSS/dataverse to get a pulse from the team (especially @landreev ) on if we would prefer a database setting or a JVM option.

**Comment by djbrooke** [comment]
@paulboon we talked about this after standup, and we think a DB setting (with documentation) is the way to go.  I'm going to move this to our community development column. Feel free to ping us when it's ready for Code Review.  Thanks for the continued contributions!

**Comment by pdurbin** [comment]
I just moved this issue to code review at https://waffle.io/IQSS/dataverse but please be advised that pull request #5604 (for this issue) will be smaller once pull request #5595 (for #4972) is merged. (It probably makes sense to QA this all together.) To preview the smaller "diff", you can use this link: https://github.com/PaulBoon/dataverse/compare/4972-handle-library-upgrade-to-8.1.1...PaulBoon:5587-support-independent-handle-service
