### ISSUE TITLE
Avoid log error message when not using Archiver

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#5590]
if :ArchiverClassName is not set (the default case), things work, but the null classname results in a log message noting that an archiver class can't be loaded. There's no need for such a message - it just pollutes the log. I'll send a PR to suppress it.

**Comment by qqmyers** [comment]
Actually, this should only happen if an archiver workflow is set up, or if you call the submitToArchive api call, or with the new 'update current version' code in #5541, so it should not be affecting v4.11 users who haven't ever set up archiving (just @kcondon during his testing... sorry).

**Comment by qqmyers** [comment]
fixing in #5541...

**Comment by kcondon** [comment]
@qqmyers Updating a file to be restricted allows updating in current version but fails with error in UI, not in server log:
 Error – Dataset Version Update failed. Changes are still in the DRAFT version. - edu.harvard.iq.dataverse.engine.command.exception.IllegalCommandException: Cannot change files in the dataset If you believe this is an error, please contact Harvard Dataverse Support for assistance.

**Comment by pdurbin** [comment]
I just moved this to QA since it's part of the pull request currently under test.
