### ISSUE TITLE
Modify GeoConnect/WorldMap code to fit into Modular Tool Framework

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#5597]
We developed GeoConnect before we came up with the Modular Tool Framework, so the core Dataverse code has hardcoded logic for this. We want to extract this out and make it work as a modular tool.

From Dataverse this will likely look like two tools, one to configure the data that Dataverse needs and the second to explore the data. We should be able to separate this into (at least) two chunks for that.

**Comment by djbrooke** [comment]
Closing this, as the migration of worldmap.harvard.edu to new infrastructure is resulting in Geoconnect and Worldmap being able to no longer communicate. We can investigate new Geospatial explore/analysis solutions in the future and will reopen specific issues as needed.
