### ISSUE TITLE
broken 404 page

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#5609]
Mentioning on the off chance this is not a duplicate (feel free to close if so); but the 404 page for `{"version":"4.11","build":"1236-3721306"}` appears to be broken:

![screen shot 2019-03-06 at 6 01 02 pm](https://user-images.githubusercontent.com/10261853/53920059-d73e2b00-4039-11e9-8f27-458a89d228b9.png)

**Comment by pdurbin** [comment]
Related: #5589

**Comment by mheppler** [comment]
I'd be willing to suggest these are related issues. See my most recent comment and screenshot in #5589.

**Comment by pameyer** [comment]
@pdurbin @mheppler Looks related to me (although this was on me typo'ing a  dataverse page, not an unpublished dataset).

**Comment by djbrooke** [comment]
Closing in favor of #5589, which was estimated in sprint planning today. No hard feelings, @pameyer :)

**Comment by pameyer** [comment]
0 hard feelings @djbrooke :)
