### ISSUE TITLE
Documentation UI

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#561]
---

Author Name: **Elizabeth Quigley** (@eaquigley)
Original Redmine Issue: 3979, https://redmine.hmdc.harvard.edu/issues/3979
Original Date: 2014-05-14
Original Assignee: Mike Heppler

---

Further develop UI for documentation. 
Includes:
-Branding
-Moving Search Bar out of header
-Header (move persistent header from Beta into documentation so it looks like it is all in the same application)
-Navigation
-Table of Contents

**Comment by eaquigley** [comment]
Guides from dataverse.org have navigation in the header but guides from dataverse.harvard.edu don't. @mcrosas @mheppler can we review this in today's UI/UX meeting?

**Comment by mheppler** [comment]
- [ ] Change "Dataverse Project" navbar header and link to read "Dataverse Guides {VersionNumber}" (version number in smaller font) and link to "{DataverseInstalltion}/guides/index.html"

**Comment by mheppler** [comment]
With the changes to how the User Guides are hosted and linked, this fix to the navbar is no longer required, per @mcrosas @scolapasta @eaquigley . Closing.
