### ISSUE TITLE
Feature Request - Confirmation pop-up to confirm ['Grant' access/assign access permissions] to Restricted data

### ISSUE THREAD

**Issue by mdmADA** [IQSS/dataverse#5610]
To prevent an inadvertent release of restricted data, when an admin-type user:

- clicks "Grant" for a restricted file OR
- assigns access permissions to a user/group on a dataset that contains at least one Restricted file

=> pop up a confirmation: "You are granting access to Restricted files. Continue?" with Continue/Cancel buttons (or something similar) to remind the user to double-check they want to grant access to that user/group for that restricted data.

**Comment by pdurbin** [comment]
@mdmADA makes sense. Is this a feature you're considering implementing? And making a pull request? Or are you just putting the idea out there? Hopefully, people who are clicking "Grant" understand that the "Grant" button only appears for restricted file. (The user who wants the file has gone through the "request access" workflow already.) Files that are not restricted can simply be downloaded (though sometimes there are some click through Terms of Use to agree to or a guestbook to fill out). I understand that in your installation 99% of files are restricted so your users may not encounter public (non-restricted) files very often.

**Comment by mdmADA** [comment]
Hi Phil - Perhaps the 'warning' would have to be a bit more specific - "You are about to Grant access for <dataset/datafile> to <user>(s)" or something to remind the "granter" to double-check who they're about to grant it to.


Our admin-type users know that Grant only appears for requested (restricted) data but not all who request access should be granted access so it would be an additional visual reminder to double check who you're about to grant it to. When you have a lot of people requesting access at once, it might (?) be easy to accidentally include somebody that shouldn't have access.


Perhaps such a pop-up would apply to only to "ultra-sensitive" data if there is going to be such a designation (or similar) in the sensitive data rollout. 

Or perhaps the pop-up should be triggered by a flag to set for extremely sensitive data/datasets -> this might be a more effective solution since the user would really take notice when it did pop up - "Hey, this is extremely sensitive - make sure you double check who you're giving this to". 


As for implementation, I put it out there as an idea. I am not sure when I would be able to get to it to implement it myself... 


Thanks!

**Comment by TaniaSchlatter** [comment]
Potentially related to #871 – Integrate with Datatags

**Comment by pdurbin** [comment]
@mdmADA hi! It's been little while. Still interested in this? Thanks.

**Comment by mdmADA** [comment]
Hi @pdurbin - It has been a while. ADA is interested in it as a double check, but it isn't critical.

Thanks!

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
