### ISSUE TITLE
Add Data popup message as a warning and not an error

### ISSUE THREAD

**Issue by TaniaSchlatter** [IQSS/dataverse#5614]
The message in the Add Data popup should not be displayed as an error, as it is informative and invites people to log in. 

This:
![Add_data_popup_muted_message](https://user-images.githubusercontent.com/15386424/54311551-33113280-45ab-11e9-8bdd-9a9492bea052.png)

Or even better, this:
![Add_data_popup_muted_message_buttons](https://user-images.githubusercontent.com/15386424/54311454-fb09ef80-45aa-11e9-9e8e-d3c837bb45e3.png)

Not this:
![screen shot 2019-03-07 at 11 55 31 am](https://user-images.githubusercontent.com/15386424/53976854-d65ad700-40d5-11e9-8b61-9d512ecdbf8d.png)

**Comment by mheppler** [comment]
Or...

![Screen Shot 2019-03-26 at 2 12 41 PM](https://user-images.githubusercontent.com/687227/55022574-3f48b700-4fd1-11e9-85fa-f847e0ce5b45.png)
