### ISSUE TITLE
ImageMagick install now requires an edit of policy.xml

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#5617]
Following the DV docs to install ImageMagick to support pdf thumbnails, I found that I had to edit a line in /etc/ImageMagick/policy.xml, changing
`policy domain="coder" rights="none" pattern="PDF"`
to
`policy domain="coder" rights="read" pattern="PDF"`

to get any pdf thumbnails. There were no log messages but I looked in the source and tried running the convert command  from there manually and found, with some web searching, that this was the issue.

From [https://launchpad.net/ubuntu/+source/imagemagick/8:6.7.7.10-6ubuntu3.13|https://launchpad.net/ubuntu/+source/imagemagick/8:6.7.7.10-6ubuntu3.13]

```
  * SECURITY UPDATE: code execution vulnerabilities in ghostscript as
    invoked by imagemagick
    - debian/patches/200-disable-ghostscript-formats.patch: disable
      ghostscript handled types by default in policy.xml

```
I gather that this change in the default was due to a ghostscript security issue, which, if I follow correctly, has since been fixed. However, at least on Ubuntu14.4 an apt-get install imagemagick, a current install gets the 6.7.7.10 version of imagemagick that still has this policy.xml default. (The ghostscript downloaded is 9.26 which is newer than the pre9.24 versions that were affected.)

So FYI and, if this can be replicated elsewhere, this additional step may need to be added to the docs. (FWIW: We'll be able to test on Ubuntu 18 soon...).

**Comment by donsizemore** [comment]
I just tested on an Ubuntu 18.04 VM, which installed version 6.9.7.4 and set the PDF policy to none as you found.

My RHEL7 VMs (including a "clean" install of 6.7.8.9 on CentOS7) don't mention PDFs in policy.xml.

**Comment by pdurbin** [comment]
CentOS is preferred over Ubuntu by @IQSS but I'm certainly open to a pull request that helps explain to Debian or Ubuntu users that this config change is important.

**Comment by qqmyers** [comment]
for us, the policy.xml file on Ubuntu 18 was /etc/ImageMagick-6/policy.xml - edit still needed for pdf previews.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
