### ISSUE TITLE
Dataverse v4.11 facets translation

### ISSUE THREAD

**Issue by juancorr** [IQSS/dataverse#5623]
Dataverse v4.11 facets are not properly translated to French and Spanish. This issue affect to dataverse-language-pack project too. There are some facets that are not translated, other facets with a wrong translation and  other that are properly translated:
  - "Dataverse Category", "Publication Year" and "Subject" are not translated.
  - "Auteur Nom" and  "Mot-Clé Terme" should be "Auteur", "Mot-Clé" or "Auteur: Nom", "Mot-Clé: Terme"

![image](https://user-images.githubusercontent.com/325896/54208253-d7c43f00-44db-11e9-8df1-b3fdd0939513.png)

**Comment by pdurbin** [comment]
Related: #5207

**Comment by JayanthyChengan** [comment]
@juancorr - these were handled in PR https://github.com/IQSS/dataverse/pull/5618 (Still in code review)
also we deployed in production: https://dataverse.scholarsportal.info/dataverse.xhtml

**Comment by scolapasta** [comment]
Closing issue in favor of #5207
