### ISSUE TITLE
Add Login mechanism to Info shown when Access is Requested

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#5630]
When a user requests access to a file, the curator is shown the name, username, and e-mail. We want to add the login mechanism (shibboleth / institution, orcid, etc.) to provide additional context.

**Comment by pdurbin** [comment]
It sounds like we're not sure if HarvardKey users will show up as "shib" or "Harvard University" so we should probably test that.

**Comment by sekmiller** [comment]
Here is the current key associating provider Ids to display values (from the Bundle)

authenticationProvider.name.builtin=Dataverse
authenticationProvider.name.null=(provider is unknown)
authenticationProvider.name.github=GitHub
authenticationProvider.name.google=Google
authenticationProvider.name.orcid=ORCiD
authenticationProvider.name.orcid-sandbox=ORCiD Sandbox
authenticationProvider.name.shib=Shibboleth
