### ISSUE TITLE
Downloading records on dataverse

### ISSUE THREAD

**Issue by chaudj** [IQSS/dataverse#5633]
I know I have asked this before but I dont think it has been resolved yet. Would we have a easier way to download records on Dataverse (Harvard hosted Dataverses). Like having an export functionality to get datasets for maybe a particular year, subject etc?

**Comment by djbrooke** [comment]
Hi @chaudj - can you expand on this a bit more? I believe this can all be accomplished using the APIs, but I want to make sure I understand your request.

**Comment by djbrooke** [comment]
Hi @chaudj - I'm going to close this, but if you have other thoughts please let me know.
