### ISSUE TITLE
Create new Unit Tests

### ISSUE THREAD

**Issue by alexscheitlin** [IQSS/dataverse#5634]
We, [nikzaugg](https://github.com/nikzaugg), [rschlaefli](https://github.com/rschlaefli) and [alexscheitlin](https://github.com/alexscheitlin), again focus on improving the testing (see #5619).

This time we will test a few methods that are not covered so far.

**Comment by djbrooke** [comment]
@nikzaugg - @matthew-a-dunlap added one requested change in the PR. I moved this back to the Community Dev column on https://waffle.io/IQSS/dataverse. Let us know when it's ready for another code review pass! Thank you!
