### ISSUE TITLE
Move/Alias more commands in new Users endpoint

### ISSUE THREAD

**Issue by matthew-a-dunlap** [IQSS/dataverse#5646]
With the creation of new user commands in #5514 & #5515, we've gone with the approach of creating a new path of `api/users` for these commands. This was in part because wanted these commands to be available to superusers and not just sysadmins on running commands on the server.

With the creation of this path, there are other commands that could be moved or aliased here for better api usability. Some of these may be admin level commands we want to allow to be accessible to a wider population (e.x. `/api/admin/authenticatedUsers/$userIdentifier`, and other are public commands that may just need a better location.

**Comment by pdurbin** [comment]
@matthew-a-dunlap are you still interested in this?
