### ISSUE TITLE
Dataset - Peer Reviewed Tag or Badge

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#565]
---

Author Name: **Eleni Castro** (@posixeleni)
Original Redmine Issue: 3984, https://redmine.hmdc.harvard.edu/issues/3984
Original Date: 2014-05-14

---

User who is a Publisher and is setting up a journal Dataverse recommended that we have a way to flag datasets that have gone through a data peer-review process. We could demonstrate a peer-reviewed dataset with a tag or badge similar to the Center for Open Science's Data Badges: http://centerforopenscience.org/journals/

**Comment by pdurbin** [comment]
This "Idea: badges/icons for CV's" thread is related: https://groups.google.com/forum/#!topic/openscienceframework/7oeul9pusKg

**Comment by pdurbin** [comment]
I'd like to point out that datasets such as https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/GSQG1K already have badges and above them it says, "The associated article has been awarded Open Materials and Open Data Badges. Learn more about the Open Practice Badges from the Center for Open Science."

Here's a screenshot:

<img width="1563" alt="screen shot 2018-10-03 at 9 30 46 pm" src="https://user-images.githubusercontent.com/21006/46448231-c2d8c800-c753-11e8-8861-10a74c8b8d2e.png">

Note that above the text about the badge, it says "This dataset underwent an independent verification process that replicated the tables and figures in the primary article. For the supplementary materials, verification was performed solely for the successful execution of code. The verification process was carried out by the Odum Institute for Research in Social Science at the University of North Carolina at Chapel Hill."

So what is the definition of done for this issue? Is it done already? Vote to close.

**Comment by mheppler** [comment]
Those are images and links that were manually added by the depositor to the Notes metadata field. This issue is requesting built in functionality provided by the system as opposed to something external and manual.

Vote to remove the Vote to Close label.

**Comment by pdurbin** [comment]
Removed! Thanks for helping me understand. I see what you mean about how the "Notes" field is being used or abused to have badges in it. Suboptimal but a clever workaround. 😄

**Comment by djbrooke** [comment]
Closing this in favor of #6041 for a more generalized approach.
