### ISSUE TITLE
Migrate away from Waffle before May 16, 2019

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#5651]
@scolapasta noticed that Waffle is shutting down! https://blog.waffle.io/farewell-from-waffle-%EF%B8%8F-794da4a72851

This is extremely sad news. The Waffle team even sent us [stickers][] after we did a call with them some years back:

![Screen Shot 2019-03-15 at 12 26 44 PM](https://user-images.githubusercontent.com/21006/54446586-a8047980-471d-11e9-9529-540363f43727.png)

[stickers]: https://twitter.com/philipdurbin/status/836326514828378112

https://help.waffle.io/waffle-shutdown (linked from the blog post) suggests migrating to GitHub Projects.

Sadly, we'll need to remove reference to Waffle from our docs:

```
$ ack -i waffle
README.md
20:[![Waffle.io - Columns and their card count](https://badge.waffle.io/IQSS/dataverse.svg?columns=all)](https://waffle.io/IQSS/dataverse)

CONTRIBUTING.md
60:After making your pull request, your goal should be to help it advance through our kanban board at https://waffle.io/IQSS/dataverse . If no one has moved your pull request to the code review column in a timely manner, please reach out. Thanks!

doc/sphinx-guides/source/developers/intro.rst
37:You can get a sense of what's currently in flight (in dev, in QA, etc.) by looking at https://waffle.io/IQSS/dataverse

doc/sphinx-guides/source/developers/version-control.rst
85:Make a pull request to get approval to merge your changes into the develop branch. Feedback on the pull request template we use is welcome! The "connects to #3728" syntax is important because it's used at https://waffle.io/IQSS/dataverse to associate pull requests with issues.
92:Now that you've made your pull request, your goal is to make sure it appears in the "Code Review" column at https://waffle.io/IQSS/dataverse 
```

We won't need the magic "connect to" syntax anymore either:

```
$ ack connects PULL_REQUEST_TEMPLATE.md 
- connects to #ISSUE_NUMBER: ISSUE_TITLE
```

**Comment by pdurbin** [comment]
@adam3smith feels me:

<img width="590" alt="Screen Shot 2019-03-15 at 5 21 08 PM" src="https://user-images.githubusercontent.com/21006/54462648-dba7c980-4746-11e9-9f74-2664fe12fbb1.png">

https://twitter.com/philipdurbin/status/1106637350774423552

It was even sadder to see the animated version Ana sent me:

![cry](https://user-images.githubusercontent.com/21006/54462728-20cbfb80-4747-11e9-9c1f-e87018b10e9c.gif)

**Comment by poikilotherm** [comment]
Sorry to hear Waffle is closing.

Options I am aware of not involving migration to GitHub Projects:
* [You could ask Atlassian for a free plan for JIRA on-premise or JIRA Cloud](https://de.atlassian.com/software/views/open-source-license-request). They offer a pretty nice Scrum/Kanban board.
  * There are options to sync between both JIRA issues and GitHub Issues
  * Or just offer public access to anyone and migrate.
* Try to connect [Wekan](https://wekan.github.io/) or [Kanboard](kanboard.net) via webhooks
* About a year ago I had a short look on http://zube.io, it looked at least visually appealing.

**Comment by djbrooke** [comment]
I'll be poking at this over the next few days and getting us into a good place with Github projects. General steps:

- [ ] run the waffle API to get a data dump and convert to .csv (most of the stuff is mirrored in github, but some stuff like estimates are not)
- [ ] smash that migrate button
- [ ] clean up the resulting Github project
- [ ] run the two in parallel a few days and figure out what processes of ours will be different
- [ ] when we're ready to cut over, update the docs and message the community

**Comment by pdurbin** [comment]
Is there a newer, better example pull request than `#3827`? This pull request is held up as an example at http://guides.dataverse.org/en/4.14/developers/version-control.html#make-a-pull-request
