### ISSUE TITLE
RFE: Update example/initial admin user password for consistency

### ISSUE THREAD

**Issue by atc0005** [IQSS/dataverse#5652]
While working with the Ansible Playbook we found that the initial password there was different than the initial password provided in the installation docs here:

http://guides.dataverse.org/en/latest/installation/installation-main.html#superuser-account

Current wording:

> Use the following credentials to log in:
> 
>     URL: http://localhost:8080
>     username: dataverseAdmin
>     password: admin

Due to IQSS/dataverse-ansible#48, the Playbook is now using `admin1` as the initial password. Perhaps update the password here to match that one?

CC: @pdurbin, @auadamw

**Comment by pdurbin** [comment]
@atc0005 thanks for opening this issue. If you or @auadamw or anyone would like to make a pull request, it should be fairly straightforward. Here are the files in play:

```
$ grep ^DV_SU_PASSWORD scripts/api/setup-all.sh
DV_SU_PASSWORD="admin"
$ grep -C1 ': admin' doc/sphinx-guides/source/installation/installation-main.rst 
- username: dataverseAdmin
- password: admin
$ grep 'default password' doc/sphinx-guides/source/installation/config.rst
The default password for the "dataverseAdmin" superuser account is "admin", as mentioned in the :doc:`installation-main` section, and you should change it, of course.
$ grep dataverseAdmin doc/sphinx-guides/source/developers/testing.rst
In your browser, log in as dataverseAdmin (password: admin) and click the "Edit" button for your root dataverse. Navigate to Permissions, then the Edit Access button. Under "Who can add to this dataverse?" choose "Anyone with a dataverse account can add sub dataverses" if it isn't set to this already.
```

**Comment by atc0005** [comment]
Just to double-check, draft PRs against the `develop` branch?

refs http://guides.dataverse.org/en/latest/developers/version-control.html

**Comment by pdurbin** [comment]
@atc0005 yes please! We're using git-flow, if you're familiar with it. "develop" instead of "master" branch.

**Comment by pdurbin** [comment]
@atc0005 (years later 😄 ) are you still interested in this? Maybe we can talk it out in https://chat.dataverse.org before you make your pull request. Thanks.

**Comment by pdurbin** [comment]
@atc0005 thanks for getting back to me so quickly. Good luck on your new endeavors! I'll go ahead and close this out.
