### ISSUE TITLE
Edit File Metadata does not validate (saves with old (valid) value)

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#5654]
When you upload a file or edit a file, the metadata validation is not working. A valid value will save, but an invalid one will appear to save and just keep the old (valid) value.

This is true for label, and the new (soon to be merged) path. I didn't test with description, but I assume it is also true there.

The same fragment is used for create dataset and there it does work properly.

**Comment by sekmiller** [comment]
Rendering the save button within a p:fragment was limiting its scope (to basically nothing)
Changing the render to ui:fragment fixes it, also removed ancillary code
