### ISSUE TITLE
slow shibboleth account creation

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#5659]
on `"version":"4.10.1","build":"1178-1a12cda"` ; creating new shibboleth accounts (aka - hitting save after initial shib login) is reported as taking > ~1m.  May or may not be due to running in a non-standard / unsupported configuration; will investigate further.

**Comment by donsizemore** [comment]
@pameyer I just made Andrey sign in to our test instance (4.11, shibd 3.0.4). He timed it at 961ms.

**Comment by pameyer** [comment]
@donsizemore Thanks! That makes it seem like the slow-down is something outside Dataverse.  I'll update if/when I find anything useful.

**Comment by pameyer** [comment]
For future reference, this was symptomatic of making changes to the mail server without updating the dataverse configuration.  Page delay was due to timeout contacting the mail server (clearly shown in server.log).

Curiously, authenticateduser.emailconfirmed acts as though the email is confirmed even when the email server connection times out (at least for shib users).

**Comment by pdurbin** [comment]
> Curiously, authenticateduser.emailconfirmed acts as though the email is confirmed even when the email server connection times out (at least for shib users).

This is by design for shib users ("Institutional Log In" users): "Users of the Institutional Log In option are not required to verify their email address because the institution providing the email address is trusted." http://guides.dataverse.org/en/4.11/user/account.html#edit-account
