### ISSUE TITLE
Doc update: TestShib not available anymore

### ISSUE THREAD

**Issue by poikilotherm** [IQSS/dataverse#5666]
TestShib.org referenced in the [Shibboleth docs](http://guides.dataverse.org/en/latest/installation/shibboleth.html#id36) for testing your SP is not available anymore.

Instead, https://samltest.id can be used for testing purposes. This will be done for IQSS/dataverse-kubernetes#14.

**Comment by pdurbin** [comment]
This is a duplicate of #5369

@poikilotherm would you like to make a pull request? 😄

**Comment by poikilotherm** [comment]
Sorry for the duplicate. Shall I close this in favor of the original issue?

**Comment by pdurbin** [comment]
@poikilotherm no worries. We appreciate the bug report. I'll close it.
