### ISSUE TITLE
Investigate what content to put into meta description tags of dataverses/datasets/files when depositors haven't entered description metadata

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#5672]
In the page html of dataverses, datasets, and files that have no description metadata, the various meta tags are empty (`<meta name="description">`, `<meta name="dc.description">`, and `<meta name="og.description">`).(https://github.com/IQSS/dataverse/issues/4894 describes how we'll add description metadata to the page html of dataverses, datasets, and files that **do** have description metadata.)

For example, the published dataset at https://doi.org/10.7910/DVN/UCVPTW has no description metadata (published before the description metadata field became a required field) , so its description meta tags are empty.

After Open Graph tags are added to dataset pages (https://github.com/IQSS/dataverse/issues/5640), the html of dataverse, dataset and file pages will contain between one or three types of meta tags for description metadata. They are each added for different reasons:

Meta tag | Description | Which pages?
------------ | ------------ | ------------
`<meta name="description">` | Basic meta tag that search engines consider | dataverses, datasets, files
`<meta name="dc.description">` | Dublin Core meta tags added because citation managers, like Zotero, pull metadata from them | datasets
`<meta name="og.description">` | Open Graph meta tags added because social media platforms like Facebook display them | datasets

(There's also description metadata in Schema.org standard using json-ld, but it's limited to datasets and added so that datasets are index in [Google's Dataset Search](https://toolbox.google.com/datasetsearch).)

When depositors haven't entered description metadata for dataverses/datasets/files, what information should go in these meta description tags ?

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
