### ISSUE TITLE
UZH: Adding unit tests (input-space partitioning, branch & prime-path coverage)

### ISSUE THREAD

**Issue by rschlaefli** [IQSS/dataverse#5673]
Hi!

Me (@rschlaefli), @alexscheitlin, and @nikzaugg have received our second assignment and will again be working on new unit tests. This time, we will be focusing on a clean partitioning of the input space for the tested methods, as well as increasing branch and prime-path coverage. We will track our progress with the assignment on this issue.

Please see #5619 for who we are and what we do.

**Comment by djbrooke** [comment]
Thanks UZH team for creating this issue and the continued work on the unit tests! If you want to talk through any implementation details before you start on this, let us know.

**Comment by matthew-a-dunlap** [comment]
Note that with this PR there is an actual code change. Tests were written for StringUtils.truncateString , but that code was unused in our codebase and was very old, so I had @rschlaefli remove the method itself. As it is unused there should be no impact.
