### ISSUE TITLE
Streamline DataFile Metadata Creation/Read/Update

### ISSUE THREAD

**Issue by matthew-a-dunlap** [IQSS/dataverse#5674]
- [x] Direct API endpoint to `GET` file level metadata. Using the JSON syntax we use for add/replace.
   - [x] access via file PIDs
   - [x] Access previous versions
   - [x] Access draft version if authorized
   - [x] All attributes
   
- [x] API endpoint to update metadata without uploading a new file. This will be based off the file `/update` code.
   - [x] All attributes
   - [x] Restrict file if restrict is passed
   - [x] General tests
      - [x] Tags
      - [x] File hierarchy
   - [x] Should error if you attempt to update when there is already a draft

- [x] Documentation
- [x] Merge develop

**Comment by matthew-a-dunlap** [comment]
One question I have is what paths do we want? 
   - `GET` `files/{fileId}` fits the same structure as dataset, but to me conveys you are getting actual data not metadata.
   - `GET` `files/{fileId}/metadata` seems to be more straightforward.
   - I am adding an option to get the version as well, so `GET` `files/{fileId}/versionId/{vId}` and `GET` `files/{fileId}/metadata/versionId/{vId}` need to be weighed
      - Or `GET` `files/{fileId}/versionId/{vId}/metadata/`, tho this conveys that other `files/{fileId}` endpoints support versions

**Comment by matthew-a-dunlap** [comment]
Working on this story, I had to decide between two JSON "schema" used in our code to expand upon for this story. One is the schema used by most of the dataset methods, the other by the file-update and dataset-addFile commands. Both had some ability to edit file metadata.

I went with the latter one (used by update/add) as that code is more used in practice and amenable to expanding for fileMetadata `GET` and `POST` methods. Most important, the existing file-update method already contains the `POST` functionality needed, it just needs to be altered to not require a file upload.

Before this decision I had started down the road of expanding functionality based on Dataset JSON schema, so today I changed my `GET` method over to the other schema. This involved fixing the incomplete serializer that had already been created but was unused in our code. 

I'm hoping that this part of the work should only take another day or two, as the tests are mostly written and it shouldn't be too hard to break out the metadata part of the update endpoint. We had previously discussed fixing issues with dataset update allowing file MD5 to be changed (the goal was to make it superuser only), but with this new approach that code is not being touched. I think we should move that work to another story.

**Comment by matthew-a-dunlap** [comment]
Overview of the connected PR:
- Created 3 new File API endpoints: `GET files/{id}/metadata`, `GET files/{id}/metadata/draft`, ``POST files/{id}/metadata`
   - Based off the existing `POST {id}/replace` code
   - The fileMetadata on the dataFile is replaced entirely by what is `POST`ed. So if you want to edit just one attribute you must get the metadata and then post it back.
   - Junk json provided to the `POST` endpoint will be ignored the same as `POST files/{id}/replace`
   - See the `native-api.rst` documentation for more info
- Minor changes were made to code that underlies `POST files/{id}/replace` and `POST datasets/{id}/add`, those should be retested
- Doc changes were done to `GET`/`POST` metadata and replace. Also some minor doc fixes that were erroring in sphinx

**Comment by pdurbin** [comment]
@matthew-a-dunlap here are the failing API tests I showed you: https://github.com/IQSS/dataverse/pull/5715#issuecomment-479651709

**Comment by matthew-a-dunlap** [comment]
This is actually broken in develop. I'm moving this back to code review but yea still needs to be fixed.

**Comment by kcondon** [comment]
Issues/Questions:
1. Errors thrown are often html pages: 500, 404, etc. Should they report just the http error itself? Is there a standard for our API?
2. Calling draft metadata with no key results in 500 error. Should this be handled better/sooner, with a different error code?

**Comment by pdurbin** [comment]
Since this is the native API, errors should be reported in JSON format. APIs that are XML-based such as SWORD should (and do, as far as I know), report errors in XML format. I can't think of a time that any of our APIs should report in HTML format.

**Comment by pdurbin** [comment]
I just stumbled across this issue: Uploading data file through API and with json params = {} overwrites UNF/file description in UI #5010

It would probably be nice to test that scenario and reply on that issue with any findings.

**Comment by matthew-a-dunlap** [comment]
@scolapasta I'm curious what your take is on Kevin's #3 above. The output is misleading for sure. We could change the name of the element in the JSON but it'll probably break someone's integration.

**Comment by matthew-a-dunlap** [comment]
Talking with @scolapasta we decided #3 we will not change at this time even though it is confusing. This is to not break any integrations. I have added a note to the native-api rst about the id attribute.
