### ISSUE TITLE
Investigate possibility of using COUNTER standard for reporting and sharing Dataverse download stats

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#568]
---

Author Name: **Kevin Condon** (@kcondon)
Original Redmine Issue: 3987, https://redmine.hmdc.harvard.edu/issues/3987
Original Date: 2014-05-16

---

Came from a user who is installing their own dataverse, see RT # 171127

Are the download statistics of DVN compatible with the counter standard
(http://www.projectcounter.org/) or is it planned to be counter compatible.

**Comment by eaquigley** [comment]
@posixeleni remember we were going to plan a meeting with impact story once you were back. should we still do that?

**Comment by posixeleni** [comment]
I will follow-up with them to see if they can meet with us.

**Comment by posixeleni** [comment]
@eaquigley and I spoke with Almetrics about using their repository badges to track metrics for datasets in Dataverse.

They pointed us to this small piece of code which would need to be embedded into each dataset page and would just the section to be populated

```
<div data-badge-popover="right" data-badge-type="medium-donut" data-doi="10.5072/FK2/PTU9PK" data-hide-no-mentions="true" data-hide-less-than="1" class="altmetric-embed"></div>
```

**Comment by posixeleni** [comment]
Created a new issue to track Altmetric #2899 and keeping this one for Counter, since they each deal with different kinds of metrics.

Email from Scholars Portal (Alan) had some useful info for us to look into Counter more for download stats

>Ran across this information from JISC about creating COUNTER compliant statistics related to data downloading.  

>https://www.jisc.ac.uk/irus

>I have not looked at the usage statistics that are available from Dataverse, but imagine that this will become more important to demonstrate the scope of data reuse in relation to new funder requirements for data preservation.

**Comment by posixeleni** [comment]
http://www.slideshare.net/JiscRDM/research-data-metrics-for-usage (another item to read when working on COUNTER)
