### ISSUE TITLE
File Upload: the following zip file "issues" should not prevent success upload of zip content

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#5683]
When users have a zip folder containing an "empty" folder (usually designated to hold new files created from running the code), or the zip folder contains "shape files"---the zip will not upload and will not throw an error of why it failed.

**Comment by djbrooke** [comment]
@sbarbosadataverse - if the problematic zips are OK to include here, please do so. If not, feel free to email them to me. Thanks!

**Comment by sbarbosadataverse** [comment]
sending via dropbox link @djbrooke

**Comment by mheppler** [comment]
Related to _Duplicate Files - publish a dataset that contains files with the same content, which are handled differently #4813_.

**Comment by djbrooke** [comment]
Closing in favor of #6627, will link this issue from there.
