### ISSUE TITLE
ORCID 3.0

### ISSUE THREAD

**Issue by pameyer** [IQSS/dataverse#5689]
For future reference / planning; the ORCID 3.0 API (https://github.com/ORCID/ORCID-Source/blob/master/orcid-model/src/main/resources/record_3.0_rc1/README.md) has been announced to be the default API version in the next year; with continued support for 2.0 and 2.1.

**Comment by pdurbin** [comment]
@pameyer thanks for the heads up. Will ORCID API 2.0 and 2.1 be supported indefinitely? I don't see anything about EOL dates in the README you linked.

**Comment by pameyer** [comment]
@pdurbin "for the foreseeable future" is the level of detail I've got.

**Comment by pdurbin** [comment]
https://info.orcid.org/api-version-policy/ looks like a good resource. It's not immediately clear to me when we need to worry about ORCID API version changes.

That page does indicate that

- ORCID API 3.x was released in May 2019
- ORCID aims to support 2 major API versions at a time
- ORCID releases a new major API version every 2-4 years

From a quick look I'm not seeing anything about ORCID API 4.x.
