### ISSUE TITLE
Refactor/Revisit "My Data"

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#5696]
"My Data" is good and useful. While it appears very similar to our usual search result pages, it's built differently. This has resulted in some challenges (#3038 is the latest) as we basically need to maintain and troubleshoot different versions of the same view. In the interest of maintenance, we should simplify and consolidate this code where possible.

**Comment by mheppler** [comment]
Found an old to-do list from the original My Data development effort. I am closing that and leaving a link here. I am sure there are other My Data-related issues that are consolidation candidates, but I will leave that effort up to @djbrooke.

>MyData - card attributes #2410
>
>-  Add file tags to final cards
>- Add affiliations to final dataverse card -- single query to grab all dataverse affiliations.
>- logic for displaying correct icons for file cards

**Comment by TaniaSchlatter** [comment]
**Notes from recent discussion in Slack with @sbarbosadataverse and @scolapasta about My Data**

Original use cases addressed by My Data:

- as a superuser, show me all objects (files, datasets, dataverses) related to a username, so I can edit/assist/curate.

- as a user (any type), show me objects that have a license to which I have been granted access. This means I am able to download/view.

- as a user (any type), show me objects that I have been invited to contribute to/edit/curate.

@sbarbosadataverse questions if the MyData feature is serving too many functions, adding:

1. When you select mydata, all roles listed on the left are already selected for you.  You have to unselect each one to get the one you want to see.
2. Maybe a separate tab for displaying restricted  data one can  access/download by affiliation or permission (licensed data)
3. One tab for "data I can manage"
These also don't solve the problem that inserting a username in the open username search box doesn't work for super users

**Comment by djbrooke** [comment]
Thx @TaniaSchlatter @sbarbosadataverse and @scolapasta. I created this issue originally to be purely refactoring, and not to change any of the functionality. I'll retitle this to indicate that we'll want this to be a bit broader if we get a chance to prioritize this.

**Comment by TaniaSchlatter** [comment]
Related to https://github.com/IQSS/dataverse/issues/7239: My Data->"results by username" field: The “results by username” field should display the content created by the "username" inserted in that field

**Comment by pdurbin** [comment]
> * as a user (any type), show me objects that have a license to which I have been granted access. This means I am able to download/view.

Sometimes the user sees more objects than they want under My Data. In this issue I explain that I have to uncheck "File Downloader" to see only the datasets that are mine:

- How many datasets do I have? Are these 163 more things really My Data? #5880
