### ISSUE TITLE
4.12 tag/release is inconsistent with the rest, not prepended with a "v"

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#5709]
I predict the lack of the "v" in the 4.12 release will cause problems downstream in projects like dataverse-ansible, dataverse-docker, and dataverse-kubernetes. Hopefully it's straightforward to add it.

<img width="503" alt="Screen Shot 2019-04-02 at 7 32 58 AM" src="https://user-images.githubusercontent.com/21006/55399674-c0480700-5519-11e9-9047-001ea366e3fd.png">

**Comment by poikilotherm** [comment]
Good catch @pdurbin!

Thanks for creating the issue, it would have broken my build in IQSS/dataverse-kubernetes#18 later on...

A quick fix would be very much appreciated!

**Comment by djbrooke** [comment]
All set!

**Comment by pdurbin** [comment]
@djbrooke thanks but can we delete the old tag? It's still there:

![Screen Shot 2019-04-02 at 9 02 02 AM](https://user-images.githubusercontent.com/21006/55404524-102ccb00-5526-11e9-9564-d2bcd1d41f02.png)

**Comment by djbrooke** [comment]
@pdurbin I'm not sure how to do it through the Github UI. I'll do a little research, but may check in with you when I'm in the office.

**Comment by pdurbin** [comment]
@djbrooke sounds good. Below is an example of where the old "4.12" tag appears. We **could** also rename 4.0 to v4.0 and clean up the other weird tags while we're in there, if you want:

![Screen Shot 2019-04-02 at 9 10 06 AM](https://user-images.githubusercontent.com/21006/55405060-41f26180-5527-11e9-8857-07456feb8c84.png)

**Comment by djbrooke** [comment]
Thanks @pdurbin for showing me how to delete tags through the UI. I deleted the "accessibility" tag, but am keeping 4.0 as it's tied to a release and I'm not sure about the "untagged-a..." one.
