### ISSUE TITLE
As the creator of a dataverse I'd like to know how to make an "Add Data" button appear for non-logged in users to encourage user interaction

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#5718]
Today I learned that I can make an "Add Data" button appear on my dataverse for non-logged in users by simply updating the permissions of my dataverse to switch away from "Anyone adding to this dataverse needs to be given access" (screenshots below).

The definition of done for this issue is an update to the User Guide to explain this.

My hope is that the presence of an "Add Data" button on my dataverse will encourage user engagement. Maybe people who have an interest in open source at Harvard (the topic of my dataverse) will create a dataset. Maybe people will link my dataset to their dataverse. Maybe people who don't even have an account on Harvard Dataverse will create one.

## Before: no "Add Data" button

![Screen Shot 2019-04-03 at 12 00 17 PM](https://user-images.githubusercontent.com/21006/55494429-c23cc380-5608-11e9-8ed2-675ae0ebf117.png)
![Screen Shot 2019-04-03 at 12 00 45 PM](https://user-images.githubusercontent.com/21006/55494430-c23cc380-5608-11e9-9534-fd795b74079a.png)
![Screen Shot 2019-04-03 at 12 00 57 PM](https://user-images.githubusercontent.com/21006/55494431-c23cc380-5608-11e9-941b-ae550038a762.png)
![Screen Shot 2019-04-03 at 12 01 35 PM](https://user-images.githubusercontent.com/21006/55494432-c23cc380-5608-11e9-95e7-989a0e71f822.png)
![Screen Shot 2019-04-03 at 12 01 45 PM](https://user-images.githubusercontent.com/21006/55494434-c23cc380-5608-11e9-8708-65f873b002c1.png)
![Screen Shot 2019-04-03 at 12 01 59 PM](https://user-images.githubusercontent.com/21006/55494436-c23cc380-5608-11e9-85b7-8916a74e5e9e.png)

## After: now there's an "Add Data" button 🎉 

![Screen Shot 2019-04-03 at 12 02 31 PM](https://user-images.githubusercontent.com/21006/55494438-c23cc380-5608-11e9-876c-4ed3c3abe2cd.png)

**Comment by pdurbin** [comment]
This is a neat trick but I don't feel compelled to document it. For now I added this to my list of stuff to talk about in the "Hidden Features of Dataverse" talk I sometimes threaten to give. 😄 Closing.

**Comment by jggautier** [comment]
Is this what's described at https://guides.dataverse.org/en/latest/user/dataverse-management.html#setting-access-configurations?

**Comment by pdurbin** [comment]
@jggautier yes. This part:

"you can set whether or not the entire userbase (all logged in users) has the ability to add datasets or sub Dataverse collections to your Dataverse collection"

So I guess it's already documented. Not the exact use case, but it's implied. Thanks!

**Comment by pdurbin** [comment]
This is what I set up (anyone can create datasets) but I'm removing it:

<img width="1153" alt="Screen Shot 2022-11-14 at 4 00 03 PM" src="https://user-images.githubusercontent.com/21006/201764559-5904df3e-f985-4cc5-ab3f-a6c8e5c67b4f.png">

https://github.com/IQSS/dataverse.harvard.edu/issues/199 is about disabling "anyone can create collections" but still, close enough. Gone!
