### ISSUE TITLE
As a Developer of the Dataverse App Who Regulary Reads GitHub Issue Titles in the Slack Activity Feed and in Waffle Columns, I would like Issue Titles Text Limited to Report What's Important, and to Use Labels to Communicate Roles, Features, Et al 

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#5719]
Thank you for contributing an issue to the Dataverse Project! If this is a bug report, please let us know when the issue occurs, which page it occurs on, to whom it occurs, and which version of Dataverse you're using. If this is a feature request, please let us know what you'd like to see and give us some context - what kind of user is the feature intended for, and what inspired the request? No matter the issue, screenshots are always welcome.

**Comment by djbrooke** [comment]
@mheppler - well, the waffle part won't be an issue for much longer, at least. 

We can discuss as a team the best approach.

**Comment by djbrooke** [comment]
Closing for discussion offline.
