### ISSUE TITLE
Move Resource Bundle property files to a new folder

### ISSUE THREAD

**Issue by JayanthyChengan** [IQSS/dataverse#5720]
Planning to sync English propertyfiles between dataverse and https://github.com/GlobalDataverseCommunityConsortium/dataverse-language-packs repo.

To accomodate that moving all resource bundle property files into a new folder named **propertyFiles**

**Comment by pdurbin** [comment]
@JayanthyChengan I see @mheppler assigned himself as well but my feedback is that the API test suite is failing as of 96dd7ab. Please see https://github.com/IQSS/dataverse/pull/5721#issuecomment-479631517 for details. Can you please get it passing? Please let us know if you need any assistance. Thanks!

Here's how I tested it:

`ec2-create-instance.sh -g main.yml -b 5720-ResourceBundle-newFolder -r https://github.com/scholarsportal/dataverse.git`

`ssh -i key-pdurbin-07EFFEFB.pem centos@ec2-3-92-243-36.compute-1.amazonaws.com`

`sudo -i`

`cd /tmp/dataverse/`

`conf/docker-aio/run-test-suite.sh http://localhost:8080`

The `ec2-create-instance.sh` script can be downloaded from http://guides.dataverse.org/en/4.12/developers/deployment.html if you're interested.

**Comment by JayanthyChengan** [comment]
Thanks @pdurbin .  I will look into it.

**Comment by pdurbin** [comment]
@JayanthyChengan thanks! Heads up that some but not all of the failing tests are also apparently failing on the "develop" branch. For details, please see #5722

**Comment by JayanthyChengan** [comment]
@pdurbin : 
I ran the API tests against Glassfish running on my laptop.  I was able to clear some of the tests, and committed the new code to this PR #5721 , and currently it's failing only for the tests as mentioned in #5722 .  Thanks

**Comment by pdurbin** [comment]
@JayanthyChengan thanks! If you have any clues for how to fix #5722 please feel free to comment in that issue or make a pull request. 😄

**Comment by mheppler** [comment]
@JayanthyChengan with the recent changes to the bundles in #4679 merged into `develop`, this branch will need to be updated with that code to resolve those conflicts.

I wanted to point that out, and also ask if we have a procedure in place for reporting changes required to the language bundles after they have been removed. Since this issue and PR removes those files, any changes like those included in the javascript changes will need to be reported and tracked in each of the language bundles.

@scolapasta, @pdurbin and I briefly discussed this in stand up this morning and wanted to reach out and coordinate for this issue and other issues going forward.

**Comment by pdurbin** [comment]
@JayanthyChengan I just resolved the merge conflicts in 93b29c838

Here's how `git merge develop` looked when I ran it:

```
Auto-merging src/main/webapp/dataverseuser.xhtml
CONFLICT (content): Merge conflict in src/main/webapp/dataverseuser.xhtml
CONFLICT (modify/delete): src/main/java/Bundle_fr.properties deleted in HEAD and modified in develop. Version develop of src/main/java/Bundle_fr.properties left in tree.
Automatic merge failed; fix conflicts and then commit the result.
```

It looks you want `<f:loadBundle basename="propertyFiles.Bundle" var="bundle"/>` in there so I left it in. This is what I saw in Netbeans:

![Screen Shot 2019-04-08 at 1 51 26 PM](https://user-images.githubusercontent.com/21006/55745712-df590400-5a05-11e9-97c2-cf7e12d93d5e.png)

**Comment by pdurbin** [comment]
@pengchengluo heads up that `Bundle_zh_CN.properties` is being removed in pull request #5721 

@mheppler I'm sure what the exact procedure is but I believe we want @pengchengluo to re-contribute the Chinese translation of Dataverse over at https://github.com/GlobalDataverseCommunityConsortium/dataverse-language-packs

**Comment by pdurbin** [comment]
I spoke to @mheppler a little more and we're good with this going to QA. Thanks, @JayanthyChengan !

**Comment by JayanthyChengan** [comment]
@mheppler @scolapasta @pdurbin  - currently don't have any procedure for reporting changes to the language bundles.

**Comment by kcondon** [comment]
@JayanthyChengan @pdurbin @mheppler Is there anywhere that tells where to go to get the language bundles? There is the http://guides.dataverse.org/en/4.12/installation/config.html#dataverse-lang-directory jvm option where it talks about the bundles but not that you can go here to get them:
https://github.com/GlobalDataverseCommunityConsortium/dataverse-language-packs

**Comment by pdurbin** [comment]
Yeah, we should update the docs to mention https://github.com/GlobalDataverseCommunityConsortium/dataverse-language-packs 

We should also have these two config options should cross reference each other:

- http://guides.dataverse.org/en/4.12/installation/config.html#dataverse-lang-directory
- http://guides.dataverse.org/en/4.12/installation/config.html#languages

@JayanthyChengan do you want to work on this?

**Comment by pdurbin** [comment]
@kcondon I added a doc change at 6b11d32

**Comment by pengchengluo** [comment]
@pdurbin Thanks for you informing me. I can try to re-contribute the Chinese translation later.

**Comment by pdurbin** [comment]
@pengchengluo thanks! For now, if you want, you could create an issue at https://github.com/GlobalDataverseCommunityConsortium/dataverse-language-packs/issues so people managing that repo know who to contact or follow up with. No rush! 😄
