### ISSUE TITLE
Dashboard to manage users: expose more fields and make them sortable, in the API and UI 

### ISSUE THREAD

**Issue by gohsunee** [IQSS/dataverse#5726]

**Comment by djbrooke** [comment]
Thanks @gohsunee, this is a good idea (as is #5727). We'll consider this.

**Comment by pdurbin** [comment]
@gohsunee there is a new pull request at #6848 by @pkiraly to make fields sortable via API, a step forward.

**Comment by djbrooke** [comment]
Closing as a duplicate of #4285
