### ISSUE TITLE
Dashboard to manage users: allow users to be downloadable as a csv, via API and UI

### ISSUE THREAD

**Issue by gohsunee** [IQSS/dataverse#5727]

**Comment by pdurbin** [comment]
@gohsunee are you still interested in this? For now, does it help that you can download users in JSON format via API? Please see https://guides.dataverse.org/en/5.12/api/native-api.html#list-users

**Comment by gohsunee** [comment]
Thanks for the follow-up. I'll close this issue. I'll defer to the new team who is managing our university dataverse.
