### ISSUE TITLE
Feedback on Whole Tale external tool

### ISSUE THREAD

**Issue by RightInTwo** [IQSS/dataverse#5728]
As discussed with Phil, I'm opening this issue to keep track about the feedback on Whole Tale. Disclaimer: I do not feel responsible to follow up on it ;)

**Comment by RightInTwo** [comment]
I have one major feedback on wholetale in general: It is an external tool and it is therefore not suitable for sensitive data. (I currently cannot find an option to run it locally...)

**Comment by pdurbin** [comment]
@RightInTwo well, you could install Whole Tale on your own hardware: https://wholetale.readthedocs.io/en/stable/admin_guide/install.html

**Comment by RightInTwo** [comment]
Okay, that was a misunderstanding on my part.... Should I close this issue or do you want to keep it for further feedback?

**Comment by pdurbin** [comment]
@RightInTwo I would say it's up to you. When you're done talking about it, whether or not you decide to use Whole Tale (I'm definitely interested either way), you should close it. If you think the documentation on the Dataverse side should be improved, you're welcome to follow up on pull request #5417 with another pull request to suggest improvements.

Thanks for all the chatter at http://irclog.iq.harvard.edu/dataverse/2019-04-08#i_90385 . I just linked to this discussion from https://groups.google.com/d/msg/dataverse-community/fi08uEJJec0/sWV1PInMAgAJ which I called "user workflow diagram for Dataverse Trusted Remote Storage Agent (sensitive data)". Here's the TRSA issue: #5213

**Comment by RightInTwo** [comment]
> I gave a demo of launching a Jupyter Notebook from Dataverse a couple months ago at #dataverse2019 and I took some screenshots that you can see at https://scholar.harvard.edu/pdurbin/blog/2019/jupyter-notebooks-and-crazy-ideas-for-dataverse

@pdurbin Thank you for following up on this. I saw your Crazy Ideas and like them a lot! Due to prioritization, we will stay with TwoRavens until something comes along that is as easy to install/maintain - or maybe even something like a store (#5688). Sorry for not providing any insight here. All the best to everyone who reads this :)
