### ISSUE TITLE
publication date appears in the citation

### ISSUE THREAD

**Issue by MohanaPriyaNarapareddy** [IQSS/dataverse#5729]
I imported a dataset from datacite to dataverse. The import was working fine but the problem comes with the publication date in the metadata. My production date was 2016. But the publication date is 2019, and the publication date appears in the citation. Is there any way that I can edit the publication date and give my custom date? I want my production date to appear in the citation.

**Comment by pdurbin** [comment]
@MohanaPriyaNarapareddy thanks for the feedback! Yes, this is possible and documented at http://guides.dataverse.org/en/4.12/api/native-api.html#set-citation-date-field-for-a-dataset

See also the "Dates in citation" thread at https://groups.google.com/d/msg/dataverse-community/neijtUjq8fk/Svxl8A_DAwAJ

If you have any trouble, please let us know because that would be an indication that our documentation should be improved! Thanks!

**Comment by MohanaPriyaNarapareddy** [comment]
@pdurbin Thanks for the reply. I tried the above command but, I am getting an error that endpoint doesn't exist. The following is my URL.
PUT http://localhost:8080/api/datasets/doi:10.7937/k9/tcia.2016.5di84js8/citationdate?key=5bbeb877-6c74-4131-8144-fbcaa128344a

I replaced $SERVER with localhost:8080 and $ID with doi:10.7937/k9/tcia.2016.5di84js8.
Not sure if ID is same as PID and also if the $Server is as same as $Serverurl

**Comment by pdurbin** [comment]
It's confusing. Can you please try something like...

http://localhost:8080/api/datasets/12345/citationdate?key=5bbeb877-6c74-4131-8144-fbcaa128344a

... where your replace 12345 with the database id of your dataset? You can see the database id in the URL when you go to edit dataset permissions. "159" in this screenshot:

![Screen Shot 2019-04-08 at 3 05 48 PM](https://user-images.githubusercontent.com/21006/55749795-d4a36c80-5a0f-11e9-89fa-9802a9017c09.png)

**Comment by MohanaPriyaNarapareddy** [comment]
@pdurbin 
I tried with the database id. I get the following error saying not found.
{
    "status": "ERROR",
    "message": "Dataset Field Type Name {\"datasetVersion\":{\"termsOfUse\":\"CC0 Waiver\",\"license\":\"CCO\",\"protocol\":\"doi\",\"authority\":\"10.7937\",\"identifier\":\"K9/TCIA.2016.5DI84JS8\",\"metadataBlocks\":{\"citation\":{\"fields\":[{\"typeName\":\"title\",\"multiple\":false,\"value\":\"Glioma DSC-MRI Perfusion Data with Standard Imaging and ROIs\",\"typeClass\":\"primitive\"},{\"typeName\":\"productionDate\",\"multiple\":false,\"value\":\"2016\",\"typeClass\":\"primitive\"},{\"typeName\":\"dsDescription\",\"multiple\":true,\"typeClass\":\"compound\",\"value\":[{\"dsDescriptionValue\":{\"typeName\":\"dsDescriptionValue\",\"multiple\":false,\"typeClass\":\"primitive\"}}]},{\"typeName\":\"subject\",\"multiple\":true,\"typeClass\":\"controlledVocabulary\",\"value\":[\"Medicine, Health and Life Sciences\"]},{\"typeName\":\"author\",\"multiple\":true,\"typeClass\":\"compound\",\"value\":[{\"authorName\":{\"typeName\":\"authorName\",\"multiple\":false,\"value\":\"Schmainda, Kathleen M.\",\"typeClass\":\"primitive\"}},{\"authorName\":{\"typeName\":\"authorName\",\"multiple\":false,\"value\":\"Prah, Melissa A.\",\"typeClass\":\"primitive\"}},{\"authorName\":{\"typeName\":\"authorName\",\"multiple\":false,\"value\":\"Connelly, Jennifer M.\",\"typeClass\":\"primitive\"}},{\"authorName\":{\"typeName\":\"authorName\",\"multiple\":false,\"value\":\"Rand, Scott D.\",\"typeClass\":\"primitive\"}}]},{\"typeName\":\"depositor\",\"multiple\":false,\"value\":\"Admin,TCIA\",\"typeClass\":\"primitive\"},{\"typeName\":\"datasetContact\",\"multiple\":true,\"typeClass\":\"compound\",\"value\":[{\"datasetContactEmail\":{\"typeName\":\"datasetContactEmail\",\"multiple\":false,\"value\":\"help@cancerimagingarchive.net\",\"typeClass\":\"primitive\"}}]}],\"displayName\":\"Citation Metadata\"}}}}\n\n not found."
}

**Comment by pdurbin** [comment]
Ah, that's coming from here:

```
src/main/java/edu/harvard/iq/dataverse/api/Datasets.java
411:                    return badRequest("Dataset Field Type Name " + dsfTypeName + " not found.");
```

You have to pass it which field you want to use for the date. It's not a complete `curl` example.

There's a bit of a clue here: https://github.com/IQSS/dataverse/issues/2606#issuecomment-192475012

**Comment by pdurbin** [comment]
This worked for me:

`export API_TOKEN=1d02de58-04df-47fb-90ef-315edcf6cef1`

`curl -H "X-Dataverse-key:$API_TOKEN" -X PUT -d productionDate http://localhost:8080/api/datasets/10/citationdate`

`{"status":"OK","data":{"message":"Citation Date for dataset 10 set to: Production Date"}}`

(It's ok to share my API token here because it's a dev server on my laptop.)

@MohanaPriyaNarapareddy can you please give this a try?

Definition of done for this issue is to document this better, obviously. In the docs we should also include a list of date fields you can use.

**Comment by MohanaPriyaNarapareddy** [comment]
The command works. Thanks for the reply. I can now see the production date in the citation. But, Is there any way that I can edit the publication date or hide the publication date?

**Comment by pdurbin** [comment]
@MohanaPriyaNarapareddy can you please upload a screenshot to this issue? I'm not sure I understand what you're seeing. Thanks!

**Comment by MohanaPriyaNarapareddy** [comment]
<img width="788" alt="Screen Shot 2019-04-10 at 2 03 37 PM" src="https://user-images.githubusercontent.com/31942449/55902479-920d9b80-5b99-11e9-842e-17e514b7ba0e.png">

**Comment by MohanaPriyaNarapareddy** [comment]
I want to edit or hide the publication date which appears in the picture.

**Comment by pdurbin** [comment]
@MohanaPriyaNarapareddy I'm sorry but there is no way to hide Publication Date (or any metadata field) from the Metadata tab (or from the JSON and XML that comes out of "Export Metadata"). If you really want to change it, you will have to directly edit the database... but we never recommend this. Publication Date is not something you can edit. It is a timestamp from when you click "Publish".

**Comment by MohanaPriyaNarapareddy** [comment]
Thanks for your reply.

**Comment by pdurbin** [comment]
@MohanaPriyaNarapareddy you're welcome. Would you like to make a pull request to improve the documentation? Here's the somewhat confusing documentation you were looking at: https://github.com/IQSS/dataverse/blob/v4.12/doc/sphinx-guides/source/api/native-api.rst#set-citation-date-field-for-a-dataset

**Comment by sharmaashish** [comment]
@pdurbin: @MohanaPriyaNarapareddy and our team were looking at the Publication Year, on the main Dataverse landing page — [dataverse.cancerimagingarchive.net](dataverse.cancerimagingarchive.net)
We imported a few DOIs as we migrate from our homebrew system to Dataverse. The publication year shows up as 2019, but some of these DOIs were created in 2016, 2018, etc.

Is there a way for us to show the creation date on the main landing page? Otherwise, we will start showing a mass creation in 2019 and give the impression that no data was created pre-2019.

**Comment by pdurbin** [comment]
@sharmaashish hi! The only way I can think to fix this problem now that you seem to be in production is to hack on the "publicationdate" column of the "dvobject" table (highlighted in blue in the screenshot from http://phoenix.dataverse.org/schemaspy/latest/tables/dvobject.html below), followed by some reindexing: http://guides.dataverse.org/en/4.14/admin/solr-search-index.html

I hate suggesting database hacks like this so if you would like an API for this, please open a new issue.

Also, are you interested in adding https://dataverse.cancerimagingarchive.net to the map at https://dataverse.org and the metrics page at https://dataverse.org/metrics ? I hope so! The procedure is to email our support address, as explained at http://guides.dataverse.org/en/4.14/installation/config.html#putting-your-dataverse-installation-on-the-map-at-dataverse-org

![Screen Shot 2019-06-13 at 12 11 33 PM](https://user-images.githubusercontent.com/21006/59449373-e8cf6580-8dd4-11e9-8c64-ea270adbe3c2.png)

**Comment by jggautier** [comment]
@sharmaashish when you write "Publication Year on the main Dataverse landing page," you mean the year in the dataset search cards that's below the dataset title, right?

<img width="750" alt="Screen Shot 2019-06-13 at 12 27 36 PM" src="https://user-images.githubusercontent.com/18374574/59450357-11585f00-8dd7-11e9-8864-6f4d08794684.png">

So for the dataset in the screenshot above, you'd want to show 2018, which is what's in that dataset's Production Date field.

When you Sort the results by "Newest," what's being used to sort is the date that the dataset was published in the Dataverse installation (or if the dataset isn't published yet, the date that the dataset was created in the Dataverse installation ). @pdurbin, would this database hack affect that Sort order, too?

**Comment by sharmaashish** [comment]
No. I meant the year on the left panel of the main page. 
<img width="704" alt="Screen Shot 2019-06-13 at 12 39 04 PM" src="https://user-images.githubusercontent.com/8442831/59450918-4dd88a80-8dd8-11e9-8605-8f72f518608a.png">

I think the publication date on the individual dataset is fine. It tells me when this dataset/DOI was updated (published with a new version).

**Comment by sharmaashish** [comment]
@pdurbin 
Could one populate the main landing page with the createdate field instead of the publicationdate field http://phoenix.dataverse.org/schemaspy/latest/tables/dvobject.html

**Comment by sharmaashish** [comment]
@pdurbin Once this goes live (we just imported 4 or 5 datasets for our testing), we will email support and request that it be listed on the dataverse map.

**Comment by pdurbin** [comment]
> Could one populate the main landing page with the **createdate** field instead of the **publicationdate** field

@sharmaashish if you want this, please create an issue for this. Are you saying you'd want something like a "Creation Year" facet like in the screenshot below?

![Screen Shot 2019-06-13 at 12 57 18 PM](https://user-images.githubusercontent.com/21006/59452020-d821ee00-8dda-11e9-8b60-41a18a7dadbd.png)

> Once this goes live (we just imported 4 or 5 datasets for our testing), we will email support and request that it be listed on the dataverse map.

Fantastic!

@jggautier I'll swing by your office and explain. 😄

**Comment by sharmaashish** [comment]
Yes!!! How do I get this **Creation Year**? A new issue request, or a hidden tweak?

**Comment by pdurbin** [comment]
@sharmaashish a new issue request, please. 😄 That was just me hacking on https://demo.dataverse.org using a Chrome extension called VisBug: https://github.com/GoogleChromeLabs/ProjectVisBug

Here's VisBug in action:

![Screen Shot 2019-06-13 at 1 03 16 PM](https://user-images.githubusercontent.com/21006/59452452-bd03ae00-8ddb-11e9-9968-a46a8fe4fab1.png)

**Comment by pdurbin** [comment]
@sharmaashish thanks for creating this related issue:

- #5945

@MohanaPriyaNarapareddy are you all set? Can we close this?
