### ISSUE TITLE
exportAll and reExportAll get "Workflow in Progress" notification and never provide the actual records

### ISSUE THREAD

**Issue by pdante-ubc** [IQSS/dataverse#5730]
I'm using Dataverse v.4.10.1 and when I try to export all the metadata records via the API I get a notification (error?) "WORKFLOW_IN_PROGRESS" and never get any records. I've tried this using curl, directly putting the call into a web browser, and using Postman, but all had the same result. 

my call is: 
      curl http://localhost:8080/api/admin/metadata/reExportAll
      or
      curl http://localhost:8080/api/admin/metadata/exportAll

**Comment by pdurbin** [comment]
@pdante-ubc sorry for the slow response. I just tried this myself when replying to @shlake at https://groups.google.com/d/msg/dataverse-community/Dyfl7P0DEUQ/I1W9y3zyAAAJ and it worked fine.

I'm not sure what you mean when you say you never got any records. For me the export formats were correctly written to disk. I'm talking about files like this being written to /usr/local/glassfish4/glassfish/domains/domain1/files/10.5072/FK2/U33D6V

- export_Datacite.cached
- export_dataverse_json.cached
- export_dcterms.cached
- export_ddi.cached
- export_oai_datacite.cached
- export_oai_dc.cached
- export_oai_ddi.cached
- export_OAI_ORE.cached
- export_schema.org.cached

**Comment by pdante-ubc** [comment]
I'm still getting:

```
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    33  100    33    0     0    452      0 --:--:-- --:--:-- --:--:--   452{"status":"WORKFLOW_IN_PROGRESS"}

```
went I try to run those calls. Not sure why my DV is working differently than yours. I've actually changed my code to search for records, gather all those DOIs, and then iterate through my list of DOIs getting each metadata record individually. It's a workflow that functions and actually works a little better for me than bulk downloading the metadata records.

**Comment by pdurbin** [comment]
@pdante-ubc I think you've identified a bug in our docs.

Are you expecting the records themselves to be returned by that curl command?

Please feel free to pop in http://chat.dataverse.org for a minute if you'd like to talk this out in real time.

> I've actually changed my code to search for records, gather all those DOIs, and then iterate through my list of DOIs getting each metadata record individually.

What code? Is it on GitHub? Are you using one of the Dataverse client libraries? A new one just came out. 😄

**Comment by pdante-ubc** [comment]
Seems I was misunderstanding what the exportAll and reExportAll calls were supposed to do.

**Comment by pdurbin** [comment]
@pdante-ubc thanks for the chat over at http://irclog.iq.harvard.edu/dataverse/2019-06-14#i_97969 !

If you or anyone else would like to improve the docs, here's the latest version that was tripping you up: https://github.com/IQSS/dataverse/blob/v4.14/doc/sphinx-guides/source/admin/metadataexport.rst#batch-exports-through-the-api

Maybe we just need to add "to disk" to say that the export files are written to disk? I guess they're written to S3 or Swift if you use those storage drivers.

**Comment by pdante-ubc** [comment]
I think the confusion I had is that export and download are often interchangeable terms, so it looked to me like I could use those endpoints to batch download all the metadata records from DV.
