### ISSUE TITLE
UZH: Unit Testing (Test Smells Refactoring & Mocking)

### ISSUE THREAD

**Issue by nikzaugg** [IQSS/dataverse#5732]
Hi all!

We (@alexscheitlin, @rschlaefli and @nikzaugg) have received our third assignment. This time the focus will be on identifying and refactoring test smells and mocking.

We noticed that you do not really mock classes even inside your mock factories. We would therefore start mocking by using the [mockito](https://site.mockito.org/) library you have already installed. Please let us know if there is anything specific we need to know about mocking in Dataverse.

We will track our progress with the assignment on this issue.

Take a look at #5619 for who we are and what we do.

**Comment by pdurbin** [comment]
Hi! Thanks for all the pull requests! With regard to mocking, the thing that drives me the most crazy at the moment is that various slightly different `MockDatasetFieldSvc` classes appear throughout the code base (screenshot below). Would you be able to investigate the possibility of creating a single `MockDatasetFieldSvc` and deleting the rest? We'd still want all the tests to pass, of course. 😄 

![Search_·_MockDatasetFieldSvc_-_2019-04-09_06 47 13](https://user-images.githubusercontent.com/21006/55794589-98b1eb00-5a93-11e9-98f7-a29864853c17.png)

**Comment by alexscheitlin** [comment]
> Hi! Thanks for all the pull requests! With regard to mocking, the thing that drives me the most crazy at the moment is that various slightly different `MockDatasetFieldSvc` classes appear throughout the code base (screenshot below). Would you be able to investigate the possibility of creating a single `MockDatasetFieldSvc` and deleting the rest? We'd still want all the tests to pass, of course. smile

Hi @pdurbin, the `MockDatasetFieldSvc` is defined three times (in `DDIExporterTest`, `FeedbackUtilTest`, and `JsonParserTest`) and used in two more test classes (`SchemaDotOrgExporterTest` and `JsonPrinterTest`). It seems like they were just copy pasted. So it should possible move the class `MockDatasetFieldSvc` into a separate file or deleting two of the three declarations and just use the remaining one.

What do you prefer? In case of the separate file: where should the file be stored? In a separate "mock" folder or right next to the `DatasetFieldServiceBean`?

**Comment by pdurbin** [comment]
@alexscheitlin hi! A separate file in a new folder called "mock" sounds fine but honestly, whatever is easiest for you is also fine. 😄  The main thing is to remove duplicate code.

**Comment by alexscheitlin** [comment]
Hi @pdurbin, I extracted the class and removed code duplication (see #5780).

FYI: More PR's follow for this issue (regarding to test smells and mocks from each of us). We'll drop a comment here as soon as we have finished our work and created the PR's.

**Comment by pdurbin** [comment]
@alexscheitlin thanks! Last time we had three pull request tied to one issue. Instead, can we have a single pull request per issue? This should help items move more quickly across our kanban board.

**Comment by rschlaefli** [comment]
@pdurbin Do you suggest we do both mocking and test refactoring (which, in this case, are quite unrelated) in a single pull request (yielding 3 PRs), or do you suggest we combine all of the changes across our forks into a single one (which would be harder, I guess)?

I would have thought that it would be easier for you to review if separate "topics" are also handled in separate pull requests. Maybe we should create one issue per separate task and link our pull requests to these?

We are totally flexible, so we can submit our changes in whatever way works best for you :)

**Comment by pdurbin** [comment]
@rschlaefli hi! Whatever is easiest for you is fine. I think you understand what I was trying to say above but here's a screenshot from https://waffle.io/IQSS/dataverse to reinforce it:

<img width="770" alt="Screen Shot 2019-04-23 at 10 32 55 AM" src="https://user-images.githubusercontent.com/21006/56589446-3d174f80-65b3-11e9-83d9-efcfee9da22b.png">

When #5673 was in Code Review, it would come up during standup and we'd say something like, "Two of these pull requests are not-controversial but the third needs a little work. Let's drag it [all] back to Community Dev." This is the situation I'd like to avoid. If a pull request is ready for QA, great, move it over. Don't entangle it with other work in progress.

To be clear, it all worked out in the end. Everything got merged and included in our 4.13 release (thanks!) but I like your "topics" idea. Are you saying that you'd do something like this?

- topic 1: issue 1234, pull request 1237
- topic 2: issue 1235, pull request 1238
- topic 3: issue 1236, pull request 1239

If so, that sounds great. We're open to other approaches though so again, whatever works for you is fine. Thank you very much for all you contributions!

p.s. Please don't feel limited to three topics. 😄 It's free to create an issue, it's free to create a branch and a pull request. 😄 Thank you!!

**Comment by alexscheitlin** [comment]
Hi @pdurbin, for your workflow with waffle, I think it's best if we only create one PR for one issue (concerning one topic).

For this issue, this means:
1. each of us will create a separate issue (referencing this one) for test smells
2. each of us will create a separate issue (referencing this one) for mocking
3. each of us will create two pull requests (one for each issue)
4. @rschlaefli will create a separate issue (as described above in 2.) for PR #5775
5. this issue only has one PR (#5780 concerning the `MockDatasetFieldSvc` class)

Note:
As we already committed our changes, referenced this issue number in the commit message and pushed our changes to GitHub, the commits are listed in this issue. Even amending the commit message with the new issue number will not change that. Thus, we won't amend our commit messages and the already committed changes will reference this issue. The PR however will then list all relevant commits. So I think this won't be an issue.

For future assignments (I think there is only one left, max two):
- each of us creates "his" own issue for a certain topic
- only one PR is created for one issue

**Comment by pdurbin** [comment]
@alexscheitlin sounds great! Thanks!!

**Comment by pdurbin** [comment]
I realize there's a lot of meta discussion above but I'm moved this issue to QA because it's the "connects to" issue for pull request #5780 which has some removal of duplicate code that I asked for above. Thanks, @alexscheitlin !
