### ISSUE TITLE
Manage Harvesting Client page keeps refreshing. Unable to add or edit clients

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#5735]
On Harvard Dataverse, v4.12, the Manage Harvesting Client page keeps refreshing. So I'm not able to add clients or edit existing clients because the modal windows close seconds after opening.

This wasn't happening on Demo Dataverse, v4.12, until I added a client and tried harvesting. Looks like the harvesting job is stuck INPROGRESS, and now the modal windows on Demo also closes seconds after opening.

**Comment by landreev** [comment]
This is not related to the harvesting sets issues we were having. It looks like autorefresh was added to the page by an external contributor last fall. These lines in harvestclients.xhtml:
```
<script type="text/javascript" jsf:rendered="#{harvestClient.harvestingNow or harvestClient.deleteInProgress}">
                                if (window.refreshTimer === undefined){
                                    window.refreshTimer = setTimeout(function(){window.location.reload();},5000);
                                }
                            </script>
```
The intention must have been to have the page refresh automatically if there are harvests in progress... similarly to what we do with the dataset page when the dataset is locked. Unfortunately, unlike with the dataset page, we still want people to be able to do things with *other* harvesting clients, even if some are running already. In reality, as @jggautier pointed out, a long-running harvest, or a stuck harvest, is now rendering the page unusable. 
So these lines above should be removed. 
(so yeah, I would estimate it as 1 and add it to the next spring)

**Comment by jggautier** [comment]
@landreev did something to stop the page from auto refreshing in Harvard Dataverse's Dataverse instance. (Thanks!) But this issue can't be closed because the fix isn't in a Dataverse release on GitHub, right?

**Comment by pdurbin** [comment]
I just approved pull request #5926 but but head up to @tcoupin (and everybody) that this reverts your commit at 7240e7a in pull request #5248 for the following issue (which was opened by @kcondon ):

Harvest: Automatically update manage client page as harvesting completes. #3260
