### ISSUE TITLE
Spike: Faster feedback loop when developing

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#5736]
Spun out of https://github.com/IQSS/dataverse/issues/5593

- Hello-world spike-test to see speed of deploying the minimum possible glassfish application (to understand what is the fastest possible).
- Automate and time our build/deploy process across multiple version (we could start by looking at the ones with major size spikes, or just run all the versions), include line count of server.log. Put these in the new columns at "Metrics for Dataverse by release" (formerly "Size of Dataverse WAR file over time") at https://docs.google.com/spreadsheets/d/1uL5CVGhMh6Vcr_UUgwbrcHterz7BM1qMPPPrk6ao4ZY/edit?usp=sharing

**Comment by smillidge** [comment]
btw the war file is full of junk likely pulled in from many different dependencies. I recommend people open their war file in file-roller(Linux)  or something and look in the WEB-INF/lib just to see what maven has added. I could manually delete loads of stuff from the war and still deploy it as many of the jars are already provided by the runtime.

**Comment by pdurbin** [comment]
@smillidge yes, you're right. The war file is getting big. :cry:  The following chart is from this issue:  Increasingly slow feedback loop for developers, increasingly large WAR files #5593 

<img width="1256" alt="53664394-66140780-3c36-11e9-80c9-de1e3cad83ab" src="https://user-images.githubusercontent.com/21006/58667934-73a85e80-8305-11e9-9d08-b2f03caca99e.png">

**Comment by poikilotherm** [comment]
Pretty please take a look at #5274 and #5360 when talking about WAR file contents and size. I already had a look at a few things, which might be helpfull down the road. Obviously even more can be moved out when heading for Payara 5 finally! :smile: :man_dancing:

**Comment by smillidge** [comment]
I had a look as well and did this https://github.com/smillidge/dataverse/commit/ba42682e80c66b6fd78d362a0d820b2528171be3 

There's still some ancient dependency wanting to use Xalan and Xerces though so II couldn't remove them although they have been deprecated for many many years.

**Comment by pdurbin** [comment]
> Hello-world spike-test to see speed of deploying the minimum possible glassfish application (to understand what is the fastest possible).

We now have a tiny app at https://github.com/IQSS/dataverse-people which I created for this issue:

- #8987

I haven't timed how long it takes to deploy but it's quite fast. It's a joy to deploy this little app compared to Dataverse. 😄

**Comment by pdurbin** [comment]
Closing in favor of the original issue, which I just updated:

- #5593
