### ISSUE TITLE
Add previewers as external tools in docs

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#5738]
The previewers at https://github.com/QualitativeDataRepository/dataverse-previewers should be listed in the inventory at http://guides.dataverse.org/en/latest/installation/external-tools.html - I'll make a pull.

**Comment by pdurbin** [comment]
@qqmyers thanks! I've been playing around with them on ec2 thanks to @donsizemore and https://github.com/IQSS/dataverse-ansible/issues/52
