### ISSUE TITLE
v4.12 download issue: GuestbookResponseServiceBean.modifyDatafile still used in file-download-button-fragment.xhtml

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#5743]
Commit https://github.com/IQSS/dataverse/commit/dc11ec188dd72524c7d5cabd0a5c4801b5fd35a6#diff-e9ed8dcfe63d49945e42b203bb970a2a by @matthew-a-dunlap removed this method but the current code at https://github.com/IQSS/dataverse/blame/develop/src/main/webapp/file-download-button-fragment.xhtml#L157 still uses it.
The effect I see is that the Download button for a file on the dataset page fails if there are terms of access that cause the pop-up dialog to appear. I see an error in the log about the missing method.

As far as I can tell, adding the method back in fixes the issue, but, as I'm not sure why it was removed, I'm not sure if that is the best approach.

**Comment by djbrooke** [comment]
Thanks @qqmyers for the details here. We'll discuss this in tech hours (starting in 13 minutes) and provide an update here after that.

**Comment by scolapasta** [comment]
@matthew-a-dunlap is going to take a look (we think the solution is, like @qqmyers says to just add it back), but he is going to confirm that doesn't affect anything else.

**Comment by matthew-a-dunlap** [comment]
PR is up and I confirmed the popup works again. Sorry for the breakage @qqmyers, I got a big trigger happy fixing up code around Make Data Count!
