### ISSUE TITLE
Host and preview HTML files in Dataverse

### ISSUE THREAD

**Issue by TaniaSchlatter** [IQSS/dataverse#5746]
There are several interactive figures associated with this dataverse: https://dataverse.harvard.edu/dataverse/cloud_distances
Here is one: https://faun.rc.fas.harvard.edu/czucker/Paper_Figures/summary_fig.html

The authors of the paper connected to this data would like to host the interactive figures on Dataverse as well as with the journal who is publishing the work. 

This would involve hosting an html webpage for the figure itself, and URLs for the individual png files which go into the interactive figure (of which there are ~ thousand). 

The author added the pngs to the Dataverse so they are preserved, along with all the tables, but would love to have a stable place (with a doi) to host the figures as a data product in themselves.

**Comment by pdurbin** [comment]
@qqmyers just added some thoughts on this use case over at https://github.com/QualitativeDataRepository/dataverse-previewers/issues/5 (thanks!)

**Comment by TaniaSchlatter** [comment]
Another user request came in through support for this feature: 

"I was hoping for... nested folders in GUI form, perhaps with icons and brief labels, with links to deeper files and folders, such as you have with a web page. ... The attached screen shot shows the kind of presentation I’m thinking of.  Would this be possible?"
![Screen Shot 2019-10-30 at 12 51 53 PM](https://user-images.githubusercontent.com/15386424/68051017-ce7f2100-fcbc-11e9-9e53-31f1b809f9f6.png)

**Comment by pdurbin** [comment]
I think this is primarily a job for external tools and the previewers are the best fit, so we should probably close this issue and open one at https://github.com/gdcc/dataverse-previewers (ideally the person who wants this would open the new issue).

**Comment by pdurbin** [comment]
I'd say this new issue by @kmika11 more or less covers the use case:

- https://github.com/gdcc/dataverse-previewers/issues/31

**Comment by pdurbin** [comment]
Just a heads up that this PR has been merged:

- https://github.com/gdcc/dataverse-previewers/pull/40
