### ISSUE TITLE
File access: when a user is added to restricted files, their name should show up under "user/groups" without refreshing page

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#5747]
Navigate to dataset, permissions, files. 
Search for user by name or username.
Select account
Select files
Select save.
User doesn't show up on list of grantees until page is refreshed.

**Comment by mheppler** [comment]
@sbarbosadataverse could provide some detail on where you saw this, and any other relevant details like how many files were in the dataset or something that might provide a clue as to why you saw this behavior. I tested this locally with the 4.12 `develop` branch and it worked when granting a user permission with only one file in the dataset (see attached).

![Screen Shot 2019-04-16 at 2 41 52 PM](https://user-images.githubusercontent.com/687227/56235853-430ead00-6056-11e9-9bc6-4fbf81b62e36.png)

**Comment by mryder2** [comment]
@mheppler I could not duplicate this issue, using Demo Dataverse.

**Comment by mheppler** [comment]
@mryder2 thank you for attempting to replicate this. Closing.
