### ISSUE TITLE
Guides: Improve language doc to explain what needs to happen to enable and keep up to date.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#5756]
Improve languages doc to:
-provide a brief overview in config section
-cross link 2 languages settings, :Languages and the jvm-option, dataverse.lang.directory
-emphasize location of language bundles
-emphasize that every (nearly) release of Dataverse will contain a new english bundles.properties file that will need to be a)translated and b) copied over to the dataverse.lang.directory location if multiple languages are configured.

**Comment by mheppler** [comment]
To follow up on Kevin's last point, the `dataverse.lang.directory` JVM option was added in 4.9.3 as part of #4892. Any time a new release is deployed with changes to the bundle files, those new updated files need to be manually updated in the location specified by that setting. Or you will see the dreaded `???file.display.label???` displayed where bundle text is called by the page but not found in the bundle file.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
