### ISSUE TITLE
Translation for API token generation in external tool

### ISSUE THREAD

**Issue by lubitchv** [IQSS/dataverse#5757]
In #5671 and #5755 new api token will be generated. The message will popup and the email about it will be sent to the user.
The message and email have to be translated into different languages. Now they are located in Bundle.properties
`
notification.email.apiTokenGenerated=Hello {0} {1},\n\nAPI Token has been generated. Please keep it secure as you would do with a password.
notification.email.apiTokenGenerated.subject=API Token was generated
configurefragmentbean.apiTokenGenerated=API Token will be generated. Please keep it secure as you would do with a password.`

The popup message is in screenshot.

![Screenshot from 2019-04-11 16-27-23](https://user-images.githubusercontent.com/43550154/55991102-695bd380-5c77-11e9-8d11-c5cd16272232.png)

**Comment by djbrooke** [comment]
Hey @lubitchv - is there anything that needs to be done in the Dataverse code for this? Once it's bundle-ized we'd expect the translations to take place in https://github.com/GlobalDataverseCommunityConsortium/dataverse-language-packs for the respective languages. I'll close this out, but let me know if I'm misunderstanding and if I should reopen.

**Comment by lubitchv** [comment]
@djbrooke Yes, you are right. Although there is one small thing yet to be done. It is a drop down box from configure button with the name of external tool. Currently it is take from database. I already implemented the change for Scholars Portal code when DCT was launched (at the last minute), but have not yet added it to IQSS. I will open separate issue for that.

**Comment by djbrooke** [comment]
@lubitchv Got it, thanks !
