### ISSUE TITLE
Monitoring dashboard for shared resources use in dataverse

### ISSUE THREAD

**Issue by mbamouni** [IQSS/dataverse#5760]

**Comment by mbamouni** [comment]
As Philip DUrbin suggest in this trend https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/dataverse-community/zziMWREdirs,

I think, it will be good to have a monitoring dashboard for some resources we in dataverse. For example :
- DataCite
- Harvard WorldMap
- ORCID login
- OSF
- RSpace
- Whole Tale

Best regards,

Michel

**Comment by RightInTwo** [comment]
I would love to see this as well. It would be awesome to have it combined with the tool proposed as the "dataverse store" #5688.

**Comment by RightInTwo** [comment]
> As Philip DUrbin suggest in this trend

Looking at that exchange, the core idea is to "set up some sort of monitoring solution such as Nagios or whatever the cool kids uses these days so we could all check a dashboard to see if services we depend on are up or not".

**Comment by RightInTwo** [comment]
> I think, it will be good to have a monitoring dashboard for some resources we in dataverse.

In addition to monitoring external tools (asserting/analyzing responses of their respective APIs), the monitoring of internal processes would of course also be very useful:

- data integrity
- file ingest
- harvesting
- usage metrics

**Comment by pdurbin** [comment]
> monitoring of internal processes

I completely agree but a new issue would be better, I think.

Unless I'm thinking about this wrong.

Are you thinking all ~50 installations of Dataverse would monitor if DataCite is down? I was thinking one monitoring system for DataCite, ORCID, etc is enough. Of course someone has to host it. Harvard? The GDCC? One of the Dataverse installations? 😄

**Comment by RightInTwo** [comment]
> Are you thinking all ~50 installations of Dataverse would monitor if DataCite is down? I was thinking one monitoring system for DataCite, ORCID, etc is enough. Of course someone has to host it. Harvard? The GDCC? One of the Dataverse installations? smile

Well, okay, then we are talking about different things. I thought about a software (e.g. elk stack adapted to research data management needs), not a service. Of course, not everyone would want to monitor everything, but if that would be integrated with the dataverse dashboard, many smaller institutes could set up monitoring for their data ecosystem without much hassle.

**Comment by pdurbin** [comment]
This issue has gone cold.

@mbamouni are you still interested?

Maybe each service should provide its own monitoring page like DataCite does: https://status.datacite.org

We could document these in the guides if we don't already. I'm not so sure the Dataverse project should run a monitoring service to see if DataCite, OSF, RSpace, etc. are up. If someone out there sets up this monitoring service, I'd certainly use it if I think something's down.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
