### ISSUE TITLE
Button to switch visibility of an unpublished dataset

### ISSUE THREAD

**Issue by RightInTwo** [IQSS/dataverse#5764]
As a institutional repository admin, I would like to enable users to make *some* unpublished Datasets and Dataverses visible to members of a certain group (in this case an IP Group: all users from within the local network).

Ways to go about it:
a) Show the relevant Dataverses and Datasets only to users of that group
b) Add another state (like InstitutionalAccess or RestrictedVisibility or InternalDataset or ...) and relevant permissions that can then be assigned to the group
c) another way....?

In a [discussion on the IRC](http://irclog.iq.harvard.edu/dataverse/2019-04-17), @poikilotherm and @pameyer brought a lot of valuable comments into this, like the strong analogies to the state when data is in review.

@pameyer or @poikilotherm: Do you know which issues should be linked here?

**Comment by RightInTwo** [comment]
The goal would be to have three levels of access:
a) External users: See published datasets/verses in the two public dataverses
b) DOES NOT EXIST (right?): Internal users: see published datasets/verses in all dataverses
c) Curators/Admins (can be people or units): See unpublished datasets/verses they own

**Comment by RightInTwo** [comment]
Example: Researcher has preliminary data that they do want to publish, but share it with the other >100 researchers in the institution.

**Comment by djbrooke** [comment]
Hey @RightInTwo - this is something that we've kicked around a bit but we haven't had a great solution for. I am heading into a meeting, but thought I'd quickly mention the private URL feature: 

http://guides.dataverse.org/en/latest/user/dataset-management.html#private-url-to-review-unpublished-dataset

This lacks this discovery/searching part, but could help with the access part - just a thought.

**Comment by RightInTwo** [comment]
@djbrooke Hey Danny, nice to "see" you! Thanks for the input! Discovery/Listing is a major point, though... I would like to see these datasets in a widget on the intranet.

**Comment by scolapasta** [comment]
@RightInTwo I'm probably missing something, but can't this be done now?

You can assign the Member role to the IP group you want to have access to a particular dataset or dataverse. (note this would allow them to download the files, as well; if you need to not allow this, you would need to create a new custom role that is like Member but without the DownloadFile permission).

**Comment by RightInTwo** [comment]
@scolapasta In that scenario, how do the owners distinguish which of their unpublished datasets they would like to have visible on an institutional level?

**Comment by scolapasta** [comment]
The owner would need to have the ability to manage permissions, but assuming they do, they would just assign the role for the object.

**Comment by RightInTwo** [comment]
Yes, that's a good point. So maybe nothing more is needed than buttons to add/remove the "Any User on the institutional network" role to/from the Dataverse/set.

![image](https://user-images.githubusercontent.com/12545221/56312552-a7159c00-6150-11e9-8a7d-8017445e5739.png)

**Comment by scolapasta** [comment]
In other words your asking for a shortcut to grant / remove this role assignment? (similar to the default options for a dataverse which are just a short cut to give "Dataverse/Dataset creator) roles to the "AuthenticastedUsers" group)

**Comment by RightInTwo** [comment]
Sounds good! I guess the button would need to switch states (grant/remove) and only be visible for unpublished datasets...

**Comment by RightInTwo** [comment]
![image](https://user-images.githubusercontent.com/12545221/56315907-4b9bdc00-6159-11e9-9d4d-ca59c0407ece.png)

**Comment by RightInTwo** [comment]
One problem I see that remains with this solution: No versioning is possible without publishing. Is there a way to version a dataset without publishing it?

**Comment by pdurbin** [comment]
@RightInTwo that's correct. In Dataverse, versioning is tied to publishing. There's an old issue about this: Support versions before a dataset is published #1002

**Comment by pdurbin** [comment]
@RightInTwo are you still interested in this? Thanks. Hope you're well!

**Comment by RightInTwo** [comment]
@pdurbin Hi Phil! I'm actually not working in research data anymore, now rather web dev, so I don't know if my colleagues are still pursuing it. I think I will just close it, as nobody else has shown interest yet. Best wishes to the team :)
