### ISSUE TITLE
Clean up VersionNote, ArchiveNote, DeaccessionLink in DatasetVersion

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#5767]
In attempting to debug both:
https://github.com/IQSS/dataverse.harvard.edu/issues/8
https://github.com/IQSS/dataverse.harvard.edu/issues/15

we noticed that the reason for deaccession was being stored as VersionNote and the link for where as ArchiveNote. However, ArchiveNote used to store text info (such as "Replaced by version x").

We need to clean these up, removing anything that is no longer needed from DVN 3 days:
• do we actually need that "replaced by version x"? 
• do we need "Initial version"?
• do we need any of the version notes which were user entered, but we no longer display anywhere?

and then make sure we store the deaccession reason and link in specific fields that we also then properly validate.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
