### ISSUE TITLE
Integration tests failing, on 4.13 release candidate

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#5768]
Observed on phoenix.harvard.edu:
1st try: 
https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-apitest-develop/359/

Test Result (6 failures / +6)
DatasetsIT.testCreatePublishDestroyDataset
DatasetsIT.testExcludeEmail
DatasetsIT.testUpdatePIDMetadataAPI
DatasetsIT.testExport
SearchIT.testSearchPermisions
SearchIT.testSubtreePermission

2nd try: 
https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-apitest-develop/360/
3 failures:
DatasetsIT.testUpdatePIDMetadataAPI
SearchIT.testSearchPermisions
SearchIT.testSubtreePermissions

somewhat different results on my own build (will enter below)

**Comment by landreev** [comment]
On my own build I'm getting the results that are the hybrid of the 2 results on the phoenix server above.

DatasetsIT - passes  (with a bunch of exception stack traces in the log, but passes)
SwordIT: - testCreateAndDeleteDatasetInRoot fails consistently; 
SearchIT: SearchIT: - 2 failures (consistently): earchIT.testSearchPermisions and SearchIT.testSubtreePermissions

**Comment by landreev** [comment]
Third attempt to run the tests on phoenix.dataverse.org - back to 6 failures: 
https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-apitest-develop/361/console
(these 2nd and 3rd attempts were just running the 3rd Jenkins job again; skipping the first 2 jobs that build the branch, drop the db. and redeploy, from scratch)

**Comment by landreev** [comment]
For reference:
Most of these failures (and intermittent failures) were traced to the extra 1 second sleep in the indexing code, that was added in this release in order to solve a problem where permissions were not properly indexed. Because of the extra time it's now taking to index the dataset, attempts to modify it immediately after publishing are now likely to result in a 500 - because of an underlying EJB conflict w/ the indexing code attempting to modify the "lastindextime" timestamp on the dvobject. 
These were all fixed by throwing extra Thread.sleep() calls at the problem. (whether that's a good solution - we may need to discuss; there may still be other places in the tests code that are working now purely by luck)
Two PRs were made in the process, both have been merged, things have been tested and release has been cut. 

Two tests causing intermittent failures were masked with @Ignore, and the issue #5771 has been opened to address the underlying problem.

**Comment by matthew-a-dunlap** [comment]
Glad that you were able to find the root cause for these, sorry I didn't catch them when developing on the issue!
