### ISSUE TITLE
Status Message - UX Improvements

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#5769]
_Originally posted by @shlake in https://github.com/IQSS/dataverse/issues/5638#issuecomment-484255584_

> OK, UVa - test system is now at 4.12. And in the process has realized that the "bubble" text for StatusMessageHeader no longer appears as Don points out as on UNC's test V 4.9.4 https://dataverse-test.irss.unc.edu/. 
> 
> My concerns with the current way status is shown.
> 
> 1. A user can dismiss the notice (and then "forget" about it). If a browser is not closed, but windows are, when a new DV window opens the notice is not there (because it was dismissed previously).
> 2. With current config, you need to set BOTH StatusMessageHeader AND StatusMessageText with content for the alert panel to show up.
> 3. Why do I need to break up my text into two settings StatusMessageHeader AND StatusMessageText (in order for it to show up)?
> 4. I really liked the "bubble" text in the header - from StatusMessageHeader because that message appeared on EVERY page.
> 
> Maybe have two types of status - one for alerts - yellow panel, that can be turned off and one for warnings that cannot be turned off - red panel??
> 
> Thanks for listening.

**Comment by TaniaSchlatter** [comment]
Hi @shlake, we moved the status message out of the header to make more room for navigation (see #4842 as one example). We discussed "dismissing" behavior, and made the call that users should be able to dismiss messages, even status messages. We were not considering the use case of a more long-term status message. I wonder about making the "dismissability" an admin option, or as you note, introducing an additional type of message that the user can not dismiss. Do you have some examples of what the content of that type of message might be? Thanks!

**Comment by shlake** [comment]
Hi Tania,
Let me get back to you on examples. We use those (ones that can be dismissed & those that can't) on our UVa Library web pages.

I guess my main surprise was that the "old" header status (location) had been changed & the information about that change was sort of hidden in the guides.

**Comment by pdurbin** [comment]
@shlake hi! Still interested? Thanks!

**Comment by pdurbin** [comment]
@shlake sounds good. I'll go ahead and close it then. Please feel free to open a fresh issue in the future!
