### ISSUE TITLE
Hard-coded values in some DatasetsIT tests prevent them from working reliably

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#5771]
In DatasetsIT RA test testExport(), note the following 2 lines:
```
// FIXME: make this less brittle by removing "2" and "0". See also test below.
                .body("data.latestVersion.metadataBlocks.citation.fields[2].value[0].datasetContactEmail.value", equalTo("sammi@sample.com"))
```
It looks like the person who wrote them knew that this was not going to work consistently, because these hard-coded numbers are not guaranteed to correspond to the right json parts. Some work was done on this test method that must have affected the timing (?) of how things are cooked, so the test is now failing pretty often, because the field number 2 in the citation is not the contact email. 
Needs to be rewritten to go through the fields and look for the right one (?)
This same test line appears in another DatasetsIT test, testUpdatePIDMetadataAPI() - so needs to be fixed there too.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
