### ISSUE TITLE
Document queries used to de-identify user data

### ISSUE THREAD

**Issue by dheles** [IQSS/dataverse#5776]
Documentation of SQL queries that could be used to de-identify user data within a Dataverse database would be useful. Per discussion with @pdurbin, a good place for them would be the following section of the Admin Guide:
http://guides.dataverse.org/en/4.13/admin/backups.html

Relates to: #4169

**Comment by pdurbin** [comment]
Yes, we talked this out at http://irclog.iq.harvard.edu/dataverse/2019-04-22

@dheles thanks for creating this issue! As I mentioned in IRC, even if you simply create a pull request with your script(s) in `doc/sphinx-guides/source/_static/admin` that would be a great start and we can link 'em up for you. 😄

**Comment by pdurbin** [comment]
@dheles hi! Are you still interested in this? No pressure if you aren't! 😄

**Comment by dheles** [comment]
Apologies, @pdurbin -

I moved on from the job that had me involved with dataverse several years ago. Sorry I didn't wrap this up before doing so. Best I can offer at this point is my one remaining note on the matter:

```
TRUNCATE TABLE actionlogrecord, apitoken, confirmemaildata, fileaccessrequests, guestbookresponse, maplayermetadata, oauth2tokendata, passwordresetdata, pendingworkflowinvocation_localdata, pendingworkflowinvocation, savedsearchfilterquery, savedsearch, worldmapauth_token;

-- TODO: authenticateduser, authenticateduserlookup, builtinuser, datasetversionuser, dataversecontact, dvobject (creator_id, owner_id), roleassignment (assigneeidentifier), usernotification
```

IIRC, those truncated tables could be successfully truncated w/o issue, while the TODO tables could not (due to referential integrity issues, perhaps). I don't believe I ever went back to look for PII-containing fields and clean them out in a less brute-force kind of way. Hope this is helpful.

-drew

**Comment by pdurbin** [comment]
@dheles no worries! Thanks for getting back to me so quickly. Some of those old tables are gone now such as `worldmapauth_token` but perhaps someone out there will find your SQL statement useful (maybe for #6775?).

I'll go ahead and close this out. Enjoy the new job!
