### ISSUE TITLE
bump jdbc driver to current version

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#5784]
we're packaging Postgres JDBC 42.2.2, which is now over a year old. 42.2.5 was released on 27 Aug 2018 and seems fine according to my limited testing.

**Comment by poikilotherm** [comment]
Just my 2 cents: using 42.2.5 in my Docker images, as the [release notes of the Postgres drivers](https://jdbc.postgresql.org/documentation/changelog.html#version_42.2.5) did not show anything to worry from since 42.2.2.

**Comment by qqmyers** [comment]
same - we're testing 42.2.5 and see no issues.

**Comment by djbrooke** [comment]
@poikilotherm @donsizemore @qqmyers any volunteers for a PR? I was going to make the change but it's been awhile since the discussion and I'm not sure if 42.2.5 is still the right version to move to. Thank you!

**Comment by qqmyers** [comment]
FWIW: QDR's been using postgresql-42.2.5.jar, but I haven't looked for newer updates lately. I can't immediately volunteer.

**Comment by donsizemore** [comment]
The current version is https://jdbc.postgresql.org/download/postgresql-42.2.9.jar — I think I've dropped it in place on a few of our test instances. I can make a PR if you'd like.

**Comment by poikilotherm** [comment]
Doesn't look like https://jdbc.postgresql.org/documentation/changelog.html names breaking changes.
I'll try to update my images and test.
