### ISSUE TITLE
UZH: Refactoring tests for AuthenticationProvider, SearchUtil, and PrivateUrlUtil

### ISSUE THREAD

**Issue by rschlaefli** [IQSS/dataverse#5795]
This issue is about refactoring existing unit tests that contain test smells (see #5732). See #5619 for additional details.

**Comment by pdurbin** [comment]
@rschlaefli as I mentioned at https://github.com/IQSS/dataverse/pull/5775#issuecomment-487923079 I'm concerned about the (slight) decrease in code coverage.

**Comment by pdurbin** [comment]
@rschlaefli also, can you please give this issue a more meaningful title? Thanks!
