### ISSUE TITLE
New API: Add API end point to copy language-pack to Dataverse Installation

### ISSUE THREAD

**Issue by JayanthyChengan** [IQSS/dataverse#5806]
Create an API call to copy the property files from https://github.com/GlobalDataverseCommunityConsortium/dataverse-language-packs to the [dataverse.lang.directory](http://guides.dataverse.org/en/latest/installation/config.html#dataverse.lang.directory) path specified in dataverse installation.

**Comment by djbrooke** [comment]
Hi @JayanthyChengan - is this something that you're working on or are planning to work on?

**Comment by JayanthyChengan** [comment]
@djbrooke :  I am working on it and will submit PR soon

**Comment by djbrooke** [comment]
Awesome, thanks @JayanthyChengan !

**Comment by JayanthyChengan** [comment]
@djbrooke - submitted PR #5843

**Comment by pdurbin** [comment]
@JayanthyChengan thanks for the pull request! I'm excited to try this out but I requested changes, docs, specifically. Thank you!!

This work is very timely because @pkiraly just gave us a lot of great feedback at https://groups.google.com/d/msg/dataverse-community/AgYRCOz1Tlk/ex66tU9FAwAJ

**Comment by djbrooke** [comment]
@JayanthyChengan - I'm moving this back to code review for some doc changes. Please let us know when it's ready for another code review pass. Thanks!

**Comment by pdurbin** [comment]
In 5a8c18d I added @JayanthyChengan 's write up to a new "Internationalization" section of the config section of the Installation Guide. I tried it out on dev2 and it seemed to work. @JayanthyChengan heads up that I looks some liberties to re-write and add what I hope is clarity. 😄 Off to QA! Thanks!

**Comment by JayanthyChengan** [comment]
Thanks @pdurbin

**Comment by pkiraly** [comment]
@JayanthyChengan: great work, congratulation!

For me it is still open question if the language pack should or should not contain the original language property files available in the Dataverse core.

Don't you want to cover dataverse-docker repository's language properties as well? Or maybe move the language files from there to the now referenced repository? (I include @4tikhonov into this discussion.)

**Comment by pdurbin** [comment]
@pkiraly yes, I believe the English files are required. Please see #5793 and this note that I left in the guides (I just highlighted the important part in my browser):

![Screen Shot 2019-05-15 at 4 19 53 PM](https://user-images.githubusercontent.com/21006/57806539-52544980-772d-11e9-83d0-d1fb701c8662.png)

And yes, we absolutely want the languages in the dataverse-docker repo. Please see this issue I just opened (and please feel free to work on it if you'd like! 😄 ): https://github.com/GlobalDataverseCommunityConsortium/dataverse-language-packs/issues/10
