### ISSUE TITLE
E-mail for users does not properly trim

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#5807]
This allows you to create a user when a space at the end of the e-mail and effectively use the same e-mail address for multiple accounts, which we don't want to allow.

**Comment by scolapasta** [comment]
This query can be used to find example of these "duplicates":

select distinct au.useridentifier,au2.useridentifier,
'"'||au.email||'"' as em, au.firstname, au.lastname, au.createdtime, au.lastlogintime
from authenticateduser au, authenticateduser au2
where trim(au.email) = trim(au2.email)
and au.id != au2.id order by em;

**Comment by djbrooke** [comment]
@scolapasta - is this solely a code change or will there need to be any cleanup before/after a release that contains this code change?

**Comment by scolapasta** [comment]
There will need to be cleanup; in particular, people have used this loophole to use the same e-mail address for multiple accounts. So those e-mails will need to be changed before the cleanup (trim what is in db) can happen.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
