### ISSUE TITLE
update install docs: PostgreSQL 9.3 is EOL

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#5809]
pull request forthcoming.

**Comment by pdurbin** [comment]
@donsizemore I'm confused. According to https://flywaydb.org/documentation/database/postgresql PostgreSQL 9.3 is supported. Here's a screenshot:

![Screen Shot 2019-05-02 at 3 31 48 PM](https://user-images.githubusercontent.com/21006/57101536-77899680-6cef-11e9-982a-e250d32f5851.png)

In pull request #5810 you're removing the strong recommendation for 9.6:

![Screen Shot 2019-05-02 at 3 33 37 PM](https://user-images.githubusercontent.com/21006/57101670-b61f5100-6cef-11e9-9a23-852d5c14726b.png)

What version of PostgreSQL does that "latest" yum command install? I like knowing what version of PostgreSQL we're indicating that people should install. Currently the `postgresql96` RPM is installed.

**Comment by donsizemore** [comment]
@pdurbin right you are. I remembered the error:

> Flyway Enterprise Edition or PostgreSQL upgrade required: PostgreSQL 9.2 is past regular support by PostgreSQL and no longer supported by Flyway Community Edition

but incorrectly conflated it with 9.3, which is also no longer supported by Postgres upstream but apparently still supported by Flyway.

**Comment by pdurbin** [comment]
@donsizemore ok. Thanks. Should a pull request simply be a doc change, then? Without touching the yum lines, which already install the `postgresql96` RPM?

**Comment by pdurbin** [comment]
@donsizemore can you please write some more here about this new single repo thing and postgres 10 an 11? Thanks!

**Comment by donsizemore** [comment]
I'm proposing we update the PostgreSQL repo RPM per [https://yum.postgresql.org/repopackages.php](https://yum.postgresql.org/repopackages.php) which announces

> As of 15 April 2019, there is only one repository RPM per distro, and it includes repository information for all available PostgreSQL releases.

**Comment by pdurbin** [comment]
@donsizemore I just opened https://github.com/IQSS/dataverse-ansible/issues/63 after talking to @djbrooke @landreev and @kcondon after standup. I offered to make a pull request with the changes we think we want, which is to change the docs to remove the suggestion of running PostgreSQL 9.3, which we don't test with, and keeping in the line about PostgreSQL 9.6 being strongly recommended. That ansible issue is about future experiments with PostgreSQL 10.

I'm not sure if I'm fully groking the implications of the one repo thing, but I'll make a pull request so we can hash it out.

One thing we were saying at standup is how we really appreciate that you are on the frontier, trying things out like Shibboleth 3 and reporting back if it's working or not. It's extremely valuable to us. Thank you!

**Comment by pdurbin** [comment]
@donsizemore ok, please take a look at pull request #5813 which I just made. Thanks!

**Comment by donsizemore** [comment]
@pdurbin PostgreSQL now publishes one repo RPM per distribution (RedHat7, CentOS7, etc) then references each version in the package name: postgresql96-*, postgresql10-*, postgresql11-*

With 10+ they added a dash to the postgresql-setup binary name so I'm throwing a switch in dataverse-ansible to account for that. I tested deployment with no SQL errors on 10 and 11, but I didn't exercise much code beyond the sample data creation.

**Comment by pdurbin** [comment]
@donsizemore ok, maybe we should talk this out in IRC a bit more but is fec1a26 enough of a change to put through QA? I'm not switching to a new repo RPM. It's just a doc change to stop suggesting that 9.3 is to use. I'm taking your word for it that it's EOL. :)

**Comment by donsizemore** [comment]
@pdurbin 9.3 is EOL: https://yum.postgresql.org/

I'm happy to marinate the repo RPM change in dataverse-ansible for a bit before we update the installation docs. It's a pretty transparent change.

**Comment by pdurbin** [comment]
Thanks. I love screenshots so here we go:

<img width="626" alt="Screen Shot 2019-05-03 at 12 55 17 PM" src="https://user-images.githubusercontent.com/21006/57152870-c2181b00-6da2-11e9-9a76-a962e38321c2.png">

Thanks for noticing this! I'll close the pull request with the yum change (yes! let's marinate it more over in dataverse-ansible!) and put the doc change only one into QA.
