### ISSUE TITLE
Correction to make in the Guides to Download Package File via rsync instructions

### ISSUE THREAD

**Issue by TaniaSchlatter** [IQSS/dataverse#5816]
There is a small clarification needed in the description of downloading a package file via rsync in the guides. "Dataset" highlighted in the image below should be "file." In addition, we should state that users can get access instructions on the dataset page in the file table. 
<img width="1233" alt="Screen Shot 2019-05-06 at 11 12 12 AM" src="https://user-images.githubusercontent.com/15386424/57234967-d735b980-6fef-11e9-8942-2f3ac70ca14d.png">
<img width="686" alt="issue_3998_DataAccess_tab" src="https://user-images.githubusercontent.com/15386424/57235896-f0d80080-6ff1-11e9-8bc4-ceb6621e0069.png">
<img width="681" alt="Screen Shot 2019-05-01 at 2 49 28 PM" src="https://user-images.githubusercontent.com/15386424/57235945-03ead080-6ff2-11e9-94ed-f41f1dbe9248.png">

**Comment by pdurbin** [comment]
@TaniaSchlatter and I discussed this issue yesterday. I just made pull request #5818 and will move this to code review. Here's a screenshot of what I wrote:

![Screen Shot 2019-05-07 at 9 29 13 AM](https://user-images.githubusercontent.com/21006/57303103-99499b80-70aa-11e9-8a22-66c1e6b214f0.png)

**Comment by pdurbin** [comment]
@TaniaSchlatter and I talked this out and we (mostly Tania) came up with the version I just pushed in 802fb6d8a . Here's a screenshot:

<img width="884" alt="Screen Shot 2019-05-07 at 10 39 00 AM" src="https://user-images.githubusercontent.com/21006/57308477-6ad0be00-70b4-11e9-8865-ac789c361fc0.png">

**Comment by pdurbin** [comment]
@TaniaSchlatter and I decided to add a little more bold text in 0523eea.
