### ISSUE TITLE
Unit Test `formatIdsForSolrClause` of `SolrQueryFormatter.java`

### ISSUE THREAD

**Issue by alexscheitlin** [IQSS/dataverse#5821]
Hi guys,

as described in #5619 I focus on unit testing. This time, I'll have a look at the function below.

Until now, the function was only tested indirectly and thus not completely (even though coveralls shows that most of the lines are covered, [see here](https://coveralls.io/builds/23241781/source?filename=src/main/java/edu/harvard/iq/dataverse/mydata/SolrQueryFormatter.java#L35)). More importantly, the function is not tested with considering different "input combinations". To directly call the function for proper testing, I need to change the method's access modifier from `private` to `protected`.

https://github.com/IQSS/dataverse/blob/a9605376c6be3d14c14592c1f692a3f83efae9df/src/main/java/edu/harvard/iq/dataverse/mydata/SolrQueryFormatter.java#L29-L60

**Comment by djbrooke** [comment]
Thanks @alexscheitlin! I moved this over to Community Dev for now. Let us know when you have PR that you'd like reviewed.

**Comment by alexscheitlin** [comment]
> Thanks @alexscheitlin! I moved this over to Community Dev for now. Let us know when you have PR that you'd like reviewed.

Hi @djbrooke, I created a PR (#5829). It is ready for review.
