### ISSUE TITLE
Export for variable level metadata

### ISSUE THREAD

**Issue by lubitchv** [IQSS/dataverse#5822]
Data Curation tool will allow users to edit variable level metadata and create a new version of dataset. Therefore export of DDI XML in dataverse should take under consideration the version that user wants to export (Download->Variable Metadata), i.e export API should use not only fileId, but FileMetadataId for proper version identification. To do that export api will need new optional query parameter filemetadataId. In the case that parameter is not given, the export should work as it works now and export the latest version of metadata.

**Comment by djbrooke** [comment]
Thanks @lubitchv - I'll move this over to community dev.

**Comment by djbrooke** [comment]
You're quick @lubitchv! Is the PR ready for review?

**Comment by lubitchv** [comment]
@djbrooke Yes, it is ready.

**Comment by kcondon** [comment]
@lubitchv To test this I should have more than one version to reference, correct? Is there currently a way to generate such a version or do I need to duplicate a record in the db and change the key?

**Comment by lubitchv** [comment]
Yes, you need different versions that will have different fileMetadataId. Presently, you can publish the draft version and EditFiles -> Metadata. It will create a new Draft version for you. Then you can Download->Variable Metadata for Draft and published version of XML files. Although the change in code was meant for VariableMetadata (in variablemetadata table) and I have not yet submitted the API for  updating variable metadata.

**Comment by kcondon** [comment]
@lubitchv OK, I can do that, thanks. What I noticed is that it does not seem to care about the actual fileMetadataId value -it will return something if it is a valid file and I enter an id  of 1 or 1000, even though 1000 does not exist. So, I can't tell if it is checking. Sorry for being slow but where do I find the fileMetadataId value? I see a column named filemetadata_id in the variablemetadata table but it is empty.

**Comment by kcondon** [comment]
@lubitchv OK, I think I have it now:
dvndb=# select id, label, datasetversion_id from filemetadata where datafile_id=2214;
  id  |    label     | datasetversion_id 
------+--------------+-------------------
 2140 | 50by1000.tab |               107
 2139 | 50by1000.tab |               106
(2 rows)

filemetdataid is the primary key for the filemetadata table. Above are the entries for my test file. However, as I mentioned I can put any number in as id and it works and so far I can't tell if I'm getting the number I requested. I can try modifying the metadata directly and look at it.

**Comment by lubitchv** [comment]
@kcondon 
It should return different variable metadata in DataDscr section of xml. But that data depends on data in variablemetadata table. Sumstats do not change. Since I have not yet provided an API for updating values in variablemetadata table, it is empty and you get the same xml. To check Variable Metadata you can update variablemetadata table manually with existing draft version filemetadataId.  In that case you should get different xml files for drafted and published version. Difference will be on var level for interview instruction, notes, postquestion etc.

But I noticed a bug in biblCit, for biblCit it takes the latest verson instead of the proper version. I was concentrated on variable level metadata (DataDscr)  and missed StdyDscr. Y I will fix that.

**Comment by kcondon** [comment]
@lubitchv OK, I was able to get the changed value to appear when requested. I'm not 100% sure yet how it should be presented:
dvndb=# insert into variablemetadata (filemetadata_id, datavariable_id, interviewinstruction, notes, postquestion) values (2140, 1544, 'interviewinstruction value', 'notes value', 'postquestion value');
results in:
dvndb=# select * from variablemetadata;
 id |    interviewinstruction    | isweightvar | label | literalquestion |    notes    | universe | weighted | data
variable_id | filemetadata_id | weightvariable_id |    postquestion    
----+----------------------------+-------------+-------+-----------------+-------------+----------+----------+-----
------------+-----------------+-------------------+--------------------
  2 | interviewinstruction value |             |       |                 | notes value |          |          |     
       1544 |            2140 |                   | postquestion value
(1 row)

results in:

<sumStat type="medn">5.5</sumStat><sumStat type="max">10.0</sumStat><sumStat type="mean">5.5</sumStat><sumStat type="vald">1000.0</sumStat><varFormat type="numeric"/><notes subject="Universal Numeric Fingerprint" level="variable" type="VDC:UNF">UNF:6:8OuUohmPouAgl2L3IrfN2A==</notes><notes><![CDATA[notes value]]></notes><qstn><ivuInstr>interviewinstruction value</ivuInstr><postQTxt>postquestion value</postQTxt></qstn></var><var ID="v1498" name="var42" intrvl="discrete"><location fileid="f2214"/><labl level="variable">var1</labl>

**Comment by lubitchv** [comment]
@kcondon Your xml result looks OK to me. I attach the example of xml file with variable metadata, how it suppose to look.
[DDI_with_var_metadata.txt](https://github.com/IQSS/dataverse/files/3192094/DDI_with_var_metadata.txt)
I attached it with txt extension since github did not allow me to attach xml. 

CDATA in second notes value looks perfectly fine to me. You will see that there are two types of notes. One is something like that <notes subject="Universal Numeric Fingerprint" level="variable" type="VDC:UNF">UNF:6:HbM1tFHAsgACfUYee9JhTQ==</notes>
I also added new notes <notes><![CDATA[Long notes for first variable]]></notes>  There will be both in XML.

![CDATA] is a tag for rendering HTML and it is done on purpose.

I fixed the BiblCit and fileDscr that I missed last time and updated the branch.

**Comment by kcondon** [comment]
@lubitchv Thanks, I'm looking at it now.
