### ISSUE TITLE
Long edits timeout

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#5823]
Somewhat analogous to long uploads timing out, long edits can cause a timeout that leaves the dataset or datafile page where the edit was initiated perpetually in a wait state (spinning icon, grayed out, showing edit mode). The edit itself continues to completion, with further edits not allowed until finished (see #5550). 
The timeout we saw at QDR was for the AJP connection between Apache2 and Glassfish. The timeou can be lengthened from a default of ~300 seconds by changing the apache config line:
ProxyPass / ajp://localhost:8009/ 
to
ProxyPass / ajp://localhost:8009/ timeout=600
(for example).
For QDR, we've gone ahead and caught the error itself and added code to add a warning message and return to the dataset/datafile page in non-edit mode (which would happen if the edit completed successfully) and, further, tied into the edit lock proposed in #5550 and the refresh mechanism currently in the dataset page to auto refresh until the edit completes and the lock is removed. To handle edits initiated from a datafile page, we've also ported the auto page refresh code to work on the datafile page as well.

Some or all of this code may be relevant for the community. Nominally, I think the error handling to trigger a warning and page refresh could be separated out. Similarly, the addition of an auto-refresh to the datafile page could be useful for non-edit locks (providing a warning and un-graying the edit buttons if/when the lock is removed). If edit locks (#5550) are incorporated, the error handling would trigger a message and the page refresh mechanisms would remove the warning when the edit completes. 

If this is something to provide a PR(s) for, let me know.

**Comment by djbrooke** [comment]
Hi @qqmyers - I'll let someone more technical respond as well, but we did an investigation into some timeouts in #5598 and we decided the best way to resolve them was with the implementation of OnSuccess in #4425.

**Comment by qqmyers** [comment]
@djbrooke - that may speed things up enough to make timeout errors be very rare/not occur, but I don't think it does anything to handle if/when they occur. (in any case +1 for indexing once at the end of a composite operation on a dataset!)

**Comment by pdurbin** [comment]
Now that pull request #5987 for onSuccess (#4425) has been merged, I'd like to suggest that this issue can be put through QA. Again, the initial investigation that lead to the conclusion that we should go ahead implement onSuccess was done in #5598. Indexing was related to the slowdown and in the "develop" branch, indexing is now part of onSuccess.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
