### ISSUE TITLE
Rest assured tests failing for v4.14

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#5826]
[ERROR] Tests run: 14, Failures: 2, Errors: 0, Skipped: 2, Time elapsed: 36.244 s <<< FAILURE! - in DatasetsIT
[ERROR] testSequentialNumberAsIdentifierGenerationStyle  Time elapsed: 2.569 s  <<< FAILURE!
junit.framework.AssertionFailedError: expected:<200> but was:<500>
	at edu.harvard.iq.dataverse.api.DatasetsIT.testSequentialNumberAsIdentifierGenerationStyle(DatasetsIT.java:667)

[ERROR] testCreateDataset  Time elapsed: 0.945 s  <<< FAILURE!
junit.framework.AssertionFailedError: expected:<10> but was:<5>
	at edu.harvard.iq.dataverse.api.DatasetsIT.testCreateDataset(DatasetsIT.java:118)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   DatasetsIT.testCreateDataset:118 expected:<10> but was:<5>
[ERROR]   DatasetsIT.testSequentialNumberAsIdentifierGenerationStyle:667 expected:<200> but was:<500>
[INFO] 
[ERROR] Tests run: 91, Failures: 2, Errors: 0, Skipped: 4
[INFO] 
[ERROR] There are test failures.

**Comment by donsizemore** [comment]
@kcondon i've been running the api test suite by way of adding it to jenkins.dataverse.org in docker-aio, and this morning in 4.14 develop i make it to:

>[ERROR] Tests run: 14, Failures: 1, Errors: 0, Skipped: 2, Time elapsed: 433.601 s <<< FAILURE! - in DatasetsIT
[ERROR] testPrivateUrl  Time elapsed: 315.83 s  <<< FAILURE!
junit.framework.AssertionFailedError: expected:<200> but was:<500>
	at edu.harvard.iq.dataverse.api.DatasetsIT.testPrivateUrl(DatasetsIT.java:943)

(just FWTW)

**Comment by pdurbin** [comment]
For the record, I just ran the rest assured tests in docker-aio as of 268a87cad on my Mac and they passed. They were failing a few days ago.
