### ISSUE TITLE
Subset and Analysis: Subsetting a particular file in production results in exception with number of extra rows. Download file works.

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#584]
---

Author Name: **Kevin Condon** (@kcondon)
Original Redmine Issue: 4013, https://redmine.hmdc.harvard.edu/issues/4013
Original Date: 2014-05-20

---

Reported by a user, see RT #179122: subsetting this data file is causing an error

[Kevin] I checked the dimensions of the tab file and it appears to be the same as the original stata file so maybe there is a character in the data that breaks a line and causes the bad row count?

From Sonia:

Error received:

Error Message:javax.faces.el.EvaluationException: 
java.lang.RuntimeException: Tab file has extra nonempty rows than the 
determined number of cases. If this continues to occur, please Contact 
<http://thedata.harvard.edu/dvn/faces/ContactUsPage.xhtml [Open URL]> the Dataverse 
Network admin with this message.

Event occurred at May 20, 2014 3:10:35 PM

The dataverse/study: 
http://thedata.harvard.edu/dvn/dv/Migration/faces/study/StudyPage.xhtml?globalId=hdl:1902.1/20463&studyListingIndex=20_9eac00a0dc198ac567d20ff4f3be [Open URL]

This tabular data file.

I can download the entire file as stats original, but when you attempt 
to subset and zip the file, the error above happens.

**Comment by scolapasta** [comment]
Is this just a 3.6 issue? Is there anything we need to do in 4.0?

**Comment by sbarbosadataverse** [comment]
Kevin--Not sure what to do with this. This file was tested iin 3.6, but doesn't appear from the notes in this ticket that anything was done to fix it? Do you just want me to test this particular file in 4.0?

**Comment by kcondon** [comment]
@sbarbosa

Yes, go to the redmine/RT ticket mentioned in the ticket and it should contain the file. Try to ingest it, then subset it.

Let me know if you have any trouble with that
________________________________

**Comment by sbarbosadataverse** [comment]
I was able  to successfully select "data subset," select files, and save the file.
