### ISSUE TITLE
OAI server guides documentation -  requires editing

### ISSUE THREAD

**Issue by janetm** [IQSS/dataverse#5840]
OAI server documenation states "Only the published, **unrestricted datasets** in your Dataverse can be made harvestable".  This is misleading as metadata  can be harvested whether dataFILES are restricted or unrestricted.  Also, datasets are not restricted, only datafiles are restricted.
http://guides.dataverse.org/en/latest/admin/harvestserver.html

Phil Durbin asked me to open this issue to have the documentation updated: 
 https://groups.google.com/forum/#!searchin/dataverse-community/oai%7Csort:date/dataverse-community/DtLfBfxs1lc/wUSynlc2AwAJ

**Comment by pdurbin** [comment]
@janetm all set! Fixed by @shlake in this pull request:

- #9055
