### ISSUE TITLE
Change the publisher name from root

### ISSUE THREAD

**Issue by MohanaPriyaNarapareddy** [IQSS/dataverse#5841]
The following is the use case of my process. 
1. Importing the existing dataset from datacite to dataverse without publishing ("release=No"),
2.  Then modifying the imported dataset in the UI by adding additional files.
Now when i add the files in the UI and then publish the dataset., it results in the modification of  existing DataCite record by Dataverse. Still i don't have problem with the modification of datacite record, but the publisher name is being changed to "root" (since i am publishing from dataverse root) instead of "cancer imaging archive".  Now, I want to change the publisher name from root to "cancer imaging archive".    I am not sure what attribute in dataverse  maps the name of the "publisher" in datacite. Please let me know, the required changes to be made in dataverse to change the publisher name in the datacite.

**Comment by pdurbin** [comment]
@MohanaPriyaNarapareddy hi! It's funny, @amberleahey @johnhuck @jggautier and I were just talking last week about #2146 and how the name of the root dataverse appears as the publisher in the citation.

http://guides.dataverse.org/en/4.14/installation/config.html#branding-your-installation currently says this:

"The name of your root dataverse is the brand of your installation of Dataverse and appears in various places such as notifications and support links..."

One of the "various places" is the citation! 😄 This should be documented.

Here's a screenshot from #2146 that shows that in DVN 3 the citation used to include the name of the parent dataverse ("Massachusetts Archives, Boston MA") but that now in Dataverse 4 the name of the root dataverse ("Harvard Dataverse") is shown:

![Screen Shot 2019-05-13 at 11 06 33 AM](https://user-images.githubusercontent.com/21006/57632298-50dd2280-756f-11e9-9c31-44069824d5a1.png)

**Comment by sharmaashish** [comment]
@pdurbin The **Root** that @MohanaPriyaNarapareddy is referencing is the value that populates in the Datacite metadata. Take a look at this JSON document:
https://api.datacite.org/dois/application/vnd.datacite.datacite+json/10.7937/k9/tcia.2018.15quzvnb
This is the metadata for one of the DOIs that we imported (we are migrating from an in-house solution to Dataverse). When this was published via Dataverse it changed/set the publisher to **Root**. We'd like it to be **The Cancer Imaging Archive**

**Comment by jggautier** [comment]
Would it be possible to change the branding of your Dataverse from "Root" to "The Cancer Imaging Archive"?

**Comment by sharmaashish** [comment]
Sure. I don't care for **Root** But would changing the branding also reflect in the documents that are sent to Datacite?

**Comment by pdurbin** [comment]
After adjusting the name of your root dataverse (changing to from "Root" to "The Cancer Imaging Archive" or whatever), you can re-sent the metadata to DataCite using this API endpoint: http://guides.dataverse.org/en/4.14/admin/dataverses-datasets.html#send-dataset-metadata-to-pid-provider

It should work anyway. I haven't actually tested it myself. 😄 This feature was added as part of #5060 in Dataverse 4.10.

**Comment by jggautier** [comment]
Yes, after the installation branding is changed, when new datasets are published, or new versions of existing datasets are published, the metadata that DataCite is sent will include the new installation name in DataCite's "producer" element.

Has your installation already published datasets? (I'm not sure how the metadata that DataCite has could be updated - other than by publishing a new version for each dataset.)

**Comment by djbrooke** [comment]
Hi @MohanaPriyaNarapareddy and all - I'm going to close this out as it seems from above conversation that there's a solution and no code changes are needed. Thanks for the good discussion and please repopen this if I'm wrong. :)

@MohanaPriyaNarapareddy - if you have a Dataverse installation that's not on the map at dataverse.org and you'd like it added, please feel free to reach out to us at support@dataverse.org!
