### ISSUE TITLE
Create Dataverse with linked dataset

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#5851]
For issue #5493, we need the functionality to create a dataverse and add a linked dataset at the same time. We can accomplish this by adding a parameter to the URL (e.g. linkedId=XXXX) and having the backing bean call both commands. 

Additionally it has been discussed prepopulating the Dataverse Category with "Researcher"  AND preselecting an identifier.

Open question: do we want to do these just for this case or for all create dataverse cases (can be different answer for each).
- if just this case, we can accomplish with another parameter, e.g. "category=Researcher"

**Comment by djbrooke** [comment]
Closed in favor of #5874.
