### ISSUE TITLE
can't Create a dataverse using API

### ISSUE THREAD

**Issue by moumenuisawe** [IQSS/dataverse#5865]
hello there. 
I faced some issue when I was trying to use The native API for testing supported by (demo.dataverse.org). 

> https://demo.dataverse.org/api/dataverses/$id?key=$apiKey

when I tried to test that API using this site  [Api tester](https://apitester.com) this error was occurred.

> Response Headers
`HTTP/1.1 400 Bad Request
Date: Tue, 21 May 2019 10:40:06 GMT
Content-Type: application/json
Content-Length: 153
Connection: close`
>Response Body
`{"status":"ERROR","message":"Error parsing Json: Invalid token=EOF at (line no=1, column no=0, offset=-1). Expected tokens are: [CURLYOPEN, SQUAREOPEN]"}
`

actually, I changed the API key and used the created one in my API token " in the [Demo Dataverse](https://demo.dataverse.org)" "

The question is what the $id value? and is there is any problem with my request?

**Comment by pdurbin** [comment]
@moumenuisawe hi! According to #5198 the sample JSON file doesn't work. I haven't verified if this is true or not but let me at least point to you the script that creates the root dataverse, which is definitely working:

https://github.com/IQSS/dataverse/blob/v4.14/scripts/api/setup-all.sh#L74

The input is the `dv-root.json` file here:

https://github.com/IQSS/dataverse/blob/v4.14/scripts/api/data/dv-root.json

```
{
    "alias": "root",
    "name": "Root",
    "permissionRoot": false,
    "facetRoot": true,
    "description": "The root dataverse.",
    "dataverseContacts": [
        {
            "contactEmail": "root@mailinator.com"
        }
    ],
    "dataverseSubjects": ["ALL"]
}
```

**Comment by pdurbin** [comment]
@moumenuisawe please take a look at pull request #5870 and see if that helps ("files changed" if you're unfamiliar with pull requests).

**Comment by pdurbin** [comment]
@moumenuisawe I brought up this issue in standup this morning and again I believe that pull request #5870 is a fix for it. We decided to close this issue as a duplicate in favor of #5198 (currently in QA) so please try again and comment there if you are still having trouble.

Also, I see you wrote at https://github.com/samihabakri/D2S-Dataverse/issues/18#issuecomment-494601089 that you think there's a problem with the API. I don't believe that's right. I believe the API is poorly documented, which is what the pull request above is about.
