### ISSUE TITLE
unable to get past dataverseAdmin password reset page on first log in

### ISSUE THREAD

**Issue by tcpan** [IQSS/dataverse#5868]
I am trying to create a docker container in the spirit of conf/docker-aio, but without the integration testing scripts and test data.   I have created a dockerfile that incorporate the steps from the installation instruction for dataverse version 4.14, and a corresponding entrypoint.bash file.

The docker image is built successfully, and once started the webapp loads as well.  I can access the initial log in page.  On log in, I am brought to the password reset page.  However, clicking on reset/set password button does not do anything.  I get the spinning circle only.  There are no additional messages in the server.log file for dataverse, nor the pg_log file for postscript. 

The dockerfile follows directly the installation instructions, including the creation of user accounts for glassfish, solr, and counter for the respective software.  postgres user appears to be automatically created during yum install.   This is obviously different than how conf/docker-aio is configured, where solr and glassfish run as root.  docker-aio also does explicitly create the postgres user dvnapp with superuser permissions.  I added this to my dockerfile, and also tested with modifying the user permission directly in postgres, to no effect.

The default.config file used by the install script has my gmail email address and smtp server address, as well as the datacite username, password, and baseurl, but I am not sure they are being used based on the install log output.

I am not sure what I am missing.  If someone can take a look at my dockerfile and corresponding entrypoint.bash file, I would appreciate it. 

Thank you.

[tcia-docker.zip](https://github.com/IQSS/dataverse/files/3203715/tcia-docker.zip)

**Comment by djbrooke** [comment]
Hey @tcpan - can you provide a few more details? Feel free to reply in a comment or edit the original summary above. Thanks!

**Comment by tcpan** [comment]
I pressed enter before typing my comments.  Sorry about that.  Please see the revised initial comment.

**Comment by tcpan** [comment]
I should mention that I tried following the conf/docker-aio "detailed" instructions.  To avoid going through the integration testing process, I did steps 1 and 2, and then called the install script from step 3 to deploy the war, and skipped step 4.  The result was that the webapp does not load.   This is another motivation for me to try to make my own dockerfile following the standard installation instructions.

**Comment by poikilotherm** [comment]
Hey @tcpan,
let me mention https://github.com/IQSS/dataverse-kubernetes here...

You could try to use the container images without using Kubernetes by adding the env vars and secret mounts from Docker. The scripts should be reusable anyway, although you might workaround not using Kubernetes there, too.

Feel free to open an issue in case of questions or to report your findings :-) Happy to add docs on usage without K8s, too.

**Comment by pameyer** [comment]
The "spinning circle only" part reminds me of #5659; where issues with connecting to the email server resulted in timing problems; so this may be something investigating after the usual suspects (postgres/glassfish connection, etc).  With docker-aio on develop (bd336b1912ae24d361ab6c17331e865f9bf0883d), the dataverseAdmin password reset appears to be working with out of the box default.config.

Almost certainly unrelated to your original problem, but the `HEALTHCHECK` entry in your docker file will likely not work without other changes to `domain.xml` (it'll always show unhealthy, and may be killed/restarted depending on how you're running).

I'd also recommend taking a look at https://github.com/IQSS/dataverse-kubernetes - if you're going to the trouble of using separate user accounts within a single container, it may make more sense to split things into separate containers.

**Comment by tcpan** [comment]
Thanks @poikilotherm and @pameyer for your suggestions.  Based on @pameyer's comment about #5659, I removed the AdminEmail from my custom default.config file and reverted SMTP server to the default Harvard one, and was able to get past this problem.  Please feel free to close this issue.

While this would have been a good opportunity to learn kubernetes, I'll have to save that for another time when I am more available :).  Thank you all very much for your help!

For reference and your enjoyment, my final dockerfile is attached.  The entrypoint.bash is now generated during docker build through the dockerfile, as is the default.config, so this dockerfile is now standalone. 

[dockerfile4.14.zip](https://github.com/IQSS/dataverse/files/3208759/dockerfile4.14.zip)

**Comment by pdurbin** [comment]
@tcpan thanks for the update. If indeed your problems were related to email, the following issues might be of interest:

- Failure to connect to mail server causes a timeout, eventual Glassfish crash #5707 
- No provider for smtp #5723
