### ISSUE TITLE
Dataset Import fails with "Command [DatasetCreate dataset:3] failed: null"

### ISSUE THREAD

**Issue by tcpan** [IQSS/dataverse#5869]
We have been using the fix from #5667 with dataverse 4.9.4, in containers constructed via code in dataverse-docker respository.  This has worked for us until we needed a newer version of dataverse.  I changed the script to use dataverse 4.10.1 (the last version that still used both solr 7.3.0 and postgres 9.3), and received the error "Command [DatasetCreate dataset:3] failed: null".

An earlier attempt with dataverse 4.14 with solr 7.3.0 and postgre 9.3 failed with the same errors, and my debugging is mostly with 4.14.   I switched back to 4.10.1 to check if the issue is with solr and postgres versions and it appears not.

The log from the 4.14 attempt (no longer available) appears to show importDataCommand -> AbstractCreateDatasetCommand -> ctx.index().indexDataset() -> EJB31_Generated_IndexServiceBean.indexDataset() causing a transaction rollback.   Also, DataRetrieverAPI.java encounters a nullpointer error, failing at retrieveMyDataAsJsonString().    Comparing some of the relevant files between 4.9.4 and 4.14 show that 
Datasets.java differ significantly while Dataverses.java, ImportDatasetCommand.java, AbstractCreateDatasetCommand.java, and DataRetrieverAPI.java showed little to no code change.

Help would be much appreciated.

Incidentally, an instance of the 4.9.4 container spontaneously developed a problem where I received "User @dataverseAdmin is not permitted to perform the requested action" when performing import, while another identically configured instance was fine.   I am not sure if this is related or if it's even a real bug, hence I have not created an issue about it.  But I thought I mention it here in case it's relevant.

**Comment by pdurbin** [comment]
@tcpan thanks for opening this issue. Are you saying you're trying to use Dataverse 4.10.1 specifically? I was going to suggest that you create a duplicate endpoint without the colon (like we talked about in the issue you mentioned) in a pull request but that won't help you if you're trying to stay on a specific older version of Dataverse.

**Comment by tcpan** [comment]
Hi, @pdurin, thanks for responding.  I'd prefer version 4.14 but I'd settle for any version newer than 4.10 as you suggested in the "root" publisher issue #5841 to get the datacite metadata update capability.   The choice of 4.10.1 is really because I don't want to modify too much of the dataverse-docker code base to support solr 7.3.1 as required by 4.11 onward and postgres 9.6 for version 4.14. 

Re. the endpoints:  I used "import" (without colon) in the version 4.14 attempt, and used ":import" in the version 4.10.1 attempt.    Both resulted in the same error message, which makes sense as the error appear to occur during dataset creation.

**Comment by pdurbin** [comment]
@tcpan ok as @poikilotherm suggests at https://github.com/IQSS/dataverse/issues/5868#issuecomment-494527718 I think you should consider using his Dockerfiles from the dataverse-kubernetes repo. He's doing an excellent job of keeping them up to date.

**Comment by tcpan** [comment]
Hi, @pdurbin, my ultimate goal of getting a working 4.14 docker container is now achieved based on the comment of @pameyer in #5868.   I am okay not pursuing the resolution of this issue further.

Having said that, I did find a typo in my domain.xml configuration - I accidentally used http instead of https with mds.datacite.org for doi.baseurlstring.   I do not know if this is the cause and did not investigate further using my 4.14 working instance.  I am including it here in case it is relevant.

**Comment by pdurbin** [comment]
Hmm, yeah I don't know that's the cause either but thanks for circling back. Please feel free to close both issues if you're all set. You an always open fresh ones in the future. 😄
