### ISSUE TITLE
Flyway: disable DDL generation from EclipseLink

### ISSUE THREAD

**Issue by poikilotherm** [IQSS/dataverse#5871]
This is a successor issue to #5862.
This kind of relates to #5854.
This should be read by @pdurbin, @MrK191, @donsizemore and @djbrooke at least.

Since the introduction of Flyway in #5344, only minor modifications happened to the schema.
In #5822 a new column has been added and since it had been merged, the develop branch no longer deploys on new "installations".

Some background on the cause:
EclipseLink ORM generates a DDL script from all models on startup and ([due to this setting in persistance.xml](https://github.com/IQSS/dataverse/blob/aa59755ded639af2f33a22d52f6b7cfca33a7db4/src/main/resources/META-INF/persistence.xml#L14)) creates new tables when not existing. It does not update existing tables. This job is left to Flyway, which is one reason why it had been introduced.

Flyway throws exceptions due to a conflict, trying to change something already present. In #5822, a [new column should be added](https://github.com/lubitchv/dataverse/blob/747bc518b8f2af945bfe74beb2feab2691300a7f/src/main/resources/db/migration/V4.14.0.1__5822-export-var-meta.sql), but on new deployments, EclipseLink already generated the mapping. Thus the deployment fails.

How to get along with this:
Obviously, one could just use workarounds as #5866 does. It would be better to have a discussion and decision on how to deal with database model, mappings, EclipseLink and Flyway in the future, write down a process and adapt.

IMHO there is only one "good" solution, but this is only a proposal and needs to be discussed and/or modified:
1. Do not let EclipseLink generate DDL anymore.
2. Get a base model mapping in the codebase as a proper baseline. This, ideally, should be the exact mapping as it has been when Flyway had been merged.
3. Continue to write migrations in SQL or Java with Flyway, as already done. Document this part of the process if not already done sufficiently.
4. To ensure 100% compatibility between tables and models, the mapping - now maintained with Flyway as migration files - needs to be validated regularly. This is an ideal task for CI on jenkins.dataverse.org.

It might be an option to switch from EclipseLink JPA to Hibernate JPA as it offers easier to use validation mechanisms than EclipseLink does.

**Comment by djbrooke** [comment]
Thanks @poikilotherm for the tag, I'll tag @landreev and @scolapasta as well.

**Comment by MrK191** [comment]
@poikilotherm I agree, in our version we just disabled eclipse-link ddl generation. In terms of hibernate you are going to have some troubles, since some annotation syntax changed and you gonna get LazyLoadingException on the face since for whatever reason lazy loading was disabled in this app.

**Comment by poikilotherm** [comment]
Thanks @MrK191 for pointing out the monsters lurking in the shadows. :smile: 
So you think it might be worse the price doing the switch?
Hibernate seems to be more widely used anyway, standard for Spring etc...

**Comment by pdurbin** [comment]
@poikilotherm @MrK191 if there's a feature missing from the JPA spec can one of you please open an issue at https://github.com/eclipse-ee4j/jpa-api ? (I have one open issue over there. 😄 )

**Comment by MrK191** [comment]
@pdurbin  Nothing is missing, it's just that the glassfish 4 uses eclipse-link version that has this bug.
@poikilotherm Nah I think it's good direction almost no-one heard of eclipse-link when I talk about JPA now :P, so in long-term it's good decision.

**Comment by pdurbin** [comment]
@MrK191 ok, you're saying there's a bug in the version of eclipse-link in the somewhat ancient version of Glassfish we're stuck on. That's bad news but I'm glad to hear that there's nothing missing from the JPA standard and that we don't have to move to one particular JPA implementation (Hibernate) to resolve this issue. I like standards. 😄

**Comment by pdurbin** [comment]
@poikilotherm and I had a short chat about this issue just now: http://irclog.iq.harvard.edu/dataverse/2019-10-22#i_110035

My take away is that overall, adding Flyway to the mix has been a step forward but there are further improvements we can make so that upgrading Dataverse is easier.

**Comment by pdurbin** [comment]
Related:

- #4920

**Comment by pdurbin** [comment]
Related:

- #10160

**Comment by poikilotherm** [comment]
Recently I gave creating a new base migration a shot. Turns out: works perfectly. So we make of this anytime we want to get rid of the DDL generation. @pdurbin thinks this might help with #9686 - it's not so easy to move the columns around with DDL generation getting in the way.

**Comment by pdurbin** [comment]
@poikilotherm fantastic! Can you please push a branch and maybe even make a pull request so we can see it?

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.

**Comment by pdurbin** [comment]
Related:

- #11074

**Comment by pdurbin** [comment]
As discussed during yesterday's tech hours meeting, I reopened this issue and applied a size of 80, as suggested by @poikilotherm (thanks).

This issue represents technical debt we should pay down some day. When we introduced Flyway into our app over 6 years ago in #5349 we didn't understand the importance of having a proper baseline migration. Instead, our baseline is empty and we continue to rely on EclipseLink's "generate tables" functionality.

We need to:

- Read up on rebaselining in Flyway.
- Make a new baseline:
    1. Setup an empty database.
    2. Have EclipseLink generate the tables by deploying Dataverse, but don't run the setup scripts (so it mostly stays empty).
    3. Use `pg_dump -s` to dump the schema only into a file, usable as a baseline.
- Turn off EclipseLink's "generate tables" in `persistence.xml`.
- Figure out how to make Flyway pickup the new baseline, at least for new installations. (This may be a limitation of the community version - needs testing!) [See docs](https://documentation.red-gate.com/fd/baseline-migrations-273973336.html).
- Figure out ways to (semi)automatically generate any future schema changes that are necessary not only for changes to tables, but also new tables for newly added entity classes. Some options for this are:
    - Do it all manually
    - Use [JPA Buddy](https://jpa-buddy.com/)
    - Create a Maven job to run two database and use [LiquiBase Maven Plugin "diff" goal](https://deepwiki.com/liquibase/liquibase/3.2-maven-plugin) to generate scripts from the difference between them. (One is a temporarily EclipseLink-generated DB with the latest code changes, the other is a baseline + any existing migrations applied. The difference can be expressed as SQL migrations scripts)
    - Unfortunately, [Flyway diff](https://documentation.red-gate.com/flyway/reference/commands/diff) is enterprise only.
    - ...?
    - AI?
- Add Testcontainers based integration tests that applies migrations to a test database, ideally including test data.
- Docs, etc.

These days we have two other apps that also use Flyway, and they use it properly:

- https://github.com/IQSS/dataverse-hub
- https://github.com/IQSS/dataverse-marketplace

We can study them and experiment there if we like.

As for the "why" or "why is this important", here are a few thoughts:

- Users suffer from confusing warnings on every deployment. See #11074.
- We are currently unable to move some columns from one table to another. See #9686.
- Migration scripts are hard to test. See #12002.
