### ISSUE TITLE
Dataset with files in differents S3 Buckets ?

### ISSUE THREAD

**Issue by Thanh-Thanh** [IQSS/dataverse#5873]
Hello Dataverse team,

Our use case is as the following:

Our dataverse uses a bucket S3 called bucketDataverse, for example, to store files.
The owner of a dataset has his file(s) already stored in another S3 storage, called anotherBucketS3 and he does not want to re-up their files into our bucketDataverse.

In this case, what do you advice us to do in order to have his files referenced in de DOI? 
We think of using the alternativeUrl metadata to reference to the files in anotherBucketS3.

However, with this workaround, we can not see in dataverse all the files' related informations, its versions, etc. and we can not, later on, make the changes from dataverse.

We wonder whether there's the same need out there and whether you have in mind (or better in your roadmap) some evolution to response to this kind of usage ?

Thanks in advanced,

Thanh Thanh

**Comment by djbrooke** [comment]
Hey @Thanh-Thanh, I'd suggest looking into what the Odum team (@jonc1438 @donsizemore and others) is working on regarding Trusted Remote Storage Agents (TRSAs) to support your use case. There's some good info in a few spots:

https://tdl-ir.tdl.org/handle/2249.1/156346
https://www.youtube.com/watch?v=MKsrsV6KWsQ&feature=youtu.be
http://cyberimpact.us/architecture-overview/
