### ISSUE TITLE
Push researchers towards Dataverse Creation and Dataset Linking from Journal Acceptance Notifications

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#5874]
This is an attempt to combine what's in #5493, #5851, and #5852 into a single issue. I think I pushed to have that broken down too small and it's resulted in some uncertainty about the flow. There's some background discussion in the other issues. Generally, the steps for this will be:

- Update the text of the journal acceptance notification to mention the benefits of having a dataverse
- In the text, add a link for "Click here to add this dataset to your dataverse." This link will lead to the dataset page with the existing link popup presented and the person will go through the regular linking flow. 
- In the text, add a link for "Click here to create a dataverse and link this dataset to it." This link will go to a dataverse create page with as many fields default-populated as possible, and when the dataverse is created the dataset is linked to automatically.

There are some details here to be figured out:

- what logic do we use to decide what text and link to display?
- how do we figure out if someone has a dataverse or not?
- what fields are OK to pre-populate?
- what if someone has more than one dataverse?

**Comment by TaniaSchlatter** [comment]
Reviewed proposed flow document with the team, and revised to incorporate feedback. The resulting flow feels a little convoluted, so I am pulling this back to design.

**Comment by TaniaSchlatter** [comment]
Solving linking is related to users being able to select or create a Dataverse they can add to. See "Typeahead widget on Link Dataset popup is slow and doesn't display all options as expected" #6672 and "Optimize permission lookups for a user" #6467 for related issues.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
