### ISSUE TITLE
New, second Dataverse client library for Python (pyDataverse)

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#5879]
Don't look now but over at https://twitter.com/stefankasberger/status/1130752131881947142 @skasberger announced the availability of pyDataverse:

<img width="1109" alt="Screen Shot 2019-05-23 at 7 55 48 AM" src="https://user-images.githubusercontent.com/21006/58250850-4de0ef80-7d30-11e9-8c54-bad10f28b941.png">

Why is this exciting:

- For the first time, one can simply `pip install` a Dataverse library.
- pyDataverse is under active development where as dataverse-client-python is, well, stable. 😄 
- pyDataverse has excellent documentation: https://pydataverse.readthedocs.io/en/latest/
- based on discussions during a recent community call, @skasberger @4tikhonov and others have BIG PLANS for pyDataverse. Please see the notes at https://groups.google.com/d/msg/dataverse-community/op753PRmoUY/mm7GAGoaAgAJ and join the discussion there or in the issue tracker at https://github.com/AUSSDA/pyDataverse

In pull request #5878 we are adding pyDataverse to the "client libraries" page of the API Guide.

**Comment by skasberger** [comment]
btw: I will send out announcement mails in the next day.
