### ISSUE TITLE
Clean up ambiguous references to "homepage" in guides

### ISSUE THREAD

**Issue by dlmurphy** [IQSS/dataverse#5884]
We currently use the term "homepage" or "home page" in our guides to refer to both the default root dataverse search listings (e.g. the old Harvard Dataverse homepage) and to custom homepages. This introduces confusion when we're, e.g., guiding users to specific pages in the application.

We should fix this ambiguity:

- [x] Make sure any references to custom homepages use the term "custom homepage", and make sure sections that talk about custom homepages are sufficiently generalized that they can apply to all installations with custom homepages.

- [x] Decide on a term to use when talking about the default homepage ("root dataverse page?" "default search listings?" "Browse page?"). It needs to be both unambiguous and immediately clear to non-expert users.

- [x] Update the guides to make sure we consistently use the term we decide on for the default homepage.

- [x] Update the guides to make sure we consistently use the word "homepage" and not "home page".

- [x] Disambiguate bundle entries that reference the homepage.

**Comment by dlmurphy** [comment]
Moved to this sprint on Danny's advice.

**Comment by pdurbin** [comment]
Great idea. Related to this is a spreadsheet called "Dataverse Glossary" that we created for #4274: https://docs.google.com/spreadsheets/d/1xje8FADNjCKNBNExXjKQXrmRgc-WQxEv7jKJrDOuuLA/edit?usp=sharing

We could add an entry for whatever end up calling the thing we're talking about. 😄

**Comment by dlmurphy** [comment]
I just noticed three uses of the term "homepage" in bundle.properties that I recommend we fix as part of this issue as well. Very minor increase in scope.

dataverse.link.no.linkable=To be able to link a dataverse or dataset, you need to have your own dataverse. Click on the Add Data button on the **homepage** to get started.

dataverse.displayFeatured=Display the dataverses selected below on the **homepage** for this dataverse.

dataverse.selectToFeature=Select dataverses to feature on the **homepage** of this dataverse.

**Comment by dlmurphy** [comment]
I'm currently leaning toward the phrase "root dataverse" or "root dataverse page" in place of "homepage". We actually make this connection already in the Dataverse Management section of the User Guide:

> You can decide either to use the theme from the dataverse containing your dataverse (**even up to the root dataverse, AKA the homepage**), or upload your own image file.

**Comment by pdurbin** [comment]
@dlmurphy I just approved your pull request but can you please leave a comment here with instructions on how to make the strings below appear in the UI? What to click I mean. I'm happy to spin up a branch for you if you'd like. Thanks!

![Screen Shot 2019-05-31 at 1 01 01 PM](https://user-images.githubusercontent.com/21006/58721997-4eb6f880-83a4-11e9-98c0-ea2bfc18ac6e.png)

**Comment by dlmurphy** [comment]
Sure.

dataverse.selectToFeature: On a dataverse page, click Edit -> Featured Dataverses
dataverse.displayFeatured: Not sure, but I edited this one to be consistent with the other.

dataverse.link.no.linkable: Presumably appears when you try to link a dataverse to another dataverse but can't because you don't have the correct permissions on at least one dataverse. Because this feature is superuser only, and superusers have the correct permissions on ALL dataverses, to see this situation in action you'd have to spin up a new installation with only one dataverse in it. For the purposes of this issue, the context provided in the bundle was enough to edit this text to be more clear, regardless of how often it actually appears.
