### ISSUE TITLE
tests: hard-coded file paths break tests for multiple users running `mvn package`

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#5885]
If more than one user attempts to build Dataverse on the same host, two hard-coded file paths break two tests for the second user.

In SiteMapUtilTest.java:  
`File sitemapFile = new File("/tmp/sitemap.xml")`
yields
`WARNING: Unable to update sitemap! The staged file from a previous run already existed. Delete /tmp/sitemap.xml.staged and try again.
Exception caught checking that XML is well formed: java.io.FileNotFoundException: /tmp/sitemap.xml (No such file or directory)
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.017 s <<< FAILURE! - in SiteMapUtilTest`

Similarly, in SchemaDotOrgExporterTest.java:
`try (PrintWriter printWriter = new PrintWriter("/tmp/dvjsonld.json"))`
breaks the SchemaDotOrgExporter test with a permission denied.

These lines coupled with my manually running the api-test-suite in docker-aio have caused the rain clouds on jenkins.dataverse.org. Coincidentally, I was running the test suite manually so that I wouldn't ruin Jenkins' weather report by not having the kinks worked out... sorry!

**Comment by pdurbin** [comment]
@donsizemore thanks for opening this issue and for running that new Jenkins server for the Dataverse community! I mentioned it several times in the "thoughts on automated testing" email I send out this week: https://groups.google.com/d/msg/dataverse-dev/ISot5k4VjZQ/t-hzPk8tAwAJ

**Comment by pdurbin** [comment]
> Similarly, in SchemaDotOrgExporterTest.java:
> `try (PrintWriter printWriter = new PrintWriter("/tmp/dvjsonld.json"))`
> breaks the SchemaDotOrgExporter test with a permission denied.

I'm seeing this problem over at https://github.com/IQSS/dataverse-jenkins/issues/8#issuecomment-499847911

**Comment by poikilotherm** [comment]
You could build in a multistage build. Example at https://github.com/IQSS/dataverse-kubernetes/blob/4fa05c1d4e2a3b69478d42481858811e0a479c15/docker/dataverse-k8s/dev-payara/Dockerfile#L9

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
