### ISSUE TITLE
Assist users who are linking but don't have a dataverse

### ISSUE THREAD

**Issue by TaniaSchlatter** [IQSS/dataverse#5890]
Any logged in user can link to any published dataset if they have a dataverse they can link to. However, users who don't have a dataverse they can link to end up in at a dead end after clicking the "Link" button:
<img width="959" alt="Screen Shot 2019-05-29 at 1 12 51 PM" src="https://user-images.githubusercontent.com/15386424/58576978-7d519980-8213-11e9-992e-db852053c4f4.png">

How might we help these users complete linking the dataset?

1. invite these users to create a dataverse
2. let users know that they might need to request permission from a dataverse administrator to link a dataset to a dataverse
3. other possibilities?

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
