### ISSUE TITLE
StartupFlywayMigrator is not a valid EJB

### ISSUE THREAD

**Issue by smillidge** [IQSS/dataverse#5893]
A valid EJB must have a public no-args constructor as StartupFlywayMigrator is not a public class it does not have a public constructor and war deployment fails on Payara 5.

**Comment by pdurbin** [comment]
@smillidge thanks for making pull request #5894! I just approved it and moved it to QA.

Thanks also for your recent comments at https://github.com/IQSS/dataverse/issues/2628#issuecomment-496858474 !

**Comment by pdurbin** [comment]
@smillidge I keep thinking about how at https://github.com/IQSS/dataverse/issues/2628#issuecomment-497483232 you said you had to patch a Flyway script for your deployment to work. I'm going to guess this may have been related to 60cd169. We only recently started using Flyway and we're still getting used to it.

As I mentioned at https://github.com/IQSS/dataverse/issues/4172#issuecomment-497707104 I was able to deploy a war file built from your branch (pull request #5894) to Payara 5 without touching any Flyway scripts. I'm wondering if I should be concerned that you had to patch a Flyway script.

I don't think I really have a question. I think I just wanted to put this brain dump out there.

**Comment by smillidge** [comment]
The flyway script was trying to create an index that already exists (if I remember correctly) it could just have been due to the current state of my database. I sort of hack installed Dataverse rather than using your install scripts so it could be related to that.

**Comment by pdurbin** [comment]
@smillidge ok, thanks. It's possible to get in a weird state if you apply our "reference data" SQL script before deploying the war file but this doesn't happen normally. Thanks again for this pull request! Stay tuned over in #4172 I guess. :smile:

**Comment by smillidge** [comment]
I think Eclipselink is building the correct database schema then Flyway is trying to "upgrade" it by adding an index that already exists. It was a simple matter of patching the flyway script to add `IF NOT EXISTS` to the create statement.

**Comment by poikilotherm** [comment]
This is also discussed in #5871. EclipseLink should not create the tables anymore...
