### ISSUE TITLE
Add tests for Excel/XSLX ingest

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#5896]
Model after the existing CSV test. 

(this should be the first step, before re-visiting and improving the XSLX ingest plugin)

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
