### ISSUE TITLE
Allow terms metadata to be changed with Native API

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#5899]
Some users want to be able to change Terms of Use metadata for multiple datasets in bulk (without need to open and edit each dataset's metadata). Users can use the Native API to add or edit metadata in the metadata fields that are in Dataverse's metadata blocks, but as of 4.19 the Native API doesn't let users do the same for Terms of Use and Terms of Access fields (in the Terms tab). In fact, if you use [the "Update Metadata"](http://guides.dataverse.org/en/latest/api/native-api.html#update-metadata-for-a-dataset) endpoint to create or edit a dataset draft, which will overwrite any existing dataset metadata, all values in the Terms of Use and Terms of Access fields are also removed.

It would also be helpful to document in some brief way which fields can and can't be edited using the Native API.

(This is following discussion from the related issue at https://github.com/IQSS/dataverse/issues/2585)

**Comment by pdurbin** [comment]
@jggautier thanks for creating this issue! 🎉 

> gives the impression that using the Native API to change Terms of Use has been possible since 4.8.6

I wish but #4431 is about being able to see the API Terms of Use from https://dataverse.harvard.edu/api/info/apiTermsOfUse for example. Here's the setting: http://guides.dataverse.org/en/4.14/installation/config.html#apitermsofuse

**Comment by jggautier** [comment]
Adding the workaround that Phil suggested in #2585:

> Also, as we discussed, a workaround for now, in the absence of being able to update terms via the native API might be:
> 
> - serialize your dataset as native dataverse JSON format.
> - change the terms of use via SWORD
> - reupload your metadata from the JSON backup you made
> 
> The reason for backing up and re-applying the native JSON format is that with SWORD your metadata will be overwritten with very few (Dublin Core) fields. At least, that's how I believe it works. It's been a while since I've tested this.

A Dataverse user is trying this workaround now and working through issues (https://help.hmdc.harvard.edu/Ticket/Display.html?id=276348)

**Comment by djbrooke** [comment]
- We want the granular option to edit terms, specifically "Terms of Use" and "Restricted Files + Terms of Access" (see screenshot)
- Add docs for what works and what does not work
- We'd want the workflow to be the same as what's in the UI, in that the option to provide terms is only available to those users deselecting CC0 and creating a new dataset version
- Do we want to just accept terms JSON that people send and change it off CC0 (do we do it silently or do we provide info)? - we want to provide info per @djbrooke 

![Screen Shot 2020-02-05 at 3 13 20 PM](https://user-images.githubusercontent.com/7773392/73879234-18325700-482a-11ea-96ca-a6a4085f5f43.png)

-

**Comment by pdurbin** [comment]
Yesterday at standup I said I'd push what I have (which isn't much) to a branch so here it is: https://github.com/pdurbin/dataverse/commit/60ff805

One thing I re-discovered along that way is that we already have an API to enable or disable the "Request Access" button: http://guides.dataverse.org/en/4.19/api/dataaccess.html#allow-access-requests

Here's a dump of the doc I stubbed out, which gives an idea of where my head's at:

```
Changing Terms and Licenses
~~~~~~~~~~~~~~~~~~~~~~~~~~~

curl -X GET /terms

curl -X POST /terms

{
  "specialPermissions": "so special",
  "depositorRequirements": "dance",
  "requestAccess": true,
  "license": "CC-BY"
}

(This would be an error since CC-BY is not supported.)

curl -X DELETE /terms/disclaimer
```

**Comment by jggautier** [comment]
Interesting!

> (This would be an error since CC-BY is not supported.)

Just posting for consideration that the SWORD API guide describes similar logic, in [the section with the crosswalk](http://guides.dataverse.org/en/4.19/api/sword.html#dublin-core-terms-dc-terms-qualified-mapping-dataverse-db-element-crosswalk), where if in the given xml file has dcterms:license set to "CC0," the CC0 waiver is retained. Otherwise, "enter “NONE” and fill in the dcterms:rights field".

Could this functionality borrow that logic? E.g. users who don't want to use CC0 for license should enter NONE, and for termsOfUse enter CC-BY (and even better, include the URL https://creativecommons.org/licenses/by/2.0)?

**Comment by qqmyers** [comment]
@pdurbin -just wanted to mention https://github.com/IQSS/dataverse/issues/6497 work. It would let you set any metadata on a dataset (without having to read the existing metadata, update the one field, and send it back), but it doesn't yet cover bulk operations. It could though - wondering if adding bulk options to this, (or at least thinking that if you write bulk operation code, it could be reused for this) would help. I do have some working code for this - got busy on other things and didn't make a PR yet but I could post what I have if that would help.

**Comment by poikilotherm** [comment]
There's a new kid on the block with related goals #7440

**Comment by pdurbin** [comment]
Heads up that pull request #7414 might close this issue.
