### ISSUE TITLE
Documentation Issue on "Solr Init Script"

### ISSUE THREAD

**Issue by dyaw-Drexel** [IQSS/dataverse#5905]
http://guides.dataverse.org/en/latest/installation/prerequisites.html

In the "Solor Init Script" step:

"service solr start" should read "service solr restart"

**Comment by pdurbin** [comment]
@dyaw-Drexel hi! As discussed in chat I'm happy to help you make a pull request.

To get started please click https://github.com/IQSS/dataverse/blob/develop/doc/sphinx-guides/source/installation/prerequisites.rst and click the "edit" pencil:

![Screen Shot 2019-06-03 at 3 44 37 PM](https://user-images.githubusercontent.com/21006/58829748-9a70d880-8616-11e9-9e7b-2f2080240b58.png)

**Comment by dyaw-Drexel** [comment]
> 
> 
> @dyaw-Drexel hi! As discussed in chat I'm happy to help you make a pull request.
> 
> To get started please click https://github.com/IQSS/dataverse/blob/develop/doc/sphinx-guides/source/installation/prerequisites.rst and click the "edit" pencil:
> 
> ![Screen Shot 2019-06-03 at 3 44 37 PM](https://user-images.githubusercontent.com/21006/58829748-9a70d880-8616-11e9-9e7b-2f2080240b58.png)

Great, just put in the pull request!

**Comment by pdurbin** [comment]
@dyaw-Drexel I see your branch. Now you need to click "Create Pull Request" at https://github.com/IQSS/dataverse/compare/develop...dyaw-Drexel:patch-1

**Comment by dyaw-Drexel** [comment]
> 
> 
> @dyaw-Drexel I see your branch. Now you need to click "Create Pull Request" at [develop...dyaw-Drexel:patch-1](https://github.com/IQSS/dataverse/compare/develop...dyaw-Drexel:patch-1)

@pdurbin No problem, just created the request

**Comment by pdurbin** [comment]
As I mentioned at standup, the "why" is captured in an IRC conversation. The pitfall according to @poikilotherm at http://irclog.iq.harvard.edu/dataverse/2019-06-03#i_95879 is this:

"The guide lets you start Solr to create the core"

"And afterwards, you install the init script"

"And simply call start with systemd"

"That will obviously crash"

"So this is a docs bug :-D"

@donsizemore seemed to agree with this. To be honest, I wasn't following the conversation very closely but if both of these Dataverse experts are happy with the pull request, so am I!

**Comment by pdurbin** [comment]
Pull request #5906 was merged so I'm closing this. Thanks, @dyaw-Drexel !

**Comment by poikilotherm** [comment]
@pdurbin, please don't call me a troublemaker, but PR #5906 does not solve the underlying problem. You now even have a released docs version 4.15 with a new bug, as the docs now tell people to use systemctl on SysV init style systems.

**Comment by pdurbin** [comment]
@poikilotherm d'oh! Can you please create a new issue (or pull request if that's easier)?

**Comment by poikilotherm** [comment]
@pdurbin, I just created #5951 for you guys. This is the patch I had in a pull request for @dyaw-Drexel, which had not been merged.

My 2 cents: I would love to see an updated 4.15 or a 4.15.1, as wrong published docs are bad   :hear_no_evil: :speak_no_evil: :see_no_evil:
