### ISSUE TITLE
Add shapefile (zip format) failed due to can not remove the tempo unzipped directory

### ISSUE THREAD

**Issue by Thanh-Thanh** [IQSS/dataverse#5909]
Hello everybody,

We are migrating to 4.10.1, in testing phrase.

We're blocking by this scenario :
+ Upload a zipped shapefile
+ On the GUI, we see the upload progress; but when it comes to the end, it just disappear, no file is added
+ In the server log, we have this kind of message : 
_Failed to process and/or save the file test-worldmap_1.zip; Unable to delete directory [pathToSaveFileFolder]/temp/shp_[date_and_time]_

Dig in the codes, it comes from FileUtil, line 920

_// Delete the temp directory used for unzipping
 FileUtils.deleteDirectory(rezipFolder);_

And I do not really know why it can not delete the folder. However, I suppose that we need not to interrupt the treatment here, on the failed delete of the tempo folder ? (other failed delete on file are catched, a warning is written in the logs)

I do not know if we can have a quick patch for this, in order to move on ? :(

Thanks in advance,

Thanh Thanh

**Comment by pdurbin** [comment]
@Thanh-Thanh my first thought is to check the permissions on the folder and make sure the Unix user that Glassfish runs as ("glassfish" or whatever) can read and write to it.

**Comment by Thanh-Thanh** [comment]
@pdurbin : Thanks for your answer. We have all the needed permissions on the folder. The proof is that this tempo folder is previously created in the codes. 

I have checked a little more to be sure, the problem comes from the fact that we use NFS to stock files :( I did not have this problem when using the machine's disk.

Anyway, we can not interrupt the process with the failed delete on a tempo folder ?!

Thanks you in advance,

Thanh Thanh

**Comment by pdurbin** [comment]
That's strange because we used to run Harvard Dataverse with files on NFS. This was before we migrated to S3 which according to https://www.iq.harvard.edu/news/dataverse-moves-cloud was winter/spring 2018, so fairly recently.

Are you saying this problem is only with zipped shape files?

Or are you saying other types of files are affected.

Shape files have some special handling in Dataverse so maybe there's a bug somewhere in that code.

**Comment by Thanh-Thanh** [comment]
This is a bug from 4.10(.1), and only for zipped shapefile in fact. (I've compared the codes of 4.10.1 with 4.8.6, in which there's no delete on tempo folder in the case of zipped shapefile)
And from what I see, you have migrated to S3 before 4.10...

**Comment by pdurbin** [comment]
@Thanh-Thanh ok, are you interesting in trying to track down the bug and creating a pull request?

It sounds like the bug affects shape files on NFS. Thanks for all the investigation you've done!

**Comment by Thanh-Thanh** [comment]
I can do the correction, however, I do not know whether I need to do it from the codes of 4.10.1 ?

**Comment by pdurbin** [comment]
@Thanh-Thanh I would much prefer for you to make a pull request against the "develop" branch so that it will be included in the next version of Dataverse (4.15 or whatever).
