### ISSUE TITLE
Change the production date

### ISSUE THREAD

**Issue by MohanaPriyaNarapareddy** [IQSS/dataverse#5911]
I imported my dataset from datacite to dataverse. Is there anyway that i could change the Publication  data from today's date to the production date?

**Comment by jggautier** [comment]
Hi @MohanaPriyaNarapareddy. This seems related to your discussion at https://github.com/IQSS/dataverse/issues/5729. So is this issue about being able to edit or hide Dataverse's publication date timestamp?

**Comment by djbrooke** [comment]
@MohanaPriyaNarapareddy and @jggautier - I'm going to close this as a duplicate of #5729.
