### ISSUE TITLE
Deleting a Published File that has been set as DS Thumbnail does not remove it as the Thumbnail

### ISSUE THREAD

**Issue by sekmiller** [IQSS/dataverse#5912]
If you set a file as the thumbnail of a dataset and publish it as version 1 and delete that file in version 2 or subsequent version, the thumbnail remains.  It seems that if the file is not part of the current released version of the dataset it should be removed as the thumbnail.

**Comment by BPeuch** [comment]
I experienced the same thing and verified it on both our local Dataverse (v 4.20) and on Demo Dataverse.
