### ISSUE TITLE
Attribute naming of bounding-box wrong

### ISSUE THREAD

**Issue by skasberger** [IQSS/dataverse#5915]
The attribute names for the bounding box are name in a wrong way.

A bounding box normally contains
bbox = left,bottom,right,top
bbox = min Longitude , min Latitude , max Longitude , max Latitude 

I have seen this issue in a [Dataverse API JSON file](https://github.com/IQSS/dataverse/blob/v4.14/scripts/api/data/dataset-create-new-all-default-fields.json). In it, the bounding box attributes are always name longitude, also south and north, which should be latitude. I have not checked how the naming works internally in Dataverse, but the guess is, that this also relates to the database naming.

Find out more about Lon/Lat [here](https://wiki.openstreetmap.org/wiki/Bounding_Box) and [here](https://en.wikipedia.org/wiki/Longitude).

**Comment by pdurbin** [comment]
@skasberger hi! According to http://guides.dataverse.org/en/4.14/user/appendix.html#metadata-references the Dataverse "geospatial" metadata block is "compliant with DDI Lite, DDI 2.5 Codebook, DataCite, and Dublin Core." I am certainly not an expert in any of this though. Usually @jggautier takes a look at metadata standard questions like this. Thanks for bringing this to our attention.

**Comment by skasberger** [comment]
just practically: to define a rectangle with four x values is tricky. for this you need two x and two y values. lon and lat are the x and y's of geography.

**Comment by jggautier** [comment]
Hi @skasberger. Thanks for bring this issue up. It seems identical to the one described in https://github.com/IQSS/dataverse/issues/5645. Is there an aspect in that issue that's missing? Could we close this issue and move more discussion to that other issue?

**Comment by skasberger** [comment]
Yes, looks like it's adressing the same cause. So moving over works for me.
