### ISSUE TITLE
disabling a guestbook breaks downloads in datasets where it was used

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#5925]
Related to #1645 - if a dataset has restricted files and used a guestbook with required fields, and the guestbook is then disabled, when you try to download the file, you don't see the guestbook and the download silently fails. It looks like the page includes a guestbookresponse, but the download popup doesn't include the guestbook form (because it's disabled) and therefore the response lacks required fields and the download fails due to a validation error. The code (FileDownloadHelper.writeGuestbookAndStartDownload) has a line to display a message if validation fails, but it doesn't appear in the display (message field not in the update= attribute for the accept button in file-download-popup-fragment.xhtml?).

I found this issue on a test system but we don't use guestbooks in production, so I'm reporting but don't plan to fix this at present.

**Comment by donsizemore** [comment]
We're seeing this on a production system running 5.3:

```
Exception writing GuestbookResponse for file: 24 : Command edu.harvard.iq.dataverse.engine.command.impl.CreateGuestbookResponseCommand@2419a6b3 failed: Exception thrown from bean: javax.ejb. EJBException: Transaction aborted
A system exception occurred during an invocation on EJB DataFileServiceBean, method: public edu.harvard.iq.dataverse.DataFile edu.harvard.iq.dataverse.DataFileServiceBean.find(java.lang.Obje
ct)
javax.ejb.TransactionRolledbackLocalException: Client's transaction aborted
at edu.harvard.iq.dataverse.__EJB31_Generated__FileDownloadServiceBean__Intf____Bean__.writeGuestbookAndStartBatchDownload(Unknown Source)
at edu.harvard.iq.dataverse.FileDownloadHelper.writeGuestbookAndStartDownload(FileDownloadHelper.java:85)
at edu.harvard.iq.dataverse.FileDownloadHelper$Proxy$_$$_WeldClientProxy.writeGuestbookAndStartDownload(Unknown Source)
```

```
A system exception occurred during an invocation on EJB FileDownloadServiceBean, method: public void edu.harvard.iq.dataverse.FileDownloadServiceBean.writeGuestbookAndStartBatchDownload(edu.harvard.iq.dataverse.GuestbookResponse)
javax.ejb.EJBTransactionRolledbackException: Client's transaction aborted
at edu.harvard.iq.dataverse.__EJB31_Generated__FileDownloadServiceBean__Intf____Bean__.writeGuestbookAndStartBatchDownload(Unknown Source)
at edu.harvard.iq.dataverse.FileDownloadHelper.writeGuestbookAndStartDownload(FileDownloadHelper.java:85)
at edu.harvard.iq.dataverse.FileDownloadHelper$Proxy$_$$_WeldClientProxy.writeGuestbookAndStartDownload(Unknown Source)
```

```
/file-download-popup-fragment.xhtml @171,59 actionListener="#{fileDownloadHelper.writeGuestbookAndStartDownload(guestbookResponse)}": javax.ejb.EJBTransactionRolledbackException: Client's transaction aborted
javax.el.ELException: /file-download-popup-fragment.xhtml @171,59 actionListener="#{fileDownloadHelper.writeGuestbookAndStartDownload(guestbookResponse)}": javax.ejb.EJBTransactionRolledbackException: Client's transaction aborted
```

**Comment by djbrooke** [comment]
Thanks @qqmyers and @donsizemore, we'll take a look at this in the sprint starting tomorrow.

**Comment by sekmiller** [comment]
When this becomes a priority again it might be worth it to look at removing a disabled guestbook from its assigned datasets as part of the disabling process. We would also want to document this so that if the guestbook is re-enabled the dataset admins would have to add it to their datasets again.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
