### ISSUE TITLE
Customization of home html pages and css 

### ISSUE THREAD

**Issue by MohanaPriyaNarapareddy** [IQSS/dataverse#5939]
Hello. I want to have my custom home page and logo by adding a few changes to the current HTML pages. Can u direct me to the location of current HTML and CSS of dataverse?

**Comment by pdurbin** [comment]
@MohanaPriyaNarapareddy hi! Do these links help?

- http://guides.dataverse.org/en/4.14/installation/config.html#custom-homepage
- http://guides.dataverse.org/en/4.14/installation/config.html#custom-navbar-logo
- http://guides.dataverse.org/en/4.14/installation/config.html#custom-stylesheet

Maybe I'm not sure what you're asking. 😄

**Comment by MohanaPriyaNarapareddy** [comment]
thanks for your reply. I also want the current styling sheets of the dataverse.

**Comment by pdurbin** [comment]
Sure, as mentioned at http://guides.dataverse.org/en/4.14/style/foundations.html the main file is structure.css and you can find the latest released version at https://github.com/IQSS/dataverse/blob/v4.14/src/main/webapp/resources/css/structure.css

**Comment by MohanaPriyaNarapareddy** [comment]
Thank you.

**Comment by djbrooke** [comment]
Thanks @pdurbin for responding and @MohanaPriyaNarapareddy for the questions. I'm going to close this one out as it looks like it's all set.

**Comment by MohanaPriyaNarapareddy** [comment]
@pdurbin i couldn't find the html and css sheets of the home page. The home page mentioned 
 here http://guides.dataverse.org/en/4.14/installation/config.html#custom-homepage seems to the different.

i am trying to create something like below.
<img width="1430" alt="Screen Shot 2019-07-03 at 11 57 52 AM" src="https://user-images.githubusercontent.com/31942449/60608471-8d6a1500-9d8d-11e9-9415-56fe645de274.png">

**Comment by pdurbin** [comment]
@MohanaPriyaNarapareddy it looks like you're trying to add what we'd call a Custom Header. This is documented at http://guides.dataverse.org/en/4.14/installation/config.html#custom-header

Please let me know if this helps.

**Comment by MohanaPriyaNarapareddy** [comment]
i am not trying to add the header. I am trying to use the above dataverse home page in my custom template with the help of iframe. I am unable to locate the html and css pages of the current dataverse home page. can u direct me to the location?

**Comment by pdurbin** [comment]
@MohanaPriyaNarapareddy hmm. I'm confused about what you're trying to do. I would suggest emailing https://groups.google.com/forum/#!forum/dataverse-community with something like this:

"Subject: help with customization/branding

I'm looking for some help with customization/branding of my installation of Dataverse. Can you please look at `https://github.com/IQSS/dataverse/issues/5939` for details?

Thanks"

@shlake recently did a lot of customization of https://dataverse.lib.virginia.edu which looks like this:

![Screen Shot 2019-07-03 at 1 01 21 PM](https://user-images.githubusercontent.com/21006/60610798-afb26180-9d92-11e9-9f47-4183b2c6f17b.png)

Others on that mailing list might be able to share their stories and code as well.

**Comment by MohanaPriyaNarapareddy** [comment]
Sure. will email them. I just need the styling sheets of the current dataverse home page.

**Comment by TaniaSchlatter** [comment]
Hi @MohanaPriyaNarapareddy, it sounds like you are trying to have a home page that displays all the datasets and dataverses, along with the filters on the left, as shown in the image you added earlier today. In the guides I think we call that the "root dataverse" page. We call a home page something that an installation has customized, and that appears before a root dataverse page, if there is one and a user navigates to the "top" page of your installation. If this is the case, you would not want to use a custom home page (custom-homepage.html).

**Comment by MohanaPriyaNarapareddy** [comment]
Hello Tania, Thanks for your response. Can u direct me to the styling sheets of the "root dataverse page"?

**Comment by pdurbin** [comment]
@MohanaPriyaNarapareddy hi! @TaniaSchlatter just stopped by my desk and we think you'd like to apply custom CSS to your Dataverse. Here's an example of custom CSS at https://edatos.consorciomadrono.es

![Screen Shot 2019-07-03 at 3 17 23 PM](https://user-images.githubusercontent.com/21006/60619060-c7dfac00-9da5-11e9-9985-6dbb158ba08e.png)

Is this the sort of customization you're interested in? If so @juancorr can probably direct you to the custom CSS they are using.

**Comment by MohanaPriyaNarapareddy** [comment]
yes, can u direct me to the html and css sheet of the root dataverse page?

**Comment by pdurbin** [comment]
> yes, can u direct me to the html and css sheet of the root dataverse page?

I believe it's all in here: https://github.com/IQSS/dataverse/blob/v4.15/src/main/webapp/resources/css/structure.css

**Comment by MohanaPriyaNarapareddy** [comment]
Have gone through this earlier. couldn't find the html page of the root dataverse page

**Comment by pdurbin** [comment]
@MohanaPriyaNarapareddy here is the HTML for the dataset cards on the root dataverse page, for example:

https://github.com/IQSS/dataverse/blob/v4.15/src/main/webapp/search-include-fragment.xhtml#L498

**Comment by juancorr** [comment]
Hello @MohanaPriyaNarapareddy, 

  In e-cienciaDatos, we have done some changes in dataverse.xhtml (main home page) y dataverse_header.xhml . You can see the source code in https://github.com/Consorcio-Madrono/dataverse/tree/v4.11eDatos/src/main/webapp . You can compare our code with the original v4.11 dataverse code.

  We have customized css, footer and header too:
https://github.com/Consorcio-Madrono/dataverse/blob/v4.11eDatos/src/main/webapp/resources/css/custom-stylesheet.css
https://github.com/Consorcio-Madrono/dataverse/blob/v4.11eDatos/src/main/webapp/resources/html/custom-footer.html
https://github.com/Consorcio-Madrono/dataverse/blob/v4.11eDatos/src/main/webapp/resources/html/custom-header.html
 
  I hope it helps.

**Comment by pdurbin** [comment]
@juancorr thanks! I didn't know your custom CSS file is on GitHub!

**Comment by MohanaPriyaNarapareddy** [comment]
I am trying to disable the display of the root dataverse theme, so that I can remove the dataverse logo and navigation bar, which helps my customization.
http://guides.dataverse.org/en/latest/installation/config.html#custom-header
I tried the following as mentioned above in the documentation. 
curl -X PUT -d 'true' http://localhost:8080/api/admin/settings/:DisableRootDataverseTheme
But, I am getting the following error. 
{ status:"error", message:"Endpoint available from localhost only. Please contact the dataverse administrator"}

**Comment by pdurbin** [comment]
@MohanaPriyaNarapareddy are you running that exact curl command with "localhost:8080" in it? The error you see is expected if you put the name of your server in the curl command instead. You have to ssh into your server first and then run the localhost version.

**Comment by MohanaPriyaNarapareddy** [comment]
Hello,  i am trying to remove the dataverse logo in the below display as a part of my customization. 
Can u please suggest me the appropriate way to do that? 
<img width="719" alt="Screen Shot 2019-07-15 at 11 39 22 AM" src="https://user-images.githubusercontent.com/31942449/61229141-9ea01380-a6f5-11e9-82e1-345eea34bcfb.png">

**Comment by mheppler** [comment]
@MohanaPriyaNarapareddy in a comment from @pdurbin above, he included links to the Installation Guide which cover this feature. Specifically the Custom Navbar Logo section will outline the steps to replace that navbar logo with your own custom logo image.

http://guides.dataverse.org/en/4.14/installation/config.html#custom-navbar-logo

Good luck!

**Comment by djbrooke** [comment]
Hi @MohanaPriyaNarapareddy - I'm going to close this out. Please let us know when your dataverse installation is ready to be put on the map at dataverse.org! Thank you!

**Comment by MohanaPriyaNarapareddy** [comment]
hello, I am trying to remove the header navigation bar. I tried to replace it with my custom header. But I could remove it. I tried disabling the theme of the root dataverse. Still, it doesn't seem to work.
<img width="1440" alt="Screen Shot 2019-07-30 at 10 16 30 AM" src="https://user-images.githubusercontent.com/31942449/62144181-5b31d180-b2bf-11e9-9c48-c3828013706f.png">

**Comment by mheppler** [comment]
@MohanaPriyaNarapareddy sorry, but there is no way to configure Dataverse and remove the navbar from the UI.

**Comment by pdurbin** [comment]
@MohanaPriyaNarapareddy if you remove the header navigation bar, your users won't be able to click "Log In".

**Comment by hblancoca** [comment]
@pdurbin Hi, I have a question about that, its possible to customize each dataverse with  different css styles?

**Comment by pdurbin** [comment]
@hblancoca at the installation level you can have a custom CSS styles: http://guides.dataverse.org/en/4.18.1/installation/config.html#custom-stylesheet

I *think* you asking about dataverses within a Dataverse installation, however. No custom CSS files are not supported. Please see also this issue:

- Footer image and CSS customization for Sub-Dataverse #6156
