### ISSUE TITLE
Discipline-specific Ingest: Type "Figure" not added to Astro Type

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#594]
---

Author Name: **Kevin Condon** (@kcondon)
Original Redmine Issue: 4025, https://redmine.hmdc.harvard.edu/issues/4025
Original Date: 2014-05-21
Original Assignee: Gustavo Durand

---

Reported by Gus, tested on dataverse-demo.iq.harvard.edu

"dataset: http://dx.doi.org/10.5072/FK2/144
(unpublished)
[file: PerA_12coFCRAO_F_map.png]"

The metadata model had listed PNG mimetypes to be "Typed" as Figure. This file was not typed on add.

**Comment by pdurbin** [comment]
Related: #3259 and #916

**Comment by pdurbin** [comment]
> Still, it's not clear to me at all how this is going to work - it sounds like the same JPEG and PNG files that we treat as regular images in most studies would somehow need to be treated as special "astronomical images", in astro datasets and dataverses...

These days we have file tags. Can we just use those?
