### ISSUE TITLE
Tests failing on phoenix

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#5946]
Private URL tests are failing.

**Comment by pdurbin** [comment]
a9483ac is the commit phoenix was on when the tests failed:

![Screen Shot 2019-06-14 at 11 23 22 AM](https://user-images.githubusercontent.com/21006/59519995-0bc24e00-8e97-11e9-8596-cdeae9660315.png)

![Screen Shot 2019-06-14 at 11 24 06 AM](https://user-images.githubusercontent.com/21006/59519994-0bc24e00-8e97-11e9-9f7f-f816665240fa.png)

**Comment by pdurbin** [comment]
Ok, passing as of 5d9c42a. Phew. Closing. Sorry for the noise.
