### ISSUE TITLE
Download API

### ISSUE THREAD

**Issue by baerbock** [IQSS/dataverse#5953]
When downloading through e.g.
`wget http://dataverse.harvard.edu/api/access/datafile/:persistentId/?persistentId=doi:10.7910/DVN/G4TBLF/7RIFT5`
is automatically the newest version of the file selected?

**Comment by pdurbin** [comment]
@baerbock hi! I'm sorry for the slow response. We are in the middle of our 5th annual Dataverse Community Meeting: https://dataverse.org/events

When you reference a file using a DOI or a database id, the exact same file should be downloaded every time. I mean the bytes are always the same and if you check the MD5 it should be the same as the MD5 that Dataverse shows. Sometime we say "files are immutable" if that helps.

**Comment by jggautier** [comment]
I thought it might be helpful to add that in installations that register PIDs for files, every file within a dataset is given its own PID (such as a DOI) and database id, even if one file was uploaded as a replacement of an existing file using the file replace feature.

For example, in [this dataset](https://doi.org/10.7910/DVN/5P03UL), the depositor used the file replace feature to replace a file in version 2 of the dataset with a new file, which was published in version 3 of the dataset.
- The first file's DOI, in version 2, is https://doi.org/10.7910/DVN/5P03UL/G7INOU
- The replacement file's DOI, in version 3, is https://doi.org/10.7910/DVN/5P03UL/ZRYGOX

And of course both files have different database IDs.

**Comment by djbrooke** [comment]
Hi @baerbock - I'm going to close this out, but feel free to reopen if you have questions or if there's an issue.
