### ISSUE TITLE
Issue uploading large files with an S3 backend

### ISSUE THREAD

**Issue by rontrompert** [IQSS/dataverse#5954]
Hi,

We have managed to successfully couple Dataverse with an Openstack SWIFT S3 backend. The problem that we run into now is that uploading small files works fine, but uploading a 6GB file fails. When you upload a big file to an S3 object store you have to do multipart uploading, where an object is uploaded in smaller pieces. 
We have had a quick look at the S3-related code in Dataverse but we did not find an implementation of multipart uploading. 

Is multipart uploading implemented? And if not, could this be implemented so that we can upload large objects?

Cheers,

Ron

**Comment by poikilotherm** [comment]
Hi @rontrompert,

I also had a look at [S3AccessIO.java](https://github.com/IQSS/dataverse/blob/develop/src/main/java/edu/harvard/iq/dataverse/dataaccess/S3AccessIO.java), and it indeed looks like there is no multipart upload support.

I made a quick google search and found things like https://www.baeldung.com/aws-s3-multipart-upload. It seems to be fairly easy to integrate.

As this kind of relates to #5733 (setting the threshold, ...), #5072 & #5068 (testing) and #5062 (running out of tmp space, availabilty, ...), any interest to unite forces?

**Comment by pdurbin** [comment]
> uploading a 6GB file fails

This reminds me strongly of #4439. @rontrompert can you please tell us the largest file you've successfully uploaded into Dataverse? Also, are you running Dataverse 4.15? Thanks for looking at the code! (You too, @poikilotherm 😄 )

**Comment by pdurbin** [comment]
@rontrompert @poikilotherm you might be interested in reviewing a new pull request from @mderuijter at #6341
