### ISSUE TITLE
John Harvard’s is closed

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#5955]
Please schedule the Dataverse Cup Third Half in a new location. Don’t forget to update your branch before submitting your pull request.

![628E9F02-3C70-4118-8298-DB816D18C262](https://user-images.githubusercontent.com/12831666/59727256-f6d11c00-9202-11e9-928d-8ca25124b205.jpeg)

**Comment by shlake** [comment]
Suggesting Grendal's Den https://www.grendelsden.com/
as a new location.

**Comment by scolapasta** [comment]
@shlake Grendel's was were I am leaning.

**Comment by poikilotherm** [comment]
You definitely should provide end to end testing before a pull request is merged. And please keep in mind not to feed docker-aio with this. Spirits and lots of beer tend to result in catastrophes for container ships.

**Comment by donsizemore** [comment]
@scholapasta et al: Grendel’s has both wifi and a flat screen over the fireplace.

**Comment by djbrooke** [comment]
https://twitter.com/shlakeuva/status/1141507247337611264

End to end testing complete?

**Comment by donsizemore** [comment]
testing complete!

**Comment by djbrooke** [comment]
For #dataverse2020:

https://www.thecrimson.com/article/2019/7/3/wachusett-brewery-opening-harvard-square/
