### ISSUE TITLE
Download counts for partial downloads

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#5957]
We know that some users use Dataverse to serve data to networks of automated clients that rely on partial downloads of relatively small number of bytes from specific parts of the main file to keep their distributed copies in sync. 
A "partial download" is a download API call that specifies the byte offset and length. 
The problem with this is that each of these automated download calls is counted as a full download of a file, inflating our overall statistics (not to mention each one results in a new GuestBookResponse entry). 
We should either stop counting these downloads at all; or count them as a different type of a download, and exclude them from the counts displayed next to the file on the dataset page.

**Comment by djbrooke** [comment]
@mfenner and @dlowenberg - we have some thoughts about how to handle these partial downloads (see above :)), but since we'll soon be moving towards MDC and I know you're very interested in standardization, it would be good to get some input from your team as well. Thanks in advance!

**Comment by mheppler** [comment]
Related to _Guestbook: Count of Guestbook varies from displayed count. #3582_.
