### ISSUE TITLE
Add option to download all WITHOUT file hierarchy

### ISSUE THREAD

**Issue by tlchristian** [IQSS/dataverse#5959]
As a user, I want to be able to download all files without the file hierarchy preserved in the download package.  As part of their workflow, verifiers have to compare the file list in the author's README with the downloaded files.  Most often, the file list in the README is not presented in the file hierarchy, so it is cumbersome to perform the comparison.

**Comment by pdurbin** [comment]
@donsizemore and @jonc1438 told me they have some more thoughts on this issue and that it might be ok to close it.

**Comment by donsizemore** [comment]
Not okay to close it... Sherry Lake and I were talking about file view and she mentioned a toggle button in the web interface. If download all preserves the hierarchy our verifiers will indeed want this functionality.

**Comment by pdurbin** [comment]
Ah, ok, maybe @shlake will have some comments as well. Here's a visual of the new "tree" view from http://guides.dataverse.org/en/4.15/user/find-use-data.html#tree-view

![file-tree-view](https://user-images.githubusercontent.com/21006/59926770-fdc97b80-9408-11e9-9557-64df25f73074.png)

**Comment by tlchristian** [comment]
Yes, the file hierarchy view is great.  And it's great that when you "download all" the file hierarchy is retained in the download package.   However, we'd like to be able to "download all" without the hierarchy retained in the download package.

**Comment by pdurbin** [comment]
@tlchristian ok. My only concern with this is that you could have multiple files with the same name that are in different folders. In the screenshot below we see "file.txt" in various folders:

<img width="1595" alt="55624811-fc2ad880-5774-11e9-97d3-cb8c6d504e97" src="https://user-images.githubusercontent.com/21006/59927423-70872680-940a-11e9-854a-e0f77e263b54.png">

Maybe this is an edge case to have lots of files with the same name but we'll have to do some renaming in this case.

**Comment by shlake** [comment]
I think it is up to the person who downloaded the zip file to decide how to unzip the file. If you use the command line (UNIX) "unzip" you can specify to NOT to create the default hierarchy (-j option):

unzip -j dataverse_files.zip

**Comment by shlake** [comment]
In @donsizemore comment above, I was referencing the toggle on the display of the files view (hierarchy or no hierarchy). So was talking about the GUI not the download action. See my comment above on my opinion on download zips w/ hierarchy.

**Comment by djbrooke** [comment]
It'll be good to get some additional use cases around hierarchy-less downloads, but right now I'd lean towards the downloader using the method that @shlake provided. Happy to keep this open for now if others have thoughts or if I'm misunderstanding something.

**Comment by cmbz** [comment]
2024/09/30: There is an option to address this issue (see https://github.com/IQSS/dataverse/issues/5959#issuecomment-504450060). Closing as not planned.
