### ISSUE TITLE
Add support for exporting more metadata formats via XSLT crosswalks

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#5960]
Opening this issue per request from/conversation with a Dataverse user from DANS. 

The goal is to give a Dataverse admin an easy way to add support for an extra XML format, by providing an XSLT crosswalk from an existing format. (They want to support certain formats and they already have crosswalks for them from DDI). 

This can in fact be implemented using the current code base, by writing an edu.harvard.iq.dataverse.export.spi.Exporter class that would, instead of creating a metadata export from scratch, run XSL on a pre-exported DDI... But this would be a bit hacky. It would be nice to create a clean, dynamic way of handling this - an API for uploading the crosswalk and adding the information about the new format (what to call it; how to advertise it; should be available to OAI harvesters? downloadable by human users? ...)

**Comment by jggautier** [comment]
I'm assuming that the Dataverse user from DANS is @rvanheest? :) If so, would you be able to share those crosswalks (the xsl files) with me here (or over email, juliangautier@g.harvard.edu)?

**Comment by rvanheest** [comment]
@jggautier you're right in saying I'm one of the developers at DANS looking into using Dataverse in [EASY](https://easy.dans.knaw.nl/ui/home) (note: this project is separate from [DataverseNL](https://dataverse.nl/)!). Currently we're not yet using Dataverse; we're for now just looking into how we can use it in the future.

In EASY we export our metadata into [several formats over OAI-PMH](https://easy.dans.knaw.nl/oai/?verb=ListMetadataFormats). When moving toward Dataverse we would like to keep this functionality and export these formats from the Dataverse OAI-PMH.

On another note, in the original description of this issue it says that the conversion will be done from the DDI export. However, that is not what we want. We would prefer to convert to these formats from the original JSON or database data. In the DataverseNL project @paulboon and @ekoi have written an XSLT from the Dataverse JSON file to one of the formats we have in EASY. You can find that conversion as a reference [here](https://github.com/DANS-KNAW/dataverse-bridge-mappings/blob/master/src/main/resources/xsl/easy/dataverse/dataverseJson-to-easy-dataset.xsl).

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
