### ISSUE TITLE
File Ingest - On complete, refresh to remove lock shows success msg on published version not DRAFT

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#5961]
Seen locally on develop branch (v 4.15). Workflow to replicate:

- Start with published dataset, upload new files, including tabular files to ingest
- Return to dataset pg, with new draft version, and the lock msg displayed during ingest
- Page refreshes upon completion, removes lock and displays success msg, but is on the published version and not the new draft (see screenshot)

<img width="739" alt="Screen Shot 2019-06-20 at 10 00 39 AM" src="https://user-images.githubusercontent.com/687227/59855465-00fa3400-9343-11e9-8aed-b9747452354a.png">

Apparently this is a previously reported issue in #2555 (thank you once again GitHub Related Issue list), different symptoms however. That issue says the URL remained "DRAFT", but I am not seeing that `http://localhost:8080/dataset.xhtml?persistentId=doi%3A10.5072%2FFK2%2FZRD4U0&showIngestSuccess=true`.

That was fixed way back in 4.2 and unfortunately there are no linked commits or pull requests, but @landreev claimed to have fixed, but does not provide any detail on the offending code.

Also, cannot replicate in demo do to not have access to a published dataset there, and an error publishing to DataCite.

**Comment by kcondon** [comment]
Closing in favor of more general #6443  Will be added to next sprint
