### ISSUE TITLE
question: optionally replacing solrconfig.xml and solr version

### ISSUE THREAD

**Issue by jmjamison** [IQSS/dataverse#5969]
About  replacing solrconfig.xml.    It was a bit confusing about where to find the replacement solrconfig.xml file.  I'm assuming I should use the one in the 4.15 source files.

Which leads to another question.   I'm running solr 7.3.0.   Should I be upgrading to 7.3.1?

As always, thank you for your patience with beginner questions,

Jamie

**Comment by poikilotherm** [comment]
Hey Jamie,

you might take a look at my comment here https://github.com/IQSS/dataverse-kubernetes/issues/67#issuecomment-502714220, regarding the replacement.

Regarding upgrading to Solr 7.3.1: maybe a look at http://lucene.apache.org/solr/7_3_1/changes/Changes.html might provide help in picking poison?

Cheers
Oliver

**Comment by djbrooke** [comment]
Hi @jmjamison and thanks @poikilotherm for the answers here! We recommended an upgrade to Solr 7.3.1 in the 4.11 release notes, so I'd encourage you to upgrade if possible. Yes, the solrconfig provided with the source files in the release is the correct one. I'll close this for now, but feel free to reopen if there are more questions.
