### ISSUE TITLE
On the Dataset Page, Filter Tags and File Types containing Spaces 

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#5972]
Tags and File Types with spaces aren't being filtered. This was patched in dataverse.harvard.edu this evening. In filesFragment.xhtml, we need to change: 

```<f:param name="fileTag" value="#{facetLabel.name}"/>```
to
```<f:param name="fileTag" value='"#{facetLabel.name}"'/>```

and 

```<f:param name="fileTypeGroupFacet" value="#{facetLabel.name}"/>```
to
```<f:param name="fileTypeGroupFacet" value='"#{facetLabel.name}"'/>```

**Comment by kcondon** [comment]
Tested, works.

**Comment by umuchlish** [comment]
Hi All, Does this error also related to this issue? Thanks a bunch. Usman.

Subject metadata:  Forest Management & Restoration (FMR)

dataverse-4.15\logs\server.log: 
Search Syntax Error: Error from server at http://localhost:8983/solr/collection1: org.apache.solr.search.SyntaxError: Cannot parse 'subject_ss:"Forest Management ': Lexical error at line 1, column 31.  Encountered: <EOF> after : "\"Forest Management "]]

**Comment by pdurbin** [comment]
@umuchlish I believe your issue might be different. I wonder if the "&" is causing you trouble. Can you please give us step by step instructions on how to reproduce the error you're seeing?

**Comment by umuchlish** [comment]
Hi @pdurbin, I am not sure what triggered the Error, it's just appear after I finished the upgrade process.

**Comment by umuchlish** [comment]
Thanks Phil. I found the culprit, its came from the API Search request without encode the & symbol.

**Comment by pdurbin** [comment]
@umuchlish do you have a fix then? If so, is it a code change? Or something we should document in the guides?

**Comment by umuchlish** [comment]
No Need Phil, its from external request that triggered by project website. 

Thank you Phil.
