### ISSUE TITLE
Please support PostgreSQL 9.5.x

### ISSUE THREAD

**Issue by bricas** [IQSS/dataverse#5976]
The official package of PostgreSQL on Ubuntu 16.04 is still at 9.5

I've filed a support ticket regarding the upgrade to 4.15 which apparently was caused by using SQL only supported by 9.6+

I know I'm in the minority of users by using Ubuntu, but while 16.04 is still officially supported (April 2021) it would be nice if PG 9.5 was still supported by Dataverse.

(sidebar: I'm actually using Ubuntu 18.04, which has PG 10 available, but i understand it has not been tested with Dataverse thoroughly yet)

**Comment by donsizemore** [comment]
If you don't mind dumping and reloading your tables, you could install 9.6 from the PostgreSQL APT repo? https://wiki.postgresql.org/wiki/Apt
(unless you really want to stick with distro-canon packages)

**Comment by bricas** [comment]
We went with @donsizemore's suggestion and are now on pg 9.6.
