### ISSUE TITLE
JavaMail config for Microsoft-Office365 email

### ISSUE THREAD

**Issue by umuchlish** [IQSS/dataverse#5986]
Just in case someone need it, this config has worked from my end: 

./bin/asadmin create-javamail-resource --mailhost smtp.office365.com --mailuser mail\-address\@mymail\.org --fromaddress mail\-address\@mymail\.org --property mail.smtp.auth=true:mail.smtp.password=mypassword:mail.smtp.port=587:mail.smtp.socketFactory.port=587:mail.smtp.socketFactory.fallback=true:mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory:mail.smtp.starttls.enable=true mail/notifyMailSession

Cheers
Usman

**Comment by pdurbin** [comment]
@umuchlish cool. Were you thinking about adding this example to the Dataverse guides?

Alternatively, we could close the issue and link people to it if they ask about configuring Dataverse and JavaMail for Office365.

**Comment by umuchlish** [comment]
hi @pdurbin, issue-number as reference is just fine with me.

**Comment by pdurbin** [comment]
@umuchlish sounds good. I'll close this then. Thanks.
