### ISSUE TITLE
Use addition "[datasetUNF]" for dataset UNFs

### ISSUE THREAD

**Issue by philippconzett** [IQSS/dataverse#5988]
Properly ingested tabular files are assigned a UNF in Dataverse. On the file landing page, such file UNFs are displayed with the addition "[fileUNF]". Based on the file UNF(s) in a dataset, Dataverse calculates a UNF for the entire dataset. This dataset UNF is displayed on the dataset landing page in the dataset citation with the addition "[fileUNF]".  Since this UNF applies for the entire dataset, I suggest to replace the addition "[fileUNF]" with "[datasetUNF]".

**Comment by pdurbin** [comment]
Here's the code in question, I believe:

https://github.com/IQSS/dataverse/blob/v4.15/src/main/java/edu/harvard/iq/dataverse/DataCitation.java#L214

**Comment by pdurbin** [comment]
Related:

- #1682
- #7328

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
