### ISSUE TITLE
Documentation of OAI-PMH server does not mention the URL of the service

### ISSUE THREAD

**Issue by pkiraly** [IQSS/dataverse#5992]
The OAI-PMH server documentation (e.g. http://guides.dataverse.org/en/4.14/admin/harvestserver.html) does not mention the URL of the OAI-PMH server. I suggest to add one sentence to the end of "How does it work?" section:

The base URL of the OAI-PMH service is https://<host>/oai.

I'll create a pull request for that.

**Comment by pkiraly** [comment]
Seems it is already added at 4.15 (http://guides.dataverse.org/en/4.15/admin/harvestserver.html), so is is already solved.

**Comment by pdurbin** [comment]
Yes, that was thanks to @poikilotherm in pull request #5834! 🎉
