### ISSUE TITLE
LimitNPROC in SystemD sample file

### ISSUE THREAD

**Issue by jri-sp** [IQSS/dataverse#5993]
Hello,

Just a little issue to say that it could be nice to add `LimitNPROC=65000` to http://guides.dataverse.org/en/4.15/_downloads/solr.service sample file because systemd completely ignores `/etc/security/limits*` and it shows a warning at solr startup:
```
Jul 04 12:53:02  solr[619]: *** [WARN] ***  Your Max Processes Limit is currently 31171.
Jul 04 12:53:02  solr[619]: It should be set to 65000 to avoid operational disruption.
Jul 04 12:53:02  solr[619]: If you no longer wish to see this warning, set SOLR_ULIMIT_CHECKS to false in your profile or solr.in.sh
```

Just found that because I was following this doc:
http://guides.dataverse.org/en/4.15/installation/prerequisites.html#solr-init-script

**Comment by kcondon** [comment]
This is fine to merge, pending point release planning.
