### ISSUE TITLE
External data support: Globus endpoints (deposit and indexing)

### ISSUE THREAD

**Issue by amberleahey** [IQSS/dataverse#5994]
At Scholars Portal we would like to develop an option to allow a depositor to add / link to a Globus endpoint as an option from the deposit form (configurable at the instance level to only certain providers for trustworthiness). 

Use Case:
Users with large volumes or large size data may wish to keep data stored remotely outside of DV, and setup a Globus endpoint for sharing and data transfer. In Canada, Globus is used by the national high performance computing community and at Compute Canada. We think Dataverse would be a good option for researchers who wish to create descriptive and discoverable metadata in DV and keep institutional dataset collections together from a single point of access regardless of where the data is stored. 

DV would expose the globus endpoint through the UI and index in the metadata the dataset & file Globus endpoint(s) to authorized or public users of the data, forcing the separate Globus login when a user tries to access in DV. 

This development is related to the following issues:
https://github.com/IQSS/dataverse/issues/3145
https://github.com/IQSS/dataverse/issues/2728
https://github.com/IQSS/dataverse/issues/3403
https://github.com/IQSS/dataverse/issues/5213

**Comment by pdurbin** [comment]
I just merged #8891 (Globus support). Thank you to @JayanthyChengan @lubitchv and @qqmyers for all the hard work on this!
