### ISSUE TITLE
Missing S3 storage options for payload signing and chunked encoding

### ISSUE THREAD

**Issue by PaulBoon** [IQSS/dataverse#5996]
Using an Openstack SWIFT S3 backend, we could only get it working with payload signing enabled and chunked encoding disabled. These seem nice options to have anyway.

This can be added in [S3AccessIO.java](https://github.com/IQSS/dataverse/blob/develop/src/main/java/edu/harvard/iq/dataverse/dataaccess/S3AccessIO.java). The constructor has a line for setting the PathStyleAccess, so we could add PayloadSigning and ChunkedEncoding based on options there as well.

**Comment by poikilotherm** [comment]
Cross referencing #5072 here, too

**Comment by pdurbin** [comment]
@PaulBoon adding those options sounds like it would be a nice contribution. Are you thinking about making a pull request? 😄
