### ISSUE TITLE
As a curator, I want depositors to be able to add structured information about the relationships between datasets

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#5998]
Curators want to add and want depositors to add structured information about datasets that are related to the datasets they're depositing so that computers know what the metadata is and can act on it, such as exporting it in other metadata standards.

@doigl [wrote in a related issue](https://github.com/IQSS/dataverse/issues/2778#issuecomment-498545002) that

> "We would like to use the relation to other datasets to link the (datasets of the) individual steps in the creation process of a data record and therefore record the provenance."

Dataverse's "related dataset" metadata field is a free text box:

![48018642-60326d80-e0ff-11e8-846f-53846d10bb76](https://user-images.githubusercontent.com/18374574/60749293-a9281380-9f65-11e9-94fc-9fb4505f7971.png)

Unless there's a way for a system to infer the type of relationship between one dataset and another using the free text that depositors enter in that box, mostly dataset citations, Dataverse will need to add fields that let depositors indicate the identifier type, identifier and type of relationship. Similiar to plans for the "related publications" metadata fields, we could use or map to DataCite's vocabulary of relation types (isSourceOf, Requires, etc).

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.

**Comment by pdurbin** [comment]
This is highly related to the recent meeting with @vera @julian-schneider @qqmyers and myself:

2024-07-02 BioHackathon meeting (dataset relations in Dataverse) - https://docs.google.com/document/d/1fpV4hhsk879zXMPLiK_ILK1gzdoyFslVXywjo8LhZmM/edit?usp=sharing

We talked a lot about the "Related Dataset" field.
