### ISSUE TITLE
UI proposal: as a Dataverse user, I want autocompletion for (long) controlled vocab metadata

### ISSUE THREAD

**Issue by poikilotherm** [IQSS/dataverse#6000]
We want our researchers to add datasets and annotate them with some metadata needed for research information systems / science reporting:

1. Select one or more departments out of a list of ~70 or maybe even worse, [a list of ~500](https://juser.fz-juelich.de/search?ln=en&cc=Institutes&p=&f=&action_search=Suchen&c=Institutes&c=&sf=&so=d&rm=&rg=10&sc=1)
2. Select one topic out of [a list of ~120](http://juser.fz-juelich.de/search?ln=en&cc=Grants&p=035__a%3A%2FPOF3-.*%2F%20and%20not%20751_7a%3A%22IGN_4_FZJ%22&f=&action_search=Suchen&c=Grants&c=&sf=&so=d&rm=&rg=10&sc=1&of=hb)

Adding the controlled vocabulary via custom metadata TSV files is fine. Choosing from endless checkbox or dropdown is a nightmare...

I would like to propose changing controlled vocabulary metadata fields to autocomplete UI components instead. PrimeFaces offers them out of the box: https://www.primefaces.org/showcase/ui/input/autoComplete.xhtml

This is kind of blocker for us, as we are not very fond of going into production with a bad UI experience for our researchers. :unamused: Skipping the metadata in a first production version might be a solution, but it is far from ideal, as people need to add it later (most likely wont happen).

I'm happy to craft a code contribution, but am aware that this needs to be discussed by UI/UX people first. Thinking of @TaniaSchlatter, @djbrooke and @dlmurphy here...

----
This definitly is connected to #4772 (:wave: @RightInTwo, @doigl and @4tikhonov) and might be part of its solution. Mentioning @bronger, too.

**Comment by 4tikhonov** [comment]
Hi @poikilotherm, can you please provide also link to your Search API endpoint to get JSON out from this [query](http://juser.fz-juelich.de/search?ln=en&cc=Grants&p=035__a%3A%2FPOF3-.*%2F%20and%20not%20751_7a%3A%22IGN_4_FZJ%22&f=&action_search=Suchen&c=Grants&c=&sf=&so=d&rm=&rg=10&sc=1&of=hb)?

**Comment by poikilotherm** [comment]
Sorry, I can't. There is no public available JSON output for this. :unamused:

**Comment by RightInTwo** [comment]
Could the ORCID search API be a good example? 

https://pub.orcid.org/v2.1/search/?q="müller"?&start=0&rows=10 (with header "Accept: application/json")

#4236 #4772

**Comment by poikilotherm** [comment]
Guys maybe I need to emphasize a bit: this issue is not about using an API in the background to fill in the data, but using existing views, using autocomplete (multiselect) components instead of generating checkboxes and dropdowns.

@pdurbin requested adding some screenshots to be added here to have a showcase. I'll see what I can do about this.

**Comment by RightInTwo** [comment]
@poikilotherm Yes, but a general way to include data from APIs via autocomplete would also solve your issue, wouldn't it? That way, you would only need a small API endpoint and not sync your lists to TSV files. Not?

**Comment by poikilotherm** [comment]
Definitely. But solving both at the same time seems to be a big change which will require a lot more effort. I know that people at IQSS like small changes, thus I hope (as outlined above) this can be a first small step into the right direction. We need to get things done now... :wink:

**Comment by pdurbin** [comment]
Yes, small chunks, please!

@poikilotherm it looks like there are 180 languages, so that might be a good one to demo your proposed UI solution on. Here's a screenshot:

![Screenshot from 2019-07-08 16-10-20](https://user-images.githubusercontent.com/21006/60839358-fd680900-a19a-11e9-8e53-23686b74b3fe.png)

@jggautier might be aware of a controlled vocabulary with even more values.

**Comment by jggautier** [comment]
I think this is implied in this issue's title, but might be helpful to make explicit: Would a PR for this issue include a way for installations to specify which type of component (auto complete, drop down, check boxes, etc) is used for which fields? I would say we would want to use autocomplete *in addition to* other types of components.

**Comment by poikilotherm** [comment]
@pdurbin thank you, excellent find! Thx for saving me from working on a complete example... :smile: 

@jggautier I think this should be discussed. 

- Dropdowns could be done with autocomplete fields as you can see in the Primeface showcase. - Checkboxes might be replaced by autocomplete fields with multiselect. 

It all depends on what you UX/UI guys prefer. As far as I can foresee, enabling *additional* configuration  requires a change in the TSV file format.

Currently rendering for text field with `allowControlledVocabulary=TRUE` is done as checkbox when `allowmultiples=TRUE` and as dropdown when `allowmultiples=FALSE`. Adding a third rendering option would need better configuration or some other (configurable) criteria like number of terms.

**Comment by jggautier** [comment]
Ah, thanks, I'd just assumed that the Primefaces "Autocomplete" was the kind of field where someone enters letters and the field simply displays options from a controlled vocab. I hadn't looked at [the components](https://www.primefaces.org/showcase/ui/input/autoComplete.xhtml) @poikilotherm mentioned earlier, which include multi select and dropdown.

I think the languages field @pdurbin pointed out is a great example for these types of components because it's reasonable to assume that depositors know the names of languages they're looking for, so they'll know what to start typing.

For a field like Subjects with its list of 13 terms, I'm not so sure people would know what to start typing. Perhaps the dropdown could include a multi-select?

I'm excited to see Dataverse have autocomplete 😄; like you wrote it's been a blocker for a while for improving how people add metadata.

**Comment by poikilotherm** [comment]
I just took a look at two other standard Primefaces UI components:
* [SelectCheckboxMenu](https://www.primefaces.org/showcase/ui/input/checkboxMenu.xhtml)
* [SelectOneMenu](https://www.primefaces.org/showcase/ui/input/oneMenu.xhtml)

`<p:selectOneMenu>` is already in use at [metadataFragment.xhtml](https://github.com/IQSS/dataverse/blob/2f477c9e733bdffb9421d5e51a7ce2c49d4073d5/src/main/webapp/metadataFragment.xhtml#L206) and [filtering can be activated](https://www.primefaces.org/docs/vdl/6.2/core/primefaces-p/selectOneMenu.html) for easier lookup of values.

Instead of [`<p:selectManyCheckbox>`](https://github.com/IQSS/dataverse/blob/2f477c9e733bdffb9421d5e51a7ce2c49d4073d5/src/main/webapp/metadataFragment.xhtml#L212) the [component `<p:selectCheckboxMenu>`](https://www.primefaces.org/docs/vdl/6.2/core/primefaces-p/selectCheckboxMenu.html) could be used, offering filtering and more.

Both do not offer limiting the number of elements to choose from. Could this be an interesting minimal alternative compared to using `<p:autoComplete>`?

**Comment by TaniaSchlatter** [comment]
In general, [oneMenu.xhtml](https://www.primefaces.org/showcase/ui/input/oneMenu.xhtml) is good for 3-12 items,  [checkboxMenu.xhtml](checkboxMenu.xhtml) is good for 10 to maybe 40 or 50 items, and [autoComplete.xhtml](https://www.primefaces.org/showcase/ui/input/autoComplete.xhtml) is good for 20-many (100?) items.  For more than 150 or so items I'd use a categorized search, like Amazon. 
<img width="587" alt="Screen Shot 2019-07-09 at 11 10 39 AM" src="https://user-images.githubusercontent.com/15386424/60900833-e0831280-a23a-11e9-82e7-a588061cb0d5.png">

I would want to understand the parameters of what might be displayed to help make a choice. We don't want to add a lot of conditional code for what widget to display when.

**Comment by djbrooke** [comment]
Closing in favor of #6030 to evaluate as part of a larger effort (though I see potential that we could reopen this as a smaller chunk).

**Comment by poikilotherm** [comment]
Meh. I already started some implementation work for this to have sth. you guys could take a look at and play with... I'm feeling blocked. :neutral_face:

**Comment by pdurbin** [comment]
> I already started some implementation work for this to have sth. you guys could take a look at and play with... I'm feeling blocked. 😐 Meh.

@poikilotherm and I started talking about him feeling blocked at http://irclog.iq.harvard.edu/dataverse/2019-07-18#i_101305 and he has many JSF questions that I wasn't able to answer at the exact times he asked (heads up to @scolapasta and other that the questions are in the IRC log above).

In short @poikilotherm was actively working on a prototype of what's possible using JSF and PrimeFaces and I encouraged him to continue working on his branch so that I can spin it up and demo it to @TaniaSchlatter @mheppler @djbrooke @scolapasta and @jggautier (the design meeting regulars).

The reason @poikilotherm is working on this, of course, is that he feels it's very important before his institution goes live with Dataverse. The "poikilotherm / FZJ" board can be found at https://github.com/orgs/IQSS/projects/4

**Comment by djbrooke** [comment]
Sure, as I mentioned in the above message, we can re-evaluate this as a smaller effort.

**Comment by 4tikhonov** [comment]
I just spoke to @mbamouni and his institution INRA requires the same functionality.

**Comment by pdurbin** [comment]
Over in pull request #6356 we are playing around with swapping out the component for "Subject" to look like this (not merged yet, could probably use some design work):

![Screen Shot 2019-11-20 at 2 06 37 PM](https://user-images.githubusercontent.com/21006/69269497-219f1200-0b9f-11ea-960b-2327c4e4d2b2.png)

You can also see it under "Language", which looks like this:

![Screen Shot 2019-11-20 at 2 11 40 PM](https://user-images.githubusercontent.com/21006/69269774-bb66bf00-0b9f-11ea-9866-568fb587fdd2.png)

For comparison, here's how "Subject" and "Language" look on the demo site (which runs code that has already been released):

![Screen Shot 2019-11-20 at 2 13 16 PM](https://user-images.githubusercontent.com/21006/69269952-0f71a380-0ba0-11ea-9db5-d948512ef9d4.png)
![Screen Shot 2019-11-20 at 2 13 27 PM](https://user-images.githubusercontent.com/21006/69269953-0f71a380-0ba0-11ea-832b-81cc8150b9f4.png)

**Comment by mheppler** [comment]
ATTN: @poikilotherm, @RightInTwo, @doigl, @4tikhonov, @bronger, @mbamouni, @alejandratenorio, et al.

We had a bug related to the Subject metadata form component reported in issue #6339, so we decided to do away with the scrolling list, and use the `selectCheckboxMenu` PrimeFaces component that Oliver suggested above.

This new component provides a filter at the top of the dropdown menu, allowing users to easily find controlled vocabulary values in long lists. (See screenshot.)

![Screen Shot 2019-11-20 at 1 36 08 PM](https://user-images.githubusercontent.com/687227/69269996-22847380-0ba0-11ea-814f-e422763b2ea8.png)

I am going to close this issue, and ask that you follow the progress of that new issue, _Subjects disappear when clicked in metadata editing #6339_. We hope to have this improvement included in our next 4.18.1 release.
