### ISSUE TITLE
Dataverse mangles "original format" filename extensions

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#6002]
Only slightly related to #2720: Dataverse still renames certain file format extensions on upload/ingest. In our particular case, a `.tab` file is returned in original format as `.tsv` — verified on 4.14 and 4.15.

This breaks automated reproducibility when filenames are hard-coded in user-submitted scripts.

**Comment by oscardssmith** [comment]
As the culprit, this was intentional, since from everything I could find suggested that tsv was the much more common name for tab separated data. I understand the frustration though.

**Comment by djbrooke** [comment]
Thanks @donsizemore for the report. We'll change this.

**Comment by djbrooke** [comment]
We should add a solution that makes the reproducibility folks happy (this issue) and the preservation folks happy (#2720). We'll bring both into this sprint.

**Comment by djbrooke** [comment]
Closing in favor of newly-created #6006.
