### ISSUE TITLE
If dataset depositors choose a contributor type that isn't one of DataCite's contributorTypes, in Dataverse's DataCite and OpenAIRE metadata exports, map to DataCite's "Other" contributorType

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#6003]
An organization that uses Dataverse, CIMMYT, will be adding to or changing the contributor types in the citation metadata block:

<img width="698" alt="Screen Shot 2019-07-09 at 2 21 44 PM" src="https://user-images.githubusercontent.com/18374574/60913249-fb628080-a254-11e9-802c-e9dad68fc0f4.png">

That list comes from DataCite's metadata schema. CIMMYT plans to add contributor types that aren't on that list because they don't think that list represents all types of their dataset contributors and they would rather not use DataCite's "Other" contributor type.

Dataverse's OpenAIRE metadata export, based on the DataCite schema, includes contributor metadata ([example OpenAIRE xml from Demo Dataverse](https://demo.dataverse.org/api/datasets/export?exporter=oai_datacite&persistentId=doi%3A10.70122/FK2/P2VLO5)). I think when the code that creates the exports was written, it was assumed that the contributor types that depositors can choose from will always be one of DataCite's contributor types.

When an installation lets depositors choose contributor types that aren't one of DataCite's contributor types, will contributor metadata appear in the OpenAIRE metadata export? If so, would the installation's custom contributor type term be used, which would produce metadata that doesn't validate against the DataCite schema?:

```
<contributor contributorType="TermNotInDataCiteSchema">
  <contributorName>Starr, Joan</contributorName>
</contributor>
```

When an installation lets depositors choose contributor types that aren't one of DataCite's contributor types, that contributor type should be mapped to "Other" in the OpenAIRE export (and/or the DataCite export (https://github.com/IQSS/dataverse/issues/5889)) and in the metadata that's sent to DataCite (https://github.com/IQSS/dataverse/issues/2917):

```
<contributor contributorType="Other">
  <contributorName>Starr, Joan</contributorName>
</contributor>
```

**Definition of done for this issue**:

Make sure that if a dataset depositor chooses a contributor type that is not one of DataCite's contributor types, the OpenAIRE metadata export code maps that contributor type to DataCite's "Other" contributor type.

**Comment by djbrooke** [comment]
- It would be good to show some indication of the mapping in the dropdown as this could help people make decisions (ex. in DataCite this maps to this)

**Comment by djbrooke** [comment]
Pulling out of the sprint for now. We need to discuss how to implement this without requiring installations to fork the metadata blocks.

**Comment by djbrooke** [comment]
Closing in favor of #6030 to evaluate as part of a larger effort.
