### ISSUE TITLE
Only use one HttpSolrClient object per Solr server (i.e. One HttpSolrClient)

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#6005]
When we released 4.15 we had a production stability issue; this was caused by the fact that the DatasetPage was building a HttpSolrClient each time the page was loaded. We modified the code and patched our prod so that we now get the HttpSolrClient from the SearchServiceBean, so one HttpSolrClient gets bulit per SearchServiceBean in the pool (and closed when the ejb is destroyed).

However, in researching this issue further, it appears this is still not the correct way. 

"Create one HttpSolrClient object for each Solr server you are talking to. Reuse it for all requests to that Solr server. It will manage a pool of connections and keep them alive for faster communication. "

from: http://lucene.472066.n3.nabble.com/Memory-leak-defect-or-misssuse-of-SolrJ-API-td4254226.html

**Comment by landreev** [comment]
Meant for it to go into code review yesterday.
