### ISSUE TITLE
Publising a dataset gives a confusing message about license

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#6015]
When you publish a dataset, you get this message:

"By default datasets are published with the CC0-“Public Domain Dedication” waiver. Learn more about the CC0 waiver here. 

To publish with custom Terms of Use, click the Cancel button and go to the Terms tab for this dataset."

But this shows up even if you have changed the terms and turned off the CC0 waiver. 

I found this confusing and it forced me to go back and double check that I had in fact turned it off.

**Comment by sbarbosadataverse** [comment]
@scolapasta when you say "changed the terms" does that mean the user actually populated the custom terms fields? Or did they just opt out of CC0 and leave the custom terms blank?

**Comment by pdurbin** [comment]
Is this better now that we support multiple licenses? I know we worked on the wording a lot.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
