### ISSUE TITLE
Contributing to documentation: Quick Fix procedure creates a pull request in forked repo instead of upstream repo

### ISSUE THREAD

**Issue by j-n-c** [IQSS/dataverse#6017]
**Quick Fix** procedure depicted in http://guides.dataverse.org/en/latest/developers/documentation.html regarding contributions to documentation will create a pull request on forked Dataverse repo (_github_username_/dataverse) instead of upstream repo (IQSS/dataverse)

**Comment by pdurbin** [comment]
@j-n-c thanks for opening this issue! For years, I've been thinking we should revisit that page. Are you interested in making a pull request? 😄
