### ISSUE TITLE
TestShib is gone away. Document use of SAMLTest instead.

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#6018]
As @poikilotherm reported in #5666 TestShib is gone away and https://samltest.id/ looks like a great replacement. Accompanying PR will also close #5369

**Comment by pdurbin** [comment]
@donsizemore and I talked about this issue the other day. He's not actively working on it so it's up for grabs.

Here's where the guides continue to mention the now-defunct testshib.org site: http://guides.dataverse.org/en/4.18/installation/shibboleth.html#exchange-metadata-with-your-identity-provider

**Comment by pdurbin** [comment]
https://help.hmdc.harvard.edu/Ticket/Display.html?id=283463 is taking a fair amount of time. My Shibboleth fu is weak ever since my shib test box got owned (don't run Glassfish as root, kids!).

I think I may try to get Shibboleth working on my https://dev2.dataverse.org server using https://samltest.id

If I learn anything, I can at least try to leave some notes here.

Then maybe someday @donsizemore can add it to SAMLtest (that's how they brand https://samltest.id ) to dataverse-ansible.

**Comment by pdurbin** [comment]
Hmm, these files look pretty good:

- https://dev2.dataverse.org/Shibboleth.sso/Metadata
- https://dev2.dataverse.org/Shibboleth.sso/DiscoFeed

I think I'm close. The docs I've edited so far are at https://dev2.dataverse.org/guides/build/html/installation/shibboleth.html

Unfortunately, I'm getting this:

Problem with Identity Provider – The SAML assertion for "eppn" was null. Please contact support. 

In the screenshots below @landreev will appreciate the Rick and Morty references!

<img width="1251" alt="Screen Shot 2019-11-27 at 11 29 26 AM" src="https://user-images.githubusercontent.com/21006/69741782-a4791d00-1109-11ea-9881-ea5cf85a9237.png">
<img width="1251" alt="Screen Shot 2019-11-27 at 11 29 30 AM" src="https://user-images.githubusercontent.com/21006/69741784-a4791d00-1109-11ea-9b52-52eb80fb0cc0.png">
<img width="1251" alt="Screen Shot 2019-11-27 at 11 29 38 AM" src="https://user-images.githubusercontent.com/21006/69741785-a4791d00-1109-11ea-8151-e0e8294e9679.png">
<img width="1251" alt="Screen Shot 2019-11-27 at 11 29 44 AM" src="https://user-images.githubusercontent.com/21006/69741786-a4791d00-1109-11ea-92f8-2287f5bbcbbe.png">
<img width="1251" alt="Screen Shot 2019-11-27 at 11 30 16 AM" src="https://user-images.githubusercontent.com/21006/69741787-a4791d00-1109-11ea-90f1-e42d19afa256.png">
<img width="1251" alt="Screen Shot 2019-11-27 at 11 30 29 AM" src="https://user-images.githubusercontent.com/21006/69741788-a4791d00-1109-11ea-8997-9b0e72ab6788.png">
<img width="1251" alt="Screen Shot 2019-11-27 at 11 30 38 AM" src="https://user-images.githubusercontent.com/21006/69741789-a4791d00-1109-11ea-80ae-3ab142aaf4f1.png">

**Comment by pdurbin** [comment]
Hmm, when I go to https://dev2.dataverse.org/Shibboleth.sso/Session I don't see many attributes:

```
Miscellaneous
Session Expiration (barring inactivity): 479 minute(s)
Client Address: 75.69.182.6
SSO Protocol: urn:oasis:names:tc:SAML:2.0:protocol
Identity Provider: https://samltest.id/saml/idp
Authentication Time: 2019-11-28T01:23:28.381Z
Authentication Context Class: urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport
Authentication Context Decl: (none)

Attributes
subject-id: rsanchez@samltest.id
```

**Comment by pdurbin** [comment]
Right, I forgot to mess with /etc/shibboleth/attribute-map.xml

I got it working but I had to change "subject-id" to "eppn". This reminds me of #1422.

I also commented out the part for attributes like "sn", "givenName", etc.

Now it's working. Here's a screenshot: 

<img width="1225" alt="Screen Shot 2019-11-27 at 8 33 14 PM" src="https://user-images.githubusercontent.com/21006/69770096-acf74500-1155-11ea-8f1a-bc359a4a05c4.png">


Now here's https://dev2.dataverse.org/Shibboleth.sso/Session

```
Miscellaneous
Session Expiration (barring inactivity): 479 minute(s)
Client Address: 75.69.182.6
SSO Protocol: urn:oasis:names:tc:SAML:2.0:protocol
Identity Provider: https://samltest.id/saml/idp
Authentication Time: 2019-11-28T01:23:28.381Z
Authentication Context Class: urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport
Authentication Context Decl: (none)

Attributes
displayName: Rick Sanchez
eppn: rsanchez@samltest.id
givenName: Rick
mail: rsanchez@samltest.id
sn: Sanchez
telephoneNumber: +1-555-555-5515
uid: rick
```

**Comment by pdurbin** [comment]
I just made pull request #6424

**Comment by xoroz** [comment]
Hello,

could someone  please share the attributes-map and shibboleth2.xml  to work with https://samltest.id/ we keep getting the eppn null error.

thank you

**Comment by pdurbin** [comment]
@xoroz yes, you can find them at https://github.com/IQSS/dataverse/pull/6424/files for now.

**Comment by xoroz** [comment]
thanks again Phill! 
our problem was at the glassfish side.
[METHODNAME: getAffiliation] [[
  Trying to get affiliation from disco feed URL: http://demo.dataverse.org/Shibboleth.sso/DiscoFeed]

 we fixed it by doing
/opt/glassfish4/bin/asadmin delete-jvm-options '-Ddataverse.siteUrl=http\://demo.dataverse.org' 
/opt/glassfish4/bin/asadmin create-jvm-options '-Ddataverse.siteUrl=https\://test-dataverse.our.local'

**Comment by pdurbin** [comment]
@xoroz interesting. If you think this is a bug, please open a new issue.

**Comment by carlo318** [comment]
Sadly   https://samltest.id/     is not working anymore, at least in Test IdP  and Test SP.

**Comment by pdurbin** [comment]
@carlo318 bah, that's a bummer. It sounds like we should remove it from our guides. If you want, please feel free to create a fresh issue about this!
