### ISSUE TITLE
Dashboard: Add an ingest widget that reports on ingests in progress and potentially flushes queue.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#6020]
We have recently experienced a heavy ingest load that caused some stability issues. In addition to potentially redesigning this functionality, including separating it, it would be good just to report on the ingest queue. This could be done with existing data and initially be very simple -for a specific web server, list number of files in process, number of files in queue, with timestamps, sizes, datasets. Potentially record this info for later review. There is also a jmsqueue flush function that could clear a queue if it is a problem and then provide lock cleanup and preserve a list for later reingest, potentially.

This list can be made even simpler -just list current files in queue but other features may be nice as well, depending on time available.

**Comment by donsizemore** [comment]
naughty user behavior report: we have openjdk security patches pending, so I killed our long-running Rserv processes (one of which seemed to be spinning). server.log reports:

```
[#|2019-07-23T09:26:40.369-0400|INFO|glassfish 4.1|edu.harvard.iq.dataverse.ingest.IngestMessageBean|_ThreadID=66;_ThreadName=p: thread-pool-1; w: 5;_TimeMillis=1563888400369;_LevelValue=800;|
  Unknown exception occurred  during ingest (supressed stack trace); re-setting ingest status.|#]

[#|2019-07-23T09:26:40.377-0400|INFO|glassfish 4.1|edu.harvard.iq.dataverse.ingest.IngestMessageBean|_ThreadID=66;_ThreadName=p: thread-pool-1; w: 5;_TimeMillis=1563888400377;_LevelValue=800;|
  trying to save datafile and the failed ingest report, id=7506685|#]
```

in this case we just want to delete the record anyway, so i'll poke around and see what i messed up in the database.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
