### ISSUE TITLE
Request Access can be invoked on Public Files

### ISSUE THREAD

**Issue by sekmiller** [IQSS/dataverse#6021]
If a user selects one or more public files from on the file list on the dataset and then presses "Request Access"  a record is created on the file access request table and a notification is sent to the dataset admin. (The "Request Access" button is validly available when the dataset contains one or more restricted files.)

The request access method is already smart enough to know not to create a new record in the request table when there's already a request by that user for that file, so we have to make it smart enough to know not to send a request for a public file (and prevent a notification.)

**Comment by sekmiller** [comment]
Also check the case where the file is restricted, but the user has already been granted file downloader permission one way or another.

**Comment by djbrooke** [comment]
- We have logic for how we handle cases where the request has already been generated
- No UI changes needed here
- We should not do any cleanup as part of this

**Comment by sekmiller** [comment]
@jggautier I tried the issue that you described where a dataset admin cannot grant access to a user if there's a mix of public and restricted files requested. I couldn't recreate it, but I did notice that the manage permissions page doesn't automatically refresh when the admin grants access.  The request is granted and if you manually refresh the page you'll see the request disappear from the page. If there's something else you're seeing, please let me know.

**Comment by sekmiller** [comment]
@jggautier - another test suggested by Gustavo shows that if you've already been granted access to a restricted file and you submit a second request there is an error thrown. Part of my plan for the fix was to verify that the requestor doesn't have download permission before submitting a request so that should fix it.

**Comment by jggautier** [comment]
Ah, yes. Thanks! I think that second test is what I meant, and it's what happened in [this Dataverse support ticket](https://help.hmdc.harvard.edu/Ticket/Display.html?id=278512):
- A dataset has 5 restricted files.
- Requestor requests access to 1 restricted file.
- Dataset admin approves request, so requestor has access to that one file now.
- Requestor then requests access to all 5 restricted files, one of which she already has access to.
- Dataset admin tries approve request but can't. The Grant button is unresponsive.
- If you remove from the request the one file the requestor already has access to, the Grant button works and the dataset admin is able to grant access to the remaining four files.

**Comment by sekmiller** [comment]
For testing:
Requesting access for a public file via the UI, which is possible if there's a mix of public and restricted files, should not create a request(nor does it inform the user "hey dummy! this file is public"). Must verify absence of request via DB query. 
Similarly requesting access to a file where you already have download permission should not create a request. again, Must verify via DB query.

making either of these requests for access via the API should return a message of "You may not request access to this file. It may already be available to you." or something similar.

**Comment by kcondon** [comment]
Works except for when using UI either on public file or already granted, still sends notification, though does not create db record.
