### ISSUE TITLE
Extend validation API to optionally validate down to the variable level

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#6026]
Code change needed from https://github.com/IQSS/dataverse.harvard.edu/issues/4

**Comment by djbrooke** [comment]
- We have metadata validation API for datasets. We should add an option to run this validation at the file and variable level as well. 
- This should only apply to old datafiles and variables as our ingest process now has these validations built in
- We don't expect this to be intensive

**Comment by landreev** [comment]
@kcondon 
A good way to test this would be to replicate the real condition we had in production - create an invalid DataVariable object by setting the name to null. Then run the validation API on the dataset that owns the tabular file. 
The default behavior should be as before - it will report that the dataset is valid. (assuming all the dataset/version/file-level metadata entries are valid). 
But with the new optional "variables=true" flag, it will validate the tabular data-level metadata as well - and should detect and report the problem.

**Comment by sekmiller** [comment]
@landreev can you write that as an integration test? The test file "stata13-auto-withstrls.dta" has a null DataVariable name which was causing the MergeAccounts integration test to fail.

**Comment by sekmiller** [comment]
Sorry @landreev, I was conflating two issues. We recently fixed an issue where the export was failing because the variable label was missing (https://github.com/IQSS/dataverse/issues/6027).
