### ISSUE TITLE
Re-evaluate metadata blocks, metadata display, help, and metadata sources

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#6030]
As Dataverse expands to new disciplines and as we seek new ways to ensure high quality metadata, we should take an opportunity to discuss where we can make some improvements. We’ve had good feedback from the community across several issues (#5938, #6003, #3622, #6000, #4772, #350, #2603, #4282), which I’ve tried to capture as use cases below. 

- I want depositors to select subjects more appropriate to the discipline(s) the dataverse installation supports
- I want depositors to select contributor types more appropriate to the disciplines the dataverse installation supports
- I want depositors to select from a list of people provided by LDAP (or another system) for fields such as author, contributor, producer
- I want depositors to be presented with the most appropriate experience (dropdown, checkbox, autocomplete) for selecting/populating metadata values
- I want depositors to be able to select from metadata options provided by an API instead of from hard coded values
- I want depositors to be able to select multiple fields for certain metadata elements

This issue will focus on proposing a solution to cover as many of these use cases as possible (and others that I'm sure I'm missing) instead of trying to push forward individual issues.

**Comment by RightInTwo** [comment]
Awwww yisss, let's get the party started! 
![image](https://user-images.githubusercontent.com/12545221/61416753-1c7e3d80-a8f5-11e9-94f6-cbcf7f833afb.png)

**Comment by doigl** [comment]
May I add to the list:

- I want a possibility to index numerical values for some metadata fields and add range-filter search facets for these fields

**Comment by qqmyers** [comment]
FWIW: Clowder has implemented this type of functionality, pulling controlled vocabulary from external services or static json lists posted to a URL. In their case, I think the semantic term and value are recorded, but not the provenance of when the vocab choices were retrieved. The GUI just presents pull down lists or autocompletes for these terms rather than a type-in.
If anyone wants pointers to look at their GUI for this or to hear more about the implementation, let me know.

**Comment by pdurbin** [comment]
@qqmyers is there a demo site for Clowder so we can play around with the UI? And get a sense of the UX?

**Comment by qqmyers** [comment]
They have an official demo site, but I'd suggest https://sead2.ncsa.illinois.edu/ where I know what features are turned on.

**Comment by mheppler** [comment]
Had a brief discussion in design mtg today about the potential for a consistent application support of markdown in areas such as metadata block help text (#6476), as well as metadata values entered by dataset creators (#6383) and even dataverse descriptions (no specific issue yet, but this one is kinda sorted related #1249). Adding note here of proposed project synergy per request from @TaniaSchlatter.

**Comment by RightInTwo** [comment]
I updated #4772 with some slides from the Flexible Metadata session at DCM2020 as input for this issue.

**Comment by BPeuch** [comment]
Hello everybody,

I was wondering if "checkbox" as a new field type has already been suggested? I couldn't find an open issue specifically referring to this, but I do see the word mentioned in djbrooke's original post in this here issue.

This would be great for adding fields that require users to mark their consent to or agreement with declarations such as "Provided my dataset contains personal data, I hereby declare that I have secured the consent of participants to publishing their information…"

**Comment by pdurbin** [comment]
@BPeuch yes, there is the following issue (and some discussion on the mailing list linked from there):

- Custom Metadata: support boolean values #7961

**Comment by BPeuch** [comment]
Aaah indeed, I forgot to look it up with "boolean" as a keyword! Thanks a lot, @pdurbin

**Comment by pdurbin** [comment]
> FWIW: Clowder has implemented this type of functionality, pulling controlled vocabulary from external services or static json lists posted to a URL.

Dataverse has this now too: https://guides.dataverse.org/en/5.12/admin/metadatacustomization.html#using-external-vocabulary-services

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
