### ISSUE TITLE
Bootstrap 5 Upgrade

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#6045]
We should upgrade to Bootstrap 4.

**Comment by djbrooke** [comment]
Approach to discuss:

- Investigate ability to phase in the changes page by page, login page or advanced search may be good candidates. As part of this, investigate whether or not the pages could be released page by page.
- If investigation indicates this is the appropriate path forward, then get a list of the pages in the application and start working through them.

**Comment by TaniaSchlatter** [comment]
Good discussion with @mheppler. The technical effort to support two UI frameworks in the same app in order to slowly transition from Bootstrap 3 and 4 should not be necessary, and would be a throwaway effort. Small chunks can be used to carved up the ~20 pgs of the app in the development process, and released together. Alternate, single release approach:
- develop new front end code page templates in Bootstrap 4 for the new redesigned dataset and file page 
- apply the same page layout and various style changes to all pages and review
- release the new Bootstrap 4 UI for all pages together

**Comment by TaniaSchlatter** [comment]
High-level overview of Bootstrap 4 and accessibility. It is not surprising from what I have seen, but disappointing that Bootstrap 4 default colors lead to _insufficient_ color contrast using WCAG 2.0 standards. https://getbootstrap.com/docs/4.0/getting-started/accessibility/

**Comment by mheppler** [comment]
Recently I have suggested a few deliverables could be included in this app-wide UI effort. Adding those hear for reference and discussion.

- configurable custom Bootstrap themes, making it easier to apply branded color schemes to button, link and other UI components
- right-to-left language support
- selenium automated testing selector support

**Comment by BPeuch** [comment]
Howdy-do, IQSS crew.

We like the potentialities afforded by Bootstrap 4 a lot, so we fully support the upgrade. Good luck!

How are things coming so far?

**Comment by djbrooke** [comment]
Hey @BPeuch, this isn't something that we've started yet. Just wondering, can you let us know what things you're interested about specifically?

**Comment by youssefOuahalou** [comment]
Hello @djbrooke  our web designer strongly advised us to do this update. Do you think this tool can help you? : http://upgrade-bootstrap.bootply.com/

**Comment by djbrooke** [comment]
Thanks @youssefOuahalou, we'll take a look. This is a pretty big change that requires touching most of the pages in the application, so we haven't had a chance to plan and work on it yet. Watch this space! :)

**Comment by BPeuch** [comment]
Thank you for the feedback, @djbrooke. Our Web designer further mentioned the following Bootstrap 4 features she found most interesting: flexboxes and the grid system in general, cards, CSS classes for margins and padding. Those are but a few.

**Comment by pdurbin** [comment]
Bootstrap 5 came out in 2021. I guess we should update the title.

**Comment by pdurbin** [comment]
The new frontend ( https://github.com/IQSS/dataverse-frontend ) is already using Bootstrap 5! 🎉  Closing.
