### ISSUE TITLE
Revisit "Edit in Progress" lock

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#6046]
In #5550/#5551 we added a new lock for "Edit in Progress." There was some good discussion in the issue about whether or not this lock was needed and we decided to merge it. Since upgrading to 4.15, which included this change, our support team has had to clear out Edit in Progress locks several times a day on Harvard Dataverse. I'd like to either:

- Remove the lock from the code base 
- Make code changes that reduce the number of locks that occur in a production environment like Harvard Dataverse 

Let's discuss, look at some prod logs, and make a decision about the next step.

**Comment by pdurbin** [comment]
Related: "Edit In Progress" lock remains forever when a tabluar file is uploaded and going through ingest while a second file is uploaded via native API #5979

**Comment by qqmyers** [comment]
@pdurbin I think this is just the bug that we talked about/that I promised a fix for. I haven't gotten back to merging with 4.15.1 to pull out the fix, but I'll try to prioritize that this week...

**Comment by pdurbin** [comment]
@qqmyers right. I forgot we talked at http://irclog.iq.harvard.edu/dataverse/2019-06-27#i_99151 and you reminded me that you and @sekmiller talked about related bugs at https://github.com/IQSS/dataverse/issues/5847#issuecomment-497716243

If you're saying you have a fix that you're running in production that you could easily pull out, I'd be interested in taking a look.

**Comment by qqmyers** [comment]
@pdurbin - I haven't merged with 4.15+ yet, but I think this PR should work with the latest code. If it does, the underlying issue was that a failure prior to savedDataset being set was causing the finally clause to get a null pointer exception and therefore to fail in unsetting the lock. Making the check and unsetting the lock on the original (theDataset) instead should fix that.

If not, I won't have a good way to test/fix until I get all of the other 4.15 changes integrated.

**Comment by djbrooke** [comment]
Thanks @qqmyers and @pdurbin. I took a look at a few of the datasets in Harvard Dataverse that had issues and most of them have tabular files, one has a shapefile zip, and another just has a non-shapefile zip. Would we expect this fix handle all of those cases, or just the two cases where an ingest would take place?

**Comment by qqmyers** [comment]
@djbrooke - All this fix should do is make sure that the lock is released when whatever issue involving ingest causes a problem. It doesn't address the initial situation, but it should stop people from having to manually remove locks. I think (haven't looked recently so may be off) ingest in general is not monitoring or setting a lock, so if someone manually edits the dataset while ingest is still happening, the ingest and manual update can cause conflicting changes and for one of them to then fail. Making ingest edit lock aware should solve that.

**Comment by djbrooke** [comment]
>  but it should stop people from having to manually remove locks.

Great! Thanks. I'm going to close this and update the PR to point here and to #5979, which has some good steps to reproduce this.
