### ISSUE TITLE
Performance: Very sluggish page load when languages and all facets enabled in root dv.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#6052]
While testing a recent language change, it was discovered that when all facets in root dv are enabled and languages are enabled, dataverse page take up to 30s to load. When languages are not defined but all facets are enabled, there is no slow down. This is happening in the v4.15.1 release as well.

Should also note that page load slows from 3s to 7s when language is enabled without change to facets.

**Comment by djbrooke** [comment]
- We will investigate this and may revisit if the fix is larger than we expect.

**Comment by jri-sp** [comment]
Hi, 
I don't know if this is related to the same issue, but on a fresh install of v.4.15.1, I also have a performance issue.
I also have activated languages. 
I don't have any dataverse, dataset or data in it yet.

When I'm not logged, the page load in 500ms (avg) and once logged the page takes between 5-10 seconds to be fully loaded.

My server have 8Gb of RAM and 8 CPUs. Xmx for Dataverse JVM is set to 4096m and 1024m for Solr. And I don't have any visitor or user for now or any load.
I don't have this issue with an another older installation with similiar hardware and JVM config.

So I'm following this issue :)
Tell me if I can be useful.

**Comment by scolapasta** [comment]
Hi @jri-sp do you know specifically which earlier version you were using that did not have the issue? And did it have have multiple languages enabled at the time?

This info will help us pinpoint when the issue got introduced.

**Comment by jri-sp** [comment]
Hi @scolapasta unfortunately I don't know if it will help you... It's v4.8.5. Quite old now and there were many changes, so it's probably not relevant for you.
It was more to say that I didn't seen an issue like that before and I don't really know how to find the bottleneck.

Still available to help or test stuff about that. We've a staging installation with the problem so we can change it easily.

**Comment by pdurbin** [comment]
> When I'm not logged, the page load in 500ms (avg) and once logged the page takes between 5-10 seconds to be fully loaded.

@jri-sp Wow, that's a dramatic difference. How many datasets do you have?

**Comment by jri-sp** [comment]
Hi @pdurbin !
For now we have 5 dataverses and 0 dataset. It's a fresh installation for testing purposes, there is no data yet.

**Comment by JayanthyChengan** [comment]
Hi @pdurbin :  I also experienced the performance of page load very slow when the language is defined and when the language files are stored in any directory on disk, 
http://guides.dataverse.org/en/latest/installation/config.html#internationalization

Instead, if the property files are moved inside <glassfish-install-dir>/glassfish/domains/<domain-name>/lib/classes and modify BundleUtil.java, the performance was improved.
Please find the correction in PR #6332 .

These are the steps to be followed :

1.	Delete the old jvm option for dataverse.lang.directory and set the jvm option:

/usr/local/glassfish4/glassfish/bin/asadmin  create-jvm-options  “-Ddataverse.lang.directory=<glassfish-install-dir>/glassfish/domains/<domain-name>/lib/classes“


2.	Copy the languages property files into <glassfish-install-dir>/glassfish/domains/<domain-name>/lib/classes directory

**Comment by tcoupin** [comment]
Same issue on dataverse.ird.fr:
- with dataverse.lang.directory: 5s to load page
- without dataverse.lang.directory: <1s

**Comment by poikilotherm** [comment]
Ok I have done some profiling.

So far, this only seems to be a problem when accessing a Dataverse, either in view or edit mode.
Accessing a Dataset does not seem to be affected.

I can see that `SearchIncludeFragment.search()` uses a lot of time, getting these localized fields from the bundle at `ResourceBundle.findBundle()`. My wild guess: caching issue.

Normally the bundles should be loaded once, [getting cached by default](https://docs.oracle.com/javase/8/docs/api/java/util/ResourceBundle.html). Somehow, this does not work here and I don't have an idea yet why.

Bundle loading is done lots of times, see below. Does that number 45 or 46 reflect the number of facets/fields?

![grafik](https://user-images.githubusercontent.com/5468333/68236072-be40ac00-0004-11ea-9c1c-9f565fefd9a8.png)

Please find my profiling snapshots created with VisualVM at FileBin: https://filebin.net/4g6iqmmt5dqgkoup (this link will expire in 1 week)

**Comment by pdurbin** [comment]
@JayanthyChengan hi! Can you please read through the conversation @poikilotherm and I just had at http://irclog.iq.harvard.edu/dataverse/2019-11-05#i_111818 ? Thanks!! 😄

**Comment by pdurbin** [comment]
@JayanthyChengan hi! I'm just checking in. This issue isn't assigned to you. Should it be? I see it got pulled out of a sprint. This feels like an important issue to me. I've been thinking that maybe we should add multiple languages to the AWS EC2 instances running Dataverse that we spin up for testing. That way, more of us would see or feel the performance problem reported here.

**Comment by JayanthyChengan** [comment]
@pdurbin - Yes, its an important issue and at SP we just added the workaround as mentioned in PR #6332 . Currently I am busy with Canarie Project (large file upload feature).

**Comment by tcoupin** [comment]
@pdurbin did you see my PR #6428  ?

**Comment by pdurbin** [comment]
@tcoupin no! I missed it! I just moved it to code review. Thanks!

@JayanthyChengan thanks for the update! I just unassigned you from #6332. If you need any help with the large data upload project, please let us know!

**Comment by JayanthyChengan** [comment]
Thanks.
