### ISSUE TITLE
Investigate NULL values in DataVariable Labels

### ISSUE THREAD

**Issue by sekmiller** [IQSS/dataverse#6065]
In https://github.com/IQSS/dataverse/issues/6027 we addressed an issue where NULL values in DataVariable labels caused the export to fail.  As a follow-up to that we should investigate if the DDI exporter should handle NULL labels in a different way or if in fact labels should be allowed to be null.  Data Variable names already have a NotBlank Bean Validation.

**Comment by djbrooke** [comment]
@jggautier - do you have any thoughts here from a metadata interoperability perspective?

**Comment by sekmiller** [comment]
After discussing with @jggautier and @scolapasta we have determined that it is working as designed. Closing.
