### ISSUE TITLE
Make Guestbook Entries available at the Dataset Level

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#6069]
This issue is to generate discussion based on the post from @shlake at https://groups.google.com/forum/#!topic/dataverse-community/FHvDtu7BYaE. 

I think it's kind of weird that Dataverse currently allows people to enable guestbooks on their datasets but doesn't allow them to see the entries that visitors create and I feel that Sherry brings up a common use case. This decision predates me so I'm wondering if this was a conscious decision, an oversight, or some cut scope. 

Discussion welcome...

**Comment by pdurbin** [comment]
>  This decision predates me so I'm wondering if this was a conscious decision

The place to look is the "Guestbook/Metrics/Tracking Data" folder at https://drive.google.com/drive/folders/0B3_V6vFxEcx-Wng1UzVjX3ZBUGM?usp=sharing

In that folder there are two documents from the Dataverse 4 rewrite:

- Guestbook Design Document: https://docs.google.com/document/d/1CpzpqC__aOSoSk8JvRcz0bwQNBuaVE_XKXa2bHGb8Cw/edit?usp=sharing
- Guestbook Functional Requirements Document: https://docs.google.com/document/d/1hoBitVmYXJVQep__fKr1sE1xD6jDofxqfILbMPLGu-k/edit?usp=sharing

There is also some discussion of original design decisions in this issue: License & Terms Dataset Page Tab: Guestbook, Use & Access Requirements #701

**Comment by pdurbin** [comment]
Yes, this is weird. No discussion has happened here. 

@shlake three plus years later, are you interested in championing this cause? If so, would you consider creating a fresh issue in your own words? Or should we keep discussing in the email thread you started? @sbarbosadataverse weighed in, which is nice. Or elsewhere? A community call?

This issue feels a bit stale and I'm tempted to vote to close if there's little interest in it.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
