### ISSUE TITLE
Dependency update: Apache Common Lang v2 -> v3

### ISSUE THREAD

**Issue by poikilotherm** [IQSS/dataverse#6070]
This is related to my other dependency housekeeping things. See #5288 and #5360.

----

While programming unit tests for #6000, I wanted to use `org.apache.commons.lang3.RandomStringUtils`. In Maven POM I saw that Dataverse is still on [`org.apache.commons.lang` v2.6](https://mvnrepository.com/artifact/org.apache.commons/commons-lang/2.6), which is dead since 2011, when 3.0 was released.
See also: http://www.h-online.com/open/news/item/Apache-Commons-Lang-3-0-makes-a-break-with-the-past-1283761.html

Dataverse uses a lot of Commons Lang stuff. It should be refactored to use v3 of the lib, which gets included anyway, as it is a dep of `com.lyncode:xoai-common`. (see `mvn dependency:tree`, grepping for `commons-lang`). Nothing else is relying on the v2 lib.

Notes about upgrading from upstream project: https://commons.apache.org/proper/commons-lang/article3_0.html

**Comment by djbrooke** [comment]
Hi @poikilotherm, do you plan to work on this one or should I keep it unassigned?

**Comment by poikilotherm** [comment]
I can submit a PR, but I thought about discussing this first? Maybe there is some technical issue with this or you guys want smaller chunks or whatever... 

Just wanted to be polite, ask and discuss before I do... :wink:

If you @djbrooke want me to work on this and everybody at IQSS is fine with that, this should be a rather small thing to do...

**Comment by pdurbin** [comment]
@poikilotherm I'm wondering if we should wait until we delete the all the locally build jars in "local_lib/com/lyncode" from the codebase before we take on this refactoring. These jars: https://github.com/IQSS/dataverse/tree/v4.15.1/local_lib/com/lyncode

I found these by reading this comment in the pom.xml:

        </dependency>
        
        
        
        
        
        
        <dependency>
            <groupId>com.lyncode</groupId>
            <artifactId>xoai-common</artifactId>
            <version>4.1.0-header-patch</version>
        </dependency>

What I'm trying to say is that maybe we should just stick with the v2 version (unless there's a security issue) until we have time to move completely to v3. As I said in this issue, I'm worried about the war file getting bigger and bigger: Increasingly slow feedback loop for developers, increasingly large WAR files #5593

**Comment by pdurbin** [comment]
Whoops, I had some misunderstanding but @poikilotherm set me straight at http://irclog.iq.harvard.edu/dataverse/2019-08-06#i_102177

I'd like to back up to what problem we're trying to solve here.

Originally, @poikilotherm said he'd like to use v3 of Apache Common Lang. As he stated above, v3 is already available in Dataverse because is it pulled in as a transitive dependency. He **could** use v3 right now but it's a bad practice to write code that relies on a transitive dependency. We **could** declare v3 as an explicit dependency in the pom and keep v2 in there as well but this is not desirable to @poikilotherm . He would rather change the version in the pom from v2 to v3.

The second problem @poikilotherm is trying to solve is that v2 is old. It's flagged as "legacy" by its developers. I assume Dataverse has a lot of old dependencies like this. I don't know if there is any immediate risk in this case. I don't know of any security problems or anything.

The third problem @poikilotherm is trying to solve is to help get the war file to be smaller. It is unknown how much smaller the war file will become.

Those are the benefits. What are the costs or risks? There's @poikilotherm 's valuable time, of course, and he estimates that 87 Java files will be affected. That seems like a lot to me but he said he's willing to provide a list of what to test to QA. I guess we'll see how long that list before we can guess how much of a QA effort this will become.

I'm not personally very enthusiastic about the benefits above (no new features or bug fixes) but if @poikilotherm wants to go ahead and make a pull request and summarize what features need to be tested, I'm happy to review it.

**Comment by poikilotherm** [comment]
Alright, my findings so far in [develop@09fe94bd](https://github.com/IQSS/dataverse/commit/09fe94bdc6f4f5e79c61a203b7df8736692657ea):

__Occurences of Apache Commons Lang V3__
```shell
find src/main/java src/test/java -name '*.java' -exec grep "commons\.lang3\." {} \; | sort | uniq -c | sort -n
      1 import org.apache.commons.lang3.math.NumberUtils;
      1 import org.apache.commons.lang3.StringUtils;
      1 import org.apache.commons.lang3.text.WordUtils;
      3 import org.apache.commons.lang3.StringUtils;
```
So there is already bad code in place: usage of a transitive dependency...

__Occurences of Apache Commons V2__
```shell
$ find src/main/java src/test/java -name '*.java' -exec grep "commons\.lang\." {} \; | sort | uniq -c | sort -n
      1 import org.apache.commons.lang.ArrayUtils;
      1 import org.apache.commons.lang.builder.*;
      1 import org.apache.commons.lang.builder.ToStringBuilder;
      1 import org.apache.commons.lang.builder.ToStringStyle;
      1 import org.apache.commons.lang.mutable.MutableBoolean;
      1 import org.apache.commons.lang.mutable.MutableLong;
      1 import org.apache.commons.lang.NotImplementedException;
      1 import static org.apache.commons.lang.StringUtils.isEmpty;
      2 import static org.apache.commons.lang.StringUtils.isNumeric;
      4 import org.apache.commons.lang.RandomStringUtils;
      8 import org.apache.commons.lang.StringEscapeUtils;
      9 import org.apache.commons.lang.*;
     56 import org.apache.commons.lang.StringUtils;
```

__Classes using Apache Commons Lang V2__ (81 files affected)
```shell
$ find src/main/java src/test/java -name '*.java' -exec grep -l "commons\.lang\." {} \; | sort -f | cut -f2,8- -d"/"
main/api/AbstractApiBean.java
main/api/datadeposit/SwordServiceBean.java
main/api/datadeposit/UrlManager.java
main/api/DatasetFieldServiceApi.java
main/api/Groups.java
main/api/HarvestingServer.java
main/api/imports/ImportDDIServiceBean.java
main/api/imports/ImportServiceBean.java
main/api/Search.java
main/authorization/AuthTestDataServiceBean.java
main/authorization/DataverseRolePermissionHelper.java
main/authorization/providers/builtin/DataverseUserPage.java
main/authorization/providers/builtin/PasswordEncryption.java
main/dataaccess/TabularSubsetGenerator.java
main/DataCitation.java
main/DataFileServiceBean.java
main/DataFileTag.java
main/DatasetField.java
main/DatasetFieldCompoundValue.java
main/DatasetFieldValidator.java
main/DatasetFieldValue.java
main/DatasetFieldValueValidator.java
main/DatasetPage.java
main/DatasetServiceBean.java
main/datasetutility/AddReplaceFileHelper.java
main/DatasetVersionDifference.java
main/DatasetVersionServiceBean.java
main/DataverseHeaderFragment.java
main/DataversePage.java
main/DOIDataCiteRegisterService.java
main/DvObjectServiceBean.java
main/EditDatafilesPage.java
main/engine/command/impl/ImportDatasetCommand.java
main/Guestbook.java
main/GuestbookPage.java
main/HandlenetServiceBean.java
main/harvest/client/HarvesterServiceBean.java
main/harvest/client/oai/OaiHandler.java
main/harvest/server/web/servlet/OAIServlet.java
main/HarvestingClientsPage.java
main/HarvestingSetsPage.java
main/ingest/IngestableDataChecker.java
main/ingest/tabulardata/impl/plugins/csv/CSVFileReader.java
main/ingest/tabulardata/impl/plugins/dta/DTAFileReader.java
main/ingest/tabulardata/impl/plugins/dta/NewDTAFileReader.java
main/ingest/tabulardata/impl/plugins/por/PORFileReader.java
main/ingest/tabulardata/impl/plugins/rdata/RDATAFileReader.java
main/ingest/tabulardata/impl/plugins/rdata/RTabFileParser.java
main/ingest/tabulardata/impl/plugins/sav/SAVFileReader.java
main/ingest/tabulardata/impl/plugins/xlsx/XLSXFileReader.java
main/ingest/tabulardata/InvalidData.java
main/MailServiceBean.java
main/ManageFilePermissionsPage.java
main/ManageGroupsPage.java
main/ManagePermissionsPage.java
main/mydata/DataRetrieverAPI.java
main/mydata/MyDataFilterParams.java
main/mydata/MyDataFinder.java
main/mydata/RoleTagRetriever.java
main/mydata/SolrQueryFormatter.java
main/NavigationWrapper.java
main/passwordreset/PasswordResetPage.java
main/RoleAssigneeServiceBean.java
main/RolePermissionFragment.java
main/rserve/RemoteDataFrameService.java
main/rserve/RJobRequest.java
main/rserve/VariableNameCheckerForR.java
main/search/AdvancedSearchPage.java
main/search/IndexServiceBean.java
main/search/SearchIncludeFragment.java
main/search/SearchUtil.java
main/ThemeWidgetFragment.java
main/UserServiceBean.java
main/util/FileSortFieldAndOrder.java
main/util/MarkupChecker.java
main/util/SumStatCalculator.java
main/validation/PasswordValidatorUtil.java
test/api/DatasetsIT.java
test/DataCitationTest.java
test/mydata/SolrQueryFormatterTest.java
test/validation/PasswordValidatorTest.java
```

**Comment by poikilotherm** [comment]
I just created a PR for this, as I want to use stuff from Lang3 (see PR).
Looks like there is a bug hiding in the CSV ingest code. Would appreciate some help with this. Thx.
