### ISSUE TITLE
File Tags - Improve UI/UX and misc. bugs

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#6074]
With the addition of DataTags #871 to the UI, we plan to revisit File Tags (including custom and tabular), to improve the UI displaying them, UX of adding them, as well as fix some minor bugs.

_FEATURES_
- File Tabular Tags - Tags applied in DRAFT version displayed in published version #3429
- File Tags: Batch update should be incremental, not specify all tags as a set. #3010
- UI to enable file tags to be searched #4122
- File Landing Page: Add Edit Tags to the edit list button. #3488
- Edit Files: No Batch Tag Button on Edit Files Metadata Page #2842

_BUGS_
- Files Tab: Tabular data tags are not sorted. #2808
- Tags Attack! Tag Uniqueness is not enforced, resulting in multiples in select list and assigned in db. #5002
- Dataset Version - Missing summary and view differences details #5510
- Save on Upload error: Upload 3 files at once with descriptions and custom tags results in exception. #4918
- Dataset: Creating a draft dataset from published version fails with some file metadata changes. #3482

![Screen Shot 2019-08-06 at 10 56 39 AM](https://user-images.githubusercontent.com/687227/62550830-e9b2cf80-b838-11e9-93a4-69897c35088f.png)

**Comment by djbrooke** [comment]
Met with @TaniaSchlatter @scolapasta and @mheppler about this earlier today. The plan is for @mheppler and @scolapasta to discuss and line up some issues (whether from the list above or some consolidation) for future sprints.

**Comment by scolapasta** [comment]
Discussed at design meeting with @mheppler @kcondon @djbrooke . Some of these were closed, some got moved to Up Next, some to needs discussion. (and a new one was created #7194 )

Closing this consolidation issue out.
