### ISSUE TITLE
UI - Bootstrap 3.4.1 Upgrade

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#6076]
With recent security patches to Bootstrap 3, we should upgrade from 3.3.7 to the most recent release 3.4.1.

**Comment by mheppler** [comment]
PR submitted for `6076-bootstrap-3-4-1-upgrade` branch. Moving to code review.

Included are:

- Added new Bootstrap 3.4.1 and jQuery 3.4.1 library files, removed previous versions
- Fixed link in `widgets.js` that linked to outdated jQuery library
- Removed outdated analytics code from guides
- Fixed warning for `navbarscroll.js` (guides) related to jQuery conflicts
- Fixed warning for `favicondataverse.png` (guides) related to bad path

**Comment by kcondon** [comment]
This appears all set but will check with Mike on Monday.
