### ISSUE TITLE
Documentation: Some tweaks to Make Data Count doc based on recent experience.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#6082]
While configuring MDC for use recently, encountered a few points that might be addressed or improved upon:

1. Make it clear where to start the installation workflow
Should always start in Installation Guide, prerequisites if installing Counter Processor manually.
-Perhaps indicate in Admin and Developer guides that if you are installing Counter Processor manually or if this is a production or non dev instance, begin with instructions in Prerequisites. 
2. Dataverse currently only supports Counter Processor v0.0.1, won't work with other versions
-Make this note clear, and to follow CP installation instructions under Prerequisites rather than from the CP project, which would result in a different version.
3. Be more emphatic about disabling uploading MDC stats to DataCite if any Handles exist on local instance.
Uploading MDC stats to DataCite will not work if Handles exist on your Dataverse and are part of the activity report. DataCite will reject any such report in entirety so if Handles exist, even in a mixed handle/doi situation, either replace them with DOIs or disable upload to hub/DataCite.

**Comment by pdurbin** [comment]
We can open a fresh issue after we work on this:

- https://github.com/IQSS/dataverse.harvard.edu/issues/3
