### ISSUE TITLE
documentation: update Native API examples

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#6083]
Related to #2174 and #930 and #1381 but focusing on a smaller chunk: the Native API examples in http://guides.dataverse.org/en/latest/api/native-api.html are sometimes complete, sometimes make assumptions of the user, and in a few cases contradict one another.

A rising graduate student here would like to learn more about Dataverse, Git, and contributing code to open source, so she's agreed to graciously test and update curl examples. Pull request forthcoming.

**Comment by pdurbin** [comment]
@donsizemore fantastic! Please be aware that if she starts immediately, she's very likely to encourage merge conflicts with the improvements I'm hoping to make to the API Guide before my talk on Tuesday: https://groups.google.com/d/msg/dataverse-community/V5WkMGDS4VI/maxXTdmzDwAJ

It could be a good opportunity to learn about how to resolve merge conflicts, I suppose. 😄 

Also, once we know her GitHub username, we can add her to https://github.com/orgs/IQSS/teams/dataverse-readonly/members , assign this issue to her, and move it to the "Community Dev" column on our board at https://github.com/orgs/IQSS/projects/2 . This helps us remember what people are working on. 😄

**Comment by pdurbin** [comment]
@donsizemore hi! Would you and/or the rising graduate student like to review pull request #6107 ? I rewrote a few of the curl commands in the Native API section and I hope you like the direction I'm taking. 😄 Feedback welcome!

**Comment by donsizemore** [comment]
In the spirit of "small chunk" updates, I'm closing this in favor of tickets to accompany smaller batches of documentation changes, say updating the example syntax in the "Dataverses" section, then Datasets, and so on.
