### ISSUE TITLE
File Preview Updates on Current File Page

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#6089]
Building on the branch available from the recent spike (#6048), we should enable a file preview from an external previewer to appear in the desired size under the file metadata tab on the file page. We will also need to take into account the view for those file types where previewers do not exist. 

This intermediate step is part of the continued effort to deliver the Dataset and File Redesign (#3404) in stages, that is, it will allow users to take advantage of expanded preview options while at the same time building infrastructure that the file page redesign will use.

While not necessary for completing this, I think it would be nice to pick at least one of the previewers on https://github.com/QualitativeDataRepository/dataverse-previewers (heads up @qqmyers) and make changes so that we can display it on the File Page in the preferred way.

**Comment by TaniaSchlatter** [comment]
Related information about file preview types: #3758 File preview on the file page only.

**Comment by djbrooke** [comment]
Closing in favor of #3758, we'll move that one forward instead.

**Comment by pdurbin** [comment]
Here comes an assist to close this issue. :basketball:
