### ISSUE TITLE
File metadata updates not reindexed

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#6092]
On v4.15.1 (demo.dataverse.org today and locally), it looks to me like edits of file metadata (I checked name and category tags specifically) are not being reindexed, which manifests itself as searches failing to find files by their updated name and the Filter by Tag facet either not appearing or not adding a new tag. It does look like file metadata is being indexed during upload (so I can make the Filter by tag facet appear by adding tags during upload, but subsequent tag edits don't change anything).

Any guidance /help appreciated. Otherwise, I'll start looking into the code.

**Comment by qqmyers** [comment]
I think this is limited to edits made from the file page. Those appear to go through EditDatafilepage's save() method without invoking a command or reindexing directly. 

Also - I see evidence that the reidex command being commented out for #4425 (https://github.com/IQSS/dataverse/blame/develop/src/main/java/edu/harvard/iq/dataverse/EditDatafilesPage.java#L1437) is actually used when you select add metadata for files selected on the dataset page and then use the edit/tag dialog after that. I.e. removing that line should be causing a similar bug in dev and will affect post 4.15.1 releases if not reverted.

I can put in a fix for both issues if that's useful.

**Comment by pdurbin** [comment]
@qqmyers yes, please fix all the bugs. If you have any question, please don't hesitate to ask!

It sounds like we need more API tests. There are some search/index related tests in "SearchIT": https://github.com/IQSS/dataverse/blob/v4.15.1/src/test/java/edu/harvard/iq/dataverse/api/SearchIT.java
