### ISSUE TITLE
Refactoring: Have check for whether to index files use same code as version differences

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#6099]
#6096 is a simple change to catch labels for reindexing of files when changed. We already have similar logic in version differences. Rather than have these in two places, we should have the indexing check use the version differences code so that if/when we need to change the logic it only happens in the one place.

**Comment by sekmiller** [comment]
Testing is kind of subtle. Make sure that when you edit a file creating a new draft that the changes to the file are reflected in the indexing of the new draft. (or updated existing draft.)
