### ISSUE TITLE
Make download all files feature more prominent

### ISSUE THREAD

**Issue by philippconzett** [IQSS/dataverse#6118]
As a user / file downloader I'd like to have the download all files feature to be more prominent. Currently, this option only appears after ticking the box "1 to X Files of Y Files" on the top of the file table. A possible solution would be to describe the selection boxes more explicitly and have two selection boxes, one box to select all the files in the file table currently displayed on the page, and another selection box to select all the files in the dataset; see the following illustration:

![image](https://user-images.githubusercontent.com/21955790/63705446-7398fb80-c82d-11e9-81a8-626049367769.png)

For datasets with less than the minimal number of displayed files on one page (10 files?) the two selection boxes would obviously select the same amount of files, i.e. all files in the dataset.

**Comment by TaniaSchlatter** [comment]
Thanks for opening the issue and including the mockup, @philippconzett. I agree that what you propose is more helpful for people who want to download all files, when there are more than 10 in a dataset.

**Comment by mheppler** [comment]
Discussed this issue with the team, to get a download link displayed in the dropdown menu for the new Access Dataset btn at the top of the dataset pg, included in the new UI changes in issue #6684. This will be more prominent and simpler than adding more checkboxes. That said, improvements to the file table can be included, such as the checkbox selection functionality can be improve by describing the selection boxes more explicitly, as suggested (and also mocked up in #6605).

Here is an outline of the new feature:
- New options for “Download”, or “Download Original Files” and “Download Archival Format” under the Access Dataset btn
- Include the size of the download and format, e.g. “Download (ZIP, 5 GB)” in the dropdown menu link text (#6400)
- All the same download back end rules as those for the current “select all” Download btn in the file table header
- Dataset Terms popup displayed for terms and guestbook when enabled
- Restricted Files popup warns user if they do not have access to
- Manifest still used if not all files are included, will separate that out into another phase (#5588)
- And of course analytics click event tracking (#6938)

_QUESTIONS?_
- What about an API? (#4529)
- What about file count? (#6601)

**Comment by bikramj** [comment]
Hi @pdurbin,

we are having a problem with the function `getDownloadSize`  in file dataverse/dataset/DatasetUtil.java which was linked to this issue. 

we have some old files in `datatable` table with `originalfilesize` is null, this function is failing with exception when it gets null value and interface get `500 Internal server error.`

**Comment by djbrooke** [comment]
Hi @bikramj - I believe we added this API endpoint to help out with these cases:

https://guides.dataverse.org/en/5.1/api/native-api.html#datafile-integrity

We had some text about this in the 4.10 release notes, step 9 in the direction:

https://github.com/IQSS/dataverse/releases/tag/v4.10

Congratulations, it means your installation is one of the older ones! 🥳 Hope this does the trick. If not, please feel free to open up a new issue and we can work with you on it.

**Comment by bikramj** [comment]
Thank you for the quick response @djbrooke, we just found same link 15minutes ago and it will do the magic. :) 

And thank you again, our installation is from 2013ish DVN3 times :D
