### ISSUE TITLE
File page for deaccessioned datasets

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#6121]
When you deaccession a dataset, if you visit the PID you will get a tombstone page, showing you the dataset existed once upon a time.  Now that we have file PIDs, we need a similar tombstone page for the File Page. 

Current behavior is that a user is redirected to login. (after login, it appears, you get a 403 not authorized page, though demo currently has a rendering issue)

**Comment by mheppler** [comment]
I just stumbled upon this exact login redirect for a deaccession view of the file pg and thought it was a bug. I too expected the "tombstone" view of the file pg that is suggested above. We should reconsider this behavior, as @scolapasta points out, most users upon logging in would get an error pg.

In discussing this issue with Gustavo in more detail, he pointed out that we do not display a file table on the deaccession view of the dataset pg, so any changes to the view of the file pg should also be applied to that file table view on the dataset pg.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
