### ISSUE TITLE
By default, leave all folders closed in tree view of files

### ISSUE THREAD

**Issue by philippconzett** [IQSS/dataverse#6122]
As a user / file downloader, by default, I'd like to see all folders being closed in the tree view of files in a dataset. Currently, the first folder in the hierarchy (regardless of the number of files it contains) is open by default (see this [comment](https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2FIQSS%2Fdataverse%2Fissues%2F5572%23issuecomment-479071056&sa=D&sntz=1&usg=AFQjCNFrkZhoc4vyo56W7lZ5zWSKkNIT5g)). The problem with this is, e.g., that if there are many files in the first folder, you'd first have to close it (or alternatively scroll down) in order to see the other folder(s), and file(s) not contained in folders, e.g. a README file. For a user, it's more convenient to have a nice overview of all the folders and files not contained in folders. I suggest the default settings for closed/open should be a configuration option.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
