### ISSUE TITLE
Add code coverage for integration tests

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#6124]
This issue is related to #4960. 

That issue was closed once documentation was added, but let's go further and actually add this to our process. In particular, with our new focus on integration tests over unit tests, this should help us fine which areas of the application are not being exercised by the current test so we can add new tests.

- Percentage of coverage
- Areas exercised and those not exercised

It would be great to include some coverage metric in the readme like we do for coveralls.

**Comment by pdurbin** [comment]
In pull request #6186 I improved the docs on how to get a code coverage report for API tests out of Dataverse. Sadly, this has not yet been automated. Just today @poikilotherm asked me if we plan to use Maven for this and we probably should but right now we're using a script and some documented commands. This issue isn't a sprint anymore though so I guess it'll have to wait unless someone from the community picks it up. Here are the new and improved docs from the pull request I mentioned: http://guides.dataverse.org/en/4.17/developers/testing.html#measuring-coverage-of-integration-tests

**Comment by donsizemore** [comment]
Currently, Jenkins/Ansible are spitting out this:

![Screen Shot 2020-02-25 at 07 56 26](https://user-images.githubusercontent.com/12831666/75249468-62ad5080-57a4-11ea-9c21-754c41ac62f2.png)

and this: https://jenkins.dataverse.org/job/IQSS-dataverse-develop/364/jacoco/

next to review with @pdurbin and @scolapasta and decide which statia to publish.

**Comment by pdurbin** [comment]
> It would be great to include some coverage metric in the readme like we do for coveralls.

I just split this off into its own small chunk:

-  As a developer, I want a button in the README saying the percentage code coverage for the API test suite (integration tests) #6682

**Comment by djbrooke** [comment]
Much of this is now available at the bottom of the readme! Thanks @donsizemore!
