### ISSUE TITLE
Additional Astronomy FITS File Metadata Support for Units

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#613]
---

Author Name: **Eleni Castro** (@posixeleni)
Original Redmine Issue: 4050, https://redmine.hmdc.harvard.edu/issues/4050
Original Date: 2014-05-28

---
## When ingesting FITS file metadata or allowing users to enter information in the UI for Astronomy metadata elements containing units, Arnold Rots suggested the following:

Assuming that numeric parameters are being kept as numbers, not strings (a requirement for data discovery):

The issue with units is that, no matter in what units the parameters are being held, the following considerations come into play:
1. When metadata parameters are extracted, their units need to be interpreted - otherwise there is no information on what it means.
2. Users ought to be presented with something they can understand in their own context
3. For data discovery, queries need to be interpreted - and that means interpreting the units.

One might consider (2) a nicety and one could shift the burden of (3) to the client, but (1) is absolutely crucial.
What that says is that the system needs to be units-aware, so it might as well include all of them.

**Comment by pdurbin** [comment]
> Users ought to be presented with something they can understand in their own context

To me this sounds like an external preview or explore tool is needed, one that's geared toward astronomy data.
