### ISSUE TITLE
potential viewUnpublishedSubDataverse role?

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#6131]
The "admin" permissions role boasts the ability to view unpublished Dataversia, but each sub-dataverse is considered an island of permissions. This caused confusion today as otherwise unprivileged admins of a sub-dataverse were unable to view that dataverse's unpublished sub-dataversia.

If the proposed role is technically unfeasible or otherwise undesirable, I can submit a PR to make the dataverse/subDataverse distinction more explicit in the permissions section of dataset-management.html.

**Comment by donsizemore** [comment]
Archivists everywhere would love for this to appear in the UI.

**Comment by qqmyers** [comment]
Just to be clear: the setting that exists now can automatically grant admin and/or other roles on all newly created dataverses, so once it is configured, it just works. The API call was motivated by the need to bring existing dataverses in line with ones that would be created with the new setting.

This doesn't remove the utility of a UI option, but it is already something a site admin can configure and do one round of api calls to bring existing dataverses up to date, versus something where ongoing use of the api/ use of the api by users is needed.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
