### ISSUE TITLE
SQL error on initial deploy

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#6148]
Seen in Postgres log whilst deploying Dataverse 4.16 (or develop) on Postgresql-9.6. May be unimportant, but dutifully reporting:

```
ERROR:  relation "sequence" does not exist at character 22
STATEMENT:  SELECT SEQ_NAME FROM SEQUENCE WHERE SEQ_NAME <> SEQ_NAME
```

**Comment by donsizemore** [comment]
Just tried again on 4.18 to see if this had gone away. I think it has, but:

```
ERROR:  relation "sequence" does not exist at character 15
STATEMENT:  SELECT 1 FROM SEQUENCE
```

**Comment by pdurbin** [comment]
@donsizemore when I grep for "SEQ_NAME" I only find them in the "create" scripts at "scripts/database/create". Are you using these? Have you had any luck figuring out which script is throwing either error?

**Comment by donsizemore** [comment]
There are 34 instances of SEQ_NAME in CREATE statements beneath scripts/database/create/ though we're using FlyWay these days. I'm still seeing the above error in develop, FWIW.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
