### ISSUE TITLE
database deadlock during API test suite

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#6149]
seen in troubleshooting API test suite failures on jenkins.dataverse.org. sending to @gdurand and @pdurbin 

console output at https://jenkins.dataverse.org/job/IQSS-Dataverse-Develop-testSubset/27/console

server.log at https://jenkins.dataverse.org/job/IQSS-Dataverse-Develop-testSubset/ws/conf/docker-aio/server.log (will copy this elsewhere before I trigger another build)

```
< 2019-09-06 17:50:54.512 UTC > ERROR:  current transaction is aborted, commands ignored until end of transaction block
< 2019-09-06 17:50:54.512 UTC > STATEMENT:  SELECT 1
< 2019-09-06 17:51:14.704 UTC > LOG:  process 1222 detected deadlock while waiting for ShareLock on transaction 2419 after 1000.219 ms
< 2019-09-06 17:51:14.704 UTC > DETAIL:  Process holding the lock: 1221. Wait queue: .
< 2019-09-06 17:51:14.704 UTC > CONTEXT:  while updating tuple (0,37) in relation "dvobject"
< 2019-09-06 17:51:14.704 UTC > STATEMENT:  UPDATE DVOBJECT SET PERMISSIONINDEXTIME = $1 WHERE (ID = $2)
< 2019-09-06 17:51:14.704 UTC > ERROR:  deadlock detected
< 2019-09-06 17:51:14.704 UTC > DETAIL:  Process 1222 waits for ShareLock on transaction 2419; blocked by process 1221.
	Process 1221 waits for ShareLock on transaction 2420; blocked by process 1222.
	Process 1222: UPDATE DVOBJECT SET PERMISSIONINDEXTIME = $1 WHERE (ID = $2)
	Process 1221: UPDATE DVOBJECT SET INDEXTIME = $1 WHERE (ID = $2)
< 2019-09-06 17:51:14.704 UTC > HINT:  See server log for query details.
< 2019-09-06 17:51:14.704 UTC > CONTEXT:  while updating tuple (0,37) in relation "dvobject"
< 2019-09-06 17:51:14.704 UTC > STATEMENT:  UPDATE DVOBJECT SET PERMISSIONINDEXTIME = $1 WHERE (ID = $2)
< 2019-09-06 17:51:14.706 UTC > ERROR:  current transaction is aborted, commands ignored until end of transaction block
< 2019-09-06 17:51:14.706 UTC > STATEMENT:  SELECT 1
```

**Comment by donsizemore** [comment]
Just a note that I tried the API test suite using Postgresql 10 with the current JDBC driver at Akio's suggestion (the one packaged with Dataverse is now over a year old). It hit the same deadlocks as well.
[pg10currentjdbc.zip](https://github.com/IQSS/dataverse/files/3714211/pg10currentjdbc.zip)

**Comment by donsizemore** [comment]
At @pdurbin 's prompting I tried PostgresQL 10 in EC2 again today and got database deadlocks during the API test suite (11 errors).

I bumped the dataverse-ansible role from 4.17->4.18 using PostgresQL 9.6 and just now 
got the same deadlocks (11 errors as well).

We had been blaming these on sluggish storage, but the errors occur in EC2.

the first:
```
Internal Exception: org.postgresql.util.PSQLException: ERROR: deadlock detected
  Detail: Process 20032 waits for ShareLock on transaction 2647; blocked by process 20031.
Process 20031 waits for ShareLock on transaction 2644; blocked by process 20032.
  Hint: See server log for query details.
  Where: while updating tuple (1,30) in relation "dvobject"
Error Code: 0
Call: UPDATE DVOBJECT SET PERMISSIONINDEXTIME = ? WHERE (ID = ?)
        bind => [2 parameters bound]
Query: UpdateObjectQuery([Dataset id:56 ])
Caused by: org.postgresql.util.PSQLException: ERROR: deadlock detected
  Detail: Process 20032 waits for ShareLock on transaction 2647; blocked by process 20031.
Process 20031 waits for ShareLock on transaction 2644; blocked by process 20032.
  Hint: See server log for query details.
  Where: while updating tuple (1,30) in relation "dvobject"
```

[PG10_server.log.zip](https://github.com/IQSS/dataverse/files/3853425/PG10_server.log.zip)

**Comment by pdurbin** [comment]
🤷‍♂ 

😄 

Thanks for testing, @donsizemore !!

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
