### ISSUE TITLE
Auto-completion based on existing database values for the field Keyword.

### ISSUE THREAD

**Issue by alejandratenorio** [IQSS/dataverse#6154]
Users in CIMMYT need to create a suggested vocabulary list to use them in auto-completion values for the field Keyword.
The community has proposed to add a similary functionality to metadata such as Authors or keywords using a lookup that would unfold in a button within the template, as exposed in https://github.com/IQSS/dataverse/issues/4772, unfortunately, we don't know the current state of this development.

Our list of requirements is as follows:

1. The autocomplete must automatically fill in the fields of:
- Term
- b.	Vocabulary
- c.	Vocabulary URL
2. Each term can have a main language and translations.
3. As administrators, we must manage the controlled vocabularies,
- a.	Add new vocabularies to Dataverse using an easy-to-structure CSV file.
- b.	Edit and delete vocabularies.
- c.	List the controlled vocabularies
- d.	Allow editing a vocabulary: add, edit and delete terms and translates
- e.	Use of a controlled vocabulary from a Global Dataverse to a Sub-Dataverse

We have developed 60% of the requirements; however, the goal  of CIMMYT is to contribute with this new module. We would like to share with you the design, tables and UI for feedback.
The following are some of the UIs we have
For example,
![image](https://user-images.githubusercontent.com/31973211/64625086-372ed900-d3b1-11e9-80ad-b53a6cc535e4.png)

List of controlled vocabularies of a Dataverse 
![image](https://user-images.githubusercontent.com/31973211/64625138-4877e580-d3b1-11e9-920e-f4b4faae98cb.png)

Add new vocabulary
![image](https://user-images.githubusercontent.com/31973211/64625157-50378a00-d3b1-11e9-8054-f4aac38ad777.png)

Confirm before creating a vocabulary from a CSV file
![image](https://user-images.githubusercontent.com/31973211/64625167-5594d480-d3b1-11e9-9979-9329a507defb.png)

Manage a previously created vocabulary
![image](https://user-images.githubusercontent.com/31973211/64625180-5b8ab580-d3b1-11e9-8d15-28f4bcd09512.png)

Editing a term
![image](https://user-images.githubusercontent.com/31973211/64625191-604f6980-d3b1-11e9-9ae9-c2053606a19d.png)

Create a new term
![image](https://user-images.githubusercontent.com/31973211/64625204-66dde100-d3b1-11e9-8f83-c3bb6e36ed00.png)

**Comment by jggautier** [comment]
Hi @alejandratenorio! Thanks for sharing! You wrote that:

> The community has proposed to add a similary functionality to metadata such as Authors or keywords using a lookup that would unfold in a button within the template, as exposed in #4772, unfortunately, we don't know the current state of this development.

About the status of these similar developments, I just wanted to mention that #4772 is part of [this larger github issue](https://github.com/IQSS/dataverse/issues/6030) (larger in scope). In #6030 the thinking, I think, is to consider an approach that takes as many of these use cases and the approaches that teams have proposed and even developed, like yours, into account before changes to the core code are tested and made. This hasn't been done, yet. Just trying to help answer your question about the status of addressing these issues. :)

**Comment by alejandratenorio** [comment]
Hi @jggautier,

I understand, if we want to craft a code contribution for this issue, we should send you a proposal to resolve the #6030

**Comment by alejandratenorio** [comment]
@jggautier, For your comments, could we show you our prototype? 
We would like to develop the global solution but i'm aware that this needs to be discussed

**Comment by jggautier** [comment]
Yes, I think we'd love to see the prototype. It'll really help move solutions forward. (And thanks for the screenshots!)

Could we get back to you next week? I think what we want to do is exactly what you've been doing by contacting people who are already working on aspects of this issue:  Trying to collaborate with everyone who shares similar needs, and might have already forked Dataverse to solve those needs.

**Comment by alejandratenorio** [comment]
@jggautier, 

Sure, we can show you the prototype, it's the same that @scolapasta saw. We'd be happy if you give us feedback and tell us the way to go on.

**Comment by pdurbin** [comment]
@alejandratenorio we have the ability to spin up arbitrary branches from forks of Dataverse if you'd like us to try that. The script we use is documented at http://guides.dataverse.org/en/4.16/developers/deployment.html#download-and-run-the-create-instance-script

![Screen Shot 2019-09-18 at 1 40 13 PM](https://user-images.githubusercontent.com/21006/65171869-dc812700-da19-11e9-92ea-8326493ccfe3.png)

**Comment by alejandratenorio** [comment]
> @alejandratenorio we have the ability to spin up arbitrary branches from forks of Dataverse if you'd like us to try that. The script we use is documented at http://guides.dataverse.org/en/4.16/developers/deployment.html#download-and-run-the-create-instance-script
> 
> ![Screen Shot 2019-09-18 at 1 40 13 PM](https://user-images.githubusercontent.com/21006/65171869-dc812700-da19-11e9-92ea-8326493ccfe3.png)

Hi @pdurbin,

Gerardo did the deploy, 
http://ec2-34-235-131-178.compute-1.amazonaws.com:8080
dataverseAdmin
admin1

**Comment by pdurbin** [comment]
@alejandratenorio fantastic! When I look at http://ec2-34-235-131-178.compute-1.amazonaws.com/api/info/version I see dataverse-4.13-18cbbe6 and it looks like you're building from https://github.com/CIMMYT/Research-Data-Repository/commit/18cbbe6 . The odd thing about that repo is that it only has two commits, but I'll worry about that later. 😄 

The password works fine but I didn't play with the feature or get any screenshots (I'm about to leave for the day) but @jggautier @TaniaSchlatter @mheppler @djbrooke @scolapasta or others might be interesting in playing around with the feature to get a better understanding of how it works. Thanks! 🎉

**Comment by djbrooke** [comment]
Hi @alejandratenorio, I got a chance to review this with @jggautier @scolapasta @TaniaSchlatter and @pdurbin earlier today. Thanks again for setting up the AWS instance for us. 

I have some concerns about building a UI for the administration of this suggestion feature. While the UI that you've worked on so far may work for CIMMYT users, I'm concerned about the scalability of this interface for others that want to allow suggestions for metadata fields while users are adding or editing datasets. I think the better option would be to have the field suggestions managed through an API. 

Generally, what we're thinking is:

- Add table(s) to the application that can be populated with suggestions for metadata fields/compound fields
- Add an API endpoint that can be used to populate those tables for the root dataverse or a specific dataverse (and possibly the sub-dataverses). We'd need to work with you on determining the format and @jggautier will have some ideas. 
- Use our autocomplete component from Primefaces (@scolapasta can you point to this?) to provide suggestions based on what's in the table

There are still some details to be figured out and we're happy to discuss this with you. If managing the suggestions through a UI is a requirement, could we discuss building an external tool that uses the APIs to update the application? 

Comments welcome!

**Comment by alejandratenorio** [comment]
> Hi @alejandratenorio, I got a chance to review this with @jggautier @scolapasta @TaniaSchlatter and @pdurbin earlier today. Thanks again for setting up the AWS instance for us.
> 
> I have some concerns about building a UI for the administration of this suggestion feature. While the UI that you've worked on so far may work for CIMMYT users, I'm concerned about the scalability of this interface for others that want to allow suggestions for metadata fields while users are adding or editing datasets. I think the better option would be to have the field suggestions managed through an API.
> 
> Generally, what we're thinking is:
> 
> * Add table(s) to the application that can be populated with suggestions for metadata fields/compound fields
> * Add an API endpoint that can be used to populate those tables for the root dataverse or a specific dataverse (and possibly the sub-dataverses). We'd need to work with you on determining the format and @jggautier will have some ideas.
> * Use our autocomplete component from Primefaces (@scolapasta can you point to this?) to provide suggestions based on what's in the table
> 
> There are still some details to be figured out and we're happy to discuss this with you. If managing the suggestions through a UI is a requirement, could we discuss building an external tool that uses the APIs to update the application?
> 
> Comments welcome!

@djbrooke, Could we talk about this on Monday?

**Comment by djbrooke** [comment]
@alejandratenorio Sure thing. Looking forward to it! Have a good weekend!

**Comment by stevenmce** [comment]
Hi everyone,

ADA is a definite +1 on adding this feature. I've added it to our project board.
We would like to be able to reference an external vocabulary, ideally held at an authorative source, and then autocomplete based on the user text entry. 

We would be particularly interested in using directly vocabs on:
a) The ARDC vocabulary server: https://vocabs.ands.org.au (here is our current vocab on there: https://editor.vocabs.ands.org.au/apais.html)
b) The CESSDA vocabulary server: https://vocabularies.cessda.eu/ (note particularly they have the DDI vocabularies there!!!)

Cheers,
Steve

**Comment by mdmADA** [comment]
It seems to me that the OP team is wanting a vocabulary service that allows creation of a (self-managed) vocab and then integrate that into their Dataverse UI. If this is true, perhaps there is already a vocab service 'out there' that that team can leverage to manage the vocab itself, then integrate that into the Dataverse UI? Perhaps this is what you are alluding to in your comment @djbrooke?

As Steve pointed out in the previous post, ADA is wanting to leverage the already-existing ARDC vocab service either through 'widgetable' vocabs it offers (select a vocab and the widget explorer gives you the jquery code to embed the 'widget' into web pages) and/or through its API.

For the widgetable vocabs see https://vocabs.ands.org.au/vocabs/page/widget_explorer. As an example, choose 'Australian and New Zealand Standard Research Classification: Fields of Research' - you can test it out below the selection box. The 'widget' generated and embedded is displayed either as a tree or as an autocomplete text box with the latter requiring knowing the vocab you're looking for in order to find it.

The API for the ARDC vocab service:
http://vocabs.ands.org.au/registry/swagger-ui/#/resources
https://documentation.ands.org.au/pages/viewpage.action?pageId=81986922

Determining how ADA can (hopefully easily!) leverage and integrate these exisiting services into the Dataverse UI for the Controlled Vocabs is the next step for this part of ADA's requirements and I will most likely be asking @scolapasta and @djbrooke for views on how to do this.

Thanks!

**Comment by alejandratenorio** [comment]
Hi @djbrooke,

I propose to separate the functionality according to the type of metadata fields.
This proposal is designed for compound metadata, such as Keyword or Topic Classification. For metadata fields like Subject or Language @poikilotherm is working on a prototype #6000
•	Add a table to define controlled vocabularies and their associated metadata field.
•	Add tables that can be populated with suggestions for compound fields: term, vocabulary and URL (for each controlled vocabulary)
•	Add two API endpoint, that can be used to create control vocabulary and their suggestions.
•	Also, add an admin page to manage these features (for admin users).
o	As an administrator user, you could upload suggestions one by one or with a CSV file.
o	We would not read directly a RESTful API because we would have to read different input formats, this would be more complex. Tell me if this is important to you.
•	Each controlled vocabulary could be used in a specific Dataverse or Sub-dataverse.

What do you think?

**Comment by Gerafp** [comment]
Hi all!

In CIMMYT we continue with this functionality. Currently, We work in the autocomplete fields task in the dataset form, the user selects a Controlled Vocabulary in a dropdown list and the terms are load in a list for complete other fields.
We have the problem that the _SelectOneMenu_ not called the java method in the attribute _valueChangeListener_ this method is use for update the selected vocabulary and later for load a list of terms. This terms are used for an autocomplete field.
We see the implementation used when a user created a new Dataset and replicate this, but not work. 

Does anyone have any ideas for this problem?

Java bean
[https://github.com/CIMMYT/Research-Data-Repository/blob/ceee339ffd10115289af373071d04c9796fe84ac/src/main/java/edu/harvard/iq/dataverse/VocabularyTestPage.java](url)

Xhtml page

[https://github.com/CIMMYT/Research-Data-Repository/blob/ceee339ffd10115289af373071d04c9796fe84ac/src/main/webapp/vocabulary-test.xhtml](url)

This is an example for develop and testing, the final version is part of dataset form.

**Comment by djbrooke** [comment]
Hi @alejandratenorio @Gerafp apologies for missing your previous message. Before we start diagnosing the JSF issues, can we meet to discuss the proposal here and get a demo? I know that we tried to get a demo when we last met but we ran out of time after talking through the (now merged and released) MS login feature. 

Would 10 AM ET Friday or 3 PM ET Monday work for you?

**Comment by poikilotherm** [comment]
Just to spread the word, @mheppler posted [this answer to #6000](https://github.com/IQSS/dataverse/issues/6000#issuecomment-556269561). So for now I will not continue to work on it (other prios, too), but test the new component with our usecase. Dunno if #6339 and its solution is related here, too.

**Comment by mheppler** [comment]
@poikilotherm the new `selectCheckboxMenu` PrimeFaces component used by Subject and Language citation metadata fields allow multiple selections, so that component provides checkboxes in the select dropdown menu. The Keyword compound citation metadata fields would provide a `selectOneMenu` PrimeFaces component for the user for Term, as is currently used in the UI for Author and Related Publication compound citation metadata fields for. (See screenshot.)

![Screen Shot 2019-11-21 at 9 57 19 AM](https://user-images.githubusercontent.com/687227/69349174-54034a80-0c45-11ea-821c-0b1b02a268c0.png)

You can see this code with the render logic to determine which UI component is displayed for various metadata fields in the metadataFragment.xhtml (code snippet from PR #6356).

```
<ui:fragment rendered="#{dsf.datasetFieldType.controlledVocabulary}">
    <div class="form-group dataset-field-values">
        <div class="form-col-container col-sm-9 edit-field">
            <p:selectOneMenu value="#{dsf.singleControlledVocabularyValue}" converter="controlledVocabularyValueConverter" style="width: auto !important; max-width:100%; min-width:200px;" styleClass="form-control primitive"
                                            id="unique1" rendered="#{!dsf.datasetFieldType.allowMultiples}">
                <f:selectItem itemLabel="#{bundle.select}" itemValue="" noSelectionOption="true"/>
                <f:selectItems value="#{dsf.datasetFieldType.controlledVocabularyValues}" var="cvv" itemLabel="#{cvv.localeStrValue}" itemValue="#{cvv}"/>
            </p:selectOneMenu>
            <p:selectCheckboxMenu value="#{dsf.controlledVocabularyValues}" multiple="true" converter="controlledVocabularyValueConverter" styleClass="form-control"
                                                      filter="true" filterMatchMode="startsWith" label="#{bundle.select}"
                                                      id="unique2" rendered="#{dsf.datasetFieldType.allowMultiples}">
                <f:selectItems value="#{dsf.datasetFieldType.controlledVocabularyValues}" var="cvv" itemLabel="#{cvv.localeStrValue}" itemValue="#{cvv}"/>
            </p:selectCheckboxMenu>
            <div class="ui-message ui-message-error ui-widget ui-corner-all" aria-live="polite" jsf:rendered="#{!empty dsf.validationMessage}">
                <span class="ui-message-error-detail">#{dsf.validationMessage}</span>
            </div>
        </div>
    </div>
</ui:fragment>
```

**Comment by alejandratenorio** [comment]
> Would 10 AM ET Friday or 3 PM ET Monday work for you?

Hey, @djbrooke,

It's okay Monday at 3 PM ET.

**Comment by djbrooke** [comment]
Thanks @alejandratenorio see you then. Use this information to join:

https://global.gotomeeting.com/join/792074317

You can also dial in using your phone.
United States: +1 (571) 317-3112
Access Code: 792-074-317

**Comment by djbrooke** [comment]
Thanks @alejandratenorio and @Gerafp for offering to add a video here and pointing us to any code or template documents!

**Comment by Gerafp** [comment]
Hi all!
Happy 2020 :D
We have two videos for show the CIMMYT work in this Issue. 
The videos are in OneDrive

Prototype 1 - https://1drv.ms/v/s!Al54grRzE57lhjS7fNpSh2NA0ArG
Prototype 2 - https://1drv.ms/v/s!Al54grRzE57lhjO1kbD6J6AKUkdz

We look forward to your comments

Good Day

**Comment by pdurbin** [comment]
@Gerafp thanks! I just added these videos to the top of DataverseTV: https://dataverse.org/dataversetv

![Screen Shot 2020-02-25 at 1 57 53 PM](https://user-images.githubusercontent.com/21006/75277928-f13ac580-57d6-11ea-8b52-3b2ea69ddd86.png)

@4tikhonov these are the videos I told you would be coming. @RightInTwo you might want to check these out. I know lots of people are interested in better controlled vocabulary stuff in Dataverse. 😄

**Comment by djbrooke** [comment]
Hey @Gerafp, happy new year! Thanks for sharing these videos. We're working on moving forward some big initiatives at the moment (#3404 and #6085) and won't be able to be responsive on this for the next two weeks or so. I'll work with the UI/UX team here to respond to what you've built so far once we have some additional bandwidth. Let me know if you have any concerns.

**Comment by pdurbin** [comment]
@Gerafp from a quick look this morning, I was glad to see the author/depositor "create dataset" experience with the new controlled vocabulary feature toward the end of the second video. A couple screenshots:

![Screenshot from 2020-02-26 07-57-36](https://user-images.githubusercontent.com/21006/75347029-e2ebb880-586d-11ea-8f49-ce8f9b8e668c.png)

![Screenshot from 2020-02-26 07-57-46](https://user-images.githubusercontent.com/21006/75347028-e2ebb880-586d-11ea-9bb1-be85c29ae251.png)

I also really appreciate the final slide of the second video where the current development status is made clear:

![Screenshot from 2020-02-26 07-58-01](https://user-images.githubusercontent.com/21006/75347025-e2532200-586d-11ea-83cb-614cbdcdf8df.png)

**Comment by alejandratenorio** [comment]
Hi all, 

Thank you all for your comments, we are finishing the second prototype,  we think it's more functional than the other one. 
We hope this contribution will be useful and hope your suggestions and comments.

**Comment by djbrooke** [comment]
Thanks @alejandratenorio, good to hear from you. I'm going to tag @qqmyers as he is working on a document regarding metadata use cases in Dataverse and it would be helpful to discuss your work so far, and perhaps see a demo/video.

**Comment by Gerafp** [comment]
Hi all!.

In these days, we continue working in this functionality. At present, we have a test version with this implementation, the implementation is based on the second prototype show in the videos. 
If you want test it, the URL is:

http://dataversetest.servehttp.com/

u: dataverseAdmin
p:qwerty12

Unfortunately, we experiment some problems when adding the modal for select a term into the "dataset.xhtml" file:

- The modal sometimes is not showing correctly or some fragments rendered in different parts of the page . Not show the vocabularies and not show the vocabularies terms.

![image](https://user-images.githubusercontent.com/25359497/82088439-5d7ee400-96b7-11ea-9c62-86eb86117726.png)


- If the modal is showing correctly. When a user select a term and set into the keyword fields in the dataset metadata form. The values are not save.

![image](https://user-images.githubusercontent.com/25359497/82087770-6622ea80-96b6-11ea-8abe-7db37cdf975f.png)

![image](https://user-images.githubusercontent.com/25359497/82087683-3378f200-96b6-11ea-8d69-6f31254888e9.png)

![image](https://user-images.githubusercontent.com/25359497/82087716-455a9500-96b6-11ea-8c28-3648e63769e6.png)


- The Upload file section is bugged. If a user want upload a file when created a new dataset, this section are repeat and cant not upload the file. 

![image](https://user-images.githubusercontent.com/25359497/82087618-147a6000-96b6-11ea-80bc-d6ec86640358.png)

We believe it is an incompatibility with the elements of Primefaces but it would be helpful if you could take a look at it.

The problems are rare, because when we adding the modal into the "template.xhtml", the modal works correctly. The user can create a new template, select a keyword by the modal, set the values and save the values for each template, the same when a user edit a template.


We continue work in this funtion and We look forward to your comments, the code is up to date in this issue branch.

If the server is down you can tell me for start it.

Gerafp.

**Comment by Gerafp** [comment]
Hi all!

Do you have some suggestions or comments about the last update?

Regards

**Comment by djbrooke** [comment]
Hi @Gerafp, good to hear from you. I hope you and the team are well. 

@qqmyers @kmika11 and @stevenmce recently contacted Richard F. to include discussion of this work in the Flexible Metadata session at the Dataverse Community Meeting (https://projects.iq.harvard.edu/dcm2020). We hope that will be a good opportunity to discuss the goals driving this work, and to discuss the work so far.

**Comment by qqmyers** [comment]
@Gerafp  - In trying to start the controlled vocabulary value topic in the Dataverse Metadata working group, I'm wondering if you might want to particpate and perhaps recap your requirements/work relevant to the topic in the first meeting for that topic. Would you be interested? If so, the best way to connect would probably be to follow the process to join the WG and get into the slack space and contact me there (see https://groups.google.com/g/dataverse-community/c/dyNNdNXNe-I/m/29Z5bgdCAQAJ).

**Comment by pdurbin** [comment]
@alejandratenorio @Gerafp @stevenmce and others, I just want to make sure you're all aware that Dataverse 5.7 has been released and includes a new external controlled vocabulary feature. I'll copy the relevant part of the release note below. I'm hoping you get a chance to try it out and see if it meets your needs!

From https://github.com/IQSS/dataverse/releases/tag/v5.7

### Experimental Support for External Vocabulary Services

Dataverse can now be configured to associate specific metadata fields with third-party vocabulary services to provide an easy way for users to select values from those vocabularies. The mapping involves use of external Javascripts. Two such scripts have been developed so far: one for vocabularies served via the [SKOSMOS protocol](https://skosmos.org) and one allowing people to be identified via their [ORCID](https://orcid.org). The guides contain info about the new [:CVocConf setting](https://guides.dataverse.org/en/5.7/installation/config.html#cvocconf) used for configuration and additional information about this functionality. Scripts, examples, and additional documentation are available at the [GDCC GitHub Repository](https://github.com/gdcc/dataverse-external-vocab-support).

Please watch the [online presentation](https://youtu.be/mWMPxCwB2ys?t=1794), [read the document with requirements](https://docs.google.com/document/d/1txdcFuxskRx_tLsDQ7KKLFTMR_r9IBhorDu3V_r445w/edit?ts=5fdbca9a) and join the [Dataverse Working Group on Ontologies and Controlled Vocabularies](https://dataverse.org/community-calls) if you have some questions and want to contribute.

This functionality was initially developed by [Data Archiving and Networked Services](http://dans.knaw.nl/en/) (DANS-KNAW), the Netherlands, and funded by [SSHOC](https://sshopencloud.eu), "Social Sciences and Humanities Open Cloud". SSHOC has received funding from the European Union’s Horizon 2020 project call H2020-INFRAEOSC-04-2018, grant agreement #823782. It was further improved by the Global Dataverse Community Consortium (GDCC) and extended with the support of semantic search.

**Comment by pdurbin** [comment]
@alejandratenorio @Gerafp have you tried the external vocabulary feature? Here are the latest docs: https://guides.dataverse.org/en/5.12/admin/metadatacustomization.html#using-external-vocabulary-services

Are you still interested in the issue (#6145)? Thanks for the demos and all the work on it! If external vocabularies work for you, perhaps we can close this issue. Please let us know. Thanks.

**Comment by cmbz** [comment]
2024/09/30: @alejandratenorio @Gerafp we are closing this issue because it appears that it may be addressed already. If not, please comment and let us know if it is still a problem.
