### ISSUE TITLE
Footer image and CSS customization for Sub-Dataverse

### ISSUE THREAD

**Issue by alejandratenorio** [IQSS/dataverse#6156]
In Dataverse, it is only possible to customize CSS styles and the footer globally. Sometimes we need to add a style or image in the footer to some sub-dataverse. 

Similar to logo image, we add the code that allows administrators to configure an image in the footer and add some CSS style.

![image](https://user-images.githubusercontent.com/31973211/64630356-91806780-d3ba-11e9-9ff3-7d75fa85e884.png)

The footer image is shown above the default Footer and CSS styles are embedded as a separate file.
![image](https://user-images.githubusercontent.com/31973211/64630467-cd1b3180-d3ba-11e9-827c-47834f581d3b.png)

The goal of CIMMYT is to contribute with Dataverse. We would like to share with you the source code for your review and comments.

**Comment by TaniaSchlatter** [comment]
Hi @alejandratenorio, thanks for opening this issue. We are wondering what need is being solved with this functionality? 

In general, the UI and functionality for adding a footer image seems ok. We are concerned about opening up security risks by allowing custom CSS, however.

**Comment by alejandratenorio** [comment]
Hello, @TaniaSchlatter, some sub-dataverses must display the donor logo in the footer. We also need to change the font color or background color.

**Comment by alejandratenorio** [comment]
@TaniaSchlatter, can we show you a prototype of footer image? I'm aware that this needs to be evaluated.

**Comment by TaniaSchlatter** [comment]
@alejandratenorio yes, definitely. I sat with @scolapasta and saw a footer image example, and am interested in seeing any other prototypes.

**Comment by alejandratenorio** [comment]
@TaniaSchlatter, @djbrooke, It's the same, can we make a pull request for your review?

**Comment by djbrooke** [comment]
Hi @alejandratenorio - we want to very careful at adding this level of customization to the application. For each customization that we add, it means one other option that we will need to take into consideration when designing things in the future. 

Would allowing a logo or logos to the footer be sufficient? That would be much easier to work with than custom CSS. If this is sufficient, can you make a PR that just has support for adding logos?

**Comment by alejandratenorio** [comment]
Hi @djbrooke,
I understand, you have a broader view of the project than we do.  Yes, we are happy if you allow a logo in the footer.

**Comment by mheppler** [comment]
Hello, @alejandratenorio and @Gerafp. I have created a new branch `6156-dv-theme-footer-cleanup` in our repo, based off the original branch from Gerardo in PR #6219. Can you please grant me access to your repo to get those recent changes merged into the original branch? That will allow us to move this issue back to QA.

Here is an outline of the changes in the new branch:

- dataverseFooterName, dataverseFooterTagline, dataverseFooterLink classes in CSS are not used in the XHTML and should be removed
- Fix spacing between new footer and copyright and Dataverse Project logo
- Footer overlaps custom footer
- Add "logo" to image alt text
- Remove Logo Format from footer because that is a header only feature

**Comment by alejandratenorio** [comment]
> Hello, @alejandratenorio and @Gerafp. I have created a new branch `6156-dv-theme-footer-cleanup` in our repo, based off the original branch from Gerardo in PR #6219. Can you please grant me access to your repo to get those recent changes merged into the original branch? That will allow us to move this issue back to QA.
> 
> Here is an outline of the changes in the new branch:
> 
> * dataverseFooterName, dataverseFooterTagline, dataverseFooterLink classes in CSS are not used in the XHTML and should be removed
> * Fix spacing between new footer and copyright and Dataverse Project logo
> * Footer overlaps custom footer
> * Add "logo" to image alt text
> * Remove Logo Format from footer because that is a header only feature

Hi @mheppler,

Yes, of course. Now, you are a collaborator

**Comment by mheppler** [comment]
Thank you, @alejandratenorio!

**Comment by mheppler** [comment]
The CIMMYT branch for PR #6219 has been updated with my changes to cleanup the UI, and I will now move that back to QA.
