### ISSUE TITLE
Dataverse setting to restrict files by default

### ISSUE THREAD

**Issue by adam3smith** [IQSS/dataverse#6158]
As discussed [here.](https://groups.google.com/d/msg/dataverse-community/EL863mV0epw/S8siUGBuAwAJ) Several installations including ADA, AUSSDA, and QDR restrict most of their files and it would be very convenient to have all files restricted by default. @scolapasta in the google group suggests the following approach/considerations:

> This should just be a setting in the settings table ":RestrictFilesByDefault" (or something like that) with the default being false. It would be straightforward to check this code when you upload a dataset.

>Do note that this will have to change once we add DataTags support, but I imagine we could have "defaultDataTag" and migrate the above from "false" to "blue" and "true" to "yellow".

>The other thing to note is that currently when a user does restrict a file, we "nudge" the user to allow request access and / or add terms. We'd lose this in the case of default restricted, so another addition is that it may be worth considering nudging them at upload time, in this scenario.

I imagine that setting should be an admin setting at the dataverse level, right?

**Comment by tgoelles** [comment]
I am also interested in this and think that it would be nice if:

- managed by dataverse: for example a dataverse is a project where everything is restricted
- manged via the dataset template: if I create a new project I can then choose that everything is restricted by default

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
