### ISSUE TITLE
Import Utility: Fails on filenames with accented characters in production but works on test boxes.

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#616]
---

Author Name: **Kevin Condon** (@kcondon)
Original Redmine Issue: 4053, https://redmine.hmdc.harvard.edu/issues/4053
Original Date: 2014-05-29
Original Assignee: Gustavo Durand

---

See RT #177216

The issue does not occur with our test boxes, former production boxes,
dvn-4 and dvn-1, but does happen in production.

One theory is that one of the layers that handles opening the file for
import does not use UTF-8 and that is causing the issue.

The layers are: OS, JDK, Glassfish, DVN.

DVN is probably not the direct cause, although the file handling library
may affect it.
Glassfish has numerous places to configure UTF-8 for various reasons but I
saw no evidence in any of the config files: glassfish-web.xml,
sun-web.xml, JVM option, web.xml.
JDK is different in production, Open JDK, based on java6, java7 on dvn-4
and java6 Sun JDK on dvn-1.
OS is unclear, RHEL 6 in prod, RHEL 5 on dvn-4 and dvn-1. Environment vars
all show UTF-8 (LANG, LC). Accented chars display on all systems.

If we rename the files to substitute english chars for accented chars, it
works fine. Also works as is on test boxes as mentioned.

The language in this case is Spanish.

**Comment by scolapasta** [comment]
We no longer have the import utility, but we need to make sure this works for any of our import APIs.

**Comment by landreev** [comment]
We don't have the import utility. 
We do have sword, which I tested, and it seems to be working with any UTF8 characters in the name. 
Not sure what else to do with this ticket.
