### ISSUE TITLE
On dataset page, deaccession reason text is misplaced to right of citation box 

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#6162]
In version 4.16, on dataset pages of deaccessioned dataset versions, the "Deaccession Reason" text appears to the right of the citation box:

<img width="750" alt="Screen Shot 2019-09-12 at 11 33 48 AM" src="https://user-images.githubusercontent.com/18374574/64798561-37fe7100-d551-11e9-86c0-be2889f058bc.png">

When the page width shrinks (enough for the top nav bar to collapse into that hamburger menu), the "Deaccession Reason" text moves below the citation box where it should be:

<kbd>![Screen Shot 2019-09-12 at 11 14 59 AM](https://user-images.githubusercontent.com/18374574/64798668-6bd99680-d551-11e9-98a6-8e65a1d04b4d.png)</kbd>

**Comment by mheppler** [comment]
Fixing this as part of the many responsive improvements to the dataset pg in issue #5615.

![Screen Shot 2019-10-22 at 3 57 33 PM](https://user-images.githubusercontent.com/687227/67326693-e4cef500-f4e4-11e9-9d4f-608ce2250259.png)

**Comment by BPeuch** [comment]
I wanted to add that it might be a bit more elegant if the additional information entered by the admin appeared one lign below the reason that must be selected before deaccessioning a dataset, so as to avoid concatenating both like this:

![test_deaccession](https://user-images.githubusercontent.com/15209224/76222650-29042d00-621b-11ea-89a4-e6b317551bc0.png)

**Comment by mheppler** [comment]
@BPeuch thank you for the feedback and the screenshot example of the issue. We are currently working on some dataset pg UI improvements in issue #6605, and will aim to improve issue as part of those efforts.

**Comment by BPeuch** [comment]
Gladly done, @mheppler! Good luck with the overhaul.
