### ISSUE TITLE
Building of PDF version of guides failing on develop branch

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#6168]
As of 22ee5e5 (or earlier?) we are seeing failures to build the PDF version of the guides. Here's a screenshot from https://build.hmdc.harvard.edu:8443/job/guides.dataverse.org-develop/6727/consoleFull

<img width="1519" alt="Screen Shot 2019-09-13 at 2 08 10 PM" src="https://user-images.githubusercontent.com/21006/64884685-51c2b580-d630-11e9-9b63-09b88b9370ac.png">

**Comment by pdurbin** [comment]
Today @Xarthisius asked for docs on external tools so I disabled PDF builds at https://build.hmdc.harvard.edu:8443/job/guides.dataverse.org-develop/ but we should really fix this. PDFs are the best way we have to offer better search as explained at https://github.com/IQSS/dataverse/issues/4884#issuecomment-431332918

**Comment by djbrooke** [comment]
Thanks @pdurbin, we'll bring it into the next sprint.

**Comment by landreev** [comment]
Huh, I broke it, actually.

**Comment by landreev** [comment]
and I fixed it too.

**Comment by landreev** [comment]
I have re-enabled PDF build in the configuration of https://build.hmdc.harvard.edu:8443/job/guides.dataverse.org-develop/
