### ISSUE TITLE
An exception is logged as FINE entry during email verification

### ISSUE THREAD

**Issue by pkiraly** [IQSS/dataverse#6175]
in the `findSingleConfirmEmailDataByUser` method (edu.harvard.iq.dataverse.confirmemail.ConfirmEmailServiceBean#findSingleConfirmEmailDataByUser in src/main/java/edu/harvard/iq/dataverse/confirmemail/ConfirmEmailServiceBean.java) if the user is not found exceptions are catched and logged as FINE log entry:

```
try {
  confirmEmailData = typedQuery.getSingleResult();
} catch (NoResultException | NonUniqueResultException ex) {
  logger.fine("When looking up user " + user + " caught " + ex);
}
```

For me it is strange. I think FINE entries are for those information which happen on the main, expected workflow. If we run into an exception, it should not be the main way, and we should make a distinction putting this into at least a warning or a higher level of log entry.

In this particular case it would be useful to log the SQL query if it is possible.

The current resulted log entry is something like this:

```
When looking up user [AuthenticatedUser identifier:@<useridentifier>] 
  caught javax.persistence.NoResultException: getSingleResult() did not retrieve any entities.]]
```
(It is a single line, I just break it because of the display of the ticket.)

The message is misleading, because this query runs on the ConfirmEmailData table, and it means that the user ID is not found in the table used for storing user data temporary in the email confirmation process, and not as the log entry might suggest the user is not existing in the system.

**Comment by pdurbin** [comment]
@pkiraly yes, you're right. At http://guides.dataverse.org/en/4.16/developers/coding-style.html#logging (screenshot below) we try to give some guidance on logging and and I agree that "fine" is too low for that caught exception. Would you like to make a pull request to correct this? I also agree that showing the query or at least some more information in the log would be helpful.

![Screen Shot 2019-09-17 at 12 08 46 PM](https://user-images.githubusercontent.com/21006/65059512-239ce880-d944-11e9-9ad7-fe1f3a74b7ff.png)

**Comment by pkiraly** [comment]
I've created a pull request: https://github.com/IQSS/dataverse/pull/6177

**Comment by pdurbin** [comment]
@pkiraly thanks! I moved it to QA but can you please leave a note here about "how to test"?

What I mean is, what steps should QA take to make the warnings appear in server.log?

Thanks!

**Comment by pkiraly** [comment]
Not an easy question to answer. Shortly: I do not know how this log entry were created in our system. The bigger picture is this: a user (a person) has two independent email addresses and he tried both to register and log in to Dataverse. He was able to log in with one of them (he shared a screenshot with me with his profile page on it), and not able with the other. However in the authenticateduser table the lastlogintime of the account he was able to use was a date more than a year ago! (Again: he share a screenshot, that we were able to log in yesterday). I started to investigate in the log, and found the log entry. I do not have a clue how this log entry were created, but I guess it is part of the email verification process. To start this process you have to go to https://data.goettingen-research-online.de/dataverseuser.xhtml?selectTab=accountInfo, click on "Verify email" button, and to create the log entry it should something happen to run into the exception which triggers the log entry, however it is absolutely not clear what exactly which is this "something".

**Comment by pdurbin** [comment]
@pkiraly thanks. This helps. One more thing. Can you please update the title of the issue (and the pull request, if you like) to say something about "verify email"? Release notes link to issues so it's nice to have titles that describe the problem in terms of which feature or part of the system is affected.

**Comment by pkiraly** [comment]
"An exception is logged as FINE entry during email verification"
is it acceptable/expressive?

**Comment by pdurbin** [comment]
@pkiraly sounds perfect! Thanks!

**Comment by kcondon** [comment]
@pkiraly @pdurbin This change in logging makes the account info page noisy now under normal situations, putting this in the logs:


[2019-09-18T09:41:24.408-0400] [glassfish 4.1] [WARNING] [] [edu.harvard.iq.dataverse.confirmemail.ConfirmEmailServiceBean] [tid: _ThreadID=53 _ThreadName=jk-connector(3)] [timeMillis: 1568814084408] [levelValue: 900] [[
  When looking up user [AuthenticatedUser identifier:@kc091819] at ConfirmEmailData table, exception caught: javax.persistence.NoResultException: getSingleResult() did not retrieve any entities.]]

[2019-09-18T09:41:24.409-0400] [glassfish 4.1] [WARNING] [] [edu.harvard.iq.dataverse.confirmemail.ConfirmEmailServiceBean] [tid: _ThreadID=53 _ThreadName=jk-connector(3)] [timeMillis: 1568814084409] [levelValue: 900] [[
  When looking up user [AuthenticatedUser identifier:@kc091819] at ConfirmEmailData table, exception caught: javax.persistence.NoResultException: getSingleResult() did not retrieve any entities.]]

[2019-09-18T09:41:24.409-0400] [glassfish 4.1] [WARNING] [] [edu.harvard.iq.dataverse.confirmemail.ConfirmEmailServiceBean] [tid: _ThreadID=53 _ThreadName=jk-connector(3)] [timeMillis: 1568814084409] [levelValue: 900] [[
  When looking up user [AuthenticatedUser identifier:@kc091819] at ConfirmEmailData table, exception caught: javax.persistence.NoResultException: getSingleResult() did not retrieve any entities.]]

[2019-09-18T09:41:24.409-0400] [glassfish 4.1] [WARNING] [] [edu.harvard.iq.dataverse.confirmemail.ConfirmEmailServiceBean] [tid: _ThreadID=53 _ThreadName=jk-connector(3)] [timeMillis: 1568814084409] [levelValue: 900] [[
  When looking up user [AuthenticatedUser identifier:@kc091819] at ConfirmEmailData table, exception caught: javax.persistence.NoResultException: getSingleResult() did not retrieve any entities.]]

[2019-09-18T09:41:24.410-0400] [glassfish 4.1] [WARNING] [] [edu.harvard.iq.dataverse.confirmemail.ConfirmEmailServiceBean] [tid: _ThreadID=53 _ThreadName=jk-connector(3)] [timeMillis: 1568814084410] [levelValue: 900] [[
  When looking up user [AuthenticatedUser identifier:@kc091819] at ConfirmEmailData table, exception caught: javax.persistence.NoResultException: getSingleResult() did not retrieve any entities.]]

[2019-09-18T09:41:24.410-0400] [glassfish 4.1] [WARNING] [] [edu.harvard.iq.dataverse.confirmemail.ConfirmEmailServiceBean] [tid: _ThreadID=53 _ThreadName=jk-connector(3)] [timeMillis: 1568814084410] [levelValue: 900] [[
  When looking up user [AuthenticatedUser identifier:@kc091819] at ConfirmEmailData table, exception caught: javax.persistence.NoResultException: getSingleResult() did not retrieve any entities.]]

I know we sometimes "fix" these noisy logging situations by marking them as fine. So, is this one of those situations? Is there a way to not make these log entries occur under normal situations?

**Comment by pkiraly** [comment]
Since my starting point was a strange behaviour, my (biased) suspicion is that this change just reveals a so far hidden (and possibly not intended) behaviour.

**Comment by kcondon** [comment]
@pkiraly Which version of dataverse are you using? So far I am unable to get the verify email button to appear. Also, I do not understand the steps to reproduce the problem. I understand it involves two email addresses but that's all. Did the user change email address for the account? In an earlier version of Dataverse, there was an issue with sequence numbers becoming out of synch on the builtin user and authenticateduser tables that was later corrected by removing duplicate columns from builtin user table.

**Comment by pkiraly** [comment]
@kcondon 
v4.16 (https://data.goettingen-research-online.de/)

For me the exact steps are also not clear. I get information in different emails. One of the account was builtin account previously and later (several month ago) it was converted to Shibboleth based. I just checked: the user IDs are not in the builtinuser table, only in the authenticateduser table.

**Comment by kcondon** [comment]
@pkiraly Ok, thanks. Could you maybe talk about the original problem? I'm not sure whether this is fixing something you experienced or just something you noticed while looking into another problem? Either way it would be good to understand what the original problem was. Btw,  I think this exception, as originally conceived by us, is somewhat meaningless -I think our code checks that table, which only contains temporary data, and throws an exception when it does not find an entry, which appears to be possible under normal circumstances. I see it when an account is initially created and the user visits the account info tab, I also see it when the verify email token times out.

**Comment by kcondon** [comment]
@pkiraly Actually, I think the exception is only telling us that there is no outstanding/available email verification token for this account. I notice a token is added to the table when the account is first created or if the email address is changed, or of the verify email button sends a new verification email with a new token. It remains in the table when expired until the user clicks on the expired verify email link, then it is removed from the table. This last action is what causes subsequent page loads to throw that exception, which really provides no useful information.  I think I understand why the entry was removed -housekeeping, don't want stale entries around, but why do we throw an exception? Maybe the logic can be improved? I would argue in light of this functioning, marking the exception as a warning instead of fine is not helpful but fixing the logic would be.

**Comment by pkiraly** [comment]
@kcondon I agree, that it would be better to fix the logic.

BTW: I sent myself a versification email, and the email contains the following:

```
subject:
Göttingen Research Online / Data: Verify your email address

body: 
Hello, Peter.

Please contact us if you did not intend this change or if you need assistance.

You may contact us for support at dataverse@gwdg.de.

Thank you,
Dataverse Team
```

The is no instruction or link in this email. Is this intended, or is this another issue around verification process?

**Comment by kcondon** [comment]
@pkiraly That seems like a bug. This is what I see when I click verify email:

Hello, kc091819d.

Please verify your email address at https://dataverse-internal.iq.harvard.edu/confirmemail.xhtml?token=eb92bbcf-b23f-425a-aaf8-01faf5532c8a . Note, the verify link will expire after 1 minute. Send another verification email by visiting your account page.

Please contact us if you did not intend this change or if you need assistance.

You may contact us for support at support@dataverse.harvard.edu.

Thank you,
Harvard Dataverse Support

**Comment by kcondon** [comment]
@pkiraly Does your local email filter out links in some way as a security measure? For testing, I'm using the free mailinator.com. Just specify your test user email like me123@mailinator.com and go to mailinator.com. Enter your user me123 in the mailbox portion to see the email.

**Comment by pdurbin** [comment]
@pkiraly are you using institutional login? I ask because you might be seeing expected behavior (no link): "Users of the Institutional Log In option are not required to verify their email address because the institution providing the email address is trusted." http://guides.dataverse.org/en/4.16/user/account.html#edit-account

**Comment by pdurbin** [comment]
@pkiraly is this still of interest? Thanks.
