### ISSUE TITLE
Search Results Facets - Default Facets

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#619]
---

Author Name: **Mike Heppler** (@mheppler)
Original Redmine Issue: 4056, https://redmine.hmdc.harvard.edu/issues/4056
Original Date: 2014-05-29
Original Assignee: Philip Durbin

---

For my local dev environment, by default, the facets that display are Publication Status, Affiliation, Publication Date.

From an older ticket (#3490), we outlined the default facets as:

* Type (Dataverse, Dataset, File)
* Host Dataverse
* Author
* Affiliation (dataverse "Affiliation" and dataset "Author Affiliation" combined into a single facet)
* Distributor (not "Distributor Name", see #3609)
* Release Date #3592 (Dataset release date #3628 and Dataverse release date #3629 combined into one facet)
* Keyword
* Topic Classfication Per 3/4/14 discussions now named Subject #3619
* File Type

---

Related issue(s): #82
Redmine related issue(s): [3490](https://redmine.hmdc.harvard.edu/issues/3490)

---

**Comment by pdurbin** [comment]
This ticket was closed after internal discussion that the person installing Dataverse should choose the default facets at the root level. I disagree. We should provide sane defaults for new installation of Dataverse. At minimum I would think "Author" and some sort of date would be of interest. Perhaps "Keyword" too.

I don't see this as a high priority so I'm taking it out of any particular milestone.

Please note that we reference this ticket from http://guides.dataverse.org/en/latest/developers

**Comment by scolapasta** [comment]
This is actually done in setup-all.
