### ISSUE TITLE
Minor 4.15 release note issues

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#6201]
In reviewing the notes to help TDL upgrade, I noticed that:

while solr was upgraded to 7.3.1 as of 4.11, the 4.15 release notes show paths to 7.3.0 in step 7.

and step 7 also says 'optionally replace solrconfig.xml to allow sorting and filtering on the file page', but I don't see that solrconfig.xml changed in this release - last update in git was 9 months ago .

**Comment by djbrooke** [comment]
Thanks @qqmyers, I updated the first issue. Bad copy/paste. Let me check on the second reported issue.

**Comment by djbrooke** [comment]
@landreev, @kcondon I think the reference to replacing solrconfig is unnecessary (no changes) and was the result of an over-aggressive copy paste by me from the 4.10 release notes. Can one of you do a quick check before I remove it from the 4.15 notes? Thank you!

**Comment by djbrooke** [comment]
I've updated the notes to reflect that changing solrconfig is not required. Thanks again @qqmyers!
