### ISSUE TITLE
metadata tab: doi link in related publications field should hyperlink

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#6202]
In the demo site: if you click on the metadata tab, the doi link in "related publications" does not hyperlink, although in the summart view of the dataset page, it does.

see both images:
summary provides hyperlink

![Screen Shot 2019-09-25 at 3 07 04 PM](https://user-images.githubusercontent.com/18374574/65631756-29c74080-dfa6-11e9-94a5-64d18ab27f27.png)

metadata tab does not:

<img width="941" alt="Screen Shot 2019-09-25 at 3 09 09 PM" src="https://user-images.githubusercontent.com/18374574/65631889-7579ea00-dfa6-11e9-9843-2ec8855562f2.png">

**Comment by djbrooke** [comment]
Thanks @sbarbosadataverse. 

@jggautier - let's catch up about this next week. I think the preferred solution to this issue is #1625.

**Comment by pdurbin** [comment]
What's weird is that #2814 has a screenshot of it working.

**Comment by pdurbin** [comment]
The URL for "Related Publiction" works fine on https://dataverse.ada.edu.au/dataset.xhtml?persistentId=doi:10.4225/87/JUDY2Y running Dataverse 4.6.1. Here's a screenshot:

![Screen Shot 2019-09-20 at 3 53 26 PM](https://user-images.githubusercontent.com/21006/65355045-01fb6580-dbbf-11e9-828f-f619a608ec77.png)

**Comment by jggautier** [comment]
> @jggautier - let's catch up about this next week. I think the preferred solution to this issue is #1625.

@djbrooke and I chatted about this issue. The suggestion in #1625 would go beyond fixing this bug.

As far as I can tell, in Dataverse 4.16, related publication URL is the only URL field (a field that expects a URL) that isn't displayed in the Metadata tab as a clickable link. Keyword vocab, producer and distributor URLs are all still clickable when displayed in the Metadata tab.

<img width="1005" alt="Screen Shot 2019-09-23 at 2 43 41 PM" src="https://user-images.githubusercontent.com/18374574/65453598-8a714480-de11-11e9-8600-b5850ea8892d.png">

**Comment by djbrooke** [comment]
Thanks @jggautier ! Will move to the Ready column for us to take on in an upcoming sprint.

**Comment by djbrooke** [comment]
@jggautier - can you add in the additional information that you mentioned during sprint planning? Also, let's discuss the old issue from @pameyer regarding opening links in a new window.

**Comment by jggautier** [comment]
Sure. I just mentioned that the only change in the citation.tsv that I could see between the Dataverse version ADA's repository is using, 4.6.1, and the more recent versions, is that the html attribute target="_blank" was added to the display format of the url fieldtypes. (Although we didn't think that could be the source of the regression.)

The old issue from @pameyer about adding another html attribute is https://github.com/IQSS/dataverse/issues/4717

**Comment by scolapasta** [comment]
The low level issue is the **displayformat** for **publicationURL** in the database is set to: '#VALUE'  instead of '<a href="#VALUE" target="_blank">#VALUE</a>'. 

If you change that value in the DB it works correctly.

So the real question is how did this get changed in the DB? (and is anything else incorrect)

@jggautier looked at the TSV and it is correct there. So the bug is likely in the API that reads and parses the TSV.

(the upshot is that we could manually update this as a quick fix, but we should find the root cause so that it doesn't occur in the future if/when we reload the TSV)

**Comment by landreev** [comment]
Setting **displayformat**  for **publicationURL**  to ```<a href="#VALUE" target="_blank">#VALUE</a>``` does fix it; I've done it on demo and in production, and the url in the metadata tab is now clickable.
I haven't yet figured out how the field got set to ```#VALUE``` in the first place.

**Comment by landreev** [comment]
We suspected that this was caused by a bug in the ```/api/admin/datasetfield/load``` API, that caused the **displayFormat** to be set to the wrong value. But it doesn't appear to be the case - reimporting citation.tsv doesn't seem to result in this. 
Is there a chance the display format was changed on purpose, both on demo and in prod.?
Should we just ask in the release notes to reimport the citation block, just in case - and declare this solved?

**Comment by djbrooke** [comment]
I'm OK with not spending time investigating this further if the only consequence is that it could not be clicked and there are not other known issues. @jggautier are you OK with this?

**Comment by landreev** [comment]
Correct. And it CAN be clicked now, on our systems here. 
We just don't know why it got reset; and if any other installations are affected. (sorry for repeating things - just want to make sure we're all on the same page...)

**Comment by jggautier** [comment]
I'm okay with this, too.

Other installations running more recent Dataverse versions are affected, like UNC: https://dataverse.unc.edu/dataset.xhtml?persistentId=hdl:1902.29/11878. So they'll just have to reload the citation.tsv, too?

**Comment by scolapasta** [comment]
If the API is working as it should (which @landreev is confirming above) then yes, reloading should work.

It's still weird how it got in this state in the first place. But if it's all working now as it should, then yeah, let's just add to release notes and close. (and make sure to keep an eye on this, in case something recurs)

**Comment by landreev** [comment]
Yes, I've tried re-importing citation.tsv on multiple hosts - appears to be doing the right thing. I checked the actual copy of ```citation.tsv``` that we have up on the 4.16 release page - and it appears to be correct too. 
As for Odum - they seem to be affected; but then they also seem to be running 4.11 (?).
The whole thing is suspicious and sketchy, but I also feel that the right way of going about it is to pretend it never happened and move on.

**Comment by landreev** [comment]
Well, this is one of those rare occurrences where pretending something isn't happening is not the best way of addressing a problem. 
(it looks like we have found where it's happening, in ```DatasetVersion.java```:

```
public List<DatasetRelPublication> getRelatedPublications() {
        List<DatasetRelPublication> relatedPublications = new ArrayList<>();
        for (DatasetField dsf : this.getDatasetFields()) {
            if (dsf.getDatasetFieldType().getName().equals(DatasetFieldConstant.publication)) {
                for (DatasetFieldCompoundValue publication : dsf.getDatasetFieldCompoundValues()) {
                    DatasetRelPublication relatedPublication = new DatasetRelPublication();
                    for (DatasetField subField : publication.getChildDatasetFields()) {
                        if (subField.getDatasetFieldType().getName().equals(DatasetFieldConstant.publicationCitation)) {
                            String citation = subField.getDisplayValue();
                            relatedPublication.setText(citation);
                        }
                        if (subField.getDatasetFieldType().getName().equals(DatasetFieldConstant.publicationURL)) {
                            // Prevent href and target=_blank from getting into Schema.org JSON-LD output.
                            subField.getDatasetFieldType().setDisplayFormat("#VALUE");
                            String url = subField.getDisplayValue();
                            relatedPublication.setUrl(url);
                        }
                    }
                    relatedPublications.add(relatedPublication);
                }
            }
        }
        return relatedPublications;
    }
```

**Comment by landreev** [comment]
ok, so there will be BOTH a PR for a fix, and a line in the release notes telling other installations to fix their citation block by reimporting the tsv file.

**Comment by landreev** [comment]
This was a bug in schema.org export. There doesn't seem to be a way to get it triggered through the UI.
But this is how to reproduce it:
1. Make sure the displayFormat for **publicationUrl** is set correctly (to ```<a href="#VALUE" target="_blank">#VALUE</a>```); for example, by re-importing ```citation.tsv```.
2. Create a dataset with at least one Related Publication entry with a valid url; publish the dataset. 
3. Make sure ```lastExportTime``` is null in the dataset table for this dataset.
4. Run a full export:
   ```curl http://localhost:8080/api/admin/metadata/reExportAll```
(alternatively, sit and wait for the nightly export job to run, lol)

This should reset the **displayFormat** to ```#VALUE```!

Optionally, for extra careful verification, after step 2. rename and save the cached ```export_schema.org.cached```, then once the step 4. is completed, compare it to the re-exported version, to make sure LD JSON is still exported correctly.
