### ISSUE TITLE
XHTML changes not deployed on save from Netbeans

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#6208]
When I save a change in xhtml, it does get promptly copied into the target/dataverse-4.16 directory... which really is all it should take to "deploy" an xhtml file, normally. So somehow jsf/primefaces keeps caching the old copy past this point - ?
I'll keep researching...

**Comment by pdurbin** [comment]
One decision from tech hours so far, let's try backing out these pull requests independently to see if it gets us back to normal:

- remove orphaned Endorsed Java API specials #6141 
- Maven Offline support #6133

**Comment by pdurbin** [comment]
Something else to try is Watch and Deploy (WAD) from @AdamBien

From the README I wasn't sure if it only watches for Java changes but according to https://github.com/AdamBien/wad/issues/2 it might look for XHTML changes as well.

The idea here is to better understand how Netbeans is involved. We think Netbeans is hooking into a feature of Glassfish or something to allow "deploy on save" to work.

**Comment by poikilotherm** [comment]
Please keep me posted on this. If those PRs really would be a showstopper for Netbeans, that sounds like a bug in Netbeans...

**Comment by pdurbin** [comment]
Something else to look at backing out:

- 5f99037 increase buffer size for response committed error

**Comment by mheppler** [comment]
@poikilotherm You're off the hook -- for now. Backed out your changes in my local version of `develop` and still can not get XHTML changes to show in the browser without a full redeploy.

**Comment by poikilotherm** [comment]
![Woohoo!](https://media1.tenor.com/images/4a6158ad4f30c71f4fecf224cec12eb1/tenor.gif?itemid=5580903)

**Comment by mheppler** [comment]
And the winner is... 5f99037e5df918cf5f653c61971b5a701d690e58.

Reverted those changes, redeployed the app, and now I can make a simple XHTML change, refresh my browser, and see the change to the page without having to redeploy the entire app.

Thanks for the tip, @pdurbin. Sorry @sekmiller for having to assign this one to ya.

**Comment by landreev** [comment]
Steve, have you tried leaving the `BUFFER_SIZE` set to the high value, but setting the`REFRESH_PERIOD` to something like 60 sec.? - I'm curious what happens then...

**Comment by djbrooke** [comment]
Developers have a workaround so I'm de-prioritizing this for now.

**Comment by mheppler** [comment]
Closing in favor of **NetBeans deploy vs web.xml config - Increased buffer size breaks auto display on save (requires developer config workaround) #6953**>

Recently it was discovered that the culprit is just the `FACELETS_REFRESH_PERIOD` param. The `FACELETS_BUFFER_SIZE` has not been commented out in my web.xml and I'm seeing my XHTML changes without having to deploy manually.
