### ISSUE TITLE
User Notification Following Ingest

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#6214]
Users need to wait for files to ingest before publishing. To let them know when the ingests are complete (successfully or not) and that they can now publish, we could provide a notification (to exist in Dataverse and email).

Created as a new issue from #6157.

**Comment by djbrooke** [comment]
@alejandratenorio, @gerafp, are you working on this? I moved it to the "Community Dev" column but I can remove it if you're not working on it.  Thanks!

**Comment by alejandratenorio** [comment]
Hi @djbrooke, Yes, we are.

**Comment by alejandratenorio** [comment]
Hi @djbrooke,
We worked on this, before doing the pull request, i sent you a list of changes for your review.
https://github.com/CIMMYT/dataverse/commit/0c3522b7a8138f0dce6c29a081b74a72847f2552

We overloaded the sendNotificationEmail method to allow sending HTML code.


![image](https://user-images.githubusercontent.com/31973211/66498342-8127df00-ea83-11e9-8bd9-118409c1f5e1.png)

**Comment by djbrooke** [comment]
Thanks @alejandratenorio. Can you put this code up on an EC2 instance so that I can review with the design team? We'll also start to look at the code and give you guidance there.

**Comment by djbrooke** [comment]
Thanks @landreev for starting to review the code. @alejandratenorio @Gerafp please let us know when it's available on an instance. Thank you!

**Comment by alejandratenorio** [comment]
Hi @djbrooke , this is the url

https://sandbox.cimmyt.org
u: dataverseAdmin
p: dataverse.1

**Comment by djbrooke** [comment]
Thanks @alejandratenorio! I'll look tomorrow and may make some changes to the text.

**Comment by djbrooke** [comment]
I need to:

- Update the text in src/main/java/propertyFiles/Bundle.properties (line 190, 203, 640 at least)
- Add some/update information in the guides about notifications (https://github.com/IQSS/dataverse/blob/develop/doc/sphinx-guides/source/user/account.rst)

**Comment by alejandratenorio** [comment]
Hi @djbrooke, can i do a PR?

**Comment by djbrooke** [comment]
Sure, that's fine! We can discuss there. 

A quick question, is there any messaging when an ingest fails? Or only on success?
