### ISSUE TITLE
Internationalization of external tools

### ISSUE THREAD

**Issue by lubitchv** [IQSS/dataverse#6215]
Data Explore and Data Curation Tools need to know what language is used by user in Dataverse interface in order to launch its interface in the same language. Therefore json manifest file that connects dataverse to external tool will need additional parameter, for example:
`{
         "dvLocale": "{localeCode}"
 }`
In order to accommodate that new parameter changes in ExternalToolHandler,  ExternalToolServiceBean and ConfigureFragmentBean will be needed.

**Comment by pdurbin** [comment]
@lubitchv sounds great! Will you be making a pull request for this? If so, do you need any help?

**Comment by lubitchv** [comment]
@pdubrin Yes, I am going to do that. I just plan to add an additional parameter. That should not be difficult. Review and any suggestions would by helpful.

**Comment by pdurbin** [comment]
@lubitchv fantastic! I just moved this issue to the "community dev" column and assigned it to you. You might be interested in taking a look at pull request #5881 (or at least wait to branch from develop until after it has been merged because I think it's close).

**Comment by pdurbin** [comment]
@lubitchv hi! Heads up that pull request #5881 was merged! :smile:

**Comment by pdurbin** [comment]
@lubitchv me again. Heads up that I'm hacking on the external tools code a bit for #6229.
