### ISSUE TITLE
Root dataverse not shown when deploying on Payara 5

### ISSUE THREAD

**Issue by poikilotherm** [IQSS/dataverse#6216]
This issue has been triaged a while ago: see #5907, #5933 and #4172 

In the following, it doesn't matter if you are logged in or not - these problems occur way before the authz in `DataversePage.init()` can happen.

When deploying `develop` (6bebe7f4) to Payara 5, the following screen is shown:

![grafik](https://user-images.githubusercontent.com/5468333/65600039-8e32d180-df9f-11e9-912d-68a9a464042f.png)

After switching http://github.com/poikilotherm/dataverse/blob/develop/src/main/webapp/dataverse_header.xhtml#L313 to `<h:messages id="messages"/>`, you'll see this error message:

![grafik](https://user-images.githubusercontent.com/5468333/65597927-8e7c9e00-df9a-11e9-98ac-47f5c40afd4f.png)

As `f:viewAction`s are not executed when validation fails, `DataversePage.init()` will not be executed. Thus you have an empty `Dataverse` object in `DataversePage`, which results in all kind of funny side effects (because if no dataverse was present, it would have been set to `null` by `init()`), including the "New Dataverse" title, etc (see result in the first picture).

This has been verified by removing all code from `DatasetPage.init()` and inserting a `throw new RuntimeException` - nothing happens. See also [here](https://github.com/omnifaces/omnifaces/issues/147#issuecomment-121159860) and [here](http://incepttechnologies.blogspot.com/p/validation-in-jsf.html)

Next question: why is `alias` failing validation?
Answer: because setting the alias name in the empty `new Dataverse()` object at [`DataversePage`](http://github.com/poikilotherm/dataverse/blob/develop/src/main/webapp/dataverse.xhtml#L23) causes validation constraints to fail: [`Dataverse.java`](http://github.com/poikilotherm/dataverse/blob/develop/src/main/java/edu/harvard/iq/dataverse/Dataverse.java#L79-L84)

**Comment by poikilotherm** [comment]
This has been attacked to short notice availability of a pair programming partner here with knowledge about JSF. This was an evaluation to estimate options how to continue. Mentioning @djbrooke.

**Comment by scolapasta** [comment]
I'm going to ahead and close this issue as we've resolved it for #6230. (using the ideas that were suggested here, thanks @poikilotherm).
