### ISSUE TITLE
Edit Dataset: Saving a dataset that has filenames with internation characters, eg. Chinese, a second time, converts characters to unknown types.

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#622]
---

Author Name: **Kevin Condon** (@kcondon)
Original Redmine Issue: 4061, https://redmine.hmdc.harvard.edu/issues/4061
Original Date: 2014-06-02
Original Assignee: Leonid Andreev

---

This was found on dataverse-demo but had appeared before.

Uploading files with international characters in the filename works but then if you reedit the study and save, the filenames are mangled.

See: http://dataverse-demo.iq.harvard.edu/dataset.xhtml?id=155&versionId=57

**Comment by landreev** [comment]
Please retest, should be working now.

**Comment by kcondon** [comment]
OK, was able to upload file named: 方彝 and remained after adding another file. Closing.
