### ISSUE TITLE
permission to create a board for my installation of Dataverse

### ISSUE THREAD

**Issue by stevenmce** [IQSS/dataverse#6221]
Request for a new board for the ADA Dataverse

Github Users and usernames associated with this:
 - Steve McEachern (@stevenmce)
 - Marina McGale (@mdmADA)
 - Janet McDougall (@janetm)

**Comment by pdurbin** [comment]
Hi @stevenmce @mdmADA @janetm

@mdmADA is already a member of https://github.com/orgs/IQSS/teams/dataverse-readonly/members

I invited @stevenmce and @janetm . You two should go to https://github.com/IQSS and you should see a banner that looks something like this (but for IQSS):

<img width="1231" alt="Screen Shot 2019-09-25 at 9 04 48 PM" src="https://user-images.githubusercontent.com/21006/65650264-2187f900-dfd8-11e9-8c20-3beb8ee7ee9a.png">

You'll want to click "View Invitation" and then "Join". You should see something like this (again, but for IQSS):

<img width="1128" alt="Screen Shot 2019-09-25 at 9 05 27 PM" src="https://user-images.githubusercontent.com/21006/65650305-4a0ff300-dfd8-11e9-8dbc-63b80630f75c.png">

After that, any of you should be able to go to https://github.com/orgs/IQSS/projects and click "New Project" to see screens like these:

<img width="1227" alt="Screen Shot 2019-09-25 at 9 06 46 PM" src="https://user-images.githubusercontent.com/21006/65650348-7af02800-dfd8-11e9-934c-aecbce933e1b.png">
<img width="1164" alt="Screen Shot 2019-09-25 at 9 07 00 PM" src="https://user-images.githubusercontent.com/21006/65650350-7af02800-dfd8-11e9-86a1-6db9a9f34a6f.png">

Please make your board public so other installations of Dataverse can see your board and see which issues interest you the most.

**Comment by stevenmce** [comment]
New public board added - https://github.com/orgs/IQSS/projects/17

**Comment by pdurbin** [comment]
@stevenmce looks GREAT! Thanks! 🎉 

I just added your new board to the new and public (but not on a stable URL) spreadsheet I'm planning to point to the community at to help crowdsource some of this data. I have a little script that's combining data from various sources and here's how ADA's record looks in JSON format at the moment:

    {
      "name": "ADA Dataverse",
      "description": "The Australian Data Archive provides a national service for collecting, preserving, publishing and accessing digital research data.",
      "lat": -35.343784,
      "lng": 149.082977,
      "hostname": "dataverse.ada.edu.au",
      "country": "Australia",
      "continent": "Australia",
      "gdcc_member": true,
      "doi_authority": "10.26193",
      "board": "https://github.com/orgs/IQSS/projects/17"
    }

By the way, there are some additional fields that I don't have values from ADA for. I'm interested in:

- launch date (year, at least)
- fork URL
- contact email address (sometimes we check "adminEmail" via OAI-PMH but https://dataverse.ada.edu.au/oai?verb=Identify is closed, which is fine!)
- any kind of "About" website like how the "About" link at https://dataverse.tdl.org takes you to https://texasdigitallibrary.atlassian.net/wiki/spaces/TDRUD/pages/289144946/About

I don't need these right now (but I'll take them if you want to give them!). I'm just trying to give you a sense of some of the basic data I'm interested in tracking.

Thanks!! 🎉

**Comment by stevenmce** [comment]
Hi Phil,

Answers as follows:

Launch date: August 2017
Fork URL: Marina can advise
Contact email: adaINSERTANATSYMBOLHEREanu.edu.au
About website: https://ada.edu.au

Cheers,
Steve

**Comment by djbrooke** [comment]
@stevenmce , @pdurbin I'm going to close this since it seems all set.

**Comment by pdurbin** [comment]
@djbrooke sounds good. I guess the only other things I'd mention is that I'm linking to the project board on a the new map I made and that I wrote a little aggregator so we can all see which are the "hot" issues that are included on the boards of multiple installations. I'll put a couple screenshots below.

<img width="1160" alt="Screen Shot 2019-10-09 at 1 12 29 AM" src="https://user-images.githubusercontent.com/21006/66453424-447fc780-ea32-11e9-84cd-f14eb4ff5e40.png">

The map above with the "Project board" link comes from https://iqss.github.io/dataverse-installations/ and I wrote about it at "map of Dataverse installations, installations as a dataset, launch year" at https://groups.google.com/d/msg/dataverse-community/xFRXZ7BAuQA/q_fLaenBBgAJ

<img width="1576" alt="65918285-4b119d80-e3a7-11e9-8a25-9860676043d5" src="https://user-images.githubusercontent.com/21006/66453488-7ee96480-ea32-11e9-8b8d-7e1f5068328c.png">

I wrote about the list of aggregated issues above in the "boards for prioritizing issues (for each installation of Dataverse)" thread at https://groups.google.com/d/msg/dataverse-community/z8ugn2KzNSc/3xf4TXIqCQAJ
