### ISSUE TITLE
Error in glassfish server - When I'm deploying my application

### ISSUE THREAD

**Issue by lakshitha1629** [IQSS/dataverse#6225]
Please help me to fix this (error in glassfish - When I'm deploying my application)

_(glassfish 4.1,Windows 8,netbeans 8.2)_

**HTTP Status 500 - Internal Server Error**

**Type** Exception report

**message** Internal Server Error

**description** The server encountered an internal error that prevented it from fulfilling this request.

**exception** java.lang.RuntimeException: Error in multipart initialization

**Comment by pdurbin** [comment]
@lakshitha1629 hi! Unfortunately setting up a Dataverse dev environment isn't much fun on Windows. (I assume Netbeans installed ok for you, though.)

For #3927 a borrowed a Windows laptop and tried to get version 1 of Windows Subsystem for Linux but failed. I hear that version 2 of Windows Subsystem for Linux is available now. Have you tried it? You can see my notes for v1 at http://guides.dataverse.org/en/4.16/developers/windows.html#windows-subsystem-for-linux

If you can find a file called server.log in a path similar to glassfish4/glassfish/domains/domain1/logs/server.log and email it to support@dataverse.org I'd be interested in seeing what the RuntimeException is.

Do you have a Linux or Mac you can use instead? Or are you comfortable with Vagrant? Thanks for trying Dataverse on Windows!

**Comment by poikilotherm** [comment]
@pdurbin beware, he is on Windows **8**, not 10, so no WSL.
@lakshitha1629 you could try to get rolling fast in a VirtualBox VM using Linux.
You might also try to play with [IQSS/dataverse-kubernetes](https://github.com/IQSS/dataverse-kubernetes), where I just recently added dev support. This is a work in progress and I play with different things, but experiments, issues, feedback and PRs are welcome.

**Comment by djbrooke** [comment]
Hi @lakshitha1629 - I'm going to close this out since you've received some feedback from @pdurbin and @poikilotherm. Feel free to reply and reopen this if you still have issues with running Dataverse. Thank you!

**Comment by djbrooke** [comment]
Hi @lakshitha1629, please leave a comment here to let me know if you're still having issue and if you'd like us to reopen this. I didn't realize that you were unable to reopen issues. Sorry for the confusion.
