### ISSUE TITLE
Revise PR Template

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#6226]
In https://github.com/IQSS/dataverse/pull/6223#discussion_r329180952 @pdurbin mentioned that he just deletes most of the PR template (https://github.com/IQSS/dataverse/blob/develop/PULL_REQUEST_TEMPLATE.md). I do the same. 

Let's think about this, get some opinions (from other people or other projects) and change what's in the template.

**Comment by poikilotherm** [comment]
As discussed with @pdurbin [on IRC today](http://irclog.iq.harvard.edu/dataverse/2019-11-21#i_113036), more information in PRs would be usefull when reaching the QA column. @pdurbin, me and (as far as I understood it) most certainly @djbrooke and @kcondon, too, would like to communicate more about what things changed, what needs to be tested, etc.

It would be very helpfull to include a good and easy pattern (needs to be first timers compatible) on how to most efficiently draw a picture for reviewers, testers etc.

The K8s people have some nice ideas for this, maybe it's an inspiration: 
https://github.com/kubernetes/kubernetes/blob/master/.github/PULL_REQUEST_TEMPLATE.md

(These `/kind` thingies have bots attaching labels to the PR, which is not doable for normal contributors)

**Comment by poikilotherm** [comment]
In addendum: it might be a good idea to talk about where to put updates that happen after creating the PR in code review. 

- Should QA browse through all of this? 
- Should the author provide an enhanced description before it moves from review to QA? In small PRs this is no problem, but what about longer reviews with lots of chatter? 
- When using Waffle, the policy was "discuss in the issue". Nowadays that changed to "use the code review functions of GitHub" (which changed for good), but does it help QA?

**Comment by djbrooke** [comment]
Thanks @poikilotherm for the thoughts and for the links to the k8s example. I like to encourage face to face discussion whenever possible but that doesn't mean we can't to better here. I looked around at a few other projects (Canvas, EdX) and the k8s example was better. Just needs to add some QA-specific info. This is what I'm going to do:

- Create a proposed PR template based on k8s (will link branch here), add some proposed thoughts for QA as well
- Ask @scolapasta and the developers to discuss the proposed template during tech hours and make any changes.

From there, we'll get it out to the larger community for comment.
