### ISSUE TITLE
Add Issue Templates

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#6227]
Github offers issue templates. We should investigate these, and if we think they'd be useful, we should make use of them and update the documentation to explain their purpose.

https://help.github.com/articles/about-issue-and-pull-request-templates

**Comment by djbrooke** [comment]
@ysuarez, @pdurbin mentioned you may be interested in this. If so, let me know and I'll assign it to you and we can work on it together. If you're not interested or if you don't have time to work on this right now, let me know and I'll work on it in the sprint starting 10/9.

**Comment by ysuarez** [comment]
@djbrooke yes, I would like to work on this with you. I will write out some of my specific ideas inspired by what I saw in the PR templates of a couple of other open source projects. 

BTW, from my extremely brief notes from the 2019 Dataverse community meeting on this, I see that I was thinking of somehow creating a "fork in the road" for submitting issues. By this I mean somehow using these Github templates to better guide non-tech savvy issue submitters to provide enough details for submitting a bug, versus submitting a new feature request. Though I don't want the project to end up with a long and/or complicated issue template, and my idea may be impossible to achieve in the end.

**Comment by ysuarez** [comment]
@djbrooke nevermind, my memory failed me. This is the "fork in the road" I was originally thinking about...

![alt text](https://help.github.com/assets/images/help/issues/new-issue-page-with-multiple-templates.png "New issue page showing issue template choices")

from: https://help.github.com/en/articles/about-issue-and-pull-request-templates

I assume within those two options for a new issue we can create a Markdown based template with suggested fields for the users to fill out for the respective type of issue.

**Comment by pdurbin** [comment]
@ysuarez thanks for jumping in!

It seems like this article describes an "issue template builder" or wizard for setting this up: https://help.github.com/en/articles/creating-issue-templates-for-your-repository

As a readonly user of this repo, I'm not sure if you have access to that wizard or not.

The GitHub docs don't seem to explain how to set up the new style issue templates manually but I think https://github.com/publiclab/plots2/issues is a good example of how fancy you can get. Here's a screenshot:

<img width="884" alt="Screen Shot 2019-09-29 at 6 31 13 AM" src="https://user-images.githubusercontent.com/21006/65831059-3fc55180-e283-11e9-83d4-f0438f8b4219.png">

We can take a look at the YAML they used at https://github.com/publiclab/plots2/pull/5967

**Comment by ysuarez** [comment]
@djbrooke sorry for the radio silence, I had a hackathon competition last week and got slammed. I am currently attending the Islandora conference, and we were talking about issues. This gave me a chance to create my own private repo to try out creating Github Issue templates. Would you like me to add you to this private repo (I can make it public too) so we can work together on this?

Let me know.

**Comment by djbrooke** [comment]
Sure thing @ysuarez, public is fine with me unless there's some reason not to open it up.

**Comment by ysuarez** [comment]
@djbrooke I made it public and added you as a collaborator.

https://github.com/ysuarez/github_issue_templates_experiments

**Comment by pdurbin** [comment]
@ysuarez your templates look good to me! 😄

**Comment by ysuarez** [comment]
@pdurbin for the record, those are the Github default templates and their content. It was not customized by me at all.

Here are some screenshots of the defaults....

![image](https://user-images.githubusercontent.com/725449/66438883-f94ac200-e9fb-11e9-81e4-0293772e01ec.png)


![image](https://user-images.githubusercontent.com/725449/66438863-f059f080-e9fb-11e9-84af-2bd291473496.png)

![image](https://user-images.githubusercontent.com/725449/66438969-3747e600-e9fc-11e9-98b6-2495eb814f0a.png)

**Comment by pdurbin** [comment]
Cool. The defaults seem like a good starting point. We can always iterate on them in the future.

We aim for "small chunks" in our development process. And we use the phrase "incremental progress" a lot. The idea is that every pull request, no matter how small, helps move us forward.

Oh! That reminds me! It's Hactoberfest! I'm totally adding that label to this issue. See also https://groups.google.com/d/msg/dataverse-community/ootwCQL-4K4/00QO3__8CQAJ

**Comment by ysuarez** [comment]
@djbrooke Did you want to coordinate by email/slack/phone to deploy these templates? I do not have access to Dataverse repo to do it, but we can try out content variations on my test repo. Let me know.

**Comment by djbrooke** [comment]
Hey @ysuarez thanks for checking in. I'm excited to see what you've been working on. Let's use your test repo to discuss and edit and then we can just bring in the .md files to the Dataverse repo. 

If you want to point me at what you have, we can set up a video call next week sometime. Would either 1 PM on Wednesday or 3 PM on Thursday work for you?

**Comment by ysuarez** [comment]
@djbrooke I currently have conflicts for the two times you suggested. DO you have other times you could suggest? How about Thursday at 10 AM EST or Thursday at 2 PM EST?

For the record, so far I have set up the issue templates to use their default content, as seen in the screenshots above. Though of course we can customize to our liking.

**Comment by djbrooke** [comment]
Hi @ysuarez, sorry to miss your previous. Would Thursday at 2 PM still work for you? We can look at some times next week if it works for you.

**Comment by pdurbin** [comment]
@ysuarez hi! Anything I can do to help? Honestly, just about anything you propose would probably get accepted given the discussion of pull request #6398 in tech hours yesterday. That is to say, we're flexible and willing to experiment. 😄

**Comment by pdurbin** [comment]
Some nice issue templates are being added to OpenDP as part of https://github.com/opendp/opendp/pull/293

Here's a preview:

<img width="717" alt="Screen Shot 2021-09-16 at 10 45 31 AM" src="https://user-images.githubusercontent.com/21006/133633533-37f1cf0d-d2be-46d0-97ca-3034bea27240.png">

@ysuarez are you still interested in working on this? Maybe we'll go ahead without you. Sorry! 😄

**Comment by ysuarez** [comment]
@pdurbin Sorry for the delay. I do not mind if you go ahead without me, do what is best for Dataverse. I am still interested but I just kept forgetting to make the time for it with my other commitments. I just blocked time this Sunday for it, though that may be too late for Dataverse. I recently signed myself up to create issue templates for the Islandora community, so it will be worth it  to work on learning how to create these templates for Dataverse and/or Islandora. Even if you don't use my help I can still watch and learn through this Dataverse issue so that I can better create draft issue templates in general.

**Comment by poikilotherm** [comment]
You might be interested in issue forms (currently in beta), too.

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms

**Comment by ysuarez** [comment]
@pdurbin (and others)... 
Do you want me to let others lead the creation of a PR for this issue? I don't mind, I care for what is best for the community. Do you prefer I try to explore this weekend using the current way of creating issues or do you want me to look into "issue forms" which are in beta, but look useful? 

Maybe I or someone else could start with the current way to create an issue template to get the Dataverse community started, and then work on figuring out how to use and setup "issue forms"? Either way I plan to review and create soem sample issue templates for Dataverse and Islandora this weekend and will put in a PR.

**Comment by pdurbin** [comment]
@ysuarez if you're comfortable with it, please go ahead and create a pull request. (I would suggest distinguishing between a bug and a feature request.) I say this because this issue is unprioritized so it's unknown when we'd get around to it. Whatever you do, I'm sure we can iterate on it. You're welcome to use the new "forms" thing if you want, but it's up to you. Thanks!

**Comment by ysuarez** [comment]
I added a PR last night, and I erred on the side of being verbose when creating the content for both templates. Feel free to suggest any changes major or small, like cutting out the instructions in the top section wrapped by HTML comments. 

Note: For additional consideration based on this PR/branch 

Github issue templates allow for...
1) Placeholder "titles" of issues. As an experiment I made the placeholder title of the feature request be "Feature Request/Idea:", but it could be left blank.

2)  Pre-labeling of issues. That means that, for example, you could create a new label like "Features: uncategorized" for new features to better track them.

3) Pre-assigning repo users to new issues. If you wanted a certain users to be assigned to new bugs or features.

4) A config.yml file can be used to further tweak the template chooser, but I will wait for the first commit to be merged before trying to experiment with config.yml. More info here: [Configuring the template chooser](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser0
