### ISSUE TITLE
support/bless Postgresql 10+

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#6231]
RHEL/CentOS8 includes PostgresQL-10 by default, and as such the Postgres repos don't appear to support PostgresQL < 10 (a psycopg2 library incompatibility at minimum).

You may test Dataverse over versions 10, 11, and 12 in EC2 by adjusting postgresql.version in the dataverse-ansible group_vars pending the merge of https://github.com/IQSS/dataverse-ansible/pull/115

**Comment by djbrooke** [comment]
Thanks @donsizemore for the report. Is this something that you're willing to work on or should we plan to get it into a sprint in the near future?

**Comment by donsizemore** [comment]
@djbrooke it occurred to me that I a) have a CentOS 8 VMs which I used to update dataverse-ansible and b) I've been working with Gustavo and Phil to automate the API test suite through dataverse-ansible, so I can volunteer to take it on, but... speaking on behalf of IQSS is a terrifying concept =)

**Comment by pdurbin** [comment]
Since this question is bound to come up... yes, Amazon RDS, the "Postgres as a service" that we use for Harvard Dataverse, supports version 10 and above. Below is a screenshot from https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_PostgreSQL.html

![Screen Shot 2019-09-30 at 5 16 26 PM](https://user-images.githubusercontent.com/21006/65917808-3f71a700-e3a6-11e9-97e2-1b28e155be90.png)

**Comment by djbrooke** [comment]
We trust you @donsizemore! :)

**Comment by donsizemore** [comment]
Ran the API test suite against 4.16 on CentOS 8 using Postgresql 10, which failed. Tarball of surefire-reports/ and server.log* attached.
[centos8_pg10_logs.tar.gz](https://github.com/IQSS/dataverse/files/3681572/centos8_pg10_logs.tar.gz)

**Comment by donsizemore** [comment]
Ran the API test suite against 4.16 on CentOS 7 using Postgresql 10 in EC2. Only failure was SearchIT; tarball attached.
[api_tests_pg10.tar.gz](https://github.com/IQSS/dataverse/files/3687661/api_tests_pg10.tar.gz)

**Comment by pdurbin** [comment]
@donsizemore and I talked about this issue the other day. He's not actively working on it so I unassigned him.

**Comment by donsizemore** [comment]
Just tried against 4.17 this afternoon. SearchIT and AccessIT failed - deadlocks detected (in EC2)
[PG10_server.log.zip](https://github.com/IQSS/dataverse/files/3853081/PG10_server.log.zip)

Bumping Ansible role to 4.18, then will run again.

**Comment by donsizemore** [comment]
RHEL/CentOS8 doesn't easily offer python3-psycopg2 for Postgres 9.6 so I've run a number of test installations on Postgresql10 (the default in RHEL/CentOS8) without incident. The deadlocks in my previous comment seem to be related to speed of storage. Closing.
