### ISSUE TITLE
Thumbnail api call returns original file when thumbnail not available

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#6240]
Calling /api/access/datafile/\<id\>?imageThumb=400 works for file types that have a thumbnail/where a thumbnail can be generated, but it just sends the original file for filetypes for which thumbnails can't be generated. It seems like a 404 would be a better default (avoids downloading large files accidentally and I think it stops the bad thumbnail call from counting a download). 
For a quick look, it appears that not being able to create a thumbnail causes the execution to hit this in the Access class:
```
            } else {
                // Service unknown/not supported/bad arguments, etc.:
                // TODO: throw new ServiceUnavailableException(); 
            }
```
Unless there are objections, or better ideas, I can look into throwing this exception or otherwise replying with a 404.

**Comment by pdurbin** [comment]
@qqmyers if it's not too much trouble to put together a pull request, it'll at least get on our radar in terms of code review and thinking about possibilities. (I recently made two small pull requests at once for different approaches to solving an issue.) Thanks for offering!

**Comment by qqmyers** [comment]
Will do -we're looking at pulling thumbnails for specific files into an external display page and it will be cleaner if there are only 404s to deal with.
