### ISSUE TITLE
Edit Dataverse - Cancel on edit dataverse form refreshes with empty dataverse pg (viewMode)

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#6258]
While working on a new branch off of `develop`, I noticed this issue on my localhost, and replicated it on demo.

From the Edit Dataverse form, click the Cancel btn, the pg reloads to display the "view" version on the dataverse pg, but the results cards are missing, and the type facets show "null". (Oddly the other facets below those have counts. See screenshot.)

There are no errors in the Glassfish server log.

![Screen Shot 2019-10-07 at 10 49 17 AM](https://user-images.githubusercontent.com/687227/66322837-bfd96000-e8f0-11e9-880b-dabba6d0ad57.png)

**Comment by pdurbin** [comment]
@mheppler same behavior on phoenix which happens to be running 064f152. Good catch.

**Comment by scolapasta** [comment]
Highly likely to be caused be the View scoped / Request scoped change. (so cancel needs to work differently now)
