### ISSUE TITLE
reorder facets to allow custom metadata blocks as topmost content of pane

### ISSUE THREAD

**Issue by joelmarkanderson** [IQSS/dataverse#6259]
My researchers would like the weight of their custom metadata blocks to bubble up to the top of the left navigation pane in the main page. Right now that position is dominated by  Dataverse Category, Publication Year/Status, Author Name, Keyword Term, etc. If these all receive configurable weighting/positioning, that would be ideal. Thanks.

**Comment by djbrooke** [comment]
Thanks @joelmarkanderson. Once we get our dataset and file redesign done, we'll be looking at a dataverse page redesign and we can consider this.

**Comment by pdurbin** [comment]
@joelmarkanderson does this new feature of 5.12 help?

https://guides.dataverse.org/en/5.12/api/native-api.html#set-metadata-block-facets-for-a-dataverse-collection

This is the PR where it was developed:

- #8793
