### ISSUE TITLE
Ability to Publish Dataverse when Trying to Publish Dataset (if user has permission to do so)

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#626]
---

Author Name: **Elizabeth Quigley** (@eaquigley)
Original Redmine Issue: 4065, https://redmine.hmdc.harvard.edu/issues/4065
Original Date: 2014-06-03

---

Need to add in functionality so that a user can publish a dataverse and a dataset at the same time if they are trying to publish a dataset in an unpublished dataverse. This will relate to permissions as the system will be able to identify that a user has access to publish the dataverse. If not, then we need messaging that states why they can't publish the dataset.

**Comment by scolapasta** [comment]
We'll need to think how this works with dataverses within dataverses (that are all unpublished). Maybe we can add a simple only one dataverse up logic for 4.0, while we think about the broader issue).

**Comment by sekmiller** [comment]
Based on discussion w/Gustavo and Liz we identified 3 scenarios.
1) You don't have permission to publish the owning DV
2) You have permission to publish owning DV and  the "grandparent" is published.
2) You have permission to publish owning DV and  the "grandparent" is NOT published. (hopefully unlikely).

**Comment by sekmiller** [comment]
Logic and first pass at popups and bundle changes checked in.  Pop-ups may need a little love and Liz will modify the bundle messages.

**Comment by eaquigley** [comment]
messages for @sekmiller 
- [ ] Grandparent and parent aren't published (i'd like them broken up into lines as shown below): 
This dataset cannot be published until
(grandparent dv w/link)
(parent dv w/link)
are published.
- [ ] Parent isn't published (no permission to do so)
This dataset cannot be published until
(parent dv w/link)
is published by its administrator. 
- [ ] Parent isn't published (permission to do so)
This dataset cannot be published until
(parent dv w/link) 
is published. Would you like to publish both right now?
Buttons: Yes, publish both. No.

**Comment by scolapasta** [comment]
For maintainability of these (and possibly for internationalization if other languages format their sentences structures differently) we should keep these as one bundle property per message. You'll have to use <outputFormat> and put <br/> I think in the bundle.

**Comment by sekmiller** [comment]
Messages are redone per notes above in a single bundle statement for each scenario

**Comment by sekmiller** [comment]
A new build is required before testing can be done...

**Comment by eaquigley** [comment]
Grandparent & Parent not published scenario: Publish button is not appearing at all. After I published the grandparent and went back to the dataset page, two publish buttons appeared. 

Passing back to @sekmiller to take a look.

**Comment by sekmiller** [comment]
I fixed the publish button render.  We'll need a new build before it can be tested....

**Comment by eaquigley** [comment]
Works. Closing ticket.
