### ISSUE TITLE
As someone running an installation of Dataverse, I want metrics on my users

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#6261]
@erikbuunk and I are working on metrics for Dataverse and plan to write some SQL and eventually an API endpoint to create a tabular file about users in an installation of Dataverse.

We are planning on the following columns for now:

- id
- affiliation
- createdtime
- lastlogintime
- lastapiusetime
- lastusetime

**Comment by djbrooke** [comment]
@pdurbin sorry we weren't able to catch up today (trainings and meetings). I'll let you take your cue from @erikbuunk in regards to the data from Harvard Dataverse, but let's hold off on adding any API endpoints until we get a chance to discuss as a team and community.

**Comment by pdurbin** [comment]
@djbrooke no problem. @erikbuunk and I were just playing with the data in Tableau (screenshot below) and we're not even entirely sure that the one SQL script we came up with in 6991258 will be sufficient. More discussion is needed but at least we have some data to play with. A good day of hacking! 😄 

![Screen Shot 2019-10-08 at 6 03 01 PM](https://user-images.githubusercontent.com/21006/66436794-0fee1a80-e9f6-11e9-9fdf-82949030e354.png)

**Comment by pdurbin** [comment]
@djbrooke @erikbuunk and I met today and it sounds like this issue will disappear from the board for now. I'll let @djbrooke decide whether to close it or move it to some other column.

**Comment by pdurbin** [comment]
I still think it would be nice to know how many users are out there but we have other priorities. If someone wants to work on this (again, there's a stub at 6991258), please get in touch! Otherwise.... closing.
