### ISSUE TITLE
Linking Dataverses does not show proper number of Datasets in facet results

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#6262]
When you link an entire dataverse to another dataverse, it does not display the number of datasets in the linked dataverse, on the target dataverse page:
see https://dataverse.harvard.edu/dataverse/HarvardUniversity
Where I have linked several dataverses with multiple collections and the only dataset facet that shows (1) is for the single dataset I linked.

Merce wants it to display #datasets contained within the linked dataverses.

**Comment by mheppler** [comment]
Looking at the Internet Connectivity Statistics dataverse, which was linked to Harvard University Dataverse, it appears that in addition to missing the 2 child datasets, it is missing 5 child dataverses (however 4 of those are empty, only Country Profiles dataverse has any datasets).

**Comment by mheppler** [comment]
Related to #4936.

**Comment by TaniaSchlatter** [comment]
Screen shot to indicate where this shows in the UI:

<img width="1387" alt="linked_counts_incomplete" src="https://user-images.githubusercontent.com/15386424/66419000-46656e80-e9d1-11e9-8b99-eb666e1e62b6.png">

**Comment by sbarbosadataverse** [comment]
The screen shot showing 1 dataset facet

<img width="1594" alt="Screen Shot 2019-10-08 at 2 06 27 PM" src="https://user-images.githubusercontent.com/8322346/66420912-dce75f00-e9d4-11e9-9abd-3ba61d94beb5.png">

**Comment by djbrooke** [comment]
@sbarbosadataverse I'm assuming this is happening because we want to avoid double (or triple, etc.) counting as we roll up to higher levels. I can see why it's confusing here but I can't think of an easy solution for this. I'll think about this, but suggestions welcome.

**Comment by sbarbosadataverse** [comment]
@djbrooke Not sure what the reasoning was, but Merce would like the numbers to display datasets linked. Thanks

**Comment by djbrooke** [comment]
@sbarbosadataverse Got it, I understand the request in this context, but we don't want to trade one problem for another. I'll work with Merce to learn more and implement a solution here.

**Comment by scolapasta** [comment]
This seems to me like it would be an indexing issue (though I did try reindeixing one of the datasets in question and that didn't "add it"). I thought this used to work, i.e. link a dataset all it's children would be linked, as well.

(double counting shouldn't be a risk, as the datasets in question would still be one "document" in Solr)

**Comment by scolapasta** [comment]
To add more, I think the logic in the indexing would have to check if a parent was linked (and up the tree to see if any parent were linked), so it's a little more complicated than just a simple indexing issue.

I'm still a little surprised that we didn't do this originally (though there are definitely performance considerations with these recursive looks).

**Comment by djbrooke** [comment]
- This may be a design shortcut made back in the move to 4.0, we should revisit
- Child Datasets of linked dataverses should be discoverable using search within the host dataverse
