### ISSUE TITLE
Add API endpoints to help manage API tokens

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#6266]
We want to add 3 new endpoints for API token management:

- one that returns the expiration date of a token
- one that allows you to regenerate a new token
- one that allows you to remove the existing token

**Comment by scolapasta** [comment]
Note: this will involve moving some code from backing bean to business layer.

**Comment by poikilotherm** [comment]
I just stumbled over this issue and PR and thought about a possible connection to #6286.

Do you think it would be feasible to add an admin API endpoint to generate a new token for a given user which expires in short time and is returned after creation? It would allow to easily grab a temporary API token for loading data...

**Comment by djbrooke** [comment]
Hi @poikilotherm, we'll move this through as is since there's an external project relying on us adding this and I don't want to increase scope. This is not a comment on the merit of your proposal, I just want to keep this moving. :)
