### ISSUE TITLE
Add expiration date and delete button to UI for API tokens

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#6267]
On the API token tab of the user page, add the expiration date of the token and a button to delete the exisiting token (currently only have a regenerate token button).

This would match the API logic introduced in  #6266

**Comment by TaniaSchlatter** [comment]
Quick mockup from our discussion, showing what needs to be added to the existing UI:

<img width="1227" alt="API expiration" src="https://user-images.githubusercontent.com/15386424/67408418-f072f800-f586-11e9-9b9e-8c4436333a5d.png">

**Comment by mheppler** [comment]
Cleaned up api token experation date layout on api token tab of account pg.

<img width="1158" alt="Screen Shot 2019-11-15 at 3 22 22 PM" src="https://user-images.githubusercontent.com/687227/68973542-8ed82f00-07bc-11ea-83b8-b2420a73ebb7.png">

**Comment by TaniaSchlatter** [comment]
If the time is hard coded to a year, let's:
a) add a few words of text to the page:
"Your API Token is displayed below after it has been created, and is valid for a year. Checkout our API guide..."

b) add an "Expired" message:
![screen_shot_2019-11-18_at_2 44 36_pm](https://user-images.githubusercontent.com/15386424/69166992-2772f580-0ac2-11ea-9977-ca64ccd62055.png)

Thanks for catching, @kcondon and for mock ups, @mheppler

**Comment by mheppler** [comment]
Added api token expiration warning and error msgs to bundle and xhtml, needs backend render logic. Passing to @sekmiller.

**Comment by sekmiller** [comment]
@TaniaSchlatter, @mheppler what is our definition of "about to expire"?

**Comment by TaniaSchlatter** [comment]
I don't think we need the warning in the UI. Users will have the date and timeframe in front of them. That's why I didn't include it in the note above.
