### ISSUE TITLE
As a translator, I'd like to know which external tools are translatable

### ISSUE THREAD

**Issue by juancorr** [IQSS/dataverse#6277]
From e-cienciaDatos, we are interested in a complete multilingual Dataverse installation, including the external tools. We like to know which external tools are translatable and eventually, participate in their Spanish translation.

**Comment by pdurbin** [comment]
Don't look now but @juancorr also has pull request https://github.com/QualitativeDataRepository/dataverse-previewers/pull/18 in for a Spanish translation of the File Previewers!!! 🎉 🎉 🎉 

Go go go! 🚀

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
