### ISSUE TITLE
SPSS file does not get properly ingested in Dataverse, why? 

### ISSUE THREAD

**Issue by mshariful** [IQSS/dataverse#6288]
Hello,
Could you please tell me why this spss file does get properly ingested?
I do not see any Explore button (for file type DTA, SPSS; for txt file I do see the button) AND
I do not get multi-option download button. I simply get a download button offering to download the data in its original format.
Here is the link : https://github.com/mshariful/SPASS/blob/master/survey.sav
Thanks,
Sharif

**Comment by pdurbin** [comment]
@mshariful thanks for the bug report. I uploaded it to https://dev2.dataverse.org/dataset.xhtml?persistentId=doi:10.5072/FK2/8HTD34 and it looks pretty good in the Spreadsheet Viewer and Data Explorer. Below are some screenshots.

![Screenshot from 2019-10-18 07-39-13](https://user-images.githubusercontent.com/21006/67091457-a64ed880-f17a-11e9-9b24-ae0c5d76222b.png)

![Screenshot from 2019-10-18 07-39-27](https://user-images.githubusercontent.com/21006/67091456-a64ed880-f17a-11e9-9546-a4a6e9b2de9f.png)

![Screenshot from 2019-10-18 07-40-01](https://user-images.githubusercontent.com/21006/67091454-a5b64200-f17a-11e9-8b0d-5e8b7ac6491a.png)

That "dev2" server is running 731f160 from the "develop" branch as of this writing (I also tried it on https://demo.dataverse.org which is running 4.17 and the file was successfully ingested there too). I spin up dev2 using the ec2 script at https://github.com/IQSS/dataverse-sample-data . Can you please remind me how you are installing Dataverse and which version you are running?

**Comment by mshariful** [comment]
They look really cool. But why it does not work with my installation?!!  Could you please suggest? 
As I mentioned above....I do not see any Explore button (for file type DTA, SPSS; for txt file I do see the button) AND I do not get multi-option download button.

**Comment by pdurbin** [comment]
@mshariful as we discussed in IRC, my suspicion is that it's a bug in dataverse-docker. Please close this issue after you create a new issue in https://github.com/IQSS/dataverse-docker/issues (and please link it here). Thanks!

**Comment by pdurbin** [comment]
@mshariful thanks for creating https://github.com/IQSS/dataverse-docker/issues/28 ! I'm glad you got it working using https://github.com/IQSS/dataverse-kubernetes (good job, @poikilotherm ). 😄
