### ISSUE TITLE
Dataset Role Management API

### ISSUE THREAD

**Issue by flaviofrancisco** [IQSS/dataverse#6290]
As Dataverse user, I would like to assign a specific role/user to a specific dataset using the Native Api. As we can do with Dataverse. I didn't found it in the documentation.

Thanks in advance;
Flavio.

**Comment by pdurbin** [comment]
@flaviofrancisco unfortunately, it's not possible to assign roles to datasets using any Dataverse API. In 5fa140a I stubbed out some code to allow this but never completed it. If someone wants to make a code contribution to finish this off, please get in touch! 😄 

It is possible to **list** role assignments at the dataset level: http://guides.dataverse.org/en/4.17/api/native-api.html#list-role-assignments-for-a-dataset

It is also possible to assign roles at the parent dataverse level (these docs could be way better): http://guides.dataverse.org/en/4.17/api/native-api.html#assign-a-new-role-on-a-dataverse

**Comment by djbrooke** [comment]
- Will use same business logic as the UI
- We hope this is already in the command infrastructure
- Integration Tests should be added

**Comment by djbrooke** [comment]
Hi @flaviofrancisco -- this has been merged and will be included in the next release.
