### ISSUE TITLE
File previewers and other areas of the code do not work if Dataverse server is under http (not https)

### ISSUE THREAD

**Issue by juancorr** [IQSS/dataverse#6296]
Access to file previewers fail when Dataverse server (the server with the file to preview) is under http and not under https.

Dataverse code is taking the site url from the SystemConfig.getDataverseSiteUrlStatic method (with the code _hostUrl = "https://" + hostName;_) and not paying attention to the toolURL parameter in the externaltool table in the database.

**Comment by djbrooke** [comment]
Hey @juancorr, apologies if I'm misunderstanding, but I know that we strongly recommend https:

http://guides.dataverse.org/en/latest/installation/config.html#forcing-https

I'm not sure if the right answer here is:

- Updating this to allow http 
- if this and other areas of the application code are expecting https, updating our docs to say that HTTPs is required
- Other?

I'll let someone more technical than me provide a better answer here.

**Comment by pdurbin** [comment]
I think @juancorr has a good point. At a high level we do want to encourage HTTPS but I've run into this problem too. @donsizemore helped me out a done by enabling certs and HTTPS in dataverse-ansible so I could easily demo Data Explorer and File Previewers.

All that said, the fix would be to revisit the logic at https://github.com/IQSS/dataverse/blob/v4.17/src/main/java/edu/harvard/iq/dataverse/util/SystemConfig.java#L339 and I'll post a screenshot for the coders since there's isn't all that much code:

<img width="624" alt="Screen Shot 2019-10-21 at 1 17 08 PM" src="https://user-images.githubusercontent.com/21006/67227527-66e7ec80-f405-11e9-8cd1-e4dd2a580d9c.png">

**Comment by poikilotherm** [comment]
Please stay compatible with plain HTTP. Demo sites, test installation etc might not be using HTTPS, but want to test previewers.

**Comment by juancorr** [comment]
Thanks pdurbin, another subject is that the local URL parameter put by the
curl command in the database is ignored.

**Comment by djbrooke** [comment]
Thanks @pdurbin @poikilotherm @juancorr. Sounds like we'll not want to take the path of requiring https :)

**Comment by sekmiller** [comment]
@juancorr we took a look at this issue, and there doesn't seem to be a problem with the dataverse code. It's properly using the toolUrl from the external tool and passing a proper url for the file. The issue that we have seen is that when you use the version of the tool hosted at GitHub such as ( https://qualitativedatarepository.github.io/dataverse-previewers/previewers/SpreadsheetPreview.html) and pass it a file from your http://LocalHost it fails, but only in Safari.  it is successful in FireFox and Chrome.

What browser are you using? (and which version and OS)?

Also, if we cloned the QDR repo and served it locally it works in Safari as well.

**Comment by juancorr** [comment]
@sekmiller, I have tested it with Firefox and Chromium over Linux. I had not used the localhost in curl command (I do not remember the configuration in the Dataverse part)

I will check last Dataverse code and last File Preview code next Monday when I return to the office.

**Comment by djbrooke** [comment]
@juancorr any news?

**Comment by juancorr** [comment]
Hi  @djbrooke and @sekmiller,

  sorry for the late response. We have the same problem yet. You can see it
in
http://oaimadrono.uned.es:8080/dataset.xhtml?persistentId=doi:10.21950/UQAK4C .
Previewers are searched in https.
http://oaimadrono.uned.es/dataverse-previewers/previewers/TextPreview.html?fileid=4259&siteUrl=
*https*://oaimadrono.uned.es:8080&datasetid=4125&datasetversion=1.0


  We have installed the develop Dataverse branch (updated two hours ago)
and the master dataverse-previewers branch.

  My database:
 id |     description      |  displayname  |

toolparameters
                                                                      |
                                 t
oolurl                                   |  type   |   contenttype   |
scope | haspreviewmode
----+----------------------+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------

-----------------------------------------+---------+-----------------+-------+----------------

26 | Read the text file.  | Read Text     |
{"queryParameters":[{"fileid":"{fileId}"},{"siteUrl":"{siteUrl}"},{"key":"{apiToken}"},{"datasetid":"{datasetId}"},{"datasetversion":"{datasetVersion}"}]}
| *http://oaimadrono.uned.es
<http://oaimadrono.uned.es>*/dataverse-previewers/previewers/TextPreview.html
| EXPLORE | text/plain      | FILE  | t
27 | Read a pdf document. | Read Document |
{"queryParameters":[{"fileid":"{fileId}"},{"siteUrl":"{siteUrl}"},{"key":"{apiToken}"},{"datasetid":"{datasetId}"},{"datasetversion":"{datasetVersion}"}]}
| *http://oaimadrono.uned.es/
<http://oaimadrono.uned.es/>*dataverse-previewers/previewers/PDFPreview.html
 | EXPLORE | application/pdf | FILE  | t
(2 rows)

My domain.xml:
        <jvm-options>
-Djavax.xml.parsers.SAXParserFactory=com.sun.org.apache.xerces.internal.jaxp.SAXParserFactoryImpl
</jvm-options>
       <jvm-options>-Ddataverse.fqdn=oaimadrono.uned.es:8080</jvm-options>
       <jvm-options>
-Ddataverse.rserve.password=${ALIAS=rserve_password_alias}</jvm-options>
       <jvm-options>-Ddoi.username=</jvm-options>
       <jvm-options>-Ddoi.password=${ALIAS=doi_password_alias}</jvm-options>
       <jvm-options>-Ddoi.baseurlstring=</jvm-options>

Juan Corrales

**Comment by juancorr** [comment]
I have written the response from the mail and there are some lines with wrong characters:
The previewers URL is 
http://oaimadrono.uned.es/dataverse-previewers/previewers/TextPreview.html?fileid=4259&siteUrl=https://oaimadrono.uned.es:8080&datasetid=4125&datasetversion=1.0

and the database externaltool table:
 id |     description      |  displayname  |                                                                       toolparameters                                                                       |                                  t
oolurl                                   |  type   |   contenttype   | scope | haspreviewmode 
----+----------------------+---------------+------------------------------------------------------------------------------------------------------------------------------------------------------------+-----------------------------------
-----------------------------------------+---------+-----------------+-------+----------------
 26 | Read the text file.  | Read Text     | {"queryParameters":[{"fileid":"{fileId}"},{"siteUrl":"{siteUrl}"},{"key":"{apiToken}"},{"datasetid":"{datasetId}"},{"datasetversion":"{datasetVersion}"}]} | http://oaimadrono.uned.es/datavers
e-previewers/previewers/TextPreview.html | EXPLORE | text/plain      | FILE  | t
 27 | Read a pdf document. | Read Document | {"queryParameters":[{"fileid":"{fileId}"},{"siteUrl":"{siteUrl}"},{"key":"{apiToken}"},{"datasetid":"{datasetId}"},{"datasetversion":"{datasetVersion}"}]} | http://oaimadrono.uned.es/datavers
e-previewers/previewers/PDFPreview.html  | EXPLORE | application/pdf | FILE  | t

**Comment by pdurbin** [comment]
@juancorr I'm seeing a CORS problem at http://oaimadrono.uned.es/dataverse-previewers/previewers/TextPreview.html?fileid=4259&siteUrl=https://oaimadrono.uned.es:8080&datasetid=4125&datasetversion=1.0

I'll attach a screenshot below, which shows this error:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://oaimadrono.uned.es:8080/api/datasets/4125/versions/1.0. (Reason: CORS request did not succeed).

<img width="1971" alt="Screen Shot 2019-11-06 at 6 11 54 AM" src="https://user-images.githubusercontent.com/21006/68293719-8a917080-005c-11ea-8a1e-0730ef6a43dc.png">

This is the file I clicked "Explore" on: http://oaimadrono.uned.es:8080/file.xhtml?persistentId=doi:10.21950/UQAK4C/4O7RLS&version=1.0

**Comment by juancorr** [comment]
Real problem is the change to https.
Previews URL should be (with siteUrl=http://oaimadrono)
http://oaimadrono.uned.es/dataverse-previewers/previewers/TextPreview.html?fileid=4259&siteUrl=http://oaimadrono.uned.es:8080&datasetid=4125&datasetversion=1.0
Not (with siteUrl=https://oaimadrono)
http://oaimadrono.uned.es/dataverse-previewers/previewers/TextPreview.html?fileid=4259&siteUrl=https://oaimadrono.uned.es:8080&datasetid=4125&datasetversion=1.0
<http://oaimadrono.uned.es/dataverse-previewers/previewers/TextPreview.html?fileid=4259&siteUrl=http://oaimadrono.uned.es:8080&datasetid=4125&datasetversion=1.0>
Juan Corrales

**Comment by pdurbin** [comment]
@juancorr I just noticed this:

... siteUrl=https://oaimadrono.uned.es:8080&datasetid=4125& ...

https://oaimadrono.uned.es:8080 will never work because 8080 is for http (usually, in our world) but https is being used.

Can you please send me your domain.xml file?

**Comment by juancorr** [comment]
Thanks pdurbin,

  It is not a big problem for us if Dataverse does not allow to have the Dataverse in the port 8080 or without https. We can change the SystemConfig code to test.
  Dataverse url is oaimadrono.uned.es:8080 (Glassfish) and previewers url is http://oaimadrono.uned.es/dataverse-previewers/previewers/ (Apache)

[domain.xml.zip](https://github.com/IQSS/dataverse/files/3814337/domain.xml.zip)

**Comment by poikilotherm** [comment]
Looks like you messed up with `dataverse.fqdn` setting not pointing to the correct host and not setting `dataverse.siteUrl` to avoid the "https://" default usage...

**Comment by pdurbin** [comment]
@juancorr @poikilotherm here's the problem:

```
Teams-iMac:gf family$ curl -O -L https://github.com/IQSS/dataverse/files/3814337/domain.xml.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   565    0   565    0     0   1566      0 --:--:-- --:--:-- --:--:--  1565
100  5632  100  5632    0     0  10799      0 --:--:-- --:--:-- --:--:-- 10799
Teams-iMac:gf family$ unzip domain.xml.zip 
Archive:  domain.xml.zip
  inflating: domain.xml              
Teams-iMac:gf family$ grep siteUrl domain.xml
Teams-iMac:gf family$ grep fqdn domain.xml
        <jvm-options>-Ddataverse.fqdn=oaimadrono.uned.es:8080</jvm-options>
Teams-iMac:gf family$ 
```

As I discussed with @sekmiller and @djbrooke while we worked on this issue, some day I think we should get rid of "dataverse.fqdn" and only use "dataverse.siteUrl". It's very confusing. See also #4517 😄 

A quick note about ports:

- dataverse.fqdn does not support ports
- dataverse.siteUrl does support ports

@juancorr here's what I recommend:

- delete dataverse.fqdn
- add dataverse.siteUrl
- restart Glassfish

Because dataverse.siteUrl always "wins" over dataverse.fqdn (because of how the code is written) I never use dataverse.fqdn. I always delete dataverse.fqdn and only use dataverse.siteUrl.

**Comment by poikilotherm** [comment]
:+1:  for removing `dataverse.fqdn`. It's giving lots of people headaches lately :wink:

**Comment by juancorr** [comment]
Thanks for your patience @pdurbin and @poikilotherm . You are right. It was a configuration problem not a Dataverse issue.
  I had not seen previous @poikilotherm comment with the solution.

**Comment by djbrooke** [comment]
Thanks all. @juancorr I'm going to close this out, but please feel free to let us know if you feel there's something that should be better documented here.

**Comment by pdurbin** [comment]
I was the one who asked for "other areas of the code do not work if Dataverse server is under http" to be added to the issue title and here's where "https" is hard-coded for SWORD: 

https://github.com/IQSS/dataverse/blob/v4.17/src/main/java/edu/harvard/iq/dataverse/api/datadeposit/UrlManager.java#L195
