### ISSUE TITLE
Documentation: Fix/Update version on doc index page

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#6297]
Thank you for contributing an issue to the Dataverse Project! If this is a bug report, please let us know when the issue occurs, which page it occurs on, to whom it occurs, and which version of Dataverse you're using. If this is a feature request, please let us know what you'd like to see and give us some context - what kind of user is the feature intended for, the relevant use cases, and what inspired the request? No matter the issue, screenshots are always welcome.

**Comment by poikilotherm** [comment]
Isn't this a dup of #6295? :scratch:

**Comment by kcondon** [comment]
Maybe but it was a ticket I was using just to create a branch and update the file (nothing to see here ;) ). I have already edited the file directly where built but wanted to fix develop too. There are other changes that Danny and your branch can be about. Don't worry, we'll get it ! :)
