### ISSUE TITLE
View unpublished data through search API

### ISSUE THREAD

**Issue by tainguyenbui** [IQSS/dataverse#6301]
**Given** that I am searching for information in Dataverse
**When** I perform a search through the **Search native API**
**Then** I would like to have the ability to see `Published`, `Unpublished` or `both` information

**What is currently happening:**
I am only able to search for published information

**What we would love to have**
A more flexible approach for search that allows us to search for any kind of data, having `only published` by default and then having a potential flag that can be set on the request

Thanks a lot! 🚀

**Comment by djbrooke** [comment]
Thanks @tainguyenbui! I think you mean through the search API based on the nature of your integration. Feel free to edit the issue if appropriate. I'll let someone more technical get into the details about how we could approach this. Note that in the UI at least, we have some facets available for different publication statuses. 

<img width="523" alt="Screen Shot 2019-10-21 at 6 29 55 PM" src="https://user-images.githubusercontent.com/7773392/67248049-1edebf00-f431-11e9-9f80-206477bdc43d.png">

**Comment by tainguyenbui** [comment]
@djbrooke thanks! yes you are right, through the API, I just updated the issue

**Comment by djbrooke** [comment]
- A dev setting exists now that could be used here (nonPublicSearchAllowed), but we'd need to bring it up to a production level, this would be the main part of this work 
- See https://github.com/IQSS/dataverse/blob/e093c0fdf42545c56479de02f04bf10143b56922/src/main/java/edu/harvard/iq/dataverse/api/Search.java#L225 for context of how this is currently structured
- This exists in the front end now (you can see your own content, or all content if you have superuser access)

**Comment by pdurbin** [comment]
I just made pull request #6333. 

The "AccessIT" test failure at https://jenkins.dataverse.org/job/IQSS-Dataverse-Develop-PR/view/change-requests/job/PR-6333/1/ is pre-existing in the "develop" branch and being tracked at #6322.

@tainguyenbui the optional "flag" to pass in will be your API token. 😄 You are very welcome to review the doc change (and the code change, if you feel like it). Thanks for reporting this issue! I've wanted to get this improvement in for years. 😄

**Comment by tainguyenbui** [comment]
thanks a lot everyone! /cc @pdurbin
