### ISSUE TITLE
No mail sent when you ask  Dataverse support for assistance

### ISSUE THREAD

**Issue by janderksen** [IQSS/dataverse#6307]
When you try to login to dataverse and it fails, you are offered to "contact dataverse for assistance".
In the dialog you can type your email address and a message. To prove you are not a robot you have to calculate a sum, but the sum is empty (+ = )
When you type 0 the form is accepted, but no mail is send 

People start complaining they do not get an answer.

![Annotation 2019-10-23 084942](https://user-images.githubusercontent.com/25841233/67395703-b87bad00-f5a6-11e9-9173-b6232b9c5103.png)
  
This does work when you click on the support link at the top of the screen.

Version is: v. 4.17 build 1450-51739f6

**Comment by djbrooke** [comment]
Thanks @janderksen, we'll take a look.

**Comment by kcondon** [comment]
For reference, see https://github.com/IQSS/dataverse/issues/3036
