### ISSUE TITLE
Documentation: Downloading URL Mistake in "Finding and Using Data"

### ISSUE THREAD

**Issue by shlake** [IQSS/dataverse#6308]
Here's the error sentence:

In "Finding and Using Data" under "Downloading via URL"
Dataverse displays a plaintext URL for the location of the file under the Metadata tab on the **dataset** page. 

This should be on the "**file** page".

**Comment by shlake** [comment]
I've fixed this on my forked copy of "dataverse". Now how do I connect this issue with my pull request (that I haven't done, but will do once I get instructions on tying this issue with my fix).

**Comment by pdurbin** [comment]
@shlake hi! Please go to https://github.com/IQSS/dataverse/compare/develop...shlake:develop and click "Create pull request". It should look like this:

<img width="1454" alt="Screen Shot 2019-10-23 at 10 04 09 AM" src="https://user-images.githubusercontent.com/21006/67401022-85242880-f57c-11e9-997a-229107580ebb.png">

**Comment by shlake** [comment]
Wasn't sure if I had to edit the text in the comment box (I didn't).

**Comment by pdurbin** [comment]
@shlake your pull request looks perfect and I added it to https://github.com/orgs/IQSS/projects/2 at which point automation kicks in to move your pull request to the Code Review column.

If you want, you can edit your pull request description to delete all the text and replace it with "closes #6308" like this (click "Update comment" when you're done editing):

<img width="1147" alt="Screen Shot 2019-10-23 at 10 43 12 AM" src="https://user-images.githubusercontent.com/21006/67405010-295c9e00-f582-11e9-86e0-47d6e9e2883e.png">

If you do this, further automation will kick in when your pull request is merged to automatically close this issue.
