### ISSUE TITLE
run unit tests and API test suite on pull request submission

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#6311]
https://jenkins.dataverse.org/job/IQSS-Dataverse-Develop-PR/
watches
https://github.com/OdumInstitute/dataverse
and launches
`ec2-create-instance.sh -b develop -r https://github.com/IQSS/dataverse.git -t jenkins_delete_me -l target -g tests/jenkins/groupvars.yml`
when a pull request is submitted.

Test results are written here:
https://jenkins.dataverse.org/job/IQSS-Dataverse-Develop-PR/view/change-requests/job/PR-19/
and here:
https://jenkins.dataverse.org/job/IQSS-Dataverse-Develop-PR/view/change-requests/job/PR-19/1/execution/node/3/ws/target/site/surefire-report.html
and server.log is copied here:
https://jenkins.dataverse.org/job/IQSS-Dataverse-Develop-PR/view/change-requests/job/PR-19/1/execution/node/3/ws/target/server.log

To enable this on https://github.com/IQSS/dataverse I'll need, pretty please, a jenkins/ folder beneath tests/ to add a groupvars.yml copy which will force unittests and apitestsuite to true, and an EC2-specific Jenkinsfile describing the pipeline.

Pull request forthcoming.

**Comment by djbrooke** [comment]
@donsizemore thank you so much for this, it'll be great to enable this for Dataverse!

**Comment by donsizemore** [comment]
@djbrooke @pdurbin well, I realized that Jenkins' GitHub Branch Source Plugin offers an environment variable for the source branch but not a forked source repo. We build the warfile in Jenkins and run unit tests locally, but switch to EC2 and dataverse-ansible to run API tests because #6149 

So at present, pull requests submitted from within IQSS will flow through completely, but pull requests from outside your organization won't run the API test suite. We can either fix #6149 or I can move the entire Jenkins job into EC2 and copy the unit test output back to the Jenkins host to display locally. Probably the latter.

**Comment by poikilotherm** [comment]
https://github.com/jenkinsci/branch-api-plugin/blob/branch-api-2.5.4/src/main/java/jenkins/branch/BranchNameContributor.java might be helpfull regarding the env vars available.

**Comment by donsizemore** [comment]
@poikilotherm yup, I tried CHANGE_FORK first which came back blank (and doesn't appear in the env).

**Comment by poikilotherm** [comment]
@donsizemore good to know! This might be a problem down the road for dataverse-kubernetes, too. Do we need to activate sth. in the job to get this?
