### ISSUE TITLE
API: Blocked-key does not seem to work.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#6313]
According to our guides, one can block api endpoints, then allow remote access by using a key identified by the setting :BlockedApiKey and accessed by passing its value by adding an argument, unblock-key=theKeyYouChose . When troubleshooting a recent user issue, this appeared not to work when using the default localhost/admin/test policy along with the example key setting provided in the guide:

http://guides.dataverse.org/en/4.17/installation/config.html#blockedapikey

**Comment by poikilotherm** [comment]
I can ensure that it works perfectly at least up to release 4.16 and it has been working at least two weeks ago in `develop`.

I use this all the time in IQSS/dataverse-kubernetes, as all calls to those API endpoints do not come from "localhost" due to the nature of K8s.

If you want me to check on latest `develop`, I'm happy to do so in a quick shot tomorrow.

**Comment by djbrooke** [comment]
Thanks @poikilotherm for taking a closer look here!

**Comment by poikilotherm** [comment]
Ok I just ran a quick test with `develop`@ deb180bc using my local `kind` cluster.

It has been no problem to deploy, bootstrap or retrieve Admin API endpoints after bootstrapping finished.

After port-forwarding with `kubectl port-forward service/dataverse 8080:8080`, I used 
```
curl "http://localhost:8080/api/admin/authenticationProviders?unblock-key=supersecret"
```
to retrieve data.

It should be noted that I do set the key from a `Secret`, but also set some other things at 

https://github.com/IQSS/dataverse-kubernetes/blob/6f83afbeeb249542e87b9d04ae504d2ff319abfe/docker/dataverse-k8s/bin/bootstrap-job.sh#L60-L62

**Comment by pdurbin** [comment]
@poikilotherm thanks for doing all this testing. Did you happen to review the docs for this feature? If so, did you see any improvements you can make to the guides? Please feel free to create a pull request if you are so moved! 😄

**Comment by kcondon** [comment]
@poikilotherm I noticed your command uses localhost. That of course works because it is within the default access policy. What happens when your replace localhost with an external dns name and access it from an external machine?

**Comment by poikilotherm** [comment]
@kcondon: please be aware that although I use "localhost" in my commands, for the application I am not coming from 127.0.0.1! The flow in K8s is like follows:

```
Command on Host -> Access Reverse Proxy at localhost:8080 -> Tunnel to K8s service at service IP -> Tunnel to Application server port 8080
```

So the default access policy is __NOT__ matching and never will, as in K8s I will _always_ be like an external guy. You can quickly test that by removing the parameter :wink:

**Comment by kcondon** [comment]
@poikilotherm Got it, thanks. Glad I asked! :)
