### ISSUE TITLE
Building docs for PRs and maybe guides.dataverse.org

### ISSUE THREAD

**Issue by poikilotherm** [IQSS/dataverse#6315]
### Context
- Since I've opened #6188, I learned about a few interesting things about Sphinx, see also IQSS/dataverse#92. 
- In [PR 6192](https://github.com/IQSS/dataverse/pull/6192#discussion_r338484556) there has been a hint by @pdurbin about building the guides for PRs in EC2.
- I talked about this proposal with @pdurbin [today on IRC](http://irclog.iq.harvard.edu/dataverse/2019-10-24#i_110520)

### Proposal
- Copycat [K8s documentation job](https://jenkins.dataverse.org/job/dataverse-k8s/job/documentation) for Dataverse
- Copycat `Jenkinsfile` and `Dockerfile` for Sphinx builds from IQSS/dataverse-kubernetes for Dataverse
- Adapt both to run on PRs, tags etc.
- Adapt Jenkins pipeline deployment steps to reflect the following pattern in a repository, branch or other webserver: `https://<guides URL>/<branchname/tag/latest>/...`.
  This is planned for IQSS/dataverse-kubernetes anyway.

### Computing Resources
This proposal re-uses existing community Jenkins server. That server should be more than enough to build the docs. No AWS machinery necessary.

The builded docs need to live somewhere. Be it on a separate GitHub repository (e. g. "IQSS/dataverse-docs"), a `gh-pages` branch of IQSS/dataverse or some other webspace. GitHub pages seems like a natural place. Using a separate repository enables write access for @dataversebot without headaches for IQSS/dataverse.

### Time resources
Reusing existing scripts, etc. Low amount of time once done for IQSS/dataverse-kubernetes.
Needs some decisions and maybe admin time to create repositories, etc.

**Comment by poikilotherm** [comment]
While looking more into this, I came across #2148.

**Comment by pdurbin** [comment]
Closing. Implemented in this PR by @poikilotherm 

- #8651

Thanks, @poikilotherm !
