### ISSUE TITLE
Compile/run issue with Java 12 and 1.8

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#6318]
FWIW: I just tried compiling Dataverse with a Java 12.02 version and while it initially looked OK, when I uploaded a file I got    
```
java.lang.NoSuchMethodError: java.nio.MappedByteBuffer.rewind()Ljava/nio/MappedByteBuffer;
        at edu.harvard.iq.dataverse.ingest.IngestableDataChecker.detectTabularDataFormat(IngestableDataChecker.java:627)
```
and related errors. This appears to be related to https://github.com/eclipse/jetty.project/issues/3244 . I tried a quick test to use the maven release attribute as discussed there but it didn't work. Possibly a newer version of the compiler plugin is needed. 

In any case, it looks like compiling with 12.02 and the current pom.xml doesn't produce a war that can be run on a Java 1.8x machine.

**Comment by pdurbin** [comment]
@qqmyers yuck. Thanks for the bug report. Please see also pull request #5116 and issue #4259.

**Comment by qqmyers** [comment]
@pdurbin - thanks - I've seen those issues, didn't realize it was also a compile issue versus running glassfish4 and everything on it. Hopefully this #6320 PR will at least remove the compile problem.
