### ISSUE TITLE
Securing API tokens preemptively

### ISSUE THREAD

**Issue by poikilotherm** [IQSS/dataverse#6319]
While hacking on #6286 in sparetime, I came across https://neilmadden.blog/2018/08/30/moving-away-from-uuids/

Should one think about refactoring

https://github.com/IQSS/dataverse/blob/79bfe159b091024b591c8bc2863d454d85d5a077/src/main/java/edu/harvard/iq/dataverse/authorization/AuthenticationServiceBean.java#L450-L456

dating back to 2015? The article is from 2018 and explicitly says we are NOT AT RISK (which makes perfect sense), but it might be worth talking about this.

It would be easy to change and no current installations harmed, as non-expired API tokens saved in database continue to be valid.

**Comment by pdurbin** [comment]
Closing in favor of this issue with more discussion:

- #7070
