### ISSUE TITLE
Fix API Test Suite

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#6322]
Our handy indicator at the bottom of the readme indicates that we have some test failures. We should fix them before releasing 4.18. More info here:

https://jenkins.dataverse.org/job/IQSS-dataverse-develop/lastCompletedBuild/testReport/

**Comment by pdurbin** [comment]
My pull request is in at #6324 and I'm taking myself off this unless there is more swarming to do.

**Comment by pdurbin** [comment]
Three new-ish API test classes were missing from phoenix so I just added them:

- EditDDIIT
- ExternalToolsIT
- AccessIT
