### ISSUE TITLE
Create project for datasuds.ird.fr

### ISSUE THREAD

**Issue by tcoupin** [IQSS/dataverse#6328]
Can you create a project for our installation ?

**Comment by tcoupin** [comment]
ping @pdurbin

**Comment by pdurbin** [comment]
@tcoupin hi! I just invited you to join https://github.com/orgs/IQSS/teams/dataverse-readonly/members

![Screenshot from 2019-10-31 07-28-49](https://user-images.githubusercontent.com/21006/67943300-24b26e00-fbb0-11e9-9523-81e868dd2c85.png)

After you accept the invitation you should be able to create the project yourself. If not, please let me know! Thanks.

I also opened https://github.com/IQSS/dataverse-installations/issues/22 to update the map
