### ISSUE TITLE
Inconsistent term for .tab format

### ISSUE THREAD

**Issue by TaniaSchlatter** [IQSS/dataverse#6330]
On the dataset page, we refer to tabular files as "Archival format (.tab)" in the dataset level dropdown, and "Tab-Delimited" in the file dropdown. Are these the same format? If so, we should pick and use one term for both.

<img width="1303" alt="Screen Shot 2019-10-31 at 12 49 13 PM" src="https://user-images.githubusercontent.com/15386424/67968108-2b0b0f00-fbdd-11e9-962f-9bba5e14f603.png">
<img width="1290" alt="Screen Shot 2019-10-31 at 12 49 06 PM" src="https://user-images.githubusercontent.com/15386424/67968109-2b0b0f00-fbdd-11e9-9376-25d914482244.png">

**Comment by pdurbin** [comment]
I agree with the comment by @adam3smith at https://github.com/IQSS/dataverse/issues/2720#issuecomment-371196587 and think we should switch from `.tab` to `.tsv`. It's much more standard.

**Comment by jggautier** [comment]
If the archival format was changed from .tab to .tsv, the second options in the pulldown menus in both screenshots would be the same, right?

**Comment by adam3smith** [comment]
It already gives you the same format (.tab) right now. Switching this to `.tsv` would indeed be the right thing to do (and just to be clear, that's just a different extension for literally the same file), but wouldn't by itself address the issue @TaniaSchlatter raises here.

So to explain the slightly different naming/dialog: 
- The first one is for multiple files/potentially a whole dataset, which can have different file formats in it (e.g. .xlsx, .dta, etc.) and gives the user the possibility to download the whole dataset as is or with normalized `.tab` tabular files. Most people will probably want the original format here, e.g. as part of a reproducibility package. 
- The second one is for an individual file and allows the user additional download options such as the DDI and .RData format. For an individual file, a user may well want the .tab/.tsv -- it's easy to read into statistical software.

What you don't want to lose in making these labels more consistent is that they currently convey to the user that for the whole dataset they'll typically want the "Original format" but for the individual file, tab delimited is an option that's not merely "archival". Not sure if this is helpful. I tried to think of a single, unified label, but couldn't come up with anything I liked.

**Comment by TaniaSchlatter** [comment]
Also noting the inconsistency in wording between "Original Format" and "Original File Format (Stata 14 Binary)"

**Comment by pdurbin** [comment]
https://twitter.com/Ray_J__/status/1202296388618457089 illustrates why Dataverse should use .tsv instead of .tab for tab-separated files. Here's a screenshot:

<img width="952" alt="Screen Shot 2019-12-04 at 10 34 40 PM" src="https://user-images.githubusercontent.com/21006/70202064-75087880-16e6-11ea-9a6c-5b3564c21e81.png">

**Comment by TaniaSchlatter** [comment]
Recent prototype testing makes it clear that we need to specify the file format type, regardless of what it is, when we say "Archival Format", i.e. "Archival Format (.tab)"

**Comment by pdurbin** [comment]
I just thought I'd mention that this issue is on my mind as I chew on the following bullet from #6118

- New options for “Download”, or “Download Original Files” and “Download Archival Format” under the Access Dataset btn

**Comment by pdurbin** [comment]
Related:

- #2720
- #4274

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
