### ISSUE TITLE
As a community member, I would like to know how I should scope and size my pull requests

### ISSUE THREAD

**Issue by poikilotherm** [IQSS/dataverse#6331]
@pdurbin and I have been talking in a quick video chat this morning about my ideas for moving on with issue #5974.

Apart from the technical details, we talked about what I should include in a first version of a pull request, to keep things moving fast (poor reviewers) and positively influence the "merge rate": increase chances that things are merged upstream quickly.

Scope of this issue: this is about non-trivial changes, like refactorings or bigger features coming in.

As Dataverse has a growing number of contributers, it would be superb to have some written docs how people at IQSS would like PRs in scope and size, but also what things might be good to postpone or leave for a later iteration during Code Review. Maybe also guidance on whom to mention/include to drive attention of the right people to the PR.

**Comment by djbrooke** [comment]
@poikilotherm thanks for creating this. In terms of scope and sizing, generally, "as small diff as possible to provide independent value" is the guideline, both for making things easier to review and for getting things out in a release more quickly. I'll catch up with @pdurbin for some more details about your talk, but it would also be helpful if there are any projects that you can point to that you feel do this well. Thanks again!
