### ISSUE TITLE
Subjects disappear when clicked in metadata editing

### ISSUE THREAD

**Issue by kaitlinnewson** [IQSS/dataverse#6339]
Tested in version 4.17 in both Harvard and Scholars Portal Dataverse instances. Tested in Chrome (78.0.3904.70) and Firefox (70.0) on MacOS Mojave.

When creating a dataset and entering metadata in Google Chrome, clicking on the name/label of the subject makes the subject box disappear. The issue does not happen if you only click the checkbox.

The problem starts at the "Earth and Environmental Science" subject, which causes the box to partially collapse. Clicking subjects below "Earth and Environmental Science" will cause the block to disappear completely.

Clicking on the text label for "Earth and...":
 
<img width="906" alt="Screen Shot 2019-11-03 at 10 38 25 AM" src="https://user-images.githubusercontent.com/6903515/68087674-18cfe180-fe26-11e9-82c7-0cfc151f9aa8.png">

Clicking on any text label below "Earth and...":

<img width="902" alt="Screen Shot 2019-11-03 at 10 34 27 AM" src="https://user-images.githubusercontent.com/6903515/68087627-b8d93b00-fe25-11e9-8184-976accce49fe.png">

The bug does not occur in Firefox; other browsers were not tested. Screenshots above were created from the Harvard instance.

**Comment by jggautier** [comment]
Can confirm. The same thing happens with the Language field, when clicking on the words (not the checkboxes) of any of the listed options after the sixth option, starting with Arabic. "Earth and Environmental Science" is the seventh option in the Subjects field. Maybe happens for any other check box fields with seven or more options.

**Comment by djbrooke** [comment]
Thanks @kaitlinnewson and @jggautier. We'll bring it into a sprint very soon, hopefully this week.

**Comment by mheppler** [comment]
Saw this was reviewed, approved and moved to QA. There wasn't a review of the UI, so I jumped in and took a look. Here is a quick mockup of a proposed solution to use the same `p:selectCheckboxMenu` component that is used in editFilesFragment for the Edit Tags popup.

Can review with @TaniaSchlatter once we get a prototype to demo.

![Screen Shot 2019-11-18 at 11 10 53 AM](https://user-images.githubusercontent.com/687227/69069800-1c9e5f00-09f5-11ea-97c0-ca2eef1b2ed6.png)

**Comment by sekmiller** [comment]
The reason that the original fix wasn't sent to the design team for review was because it didn't change the UI. The original change was to swap out the generic div scroll container to a primefaces scroll panel. This worked in most cases, except in Chrome where you used the scroller before clicking the item label.

**Comment by sekmiller** [comment]
Changed to a select checkbox menu which solves the issue in Chrome(and works as expected in general). If @mheppler and @TaniaSchlatter want to take a look and see if it needs additional styling, please be my guest.
