### ISSUE TITLE
Clarify permissions and roles in User Guide

### ISSUE THREAD

**Issue by Falco-KUB** [IQSS/dataverse#6342]
After discussion in https://groups.google.com/forum/#!topic/dataverse-community/XjodQ6bQjFg, a clarification of http://guides.dataverse.org/en/latest/user/dataverse-management.html#roles-permissions would be helpful, in particular:

Setting Access Configurations for a dataverse:
"Edit Access"
> "Who can add to this dataverse?" > "Anyone with a Dataverse account can add sub dataverses (and datasets)"
in combination with
> "What should be the default role for someone adding datasets to this dataverse?" > "Contributor"

would allow user to publish direclty from a sub dataverse that they created themselves (and thereby bypassing the restrictions set by the contributor role).

Similar, a comment should be added under "Assigning Roles to Users and Groups" about the "ManageDatasetPermissions" option, that would allow users to change their own role (and thus override any restrictions set at a higher level).

**Comment by pdurbin** [comment]
@Falco-KUB thanks for opening this issue! My first thought is that we could write more in a future version of http://guides.dataverse.org/en/4.17/installation/config.html#root-dataverse-permissions

In the screenshot below, I've highlighted in blue the most pertinent text.

![Screen Shot 2019-11-05 at 9 09 56 AM](https://user-images.githubusercontent.com/21006/68214831-2ca55000-ffac-11e9-8358-049590b8d7b7.png)

Again, this is just a first thought. Would a whole page in the Admin Guide be better? Should there be more information in the User Guide? (You've already identified the "Roles & Permissions" section of the "Dataverse Management" page.)

For anyone who wants to contribute documentation, we have some tips at http://guides.dataverse.org/en/4.17/developers/documentation.html and I'm happy to coach anyone through the process! 😄

**Comment by Falco-KUB** [comment]
I wouldn't put it in the Installation Guide.

I don't know, whether the admin guide or the user guide would be the best place to describe the roles and permissions. But as it is now, I think I'd prefer to update/extend the information in the user guide.

**Comment by pdurbin** [comment]
@Falco-KUB sounds good. Are you interested in making a pull request? 😄 I'm happy to help you get Sphinx installed and coach you through the process of updating the User Guide.

**Comment by pdurbin** [comment]
@Falco-KUB time flies! Are you still interested in this? Thanks!

**Comment by Falco-KUB** [comment]
thanks for the reminder, I'd have to look at the documentation in more detail again at some point.
I think it would fit best under Dataverse Collection Management - Roles & Permissions in the user guide.

**Comment by pdurbin** [comment]
@Falco-KUB thanks for the brain dump at https://groups.google.com/g/dataverse-community/c/4VM49qUqMGo/m/a8GfIuDpJAAJ 😄

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
