### ISSUE TITLE
Geographic coverage: add punctuation to improve display

### ISSUE THREAD

**Issue by johnhuck** [IQSS/dataverse#6345]
The Portage Dataverse North Metadata Working Group would like to recommend that the display of the Geographic Coverage statement be improved by adding punctuation (or some kind of visual marker) between, or perhaps even labels for the coverage statement's components (i.e., Country/Nation, State/Province, City, and Other). This would only be for display, of course.

Commas would be simplest option, and are what most people expect to see, I think, but there may be other UX friendly choices that would work too.

In the absence of punctuation, one long string can sometimes be difficult to interpret, especially when one of the components consists of two or more words. Furthermore, values in the "Other" field may consist of a phrase that includes a place name (a made up example: "Vancouver district field station"), making the meaning of the string ambiguous.

I believe this issue applies to all released versions. I couldn't find this issue in the Community group or an issue for it here. Hope I didn't miss anything!

Here is a simple example. I can find others, if necessary. Thanks!

<img width="660" alt="Screen Shot 2019-11-05 at 3 28 35 PM" src="https://user-images.githubusercontent.com/5233196/68252937-f5eb2c00-ffe3-11e9-9bc1-f6a45c7efb37.png">

**Comment by djbrooke** [comment]
Hey @johnhuck, thanks for opening this. Can you link me to the example here?

**Comment by johnhuck** [comment]
Yes, you bet.

https://dataverse.scholarsportal.info/dataset.xhtml?persistentId=doi:10.5683/SP2/4RNOVS

**Comment by pdurbin** [comment]
@johnhuck thanks. It looks like the metadata is entered perfectly with "country", "state" and "city" entered into discrete fields:

<img width="918" alt="Screen Shot 2019-11-06 at 3 30 37 PM" src="https://user-images.githubusercontent.com/21006/68335485-89873000-00aa-11ea-85c3-f6ab3c96ff41.png">

So I think what you're asking for (commas or some other normal separator) makes complete sense. It should look something like this:

<img width="1179" alt="Screen Shot 2019-11-06 at 3 34 05 PM" src="https://user-images.githubusercontent.com/21006/68335680-ee428a80-00aa-11ea-8f61-38219acbffa5.png">

Thanks!

**Comment by johnhuck** [comment]
@pdurbin Phil, yes inserting commas into the display (but not the metadata) would be the most straight-forward way to address this.

You could make an argument that, perhaps the components should actually be labeled, but that's not something I'm advocating for at this time. If people are savvy enough to check the JSON export, they can check whether a place name is a "city" or an "other", for instance, if that were important for some task at hand.

**Comment by TaniaSchlatter** [comment]
![Screen Shot 2020-01-06 at 12 15 18 PM](https://user-images.githubusercontent.com/15386424/71834908-5519fb00-307e-11ea-9131-247dd657e37c.png)

We did a little further investigation of the UI behavior, and agree that adding commas are the best approach.

In the example above, an additional item was added with the "+" 

![Screen Shot 2020-01-06 at 12 18 26 PM](https://user-images.githubusercontent.com/15386424/71835049-a9bd7600-307e-11ea-973c-389531375443.png)

**Comment by kamil386** [comment]
I think that resolution works quite good for smaller schemas, but I think it don't work well for bigger schemas like DwC, that i.e has 34 subfields in Taxon group

Edit metadata page:
![image](https://user-images.githubusercontent.com/56053188/73450586-fb97aa00-4365-11ea-99b8-c8f66dd1daec.png)

Show metadata page:
![image](https://user-images.githubusercontent.com/56053188/73450663-27b32b00-4366-11ea-84ca-7e05caf3037b.png)

**Comment by BPeuch** [comment]
I second @johnhuck's point, and I wanted to add that explicitly distinguishing the fields in the final metadata display (```County / Nation```, ```State / Province```, ```City``` and ```Other```) might be a good idea. For example, if a researcher has collected data in various cities in the province of Namur, Belgium, namely Dinant, Rochefort and, also, the city of… Namur, then you get the following result:

![image](https://user-images.githubusercontent.com/15209224/80076780-f30dd480-854c-11ea-8867-d46cbf35665c.png)

And I think that repeating the field for every city is not only a lot of extra clicks but also not entirely satisfying because we still end up with "Namur Namur" (as well as the repetition of the ```Country / Nation``` field)…

![image](https://user-images.githubusercontent.com/15209224/80077291-965ee980-854d-11ea-96bf-83cf489db16e.png)

… and we also have the ambiguity of not knowing, if a researcher only entered "Namur", whether they're referring to the province or the city.

**Comment by pdurbin** [comment]
@kamil386 and @BPeuch these screenshots and use cases are great but once we close an issue (this one was closed with pull request #6483 as part of Dataverse 4.19) we don't tend to re-open it and work more on it. Instead, we look to new open issues for feedback on where to go next. All this is to say, if you could each create a new issue (or coordinate and create a single issue), it would be appreciated!

**Comment by BPeuch** [comment]
Sorry about that, @pdurbin. Here's the new issue for our problem: https://github.com/IQSS/dataverse/issues/6855
