### ISSUE TITLE
OAuth2 broken in recent develop (needs verification & more investigation)

### ISSUE THREAD

**Issue by poikilotherm** [IQSS/dataverse#6357]
While hacking on #5991 I started to add unit tests and refactoring. Noticing that Github login didn't work anymore.

Switching to `develop@` 41acae14, I was able to reproduce: login via Github redirects to `/`, because of `OAuth2LoginBackingBean.newAccountPage.newUser` is `null`, not set to user after redirect.

Setting the object, note the instance id: `OAuth2FirstLoginPage@20400`
![grafik](https://user-images.githubusercontent.com/5468333/68621420-fd24a500-04cf-11ea-997d-bccd540bf293.png)

You can already see in the calling bean (`OAuth2LoginBackingBean`), that there is a different instance id present and the `newUser` attribute is null.
![grafik](https://user-images.githubusercontent.com/5468333/68621518-3f4de680-04d0-11ea-84c8-6e12e0b9342b.png)

Finally, after being redirected to the first login page by JSF, the `newUser` attribute is still `null` in `OAuth2FirstLoginPage.init()`:
![grafik](https://user-images.githubusercontent.com/5468333/68621630-889e3600-04d0-11ea-88aa-e43bc249190b.png)

Can somebody please test to reproduce this regression on your machines and with other provider s, too? (although this doesn't look provider related, as it happens in the beans/controllers/views)
I have no idea yet why this happens, but it would be a major drawback.

**Comment by poikilotherm** [comment]
@djbrooke if this a reproducable regression, will this affect the release of 4.18?

**Comment by djbrooke** [comment]
@poikilotherm yes. There's a lot of detail here but it would be good to know the actual experience that someone gets when trying to login with Github.

**Comment by poikilotherm** [comment]
Ok this seems like related to session management between client (Firefox) and server.
I read some more details about `@SessionScoped` for the `OAuth2FirstLoginPage` CDI injection and tried to reproduce in a private tab / new browser.

Everything is working fine now - looks like the sessions have been mixed up, could not be reseted or whatever. Using a clean browser session this is back to working normally.

Closing this for now.
