### ISSUE TITLE
Edit Dataverse: Removing a metadata block removes the block and its data from existing, published studies.

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#636]
---

Author Name: **Kevin Condon** (@kcondon)
Original Redmine Issue: 4075, https://redmine.hmdc.harvard.edu/issues/4075
Original Date: 2014-06-04
Original Assignee: Gustavo Durand

---

Found on 6/4
Edit Dataverse: Removing a metadata block removes the block and its data from existing, published studies.

Not sure what the desired behavior should be but I think it should warn the user that data will be removed and possibly provide a list of affected studies.

**Comment by sekmiller** [comment]
Fixed and checked in.

**Comment by sbarbosadataverse** [comment]
Not clear if this is "removing a metadata block from a DATAVERSE/SUBDATAVERSE, removes the block form an existing published study?"

**Comment by sbarbosadataverse** [comment]
created a subdataverse with required life science metadata block. 
created a dataset and completed the block. published dataset.
removed the metadata block from subdataverse.
checked dataset and metadata block fields and values still there!

looks good.

**Comment by sbarbosadataverse** [comment]
Tested again:
metadata block selected in parent dataverse
dataset created. published successfully.
removed metadata block from parent.
dataset still contains the metadata block fields and values.
