### ISSUE TITLE
As a curator, I want to easily update the metadata of multiple datasets with the same values

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#6362]
For example, a Harvard Dataverse user recently needed to change the dataset contact email addresses in most of the ~50 datasets in the dataverse she administers. These datasets have an old email address that won't be monitored much longer, and she wants to make sure that people can continue to contact the dataset owners.

The only way to change these metadata values in the UI is to visit each dataset's edit metadata page, and if that dataset has the old email address, type in the new one. She doesn't have the resources for this doing this or for using the APIs to find these datasets, which can be hard to use, especially when trying to find values in metadata fields like contact email, which aren't indexed/ findable with the Search API.

To find datasets that have metadata that the Search API doesn't expose, like contact emails, I suppose you could download and query all of the dataset metadata in a given dataverse, but this can be tough, or impossible if the installation prevents contact emails from appearing in the metadata exports.

Instead I queried the database to find the dataset DOIs that have the old contact emails, then used a script that used the "replace metadata" and "publish draft dataset" endpoints.

**Comment by jggautier** [comment]
One solution might be to enable batch metadata editing and draft publishing in the UI. Figshare is one repository that allows this.

Another solution might address the more narrow needs of the user in the example. Since she wants the contact email of every dataset in the dataverse to be the same, maybe there could be a setting that lets curators set the contact email of every dataset to the dataverse's contact email. But I'm not sure how often curators/dataverse admins want this.

**Comment by pdurbin** [comment]
Related:

- #7614

**Comment by jggautier** [comment]
I'm closing this issue since there's another at https://github.com/IQSS/dataverse/issues/6362
