### ISSUE TITLE
Tests failing on jenkins.dataverse.org/job/IQSS-dataverse-develop

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#6366]
We had two failures late yesterday on the IQSS-dataverse-develop job on https://jenkins.dataverse.org

I just ran the tests on phoenix (first time in 12 days) and they passed: https://build.hmdc.harvard.edu:8443/job/phoenix.dataverse.org-apitest-develop/443/

## job 249

https://jenkins.dataverse.org/job/IQSS-dataverse-develop/249/consoleFull has this failure:

fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'jdbcurl'\n\nThe error appears to have been in '/home/centos/dataverse/tasks/dataverse-install.yml': line 27, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: set jdbcurl\n  ^ here\n"}

I'm hoping the fix is to add the following line to tests/jenkins/groupvars.yml which is probably required due to me merging https://github.com/IQSS/dataverse-ansible/pull/130 (without testing it, sorry):

    jdbcurl: https://jdbc.postgresql.org/download/postgresql-42.2.8.jar

## job 250

https://jenkins.dataverse.org/job/IQSS-dataverse-develop/250/consoleFull has a different failure:

TASK [dataverse : build warfile with specified tests. tail /tmp/dataverse/mvn.out for gory details.] ***
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "mvn -DcompilerArgument=-Xlint:unchecked test -P all-unit-tests -T 2C package > mvn.out", "delta": "0:01:06.085942", "end": "2019-11-12 22:19:24.735007", "msg": "non-zero return code", "rc": 1, "start": "2019-11-12 22:18:18.649065"

I'm not sure what the fix is for job 250.

**Comment by donsizemore** [comment]
This was my stupidity and may be safely closed.

**Comment by pdurbin** [comment]
@donsizemore no, no, my fault for merging https://github.com/IQSS/dataverse-ansible/pull/130 without testing or thinking it through. I summarized our conversation to @kcondon yesterday. I see you're working away on a branch so we can talk more there. Closing. Thanks again!
