### ISSUE TITLE
automatic logout

### ISSUE THREAD

**Issue by benzaked** [IQSS/dataverse#6384]
dataverse version : 4.15

the system forwards to the new page unlogin after clicking on some button. for example: 
login > add data.throw the user to the login page.   
or after login and entering to some datasets. need to log in again.
Does anyone know why? 
Thanks!

**Comment by pdurbin** [comment]
@benzaked hi, how frequently does this happen and for how many users?

Have you patched Weld as explained at http://guides.dataverse.org/en/4.15/installation/prerequisites.html#installing-glassfish ?

**Comment by benzaked** [comment]
@pdurbin it's happening to every user. (including admin) . 
I installed dataverse from docker. so I did not do any of this.
should I open an issue [there](https://github.com/IQSS/dataverse-docker)?

**Comment by pdurbin** [comment]
@benzaked sure, but please link back to this one we we can easily find it. Thanks!

**Comment by djbrooke** [comment]
@benzaked - I'm going to close this for now, but please add a new issue if this ends up not being a Docker issue.
