### ISSUE TITLE
Dataverse - Broken Filter Results button to toggle facets side panel

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#6403]
When the Dataverse search results is viewed on narrow screens (e.g. narrow desktop browser windows and phones), the metadata facets are replaced by a Filter Results button.

<img width="672" alt="Screen Shot 2019-11-23 at 5 08 19 PM" src="https://user-images.githubusercontent.com/18374574/69485951-1b659b80-0e14-11ea-8436-fae7708ea2e8.png">

Clicking on/tapping that button should show the facets. But since Dataverse 4.18, clicking on that button doesn't do anything. I'm seeing this on the latest versions of Chome, Firefox and Safari.

**Comment by pdurbin** [comment]
@jggautier good catch. It's broken on Android too.

**Comment by mheppler** [comment]
This appears to have been broken in the PR to address memory leaks in #6035. Will need to review with @landreev this reasons for commenting out the necessary jQuery function for this toggle button. It appears to have been an oversight. In which case, it may make sense to move this function to the dv_rebind_bootstrap_ui.js file, and delete all this inline javascript from the search-include-fragment.xhtml, as it is already commented out.

```
    <script>
        <ui:remove>
        // The javascript below would be called once the page finished 
        // the initial rendering, and trigger an extra partial submit that 
        // displayed the extra cosmetic features of the page - the thumbnails
        // primarily - thus making the initial load happen faster. 
        // We have decided to disable this feature (at least for now) in order 
        // to be able to change SearchIncludeFragment and ThumbnailServiceWrapper 
        // to @RequestScoped (to eliminate the objects in memory associated with the 
        // @View scope).
        // For postLoad() see: https://github.com/IQSS/dataverse/issues/2004
        //<![CDATA[
        //$(document).ready(function () {
            // Calls the p:remoteCommand postLoad.
            // Posted at end of fragment to work correctly with Account information
        //    postLoad();

        //    $('[data-toggle=offcanvas]').click(function() {
        //        $('.row-offcanvas').toggleClass('active', 200);
        //    });
        //});
        //]]>
        </ui:remove>
    </script>
```

**Comment by mheppler** [comment]
Moved commented out jQuery on search-include-fragment.xhtml for Filter Results btn to dv_rebind_bootstrap_ui.js, and deleted all the other commented out javascript.

Also, fixed a CSS issue that broke Contact and Share btn tooltips, as well as Link and Edit btns dropdown menus on dataverse pg when viewed in an extra small (<768px) browser window.
