### ISSUE TITLE
POI updates needed with Tika 1.22

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#6409]
Since Tika was updated to 1.22, I see java.lang.IncompatibleClassChangeError in POI when full-text indexing some Microsoft files. I've tracked the issue down to a change in POI between 4.0 and 4.1/4.1.1 and an outdated dependency on poi-scratchpad.  Updating poi to 4.1.1 and including an explicit dependency on poi-scratchpad 4.1.1 fixes the issue. I also see that we have poi-examples as a dependency which is not needed. 
I'll add a PR. For testing, I can probably provide a file where the problem occurs (not sure if I have a public one or only ones still being curated).

**Comment by kcondon** [comment]
@qqmyers OK, testing now. Do you have that file or should I just try a Word doc or something like that?

**Comment by qqmyers** [comment]
@kcondon - sorry for being slow - thanks for going ahead.

**Comment by kcondon** [comment]
@qqmyers No worries, thanks.
