### ISSUE TITLE
Dataset API returns unparsable MDC log entries

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#6411]
At TDL and QDR, I see entries in the MDC log that cause an error in counter. Digging in, I think the root cause is that the Datasets API calls that use getDatasetVersionOrDie() all create an MDC entry, regardless of whether the version in question is published or draft. When it's draft, the MDC entry has no identifier which then breaks counter. 

If I understand correctly, the correct behavior is to not log events for requests on draft datasets. If that's true, I can submit a PR that will appropriately create entries only for published datasets. So far, I think this only affects ~ 4 API calls to get various version info (metadata, files, etc.) but I'll scan to see if there are others.

For the logs themselves, I think the there may be few enough entries to just delete the bad ones (which are for draft data and shouldn't be counted anyway). If that's not true, I think a script that deletes likes with a null identifier would fix things.

**Comment by qqmyers** [comment]
Correction - I think requests for draft version info for datasets that do have a released version are getting logged (they parse OK but I don't think they should be counted) while calls to get dataset versions where the dataset has no released version are giving the unparsable entries.

The code is still easy to fix but it looks like scanning the logs should include dropping lines where the version is :draft and there is an identifier (really any where the dataset with that identifier doesn't have a released version, but I don't know that there will be any for deaccessioned ones at this point).

**Comment by pdurbin** [comment]
@qqmyers yes, we'd love a pull request. As you're saying, views and downloads of unpublished versions of datasets should not count toward Make Data Count. Thanks!!

**Comment by kcondon** [comment]
@qqmyers @pdurbin Guys, I am unable to reproduce the logging for draft downloads in the develop branch, either by ui or api. That is consistent with my expectation but not what you reported here. What am I missing?

**Comment by pdurbin** [comment]
@kcondon oh, sorry. You have to test via API:

http://guides.dataverse.org/en/4.18.1/api/native-api.html#get-json-representation-of-a-dataset

**Comment by kcondon** [comment]
@pdurbin I am testing via the api, trying file downloads, etc. Are you saying it is limited to downloading draft versions of dataset metadata?

**Comment by qqmyers** [comment]
Here's one call that was failing:  curl -k  https://<your server>/api/v1/datasets/<id>/versions/:draft?key=<your key>

The problem was with a dataset that is only draft/never published. Before the fix, you should see an MDC log line with no identifier. After the fix, you wouldn't see this line at all.

If the data has been published, you'll see a line that is parsable/does have an id, but it shouldn't be getting logged since you're asking about the :draft version.

**Comment by kcondon** [comment]
@qqmyers I've tried that api endpoint on an unpublished draft but it was not recognizing it by pid. Let me try with db id

**Comment by qqmyers** [comment]
Yeah - I did have to use db id

**Comment by kcondon** [comment]
@qqmyers OK, got it to work/fail. Was user error but helpful to know which api call to use. Will check your branch now and merge
