### ISSUE TITLE
"Production date" hard coded in JSON metadata export

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#6426]
In recent versions of Dataverse, including the latest 4.18.1, the"JSON" metadata export of every dataset includes `productionDate: "Production Date"`.

<kbd><img width="680" alt="Screen Shot 2019-12-02 at 1 32 54 PM" src="https://user-images.githubusercontent.com/18374574/69984991-5f3d5c80-1508-11ea-974e-aea93454ce73.png"></kbd>

It seems to be hard coded, appears only in the "JSON" export, and doesn't seem to affect how the "Production Date" metadata (that depositors fill out) is recorded (see `typeName: productionDate` at the bottom of the screenshot).

But it could confuse people who are trying to make sense of the metadata in the JSON export and I think should be removed. Then I think each installation will need to re-publish each published dataset's JSON metadata export.

**Comment by pdurbin** [comment]
@jggautier good catch.

Here's where it seems to be hard coded:

https://github.com/IQSS/dataverse/blob/v4.18.1/src/main/java/edu/harvard/iq/dataverse/DatasetVersion.java#L679

**Comment by djbrooke** [comment]
@jggautier Thanks. So a quick fix (hopefully :)) and a note about running reexports in the release notes.

**Comment by djbrooke** [comment]
@jggautier @scolapasta - can you discuss before we pick this up for the sprint? Thank you!

**Comment by jggautier** [comment]
The to-do in the code that @pdurbin pointed to says "get "Production Date" from datasetfieldvalue table":

<kbd><img width="506" alt="Screen Shot 2019-12-11 at 3 52 27 PM" src="https://user-images.githubusercontent.com/18374574/70659748-b50fb400-1c2e-11ea-908d-c923b6de367e.png"><kbd>

I didn't realize that when the dataset also has a user-entered Distribution Date, the JSON export also includes the distributionDate at the "datasetVersion" level:

<kbd><img width="587" alt="Screen Shot 2019-12-11 at 4 47 46 PM" src="https://user-images.githubusercontent.com/18374574/70663272-ffe0fa00-1c35-11ea-89ad-213026685bab.png"></kbd>

So it seems like the intent was to repeat, in the JSON export, the date metadata that users enter in the Distribution Date and Production Date fields (in the Citation metadata block). (But right now the Production Date is hard coded, and that to-do is saying that it should be dynamic, like the Production Date is.)

But why is the dataset version's Distribution Date and Production Date metadata, already in the JSON export at the "metadataBlocks" level, repeated at the "datasetVersion" level above it? Is it because it's easier to get the values at that level? Why not include the Deposit Date?

**Comment by djbrooke** [comment]
Adding myself to add a release note for re-running exports.
