### ISSUE TITLE
Affiliation field on dataverse create/edit form was changed to be required

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#6430]
On the dataverse create/edit form, the Affiliation field is now required. I think it wasn't required until one of the more recent Dataverse versions (maybe 4.18 or 4.18.1).

On Harvard Dataverse (4.18.1), this dataverse [was published Oct. 23](https://dataverse.harvard.edu/api/dataverses/pnas_dropletafm) and the Affiliation field is empty. 

<img width="721" alt="Screen Shot 2019-12-03 at 1 38 48 PM" src="https://user-images.githubusercontent.com/18374574/70079203-426d5b80-15d2-11ea-8b5c-4114ad4fc8b5.png">

But today when Sonia tried to save changes she'd made on the form, and she didn't fill out the Affiliation field because it hasn't been required until recently, she was told she had to fill the Affiliation field.

Almost all dataverses created since Oct 23 (and maybe going even further back) already include Affiliations, so this might be a change that most people won't notice but can encourage a few people to add more metadata to their dataverses.

BUT it will be disruptive to curators, like Sonia, who need to update dataverse metadata and don't know what to add to the new required Affiliation field.

**Comment by mheppler** [comment]
This appears to have been an oversight in #5615 when making accessibility improvements to the form, by mistakenly copying the `required="true"` attribute into the input, and adding the asterisk icon.

@djbrooke with your "Small" estimate blessing, I can drag this into development, review all the changes again and make a PR to fix this.

**Comment by djbrooke** [comment]
@mheppler feel free, thank you!

**Comment by mheppler** [comment]
Reviewed the other changes to the dataverse form in the PR for #5615, and did not see any other fields effected by any similarly dumbfounding oversights. 🤦‍♂
