### ISSUE TITLE
Using other waiver that cc0

### ISSUE THREAD

**Issue by tcoupin** [IQSS/dataverse#6436]
At Datasuds (https://dataverse.ird.fr), we don't use CC0 but french waiver or CC by 4.0.
When I check "Don't use cc0", terms tab show "No waiver has been selected" but terms of use is "CC BY 4"

![image](https://user-images.githubusercontent.com/7457386/70249693-09bdb580-177d-11ea-8aff-d56ba3285a61.png)

I would be great if term of use is set to not display "no waiver has been selected".
Or better allow administrator to set a list of waiver instead of only CC0.

**Comment by pdurbin** [comment]
Related: License: Multiple Options for Licensing #1753

**Comment by poikilotherm** [comment]
Please note my [latest comment](https://github.com/IQSS/dataverse/issues/1753#issuecomment-616609972) to #1753

**Comment by poikilotherm** [comment]
There's a new kid on the block. #7440

**Comment by pdurbin** [comment]
@tcoupin now that multiple licenses are supported, are you all set? Please see these docs: https://guides.dataverse.org/en/5.11.1/installation/config.html#configuring-licenses

**Comment by tcoupin** [comment]
We are still in version 5.5 but I think this new feature are exactly what we need for dataverse.ird.fr

**Comment by pdurbin** [comment]
@tcoupin great! Can we close this issue? You can create a fresh once have you've had time to test multiple licenses.
