### ISSUE TITLE
Header above breadcrumb incorrect when Adding a new Dataverse

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#6440]
When Adding a new dataverse the header no longer says "New Dataverse", but rather the suggested name of the Dataverse you are creating (as if it existed). Additionally, because of that is a link that leads to a Page not Found if you click on it:
https://dataverse.harvard.edu/dataverse/

![image](https://user-images.githubusercontent.com/4268292/70348962-ca04d580-1831-11ea-8e71-026358a093a1.png)

**Comment by TaniaSchlatter** [comment]
Solutions:

- make dynamic content more dynamic, so that the breadcrumb better reflects and is consistent with the text field

- back out of using dynamic content (name and affiliation), and go with simple, clear, and consistent "New Dataverse" 

- make the header static – not a link

**Comment by djbrooke** [comment]
@mheppler and @scolapasta to connect over slack call to resolve some blockers on this. Thank you!

**Comment by mheppler** [comment]
Fixed page not found bug by removing link, as well as dynamic name and affiliate from header on New Dataverse form. Restored the rendering logic that was already in the dataverse_header include by adding a `ui:param` passed to the header via the template per the suggestion from @scolapasta. Demo'd and confirmed with @TaniaSchlatter.

![Screen Shot 2020-02-04 at 10 55 44 AM](https://user-images.githubusercontent.com/687227/73761808-5867db80-473d-11ea-975d-25b5b850d4ee.png)
