### ISSUE TITLE
Update website for ingesting Stata v14-v15 datasets

### ISSUE THREAD

**Issue by kuriwaki** [IQSS/dataverse#6444]
Website guide has not been updated to reflect   that #4708 has been merged and Stata v14-v15 can now be ingested. It says dataverse supports only up to v13 [here](https://github.com/IQSS/dataverse/blob/e12cc477b0668eb78483f1d1a2153a1dd53a0db9/doc/sphinx-guides/source/user/tabulardataingest/stata.rst) and [here](https://github.com/IQSS/dataverse/blob/e12cc477b0668eb78483f1d1a2153a1dd53a0db9/doc/sphinx-guides/source/user/tabulardataingest/supportedformats.rst) (there may be more locations).

**Comment by djbrooke** [comment]
Thanks @kuriwaki for the report. We missed this doc update. We'll fix in the next sprint.

**Comment by pdurbin** [comment]
Fixed in pull request #6451
