### ISSUE TITLE
Index: Previous Persistent ID field does not appear to be indexed, can't search on old handles.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#6445]
When we converted hdl PIDs to doi, we added a field, Previous Persistent ID. It appears that this field is not indexed so although the hdl url is resolvable when entered in the browser, the hdl PID is not searchable. This may make (re)discovery of datasets by the older hdl PID more difficult.

**Comment by scolapasta** [comment]
Do we need it to be searchable, though? It's harmless to add, so it's fine if we want it, but what we really wanted was to have a reference to it on the dataset page, so if someone came to it from a citation it would be clear why they were on that dataset. 

In other words, what's the use case for searching on a handle? (and again, I'm not against it, just trying to fully understand if it's really needed)

**Comment by kcondon** [comment]
@scolapasta Yes, I believe we do want it to be searchable. Imagine for a moment that someone has a badly formed url and writes in to Support, requesting access to said PID. Tech supporter confirms URL is bad, then searches on hdl to see whether it actually exists but nothing appears. Hmm, would be useful if it was searchable. They then realize field is not index and open a github issue.

**Comment by djbrooke** [comment]
We'll add this in a sprint soon.

**Comment by djbrooke** [comment]
We'd want to make only one field searchable here (Dataset Persistent ID) to search the previous PID and other IDs.
