### ISSUE TITLE
Shibboleth not working in AWS with ELB

### ISSUE THREAD

**Issue by nightowlaz** [IQSS/dataverse#6449]
I am trying to implement Shibboleth authentication on a Dataverse installation that runs in AWS EC2. I have verified that it works correctly without the load balancer. I have created SSL certificate files locally using "Let's Encrypt", and on AWS we have a wildcard certificate installed to cover all domains under the main domain of our organizational unit. I have exchanged metadata with my IDP (my organization main IT), and the SSO works correctly when accessed directly to the EC2.  When I have the load balancer in place (either ALB or NLB), using the ACM certs, and click Login using my IDP (or have tried it on SAMLtest as well), it goes through the CAS SSO, then takes me to the SAML user preferences screen, then takes me back to the DV dashboard, but does not create an account or log me in. It just stays on the "Account Information" page of the dashboard with a blank page (does not list the fields) or the CREATE account button.

**Comment by nightowlaz** [comment]
Just an update on this...the issue was due to my target group in AWS (that the ELB forwarded to) being configured to route on port 80 instead of port 443. I created a new target group that routes https on port 443 and registered the target also on port 443 and shibboleth works as expected.

**Comment by pdurbin** [comment]
@nightowlaz good job figuring it out! 🎉 🎉 🎉 

Thanks for letting us know!
