### ISSUE TITLE
Improve thumbnails

### ISSUE THREAD

**Issue by TaniaSchlatter** [IQSS/dataverse#6450]
Thumbnails were created because Harvard Dataverse stakeholders wanted to identify their datasets with an image. Thumbnails work well when they are set by a user, and/or when a dataset has a lot of file types.

There are several issues with thumbnails:

- many datasets do not have a thumbnail, and the default icon is not informative.

- thumbnail images are too small to be useful on the top of the dataset page.

- thumbnails that the system selects by default are limited and often do not show useful information.

This issue is intended to capture research, examples, and use cases to help improve thumbnails. 

Discovery: https://docs.google.com/presentation/d/1Oir1n6KVauYxxZcNyuJsVmpvY4HCa0K0gzRGzxjTV-I/edit#slide=id.g6bdb0a7b77_0_50

**Proposed Solutions**
1. Improve technology:

- improve the resolution of thumbnails, so that they can be displayed at larger sizes (#5679, originally opened in part to help improve the display of thumbnails in social media)

- improve technology to recognize a wider range of image file types (issues?)

2. Improve UI:

- make thumbnails larger, without adding emphasis to default thumbnail icons (see #6605)

- make the differences between default thumbnails more clear: Dataverse (a container), dataset (a collection), and file (an item of a certain type see #7991 )

[UI sketches in progress](https://sketch.cloud/s/PWk71/a/Mwpgrw/play)

3. Encourage users to upload/select custom thumbnails: 

- prompt users to add a dataset thumbnail before publishing

- highlight/flag the thumbnail image to users who have edit permission as a way to increase the visibility of the thumbnail feature, and prompt users to select or add a different (more useful) thumbnail image

- add a "crop" feature to help select more useful sections of thumbnail images

**Comment by TaniaSchlatter** [comment]
To dos:

- [ ] review UI sketches internally

- [ ] review related technical issues

- [ ] review UI sketches with the community

**Comment by TaniaSchlatter** [comment]
This issue is related to #6684, and needs to be addressed along with #5679 to move #6684 forward.

**Comment by pdurbin** [comment]
> improve technology to recognize a wider range of image file types

Related:

- #8194
