### ISSUE TITLE
Research and document autocomplete/typeahead instances and behavior

### ISSUE THREAD

**Issue by TaniaSchlatter** [IQSS/dataverse#6466]
Create an inventory of autocomplete/typeahead components in the UI, including:
- location 
- purpose (user goal and system goal)
- behavior (front end feedback and functionality, such as returning results from the start of a text string vs middle of text string)

as a step toward improving data entry UX. We want to document what components we have, how they function, and why so we can make informed decisions about how they should behave, how they might behave better, and how consistent or inconsistent they should be and why. 

Related:

- #6467

**Comment by pdurbin** [comment]
Alas, I never got search autocomplete working in JSF back in 2015. To me search is an obvious place to have autocomplete if we can:

- #108
