### ISSUE TITLE
File Replace - "...same file" validation error msg not displayed correctly

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#6468]
On Dataverse 4.18.1, when I try to replace a file with another file that has the same content (same md5), I'm not immediately getting the error message that "You cannot replace a file with the exact same file.":

<kbd>![filereplacebug](https://user-images.githubusercontent.com/18374574/71121299-38d81c00-21ac-11ea-81d9-2763855bde91.gif)</kbd>

There's no messaging that the replace didn't work or why.

But if I then try to replace the file with a file that **does not** have the same content, the replace succeeds, and the error message that should have appeared when the replace failed the first time appears here:

<kbd>![filereplacebug2](https://user-images.githubusercontent.com/18374574/71121762-14307400-21ad-11ea-9695-50f7041a59e1.gif)</kbd>

So it's like the error message for failed attempts only appears once a successful attempt as been made.

**Comment by djbrooke** [comment]
We expect this will be fixed by work in #4813/#6924. I'll add it to the "closes" there.
