### ISSUE TITLE
User Account: Displayed user name  and contact email changes from admin to another user during session (session bug)

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#647]
---

Author Name: **Kevin Condon** (@kcondon)
Original Redmine Issue: 4096, https://redmine.hmdc.harvard.edu/issues/4096
Original Date: 2014-06-12
Original Assignee: Elda Sotiri

---

This was reported by Liz and occurred during a UX session with Gary and witnessed by Gustavo.

Gary logged in as admin on demo, performed some basic operation: create dv, checked user account page, then at some point the displayed user account changed from admin to another user. The contact email also changed to that user. When they logged out, it returned to admin.

There was an error during that session that may or may not have affected the session data.

So far we have not reproduced this. It seems to initialize the user session/ account info and then some operation incorrectly updates the session info (perhaps visiting the account page?) and logging out resets to correct values, possibly rereading from db?

Will need to reproduce.

---

Redmine related issue(s): [1096](https://redmine.hmdc.harvard.edu/issues/1096)

---

**Comment by pdurbin** [comment]
Just an observation: during our last beta push (Beta 10), we did not happen to observe the session bug on dvn-build. (Often as we near a beta push we see the session bug because there is more traffic, generally, hitting the server.) The primary change has been upgrading Glassfish to 4.1 and Weld to 2.2.4. Of course we have no idea if this is simply a correlation.

**Comment by scolapasta** [comment]
Moving to QA, as we have not seen this since the glassfish / weld changes.

**Comment by scolapasta** [comment]
We are no longer seeing this since the weld update.

**Comment by pdurbin** [comment]
See also https://community.atlassian.com/t5/JIRA-questions/Frequent-logouts-and-Session-swap-hijack-in-JIRA/qaq-p/320125 which came in via a comment on a Google doc but I haven't really read that post in detail. For now, the solution is still to patch Weld as described at http://guides.dataverse.org/en/4.6.2/installation/prerequisites.html#installing-glassfish
