### ISSUE TITLE
Metadata Block - Add help text block

### ISSUE THREAD

**Issue by youssefOuahalou** [IQSS/dataverse#6476]
I think it will be more useful for the help block to be more flexible to add.
As in the example of being able to add it to the keyword block for example
![Blokhelp](https://user-images.githubusercontent.com/46802308/71265473-96a06b80-2346-11ea-8a71-759d7c7994e8.PNG)

**Comment by BPeuch** [comment]
Yes indeed. We find this small line of explanation above the Description > Text field very useful. It would be very handy to be able to add a line like this above all fields to give users further guidelines on how to format their input, direct them to external resources, etc.

We know there are already watermarks and information bubbles (the latter were not available in earlier versions; they look really great!). But we fear users might overlook these. A customizable text area like this would greatly help.

**Comment by TaniaSchlatter** [comment]
Thanks for the feedback and opening the issue, @BPeuch and @youssefOuahalou. It sounds like you would like for your installation to be able to add explanatory text above all fields?

**Comment by BPeuch** [comment]
Yes indeed, @TaniaSchlatter. Thanks for reaching out.

We feel like this could help make Dataverse more customizable and adjustable to the various users' needs. Some of our users told us that the meaning of certain fields' names were unclear to them, and though the information bubbles are a great addition to the UI, we fear some users might overlook them and just neglect certain fields if they're not mandatory.

**Comment by mheppler** [comment]
This feature was also requested in issue **Dataset Metadata: Add Help Text for Geographic Bounding Box Fields #950**.

**Comment by pdurbin** [comment]
@youssefOuahalou @BPeuch a feature of 5.12 is this (from the release notes in PR #8996):

"Collection managers can create templates that include custom instructions on how to fill out specific metadata fields."

I'm not sure which PR this was. @qqmyers coded it up, I believe, and would probably know.

I'm curious if this would meet your needs.

**Comment by BPeuch** [comment]
@pdurbin That sounds great! We're eager to test this new feature. Thanks a lot for the feedback and the new developments, @qqmyers & @pdurbin :)

**Comment by pdurbin** [comment]
@BPeuch sure, I'll try to remember to let you know when https://demo.dataverse.org has been updated to 5.12.
