### ISSUE TITLE
Granted role notification shows all roles

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#6479]
When you are granted a role on an dataset (or other dvobject), the notification shows all roles you have for that object, not just the one you were just granted. Additionally, any existing, past notifications showing a granted role for that object show all current roles, instead of the role at that time.

![image](https://user-images.githubusercontent.com/4268292/71285853-2f79bb80-2334-11ea-91df-0e89a4fa89c3.png)

Note in the image, only one role was assigned at a time, and what all of them show is the current state of roles.

**Comment by TaniaSchlatter** [comment]
The desired behavior is that when there is a role change, an alert should be triggered in the UI, and sent via email that notifies the user of whatever has been changed only. We should not show the current state of all roles, and we should not change the date of roles.

**Comment by scolapasta** [comment]
Agreed. Same thing happens with e-mails (except, of course, the back porting):

![image](https://user-images.githubusercontent.com/4268292/71287868-74532180-2337-11ea-96b8-15dbd5365700.png)

**Comment by mheppler** [comment]
Related to #1336.
