### ISSUE TITLE
Add ClojureScript to list of Dataverse client libraries (SDKs)

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#6487]
Thanks to @tainguyenbui and @theam there is a Dataverse client library (SDK) for Javascript. 🎉 

Thanks to @2knu and @Deraen and https://github.com/cljsjs/packages/pull/1974 a "cljsjs/js-dataverse package" appears at http://cljsjs.github.io like this: 🎉 🎉 🎉 

![Screen Shot 2020-01-07 at 10 00 03 AM](https://user-images.githubusercontent.com/21006/71904933-15621a80-3135-11ea-888e-e8b439bb2990.png)

I believe this means we could legitimately add ClojureScript to the list of Dataverse client libraries at http://guides.dataverse.org/en/4.18.1/api/client-libraries.html

Obviously, it might be nice to test it first. I do know a Clojure developer so maybe I could recruit him to try it out. 😄 

Or we could just list it and let people come along and find it, try it, and let us know if it doesn't work. 😄

**Comment by daveliepmann** [comment]
Looking at the js-dataverse entry on cljsjs.github.io, it appears that the "Project Site" link is broken. On my machine it opens up a new tab that 404s trying to reach https://github.com/js-dataverse/js-dataverse. (Hitting "Back" on that new tab goes to https://github.com/cljsjs/packages/tree/master/js-dataverse, which works, and which has the 404ing URL in its README.)

Should that point to https://github.com/IQSS/dataverse-client-javascript (or https://github.com/IQSS/dataverse)?

**Comment by daveliepmann** [comment]
I tested and found mixed success. 

I created a project template with [chestnut](https://github.com/plexus/chestnut) and added the following dependencies to *project.clj*:

```clojure
                 [cljsjs/js-dataverse "1.0.17-0"]
                 [kitchen-async "0.1.0-SNAPSHOT"]
```

([Kitchen-async](https://github.com/athos/kitchen-async) is used to handle javascript promises.)

I changed the namespace declaration in *src/cljs/dataverse_hello_world_chestnut/core.cljs*:

```clojure
(ns dataverse-hello-world-chestnut.core
  (:require [reagent.core :as reagent :refer [atom]]
            [js-dataverse]
            [kitchen-async.promise :as p]))
```

Then I started a REPL (with emacs and CIDER, following the chestnut-created README instructions) and tried to translate the example DataVerse code to CLJS.

```javascript
const client = new DataverseClient('https://demo.dataverse.org/')
```
became
```clojure
(def client (js-dataverse/DataverseClient. "https://demo.dataverse.org/"))
```
and worked fine. However I've run into errors with
```javascript
const response = await client.getDataverseInformation('myDataverseAlias')
```
and it's unclear whether this is Dataverse or my inexperience with promises in CLJS. 
```clojure
(def rsp (client.getDataverseInformation "myDataverseAlias"))
```
This causes `TypeError: this is null` in the console. Could this be an invalid alias issue?

**Comment by Deraen** [comment]
Try

```cljs
(-> (.getDataverseInformation client "myDataverseAlias")
    (.then (fn [result] (js/console.log result))
    (.failure (fn [error] (js/console.warn warn)))
```

`client.getDataverseInformation` is not syntax error, but it doesn't do anything useful in this case. To call method of an Object use the method name prepended with dot and provide the object as first parameter to the call.

https://cljs.github.io/api/syntax/dot

I'm also somewhat conflicted (even as Cljsjs maintainer) if it is good idea it is to recommend Cljsjs packages, as we nowadays have other solutions which allow using npm packages directly. [Shadow-Cljs](https://shadow-cljs.github.io/docs/UsersGuide.html) works pretty effortlesly and using [Webpack](https://clojurescript.org/guides/webpack) is possible but requires a bit more setup.

**Comment by pdurbin** [comment]
@daveliepmann @Deraen thanks so much for diving into the conversation here!

With regard to a dataverse "alias" I thought I'd give you an example. For https://demo.dataverse.org/dataverse/wholetale the alias is "wholetale". I hope that helps! I'm very happy to answer any questions you may have about Dataverse terminology, APIs, etc.

And maybe I can ask a question I had yesterday. Cljsjs gives support for ClojureScript (which is awesome) but not Clojure itself, right?

**Comment by daveliepmann** [comment]
Using Deraen's corrected code above (thanks!) lets me move forward to the next error: `Error: Bad api key`.

>Cljsjs gives support for ClojureScript (which is awesome) but not Clojure itself, right?

Correct

**Comment by pdurbin** [comment]
@daveliepmann sounds like we're getting somewhere! Great! Please see http://guides.dataverse.org/en/4.18.1/api/auth.html#how-to-get-an-api-token

**Comment by pdurbin** [comment]
> Looking at the js-dataverse entry on cljsjs.github.io, it appears that the "Project Site" link is broken. On my machine it opens up a new tab that 404s trying to reach https://github.com/js-dataverse/js-dataverse.

I just noticed this myself. @Deraen do you know why this is? Thanks!

By "Project Site" we mean at http://cljsjs.github.io and here's a screenshot:

<img width="724" alt="Screen Shot 2022-09-29 at 7 57 03 PM" src="https://user-images.githubusercontent.com/21006/193162100-4ee0378c-f55a-4a88-a3a6-d089cfd1bf74.png">

**Comment by Deraen** [comment]
@pdurbin The cljsjs package hasn't been updated in 3 years, so it points to some old URL still.

Cljsjs isn't used much now, as there are easier ways to use npm packages directly: https://github.com/cljsjs/packages/issues/2127

**Comment by pdurbin** [comment]
@Deraen interesting! I think I'll go ahead and close this issue then. I very much appreciate you and @2knu getting the cljsjs package working (and @daveliepmann for testing it) but I think we can wait for the next generation thing to come along.
