### ISSUE TITLE
Allow commands to get identifiers rather than objects

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#649]
---

Author Name: **Michael Bar-Sinai** (@michbarsinai)
Original Redmine Issue: 4098, https://redmine.hmdc.harvard.edu/issues/4098
Original Date: 2014-06-13
Original Assignee: Michael Bar-Sinai

---

So permissions checks can be done w/o loading the DvObject to memory

**Comment by kcondon** [comment]
@michbarsinai is this something we can close for now or is there something to discuss or consider?

**Comment by michbarsinai** [comment]
It's something we need to do at some point, and would gain us some performance by reducing DB calls. It's not urgent, though. Do we have a "do this if you have some free time" list?

**Comment by pdurbin** [comment]
Do we have free time? 😉

**Comment by pdurbin** [comment]
@michbarsinai how much value is there in leaving this issue open? I'd like to close it.

**Comment by michbarsinai** [comment]
OK.
