### ISSUE TITLE
New Installer: implement "pod name"-based features for OpenShift/Docker

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#6494]
This was implemented in the old installer as part of the "Cloud Dataverse" collaboration. I'm opening a new issue for this (separate from parent issue #3937), because it appears that this functionality is currently broken in the old script and needs to be revisited. There's code that's supposed to set up PostgreSQL on one of the OpenShift pod instances - but it appears to be inaccessible, due to some faulty logic. 

The way it was originally implemented, the script would check some environmental variables set by OpenShift, and based on them decide what needs to be set up on this particular pod (app server; database; etc.) and what config parameters to use. I'm wondering if we'll be better off keeping this special code out of the main installer; and adding a straightforward wrapper shell script, that would check and interpret the environmental variables, and pass them to the installer via the standard command line options and/or .config file entries.

Either way I feel it's logical to address this in a separate issue.

**Comment by pdurbin** [comment]
@landreev can we close this? We deleted all the OpenShift stuff a while back.

**Comment by landreev** [comment]
@pdurbin Yes, we should!
