### ISSUE TITLE
Localize Embedded Discovery Service (EDS) based on Dataverse header language dropdown selection.

### ISSUE THREAD

**Issue by manikon** [IQSS/dataverse#6496]
The issue occurs on the RemoteProvider Login Page for all users on all Dataverse versions.
The properties that are read from bundle.properties are being translated but not the properties from the idpselect_config.js (langBundles).

![beforeFix](https://user-images.githubusercontent.com/43245751/72095088-cd362a00-32e5-11ea-9056-03bb8c0c5110.jpg)

Currently Shibboleth EDS is adjusted as a function of the language and locale of the browser as determined by the EDS.
[Shibboleth EDS](https://wiki.shibboleth.net/confluence/display/EDS10/3.3+Internationalization)

**To fix the issue for dataverse installations that choose to configure internationalization**, the language selected from the dataverse header language dropdown should take precedence over the locale of the browser and the default language.
`curl http://localhost:8080/api/admin/settings/:Languages -X PUT -d '[{"locale":"en","title":"English"},{"locale":"fr","title":"Français"}]'`

After the fix, the login page would look as shown below.
![afterFix](https://user-images.githubusercontent.com/43245751/72095161-f6ef5100-32e5-11ea-9986-8142328e87df.png)

**The fix should not affect dataverse installations that choose not to use internationalization.**

When Dataverse upgrades to Shibboleth V1.1+, then idpselect_languages.js would need to be updated with the french translations.
[Shibboleth EDS](https://wiki.shibboleth.net/confluence/display/EDS10/3.3+Internationalization)

**Comment by djbrooke** [comment]
Hey @manikon, this seems to make sense. Are you able to provide a pull request?

**Comment by manikon** [comment]
Hey @djbrooke, just realized that this issue has been fixed by @tcoupin on develop.
[move shibboleth i18n from js to bundle ](https://github.com/IQSS/dataverse/commit/3b441dcc5bf21ee17bf80e91b7d034de7a65e41b#)

I just need to add the corresponding french translations to the language pack.

**Comment by djbrooke** [comment]
@manikon that's great, I thought this looked familiar. :) I'll close this out since the development portion is complete.
