### ISSUE TITLE
Change logging level from fine to warn for exceptions

### ISSUE THREAD

**Issue by pkiraly** [IQSS/dataverse#6499]
In several cases (33 matches in 20 files) the caught exceptions are logged with FINE level. E.g.:

```
try {
  passportValidatorMinLength = Integer.parseInt(_passportValidatorMinLength);
} catch (NumberFormatException nfe) {
  logger.fine("Invalid value for PwMinLength: " + _passportValidatorMinLength);
}
```

There are many informative notification in FINE level, which doesn't give you important information in case of something is not happenning as expected. Exceptions are more importants, since it catches some errors, so they should be distinguishable from these lowel level notifications. I suggest to change each log entries created by exception handling at least warn level.

[Suggestion:]
```
try {
  passportValidatorMinLength = Integer.parseInt(_passportValidatorMinLength);
} catch (NumberFormatException nfe) {
  logger.warning("Invalid value for PwMinLength: " + _passportValidatorMinLength);
}
```

The regex to catch the occurences: `Exception .+? ?\) \{\n\s+logger\.fine`.

**Comment by pkiraly** [comment]
A pull request has been made: #6500

**Comment by pdurbin** [comment]
> A pull request has been made: #6500

It looks like the pull request above got closed in favor of a smaller one that got merged?

@pkiraly are we all set? Can we close this? Thanks.
