### ISSUE TITLE
help on recovering missing datasets

### ISSUE THREAD

**Issue by xoroz** [IQSS/dataverse#6503]
Hello everyone,
I am running version 4.15 with docker.
We inserted some data and created some users, we see the users structure and can login but from the web interface we can not see the datasets anyome.
Anyone could help us troubleshooting ?
I raised the db log level, but there is too much going on... 

Thank you

**Comment by pdurbin** [comment]
@xoroz this is the first thing I'd try: http://guides.dataverse.org/en/4.18.1/admin/solr-search-index.html#full-reindex

**Comment by xoroz** [comment]
it worked!
thank you very much
