### ISSUE TITLE
Glassfish Upgrade - Null Pointer exception on Dataset - Edit Metadata

### ISSUE THREAD

**Issue by sekmiller** [IQSS/dataverse#6512]
When trying to edit a dataset's metadata where the owning dataverse does not have any custom dataset field input levels you get a Null Pointer exception at Line 1624 of DatasetPage.java

On line 1618 the method on the datasetFieldTypeInputLevel service bean returns a null in Payara while when running Glassfish 4.1 the same line returns an empty array so there is no exception.

Again to recreate: create a dataset in a dataverse where there are no custom input levels for any of the dataset field types, then try to Edit Metadata. You should then see the exception in the log. 

An easy fix would to be to put in a null check around the for loop at 1624.

**Comment by scolapasta** [comment]
This is related to #6448 in that we are r using a view param in the page, so the partial submit replaces our value with the original. The solution is the same; use omnifaces for the viewparam, ie. <o:viewparam>.
