### ISSUE TITLE
Edit Dataverse - Reverting to Parent Metadata blocks confirmation invokes "Save"

### ISSUE THREAD

**Issue by sekmiller** [IQSS/dataverse#6516]
When you are editing a Dataverse that does not inherit metadata blocks from its parent and you click the "Inherit" option button a dialog pops up asking if you're sure you want to do away with any customization you have done to the metadata blocks or input levels of individual dataset field types. If you click "Continue" the Dataverse Save method is invoked and you are out of edit mode. The save works as expected, but you aren't given any indication in the popup that it works like that. User would probably expect to continue in edit mode until they actually press "Save" button.

**Comment by scolapasta** [comment]
While looking at this issue, please also review the update="@all" attribute related to this code (line 253 of dataverse.xhtml). Generally, we shouldn't be using @all anywhere, so when fixing this, it will be a good time to all review this.

In this case update="dataverseForm :messagePanel" is probably the appropriate replacement.
