### ISSUE TITLE
Translate controlled vocabulary using identifier in the property

### ISSUE THREAD

**Issue by bappun** [IQSS/dataverse#6520]
The label of a controlled vocabulary can be very long and include special characters so it can be quite complicated to convert it to a property as described [here](http://guides.dataverse.org/en/latest/admin/metadatacustomization.html#id8)

For instance, if we have this controlled vocabulary in our citation.tsv:
- datasetfield: timeMethod
- value: Longitudinal: Cohort/Event-based
- identifier: Longitudinal.CohortEventBased

The property should be: 
> controlledVocabulary.timeMethod.longitudinal:_cohort/event-based=...

I think it could be helpful to be able to use the identifier of the controlled vocabulary in order to write the property like so:
> controlledVocabulary.timeMethod.Longitudinal.CohortEventBased=...

It would also make the updates of the value easier to do when having multiple languages. However there might be problems with this example (full stop, uppercases).

**Comment by pdurbin** [comment]
@JayanthyChengan and @4tikhonov, what do you think? They are closest (I think) to https://github.com/GlobalDataverseCommunityConsortium/dataverse-language-packs

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
