### ISSUE TITLE
Fix validation for empty host name autocomplete input

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#6532]
@kcondon found this while testing the glassfish upgrade PR:

Steps to reproduce:
1. Add Dataset.
2. Click in host dataverse.
3. Type additional characters and wait for autocomplete to say “No matches found:"
4. remove those characters and click other input field (the autocomplete should remain on the screen.
5. keep filling out form and click save.

Result: 
Page grays out, but then never completes due to exception being thrown:

```  For input string: "kc011620 kc011620 Dataverse"
java.lang.NumberFormatException: For input string: "kc011620 kc011620 Dataverse"
...
edu.harvard.iq.dataverse.DataverseConverter.getAsObject(DataverseConverter.java:29)

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
