### ISSUE TITLE
Data related to me for superuser always shows all data

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#6533]
When you're in the data related to me as a supersuer, you have the ability to type a username to see what they would see on that page. That seems to be broken as typing anything still results in seeing the same cards as you would if you were the superuser.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
