### ISSUE TITLE
Add dataset and file PIDs to guestbook csv download

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#6534]
In all Dataverse 4.x versions, the guestbook csv file that dataverse owners can download identifies the datasets by dataset title:

<img width="560" alt="Screen Shot 2020-01-16 at 3 21 17 PM" src="https://user-images.githubusercontent.com/18374574/72559896-ddb14c00-3873-11ea-8863-f87301222ca1.png">

I recently helped someone who needed to analyze the data in a dataverse guestbook, and the instability of the dataset titles, the only way that the dataset is identified, became a problem.
- In the guestbook csv, commas are removed from dataset titles (https://github.com/IQSS/dataverse/issues/3449)
- The title shown is always from the first published version of the dataset, so for example, if the dataset title "Japan 1954" in the screenshot above was to change in a later published dataset version to "Replication data for: Japan 1954", the guestbook will still identify the dataset with "Japan 1954".

This instability makes it difficult to work with this data (like combining it with data from other sources).

Since the dataset DOI should be more stable, could that be added to the guestbook?

**Comment by djbrooke** [comment]
Yes, we should add this. Makes sense.

**Comment by djbrooke** [comment]
- We should add the two columns (File PID and Dataset PID) to the .csv download
- We will need to modify the custom queries
- We should handle the case where File PIDs are not enabled

**Comment by pdurbin** [comment]
@jggautier do you have a preference for *where* the two columns are inserted?

Here's how it could look if we insert the columns inline:

```
$ git diff
diff --git a/src/main/java/edu/harvard/iq/dataverse/GuestbookResponseServiceBean.java b/src/main/java/edu/harvard/iq/dataverse/GuestbookResponseServiceBean.java
index 7ac791acf..7159fab64 100644
--- a/src/main/java/edu/harvard/iq/dataverse/GuestbookResponseServiceBean.java
+++ b/src/main/java/edu/harvard/iq/dataverse/GuestbookResponseServiceBean.java
@@ -140,7 +140,7 @@ public class GuestbookResponseServiceBean {
         List<Object[]> guestbookResults = em.createNativeQuery(queryString).getResultList();
 
         // the CSV header:
-        out.write("Guestbook, Dataset, Date, Type, File Name, File Id, User Name, Email, Institution, Position, Custom Questions\n".getBytes());
+        out.write("Guestbook, Dataset, Dataset PID, Date, Type, File Name, File Id, File PID, User Name, Email, Institution, Position, Custom Questions\n".getBytes());
         
         for (Object[] result : guestbookResults) {
             Integer guestbookResponseId = (Integer)result[0];
```

**Comment by landreev** [comment]
@pdurbin thank you,  I have adopted the order you proposed above. It makes more sense, as opposed to adding these fields to the end of the line. 
Even if somebody has written a script that relies on the old order, it should be easy for them to figure it out and fix it.

**Comment by pdurbin** [comment]
@landreev yeah, and we can always add a release note to alert people that columns have shifted a bit.
