### ISSUE TITLE
dropbox file upload: files larger than 1GB failing without error message

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#6535]
see ticket https://help.hmdc.harvard.edu/Ticket/Display.html?id=285188
(Link to data in dropbox is in ticket)

I tried testing in demo but dropbox won't connect in demo at all for upload, so tried directly to the dataset on production.

User reported issue of time-out as in RT ticket.
I tried zip for extraction from dropbox without success.  I tried small image file from dropbox and that was fine. I tried individual large files for this user from dropbox with no success no error message. Tried from my "Finder" individually and it was successful.

Screen shot of blank/no ingest blue progress bar when trying to upload from dropbox

when you start the blue ingest is not there but it indicated some action with spinner
<img width="1841" alt="Screen Shot 2020-01-16 at 1 24 27 PM" src="https://user-images.githubusercontent.com/8322346/72563496-cf672e00-387b-11ea-8f51-a845a45a8aab.png">

results are empty file space, no status, no file upload

<img width="2143" alt="Screen Shot 2020-01-16 at 1 58 12 PM" src="https://user-images.githubusercontent.com/8322346/72563580-f9b8eb80-387b-11ea-8f70-9ecbf44185e9.png">

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
