### ISSUE TITLE
Support File Previews/Explore Tools for Private URL Users

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#6537]
People viewing a draft dataset using the Private URL feature should be able to use the same explore tools and see the same previews as regular users. As peer reviewers take advantage of this feature, it will be helpful to use all of the tooling. 

To reproduce the issue:

- Create a Private URL for your dataset and copy it to your clipboard
- Add a .pdf file (or other previewable file)
- Sign out of Dataverse and click on the private URL
- Go to the file page and see that the preview is not available
- Click the "Explore" button on the file page and be taken to a window that shows an error message in the previewer

If we look at the URL in the window from launching "Explore" we can see that no token is passed. We get something like this:

- https://qualitativedatarepository.github.io/dataverse-previewers/previewers/PDFPreview.html?fileid=xxxx&siteUrl=https://dataverse.harvard.edu&datasetid=xxx&datasetversion=:draft

Instead of something like this which has the private URL user's key:

https://qualitativedatarepository.github.io/dataverse-previewers/previewers/PDFPreview.html?fileid=xxx&siteUrl=https://dataverse.harvard.edu&key=xxx&datasetid=xxx&datasetversion=:draft

**Comment by djbrooke** [comment]
- Add a note about external tools wanting/needing tokens for their operation to the admin guides, security implications therein

**Comment by pdurbin** [comment]
I just made pull request #6625 about the preview tab.

I'm sort of thinking that a note about tokens and security could be a separate small chunk.
