### ISSUE TITLE
Dataverse should correctly categorize certain .spx files as geospatial files

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#6541]
In Dataverse 4.18.1 (and possibly older versions), Dataverse is tagging geospatial files that have the extension .spx as OGG audio files (and the file previewer tries and fails to preview what it thinks is an audio file). If you go to the dataset at https://doi.org/10.7910/DVN/KKQFKA and filter for audio files, you'll find six files that are related to ArcGIS. I'm assuming Dataverse labels them as audio files because there is an audio file format (Speex Audio Compression Format) that shares the same file extension.

Is there a way for Dataverse to tell when an .spx file is an audio file and when it's related to ArcGIS?

**Comment by mheppler** [comment]
Strange. I looked at some resources from recent file type facets work, and found `.spx` files labeled as [Ogg Vorbis Speex File](https://fileinfo.com/extension/spx), but no reference there to [ArcGIS software](https://www.esri.com/en-us/arcgis/products/arcgis-pro/overview). However, a keyword search on that site found 80 file extensions with "ArcGIS" in the Programs field (e.g. .ATX ArcGIS Attribute Index File; .MXT ArcGIS Map Template). All that said, this other resource in fact does label them as [ArcGIS Geodatabase SPX File](https://datatypes.net/open-spx-files).

For comparison's sake, it appears we have nearly [200 OGG Audio (.ogg) files in Harvard Dataverse](https://dataverse.harvard.edu/dataverse/harvard?q=ogg&types=files&fq0=metadataSource%3A%22Harvested%22&fq1=fileTypeGroupFacet%3A%22Audio%22&sort=score&order=desc&page=1) which were harvested from our amigos at e-cienciaDatos.

We should also consult @landreev to look into why the new [JHOVE library](http://jhove.openpreservation.org/) added in 4.15 (#2202) would be missing this identification.

There are loosely documented ways to correct mislabeling like this via the [native API](http://guides.dataverse.org/en/4.18.1/api/native-api.html#add-a-file-to-a-dataset). But a nice friendly ArcGIS label would also require the addition of UI friendly file type labels like `application/spx=ArcGIS Geodatabase SPX File` added to [MimeTypeDisplay.properties](https://github.com/IQSS/dataverse/blob/develop/src/main/java/propertyFiles/MimeTypeDisplay.properties).

```
application/dbf=dBASE Table for ESRI Shapefile
application/dbase=dBASE Table for ESRI Shapefile
application/prj=ESRI Shapefile
application/sbn=ESRI Spatial Index
application/sbx=ESRI Spatial Index
application/shp=Shape
application/shx=Shape
application/zipped-shapefile=Shape
```

And don't forget the file category facet too in [MimeTypeFacets.properties](https://github.com/IQSS/dataverse/blob/develop/src/main/java/propertyFiles/MimeTypeFacets.properties)

```
# Shape
application/dbf=Shape
application/dbase=Shape
application/prj=Shape
application/sbn=Shape
application/sbx=Shape
application/shp=Shape
application/shx=Shape
application/zipped-shapefile=Shape
```

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
