### ISSUE TITLE
When using Make Data Count, display pre-MDC download count as well

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#6542]
Known issue: When MDC metrics are enabled, Dataverse currently doesn't display any download counts for the dataset from before MDC was enabled. Further, it does display file download counts (in the file table and on the file page) which are not MDC and do count from the start of the instance.

To address this for QDR, I've tried the following:
added an :MDCStartDate setting 
added a count of pre-MDC downloads to the dataset display:

![image](https://user-images.githubusercontent.com/6731983/72645516-d6587400-3941-11ea-85d3-5aab94c11f39.png)

added a tooltip for the pre-MDC counts in Bundle.properties:
![image](https://user-images.githubusercontent.com/6731983/72645635-1881b580-3942-11ea-8d2a-3fa7b44c47f4.png)

If there are no pre-MDC counts, the second entry does not appear (i.e. it does not change the display for datasets with all activity post-MDC logging).

Made the tooltip on the file page metrics block MDC-aware and update the tooltip when in MDC mode with a new Bundle.properties entry:

![image](https://user-images.githubusercontent.com/6731983/72645741-51218f00-3942-11ea-86fb-7db03a5ce8f4.png)

We're currently discussing whether these changes are enough to turn on MDC display for the QDR production server. I'll create a branch/PR to make this code available at least as a concrete option to discuss.

**Comment by TaniaSchlatter** [comment]
My thinking is that if we need to display more than one set of numbers, we prioritize one type (such as MDC), and show that in the UI on the page. A secondary number, such as the count generated by the previous method, could be displayed in the popover. In this way, we would be enabling the display of the prioritized count without distraction, and providing more detailed information on demand.

**Comment by qqmyers** [comment]
I think the key use case is when there are, for example, 10 MDC counts and 600 pre-MDC ones, i.e. where the earlier, less precise method, is important to understanding the overall popularity/importance. Given that, I suspect hiding it in a pop-over isn't enough (the user community should comment). (And to be clear - the idea is that these are additive as proposed. The secondary number is not just showing the same count by an alternate, less precise method, it just shows counts from before MDC was turned on, which, for older datasets could be most of the downloads (at least for now)).

However, the issue of distraction makes me wonder if there could/should be some cut-off, e.g. if the earlier downloads are less than MDC ones (or less than some small multiple/fraction) then they don't display/only show in a pop-up (not sure a pop-up would even be useful here).  Seeing 50 (+3 pre-MDC) doesn't add much value. And, having a cutoff would automatically drop the number of datasets showing pre-MDC info over time - as that number became unimportant for that dataset.

**Comment by TaniaSchlatter** [comment]
When considering this (and other similar) UI display issues, we need to keep context in mind, since the UI is an ecosystem of information. I take multiple perspectives. One is from the standpoint of balancing the display of the metrics widget with the relative importance of other information. Another is considering what will provide the most comprehensible information to the most users. A typical model for this type of situation is what I described; prioritizing, and enabling progressive display of information for those who want details. If we find we are providing misinformation if we do not disclose all metrics data, that will need to be considered against the whole and other perspectives.
