### ISSUE TITLE
Google Indexing: Invalid string length in field "description"

### ISSUE THREAD

**Issue by lmaylein** [IQSS/dataverse#6544]
Google complains about this dataset: https://heidata.uni-heidelberg.de/dataset.xhtml?persistentId=doi:10.11588/data/10036

The error message when indexing the dataset is: Invalid string length in field "description"

According to https://developers.google.com/search/docs/data-types/dataset#dataset, the length of the description field of a record must not exceed 5000 characters.

Is it possible to automatically shorten the data in the meta tag?

**Comment by scolapasta** [comment]
Hmm, I think we'll have to (and should be straightforward enough). Though I wonder about the minimum length: "The summary must be between 50 and 5000 characters long" - does it also throw any errors if a description is too short??

**Comment by jggautier** [comment]
I think it would want the description to be 50 or more characters, too. The [structured testing tool](https://search.google.com/structured-data/testing-tool/u/0/) does:

<kbd><img width="750" alt="Screen Shot 2020-01-20 at 11 13 30 PM" src="https://user-images.githubusercontent.com/18374574/72774928-7e886a00-3bda-11ea-8a9c-79995ae4f0fe.png"></kbd>

**Comment by scolapasta** [comment]
So if our descriptions are less than 50, do we not send any? (that doesn't seem ideal, but the alternative is to add filler text?)

**Comment by lmaylein** [comment]
Yes, it's not pretty.
Maybe we can accept the Google complaint if the text is too short. But someone who takes the trouble to provide a detailed description should not have any disadvantages.

**Comment by mheppler** [comment]
Related to #5672, #4632

**Comment by jggautier** [comment]
@lmaylein, is the disadvantage that in Google Dataset Search or in the Google search engine datasets with non-compliant descriptions may not be ranked as highly, their description metadata might not be indexed, or the dataset night not be indexed at all? Just trying to be sure we know what the drawbacks of ignoring these warnings _might_ be.

I haven't found a dataset in Google Dataset Search that has fewer than 50 characters. Haven't tried looking for datasets that I know have more than 5000 characters.

**Comment by bronger** [comment]
While I can sympathise with the upper limit a bit – excessively detailed descriptions should be part of the data rather than the metadata IMO – I am concerned about the lower limit. It is nannying and does not lead to better metadata. FWIW, I don’t want such a restriction in our own instance at my home institution.

**Comment by lmaylein** [comment]
@jggautier : None of our records has a description with less than 50 characters.
The record Google complained about seems to have been indexed anyway:
Somewhat strange is that this record is from 2017, but has only just been claimed by Google.

https://toolbox.google.com/datasetsearch/search?query=Die%20Itinerare%20der%20Pfalzgrafen%20bei%20Rhein%201200-1400&docid=v1KuwBWcbDoa4g%2BsAAAAAA%3D%3D

Then it is probably just annoying (because of the mails from Google, which have to be checked in each case) but not a real problem.

**Comment by jggautier** [comment]
I agree @bronger. There's some effort in the community toward measuring metadata quality and how it affects re-use. I'm hoping we'll be able to measure more as tools and techniques improve (e.g. Make Data Count).

Google just [announced](https://blog.google/products/search/discovering-millions-datasets-web) their Dataset Search is out of beta, and hopefully they'll continue detailing their decisions in [their Google Group](https://groups.google.com/forum/#!forum/datasetsearch-announce). (According to the wayback machine, that description restriction was added in their guidelines between April and June, 2019, and it feels like it was snuck in there.)

Is it okay to close this issue, knowing that we're all keeping an eye on these Search Console errors, how they actually affect search results and what (if anything) Google says about them? For example, if we find that Google decides to stop indexing datasets with non-compliant descriptions, or is explicit about some sort of ranking penalty (or someone gets evidence that there is a ranking penalty), we could re-open this issue or open a new one, to discuss options.

**Comment by lmaylein** [comment]
Yes, it's okay.
