### ISSUE TITLE
In DDI export, use https for the DDI schemaLocation URL

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#6553]
While checking for validation issues with the DDI XML that Dataverse exports, the tool I use (https://www.freeformatter.com/xml-validator-xsd.html) reported that the XML failed validation because "White spaces are required between publicId and systemId.: Line = 1, Column = 50". Some Googling led me to [this GitHub issue comment](https://github.com/openpreserve/jhove/issues/227#issuecomment-303433586) about the error message where the solution was to change the http in the URL in the schemaLocation attribute (within the XML's `<codebook>` element)...

```
<codeBook
	xmlns="ddi:codebook:2_5"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="ddi:codebook:2_5 http://www.ddialliance.org/Specification/DDI-Codebook/2.5/XMLSchema/codebook.xsd" version="2.5">
```

... to https.

In any dataset's DDI XML export, when I changed the http in http://www.ddialliance.org/Specification/DDI-Codebook/2.5/XMLSchema/codebook.xsd to https, the validation tool doesn't report that "white spaces" error (and is able to continue reporting other errors). Maybe the DDI Alliance changed the URL to use https recently? So the DDI Codebook metadata that Dataverse exports should, too, so it's pointing to the right schema URL.

**Comment by jggautier** [comment]
I tried creating a Dataverse instance where I edited the schemalocation URL in two files called [OAI_DDIExporter.java](https://github.com/IQSS/dataverse/blob/739083bb672479b5b832daf03f9b1a7c47caf986/src/main/java/edu/harvard/iq/dataverse/export/OAI_DDIExporter.java) and [DDIExporter.java](https://github.com/IQSS/dataverse/blob/739083bb672479b5b832daf03f9b1a7c47caf986/src/main/java/edu/harvard/iq/dataverse/export/DDIExporter.java) but that didn't work. When I export a dataset's DDI XML, the schemalocation URL still has http.

**Comment by mheppler** [comment]
Found 42 files in the project that have the http version of the schema...

![Screen Shot 2020-02-05 at 11 51 36 AM](https://user-images.githubusercontent.com/687227/73864897-663a6100-4810-11ea-9a22-f1b5fa8a7a61.png)

**Comment by djbrooke** [comment]
- We are talking about the DDI schema specifically, as the other schema.xmls may be http and others may have https

**Comment by pdurbin** [comment]
@jggautier I requested a code review from you in pull request #6621 which has some notes on my findings.
