### ISSUE TITLE
[4.19] Missing assets in release page 

### ISSUE THREAD

**Issue by jri-sp** [IQSS/dataverse#6556]
Hi,

This is just to tell you that `citation.tsv`and `geospatial.tsv` are missing in the release page for version `4.19`. So the wget commands doesn't work if we stupidly copy/paste them ^^

If it can be useful for others, we can find those files here: https://github.com/IQSS/dataverse/tree/v4.19/scripts/api/data/metadatablocks (download them as a raw file).

Anyway, thanks for this new release!

**Comment by djbrooke** [comment]
Thanks @jri-sp for noticing and reporting. We'll get this fixed and we'll announce the release very soon!
