### ISSUE TITLE
Guides - Fix section ref linking

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#6560]
Across our guides, there are many, many instances of documentation writing styles such as:

>See the “Export” section of the Admin guide, for more information...

This style does not contain a link to the section. Some might contain a link to the page, but not the specific section referenced. This can lead to a frustrating user experience for even the most experienced Dataverse users/admins/developers/et al.

The section cross-reference markdown format (see Sphinx documentation: https://www.sphinx-doc.org/en/master/usage/restructuredtext/roles.html#cross-referencing-syntax) for linking to a specific section should be written as:

```
see the :ref:`dataset-linking` section of the User Guide for more information
```

With a reference link on the specific section, such as:

```
.. _dataset-linking:
```

This automatically pulls the section title and neatly places it inline, as seen in this screenshot:

![Screen Shot 2020-01-22 at 4 33 37 PM](https://user-images.githubusercontent.com/687227/72936361-07b3b400-3d35-11ea-99bf-46bb8f05a5cd.png)

Will follow up with a checklist of such instances as I fix them in a follow up comment below.

**Comment by mheppler** [comment]
**Admin Guide**
============

_Managing Datasets and Dataverses_
--------------------------------------
- [x] Dataverse Linking
- [x] Dataset Linking

**Developer Guide**
===============

_Troubleshooting_
------------------
- [x] Fresh Reinstall

**Installation Guide**
================

_Configuration_
----------------
- [x] :MDCLogPath
- [x] :DisplayMDCMetrics

_Installation_
-------------
- [x] Rebuilding Your Dev Environment

**Comment by poikilotherm** [comment]
You might consider taking a look at https://www.sphinx-doc.org/en/master/usage/extensions/autosectionlabel.html

See it in action in the IQSS/dataverse-kubernetes guide.
