### ISSUE TITLE
Guides - Missing quotation marks in curl command for creating dataset via API

### ISSUE THREAD

**Issue by BPeuch** [IQSS/dataverse#6563]
Version: 4.18.1

Hello everybody,
After @youssefOuahalou brought up an error, @pdurbin found out that quotation marks are missing in the curl commands in [this section of the API Guide](http://guides.dataverse.org/en/4.18/api/native-api.html?highlight=already%20doi#create-dataset-command). Otherwise, bash cannot parse the URLs properly (and the ampersand (&) in the first of the two paths confuses it).

It should be:

`curl -H "X-Dataverse-key: [admin token]" -X POST "http://[dataverse URL]/datasets/:import?pid=[digital object identifier]&release=[yes or no]" --upload-file "[folder path]"`

**Comment by djbrooke** [comment]
Hey @BPeuch, are you able to make this change in a PR?

**Comment by BPeuch** [comment]
Thanks for the feedback, @djbrooke. Here it is: https://github.com/IQSS/dataverse/pull/6580
I hope I did this properly. Do tell if there's a problem one way or another.
