### ISSUE TITLE
New contact affiliation metadata in Search API includes parentheses

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#6570]
In Dataverse 4.19, when Search API results include datasets with Contact Affiliation metadata, the affiliation value is wrapped in parenthesis:

<img width="1030" alt="Screen Shot 2020-01-23 at 8 23 58 PM" src="https://user-images.githubusercontent.com/18374574/73037822-66a12800-3e1e-11ea-8ee5-e04ad46c39e8.png">

Was this by design? It reminds me of https://github.com/IQSS/dataverse/issues/5521

**Comment by pdurbin** [comment]
It's funny, nothing jumps out at me in pull request #6441 about why the parentheses would be added. It's definitely worth investigating further though. Very strange.

**Comment by djbrooke** [comment]
- this comes from the datasetfield type format field (@sekmiller please correct me :)) 
- Get the field value, not the display value
