### ISSUE TITLE
Internationalization - Compound names in Facet Category/Facet Label

### ISSUE THREAD

**Issue by mhvezina** [IQSS/dataverse#6573]
[Remaining work regarding issue #5207 maybe ?]

**Suggestion regarding compound names in facetCategory:**

Why not use the `>` symbol which suggests a logical hierarchical sequence and that is often used with breadcrumb navigation ? Would that work for all (a majority of maybe?) languages ?

e.g.:

```
Auteur > Nom
Auteur > Affiliation
Renseignements sur la subvention > Organisme subventionnaire 
Renseignements sur la subvention > Numéro de la subvention

Author > Name
Author > Affiliation
Grant Information > Grant Agency 
Grant Information > Grant Number

Autor > Nombre
Autor > Afiliación
Información de la subvención > Agencia subvencionadora
Información de la subvención > Número de subvención
```

**Comment by kaitlinnewson** [comment]
One issue with this approach is how it impacts accessibility - most screenreaders would read this out as "Author greater than name".

**Comment by mhvezina** [comment]
True it is not used as a mathematical or relational operator here. 
Then maybe a an arrow (U+21E2)? 
The arrow characters are characterized as being for multiple use; according to the Unicode Standard (http://www.unicode.org/reports/tr25/), “_Arrows are used for a variety of purposes in mathematics and elsewhere, such as to imply directional relation, to show logical derivation or implication, and to represent the cursor control keys_.” e.g.:

```
Información de la subvención ⇢ Agencia subvencionadora
Información de la subvención ⇢ Número de subvención
```

On the other hand, I don't know what is the assistive technologies extent of use for accessing Dataverse and how those users would figure out it's a breadcrumb separator, and not a greater than sign, if ">" symbol is chosen. My understanding is that the ">"  breadcrumb separator has become a de facto-standard as it is used by a majority (probably way more than 50%) of web sites for this purpose.

**Comment by kaitlinnewson** [comment]
Some implementations of breadcrumbs in websites cause accessibility problems, regardless of being the standard - unfortunately not everyone is aware of these kinds of issues or is prioritizing accessibility. Adding arrows or greater than symbols in either language introduces an accessibility problem for screenreaders. In some cases it can be mitigated by adding the symbol using CSS or an SVG with an empty alt tag, but @JayanthyChengan said this likely would not work for facets.

A screenreader would read the arrow as "right arrow" (so "Author right arrow name").

This post is a good guide to screenreaders and punctuation: https://www.deque.com/blog/dont-screen-readers-read-whats-screen-part-1-punctuation-typographic-symbols/

**Comment by mhvezina** [comment]
@kaitlinnewson What is wrong in having screenreaders read the arrow as "right arrow" since it is indeed an arrow? and arrow can be used to imply a directional relation (here I would rather say a hierarchical relation)...

e.g. `Grant Information ⇢ Grant Number`

What is the alternative then ? A colon or semi-colon ? A pipe? (moreover the web site you are referring to seems to say that even a colon or semi-colon might not be recognized/read by a screenreader....)

e.g. `Grant Information ; Grant Number`

or having the second part between parentheses?

`Grant Information (Grant Number)`

One thing for sure, not putting a separator makes it difficult to understand (and is grammaticaly incorrect, at least in French and Spanish)

e.g. `Grant Information Grant Number`

**Comment by kaitlinnewson** [comment]
@JayanthyChengan or other developers following along - is it possible to fix the implementation so the strings can be grammatically correct for each language, e.g. by not using a concatenated string, and then having the proper string in the bundle properties? That seems like the most logical solution. Is that too technically complex based on the current implementation?

**Comment by kaitlinnewson** [comment]
(Deleting my previous message as I review the conversation in #5207)

**Comment by jggautier** [comment]
The conversations in the issue at https://github.com/IQSS/dataverse/issues/5207 and the connected issues and PRs makes me think that there's now a way to specify how the names of child fields should appear when they're displayed as facet categories on the search page. So instead of the Dataverse software concatenating a parent name, like Author, and child name, like Affiliation, to display Author Affiliation as a facet category, an installation could specify that the child field Affiliation could be displayed using any given string.

Is this true? I had a hard time following the status of this and related issues and PRs.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.

**Comment by pdurbin** [comment]
> Why not use the `>` symbol which suggests a logical hierarchical sequence and that is often used with breadcrumb navigation ? Would that work for all (a majority of maybe?) languages ?

The new Dataverse front end is also using ">". Here's a screenshot from https://beta.dataverse.org/spa/datasets?persistentId=doi:10.5072/FK2/BJ5KN4

![Screenshot 2024-10-23 at 4 10 52 PM](https://github.com/user-attachments/assets/fdf3d1b2-126a-4d1a-87d3-07ad5ad582ac)

If you want something other than a ">" here, please open a new issue at https://github.com/IQSS/dataverse-frontend/issues

**Comment by pdurbin** [comment]
Also, as @jggautier pointed out, there is a related conversation going on at https://dataverse.zulipchat.com/#narrow/channel/378866-troubleshooting/topic/order.20of.20words.20in.20translations/near/478471602
