### ISSUE TITLE
When a dataset is moved from one dataverse to another, the dataset should take on the new dataverse workflow

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#6575]
a dataset was moved from a journal to harvard root after it had been submitted for review.
in root, the dataset workflow  setting did not change from that of the journal-"submit for review" was not removed

see attached screen shot

<img width="1911" alt="Screen Shot 2020-01-24 at 12 56 46 PM" src="https://user-images.githubusercontent.com/8322346/73095999-ce548300-3eb1-11ea-9bb6-9044e12bd2a7.png">

*i requested permission from journal to move published dataset back to their journal dataverse as should be the case

**Comment by djbrooke** [comment]
Thanks @sbarbosadataverse for reporting. Before we work on this, we'll need to map what status is expected when a move occurs under different conditions.

**Comment by sbarbosadataverse** [comment]
I deleted the dataset because the author needed to recreate it in the journal dataverse for publishing. just an FYI

**Comment by cmbz** [comment]
2024/05/06
- The logic of what aspects of previous workflow state are preserved or cleared after the move will need to be defined.

**Comment by pdurbin** [comment]
We have a SubmitDatasetForReviewCommand. Would a WithdrawDatasetFromReviewCommand be appropriate? That is, put it back in the state it was in before it was submitted for review. I think removing the lock (`DatasetLock.Reason.InReview`) is the main thing. I'm not sure if we'd want to send notifications or not. "This dataset has been withdrawn from review." 🤔 

Anyway, a new command could be useful in cases that don't involve moving datasets.

We should discuss the plan and scope before we size this.

**Comment by cmbz** [comment]
Sized at 10, needs a bit more investigation. Resize as needed.

**Comment by sekmiller** [comment]
The logic added here is based on the permissions granted to the default contributor of the target Dataverse. If a dataset that is locked for review is moved to a collection where the default contributor may publish datasets, then the lock is removed.
