### ISSUE TITLE
Private URL: If User otherwise has access to the dataset, do not log them out

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#6576]
When a user accesses a dataset using the Private URL, they are logged in with a read-only account that's tied to the dataset. This account is created specifically for Private URL purposes. 

This usually works fine, but it can create a confusing experience when someone is already logged in under their own account that already has access to the dataset, as they visit the Private URL and are then logged out and logged back in under the read-only account.  This means that someone could visit the Private URL expecting to be able to publish and such and would not have those abilities.

A suggestion was to make this work like Google Docs where if you are the owner of a document that's marked as "Anyone with the Link can view but not edit," you're not logged out and given the lower level of access, but instead keep your greater level of access. 

In Dataverse the implementation of this could mean adding a check to see if a user is logged in when a private URL is clicked, and if so, a check is made against the dataset that's associated with that Private URL. If the user already has access to that unpublished dataset, they would remain logged into their account instead of being logged out and logged in to the Private URL account.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.

**Comment by pdurbin** [comment]
This issue was rediscovered and is now being tracked here:

- #11076
