### ISSUE TITLE
Contact - Feedback, Email Dataverse/Dataset Contact

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#658]
---

Author Name: **Elizabeth Quigley** (@eaquigley)
Original Redmine Issue: 4108, https://redmine.hmdc.harvard.edu/issues/4108
Original Date: 2014-06-17
Original Assignee: Elizabeth Quigley

---

We need to design and determine what will go in the forms that pop up when a user clicks on the dataverse or dataset contact button.

Gary had suggested within the form having a way for the user to pick if the question is a support question (so send to Dataverse development team) or a data issue (so send to user or data owner) to decide who to send the email to.

**Comment by eaquigley** [comment]
@sekmiller I'm adding this to Beta 11. If you get a chance today, could you take a look at this? Thanks!

**Comment by eaquigley** [comment]
@rtreacy could you please change the subject line to be a blank input field instead of the drop down menu. thanks!

**Comment by kcondon** [comment]
@eaquigley I have some questions on this, most likely are bugs:
1. Subject is filled in automatically by default, should it be?:
Dataverse 4.0 Beta build 896 Feedback
2. No required asterisks as you requested.
3. Still throws exception when attempt to send email where either subject or message are missing.

**Comment by eaquigley** [comment]
1. That's fine with me.
2. Definitely still need the required asterisks. 
3. Is there another ticket created for that?

@kcondon

**Comment by kcondon** [comment]
1. Great
2. OK, maybe pass to Mike? to add them?
3. Yes
________________________________

**Comment by mheppler** [comment]
Sure. I'll take it. @kcondon @eaquigley

**Comment by ekraffmiller** [comment]
@eaquigley @kcondon @mheppler FYI, I'm working on this form now, will pass to Mike when I'm done

**Comment by mheppler** [comment]
@ekraffmiller -- thanks!

**Comment by eaquigley** [comment]
#1502 is the ticket @ekraffmiller has been working on. i think we might have a duplicate ticket situation. ah!

**Comment by mheppler** [comment]
I am giving this ancient, high-level ticket back to QA to close, as there are other more specific being developed still #1530 #1502 #1327.

If there is something that still needs to be done on THIS ticket, I suggest it gets add to one of the existing tickets.

**Comment by eaquigley** [comment]
Still not seeing required asterisks for subject, message, and the math problem at the bottom. Passing back to @mheppler

**Comment by mheppler** [comment]
Added required asterisks to field labels, and other UI clean up on the Feedback/Dataverse/Dataset contact form.

**Comment by eaquigley** [comment]
@mheppler I'm only seeing the required asterisk for Subject appearing on the Feedback form not the contact dataverse or dataset forms.

**Comment by mheppler** [comment]
Fixed render logic on required asterisk for the Subject label on Feedback/Contact form.

**Comment by eaquigley** [comment]
All asterisks appearing. closing ticket.
