### ISSUE TITLE
Clarify user rights in admin's "Edit Access" panel

### ISSUE THREAD

**Issue by BPeuch** [IQSS/dataverse#6583]
Version: 4.18.1

Hello everybody,
Something is unclear to me in the Dataverse > Permissions > Edit Access panel in which administrators can specify who can by default add to a Dataverse and the role that is automatically assigned to a user for a dataset they added. I mean this section:

![DV_admin_edit_access](https://user-images.githubusercontent.com/15209224/73245111-c47d9900-41ab-11ea-9d35-6feb5368aa9f.png)

I highlighted "File Restrictions (Files Access + Use)" because, as it stands, it suggests that only Curator users may restrict or unrestrict access to the files in the datasets they deposit. However, I have just tested this with a user account who was given only the Contributor role by default, and it is still possible for me to restrict or unrestrict access to files in my own datasets.

Maybe "File Restrictions (Files Access + Use)" designates something else than what I'm thinking about?

**Comment by pdurbin** [comment]
@BPeuch yes, I agree this is confusing. You're right, a Contributor can restrict files. The most important action that a Contributor cannot take is to publish the dataset. Instead, they have to click "Submit for review and wait for a Curator to publish the dataset.

**Comment by BPeuch** [comment]
Thanks for your input, @pdurbin. I agree: the right to publish is the most important distinguishing feature, and we talked about that just yesterday at the State Archives because of the related policy implications: do we want to give depositors full rights and let anyone* post virtually anything in Dataverse, or should we not have a validation stage of some sort, but this implies having someone check the datasets before publication, which entails human costs and what not.

(* Not so much anyone in our case as a select list of individuals because we'll be using Dataverse's Shibboleth feature to restrict access to local identity providers.)

So in the end I only meant to bring up this small semantic ambiguity. But the distinction between contributor and curator remains very valid and useful.

**Comment by pdurbin** [comment]
@BPeuch 

Here's how that line reads now:

`dataverse.permissions.Q2.answer.editor.description=- Edit metadata, upload files, and edit files, edit Terms, Guestbook, Submit datasets for review`

From https://github.com/IQSS/dataverse/blob/v5.12/src/main/java/propertyFiles/Bundle.properties#L1140

How would you like it to read instead? Would you like to make a pull request?

**Comment by BPeuch** [comment]
@pdurbin I think it's perfect now! Thanks a lot for the ping and for the change :)
