### ISSUE TITLE
validate API endpoint doesn't enforce DataCite requirements

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#6586]
Possibly related to #6380 though the Dataverse instance in question is still on 4.16. It is possible to create a dataset with metadata which passes validation via endpoint:
```
$ curl -H "X-Dataverse-key:" "http://localhost:8080/api/admin/validate/dataset/556?variables=true"
{"status":"OK","data":{"message":"valid"}}
```
but lacks certain fields required by DataCite:

`Response code: 422, [facet 'minLength'] The value has a length of '0'; this underruns the allowed minimum length of '1'. at line 31, column 0]]`

In our case this turned out to be a producer URL not being accompanied by a producer name, but with only the above to go on from DataCite, this took a while to find.

If catching such a condition is outside the scope of the validate endpoint and/or I'm comparing tangerines to clementines, feel free to close this issue.

**Comment by jggautier** [comment]
Hi Don. Your mention of producer URL makes me think you're referring to the Producer Name and URL fields in the Citation metadata block:

![Screen Shot 2020-01-29 at 2 25 20 PM](https://user-images.githubusercontent.com/18374574/73390032-51efe480-42a3-11ea-9ea5-dbeb9a9927bb.png)

Is that right?

**Comment by pdurbin** [comment]
@jggautier sounds right but let's let @donsizemore confirm. 😄 

@donsizemore I assume that `minLength` error is on publish?

**Comment by donsizemore** [comment]
@jggautier @pdurbin correct on both points.

**Comment by jggautier** [comment]
Thanks. This sounds like [the problem described in this GitHub issue](https://github.com/IQSS/dataverse.harvard.edu/issues/4#issuecomment-494878248). It still happens in Dataverse 4.19, but I'm guessing it hasn't come up often because people haven't been trying to publish datasets where the Producer URL field has a value but the Producer Name field does not.

**Comment by qqmyers** [comment]
FWIW - I think I played around at one point with the idea of being able to make a metadatablock child entry 'required' with the parent 'optional', so one could potentially require a producer name and url if one is entered (if I understand the structure of producer). If that's useful, let me know. (I think I had code - it may even be in qdr's fork.)

**Comment by landreev** [comment]
I agree it would be useful to be able to validate for things like this - but should it be a different API? This "admin/validate/dataset" API was only meant for database constraints; all it does it tries to instantiate entities and checks for ConstraintViolationExceptions.

**Comment by djbrooke** [comment]
Closing in favor of #7551
