### ISSUE TITLE
Add Renku to list of integrations

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#6592]
At https://twitter.com/pmarrai/status/1222813558758572032 you can see that I just mentioned Renku in a talk...

<img width="585" alt="Screen Shot 2020-01-30 at 10 17 25 AM" src="https://user-images.githubusercontent.com/21006/73440737-c41b0480-4349-11ea-9978-bbca7c245bb2.png">

... but Renku isn't on the list at http://guides.dataverse.org/en/4.19/admin/integrations.html

We should update https://github.com/IQSS/dataverse/blob/develop/doc/sphinx-guides/source/admin/integrations.rst to add Renku. Pull requests welcome!

**Comment by rokroskar** [comment]
Renku is not on the slide either :P

**Comment by pdurbin** [comment]
@rokroskar whoops, you're right about that slide. I was thinking about three slides later:

<img width="645" alt="Screen Shot 2020-01-31 at 9 51 16 PM" src="https://user-images.githubusercontent.com/21006/73573586-ffb1ed80-4473-11ea-8004-47f8d8811de0.png">


Thanks for the pull request!
