### ISSUE TITLE
Clarification regarding supported Solr version(s)

### ISSUE THREAD

**Issue by bricas** [IQSS/dataverse#6599]
Although solr 7.3.1  is used in the install example (http://guides.dataverse.org/en/4.19/installation/prerequisites.html#solr), there is no clarity as to exactly what versions are supported/tested.

Can i use the latest 7.x release, since 7.3.1 is now quite old?

What about the latest stable (8.x)?

Thanks in advance!

**Comment by scolapasta** [comment]
Hi @bricas 

solr 7.3.1 is the supported (and tested) version of Solr for Dataverse. We haven't tested with any newer versions. That said, if you or anyone in the community has the bandwidth to do the testing, we'd be happy to review any PR for needed changes.

**Comment by bricas** [comment]
Thanks @scolapasta. We'll probably install the latest 7.x release soon, and I'll report back.

I think adding a simple line to the documentation about the tested version would be helpful also.

**Comment by poikilotherm** [comment]
This is also interesting for IQSS/dataverse-kubernetes, as the Solr project only supports more recent versions of Solr in their [upstream container images](https://hub.docker.com/_/solr) (>7.5).

**Comment by poikilotherm** [comment]
I gave this a quick shot, as it was basically just changing the image tag for me. It worked pretty straight forward so far. Dataverse creation and search for a title works. No error or warning messages about the config files.

@kcondon what would you like to see tested for a PR? API test suite passing? Anything else?

**Comment by djbrooke** [comment]
Thanks @poikilotherm and thanks @kcondon for the heads up.

@scolapasta what do you think? If the automated tests are passing we could add a note like we did at http://guides.dataverse.org/en/latest/installation/config.html#amazon-s3-storage-or-compatible that we have tested a specific version and that others may be successfully used, but I feel like Solr is pretty core to the application and we may run into trouble trying to troubleshoot installations on different versions.

**Comment by scolapasta** [comment]
I think if we we've tested, it's likely fine to support different minor versions. (with the added caveat that as people run into issues that they upgrade to the latest supported - and we should run on the latest supported in demo, at least)

**Comment by poikilotherm** [comment]
@scolapasta you wanna me craft a PR for this? Installer and docs to be changed. Would talk to @donsizemore about dataverse-ansible, too. I estimate this to "small" and volunteer.

**Comment by poikilotherm** [comment]
When moving to Solr 8 down the road, we should switch to using the service installer script. See https://lucene.apache.org/solr/guide/8_0/taking-solr-to-production.html#service-installation-script

This is already present in older releases, but as this is a breaking change, we should do this with care.

**Comment by poikilotherm** [comment]
I took the liberty to start a PR as suggested by @pdurbin on IRC. Please see #6631

**Comment by pdurbin** [comment]
@poikilotherm thanks for the pull request! I just created #6633 to be about the Solr upgrade within 7.x.

We want to treat this "clarify supported Solr version" issue as a separate small chunk. I assume this would be a doc change. Suggestions are welcome!

**Comment by poikilotherm** [comment]
Is this issue still an issue? @bricas does #6633 and its PR #6631 clarify the situation for you?

**Comment by bricas** [comment]
Having followed this issue, I'm clear on what is supported and tested. The linked PR doesn't add any language to the docs about it though.

I've already updated my local install's solr to 7.7.2. :+1:

**Comment by pdurbin** [comment]
@bricas what do you think the docs should say? 😄 I'm open to ideas. 😄

**Comment by bricas** [comment]
Before the "Installing Solr" section, i would probably add a "Versions" or "Supported Versions" heading.

> Dataverse has been tested with Solr version 7.7.2. Future releases in the 7.x series are likely to be compatible; however, this cannot be confirmed until they are officially tested. Major releases above 7.x (eg. 8.x) are not supported.

Something along those lines would be helpful.

**Comment by pdurbin** [comment]
@bricas sounds good to me! Do you want to make a pull request? Here's the part of the file to edit: https://github.com/IQSS/dataverse/blob/develop/doc/sphinx-guides/source/installation/prerequisites.rst#installing-solr
