### ISSUE TITLE
Write Dataset Documentation (User Guide)

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#66]
---

Author Name: **Elizabeth Quigley** (@eaquigley)
Original Redmine Issue: 3474, https://redmine.hmdc.harvard.edu/issues/3474
Original Date: 2014-02-03
Original Assignee: Elda Sotiri

---

User guide for dataset section

**Comment by posixeleni** [comment]
Per @mcrosas
> Just a reminder that before 4.0 release, we should improve the Add Data documentation page:
 In Add Dataset page: What's the best way of sharing data? - description, documentation, metadata in files, commonly used formats, CC0 (unless restrictions or agreements apply), etc.

**Comment by posixeleni** [comment]
Also need to add more documentation on Dataset File features: Download files/citations, Explore files, etc.

**Comment by eaquigley** [comment]
done. closing ticket.
