### ISSUE TITLE
Label for "Data Related to Me" tab

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#660]
---

Author Name: **Elizabeth Quigley** (@eaquigley)
Original Redmine Issue: 4110, https://redmine.hmdc.harvard.edu/issues/4110
Original Date: 2014-06-17
Original Assignee: Elizabeth Quigley

---

This tab needs to be renamed so it makes more sense. Suggestions: Data Owned by Me or Data Shared with Me

**Comment by bencomp** [comment]
Neither covers exactly what I see on that tab, but I can't think of anything better.

What should a superuser see on this tab, by the way? Everything, or just the object she has an explicit role in?

**Comment by eaquigley** [comment]
Reads My Unpublished Data now based off of indexing change where this tab no longer shows published data. Closing this ticket. Will reopen if something changes.
