### ISSUE TITLE
Dataset file count in search results from API

### ISSUE THREAD

**Issue by tainguyenbui** [IQSS/dataverse#6601]
Hi!

We have been recently working with search results and also retrieving dataset information. 

We are wondering whether it would be possible to get the file count for a dataset as part of the information being returned in each dataset information search result item.

We would find it very handy for our application

**Why do we need it?**
When showing dataset information in our application, we want to display the number of files that a dataset has as part of the search result. Currently, the only way to do this operation is by retrieving dataset information and calculating the files' array length.

**Why would this be useful for other people?**
Taking into consideration that people might be performing searches looking for dataset files, it would be handy to know whether a dataset contains files.

Thanks! 🚀

**Comment by mheppler** [comment]
Related to:

- _Dataset Size API #6524_
- _Display the total size of a dataset on the dataset page #6400_
- _indicate "size" of a dataverse in card when browsing #4704_

**Comment by djbrooke** [comment]
Moving to ready as this seems clear enough.

**Comment by pdurbin** [comment]
Makes sense. I think we should take the performance hit on the indexing side. That is, store the database id of each file in an array for the dataset version in question. That way, we don't have to go to the database at search/browse time.

**Comment by djbrooke** [comment]
- We should just a number here instead of a number and the files

**Comment by tainguyenbui** [comment]
completely agree with you @djbrooke, it will be an overkill otherwise and could increase the payload dramatically

**Comment by pdurbin** [comment]
In non-overkill style, I just made a pull request #6623 which is small and doesn't involve reindexing or any Solr changes.
