### ISSUE TITLE
The metadata tab of a dataset does not display the translated values

### ISSUE THREAD

**Issue by bappun** [IQSS/dataverse#6607]
In the metadata tab of a dataset the fields labels are translated but their values are not. However these values are translated in the edit form as well as in the facets of the search page.

For example I get "Other" instead of "Autre" in the french version:
![image](https://user-images.githubusercontent.com/24225471/73753978-e48cf980-4763-11ea-9e85-7e2205ca7c92.png)

But I get this in the facets:
![image](https://user-images.githubusercontent.com/24225471/73754397-a5ab7380-4764-11ea-89b2-5b4df89b0dfc.png)

And this in the edit form:
![image](https://user-images.githubusercontent.com/24225471/73754490-c4aa0580-4764-11ea-8300-b1fc20cbae14.png)

I noticed the issue for the fields that have controlled vocabulary but I am not sure if it affects the default fields.

**Comment by pdurbin** [comment]
@bappun nice meeting you on Friday! Thanks for opening this issue and thanks for the screenshots. 😄  Can you please us know which version of Dataverse you're using?

@JayanthyChengan do you have any insight into this? Is this behavior expected?

**Comment by bappun** [comment]
@pdurbin It was nice meeting you too!

Oh sorry I forgot. I tried on the **v. 4.19 build 331-affbf4f**

**Comment by bappun** [comment]
Hi! are there any updates on this issue?

**Comment by pdurbin** [comment]
@bappun no, we haven't looked at it.

The best ways to reach the people who work on internationalization are probably the following:

- open an issue at https://github.com/GlobalDataverseCommunityConsortium/dataverse-language-packs (linking back to this issue, please)
- send an email to https://groups.google.com/forum/#!forum/dataverse-internationalization-wg

You could try both. 😄
