### ISSUE TITLE
Page pops up to error message or first field with error message

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#661]
---

Author Name: **Elizabeth Quigley** (@eaquigley)
Original Redmine Issue: 4111, https://redmine.hmdc.harvard.edu/issues/4111
Original Date: 2014-06-17
Original Assignee: Gustavo Durand

---

When there is an error, the page doesn’t move to the top or inline with the field where the error has occurred, it is staying down at the bottom so you can’t tell why it didn’t save. Need to fix this so it at the very least, pops up to the top to show error messages

**Comment by eaquigley** [comment]
Tried this and it is still happening. @scolapasta who should I assign this to for them to look at. This is quite bad UX and is a usability issue so it does need to be fixed prior to 4.0 launching.

**Comment by esotiri** [comment]
verified @eaquigley comment and sending back to dev.

**Comment by eaquigley** [comment]
Assigning to @sekmiller to take a look at if he has a chance.

**Comment by eaquigley** [comment]
At the very least, this needs to pop up to the top of the page and not stay next to the save and cancel buttons when there is an error

**Comment by sekmiller** [comment]
Pops to top of page and displays general validation message and "See below for details."

**Comment by kcondon** [comment]
Pops to top of page with generic message:  Data input validation error. See below for details.   @eaquigley is this ok? Closing unless hear otherwise.

**Comment by eaquigley** [comment]
@kcondon not okay. I'd like it to be the same message that appears on the Dataverse page:

Validation Error – Required fields were missed or there was a validation error. Please scroll down to see details.

Also, I noticed this isn't appearing on the Create Dataset page at all.

**Comment by sekmiller** [comment]
Don't see this happening(lack of a validation message on create.) @eaquigley @kcondon - Is there anything I need to do besides click add and save?

**Comment by eaquigley** [comment]
@sekmiller it could be happening to me because of how the 500 error is appearing each and every time i click a button on dvn-build. please pass this back to me and i will try again next week

**Comment by eaquigley** [comment]
works for me now. passing this ticket to QA to close.

**Comment by eaquigley** [comment]
Closing this ticket because 11 days ago I passed it to QA to close. Also, I tried it again and it is popping up to the top of the page.
