### ISSUE TITLE
api/datasets/{id}/modifyRegistrationMetadata always returns OK

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#6611]
Just noticed during an issue at DataCite that this API call doesn't report any errors. An error (e.g. DataCite not being able to find the DOI that one is trying to modify) produces useful log messages, but the HTTP response is still OK with no indication that things went wrong. Just looks like there is no code to handle the error (versus a bug in the logic).

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
