### ISSUE TITLE
Add biblatex export for dataset citation

### ISSUE THREAD

**Issue by adam3smith** [IQSS/dataverse#6613]
Following up on Community Group exchange here: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/dataverse-community/dVE9HdSIgM8/1bZjWKgrEwAJ

A user had reported the following error:
> "On the dataset page, there is a button called "Cite Dataset". When choosing BibTeX, a reference is produced of the type @ data. But LaTex is not able to process this reference. It seems that LaTeX does not support @ data.  

As described on the google group, I would suggest taking one of the following approaches:

There are several approaches here:
1. Just support bibtex with a pared down, standardized @misc format. This means that citations "work" but is quite unsatisfactory because these aren't data citations. You're effectively going to end up citing datasets as webpages
2. You support both bibtex and biblatex. That's the route e.g. Zotero has taken. Biblatex is actively maintained and updated and does have item types for data and software. Unfortunately, it's much less commonly used, still, than bibtex, given the wide availability of (very hard to code) bibtex citation styles. Note that this requires some other changes, too. Happy to help with those.
3. Go all in with biblatex. That's the route that Zenodo very recently has decided to take, and they now use @dataset and @software : https://github.com/zenodo/zenodo/issues/1428 but note the not-very-old comment on that same issue that reported lots of user complaints about those item types https://github.com/zenodo/zenodo/issues/1428#issuecomment-398729076 -- it's unclear from the discussion on the issue that they every actually came to grips with the fact that their solution is going to cause a lot of things/styles to break. But as Katrin Leinweber makes clear in that thread, this is also a political move, trying to get people to adopt styles/systems that actually support proper data (and software) citation, which is in line with dataverse's mission.

(The @ data item type that dataverse currently uses used to be the best option based on its usage in the biblatex-apa style (APA was one the first major style guides to have an explicit data citation format), but now that dataset is in biblatex -- which is very recent: it's included in version 3.14 which came out in December 2019) it should definitely be replaced.)

**Comment by djbrooke** [comment]
Thanks @adam3smith for adding the issue and @philippconzett for starting the conversation. 

As I mentioned in the issue I think we'd want to implement option 2, where we'd add biblatex as an additional citation type and support both for some period of time.

**Comment by bellerophons-pegasus** [comment]
I made some suggestions for the data model of @dataset for biblatex (https://github.com/plk/biblatex/issues/1103). 

As dataverse is also providing citation suggestions for parts of datasets, maybe someone is interested to join the discussion there?

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
