### ISSUE TITLE
UNF & DOI URL display order in citation

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#662]
---

Author Name: **Elizabeth Quigley** (@eaquigley)
Original Redmine Issue: 4112, https://redmine.hmdc.harvard.edu/issues/4112
Original Date: 2014-06-17
Original Assignee: Eleni Castro

---

Gary mentioned that the DOI URL and UNF sometimes get combined together by a publisher. He suggested us looking into ways to separate them better.

Examples of suggestions:
* UNF first, URL
* URL, this is a UNF [  ]

**Comment by eaquigley** [comment]
For 4.0, why don't we have it displayed as [UNF] and we can evaluate how that goes after it is in.

**Comment by sekmiller** [comment]
Added brackets around the UNF for display purposes.

**Comment by kcondon** [comment]
Brackets in place. Closing.
