### ISSUE TITLE
Geolite2 database for MDC no longer available at URL /under completely open license

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#6629]
As of Dec 31rst, 2019, it looks like MaxMind, in order to comply with privacy regulations, is adding some conditions to the use of the Geolite2 database used by counter-processor. It is still free, but downloading requires creation of an account at MaxMind and agreeing to a EULA that requires one to keep up to date with the database releases. (The primary concern appears to be that individuals can opt-out under privacy laws and MaxMind needs a way to comply with that for products it has sold (for free). See
https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/ .

The most basic consequence is that the database is no longer available at the URL specified in http://guides.dataverse.org/en/latest/installation/prerequisites.html and some update is needed.

More broadly, using the database now involves agreeing to update to the latest version within 30 days of being notified. At a minimum the docs should probably note/discuss that as part of the updated download instructions. 

It might also be worthwhile to raise this with the creator of counter-processor / MDC to see if there are ways to simplify/automate and/or whether there are alternatives and whether there are other aspects of counter-processor's functionality that are affected by privacy laws, whether location determination should be an option that can be turned off, etc.

**Comment by djbrooke** [comment]
Thanks @qqmyers for adding the issue on the Counterprocessor repo: 

https://github.com/CDLUC3/counter-processor/issues/16

**Comment by qqmyers** [comment]
FWIW: QDR has now gone through the agreement and set up their updatescript (which you then run as a cron job). It was fairly simple to set up, beyond having someone have to signup/agree/get the free key.

**Comment by j-n-c** [comment]
@qqmyers there are two typos on Your commit:

_... free but to use it one **M**ust sign~~ing~~ an agreement (EULA) with MaxMind..._

would you consider correcting these?

**Comment by pdurbin** [comment]
@j-n-c if you have time, please go ahead and create a new pull request to fix those typos.

**Comment by j-n-c** [comment]
@pdurbin since this issue is closed, should I create a new one? Or just reference it on the PR?

**Comment by pdurbin** [comment]
@j-n-c ideally, all pull requests close an issue but in this case, since it's just a small doc change, please feel free to simply create a pull request. Thanks!
