### ISSUE TITLE
APIs for File Services (other than Dropbox)

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#663]
---

Author Name: **Elizabeth Quigley** (@eaquigley)
Original Redmine Issue: 4113, https://redmine.hmdc.harvard.edu/issues/4113
Original Date: 2014-06-17
Original Assignee: Gustavo Durand

---

Look into other APIs for file services besides Dropbox

**Comment by kcondon** [comment]
This is somewhat duplicative of #1746. Closing.
