### ISSUE TITLE
lastlogintime - not updated for users when logged in via web

### ISSUE THREAD

**Issue by Venki18** [IQSS/dataverse#6630]
We were trying to use the authenticated users and list-user APIs to generate the list of all users in Dataverse. What I found is that the lastlogintime is not updated even after we login. I think this is a bug. 

Please see the details that I got when using the authenticated users API. (I have removed sensitive details from the following list).
  "id": 23,
  "identifier": "@venki",
  "displayName": "Kannadasan Venkatachalam",
  "emailLastConfirmed": "2017-07-18T09:58:00Z",
  "createdTime": "2017-07-18T09:58:00Z",
  "lastLoginTime": "2017-07-18T09:58:00Z",
  "lastApiUseTime": "2020-01-31T06:25:45Z",
  "authenticationProviderId": "shib"

This is my details and the lastLoginTime was updated in 2017 but the lastApiUseTime was updated on 31st Jan since I used the API.

NTU Dataverse is running on v4.16.

**Comment by pdurbin** [comment]
Hi @Venki18 nice to hear from you.

I just tried logging in as "dataverseAdmin" on a recent version of Dataverse (v. 4.18.1 build 6381-decode-fb4bd69 ) and "lastLoginTime" was updated to today's date (2020-02-10):

Here's the output from http://localhost:8080/api/admin/authenticatedUsers/dataverseAdmin

```
{
  "status": "OK",
  "data": {
    "id": 1,
    "identifier": "@dataverseAdmin",
    "displayName": "Dataverse Admin",
    "firstName": "Dataverse",
    "lastName": "Admin",
    "email": "dataverse@mailinator.com",
    "superuser": true,
    "affiliation": "Dataverse.org",
    "position": "Admin",
    "persistentUserId": "dataverseAdmin",
    "createdTime": "2019-11-01T14:29:44Z",
    "lastLoginTime": "2020-02-10T18:48:00Z",
    "lastApiUseTime": "2019-12-06T17:38:45Z",
    "authenticationProviderId": "builtin"
  }
}
```

Would you be able to test this bug on the latest release (4.19) or the "develop" branch (please let us know which commit)? In short, I'm having trouble reproducing it.

**Comment by Venki18** [comment]
Hi @pdurbin thank you for the reply. Nice to hear from you. 
May I know whether the last login time update only works for local logins? I am using shibboleth login. Does it work for other oauth logins?

**Comment by donsizemore** [comment]
@pdurbin https://dataverse-test.irss.unc.edu is only running 4.16 but I can reproduce the problem there.

**Comment by djbrooke** [comment]
@philippconzett if you wouldn't mind, for another data point, can you check what happens on dataverse.no? You're running 4.17 and I believe you have a similar setup to NTU in that there's a single option on https://dataverse.no/loginpage.xhtml. Thanks!

**Comment by philippconzett** [comment]
We are in the middle of upgrading to 4.19 (our demo site [](https://test.dataverse.no/) is already there), so I'm afraid we cannot help. Sorry!

**Comment by pdurbin** [comment]
This was also reported by @joe00z a few months ago:

- #8637

I'm going to close that new issue in favor of this older one.

**Comment by DS-INRA** [comment]
Putting this to higher priority as we would need this fixed to contribute on both :
- fixing API rights from Shibb groups (issue to be created after community discussion)
- https://github.com/IQSS/dataverse/issues/9631
