### ISSUE TITLE
Upgrade from Solr 7.3.1 to 7.7.2

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#6633]
We're using Solr 7.3.1 but Solr 7.7.2 is out. We should upgrade.

Here's the changelog: https://lucene.apache.org/solr/7_7_2/changes/Changes.html

**Comment by donsizemore** [comment]
[solr_7.7.2.zip](https://github.com/IQSS/dataverse/files/4194702/solr_7.7.2.zip)

**Comment by poikilotherm** [comment]
@donsizemore I don't get it... I don't see any critical things - what am I missing?

**Comment by donsizemore** [comment]
@poikilotherm I thought things looked good!

The only repeated SEVERE I see during the API test suite is

`java.lang.IllegalAccessException: Class edu.harvard.iq.dataverse.search.SearchServiceBean can not access a member of class edu.harvard.iq.dataverse.search.SearchFields with modifiers "private static transient"`

which showed up 654 times...

**Comment by poikilotherm** [comment]
So maybe @pdurbin accidentially hit the wrong emoji :rofl: 
Is this SEVERE thing also popping up with 7.3.1? It looks like a deeper code issue.

**Comment by poikilotherm** [comment]
I already created an issue to track the log messages, should I also create a fresh issue for those deprecation warnings from Solr? @pdurbin @kcondon

**Comment by pdurbin** [comment]
@poikilotherm assuming you're talking about the deprecation warnings you mentioned at https://github.com/IQSS/dataverse/issues/6599#issuecomment-581383566 , yes, a fresh focused "small chunk" issue would absolutlely be welcome.
