### ISSUE TITLE
Search - UI bug: Strange dataverse ID and duplicate selected facets displaying above results table

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#6641]
**What's wrong?:**

Strange selected facets are displayed above the results table on the dataverse pg, when using the filter facet links in the side bar.

**Use Case:**

When on a sub-dataverse (not root), then filtering for just files, and then selecting any additional facet, you end up with some strange dataverse ID (`subTreePaths: /####)`) and dataverse/dataset/file types (`Type: (files)`) displayed above the results table. Additionally, you get duplicate `Type: (files)` selections when you deselect the additional facets.

![Screen Shot 2020-02-12 at 9 59 11 AM](https://user-images.githubusercontent.com/687227/74360318-d312a580-4d92-11ea-959a-640a93a7ed4d.png)

**How to fix?**

Obviously we do not want to display the strange ID facet, but also I believe that displaying the `Type: (files)` is a bug, as it does not display until I have made an additional facet selection. If I only click the Files facets label, there is no selected facet displayed.

For example, the only selected facets displayed for this search URL (https://dataverse.harvard.edu/dataverse/the_review?q=&fq2=publicationDate%3A%222019%22&fq0=subtreePaths%3A%22%2F2867131%22&fq1=dvObjectType%3A%28datasets%29&types=datasets&sort=dateSort&order=) should be `Publication Year: 2019`.

**Comment by pdurbin** [comment]
@mheppler if you have a couple minutes, can you please confirm if you're seeing this bug on https://dev2.dataverse.org ? It's running fb4bd69 from a pre 4.19 release. I can't seem to replicate it there.

**Comment by mheppler** [comment]
@pdurbin confirming the bug is not on dev2, does that point to a db/index issue on Harvard Dataverse?

**Comment by pdurbin** [comment]
@mheppler no, I believe it still could be a code issue, perhaps a regression introduced in 4.19? Can you reproduce in on "develop"?

**Comment by mheppler** [comment]
I don't know about develop, as I don't currently have my environment up, but I can reproduce this on dvn-build, dataverse-internal, and demo. Hopefully that's enough to conclude we have a problem somewhere.
