### ISSUE TITLE
Documentation: Add json file type to endpoints that post json files as input.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#6645]
While testing the assign roles to datasets endpoint, the command was failing until the upload file type (-H "Content-Type: application/json")  was added:

curl -H X-Dataverse-key:xxxx-xxxx-xxxx-xxxx-xxxx -X POST http://localhost:8080/api/dataverses/4/assignments -H "Content-Type: application/json" --upload-file /tmp/curator_role.json

There are other places in the guides that post json files as input so we should consider adding this to the curl commands or at least confirm whether they are needed.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
