### ISSUE TITLE
SearchServiceBean using Reflection API should not log SEVERE errors

### ISSUE THREAD

**Issue by poikilotherm** [IQSS/dataverse#6647]
While working on #6633 we found a lot of error messages being logged in `server.log`:

```
java.lang.IllegalAccessException: Class edu.harvard.iq.dataverse.search.SearchServiceBean can not access a member of class edu.harvard.iq.dataverse.search.SearchFields with modifiers "private static transient"
[...]
at edu.harvard.iq.dataverse.search.SearchServiceBean.search(SearchServiceBean.java:684)
[...]
```

This points to 
https://github.com/IQSS/dataverse/blob/251a570d5d14a42977d4d8c2ed866ac9a4556d9b/src/main/java/edu/harvard/iq/dataverse/search/SearchServiceBean.java#L684

`SearchServiceBean` uses Java Reflection API to [get all fields from `SearchFields.java`](https://github.com/IQSS/dataverse/blob/251a570d5d14a42977d4d8c2ed866ac9a4556d9b/src/main/java/edu/harvard/iq/dataverse/search/SearchServiceBean.java#L348) and iterates over them (which is also having a TODO attached)

https://github.com/IQSS/dataverse/blob/251a570d5d14a42977d4d8c2ed866ac9a4556d9b/src/main/java/edu/harvard/iq/dataverse/search/SearchServiceBean.java#L675-L680

By some magic, there seems to be a private field found by Reflection API (although there is none present in [`SearchFields.java`](https://github.com/IQSS/dataverse/blob/251a570d5d14a42977d4d8c2ed866ac9a4556d9b/src/main/java/edu/harvard/iq/dataverse/search/SearchFields.java)). This causes an exception, which is logged as being SEVERE.

No functionality seems to be broken. This should be refactored.

**Comment by donsizemore** [comment]
@poikilotherm thanks for digging in to this. I was in the process of running the (lengthy) test suites to see if it occurred on current develop under 7.3.1.

**Comment by poikilotherm** [comment]
@donsizemore is this still a thing?

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
