### ISSUE TITLE
Quotes added to BibTeX output 

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#6658]
Some " are added to "title" field in the BibTeX export from https://doi.org/10.7910/DVN/TDOAPG. We'd expect only quotes or braces, not both:

`
@data{DVN/TDOAPG_2020,
author = {Messing, Solomon and DeGregorio, Christina and Hillenbrand, Bennett and King, Gary and Mahanti, Saurav and Mukerjee, Zagreb and Nayak, Chaya and Persily, Nate and State, Bogdan and Wilkins, Arjun},
publisher = {Harvard Dataverse},
title = "{Facebook Privacy-Protected Full URLs Data Set}",
year = {2020},
version = {V2},
doi = {10.7910/DVN/TDOAPG},
url = {https://doi.org/10.7910/DVN/TDOAPG}
}
`

**Comment by jggautier** [comment]
Looks like this wasn't the case around Dataverse version 4.11. See examples in issue https://github.com/IQSS/dataverse/issues/5424 and the BibTeX produced in [Portail Data INRAE](https://data.inra.fr/), which is running 4.10.1. Hopefully that's helpful for finding when it was introduced.

**Comment by mheppler** [comment]
Need to discuss potential fixes with @pameyer and @jggautier as these extra quotes are result of the changes in PR _**5424 convert quotes in bibtex exports #5476**_.

Specifically this commit 9547f34a7afbfb26812862b73a44c8dff426e88e that was billed as "support case sensitivity in bibtex title", for issue _In BibTex exports, convert quote characters so LaTex displays quotes #5424_.

**Comment by djbrooke** [comment]
Thanks @mheppler and @jggautier!

**Comment by jggautier** [comment]
Discussed with @mheppler, who thought the extra quotes might've been to added to preserve capitalization in dataset titles. [See the screenshot in this issue comment](https://github.com/IQSS/dataverse/issues/5424#issuecomment-449449655). So maybe this is an issue with different software, software versions, settings or style files interpreting the extra quotes differently? So far I've read that wrapping the title in curly braces should preserve the capitalization.

**Comment by mheppler** [comment]
@pameyer commented on Dec 21, 2018, on issue #5424

>For a visual illustration:
>
>1058-57b3b7e :
>![screenshot_20181221_122731](https://user-images.githubusercontent.com/10261853/50355295-3b158500-051c-11e9-9172-86fff8fd70d3.png)
>
>After bibtex changes:
>![screenshot_20181221_122743](https://user-images.githubusercontent.com/10261853/50355310-49fc3780-051c-11e9-84d7-371dfaeef8ee.png)

**Comment by mheppler** [comment]
Following the directions outlined in [Bibliography in LaTeX with Bibtex/Biblatex](https://www.latex-tutorial.com/tutorials/bibtex/), I created some `tex` and `bib` files locally and created a PDF using bibtex and pdflatex commands.

First, here is the tex file that I started with based on those directions.

```
\documentclass{article}

\begin{document}

Random citation \cite{DVN/0XXXXX_2020} embeddeed in text.

\bibliography{bib1}
\bibliographystyle{ieeetr}

\end{document}
```

Then I started a sample bibtex citation containing all the formatting weirdness I could think of.

```
@data{DVN/0XXXXX_2020,
author = {Example, Erica},
publisher = {Harvard Dataverse},
title = "{Replication Data for: @CamelCasé: ``Conseil international de la langue française''}",
year = {2020},
version = {V1},
doi = {10.7910/DVN/0XXXXX},
url = {https://doi.org/10.7910/DVN/0XXXXX}
}
```

That resulted in the following formatting in the PDF.

<img width="614" alt="Screen Shot 2020-02-24 at 2 31 17 PM" src="https://user-images.githubusercontent.com/687227/75184415-57114980-5712-11ea-8e9c-daec4b2953b0.png">

Then I tried removing the extra quotes from the bibtex citation.

```
@data{DVN/0XXXXX_2020,
author = {Example, Erica},
publisher = {Harvard Dataverse},
title = {Replication Data for: @CamelCasé: ``Conseil international de la langue française''},
year = {2020},
version = {V1},
doi = {10.7910/DVN/0XXXXX},
url = {https://doi.org/10.7910/DVN/0XXXXX}
}
```

Which resulted in lose of capitalization and "camel case" formatting in the PDF, and for some reason the quotes outside the title are still there.

<img width="617" alt="Screen Shot 2020-02-24 at 2 35 49 PM" src="https://user-images.githubusercontent.com/687227/75184812-fafaf500-5712-11ea-9779-0972139133b1.png">

Finally, I added double brackets to preserve the formatting.

```
@data{DVN/0XXXXX_2020,
author = {Example, Erica},
publisher = {Harvard Dataverse},
title = {{Replication Data for: @CamelCasé: ``Conseil international de la langue française''}},
year = {2020},
version = {V1},
doi = {10.7910/DVN/0XXXXX},
url = {https://doi.org/10.7910/DVN/0XXXXX}
}
```

That resulted in the formatting returning to the PDF, but still, I am seeing quotes outside of the title.

<img width="619" alt="Screen Shot 2020-02-24 at 2 41 05 PM" src="https://user-images.githubusercontent.com/687227/75185233-b58af780-5713-11ea-8d16-9f46905619ec.png">

I am curious if these extra quotes are result of the `bibliographystyle{ieeetr}`. Not sure as of yet, I'll need to investigate further. Just wanted to update this issue now that I was able to generate some PDF's using the bibtex citation.
