### ISSUE TITLE
Original files are not fully restored after certain ingest failures

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#6660]
`TL;DR: an occasional failed ingest still leaves the tab file in place of the original`

longer version: 

An example in production: 
the file in ESS2e03.3_F1.dta in the dataset `doi:10.7910/DVN/PTIN2E`. It failed ingest with the following error report message: `Ingest succeeded, but failed to save the ingested tabular data in the database: Transaction aborted`
This means just that, that Dataverse was able to parse and generate everything - but for whatever reason failed to execute the final database save. 
The file is correctly showing as an uningested Stata file, with all the correct metadata. However the file on S3 was already replaced by the generated tab-delimited version; and we failed to reverse it after the database transaction got reverted.

**The good news is that this is easily recoverable** - by just replacing the file with the .orig file. But we should prevent this from happening in the first place. 

Wasn't this specifically addressed in #3768 3 years ago, you ask? Yes, doh. I suspect this is something S3-specific; though not clear why it started happening now. (and we'll need to test if this can be reproduced with the files on a regular filesystem). 

Regardless, this needs to be fixed.

**Comment by djbrooke** [comment]
- This is likely some exception not being properly caught

**Comment by landreev** [comment]
OK, I think I can make a PR for this fairly quickly.
