### ISSUE TITLE
Import a Dataset – Data do not transfer (while metadata do)

### ISSUE THREAD

**Issue by BPeuch** [IQSS/dataverse#6661]
Version: 4.18.1 and 4.19

Hello everybody,

Our Dataverse installation is unable to import a dataset's files with the [Import a dataset into a Dataverse](http://guides.dataverse.org/en/4.19/api/native-api.html#import-a-dataset-into-a-dataverse) API feature.

The metadata successfully transfer from one Dataverse to ours (although only with JSON, not with DDI, as noted in #5467) but clicking on the data files or attempting to download them always fails. Earlier it would bring us to a short JSON webpage with a 404 "Not found" error. Now for some reason we have yet to work out, it gives us a 500 "Internal server error."

You can see it for yourself if you try to access the data here: [https://dataverse.arch.be/dataset.xhtml?persistentId=doi:10.18419/darus-444](https://dataverse.arch.be/dataset.xhtml?persistentId=doi:10.18419/darus-444).

(We encounter the exact same issue with a local v 4.19 Dataverse installation.)

**Comment by djbrooke** [comment]
Hey @BPeuch, did you see this note in the docs? 

> Before calling the API, make sure the data files referenced by the POSTed JSON are placed in the dataset directory with filenames matching their specified storage identifiers. In installations using POSIX storage, these files must be made readable by GlassFish.

Does everything look as expected in terms of storage identifiers?

**Comment by BPeuch** [comment]
Thanks for your reply, @djbrooke. You were right: the problem had to do with the files. I think we got confused because, seeing that the feature is called [Import a dataset into a Dataverse](http://guides.dataverse.org/en/4.19/api/native-api.html#import-a-dataset-into-a-dataverse), we must have assumed that the data would transfer automatically, when in fact only the metadata do.

Manually renaming each file with its corresponding storage identifier proved to be rather toilsome. Do you know if this step of the process was automated to some extent or if something's under consideration in this area?

I take it that the philosophy behind this API feature is that it was devised for ad-hoc, isolated cases (e.g. one dataset must absolutely be deposited in a Dataverse but it has already received a DOI from another source) whereas larger imports of datasets should be done through an OAI-PMH harvesting server. Does this sound right, @djbrooke?

**Comment by djbrooke** [comment]
Hey @BPeuch, there has been some consideration for a better migration path into Dataverse. Most of these efforts have been by the community. @4tikhonov or @skasberger may have some more information about work to automate this, in PyDataverse or otherwise. I'd also suggest asking on the Google Group. 

Since you mentioned OAI-PMH, I just want to make sure about your use case. Do you want to move metadata and files from your current repository to the new Dataverse installation, or do you want the files to remain in the old repository while the metadata is discoverable in the Dataverse installation?

**Comment by pdurbin** [comment]
I agree with @djbrooke about checking with @4tikhonov 

Just today he was tweeting about migrating 50,000 datasets into Dataverse: https://twitter.com/4tykhonov/status/1232284931595874304

![Screen Shot 2020-02-25 at 4 25 18 PM](https://user-images.githubusercontent.com/21006/75289037-7334e980-57eb-11ea-8095-50bc4d685308.png)

I assume he's migrating the files as well! 😄

**Comment by 4tikhonov** [comment]
Yes, I did the migration of files without reingest, just moving them to the folders with specific DOIs and relying on the mime types recognized by EASY.

**Comment by BPeuch** [comment]
Thank you everybody for your comments!

Sorry for my delayed reaction, @djbrooke, and thank you — @pdurbin, too! — for the recommendations. I will definitely get in touch.

Our use case is: A Belgian university is going to deposit a fairly large amount of datasets (about 200) into their own Dataverse installation. It's nowhere near as big as the 50,000 datasets Slava imported, but of course the point is, we'd still rather do it by hand only once.

Because we at the State Archives are going to act as the national portal and repository, we want to import not only the metadata of those datasets (to give the data more online visibility/discoverability and to have a unique harvesting point for the crawler of the [CESSDA](https://www.cessda.eu/) [Data Catalogue](https://datacatalogue.cessda.eu/)) but also the data, thus creating both backup copies and extra access points for the data.

I'm guessing you were asking about our use case perhaps because one should be wary that OAI-PMH is for metadata import only. Indeed I was studying this possibility since it allows for batch import but I knew that data would have to transfer some other way.

That sounds fascinating, @4tikhonov! So this is a specific feature of DANS' Easy software? I'm guessing you wrote a list of select MIME types which the program will accept, and Easy automatically ingested all the files that had one of these types so you didn't have to rename all the files, as must be done with the [Import a dataset](http://guides.dataverse.org/en/4.19/api/native-api.html#import-a-dataset-into-a-dataverse) API feature?

**Comment by BPeuch** [comment]
As far as Dataverse is concerned and regarding what's in the user guide, this issue is solved, so I'll close this for the sake of tidiness.
