### ISSUE TITLE
Complete the JSON payload example for creating datasets

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#6671]
The [create-a-dataset-in-a-dataverse endpoint in the API guides](http://guides.dataverse.org/en/4.19/api/native-api.html#create-a-dataset-in-a-dataverse) includes an example JSON file, "dataset-create-new-all-default-fields.json", that should contain all of the fields in Dataverse's standard metadatablocks. I'd like to add to that JSON file two missing fields, Language and Topic Classification. They're included in this attached file:
[dataset-create-new-all-default-fields.json.txt](https://github.com/IQSS/dataverse/files/4242292/dataset-create-new-all-default-fields.json.txt)

**Comment by pdurbin** [comment]
@jggautier nice! Please feel free to make a pull request!
