### ISSUE TITLE
Unable to resume a "Paused" workflow

### ISSUE THREAD

**Issue by vbernabe** [IQSS/dataverse#6672]
Bug Report: Unable to resume a "Paused" workflow
Dataverse version: 4.18.1
Glassfish: 4.1

We have a use case to "pause" the publishing of a Dataset for a curator/admin to check and approve before publish. I'm trying out the workflow based on the documentation (http://guides.dataverse.org/en/latest/developers/workflows.html)

Steps:
1. I set the default workflow for prepublish dataset
        curl -X POST -H "Content-Type: application/vnd.api+json" -H "X-Dataverse-key:$API_TOKEN"  -d @internal-pause-workflow.json  $SERVER/api/admin/workflows
    
2. I created a Dataset and click on publish - now it is showing "The dataset is locked until publication."
![image](https://user-images.githubusercontent.com/3328254/75126707-1efc0d80-56f6-11ea-9891-65dd75e8d5e3.png)

 3. I tried to resume the workflow but getting an error
![image](https://user-images.githubusercontent.com/3328254/75126735-3cc97280-56f6-11ea-9323-be91a33d2931.png)

**Comment by pdurbin** [comment]
@vbernabe I don't know a ton about the workflow feature apart from what's written at http://guides.dataverse.org/en/4.19/developers/workflows.html

Have you considered using the "Submit for Review" (then "Return to Author" or "Publish") feature? It's documented at http://guides.dataverse.org/en/4.19/user/dataset-management.html#submit-for-review

Here's a screenshot:

![Screen Shot 2020-02-25 at 4 55 23 PM](https://user-images.githubusercontent.com/21006/75291135-a4171d80-57ef-11ea-8e23-118cce558b74.png)

**Comment by vbernabe** [comment]
@pdurbin our users are allowed to created their own Dataverse and add their Dataset under it. So these users will own the Dataverse hence we are not able to set their role as Dataset Contributor only.

If the workflow pause on publish and resume is not working, is there a way for an Admin role to be notified when a Dataset is created? This way at least we can get the notification for a new Dataset and keep tabs on the newly created Datasets. Right now a notification is only send to the creator of Dataset.

**Comment by pdurbin** [comment]
> our users are allowed to created their own Dataverse and add their Dataset under it. So these users will own the Dataverse hence we are not able to set their role as Dataset Contributor only.

My first thought was, "Wait, can't you configure permissions on a dataverse such that users can create a dataverse under it but not publish datasets within it?" I was thinking about radio button for Contributor vs Curator in this dialog:

<img width="2103" alt="Screen Shot 2020-02-27 at 4 36 11 AM" src="https://user-images.githubusercontent.com/21006/75431561-ff91fa00-591a-11ea-9ec2-37f95298bd8f.png">

Re-reading `:InheritParentRoleAssignments` at http://guides.dataverse.org/en/4.19/installation/config.html#inheritparentroleassignments just now I don't **think** that will help you either. @qqmyers might have some thoughts on this (and he has done a lot with workflows).

I also feel like @shlake might have some ideas with this whole situation. I know she's thought a lot about which groups she allows to create dataverses, at least. I think she was datasets from the her law school to go through the "Submit for Review" process or something. So she doesn't allow them to create their own dataverses? This was years ago and I probably have the details wrong. 😄 

> is there a way for an Admin role to be notified when a Dataset is created? This way at least we can get the notification for a new Dataset and keep tabs on the newly created Datasets. Right now a notification is only send to the creator of Dataset.

I'm not sure. Would you be able to create a new issue for this question?

**Comment by qqmyers** [comment]
@vbernabe It's possible that a bug has been introduced over the last couple of years, and I can check on that. The error log you sent above shows the LoggingWorkflowStep running but I don't see an indication that the pause step runs.  (The pause step is what registers the invocationid so it can be found when you send it back via http.) Can you share the internal-pause-workflow.json you've used? Is it the same as in /scripts/api/data/workflows?

**Comment by shlake** [comment]
Info on UVa's set up. On UVa's LibraData - Dataverse, Users can only create datasets. Superuser created one dataverse (Law School) with 2 others set as "admin". These two admins get the submission requests. Since they are admins, I assume they can create a dataverse under Law (which is OK in my scenario, as they are part of the Library and we want only "Library" staff to create dataverses). Here's the permissions for our Law Dataverse:

![Screen Shot 2020-02-27 at 12 24 08 PM](https://user-images.githubusercontent.com/3809325/75469827-a7301c00-595d-11ea-9526-e1968282b97e.png)

**Comment by vbernabe** [comment]
@qqmyers The pause workflow I'm using is from https://github.com/IQSS/dataverse/blob/develop/scripts/api/data/workflows/internal-pause-workflow.json

@shlake Thanks for the info. I guess it is a different use case on our side. Our users permission is "Anyone with a Dataverse account can add sub dataverses" so they can only add their dataset on their created Dataverse.

**Comment by qqmyers** [comment]
@vbernabe - sorry for the long delay. This just got buried. I think #7521 should fix what you were seeing. (In the future, if I've said I'll look into something and I don't reply, please feel free to ping me again.)
