### ISSUE TITLE
As a sysadmin, I would like an easy option to link to legal notice

### ISSUE THREAD

**Issue by poikilotherm** [IQSS/dataverse#6676]
At least in Germany, if not also within EU, you need to provide a link to a legal notice for any webservice being public. There are even laws/court decisions how many clicks are appropriate to reach the legal notice from any page of the service (it's 2).

As a Sysadmin, I would like to have a configuration option that allows me to set a URL to a legal notice, just like the privacy statement:

![image](https://user-images.githubusercontent.com/5468333/75244516-33123e80-57cc-11ea-95cf-40eb0344144e.png)

Currently, I added this as a dirty hack:
```
:FooterCopyright = " Forschungszentrum Jülich GmbH | <a href=\"https://fz-juelich.de/portal/EN/Service/LegalNotice/_node.html\" rel=\"noopener\" target=\"_blank\">Legal Notice</a>"
```

This is ugly, does not provide i18n support ("legal notice" is "Impressum" in german) and should be changed. A simple configuration option to provide a URL seems appropriate, rendered on demand. This is a very small, but UI related issue. As it relates to legal, it would be nice to solve this for 4.20.

**Comment by djbrooke** [comment]
I'll tap @TaniaSchlatter and @mheppler for more specific feedback, but my initial thought is that we make the footer freely customizable for these exact situations and that we shouldn't implement a "Legal Notice" specific feature. At Harvard, we have an "accessibility" link that we're required to apply on Harvard sites and I'm sure there are hundreds of situations where national/state/local/organization policies dictate something in the footer. I'm concerned that if we start supporting specific cases we'll be introducing a challenging maintenance problem, but I'm happy to hear other opinions.

**Comment by pdurbin** [comment]
> my initial thought is that we make the footer freely customizable for these exact situations

I had the same initial thought. 😄 

Hmm, but can the footer support multiple languages? I don't know.

**Comment by mheppler** [comment]
While I do not think there will be a rash of footer links required by the community, I do agree that such a small piece of UI real estate can only handle so many configuration settings. We already have config options for `:FooterCopyright` and `:ApplicationPrivacyPolicyUrl`, plus as Danny pointed, we used a customization hack to add an Accessibility link to the Harvard Dataverse footer.

I think it is probably wise to take this opportunity to design a more scalable solution for such a popular piece of customizable page content.

@pkiraly might have some feedback, as I found that he opened an issue (#4467) with hopes that documentation of footer and header customization could be expanded, to be made clearer that it does not overwrite the application's navbar and footer. This may be an opportunity to consider any installation customization issues he encountered when setting up his installation.

**Comment by mheppler** [comment]
@bappun commented on issue #6673 with a similar footer copyright workaround that I wanted to document here.

> @pdurbin We got the error after using the `:FooterCopyright` with this command:
`curl -X PUT -d ", Sciences Po | <a href="https://data.sciencespo.fr/misc/cond_jur/ToU.pdf" target="_blank">General Terms of Use</a>" http://localhost:8080/api/admin/settings/:FooterCopyright`

**Comment by djbrooke** [comment]
I'm going to close this one, as I don't think there's a code change to make here and the documentation is covered in another issue (#4467).
