### ISSUE TITLE
Provide support for DataCite Test URLs

### ISSUE THREAD

**Issue by poikilotherm** [IQSS/dataverse#6677]
When using the Test Fabrica of DataCite (https://test.datacite.org) to provide support for clickable citation URLs which indicate they are used for testing or training, nothing serious.

Currently, the DOI URLs are presented like this, leading to a 404 resolver error when accessing [the citation URL](https://doi.org/10.0346/JUELICH-DATA-BETA/2S0MUQ):
![image](https://user-images.githubusercontent.com/5468333/75246167-7de18580-57cf-11ea-8844-a4f17e8d6423.png)

When we would use [handle test URL provided by DataCite](https://handle.test.datacite.org/10.0346/juelich-data-beta/2s0muq), the link gets clickable:
![image](https://user-images.githubusercontent.com/5468333/75246425-06602600-57d0-11ea-90f8-c7cac9f6e331.png)

To provide support for this, refactoring necessary here, testing if the Test Fabrica is in use:

https://github.com/IQSS/dataverse/blob/9ce4aa00603d9fd9233a5c4d99b527ed230af1ce/src/main/java/edu/harvard/iq/dataverse/GlobalId.java#L123-L138

(Call graph: `dataset.xhtml` -> `dataset-citation.xhtml` -> `DatasetPage.displayCitation`, which is prepared by [`DatasetPage.init()`](http://github.com/poikilotherm/dataverse/blob/9ce4aa00603d9fd9233a5c4d99b527ed230af1ce/src/main/java/edu/harvard/iq/dataverse/DatasetPage.java#L1874-L1874) -> `Dataset.getCitation()` -> [`DatasetVersion.getCitation()`](http://github.com/poikilotherm/dataverse/blob/9ce4aa00603d9fd9233a5c4d99b527ed230af1ce/src/main/java/edu/harvard/iq/dataverse/DatasetVersion.java#L1316-L1316) creating a new `DataCitation` [finally rendering as HTML](http://github.com/poikilotherm/dataverse/blob/9ce4aa00603d9fd9233a5c4d99b527ed230af1ce/src/main/java/edu/harvard/iq/dataverse/DataCitation.java#L199-L202) calling the code above)

**Comment by djbrooke** [comment]
Thanks @poikilotherm for the suggestion. What's the UI/UX impact here? Is it that a non-typical DOI would be shown in the citation in test situations? 

@scolapasta this seems like a good idea. Any concerns?

**Comment by poikilotherm** [comment]
Diffs for pictures are non-trivial. :wink:
From my view, the only change is indeed the nontypical URL shown in the citation block, as shown in the example above. I would leave everything else untouched, like the non-URL DOI display in metadata etc.

**Comment by poikilotherm** [comment]
I had a brief look into this and it seemed like Pandora's box.

You could obviously hard code stuff or introduce a setting. Automatic changing might be hard, because the rendering happens independent from the Datacite service beans, which know if you're on testing.

To make this non-hacky, some architectural changes might need to happen. Maybe the view could retrieve the rendered string from a provider interface instead of GlobalId. Some other ideas floating around, too.

**Comment by cmbz** [comment]
2024/09/30: @qqmyers do you have a sense of whether we should keep this issue open/plan the work or has other work done since 2020 addressed the problem sufficiently?

**Comment by qqmyers** [comment]
Not my issue so I don't think I can decide on closing. I don't think anything that has been done changes the issue noted here (that test DOIs don't resolve), but I would say that at some level that's a 'feature'. DataCite explicitly doesn't support making test DOIs publicly findable (there's no test equivalent of the https://doi.org/ resolver for public access). I assume that's because they don't want test DOIs used in production, which would be possible if they resolved OK. Advertising the underlying handle address doesn't quite go that far (it says test in it) and it's non-standard, but getting a 404 instead is potentially a good reminder that this is a test DOI. That could perhaps be something that's decided by a feature flag if it's something that gets kept open.

**Comment by cmbz** [comment]
@scolapasta Please close/keep open based on Jim's comment: https://github.com/IQSS/dataverse/issues/6677#issuecomment-2383440840

**Comment by scolapasta** [comment]
I agree with @qqmyers so am willing to close it, and if @poikilotherm or someone else deems it critical, it can be reopened and as @qqmyers set with a feature flag for an installation that would want it.
