### ISSUE TITLE
Fix Integration Test Failures, Address Inconsistency

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#6681]
The test dashboard on jenkins.dataverse.org for commit https://github.com/IQSS/dataverse/commit/7227c381a0669c6e2d21d87edbe90947893cccc2 has shown:

- Blue (https://jenkins.dataverse.org/job/IQSS-dataverse-develop/362/)
- Yellow (https://jenkins.dataverse.org/job/IQSS-dataverse-develop/363/)
- Red (https://jenkins.dataverse.org/job/IQSS-dataverse-develop/365/)

We should investigate why we are getting mixed results here, and address any actual failing tests.

**Comment by donsizemore** [comment]
363 was a test suite failure:

`FAILURE!\njava.lang.AssertionError: \nExpected status code <200> doesn't match actual status code <500> at edu.harvard.iq.dataverse.api.FileMetadataIT.tearDownDataverse(FileMetadataIT.java:96`

so with 364:

`FAILURE!\njava.lang.AssertionError: \nExpected status code <200> doesn't match actual status code <500> at edu.harvard.iq.dataverse.api.FileMetadataIT.tearDownDataverse(FileMetadataIT.java:96`

365-367 have been already resolved.

**Comment by djbrooke** [comment]
Thanks @donsizemore for the details and thanks for your continued work on this. We've been blue for the past few builds, and I'll close this out for now. We can reopen if there are additional questions.
