### ISSUE TITLE
Update Tool Tips

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#669]
---

Author Name: **Elizabeth Quigley** (@eaquigley)
Original Redmine Issue: 4119, https://redmine.hmdc.harvard.edu/issues/4119
Original Date: 2014-06-17
Original Assignee: Eleni Castro

---

Notes field needs to also say "updates on data can go here as well"

Eleni-I'm not giving you a due date for this yet because I feel like some more of these might need to change so don't want you to have to do only one right now.

**Comment by mheppler** [comment]
All of the above listed tooltips and help text have been added to the appropriate pages.

**Comment by kcondon** [comment]
Looks good except there is a link in the TOU info area that was not made into a link in the app:

Here is an example of a Data Usage Agreement for datasets that have de-identified human subject data.

Passing back to @mheppler

**Comment by mheppler** [comment]
LINK: http://guides.dataverse.org/en/latest/user/permissions-tou.html#example-of-data-usage-agreement

**Comment by mheppler** [comment]
Added link to bundle for help text on the Terms of Use textarea input on the Edit License + Terms view of the dataset page.

**Comment by eaquigley** [comment]
@mheppler still need Community Norms link for when a user is in the edit license + terms view. Currently says, {0}Community Norms{1} and isn't linked.

**Comment by posixeleni** [comment]
@mheppler if you check out comment above https://github.com/IQSS/dataverse/issues/669#issuecomment-67521209, the Community Norms text when someone is editing/selecting a license needs to have the following text:

Informational help text should be included above the radio button options for licensing when someone is editing the license + terms:

>Datasets will default to a CC0 public domain dedication license (https://creativecommons.org/publicdomain/zero/1.0/). CC0 facilitates reuse and extensibility of research data. Our Community Norms (http://best-practices.dataverse.org/harvard-policies/community-norms.html) as well as good scientific practices expect that proper credit is given via citation. If you are unable to give your datasets a CC0 license you may enter your own custom Terms of Use for your datasets.

**Comment by mheppler** [comment]
Fixed display of Community Norms link in the License + Terms tab of the dataset page. Cleaned up render logic to remove repetitive markup.

**Comment by posixeleni** [comment]
If you look at the above comment https://github.com/IQSS/dataverse/issues/669#issuecomment-67521209 we are also missing help text when someone selects No CCO to put in their own Custom Terms of Use

>If you are unable to use CC0 for your datasets you are able to set your own custom terms of use. Here is a sample Data Usage Agreement (http://best-practices.dataverse.org/harvard-policies/sample-dua.html) for datasets that have de-identified human subject data.

**Comment by eaquigley** [comment]
I'm seeing all the text and links listed in the comments above. Closing ticket.
