### ISSUE TITLE
Bug in OAuth2 First Login page not using prefilled username from OAuth2UserRecord

### ISSUE THREAD

**Issue by poikilotherm** [IQSS/dataverse#6690]
While playing with our new Jülich DATA Beta service, I discovered that the username set in the authentication provider is never used in the first login form. This should be changed.

![image](https://user-images.githubusercontent.com/5468333/75343933-cebdb080-5899-11ea-925b-70b1fb6a4fb3.png)
![image](https://user-images.githubusercontent.com/5468333/75343980-e432da80-5899-11ea-8467-28ed5562b0b3.png)

Digging into the code. I set the field during auth:

https://github.com/IQSS/dataverse/blob/7227c381a0669c6e2d21d87edbe90947893cccc2/src/main/java/edu/harvard/iq/dataverse/authorization/providers/oauth2/oidc/OIDCAuthProvider.java#L189-L194

But the view is simply requesting the `username` attribute, which is never set in [`OAuth2FirstLoginPage.init()`](http://github.com/IQSS/dataverse/blob/develop/src/main/java/edu/harvard/iq/dataverse/authorization/providers/oauth2/OAuth2FirstLoginPage.java#L101-L101):
https://github.com/IQSS/dataverse/blob/7227c381a0669c6e2d21d87edbe90947893cccc2/src/main/webapp/oauth2/firstLogin.xhtml#L43-L46

As ~~always~~ most of the time: happy to contribute. This looks like it was not left out on purpose, so dunno if we need a trigger for UI team or just go ahead and fix it.

**Comment by pdurbin** [comment]
@poikilotherm as always, thanks for the bug report! Please go ahead and try to fix it! Thanks! :smile:

**Comment by espenfl** [comment]
Dear everyone. We also noticed this upon enabling OIDC for our organization. Would be nice to fill the user name as well. By the way, would `@` in the user name be supported?

**Comment by pdurbin** [comment]
> By the way, would `@` in the user name be supported?

@espenfl you are welcome to open an issue about this. Here's the code we use: https://github.com/IQSS/dataverse/blob/v5.2/src/main/java/edu/harvard/iq/dataverse/UserNameValidator.java#L36

**Comment by pdurbin** [comment]
This issue should be easier to work on now that developers have a simple way to spin up Keycloak on their laptops:

- #9234

By the way, @espenfl since I'm leaving a comment anyway, I'm not sure if you ever created a dedicated issue about supporting `@` in usernames, but if you're still interested in this, please go ahead and create one (and please comment here with the issue number). Thanks.

**Comment by RemieJanssen** [comment]
We use a OIDC connection for auth in our Dataverse, and we are also interested in having the username prefilled.
(In fact, we would prefer to skip this 'first login' form altogether, and rely on the information from the OIDC connection)

I dug through the code some more and found this comment 
https://github.com/IQSS/dataverse/blob/cf174b218b79073bb52ddf2e3d8eb557662403e4/src/main/java/edu/harvard/iq/dataverse/authorization/providers/oauth2/OAuth2FirstLoginPage.java#L295-L300

I guess that the setNewUser method is still called from the following line, but I'm not so familiar with the code base yet...
https://github.com/IQSS/dataverse/blob/cf174b218b79073bb52ddf2e3d8eb557662403e4/src/main/java/edu/harvard/iq/dataverse/authorization/providers/oauth2/OAuth2LoginBackingBean.java#L128

This would suggest that uncommenting the line `setUsername(newUser.getUsername());` might solve the problem. Looking at the blame, it seems @pdurbin has disabled this about 8 years ago. Do you recall why, and do you still stand by that?

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
