### ISSUE TITLE
Clarify docs that Shibboleth/SAML is supported by OpenID Connect (OIDC)

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#6701]
http://guides.dataverse.org/en/4.19/installation/shibboleth.html doesn't mention OpenID Connect (OIDC) but from a quick test with @poikilotherm at https://data-beta.fz-juelich.de I seem to be able to log in with my HarvardKey. As the screenshots below indicate, now I just need to wait for someone to approve my account.

<img width="1161" alt="Screen Shot 2020-02-27 at 8 17 49 AM" src="https://user-images.githubusercontent.com/21006/75449541-25c79200-593b-11ea-859c-3f7ee3ad254a.png">
<img width="1161" alt="Screen Shot 2020-02-27 at 8 18 02 AM" src="https://user-images.githubusercontent.com/21006/75449544-26f8bf00-593b-11ea-8a5c-501df9a773e1.png">
<img width="1161" alt="Screen Shot 2020-02-27 at 8 18 43 AM" src="https://user-images.githubusercontent.com/21006/75449546-2829ec00-593b-11ea-8a65-a0ab0ced5def.png">
<img width="1161" alt="Screen Shot 2020-02-27 at 8 19 13 AM" src="https://user-images.githubusercontent.com/21006/75449548-28c28280-593b-11ea-9301-a216f1048c7d.png">
<img width="1161" alt="Screen Shot 2020-02-27 at 8 19 25 AM" src="https://user-images.githubusercontent.com/21006/75449555-2bbd7300-593b-11ea-9dac-76c8e9f36869.png">
<img width="977" alt="Screen Shot 2020-02-27 at 8 20 57 AM" src="https://user-images.githubusercontent.com/21006/75449556-2c560980-593b-11ea-96e5-69e5d5c5b610.png">
<img width="977" alt="Screen Shot 2020-02-27 at 8 21 57 AM" src="https://user-images.githubusercontent.com/21006/75449559-2ceea000-593b-11ea-8e12-1124ff252a7a.png">

**Comment by pdurbin** [comment]
I got an email and clicked a link. "Sign Up completed."

<img width="715" alt="Screen Shot 2020-02-27 at 8 30 49 AM" src="https://user-images.githubusercontent.com/21006/75449749-8d7ddd00-593b-11ea-9c9c-90c64e53b823.png">
<img width="1223" alt="Screen Shot 2020-02-27 at 8 31 02 AM" src="https://user-images.githubusercontent.com/21006/75449750-8d7ddd00-593b-11ea-94c9-ee5feb424d79.png">

I'm not sure what to do now... I guess I should return to the other browser window that looks like this:

<img width="977" alt="Screen Shot 2020-02-27 at 8 21 57 AM" src="https://user-images.githubusercontent.com/21006/75449886-cf0e8800-593b-11ea-88ef-9531411d4444.png">

**Comment by apw1388** [comment]
Sadly you have no redirect to the services after the registration. You need to restart the login flow from the services.

**Comment by pdurbin** [comment]
@apw1388 thanks. At http://irclog.iq.harvard.edu/dataverse/2020-02-27#i_119565 @poikilotherm suggested "Just close that popup/overlay and click on the Harvard IdP again" and I just did. This is what I got:

<img width="977" alt="Screen Shot 2020-02-27 at 8 21 57 AM" src="https://user-images.githubusercontent.com/21006/75450294-87d4c700-593c-11ea-98e1-a094c3ac7987.png">
<img width="977" alt="Screen Shot 2020-02-27 at 8 35 48 AM" src="https://user-images.githubusercontent.com/21006/75450242-6ffd4300-593c-11ea-9020-a6076e65a690.png">
<img width="977" alt="Screen Shot 2020-02-27 at 8 36 02 AM" src="https://user-images.githubusercontent.com/21006/75450246-71c70680-593c-11ea-9b80-53cba8332f7b.png">
<img width="977" alt="Screen Shot 2020-02-27 at 8 36 22 AM" src="https://user-images.githubusercontent.com/21006/75450257-74296080-593c-11ea-81ff-3e3985ec39f0.png">

Is this all looking ok? Should I click "Confirm"?

**Comment by poikilotherm** [comment]
Perfectly fine! :smile:

**Comment by pdurbin** [comment]
@poikilotherm ok, I clicked "Confirm" (after first clicking the arrow to see more details) and this is what I got:

<img width="977" alt="Screen Shot 2020-02-27 at 8 42 25 AM" src="https://user-images.githubusercontent.com/21006/75450651-37119e00-593d-11ea-9361-a348f861492f.png">
<img width="977" alt="Screen Shot 2020-02-27 at 8 42 37 AM" src="https://user-images.githubusercontent.com/21006/75450647-36790780-593d-11ea-9a0b-d513b1af0131.png">
<img width="977" alt="Screen Shot 2020-02-27 at 8 42 56 AM" src="https://user-images.githubusercontent.com/21006/75450812-7a6c0c80-593d-11ea-9149-a4cfcdb7769b.png">

I clicked "Central Library - Research Data Management" and got a spinner and then the text moved.

<img width="977" alt="Screen Shot 2020-02-27 at 8 45 46 AM" src="https://user-images.githubusercontent.com/21006/75450903-a1c2d980-593d-11ea-8110-6b72d2b4f4ca.png">

I made the window taller:

<img width="977" alt="Screen Shot 2020-02-27 at 8 46 40 AM" src="https://user-images.githubusercontent.com/21006/75450978-bf903e80-593d-11ea-9fa8-b3664278cc3a.png">

Not sure what's going on. Nothing in the Javascript console log.

**Comment by pdurbin** [comment]
@poikilotherm just asked "Could you just re-initiate the login?" and I did and it worked! 🎉 

<img width="1109" alt="Screen Shot 2020-02-27 at 8 49 50 AM" src="https://user-images.githubusercontent.com/21006/75451295-4cd39300-593e-11ea-8ac4-21623e489f8d.png">
<img width="1109" alt="Screen Shot 2020-02-27 at 8 49 55 AM" src="https://user-images.githubusercontent.com/21006/75451300-4e9d5680-593e-11ea-8f4a-252638ed4205.png">
<img width="1109" alt="Screen Shot 2020-02-27 at 8 50 06 AM" src="https://user-images.githubusercontent.com/21006/75451304-4f35ed00-593e-11ea-843a-16439c302ac0.png">
<img width="1109" alt="Screen Shot 2020-02-27 at 8 50 17 AM" src="https://user-images.githubusercontent.com/21006/75451308-50671a00-593e-11ea-84df-f97f98fe78fd.png">
<img width="1109" alt="Screen Shot 2020-02-27 at 8 50 31 AM" src="https://user-images.githubusercontent.com/21006/75451310-50ffb080-593e-11ea-8e6a-ef904dcd0092.png">
<img width="1109" alt="Screen Shot 2020-02-27 at 8 51 45 AM" src="https://user-images.githubusercontent.com/21006/75451344-6aa0f800-593e-11ea-9775-091523829f89.png">

Good job @poikilotherm and @apw1388 !!!

**Comment by pdurbin** [comment]
Along the way a couple emails came through:

<img width="605" alt="Screen Shot 2020-02-27 at 8 57 17 AM" src="https://user-images.githubusercontent.com/21006/75451914-56a9c600-593f-11ea-9aa8-24b64012c7e5.png">
<img width="608" alt="Screen Shot 2020-02-27 at 8 58 11 AM" src="https://user-images.githubusercontent.com/21006/75451915-56a9c600-593f-11ea-848a-bbaffa49bfab.png">

@poikilotherm if you host your own guides and configure http://guides.dataverse.org/en/4.19/installation/config.html#guidesbaseurl you could mention https://login.helmholtz-data-federation.de in your custom guides (the guides link is in the "Jülich DATA - Beta Training Facility: Your account has been created" email) and explain in your custom guide that **MULTIPLE LOGIN TO THE SAME ACCOUNT (for me HarvardKey, ORCID, GitHub) IS SUPPORTED!** The dream of #3487 is alive!!! 🎉 🎉 🎉 I need to lie down. 🛏

**Comment by pdurbin** [comment]
@bencomp right, at minimum I was thinking we could add a section at the end of `doc/sphinx-guides/source/installation/shibboleth.rst` that links to the OIDC docs. Maybe "Other Ways to Support Shibboleth/SAML" could be the title of the section.

The OIDC docs are here: `doc/sphinx-guides/source/installation/oidc.rst`

**Comment by bencomp** [comment]
I think what you mean is "Other ways to support single sign-on" as the section title? Otherwise this is clear.

**Comment by pdurbin** [comment]
Sure, that's fine. Here's a preview of how the OIDC page will look in the next release: https://preview.guides.gdcc.io/en/develop/installation/oidc.html

Please note that SAML is mentioned a couple times. It's a way not to run Shibboleth:

As a use case:

- You want to use the [eduGain Federation](https://edugain.org/) or other well known SAML federations, but don’t want to deploy Shibboleth as your service provider. Using an IDM solution in front easily allows you to use them without hassle.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.

**Comment by pdurbin** [comment]
It's fine that this issue was closed. Auth will be changing a lot in the future. I recommend reading our doc on it: https://docs.google.com/document/d/1624KuPj4zp_TQzWivqaNY3YUCzibwFib8tZUz_IshTo/edit?usp=sharing
