### ISSUE TITLE
Dataverse Metrics: icon/title link, improve UI/UX

### ISSUE THREAD

**Issue by kaitlinnewson** [IQSS/dataverse#6707]
Hi Dataverse team!

I didn't see any other issues on this - apologies in advance if this is a duplicate. I see some related issues at #3538 and #3341 but no specific discussion of this issue.

In the UI in Dataverse, we've noticed that users can't tell that the 'Metrics' link at the top of the Dataverse page can be clicked. I think this may be partially because of the design of the element, but also because it looks like a label for the number beside it (and not something that is clickable). Perhaps this style should vary depending on if this element is a link (if `:MetricsUrl` has been set).

![Screen Shot 2020-02-28 at 10 21 22 AM](https://user-images.githubusercontent.com/6903515/75560919-18caa180-5a14-11ea-91a8-75477dcb0fb2.png)

Happy to discuss further! In our case, the result of this is that people don't tend to find our external metrics application.

**Comment by pdurbin** [comment]
@kaitlinnewson yeah, I agree that the "Metrics" button doesn't scream "CLICK ME!" Thanks for opening this issue. As a work around I'm wondering if you can use some custom CSS: http://guides.dataverse.org/en/4.19/installation/config.html#custom-stylesheet

**Comment by mheppler** [comment]
Thank you for opening a new issue, @kaitlinnewson. This is something on the to-do list dataverse pg improvements after we complete dataset pg improvements. We appreciate your feedback from your users, and for you getting the ball rolling on the discussion.
