### ISSUE TITLE
Improve Geospatial Metadata Block by adding additional fields

### ISSUE THREAD

**Issue by tlchristian** [IQSS/dataverse#6713]
As a curator, I would like to be able to add additional standardized geospatial metadata to ensure usability of geospatial datasets.  Specifically, add the following spatial reference elements that are considered essential according to the FGDC-CSDGM Standard:

- Latitude_Resolution
- Longitude_Resolution
- Geographic_Coordinate_Units
- Map_Projection
- Grid_Coordinate_System
- Geospatial_Data_Presentation_Form

**Comment by mheppler** [comment]
Additional improvements suggested in **Attribute naming of bounding-box wrong (North and South Longitude) #5645**.

**Comment by amberleahey** [comment]
Just to chime in and say this is very important and we are getting several requests for this as more researchers with geospatial data are depositing. We are noticing geospatial projection information being stored creatively throughout the metadata across our installation (sigh), at the dataset and file level, and we'd like to see this feature be made available in the geospatial metadata block officially. If possible, these additional geospatial fields could also be faceted on so that way users can easily identify data in different projections for their projects.

**Comment by atrisovic** [comment]
In order to incorporate these geospatial metadata fields, we need information if they are the standard and community-used fields, and also their mappings to other metadata schemas.

**Comment by DS-INRA** [comment]
Here are documents for the mapping whith the [INSPIRE Directive](https://inspire.ec.europa.eu/about-inspire/563) requirements : https://raw.githubusercontent.com/INSPIRE-MIF/technical-guidelines/2022.2/metadata/metadata-iso19139/metadata-iso19139.pdf
The most prioritary for us would be the coordinate reference system (3.2.1.1. of document above), which could be implemented as a bloc with 2 subfields :

- URL (example value 1 : http://www.opengis.net/def/crs/EPSG/0/4258, example value 2 : https://www.data.gouv.fr/fr/datasets/code-officiel-geographique-cog/)

- Code (example value 1 : EPSG:4258, example value 2 : BDTopo ® Edition mars 2019)

**Comment by pdurbin** [comment]
@DS-INRA thanks! FYI we also have a Zulip thread going on the topic of additional fields, if you'd like to participate there: https://dataverse.zulipchat.com/#narrow/stream/376593-geospatial/topic/more.20fields.20.236713

Another option is to attend one of our weekly calls! (Mondays at 10am Boston time) We'd like to have @amberleahey back after our great discussion last week: https://docs.google.com/document/d/1uByvnjhi7dD11i3GBaNAlM4KI1pWRRFtiRnc_b3ivm4/edit?usp=sharing

**Comment by cmbz** [comment]
**2024/01/08:** 
- Implementing the features described here will require a champion (ideally who is a geospatial metadata expert) and substantial project management resources. 
- There are many related open issues pertaining to geospatial metadata block improvements
- Recommendation: Create a full proposal that looks at geospatial metadata support and geospatial UI entry improvements holistically,  includes existing related issues, and incorporates feedback from the Dataverse community.
  - Example: Draw bounding box on map rather than entire exact lat/long coords.

**Comment by cmbz** [comment]
2024/01/08: Closing, see comment here: https://github.com/IQSS/dataverse/issues/6713#issuecomment-1881720195

**Comment by pdurbin** [comment]
@amberleahey Ceilyn and I closed this issue but I'm hoping we can use all the great thought you put into the [NetCDF/HDF5 Design Doc](https://docs.google.com/document/d/1Ax_sMdgx5ROkIBA7-IC4_hySvgXkk6O8qTZLIvWWnqE/edit?usp=sharing) in the future. I really appreciate you attending meetings and working on this! ❤️

**Comment by amberleahey** [comment]
great! @pdurbin here are new proposed fields and subfields and their corresponding mapping that have been discussed by some in the NetCDF design project! As part of that project, I shared the proposed fields with experts here in Canada including John Huck (UAlberta) and Paul Lesack (UBC) https://docs.google.com/presentation/d/1mULdaZcgvbyFFJYcYCIE7VgZD5rA8fLwULBlzBWfi58/edit?usp=sharing

**Comment by DS-INRA** [comment]
Great !
Just to confirm the interest on our side to these additions, we also added some of this fields in the list (here is our added lines from the tsv, which could be improved) and plan to add the Spatial Reference System info so it'd be great to have the fields from the slide in the core tsv.
| name | title | description | watermark |  fieldType | parent |
|---|---|---|---|---|---|
| qualityValidity | Quality and validity |  |  | none | |
| lineage | Lineage | Statement on process history and/or overall quality of the spatial data set. Where appropriate it may include a statement whether the data set has been validated or quality assured, whether it is the official version (if multiple versions exist), and whether it has legal validity. |  | textbox | qualityValidity |
| spatialResolution | Spatial resolution | Level of detail of the data set. It shall be expressed as a set of zero to many resolution distances (typically for gridded data and imagery-derived products) or equivalent scales (typically for maps or map-derived products). |  | text | qualityValidity |
| conformity | Conformity | Article 7(1) of Directive  2007/2/EC or other specification |  | none | |
| specification | Specification | Citation of the implementing rules adopted under Article 7(1) of Directive 2007/2/EC or other specification to which a particular resource conforms. A resource may conform to more than one implementing rules. |  | textbox | conformity |
| degree | Degree | Degree of conformity of the resource to the implementing rules adopted under Article 7(1) of Directive 2007/2/EC or other specification. |  | text conformity |
And our controlled values for conformity degree : 
controlledvocabulary.degree.conformant=Conformant
controlledvocabulary.degree.not_conformant=Not Conformant
controlledvocabulary.degree.not_evaluated=Not evaluated
