### ISSUE TITLE
Extra Colon on Configuration Page

### ISSUE THREAD

**Issue by charvey-CSS** [IQSS/dataverse#6716]
Under Installation Guide/Configuration
here http://guides.dataverse.org/en/latest/installation/config.html
there is an extra colon under :InheritParentRoleAssignments as 
shown in attached image. 
![Screen Shot 2020-03-03 at 10 20 59 AM](https://user-images.githubusercontent.com/52752765/75792551-2184e580-5d3c-11ea-9738-caab2ea78d84.png)

**Comment by djbrooke** [comment]
@charvey-CSS thanks for the report. Do you want to work together on a pull request for this? I'm happy to guide you through the process. If not, I'll make the change.

**Comment by charvey-CSS** [comment]
Definitely interested in going over a pull request. I'm out for a ticket at the moment.

-Cameron
________________________________
