### ISSUE TITLE
Investigate simplifying metadata fields for "Data Collector"

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#6720]
There are two ways to add the name of a Data Collector:

Using one of the Contributor options in the Citation metadata block:

<img width="705" alt="Screen Shot 2020-03-03 at 8 45 22 PM" src="https://user-images.githubusercontent.com/18374574/75836478-ff1cb780-5d8f-11ea-9c9a-f45406d156d1.png">

Using the Data Collector field in the Social Science/Humanities metadata block:

<img width="713" alt="Screen Shot 2020-03-03 at 8 45 41 PM" src="https://user-images.githubusercontent.com/18374574/75836515-1fe50d00-5d90-11ea-89d9-9697d64bed8b.png">

The option in the Contributor vocab comes from the list in [DataCite's schema](https://schema.datacite.org/meta/kernel-4.3/doc/DataCite-MetadataKernel_v4.3.pdf):
> Person/institution responsible for finding, gathering/collecting data under the guidelines of the author(s) or Principal Investigator (PI). May also use when crediting survey conductors, interviewers, event or condition observers, person responsible for monitoring key instrument data.

The field in the Social Science/Humanities metadata block comes from DDI Codebook ([element page in DDI documentation](https://ddialliance.org/Specification/DDI-Codebook/2.5/XMLSchema/field_level_documentation_files/schemas/codebook_xsd/elements/dataCollector.html)):

> The entity (individual, agency, or institution) responsible for administering the questionnaire or interview or compiling the data. This refers to the entity collecting the data, not to the entity producing the documentation.

I think these definitions aren't different enough to warrant their own fields. Having two fields is contributing to important information loss during different metadata transformations, depending on how often these fields are being used and which ones are used more often. Trying to include both fields when transforming metadata would make metadata mapping more complicated than it needs to be.

This issue is very related to the issue about duplicate fields for funding info (https://github.com/IQSS/dataverse/issues/4859) and maybe could be resolved in a similar way.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
