### ISSUE TITLE
create and link to crowdsourced spreadsheet indicating status of Dataverse trademark violations

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#6722]
Seeing someone just now talking about Dataverse charging them...

- "I have no idea what this is but why am i being charged out of my bank account"
- "Why am i being charged"

... has me fired up to go ahead and create an issue I mentioned the other day.

Here's what I'm reacting to:

<img width="908" alt="Screen Shot 2020-03-04 at 4 00 06 AM" src="https://user-images.githubusercontent.com/21006/75862367-d5ce4c80-5dcc-11ea-870b-3336767ba2dd.png">

<img width="1159" alt="Screen Shot 2020-03-04 at 3 55 54 AM" src="https://user-images.githubusercontent.com/21006/75862384-dcf55a80-5dcc-11ea-8138-d2263adb4bac.png">

My guess is this person in chat bought a game on Android and maybe the in-app purchase got them or something. Who knows. To give you a visual (this one is old), games might look something like this:

![Screenshot_20170921-204234](https://user-images.githubusercontent.com/21006/75863015-cef40980-5dcd-11ea-8f4e-3e6cc7a06014.png)

The other day I was reacting to this Tweet: https://twitter.com/DataVerse_AIM/status/1234288880209231874

Here's a visual: 

<img width="842" alt="Screen Shot 2020-03-02 at 2 22 45 AM" src="https://user-images.githubusercontent.com/21006/75863098-f2b74f80-5dcd-11ea-8f63-660ffb4cbbe7.png">

That lead me to send this email:

--

Thanks, Pat! I just fired up TweetDeck and noticed something new that reminded me to thank you!

(Merce, thanks for looping Pat in. We should probably explain to the Dataverse community what the procedure should be. I would suggest a list of "misuse" cases like https://wiki.opensource.org/bin/Main/OSI+Operations/OSI-Logo+Misuse/ where the "notifier" gets credit and the status (open/resolved) gets updated over time. People like Sherry Lake from UVa have been notifiers in the past. It's a contribution to Dataverse! We could also list cases that Liz and others have helped resolve so that the community doesn't have to re-report violations. Danny, the misuse list could just be a Google spreadsheet for now, MVP-style, and we could link to it with "please help us protect the Dataverse trademark by reporting unknown violations" in the README, right after we explain, as Merce says, that Harvard owns the trademark. I dropped Jon/GDCC from cc but let's loop the Dataverse community back into the conversation when we're ready. Perhaps this could simply be a GitHub issue, which I'm happy to create. Please just let me know.)

This short video from a few hours ago is a good example of likelihood of confusion over the Dataverse brand: https://twitter.com/DataVerse_AIM/status/1234288880209231874

The text of the tweet is "Check out the different ways you can view subsea cable events and anomalies using Dataverse" I could *very* easily see how someone who does searches on the word "Dataverse" on Twitter from time to time (like I do) would naturally assume that this video is about *our* Dataverse product. It is not. Pat, I don't know if our lawyer needs more evidence or not. I'm also attaching a screenshot so you (and others cc'd
here) can get a quick visual without clicking "play".

It's a good problem to have that people like your product's name so much that they (accidentally) start using it for their product! Thank you Ella, Gary's daughter! Great name! Dataverse! :)

---

Small chunks. My plan:

- Create a Google Spreadsheet
- Link to it  from the README with a little explanation, maybe even linking back to this issue for discussion!

MVP-style, the spreadsheet would be a way less fancy version of https://wiki.opensource.org/bin/Main/OSI+Operations/OSI-Logo+Misuse/

Here's a visual:

<img width="1784" alt="Screen Shot 2020-03-04 at 4 12 27 AM" src="https://user-images.githubusercontent.com/21006/75863436-78d39600-5dce-11ea-9612-6633abd49044.png">

**Comment by djbrooke** [comment]
This isn't the process that we'll use for this. If someone perceives a possible trademark violation, please email support@dataverse.org and we'll take it from there.
