### ISSUE TITLE
Create a Tier-1 support playbook

### ISSUE THREAD

**Issue by ericwood-1** [IQSS/dataverse#6724]
Creating a T1 guide for moving data, unlocking datasets, other basic tier-1 tasks, etc.

**Comment by poikilotherm** [comment]
Could this be a task for dvcli?

**Comment by djbrooke** [comment]
Hey @ewoodharvard - thanks for adding this issue. Let's catch up next time you're upstairs about what you're thinking here.

**Comment by pdurbin** [comment]
To get this rolling we should start with what the new guide should be called.

- Support Guide?
- End User Support Guide?
- Support Team Guide?

Here are the existing guides:

- User Guide
- Admin Guide
- API Guide
- Installation Guide
- Developer Guide
- Style Guide

@ericwood-1 it would be great to get some of the knowledge out of your wiki and into the official documentation!

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
