### ISSUE TITLE
Support for Core Trust Seal Certification - Harvard Dataverse

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#6728]
Planning for our application will require we address the following support:

1-super user ability to define a "managed collection" as certified
2-searchable facet for the collections
3-"badge' for collections level and dataset level

**Comment by djbrooke** [comment]
Thanks @sbarbosadataverse for discussing this a few minutes ago, I'll update a bit of the above text.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
