### ISSUE TITLE
Users struggle to find tree view for dataset files

### ISSUE THREAD

**Issue by PaulBoon** [IQSS/dataverse#6730]
When we upgraded from 4.10.1 to 4.18.1 some users where eager to see the directory structure (tree view) of the dataset files, but could not at first find it. 

I propose to make the two view 'options' more related to each other and the files 'view' by using a 'tab view' instead of two separate buttons. Furthermore I propose to use icons on the buttons to make them more prominent and a bit more intuitive. 

![IMG_2676](https://user-images.githubusercontent.com/2151103/76160529-3510c180-612b-11ea-93ec-82a2c01062d3.jpg)

**Comment by TaniaSchlatter** [comment]
Hi @PaulBoon. I can see that the button to toggle List and Tree view is hard to find. The dataset page is busy. We need to balance a wide number of possible user scenarios and installation situations. To achieve this, each UI element has a role to play. Elements are part of groups based on function and context. Tabs change the information shown for a dataset. Search/filter/sort features change the display of information on the files tab. "Tree view" plays a role more like search and filter features than the role of tabs. We need to balance the visual emphasis of elements overall, which means that some are less noticeable than others. 

I understand that rationale is not necessarily useful for users stuck in a particular situation. Hopefully this grouping will be more clear in the redesign. [Mockups of the updated dataset page](https://sketch.cloud/s/o5ZK3/a/OMPJGR)

**Comment by PaulBoon** [comment]
Hi @TaniaSchlatter, I think that usability testing would be helpful to improve the interface. 
Also the datasets you then test with should not only have just a handful of files in a single folder, but instead have much more files that are obviously categorised in a folder structure. 
As an alternative you should also consider to always show a tree view to the left of the file listing.

**Comment by TaniaSchlatter** [comment]
@PaulBoon we did usability testing a little over a year ago before implementation. Responses were quite  positive. We made some refinements, based on what we learned, and launched. There is always room for improvement. We are planning more usability testing, and will keep this feedback in mind.

**Comment by PaulBoon** [comment]
I just had to edit a screenshot from the mockup to explain what I think is better. 
![Edited screenshot of mockup](https://user-images.githubusercontent.com/2151103/78908923-16cc1780-7a83-11ea-90b2-7ab9af80352f.png)

**Comment by LauraHuisintveld** [comment]
I am not sure if this deserves a separate issue, but one of our users suggested to show the tree view (instead of table view) as default for datasets with a lot of files. He mentioned an example of a dataset with 1129 files.
There are of course also datasets with a lot of files without a folder structure at all.

**Comment by rlzijdeman** [comment]
Hi, I'd like to +1 @LauraHuisintveld 's the suggestion to have tree view as the default. Our users fail to find the label as well. Moreover, if there is no structure, tree view doesn't hurt anyone, while vice versa it sort of does.

**Comment by BPeuch** [comment]
Though I can't rely on user feedback, I instinctively side with @LauraHuisintveld's proposal. A compromise could also be: let users choose whether their dataset's files will appear in table or tree view on a dataset basis (e.g. the same user might think that, for dataset A, which has few files, table view is fine, but for dataset B, which has 50+ files, it is best to have tree view toggled by default, though users can still revert to table view if that's their preference).

**Comment by pdurbin** [comment]
Related:

- #8694
- #8892

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
