### ISSUE TITLE
Admin cannot view deaccessionned record in GUI list if draft of said record still exists

### ISSUE THREAD

**Issue by BPeuch** [IQSS/dataverse#6733]
Version: 4.19

Hello everybody,

I ran a few tests to study how the deaccession feature works, and I found something that is not a major concern, but I didn't know if y'all knew about it.

The general situation, I believe, is the following: a dataset was published, but for some reason it must unfortunately be deaccessioned. Using the GUI the admin accesses the record for that dataset and selects `Deaccession Dataset`. The resulting tombstone can then be found in only two ways:

1. By users who saved the hyperlink;
2. By Dataverse admins, who can see a reference to the tombstone landing page in the general list of datasets and Dataverses, like so:

![image](https://user-images.githubusercontent.com/15209224/76308973-24e41800-62cc-11ea-93f9-c3c3bfaf3582.png)

However, I found a certain workaround that makes the reference to the tombstone landing page not show up in said list. The steps are the following:

1. Deposit a dataset;
2. Publish it;
3. Click on `Edit Metadata` or `Edit Terms` then `Save Changes` (no actual modifications required);
=> This will create a `Draft` ~~and `Unpublished`~~ version of the dataset, co-existing with the published version;
4. Deaccession the published version of the dataset;
=> This will replace the published record with a tombstone landing page. However, the `Draft` and `Unpublished` version of the record remains.

At this point, the deaccessioned record can be accessed through the hyperlink, but it does not show up in the general list of datasets and Dataverses even while logged in as admin. Only the `Draft` and `Unpublished` version does.

**Comment by djbrooke** [comment]
Thanks @BPeuch. I confirmed this in demo.dataverse.org using the replication steps above.

**Comment by mheppler** [comment]
Hello, @BPeuch. I just wanted to confirm your expected behavior of a deaccessioned version of dataset. In the screenshot below, there is a `Draft` version of a dataset, listed just above the single published version. This is **step 3** in your outline above.

<img width="863" alt="Screen Shot 2020-04-22 at 3 16 48 PM" src="https://user-images.githubusercontent.com/687227/80024139-9a86fa80-84ac-11ea-83eb-fa87109bbeb0.png">

So the proposed view you would expect in step 4 displays the `Draft` and the `Deaccessioned` versions together, like this mocked up screenshot shows?

<img width="860" alt="Screen Shot 2020-04-22 at 3 22 11 PM" src="https://user-images.githubusercontent.com/687227/80024517-33b61100-84ad-11ea-87a6-f33737c238e2.png">

**Comment by BPeuch** [comment]
Hello @mheppler. Thank you for your feedback.

> So the proposed view you would expect in step 4 displays the ```Draft``` and the ```Deaccessioned``` versions together, like this mocked up screenshot shows?

Yes, it would seem most logical to me because, as is, we have a certain category of datasets — i.e. those for which only a ```Draft``` version exists, not a ```Published``` one — that behaves differently from the others, once deaccessioned, for no particular reason as far as I know. (Or maybe there's an implicit one but then I haven't found it.)

> For the record, if you deaccession the single dataset version before creating the draft, the deaccession version is still removed from the result card list view on the dataverse pg, as this ```Draft``` and ```Unpublished``` dataset shows.

I'm not sure I'm following here. How can you create a ```Draft``` version of a dataset if you previously deaccessioned it? The option of modifying the dataset isn't available anymore in that case, even to a super user, right?

**Comment by pdurbin** [comment]
Related: Deaccession latest published version prevents further edits, deaccession or create draft #1308

**Comment by mheppler** [comment]
Also adding this related older issue that requests. We already have a Publication Status that allows for filtering of deaccessioned datasets, and confirmed that when I search for a deaccessioned dataset title, and it is returned as a result, so this request may be already done.

>Searching for De-accessioned Datasets #1725
>posixeleni commented on Mar 19, 2015
>
>Spoke with mcrosas and I had missed an important use case where we would have end users wanting to search for known datasets in Dataverse that had become de-accessioned. So we need to review this functionality for 4.x to see how these would be made searchable.

<img width="1190" alt="Screen Shot 2020-07-15 at 5 14 46 PM" src="https://user-images.githubusercontent.com/687227/87596813-bc180c80-c6be-11ea-8d3f-a4d6f2c89d07.png">

**Comment by pdurbin** [comment]
> => This will replace the published record with a tombstone landing page. However, the `Draft` and `Unpublished` version of the record remains.

@BPeuch can you still replicate this on https://demo.dataverse.org ?

Maybe I followed your steps wrong, but I can't. Only the draft "search card" (as we call it) is left:

<img width="341" alt="Screen Shot 2022-10-14 at 8 56 29 AM" src="https://user-images.githubusercontent.com/21006/195852518-5ade60db-5de9-435e-b329-304c00a7ce67.png">

**Comment by BPeuch** [comment]
@pdurbin Indeed, then I think the problem remains. I just tested it by following these two steps:

1. I created and published a new dataset (which I called "Chickpea test deaccession later showing up or not"), then I created an extra, `Draft` version of it, then deaccessioned the published version.
2. I created and published a second dataset (which I called "Lentils deaccession") then immediately deaccessioned it.

The result is that I can see the entry for the second, deaccessioned record in the list, but not for the first one, as you can see here:

![deacc](https://user-images.githubusercontent.com/15209224/197991552-d2ba3287-3834-41df-849e-827e378edf1f.png)

In the version history of the first dataset, both iterations appear: the initial, published-then-deaccessioned version, and the second, `Draft` version of the dataset:

![two](https://user-images.githubusercontent.com/15209224/197992823-094b820a-7dee-4b02-a9cd-f6e3ca9ef500.png)

I think that, just like there can be several entries in the list of datasets for iterations of one sole dataset (e.g. a `Published` version followed by a `Draft` version of a certain dataset), maybe there should also be both the `Deaccessioned` iteration alongside the `Draft` iteration, to follow through on that logic.

(I hope I made it clear but if I didn't quite manage, don't hesitate to reach out on the chat. It's SLOPI after all :) )

**Comment by pdurbin** [comment]
@BPeuch I'll need to circle back to this but I think the behavior you're seeing is by design (my emphasis added):

"The overall goal is to always have a way from users to search for or browse to any dataset that's related to them. If they have deaccessioned a dataset, they (and other people who have been granted access) should still be able to find it! That said, we don't want to overwhelm them with deaccessioned datasets. **If they take a deaccessioned dataset and make a new draft or publish it, we won't show a deaccessioned card anymore.**"

-- [design doc for deaccessioning](https://docs.google.com/document/d/1lFcwjtdGIqqQLYYnwtTI2GZNzmzYlrnMk2omGcXO9oY/edit?usp=sharing)

**Comment by BPeuch** [comment]
@pdurbin Indeed, this seems quite deliberate then. In that case I'll close the issue. Thank you for elucidating this Philip!
