### ISSUE TITLE
As an admin, I want to be able to hide certain fields in Terms

### ISSUE THREAD

**Issue by BPeuch** [IQSS/dataverse#6737]
Version 4.19

Hello everybody,

A comment that came to us from a social scientist when we sat him in front of Dataverse and asked him for his impressions while depositing a dataset was that the Terms section looks very, very **long**.

He feared that depositors might lose courage and rush through or even give up filling in this very important section of the metadata.

It looks like the making of this section was greatly inspired by DDI, as the field labels often correspond to those of DDI tags. Here's the DDI output:

```
<useStmt>Terms of Use: Terms of Use</useStmt>
<confDec>Terms of Use: Confidentiality Declaration</confDec>
<specPerm>Terms of Use: Special Permissions</specPerm>
<restrctn>Terms of Use: Restrictions</restrctn>
<citeReq>Terms of Use: Citation Requirements</citeReq>
<deposReq>Terms of Use: Depositor Requirements</deposReq>
<dataAccs>Restricted Files + Terms of Access: Terms of Access</dataAccs>
<accsPlac>Restricted Files + Terms of Access: Data Access Place</accsPlac>
<conditions>Terms of Use: Conditions</conditions>
<disclaimer>Terms of Use: Disclaimer</disclaimer>
<origArch>Restricted Files + Terms of Access: Original Archive</origArch>
<avlStatus>Restricted Files + Terms of Access: Availability Status</avlStatus>
<contact>Restricted Files + Terms of Access: Contact for Access</contact>
<collSize>Restricted Files + Terms of Access: Size of Collection</collSize>
<complete>Restricted Files + Terms of Access: Study Completion</complete>
```

Surely that's good practice since Dataverse was developed for storing and sharing social science datasets, and DDI is the international standard for documenting social science data.

However, what would be really great would be for the admin to be able to modify the Terms section just like another set of metadata.

Of course, it should very much work like Citation Metadata: the Terms section should not be entirely removable, and some of its fields should be absolutely must-have (e.g. Waiver, Terms of Use and perhaps Terms of Access) just like Title, Author and Contact Information cannot be removed from Citation Metadata.

But the other fields should be **hideable** so that this metadata subset can be better managed.

One could argue that several of these fields are or can be redundant, e.g. Special Permissions, Restrictions and Conditions with Terms of Use/Access, Citation Requirements with Dataverse's automatically generated citation, Contact for Access with the Contact compound element in Citation Metadata…

If fields can be hidden however, some of them can be better highlighted, like Original Archive, which is a most valuable field for documenting provenance (this is the archivist speaking).

**Comment by TaniaSchlatter** [comment]
@BPeuch thanks for this feedback. We have done several rounds of mockups that reconsider the UI for Terms in the context of DataTags (identifying and restricting sensitive data), and enabling a wider possibility possibility of licenses. This work has been deprioritized while we work on data management practices and processes, to understand implications for Terms. However, the need to improve is still there.

**Comment by BPeuch** [comment]
Thank you for your reply, @TaniaSchlatter. It's good to know that you're working on this, though I understand IQSS have a lot on their plate. I've also been closely following the discussions regarding licences and I have no doubt the end result will do more than satisfy.

**Comment by BPeuch** [comment]
As @TaniaSchlatter mentioned, related to #6605.

**Comment by pdurbin** [comment]
@BPeuch have you played with this recently, now that multiple license are supported? A lot of these fields are hidden by default now. You can try it out at https://demo.dataverse.org

**Comment by BPeuch** [comment]
@pdurbin Thanks for the shout-out! That's an interesting development. I think some researchers might still want to combine a by-default license (like CC0 or CC-BY) with fields like "Disclaimer," so ideally a field-by-field decision process might be preferable.

**Comment by pdurbin** [comment]
@BPeuch hmm. Ok. I think that might be contrary to the thinking that went into the multiple license feature. My understanding is that if you're downloading data with standard license like CC-BY, you shouldn't have to think about a bunch of extra fields. You just think about the standard license.

**Comment by BPeuch** [comment]
@pdurbin I think some of the fields in the "Dataset Terms" metadata box bear over other aspects of data access and reuse which are not covered by licenses. For example, though a dataset might be published with CC-BY*, depositors might want to specify things in certain fields such as:
- Citation Requirements: "Please make to include the version number when you cite this dataset, as the initial publication contained errors."
- Depositor Requirements: "Please make sure you include [research center email address] in cc of all your communications to the authors of the study."
- Disclaimer: "The authors of the study, the research centers involved, and the funding agencies bear no responsibility in case of…"

**Comment by pdurbin** [comment]
@BPeuch that's fine but I think we're no longer talking about hiding fields. 😄 

What if you kick off a thread on https://groups.google.com/g/dataverse-community ?

Then maybe we can close this issue, with your blessing! 😄
