### ISSUE TITLE
Inconsistencies in DOI display (related publications)

### ISSUE THREAD

**Issue by lmaylein** [IQSS/dataverse#6740]
It is somewhat unpleasant that the display of DOIs for related publications is not uniform. In the header of a dataset, they are displayed differently than in the "Citation metadata" tab.

How should DOIs be entered in the related publications? As complete URL or only the identifier part?

Here are two examples. In the first, only the identifier part was entered, in the second the complete URL.

Example 1:

![doi1](https://user-images.githubusercontent.com/7468155/76502185-e2454b80-6443-11ea-93c3-81189d70467f.png)

Examaple 2:

![doi2](https://user-images.githubusercontent.com/7468155/76502200-e7a29600-6443-11ea-9731-3e34ffc86621.png)

In both cases the display is not uniform. In example 2, the URL is then displayed twice in the Citation Metadata tab (once as text, once as a link).

Crossref has been recommending for several years that DOIs should always be cited as the complete URL.

**Comment by BPeuch** [comment]
Agreed. Related to @jggautier's issue #5277 "As a curator, I want to more easily add metadata about related resources so that it's more discoverable".

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
