### ISSUE TITLE
Failure to overwrite dataset versions ("Update Current Version") upon publication

### ISSUE THREAD

**Issue by BPeuch** [IQSS/dataverse#6745]
Version: 4.19

[ Closely related to #4760. Maybe I found a way of replicating the error that @kcondon first encountered because I got the same error message. ]

Hello everybody,

I was running some tests of version management in Dataverse. I did the following:

1. I added a dataset with a file (file A).
2. I published said dataset.
3. I edited the dataset by deleting file A and adding another file (file B).
4. I tried to publish the dataset's new version, but instead of incrementing the version (from version 1.x to version 2.x or from version x.1 to version x.2), I chose the third option proposed when updating a dataset, namely "Update Current Version (will permanently overwrite the latest published version)" as shown here:

![image](https://user-images.githubusercontent.com/15209224/76855877-5754be80-6852-11ea-83f8-2f239f724a9a.png)

I tried this while connected as an admin and superuser, so I believe I had all necessary rights to do this. However, Dataverse sent back the following error message:

![image](https://user-images.githubusercontent.com/15209224/76855968-9125c500-6852-11ea-94e1-1ae78b546045.png)

"Error – Dataset Version Update failed. Changes are still in the DRAFT version. - ``edu.harvard.iq.dataverse.engine.command.exception.IllegalCommandException``: Cannot change files in the dataset If you believe this is an error, please contact SODAtaverse Support for assistance."

I'm not sure what to make of this.

**Comment by djbrooke** [comment]
@BPeuch if it's not sensitive, can you add the test file here? Or add it to a test dataset on demo.dataverse.org and link it here? Thanks!

**Comment by BPeuch** [comment]
Hey @djbrooke. Thank you for your reaction. I didn't have the reflex of running the same test on demo.dataverse.org, but I will make sure to do that in the future.

I didn't run in the issues on Demo Dataverse, and then later tests produced other errors. So I think we must further investigate internally first before I ask for IQSS feedback here. I'll close this for now. Sorry for the inconvenience.

**Comment by djbrooke** [comment]
No worries, thanks @BPeuch
