### ISSUE TITLE
Allow favicon to be configurable by sys-admin

### ISSUE THREAD

**Issue by oodu** [IQSS/dataverse#6746]
One need to make a change of the follow if you need a change of default images with new images:

        src/main/webapp/resources/images/fav/android-chrome-192x192.png
        .../images/fav/android-chrome-512x512.png
        .../images/fav/apple-touch-icon.png
        .../images/fav/browserconfig.xml
        .../images/fav/favicon-16x16.png
        .../images/fav/favicon-32x32.png
        .../images/fav/favicon.ico
        .../images/fav/mstile-144x144.png
        .../images/fav/mstile-150x150.png
        .../images/fav/mstile-310x150.png
        .../images/fav/mstile-310x310.png
        .../images/fav/mstile-70x70.png
        .../images/fav/safari-pinned-tab.svg
        .../images/fav/site.webmanifest

    ...which were link to dataverse-template:

            <link rel="apple-touch-icon" sizes="180x180" href="#{resource['images/fav/apple-touch-icon.png']}"/>
            <link rel="icon" type="image/png" sizes="32x32" href="#{resource['images/fav/favicon-32x32.png']}"/>
            <link rel="icon" type="image/png" sizes="16x16" href="#{resource['images/fav/
    favicon-16x16.png']}"/>
            <link rel="manifest" href="#{resource['images/fav/site.webmanifest']}"/>
            <link rel="mask-icon" href="#{resource['images/fav/safari-pinned-tab.svg']}" color="#da532c"/>
            <meta name="msapplication-TileColor" content="#da532c"/>
            <meta name="theme-color" content="#ffffff"/>

**Comment by djbrooke** [comment]
Relevant community discussion:

https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/dataverse-community/wjH_dPaoSAY/LfgKFSfWHAAJ

**Comment by pdurbin** [comment]
Related (list of files created by RealFaviconGenerator tools):

- https://github.com/IQSS/dataverse/issues/5637#issuecomment-474604330

@oodu are you still interested in this?

**Comment by Asbjoedt** [comment]
Hello, we want to customize our favicon and just want to add this would be a good feature to have through the Native API. We hope this is not off the table yet.

**Comment by pdurbin** [comment]
@Asbjoedt well, since the old/current JSF UI is deprecated in favor of the new/upcoming React UI, would you be willing to create an issue over in that repo? https://github.com/IQSS/dataverse-frontend

**Comment by Asbjoedt** [comment]
yup thank you
