### ISSUE TITLE
Internationalization DCT - Drop down configure button

### ISSUE THREAD

**Issue by lubitchv** [IQSS/dataverse#6748]
Drop Down "Configure" button in Dataverse shows entries of external tools that are taken from the database.  Therefore the name of tools are only shown in English. For Data Curation there is a need to show the name in different languages.

**Comment by djbrooke** [comment]
@lubitchv thanks. Is this something you're planning to work on? If so I'll plan to move it to Community Dev.

**Comment by lubitchv** [comment]
@djbrooke Yes, I am working on this now.

**Comment by djbrooke** [comment]
Thanks @lubitchv!!

While I have you, I just wanted to make sure that you saw my note in https://github.com/IQSS/dataverse/pull/6577#issuecomment-598733687 about the indexing we had to pull out of the upcoming release.

**Comment by lubitchv** [comment]
Yes, @djbrooke . I saw it. I will think how one can optimize it although I do not have solution yet.
