### ISSUE TITLE
API error when trying to insert same username previously deleted

### ISSUE THREAD

**Issue by ffrnioz** [IQSS/dataverse#6749]
Using the native api we are trying to insert an user with a user name that was previously deleted.

**Steps to reproduce:**

- Create an user with the user name: 7b.b.z
- Delete that user.
- Try to create a user with the user name: 7b.b.z

First we check if the user exists using the following uri:
_{server}/api/v1/admin/authenticatedUsers/7b.b.z?unblock-key=xxx_

**Response:**
```
{
    "status": "ERROR",
    "message": "User 7b.b.z not found."
}
```
Than when we try to insert the user name again:
_{server}/api/builtin-users?password=xxx&key=xxx_

**Body Message**
```
{"firstName":"Created","lastName":"Automatically","userName":"7b.b.z","affiliation":"NIOZ Royal Netherlands Institute for Sea Research","position":"Research Data Management","email":"7b.b.z@nioz.nl"}
```
**Error:**
```
{"status":"ERROR","message":"username '7b.b.z' already exists"}
```
**Expected result**
Create new user with the same user name that was deleted before.

Thanks in advance for the help.

**Comment by djbrooke** [comment]
Hey @ffrnioz, thanks for the detailed report and the steps to reproduce. What version did you try this on?

**Comment by ffrnioz** [comment]
Hi @djbrooke our version is the 4.19

**Comment by pdurbin** [comment]
@ffrnioz have you tried this again recently? Are you still on 4.19?

**Comment by ffrnioz** [comment]
Hi Philip;

We are on the v. 4.20 build 413-4e07b62 and yes we still having this error.

**Comment by shlake** [comment]
This still happens on 5.11.1.

when tried to add a new user with a previously (deleted) username, 
`curl -d @user-add.json -H "Content-type:application/json" "$SERVER_URL/api/builtin-users?password=$NEWUSER_PASSWORD&key=KEY-HERE"`
get this error:
{"status":"ERROR","message":"username 'shlakegm' already exists"}

But traces shows nothing:
`curl -H "X-Dataverse-key:$API_TOKEN" -X GET $SERVER_URL/api/users/shlakegm/traces`
{"status":"ERROR","message":"Cannot get traces. User not found."}

**Comment by pdurbin** [comment]
@shlake anything interesting in server.log?

**Comment by shlake** [comment]
Nothing in the log after this displayed: {"status":"ERROR","message":"username 'shlakegm' already exists"}

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
