### ISSUE TITLE
Show differences: Allows more than 2 checkboxes to be selected, then tells you to only select 2.

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#675]
---

Author Name: **Kevin Condon** (@kcondon)
Original Redmine Issue: 4125, https://redmine.hmdc.harvard.edu/issues/4125
Original Date: 2014-06-17
Original Assignee: Gustavo Durand

---

The was reported on 6/4 as a part of a number of versioning issues but opening separate ticket.

User is able to select more than 2 versions to see differences on versions tab but then when click show, a popup says only choose 2. Why not just gray out the rest so user doesn't choose more than 2?

**Comment by mheppler** [comment]
Related to #3241 

Potential solution with AJAX or PrimeFaces Extension proposed on [StackOverflow](http://stackoverflow.com/questions/4550587/primefaces-datatable-need-to-enable-disable-components-based-on-row-selection?rq=1).
