### ISSUE TITLE
Use the translation of a controlled vocabulary in the oai_ddi

### ISSUE THREAD

**Issue by bappun** [IQSS/dataverse#6751]
In our dataverse we use the identifiers of the controlled vocabularies as their value in the TSVs to be able to translate them easily. However these identifiers are not really human readable and are present in the output of the oai_ddi.

Would it be possible to use the translation of the controlled vocabularies in the oai_ddi output instead of their default value (in my case the identifier)?

For example in the oai_ddi output we have:
`<sampProc>TotalUniverseCompleteEnumeration</sampProc>`
But we would like the value present in our languages.zip:
`<sampProc>Total universe/Complete enumeration</sampProc>`

Maybe it is a bit too specific, but if you have any insight I will be glad to read them.

**Comment by djbrooke** [comment]
Hey @bappun, that's a good question. I'll defer to @jggautier (who may defer to a developer) but maybe we remove spaces and non-alphanumeric characters form this output because of interoperability reasons?

**Comment by jggautier** [comment]
Sorry for the late reply @bappun.

I'd like to make sure I understand, using the example you gave: When someone views the English version of your repository, on the metadata edit she sees the English version of the vocabulary terms of the Sampling Procedure metadata field, one of the terms being "Total universe/Complete enumeration", right? And that string is ultimately coming from your repository's languages.zip?

But currently the code that creates the DDI XML export is using the string that's in the metadatablock TSV file, "TotalUniverseCompleteEnumeration", which is supposed to be the language-agnostic identifier for that term?

I agree that "Total universe/Complete enumeration" should be what's used in the DDI xml export, and not "TotalUniverseCompleteEnumeration". But I don't know much about how these language files interact with the TSV files, so I'd have to defer to a developer who's familiar with the internationalization changes over the past couple of years.

**Comment by bappun** [comment]
Hi @jggautier 

You're right. I used identifiers as the vocabulary values in my TSV and I'd like to be able to output their translations in the oai_ddi instead of their values so we can have the oai_ddi in different languages.

Thanks!
