### ISSUE TITLE
API: empty datasets can be created resulting in 502 errors

### ISSUE THREAD

**Issue by MYF95** [IQSS/dataverse#6752]
Hi!

As written in the title, we can create "empty" datasets which in turn returns 502 when we try to access them via the dataverse page.

## How to reproduce
The endpoint used is the one described here http://guides.dataverse.org/en/latest/api/native-api.html#id47

`curl -H X-Dataverse-key:$dataverse-key-value https://demo.dataverse.org/api/dataverses/${dataverse}/datasets --upload-file example.json`

The contents of `example.json` are as follows:
```
{
  "datasetVersion": {
    "metadataBlocks": {
      "citation": {
        "fields": [
        ]
      }
    }
  }
}
```
Which is the bare minimum amount of data allowed to create the dataset.

## Current behaviour
This results in the following dataset being created:

![image](https://user-images.githubusercontent.com/10046051/77101752-b6abfd80-6a0f-11ea-8e13-6a4f66f4bc36.png)

And consequently when trying to enter the dataset page

![image](https://user-images.githubusercontent.com/10046051/77101793-c7f50a00-6a0f-11ea-9709-7e1d81e49658.png)

## Expected behaviour
Dataset is not created in the first place because the required minimum information is not there

or

The dataset page is able to load with no initial information (maybe using some default values if not set?)

We are not really actively using the endpoint, but just wanted to let you guys know since I found this when testing some of our endpoints using dataverse.

**Comment by djbrooke** [comment]
Thanks @MYF95 for the report. We'd want the behavior to be that the dataset would not be created.

**Comment by akio-sone** [comment]
Hi all, I guess this issue is related to #6739 (Multistore: If no files are uploaded to published dataset, export fails).

**Comment by djbrooke** [comment]
Thanks @akio-sone. @MYF95 and the team usually work against demo.dataverse.org, which is running 4.19 and does not have have the multiple stores changes. I think this is unrelated, but could be wrong.

**Comment by djbrooke** [comment]
- We'd want to not allow creation if the required fields are not passed and provide a message over the API. 
- The solution here should include the validation and not just fail if it's empty
- This may be just a Solr record being created

**Comment by poikilotherm** [comment]
I just came across this issue and I think this is (at least) related to my #7173
