### ISSUE TITLE
Create Dataset: On slower systems, spinner changes focus to parent dv causes typos, input error

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#6754]
This is especially noticeable on slower systems or if you are a faster typist. When you go to create dataset page, the focus is on title and you begin typing but then a spinner appears, changes focus to parent dv edit box and you find your typing is now appearing there. Since that field is prepopulated, you have now messed up the name of the parent dv and you may not know it, causing problems with create. Really annoying, btw.

**Comment by BPeuch** [comment]
Yup. I experienced just the same thing, on different navigators and both on my local DV installation and on Demo Dataverse.

The worst thing being that, once you have filled in all the fields and added your files, when you click on `Save Dataset`, a white transparent frame covers most of the page and, as far as I could manage with tests, the metadata content you created is lost.

**Comment by TaniaSchlatter** [comment]
Closing in favor of #6772, as the proposed solution for that issue will address this issue.
