### ISSUE TITLE
Can't publish datasets

### ISSUE THREAD

**Issue by PhoenixZCS** [IQSS/dataverse#6758]
Hello,

I encountered the same situation as this issue [#5297](https://github.com/IQSS/dataverse/issues/5297). But after I configured the test datacite account and DOI prefix, I still can't publish datasets. 

Error – Command：
`This dataset may not be published due to an error when contacting the DataCite Service.`

`Caused by: java.lang.RuntimeException: Response code: 403, Access is denied` is the main error in server.log.

Here are my configuration options for DOIs:
><jvm-options>-Ddoi.username=DEV.XWJSSE</jvm-options>
        <jvm-options>-Ddoi.password=$myPassword</jvm-options>
         <jvm-options>-Ddoi.mdcbaseurlstring=https://api.test.datacite.org</jvm-options>
        <jvm-options>-Ddoi.baseurlstring=https://mds.test.datacite.org</jvm-options>
        <jvm-options>-Ddataverse.siteUrl=http://localhost:8080</jvm-options>

And here are my Database Settings:
> DoiProvider: DataCite
Protocol: doi
Authority: 10.0355
Shoulder: FK2/

Is there any config wrong? 

Thanks.

**Comment by donsizemore** [comment]
Hi @PhoenixZCS 

I believe your siteUrl must be set to the FQDN of your Dataverse service. Update that setting, restart Glassfish, then try to publish again?

**Comment by PhoenixZCS** [comment]
Hi @donsizemore 
Thanks for your help. I tried to set siteUrl to http://39.101.198.19:8080. It doesn't work.

**Comment by donsizemore** [comment]
@PhoenixZCS have you verified your credentials with DataCite? (can you sign in to https://doi.test.datacite.org/ ?)

I vaguely remember DataCite requiring https on the client side, but don't quote me on that.

**Comment by PhoenixZCS** [comment]
@donsizemore 
Oh! On this website, I found that the dataset information has been submitted to datacite.  And datacite has already generated doi for the dataset. 
But It makes me feel confuesd that why dataverse reported the error and the dataset is still unpubished？

![%~A$($Q50N}@IYDQ)LNVV%0](https://user-images.githubusercontent.com/40781727/77326706-29d9aa80-6d55-11ea-8176-91ecde5afcee.png)

**Comment by donsizemore** [comment]
@PhoenixZCS Ah! In your screenshot it looks like you're using handles, but above you have  http://guides.dataverse.org/en/latest/installation/config.html?highlight=protocol#protocol set to 'doi' rather than 'hdl'. See if that doesn't fix things?

**Comment by PhoenixZCS** [comment]
@donsizemore Sorry, I don't know what is handles. But I have configured the protocol. I just tried it again and It still doesn't work.

**Comment by PhoenixZCS** [comment]
@donsizemore I just cteated a new dataset and it can be published now. Thanks a lot. Maybe the reason why the first dataset can't be published is that it was created before i set the protocol.

**Comment by youssefOuahalou** [comment]
Did you make this curl command? : 
curl -X PUT -d **10.0355** http://localhost:8080/api/admin/settings/:Authority
there is already your **:Authority**
