### ISSUE TITLE
Record the date of a deaccessioning

### ISSUE THREAD

**Issue by BPeuch** [IQSS/dataverse#6759]
Version: 4.19

Hello everybody,

We think it would be good practice to save the date when a dataset was deaccessionned. If I'm not mistaken, it is currently not recorded within a dataset's metadata (which, after a deaccession, are preserved in a tombstone landing page).

In version 4.19, the metadata of deaccessioned datasets feature 2-n dates by default:

1 • Publication date (also date of first version)
2 • Deposit Date
(3-n • Dates of subsequent versions)

**Comment by djbrooke** [comment]
Thanks @BPeuch, this does seem like a good idea.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
