### ISSUE TITLE
For Make Data Count, "requests" should be a subset of "investigations", not mutually exclusive

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#6760]
This issue is for confirming a discrepancy between what COUNTER considers "requests" and "investigations" and what activities Dataverse is putting into each category (metric type), and, if there is a discrepancy, tracking a solution for it.

@qqmyers looked briefly at some of the code that generates MDC reports and it seems that Dataverse is treating several API calls as "investigations" and treating calls related to downloads/explores separately as "requests". But from what I've read, "investigations" should include all activity, including "requests". "Requests" should be a subset of "investigations".

Adding what @qqmyers found from a brief look:

> Once things are logged, the counter-processor-config.yaml file decides which URLs are counted as investigations versus requests:
> 
> investigations:
>     - ^.*/dataset.xhtml\S*$
>     - ^.*/file.xhtml\S*$
>     - ^.*/api/datasets\S*$
>     - ^.*/api/v1/datasets\S*$
> 
>   requests:
>     - ^.*/api/access/datafile\S+$
>     - ^.*/api/v1/access/datafile\S+$
> 
> which is again consistent – page views and non/access/ API calls are investigations

**Comment by qqmyers** [comment]
@jggautier suggested just adding the two paths under requests: above to investigations: to address this. I think that could work if the mdc logs were reprocessed. I have not checked to see if the Dataverse mdc db entries get updated if they change upon reprocessing. (same for DataCite, but I'm pretty sure one can replace reports sent to them.)

(More generally, but useful here - it would be nice to have a test log and the results one expects in the db at the end to verify that processing is doing what it should. )

**Comment by qqmyers** [comment]
I just tried the change above at QDR and looked through the code - Dataverse does completely replace the entries when you reingest a report - as long as the dataset, date (beginning of the month being reported), and country code for a given entry aren't changed. That means that the change above, which just adds counts would be OK (but going the other way wouldn't - i.e. a machine download from a given country wouldn't necessarily be removed from the investigations count unless there were also investigations from that country).

I still haven't checked the datacite part but I recall from the guides (discussing MDC testing) and DataCite docs that you can remove/replace a report. I plan to test this soon, but I'm not sure its worth waiting to get a PR in on this.

**Comment by qqmyers** [comment]
@jggautier - looking more closely, I think it is working correctly now - adding the lines above to the investigations just drops them from being counted as requests/downloads. https://github.com/CDLUC3/counter-processor/issues/1 and a commit prior to that in Aug 2018 addressed this in counter-processor.  So, while their comments/naming could use improvement, I think the counting is working per spec with the current config and this issue can be closed.

**Comment by jggautier** [comment]
Thanks for testing, @qqmyers! Closing this issue.
