### ISSUE TITLE
Direct S3 Upload: Files >5GB cannot be uploaded to AWS, need to be segmented

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#6763]
A limitation of AWS with the direct s3 upload approach we are using is it cannot support more than 5GB. So, files >5GB would need to be segmented and uploaded in pieces, then reassembled.

**Comment by qqmyers** [comment]
I've managed to generate presigned URLs for multiple file parts in Dataverse, use those URLs to upload parts of a file and signal completion of the multipart upload, and then add the file to the dataset. Only generating the URLs and telling S3 that the multipart upload is complete are in the API - the other steps are by Curl for now - things that the javascript will need to do for the UI upload or that the DVUploader will do.  However, I think that proves the concept, so nominally its just a smop at this point.
