### ISSUE TITLE
Import DDI: Ignores supplied doi on command line, utilizes one of 2 doi entries in ddi.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#6764]
The import DDI endpoint does not behave the way it is documented in the Guides.
First, it ignores a supplied doi on the command line.
Second, it instead uses the doi provided in the stdyDscr section of the DDI, if provided.
Third, if a doi is provided in the stdyDscr and it exists in the system, in the case of using an exported DDI as import file, the import  fails with  "already exists" error message on the command line but nothing in the log file. This could be argued to be as designed -it detects the doi you want to create already exists and is maintaining uniqueness but maybe better messaging and/or a log entry saying what doi it was trying to create and that it already exists in the system?

Note that you can import a DDI by specifying a doi in the stdyDscr section, but currently it is in the ddi file only and of course cannot exist in the system, must be unique

**Comment by BPeuch** [comment]
Could this be related to #5467?
