### ISSUE TITLE
document local-storage-to-S3 database queries

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#6771]
I've suggested example SQL queries in a "Storage Migration to S3" sub-heading at the bottom of the [Useful SQL Queries](https://docs.google.com/document/d/1-Y_iUduSxdDNeK1yiGUxe7t-Md7Fy965jp4o4m1XEoE) page.

If @landreev @qqmyers and other interested parties could please take a look and approve or correct the queries, I'll ask someone with editing rights to accept the suggested edits and convert the S3 ToC entry to an in-document paragraph link.

Finally, I'll submit a pull request to document this process at the bottom of the [Developer Deployment Page](http://guides.dataverse.org/en/latest/developers/deployment.html) (for lack of a better place?).

**Comment by qqmyers** [comment]
They look good to me. I wasn't sure why the second datafile query doesn't check for harvestingclient like the first one though.

**Comment by landreev** [comment]
Good catch @qqmyers - the only reason the second query doesn't bother to skip harvested files is that the actual test case dataverse we were trying these on didn't have any.

**Comment by landreev** [comment]
Can't quite think of a better place for this instruction either, just yet. But let me look around (developers/deployment should be fine; but maybe add a link to it to some place in the admin guide? - let me think...)

**Comment by landreev** [comment]
This may be nit-picking, but the wording in the doc may suggest that they only need to run one of the 2 datafile queries, depending on which Dataverse version they are on currently. I would remove the references to the version, and just say, run these 2 queries; the first one will catch all the storageidentifiers with the "file://" prefix, the second one the remaining ones without.
