### ISSUE TITLE
Typeahead widget on Link Dataset popup is slow and doesn't display all options as expected

### ISSUE THREAD

**Issue by TaniaSchlatter** [IQSS/dataverse#6772]
The type ahead feature on the Linking popup is slow to respond to user input. Also, if a user types quickly, not all results that include what has been typed in are shown. This is problematic because it looks like not all results are returned.

All items that include "Tania Schlatter Dataverse": 
<img width="1190" alt="Screen Shot 2020-03-26 at 2 18 31 PM" src="https://user-images.githubusercontent.com/15386424/77683192-6e8c5e00-6f6e-11ea-9c63-74e871c394f5.png">

What is shown when I type "Tania Schlatter Dataverse". "Tania Schlatter Dataverse" is not shown:
<img width="1195" alt="Screen Shot 2020-03-26 at 2 18 42 PM" src="https://user-images.githubusercontent.com/15386424/77683201-70eeb800-6f6e-11ea-9374-89f3e226311c.png">

The typeahead for super users is more responsive and accurate:
<img width="898" alt="Screen Shot 2020-03-26 at 2 20 32 PM" src="https://user-images.githubusercontent.com/15386424/77683200-70eeb800-6f6e-11ea-9cb4-9dd27c334a00.png">

<img width="1167" alt="Screen Shot 2020-03-26 at 2 20 38 PM" src="https://user-images.githubusercontent.com/15386424/77683197-70562180-6f6e-11ea-8a2f-e664a4657bdd.png">

**Comment by TaniaSchlatter** [comment]
Possibly related to #6754

**Comment by TaniaSchlatter** [comment]
In the design meeting we discussed addressing this by removing the typeahead, and providing more robust functionality for finding Dataverses you can add to in a popup. 

The idea is that Harvard or other open installation users, who can deposit to Root, see the option to change the default Dataverse and add a template in a new block, below. "Edit" will open a popup (mockup to come). 

<img width="1027" alt="Create_dataset_revised2" src="https://user-images.githubusercontent.com/15386424/78172045-637c7680-7423-11ea-8b32-6bb5452e3c4b.png">

We need further discussion to figure out what happens for installations who's users can not add to the Root dataverse. We discussed that the Add Data button should not appear in the header for installations who's users who can not add to Root (related to #6708).

There are 4 user states that relate to the Add Data button in the header. We need to figure out how those states relate to and might affect this proposed approach.

1. User can not add to Root = no "Add Data" button in header.
– Might the user see the "Dataverse Details" block, but only the "Dataset Template" field?

2. User can add dataverses but not datasets to Root = "Add Data" button in header with only "Add Dataverse" option.
– Need to look into implications for the Add Dataverse page. 

3. User can add Datasets but not dataverses to Root = "Add Data" button in header with only "Add Datasets" option.
– Does the mockup work for this scenario, but the user can not edit the dataverse?

4. User can add Dataverses and Datasets to Root (Harvard) = "Add Data" button in header with both options – what we have now
– User sees proposed mockup as shown.

**Comment by scolapasta** [comment]
FWIW, #2 is fine for any installation - you just wouldn't see the root amongst und your options.

**Comment by scolapasta** [comment]
One minor drawback to this - if you can only deposit to one dataverse (say you are new on Harvard dataverse, so can only deposit to the root), then you would go to the popup and see no more than the one result. i.e. nothing to change to. (and we can't do something like only show the edit if you can multiple, because then we're back to the having to check every dataverse issue)

**Comment by djbrooke** [comment]
- Revisit "Dataverse details" terminology
- Show Dataverses that can be linked into without a search if the person only has one Dataverse

**Comment by TaniaSchlatter** [comment]
@scolapasta I think we can live with the drawback, especially if we can show results without running the search.

**Comment by TaniaSchlatter** [comment]
Rough mockups, one showing "Linking" use case, and one showing adding a dataset use case, with  functionality needed: title and messaging that depends on the use case, search, results, ability to select a result, and save/cancel. Not shown: the proposed dataset template selection, showing dataverses based on permissions without running a search.

Link use case:
<img width="358" alt="Screen Shot 2020-04-15 at 1 09 22 PM" src="https://user-images.githubusercontent.com/15386424/79376191-cee83d00-7f27-11ea-87d8-e25e10ea95e6.png">

Add use case w/o template selection:
<img width="631" alt="Screen Shot 2020-04-15 at 1 09 07 PM" src="https://user-images.githubusercontent.com/15386424/79376192-cf80d380-7f27-11ea-9758-7e2b52157a85.png">

**Comment by scolapasta** [comment]
While this component is going away with the proposed solution, I just want to add that @kcondon ran into another issue while testing PF8 (not related specifically to PF8):

"Host Dataverse type ahead/lookup logic not working after lookup failure/correction on create dataset page. Does not try again. Update: This is now also broken on develop branch, was working recently."

**Comment by kcondon** [comment]
To follow up on the above comment, the issue appears to be with individual dv's rather than root, where "Dataverse" is added to the name. If you removed "Dataverse" on the edit dataset page, the lookup begins working again. This quirk does not happen with root dv.

**Comment by djbrooke** [comment]
Inventory of type ahead widgets:

- Dataverse selection for Host Dataverse on dataset create
- Dataverse selection for Host Dataverse on dataverse create
- Dataverse selection for Linking Dataverses
- Dataverse selection for Linking Datasets
- Dataset Moving on Dashboard (note no permission needed because of superadmin status)
- Harvesting Client Dataverse selection (note no permission needed because of superadmin status)
- User/Group selection for assigning roles to a dataverse, dataset, or file
- User/Group selection for adding to a group

**Comment by TaniaSchlatter** [comment]
Mockup to review:
[Typeahead changes (create and link).pdf](https://github.com/IQSS/dataverse/files/4724579/Typeahead.changes.create.and.link.pdf)

**Comment by TaniaSchlatter** [comment]
We reviewed work in progress, and agreed to pause this effort. Proposed solutions add complexity. We are interested in looking into different approaches, for example, what if users create a dataverse or dataset first, and then associate it with a dataverse?

Discussed:

- Users: users who are adding a dataverse or a dataset who do not know in advance what dataverse they want to add to, or if they want to add to a dataverse other than root, are more likely to be "unaffiliated," meaning, not associated with an existing user group, such as a course, lab, or journal. 

- Information: Q: what do unaffiliated users need to know to make an informed decision about where to create a dataset/dataverse? A: what dataverses they can create in, and maybe  characteristics of those dataverses, such as associated metadata templates.

- Goal: what do we want to facilitate? For Harvard Dataverse,  do we want unaffiliated users to create datasets/dataverses in the root, or do we want to help them add to an exisitng dataverse within root?

- System: if we think of creating/using/adding as actions that happen in a system, the elements of the system are dataverses and datasets, and the actions are "nesting" (creating a dataverse or dataset within a dataverse) and "linking" (associating a dataverse or dataset with a dataverse).

- Experience: we believe, and test participants believe, that there is value in creating containers of data. Making it easy to create containers and organize data will provide value. Users need to be able to make informed decisions about their groups, and/or, easily be able to change them themselves to have a good user experience.

**Comment by TaniaSchlatter** [comment]
Ideally we want to use a typeahead/dropdown for users to select a dataset and dataverse, rather than a different method. This issue should be helped by resolving this one: Optimize permission lookups for a user #6467.

**Comment by scolapasta** [comment]
Link Dataverse and Link Datasert (both which show you DV collections) have different UI/UX. We should determine one that we end up using for both (once the backend permisisons work is compete):

See https://github.com/IQSS/dataverse/issues/9092

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
