### ISSUE TITLE
Integration Tests Failing

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#6776]
https://jenkins.dataverse.org/job/IQSS-dataverse-develop/397/testReport/ is reporting that there are three integration tests failing:

edu.harvard.iq.dataverse.api.FilesIT.testReplaceFileBadJson
edu.harvard.iq.dataverse.api.FilesIT.test_006_ReplaceFileGood
edu.harvard.iq.dataverse.api.FilesIT.testForceReplaceAndUpdate

**Comment by qqmyers** [comment]
I think I've got it - PR soon
