### ISSUE TITLE
Bug with Manage Permissions - Edit Access

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#6777]
If trying to edit access of a dataverse where "When a user adds a new dataset to this dataverse, which role should be automatically assigned to them on that dataset?" is set to contributor, it is not selected, and you cannot change the other question.

If it is set to Curator, it cannot be set to Contributor.

**Comment by scolapasta** [comment]
This is most likely due to our changing the backend name of the role from "editor" to "contributor". Should be an easy fix.

PR incoming.

**Comment by kcondon** [comment]
@scolapasta Not sure what the 2 test cases are here. 
1. When initially created, no inherited role set in ui, though it is actually contributor?
2. If then change to be curator, can no longer switch back to contributor?

If the above are the two cases, then yes, this is fixed.

**Comment by scolapasta** [comment]
Yes, those were the cases. (1 also had an issue that you couldn't change the answer to the other question)
