### ISSUE TITLE
Deaccessioning a Dataset - Select all versions

### ISSUE THREAD

**Issue by tainguyenbui** [IQSS/dataverse#6780]
Hi Dataverse team, I will drop here a suggestion for deaccessioning datasets. Thanks!

**Given** that I am a user
**When** I attempt to deaccession a dataset
**Then** I should be able to select all versions with one click

**Current behaviour**
The user should select all versions one by one

![Screenshot 2020-03-30 at 14 47 30](https://user-images.githubusercontent.com/4402762/77919961-c04a2680-7295-11ea-9a4e-3931c4b8687c.png)

**Expected behaviour**
The user should be able to click a "select all" button that will allow them to easily select all versions

**Dataverse version**
v. 4.19 build 331-affbf4f

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
