### ISSUE TITLE
Manage Groups - Dialog popup does not close on save, action saved by system

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#6792]
On the Manage Groups pg, when editing an existing group in the Dataverse Group popup, the Save Changes btn silently saves the action, but does not close the popup. Checking the console, there is this XML parsing error when you click Save Changes.

```
XML Parsing Error: mismatched tag. Expected: </update>.
Location: .../manage-groups.xhtml?dataverseId=####
Line Number 150, Column 3:
```

There was also a console error `ReferenceError: handle_dropdown_popup_scroll is not defined` on the Manage Groups pg when it loads (#5653), but that does not appear to be related.

@kcondon initially discovered this on a test server, but could not reproduce it on another test server. One major difference between these two machines was the analytics button click event tracking code (http://guides.dataverse.org/en/4.20/installation/config.html#tracking-button-clicks) that was set up on the machine throwing the errors.

This bug is not on demo (4.19, no analytics), but it is on production (also 4.19) where the analytics event tracking code was added last month.

**Comment by pdurbin** [comment]
I can't reproduce this on develop (I'm on 3da9c4018) so I'm sending this to QA to confirm. I tried Firefox and Chrome. In both cases, clicking "Create Group" closed the popup and I was left with a screen like this:

<img width="998" alt="Screen Shot 2020-11-04 at 12 00 00 PM" src="https://user-images.githubusercontent.com/21006/98142052-5336e900-1e95-11eb-9f7a-6e1ed63f272e.png">

**Comment by pdurbin** [comment]
In production on edit (not create) I was able to get the `XML Parsing Error: mismatched tag. Expected: </update>.` error when clicking "Save Changes":

<img width="2032" alt="Screen Shot 2020-11-04 at 12 26 49 PM" src="https://user-images.githubusercontent.com/21006/98147055-06094600-1e9a-11eb-93a2-a95a868404da.png">

Thanks to @djbrooke for pointing out the bit about Google Analytics above. I'll keep digging.

Something else that struck me (I haven't used groups much) is that you can enter a description when you create a group but you can't edit or even see the description when you edit it. The description doesn't appear in the table either.

**Comment by djbrooke** [comment]
Thanks @pdurbin !!
