### ISSUE TITLE
Publish Command: Command should check current dataset lock status before publishing to avoid a potentially stale read.

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#680]
---

Author Name: **Kevin Condon** (@kcondon)
Original Redmine Issue: 4130, https://redmine.hmdc.harvard.edu/issues/4130
Original Date: 2014-06-18
Original Assignee: Gustavo Durand

---

This ticket was requested by Gustavo.

When the publish command is called, it should not assume it is ok to publish a study but instead check the lock status of the dataset in case somehow the user has a stale read of the dataset state and should not be allowed to publish.

**Comment by pdurbin** [comment]
I fixed this in 5fc191b.
