### ISSUE TITLE
update Jenkinsfile to publish Pull Request test results

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#6814]
the pull request will get a rubber stamp:

<img width="740" alt="Screen Shot 2020-04-13 at 13 58 14" src="https://user-images.githubusercontent.com/12831666/79147886-ad098180-7d92-11ea-9b4c-e22ba3193a9b.png">

"Details" links to a nominally-useful landing page, which contains a "Tests" heading leading to the actual test results. it's a start.

**Comment by poikilotherm** [comment]
You might be interested in my pipeline function.

https://github.com/IQSS/dataverse-kubernetes/blob/5accd2de4764b80d43359a8747f63f09d10b5f96/docker/dataverse-k8s/Jenkinsfile#L1-L9
