### ISSUE TITLE
edu.harvard.iq.dataverse.sitemap.SiteMapUtilTest.testUpdateSiteMap failing intermittently

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#6820]
edu.harvard.iq.dataverse.sitemap.SiteMapUtilTest.testUpdateSiteMap has been failing intermittently over the last few test runs on dataverse.org Jenkins (407 is one build where this occurs). We should determine why this is occurring and get our test suite healthy.

**Comment by pdurbin** [comment]
I just created pull request #6822 to fix this.
