### ISSUE TITLE
Add Dataset - After upload file complete, browser jumps to top of page

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#6823]
Seen on Demo Dataverse and Harvard Dataverse running Dataverse version 4.20, on the newest versions of Chrome and Firefox:

On the dataset create page, the file upload section is at the bottom of the page. When uploading a file in a new dataset, once the file is uploaded, the dataset create page jumps to the top or near the top. Depositors have to scroll back down to click the Save Dataset button.

Is this jumping behavior by design? Since the file upload section is at the bottom of the page, isn't file uploading the last step before saving the draft dataset? Or is jumping to the top encouraging people to review the metadata they've entered while scrolling back down to save the dataset?

**Comment by djbrooke** [comment]
I don't think this is by design. :) That's weird. IMHO we should fix. Will move this to the board.

**Comment by donsizemore** [comment]
FWIW I'm seeing this on Payara5 as well (primefaces8 branch just now)

**Comment by mheppler** [comment]
Took a peek into this, and I believe the reloading of the entire form at Line 285 of editFilesFragment.xhtml is causing the page to jump.

```
<p:commandButton id="AllUploadsFinished" 
    action="#{EditDatafilesPage.uploadFinished()}"
    update="@form,datasetForm:fileUpload,datasetForm:dropBoxUserButton,datasetForm:uploadMessage,datasetForm:rsyncPanel,datasetForm:filesCounts,datasetForm:filesTable" 
    oncomplete="javascript:bind_bsui_components();javascript:uploadWidgetDropMsg();" 
    style="display:none"/>
```

That `@form` in the hidden button update was added by @sekmiller in 8dffc46bbdc9e8782efcdb82c8c974411ca39385 as part of the dual mode work in issue #4610. It looks to be a pretty convoluted series of elements listed in all those various hidden commandButton update attributes, so I'm just gonna leave this in Up Next and ask Stephen to take a peek in more detail when he has a chance.
