### ISSUE TITLE
Can't download files of dataset

### ISSUE THREAD

**Issue by ipcraiurosario** [IQSS/dataverse#6827]
Hello everyone, 

I hope you guys are doing good and taking care of your health!!

As the title of this issue says, I can't download files of my datasets.

To put you guys in context, our university has a production dataverse (version 4.9.4) that's working fine. However, in order to make some tests we decided to install the same version of dataverse on a development server.

With that being said, we are having some troubles making it work smoothly, two of those errors goes as follow:

1 when we try to download a file from a dataset (unpublished):

![image](https://user-images.githubusercontent.com/53486765/79473738-2986a500-7fcb-11ea-8dc1-0b5d85b99428.png)

we get the following error: 

{"status":"ERROR","code":403,"message":"'/api/v1/access/datafile/120' you are not authorized to access this object via this api endpoint. Please check your code for typos, or consult our API guide at http://guides.dataverse.org."}

2. when we try to download multiple files from a dataset:

![image](https://user-images.githubusercontent.com/53486765/79473937-6eaad700-7fcb-11ea-9fd8-2e8cd904b7df.png)

we get the following error:

{"status":"ERROR","code":404,"message":"'/api/v1/access/datafiles/113,114,118' Datafile null: no such object available"}

Any ideas on how to make this work? as I said before, our production dataverse is working fine.

Thanks in advance!

**Comment by juancorr** [comment]
Hi,

  are your files in a local file system?. If the file system is local, have
the Glassfish access to the files?. Files could be under
/usr/local/glassfish4/glassfish/domains/domain1/files/ if you have
installed Dataverse in the default path.

  Best,

Juan Corrales

**Comment by ipcraiurosario** [comment]
Hi Juan, sorry for the delay.

Glassfish has access to the files, as shown in the following image 

![image](https://user-images.githubusercontent.com/53486765/79898254-94bbe700-83d0-11ea-9239-cdf45c7e5048.png)

However, I can't download files from the platform.

once again, sorry for the late response and thanks for the help!

**Comment by pdurbin** [comment]
@ipcraiurosario hi, nice chatting with you the other day in IRC. I'm not sure if your dev server only has copies of files from production.

On your dev server, if you create a new dataset and upload a file, can you download it?

**Comment by ipcraiurosario** [comment]
@pdurbin Hi, we've indeed created a new dataset on our dev server, but as I said when we spoke last week, we're not able to download the files of the dataset.

**Comment by ipcraiurosario** [comment]
Hi guys!... I was wondering if there's some kind of workaround to this issue

**Comment by pdurbin** [comment]
@ipcraiurosario I'm afraid I'm out of ideas. Could you please email support@dataverse.org? Thanks!

**Comment by djbrooke** [comment]
Hi @ipcraiurosario - I'm going to close this out, hopefully it was resolved as part of #7270
