### ISSUE TITLE
Metrics: DisplayMDCMetrics mouseover doesn't work w/ MDC enabled, not true by default contrary to doc.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#6831]
The gray banner labeled, Dataset Metrics has a ? mouseover next to it. It works when :DisplayMDCMetrics is false or not defined but you need to actively click it to work when it is set to true.

While testing discovered  that the default for DisplayMDCMetrics is not true, at least in terms if Display Metrics render, as described in Make Data Count guide: http://guides.dataverse.org/en/4.20/developers/make-data-count.html#testing-make-data-count-and-dataverse

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
