### ISSUE TITLE
MyData: Publication Status and Role checkbox filters do not filter datasets.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#6833]
Clicking on any of the publication status or role checkboxes does not seem to filter datasets but does filter dataverses. Example, unchecking unpublished will remove unpublished dataverse but unpublished datasets remain. Same with unchecking admin role, etc.

**Comment by djbrooke** [comment]
Hey @kcondon, I couldn't reproduce this on demo. Is it just broken on develop (may be related to #6802 merge?)?

#6834 is broken on demo.

**Comment by kcondon** [comment]
@djbrooke Yes, it appears to work in 4.20 and introduced in Develop. Not sure when though.

**Comment by djbrooke** [comment]
@kcondon -- @scolapasta and I weren't able to reproduce this on a develop build from yesterday and it's working as it does in 4.20. I'm going to close based on this, but feel free to retest and reopen if you have the cycles.
