### ISSUE TITLE
MyData: Clicking on draft version of dataset takes user to published version

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#6834]
If a published dataset has a draft version and it appears in MyData, clicking on that takes the user to the published version instead.

**Comment by mheppler** [comment]
@kcondon, @djbrooke this appears to be a duplicate of **Draft Version URL Problem in "My Data" #3038**.

**Comment by djbrooke** [comment]
Thanks @mheppler. I'd still like to work on #5696 as a general rearchitecture, but thanks for the quick fix in the PR #6969

**Comment by mheppler** [comment]
@djbrooke I agree 100%, that PR is a minor repair on bridge to that effort. Closing this issue a duplicate.

**Comment by kcondon** [comment]
@mheppler @djbrooke Yes, it looks like a duplicate.
