### ISSUE TITLE
# Fix ```.partae``` files with unknown content types   - Change extension ```.partae``` to contenttype ```.tar.gz```:

### ISSUE THREAD

**Issue by jatinrajani** [IQSS/dataverse#6841]
Thank you for contributing an issue to the Dataverse Project! If this is a bug report, please let us know when the issue occurs, which page it occurs on, to whom it occurs, and which version of Dataverse you're using. If this is a feature request, please let us know what you'd like to see and give us some context - what kind of user is the feature intended for, the relevant use cases, and what inspired the request? No matter the issue, screenshots are always welcome.

**Comment by djbrooke** [comment]
Hi @jatinrajani, can you provide more information about your request? Are you asking for these files to be updated in Harvard Dataverse, or for another installation, such as your own? 

Would you be able to make a pull request?

**Comment by djbrooke** [comment]
Hi @jatinrajan, I'm going to close this, but please comment here with more information and I can re-open it.
