### ISSUE TITLE
Deaccession user role breaks "My Data" page

### ISSUE THREAD

**Issue by kaitlinnewson** [IQSS/dataverse#6843]
Hi IQSS Team! 

We're in the process of upgrading to 4.19 at Scholars Portal and have encountered a bug that stops the 'my data' results from loading.

**Version(s)**:
 Tested in 4.19 (at demodv.scholarsportal.info) and 4.20 (at demo.dataverse.org).

**Page it occurs on:** 
"My Data" (e.g. https://demo.dataverse.org/dataverseuser.xhtml?selectTab=dataRelatedToMe)

**Steps to reproduce:**
1. Create a new dataset and publish it
2. Add another account as a "Contributor" to this dataset (may happen for other roles too, only tested this one)
3. Deaccession the dataset
4. Login as the other account that was given permissions in step 2, and go to the "My Data" page
5. See a loading spinner for the results, and a `Failed to load resource: the server responded with a status of 500 (Internal Server Error)` error in the console (Chrome); issue is resolved if that user's roles are cleared in the superuser-only users dashboard.

**Screenshot(s):**
![Screen Shot 2020-04-20 at 12 03 12 PM](https://user-images.githubusercontent.com/6903515/79773161-117e9080-82ff-11ea-8106-a214372f7925.png)

**Additional information:**
According to our developer @suniluoft, "Deaccessioned versions are not handled, it throws an error. It's trying to find keywords for a datasetversion that does not exist. By datasetversion doesn't exist, I mean it tries to find only latest draft version or released version".

Let me know if you need any additional information!

**Comment by kaitlinnewson** [comment]
Additionally, if "Deaccessioned" is unchecked in the facets under "Publication Status", then the page loads normally.

**Comment by djbrooke** [comment]
Thanks @kaitlinnewson. A few other bugs have cropped on MyData recently (#6833 and #6834).

@scolapasta, I'm going to move #5696 onto the board for us to investigate. MyData is getting to be a maintenance burden. It would be good to get this aligned with the rest of the codebase so that we (hopefully!) have fewer issues.

**Comment by BPeuch** [comment]
Thank you very much for your post, @kaitlinnewson. My coworker @youssefOuahalou and I think that you've pinpointed what's been a thorn in our side as well (issue https://github.com/IQSS/dataverse/issues/6781).

We've been struggling to remove entirely a deaccessioned dataset, so it's been straggling around for some time, and now we think that it might be the reason why the ```My Data``` doesn't dispay correctly on one of our Dataverses (no such problem on the other one). Like you, we unchecked the box for deaccessioned datasets and, sure enough, the results then displayed without problems.

**Comment by kaitlinnewson** [comment]
That's great @BPeuch - it was definitely tricky to figure out the cause, as some user accounts would have the issue but not others.

**Comment by shlake** [comment]
This is great!! Means "My Data" should work for my users (except me, who has a Deaccession'd dataset - and of course admin who sees "all")

**Comment by sekmiller** [comment]
Fixed by https://github.com/IQSS/dataverse/issues/6781
