### ISSUE TITLE
Create Datavese: Timed out session still allows access to add dataverse but saving form results in permissions error.

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#685]
---

Author Name: **Kevin Condon** (@kcondon)
Original Redmine Issue: 4135, https://redmine.hmdc.harvard.edu/issues/4135
Original Date: 2014-06-19
Original Assignee: Gustavo Durand

---

Tested on 6/19

Was logged in as a pete but session timed out. Didn't notice and could still add dataverse but threw permissions error relating to guest on  save.

**Comment by eaquigley** [comment]
Sending to QA to retest. @kcondon

**Comment by kcondon** [comment]
With such a long timeout, this is no longer a practical issue. Closing.
