### ISSUE TITLE
Move from IQSS Jenkins to new CI solution

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#6850]
The current Jenkins box at IQSS will soon no longer be supported. We should move to the another solution, possibly the already-available jenkins.dataverse.org.  

Creating an issue to capture any discussion or process changes needed around this transition.

**Comment by djbrooke** [comment]
@kcondon thanks Kevin for all the work moving this over. Is this one all done or is there still some work to be done?

**Comment by kcondon** [comment]
@djbrooke It looks like we're good.
