### ISSUE TITLE
Confirm file deletion in a pop-up window

### ISSUE THREAD

**Issue by philippconzett** [IQSS/dataverse#6858]
As a depositor, I'd like to be required to confirm file deletion in a pop-up window.

**Comment by pdurbin** [comment]
@philippconzett not a lot of chatter on this issue. 😄 

Are you still interested in this?

If so, we might want to make the popup configurable, in case people don't like it.

Also, if I accidentally delete a file in a post-publication draft, I can always delete the whole draft and start over. So at least we have that safeguard. Better than nothing.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
