### ISSUE TITLE
Dataset under unpublished dataverse is published

### ISSUE THREAD

**Issue by Venki18** [IQSS/dataverse#6861]
We have an issue with publishing of datasets, when both the dataverse and dataset are unpublished, and we click publish on the dataset page, there is a prompt that shows “Both dataverse and dataset will be published” but only the dataset gets published and the dataverse stays unpublished. We are running v4.17 and we are facing this issue only recently. 

Added information: Our institution has implemented Web Application Firewall (WAF) since April 2020, not sure whether it is related.

**Comment by pdurbin** [comment]
@Venki18 when you get into this state where the dataset is published but its parent dataverse is not, are you able to fix it by publishing the parent dataverse? Or is impossible to publish the parent dataverse?

**Comment by Venki18** [comment]
@pdurbin We were able to publish the parent Dataverse without any issues. We are not sure what is causing the behavior.

**Comment by pdurbin** [comment]
@Venki18 this is very strange behavior but I'm not aware of any reports of it. What do you think? Close it? You could always open a fresh issue if it happens again.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
