### ISSUE TITLE
Bug in ApplicationTermsOfUse API

### ISSUE THREAD

**Issue by Venki18** [IQSS/dataverse#6862]
I tried to update the ApplicationTermsOfUse API to upload a html file and failed. Followed the instruction provided in the [guide](http://guides.dataverse.org/en/latest/installation/config.html#id163).

`curl -X PUT -d@/tmp/apptou.html http://localhost:8080/api/admin/settings/:ApplicationTermsOfUse ` 

 But when I used the language specific Terms of Use file for English as below and IT WORKED.

`curl -X PUT -d@/tmp/apptou.html http://localhost:8080/api/admin/settings/:ApplicationTermsOfUse/lang/en`

I think there is a bug in the API.

**Comment by pdurbin** [comment]
I'm not aware of a bug but there certainly could be. Language support for settings was added in pull request #6042. Perhaps a bug crept in later.

**Comment by qqmyers** [comment]
Good catch! See #7189 - it looks like your first upload will set the terms for the server's defaultLocale/language, but any visitors using a different locale/language would see the default from the system.app.terms Bundle.properties entry. The second would set the terms only for people using a locale with the 'en' language.

We're still discussing the best fix but my guess is that any solution will support having a way to set a default for all languages via a setting.

In the meantime, I think the notes in #7189 will help you work-around this issue.

**Comment by djbrooke** [comment]
Hi @Venki18 - I'm going to close this as I suspect it was fixed in #7189/#7192 in Dataverse 5.
