### ISSUE TITLE
Internal Exception: org.postgresql.util.PSQLException: ERROR: deadlock detected

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#6865]
Sometimes, but not all the time, when I run the API test suite on my laptop, some of the API tests fail with a 500 response and when I look at server.log I see errors like this:

`Internal Exception: org.postgresql.util.PSQLException: ERROR: deadlock detected`

Here's an example of a failing test but the tests vary:

[ERROR]   FilesIT.testReplaceFileBadJson:898 Expected status code <200> doesn't match actual status code <500>.

Here are a couple more examples from last week, both from the same run:

[ERROR] FileMetadataIT.tearDownDataverse:96 Expected status code <200> doesn't match actual status code <500>.

[ERROR] FilesIT.testReplaceFileBadJson:898 Expected status code <200> doesn't match actual status code <500>.

In tech hours today we discussed how these local failures are probably related to failures we've seen on https://jenkins.dataverse.org

Here's my server.log (renamed so GitHub will take it) from today's run: 
[server.log.txt](https://github.com/IQSS/dataverse/files/4548577/server.log.txt)

**Comment by mheppler** [comment]
Discussing Deadlocks Part Duex with the team today. More info will presumably make it here from those discussions. Hope to confirm with authors of the following issues that we can close and consolidate those into this one deadlock issue.

- #6149 database deadlock during API test suite @donsizemore 
- #5827 Rest Assured Tests: Make Rest Assured integration tests less brittle @kcondon

**Comment by kcondon** [comment]
Don't we have a close newest dupe issue practice? I know curation of issues is informal and not an official part of the process so not sure how we do things now.
