### ISSUE TITLE
Dataverse not saving uploaded zip file's directory structure when the zip file contains shapefiles

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#6873]
On Harvard Dataverse and Demo Dataverse, running version 4.20, I was able to reproduce the following bug that a Harvard Dataverse user reported:

When uploading a ZIP file with files within multiple folders, using drag and drop as the depositor did, on either the dataset create page or on an existing dataset, Harvard Dataverse isn't saving the directory structure. After all the files are uploaded, each file's "File Path" field is empty.

<img width="390" alt="screenshot of file path field" src="https://user-images.githubusercontent.com/18374574/81101399-12591a00-8edc-11ea-87e7-0bc36bca34cc.png">

More info and a Dropbox link to the depositor's ZIP file are in the RT ticket, https://help.hmdc.harvard.edu/Ticket/Display.html?id=289407, but I'll note here that:

- The ZIP file is about 100 MB and 216 MB unzipped
- It contains hidden folders and files. The depositor said he's aware of this, it's fine that they were included in the deposit, all files he needed deposited are deposited in the dataset, and he doesn't see any missing files in the deposit.
- The dataset on Harvard Dataverse was unpublished as of opening this issue, so I was careful to not publish the files on Demo Dataverse while testing. The files should not be shared publicly or widely.
- If you look at that unpublished dataset, note that you're seeing a directory structure because the depositor re-created the directory structure by entering it into each file's File Path field.

**Comment by jggautier** [comment]
The problem might have something to do with the .shx files in the zip folder, the "geodata" folder, and the way Dataverse tries to process shape files might be related:
- When those .shx files in the "geodata" folder are included in the zip file, Demo Dataverse doesn't save the directory structure. Demo Dataverse also changes the extensions of the .shx files to .zip.
- When I remove that "geodata" folder, re-zip, and upload to Demo Dataverse, Demo Dataverse remembers the directory structure.
- When I upload only those .shx files in a zip file with a directory structure, Demo Dataverse remembers the directory structure and does not change the extensions to .zip. (Uploading the .shx files individually also works fine - the file extensions aren't changed.)

**Comment by jggautier** [comment]
Because this bug can be reproduced with any zip file that contains at least one set of shapefiles, here's [a zip file with a directory structure and with shapefiles for testing](https://github.com/IQSS/dataverse/files/4588466/files.zip)

**Comment by jggautier** [comment]
Dataverse zips each set of shapefiles. If the depositor zips each set of shapefiles before uploading, Dataverse remembers the directory structure.

This might be a workaround to get Dataverse to remember the directory structure, although I don't know how these files are produced or how inconvenient it would be to zip each set of shapefiles before zipping the whole thing and uploading. And I don't know if the fact that Dataverse zips each set of shapefiles affects replication. Would this be a concern? @atrisovic or others? I could ask the depositor who reported this issue, too.

**Comment by djbrooke** [comment]
Thanks @jggautier. I'm going to prioritize fixing this for the next sprint. My preferred solution here is that the shapefiles keep being combined as they are now but the hierarchy is otherwise maintained. If this is not possible/challenging I'm happy to discuss removing the shapefile zipping features for now. I'll start a separate thread with some Geospatial data folks to get their take on the importance of this feature outside of the Worldmap integration.

**Comment by djbrooke** [comment]
- We should implement the hierarchy fix without changing the Shapefile change for now
- (@djbrooke to link to code that handles sharpefile ingest)
- @djbrooke to check with Geospatial folks before this is picked up to see if we can just rip out the shapefile ingest
