### ISSUE TITLE
Add setting for navbar guide URL override

### ISSUE THREAD

**Issue by poikilotherm** [IQSS/dataverse#6877]
Back in #3637, a database setting "NavbarGuidesURL" has been added to `SettingsServiceBean`, but was never used.

I would like to pick this up (and document it) for a use case in Jülich DATA. We have a [custom guide](https://data.fz-juelich.de/guide) based on your magnificent work, which includes a guide for the special needs and processes in our instance. We would like to link to this section of the guide in the navigation bar instead of the user guide.

[The code for this is very simple.](https://jugit.fz-juelich.de/fdm/dataverse/-/commit/accd1bdfc330888d17613246fbd43696314dd4a6) It provides a fallback to a sane default.

Please tell me what you think and if I should create a PR for this *very* simple change.

Pinging @TaniaSchlatter for being UI related.

**Comment by djbrooke** [comment]
Thanks @poikilotherm. Just so I understand correctly, is your use case similar to Libradata (https://dataverse.lib.virginia.edu/) or is it different?

**Comment by poikilotherm** [comment]
I think it's different (from what I see at their site). We offer all the guides, too, so we use the `:GuidesBaseUrl` setting to forward any help button links to our guide. But we want to point the big "overall" user guide link reachable from the navigation bar to point to our special guide about how to login, where to find help, read about processes etc.

Please feel free to try for yourself :smile: (the guide is not finished yet, but we're getting there...)

**Comment by shlake** [comment]
@poikilotherm we use the :GuidesBaseURL setting for the "User Guide" link on the navbar and use :NavbarAboutURL for the "About" link.

I have customized the default Harvard User Guides, so UVa's look like Harvard's, uses sphinx, with UVa specific information - see account information: http://uvalib.github.io/dataverse-docs/en/current/user/account.html

**Comment by poikilotherm** [comment]
Nice!

We didn't want to fork and change the user guide directly, but instead we use the upstream as a submodule and add the pages. I created another section parallel to the others, so this is not reachable via the `/user` based generation of the link...

We went for using a distinct section because we want to elaborate on a few things and feared those might get a little lost in the very complex and detailed user guide.

**Comment by pdurbin** [comment]
@poikilotherm I looked at your commit above and I think I get what you want.

From the header, you don't want to link to "/user". You want to link to "/juelich", which is, of course, specific to your institution.

You made the code in that header backward compatible, as you said and from what I can tell. Great.

The main reason I'm writing is that I'm wondering about all the other places where the URL to the guides is used. I'll dump a couple screenshots below to show what I mean. I'm wondering if you're aware of all these usages and if you're fine leaving the code alone for these.

Finally, good catch to finding an used database setting!

<img width="979" alt="Screen Shot 2020-04-30 at 10 55 41 AM" src="https://user-images.githubusercontent.com/21006/80726123-fddae300-8ad1-11ea-9e6a-3ff681fbff97.png">
<img width="1037" alt="Screen Shot 2020-04-30 at 10 56 01 AM" src="https://user-images.githubusercontent.com/21006/80726132-ffa4a680-8ad1-11ea-8a4c-960cab7cc3f5.png">

**Comment by poikilotherm** [comment]
Howdy @pdurbin !

Yeah, those places were the things I meant with "help button links" in my 2nd comment. I am fine with those, I simply created a rewrite rule in NGINX.

But obviously that rule cannot change the target when clicking on the navbar link to the specialized guide, that's why I went for the option... :wink: 

Should I wait for a notification by @TaniaSchlatter or others from the UI team or should I just craft a PR? If the UI team wants to take a look at how this looks and feels, feel free to go to https://data.fz-juelich.de

**Comment by pdurbin** [comment]
@poikilotherm thanks, here are a couple screenshots I took. I clicked "User Guide".

<img width="1198" alt="Screen Shot 2020-04-30 at 11 34 04 AM" src="https://user-images.githubusercontent.com/21006/80730126-2e714b80-8ad7-11ea-9780-f0023e4d8935.png">
<img width="1198" alt="Screen Shot 2020-04-30 at 11 34 10 AM" src="https://user-images.githubusercontent.com/21006/80730130-2fa27880-8ad7-11ea-927a-4b5cca3b84e1.png">

**Comment by TaniaSchlatter** [comment]
Looks great, @poikilotherm. Thanks. Also, lovely typeface on your guide.

**Comment by poikilotherm** [comment]
@TaniaSchlatter Wait till you see it on our installations, too :smile: 

Then I'll go ahead and do some magic to summon a pull request.
