### ISSUE TITLE
Google Drive as remote storage request

### ISSUE THREAD

**Issue by nightowlaz** [IQSS/dataverse#6880]
I was wondering what the status of integrating Google Drive as a remote storage location for Dataverse? We have researchers who are very interested in this option, as google drive is a very common location for file storage in our environment. Researchers would like to keep their files in google drive and link to them from DV datasets.

**Comment by djbrooke** [comment]
Hey @nightowlaz, Google Drive isn't something that we'd add as a storage service for Dataverse, as the file storage wouldn't be under the repository's control and would break the assurances around persistence of files. If you are talking about deposit from Google Drive for archiving and sharing in Dataverse, it's something that has been discussed (#1746) but hasn't been prioritized.  

Theoretically, if there was some SLA with Google Drive at the institutional level, I guess it could be set up as a Trusted Remote Storage Agent (https://cyberimpact.us/dataverse-trusted-remote-storage-agent-update/) in the future, but I'm not sure and I'd defer to @jonc1438 or someone more familiar...

**Comment by nightowlaz** [comment]
Okay, thanks, that makes sense regarding remote storage and persistence. I saw all of the threads referring to the Trusted Remote Storage Agent and wasn't quite sure what the status of that was. This helps a lot and I will keep my eyes open for future updates.
