### ISSUE TITLE
Cancel in create dataset doesn't delete temp files

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#6881]
While hitting 'Cancel' rather than 'Save' when editing datasets properly removes temp files, doing so on the dataset creation page does not. Looking at the code, the 'Cancel' method in DatasetPage just calls returnToLatestVersion which clears the newfiles list but does not delete any files. In contrast, the EditDatafilesPage cancel goes through two loops to delete the newfiles (those in the lower pane) and the uploadedFiles (those in process/still in the upper list). (Actually, in mode SINGLE or SINGLE_REPLACE, EditDatafilesPage doesn't try to delete any files - shouldn't it delete the one upload?).

**Comment by mheppler** [comment]
Sounds like a duplicate or highly related to an old from @kcondon, **Create Dataset: Delete file on create dataset does not delete. #2862**.

**Comment by qqmyers** [comment]
It's different, not sure if its related. This issue is about 'cancel' in create mode doing nothing but redirecting the the owning dataverse page and abandoning any temp files (not calling returnToLatestVersion as I said above - that's the cancel button show when editing the dataset). In trying to figure out how to fix this, I've looked into how DatasetPage and  EditDatafilesPage communicate, so I'll keep #2862 in mind to see if there's some reason delete wouldn't work from the dataset page.

**Comment by mheppler** [comment]
Thank you for the clarification, @qqmyers. Any learned info added to the create+delete issue would be much appreciated. I have a personal ~vendetta~ related issues list for all things file upload, so when I see new issues opened, I comb over those to see if there is anything in the backlog that can be consolidated or closed.
