### ISSUE TITLE
File Upload: Direct S3 intermittently fails on file upload during dataset creation on payara 5.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#6882]
Uploading files on dataset creation when using S3 has had some issues but many have been fixed. This is a placeholder for remaining ones that appeared to be specific to Payara5.

The basic use case(s) are to upload 3 smaller files while creating a dataset in a dataverse configured to use direct s3 upload. The behavior is it will work sometimes and fail sometimes but in a couple different ways: hung on all files 100% progress, 0% progress, or some 100, some 0.

Try running the same test several times in a row, noting UI behavior, browser log, console and network, and server.log

Have tried as a new user, both in root dv and in a sub dv.

**Comment by qqmyers** [comment]
Testing on #6829 showed errors such as the one below, which I don't think we've seen using glassfish. It's not clear yet what's causing that - direct upload does involve remoteCommand calls and having Primefaces call executeScript() to invoke javascript upon return.

[2020-05-01T14:27:15.022+0000] [Payara 5.201] [SEVERE] [] [javax.enterprise.resource.webcontainer.jsf.context] [tid: _ThreadID=96 _ThreadName=http-thread-pool::jk-connector(2)] [timeMillis: 1588343235022] [levelValue: 1000] [[
  java.lang.NullPointerException
        at javax.faces.component.ComponentStateHelper.restoreState(ComponentStateHelper.java:294)
        at javax.faces.component.UIComponentBase.restoreState(UIComponentBase.java:1249)
        at javax.faces.component.UIOutput.restoreState(UIOutput.java:243)
        at javax.faces.component.UIInput.restoreState(UIInput.java:1512)
...

**Comment by qqmyers** [comment]
@kcondon - using the latest dataverse-ansible script to deploy with payara 5.201, I'm so far unable to replicate this (now that the other fixes are in place). Using 3 1 KB  *.bin files, in the root dataverse, or a sub-dataverse as dataverseAdmin, 8 times in a row. Tried some slight variations of filing out metadata before/after uploading files, submitting with missing required metadata to have to go back and add that before I could save, starting in child dataverse and switching to root on the create page. So far, no glitches. 
Can you check your setup and see if you can replicate this error now? If so, and if it isn't specific to an older payara, we can start comparing notes to see whether it's specific files/types, etc.  If it's random,
