### ISSUE TITLE
File Upload: Figure out best way to handle host dv change that changes file store type on dataset creation.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#6883]
There is a potential issue where on dataset creation, the user has the chance to change the dataverse the dataset will be created in, ie. the host dv. This can be problematic if the initial dv used a direct s3 store but the changed host used something else, like local. The path has changed, especially if some files were uploaded with on dv, some with other. @qqmyers is this an accurate description?

**Comment by qqmyers** [comment]
Yes - with direct upload and temp files going to their final locations, switching to a store with normal uploads could break something - not clear that the code will find the temp files in the other store and properly create final copies in the right store, not clear that the temp copies in the direct store will get deleted.  There's also the issue that unless the page/the edit files component is updated, the page will continuing using direct upload, probably to the original store. Conversely, when you start from a normal store, switching to direct may also break file handling and the uploads won't switch to direct.
I'm not certain that things will break, but unless we don't allow the changes, or force a refresh of the file upload part, etc. the upload processing will be very confusing.
Note #6872 may change this - if the store isn't associated with the owning dataverse.

**Comment by landreev** [comment]
That new (relatively) ability, to select the host dataverse for a new dataset, is a lot of trouble. (Serious question - do we feel it's been worth it?)
The page could be rigged to trigger a full reload/full re-initialization, when the host dataverse is changed.  Ensuring all the components are properly initialized. I recall we are already doing enough of that, to warrant warning the user they are going to lose everything they may have already entered, if they change the dataverse. Don't know if we are already doing enough for the purposes of this upload issue; but we should be able to. 

As for the relation to #6872 - this may be another reason to limit that to API uploads only, for now.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
