### ISSUE TITLE
File Permissions: Provide a filter that displays only the most recently granted users

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#6884]
This was proposed by Sonia in response to a recent RT ticket, 289395
User had granted 275 users access over several years. It became unwieldy and slow. So, she wonder whether some type of filter might help, such as only displaying 50 most recent by default.

Other thoughts could include granted access for limited time and then expiring, dropping off.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
