### ISSUE TITLE
Classify metadata fields as mandatory, recommended, and optional

### ISSUE THREAD

**Issue by philippconzett** [IQSS/dataverse#6885]
As an admin, I'd like to be able to classify metadata fields as mandatory, recommended, and optional in any dataverse (as opposed to the current two choices of mandatory and optional fields). Mandatory and recommended fields should pop up at the initial step of creating a dataset. The possibility to classify metadata fields as recommended and make them appear in the first round of metadata registration would make it much easier to get researchers / depositors filling in these fields. Currently, our curators often have to make depositors aware of there being other important metadata fields than the mandatory ones.

**Comment by poikilotherm** [comment]
This matter is being discussed in a few places already. 

- See #6700 for a crazy idea about forkability of schemas.
- See #6030, #4451 and #6561 for a more general, UI-refactor approach.

**Comment by philippconzett** [comment]
Thanks, @poikilotherm! I think my suggested introduction of “recommended” as a third value for metadata field mandatoriness would be useful independently of how (custom) metadata fields are managed (cf. [#6700](https://github.com/IQSS/dataverse/issues/6700)).

**Comment by pdurbin** [comment]
> Currently, our curators often have to make depositors aware of there being other important metadata fields than the mandatory ones.

@philippconzett this new feature of 5.12 might help:

"Collection managers can create templates that include custom instructions on how to fill out specific metadata fields."

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.

**Comment by philippconzett** [comment]
Hi all, I still think this feature request is relevant as it would make metadata registering as well as dataset curation more efficient. Thank you for reconsidering whether this issues should be closed!

**Comment by cmbz** [comment]
Thanks @philippconzett reopening now.

**Comment by philippconzett** [comment]
I might have misunderstood some part of the old issues review process. As for me, this issue (#6885) can wait until the new SPA version of Dataverse is released.

**Comment by pdurbin** [comment]
@philippconzett ok, in that case, would you be willing to create an issue in https://github.com/IQSS/dataverse-frontend , mention it here, and close this issue?

**Comment by philippconzett** [comment]
@pdurbin Sure! Here it is: https://github.com/IQSS/dataverse-frontend/issues/475
