### ISSUE TITLE
Make it easier for users to navigate to collections they have permission to create datasets and collections

### ISSUE THREAD

**Issue by philippconzett** [IQSS/dataverse#6890]
As a Dataverse depositor, I'd like to have available a shortcut to get to the sub-dataverse where I have deposit access.

Some dataverses contain many sub- (and even sub-sub-)dataverses. A given user might only have deposit access to one such sub-dataverse. As any user account always is defined at root level, in some cases (e.g. when navigating to your user account), a user may end up at root level and not easily find his/her way back to the sub-dataverse where s/he has the Dataset Creator role (or any other access role). When you click on your user name in the top right section you'll find the alternative _My Data_, which brings you to your datasets, and thereby also to the (sub-)dataverse where you have deposit access. However, if you for some reason have not created any datasets yet, you'll only get the following message:

> Sorry, nothing was found for these roles: Special, Admin, File Downloader, Dataverse + Dataset Creator, Admin sans publish, Dataverse Creator, Dataset Creator, Contributor, Curator, Member, Edit Dataset

and you'll still be in the root collection. We are quite often contacted by new users asking us why they are not able to publish datasets. We then have to guide them to the right sub-dataverse.

To help users getting to the right sub-dataverse, I'd like to suggest to add " / Repository" to _My Data_ in the user menu, and change its behavior so that by clicking it, it brings you to your data in case you already have created any datasets, or to the (sub-)dataverse where you have deposit access.

**Comment by philippconzett** [comment]
I just realized that I didn't quite get the whole picture of this issue, so I'll rephrase parts of it:

When you click on your user name in the top right section you'll find the alternative _My Data_, which brings you to your datasets. On the same page (/dataverseuser), there is an _Add Data_ button. However, if you click _New Dataset_, you'll get the following error message:

> Not Authorized - You are not authorized to view this page. If you believe this is an error, please contact XXX for assistance.

(That's why we get quite a few requests from users who get this error message.)

As a depositor, when I click the _Add Data_ button, I'd like to be sent to the dataverse where I have the Dataset Creator role, or if I have this role in multiple dataverses, I'd like to be presented a menu where I can choose in which dataverse I'd like to add a dataset.

**Comment by poikilotherm** [comment]
This is related to #6741 and #6708. Maybe some of the discussion there is helpful?

As I mentioned there, we would be interested in a solution without presenting the user an error, but provide a way forward.

For now, the added rendering logic for the header link is a good first step to avoid user confusion.

**Comment by CCMumma** [comment]
The TDR users have been seeing this issue as problematic, as well. Because the Add Data button on the My Data page is navigating to the root TDR, and the Institutional Dataverse Collection where the user has shib access, they get a confusing error, despite the fact that they can still navigate to their own Institutional Dataverse Collection and click the Add Data button successfully there.

I've read the related tickets and it doesn't appear that there is a solution that will avoid this user frustration as yet, but do correct me if I'm wrong.

Thanks,
Courtney, TDL

**Comment by pdurbin** [comment]
I feel like this issue could use a catchier title.

"Make it easier for users to navigate to collections they have permission to create datasets and collections"

Hmm, maybe that's too long. 😄 But that's what we're talking about, right? I've definitely heard this before.

**Comment by philippconzett** [comment]
Thanks, @pdurbin! I have changed the title :-)

**Comment by philippconzett** [comment]
To some degree, the intended behavior described in this issue has been established when the _Add Data_ button was added to the header section. However, if a user has access to more than one collection, they still need to search for the collection they want deposit to after clicking the _Add Data_ button. For example, linguists at UiT The Arctic University of Norway who are TROLLing users, also have access to the UiT collection in DataverseNO and thus would see the UiT collection selected after clicking the _Add Data_ button:

<img width="614" alt="image" src="https://github.com/IQSS/dataverse/assets/21955790/24cd46a2-e815-4bf3-9e9e-ffdb4b992310">

Some users might just ignore the need to select the appropriate collection before they start entering metadata. To avoid this, I suggest a feature that forces users to actively select a collection before they are allowed to start entering metadata.

**Comment by pdurbin** [comment]
@philippconzett heads up that there is active development in this area of the new frontend:

- https://github.com/IQSS/dataverse-frontend/pull/399

**Comment by pdurbin** [comment]
Merged. If you log in and go to https://beta.dataverse.org/spa/datasets/create this is how it looks:

![Screenshot 2024-05-22 at 11 02 53 AM](https://github.com/IQSS/dataverse/assets/21006/3534348f-fe92-4ce4-a337-204d2f26ee22)

**Comment by pdurbin** [comment]
This is a good issue to follow on the SPA side:

- https://github.com/IQSS/dataverse-frontend/issues/388

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
