### ISSUE TITLE
Unable to link harvested datasets via API

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#6899]
We don't have a straightforward way currently to link harvested datasets through the UI, because we don't have a dataet page for harvested datasets.

But this should be possible through the API. When I try, however, I get the following error response:

{"status":"ERROR","message":"Can't link a dataset that has not been published"}

**Comment by jggautier** [comment]
Related to https://github.com/IQSS/dataverse/issues/5886?

**Comment by scolapasta** [comment]
@jggautier if by related you mean, it's the exact same thing then, yes. :)

I'll close this and we can see about getting #5886 prioritized.
