### ISSUE TITLE
RESTful Search API

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#69]
---

Author Name: **Philip Durbin** (@pdurbin)
Original Redmine Issue: 3477, https://redmine.hmdc.harvard.edu/issues/3477
Original Date: 2014-02-03
Original Assignee: Philip Durbin

---

We have a beta RESTful search API in 4.0 but it should be finalized.

It returns JSON. Here's an example: http://dataverse-demo.iq.harvard.edu/api/search?q=tabulardata

It's also used in these integration tests: https://github.com/IQSS/dataverse/tree/master/scripts/search/tests

Requirements:

- use API keys: #3874
- enforce SSL (always?)
- provide a link for each item returned (file link will be for parent dataset)
- sorting
- start/offset (limit number returned?)

Questions:

- have showrelevance boolean?

Asked the community what they would like at https://groups.google.com/d/msg/dataverse-community/sXJmpoL84EU/gJmJhvRPm6YJ

---

Redmine related issue(s): [3430](https://redmine.hmdc.harvard.edu/issues/3430)

---

**Comment by pdurbin** [comment]
As @scolapasta @eaquigley @rtreacy and I discussed, I'm taking this ticket over from @rtreacy .

**Comment by pdurbin** [comment]
@kcondon I believe I've addressed almost all the concerns with the Search API from the meeting yesterday with you, @scolapasta and @eaquigley so I'm passing this to QA.

As we discussed, we need to QA the documentation as well, so please use http://guides.dataverse.org/en/latest/api/search.html for all the information you should need on using the Search API.

If you find any problems with how the code works, please let me know. I mentioned yesterday an issue I know about regarding datasets not showing descriptions. (This is why I said "almost all the concerns" above and you are welcome to open a ticket for this.)

If you don't like how the documentation reads, please give feedback to @eaquigley who has volunteered to improve the Search API docs in a separate ticket: #1328.

**Comment by kcondon** [comment]
Thanks, I'll test it as I test all features and use the doc as functional requirements.


________________________________

**Comment by kcondon** [comment]
Test all functions, public data only, payload contents for each type against cards, boolean operators.

Looks good, closing.
