### ISSUE TITLE
Notification Remains for a Deleted Dataset

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#690]
---

Author Name: **Elizabeth Quigley** (@eaquigley)
Original Redmine Issue: 4140, https://redmine.hmdc.harvard.edu/issues/4140
Original Date: 2014-06-20
Original Assignee: Elizabeth Quigley

---

None

**Comment by scolapasta** [comment]
For 4.0, we will replace where the name is missing with [Dataverse deleted] or [Dataset deleted].

Going forward, we may want to revisit how these notifications are stored - should we store the name at the time the notification was created so we can reference that in perpetuity (until notification is deleted).

**Comment by sekmiller** [comment]
There is now a generic notification when an item has been deleted.
Also, all notifications have been updated to the current pattern for bundles.

**Comment by posixeleni** [comment]
As @sekmiller wrote above there is a generic notification that the item has been deleted which replaces the notification that the dataset was created:

![image](https://cloud.githubusercontent.com/assets/5013837/7073543/257d19a8-dec2-11e4-8257-150b6c1edf38.png)

Works as expected. Closing.
