### ISSUE TITLE
External tools - explore button cause page reload

### ISSUE THREAD

**Issue by kamil386** [IQSS/dataverse#6908]
Clicking explore button on file details preview page takes us to new webrowser tab, but in the same time causes a reload on origin page. This behaviour is unacceptable for performance reasons, especially when using a 3D Viewer external tool. Kindly please implement asynchronous action to this button that doesn't require origin page reload, preferably in the next release of Dataverse if possible.

![obraz](https://user-images.githubusercontent.com/56053188/81701861-d9d0b780-946a-11ea-976b-a6f577791b59.png)

**Comment by djbrooke** [comment]
@kamil386 thanks for the report. If it's reloading that page for no reason, I agree it's a waste. 

I'll defer to @scolapasta @qqmyers @pdurbin and others that are more familiar with the external tools framework in case there's some technical reason for this.

**Comment by qqmyers** [comment]
There is.  I don't recall the details, but it's related to being able to close the preview window and return to Dataverse.

**Comment by kamil386** [comment]
Can we do anything with that? My web browser isn't happy with doing double hard work in the same time

**Comment by pdurbin** [comment]
I haven't looked into the code but from some quick testing my observation is that when the page is relatively light, the page reload is not especially bothersome, to me at least. I was testing with this JPG viewer: https://dataverse.harvard.edu/file.xhtml?persistentId=doi:10.7910/DVN/1ZG6EE/8X5WD9&version=1.0

I'm not saying we shouldn't fix it but we want to make sure we have a use case in front of us that clearly illustrates the performance problem.

Or is this a user experience problem? The page certainly does flash, which isn't great.

Finally, we're certainly open to pull requests!

**Comment by qqmyers** [comment]
I looked at this again and think it was simpler than I thought. When I wrote this originally, I hadn't realized that <h:commandLink> is not ajax by default while <p:commandLink> is. The PR above should resolve this.

**Comment by qqmyers** [comment]
@kamil386 - since the change is just to one .xhtml file, it should be easy to update locally in your current Dataverse instance if you don't want to wait. (I think you have to delete the files in /generated and /osgi-cache and restart glassfish to pick up the change, but that's all beyond making the same edit that's in the PR.
