### ISSUE TITLE
Add a timer for running saved searches

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#6910]
We currently have a way to define a saved search that gets associated with a dataverse (anything that matches that search gets linked to that dataverse) and an API to rerun the search. However, this API currently needs to be called manually*.

(*) when saved search functionality was added, we did not yet have a Timer Service, and we had planned on just using a cron job to automatically call the api

We should add a Timer, similar to Export Service or Harvesting, that runs these saved searches automatically.

**Comment by djbrooke** [comment]
@scolapasta is this a timer for Harvard Dataverse only or does it require a code change to Dataverse? If former, do we just provide docs?

**Comment by scolapasta** [comment]
Code change.
