### ISSUE TITLE
Production patch for  4.20, 6918

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#6922]
branch off of v4.20 tag, create a quick patch. 
(separate from the long term solution as described in #6918, that will be merged into dev. and eventually v.5)

**Comment by landreev** [comment]
The patch will do the following:
- eliminate the evil singleton; 
- eliminate unnecessary reindexing of parent dataverses, when no new subjects are added in the dataset that's being published.

**Comment by kcondon** [comment]
Looks good.
