### ISSUE TITLE
custom terms of use causes dataset page file-level Explore to choose dataset-level Explore 

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#6923]
Hit this on 4.20/glassfish4 this morning and recreated it on a fresh install of 4.20/payara5.

Enable WholeTale. Create a dataset and upload a CSV. Fine. Now set a custom "Terms of Use."

The dataset page's Explore file entry throws the user to WholeTale instead of Data Explorer. Workaround is to click on the file landing page, and Explore from there.

Changing the custom terms to CC0 corrects the behavior - only custom terms seem to cause this bug.

**Comment by djbrooke** [comment]
In #5354, a similar issue was reported as a file level issue on 4.9.x. I closed that one because so much work has been done in this area and I expect/hope the same solution will solve both.
