### ISSUE TITLE
Permissions- groups:  "edit" option under groups should allow me to edit "group name" also

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#6926]
I can edit  "group members"  but not the "group name." I made a mistake in naming the group and would rather not recreate the entire group

<img width="1960" alt="Screen Shot 2020-05-20 at 6 29 58 PM" src="https://user-images.githubusercontent.com/8322346/82503897-269a3b00-9ac8-11ea-8f24-70c42dee5b71.png">

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
