### ISSUE TITLE
File upload: Direct S3 upload has intermittent failures when uploading larger number of files.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#6930]
Direct S3 file upload was recently tested using 100 small files, uploaded simultaneously. While smaller numbers of files appears to be reliable, the larger 100 file set has shown intermittent failures. Attached is a file containing 3 tests and their results.
[directs3100fileuploaderr.txt](https://github.com/IQSS/dataverse/files/4670035/directs3100fileuploaderr.txt)

**Comment by qqmyers** [comment]
The problem appears to be only with very small files (26 bytes in the test). Even though the fileupload javascript is now only making one call to Dataverse at a time (actual byte uploads to S3 are still done in parallel), the quick turn around between calls to Dataverse still seems to cause some concurrency issue in managing the view state. As far as I can tell, the problem disappears by the time the file is 1K or larger, so I'm planning to just put in an artificial ~half-second delay (haven't optimized but 200 msec is too short).
