### ISSUE TITLE
Add "sort by file path" to sort options for file listing on dataset page

### ISSUE THREAD

**Issue by npoppeli** [IQSS/dataverse#6933]
In the Dataset overview page, there is a Sort button, which presently has the following options: name(a-z), name(z-a), newest, oldest, size, type.
In a round of testing with Dataverse at our institute, the suggestion was made to add an extra option: 'file path'. 

Regards,

Nico Poppelier
University Medical Centre Utrecht, The Netherlands

**Comment by djbrooke** [comment]
Thanks @npoppeli. It's great to hear that you're doing testing on Dataverse!

Can you provide more information about the person's expectation of what would happen when "File Path" was selected as a sort option?

**Comment by npoppeli** [comment]
The tester's intended behaviour is that the files in the dataset are shown in order of the file path, sorted alphabetically. As I'm writing this, I can imagine doing both an ascending sort and a descending sort, as with the name attribute.

**Comment by djbrooke** [comment]
Thanks @npoppeli for the details!

**Comment by pdurbin** [comment]
@npoppeli I hope you don't mind but I updated the title.

Have you seen the tree view? Here are some screenshots (also showing current sort options).

<img width="764" alt="Screen Shot 2022-09-30 at 8 46 15 PM" src="https://user-images.githubusercontent.com/21006/193376541-4e25545e-80c0-49d2-8f4a-d4a688cfd34d.png">
<img width="764" alt="Screen Shot 2022-09-30 at 8 46 35 PM" src="https://user-images.githubusercontent.com/21006/193376543-ab75cd3b-ab26-4392-960d-b9ef5cc78a2e.png">


You can play with that dataset at https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/BOU7XR

**Comment by npoppeli** [comment]
Hello Philip,
    
    
    Thanks for the update on issue 6933. We
      are aware of the tree view. Nevertheless, we think that sort by
      file path would be useful in the table view.
    
    
    Regards, Nico
    
    
    Op 01-10-2022 om 02:49 schreef Philip
      Durbin:
    
    
      
      @npoppeli
        I hope you don't mind but I updated the title.
      Have you seen the tree view? Here are some
        screenshots (also showing current sort options).
      
      
      You can play with that dataset at https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/BOU7XR
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        You are receiving this because you were mentioned.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/IQSS/dataverse/issues/6933#issuecomment-1264175260",
"url": "https://github.com/IQSS/dataverse/issues/6933#issuecomment-1264175260",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
    
    
    
    -- 
Vriendelijke groet,

Nico

**Comment by qqmyers** [comment]
FWIW: QDR has implemented group by folder and group by tag options that do this. We had an early PR that was closed while waiting for other dataset page changes but that could be updated/resubmitted if this is something the community wants. I've had other discussions lately re: the group by tag feature (i.e. so that files tagged as Documentation appear first) with JHU and Odum who would like that part at least.

**Comment by pdurbin** [comment]
@qqmyers good point. Here's that PR that was closed:

- #5485

It was meant to address this (still open) issue:

- #4959
