### ISSUE TITLE
Call shibboleth logout if we are logged in through shibboleth, :ShibPassiveLoginEnabled setting stopped working

### ISSUE THREAD

**Issue by pallinger** [IQSS/dataverse#6934]
dataverse version: 4.20 build 413-4e07b62

The problem: If we login using shibboleth, then after logout, the shibboleth session remains, and re-login occurs without re-login at the IDP.

The proposed solution: on logout, if the user is logged in through shibboleth, the site should should redirect to `/Shibboleth.sso/Logout`.

**Comment by djbrooke** [comment]
Hey @pallinger, this is an interesting question and I'm not sure of the best practice here. Thanks for creating this issue. 

If I log in to Harvard Dataverse using Harvard Key (Shibboleth), and then log out of Harvard Dataverse, does it make sense to end my Harvard Key session and log me out of all the other Harvard systems that I'm currently logged in to (finance, HR, travel)? Is this what's being proposed?

**Comment by pallinger** [comment]
I tried to fix this issue by modifying DataverseHeaderFragment.logout().

However, the redirect did not happen even though I changed the value of redirectPage.

`		// If we have a shibboleth session, so we should log out of it
		HttpServletRequest req = (HttpServletRequest) FacesContext.getCurrentInstance().getExternalContext().getRequest();
		Cookie[] cookies = req.getCookies();
		for(Cookie cookie : cookies) {
			if (cookie.getName().startsWith("_shibsession_")) {
				redirectPage = "/Shibboleth.sso/Logout?return="+systemConfig.getDataverseSiteUrl()+"/"+redirectPage;
			}
		}
`

**Comment by pallinger** [comment]
@djbrooke no, it would not log out globally on the IDP, only on the local shibboleth. If the shibboleth instance has multiple web services (that is quite rare, but not impossible, but also may have unwanted side-effects), then it will still logout only from their shibboleth sessions, their JSESSIONID or PHP_SESSION or similar would be unaffected.

**Comment by pallinger** [comment]
@djbrooke There _is_ a single logout feature that could be implemented; however, it should be a different button. See: https://wiki.shibboleth.net/confluence/display/SHIB2/SLOWebappAdaptation

This would be nice to implement, but much larger in scope.

**Comment by pdurbin** [comment]
@pallinger hi, have you experimented with setting `:ShibPassiveLoginEnabled` to true? Here are the docs: http://guides.dataverse.org/en/4.20/installation/config.html#shibpassiveloginenabled

This feature was contributed in pull request #3762 as a fix for this issue:

-  Shibboleth log off doesnt clear the cookies #3535

**Comment by szabogyula** [comment]
> If I log in to Harvard Dataverse using Harvard Key (Shibboleth), and then log out of Harvard Dataverse, does it make sense to end my Harvard Key session and log me out of all the other Harvard systems that I'm currently logged in to (finance, HR, travel)? Is this what's being proposed?

as @pallinger wrote, the logout action in dataverse terminates the app's session only, but the shibboleth sp session is untouched. After logout you can go to `/shib.xhtml` and you will logged in dataverse again without any new authentication, and you see the live shibboleth sp session at the `/Shibboleth.sso/Session` url.

There is a screencast of the logout issue:

https://drive.google.com/file/d/1ejoDStrwJMvFbvx8VqMWxUOUNFF1_q7w/view?usp=sharing

**Comment by pallinger** [comment]
The behaviour in the above video by @szabogyula definitely does not seem OK. But regardless, I would like some help as to why my patch is not working. It seems that no matter what I return as `redirectPage`, it does not get sent to the user. Or is that some internal redirect that only pertains to some page _element_?

**Comment by pdurbin** [comment]
@szabogyula thank you for the video. It's very clear.

@pallinger I'm not sure why your patch isn't working. From a quick look it seems like it should.

Did you see my earlier comment about how a contributor already implemented a fix?

**Comment by pallinger** [comment]
@pdurbin I checked whether @szabogyula 's scenario occurs if `:ShibPassiveLoginEnabled` is `true`. It does, so that setting does not solve the above logout error. 

I have seen the possible workaround of using short session timeouts (as shibboleth session is consulted only on login, and never later), which we may use, but it is not perfect.

**Comment by pdurbin** [comment]
@pallinger ok, thanks for testing. It's sad to hear that that setting doesn't work!

**Comment by pdurbin** [comment]
Uh oh, we just heard the following at https://groups.google.com/g/dataverse-community/c/2OjYxw_czDw/m/_iNoF9aQAAAJ

> I tried the :ShibPassiveLoginEnabled setting and it did not work for the Shibboleth logout.

@sudoflyy if you're listening, do you know if pull request #3762 is still working?

**Comment by qqmyers** [comment]
If passive login is working, you should be able to login to Shib directly/with some other app and then go to the Dataverse page and automatically be logged in (assuming you have an account).

If that isn't working any more, it's possible that some tweaks from QDR might help. For example, I think we made some changes when the fix to destroy the Java session at logout was made. (QDR's customizations w.r.t. SSO make it hard to know exactly if/when specific changes will affect the Shib implementation in IQSS/community version.)

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
