### ISSUE TITLE
Add byte offset functionality to StorageIO and Access API

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#6937]
We want to be able to support the standard HTTP "bytes=" parameter. For example, call `/api/access/datafile/<id>?bytes=8192-8208` and get just the 16 bytes at the 8K offset, instead of the entire file. 

(it's "working" for some people in our own prod. Dataverse - see #5957 - but only because we redirect to S3, which does understand the parameter). 

To implement it, we should add some form of "open at offset specified" functionality to the StorageIO structure. Then adding the handling of the extra parameter to the Access API should be trivial. 

Should be straightforward overall.

**Comment by djbrooke** [comment]
- Small modification of AccessIO
- per @djbrooke, This is more defensive than anything - we wouldn't want an installation to have files downloaded many times when this feature could be used (saving on costs and allowing for better stability)

**Comment by djbrooke** [comment]
- from @qqmyers - this will allow us to do better file ID for large files
- this will continue to support the Tectonic use case on Harvard Dataverse - and we're concerned about that same use case happening for another installation, where there'd be cost/stability implications
