### ISSUE TITLE
File deletion error

### ISSUE THREAD

**Issue by youssefOuahalou** [IQSS/dataverse#6939]
Hello everyone,

I have a problem when I delete a file from a dataset that is already published, I see an error message but the file is deleted. But I'm afraid it will cause errors elsewhere, I think the error comes from Solr but I have no more information, here are my logs from Glassfish and Solr.

[errorFileGlassfish.txt](https://github.com/IQSS/dataverse/files/4687920/errorFileGlassfish.txt)
[solrErrorFile.txt](https://github.com/IQSS/dataverse/files/4687922/solrErrorFile.txt)

![DeleteFileError](https://user-images.githubusercontent.com/46802308/83004382-e2e78a00-a00f-11ea-875a-fdbcfa96a268.PNG)

**Comment by djbrooke** [comment]
Hey @youssefOuahalou, can you check the discussion in https://github.com/IQSS/dataverse/issues/6457 and see if this is the same issue?

**Comment by youssefOuahalou** [comment]
Thank you very much @djbrooke , you have solved my problem. However, I was sure that I had updated this file. I'm sorry to have opened a duplicate issue.
