### ISSUE TITLE
Style Guide - Review and update UI references for new btn's on dataset and file pgs

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#6940]
With the new btn's on the dataset and file pgs, we will need to review and update and references to the old layout in the User Guides and Style Guides.

This is was spun off from #6684 in order to get that moving forward.

**Comment by djbrooke** [comment]
We should keep this scoped to the Style Guide for now. We can update the "Finding and Using Data" section of the User Guide when we add the option to "Download All" that depends on #6505.

**Comment by mheppler** [comment]
Added new button styles with code examples to Style Guide, Patterns pg for the new action button at the top of the dataset and file pg, as well as the icon-only buttons in the file table on the dataset pg.

<img width="874" alt="Screen Shot 2020-06-22 at 3 08 27 PM" src="https://user-images.githubusercontent.com/687227/85326141-c9185600-b49a-11ea-9685-2dc4062adbe9.png">

...

<img width="862" alt="Screen Shot 2020-06-22 at 3 13 40 PM" src="https://user-images.githubusercontent.com/687227/85326233-f6650400-b49a-11ea-9215-b55e1d5d1297.png">
