### ISSUE TITLE
414 error when trying to download ~1000 files in a dataset

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#6943]
There’s an unpublished dataset in dataverse.harvard.edu that has 1061 files:

https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/HVY5GR

When I try to select all files for download I get:

“Request-URI Too Long
The requested URL’s length exceeds the capacity limit for this server.”

…I assume because it’s a URI like https://dataverse.harvard.edu/api/access/datafiles/3851150,3851397,3851153, and so on, with all 1,000 files. 

Tagging @qqmyers as he mentioned he has some code that handles this issue. Thanks @qqmyers !

**Comment by pameyer** [comment]
FYI - I think max URL length is configurable in apache (not sure about glassfish/payara/etc), so this may be fixable without code changes.

**Comment by qqmyers** [comment]
I think I looked into that, but there are browser limits as well. I think the lowest is IE/Edge at around 2K chars (current info afaik).
