### ISSUE TITLE
Shibboleth registration results in badly converted accented characters in user's name

### ISSUE THREAD

**Issue by pallinger** [IQSS/dataverse#6946]
Registering with shibboleth, my Given Name is "PÃ©ter" instead of "Péter", which I cannot even change. My colleague András was named "AndrÃ¡s".

It seems like the UTF-8 name was interpreted as ASCII or similar.

If I register without shibboleth, I can use any (Hungarian) accented characters: Árvíztűrő Tükörfúrógép works just fine.

Dataverse version: 4.20

**Comment by pdurbin** [comment]
@pallinger thanks for reporting this issue.

Developers, I'd suggest adding these examples to the mutateRequestForDev examples at https://github.com/IQSS/dataverse/blob/v4.20/src/main/java/edu/harvard/iq/dataverse/authorization/providers/shib/ShibUtil.java#L164 which only seem to have ASCII characters (my bad). See also `:DebugShibAccountType` at http://guides.dataverse.org/en/4.20/developers/remote-users.html

**Comment by djbrooke** [comment]
thanks @pdurbin for the pointer!

@pallinger are you able to make a PR for this?

**Comment by pallinger** [comment]
I am not sure where to look, but I will try tomorrow.

**Comment by djbrooke** [comment]
@pallinger that's great, thanks for taking a look!

**Comment by pallinger** [comment]
I have found similar issues here: 
 - https://issues.redhat.com/browse/UNDERTOW-1324
 - https://shibboleth.1660669.n2.nabble.com/Shibboleth-Tomcat-AJP-and-UTF-8-conversion-td7628986.html

They point to the AJP attributes being parsed as iso8859-1 instead of utf-8 in glassfish (and elswhere, tomcat). They seemed to find glassfish configuration to fix it.

There is a trick to re-encode the sting: `attributeValue= new String( attributeValue.getBytes("ISO-8859-1"), "UTF-8");` but it will wreak havoc if the original bug/misconfiguration gets fixed.

If I cannot find a better solution, I will try introduce this change but make it optional. Would a setting in `SettingsServiceBean` named `ShibAttributeCharacterSetConversion` be OK?

**Comment by pdurbin** [comment]
@pallinger I looked at 0808d9b and it makes sense to me. My only suggestion is to make your fix the default. If it gives people trouble they can disable it. Thanks for looking into this!
