### ISSUE TITLE
Publish Dataset - Failed publish error msg displayed on latest published version, not on draft version

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#6947]
While chasing publish lock UI bugs on demo (4.20), I stumbled upon this confusing behavior.

**PROBLEM**

After the publish lock warning msg clears upon refresh, and something failed, the error msg is displayed on the latest published version (see screenshot below), and not on the draft version where the publish workflow was started by the user when they clicked the Publish btn.

This leads to confusion. The msg text even suggests, "please try again", but there is no Publish btn displayed to click!

**SUGGESTION**

The publish error msg should be displayed on the draft version, not the latest published version.

**REFERENCES**

<img width="1165" alt="Screen Shot 2020-05-29 at 11 17 02 AM" src="https://user-images.githubusercontent.com/687227/83279803-ac427880-a1a3-11ea-8186-d1c2fe72977e.png">

**Comment by djbrooke** [comment]
Thanks @mheppler. I think we fixed something similar this recently, but a quick search didn't turn anything up. :/ I agree with your suggestion about how to handle this. I'll add to up next.

**Comment by landreev** [comment]
Confirming that the PR #7118 will also fix this issue. If anything goes wrong during an attempt to publish, the user will end up staying on the draft page. And not, confusingly, on the last previously published version (if exists).
