### ISSUE TITLE
Upload a file to a draft, change the name to an existing name, saves and renames on saving

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#6949]
1. Start from a draft dataset (with files)
2. Upload a file, then manually change the name to an existing file name.
3. save.

The save succeeds, when it shouldn't, and filename is changed on save.

Expected behavior: save should fail with duplicate filename error. (the auto renaming should be occurring when you upload the file, so the user can see the change before save. In this case, as a user, I changed the name manually to what I wanted, so the save should fail and let me know why.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
