### ISSUE TITLE
As an admin, I want to make dataset templates mandatory / remove "None" from the template dropdown menu

### ISSUE THREAD

**Issue by BPeuch** [IQSS/dataverse#6955]
Version: 4.20

Hello everybody,

We at the State Archives of Belgium find the dataset template feature very neat, and we have used it to prepopulate the ```Terms of Use``` field with several "access & reuse regimes." This is beneficial in more ways than one:

- Those access & reuse regimes were written by our legal expert, who took into account the latest judicial developments at both the national (Belgian) and international (European) levels;
- These texts are meant to protect the rights and interests of researchers while striving to make datasets as widely and fairly reusable as possible;
- As such, they are very long and technical, which is why writing them preemptively and letting our depositors choose among them is preferable to delegating to them the responsibility of writing or finding ready-made terms of use for their datasets;
- These access & reuse regimes are also written in accordance with all of our rules and policies, which is why choosing one of them (and not altering their contents) is mandatory.

That is why we were wondering if there might be a way to hide the "None" option in the template dropdown menu, thus in effect making the choice of a template mandatory.

**Comment by BPeuch** [comment]
I also think it would interesting to combine the possibility of imposing dataset templates with the ability to make certain metadata fields uneditable by regular users — though such fields should still show both in the form the depositor must fill in and in the end result, the metadata record — so that users cannot e.g. choose a template and then (malevolently or unwittingly) remove the contents of the prepopulated fields.

@philippconzett suggested the possibility of making metadata fields uneditable in issue #6889.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
