### ISSUE TITLE
Display Dataset Publication Date in Summary Dataset Information (above tabs)

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#696]
---

Author Name: **Eleni Castro** (@posixeleni)
Original Redmine Issue: 4150, https://redmine.hmdc.harvard.edu/issues/4150
Original Date: 2014-06-24

---

ODUM reported that they could not see information about when the Dataset was published. We should make the Dataset Publication clear to users by either displaying it in the Dataset Summary (above tabs/fold) or in the Citation Block. Right now it only displays in the citation, which does not clearly state that this is the Publication Date. This element is not in the metadata tsv files so would need to be put to display some other way.

**Comment by eaquigley** [comment]
@mcrosas what are your thoughts on displaying this as one of the fields above the tabs on a dataset page? we haven't gotten much feedback from others saying they can't figure out where the publication date is displayed.

**Comment by mcrosas** [comment]
@eaquigley  seems reasoanble

**Comment by eaquigley** [comment]
passing to @scolapasta to determine what milestone this fits best in. we will be adding the Publication Date as a metadata field that displays above the tabs in the box

**Comment by eaquigley** [comment]
Checked in dataverse-demo and the Publication Date is now showing in the citation part of the metadata tab. Passing to @kcondon to close.

**Comment by kcondon** [comment]
Publication date appears in citation block, closing.
