### ISSUE TITLE
Add release note instructions for migrating servers from Glassfish 4 to Payara 5 

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#6961]
For Dataverse 5, we are dropping support of Glassfish 4 for Payara 5. We have a new installer and documentation for new installations, but we need to add to the release notes what existing installations should do to migrate their servers.

**Comment by scolapasta** [comment]
There are two possible paths:
• take existing domain and move into a fresh Payara installation (with some tweaks)
• use the installer to set everything up then re add needed jvm options and connection to exisitng DB

We discussed at tech hours and are leaning towards the first one - @landreev will add what he currently has for instructions in this issue and we can review to make sure that it works.

**Comment by djbrooke** [comment]
- @landreev and @donsizemore have been doing some experiments here
- Domain move is the option we want to go with here
- We have instructions here, there is a potential issue if there are things included in Payara 5.x (Hazelcast) that aren't handled in Glassfish. 
- Plan is to get it in PR and move it along there

**Comment by donsizemore** [comment]
@landreev I just retested the pseudo-RST I wrote and successfully moved domain1 from Glassfish 4 to Payara 5.

You were correct - on launch Payara copied domain.xml to domain.xml.bak, modified some settings, and added others, among them:

```
>       <phone-home-runtime-configuration phone-home-id="2e9ae397-0e21-4104-8bc8-94ac430f50ee"></phone-home-runtime-configuration>
>       <notification-service-configuration>
>         <log-notifier-configuration></log-notifier-configuration>
>       </notification-service-configuration>
>       <hazelcast-config-specific-configuration></hazelcast-config-specific-configuration>
>       <hazelcast-config-specific-configuration></hazelcast-config-specific-configuration>
>       <payara-executor-service-configuration></payara-executor-service-configuration>
>       <zendesk-support-configuration></zendesk-support-configuration>
>       <stuck-threads-checker></stuck-threads-checker>
>       <health-check-service-configuration>
>         <log-notifier></log-notifier>
>       </health-check-service-configuration>
>       <asadmin-recorder-configuration></asadmin-recorder-configuration>
>       <metrics-health-check-configuration></metrics-health-check-configuration>
>       <microprofile-config></microprofile-config>
>       <request-tracing-service-configuration>
>         <log-notifier></log-notifier>
>       </request-tracing-service-configuration>
>       <amx-configuration></amx-configuration>
>       <admin-audit-configuration></admin-audit-configuration>
>       <microprofile-metrics-configuration></microprofile-metrics-configuration>
>       <ejb-invoker-configuration></ejb-invoker-configuration>
>       <rest-monitoring-configuration></rest-monitoring-configuration>
>       <microprofile-openapi-configuration></microprofile-openapi-configuration>
>       <microprofile-fault-tolerance-configuration></microprofile-fault-tolerance-configuration>
```

With your permission I'll submit the instructions I have as a PR if you'd like.

**Comment by landreev** [comment]
@donsizemore 
> With your permission I'll submit the instructions I have as a PR if you'd like.

That would be much appreciated! I was going to copy-and-paste the current instruction into a PR myself... it's going to be a PR with just one release note, correct?  - Either way works, thank you for all the testing!
