### ISSUE TITLE
File thumbnail upload fails silently with uppercase file extension

### ISSUE THREAD

**Issue by adam3smith** [IQSS/dataverse#6967]
Tested on demo.dataverse.org and QDR using 4.20-qdr build using Chrome and Firefox on Windows.

Uploading a thumbnail file for a dataset (via Edit --> Thumbnails + Widgets) fails silently for file extensions in uppercase: Upload appears to succeed, but then the file just vanishes and the previous thumbnail remains. 
Example: This fails
![Croaky1](https://user-images.githubusercontent.com/128986/83918352-8f2f1c00-a746-11ea-87cd-818b9c4cd504.JPG)

This works:
![Croaky1](https://user-images.githubusercontent.com/128986/83918372-99511a80-a746-11ea-9649-34b3c9585411.jpg)

**Comment by pdurbin** [comment]
@adam3smith can you please try on https://demo.dataverse.org again? It's running 5.11.1 now and the uppercase "JPG" version seems to work for me:

<img width="1356" alt="Screen Shot 2022-10-12 at 10 49 29 PM" src="https://user-images.githubusercontent.com/21006/195487594-bf8f81af-4fe8-43c0-8b30-04ddf1c0f920.png">

**Comment by adam3smith** [comment]
Works now, thanks!
