### ISSUE TITLE
DVUploader uploading files larger then 2 gb

### ISSUE THREAD

**Issue by jmjamison** [IQSS/dataverse#6971]
I'm trying to use DVUploader for large geodatabases (gdb files).   This works fine with files around 2 gb but over that, for example 2.87 gb.

Over that and i get:
Jun 08, 2020 1:32:54 PM org.apache.http.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request to {s}->https://dataverse.ucla.edu:443: Software caused connection abort: socket write error
Jun 08, 2020 1:32:54 PM org.apache.http.impl.execchain.RetryExec execute

This is an aws s3 bucket and I've raised :MaxFileUploadSizeInBytes to 8gb but that doesn't seem to help.

**Comment by pdurbin** [comment]
@jmjamison hi! DVUploader has a dedicated repo so it would probably be better to open an issue there: https://github.com/GlobalDataverseCommunityConsortium/dataverse-uploader/issues

**Comment by jmjamison** [comment]
Sorry, will post over there.

**Comment by pdurbin** [comment]
@jmjamison no worries! Thanks for opening https://github.com/GlobalDataverseCommunityConsortium/dataverse-uploader/issues/4
