### ISSUE TITLE
File Upload: Rsync upload button not presenting rsync script popup, not working

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#6975]
Rsync upload (Big Data) was released in v4.8. With recent button changes, rsync upload was tested against the released version 4.20 and found not to be working. Using a mock DCM, functionality was confirmed working in v4.8 and not working in 4.20. It is not known in which version this stopped working. There are no server log errors.

The issue may only be in calling the rsync download rsync upload script popup. In 4.8, clicking the upload button presents this popup, the user downloads the rsync upload script, and the workflow continues. In v4.20, clicking the upload button takes the user to the files page, no popup, with a done button.

**Comment by felker13** [comment]
In DataCaptureModuleServiceBean.java inretreiveRequestedRsyncScript function I found this code:
HttpResponse<JsonNode> scriptRequest = Unirest.post(scriptRequestUrl)
                                                   .field("datasetIdentifier", datasetIdentifier)
                                                   .asJson();
Where scriptRequestUrl is http://{dcm_url}/sr.py
The URL returns a python file, not a json. Then in the com.mashape.unirest.http.HttpResponse class this code will be executed:
if (JsonNode.class.equals(responseClass)) {
                    jsonString = (new String(rawBody, charset)).trim();
                    this.body = new JsonNode(jsonString);
...
}
where jsonString is the content of the python file, so the new JsonNode(jsonString) call throws an exception.

**Comment by pdurbin** [comment]
Related:

- #8985
