### ISSUE TITLE
Big Data: Mock DCM scripts need to be updated to support Python 3.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#6976]
The mock DCM is needed to test rsync in a dev mode. Since it was first created, python 3 has become the main released version, with python 2 is no longer supported as of 1/2020. The incompatibility may be fairly simple: it complains about needing a string type rather than byte type, which appears to be a simple difference between the two versions.

I have not tested but am guessing the actual DCM project has a similar issue.

Please note there is a supporting mock dcm script that tests the configuration, which should also be updated.

**Comment by pdurbin** [comment]
Related:

- #8985
