### ISSUE TITLE
RData ingest

### ISSUE THREAD

**Issue by WickM** [IQSS/dataverse#6985]
RData Import Problem descriped in this threath.
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/dataverse-community/fktZwaoV4yg/AzWRc0heBQAJ

Tabular data ingest failed. Unknown exception occured during ingest; R Tab File Parser: Could not obtain varQnty from the dataset metadata

**Comment by pdurbin** [comment]
Developers, note that "dat.RData" can be downloaded from the thread above.

**Comment by kuriwaki** [comment]
The dat.RData file given in the thread seems like only like length-one character vector.

<img width="216" alt="image" src="https://user-images.githubusercontent.com/8290417/92038607-a9769700-ed41-11ea-8a91-c0da0d8ef273.png">

Unlike dta's/csv's, RData is not guaranteed to be rectangular -- most RData files in the wild aren't. So I'm not sure if it is a good default to try ingesting every RData/Rds file that comes in.

**Comment by pdurbin** [comment]
Related:

- it's already possible to skip ingest via API #8532
- here's a request to be able to skip ingest via UI (a "skip ingest" checkbox) #2199
