### ISSUE TITLE
"Return to Author" button should actually be "Return to Owner"

### ISSUE THREAD

**Issue by BPeuch** [IQSS/dataverse#6989]
Version: 4.20

Hello everybody,

A modest proposal: Change "Author" into "Depositor" in the label of the "Return to Author" button, as a dataset's depositor is not always (one of) its author(s).

![rta](https://user-images.githubusercontent.com/15209224/84900059-dd7ade00-b0a9-11ea-8dd7-dccc27b95813.png)

**Comment by pdurbin** [comment]
Just a reminder of this issue:

- User Guide - Create a Glossary of Terms #4274

**Comment by BPeuch** [comment]
I really like the change in version 5+ where the "Contact" button on a dataset's webpage has been changed to "Contact Owner." I think it would likewise make sense to actually rephrase the aforementioned button as "Return to Owner" and not "Depositor" for the reasons mentioned [here](https://github.com/IQSS/dataverse/issues/7252#issuecomment-876989040).

**Comment by pdurbin** [comment]
@BPeuch in case you aren't aware, you can change stuff like this in your installation by editing a local copy of Bundle.properties.
