### ISSUE TITLE
Groups Documentation for admins: merge scattered info into single guide page

### ISSUE THREAD

**Issue by poikilotherm** [IQSS/dataverse#6992]
As discussed with @pdurbin on IRC, this issue is about making all information about group administration appear in one place of the admin guide.

Currently, admins will have to dig out all the informations scattered across the guides or even need to look deep in API guide or code for explicit groups.

This will need to merge or reference to:
- IP groups
- Global explicit groups (see #2412)
- Mail Domain groups (see #6936)
- Shibboleth groups

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.

**Comment by DieuwertjeBloemen** [comment]
While preparing the quickstart guides (e.g. how to [publish a collection](https://docs.google.com/document/d/1JtBJyWN2sOpSowyUWYU_77mQhKP1m35ZlUMB_0RXoKc/edit?tab=t.0#heading=h.29b55jb6wa7e)), we noticed there is no explanation on how to create and manage a group in a collection. You can see in the index that all the editing options are there except the groups one: [https://guides.dataverse.org/en/latest/user/dataverse-management.html](https://guides.dataverse.org/en/latest/user/dataverse-management.html)
There is some information on how to grant a group permissions under the permissions setting, but I couldn't find anything about actually managing groups.
