### ISSUE TITLE
License & Terms Dataset Page Tab: Guestbook, Use & Access Requirements

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#701]
---

Author Name: **Elizabeth Quigley** (@eaquigley)
Original Redmine Issue: 4157, https://redmine.hmdc.harvard.edu/issues/4157
Original Date: 2014-06-26
Original Assignee: Gustavo Durand

---

Feature from 3.6 that dataverse owners and admins use to keep track of requests for data use and downloads.

**Comment by scolapasta** [comment]
Can this be passed to QA and closed? (as there are specific issues already being opened separately?)

**Comment by eaquigley** [comment]
Passing this ticket to QA since I've confirmed there are individual tickets created for remaining issues.

**Comment by kcondon** [comment]
OK, tested this reasonably well, found a bunch of issues that have been reported separately. Closing.
