### ISSUE TITLE
As a user I don't want to be confused by a non-working signup link if signup is disabled

### ISSUE THREAD

**Issue by poikilotherm** [IQSS/dataverse#7011]
Howdy. In #6170, #6246, 46e0188 a link to sign up has been added to the login page.

While this makes perfect sense, some of our users are confused about that link. We disabled signup for Jülich DATA, so clicking the link leads to a 401 error.

PR forthcoming to add rendering logic.

**Comment by TaniaSchlatter** [comment]
Hi @poikilotherm, I am keeping an [inventory of installation customizations](https://docs.google.com/presentation/d/1etY4S7w9oi9cccWLoDi92h1KGjcxzpZ3k59Wesja6bU/edit#slide=id.g8901cf666d_2_12) that affect the UI. When you have a chance, can you please explain how the installation manages user accounts, and why? This will help us take variations into account when planning design changes.
