### ISSUE TITLE
Python Installer: 2 Issues on develop branch: handshaker fails to deploy, setup-all.sh fails to run but install completes without error.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#7013]
Currently, using develop branch, I'm seeing two issues with the python installer.

1. Installer exits, fails to deploy war file with handshaker error in logs. This is a known issue between payara and a specific version of jvm:  https://github.com/payara/Payara/issues/4625 . There is a temp workaround, updating some jvm-options. My understanding is this will be resolved with a patched version of Payara so we'll either need to add the workaround for now or wait for the new Payara, then update installer doc download links.
2. Installer completes but does not run setup-all.sh. This is inferred due to the 500 error when loading the home page and the could not find root dv error.

**Comment by landreev** [comment]
OK, so we reason we didn't run into the issue 1. during QA of the installer-updated-for-payara, because we were using java 1.8.0 build number < 252? 
(for example, I have build 1.8.0_231-b11 on my MacOS box)
OK, so this makes sense - would be easy to add to the installer.

**Comment by landreev** [comment]
tagging #6853 (issue 1. above)

**Comment by donsizemore** [comment]
@kcondon I think this was resolved by https://github.com/IQSS/dataverse/pull/7036 ?
