### ISSUE TITLE
consider payara-5.2020.2 for Dataverse 5

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#7017]
Release Notes at https://github.com/payara/Payara/releases/tag/payara-server-5.2020.2

Would resolve issue #6853 and includes an updated jakarta.faces jar to match the one Gustavo built, which would reduce complexity in the Dataverse installer. The jars differ only in the Mojarra version: 2.3.14.payara-p1 vs 2.3.14.payara-p2

There's a dataverse-ansible branch for testing: https://github.com/IQSS/dataverse-ansible/compare/211_payara_5_2020_2

Pull request forthcoming pending IQSS approval.

**Comment by djbrooke** [comment]
Thanks @donsizemore, it would be great to release on an unpatched version if possible. I'll add this to the Dataverse 5 milestone for now. @scolapasta please take a look and add some details about whether we should include this or not -- thanks.

**Comment by scolapasta** [comment]
Yes, if we can release without a patched jar, that would be great. It should be straightforward if this version contains the fix that I added to the jsf jar. I will take a look to confirm.
