### ISSUE TITLE
Get API test suite passing 😴 😴 😴

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#7020]
[ERROR]   FilesIT.testForceReplaceAndUpdate:649 expected:<200> but was:<400> should be fixed in pull request #6968 but there are a variety of other test failing with 500 errors.

As of b97185abc I saw the following tests failing on an EC2 instance...

[ERROR]   DatasetsIT.testAddRoles:1197 expected:<200> but was:<500>
[ERROR]   FilesIT.testReplaceFileBadJson:898 Expected status code <200> doesn't match actual status code <500>.
[ERROR]   FilesIT.test_006_ReplaceFileGood:340 Expected status code <200> doesn't match actual status code <500>.

... but these are just examples. If you go to https://jenkins.dataverse.org/job/IQSS-dataverse-develop/test_results_analyzer/ you can see recently failing tests. Here's a screenshot:

<img width="833" alt="Screen Shot 2020-06-25 at 2 00 36 PM" src="https://user-images.githubusercontent.com/21006/85773845-42f34e00-b6ec-11ea-9dab-81caac4f32b2.png">

Long term, we'd like to figure the root cause of the 500 errors (believed to be database deadlocks, see #6865) but for now we plan to sprinkle in some sleep statements as necessary. 😴 😴 😴

**Comment by djbrooke** [comment]
I'm going to close this, as I believe it's been superseded by #6865 and #7069.
