### ISSUE TITLE
Breadcrumb trail disappears after deleting / replacing file

### ISSUE THREAD

**Issue by philippconzett** [IQSS/dataverse#7027]
After issue [#7026](https://github.com/IQSS/dataverse/issues/7026), there was no breadcrumb trail available anymore to navigate back to the dataset:

![image](https://user-images.githubusercontent.com/21955790/85881436-e07a7a80-b7dd-11ea-9325-1b35eb5ce0ab.png)

**Comment by djbrooke** [comment]
@philippconzett I'm not going to close this one yet because I'm not as confident they are related, but can you try to reproduce this after the fix suggested in https://github.com/IQSS/dataverse/issues/7026#issuecomment-650315270 ? Thanks!

**Comment by pdurbin** [comment]
@philippconzett hi! Are you still having this problem?

**Comment by philippconzett** [comment]
Thanks for the reminder, Phil, and sorry for my late reply. I sust tested this once more in our current production environment (Dataverse v. 5.6). After deleting a file when being on the file landing page, I was redirected to the dataset landing page, which makes sense. I'll close the issue.
