### ISSUE TITLE
Error when trying to replace file

### ISSUE THREAD

**Issue by philippconzett** [IQSS/dataverse#7028]
Earlier today I tried both to delete (cf. [#7026](https://github.com/IQSS/dataverse/issues/7026)) and replace a file. When trying to replace the file, I got this error message:

![image](https://user-images.githubusercontent.com/21955790/85881696-5383f100-b7de-11ea-8c0a-f872c8dcb55c.png)

**Comment by djbrooke** [comment]
Hey @philippconzett - can you test this again after running the script that @pdurbin mentions in https://github.com/IQSS/dataverse/issues/7026#issuecomment-650315270 ? I think it may be related. Feel free to comment if it still occurs and we'll reopen for investigation.
