### ISSUE TITLE
Error pages are application/xhtml+xml

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#7043]
Unlike Dataverse's normal pages which are delivered as mimetype text/html despite their .xhtml extensions, the error pages (403.xhtml, 404.xhtml, and 500.xhtml) are sent as application/xhtml+xml. This doesn't directly affect how they work, but this breaks some uses of javascript in those pages, i.e. use of jquery to dynamically add content in a custom header or footer breaks as doing something like $('#header').html('something'); doesn't work - the html() method isn't allowed/supported on xhtml+xml. 

QDR has this issue - I don't know if there are others affected, and I haven't checked whether other scripts, such as the google analytics are affected on these pages. 

A quick fix I've found is to add the .xhtml extension to the mime-map in web.xml. I haven't seen any side effects. I'll submit a PR with that change, but if there are better ways to handle this, let me know.

**Comment by qqmyers** [comment]
Can't reproduce - closing

**Comment by pdurbin** [comment]
Re-opening based on the comment by @luddaniel at https://github.com/IQSS/dataverse/pull/7044#issuecomment-824877625
