### ISSUE TITLE
Publish Dataset: On Metadata only changes, version popup only does minor version regardless of what is chosen.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#7051]
When making metadata only changes at publish time you are given a choice of minor, major, or update existing version. ~~When running on payara,~~ no matter which option you choose, you always get the first one, minor version. 

Correction: this happens with both gfish and payara and is possibly related to recent popup changes.

It is happening in develop, does not happen in 4.20

**Comment by scolapasta** [comment]
After a quick review of code and test, it doesn't look to be app server related (i.e. @kcondon and I both reproduced it on glassfish). There was some recent consolidation to this logic related to popups, @sekmiller can you take a look?

(I'll change the title to remove app server aspect)
