### ISSUE TITLE
Harvesting run infinitely stays at IN PROGRESS and DELETE IN PROGRESS

### ISSUE THREAD

**Issue by JingMa87** [IQSS/dataverse#7052]
When the issue occurs: When a harvesting client is running/deleting and on the server dataverse gets rebooted. Since the status in the database is still running/deleting, the user can't rerun or delete the client because the buttons are disabled.
Which page it occurs on: Root>Dashboard
To whom it occurs: People who harvest
Version: 4.20

**Comment by JingMa87** [comment]
@pdurbin I did notice one more issue, which is that not all metadata is deleted correctly when the server reboots during the deletion of a harvesting client. I might make a fix for this in the future.

**Comment by pdurbin** [comment]
Related:

- #7940

Also, while I'm here, thanks again for all the harvesting-related PRs, @JingMa87! 🎉

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
