### ISSUE TITLE
direct download causes RedirectException

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#7060]
On the current develop branch, setting -Ddataverse.files.s3.download-redirect=true and trying to download a file gives me:

{
"status": "ERROR",
"code": 500,
"type": "RedirectionException",
"message": "Internal server error. More details available at the server logs.",
"incidentId": "113fbb33-f4e0-402e-b9a9-5417c3c9822b"
}

If I remove that jvm option, I can download the file, so I think the underlying s3 store is configured correctly. WHen I use:
bin/asadmin set-log-levels edu.harvard.iq.dataverse.api.DownloadInstanceWriter=FINE
the presigned download URL that shows in the log is actually correct/works, so it looks like something has changed in how the redirect is processed in Dataverse. 

FWIW: I used the ansible scripts to create an EC2 instance and configured s3 manually after that.

**Comment by qqmyers** [comment]
Looks like the 500 error is being generated by the api.errorhandlers.ThrowableHandler class. Perhaps what's needed is a class to implement ExceptionMapper<RedirectionException>? Not sure why this would have changed from 4.20 to current develop branch though unless some default handler for that has disappeared/not been configured.

**Comment by qqmyers** [comment]
That seems to work - I'll put in a PR.

**Comment by poikilotherm** [comment]
/me added a lengthy discussion about what `ThrowableHandler` is about and what IMHO should be done now to the PR at https://github.com/IQSS/dataverse/pull/7085#issuecomment-658652903
