### ISSUE TITLE
Update to Dataverse 4.20

### ISSUE THREAD

**Issue by youssefOuahalou** [IQSS/dataverse#7065]
Hello erveryone,
When I upgraded from 4.19 to 4.20 I copied and pasted elements that I didn't need for the s3 store. 
![CopyPastFail](https://user-images.githubusercontent.com/46802308/86943975-689a4180-c147-11ea-816b-0dc13cb9faa1.png)
Do you think I can still have problems with this?
I manually delete it in the domain.xml file for s3 store.

**Comment by pdurbin** [comment]
@youssefOuahalou it sounds like you accidentally added some JVM options related to S3 that you don't need. (Maybe we should make this more clear in the release notes that only one set of commands should be executed.) Then you deleted those JVM options from your domain.xml file. This sounds fine. My only suggestion would be to restart Glassfish.

**Comment by youssefOuahalou** [comment]
Yes this is what I did directly after noticing my error, and thank you for your answer ☺

**Comment by djbrooke** [comment]
@youssefOuahalou, I'm going to close this, feel free to leave a comment here if you feel it should be reopened
