### ISSUE TITLE
Harvesting: Get rid of this seemingly meaningless and noisy log entry

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#7073]
When harvesting I see this error a lot and it provides no meaning at all but is very noisy. This one was taken from prod using the Princeton_Authored_Datasets set

[2020-07-11T14:40:44.319+0000] [Payara 5.201] [WARNING] [] [edu.harvard.iq.dataverse.DataCitation] [tid: _ThreadID=183 _ThreadName=__ejb-thread-pool1] [timeMillis: 1594478444319] [levelValue: 900] [[
  Unable to find citation date for datasetversion: 2753]]

**Comment by landreev** [comment]
I believe this logging message is from indexing; we are getting the same noise in the logs when we run indexAll. So it's not specific to harvesting. But we should fix this.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
