### ISSUE TITLE
Known field types in a dataset also causes the whole dataset to fail from being harvested

### ISSUE THREAD

**Issue by JingMa87** [IQSS/dataverse#7076]
When the issue occurs: When harvesting using dataverse_json and there's custom types like "titulo" or "mraCollection"
Which page it occurs on: Harvesting Dashboard
To whom it occurs: People who harvest using dataverse_json
Version: 4.20
Extra info: This issue expands on issue https://github.com/IQSS/dataverse/issues/7056

**Comment by pdurbin** [comment]
This issue seems to be related:

- Harvest: Json format harvest fails with unknown field when field exists on client. #7075

**Comment by JingMa87** [comment]
@pdurbin Oh they're the same actually, can you delete this issue for me?

**Comment by pdurbin** [comment]
I looked at https://docs.github.com/en/github/managing-your-work-on-github/deleting-an-issue but I don't see a way to delete issues so I'll just close it.
