### ISSUE TITLE
Changes to DOI Updating upon Dataset deletion were reverted

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#7078]
As part of the Community call discussion last night, I looked into what happens to the DOI state for a dataset that is destroyed in Dataverse. It looks like the current develop branch will not do anything to the DOI (at least for DataCite) if the dataset being destroyed has been published. With pointers from @djbrooke, I realized that the changes in #6060 to address #2471 have been reverted by #6901 from @pdurbin . #2471/#6060 sets many of the metadata fields to :unav and switches 'findable' DataCite DOIs to registered to stop them from being indexed. If that's still the intended behavior, I think this code has to be restored/adapted to work with #6901 (perhaps this was temporarily dropped to simplify getting the DOI reservation work in place?).

**Comment by qqmyers** [comment]
FWIW: was able to test ( :-) ) the delete published dataset command in 4.20 and confirmed that it set the DOI to registered as it should (e.g. the code that was accidentally removed looks like it was working, so OK to restore it).

**Comment by qqmyers** [comment]
In looking through #6901 and the DataCite code, I came up with several other things that could/should be discussed/fixed. The first three might be worth figuring out for 5.0, the rest are longer term (and perhaps already known/in other issues)

- The api uses Bundled strings to i18nize the API responses - that is different than most calls and probably not best practice (calling different Dataverse instances will return different API responses)
- The api adds /delete and /reserve to the HTTP DELETE and HTTP POST calls for those functions - more RESTful if the URL didn't repeat the function
- The Pids API is only for Datasets, not Datafiles at present but it will presumably need to work with both going forward - this might be another candidate for labelling the calls 'experimental' as I suggested for some of the direct upload calls

- The rest api URL should probably be added to the DataCiteRESTfulClient class and that class should be used to do the PID-related API calls - it uses a shared HttpClient that will be more efficient that creating one on the fly
- The PidUtil class is just handling the DataCite call to retrieve metadata at this point which could go in the DataCiteRESTfulClient as well. There's already a call to the older api (mds) to get the metadata in XML there - not clear we need both.
- The DOI cache that isn't really used is still in the code waiting to be pulled out
-The Pids api delete only deletes draft DOIs - which is different than the DestroyDataset and DeleteDataFiles commands which will also destroy an already public PID (per #2471). Right now the deleteIdentifier calls for the individual PID services handle both actions - wondering if it would be better to separate those in the servicebeans. (If not, we just need to avoid calling deleteIdentifier on released objects in API calls as is now done in the Pids api).

**Comment by pdurbin** [comment]
I just wanted to note that @qqmyers and I had a lovely conversation this morning and at least touched on all of the above points.

The decision to start translating new and being-worked-on APIs to English was made, maybe at standup, at least a year ago, I'd say. I suggested bringing it up at tech hours.

I definitely agree that we should be careful designing our APIs and that flagging some of them as experimental in some way might make sense.

**Comment by qqmyers** [comment]
re: i18n - after discussion I think my concern in this case relates to the error message only sending the http status from DataCite in an i18n'ed message and I think that status code could be something that a remote app might want to use. Perhaps having a an additional statuscode key in the json response would make sense and so that the i18n'ed message is just for humans.
