### ISSUE TITLE
Access Dataset + Download "All Files" - Update Guides and Analytics

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#7079]
With the new dataset level download option under the new Access Dataset btn (#7047) the User Guide should be reviewed and updated to outline this new feature.

There should also be updates to the analytics event tracking sample code provided in the Installation Guide, as the download format and size included in the dropdown option text is sent to the Google Analytics reports. That text should be stripped in order to keep the category and values consistent for reporting purposes. Inclusion of varying file sizes in the reports will prohibit those events from being grouped and properly counted.

![Screen Shot 2020-07-01 at 3 47 34 PM](https://user-images.githubusercontent.com/21006/86285243-3f5f3b80-bbb2-11ea-9535-f14bf247bb13.png)

<img width="1167" alt="Screen Shot 2020-07-14 at 9 38 09 AM" src="https://user-images.githubusercontent.com/687227/87432261-c13d6480-c5b5-11ea-9b67-99181017f93a.png">

**Comment by djbrooke** [comment]
@mheppler or whatever analytics wizard takes this on next... I created branch https://github.com/IQSS/dataverse/tree/7079-guides-download-all-and-analytics with the guides edits. Feel free to build on this.

**Comment by mheppler** [comment]
Thank you, @djbrooke. Added my assignment, will pick this back up when the PR #7047 for the download option links moves forward.

**Comment by mheppler** [comment]
Added analytics function to strip ZIP size from link text used to track clicks of new download all files options under the Access Dataset btn.

<img width="1049" alt="Screen Shot 2020-07-22 at 9 07 14 AM" src="https://user-images.githubusercontent.com/687227/88185666-376b4800-cc02-11ea-895f-864dc47fb018.png">
