### ISSUE TITLE
Dataset Page Filter, Sort, and Search Updates

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#7082]
Various updates of the Filtering, Sorting, and Searching functionality on the Dataset page.

In scope:

- Improve responsive layout of file table sort/filter/search, file metadata and action buttons
- Styling updates to the sort/filer/search functions
- Enable search of File Tags (previously #4122)

Possibly in scope:

- Let's review the file tag issues in #6074 for possible inclusion. 

Pulling this out as an individual issue from #6605. Link to mockups: https://sketch.cloud/s/o5ZK3/a/OMPJGR

**Comment by djbrooke** [comment]
Met with @TaniaSchlatter @scolapasta and @mheppler about this earlier today. We'll move #6074 ahead of this and revisit this in a few weeks, once we start to fix up the bugs and add features that make file tags more useful.

**Comment by mheppler** [comment]
These follow dataset redesign issues should move forward before picking this up.
- Dataset Page - File Options Kebab Btn 🍡 #7081
- Preview Tools - New external tool preview type config setting, icon btn on dataset/file pgs #6919

**Comment by TaniaSchlatter** [comment]
Expected outcomes are as follows if a file tag is applied to a tabular file: 

- the tag should appear in the "File Tag" drop down above the file table.

- users should be able to filter by tabular file tag term in advanced search.

- searching for the term on the tag (only the term, like "survey") in the file table returns results that have the "survey" tag applied 

- searching for the term on the tag on the advanced search page also returns results that have the tag applied. 

- we will not change the order of results as part of this effort (current order is alphabetically by the number of times the term appears).
