### ISSUE TITLE
S3 Nutanix not found!

### ISSUE THREAD

**Issue by felipecastro-fiocruz** [IQSS/dataverse#7083]
Hello everybody!!

We are trying to implement the dataverse with Nutanix ObjectStore S3, but so far without success.

We followed the manual, did more research and added the lines below to the domain.xml

        <jvm-options> -Ddataverse.files.s3.type = s3 </jvm-options>
        <jvm-options> -Ddataverse.files.s3.label = s3 </jvm-options>
        <jvm-options> -Ddataverse.files.s3.bucket-name = dataverse </jvm-options>
        <jvm-options> -Ddataverse.files.s3.custom-endpoint-url = ocl01.fiocruz.br: 7200 / objectstore / </jvm-options> (In this line we've tried without the "objectstore")
        <jvm-options> -Ddataverse.files.s3.path-style-access = true </jvm-options>
        <jvm-options> -Ddataverse.files.s3.custom-endpoint-region = us-east-1 </jvm-options>
        <jvm-options> -Ddataverse.files.s3.chunked-encoding = false </jvm-options>
        <jvm-options> -Ddataverse.files.storage-driver-id = s3 </jvm-options>

In /usr/local/glassfish4/glassfish/domains/domain1/logs/server.log appears:

"Failed to save dataset logo: ERROR: S3AccessIO - Failed to look up bucket dataverse (is AWS properly configured?)]"

We are already out of ideas, can someone help me? Is the domain.xml missing or is there something wrong?

**Comment by djbrooke** [comment]
Hi @felipecastro-fiocruz - can you please take a look at the guides on the develop branch (https://github.com/IQSS/dataverse/blob/develop/doc/sphinx-guides/source/installation/config.rst) instead of guides.dataverse.org? There was a formatting issue that was causing some of the documentation to not appear correctly on guides.dataverse.org. This may be related.

**Comment by felipecastro-fiocruz** [comment]
Djbrooke, thanks for the answer!

We had already followed that guide. But unfortunately it didn't work. Do I still need to add or remove any line in my domain.xml?

**Comment by felipecastro-fiocruz** [comment]
Thanks for the answer!

We had already followed that guide. But unfortunately it didn't work. Do I still need to add or remove any line in my domain.xml?

**Comment by qqmyers** [comment]
One potential issue is that the user that glassfish is running as needs to have a profile with the credentials for your S3 server. For AWS, that's in a .aws subdirectory for the user. (And if your bucket is accessible by a profile other than the default, there's a jvm option to tell Dataverse to use a named profile.)

**Comment by felipecastro-fiocruz** [comment]
The problem was solved.
I had left in the "/root/.aws/config" subdirectory the line "region=us-east-1"
 
When we deleted the contents of that subdirectory, the problem was solved (the region was already written in domain.xml).

Below is my domain.xml for use by friends who want to configure Nutanix S3 for the dataverse.

        <jvm-options> -Ddataverse.files.s3.type=s3</jvm-options>
        <jvm-options> -Ddataverse.files.s3.label=s3</jvm-options>
        <jvm-options> -Ddataverse.files.s3.bucket-name=dataverse</jvm-options>
        <jvm-options> -Ddataverse.files.s3.custom-endpoint-url=http://ocl01.fiocruz.br:7200</jvm-options>
        <jvm-options> -Ddataverse.files.s3.path-style-access=true </jvm-options>
        <jvm-options> -Ddataverse.files.s3.custom-endpoint-region=us-east-1</jvm-options>
        <jvm-options> -Ddataverse.files.s3.chunked-encoding=false</jvm-options>
        <jvm-options> -Ddataverse.files.storage-driver-id=s3</jvm-options>

**Comment by felipecastro-fiocruz** [comment]
The problem was solved.
I had placed in the "/root/.aws/config" subdirectory the line "region=us-east-1"
 
When we deleted the contents of that subdirectory, the problem was solved (the region was already written in domain.xml).

Below is my domain.xml for use by friends who want to configure Nutanix S3 for the dataverse.

        <jvm-options> -Ddataverse.files.s3.type=s3</jvm-options>
        <jvm-options> -Ddataverse.files.s3.label=s3</jvm-options>
        <jvm-options> -Ddataverse.files.s3.bucket-name=dataverse</jvm-options>
        <jvm-options> -Ddataverse.files.s3.custom-endpoint-url=http://ocl01.fiocruz.br:7200</jvm-options>
        <jvm-options> -Ddataverse.files.s3.path-style-access=true </jvm-options>
        <jvm-options> -Ddataverse.files.s3.custom-endpoint-region=us-east-1</jvm-options>
        <jvm-options> -Ddataverse.files.s3.chunked-encoding=false</jvm-options>
        <jvm-options> -Ddataverse.files.storage-driver-id=s3</jvm-options>

**Comment by djbrooke** [comment]
Great to hear, @felipecastro-fiocruz! I'll close this out, and we can point people here if there are other questions about Nutanix.
