### ISSUE TITLE
On dataverse.harvard.edu, password reset not showing messaging that email has been sent

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#7106]
On https://dataverse.harvard.edu/passwordreset.xhtml, putting in an email associated with a local account does not show the page with the message about the password reset email being sent. I did receive an email as expected.

On https://demo.dataverse.org/passwordreset.xhtml this works as expected and displays the informational message (screenshot attached).

<img width="972" alt="Screen Shot 2020-07-21 at 9 40 33 AM" src="https://user-images.githubusercontent.com/7773392/88062323-ae3b0f00-cb36-11ea-8c4b-01f31820024e.png">

**Comment by pdurbin** [comment]
Just as another data point it worked fine on some code that's only slightly behind develop. As of 06367261a, that is.

<img width="1284" alt="Screen Shot 2020-07-21 at 12 43 10 PM" src="https://user-images.githubusercontent.com/21006/88082611-f9ade700-cb4f-11ea-898e-9f88f1cedb20.png">

Demo and production are running 4.20.

**Comment by djbrooke** [comment]
Closing in favor of #7677
