### ISSUE TITLE
As a superuser, I would like to be able to deactivate or hide the "Position" field in Account Information

### ISSUE THREAD

**Issue by BPeuch** [IQSS/dataverse#7109]
Version: 4.20

Hello everybody,

Because we operate in Belgium, we have to comply with the European Union's General Data Protection Regulation (GDPR), which dictates among other things that anyone (private or public company, small or big) who collects personal information must be able to justify to what precise ends they collect this or that specific element of information.

Which is why our legal expert recently drew our attention to the fact that we do not really have a use for the content of the "Position" field in the users' Account Information, therefore she strongly recommended that we deactivate or hide this field.

But I don't think this is currently possible in Dataverse?

(Semi-related to issue #1444, in which the relevance of "Position" is called into doubt)

**Comment by poikilotherm** [comment]
This might be related to #6694

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
