### ISSUE TITLE
doi.mdcbaseurlstring and doi.baseurlstringnext are the same thing

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#7113]
The URL for the DataCite REST api (i.e. api.test.datacite.org or api.datacite.org in production) is currently (in develop) recorded via two jvm options (those in the title). The former (mdc...) was in 4.20 and is configured in Ansible. I'm not sure either name is great, but using the former would be backward compatible. If we can decide what single name to use, it should be easy to change the relevant code before we release 5.0

**Comment by djbrooke** [comment]
Thanks @qqmyers. I don't have a preference on the name, but I'm all for fewer duplicate options. It would be good to resolve for Dataverse 5.

**Comment by qqmyers** [comment]
How about doi.datacite.restapiurlstring and a release note that we're changing the mdcbaseurlstring as it a) DataCite-specific and b) now used for MDC and DOI reservations? I can do this is if it makes sense to everyone. (One question would be whether to allow backward-compatibility with a warning in the log to update. It might stop some support requests, but if people aren't following the update steps in general, this won't be the only failure).
