### ISSUE TITLE
Some elements in the DDI XML response have an incorrect sequence

### ISSUE THREAD

**Issue by JingMa87** [IQSS/dataverse#7127]
When the issue occurs: When harvesting a dataset with Geospatial Metadata
Which page it occurs on: It occurs when harvesting, so the Dashboard
To whom it occurs: People who harvest Geospatial Metadata
Version: 4.20

**Context**
The DDI XML response from Dataverse has multiple XSD validation errors which are being addressed one by one. This one deals with the sequence of elements.

Main issue: https://github.com/IQSS/dataverse/issues/3648
Geographic Bounding Box: https://github.com/IQSS/dataverse/issues/7108
Source attribute: https://github.com/IQSS/dataverse/issues/7128

**Comment by pdurbin** [comment]
@JingMa87 hi! What's the status of this issue, please? Above I see some PRs were merged and some were closed. Were you planning another PR or two to close it? Thanks.

**Comment by pdurbin** [comment]
@JingMa87 is no longer working on the issues he opened: https://github.com/IQSS/dataverse/issues/7412#issuecomment-1273464175

We should check with the DANS crew to see if any of them are still interested in this: @PaulBoon @janvanmansum @WittenbergM @LauraHuisintveld

**Comment by janvanmansum** [comment]
@pdurbin : no longer a priority for DANS.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
