### ISSUE TITLE
Editor has been renamed to contributor

### ISSUE THREAD

**Issue by tcoupin** [IQSS/dataverse#7129]
See #6662 

https://github.com/IQSS/dataverse/blob/941d17dd0c196f8443a9512db40e4be002cbe572/src/main/java/propertyFiles/BuiltInRoles.properties#L3

**Comment by djbrooke** [comment]
Hi @tcoupin, can you please tell us more about the issue here?

**Comment by tcoupin** [comment]
BuiltInroles must be updated: `role.editor.name` become `role.contributor.name`

It's not important for english since if the key is not founds, name and description from https://github.com/IQSS/dataverse/blob/941d17dd0c196f8443a9512db40e4be002cbe572/scripts/api/data/role-editor.json is used (in english too...)

But it is important for other language

**Comment by pdurbin** [comment]
I see. You want to make the following change...

```
$ git diff src/main/java/propertyFiles/BuiltInRoles.properties
diff --git a/src/main/java/propertyFiles/BuiltInRoles.properties b/src/main/java/propertyFiles/BuiltInRoles.properties
index 3c4b80200..115ccf6af 100644
--- a/src/main/java/propertyFiles/BuiltInRoles.properties
+++ b/src/main/java/propertyFiles/BuiltInRoles.properties
@@ -1,7 +1,7 @@
 role.admin.name=Admin
 role.admin.description=A person who has all permissions for dataverses, datasets, and files.
-role.editor.name=Contributor
-role.editor.description=For datasets, a person who can edit License + Terms, and then submit them for review.
+role.contributor.name=Contributor
+role.contributor.description=For datasets, a person who can edit License + Terms, and then submit them for review.
 role.curator.name=Curator
 role.curator.description=For datasets, a person who can edit License + Terms, edit Permissions, and publish datasets.
 role.dscontributor.name=Dataset Creator
```

... and then update BuiltInRoles.properties in the language packs to use the new keys? I see you opened https://github.com/GlobalDataverseCommunityConsortium/dataverse-language-packs/issues/76

Thanks for the tip that this doesn't affect English installations.

In a French installation, does it fall back to English? Or do you get an error?

**Comment by pdurbin** [comment]
@tcoupin hi! Are you thinking about making a pull request for this?

**Comment by tcoupin** [comment]
On my v5.10 stagging server with branch 5.10
![image](https://user-images.githubusercontent.com/7457386/193516776-268c3231-4dd9-4c86-a2f9-dd8444f8d306.png)

I will open a new PR on https://github.com/GlobalDataverseCommunityConsortium /
[dataverse-language-packs](https://github.com/GlobalDataverseCommunityConsortium/dataverse-language-packs)

**Comment by tcoupin** [comment]
2 PR opened on https://github.com/GlobalDataverseCommunityConsortium/dataverse-language-packs
1 PR on dataverse
