### ISSUE TITLE
Add Avgidea Data Platform to integration list

### ISSUE THREAD

**Issue by tyagihas** [IQSS/dataverse#7141]
Please consider adding the following product to the integration list, maybe under "analysis and computation".
https://www.avgidea.io/avgidea-data-platform.html

It's an add-on to Google Sheets and lets users import CSV data from Dataverse to a sheet directly.
https://gsuite.google.com/marketplace/app/avgidea/771437130061

Thanks.
Teppei

**Comment by djbrooke** [comment]
@tyagihas I put up a draft PR to add Avgidea to the integrations list, but when I tried the add-on in Google Sheets it didn't work. Is it still in beta?

**Comment by tyagihas** [comment]
@djbrooke Thank you for working on this.

How do you install the add-on?

This is an installation guide.
https://adp-tech.avgidea.io/add-on-installation

Also, if you login with Google G Suite account and your organization doesn’t allow individual installation, the administrator needs to change the policy.

**Comment by tyagihas** [comment]
@djbrooke 
Are you still having an issue with installation? Please let me know if the problem still persists (screen shot or error messages).

**Comment by djbrooke** [comment]
Hey @tyagihas, I've successfully installed the software. Before adding this to the integration list, I have two suggestions:

- I noticed it works on some files (like city_day_sum.csv, https://dataverse.harvard.edu/file.xhtml?persistentId=doi:10.7910/DVN/745ZS3/KVYDC4) and not others (fecundity_data_STSTA_JEB.csv, https://dataverse.nl/dataset.xhtml?persistentId=doi:10.34894/JIKZ4U). To make this more useful, I'd suggest excluding "Harvested" Files from the search results. 

- Files deposited into Dataverse go through an ingest process. Are you taking into account these files? I can't find files like this one in the search: https://dataverse.harvard.edu/file.xhtml?persistentId=doi:10.7910/DVN/0XOYTG/RIYVNR&version=1.0. On that page, note that there's a download dropdown and the original file can be downloaded in .csv. Many files in Dataverse go through this process and you should add handling for this.

**Comment by tyagihas** [comment]
Thank you for feedbacks. I will work on them.

Can I just confirm a few things?
Item 1 : 
By analyzing returned search response, it seems existence of "file_persistent_id" is the attribute to differentiate between "Harvested" and non-Harvested (ie. downloadable CSV file). Only non-Harvested response contains "file_persistent_id".
Is that correct?

Item 2 : 
I think this is because we search files based on "fileContentType=text/csv" and the file you mentioned seems stored as "fileContentType=text/tab-separated-values"
https://dataverse.harvard.edu/api/search?fq=df.tab%20&q=fileContentType%3Atext%2Ftab-separated-values

Is it possible to specify two fileContentType for a single search? If not, we can run two searches separately and aggregate them.

**Comment by djbrooke** [comment]
Hey @tyagihas, people on the Google Group may have some better answers, but I'll try to answer below.

- I think harvested is a facet that can be included in the search with "show_facets". See the "advanced search" example in the Search API Guide: http://guides.dataverse.org/en/latest/api/search.html. What you suggest may work as well, but I'd suggest the facet as a first step. You could exclude the harvested results. Others may have better ideas.  
- You should be able to use the API to get the original file (csv is this case) by adding "original" in the API call. See http://guides.dataverse.org/en/latest/api/dataaccess.html for more information. 

Hope this helps!

**Comment by tyagihas** [comment]
@djbrooke 
Thanks for your advice. I changed the code and just deployed new version of the add-on.
If you still open the sheet, please re-open and try it.

Thanks!
Teppei

**Comment by djbrooke** [comment]
@tyagihas much better, thanks. There are now multiple instances of Dataverse (dataverse1 and dataverse2, as well as ckan1 and ckan2) so you probably want to address that. Also, I think limiting it to 10 rows extremely restricts the usefulness of the application. I hope you'll consider this feedback as you continue to work on Avgidea.

**Comment by tyagihas** [comment]
@djbrooke 
The reason why I made different types of instances for ckan and dataverse is that they return different search results. I guess they are running different versions of the software.
I agree about the limit so just raised to 100 and already deployed the add-on.
