### ISSUE TITLE
install.py ignores non-interactive HOST_DNS_ADDRESS setting

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#7144]
install.py ignores the default.config HOST_DNS_ADDRESS setting:
https://github.com/IQSS/dataverse/blob/develop/scripts/installer/install.py#L150

In EC2 instances this results in an FQDN JVM-option like:

`<jvm-options>-Ddataverse.fqdn=ip-172-31-79-10.ec2.internal</jvm-options>`

and would be used in the dataverse.siteUrl value, which instead produces:

`<jvm-options>-Ddataverse.siteUrl=http://${dataverse.fqdn}:8080</jvm-options>`

Since we want to keep both FQDN and siteUrl values for now, I propose adding an `if nonInteractive:` case for the FQDN setting and the addition of a SITE_URL setting to default.config and interactive.config to allow the installer to set each value correctly.

If IQSS finds this friendly I'll submit a pull request.

**Comment by djbrooke** [comment]
@donsizemore if it's an easy one go ahead and make the PR and we discuss there. If it's a bit more involved others may have thoughts here. Thank you!
