### ISSUE TITLE
publishing a dataset gets stuck

### ISSUE THREAD

**Issue by gboeing** [IQSS/dataverse#7145]
Last week I created a dataverse with 5 datasets and published them. 4 of the 5 datasets successfully published. The 5th is stuck: it says "Publish in Progress – This dataset is locked while the file persistent identifiers are being registered or updated." But this has been the case for several days now, while the others took only a couple minutes to finish. Furthermore, the "publish" and "edit" buttons are grayed out for this dataset, so I can't try it again or delete it and start over.

The dataverse is here: https://dataverse.harvard.edu/dataverse/global-urban-street-networks

And the draft dataset that's stuck is here: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/ZTFPTB

**Comment by djbrooke** [comment]
@gboeing sorry about that. I'll take a look. We're adding some better handling for this condition in the next release.

**Comment by djbrooke** [comment]
Hey @gboeing, we've removed the lock. Can you please try to publish this dataset again? Feel free to close this issue if it publishes as expected. If you encounter another lock, please let us know! Apologies again about the inconvenience.

**Comment by gboeing** [comment]
Thanks. That worked.
