### ISSUE TITLE
One file in several datasets

### ISSUE THREAD

**Issue by juancorr** [IQSS/dataverse#7148]
An researcher have a large file that is used in several datasets in e-cienciaDatos. We can:
  
- Upload the file to all datasets. But the file should be updated in all datasets when a new file version is released.
- Upload the file to a dataset and reference the file from the other datasets. But there is not a specific metadata field to reference external files that are part of a dataset.

  I think that a way to reference/share files that are part of other dataset or even that are not managed by Dataverse could be useful.

**Comment by pdurbin** [comment]
Yes. For example, there are 4072 copies of this file:

https://dataverse.harvard.edu/api/search?q=fileChecksumValue:1abc747829719298fb777cf92b8285ca

At least it isn't a large file! Only 1.2 MB.

That is to say, we feel your pain, @juancorr.

5.12 will support remote files, if that helps:

- #7325

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
