### ISSUE TITLE
Confirm 5.0 is not a memory hog 🐷, make necessary adjustments

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#7156]
In #7089/#7155 we added the ability to run memory tests on the 5.0 release candidate. We should now use this power to see if the release candidate is performing as well or better than 4.20 in terms of memory usage.

**Comment by mheppler** [comment]
Duplicate? Run Memory Tests on Release Candidate #7089

**Comment by pdurbin** [comment]
Per tech hours, @scolapasta will use this issue to coordinate the "human swarm." 🐝 🐝 🐝 

#7155 is a good place to follow up on discussion of memory tests.

**Comment by pdurbin** [comment]
As discussed in tech hours, here are the results of the memory tests. The raw data and more is linked from the "Comparison for memory tests 4.20 vs 5.0 RC" spreadsheet at https://docs.google.com/spreadsheets/d/1Pghs_UIGb1QEmPl01HJ3T9KRvEZy619dp3dJ-2S6gTQ/edit#gid=0

## 4.20

![benchmark-dataset](https://user-images.githubusercontent.com/21006/89341993-2560bf00-d670-11ea-94c6-4be13004d318.png)
![benchmark-dataverse](https://user-images.githubusercontent.com/21006/89341994-25f95580-d670-11ea-8a47-db0b3261daf0.png)

## 4.20-withG1GC

![benchmark-dataset](https://user-images.githubusercontent.com/21006/89342021-30b3ea80-d670-11ea-94c6-c6e09b47231e.png)
![benchmark-dataverse](https://user-images.githubusercontent.com/21006/89342022-30b3ea80-d670-11ea-8435-2df980fe3769.png)

## 5.0rc-78527a291

![benchmark-dataset](https://user-images.githubusercontent.com/21006/89342053-3b6e7f80-d670-11ea-9816-0e226563bf5d.png)
![benchmark-dataverse](https://user-images.githubusercontent.com/21006/89342056-3b6e7f80-d670-11ea-9fa3-18c9ce1180f2.png)

## 5.0rc-78527a291-noG1GC

![benchmark-dataset](https://user-images.githubusercontent.com/21006/89342091-475a4180-d670-11ea-90d2-318c07999e79.png)
![benchmark-dataverse](https://user-images.githubusercontent.com/21006/89342093-47f2d800-d670-11ea-9463-f48defafe25d.png)

**Comment by scolapasta** [comment]
Thanks for the graphs @pdurbin. As we discussed, these results are what we want to see - similar graphs when using the same GC. So for that purpose, these tests "passed".

One more test we still plan on doing is a team "swarm". Once we have the RC ready, we'll set an hour and everyone will go and use the system, create objects, etc. We'll keep this ticket open until we do that.

**Comment by scolapasta** [comment]
Swarm run. While we found an unrelated issue (with the publish button), nothing memory related jumped out as consequential related to 4.20. Closing this issue.
