### ISSUE TITLE
API development: read sensitive data and write privacy preserving metadata for OpenDP privacy tools

### ISSUE THREAD

**Issue by tercer** [IQSS/dataverse#7158]
New APIs are needed for using OpenDP to provide differentially private releases of metadata to Dataverse.  First we need to define and finalize the APIs needed for the immediate minimum viable product under development for October.  This issue is the placeholder to further define this need.

Currently anticipate OpenDP tool with read private metadata and dataset, and later write privacy-preserving (public) metadata in three formats (full form in JSON, reduced form in DDI schema in XML, and PDF/A file presenting a human readable summary report).

**Comment by raprasad** [comment]
Regarding writing privacy-preserving metadata, this doc describes several considerations: https://docs.google.com/document/d/1q0Upg3Pa5lP1Gq5TxEzm9BYtA5G8PaqAx7o4WfKPo4U/edit

**Comment by raprasad** [comment]
DP = Differentially Private

## (1) API: Deposit DP Release Data
- Allow the depositing of DP Release data
- This data is specific to a Dataverse file
- There are three data formats to deposit for each release:
	- DP JSON format (full form)
	- DP PDF Report (human readable summary)
	- DP DDI (XML)

### (1a) Future consideration : Multiple Releases
In the next phase, multiple releases may be created for *each* Dataverse file.  There should be provision to store data/files for each release. Example:

- DP Release 1
	- DP statistic: `mean of age`
	- DP release data generated
		- DP JSON format 
		- DP PDF Report
		- DP DDI
- DP Release 2
	- DP Statistic: `OLS regression of age/sex`
	- DP release data generated
		- DP JSON format 
		- DP PDF Report
		- DP DDI

### (1b) Future consideration: Building on Previous DDIs

Discuss whether DP DDIs should be “cumulative”, building on previous DP DDIs.  In the (simplistic) example above:
- Release 1, DP DDI
	-  `mean of age`
- Release 2, DP DDI
	-  `OLS regression of age/sex`

An example of a “cumulative” Release 2, DP DDI would be:
- Release 2, DP DDI
	-  `OLS regression of age/sex`
	-  `mean of age` from Release 1

## (2) API: Retrieve DP Release Data
- API to retrieve deposited DP Data
	- Allow retrieval of each type of DP release data type separately, e.g.:
		- DP JSON
		- DP PDF Report
		- DP DDI
	- Allow retrieval of all 3 data types in one API call?
- Design API for “Future considerations” described in (1) API: Deposit DP Release Data

## (3) API: Retrieve User Information
- Via a user’s apiToken, retrieve the user’s data
- Output is the same as the existing “List Single User” API endpoint
	- [Native API — Dataverse.org](http://guides.dataverse.org/en/latest/api/native-api.html) 

## (4) API: Messaging
- The creation of a DP Release may take seconds, minutes, or hours. 
- Via API, notify a Dataverse user via the existing Dataverse messaging system, including email, that a release:
	- (a) Has been deposited or
	- (b) Failed to be created
- Possible alternative.  
	- Notification can also be a function of successfully depositing DP release data in (1) API: Deposit DP Release Data

**Comment by scolapasta** [comment]
I just added #7275 as a more generic solution for this API - I wanted to leave this issue as being focused on Open DP. Once we have #7275, we can see what else is needed here.

**Comment by pdurbin** [comment]
Related:

- #4063
- #7244
- #9007

**Comment by pdurbin** [comment]
Closing in favor of this issue:

- #9099
