### ISSUE TITLE
support a "noreply" email address (in addition to the "support" email address) 

### ISSUE THREAD

**Issue by stevenferey** [IQSS/dataverse#7160]
Hello dataverse team,

We have specified a dataverse admin sender "noreply@..".
But, when clicking on the "Support" menu, it sends an email to this "noreply" address!

![Capture_form](https://user-images.githubusercontent.com/13960773/89395713-fdc03400-d70d-11ea-82f0-8ac1198aa7f1.png)

Is it possible to configure a "noreply" admin address and a support address for a dataverse installation?

Dataverse version: 4.20

Thank you very much for your feedback.
Steven.

**Comment by pdurbin** [comment]
@stevenferey thanks for the suggestion.

Right now the :SystemEmail is used as both the "from" when sending email and the "to" when receiving it.

If I recall correctly, a number of messages sent by Dataverse say something like "reply to this message" at the end so if we do make this separation you're proposing possible, we'll want to be careful to consider the "do-not-reply" email address possibility.

**Comment by stevenferey** [comment]
Hello,

Thanks for your feedback.
Yes, we have modified the property files to modify the end of some emails.

We will redirect the "Support" link to an external form page.

Do you know if this suggestion can be incorporated in a future version of dataverse?

Thank you so much.
Steven.

**Comment by pdurbin** [comment]
It's certainly possible but there are 957 open issues right now. Pull requests are always welcome! 😄

**Comment by pdurbin** [comment]
1,259 open issues right now. PRs still welcome! 😄

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
