### ISSUE TITLE
Remind Dataverse account owners who have trouble logging in that their account is or may be managed by another system (e.g. using Shibboleth or OAuth)

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#7166]
Occasionally people who have user accounts on Harvard Dataverse or Demo Dataverse (running Dataverse version 4.20 as of this writing) that are set up through Shibboleth or OAuth (academic institutional accounts, Google, etc.) forget that their account was created through Shibboleth or OAuth. 

When they click on "Log in", instead of clicking on an option that let's them log in through a Shibboleth or OAuth account ("Your institution", "GitHub", etc):

<kbd><img width="564" alt="Screen Shot 2020-08-06 at 12 01 10 PM" src="https://user-images.githubusercontent.com/18374574/89554217-8efddc00-d7dc-11ea-9c61-06e78f65eb93.png"></kbd>

... they click "Username/Email" and are asked for their username/email address and password. Maybe they don't remember this information or enter the username/email address and password associated with the Shibboleth or OAuth account. In any case, no information they enter here will work.

When they see that no email address or password is working, some users click on "Forgot your password?" and/or email the repository's admins/support staff for help. After some digging, support staff realize that the users' accounts are managed through Shibboleth or OAuth and let the user know that information for the account is managed through a different system (an academic institution, Google, etc.).

Often, the user will then use the appropriate option ("Your institution", "Google", etc) and gain access to their accounts again. 

Other times they need to resolve issues with those third party accounts, and more help from repository support staff might help (e.g. converting Shibboleth or OAuth accounts to an email (or "builtin") account).

**This GitHub issue is a proposal** to provide some feedback through the Dataverse UI that may help these users realize that their accounts are Shibboleth or OAuth accounts (instead of repository admins/support staff doing this).

One way might be to have Dataverse display some sort of message when the login fails because the user enters a username/email address on the Log In page for an account that is actually associated with a Shibboleth or OAuth account. The message may be a suggestion to try logging in using one of the other options - an academic institution, Google, etc- maybe worded vaguely enough in keeping with best security practices.

Another option may be to display such a message whenever logging in on the Log In page (using username/email and password) fails (instead of having Dataverse check if the username/email is associated with a a Shibboleth or OAuth account). Maybe the suggestion that the user's account may be a Shibboleth or OAuth account could be added to the existing error message:

<kbd><img width="740" alt="Screen Shot 2020-08-06 at 12 25 04 PM" src="https://user-images.githubusercontent.com/18374574/89556790-e5b8e500-d7df-11ea-995a-7585d5153862.png"></kbd>

**Comment by pdurbin** [comment]
@jggautier great description of a real problem and I like that you're proposing a range of solutions.

Another suggestion from #3704 is adjusting the "new account" email to say if the account is shib, builtin, orcid, etc. This won't help existing users, of course.

Another fix is to run our own Open ID Connect (OIDC) auth provider to unify all the account types. See screenshots at https://github.com/IQSS/dataverse/issues/3487#issuecomment-592441613 but in short the idea is that I'd be able to log in to HarvardKey, ORCID, GitHub, and other systems and still be "me" in Dataverse. As the issue's title says, "Permit multiple login options to the same Dataverse account."

**Comment by qqmyers** [comment]
Another variant might be to adapt the forgot password to 'forgot password or which authentication mechanism you used?'. That would avoid the security issue of hinting at which type of account it is in public - the answer is in an email only to the user.

**Comment by pdurbin** [comment]
Related:

- #10715

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
