### ISSUE TITLE
Improved display/warning about updated files

### ISSUE THREAD

**Issue by mankoff** [IQSS/dataverse#7174]
I think that older versions of files should clearly warn that there are newer versions, and link to them. 

Here is a file in a data set, v1.1 https://demo.dataverse.org/dataset.xhtml?persistentId=doi:10.70122/FK2/EIB6CG&version=1.1

Clicking on or mousing over the "Version 1.1" button does nothing.

I have to manually click on the "Versions" tab to see that v3.0 exists. 

I think there should be a large red warning box that this is not the latest version of the file, and a link to the latest version of the file, and perhaps a link to the latest version of the dataset too.

**Comment by poikilotherm** [comment]
Maybe this sth. that @TaniaSchlatter and the rest of the design team can take a look at for #6605 ?

**Comment by TaniaSchlatter** [comment]
Thanks for opening, @mankoff, and for the shout-out, @poikilotherm.

**Comment by sbarbosadataverse** [comment]
@TaniaSchlatter completed related to the DRAFT and versioning messaging we discussed in this ticket: #2921

**Comment by pdurbin** [comment]
> Here is a file in a data set, v1.1 https://demo.dataverse.org/dataset.xhtml?persistentId=doi:10.70122/FK2/EIB6CG&version=1.1

We clean out the demo server from time to time. Here's another example: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/TJCLKP&version=1.0

<img width="1208" alt="Screen Shot 2022-10-12 at 8 28 17 PM" src="https://user-images.githubusercontent.com/21006/195471878-b2ce1760-8520-424e-9a54-2ae7788ee698.png">

As before:

- Clicking on or mousing over the "Version 1.0" label below the title does nothing.
- I have to manually click on the "Versions" tab to see that version 3.0 exists.

I agree. some sort of indication that there is a newer version might be nice. Right now we rely on the user clicking the "Versions" tab.

**Comment by pdurbin** [comment]
Closing in favor of this issue:

- #9059
