### ISSUE TITLE
Exports not working on release candidate

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#7182]
During some testing of the release candidate, we noticed that exports were not being generated as expected. I'm including a not-very-helpful screenshot of the issue:

<img width="747" alt="Screen Shot 2020-08-11 at 2 10 45 PM" src="https://user-images.githubusercontent.com/7773392/89933762-8d1d8980-dbdd-11ea-8996-34554712ed9e.png">

This is reproducible by clicking on any of the export options under the "metadata" tab for a dataset. 

@landreev wondered "if it's just because all the other publishing attempts are exporting, in their onSuccess() call?"

Adding to Dataverse 5 milestone.

**Comment by djbrooke** [comment]
Going to close as we expect this is a configuration issue. 8080 was included in the URLs. Will reopen if it is an issue.

**Comment by scolapasta** [comment]
As @qqmyers pointed out it was a config issue (added port 8080 to URL).
