### ISSUE TITLE
Extraneous Publish Option on Release Candidate

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#7183]
See screenshot. There's an unexpected "Publish" option that appears when "Publish Dataset" is clicked. This was retested on incognito windows and 3x shift-refreshing.

![image (1)](https://user-images.githubusercontent.com/7773392/89934809-28632e80-dbdf-11ea-9aa8-adc0cd5e73cb.png)

**Comment by mheppler** [comment]
Extra `dropdown-toggle` style class snuck into the single-click version of the Publish btn, which triggered the display of the dropdown menu under the button when clicked.
