### ISSUE TITLE
geospatial file type: geodatabase  

### ISSUE THREAD

**Issue by jmjamison** [IQSS/dataverse#7185]
In the documentation, Geospatial Data section you list shapefiles.   You might consider adding Geodatabases. It's an ESRI format but used by other software, including QGIS.  

 It's called "database" but is really a folder with a bunch of file in it and has the extension of .gdb.  UCLA has a lot of LiDAR data in this format.   Right now I double zip the gdb file so the first layer is peeled off during ingest.  Zipped files aren't unusual for geospatial data.

**Comment by pdurbin** [comment]
@jmjamison thanks. Are you interested in making a pull request for this?

**Comment by jmjamison** [comment]
Yes, be glad to but I'm not sure what to do.  Haven't done a pull request at least here before.

**Comment by djbrooke** [comment]
Hey @jmjamison, as I mentioned on the community call, I'm happy to walk you through this process once I'm back from vacation. :)

**Comment by jmjamison** [comment]
Thank you.  I'll take you up on that next week.  I've been distracted trying out 5.0 on our test system.

**Comment by amberleahey** [comment]
hi there, just chiming in to say we are getting more deposits of geodatabase files (as zip packages) and would love to see more recognition for this format in DV. 

Here is the request list:
-Dataverse adds format identification and display for geodatabase files
see: 
![image](https://user-images.githubusercontent.com/17624834/188955478-9a90036b-74d9-4753-89b8-2cef727a3aad.png)
'Unknown'
-Supports geodatabase packages (.zips) and associates files from the package upon upload (similar to how DV handles shapefiles)

**Comment by pdurbin** [comment]
@jmjamison @amberleahey one thought is that you could help us create a sample dataset with these files over in this repo: https://github.com/IQSS/dataverse-sample-data

We'd want some (small!) files, of course (5 KB from the screenshot is plenty small!) and some idea of what to put for the title, author, etc. Basically, you could create a dataset on https://demo.dataverse.org the way you like it and then we could pull down the metadata and files from there.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
