### ISSUE TITLE
Native API: Get PID info endpoint always returns ok

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#7187]
The get pid info endpoint always returns ok, even when the datacite rest api url is incorrect:

curl -H "X-Dataverse-key:XYZ
" http://localhost:8080/api/pids?persistentId=doi:10.70122/FK2/ABCDEF

{"status":"OK","data":{"response":"crapi.test.datacite.org"}

**Comment by djbrooke** [comment]
- The exceptions don't make it up to the error code level
