### ISSUE TITLE
"General Terms of Use" field on "Sign Up" page is empty, even on dataverse.harvard.edu, with some Web browsers

### ISSUE THREAD

**Issue by BPeuch** [IQSS/dataverse#7189]
Version: 4.20

Hello everybody,

We have run into an issue at SODA, and it seems not just specific to our Dataverse installation.

My colleague @youssefOuahalou was trying to add text to the "General Terms of Use" field that shows up last on the "Sign Up" page:

![CTU](https://user-images.githubusercontent.com/15209224/90002681-45f1d000-dc93-11ea-818d-1c52d2b80296.png)

After completing the steps to this end, several strange things came about:

1. @youssefOuahalou did not see any change on his computer, even when changing Web browsers (the ones he tried: Firefox, Chrome, IE, Opera): the field still only contains the default sentence, "There are no Terms of Use for this dataset installation." Emptying the Web browser's cache or going into private navigation was not effective either.

2. I, on the other hand, do see something new in the "General Terms of Use" field — but not in all Web browsers:
✔ ️Firefox
✔️ Google Chrome
✔️ Opera
❌ Internet Explorer
❌ Microsoft Edge

Here is what I see in Firefox:

![sodhactu](https://user-images.githubusercontent.com/15209224/90003273-2313eb80-dc94-11ea-8574-6e671d0dc9a0.png)

3. @youssefOuahalou further noticed that, most strangely, the "General Terms of Use" field appears to be "empty" on **dataverse.harvard.edu** as well (i.e. it only contains the default sentence, "There are no Terms of Use for this dataset installation.") on his side, regardless of the Web browser.

4. That is not the case on my side, except for ❌ Microsoft Edge, in which this is what I see when trying to sign up on dataverse.harvard.edu:

![harvgtu](https://user-images.githubusercontent.com/15209224/90003615-9fa6ca00-dc94-11ea-80eb-ae2825f9b935.png)

Maybe Microsoft Edge is problematic in this instance because it is a young browser, so some of its technical specificities clash with Dataverse's code?

We are quite puzzled. 😐

**Comment by qqmyers** [comment]
@BPeuch - I don't see anything in the code that could be browser-specific - the text is added on the server. However, digging a bit I see that the terms are internationalized - could they be set for one language and not another? If it isn't set for a language, I think it defaults to whatever is set as system.app.terms in the main Bundle which is "There are no Terms of Use for this Dataverse installation."

If that's it, the workaround would be to set system.app.terms (and system.api.terms too probably). However, since there is now a setting (ApplicationTermsOfUse (and ApiTermsofUse)) it might be better for the code to default to the setting for the default language (if set) rather than the system.app.terms entry in in the Bundle.properties file.

**Comment by djbrooke** [comment]
@BPeuch and @youssefOuahalou thanks for the thorough investigation and the report. This is a fairly important part of the application and we should prioritize getting the correct information displayed here. 

@qqmyers thanks also. Yes, if ToU are not available in a specific language it should go with the default language. For example, in dataverse.harvard.edu I'd want everyone to get the English TOU.

**Comment by BPeuch** [comment]
Thank you for your replies, @qqmyers and @djbrooke. Indeed @djbrooke, we think this is something rather preoccupying if Dataverse is to be a program that can be implemented in other, non-English-speaking countries (and we know there are quite a few by now).

**Comment by qqmyers** [comment]
The PR will use the value set for the defaultLocale as the default for any locale unless those are specifically set (as described in http://guides.dataverse.org/en/latest/installation/config.html#id163).

Until then, setting the Bundle.properties system.app.terms value to match your terms, or adding language-specific values for the terms setting would be a work-around.

**Comment by BPeuch** [comment]
That's wonderful, @qqmyers. Thank you for working this out so quickly.

Do you think this PR will be integrated in an intermediary version of Dataverse, or is it planned for version 5?

**Comment by djbrooke** [comment]
Hey @BPeuch - we plan to add this to Dataverse 5, which will be the next release.

**Comment by BPeuch** [comment]
Thanks, @djbrooke. And good luck! 🚀
