### ISSUE TITLE
Issue using SWORD API documentation instructions

### ISSUE THREAD

**Issue by mderuijter** [IQSS/dataverse#7190]
While experimenting with uploading a large number of files via Dataverse's API's, I ran into an issue with the SWORD API.

I must be doing something wrong, although i'm using the curl examples on the [sword docs](http://guides.dataverse.org/en/4.20/api/sword.html#id9):
`curl -u 9b29159b-9c77-460d-a459-a2171b0b8d67: https://localhost/dvn/api/data-deposit/v1.1/swordv2/service-document`
 but receive the following error: `no such file or directory`

I'm using v4.20

Am I missing something here?

**Comment by JingMa87** [comment]
@mderuijter Hello fine colleague, what error message do you get when you change your call to the following?
```
curl -u 9b29159b-9c77-460d-a459-a2171b0b8d67: http://localhost:8080/dvn/api/data-deposit/v1.1/swordv2/service-document
```

**Comment by mderuijter** [comment]
> @mderuijter Hello fine colleague, what error message do you get when you change your call to the following?
> 
> ```
> curl -u 9b29159b-9c77-460d-a459-a2171b0b8d67: http://localhost:8080/dvn/api/data-deposit/v1.1/swordv2/service-document
> ```

For some strange reason they both commands work now, must have been a copy and past issue. See screenshot bellow:
![Screen Shot 2020-08-12 at 20 33 40](https://user-images.githubusercontent.com/56864998/90053725-2bdbe000-dcdb-11ea-8d83-9188f226e57a.png)

I'll close this issue immediatly... my mistake...
