### ISSUE TITLE
DownloadFilesIT/downloadAllFilesRestricted Failing on build 555

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#7195]
We are down to one failing test 😄 

On build 555 of Jenkins (not linking here so the bots don't find it) there's more info.

**Comment by landreev** [comment]
Copying what I said on slack; this appears to be this message hard-coded in DownloadFilesIT.java: 
```
downloadFiles3.then().assertThat()
                .statusCode(FORBIDDEN.getStatusCode())
                .body("status", equalTo("ERROR"))
                .body("message", equalTo("'/api/v1/access/dataset/%3ApersistentId' you are not authorized to access this object via this api endpoint. Please check your code for typos, or consult our API guide at http://guides.dataverse.org."));
```
and the actual message has changed, after the "error handler" PR got merged. So it simply needs to be adjusted accordingly.

**Comment by scolapasta** [comment]
Do we even need to check the exact message? I think confirming that we got the write status code and error would be enough? (i.e. we shouldn't have to fix this test every time we decide to change the messaging)

**Comment by landreev** [comment]
Agree. I don't think it's necessary at all, to check the exact message.

**Comment by landreev** [comment]
(it's in QA now - but I don't think it needs any QA other than having it pass the tests; which has been confirmed: https://jenkins.dataverse.org/job/IQSS-Dataverse-Develop-PR/job/PR-7198/)
