### ISSUE TITLE
OpenDP - bring DP Metadata Storage Infrastructure and APIs from Old Branch

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#7203]
We have an old branch (https://github.com/IQSS/dataverse/tree/4230-4231-4232-4233-4307-psi-combined) that has code to support an integration between Dataverse and the PSI tool. In support of upcoming with on OpenDP, we'd like to bring some things in from that branch to the develop branch. Generally:

- There are some APIs from depositing/retrieving DP metadata there that we'd like to support
- There's some DP metadata storage there that we'd like to implement
- The configure tool code that's there has already been implemented in Dataverse, so we don't need to grab that
- The explore tool code that's there pre-dates a lot of external tool functionality, and we'll be rethinking how we do launch DP explorations, so we don't need to grab that

I'll leave it up to @scolapasta @rtreacy @ekraffmiller and Mike P to determine where the intersections are here with #7158.

**Comment by scolapasta** [comment]
I'm going to close this. I just created #7275. In practice, the developer who works on it should be able to take some of the code from the old branch, but we don't need to track that separately.
