### ISSUE TITLE
Bug: It is possible to click on "Submit for Review" again even though a dataset has already been submitted for review (and is still "In Review")

### ISSUE THREAD

**Issue by BPeuch** [IQSS/dataverse#7204]
Observed on both local (v 4.20) Dataverse installations and on [Demo Dataverse](https://demo.dataverse.org/)

Hello everybody,

Even though, after clicking on "Submit for Review" on a dataset page, the dataset's status is updated as "In Review," the button "Submit for Review" is grayed out, and when hovering above it with the cursor the latter becomes a "Stop" sign…

![inrev](https://user-images.githubusercontent.com/15209224/90529168-b311d380-e173-11ea-97dc-8ac4317bb3d0.png)

… it's possible to click on it again.

Thankfully though, the program sends back an error message if a user tries to submit their dataset for review a second time, so it's not a major problem.

**Comment by sekmiller** [comment]
We've revised the publish/submit buttons in DV5, and I believe this issue will be fixed in the coming release.

**Comment by djbrooke** [comment]
Thanks @sekmiller. @BPeuch Thanks for the report - I'm going to close this one as we suspect it's fixed in develop, but feel free to reopen if this still happens in DV5.
