### ISSUE TITLE
Content placed in the "Terms of Access" field via dataset templates does not appear in datasets created with those templates

### ISSUE THREAD

**Issue by BPeuch** [IQSS/dataverse#7217]
Version: 4.20

Greetings,

It seems that the field "Terms of Access" in the Terms section of a dataset cannot receive content from dataset templates. We've done several tests and the field always remains empty, whether a file was added to the dataset or not. We want to prepopulate it by the use of templates to inform depositors that, if they have chosen a template for datasets with restricted access, they must fill in the "Terms of Access" field.

Possibly related to #2565.

[Edit] I just ran a test to see if this problem also occurs in Demo Dataverse: it does.

**Comment by BPeuch** [comment]
Thank you for your feedback @scolapasta! (And sorry for this late reaction. I was on holiday.)

**Comment by shlake** [comment]
Not sure if related, but if you do not enter "Terms of Access" when files are 1st restricted (via the popup) and then go back to "Edit Terms" to add text in "Terms of Access" the new text never appears. OR, if you want to change the "Terms of Access" from original, the new text does not get saved.

**Comment by scolapasta** [comment]
There have been issues related to all this, but as far as I know they are fixed in some version - i can't recall if in the released 5.3 or in a PR that is already merged in develop and slated for 5.4.

**Comment by djbrooke** [comment]
Hi - since we expect this is fixed in the current version, I'll close this issue. If we are wrong and it's still actually an issue, feel free to comment with details for it to be reopened. :)

**Comment by scolapasta** [comment]
I went ahead and refreshed my memory; and tried in demo. All of the above should be working in 5.3. So as @djbrooke if you do see anything else related to this not working, let us know.
