### ISSUE TITLE
Support replacing multiple files, or replace in draft dataset

### ISSUE THREAD

**Issue by mankoff** [IQSS/dataverse#7223]
Google groups conversation: https://groups.google.com/g/dataverse-community/c/ZN6ekXaCTo0/m/S7ugoJt2AAAJ

I am unable to replace 2 files in a dataset. After replacing 1, a new copy of the dataset exists in draft mode. I am unable to properly replace a file in draft mode. Instead it gets renamed with the "-1" issue. For example, with https://demo.dataverse.org/dataset.xhtml?persistentId=doi:10.70122/FK2/EIB6CG

```bash
export SERVER_URL=https://demo.dataverse.org

# file ID (latest version)
export ID_foo=doi:10.70122/FK2/EIB6CG/OFMC8B
export ID_bar=doi:10.70122/FK2/EIB6CG/YCYSP7

export FILE_foo=/home/kdm/tmp/DV/two/foo.txt
export FILE_bar=/home/kdm/tmp/DV/two/bar.txt

curl -H "X-Dataverse-key:$API_TOKEN" -X POST -F "file=@${FILE_foo}" -F 'jsonData={"description":"Foo", "forceReplace":true, "directoryLabel":"."}' "$SERVER_URL/api/files/:persistentId/replace?persistentId=$ID_foo"

curl -H "X-Dataverse-key:$API_TOKEN" -X POST -F "file=@${FILE_bar}" -F 'jsonData={"description":"Bar", "forceReplace":true, "directoryLabel":"."}' "$SERVER_URL/api/files/:persistentId/replace?persistentId=$ID_bar"
```

The first curl command returns:

```json
{
   "status":"OK",
   "data":{
      "files":[
         {
            "description":"Foo",
            "label":"foo.txt",
            "restricted":false,
            "version":1,
            "datasetVersionId":167419,
            "dataFile":{
               "id":1579549,
               "persistentId":"",
               "pidURL":"",
               "filename":"foo.txt",
               "contentType":"text/plain",
               "filesize":6,
               "description":"Foo",
               "storageIdentifier":"file://17422a9f04e-fc4c814c928b",
               "rootDataFileId":1579546,
               "previousDataFileId":1579546,
               "md5":"e19673b6e69c5f73192e4f78f6e771ab",
               "checksum":{
                  "type":"MD5",
                  "value":"e19673b6e69c5f73192e4f78f6e771ab"
               },
               "creationDate":"2020-08-24"
            }
         }
      ]
   }
}
```

And the second curl command returns:

```json
{
   "status":"OK",
   "data":{
      "files":[
         {
            "description":"Bar",
            "label":"bar-1.txt",
            "restricted":false,
            "version":1,
            "datasetVersionId":167419,
            "dataFile":{
               "id":1579550,
               "persistentId":"",
               "pidURL":"",
               "filename":"bar-1.txt",
               "contentType":"text/plain",
               "filesize":6,
               "description":"Bar",
               "storageIdentifier":"file://17422a9feea-3ac9367074bc",
               "rootDataFileId":1579545,
               "previousDataFileId":1579545,
               "md5":"17f50f4b842bd98f58f2e11c0848c821",
               "checksum":{
                  "type":"MD5",
                  "value":"17f50f4b842bd98f58f2e11c0848c821"
               },
               "creationDate":"2020-08-24"
            }
         }
      ]
   }
}
```

(note the `bar-1.txt`)

**Comment by pdurbin** [comment]
My first thought is that https://demo.dataverse.org is currently running Dataverse 4.20 and that a lot of work went into handling of files with duplicate names (and paths) in Dataverse 5.0. @mankoff if you're willing, perhaps you can retest once we upgrade that demo server.

**Comment by pdurbin** [comment]
@mankoff https://demo.dataverse.org was just upgraded to Dataverse 5.0. When you have a chance to re-test, please go ahead.

**Comment by mankoff** [comment]
Things are "worse"? Now even the 1st file has "-1" appended to the name, not just the 2nd and subsequent files.

As commented on the mailing list, this can be solved with a "replace" and then a "rename" call, although at a bit of extra work because a) two calls and b) the rename call needs to use the new DOI parsed from the return of the replace call.

**Comment by pdurbin** [comment]
Huh. Thanks for testing!

**Comment by scolapasta** [comment]
#7250 made a fix for this, but assumes the replacement file would be the same name as the new file (so skips the check). However, it would be possible to upload a replacement file with a different name and that could clash with other files - so we still need some sort of check.

(one possible thing to do is to delete the file first, THEN do the usual check, but not sure if that presents other challenges)
