### ISSUE TITLE
confusion over how to install Java 8 from Oracle for potential Dataverse developers

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#7234]
I'm setting up a new laptop and following the dev guide. It says to get Java from Oracle, which makes sense historically, but because Dataverse requires Java 8, what seems like the obvious things to click lead to a login screen:

<img width="1094" alt="Screen Shot 2020-08-26 at 4 35 15 PM" src="https://user-images.githubusercontent.com/21006/91354436-c39cfc00-e7ba-11ea-96da-c3ee9b05d852.png">
<img width="1094" alt="Screen Shot 2020-08-26 at 4 35 34 PM" src="https://user-images.githubusercontent.com/21006/91354441-c4ce2900-e7ba-11ea-9c0d-61ea90eb7551.png">
<img width="1094" alt="Screen Shot 2020-08-26 at 4 35 55 PM" src="https://user-images.githubusercontent.com/21006/91354445-c566bf80-e7ba-11ea-8716-842a3ea7c535.png">
<img width="1094" alt="Screen Shot 2020-08-26 at 4 36 08 PM" src="https://user-images.githubusercontent.com/21006/91354450-c5ff5600-e7ba-11ea-81c6-b83ffb2e7221.png">

On my previous laptop I had switched to https://adoptopenjdk.net and will probably try that instead (and if it works, suggest this in the guides).

**Comment by poikilotherm** [comment]
fwiw: in my container images I'm using OpenJDK (CentOS) and Zulu JDK (Payara base image)

**Comment by rtreacy** [comment]
OpenJDK is the way to go.
