### ISSUE TITLE
My Data->"results by username" field: The “results by username” field should display the content created by the "username" inserted in that field

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#7239]
The “results by username” field under "My Data" SUPERUSER features should display the content created by the "username" inserted in that field. It does not do that in demo or production. Tried with quotes and without, around the username.
in this example, there is a valid username found in the dashboard inserted. Results are all my curation tasks, not the said users.

<img width="1517" alt="Screen Shot 2020-08-27 at 3 55 31 PM" src="https://user-images.githubusercontent.com/8322346/91492756-2efed080-e884-11ea-92c1-70ba2535486b.png">

**Comment by cmbz** [comment]
2024/07/10
- Sized at 10 to conduct investigation into whether this should be implemented now or wait for SPA support.
