### ISSUE TITLE
File Hierarchy Not Preserved on Zip Downloads

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#7253]
To reproduce:

- Go to https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/GEC2LS
- Select "Download Original Format" under Access Dataset

When the download completes, note that it does not have the file structure. The structure is also not preserved when we select all the files in the dataset (91 in this case) and download that way.

**Comment by djbrooke** [comment]
Interestingly, this does work on Demo: 

https://demo.dataverse.org/dataset.xhtml?persistentId=doi:10.70122/FK2/LWVIZM

This may point to a configuration issue/difference

**Comment by landreev** [comment]
As suspected, this appears to be unique to the "outside zipper" optimization that was enabled in prod. I switched back to builtin zipping while this is being fixed.

**Comment by djbrooke** [comment]
Closing, will create a new issue for the zipper fix.
