### ISSUE TITLE
Linking Dataset API called twice will create two rows in db

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#7259]
When calling the link dataset API, if you call it twice for the same dataset - dataverse combo, it will not fail the 2nd time, but will say success and add a second (duplicate) row to the db. You then can't use the unlink, because it throws a 500 (probably because query doesn't return single result).

2nd row needs to then be deleted directly in the db.

This should be caught in the command. (and also should be checked for Dataverse links, as well)

**Comment by djbrooke** [comment]
- The linking should be smart enough to identify when a link already exists and show a message
