### ISSUE TITLE
Demo Dataverse – Unable to test metadata subsets (e.g. Geographic)

### ISSUE THREAD

**Issue by BPeuch** [IQSS/dataverse#7260]
Good morrow,

Dataverse 5 looks very exciting! I'm eager to test it with Demo Dataverse, but unfortunately I couldn't edit the metadata subsets available in my own subdataverse though, having created it, I have the Admin role for it:

![nogeo](https://user-images.githubusercontent.com/15209224/92917119-7792be00-f42e-11ea-95c9-550caa6aecfa.png)

Would it be possible to turn on these settings in users' own subdataverses?

**Comment by poikilotherm** [comment]
Hi @BPeuch - Did you uncheck the box "Use metadata fields from Demo Dataverse"? Otherwise you cannot override stuff in your sub-dataverse...

**Comment by BPeuch** [comment]
Oh, silly me. It was right under my nose. Thanks a lot, @poikilotherm!

**Comment by poikilotherm** [comment]
There, there... :grin:
