### ISSUE TITLE
Inform users of Terms of Use Update, Dismissible Banner

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#7263]
We have a minor terms of use update coming for dataverse.harvard.edu. We've been directed that we can just inform users of this in the application, and this option is attractive to me as it does not require us to build a workflow for re-acceptance (covered in #4978). 

My first thought is a dismissable banner with a quick message and a link to the TOU that, once dismissed, does not appear again. We'd need to track the dismissal somehow. This feature may also be useful for other messages that we want to show once, such as a release announcement or some announcement about an upcoming community meeting.

We have StatusMessageHeader and StatusMessageText available to us (http://guides.dataverse.org/en/latest/installation/config.html#id174) but don't think either of these are what we want (as they are messages turned off and on by admins), but we do want to use that banner pattern:

![Screen Shot 2020-09-11 at 2 23 25 PM](https://user-images.githubusercontent.com/7773392/92964164-ab2b1380-f441-11ea-8c6e-97b1ee24ca55.png)

Thanks @TaniaSchlatter for the screenshot and also for stating this a different way: "...having 2 types of system alert banners that look and appear the same but have two different purposes; persistent until turned off by the admin, vs persistent until turned off by the user"

**Comment by BPeuch** [comment]
This looks great! Do you think this feature will be available to admins through the GUI?

**Comment by djbrooke** [comment]
Hi @BPeuch - we'd plan to implement the management of this through the API initially.

**Comment by djbrooke** [comment]
For discussion as this enters development:

- Setting an expiration date as part of a message could be useful but also may be out of scope. Happy to discuss. 
- For the ToU use case, we wouldn't want to display to users who had just signed up for an account (and just agreed with the terms of use). Not sure how to handle this.
- Can we track the dismissal of a TOU banner (at least the session in which it occurred) in the DB?

**Comment by djbrooke** [comment]
From sprint planning

- @scolapasta mentioned moving banners outside of settings and set up some table for managing this
- This would potentially allow us to track this - which would be useful (20k-40k users means 20k-40k rows at least)
- @kcondon mentioned that there may be some overlap with notifications - it's some type of broadcast and we want to track if people have seen it (let's dig in this as we develop)
- Banners would be defined as automatically dismissible by new users (this is so a user that signs up for an account does not see the banner that terms of use are not updated).

**Comment by TaniaSchlatter** [comment]
Two user scenarios that represent Harvard use case:

Gary King (as existing depositor and data user) sees a message when he logs in to Harvard Dataverse, that terms of use have changed. He reads that by continuing to use the site, he is accepting the new terms. He sees that there is a link to the new terms that he can read if he wants. He checks out the new terms, which open in a new window. He closes the window, and, back on the Dataverse page, dismisses the message. The system tracks that Gary dismissed the message, implying that he has accepted the new terms of use. 

A new Dataverse user creates an account, accepting the (new) terms of use. On the Harvard Dataverse home page, the new user sees the same message. They dismiss the message. The system tracks that the new user dismissed the message, same as in the existing user scenario. 

- [ ] we need to track user activity (dismissing the banner) in a way that we do not currently, (see @scolapasta's suggestion above), and in a way that is separate from other notifications. 

- [ ] can a link can be used in the banner currently? If not, add that capability. 

- [ ] do we augment the existing banner, or create a different banner type? (Admin use case)

**Comment by sekmiller** [comment]
Proposed Table Design:

A Notification Banner table which would include a text field for header and message analogous to the settings table entries of :StatusMessageHeader and :StatusMessageText, and a nullable time stamp after which the message would not display. (if null, the message would have to be dismissed by each user.)

A join table for NotificationBanner/AuthenticatedUser, which would include ids for each and a time stamp for when the user has dismissed the notification.

Something like this:

<img width="256" alt="Screen Shot 2020-11-09 at 1 04 03 PM" src="https://user-images.githubusercontent.com/2364928/98579663-f66c7180-228c-11eb-84af-f367600aebd7.png">

**Comment by sekmiller** [comment]
Immediate Questions:
Are we thinking of continuing to use :StatusMessageHeader and :StatusMessageText for short term notifications?
Would we delete old notification banner records along with records from the join table?

**Comment by sekmiller** [comment]
In the case of a user that is not logged in, I'm assuming that we would post any notification that has not expired. Once they log in we can check if they have dismissed it.

**Comment by djbrooke** [comment]
- Expiration date is out of scope
- Instead of header we can just define the whole thing in HTML using bolding
- We should handle multiple languages, look to how we handled it in Terms of Use internationalization (#5303)
- Add a boolean for dismissible for user vs persists until removed by admin
- Consider renaming the table from UserNotifications (something banner-related)

**Comment by sekmiller** [comment]
Updated table design based on recent discussion:

<img width="280" alt="Screen Shot 2020-11-09 at 4 20 46 PM" src="https://user-images.githubusercontent.com/2364928/98597974-c9798800-22a7-11eb-8cb2-f14f40f32a89.png">

if the boolean dismissibleByUser is false the banner will be shown until the record in the table is deleted. It may be dismissed in a session. If it is true then it will only be shown to logged in users (and only if the dismissalTime in the join table for that user is null)

**Comment by TaniaSchlatter** [comment]
Reviewed a WIP demo. To dos include: 

- testing the message with a text link
- enabling the message to be deleted (need the message ID)

We discussed that if the user changes the language after dismissing the alert, the alert will not be displayed a second time, because changing the language does not change the session (or the user).
