### ISSUE TITLE
Update Display Logic for Add Data button from My Data page

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#7269]
In 5.0 we updated the display logic for the Add Data button in the header (#6741). We should update the Add Data button under "My Data" to match this display logic. 

<img width="510" alt="Screen Shot 2020-09-15 at 3 18 39 PM" src="https://user-images.githubusercontent.com/7773392/93254828-fce7dc80-f766-11ea-8d42-d3d234eabf8e.png">

Created from #6951, which suggested removing it.

**Comment by scolapasta** [comment]
Since we have the button in the navbar, why not just remove it?

**Comment by djbrooke** [comment]
@scolapasta I'm not opposed to that, but you suggested updating the logic in the previous issue. :) If we want to remove it, that's fine, I'd just run it by the design team to get a take on it.

**Comment by TaniaSchlatter** [comment]
I am fine removing "Add Data" from the "My Data" page.
