### ISSUE TITLE
Add "debug=true" to session, so we can use it more robustly

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#7273]
Currently, we have the ability (as a superuser) to add a parameter of debug=true to a URL and for 1 or two pages (the dataverse page for example), spit out some extra info in the UI. However if you then click (for example on "next page", the debug goes away.

This is to set the debug into the session so you don't have to add it to the url each time. We could even consider adding a UI toggle if we want, but that's not as important.

We can also in the future consider adding more uses of debug = true if we find other places it could be useful.

**Comment by djbrooke** [comment]
- Add at the session level instead of page by page
- Could toggle between true and false by updating the URL
