### ISSUE TITLE
External tool for TIFF Images

### ISSUE THREAD

**Issue by kamil386** [IQSS/dataverse#7280]
How to register an external tool with MIME Type that hava an "space" char?

Unfortunately,
\"contentType\":\"TIFF Image\"
or
\"contentType\":\"TIFF%20Image\"
both doesn't work as expected.

**Comment by qqmyers** [comment]
The contentType/ mimetype for TIFF would be image/tiff. The display then provides the more readable name "TIFF Image", but you should use the real mimetype in registering an external tool.

**Comment by djbrooke** [comment]
Thanks @qqmyers. 

@kamil386 I'll close this out, but please comment if you feel it should be reopened.
