### ISSUE TITLE
Unexplained publishing failures

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#7303]
This has been observed twice in production under v5.0: 
All publishing requests start failing on an application node; this continues  until it is restarted. 
The first time it happened, it started with a few datasets with lots of files. So there was an assumption early on that it may have had to do with all the extra DataCite registration calls (the DataCite client and the http client it uses are cached and reused; so it's not entirely impossible for those to be stuck in some kind of a bad state - ?)  
But that apparently can happen with the file reg. disabled too. So there's a good chance it has nothing to do with DataCite at all. For example, it's the async. execution that for some reason stops working - so the FinalizePublication command never even runs (the lock is created in PublishDataset command, and removed in FinalizePublication command). In v5.1 some explicit .info logging messages are being added to the FinalizePublication command so at least we'll know if it's being called at all). 

Not clear how to investigate this; or how to go about diagnosing the condition next time it happens.

**Comment by qqmyers** [comment]
A complete WAG: is there any way a command gets stuck in the EjbDataverseEngine CommandContext? Just thinking that with Publish only calling the Finalize command in the onSuccessMethod, which only gets called if the command is top of the CommandContext stack, this could be a way to get the symptom of one failure then causing others to fail until restart.

**Comment by landreev** [comment]
It may be a WAG, but I actually think it's a very good idea. My sense is that it should be something in that direction... I assumed at first it was because of something we attempt to do inside the FinalizePublication command that goes wrong; but I more and more feel like it's more likely that the command just never gets executed at all. 

This would be a potential explanation. And also there is a correlation, between  this starting to happen in 5.0, and that async. call to the second command having been moved to the onSuccess() of the first.

**Comment by landreev** [comment]
With that theory in mind, that something can get stuck on the command context stack, preventing the execution of onSuccess blocks going forward - is there any possibility of simultaneous attempts to execute something - like parallel attempst to publish multiple datasets - making it more likely to happen? (this IS a complete WAG)

**Comment by qqmyers** [comment]
I think so - great idea. I looked a bit more and see that the cleanup looks pretty good, so I no longer think things can get stuck on the stack. However, with the singleton, now that you mention it, I think it might still be possible that both commands are using the same stack, and only one gets its onSuccess called if they run in parallel - only one is top of the stack or one clears the stack at finish before the other is ready.

**Comment by djbrooke** [comment]
- Short term lets focus on adding some debug statements to the commandengine so that when/if it happens again we can see if the above hypotheses are correct
