### ISSUE TITLE
Bug: Removing facet filter removes file count from search

### ISSUE THREAD

**Issue by adam3smith** [IQSS/dataverse#7304]
Testing on demo.dataverse.org but this also occurs on qdr, both in 4.20 and in 5.0 testing:

Steps to reproduce:

1. Go to dataverse root, e.g. https://demo.dataverse.org/ -- note number of files
![image](https://user-images.githubusercontent.com/128986/95247229-9729c600-07e3-11eb-9dab-586a2a297c9c.png)

2. Filter by any facet, e.g. "Researcher" (the bug appears to be unrelated to which facet I choose)
![image](https://user-images.githubusercontent.com/128986/95247278-aa3c9600-07e3-11eb-93b1-03e4002b901a.png)

3. Click the x next to the facet to remove the filter

Expected behavior: The search returns exactly as previously
Actual behavior: The number of files is displayed as 0
![image](https://user-images.githubusercontent.com/128986/95247358-c3dddd80-07e3-11eb-9740-a91615b91cba.png)

**Comment by qqmyers** [comment]
FWIW: Easy to see that the URL keeps some filters when you remove the category: e.g. ?q=&fq0=dvObjectType%3A%28dataverses+OR+datasets%29&types=dataverses%3Adatasets&sort=dateSort&order=desc
 versus going back to having no query param.

**Comment by mheppler** [comment]
Sound possibly related to other search facet related issue, **Search - UI bug: Strange dataverse ID and duplicate selected facets displaying above results table #6641**, from 5.0.

**Comment by scolapasta** [comment]
The issue is specifically related to that fq0:
fq0=dvObjectType%3A%28dataverses+OR+datasets
If you remove that (and leave the types), you get the correct results. 

the fq param are facet params so I guess it makes sense? though clearly it should not be part of the url, while the other params do make sense - they don't need to be there, but are legitimate)
