### ISSUE TITLE
API/OpenDP: Retrieve User Information

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#7307]
## API: Retrieve User Information
- Via a user’s apiToken, retrieve the user’s data
- Output may be the same as the existing “List Single User” API endpoint in the Dataverse Native API:
  - http://guides.dataverse.org/en/latest/api/native-api.html#id146
   ```json
  {
    "authenticationProviderId": "builtin",
    "persistentUserId": "dataverseAdmin",
    "position": "Admin",
    "id": 1,
    "identifier": "@dataverseAdmin",
    "displayName": "Dataverse Admin",
    "firstName": "Dataverse",
    "lastName": "Admin",
    "email": "dataverse@mailinator.com",
    "superuser": true,
    "affiliation": "Dataverse.org"
  }
  ```
- Or a subset of these fields: `persistentUserId`, `firstName`, `lastName`, `email`

Note: I am separating this out from #7158:
 - This is [Part 3 of #7158](https://github.com/IQSS/dataverse/issues/7158#issuecomment-673489082)
 - Required for the OpenDP MVP

**Comment by djbrooke** [comment]
@raprasad thanks for your patience, I just had the time to catch up with @scolapasta about this. I think this all sounds good, and thanks for highlighting the four fields you need. I'll move to Up Next so we can get this into a near-term release of Dataverse.
