### ISSUE TITLE
Update dataverse.org/publications

### ISSUE THREAD

**Issue by atrisovic** [IQSS/dataverse#7322]
Hi All,

I noticed that the publications page could be updated with some more recent works, like for example [this one](https://dl.acm.org/doi/10.1145/3391800.3398173).
I'm not sure who to write about this, but I'm happy to follow up :-)

Thanks!
Ana

**Comment by djbrooke** [comment]
I'm going to close out this issue -- thanks @atrisovic fo reporting and @dliburd for helping with this!
