### ISSUE TITLE
Dataset page - button and citations display issues in different languages

### ISSUE THREAD

**Issue by kaitlinnewson** [IQSS/dataverse#7326]
Hi Dataverse team,

We at Scholars Portal have begun testing Dataverse 5 (currently 5.0 and working on our merge up to 5.1.1, so apologies if this was already addressed). We have noticed an issue with the display of buttons and citations on the dataset page when we change languages to French.

![Screen Shot 2020-10-13 at 4 59 28 PM](https://user-images.githubusercontent.com/6903515/95915843-c3aa8880-0d75-11eb-8b85-5569609189b4.png)

The new design does not seem to accommodate longer strings of text.

Has the new dataset page been previously tested with different languages? We only use EN/FR, but I can see this happening with other languages too.

**Comment by mheppler** [comment]
🤦 

Apologies, @kaitlinnewson. I thought this was addressed. I can look into this and get it prioritized ASAP. ATTN @djbrooke.

**Comment by djbrooke** [comment]
@kaitlinnewson thanks for the report, we can take a look

**Comment by qqmyers** [comment]
To frame discussion a bit, it seems like there are ~3 directions that could be pursued, alone or in some combination:

- Maximizing the length allowed in the display through UI changes, e.g. either with bigger spaces, or something adaptive such as allowing word wrap to expand a button. While it would be difficult to handle truly arbitrary length text and keep the UI looking reasonable, if there are only a few problematic places and handling length of 1.5x to 2x of the existing length is enough, this could work. It might still be hard to avoid whitespace for short translations, etc.
- Review the translations and come up with shorter ones - may or may not be possible to do without reducing how clear the meaning is, and I don't think there is currently any documentation about length limits
- Consider some form of progressive disclosure, e.g. showing the first n characters and, upon hovering, show the full label as a popup. This can be a bit tricky (truncate at word boundaries? and in the first word if it is too long?) and can also limit comprehension unless the translations are made with this in mind.

**Comment by mheppler** [comment]
Submitted a PR #7535 to improve the display of long button label text, so that any overflow is no longer hidden by the container button width.

While @qqmyers brings up some good points above to address this issue, this quick code fix might be the most appropriate to resolve the issues reported by @kaitlinnewson above.

<img width="956" alt="Screen Shot 2021-01-25 at 2 05 19 PM" src="https://user-images.githubusercontent.com/687227/105756043-1ae5fa80-5f1a-11eb-8adf-d8d945813d7a.png">

**Comment by kcondon** [comment]
@kaitlinnewson Do you have a test Bundle_fr.properties file I can use to test with?

**Comment by kaitlinnewson** [comment]
@kcondon This one should hopefully work. It's for 5.1.1 so may have some missing strings: https://github.com/scholarsportal/dataverse-language-packs/blob/dataverse-v5.1.1-SP/fr_CA/Bundle_fr.properties

**Comment by kaitlinnewson** [comment]
Actually we did shorten some strings to make them fit in the 5.1.1 version, so this one should be better for testing the issue: https://github.com/scholarsportal/dataverse-language-packs/blob/dataverse-v5.0-SP/fr_CA/Bundle_fr.properties

**Comment by kcondon** [comment]
@kaitlinnewson Thanks, that works.
