### ISSUE TITLE
Use https for guides.dataverse.org

### ISSUE THREAD

**Issue by PaulBoon** [IQSS/dataverse#7327]
Right now the dataverse guides site is on http (not on https). 
Some users are concerned  about the ‘non secure’ connection that browsers indicate.
It would be better if we also have the guides on https. Although technically these are static pages and https is not needed, this is a usability thing and user perception is important.

**Comment by nightowlaz** [comment]
Seconding this request as our email is flagging the email sent to new users as spam (as it links to the user guide).

**Comment by donsizemore** [comment]
@djbrooke this is done: https://guides.dataverse.org

@nightowlaz now that ^^ is listening on https, you'll want to update https://guides.dataverse.org/en/latest/installation/config.html#guidesbaseurl so avoid having outgoing e-mails flagged as spam.

**Comment by djbrooke** [comment]
@donsizemore thanks, and thanks to @nightowlaz and @PaulBoon for raising the issue. 

@donsizemore do you feel there should be a code change that should accompany this? I see lots of instances of http://guides.dataverse.org in the code and I'm happy to clean it up, but I'm not sure if it's needed.

**Comment by donsizemore** [comment]
@djbrooke testing a PR now to update the default BaseUrl used for sending e-mails. old links in the code won't matter since we have (and should always have) an http->https redirect which preserves deep links.

**Comment by nightowlaz** [comment]
Thank you!!
