### ISSUE TITLE
Documentation: GeoLite free download for Counter Processor now needs a free license key

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#7340]
https://blog.maxmind.com/2019/12/18/significant-changes-to-accessing-and-using-geolite2-databases/
https://stackoverflow.com/questions/59946333/how-to-download-geolite2-country-mmdb-gz-now-need-to-add-access-code

The blog indicates you need to create an account and agree to new? tou, including promptly updating db when updates avail and destroying old ones. It seems like they want you to either run an update app or set up a download updates cron job.

The stackoverflow post just provides someone's free license key in a bash script so not sure that is legit.

**Comment by qqmyers** [comment]
duplicates #6629 .

**Comment by kcondon** [comment]
@qqmyers thanks

**Comment by qqmyers** [comment]
FWIW: #6629 is awaiting someone to work on it. A PR with updated language for the guides would be welcome.
