### ISSUE TITLE
Mail Domain Groups require exact domain match

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#7344]
If I create a Mal Domain Group, the domain has to match exactly, i.e. does not support subdomains.

For example, if the group is "harvard.edu", a user with email user@iq.harvard.edu would not match, though ostensibly they should. (similarly it might be nice to create a domain group with ".edu" for all users that have a ".edu" domain.

**Comment by poikilotherm** [comment]
Thanks for opening the issue @scolapasta .

I'll try to give this a shot till Friday. I want that shirt 😻
