### ISSUE TITLE
install.py bails when database or username contains a hyphen

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#7347]
Stupid Admin Mistake 47b: passing DB and user names like ORG-test and ORG-testuser

The installer doesn't quote the values and dies here: https://github.com/IQSS/dataverse/blob/develop/scripts/installer/install.py#L430

Solutions might include adding quotes to install.py, discouraging the use of such naming conventions in the Installation Guide, or both.

I'm happy to test and submit a PR according to direction.

**Comment by pdurbin** [comment]
Does it bail with a meaningful error? If not, another solution could be to error out with an explanation of which characters are supported, or even validate the strings when the installer is run interactively.

**Comment by donsizemore** [comment]
It dies: https://github.com/IQSS/dataverse/blob/develop/scripts/installer/install.py#L434

Validation would be nice, though conditionals to add quotes seems like overkill. Escaped quotes + verbiage in Installation Guide?

**Comment by pdurbin** [comment]
Honestly, I think your "discouraging the use of such naming conventions in the Installation Guide" solution sounds fine. Doc-only pull requests are easier to review and QA. 😄
