### ISSUE TITLE
Impossible to delete metadata that were mandatory upon deposit in root but not anymore after moving dataset to subdataverse

### ISSUE THREAD

**Issue by BPeuch** [IQSS/dataverse#7361]
Version: 4.20

Ahoy,

I have run into an error after performing the following manipulations:

1. I **added** and **published** a **dataset** into our **root dataverse**, in which **two metadata elements** of the "Social Sciences and Humanities Metadata" metadata group are **mandatory**, namely "Number of Variables" (custom-added metadata element) and "Target Sample Size / Number of Units" (renamed element, formerly "Target Sample Size");

2. I then **moved** this dataset, by the use of the Move Data functionality in the admin panel, into a **subdaverse** in which none of the "Social Sciences and Humanities Metadata" elements are mandatory;

3. I then edited the dataset's metadata by **removing** the **values** in the aforementioned elements (which should be possible, considering they are not mandatory in this subdataverse in which the dataset was just moved);

4. I then tried to **publish** (as admin) the dataset by selecting the third option, "**Update Current Version** (will permanently overwrite the latest published version)."

But the following error message popped up:

![error_remove_formerly_mandatory_metadata](https://user-images.githubusercontent.com/15209224/97319539-4864ce80-186d-11eb-91ac-6af731f2ab3e.png)

(Transcript for full-text indexation: ```Error – Dataset Version Update failed. Changes are still in the DRAFT version. - edu.harvard.iq.dataverse.engine.command.exception.CommandException: Command edu.harvard.iq.dataverse.engine.command.impl.CuratePublishedDatasetVersionCommand@79fe9fb9 failed: null If you believe this is an error, please contact Team SODHA for assistance.```)

It looks like the dataset, though moved into a new environment, "inherited" the mandatoriness of these metadata elements and retained it despite being moved into a subdataverse where the rules are different.

**Comment by qqmyers** [comment]
@BPeuch - is there anything in the log to identify what line the null came from? The one thing I know was an issue in v4.20 was a problem if any files had been deleted (see #7014). Could that be a problem? If not, my guess would be that this isn't directly related to mandatoriness since the command just copies all fields across, but it could be something related to deleting fields instead of just changing values (at least I suspect that may not have been tested since the initial use was to deal with editing).

**Comment by pdurbin** [comment]
@BPeuch I'm curious if you get different behavior if you use the API to delete the fields: https://guides.dataverse.org/en/5.1.1/api/native-api.html#delete-dataset-metadata

I'm not saying you should have to resort to using the API, but I'm curious what happens.

**Comment by BPeuch** [comment]
Thank you @qqmyers and @pdurbin for your quick reactions.

@qqmyers

There were no file changes, only modifications in the metadata.

I'm attaching the messages the system returned in the server log when I tried to publish the new version (by overriding the first one):

[error_not_mandatory_anymore.txt](https://github.com/IQSS/dataverse/files/5451759/error_not_mandatory_anymore.txt)

The line that stands out to me is the following:

_Caused by: java.lang.RuntimeException: Response code: 422, **URL is not allowed by repository domain settings.**_

I think this might have to do with the fact that we changed our website's URL recently: it used to be https://dataverse.arch.be and it is now https://www.sodha.be.

So I tried something: I modified a random metadata element in our oldest published dataset, which was published back when the website was still called https://dataverse.arch.be. I simply added "d" in the field "Documentation and Access to Sources" (Citation Metadata) and then I tried to publish the new version, once again by overriding the current version.

The result was a failure to publish with an identical error message (save for the characters after the "@"):

_Error – Dataset Version Update failed. Changes are still in the DRAFT version. - edu.harvard.iq.dataverse.engine.command.exception.CommandException: Command edu.harvard.iq.dataverse.engine.command.impl.CuratePublishedDatasetVersionCommand@79d417fc failed: null If you believe this is an error, please contact Team SODHA for assistance._

If my hypothesis is correct, then you would be right and this would not be related to the fact that some metadata elements are or were mandatory.

@pdurbin

Thank you for the tip. I tried to delete the metadata values this way but I got an error message in return. I'm afraid I might have not written something properly in the JSON file…

Here is my JSON file:

[dataset-delete-author-metadata.txt](https://github.com/IQSS/dataverse/files/5452315/dataset-delete-author-metadata.txt)

(When I first tried with ```null``` I got another, shorter error message, so I tried with ```""````  instead.)

And this is the ensuing error message, which I'm not sure how to interpret:

[error_500_internal_server_error.txt](https://github.com/IQSS/dataverse/files/5452302/error_500_internal_server_error.txt)

**Comment by qqmyers** [comment]
Sounds like it may be this: https://support.datacite.org/docs/fields-client-settings#domains - you've restricted DataCite to only allowing URLs for the old domain name?

**Comment by BPeuch** [comment]
Well it looks like it all boiled down to the fact that we had forgotten to include "www." in the Domain and/or URL fields in DataCite Fabrica (probably the former because the latter is optional)…

Changing the contents of the field from "sodha.be" to "www.sodha.be" entirely solved the problem. The mandatory metadata element thing was a complete wild goose chase.

Thank you very much for your quick reaction, @qqmyers! And thank you too, @pdurbin.

**Comment by djbrooke** [comment]
That's great - thanks @BPeuch for reporting and @qqmyers and @pdurbin for the investigation.

**Comment by pdurbin** [comment]
For the record dataset-delete-author-metadata.txt isn't valid JSON:

cat dataset-delete-author-metadata.txt | jq .
parse error: Unfinished JSON term at EOF at line 25, column 1

If the API still doesn't work after fixing this, please open a new issue. The API shouldn't return 500 errors so you're welcome to open an issue about this too. It should say something like "Invalid JSON".

**Comment by qqmyers** [comment]
FWIW: The 500 may be a v4.20 limitation - I think 5.x may now send a 400/BadRequest. While that may not be true for this specific call,  there was a lot of work done in updating the error handling so I'd suggest a test against 5.x to make sure.
