### ISSUE TITLE
Remove Provenance Link from FilePage edit options

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#7368]
After discussing design implications for #7342, we decided to close it and remove the Provenance Link from FilePage edit options (for consistency). Provenance is still available under edit metadata.

(the discussion was about the fact that provenance is metadata, so where should it best live; at some point we may add back (to both file edit and kebabs) or we may even move Provenance to be an external tool, and it would a configure option.

But for now the straightforward resolution was to remove it from the FilePage edit options.

**Comment by TaniaSchlatter** [comment]
Pulling this back to needs discussion. We need to establish what consistency might be for actions for a file. Actions that can be taken are: delete, restrict, unrestrict, replace, add tag, add provenance, edit metadata (file name, file path, description), set a thumbnail. Are sub-classes needed? We could also use some clarity around what metadata is for a file. Is provenance metadata? Are tags metadata?

**Comment by scolapasta** [comment]
closing until we determine design from #7376
