### ISSUE TITLE
Upload+Rsync DCM

### ISSUE THREAD

**Issue by Fernand0S** [IQSS/dataverse#7372]
Hi, 

I have problem upload+rsync on dataverse, the module it is DCM active, but feature the message. 

The Data Capture Module failed to generate the rsync script. 
- 
![dataverse-json](https://user-images.githubusercontent.com/32446123/97599497-d617f980-19e6-11eb-967f-bac3e11cf49c.JPG)
![DCM](https://user-images.githubusercontent.com/32446123/97599595-ef20aa80-19e6-11eb-85aa-0832ddee0715.JPG)

**Comment by Fernand0S** [comment]
I used version Dataverse v. 4.10 build 1173-38851fa.

**Comment by djbrooke** [comment]
Hi @Fernand0S - have you previously added files to the dataset? The rsync integration is built in a way that you either need to bring in all files for a dataset using rsync/ssh or files using the UI/API. A restriction of the implementation was that you could not mix upload methods.

**Comment by Fernand0S** [comment]
> Olá @ Fernand0S - você já adicionou arquivos ao conjunto de dados? A integração rsync é construída de forma que você precise trazer todos os arquivos para um conjunto de dados usando rsync / ssh ou arquivos usando a IU / API. Uma restrição da implementação era que você não podia misturar métodos de upload.

**Comment by Fernand0S** [comment]
Or be, if i did upload via native http don't can accomplish via rsync now ? do I have to remove every data set ever made?

**Comment by Fernand0S** [comment]
> > Olá @ Fernand0S - você já adicionou arquivos ao conjunto de dados? A integração rsync é construída de forma que você precise trazer todos os arquivos para um conjunto de dados usando rsync / ssh ou arquivos usando a IU / API. Uma restrição da implementação era que você não podia misturar métodos de upload.
> 
> Or be, if i did upload via native http don't can accomplish via rsync now ? do I have to remove every data set ever made?

**Comment by djbrooke** [comment]
Hi @Fernand0S - you shouldn't need to remove any existing datasets, but you won't be able to upload using rsync in any datasets that already have files that have been uploaded using the API/UI. 

The rsync/SSH implementation was an early version of large data support. We've been doing a lot of work in this space and if your installation is running on S3 I'd suggest taking a look at Direct Upload options introduced in recent releases:

https://guides.dataverse.org/en/latest/developers/big-data-support.html
