### ISSUE TITLE
Upgrade to Solr 8+

### ISSUE THREAD

**Issue by jomtov** [IQSS/dataverse#7373]
In present [Installation Guide] (https://guides.dataverse.org/en/latest/installation/prerequisites.html#supported-versions) you recommend Solr version 7, for which last update was 7.7.3, and is now only updating from version 8.x. Evaluate risk for obsolecense / end-of-life of version 7.

**Comment by djbrooke** [comment]
@jomtov, thanks for opening this issue. When we discuss more we may retitle as "upgrade to version..." before we pull this into a sprint.

**Comment by djbrooke** [comment]
- We'll try to handle this with a discussion in dv-tech or tech hours
- We should make sure to read the release notes as there may be incompatibilities

**Comment by poikilotherm** [comment]
**thought:** I would be glad and honored to be part of the discussion.

**Comment by donsizemore** [comment]
FWIW, I just ran integration tests against develop and Solr 8.7.0.

test run: 1311, 0 errors, 0 failures.

Basic search seems to work. Lots of search warnings and errors in server.log though:

180 occurrences of
```
[#|2021-01-07T15:12:48.605+0000|SEVERE|Payara 5.2020.6|edu.harvard.iq.dataverse.search.SearchServiceBean|_ThreadID=68;_ThreadName=http-thread-pool::http-listener-1(5);_TimeMillis=1610032368605;_LevelValue=1000;|
  java.lang.IllegalAccessException: Class edu.harvard.iq.dataverse.search.SearchServiceBean can not access a member of class edu.harvard.iq.dataverse.search.SearchFields with modifiers "private static transient"
	at edu.harvard.iq.dataverse.search.SearchServiceBean.search(SearchServiceBean.java:684)
	at edu.harvard.iq.dataverse.search.__EJB31_Generated__SearchServiceBean__Intf____Bean__.search(Unknown Source)
 ```

but I think we're already seeing those regularly. The instance is still up if anyone wants to poke at it.
