### ISSUE TITLE
"other" as facet in the geospatial metadata

### ISSUE THREAD

**Issue by mpearse17** [IQSS/dataverse#7399]
Would it be possible to make the "other" field in the geospatial metadata (under geographic coverage) into a facet like the countries are?

Thanks!
Michelle

**Comment by pdurbin** [comment]
@mpearse17 hi, I don't see why not. It should just be a matter of editing scripts/api/data/metadatablocks/geospatial.tsv
 and changing "factetable" to "TRUE" for that field (and reloading the metadata block). I've highlighted that cell below:

<img width="868" alt="Screen Shot 2020-11-09 at 10 41 21 AM" src="https://user-images.githubusercontent.com/21006/98562759-645a6e00-2278-11eb-9262-6999db5e9848.png">
