### ISSUE TITLE
Auxiliary Files - Accessing DP releases in Dataverse

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#7400]
Between the existing configure tools framework and the auxiliary files support we're adding in #7275/#7350, we'll soon have a way to deposit DP release files into Dataverse. Now we need to determine how to display those files to users in Dataverse. The use case around this is:

"I want to view a differentially private release of a datafile so that I can learn enough to determine whether or not it’s worth my time to go through the request process for the raw data."

We kicked this around internally and with some members of the DP team and one option may to be add some download and explore options on the Dataset and File pages, options that would be available BEFORE the user requests access to the file. Right now, the user is just presented with some file metadata and a request access option:

<img width="755" alt="Screen Shot 2020-11-09 at 8 47 00 AM" src="https://user-images.githubusercontent.com/7773392/98548942-2a816b80-2268-11eb-8e75-8c51377d7241.png">

Instead, we could add some options for download and exploration appropriate to the auxiliary files that have been deposited, something like what we've started to investigate here: [working UI & behavior document](https://docs.google.com/presentation/d/1HFDjXJJqYkufY8xxtn8B3NPV9JJhj1tSHBGk97ZP03I/edit#slide=id.ga60a561816_0_27)

Some considerations:

- We need to figure out the logic for auxiliary files display here. We want to keep auxiliary files general, but some DP-specific support may be required. IMHO it's OK if we build in some DP-specific stuff here and revisit when we have other use cases around aux files better defined. 
- Related to the question above, we need to determine which DP files (.pdf, json, xml) are categorized under which option/dropdown - download, explore, preview.
- Is there anything we need to stop doing in Dataverse to make sure that privacy is not spoiled? As part of the ingest process we create summary stats for the raw file, so if this will reveal too much we may need to revisit to determine what to no longer make available when a DP release exists.
- If a user selects multiple files, some that have DP releases and others that don't, and clicks "Download All" - what happens? I'd be OK with handling this the same way as we currently handle multiple file download when a restricted file is selected.

**Comment by djbrooke** [comment]
Questions and discussion from design meeting 11/18:

- If you have access or are the data owner, what shows up on the access dropdown? Do you still see the aux files? One potential solution is to show all files (as the data owner may want to be able to see what people without access see) 
- If there's only one option, do we provide any options in a dropdown (Ex. request access)? Is there any advantage to showing the options? There may be some benefit to showing that "request access" is the only option - otherwise in this situation someone could click "request access" and kick off a access request to a person unintentionally. Note that user confirmation is currently delivered by the "Request Access" being turned to "Access Requested" in gray - we can't do this if the option is not shown when there's only one option. 
- If the only access is request access, is there some different icon that could be shown (bullhorn)? This would potentially address the concern of the user not knowing what would happen once the access button was clicked
- Is access the right symbol for all the potential options (as of 5.2 we have downloads/explore under the access dropdown)?

**Comment by TaniaSchlatter** [comment]
[Slides with current status](https://docs.google.com/presentation/d/1XuX4qStdHjkFf4g1d1vKxxb85kuuUSEzdKN41dNM2mM/edit?usp=sharing). There are a few open questions noted, to be worked out as part of development

**Comment by pdurbin** [comment]
In 7e7a502 I just pushed a branch to stub out downloading differentially private statistics. I'm having some JSF trouble (screenshot below) and the code contains several FIXMEs.

I need to go respond to feedback on a pull request so others are welcome to swarm on this.

<img width="491" alt="Screen Shot 2021-03-09 at 12 13 19 PM" src="https://user-images.githubusercontent.com/21006/110510626-65d65e80-80d1-11eb-99bc-a001d8628dc4.png">

**Comment by mheppler** [comment]
**_QUESTIONS:_** OpenDP Release Aux File #7400

_system configure tools config_
    - QUESTION how is the aux file name "Differentially Private Statistics" added? pulled from the name of the tool? defined by us? Internationalization? (Gustavo's idea...?)
    - QUESTION explore/any other tool changes required?

_system storing, displaying aux files for dataset files_
    - [x] ANSWER aux files are for all file types (currently only tabular)
    - QUESTION aux files access restricted?, available to guest for download (no log in prompted)? (what's needed for OpenDP vs what's scalable...)
    - QUESTION include DP info in the metadata for indexing? (How might we help an end user discover DP aux files)

_end user access options for restricted files (File Access > Download Options)_
    - QUESTION add “Differentially Private” tag? (How might we help an end user discover DP aux files?)
    - QUESTION data file citation restricted?, available to guest for download? for all file types?
    - QUESTION are/will current Variable Metadata .XML files considered aux files? whats the diff between them and Differentially Private Statistics .XML "fuzzy stats" file? need to change access to them?
    - QUESTION request access UX improvements #7469 in scope?

**Comment by qqmyers** [comment]
FYI: For QDR on work related to linking papers and data via Hypothesis annotations, I've been doing some incremental work to allow Aux files for other types and tracking issues (e.g. two aux files can have the same metadata). I'll get those into a PR request at some point, but if someone else is going to work on it, let me know and I'll share what I have.

**Comment by pdurbin** [comment]
> I'm having some JSF trouble (screenshot below)

I just wanted to give an update that somewhat magically JSF started behaving for me as as of 3c0140b here's how the files under "Differentially Private Statistics" look:

<img width="1161" alt="Screen Shot 2021-03-10 at 2 20 14 PM" src="https://user-images.githubusercontent.com/21006/110697173-f5efd300-81b9-11eb-9b1f-f3d15df7795e.png">

That is, this form: lablel (tag)

I have download working but I'll note that the existing download code doesn't put any sort of extension (at least for the example in AccessIT):

<img width="486" alt="Screen Shot 2021-03-10 at 2 23 50 PM" src="https://user-images.githubusercontent.com/21006/110697168-f4260f80-81b9-11eb-86a6-803f69ef925c.png">

Also on my mind is the `isPublic` boolean on the AuxiliaryFile object. If this is false, I'm not sure how the permissions are determined.

**Comment by scolapasta** [comment]
> Also on my mind is the isPublic boolean on the AuxiliaryFile object. If this is false, I'm not sure how the permissions are determined.

While we may someday want something more complex, I think for this initial release is:
isPublic - public
restricted - same permissions as the main file

(I don't think we can have a case for public main file and restricted aux files)

**Comment by mheppler** [comment]
Discussed some of the questions above with Phil and implemented some of the changes to the render logic for the File Access btn as well as some of it's dropdown options. These move the UI closer to some of the changes in the mockups, but there are outstanding questions that are blockers until answered.

**Comment by pdurbin** [comment]
Here are a couple screenshots from pull request #7729 that show what was implemented. Auxiliary files uploaded as type=DP appear under "Differentially Private Statistics" under file level download. The rest appear under "Other Auxiliary Files". 

<img width="1285" alt="file-landing-page" src="https://user-images.githubusercontent.com/21006/116894078-a220c980-abff-11eb-8e26-fa94ccaaf1a7.png">
<img width="691" alt="other" src="https://user-images.githubusercontent.com/21006/116894091-a51bba00-abff-11eb-9a79-c1d7805b9f7f.png">
