### ISSUE TITLE
API Native Endpoint - Error 

### ISSUE THREAD

**Issue by Fernand0S** [IQSS/dataverse#7404]
Hello could you help me on this API question

![image](https://user-images.githubusercontent.com/32446123/98984068-73ebe800-2500-11eb-8928-afc103b26cb6.png)

**Comment by Fernand0S** [comment]
Any command executed with "curl  .... " displays the error message.

**Comment by pdurbin** [comment]
@pameyer and I have been helping @Fernand0S in IRC: http://irclog.iq.harvard.edu/dataverse/2020-11-12#i_131934

**Comment by Fernand0S** [comment]
I solved execute command line - curl -X PUT -d localhost-only http://localhost:8080/api/admin/settings/:BlockedApiPolicy?unblock-key=****  

thank's

**Comment by djbrooke** [comment]
Great to hear @Fernand0S! Thanks @pdurbin and @pameyer for the help!
