### ISSUE TITLE
antedate citation date

### ISSUE THREAD

**Issue by rlzijdeman** [IQSS/dataverse#7405]
Hi,

I have a dataset that was released in 2010, and made its way to Dataverse today (yeah!).

The only thing is that the 'citation' now mentions 2020 as year of publication, rather than 2010, even though I filled out 2010 or 2010-09-01 in all the data fields ('date', 'distribution date', 'production date' and 'deposit date').

Is there another way for me to antedate the citation?

Best,

Richard

**Comment by djbrooke** [comment]
Hi @rlzijdeman, if I recall correctly, this is something we support over the API but not in the UI. Can you try the process outlined here: 

https://guides.dataverse.org/en/latest/api/native-api.html#set-citation-date-field-type-for-a-dataset

If this isn't the case, hopefully someone else will jump in here. :)

**Comment by djbrooke** [comment]
Hi @rlzijdeman, I'm going to close this issue but please feel free to reopen if this didn't work for you.
