### ISSUE TITLE
"Access Requested" only shown after page refresh on File and Dataset page

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#7406]
When access is requested to a file from the file table on the dataset page, the dropdown menu option switching from "Request Access" to the grayed-out "Access Requested" does not take place until after a page refresh. The same issue takes place on the file page. The expectation is that it would change without a refresh since this is the indication to the user that the request has gone through. If it doesn't change they are left wondering if the request was successful. 

To reproduce on the file page:

- Log in to demo.dataverse.org
- Go to a file on demo.dataverse.org that is restricted (pick one of these https://demo.dataverse.org/dataverse/demo?q=&fq1=fileAccess%3A%22Restricted%22&fq0=dvObjectType%3A%28files%29&types=files&sort=dateSort&order=)
- "Request Access" from the top right under the "Access File" dropdown
- In the "Access File" dropdown, note that "Request Access" is still an option and access can be requested again
- Refresh the page
- Note that "Request Access" has been grayed out and changed "Access Requested"

To reproduce on the dataset page, go through the same process but using the button on the file table instead. 

Running into this on 5.2, but may be an issue for 5.0 installations.

**Comment by scolapasta** [comment]
My guess is it's a likely 5.2 issue, since I think that's where request access was changed a dedicated button to under the dropdown. Should be a straightforward "update" fix.

**Comment by sekmiller** [comment]
<img width="254" alt="Screen Shot 2020-12-01 at 3 43 15 PM" src="https://user-images.githubusercontent.com/2364928/101078536-51d00d80-3574-11eb-9761-91a5176d9ac1.png">
<img width="226" alt="Screen Shot 2020-12-01 at 3 43 31 PM" src="https://user-images.githubusercontent.com/2364928/101078581-5f859300-3574-11eb-9821-6a013e4c78af.png">

I haven't been able to solve the issue with the display of "Access Requested" immediately following a request made on a file in a dataset that does not have Terms of Access. See the example above.
