### ISSUE TITLE
Deaccession: Deaccessioned datasets still appear in dataverse card, preview recently released datasets link.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#741]
Deaccessioned datasets still appear in dataverse card, preview recently released datasets link. The contents of this area is not controlled through indexing.

It is an issue only if the most recent version is deaccessioned, otherwise published version will appear.

Should probably only display most recent *published* version

**Comment by scolapasta** [comment]
Actually deaccesioned doesn't seem to appear any more, but a draft that was unpublished did!

**Comment by scolapasta** [comment]
Also, the logic was displaying info from the latest version, regardless of whether it was published or not.

So fixed all this. Now goes only published (and not deaccessioned) datasets and info from the latest published version.

**Comment by kcondon** [comment]
Works now, closing
