### ISSUE TITLE
Use Vagrant with LibVirt

### ISSUE THREAD

**Issue by poikilotherm** [IQSS/dataverse#7411]
Running on Fedora 33, there is no support for Oracle VirtualBox yet.
On Linux, I have the option to use a libvirt-based VM instead. I'll add a Vagrantfile for it.

They should be merged together, so we can just use `--provider=...` to switch between those.

**Comment by pdurbin** [comment]
We removed Vagrant:

- #9839

@poikilotherm do you want to close this?
