### ISSUE TITLE
Dataverse can't authenticate with OAuth2/OIDC using a custom identifier

### ISSUE THREAD

**Issue by JingMa87** [IQSS/dataverse#7412]
**Feature request**

For a migration of user accounts we at DANS (NL) would like to be able to authenticate users using a custom identifier. The identifier, which is called the persistentuserid in the database, is currently the "sub" value when requesting user info from the Identity Provider (like Google). We would like to use the institutional e-mail address of the user instead. Would this be possible? I'd like to build the feature myself.

**Comment by poikilotherm** [comment]
Hi @JingMa87,

I'm not sure I understand your use case in depth. Could you elaborate a bit more, maybe add a diagram of the envisioned auth flow?

Thx!

**Comment by pdurbin** [comment]
@JingMa87 I'm not sure if you saw the question by @poikilotherm above but you two seem to be talking about OIDC (I only recently heard about "sub"). Are you still interested in this? Thanks.

**Comment by pdurbin** [comment]
@JingMa87 no worries, good luck with your new job! I'll go ahead and close this out.

@PaulBoon or @janvanmansum if DANS is still interested in this, can one of you please open a fresh issue? Thanks!

**Comment by janvanmansum** [comment]
@pdurbin : no longer a priority for DANS.
