### ISSUE TITLE
Restricted file with "Request Access" disabled shows empty "download" dropdown

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#7426]
If request access is enabled, you get a dropdown with a request access option (as designed:

![image](https://user-images.githubusercontent.com/4268292/99553570-4bdf0780-298c-11eb-87b4-943c08dc9a97.png)

But if request access is disabled, you get an empty dropdown:

![image](https://user-images.githubusercontent.com/4268292/99554034-c576f580-298c-11eb-82df-8f3670b4c352.png)

**Comment by djbrooke** [comment]
If we restore this to the previous state, it would be that just don't show any option there - there's a blank space where the request/access options usually are. I'm fine restoring it to this state instead of trying to revisit the on-page messaging right now but there's definitely some opportunity for improvement in the future.

**Comment by TaniaSchlatter** [comment]
Meaning, the file is restricted, but "Request Access" is not selected?

**Comment by TaniaSchlatter** [comment]
I am getting a variety of strange behavior when I try to reproduce, using this file:https://demo.dataverse.org/file.xhtml?persistentId=doi:10.70122/FK2/9UJEHM/6YNOBB&version=3.0. For example, the deleted .tsv file goes away and comes back. A .pdf and >SVG that are restricted, but don't have an icon.

**Comment by TaniaSchlatter** [comment]
And there is no way to request access from the file page:
![Screen Shot 2020-11-23 at 2 03 51 PM](https://user-images.githubusercontent.com/15386424/100003971-d19bf200-2d94-11eb-872a-32521b1bc964.png)

**Comment by scolapasta** [comment]
@TaniaSchlatter in the file above, it appears to me that "request access" is disabled) on the dataset. i.e the file page has the correct behavior (the dataset is showing the empty dropdown).
