### ISSUE TITLE
Failing Tests

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#7428]
After a long string of blues (hooray!), we are seeing some failing tests on recent runs on jenkins.dataverse.org:

https://jenkins.dataverse.org/job/IQSS-dataverse-develop/645/
https://jenkins.dataverse.org/job/IQSS-dataverse-develop/644/

Let's figure out what's wrong and fix.

**Comment by donsizemore** [comment]
@djbrooke It's dying on the now-removed reference data step. I'll remove that in dataverse-ansible.

**Comment by djbrooke** [comment]
Thx @donsizemore. If we're pretty sure that's the cause, I'll close this and reopen if it continues to fail.
