### ISSUE TITLE
Dataverse trademark usage and new Microsoft product

### ISSUE THREAD

**Issue by DataverseUser** [IQSS/dataverse#7432]
Public readme of this project reports:
"Dataverse is a trademark of President and Fellows of Harvard College and is registered in the United States."

Recently Microsoft announced a new product called Dataverse https://powerplatform.microsoft.com/en-us/dataverse/

ZDNet wrote about it: https://www.zdnet.com/article/microsoft-makes-power-platform-tools-dataverse-data-platform-available-for-teams/

Is this a legal trademark usage of Dataverse, especially in the United States?

**Comment by djbrooke** [comment]
Thanks @DataverseUser for the report. We're aware of this and it's being looked into. 

Since this isn't something that we'll track through our usual issue resolution process here, I'll close this out.
