### ISSUE TITLE
Institution name truncated in shibboleth login

### ISSUE THREAD

**Issue by joe-programador** [IQSS/dataverse#7435]
Grettings , in shibbolet login section exist a combobox id = "idpSelectSelector". Which allows to select the name of the Idp, however some names are truncated. What changes would be necessary for the full name to be displayed?

**Comment by pdurbin** [comment]
@joe-programador hi! I think you'd want to hack around with these files:

<img width="749" alt="Screen Shot 2020-11-23 at 10 45 07 AM" src="https://user-images.githubusercontent.com/21006/99982810-0601b500-2d79-11eb-9869-744ebad2f0f0.png">

**Comment by djbrooke** [comment]
Hi @joe-programador, as @pdurbin mentions, there are some code changes that could be made to adjust this. Two things I wanted to ask/mention:

- Can you talk about your need here? Is it cosmetic or is there some information at the end of the name that's being cut off and it's preventing the user from making the correct choice in the dropdown? Some screenshots would be helpful. 
- We are reviewing some ways to truncate longer fields throughout the application (#6685) and we would want to be consistent if we did truncate, so it is unlikely we would accept a PR for this until we were about to review it alongside other truncation needs in the application.

**Comment by pdurbin** [comment]
@joe-programador hi, just checking if you got a chance to hack around with those files. Thanks.
