### ISSUE TITLE
[doc] Emphasize diferences between Dataverse Native API and SWORD API auth mechanism

### ISSUE THREAD

**Issue by joenio** [IQSS/dataverse#7441]
Would be nice if Dataverse SWORD API doc emphasize that the SWORD API does have a quite different auth mechanism then the Dataverse Native API doc.

The Dataverse SWORD API doc where would be nice to be updated:
* https://guides.dataverse.org/en/latest/api/sword.html

Forum thread where this point emerged:
* https://groups.google.com/g/dataverse-community/c/Sub1PzW5iPU

**Comment by djbrooke** [comment]
Thanks @joenio, it should be an easy addition.

**Comment by pdurbin** [comment]
@joenio thanks for creating this issue. Are you interested in making a pull request? The file to edit is doc/sphinx-guides/source/api/sword.rst. If not, no worries, we'll get to it someday. 😄

**Comment by joenio** [comment]
Hi @djbrooke @pdurbin I'll take a look in it soon, thanks for the tip about the place where lives the file.
