### ISSUE TITLE
guide latest =5.1.1

### ISSUE THREAD

**Issue by youssefOuahalou** [IQSS/dataverse#7448]
![GuideLatestVersion](https://user-images.githubusercontent.com/46802308/100899151-cdbd4d80-34c1-11eb-9273-a9b8121513d0.PNG)
Hello everyone,
There is a small problem the last version of the guide displays version 5.1.1 instead of version 5.2

**Comment by djbrooke** [comment]
Thanks @youssefOuahalou - we'll take a look

**Comment by djbrooke** [comment]
Hey @youssefOuahalou - this is resolved. You may need to refresh a few times. Thanks again for the heads up!
