### ISSUE TITLE
Dealing with Super User

### ISSUE THREAD

**Issue by michbarsinai** [IQSS/dataverse#745]
Having permission roots in the DvObject tree collides with having a super user. But maybe it's wrong to put that functionality on a *User* - we could implement it as a mode on the engine rather than as a permission.

Effectively, this could mean allowing some users to submit commands to the engine, and not have the engine check their permissions.

**Comment by eaquigley** [comment]
Passing to QA to close (@kcondon)

**Comment by kcondon** [comment]
Superuser is working, closing.
