### ISSUE TITLE
Workflow for requesting and approving access to published content 

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#746]
As in DVN 3.x, we need to support a workflow for requesting access to published content that hooks into notifications for approval.

Notes: https://docs.google.com/document/d/1Lmp70OrfLkX5UuXWVkz2iqh3H749n0pLo6tq69XtwWw/edit?usp=sharing

**Comment by scolapasta** [comment]
#1348

**Comment by eaquigley** [comment]
Passing this to QA to close as it basically is a duplicate of #1348

**Comment by kcondon** [comment]
Closing
