### ISSUE TITLE
Invalid response format (invalid JSON from API blocking code)

### ISSUE THREAD

**Issue by MingjingPeng-ANU** [IQSS/dataverse#7460]
Discovered this when calling the API to list permissions of a user and found the response returned by Dataverse was a piece of string '{ status:"error", message:"Endpoint available from localhost only. Please contact the dataverse administrator"}', which cannot be converted into a JSON as the format was invalid with "status" and "message" unquoted.

According to the tests, both version 4.20 and 5.0 have this issue while version 4.6.1 works fine as it returns an object instead.

**Comment by pdurbin** [comment]
@MingjingPeng-ANU thanks for opening this issue. It has bothered me for a long time that this part of the API emits JSON that isn't valid. There are actually three places which I've highlighted here:

https://github.com/IQSS/dataverse/blob/v5.2/src/main/java/edu/harvard/iq/dataverse/api/ApiBlockingFilter.java#L44-L111

If anyone out there is interested in making a somewhat small contribution, I don't think it would be too hard to quote "status" and "message" like you said.

**Comment by poikilotherm** [comment]
Related to #7171
