### ISSUE TITLE
E-mail notifications for completion of tabular data ingest behave differently from other notifications

### ISSUE THREAD

**Issue by BPeuch** [IQSS/dataverse#7461]
Versions: 4.20 and 5.2 (also observed on Demo Dataverse)

Howdy,

It seems that two of the notifications Dataverse sends by e-mail behave differently from the others. Those notifications are the ones users receive when a dataset they just created contains tabular data files. Their names in bundle.properties are ```completed``` and ```completedwitherrors```.

Compare this e-mail notification (as displayed in Outlook version 14.0.7258.5000), which users receive right after successfully creating a new dataset…

![justcrea](https://user-images.githubusercontent.com/15209224/101351323-bbac2800-3890-11eb-8914-82274e1454f0.png)

— As you can see, the font is the default one in Outlook's latest versions, Calibri. —

… with this e-mail notification, which users receive right after Dataverse is done ingesting a tabular data file:

![tabingest](https://user-images.githubusercontent.com/15209224/101351333-be0e8200-3890-11eb-9918-ad7e6e559cf5.png)

Here, the font is Times New Roman, and several linebreaks are missing:

- "Hello, [no linebreak] Dataset…"
- "… at support@dataverse.org. [no linebreak] Thank you, [no linebreak] Demo Dataverse Support"

It looks like ```completed``` and ```completedwitherrors``` are parsed as HTML, as the ```\n``` tags for linebreaks (used elsewhere in e-mail notification snippets) are ignored, while adding ```<br>``` in those two snippets effectively breaks the line.

**Comment by djbrooke** [comment]
Thanks @BPeuch, we can take a look at this. The notifications were added by an external contributor, but I think I wrote the messaging here, so I may have done something wrong. 🤔
