### ISSUE TITLE
Editing a dataset which had "Enable access request" unchecked, I check the box but Dataverse unchecks it in the newly published version

### ISSUE THREAD

**Issue by BPeuch** [IQSS/dataverse#7464]
Version: 5.2 (observed in Demo Dataverse)

Zdravstvuyte,

It seems that, when you follow these steps…

1. Create a new dataset;
2. Add a file;
3. Restrict access to this file;
3. Do not check the "Enable access request" box in the Terms section;
4. Publish the dataset;
5. Edit the Terms of the dataset by
– checking the "Enable access request" box;
– adding contents in various fields but especially in "Terms of Access";
6. Publish the new version of the dataset (whether as 1.x -> 2.x or as x.0 -> x.1);

… Dataverse unchecks the "Enable request access" box and does not take in the content placed in the "Terms of Access" field. 🚧 Input in other fields of Terms is accepted.

So in the end users still cannot 📢 request access to the file(s):

![inacs](https://user-images.githubusercontent.com/15209224/101501741-66474800-3970-11eb-8003-6fe9ba2f9587.png)

Link to the test dataset shown above: [https://demo.dataverse.org/dataset.xhtml?persistentId=doi%3A10.70122%2FFK2%2F03CIBW&version=3.0](url)

Notice how input is recorded for several fields in Terms from version 1.3 to 2.0 but the checking of "Enable request access" and the new content in "Terms of Access" is dropped: [https://demo.dataverse.org/dataset.xhtml?persistentId=doi%3A10.70122%2FFK2%2F03CIBW&version=3.0](url)

Conversely, it would seem that, in version 4.20, when you check the "Enable request access" box for a dataset that has already been published and then publish a second version, it becomes possible to 📢 request access for both datasets, as observed with this dataset: [https://test.sodha.be/dataset.xhtml?persistentId=doi:10.80118/FK2/3EGTZ7&version=1.0](url)

**Comment by scolapasta** [comment]
@BPeuch This is a known issue (#7427), as has been fixed for the next release, 5.3.

A workaround is 5.2. is to restrict any file from the Dataset (or file) page on a draft and set the terms / checkbox on that popup.

Closing, but please re open if I'm misinterpreting anything.

**Comment by BPeuch** [comment]
Ouch, my bad, the existing issue flew under my radar. Sorry for the double posting.
