### ISSUE TITLE
People requesting access to a file need visible feedback when request is sent

### ISSUE THREAD

**Issue by TaniaSchlatter** [IQSS/dataverse#7469]
With the UI changes to the action buttons in the file table on the dataset page, people who request access to a restricted file do not get feedback that the request has been sent. 

If the page is refreshed, there is an indicator in the user account in the header, and the user can not request access again (see image).

Note that the request is sent to people who are a curator for the dataset, or above, in terms of permissions. 

![Screen Shot 2020-12-09 at 10 21 46 AM](https://user-images.githubusercontent.com/15386424/101698763-12a82d80-3a48-11eb-9d9a-1c2b81850c2e.png)

**Comment by djbrooke** [comment]
We talked about this in the design meeting in the context of accessing DP releases in Dataverse, but we can move this forward independently. Options:

- We can add the green success message on the top of the page here, just when the message is sent 
- We can add the green success message on the top of the page here, and then persist a yellow message after the request has been sent
- Other?

We can bring this in to a sprint when we know the desired path here. I'd also be OK bringing this in and discussing there. 

cc: @TaniaSchlatter @mheppler

**Comment by TaniaSchlatter** [comment]
Shifting from green to yellow, as in the comment above would help to indicate time. Adding the date of request to the message on return visits before the request is approved would also help.

Green message after requesting would say something like, "Your request for access has been submitted to dataset curators" 

Yellow message when requestor returns to the page would say something like, "Your request for access was submitted to dataset curators on [Month, Day, Year]" 

More simple messaging would be a yellow status message for both situations – just after submitting and return visits. It would say something like, "Your request for access was submitted to the curators of this dataset on [Month, Day, Year]"

**Comment by scolapasta** [comment]
I think the yellow message is opens up some more challenges - since there can be multiple requests for multiple files made on different dates. So would we have several yellow messages at the top? I think that wouldn't be ideal. So we would need some rules for how to consolidate. And also do we specify which file or files in the yellow messages? I'm. thinking of datasets which may have 100s of files and how different to display for user A who request file 2, vs user B who requested files 5,8, 10, and 15 all on different dates, and user C who requested all the files.

From the backend, we don't currently store the date so we'd have to add that and also determine how to handle existing, dateless requests.

**Comment by TaniaSchlatter** [comment]
To try to get some part of this issue addressed in #7400, how about going with the hopefully simpler green option: Green message after requesting would say something like, "Your request for access to [dataset name] or [filename, filename, filename] or [4 files] has been submitted to dataset curators", adding the name of file(s) requested up to some number like 3, and adding the number of files requested if 4 or more files were requested.

Regarding the ability for the requester to know when the request was made, do we send a message to the user in their account messages when they have made a request? We have not logged that in the [reference workflows](https://docs.google.com/presentation/d/1kkihp4PkABfRjQ9Awkp5UJ8pUU9OjRE0DFB1mHLevwQ/edit?usp=sharing).

**Comment by mheppler** [comment]
>we don't currently store the date so we'd have to add that and also determine how to handle existing, dateless requests.

Back fill/reverse engineer from the notifications... 🤷 

<img width="1186" alt="Screen Shot 2021-03-15 at 12 15 23 PM" src="https://user-images.githubusercontent.com/687227/111185219-205dd980-8588-11eb-9c11-37a0b5a0616b.png">

**Comment by TaniaSchlatter** [comment]
[Mockups on pgs 10, 11, 12](https://docs.google.com/presentation/d/1XuX4qStdHjkFf4g1d1vKxxb85kuuUSEzdKN41dNM2mM/edit#slide=id.gc47211c9f7_0_24)

<img width="970" alt="Screen Shot 2021-03-18 at 1 37 43 PM" src="https://user-images.githubusercontent.com/15386424/112860108-831f9c80-9081-11eb-8d68-0bf0933e7218.png">

**Comment by TaniaSchlatter** [comment]
A simple, general green feedback message would be better than nothing. From January 13 comment above: 
Green message after requesting would say something like, "Your request for access has been submitted to dataset curators"

**Comment by TaniaSchlatter** [comment]
If there is only one file, and request has been made, the button should gray out. 

This discussion and situation is making me think about the need for/question of providing visible feedback in the file table, as we have been looking at when data file ingest fails (#[8096](https://github.com/IQSS/dataverse/issues/8096)). 

There seem to be a few situations where it is desirable to have file status clearly displayed without clicking on the Access dropdown.

**Comment by djbrooke** [comment]
- We could potentially tap into the file-row level feedback that we're added for ingest messaging (https://user-images.githubusercontent.com/21006/144502414-d5a4bc67-b914-45da-acc2-33788d06a961.png) - if we finish the ingest branch and get that in we can tap into that here
- Note that we have requests for showing more information on embargo (which is a bit different since that's label specific)

**Comment by sekmiller** [comment]
<img width="1172" alt="Screen Shot 2022-01-10 at 11 45 52 AM" src="https://user-images.githubusercontent.com/2364928/148804511-565fa80f-92f7-4509-aaea-c27ec39f441b.png">
<img width="1156" alt="Screen Shot 2022-01-06 at 10 36 09 AM" src="https://user-images.githubusercontent.com/2364928/148804519-53386fac-e87e-42da-8ca5-aa359714c0e9.png">
<img width="1174" alt="Screen Shot 2022-01-06 at 10 35 56 AM" src="https://user-images.githubusercontent.com/2364928/148804521-dbd595e6-6997-4168-83e1-74c193076385.png">

**Comment by sekmiller** [comment]
See above for screen shots of Request Access feedback. 
There's a success message in the banner when you Request Access.
Also in the files table there's an info label on each file where you have a pending request.
No change to the download button - if there's a pending request the link is disabled with the label "Access Requested"

**Comment by sekmiller** [comment]
Summarizing the changes which are in the forthcoming PR:

- A Success Banner message when there's a valid access request made
- An info tag added the the files table for any active request which will remain until the request is acted upon by the admin
- The general Request Access button will be removed when there are no more files that can be requested (all are public or all have been granted access or all have pending requests or any combination of the above)
- A warning message will be displayed if a request is made on a file that is already public or has an active request (this is possible if there is still a file or files for which a valid request may be made alongside others that are public, etc.)
