### ISSUE TITLE
Querying waiver/license via dataverse search API

### ISSUE THREAD

**Issue by mbamouni** [IQSS/dataverse#7482]
Hi,
This is not an issue but a request of improvement on the dataverse search API.
Currently, it is impossible to query the waiver/license field using the search API. I would like to know if it is possible to add this field in the fields indexes by solr and so we could querying it suing the search API?

Best regards,

Michel
INRAE

**Comment by pdurbin** [comment]
@mbamouni thanks for creating this issue.

Others, for more context, please see https://groups.google.com/g/dataverse-community/c/gtHgXt_eGtE/m/BYvglVT8BAAJ

One quick thought on this is that I don't see why we couldn't make this a facet. For example, researchers might be looking specifically for data with a CC0 waiver.

**Comment by pdurbin** [comment]
Related:

- #7482

**Comment by jggautier** [comment]
@pdurbin did you mean to link to another GitHub issue or PR?
