### ISSUE TITLE
Vagrant based quick setup fails because of missing "wget"

### ISSUE THREAD

**Issue by hkramski** [IQSS/dataverse#7483]
The Vagrant based quick setup (as described in https://guides.dataverse.org/en/latest/developers/tools.html) fails because of a missing "wget" in box 'bento/centos-8.2':
```
default: Installing jq for the setup scripts
default: /tmp/vagrant-shell: line 14: wget: command not found
default: chmod: cannot access 'jq': No such file or directory
default: mv: cannot stat 'jq': No such file or directory
```
Solution: Add `dnf install -y wget` at the top of `./dataverse/scripts/vagrant/setup.sh`.

**Comment by pdurbin** [comment]
@hkramski seems like a good solution to me! Do you feel like making a pull request? 😄
