### ISSUE TITLE
Deploying dataverse.war, database configuration other than defaults

### ISSUE THREAD

**Issue by mohammadsalem** [IQSS/dataverse#7495]
When installing dataverse `sudo -u dataverse python3 install.py --noninteractive --force --nogfpasswd` it fails with an error:
```
remote failure: Error occurred during deployment: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.6.payara-p1): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLException: Error in allocating a connection. Cause: Connection could not be allocated because: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
Error Code: 0. Please see server.log for more details.
```
While postgres is not running on localhost.

After the deploy failed, the installer continued and it was able to connect to the database:
```
performing database setup
Admin database connectivity succeeds.
PostgresQL version: 90620
Looks like the user already exists. Continuing.
WARNING: failed to create the database - continuing, since the --force option was specified
Database and role created!
```

default.conf content for database:
```
 [database]
 POSTGRES_ONLY = false
 POSTGRES_SERVER = postgres
 POSTGRES_PORT = 5432
 POSTGRES_DATABASE = dvndb
 POSTGRES_USER = dvnapp
 POSTGRES_PASSWORD = PASSWORD
 POSTGRES_ADMIN_PASSWORD = PASSWORD
```

The installation was on a Centos 8 docker image, Dataverse V5.3.

**Comment by pdurbin** [comment]
@mohammadsalem thanks for opening this issue. Do you have any explanation for "Connection to localhost:5432 refused"? That's PostgreSQL, of course.

Also, if you haven't yet emailed support@dataverse.org about this, please do. You'll receive a ticket number and if you put it into this issue I'd appreciate it.

Finally, you are also welcome to email the mailing list: https://groups.google.com/g/dataverse-community

**Comment by shlake** [comment]
UVa ran into this "similar" error:
```
Authentication failed with password from login store: /root/.gfclient/pass
Enter admin password for user "admin"> 
remote failure: Error occurred during deployment: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.7.payara-p3): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: java.sql.SQLException: Error in allocating a connection. Cause: Class name is wrong or classpath is not set for : org.postgresql.ds.PGPoolingDataSource
Error Code: 0. Please see server.log for more details.
Command deploy failed.
```

when attempting to (re)deploy V5.2 after an upgrade of Payara (using[ V5.3 release notes](https://github.com/IQSS/dataverse/releases/tag/v5.3))

It was a missing PG JDBC driver - which is not included in standard Payara install.

Our problem was fixed after 

- Stop payara
- grab a copy of https://jdbc.postgresql.org/download/postgresql-42.2.23.jar
- put that jar in /usr/local/payara5/glassfish/lib 
- then restart payara and try to deploy again

**Comment by pdurbin** [comment]
@mohammadsalem are you still having this problem? Do you need any help getting Dataverse installed?

**Comment by mohammadsalem** [comment]
Hi @pdurbin, version 5.3 installation worked only when running the installer as root 
```sh
python3 install.py --noninteractive --force --nogfpasswd
``` 
While for versions 5.4+ (until the current release 5.11.1) it was possible to run it as dataverse user 
```sh
sudo -u dataverse python3 install.py --noninteractive --force --nogfpasswd
```
We skipped version 5.3 and haven’t got the issue again.

@pdurbin @shlake thank you for your replies.

**Comment by pdurbin** [comment]
@mohammadsalem ok, great. Yes, it's important to run the installer as non-root. I'm glad that's working with newer versions.

I'll go ahead and close this issue. Thanks!
