### ISSUE TITLE
When Dataverse can harvest ICPSR metadata, it misses a third of records

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#7498]
UNC's Dataverse-based repository and Demo Dataverse (https://demo.dataverse.org) show an error when trying to create a harvesting client for ICPSR (see #7497).

But when I have been able to harvest ICPSR's metadata (using the oai_ddi25 metadata format and ICPSR "archive type"), most recently by creating [a Dataverse instance on AWS](http://ec2-54-81-175-218.compute-1.amazonaws.com/dataverse/root), Dataverse repeatedly fails to harvest 3,573 of the feed's 10,890 records. It does harvest the other 7,317 records.

I compared the DDI 2.5 metadata of a few records that Dataverse could and could not harvest, and the only difference I could see is that records that Dataverse failed to harvest have file-level metadata (in DDI's fileDscr element) while records that Dataverse successfully harvested do not include file level metadata. Also, when ICPSR's DDI 2.5 metadata does include file level metadata, it doesn't include the fileDscr element's ID or URI attributes.

So maybe the Dataverse code that imports DDI metadata from ICPSR's OAI-PMH feed doesn't like seeing file level metadata or expects to see more metadata about the files (like the ID and/or URI attributes)?

**Questions**
- When Dataverse is able to harvest some records from ICPSR, why is it skipping about a third of the records?
- More generally, is Dataverse indexing the file-level metadata in the records that it harvests or should it be? How does this or might this affect data discoverability?

I originally reported this bug in Harvard Dataverse's Github repo at IQSS/dataverse.harvard.edu#63, but this issue isn't really specific to Harvard Dataverse so I moved it here.

**Comment by djbrooke** [comment]
@jggautier - is there anything in the logs that has more info about what's happening?

**Comment by jggautier** [comment]
I have access to Harvard Dataverse's logs using Splunk, but I haven't tried harvesting ICPSR metadata into Harvard Dataverse because I'm waiting to hear if it's okay to remove the stale records at https://dataverse.harvard.edu/dataverse/icpsr, which should be the same records in the OAI-PMH feed now. (https://github.com/IQSS/dataverse.harvard.edu/issues/63 was originally about figuring out if it's okay to remove those stale records (and how it should be done) before harvesting.)

I've only recently harvested ICPSR metadata using instances created on AWS. Is it possible to access those instances' logs using Splunk? The database might have info about what's happening too. I see harvesting related things in the actionlogrecord table, but I don't know how to access the postgres database of instances created on AWS.

**Comment by djbrooke** [comment]
@jggautier thanks - I don't think there's an easy way to bring the logs for an instance into Splunk, as I remember it involved some setup with HUIT. The logs should be available somewhere, of course. We can bring this into a future sprint for more detailed investigation.

**Comment by jggautier** [comment]
This csv file contains the dataset oai-pmh ids and dois of the datasets that Dataverse can and can't harvest: 
[icpsr_oaiomh_missing_records.txt](https://github.com/IQSS/dataverse/files/5767485/icpsr_oaiomh_missing_records.txt)

**Comment by djbrooke** [comment]
- We'll need to revisit our DDI import and match it up to what ICPSR is exporting, this is a complex format and not used by many harvesting servers. Time to revisit the mapping.
- We should differentiate between datasets that have files and those that do not have files

**Comment by djbrooke** [comment]
Closing along with #7497.
