### ISSUE TITLE
Re-establish OAI sets in production

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#75]
---

Author Name: **Philip Durbin** (@pdurbin)
Original Redmine Issue: 3483, https://redmine.hmdc.harvard.edu/issues/3483
Original Date: 2014-02-03
Original Assignee: Philip Durbin

---

Translates OAI sets (defined as Lucene queries) into Solr and make sure they're compatible.

---

Redmine related issue(s): [3430](https://redmine.hmdc.harvard.edu/issues/3430)

---

**Comment by scolapasta** [comment]
We don't currently have OAI support; once we do, it will likely make sense to just start from scratch on what sets we offer. @kcondon please confirm you're OK with this.

**Comment by kcondon** [comment]
Closing, start from scratch as suggested.
