### ISSUE TITLE
UI Clean up - Review "disabled" state of links, buttons, dropdown menu options, etc

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#7511]
@scolapasta pointed out that disabled button dropdown menu options in the UI are sometimes still clickable. We should review as much of the disabled render logic in all the various links, buttons and dropdowns, to make sure the clickable objects that have a disabled state rendered, are actually disabled and nothing happens when you click on them.

<img width="359" alt="Screen Shot 2021-01-15 at 1 30 22 PM" src="https://user-images.githubusercontent.com/687227/104765923-b23b9880-5737-11eb-94a4-4a0ef820ea44.png">

**Comment by scolapasta** [comment]
Depending on where we find issues, there may also need to be made corresponding fixes in back end. For example, in the link search above, the back end doesn't stop it once you click save (and probably should).

Other disabled buttons may be ok, as if the disabling is permissions based, the command permission logic would stop it.
