### ISSUE TITLE
PR #7506 causes dataverseuser page failure/notification corruption

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#7512]
Part of the removal of worldmap related code was the removal of two types of UserNotification. Since those types were part of an enumeration that maps to numeric values in the database, values for any types later in the list have db type values off by 2 and any notifications with type =19 or 20 no longer correspond to any values in the enumeration and cause an internal server error with a log message like:
```
Exception [EclipseLink-116] (Eclipse Persistence Services - 2.7.7.payara-p3): org.eclipse.persistence.exceptions.DescriptorException
Exception Description: No conversion value provided for the value [20] in field [USERNOTIFICATION.TYPE].
Mapping: org.eclipse.persistence.mappings.DirectToFieldMapping[type-->USERNOTIFICATION.TYPE]
Descriptor: RelationalDescriptor(edu.harvard.iq.dataverse.UserNotification --> [DatabaseTable(USERNOTIFICATION)])
```
One solution is to add a flyway script to reduce the value of type for all usernotification entries >6 by 2. Presumably any entries for values 5,6 corresponding to world map notifications would need to be deleted? 

Or, if they need to be kept, perhaps just keeping those types in the enumeration is better (the code to generate them is gone).

(Note that any dev instance that creates new usernotifications after deploying the existing dev branch and prior to a fix for this would create entries with types according to the new shorter enumeration, so they would have to be treated differently from earlier notifications if their type needs to be retained.)

**Comment by mheppler** [comment]
Remove Worldmap/Geoconnect from Application #7409
