### ISSUE TITLE
Publish Dataset: Silently fail to publish dataset, server log shows facet minlength error.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#7518]
Cannot publish dataset in prod, fails silently, server log error indicates facet minlength error. See RT 298920. Attached is log.
[publishminlength.log](https://github.com/IQSS/dataverse/files/5844602/publishminlength.log)

[2021-01-20T13:35:19.701-0500] [Payara 5.2020.7] [SEVERE] [] [edu.harvard.iq.dataverse.DataCiteRESTfullClient] [tid: _ThreadID=340 _ThreadName=__ejb-thread-pool11] [timeMillis: 1611167719701] [levelValue: 1000] [[
  Response from postMetadata: 422, DOI 10.7910/dvn/kad4gg: [facet 'minLength'] The value has a length of '0'; this underruns the allowed minimum length of '1'. at line 46, column 0]]

**Comment by kcondon** [comment]
This particular instance was resolved but it revealed an underlying bug: It is possible to create metadata that passes validation but fails on publish, presumably due to it being a compound metadata field that is passed to DataCite upon publication and where child fields are populated but the parent field, eg. name is blank.

There have been several reports on this for different fields:
-Contact field has email address but no name: https://github.com/IQSS/dataverse.harvard.edu/issues/4#issuecomment-494878248
-Producer name missing: https://github.com/IQSS/dataverse/issues/6586
-Producer name missing but combined with Related Publication citation missing.

In the case mentioned in this issue, fixing either the Related Publication or the Producer name alone did not resolve the problem, presumably because both were failing cases and so both needed to be fixed before it worked. @donsizemore indicates he believed it to be metadata fields needed by DataCite and that makes sense. Needs to be confirmed though. Then scope to be either just those compound fields needed by DataCite need parent if populated at all or all compound fields? Not sure whether there is another case where not having a parent field would cause a failure, maybe Export as in

**Comment by kcondon** [comment]
Quick list of citation metadatablock fields passed to DataCite per Julian's crosswalk doc:
Dataset Persistent ID
Dataset Publisher
Publication Date
Title
Author
Name
Affiliation
Identifier
Identifier Scheme
Identifier Scheme URI
Contact
Contact Name
Contact Affiliation
Description Value
Producer
Name
Affilitation


Note that Related Publications is not listed but was definitely part of the failure case so not sure what that means, needs to be considered.

**Comment by qqmyers** [comment]
Does this match the DataCite.xml export format? (I think it should - same code underneath if I recall).

**Comment by kcondon** [comment]
@qqmyers I don't know how to confirm that. Export only shows fields that are populated, right?

**Comment by qqmyers** [comment]
yes - just thinking that if you see a field in the datacite.xml export that isn't in your list, e.g. for a test dataset with everything, you'd know your list was missing something.

**Comment by djbrooke** [comment]
Closing in favor of #7551
