### ISSUE TITLE
Tree performance: breadcrumbs, groups, etc

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#752]
Main point:  Discuss a tree management strategy for dataverses/groups (could be different strategies for each one).  

As @michbarsinai has pointed out in several meetings/emails, relational databases don't handle this well. 
- _dataverses_ - There needs to be a strategy for retrieving dataverse trees in a non-naive way.  (Then breadcrumbs can be re-activated)
- _groups/permissions_ - Group permissions (for potentially infinite depth groups) will be checked for every request.  What is the strategy for traversing group trees? 
### Background

Several parts of the system including dataverses and groups (soon-to-be-implemented) use  tree relationships of potentially infinite depth.

For example:  Root Dataverse -> Sub Dataverse -> Sub-sub dataverse, etc.

We should discuss strategies for handling dataverses and groups so that we aren't traversing the trees with naive SQL queries  (get parent, get parent, get parent).  

There are several methods to manage these relationships (all with trade-offs) ranging from object databases to several non-ideal SQL strategies such as [MPTT](http://www.sitepoint.com/hierarchical-data-database-2/).  In addition, there could be business rules to potentially limit tree depth, etc.

Related Ticket: #181 

/cc @michbarsinai  @scolapasta @pdurbin @landreev @sekmiller

**Comment by scolapasta** [comment]
We mitigated areas that had issues with the performance (e.g. featured dataverses only allow you to feature direct children). In order to allow features that want to traverse the full tree, we'll need to consider solutions to improve performance to a reasonable level.

**Comment by pdurbin** [comment]
One of the biggest things we lost due to the performance problems was the Integrated Faceted Breadcrumb (IFB) design from #128. We still don't have a great solution for people to simply get a sense of the what the tree of dataverses within an installation looks like. @pameyer and @bmckinney were just asking about this last week.

**Comment by michbarsinai** [comment]
This may be a good candidate for de-normalization. Unless there's a better solution, e.g. using Solr? @pdurbin - any index/data structure  we can add there to make these queries quick?

**Comment by pdurbin** [comment]
@michbarsinai Solr **does** have all the information about each DvObjects's position in the tree. For example, we say the "trees.png" file is under "Root Dataverse > Trees Dataverse > Spruce Dataverse > Spruce Goose" with '"subtreePaths":["/7", "/7/8"]'. 7 is for "Trees Dataverse" and 8 is for "Spruce Dataverse". See also "subtree" at http://guides.dataverse.org/en/4.3/api/search.html . Please keep in mind that we use the same "subtreePaths" Solr field for "linked" dataverses and datasets. It might have more information that you want. Anyway, there are now performance issues with retrieving data from Solr that I know of. I **think** some of the current performance issues have to do with permissions. We should benchmark the Integrated Faceted Breadcrumb (IFB) feature (or some other) with and without permission checks to know for sure.

**Comment by pdurbin** [comment]
@raprasad is the one who opened this issue and was its champion but I spoke with him today and now that no longer works on Dataverse day to day he doesn't plan to revisit most of the 63 issues that are still open in his name (this one is the oldest of those). This week I mentioned this issue and MPTT at https://github.com/IQSS/dataverse/issues/2122#issuecomment-403529813 and we can always re-open it if we feel like a lot of value is being added by having it remain open. Closing.
