### ISSUE TITLE
Where can I find the max length of each field in Dataverse?

### ISSUE THREAD

**Issue by flaviofrancisco** [IQSS/dataverse#7531]
Hi everyone;

I would like to know if there is a reference table with all max length fields of Dataverse. I was trying to find out it for the Description Field.

Thanks in advance. Stay safe.
Flavio.

**Comment by pdurbin** [comment]
SchemaSpy might help in general. Since it's a case of DatasetFieldValue, the "Description" field is of type "text" so it's effectively unlimited: http://phoenix.dataverse.org/schemaspy/latest/tables/datasetfieldvalue.html

**Comment by pdurbin** [comment]
@flaviofrancisco I see you gave my comment a 👍 

Does that mean it's ok to close this issue?

**Comment by pdurbin** [comment]
> http://phoenix.dataverse.org/schemaspy/latest/tables/datasetfieldvalue.html

phoenix was taken down a while ago and we need new hosting for schemaspy:

- #7031

We should probably close this issue in favor of that one.

By the way we (thanks to @donsizemore ) did a one off push a while back of schemaspy doc here:

https://guides.dataverse.org/en/5.4/schemaspy/

It's gotten us by for now in 5.x but it's getting out of date (5.12 is the latest release as of this writing).

**Comment by ffrnioz** [comment]
Hi Philip;
It's is Okay for me if you want to close this is issue.
Thanks;
Flavio.

**Comment by pdurbin** [comment]
Ok, thanks, Flavio. Much appreciated! 😄 Closing!
