### ISSUE TITLE
Very partial harvest from https://demo.dataverse.org/oai

### ISSUE THREAD

**Issue by tjouneau** [IQSS/dataverse#7545]
Hi,
This is a follow-up to messages to Dataverse-Users.
I'm currently testing OAI harvesting from a non-production instance of Dataverse (5.3). I'm having a cluster of problems, no repository I'm testing seems to work as it should. I'm starting with the most obvious, demo.dataverse.org.
Here's the configuration of my client : 

```
Alias : demo_dataverse_test
Server URL : https://demo.dataverse.org/oai
Local dataverse : moissonnage_demo_dataverse_2
OAI set : demodv_all
Metadata format : dataverse_json
Repository type : Dataverse 4+

```
The result shown in the interface reads "SUCCESS; 5 harvested, 0 deleted, 995 failed.". 5 on 1000 is better than zero but still :)
Looking at the log I've got messages like
`Error calling GetRecord - Failed to parse GetRecord response; baseURL=https://demo.dataverse.org/oai, identifier=doi:10.5072/FK2/09UWFI, metadataPrefix=dataverse_json`
for every record not harvested.
I'm attaching the log.
[harvest_demo_dataverse_test_2021-01-27T09-22-38.zip](https://github.com/IQSS/dataverse/files/5878770/harvest_demo_dataverse_test_2021-01-27T09-22-38.zip)

Any insight would be appreciated.
Cheers
Thomas

**Comment by jggautier** [comment]
Hmmm, about Demo Dataverse, it has [only 131 published datasets](https://demo.dataverse.org/dataverse/demo?q=&types=datasets&page=1&sort=dateSort&order=asc).

Here's info in the harvesting dashboard about the sets:

<img width="1159" alt="Screen Shot 2021-01-27 at 10 27 54 AM" src="https://user-images.githubusercontent.com/18374574/106013609-9b2b6d80-608a-11eb-9fa2-8f421a7c3378.png">

Are you telling your Dataverse instance to harvest the records in the demodv_all set? The query parameters for that set are too restrictive, so it's catching only the five datasets in Demo Dataverse whose DOIs start with 10.5072 (the five oldest datasets before I guess the DOI authority was changed). I can make the query parameters less restrictive or get rid of that set entirely. You shouldn't need to tell Dataverse to specify a set, and not specifying one should get you all 131 records. Let me know when you'd like me to do that. :)

**Comment by tjouneau** [comment]
Thanks a lot @jggautier for this answer. 
I managed to harvest all 131 datasets. My mistake was to choose demodv_all, 
Problem solved!
Incidentally though, I had to delete and re-create a client profile. Editing the existing one did result in a blank harvest (0 harvested / 0 deleted / 0 failed). No idea why?

**Comment by jggautier** [comment]
Not your mistake! =) It's a misleading set name lol. I'm going to remove it.

> Incidentally though, I had to delete and re-create a client profile. Editing the existing one did result in a blank harvest (0 harvested / 0 deleted / 0 failed). No idea why?

I'm not sure what deleting and re-creating a client profile means. Might be too technical for me! I'll defer to others (@pdurbin, @donsizemore?)

**Comment by tjouneau** [comment]
@jggautier Maybe "client profile" is not the right term. I mean that I had to erase the client demo_dataverse_set (by clicking on the delete button) and then create another one. Editing it did not do the trick. Strange.
![image](https://user-images.githubusercontent.com/6040893/106024841-75bd5480-60c8-11eb-8744-44168d87963a.png)

**Comment by jggautier** [comment]
Oh, hmm. And there's no log with more info about what happened when you re-ran the harvest after you edited it?

**Comment by tjouneau** [comment]
Hi @jggautier 
Here's the compressed log of the successful harvest. 
As the issue raised concerned the harvest and it is now successful, I think however it can now be closed. 
The neighbouring issue #7546 is the current fly in my soup and would need a closer insight if you ever have some time. 
Thanks again for your help :)
[harvest_demo_dataverse_test2_2021-01-27T16-56-23.log.gz](https://github.com/IQSS/dataverse/files/5910912/harvest_demo_dataverse_test2_2021-01-27T16-56-23.log.gz)
