### ISSUE TITLE
Silent publishing failure when not all fields required by Datacite are present

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#7551]
Short version, this is an attempt to consolidate #6586 and #7518. #7518 has some good logging details and information about the crosswalk.

I'm thinking we'd like to:

- Have an API endpoint that takes into account PID provider requirements as well as Dataverse requirements when returning a response (basically #6586, just not sure if it should be an existing or new API). There is a wrinkle here that some instances don't use DataCite and it may need to be taken into account when returning what's valid or not, but I'm sure we can work this out.
- Have better logging at publish time if there's a failure related to a missing field. Whenever this happens it seems like we have to reinvestigate because I forget about this issue. 🤯 
- Better communication to the user when something can't be published because of this (or require it when the Dataset metadata is being added). Right now it just leaves the data in an unpublished state after a silent failure.

Other thoughts welcome...

**Comment by djbrooke** [comment]
- @scolapasta suggested having both validation and messaging at entry time and at publish time (to catch any that made it through or are existing)
- In the cases were a subfield is required, there could be a trivial fix - this could be a change to the tsv

**Comment by mheppler** [comment]
Related? **Some Dataverse metadata fields seem not to be harvested/indexed correctly by DataCite #7072**

**Comment by scolapasta** [comment]
Since this is for a specific issue, I went ahead and created a new issue for the general solution of allowing for Conditionally Required fields: #7606
