### ISSUE TITLE
publication failure

### ISSUE THREAD

**Issue by virgilejarrige** [IQSS/dataverse#7571]
Hello,

Running two Dataverse 5.3 instances here with (almost) the same parameters, both using the same datacite test account.

On server A, everything is working.

On server B, there are 2 issues, second one will be in another message. 
When trying to publish a dataset it just fails. On datacite we can see the dataset in "DRAFT". 

In server.log I could notice these :

```
  [#|2021-01-27T08:57:57.052+0100|WARNING|Payara 5.2020.6|edu.harvard.iq.dataverse.dataaccess.ImageThumbConverter|_ThreadID=87;_ThreadName=http-thread-pool::jk-connector(4);_TimeMillis=16
  11734277052;_LevelValue=900;|
  Failed to read in an image from /usr/local/dvn/data/temp/s3://dnum-dataverse-pprd:17742d956f7-7f0d06b812e2: Can't read input file!|#]
```
  But we don't have any /usr/local/dvn folder.
  Could that be an issue?
  
  also,

```
  [#|2021-01-27T08:58:34.600+0100|WARNING|Payara 5.2020.6|edu.harvard.iq.dataverse.DOIDataCiteServiceBean|_ThreadID=223;_ThreadName=__ejb-thread-pool3;_TimeMillis=1611734314600;_LevelValu
  e=900;|
  modifyMetadata failed: Response from postUrl: 200, Not a valid HTTP(S) or FTP URL
  java.io.IOException: Response from postUrl: 200, Not a valid HTTP(S) or FTP URL
```

  which url is it trying to reach?
  
  and finally,

```
  [#|2021-01-27T08:53:33.376+0100|WARNING|Payara 5.2020.6|javax.enterprise.resource.webcontainer.jsf.lifecycle|_ThreadID=87;_ThreadName=http-thread-pool::jk-connector(4);_TimeMillis=16117
  34013376;_LevelValue=900;|
  For input string: "Direction du Numérique - DNUM"
  java.lang.NumberFormatException: For input string: "Direction du Numérique - DNUM"
  at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
```

I checked jvm options line per line - they are the same on server A or server B..

Help ^^

Take care,

Virgile

**Comment by qqmyers** [comment]
These look like 2 different issues, with your first two things above being related.

1. The place temp files are stored is defined by the dataverse.files.directory jvm option - you should make sure that's set to an existing directory (the temp files will go in a ./temp subdirectory of what you put in the jvm-option. (It also looks odd to me that the temp file error includes s3://dnum-dataverse-pprd in the path. That may be OK, but I would check your s3-related jvm options (for this issue and #7572) to make sure you have everything set, including dataverse.files.s3.type=s3 (where the first 's3' is the id of your datastore).
2. The DOIDataCiteServiceBean will try to contact the DataCite server you have configured. I think the error message means you are successfully contacting Datacite (the 200 response), but the landing URL being sent is not valid. My guess would be that this is related to some misconfiguration of your data store. This is just a guess, as I haven't seen this issue before, but I'd suggest figuring out 1) above and #7572 first and, with those resolved, see if this issue still exists.
3. The third looks like a Java complaint that it is trying to convert 'Direction du Numérique - DNUM' into a number and failing. To debug this, you'll need to find where that string is and decide whether it should be a number, or if the field where it is used is incorrectly configured to expect a numeric value. (If it is part of a metadata block, I think the tsv includes an entry to define the value type).

Hope that helps.

**Comment by virgilejarrige** [comment]
Thank you.

1. I fixed that but apart from not having the error message anymore it didn't change anything else.
s3://dnum-dataverse-pprd is not the path of our custom s3 location... it's "s3.unistra.fr"
Wierd..
2.  What is the "data store" ? 
I checked every jvm options related to file location and doi configuration - and it's the same on both servers!
**Test server (working):**
```
        <jvm-options>-Ddoi.username=INIST.xxx</jvm-options>
        <jvm-options>-Ddoi.password=xxx</jvm-options>
        <jvm-options>-Ddoi.baseurlstring=https://mds.test.datacite.org</jvm-options>
        <jvm-options>-Ddoi.dataciterestapiurlstring=https://api.test.datacite.org</jvm-options>

        <jvm-options>-Ddataverse.files.1.type=s3</jvm-options>
        <jvm-options>-Ddataverse.files.1.label=dataverse5-s3-test</jvm-options>
        <jvm-options>-Ddataverse.files.1.bucket-name=dnum-dataverse5-test</jvm-options>
        <jvm-options>-Ddataverse.files.1.download-redirect=true</jvm-options>
        <jvm-options>-Ddataverse.files.1.custom-endpoint-url=https://s3.unistra.fr</jvm-options>
        <jvm-options>-Ddataverse.files.1.custom-endpoint-region=eu-sxb-1</jvm-options>
        <jvm-options>-Ddataverse.files.1.path-style-access=true</jvm-options>
        <jvm-options>-Ddataverse.files.1.upload-redirect=true</jvm-options>
```

**pprd server (not working):**
```    
        <jvm-options>-Ddoi.username=INIST.xxx</jvm-options>
        <jvm-options>-Ddoi.password=xxx</jvm-options>
        <jvm-options>-Ddoi.baseurlstring=https://mds.test.datacite.org/</jvm-options>
        <jvm-options>-Ddoi.dataciterestapiurlstring=https://api.test.datacite.org</jvm-options>

        <jvm-options>-Ddataverse.files.storage-driver-id=s3</jvm-options>
        <jvm-options>-Ddataverse.files.s3.type=s3</jvm-options>
        <jvm-options>-Ddataverse.files.s3.label=s3-unistra</jvm-options>
        <jvm-options>-Ddataverse.files.s3.bucket-name=dnum-dataverse-pprd</jvm-options>
        <jvm-options>-Ddataverse.files.s3.url-expiration-minutes=60</jvm-options>
        <jvm-options>-Ddataverse.files.s3.custom-endpoint-url=https://s3.unistra.fr</jvm-options>
        <jvm-options>-Ddataverse.files.s3.download-redirect=True</jvm-options>
        <jvm-options>-Ddataverse.files.s3.upload-redirect=True</jvm-options>
        <jvm-options>-Ddataverse.files.s3.path-style-access=True</jvm-options>  
```
**How can I check that the landing URL being sent is valid or not?  And where do I configure it? I think it's my main issue.**
I saw that the fqdn was not configured propely in jvm options. But even when I changed that it didn't work any better. I even restarted the server, to make sure ...

We sent a message to Datacite so they can tell us what they see on their end.. but I'm really stuck there.

3. This is a name of a dataverse...! o_O I only wrote "DNUM" in case the "é" was causing trouble, but it didn't change anything. On the web ui side, there is no problem.

Oh, and  both instances are set on 10.80425/FK2/ - i checked with curl GET commands.

**Comment by virgilejarrige** [comment]
I forgot something important... here is how the email that is sent by dataverse looks like : 

test zip (view at dataverse-pprd.unistra.fr/dataset.xhtml?persistentId=doi:10.80425/FK2/FYVGSM) in DNUM (view at dataverse-pprd.unistra.fr/dataverse/dnum) could not be published due to a failure to register, or update the Global Identifier for the dataset or one of the files in it. Contact support if this continues to happen.

**Comment by qqmyers** [comment]
I'm not sure I'm following everything at this point. The URL sent to DataCite starts with the base provided by https://github.com/IQSS/dataverse/blob/a1928d8e6e24b4d2f8338091cde3578ae92f2d02/src/main/java/edu/harvard/iq/dataverse/util/SystemConfig.java#L328 - so setting the dataverse.siteUrl option would let you configure that directly (has to include the protocol - the https:// part and any port). If you don't have that set, the fqdn is used with https:// prepended.

**Comment by virgilejarrige** [comment]
Thank you!

It had indeed things to do with siteURL and fqdn.
As we have a separate apache/shibboleth server it had to be configured properly, which it wasn't.

Take care!
