### ISSUE TITLE
Publish in progress will not end, prevents adding of new data

### ISSUE THREAD

**Issue by jcuriel-unc** [IQSS/dataverse#7578]
Three weeks ago I uploaded a new version of my data, which included a 3631 X 19 csv, a readme, and a 51 X 3 csv, which included hyperlinks to the sources used to generate our data. However, the publish is still in progress, and will not allow any editing of the data. Is there any particular reason for this, or some means to fix this? Any help would be appreciated.

**Comment by djbrooke** [comment]
Hey @jcuriel-unc, sorry to hear about the trouble. Can you share a link to the dataset? 

There are two things that may be happening (off the top of my head):

- There was some issue either contacting the PID provider or verifying the files at publish time
- There is something in the dataset that flagged the spam detector that we're still tweaking

This is an issue tracker for the Dataverse Software generally, but I'm assuming you're trying to publish in the Harvard Dataverse Repository. If it's for one of the other Dataverse installations, we can get you in touch with the right support team. If the dataset is on the Harvard Dataverse Repository and you don't feel comfortable sharing the link here, you can email us at support@dataverse.harvard.edu.

**Comment by jcuriel-unc** [comment]
Hello Danny,

Thank you for the quick reply! I'm happy to share the link, which is below

https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/PEJ5QU&version=DRAFT

Given the two possibilities, I'd suspect it would be the
sources-senate.tab, which has hyperlinks to the websites we used to gather
the data. I am trying to publish on the Harvard Dataverse, so I apologize
about contacting the Dataverse software generally. Anything that you might
be able to do to help would be appreciated, and thanks again for your help!

Best,

John

**Comment by djbrooke** [comment]
Hi @jcuriel-unc, sorry for the delay. Can you please try publishing again? Thank you!
