### ISSUE TITLE
Dataverse Default Template Configuration not being applied

### ISSUE THREAD

**Issue by xoroz** [IQSS/dataverse#7590]
Hello,
I have been trying to configure the author filed "Affiliation" default for everyone that uses our dataverse.
I tried adding a metadata on user creation, and also on dataverse creation but it did not work.

Now I tried following the instruction to create a default dataverse template via https://guides.dataverse.org/en/latest/user/dataverse-management.html

I created my template and set on default on root, but it does not apply to existing or the new created DV.
It only works if I manualy go in each dataverse and change its default template to the one I just created.

Is there a easier way to apply default template to all dataverses? How ?

thank you

**Comment by xoroz** [comment]
anyone can help/comment ?

thanks

**Comment by djbrooke** [comment]
Hey @xoroz - I thought I replied to this last week but I guess I didn't hit send. We haven't done much work in this area recently, but can you confirm what version you're on and add some screenshots?

I'll ask some members of our curation team to add some additional details here, but if I'm understanding correctly, I think the steps would be:

- Go to the Root Dataverse
- Click Edit
- Click General Information
- Click "View fields + set as hidden, required, or optional" next to "Citation Metadata" 
- Click the radio button to make author affiliation required
- Save

Any new Dataverses created that "inherit from root" would use this configuration by default but would be able to deselect "inherit from root" and change the selection. I think a more permanent change would require an edit of the citation metadata block, which is not recommended.

**Comment by pdurbin** [comment]
@xoroz hi! Are you still having trouble with this?
