### ISSUE TITLE
UI feature request - tracking dataset users in large dataverse

### ISSUE THREAD

**Issue by bethtruesdale** [IQSS/dataverse#7594]
We have a dataverse with several dozen datasets.  It would be useful to have a feature in the UI that enables us to track which users have access to which datasets; enable access for a given user to multiple selected datasets at once; and disable access for a given user to multiple selected datasets.  Specifically, we want to:

(a) see which datasets are accessible by which users - for instance by downloading a spreadsheet that outputs a list of users for each of the XX datasets in the dataverse

(b) see a list of which datasets a given user has access to

(c) remove [grant] a given user's access to some or all the WFHN datasets at once, rather than going through the Permissions tab in each separate dataset

For example:

Let's say that Joe Jones leaves the project.  Joe has access to 26 of the 72 datasets (granted via the permissions page of each of the 26 datasets).  It would be handy if we could click a button that says "Remove Joe Jones's access to all [Dataverse Name] datasets" rather than having to go into each of the 26 datasets to remove access to each dataset individually. 

Failing that, it would be great to be able to make a list of users and associated datasets to make sure we haven't missed one or two of the 26 datasets as we're deleting Joe's permissions.

Conversely, it would be useful if we could *grant* access to multiple datasets at once.  For instance, let's say Sheila Smith joins the project and needs access to 8 of the 72 datasets.  It would be great if we could, say, see the list of all the datasets; tick a box next to each of the 8 datasets she needs; and give Downloader permission to Sheila for all 8 datasets at once. 

We know this can be done with Dataverse's API endpoints and some scripting, but wanted to suggest that this would be a valuable feature in the Dataverse UI.

**Comment by pdurbin** [comment]
@bethtruesdale the features you're talking about make complete sense but for now I'm wondering if you could make use of the "groups" feature. That way, you could remove Joe from the group with one click.

If you're not familiar with groups, here are a couple screenshots:

<img width="1133" alt="Screen Shot 2021-02-09 at 1 58 46 PM" src="https://user-images.githubusercontent.com/21006/107413837-3a1a8580-6adf-11eb-852b-17ef6e314ad3.png">
<img width="1133" alt="Screen Shot 2021-02-09 at 1 58 03 PM" src="https://user-images.githubusercontent.com/21006/107413843-3e46a300-6adf-11eb-8292-57f57829797c.png">

**Comment by bethtruesdale** [comment]
I will check it out, thanks!

**Comment by djbrooke** [comment]
Hi @bethtruesdale - I'll go ahead and close this out for housekeeping purposes, but please feel free to comment if the groups solution doesn't work for your use case and we can discuss further.
