### ISSUE TITLE
Helper method for setting required fields (e.g. distributorContact) on a dataset version

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#761]
@sekmiller and I just discussed how it would probably be worthwhile to have a helper method to set fields that are required, such as title, authorName, distributorContact, dsDescription, and subject.

That is, I'd love to have something like

`newDatasetVersion.setTitle("fooTitle");`

rather than...

```
List<DatasetField> datasetFields = new ArrayList<>();
DatasetField titleDatasetField = new DatasetField();
DatasetFieldType titleDatasetFieldType = datasetFieldService.findByName("title");
titleDatasetField.setDatasetFieldType(titleDatasetFieldType);
List<DatasetFieldValue> datasetFieldValues = new ArrayList<>();
DatasetFieldValue titleDatasetFieldValue = new DatasetFieldValue(titleDatasetField, "fooTitle");
datasetFieldValues.add(titleDatasetFieldValue);
titleDatasetField.setDatasetFieldValues(datasetFieldValues);
datasetFields.add(titleDatasetField);
newDatasetVersion.setDatasetFields(datasetFields);
```

(which I was doing https://github.com/IQSS/dataverse/blob/5226693e40b6ca82f8a5a5e3215b9ee4a2576b7d/src/main/java/edu/harvard/iq/dataverse/api/datadeposit/CollectionDepositManagerImpl.java#L143 )

**Comment by scolapasta** [comment]
There are already some generic helper methods (and I had updated the sword code to use). @pdurbin do you feel we need more?

**Comment by pdurbin** [comment]
> I'd love to have something like
> 
> newDatasetVersion.setTitle("fooTitle");

We don't have what I wished for above... the code looks more like this...

    DatasetFieldType emailDatasetFieldType = datasetFieldService.findByNameOpt(DatasetFieldConstant.datasetContact);
    DatasetField emailDatasetField = DatasetField.createNewEmptyDatasetField(emailDatasetFieldType, datasetVersion);
    for (DatasetField childField : emailDatasetField.getDatasetFieldCompoundValues().get(0).getChildDatasetFields()) {
        if (DatasetFieldConstant.datasetContactEmail.equals(childField.getDatasetFieldType().getName())) {
            childField.getSingleValue().setValue(user.getDisplayInfo().getEmailAddress());
        }
    }
    datasetVersion.getDatasetFields().add(emailDatasetField);

... which is better but still a fair amount of code for adding a value, in my opinion. I'll give this back to @scolapasta since he asked me to comment. Do with this ticket what you will. It certainly isn't user-facing. :)

**Comment by scolapasta** [comment]
OK, we'll consider for later, if we need anything more.

**Comment by raprasad** [comment]
this is cobol:)
```
DATA DIVISION.
   WORKING-STORAGE SECTION.
   01 TITLE PIC X(100) VALUE 'FOOTITLE'.
```

**Comment by eaquigley** [comment]
Passing to QA to close (@kcondon) per @scolapasta

**Comment by kcondon** [comment]
Closing
