### ISSUE TITLE
Error "Unsupported deployment descriptors element message-destination value null" during application deployment

### ISSUE THREAD

**Issue by poikilotherm** [IQSS/dataverse#7612]
When deploying recent Dataverse versions to Payara, I noticed the following error messages after server start, during the initial application deployment phase:

```
Unsupported deployment descriptors element message-destination value null
```

Looking around for similar problems on the internet, I found some old mailing list entries on these log messages regarding JMS.
(First Google results, e. g. [1](https://www.eehelp.com/question/dpl8007-unsupported-message-destination-element-descriptors-deployment/)).

After some investigation, it looks like using the `@Resource(name="")` syntax is not the best way to go. Sth. about referencing JNDI resources not physically located due to the new mechanism. Whatever - didn't dig deeper to understand every detail.

Looks like changing `@Resource(name="")` to `@Resource(lookup="")` might do the trick, but there is manual testing of Ingest needed.

PR forthcoming.

**Comment by landreev** [comment]
A silly question perhaps, but was that error message on startup *the only* negative effect of this? Or was it actually causing any real problems? (Ingest is still working in 5.3, as far as we know...)

**Comment by poikilotherm** [comment]
As far as I can tell, yes, that was the only effect. But as there were a lot of 'em (20-30) and IIRC as warning, I did not want to generate confusion and potential issues for the future...
