### ISSUE TITLE
Delete File: Can still search on files from versions more than 1 pub version back.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#762]
Tested on 7/23
Not entirely sure of the rules here but since search result card logic only shows at most 2 versions of a study: published and a draft, it makes sense that searching on a deleted file would at most show up the recent published version if it was deleted in draft and once that draft is published then no results. Confirmed with Phil.

It currently behaves correctly if 1 pub and 1 draft but once the draft is published with file deleted, the prior version containing the file is still searchable by filename.

**Comment by pdurbin** [comment]
I agree this is a bug. Here's how I reproduced it:

- create dataset (unpublished)
- upload file (dataset still unpublished)
- publish dataset (as v1)
- delete file (dataset enters draft)
- re-publish dataset (as v2, with no files)
- determine if the published file card is still around while browsing (it is and I agree it shouldn't be)

The next step, of course, is to fix the bug. :)

**Comment by pdurbin** [comment]
As of dde9997 the bug in the scenario above is no longer reproducible. Passing to QA.

Unrelated: @kcondon if you use my scenario, you might want to look at something somewhat related. If you go to V1 of the dataset and look at the Files tab, the thumbnail image is broken (this is more evident in Chrome than Firefox). I mentioned this to @landreev and he said there might be a ticket for this.

**Comment by kcondon** [comment]
Works, closing. I'll test any unrelated issues in their respective unrelated tickets.
