### ISSUE TITLE
Dataverse Software Naming Changes

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#7621]
Following the changes in #7501/#7567, we need to make updates of the Dataverse Software based on Merce's post in the Google Group:

https://groups.google.com/g/dataverse-community/c/pD-aFrpXMPo

**Comment by poikilotherm** [comment]
What about side projects like DV on K8s, pyDataverse etc? Do we need to rename those? What about the Github repos?

**Comment by djbrooke** [comment]
Hi @poikilotherm - thanks for the questions. I'll try to answer. :) 

- What about side projects like DV on K8s, pyDataverse etc? Do we need to rename those / change language there?

Yes, the user facing documentation and applications should follow the guidance. I made updates to pyDataverse in https://github.com/gdcc/pyDataverse/pull/81 and I'm happy to provide assistance elsewhere as needed/requested. Let me know.

- What about the Github repos?

The efforts are focused on user facing documentation and the applications, so I don't anticipate the need to make changes. We can come back to this if there's further guidance.

- What about artifacts like dataverse.war, container image names etc?

See above - no changes that I know of right now, but we can come back to this if there's further guidance.
