### ISSUE TITLE
Deterministic order of dataverse contents (API)

### ISSUE THREAD

**Issue by wibeasley** [IQSS/dataverse#7634]
*Feature request*: when the API returns objects within a dataverse, can the order be consistent across repeated calls?

I don't think the equation for the order matters, but having some consistent order would make our demo/example code more repeatable.  It would also eliminate the ordering that our test suite requires, [like @kuriwaki recently included](https://github.com/IQSS/dataverse-client-r/commit/09eb25aff9b38e976d2feadb2eb336b93991ee3d).

@pdurbin [isolated the following code](https://github.com/IQSS/dataverse-client-r/issues/85#issuecomment-785186798) in the [dataverse-client-r](https://github.com/IQSS/dataverse-client-r) repo:
```
@NamedQuery(name = "DvObject.findByOwnerId", 
            query = "SELECT o FROM DvObject o WHERE o.owner.id=:ownerId"),
```

I don't know the database, but two options that come to mind are:
1. ordering by the primary key for performance reasons, and
2. ordering by the human-assigned name.  So if the owner updates or deletes & recreates the object, the returned order is unchanged.

My slight preference is the latter, but either would help us and be appreciated.

(*@kuriwaki, anything you'd like to add?*)

**Comment by djbrooke** [comment]
Thanks @wibeasley, we'll consider this.

**Comment by djbrooke** [comment]
- We'd want to add an orderby to this query
