### ISSUE TITLE
Add "recent changes" endpoint to Native API

### ISSUE THREAD

**Issue by skasberger** [IQSS/dataverse#7646]
Getting a list of recent changes chronically ordered by the Native API, with the most recent change first. 

This should include:

Dataverses
* created
* updated
* deleted

Datasets
* created
* updated
* deleted
* destroyed

Datafiles
* uploaded
* update metadata 
* deleted

Suggested API endpoint name: `recent` or `recent-changes`

The response should consist of :

* all relevant identifiers
  * Dataverse
    * alias
    * id
  * Dataset
    * id
    * pid
    * version
  * Datafile
    * id
    * pid
* timestamp of change
* change id

**Comment by qqmyers** [comment]
How well does #7178 cover what you want?

**Comment by skasberger** [comment]
@qqmyers As a non-java developer, I can not really say.

**Comment by qqmyers** [comment]
[The updates to the guide for the PR](https://github.com/IQSS/dataverse/blob/708b1e8d1c638825d809a60b551638447b9c4f9a/doc/sphinx-guides/source/api/metrics.rst) might make things clearer. There's also discussion in the issue and [a spreadsheet showing what has changed/been added](https://docs.google.com/spreadsheets/d/1MxcaTtK4Uq_7-4HGt-X2C6hYo7FzrSYYH2mt3ln4M3w/edit#gid=777914207) but I think the guide update is a good summary.

**Comment by djbrooke** [comment]
Thanks @skasberger and @qqmyers for the discussion. 

@skasberger can you describe your use case for this new endpoint? It may be helpful in guiding the discussion.

**Comment by skasberger** [comment]
@qqmyers not really, as I understand.

@djbrooke : the main use-case for me would be to keep local data synced with one from an Dataverse installation. For example if you want to store all Datasets metadata as JSON locally, you can do it once with pyDataverse.api.get_children(). But this function takes a while (depending on the amount of data in the Dataverse installation) and often a request breaks this and the data collection must be started again. So it is not stable/reliable, but it works if you try it manually and have some time. But with the recent changes endpoint, it would be easy. Then i would call the endpoint once a day or week, download the new or updated Dataset metadata and store it locally as JSON. To sum it up: it would make keeping data synced way easier.

**Comment by djbrooke** [comment]
@skasberger thanks for the details, I understand. It sounds like the search API (https://guides.dataverse.org/en/latest/api/search.html) would do some of this with a Date Range search, but some of the things that you mention, like Destroy, would not be included.

**Comment by pdurbin** [comment]
Multiple options described above. Plus, Stefan left. Closing.
