### ISSUE TITLE
Add attributes to show dataverse contents endpoint of Native API

### ISSUE THREAD

**Issue by skasberger** [IQSS/dataverse#7648]
It would be very helpfull to get by default more information back from the [show dataverse contents](https://guides.dataverse.org/en/latest/api/native-api.html#show-contents-of-a-dataverse) API endpoint.

Following attributes would be great to be added to the response:

Dataverse:

* alias (nice to have)

Dataset

* version: as mentioned later, the version id would be better than the version itself.

Datafile

* checksum
* originalFileFormat

This would make harvesting and keeping data between installation and local environment way easier.

**Comment by djbrooke** [comment]
Hey @skasberger - can you talk a bit more about your use case for this? We talked about this a little in sprint planning earlier today and we don't necessarily want to include all the attributes in this response, as it could result in a very slow return for some of the larger Dataverse installations. We need to balance the amount returned in this response and the amount returned from other endpoints.

**Comment by skasberger** [comment]
I use this endpoint to harvest recursively the complete data tree from a dataverse instance. 

once done, then i want to keep it up to date. the same purpose, as i mentioned in #7646 . to save time and get rid of errors, this would be helpful too.

Explain the update issue:

if i have the dataset version, i can compare with the downloaded metadata from the first time. if it is the same, as returned by the API, i do not need to go deeper into the data-tree (e.g. datafiles) and save time. 

the same with the hash for the datafiles. if it is still the same as last time, dont download the data or metadata again.

but maybe there is another way to solve this problem. I was thinking of hashing the complete JSON response of an request of a Dataset. Have not tested it out, but if it stays the same, it should mean all the dataset metadata and the datafile metadata attached to it are still the same. but have to check if there are some time-depending values, which change for each request or something similiar problematic.

**Comment by jggautier** [comment]
> if i have the dataset version, i can compare with the downloaded metadata from the first time. if it is the same, as returned by the API, i do not need to go deeper into the data-tree (e.g. datafiles) and save time.

Hi @skasberger, if I understand correctly, this means you would be comparing the dataset version number of the metadata you've already downloaded to the version number of the dataset's latest version, and if those numbers are the same, you'd know the dataset has not been updated. Is that right? If it is, have you considered that "superusers" are able to make metadata edits without updating the dataset version? In that case, comparing version numbers wouldn't let you know that the dataset was updated. Maybe you could compare the version ID (the database ID for each version) if that's available from an API call? (Or, as you wrote of course, hashing the complete JSON response and comparing those.)

Hope that's helpful and sorry if I misunderstood something :)

**Comment by skasberger** [comment]
Thanks for the answer. 

Yes, that's right.

>  If it is, have you considered that "superusers" are able to make metadata edits without updating the dataset version?

No, did not know that. Then, getting the version ID from the get dataverses content endpoint would be good.

**Comment by scolapasta** [comment]
@jggautier Are you sure that the db id for the version changes in that scenario? I haven't looked at the code recently, but I could see it written either way.

**Comment by scolapasta** [comment]
Also @skasberger part of why we asked and were unsure here is that Ithe get Dataverse Contents API doesn't (and shouldn't, imo) return files.

**Comment by skasberger** [comment]
@scolapasta you mean the files itself, right, as it returns datafile metadata listed?

**Comment by jggautier** [comment]
> @jggautier Are you sure that the db id for the version changes in that scenario? I haven't looked at the code recently, but I could see it written either way.

I'm not sure. I was assuming it would, but I haven't tested it. I was thinking it was likely that in the database there would be _some_ record of the change, and I couldn't imagine that change not being associated with a different database ID, even if in the UI and metadata exports it looked like the version was overwritten. I couldn't tell from the code but could test in Demo if that's helpful.

**Comment by scolapasta** [comment]
I can check the code later (or of @qqmyers sees this, he might immediately know).

**Comment by qqmyers** [comment]
I think the code retrieves the old dataset version and copies the new values in - so no id change. (90% sure without checking)

**Comment by qqmyers** [comment]
One other thought - 7640 added a datasets/<id>/timestamps endpoint - I'm not sure that all changes are reflected in the dataset modificationtime, but if so, you could watch that...

**Comment by scolapasta** [comment]
OK, just checked code and can confirm that it maintains the id:

from CuratePublishedDatasetVersionCommand:
``` 
// Copy metadata from draft version to latest published version
updateVersion.setDatasetFields(getDataset().getEditVersion().initDatasetFields());

**Comment by skasberger** [comment]
Just some general thoughts: it would be nice to have some events table or so, where all interactions with the data are stored. just to have a history. can be used to offer audit trails, but also to update data as i want to do.

**Comment by cmbz** [comment]
2024/11/4: Closing because we are uncertain if the user still wants it. @skasberger please let us know if you have additional input.
