### ISSUE TITLE
Stop harvesting ?

### ISSUE THREAD

**Issue by virgilejarrige** [IQSS/dataverse#7650]
Hello,

Is it possible to abort an ongoing harvest?
(without breaking everything ^^)

Take care,

Virgile

**Comment by djbrooke** [comment]
Hey @virgilejarrige - this is resolvable through the database, @landreev left some instructions recently in the Google Group:

https://groups.google.com/g/dataverse-community/c/O-NdDtgFrI0/m/os_KjdLxAQAJ

I'll close this out, but feel free to comment and ask us to open this up again if we need to discuss further.
