### ISSUE TITLE
Import file PIDs / file DOIs

### ISSUE THREAD

**Issue by kaitlinnewson** [IQSS/dataverse#7665]
In the import API documentation, there is a note that file persistent identifiers can't be imported through that API. After reviewing the documentation, it appears there isn't any way to import file DOIs. Is this correct?

My context for this issue is that we're importing datasets from another Dataverse installation which had file DOIs enabled, and would ideally like to import them. It would also be ideal if these can be imported even if our install has file DOIs turned off.

Related Google group thread: https://groups.google.com/g/dataverse-community/c/rmDpYiSPzVU

**Comment by qqmyers** [comment]
This would be a useful addition to the import/migrate functionality, and something that would be good to support for reimporting Bags, but as of now, I'm not aware of any way to do this aside from accessing the database. https://github.com/IQSS/dataverse/pull/7504 deals with this for the Dataset (along with handling Terms of Use/Access) but nothing has been done yet at the file level. I don't think it would be too hard for someone to add, as long as the DOIs are managable by Dataverse (correct authority/shoulder).

**Comment by pdurbin** [comment]
Closing in favor of this issue:

- #10008
