### ISSUE TITLE
as-setup.sh aliases aren't expanded in traditional installation process

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#7668]
The BASH aliases specified in https://github.com/IQSS/dataverse/blob/develop/scripts/installer/as-setup.sh#L76 aren't handled correctly during a traditional/manual installation, and result in the following entries in domain.xml:

```
<property name="password" value="${ALIAS=db_password_alias}"></property>
<jvm-options>-Ddataverse.rserve.password=${ALIAS=rserve_password_alias}</jvm-options>
<jvm-options>-Ddoi.password=${ALIAS=doi_password_alias}</jvm-options>
```

Ansible and other installation methods may replace these lines with template data or deal with these settings in other ways, but at present anyone installing Dataverse from scratch must manually edit these values in domain.xml and restart Payara to get things working.

**Comment by poikilotherm** [comment]
Uhm @donsizemore I can't put my finger on it syntactically, but the intention was, IIRC to use variable substitution here to avoid clear text passwords.

https://docs.payara.fish/community/docs/5.2021.1/documentation/payara-server/server-configuration/var-substitution/usage-of-variables.html
