### ISSUE TITLE
API - find/delete group memberships for a user

### ISSUE THREAD

**Issue by veustp** [IQSS/dataverse#7676]
feature request: 
currently on version 4.20 of Dataverse
Authenticated (shibboleth) users are uploaded and (explicit) groups are assigned to them.
These groups are then granted roles on specific dataverses (e.g. a dataverse specific for a certain research department).

However, when users migrate within departments in the university in the course of their career, they would have to be unassigned from their previous group and to be re-assigned to their "new" group/department.

The API is being used for the upload.  However, no API was found to easily identify the (explicit) groups a user is currently assigned to.  This would facilitate un-assigning the user from these groups.  
Have we overlooked something?
If not, such an API, listing users' (explicit) group membership would benefit us.

The current workaround would be to retrieve all groups (/api/dataverses/$dv/groups/$grp) -keep them in memory to avoid doing this call for every user to be updated- and then use the API to "Remove a single role assignee from an explicit group".

Hope this is clear.

br, 
Pieter

**Comment by veustp** [comment]
Hi @djbrooke , thanks and wrt  #7629: the request for an API for "remove all roles" that does the equivalent of the button in the superuser dashboard, is closely related to what I'm asking for.  Although my request would opt for more fine-grained user detail (group membership) deletion.

**Comment by pdurbin** [comment]
@veustp these sound like useful features. Do you have any interest in making a pull request?

**Comment by veustp** [comment]
Hi @pdurbin, I've changed jobs - no longer working with Dataverse, so not interested anymore.
