### ISSUE TITLE
Reset Password button does not result in info banner feedback, shows no feedback in develop branch

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#7677]
Go to forgot your password, enter email, click Submit Password Request button and get no feedback where on demo/5.3 you get an info message saying it was sent if email exists.

**Comment by djbrooke** [comment]
Thx @kcondon. I reported this in #7106 but it's been frustratingly intermittent. I'll move to up next so we can dig in.

**Comment by kcondon** [comment]
So, after discussing with Stephen, found that disabling the updated google analytics code allowed it to work again: https://guides.dataverse.org/en/5.4.1/installation/config.html#web-analytics-code

Is this a case of the analytics code breaking the event handling/listener on the page? I don't know how that works so am speculating ;)

**Comment by sekmiller** [comment]
I added web analytics to my local environment, but I am still seeing the proper messaging on reset password.

**Comment by qqmyers** [comment]
FWIW: There was a time when the analytics code examples caused trouble - I think because they didn't have everything in CDATA blocks, so it's possible that out of date versions would break this and the latest wouldn't.

**Comment by sekmiller** [comment]
@qqmyers as a test I took out the CDATA blocks and now the messaging works. So what was the issue that adding it was trying to solve?

**Comment by qqmyers** [comment]
#5967
