### ISSUE TITLE
Revisit Button Stack, Highlight Publish

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#7678]
In the Dataset and File Redesign mockups the button stack used different colors to differentiate between buttons: 

<img width="325" alt="Screen Shot 2021-03-11 at 1 35 24 PM" src="https://user-images.githubusercontent.com/7773392/110837278-0615ba00-826f-11eb-8f29-878a2f41014f.png">
 
In the implementation, we don't have the different colors or order from top to bottom as expected:

<img width="299" alt="Screen Shot 2021-03-11 at 1 37 48 PM" src="https://user-images.githubusercontent.com/7773392/110837379-247bb580-826f-11eb-87e8-d3f86b4094fb.png">

I'll let @TaniaSchlatter fill in any additional details. This is part of the larger effort to get more people to publish (#7675 is another step here).

The button stack was designed expecting and using default Bootstrap 4 buttons without additional button styling. We will need to figure out what we can do. Here is a mockup using Boostrap 3 default button styles (applying "success" and "info" button styles):
<img width="335" alt="Screen Shot 2021-03-11 at 2 22 14 PM" src="https://user-images.githubusercontent.com/15386424/110843371-33b23180-8276-11eb-9129-6384f19ec337.png">

However, this is not a viable solution as several Bootstrap 3 default button styles including "info" are not accessible. There is not enough contrast between button color and text color.

**Comment by TaniaSchlatter** [comment]
The large, prominent, high-contrast button helped users publish in our small Harvard Dataverse study. [#109](https://github.com/IQSS/dataverse.harvard.edu/issues/109)
