### ISSUE TITLE
Uploading files to multiple datasets

### ISSUE THREAD

**Issue by dvabad** [IQSS/dataverse#7683]
We have previously created custom datasets in Dataverse and now we need to upload files to those datasets via API. To upload files to each dataset we need doi/handl, but we have hundreds of datasets and files. In each dataset metadata, we have an ID (which is the same with the file ID to be uploaded). I could not see any option such as uploading files to multiple datasets via API (such as iterating over files and uploading them to the suitable dataset). I am quite new to Dataverse. It would be nice to get some ideas.

**Comment by poikilotherm** [comment]
Sounds like a perfect use case for using a Python script and [pyDataverse](https://pydataverse.readthedocs.io/en/v0.3.0/user/basic-usage.html#upload-datafile). :smile:

**Comment by dvabad** [comment]
> Sounds like a perfect use case for using a Python script and [pyDataverse](https://pydataverse.readthedocs.io/en/v0.3.0/user/basic-usage.html#upload-datafile). 😄

Seems that is exactly what I needed. Thank you very much! 😄
