### ISSUE TITLE
Unhelpful Error Message when adding role with a duplicate(existing) alias

### ISSUE THREAD

**Issue by sekmiller** [IQSS/dataverse#7685]
If you attempt to add a Dataverse Role with an alias that is already in the table you get the generic "Not able to be saved" error. It would be helpful to add the reason. Underlying issue is that theCreateRoleCommand is not handling the database error that arrises. (Same result for adding role via api)

<img width="1209" alt="Screen Shot 2021-03-15 at 10 43 05 AM" src="https://user-images.githubusercontent.com/2364928/111171639-7d9f5e00-857b-11eb-9392-0f4198ce01fa.png">
<img width="1088" alt="Screen Shot 2021-03-15 at 10 42 43 AM" src="https://user-images.githubusercontent.com/2364928/111171647-7e37f480-857b-11eb-8224-2dd364a6d246.png">
<img width="1179" alt="Screen Shot 2021-03-15 at 10 37 57 AM" src="https://user-images.githubusercontent.com/2364928/111171648-7e37f480-857b-11eb-8d44-54a7dba06229.png">

**Comment by sekmiller** [comment]
Danny asked me if I could make this part of the fix for Delete Role API so I included the changes in that branch

**Comment by donsizemore** [comment]
I came here searching for a closely related issue: the Identifier "alias" is required, but not denoted as such:

<img width="657" alt="Screen Shot 2021-03-19 at 11 29 55" src="https://user-images.githubusercontent.com/12831666/111804522-89a25d00-88a6-11eb-95af-d12de9fc0573.png">

If a user attempts to create a role with out an identifier, the error message is similarly unhelpful:

<img width="1118" alt="Screen Shot 2021-03-19 at 09 54 09" src="https://user-images.githubusercontent.com/12831666/111804663-a8a0ef00-88a6-11eb-8d40-db962ab4da2e.png">

In this case server.log complains: `ERROR: null value in column "alias" violates not-null constraint`

It would be great to percolate a message back to the user stating that the Identifier field must be provided, and must be unique.

**Comment by sekmiller** [comment]
Thanks, Don. I didn't notice that when I was fixing the duplicate issue. Since this is still an open issue I can add the fix here. Also see about adding a UI "required"  indicator to the page.

**Comment by sekmiller** [comment]
UI Change with respect to suggestions made by Don. I added the "Required" asterisks for Name and Identifier (alias). I also added custom error messages for the popup. When the user fails to enter a name for the role the error message makes the popup bigger to accommodate. 
<img width="777" alt="Screen Shot 2021-03-22 at 3 45 46 PM" src="https://user-images.githubusercontent.com/2364928/112049600-3b9b8c80-8b26-11eb-956c-de657e98d511.png">
<img width="1029" alt="Screen Shot 2021-03-22 at 3 45 18 PM" src="https://user-images.githubusercontent.com/2364928/112049601-3b9b8c80-8b26-11eb-9150-127b810a429e.png">

**Comment by sekmiller** [comment]
@mheppler if you think this should be formatted differently the code in question is in roles-edit.xhtml around lines 11-40 for the input of Role Name and Identifier.

**Comment by djbrooke** [comment]
Hey @sekmiller - @TaniaSchlatter @scolapasta and I talked about this briefly and the format should match the validation messages on the other pages like in the screenshot shown:

![image (2)](https://user-images.githubusercontent.com/7773392/112181659-026d2600-8bd3-11eb-87f3-20e8d6032772.png)

**Comment by sekmiller** [comment]
Just checked in a change to format the required fields like this:
<img width="780" alt="Screen Shot 2021-03-23 at 2 20 01 PM" src="https://user-images.githubusercontent.com/2364928/112197951-00ab5e80-8be3-11eb-834e-4d28a9032ee2.png">

**Comment by sekmiller** [comment]
Moving back to Review
