### ISSUE TITLE
api.create_dataset("test",ds.json()) sends only "citation" metadata

### ISSUE THREAD

**Issue by dvabad** [IQSS/dataverse#7689]
I have JSON data for custom dataverse including several fields other than citation metadata. However, with esp = api.create_dataset() function only citation metadata is created. When I use the curl command (curl -H X-Dataverse-key:$API_TOKEN -X POST $SERVER_URL/api/dataverses/$DATAVERSE_ID/datasets/:import?pid=$PERSISTENT_IDENTIFIER&release=yes --upload-file dataset.json), it uploads all the data from the JSON file. So basically the problem is not related to JSON. Any idea?

**Comment by pdurbin** [comment]
I know this issue has already been closed but it sounds like a duplicate of https://github.com/gdcc/pyDataverse/issues/117
