### ISSUE TITLE
Add Subject field for dataverses

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#769]
Should use the same CV as the datasets and be indexed so that it can be part of the facets (should this be a general facet and always show?)

This was by request of Merce.

**Comment by eaquigley** [comment]
Requirements/Guidelines for this:

- [ ] On the General Information page for a dataverse, there needs to be another field called Subject with a the same list that is used for the Subject field for a dataset.
- [ ] Users can select multiple subjects for the dataverse
- [ ] The subject(s) selected for the dataverse (direct parent) should by default be selected for a dataset when it is created. 
- [ ] User should be able to deselect the preselected subjects

**Comment by posixeleni** [comment]
What if, since Subject IS a controlled vocabulary we have the system decide if it should map to Subject or Keyword?

So the logic would go as such for the mapping:

Map dcterms:subject to both subject and keyword. 
IF term matches controlled vocabulary THEN 
Map dcterms:subject to Subject
ELSE map dcterms:subject to Keyword.

Reviewing this with @mcrosas @scolapasta

**Comment by sekmiller** [comment]
Mike, can you take a look at Dataverse Subject.  It's at the top of dataverse.xhtml.

**Comment by mheppler** [comment]
Cleaned up layout and styled form elements for the Subject field in Dataverse General Information create/edit workflows. Also cleaned up the validation error layout.

**Comment by pdurbin** [comment]
I just checked the "There needs to be a subject facet that is populated with subjects from both dataverses and datasets" box above. Please note that the dataverse facet is collapsed into the dataset facet so to see it you need to enable the dataset facet. The "Subject" facet that is.

**Comment by scolapasta** [comment]
From the checkboxes: we set ALL subjects for the root in setup all.

We decided not to have any inheritance of subjects for now, so the last three checkboxes are no longer needed.

**Comment by kcondon** [comment]
OK, all checkboxes above are working. @pdurbin Searching on dv subject from basic search doesn't work, will open a ticket. Closing

**Comment by pdurbin** [comment]
> Searching on dv subject from basic search doesn't work, will open a ticket.

Right. Thanks for opening #1431
