### ISSUE TITLE
Question: OAI set with all datasets of a dataverse including those only included by link.

### ISSUE THREAD

**Issue by lmaylein** [IQSS/dataverse#7699]
Quick question:
Is it possible to define an OAI set in such a way that it contains all datasets of a dataverse including those that are only included via link?
parentId=... does not work (as already suspected).

**Comment by jggautier** [comment]
Hi @lmaylein, just for my own clarification, you're asking if it's possible to create an OAI set that contains only datasets have been "linked" into a Dataverse collection, using [the Dataset Linking feature](https://guides.dataverse.org/en/5.3/user/dataverse-management.html?highlight=dataset%20link#dataset-linking)?

So for example, the OAI set would contain records for only the linked datasets in the collection at https://dataverse.harvard.edu/dataverse/DiversityDatasets?

**Comment by lmaylein** [comment]
@jggautier : Not only the "linked" Datasets of a Dataverse collection but also the "real" childrens/Datasets. The OAI set should reflect all datasets that are displayed in the frontend in a specific dataverse.

**Comment by jggautier** [comment]
Using "subtreePaths" works...

<img width="1426" alt="Screen Shot 2021-03-19 at 4 39 22 PM" src="https://user-images.githubusercontent.com/18374574/111839767-b28c1780-88d1-11eb-96f7-16d43af36ded.png">

... where 1535 is the database ID of the Dataverse collection. If you visit that collection, https://dataverse.harvard.edu/dataverse/crp6, you'll see that the count of published datasets is 22, including some that have been deposited into other Dataverse collections (you might have to go to the second page of results to see the chainlink icons). And the OAI set includes all 22 records: https://dataverse.harvard.edu/oai?verb=ListRecords&metadataPrefix=oai_dc&set=CGIAR_Research_Agroforestry. In that XML doc you can do a search for and find doi:10.7910/DVN/7WEJV5, one of the datasets linked into that CGIAR Research Program on Forests, Trees and Agroforestry Dataverse collection.

You can also include multiple collections with "OR" between multiple subtreePaths, with slashes to narrow down to specific Dataverse collections within Dataverse collections:
<kbd><img width="1319" alt="Screen Shot 2021-03-19 at 4 50 37 PM" src="https://user-images.githubusercontent.com/18374574/111840920-870a2c80-88d3-11eb-94a0-24d00211748a.png"></kbd>

Hope that helps!

I think subtreePaths should be added to the examples listed in [the section of the Admin guide for creating OAI sets](https://guides.dataverse.org/en/latest/admin/harvestserver.html), and the description of parentId could be updated to note that what's returned will exclude any datasets linked into the Dataverse collection.

**Comment by lmaylein** [comment]
It works. Great. Thanks for the quick and detailed reply.

**Comment by lmaylein** [comment]
Adding this example to the documentation would be nice. Then I don't have to document it myself :-)

**Comment by djbrooke** [comment]
Hey @lmaylein - great to hear it's working for you. Would you be interested in making a Pull Request with this documentation change?

**Comment by lmaylein** [comment]
@djbrooke With pleasure. Where can I find the sources for the documentation?

**Comment by djbrooke** [comment]
Thx @lmaylein. I agree with the suggestion from @jggautier that it could be added as an example set on the Harvest Server documentation. There's a bulleted list starting at line 64 here:

https://github.com/IQSS/dataverse/blob/develop/doc/sphinx-guides/source/admin/harvestserver.rst

I would add this as a new example on that list. Thanks again!

**Comment by lmaylein** [comment]
The pull request has been submitted. #7713
