### ISSUE TITLE
When importing datasets via API, restrict files when indicated in the metadata JSON

### ISSUE THREAD

**Issue by kaitlinnewson** [IQSS/dataverse#7702]
Hi IQSS team,

I've been working on testing the migration of several datasets from one Dataverse installation to another (we are on 5.1.1). When metadata is exported as JSON for the datasets, the files section includes whether the file is restricted or not with `"restricted": true`. When importing through the API, it would be great if the file was then restricted at the time of import based on this metadata, as this doesn't currently happen. It will be more challenging to restrict it through the separate API for restricting files afterwards, as the file ID is going to change between the old install and the new one when importing.

Related Google group thread: https://groups.google.com/g/dataverse-community/c/eDxPaNweTR8

**Comment by pdurbin** [comment]
These days the migration API should be used: https://guides.dataverse.org/en/6.0/developers/dataset-migration-api.html
