### ISSUE TITLE
Error while uploading xlsx file format

### ISSUE THREAD

**Issue by dvabad** [IQSS/dataverse#7710]
I get an error after uploading the xlsx file. However, not all of them. Some work well

![Screenshot 2021-03-22 at 17 34 18](https://user-images.githubusercontent.com/43417266/112025911-f8e1b080-8b35-11eb-95fd-37665eba04ea.png)

**Comment by djbrooke** [comment]
Hi @dvabad -  errors from ingest are non-fatal conditions, and it's expected that the ingest tool won't be able to handle every file. We have files in the Harvard Dataverse Repository that don't ingest, and that's fine - when ingest fails, that Dataverse installation will still provide the file itself. Please don't consider it a requirement that all files are ingested successfully before publishing. The message you're seeing here is only shown to administrators and other privileged users at the dataset level.

If the file is public and non-sensitive feel free to share it here and we can take a look, but again, it's not expected that every file will be able to be ingested.

**Comment by dvabad** [comment]
Hi @djbrooke, Thank you very much for the explanation. I am new in Dataverse, so the error confused me. As the data file is private I cannot share it. However, your answer is enough for me.

**Comment by pdurbin** [comment]
Related:

- Improve Excel ingest documentation for troubleshooting #7452
