### ISSUE TITLE
Enable S3 redirects for "stored originals" of tabular files.

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#7720]
(this should be a simple fix/low-hanging fruit type of an improvement)

Even when S3 redirects are enabled, tabular files are still served locally. This is because of the variable names line (aka "variable name header") that needs to be added to the file contents in real time. (As stored, on disk/s3, an ingested file contains data columns only).
However, this should not be preventing us from issuing redirects for the stored originals; since nothing needs to be added there. 

Note that I will also open an issue to review and reconsider the above-mentioned scheme, of storing the ingested files without the var. name header and adding it in real time. This issue however is for an improvement that can be done quickly and without having to make any complicated decisions.

**Comment by djbrooke** [comment]
- will also apply to rdata files
