### ISSUE TITLE
Upgrade to Primefaces 10

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#7726]
While it hasn't shown up on https://www.primefaces.org/downloads/,  Primefaces 10 is now available on Github and Maven:

https://github.com/primefaces/primefaces/releases/tag/10.0.0
https://mvnrepository.com/artifact/org.primefaces/primefaces/10.0.0

Let's upgrade to catch up with some of the cool new features, security fixes, etc.

**Comment by djbrooke** [comment]
- Upgrading to PF8 was pretty straightforward. Needs testing, of course.
- Review docs (migration/backwards compatibility guide), bump in pom and get on an AWS instance for review
- Ask @4tikhonov if he can run the frontend test suite to identify any regressions

**Comment by akio-sone** [comment]
Just FYI: 
[Migration Guide](https://primefaces.github.io/primefaces/10_0_0/#/../migrationguide/migrationguide)
esp. 
from  [8.0 =>10.0](https://primefaces.github.io/primefaces/10_0_0/#/../migrationguide/10_0_0)

**Comment by scolapasta** [comment]
Seems like this issue was never closed, though the PR appears to be merged. Closing now.
