### ISSUE TITLE
Globus: StorageIdentifier for file matadata API

### ISSUE THREAD

**Issue by lubitchv** [IQSS/dataverse#7738]
Current API for file metadata `curl $SERVER_URL/api/files/$ID/metadata` does not bring storage Identifier. But file level download Globus external tool needs to know not only filename and directory label but also a storage identifier to provide information for globus transfer from dataverse to user globus end point.
So there is a need to storageIdentifier to that API.

**Comment by qqmyers** [comment]
FWIW: This API call is only returning info from the FileMetadata class now so it also isn't sending other info from the DataFile object such as the mimetype, checksum, size, DOI. (These are available from search, e.g. /api/search?q=identifier:\<id\> , but storageidentifier isn't.) Nor does it let you get the FileMetadata for any versions except the latest published one (or draft with an extra /draft at the end) - despite the fact that the code has versionId path parameter defined (it just isn't in the @Path defined).

It might be useful to clean this up and either add the DataFile info (including storageidentifier) to whatever version's FileMetadata info is included, and perhaps instantiate the versionId param, and/or distinguish Datafile (../metadata) and FileMetadata (../versionmetadata/\<id\> with :draft and :latest also allowed?).

**Comment by pdurbin** [comment]
@lubitchv @qqmyers now that the Globus PR has been merged, do we need to keep this issue open? Thanks.

**Comment by qqmyers** [comment]
It can probably close. The PR that went in gives the storageidentifier to Globus. A more general mechanism to get file info (not filemetadata info) and filemetadata info for earlier versions would still be useful.
