### ISSUE TITLE
Globus: DatasetVersion in dataset level externaltool

### ISSUE THREAD

**Issue by lubitchv** [IQSS/dataverse#7740]
At present dataset level external tool although provides a possibility to have DatasetVersion in manifest json and external tool url, but it always brings the last version of dataset, independently from which version user accesses the tool.
There is a need to provide a proper datasetVersion in external tool, not to confuse the user and give the ability to use information from the proper version.
This, for example, is needed for Globus download tool, such that user can access the files from proper version.

**Comment by pdurbin** [comment]
@lubitchv I see what you mean...

```
if(fileMetadata!=null) { //true for file case
    versionString = fileMetadata.getDatasetVersion().getFriendlyVersionNumber();
} else { //Dataset case - return the latest visible version (unless/until the dataset case allows specifying a version)
    if (getApiToken() != null) {
        versionString = dataset.getLatestVersion().getFriendlyVersionNumber();
    } else {
        versionString = dataset.getLatestVersionForCopy().getFriendlyVersionNumber();
    }
}
```

... at the dataset level the latest version is always returned. I'm not sure why.
