### ISSUE TITLE
Enable installations to add multiple license options to their installations

### ISSUE THREAD

**Issue by TaniaSchlatter** [IQSS/dataverse#7742]
Related issues:  #1753, #6015, #7440, https://github.com/IQSS/dataverse/issues/7691

This issue is to track current Discovery and Design efforts.

- [Proposal created by @qqmyers and sent out to the community](https://docs.google.com/document/d/10htygglMdlABYWqtcZpqd8sHOwIe6sLL_UJtTv8NEKw/edit) 
- [Miro board showing UI implications](https://miro.com/app/board/o9J_lTD_QGI=/?moveToWidget=3074457354702328868&cot=14) _out of date_
- [Slides with proposed UI design changes](https://docs.google.com/presentation/d/1vnbN3i7hW_00R5jU1TQH8QOqhrNhXmH9A6l0UA3zVq0/edit#slide=id.gc2696eff57_0_0)

How we will know the design meets the needs of DANS, Harvard Dataverse, and other installations:

- administrators can configure their Dataverse installation with additional/alternate pre-defined license choices 
- administrators can decide if custom licenses can be created 
- To be confirmed: administrators can define whether there is a default license and, if so, which license it is. 
- depositors will be able to select from a list of configured licenses prior to publishing a Dataset version, or enter custom terms (if custom licenses are allowed)
- data users and depositors can see the license more easily than visiting the Terms tab – i.e. on the dataset page, in the publish dialog
- Other machines can read the selected license 
- (other criteria?)

Next steps:

- [x] get input from those possibly affected by changes to the "disclaimer" field
- [x] review with Harvard Dataverse repository curators
- [x] re-send the request for review to the community with implications and a deadline for responses

**Comment by amberleahey** [comment]
We've enabled something like this using the templates feature , we are adding a new "Custom" template option in the dropdown of available CC license templates. Originally some were concerned that the default template provided by Dataverse was not clear enough to end-users that this is CC-0 so we set this up. Would be interested to see what is planned that would replace this for us to use. 
![Screen Shot 2021-03-31 at 1 05 48 PM](https://user-images.githubusercontent.com/17624834/113727460-25173880-96c3-11eb-8589-bbacf1129df2.png)

**Comment by amberleahey** [comment]
Sorry one more thing to add, these fields/template names are not in the metadata tab files so they are not easily translated in accordance to the internationalization of Dataverse, that would be great to address as well!

**Comment by 4tikhonov** [comment]
Hi @amberleahey, @qqmyers and @djbrooke, we did managed to put SPDX licenses list into SKOS format perfectly suitable for the internalization, and connect to Dataverse by using it as external controlled vocabulary. Please see the screenshot: 
<img width="1165" alt="Screen Shot 2021-04-11 at 11 31 56 PM" src="https://user-images.githubusercontent.com/704075/114377036-825d2f00-9b86-11eb-9033-6962c9caf38c.png">
 I'll be more happy to discuss this further.

**Comment by djbrooke** [comment]
Thanks @amberleahey for the previous comment and for including it in the Google Group thread, and thanks @4tikhonov for the comments here. We'll move forward with the proposal discussed (https://docs.google.com/document/d/10htygglMdlABYWqtcZpqd8sHOwIe6sLL_UJtTv8NEKw/edit) and can revisit the implementation later.
