### ISSUE TITLE
Solr - Security Access 

### ISSUE THREAD

**Issue by Fernand0S** [IQSS/dataverse#7751]
I am recently working with Solr Apache which is an application for real-time indexing, clustering and database integration. What surprised me was when I started the application that it really exposes. With that, anyone could perform the exclusion of data already indexed. When you notice that in the file solr.in.sh it is explicit that the JMX_REMOTE_ENABLE making anybody have access to your application through the GUI. In the published CVE of Apache Solr he mentions affected versions 8.1.1 and 8.1.2, however, in the versions I tested it also has this flaw.

Being able to upload my application in this way:

./solr start -j "-Djetty.host={hostaname}" -noprompt  

So I would not be exposed to "internet".

https://www.linkedin.com/pulse/solr-apache-ant%25C3%25B4nio-fernando/?trackingId=w4R04bad3beqx3kmDpkQNA%3D%3D

**Comment by pdurbin** [comment]
As explained at https://guides.dataverse.org/en/5.3/installation/prerequisites.html#securing-solr we only have Solr run on localhost.

**Comment by Fernand0S** [comment]
@pdurbin  So I mentioned above how to perform the Solr in safe mode.  or that way ./solr start -j "-Djetty.host=domain" -force 

with the iptables filter this way 

iptables -A INPUT -s ip.server/32 -p tcp -m tcp --dport 8983 -j ACCEPT

iptables -A INPUT -p tcp -m tcp --dport 8983 -j DROP

I hope it helps people with difficulty in exposing the solr to external access and safely

**Comment by pdurbin** [comment]
@Fernand0S ok, thanks. If you'd like to suggest specific changes to that page (with a pull request, ideally), you can find the source here: https://github.com/IQSS/dataverse/blob/develop/doc/sphinx-guides/source/installation/prerequisites.rst
