### ISSUE TITLE
Linking a dataverse into a "grandchild" of root not working

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#7766]
If you link a dataverse to a dataverse that is a direct child of root, everything works fine. However, if you link to a child of a child of root, then the linked dataverse (nor its dataverse or datasets) show. Note, that the link is correctly created in the db, so this appears to be an indexing issue.

This is not working wither in current production (5.3) or develop (5.4).

**Comment by scolapasta** [comment]
More details on where the problem lies (research gotten by using direct solr API to get the subtrees):

In the index we store the "subtrees" of of where the object exists and where it's linked; this code needs to be be reviewed and fixed.

Here are a couple example:

These are the subtrees for a dataset that is located in a grandchild dataverse and is linked in a grandchild dataverse (Note, that there is no issue with where this dataset displays, but it is here to a) compare to the 2nd example and b) also review some possibly extraneous unneeded subpaths):

"subtreePaths":["/1531",
          "/1531/3030068",
          "/3583725",
          "/3583725/3723273",
          "/3723273",
          "/3723273/1531",
          "/3723273/1531/3030068"]

We should review which if these are needed - The first two definitely, as they are for the dataset's parent dataverse and its parent (reverse order). The next two are for the dataverse it's linked two and its parent (again, reverse order). But I'm not sure the next three are needed / do anything as they start at '3723273, instead of one level up).

And here is a linked datataverse's subtrees, which is not showing up where it should:

"subtreePaths":["/1531",
          "/3723273",
          "/3723273/1531"]

In this one /1531 is itself. But the linked only shows the direct link and not the version with the parent of the linked, i.e. "/3583725" and  "/3583725/3723273". As in the last one, both the paths starting with just "/3723273" likely don't do anything and are unnecessary.

**Comment by scolapasta** [comment]
One more example:

This dataset is in the linked dataverse (that is not showing up) and at the same level as the dataset above, which was linked directly to the parent):

"subtreePaths":["/1531",
          "/1531/3030068",
          "/3723273",
          "/3723273/1531",
          "/3723273/1531/3030068"]

Again you see the correct: "/1531" and "/1531/3030068", but no "/3583725/3723273" or "/3723273", Instead, there's just "/3723273" and two others that seem probably extraneous...

**Comment by djbrooke** [comment]
- This will likely be a change to the indexing code for the subtree paths
- There was some limit previously to how deep the tree went (this was for the API but not for the UI), for performance reasons
