### ISSUE TITLE
Error creating dataset with Handle and sequential :IdentifierGenerationStyle

### ISSUE THREAD

**Issue by Fernand0S** [IQSS/dataverse#7769]
When updating Dataverse 4.10 and all processes up to version 4.20. When trying to create a dataset it displays the message that was not found. I made the list and it is there. 

I did the process of cleaning the timestamp and re-indexing, when trying to create this new dataset it presents the same error.

![image](https://user-images.githubusercontent.com/32446123/113786768-35093980-9710-11eb-9411-629abf95e62b.png)

![image](https://user-images.githubusercontent.com/32446123/113786783-3d617480-9710-11eb-9d0f-6a804ccfa3ed.png)

![image](https://user-images.githubusercontent.com/32446123/113786805-46524600-9710-11eb-8d5c-4e309386ac3f.png)

**Comment by Fernand0S** [comment]
remembering that the items appear on the dashboard visually

**Comment by pdurbin** [comment]
@Fernand0S I'm a little confused by what I'm seeing in your `ls` output. Here's how it looks for me:

```
beamish:FK2 pdurbin$ cd /usr/local/payara5/glassfish/domains/domain1/files/10.5072/FK2
beamish:FK2 pdurbin$ ls -lah | head
total 0
drwxr-xr-x  36 pdurbin  wheel   1.1K Apr  6 16:50 .
drwxr-xr-x   3 pdurbin  wheel    96B Apr  5 15:49 ..
drwxr-xr-x   8 pdurbin  wheel   256B Apr  6 12:57 1ECAAW
drwxr-xr-x   5 pdurbin  wheel   160B Apr  6 12:45 1YBTCA
drwxr-xr-x   8 pdurbin  wheel   256B Apr  6 12:56 3YLKQK
drwxr-xr-x   8 pdurbin  wheel   256B Apr  6 12:46 42PYR0
drwxr-xr-x   5 pdurbin  wheel   160B Apr  5 16:42 4KWDBG
drwxr-xr-x   8 pdurbin  wheel   256B Apr  5 15:49 7DSNJE
drwxr-xr-x   3 pdurbin  wheel    96B Apr  5 15:52 986HIV
beamish:FK2 pdurbin$ 
```

When you show 32 through 69, are those datasets?

Do you have :IdentifierGenerationStyle set to something other than "randomString"?

Are you using Handles instead of DOIs?

Can you please add a screenshot of what the create looks like when it fails?

Thanks.

**Comment by Fernand0S** [comment]
Yes, Phil. I'm using Handle instead of DOI. I am using the data set sequentially. 

![image](https://user-images.githubusercontent.com/32446123/113900708-7fd49100-97a4-11eb-8290-b34464d984c7.png)


I remember that I previously talked to you about this same incident and I mentioned the Schema.xml and Solrconfig.xml settings, but how did I overwrite this mistake correctly?

**Comment by pdurbin** [comment]
It certainly could be related to Solr. Can you please look at server.log and show us the errors when creation of a dataset fails? you can attach it here as .txt or email it to support@dataverse.org

**Comment by Fernand0S** [comment]
@pdurbin above I attached the server.log to the screen.

Dataset change is successful, creation of a new repository is successful too, only error when inserting a new dataset. 

![image](https://user-images.githubusercontent.com/32446123/114107180-db874300-98a6-11eb-9aa6-cd5ac8b4640a.png)

**Comment by pdurbin** [comment]
@Fernand0S thanks but I can't see what the problem is. Perhaps you could email the entire server.log to support@dataverse.org so we can take a look.

Also, I renamed this issue to make it a bit more specific.

**Comment by Fernand0S** [comment]
@pdurbin After performing updates until arriving at the dataverse 4.20 deploy and checking the log I noticed the following error:  Could not find storage driver for: file://20.500.12196/CIDACS/32]]

When executing the commands below

./asadmin create-jvm-options "\-Ddataverse.files.file.type=file"
./asadmin create-jvm-options "\-Ddataverse.files.file.label=file"
./asadmin create-jvm-options "\-Ddataverse.files.file.directory=<your directory>"

checked the log file has the same error.

**Comment by Fernand0S** [comment]
Resolved the question "**Could not find storage driver for**".  trying to resolve the issue of inclusion of dataset.

**Comment by Fernand0S** [comment]
@pdurbin Do you have an answer about this dataset registration error? 

Yesterday I did a table test with the following conditions below;

Upgrade from 4.10 to 4.10.1 - it has been successful (validation of repository registration, deletion and editing, creation of dataset, editing of dataset and removal of dataset).

Update from 4.10.1 to 4.11 - it has been successful (validation of repository registration, deletion and editing, creation of dataset, editing of dataset and removal of dataset).

Update from 4.11 to 4.12 (failure)

**Comment by djbrooke** [comment]
Hey @Fernand0S - I saw your response to my email in the ticketing system, I just haven't yet had a chance to respond. I'll respond again soon.

**Comment by qqmyers** [comment]
FWIW: I haven't been following this closely, but I see that 4.12 updated the version of the Handle library used (#4792) and introduced a new setting :HandleIsIndependentService (discussed in  #5587). Could these be involved?

**Comment by Fernand0S** [comment]
Yes, @qqmyers jvm-options is used for the Handle, informing in this way

<jvm-options> -Ddoi.username = 0.NA / xx.xxx.xxx </jvm-options>

**Comment by pdurbin** [comment]
@Fernand0S hi, are you still having trouble? Did you pick a different style instead?
