### ISSUE TITLE
Provide Dataverse Statistics to OpenAIRE

### ISSUE THREAD

**Issue by sourcedump** [IQSS/dataverse#7782]
Hello!
We are interested in providing view and download statistics to the openaire content dashboard ( https://openaire.github.io/usage-statistics-guidelines/ ).
The Generic matomo tracker script doesn’t seem to be sufficient for that, have anyone build a solution for that?
I've also opened a twin issue here: https://github.com/openaire/Generic-Matomo-Tracker/issues/9

Thank you!

**Comment by djbrooke** [comment]
Hi @sourcedump - have you seen the Make Data Count integration? Would that be of any help to you? 

https://guides.dataverse.org/en/latest/developers/make-data-count.html

**Comment by pdurbin** [comment]
@sourcedump hi! Just checking if you saw the question above. Also, it looks like you were asked for further elaboration on the Matomo side (which is probably the way to go):

- https://github.com/openaire/Generic-Matomo-Tracker/issues/9#issuecomment-817731116

Please let us know how we can help. Thanks!

**Comment by pdurbin** [comment]
> Also, it looks like you were asked for further elaboration on the Matomo side

Nothing yet.

@sourcedump are you still interested in this?

**Comment by juancorr** [comment]
Hi @pdurbin and @sourcedump,
   I am interested, and we could contribute to this if @sourcedump was no
longer interested.
  Best,
Juan Corrales

**Comment by pdurbin** [comment]
@juancorr great! I would suggest replying here first:

- https://github.com/openaire/Generic-Matomo-Tracker/issues/9

**Comment by juancorr** [comment]
Perfect,
  Seeing the Generic-Matomo-Tracker configuration, I think that we only
need to adapt the configuration file when the MDC is active.

  I hope to do the tests this week and after that I will reply in the
OpenAIRE issue.

Juan Corrales

**Comment by cmbz** [comment]
@juancorr Do you still need this feature? Or have you solved the problem another way?

Also, @jp-tosca can you review and see if there might be any interaction/relevance of this feature request to the Dataverse Metrics Hub?

**Comment by juancorr** [comment]
Hi @cmbz, There were some problems with the OpenAIRE statistics and now, it is not one of our priorities. 
If we decide to implement it in the future, we will tell you.

**Comment by cmbz** [comment]
Thanks @juancorr I'll close the issue now.

**Comment by cmbz** [comment]
See conversation: [here](https://github.com/IQSS/dataverse/issues/7782#issuecomment-2455000401) and [here](https://github.com/IQSS/dataverse/issues/7782#issuecomment-2457505798)
