### ISSUE TITLE
DataCite Fabrica metadata does not work with organization as author

### ISSUE THREAD

**Issue by skasberger** [IQSS/dataverse#7783]
We at AUSSDA have a problem with registering DOIs on DataCite. As it seems, DataCite Fabrica uses the sent author metadata from a Dataverse dataset during creation or publishing in the format `FAMILYNAME, FIRSTNAME`. But as we currently have Datasets, where the author is an Organization, the requested/required format is not sent, so the DataCite Fabrica DOI creation process fails. 

We solve it right now by manually changing the type in each DOI in DataCite Fabrica from person to organization. 

Would be great, if Dataverse could handle this automatically.

Dataverse: 4.18.1 (data.aussda.at)

**Comment by pdurbin** [comment]
Stefan left. Closing. Besides, I'm pretty sure we sent orgs across the wire to DataCite all the time.
