### ISSUE TITLE
Prevent "null" as email sender

### ISSUE THREAD

**Issue by pkiraly** [IQSS/dataverse#7784]
If the [:SystemEmail](https://guides.dataverse.org/en/5.3/installation/config.html#systememail) value does not contain a name, only an email address, and the user use contact form or the "Contact owner" form to send a mesage, the sender of the email will look like this:

null on behalf of name@example.com <dataverse@example.edu>

The guide says: "Note that only the email address is required", so Dataverse should handle both cases: when the name is supplied and when it isn't. Now the missing name ends up as "null" in the sent email.

**Comment by poikilotherm** [comment]
Related to #7424

**Comment by pkiraly** [comment]
> Related to #7424

I don't know how to reflect to that. I have created a pull request to fix this single issue, and also to remove some unwanted spaces from the Java class.

**Comment by poikilotherm** [comment]
No worries. Just a pointer for me that there have been some changes and I need to carefully revisit the code with this aspect in mind.

**Comment by pkiraly** [comment]
Thanks for the clarification!

BTW: do you have an idea how to create integration test for this service?

**Comment by poikilotherm** [comment]
Easy. Testcontainers, Mailhog/MailCatcher and a REST client all in a JUnit test.

**Comment by TaniaSchlatter** [comment]
This is a nice improvement. Thanks @pkiraly @poikilotherm & Harvard team for moving this forward.

**Comment by pkiraly** [comment]
Thanks @TaniaSchlatter!
