### ISSUE TITLE
No URI in OAI-PMH records (with oai-ddi metadata prefix)

### ISSUE THREAD

**Issue by tvi-cdsp** [IQSS/dataverse#7786]
From our understanding, we could have an URI Provided inside a metadata "holdings" tag pointing to the dataset (in the form of an URL https://doi.org/… rather than the DOI itself doi:10.21410/7E4/SRVNPE).
This uri, in ddi-codebook 2.5 xml, should be in codeBook -> docDscr -> citation -> holdings or/and codeBook -> stdyDscr -> citation -> holdings

This should allow Dataverse to provide "self sufficient" records in OAI-PMH records.

Example of desired result : http://services.fsd.tuni.fi/v0/oai?verb=GetRecord&identifier=oai:fsd.uta.fi:FSD1262&metadataPrefix=oai_ddi25

**Comment by gmi-cdsp** [comment]
Hi !

From a recent discussion around CESSDA data catalogue, it would be a better practice to use the first: 
`<pr:Used xpath="/codeBook/stdyDscr/citation/holdings/@URI" isRequired="true">`

**Comment by jggautier** [comment]
Hi @gmi-cdsp and @tvi-cdsp. Could you write a little more what you mean by "self sufficient"? I'm just curious :)

**Comment by gmi-cdsp** [comment]
Hi Julian. I guess we meant both that conforms to the DDI standard and that provides records including a URI. This URI would be displayed without transformation (self sufficient would mean clickable in that regard)?

**Comment by jggautier** [comment]
Ah thanks, makes sense to me!

**Comment by qqmyers** [comment]
From the description and example in the [DDI documentation for the holdings element](https://ddialliance.org/Specification/DDI-Codebook/2.5/XMLSchema/field_level_documentation_files/schemas/codebook_xsd/elements/holdings.html), it looks like putting file information as multiple holdings elements (with the file page URI/file DOI as the URIs) might be a better practice. I see right now that files are currently listed as other Materials (otherMat). 
Does such a change make sense? Or are there services that expect files in otherMat?

**Comment by tvi-cdsp** [comment]
It seems to be a better practice indeed, sadly i cant speak about other services using otherMat.
I might be missing something, but it seems to me that modifying otherMat elements and adding a holdings element to docDscr and stdyDscr citation containing the doi url are two separate issues? Am I missing something here?
