### ISSUE TITLE
Improve .zip upload messaging to improve use & display of file hierarchy

### ISSUE THREAD

**Issue by TaniaSchlatter** [IQSS/dataverse#7797]
Data depositors who want to have their .zip file display the file hierarchy aren't aware of the 1,000 file default limit (configurable by installation – 1,500 for Harvard Dataverse), and don't get a message in the UI when the .zip is not displaying the hierarchy. The result is that file hierarchy display seems random – sometimes it works, sometimes it doesn't. 

Ideas to improve are:
- make it clear in the user guides that the limit includes all files 
- add a bit of text in the UI to help users be aware of the .zip limit along with the size limit (image)
- system check the number of files in the .zip on upload and show a "warning" message that the .zip file has more files than the limit for displaying the hierarchical view (not shown).

![Screen Shot 2021-04-13 at 1 01 26 PM](https://user-images.githubusercontent.com/15386424/114608726-fae9eb80-9c6b-11eb-9d41-90af8bda5e4b.png)

**Comment by pdurbin** [comment]
Yes, good idea. It's a bummer we didn't work on this as part of this PR:

- #8271

Oh well. Following those changes, here's how the UI looks for Harvard Dataverse, running 5.11.1 currently:

<img width="954" alt="Screen Shot 2022-10-01 at 8 18 23 AM" src="https://user-images.githubusercontent.com/21006/193409272-2d03f6e4-8799-4450-a736-4f3de9138d75.png">

Yes, we should show the :ZipUploadFilesLimit as well.

(Note that the 1000 files shown in the screenshot is for :MultipleUploadFilesLimit.)
