### ISSUE TITLE
Dataverse 5.3: Configure button not showing on Geospatial

### ISSUE THREAD

**Issue by ipcraiurosario** [IQSS/dataverse#7809]
Hi!

I'm trying to configure the map of one .tab file, but the "configure" button is not showing in any of my .tab files that had been tagged as geospatial.

These are the options that I get:
![image](https://user-images.githubusercontent.com/53486765/115052695-dbd59e80-9ea3-11eb-9e41-399938954f85.png)

Meanwhile in the dataverse guide (https://guides.dataverse.org/en/5.3/user/data-exploration/worldmap.html#id5) the section "Preparing a tabular file to be mapped" item 3 says that the missing button should be there for me to use it.

Hope you guys can help with this... and again, thank you all for your time.

**Comment by djbrooke** [comment]
Hi @ipcraiurosario - we've removed the Worldmap integration in the Dataverse Software. You can read about the changes in the 5.4 release notes here:

https://github.com/IQSS/dataverse/releases/tag/v5.4

I believe we removed this from the kebab in 5.3. and the removal became official in 5.4.
