### ISSUE TITLE
Aux Files: Add some checks  to aux files on upload

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#7819]
Add file validation: particularly duplicate names, which when occurring on the same tabular file results in a 404 on download. Name is comprised of format tag+format version.

Potentially add file size and file count limits.

**Comment by qqmyers** [comment]
Also have a fix for this. Awaiting the changes from #7729 to make a PR.

**Comment by djbrooke** [comment]
I'll close based on the third bullet in https://github.com/IQSS/dataverse/pull/8237#issue-1050059307 - please reopen if this is not the case. We can revisit the count and size limits if this gets more widely adopted.
