### ISSUE TITLE
Download Tracking: global id in exported excel spreadsheet incorrectly puts study db id in place of study global id.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#782]
This was reported by our friends in the Netherlands, see RT #181922 in v3.6.2.
Replied that it most likely will be fixed in v4.0 but recording here for reference:

If I look at the Download Tracking Data in the
Network Options online, the IDs are correctly shown as "hdl:10411/<global
ID>", but in the downloaded CSV file the IDs in the column Study Global ID
are "hdl:10411/<internal ID>". We use handles only.

For example (headers + 1 line of log):
User/Session,First Name,Last
Name,Email,Institution,Position,Dataverse,Study Global ID, Study
Title,Study File,Time,Type,Session
Anonymous - + ad8496d39061585d1197d8c5384d,,,,,,Website Institutions for
Collective Action - Guilds,hdl:10411/17,Journeymen's
Boxes,DAT_Journeymens_boxes_WS1_v23.mdb,2014-05-08 10:08:54.489,File
Download - application/octet-stream,ad8496d39061585d1197d8c5384d

**Comment by sekmiller** [comment]
Download tracking (aka Guestbook responses) export has not been implemented yet. When is it on the schedule?

**Comment by eaquigley** [comment]
Passing to QA (@kcondon) to close as this was for 3.6.2.

**Comment by kcondon** [comment]
OK, 4.0 functionality not ready yet but will need to test this case when it is. Closing.
