### ISSUE TITLE
Upgrade Documentation: Dataverse 5.4 Upgrade Instructions Order of Steps Issue

### ISSUE THREAD

**Issue by sgurnick** [IQSS/dataverse#7821]
I am testing the update of our all-in-one Dataverse system, going from version 5.3 to 5.4. I attempted to follow the procedures available on [the GitHub 5.4 release page](https://github.com/IQSS/dataverse/releases/tag/v5.4). However, I quickly ran into an issue that seems to be related to the ordering of the steps. Our instance of Dataverse originally had a 4.X version installed.

Our server has Java 1.8 installed, and version 5.4 requires Java 11. Step 1 of the update instructions says to update java to version 11, which involves removing java 1.8 and then installing Java 11. However, once this is complete Payara can no longer start due to unsupported JVM options. Steps 3 and 4 involve undeploying the existing dataverse application, but since Payara can't start, I'm unable to run these steps.

Step 5 of the instructions provides the necessary steps to add/remove the necessary JVM options to get Payara to start-up using Java 11. If I do what's listed in Step 5 earlier on in the update process, everything works as expected. The order of the steps I used are as follows:

1. Stop Payara, Solr and Postgres
2. Back-up postgres db using pg_dumpall utility
3. Uninstall postgres 9.6
4. Upgrade postgres to 13 - follow instructions here: https://guides.dataverse.org/en/5.4/installation/prerequisites.html#postgresql
5. Restore pg_hba.conf from postgres 9.6 into 13 data directory
6. Restart Postgres
7. Restore postgres back-up using psql utility
8. Upgrade Solr to 8.8.2 - follow instructions here: https://guides.dataverse.org/en/5.4/installation/prerequisites.html#solr
9. Stop Solr
10. Remove Java 1.8 and Upgrade Java to 11 (Step 1 in the [dataverse 5.4 upgrade notes](https://github.com/IQSS/dataverse/releases/tag/v5.4))
11. Start Solr
12. Update Payara jvm configuration parameters for Java 11 in domain.xml (Step 5 in the [dataverse 5.4 upgrade notes](https://github.com/IQSS/dataverse/releases/tag/v5.4))
13. Start Payara
14. Proceed with Step 3 and Step 4 in the [dataverse 5.4 upgrade notes](https://github.com/IQSS/dataverse/releases/tag/v5.4)
15. Proceed with Steps 6, 7, 8, 9 in the [dataverse 5.4 upgrade notes](https://github.com/IQSS/dataverse/releases/tag/v5.4)
16. Perform a full Solr Reindex - follow instructions here: https://guides.dataverse.org/en/latest/admin/solr-search-index.html

These steps result in a successful update to version 5.4.

I was hoping to check-in about this to see if there is something I'm missing that would necessitate this adjustment in the order of operations mentioned in the 5.4 update steps.

Thank you for your help.

(This was also posted in the [Dataverse Google Discussion Group](https://groups.google.com/g/dataverse-community/c/vmTHb-0TxJk/m/33aFkVKiAQAJ))

**Comment by qqmyers** [comment]
Looking at the original steps, I think they assume that Java 1.8 isn't removed and payara is continuing to run with it until it is stopped in step 4 (in which case I think they work). To avoid the issue above (lot's of reasons why people might stop/start as they go through the process)  - step 5 could be moved earlier, or we might just add a note that, if you stop payara after step 1 (installing Java 11), you'll need to perform step 5 (if you had previously updated from glassfish, to be able to restart it.  If step 5 moves forward, it needs to have a stop payara before and a start payara after.

**Comment by pdurbin** [comment]
@sgurnick hi! Are you interested in making a pull request? The file to edit is https://github.com/IQSS/dataverse/blob/develop/doc/release-notes/5.4-release-notes.md

**Comment by sgurnick** [comment]
@pdurbin From my perspective this issue can be closed. This is for an old version of Dataverse that I don't believe anyone would or should attempt to install anymore.

**Comment by pdurbin** [comment]
@sgurnick ok, closing. Thanks!
