### ISSUE TITLE
`dirindex`does not support web browsing

### ISSUE THREAD

**Issue by mankoff** [IQSS/dataverse#7823]
Follow-up on #7084 because that has remained closed even after an issue was raised.

The implementation discussion (and a logical behavior) supports a web browser access to the dirindex, not just `wget`.  See for example https://github.com/IQSS/dataverse/issues/7084#issuecomment-731053846 

But the current implementation does not support a web browser. When I go to https://demo.dataverse.org/api/datasets/24/dirindex I'm given a ".index" to download in firefox, not something that I can view in my browser.

Cc: @landreev

**Comment by djbrooke** [comment]
Thanks @mankoff, we'll take a look. Right now we're focusing on some performance issues but we should be able to get back to this soon. From a process perspective, we don't usually reopen old issues, so a new issue is great. Thanks!

**Comment by djbrooke** [comment]
- likely related to setting the mimetype incorrectly, need to revisit contentdisposition

**Comment by pdurbin** [comment]
@mankoff et al., I just made pull request #7894 to fix this.

**Comment by mankoff** [comment]
I'll test it on demo.dataverse.org as soon as I can...

**Comment by pdurbin** [comment]
@mankoff sounds good. It was just merged. That demo server will be updated after we put out a release (like usual).
