### ISSUE TITLE
Dataverse 5.3 Two Ravens, Data explorer and download RData format errors.

### ISSUE THREAD

**Issue by ipcraiurosario** [IQSS/dataverse#7824]
Hi, hope you guys are doing well,

I'm having troubles with the features that I listed on the issue title, here's what my Dataverse (development environment) shows for each one of those features:

**Two Ravens:** It doesn't work with the new datasets that I've created
![image](https://user-images.githubusercontent.com/53486765/116096404-e398fe00-a66e-11eb-9c26-cce3782ff1c5.png)

**Data explorer:** It doesn't load
![image](https://user-images.githubusercontent.com/53486765/116096702-1c38d780-a66f-11eb-9147-881235ddc084.png)

download RData format of a file: 
![image](https://user-images.githubusercontent.com/53486765/116096839-3a063c80-a66f-11eb-8654-a0f0e4ba3446.png)

I think that the first 2 are related with this being a development server but with the RData one, am not sure what might be wrong. 

Is there a workaround to this?

**Comment by djbrooke** [comment]
Hi @ipcraiurosario - did you take the steps to install R, outlined in the Guides?

https://guides.dataverse.org/en/latest/installation/prerequisites.html#r

**Comment by ipcraiurosario** [comment]
@qqmyers  Hi, yes I did. This is the only message that my log shows:

```
[2021-04-27T13:52:19.849+0000] [Payara 5.2020.6] [SEVERE] [] [edu.harvard.iq.dataverse.rserve] [tid: _ThreadID=66 _ThreadName=http-thread-pool::http-listener-1(3)] [timeMillis: 1619531539849] [levelValue: 1000] [[
  Cannot connect: Connection refused (Connection refused)]]

```

**Comment by ipcraiurosario** [comment]
Closing this issue, I just reinstalled  RData, Data explorer and Two ravens and everything's working fine.
