### ISSUE TITLE
Dataverse 4.9.4 geoconnect

### ISSUE THREAD

**Issue by ipcraiurosario** [IQSS/dataverse#7831]
Hi,

I know that from the 5.3 version of dataverse, geoconnect is not working anymore due to the fact that is not being used by dataverse anymore, however, in the 4.9.4 shouldn't it be working normally?

Here's the thing, I try to configure a new map but when I click on "Submit latitude and longitude columns" I get this error:

![image](https://user-images.githubusercontent.com/53486765/116440932-922b7300-a816-11eb-854d-986fe5d75160.png)

the file has the same format that has worked in the past ... does this means that geoconnect is not working in any version of dataverse?

**Comment by djbrooke** [comment]
Hi @ipcraiurosario - the GeoConnect service at Harvard has been discontinued, so I wouldn't expect this to work unless you were running Geoconnect locally. If you are running it locally, it will be challenging for us to troubleshoot this due to the outdated version. Are you running it locally?

**Comment by ipcraiurosario** [comment]
Hi @djbrooke we're not running it locally, so we should install Geoconnect locally or wait for the next software that will replace geoconnect in the future?

**Comment by djbrooke** [comment]
Hi @ipcraiurosario, thanks. I'd absolutely encourage you to wait instead of trying to work with Geoconnect locally, since support would be very limited. If you're interested in Geospatial Data, feel free to contact me at dannybrooke (at) g.harvard.edu and I'll add you to Geospatial interest group in Slack. I'll close this for now.

**Comment by ipcraiurosario** [comment]
@djbrooke as always, thank you very much
