### ISSUE TITLE
Rename the auxiliary file download API?

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#7850]
Proposal to rename the current form of the API: 
```
/api/access/datafile/{fileId}/metadata/{formatTag}/{formatVersion}
```
to 
```
/api/access/auxiliaryfile/{fileId}/{formatTag}/{formatVersion}
```
Because aux. files do not necessarily have to be "metadata". And in order to avoid potential conflicts with other forms of /api/access/datafile.

**Comment by qqmyers** [comment]
Since the file id there is still the datafile id, perhaps 
/api/access/datafile/{fileId}/auxiliaryfile/{formatTag}/{formatVersion}

or 
/api/access/datafile/{fileId}/aux/{formatTag}/{formatVersion} ?

**Comment by djbrooke** [comment]
Good idea. I don't have strong feelings about what to rename it to, but now's the time.

**Comment by landreev** [comment]
OK, let's drop the "file", but spell "auxiliary" fully:
/api/access/datafile/{fileId}/auxiliary/{formatTag}/{formatVersion}
?

(the code change would be trivial; will just need to carefully reflect it in the docs and the tests)
