### ISSUE TITLE
Create Dataset: Trap MS Word formatting characters from copy and paste.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#787]
A common issue is for users creating studies to copy and paste from Microsoft Word docs into dataset fields such as description. Sometimes, this results in unknown formatting characters being pasted into our forms that later get misinterpreted and results in a variety of bad display behavior: truncated page, unusual characters in the display, etc.

Not sure how much we can do to prevent this but this ticket is a placeholder to address this issue.

**Comment by eaquigley** [comment]
Passing to QA (@kcondon) to restest in 4.0.

**Comment by sbarbosadataverse** [comment]
@kcondon I tested in internal, copied and pasted text from word to description field, specifically used single quote and no character issues.

**Comment by kcondon** [comment]
OK, basic testing showed no issues so closing. Will reopen if we have further customer reports.
