### ISSUE TITLE
Dataset template: authors ordering

### ISSUE THREAD

**Issue by ipcraiurosario** [IQSS/dataverse#7874]
Hi, 

I'm trying to build a dataset template but after I save the template, the order in wich I added the authors doesn't seem to stay that way and if I modify said template, dataverse reoders the list of authors again in another way.

Shouldn't my list of authors stay in the order that I added them?

Thanks in advance!

**Comment by jggautier** [comment]
Just writing to say I agree, I would expect your list of authors to stay in the order that you added them in the template. On Demo Dataverse I was able to apply a template to a dataset and the author order was the same as it was in the template I used.

I can't imagine what the problem could be, but could you share what version of Dataverse you're using?

**Comment by ipcraiurosario** [comment]
@jggautier of course, I have 2 dataverse: one is running with 4.9.4 version and the other with 5.3, both are having the same issue.

**Comment by jggautier** [comment]
Thanks! I'm hoping someone else in the community knows what other information might be helpful to troubleshoot.

**Comment by alejandratenorio** [comment]
Hi all,

Recently a curator reported us the same problem with authors and keywords.  We tested and found this error. We have Dataverse version 4.20. Do @ipcraiurosario still have the same problem?

**Comment by ipcraiurosario** [comment]
Hi Alejandra,

Yes, we still have the same error. We're running Dataverse 5.3.

**Comment by alejandratenorio** [comment]
Hi @jggautier,

This error doesn't always happen. For example, we had a template with some authors, we edited it to add authors among the existing ones and when saving, dataverse we reordered the list of authors in another way.

The same with keywords.

**Comment by jggautier** [comment]
Thanks for the update and for the extra info about which other Dataverse versions this bug is happening in. Is there something in the logs in your Dataverse installations or something related to the browsers we're using that could help us figure out what's going on? This sort of technical investigation will probably soon become beyond me.

**Comment by alejandratenorio** [comment]
@jggautier ,

We have found this problem on Edge, Chrome and Firefox. No errors in the logs only warnings,

**Comment by alejandratenorio** [comment]
@jggautier ,

We have found this problem on Edge, Chrome and Firefox. No errors in the logs only warnings,
![image_2021_08_31T15_46_57_681Z](https://user-images.githubusercontent.com/31973211/131534938-8abb58fe-78b9-4717-afa1-e8f37655f3c2.png)

**Comment by qqmyers** [comment]
FWIW: I haven't dug too deep but I see that DatasetFieldValue has a displayOrder field. My guess would be that that either isn't getting set or isn't getting used for display somehow. That would mean it could be intermittent - looks OK if the order of values returned from the database is accidentally the same as what you wanted.
If this is the case, it might be useful to know if the problem only occurs with templates or also when creating datasets without templates. Beyond that, as long as its fairly easy to reproduce, I'd hand off to someone who can look at the code and the database values and see what's going on.
(I could be wrong about the root problem here, but I suspect that looking at the values in the db would be a good check .)

**Comment by alejandratenorio** [comment]
Hi @qqmyers,

Datasets no have problems, we only found this problem in templates. We are going to look the code and database.

**Comment by alejandratenorio** [comment]
Hi @jggautier, hi @qqmyers ,

I'm Alejandra from CIMMYT, All multiple value fields become unordered in the templates. We have found the problem, tidyUpFields method is executed when a dataset is created/updated but not when a template is created. This method removed empty fields and set their display order. 

![image](https://user-images.githubusercontent.com/31973211/140377843-7f0c2592-a504-4a6c-ad80-976026f62d5b.png)

We did some tests by adding these code lines when Dataverse saves a Template (in the TemplatePage class) and this error is solved. 

We would like to contribute with this fix (we can do a PR), could you look at our code?

**Comment by jggautier** [comment]
Awesome! About reviewing the code, I'll defer to @pdurbin and/or other developers in the community :)

**Comment by alejandratenorio** [comment]
@jggautier, I'll do a PR
