### ISSUE TITLE
Change Dataset owner contact

### ISSUE THREAD

**Issue by dvabad** [IQSS/dataverse#7875]
Hi,

I have several datasets that belong to different people. When I upload these datasets via API, I automatically become the owner in the "Contact Owner" form. Is there any way to change it with another email ( to change the owner of the dataset)?

**Comment by djbrooke** [comment]
Hi @dvabad, looking at the docs here:

https://guides.dataverse.org/en/latest/api/native-api.html#import-a-dataset-into-a-dataverse-collection 

It looks like it can changed in the JSON:

`"typeName": "datasetContact",
            "multiple": true,
            "value": [
              {
                "datasetContactEmail": {
                  "typeName": "datasetContactEmail",
                  "multiple": false,
                  "value": "aprof@mailinator.com",
                  "typeClass": "primitive"`

Hopefully this helps, or at least starts a conversation where more technical members of the community can join the discussion. :)

**Comment by dvabad** [comment]
Hi @djbrooke, thanks for your answer. However, even changing it in JSON, or editing it manually in the interface after the dataset created does not change the contact person - the contact person is always the one who creates the dataset.  So if you upload the dataset for someone else, You will be the contact person, not the real owner of the dataset. There are hundreds of datasets. Maybe someone has an idea for this issue.

**Comment by pdurbin** [comment]
> editing it manually in the interface after the dataset created does not change the contact person

@dvabad do you get the same behavior for a dataset created the normal way? Or only imported datasets? You should definitely be able to update the dataset contact.
