### ISSUE TITLE
Travis CI is going away soonish

### ISSUE THREAD

**Issue by poikilotherm** [IQSS/dataverse#7876]
[Travis CI announced it's shutting down it's free service.](https://docs.travis-ci.com/user/migrate/open-source-repository-migration/#q-what-will-happen-to-travis-ciorg-after-december-31st-2020)

As it's May now, they still announce "soonish" on their page travis-ci.org.

As #7837 and #7839 introduced the first Github Actions for this repo, maybe it's time for a change, moving away from Travis? See also my [comment on #7801](https://github.com/IQSS/dataverse/pull/7801#issuecomment-842238970) about introducing some automated checks / review comments.

**Comment by poikilotherm** [comment]
This is also related to @pkiraly comment about SonarCloud / SonarCube.

https://github.com/IQSS/dataverse/issues/3950#issuecomment-830172719

**Comment by donsizemore** [comment]
@poikilotherm I tinkered with a GitHub action to do this; any interested party is welcome to take it and run with it.

**Comment by pdurbin** [comment]
@poikilotherm I've been playing around with GitHub Actions a little bit at https://github.com/opendp/opendp-documentation/blob/main/.github/workflows/main.yml

**Comment by poikilotherm** [comment]
![grafik](https://user-images.githubusercontent.com/5468333/121015879-c7bf6680-c79b-11eb-855e-872cb9dbc69d.png)

Postponed from end of May to June 15th. Looks like at some point they are going to make a hard cut.

**Comment by poikilotherm** [comment]
Looks like they finally cut the wire.

![20210615_225735.jpg](https://user-images.githubusercontent.com/5468333/122122628-5764b500-ce2d-11eb-8c0c-8b779ebfb16a.jpg)

**Comment by pkiraly** [comment]
In the last days there were possibility to initialize a move from .org to .com. Maybe it is still an option. The description is here: https://docs.travis-ci.com/user/migrate/open-source-repository-migration. It seems however that you will have a limited free credit, and each build costs some credits. I do not see an option to have unlimited credit points for OSS projects.
