### ISSUE TITLE
After 127, paging numbers are showing negative (126, 127, -128, -127)

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#788]
After adding over 1,400 datasets, the "paging" on the front page started showing negative numbers.

e.g. After page 127, the paging goes to -128, -127, etc.  This cycles every 127 pages or so…

+ (count down)				
  + 126, **127, -128**, -127, -126 … 
+ (count up)	
   +-2, **-1, 0, 1**, 2 … 
+ (count down)			
  + 126, **127, -128**, -127, -126 … 
+ (count up)	
   +-2, **-1, 0, 1**, 2 … 

See screen shots:
![root_dataverse](https://cloud.githubusercontent.com/assets/1036060/3755287/48cd463c-1823-11e4-9531-7e1701e696b7.png)

![root_dataverse](https://cloud.githubusercontent.com/assets/1036060/3755279/3eeaface-1823-11e4-86d5-97fbd8dd7470.png)

**Comment by scolapasta** [comment]
For some reason the var attribute of c:foreach can not be used for #s greater than 127. Instead we can use varStatus.index:

See: http://stackoverflow.com/questions/6568983/jsf-core-tag-cforeach-value-overflow-while-iterate

**Comment by kcondon** [comment]
OK, does not happen with 150+ pages, closing.
