### ISSUE TITLE
Display (future) file DOIs in non-published datasets

### ISSUE THREAD

**Issue by lmaylein** [IQSS/dataverse#7887]
Is it possible to display the future DOI for the individual files of datasets that have not yet been published, as is the case with the dataset itself? Or is it only known what the file DOIs will look like when it is published?
It would be nice to be able to print individual file DOIs in text publications before the dataset is published.

**Comment by qqmyers** [comment]
Not currently. FWIW #7334 would support this - it registers file DOIs when the files are first uploaded, but concerns over possible performance issues have it on hold until #7393 is addressed.

**Comment by lmaylein** [comment]
Okay, thanks.
