### ISSUE TITLE
5.5 Installer Makefile: Fails with dependency on removed file, schema_dv_mdb_copies.xml

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#7891]
The 5.5 make file fails with this error:
copying jhove schema file
/bin/cp ../../conf/jhove/jhoveConfig.xsd dvinstall
make: *** No rule to make target `../../conf/solr/8.8.1/schema_dv_mdb_copies.xml', needed by `dvinstall/schema.xml'.  Stop.

This is apparently due to a dependency on the recently removed schema_dv_mdb_copies.xml, see #7865 . This was manually fixed by temporarily adding back the file to produce the 5.5 dvinstall.zip but the dependency needs to be fixed/removed.

**Comment by pdurbin** [comment]
Less critical but on topic is that schema_dv_mdb_copies.xml also appears in the dev guide and the curl command highlighted in blue below from https://guides.dataverse.org/en/5.5/developers/dev-environment.html#install-solr will fail.

<img width="821" alt="Screen Shot 2021-05-20 at 2 17 09 PM" src="https://user-images.githubusercontent.com/21006/119029130-4338af80-b976-11eb-8916-233884a710a7.png">

We might as well fix both in the same pull request, I'm thinking.
