### ISSUE TITLE
Cannot locate "rserve-setup.sh" script in Dataverse V.5.4

### ISSUE THREAD

**Issue by shahab-ab** [IQSS/dataverse#7892]
Hello,

Following the instruction for installing Dataverse v.5.4, unfortunatly we were not able to locate script **rserve-setup.sh**. This is script is mandatory to communicate Dataserve with R. 

https://guides.dataverse.org/en/5.4.1/installation/prerequisites.html#rserve

Would you help us on this issue and provide us the script.

**Comment by djbrooke** [comment]
Hi @shahab-ab - I believe the script can be found here:

https://github.com/IQSS/dataverse/tree/v5.4/scripts/r/rserve

Is this what you are looking for?

**Comment by shahab-ab** [comment]
Thank you so much.

**Comment by djbrooke** [comment]
Hi @shahab-ab happy to help. I'll close this issue but it looks like we can do a better job with the documentation for this. #7893 was created to track the documentation improvement and we'll make any changes as part of that issue.
