### ISSUE TITLE
Unable to publish draft dataset

### ISSUE THREAD

**Issue by kishanlokappa** [IQSS/dataverse#7899]
I Created Dataset Using the below endpoint 

POST - http://ServerURL/api/dataverses/kishan/datasets   , Along with dataset-finch1.json which worked successfully creating Draft Dataset and returning JSON with id and Doi

But I'm unable to publish the dataset using below endpoint:

curl -H "X-Dataverse-key: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx" -X POST "https://demo.dataverse.org/api/datasets/:persistentId/actions/:publish?persistentId=doi:10.5072/FK2/J8SJZB&type=major"

I'm getting error in response saying below:

{
    "status": "ERROR",
    "code": 404,
    "message": "API endpoint does not exist on this server. Please check your code for typos, or consult our API guide at http://guides.dataverse.org.",
    "requestUrl": "http://ServerURL/api/v1/datasets/31/actions/?persistentId=doi:10.5072/FK2/YXL1DQ&type=major",
    "requestMethod": "POST"
}

is there anything wrong, any help would be great, Thanks?

**Comment by pdurbin** [comment]
@kishanlokappa hi, are you still having trouble?
