### ISSUE TITLE
incorrect link in v5.0

### ISSUE THREAD

**Issue by youssefOuahalou** [IQSS/dataverse#7902]
Hello
There is a small missing link in version 5.0 when reloading astrophysics.tsv
<s>wget https://github.com/IQSS/dataverse/releases/download/5.0/astrophysics.tsv</s>
==> https://github.com/IQSS/dataverse/releases/download/v5.0/astrophysics.tsv 
![GithubV5](https://user-images.githubusercontent.com/46802308/119579608-10037f80-bdbf-11eb-9007-50aa42b17aa1.PNG)

**Comment by pdurbin** [comment]
@youssefOuahalou thanks for letting us know! Are you interested in creating a pull request to fix it? If so the file to edit is https://github.com/IQSS/dataverse/blob/develop/doc/release-notes/5.0-release-notes.md

**Comment by youssefOuahalou** [comment]
Yes of course 👍

**Comment by youssefOuahalou** [comment]
https://github.com/IQSS/dataverse/commit/3475bf9f6590091af85f437cfba11ff805c99a19

**Comment by pdurbin** [comment]
@youssefOuahalou thanks! The last step is to click "Create pull request" (and fill out the form) at https://github.com/IQSS/dataverse/compare/develop...youssefOuahalou:patch-1
