### ISSUE TITLE
Allow adding elements to html header

### ISSUE THREAD

**Issue by dmelichar** [IQSS/dataverse#7921]
At the moment it is not possible to add html elements to `<head>`. Anything added through :HeaderCustomizationFile is added to `<body>`. 

Being able to add stuff to `<head>` would be nice, e.g. for custom javascript or css files.

**Comment by pdurbin** [comment]
You're right. :HeaderCustomizationFile is included using the following in dataverse_header.xhtml

```
<o:resourceInclude path="/CustomizationFilesServlet?customFileType=header"
```

And dataverse_header.xhtml itself is included in dataverse_template.xhtml within the `<body>` tag.

So the fix would be to add a new `o:resourceInclude` in the `<head>` section of dataverse_template.xhtml.

**Comment by dmelichar** [comment]
Thanks, that works!
