### ISSUE TITLE
no translation for subfield with controlled vocabulary 

### ISSUE THREAD

**Issue by tcoupin** [IQSS/dataverse#7922]
When I change display language, fields with controlled vocabulary are translated, but not the subfield with controlled vocabulary.

English version:
![image](https://user-images.githubusercontent.com/7457386/120842289-cc520800-c56c-11eb-8317-364ca0dc37f7.png)

French version:
<img width="723" alt="Capture d’écran 2021-06-04 à 19 38 47" src="https://user-images.githubusercontent.com/7457386/120842485-09b69580-c56d-11eb-8d72-3abf7a867386.png">

**Comment by juancorr** [comment]
Hi Thibault,

  The citation.properties file is not translated to German
https://github.com/IQSS/dataverse-docker/tree/master/dataversedock/dataverse-property-files/de-AT,
but it is translated to French
https://github.com/GlobalDataverseCommunityConsortium/dataverse-language-packs/tree/develop/fr_CA
.

  Perhaps you could:
  - Contact with AUSSDA (http://aussda.at/). They have translated dataverse
to German
  - Open an issue in the
https://github.com/GlobalDataverseCommunityConsortium/dataverse-language-packs
with or without a translation for this file.

  Bests,

Juan Corrales

**Comment by tcoupin** [comment]
Hi Juan,

When I edit dataset, country are translated in french.
I push #7923 with a fix
