### ISSUE TITLE
Please add punctuation to standard deaccession reasons.

### ISSUE THREAD

**Issue by tlchristian** [IQSS/dataverse#7936]
Because of how Dataverse assembles information from the Deaccession Dataset form (reason for deaccession, additional information about the reason, alternative URL) the resulting Deaccession Reason information that appears on the landing page of deaccessioned datasets does not read correctly, like so:

<img width="865" alt="2021-06-09_11-23-59" src="https://user-images.githubusercontent.com/6351715/121384042-e9445d80-c915-11eb-90a5-8e584cefc5cf.png">

Please add punctuation to the standard deaccession reasons as an easy fix for this.

**Comment by pdurbin** [comment]
@tlchristian good catch. It looks like the bundle entries are here:

https://github.com/IQSS/dataverse/blob/v5.5/src/main/java/propertyFiles/Bundle.properties#L1775
