### ISSUE TITLE
Feature Request: Authority Control on Names

### ISSUE THREAD

**Issue by steeleworthy** [IQSS/dataverse#7937]
**Feature Request:  Authority Control on Names**

Apologies if this has been discussed and is open/closed.

As DV grows in usage (datasets, users, instances), we are encountering more and more issues with authority control around author names and institution names.   I appreciate the complexity of solving this problem, but it would be great to see it discussed some. I'm going to use the example of author names, but the issue is present with organizations, too.

_Problem:_ inconsistent use of names affect search, facets, and interoperability
A Fix: authority control, either inside DV or against a PID (e.g., ORCID)

_Example of Problem: (See screenshot below for visual examples)_
Researchers will either upload data or have it curated.  Sometimes, the usage of names will slip. Our repository has several examples:

- Middle initials may be included or excluded (See: [Connon](https://dataverse.scholarsportal.info/dataverse/sp/?q=authorName%3AConnon) in facets
- Diacritics/accents may be included or excluded (See: [Devoie](https://dataverse.scholarsportal.info/dataverse/sp/?q=authorName%3ADevoie) in facets)
- Periods may have inadvertently been forgotten (See: [Baltzer](https://dataverse.scholarsportal.info/dataverse/sp/?q=authorName%3ABaltzer) in facets)

The easy fix is to change the metadata and improve our practices going forward.  While practices have been improved over the years, we don't want to change the metadata and effectively version-jump a dataset, even by a decimal, over an initial.  (See examples above)

I propose that other pathways be considered:

_1. "very Minor" ("micro?") changes to metadata that will not affect a version change?_  If people were on board, sure.  but it doesn't solve the authority control issue.
_2. Authority control in the system._   Can there be a way for DV to work to identify existing values in the name fields in its DB (within the local instance) to help people see if a matching/similar name exists?  _Even better:_  Linking in the background of name variants, which will solve this problem as well as others (e.g, name changes).
_3. Authority control according to a PID._  There are so many PIDs out there, but making this happen would be a dream come true. 

Going forward, I know we could make a policy at our local institution that says a researcher is required to have an ORCID (for example) and that the name in this PID is the name we'll put into the record.  But that doesn't help DV's that have an open deposit policy.   Ideally, this solution here should have a technical component as well as a policy component.

Thank you!  xoxo.

![image](https://user-images.githubusercontent.com/8768756/121404155-ab513480-c929-11eb-8f6b-b858ee90c4b0.png)

**Comment by steeleworthy** [comment]
Thank you, @qqmyers !

**Comment by pdurbin** [comment]
I believe @Kris-LIBIS has made some good progress on this using the new external vocabulary feature (#7946) in 5.7. Here are some screenshots from the thread he started at https://groups.google.com/g/dataverse-community/c/eZ0m0bVsjpc/m/OjBvB8TsFQAJ

<img width="834" alt="Screen Shot 2022-02-01 at 11 38 33 AM" src="https://user-images.githubusercontent.com/21006/152011671-b35f36f7-79a6-41a3-9026-3ab22b8cfe38.png">

It's funny. I wasn't 100% sure this was possible without modifying the citation.tsv metadata block. But if it's working, great! Maybe it's time to document this!

Adding @4tikhonov to the conversation as well.

**Comment by 4tikhonov** [comment]
@pdurbin, it's just a beginning of something big, I was always convinced that's possible and people will start to contribute stuff. :) Congrats @Kris-LIBIS and KU Leuven, great job! Can you share your solution with others?

**Comment by steeleworthy** [comment]
Developers and Issue trackers are the best.  Thank you for keeping up with this feature request.

**Comment by Kris-LIBIS** [comment]
FYI, I have created a [PR](https://github.com/gdcc/dataverse-external-vocab-support/pull/9) in the external-vocabularies-support repository with some tech info on our implementation.

**Comment by 4tikhonov** [comment]
Thanks @Kris-LIBIS, looks good! Just for your and others information: I've archived in Zenodo the [current version](https://zenodo.org/record/5845540) of the proposal for external CVs implementation but we can organize a new session if more ideas are coming on the vocabularies. It's a hot topic in the most of our projects.

**Comment by pdurbin** [comment]
@steeleworthy have you had a chance to look a the PR @Kris-LIBIS mentioned? It's been merged and has ORCID examples. This one:

- https://github.com/gdcc/dataverse-external-vocab-support/pull/9

**Comment by pdurbin** [comment]
@steeleworthy here are the docs: https://guides.dataverse.org/en/6.0/admin/metadatacustomization.html#using-external-vocabulary-services

If you have any questions, please let us know!
