### ISSUE TITLE
Dataverse cannot connect to S3 storage Endpoint 

### ISSUE THREAD

**Issue by shahab-ab** [IQSS/dataverse#7938]
Hello dear Dataverse team,
Here is the explanation of our issue regarding connection to a custom S3 storage endpoint:
 

1. With all S3 <jvm-options> configured together with credentials under ~/.aws/ to use custom S3 endpoint according to the  instructions of Multi-Store configurations instructions on [Amazon S3 Storage (or Compatible)](https://guides.dataverse.org/en/latest/installation/config.html#id80) (in our case ECS), Dataverse v5.4 cannot instantiate a S3 client and establish a connection to the target endpoint URL as can be seen from the screenshot of server.log below:

![log](https://user-images.githubusercontent.com/7823110/121503633-89b38400-c9e1-11eb-80c1-b551d75633c9.JPG)
#### _It's worth mentioning that using AWS CLI on the same Dataverse server with an exact credentials & config, a connection to the same endpoint can be successfully initiated and contents of the given bucket can be normally accessed._

2. The following happens as a result of 1:
Even though the S3 storage is added as a new storage option on the frontend side, the whole webpage hangs and is grayed out right after submitting Create button while creating a new Dataverse collection as it tries to upload a given file to its assigned storage and finally runs into the "Intrernal server Error" as the attached screeshot below:

![grafik](https://user-images.githubusercontent.com/7823110/121504606-6d641700-c9e2-11eb-9958-affa4264dcb4.png)

**Comment by qqmyers** [comment]
Is it possible that Dataverse is being run as a different user than the one you manually test the AWS client with? If not - the AmazonClientException you’re getting comes directly from the Amazon library so the issue would have to be something either with:
the credentials location/permissions/content, 
the jvm-options for your store such as custom-endpoint-url, custom-endpoint-region or profile, 
some jvm-option required for ECS, or 
some incompatibility with ECS in the version of the AWS library in Dataverse.

**Comment by shahab-ab** [comment]
Hello @qqmyers,
Thank you for your answer.
All of operation are done under a specific username "dataverse".
AWS runs with the same user with the same credentials without any problem. 
I will check them again and this time with Ceph S3 and give you feedback.

**Comment by shahab-ab** [comment]
The following jvm-options should be added to domain.xml:

<jvm-options>-Ddataverse.files.s3.custom-endpoint-region=</jvm-options>
<jvm-options>-Ddataverse.files.s3.path-style-access=true</jvm-options>

AWS library has 2 bucket addressing style: 
-Virtual or subdomain:  **bucket**.endpoint-url
-path:  endpoint-url/**bucket**
-auto
 In our case it shoud be adjusted on path-style

It should then work. Assuming that all permissions under domain1 are set to the user running Dataverse.

this link might be helpful for further reading:
https://groups.google.com/g/dataverse-community/c/fbl96kea2g8

**Comment by djbrooke** [comment]
HI @shahab-ab - from my reading, it looks like you were able to get this set up correctly? I'll go ahead and close this out, but feel free to comment if this is not correct.
