### ISSUE TITLE
Files uploaded via API are public

### ISSUE THREAD

**Issue by dvabad** [IQSS/dataverse#7939]
Hi, 
I uploaded a bunch of data files to different datasets in dataverse via Native API.  How can I make them private by default? When I publish datasets the files become public (literally for everyone). To make each file private is not a good idea for thousands of files. Is there any way to make it private (restricted) while uploading them?

**Comment by pdurbin** [comment]
@dvabad hi, does my suggestion help? Are you still having trouble?

**Comment by pdurbin** [comment]
Related:

- #6158
