### ISSUE TITLE
Multi-level approval - I need help on how to implement multi level approval of data set in dataverse

### ISSUE THREAD

**Issue by subrush** [IQSS/dataverse#7943]
Thank you for contributing an issue to the Dataverse Project! If this is a bug report, please let us know when the issue occurs, which page it occurs on, to whom it occurs, and which version of Dataverse you're using. If this is a feature request, please let us know what you'd like to see and give us some context - what kind of user is the feature intended for, the relevant use cases, and what inspired the request? No matter the issue, screenshots are always welcome.

**Comment by djbrooke** [comment]
Hi @subrush - can you please provide more information about your request? Thank you!

**Comment by pdurbin** [comment]
@subrush are you still interested in this? Is there more detail you can provide? Thanks.
