### ISSUE TITLE
Add support for handle service with authentication NOT in default handle

### ISSUE THREAD

**Issue by cookie33** [IQSS/dataverse#7949]
When registering a handle for a dataset the bean will use a special 'admin' handle to communicate with the service and that is now:
* '"0.NA/" + handlePrefix' for a global resolvable handle service.
* 'handlePrefix + "/ADMIN"' for in independent handle service.

This, however, does not work when the handle service is configured to run as global handle service but the public key is not in the handle 0.NA/handlePrefix. in this case this 'admin' handle could for instance be 'handlePrefix + "/USER01"'.

In order to also support the handle service we could add a new optional setting:
‘:HandleAuthHandle’ =  ’prefix/suffix’ ! handle to use when authenticating

Then use the new setting to construct this 'admin' or 'auth' handle in:
src/main/java/edu/harvard/iq/dataverse/HandlenetServiceBean.java

See also #5587 to have an example how the independent was implemented

**Comment by djbrooke** [comment]
Hi @cookie33 - would you be interested in making a pull request for this functionality? If so, are you just seeking some guidance for implementation?

**Comment by cookie33** [comment]
We can try to make a pull request. But at our site we are a handle provider/hoster. We are not a Dataverse user. So we have no ways of properly testing it.
We will try to make a pull request in a few days.
One of our customers is using Dataverse and was trying to use the handle service.

**Comment by cookie33** [comment]
We created a pull request. But we do not run Dataverse. So we can not test it.

**Comment by vaidasmo** [comment]
Since I am the "interested party", please let me know when we could test it.
Greetings!
