### ISSUE TITLE
Maven Unit Tests failing (new Coveralls check in GitHub Actions)

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#7977]
Ever since merging pull request #7944 commits are showing a failure of the "Maven Unit Tests" check like this:

<img width="1358" alt="Screen Shot 2021-06-29 at 10 06 49 AM" src="https://user-images.githubusercontent.com/21006/123812034-c2989780-d8c1-11eb-805a-c6f073c30ef6.png">

If you did into the error, it says:

> Error:  Failed to execute goal org.eluder.coveralls:coveralls-maven-plugin:4.3.0:report (default-cli) on project dataverse: Processing of input or output data failed: Report submission to Coveralls API failed with HTTP status 422: Unprocessable Entity (Couldn't find a repository matching this job.) -> [Help 1]

Here's a screenshot from https://github.com/IQSS/dataverse/runs/2941612189 for more context:

@poikilotherm has his eye on these potential fixes:

- https://github.com/trautonen/coveralls-maven-plugin/issues/136#issuecomment-797322126
- https://github.com/common-workflow-language/cwlviewer/blob/main/.github/workflows/ci-build.yml

As fate should have it, old friend @michbarsinai ran into similar trouble a while back! 😄 https://stackoverflow.com/questions/41433800/travis-ci-org-project-cannot-submit-code-coverage-report-to-coveralls-io

**Comment by poikilotherm** [comment]
I will delete the demo commits now. 

Please find results here:
- Working coverage: https://github.com/IQSS/dataverse/pull/7981/checks?sha=2bcd9a0791bab733ce0a2be89dc2b98b92b7c141
- Working coverage, working cache restore: https://github.com/IQSS/dataverse/pull/7981/checks?sha=7ec91f89eb6a15239002a3b26c38f93a088569d8

**Comment by michbarsinai** [comment]
Ah, memories of late night CI debugging. These were the times.
