### ISSUE TITLE
In Permission.java enum, specify which DvObject(s) the permission applies to

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#799]
For example, the `AddDataverse` permission is not valid for a Dataset object. For each permission, we will specify the DvObject(s) where the permission applies.

This will allow us to provide a shorter list of permissions when users are configuring roles for the DvObject in question.

**Comment by pdurbin** [comment]
@esotiri you asked how to test this. I guess I would suggested using https://github.com/IQSS/dataverse/blob/master/scripts/api/data/role-dvContributor.json or some other role as a starting point and changing the JSON to try assign an invalid permission to a dvobject.

**Comment by esotiri** [comment]
Gustavo recommended testing around permissions as a way to test this.

**Comment by scolapasta** [comment]
To be clear, it is not invalid to have a role with EditDataverse assigned to a Dataset. What is true is that that permission is not relevant to the dataset so is effectively meaningless.

As an example, DownloadFile is only for DataFile. But you can assign the FileDownloader role at a dataset (or dataverse) and that allows that user to download all files.

**Comment by esotiri** [comment]
related issue https://github.com/IQSS/dataverse/issues/1369

**Comment by esotiri** [comment]
overall look ok, resolving.
