### ISSUE TITLE
Odd looking selection dropdown on extra metadata block

### ISSUE THREAD

**Issue by PaulBoon** [IQSS/dataverse#7999]
When adding a dataset on a verse with extra metadata enabled, like the 'Journal Metadata', 
the dropdown selection on that input form looks 'odd' in that it seems that the selected value has an offset within its component revealing a 'button' like background. 
See top left of the 'addendum' text (non-blue). 
 
![Screenshot 2021-07-14 at 17 03 36](https://user-images.githubusercontent.com/2151103/125645785-4c0e67f6-230c-40ee-bcc2-30ec0747db22.png)

This was also visible for some of our custom metadata blocks, so it seems not specific for the 'Journal Metadata', but it is not visible on the citation block. 

We discovered this with version 5.5, but it might be there in previous versions like 5.4, but we did not test it yet.

**Comment by PaulBoon** [comment]
If I use developer tools to disable `padding: 6px 12px;` in `.form-control` it is corrected it seems.

**Comment by qqmyers** [comment]
I think this duplicates #7954 / #7955? - that's been merged and will be in 5.6.

**Comment by djbrooke** [comment]
Thanks @qqmyers @PaulBoon. I'll close this as a duplicate, feel free to comment if this is incorrect.
