### ISSUE TITLE
Performance: v4.0 homepage load time is significantly outside of the 1s target on demo an intermittently varies widely.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#800]
This ticket focuses on homepage performance for v4.0. Recently there was an email thread discussing various performance tools and when applying them to demo, showed issues.

Most notably, http://www.webpagetest.org showed between 4 and 16 seconds page complete on Saturday, 8/4. First byte was 1.3s, page complete was 4.5s, some .js resources took 1s+.

Some recommendations to fix here:
http://developers.google.com/speed/pagespeed/insights/?url=dataverse-demo.iq.harvard.edu 

I'm pasting the thread here:

[Kevin]
So, what's the analysis?

I ran it and saw ~4.5s, though my human perception was faster since it is not based on page complete but initial render. Fyi, production showed 6.6s and 4s.

There are 3 things that we can pay attention to:
the high level score card at the top, indicating general areas to adjust: keep alives, compression, etc.
first byte response, which indicates backend processing such as in page init method that we had fixed in prod recently,
page complete, which takes into account all content and depending on render logic, can hold up display of page.

So, for
1. high level settings
we can enable keep alives though that should not affect speed on a fast network
we can enable compression, we had done that in production and did not see a major improvement since we don't send a lot of bytes on page load
we can enable caching of static content. this might help.

2. first byte
it showed 1.3s on my test and that seems slow. I'm wondering how much the new featured dvs is adding to this time. we could disable and test again unless it is always in init. maybe someone can profile this page and check the init method?

3. page complete
I saw two or three 1s+ page element downloads, a primefaces,js, a jquery.js, and a bootstrap.js. Not sure what to do about this or what they have to do with. Also, we can try to understand whether we can render parts of the page without page complete like in the old days ;)

Last, there seems to be large variations i measurements. That is not good. We need to get a handle on how variable this is.

Anyone else have thoughts or ideas?

________________________________________
Sent: Saturday, August 02, 2014 7:09 AM
Subject: [dataverse] Performance, WebPageTest, was Re:  Fwd: PageSpeed for mobile and desktop

Mike, I'm not sure why webpagetest.org wasn't on the list of resources
for the performance ticket (I must have missed it) but I just added
it: https://github.com/IQSS/dataverse/issues/181

I just heard about it at
http://shoptalkshow.com/episodes/124-rob-dodson/ during an ad read for
SpeedCurve and their about page at http://speedcurve.com/about/ says
"The plan is simple... Build a beautiful UI on top of the open source
powerhouse that is WebPagetest."

So yeah, it's open source. Neat! https://github.com/WPO-Foundation/webpagetest

Anyway, I ran a test on demo last night and it was (unfortunately)
much slower that the test you ran at
http://www.webpagetest.org/result/140516_A8_DC5/

Here's the one I ran (16 seconds to load the home page):
http://www.webpagetest.org/result/140802_CQ_1ZV/

Screenshots attached.

Phil

**Comment by kcondon** [comment]
Not sure what to do with this ticket. We know there are page load performance issues with fully migrated content. Demo is showing 4-5s page load times from my home machine. The above notes are from a google web test tool that give developer recommendations on how to improve performance. 

So, I'm passing this ticket back to dev to act on.

**Comment by mcrosas** [comment]
I moved this issue to Beta 15 and assigned it to @scolapasta 

Performance to a dataverse page needs to be improved to be around 1s in average, before we can release 4.0.

**Comment by scolapasta** [comment]
from issue #1735:

The Search/Browse Cards generate a high number of queries. File Cards, in particular, appear to create in the neighborhood of 500 queries each.

A listing of queries for 18 dataverses, 3 datasets, 9 files is available on google drive:

https://drive.google.com/a/harvard.edu/folderview?id=0B4VvItDJwfehemRYN0ktVFJnRzA&usp=sharing
The query list is related to the screenshot below:

![3e0adef8-cf02-11e4-9d35-25c0400c6438](https://cloud.githubusercontent.com/assets/4268292/6833090/d0746e92-d300-11e4-9812-2c5abea20377.png)

**Comment by scolapasta** [comment]
Many improvements made, I think performance may finally be ready for release.
