### ISSUE TITLE
Problem upgrading to v5.5 due to null values in the authenticateduser table

### ISSUE THREAD

**Issue by nightowlaz** [IQSS/dataverse#8004]
Hello, was asked to submit this as an issue. I was trying to upgrade from v5.4.1 to v5.5 and the upgrade would not complete. Jim M noticed an error in our server log "Message    : ERROR: column "deactivated" contains null values" and suggested that I first run the query "UPDATE authenticateduser SET deactivated = false WHERE deactivated IS NULL;" as it appeared there were null values in the authenticateduser table in the "authenticated" field causing the deploy of 5.5 war file to fail. 

Jim thought this could possible occur if at any time in the past we had run v5.2 code with a v5.3 database. I don't believe that we did that, however, we did run v5.3 code with a v5.4 database. When I tried to upgrade to v5.4 dataverse, I ran into issues and had to restore the volume in aws ... however the deploy HAD completed (had an issue with solr) .. so I believe we were running v5.3 code with a v5.4 database for a while, if it helps.

**Comment by qqmyers** [comment]
If others see this, we might want to add to the 5.5 release notes. (5.3 changes all existing nulls to false, so if a null exists when 5.5 is installed, there is probably some way to create them in 5.3 or 5.4 and the 'solution' is to run the query above again before installing 5.5 which adds a non-null constraint in the db). If it's a one-off issue, no action is needed.

**Comment by pdurbin** [comment]
@nightowlaz are you all set? I see you're on the latest, 5.11.1. Thanks.

**Comment by nightowlaz** [comment]
Yes, all is well so this can be closed.
