### ISSUE TITLE
Performance: Saving browse options is slow

### ISSUE THREAD

**Issue by esotiri** [IQSS/dataverse#801]
Edit Browse dateverse options: 
Selecting display "Featured Dataverses" giving 3.4 seconds on saving on dvn-build (all dataverses), according to firebug.

**Comment by scolapasta** [comment]
@kcondon could you retest this one?

**Comment by posixeleni** [comment]
Tested on Chrome and it is now working much faster than previously tested. I notice no lag time when setting up and saving featured dataverses. Closing.
