### ISSUE TITLE
Jenkins Tests Failing 

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#8010]
After a long run of success, it appears we're seeing some failing tests with the last few merges to dev:

- https://jenkins.dataverse.org/job/IQSS-dataverse-develop/843
- https://jenkins.dataverse.org/job/IQSS-dataverse-develop/842

**Comment by donsizemore** [comment]
These should be fixed: https://github.com/GlobalDataverseCommunityConsortium/dataverse-ansible/commit/8c52112e05800cb335c2d383a99484143358fce9
<img width="453" alt="Screen Shot 2021-07-21 at 15 19 33" src="https://user-images.githubusercontent.com/12831666/126547366-9c1a0956-70dc-4f26-b297-ff56c1ea7af2.png">
Vote to close.

**Comment by djbrooke** [comment]
Thanks @donsizemore ! Just as you suspected! I'll close this and we'll keep an eye on the next run.
