### ISSUE TITLE
Batch Import: in v3.6 utility, seems not thread safe; weird errors can happen with large imports. 

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#803]
Found during import of antislavery petitions.
Several symptoms:  the set was imported twice for double the number of studies, or 90% were imported and the rest failed with the error: java.nio.channels.ClosedByInterruptException, or the studies were imported but were not fully indexed.

Importing in batches of 200-300 works. 

Recording here to review for when we implement in v4.0.

OK, some clarification on the doubling:
It seems browser-related. Small sets complete and update the UI with a success message. Sets of 200+ don't always update UI on complete and seems like the browser may resubmit request due to timeout or some such since if I close browser immediately after clicking batch import, this does not happen.

Also, index does not reliably happen at the end of large batch jobs and needs to be run manually or wait for nightly index.

**Comment by scolapasta** [comment]
We don't currently have any batch imports through UI, it should all be through APIs, and should work fine if called via curl. There may be issues were the browser will recall an api call if it takes too ling but I'm not sure what we can do on our side, besdies not run though the browser.

**Comment by kcondon** [comment]
This does not seem relevant to v4.0 but we will keep an eye on it during migration.

Closing
