### ISSUE TITLE
5.6 release notes addendum

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#8048]
I've discovered a bug in Payara-5.2021.5: any change to its logging configuration seems to wipe out the logging.properties file. Existing Dataverse installations which are upgrading to 5.6 won't see this bug, but any new installation likely will, as this bug seems to be triggered during the Dataverse installation routine. (It is also easily triggered without Dataverse, and has been reported to the Payara project).

As a courtesy to any new installation, it might be nice to make a note of this bug in the 5.6 release notes, as the default-logging.properties file is 29 lines shorter than the stock Payara logging.properties, which adds the following:

```
> javax.enterprise.resource.corba.level=INFO
> javax.enterprise.resource.jta.level=INFO
> javax.enterprise.system.webservices.saaj.level=INFO
> javax.enterprise.system.container.ejb.level=INFO
> javax.enterprise.system.container.ejb.mdb.level=INFO
> javax.enterprise.resource.javamail.level=INFO
> javax.enterprise.system.webservices.rpc.level=INFO
> javax.enterprise.system.container.web.level=INFO
> javax.enterprise.resource.jms.level=INFO
> javax.enterprise.system.webservices.registry.level=INFO
> javax.enterprise.resource.webcontainer.jsf.application.level=INFO
> javax.enterprise.resource.webcontainer.jsf.resource.level=INFO
> javax.enterprise.resource.webcontainer.jsf.config.level=INFO
> javax.enterprise.resource.webcontainer.jsf.context.level=INFO
> javax.enterprise.resource.webcontainer.jsf.facelets.level=INFO
> javax.enterprise.resource.webcontainer.jsf.lifecycle.level=INFO
> javax.enterprise.resource.webcontainer.jsf.managedbean.level=INFO
> javax.enterprise.resource.webcontainer.jsf.renderkit.level=INFO
> javax.enterprise.resource.webcontainer.jsf.taglib.level=INFO
> javax.enterprise.resource.webcontainer.jsf.timing.level=INFO
> javax.org.glassfish.persistence.level=INFO
> javax.enterprise.system.tools.backup.level=INFO
> javax.mail.level=INFO
> org.glassfish.admingui.level=INFO
> org.glassfish.naming.level=INFO
> org.eclipse.persistence.session.level=INFO
> javax.enterprise.system.tools.deployment.dol.level=WARNING
> javax.enterprise.system.tools.deployment.common.level=WARNING
```

The bug will cause Payara to attempt to update its logging settings approximately twice a second, which will cause server.log to grow unnecessarily, and the absence of a proper logging configuration will cause Payara to dump several thousand WELD INFO entries about `orig.edu.harvard.iqss` on service launch.

Since Payara's logging.properties and default-logging.properties files don't match, I'm attaching Payara's distributed logging.properties to this issue. Perhaps we can explain this in the 5.6 release notes, and offer the current default properties file as an artifact of this release. I had to give it a .txt extension to attach it here: [logging.properties.txt](https://github.com/IQSS/dataverse/files/6934934/logging.properties.txt)

**Comment by poikilotherm** [comment]
This relates to future updates to some degree, as we still require Payara 5.2021.5 during install and most people stick with that. #8064
