### ISSUE TITLE
Header displayed on custom home page

### ISSUE THREAD

**Issue by tcoupin** [IQSS/dataverse#8058]
On my 4.20 installation, when I set a custom home page, the dataverse's header is not displayed on root page (path /).
When I go to the root dataverse's details page (path /dataverse/root), header is displayed.

But on 5.5, header is displayed on root page and on the root dataverse's details page.

I found https://github.com/IQSS/dataverse/blob/develop/src/main/webapp/dataverse_homepage.xhtml#L19 so I'm gessing it's bug, not a feature change.

**Comment by pdurbin** [comment]
@tcoupin this is just a guess but could this have something to do with the :DisableRootDataverseTheme setting? https://guides.dataverse.org/en/5.5/installation/config.html#disablerootdataversetheme

Also, if you are able to add some screenshots, it would be appreciated.

**Comment by tcoupin** [comment]
Hi @pdurbin 
I thought the same as you at the beginning but I do not change this setting.

I maked some tests:

### Version 4.20

Disablerootdataversetheme  | true | false or undefined
------------| --- | --- 
Header present on `/` | ❌ | ❌ 
Header present on `/dataverse/root` | ❌ | ✅ 



### Version 5.5

Disablerootdataversetheme  | true | false or undefined
------------| --- | --- 
Header present on `/` | ❌ | ✅  
Header present on `/dataverse/root` | ❌ | ✅

**Comment by pdurbin** [comment]
@tcoupin have you upgraded your 4.20 installation yet? 😄 Are you all set?
