### ISSUE TITLE
Expired SSL certs error messages in server log for Payara

### ISSUE THREAD

**Issue by nightowlaz** [IQSS/dataverse#8059]
Hi there, I noticed that we are getting a message about expired SSL certs for Payara/Java in our dataverse logs. Phil suggested that I put in an issue regarding this. It doesn't seem to affect normal dataverse processing, but we are also having an issue with certs when trying to add other s3 compatible stores, so wondering if it could be related. Attaching the thread in the log where the expired certs messages appear.
[dataverse_expired_certs.txt](https://github.com/IQSS/dataverse/files/6957069/dataverse_expired_certs.txt)

**Comment by pdurbin** [comment]
@nightowlaz thanks for opening this issue. As I [mentioned][] in chat, Payara has some docs on expired certs: https://docs.payara.fish/enterprise/docs/documentation/payara-server/server-configuration/ssl-certificates.html#cetificate-expiration

[mentioned]: https://matrix.to/#/!AmypvmJtUjBesRrnLM:matrix.org/$j2s2oOeOHSRf48B5mk57YKhpvNYN2SaEqUB1scf-r88?via=matrix.org&via=bertuch.name

**Comment by nightowlaz** [comment]
I went into asadmin interactive and found all of the commands available, and those mentioned in the docs regarding certs don't seem to be available, namely the ones related to adding or removing certs from the keystore

![add-commands](https://user-images.githubusercontent.com/22484650/128826740-a691bfc6-6589-4d08-be25-d29d67550a68.JPG)
![remove-commands](https://user-images.githubusercontent.com/22484650/128826750-857db93e-d805-4eb5-b3ee-48589bd960bf.JPG)

**Comment by pdurbin** [comment]
@nightowlaz does upgrading to a newer version of Payara help? We're strongly recommending such an upgrade in 5.12.

**Comment by qqmyers** [comment]
FWIW: The default domain in a new payara instance should have a newer cacerts file - copying that to the Dataverse domain when you transfer (remembering to add any custom certs you may have added to your existing cacerts file) should help.

**Comment by nightowlaz** [comment]
Yes we have done that. This can be closed. Thanks!
