### ISSUE TITLE
Citation Block:  Citation.properties missing several keys, results in create dataset reporting several log errors.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#8065]
Update: read the bottom post by @qqmyers regarding mismatch between citation tsv and citation.properties file. It appears that a relatively old update to that block did not also update the citation.properties file with the corresponding keys so that creating a dataset logs several bundle errors but otherwise appears to function. This was reveal by increased logging in a recent branch.

When creating a new dataset in 5.6+ (5.7?), there are several log errors but the dataset is created successfully. This does not happen in 5.6.

[2021-08-18T13:47:39.043+0000] [Payara 5.2021.5] [WARNING] [] [edu.harvard.iq.dataverse.ControlledVocabularyValue] [tid: _ThreadID=93 _ThreadName=http-thread-pool::jk-connector(2)] [timeMillis: 1629294459043] [levelValue: 900] [[
  Error findingcontrolledvocabulary.authorIdentifierScheme.dai in defaultLang : Can't find resource for bundle java.util.PropertyResourceBundle, key controlledvocabulary.authorIdentifierScheme.dai]]

[2021-08-18T13:47:39.043+0000] [Payara 5.2021.5] [WARNING] [] [edu.harvard.iq.dataverse.ControlledVocabularyValue] [tid: _ThreadID=93 _ThreadName=http-thread-pool::jk-connector(2)] [timeMillis: 1629294459043] [levelValue: 900] [[
  Error findingcontrolledvocabulary.authorIdentifierScheme.researcherid in defaultLang : Can't find resource for bundle java.util.PropertyResourceBundle, key controlledvocabulary.authorIdentifierScheme.researcherid]]

[2021-08-18T13:47:39.043+0000] [Payara 5.2021.5] [WARNING] [] [edu.harvard.iq.dataverse.ControlledVocabularyValue] [tid: _ThreadID=93 _ThreadName=http-thread-pool::jk-connector(2)] [timeMillis: 1629294459043] [levelValue: 900] [[
  Error findingcontrolledvocabulary.authorIdentifierScheme.scopusid in defaultLang : Can't find resource for bundle java.util.PropertyResourceBundle, key controlledvocabulary.authorIdentifierScheme.scopusid]]

**Comment by qqmyers** [comment]
#7968 added a log message at https://github.com/IQSS/dataverse/blob/7fd59a580231d5506820cd2c5ac6e3922b627605/src/main/java/edu/harvard/iq/dataverse/ControlledVocabularyValue.java#L151 when your Bundle is missing a value/you have a lang dir with the citation properties file for your server (in the default lang for your server for the log above). Before that, this was a silent error.

If we want that restored, the line above should be removed.

**Comment by kcondon** [comment]
@qqmyers So you are indicating this is an intentional informative message and that my Bundle config is likely missing a value? I will double check but I'd thought I was running with the default bundle.

**Comment by qqmyers** [comment]
The CVVs would be in Bundles for the individual metadata blocks, so these would be in a citation.properties (or citation.properties_en) file that has to be in the lang dir

**Comment by kcondon** [comment]
So if I understand you, you are saying that in addition to language translations of fields that require additional key/pairs in their own bundle file, controlled vocabulary also needs such key/pair fields to be added to bundle files of the corresponding block name for even the default lang?  My understanding is the lang dir jvm-option was entirely optional so in the case of a default config (unless we have a custom citation.properties?) an admin needs to do nothing additional for this to work. I'll look in citation.properties and then will put this out to the tech list for a more general discussion. The key name looks like it has a typo in the error anyway and so it may have been a bad citation.properties change.

**Comment by qqmyers** [comment]
If you compare the citation.tsv file's definition of the CVV values (at https://github.com/IQSS/dataverse/blob/7fd59a580231d5506820cd2c5ac6e3922b627605/scripts/api/data/metadatablocks/citation.tsv#L131-L138) with the citation.properties file (at https://github.com/IQSS/dataverse/blob/7fd59a580231d5506820cd2c5ac6e3922b627605/src/main/java/propertyFiles/citation.properties#L285-L289) it looks like new values were added to the tsv 2 years ago (in https://github.com/IQSS/dataverse/commit/c9618d55693ae36b0cf0667df3f14a7632ae5bde) and the properties file was not updated to match.

**Comment by kcondon** [comment]
OK, so this issue now becomes, "default citation.properties is missing several keys"?
