### ISSUE TITLE
BagIt Doesn't Get All Files

### ISSUE THREAD

**Issue by shlake** [IQSS/dataverse#8066]
For Datasets that have files with the same filename, only one file (of that name) is added to the "data" directory in the bag, or appears in the manifest file. 

But the bag-info.txt file has "counted" ALL files, but the "Payload-Oxum" doesn't match the number of files in the manifest (or in the folder "data").

**Comment by shlake** [comment]
It doesn’t matter whether the files with the same name is in the same path (or no path) or in different ones.

I have one of each example. One dataset has 6 files (no path) and another has paths - it was a from github so there are multiple README.md files in different directories.

**Comment by qqmyers** [comment]
FWIW: The current implementation could have limitations/problems when two files with the same directory path have the same name (see https://github.com/IQSS/dataverse/blob/7fd59a580231d5506820cd2c5ac6e3922b627605/src/main/java/edu/harvard/iq/dataverse/util/bagit/BagGenerator.java#L526-L528) or when two files in the dataset have the same hash (see https://github.com/IQSS/dataverse/blob/7fd59a580231d5506820cd2c5ac6e3922b627605/src/main/java/edu/harvard/iq/dataverse/util/bagit/BagGenerator.java#L547-L551). 

Are there log messages that indicate one or both of these issues (or something else?).

**Comment by shlake** [comment]
Testing w/ V5.5 the Dataverse software will not allow duplicate filenames (in the same path). So the problem of two files within same directory having the same name - shouldn't happen (now). 

So the real issue is.....  files that have the same name in different paths - so is this a problem with bagit that it is a flat structure?

To answer your question - there are no "Duplicate/Collision" errors.
Yes, there are "Multiple items with the same title" errors, but these are for files in different "Paths".

**Comment by shlake** [comment]
Philosophical Sherry question.... are bags created for "archival" purposes, or are they created (and used) as a backup - which means that bagging a Dataverse dataset needs to represent the exact file (and naming) structure for the original dataset if it is to be "moved" to a new Dataverse repository?

**Comment by shlake** [comment]
@qqmyers Can the "bag name" or DOI be added to the logger.warning messages? Would be nice to know which dataset had the error.

**Comment by qqmyers** [comment]
~Both - the idea of having the OAI-ORE map in the Bag is so that all original metadata (including file names/dir structure) can be preserved even when the file name/path in the Bag might differ. Having the paths/names of files within the Bag match what's in Dataverse is a convenience/usability help rather than a requirement. (The data files could just be named 1,2,3,4 and all added directly under the /data dir in the Bag and things would still work.)

**Comment by qqmyers** [comment]
FWIW: #8067 adds the directory path of the files under the /data dir - so things stay human readable.
