### ISSUE TITLE
Database: Put not null constraints on table columns where appropriate, eg. datasetversion createtime, lastupdatetime.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#807]
As we have moved along in our development, we are seeing data issues where old data created during more lax data requirements is causing errors with newer code that makes assumptions about fields having a value.

Specifically, datasetversion table needs to have a createtime and lastupdatetime and should probably be marked as not null. The code currently adds these but perhaps the db should also enforce this?

I'm making this ticket more general so these issues can also be looked at as a class of problems.

**Comment by pdurbin** [comment]
The Dataverse object should be examined as well. The database currently allows "alias" to be null, for example.

**Comment by michbarsinai** [comment]
Lots of constraints added. Some cases, where I was not sure, are detailed here:
https://docs.google.com/spreadsheets/d/1Q1NanQtTyk1z6ZoIg-nb3n98K1gvvVgLuHaWbg6M97s/edit?usp=sharing

**Comment by pdurbin** [comment]
@michbarsinai your Google Doc says "ControlledVocabularyValue - identifier - Fails for value NA".

Is that why I can't create a dataset via SWORD anymore? The stacktrace says, "A system exception occurred during an invocation on EJB DatasetFieldServiceBean, method: public edu.harvard.iq.dataverse.ControlledVocabularyValue edu.harvard.iq.dataverse.DatasetFieldServiceBean.findNAControlledVocabularyValue()"

**Comment by michbarsinai** [comment]
"Fixed" - turns out the N/A also does not have a type. So I removed this constraint. Post 4.0, we might want to add an internal N/A type so that we can impose non-null constraint on types.

-- Michael

**Comment by pdurbin** [comment]
@michbarsinai thanks! Your commit at 03fca79e4a25e3832aef4c44285d7d37c6198505 did seem to resolve the issue. I'm able to create datasets via SWORD.

**Comment by scolapasta** [comment]
Added not null to md5 and UNF

**Comment by scolapasta** [comment]
Added questionType in CustomQuestion and name and displayName in ForeignMetadataFormatMapping per the google doc.

**Comment by scolapasta** [comment]
OK, I think this is et for 4.0. I'd still like to review one more time in 4.01, so moving this issue to there.

**Comment by scolapasta** [comment]
We're all set with these. If we find any others, we'll open up a new issue.
