### ISSUE TITLE
Dataset with many of files

### ISSUE THREAD

**Issue by mohammadsalem** [IQSS/dataverse#8080]
Hi!

We recently created a dataset containing 106K JPG images and few CSV files, we uploaded them using sword zip uploader with 500 files each patch. 
Now every operation on that dataset is taking a very long time, even loading the dataset page is taking more than 20 minutes which made it impossible to use. Until it had around 90K files the dataset page was taking about 4 minutes to load which was more or less ok, even the upload became not possible after 90K files so we had to move the already existing files into a temp dataset (from the database) to upload the rest of the files then we moved them back.

Now we still need to update all the files to add more metadata and publishing it which is not possible.

Is there any limitations on the files count for a dataset? Do you have any suggestions/tricks to make it usable? Is this something you plan to consider, supporting datasets with large number of files?

Running on Dataverse V5.6

Thanks!

**Comment by djbrooke** [comment]
Hi @mohammadsalem - I'll go ahead and close this out since the immediate issue is resolved. Once we can revisit datasets with large numbers of files - either through optimizations or changing to package files or something else - we can start with a new issue.
