### ISSUE TITLE
timestamp of data access request

### ISSUE THREAD

**Issue by npoppelier** [IQSS/dataverse#8092]
If you open the overview Restricted File Permissions of a dataset with restricted access, you get an overview of open requests, with the following columns: User/Group Name, ID, Authentication, Email, Files, Access (buttons).

We would like to have an extra column there: Date (or Datetime) of the access request. This would imply a change in the GUI but also a change in the database schema, since the timestamp of the access request is not stored yet (see https://guides.dataverse.org/en/5.4/schemaspy/tables/fileaccessrequests.html).

**Comment by pdurbin** [comment]
@npoppelier thanks for discussing this a while back at https://groups.google.com/g/dataverse-community/c/FHy7IVW3Z3Q/m/am6omciNCAAJ and ultimately opening this issue.

To make this a little more concrete, here's a screenshot of how the list of requests looks as of Dataverse 5.10:

<img width="982" alt="Screen Shot 2022-03-31 at 7 27 45 AM" src="https://user-images.githubusercontent.com/21006/161045019-6d205497-d912-4463-9a6d-1ed3548ba5d5.png">

I don't believe it would be too difficult to add an extra column called "Date". Perhaps if you hover over the date it would reveal an actual timestamp.

We'd need to think about all the old files that don't have a timestamp. Do we always include the "Date" column and just show a blank space when there's no date? Do we hide the "Date" column unless at least one file has a timestamp?

Are you a developer or do you know one who could work on this? If so, let's decide some of these details above before you or they begin. If not, I can try to advocate for this issue to the people who prioritize issues.

Is your installation of Dataverse on our map? If so, perhaps you could create a board to indicate which issues are most important to you. This idea of mine is not fully formed, but you can read about it in the "boards for prioritizing issues (for each installation of Dataverse)" thread: https://groups.google.com/g/dataverse-community/c/z8ugn2KzNSc/m/zt7COeRYBQAJ

**Comment by npoppelier** [comment]
Hi Philip,

Thanks for the reassurance that the addition of an extra column "Date", both in the data model and the user interface, is not a lot of work.
A solution with hovering sounds nice and does not take up extra space. When there's no date, the hover space can be filled with '-------' instead of '2022-03-31T09:15:33' for example.

I have done some Dataverse-related development work in Python, but I'm not a Java developer. At the UMCU we do not have Java developers unfortunately.

The UMCU does not have its own installation of Dataverse: we are members of the network organized by DANS around DataverseNL, and DataverseNL is certainly on your map. Should this idea first be discussed at the DANS level?
Regards, Nico


Van: Philip Durbin ***@***.***>
Verzonden: donderdag 31 maart 2022 13:38
Aan: IQSS/dataverse ***@***.***>
CC: Poppelier, N.A.F. (Nico) ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [IQSS/dataverse] timestamp of data access request (#8092)


@npoppelier<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnpoppelier&data=04%7C01%7CN.Poppelier%40umcutrecht.nl%7C5ed5fd29221d4edd3f2308da130af361%7Cdcdf4a3dd0c04a6394cf781981249be5%7C0%7C0%7C637843235758505440%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Y%2Bgj55Bm2K7QYsuJlG%2FWInuf2d1NqmVAX%2BbM8aGdy4g%3D&reserved=0> thanks for discussing this a while back at https://groups.google.com/g/dataverse-community/c/FHy7IVW3Z3Q/m/am6omciNCAAJ<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgroups.google.com%2Fg%2Fdataverse-community%2Fc%2FFHy7IVW3Z3Q%2Fm%2Fam6omciNCAAJ&data=04%7C01%7CN.Poppelier%40umcutrecht.nl%7C5ed5fd29221d4edd3f2308da130af361%7Cdcdf4a3dd0c04a6394cf781981249be5%7C0%7C0%7C637843235758505440%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=tT1FJ4X9MKsoeJOSd6Nbe9Z2qSUMDT9%2B5Db8JnMGHgI%3D&reserved=0> and ultimately opening this issue.

To make this a little more concrete, here's a screenshot of how the list of requests looks as of Dataverse 5.10:

[Screen Shot 2022-03-31 at 7 27 45 AM]<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F21006%2F161045019-6d205497-d912-4463-9a6d-1ed3548ba5d5.png&data=04%7C01%7CN.Poppelier%40umcutrecht.nl%7C5ed5fd29221d4edd3f2308da130af361%7Cdcdf4a3dd0c04a6394cf781981249be5%7C0%7C0%7C637843235758505440%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=InRZw8QHSh%2BGgcS7GymuWCnE7OZfz76vn44IeUAp35I%3D&reserved=0>

I don't believe it would be too difficult to add an extra column called "Date". Perhaps if you hover over the date it would reveal an actual timestamp.

We'd need to think about all the old files that don't have a timestamp. Do we always include the "Date" column and just show a blank space when there's no date? Do we hide the "Date" column unless at least one file has a timestamp?

Are you a developer or do you know one who could work on this? If so, let's decide some of these details above before you or they begin. If not, I can try to advocate for this issue to the people who prioritize issues.

Is your installation of Dataverse on our map? If so, perhaps you could create a board to indicate which issues are most important to you. This idea of mine is not fully formed, but you can read about it in the "boards for prioritizing issues (for each installation of Dataverse)" thread: https://groups.google.com/g/dataverse-community/c/z8ugn2KzNSc/m/zt7COeRYBQAJ<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgroups.google.com%2Fg%2Fdataverse-community%2Fc%2Fz8ugn2KzNSc%2Fm%2Fzt7COeRYBQAJ&data=04%7C01%7CN.Poppelier%40umcutrecht.nl%7C5ed5fd29221d4edd3f2308da130af361%7Cdcdf4a3dd0c04a6394cf781981249be5%7C0%7C0%7C637843235758505440%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=UJm2JyU7QnR92pudcWc9ibprlUObMs0I0o3%2F4y9532A%3D&reserved=0>

-
Reply to this email directly, view it on GitHub<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FIQSS%2Fdataverse%2Fissues%2F8092%23issuecomment-1084467928&data=04%7C01%7CN.Poppelier%40umcutrecht.nl%7C5ed5fd29221d4edd3f2308da130af361%7Cdcdf4a3dd0c04a6394cf781981249be5%7C0%7C0%7C637843235758505440%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=rdlb91vsbvhB1LPE54aHihu86NDO10slGXSmrirhSL8%3D&reserved=0>, or unsubscribe<https://eur05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAM2LWSZDH2XF76MEW6UUT3LVCWFCNANCNFSM5D6AG7MA&data=04%7C01%7CN.Poppelier%40umcutrecht.nl%7C5ed5fd29221d4edd3f2308da130af361%7Cdcdf4a3dd0c04a6394cf781981249be5%7C0%7C0%7C637843235758505440%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=68YmfDgNw%2BO6AgsiYtD1NZqt81DJEYWRjmU5IQb%2FQ40%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

------------------------------------------------------------------------------

De informatie opgenomen in dit bericht kan vertrouwelijk zijn en is
uitsluitend bestemd voor de geadresseerde. Indien u dit bericht onterecht
ontvangt, wordt u verzocht de inhoud niet te gebruiken en de afzender direct
te informeren door het bericht te retourneren. Het Universitair Medisch
Centrum Utrecht is een publiekrechtelijke rechtspersoon in de zin van de W.H.W.
(Wet Hoger Onderwijs en Wetenschappelijk Onderzoek) en staat geregistreerd bij
de Kamer van Koophandel voor Midden-Nederland onder nr. 30244197.

Denk s.v.p aan het milieu voor u deze e-mail afdrukt.

------------------------------------------------------------------------------

This message may contain confidential information and is intended exclusively
for the addressee. If you receive this message unintentionally, please do not
use the contents but notify the sender immediately by return e-mail. University
Medical Center Utrecht is a legal person by public law and is registered at
the Chamber of Commerce for Midden-Nederland under no. 30244197.

Please consider the environment before printing this e-mail.

**Comment by pdurbin** [comment]
@npoppelier let me ping @janvanmansum (DANS) and @qqmyers (GDCC) who recently collaborated on an awesome new "multiple licenses" feature. I gave them a well-deserved shout out in the Dataverse 5.10 announcement: https://groups.google.com/g/dataverse-community/c/cgiUjHcUzi8/m/EY5WbfnYAwAJ

They might be able to tell you more about if DANS/GDCC can help with this. I don't think this feature is especially controversial but I'll go ahead and ping @TaniaSchlatter and @jggautier if they'd like to weigh in on UI/UX impact. (It occurs to me that it might be nice to sort by the proposed "Date" column.) And I'm sure @scolapasta would be interested in the database change.

One thing I forgot to mention earlier is that you can see what the core team is working on by looking at our project board at https://github.com/orgs/IQSS/projects/2 . That is to say, if one of the ~1200 open issues isn't on that board, it hasn't been prioritized. I think your idea is good one, but there are lots of good ideas in this issue tracker. 😄 

Finally, we have plenty of code in Python. Please let me know if you're itching to work on something! 😄
