### ISSUE TITLE
Migrate codebase to Java 17 LTS

### ISSUE THREAD

**Issue by poikilotherm** [IQSS/dataverse#8094]
Today, Java 17 has been released. This is the next LTS version of Java following 11, which will still be around for some time and then EOL.

Dataverse should run on the next generation Java, too! 🎊🥳

Things that pop up:
- Payara has had a roadmap item for JDK 17 support for Q3/2021. Let's see how fast this will become a reality.
- We might already add support for compiling and unit testing etc with Java 17 on CI to watch out for any trouble.
- Maybe it's a good idea so rewrite some DTOs to records...?

**Comment by pdurbin** [comment]
Similar errors came up in [chat](https://matrix.to/#/!AmypvmJtUjBesRrnLM:matrix.org/$dsdEwLzi12LtlCCVyRDP6JnCOWfeeEzmYBW4i76hqiw) the other day on Java 16:

![Screen Shot 2021-11-04 at 3 37 44 PM](https://user-images.githubusercontent.com/21006/140408535-628ee6d7-42ae-4106-a9b0-292c3f7508e7.png)

**Comment by poikilotherm** [comment]
Maybe we can add a build matrix to our Github Unit Test workflow and use a shadow job to make it non-failing?

See https://ncorti.com/blog/howto-github-actions-build-matrix

**Comment by poikilotherm** [comment]
### Current status

![image](https://user-images.githubusercontent.com/5468333/151152860-05444ac6-0f06-472d-bf5e-22208fde1422.png)

### Dependency updates

This means we need to at least upgrade GSON and RestAssured deps: 

```
[ERROR] edu.harvard.iq.dataverse.export.DDIExporterTest.testExportDataset  Time elapsed: 0.163 s  <<< ERROR!
java.lang.reflect.InaccessibleObjectException: Unable to make field private final int java.time.LocalDate.year accessible: module java.base does not "opens java.time" to unnamed module @23ceabc1
	at edu.harvard.iq.dataverse.export.DDIExporterTest.testExportDataset(DDIExporterTest.java:68)
        [...]
        at com.google.gson.Gson.fromJson(Gson.java:689)

[ERROR] edu.harvard.iq.dataverse.export.OpenAireExporterTest.testExportDataset  Time elapsed: 0.532 s  <<< ERROR!
java.lang.reflect.InaccessibleObjectException: Unable to make private java.util.regex.Pattern(java.lang.String,int) accessible: module java.base does not "opens java.util.regex" to unnamed module @23ceabc1
	at edu.harvard.iq.dataverse.export.OpenAireExporterTest.testExportDataset(OpenAireExporterTest.java:74)
        [...]
        at com.jayway.restassured.path.xml.XmlPath.getString(XmlPath.java:573)
```

### NPEs

These all seem related to `null` in some paths?

```
[ERROR] edu.harvard.iq.dataverse.dataaccess.DataAccessTest.testCreateNewStorageIO_createsFileAccessIObyDefault  Time elapsed: 0.003 s  <<< ERROR!
java.lang.NullPointerException
	at edu.harvard.iq.dataverse.dataaccess.DataAccessTest.testCreateNewStorageIO_createsFileAccessIObyDefault(DataAccessTest.java:59)
```
![image](https://user-images.githubusercontent.com/5468333/151153358-9ac48b16-87e2-4623-afdc-b6eca62cf6bf.png)

```
[ERROR] edu.harvard.iq.dataverse.dataset.DatasetUtilTest.testGetThumbnailCandidates  Time elapsed: 0 s  <<< ERROR!
java.lang.NullPointerException
	at edu.harvard.iq.dataverse.dataset.DatasetUtilTest.testGetThumbnailCandidates(DatasetUtilTest.java:35)
```
![image](https://user-images.githubusercontent.com/5468333/151153614-0f963279-8147-4385-ae59-f7c539e552ca.png)


```
[ERROR] edu.harvard.iq.dataverse.dataset.DatasetUtilTest.testGetThumbnailNullDataset  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NullPointerException
	at edu.harvard.iq.dataverse.dataset.DatasetUtilTest.testGetThumbnailNullDataset(DatasetUtilTest.java:53
```
![image](https://user-images.githubusercontent.com/5468333/151153737-3101831b-0e03-445d-b2c7-3808661175c5.png)

**Comment by poikilotherm** [comment]
@qqmyers @pdurbin @donsizemore I created #8362 to include regular Java 17 CI builds, flagged as "Experimental". WDYT?

**Comment by donsizemore** [comment]
Related to #7530 - OpenJDK17 includes [a "production ready" version of ZGC](https://malloc.se/blog/zgc-jdk17)
