### ISSUE TITLE
Vagrant setup.sh broken link

### ISSUE THREAD

**Issue by gammaeva** [IQSS/dataverse#8104]
When deploying with vagrant, the maven download link in /scripts/vagrant/setup.sh is not accessible anymore.

`wget -q https://www-us.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz`

can be replaced by 

`wget -q https://archive.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz`

**Comment by djbrooke** [comment]
Thanks @gammaeva for the heads up. Would you be willing to make a pull request for this small change? If not, we can make the change, but I wanted to check with you first.
