### ISSUE TITLE
Split off GrantFileAccess permission from ManageDatasetPermissions

### ISSUE THREAD

**Issue by janvanmansum** [IQSS/dataverse#8109]
Problem
======
Currently, the permission to grant file access is grouped together with the permission to assign roles to users and groups under `ManageDatasetPermissions`. This is problematic in the following scenario: 

* You have configured a dataverse so that dataset creators get the role "contributor" on the datasets they create, meaning   that the dataset has to be reviewed and published by a curator.
* You still want to delegate the responsibility to grant access to restricted files to the dataset creator.

To enable the creator to handle the access requests you could assign them a role that includes  `ManageDatasetPermissions`. However, that would also enable them to assign to themselves any other role, including curator, thus enabling them to publish new versions of the dataset without prior review.

Solution
======

By separating `ManageDatasetPermissions` into `ManageDatasetPermissions` (assigning roles) and `GrantFileAccess` (granting access to files) this can be resolved.

Code changes
==========

* A new permission `GrantFileAccess` will be created.
* All permission checks in the code that currently check for `ManageDatasetPermissions` will be reviewed. In the occurrences where the protected action is granting file access, the check's argument will be changed to `GrantFileAccess`.
* A flyway script will be created that updates the table `dataverserole` so that all roles that include the permission bit for `ManageDatasetPermissions` will additionally get the bit for `GrantFileAccess`.

**Comment by qqmyers** [comment]
FWIW: Sounds like this could be useful at Harvard (talked to Sonia). It doesn't fit the curation model at QDR (where QDR staff will handle file access requests) but no concerns regarding splitting the permissions from them either.
