### ISSUE TITLE
XML Parsing Error: duplicate attribute Location: https://dados.ipb.pt/dataset.xhtml?persistentId=doi%3A10.34620%2FFK2%2FN0SAHK&version=DRAFT

### ISSUE THREAD

**Issue by aialves** [IQSS/dataverse#8116]
![dataverse](https://user-images.githubusercontent.com/13556933/134988663-c2714df3-93fb-4d54-a7a8-2a21b57e91e6.png)
Can someone help me with this error? It happens when I try to create a dataset (with DOI)?
Thanks in advance.
Best regards,
Adília Alves

**Comment by donsizemore** [comment]
Hello, this is just curiosity on my part - do you get any errors in your browser's console / developer tools when you try to publish a dataset? (it may still say line 118, col 342, but may provide more helpful information)

**Comment by aialves** [comment]
Hello.
Nothing new is shown on browser's inspector. Thank you.
![xmlparsing](https://user-images.githubusercontent.com/13556933/135172021-c2bd3350-21dd-495b-983f-e4d11a189697.png)
.

**Comment by tjouneau** [comment]
Sorry to reopen this, but what was the solution eventually found to this issue?

**Comment by pdurbin** [comment]
@tjouneau thanks for opening a fresh issue (#8931) about this.
