### ISSUE TITLE
Improve accessing all files in a dataset when all files are restricted and request access enabled

### ISSUE THREAD

**Issue by TaniaSchlatter** [IQSS/dataverse#8126]
When all files in a dataset are restricted with request access enabled, there is no dataset-level "Access Dataset" button displayed on the dataset page (example: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/CN0PR9). There is an "Access Dataset" button displayed on **file pages** when the file is restricted, and access has not been requested or granted. 

We should display the "Access Dataset" as a dropdown button on the dataset page with the option to select "Request Access" when some or all files in the dataset are restricted. This is partly for consistency, as users can select all files in the file table and request access. 

Related to #7469: People requesting access to a file need visible feedback when request is sent

**Comment by pdurbin** [comment]
> When all files in a dataset are restricted with request access enabled, there is no dataset-level "Access Dataset" button displayed on the dataset page (example: https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/CN0PR9). There is an "Access Dataset" button displayed on **file pages** when the file is restricted, and access has not been requested or granted.

https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/X74UQJ is a better example now. (As indicated, there is no "Access Dataset" button.) The previous dataset now has all non-restricted files.
