### ISSUE TITLE
Change Dataverse / Dublin Core mapping to improve OAI-PMH harvesting

### ISSUE THREAD

**Issue by philippconzett** [IQSS/dataverse#8129]
## Note: dc:rights is being handled in #5920 and https://github.com/IQSS/dataverse/issues/4176 but the original description of this issue has been preserved.

Based on a semi-systematic survey of how DataverseNO metadata is harvested in Bielefeld Academic Search Engine (BASE; [https://www.base-search.net/Search/Advanced](https://www.base-search.net/Search/Advanced)), a major search engine for research outputs, we have noticed some issues related to the way the Dataverse software provides Dublin Core metadata for OAI-PMH harvesting.

**dc:type**
BASE harvests multiple types of research output, e.g. publications and datasets. Searching BASE you can filter/limit the search result to only include datasets by selecting _Dataset_ in the _Document Type_ section of advanced search:
![image](https://user-images.githubusercontent.com/21955790/135749473-607b8606-f4f5-4935-a3a1-2217a5276a9b.png)

However, only very few metadata records harvested directly from DataverseNO are marked as Document Type = Dataset.
It seems that in the oai_dc format, which BASE uses for harvesting, _Document Type_ is based on the dc:type field. According to the Dataverse Metadata Crosswalk, dc:type corresponds to the Dataverse metadata field _Kind of Data_. But this field may contain very different values, e.g., “survey data”, “survey”, “observations” etc. Dublin Core (see [https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/type](https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http://purl.org/dc/terms/type)) recommends “to use a controlled vocabulary such as the DCMI Type Vocabulary” for dc:type. The DCMI Type Vocabulary has “dataset” as one of its values. I therefore suggest changing the Dataverse / DC Element (oai_dc) mapping, so that dc:type is hard-coded as “dataset” for all dataset metadata in Dataverse.

**dc:date**
The Dataverse metadata field _Publication Date_ is available as dcterms:issued, but it doesn’t seem to be among the oai_dc fields Dataverse exposes for OAI-PMH harvesting. According to the Dataverse Metadata Crosswalk, dc:date corresponds to the Dataverse metadata field _Deposit Date_, but all the random samples I tested in BASE indicate that dc:date, which BASE uses as input for their metadata field _Year of Publication_, corresponds to the Dataverse field _Date of Production_. I suggest changing the Dataverse / DC Element (oai_dc) mapping, so that dc:date is mapped with _Publication Date_. This is also in line with citation recommendations. The publication date is the preferred date when citing research data; see, e.g., page 12 in The Tromsø Recommendations for Citation of Research Data in Linguistics; [https://doi.org/10.15497/rda00040](https://doi.org/10.15497/rda00040).

**dc:rights**
For some of the sources included in BASE, there is an indication of the degree of Open Access. Among them are some Dataverse-based repositories. On the other side, for DataverseNO and other Dataverse-based repositories, this information is not available / unknown (“unbekannt”):
![image](https://user-images.githubusercontent.com/21955790/135749781-ef2d7c4a-6cf9-4b22-9b7f-7184c10f7698.png)

The Open Access information in BASE is based on the Dublin Core field dc:rights. Dataverse does not provide the field dc:rights. A correct value in this field would enable BASE to indicate the degree of Open Access (see more information at [https://www.base-search.net/about/en/faq_oai.php#dc-rights](https://www.base-search.net/about/en/faq_oai.php#dc-rights)). For datasets without access restriction, the dc:rights field could look like this: info:eu-repo/semantics/openAccess (see more information at [https://guidelines.openaire.eu/en/latest/data/field_rights.html#rightsuri-ma](https://guidelines.openaire.eu/en/latest/data/field_rights.html#rightsuri-ma)).

**Comment by poikilotherm** [comment]
Related #8693

**Comment by pdurbin** [comment]
> I suggest changing the Dataverse / DC Element (oai_dc) mapping, so that dc:date is mapped with _Publication Date_.

I believe that @tcoupin fixed this in the following pull request, which we just merged and will be available in the next version of Dataverse (5.13 as of this writing):

- #8733

By the way, thank you @philippconzett for the extensive write up! It's a lot to go through. Very thorough. 😄

**Comment by jggautier** [comment]
Related: https://github.com/IQSS/dataverse/issues/5920

**Comment by cmbz** [comment]
2024/05/08
- Identify which elements of the request have already been addressed by open or closed issues
- Split remaining elements into their own issues

**Comment by DS-INRA** [comment]
Another related issue:
- https://github.com/IQSS/dataverse/issues/4176

**Comment by pdurbin** [comment]
@philippconzett (and any others watching this issue), I create a pull request to address the points you made above:

- #10737

Please take a look and feel free to leave comments or a review on the pull request. Thanks.

**Comment by philippconzett** [comment]
@pdurbin  Thanks! I just left a comment on the PR.

**Comment by pdurbin** [comment]
This issue was just closed because we merged the following pull request:

- #10737

As explained above, changes to dc:rights were not included in the scope of the pull request. Please look instead to these issues:

- #5920
- #4176
