### ISSUE TITLE
Add a simple, general green feedback message when access is requested

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#8133]
"Your request for access has been submitted to dataset curators"

_Originally posted by @TaniaSchlatter in https://github.com/IQSS/dataverse/issues/7469#issuecomment-934701158_

Let's identify the correct "role" for that message. I don't think "data curator" is the appropriate role, but "dataset adminstrator"--i think the admins get the notifications for request...Gustavo can confirm

**Comment by scolapasta** [comment]
It is anyone with the ManageDatasetPermissions permission, which is both the Curator role and the Admin role (if it gets passed down from the Dataverse).
