### ISSUE TITLE
On file upload.  Increase the size of file name fields.

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#814]
Minor.

See screen shot.  (Most of my test files have names the length of the cut off name in the screen shot)

![add_new_dataset_-_root_dataverse](https://cloud.githubusercontent.com/assets/1036060/3864617/f929d684-1f63-11e4-9738-0acd766f7065.png)

**Comment by mheppler** [comment]
Increased the width of the file name and description inputs on the file edit/upload page.

This whole table is going to need a little clean up, and I'll be addressing that in other tickets.

**Comment by esotiri** [comment]
issue is resolved
