### ISSUE TITLE
Email validation failed on Dataverse creation (worth flagging this again)

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#815]
Accidentally typed in this email address and it went through: ```pete@malinator.com.blah.ha^```

A "^" is allowed in the first part of an address, before the "@", but it shouldn't be in the domain name.

Here is the regular expression code for a heavily used* email validation routine that may be adapted for the system:

[email validation code in github](https://github.com/django/django/blob/master/django/core/validators.py#L119)

(*Used by edX, HarvardX, pinterest, etc) 

Related ticket: #364

**Comment by scolapasta** [comment]
E-mail validation needs to be consistent, so using this as the issue for all previously entered, related issues:
- dataverse e-mail, #364
dataset e-mail (this)
forgot password e-mail #864

**Comment by sekmiller** [comment]
All are now using consistent validator.

**Comment by sbarbosadataverse** [comment]
Tested using same email address that was used in original report and email validation worked. image attached in link below

https://www.dropbox.com/s/s23es1vl1v519vo/Screenshot%202015-03-18%2015.47.14.png?dl=0
