### ISSUE TITLE
Implement Protected Branches

### ISSUE THREAD

**Issue by djbrooke** [IQSS/dataverse#8166]
As we increase in contributors (hooray!) we should take a look at Protected Branches in order to make sure only appropriate changes make it into develop and main:

https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/about-protected-branches

@pdurbin mentioned that OpenDP uses this with success - we should take inspiration from what they do.

**Comment by pdurbin** [comment]
Right, below are the rules used by OpenDP. We may not want to go as far in terms of requiring that tests/checks pass before merging or requiring a certain number of reviews before merging. Also, we might want to consider disabling force pushes.

## overview

![Screen Shot 2021-10-19 at 9 58 53 AM](https://user-images.githubusercontent.com/21006/137963506-b6887f68-cce9-4e54-994e-ea4551a3aa16.png)

## main (develop for us)

![Screen Shot 2021-10-19 at 9 58 08 AM](https://user-images.githubusercontent.com/21006/137963507-96c94076-f9dc-45df-896d-7dcc811630bb.png)

## release branches (we don't use these)

![Screen Shot 2021-10-19 at 9 58 38 AM](https://user-images.githubusercontent.com/21006/137963508-752f9db4-3536-4126-9da8-0d5d1e79df2e.png)

**Comment by pdurbin** [comment]
> Main focus is preventing force pushing, and making branch only updatable with PRs instead of pushing direct to develop and main (master)

I just implemented branch protection for our two persistent branches:

- develop
- master

(For the uninitiated, we describe these branches here: https://guides.dataverse.org/en/5.8/developers/version-control.html#branches )

I took the approach outlined above, which means the following:

- You can only update these branches with pull requests.
- You can't force push to the branches.
- You can't delete the branches.

For the last two, force push and delete, you have to actively check boxes to say that you want to allow these. Please see the screenshots below for the config.

![Screen Shot 2021-11-23 at 2 22 09 PM](https://user-images.githubusercontent.com/21006/143090962-eb962278-b844-4b8c-91b7-c3286c2b22bd.png)

![Screen Shot 2021-11-23 at 2 22 58 PM](https://user-images.githubusercontent.com/21006/143090974-63da7aa9-2573-4e87-861b-6a2e0215951f.png)

**Comment by djbrooke** [comment]
Thanks @pdurbin. Looks good to me. 

@scolapasta can you give it a 👍 or discuss in tech hours to see if there are questions?

**Comment by scolapasta** [comment]
👍  This looks good to me as well. I don't see a current need for being too beauracratic (requiring ax number of approvals, requiring tests pass, etc. (I think we've done well enough with these, manually, and the goal of this issue was more just to protect against mistakes.

**Comment by pdurbin** [comment]
Just a heads up that we adjusted these rules because they broke automation, specifically, moving PRs to QA upon approval. For the latest rules, see https://github.com/IQSS/dataverse/issues/8388#issuecomment-1058419068
