### ISSUE TITLE
Upload of large TIFF file caused dataset timeout

### ISSUE THREAD

**Issue by nightowlaz** [IQSS/dataverse#8176]
We had a depositor try to upload a TIF file that was generated by a microscope, so it was about 450MB, and included many stacks and high resolution. The upload went through in a couple of minutes, but when it got to the end of the progress bar, it stalled and never completed. She waited for 90 minutes and then tried to cancel the upload, and eventually had to close the upload window. We were able to upload the file via API with no problem.
 
We got a tip from Leonid to set the Ddataverse.dataAccess.thumbnail.image.limit to 3MB, and once we did that, the file uploaded fine, but did not create the thumbnail. 

Was asked to put this in as an issue to help with providing more documentation on the thumbnail image creation/limit. We are also wondering if it might be helpful to have an option to manually upload file thumbnails in such a case.  

Thanks!

**Comment by nightowlaz** [comment]
Setting the dataverse.dataAccess.thumbnail.image.limit<https://guides.dataverse.org/en/latest/installation/config.html#dataverse-dataaccess-thumbnail-image-limit> JVM option to 3M worked for us, although doing so eliminates the thumbnail creation.
Also noted, when I used our large file upload store (direct upload), it also worked and created the thumbnail, but we opted for just setting a limit to reduce future issues.
It would be good to have the ability to manually upload a thumbnail image for those files that don’t automatically generate one.

**Comment by landreev** [comment]
We've been seeing some (anecdotal) evidence that TIFFs are especially expensive in terms of resizing, when processed by the image library Dataverse is using. 
Which is completely counter-intuitive (since TIFF is uncompressed; and thus you would expect it to cost less to handle - ??). 

> I'm not sure what happens if you have 250 of these files. An even longer delay?

When you are attempting to load the dataset page, it should never be attempting to generate thumbnails for more than one page-worth of files (i.e., 10, in most cases). But it looks like with TIFFs of this size 10 is enough to break/time out the page.

**Comment by landreev** [comment]
> Also noted, when I used our large file upload store (direct upload), it also worked and created the thumbnail, but we opted for just setting a limit to reduce future issues.

Interesting. When you use direct upload, the thumbnail is NOT generated on upload (same with a non-direct upload via API). The thumbnail gets generated the first time the dataset page loads. The fact that it worked... could it be because it was in a different dataset, where you had only one such large file? - So the page was able to generate it without timing out... Not sure, tbh.

**Comment by nightowlaz** [comment]
Hmmm now I’m doubting myself and wonder if I’m remembering wrong! Going to test it again I know the file uploaded, but now not sure it created the thumbnail. =)

**Comment by nightowlaz** [comment]
Yes, you are right .. using direct upload from the Dataverse dashboard, a 300MB Tiff file uploaded fine, but no thumbnail was created. So sorry for the misdirection, I don’t think I noticed that the thumbnail didn’t get created in the original test because we were focused on the file uploading! =D


From: Deirdre Kirmis
Sent: Friday, November 19, 2021 11:15 AM
To: IQSS/dataverse ***@***.***>; IQSS/dataverse ***@***.***>
Cc: Deirdre Kirmis ***@***.***>; Mention ***@***.***>
Subject: RE: [IQSS/dataverse] Upload of large TIFF file caused dataset timeout (Issue #8176)

Hmmm now I’m doubting myself and wonder if I’m remembering wrong! Going to test it again I know the file uploaded, but now not sure it created the thumbnail. =)

**Comment by landreev** [comment]
> It would be good to have the ability to manually upload a thumbnail image for those files that don’t automatically generate one.

This can be done currently; but with a good amount of manual work. 
If you have a large image file for which thumbnail generation was skipped, you can look up the location of the physical file on disk (or in the S3 bucket); and then create and place the thumbnails in the same directory, under the same filename but with the extensions .thumb64 and .thumb48 (the 64 and 48 pixel versions for the dataset and dataverse pages respectively). 

It is also possible that this can be done in a less hacky way... by using the new Aux file API... (thumbnails are essentially auxiliary files). But I'm not 100% about that - would need to check.

**Comment by nightowlaz** [comment]
That worked! Thanks for the tip! (I had to name the second file .thumb400).
I think the cases of this particular issue (at least at this time) will be few enough that we could handle this workaround for people needing it.

**Comment by landreev** [comment]
You are right, I forgot to mention the 3rd thumbnail size - the 400 pixel "large preview" for the dataset page. 
(but do note that you need all 3 - thumb48, thumb64 and thumb400)

**Comment by nightowlaz** [comment]
Okay great! That is so good to know! Thanks for taking time to explain that. Sorry I should have been responding in this forum instead of via email as I generated a lot of uneccessary text (I cleaned up my posts)!

**Comment by landreev** [comment]
It's all good; glad we could help.
Apologies for the fact that we didn't respond to/address this sooner. (it happens :( )

**Comment by nightowlaz** [comment]
oh no worries, we have (as I'm sure you all do too) many other things to work on! This is the most responsive community I've ever worked with!

**Comment by pdurbin** [comment]
Heads up that I just made pull request #8260 and indicated that it closes this issue.
