### ISSUE TITLE
Search: Does not support diacritics, eg, Guaraní from language field, Citation block.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#818]
Tested on 8/11

I created a dataset with Guaraní as a language. After  publishing, when I search on this either using basic or advanced search, I see no results. Also, after searching, the find edit box updates the accented i at the end to be a capital accented A with a tilde. Subsequent repeated clicks on find alters it more to create a graphic character.

**Comment by landreev** [comment]
Please retest, appears to be working. Tested with Mandarin, among other things. 
![search_accents](https://cloud.githubusercontent.com/assets/737558/5825650/03f443e6-a0bb-11e4-89a4-2a7071b22cf3.png)

**Comment by kcondon** [comment]
This works, closing
