### ISSUE TITLE
Style of green open lock icon changed in Dataverse v5.7

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#8181]
**What steps does it take to reproduce the issue?**

See green open lock icon in v5.6 (or earlier versions)
- Log into an account of a Dataverse repository running v5.6 (or an earlier version)
- Create a dataset with a restricted file or visit a dataset page with a restricted file that you have access to
- Notice the style of the open green lock icon

Compare to same icon in v5.7
- Log into an account of a Dataverse repository running v5.7
- Create a dataset with a restricted file or visit a dataset page with a restricted file that you have access to
- Notice that the style of the open green lock icon is different than the icon in v5.6. The bit of the lock shackle that's inside the body of the lock is white

**When does this issue occur?**
When a user views a restricted file that they have access to in a Dataverse repository running v5.7

**Which page(s) does it occurs on?**
All pages where a restricted file's open green lock icon appears: On the dataset page (on the file icon or thumbnail in the file table and in the restricted file's File access dropdown), on the search page, on the file page

**What happens?**
The icon style is different

**To whom does it occur (all users, curators, superusers)?**
To logged in users with access to restricted files

**What did you expect to happen?**
We were expecting the icon's style to stay the same between versions 5.6 and 5.7. 

**Which version of Dataverse are you using?**
v5.6 and v5.7

**Any related open or closed issues to this bug report?**
None that I could find

**Screenshots:**

Open green lock icon in v5.6 (and earlier versions):

<kbd><img width="552" alt="Screen Shot 2021-10-22 at 4 19 49 PM" src="https://user-images.githubusercontent.com/18374574/138520770-f6ca15e4-8b8b-434d-b9ab-009079a68098.png"></kbd>

Open green lock icon in v5.7:

<kbd><img width="542" alt="Screen Shot 2021-10-22 at 4 21 54 PM" src="https://user-images.githubusercontent.com/18374574/138520798-fec33fe9-fa42-46bb-b23b-058f7e0318b8.png"></kbd>

**Comment by djbrooke** [comment]
@jggautier I'm inclined to close this as there's not really anything actionable on our part. What do you think?

**Comment by jggautier** [comment]
@qqmyers followed up with me in Slack that he guessed that "the change three months back resulted in the new style but anyone who had the old fontcustom file cached in their browser wouldn't be seeing it."

I've cleared my cache on Google Chrome and still see the new icon style. I don't know how to test the reverse. That is, how do I get my browser to display the old icon style?

The actionable parts might be:
- Confirm that we don't really want the pages to use the new lock icon style that I'm seeing. @TaniaSchlatter asked me to open this issue after seeing the icon while looking at my screen when I was screen sharing a few weeks ago. But if the new icon isn't a problem, then I'd think this issue could be closed. If the new icon is a problem:
- Confirm that even after clearing your browser cache, you still see the old icon style

**Comment by TaniaSchlatter** [comment]
We don't want to the new unlocked icon style. The white shape is a mistake. I don't know how the appearance of that icon came to change, but it is problematic.

**Comment by BPeuch** [comment]
We have the same problem — or rather I should say, I have the same problem when I browse our updated Dataverse test instance (currently 5.10.1) from my work computer:

![open](https://user-images.githubusercontent.com/15209224/168755808-2ae42dd8-4ddf-45e2-ad46-7e6b24a8be76.png)

It shows up even after deleting my cache, as well as on several browsers.

(I must say I have a marked preference for the original icon.)

**Comment by jggautier** [comment]
I’m going to close this issue, since the icons are being redone as part of the rearchitecture, and I don't think it'll be addressed in pre-rearchitecture Dataverse.
