### ISSUE TITLE
Reviewers using anonymous private URL might learn dataset author's identity from information about the Dataverse installation or collection

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#8184]
Information about the installation and about the Dataverse collection that the dataset is in could help reveal the dataset author's identity to the dataset reviewer.

_Information about the repository housing the dataset:_

The anonymous private URL page shows the name of the Dataverse repository/installation that the dataset is in and the reviewer can navigate around the repository website to find more information about the repository. This could be an issue for Dataverse repositories with a more narrow/focused audience, like the repositories that only allow researches affiliated with a certain institution to deposit datasets.

_Information about the Dataverse collection housing the dataset:_

The anonymous private URL page shows the name of the Dataverse collection that the dataset is in, even if the Dataverse collection is unpublished. This feature was meant mostly for "Journal Dataverse collections," (#1724) so we should expect that the reviewer would already know, before ever visiting the anonymous private URL page, that the dataset is associated with a particular journal.

But the depositor's dataset could be in a Dataverse collection whose information (such as collection name or description) could be used to identify the author. This point was also brought up in two comments ([1](https://github.com/IQSS/dataverse/issues/1724#issuecomment-699079915), [2](https://github.com/IQSS/dataverse/issues/1724#issuecomment-699283667)) in the original GitHub issue. For example, many collections include the researcher's name because when people create Dataverse collections, the Dataverse software prefills the "Dataverse Name" field with the name of the Dataverse repository account that created the Dataverse collection. This is often the author's name, and the reviewer can see that Dataverse collection name, in the breadcrumbs on the anonymous private URL page.

**Comment by jggautier** [comment]
Hi everyone. Changes in the UI that @TaniaSchlatter and I are proposing are in the PDF, [Proposed changes to Anonymous Private URL.pdf](https://github.com/IQSS/dataverse/files/7488669/Proposed.changes.to.Anonymous.Private.URL.pdf). The PDF has two boxes, the first describing how the feature works as designed now (v5.7) and the second describing changes based on reviews by the curation team at Harvard Dataverse Repository and @kmika11's review with some researchers who've needed to share their dataset anonymously.

Changes to the User Guides section about this feature are in the Google Doc at https://docs.google.com/document/d/1bn4fIPr_yhOj_DYDldzdKEZjmETV-WLYc98sWTgcg58.

The changes are meant to address the issue described in this GitHub issue as well as address confusion about https://github.com/IQSS/dataverse/issues/8185. (@jeisner's [brought up other points](https://github.com/IQSS/dataverse/issues/1724#issuecomment-215571435), particularly about being able to anonymously share a dataset that's already been published, that this feature doesn't address.)

The next steps are:

- [ ] Gathering feedback...
  - [ ] From the community, particularly people who've worked on or expressed interest in this feature (including @jeisner, @Duhem123, @adam3smith, @philippconzett, @qqmyers, @meghangoodchild and
Jonathan Bohan at CISER). Please feel free to download and review the changes described in the PDF, visit [the Google Doc with changes to the User Guide section](https://docs.google.com/document/d/1bn4fIPr_yhOj_DYDldzdKEZjmETV-WLYc98sWTgcg58), and leave comments and questions in this GitHub issue, [issue #8185](https://github.com/IQSS/dataverse/issues/8185), and the Google Doc.
  - [ ] By reaching out to and testing the changes with more depositors who've already created and/or published datasets in the Harvard Dataverse Repository for double blind review
- [ ] Iterate on the proposed changes based on the feedback

**Comment by philippconzett** [comment]
Thanks for sharing the progress on this feature! The proposed changes look all good to me. The term "Prepublish URL" is clearer than "Private URL", and the descriptions in the pop-up windows and in the user guide are all very clear. I think the anonymized version of the Prepublish URL is mainly useful in cases where a dataset is part of a double-blind peer-review process. I have added a note on this in the Google doc.

As mentioned earlier, in DataverseNO, we use a special, unpublished collection for datasets that are part of a double-blind peer review process. Page 12 in [this presentation](https://hdl.handle.net/10037/21466) summarizes how DataverseNO currently supports double-blind peer review. See also [this fake example](https://dataverse.no/privateurl.xhtml?token=95d8d8fa-e953-4207-84ca-766bfa51f8d7) of an anonymized dataset in our double-blind peer review collection. 

Maybe an easy(?) way to enhance the Prepublish URL feature even more, could work like this:
When the depositor or curator (depending on the access rights) clicks the _Prepublish URL_ button and selects _Anonymous Review_, a copy of the dataset will be pushed into an anonymized collection like the double-blind peer review collection at DataverseNO, and the copy will be anonymized following the current _Anonymous Review_ feature.

That way, the name of the repository would still be revealed, but the collection would be anonymized.

**Comment by jggautier** [comment]
Thanks @philippconzett :) I think for now we've decided to change the layout and the text on the popup to help the depositor understand the limitations of the feature, like how the collection name can help reveal the the authors' identities. 

I'm all for opening another issue specifically for discussing ways to remove that limitation. @djbrooke and @TaniaSchlatter, what do you think?

To get more feedback about the redesigned popup, we reviewed it with 6 people - 5 people who I found used workarounds to deposit datasets in Harvard Dataverse Repository for anonymous review and 1 person who manages a journal's Dataverse Collection in the repository and has been interested in support for anonymous review. The redesign seemed to work well and I made small text-based adjustments based on the issues we heard:

- One depositor who saw the button for disabling the Anonymous Review URL said he worried that if he disabled the link, the people who he gave the link to would then be able to see the metadata that would identify him as an author.
- Another person suggested including that the "General Review" link would include metadata that could identify the author.

These screenshots of the popup show the text changes:

<img width="1030" alt="Screen Shot 2021-12-16 at 9 22 52 AM" src="https://user-images.githubusercontent.com/18374574/146389388-7c23b537-7a38-49c9-961f-dbb6d7e51045.png">

I also split the last block of text in two to improve readability and changed "data files" to "dataset's files". We heard during the review of the metadata tooltips that "data files" could be interpreted to exclude other types of files like "documentation files" and "code files", so I think it's better to use broader language here.

We learned more about the feature in general, including how discoverable it is (or isn't), and we heard things about the journal review process that I think we need to learn more about, so I'm working on summarizing that feedback and recommending next steps.

**Comment by TaniaSchlatter** [comment]
The wording and layout changes outlined above should help from the UI perspective, however moving them forward is not a complete programmatic fix.

**Comment by meghangoodchild** [comment]
Thanks for the opportunity to provide feedback. The anonymous review feature is certainly a desired feature.

Based on some discussions with members from our community, we learned about several experiences where researchers have used the private URL in their article's data availability statement (instead of the DOI). We would like to stress the importance of using terminology that emphasizes the temporary nature of the URL, such as "temporary prepublish URL" or "prepublish preview URL".

**Comment by philippconzett** [comment]
We have had the same experience as @meghangoodchild describes - although we have emphasized for the depositors that they must replace the private URL with the DOI before the article is published. Right now, this is the case in a Nature article that was published several months ago and so far, we have not been able to make Nature replace the private URL with the DOI. As a result, we cannot publish the dataset, because that would cause the private URL to be deactivated and the dataset URL in the reference list of the article would thus no longer resolve.

Maybe you could include some explicit wording in the private URL feature that makes depositors aware of the importance of making sure that the dataset reference in the final article must contain the dataset DOI, not the private URL.

**Comment by jggautier** [comment]
@TaniaSchlatter agrees that the redesign of the feature name, the popup, banner messages, and relevant guide pages are done and can be moved to development when possible.

The changes are illustrated in mockups in [an image](https://user-images.githubusercontent.com/18374574/151025261-ed70e998-9341-4013-9e0f-3c1d4d2c83e4.jpg) and in [a section of a virtual whiteboard](https://miro.com/app/board/o9J_leCZVUU=/?moveToWidget=3074457366769811849&cot=14). They include changes to:
- The name of the feature in the Edit Dataset dropdown on the dataset page
- Changes to the text, layout, and interaction of the feature's popup
- Changes to the text of the "Disable URL" confirmation popup
- Changes to the name of feature in the URL (e.g. `previewurl` in `https://demo.dataverse.org/previewurl.xhtml?token=39b07d51-e0aa-4a89-a179-cacd63c94d72`)
- Changes to banner messages shown when using the feature

The changes to the guide pages - pages in the User, API, Installation, Developer and Style guides - are in the Google Doc at https://docs.google.com/document/d/1bn4fIPr_yhOj_DYDldzdKEZjmETV-WLYc98sWTgcg58

The change to the name of the feature will require changes to the names of associated code files, e.g. PrivateUrlUtil.java

**Comment by mreekie** [comment]
Worked on by
-  Tania
- Julian

**Comment by scolapasta** [comment]
Removing information about the Dataverse collection should be relatively straight forward to not render (would have to see how it looks), i.e. don't show the dataverse collection header, don't show breadcrumbs.

Repository name can't be hidden as it's part of the URL.

Currently not sure about the past versions - since I'm not sure if the persistent ID is exposed in this; if it is, then an end user could use that to find the dataset. If it's not, then we should be able to not render the version tabs.

**Comment by sbarbosadataverse** [comment]
From the comments on Jan 25, 2022:
This task needs review (@scolapasta_: "Changes to the text, layout, and interaction of the feature's popup"

**Comment by sbarbosadataverse** [comment]
> Removing information about the Dataverse collection should be relatively straight forward to not render (would have to see how it looks), i.e. don't show the dataverse collection header, don't show breadcrumbs.
> 
> Repository name can't be hidden as it's part of the URL.
> 
> Currently not sure about the past versions - since I'm not sure if the persistent ID is exposed in this; if it is, then an end user could use that to find the dataset. If it's not, then we should be able to not render the version tabs.

@jggautier can you review Gustavo's feedback on how we can hide collection level information for this feature, to use in the HDV? What other collection level information should be hidden? We need to test to see if any other info would be visible to a reviewer.

**Comment by sbarbosadataverse** [comment]
> From the comments on Jan 25, 2022: This task needs review (@scolapasta_: "Changes to the text, layout, and interaction of the feature's popup"

@jggautier can you explain further what this particular change would fix?

**Comment by scolapasta** [comment]
So reviewing with @qqmyers it does seem that anonymos peer review can only happen for initial drafts - which means there are no previously published versions. That means there's no code/logic to worry about there, but also that the suggested popups above don't even need to mention previous versions in that case.

**Comment by jggautier** [comment]
The changes are meant to:
- Help depositors be aware that reviewers might figure out who they are based on the name of the repository and the name of the Dataverse collection that the dataset is deposited in
- Help depositors be sure about the differences between the "Private URL" and "Anonymous Private URL". We wrote more about this in https://github.com/IQSS/dataverse/issues/8185
- Encourage depositors to use the PID when citing the dataset, instead of using the private URL
- Make depositors aware that their files are not being anonymized or changed in any way

I didn't know that anonymous peer review is available only for initial drafts of the dataset, but that's great!

**Comment by adam3smith** [comment]
So this is only changes the guidance, correct? I think changes look good and worthwhile, though ime you shouldn't expect big effects on user behavior from any written text.

**Comment by jggautier** [comment]
Yeah changes to text, and also the popup's layout and interaction

**Comment by sbarbosadataverse** [comment]
My next question is can we get this done and on the list of prioritization @scolapasta @jggautier 
Any blockers to the changes we need to make to have this work on HDV?

**Comment by qqmyers** [comment]
FWIW: The text proposed, at least as of https://github.com/IQSS/dataverse/issues/8184#issuecomment-1011170056 indicated that restricted files are not available with the anonymized preview URL - that is not currently the case. If this is desired, I suspect it may need to be an option (presumably some review requires looking at the restricted files?). #10403 is proposing to allow this in general (allowing users to be given the ability to view unpublished datasets but not restricted files), but that doesn't necessarily change how anonymized preview Urls work, so that would have to be handled somewhere. In any case, the text change here shouldn't include that unless/until the functionality is changed.
