### ISSUE TITLE
Some researchers unsure of difference between "Private URL" and "Anonymous Private URL"

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#8185]
While reviewing the "Anonymous Private URL" feature (https://github.com/IQSS/dataverse/issues/1724), members of the Harvard Dataverse Repository curation team saw that some researchers were unsure of the difference between the "Private URL" and the "Anonymous Private URL". In particular, one or more researchers weren't sure if the feature would let them share an anonymized version of the data in a dataset's data files.

The feature only removes from the page dataset metadata that the repository administrators have decided could reveal the dataset author's identity. The User Guides [mention this (item 4)](https://guides.dataverse.org/en/5.7/user/dataset-management.html#private-url-to-review-unpublished-dataset), and the popup includes a link that points to that section of the User Guides.

But it's unclear if most users will click on that link or if that User Guide section makes the purpose of the Anonymous Private URL clear enough.

**Comment by jggautier** [comment]
We tested a redesigned popup with 6 users. They were able to distinguish between the two types of URLs. (More about the review is described in [a comment in another Github issue](https://github.com/IQSS/dataverse/issues/8184#issuecomment-995879686).)

**Comment by jggautier** [comment]
@TaniaSchlatter agrees that the redesign of the feature name, the popup, banner messages, and relevant guide pages are done and can be moved to development when possible.

The changes are illustrated in mockups in [an image](https://user-images.githubusercontent.com/18374574/151025261-ed70e998-9341-4013-9e0f-3c1d4d2c83e4.jpg) and in [a section of a virtual whiteboard](https://miro.com/app/board/o9J_leCZVUU=/?moveToWidget=3074457366769811849&cot=14). They include changes to:
- The name of the feature in the Edit Dataset dropdown on the dataset page
- Changes to the text, layout, and interaction of the feature's popup
- Changes to the text of the "Disable URL" confirmation popup
- Changes to the name of feature in the URL (e.g. `previewurl` in `https://demo.dataverse.org/previewurl.xhtml?token=39b07d51-e0aa-4a89-a179-cacd63c94d72`)
- Changes to banner messages shown when using the feature

The changes to the guide pages - pages in the User, API, Installation, Developer and Style guides - are in the Google Doc at https://docs.google.com/document/d/1bn4fIPr_yhOj_DYDldzdKEZjmETV-WLYc98sWTgcg58

The change to the name of the feature will require changes to the names of associated code files, e.g. PrivateUrlUtil.java

**Comment by mreekie** [comment]
Discussion with Sonia:
For the harvard dataverse, we need to discuss and come up with a plan for how to make use of it's use in the Harvard repository.

If someone creates a collection, then this will expose information that should not be exposed.
So we need to either fix the feature, or make a policy of how this feature will be used.

This will need further discussion as to which approach to take.

**Comment by mreekie** [comment]
sizing:
- PM added to ordered sizing queue

**Comment by mreekie** [comment]
Sizing:
- The first step, the spike for getting input, is lacking an assigned person and it's not clear who would collect the information.
- Once requirements take shape, we will need dev requirements.

Discussion:
- What of changing the wording? Could that be a simple fix to change the context that it communicates?
-  This is one of 2 issues, The other issue is: https://github.com/IQSS/dataverse/issues/8184

**Comment by jggautier** [comment]
> What of changing the wording? Could that be a simple fix to change the context that it communicates?

Just refreshed my memory of the changes we proposed and yeah, we proposed changing the name of the feature from "Private URL" to "Preview URL". The Miro board at https://miro.com/app/board/o9J_leCZVUU=/?moveToWidget=3074457366769811874&cot=14 I think gives an overview of how the feature works now and the changes we proposed.

**Comment by cmbz** [comment]
**2023/10/02**
- @sbarbosadataverse and @jggautier will discuss over the next few weeks to decide next steps for implementing on Harvard Dataverse.
