### ISSUE TITLE
Search: Searching on a negative number returns a lot of false results.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#819]
Tested on 8/11/2014

I entered -160 in Geographic Bounding Box for West Longitude and -65 in North Latitude and got 122 results, which I find very unlikely. also, the cards did not show matches, whereas when I searched on 143 for East Longitude, it returned the dataset I was looking for.

**Comment by mheppler** [comment]
@kcondon and @pdurbin I am closing this issue, and consolidating it with other related issues in an old issue that I have retitled as _**Search: Accented characters, ampersands, negative numbers and other special characters #820**_.

If you have any further information about this bug or other "special character" related search issues, please add your comment there.
