### ISSUE TITLE
No PDF thumbnails when contained in ZIP

### ISSUE THREAD

**Issue by sergejzr** [IQSS/dataverse#8195]
**What steps does it take to reproduce the issue?**
Create/Edit a  dataset
Upload a zip file containing pdf files

* When does this issue occur?
always when uploading a zip file containing pdfs

* Which page(s) does it occurs on?
Upload preview page editdatafiles.xhtml
Data set view page: /dataset.xhtml

* What happens?
The thumbnail of the pdf file remains "unknown" whilst thumbnails for png files are generated and displayed correctly

* To whom does it occur (all users, curators, superusers)?
all users

* What did you expect to happen?

**Which version of Dataverse are you using?**

v. 5.4 build 413-ea91390

**Any related open or closed issues to this bug report?**
A general discussion on thumbnail improvements can be related: https://github.com/IQSS/dataverse/issues/6450

**Comment by pdurbin** [comment]
@sergejzr sorry for the slow reply. I'm a little surprised this doesn't work. When you get a minute, can you please try it at https://demo.dataverse.org ?

**Comment by sergejzr** [comment]
Turned out it was a general thumbnail creation problem. Solved in the meanwhile. Thank you!
