### ISSUE TITLE
Clarify what logs, output, and other info to send to support and/or community when installation fails

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#8198]
When I look at threads like https://groups.google.com/g/dataverse-community/c/VM-G3rf5iUE/m/X94Gw0H-BAAJ I'm reminded that we don't specify in the guides very clearly what logs, output, and other information can help support and/or the community troubleshoot when installation fails.

Off the top of my head, these are helpful (more ideas are welcome, of course):

- output from the installer (STDOUT, STDERR)
- scripts/api/setup-all.*.log files from the installer
- server.log from Payara
- OS and version (i.e. Rocky Linux 8.4)

We could add a new section under "Troubleshooting" about this:

![Screen Shot 2021-10-28 at 12 04 23 PM](https://user-images.githubusercontent.com/21006/139307549-a8a55508-5f8b-4305-bb95-6b7e670f8bff.png)

**Comment by djbrooke** [comment]
- We could also have the installer generate some unified records (different issue)
- This text would provide value for all versions, outside of the unified record
