### ISSUE TITLE
Search: Accented characters, ampersands, negative numbers and other special characters

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#820]
This was suggested by Eleni during discussions around search issues with accented characters. 

The suggestion is to allow searching both using the original accented characters and without, in those cases where a user may not have access to accented keyboard, etc.

**Comment by pdurbin** [comment]
@mheppler pointed out an interesting answer at http://stackoverflow.com/questions/16627062/not-able-to-search-spanish-word-with-accent-in-solr/20657529#20657529

Here it is in full (note downsides though):

You can try using the [ASCIIFoldingFilterFactory][1] filter.

It converts characters with ascent into their no-ascent counterpart.
Put this in your schema.xml:

    <filter class="solr.ASCIIFoldingFilterFactory"/>

*Note: The downside is that words like "cañon" and "canon" are now equivalent and both hit the same documents IIRC.*

  [1]: http://wiki.apache.org/solr/AnalyzersTokenizersTokenFilters#solr.ASCIIFoldingFilterFactory

**Comment by mheppler** [comment]
Dusted off this oldie but goodie to be a representative issue for many other search bugs/feature requests. I have closed the following issues, to consolidate them here, and moved over any pertinent information in their comments.

-  _**Search: Support searching on accented words by typing unaccented characters instead**_ (original title of this issue)
- _**Search: Searching on a negative number returns a lot of false results. #819**_ (`-160` in Geographic Bounding Box for West Longitude and `-65` for North Latitude, returns unexpected results, but `143` for East Longitude target dataset found)
- _**Search: characters in (dataset names) return zero results #2156**_ (search `População Estrangeira na Europa e no Mundo Nôvo (%) - 1870 - 2001` is broken in Harvard Dataverse, remove "%" and it returns results)
- _**Search: Text after and including Ampersand (&) is removed from Search Query #2702**_ (search `Economics & Politics` in Harvard Dataverse)
- _**Parameters issue in display on production #3993**_ ([example on Harvard Dataverse](https://dataverse.harvard.edu/dataverse/CMMR?q=&fq2=keywordValue_ss%3A%22Community+mobilization%2C+Female+sex+workers+%28FSWs%29%2C+HIV%2C+HIV+prevention%2C+India%2C+Risk%2C+Structural+factors%2C+Structural+interventions%3B++INSTITUTION%3A+American+University%3B+STRATEGIC+AREAS%3A+Behavioral+tracking+surveys%2C+Community+mobilization+in-depth+research%22&fq0=subtreePaths%3A%22%2F2711545%2F1630%2F1772%22&fq1=dvObjectType%3A%28dataverses+OR+datasets%29&types=dataverses%3Adatasets&sort=dateSort&order=))

**Comment by pdurbin** [comment]
@mheppler I'm still haunted by the bug report at https://github.com/IQSS/dataverse/issues/1928#issuecomment-104471953 that a search for "Experiment" found datasets with "Experience" but I haven't tested lately. That was nearly five years ago. 😄

**Comment by BPeuch** [comment]
We here in Belgium second this, as our three official languages – Dutch, French and German – all three contains special characters (á, à, â, ç, é, è, ê, ë, í, ó, ö, ú, ù, û, ü…).

Here is an illustration of how accented characters can hinder the search for / the discovery of datasets:

![freq1](https://user-images.githubusercontent.com/15209224/95757974-203f7200-0ca8-11eb-8f01-ec5db413b971.png)

———————————————————————————————————————————————

![freq2](https://user-images.githubusercontent.com/15209224/95757989-23d2f900-0ca8-11eb-8569-1065b5d0f85c.png)

**Comment by pdurbin** [comment]
@BPeuch in a report from a French installation, switching from text_en to text_fr seems to have helped: https://groups.google.com/g/dataverse-community/c/9sjpBpPRuFk/m/uxH2KKJnAQAJ

Since you have three official languages, however, I'm not sure if this will work for you.

**Comment by BPeuch** [comment]
That's valuable information still. Thank you, @pdurbin!

**Comment by qqmyers** [comment]
FWIW:  For QDR, we addressed some of this with changes in the solr schema.xml leveraging some filters:
solr.WordDelimiterGraphFilterFactory
solr.ASCIIFoldingFilterFactory
solr.PatternReplaceFilterFactory

I can dig up that code if it's helpful - I don't know much about solr so I think what we did was mostly to cut/paste from sources I found on the web though, so you might be better off searching for the latest on this issue - perhaps including some of those filter names. (Our interest was primarily in handling characters from other languages and contractions, so it may not be as general as others might want.)

One thing I think is helpful to convey though - I think this can be solved/significantly improved just making solr changes ,versus requiring Dataverse code changes. So looking for answers related to solr or solr expertise at our institutions might be a good approach.

**Comment by qqmyers** [comment]
FWIW: QDR's solution can be seen in https://github.com/QualitativeDataRepository/dataverse/blame/develop/conf/solr/7.7.2/schema.xml - see the qqmyers changes starting from https://github.com/QualitativeDataRepository/dataverse/blame/develop/conf/solr/7.7.2/schema.xml#L573.
The main  thing for non-ASCII characters was to enable the solr.ASCIIFoldingFilterFactory filter during indexing and querying. We also used the solr.PatternReplaceFilterFactory filter to try to recognize contractions (e.g. qu'est que) - you can see from the pattern there that this is fairly limited. The use of the solr.ASCIIFoldingFilterFactory is probably generic and could be pulled into a separate PR if there's interest in having it as the default for the community.

(You'll also see some modifications to the solr.WordDelimiterGraphFilterFactory params - I think those are related to file names containing numbers - basically an unrelated but also potentially useful change).

**Comment by poikilotherm** [comment]
This might be linked to #6675 and #7375.
