### ISSUE TITLE
Request for Help with "Make Data Count"

### ISSUE THREAD

**Issue by ghost** [IQSS/dataverse#8221]
Hi

I have setup dataverse 5.5 using this docker-compose file https://github.com/IQSS/dataverse-docker/blob/master/docker-compose.yml

However, I can't get the Dataset Metrics to work. It shows 0 on 2 Nov even though I have viewed & downloaded the dataset a few times on 1 Nov before and after I ran the steps below to enable the dataset metrics.
![image](https://user-images.githubusercontent.com/93647724/140037822-6cd468b8-5c08-4995-b1e8-1fd5eb206c83.png)

I have followed these steps to enable the dataset metrics on 2-nov-2021:
curl -X PUT -d '/usr/local/payara5/glassfish/domains/domain1/logs/mdc' http://localhost:8080/api/admin/settings/:MDCLogPath
curl -X PUT -d 'true' http://localhost:8080/api/admin/settings/:DisplayMDCMetrics

cd /usr/local
wget https://github.com/CDLUC3/counter-processor/archive/v0.0.1.tar.gz
tar xvfz v0.0.1.tar.gz

useradd counter
chown -R counter:counter /usr/local/counter-processor-0.0.1

cd /usr/local/counter-processor-0.0.1
download GeoLite2-Country_20211026.tar.gz from maxmind.com
tar xvfz GeoLite2-Country_20211026.tar.gz
cp GeoLite2-Country_*/GeoLite2-Country.mmdb maxmind_geoip

wget https://guides.dataverse.org/en/latest/_downloads/f99910a3cc45e4f68cc047f7c033c7f0/counter-processor-config.yaml
set year_month to 2021-11 in  counter-processor-config.yaml

touch /usr/local/payara5/glassfish/domains/domain1/logs/mdc/counter_2021-11-01.log

CONFIG_FILE=counter-processor-config.yaml python3 main.py

curl -X POST "http://localhost:8080/api/admin/makeDataCount/addUsageMetricsFromSushiReport?reportOnDisk=/tmp/make-data-count-report.json"

setup cron to run counter_daily.sh
crontab -e 
01 00 * * * sh /usr/local/counter-processor-0.0.1/counter_daily.sh 

On 3 Nov, I view and download the dataset a few times again. however, on 4 nov, I'm still getting 0 for the dataset metrics.  When I went to check /usr/local/payara5/glassfish/domains/domain1/logs/mdc/, I only see counter_2021-11-01.log but the cron job didn't produce any log for even 3 Nov. 

Can anyone advise if I have done any step wrong or miss out anything? 

Thank you very much.

**Comment by pdurbin** [comment]
@debug1g back when you opened this issue I saw a lot of back and forth on this issue as well:

- https://github.com/GlobalDataverseCommunityConsortium/dataverse-previewers/issues/62

Are you still having trouble with Make Data Count? Have you tried setting it up outside of dataverse-docker (which is community supported).

**Comment by pdurbin** [comment]
Closing because the the GitHub account that created this issue has been deleted:

> Hi, I'm @ghost! I take the place of user accounts that have been deleted. 👻
