### ISSUE TITLE
Empty dropdown under "Account Information" button for Shib users

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#8223]
**What steps does it take to reproduce the issue?**

- Log into https://demo.dataverse.org with Institutional Login (Shibboleth)
- Go to Account page.
- Click "Account Information" button
- Observe empty dropdown (screenshot below)

**To whom does it occur (all users, curators, superusers)?**

All users.

**What did you expect to happen?**

I'm pretty sure that previously the "Account Information" button shouldn't appear at all? 

**Which version of Dataverse are you using?**

Dataverse 5.8 but I'm seeing the same on Dataverse 5.6.

**Screenshots:**

![Screen Shot 2021-11-08 at 12 00 56 PM](https://user-images.githubusercontent.com/21006/140786087-c92878ec-6a4a-4383-a9ae-a8902b3fb855.png)

Thanks to @PaulBoon for noticing this!

**Comment by PaulBoon** [comment]
Tanks for creating this issue @pdurbin. This problem was discovered by Tim Warbout, a user of DataverseNL, so all credits for finding it go to him.

**Comment by donsizemore** [comment]
@pdurbin Just a note that I've reproduced this on 5.3:
![Screen Shot 2021-11-24 at 11 08 23](https://user-images.githubusercontent.com/12831666/143274164-a51cd40c-e9f6-4574-87b3-52791494bd78.png)

The Payara log is quiet as I'd expect; Firefox's browser console not so much:

```
Attempt to override an existing term: "brand-shorter-name". branding/brand.ftl
Attempt to override an existing term: "brand-short-name". branding/brand.ftl
Attempt to override an existing term: "brand-full-name". branding/brand.ftl
Attempt to override an existing term: "brand-product-name". branding/brand.ftl
Attempt to override an existing term: "vendor-short-name". branding/brand.ftl
Attempt to override an existing message: "trademarkInfo". branding/brand.ftl
[Exception... "Favicon at "https://sso.unc.edu/favicon.ico" failed to load: Forbidden."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource:///modules/FaviconLoader.jsm :: onStopRequest :: line 253"  data: no] FaviconLoader.jsm:253:22
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “'unsafe-inline'” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “https:” within script-src: ‘strict-dynamic’ specified
Content Security Policy: Ignoring “http:” within script-src: ‘strict-dynamic’ specified
```

**Comment by pdurbin** [comment]
Before making any changes, as of 5.10.1, here what a builtin user and a shib user see:

## Builtin user (dropdown to edit account or password)

![Screen Shot 2022-04-08 at 2 33 35 PM](https://user-images.githubusercontent.com/21006/162501208-e2b6aeb6-a7af-4e82-a5aa-d9febe45d103.png)

## Shib user (weird broken dropdown)

![Screen Shot 2022-04-08 at 2 35 38 PM](https://user-images.githubusercontent.com/21006/162501402-0452b64f-437c-4aa8-880d-0d85eeebc0f3.png)

**Comment by pdurbin** [comment]
In this pull request, I removed the weird empty "Account Information" popup:

- #8579
