### ISSUE TITLE
Feature Request/Idea: Allow the Deletion of Auxiliary Files via API

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#8235]
**Overview of the Feature Request**
Currently the Dataverse API includes endpoints to **add** or **download** Auxiliary Files as described in the documentation: https://guides.dataverse.org/en/latest/developers/aux-file-support.html

However, there is no way to **delete** an auxiliary file that is accidentally or incorrectly added. Please add an API endpoint to remove an existing auxiliary file.

**What kind of user is the feature intended for?**
An API User who has permissions to add auxiliary files

**What inspired the request?**
Testing with a Dataverse-integrated application prompted the request after duplicate auxiliary files were added as well as an incorrectly formatted auxiliary files. As these are auxiliary files we did not consider them falling under the same category as regular data files--which would need to be formally de-accessioned.

**Comment by djbrooke** [comment]
Thanks @raprasad - per #7820 it sounds like @qqmyers has some code for this, we will just need to get into a PR, review, and test.

**Comment by qqmyers** [comment]
FYI: I've implemented this in the QDR fork and it should mostly be a matter of making a PR.
