### ISSUE TITLE
Help users creating a guestbook, including how to download results

### ISSUE THREAD

**Issue by TaniaSchlatter** [IQSS/dataverse#8244]
This issue for text-only changes is to improve help for API users, Depositors, and Curators when creating guestbooks. It will be most helpful for self-deposit users (Harvard Dataverse), and is likely to add context for less frequent and new users.

1. Provide a link to the user guide (https://guides.dataverse.org/en/5.8/user/dataverse-management.html#dataset-guestbooks) when creating [, editing] and selecting a guestbook. The app contains links to guides in other cases.  

2. Add a link to the API for downloading guestbook data (https://guides.dataverse.org/en/5.8/api/native-api.html#) to the section on guestbooks in the user guides, so it is more complete.

~~3. Add text in the UI when creating and selecting a guestbook that links to the guides.~~

~~4. Add API link as specified in https://github.com/IQSS/dataverse/issues/8244#issuecomment-970696251~~

5. Add a download button on the create guestbook page so the person does not need to go to the responses page to see the button (since the responses page can take a long time to load if there are many... responses)

**Current screens**
When creating a new guestbook, editing a dataverse collection:
![Screen Shot 2021-11-16 at 2 27 05 PM](https://user-images.githubusercontent.com/15386424/142053705-cd0d0684-8212-4982-adf0-e15897dc54ad.png)

![Screen Shot 2021-11-16 at 2 27 32 PM](https://user-images.githubusercontent.com/15386424/142052360-93c2f05c-0154-4bee-b9d9-a0e652449d27.png)

When selecting a guestbook for a dataset:
![Screen Shot 2021-11-16 at 11 36 33 AM](https://user-images.githubusercontent.com/15386424/142053158-49f0a2e3-d3dc-4364-b114-2083b89cc630.png)

**Comment by pdurbin** [comment]
@TaniaSchlatter just a heads up in case you or others aren't aware that there is some explanatory text (screenshot below) about guestbooks visible in the app. I'm not sure but this may only show when there are no guestbooks at the root level.

![Screen Shot 2021-11-16 at 3 33 38 PM](https://user-images.githubusercontent.com/21006/142061642-577d0cee-954d-4e4e-85ce-0351daa54545.png)

**Comment by sbarbosadataverse** [comment]
Once you create a guestbook, that text disappears when you go back to the guestbook feature, fyi

**Comment by djbrooke** [comment]
- If we add a link to download on the create guestbook page, the user could more easily get to the responses - if they don't have to go to the responses page to access the download button and they would not have a bad experience
