### ISSUE TITLE
Shibboleth repo changes ahoy

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#8259]
With the v3.3.0 announce, the Shibboleth project notes:

> we have changed the set of Linux platforms by dropping SUSE (which has its own packages) and adding Rocky and Amazon Linux.

Dataverse guides point would-be Shibbolizers (Shibbolethizens?) at download.opensuse.org, but the Shibboleth project now provides repos here: https://shibboleth.net/downloads/service-provider/RPMS/

Note that they currently point RHEL8 users at the CentOS8 repo, but their CentOS8 repo is going away next month when CentOS8 reaches EOL. It is yet unclear to me how the CentOS8 and Rocky8 repos differ.

This is a place-holder issue to accompany a documentation pull request once we collectively decide what should be done.

**Comment by pdurbin** [comment]
@donsizemore I know this is related...

- #8405

... and was closed by

- #8406

Is there still more to do? Are we done? 😄 Please forgive my ignorance.
