### ISSUE TITLE
GeoJSON files marked as "Unknown"/"application/octet-stream"

### ISSUE THREAD

**Issue by kaitlinnewson** [IQSS/dataverse#8261]
Hi Dataverse team,

I'm reporting this issue as I've developed a file previewer for GeoJSON files, but don't believe we can use it without being able to enable it for this specific content type, and in order to do that, GeoJSON files need to be individually identified. Hoping this is possible!

**What steps does it take to reproduce the issue?**

1. Upload a GeoJSON file to Dataverse
2. View the file type, which is "Unknown" in the UI
3. In the API, in the files list the content type for the file is "application/octet-stream". [Here's an example from the Harvard DV](https://dataverse.harvard.edu/api/datasets/:persistentId/?persistentId=doi:10.7910/DVN/YQX0SW).

**When does this issue occur?**

When uploading GeoJSON files.

**What happens?**

After uploading a GeoJSON (.geojson) file to Dataverse, the file type displayed in the UI is "Unknown". Through the API, I can see the content type being set as "application/octet-stream". I have checked older files and also uploaded a few geojson files to the Harvard demo (v 5.8). [Here's an example of a GeoJSON file in the Harvard DV](https://dataverse.harvard.edu/file.xhtml?persistentId=doi:10.7910/DVN/YQX0SW/GLBKGD&version=1.0).

**To whom does it occur (all users, curators, superusers)?**

All users

**What did you expect to happen?**

The MIME type should be "application/geo+json". I'm hoping it's possible to detect this (as opposed to it being marked as "application/json" or "text/plain").

**Which version of Dataverse are you using?**

5.1/5.8

**Comment by djbrooke** [comment]
Hey @kaitlinnewson, really exciting to hear about the previewer. 

If you're interested, I think a PR similar to https://github.com/IQSS/dataverse/pull/7502 would do the trick. If you'd be interested in making this PR, I can have someone more technical than me confirm that this is the correct path.

**Comment by pdurbin** [comment]
@kaitlinnewson hi! As a workaround, you can set the content type. Check this out from https://guides.dataverse.org/en/5.8/api/native-api.html#add-a-file-to-a-dataset

> Please note that it’s possible to “trick” a Dataverse installation into giving a file a content type (MIME type) of your choosing. For example, you can make a text file be treated like a video file with -F 'file=@README.txt;type=video/mpeg4', for example. If the Dataverse installation does not properly detect a file type, specifying the content type via API like this a potential workaround.

A better, longer term solution is to add `.geojson` to the list of file extensions Dataverse knows about. A pull request would touch these two files:

- src/main/java/propertyFiles/MimeTypeDisplay.properties
- src/main/java/propertyFiles/MimeTypeFacets.properties

If you'd like to make a pull request, you can model it off pull request #7502.

**Comment by djbrooke** [comment]
@pdurbin I'll take that as a confirmation... :) Thanks!

**Comment by kaitlinnewson** [comment]
Thanks for your guidance @djbrooke and @pdurbin! Hopefully my PR does the trick. 

Here's a sneak preview of the new previewer:

![Screen Shot 2021-11-30 at 2 11 28 PM](https://user-images.githubusercontent.com/6903515/144118042-64175688-782e-4fe1-b192-765246a6d70b.png)
