### ISSUE TITLE
Analytics: Button tracking broken in some cases

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#8263]
"Can you add an issue - looks like mheppler changed the analytics-code.html example a couple years back and, with the change, the button tracking only works for the file edit mode (haven't checked) but not for the file table in view mode."

**Comment by qqmyers** [comment]
Will revert the bad commit in a PR... - basically the more refined selector that was added only works in edit mode and doesn't catch button clicks in the view mode.
