### ISSUE TITLE
Google Analytics: Button Tracking Code not working for inline file download button

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#8280]
https://guides.dataverse.org/en/5.8/installation/config.html?highlight=button%20tracking

In a Dataverse installation, these events include file downloads, requesting access to restricted data, exporting metadata, social media sharing, requesting citation text, launching external tools, contacting authors, and launching computations

This is working for the table wide download button but not the individual file, inline button.

A review of the other events might be in order.

Current production screenshots of some existing events:
<img width="1364" alt="Screen Shot 2021-12-06 at 10 50 04 AM" src="https://user-images.githubusercontent.com/4983816/144886598-4d5e3ac5-6e26-4089-a499-30d44d5d89f7.png">
<img width="1015" alt="Screen Shot 2021-12-06 at 11 27 58 AM" src="https://user-images.githubusercontent.com/4983816/144886600-c3fdb50a-00e6-4b99-b0b7-ff7ecddfdfe9.png">

**Comment by qqmyers** [comment]
Which button isn't working? From the images above, I would have thought the 'MS Word', "Adobe PDF", etc. entries are from using the download kebab in the file table. Is that not working? Or is it something else. (At QDR, I just checked that, with #8274, I do see events from the file table kebab menu on the Dataset page. FWIW: I did not see them when I was coming from a machine using a VPN .)

**Comment by qqmyers** [comment]
Ah - it wasn't a VPN issue - I had an anti-tracker app in Chrome. Turning it off allowed Google to track the button hits. With the tracker on, I see `data.qdr.syr.edu/:4 GET https://www.googletagmanager.com/gtag/js?id=UA-XXXXXXX net::ERR_BLOCKED_BY_CLIENT` in the Chrome console.

**Comment by kcondon** [comment]
@qqmyers I tested against our prod above and what appeared to happen is downloading with the download button, where you check which files you want works but choosing the download next to a particular file did not appear to trigger a Google Analytics event in prod.

**Comment by kcondon** [comment]
It looks like I'll need to go over this in more detail just to be clear/sure. It sounds like this is now working for you with the latest reverted branch?

**Comment by qqmyers** [comment]
dataverse.harvard.edu is currently using the analytics-code.html file from before #8274. It has to be updated on that machine.

**Comment by kcondon** [comment]
Thanks, all events appear to be working on test, see screen shot, will update in prod:
<img width="1346" alt="Screen Shot 2021-12-06 at 1 35 27 PM" src="https://user-images.githubusercontent.com/4983816/144902953-078256ec-cbf4-4122-a291-fc2750742ac5.png">

**Comment by kcondon** [comment]
OK, confirmed this code works in test, updated prod and confirmed inline download event now recorded. Closing.
