### ISSUE TITLE
Template: editing and "Existing" template should allow the drop down to clearly display the edit options for "metadata" or "terms"

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#8281]
When editing an existing template, the dropdown arrow next to the edit option doesn't properly display for viewing the two edit options available. The two options are hidden unless you scroll the page:

<img width="2104" alt="Screen Shot 2021-12-06 at 1 06 07 PM" src="https://user-images.githubusercontent.com/8322346/144898675-5b90c7ea-8544-4e53-bb12-6ef1c1f90109.png">
<img width="2215" alt="Screen Shot 2021-12-06 at 1 06 13 PM" src="https://user-images.githubusercontent.com/8322346/144898677-b83a3e41-c323-48eb-a4e9-45bdb796e692.png">

**Comment by djbrooke** [comment]
- Could be a z-index issue

**Comment by qqmyers** [comment]
@sekmiller - The thing I found that seems to work is to add 
```
#manageTemplatesForm\:allTemplates .ui-datatable-tablewrapper {
    overflow: visible;
}
``` to the structure.css file. I haven't checked to see if there are side effects, but that allows the 'Edit Template' drop down to show.
