### ISSUE TITLE
Feature Request/Idea: Make the 'Embargoed' tag applied to embargoed files be visible in the dataset's table of files

### ISSUE THREAD

**Issue by mdmADA** [IQSS/dataverse#8283]
**Overview of the Feature Request**
When one or more files in a dataset is embargoed and when viewing the dataset.xhtml page, the 'Embargoed' tag is applied to the dataset but there is no indication of which files in the dataset are embargoed. The user doesn't know until they click on the file command link to see the italicised 'Embargoed' in the drop down list, or if they go to the file.xhtml page for that file (where the 'Embargoed' tag is visible). They would then have to click on each individual file to figure out those that are embargoed. 

Seeing the dataset is embargoed with no indication of which files are embargoed may lead a user to think that the whole dataset or all files are embargoed when that may not be true.

Also, and maybe this should be logged as a bug, if a user clicks the 'Files' in the left-menu bar (Dataverses, Datasets, Files checkboxes) to select only files, every file, embargoed or not, in a dataset that has at least one embargoed file has the tag 'Embargoed' applied to in the files list.

**What kind of user is the feature intended for?**
(Example users roles: API User, Curator, Depositor, Guest, Superuser, Sysadmin)
All users

**What inspired the request?**
Not being able to tell at a glance of the dataset which files are embargoed and having to click through each to find those that are.

**What existing behavior do you want changed?**
Show users which files are embargoed when they are viewing the dataset.

**Any brand new behavior do you want to add to Dataverse?**
No.

**Any related open or closed issues to this feature request?**
Not sure.

**Comment by pdurbin** [comment]
@mdmADA sorry for the super slow reply. I agree and so does @DS-INRA who opened this issue later:

- #9678

I ended up adding a bunch of screenshots to that issue so I'm closing this in favor of that one. I hope you don't mind!
