### ISSUE TITLE
Feature Request/Idea: Change the language of facets in the search API

### ISSUE THREAD

**Issue by bappun** [IQSS/dataverse#8286]
**Overview of the Feature Request**
I would like to be able to get the facets in different languages directly in the API. Maybe by adding a language parameter to the request?

**What kind of user is the feature intended for?**
(Example users roles: API User, Curator, Depositor, Guest, Superuser, Sysadmin)
API User

**What inspired the request?**
Integration of Dataverse search API in another website using javascript.

**What existing behavior do you want changed?**
The translation of facets in the search API.

**Any related open or closed issues to this feature request?**
#8287

**Comment by qqmyers** [comment]
@bappun - see the PR for some limits on what I was able to do in one PR/on current funds. It should allow API calls using translated terms to work, though you do need to search against the field (e.g. subject) rather than the special facet field (subject_ss).

**Comment by bappun** [comment]
@qqmyers 

We upgraded our [instance](https://data.sciencespo.fr/) to 5.10.1 but we are not able to search for the translated value.

I get no results when I search for `topicClassValue:Elections` (EN) or `topicClassValue:Élections` (FR) instead of `topicClassValue:Politics.Elections`/`topicClassValue_ss:Politics.Elections` (original value from the TSV).

Is there something we need to do to index the translated properties? We restarted payara and also did a reexportAll at the end of the upgrade.

**Comment by qqmyers** [comment]
Yes, a reindex would be required. (The 5.10 release includes Additional Release Steps: Solr Upgrade which includes doing a reindex all. Reindexing wasn't listed as a separate step due to that.)

**Comment by qqmyers** [comment]
Ergh! We must have only tested with multivalue fields? In any case, I think there's a simpler fix - just change the schema.xml line for any single-valued CVV field to have multiValued="true" - i.e. [this line for samplingProcedure](https://github.com/IQSS/dataverse/blob/f2bd5598f246271d2726864c59afdaa1b4eb020d/conf/solr/8.11.1/schema.xml#L361) . You'll probably have to restart solr and reindex after that change. This allows multiple values in solr but doesn't allow the user to add multiple entries in the UI.

Pleas submit an issue as this is something where we need to update the default schema for any fields in the standard blocks and the update schema script.

**Comment by bappun** [comment]
Thank you! We changed to true for our CVV fields and the reindex worked. I will create the issue.
