### ISSUE TITLE
Support for Integration With ORCID via API

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#829]
Now that we support users entering their ORCID ID at the Dataset Author level we can look into more closely integrating with ORCID using their API http://support.orcid.org/knowledgebase/articles/116874-orcid-api-guide

**Comment by eaquigley** [comment]
List of open code available for APIs with ORCID: http://members.orcid.org/api/code-examples

**Comment by eaquigley** [comment]
FRD for this has been worked on by @suenjedt and myself. Link here: https://docs.google.com/document/d/1bAkeEF72MBpy8AHEABasc8SO2RcRmhnQ9D71pXGjkkI/edit?usp=sharing

**Comment by mcrosas** [comment]
This becomes even more relevant with the recent news: 
http://blog.datacite.org/auto-update-has-arrived/

Note in particular:
Publishers and data centers. These organizations also have two things to do: (1) collect ORCID identifiers during the submission workflow, using a process that involves authentication (not a type-in field!), and (2) embed the iD in the published paper and include the iD when submitting information to Crossref or DataCite.

**Comment by posixeleni** [comment]
Sent by @mcrosas 
The approach that DataCite follows for DataCite integration with ORCID is very nice: http://blog.datacite.org/announcing-datacite-profiles-service/

**Comment by pdurbin** [comment]
An interesting description of ORCID integration: https://www.editorialmanager.com/robohelp/12.2/Editorial_Manager_Help/Single_Sign-on_via_ORCID.htm

**Comment by mcrosas** [comment]
That's useful. ORCID as a SIngle-Sign-On provider is now one the
requirements for Phase 2 Dataverse remote authentication.

**Comment by nniiicc** [comment]
For clarification -  is Phase 2 DV related to development milestones or some larger roadmap ?

**Comment by pdurbin** [comment]
@nniiicc hi, @mcrosas was referring to the Remote Authentication Business Requirements Document (BRD) at https://docs.google.com/document/d/1vcAmo2nkFYavAr7OwwXzxM0IFQbkRZYZrrX43q-wqGE/edit?usp=sharing which differentiates between "phase 1" (pull request #3025) and "phase 2" (future work). She's basically saying that we're aware that ORCID can be used as an identity provider but that supporting this within Dataverse is outside the scope of phase 1, which is currently underway and being summarized for the community in this thread I started on the mailing list: https://groups.google.com/d/msg/dataverse-community/pTmHCBVRE3o/rASPXMJCFAAJ

**Comment by nniiicc** [comment]
@pdurbin thanks for the clarification - much appreciated.

**Comment by kcondon** [comment]
This is already being considered.

**Comment by pdurbin** [comment]
The specific feature of users being about to login to Dataverse via an ORCID (using OAuth) is being tracked at #3338. Existing login options for Dataverse include local accounts and Shibboleth.

**Comment by djbrooke** [comment]
I'm going to close this in favor of #3338.
