### ISSUE TITLE
Customization "footer" image: "spinning" icon continues, can still save changes

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#8297]
The spinning icon doesn't resolve. You can still select save and upload the image

<img width="1737" alt="Screen Shot 2021-12-08 at 2 26 44 PM" src="https://user-images.githubusercontent.com/8322346/145271839-cf74093d-82e6-49a4-ab39-46ef753a7edc.png">
.

**Comment by pdurbin** [comment]
When I was investigating #8249 I noticed the same behavior (spinning icon) with "Logo Image":

<img width="952" alt="Screen Shot 2021-12-08 at 3 52 31 PM" src="https://user-images.githubusercontent.com/21006/145282687-89cbd518-fd3b-4fec-bb44-92eaded7c186.png">
