### ISSUE TITLE
API: Pretty print JSON responses

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#830]
Many RESTful APIs such as GitHub's pretty-print the JSON response, indenting it so it's readable.

For efficiency, `javax.json` (Jersey) does _not_ pretty print JSON. One workaround looks something like this...

```
@GET
@Path("stuff")
public Response getStuff(@QueryParam("pretty") boolean pretty) {
    JsonArrayBuilder stuff = Json.createArrayBuilder().add("foo").add("bar");
    JsonObject jsonObject = Json.createObjectBuilder()
            .add("status", "OK")
            .add("data", stuff).build();
    if (pretty) {
        Map<String, Boolean> config = new HashMap<>();
        config.put(JsonGenerator.PRETTY_PRINTING, true);
        JsonWriterFactory jwf = Json.createWriterFactory(config);
        StringWriter sw = new StringWriter();
        try (JsonWriter jsonWriter = jwf.createWriter(sw)) {
            jsonWriter.writeObject(jsonObject);
        }
        // return "Content-Type: application/json", not "text/plain"
        MediaType mediaType = MediaType.APPLICATION_JSON_TYPE;
        return Response.ok(sw.toString(), mediaType).build();
    } else {
        return Response.ok(jsonObject).build();
    }

}
```

... but a better way suggested by @michbarsinai is to add a pretty-printing filter per http://docs.oracle.com/javaee/7/tutorial/doc/servlets006.htm

Perhaps by default the JSON would continue to be non-pretty for performance and efficiency but the the pretty-printing filter could be enabled with a config option.

**Comment by pdurbin** [comment]
> pretty-print could also be used for examples in the documentation (embedded in the APIs guides)

I manually pretty-print the example JSON output at http://guides.dataverse.org/en/latest/api/search.html so that it's readable.

**Comment by pdurbin** [comment]
I have a need to pretty print JSON while working on #2579 for debugging purposes (so I can actually read the JSON) so I created a method for this at 2e75546 because from what I could tell my previous code for pretty printing JSON was deleted as part of fa26ec8fdc48c080d7f42f49bce3b1bff008eedf . The methods are different and this time I wrote tests so I'm happier with the new method. If I'm duplicating effort, please let me know.

**Comment by michbarsinai** [comment]
My objection to doing this on the server side if not because of effort duplication. The problem is the unbounded contiguous memory allocation that this feature requires, and the fact that it's easy to do on the client side with jq or (my new favorite) HTTPie (https://github.com/jkbrzt/httpie <https://github.com/jkbrzt/httpie>). Client-side solution also gets you syntax coloring.

As long as it's not public API, that's fine. 

If we need this on a public API, I'd go with a web filter, and put some effort into implementing this in a stream, not a string.

**Comment by pdurbin** [comment]
@michbarsinai my use case is pretty printing the JSON in the Glassfish logs: https://github.com/IQSS/dataverse/commit/9b04e1af00520f0442d8ca5bf1bbfc150e046665#diff-a921aa2648ecc0764975a817168935fbR32 . It's for development, for now. I'm probably commenting on the wrong issue since this one is about what we expose via the API but we have enough issues and I didn't want to create a new one about pretty printing JSON for debugging purposes. Mostly I made the comment so someone like you or @ekraffmiller or whoever else can say, "hey, we already have a method for this and it's over here." :)

**Comment by michbarsinai** [comment]
You need to try  HTTPie, man. Literally go:

    http GET localhost:///// <localhost://///>/


and you get the colors for free :-)

**Comment by pdurbin** [comment]
@michbarsinai ok, I brew installed it. It doesn't help with my use case but it's a nice tool. Thanks. :)

**Comment by pdurbin** [comment]
I think this would be a very nice and low-hanging-fruit feature but users aren't exactly clamoring for it so I vote we close it until there's actual user demand.

**Comment by pdurbin** [comment]
No one seems to want this but me so I guess I'll close this issue.
