### ISSUE TITLE
Backup-Error  "No time stamp! first run (or a full re-run)  " 

### ISSUE THREAD

**Issue by linsherpa** [IQSS/dataverse#8307]
during backup the FILE "run_backup.py" shows the following error:
.../scripts/backup/run_backup/run_backup.py", line 25
    print "No time stamp! first run (or a full re-run)."

**What steps does it take to reproduce the issue?**

* When does this issue occur?

* Which page(s) does it occurs on?

* What happens?

* To whom does it occur (all users, curators, superusers)?

* What did you expect to happen?

**Which version of Dataverse are you using?**

**Any related open or closed issues to this bug report?**

**Screenshots:**

No matter the issue, screenshots are always welcome.

To add a screenshot, please use one of the following formats and/or methods described here:

* https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests
*

**Comment by pdurbin** [comment]
@linsherpa any news on this? Still broken? Working? Please note at this script is experimental, as mentioned at https://guides.dataverse.org/en/5.11.1/admin/backups.html

If you get it working, please make a pull request!

**Comment by pdurbin** [comment]
@linsherpa nice meeting you in Braga! Great talk! I'm closing this but if you're still having trouble, please get in touch!
