### ISSUE TITLE
Support for SPSS Portable Files with Labels (Odum)

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#831]
From Odum:  Label correction feature is a required feature for us. If not we have to manually edit the database to correct the truncated labels.

The issue is that SPSS truncates variable labels at set number. Some of ours are paragraph long.

**Comment by landreev** [comment]
This is done and should be working... 
But maybe before we spend too much testing this, I should get a real-life file from Odum; just to make sure we are testing the right thing.

**Comment by landreev** [comment]
OK, should be working. 
Real life test files still available in the original redmine ticket: 
https://redmine.hmdc.harvard.edu/issues/2033

**Comment by kcondon** [comment]
OK, long labels are working. Closing.
