### ISSUE TITLE
API endpoint to fix missing datafile checksums

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#8311]
Have mercy on my plight, IQSS:

```
select count(id) from datafile where checksumvalue='';
 count 
-------
 31727
(1 row)
```

Given the other issues I've seen regarding special cases (S3-with-non-MD5s, Globus), is there a reason that an analog of `fixmissingunf`, maybe `fixmissingDataFileHashValue`, would be a Bad Idea? Perhaps something enabled by an opt-in setting.

**Comment by qqmyers** [comment]
[/api/admin/computeDataFileHashValue/{fileId}/algorithm/{alg}](https://guides.dataverse.org/en/latest/api/native-api.html#id21) 
:-)

**Comment by donsizemore** [comment]
Correct, I'm asking for an automatic population of the field when it's empty.

**Comment by donsizemore** [comment]
I'm pre-emptively iterating through our problem files, closing.
