### ISSUE TITLE
Problem with long file stores ID in JVM options

### ISSUE THREAD

**Issue by fredericbeck** [IQSS/dataverse#8312]
**What steps does it take to reproduce the issue?**

* When does this issue occur?

When adding a file store with a long name in the JVM options, file uploads fail whatever the upload method used, generating a `javax.ejb.EJBException: String index out of range: -3` error in the server logs.

Everything works for short ID, e.g. `sed-nge-storage` or `dv-global`, but not for longer ones such as `dataverse-global-storage`

* Which page(s) does it occurs on?

Error occur on the file upload page, or when using DV Uploader or direct `curl` API access.

* What happens?

File upload fails, detailed error log can be found [here](https://github.com/IQSS/dataverse/files/7726121/full-error.txt).

* To whom does it occur (all users, curators, superusers)?

All users are impacted.

* Workaround

Using shorter file store IDs works fine

**Which version of Dataverse are you using?**

Using Dataverse v5.8

**Comment by qqmyers** [comment]
@fredericbeck - thanks! Having looked after chat yesterday, I'm fairly sure that the problem with the line @pdurbin referenced - https://github.com/IQSS/dataverse/blob/c7539215e87f3d569650ad1e0e7fb243dc30a525/src/main/java/edu/harvard/iq/dataverse/dataaccess/S3AccessIO.java#L181 is that it should just be `if(!storageIdentifier.contains(":")) { `.

I think this is 'just' a bug - a cut/paste error. It will cause problems whenever the length of the store name is within a couple characters of being longer than the bucket name.

**Comment by pdurbin** [comment]
@fredericbeck are you interested in creating a pull request for this? We don't want to deprive you of long and meaningful IDs for stores. 😄

**Comment by pdurbin** [comment]
@qqmyers to be clear, we're saying this only affects the S3 driver, right? The file system driver should be ok?

**Comment by AR-2910** [comment]
Hey @pdurbin! I would like to address this issue and implement the solution provided by @qqmyers. Could you please assign it to me?

Regards

**Comment by pdurbin** [comment]
@AR-2910 it looks like @qqmyers assigned you. Thanks!

**Comment by AR-2910** [comment]
hey @pdurbin @qqmyers ,
I've reviewed the code related to this issue. I noticed that the specific line to change is different from what the issue originally asked for. The line in question is as follows:
if (!storageIdentifier.substring((this.driverId + DataAccess.SEPARATOR).length()).contains(":")) {

This differs from the proposed change in the issue description. The issue initially requested changing it to:
if (!storageIdentifier.contains(":")) {

The current code appears to have evolved, and the context of the check has changed. To address the issue and align with the current codebase, I plan to implement the proposed change line that does not involve substring. This change aims to simplify the code and make it more robust

Before proceeding, I wanted to confirm the correct line to modify. Could you please provide clarification on which change should be made?

Regards

**Comment by qqmyers** [comment]
Looks like that line moved to https://github.com/IQSS/dataverse/blob/0af5caf98bccf6a296e5ded3475519fd201e1ea2/src/main/java/edu/harvard/iq/dataverse/dataaccess/S3AccessIO.java#L194

**Comment by AR-2910** [comment]
Hey @qqmyers @pdurbin,

Thank you for assigning issue #8312 to me. I appreciate the opportunity to contribute to this project.

I have created a pull request #10031 for the code change.

Please review the pull request at your convenience. If the changes look good and meet the requirements, I would appreciate you merging it into the main branch.

Regards
