### ISSUE TITLE
Publish (Submit for Review) Dataset: Contributor/Reviewer Workflow

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#832]
In v3.6 and earlier, we had a dataset release workflow that involved a contributor creating a dataset, submitting it for review, notification sent to admin and curators, then reviewers (curator/admin) approve and publish or reject with notification sent back to contributor.

This may not be what we want in v4.0 but I believe some of our user base relies on this workflow and may expect something similar in v4.0.

**Comment by sekmiller** [comment]
If a user has create and edit privileges, but not publish he will see a submit for review button.  If he selects it and presses Continue a notification will be sent to everyone who has publish privileges on that dataset.  These users will have a new button on the dataset page "Return to Contributor"

This is available in the current build Weds. 2:15PM

**Comment by eaquigley** [comment]
Few notes and things to fix after reviewing this with @sekmiller 

- [ ] When a dataset is returned for modification, dataset contributor should receive a notification
- [ ] When a dataset is published, the submit for review button should not appear until something in the dataset has been edited
- [ ] When a dataset is published, the contributor should receive a notification

**Comment by sekmiller** [comment]
Issues noted above have been fixed and checked in

**Comment by eaquigley** [comment]
@kcondon to test this:

1) Have a default contributor for a dataverse be either an editor or manager
2) Create a dataset using an account that isn't a superuser
3) Submit for review button should appear

**Comment by mheppler** [comment]
I am taking this to do some UI clean up.

**Comment by mheppler** [comment]
Moved "Submit Dataset for Review" button into place where the "Publish Dataset" would be. Changed button text after submission to "Dataset Submitted for Review". The buttons in that section of the dataset need some spacing, but I am addressing that in another ticket (ref #1325).

**Comment by kcondon** [comment]
OK, this all works. One potential issue is the contributor is allowed to edit after submitting for review. I would think you'd want to "freeze" changes for that user while it is being reviewed? Otherwise the copy the reviewer is looking at may be undergoing change. Just a thought. @eaquigley What do you think? Otherwise I'm closing this.
