### ISSUE TITLE
solrconfig.xml is using deprecated cache implementation

### ISSUE THREAD

**Issue by Kris-LIBIS** [IQSS/dataverse#8325]
**What steps does it take to reproduce the issue?**
Install Dataverse with latest 8.x (currently 8.11.1) version

* When does this issue occur?
Whenever Solr index search is triggered

* Which page(s) does it occurs on?
Dataverse index page

* What happens?
Dataverse index page shows empty list. Solr logging dumps exception with error message:
```
Using join queries with synchronous filterCache is not supported! Details can be found in Solr Reference Guide under 'query-settings-in-solrconfig'.
```

* To whom does it occur (all users, curators, superusers)?
everybody ?

* What did you expect to happen?
Dataverse index page should list all published collections and datasets

**Which version of Dataverse are you using?**
5.9, but is expected to happen on any Dataverse version using latest Solr.

**Any related open or closed issues to this bug report?**
Log4J vulnerability is the reason I wanted to update the Solr version as the vulnerability is properly solved in the latest Solr version (docker image).

**Screenshots:**

No matter the issue, screenshots are always welcome.

To add a screenshot, please use one of the following formats and/or methods described here:

* https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests
*

**Comment by Kris-LIBIS** [comment]
FYI: I fixed it in my local installation by modifying the solrconfig.xml:

replacing in all cache configurations ```class="solr.FastLRUCache"``` or ```class="solr.LRUCache"``` with ```async="true"```

**Comment by poikilotherm** [comment]
This is related to #7662 and #8260

**Comment by minhd** [comment]
`solr.FastLRUCache` or the older `solr.LRUCache` seems to not support the async property.

I managed to get over this issue by switching the filterCache class to the recommended `solr.CaffeineCache` as documented here https://solr.apache.org/guide/8_11/query-settings-in-solrconfig.html#cache-implementations

**Comment by poikilotherm** [comment]
Thx @minhd I'll take a look and maybe add a transformation for #8320

**Comment by Kris-LIBIS** [comment]
I just removed the class attribute and let Solr choose the default class (which is CaffeineCache as of Solr 8.3). I don't think the async=true is strictly necessary as that is the default for CaffeineCache. So just removing the class attribute worked fine for me.

**Comment by poikilotherm** [comment]
Note to self:

Creating the solrconfig.xml from scratch via XSLT makes us use the new default cache implementation, as the class attribute isn't present in newer versions. It's good to know it defaults to CaffeineCache in Solr 8.3+, as this isn't stated within the docs (it's only announced to be default in Solr 9.0)

`async=true` is the default for Caffeine. This is very important, as we use joins etc.
>  If your queries include child documents or join queries, then async cache must be enabled to function properly

**Comment by pdurbin** [comment]
> I don't think the async=true is strictly necessary as that is the default for CaffeineCache. So just removing the class attribute worked fine for me.

Should we just do that? @Kris-LIBIS do you want to make a PR?

@poikilotherm are you already addressing this in #8320?

We wouldn't want to duplicate effort. 😄

**Comment by pdurbin** [comment]
We upgraded to Solr 9 in this PR:

- #9787

We started over with a vanilla Solr 9 solrconfig.xml so I assume this problem has gone away. Closing, but if this is still an issue, please let us know!
