### ISSUE TITLE
Metadata: Create a way to migrate and preserve existing custom fields for users

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#833]
Custom fields in v3.6 are used by a limited number of users but they tend to really want to keep using them, at least the ones already created and perhaps edit modify or create new ones.

We have a general strategy to get away from individual custom fields and replace them with metadata blocks that we create on behalf of interested parties, if the requirement rises to a certain level of importance.

However, how will we handle the legacy custom fields? How will they appear in the UI, templates, can they be maintained and updated?

We have talked about this a few times but this ticket is a placeholder for more definite planning.

**Comment by posixeleni** [comment]
Re-opening this issue since I need to now work with @scolapasta and @ekraffmiller to figure out how we will migrate datasets that have custom fields. I have the custom fields setup in 4.0 as separate custom metadata blocks but how we migrate them from 3.6 to 4.0 has not been planned out yet. This will be crucial for the migration of these datasets within the following Dataverses:

1) GSD - see #1137 
2) ARCS Dataverse - see #1213 
3) PS Replication Dataverse - see #1215

**Comment by ekraffmiller** [comment]
@posixeleni , just FYI, here is a snippet of DDI data, to give you an idea of how I will be looking up custom fields in the table we talked about:  
    <notes type="DVN:EXTENDED_METADATA" subject="TEMPLATE:Contains Custom Fields;FIELD:Customfield1">This is a plain text input field 1</notes>
            <notes type="DVN:EXTENDED_METADATA" subject="TEMPLATE:Contains Custom Fields;FIELD:Customfield1">This is a plain text input field 2</notes>

**Comment by ekraffmiller** [comment]
@pdurbin , can you update the solr schema for the new custom fields that Eleni has added in the tsv files?

**Comment by pdurbin** [comment]
@ekraffmiller @posixeleni I can but I'm having trouble finding the commit. I don't see it in master or any branch.

**Comment by posixeleni** [comment]
these custom fields have been around for months or several weeks so I am not sure I can locate a specific commit(s) for all of these

**Comment by pdurbin** [comment]
@ekraffmiller is all set. She needed to update her Solr schema locally.

**Comment by ekraffmiller** [comment]
completed - @kcondon in order to test this, the customfieldmapping table needs to be populated (this is a migration step)  let me know when you are ready to test and I can show you how to set that up
