### ISSUE TITLE
Large file disappears in demo.dataverse.org upload

### ISSUE THREAD

**Issue by kuriwaki** [IQSS/dataverse#8336]
I tried to uploaded a file over 500MB (specifically the original version of [this](https://dataverse.harvard.edu/file.xhtml?persistentId=doi:10.7910/DVN/GDF6Z0/JPMOZZ&version=4.0#)) on demo.dataverse.org. 

At the end of the upload stage, the file disappeared without any message. Here is [a video](https://www.dropbox.com/s/b7sf16ihbbadt1d/Screen%20Recording%202022-01-06%20at%202.55.58%20PM.mov?dl=0) of that.

Scope: 
- I first noticed the issue yesterday, and I tried again today. 
- The same file uploads fine on dataverse.harvard.edu. 
- A smaller subset of the same large file uploads fine on demo.dataverse.org

Perhaps related: PR #8271

In case it's relevant, the demo dataset I am trying to upload to is [dataverse-client-r](https://demo.dataverse.org/dataset.xhtml?persistentId=doi:10.70122/FK2/V14QR6&version=4.0)

**Comment by pdurbin** [comment]
@kuriwaki the demo server was recently rebuild by @landreev: 🎉 🚀 

- https://github.com/IQSS/dataverse.harvard.edu/issues/187

Want to give it another try? 😄
