### ISSUE TITLE
Dataverse OpenID connect / OAuth2 with PKCE

### ISSUE THREAD

**Issue by jakobmolandergeus** [IQSS/dataverse#8349]
Is it possible to configure Dataverse OpenID Connect (OIDC) provider to use Authorization Code Flow with Proof Key for Code Exchange (PKCE) such that it appends “code_challenge” and “code_challenge_method” (either S256 or plain) parameters to the login request?

I am trying to connect our Dataverse instance with our specific Microsoft Azure AD tenant and get the following error from the Microsoft Azure AD after login but before returning to Dataverse:

AADSTS9002325: Proof Key for Code Exchange is required for cross-origin authorization code redemption

It might be because I have a cluster of three instances of Dataverse running behind a Load Balancer.

Thank you in advance.

**Comment by poikilotherm** [comment]
Looks like both https://github.com/scribejava/scribejava (the OAuth2 lib we use) and Nimbus OpenID Connect SDK (which we use for OIDC only) is supporting this, too: https://connect2id.com/products/nimbus-oauth-openid-connect-sdk/examples/oauth/pkce. 

To be clear with this: this is not implemented right now and needs code changes.

I have no idea if you could work around this Azure AD requirement without code changes.

**Comment by jakobmolandergeus** [comment]
It would be much appreciated, if you (or anyone else) could find the time to implement the OAuth2 authorization code flow into the Dataverse application. It seems like a standard methodology, at least for Microsoft: 

https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow

**Comment by pdurbin** [comment]
@jakobmolandergeus if you don't have a requirement to use OIDC, as a workaround you might want to try OAuth. There are instructions for Microsoft at https://guides.dataverse.org/en/5.9/installation/oauth2.html

**Comment by pdurbin** [comment]
@jakobmolandergeus sure. Any news from your end? Still broken? Have you considered a different way to do auth?

**Comment by jakobmolandergeus** [comment]
@pdurbin It is still broken. The OAuth2 implementation used in DV (OIDC or OAuth2) in no longer supported by Microsoft Azure AD tenant. I do not know, if it is the existing implementation which need to change or is is a new IDP for DV.

**Comment by pdurbin** [comment]
@jakobmolandergeus bummer. There's one more option you could try: https://guides.dataverse.org/en/5.11.1/installation/shibboleth.html#shibboleth-and-adfs

**Comment by pdurbin** [comment]
Implemented in this PR by @poikilotherm:

- #9273
