### ISSUE TITLE
Inconsistency in Troubleshouting page

### ISSUE THREAD

**Issue by pkiraly** [IQSS/dataverse#8351]
**What steps does it take to reproduce the issue?** 

* When does this issue occur?
This is a documentation issue.

* Which page(s) does it occurs on?

Check the 'Deployment fails, “EJB Timer Service not available”' section of the Troubleshouting page of the Dataverse guide at https://guides.dataverse.org/en/latest/admin/troubleshooting.html#deployment-fails-ejb-timer-service-not-available.

* What happens?

The text says: "Remove the generated and `osgi-cache` directories". Below that there is a script which removes only a subdirectory of `osgi-cache` directory, not the whole:

```
rm -rf ${PAYARA_DIR}/${DV_DIR}/osgi-cache/felix
```
In my use case, to remove only the subdirectory did not help. It worked only when I removed the whole `osgi-cache` directory. I do not know if my use case is universal, and which should be the proper suggestion, but I am sure that the text and the script should be in line with each other.

* To whom does it occur (all users, curators, superusers)?

Superusers

* What did you expect to happen?

My expectation is that the text and code suggest the same action.

**Which version of Dataverse are you using?**

5.9

**Any related open or closed issues to this bug report?**

I haven't found any.

**Screenshots:**

The relevant section of the guide:

![Screenshot from 2022-01-18 17-13-59](https://user-images.githubusercontent.com/218218/149975604-9d5c7409-d38b-4041-840c-a8ed992f5cc0.png)

**Comment by pdurbin** [comment]
@pkiraly are you interested in making a pull request to fix these docs?

**Comment by pkiraly** [comment]
@pdurbin sure
