### ISSUE TITLE
Bug: Override ("Update Current Version") updates date on version in "Version" tab on dataset page

### ISSUE THREAD

**Issue by eunices** [IQSS/dataverse#8352]
**What steps does it take to reproduce the issue?**

* When does this issue occur?
1. When superuser updates a dataset
2. Dataset draft is published using the override ("Update Current Version") function.

![override-2022-01-19_8-40-33](https://user-images.githubusercontent.com/4596893/150042119-ff6e5a74-e626-4f7c-9118-4f97104c5e63.png)

* Which page(s) does it occurs on?
dataset.xhtml, "Versions" tab

* What happens?
The date of the version updated on the "Versions" tab changes (to the "lastupdatetime") with the override  ("Update Current Version") function.  
![2022-01-19_8-52-19](https://user-images.githubusercontent.com/4596893/150043043-ba844b56-0c1d-4fd2-ade3-4e0e31d060a2.png)

This bug *may* have started from v5.4.

note: Datasets listing as well as citation on the dataset page both use the version releasetime 
![image](https://user-images.githubusercontent.com/4596893/150042059-7e44407f-6a0d-46eb-aec4-7199e2ddb94a.png)

* To whom does it occur (all users, curators, superusers)?
Superusers (when publishing dataset)
Users (when viewing "Versions" tab)

* What did you expect to happen?
Expect that the date of the version updated with override  ("Update Current Version") to display releasetime of the version. The date should be consistent with the date reflected on the listing at the least.

There are probably multiple ways to go about fixing this bug, e.g.

1. When superuser updates dataset and publish by "Update Current Version", the releasetime of the dataset version should be displayed on the "Versions" tab, and not the lastupdatetime. The lastupdatetime of the dataset could still be updated.

2. When superuser updates dataset and publish by "Update Current Version", update the version releasetime and the lastupdatetime.

This is open to discussion but we are currently more **in favour of option 1**. We think that overrides ("Update Current Version") are typically done by superusers (e.g. curators) and are just minor changes (only metadata changes; any file changes would result in major release), at least in our use case. 

This issue is potentially important because citation dates may differ between "Versions" tab and dataset citation (on dataset page and dataset listings page).

**Which version of Dataverse are you using?**
v5.6 but likely still present in later versions

**Any related open or closed issues to this bug report?**
- Related Dataverse Google Group post: https://groups.google.com/g/dataverse-community/c/aMI4l_JcaQ8/m/a8g4ixhJAQAJ 
- Google docs under community questions: https://docs.google.com/document/d/1_OqCf58yJg3E_SIda0S2T7hf2DDklx8Fa0-DjtPmRyQ/edit

If anyone could share where the code could be found, will be helpful too.

**Comment by qqmyers** [comment]
FWIW: QDR likes option 1 (thinks the update current version shouldn't change the displayed date but likes that the lastupdatetime is recording there's been an update)
