### ISSUE TITLE
Create Account: Require user email address to be unique by account to support Password Reset feature.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#836]
Currently in v3.6 and in v4.0, user account email is not enforced to be unique. This causes  problem with the new Password Reset which relies on email address to sent the reset link to. Which account?

So, we are in the process of determining whether there is a legitimate use case for having a single email for multiple accounts and checked production.

There are 453 emails that exist in more than one account. We're not trying to determine whether that is due to forgotten accounts or other reason.

**Comment by scolapasta** [comment]
Duplicate of #845

**Comment by kcondon** [comment]
Closing as a dupe.
