### ISSUE TITLE
Investigate Dataset Move functionality and how permissions work

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#8365]
If you have a dataset where a user has curatior permission from one dataverse to another (where creators get default contributor role) what happens?

We recently had this was a manually (read via db) unpublished dataset and it the role stayed - we want to confirm that functionality, and was not some artifact of the unpublish.

My assumption is that yes, that's how it works, but it if so, it'll be good to confirm it is documented clearly.

**Comment by pdurbin** [comment]
Documentation only.
