### ISSUE TITLE
In-page preview for draft files shows an error when missing user API token

### ISSUE THREAD

**Issue by kaitlinnewson** [IQSS/dataverse#8367]
**What steps does it take to reproduce the issue?**

1. Login to a Dataverse install with previewers installed
2. Verify your account doesn't have a generated API token, or revoke it if it exists
3. Create a new dataset with a file that can be previewed, like an image or PDF
4. After the file is uploaded, visit the file page
5. Note the preview panel error that appears (screenshot below). If you generate an API token, it will load correctly.

* When does this issue occur?

When on a file page for a draft file with an account that does not have an API token generated.

* Which page(s) does it occurs on?

The File view page (file.xhtml).

* What happens?

An error is displayed in the preview panel ("Unable to preview metadata....").

* To whom does it occur (all users, curators, superusers)?

Dataset creators, or anyone that can view a draft file.

* What did you expect to happen?

I expected to see a preview of the file.

**Which version of Dataverse are you using?**

5.8, tested in the Scholars Portal demo environment and Harvard demo.

**Any related open or closed issues to this bug report?**

May be resolved in #8265 - please close if that is the case.

**Screenshots:**

![Screen Shot 2022-01-25 at 3 19 41 PM](https://user-images.githubusercontent.com/6903515/151053237-678241d7-af29-4ade-9418-9a1cb9b86ad0.png)

**Comment by qqmyers** [comment]
FWIW:  Looks like the preview() method starting at https://github.com/IQSS/dataverse/blob/0ea1f043ef45924389bb391687e8a7415c0c08b2/src/main/java/edu/harvard/iq/dataverse/FilePage.java#L915 doesn't include code to generate a token when there isn't one as 
https://github.com/IQSS/dataverse/blob/0ea1f043ef45924389bb391687e8a7415c0c08b2/src/main/java/edu/harvard/iq/dataverse/FileDownloadServiceBean.java#L305-L308 does for the 'explore' option that launches a new page. It looks like both of these will need to be updated given #8363 which will now return a non-null APIToken that could be expired (versus returning a null when the token was expired and thereby triggering creation of a new token.) - so the check should be for a null or an expiretime in the past.
