### ISSUE TITLE
Upload Files: Add dataset button stays active while files are uploading so can drop files in progress.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#837]
Tested on 8/22

I was creating a dataset and also uploading two files, one large sav file of 1.2G. The first file completed right away but the second one took a while and seemed to hang on upload. No error in server log so I just clicked add dataset (why was that enabled with an operation in process?) and it created the dataset without the file that was uploading.

**Comment by eaquigley** [comment]
@kcondon I don't feel strongly about this. I think it makes sense that if something hasn't finished uploading and you click away from this page, nothing is saved. Feel free to close!
