### ISSUE TITLE
Notifications: Users should have the option to "turn off" or "pause" notification

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#8375]
**Overview of the Feature Request**

**What kind of user is the feature intended for?**
(Example users roles: API User, Curator, Depositor, Guest, Superuser, Sysadmin)
Depositor, Curator, Superuse, API user

**What inspired the request?**
A request from a user uploading >1000 files who was bombarded with notifications for a past deposit.

**What existing behavior do you want changed?**
Notification for file ingest is sent automatically. Should allow a turn-off or pause option

**Any brand new behavior do you want to add to Dataverse?**

**Any related open or closed issues to this feature request?**
Notification improvements

**Comment by pdurbin** [comment]
@sbarbosadataverse good news! As of 5.11 it's possible to mute notifications:

- #8530

Here's a demo: https://harvard.zoom.us/rec/share/sFlpmpsfBOFyGHUiWcrLpLwnjpAa_CaHkV6WU1mBB56cUDXJ8hWUF50qcNIIQ_yV.alzT560S9diRN1TT

**Comment by sbarbosadataverse** [comment]
per Phil's comment
