### ISSUE TITLE
Feature Request/Idea: Too many email notifications - Data curation labels change results in email sent

### ISSUE THREAD

**Issue by eunices** [IQSS/dataverse#8379]
**Overview of the Feature Request**
Turn off email notifications for "Data curation label" 

**What kind of user is the feature intended for?**
(Example users roles: API User, Curator, Depositor, Guest, Superuser, Sysadmin)
Curator, dataset admins, superuser.

**What inspired the request?**
Users inbox getting too many emails. 

They start receiving too many email notifications and start to ignore them. They may ignore the more "important" notifications, such as to T&C of datasets upon dataset creation, etc.

**What existing behavior do you want changed?**
Email notifications for "Data curation label" received each time "Data curation label" is changed.

![image](https://user-images.githubusercontent.com/4596893/151737709-93538d05-9e24-4364-91da-c70cac3beb76.png)

**Any brand new behavior do you want to add to Dataverse?**
Either to turn off or a setting to turn-off email notifications for "Data curation label".

**Any related open or closed issues to this feature request?**

- A related "too many" notifications issue  #8375

**Comment by pdurbin** [comment]
@poikilotherm definitely. Once #8530 I think @eunices will be able to mute STATUSUPDATED to stop getting these emails.

@eunices here's a preview of the docs if you're interested: https://dataverse-guide--8530.org.readthedocs.build/en/8530/admin/user-administration.html#mute-notifications
