### ISSUE TITLE
Version Differences summary shows file metadata differences where none are there

### ISSUE THREAD

**Issue by sekmiller** [IQSS/dataverse#8382]
**What steps does it take to reproduce the issue?**
Create a dataset with multiple files; publish the dataset; make changes, republish; make a new draft with more dataset metadata changes; navigate to a published version; click on the versions tab. You'll see in the differences summary that there are file metadata differences in all of your files, but if you click "View Details" there are no actual changes in the file metadatas. 

* When does this issue occur?
See Above

* Which page(s) does it occurs on?
Dataset Page

* What happens?

* To whom does it occur (all users, curators, superusers)?
At least superusers and probably anyone who can see drafts

* What did you expect to happen? If there aren't any changes in the file metadata they shouldn't be in the summary

**Which version of Dataverse are you using?**
5.9

**Any related open or closed issues to this bug report?**
None open. I didn't review closed

**Screenshots:**
<img width="667" alt="Screen Shot 2022-02-01 at 11 12 02 AM" src="https://user-images.githubusercontent.com/2364928/152013674-92a5e299-bde5-4ca7-85c1-e342a345d03c.png">

No matter the issue, screenshots are always welcome.

To add a screenshot, please use one of the following formats and/or methods described here:

* https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests
*

**Comment by pdurbin** [comment]
@sekmiller has a fix in mind. When you do a comparison of the description we're seeing null vs empty string. We could consider these to be the same.

Let's do some code consolidation.
