### ISSUE TITLE
Number of search results per page should be configurable

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#84]
---

Author Name: **Philip Durbin** (@pdurbin)
Original Redmine Issue: 3492, https://redmine.hmdc.harvard.edu/issues/3492
Original Date: 2014-02-03
Original Assignee: Gustavo Durand

---

Right now, 10 results per page are shown. We'd like the user to be able to choose 20, 30, etc. results per page.

---

Related issue(s): #163
Redmine related issue(s): [3430](https://redmine.hmdc.harvard.edu/issues/3430), [3575](https://redmine.hmdc.harvard.edu/issues/3575)

---

**Comment by pdurbin** [comment]
FYI that via the Search API you can can use the `per_page` parameter to specify the results to return per request: http://guides.dataverse.org/en/latest/api/search.html

**Comment by pdurbin** [comment]
Here's where it's hard-coded in the GUI: https://github.com/IQSS/dataverse/blob/v4.4/src/main/java/edu/harvard/iq/dataverse/search/SearchIncludeFragment.java#L309

**Comment by pdurbin** [comment]
Is anyone who is following this issue interested in this? If not, let's close it.

**Comment by pdurbin** [comment]
No one seems to want this. Closing.
