### ISSUE TITLE
Dashboard for Superusers

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#840]
Need to determine what functionality will be editable on this as well as what it will look like.

Utilities:
- [ ] Configure time length for reset password link
- [ ] "index all" button
- [ ] support email address

**Comment by bencomp** [comment]
I started on a list of configuration items/settings that need to be documented in #2283.

**Comment by kcondon** [comment]
Also requested by Open Scholar, see RT 225414: I am strongly in support of having an admin
utilities page like in 3.6!  Looking forward to that being added.

**Comment by pdurbin** [comment]
A couple months ago @eaquigley [posted on the mailing list](https://groups.google.com/d/msg/dataverse-community/S0wcldZrsmQ/s-gklYN6DAAJ) about a helping us "build a better equivalent of the DVN v3.x Network Admin functionality for Dataverse v4.0". The survey is still open and everyone is encouraged to fill it out: https://harvard.az1.qualtrics.com/jfe/form/SV_8qcaOi0EO2dkK8Z

Some of the potential functionality is also naturally being added as bullets under "administration" as @bencomp and others brainstorm about how best to organize the guide for people installing Dataverse: https://groups.google.com/d/msg/dataverse-community/qujUFJDYXG0/0BhECCp0HQAJ

**Comment by kcondon** [comment]
LTS requested some stats for our app since they need to report on all apps under management:   “average uploads/downloads/searches per month”?

**Comment by mheppler** [comment]
Related to: Create Documentation for Super Users in User Guide #2211

**Comment by solomonhms** [comment]
I am interested in helping with the design and eventual testing of the administrative dashboard.

**Comment by pdurbin** [comment]
@solhm great! Are you "teya" at http://irclog.iq.harvard.edu/dataverse/2016-10-24#i_43665 ? @jggautier created a card at https://trello.com/c/kDSgIVVS/8-administrative-dashboard-4-7 and mentioned contacting you. Either way, you can get in touch by emailing support@dataverse.org and mentioning this issue number. Thanks!

@djbrooke I was just looking at https://github.com/IQSS/dataverse/issues/840#issuecomment-145844868 and wondering if that "build a better equivalent of the DVN v3.x Network Admin functionality for Dataverse v4.0" survey is still open. The link still works so it appears to be!

**Comment by solhm** [comment]
yes this is me teya the IRC. Thanks for the info

**Comment by djbrooke** [comment]
Yes, that survey is still open but I anticipate another survey going out as part of the user research process.

**Comment by pdurbin** [comment]
> I am interested in helping with the design and eventual testing of the administrative dashboard.

@solhm do you want to do some code review of pull request #3877 and run the code locally to see what you think? It's a dashboard we're developing for listing users as part of #3614.

**Comment by solhm** [comment]
@pdurbin sure I'll check it.

**Comment by scolapasta** [comment]
We now have a dashboard. We can open up new issues for specific features we want to add to it.
