### ISSUE TITLE
Requested change for direct upload call to S3

### ISSUE THREAD

**Issue by nightowlaz** [IQSS/dataverse#8414]
Hi there ... we have been trying to move the data for our Dataverse installation to a Dell Isilon storage server running OneFS software (offers S3 protocol). We have it working as long as the store is not configured for direct upload. When we configure the store for direct upload, the screen shows a network error, and nothing appears in the payara server log.

I have done some testing in a simulated environment with the same results where I could view the log on the OneFS server. I spoke with Jim Myers, who recommended testing just using the dataverse direct upload API, and got some better error messages. He analyzed the errors and determined that it appears that Dell is not parsing the headers sent in the API call correctly. Specifically, to upload the file to S3, the api formats the pre-signed URL including headers such as:

?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20220209T214113Z&X-Amz-SignedHeaders=host%3Bx-amz-tagging&X-Amz-Expires=28800&X-Amz-Credential=access key%2F20220209%2Fus-west-2%2Fs3%2Faws4_request&X-Amz-Signature=signature

Per the corresponding error in the OneFS log, it seems that the "%3B" is not interpreted as ";" and the two headers are interpreted as one by the storage server, and the upload fails. We used the API to test manually changing the "%3B" to ";" and when we sent the URL that way the upload was successful to the S3 bucket. We then ran the command to register in dataverse and the file appeared in the dataset.

It was recommended that I submit an issue to request a javascript change in the code to use the semi-colon when sending the headers instead of the URL-encoded special character (or have an exception for systems that don't parse that correctly). I know that there was another org that had a similar issue, so thought this could possibly be related.

I am happy to send more information about the results we got when testing, as well as the results in testing directly to an AWS S3 bucket. I am also requesting a code change to Dell support.

**Comment by qqmyers** [comment]
Another design option to consider would be adjusting the presigned URLs generated by Dataverse to decode that character (or that character in the X-Amz-SignedHeaders param only). I hesitate to do that only because we're using the URLs as returned form the AWS client now, but changing them right after creation avoids having to change the javascript, and DVUploader, and making a note in the API docs, etc. (@nightowlaz did confirm that Amazon AWS works with the decoded %3B so we don't have know cases where this would need to be optional per store).

**Comment by qqmyers** [comment]
FWIW: Another option would be to have an S3 flag to use/not use the tag. I believe MinIO doesn't support tags (at least as of when the code was written) - the request to set them is ignored and the request to delete results in an error we catch). A flag to not use tags would help there and support the Dell case too.

**Comment by poikilotherm** [comment]
FWIW: as far as I understand the MinIO docs, tagging objects and buckets is supported in recent versions.

**Comment by pdurbin** [comment]
@nightowlaz I've lost track of what you're using for storage these days. Are you still interested in this?

**Comment by nightowlaz** [comment]
We are still using AWS S3, and still waiting on Dell to fix this issue on their side in order to utilize the Isilon storage. The Dell tech asked if the application can be changed, which I think is why I submitted this, but I don't see a reason to change it if no one else needs this functionality. If you think it may be helpful in situations where folks are trying to utilize storage that doesn't support the headers (or can't interpret them correctly =) then it might be a nice feature).

**Comment by pdurbin** [comment]
@nightowlaz sounds good. If someone comes along and finds this issue we can always re-open it or open a fresh one. Thanks!
