### ISSUE TITLE
Improvement: Do not display "Dataset Creator" permissions on dataset level

### ISSUE THREAD

**Issue by haarli** [IQSS/dataverse#8417]
We want to apply the "Dataset Creator" role to certain users on Dataverse level (which is the only level that makes sense with this role). However, when doing this, the permission list of every dataset in this Dataverse displays this role (View Dataset -> Edit -> Permissions -> Dataset), although this role does not have any impact on this particular dataset. 

![grafik](https://user-images.githubusercontent.com/5524896/153599429-58978464-3038-4774-9080-cd392e7db18b.png)

This is really confusing for users, in particular for the real owners of the dataset. They might belive that all persons in the list have access to their dataset, even if unpublished. Wouldn't it make sense to remove Dataset Creators from the Dataset permission list? Of course, they should still be visible in the Dataverse permission list.

I will provide a pull request for this

**Comment by qqmyers** [comment]
On datasets I created on demo.dataverse.org, I don't see this role showing up:
![image](https://user-images.githubusercontent.com/6731983/153605376-b3e8d6b5-248d-49f2-9840-0913b7f13f3c.png)

And your screenshot shows multiple Dataset Creator entries - is something else going on?

I also ask because if Dataset Creator shows up, I'm surprised that Dataverse and Dataset Creator doesn't.

**Comment by qqmyers** [comment]
Ah - right - I was just looking at the available roles. So a better fix would be to only show assignments where the role shows in the role panel? Versus your fix which only handles that one role? Which could be done by reusing the logic at https://github.com/IQSS/dataverse/blob/4a6336975dda9ae5394027c30454121c13ccec56/src/main/java/edu/harvard/iq/dataverse/ManagePermissionsPage.java#L410-L418 ?

**Comment by haarli** [comment]
Absolutely, a much better solution! I'll modify my pull request. 
Thanks for the hint!

**Comment by jggautier** [comment]
Just noting that https://github.com/IQSS/dataverse/issues/6067 is or might be related.
