### ISSUE TITLE
dataverse.org/integrations is out of date

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#8425]
https://dataverse.org/integrations is out of date (screenshots below).

In pull request #4737 we created an integrations page in the Admin Guide we actually maintain: https://guides.dataverse.org/en/latest/admin/integrations.html

I'd like to propose that we remove the content from https://dataverse.org/integrations except for the link to https://guides.dataverse.org/en/latest/admin/integrations.html . If we can also set up an automatic redirect, that's fine too.

## Current integrations

![Screenshot 2022-02-15 at 14-08-06 Integrations](https://user-images.githubusercontent.com/21006/154132188-872b5f07-2049-47a3-abf6-5b256fd68ef3.png)

## Future integrations

![Screenshot 2022-02-15 at 14-08-15 Integrations](https://user-images.githubusercontent.com/21006/154132189-621b97f2-e3c2-4e63-9b69-d33849297aba.png)

**Comment by mreekie** [comment]
Sprint;
 - Size is trivial

**Comment by pdurbin** [comment]
I just set up a redirect:

![Screen Shot 2022-05-13 at 9 42 51 AM](https://user-images.githubusercontent.com/21006/168296833-cbb1d7cf-d670-4a21-8dce-e7458efc1743.png)

It seems to work fine. https://dataverse.org/integrations redirects to https://guides.dataverse.org/en/latest/admin/integrations.html

Moving to Review.
