### ISSUE TITLE
Remove TwoRavens from guides and code base

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#8433]
TwoRavens still has a prominent place in the guides despite being unsupported for many years. People new to Dataverse try to get it installed and (understandably) ask for help, given this prominence. However, we haven't run TwoRavens ourselves in Harvard Dataverse for years, making it very difficult to support it.

We should remove TwoRavens from the guides.

Furthermore, we should remove code and config related to TwoRavens that we don't use. I believe rApache is the main thing to remove here. (We definitely still use and support Rserve.)

We should probably also knock TwoRavens down from its number 1 spot on the list of external tools. Let Data Explorer or the previewers have that spot.

Here are docs that have a reference to TwoRavens or rApache:

```
$ ack -il 'rapache|raven' doc/sphinx-guides/source
doc/sphinx-guides/source/admin/integrations.rst
doc/sphinx-guides/source/_static/util/default.config
doc/sphinx-guides/source/_static/admin/dataverse-external-tools.tsv
doc/sphinx-guides/source/_static/installation/files/etc/httpd/conf.d/ssl.conf
doc/sphinx-guides/source/_static/installation/files/root/external-tools/twoRavens.json
doc/sphinx-guides/source/style/patterns.rst
doc/sphinx-guides/source/user/data-exploration/index.rst
doc/sphinx-guides/source/user/data-exploration/tworavens.rst
doc/sphinx-guides/source/installation/index.rst
doc/sphinx-guides/source/installation/prerequisites.rst
doc/sphinx-guides/source/installation/config.rst
doc/sphinx-guides/source/installation/img/tworavens_components.uml
doc/sphinx-guides/source/installation/img/tworavens_components.sh
doc/sphinx-guides/source/installation/r-rapache-tworavens.rst
doc/sphinx-guides/source/installation/shibboleth.rst
doc/sphinx-guides/source/installation/prep.rst
doc/sphinx-guides/source/api/apps.rst
doc/sphinx-guides/source/api/dataaccess.rst
doc/sphinx-guides/source/developers/intro.rst
doc/sphinx-guides/source/developers/selinux.rst
```

rApache RPMs to remove:

```
doc/sphinx-guides/source/_static/installation/files/home/rpmbuild/rpmbuild/RPMS/x86_64/rapache-1.2.9_R-3.5-RH6.x86_64.rpm
doc/sphinx-guides/source/_static/installation/files/home/rpmbuild/rpmbuild/RPMS/x86_64/rapache-1.2.9_R-3.5.x86_64.rpm
doc/sphinx-guides/source/_static/installation/files/home/rpmbuild/rpmbuild/RPMS/x86_64/rapache-1.2.6-rpm0.x86_64.rpm
doc/sphinx-guides/source/_static/installation/files/home/rpmbuild/rpmbuild/RPMS/x86_64/rapache-1.2.7-rpm0.x86_64.rpm
```

Here are scripts and that can be removed:

```
scripts/vagrant/install-tworavens.sh
scripts/rapache/build.sh
```

Config to edit to remove references:

```
conf/httpd/conf.d/dataverse.conf
conf/docker-aio/httpd.conf
```

There may be a few other places, but hopefully the above is a good start.

I found some of these by looking at #3210 where we last updated the rApache RPM.

Here's where we asked the TwoRavens team to host their own documentation: https://github.com/TwoRavens/TwoRavens/issues/696

**Comment by donsizemore** [comment]
rApache also appears in `./Architecture/dataflow.uml`
