### ISSUE TITLE
Reset Password: Throws an exception if more than one account is associated with an email.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#844]
This may be an as designed issue but I am reporting it since it should be handled even if we decided to make one email address a requirement.

**Comment by eaquigley** [comment]
Assigning this to @scolapasta due to #845 being assigned to him.

**Comment by scolapasta** [comment]
You'll need to drop the db, but e-mail is now configured to be unique.

**Comment by kcondon** [comment]
OK, reset with dupes no longer throws exception, just doesn' send email. Looks like the fix is to just require uniqueness.

Ok, closing.
