### ISSUE TITLE
Add admin-visible column to version table showing archival status

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#8443]
**Overview of the Feature Request**
3A-3.1 - merge the QDR-created code to add a final archival status column to the version table that is shown to superusers. This is simply a mechanism to expose the existing archival status column in the datasetversion table in the UI. As created, the column shows the value in the db if it is non-null, showing it as a live link if the value is a URL (e.g. it references an archival Bag in a remote web-accessible system). For null values, the UI shows a 'Submit' button that runs the archive API on the specified dataset version which provide a UI mechanism for creating Bags for previously published versions.

**What kind of user is the feature intended for?**
Superuser

With QDR's custom styling, it looks like this: 

![image](https://user-images.githubusercontent.com/6731983/154822162-635cfe4d-0bef-4ca6-9025-dbbfa1eed106.png)

**Comment by qqmyers** [comment]
Initial code in https://github.com/GlobalDataverseCommunityConsortium/dataverse/tree/GDCC/DC-3A

**Comment by sbiver** [comment]
Let's close this ticket once Sonia and Tania have been able to review it in QA.
