### ISSUE TITLE
Add collection info to OAI-ORE export

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#8444]
**Overview of the Feature Request** 
DV3A-4.1: The OAI_ORE export and therefore the archival bags don't currently provide information about which collection a dataset (version) is from. This task is to add basic information about the parent collections to the OAI-ORE export.

**Comment by qqmyers** [comment]
Code to add schema.org/IsPartOf info about enclosing collections added to [DC-3A branch](https://github.com/GlobalDataverseCommunityConsortium/dataverse/tree/GDCC/DC-3B). Also includes change from using root collection to BrandName as the catalog name.

**Comment by sbiver** [comment]
Let's have Robin verify that this is as per requirements.
Upon publish files should show up in the S3 bucket and will be visible in the UI
