### ISSUE TITLE
Create Account: Consider requiring unique email address per user account.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#845]
The reset password functionality relies on one email address per user account. This is not the case currently in production, with 453 instances of 2 or more accounts per email.

We think we want to make it unique but are investigating whether there is a legitimate use case here to support more than one account per email, such as some group notification or user with multiple group/ individual affiliations requiring multiple accounts but wanting to consolidate to single email address.

If we do change, this will impact current users and some migration step needs to take place.
If this ticket is acted upon, we should add this migration requirement to the migration placeholder ticket.

**Comment by pdurbin** [comment]
The uniqueness constraint for "email" definitely needs to be added to the authenticateduser table. I'm hoping the email field can be removed completely from the builtinuser table (so it would be a non-issue): https://docs.google.com/document/d/1zP80gaCx8a1UGD7GNxxjlKbYLBdbaxpQs1mapcrqON4/edit?usp=sharing

**Comment by scolapasta** [comment]
This has been added, but need to make sure the UI does validation for this (rather than fail at the save) (Same with API, but that is lower priority).

**Comment by sekmiller** [comment]
UI now enforces unique email prior to attempting to save

**Comment by kcondon** [comment]
Yep, email needs to be unique. Closing.
