### ISSUE TITLE
Feature Request/Idea: FAIR (data) view on files listings; some suggestions

### ISSUE THREAD

**Issue by steltenpower** [IQSS/dataverse#8453]
As I meet too many researchers not having much of a clue about open file formats and the breadth of what they can bring, I came up with a way of helping them in a user-friendly way within the tools they already use. Do you agree that (part of) it would be a welcome improvement to DATAVERSE perhaps?

When you read the few lines of text, you'll understand the ugly drawing
https://github.com/steltenpower/FAIRfilesListing

Looking forward to your views. 

ping @TaniaSchlatter

**Comment by TaniaSchlatter** [comment]
Thanks for opening this issue, @steltenpower, and for including the sketch and demos. I agree with the importance of clearly showing the file type. Is your intent to help educate researchers depositing data primarily, or looking to use data?

**Comment by steltenpower** [comment]
Thanks @TaniaSchlatter, I'm glad to hear you're interested in (part of) it.

My intent is to help both sides of re-use (the one publishing the data and the many using it), depending on the tool or specific parts of it, the focus can be different however:
When somewhere in the future 'all' creation tools and operating systems have this for their file dialogs/explorers, the quality assurance part is already done there and makes less sense to repeat in Dataverse.

I hope that answers your question.
Is there anything else you need explained, or improved at that page, to take anything further?

If/when I have the time and skill to help realize parts, what page or source code file should I look at first?

**Comment by pdurbin** [comment]
Neat idea. Like I said on the thread at https://groups.google.com/g/dataverse-community/c/jMt-COccvo0/m/9cR_SQg4BAAJ I like the animation at https://github.com/rickdkk/fair-file-columns (linked from @steltenpower 's README) that looks like this:

![demo](https://user-images.githubusercontent.com/21006/156454113-c2c233a7-dafb-43f3-a48c-5ddc185d9cda.gif)

@steltenpower when you're ready to set up a dev environment please take a look at https://guides.dataverse.org/en/latest/developers/dev-environment.html and please don't be shy about asking questions. We have a dev list at https://groups.google.com/g/dataverse-dev and chat at https://chat.dataverse.org

**Comment by cmbz** [comment]
2024/12/02: Closing as not planned. We will be developing a Dataverse Marketplace for external tools, and in 2025 the new Single Page Application will be deployed. Therefore, @steltenpower please revisit your idea in light of those upcoming developments. Perhaps the functionality you suggest can be packaged as an external tool or as a new UI widget that installations could add to their SPA instances.
