### ISSUE TITLE
5.10 release notes

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#8457]
As discussed at group meeting @lenwiz and I will work on the 5.10 release notes.

We'll use the 5.9 release notes as a starting point: https://github.com/IQSS/dataverse/releases/tag/v5.9

As mentioned at https://guides.dataverse.org/en/5.9/developers/making-releases.html#write-release-notes we'll grab snippets from https://github.com/IQSS/dataverse/tree/develop/doc/release-notes that have been written for this release.

I'm assuming we're using the old, established process, but we could also think about the changes proposed in pull request #8378 along the way.

**Comment by pdurbin** [comment]
I just created pull request #8464.

@lenwiz I requested a review from you. 😄

Per our normal process, the pull request is now on the board and I've removed this issue from it (so we don't have two items there).

**Comment by claudiodsf** [comment]
Hi, could I ask you if you have a timeline for the release of 5.10?

We are about to put a Dataverse installation into production, but we might want to wait a little more for the multi-licence support.

I understand that drafting a release is a complicated process, and I want by no means put any pressure on you 😉.

Thanks in advance!

**Comment by pdurbin** [comment]
@claudiodsf thanks for asking. You aren't alone in being excited about the new multi-license feature coming in 5.10. 😄 

I brought up the timing of the release this morning in standup, but as usual, we don't tend to commit to specific date. Sorry.

I will say that I think we're close. If you look at our project board at https://github.com/orgs/IQSS/projects/2  (which you can also find linked from https://guides.dataverse.org/en/5.9/developers/intro.html#kanban-board ), there are a few pull requests and issues with a milestone of 5.10 that we'd like to get through QA and into "Done".

If you'd like to help, you're welcome to look at the release notes I wrote in pull request #8464 and let me know if there are any typos or if you find anything confusing. There's actually a lot about mult-license in there that you'll probably want to read sooner or later. 😄

**Comment by eunices** [comment]
Hi, sorry, just to check, is the solr upgrade done before or after the war file deployment, or the order doesn't matter? It's not mentioned under upgrade instructions.

**Comment by pdurbin** [comment]
@eunices hmm, on my laptop I installed the new Solr version after upgrading the war file. I'm not sure if it matters but I guess I'd suggest after.

**Comment by pdurbin** [comment]
@eunices I just made the Solr upgrade of of the steps (the last) in 7a8d053cc5. Thanks for the feedback!
