### ISSUE TITLE
Feature Request/Idea: Add Dataset metadata facets as top level item in the side panel

### ISSUE THREAD

**Issue by adaybujeda** [IQSS/dataverse#8462]
**Overview of the Feature Request**
We would like to be able to select datasets with a particular facet value from the side panel without having to do a successful search first. Similar to how Dataverses/Datasets/Files are always displayed at the top.

The idea is to have a new section on the side panel, underneath the Dataverses/Datasets/Files. This will be driven from a new parameter in the DataTypeField.

Final desired UI still to be designed.

**What kind of user is the feature intended for?**
All users

**What inspired the request?**
As part of the Harvard Data Commons project there is a requirement to tag datasets as computations workflows. This can be done with metadata blocks, but we would like to find these datasets directly from the side panel as we do with the main Dataverses/Datasets/Files checkboxes.

**What existing behavior do you want changed?**
How metadata fields are indexed in Solr.
How facets are displayed on the side navigation

**Any brand new behavior do you want to add to Dataverse?**
The ability to add a default value to a metadata facet into Solr when a metadata field is inserted by a user.

**Any related open or closed issues to this feature request?**
Could be related to #6030

**Comment by pdurbin** [comment]
@adaybujeda hi, just making sure you're aware that you can already add any "is facetable" dataset metadata field to the left side panel. Here are some screenshots for how to do this:

![Screen Shot 2022-03-04 at 10 35 03 AM](https://user-images.githubusercontent.com/21006/156792942-7e7b8359-f90d-4823-8363-67bcad8f522f.png)

![Screen Shot 2022-03-04 at 10 33 16 AM](https://user-images.githubusercontent.com/21006/156792940-26ac3d0a-a38a-4ce0-bbb5-80a3307b3241.png)

So you could create a computational reproducibility metadata block, for example, and define a field called `Workflow` (or whatever, I saw this in #8461). Happy to chat more about this. Seems like a great project!

**Comment by adaybujeda** [comment]
Thanks @pdurbin,
We are aware of this feature, but it is not quite what is required.
We would like the facet to be displayed all the time, with (0) when there are no matches. Functionally, to work in the same way as` Dataverses/Datasets/Files` checkboxes.

**Comment by qqmyers** [comment]
Given that #8461 is about file categories, what is the intent here? To make it easy to find datasets where any file has been tagged with 'Workflow'?

**Comment by adaybujeda** [comment]
This does not relate to #8461 as such.
The idea is to make it easy to find datasets that have an specific metadata populated.

Lets say that we add `Computational workflow` as a new controlled vocabulary metadata field in a new metadata block.
We would like `Computational workflow` to appear in the side panel all the time, similar to the behaviour of `Dataverses/Datasets/Files` in the side panel.

**Comment by adaybujeda** [comment]
After discussions with the Harvard Data Commons team, it has been decided to follow a different approach to tag all datasets that are computational workflows. This will be accomplish with a new static field facet that will be populated with the metadata blocks that have data for a dataset.

superseded by #8536
