### ISSUE TITLE
Failure to export dataset not detected, dataset marked as exported

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#8484]
This is a followup issue to #8452. The user's/installation's issue was addressed by modifying the export code to properly handle a specific metadata field becoming multiple (#8473). But there was one underlying bug that I would still like to address: despite the failure to export, the dataset was marked as exported; and then added to the OAI set. (The fact that the partial, incomplete export was left written on disk made it even worse). 

Must be a straightforward enough issue of properly intercepting exceptions.

**Comment by landreev** [comment]
Added the "feature: harvesting" label, to add it to the pile of Harvesting issues that we want to fix as part of the GREI effort. (#8574)

**Comment by landreev** [comment]
This is not a specifically harvesting issue of course; but it does affect harvesting (a record like this breaks the ListRecords output; that's how it was discovered/reported). 
Thinking about it, this should be addressed in both places - the export code needs to do a better job detecting errors; and the Harvesting server code needs to be able to detect the condition of the exported metadata fragment missing, without generating invalid output.

**Comment by mreekie** [comment]
sprint:
 - this one is a side effect from an fix for an installation in France. That issue was addressed, and this came up during the investigation 
 - straightforward. Testing is time consuming. 
 - small

**Comment by mreekie** [comment]
- in WIP at end of [pm.sprint.2022_05_11](https://github.com/IQSS/dataverse/labels/pm.sprint.2022_05_11)
