### ISSUE TITLE
API & Notifications

### ISSUE THREAD

**Issue by arnaudbey** [IQSS/dataverse#8487]
Hi
is there any way to retrieve notification details through API ?
I managed to get a notifications list (see below) but no info about datetime / dataset involved, etc.

Thanks

`{'status': 'OK', 'data': {'notifications': [{'id': 1604, 'type': 'PUBLISHEDDS'}, {'id': 1589, 'type': 'PUBLISHEDDS'}, {'id': 1579, 'type': 'PUBLISHEDDS'}, {'id': 1568, 'type': 'PUBLISHEDDS'}, {'id': 1559, 'type': 'PUBLISHEDDS'}, {'id': 1550, 'type': 'PUBLISHEDDS'}, {'id': 1542, 'type': 'CREATEDS'}, {'id': 1535, 'type': 'PUBLISHEDDS'}, {'id': 1521, 'type': 'ASSIGNROLE'}, {'id': 1463, 'type': 'CREATEACC'}]}`

**Comment by arnaudbey** [comment]
I'd like to ! Especially since the changes don't look that complicated to implement. Add some notificationObjectBuilder.add statements with sendDate or other notification properties.

but I'm running out of time to set up a development instance to test my code :(

**Comment by pdurbin** [comment]
@arnaudbey good news! I'm reviewing pull request #8530 by @ErykKul and he's adding additional detail to these the JSON output of notifications (I added the timestamp). For example:

```
{
  "status": "OK",
  "data": {
    "notifications": [
      {
        "id": 5,
        "type": "CREATEDS",
        "subjectText": "Root: Your dataset has been created",
        "messageText": "Hello, \nYour new dataset named test (view at http://localhost:8080/dataset.xhtml?persistentId=doi:10.5072/FK2/XAVUGS ) was created in Root (view at http://localhost:8080/dataverse/root ). To learn more about what you can do with a dataset, check out the Dataset Management - User Guide at https://guides.dataverse.org/en/5.10.1/user/dataset-management.html .",
        "sentTimestamp": "2022-05-18T20:45:21Z"
      },
      {
        "id": 1,
        "type": "ASSIGNROLE",
        "subjectText": "Root: You have been assigned a role",
        "messageText": "Hello, \nYou are now Admin/Dataverse + Dataset Creator for the dataverse \"Root\" (view at http://localhost:8080/dataverse/root ).",
        "sentTimestamp": "2022-05-18T20:40:44Z"
      }
    ]
  }
}
```

The details about datasets, etc. should be available in the subject or message text. I'll go ahead and mark this issue to be closed by the pull request if it gets merged.

I'll note that while testing this I was reminded that not all API operations (creating a dataset, for example) generate a notification. We could reopen this issue if we'd like to fix this:

- #1342

**Comment by arnaudbey** [comment]
Good news indeed, thanks a lot. 
I don't know yet which release will be used here and if it'll include this feature, but sounds promising !

Thanks again  😃

**Comment by pdurbin** [comment]
@arnaudbey hi, this feature should be in the next release, which as of this writing we are calling 5.11. (The current release is 5.10.1.)
