### ISSUE TITLE
Documentation: Json import command line examples contain a couple mistakes.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#8497]
https://guides.dataverse.org/en/5.9/api/native-api.html#import-a-dataset-into-a-dataverse-collection
https://guides.dataverse.org/en/5.9/api/native-api.html#import-a-dataset-into-a-dataverse-installation-with-a-ddi-file
Both the env variable form and the fully expanded form of the command line need double quotes around the url due to the & argument, otherwise they won't work. 

Also, the PID environment variable does fully specify the PID so that it fails.
It shows: export PERSISTENT_IDENTIFIER=doi:ZZ7/MOSEISLEYDB94
Should show the authority as part of the PID, like 
export PERSISTENT_IDENTIFIER=doi:10.70122/FK2/2Z3BJM

**Comment by pdurbin** [comment]
Fixed by this PR:

- #9722
