### ISSUE TITLE
Demo Environment: Dataset could not be published due to a failure to register, or update the Global Identifier for the dataset or one of the files in it.

### ISSUE THREAD

**Issue by cmbz** [IQSS/dataverse#8505]
While attempting to publish a dataset on demo.dataverse.org, I repeatedly received the following message:

"could not be published due to a failure to register, or update the Global Identifier for the dataset or one of the files in it. Contact support if this continues to happen"

**What steps does it take to reproduce the issue?**

I continued to receive the error message each time I tried to publish the dataset using pyDataverse and also manually clicking the Publish button in the UI.

I was eventually able to publish the dataset successfully.

**Which version of Dataverse are you using?**
demo.dataverse.org, v. 5.9 build 750-fb24c87

**Any related open or closed issues to this bug report?**

The error appears related to this issue from several years ago: https://github.com/IQSS/dataverse/issues/886

**Screenshots:**

<img width="1119" alt="Screen Shot 2022-03-18 at 9 35 54 AM" src="https://user-images.githubusercontent.com/18597493/159012722-fe1d03d3-435b-4c7a-b566-612043d85e2d.png">

**Comment by cmbz** [comment]
I have not encountered another instance of this behavior since I opened this issue. In addition, the server for demo.dataverse.org has been updated.

**Comment by pdurbin** [comment]
Right, the rebuild of demo was here:

- https://github.com/IQSS/dataverse.harvard.edu/issues/187
