### ISSUE TITLE
File upload javascript was giving errors for not unique identifier

### ISSUE THREAD

**Issue by ErykKul** [IQSS/dataverse#8515]
**What steps does it take to reproduce the issue?**
Go to a dataset and try to upload a file. Open the development console in your browser; you can see the error about not unique identifier

* Which page(s) does it occurs on?
Upload data fragment.

* What happens?
Error in the console.

**Which version of Dataverse are you using?**
Develop

**Comment by ErykKul** [comment]
![image](https://user-images.githubusercontent.com/101262459/159237375-d006e085-38ab-4156-acd4-a864eced1b8c.png)

**Comment by pdurbin** [comment]
Resolved by PR #8516, closing.
