### ISSUE TITLE
Search in dropdowns is broken

### ISSUE THREAD

**Issue by ErykKul** [IQSS/dataverse#8519]
**What steps does it take to reproduce the issue?**
Edit dropdown/combobox field with more than 10 items. Search does not show up.

* When does this issue occur?
All dropdowns, regardless the number of items.

* Which page(s) does it occurs on?
Edit/create dataset.

* What did you expect to happen?
For dropdowns with more than 10 items the search should show up like this (preferably with filterMatchMode "contains", "startsWith" is less useful):
![image](https://user-images.githubusercontent.com/101262459/159274646-6484d719-7d84-41a5-8635-2cca0dc94894.png)

![image](https://user-images.githubusercontent.com/101262459/159274736-44c4c092-4ee7-46f9-a6cd-948938e03ceb.png)

![image](https://user-images.githubusercontent.com/101262459/159274835-2926530a-f518-4324-9e65-9cbd397c41a7.png)

**Which version of Dataverse are you using?**
develop

**Comment by TaniaSchlatter** [comment]
Hi @ErykKul, thanks for opening the issue and the pull request. It looks like we lost the search feature on the Subject and Language field drop downs between version 5.9 and 5.10. Is that what you noticed and are fixing with this issue?

**Comment by ErykKul** [comment]
Hi @TaniaSchlatter. Yes, this is the pull request to fix that. My description is more generic as it applies to all fields in metadata that had search function, including the Subject and Language field.

**Comment by pdurbin** [comment]
As discussed in standup this morning, we'll be using this issue to track the bug/regression in 5.10 where the search is missing from fields such as "Subject". Below are some screenshots from @scolapasta to show the behavior in 5.9 vs 5.10.

## 5.9 (has search)

![image (1)](https://user-images.githubusercontent.com/21006/160435550-1c992cbe-8ea7-4e45-9b0f-d187b712b422.png)

## 5.10 (search missing)

![image (2)](https://user-images.githubusercontent.com/21006/160435587-2923c1ce-6fc1-4c31-ba0a-ce16a4016db0.png)

Thanks again @ErykKul for bringing this our attention!
