### ISSUE TITLE
Solr Search Index with 5.10 (Solr 8.11.1) 

### ISSUE THREAD

**Issue by JulienBr57** [IQSS/dataverse#8522]
Hi,

We migrate in test the latest version from 5.9 to 5.10. 
Problem : we have no results on the homepage (but we still have dataverses and datasets in database). The [full reindex](https://guides.dataverse.org/en/latest/admin/solr-search-index.html) doesn't work : more precisely, the cleaning curl execution doesn't return result {} while it was OK with 5.9
I think that the solr upgrade is the problem.
Can you help us please ?
Thx!
Julien from Université de Lorraine

**Comment by donsizemore** [comment]
Hello,

Have you retraced your steps through the Solr 8.11.1 installation, and made sure that Dataverse can communicate with Solr (are the XML config files in place)? There may be something helpful in the Payara server.log or in Solr's solr.log itself, but especially if Dataverse isn't able to clear the Solr index, I'd be certain that Solr is responding to Dataverse.

Don

**Comment by pdurbin** [comment]
@JulienBr57 I'm just echoing @donsizemore here but I do think that seeing the errors (and probably stacktrace) in server.log would be helpful. Usually it's stored at `/usr/local/payara5/glassfish/domains/domain1/logs/server.log`. You are welcome to email it to support@dataverse.org

**Comment by JulienBr57** [comment]
Hello Don, Philip,
Thx very much for your quick replies. I just sent the piece of log with the curl execution (index/clean). 
I think that the port 8983 is  because it returns a 404 error : 

```
javax.ejb.EJBException:` Error from server at http://localhost:8983/solr/collection1: Expected mime type application/octet-stream but got text/html. 
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 404 Not Found</title>
[...]
```
I keep looking !

**Comment by JulienBr57** [comment]
Yes ! That was missing. That works 👍 👍 👍  thanks !!
Best regards
Julien
