### ISSUE TITLE
Optional tabular ingest skipping 

### ISSUE THREAD

**Issue by lubitchv** [IQSS/dataverse#8525]
We have a pilot project of transitioning from Nesstar to Dataverse. One of the features of Nesstar is the ability to convert files into different formats on the fly, such as SPSS, STATA etc. Dataverse does not have this feature, but our users really would like to have all these different formats. To get around this we plan to import all these formats from Nesstar. The problem is all these files will go through tabular ingest, but we would like that only one (SPSS) file would go through tabular ingest but other files in other formats such as STATA would be added to datasets without ingest.

Therefore it would be nice to have an optional parameter (tabularIngest=true/false) in add file to dataset API. Maybe this parameter would be passed down to   saveAndAddFilesToDataset function in IngestServiceBean and  maybe something like  

`if (FileUtil.canIngestAsTabular(dataFile)) ` 
replaced with 
`if (FileUtil.canIngestAsTabular(dataFile) && tabularIngest)`  

What would be the thoughts regarding it?

**Comment by qqmyers** [comment]
Have you considered the aux file API? If you add your alternate formats that way they appear in the download menu but would not be separate, first-class datafiles in the file list and wouldn't undergo ingest, etc.

**Comment by landreev** [comment]
Uploading alternative formats as auxiliary files may be a perfectly good solution for this use case. But I would very much like to finally implement this "skip option" flag/parameter, both for the API and for the UI, regardless.

**Comment by lubitchv** [comment]
We will need such feature for add file API soon. I can make a pull request for add API with parameter with existing code, if it is ok with everyone. Otherwise I will look into  auxiliary files or import/uningest  and will discuss it with my group.
