### ISSUE TITLE
Edit Dataset: After click +, Geographic Coverage Country select box missing arrow due to field overlap

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#853]
Tested using FF and Chrome on Mac

When you click the + button the country select box lengthens so the select arrow is behind the next field. It still works but can be puzzling.

**Comment by eaquigley** [comment]
@kcondon could you please test this again and report back if it is still happening? thanks.

**Comment by kcondon** [comment]
Works now, closing
