### ISSUE TITLE
OIDC first login page without user Information

### ISSUE THREAD

**Issue by chinghuangflysheet** [IQSS/dataverse#8538]
Hi,
We already have UserStore in our IdM and we can provide API either.
Is there any API that can post all the user profiles to the dataverse?
If API isn't available, is there any possibility for us to retrieve the data from the UserStore to the dataverse? What would be the table schema for our reference?

related issues below:

- https://github.com/IQSS/dataverse/issues/5974
- https://github.com/IQSS/dataverse/issues/6690
- https://github.com/IQSS/dataverse/issues/6679

**Comment by pdurbin** [comment]
> No, there is no API for modifying user profiles. Perhaps there should be one!

I just stumbled upon this open issue for modifying users via API:

- #7679

**Comment by chinghuangflysheet** [comment]
@pdurbin 
Thank you for your reply!
We successfully solved the problem by the schema
I really appreciate that.

**Comment by pdurbin** [comment]
@chinghuangflysheet wonderful! It sound like you're all set so I'll close this issue. If you have code you'd like to contribute through a pull request, please let us know!
