### ISSUE TITLE
Dataset page stays on the url with "version=DRAFT" after the dataset is published

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#8548]
... this results in "DRAFT version not found" warning message. Refreshing the page does not fix it, because "version=DRAFT" is in the url. 
This is a sub-issue of #7653. Opening a "small chunk" issue for this specific problem, since it's the most annoying to the users; and should be the easiest to fix.

**Comment by landreev** [comment]
Copy-and-pasting what I said in the parent issue: 

> Do we actually need that "DRAFT not found" message at all? Should we quietly redirect to the last published version instead, if there's no DRAFT? - That would be so much easier than messing with that redirect-on-unlock...

**Comment by sbarbosadataverse** [comment]
Yes, Leonid. I think it's confusing to have the DRAFT not found message.

**Comment by landreev** [comment]
To clarify, when I said "Do we actually need that ... message at all?" above -  I meant, not just in this scenario, but do we EVER need it, when somebody tries to go to a DRAFT and it does not exist.

**Comment by sbarbosadataverse** [comment]
I can't see how we would need that scenario? Maybe someone else may have a scenario in mind I can't think of...if they delete a DRAFT--what's the need?

**Comment by cmbz** [comment]
2024/10/24: Should be implemented in the SP. Added to the SPA Beta backlog for review there.

**Comment by pdurbin** [comment]
I already tested it and it works fine on the SPA. Some screenshots:

![Screenshot 2024-10-24 at 10 50 34 AM](https://github.com/user-attachments/assets/1e096762-059c-4eb4-b9f3-c039b25ae585)
![Screenshot 2024-10-24 at 10 50 43 AM](https://github.com/user-attachments/assets/49e3c6b6-8fb6-4370-90a1-b1dddaa3eee8)

**Comment by cmbz** [comment]
2024/10/25: Closing this issue as complete and removed from the backlog because the bug is fixed in the SPA.

**Comment by pdurbin** [comment]
This will be fixed by the following PR:

- #11947
