### ISSUE TITLE
Better license workflow on dataset creation

### ISSUE THREAD

**Issue by DieuwertjeBloemen** [IQSS/dataverse#8561]
**Overview of the Feature Request**
The selection of a license should be more explicit and visible upon dataset creation.

**What kind of user is the feature intended for?**
Dataset creators

**What inspired the request?**
The new license feature and an improved user experience.

**What existing behavior do you want changed?**
The license choice should be more accessible and more visible, perhaps even mandatory.

**Any brand new behavior do you want to add to Dataverse?**
The license selector is hidden under the Terms tab and Dataverse doesn’t ask the user to pick a license when they first create a dataset.
Our institution doesn’t allow us to set a default license because of legal reasons (I know, we’re not happy about it either). However, we also think it would be best practice to explicitly get the approval of the user for the license applied to their dataset by making the license selection a bit more obvious and visible.

We would like the dataset creation workflow to allow the creator to select a license on creation or at least always see which default license will be applied to the dataset. And therefore not only have it hidden under the Terms tab.

A solution (option A) could be to do have a similar workflow to that of the template creation (see screenshot). When you create a template, you are immediately sent to Terms and not to the draft dataset once you’ve filled in all your metadata.
Another option (option B) would be to add a license field in the create a dataset form above the citation metadata block, like where the ‘Dataset Template’ selector is.

<img width="761" alt="image" src="https://user-images.githubusercontent.com/92870663/161095928-ded66fa6-d18c-4d0e-9e57-52c2b55b9975.png">

**Any related open or closed issues to this feature request?**

- https://github.com/IQSS/dataverse/issues/8554

**Comment by DieuwertjeBloemen** [comment]
Well, the issue with that is that it appears in the **publish** pop-up. And because we work with a review phase, it's the reviewer that sees it, not the actual dataset creator. On top of that, I don't think it makes it all that clear that they actually have a choice in license either.

**Comment by qqmyers** [comment]
Adding the same info to the review popup would be a fairly small change if it would work for you. Similarly, one could consider ways to make the 'if you don't like this license...' info more prominent in those. I'm suggesting these primarily because I think a larger change would be something that we'd want to get community consensus about before proceeding, and/or agree that whether a default license exists should be an option that would have to then be maintained going forward, etc., plus its more work.

**Comment by poikilotherm** [comment]
What about a textual hint "This dataset will be licensed by default with XYZ, please edit under terms tab after creation to change this." just above the submit button?

These hints will become even more important when dealing with new flavors of "datasets" for software and workflows...

**Comment by pdurbin** [comment]
> What about a textual hint like "This dataset will be licensed by default with XYZ, please edit under terms tab after creation to change this." just above the submit button?

I like this idea as something we could implement fairly quickly. Incremental progress.

**Comment by DieuwertjeBloemen** [comment]
I like the idea of changing the pop-up for the submit for review as was done for the publish pop-up to show the license choice with the textual hint. It's maybe still worth thinking about the workflow at a later stage, but for now that would be enough I think.
We are thinking of making 'Please select a license' the default with a link behind it to the manual on how to actually change/select the license in the Terms tab. It's a bit of a work around, but would work well enough, we think. And this way, our reviewers can also easily check if someone actually selected a license or not.
