### ISSUE TITLE
API endpoint for downloading guestbook doesn't accept the Dataverse Collection's database ID, accepts only its alias

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#8563]
**What steps does it take to reproduce the issue?**

* When does this issue occur?
  When using the API endpoint for downloading guestbooks, documented at https://guides.dataverse.org/en/5.10/api/native-api.html#retrieve-guestbook-responses-for-a-dataverse-collection

* What happens?
  The endpoint returns an empty dictionary instead of the guestbook responses when a database ID of a Dataverse Collection is given, e.g. `curl -H X-Dataverse-key:xxx "https://dataverse.harvard.edu/api/dataverses/2966344/guestbookResponses?guestbookId=204"` where 2966344 is a collection's database ID.

* To whom does it occur (all users, curators, superusers)?
  All users who need or prefer to use the API endpoint to download guestbooks

* What did you expect to happen?
  The endpoint would return the responses in the guestbook, like it does when you pass the Dataverse Collection alias, e.g. `curl -H X-Dataverse-key:xxx "https://dataverse.harvard.edu/api/dataverses/dataverse-ux-research-dataverse/guestbookResponses?guestbookId=204"` where dataverse-ux-research-dataverse is a collection's alias.

  Or the endpoint would return an error message saying that no collection would be found, but then it might be better to edit the documentation so that users know that the collection alias must be used.

**Which version of Dataverse are you using?**
  v5.10

API guide entry about the endpoint mentions database ID:
<kbd><img width="863" alt="Screen Shot 2022-03-31 at 2 11 55 PM" src="https://user-images.githubusercontent.com/18374574/161123930-d79c40dc-ae9c-4e63-a577-533e26a5cdcf.png"></kdb>

**Comment by pdurbin** [comment]
@jggautier thanks for the comment at https://github.com/IQSS/dataverse/issues/9619#issuecomment-1802562969

Yes, this issue has been fixed by the following pull request:

- #10020

Closing.
