### ISSUE TITLE
The calendar annoyingly reappears after date selection during embargo creation

### ISSUE THREAD

**Issue by tjouneau** [IQSS/dataverse#8566]
**What steps does it take to reproduce the issue?**
Select files and set embargo.

* When does this issue occur?
When selecting the date for the embargo, the calendar briefly disappears then reappears, probably because the cursor is still in the date field (Firefox 98.0.2).

* What did you expect to happen?
It would be best if the calendar would completely vanish after the single click of the date selection. Currently the user has to click somewhere on the side to make it disappear.

**Which version of Dataverse are you using?**
5.10

Thanks!

**Comment by pdurbin** [comment]
I can reproduce this on https://demo.dataverse.org running 5.10. I only tried Firefox. I agree it's a little annoying. The "Enter a short reason why this embargo exists" field is covered up until you click somewhere (as a workaround I can hit the Tab key to advance to that field):

<img width="739" alt="Screen Shot 2022-04-01 at 8 59 55 AM" src="https://user-images.githubusercontent.com/21006/161268421-7151b028-1d69-412d-b0a4-6096a04a9462.png">

**Comment by qqmyers** [comment]
FWIW: I think this is just the stock PrimeFaces datepicker component - it's possible there is a param to change this behavior - either in PF 10 or PF 11 (not yet in Dataverse) - that would make this easy to fix. (If not we may want to decide whether to report to them vs. fix ourselves.)

**Comment by pdurbin** [comment]
When I play around in the PrimeFaces showcase at https://www.primefaces.org/showcase/ui/input/datepicker/datePicker.xhtml (currently running PrimeFaces 11), the calendar behaves as I expect. That is, after you pick the date, the calendar disappears. Definitely something test as we upgrade to PrimeFaces 11:

- #8456

**Comment by pdurbin** [comment]
@tjouneau we upgraded to PrimeFaces 11 in 5.11. Can you please try again at https://demo.dataverse.org ? Any better?

**Comment by tjouneau** [comment]
For me it's fine now. Thanks!
