### ISSUE TITLE
ShibAttributeCharacterSetConversionEnabled has no influence on affiliation

### ISSUE THREAD

**Issue by jahbra** [IQSS/dataverse#8573]
**What steps does it take to reproduce the issue?**

* When does this issue occur?
If you get the affiliation via shibboleth and use ShibAttributeCharacterSetConversionEnabled set to true

* Which page(s) does it occurs on?

* What happens?
affiliation has garbled chars from bad utf-8 conversation

* To whom does it occur (all users, curators, superusers)?
all users

* What did you expect to happen?
the following code has to be enabled for affiliation too
Shib.java:
if(systemConfig.isShibAttributeCharacterSetConversionEnabled()) {
                        attributeValue= new String( attributeValue.getBytes("ISO-8859-1"), "UTF-8");
                }

**Which version of Dataverse are you using?**
5.9 

**Any related open or closed issues to this bug report?**
no

**Comment by pdurbin** [comment]
@jahbra thanks for the bug report. This was added by @pallinger in pull request #6956 but I don't know if they're available to help troubleshoot.

The setting is on/true by default. You can prevent the character conversion by setting it to false. Does that help?

**Comment by jahbra** [comment]
Hi, Thanks for the answer.
Setting it to false did not work If I set it to false everything is not shown correct. 
If I set character conversion to true name and everything is shown correct but affiliation is not. So my guess is, that affiliation is treated different and does not benefit from the (attributeValue.getBytes("ISO-8859-1"), "UTF-8") treatment.

**Comment by pallinger** [comment]
Hello, I will try to test this on our dev server, although I may need some setup to have appropriate test data on the IdP. If you have specific test data we may be able to whip up a correct conversion function. It may also be that your IdP has different fields in different formats. :\

**Comment by jahbra** [comment]
Yes, testdata and idp is not easy, if you lack the permissions like I do. Solved it by configuring the shibboleth attribute-map.xml sp in this way:

<Attribute name="urn:oid:2.5.4.10" id="sn"/> 
and
curl -X PUT -d "sn" http://localhost:8080/api/admin/settings/:ShibAffiliationAttribute

normally Organisation ("Universität") now surname and affiliation.
The same field for both surname and affiliation
As surname diacritics is displayed correct, as affiliation I get: UniversitÃ¤t

**Comment by pdurbin** [comment]
@pallinger have you had a chance to test this? Thanks!

**Comment by pdurbin** [comment]
Hmm, it looks like I approved this PR by @pallinger and didn't notice that we should have updated `getValueFromAssertion` as well:

- #6956

@PaulBoon @pallinger would either of you like to make a pull request to fix this? 😅

**Comment by pdurbin** [comment]
Nice. @pallinger do you have time to test this?

**Comment by PaulBoon** [comment]
@pdurbin The simplest thing to do was ignoring the UnsupportedEncodingException, but maybe we should let the login fail?

**Comment by pallinger** [comment]
@pdurbin I could compile and run the version on our test server, but I could not really test it as I do not have a test IDP that I could use to get iso1-encoded affiliation values. Otherwise, shibboleth login continues to work.
That said, I have examined the pull request, and seems to be okay for me. Very unlikely to cause problems.
