### ISSUE TITLE
Notification for email verification: notifications should include a more useful message so users understand what they are seeing

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#8582]
We are getting unnecessary emails about failed email verifications from users creating accounts, when this is a known bug/issue.
It would help mediate support tickets in RT if we added a note that assured users that their emails were verified so they don't continue to send tickets to support.

**Comment by pdurbin** [comment]
In 904a4e7 I fixed a bug having to do with two browsers. This is in pull request #8579 

Imagine the following scenario:

- You are logged into Dataverse from your desktop browser. You click the button to send a verification email.
- On your phone, you get the email verification link and tap it. On your phone's browser you see "success, verified'.
- Back on your desktop browser, it still shows not verified.

In the fix above, I made it so we look up the user more often to know the latest of if it's verified or not.

**Comment by pdurbin** [comment]
In dc03e3d (also in pull request #8579) I attempted to expose more information to the user about any errors with processing their email verification token. I don't expect a huge benefit from this because the page will most often say "Invalid token" for a non-existent or expired token. It looks like this:

![Screen Shot 2022-04-11 at 4 08 14 PM](https://user-images.githubusercontent.com/21006/162825977-c13573c5-f3b3-4ac7-86eb-1d6b0448d381.png)

I also added more logging in server.log for sysadmins. Users can't see this, of course, but maybe it will help with troubleshooting.

**Comment by pdurbin** [comment]
@sbarbosadataverse there are a lot of good fixes in pull request #8579 and I've marked it to close this issue when it gets merged.

I looked through old RT tickets from November until now and noticed that several users reported receiving the same nonsensical email I did when I clicked "Verify Email". There's no link, nothing to do. Here's a screenshot.

![162015182-0fd16d49-1aaa-4e28-80d1-e91d2ac752dd](https://user-images.githubusercontent.com/21006/162831223-fc620812-52f2-4971-b305-0f7afb0772ef.png)

Here are all the cases of this I found in RT:

- https://help.hmdc.harvard.edu/Ticket/Display.html?id=316215
- https://help.hmdc.harvard.edu/Ticket/Display.html?id=315336
- https://help.hmdc.harvard.edu/Ticket/Display.html?id=312844
- https://help.hmdc.harvard.edu/Ticket/Display.html?id=312844
- https://help.hmdc.harvard.edu/Ticket/Display.html?id=312043

For a lot of the other RT tickets, the exchange often went like this:

- User: I'm having trouble confirming my email.
- Support: It's buggy and you don't need to anyway.
- User: Ok thanks (or crickets)

The thing I learned from working with user (and @kcondon ) on the ticket you gave me ( https://help.hmdc.harvard.edu/Ticket/Display.html?id=318230 ) is that the user was seeing "Not Verified" but the database showed the email was verified. The "look up the user more often" fix I mentioned above should help with this.

Obviously, if the pull request gets merged and deployed to Harvard Dataverse and we still are seeing lots of support tickets, let's open a new issue and work on the next round of bugs.
