### ISSUE TITLE
Keep or make editable the order of entries in the metadataLanguage dropdown list

### ISSUE THREAD

**Issue by tjouneau** [IQSS/dataverse#8588]
**What steps does it take to reproduce the issue?**
Configure a list of languages by populating the :MetadataLanguages setting.
`curl http://localhost:8080/api/admin/settings/:MetadataLanguages -X PUT -d '[{"locale":"en","title":"Anglais (English)"},{"locale":"fr","title":"Français (French)"},{"locale":"de","title":"Allemand (German)"},{"locale":"es","title":"Espagnol (Spanish)"},{"locale":"it","title":"Italien (Italian)"},{"locale":"pt","title":"Portugais (Portuguese)"}]'`
Consider the order in which they appear at dataset creation.
![image001](https://user-images.githubusercontent.com/6040893/162422291-ca65fcdc-b139-4a20-ace3-129bf1b18e99.png)

* When and on which page(s) does this issue occur?
At dataset creation.

* What happens?
The order in which they appear does not correspond to the one in the request, nor the alphabetical order of "locale" or "title".

* To whom does it occur (all users, curators, superusers)?
All users

* What did you expect to happen?
The order of the array sent to the :MetadataLanguages setting should ideally be kept. In our use case, we would prefer English and French to appear first.

**Which version of Dataverse are you using?**
5.10

**Any related open or closed issues to this bug report?**
None identified.

**Comment by pdurbin** [comment]
@tjouneau thanks for letting us know at https://github.com/IQSS/dataverse/issues/4632#issuecomment-1266816411 that

"TBH we only retained two languages, English and French."

Does that mean you don't really worry about the order anymore?

**Comment by tjouneau** [comment]
@pdurbin We originally restrained this because of the order not being editable, that's true. I still think it would be better to have a default language and an editable order afterwards.
As for us specifically, as we are on a path to merge into recherche.data.gouv.fr eventually, I think we will content ourselves with what exists.

**Comment by pdurbin** [comment]
@tjouneau ok. Sounds good. Please do feel free to create a fresh issue in the future! A default language and an editable order afterwards makes sense to me. Or maybe simply the order in the JSON that is sent in the setting, as you suggested above.
