### ISSUE TITLE
Login: Request username

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#859]
This was originally part of #416 but as implemented only allowed for reset of password.
I'm not sure we want to do this or it is advisable but recording it here for review.

**Comment by eaquigley** [comment]
Moving to post 4.0 as there is a way in 4.0 to get your username. If you request a password change, you also get your username sent to you in the email. For 4.0, all we need to do is reword the language on the forget/reset password page and button to include username.

**Comment by kcondon** [comment]
Now logging in with email makes this less necessary. Closing
