### ISSUE TITLE
Default header is not replaced by custom header 

### ISSUE THREAD

**Issue by j-n-c** [IQSS/dataverse#8591]
**What steps does it take to reproduce the issue?**
- Copy an html file containing a custom header (e.g. [https://guides.dataverse.org/en/latest/_downloads/4e2c4e359b641142d3b5d34f979248b0/custom-header.html](https://guides.dataverse.org/en/latest/_downloads/4e2c4e359b641142d3b5d34f979248b0/custom-header.html)) to dataverse (e.g. `/usr/local/payara5/glassfish/domains/domain1/docroot/`)
- Configure dataverse to use this customized header: `curl -X PUT -d '/usr/local/payara5/glassfish/domains/domain1/docroot/custom-header.html' http://localhost:8080/api/admin/settings/:HeaderCustomizationFile`
- Test
- Disable default Dataverse theme `curl -X PUT -d 'true' http://localhost:8080/api/admin/settings/:DisableRootDataverseTheme`)
- Test

* When does this issue occur?
When trying to use a customized header

* Which page(s) does it occurs on?

* What happens?
- Customized header does not replace default header. Instead, both headers are displayed
- Disabling/enabling default Dataverse theme `curl -X PUT -d 'true' http://localhost:8080/api/admin/settings/:DisableRootDataverseTheme`) does not have any impact

* To whom does it occur (all users, curators, superusers)?
all users

* What did you expect to happen?
Custom header should replace default header

**Which version of Dataverse are you using?**
Tested with 5.9, 5.10 and 5.10.1
This is also happening both on a running server and on a vagrant deploy

**Any related open or closed issues to this bug report?**
Not specifically related to this behaviour

**Screenshots:**

No matter the issue, screenshots are always welcome.

![custom_header_error](https://user-images.githubusercontent.com/17250006/162479616-a0ead7b1-6371-477c-8d9b-33137210871c.png)

**Comment by pdurbin** [comment]
@j-n-c hi! As @shlake said at https://groups.google.com/g/dataverse-community/c/zoYOSljACNA/m/Ck5DRhaXAAAJ you can't replace navbar, which you have highlighted in yellow. Above it you can add a custom header, which you have highlighted in red.

There's a lot going on in the navbar such as login and logout. Are you thinking you'd replicate all that functionality in your custom header?

What if we simply document better the parts of the page and set expectations about what can be customized in the header? If so, perhaps we could change the title of this issue (or make a new one) to reflect what the "definition of done" for this issue could be.

**Comment by j-n-c** [comment]
Hi @pdurbin. From @shlake document (https://github.com/IQSS/dataverse/files/2128735/UVaHomePage.pdf) the distinction between the header and navbar was not clear to me. I thought the navbar was a part of the header, that by inserting a custom header, one had to handle the menus on the desired navbar (if present).

I think the solution you propose (better documentation and expectation handling) is a very good compromise. If you agree I can contribute with some inputs for the documentation building up from @shlake document.

Would You prefer to open a new issue or change the change the description fromthis one?

**Comment by pdurbin** [comment]
@j-n-c honestly, I do love a fresh clean issue! So when you get a chance, please feel free to close this one and open a new one.

While that PDF from @shlake is very nice, it might be best to explain things better in the guides themselves, rather than linking to a PDF. Easier to maintain, a living document, all that. So please feel free to get creative about how to document this! 🤔 🎉 🚀

**Comment by j-n-c** [comment]
Will be handled in https://github.com/IQSS/dataverse/issues/8617
