### ISSUE TITLE
Write Dataverse Administration Documentation (User Guide)

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#86]
---

Author Name: **Elizabeth Quigley** (@eaquigley)
Original Redmine Issue: 3495, https://redmine.hmdc.harvard.edu/issues/3495
Original Date: 2014-02-03
Original Assignee: Eleni Castro

---

Setup sections for:

- Create
- Edit
- Publish

Available on git: https://github.com/IQSS/dataverse_temp/blob/master/doc/Sphinx/source/User/dataverse-management.rst

---Need to review these after beta---
Customize
Collections information for 3.6.1. in here since they are now Dataverses
Classifications
Templates
Guestbook
Download Tracking Data

**Comment by posixeleni** [comment]
@eaquigley is this something you are working on? I see its assigned to me but I'm working on the Dataset documentation section. Just want to make sure we dont duplicate our efforts.

**Comment by eaquigley** [comment]
@posixeleni please assign it to me; I worked on it in the past so I'll finish it up.


On Mar 27, 2015, at 10:06 AM, Eleni Castro <notifications@github.com<mailto:notifications@github.com>> wrote:


@eaquigley<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_eaquigley&d=BQMCaQ&c=WO-RGvefibhHBZq3fL85hQ&r=Y9aY3P6kFFpmMLaYYO_id08dS3gL1xWMQuI2CZ74PoI&m=SKFqexkpBU51b-PaNoEZyIStfhA_5Y61ijXQXM2f2Ro&s=TYE2ouO3TeYj-wTuf0_K_mW3QYSpn3bUyk7xivieygA&e=> is this something you are working on? I see its assigned to me but I'm working on the Dataset documentation section. Just want to make sure we dont duplicate our efforts.

**Comment by eaquigley** [comment]
done. closing ticket.
