### ISSUE TITLE
Reset Password: In successfully changed email, put link to contact us.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#860]
Current success email may need link for how to contact us:

Hi kc825b tester,

Your Dataverse account password was successfully changed.

Please contact us if you did not request this password reset or need further help.

Thank you,

Dataverse Support Team

**Comment by scolapasta** [comment]
This will also need to be configurable per installation, so not a trivial thing.

**Comment by eaquigley** [comment]
Hmmm so this seems like it could be why we never went back and changed do-not-reply to support@ 

As that change happened in #2072 and we now have a way for users to contact support directly from the email, I am going to pass this ticket to QA to close.
