### ISSUE TITLE
Feature Request/Idea: BagIt Support - Add automatic checksum validation on upload

### ISSUE THREAD

**Issue by adaybujeda** [IQSS/dataverse#8608]
**Overview of the Feature Request**
Add automatic checksum validation if the file uploaded to Dataverse is in BagIt format.
Upon file upload, we will detect if it is a Bag and perform file checksums against the Bag manifest.
If there are checksum errors, we will display a warning message to the end-user.

UI changes still to be discussed.

**What kind of user is the feature intended for?**
Curator and Depositor

**What inspired the request?**
As part of the Harvard Data Commons project there is a requirement to add support for BagIt. The first iteration is to simply inspect the manifest files and perform a file validation when a new deposit is made.

**What existing behavior do you want changed?**
We want to enhanced the upload functionality to add the file validation based on the BagIt manifest.

**Any brand new behavior do you want to add to Dataverse?**
No

**Any related open or closed issues to this feature request?**
N/A

**Comment by shlake** [comment]
To support this, this issue needs to be fixed: #8449 
As the checksum in the manifest is for the original uploaded file, but the ingested "tab" file is what is in the bag.

**Comment by adaybujeda** [comment]
We had a first attempt at the UI to provide feedback to the users when uploading BagIt packages.
Here is an screenshot for when we find errors in the checksums:

<img width="1444" alt="Screenshot 2022-04-29 at 16 05 27" src="https://user-images.githubusercontent.com/17336210/165972406-81861dd9-9824-4a5b-a5b5-84268c565a94.png">

**Comment by adaybujeda** [comment]
Created a draft PR to start the conversation about the implementation.

**Comment by adaybujeda** [comment]
A demo of the functionality and a AWS environment has been shared with a group from the `Instituto Brasileiro de Informação em Ciência e Tecnologia`

**Comment by adaybujeda** [comment]
The final implementation is ready for review. PR: https://github.com/IQSS/dataverse/pull/8677
