### ISSUE TITLE
Search: Newly created datasets or newly added cvv fields are not searchable

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#8633]
Noticed in v5.10.1.

CVV fields such as Subject in the Citation block are not searchable for newly created datasets or if the CVV field was newly added where it had not existed before.

Steps to reproduce:
1. For convenience in limiting results, create a new dataset, then create a new dataset, add Chemistry as the subject, save
2. Type Chemistry into basic search or select it in advanced search, search on it. No results found.
3. Choose an existing dataset that is older, search on subject, it should be found.

**Comment by pdurbin** [comment]
Yuck. You're right. If I use the "Advanced Search" page to construct a query for datasets with "Chemistry" as the subject, I get no results:

![Screen Shot 2022-04-21 at 3 58 50 PM](https://user-images.githubusercontent.com/21006/164542752-b8d32288-5c71-472a-b599-f9a0c43c7088.png)

![Screen Shot 2022-04-21 at 3 58 23 PM](https://user-images.githubusercontent.com/21006/164542693-622894fb-5ae8-4768-bcac-d1dea00512aa.png)

By running the `query` script to dump the Solr data and grep for Chemistry I can find my dataset:

```
scripts/search/query | grep Chemistry
        "subject_ss":["Chemistry"],
```

Does this mean that we somehow changed the search field from `subject` to `subject_ss`? This strikes me as backward incompatible (think OAI-PMH sets or saved searches). At the very least, field needs to line up with what's filled in by the "Advanced Search" page.

This pull request that was merged as part of 5.10.1 seems related, at least:

- #8435

**Comment by ErykKul** [comment]
Fixed in the linked pull request https://github.com/IQSS/dataverse/pull/8624 :
![image](https://user-images.githubusercontent.com/101262459/164633100-46884f4b-04eb-4c9f-a140-473e23fc2c2b.png)

**Comment by ErykKul** [comment]
After merging reindexing will berequired.

**Comment by mreekie** [comment]
sprint:
 - The behavior is well understood.
 - The solution is not clear.
 - there is an attached PR.
 - Jim suggests that this may be an issue he introduced.
 - sounds like it started in 5.10 or 5.10.1
 - might be specific to controlled vocabularied.
 - small.  There is a PR against this that needs to be checked. 

We will remove this from the board
The attached PR will take the place of this in the sprint.
The attached PR is linked to this as closing it.
