### ISSUE TITLE
Feature Request/Idea: allow setting FAKE DOI validation via default.config file

### ISSUE THREAD

**Issue by carlsonp** [IQSS/dataverse#8635]
**Overview of the Feature Request**

The `default.config` file that is read in as part of the installation process has the test validation DOI endpoint listed.  It would be nice if it could also work with setting the [FAKE DOI provider](https://guides.dataverse.org/en/5.10.1/developers/dev-environment.html#configure-your-development-environment-for-publishing).  Right now, the only ability to set this seems to be after Dataverse starts up and to set it via a `curl` command as per the example in the documentation.

**What kind of user is the feature intended for?**
(Example users roles: API User, Curator, Depositor, Guest, Superuser, Sysadmin)

**What inspired the request?**

Discussion in chat

**What existing behavior do you want changed?**

**Any brand new behavior do you want to add to Dataverse?**

**Any related open or closed issues to this feature request?**

Not that I am aware.

**Comment by pdurbin** [comment]
Just a quick note that `:DoiProvider` is set to "DataCite" by the setup all script:

https://github.com/IQSS/dataverse/blob/v5.10.1/scripts/api/setup-all.sh#L60

In 791d1fa we made the password for dataverseAdmin configurable. Maybe we could so something similar here.

**Comment by pdurbin** [comment]
@carlsonp are you interested in creating a pull request for this?

If we had this, we could remove this step from the dev guide: https://guides.dataverse.org/en/5.11.1/developers/dev-environment.html#configure-your-development-environment-for-publishing

**Comment by carlsonp** [comment]
Possibly.  What file(s) and sections do you feel would need to be modified or adjusted?

**Comment by pdurbin** [comment]
@carlsonp on second thought, let's talk to @poikilotherm and see if this PR of his will meet your needs:

- #8828

**Comment by pdurbin** [comment]
Sadly, Patrick's org didn't go with Dataverse. Closing.
