### ISSUE TITLE
Dashboard > Harvesting Server links to unexisting section of the User Guide

### ISSUE THREAD

**Issue by j-n-c** [IQSS/dataverse#8640]
**What steps does it take to reproduce the issue?**

    - Login as superuser
    - Navigate to Dashboard > Harvesting Server > Manage Server
    - Click _Harvesting_ link under section _How to run a Harvesting Server?_ 

* When does this issue occur?
When trying to see documentation about Harvesting

* Which page(s) does it occurs on?
http://<dataverse_host>/harvestsets.xhtml?dataverseId=<id>

* What happens?
The link redirects to the User Guide index page, but the Harvesting documentation is in Admin Guide

* To whom does it occur (all users, curators, superusers)?
superusers

* What did you expect to happen?
The link would redirect to the Harvesting documentation page

**Which version of Dataverse are you using?**
5.10.1

**Any related open or closed issues to this bug report?**
N/A

**Screenshots:**

No matter the issue, screenshots are always welcome.

To add a screenshot, please use one of the following formats and/or methods described here:

* https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests
*

**Comment by kcondon** [comment]
@j-n-c Hi, Can you send a quick screenshot of where the link is? I'm not finding it in the UI under dashboard, manage server.
