### ISSUE TITLE
Terms of Access from Template not carried over into restrict file popup (on Dataset Create)

### ISSUE THREAD

**Issue by sekmiller** [IQSS/dataverse#8646]
**What steps does it take to reproduce the issue?** Add a Template that includes Terms of Access for Restricted files. On dataset create apply that Template and while in create mode of the dataset upload a file and try to restrict it. When the popup appears the Terms of Access from the template do not appear. If you go on to restrict the file by setting "Allow Access Request" to true the Terms of Access from the Template are not carried over into the created dataset. (If you create a dataset with the Template, but do not restrict a file on create the terms will be added to the dataset as expected.)

* When does this issue occur? On Dataset create via the UI

* Which page(s) does it occurs on? Dataset Page 

* What happens? described above

* To whom does it occur (all users, curators, superusers)? anyone with create dataset permission

* What did you expect to happen? I would expect that the Terms of Access from the Template would appear in the access popup where they could be accepted or edited

**Which version of Dataverse are you using?** 5.10.1 dev

**Any related open or closed issues to this bug report?**

**Screenshots:**

No matter the issue, screenshots are always welcome.

To add a screenshot, please use one of the following formats and/or methods described here:

* https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests
*

**Comment by mreekie** [comment]
Sprint
 - it's a bug stece found that is newer related to recent license related changes
- small.

**Comment by sekmiller** [comment]
Upon re-examining this. The issue is that the Terms are coming from the default template and changing the template on dataset create is not updating the default terms to the terms on the alternate (selected) template
