### ISSUE TITLE
Update Dataset API fails with 500 error

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#8686]
From an RT ticket, we got a report that updating a dataset on demo dataverse is resulting in a 500 error. I was able to reproduce.

Here is the curl command (the json file is attached, though I had to change the extension to .txt in order to attach):
```curl -H "X-Dataverse-key: XXXXXXXXXXX" -X PUT "https://demo.dataverse.org/api/datasets/:persistentId/versions/:draft?persistentId=doi:10.70122/FK2/BONNFM" --upload-file dv_obj.json```

[dv_obj.txt](https://github.com/IQSS/dataverse/files/8662939/dv_obj.txt)

Here is the server.log error:
```
[#|2022-05-10T11:29:34.724-0400|SEVERE|Payara 5.2021.5|edu.harvard.iq.dataverse.api.errorhandlers.ThrowableHandler|_ThreadID=195;_ThreadName=http-thread-pool::jk-connector(7);_TimeMillis=1652196574724;_LevelValue=1000;|java.lang.NullPointerException
	at edu.harvard.iq.dataverse.util.json.JsonParser.parseMetadataBlocks(JsonParser.java:405)
	at edu.harvard.iq.dataverse.util.json.JsonParser.parseDatasetVersion(JsonParser.java:372)
	at edu.harvard.iq.dataverse.util.json.JsonParser.parseDatasetVersion(JsonParser.java:295)
```

**Comment by mreekie** [comment]
sprint
 - small. reproducible.
 -

**Comment by mreekie** [comment]
- in WIP at end of [pm.sprint.2022_05_11](https://github.com/IQSS/dataverse/labels/pm.sprint.2022_05_11)
