### ISSUE TITLE
Spike: Sync up on Dataverse/Open DP integration

### ISSUE THREAD

**Issue by mreekie** [IQSS/dataverse#8705]
The objectives of this spike:
- Bring members of the DV team (e.g. Mike, Len) more up-to speed on the details of the OpenDP work.
- Discuss design, assumption, requirements of the work as it's being implemented.
- net/net get us all on the same page.

Here is the doodle link for scheduling a meeting:
https://doodle.com/meeting/participate/id/dNkqEGme

Def of done:
- Meeting of the people impacted and involved ( ideally in person with a whiteboard)
- documentation of any outcomes, next steps, decisions made.

Key people:
- Gustavo Durand
- Bob Treacy
- Raman Prasad
- Ellen Kraffmiller
- Len Wisniewski

Optional:
- Annie Wu
- Mike Reekie

Related to:
- https://github.com/IQSS/dataverse/issues/7715
- https://github.com/opendp/dpcreator/issues/127
- https://github.com/opendp/dpcreator/issues/90
- https://github.com/IQSS/dataverse/issues/8737

**Comment by mreekie** [comment]
This comment is just to make folks aware of the issue:
@scolapasta @rtreacy @lenwiz @ekraffmiller @raprasad

**Comment by mreekie** [comment]
I met with Annie yesterday and got a really basic overview of the relationship between OpenDP and DV that we are discussing.  

She walked me through the [DP Creator Demo Beta Instructions v1](https://docs.google.com/document/u/1/d/e/2PACX-1vRlZ2IgigIhl4oz_uOakQPxovzlrmFkbD-x_9RUO31dC0eRq2wCt_vN2Go0_9LTRd67srjgy04CfPVk/pub) document.

The document provides a good framework for discussing things.
Roughly you:
- create a dataset in dataverse from your data to be analyzed.
- open DP creator application (launching it from within dataverse)
- log into DP creator
- Transfer the dataset over to DP creator and analyze it.
- Send the new dataset back.

There is an assumption that in the final product (the demo does not assume this) the data you are processing is sensitive and that this sensitive data is going to be stored in dataverse
- This then implies that dataverse supports sensitive data storage.
- This then implies that dataverse supports secure authentication/authorization for users.

**Points for the discussion:**
- Dataverse does not currently support sensitive data at rest.
- Dataverse does not support the user AA required as part of supporting sensitive data.
- It's currently on the roadmap but its far out.
  - There is discussion of deprecating this issue based on the latest NIH grant work. It sounds like there are data repositories that specialize in storing sensitive data.
  - In place of directly supporting sensitive data there is discussion of working with these other directories (maybe via harvesting? - just a guess) to get the sensitive data to and from DP creator
 

anyone feel free to correct any misinformation here.

**Comment by qqmyers** [comment]
FWIW: It would be useful to separate out where requirements can't be met due to software limitations versus the configuration of Harvard DV and/or policy issues. For example, while DataTags isn't implemented, S3 stores can be configured to encrypt stored data - is that sufficient to meet sensitive data requirements technically (if configured?). Similarly, Dataverse authenticates users so what aspect of AA is required, if any, that isn't available technically versus not currently configured?

**Comment by mreekie** [comment]
> FWIW: It would be useful to separate out where requirements can't be met due to software limitations versus the configuration of Harvard DV and/or policy issues. For example, while DataTags isn't implemented, S3 stores can be configured to encrypt stored data - is that sufficient to meet sensitive data requirements technically (if configured?). Similarly, Dataverse authenticates users so what aspect of AA is required, if any, that isn't available technically versus not currently configured?

@qqmyers 
- This is a valid point.
- Tomorrow will get us closer to understanding things.

**Comment by mreekie** [comment]
For the May 24th meeting. Agenda:
- Walk the flowchart "Storing sensitive data in Dataverse and Processing it in DP Creator" that is  based on the  guide that Annie Wu wrote. This provides us a common starting point.
- Identify the points where support is needed & is lacking from dataverse in order DP Creator to satisfy it's orignal design.
- Len discusses his thoughts regarding an alternative based on his work with the NIH working groups so far.

Summarize:
- any decisions.
- any points where clarification is still needed.
- Next steps.

The flowchart is published in a public board in miro
https://miro.com/app/board/uXjVOyWuciE=/?share_link_id=363863912754

**Comment by mreekie** [comment]
- in WIP at end of [pm.sprint.2022_05_11](https://github.com/IQSS/dataverse/labels/pm.sprint.2022_05_11)

**Comment by mreekie** [comment]
Three items came out the meeting

- DV and Open DP teams will collaborate on a way to get DP Creator to work on this particular demo.
- Explore the best way to architect the method that DP creator data accesses Dataverse and other repositories
  - This discussion needs to take into account the grant funding and deliverables
  - During the meeting the TRSA work came up as a possible solution.  There are bi-weekly meetings that Raman and

Jump start continuing conversations towards a long term solution by expanding the conversation:

**TODO**: Bob, Raman, Gustavo meet next Thursday PM to figure out a way forward for the DP Creator demo. This is highest priority.

**TODO**: Invite members of this meeting to discuss TSRA with Jon Crabtree and Jim Myers of the GDCC at UNC




Notes:
It sounds like TRSA is one way to securely transmit sensitive meta data between two targets as a  broker or a middle man.  Then the data would be transmitted directly from a source repository. (Don't quote me on this description).

This sounds like it's generally the same idea as the harvard data tags feature.

**Comment by mreekie** [comment]
- proposed a meeting next Thursday at 3PM
  -  Bob, Gustavo, Raman
  - Left the invite editable by the particpants

**Comment by raprasad** [comment]
Brief slides on current state of the integration re: api key/token: https://docs.google.com/presentation/d/1oLQqF7nEGpPFpyarr6BwfQqzDYuytYwIyMXK3OS1Gh8/edit?usp=sharing

**Comment by mreekie** [comment]
Meeting notes from June 2 meeting.

The current objective is still to support only a demo version. This is not a permanent solution, but the work here may be useful to other dataverse users.

There was agreement that supporting the ability to use POST in addition to Get in the external tools framework may also be helpful to others in the community and so it's worth putting some work into this versus our first idea which was a one-off code modification.  
  - It was agreed that for most external applications, the current use of the GET to launch the external application is working fine.
  - It was noted that TSRA and others will eventually want to create POSTS. 
    -  After the meeting Jim clarified that the important part of the TRSA discussion is that "... the URL creation and validation class in Bob's branch was created for it ([it comes from my Oct 2020 PR](https://github.com/IQSS/dataverse/pull/7325/files#diff-9fe11f3c4ea1402b2c5d730421865056c0bec1869c7f423f49204094a7969632)). The idea there was that Dataverse could send a signed URL for a remote store's API to that remote store and it would then validate the signature before giving the user access to the remote file. That is ~backward from the current case where we're signing a call to the Dataverse API and it is Dataverse that has to validate the signature. (TRSA is also not doing anything with the external tools mechanism).
 - Raman raised a question about pop-up settings in the browser interfering with the user experience.  It was captured in a new issue: [Feature Request/Idea: Dataverse External Tools Fail if Pop-ups are blocked which is easy to miss](https://github.com/IQSS/dataverse/issues/8766#)
 - Ellen asked for input on whether or not the team thought that there was a strong use case for DP creator for L2 data that is restricted.  We had a short discussion about this and agreed that Sonia may be a good person to start with.

**Comment by mreekie** [comment]
This issue has served it's purpose.
