### ISSUE TITLE
Integrate with DataTags

### ISSUE THREAD

**Issue by mercecrosas** [IQSS/dataverse#871]
Integration of Dataverse with DataTags through API.

**Comment by mheppler** [comment]
Resources:

- [DataTags, the Tags Toolset, DataTags, and Dataverse Integration (PDF), Michael Bar-Sinai](http://projects.iq.harvard.edu/files/dcm2016/files/datatags-dvncm16_1.pdf)

- [The DataTags System: Sharing Sensitive Data with Confidence (PDF), Mercè Crosas](http://scholar.harvard.edu/files/mercecrosas/files/dataverse-datatags-mercecrosas.pdf)

- [Open Source Tools Facilitating Sharing/Protecting Privacy: Dataverse and DataTags (PDF), Mercè Crosas}(http://scholar.harvard.edu/files/mercecrosas/files/dataverse-datatags-mercecrosas.pdf)

- [Sharing Sensitive Data with Confidence: The DataTags System (PDF), Mercè Crosas](http://scholar.harvard.edu/files/mercecrosas/files/datatags-crosas-sweeney-bar-sinai.pdf)

(As mentioned in reply to a [user email[(https://groups.google.com/d/msg/dataverse-community/1BtCe29Dhp0/pZppsTTc-MoJ) to the Dataverse User Community list. More of [Mercè's presentations](http://scholar.harvard.edu/mercecrosas/presentations) are available on her site.)

**Comment by pdurbin** [comment]
Closing in favor of this issue:

- https://github.com/IQSS/dataverse-pm/issues/148
