### ISSUE TITLE
Bug: embargoed files can be downloaded after private URL is shared

### ISSUE THREAD

**Issue by eunices** [IQSS/dataverse#8710]
**What steps does it take to reproduce the issue?**
1. Create a dataset
2. Add data files
3. Publish v1 dataset
4. Add data files
5. Publish v2 dataset
6. Add **embargo** to all files in all versions in the dataset using superuser API
7. Make change to metadata
8. Create private URL on DRAFT
9. Logout and stay logged out.
10. Go to private URL and attempt to download files. It should download.
11. Go to dataset page showing the latest draft (e.g. URL that looks like https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/I6PMAE, without DRAFT tag). Attempt to download files. Files can be downloaded, but should not be downloaded.

* When does this issue occur?
As described above.

* Which page(s) does it occurs on?
Dataset page

* What happens?
Embargoed files can be downloaded on published datasets, after accessing the private URL.

* To whom does it occur (all users, curators, superusers)?
All users who have the private URL and published dataset with embargoed files.

* What did you expect to happen?
I should not be able to download embargoed files on published datasets.

**Which version of Dataverse are you using?**
5.8

**Any related open or closed issues to this bug report?**
Not that I know of

**Screenshots:**

On the dataset page (with the latest dataset, and no DRAFT tag)
![image](https://user-images.githubusercontent.com/4596893/168980465-d3ffc610-5b0c-4027-88d3-73709fbe7b5f.png)

**Comment by eunices** [comment]
If the private URL is meant to give data file download access to all versions, then it might not exactly be a bug. 
However, the preferred behaviour should be: private URL gives access only to DRAFT version or at the least retain embargo of other published files.

**Comment by pdurbin** [comment]
@eunices I hear your use case but I'd like to point out that a Private URL grants "Member" permission on the dataset:

<img width="895" alt="Screen Shot 2022-05-19 at 4 51 11 PM" src="https://user-images.githubusercontent.com/21006/169402444-1d19460e-f53c-4291-b34f-992c3c6cc647.png">

A more technical explanation can be found at https://github.com/IQSS/dataverse/blob/v5.10.1/src/main/java/edu/harvard/iq/dataverse/privateurl/package-info.java

I guess I'd encourage you to think about the Member role. Right now it allows you to download files, all files from all versions, as far as I know, and from what you're saying, it doesn't matters if files are embargoed. That "DownloadFile" permission is what is granted to a user who goes through the "Request Access" process for a restricted file. There's a lot tied up in your use case. 😄

**Comment by eunices** [comment]
Yes, I noticed that it grants the member role on the dataset permission... So it's token based (private URL has a token) and session cookie (sorry if I am mangling the terms)? With the private URL, there's no login.

Maybe the private URL's member cookie can be cleared on the dataset page. It's still a little surprising to see embargoed files (on a published dataset) downloadable, after navigating away from the private URL, on the dataset page. 

I can close the issue, if it is a non-issue though
