### ISSUE TITLE
Linking Dataverse does not update child dataset indexes

### ISSUE THREAD

**Issue by sekmiller** [IQSS/dataverse#8724]
Very closely related to: 
- #7430  

**What steps does it take to reproduce the issue?** Link a Dataverse that contains datasets to another dataverse. We expect to see the linked Dataverse's datasets appear on the linking Dataverse's home page. We see the linked Dataverse, but not its datasets.

* When does this issue occur? When  you link a Dataverse that contains datasets.

* Which page(s) does it occurs on? Dataverse page

* What happens? We don't see the datasets contained in the linked dataverse.

* To whom does it occur (all users, curators, superusers)? The end result is seen (or not seen) by all users.

* What did you expect to happen?
We would expect to see the datasets contained in the linked Dataverse to show up on the linking Dataverse's page

**Which version of Dataverse are you using?** 5.10

**Any related open or closed issues to this bug report?**
https://github.com/IQSS/dataverse/issues/7766

**Screenshots:**

No matter the issue, screenshots are always welcome.

To add a screenshot, please use one of the following formats and/or methods described here:

* https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests
*

**Comment by pdurbin** [comment]
There was some recent seemingly related discussion at https://groups.google.com/g/dataverse-community/c/DDmVelt3Zfk/m/_hekZgR4BQAJ and the following issue:

- #7430

**Comment by mreekie** [comment]
Sizing:
 - Deferred
 - we need @sekmiller for this.

**Comment by mreekie** [comment]
Discussed today. Stephen might pull these in if he wants for this sprint.
