### ISSUE TITLE
Improved HTTP Range request support

### ISSUE THREAD

**Issue by haarli** [IQSS/dataverse#8726]
We are currently working on a tool which allows to preview the structure of an uploaded zip file without the need to download the whole file. This requires HTTP range requests support in the Data Access API (api/access/datafile/{id}) for files. I found out that range requests are already supported in Dataverse. However, they do not return required HTTP headers and status to comply with 3rd party tools. So I suggest the following changes:

- If a certain range is requested, the returned status should be 206 (partial content) instead of 200
- A Content-Range header should be returned containing information about the returned bytes
- A Accept-Ranges header with value "bytes" should be returned
- CORS: The "Range" header should be allowed by adding it to "Access-Control-Allow-Headers"
- CORS: Content-Range and Accept-Ranges header should be exposed by adding it to "Access-Control-Expose-Headers"

I'll provide a PR with these changes.

**Comment by qqmyers** [comment]
These seem like useful additions. FWIW: I've also been looking at zip preview, with download of a file from within a zip leveraging the ranged requests (at QDR, primarily in the context of a specific zip format used for qualitative data analysis). I'm interested to see what you come up with and would be happy to compare notes if that's ever useful.

**Comment by haarli** [comment]
Thanks. It's nearly ready, with the ability to download files within the zip using range requests. Here's a preview of the previewer :)

![grafik](https://user-images.githubusercontent.com/5524896/169830943-5522b16f-ddb6-4779-8c32-4cb48e95f0b3.png)



Current code is on https://github.com/MPDL/dataverse-previewers/tree/zip-preview-download if you're interested. 
It uses the zip.js library from Gildas Lormeau (https://github.com/gildas-lormeau/zip.js) and the fancytree library (https://github.com/mar10/fancytree) for rendering the treeview. It works with local file storage and S3 (needs some CORS rules configured)

I'll provide a PR with the complete previewer to the gdcc GitHub repo as soon as we are finished and have tested a bit more.

**Comment by pdurbin** [comment]
Closed by this PR:

- #8727
