### ISSUE TITLE
Instructional text at the top of the Dataset page does not make sense

### ISSUE THREAD

**Issue by TaniaSchlatter** [IQSS/dataverse#8728]
When on the "Add dataset" page in v5.10, there is a line of text at the top of the page:
"Please enter metadata in the language, or change the metadata language choice in the parent dataverse before proceeding."

This text does not make sense. Why was it added? If instructional text needs to appear, it should be in the gray color. 

![Screen Shot 2022-05-23 at 1 41 12 PM](https://user-images.githubusercontent.com/15386424/169877426-59860771-20a9-4992-a00c-313bf7a9ccee.png)

**Comment by mreekie** [comment]
Prio
- May have been introduced accidently in recent build
- Seems straightforward to fix.
- High priority from Tania.
