### ISSUE TITLE
SPSS files download issue

### ISSUE THREAD

**Issue by Gerafp** [IQSS/dataverse#8736]
In recent days. An user needed to download a file from dataverse but the repository responds with a message error. 

![image](https://user-images.githubusercontent.com/25359497/170138915-fde5d462-de83-4ab6-a4ed-0b2601df5ac7.png)

The problem occurs when the user selects “Original File Format (SPSS Binary)” into "Download" button menu.  

![image](https://user-images.githubusercontent.com/25359497/170138971-aca0a93b-2a18-4fc2-9958-35c613f07412.png)

We check the logs files but We don’t see someone message error about this action. 

![image](https://user-images.githubusercontent.com/25359497/170138985-482e34a0-86e5-44ae-bb8c-4f69318ee504.png)

Do you have some idea about this problem? 

The dataset is https://hdl.handle.net/11529/10757. We have dataverse 4.20 in production but we update our dataverse instance to 5.10.1 in a develop enviroment and we have the same problem, too.

**Comment by jggautier** [comment]
Hey @Gerafp. I don't have a solution, but wanted to share that I was planning on opening a GitHub issue about ingested files in the Harvard Dataverse Repository that seem to have the same problem. And in the database's "datatable" table, where the original file sizes are recorded for ingested files, the originalfilesize is "-1". Querying the database that way let me find hundreds of files in the repository, although as far as I can tell none of the files were deposited within the last year or two, so it doesn't seems to be an issue that's happening anymore.

**Comment by qqmyers** [comment]
Hmm, it is hard to debug remotely, particularly if there's no log info about it. In general, there are three possible problems: the file is missing/misnamed, the db has an issue like a bad file size, or there's a bug. The original file should be stored in the same place as the tab version, but with a .orig extension - the location of the file is described by the storageidentifier column in the dvobject table for the id of this file. W.r.t. the db entries, the originalfilesize that Julian mentions is probably the only potential problem (since you can download the tab version, the storageidentifier is correct and there is no separate storagelocation entry for the orig file). If neither of those look like the problem, it could still be a software issue.

**Comment by Gerafp** [comment]
Hi @qqmyers @jggautier 

Thanks for your response. 

Yep. I saw the DB in the dvobject table and check the storageidentifier. The problem is caused for missing files in localstorage. the files are deposited on old datasets. 

For testing porpuse, I copied the 4849 to 4849.orig and I can download the SPSS file. 

![image](https://user-images.githubusercontent.com/25359497/170578960-64cb281f-49df-4f30-bc10-89626ab820b4.png)

I have two questions:

Is the copy correct method for fix this problem?

Is this problem a solved bug?

**Comment by qqmyers** [comment]
That probable isn't a good fix as the original file and the ingested tab version shouldn't be the same. Given the naming of the files - is this a Dataverse instance that was migrated from v3.x? If so, someone who was around at that time may know more about naming conventions back then. (Anyone know if _ was used as a prefix for the original file at that time?)

**Comment by donsizemore** [comment]
@qqmyers I believe I have some PERL lying around on our old Dataverse4 instance which handled this renaming on the filesystem. I glanced through the 3=>4 migration instructions (albeit on my phone) and didn't see this step documented. IIRC it was left as an exercise for the installation admin.

**Comment by donsizemore** [comment]
> @donsizemore, Do you have a script for this issue?

I do. If you could e-mail don.sizemore@gmail.com, I'll reply with it privately? I'm too sheepish to post my code here.

Don

**Comment by pdurbin** [comment]
@Gerafp did you get the script from @donsizemore ? Are you all set?
