### ISSUE TITLE
Email notifications - review

### ISSUE THREAD

**Issue by esotiri** [IQSS/dataverse#875]
Email notifications has yet to be worked and I am opening this as a placeholder for different issues/discussions. 

For example at Dataverse Password Reset Requested #862 email response needs review.

**Comment by michbarsinai** [comment]
Password reset emails has to be configurable. Currently its hard-coded, including the from address.

**Comment by eaquigley** [comment]
Passing to @kcondon to close (if you would like to retest, not sure)

**Comment by kcondon** [comment]
@eaquigley Not sure what the solution would be if the user forgets both their username and email. Not sure what information we would use to validate them in this case, maybe some personal trivia question like some sites do? I'm not sure this is a major requirement for us at this point so I'm closing until we see more direct user need.
