### ISSUE TITLE
Dataset Archiving: BagIt bag-info.txt has some fields that are populated from bundle.properties, could be doc'd and maybe made a setting?

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#8760]
While testing a recent bag-it, dataset archiving change, noticed the bag-info.txt file had some filler, replacement text in it. In discussing with @qqmyers it was identified as an earlier attempt at populating the fields and that they could be populated in a more standardized and documented way:

cat bag-info.txt
Contact-Name: kc052622b, kc052622b
Contact-Email: [kc052622b@mailinator.com](mailto:kc052622b@mailinator.com)
Source-Organization: Dataverse Installation (<Site Url>)
Organization-Address: <Full address>
Organization-Email: <Email address>
External-Description: This is my description
Bagging-Date: 2022-05-26
External-Identifier: doi:10.70122/FK2/DJNPSO
Bag-Size: 109.77 KB
Payload-Oxum: 109765.3
Internal-Sender-Identifier: Dataverse Internal:kc052622b

from @qqmyers: 

they ~are filled in, with the values from https://github.com/IQSS/dataverse/blob/552dfc8c7af7a0b0e0c3948e6de1a8321af98c37/src/main/java/propertyFiles/Bundle.properties#L2269-L2271 

if you want an issue to move these things, or document that they exist (not sure if they are in the guides or not), feel free to add one and I'll take a look.
[Bundle.properties](https://github.com/IQSS/dataverse/blob/552dfc8c7af7a0b0e0c3948e6de1a8321af98c37/src/main/java/propertyFiles/Bundle.properties)
bagit.sourceOrganization=Dataverse Installation (<Site Url>)
bagit.sourceOrganizationAddress=<Full address>
bagit.sourceOrganizationEmail=<Email address>

**Comment by cmbz** [comment]
2023/09/25: Added to 6.1 milestone as per conversation during prioritization meeting.

**Comment by cmbz** [comment]
2023/10/23: Sized at: 3 during resizing meeting.
