### ISSUE TITLE
Jenkins jobs failing

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#8762]
This issue is just for tracking on our board.

Details are at https://github.com/GlobalDataverseCommunityConsortium/dataverse-ansible/issues/238

**Comment by pdurbin** [comment]
We seem to be good as of SELinux-related changes in https://github.com/GlobalDataverseCommunityConsortium/dataverse-ansible/commit/9c8e2a7

@donsizemore thanks for working on this!

I triggered a build on PR #8732 and all the tests seem to run correctly. The API tests took about 9 minutes: https://jenkins.dataverse.org/job/IQSS-Dataverse-Develop-PR/job/PR-8732/3/testReport/

I'm sending this to review. Thanks again, Don!

**Comment by scolapasta** [comment]
All set here; so closing.
