### ISSUE TITLE
Bug with a modified tsv ?

### ISSUE THREAD

**Issue by JulienBr57** [IQSS/dataverse#8764]
Hello,

I have a problem applying a custom citation.tsv (on a 5.10 test instance).
I modified the tsv to change a field ("kindOfData") to a controlled field with values and reloaded the solr schema with update-fields.sh"

It's OK with loading curl command but if I want to return to a simple text field, kindOfData remains in a controlled field while there are no more values indicated in the tsv.

Did I miss something ?

Thank you for you precious help !
Regards

Julien Brancher
Université de Lorraine
https://dorel.univ-lorraine.fr/

**Comment by JulienBr57** [comment]
Hi
After searching, I think the database was not completely updated with tsv commands because table "controlledvocabularyvalue"  I find old values of controlled field on the datasetfieldtype_id. 
It could have a problem of integrity constraints on foreign keys ?

Also, when I load the form page to edit the dataset metadata, the server.log gives me a warning by dataset types value :

- [2022-06-03T15:03:28.502+0200] [Payara 5.2021.5] [WARNING] [] [edu.harvard.iq.dataverse.ControlledVocabularyValue] [tid: _ThreadID=95 _ThreadName=http-thread-pool::jk-connector(5)] [timeMillis: 1654261408502] [levelValue: 900] [[
**Error findingcontrolledvocabulary.kindOfData.audiovisual in en : Can't find resource for bundle java.util.PropertyResourceBundle, key controlledvocabulary.kindOfData.**audiovisual**]]**

- [2022-06-03T15:03:28.502+0200] [Payara 5.2021.5] [WARNING] [] [edu.harvard.iq.dataverse.ControlledVocabularyValue] [tid: _ThreadID=95 _ThreadName=http-thread-pool::jk-connector(5)] [timeMillis: 1654261408502] [levelValue: 900] [[
  **Error findingcontrolledvocabulary.kindOfData.image in en : Can't find resource for bundle java.util.PropertyResourceBundle, key controlledvocabulary.kindOfData.image]]**

- [2022-06-03T15:03:28.505+0200] [Payara 5.2021.5] [WARNING] [] [edu.harvard.iq.dataverse.ControlledVocabularyValue] [tid: _ThreadID=95 _ThreadName=http-thread-pool::jk-connector(5)] [timeMillis: 1654261408505] [levelValue: 900] [[
  **Error findingcontrolledvocabulary.kindOfData.software in en : Can't find resource for bundle java.util.PropertyResourceBundle, key controlledvocabulary.kindOfData.software]]**

- [...]

Regards,
Julien

**Comment by pdurbin** [comment]
@JulienBr57 hi! Just checking it to see what you think about my last comment. Thanks.
