### ISSUE TITLE
Developer's Guide: Bumping version numbers

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#8795]
The steps for bumping version numbers have changed: 
-scripts/database/releases.txt is no longer updated, this has been true for a long time, since flyway was introduced.
-the example github commit showing changes contains the old way to update pom.xml, though the page has updated the pom file to be: modules/dataverse-parent/pom.xml -> <properties> -> <revision> and has a note: Note: the version has been moved to a property in parent module since this commit was created. Just not sure what that means, now that I'm one release away from that. Is there an action required or is it automatically populated?

Note: from last version bump, appears a new/different place to update pom.xml:
https://github.com/IQSS/dataverse/pull/8585/commits/3943aa034c3a8ebd8ef223700e521d11bc9bd46e

[modules/dataverse-parent/pom.xml](https://github.com/IQSS/dataverse/pull/8585/commits/3943aa034c3a8ebd8ef223700e521d11bc9bd46e#diff-13932ab2936dd2e5aa2e00edff959df8c4b1c04f30cdacd694f0b81cef68ec21)

 <properties>
        
        <revision>5.10.1</revision>

**Comment by mreekie** [comment]
Gustavo would like this done as it impact the 5.12 process.
Phil - there is already a pull request for this.

**Comment by pdurbin** [comment]
I addressed this as part of #8877, now merged.
