### ISSUE TITLE
Release Notes: v5.11 release notes should indicate Solr should reload the core after schema update.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#8817]
v5.11 release notes indicates the schema.xml needs updating due to an updated metadata block. It does not indicate the core needs to be reloaded per the guides: 
https://guides.dataverse.org/en/5.11/admin/metadatacustomization.html#updating-the-solr-schema
curl "http://localhost:8983/solr/admin/cores?action=RELOAD&core=collection1"

I've temporarily updated the live copy of release notes but opened this issue in case we have another process for maintaining the record on github.

**Comment by pdurbin** [comment]
Related:

- #7988

The failure scenario described there:

"The live notes are edited and the change is not propogated back to git. (This is less of a problem for end users and impossible for 4.15 and below where release notes aren't even in git.)"
