### ISSUE TITLE
CRITICAL: Pressing Enter in Group Members assignment windows deletes the whole group

### ISSUE THREAD

**Issue by philippconzett** [IQSS/dataverse#8820]
**What steps does it take to reproduce the issue?**
1. As an admin/curator in a TEST environment, click Edit > Groups > Create Group, and create a new user group for testing this issue.
2. Look up and add a user to the newly created test group, so that the user name displays in the Group Members field:

![image](https://user-images.githubusercontent.com/21955790/176399345-56afdcd3-8c1e-49bf-b2aa-99bea9bb1062.png)

3. With the cursor placed to the right to the added user name, press Enter.

* When does this issue occur?
See above.

* Which page(s) does it occurs on?
On the Group edit page, e.g.
https://demo.dataverse.org/manage-groups.xhtml?dataverseId=XX

* What happens?
The group is deleted, and the following confirmation message appears on screen:

![image](https://user-images.githubusercontent.com/21955790/176399659-767c5907-ef1f-4332-a9ed-9e36dbf3d59d.png)

* To whom does it occur (all users, curators, superusers)?
To everyone have the rights to add users to an existing user group.

* What did you expect to happen?
Not sure. I guess many curators would expect the added user to be saved, thus they want to use Enter as a shortcut for scrolling to the bottom of the page and click Save Changes.

**Which version of Dataverse are you using?**
The behavior was tested on version v.5.6 (test.dataverse.no) and version v.5.11 (demo.dataverse.org).

**Any related open or closed issues to this bug report?**
None to my knowledge.

**Screenshots:**
See above.

**Comment by sekmiller** [comment]
@philippconzett it seems to be browser-related. It works as expected in Safari - ENTER adds the group/user. In Chrome I see the "Success- Group has been deleted" - at least when I add a user on Group Create. Will try on Group Edit next.

**Comment by sekmiller** [comment]
In Chrome the delete also happens on update group - add users.

**Comment by philippconzett** [comment]
Thanks, @sekmiller. I just tested this on Microsoft Edge also: On update group, the whole group is deleted when pressing Enter.

**Comment by philippconzett** [comment]
The same behavior also in Firefox.

**Comment by poikilotherm** [comment]
Is there a particular reason why there is no `p:defaultCommand` in our forms to make pressing enter key bound to an explicit behaviour (button)?

https://www.primefaces.org/showcase/ui/misc/defaultcommand/multiple.xhtml

HTML 5 specs says the default button is the one contained first in the tree. https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#implicit-submission The "delete" button is in a "higher" level of the DOM tree than our "submit" buttons. This might be a problem.

We could at least make the `onclick` modal also appear when pressing enter, so there is at least a dialogue that prevents the deletion.

**Comment by sekmiller** [comment]
When I was working on this last week I tried only having the confirm delete popup render after the delete button was pressed. That fixed the "delete group on enter" problem, but the delete popup would appear and then disappear when the delete button was pressed. I will try to narrow the render around the "confirm delete" button instead of the popup itself.
