### ISSUE TITLE
Footer showing: "v. 5.11 build 1009-21ac7e1" instead of "v5.11"

### ISSUE THREAD

**Issue by DieuwertjeBloemen** [IQSS/dataverse#8829]
**What steps does it take to reproduce the issue?**
Install 5.11 and scroll to the footer.

* When does this issue occur?
Always

* Which page(s) does it occurs on?
All pages (the footer)

* What happens?
The Dataverse footer logo, which is normally accompagnied by just the version, also has build information next to it.

So it used to say:
_Powered by The Dataverse Project logov. 5.10.1_

But now it says:
_Powered by The Dataverse Project logov. 5.11 build 1009-21ac7e1_

* To whom does it occur (all users, curators, superusers)?
All users.

* What did you expect to happen?
For it to say _Powered by The Dataverse Project logov. 5.11

**Which version of Dataverse are you using?**

5.11

**Any related open or closed issues to this bug report?**
/
Also pointed out in the Google community: https://groups.google.com/g/dataverse-community/c/vR15qIXPYdY

**Screenshots:**
![image](https://user-images.githubusercontent.com/92870663/177127446-abf5dc6c-c00f-4b15-b784-3a45a048eb0b.png)

**Comment by poikilotherm** [comment]
Copying my answer from the Google Group here:

> Looks like this one slipped through when the final WAR was build. On the system the WAR was built before upload, the BuildNumber.properties file was present and packaged, which is not intentional.
> 
> See also the dev guide: https://guides.dataverse.org/en/latest/developers/tips.html#automation-of-custom-build-number-on-webpage

@pdurbin @landreev @kcondon can we rebuild and replace the WAR & `dvinstall.zip` on the release page?

**Comment by kcondon** [comment]
For the record, v5.10.1 also has build info and am told this behavior is not new when using ansible to build, which I have always been doing. I've also seen a production version of v5.3 also showing the build number. This seems to be request for change or perhaps just noticing it was there.

**Comment by pdurbin** [comment]
I'm documenting where the build string comes from in this PR:

- #9024

@DieuwertjeBloemen et al. please let me know if it makes sense. Thanks!

**Comment by pdurbin** [comment]
@DieuwertjeBloemen Dataverse 5.12 will mostly likely look like this (unless we make a few final commits):

<img width="429" alt="Screen Shot 2022-10-05 at 9 08 45 AM" src="https://user-images.githubusercontent.com/21006/194068134-642c5bd9-ec27-4899-9a20-dd14748ec771.png">

From /api/info/version -

```
{
  "status": "OK",
  "data": {
    "version": "5.12",
    "build": "1119-71341c0"
  }
}
```
