### ISSUE TITLE
Problem with license selection and Terms of Access/'Enable access request' button

### ISSUE THREAD

**Issue by DieuwertjeBloemen** [IQSS/dataverse#8832]
**What steps does it take to reproduce the issue?**
In 5.11, create a new dataset with metadata and files. Once created, go to the Terms tab and click 'Edit Terms Requirements' to select a different license. Pick a different license, and try to save. It doesn't give an error, it just doesn't save the changes or leave the 'Edit Terms Requirements' page.

* When does this issue occur?
When you try to save your changed license choice.

* Which page(s) does it occurs on?
On all the newly created datasets.

* What happens?
It doesn't allow us to change the license because neither the 'Enable access request' button is ticked nor are there any 'Terms of Access for Restricted Files', even though there are no restricted files in the dataset and the option to select or fill them in is greyed out.
I can get it to work by first restricting a file and tick the 'Enable access request' button there, then unrestrict said file. If I then go to Terms and edit them to select a different license, it does work because the 'Enable access request' button (though again greyed out) is now ticked.
I don't get this issue in the demo.dataverse.org environment. There it already has the 'Enable access request' button ticked by default, even though it's greyed out. So, I'm wondering if it's a setting that we don't know about.

* To whom does it occur (all users, curators, superusers)?
All users.

* What did you expect to happen?
That I could change the license selection and save it. Or that the 'Enable access request' button is always ticked for newly created datasets and the licenses even when there are no files restricted.

**Which version of Dataverse are you using?**
5.11

**Any related open or closed issues to this bug report?**
no

**Screenshots:**
![image](https://user-images.githubusercontent.com/92870663/177567694-ab8929c0-ec82-4b8a-8b65-164e22f64cb6.png)

As you can see, the error is given because neither the 'Enable access request' button is selected nor Terms of Access are supplied. But I also can't select either of them, because they're greyed out due to a lack of restricted files in this dataset.

**Comment by sekmiller** [comment]
@DieuwertjeBloemen, thanks for this. It's definitely something that needs to be fixed. I think it's due to using a Dataset Template where Request Access is not checked. An easier workaround, for the time being would be to make sure that all of your dataset templates have "Request Access" checked.

**Comment by DieuwertjeBloemen** [comment]
Thanks for pointing out the Dataset Template point, I completely forgot we had a default template chosen that indeed had the old setting of neither the 'Enable access request' button ticked nor Terms of Access filled in. Once I changed the template and removed it as a default, the problem is solved for now for newly created datasets.
But it remains a problem for existing datasets that at some point had neither the 'Enable access request' button ticked nor Terms of Access filled in and have no restricted files and may want to change something in the Terms tab. There the issue persists.
In our case, we can work around it via the helpdesk by temporarily restricting a file, changing one of the settings and unrestricting. But I think we can only do that because we don't have loads of datasets yet. So, something to look out for for the other installations when they implement 5.11, and definitely something to fix for the next release, I hope.

**Comment by shlake** [comment]
I have the same problem, but not on creating new datasets (now at version 5.11), but see this error on previously created datasets (before 5.10).

I do not have any templates.
