### ISSUE TITLE
Handle server: Investigate and correct intermittent failure to start service using init.d script.

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#884]
---

Author Name: **Kevin Condon** (@kcondon)
Original Redmine Issue: 1371, https://redmine.hmdc.harvard.edu/issues/1371
Original Date: 2011-10-26

---

Most recently tested on dvn-1, the init.d handlenet script intermittently fails to start the handle service due to a password failure. 

Leonid theorized it may not always be triggering at the same time to possibly has extra line feeds or tabs when it fails.

**Comment by eaquigley** [comment]
@kcondon and @landreev can you comment on if this is relevant to 4.0? thanks!

**Comment by kcondon** [comment]
@eaquigley @landreev  This is from when we hosted the service here. Problem has not show itself since that we're aware of.  OK to close,

**Comment by eaquigley** [comment]
Closing based on @kcondon comment above that says it is okay to close.
