### ISSUE TITLE
Truncated view of checksums missing in v 5.11

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#8841]
(as noticed by @adam3smith) : 
v5.11 on demo.dataverse.org: 
![image](https://user-images.githubusercontent.com/6731983/178836881-b62cd146-1220-4971-b885-ec9173e097da.png)

v5.10.1 @dataverse.harvard.edu: 
![image](https://user-images.githubusercontent.com/6731983/178837003-d0c50193-c363-435f-86a8-768f47ec478d.png)

FWIW: I've tracked the removal to [the change to not call bind_bsui_components in many places and use o:onloadScript](https://github.com/IQSS/dataverse/commit/bd7634f2a6af679a52d80cf18768f1c2e519e828). The checksumTruncate() method that would have been called from there has https://github.com/IQSS/dataverse/blob/40c6f304de4bbc162dec865b3c7ca5cfb2fe22cd/src/main/webapp/resources/js/dv_rebind_bootstrap_ui.js#L216 - which removes the sr-only class and adds the visisble (sp - which made it easy to find!) class **-if called once**. It looks like it is now running twice and hence resetting the original classes.

I don't think visisble actually exists in any css file so the old function was essentially removing the sr-only class. Thus a simple fix would just be to remove that class in the xhtml file.  Alternately, the checksumTruncate() method could just removeClass("sr-only") instead of toggling it. (Same for "visisble" but again I don't see that used anywhere).

I can do either of those (already tested at QDR) if someone has a preference or something else if anyone can think of a reason to make a different fix. (I'm not sure why bind_bsui was moved or why the checksum truncate toggled these classes...)

**Comment by qqmyers** [comment]
sr-only seems like it aims to only show the text to a screen reader, so removing that should still keep it accessible for screen readers, it just becomes visible in the normal browser as well. So I don't think this change should cause accessibility issues (and Deque Axe doesn't complain about it)

As for visisble - there isn't any visible class either. The closest I see is a visibility:visible css property. In any case, with sr-only removed, I don't see why you'd also need to set it visible.

**Comment by scolapasta** [comment]
OK that makes sense. Weird about the visisble / visible class.
