### ISSUE TITLE
Version table always shows DRAFT?

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#8845]
**What steps does it take to reproduce the issue?** I'm not sure if it's new, but if I look at a dataset's version table, I see a DRAFT row even when there is no draft. Clicking the link brings me to the last version with a warning that draft doesn't exist, this is version x.y

**What did you expect to happen?**

DRAFT only appears if there is one.

**Which version of Dataverse are you using?**
5.11 / demo.dataverse.org

**Any related open or closed issues to this bug report?**
?

**Screenshots:**
DRAFT in the table - warning that draft doesn't exist at the top...

![image](https://user-images.githubusercontent.com/6731983/179318869-a93d0436-f94b-4185-98bf-16c1db57549f.png)

**Comment by pdurbin** [comment]
@qqmyers can you please try something for me? When you have a dataset in this state, that is:

- the only version is published
- the Versions tab shows a draft that isn't really there (not in the database)

What if click "Edit Dataset" and try to delete the dataset? I just tried this as of 75d2900f28 on develop and THE PUBLISHED DATASET WAS DELETED! That is, I didn't do a "destroy" from the API. I was able delete a published dataset from the GUI (when the dataset is in this weird state).

More specifically, my dataset was in the "non-complaint" state described in https://github.com/IQSS/dataverse/issues/8742#issuecomment-1196801993 (no terms, no request access).
