### ISSUE TITLE
HTML tags popup is blank, doesn't show allowed tags

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#8846]
**What steps does it take to reproduce the issue?**

- Edit a dataverse collection or a dataset (screenshots are for the former)
- Click on "HTML tags" to see the "Allowed HTML Tags" popup
- Observe that is is empty (screenshot below)

![Screen Shot 2022-07-18 at 4 32 38 PM](https://user-images.githubusercontent.com/21006/179614482-87dd384a-bd24-4eb9-ac17-2cc997337dc0.png)

* To whom does it occur (all users, curators, superusers)?

All users.

* What did you expect to happen?

I expect to see a list of allowed HTML tags (screenshot below):

![Screen Shot 2022-07-18 at 4 34 14 PM](https://user-images.githubusercontent.com/21006/179614581-8bc7a06a-57ef-49c7-9ad8-f10b3ff17714.png)

**Which version of Dataverse are you using?**

5.11.

The bug does not seem to be present in 5.10.1.

We also see the bug in the develop branch (567e506 as of this writing).

**Any related open or closed issues to this bug report?**

Possibly the bsui changes here:

- #8586

**Comment by mreekie** [comment]
() clearly broken
() Going in as a small based on initial investigation. Possibly could surprise us.
