### ISSUE TITLE
DVUploader URL is Wrong in Guides

### ISSUE THREAD

**Issue by shlake** [IQSS/dataverse#8851]
Looks like the DVUploader repo was moved to GDCC repo, but the guides did not update the link. And now the "new" "dataverse-uploader" repository on IQSS is the github uploader, not the command line.

**What steps does it take to reproduce the issue?**
The URL for Command-line DVUploader is wrong in the User Guide and the API Guide. The link goes to the dataverse-uploader, which is the uploader for files in a git repository.

For example on the User Guide, this section: 
https://guides.dataverse.org/en/5.11/user/dataset-management.html#command-line-dvuploader
The link displayed is: https://github.com/IQSS/dataverse-uploader

which is not the correct link. This is the correct link:
https://github.com/GlobalDataverseCommunityConsortium/dataverse-uploader/wiki/DVUploader,-a-Command-line-Bulk-Uploader-for-Dataverse

Or this one which goes to the github repo "home" page"
https://github.com/GlobalDataverseCommunityConsortium/dataverse-uploader

**Which page(s) does it occurs on?**
User Guide -> Dataset + File Management
https://guides.dataverse.org/en/5.11/user/dataset-management.html#command-line-dvuploader

Wrong link Occurs in two paragraphs - in the User Guide.

API Guide -> Apps
https://guides.dataverse.org/en/5.11/api/apps.html#dvuploader

**Comment by pdurbin** [comment]
@shlake oh dear. Would you like to make a pull request? Thanks for finding this!

**Comment by shlake** [comment]
I think I can do that. I'll try.
