### ISSUE TITLE
Fields in metadata block TSV files have allowControlledVocabulary property set to true, but no CV terms

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#8857]
Fields in a few of metadata block TSV files that ship with the Dataverse software have their allowControlledVocabulary property set to TRUE. For example in the Citation metadata block, the software name field has allowControlledVocabulary as TRUE:

<img width="1142" alt="Screen Shot 2022-07-25 at 10 52 04 AM" src="https://user-images.githubusercontent.com/18374574/180807336-c23f4621-89e5-4c5c-a83f-cf0cb4aaa080.png">

But the TSV file's #controlledVocabulary section has no terms listed for those fields. These fields weren't meant to have controlled vocabularies. Maybe at one point it was being considered, so the allowControlledVocabulary properties were set to TRUE and never set back to FALSE?

In the UI, those fields are free text fields:

<kbd><img width="962" alt="Screen Shot 2022-07-25 at 10 55 37 AM" src="https://user-images.githubusercontent.com/18374574/180807923-7102209e-e675-4fa7-ab0f-5f7979bcfefd.png"></kbd>

So it looks like the Dataverse software creates single-line text boxes for these fields since they don't have terms in the TSVs' controlled vocabulary sections. Or maybe the Dataverse software is looking at the metadata block's properties files, which also list controlled vocabulary terms but would does not list terms for these fields.

In the example used here, the Citation metadata block's software name field has had allowControlledVocabulary set to TRUE for as far back in the TSV file's history as I can tell.

There are one or more fields like this in other metadata blocks that ship with the Dataverse software.

I think at least to avoid confusion, the allowControlledVocabulary property of these fields should be changed to FALSE. And maybe that could be the "definition of done" for this GitHub issue.

Also maybe the Dataverse software can return some error when it tries to load a TSV file that has any fields where allowControlledVocabulary is TRUE but no terms are listed for that field in the TSV file's #controlledVocabulary section.

**Comment by scolapasta** [comment]
I think that was done in (except for the error of loading): https://github.com/IQSS/dataverse/pull/9984

**Comment by jggautier** [comment]
Awesome. Closing this issue.

https://github.com/IQSS/dataverse/issues/10461 is related
