### ISSUE TITLE
Handle Registration: Identify and correct *all* unregistered handles in IQSS dvn production.

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#887]
---

Author Name: **Kevin Condon** (@kcondon)
Original Redmine Issue: 2214, https://redmine.hmdc.harvard.edu/issues/2214
Original Date: 2012-05-09

---

This ticket is a follow up from the RT #132008 where several handles belonging to a customer failed to resolve.

At that time, the handles mentioned and many more that were identified in a range were corrected. However, some were not and it was discovered the pattern was intermittent and not associated with just the handle server being down. This implied there may be more handles that are unregistered but undetected in our service. We do not currently have a systematic way of reviewing and verifying correct handle registration and failures occur silently.

This ticket is about correcting the immediate problem in production of determining which handles have failed and correcting them. A global reregister will not work because in testing we found such a batch job appears to overwhelm the remote handle system and that results in failures.

There are two other tickets related to this one: 1. indicates the general reliability and supportability issues surrounding the handle system and 2. proposes a system similar to the index error detect and correction mechanism but for handles (and also to send failure notifications at study create/ handle register time when handle is not registered).

**Comment by scolapasta** [comment]
Passing to QA, as @landreev had commented in a separate ticket that we have previously verified all existing handles (and no handles have been created since then)

**Comment by kcondon** [comment]
Closing based on Gustavo's testimony of Leonid's confirmation.
