### ISSUE TITLE
Additional documentation fixes

### ISSUE THREAD

**Issue by kuhlaid** [IQSS/dataverse#8873]
Sphinx documentation fixes (in progress - PR to follow):

1. Changing openprovenance.org to use the https (because the site seems to only be using HTTPS and the HTTP URL is not redirecting to the HTTPS URL and is breaking page) [https://github.com/kuhlaid/dataverse/commit/0893d172f72e87803da00b183f4ad1d6da67b280](https://github.com/kuhlaid/dataverse/commit/0893d172f72e87803da00b183f4ad1d6da67b280)

2. Removing index links because they no longer link to anything [https://github.com/kuhlaid/dataverse/commit/1d5ec876de31a7bcb06b7a8bf78895a00e469852](https://github.com/kuhlaid/dataverse/commit/1d5ec876de31a7bcb06b7a8bf78895a00e469852)

3. Fixing link to https://orcid.org [https://github.com/kuhlaid/dataverse/commit/6b9d175cd46be347c157f249e01b243f96d9824c](https://github.com/kuhlaid/dataverse/commit/6b9d175cd46be347c157f249e01b243f96d9824c)

4. Fixing URL to the R Project [https://github.com/kuhlaid/dataverse/commit/01e1d5291b01de7bb79b329ce3ba2b9a3049ce59](https://github.com/kuhlaid/dataverse/commit/01e1d5291b01de7bb79b329ce3ba2b9a3049ce59)

5. Fixing link to PIP [https://github.com/kuhlaid/dataverse/commit/1968c752e1c554060e99b19274a4aff8fc0982a3](https://github.com/kuhlaid/dataverse/commit/1968c752e1c554060e99b19274a4aff8fc0982a3)

6. Fixing Renku documentation link [https://github.com/kuhlaid/dataverse/commit/ab8d609efec85aef5ef0751441a8462db5706926](https://github.com/kuhlaid/dataverse/commit/ab8d609efec85aef5ef0751441a8462db5706926)

**Comment by pdurbin** [comment]
@kuhlaid your PR #8885 closes #8869 but none of the above... is that right? So more PRs are coming? Is that right? Thanks!

**Comment by kuhlaid** [comment]
Yes, thank you for that reminder. PR has been sent.
