### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by kuhlaid** [IQSS/dataverse#8874]
Below are a list of URLs that need to be removed or updated in the documents as they no longer point to useful resources (I can clean these out but wasn't sure if there were alternate resources to replace them):

1. Under [https://guides.dataverse.org/en/latest/admin/metadatacustomization.html#metadatablock-properties](https://guides.dataverse.org/en/latest/admin/metadatacustomization.html#metadatablock-properties) it references the dead URL ``https://dataverse.org/schema/citation/ `` which no longer points to anything.

2. Under [https://guides.dataverse.org/en/latest/installation/config.html#persistent-identifiers-and-publishing-datasets](https://guides.dataverse.org/en/latest/installation/config.html#persistent-identifiers-and-publishing-datasets) it references the dead URL ``https://dataverse.org/global-dataverse-community-consortium`` which no longer points to anything.

3. Under [https://guides.dataverse.org/en/latest/api/external-tools.html](https://guides.dataverse.org/en/latest/api/external-tools.html) there are multiple references to ``fabulousfiletool.com`` which not longer seems to be a functioning site and a search did not turn up alternatives.

4. Under [https://guides.dataverse.org/en/latest/installation/config.html](https://guides.dataverse.org/en/latest/installation/config.html) there is broken link to ``https://documentation.ands.org.au/display/DOC/ANDS+DataCite+Client+API``.

**Comment by qqmyers** [comment]
Thanks for the heads up on these. As always you're welcome to submit a pull request with these changes as well.

One thing I'll note - the first one is not an error per se. If you look in the OAI_ORE file and use the json-ld semantic API, you will indeed see/use https://dataverse.org/schema/citation/. It is however, just a global semantic identifier (a namespace/root for many identifiers) rather than a live URL currently. So it might be helpful in the short term to avoid showing it as a live link. (In the longer term, it would make sense to provide a list of identifiers/definitions online at those URLs.)

**Comment by AkiraY1** [comment]
Hey! This is the first time I'm contributing to this project. Let me know if there's anything I need to change or any guidelines/rules I didn't follow properly.

**Comment by pdurbin** [comment]
@AkiraY1 hi! I left some comments on your pull requests. Thanks for making each change separate!

**Comment by AkiraY1** [comment]
Thanks for the quick response! I responded to all the changes under each PR

**Comment by AkiraY1** [comment]
I created individual issues and marked each PR with "closes #XXXX". All three PRs have been closed or merged. Two of the PRs (#8886 and #8888) were merged _before_ I created the new issues. Will the new issues still close automatically when this parent issue is closed?

Thank you for all the help btw, I really appreciate it :)

**Comment by pdurbin** [comment]
For the open issues you can just type "closed by #XXXX" (using the PR number) and close them. Thanks.

**Comment by pdurbin** [comment]
@AkiraY1 thanks for the pull requests! Anything left to do? If not, please go ahead and close this issue. You're very welcome to create new issues and pull requests! Thanks again! 🎉

**Comment by AkiraY1** [comment]
Hi @pdurbin, how do I close this issue since I didn't open it?

**Comment by pdurbin** [comment]
@AkiraY1 d'oh! Sorry! You're right, @kuhlaid opened it. I think we're finished so I'm going to close it. If either you notice anything else, please open a fresh issue! Thanks!
