### ISSUE TITLE
Handle System: There are several reliability and supportability issues with current system that need to be investigated and guarded against.

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#888]
---

Author Name: **Kevin Condon** (@kcondon)
Original Redmine Issue: 2215, https://redmine.hmdc.harvard.edu/issues/2215
Original Date: 2012-05-09

---

Tested with v3.0.232, also see customer issue RT #132008.

The handle system has several issues that make it less reliable and also pose supportability problems. Since this is a complex issue, I wanted to first describe the problems generally, then reference other tickets that 1. describes current support issues in production, and 2. proposes and requests a feature that should address most of the issues. Since this is considered a fundamental, critical part of the DVN data citation concept and because we are gaining more and more partners who would assume this is reliable, I will mark this as a high priority.

Reliability issues:
1. When handle server is not running or not responding, either due to not being restarted when machine is started or other reasons, DVN will continue to create studies with handles that are not registered and there is no indication that handles are not being registered.
1. Based on evidence from a recent support ticket, RT #132008, it also seemed that handle registration in our production cluster intermittently did not register studies though the handle server continued to run and successfully register handles. Again, there was no indication handles were not being registered.

Supportability issues:
3. When it has been discovered that some handles have not been registered, there is no systematic way to determine the extent of the problem, other than manually checking ranges of handles. This effective when the cause was due to the handle server being down since the failures are contiguous and the range can be determined. This is not effective when this issue is caused by intermittent failure to register since some handles in a range resolve and some do not.
4. Due to the intermittent nature of some of the failures, the handle fix utility needs to be able to accept an arbitrary list of handles needing registration or reregistration. Recently ranges were added to this feature which was a great addition since it provided a lot of flexibility when dealing with multiple failures in contiguous ranges.

This ticket also references 2 other tickets: 
1. Related to the current issue in IQSS production where it is unclear how many handles are not registered and need to be corrected (Support #887
Handle Registration: Identify and correct _all_ unregistered handles in IQSS dvn production.)
2. Proposed feature/ solution to above reliability and supportability issues which is similar to the index mechanism to identify, inform, and correct handle registration issues automatically (Feature #886
Handle Registration: Provide proactive way to identify and correct handles that fail to register.)

**Comment by kcondon** [comment]
@pdurbin I see you are closing some issues as completed. Are they in fact or are these being administratively closed and under what mandate?

**Comment by pdurbin** [comment]
This one I wasn't sure about. It just seemed so old. 9 years. I'll re-open it.

I've closed a lot of issues that are just noise. No one else seems interested in closing issues so I'm doing it. You're welcome! 😄
