### ISSUE TITLE
shib-affiliation

### ISSUE THREAD

**Issue by Louis-wr** [IQSS/dataverse#8882]
**Overview of the Feature Request**
Feide authentication service returns an array of values for affiliation. The affiliation in English is expected to be the last element in the array. This modification adds an option to only return the last element of said array.

**What kind of user is the feature intended for?**
(Example users roles: API User, Curator, Depositor, Guest, Superuser, Sysadmin)
Sysadmin

**What inspired the request?**
Feide authentication service returns an array of values for affiliations.

**What existing behavior do you want changed?** 
Affiliation being an array to a single affiliation value.

**Any brand new behavior do you want to add to Dataverse?** 
Ability to split an array of affiliations. 

**Any related open or closed issues to this feature request?**
No

note : see https://github.com/IQSS/dataverse/pull/8880

**Comment by donsizemore** [comment]
I'm getting `Couldn't find an affiliation from <IDP>` on 5.12.1, and in debugging, my University is returning FOUR semi-colon-delimited affiliation attributes (staff, alum, member, employee). Dataverse only seems to treat the missing affiliation as a warning rather than fatal...?

**Comment by pdurbin** [comment]
@donsizemore and I are talking about this in chat. From a quick look I think this is pretty old behavior. It's been logger.info for a long time. It should probably be reduced to logger.fine. I don't think it's related to this issue or PR but I could be wrong.
