### ISSUE TITLE
Handle/DOI Registration: Investigate, correct, and improve handle/DOI registration process

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#889]
---

Author Name: **Kevin Condon** (@kcondon)
Original Redmine Issue: 2216, https://redmine.hmdc.harvard.edu/issues/2216
Original Date: 2011-10-26

---

This is a parent ticket for the various handle/doi and handle/doi registration tickets.

**Comment by pdurbin** [comment]
> This is a parent ticket for the various handle/doi and handle/doi registration tickets.

This issue is apparently being billed as the parent issue for Handle support but so is #2437 judging from its title. We probably only need one parent issue.

**Comment by kcondon** [comment]
This is a duplicate and doi has been addressed. #886 is targeted at handles. Closing.
