### ISSUE TITLE
Broken link and description of DataCite Proxy no longer used by ADA

### ISSUE THREAD

**Issue by AkiraY1** [IQSS/dataverse#8899]
There is a broken link (https://documentation.ands.org.au/display/DOC/ANDS+DataCite+Client+API) on page https://guides.dataverse.org/en/latest/installation/config.html of the documentation. That section of the config page of the documentation explains the DataCite Client API, which has been decomissioned.

**Comment by poikilotherm** [comment]
Please note I already have a refactoring of this entire section within the MPCONFIG PR for PIDs

**Comment by AkiraY1** [comment]
Closed by #8888
