### ISSUE TITLE
Feature Request/Idea: create a base container image providing a Dataverse-tuned Payara application server

### ISSUE THREAD

**Issue by poikilotherm** [IQSS/dataverse#8932]
**Overview of the Feature Request**

To allow building a Dataverse container, it needs a carefully tuned Payara application server image first.

While technically one might use https://hub.docker.com/r/payara/server-full, this image lacks a few things:

- Based on Azul JDK, not Temurin/Adoptium
- Missing CLI tools necessary for Dataverse operation
- Non-optimized for production scenarios (at least not with the shipped community edition defaults)
- Do not provide multi-arch images (AMD64 + ARM64 for Apple M1/2)
- Some other small issues

With this issue I request we create a sustainable base image for future addition of a Dataverse container image.
It should be maintained in a separated Maven module and use dmp.fabric8.io to integrate it into Maven workflows.

**What kind of user is the feature intended for?**
Sysadmin, Developers

**What inspired the request?**
Provide community-backed container usage out of the box.

**What existing behavior do you want changed?**
Add a base image to build a Dataverse container image upon.

**Any brand new behavior do you want to add to Dataverse?**
Starting a "Container Guide" to describe and document the images, build processes etc.

**Any related open or closed issues to this feature request?**
#5292 #4665 #8709

**Related folks to ping**
@carlsonp @4tikhonov @pameyer @pdurbin @beepsoft @Kris-LIBIS

**Comment by poikilotherm** [comment]
Woah! Thx for merging! This is great @kcondon 🥳

**Comment by mreekie** [comment]
@pdurbin @poikilotherm 
In this last sprint, we explicitly allowed out of order items to get in so this is fine

Just to be a pain in the butt and remind you  -- Please don't don't slip things in as a general practice.
