### ISSUE TITLE
Handle more than 50,000 entries in the sitemap

### ISSUE THREAD

**Issue by PaulBoon** [IQSS/dataverse#8936]
**What steps does it take to reproduce the issue?**
Generate a sitemap for an archive that has more than 50k datasets

* What happens?
A single sitemap.xml file is generated, but Google only wants sitemap files with 50k or less URL's in it, so it won't be used for indexing. 

* What did you expect to happen?
Dataverse should split up the sitemap entries over several files and reference them in a sitemap index file. See: https://developers.google.com/search/docs/advanced/sitemaps/large-sitemaps

**Any related open or closed issues to this bug report?**

- https://github.com/IQSS/dataverse/issues/4261

**Comment by landreev** [comment]
@PaulBoon Do you happen to know for the fact if this is still a problem? I.e., if Google is still enforcing this limit? 
I was under the impression/assumption that they were no longer applying it, but I'm seeing some evidence to the contrary now, and they appear to still mention it in their documentation. 
It really looks like we need to address this in the code to be safe.

**Comment by PaulBoon** [comment]
@landreev This is a while back, but I do remember that the Google Search Console was driving me mad. 
It might be that Google is not very strict on the limit, but if you have 100k+ it was complaining the last time I looked. 
We now have a Python script in place that splits up the sitemap every night via cron. However we do have problems with Google, not being clear what and when and how it is doing things, their indexing is intentionally really a black box. 
We do have problems getting all the published datasets properly indexed by Google, as others from the Dataverse community also have. It might be good if we shared our combined knowledge somehow.

**Comment by landreev** [comment]
@PaulBoon thank you. I've been looking into all of this, and yes, it will be a good idea to combine and document all the solutions/tips we may find. 
BTW, did it actually work in your case, supplying the sitemap index to the bot by simply adding it to your robots.txt? - I did try that, via this line: 
```
sitemap: https://dataverse.harvard.edu/sitemap_index.xml
```
but the bot just kept stubbornly using the combined sitemap we had there previously. I had to go into the search console and force-submit the index there. (although there's a chance I simply didn't wait long enough and it would have switched to it eventually - ?)

There appears to be lots of small idiosyncratic things like this when trying to appease the bot.

**Comment by PaulBoon** [comment]
@pdurbin The script we use to split, scraped it from the internet sometime ago. 

```
#!/usr/bin/env python3

import os
import sys
from xml.sax import parse
from xml.sax.saxutils import XMLGenerator
import datetime

# based on code from https://github.com/realitix/sitemap_splitter
# needs to be run from same directory as the sitemap.xml file

BASE_URL = "{{ dataverse.payara.siteurl }}/sitemap/"
BREAK_AFTER= 2500 

class CycleFile():
    def __init__(self, filename):
        self.basename, self.ext = os.path.splitext(filename)
        self.index = 0
        self.filenames = []
        self.open_next_file()

    def open_next_file(self):
        self.index += 1
        filename = self.name()
        self.file = open(filename, 'w')
        self.filenames.append(filename)

    def name(self):
        return'%s%s%s' % (self.basename, self.index, self.ext)

    def cycle(self):
        self.file.close()
        self.open_next_file()

    def write(self, str):
        self.file.write(str.decode('utf-8'))

    def close(self):
        self.file.close()


class XMLBreaker(XMLGenerator):
    def __init__(self, break_into=None, break_after=1000, out=None, *args, **kwargs):
        XMLGenerator.__init__(self, out, encoding='utf-8', *args, **kwargs)
        self.out_file = out
        self.break_into = break_into
        self.break_after = break_after
        self.context = []
        self.count = 0

    def startElement(self, name, attrs):
        XMLGenerator.startElement(self, name, attrs)
        self.context.append((name, attrs))

    def endElement(self, name):
        XMLGenerator.endElement(self, name)
        self.context.pop()

        if name == self.break_into:
            self.count += 1
            if self.count == self.break_after:
                self.count = 0
                for element in reversed(self.context):
                    self.out_file.write(b"\n")
                    XMLGenerator.endElement(self, element[0])
                self.out_file.cycle()

                XMLGenerator.startDocument(self)
                for element in self.context:
                    XMLGenerator.startElement(self, *element)


def generate_index(base_url, filenames):
    now = datetime.datetime.now()
    dt = now.strftime("%Y-%m-%d")
    index_content = """<?xml version="1.0" encoding="UTF-8"?>
    <sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    """

    for filename in filenames:
        index_content += """
            <sitemap>
                <loc>{}</loc>
                <lastmod>{}</lastmod>
            </sitemap>
        """.format(base_url+filename, dt)

    index_content += """
    </sitemapindex>
    """

    # Move current sitemap to backup and write the other one
    os.rename('sitemap.xml', 'backup_sitemap.xml')
    with open('sitemap.xml', 'w') as f:
        f.write(index_content)


def run():
    filename = "sitemap.xml"
    break_into = "url"
    break_after = BREAK_AFTER
    cycle = CycleFile(filename)
    parse(filename, XMLBreaker(break_into, int(break_after), out=cycle))
    generate_index(BASE_URL, cycle.filenames)


if __name__ == '__main__':
    run()
```

**Comment by PaulBoon** [comment]
Sorry, I accidentally closed the issue

**Comment by pdurbin** [comment]
Awesome, thanks @PaulBoon

**Comment by cmbz** [comment]
2024/01/29
- Prioritized following Slack conversation with @scolapasta
