### ISSUE TITLE
Extend 'metadatablocks' endpoint to include the 'multiple' field

### ISSUE THREAD

**Issue by JR-1991** [IQSS/dataverse#8944]
**Overview of the Feature Request**

Extend the ```/metadatablocks/{identifier}``` endpoint to include the ```multiple``` field such that the schema can be used to programmatically upload data.

**What kind of user is the feature intended for?**

API Users

**What inspired the request?**

While presenting the [EasyDataverse](https://github.com/gdcc/easyDataverse) library at the Dataverse Community Meeting 2022 it was brought up in the discussion that the missing field could allow more users to upload datasets programmatically.

**What existing behavior do you want changed?**

The current REST-API implementation offers the possibility to fetch all metadatablock configurations by using the ```/metadatablocks/{identifier}``` endpoint. It provides relevant information of a metadatablock but lacks the ```multiple``` statement in a field, which on the flip is necessary to upload data via [PyDataverse](https://github.com/gdcc/pyDataverse)/HTTP. At the moment, the TSV file has to be inspected to find the corresponding values, but since metadatablock TSVs usually aren't hosted publicly this is only possible for those with access (except for the default TSVs)

An extension of the endpoint would allow users to infer the correct schema to upload datasets programmatically. Furthermore, this would allow [EasyDataverse](https://github.com/gdcc/easyDataverse) to generate Python interfaces at runtime without the need of hosting a generated API such as the one [we are hosting](https://github.com/JR-1991/pyDaRUS) at our university. This would allow the following functionality as an example:

```python
from easyDataverse import Dataset

# Adds metadata configs as objects to which data can be added
dataset = Dataset.from_installation("https://www.mydataverse.com")
dataset.citation.add_author(...)
```

**Comment by pdurbin** [comment]
Yes, sure. Good idea @JR-1991. I assume you only want to add to the JSON output, not change anything. Are you thinking about making a pull request?

We've been talking a lot internally about APIs and what the community needs. This is an API I sort of forgot even existed. 😄 

Here's a handy link to the docs: https://guides.dataverse.org/en/5.11.1/api/native-api.html#show-info-about-all-metadata-blocks

The API seems extremely useful. Here is some example output:

```
$ curl -s https://demo.dataverse.org/api/metadatablocks | jq '.data[0]'
{
  "id": 2,
  "displayName": "Geospatial Metadata",
  "name": "geospatial"
}
$ curl -s https://demo.dataverse.org/api/metadatablocks/geospatial | jq | head -20
{
  "status": "OK",
  "data": {
    "id": 2,
    "name": "geospatial",
    "displayName": "Geospatial Metadata",
    "fields": {
      "geographicCoverage": {
        "name": "geographicCoverage",
        "displayName": "Geographic Coverage",
        "title": "Geographic Coverage",
        "type": "NONE",
        "watermark": "",
        "description": "Information on the geographic coverage of the data. Includes the total geographic scope of the data.",
        "childFields": {
          "country": {
            "name": "country",
            "displayName": "Geographic Coverage Country / Nation",
            "title": "Country / Nation",
            "type": "TEXT",
```
