### ISSUE TITLE
Can't validate sitemap, sitemap.xsd root cert change

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#8950]
[Per Steven Frey](https://groups.google.com/d/msgid/dataverse-community/46ac97b2-bc10-4ba5-9a86-2f94aee005fcn%40googlegroups.com), it appears that https://www.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd got a new cert with an Azure  cert signed by the 'DigiCert Global Root G2' cert that isn't in some/all JVMs. Not sure if this will affect tests, but it sounds like it causes sitemap generation to fail and is probably something we want to put out a release notes or other guidance for?

**Comment by qqmyers** [comment]
The certificate store file that needs to be up-to-date is the cacerts.jks file in the config dir, i.e. /usr/local/payara5/glassfish/domains/domain1/config.cacerts,jks

Before an update 
 `curl -X POST http://localhost:8080/api/admin/sitemap`
returns OK since the asnc job started but the log shows
```
[#|2022-08-31T18:04:11.623+0000|WARNING|Payara 5.2022.3|edu.harvard.iq.dataverse.sitemap.SiteMapUtil|_ThreadID=233;_ThreadName=__ejb-thread-pool9;_TimeMillis=1661969051623;_LevelValue=900;|Unable to updat
e sitemap! Exception caught while checking XML staged file (/srv/glassfish/dataverse/docroot/sitemap/sitemap.xml.staged ) against XML schema: schema_reference.4: Failed to read schema document 'https://ww
w.sitemaps.org/schemas/sitemap/0.9/sitemap.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.|#]
```
and the staged sitemap is left in the sitemap dir (could be /tmp or ./docroot/sitemap based on configuration)
To resolve the issue:
`rm sitemap.xml.staged`
(after running the curl above, the log will show an error if a staged sitemap file exists that shows the right path: e.g. `Unable to update sitemap! The staged file from a previous run already existed. Delete /usr/local/payara5/glassfish/domains/domain1/docroot/sitemap/sitemap.xml.staged and try again`)

To add the cert
```
cd <your config dir>
wget https://cacerts.digicert.com/DigiCertGlobalRootG2.crt
keytool -importcert -alias digicertglobalrootg2 -keystore cacerts.jks -storepass <yourpasswd> -file DigiCertGlobalRootG2.crt
rm DigiCertGlobalRootG2.crt
```
restart payara, e.g. `service payara restart`

The java default for the storepass is 'changeit' - not sure if the Dataverse install changes that or not.

**Comment by pdurbin** [comment]
We saw another case of this today:

- #10143

**Comment by qqmyers** [comment]
Closing as this is not a code issue and the problem is hopefully fading away as people update to payara 6
