### ISSUE TITLE
Erro publish Dataset in Dataverse 5.9 with Docker 

### ISSUE THREAD

**Issue by Fernand0S** [IQSS/dataverse#8951]
Error occurred in publish dataset dataverse version 5.11 with docker, below info. environment production

100   426  100   426    0     0  22421      0 --:--:-- --:--:-- --:--:-- 22421
{
  "status": "OK",
  "data": {
    ":Authority": "10.57833",
    ":Shoulder": "CIDACS/",
    ":DoiProvider": "DataCite",
    ":BlockedApiPolicy": "localhost-only",
    ":Languages": "[{\"locale\":\"en\",\"title\":\"English\"}, {\"locale\":\"en\",\"title\":\"English\"}]",
    ":Protocol": "doi",
    ":FilePIDsEnabled": "false",
    ":BlockedApiEndpoints": "admin,builtin-users",
    ":AllowSignUp": "yes",
    ":SignUpUrl": "/dataverseuser.xhtml?editMode=CREATE",
    ":UploadMethods": "native/http"
  }
}

![Captura de Tela 2022-08-31 às 20 41 22](https://user-images.githubusercontent.com/32446123/187804380-07bc987a-6a5e-4273-9a3b-a6298ed10eff.png)

**Comment by pdurbin** [comment]
@Fernand0S anything in the server.log? Is your DataCite password correct? You could test it by hitting DataCite APIs directly.

**Comment by pdurbin** [comment]
@Fernand0S I'm closing this issue but if you're still having trouble, please get in touch!
