### ISSUE TITLE
Cite Dataset: "DRAFT VERSION" instead of version number

### ISSUE THREAD

**Issue by dpx9fR** [IQSS/dataverse#8952]
**What steps does it take to reproduce the issue?**
For a published dataset that has an active draft version, go to the published version and click "Cite Dataset" and select a format for the citation export (e.g. BibTex.) The exported file will display "DRAFT VERSION" instead of the version number. It does not matter whether the user is logged in or not

**Which version of Dataverse are you using?**
This behavior was seen in V5.9 anf V5.11.1,

**Any related open or closed issues to this bug report?**
Discussion about this bug in google groups: https://groups.google.com/g/dataverse-community/c/kOSGz6DV4ZQ

**Comment by pdurbin** [comment]
I showed this to @sekmiller and we agree it's weird. Definitely a bug.

@dpx9fR thanks for letting us know!

**Comment by ErykKul** [comment]
We will pick this issue up and make a PR for this.
