### ISSUE TITLE
On Search API page in API Guide, fix or update values that can be passed to "type" paramter

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#8971]
**What steps does it take to reproduce the issue?**

* When does this issue occur?
When using the Search API

* Which page(s) does it occurs on?
None

* What happens?
The current [Search API page](https://guides.dataverse.org/en/latest/api/search.html) in the API Guide says that "Dataverse", "dataset", or "file" can be used in the type parameter (to limit search searches to those types of objects).

  But the string "Dataverse" needs to be all lowercase:
https://demo.dataverse.org/api/search?q=*&type=Dataverse returns a helpful error that lists the allowed types
https://demo.dataverse.org/api/search?q=*&type=dataverse returns Dataverse collections

  I've run into this error before after following the Search API page. Hopefully improving this can prevent others from hitting this little speed bump.

* To whom does it occur (all users, curators, superusers)?
all users

* What did you expect to happen?
Either:
  - In the documentation's list of strings that can be passed to the "type" parameter, "Dataverse" should be changed to "dataverse" or
  - The Search API doesn't care which letters are capitalized. But is this bad practice?

**Which version of Dataverse are you using?**
v5.11.1

**Any related open or closed issues to this bug report?**
None that I could find

**Comment by jggautier** [comment]
If we'd rather improve the documentation instead of making the Search API not care which letters are capitalized, I'd be happy to submit a PR with the small edit to the page.

**Comment by pdurbin** [comment]
It was changed from "dataverse" to "Dataverse" in b6e1edb and shouldn't have been. We should change it back. (Yes, let's improve/revert the documentation back to how it was.) Good catch. PR #7567 was huge so I'm not surprised we didn't discover this mistake.

**Comment by pdurbin** [comment]
Fixed by this PR:

- #10250
