### ISSUE TITLE
File level metadata: File level metadata tags should wrap and not run off the page

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#8975]
Please fill out as much of the template as you can.
Start below this comment section.
-->
Follow the link to this draft dataset in production, which has a long list of file-level tags and long description:
https://dataverse.harvard.edu/file.xhtml?fileId=6489063&version=DRAFT
The tags run off the page, see screen capture

* When does this issue occur?
Whenever file level tags or description exceed a certain # of characters, not sure how many characters are supported

* Which page(s) does it occurs on?
FILE LANDING PAGE

* What happens?
FILE-LEVEL METADATA TAGS/description RUN OFF THE PAGE WHEN EXCEED CERTAIN #CHARACTERS

* To whom does it occur (all users, curators, superusers)?
SUPER USERS, ADMINS (ALL USERS)

* What did you expect to happen?
* TAGS/TEXT SHOULD WRAP

@scolapasta this is for a paid curation project we plan to release soon. Please add to sprint.

**Which version of Dataverse are you using?**

MOST RECENT

**Any related open or closed issues to this bug report?**

**Screenshots:**

<img width="2080" alt="Screen Shot 2022-09-13 at 4 18 29 PM" src="https://user-images.githubusercontent.com/8322346/190001154-2d82dc1f-73f5-4487-a15f-43ea8e7ce019.png">

**Comment by sbarbosadataverse** [comment]
@jggautier def one to add to our Dataverse backlog, fyi

**Comment by mreekie** [comment]
Priority Review with Stefano:
- Moved from  Harvard Dataverse Instance to Ordered Backlog

**Comment by mreekie** [comment]
sizing:
- this is a GUI bug correction.
- we are hoping this is just a bit of css. 
- size 3
