### ISSUE TITLE
Updating API Guide(s)

### ISSUE THREAD

**Issue by kmika11** [IQSS/dataverse#8978]
**What steps does it take to reproduce the issue?**

* When does this issue occur?
When using the Native API Guide, some of the curl examples don't include ' "" ' [double quotes] around the urls. If a user is using zsh, the request will fail.  

* Which page(s) does it occurs on?
Native API Guide - "Delete Published Dataset" subheading

* What happens?
User receives error: ""zsh: no matches found: https://demo.dataverse.org/api/datasets/:persistentId/destroy/?persistentId=doi:10.70122/FK2/xxxxxx" 

* To whom does it occur (all users, curators, superusers)?
Superusers

* What did you expect to happen?
I expected the dataset to be destroyed. 

**Which version of Dataverse are you using?**
v. 5.11.1

**Any related open or closed issues to this bug report?**

**Screenshots:**
No double quotes in curl example: 

<img width="924" alt="Screen Shot 2022-09-14 at 10 26 09 AM" src="https://user-images.githubusercontent.com/23460791/190182309-8cdd43d1-7a5a-4295-90f6-f7efbe67cce9.png">

**Comment by sirineREKIK** [comment]
A PR was created : #9722

**Comment by pdurbin** [comment]
Closed by this PR:

- #9722

Thanks, @sirineREKIK!
