### ISSUE TITLE
Update GUIDE to include GeoJSON

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#8984]
GeoJSON is not included specifically as a tool in the "file previewers" page of the guide, but it should be.

**Comment by pdurbin** [comment]
Yes, in addition to adding it to a future version of https://guides.dataverse.org/en/5.11.1/admin/external-tools.html#inventory-of-external-tools

... I think we should consider adding GeoJSON and other file types to this list:

![Screen Shot 2022-09-20 at 2 49 19 PM](https://user-images.githubusercontent.com/21006/191346562-0f5c0c17-b69e-4d6b-bd1e-f2c06402237d.png)

... that comes from https://guides.dataverse.org/en/5.11.1/user/dataset-management.html#file-handling

We can explain that some of these file types require File Previewers to be configured.

**Comment by mreekie** [comment]
grooming
 - added this to the top of backlog queue: Harvard dataverse at request of sonia

**Comment by mreekie** [comment]
Size: 3

**Comment by qqmyers** [comment]
I think this has been done: https://guides.dataverse.org/en/5.12.1/admin/external-tools.html#inventory-of-external-tools has GeoJson in it.

**Comment by scolapasta** [comment]
Based on above comment, I've gone ahead and moved this to Ready for Review and pinged @pdurbin to take a look. If we're satisfied that this is competed, we can close this issue.

**Comment by pdurbin** [comment]
Like I said above, I'll add GeoJSON under "File Handling" as well. A tiny PR.

**Comment by pdurbin** [comment]
> GeoJSON is not included specifically as a tool in the "file previewers" page of the guide, but it should be.

My take on this is that @sbarbosadataverse would like to link to a future version of https://guides.dataverse.org/en/5.12.1/user/dataset-management.html#file-previews and see GeoJSON listed.

I just made a pull request: 

- #9380 

## before (5.12.1)

![Screen Shot 2023-02-10 at 9 43 59 AM](https://user-images.githubusercontent.com/21006/218120050-6b51b316-fc1a-4029-b8da-933b94daf273.png)

## after (PR #9380)

![Screen Shot 2023-02-10 at 9 44 09 AM](https://user-images.githubusercontent.com/21006/218120049-539fe70d-fd72-419c-a79b-a51ef961b533.png)

I also wrote up a small section on GeoJSON specifically:

![Screen Shot 2023-02-10 at 9 34 43 AM](https://user-images.githubusercontent.com/21006/218120173-abc4e8c8-d616-4bc9-a0e4-f79b53bdf976.png)
