### ISSUE TITLE
remove rsync from guides (deprecated)

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#8985]
Currently, rsync and package files are featured prominently in the User Guide:

https://guides.dataverse.org/en/5.11.1/user/dataset-management.html#rsync-ssh-upload

![Screen Shot 2022-09-20 at 4 45 29 PM](https://user-images.githubusercontent.com/21006/191361029-62faa565-6ce3-463b-a6b4-324f73088d97.png)

https://guides.dataverse.org/en/5.11.1/user/find-use-data.html#downloading-a-dataverse-file-package-via-url

![Screen Shot 2022-09-20 at 4 46 19 PM](https://user-images.githubusercontent.com/21006/191361227-f9567cee-d11a-4664-a02c-50078b8640a5.png)

**Comment by bencomp** [comment]
This sounds like an easy fix, but seeing other issues also mention rsync, I don't understand if it's really deprecated or already unsupported. What if people still use it?

**Comment by pdurbin** [comment]
Good point. I just asked if anyone is using the rsync feature: https://groups.google.com/g/dataverse-community/c/TMtVpYcqqFM/m/z0t4isZlHQAJ

**Comment by pdurbin** [comment]
I just created a PR to deprecate rsync:

- #10620
