### ISSUE TITLE
Spike: small app with Jakarta EE backend and SPA frontend

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#8987]
In order to understand SPA architecture better, it would be nice to have a small app with a Jakarta EE backend and an SPA front end.

I would probably start with https://github.com/pdurbin/javaee-docker

**Comment by mreekie** [comment]
Limit this scope to 2 weeks.
-

**Comment by pdurbin** [comment]
I'm closing this out. I just gave a demo to @mreekie @sekmiller @siacus @lenwiz @rtreacy @landreev @scolapasta and @jggautier during our daily.

I walked through the following links in a [doc](https://docs.google.com/document/d/1Put8Xg3WRJk6ufcAWCrqwXWkW5q69tergdK0--S6rl4/edit?usp=sharing):

* https://github.com/IQSS/dataverse/issues/8987
* https://people.dataverse.org (Web Components version)
* https://people.dataverse.org/react/build/ (React version)
* https://people.dataverse.org/api/v1/people/list (API, tsv output)
* https://github.com/IQSS/dataverse-people (code)

I touched on these points (among on others, I'm sure):

* The app is useful to me and I hope others 😄 
* I documented a fair amount in the READMEs in https://github.com/IQSS/dataverse-people
* Prod setup with proxy
* For React, `npm build` on laptop, scp to server
* CORS in dev, for now added a hack in the API
* I haven't played with routes, i.e. https://people.dataverse.org/pdurbin but it's important to get right

This was a great exercise. I didn't walk through setting up a local dev environment but it's all documented.
