### ISSUE TITLE
Feature Request/Idea: API endpoint for recommended bibliographic citation text

### ISSUE THREAD

**Issue by mccallc** [IQSS/dataverse#8989]
**Overview of the Feature Request**
Implement a native API endpoint that serves the text of the recommended bibliographic citation (bibliographicCitation) for a dataset.

**What kind of user is the feature intended for?**
(Example users roles: API User, Curator, Depositor, Guest, Superuser, Sysadmin)
API user

**What inspired the request?**
I am currently writing a program for data curators to automatically generate README.txt files for datasets on dataverse. In that README, I'd like to add the recommended bibliographic citation for the dataset as generated by dataverse and visible at the top of each dataset's webpage.

**What existing behavior do you want changed?**
There is an existing [SWORD API endpoint](https://guides.dataverse.org/en/latest/api/sword.html?highlight=citation#display-a-dataset-atom-entry) that offers the bibliographicCitation object, but this is less useful because (reasons in order of importance)

1. It always requires a privileged API key, even though the information is public in published datasets
2. The result is returned in XML, not in JSON
3. The SWORD API is an older codebase I've been discouraged from using

**Any brand new behavior do you want to add to Dataverse?**
I guess the addition of a new API endpoint counts as new behavior, but generating the underlying data I want to retrieve (recommended bibliographic citation text) does not require any brand new behavior.

**Any related open or closed issues to this feature request?**
None I could find from searching.

**Comment by pdurbin** [comment]
@mccallc hi! I'm wondering if the Search API would work for you.

Here's an example of getting the HTML version of the citation:

$ curl -s https://dataverse.harvard.edu/api/search?q=dsPersistentId:doi:10.7910/DVN/TJCLKP | jq -r '.data.items[0].citationHtml'

`Durbin, Philip, 2017, "Open Source at Harvard", <a href="https://doi.org/10.7910/DVN/TJCLKP" target="_blank">https://doi.org/10.7910/DVN/TJCLKP</a>, Harvard Dataverse, V3, UNF:6:2MMoV8KKO8R7sb27Q5GXtA== [fileUNF]`

If you prefer plain text:

$ curl -s https://dataverse.harvard.edu/api/search?q=dsPersistentId:doi:10.7910/DVN/TJCLKP | jq -r '.data.items[0].citation'

`Durbin, Philip, 2017, "Open Source at Harvard", https://doi.org/10.7910/DVN/TJCLKP, Harvard Dataverse, V3, UNF:6:2MMoV8KKO8R7sb27Q5GXtA== [fileUNF]`

In terms of a first class API for citations, it's been talked about here:

- #3140

**Comment by mccallc** [comment]
yes, this will work excellently for my needs! Thanks so much for the direction, and apologies for posting a duplicate issue.

**Comment by pdurbin** [comment]
@mccallc no worries! Good luck on your project!
