### ISSUE TITLE
Allow for Dataverse to send a notification / synching service (web hook) to an application that is using our Data Deposit API

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#900]
---

Author Name: **Eleni Castro** (@posixeleni)
Original Redmine Issue: 3426, https://redmine.hmdc.harvard.edu/issues/3426
Original Date: 2014-01-22

---

During testing with the OJS Dataverse plugin, OJS had asked if there was a way to notify them or provide a synching service if any changes were made to the metadata or data in Dataverse for files that were originally deposited from the OJS application. At the moment this is not possible since the Data Deposit API only allows for a one-way metadata & data sync _OJS-->Dataverse_ and not from _Dataverse-->OJS_. 

To support this feature we would need to investigate possible webhooks that we could integrate with the API. Suggestions: 
1) look into http://en.wikipedia.org/wiki/Webhook
2) NISO-OAI project (currently underway): ResourceSync http://www.niso.org/workrooms/resourcesync/

**Comment by pdurbin** [comment]
We should also take a look at https://github.com/CenterForOpenScience/SHARE

**Comment by bencomp** [comment]
@pdurbin it looks like SHARE uses OAI-PMH to harvest information: https://osf.io/wur56/wiki/scrAPI/

**Comment by pdurbin** [comment]
Let's wait until we have a user stories before we investigate webhooks or ResourceSync. Something real world. Closing.
