### ISSUE TITLE
User Guide (5.11.1) links to incorrect repo for DVUploader 

### ISSUE THREAD

**Issue by cmbz** [IQSS/dataverse#9006]
**What steps does it take to reproduce the issue?**

The 5.11.1 version of the Dataverse User Guide section about the Command Line DVUploader links to the incorrect Github repo. 

* When does this issue occur?
The link currently goes to the IQSS repo: [https://github.com/IQSS/dataverse-uploader](https://github.com/IQSS/dataverse-uploader) which documents the DVUploader Github integration. 

* Which page(s) does it occurs on?

https://guides.dataverse.org/en/5.11.1/user/dataset-management.html#id16

* What did you expect to happen?

Instead, the page should link to the GDCC repo: [https://github.com/GlobalDataverseCommunityConsortium/dataverse-uploader](https://github.com/GlobalDataverseCommunityConsortium/dataverse-uploader)

**Which version of Dataverse are you using?**
5.11.1

**Screenshots:**

![image](https://user-images.githubusercontent.com/18597493/193125818-cf6b14b1-f97f-492a-a105-68e97dd47322.png)

**Comment by pdurbin** [comment]
@cmbz hi! I believe @shlake already fixed this in PR #8852. You can preview the changes at http://preview.guides.gdcc.io/en/develop/

**Comment by cmbz** [comment]
Thanks @pdurbin I'll close this issue!
