### ISSUE TITLE
Support Map-based Data Visualizations Beyond WorldMap

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#901]
On top of supporting WorldMap integration, OCUL/Scholars Portal have their own Geo data visualization tool called Scholars Geoportal http://geo2.scholarsportal.info/. Will follow-up with OCUL to see how/if we could work together to plan for such an integration for a future version of Dataverse.

**Comment by raprasad** [comment]
Also recommended by Alyssa Goodman during the Dataverse community meeting

**Comment by pdurbin** [comment]
I was sitting next to someone (Greg from a university in California, maybe?) at the 2017 Community Meeting who said the WorldMap integration sounds fine but he was interested in creating maps in other systems as well. I gave him a card.

**Comment by djbrooke** [comment]
Closing this, as we now have the external tool framework at the file level and soon at the dataset level (#5028). Any geographic (or other) tools can take advantage of those frameworks.

**Comment by raprasad** [comment]
(whew:)
