### ISSUE TITLE
Sensitive Data: Restricted Metadata Block

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#902]
I have a use case where a professor would like to use Dataverse for teaching and for students to submit their datasets to, but there are privacy issues (e.g., FERPA) related to any student information being collected on a site. 

Only certain metadata fields would have identifiable information. We would need to find a way to restrict a block of metadata so that only people who have proper permissions could see these fields and make sure it's FERPA-compliant. 

The datasets would not have any identifiable information so DataTags / Secure Dataverse would need to help with this.

**Comment by kcondon** [comment]
@posixeleni Can the sensitive metadata be uploaded as a restricted file instead as a workaround and close this until more requests come in?

**Comment by posixeleni** [comment]
They want the restricted metadata to be something their contributors
populate when creating a dataset so I am afraid that's not a workaround
that would work for this use case.

Eleni Castro
Research Coordinator, IQSS
Harvard University

**Comment by pdurbin** [comment]
I don't know if anyone ever directly answered @muelle12 's question at https://github.com/IQSS/dataverse/issues/902#issuecomment-63485930 or not but the people who can see unpublished datasets are the ones who have been given at least a read only role on that dataset (Member). The news on this front is that there is now a feature called "Private URL" that could also be used to give anonymous read only access to an unpublished dataset, if that's desired: http://guides.dataverse.org/en/4.5.1/user/dataset-management.html#private-url-for-reviewing-an-unpublished-dataset

All this is to say that one of the ways to achieve the goal is to not publish the dataset. This runs counter to the DNA of Dataverse, I believe, which is a data publishing platform.

The other workaround, as @kcondon points out, is to put the restricted data in a file. This would allow you to publish the dataset at least.

I'd be interested in hearing if these workarounds would mean we could close this issue.

**Comment by mheppler** [comment]
Closed duplicate issue **Sensitive Data: Request to supported selected sensitive dataset metadata. #3510** opened by @kcondon on Dec 6, 2016.

> See RT 244340. A partner wondered whether a group of researchers working with sensitive metadata could create datasets with sensitive metadata, having to do with locations, publish the datasets but "hide" or control access to the sensitive parts.
> 
> Currently, our proposed sensitive data support assumes public, non-sensitive metadata.

**Comment by djbrooke** [comment]
I'm going to close this as a standalone issue. One of the things we'll need to figure out as part of the Datatags and sensitive data workflow is whether or not to have metadata always available (or some parts...), but we wouldn't work on this independent of the larger redesign.

**Comment by pdurbin** [comment]
Related:

- https://github.com/IQSS/dataverse/issues/9209
- https://github.com/IQSS/dataverse/pull/12319
