### ISSUE TITLE
New Citation block placeholders are too long to view

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#9022]
The placeholder text for several child fields in the citation block are now longer than the input box that contains them, e.g.
![image](https://user-images.githubusercontent.com/6731983/193839046-4a3980a1-718b-4977-9450-5a09f9cbb401.png)

Since the placeholder text doesn't scroll, it can be read in full.

**What steps does it take to reproduce the issue?**
Edit dataset metadata and read the placeholder on fields like the ones shown. Seen on Chrome/Windows.

**Which version of Dataverse are you using?**
5.11.1/5.12

A quick workaround is to add custom CSS to expand these subfields. For example, 

```
div:has(> input[placeholder='1) FamilyName, GivenName or 2) Organization']) {
    width:100%;
}
```

changes fields with that placeholder to look like this:
![image](https://user-images.githubusercontent.com/6731983/193840728-be06e883-5160-4438-8f51-b9098fb29c18.png)

Since this can be done in custom CSS, sites could fix this on their own. However, 

1. it seems like it should work by default, so it would be good to fix this in the distribution, and
2. if there isn't a non-CSS solution, it might help to add an id to the metadata fields that would simplify the CSS selector needed. The one above would have to be replicated for other i18n languages and would break when the placeholder changes. An id="producer-name' or similar would make it easier to target this field (but a placeholder selector might be desired if some i18n translations are much shorter/longer?)

**Comment by poikilotherm** [comment]
FWIW: maybe all fields should have a CSS *class* attached to them, derived from the schema TSV field name? (It seems they don't have right now?) The `id` of each field should be unique. Not sure how Primefaces handles the `id` when you add more items via the "+".

**Comment by qqmyers** [comment]
Closing as stale with the SPA in development
