### ISSUE TITLE
Language: diacritics in metadata block not displayed correctly on demo but ok on build.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#903]
This was found by Liz/ Eleni

The languages field in the Citation block has several languages with diactritics. They are displayed correctly on dvn-build but not on demo, appearing as ?? or diamonds.

**Comment by landreev** [comment]
Please re-test; should be working properly on all servers now (including datavese-demo; see attached)
![accents_display](https://cloud.githubusercontent.com/assets/737558/5825969/4ccc4b2a-a0bd-11e4-9640-263be5c5eb62.png)

**Comment by kcondon** [comment]
OK works now, closing
