### ISSUE TITLE
Feature Request: Zip preview

### ISSUE THREAD

**Issue by lmaylein** [IQSS/dataverse#9035]
Despite the possibility to display hierarchical folder structures in Dataverse, we often decide to publish data publications with a very large number of files as zip archives (one or more).
For the user, it would certainly make sense to be able to find out in advance what to expect in these (large) zip files.
We would therefore like to see a preview function for zip archives, like the one implemented here, for example:
https://zenodo.org/record/6967421#.Yz_iSEzP2Uk
Can you imagine that this could also be implemented for Dataverse?

**Comment by qqmyers** [comment]
As of v5.12, you can configure the [Zip Previewer](https://github.com/gdcc/dataverse-previewers/blob/master/5.2curlcommands.md#zip-previewer-requirements) created by the [Max Planck Digital Library](https://github.com/MPDL).

**Comment by lmaylein** [comment]
Wow! Thanks.

**Comment by pdurbin** [comment]
We should advertise this more. 😄 

I just added the link above (thanks @qqmyers ) under "HTTP Range Requests: New HTTP Status Codes and Headers for Datafile Access API" (the backend part that was required) in the 5.12 release notes: https://github.com/IQSS/dataverse/releases/tag/v5.12

**Comment by lmaylein** [comment]
I didn't know the Dataverse Previewers. This is a great extension. If I understood correctly, however, the entire (possibly very large) files are transferred to github.io on demand, which of course comes with a certain time delay. Would it also be conceivable that a file tree is already extracted during the ingest of zip files. This file tree could then displayed (very quickly) if required.

**Comment by qqmyers** [comment]
That is not how it works - the previewer is loaded from github.io (or where ever you install it) to your browser and your browser makes a call to Dataverse just for the part of the zip file that has the list of files. If you request to download a file from within the zip, only those bytes are transferred. There isn't a need to extract the file tree before hand because you can read just those bytes from the zip when you want.

**Comment by lmaylein** [comment]
That sounds good. Thanks.
