### ISSUE TITLE
Integration with Open Science Framework (OSF)

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#905]
Open Science Framework (OSF) integrates with Dataverse...

- docs: https://osf.io/getting-started/#dataverse
- ticket: https://github.com/CenterForOpenScience/openscienceframework.org/issues/112
- announcement: https://groups.google.com/d/msg/openscienceframework/vb-XKxnF6UA/-3zJnQmUawUJ

... and it would be nice to work with @jeffspies @jmcarp and others at the @CenterForOpenScience to see what API endpoints they could expose on the OSF side to allow for integration with Dataverse. For now this ticket is a placeholder.

**Comment by eaquigley** [comment]
Close as OSF + Harvard Dataverse 4.0 have integrated. If there are other specific issues, those should be opened as new tickets.

**Comment by pdurbin** [comment]
The integration is one-way because we've been waiting to hear about an API on the OSF side (plus we've been busy :) ). Judging from https://github.com/CenterForOpenScience/osf.io/pull/3683 and https://osf.io/y9jdt/ an API is coming. @JeffSpies if you could remember to ping us it would be great.

**Comment by JeffSpies** [comment]
APIv2 coming very, very soon. :)
