### ISSUE TITLE
Make Licenses available as Search Facets

### ISSUE THREAD

**Issue by adam3smith** [IQSS/dataverse#9060]
**Overview of the Feature Request**
Metadata fields can be added to search facets at the dataverse collection level. Now that we have standardized licenses, it'd be great to allow adding licenses as a facet search.

**What kind of user is the feature intended for?**
Curator/admin for setup.
Data user / guest for use

**What inspired the request?**
Since we have a lot of restricted data, allowing users to quickly filter by projects that are _not_ restricted would be very useful and has been requested several times, especially by teaching library and faculty

**What existing behavior do you want changed?**
Facet search customization

**Comment by pdurbin** [comment]
Yes. Good idea. This issue is so highly related, the same pull request would probably address both:

- #7482

**Comment by adam3smith** [comment]
Agreed, yes, 7482 is a precondition for the facets and with that in place they'd likely be trivial to add.

**Comment by adam3smith** [comment]
> Our plan for the case when there are no license but custom terms is to have a single facet "Custom Terms" to search them, is this behavior ok with you and the rest of the community too ? If so we'll add this to the open PR next week :)

That's perfect, yes. I don't see how else we'd handle custom terms

**Comment by luddaniel** [comment]
@DS-INRA @adam3smith this is done : https://github.com/IQSS/dataverse/pull/10204#issuecomment-1897969837
