### ISSUE TITLE
[BagIt Export] Correction on BagIT API Calls

### ISSUE THREAD

**Issue by linsherpa** [IQSS/dataverse#9090]
I wanted to draw atttention on this section of Dataverse_Manual (link below):
https://guides.dataverse.org/en/latest/installation/config.html#id160
Instead the command line should look like this: (validated for localfileArchive)
curl -X POST -H "X-Dataverse-key: API_KEY" 
http://localhost:8080/api/admin/submitDatasetVersionToArchive/:persistentID/Version_Num?persistentID=doi-of_dataset

Also a reference from the dataverse-google-group:
https://groups.google.com/g/dataverse-community/c/UdGIaPjmKGA/m/2qOwImRIBgAJ

**Comment by shlake** [comment]
Section in documents to fix:
https://guides.dataverse.org/en/latest/installation/config.html#api-calls
Also need to fix the (I think was supposed to be) bulleted list in that section.
