### ISSUE TITLE
Erro ao publicar um Dataverse

### ISSUE THREAD

**Issue by MarcosAnjos** [IQSS/dataverse#9097]
Hello guys,

I deployed the project in docker in version 5.11.1
I have an error, when I go to publish a dataverse this message appears.

![Captura de tela 2022-10-26 143749](https://user-images.githubusercontent.com/32145970/198100112-a8a5520c-f27e-4e29-bae2-75f5621b4ed5.png)

**Comment by pdurbin** [comment]
@MarcosAnjos sorry to hear this. Are you using dataverse-docker? If so, it's best to open an issue at https://github.com/IQSS/dataverse-docker

(We are better able to support traditional installations. dataverse-docker is community supported.)

That said, I'm curious what's in your Payara server.log file. 😄  If there's nothing sensitive in it, you can attach it here in a comment. Or you could email it to support@dataverse.org. Thanks.

**Comment by pdurbin** [comment]
Oh! @MarcosAnjos now I see you already opened https://github.com/IQSS/dataverse-docker/issues/75

That's perfect. I'm closing this issue in favor of that one.
