### ISSUE TITLE
Ingest: Restarting glassfish while ingests are in progess cause all completed ingests in same session to show error.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#910]
This is a negative test case but can easily happen in production:

I uploaded multiple ingestable files, many succeeded ingesting but a handful remained in process. Since I wasn't sure whether they were hung or still being processed, after waiting for a while, I restarted glassfish. Since restarting, all previously completed ingests were now marked with the triangle error saying no plugin exists for type tab and the explore button is available.

I'm wondering how we will handle large uploads in v4.0 and how we halt ones that seem stuck.

**Comment by scolapasta** [comment]
For this specific case, if the ingest completes on some of the files that should save to db, while still processing others, right? In other words, each upload should complete as its own transaction.

**Comment by landreev** [comment]
Should be working correctly now. 
Files that were caught in progress by the system crash/reboot will not be stuck in the "in progress" state. 
They will simply show up as regular files (and any dataset locks will be removed). 
Perhaps we could consider automatically re-scheduling such files for another ingest attempt?

**Comment by kcondon** [comment]
This works as described, closing
