### ISSUE TITLE
WorldMap Documentation for 4.0 Release

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#911]
I created a placeholder here: doc/Sphinx/source/Data_Exploration/worldmap.rst

Since we use Sphinx you will need to use the following markup language .rst which I have created a cheat sheet here: https://github.com/IQSS/dataverse/blob/master/doc/Sphinx/SphinxRSTCheatSheet.md

**Comment by eaquigley** [comment]
First draft available here in commit 85dc6a97370b9b35ffce9ae709cc2362d5d8db65

Will add images and jazz it up more later on. Passing ticket to QA.

**Comment by kcondon** [comment]
OK doc is up, closing.
