### ISSUE TITLE
NetCDF/HDF5/geospatial discovery

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#9110]
To ensure we're building the right NetCDF/HDF5/geospatial features, we need to do some discovery.

That is, we need to interview people, hack around with some tools and code, and generally explore the problem space. That's what this issue is about. The parent issue is here:

- #9053

This is timeboxed to end in a sprint

**Comment by mreekie** [comment]
Updated Project status's

**Comment by pdurbin** [comment]
@atrisovic and I have been meeting weekly and have interviewed two researchers so far.

Yesterday we refined our [ideas](https://docs.google.com/document/d/1MtANhyun_X7wE7mwCLwYRu11bfh5hSAXpXKe0fJbxsc/edit?usp=sharing) doc and plan to evolve it into a design doc.

The best way to get involved is to attend a weekly meeting. For details (especially the link to the calendar), please see https://groups.google.com/g/dataverse-community/c/rAdXa7hVeH8/m/eEuQHOqLAQAJ

Closing.
