### ISSUE TITLE
Create a whitepaper for external vocabulary work 1.2.1

### ISSUE THREAD

**Issue by mreekie** [IQSS/dataverse#9114]
Context:
- This came out of the deliverable discussions
Links:
- [2 | 1.2.1 | Design and implement integration with controlled vocabularies | 5#9027](https://github.com/IQSS/dataverse/issues/9027)

**Comment by qqmyers** [comment]
I've created a draft at https://docs.google.com/document/d/17XfX83z23UkUy2v0S0cmHdShjvgB8Q9t5OtcNStZaAI/edit?usp=sharing . Comments/suggestions welcome. Assuming no major concerns, I suggest we share this with the community and get others involved in the design/development of external vocab support to sign on as authors and add/edit/correct as needed.

**Comment by mreekie** [comment]
We discussed this at the sprint meeting yesterday.
This issue is ready for review by someone.
If it passes review it can be marked as done.

**Comment by sekmiller** [comment]
I have no issues with this being shared with the community.

**Comment by mreekie** [comment]
Review Slava's comments.
This is not a lot of work.

**Comment by pdurbin** [comment]
> I have no issues with this being shared with the community.

Me neither. Great paper, @qqmyers! As discussed, I'm closing this issue. A new issue will be create for next steps (sending the around, etc.)

**Comment by qqmyers** [comment]
Final version is at https://docs.google.com/document/d/17XfX83z23UkUy2v0S0cmHdShjvgB8Q9t5OtcNStZaAI/edit?usp=sharing. I've downloaded a pdf copy - anyone should be able to do that from the link.
