### ISSUE TITLE
Enhance Globus support for remote endpoints and tape stores

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#9123]
**Overview of the Feature Request**
Harvard is interested in extending current Globus functionality in two ways:

- Simplify/support the process of referencing a file(s) on a remote endpoint. Nominally this is possible now via the RemoteOverlay store, but there is no support for selecting an endpoint and adding all of the individual files at that endpoint or, optionally, selecting which files within an endpoint should be in the dataset.
- Provide better support for endpoints over tape stores. Tape storage would already have a posix/file endpoint, so adding an S3 endpoint is extra work. Further since tape stores can have delays in retrieving files, Dataverse's internal requests for files (i.e. for thumbnails, ingest, mime determination, read/write of aux files, downloads via S3 (which are still enabled now along side the ability to transfer out via Globus) could all have trouble.

This Issue/task is to create a requirements/design document that will flesh out these issues and propose design ideas for how to meet the requirements. Community input will be requested. The output will be used to decide future work.

**Comment by mreekie** [comment]
Added this to NIH 1.1.1 deliverables backlog.
I'm not 100% sure if this is the right place, but it's someplace I won't forget to look for follow-on work on this topic.

**Comment by cmbz** [comment]
- Updated with label: [pm.GREI-d-2.1.1](https://github.com/IQSS/dataverse-pm/labels/pm.GREI-d-2.1.1) to reflect linkage with open issue: https://github.com/IQSS/dataverse-pm/issues/36.  
- Issue still needs sizing
- **Action**: @cmbz recommends moving to _Needs Sizing_ queue @siacus

**Comment by cmbz** [comment]
- Moved to Needs Sizing as per Slack conversation with @siacus and @sbarbosadataverse

**Comment by cmbz** [comment]
Note: @qqmyers will be handling this issue specifically, therefore it is not sized. It will remain here until the associated pull request is made.

**Comment by cmbz** [comment]
I added the **Waiting** label as a visual reminder that this issue will remain in the Needs Sizing queue until the associated pull request is made.
