### ISSUE TITLE
Installer Documentation

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#913]
@landreev @kcondon @pdurbin need your help to figure out what the main headings / topics we will need to make sure are in the Installer documentation for 4.0. 

How does this look like for starters:

* Quick Install
* System Requirements Prerequisistes
* Running the Installer
* Configuring Optional Components (DOI, R, LOCKSS, etc)
* Installing Updates
* Configuring JVM options: #953
* #917
* Enforcing HTTPS: #56

http://guides.dataverse.org/en/latest/installation

**Comment by scolapasta** [comment]
Documentation for 4.0 is done, so closing this issue. If any specific issues arise relating, a new issue should be created.
