### ISSUE TITLE
3 | 1.3.2 | Research and discovery phase for biomedical workflows support | 5

### ISSUE THREAD

**Issue by mreekie** [IQSS/dataverse#9139]
References:
- [Planning Board](https://github.com/orgs/IQSS/projects/32/views/25)

**Problem Statement**

XXXX

**Proposed Solution**
XXXX

**Acceptance Criteria**
XXXX

---
Last updated: Thu Dec 15 2022 before I left for the holiday
Report: Dec 2022
See [1.3.1](https://github.com/IQSS/dataverse/issues/9034)

10%

---

**Comment by mreekie** [comment]
This issue represents a deliverable funded by the NIH
This deliverable supports the [NIH Initiative to Improve Access to NIH-funded Data](https://datascience.nih.gov/news/nih-office-of-data-science-strategy-announces-new-initiative-to-improve-data-access)

Aim 3: Support standards for sharing code, workflows, and containers

The Harvard Dataverse currently supports depositing any type of file, including code/software and documentation files that accompany data, or files within a research replication package. In this project, we plan to facilitate researchers’ efforts to share and publish their entire workflows or containers that describe the main transformations and analysis of the data, following the FAIR (Findable, Accessible, Interoperable, and Reusable) principles. As a result, the research findings will be portable and reproducible (ideally) with a single command. 

Though the services will be available to any researcher, special attention will be given to the NIH-funded work. The Dataverse project has already undertaken the development of Codemeta metadata (based on the standard schema.org) within the software. The project will assess the use of Codemeta for research software code and incorporate RO-Crate (for research objects metadata), which allows high flexibility in replication package content. 

Further, we will explore container metadata and the use of standardized container images for research. Containerization services, including software security scanning, exist for the Harvard Medical School (HMS) O2 high performance computing cluster, are in use by a number of laboratories, and are being developed by BioGrids, a HMS partner that specializes in creating replicable biomedical software packages and containers. As part of this project, we will explore the integration of these containerization services with the Harvard Dataverse repository to support sharing, discovery, and archival of replicable biomedical research.

**Comment by mreekie** [comment]
Last updated: Thu Dec 15 2022 before I left for the holiday
Report: Dec 2022
See [1.3.1](https://github.com/IQSS/dataverse/issues/9034)

**Comment by mreekie** [comment]
Next steps:
- [ ] Flesh this out with help from Mahmood.

**Comment by mreekie** [comment]
Scheduled a meeting: See
https://github.com/IQSS/dataverse/issues/9034#issuecomment-1377887691

**Comment by mreekie** [comment]
The workflow has been release in 5.12.
What is needed is to needed is to add support for additional use cases specific to the biomedical fields.
- Odun institute computational workflow was reviewed.
- Codemeta workflow was reviewed.
- [BioSchema](https://bioschemas.org/profiles/ComputationalWorkflow/1.0-RELEASE) was reviewed


The terms for the MVP were chosen.
- This is [the Computation Workflow Metadata Planning](https://docs.google.com/spreadsheets/d/1vByU0uGBU-jHEgvXeAs-zMVc7zPt8PiZ4FGoHpKnJy4/edit#gid=1849651392) Sheet
- On this sheet, everything marked MVP has been implemented in 5.12
- We can use this same sheet to go back and choose to implement additional BioMedcal terms.


The container work is also open.
- We can engage with Mahmood to do this.
- Next step here is to touch base with the person from the community who is working on this already (@pdurbin) mentioned the connection today.

**Comment by pdurbin** [comment]
> Next step here is to touch base with the person from the community who is working on this already (@pdurbin) mentioned the connection today.

That would be @carlsonp and @poikilotherm who met today and plan to meet again on Thursday.

**Comment by mreekie** [comment]
monthly update:
- Realized this can be closed. 
- We are on to[ 3 | 2.3.1 | Support biomedical workflows #9371](https://github.com/IQSS/dataverse/issues/9371)

Next Steps:
- Summarize
- Close

**Comment by mreekie** [comment]
Monthly January:

**Comment by mreekie** [comment]
deprecating this deliverable placeholder to reflect how we've been reporting on it, which is both 1.3.1 and 1.3.2 together. Alone this issue does not add value
