### ISSUE TITLE
API Documentation

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#915]
Need to make sure we have documentation ready for 4.0 that clearly documents ALL the APIs that we will have for 4.0.

@pdurbin @landreev @michbarsinai @scolapasta can you confirm what the different APIs for 4.0 will be?

* Native API (For Searching, Creating Dataverses, Creating Datasets...): Does this replace our Data Sharing API from 3.6?
* Data Deposit API (SWORD)
* Other APIs?

**Comment by kcondon** [comment]
For reference, Merce's API requirements doc: https://docs.google.com/document/d/1d8sT2GLSavgiAuMTVX8KzTCX0lROEET1edhvHHRDZOs/edit#heading=h.8v21cm94bv4e

**Comment by esotiri** [comment]
I have updated this google doc, verifying the commands of the API guide: https://drive.google.com/drive/u/0/#folders/0B3_V6vFxEcx-RS1OMGg3YUpCVDQ/0By40CG63udC_T2pZTFBIeURtZGc/0By40CG63udC_cGo2ZGNFTFgtcms

**Comment by pdurbin** [comment]
@posixeleni and @eaquigley heads up that @mcrosas and I just talked about these new sections I added to the API Guide:

- http://guides.dataverse.org/en/latest/api/client-libraries.html
- http://guides.dataverse.org/en/latest/api/apps.html

In these pages we highlight the great work of @rliebz and @leeper in developing client libraries for Dataverse in Python and R, respectively.

We also link to open source applications that make use of Dataverse APIs. The idea is that developers might draw inspiration from these "apps" and see some code examples.

**Comment by leeper** [comment]
:+1:

**Comment by posixeleni** [comment]
:+1:

**Comment by pdurbin** [comment]
Related: #2174

**Comment by scolapasta** [comment]
Documentation for 4.0 is done, so closing this issue. If any specific issues arise relating, a new issue should be created.
