### ISSUE TITLE
Update guides on use of projects/boards used by the project (2 vs. 34, etc.)

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#9157]
We've been using [project 2](https://github.com/orgs/IQSS/projects/2) ("IQSS/dataverse") for a long time and write about it in several places in the guides (below). It has appears in many slide decks over the years.

We should update the guides to reflect how the use of project 2 is changing.

In addition, we should probably write about [project 34](https://github.com/orgs/IQSS/projects/34) ("Dataverse Global Backlog") because some of the functions, especially around pull requests from the community, are shifting to this board.

At a high level, we should continue to encourage the community to contribute to the project and manage expectations about getting their contributions merged.

---

$ ack 'projects/2'
CONTRIBUTING.md
59:After making your pull request, your goal should be to help it advance through our kanban board at https://github.com/orgs/IQSS/projects/2 . If no one has moved your pull request to the code review column in a timely manner, please reach out. Note that once a pull request is created for an issue, we'll remove the issue from the board so that we only track one card (the pull request).
67:[dev efforts]: https://github.com/orgs/IQSS/projects/2#column-5298405

doc/sphinx-guides/source/admin/integrations.rst
181:The `Community Dev <https://github.com/orgs/IQSS/projects/2#column-5298405>`_ column of our project board is a good way to track integrations that are being worked on by the Dataverse Community but many are not listed and if you have an idea for an integration, please ask on the `dataverse-community <https://groups.google.com/forum/#!forum/dataverse-community>`_ mailing list if someone is already working on it.

doc/sphinx-guides/source/developers/documentation.rst
21:That's it! Thank you for your contribution! Your pull request will be added manually to the main Dataverse Project board at https://github.com/orgs/IQSS/projects/2 and will go through code review and QA before it is merged into the "develop" branch. Along the way, developers might suggest changes or make them on your behalf. Once your pull request has been merged you will be listed as a contributor at https://github.com/IQSS/dataverse/graphs/contributors

doc/sphinx-guides/source/developers/intro.rst
43:You can get a sense of what's currently in flight (in dev, in QA, etc.) by looking at https://github.com/orgs/IQSS/projects/2

doc/sphinx-guides/source/developers/version-control.rst
99:Now that you've made your pull request, your goal is to make sure it appears in the "Code Review" column at https://github.com/orgs/IQSS/projects/2.

**Comment by mreekie** [comment]
Historically as PM I don't put stuff on the project board, but I'm taking ownership of this and putting it on my own kanban

**Comment by pdurbin** [comment]
Partially addressed by this PR:

- #10221

**Comment by pdurbin** [comment]
Just before the winter holiday break, we switched from project 2 to 34. We should grep/ack for project 2, as above, and swap in 34 and fix the surrounding text.

**Comment by cmbz** [comment]
2024/01/17: Added to Sprint Ready since it's small and much needed!

**Comment by pdurbin** [comment]
I made a PR:

- #10239
