### ISSUE TITLE
Investigate associating descriptive metadata from metadata blocks with individual files. (Astronomy/FITS is a potential use case)

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#916]
Per our discussion in #614 we will need to support storing FITS file-level metadata at the file level. For 4.0 we can only store metadata values at the aggregate Dataset level.

**Comment by kcondon** [comment]
This appears to be related to file metadata project.

**Comment by pdurbin** [comment]
@kcondon is right and #3259 appears to be the modern incarnation of this issue and actually has a milestone so we should probably close this issue.

**Comment by djbrooke** [comment]
Closing in favor of #3259. Will reference this issue there.

**Comment by pdurbin** [comment]
@djbrooke it looks like you meant to click the close button so I'm closing it for you. :smile:
