### ISSUE TITLE
As a user I would like to be able to include DDI-CDI meta data with a dataset that I import, and be able to export my dataset with the metadata intact.

### ISSUE THREAD

**Issue by mreekie** [IQSS/dataverse#9160]
**Problem Statement**

This came out of the idea that we already support at least one other type of metadata as a black box. We could do the same with DDI-CDI formatted meta-data. 

**Proposed Solution**

We propose to

**Acceptance Criteria**

We will have completed this deliverable when 

**Sizing**
- TBD

**Comment by cmbz** [comment]
Close. We will develop new deliverables based on investigation in https://github.com/IQSS/dataverse/issues/8576
