### ISSUE TITLE
Server Error When Trying to Connect to demo.dataverse.org

### ISSUE THREAD

**Issue by DougCorell** [IQSS/dataverse#9167]
Navigate to https://demo.dataverse.org/ in any browser and you get an error page with a 500 Internal Server Error:

HTTP Status 500 - Internal Server Error
type Exception report

message Internal Server Error

description The server encountered an internal error that prevented it from fulfilling this request.

exception

javax.ejb.EJBException: Exception [EclipseLink-4002] (Eclipse Persistence Services - 2.7.9.payara-p2): org.eclipse.persistence.exceptions.DatabaseException
Internal Exception: org.postgresql.util.PSQLException: Connection has been closed.
Error Code: 0
Call: SELECT ID, CONTENT, LANG, NAME FROM SETTING WHERE ((NAME = ?) AND (LANG IS NULL))
	bind => [1 parameter bound]
Query: ReadAllQuery(name="Setting.findByName" referenceClass=Setting sql="SELECT ID, CONTENT, LANG, NAME FROM SETTING WHERE ((NAME = ?) AND (LANG IS NULL))")
note The full stack traces of the exception and its root causes are available in the Payara Server 5.2022.3 #badassfish logs.

Payara Server 5.2022.3 #badassfish

**Comment by ljw919** [comment]
I met this error too, I try to use the code "api.get_info_version", the BASE_URL used is "https://demo.dataverse.org". The error shows that the website get HTTP 500, and the server encountered an internal error that prevented it from fulfilling this request. How can i solved it ?

**Comment by landreev** [comment]
demo.dataverse.org has been having issues like this in the last few days, on and off. It may be because of some abuse - I'll try to keep a closer look on it. 
(it appears to be down now, I'll restart everything in a sec.)

**Comment by pdurbin** [comment]
Looking good now! Thanks, @landreev!

**Comment by DougCorell** [comment]
Confirmed. It's working again. Thanks @landreev!
