### ISSUE TITLE
Spreadsheet of DV Installations referred to in OAI doc is deprecated 

### ISSUE THREAD

**Issue by sekmiller** [IQSS/dataverse#9168]
**What steps does it take to reproduce the issue?**
Click on "This shared list" link in [the documentation of OAI Server](https://guides.dataverse.org/en/latest/admin/harvestserver.html) and it brings up [a deprecated spreadsheet](https://docs.google.com/spreadsheets/d/12cxymvXCqP_kCsLKXQD32go79HBWZ1vU_tdG4kvP5S8) which in turn has a link to [the current spreadsheet](https://docs.google.com/spreadsheets/d/1bfsw7gnHlHerLXuk7YprUT68liHfcaMxs1rFciA-mEo)

* When does this issue occur?
see above

* Which page(s) does it occurs on?
[OAI Server documentation](https://guides.dataverse.org/en/latest/admin/harvestserver.html) 

* What happens?
Goes to [a deprecated spreadsheet](https://docs.google.com/spreadsheets/d/12cxymvXCqP_kCsLKXQD32go79HBWZ1vU_tdG4kvP5S8)

* To whom does it occur (all users, curators, superusers)?
all

* What did you expect to happen?
link should open [the current version](https://docs.google.com/spreadsheets/d/1bfsw7gnHlHerLXuk7YprUT68liHfcaMxs1rFciA-mEo)

**Which version of Dataverse are you using?**
5.12.1

**Any related open or closed issues to this bug report?**

**Screenshots:**

No matter the issue, screenshots are always welcome.

To add a screenshot, please use one of the following formats and/or methods described here:

* https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests
*

**Comment by jggautier** [comment]
I think the only info in the deprecated spreadsheet missing in the current spreadsheet is the installation's "OAI URL", so I think that info should be moved to the newer and more up to date spreadsheet. (The OAI URL is usually the URL of the repository followed by oai, e.g. `https://dataverse.harvard.edu/oai`, but not always).

If @pdurbin agrees, I'd be happy to move that OAI URL column over to the newer spreadsheet.

**Comment by mreekie** [comment]
Grooming:

This issue was in the New or No Status columns on the Dataverse Global Backlog Board.
Those columns have been removed.
This issue has been removed from the board

This is NOT a reflection of the priority of these issues.
However, as we have worked on the grooming process, it became clear that these issues which are in columns that are not stewarded will likely not get prioritized or sized.

To get this item onto the Dataverse Global Backlog Board, please reach out to one of the Stewards on the board.
You can also reach out to @mreekie and I can connect you with the steward of the appropriate queue

**Comment by pdurbin** [comment]
As stated above, the task is to update this line...

"You might consider adding your OAI-enabled Dataverse installation to [this shared list](https://docs.google.com/spreadsheets/d/12cxymvXCqP_kCsLKXQD32go79HBWZ1vU_tdG4kvP5S8/) of such instances."

... at https://github.com/IQSS/dataverse/blob/develop/doc/sphinx-guides/source/admin/harvestserver.rst

.. and change the "this shared list" link to the current, non-deprecated one: https://docs.google.com/spreadsheets/d/1bfsw7gnHlHerLXuk7YprUT68liHfcaMxs1rFciA-mEo

Should be a "quick fix": https://guides.dataverse.org/en/latest/developers/documentation.html#quick-fix

**Comment by Rehan-stack** [comment]
> As stated above, the task is to update this line...
> 
> "You might consider adding your OAI-enabled Dataverse installation to [this shared list](https://docs.google.com/spreadsheets/d/12cxymvXCqP_kCsLKXQD32go79HBWZ1vU_tdG4kvP5S8/) of such instances."
> 
> ... at https://github.com/IQSS/dataverse/blob/develop/doc/sphinx-guides/source/admin/harvestserver.rst
> 
> .. and change the "this shared list" link to the current, non-deprecated one: https://docs.google.com/spreadsheets/d/1bfsw7gnHlHerLXuk7YprUT68liHfcaMxs1rFciA-mEo
> 
> Should be a "quick fix": https://guides.dataverse.org/en/latest/developers/documentation.html#quick-fix

let me do this
