### ISSUE TITLE
Duplicate property key in Bundle.properties file V5.12.1

### ISSUE THREAD

**Issue by stevenferey** [IQSS/dataverse#9169]
Hi Dataverse Community,

We detected a duplicate keys in the Bundle.properties file : 

advanced.search.datasets.persistentId.tip=The persistent identifier for the Dataset.
advanced.search.datasets.persistentId.tip=The Dataset's unique persistent identifier, either a DOI or Handle

best regards
Steven Ferey.

**Comment by pdurbin** [comment]
@stevenferey thanks!

Yes, confirmed in the develop branch as of 26afd10315

```
src/main/java/propertyFiles/Bundle.properties
935:advanced.search.datasets.persistentId.tip=The persistent identifier for the Dataset.
937:advanced.search.datasets.persistentId.tip=The Dataset's unique persistent identifier, either a DOI or Handle
```

**Comment by jggautier** [comment]
About the duplicate advanced.search.datasets.persistentId.tip lines, the second one is the one that should be used for now.

Looks like in the pull request for improving the tooltips i the Citation metadata block, I left both lines there? Sorry about that. Should I create a PR and remove the first line?

I don't understand how those ingest.csv... lines are mismatches, but I'm happy to help with that, too if you could write more about it @qqmyers. Or if I create a PR, you could fix that duplicate issue?

**Comment by jggautier** [comment]
Ah, thanks! I'll wait for this to be prioritized before creating a PR that removes from the Bundle.properties file:
- the line "advanced.search.datasets.persistentId.tip=The persistent identifier for the Dataset."
- either of the duplicate sets of lines in @qqmyers's two comments

**Comment by poikilotherm** [comment]
Should we add an action that runs a duplicate detection check on the properties files when they are changed?

**Comment by poikilotherm** [comment]
I played with a little shell script (on Linux - no idea if this works on non-GNU MacOS, but it would in a Github Action):

```shell
for PF in $(find . -wholename '*/src/*.properties'); do
    FILTER=$(grep -a -v -E "^(#.*|$)" "$PF" | cut -d"=" -f1 | sort | uniq -c | tr -s " " | grep -v "^ 1")
    if [ -n "$FILTER" ]; then
        echo "$PF"
        echo "$FILTER"
        echo ""
    fi
done
```

And it shows we have more problems with duplicates:

```
./src/main/java/propertyFiles/biomedical.properties
 2 controlledvocabulary.studyAssayMeasurementType.transcription_profiling

./src/main/java/propertyFiles/Bundle.properties
 2 advanced.search.datasets.persistentId.tip
 2 advanced.search.files.persistentId.tip
 2 authenticationProvider.name.builtin
 2 authenticationProvider.name.github
 2 authenticationProvider.name.google
 2 authenticationProvider.name.null
 2 authenticationProvider.name.orcid
 2 authenticationProvider.name.orcid-sandbox
 2 authenticationProvider.name.shib
 2 citationFrame.banner.countdownMessage.seconds
 2 ingest.csv.invalidHeader
 2 ingest.csv.lineMismatch
 2 ingest.csv.nullStream
 2 ingest.csv.recordMismatch

./src/main/java/propertyFiles/customGSD.properties
 2 controlledvocabulary.gsdCourseName.06337:_changing_natural_and_built_coastal_environments
 2 controlledvocabulary.gsdFacultyName.menges,_achim
```

**Comment by poikilotherm** [comment]
Just because I was feeling like it, I went ahead and created https://github.com/IQSS/dataverse/pull/9176

Some fun leisure time hacking!

**Comment by stevenferey** [comment]
Hello,

Can we follow the result of the execution of the [git workflow](https://github.com/IQSS/dataverse/pull/9176)  in order to propose a PR and remove key duplications?

Thank you so much,
Steven.

**Comment by pdurbin** [comment]
@stevenferey I may be misunderstanding but if you go to https://github.com/IQSS/dataverse/pull/9176/files you can see the reports of the duplicates (at the bottom). (Good work, @poikilotherm!) Here's a screenshot:

![Screenshot 2023-07-12 at 17-12-59 9169 fix duplicate keys in Java properties files by poikilotherm · Pull Request #9176 · IQSS_dataverse](https://github.com/IQSS/dataverse/assets/21006/6c516cc1-33ed-4fb9-a23c-1d611e8ea594)

**Comment by jggautier** [comment]
Just noting that [a comment I updated last week](https://github.com/IQSS/dataverse/issues/9169#issuecomment-1318836436) about one of the duplicate keys:

> About the duplicate advanced.search.datasets.persistentId.tip lines, the second one on line 937 was the one we decided to use, but since later changes to Dataverse facilitate the use of PIDs other than DOIs and Handles, I think we should avoid mentioning specific PIDs, and something like the first one on line 935 would be better.

It looks like [the PR](https://github.com/IQSS/dataverse/pull/9718) keeps the other key instead, the one with the value "The Dataset's unique persistent identifier, either a DOI or Handle".

I think this is okay for now. I've been hoping to continue improving and applying [the metadata text guide](https://guides.dataverse.org/en/latest/style/text.html), and the tooltip for persistentId field can be reviewed and improved then.

**Comment by stevenferey** [comment]
Thanks for your feedback,

I modified this key to insert the first proposal.

Steven.

**Comment by jggautier** [comment]
Ah okay. Thanks. So on the advanced search page, the tooltip for the persistent ID field label will be "The persistent identifier for the Dataset." This will be different than what's in the tooltip for the persistent ID field label on the dataset page, right?

Here's a screenshot of that tooltip on the dataset page (after clicking the Metadata tab):
<kbd><img width="392" alt="Screenshot 2023-07-26 at 9 18 38 AM" src="https://github.com/IQSS/dataverse/assets/18374574/5f97d317-2b1b-44b4-a4c4-5ffafdf83c89"></kbd>

**Comment by stevenferey** [comment]
Yes it is. I also propose to modify this label to align the two keys:

- dataset.metadata.persistentId.tip=The persistent identifier for the Dataset.

I note that this formulation is also present for the keys:

- dataset.metadata.alternativePersistentId.tip=A previously used persistent identifier for the Dataset, either a DOI or Handle

- advanced.search.files.persistentId.tip=The unique persistent identifier for a data file, which can be a Handle or DOI in Dataverse.

- file.metadata.persistentId.tip=The unique persistent identifier for a file, which can be a Handle or DOI in Dataverse.

do you want me to change these keys?
Steven.

**Comment by jggautier** [comment]
I'm not sure if this should be changed in the PR for this issue. It feels like scope creep to me, if that makes sense.

Do you know if your PR is for the next Dataverse release, 5.14?

I'm wondering if there would be time to create a new issue to make sure these tooltips are consistent and create a new PR for that issue.

**Comment by jggautier** [comment]
I was talking @scolapasta and it sounds like this PR was not planned to be in the next Dataverse release (v5.14).

We're thinking it would be better to leave the tooltip for the persistent ID field on the advanced search page as it is in 5.13, so it reads "The Dataset's unique persistent identifier, either a DOI or Handle" and leave the other tooltips that you found so far as they are. Then @scolapasta wrote that this PR could go into QA, although it may not be included in 5.14.

And then I'd open a separate GitHub issue about improving these tooltips and include the ones you listed. That way we can maintain the scope of this issue and PR and make sure we're not missing anything else when changing those other tooltips.

Does that sound okay? If so, could you change dataset.metadata.persistentId.tip back to "The Dataset's unique persistent identifier, either a DOI or Handle"?

**Comment by stevenferey** [comment]
Thank you for your reply,

Absolutely, so I modify the key to display the initial value.

Steven.

**Comment by jggautier** [comment]
Awesome! And thanks for spotting those other tooltips!
