### ISSUE TITLE
Documentation: Add information on how to configure drop box jvm option to add files.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#917]
This ticket is a placeholder to add information to the doc on how to register with Dropbox to get a key and then add it as a jvm option to enable add files via drop box feature in Dataverse installations, per feature ticket: https://github.com/IQSS/dataverse/issues/462

**Comment by scolapasta** [comment]
jvm option configuration setup was documented.

Documentation for 4.0 is done, so closing this issue. If any specific issues arise relating, a new issue should be created.
