### ISSUE TITLE
Prep PR #8983 for Sprint

### ISSUE THREAD

**Issue by mreekie** [IQSS/dataverse#9177]
This is about grooming:
 - https://github.com/IQSS/dataverse/pull/8983

This issue or PR is from
- The [Dataverse Global Backlog](https://github.com/orgs/IQSS/projects/34/views/1)
- The "SPRINT PREP" Column.
- There is a draft readme there that has additional information.

Our Objective is to get it into the "SPRINT READY" column
- Take a look at the SPRINT PREP column readme.
- Add the "Technical Tasks" Required Sections:"
- Fill them in.
- If there is anything already in the issue description 
  just add a line i.e. --- at the top and put the required
  sections above what is already there. (No need to 
  delete what is already there)
- The intent is that by thinking/talking through this in 
  a bit of detail will lead to a better estimate of the
  size. 
- Speaking of which, if a PR is well defined per the
  DV definition, then it likely can just be sized. 

Pull in help from anyone on the team

**Comment by pdurbin** [comment]
I made a few commits to the PR:

- #8983

I didn't try the new JVM option but I'm ok sending it to QA to verify that it does.

**Comment by landreev** [comment]
Yeah, it's ready to go - we just need to drag it into the review column, approve it and move it into QA.

**Comment by pdurbin** [comment]
Yes, I agree. I guess we'll wait until the kickoff.

I did go ahead and add a size to the PR (.25).
