### ISSUE TITLE
Permissions: It is possible to revoke the only admin role on a dv, such as root, should be at least one.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#918]
It is possible to revoke the only admin role on a dv, such as root, should be at least one.
In other words, do not allow removing the last admin account for root dv

**Comment by scolapasta** [comment]
for 4.0 we will allow this - we'll be able to still access any dv or ds as a superuser. (we can always ad this after, if deemed important)

We will also consider whether someone should be able to revoke their own role?

**Comment by kcondon** [comment]
Nothing to do here, closing
