### ISSUE TITLE
Feature Request/Idea: Improve Contact Form Email

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#9185]
**Overview of the Feature Request** The current contact form mechanism has some limitations that QDR and others are interested in removing. These include:

- Each contact is sent a separate email, so none of them know who else received a request and there is no single group email where a 'reply all' can be done
- When contacts for a collection or dataset exists, the repository does not receive (via to or cc) an email. For curated repositories, this means administrators are not aware when requests come in
- When the form emails the repository, it uses the :SystemEmail address. [For some repositories](https://groups.google.com/g/dataverse-community/c/b9y7lg2J9-w/m/SrHEk3hFAgAJ), there is interest in making the SystemEmail a no-reply address which would not be useful for support emails
- In determining the form of the name in a greeting, the current code assumes that any comma in the name string implies a person with a \<last name\>,\<first name\> order and it reverses the two parts. This is not correct for names such as 'IBM, Inc.'
- while there is a Feedback API call, it doesn't work and isn't documented.

QDR will submit a PR with changes addressing these issues. As usual the PR can be adjusted/split as desired.

**Comment by pdurbin** [comment]
Hmm, overall sounds fine but at a high level I'll just say that if we're changing behavior and we're not sure if people like some of the old behavior, we should probably add new settings as needed.
