### ISSUE TITLE
About the effect of  Set Metadata Block Facets command

### ISSUE THREAD

**Issue by zhoulvjun** [IQSS/dataverse#9192]
I would like to ask, where in the interface does the command Set Metadata Block Facets come into play? The command description can be found at: Set Metadata Block Facets for a Dataverse Collection (https://guides.dataverse.org/en/5.12/api/native-api.html#id32)

I am able to run the example commands in the documentation correctly, but can't see how this affects the end user interface. If possible, could you give a screenshot of the difference in the interface before and after running the set command? Thanks in advance!

**Comment by pdurbin** [comment]
@zhoulvjun hi! Below is a screenshot from https://github.com/IQSS/dataverse/issues/8536#issuecomment-1106571837

Once datasets have been created that make use of the "Computational Workflow" metadata block (in this example, but it could be any metadata block or blocks), those datasets show up under the "Dataset Feature" facet:

<img width="491" alt="164734585-d4df1cf7-450c-4968-8d3e-d5d787de8aec" src="https://user-images.githubusercontent.com/21006/204368314-0699e70c-756c-4ceb-82d7-f46ce3361f88.png">

**Comment by zhoulvjun** [comment]
So that's it! I did see results after I set the appropriate metadata blocks! Thank you for your prompt and clear guidance!
