### ISSUE TITLE
Document configuring temp. directories used  for file uploads

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#9196]
This is a child issue of a huge "refactor upload" issue #6656. 
This is something we've been meaning to do literally for years; really a shame we haven't done it yet. 

This part of the system is somewhat counter-intuitive (total of 3 different temp. locations involved) and it keeps confusing installation admins. But documenting it should be fairly trivial. 
One _slightly_ non-trivial thing we should investigate in the process is whether there is a simpler/more elegant way to configure the upload directory used by PrimeFaces than the one that's currently available. (see the parent issue for more details)

**Comment by poikilotherm** [comment]
Hi @landreev are you aware of my #8983 sitting around?

**Comment by landreev** [comment]
I was about to mention that this issue may have been created as a result of some confusion/miscommunication on this end (I was told that this part of #6656 needed to be addressed, as a new thing. They must have meant your PR). I am aware of yours _now_; will close this.
