### ISSUE TITLE
Dataverse installation using Dataverse v5.3 is unable to harvest datasets from Dataverse installation running Dataverse v5.12

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#9197]
**What steps does it take to reproduce the issue?**

* When does this issue occur?
When a Dataverse installation, https://dataverse.theacss.org, which is using Dataverse v5.3, is unable to harvest datasets from Dataverse installation, https://dataverse.harvard.edu, running Dataverse v5.12

* What happens?
The managers of the repository receive an error when trying to run the harvesting client for the set I created in the Harvard Dataverse Repository called "Survey_for_Young_People_in_Egy". The set contains two records. You can see them at https://dataverse.harvard.edu/oai?verb=ListRecords&metadataPrefix=oai_dc&set=Survey_for_Young_People_in_Egy

  They also reported that they see:
`Exception processing harvest, server= https://dataverse.harvard.edu/oai,format=oai_ddi com.lyncode.xoai.serviceprovider.exceptions.InvalidOAIResponse OAI responded with code: badArgument`

  @donsizemore says that the last successful run of the harvesting client was Oct 30th. He also says that "from our side the ACSS server's harvesting code no longer peers with Harvard's".

  See more of the discussion, and more error messages in the email thread at https://help.hmdc.harvard.edu/Ticket/Display.html?id=278227#txn-7627246

* To whom does it occur (all users, curators, superusers)?
Superusers, curators

* What did you expect to happen?
The ACSS repository is able to harvest the metadata from the Survey_for_Young_People_in_Egy set

**Which version of Dataverse are you using?**
The installation trying to harvest the set is using Dataverse v5.3. The installation that the set is from is using Dataverse v5.12

**Any related open or closed issues to this bug report?**
@donsizemore wrote that he suspects "the XOAI rewrite / library update", so whatever issue or issues are related to that could be related to this bug report.

**Comment by mreekie** [comment]
Notes:
- This customer is running an old version of Dataverse.
- The issue appears to not be present in the current version of Dataverse.

**Comment by donsizemore** [comment]
Odum (still) plans to upgrade ACSS to 5.10.1, which according to my testing makes this go away. Closing issue.
