### ISSUE TITLE
Groups UI

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#92]
---

Author Name: **Michael Bar-Sinai** (@michbarsinai)
Original Redmine Issue: 3501, https://redmine.hmdc.harvard.edu/issues/3501
Original Date: 2014-02-03
Original Assignee: Michael Bar-Sinai

---

Create a UI for groups CRUD.

**Comment by mheppler** [comment]
FRD: https://docs.google.com/document/d/1P4HOUuJEoPfU06-4R9xP0nRFapNyZUg5xnjYNVRvFik/

**Comment by mheppler** [comment]
Mock ups: https://iqssharvard.mybalsamiq.com/projects/groupsui/grid

**Comment by eaquigley** [comment]
@michaelsuo worked on this for 4.0.2, if this is ready, please send to QA.

**Comment by scolapasta** [comment]
Update from @michaelsuo: 

The application logic for CRUD operations on groups is all done, as is the separate "Manage Groups" page. The only thing left to do is the front-end for editing an existing group (i.e. the separate dialog box that lets a user add and remove group members). Should only take a day or two of work.

@kcondon can you please test this, and the remaining part we'll leave for 4.2?

**Comment by kcondon** [comment]
Basic Groups UI is delivered, bugs and incomplete functionality has have been opened in separate tickets. Closing.
