### ISSUE TITLE
Front page: "Sort by Oldest" is much slower than other sorts

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#920]
When the systems is loaded with dummy data (1100+ dataverses, 9,000 datasets), the homepage sort options works with the exception of "sort by oldest." It takes a long time (minute or so) to load the page is sorting 'by oldest'.

Just noting this--it may also be due to the test data being added concurrently.  (The concurrent loads didn't seem to effect the other sorts.)

**Comment by pdurbin** [comment]
@raprasad can you please remind me how you loaded up so much dummy data? Can you point me to a script?

**Comment by raprasad** [comment]
Phil, am running this now with just many dataverses (but not many datasets), to see if the same bug occurs.

\cc @pdurbin

**Comment by pdurbin** [comment]
@raprasad just walked me through https://github.com/IQSS/dv-api-test/blob/master/scripts/make_dataverses.py and https://github.com/IQSS/dv-api-test/blob/master/scripts/dataset_maker_books.py . Great stuff.

**Comment by sbarbosadataverse** [comment]
When the systems is loaded with dummy data (1100+ dataverses, 9,000 datasets), the homepage sort options works with the exception of "sort by oldest." It takes a long time (minute or so) to load the page is sorting 'by oldest'.

I don't have the option to test the amount of dataverses and datasets in this initial report. sort from oldest works within second in build----that's only 19 dataverses, and 44 datasets

**Comment by kcondon** [comment]
Tested on vm6 with lots of data. They're all slow. Will address as part of performance review after full migration. Closing.
