### ISSUE TITLE
Retrospective: All dev work gets represented on the board.

### ISSUE THREAD

**Issue by mreekie** [IQSS/dataverse#9203]
We should understand how much time people are actually spending on board tasks.  Ask at the end of the daily to see if anyone is working something off the board. 

Def of done:
- Work items need to be worked during sprints and from the sprint backlog.
- Work includes non code research on new items which we can represent as spikes
- Emergencies happen. When they do, size the issue and add it to the work in process for this sprint.

**Comment by mreekie** [comment]
This item has no dev action and so no size associated with it.
It's a policy thing that we'll check ourselves on during the sprint.

**Comment by sekmiller** [comment]
Are we going to represent ongoing items such as community engagement and production support on the board for each sprint?

**Comment by mreekie** [comment]
Keeping this open but without a size.
We can cover Stephens question at a standup then close this.

**Comment by sekmiller** [comment]
When a PR is added to the sprint based on a dev ticket that is part of the sprint do we assign a size to the PR? The process previously was to remove the corresponding ticket from the project, but in so doing we lose the size of the original ticket.
