### ISSUE TITLE
Clarify in guides that APIs do not support OIDC

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#9223]
## When does this issue occur?

If you look at https://dataverse.org/software-features you see the following about OIDC:

"Login via OpenID Connect (OIDC)

Log in using your institution's identity provider or a third party. [More information](https://guides.dataverse.org/en/latest/installation/oidc.html)."

This is accurate. In the guides you see an explanation of OIDC support in Dataverse but we don't explicitly explain that OIDC cannot be used as a way to authenticate to Dataverse APIs.

To be clear, some day it would be very nice to support OIDC with PKCE as a way to authenticate to Dataverse APIs, but for now let's simply set expectations better in the guides (and perhaps on the features page). Otherwise, people building apps or even their own frontend to Dataverse might be disappointed.

## To whom does it occur (all users, curators, superusers)?

API users.

## Which version of Dataverse are you using?

5.12.1

**Comment by pdurbin** [comment]
@poikilotherm @johannes-darms can we close this now that we've merged the PR below?

- #9591

That PR closed this issue:

- #9229

**Comment by johannes-darms** [comment]
@pdurbin indeed we can close this issue. We could add a disclaimer that the authorization (groups and ACL) is not integrated from an external service and is managed inside dataverse.

**Comment by pdurbin** [comment]
@johannes-darms thanks! I'll close this one.

Maybe you can suggest a doc change to this PR (which I'm actively reviewing) for the disclaimer:

- #9273
