### ISSUE TITLE
Allow users to specify their ORCID and/or ISNI ID in their user account

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#923]
From a meeting with @mcrosas @scolapasta and @pdurbin we should allow users to specify their ORCID and/or ISNI ID for their user account at sign up or later when editing their account.

This is for user accounts, not datasets, per https://docs.google.com/a/harvard.edu/document/d/1bZjEsejCaw1U6zNkER7iaZbysmXRKmonp9tKLUn-4LI/edit?usp=sharing

See also #829.

**Comment by scolapasta** [comment]
Is this for built in users or also shibboleth? currently, I don't believe we allow users to add any extra info (yes, including usernames) for shibboleth )or other external).

**Comment by pdurbin** [comment]
> Is this for built in users or also shibboleth?

All users should be treated equally.

**Comment by eaquigley** [comment]
Since 4.0 is now coming out towards the end of March and I am already rethinking the Logging In process, I would like to add this field in to the registration form.

**Comment by posixeleni** [comment]
@eaquigley would this field also be pre-populated in the Dataset form like we do for the author name? This would save the user a lot of time having to re-enter the same information twice (or multiple times if they have many datasets).

**Comment by eaquigley** [comment]
@posixeleni yes ma'am, anything from the user sign up that relates to dataset metadata needs to be pre-populated.

**Comment by pdurbin** [comment]
If we're going to revisit the registration form, can we please make it so **all users** can enter "Position" (or simply remove "Position" altogether?). Currently only builtin users can specify their position. (If we need a separate ticket to revisit the builtin user table vs. the authenticateduser table, that's fine.)

Obviously, **all users** should be able to specify their ORCID or other ID, not just builtin users.

**Comment by eaquigley** [comment]
To do for this:
- [ ] add field to account registration for user identifiers 
- [ ] what are the technical details for allowing shibboleth users to add in their ORCID? I do think that we need to figure out how that can happen and that it shouldn't be a built in user feature only

**Comment by pdurbin** [comment]
For guidance from @mcrosas on this feature please see the notes from [2015-04-30 Dataverse User Accounts and Auth Meeting](https://docs.google.com/document/d/157sw9gaFGwrb0EtCGGlLMxSg0cooHfKEvIsjcebPcA8/edit?usp=sharing). @eaquigley you are right that this will not be a feature only for builtin users. All users will benefit.

**Comment by eaquigley** [comment]
FRD for this has been worked on by @suenjedt and myself. Link here: https://docs.google.com/document/d/1bAkeEF72MBpy8AHEABasc8SO2RcRmhnQ9D71pXGjkkI/edit?usp=sharing

**Comment by mcrosas** [comment]
:+1:  

Let's plan a review with someone from ORCID and Alberto Accomazzi

**Comment by suenjedt** [comment]
I already contacted ORCID-Liz and will set up the meeting once I know more about her agenda.

**Comment by suenjedt** [comment]
An update from the meeting:
- There is a preference from the ORCID side to start with Oauth and Phase 2
- However, there are examples, e.g. by ANDS where Phase I equivalent widgets are built http://developers.ands.org.au/widgets/orcid_widget/.
- Discussion shows preference to start with Phase 1 as planned, with suggestions for ORCID records (similar to ANDS integration)

----

quick update: I asked our colleagues at ANDS, who could not give me any additional information in regards to their ORCID widget that we looked into during our ORCID meeting. The other tool that was mentioned has not been implemented yet. More details (e.g. code) to follow from my CERN colleagues.

----
My summary from the meeting and follow up conversations:  there are different models for implementations (e.g. publisher's manuscript submission systems, repositories or community portals such as ADS). ORCID prefers an Oauth integration for most, or all. However, it seems feasible to start with our planned Phase 1 and I, personally, dont see why we should not move as planned. Phase 1 is already an enhancement to the current state and Phase 2 requires more discussion and thus would happen much further down the road. 

You are of course welcome to revise my summary.

[However, what is probably needed, is a conversation about Oauth as well, non?]

**Comment by pdurbin** [comment]
I've listed OAuth as an interest of the Dataverse Auth Community Group: https://docs.google.com/document/d/1xbWkj_OIk13gKe7jleNXVvakZErvHLA8JRBvLz8Fe8Q/edit?usp=sharing

**Comment by pdurbin** [comment]
> what are the technical details for allowing shibboleth users to add in their ORCID?

From an email I sent last summer:

> Eventually, we may be able to get ORCID IDs from Shibboleth in the form of a SAML assertion of an "eduPersonOrcid" attribute per the (unfinalized) spec linked from https://spaces.internet2.edu/display/macedir/ORCID+and+other+researcher+IDs
> 
> This was mentioned yesterday in the IT Summit talk "Enabling Cross-University Collaboration with Harvard IAM: TIER, InCommon, and Grouper"

**Comment by pdurbin** [comment]
This issue is highly related to #3338 which is currently under development.

**Comment by djbrooke** [comment]
I'm going to close this in favor of #3338.

**Comment by djbrooke** [comment]
Talked with @scolapasta, got some more info, reopening. Oops.

#3338 deals with logging in with / converting an account to use ORCID. This issue deals with maintaining an ORCID association for non-ORCID accounts AND using an ORCID throughout the application.

**Comment by djbrooke** [comment]
This is out of scope for #3338 and will live on a separate issue.

**Comment by pdurbin** [comment]
Out of scope for #3507 too.

**Comment by pdurbin** [comment]
Today I stubbed out a `getOrcidId` method on `AuthenticatedUser` in ca33857 but it's only for users who log in via ORCID.

**Comment by pdurbin** [comment]
I'm closing this until we decide to start working on it.
