### ISSUE TITLE
Line 765 breaks auto-generated e-mails

### ISSUE THREAD

**Issue by Bramvdhout** [IQSS/dataverse#9235]
Generated e-mails confirming access to files has been granted will break because of the closing parenthesis, The parenthesis is added to the end of the link to the dataset, and some of our users can't figure out how to fix this on their own.

https://github.com/IQSS/dataverse/blob/be48cfda1e0f9784d1e8bd16fbdba59a87f86a8f/src/main/java/propertyFiles/Bundle.properties#L765

Is it possible to remove or change the parenthesis in this line?

Thank you

**Comment by pdurbin** [comment]
@Bramvdhout hi! I'm confused. I thought we fixed this already in Dataverse 5.10:

- #8324

That is, we added a space between the link and the closing parenthesis to make sure the link is clickable. Are you running 5.10 or newer? Can you please paste an example of what the final email looks like? Thanks!

**Comment by Bramvdhout** [comment]
We're running v. 5.12 build 1119-71341c0
 

The final e-mail looks like this: 

"Hello,
Access granted for files in dataset: Files from XXXX database (view at https://url.urlcom/dataset.xhtml?persistentId=hdl:1xxxx/Jx9xxBxx).

You may contact us for support at Example@emailexample.com."

**Comment by pdurbin** [comment]
@Bramvdhout weird! No space in the final email and yet there's a space in the code. Are you running a custom Bundle.properties? Again, there's already a space in the code so I don't know what we'd change exactly. Unless, as you suggest, we rewrite the message to remove the ().

**Comment by Bramvdhout** [comment]
Very weird indeed! Rewriting the message would probably break things for a lot of people, so we'll try to change the message on our end, somehow.
Thank you so much for your replies and efforts!

**Comment by pdurbin** [comment]
@Bramvdhout sounds good. Good luck and have a nice weekend!
