### ISSUE TITLE
Crowdsourcing rating tool of dataset 

### ISSUE THREAD

**Issue by mercecrosas** [IQSS/dataverse#924]
This is proposed by Allan Dafoe and @mcrosas 

We would like a tool to allow users to rate a dataset based on whether is well curated and reusable for replication. The tool could include a rating with the following levels: (1) Data files are available, (2) Data files are complete (3) Data files and documentation are clear

**Comment by pdurbin** [comment]
If we do want to integrate this idea with the idea of badges, the badges issue is #2119

**Comment by mheppler** [comment]
Also related to badges Dataset - Peer Reviewed Tag or Badge #565.

**Comment by djbrooke** [comment]
Closing this in favor of #6041 for a more generalized approach.
