### ISSUE TITLE
Intermittent error from the new Harvesting Clients test 

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#9240]
Has been observed a couple of times on Jenkins since the PR #9227 was merged. Meaning, it's intermittent, the test passes on most runs. 
The error happens in the new test that's somewhat extensive and runs a real harvest of an external archive. However, the 500 below happens before anything heavy is attempted, merely when creating the new harvesting client: 
```
java.lang.AssertionError: expected:201 but was:500
at edu.harvard.iq.dataverse.api.HarvestingClientsIT.testHarvestingClientRun(HarvestingClients0T.java:184)
```
which is really a cheapest operation you can think of. This makes me think that this is another weird timing condition caused by an overall load of a full restassured run on the system. I expect it to be straightforward to fix/work around.

**Comment by pdurbin** [comment]
@landreev thanks for opening this issue. Another failure just occurred (same line and 500 as above):

- https://jenkins.dataverse.org/job/IQSS-Dataverse-Develop-PR/job/PR-9262/1/testReport/edu.harvard.iq.dataverse.api/HarvestingClientsIT/testCreateEditDeleteClient/

**Comment by kcondon** [comment]
Happens with Sonarcube Fixes #9320, too. Not sure if keeping track of failures is helpful here?

**Comment by pdurbin** [comment]
Another one: https://jenkins.dataverse.org/job/IQSS-Dataverse-Develop-PR/job/PR-9290/10/testReport/edu.harvard.iq.dataverse.api/HarvestingClientsIT/testCreateEditDeleteClient/

**Comment by landreev** [comment]
I pulled it into this sprint yesterday, I'm definitely willing to spend a couple of hours resolving this. But I am also determined to keep the amount of effort under the assigned "10". If it turns out non-trivial at all to be able to truly figure out what's going on, I'm going to just throw seconds of sleep at it until it passes reliably.

**Comment by pdurbin** [comment]
We had a related failure on develop yesterday: https://jenkins.dataverse.org/job/IQSS-dataverse-develop/1306/consoleFull

"[ERROR] Failures: ", "[ERROR]   HarvestingClientsIT.testCreateEditDeleteClient:109 expected:<201> but was:<500>",

For the line number, develop is e12f3e6

**Comment by landreev** [comment]
Just grabbed this issue, going to throw some copious amounts of sleep at it.

**Comment by landreev** [comment]
Ouch. It has nothing to do with timing. And everything to do with the laws of probability.
