### ISSUE TITLE
Dataset API: Json files for creating and updating a dataset no longer work after latest metadata block change.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#925]
Using any of these json files from the data directory causes an error on create or update dataset.

dataset-bad-missingInitialVersion.json 	Adding datasets and datasets via API - DONE. 	4 months ago
dataset-create-new.json 	Adding datasets and datasets via API - DONE. 	4 months ago
dataset-updated-version.json 	Adding datasets and datasets via API - DONE.

**Comment by michbarsinai** [comment]
File dataset-bad-missingInitialVersion fails properly with message:
```
{"status":"ERROR","message":"Json POST data are missing initialVersion object."}
```

**Comment by michbarsinai** [comment]
Files fixed.

**Comment by kcondon** [comment]
OK, files are updated, work. Closing
