### ISSUE TITLE
flaky test: DownloadFilesIT.downloadAllFilesRestricted

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#9259]
@landreev and I have been discussing how DownloadFilesIT.downloadAllFilesRestricted has been flaky lately: https://iqss.slack.com/archives/C03R1E7T4KA/p1670439958671239

That is, it fails periodically with no known rhyme or reason. We should fix it.

Some places where we saw it fail:

- after #8983 was merged: https://jenkins.dataverse.org/job/IQSS-dataverse-develop/1209/consoleFull (
- #9257 (run 2 on Jenkins)

**Comment by qqmyers** [comment]
FWIW: The failure at https://github.com/IQSS/dataverse/blob/ac1454b50ee892bdb410d4dd96a56cba6883394d/src/test/java/edu/harvard/iq/dataverse/api/DownloadFilesIT.java#L301-L302 is at least consistent with a timing issue as there's a file upload right before it that could potentially not yet be complete.

**Comment by pdurbin** [comment]
I suppose this test is less flaky these days. We haven't heard about it lately. Closing.
