### ISSUE TITLE
Test and move from Solr 8.X to Solr 9.X

### ISSUE THREAD

**Issue by carlsonp** [IQSS/dataverse#9260]
**Overview of the Feature Request**

Solr `8.X`, specifically, `8.11.2` according to [this page](https://solr.apache.org/downloads.html): "is the last release in the 8.x series."  This means it likely won't be receiving any more updates, features, or patches.  This also may have implications from a security perspective.  The Dataverse Solr schema and [major changes](https://solr.apache.org/guide/solr/latest/upgrade-notes/major-changes-in-solr-9.html) should be reviewed and tested.

- [ ] Evaluate and update Solr schema if needed
- [ ] Smoke-test with Solr `9.X`
- [ ] Update documentation
- [ ] Document migration steps?

**What kind of user is the feature intended for?**

Sysadmin and developers

**What inspired the request?**

**What existing behavior do you want changed?**

**Any brand new behavior do you want to add to Dataverse?**

**Any related open or closed issues to this feature request?**

**Comment by pdurbin** [comment]
Not sizing this for now. Hoping we can help @carlsonp make a pull request. 😄 Please let us know!

Please note that this issue and PR are related:

- #7662
- #8320

This might be somewhat easy to test by bumping the Solr version in dataverse-ansible (@donsizemore would know).

**Comment by carlsonp** [comment]
Migration away from Solr `8.X` would help us in our intended deployment of Dataverse to Azure commercial.  We're getting a lot of pushback on vulnerabilities both [false-positives in the eyes of the Apache foundation](https://solr.apache.org/security.html) as well as other vulnerabilities as CVEs.  From scanning tools, they're picking up these CVEs and our Cybersecurity team wants them to be patched.  We aren't interested in forking or patching upstream Solr so it seems Solr `9.X` is a better longer-term solution.  When I push and scan Solr `9.X` there are less CVEs listed.  This could be a major hold-up or full blocker in our ability to run Dataverse.

**Comment by pdurbin** [comment]
@carlsonp makes sense. Would you be able to email a list of Solr CVEs your tool is picking for Solr 8.11.1 (the version we use currently) to security@dataverse.org?

**Comment by mreekie** [comment]
Grooming:
- Including as part of Payara 6 upgrade

**Comment by donsizemore** [comment]
@pdurbin I just heard from the security hydra about my brand-new private Dataverse instances. Per Solr's security page https://solr.apache.org/security.html we're not realistically vulnerable to the CVEs in question, but I opened https://github.com/IQSS/dataverse-security/issues/79 in response to the newer CVE.

**Comment by carlsonp** [comment]
> @carlsonp makes sense. Would you be able to email a list of Solr CVEs your tool is picking for Solr 8.11.1 (the version we use currently) to [security@dataverse.org](mailto:security@dataverse.org)?

This is complete.

**Comment by cmbz** [comment]
- Prioritizing Payara 6 release
- Sizing needed

**Comment by cmbz** [comment]
Sized as 33
Note: Has some requirements that might impact upgrade

**Comment by pdurbin** [comment]
@carlsonp I finally made a PR!

- #9787 

Please come back! ❤️ It's even containerized!!!11! 😄 🚀 🎉

**Comment by carlsonp** [comment]
Awesome! :D
