### ISSUE TITLE
give contributors guidance on how to write a release note snippet

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#9264]
Currently, the information is buried here: https://guides.dataverse.org/en/5.12.1/developers/making-releases.html#write-release-notes

We should add something to the "how to make a pull request" docs: https://guides.dataverse.org/en/5.12.1/developers/version-control.html#how-to-make-a-pull-request (this is a bit buried too, by the way).

We might also want to add something here: https://guides.dataverse.org/en/5.12.1/developers/documentation.html#quick-fix

**Comment by pdurbin** [comment]
Here's the file to edit: https://github.com/IQSS/dataverse/blob/develop/doc/sphinx-guides/source/developers/version-control.rst

Suggestions on how to edit the file: http://preview.guides.gdcc.io/en/develop/developers/documentation.html

**Comment by bencomp** [comment]
And if you want to stimulate (or enforce) the addition of release notes, you could use a GitHub workflow to suggest or check for them. I am thinking something like "if PR notes say release notes are needed, then check if a corresponding file exists and respond with 'thank you!'. Else, gently remind the contributor that no release notes were found."

**Comment by pdurbin** [comment]
Sure, maybe a reach goal for this issue. 😄 

But just some docs is also fine.

**Comment by sbondka** [comment]
Could you please provide me with more information regarding this issue? I have started making changes in the "Commit Your Change to Your New Branch" and "Find or Create a GitHub Issue" sections of the file "https://github.com/IQSS/dataverse/blob/develop/doc/sphinx-guides/source/developers/version-control.rst". Should I also include in the "Make a Pull Request" section the automated process related to adding release notes?

**Comment by pdurbin** [comment]
@sbondka yes, that would be a perfect place for it.

However, the process isn't automated. Contributors write snippets and later someone manually combines them.

Please feel free to hit me up on https://chat.dataverse.org with any questions! Thanks for your interest in this!

**Comment by pdurbin** [comment]
Whoops, now I see that you already created this PR:

- #10203

I'll make some suggestions or edits. Thanks!
