### ISSUE TITLE
"developed by" in README links to ~~inaccurate list of people who develop Dataverse~~ a 404

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#9267]
Currently (as of ac1454b), our README starts with this line about what Dataverse is and who it's developed by:

> Dataverse is an [open source](https://github.com/IQSS/dataverse/blob/develop/LICENSE.md) software platform for sharing, finding, citing, and preserving research data (developed by the [Data Science and Products team](http://www.iq.harvard.edu/people/people/data-science-products) at the [Institute for Quantitative Social Science](http://iq.harvard.edu/) and the [Dataverse community](https://dataverse.org/developers)).

The Data Science and Products team no longer exists and hasn't for years. So while we link to http://www.iq.harvard.edu/people/people/data-science-products in the README, one is redirected to the Product Development team list at https://www.iq.harvard.edu/people/role/product-development

Below is a screenshot of that list of people in the Product Development team as of this writing. It's not entirely accurate for our purposes in that not all of these folks actually work on Dataverse (yet! 😄 ).

![deleteMeGimpAlt-1](https://user-images.githubusercontent.com/21006/211172219-2cf11b4a-396f-41b8-aa06-a5178763294c.png)

More importantly, there are people missing who DO work on Dataverse! What about Sonia, Julian, and Dwayne?

<img width="965" alt="Screen Shot 2023-01-07 at 3 07 52 PM" src="https://user-images.githubusercontent.com/21006/211168619-40619805-cf16-475b-9c8c-a592b94bd3c2.png">

Plus [Katie](https://hlrdm.library.harvard.edu/people/katie-mika) who technically works for the Library but is very much part of the curation team:

![thumbnail_image001](https://user-images.githubusercontent.com/21006/211168686-f688a45e-ea93-47d2-bd5b-4d207a0def53.jpg)

Plus Jeremy and perhaps others who work for Soner and do tier one support for everything coming into support@dataverse.edu.

Beyond Harvard folks we very recently [announced](https://groups.google.com/g/dataverse-community/c/uDeNUfqe3RE/m/dph8fZUaEAAJ) an expansion of the core development team:

"We are delighted to announce that Jim Myers (GDCC/QDR), Oliver Bertuch (FZJ/HERMES) and Don Sizemore (GDCC/Odum) have accepted an invitation to join our Core Development Team. We look forward to their continued contribution to Dataverse."

<img width="480" alt="Screen Shot 2023-01-07 at 3 36 41 PM" src="https://user-images.githubusercontent.com/21006/211169486-45bcb4d7-417c-4921-9c93-829754a6b03a.png">

It would be great to incorporate these fine folks into the list of people who develop Dataverse!

Definition of done for this issue:

- Develop a better location for the README to link to. Perhaps we could cleanup "The Team" under https://dataverse.org/about (screenshot below) and link there? I'm giving this a size of "3" because this is the easiest quick fix I can think of.
- Update the link in the README and improve the wording surrounding it.
- (Optional) Document what it means to be part of the core development team. (My understanding is the main thing change is that you are authorized to approve pull requests and move them into QA.)

<img width="587" alt="Screen Shot 2023-01-07 at 3 27 16 PM" src="https://user-images.githubusercontent.com/21006/211169210-cab4cee1-4a45-414c-a148-f1ff0ad4e79c.png">

**Comment by pdurbin** [comment]
Yesterday @siacus and I decided we'd try creating a new page at https://dataverse.org/team which I did and presented very briefly during the [community call](https://docs.google.com/document/d/1pU9FbyNAnLmOklWVpbzd9nZkAtkbn1SZ1sBE4jDsjf0/edit?usp=sharing).

As I said there, this is not at all final. Very preliminary. But I think it's better and more accurate than what we have. We can iterate on it, of course. Here's a screenshot:

![Screen Shot 2023-01-10 at 9 27 22 AM](https://user-images.githubusercontent.com/21006/211652416-52f6a6a6-2b7b-4098-87cc-38b3fce7e17c.png)

**Comment by lpiep** [comment]
Note that the link `http://www.iq.harvard.edu/people/people/data-science-products` now 404s.

**Comment by pdurbin** [comment]
@lpiep bleh. You're right. That's even worse.

@cmbz can we please prioritize this? You recently updated "The Team" at https://dataverse.org/about

![Screenshot 2023-10-16 at 21-33-06 About](https://github.com/IQSS/dataverse/assets/21006/4b7d3b88-ce3a-4459-a654-c96356173355)

**Comment by cmbz** [comment]
@pdurbin I don't understand exactly what action you want me to take here?

**Comment by pdurbin** [comment]
@cmbz I'm asking if we can put this issue in sprint ready.

**Comment by cmbz** [comment]
Ah, got it! I thought you wanted me to edit/update the website! :) Will do.
