### ISSUE TITLE
Feature Request/Idea:  Help with feature development

### ISSUE THREAD

**Issue by MarcosAnjos** [IQSS/dataverse#9270]
**Overview of the Feature Request**

I would like when a published dataset is reviewed by an organization's curation team. Display a baner on the initial screen of the dataset description.

**What kind of user is the feature intended for?**

This functionality will be from Curator. When the curator reviews a dataset, it displays a banner, informing which dataset was reviewed.

**What inspired the request?**

An internal discussion on best practices for organizing, managing and curating the data deposited in the repository

**What existing behavior do you want changed?**

At the moment it would be to add new functionality to the curator user type

**Any brand new behavior do you want to add to Dataverse?**

Every time user type curator reviews a dataset, add a banner stating that this dataset has been verified by the organization.

**Any related open or closed issues to this feature request?**

None

<hr>
Community could help me develop this functionality
<hr>

**How would you like to add this functionality**

![IMAGE](https://user-images.githubusercontent.com/32145970/211397825-ae7df18c-73f0-48d4-acc6-15c8f2251045.png)

**Comment by pdurbin** [comment]
@MarcosAnjos hi! I like the idea but I want to make sure I understand something.

Who would be able to see the "checked" label? Anyone? The public? Any anonymous user?

If instead the "checked" label is only for curators (who are logged in, of course), you might want to try the new-ish curation labels feature: https://guides.dataverse.org/en/5.12.1/installation/config.html#allowedcurationlabels

By the way, sometimes curators put a note that a dataset has been checked, like below (highlighted in red) from https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/GRVR99

![Screenshot 2023-01-10 at 15-44-21 Replication Data for Retaining Political Talent A Candidate-Centered Theory of Primary Adoption](https://user-images.githubusercontent.com/21006/211659741-fe54aab4-b775-4c52-8725-de4113492350.png)

**Comment by MarcosAnjos** [comment]
@pdurbin 
Hi, I sure do

**Who would be able to see the "checked" label? Anyone? The public? Any anonymous user?**

  _This markes label is visible to anyone accessing the repository._

**If instead the "checked" label is only for curators (who are logged in, of course), you might want to try the new-ish curation labels feature: https://guides.dataverse.org/en/5.12.1/installation/config.html#allowedcurationlabels**

  _WOW, cool this new dataverse feature, but it does't apply for our use case._

**By the way, sometimes curators put a note that a dataset has been checked, like below (highlighted in red) from https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/GRVR99**

_I like this use case about notes from a verified datasert. The inspiration would be the same woth a label visible to anyone._

But I will take this use case about the notes to the organization team.


thanks!!

**Comment by pdurbin** [comment]
@MarcosAnjos if I hover my mouse over "Checked" would I get a popup with more information? Or maybe a link to click? Otherwise, I'm concerned the word "Checked" might raise more questions than answers. 😄 Checked by whom? What was checked?

Also, are you thinking you'd create a pull request for this feature or are you simply suggesting it (which is fine, of course)?

**Comment by MarcosAnjos** [comment]
@pdurbin I was thinking about this subject. And the term check generated many doubts.

Yes, I would like to be closer to the dataverse code.

**Comment by pdurbin** [comment]
@MarcosAnjos to set up a dev environment: https://guides.dataverse.org/en/5.12.1/developers/dev-environment.html

If you need any help, https://chat.dataverse.org is a good place to ask questions! 😄
