### ISSUE TITLE
Create / Edit a Dataverse collection: weird UI bug when changing the email (saves correctly)

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#9278]
When creating or editing a Dataverse collection, if you go to change the email, this is what appear to happen:

You go to edit the email of a DV and then click save:
• it pops up to the top of the page (expected, in case there are errors)
• it replaces the new email with the old on the page (bug)
• it make take a while to save, but is working
• it then returns with the "success" message and the email is correctly changed

**Comment by pdurbin** [comment]
Bummer about this bug.

This operation is not possible via API. In terms of scope, rather thank simply fixing this in JSF, I'd like to propose that we also add an API for editing collections (not just the contact email but other fields). The React UI will need this.

**Comment by scolapasta** [comment]
Closing, as it wil be a non issue with the SPA.
