### ISSUE TITLE
In Files.java usr try-with-resources to for  JsonReader

### ISSUE THREAD

**Issue by mreekie** [IQSS/dataverse#9280]
In Files.java usr try-with-resources to for  JsonReader jsonReader = Json.createReader(new StringReader(jsonData)); in method updateFileMetadata

**Comment by qqmyers** [comment]
Better to use the methods in https://github.com/IQSS/dataverse/blob/f63f0e85bfb8f2e8526551b260744f17f2d99915/src/main/java/edu/harvard/iq/dataverse/util/json/JsonUtil.java#L61-L71 which already use try with resources. There's one to get a JSON object and one for an array.

**Comment by qqmyers** [comment]
Fixed in https://github.com/IQSS/dataverse/pull/9320.

**Comment by rtreacy** [comment]
I think it's a good idea to use the JsonUtil methods - however SonarQube also calls them out

**Comment by qqmyers** [comment]
Yes - #9315 shows that the JsonReader should be in the try-with-resources along with the StringReader.
