### ISSUE TITLE
In DataConverter.java use try-with-resources for convertedFileStream

### ISSUE THREAD

**Issue by rtreacy** [IQSS/dataverse#9281]
In DataConverter.java use try-with-resources for convertedFileStream = Channels.newInputStream((ReadableByteChannel) storageIO.openAuxChannel(formatRequested)); and convertedFileStream = new FileInputStream(formatConvertedFile); in method performFormatConversion(…)

**Comment by qqmyers** [comment]
I think this is a ~red-herring. Looking at the code, we open convertedFileStream in one of two ways and then embed that open stream in an InputStreamIO that is returned to the caller which is then charged with using and closing the stream. Using try-with-resources here would close the stream prematurely. Perhaps there is a larger refactoring that could be done, but as is the caller needs the open stream. I suggest we close this as won't fix (perhaps with a comment in the code - is there any way to indicate to SonarCube that it should not warn in this case?)

**Comment by mreekie** [comment]
Sprint planning:
- Gustavo is suggesting that this will need further discussion.  
- We should pull this off the sprint, and wait until Bob gets back.
- Bob is out and he'll be the one to look at this when he gets back.

**Comment by mreekie** [comment]
sprint review.
- removed size

**Comment by rtreacy** [comment]
Ok, I see what Jim is saying. 'Fixing' would cause another problem with closing stream prematurely. Would like to return to this though to see about refactoring because I'm not sure this doesn't result in a resource leak.

**Comment by rtreacy** [comment]
Won't fix with try-with-resources but we should return to this to consider refactoring the code

**Comment by qqmyers** [comment]
FWIW: It relies on the user to close the returned stream. Assuming we use try-with-resources where this is called, we should be OK. (I know there was lots of pre try-with-resources work to make sure close was in finally {} everywhere but those could/should be updated. Hopefully SonarQube will catch those?)
