### ISSUE TITLE
In TabularSubsetGenerator.java use try-with-resources for BufferedWriter

### ISSUE THREAD

**Issue by rtreacy** [IQSS/dataverse#9282]
- [x] In TabularSubsetGenerator.java use try-with-resources for BufferedWriter out = new BufferedWriter(new FileWriter(outfile)); in method subsetFile(...) 
- [ ] 
- [x] -- FileChannel fc = (FileChannel.open(Paths.get(rotatedImageFile.getAbsolutePath()), StandardOpenOption.READ)); in method subsetObjectVector(...) 
- [ ] 
- [x] --  BufferedInputStream rotfileStream = new BufferedInputStream(new FileInputStream(rotatedImageFile)); in method extract(...)  
- [ ] 
- [x] --- Scanner scanner = new Scanner(tabfileStream); in generateRotatedImage(...) 
- [ ] 
- [x] ---    BufferedOutputStream finalOut = new BufferedOutputStream(new FileOutputStream (new File(rotatedImageFileName))); in generateRotatedImage(...) 
- [ ] 
- [x] --- BufferedInputStream cachedIn = new BufferedInputStream(new FileInputStream(cachedTempFile)); in method generateRotatedImage(...) 
- [ ] 
- [x] ---BufferedInputStream rotfileStream = new BufferedInputStream(new FileInputStream(rotfile)); in reverseRotatedImage(...)

**Comment by qqmyers** [comment]
https://github.com/IQSS/dataverse/pull/9320

**Comment by rtreacy** [comment]
This issue calls for try-with-resource usage in several places in the code. Currently only one is added
