### ISSUE TITLE
Payara 6: resolve conflicts and look for next bug

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#9283]
Definition of done (stay within a size of 10 or a full day's work):

- Resolve merge conflicts in PR #9116.
- Poke around and look for next bug.
- If the bug seems small, create a PR into PR #9116 to fix it.
- If the bug seems large, create an issue and describe the bug well. Leave a comment in PR #9116 about the new issue.

**Comment by poikilotherm** [comment]
I just merged `develop` into the feature branch and also updated to Payara 6.2022.2 in parent POM.

**Comment by pdurbin** [comment]
@poikilotherm thanks!! We just discussed this at standup and it sounds like @donsizemore is going to try to get the branch up on a server. Thanks, Don! 🎉

**Comment by pdurbin** [comment]
First, there are already merge conflicts again (the sooner we move to Payara 6 the better):

- #9116

Second, @scolapasta suggested I could poke around and look for bugs. Some far I found this problem publishing a dataset

- #9323

**Comment by mreekie** [comment]
This issue has served it's purpose.
We can close it now.
The bugs listed above take it's place as intended.
