### ISSUE TITLE
Error when merging two accounts with same group

### ISSUE THREAD

**Issue by sirineREKIK** [IQSS/dataverse#9284]
Hello,

When we try to merge two accounts belonging to the same group, an error is reported: 
(  ERROR: duplicate key value violates unique constraint \"explicitgroup_authenticateduser_pkey\"\\n  Detail: Key (explicitgroup_id, containedauthenticatedusers_id)=(16, 72) already exists.)

Is that the expected behavior or it is a Dataverse bug please?

Sirine

**Comment by pdurbin** [comment]
@sirineREKIK yikes! That certainly does sound like a bug. Thanks for letting us know!
