### ISSUE TITLE
Disable Homepage?

### ISSUE THREAD

**Issue by TanayKarve** [IQSS/dataverse#9289]
What's the way to disable the dataverse homepage?
I want to restrict unauthenticated users from viewing the dataverses present.
I remember I did this before, but after resetting the installation, I can't find that setting/API again.
Can someone point me towards it?
Thanks.

**Comment by pdurbin** [comment]
@TanayKarve I'm not sure what you mean.

You can disable the default homepage by setting up a custom home page: https://guides.dataverse.org/en/5.12.1/installation/config.html#custom-homepage

You could leave collections as drafts if you don't want them to be seen.

Should this question and answer go in the guides? Where would you look for it? 😄

**Comment by pdurbin** [comment]
Right, not possible. Sorry. You've got me curious what you did last time, though! 😄 

Sometimes people do ask for this sort of feature. Generally we tell them to leave collections and datasets unpublished (in draft) if they don't want them to be seen by unauthenticated users.

**Comment by TanayKarve** [comment]
Hmm I see.
Anyways, for someone who wants to achieve this:
1. Have the following in custom-homepage.html.
`<script>
    window.location.href = "https://dataplanet.ucsd.edu/loginpage.xhtml?redirectPage=%2Fdataverse.xhtml";
</script>`
2. Follow [these](https://dataplanet.ucsd.edu/dataverse/root) steps to put a custom homepage.
This essentially doesn't let unauthenticated users view dataverses.

_However there's a catch: just by putting '/dataverses/root' in the URL, anyone can view dataverses without being logged in._

**Comment by pdurbin** [comment]
@TanayKarve the other catch is that published collections (and a listing of their contents) are available via API without authentication. For example:

- https://dataverse.harvard.edu/api/dataverses/open-source-at-harvard
- https://dataverse.harvard.edu/api/dataverses/open-source-at-harvard/contents
