### ISSUE TITLE
Translate hard coded text - My Data page

### ISSUE THREAD

**Issue by josekarvalho** [IQSS/dataverse#9292]
**What steps does it take to reproduce the issue?**
When going to My Data menu on a user without any permissions (just registered).

* When does this issue occur?
Always

* Which page(s) does it occurs on?
/dataverseuser.xhtml?selectTab=dataRelatedToMe

* What happens?
No possible translation of alert text: (Sorry, nothing was found for these roles:)

* To whom does it occur (all users, curators, superusers)?
registered users

* What did you expect to happen?
make strings available to translate that message

**Which version of Dataverse are you using?**
5.12.1

**Any related open or closed issues to this bug report?**
Didn't find any

**Screenshots:**
![Screenshot from 2023-01-17 12-02-40](https://user-images.githubusercontent.com/1966160/212894801-5ff5917f-adb6-4fc2-af36-8a990bba09bd.png)

**Comment by pdurbin** [comment]
@josekarvalho thanks for the bug report!

> Sorry, nothing was found for these roles

Here's the hard-coded English for the message above...

https://github.com/IQSS/dataverse/blob/v5.12.1/src/main/java/edu/harvard/iq/dataverse/mydata/MyDataFinder.java#L439

... but there are other hard-coded values.

@josekarvalho if you're not aware, we plan to rewrite the front end of Dataverse: https://dataverse.org/blog/restructuring-dataverse-ui-single-page-application

... so it might make sense to defer working on this. That said, if someone wants to make a pull request, please go ahead!
