### ISSUE TITLE
reduce number of steps before "going live" steps in Installation Guide 

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#9295]
I introduced the "Going Live" steps in the installation guide in 4.6.2: https://guides.dataverse.org/en/4.6.2/installation/config.html#going-live-launching-your-production-deployment

Here's how the guides looked back then

![Screenshot 2023-01-17 at 13-46-08 Configuration — Dataverse org](https://user-images.githubusercontent.com/21006/212985963-4aca282b-3ca5-4594-8cca-701dec2dc7ee.png)

Fast forward to today (including #8915 which isn't yet merged) and the list of steps before going live is quite long:

![Screenshot 2023-01-17 at 13-45-55 Configuration — Dataverse org](https://user-images.githubusercontent.com/21006/212986127-4dcaa405-95da-42fd-8343-f0407a30996d.png)

I'm concerned that people installing Dataverse will be intimidated by this long list. We should reorganize the Installation Guide a bit (let's say timeboxed to size of 10 or a full day) to put non-essential config elsewhere.

Candidates to move elsewhere:

- Database Persistence (the default works well enough, this could go under "advanced" perhaps)
- BagIt File Handler
- BagIt Export

I'm also open to other ideas but I hope I've captured the problem: a very long list to grok.

Or as @poikilotherm put it in [a talk](http://talks.bertuch.name/mpconfig-20210223/#/1/0/1):

![meme-so-many](https://user-images.githubusercontent.com/21006/213183369-cd7d04c1-15d1-41f0-8502-81a96781698a.jpg)

**Comment by poikilotherm** [comment]
A few thoughts:

- Maybe it's time to move all configuration things into ONE configuration guide with subpages for the different topics? 
- Maybe we can adapt something like https://documentation.divio.com/ to enhance our docs?
- We definitely should create custom roles for all of our settings on the different subpages, so we can create an index of them for quick referencing!

**Comment by kuhlaid** [comment]
I would leave the install guide alone. Anyone looking at the prerequisites list will be intimidated regardless of anything else, much less getting to the 'going live' part. Speaking for myself, as someone who has yet to successfully install Dataverse, getting a containerized build script to handle the install would be ideal to simplify things and aid in adoption of the software. The fact that Dataverse seems to be exclusively developed using a non-containerized RedHat environment is a major barrier to 'simplifying' the install process.

I will revisit the Docker script I was working on with Windows 10 since I upgraded to Windows 11, which 'supposedly' has the systemd support needed in Windows Subsystem for Linux to possibly run the Dataverse from Docker scripts. Manually installing software requirements to manually setup a development environment seems like an ancient idea in our age of containers and virtualization.

**Comment by pdurbin** [comment]
Wow, the list is even longer now, especially with all the PID settings from PR #10234:

![Screenshot 2024-03-22 at 11-31-27 Configuration — Dataverse org](https://github.com/IQSS/dataverse/assets/21006/9475a55e-b307-43c2-8cb4-f453f143c0fe)

**Comment by pdurbin** [comment]
@poikilotherm @kuhlaid thanks for your feedback.

I still want to simplify this list somehow but we can create a fresh issue when we're ready to work on it. Closing.

**Comment by donsizemore** [comment]
> I would leave the install guide alone. Anyone looking at the prerequisites list will be intimidated regardless of anything else, much less getting to the 'going live' part. Speaking for myself, as someone who has yet to successfully install Dataverse, getting a containerized build script to handle the install would be ideal to simplify things and aid in adoption of the software. The fact that Dataverse seems to be exclusively developed using a non-containerized RedHat environment is a major barrier to 'simplifying' the install process.
> 
> I will revisit the Docker script I was working on with Windows 10 since I upgraded to Windows 11, which 'supposedly' has the systemd support needed in Windows Subsystem for Linux to possibly run the Dataverse from Docker scripts. Manually installing software requirements to manually setup a development environment seems like an ancient idea in our age of containers and virtualization.

@kuhlaid historically IQSS used NetBeans on Mac OS; most containerized solutions I've seen have used Ubuntu under the hood. Realistically Dataverse will run on any operating system which can run Java 17 and Postgres; whether services are launched by systemd or init.d or entrypoint scripts are dependent on the underlying platform.
