### ISSUE TITLE
[in progress] Update to documentation tables to convert inline tables to CSV generated tables

### ISSUE THREAD

**Issue by kuhlaid** [IQSS/dataverse#9307]
Going through the documentation, there are pages such as `\doc\sphinx-guides\source\admin\metadatacustomization.rst` which have inline tables. This makes me cringe. I cannot think of any reason why we should have tables created this way. The CSV generated tables on page `\doc\sphinx-guides\source\api\external-tools.rst` are much easier to update and does not clutter the .rst file.  It is a nightmare to make updates to inline tables and might be a reason why the generated PDF of the documentation cuts off the large table `\doc\sphinx-guides\source\admin\metadatacustomization.rst` on one page and does not extend to a second page (I plan to look into this issue while converting the tables to CSV generated to see if that corrects the PDF problem). 

If there are some obscure reasons why inline tables should exist in the documentation let me know, but I will begin converting the documentation currently using inline, over to CSV tables.

**Comment by pdurbin** [comment]
@kuhlaid I'm the one who added the CSV/TSV style table for external tools and I like for some things but there's also a third way. Check out this PR by @poikilotherm

- #9299

It has a table that looks like this:

```
Feature Flags
-------------

Certain features might be deactivated because they are experimental and/or opt-in previews. If you want to enable these,
please find all known feature flags below. Any of these flags can be activated using a boolean value
(case-insensitive, one of "true", "1", "YES", "Y", "ON") for the setting.

.. list-table::
    :widths: 35 50 15
    :header-rows: 1
    :align: left

    * - Flag Name
      - Description
      - Default status
    * - Example flag
      - Replace this with something real
      - ``Off``

**Note:** Can be set via any `supported MicroProfile Config API source`_, e.g. the environment variable
``DATAVERSE_FEATURE_XXX``.
```

Just another option to play with and consider! 😄

**Comment by kuhlaid** [comment]
Suggestions made.
