### ISSUE TITLE
Allow deletion of saved searches

### ISSUE THREAD

**Issue by philippconzett** [IQSS/dataverse#9317]
**Overview of the Feature Request**
Dataset links between collection within a Dataverse installation can be removed using this API call:

> curl -H "X-Dataverse-key: $API_TOKEN" -X DELETE http://$SERVER/api/dataverses/$linked-dataverse-alias/deleteLink/$linking-dataverse-alias

However, the links will still appear again since the saved searches will be re-established weekly.
To remove links permanently, we need a DELETE endpoint for saved searches.

**What kind of user is the feature intended for?**
API User

**What inspired the request?**
A long-lasting issue we have been having at DataverseNO; see this [discussion thread](https://groups.google.com/g/dataverse-community/c/dFyT4MrVkZY/m/Md1F5K8LAQAJ) in the Dataverse Google group.

**What existing behavior do you want changed?**
Dataset links between sub-collections within a Dataverse installation being re-established after unlinking.

**Any brand new behavior do you want to add to Dataverse?**
No.

**Any related open or closed issues to this feature request?**
[#1364](https://github.com/IQSS/dataverse/issues/1364). See also @pdurbin's comment in the mentioned discussion thread:

> From a quick look at the code, it seems that the ability to delete saved searches was stubbed out but never implemented: https://github.com/IQSS/dataverse/blob/v5.12.1/src/main/java/edu/harvard/iq/dataverse/api/SavedSearches.java#L174
> 
> The docs you found explain the thinking back then:
> 
> "There is a known issue (#1364) that once a link to a Dataverse collection or dataset is created, it cannot be removed (apart from database manipulation and reindexing) which is why a DELETE endpoint for saved searches is neither documented nor functional"
> 
> These days, as you know, deleting links is supported, so it's probably time to make that "delete saved search" API endpoint real.

**Comment by luddaniel** [comment]
@pdurbin @philippconzett Do you think that we need to remove links created by the saved search while removing a saved search ? This means, making sure that we don't remove links that would be created by another saved search.
Otherwise, links to datasets and dataverses would need to be removed by hand...

**Comment by pdurbin** [comment]
I'm curious what @philippconzett thinks but yes, I think it would be nice if deleting a saved search automatically deleted any links created by that saved search. However, as you point out, it could be tricky to determine how the link was created, by a saved search or not.

We do have the ability to delete links now, thanks to #4543. We call this "unlinking": https://guides.dataverse.org/en/6.1/admin/dataverses-datasets.html#unlink-a-dataset

**Comment by philippconzett** [comment]
Thanks. I'm not sure. The most important thing for us is that the new feature will allow us to permanently delete any linking between datasets and collections. Will the delete saved searches be an API command similar to the one I now need to run each Sunday (= curl -H "X-Dataverse-key: $API_TOKEN" -X DELETE http://$SERVER/api/datasets/$linked-dataset-id/deleteLink/$linking-dataverse-alias)?

**Comment by pdurbin** [comment]
@luddaniel created a pull request:

- #10198

Thanks!
