### ISSUE TITLE
Payara 6: Can't publish some datasets

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#9323]
On the Payara 6 server I came upon an existing dataset in the root and tried to publish it. It failed in a strange way.

![Screen Shot 2023-01-25 at 11 50 06 AM](https://user-images.githubusercontent.com/21006/214626726-5f3bb446-b67f-44e1-9063-a6f248302c59.png)
![Screen Shot 2023-01-25 at 11 50 13 AM](https://user-images.githubusercontent.com/21006/214626722-dcbfc8c5-f8cc-4b63-9ecb-af254915f687.png)
![Screen Shot 2023-01-25 at 11 50 18 AM](https://user-images.githubusercontent.com/21006/214626727-f7f522b8-b5aa-4d6e-b38d-84b11a572dd0.png)
![Screen Shot 2023-01-25 at 11 50 59 AM](https://user-images.githubusercontent.com/21006/214626729-76e38024-1a77-4a14-9608-cc362bac6559.png)

(here I clicked refresh)

![Screen Shot 2023-01-25 at 11 51 31 AM](https://user-images.githubusercontent.com/21006/214626737-574ae3b6-21ec-474d-a941-a972717ea2d2.png)

**Comment by pdurbin** [comment]
If it helps, related notifications (included a different dataset that I created that I was able to publish):

![Screen Shot 2023-01-25 at 12 17 08 PM](https://user-images.githubusercontent.com/21006/214634411-94f5af0c-9ec8-4e11-ab24-4d400ea72bf3.png)

**Comment by donsizemore** [comment]
Looks like we need to fix siteUrl.

**Comment by pdurbin** [comment]
@donsizemore maybe. I was able to publish a dataset I created myself ("test1" in the screenshot above).

As I said during the sprint kickoff today, I wouldn't be surprised if a develop has trouble reproducing this locally. But I duly reported it anyway.

**Comment by pdurbin** [comment]
Let's re-verify on Don's server. Time box it to 3.

**Comment by cmbz** [comment]
Currently blocked because there is not an existing known-good Payara 6 branch 
Moving to Sprint Ready
Phil will create a related issue indicating the need to produce a good branch

**Comment by pdurbin** [comment]
I'm pretty sure this will be very difficult to reproduce. Again, as mentioned above, on the same server I was later able to publish a dataset. Closing.
