### ISSUE TITLE
Payara 6: dataverseAdmin is not a superuser

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#9324]
The text is not red. No dashboard link:

![Screen Shot 2023-01-25 at 12 02 58 PM](https://user-images.githubusercontent.com/21006/214630955-50b7d41c-5d19-40b4-a917-3e8f519861e9.png)

**Comment by donsizemore** [comment]
@pdurbin I'm not sure why it wasn't, but in the mean time I've set:

```
[dls@payara6 ~]$ curl -X POST http://localhost:8080/api/admin/superuser/dataverseAdmin
{"status":"OK","data":{"message":"User @dataverseAdmin set as a superuser."}}
```

Multiple installer runs happened on that box; without looking I'd say it was an even number, affecting the toggle.

**Comment by pdurbin** [comment]
@donsizemore thanks! Fixed now. Closing.

Note to self, I agree with @landreev that we should have an API to set superuser status rather than toggle it: https://github.com/IQSS/dataverse/issues/3612#issuecomment-307170234
