### ISSUE TITLE
Description metadata field: Description field text should wrap and not run off the page

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#9325]
Bug can be viewed on SAEF data collection in production

**What steps does it take to reproduce the issue?**

Enter a certain amount of text in the description metadata field of a dataset

* When does this issue occur?
On publishing with a certain amount of text in description field

* Which page(s) does it occurs on?
dataset  landing page

* What happens?
text runs off the page

* To whom does it occur (all users, curators, superusers)?
curatore

* What did you expect to happen?

text should wrap

**Which version of Dataverse are you using?**

most recent

**Any related open or closed issues to this bug report?**

file tags metadata field has same issues

**Screenshots:**

*
![Screen Shot 2023-01-25 at 12 05 57 PM](https://user-images.githubusercontent.com/8322346/214631963-30ddaed0-cfb8-43ab-b3c7-6b386b4817d0.png)

**Comment by mreekie** [comment]
sprint prep
- needed for 5.13. moved over

**Comment by pdurbin** [comment]
Closing.

This was closed by this PR:

- #9336

The description didn't have "closes" in it so, it didn't happen automatically.
