### ISSUE TITLE
during password reset, users asked to accept term but there is no checkbox

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#9326]
When resetting their password users see "Please, accept the new terms of use before continuing."

However, there is no checkbox:

![Screen Shot 2023-01-25 at 12 14 04 PM](https://user-images.githubusercontent.com/21006/214633492-5315e9ab-93a4-473e-9902-7e9a47bf0619.png)

Tested on the Payara server. Not sure if it's an issue in 5.12.1 or develop.

**Comment by pdurbin** [comment]
I just wanted to add that the proper fix is probably to simply remove "Please, accept the new terms of use before continuing."

That is, there's no need to add a checkbox. It wasn't there before. It reminds me of how term stuff now also pops up when password are reencrypted with a new algorithm. Here's a screenshot from https://github.com/IQSS/dataverse-security/issues/29

![209150377-ed0d8cb2-e8f5-4b47-bf30-3c76e225dc0e](https://user-images.githubusercontent.com/21006/214742937-e7f35cb9-11c3-46cd-81ba-994c3f3e2e17.png)

Again, just removing the message about terms should be the fix. I'll give this a 3. And whoever picks it up should try to reproduce it in develop first, of course. My money is on it being a bug there and not specific to Payara 6.

**Comment by qqmyers** [comment]
FWIW: I can confirm that this is not Payara6 specific - it happens now at dataverse.harvard.edu.

**Comment by cmbz** [comment]
Removed Payara 6 label because the issue occurs in current branches, too.

**Comment by pdurbin** [comment]
Another possibility would be to remove the message altogether, yes.

**Comment by jggautier** [comment]
Looks like the PR that's in the code review column now (https://github.com/IQSS/dataverse/pull/9652) edits the message instead of removing it. I suspect removing it like @pdurbin [wrote earlier](https://github.com/IQSS/dataverse/issues/9326#issuecomment-1404484457) would be better but maybe that can be reviewed after the move to the SPA.
