### ISSUE TITLE
Inconsistent behavior relating to Roles

### ISSUE THREAD

**Issue by pkiraly** [IQSS/dataverse#9338]
**What steps does it take to reproduce the issue?**

I found that the API and the web UI is not working similarly. I tested it in Dataverse v5.11.1. Here is a summary:

If I create new role ("reviewer") for the root dataverse, it is displayed only in the root's roles list. It is not displayed other dataverse' role list, and I can not create another role with the same machine name elsewhere.

Displaying a newly created role in the list of roles:

web:
- root dataverse: it is shown
- elsewhere: it is not shown

API:
- root dataverse: it is shown
- elsewhere: it is not shown

Assign role to user/group:

web:
- root dataverse: possible
- elsewhere: I can not assign the same rule in another dataverse, because it is not displayed among the selectable roles
API:
- root dataverse: possible
- elsewhere: possible

Checking the list of Users/Groups (assignments).

web:
- root dataverse: the assignment is shown in the list
- elsewhere: it doesn't.
API:
- root dataverse: the assignment is shown in the list
- elsewhere: the assignment is shown in the list

I haven't found an explanation in the Dataverse guide.

- Do you know if this inconvenience is by design? or it is rather a bug?
- What would be your expectation regarding to newly created roles (those which is not packed in a freshly installed Dataverse)? Mine would be that if I create a new role in the root, it is visible and usable elsewhere in both the web UI and API, but maybe you have different opinion.

* When does this issue occur?
see above

* Which page(s) does it occurs on?
the Permission page

* What happens?
see above

* To whom does it occur (all users, curators, superusers)?
superusers, dataverse admins

* What did you expect to happen?
see above

**Which version of Dataverse are you using?**
v5.11.1

**Any related open or closed issues to this bug report?**
I am not aware of.

**Screenshots:**

No matter the issue, screenshots are always welcome.

To add a screenshot, please use one of the following formats and/or methods described here:

* https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests
*

**Comment by landreev** [comment]
> What would be your expectation regarding to newly created roles (those which is not packed in a freshly installed Dataverse)? Mine would be that if I create a new role in the root, it is visible and usable elsewhere in both the web UI and API, but maybe you have different opinion.

We agree in that the roles should be inherited from the direct ancestor dataverses. 
Working on it.

**Comment by landreev** [comment]
One other difference in how the roles are listed in the UI vs the API: the page show all the available roles, the builtin + the defined ones. The `/api/dataverses/*/roles` api only shows the defined kind. There's probably no reason for it not to show all the *available* roles, just like the page, is there? 
As of now, we have separate apis for the builtin and defined roles. But the former is under `/api/admin`, so it's not available to regular curator users.
