### ISSUE TITLE
Ability to Set a Dataset Availability Schedule

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#934]
We have a request from a user (see IRC log: http://irclog.iq.harvard.edu/dataverse/2014-09-24) to support the ability to make a dataset's _files_ publicly available for a certain period of time (start and end date), and then _restrict access to the files but keep the metadata public_. This is related to Issue #343 which will allow for a user to set an embargo period date (when to make a dataset go from unpublished or restricted to published and available) but deserves a separate ticket since this feature is about how long a dataset's files should be made publicly available.

**Comment by pdurbin** [comment]
If anyone is curious why this issue was closed, please see https://github.com/IQSS/dataverse/issues/4052#issuecomment-348826619
