### ISSUE TITLE
Editing a deaccessioned dataset: the file edit options should allow the "delete" function to work

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#9351]
**What steps does it take to reproduce the issue?**
From a deaccessioned version, any file-related action (deleting, restricting files, adding tags, etc), results in error banners and confusing success banners to appear and doesn't cause a draft version to be created

Visit a deaccessioned dataset to edit for republishing. login, and select file, delete files

select files and select the delete option, or any other option

* When does this issue occur?

When you attempt to revive/edit a deaccessioned dataset for republishing

* Which page(s) does it occurs on?

Dataset landing page

* What happens?
* 
Error message that files can't be deleted/etc

* To whom does it occur (all users, curators, superusers)?

curators, superusers

* What did you expect to happen?
expected file actions to work and create new draft

**Which version of Dataverse are you using?**

latest release 5.13

**Any related open or closed issues to this bug report?**

none

**Screenshots:**

No matter the issue, screenshots are always welcome.

To add a screenshot, please use one of the following formats and/or methods described here:

* https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests
*

**Comment by cmbz** [comment]
2024/07/10
- Sized at 3, will resize if it turns out not to be an easy fix.

**Comment by jp-tosca** [comment]
I can confirm this happens on deaccessioned datasets, while a solution is ready a quick way around is adding a file will create a draft version and will let it to be updated, this error happens when a file or any operation on the files is done on a deaccessioned dataset.

**Comment by jp-tosca** [comment]
The Id of the dataset is coming as null when it is retrieved from a deaccessioned Dataset in : https://github.com/IQSS/dataverse/blob/c59746d2176f1d8a7e1b567f12143175281e094a/src/main/java/edu/harvard/iq/dataverse/engine/command/impl/UpdateDatasetVersionCommand.java#L117

**Comment by qqmyers** [comment]
I think that makes sense - a draft version has just been created and is not yet in the db so has no id. The next line would retrieve the deaccessioned version when id is null.

**Comment by jp-tosca** [comment]
Thanks for the info @qqmyers!

**Comment by jp-tosca** [comment]
This should be solved by #10901 @sbarbosadataverse, thanks for opening the issue!

**Comment by pdurbin** [comment]
@sbarbosadataverse you could test on https://beta.dataverse.org if you like.
