### ISSUE TITLE
Feature Request/Idea: File PID at deposit time rather than publication

### ISSUE THREAD

**Issue by DS-INRA** [IQSS/dataverse#9352]
**Overview of the Feature Request**
As a user,
I can receive a reserved PID for my files when I deposit them rather than only when the host dataset is published 

**What kind of user is the feature intended for?**
API and UI depositors

**What inspired the request?**
A user request from researchers who keep a reference to the files in an external graph knowledge base so that it can be identified with the advantages of a pid.

**What existing behavior do you want changed?**
Maybe this should be optionnal if there was a specific need form the community addressed by the current workflow.

**Any related open or closed issues to this feature request?**
Maybe wait for  #9272 to be closed so that it does not create additional unecessary file DOIs

**Comment by pdurbin** [comment]
@DS-INRA hi! Thanks for creating this issue.

I believe this pull request from @qqmyers will help:

- #7334 

It closes this issue:

- #7068

Can you please take a look? Thanks!

**Comment by DS-INRA** [comment]
Thank you I somehow missed the issue and PR, I'll close this issue as duplicate, if there is additional discusion it will be in the first issue :)
