### ISSUE TITLE
Add execution rate metering to the command engine

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#9356]
The proposed idea is to modify the command engine as to make it possible to keep accurate counts of executed commands per specific time intervals. We would want to count the totals for all commands, as well as specific commands (and, possibly, classes of commands?) as well as the counts and rates for individual users. 
 
Note that this can be achieved without adding any new data structures (the values can be obtained by counting the entries in the ActionLogRecord table). However, that table is quite unwieldy on any busy installation, so we almost certainly want to add some efficient way of caching and updating the counts in the database. 

Then we want to add a system of configurable rate limits for specific commands, in a way that would allow setting different limits for different users/groups of users, etc. 
In addition to limits by the number of executed commands - for example, "certain number of  UpdateDatasetVersionCommand per minute allowed for an otherwise unprivileged logged-in user" - Action Log records how much time it took to execute each command as well. So we may want to consider limiting use by that measure too (?). For example, if a specific user keeps making edits, but for whatever reason the UpdateDatasetVersionCommand on their dataset is especially cpu- and time-consuming - maybe that could trigger some red flags too. 

A simplest use of this functionality would be to set a rate limit on, say, Get*Version commands for the anonymous (guest) users, and that would address a somewhat common case of a scripted crawler plowing through our holdings; past a certain call in too short a period of time the API starts giving them "too busy, try again later". 

More care will need to be taken to make our pages communicate this "try again later" message to the UI users. We don't want anyone to lose a page-worth of edited metadata they are trying to save, etc.

**Comment by poikilotherm** [comment]
How about Microprofile Metrics?

**Comment by landreev** [comment]
(This was opened as a followup to a meeting with @siacus and @scolapasta, and as part of the "rate limiting logic" spike).

**Comment by landreev** [comment]
There's some interesting information in that ActionLogRecord table.

**Comment by landreev** [comment]
Once again, let's be careful about interpreting these numbers. They do NOT by any means indicate that it doesn't cost us much to serve read-only content to anonymous users. Again, these are only the command. There's plenty of evidence that the search API/solr becomes the performance bottleneck during aggressive robot crawls, and none of that heavy lifting goes through the command engine and gets recorded there.

**Comment by pdurbin** [comment]
Unclear what the objective is. Work on design. 80. Some actual coding can certainly happen. We can add an outline.

**Comment by cmbz** [comment]
2023/09/13: Note, this issue is paired with another: https://github.com/IQSS/dataverse/pull/9409.

**Comment by stevenwinship** [comment]
If I understand this correctly there are two asks here.
First ask is to aggregate the data from the Action Log table into an aggregated table with a set time interval (1 hour). This could be code triggered by a cron job a few times a day. The aggregated data can be grouped/filtered by user and command. This data can then be used for various queries to report on metrics by user, command, or groups of commands. I do not know who needs this or how this will be used.

Second ask is for rate limiting. This feature does not need the metrics/aggregated data from the first task. This would only need to cache the command api calls, possibly using bucket4j or setting up a global redis cache. It would be nice to know if other cacheing or rate limiting will be needed in the future to help decide which caching system to use.

**Comment by cmbz** [comment]
2024/01/03: Resized during kickoff
