### ISSUE TITLE
Everything but publishing Role

### ISSUE THREAD

**Issue by joelfan** [IQSS/dataverse#9358]
**Overview of the Feature Request**
We would like to have a workflow where all data and metadata is managed by our researchers, while publishing is managed by dedicated people. We would like to have **roles** where anything (including granting permissions, but not admin ones) on the sub-tree is permitted **but publishing**. We want **curators** to **publish**.

We saw that the **contributor** role is close to what we want to get, but it cannot completely manage its dataverse collection sub-tree. 

**What kind of user is the feature intended for?**
Curators, Admins. 

**What inspired the request?**
An effective workflow where the publishing is performed after curators' review.

**What existing behavior do you want changed?**
We would like to have a global role where anything (including granting permissions, but not admin ones) on the sub-tree is permitted **but publishing**. We want **curators** to **publish**.
We tried to define it, but we cannot understand completely dataverse behaviour. See [here](https://groups.google.com/g/dataverse-community/c/2M9A7uo4KpM/m/zVcoQKt3AAAJ)  and  [here](https://groups.google.com/g/dataverse-community/c/5bZqCRFP8BU). 

**Any brand new behavior do you want to add to Dataverse?**
None. Just one role. 

**Any related open or closed issues to this feature request?**
None. Just to implement a new workflow.

**Comment by scolapasta** [comment]
Note that the issue with this is that if a user have the permission to grant roles, then they can give themselves a role that allows them to publish!

**Comment by poikilotherm** [comment]
This reminds me about my idea here https://github.com/IQSS/dataverse/issues/7252#issuecomment-952648161 to avoid this privilege escalation.

Back in the day it seems like @BPeuch's request was satisfied by the new split of file permissions, but maybe this usecase here demonstrates the need for such an extension?

**Comment by joelfan** [comment]
I agree with both of you. 
The role should be "all but publish" but without enabling the role itself to grant publish capablities (admin or curator).
The privilege escalation should be forbidden.

**Comment by meghangoodchild** [comment]
Please see also: https://github.com/IQSS/dataverse/issues/9190
And the related thread: https://groups.google.com/g/dataverse-community/c/4VM49qUqMGo/m/_HhjaJtwBAA

**Comment by pdurbin** [comment]
Related:

- #9938

**Comment by DS-INRA** [comment]
Is there a dedicated issue to address the priviledge escalation ? I think @poikilotherm idea of a limitation would be great in itself even if it does not exactly solve this specific use case.

**Comment by poikilotherm** [comment]
The way I see it, this issue is ideal to server as it. It sounded like it would solve the request by @joelfan. Maybe we can adapt the title a little. WDYT @pdurbin ?

**Comment by pdurbin** [comment]
Sure, but maybe we should break off into a design doc to make sure we're considering all the important angles. GitHub comments can be a bit scattered and hard to follow. 😅

**Comment by pdurbin** [comment]
@joelfan it's good suggestion but not one we're actively thinking about. Permissions are a bit tricky.
