### ISSUE TITLE
Some questions on Filling in Metadata fields, dataset DOI, and exporting metadata.

### ISSUE THREAD

**Issue by diego-guillen** [IQSS/dataverse#9362]
Hi IQSS Dataverse team, 

In this opportunity I have a few technical questions.

Q1 -  We noticed that when creating a Dataset, we cannot save it if the compulsory metadata fields are not filled in. Is it possible to change some settings so that the Dataset could be saved even if the metadata fields are not fully complete? 

 The reason for this, is that we’re creating a customized Metadata template, which is long and takes time to fill. Users would probably prefer to save the dataset draft first, and then come back and fill in the metadata information later.

Q2a – Is the Datacite DOI prefix that we associate the Dataverse installation with, one per installation? 
If we host datasets from several universities, are we limited to produce datasets with only one common DOI prefix? 

Q2b - Would we need to install several IQSS Dataverse applications (on various VMs) if we wanted to have separate DOI prefixes, one for each customer?

 Q2c – A DOI is generated automatically when we create a Dataset. Can we change the DOI to one preferred by each customer? Suppose we are hosting dataset collections for G-uni at Q-uni, but G-uni wants to use its own DOI prefix, not Q’s.

Q3 – Once the dataset is published, I noticed there are several options to export the metadata in various formats (Datacite, JSON, etc)  How can we customize an option that will allow us to export metadata from our own template?  I noticed that the JSON option lists all the metadata fields from our template. Is it possible to code/extend that feature to produce a different JSON export? 

Our experience so far, is that Dataverse seems to be a closed system, so it is cumbersome to extend it.

Thank you, in anticipation , for your kind help.

_Originally posted by @diego-guillen in https://github.com/IQSS/dataverse/issues/3148#issuecomment-1415181246_

**Comment by pdurbin** [comment]
> Q1 - We noticed that when creating a Dataset, we cannot save it if the compulsory metadata fields are not filled in. Is it possible to change some settings so that the Dataset could be saved even if the metadata fields are not fully complete?
> 
> The reason for this, is that we’re creating a customized Metadata template, which is long and takes time to fill. Users would probably prefer to save the dataset draft first, and then come back and fill in the metadata information later.

@diego-guillen hi! for this one, please see:

- #8940
- #8822
- https://harvard.zoom.us/rec/share/EZGLPBLPv3o74H_WD-ejp34c3Grro1Jk8mS5L8um9PyFbKzVr2Ro_62gqIkckKf5.1Fh8UfNOIkc8sqpc

**Comment by pdurbin** [comment]
> Q2a – Is the Datacite DOI prefix that we associate the Dataverse installation with, one per installation?
> If we host datasets from several universities, are we limited to produce datasets with only one common DOI prefix?

@diego-guillen yes, one DOI prefix ("authority") per installation. And yes, several universities in the same installation would share this prefix.

In the future, more flexibility might be possible. Please see "This PR takes significant steps toward making PID Providers plugable and allowing multiple DOI accounts to manage different authority/shoulder combinations" here:

- #8674

**Comment by pdurbin** [comment]
> Q3 – Once the dataset is published, I noticed there are several options to export the metadata in various formats (Datacite, JSON, etc) How can we customize an option that will allow us to export metadata from our own template? I noticed that the JSON option lists all the metadata fields from our template. Is it possible to code/extend that feature to produce a different JSON export?

@diego-guillen We are thinking hard about modularity right now, including in exports specifically. @qqmyers make a proof on concept PR here to demonstrate a path toward making exporters pluggable:

- #9175

We have a modularity doc almost ready to share with the community, but for now, please read the doc referenced in this blog post: https://dataverse.org/blog/restructuring-dataverse-ui-single-page-application

Feedback is welcome, of course!

> Our experience so far, is that Dataverse seems to be a closed system, so it is cumbersome to extend it.

I hope that the doc above helps convince you that we're trying. 😅 I'd like to use the modularity doc as a basis for a new page in the guides called something like "how to extend Dataverse" to explain what's possible now. That doc also attempts to explain our ideas for the future.

Thanks for your questions here. What is the "definition of done" for this issue? Would more documentation help? Are you interested in making a pull request to improve the documentation? 😄

**Comment by diego-guillen** [comment]
Thanks Philip, for your kind and prompt answers.

I think you can close the ticket now. I’ll try to read through the resources (links) that you gave me.
A separation of front-end and back-end applications is welcome, and it’s definitely a better approach than the current monolith.

Many thanks.


From: Philip Durbin ***@***.***>
Date: Thursday, 9 February 2023 at 9:33 am
To: IQSS/dataverse ***@***.***>
Cc: Diego Guillen ***@***.***>, Mention ***@***.***>
Subject: Re: [IQSS/dataverse] Some questions on Filling in Metadata fields, dataset DOI, and exporting metadata. (Issue #9362)

Q3 – Once the dataset is published, I noticed there are several options to export the metadata in various formats (Datacite, JSON, etc) How can we customize an option that will allow us to export metadata from our own template? I noticed that the JSON option lists all the metadata fields from our template. Is it possible to code/extend that feature to produce a different JSON export?

@diego-guillen<https://github.com/diego-guillen> We are thinking hard about modularity right now, including in exports specifically. @qqmyers<https://github.com/qqmyers> make a proof on concept PR here to demonstrate a path toward making exporters pluggable:

  *   #9175<https://github.com/IQSS/dataverse/pull/9175>

We have a modularity doc almost ready to share with the community, but for now, please read the doc referenced in this blog post: https://dataverse.org/blog/restructuring-dataverse-ui-single-page-application

Feedback is welcome, of course!

Our experience so far, is that Dataverse seems to be a closed system, so it is cumbersome to extend it.

I hope that the doc above helps convince you that we're trying. 😅 I'd like to use the modularity doc as a basis for a new page in the guides called something like "how to extend Dataverse" to explain what's possible now. That doc also attempts to explain our ideas for the future.

Thanks for your questions here. What is the "definition of done" for this issue? Would more documentation help? Are you interested in making a pull request to improve the documentation? 😄

**Comment by pdurbin** [comment]
@diego-guillen sounds good. I'll close it. If you ever want to chat in real time you can find me at https://chat.dataverse.org

Another good place for questions like this is https://groups.google.com/g/dataverse-community

Thanks for kicking the tires on Dataverse!
