### ISSUE TITLE
Fix Binder and Whole Tale (repo2docker) to download original files rather than archival .tab files

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#9374]
I think this is a 10 (1 day's work). It's just adding `?format=original` to the Dataverse content provider in repo2docker.

Related issues:

- https://github.com/jupyterhub/repo2docker/issues/1242
- #8524
- https://github.com/IQSS/dataverse.harvard.edu/issues/208
- https://github.com/IQSS/dataverse.harvard.edu/issues/209

**Comment by pdurbin** [comment]
> It's just adding `?format=original`

Uh oh, maybe its more work:

- #6408

It seem like we'd need to change code on the Dataverse side first to avoid 404s? When data hasn't been ingested?

Hmm, and what if we need to have Binder check the version of Dataverse first to know what behavior to expect (assuming we change it).

I'm changing the estimate to 33. A quick look into the 404 behavior would be good.

**Comment by landreev** [comment]
Hmm, #6408 is an old issue. I don't believe it is true anymore - I did run a quick test after you had opened this issue, I added "format=original" to the download api for a non-tabular file, and it appeared to have worked just fine. We should of course triple-check it; but we must have changed it specifically to accommodate something very similar, like being able to pass that "original" flag to the download-all api and have it applied to the files that have originals without causing problems with those that do not.

**Comment by pdurbin** [comment]
@landreev (as discussed internally as well) that's great news. Thanks for poking at that. I'll switch this back to a 10, then, since we hope we won't have to touch the Dataverse code. Let's put #6408 through QA as part of this effort.

**Comment by pdurbin** [comment]
On Friday I made a pull request to improve repo2docker to download original files:

- https://github.com/jupyterhub/repo2docker/pull/1253

Assuming it gets merged, I'll add a release note snippet on the Dataverse side about the change.

I'll also notify the Whole Tale folks, since they use repo2docker.

**Comment by mreekie** [comment]
grooming
- This is in a waiting state waiting for wholetail to accept a PR.
- remaining in the march 15th sprint but with zero cost.

**Comment by pdurbin** [comment]
Still no word on my PR.

https://repo2docker.readthedocs.io/en/latest/contributing/contributing.html says to ask on Gitter so I did: https://matrix.to/#/!WfHrQerMPeSiGRQIbO:gitter.im/$F8Slx836gGTaErzfd9BEWR_oIcBwIpXn3DxeTwPJhSM?via=gitter.im&via=matrix.org

**Comment by pdurbin** [comment]
Good news! My pull request on the repo2docker side was merged and already deployed to mybinder.org! Works great, I think, from my testing!

I created a pull request to note the change (improvement!):

- #9483

**Comment by mreekie** [comment]
grooming
- including this in the NIH March report as a size 10.
- Updated the NIH labels to indicate this was included in yr 2
