### ISSUE TITLE
Storage metering: Allow tracking and limiting total and individual file upload space per user/group.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#938]
This was requested by a user , see RT #186367 but is also something we have considered as we have had more interest in storing large amounts of data, >1TB:

One potential client of the Dutch Dataverse Network would like to set
restrictions to the size of files and datasets that individual
researchers can upload, because the costs of storage are billed.
Specifically, they said: a researcher should be allowed to upload a file
of up to 50 GB, but the total combined size of files uploaded by one
researcher is max 50 GB.

Apart from a limit in the JVM options on the size of files transferred
via the web interface, I couldn't find an option in the current release
or the list of features for Dataverse 4 to control the storage size of
dataverses, datasets or files.

**Comment by pdurbin** [comment]
I'm just adding the word "quota" here because that's what will help me find this issue again in the future.

**Comment by pdurbin** [comment]
@raprasad just showed me a neat trick where you can see the number of datasets in various ranges of storage usage.

https://services.dataverse.harvard.edu/miniverse/metrics/v1/datasets/bytes-used?key=REDACTED&pretty=true&skip_empty_bins=true

            {
                "bin": "(0, 50000000]", 
                "count": 19488, 
                "sort_key": 0, 
                "percentage_of_datasets": "91.0654%", 
                "bin_start_inclusive": 0, 
                "bin_start_inclusive_commas": "0", 
                "bin_start_inclusive_abbrev": "0.0 B", 
                "bin_end": 50000000, 
                "bin_end_commas": "50,000,000", 
                "bin_end_abbrev": "47.7 MB", 
                "bin_str": "0.0 B to 47.7 MB"
            }, 
            {
                "bin": "(50000000, 100000000]", 
                "count": 554, 
                "sort_key": 50000000, 
                "percentage_of_datasets": "2.5888%", 
                "bin_start_inclusive": 50000000, 
                "bin_start_inclusive_commas": "50,000,000", 
                "bin_start_inclusive_abbrev": "47.7 MB", 
                "bin_end": 100000000, 
                "bin_end_commas": "100,000,000", 
                "bin_end_abbrev": "95.4 MB", 
                "bin_str": "47.7 MB to 95.4 MB"
            },

**Comment by pdurbin** [comment]
Related: #4339.

**Comment by pdurbin** [comment]
Closing in favor of this issue:

- #4339
