### ISSUE TITLE
Zip files containing "shape file" folder should successfully upload 

### ISSUE THREAD

**Issue by sbarbosadataverse** [IQSS/dataverse#9384]
**What steps does it take to reproduce the issue?**

Create a zip file with folders, and include a folder containing shape files. Attempt to upload the zip file and you get no success or failure message, just no successful upload.

* When does this issue occur?
When a zip file contains a folder w/ shapefiles (not sure what happens if files are not in folders)

* Which page(s) does it occurs on?

file upload page

* What happens?
No success or failure message. The entire zip file does not show up in the list of files uploaded as normally expected.

* To whom does it occur (all users, curators, superusers)?
Everyone

* What did you expect to happen?
I expect a successfull upload and extraction of folders (folder preservation if possible) or an error message about failed upload

**Which version of Dataverse are you using?**

Most recent 5.12

**Any related open or closed issues to this bug report?**

possibly related:
 https://github.com/IQSS/dataverse/issues/8945**

I tested this myself with several reports from users and they confirmed when the shape file folder is removed, the zip file uploads successfully. https://help.hmdc.harvard.edu/Ticket/Display.html?id=336008
his zip file is attached to the ticket

**Comment by pdurbin** [comment]
> * When a zip file contains a folder w/ shapefiles (not sure what happens if files are not in folders)

I'm having trouble reproducing this. I downloaded a Shapefile from the City of Portland about [grocery stores](https://gis-pdx.opendata.arcgis.com/datasets/f212f915a0cb4688a6acc3d07932a730_40/explore?location=45.516875%2C-122.670350%2C11.95) and put it in a directory called "dir1" and created a zip. However, it uploads fine to Dataverse (I'm on the "develop" post 6.2, commit 8fec3516c7). Here's how it looks

![Screenshot 2024-06-07 at 3 43 40 PM](https://github.com/IQSS/dataverse/assets/21006/9b458182-259a-4781-950c-f1a53b3659e8)

Here's the zip file I'm using:

- [dir1.zip](https://github.com/user-attachments/files/15744225/dir1.zip)

> his zip file is attached to the ticket

Unfortunately, the Apple download link in the ticket has expired.

@sbarbosadataverse do you think you could provide me with a Shapefile that reproduces the bug?

**Comment by sbarbosadataverse** [comment]
@pdurbin  oh I am not sure now...I would have to find the RT ticket. Perhaps closing and when it happens again I will be sure to include the dataset and link to the files.

**Comment by pdurbin** [comment]
@sbarbosadataverse sounds fine, thanks. Closing.
