### ISSUE TITLE
Spike: Investigate interoperability between google datacommons and dataverse

### ISSUE THREAD

**Issue by mreekie** [IQSS/dataverse#9385]
work to get testing ingestions of dataverse data into google datacommons.

Re-adding info from 9368

- how to import data into GDC explained [here](https://github.com/datacommonsorg/data/blob/master/docs/README.md);

- test data set is [here](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/SEGOVA). This data has both geographical and temporal resolution using standardized identifiers.

expected output should be:
- getting this data indexed into our [instance](https://gdc.dataverse.org) of GDC
- back reference to Dataverse (see red oval in img below) 

![Image](https://user-images.githubusercontent.com/5621970/219062033-8221918e-09dc-476a-b720-17199c9578cd.png)

Stefano, Julian and ? (I need a dev).

**Comment by mreekie** [comment]
Next step:
- identify someone to work with Stefano and Julian on this.

**Comment by mreekie** [comment]
Daily
- Added to sprint at request of Stefano.
- Stephen - Thanks for picking this up!

**Comment by sekmiller** [comment]
Link to our importer wizard: https://gdc.dataverse.org/import

**Comment by mreekie** [comment]
Sizing:
- The work on this is by definition open-ended right now.
- sized 80 to reflect work will span this sprint.

**Comment by mreekie** [comment]
Sprint Review
- Just a note that this was worked prior to getting credit Feb 8th sprint but we didn't record points.
- It will get the full 80 points this sprint

**Comment by mreekie** [comment]
Grooming:
- This one is going to be considered closed for the March 1 sprint. Ensure that the 80 points are counted for the March 1 sprint.
- Steve is going to open a new issue for implementation for March 15 sprint.

**Comment by sekmiller** [comment]
Investigation is completed. Closing in favor of a feature request for implementation.
https://github.com/IQSS/dataverse/issues/9449
