### ISSUE TITLE
Feature Request/Idea: Invitation to the ELN Consortium

### ISSUE THREAD

**Issue by NicolasCARPi** [IQSS/dataverse#9389]
Hello,

I would like to invite the core developers of Dataverse to [the ELN Consortium](https://github.com/TheELNConsortium/).

Now that Dataverse started adding support to `.eln` files (see #9363), it makes sense that IQSS appears as members of the ELN Consortium.

There are no membership fees or obligations. It just makes it easier to participate in the discussions and the very few meetings we have from time to time. It is also important for the consortium to grow its members count with impactful participants.

While it is a consortium primarily composed of ELN vendors, a data repository software such as Dataverse has all its place, as a data repository is a concept close to the lab notebook one.

Please kindly let me know if you're okay with that, I will add IQSS/Dataverse to the member list and also tell me what are the `@` github usernames that should be invited.

Best,
~Nico

**Comment by pdurbin** [comment]
@NicolasCARPi hi! I hope we can be pretty informal about this. You're welcome to add me (@pdurbin) to your member list.

I'd like to suggest that other core Dataverse devs could leave a comment as well. Maybe after a month or so we could close this issue.

No fees. No obligations. I love it. /me puts his feet up

**Comment by pdurbin** [comment]
@NicolasCARPi it's been a few months. Do you want to close this?
