### ISSUE TITLE
 Translate hard coded text - File Access

### ISSUE THREAD

**Issue by DS-INRA** [IQSS/dataverse#9394]
**What steps does it take to reproduce the issue?**

* When does this issue occur?
when browsing using another language than en_US

* Which page(s) does it occurs on?
/file.xhtml?persistentId=doi:[...]

* What happens?
Some dropdown headers are hard coded and can't be translated

* To whom does it occur (all users, curators, superusers)?
everyone

* What did you expect to happen?
make the following dropdown header translatable, as are (strangely) already some others already
- https://github.com/IQSS/dataverse/blob/95c5816a04247040bfe88f3aa15e951cbed6d41a/src/main/webapp/file-download-button-fragment.xhtml#L15
- https://github.com/IQSS/dataverse/blob/95c5816a04247040bfe88f3aa15e951cbed6d41a/src/main/webapp/file-download-button-fragment.xhtml#L214

**Which version of Dataverse are you using?**
5.12.1, but issue still present on the develop branch to this day

**Any related open or closed issues to this bug report?**
Other issue related to hard coded strings
 #9292 

**Screenshots:**
![image](https://user-images.githubusercontent.com/46443753/219654114-5e15a9e9-ef9e-4a44-ad3a-7f215d3ae3b0.png)

**Comment by pdurbin** [comment]
@DS-INRA yes, you're absolutely right. Thanks for pointing this out! Are you interested in making a pull request? 😄
