### ISSUE TITLE
Metadata verification error labels are not translated

### ISSUE THREAD

**Issue by stevenferey** [IQSS/dataverse#9397]
_Issue created by the "entrepot.recherche.data.gouv.fr" team_

**What steps does it take to reproduce the issue?**

Filling in the metadata of a Dataset and not respecting the data type

* When does this issue occur?

When the metadata is invalid

* Which page(s) does it occurs on?

-> Editing the metadata of a dataset
-> Creating a dataset

* What happens?

If the value of a metadata field does not respect the data type, then a validation error message is displayed.
This error message is not internationalized.

If the Dataverse is in FR, the error message should be configurable in FR in a property file.

Currently, the label is directly declared in the Java class.
DatasetFieldValueValidator.java

* To whom does it occur (all users, curators, superusers)?

All the users

* What did you expect to happen?

If the Dataverse language is FR, the error message should be displayed in FR

**Which version of Dataverse are you using?**

5.12.1

**Any related open or closed issues to this bug report?**

**Screenshots:**

![Capture_error_label_EN_01](https://user-images.githubusercontent.com/13960773/220122741-c5892ec6-fede-40b4-8f73-8ce7f8a52f06.png)

![Capture_error_label_EN_2](https://user-images.githubusercontent.com/13960773/220122765-3465fac8-b8a9-4bd2-9fb9-e5f6efac1113.png)

**Comment by pdurbin** [comment]
@stevenferey good catch! Thanks for opening this issue, which is still present as of 5.13:

- not a valid entry: https://github.com/IQSS/dataverse/blob/v5.13/src/main/java/edu/harvard/iq/dataverse/DatasetFieldValueValidator.java#L62
- date: https://github.com/IQSS/dataverse/blob/v5.13/src/main/java/edu/harvard/iq/dataverse/DatasetFieldValueValidator.java#L131
- not a valid number: https://github.com/IQSS/dataverse/blob/v5.13/src/main/java/edu/harvard/iq/dataverse/DatasetFieldValueValidator.java#L146
- not a valid integer: https://github.com/IQSS/dataverse/blob/v5.13/src/main/java/edu/harvard/iq/dataverse/DatasetFieldValueValidator.java#L160

I THINK that's all of them but I may have missed one or two in that class.

@stevenferey are you interested in making a pull request? 😄
