### ISSUE TITLE
Facets filter labels not translated in result block

### ISSUE THREAD

**Issue by luddaniel** [IQSS/dataverse#9408]
Hello Dataverse team,

We wanted to report that facet filters are not translated in the top block result after selection.
Here is a screenshot :
![facets_fr](https://user-images.githubusercontent.com/83018819/221217587-eb1335fe-9cce-47a5-90bf-6aee9498c316.png)

Current language is **French**, on the left panel, values are translated in **French** but in top block result fragment value are in **English** (default language for Payara in our case).

Same screnshot with **English** as language :
![facets_en](https://user-images.githubusercontent.com/83018819/221217591-d2222c46-34f3-4226-a076-054f785b3a86.png)

**Which version of Dataverse are you using?**

5.12.1

**Any related open or closed issues to this bug report?**

Issue could be related to #8287 and #8286 but not sure. 

Can you do something about it ?
PR is not planned on our side for now. 

Regards.

**Comment by pdurbin** [comment]
@luddaniel thanks for reporting this.

@stevenferey I wonder if we need a fix like the one you recently made:

- #9406
