### ISSUE TITLE
Add Markdown previewer to list in Admin Guide

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#9412]
As of this writing there are 887 Markdown files in Harvard Dataverse: https://dataverse.harvard.edu/dataverse/harvard/?q=fileContentType%3A%22text%2Fmarkdown%22

We should test and hopefully merge the new Markdown previewer by @ErykKul and then add it to the guides as a supported file:

- https://github.com/gdcc/dataverse-previewers/pull/23

Here are the Markdown files in Harvard Dataverse (no preview):

![Screen Shot 2023-02-27 at 3 59 15 PM](https://user-images.githubusercontent.com/21006/221685223-6343a06a-7107-48eb-b640-d485e3ecd05f.png)
![Screen Shot 2023-02-27 at 4 03 54 PM](https://user-images.githubusercontent.com/21006/221685227-1ba7dced-54f3-48e8-af8b-ad693a9c5a36.png)

Here's how the Markdown previewer looks (from the PR above)

![220663435-d20d6b00-3914-4f63-824c-5cda08084670](https://user-images.githubusercontent.com/21006/221685056-89871414-241e-48c9-8793-34355ca480cc.png)

**Comment by pdurbin** [comment]
The Markdown previewer seems to work fine. Below is an example from https://data.qdr.syr.edu/file.xhtml?persistentId=doi:10.5064/F6VOIB8H/W1ACTL

![Screen Shot 2023-09-27 at 9 25 48 AM](https://github.com/IQSS/dataverse/assets/21006/1cfaf11a-c958-4b15-b0b1-dad49d9c1917)

**Comment by pdurbin** [comment]
The task is to updated a future version of the list below at https://guides.dataverse.org/en/6.0/admin/external-tools.html#inventory-of-external-tools to mention Markdown in the description of for File Previewers.

![Screen Shot 2023-09-27 at 9 27 52 AM](https://github.com/IQSS/dataverse/assets/21006/59a5bcc4-8164-4d81-beb5-b8d054eec04a)


In addition https://guides.dataverse.org/en/6.0/user/dataset-management.html#file-previews should be updated to add "Markdown" to the list.

![Screen Shot 2023-09-27 at 9 30 37 AM](https://github.com/IQSS/dataverse/assets/21006/6d25d1c6-6a15-4ea6-b8d2-67c26df033a8)

The files to edit:

- https://github.com/IQSS/dataverse/blob/develop/doc/sphinx-guides/source/_static/admin/dataverse-external-tools.tsv
- https://github.com/IQSS/dataverse/blob/develop/doc/sphinx-guides/source/user/dataset-management.rst

How to help with docs: http://preview.guides.gdcc.io/en/develop/developers/documentation.html

**Comment by mr-loop-1** [comment]
Hi @pdurbin  I would like to pick this up

**Comment by pdurbin** [comment]
@mr-loop-1 done! If you have any questions, please let me know here or over in #dev at https://chat.dataverse.org . Thanks! ❤️
