### ISSUE TITLE
Dataverse container-based development environment

### ISSUE THREAD

**Issue by GPortas** [IQSS/dataverse#9423]
## Overview of the Feature Request
The goal is making Dataverse development environment setup and management easier, from the initial installation to the day-to-day development. The following points have been considered when opting for a container-based development environment:

- SPA frontend developers don’t have to worry so much about backend installation details.
- Environment initialization/shut down is done in a simple way, considering we use docker-compose.
- Easier process and with fewer installation dependencies than the current process based on installation scripts and dependencies directly installed on the localhost machine.

In addition, introducing this, currently development-oriented, offers the following advantages, which are transferable and  beneficial for a future container-based production environment.

- Greater scalability and modularity, by self-containing each dependency service in its own container.
- Greater testability, by having more control over the different dependencies of Dataverse and the application itself.

For Dataverse, a custom Docker image is required. As for now is just for development purposes only, we can resort to fake properties or dependencies when needed (such as fake DOI values or SMTP server). Ideally this image will be evolved for productive use as well.

For Dataverse dependencies (PostgreSQL, Solr, etc) we should use official images where possible or create custom ones if the official ones are not enough. In the case of Keycloak, it would become part of these services too, based on the existing docker (and docker-compose) configuration recently added to the code base.

The ultimate goal is to have a docker-compose file that we can manage to have a full dev environment deployed locally (with persistent volumes when necessary). We can take inspiration from this: https://github.com/harvard-lts/drs-import-management-service/blob/main/docker-compose-dev.yml

## What kind of user is the feature intended for?
Developers

## What inspired the request?
- A demo from @ekraffmiller of docker-compose-cypressdev.yml from https://github.com/opendp/dpcreator
  - docs at https://github.com/opendp/dpcreator/blob/develop/README-DEVELOPMENT.md
  - `docker-compose up --build` - to build dependencies and start the containers
  - `docker-compose run server ./migrate.sh` - for dev, it's ok to run a script to do some config after the container is running
  - `docker-compose down --rmi` - to delete all containers
- The recent addition of a Container Guide, previewable at http://preview.guides.gdcc.io/en/develop/container/index.html
- SPA development work
- Difficulties with the current installation process
- Other applications (this approach is widely used today) [Example](https://github.com/harvard-lts/drs-import-management-service/blob/main/docker-compose-dev.yml)
- IQSS/dataverse#8709 
- IQSS/dataverse#9228 
- IQSS/dataverse#9234 
- IQSS/dataverse#6799
- IQSS/dataverse#8251
- IQSS/dataverse#5068
- IQSS/dataverse#9237 

## What existing behavior do you want changed?
Dataverse development environment setup

## Any brand new behavior do you want to add to Dataverse?
No, should be the same.

## Any related open or closed issues to this feature request?
- IQSS/dataverse#8709 
- IQSS/dataverse#9228
- IQSS/dataverse#5292
- IQSS/dataverse#4040
- IQSS/dataverse#4665
- IQSS/dataverse#8932 and IQSS/dataverse#8933 
- IQSS/dataverse#8934
- IQSS/dataverse#8320 and IQSS/dataverse#7662

**Comment by pdurbin** [comment]
Should we close this issue in favor of this one...

- #9616

... and then just fix stuff along the way as more developers use Docker?

**Comment by pdurbin** [comment]
@GPortas and I agree. Close it! See https://preview.guides.gdcc.io/en/develop/container/dev-usage.html for how to use containers! 🎉
