### ISSUE TITLE
Add Pooch to list of API client libraries (Python)

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#9433]
Pooch is a Python library and the authors announced that they now support Dataverse at https://groups.google.com/g/dataverse-community/c/GKJty_qNDbU/m/Kt4GJbIwAwAJ

We should update https://guides.dataverse.org/en/5.13/api/client-libraries.html#python

Docs on how to do this are here: https://guides.dataverse.org/en/5.13/developers/documentation.html

**Comment by Rehan-stack** [comment]
hi, i am interested to work on this issue.

**Comment by pdurbin** [comment]
@Rehan-stack hi! Over at https://groups.google.com/g/dataverse-community/c/GKJty_qNDbU/m/8ClZtue3DQAJ @dokempf said he was going to prepare a pull request.

@dokempf what do you think? Do you want to let @Rehan-stack make a pull request and you can give feedback?

@Rehan-stack like I said above, https://guides.dataverse.org/en/5.13/developers/documentation.html explains how to edit the Dataverse Guides (the guide in question is the API Guide). I'm sure I can find another issue for you to work on if @dokempf would prefer to work on this one! 😄

**Comment by pdurbin** [comment]
@Rehan-stack I just added the "good first issue" label to a few more: https://github.com/IQSS/dataverse/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22

If you want to chat about any of these: https://chat.dataverse.org . Thanks for your interest in contributing! 🎉
