### ISSUE TITLE
Build locally a Dataverse app image for dev

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#9434]
- As [discussed](https://dataverse.zulipchat.com/#narrow/stream/375812-containers/topic/PR.20.239424.3A.20dv.20container.20for.20dev/near/340931041), start with PR [#9424](https://github.com/IQSS/dataverse/issues/9424), make a new branch, merge in the latest from develop (especially PR #9417, which we are building upon for Postgres and Solr in containers)
- keep the "dev" docker-compose, remove the other
- remove mailhog 🐷 
- think about a better name for [dev-rebuild-docker.sh](http://dev-rebuild-docker.sh/) - `bootstrap.sh`?
- docs, docs, docs

**Comment by johannes-darms** [comment]
Could we use this issue and related MR to clean up the container (docker) related code and documentation? This repository contains four location related to containers, the documentation points to two different repositories and its a bit challenging to find `right`/`current` approach.

In this repository are:
[docker-aio](https://github.com/IQSS/dataverse/tree/develop/conf/docker-aio)
[docker-dcm](https://github.com/IQSS/dataverse/tree/develop/conf/docker-dcm)
[container-base](https://github.com/IQSS/dataverse/tree/develop/modules/container-base)
[Dockerfile](https://github.com/IQSS/dataverse/blob/develop/Dockerfile)
[docker-compose-dev](https://github.com/IQSS/dataverse/blob/develop/docker-compose-dev.yml)

The documentation has 16 pages mentioning docker and one page, that  links to two other repositories:
https://guides.dataverse.org/en/latest/search.html?q=docker&check_keywords=yes&area=default 
https://github.com/IQSS/dataverse-kubernetes, redirects to https://github.com/gdcc/dataverse-kubernetes
https://github.com/IQSS/dataverse-docker

**Comment by pdurbin** [comment]
@poikilotherm just made this PR:

- #9439 

So I'll do our normal "swap the issue for the PR" on the project board.

@johannes-darms yes, we'll be removing the cruft that is old approaches once we have a new stable one.

And docs! We'll be cleaning up docs as we go.

I see you RSVP'ed for the kickoff! Great! 🎉

**Comment by pdurbin** [comment]
> Could we use this issue and related MR to clean up the container (docker) related code and documentation?

@johannes-darms you're right. We should I just pushed 1382b05 into the PR for this issue, a rewrite of the "containers" page in the dev guide. Please give feedback in the PR (you can even add a review, of course!):

- #9439

**Comment by mreekie** [comment]
grooming:
- If I follow this right, based on #9439 this has made it over the "ready for QA" finish line for the sprint. 
-
