### ISSUE TITLE
Ingest: In progress indicator sometimes does not update, though it completes and disappears when refresh.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#944]
This issue happens intermittently and may be related to timing and/or file size. If I ingest Leonid's SPSS v22 test file, it seems to not update and remain on in progress, though if I refresh the page it shows it has completed. Other files do update the UI and Leonid thinks it is a timing issue.

**Comment by landreev** [comment]
The refreshing functionality has been much improved. 
I'm not claiming I have totally fixed it; I imagine it can still happen, i.e. the page can still fail to refresh on its own... But it should be much better now.

**Comment by kcondon** [comment]
@landreev Still happens with small files but will close and see whether UX testing flags it as a problem. closing
