### ISSUE TITLE
File ingest: Some extra Netcdf logging was left in place, making ingest noisy, especially of non netcdf files.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#9441]
While ingesting a simple test stata file, I'm seeing several log entries related to netcdf. This adds noise to the log and seems unnecessary.

[ingest_50by1000_dta.txt](https://github.com/IQSS/dataverse/files/10960450/ingest_50by1000_dta.txt)

**Comment by pdurbin** [comment]
This should be simple, just reducing logging from info to fine, like this:

```
diff --git a/src/main/java/edu/harvard/iq/dataverse/ingest/IngestServiceBean.java b/src/main/java/edu/harvard/iq/dataverse/ingest/IngestServiceBean.java
index 9c6acd964c..42116a222b 100644
--- a/src/main/java/edu/harvard/iq/dataverse/ingest/IngestServiceBean.java
+++ b/src/main/java/edu/harvard/iq/dataverse/ingest/IngestServiceBean.java
@@ -1272,7 +1272,7 @@ public class IngestServiceBean {
                     logger.info("NetcdfFiles.open() could not open file id " + dataFile.getId() + " (null returned).");
                 }
             } catch (IOException ex) {
-                logger.info("NetcdfFiles.open() could not open file id " + dataFile.getId() + ". Exception caught: " + ex);
+                logger.fine("NetcdfFiles.open() could not open file id " + dataFile.getId() + ". Exception caught: " + ex);
             }
         } else {
             logger.info("dataFileLocation is null for file id " + dataFile.getId() + ". Can't extract NcML.");
@@ -1310,7 +1310,7 @@ public class IngestServiceBean {
                 logger.info("exception throw calling processAuxiliaryFile: " + ex);
             }
         } else {
-            logger.info("extractMetadataNcml: input stream is null! dataFileLocation was " + dataFileLocation);
+            logger.fine("extractMetadataNcml: input stream is null! dataFileLocation was " + dataFileLocation);
         }
 
         return ncmlFileCreated;
```

I gave it a size of 3. I'd be happy to help a new contributor work on this one. My bug. 🪲 Sorry! 😅

**Comment by kcondon** [comment]
This issue may become more a problem at production scale. Can we prioritize this? @scolapasta @pdurbin

**Comment by pdurbin** [comment]
I'm sure I can roll this two line change into my PR for #9331 but if it isn't on the board, I might need a reminder.

**Comment by mreekie** [comment]
Grooming
- Added to sprint out of band

**Comment by mreekie** [comment]
@pdurbin @kcondon 
- This is confusing to the PM when work is pulled onto the board out of the prio process
- It would really helpful to leave a note specifically for the PM that explains what happened in non dev speak.

**Comment by pdurbin** [comment]
@mreekie it's been confusing all around. I thought it was about reducing the logging on two lines. Instead, it keeps going.
