### ISSUE TITLE
Implement Interoperability between Dataverse and Google Data Commons

### ISSUE THREAD

**Issue by sekmiller** [IQSS/dataverse#9449]
**Overview of the Feature Request**
We would like Dataverse datasets that are in csv format to be able to be uploaded to the Google Data Commons so that it can have more visibility and interaction with other similar datasets.

**What kind of user is the feature intended for?**
We envision a new curator task of an augmented codebook where the data owner would indicate which columns of their dataset they would like to have uploaded to the GDC (Date, Place, Variable Measured) we intend to make this as easy as possible with suggestions about variable naming, etc. We may also have to do some data conversions of date formats, for example.

There will be a method/script added to Dataverse to convert the codebook into the Template Metadata file required by the GDC (
https://docs.datacommons.org/custom_dc/prepare_data.html)

An automated process will perform the upload.

We will also customize our installation of the GDC and include at least a persistent identifier linking back to Dataverse and possibly other citation information.

**What inspired the request?**
We want to make the data more findable and interoperable.

**What existing behavior do you want changed?**

**Any brand new behavior do you want to add to Dataverse?**
Uploading of Dataverse data to the GDC

**Any open or closed issues related to this feature request?**

**Comment by mreekie** [comment]
next sprint:
- Research Continuing as a full 80
