### ISSUE TITLE
External tool problems when using allowedApiCalls / signed urls

### ISSUE THREAD

**Issue by beepsoft** [IQSS/dataverse#9453]
**What steps does it take to reproduce the issue?**

1. I'm running Dataverse 5.13 form the master branch
2. I tried following the External tools documentation https://guides.dataverse.org/en/latest/api/external-tools.html and load the [dynamicDatasetTool.json](https://guides.dataverse.org/en/latest/_downloads/11454dc75acef5448a10509ac962260d/dynamicDatasetTool.json) example
3. After that, trying to access the "Dynamic Dataset Tool" it won't get he "callback" param with the signed URL-s. This is because the in the documentation the "allowedApiCalls" key is under "toolParameters", however in [ExternalToolServiceBean.java ](https://github.com/IQSS/dataverse/blob/04a56e25435f465de4ee80ae540b7596d08b7a24/src/main/java/edu/harvard/iq/dataverse/externaltools/ExternalToolServiceBean.java#L204) it is parsed from the manifest's root (from jsonObject instead of toolParametersObj)
4. After fixing the manifest json and moving "allowedApiCalls" to the root of the json when I try to access the "Dynamic Dataset Tool" I get NPE:

```
  StandardWrapperValve[Faces Servlet]: Servlet.service() for servlet Faces Servlet threw exception
java.lang.NullPointerException
	at edu.harvard.iq.dataverse.externaltools.ExternalToolHandler.handleRequest(ExternalToolHandler.java:116)
	at edu.harvard.iq.dataverse.externaltools.ExternalToolHandler.handleRequest(ExternalToolHandler.java:83)
	at edu.harvard.iq.dataverse.externaltools.ExternalToolHandler.getToolUrlWithQueryParams(ExternalToolHandler.java:229)
	at edu.harvard.iq.dataverse.externaltools.ExternalToolHandler.getExploreScript(ExternalToolHandler.java:251)
	at edu.harvard.iq.dataverse.DatasetPage.explore(DatasetPage.java:5734)
	...
]]
```

In [ExternalToolHandler](https://github.com/IQSS/dataverse/blob/04a56e25435f465de4ee80ae540b7596d08b7a24/src/main/java/edu/harvard/iq/dataverse/externaltools/ExternalToolHandler.java#L110-L118) there seems to be a "break" missing in `case DATASET:`, so if I defined an external tool with `"scope": "dataset"`, it will also reach the `case FILE:` and will cause NPE for `dataFile.getId()`

**What did you expect to happen?**

The documentation suggests that the API Token way is `deprecated, less secure, not recommended` and so I thought the new signed url method should work.

It seems the unit tests don't cover either of the problems above.

**Which version of Dataverse are you using?**

5.13 from master branch.

**Comment by qqmyers** [comment]
Good catch! All your analysis looks correct - are you able to submit a pull request?

**Comment by beepsoft** [comment]
> Good catch! All your analysis looks correct - are you able to submit a pull request?

Sure. What should be the solution for the placement of the allowedApiCalls fields? Should be inside the 'toolParameters" or should I fix the examples?
