### ISSUE TITLE
Previewers don't work on files in deaccessioned versions

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#9455]
This affects relatively few users - only those who can see the files in deaccessioned datasets (authors, admins ...). Unauthorized users can see the dataset page for a deaccessioned version, but not the files. 
All it is is that an api token is needed to look at a deacc. file, but the page doesn't pass the token to the previewer. This is from FilePage.java: 
```
if (fileMetadata.getDatasetVersion().isDraft() || 
    (fileMetadata.getDataFile().isRestricted()) || 
    (FileUtil.isActivelyEmbargoed(fileMetadata))) {
            apiToken=fileDownloadService.getApiToken(user);
}
```
so it looks like all it needs is one extra line there: 
```
   fileMetadata.getDatasetVersion().isDeaccessioned() || 
```

**Comment by mreekie** [comment]
Grooming
- @landreev @kcondon @scolapasta 
- No comments. No labels. No size. Not prioritized?
- None on the PR either.
- Was this an emergency for  a customer or something
