### ISSUE TITLE
Dataset Json Validation: Agree on general structure - create a schema that matches our dataset JSON

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#9463]
This is the first step in addressing: https://github.com/IQSS/dataverse-pm/issues/26

Agree on general structure - create a schema that matches our dataset JSON without adding too much specifics on the metadata. Check the Structure. (no code) (10)

**Comment by johannes-darms** [comment]
@vera wrote some code to translate json schemas to the current tsv-based representation. Maybe we could reuse some of here ideas.

**Comment by pdurbin** [comment]
@johannes-darms @vera great idea! Yes! Please send us the code! ❤️

**Comment by sekmiller** [comment]
[sampleSchema.json](https://github.com/IQSS/dataverse/files/13205760/sampleSchema.json)

**Comment by sekmiller** [comment]
The intent of the schema above is to show a sample pf the schema that will be created in https://github.com/IQSS/dataverse/issues/9464 as custom for each collection (with varying required fields) I used the tool available here (https://www.jsonschemavalidator.net) to validate existing sample data against the sample schema.

**Comment by landreev** [comment]
The schema def., and basic idea seem solid. Since there's nothing to QA, should go straight into Done.

**Comment by landreev** [comment]
Closing.
