### ISSUE TITLE
Unique Identifiers for controlled vocabulary terms

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#947]
@pdurbin reminded me that we should store in the backend the unique identifiers for controlled vocabulary terms to make sure that if a term (string) is ever updated we just need to update the friendly name but in the backend it still corresponds to the same identifier. We could add an extra row in the tsv file that would not be visible in the UI.

This would be helpful for Country names which ISO http://en.wikipedia.org/wiki/ISO_3166-1 and FIPS http://en.wikipedia.org/wiki/Federal_Information_Processing_Standards use country codes and any biomedical metadata controlled vocabulary we use.

**Comment by scolapasta** [comment]
Column added - @posixeleni will you add the values now in the TSV?

**Comment by bencomp** [comment]
Is there any way to "import" public controlled vocabularies? I was thinking of creating a GitHub repository containing CVs for various lists of terms or using a publicly available vocabulary (e.g. the [SKOS version of DDC](http://dewey.info)), but if that means every update also needs manually editing the corresponding CV in Dataverse it makes no sense to keep them separate.

**Comment by posixeleni** [comment]
@bencomp sorry was out of the office and am only catching up now. So the plan is to eventually support automated updating (via an API, etc) to remove the need to manually update. Will track this progress in this ticket so you can see where we are with this automation. Let me know if you have any other controlled vocabularies you were thinking of automatically updating.

**Comment by bencomp** [comment]
I was thinking it would be nice to auto-complete terms entered in the keyword field and upon selection, automatically add the vocabulary URI in the correct field. This behaviour is not available in DVN 3.6 and goes beyond the scope of this issue, I think. To me, that keyword field is *the* field to link with external controlled vocabularies, like [ELSST][1].

[1]: http://elsst.ukdataservice.ac.uk

**Comment by posixeleni** [comment]
@bencomp we want to support auto-complete as well and this is tracked in ticket #350. Thanks for the feedback!

**Comment by kcondon** [comment]
OK, metadata blocks still functioning after id change. Closing.

**Comment by RightInTwo** [comment]
The solution proposed in #4772 would include saving the identifier from the source (rather than being limited to values hard-coded in the TSV file).
