### ISSUE TITLE
Internationalization issues where English text is appearing in UI and system-generated emails

### ISSUE THREAD

**Issue by meghangoodchild** [IQSS/dataverse#9488]
**What steps does it take to reproduce the issue?**

English text appears in messages and system-generated emails when the platform UI is set to another language.

* When does this issue occur?

When the UI is set to a non-English language (e.g., French), some text is appearing in English.

* Which page(s) does it occurs on?

- Tool tip as part of tabular ingest failed message on dataset page includes English text - "Ingest failed. No further information is available"
- File access menu on dataset page includes English text - "File access" and "Download metadata" strings
- Notifications (both in UI and in emails) show curation label status in English

* What happens?

Text strings are not completely showing in the appropriate non-English language.

* To whom does it occur (all users, curators, superusers)?

All users.

* What did you expect to happen?

We expect the strings to be completely in the selected non-English language.

**Which version of Dataverse are you using?**

Version 5.12.1

**Any related open or closed issues to this bug report?**

**Screenshots:**

No matter the issue, screenshots are always welcome.

Note: Jayanthy (Borealis/Scholars Portal) will provide pull request to address these issues.

![notificationpage](https://user-images.githubusercontent.com/34171553/228630747-2d40fb8e-8884-4b42-a4d9-679bb937eca1.png)
![Screen Shot 2023-02-22 at 11 58 23 AM](https://user-images.githubusercontent.com/34171553/228630750-4c618106-9f89-4885-9296-1661190bc66a.png)
![borealis-i18n-ca-fr-1](https://user-images.githubusercontent.com/34171553/228630751-9a6683ac-5871-401f-93ff-1cc4280b0932.jpg)

**Comment by DS-INRA** [comment]
Hello,
for the File Access part there is an opened PR https://github.com/IQSS/dataverse/pull/9451 :)
