### ISSUE TITLE
Creating a guestbook with a custom question that has more than 255 characters says "success" but silently fails

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#9492]
If you try to create a guestbook with a custom question that has more than 255 characters, the result us the success page, but no new guestbook is created. (in the log we see an exception that gets thrown.

```
org.postgresql.util.PSQLException: ERROR: value too long for type character varying(255)
Error Code: 0
Call: INSERT INTO CUSTOMQUESTION (DISPLAYORDER, HIDDEN, QUESTIONSTRING, QUESTIONTYPE, REQUIRED, GUESTBOOK_ID) VALUES (?, ?, ?, ?, ?, ?)
```

We should do one of the following: 
a) keep the user on the input page with the error message at the top, 
b) limit # of characters that can be input, or 
c) allow longer questions

**Comment by zieglerms** [comment]
Hi! I would greatly appreciate option (c). Longer questions allow us to explain what details we would like from the people who plan to use the data. These details help us communicate the broader impacts of our data collection efforts, and in turn, can help us justify funding for further data collection.

**Comment by cmbz** [comment]
**2023/12/18**
- Sized at 3, related PRs: https://github.com/IQSS/dataverse/pull/10118
