### ISSUE TITLE
Restore empty file persistentId value in JSON responses

### ISSUE THREAD

**Issue by qqmyers** [IQSS/dataverse#9496]
**What steps does it take to reproduce the issue?**
#8674 changed PID handling and inadvertently changed the no-PID behavior for the JSONPrinter from sending a "persistentId":"" key/value pair to not including a "persistentId" key. One effect of this change is that it breaks Previewers when opened in a separate page for files with no PIDs. THe change could affect any other users of the API, JSON metadata export, etc. (https://github.com/gdcc/dataverse-previewers/pull/29 will make previewers accept either case going forward). 

**Which version of Dataverse are you using?**
develop

**Comment by qqmyers** [comment]
Changing the default could be something to consider with #9463.

**Comment by mreekie** [comment]
@qqmyers @kcondon 
Grooming
- No comments. No labels. No size. Not prioritized?
- None on the PR either.
- Was this an emergency for a customer or something

**Comment by pdurbin** [comment]
This was a regression in the develop branch discovered by @kcondon 

It was introduced in PR #8674 as indicated in the comment in the fix.

Discussion here: https://iqss.slack.com/archives/C010LA04BCG/p1680701364259049

Thanks for fixing, @qqmyers! ❤️ Good catch, @kcondon! Thanks for keeping us release-ready.
