### ISSUE TITLE
Data Migration

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#95]
---

Author Name: **Gustavo Durand** (@scolapasta)
Original Redmine Issue: 3504, https://redmine.hmdc.harvard.edu/issues/3504
Original Date: 2014-02-03
Original Assignee: Kevin Condon

---

This ticket covers two primary use cases:

1. Providing real test data during development and testing.
2. Generating a final migration script for production cutover.

Some implementation issues that will need to be considered and most likely will become separate tickets are:
 -differing validation rules between v3.6 and 4.0 where something not required in v3.6 is required in 4.0. 
 -different field sizes between v3.6 and 4.0 where the initial sizes in 4.0 are too small and need to be increased to accomodate v3.6 data, eg. dataset description.

---

Child issue(s): #121
Redmine child issue(s): [3530](https://redmine.hmdc.harvard.edu/issues/3530)

---

**Comment by scolapasta** [comment]
Migration code as a whole is set. Any issues found should be opened as new issues.
