### ISSUE TITLE
Dataset Metadata: Add Help Text for Geographic Bounding Box Fields

### ISSUE THREAD

**Issue by posixeleni** [IQSS/dataverse#950]
In 3.6 we had this help text with a URL of the CGA Geo-location Finder http://maps.cga.harvard.edu/gpf/ that users could go to more easily get the coordinates from: 

![image](https://cloud.githubusercontent.com/assets/5013837/4578934/8375011c-4fc8-11e4-9c4b-1e36c8e3c89c.png)

Since this has a URL I would recommend we dont add this text in the tooltips but rather in the text right next to the field name.

**Comment by djbrooke** [comment]
Going to close this, as the Geofinder is no longer working and there are other help text suggestions in #6476
