### ISSUE TITLE
Document how to update a "develop branch to develop branch" pull request 

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#9508]
Originally posted at https://github.com/IQSS/dataverse/pull/8970#issuecomment-1430241288 below is how I've successfully merged the latest from IQSS "develop" branch into the pull request's "develop" branch.

We should document this (as well as discourage contributors from doing this).

```
# do all this in /tmp away from your normal code
cd /tmp
git clone git@github.com:IQSS/dataverse.git
cd dataverse
git remote add noobyu6 git@github.com:noobyu6/dataverse.git
git fetch noobyu6
# make a new branch not called develop (dev2)
git checkout noobyu6/develop -b dev2
git merge origin/develop
# delete the real develop branch (!) locally
git branch -d develop
# checkout dev2 (false develop)  as develop for now
git checkout -b develop
# push the false develop to the contributor's fork (to the PR)
git push noobyu6 develop 
cd ..
# delete the tmp space
rm -rf /tmp/dataverse
```

**Comment by ErykKul** [comment]
@pdurbin I always click on the "commits behind" button, it should work also for forks from other users. I was trying it out on your fork, but I am not allowed to create pull requests there:

![image](https://github.com/IQSS/dataverse/assets/101262459/ee3722ea-c3a1-4617-ae43-0ea006a98281)

Create pull request:

![image](https://github.com/IQSS/dataverse/assets/101262459/3776533b-1075-481d-ab21-d133f8abafa1)

![image](https://github.com/IQSS/dataverse/assets/101262459/75f5191f-61a7-4400-8c20-0e1c6fe440d3)

![image](https://github.com/IQSS/dataverse/assets/101262459/ce7d57ff-48aa-4e20-b66f-97350a431182)

I am not sure if it is a valid alternative for this particular problem.

**Comment by pdurbin** [comment]
@ErykKul hmm, I think we might be talking about two different things. Here's what I get when I click "commits behind" on my fork:

![Screenshot 2023-09-28 at 12-59-37 pdurbin_dataverse A data repository framework to share and publish research data](https://github.com/IQSS/dataverse/assets/21006/2859d2e4-21ca-47c9-858b-e8ca5705a208)
![Screenshot 2023-09-28 at 13-00-06 Comparing pdurbin develop IQSS develop · pdurbin_dataverse](https://github.com/IQSS/dataverse/assets/21006/8553e58d-c6e9-49cb-bfcd-4da595caa095)

I think it's trying to create a pull request to update my "pdurbin" develop to be the same as "IQSS" develop, so "pdurbin" isn't so far behind. This is useful but not the problem I'm trying to solve. 😄 

As someone reviewing and sometimes making light edits to PRs, it's inconvenient when the contributor calls their branch "develop" because I already have a local branch called "develop". It's tricky for me to push a small change to the contributor's "develop" branch. The steps I put in the description are the most sane way I've found so far to deal with this. I hope this makes sense! 😅

**Comment by ErykKul** [comment]
@pdurbin I think I get it now. It sounds like discouraging this would be the best strategy. I like the good practice of only doing pull requests associated with an issue and only with a branch having a name starting with the issue id (e.g. 9508_...). This could be placed in the pull request template at the very top of it.

**Comment by pdurbin** [comment]
@ErykKul ooo, I like the idea of updating the pull request template. We'd still want docs for core maintainers, though, when prevention doesn't work. 😄
