### ISSUE TITLE
File Ingest: Remove need for JHOVE to externally validate xml to enable use in firewalled environments.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#951]
This was a user request based on an operational issue they were seeing, see RT 186910:

I've got Dataverse set up on a machine in the Institute's DMZ and it can't
open connections through port 80 to the internet.
This doesn't seem to be an issue for most of the functionality (I can create
dataverses and studies, etc.)

However, when I try to upload data to a study (a 600k file), the interface
seems to idle for about 30 minutes before it shows the file in the table
where you can choose the category etc. I've asked the person responsible for
the firewall and he said that the only attempt to open an outgoing connection
was to "exp1.harvard.edu". When we open port 80, it works just fine.

------

We use package Jhove to determine the type of uploaded files. It's developed (or used to be?) elsewhere at Harvard, unrelated to Dataverse. Its configuration is stored in the XML file glassfish/domains/domain1/config/jhove.conf;

If you remove all the schema information from the XML header, I belive it will just parse it as is, without attempting to validate. So please replace the <jhoveConfig ...> tag
with simply "<jhoveConfig>", restart glassfish and try again.

--------

Maybe you can consider including this in one of the future releases?

**Comment by scolapasta** [comment]
@landreev is this something simple to do?

**Comment by landreev** [comment]
i believe it is done; will check and update.

**Comment by landreev** [comment]
This is done. In a quick-and-dirty way. I.e., I have removed the schema location url completely; as described in my response to RT 186910, above. A cleaner way of doing it would be to provide the schema locally. So this means, no validation of the xml... but, for the purposes of jhove, since we never need to modify the file during normal operations, it should be entirely ok.

**Comment by landreev** [comment]
(also, note that in the text above that Kevin copy-and-pasted from the RT ticket, the text inside angle brackets was lost; it should be read "replace the <jhoveConfig ...> tag with simply <jhoveConfig >"  - let's see if it gets chopped off again...)

**Comment by landreev** [comment]
Yep. Screw you, github. 
how about now: 

So please replace the &lt;jhoveConfig ...&gt; tag with simply &lt;jhoveConfig&gt;.

**Comment by kcondon** [comment]
OK, jhove.conf has tag updated in source tree. This was tested to work in the real world, so closing.
