### ISSUE TITLE
Solr custom Docker image for dev

### ISSUE THREAD

**Issue by GPortas** [IQSS/dataverse#9516]
## Overview of the Feature Request

The goal is to create a Solr image (currently oriented to development purpose, but scalable to prod) that self-contains the necessary configsets (schema, solrconfig, etc) so that the container initializes the core with the necessary configuration at startup, without needing to copy the configsets from the Dataverse repository or apply customizations through init containers or commands, as we currently do: [https://github.com/IQSS/dataverse/blob/develop/docker-compose-dev.yml#L50](https://github.com/IQSS/dataverse/blob/develop/docker-compose-dev.yml#L50)

Once this Solr image is pushed to a registry, just like the Dataverse application image, it will be a great advantage for frontend developers or any other Dataverse integration developer, since they will not depend on the Dataverse repository to setup Solr.

## What kind of user is the feature intended for?
Dataverse developers

## What inspired the request?
- Containerization strategy
- The need to easily setup Dataverse environments for testing. See: https://github.com/IQSS/dataverse-client-javascript/pull/55

## What existing behavior do you want changed?
N/A

## Any brand new behavior do you want to add to Dataverse Frontend?
N/A

## Any related open or closed issues to this feature request?

- #9439 
- #9447
- #7662

**Comment by pdurbin** [comment]
Now that we have configbaker, there is much less of a need for this. Closing, at least for now.
