### ISSUE TITLE
Enable Upload of larger files

### ISSUE THREAD

**Issue by mcrosas** [IQSS/dataverse#952]
From Michael B-S:

Here's how vimeo allows uploading of arbitrary large files (in their case, HD videos):

http://developer.vimeo.com/api/upload#http-put-uploading

In short, they create an upload ticket with its own url, have the user perform multiple PUT requests with binary data to it, and then finish the upload with a DELETE request on the ticket. There are also simple ways of validating the uploaded file.

There are some improvements that can be done over this, mainly allowing parallel uploads and having an md5 sum to validate not just the amount of files but also their correctness. Still, an interesting approach we could possibly adopt.

**Comment by michbarsinai** [comment]
Here's how Amazon S3 handles large files:
http://docs.aws.amazon.com/AmazonS3/latest/dev/UploadingObjects.html

**Comment by posixeleni** [comment]
@mcrosas @scolapasta since this relates to the helmsley grant funded project we are working on that will need FRD work to start in early January who should this ticket be assigned to and which milestone should we add it to?

cc/ @pdurbin @eaquigley

**Comment by pdurbin** [comment]
I'm fine with using this issue to track work for @sbgrid (the Helmsley grant). If so, it can be assigned to me. Or we can create an issue dedicated to that work with specific requirements.

I'd also like to point out some related issues:

- #1347 opened by @spalan mostly about S3 and Swift support (interest by @CCI-MOC)
- #2728 opened by @mutanthumb mostly about storing the files elsewhere (i.e. Globus)

For storage abstraction in general @akio-sone has been working on [some](https://github.com/akio-sone/dataverse/tree/irods-webdav-test) [branches](https://github.com/akio-sone/dataverse/tree/4.0.2-new-feature/irods-support) related to @irods support. I'm not sure what the status is.

Also @raprasad will be working in this space (storage, generally). We should see how much overlap there is on requirements.

Finally, both @sbgrid and @CCI-MOC are interested in **computing** on the data. I think they both have in mind that they will have direct access to the filesystem, which is different than how TwoRavens/Zelig works, from what I understand. I'd like to check in with @landreev on this.

**Comment by pameyer** [comment]
Does it make sense to include local checksumming (md5, sha, something else) in with the large file uploads, or should that be split off into something separate (since it could potentially be of use for small file uploads too)?

**Comment by pdurbin** [comment]
@pameyer good point about checksums. This certainly deserves its own issue so I just created one: #2788

**Comment by spalan** [comment]
I think the checksumming is critical in any context where a researcher needs to be sure of the integrity of the file he/she is working with.  It is also critical to the data archivist for proactive management of content he/she is curating, so that periodically checksums can be validated and corruption due to bit rot or other issues can be flagged early on.

Alan

On Dec 1, 2015, at 2:45 PM, pameyer <notifications@github.com<mailto:notifications@github.com>> wrote:


Does it make sense to include local checksumming (md5, sha, something else) in with the large file uploads, or should that be split off into something separate (since it could potentially be of use for small file uploads too)?

**Comment by mcrosas** [comment]
:+1: I don't think there is any questioning whether to include checksumming. The question is more about how it is implemented for larger files and whether is part of the upload (before or after)

**Comment by spalan** [comment]
This document describes strategies Swift uses for uploading very large files or collections of many files:

http://docs.openstack.org/developer/swift/overview_large_objects.html

I doesn’t mention anything about the use of checksums, however.

This cloud based data sync tool, rclone, supports transfers of large files to multiple cloud providers and does use checksums for validating successful transfers:

http://rclone.org/



On Dec 1, 2015, at 3:49 PM, Merce Crosas <notifications@github.com<mailto:notifications@github.com>> wrote:


[:+1:] I don't think there is any questioning whether to include checksumming. The question is more about how it is implemented for larger files and whether is part of the upload (before or after)

**Comment by spalan** [comment]
http://docs.openstack.org/developer/swift/api/large_objects.html

More on Swift handling of large objects that describes use of checksums

**Comment by djbrooke** [comment]
Closing this. There are issues under the "SBGrid" label that cover the upload of large files.

**Comment by pdurbin** [comment]
The primary issue to track for the SBGrid use case is this one:  Data Capture Module (rsync support) #3145
