### ISSUE TITLE
Widget-Customization: Data List has bad "hmdc" in URL

### ISSUE THREAD

**Issue by mheppler** [IQSS/dataverse#953]
The data list customization widget is pointing to the URL "https://dataverse-demo.hmdc.harvard.edu" for the javascript file it uses, and that URL has "untrusted" certificate.

The URL it should point to is, "https://dataverse-demo.iq.harvard.edu".

**Comment by landreev** [comment]
Kevin, 
Please note that whatever this ticket was originally opened for seems to have been fixed (and tested?) a while ago. 
Phil only gave me this ticket to add a documentation entry for the dataverse.siteUrl JVM option to the install guide; which I did.

**Comment by kcondon** [comment]
OK, documentation added, closing
