### ISSUE TITLE
Configurable server-port-number for the containerized Dataverse

### ISSUE THREAD

**Issue by akio-sone** [IQSS/dataverse#9534]
The current port-number of the containerized Dataverse server is set to 8080 in `docker-compose-dev.yml`.  
```
    ports:
      - "8080:8080" # HTTP (Dataverse Application)
```

Since the port-number 8080 is commonly used one and might be already preempted by another locally running container or web application, it is nice for developers to choose a non-8080 number.  

Although it is easy to change the port number in `docker-compose-dev.yml`, the shell script file `docker-final-setup.sh`, which is executed after the Dataverse starts running in a container and calls its 3 child shell script files, have many hard-coded 8080s in it. 
More specifically, 
```
scripts/dev/docker-final-setup.sh calls scripts/api/setup-all.sh
scripts/api/setup-all.sh calls the following 3 shell script files whose contents are mostly API calls

scripts/api/setup-datasetfields.sh
scripts/api/setup-builtin-roles.sh 
scripts/api/setup-identity-providers.sh
```
While this issue could be solved in a limited scope, it might be better to handle this issue in a much broader context such as refactoring of the overall configuration steps.

**Comment by pdurbin** [comment]
@akio-sone now that #9574 has been merged, can you please try this again?

We also have a thread going here if you'd like to discuss there: https://dataverse.zulipchat.com/#narrow/stream/375812-containers/topic/configurable.20ports

**Comment by johannes-darms** [comment]
@pdurbin isn't this issue solved?

**Comment by pdurbin** [comment]
Yeah, I think #9574 solved it. I'll give this the same milestone and close it.
