### ISSUE TITLE
Start Dataverse 5.13 with localized native language

### ISSUE THREAD

**Issue by rwvaldivia** [IQSS/dataverse#9537]
Hello,

After updating to the latest version (Dataverse Vr. 5.13), we noticed that when the app starts, the default language is en_US. Our users is requesting that the language be localized to our native language (pt_BR in our case).

We trying change the OS localization with localectl set-locale LANG=pt_BR, but this doens´t have effect.

**Comment by pdurbin** [comment]
@rwvaldivia hi! I don't think setting LANG is the way to fix this. 🤔 

https://guides.dataverse.org/en/5.13/installation/config.html#adding-multiple-languages-to-the-dropdown-in-the-header doesn't explain this well but I thought that the first language in the array is the default one.

So for this config...

```
[
  {
    "locale": "en",
    "title": "English"
  },
  {
    "locale": "fr",
    "title": "Français"
  }
]
```

I would expect en/English to be the default. (We use a LinkedHashMap, which should preserve the order: https://github.com/IQSS/dataverse/blob/v5.13/src/main/java/edu/harvard/iq/dataverse/SettingsWrapper.java#L440 )

Can you please paste the output when you curl http://localhost:8080/api/admin/settings/:Languages ?

**Comment by rwvaldivia** [comment]
Hi @pdurbin ,

This is the curl executed:
- curl http://localhost:8080/api/admin/settings/:Languages -X PUT -d '[{"locale":"br","title":"Português"},{"locale":"en","title":"English"}]'

I try to locate an attribute that put the language default in **br**, but seens like doens´t exist.

[{
	"locale":"br", 
	"title":"Português"
}
,
{
	"locale":"en",
	"title":"English"
}]

**Comment by pdurbin** [comment]
@rwvaldivia sorry, I forgot about this issue. Did you figure it out? Any progress?

**Comment by rwvaldivia** [comment]
Hi @pdurbin !!
Tks for asking. I wish to find you well!!

Yes. I solved it as follows using a strategy from the "Brazilian Research Network - RDP Brasil".

The strategy boils down to creating a menu called "Default Language" using the locale "en" (this is because the dataverse always uses en as the default). The problem is that for it to work, the localized content was placed in Portuguese/Brazil (this is a workaround). As I also need to leave the content in English, the location "us" and Spanish "es" were used. The final curl looked like this:

`curl http://localhost:8080/api/admin/settings/:Languages -X PUT -d '[{"locale":"en","title":"Default Language"}, {"locale":"br","title":"Português"},{"locale":"us","title":"English"}, {"locale":"es","title":"Spanish"}]'`

I adapted a bash script to help me whenever there are some changes to the language, based on the original bash script from RDP Brasil. The link to the original script is:

- https://lattesdata.cnpq.br/config/index.php/home/dataverse/customize/Languages

Well, this will do fine for any language. For example, German, Arabic or any other language. Just replace the content of location "en" with the content of the target language. 

Hope this helps.

**Comment by pdurbin** [comment]
Interesting, so you doing this...

    cp Bundle_br.properties Bundle_en.properties

... because "en" is the default.

Well, seems like a good workaround. 😄 

We're working on a new frontend web interface written in React at https://github.com/IQSS/dataverse-frontend and when we get around to adding the language drop down I'll try to remind everyone the we should support languages other than "en" as the default!

Thanks! Closing!
