### ISSUE TITLE
v5.6 changes break pydataverse and datalad-dataverse

### ISSUE THREAD

**Issue by mih** [IQSS/dataverse#9549]
**What steps does it take to reproduce the issue?**

Creating a dataverse dataset via the pydataverse API, using a metadata record that passes pydataverse's validator and used to work with `demo.dataverse.org` (presumably prior to the upgrade to v5.13).

* When does this issue occur?

It occurs every time.

* Which page(s) does it occurs on?

This issue is concerned with API usage, not the web UI.

* What happens?

Dataset creation is rejected (HTTP403) with the following message

```
'{"status":"ERROR","message":"Validation Failed: Title is required. (Invalid value:edu.harvard.iq.dataverse.DatasetField[ id=null ]), Author Name is required. (Invalid value:edu.harvard.iq.dataverse.DatasetField[ id=null ]), Subject is required. (Invalid value:edu.harvard.iq.dataverse.DatasetField[ id=null ]), Point of Contact E-mail is required. (Invalid value:edu.harvard.iq.datav
```

* To whom does it occur (all users, curators, superusers)?

I have no definitive answer, it appears to happen to every user, but we have not looked into different roles for the lack of a setup to do so.

* What did you expect to happen?

I expect a previously working metadata record to continue to work, and any transition to a new required format to be done at a pace that enables client software to adapt.

**Which version of Dataverse are you using?**

v5.13 as deployed on `demo.dataverse.org`

**Any related open or closed issues to this bug report?**

The necessary changes to Datalad's dataverse extension are documented in https://github.com/datalad/datalad-dataverse/pull/293 It is unclear whether an alternative approach would have been possible. But after these changes, our test battery passes again.

**Comment by pdurbin** [comment]
@mih I brought up this issue today in a discussion of last items to address before we ship 5.14.

Any news on this? I took a look at the PR you mentioned...

- https://github.com/datalad/datalad-dataverse/pull/293

... and it seems like you have a working solution. However, perhaps we did break something? I wonder if this will fix it on the pyDataverse side:

- https://github.com/gdcc/pyDataverse/pull/145

**Comment by pdurbin** [comment]
@mih please check this out. At https://github.com/gdcc/pyDataverse/pull/145#issuecomment-1629711512 @JR-1991 wrote that this PR might fix it:

- https://github.com/gdcc/pyDataverse/pull/145

But that would mean you last tested Datalad with Dataverse 5.8? (The backward-incompatible change of requiring "application/json" as a content header was introduced in 5.9). Does that make any sense?

**Comment by pdurbin** [comment]
We could add this to the new changelog:

- #10060

But what would we write exactly? @mih do you want to propose something? Here's the file: https://github.com/IQSS/dataverse/blob/b15b89f794415662ed860178c8f857446477d7b9/doc/sphinx-guides/source/api/changelog.rst#L4

**Comment by pdurbin** [comment]
Here's the API changelog as of https://guides.dataverse.org/en/6.2/api/changelog.html

<img width="902" alt="Screenshot 2024-04-06 at 4 27 51 PM" src="https://github.com/IQSS/dataverse/assets/21006/3e5007b9-e86d-4f34-86f8-f2a14ea5ab3e">
