### ISSUE TITLE
NetCDF/HDF5 code templates for Jupyter Notebooks, etc. for reproducibility and reuse

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#9551]
We'd like to create some initial code templates for exploring NetCDF and HDF5 files that can be retrieved from any Dataverse (or other) installation.

These templates would be executed in Binder or similar.

Here's an example of Jupyter Notebook from @JR-1991 that operates on a NetCDF file:

https://github.com/JR-1991/NetCDF-Example/blob/main/UploadNetCDF2DemoDV.ipynb

We could start with the one notebook above and use this issue to determine some good workflows to put the template into use in Binder, which we would document.

The code might go in a new git repo with a broader scope than just NetCDF/HDF5 files.

**Comment by pdurbin** [comment]
@atrisovic @JR-1991 and I just created https://github.com/gdcc/code-templates

**Comment by cmbz** [comment]
2024/01/08: Closing because grant is over and there is no immediate demand for the template.
