### ISSUE TITLE
Metrics API "file/byType/monthly" may not work

### ISSUE THREAD

**Issue by jeromeroucou** [IQSS/dataverse#9565]
Hi,

If I call metrics API `metrics/file/byType`, and after `metrics/file/byType/monthly` on the same collection, the result on `metrics/file/byType/monthy` doesn't respond correctly. On Recherche Data Gouv repository response have a HTTP 500 error code with a `NullPointerException` on the log file. On Dataverse Demo repository, the response code is 200 but the date is `null`.

I think the problem comes from using the same key in the database cache as the endpoint `metrics/file/byType` : if I call first `metrics/file/byType/monthly` the problem doesn't occur because the cache `filesByType` store the date information.

**What steps does it take to reproduce the issue?**

First I call `metrics/files/byType`.

```
curl https://demo.dataverse.org/api/info/metrics/files/byType?parentAlias=dataverseDeExemplo
```
And after I call `metrics/files/byType/monthly`.

```
curl https://demo.dataverse.org/api/info/metrics/files/byType/monthly?parentAlias=dataverseDeExemplo
```

* When does this issue occur?

When I call first `metrics/files/byType` and after `metrics/files/byType/monthly`.

* What happens?

The information date is `null` or the endpoint respond with a HTTP 500 error code with a `NullPointerException` on [FileUtil.java](https://github.com/IQSS/dataverse/blob/v5.13/src/main/java/edu/harvard/iq/dataverse/util/FileUtil.java#L2144).
If want to see the JSON response, I will see the information date is absent but the `NullPointerException` is absent : 

```
curl -s -H "Accept: application/json" https://demo.dataverse.org/api/info/metrics/files/byType/monthly?parentAlias=dataverseDeExemplo
```

This difference comes in the source code in [Metrics.java](https://github.com/IQSS/dataverse/blob/v5.13/src/main/java/edu/harvard/iq/dataverse/api/Metrics.java#L426) because the return type is `application/json`.

* To whom does it occur (all users, curators, superusers)?

All users

* What did you expect to happen?

If I call first `metrics/file/byType`, and after `metrics/file/byType/monthly`, I can see the date datas on last call.

**Which version of Dataverse are you using?**

5.12.1 and 5.13

**Comment by qqmyers** [comment]
@jeromeroucou - Good catch. Yes, it looks like a cut/paste error leaving these the same.  Are you interested in submitting a PR to fix it?
