### ISSUE TITLE
python installer doesn't create or verify existence of dataverse.files.directory

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#9572]
The installer defaults to
`os.environ['FILES_DIR'] = config.get('glassfish','GLASSFISH_DIRECTORY') + "/glassfish/domains/domain1/files"`
in https://github.com/IQSS/dataverse/blob/develop/scripts/installer/installAppServer.py#L43
which is fine.

Then https://guides.dataverse.org/en/5.10/installation/installation-main.html cautions `make sure the user running the installer has write permission to: <snip> your jvm-option specified files.dir`. It might be polite for the installer to test for at minimum the existence of files.dir, and squawk an appropriate caution in Section 9, "Declare Victory," letting admins know to either create the directory or update the jvm-option.

**Comment by donsizemore** [comment]
@poikilotherm I considered proposing making it configurable via default.config, but small chunks. Also, I have two installations with a specified but non-existent `dataverse.files.directory`; I'm intentionally sitting on creating the directory until something blows up.

**Comment by donsizemore** [comment]
@poikilotherm I support this. Feel free to edit my issue and title as you see fit?

**Comment by poikilotherm** [comment]
@donsizemore I created #9819 which is mostly to address #9662, but to ensure smooth operation I also added verification for the other directories. Does this solve your issue you described above? (Otherwise I can remove the "Closes" from the PR)
