### ISSUE TITLE
Update the new UNF6 document, based on recent feedback

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#959]
I've been talking extensively to Thomas Leeper about all things UNF. Quite a few ideas have came up in these discussions for improvements and additions to the new implementation spec I put together. 
Opening this ticket to remember to update the document incorporating all this feedback.

**Comment by landreev** [comment]
(this should be considered part of #1268, UNF documentation). 
This has been done. The v6 technical document should be considered finalized. The document has been moved from the old thedata.org site into the embedded dataverse documentation - in doc/sphinx-guides/source/developers/unf/unf-v6.rst.

**Comment by kcondon** [comment]
Updated doc is in the guide and looks good. Closing
