### ISSUE TITLE
Faster turn-around times for devs using containers

### ISSUE THREAD

**Issue by poikilotherm** [IQSS/dataverse#9590]
Part of the [containerization strategy](https://docs.google.com/document/d/14DHDB24Cp_kzpYqhHCKCtnzOw8_WuLOOONyqJHSsaYM/edit#), [milestone D](https://docs.google.com/document/d/14DHDB24Cp_kzpYqhHCKCtnzOw8_WuLOOONyqJHSsaYM/edit#heading=h.ysp9fn6ri34v).

With #9584 we will recommend stopping, repackaging and start all containers again after code changes. This takes, depending on your local hardware, 60-120 seconds. Investigate in making this faster is the task of this issue.

**Comment by pdurbin** [comment]
We talked about this about 45 minutes into today's container meeting: https://ct.gdcc.io

**Comment by pdurbin** [comment]
I'm just noting that today (and last Friday), I've been hacking around in xhtml and the feedback loop is unbearable with containers. I'm going to install Payara 6 directly on my Mac so I can hack on xhtml and have it deployed by Netbeans basically instantaneously.

**Comment by pdurbin** [comment]
@beepsoft just started a related thread at https://dataverse.zulipchat.com/#narrow/stream/375812-containers/topic/Payara.20admin.20console.20redirects.20to.20https/near/399050958
