### ISSUE TITLE
API search for terms of use & terms of access

### ISSUE THREAD

**Issue by CB-HAL** [IQSS/dataverse#9603]
**Overview of the Feature Request**
At the moment it isn’t possible to use the search API https://guides.dataverse.org/en/5.12.1/api/search.html for fields of the terms block (terms of use & terms of access). To make all terms fields searchable would be a great functionality.
Terms of use & terms of access metadata fields: license_name, license_uri, terms_of_use, confidentiality_declaration, special_permissions, restrictions, citation_requirements, depositor_requirements, conditions, disclaimer, file_access_request, terms_of_access, data_access_place, original_archive, availability_status, contact_for_access, size_of_collection, study_completion

**What kind of user is the feature intended for?**
API User, Curator

**What inspired the request?**
To get an overview of all terms in our dataverse.

**Any open or closed issues related to this feature request?**

- https://github.com/IQSS/dataverse/issues/7482

**Comment by pdurbin** [comment]
@CB-HAL hi, sorry for the slow reply. I see you already found this issue:

- #7482

I do think your issue is close enough that I'm closing it in favor of that one.

It's a very reasonable feature request! Thanks for letting us know it's important to you.
