### ISSUE TITLE
Create a CITATION.cff for citing Dataverse software

### ISSUE THREAD

**Issue by atrisovic** [IQSS/dataverse#9605]
**Overview of the Feature Request**

We should add a CITATION.cff in [the GitHub repository](https://github.com/IQSS/dataverse) to enable and facilitate Dataverse software citation. GitHub has enabled software citation using [the citation file format](https://citation-file-format.github.io). You can see more in the documentation [here](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files).

**What kind of user is the feature intended for?**

It is intended for everyone who uses and references the Dataverse software (especially in publications).

**What inspired the request?**

The community requests to cite the Dataverse software and GitHub's integration with [CFF](https://citation-file-format.github.io). 

**What existing behavior do you want changed?**

No existing behaviors would be changed.

**Any brand new behavior do you want to add to Dataverse?**

No.

**Any open or closed issues related to this feature request?**

None.

**Comment by pdurbin** [comment]
@atrisovic thanks for opening this issue and the PR!

@DS-INRA just opened a duplicate issue but I'm closing this one in favor of that one because it has a nice screenshot:

- #10187
