### ISSUE TITLE
Update dev guide to make use of containers the default

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#9616]
In a monthly meeting today we talked about how as part of our architecture and containerization strategy, we'd like to encourage developers to use the containers.

Concretely, we'd like to update the dev guide to no longer encourage developers to install Payara, PostgreSQL, and Solr directly on their laptops. Instead, we'd like to encourage the use of containers.

We'd like to keep the old content around as a fallback. I mentioned that I only got S3 working in containers this week. There may be parts of the code that are difficult to work on in containers.

**Comment by pdurbin** [comment]
I'm planning on moving the current dev env page to be called legacy or classic or something. Here are all the places that reference it:

![Screen Shot 2023-08-07 at 9 57 06 AM](https://github.com/IQSS/dataverse/assets/21006/4bfafed7-edbc-4066-985b-3321d42e5fe7)

**Comment by bencomp** [comment]
Ah, this explains why #9068 had merge conflicts 😞

**Comment by pdurbin** [comment]
Hi, @bencomp 👋 

Whoops, This issue is done. I addressed it with this PR...

- #9761

... which we merged into the Payara 6 branch which is now merged into develop.

When I wrote the email to the dev list about Payara 6 being merged, I linked developers to the updated Docker-encouraged version of the dev env page: https://groups.google.com/g/dataverse-dev/c/54AFJ_m8yXU/m/v4_UFNanAAAJ

Closing.
