### ISSUE TITLE
input database ID for Retrieve Guestbook Responses for a Dataverse Collection

### ISSUE THREAD

**Issue by CB-HAL** [IQSS/dataverse#9619]
**What steps does it take to reproduce the issue?**
The API call “[Retrieve Guestbook Responses for a Dataverse Collection](https://guides.dataverse.org/en/5.12.1/api/native-api.html#id47)” doesn’t work with the Database Id. With the alias it works.
With alias it works:
curl -H X-Dataverse-key:xxx https://data.aussda.at/api/dataverses/autnes/guestbookResponses 
With Id it doesn’t work
curl -H X-Dataverse-key:xxx https://data.aussda.at/api/dataverses/84/guestbookResponses 

* What happens?
Possible reason, Jim Myers: “I see the same thing – an empty response when using an id. My guess is that this was broken about two years ago when this line was added: https://github.com/IQSS/dataverse/blob/bef00db2fdf34c5460286cd22e7ac82a43f228fa/src/main/java/edu/harvard/iq/dataverse/api/Dataverses.java#L1129”
https://groups.google.com/g/dataverse-community/c/O9jF5o1FxTw/m/YVR9ILLrAAAJ?utm_medium=email&utm_source=footer

* To whom does it occur (all users, curators, superusers)?
API users

**Which version of Dataverse are you using?**
v. 5.12.1

**Comment by pdurbin** [comment]
Right we should be using `findDataverseOrDie(dvIdtf)` rather than `dataverseService.findByAlias(dvIdtf)`. I think this will be an easy change so I'm giving this a 3.

**Comment by jggautier** [comment]
@CB-HAL and @pdurbin, was this reporting the same issue described in https://github.com/IQSS/dataverse/issues/8563?

And should https://github.com/IQSS/dataverse/issues/8563 also be marked as closed by the PR at https://github.com/IQSS/dataverse/pull/10020?

**Comment by pdurbin** [comment]
@jggautier good catch! I closed that duplicate issue and left a comment: https://github.com/IQSS/dataverse/issues/8563#issuecomment-1803846433
