### ISSUE TITLE
Dataset Files - Editing Metadata

### ISSUE THREAD

**Issue by vjdorazio** [IQSS/dataverse#962]
Provided a dataset has been deposited and ingested, we want users to be able to edit the metadata.  Think of this as a metadata Wiki.  The metadata edits are to file types (e.g., network, survey, time series, etc.), variable labels, variable types (e.g., string, numeric, boolean, etc.), and variable tags (e.g., weights, unique identifier, time, space, continuous, etc.). The problem is that the original contributor may not agree with the edits, or the users may vandalize the data.  

An initial solution proposed by Merce is to make this a part of permissions.  That is, the original contributor has the option to allow other users to edit the metadata.

A long term solution proposed by Kevin is to have two separate metadata files for each public dataset: (1) the original metadata file, and (2) the user-edited metadata file.

The editing of metadata is to be done either through the API (as would happen when using TwoRavens), or using the interactive table editor, same as the original contributor uses.

**Comment by pdurbin** [comment]
Part of this issue are also mentioned in #961

**Comment by pdurbin** [comment]
@vjdorazio hi! Do you still have an active interest in this feature?

**Comment by pdurbin** [comment]
"having an interface to edit variable metadata would be excellent" -- @stevenmce at https://github.com/IQSS/dataverse/issues/3205#issuecomment-310673438

> The metadata edits are to file types (e.g., network, survey, time series, etc.), variable labels, variable types (e.g., string, numeric, boolean, etc.), and variable tags (e.g., weights, unique identifier, time, space, continuous, etc.). The problem is that the original contributor may not agree with the edits, or the users may vandalize the data.

The above, especially about weights reminds me of a conversation I had with @kevinworthington and @amberleahey at the 2017 Dataverse Community Meeting. In the talk they gave at https://osf.io/w5zsh/ titled "DDI and Dataverse: Use Cases for Enhanced Metadata Support Using the Data Documentation Initiative (DDI)", they talked about reusable metadata, weighting, and metadata markup, which all seems related:

![06162017-leahey-use cases for enhanced metadata support using the data documentation initiative ddi](https://user-images.githubusercontent.com/21006/27515496-33be5e0a-5972-11e7-9010-47b74e3906fc.png)

**Comment by stevenmce** [comment]
@pdurbin Good pickup - this comes directly from the discussions I've had with @amberleahey (we are both closely involved with DDI). The work @kevinworthington and @amberleahey are doing on the Data Explorer is heavily dependent on what is basically DDI metadata - so a tighter integration here would be valuable. In the end, machine actionable data requires some form of actionable metadata, so this would be one means of achieving this.

**Comment by amberleahey** [comment]
Indeed we can achieve variable tagging and variable editing using DDI in Dataverse. 

Tagging variables could improve the way the system understands tabular data. Supporting weighting of data, and how to visualize and analyse data. We could think about tagging for "weight" variable(s), "time", "geography" as examples. And data type e.g. "ordinal", "nominal", "continuous". 

For variable editing, ideally admins or curators could add information about the variables, such as question text, concepts, interviewer instructions, skip logic, universe or sample size statement, notes (recoding, etc.), and anything else one would like to add to improve understanding and reuse of data. This could greatly improve the relationship between data, code, and metadata. 

We are compiling a full list of DDI fields that could support this. I'll share via this thread...

**Comment by pdurbin** [comment]
Related issues: #4174 #4448

Related pull request: #4750

**Comment by djbrooke** [comment]
I'll close this old issue (was looking for another one :)), as this use case is probably handled these days by some mix of the Data Curation Tool (and the APIs that are used by it) and Aux files. If there's something specific that's not handled, we can open it as a new issue.

**Comment by jggautier** [comment]
From the original post:

> Provided a dataset has been deposited and ingested, we want users to be able to edit the metadata. Think of this as a metadata Wiki... The problem is that the original contributor may not agree with the edits, or the users may vandalize the data.
> 
> An initial solution proposed by Merce is to make this a part of permissions. That is, the original contributor has the option to allow other users to edit the metadata.

I think the original suggestion was to support the crowdsourcing of improved file metadata, which seems more in line with what's suggested in https://github.com/IQSS/dataverse/issues/7525. I don't think the Data Curation Tool or any Dataverse APIs allow people to contribute metadata to a published file (or published dataset), unless those people are given permission through the Dataverse software's permission systems. Do or would the "Aux files"?

**Comment by djbrooke** [comment]
@jggautier you're right. If this becomes a use case we want to support and we feel #7525 doesn't cover this, we can create a new issue.
