### ISSUE TITLE
Update GDC Custom UI For Harvard Dataverse Project

### ISSUE THREAD

**Issue by siacus** [IQSS/dataverse#9623]
Add minimal head/footer and content for landing page of https://gdc.dataverse.org

Use "Dataverse Data Commons"
Add Dataverse logo along with GDC logo on top left corner

**Comment by sekmiller** [comment]
Forked Repo added to IQSS. Minor modifications made as outlined above. Closing for now in favor of a subsequent ticket for an actual page design and deployment.
