### ISSUE TITLE
Add support issues at GDC website repo

### ISSUE THREAD

**Issue by sekmiller** [IQSS/dataverse#9626]
Add issues to GDC repo as outlined below

**Comment by sekmiller** [comment]
Outline of Custom Google Data Commons issues that we would like addressed for the Dataverse 

We provide the provenance json file with a URL in the format https://doi.org/xxxxx/xxx/xxxxxxx. The link that is provided with the graph or in the variable browser is simply doi.org. A user clicking on the link is properly brought to the Dataverse dataset as expected, but we would like the link to be displayed as dataverse.harvard.edu or the base url of any other installation that provides data to the GDC.One option could be to allow for another field in addition to the URL field, e.g. “Displayed url” or similar.
For the Data Download Tool, when data is selected across different Dataverse datasets, we are only seeing the url of the last variable selected in the provenance field, instead of multiple urls
We would like to be able to include description metadata as part of the Statistical Explorer. So to each import section, we would like to have the possibly to add a “Description” field that is exposed to Statistical Explorer
“Custom” variables should become “Dataverse”

**Comment by sekmiller** [comment]
https://github.com/datacommonsorg/website/issues/2744 provenance urls

**Comment by sekmiller** [comment]
Data Download Tool "Select Place Type" Bug

https://github.com/datacommonsorg/website/issues/2745

**Comment by sekmiller** [comment]
Add Description to Statistical Explorer tool:

https://github.com/datacommonsorg/website/issues/2746

**Comment by pdurbin** [comment]
Two responses came in yesterday:

- https://github.com/datacommonsorg/website/issues/2744#issuecomment-1710789970
- https://github.com/datacommonsorg/website/issues/2745#issuecomment-1710790863

**Comment by sekmiller** [comment]
3/12/2024 - we didn't get a chance to talk about these today, but I do have updates. I was able to close two of the issues: (https://github.com/datacommonsorg/website/issues/2744 and the one regarding labeling Variables - which I can't seem to find over there)

Also I spoke with my contact at GDC about the remaining open issues.

**Comment by cmbz** [comment]
2024/07/10
- Checking in on this item, any updates? @sekmiller

**Comment by sekmiller** [comment]
Only one issue remains - I will monitor separately.
