### ISSUE TITLE
Refactor Shibboleth code as ShibAuthenticationProvider

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#963]
As of this writing the Shibboleth logic is here: https://github.com/IQSS/dataverse/blob/master/src/main/java/edu/harvard/iq/dataverse/Shib.java

It should be refactored so we actually implement a ShibAuthenticationProvider: https://github.com/IQSS/dataverse/blob/master/src/main/java/edu/harvard/iq/dataverse/authorization/providers/shib/ShibAuthenticationProvider.java

I have questions for @michbarsinai about fitting what I've done into the model so I'm going to give this ticket to him for now to review what I've done. It sounds like he'd like to work on #954 first.

Also, so this doesn't fall through the cracks, every time a user logs in with Shib, we should update the AuthenticatedUser table with the latest info for that user.

**Comment by pdurbin** [comment]
> Also, so this doesn't fall through the cracks, every time a user logs in with Shib, we should update the AuthenticatedUser table with the latest info for that user.

Mentioned in [Shib FRD](https://docs.google.com/a/harvard.edu/document/d/12Qru8Gjq4oDUiodI00oObHJog65S7QzFfFZuPU3n8aU/edit?usp=sharing) and done in ad629e4

**Comment by scolapasta** [comment]
Discussed with @pdurbin and @michbarsinai and we decided that we don't think we need this.

Closing ticket and there is nothing to test (it was a code related issue).

**Comment by michbarsinai** [comment]
Re-opening, after talking with @pdurbin about this. This bag should be worked on after #3338 is implemented and merged.
