### ISSUE TITLE
Installation documentation: Apply feedback from Odum re: v3.6.2 install to make v4.0 doc better.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#964]
See RT #187327

The three documentation issues that were hurdles are listed below.  A seasoned web developer or Glassfish person might know these but the average user needs to have these in Docs.
1) You can not run install or deploy in read only mode for Database. I think we should suggest firewall restrictions during upgrades to prevent users from slipping in.
2) You MUST Undeploy in the GF Admin console prior to deploying on command line. The force did not work for me either.
3) You need to create the ~/docroot/guides directory prior to running install script OR fix the install script

**Comment by scolapasta** [comment]
Documentation for 4.0 is done, so closing this issue. If any specific issues arise relating, a new issue should be created.

Note: the installation has changed from 3.6 for 4.0, so the above tweaks are no longer relevant. For example, in 4.0 we don't currentl have read-only mode (will need to redocument once we reimplement). Also, the docs are no longer generated per installation, instead pointing to dataverse.org.
