### ISSUE TITLE
Filters for files in dataset page are gone

### ISSUE THREAD

**Issue by ErykKul** [IQSS/dataverse#9647]
**What steps does it take to reproduce the issue?**
Open a dataset with more than one file, the filters are gone (see "Filter by"):
![image](https://github.com/IQSS/dataverse/assets/101262459/75a10fff-8003-431f-9523-a34c0c60ef90)

* When does this issue occur?
When opening a dataset.

* Which page(s) does it occurs on?
Dataset page (files page fragment)

* What happens?
Filters for the files are gone.

* To whom does it occur (all users, curators, superusers)?
Everybody.

* What did you expect to happen?
Filters are there.

**Which version of Dataverse are you using?**
Develop.

**Any related open or closed issues to this bug report?**
#9558 

**Screenshots:**
You can cheat the page into showing the filters by providing a search term:
![image](https://github.com/IQSS/dataverse/assets/101262459/30c88cea-d108-4ae5-803c-f20ad2b28a51)

The facets will remain even after removing the search-term:
![image](https://github.com/IQSS/dataverse/assets/101262459/1e2f3c6f-e226-4aff-affd-b02df90d8f16)

I have found the code causing this and the fix for it. The PR will follow shortly.

**Comment by kcondon** [comment]
This works but a minor issue is that the filter doesn't appear right away when a draft is created -page needs to be refreshed. Is this because async not available at time of page init? I can merge as is since it is minor, just wanted to mention it.
