### ISSUE TITLE
Email validation failed

### ISSUE THREAD

**Issue by MarcosAnjos** [IQSS/dataverse#9648]
I'm having trouble validating my email

I receive the verification link in the email, but when I open it, it opens the dataverse page with an error message. As shown in the figure below.

Can someone help me.
![image](https://github.com/IQSS/dataverse/assets/32145970/8b8ebf8f-358c-42a4-9206-2bb30ef562b6)
![image](https://github.com/IQSS/dataverse/assets/32145970/76b3b23e-b1da-4130-a571-73e49d0f5ee5)
![image](https://github.com/IQSS/dataverse/assets/32145970/0a65d07f-1af2-4a38-b592-62a51817d983)

**Comment by MarcosAnjos** [comment]
@pdurbin  I was looking at the shared links. I identified that the URL com after I click on the confirmation email, the link it breaks because it adds a dot at the end of the URL.

Do you know where I could fix this bug.

![image](https://github.com/IQSS/dataverse/assets/32145970/f8e9d73e-fb5e-4e92-879e-4115ca8e0004)

**Comment by pdurbin** [comment]
I think you'd want to add a space between the URL and the dot (period) here:

```
notification.email.welcomeConfirmEmailAddOn="Por favor, verifique seu endereço de e-mail em {0}. 
```

https://github.com/GlobalDataverseCommunityConsortium/dataverse-language-packs/blob/bf09f8e067ed7d2334f979a2aaf728ed308cc512/pt_BR/Bundle_br.properties#L717
