### ISSUE TITLE
Add "Ask Dataverse" tool to Dataverse

### ISSUE THREAD

**Issue by sekmiller** [IQSS/dataverse#9663]
**Overview of the Feature Request**
Stefano is working on a tool that will enable users to ask natural language queries of Dataverse table files. The purpose of this issue is to make changes to the Dataverse App to accommodate this new type of tool. Per Stefano we are going to call it a query tool and use a chatbot icon on tabular files to indicate the availability of the tool. 

**What kind of user is the feature intended for?**
intended for guests for data exploration

**What inspired the request?**

**What existing behavior do you want changed?**

**Any brand new behavior do you want to add to Dataverse?**
Add an external tool for Dataverse natural language queries of data

**Any open or closed issues related to this feature request?**

**Comment by sekmiller** [comment]
{
  "displayName": "Ask Dataverse",
  "description": "A tool that allows you to ask question about Dataverse tables.",
  "toolName": "askDV",
  "scope": "file",
  "types": [
    "query"
  ],
  "toolUrl": "https://askdataverse.shinyapps.io/askdata",
  "contentType": "text/tab-separated-values",
  "httpMethod":"GET",
  "toolParameters": {
    "queryParameters": [
      {
        "fileId": "{fileId}"
      },
      {
        "datasetPid": "{datasetPid}"
      },
      {
        "siteUrl": "{siteUrl}"
      }
    ]
  }
}

**Comment by sekmiller** [comment]
{
  "displayName": "Ask Dataverse",
  "description": "A tool that allows you to ask question about Dataverse tables.",
  "toolName": "askDV",
  "scope": "file",
  "types": [
    "query"
  ],
  "toolUrl": "https://askdataverse.shinyapps.io/askdata",
  "contentType": "text/tab-separated-values",
  "httpMethod":"GET",
  "toolParameters": {
    "queryParameters": [
      {
        "fileId": "{fileId}"
      },
      {
        "datasetPid": "{datasetPid}"
      },
      {
        "siteUrl": "{siteUrl}"
      }
    ]
  }
}

**Comment by sekmiller** [comment]
{
  "displayName": "Ask Dataverse"",
  "description": "A tool that allows you to ask questions about Dataverse tables.",
  "toolName": "askDV",
  "scope": "file",
  "type": "query",
  "toolUrl": "https://askdataverse.shinyapps.io/askdata",
  "toolParameters": {
   "queryParameters": [
      {
        "fileId": "{fileId}"
      },
      {
        "datasetPid": "{datasetPid}"
      },
      {
        "siteUrl": "{siteUrl}"
      }
    ]
  }
}

**Comment by sekmiller** [comment]
{
  "displayName": "Ask Dataverse",
  "description": "A tool that allows you to ask questions about Dataverse tables.",
  "scope": "file",
  "type": "query",
  "toolUrl": "https://askdataverse.shinyapps.io/askdata",
  "toolParameters": {
    "queryParameters": [
      {
        "datasetPid": "{datasetPid}"
      },
      {
        "siteUrl": "{siteUrl}"
      },
      {
        "key": "{apiToken}"
      }
    ]
  }
}

**Comment by sekmiller** [comment]
```
{
  "displayName": "Ask Dataverse",
  "description": "A tool that allows you to ask questions about Dataverse tables.",
  "toolName": "askDV",
  "scope": "file",
  "types": [
    "query"
  ],
  "toolUrl": "https://askdataverse.shinyapps.io/askdata",
  "contentType": "text/tab-separated-values",
  "httpMethod":"GET",
  "toolParameters": {
    "queryParameters": [
      {
        "fileid": "{fileId}"
      },
      {
        "datasetPid": "{datasetPid}"
      },
      {
        "siteUrl": "{siteUrl}"
      }
    ]
  }
}
```

**Comment by kcondon** [comment]
Issues found:
1. When using the link, '''https://github.com/IQSS/askdataverse/blob/main/askthedata/askthedata.json''' for use in '''curl -X POST -H 'Content-type: application/json' http://localhost:8080/api/admin/externalTools --upload-file askthedata.json''' it really should point to the raw form, otherwise the contents are incorrect and the curl command will fail: '''https://raw.githubusercontent.com/IQSS/askdataverse/main/askthedata/askthedata.json'''
