### ISSUE TITLE
Metadata: Long/Lat Map UI instead of entering it in manually

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#969]
Change this field to be more user friendly

**Comment by pdurbin** [comment]
> Long/Lat Map UI instead of entering it in manually

This has definitely been talked about, usually during community meetings in the geospatial session.

**Comment by cmbz** [comment]
To focus on the most important features and bugs,     we are closing issues created before 2020 (version 5.0)     that are not new feature requests with the label 'Type: Feature'.    

If you created this issue and you feel the team     should revisit this decision, please reopen the issue and leave a comment.
