### ISSUE TITLE
Feature Request/Idea: Confirmation e-mail for file access request

### ISSUE THREAD

**Issue by CB-HAL** [IQSS/dataverse#9701]
**Overview of the Feature Request**
When a user requests access to a file, they do not receive a confirmation of the request.
As confirmation they can only see the blue bar “Access Requested”.
![grafik](https://github.com/IQSS/dataverse/assets/73164983/a212f883-a453-4fb8-88c9-2fe0bd87416c)
They only receive an e-mail after the request has been granted or rejected. 

**What kind of user is the feature intended for?**
User who requests access to a file.

**What inspired the request?**
A user who has sent an email and asked when the access will be enabled.

**Any brand new behavior do you want to add to Dataverse?**
User should receive a confirmation e-mail after access request or a pop-up window with the confirmation. User sometimes don’t see the blue bar, an additional e-mail or the pop-up windows makes it clearer that the process of access request was started. The confirmation text should be editable, as for access granted or denied.

In this context, the notification settings are also somehow unclear. 
![grafik](https://github.com/IQSS/dataverse/assets/73164983/8a5ef0ce-dce2-4d3b-afda-d7cde921ff7a)

**Comment by pdurbin** [comment]
@CB-HAL hi! I'm pretty sure the behavior is by design. It's easy for users to get overwhelmed by too many emails and in app notifications.

That said, these days, users have the the ability to mute notifications, as shown in the screenshot you posted (thanks). It's unclear? Maybe @ErykKul or @DieuwertjeBloemen (who developed that feature) can help.

**Comment by qqmyers** [comment]
FWIW: I think the Access to File Requested notification that can be turned off is one to the dataset contacts (not one to the requestor). One thought I had is perhaps it would make sense to cc the requestor on that email rather than have a separate notification/email? (Since Dataverse has a setting to hide contact email addresses, we might have to consider whether cc'ing the user makes sense in that case (as they'd then see the contact's email addresses), but cc'ing does have the advantage of setting up a means for the contacts and requestor to interact.)

**Comment by CB-HAL** [comment]
For a "normal" user (a user who only wishes to download data) there are not many notifications in use. A cc to the requestor would be in my opinon not a good solution, for the requestor would be a specific text necessary.

Ad notifiaction: in the first moment it's not clear who is the addressee of this notification, The description of all notification  should be clearer. Users who are not so familiar with Dataverse are lost with this short description.

**Comment by pdurbin** [comment]
Yeah, it makes sense. So the email might say...

"You have successfully requested access to [FILE]. Someone will review the request and you'll get another notification about if it has been granted or denied."

It might get annoying if you request access to hundreds of files at once, though. 🤔

**Comment by CB-HAL** [comment]
Hundreds of datasets is generally annoying for everyboy involved: The horror!

**Comment by mdmADA** [comment]
To add to the discussion:

I modified ADA's dataverse code to send a detailed email per access request to ADA (the user's dataverse details and the guestbook response details are appended to the bare bones Dataverse email).

So if the user requests 10 files in one dataset, there is only one email sent to the dataset contact (99% of the time this is ADA).

If the user goes back and requests 10 other files from the same dataset, then only one additional email is sent for that request. (If the details are not the same as in the first request, the ADA access team will have to resolve that with the requester).

I am not sure how newer functionality (collections, etc.)  will influence requests in comparison to ADA's 4.6.1 workflows and will have to investigate that further.

**Comment by DieuwertjeBloemen** [comment]
A bit more information on the current notification/email setting: They are indeed for the emails/notifications that are sent out to the 'owner' of the dataset once someone requests access (so not the requester). However, to slightly correct Jim in his earlier response, those emails don't go to the dataset contacts as set in the metadata, but rather to all the users that have the right to grant access for that particular dataset. E.g. At KU Leuven, we have a curation workflow, and only the curators have the rights to grant access in Dataverse in that set-up, not contributors. So, we always have to forward to the contact adresses to get their approval.
A small detail, but might be relevant to keep in mind in your workflows.

**Comment by CB-HAL** [comment]
A good idea would also be a notification/email when data access is revoked.

**Comment by pdurbin** [comment]
Ooo, that would make 'em mad. 😡 How dare you revoke my access!

**Comment by CB-HAL** [comment]
Access to restricted data is bound to terms with a project duration, after the project period has expired, user should get an e-mail notification: "According to the terms you have to erase all stored data from your personal computer and all devices of the puporse for which the data had been requested." And of course everyone will then delete the data, or the computer will destroy itself

**Comment by pdurbin** [comment]
@CB-HAL sure. Makes sense. Did you mean to close this issue? 🤔 There seems to be a fair amount of interest in it. 😄
