### ISSUE TITLE
Document new previewers: GeoTIFF and ESRI Shape Previewer

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#9704]
Added in https://github.com/gdcc/dataverse-previewers/pull/36

The PR should be similar to this one:

- #9600

@schorcht-ioer are you interested in making a pull request? Thanks for the previewers!! 🚀

**Comment by schorcht-ioer** [comment]
ok @pdurbin, the PR for adding informations to the guide is done, see: #9723
