### ISSUE TITLE
Support OIDC with PKCE

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#9709]
As explained in both the [summary](https://docs.google.com/document/d/19pbENuYyHErEmblbFGQ47_uJpTfqVKbn9O0QftVqeeU/edit?usp=sharing) and [auth doc](https://docs.google.com/document/d/1624KuPj4zp_TQzWivqaNY3YUCzibwFib8tZUz_IshTo/edit?usp=sharing) we recently[ released](https://groups.google.com/g/dataverse-community/c/2hfhWIHQddE/m/hATuWGGSAAAJ), we plan to support OIDC with [PKCE](https://www.rfc-editor.org/rfc/rfc7636) (pronounced "pixy"): Proof Key for Code Exchange.

As part this effort we will also remove the [api-session-auth](https://preview.guides.gdcc.io/en/develop/installation/config.html#feature-flags) feature flag and the code behind it.

**Comment by poikilotherm** [comment]
As I also explained on Slack, the PKCE support within backend is covered by #8349 / #9273 . That PR is waiting for a review and getting merged, but probably will only make it into 6.1? I have a feeling this issue may be a duplicate of #8349.

**Comment by pdurbin** [comment]
I'm closing this issue.

I was trying to capture the idea of removing the api-session-auth feature (what we would need in its place) but in the end I simply fixed the guides to stop linking to a closed issue:

- #9710

Someday we'll need the issue I was trying to create but let's cross that bridge when we come to it.
