### ISSUE TITLE
File Card: Icon for tabular data

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#971]
@mcrosas will talk to @tercer about this

**Comment by scolapasta** [comment]
@tercer could you please give as an update on where this stands?

**Comment by tercer** [comment]
Expect it to take a further week of work.  Don't currently have it as a priority on list of tasks for current projects.  Can give some placeholding code that gives very crude image as a function of data if useful for integration.
James

--
James Honaker, Senior Research Scientist
//// Institute for Quantitative Social Science, Harvard University
________________________________

**Comment by mcrosas** [comment]
Moved to Beta 15.

**Comment by pdurbin** [comment]
If we really wanted this I suspect we would have implemented it by now. Vote to close.

**Comment by pdurbin** [comment]
Closing.
