### ISSUE TITLE
[Spike - API] [2/2] Extend the Files API to support filters

### ISSUE THREAD

**Issue by GPortas** [IQSS/dataverse#9714]
**Overview of the Feature Request**

The logic to be implemented will extend https://github.com/IQSS/dataverse/issues/9692 so that the API is also capable of filtering files by file type, access type and tags.

**What kind of user is the feature intended for?**
API User

**What inspired the request?**
- https://github.com/IQSS/dataverse-frontend/issues/150

**What existing behavior do you want changed?**
N/A

**Any brand new behavior do you want to add to Dataverse?**
Extend Files API

**Any open or closed issues related to this feature request?**
- https://github.com/IQSS/dataverse-frontend/issues/150

**Comment by pdurbin** [comment]
Closing because this PR was merged:

- #9783
