### ISSUE TITLE
Create Account: Terms of Use Click Through

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#972]
When a user creates a new account, they need to agree to the terms of use. We already have this built and is being used for Shibboleth log ins so we need to take that code and put it in the create local account workflow.

@mheppler can you do this or does there need to be some help from a developer first?

**Comment by pdurbin** [comment]
@eaquigley can you please clarify how these Terms of Use are entered in the first place? I'm not sure where they are stored in the database.

**Comment by eaquigley** [comment]
@pdurbin Where did you store them for shibboleth? Also, I can't remember but do you have the official text and not the Lorem Impsum? If not, @posixeleni and I can get that to you since Berkman finalized them.

**Comment by pdurbin** [comment]
@eaquigley I don't store them anywhere. Nothing is in the database that I'm aware of. The first time you log into Shibboleth you simply see the placeholder test hard-coded on that page: https://github.com/IQSS/dataverse/blob/master/src/main/webapp/shib.xhtml

It looks like this the Lorem Ipsum at http://datascience.iq.harvard.edu/blog/try-out-single-sign-shibboleth-40-beta

I guess the bigger question is, what is the user experience supposed to be of entering and editing this data? Is it supposed to be in the JSON when the root dataverse is created? Where do you edit it in the UI?

**Comment by eaquigley** [comment]
@scolapasta where should the terms of use for account creation be stored? this is something that individual installations will need to be able to edit and insert their own terms of use for their installation.

**Comment by posixeleni** [comment]
Checking with Berkman if we can apply our standard Account Terms of Use or if we need API Terms of Use.

**Comment by eaquigley** [comment]
The Terms of Use will be in both the database (settings table) as well as available in the documentation that lives in the Sphinx folder for Dataverse. Waiting for the finalized doc from Berkman Center.

**Comment by pdurbin** [comment]
> The Terms of Use will be in both the database (settings table)

It can be stored in the setting table as of 44e46611186fabe83d781d5cd3188e883cb5430f with this:

    curl -X PUT -d@/tmp/apptos.txt http://localhost:8080/api/s/settings/:ApplicationTermsOfUse

@eaquigley said that she or @posixeleni will be providing the text file, probably in HTML format since the 10 page word document has nice formatting.

Before that commit the settings table could only handle 1024 characters so per @scolapasta we changed it to the "text" datatype. To avoid dropping your database, you can run this:

    ALTER TABLE setting ALTER COLUMN content TYPE text;

**Comment by pdurbin** [comment]
@mheppler I'm giving this ticket to you to help with the design and UI side of the house. I just consolidated the application-wide Terms of Use markup into the old termsofuse.xhtml you set up long ago. That file is now include both by "Sign Up" and "Shib" but I need to show you how to work on Shib locally. In short, this is what you need to do (but I'll walk you and hopefully @scolapasta through this):

Temporarily change one of the values below to true (please don't commit this change) in Shib.java and then go to http://localhost:8080/shib.xhtml

// set one of these to true in dev to avoid needing Shibboleth set up locally
boolean devRandom = false;
boolean devConstantTestShib = false;
boolean devConstantHarvard1 = false;
boolean devConstantHarvard2 = false;

**Comment by pdurbin** [comment]
> I need to show you how to work on Shib locally

@mheppler if you pull the latest you don't need to mess with Shib.java any more. Please see this for how to change Shib modes on the fly: http://guides.dataverse.org/en/latest/developers/dev-main.html#shibboleth

**Comment by mheppler** [comment]
Cleaned up the workflows for Shibboleth Account Converting and the Terms of Use on the Sign Up page.

**Comment by pdurbin** [comment]
> curl -X PUT -d@/tmp/apptou.html http://localhost:8080/api/s/settings/:ApplicationTermsOfUse

@kcondon suggested that this should go in the installers guide somewhere.

**Comment by kcondon** [comment]
OK, I see the TOU on account create, though currently with placeholder text. It also appears on the change password page so entered a ticket for that.

@eaquigley I think the message when the TOU is not checked is not that great and it removes your password:

Validation Error – Required fields were missed or there was a validation error. Please scroll down to see details. 

@eaquigley The checkbox is red but is that enough if I'm color blind or just grouchy? Passing to Liz for comment. All other required fields have their own sub message.

**Comment by eaquigley** [comment]
@kcondon I definitely think it should remove the password. I do agree that the red checkbox is not enough. @scolapasta @pdurbin can we have that entire area be shown in red?

**Comment by kcondon** [comment]
Couldn't it just have an error like all the other requred fields?
________________________________

**Comment by scolapasta** [comment]
The message text was there, but there was no display on the page. So I added that and it now shows up. (the whole area is red is not doable, but with the message it is now obvious)

I left the message text as it was; it is in the bundle if you want to change it. (note the terms xhtml is used by multiple places, but I think the message can be the same for all)

**Comment by mheppler** [comment]
I am making a separate ticket for the Terms of Use field needing a required asterisk -- #1535. There seems to be a lot going on in this ticket, and I don't want to pile on.

**Comment by eaquigley** [comment]
@kcondon passing this back to you to test and see if the fixes are now working.

**Comment by sbarbosadataverse** [comment]
The asterisk is available, but perhaps move it down by the checkbox, and it is functioning as per screen shot attached:

https://www.dropbox.com/s/hddrqm43gzsz6r9/Screenshot%202015-03-18%2015.56.36.png?dl=0

**Comment by pdurbin** [comment]
> @kcondon suggested that this should go in the installers guide somewhere.
> [Kevin] Actually you suggested it and I agreed.

Whoops, we never documented this. I just did in a2109dc in the 4.3 branch after reading this post on the mailing list: https://groups.google.com/d/msg/dataverse-community/ziGFSMCmEDA/9EDQYn7yBwAJ
