### ISSUE TITLE
Feature Request/Idea: Investigate status of Crossref Funder Registry, review alternatives for retrieving and recording funder metadata

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#9720]
During a recent NIH GREI meeting, John Chodacki at CDL mentioned that the Crossref Funder Registry is being deprecated. We should find out why and when and how this affects the work done recently to let users choose funder names from the Crossref Funder Registry (https://github.com/IQSS/dataverse/issues/9150).

**Comment by pdurbin** [comment]
Perhaps we could use ROR (Research Organization Registry) instead to look up funders. @qqmyers already did some great using ROR to look up Author Affiliation in this PR:

- #9402

**Comment by jggautier** [comment]
Right, yeah. Dryad let us know they're switching from Crossref Funder Registry to ROR for collecting funder names. And I'd guess that the NIH GREI ROR working group will be talking about using RORs for funders, too.

**Comment by pdurbin** [comment]
@adam3smith just let us know about the official announcement: https://www.crossref.org/blog/open-funder-registry-to-transition-into-research-organization-registry-ror/ (thanks!)

**Comment by cmbz** [comment]
2024/01/30
@jggautier Can this issue now be closed, or is there more work to do. (And if so, where is that work described and being tracked?)

**Comment by jggautier** [comment]
Yeah, I think it can be be closed. During the prioritization meeting last week, @sbarbosadataverse said that it was decided to not use the Crossref Funder Registry and to use ROR instead. And during a ROR meeting this morning folks from ROR said that coverage of Funder Registry entries in ROR was now over 95%, which I think is pretty good evidence that ROR will be a great to use.

@qqmyers worked on using the Funder Registry for the controlled vocabulary functionality that we were planning to use so that people adding funding metadata can choose funder names from Funder Registry (https://github.com/IQSS/dataverse/issues/9150). We'll need to revisit that work, in addition to other plans that mention the Funder Registry, such as https://github.com/IQSS/dataverse-pm/issues/19, and plans that come out of the research we're doing, being tracked in https://github.com/IQSS/dataverse/issues/10196 and https://github.com/IQSS/dataverse/issues/4859, to help us understand how best to improve how Dataverse collects and distributes funder metadata so that it's more usable.
