### ISSUE TITLE
Inconcistency between documentation and code regarding required permission for linking datasets

### ISSUE THREAD

**Issue by vera** [IQSS/dataverse#9724]
Documentation states the required permission is "Add dataset":

https://github.com/IQSS/dataverse/blob/e67dad04d1b5680782c2c1557f9412db7cda6d84/doc/sphinx-guides/source/user/dataverse-management.rst?plain=1#L215

` In order to link a dataset, you will need your account to have the "Add Dataset" permission on the Dataverse collection that is doing the linking. If you created the Dataverse collection then you should have this permission already, but if not then you will need to ask the admin of that Dataverse collection to assign that permission to your account. You do not need any special permissions on the dataset being linked. `

However, that doesn't work. The code requires "Publish dataset":

https://github.com/IQSS/dataverse/blob/e67dad04d1b5680782c2c1557f9412db7cda6d84/src/main/java/edu/harvard/iq/dataverse/DataverseServiceBean.java#L538

One of them should be updated.

I think requiring the "Publish dataset" permission makes more sense than "Add dataset", since the linking immediately causes the dataset to become publicly visible in the dataverse it is being linked in, if I understand correctly.

However, I think it would make sense to create a new separate "Link dataset" permission. To my mind, deciding a publication request and linking already published datasets to a new dataverse are two different things.

**Comment by pdurbin** [comment]
> I think requiring the "Publish dataset" permission makes more sense than "Add dataset", since the linking immediately causes the dataset to become publicly visible in the dataverse it is being linked in, if I understand correctly.

Yes, I agree. Do you want to create a PR to update the guides? Thanks for catching this!

For extra credit... we do have some tests in this area like this:

```
// A dataset cannot be linked to the same dataverse again.
Response tryToLinkAgain = UtilIT.linkDataset(datasetPid, dataverse2Alias, superuserApiToken);
tryToLinkAgain.prettyPrint();
tryToLinkAgain.then().assertThat()
        .statusCode(FORBIDDEN.getStatusCode())
        .body("message", equalTo("Can't link a dataset that has already been linked to this dataverse"));```
```

If you want, you could add a test to demonstrate that "Add Dataset" isn't enough.

That test above is here: https://github.com/IQSS/dataverse/blob/v5.13/src/test/java/edu/harvard/iq/dataverse/api/LinkIT.java
