### ISSUE TITLE
"External Metadata Filtering" improvements. 

### ISSUE THREAD

**Issue by landreev** [IQSS/dataverse#9727]
Opening the issue per conversation with @cmbz and @siacus. 
This is based on the tech. discussion in the spike issue in the local queue: https://github.com/IQSS/dataverse.harvard.edu/issues/221

Per conversations with the IQSS support team, we are going to implement some changes to how the external metadata checks are performed, to make their life easier and have fewer upset users contact them. Most of these changes will be done on the side of the filter, i.e. outside of the Dataverse source tree. But this issue is for any hooks that may need to be added to the application code.

**Comment by cmbz** [comment]
- Adding size 3 and moving to Sprint Ready as per conversations with @landreev @scolapasta and @siacus 
- Note that this issue does not contain code that involves the application, therefore the 5.14 release can proceed without it. The 5.14 milestone is here in case there are other minor spam-handling modifications that can be included in 5.14.

**Comment by landreev** [comment]
I have added some extra info to the json that Dataverse sends over to the filter, for the latter to be able to whitelist more intelligently. This may be all that's needed to be added to the application code in 5.14 in order to deliver the improvements for the support team. I'll see if I can think of anything else and will make a PR on Monday.
