### ISSUE TITLE
Data Deposit API: Contributor Type can be changed 

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#973]
Using the Data Deposit API, a metadata field with a controlled vocabulary can be changed without an error being thrown. For example, the contributor type field has funder as an option. In the API you can change it from funder to smurffunder and it will save the dataset with that.

**Comment by scolapasta** [comment]
#rtreacy - is this fixed now that that import goes through the Json?

**Comment by rtreacy** [comment]
The new json based importXML has been incorporated into ContainerManageImpl and CollectionDepositManagerImpl.

**Comment by pdurbin** [comment]
> The new json based importXML has been incorporated into ContainerManageImpl and CollectionDepositManagerImpl.

That commit was 2467468 and after it I can't edit datasets via SWORD, which I reported in #1554

Locally, I backed up to the commit before (811fd5b) and I **can** edit datasets with SWORD.
