### ISSUE TITLE
No validation of which primitives are allowed in a compound field

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#974]
With a tweak to https://github.com/IQSS/dataverse/blob/master/scripts/search/data/dataset01-create-new.json I'm able to add "Identifier" to the "Contributor" dataset field with the bit of JSON below. The GUI guides the user in which primitive fields are allowed in compound fields but it seems like this in not enforced with any sort of validation? Very strange. Screenshot below. The "Contributor" field should only allow "Type" and "Name". This should not be allowed:

![compoundvalidation](https://cloud.githubusercontent.com/assets/21006/4685661/c3730da2-563c-11e4-8fdc-edccff8c15f2.png)

`curl -s -X POST -H Content-type:application/json -d @scripts/search/data/dataset01-create-new.json 'http://localhost:8080/api/dvs/12/datasets/?key=5fa1ae77-40cb-4c3f-a9d4-61a91e48af7e`

          {
            "value": [
              {
                "contributorName": {
                  "value": "MyContributor",
                  "typeClass": "primitive",
                  "multiple": false,
                  "typeName": "contributorName"
                },
                "otherIdValue": {
                  "value": "adding an identifer to a contributor",
                  "typeClass": "primitive",
                  "multiple": false,
                  "typeName": "otherIdValue"
                }
              }
            ],
            "typeClass": "compound",
            "multiple": true,
            "typeName": "contributor"
          }

**Comment by kcondon** [comment]
OK this fails properly now, shows message: 
{"status":"ERROR","message":"Error parsing initialVersion: Exception while parsing field of type: contributor"}

Tried with another compound field, same behavior.

Closing.
