### ISSUE TITLE
add UBC's Dataverse Utilities to Guides

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#9760]
from Paul Lesack on the [community list](https://groups.google.com/g/dataverse-community/c/o64iIU7hi1g/m/HQIGJPlwCwAJ):

"Hi everyone,

I'm not exactly sure how to let everyone know about this, but there's (yet) another set of Dataverse utilities available.

https://ubc-library-rc.github.io/dataverse_utils/
https://pypi.org/project/dataverse-utils/

They were mostly developed for use with UBC's dataverse instance, but you never know who may find these things useful.

If anyone wants to add them to <https://guides.dataverse.org/en/5.14/api/client-libraries.html>, please feel free.

Sincerely,

Paul Lesack
University of British Columbia Library"

**Comment by pdurbin** [comment]
Yes, fantastic idea to add this to the guides!

Thanks, @plesubc!
