### ISSUE TITLE
switch PR jobs to Payara6

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#9765]
this is temporary while we're transitioning, and will only affect IQSS-Dataverse-Develop-PR jobs.

**Comment by poikilotherm** [comment]
@donsizemore thanks for all the work on this! Is this closable now that we run jobs on Jenkins with P6? Kudos again for all your help!

**Comment by pdurbin** [comment]
Yes, I'm pretty sure this can be safely closed. @donsizemore can you please confirm?
