### ISSUE TITLE
DOCKER> unknown flag: --driver with M1 Mac

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#9771]
I'm opening this issue on behalf of @sekmiller who unfortunately is not having a great first time experience with Docker. 😅 

He's using Docker 4.22.0 (117440). He's on an M1 Mac.

He's on the Payara 6 branch as of this commit: https://github.com/IQSS/dataverse/pull/9685/commits/0133009d5e705af3d9ea05ac12ac9f59fdfd26e5

When he tries to build the (Payara 6) base image with `mvn -Pct -f modules/container-base install`, he gets this:

`[INFO] DOCKER> [gdcc/base:unstable] “base”: Created docker-build.tar in 3 seconds`
`[INFO] DOCKER> docker --config /Users/stephenkraffmiller/Documents/GitHub/modules/container-base/target/buildx-state buildx create --driver docker-container --name maven`
`[INFO] DOCKER> unknown flag: --driver`

(This works for me on my M2 Mac at home.)

He also saw this on the Java 17 branch as of https://github.com/IQSS/dataverse/pull/9764/commits/7274eefc95c2fa5b2117fe7211b99d6f96f3af58

This GitHub issue stuck out for me:

- "Presence of the --config flag, causes the build to fail with unknown flag: --driver" -- https://github.com/fabric8io/docker-maven-plugin/issues/1678

@poikilotherm found this one:

- https://github.com/docker/for-mac/issues/6928

Afterward, @sekmiller tried adding `-Dfabric8-dmp.version=0.43.2` but it didn't help.

See also Slack discussion at https://iqss.slack.com/archives/C010LA04BCG/p1691592583014789

**Comment by pdurbin** [comment]
> He also saw this on the Java 17 branch as of [7274eef](https://github.com/IQSS/dataverse/commit/7274eefc95c2fa5b2117fe7211b99d6f96f3af58)

I just tried on my M2 Mac (same commit) and it worked fine. I wonder what the difference is. 🤔 

I'm on Docker version 20.10.23, build 7155243

Docker Desktop version 4.17.0 (99724)

If it matters, macOS 13.4.1 (c) (22F770820d)

**Comment by poikilotherm** [comment]
@sekmiller @pdurbin y'all could try https://github.com/fabric8io/docker-maven-plugin/releases/tag/v0.43.3 via `-Dfabric8-dmp.version=0.43.3`. They might have just added a workaround.

**Comment by pdurbin** [comment]
Thanks, I added it to the thread: https://iqss.slack.com/archives/C010LA04BCG/p1692010453029759?thread_ts=1691592583.014789&cid=C010LA04BCG

**Comment by poikilotherm** [comment]
While 0.43.3 fixed the problem on @sekmiller 's M1, it causes failure when pushing preview images to GHCR.

Opened a bug report at DMP's https://github.com/fabric8io/docker-maven-plugin/issues/1701

**Comment by wanieldilson** [comment]
This seems fixed in `0.43.3` but broken again in `0.43.4`

**Comment by pdurbin** [comment]
I'm seeing this problem on my non-M1 Mac (Intel chip, that is). I'm using 0.43.4 (develop branch, 960751f743). I started this thread about it:

https://dataverse.zulipchat.com/#narrow/stream/375812-containers/topic/unknown.20flag.3A.20--driver/near/404949182

**Comment by pdurbin** [comment]
`mvn -Pct -f modules/container-base install -Dfabric8-dmp.version=0.43.3` worked! Interesting.

**Comment by grnadav** [comment]
I'm getting this issue on my non-M1 mac (and NOT getting it on M1), @pdurbin 's proposal did not work for me.
using version 0.43.4

**Comment by pdurbin** [comment]
@grnadav hmm, maybe try downgrading to 0.43.3?

**Comment by grnadav** [comment]
Yes, it didn't work.
My current workaround is to add -Ddocker.platforms= when running on my Intel machine to disable buildx

**Comment by pdurbin** [comment]
@grnadav I heard 0.44 is out. Would you like to try it? 😄

**Comment by poikilotherm** [comment]
Trying it out is easy: just go for `mvn -Pct -f modules/container-base install -Dfabric8-dmp.version=0.44`

**Comment by grnadav** [comment]
Oh nice, didn't notice the release (I'll subscribe for future).
I'll give it a try and update

**Comment by pdurbin** [comment]
I'm reopening this issue.

We ended up staying on 0.43.4.

We tried 0.44.0 but it didn't work on Mac.

I just tried 0.45.0 (released two days ago) and it seems to work. I'm making a pull request to upgrade to it.
