### ISSUE TITLE
Payara 6: Embargo selection fails from Dataverse page, works from file page.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#9773]
Found while testing Payara 6 branch: https://github.com/IQSS/dataverse/pull/9685 
Selecting embargo from the dataset page, either from the individual file kebab or the edit files menu, results in a popup that says selected files are already published and cannot be embargoed, along with a stack trace. The popup and stack trace appear to be the same in both cases.
<img width="596" alt="Screen Shot 2023-08-11 at 9 31 55 AM" src="https://github.com/IQSS/dataverse/assets/4983816/289ab663-013d-4ffe-bbb2-a3adb3688c71">
[embargo_fail_datasetpg_editfiles.txt](https://github.com/IQSS/dataverse/files/12322026/embargo_fail_datasetpg_editfiles.txt)
[embargo_fail_datasetpg_file_kebab.txt](https://github.com/IQSS/dataverse/files/12322027/embargo_fail_datasetpg_file_kebab.txt)

Selecting embargo from the files page, edit files button, works but shows the same stack trace in the logs
[embargo_success_filepg_editfile.txt](https://github.com/IQSS/dataverse/files/12322031/embargo_success_filepg_editfile.txt)

So, it seems like the failure is initializing the popup due to null, but for some reason the error handling from the file page allows it to proceed anyway but from the dataset page it seems to go to an incorrect, perhaps default error?

**Comment by scolapasta** [comment]
I thing I noticed is that if you then click the embargo a 2nd time, it does show the "correct" popup.  but this also happens if you click on a file that is already published - that is it shows the popup that would be correct for the "previous" file. So something is getting initiallzed late. (possibly due to the error in the stack trace?)
