### ISSUE TITLE
Payara 6: Move all dependencies to stable jakartified versions

### ISSUE THREAD

**Issue by poikilotherm** [IQSS/dataverse#9778]
- [ ] SWORD2 lib needs a release and no snapshot
- [ ] XOAI lib needs a release and no snapshot
- [ ] Rewrite? (Is Alpha1. See also ocpsoft/rewrite#345 and #9770 
- [x] Titanium JSON-LD
- [x] Primefaces
- [x] Check `mvn dependency:tree` for any leftovers of Java EE in transitional dependencies to avoid surprises
- [ ] Check if Duracloud reportdata XML binds are problematic
- [ ] Check if Google Cloud Storage annotations usage is problematic
- [ ] Check upgrading to SLF4J 2.0. [There was an issue with Payara 6 before.](https://github.com/payara/Payara/issues/5898) @ErykKul saw problems, too, he mentioned [payara#5989](https://github.com/payara/Payara/issues/6211) (which was autoclosed) in #9426

**Comment by poikilotherm** [comment]
Looking at the dependency tree, there are two potentially broken `javax` dependencies:

1. Duracloud `reportdata` uses XML binding (`javax.xml.bind`)
2. Google Cloud Storage uses `javax.annotations`

@qqmyers are these code paths used by us? Can we test for those?

**Comment by qqmyers** [comment]
Those are both in archivers. Duracloud is used by Texas and could probably be tested with them. The Google archiver is used by QDR and could be tested with them or by anyone with a Google account. FWIW, QDR already uses different google dependencies than the main branch - it might be a good quick test to upgrade to those and see if the javax issues are still in what's pulled in.

**Comment by cmbz** [comment]
Action: 
- Split this issue into several issues and size each
- Team uses issues as learning opportunity, consulting with @qqmyers and @poikilotherm as needed to make progress and ensure that other stakeholders are not unduly affected by changes
- Contact @poikilotherm to confirm sizing for each issue

**Comment by pdurbin** [comment]
Specifically we talked about taking these two items...

- SWORD2 lib needs a release and no snapshot
- XOAI lib needs a release and no snapshot

... and creating an issue to document in the dev guide how to release these to Maven Central. It would be a learning opportunity for someone (or someones) on the team. We'll need the password, of course.

**Comment by pdurbin** [comment]
I created a number of sub issues:

- #9804
- #9805
- #9806
- #9807
- #9808
- #9809
- #9810

Closing.

**Comment by poikilotherm** [comment]
FWIW: I looked into the potential SFL4J thing. It doesn't seem to be an issue anymore! So I never created an issue for it.
