### ISSUE TITLE
Consider using Character.isXXX

### ISSUE THREAD

**Issue by michbarsinai** [IQSS/dataverse#978]
at https://github.com/IQSS/dataverse/blob/master/src/main/java/edu/harvard/iq/dataverse/util/StringUtil.java#L27

Not sure what are the requirements here. is it only English letters and digits, or digits in general (i.e. including accents, ç, ß?)

**Comment by pdurbin** [comment]
@michbarsinai https://github.com/IQSS/dataverse/blob/master/src/main/java/edu/harvard/iq/dataverse/util/StringUtil.java#L27 doesn't point to the right line any more. Please link to a commit or tag. Thanks.

**Comment by pdurbin** [comment]
@michbarsinai I'm closing this issue. I don't feel that having it open provides much value to the Dataverse community.
