### ISSUE TITLE
[Spike - API] Extend the Files API to support search

### ISSUE THREAD

**Issue by GPortas** [IQSS/dataverse#9785]
**Overview of the Feature Request**

The logic to be implemented will extend https://github.com/IQSS/dataverse/issues/9714 so that the API is also capable of filtering files by search criteria.

**What kind of user is the feature intended for?**
API User

**What inspired the request?**
- https://github.com/IQSS/dataverse-frontend/issues/150
- https://github.com/IQSS/dataverse-frontend/issues/135

**What existing behavior do you want changed?**
N/A

**Any brand new behavior do you want to add to Dataverse?**
Extend Files API

**Any open or closed issues related to this feature request?**
- https://github.com/IQSS/dataverse-frontend/issues/135

**Comment by pdurbin** [comment]
Closing because the following PR was merged:

- #9820
