### ISSUE TITLE
Payara 6: Log errors related to decoding flash data from cookies.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#9800]
Log entries related to flash and cookies. Not sure yet when they happen, happens sporadically. No apparent user impact: [2023-08-18T14:18:31.624+0000] [Payara 6.2023.8] [SEVERE] [faces.externalcontext.flash.bad.cookie] [jakarta.enterprise.resource.webcontainer.faces.flash] [tid: _ThreadID=99 _ThreadName=http-thread-pool::jk-connector(1)] [timeMillis: 1692368311624] [levelValue: 1000] [[
JSF1094: Could not decode flash data from incoming cookie value Invalid characters in decrypted value. Processing will continue, but the flash is unavailable for this request.]]

**Comment by yaof22** [comment]
I also see it in , how to reappear it? and the reason is what? @kcondon

**Comment by pdurbin** [comment]
@yaof22 we are unlikely to fix this because we are moving from JSF to a new React UI at https://github.com/IQSS/dataverse-frontend . At some point all the JSF code will be removed, along with this bug. 😄
