### ISSUE TITLE
release XOAI library 5.1.0

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#9802]
And docs about how to make a release.

Compile for Java 11. Keep target version as 11. Go ahead and try with Java 17 target.

Library side:

- merge renovate bot PRs to main:
- Bump to 5.1.0 because we already have a 5.0.0 (non snapshot).
- make release

On Dataverse side:

- update to 5.1.0
- After SWORD is done, remove snapshot repository

**Comment by poikilotherm** [comment]
Just released v5.1.0. Will create PR to adapt Dataverse.
