### ISSUE TITLE
Payara 6: Server log error when running harvest client, harvest continues to work.

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#9809]
Server log error when running harvest client, seems to work anyway:
[harvest_client_svr_log_err.txt](https://github.com/IQSS/dataverse/files/12383213/harvest_client_svr_log_err.txt)

**Comment by scolapasta** [comment]
Adding to 6.0 either to fix or to determine that we won't fix for this release.

**Comment by kcondon** [comment]
Confirmed it happens with p5 when failing to harvest 1 or more datasets. Does not happen when all succeed.
