### ISSUE TITLE
Trying to create dataset in collection with certain default dataset templates returns error page

### ISSUE THREAD

**Issue by jggautier** [IQSS/dataverse#9825]
**What steps does it take to reproduce the issue?**

* When does this issue occur?
On a collection that has a default template with certain metadata fields filled, click on Add Data, and New Dataset. For example, the collection at https://dataverse.harvard.edu/dataverse/worldfish has a default dataset template. When I try to create a dataset in that collection, the issue occurs. I've also done more testing on Demo Dataverse with collections and different dataset templates with the same results.

* Which page(s) does it occurs on?
Dataverse collection pages

* What happens?
I'm taken to an error page:

  <kbd><img width="764" alt="Screenshot 2023-08-23 at 12 48 45 PM" src="https://github.com/IQSS/dataverse/assets/18374574/31008c47-4640-43e7-850b-6cf1c7071cb8"></kbd>

* To whom does it occur (all users, curators, superusers)?
Users with permission to create datasets in the collection

* What did you expect to happen?
We're taken to the page where we can add metadata and upload files.

  Or maybe the error page lets us know what's wrong with the dataset template that the dataset is trying to use so that we can fix the template. Maybe this has something to do with how certain fields in the template are filled or not filled?

**Which version of Dataverse are you using?**
v5.14

**Any related open or closed issues to this bug report?**
None that I could find

**Comment by scolapasta** [comment]
The specifc error from the logs:
```
java.lang.NullPointerException
	at edu.harvard.iq.dataverse.dataset.DatasetUtil.getLicenseURI(DatasetUtil.java:587)```

**Comment by sbarbosadataverse** [comment]
@scolapasta more reports of this today, fyi with ajps.
