### ISSUE TITLE
Shellspec jobs and workflows fail because no MacOS (10.15) runner is available

### ISSUE THREAD

**Issue by bencomp** [IQSS/dataverse#9829]
**What steps does it take to reproduce the issue?**

* When does this issue occur?
This happens on GitHub Actions when the *Shellspec* workflow is triggered through a push or pull request.

* Which page(s) does it occurs on?
n/a

* What happens?
The Ubuntu and CentOS jobs succeed in less than 30s, but the MacOS job is queued for 1.5 day and then automatically fails because no runners are available.
I am pretty sure the cause is that the job is specified to run on `macos-10.15` runners, which are not listed under [Choosing a GitHub-hosted runner](https://docs.github.com/en/actions/using-jobs/choosing-the-runner-for-a-job#choosing-github-hosted-runners). MacOS 10.15 is end-of-life.

* To whom does it occur (all users, curators, superusers)?
Developers who look at workflow runs or who receive emails that a job has failed.

* What did you expect to happen?
The MacOS job should pass as well.
(This could be another issue, but it looks like newer commits on a branch do not cancel pending/queued jobs. I would expect that jobs are cancelled when a commit is outdated.)

**Which version of Dataverse are you using?**
The develop branch, or a feature/fix branch based off of the develop branch.

**Any related open or closed issues to this bug report?**
I could not find any issues related to the shellspec workflow.

**Screenshots:**

<img width="981" alt="Error message: no enabled runners were available for more than 1 days" src="https://github.com/IQSS/dataverse/assets/1303898/2317b617-9e80-4d39-9979-b8d824570b50">

<img width="679" alt="List of queued shellspec jobs, including ones for the same PR" src="https://github.com/IQSS/dataverse/assets/1303898/3250888c-988b-4c16-a29e-ee6d797be8e0">

**Comment by pdurbin** [comment]
Huh. Interesting! Thanks for the bug report, @bencomp! I didn't realize this is happening. 🤔

**Comment by bencomp** [comment]
I found out because updating the branch for #9068 on my fork triggered this workflow to run and fail. At first I figured that there were just fewer MacOS runners, but then I saw `10.15` in the workflow file and realised Homebrew on my MacBook Pro running OSX 10.15 (the one that I had when I visited the IQSS) is always complaining that Apple and Homebrew don't support that old version anymore.

My guess is that this can be easily fixed, by changing the runner to a newer MacOS version, or to `macos-latest`. If support for 10.15 is important, I think you need to set up a self-hosted runner.
