### ISSUE TITLE
Only Built-in Users are DvObject Creators

### ISSUE THREAD

**Issue by raprasad** [IQSS/dataverse#983]
This appears to be a bug:

- A DvObject creator is a BuiltInUser
- For the new Auth model, creator should be an AuthenticatedUser. 

https://github.com/IQSS/dataverse/blob/42692f5681ee65ea982b66656d7683bf0e015725/src/main/java/edu/harvard/iq/dataverse/DvObject.java#L55

**Comment by michbarsinai** [comment]
(setting the creator field implemented locally, will push later)

**Comment by kcondon** [comment]
Shib users can create objects and are only authenticated users, not builtins. So works, closing.
