### ISSUE TITLE
Set up Sonar

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#9846]

**Comment by bencomp** [comment]
See also (linking in the other direction)

- #775
- #3950

I wonder what Sonar is going to be used for. There's a checkstyle workflow (that could be updated to highlight more issues) and similar actions for other tools exist.

(I shouldn't get involved... I'm just happy that old issues are not completely forgotten.)

**Comment by pdurbin** [comment]
Hey, @bencomp, thanks for stopping by. 😄 

I just upgraded Netbeans from 14 to 18 and it was surprisingly easy to set up SolarLint this time. (At least it seems to be going well.)

The plugin was easy to find this time:

![Screen Shot 2023-08-29 at 4 54 41 PM](https://github.com/IQSS/dataverse/assets/21006/f4d744a0-4518-46ea-acff-02afd88823dc)

I tried this "analyze" button...

![Screen Shot 2023-08-29 at 4 59 33 PM](https://github.com/IQSS/dataverse/assets/21006/21b0570c-6e1c-41af-b7db-9ab8c2c834fd)

... and stuff started happening immediately:

![Screen Shot 2023-08-29 at 5 02 42 PM](https://github.com/IQSS/dataverse/assets/21006/802f758e-d89d-46c5-9b92-0cf91988d00e)

Maybe this is because we already set up https://sonarcloud.io/project/overview?id=IQSS_dataverse earlier. 🤔 

I'm sort of surprised it's already analyzing and doing stuff. I assumed I'd have to enter some credentials for my new sonarcloud.io account or set up SonarCube server. 🤔

**Comment by poikilotherm** [comment]
As I've mentioned before - the connection is necessary to download and apply customized rulesets. Either disabling / reconfiguring or adding new rules.

**Comment by pdurbin** [comment]
I still want Sonar to be set up but I'm closing this and will let someone else be the champion.

**Comment by poikilotherm** [comment]
As per discussed during tech hour, let's do this!
