### ISSUE TITLE
Feature Request: API Guide add docs about how to update tabularTags in the files metadata

### ISSUE THREAD

**Issue by MellyGray** [IQSS/dataverse#9864]
**Overview of the Feature Request**
Include some comment or example about how to update the tabularTags of the files metadata, because when the Native API retrieves the dataset files, the tabular tags are listed as `"tabularTags":["Survey"]`. However when you try to update this data using the update metadata endpoint `/api/files/${id}/metadata`, you need to use this other key `"dataFileTags":["Survey"]` to update them.

I think is worth including some note about this in the API Guide
https://guides.dataverse.org/en/latest/api/native-api.html#updating-file-metadata

**What kind of user is the feature intended for?**
API User

**What inspired the request?**
I was trying to update "tabularTags" using the API but I was using the wrong key to update this property.

**What existing behavior do you want changed?**
Add a note to the API Guide about how to update the tabular tags of the files

**Any brand new behavior do you want to add to Dataverse?**
Update the API Guide

**Any open or closed issues related to this feature request?**

**Comment by pdurbin** [comment]
@saikiranpatil thanks! I just left a review in your pull request.
