### ISSUE TITLE
Solr 9.3.0 link is broken

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#9865]
The Solr 9.3.0 upgrade instructions instruct users to download from archive.apache.org https://github.com/IQSS/dataverse/blob/develop/doc/release-notes/9260-solr930.md?plain=1#L14
but archive.apache.org doesn't appear to offer Solr 9+: https://archive.apache.org/dist/lucene/solr/

Dataverse-Ansible is limping along with this link, unless there's a better option: https://dlcdn.apache.org/solr/solr/9.3.0/solr-9.3.0.tgz

Happy to submit a pull request with whatever URL is deemed preferable.

**Comment by pdurbin** [comment]
Let's use the fix at https://github.com/IQSS/dataverse/pull/9787/commits/eb10b86b2fb638f55e0d5209fd492e03fb2c6ac9 from @poikilotherm , please.

It works on my machine: wget https://archive.apache.org/dist/solr/solr/9.3.0/solr-9.3.0.tgz

Yes, a PR would be great! Thank you!
