### ISSUE TITLE
Feature Request/Idea: Add Standard CC and Custom Licenses to DDI Export Metadata

### ISSUE THREAD

**Issue by amberleahey** [IQSS/dataverse#9871]
**Overview of the Feature Request**
We are using DDI XML exports from Dataverse in our Odesi data catalogue for searching and exploring datasets. We'd like to be able to display the Terms and Conditions as a button with a pop-up window containing the terms of use (including licenses) and terms of access stored in Dataverse's metadata for a given dataset before a user can download from the catalogue interface. 

See beta site: https://beta.odesi.ca fully connected to Dataverse repository in the backend

**What kind of user is the feature intended for?**
All users of DDI metadata coming from a Dataverse will benefit from having Dataverse's standard licenses (Terms of Use / Terms) be cross walked and made available in DDI Exports. Standard licenses such as Creative Commons CC-0 or CC-By are not mapped to DDI exports only the Terms of Access fields. 
See example DDI exports 1) [Dataverse Record example](https://borealisdata.ca/dataset.xhtml?persistentId=doi:10.5683/SP/AUCWOZ) 2) DDI export of that example (https://borealisdata.ca/api/datasets/export?exporter=ddi&persistentId=doi%3A10.5683/SP/AUCWOZ

**What inspired the request?**
we noticed that not all the terms metadata is being exported to DDI, especially CC licenses 

**What existing behavior do you want changed?**
Would be great to map this Dataverse terms metadata to DDI's 
dataAccs>setAvail/>useStmt/>dataAccs> section, like how it's done for when a Custom License is added to Dataverse
see: DDI export with custom license available (https://dataverse.harvard.edu/api/datasets/export?exporter=ddi&persistentId=doi%3A10.7910/DVN/ICISE4)

For example (custom license mapping to DDI from example linked above):
dataAccs>setAvail/>useStmt>
disclaimer>The <i>American Journal of Political Science</i> and the Odum Institute for Research in Social Science are not responsible for the accuracy or quality of data uploaded within the <i>AJPS</i> Dataverse, for the use of those data, or for interpretations or conclusions based on their use. /disclaimer>
useStmt>
dataAccs>

**Any brand new behavior do you want to add to Dataverse?**
Support for licenses in DDI 2.6 is a bit better than DDI 2.5 --- see https://ddi-alliance.atlassian.net/wiki/spaces/DDI4/pages/2851340301/Codebook+Tree+Diagram+Version+2.6

I'm thinking about this, but could confirm if 1.1.4.4 license (0-n) [URI, type] may work or there are additional fields supported under 2.6 dataAccs (0-n) has some new fields....TBD 

**Any open or closed issues related to this feature request?**
Yes this seems related a bit, in terms of the examples provided:

- https://github.com/IQSS/dataverse/issues/3648
- https://github.com/IQSS/dataverse/issues/8355

**Comment by jggautier** [comment]
I added that https://github.com/IQSS/dataverse/issues/8355 is related, too.

**Comment by jggautier** [comment]
I rediscovered that Terms of Use metadata is missing from the exports of Dataverse installations running more recent versions of Dataverse, so I noted that in the related GitHub issue I opened at https://github.com/IQSS/dataverse/issues/8355, then realized that this issue already mentions that Terms of Use metadata is missing. So I closed https://github.com/IQSS/dataverse/issues/8355 in favor of this GitHub issue.

**Comment by jggautier** [comment]
@amberleahey, do you mind if we edit this issue's title to reflect that we're also talking about including metadata of "custom licenses"?

**Comment by amberleahey** [comment]
Any movement on this? We are now realizing a lot of the newer open datasets do not get the custom license in the DDI export and we need it to show end-users on https://odesi.ca front end. We can change our harvester workflow to use DV JSON but would prefer to get this into the core code for DDI exports.... can we go ahead and make this change and get it in via pull request now? All standard CC and custom licenses would get mapped to <dataAccs> field and would appear like this: 

For custom licenses:
<dataAccs>
<notes level="dv" type="DVN:TOU">.....</notes>

For standard licenses: 
<dataAccs><notes level="dv" type="DVN:TOU">.....</notes>

If we can just make this change in the core code to fix this issue that would be great. Then we can scope out a larger project to export DDI-Codebook according to community standards / consensus moving forward, but that will be a larger project.

**Comment by jggautier** [comment]
Hey @amberleahey! Since I'm the only other person who's commented in this GitHub issue, I'm just jumping in to say that I'm not aware of any movement on this issue and I haven't had time to help with this so I can't say if we can make the change you're proposing.

I also edited your last comment to use the "code" formatting to avoid the angle brackets problem you mentioned.

**Comment by amberleahey** [comment]
thanks, @jggautier we can make the change and test it in our local environment and then give the pull request for you to review when there is time. This will work for standard licenses and custom terms to both appear with the DVN:TOU and it will not affect restricted file terms of access which are working and appear in the DDI XML as "dataAccs -notes type="DVN:TOA" level="dv"" you know what i mean :)insert angle brackets

**Comment by qqmyers** [comment]
Weird - we seem to import a note with DVN:TOU into the terms of use in https://github.com/IQSS/dataverse/blob/1b5a1eafcd39b757f40f9561ede201ab51c0bbff/src/main/java/edu/harvard/iq/dataverse/api/imports/ImportDDIServiceBean.java#L1181-L1184, but we never write it out.

If your change puts two things into that field (terms of use or the license URL?), it might be good to update the import code to restore it to the right field?
