### ISSUE TITLE
Setting: :AllowSignUp does not prevent signup, only removes link from homepage, still appears in popup

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#988]
A new feature recently added was a setting table where various config options can be set, among them :AllowSignUp.

My understanding of the purpose this is to prevent users from creating new accounts, until an admin is ready.

One hole in this blockade is the add data button on the homepage. All visitors see the homepage and unregistered users who click it see a popup with a sign up link. It seems that maybe that link should not appear if :AllowSignUp is not enabled?

**Comment by scolapasta** [comment]
@mheppler  Can you mimic the logic from the header in the add popup?

**Comment by mheppler** [comment]
Added new AllowSignUp logic to the Sign Up link in the Add Data button on the Dataverse page when a guest is viewing the page, or you aren't logged in.

**Comment by kcondon** [comment]
OK works, closing
