### ISSUE TITLE
idempotent API call for making a user a superuser

### ISSUE THREAD

**Issue by jorgelpolanco** [IQSS/dataverse#9887]
Hello! I like to report an issue in the docker installation process, User Administration does not exist. Issue related: https://github.com/IQSS/dataverse-docker/issues/78

**What steps does it take to reproduce the issue?**
Dataverse Docker installation
* When does this issue occur?
login with the admin account
* Which page(s) does it occurs on?

* What happens?
The admin account works fine, but it doesn't have administration permissions. 

* To whom does it occur (all users, curators, superusers)?
super user. 

* What did you expect to happen?

login with admin and have admin permission.  (red color user)

**Which version of Dataverse are you using?**
v. 5.13 build 1244-79d6e57

**Any related open or closed issues to this bug report?**
https://github.com/IQSS/dataverse-docker/issues/78

In the thread, there are a solution: 

https://github.com/IQSS/dataverse-docker/issues/78#issuecomment-1549662669

**Comment by mr-loop-1** [comment]
Hi @pdurbin , I looked at the relevant code and would like to take up this issue. Please assign me.

**Comment by pdurbin** [comment]
@mr-loop-1 done! Thanks! If you have any questions, a good place to ask is #dev in https://chat.dataverse.org

**Comment by pdurbin** [comment]
@mr-loop-1 hi! I'm just checking in. We just got another report of this bug/shortcoming: https://github.com/IQSS/dataverse-docker/issues/78#issuecomment-1818577830

Is there anything you need from us?

Are you still interested in working on this?

Thanks!

**Comment by mr-loop-1** [comment]
Hi @pdurbin , really sorry for the delay. I knew what to change but didn't pushed as I wanted to check first refarding a concern I have mentioned in the pr but got involved somewhere in the meantime. Would appreciate your responce on that.

**Comment by pdurbin** [comment]
@jorgelpolanco I'm not sure if you're comfortable building Docker images from pull requests or not but there's a new one from @zearaujo25 if you'd like to play around with it:

- #10440 

The easiest way is probably to switch to the branch and then run this quickstart: http://preview.guides.gdcc.io/en/develop/developers/dev-environment.html#quickstart

**Comment by pdurbin** [comment]
I just approved #10440 but others are welcome to take a look. Thank, @zearaujo25!
