### ISSUE TITLE
Request for .gitattributes file to handle CRLF vs LF for SH Files

### ISSUE THREAD

**Issue by jp-tosca** [IQSS/dataverse#9894]
For reference: https://groups.google.com/g/dataverse-community/c/dGduT2T8F7Y

**Overview of the Feature Request**

Adding the .gitattributes file so it can make it easier for Windows users to get going on the code by just adding a file to the Git repository. 

**What kind of user is the feature intended for?**
(Example users roles: API User, Curator, Depositor, Guest, Superuser, Sysadmin)

Users of Docker

**What inspired the request?**

The use of docker and the push to welcome Windows users. 

**What existing behavior do you want changed?**

As it is mentioned in the documentation for [[Windows]](https://guides.dataverse.org/en/latest/developers/windows.html) users can set their core.autocrlf to input or false according to the [GitHub documentation](https://www.git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_core_autocrlf) but there is a way, so each individual doesn't have to do this step and also travels with the repository.

If a file .gitattributes is added to the root of the repository with the following line: 

*.sh text eol=lf

It will ignore the settings on the user for conversion of CRLF/LF line endings on .sh files, here is the [documentation](https://www.git-scm.com/docs/gitattributes) on the .gitattributes file.

**Any brand new behavior do you want to add to Dataverse?**

Can remove the step of each user to deactivate their auto conversion feautre

**Any open or closed issues related to this feature request?**

N/A

**Comment by pdurbin** [comment]
As discussed at the container meeting this morning...

video: https://harvard.zoom.us/rec/share/-s-zXjWpkUUuxOm18BBXcdJk4OsxzWkEj8JJRJ0qUm2I_22QlpMNtJb8es_o1s0E.nFGj85s7iBqiNSsc

... we'll go with @jp-tosca 's fix at 9d479e9. It seems to work well for @Sakshi-75 as discussed at https://dataverse.zulipchat.com/#narrow/stream/375812-containers/topic/gitattributes.20files.20and.20windows.20auto.20conversion/near/397315136 while the fix from @poikilotherm did not.

@jp-tosca will create a fresh pull request with his fix. He said he'd like to retest first, which makes sense. Thanks!
