### ISSUE TITLE
Ingest: Investigate how to better handle large list of slow processing files

### ISSUE THREAD

**Issue by kcondon** [IQSS/dataverse#990]
When I upload a bunch of subsettable files, such as from r_files.zip, some are really big and depending on the order of processing, the page can seem stuck, with little user feedback.

This ticket is to investigate ways to better handle these scenarios, provide more feedback, sort by size and process the smaller ones first, timeout and fail, or process in parallel rather than in queue.

**Comment by scolapasta** [comment]
@landreev can you provide some input on what are some quick things we could do this for this?

**Comment by landreev** [comment]
Spoke to Gustavo about this briefly; 
As an immediate fix/improvement, I'm doing the following: 
If you upload a few files at the same time, first one or more large files, then a bunch of small ones (just like in your scenario above), the ingest will process them ordered by size. 
So you should never end up in a situation where small and "cheap" files are stuck in progress waiting for one giant file to be processed. 
If we have to, we can further investigate modifying the queue itself; to maybe process multiple batches in parallel, if system resources are available, etc.

**Comment by kcondon** [comment]
OK, seems to work, closing
