### ISSUE TITLE
Develop a performance strategy document describing our preferred approaches and tools

### ISSUE THREAD

**Issue by scolapasta** [IQSS/dataverse#9919]
At a recent tech hours we started discussing some strategies for performance monitoring during the dev cycle.

This issue is to capture our desired strategies in a document that we can review and revise for future use. The person picking this up would start the document and, of course, reach out, to others to comment and edit, as needed. We can then review again until we have the final document.

**Comment by kcondon** [comment]
More than monitoring? Strategy to build for and maintain performance during development and production.

**Comment by pdurbin** [comment]
I just created a doc at https://docs.google.com/document/d/1Lbl0NJaoV6WOYmP-Mw6UZaA9KYSyliu2ABgs2xNdOKU/edit?usp=sharing

Time to start writing! 😅

**Comment by pdurbin** [comment]
Good meeting at tech hours. Thanks, all.

At standup yesterday @scolapasta said he'd decide where to do go next with this effort.

My offer to create a new "performance" page for the dev guide based on the doc still stands, if that helps.

**Comment by scolapasta** [comment]
OK, finally reviewed the doc, looks good and I agree with the suggestion to write this up asa new Performance page as part of the dev guide. Will move this back to This Sprint so it can be picked up for that.
