### ISSUE TITLE
API vs UI: inconsistency between required permissions for listing role assignments

### ISSUE THREAD

**Issue by vera** [IQSS/dataverse#9926]
**What steps does it take to reproduce the issue?**

Via UI:

* Open dataset you have ManageDatasetPermissions permission for
* Click Edit dataset > Permissions > Dataset
* See list of users/groups with assigned roles

Via API:

* GET request for api/datasets/<id>/assignments for dataset with id you have ManageDatasetPermissions permission for
* Receive permissions error

I have searched through the code and I think that is because the ManageDataverse permission is required?

https://github.com/IQSS/dataverse/blob/v6.0/src/main/java/edu/harvard/iq/dataverse/engine/command/impl/ListRoleAssignments.java#L18

**What did you expect to happen?**

I expected the API call to succeed

**Which version of Dataverse are you using?**

5.13

**Any related open or closed issues to this bug report?**

No, I didn't find any

**Screenshots:**

List of role assignments in UI:

![image](https://github.com/IQSS/dataverse/assets/16904069/4a90a2cf-c0ff-448c-b9a3-33e9f4e885aa)

**Comment by pdurbin** [comment]
@vera thanks you're probably right. When we get around to building this UI for the [new frontend](https://github.com/IQSS/dataverse-frontend) (or sooner), we'll need to address this. Thanks for bringing this to our attention!

**Comment by johannes-darms** [comment]
@pdurbin : I think this in unrelated to the UI and rather requires a change of ACLs for the API call. As @vera pointed out, we just need to change the `RequiredPermissions` in this case to  from `ManageDataversePermissions` to `ManageDatasetPermissions`.

**Comment by pdurbin** [comment]
@johannes-darms oh, I see. Would you or @vera like to create a pull request we can look at?
