### ISSUE TITLE
Setup API test VM (apitest.dataverse.org) at hmdc

### ISSUE THREAD

**Issue by esotiri** [IQSS/dataverse#993]
Moving apitest.dataverse.org from Azure to HMDC.

**Comment by pdurbin** [comment]
@esotiri as we discussed, we're going to move apitest.dataverse.org to dvn-vm2.hmdc.harvard.edu which was recently kickstarted. To do:

- [ ] install Glassfish 4.1
- [ ] apply Weld patch
- [ ] configure Jenkins job

**Comment by esotiri** [comment]
TowRavens setup documentation:
Rapache: https://drive.google.com/drive/u/0/#folders/0B3_V6vFxEcx-RS1OMGg3YUpCVDQ/0By40CG63udC_T2pZTFBIeURtZGc/0By40CG63udC_cGo2ZGNFTFgtcms
TwoRavens: https://drive.google.com/drive/u/0/#folders/0B3_V6vFxEcx-RS1OMGg3YUpCVDQ/0By40CG63udC_T2pZTFBIeURtZGc/0By40CG63udC_cGo2ZGNFTFgtcms

**Comment by pdurbin** [comment]
I did this stuff:

- [ ] lots of automation at https://build.hmdc.harvard.edu:8443/job/apitest.dataverse.org-deploy/
- [ ] new SHA-256 SSL cert to make Google happy (certs and key backed up to /nfs/backups)
- [ ] enforce SSL with Apache
- [ ] made sure the feedback form makes [a ticket](https://help.hmdc.harvard.edu/Ticket/Display.html?id=192205) 

I took a swing at getting TwoRavens working but it's beyond me. @scolapasta @eaquigley and I seem to agree that it's not necessary for an API testing box so I'm passing this to QA.

**Comment by kcondon** [comment]
Ok, did basic smoke test and works for purpose of api testing. Closing.
