### ISSUE TITLE
dev guide: add jvm-option required for HarvestingServerIT.testMultiRecordOaiSet to succeed

### ISSUE THREAD

**Issue by donsizemore** [IQSS/dataverse#9931]
In perhaps a "required jvm-options" subheading beneath Integration Tests at https://guides.dataverse.org/en/latest/developers/testing.html

```
asadmin create-jvm-options "-Ddataverse.oai.server.maxidentifiers=2"
asadmin create-jvm-options "-Ddataverse.oai.server.maxrecords=2"
```

Pull request forthcoming.

**Comment by pdurbin** [comment]
@donsizemore thanks! Very likely your PR should mark this issue as closes as well:

- #9738
