### ISSUE TITLE
Signposting Authors links issues

### ISSUE THREAD

**Issue by luddaniel** [IQSS/dataverse#9940]
Hello there, 

By working on [Signposting parameters (dataverse.signposting.level1-author-limit and dataverse.signposting.level1-item-limit)](https://guides.dataverse.org/en/latest/installation/config.html?highlight=signposting#dataverse-signposting-level1-author-limit) and crawling the Java code, we found 2 issues :

- When author type and identifier fields are correctly filled, level 1 does not display a correct link 
    Ex: Given `type=ORCID` and `idvalue=0000-0002-3202-0263` it prints `Link: <0000-0002-3202-0263>;rel="author"` instead of `Link: <https://orcid.org/0000-0002-3202-0263>;rel="author"`
- When you have more authors than the limit, level 2 does not display links for authors and it should display them all unlike level 1

Also there is comment [//If no type and there's a value, assume it is a URL (is this reasonable?)](https://github.com/IQSS/dataverse/blob/d674d6687f8ade869b285c4853d8722b6112a240/src/main/java/edu/harvard/iq/dataverse/util/SignpostingResources.java#L215) : I would say that it's reasonable if it's a valid URL. As [FAIR Signposting Profile](https://signposting.org/FAIR/) suggest it must be a link and looks at the end at least like "http(s)://(domain)/(author-id)" not only "(author-id)".

PR is already done.

**Comment by qqmyers** [comment]
@cmbz - there is already a PR awaiting prioritization for this issue: #9941

**Comment by cmbz** [comment]
**2023/12/13**
- As per [Jim's comment](https://github.com/IQSS/dataverse/issues/9940#issuecomment-1854580905), please see PR: #9941. Moving #9941 to 6.2 proposals.
