### ISSUE TITLE
equals() methods check for wrong class in several classes

### ISSUE THREAD

**Issue by bencomp** [IQSS/dataverse#9951]
**What steps does it take to reproduce the issue?**

* When does this issue occur?
It *should* cause failures in unit tests, but the `equals(Object)` methods are rarely covered by unit tests.

* Which page(s) does it occurs on?
Not on pages, but in several classes.

* What happens?
The `.equals(Object)` method checks if the `other` object is of a different class than itself. This happens in

    - DataverseFacet (checks for DatasetFieldType)
    - DatasetFieldDefaultValue (checks for DatasetField)
    - DataverseContact (checks for DatasetFieldType)
    - DataverseFeaturedDataverse (checks for DatasetFieldType)
    - DataverseTheme (checks for DatasetFieldType)

* To whom does it occur (all users, curators, superusers)?
Failing tests should "occur" for developers.

* What did you expect to happen?
Unit tests should fail on equality tests.

**Which version of Dataverse are you using?**
Current development branch.

**Any related open or closed issues to this bug report?**
No.

**Screenshots:**

https://github.com/IQSS/dataverse/blob/5fc7b30d02e684f76bb985faeaef9e0becd69107/src/main/java/edu/harvard/iq/dataverse/DataverseFacet.java#L94-L101

**Comment by Sakshi-75** [comment]
Hi @bencomp ,
Can I work on this?

**Comment by bencomp** [comment]
@Sakshi-75 sure!

**Comment by Sakshi-75** [comment]
Hi @bencomp ,
I've fixed the equals method in all these classes. I was thinking of adding unit tests for them so that in future if someone changes them then the test would fail but I don't see any existing test files for any of these classes. Should I go ahead and create them?

**Comment by bencomp** [comment]
That would be great. For a PR I think it is best to only add tests for the `equals` methods in the newly created files, so that it is easy to review. I think there is an example in another test file.

Note that I am not a maintainer, so while I can comment and make suggestions, my approval doesn't count and I cannot help with getting a PR merged. (Some of my Hacktoberfest PRs from last year are still open.) But please don't let that stop you!
