### ISSUE TITLE
Linkset contains links that are rejected  by the API 

### ISSUE THREAD

**Issue by markwilkinson** [IQSS/dataverse#9957]
**What steps does it take to reproduce the issue?**

* When does this issue occur?

In a record's linkset, there are describedby links as follows;

```
<https://dataverse.harvard.edu/api/datasets/export?exporter=schema.org&persistentId=doi:10.7910/DVN/Z2JD58>
rel="describedby"
type="application/json+ld"
```

Attempting to retrieve this using curl 

```
curl -v -H "Accept: application/json+ld" "https://dataverse.harvard.edu/api/datasets/export?exporter=schema.org&persistentId=doi:10.7910/DVN/Z2JD58"
```
results in a 406 (API rejection) error

* Which page(s) does it occurs on?

* What happens?

406 error

* To whom does it occur (all users, curators, superusers)?

* What did you expect to happen?

Return me some yummy JSON :-)

**Which version of Dataverse are you using?**

current harvard dataverse release (5.14?)

**Any related open or closed issues to this bug report?**

**Screenshots:**

No matter the issue, screenshots are always welcome.

To add a screenshot, please use one of the following formats and/or methods described here:

* https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests
*

**Comment by qqmyers** [comment]
@markwilkinson - thanks for testing Signposting! I'm making fixes as you go in #9955. For this issue, it looks like requesting application/ld+json (versus json+ld) already works, so you can get the response that way as a workaround. The PR updates to use ld+json linkset.
