### ISSUE TITLE
Metadata Blocks: Displaying Custom Metadata Blocks for Specific Dataverses

### ISSUE THREAD

**Issue by eaquigley** [IQSS/dataverse#996]
From @posixeleni: I was thinking about this related to issue #833 where I am making "custom metadata blocks" for certain Dataverses which we would not want to display at the root level as options for everyone to pick. Is there a way to only show Custom Metadata Blocks for the specific Dataverses they apply to (parent and children of)? These will be confusing for others to see since this metadata should not be an option that is available to all Dataverses.

**Comment by eaquigley** [comment]
@posixeleni is this a duplicate? since these are appearing in the UI already, i'm feeling like yes.

**Comment by posixeleni** [comment]
@eaquigley sorry catching up right now. You mean that they have already resolved the issue of displaying custom metadata blocks for only specific Dataverses? If thats the case then this can be closed. This ticket was made last year to keep track of this issue.

**Comment by posixeleni** [comment]
This is a duplicate ticket. Closing since we are now hiding custom metadata blocks from showing for all Dataverses.
