### ISSUE TITLE
API-Endpoint attribute/filePIDsEnabled not working?

### ISSUE THREAD

**Issue by lmaylein** [IQSS/dataverse#9968]
According to
https://guides.dataverse.org/en/latest/api/native-api.html#change-collection-attributes
I want to disable file dois for one of our dataverses:
```
curl -X PUT -d 'true' http://localhost:8080/api/admin/settings/:AllowEnablingFilePIDsPerCollection
{"status":"OK","data":{":AllowEnablingFilePIDsPerCollection":"true"}}

curl -H "X-Dataverse-key:*********" -X PUT  "http://localhost:8080/api/dataverses/sinologie/attribute/filePIDsEnabled?value=false"
{"status":"ERROR","code":404,"message":"API endpoint does not exist on this server. Please check your code for typos, or consult our API guide at http://guides.dataverse.org.","requestUrl":"http://localhost:8080/api/v1/dataverses/sinologie/attribute/filePIDsEnabled?value=false","requestMethod":"PUT"}
```
I was not sure if $ID in the documentation meant the short name of the dataverse so I also looked for the numeric id in dvobjects. But it does not work with that either.

Am I doing something wrong or is the documentation incorrect at this point?

**Comment by lmaylein** [comment]
I forgot to say: Dataverse version 5.13

**Comment by pdurbin** [comment]
Sorry, it's a 5.14 feature: https://guides.dataverse.org/en/5.14/api/native-api.html#change-collection-attributes

**Comment by lmaylein** [comment]
Sorry. My mistake.
