### ISSUE TITLE
Netbeans, integration tests, Docker

### ISSUE THREAD

**Issue by pdurbin** [IQSS/dataverse#9974]
Now that we've merged...

- #9273

.... Netbeans users see `Caused by: java.lang.IllegalStateException: Could not find a valid Docker environment. Please see logs and check configuration` if they try to build and don't have Docker running.

From the [thread](https://iqss.slack.com/archives/C010LA04BCG/p1696448584278029) in Slack, @poikilotherm suggests reconfiguring Netbeans like this:

![image](https://github.com/IQSS/dataverse/assets/21006/23739f90-9412-4c53-9d18-15249fbefa07)

We should try it out and make a PR to update a future versions of https://guides.dataverse.org/en/6.0/developers/classic-dev-env.html#build-the-dataverse-software-war-file above where we say to click build in Netbeans:

![Screenshot 2023-10-04 at 5 14 13 PM](https://github.com/IQSS/dataverse/assets/21006/45339c64-3ac1-41b7-b619-9e1e9cebd897)

**Comment by poikilotherm** [comment]
I think I'm in favor of skipping any Testcontainers test when no Docker is available.

Simply using `@Testcontainers(disabledWithoutDocker = true)` does the trick.

**Comment by pdurbin** [comment]
@poikilotherm sounds like a great fix for now.

Longer term, we should figure out where we want the integration tests to run. I don't know if Docker is installed on Jenkins or the EC2 instances it spins up, for example.

**Comment by poikilotherm** [comment]
FWIW: They already run in Github Actions, just not for the unit tests job, but in the IT job right after :wink:

**Comment by pdurbin** [comment]
Right, right. I think we touched on this briefly during the container meeting this morning. That's how Coveralls gets updated, by GitHub Action. So as we add integrations tests, our coverage shown there should go up.
