### ISSUE TITLE
OpenAPI endpoint is broken

### ISSUE THREAD

**Issue by JR-1991** [IQSS/dataverse#9981]
**What steps does it take to reproduce the issue?**

The `openapi` endpoint provided by Payara results in an internal server error in version 6.0. For example, the endpoint does not function on [Demo Dataverse (v6.0)](https://demo.dataverse.org/openapi/), although it does on [Harvard's Dataverse (v5.14)](https://dataverse.harvard.edu/openapi). Click on each link to reproduce the error.

**Which version of Dataverse are you using?**

Dataverse 6.0

**Comment by pdurbin** [comment]
Thanks for discussing this and opening this issue, @JR-1991!

I showed the stacktrace below (from my laptop running 7e0738e, the latest from the develop branch) to @poikilotherm and he found what seems to be a related issue on the Payara side:

- https://github.com/payara/Payara/issues/6369

Here's the stacktrace: [openapi-error.txt](https://github.com/IQSS/dataverse/files/12831430/openapi-error.txt)

**Comment by pdurbin** [comment]
Today @poikilotherm suggested using https://github.com/OpenAPITools/openapi-generator which would not be dependent on Payara (should also work if we switched to Wildfly or OpenLiberty, etc.). Also, it doesn't require the app server to be running.

**Comment by cmbz** [comment]
2024/01/08: Prioritized and moved to Needs Sizing during prioritization meeting.

**Comment by cmbz** [comment]
2024/01/08: Moved to Needs Sizing during today's prioritization meeting

**Comment by cmbz** [comment]
2024/01/16: Recommendation to create a separate spike (10) to investigate the tool suggested here: https://github.com/IQSS/dataverse/issues/9981#issuecomment-1780921206

**Comment by cmbz** [comment]
2024/01/16: spike created: https://github.com/IQSS/dataverse/issues/10236

**Comment by cmbz** [comment]
2024/01/16: Moved to waiting. Work will continue via https://github.com/IQSS/dataverse/issues/10236 while we wait for response from Payara.

**Comment by pdurbin** [comment]
This just in. Someone has come up with a potential fix for Payara:

- https://github.com/payara/Payara/pull/6563

**Comment by pdurbin** [comment]
I just built that PR with this:

```
sdk use java 11.0.20-tem
mvn clean install -T 16 -PQuickBuild -DskipTests
```

Then I uploaded it to Google Drive: https://drive.google.com/file/d/17kVKOco86FDKXvs1aBZLq9QBABxO8S5A/view?usp=drive_link

I haven't tested it to see if /openapi works or not.

**Comment by cmbz** [comment]
2024/03/14
- JP will reference this issue in his PR and when it's closed this issue will be too.

**Comment by pdurbin** [comment]
> This just in. Someone has come up with a potential fix for Payara:
> 
> -  https://github.com/payara/Payara/pull/6563

This PR was just closed as already fixed. See:

- https://github.com/payara/Payara/pull/6563#pullrequestreview-1973804792 
- https://github.com/payara/Payara/pull/6546

**Comment by poikilotherm** [comment]
Payara 6.2024.4 RC1 is just in today. I suppose there will be a new release soon. We should update our version of Payara as it also contains my MPC NPE fix. We can check back again if it started working again.

**Comment by jp-tosca** [comment]
If this is the case we should probably have to decide what to do with #10328 here are a few things to consider:

- We should remove the endpoints added to serve the spec
- We should discuss if we keep using the smallrye plugin, according to the documentation shared to us by @poikilotherm if a .yaml or .json file are provided under /WEB-INF the server would provide these files.
- We still may need to include the changes done to the API methods and the annotations added on this #10328 or the spec will be similar at the one provided at https://dataverse.unc.edu/openapi which shows some of the errors solved, I am not sure how will the spec generated the payara will take this yet, as soon as the new release is up I can test it.
