### ISSUE TITLE
OpenAPI specification JSON-LD request bodies are invalid

### ISSUE THREAD

**Issue by JR-1991** [IQSS/dataverse#9982]
**What steps does it take to reproduce the issue?**

Upon retrieving the openAPI specifications from [Harvard's Dataverse](https://dataverse.harvard.edu/openapi), it appears that a couple of endpoints (listed below) do incorporate invalid request bodies. For example, the `/api/v1/datasets/{id}/actions/:releasemigrated` endpoint has the following specifications:

```yaml
/api/v1/datasets/{id}/actions/:releasemigrated:
    post:
      operationId: publishMigratedDataset
      parameters:
      - name: id
        [...]
      - name: updatepidatprovider
        [...]
      requestBody: {} # invalid
      responses:
        [...]
```

Further analysis of the endpoints revealed that most of them are associated to a JSON-LD body. Here is a table of all endpoints that contain the previously mentioned invalid `requestBody` attribute:

| Endpoint                                                | JSON-LD body | Method |
|---------------------------------------------------------|--------------|--------|
| `/api/v1/datasets/{id}/actions/:releasemigrated`          | ✅            | POST   |
| `/api/v1/datasets/{id}/metadata`                          | ✅            | PUT    |
| `/api/v1/datasets/{id}/metadata/delete`                   | ✅            | PUT    |
| `/api/v1/dataverses/{identifier}/datasets`                | ✅            | POST   |
| `/api/v1/dataverses/{identifier}/datasets/:startmigration` | ✅            | POST   |
| `/api/v1/dataverses/{identifier}/metadatablocks/:isRoot`  | ❌            | POST   |
| `/api/v1/dataverses/{identifier}/metadatablocks/isRoot`   | ❌            | PUT    |
| `/api/v1/inbox`                                           | ✅            | POST   |

**Which version of Dataverse are you using?**

v5.14 at Harvard's Dataverse instance.

**Any related open or closed issues to this bug report?**

Due to the currently broken `openapi` endpoint mentioned in #9981 this may only be able to be addressed once the other has been resolved.

**Comment by pdurbin** [comment]
@JR-1991 what are your thought on this issue? As you know the /openapi output will be complete different in the next release, generated by SmallRye instead of Payara thanks to this PR:

- #10328

Would it be best to close this issue and open small ones for small chunks of work we can schedule over time? Whatever you feel is best!

**Comment by JR-1991** [comment]
@pdurbin I am happy to close this issue and open new ones for smaller tasks. The majority of this issue has been solved by the recent merge 🙂
