### ISSUE TITLE
Getting "Unknown protocol: perma"

### ISSUE THREAD

**Issue by gonetil** [IQSS/dataverse#9988]
I am working on a Dataverse installation which uses permalinks (instead of DOI or HANDLE).
To configure permalinks, I have run the following commands:

```
./asadmin create-jvm-options '-Ddataverse.pid.permalink.base-url=OUR_BASE_URL
curl -X PUT -d perma http://localhost:8080/api/admin/settings/:Protocol
curl -X PUT -d 10915 http://localhost:8080/api/admin/settings/:Authority
curl -X PUT -d "datos/" http://localhost:8080/api/admin/settings/:Shoulder
```

**What steps does it take to reproduce the issue?**

When adding a dataset, the permalink seems to be generated correctly:

BASE_URL/dataset.xhtml?persistentId=perma%3A10915%2Fdatos%2F1JSTWU&version=DRAFT

However, I am getting a 404 error page. In the server.log I see "Unknown protocol: perma" . According to [Dataverse config. page](https://guides.dataverse.org/en/latest/installation/config.html#protocol), perma is a correct value (as well as doi and handle). 

I have already restart Glassfish as well as the whole server just in case, but it didn't resolve the issue. What I am missing?
Thanks in advance!

We are using Dataverse v. 5.13 build 1244-79d6e57
I am attaching the full server log, in case it is usefull to work this out.

[dataverse-server.log](https://github.com/IQSS/dataverse/files/12856791/dataverse-server.log)* https://help.github.com/en/articles/file-attachments-on-issues-and-pull-requests
*

**Comment by donsizemore** [comment]
@gonetil I think you want to upgrade to 5.14. In version 5.13 of the docs there is no `perma` protocol: https://guides.dataverse.org/en/5.13/installation/config.html#protocol

**Comment by pdurbin** [comment]
Right, it was added in 5.14 in this pull request:

- #8674

@gonetil if you need help upgrading: https://guides.dataverse.org/en/5.14/installation/intro.html#getting-help

Please go ahead and close this issue if you feel moved to do so. 😄

**Comment by gonetil** [comment]
Thanks a lot, that was it. Since it was a new installation, I decided to throw it all away and start with a brand new installation over Dataverse 6.0 .

I kinda feel moved to close this now  ;-)
